### ISSUE TITLE
Ntopng for each ethXX and separated indexes in elasticsearch for each ethXX

### ISSUE THREAD

**Issue by JKeySZR** [ntop/ntopng#100]
I  try to set up ntopng for the following problem (task):
I have two channels  (in future can be more)
one channel is responsible for the Internet channel, the second is for  the server segment.
They are traffic chanels , I want to analise the  traffic flowing through this traffic chanels and store it all in elasticsearch db
I have set up 2 ntopng each with its own configuration file, so that each thread is stored in its own <idx type>
Connection diagram is shown below:
![Image of scheme_connect](http://software-radar.com/sites/default/files/images/articles/36/test_structure.png)

However, I faced with such a problem:
If I run one process ntopng, all stored in elasticsearch,  as intended.

However, if I turn 2  ntopng (as shown), then I get the mess in elasticsearch.
Traffic from  c <idx type> traff_wan is stored in traff_srvlan and vice versa.
The example in the picture below.
![Image of elasticsearch index](http://software-radar.com/sites/default/files/images/articles/36/elastic_wrong.png)

Questions:
1. is  such  realization coreect for  this task?
2. Such cross  behavior is problem  on the side of ntopng, because of 2 processes on one  server or on the side of  elasticsearch?

**Comment by lucaderi** [comment]
I'm not an ES expert, but if I would be you I would create two different ES indexes
