### ISSUE TITLE
Name Incorrect

### ISSUE THREAD

**Issue by animosity022** [ntop/ntopng#1002]
Where does the Name field get populated from?

I have a name that doesn't seem to come from anywhere that I can figure out:

http://i.imgur.com/8CkJhDu.png

```
felix@plex: ~$ host 192.168.86.1
1.86.168.192.in-addr.arpa domain name pointer speedy.animosity.us.
felix@plex: ~$ host speedy
speedy.animosity.us has address 192.168.86.1
```

I have n=1 configured for my DNS name resolution. I've tried stopping/cleaning out my data dir and starting fresh yet the name keeps persisting.

**Comment by emanuele-f** [comment]
Maybe it comes from DHCP?

**Comment by animosity022** [comment]
192.168.86.1 is my DHCP and internal DNS resolver.

```
cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 192.168.86.1
search animosity.us
```

I tried wiping out all the data/mysql ntopng database and restarting fresh to see if it goes away, but I can't figure out where it's pulling that name from.

```
 cat /etc/hosts
127.0.0.1	localhost
192.168.86.30	plex.animosity.us plex

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

Rebooted a few times as well as that name was a router distro I tried for a few hours and it has been gone for some time now.

**Comment by emanuele-f** [comment]
If you think this might come from a previous ntopng configuration, you have to wipe redis data as well (redis-cli flushall). If you can provide a pcap file with dhcp / dns traffic, we can inspect it.

**Comment by animosity022** [comment]
redis-cli flushall was the last step I was missing.

It's working fine now and resolving properly!

Thanks!
