### ISSUE TITLE
iface_local_stats.lua:24: attempt to index a nil value

### ISSUE THREAD

**Issue by Kaldek** [ntop/ntopng#1003]
I've just installed a licensed 2.4.160627 - Pro Small Business Edition of ntopng on Windows 2012 R2.

After changing my interface to use a friendly name, from "\Device\NPF_{72B608E9-1BD9-4518-87CE-C8E2486AB82B}" to "Sniffer", the logs are now saying:

27/Feb/2017 15:44:42 [Lua.cpp:5134] WARNING: Script failure [D:\ntopng\scripts\lua\iface_local_stats.lua][D:\ntopng\scripts\lua\iface_local_stats.lua:24: attempt to index a nil value]

In addition to the script error, "Network Interfaces: Realtime Traffic" shows no data and the bitrate gauge at the bottom of the window also shows no data.
![image](https://cloud.githubusercontent.com/assets/26052829/23349091/2f090ace-fd04-11e6-904a-981e8d70832c.png)

![image](https://cloud.githubusercontent.com/assets/26052829/23349104/42e6e336-fd04-11e6-9bb4-e1cfe6108a72.png)

However, all other functions of ntopng appear to be working.

**Comment by Kaldek** [comment]
OK so I reinstalled and with a stock install the problem went away.  This time the difference is that I'm still running as LOCAL SYSTEM rather than a dedicated account and I started the service the very first time listing only the interface I used for packet capture rather than all interfaces.  I still renamed the capture interface.  So, that can't be the problem.

Hmm, now to check if the different account affected it.  Changing back to localsystem didn't help before.

**Comment by emanuele-f** [comment]
What do you mean with localsystem?

**Comment by Kaldek** [comment]
Sorry I was referring to the SYSTEM user account in Windows, as used below by the ntopng service:

![image](https://cloud.githubusercontent.com/assets/26052829/23382287/b204ebb4-fd95-11e6-8533-d8f8ca24a441.png)

**Comment by emanuele-f** [comment]
I see. The Windows package is outdated. I suggest you to move to a Linux based distribution like Ubuntu or Centos where the latest packages are available. Nevertheless, if you can spot the problem on Windows, maybe some other users can take advantage.

**Comment by simonemainardi** [comment]
> I started the service the very first time listing only the interface I used for packet capture rather than all interfaces

on windows, if you decide to start the parameters of an installed service, you have to remove the service first with /r , and then install it again with /i (see the user guide for additional information)
