### ISSUE TITLE
Lua.cpp:5856] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/hourly.lua][...ng/pro/scripts/lua/modules/top_scripts/top_aggregate.lua:111: attempt to index a nil value]

### ISSUE THREAD

**Issue by lucadistefano** [ntop/ntopng#1004]
we get hourly the following warning:
Lua.cpp:5856] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/hourly.lua][...ng/pro/scripts/lua/modules/top_scripts/top_aggregate.lua:111: attempt to index a nil value]

there is a way to fix it?

Thanks,
Luca

v.2.5.170217 [Enterprise/Professional Edition]
GIT rev:   dev:1cc159c09e1646b09ce6b4f8526cdac8e0c598ae:20170217
Pro rev:   r957
Built on:  CentOS release 6.8 (Final)

**Comment by emanuele-f** [comment]
Hi, do you have VLANs?

**Comment by simonemainardi** [comment]
I confirm this happens with VLANs

**Comment by lucadistefano** [comment]
yes we have vlans

Luca
Inviato da iPhone

**Comment by lucaderi** [comment]
Check added. Please resync and report. Reopen if necessary.
