### ISSUE TITLE
Ntopng Nagios send_nsca configuration parameter validation error

### ISSUE THREAD

**Issue by PSmolders** [ntop/ntopng#1005]
Using Ubuntu Server 16.04, ntopng 2.5.170228.

I am trying to connect my Nagios server to ntopng using the web GUI. Nagios was disabled in the GUI, so I switch it on, fill in the Nagios/ntopng host information and click to apply. Then I get an error message stating: [Lua.cpp:6235] WARNING: Script failure [/usr/share/ntopng/scripts/lua/admin/prefs.lua][/usr/share/ntopng/scripts/lua/modules/http_lint.lua:864: [LINT] _POST["nagios_send_nsca_config"] = "/usr/local/nagios/etc/send_nsca.cfg" parameter error: Validation error]. The same error show up in syslog and upon refreshing the page, Nagios is again disabled in the GUI.

I checked out the scripts referenced by the error and in the http_lint.lua script is a function trying to verify the filepath. It is also commented in that function that filepaths should not have dots in them. As a test I changed the validation handler for the nagios_send_nsca_config to verifyUnchecked. The web GUI now responds that everything is okay, but it still won't send any alert to Nagios. 

According to the web GUI, the nsca config file should be entered with .cfg appended to it, so why would there be a function that errors on a dot? I followed http://www.ntop.org/guides/ntopng-integration-with-nagios/ for setting up Nagios, nscp and ntopng. Nagios and nscp do work correctly, just not with ntopng. The nsca config file does exist in the right location, for testing purposes has 777 and is not empty.

Do you have any help or ideas how to fix this? I would like to have ntopng emit alerts to Nagios without any problems.

**Comment by emanuele-f** [comment]
Parameter error is fixed in 0bbcc64 . Please manually run ntopng in verbose mode and filter its output like this `ntopng -v4 | grep system`, then report the log here. It should be something like this (with error in my case):

```
28/Feb/2017 15:41:01 [NagiosManager.cpp:105] system() returned -1
sh: line 1: /usr/local/nagios/bin/send_nsca: No such file or directory
```

**Comment by PSmolders** [comment]
```
28/Feb/2017 15:51:01 [NagiosManager.cpp:105] system() returned -1
28/Feb/2017 15:51:02 [NagiosManager.cpp:112] system() returned -1
28/Feb/2017 15:52:02 [NagiosManager.cpp:105] system() returned -1
28/Feb/2017 15:52:03 [NagiosManager.cpp:112] system() returned -1
```

The alert is set up to fire every minute.

**Comment by emanuele-f** [comment]
Please try to execute this command, substituting the arguments according to your specific configuration:

`echo "TestMessage     0       This is a test message" | /usr/local/nagios/bin/send_nsca -H localhost -p 5667 -c /usr/local/nagios/etc/send_nsca.cfg`

**Comment by PSmolders** [comment]
`0 data packet(s) sent to host successfully.`
I can confirm the bin and cfg are in the correct places. 

When disconnecting NSCA I get:
`Connection refused by host
Error: Could not connect to host 192.168.90.98 on port 5667`
as would be expected.

Edit:
If I write "TestMessage 0 This is a test message" to a text file, properly tab the columns and use it as input for NSCA, it does work correctly.

Edit:
Some more information from the Nagios log.
```
[02-28-2017 16:47:03] External command error: Command failed
Informational Message[02-28-2017 16:47:03] Error: External command failed -> PROCESS_SERVICE_CHECK_RESULT;ntopng-host;NtopngAlert_iface_4;0;service OK
Informational Message[02-28-2017 16:47:03] Warning: Passive check result was received for service 'NtopngAlert_iface_4' on host 'ntopng-host', but the service could not be found!
External Command[02-28-2017 16:47:03] EXTERNAL COMMAND: PROCESS_SERVICE_CHECK_RESULT;ntopng-host;NtopngAlert_iface_4;0;service OK
```
Apparantly, ntopng appends the interface number to the NtopngAlert, while it is setup to use just NtopngAlert.

**Comment by simonemainardi** [comment]
Ntopng sends alerts to Nagios via NSCA messages using properly formatted service descriptions. You get the error as you didn't define a proper description

ntopng outputs NSCA service descriptions that are compliant with the following convention:
<nagios_service_description_as_configured>_<IP address or CIDR network or interface name>_<time granularity>_<alert type>

It's up to you to define services in the nagios configuration files that match with the convention above. Any nagios-defined service will capture its corresponding NSCA messages. Messages with undefined service names are just ignored.

```
define service{
       use passive_service
       service_description NtopngAlert
       host_name ntopng-host
}

define service{
       use passive_service
       service_description NtopngAlert_192.168.1.9_min_bytes
       host_name ntopng-host
}
 
define service{
       use passive_service
       service_description NtopngAlert_192.168.70.0/24_min_ingress
       host_name ntopng-host
}
  
define service{
       use passive_service
       service_description NtopngAlert_192.168.70.0/24_min_egress
       host_name ntopng-host
}

define service{
       use passive_service
       service_description NtopngAlert_192.168.1.0/24_min_ingress
       host_name ntopng-host
}
```


Service examples that capture ntopng alerts are:

![image](https://cloud.githubusercontent.com/assets/3397663/23547935/6cd52d16-0005-11e7-9579-c6abf7cf598a.png)

![image](https://cloud.githubusercontent.com/assets/3397663/23547937/714a7c7a-0005-11e7-84ff-ff8765da3e62.png)
