### ISSUE TITLE
The repository 'http://packages.ntop.org/apt/18.1 x64/ Release' does not have a Release file.

### ISSUE THREAD

**Issue by hoppushoppard** [ntop/ntopng#1008]
**Issue**
After installing repository and performing respective steps, apt writes
`The repository 'http://packages.ntop.org/apt/18.1 x64/ Release' does not have a Release file.`

I'm using Linux Mint 18.1. Serena (based on Ubuntu 16.04). 

**Steps to reproduce**
I've installed apt-ntop-stable.deb, using described steps on your install page.

**16.04 LTS**
```
wget http://apt-stable.ntop.org/16.04/all/apt-ntop-stable.deb
dpkg -i apt-ntop-stable.deb
```
after that, apt stuff
```
apt-get clean all
apt-get update
apt-get install ntopng
```

Apt says it the repository doesn't have a Release file and thus updating can't be done securely. This repository will be disabled by default.
```
E: The repository 'http://packages.ntop.org/apt/18.1 x64/ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://packages.ntop.org/apt/18.1 all/ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

btw.
apt clean is sufficient (see http://askubuntu.com/a/144224/85661)

**Comment by simonemainardi** [comment]
thanks for reporting. Linux Mint is not officially supported for the packaged versions. Please compile from sources or use one of the packaged versions available at: http://packages.ntop.org/

**Comment by Karlheinzniebuhr** [comment]
Having the same issue on ubuntu 18.04 Server

**Comment by simonemainardi** [comment]
@Karlheinzniebuhr show the error. Are you with ubuntu 18.04 Server? Release files seem to be in place for the 18.04: http://packages.ntop.org/apt/18.04/

**Comment by simonemainardi** [comment]
ok let's continue the discussion at the new issue you've open: https://github.com/ntop/ntopng/issues/2100

**Comment by a-essawy** [comment]
check this
https://github.com/ntop/ntopng/issues/2100#issuecomment-782788011
