### ISSUE TITLE
Missing LDAP Server address field

### ISSUE THREAD

**Issue by olivierbeytrison** [ntop/ntopng#1009]
Running Ntop-NG 2.5.170228 - Pro Small Business Edition
In preferences, when activating LDAP authentication, the ldap server address field is not displayed.

![image](https://cloud.githubusercontent.com/assets/2838126/23498212/cae07c74-ff26-11e6-844c-583f42e0bd9b.png)

**Comment by emanuele-f** [comment]
Thank you.

**Comment by olivierbeytrison** [comment]
Thanks. But I'd rather put the server address field before the ldap anonymous binding.

`local elementToSwitch = {"row_multiple_ldap_account_type", "row_toggle_ldap_anonymous_bind","server","ldap_server_address","bind_dn", "bind_pwd", "search_path", "user_group", "admin_group"}`

And while submitting the form I always get a validation error :

/usr/share/ntopng/scripts/lua/modules/http_lint.lua:864: [LINT] _POST["bind_dn"] = "_cn=adminAuth,ou=persons,o=system_" parameter error: Validation error

**Comment by olivierbeytrison** [comment]
Thanks, now it's possible to save the ldap configuration !
