### ISSUE TITLE
Error compile ndpi-netfilter

### ISSUE THREAD

**Issue by jerric12** [ntop/ntopng#101]
Hi,
I've installed ntopng/ndpi on a Debian Jessie and it works fine.
I need to associate with Netfilter. I tried to compile ndpi-netfilter with the instructions of ewildgoose.
I have these errors. Do you have an idea ? Can you help me please ?
Thanks
--------------------------------------------------------------------------------------------------------------------------
root@firewall:/opt/nDPI/ndpi-netfilter# make
make -C ipt
make[1]: Entering directory '/opt/nDPI/ndpi-netfilter/ipt'
if test -d ndpi_cpy; then \
        cp /src/* ndpi_cpy -R; \
else \
        mkdir ndpi_cpy; \
        cp /src/* ndpi_cpy -R; \
fi
cp: cannot stat '/src/*': No such file or directory
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/opt/nDPI/ndpi-netfilter/ipt'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2
---------------------------------------------------------------------------------------------------------------------

**Comment by lucaderi** [comment]
Sorry we do not maintain this code. Please ask the author to send us a patch and we will integrate it

**Comment by jerric12** [comment]
Sorry. Thanks :-)
