### ISSUE TITLE
 WARNING: Script failure [/Users/simone/code/ntopng/scripts/callbacks/5min.lua][/Users/simone/code/ntopng/scripts/callbacks/5min.lua:10: module '5min' not found:

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#1014]
no field package.preload['5min']
	no file '/Users/simone/code/ntopng/pro/scripts/callbacks/5min.lua'
	no file '/Users/simone/code/ntopng/scripts/lua/modules/5min.lua'
	no file './5min.lua'
	no file '/usr/local/share/luajit-2.0.3/5min.lua'
	no file '/usr/local/share/lua/5.1/5min.lua'
	no file '/usr/local/share/lua/5.1/5min/init.lua'
	no file './5min.so'
	no file '/usr/local/lib/lua/5.1/5min.so'
	no file '/usr/local/lib/lua/5.1/loadall.so']

**Comment by emanuele-f** [comment]
git pull on the pro branch does not work?

**Comment by emanuele-f** [comment]
Sorry, I missed to push the file
