### ISSUE TITLE
NTOPNG-Mysql

### ISSUE THREAD

**Issue by JoelAGBESSI** [ntop/ntopng#1018]
Hello, I've tried the NTOPNG-MYSQL solution but i'm facing an Issue in database. We are unable to get the proto list and corresponding ID. 
Regards

**Comment by emanuele-f** [comment]
Hi, MYSQL is used in ntopng to export flows, so you can only get the per-flow protocol.

For the full list of protocols IDs you should check out nDPI https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_protocol_ids.h
