### ISSUE TITLE
FR: Ability to alert based on protocol

### ISSUE THREAD

**Issue by PSmolders** [ntop/ntopng#1019]
Would it be possible to add a feature that generates an alert when a specific protocol is detected? For instance, generate an alert whenever Netflix traffic is detected on a certain interface or host. Or is there some way to do this already?

**Comment by emanuele-f** [comment]
In my opinion a global per-interface preference would be enough. Alternatively, we can set a preference on the host pools.

Algorithm (supposing per interface preference)

1) When we periodically scan 1 minute alerts, inside check_host_alerts we will call
  getHostInfo to get the ndpiStats associated to the host.

2) We keep a redis set of disallowed protocols for the interface. If the ndpistats
   contains such a protocol, we generate an alert

**Comment by lucaderi** [comment]
I suggest to handle this as a standard alarm by setting a threshold on a L7 protocol per host. No complex things here. Just make sure that in addition to p2p (as it is today) users can have their own protocol configured

**Comment by emanuele-f** [comment]
We could add a button into the alerts configurations page to pop up a dialog where we can specify the protocol to alarm. Then we generalize thresholds to work with any protocols.

**Comment by simonemainardi** [comment]
Added as task in https://github.com/ntop/ntopng/issues/1808
