### ISSUE TITLE
Can't view historical data of non-active local host

### ISSUE THREAD

**Issue by wdbasson** [ntop/ntopng#102]
When trying to view the historical of a non-active host (from the Top Local Hosts part of a report) I get an error: "Host *.*.*.* cannot be found. Perhaps this host has been previously purged from memory or it has never been observed by this instance."

OS: Ubuntu 14.04.2 LTS (GNU/Linux 3.18.0-22-rpi2 armv7l)
ntopng: v.2.0.150611 [Professional/Embedded Edition]

# cat /etc/ntopng/ntopng.conf
-G=/var/tmp/ntopng.pid
-i=eth1

**Comment by lucaderi** [comment]
This feature has been implemented. When a local host (and only them as they have rrd files) is requested but the host is not active, a page with a URL asking to re-activate the host is shown. Instead if you just directly to the URL of the host historical tab, the host is re-activated immediately and the graphs are shown with no further work.
