### ISSUE TITLE
ntopng start issue

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#1020]
Issue with ntop start, starts but says failed.
Cannot stop, have to kill -9.

Debian Wheezy

Starting
======

root@eros:/var/run# ps ax | grep ntopng
24914 pts/1    S+     0:00 grep ntopng
root@eros:/var/run#

root@eros:/var/run# /etc/init.d/ntopng start
[FAIL] Starting ntopng:[....] Unable to start ntopng ... failed!
 failed!
root@eros:/var/run#

yet it works

root@eros:/var/run# ps ax | grep ntopng
24928 pts/1    Dl     0:03 /usr/bin/ntopng /etc/ntopng/ntopng.conf
25026 pts/1    S+     0:00 grep ntopng
root@eros:/var/run#

Stopping
=======

root@eros:/var/run# /etc/init.d/ntopng stop
[....] Stopping ntopng:root@eros:/var/run#
root@eros:/var/run#

root@eros:/var/run# ps ax | grep ntopng
24928 pts/1    Dl     0:28 /usr/bin/ntopng /etc/ntopng/ntopng.conf
25250 pts/1    S+     0:00 grep ntopng
root@eros:/var/run#

root@eros:/var/run# kill -9 24928
root@eros:/var/run#

root@eros:/var/run# ps ax | grep ntopng
25254 pts/1    S+     0:00 grep ntopng
root@eros:/var/run#

Thanks;

**Comment by emanuele-f** [comment]
Hi, please specify ntopng version (-V option)

**Comment by ghost** [comment]
# ntopng -V
v.2.5.170306 [Enterprise/Professional Edition]

**Comment by emanuele-f** [comment]
Please also post the configuration used (content of /etc/ntopng/ntopng.conf)

**Comment by ghost** [comment]
~# cat /etc/ntopng/ntopng.conf
-i="tcp://127.0.0.1:5556"
-m="103.x.x.0/22,103.x.x.0/22,43.x.x.0/22,103.x.x.0/24"
--max-num-flows=256000
--max-num-hosts=256000
-v=5

**Comment by ValentinaViscarelli** [comment]
@rosstola 
you have forgotten -G option in your configuration file.
Please add this row and try again:
-G=/var/run/ntopng.pid

Let me know.
Thanks

**Comment by ValentinaViscarelli** [comment]
@rosstola 
After changing configuration file please restart the machine in order to be sure that your environment is clear.

**Comment by ghost** [comment]
Yep that fixed it, thanks :)
Off to the nprobe issues list, same problem with that!
