### ISSUE TITLE
LDAP : Validation error : bind_dn can contain space

### ISSUE THREAD

**Issue by olivierbeytrison** [ntop/ntopng#1021]
bind_dn is validated by ```validateSingleWord``` (http_lint.lua:706)

but you can have spaces in a DN, in my case the bind_dn contains a space and thus the ldap configuration fail.

**Comment by emanuele-f** [comment]
Fixed. Thank you for reporting.

**Comment by olivierbeytrison** [comment]
Thanks, issue fixed, and now ldap authentication work !

👍
