### ISSUE TITLE
Hosts page broken for view: interfaces (#1015)

### ISSUE THREAD

**Issue by PSmolders** [ntop/ntopng#1022]
Using ntopng 2.5.170306 on Ubuntu Server 16.04

Same problem as #1015 , but this time for ZMQ interfaces combined into a view.

I have 2 ZMQ interfaces combined into a view and the hosts page does not work, keeps saying: "No results found".

**Comment by simonemainardi** [comment]
A new build is in progress. Try to update in an hour. FWIW, I've just tried to reproduce and everything works as expected even with views of ZMQ interfaces:


![image](https://cloud.githubusercontent.com/assets/3397663/23624877/8bba5ea0-02a7-11e7-8052-530e402497ee.png)

**Comment by emanuele-f** [comment]
Fix commit reference: https://github.com/ntop/ntopng/commit/0b29b4b7edfaad6b2d3756f25aec39b1008f6364

**Comment by PSmolders** [comment]
Thanks, it is fixed now.
