### ISSUE TITLE
network interface timeseries only has data for 1 hour

### ISSUE THREAD

**Issue by trickius** [ntop/ntopng#1023]
Hi,
i'm just checking Community/Embedded Edition v.2.5.170212 and i've come to this issue (If it's an issue that is) that graphs only 1 hour data for any timeframe i choose for my network interface.

**Comment by simonemainardi** [comment]
there's a series of buttons above the chart that allows you to select a different timespan:
![image](https://cloud.githubusercontent.com/assets/3397663/23618583/0a48780e-0291-11e7-8905-db6008eff0db.png)

**Comment by trickius** [comment]
Hi, thanks for the quick reply. Yes i know and this is what i was hoping to get an answer for. Those buttons aren't working.  Perhaps there's an error somewhere with some script isn't working but i can't quite figure it out. Runtime status isn't reporting something wrong either.

**Comment by simonemainardi** [comment]
ok, now I see. A bug that was preventing time-scale change has been fixed recently. Please, hold on until a new embedded edition build is available. @lucaderi please trigger a new rpi build.

**Comment by trickius** [comment]
Will do! Thanks a lot!

**Comment by simonemainardi** [comment]
@trickius the new rpi package is available, give it a try! http://packages.ntop.org/RaspberryPI/jessie_pi/armhf/ntopng/

**Comment by trickius** [comment]
Yeap! It works fine now! Thanks a lot!
