### ISSUE TITLE
Generate Alerts/Block Traffic By Country

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1024]
As ntopng uses GeoIP, it knows what traffic belongs to what country. It is requested to extend the host pool rules to all a list of countries that are blacklisted by ntopng (i.e. when used in bridge more traffic from/to this list of countries is blocked) and an alert is generated.

**Comment by simonemainardi** [comment]
Added as task in https://github.com/ntop/ntopng/issues/1808
