### ISSUE TITLE
Multiple ntopng instances on same host share a single pf_ring clusterID

### ISSUE THREAD

**Issue by dando-it** [ntop/ntopng#1026]
I'm running running multiple ntopng instances on single host, each bound to a specific NIC with pf_ring enabled.

 * ntopng_p2p1 ( -i=p2p1 -g=12 ...)
 * ntopng_p2p2 ( -i=p2p2 -g=13 ...)

Every NIC gets a copy , from TAPs, of completely different traffic sources, so i need to keep them separated.

Checking the stats of pf_ring seems that each socket use the same "Cluster Id" (0).
From what i know, this could raise some incoerence in the traffic separation.
It's possible to configure a specific clusterid when configuring a ntopng instance ?

Thanks

Environment:

* Centos 7.3 (stock kernel)
* pf_ring 6.4.1 (stable rpm)
* ntopng 2.5 (dev -v.2.5.170306 - compiled from src)

> _[root@ntop]# ps_
> nobody    28507 25.2   Ssl  04:03 130:00 /usr/bin/ntopng /etc/ntopng/ntopng_p2p1.conf
> nobody    28612 28.4   Ssl  04:04 145:55 /usr/bin/ntopng /etc/ntopng/ntopng_p2p2.conf

> _[root@ntop]# cat /proc/net/pf_ring/28507-p2p1.19842_
> Bound Device(s)    : p2p1
> Active             : 1
> Breed              : Standard
> Appl. Name         : ntopng
> Socket Mode        : RX+TX
> Capture Direction  : RX only
> Sampling Rate      : 1
> IP Defragment      : No
> BPF Filtering      : Disabled
> Sw Filt Hash Rules : 0
> Sw Filt WC Rules   : 0
> Hw Filt Rules      : 0
> Sw Filt Hash Match : 0
> Sw Filt Hash Miss  : 0
> Poll Pkt Watermark : 8
> Num Poll Calls     : 0
> Channel Id Mask    : 0xFFFFFFFFFFFFFFFF
> **Cluster Id         : 0**
> Slot Version       : 16 [6.4.1]
> Min Num Slots      : 32770
> Bucket Len         : 1514
> Slot Len           : 1720 [bucket+header]
> Tot Memory         : 56373248
> Tot Packets        : 1765013321
> Tot Pkt Lost       : 0
> Tot Insert         : 1765013321
> Tot Read           : 1765013321
> Insert Offset      : 29812256
> Remove Offset      : 29812256
> Num Free Slots     : 32770
> TX: Send Ok        : 0
> TX: Send Errors    : 0
> Reflect: Fwd Ok    : 0
> Reflect: Fwd Errors: 0

> _[root@ntop]# cat /proc/net/pf_ring/28612-p2p2.19843_
> Bound Device(s)    : p2p2
> Active             : 1
> Breed              : Standard
> Appl. Name         : ntopng
> Socket Mode        : RX+TX
> Capture Direction  : RX only
> Sampling Rate      : 1
> IP Defragment      : No
> BPF Filtering      : Disabled
> Sw Filt Hash Rules : 0
> Sw Filt WC Rules   : 0
> Hw Filt Rules      : 0
> Sw Filt Hash Match : 0
> Sw Filt Hash Miss  : 0
> Poll Pkt Watermark : 8
> Num Poll Calls     : 0
> Channel Id Mask    : 0xFFFFFFFFFFFFFFFF
> **Cluster Id         : 0**
> Slot Version       : 16 [6.4.1]
> Min Num Slots      : 32770
> Bucket Len         : 1514
> Slot Len           : 1720 [bucket+header]
> Tot Memory         : 56373248
> Tot Packets        : 3256008961
> Tot Pkt Lost       : 0
> Tot Insert         : 3256008961
> Tot Read           : 3256008960
> Insert Offset      : 22125256
> Remove Offset      : 22124832
> Num Free Slots     : 32770
> TX: Send Ok        : 0
> TX: Send Errors    : 0
> Reflect: Fwd Ok    : 0
> Reflect: Fwd Errors: 0

**Comment by cardigliano** [comment]
@dando-it, cluster id 0 means that there is no cluster configured, don't worry.
