### ISSUE TITLE
The data retention time may still not working properly

### ISSUE THREAD

**Issue by lhxhanson** [ntop/ntopng#1028]
#939 
Several days ago, we use dev instead of the stable version. But we got some strange log:
![image](https://cloud.githubusercontent.com/assets/5568373/23685774/e72d2634-03e0-11e7-8e92-ea6b33d9fd7c.png)

After these log came out, I use a simple script to run SHOW FULL PROCESSLIST to get the MySQL state every 1s. And it looks like the data retention still start at 8:00 not 0:00:
![image](https://cloud.githubusercontent.com/assets/5568373/23685888/8109152e-03e1-11e7-9e59-2a863611012f.png)

**Comment by simonemainardi** [comment]
ok, so please tell me it the clock that you see at the bottom-right corner of the ntopng UI is reporting a proper timezone.

**Comment by lhxhanson** [comment]
Here is the ntopng' time
![image](https://cloud.githubusercontent.com/assets/5568373/23731691/f92a10bc-04a9-11e7-9b41-dbb7189dafad.png)
Here are the system info of timezone:
![image](https://cloud.githubusercontent.com/assets/5568373/23731732/274a88be-04aa-11e7-80ac-af194ff5655e.png)

**Comment by simonemainardi** [comment]
It looks like ntopng is not able to properly determine your timezone as it says +0000 rather thatn +0800.

what is your OS and distro?

**Comment by lhxhanson** [comment]
My running version is ntopng-2.5.170221-2297.x86_64

**Comment by simonemainardi** [comment]
os and distro?

**Comment by lhxhanson** [comment]
@simonemainardi 
CentOS 6.8 (64 bit) with kernel-2.6.32-642.el6.x86_64

**Comment by emanuele-f** [comment]
We have added a debug print to show the timezone offset of the system. The new package will be available in one hour. Please update and report the offset you see in the ntopng startup log.

```
10/Mar/2017 12:31:13 [Ntop.cpp:130] System Timezone offset: +3600
```

**Comment by lhxhanson** [comment]
@emanuele-f 
I have updated to the newest version. Here is the log:
![image](https://cloud.githubusercontent.com/assets/5568373/23839287/e9e769e8-07d7-11e7-885a-b62c44c95249.png)

**Comment by simonemainardi** [comment]
Fixed. Thanks for reporting. A new build is in progress. Please try in an hour.

**Comment by lhxhanson** [comment]
@simonemainardi  thanks for fixing.
By the way, when will the stable version fix this too?

**Comment by simonemainardi** [comment]
as soon as we release version 2.6. Hopefully in 1-2 weeks from now.
