### ISSUE TITLE
No RX traffic recorded on the LAN facing interface of NAT gateway

### ISSUE THREAD

**Issue by wdbasson** [ntop/ntopng#103]
I have ntopng installed on a NAT gateway. No RX traffic is recorded on the LAN facing interface. No TX traffic is recorded on the WAN facing interface.

Maybe it is a problem with my settings? (It used to work fine with older versions of ntopng and it still works on the ARM version.)

![screenshot from 2015-08-01 15 48 37](https://cloud.githubusercontent.com/assets/9715479/9022053/d3c3d0d2-3864-11e5-8490-f9740685a4cf.png)

# OS
Ubuntu 14.04.2 LTS (GNU/Linux 3.16.0-30-generic x86_64)

# ntopng --version
v.2.0.150801 [Professional Edition]
GIT rev:   dev:5858829c60282d8a9914ccd5d23fa31ab2177fe8:20150801
Pro rev:   r410

# cat /etc/ntopng/ntopng.conf
-G=/var/tmp/ntopng.pid
-F=sqlite

**Comment by lucaderi** [comment]
I am unable to reproduce your problem. Can you please try again with the latest build and see if works now? Are you using PF_RING perhaps?

**Comment by wdbasson** [comment]
Tried with the latest build and still experiencing the same problem. I assume I'm using PF_RING because it's installed by default.

**Comment by lucaderi** [comment]
Can you please check if with pfcount (part of PF_RING) do you see the traffic? In all cases, please file an issue on PF_RING and not on ntopng as the problem seems to be there.
