### ISSUE TITLE
L7 Protocol page generates an error

### ISSUE THREAD

**Issue by johnydoo** [ntop/ntopng#1030]
The L7 Protocol page generates an error for some protocols (but not all). The error can be reproduced by clicking on “Peers” from an individual Host and then click on the L7 Protocol.
SSL.Google will give this error:

```
Script "/usr/share/ntopng/scripts/lua/flows_stats.lua" returned an error:
/usr/share/ntopng/scripts/lua/modules/http_lint.lua:862: [LINT] _GET["application"] = "SSL.Google" parameter error: Validation error
```

 SSL.Facebook, SSL.Amazon, QUIC.Google are not working either.

HTTP and SSL are working fine!

Ntopng version 2.5.170308

**Comment by emanuele-f** [comment]
Thank you for reporting!
