### ISSUE TITLE
Realtime traffic graphs are not in sync

### ISSUE THREAD

**Issue by PSmolders** [ntop/ntopng#1031]
Using ntopng 2.5.170308-2479 on Ubuntu Server 16.04.02

The realtime graphs on the dashboard page are not in sync. The graph for Realtime Top Application Traffic takes 5 seconds per step, just like the live update timer, and the Network Interfaces: Realtime Traffic graph updates takes 3 seconds every step. The result is 2 graphs that don't quite correspond on peaks, ie. 1 graph notes a peak of 7 mbit at one point, while the other graph notes a peak of 17 mbit at another point. This is an issue on networks with a lot of high, unpredictable and short-lasting peaks.

**Comment by simonemainardi** [comment]
thanks for reporting. The issue has been fixed. A new binary package is being rebuilt and will be available in an hour.
