### ISSUE TITLE
Traffic reports only for 1h and 1m

### ISSUE THREAD

**Issue by trickius** [ntop/ntopng#1032]
Hi, trying the new version 2.5.170307 for ntopng Pro [Small Business Edition]/Embedded, i came up to this finding. Traffic reports works only for 1h and 1m. All other options including custom timeframe generation aren't working. Funny thing is that mouse on point in the non existent graphs works.

![image](https://cloud.githubusercontent.com/assets/26226953/23699896/a8cb8cbe-03f9-11e7-9318-a3b201f3df64.png)

**Comment by simonemainardi** [comment]
can you please try to CTRL+SHIFT+R to reload the javascript and also try with another browser

**Comment by trickius** [comment]
Tried again refreshing as you mentioned but no good. This is happening also with chrome 56.0.2924.87 and firefox v.51 browser.

**Comment by simonemainardi** [comment]
I'm trying to reproduce with no luck. Everything works here.

Please, check ntopng logs for any possible error, and also open the browser inspector (right click on the web page -> inspect element) to see if there are any javascript errors there.

**Comment by PSmolders** [comment]
Using 2.5.170308 on Ubuntu Server 16.04.02
Accessing ntopng using Firefox 51.0.1

I don't have any issues either

**Comment by trickius** [comment]
Hi again, i am running arm version on a raspberry pi.

This is an error i'm receiving in the browser dubugging console

![image](https://cloud.githubusercontent.com/assets/26226953/23707634/c0d048a0-041b-11e7-8316-b945a6f1a7b7.png)

**Comment by simonemainardi** [comment]
please help us with the debugging, follow the link that points to `report.lua` in the debugger and see if you can understand the point that trigger the error

**Comment by trickius** [comment]
It's an error in the js. All i can find is this:
![image](https://cloud.githubusercontent.com/assets/26226953/23769738/06de0c6c-0519-11e7-95bb-15480b4e1003.png)

sorry i can't provide you with much more info with my limited knowledge.

**Comment by emanuele-f** [comment]
Do you have a lot of active hosts (in the 10000 order)? If you only select one Network Interface from the dialog that appears by clicking the checkbox button in the picture, can you see a difference?

![screenshot at 2017-03-10 12-19-38](https://cloud.githubusercontent.com/assets/5488003/23793511/ed6e6c36-058b-11e7-9bf0-8599a93b3e05.png)

**Comment by trickius** [comment]
No barely 20 hosts are in my network. I choose the loopback interface but same things happen.

**Comment by simonemainardi** [comment]
@trickius can you send me access and credentials to inspect your ntopng UI? You can do it privately at mainardi ntop org

**Comment by trickius** [comment]
Hi, i have authorized privately mr mainardi by email to my ntopng installation. Plz inform me when you finish inspecting to revoke permission. Thanks a lot.

**Comment by simonemainardi** [comment]
thanks, we're looking at it

**Comment by simonemainardi** [comment]
@trickius we've released a new RPI build with the fix. Please, try to update.

**Comment by trickius** [comment]
Yeap, it's working now. Thanks a lot!
