### ISSUE TITLE
Automatic update of flows page broken

### ISSUE THREAD

**Issue by PSmolders** [ntop/ntopng#1034]
Using ntopng 2.5.170308 on Ubuntu Server 16.04.02

The flows page only updates once after opening or manually refreshing the page instead of every 5 seconds.

**Comment by simonemainardi** [comment]
can't reproduce. Refresh works properly with

```
mainardi@ubuntu16:~/PF_RING$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

right click on the flows page and hit inspect element to see if there are any errors there

**Comment by PSmolders** [comment]
I can't see any erros, I can also see that the lua receives the data every time the 5 second refresh is triggered. But the page will not update after the first time.

**Comment by simonemainardi** [comment]
So AJAX requests are properly triggered and received. Try with a different browser, also make sure there's no extension or other stuff that is preventing the page from being updated.

If you still can't solve it, open the inspector, browse ntopng JS source files, place a breakpoint in the success function of the AJAX call (https://github.com/ntop/ntopng/blob/dev/httpdocs/inc/flows_stats_id.inc#L72) of file https://github.com/ntop/ntopng/blob/dev/httpdocs/inc/flows_stats_id.inc to see if it is reached and why rows aren't updated.

**Comment by PSmolders** [comment]
The success function is called every 5 seconds. I tested it with Firefox 51, Edge and IE and it still does not work correctly. The only extension I have is uBlock, and it is disabled on ntopng webinterface.

**Comment by emanuele-f** [comment]
Please try to disable uBlock globally since it may prevent external libraries to be loaded.

**Comment by PSmolders** [comment]
Unfortunately, still no luck. The automatic updates on any other pages works fine, it's just the flows page that's stubborn.

**Comment by PSmolders** [comment]
It also seems the first row is printed twice. So the first and second row of the flows page is exactly the same, I checked all columns and parameters.

**Comment by simonemainardi** [comment]
@PSmolders can you open an access to your ntopng web ui? I just want to try it and see. Feel free to send me the access privately at mainardi ntop org

**Comment by PSmolders** [comment]
I'm sorry, but I can't do that. We are a business with highly confidential data (medical personnel files among others) and it's just not possible to allow any opportunity for any scrap of data to leave the building or to allow others in. I can take censored screenshots and provide logfiles of anything you might need. 

If it can't be fixed or if I am the only case, then so be it, I'll wait for other updates then. I'm not mad or angry or anything. I think this is a great product. It's just that I'm reporting bugs as I come across them.

**Comment by simonemainardi** [comment]
ok, I understand. The real issue here is that I can't reproduce using ubuntu 16 LTS. 

Please, enclose censored screenshots and any other information that can help us with the debugging

**Comment by PSmolders** [comment]
This will stay like this forever. I've left it on for over an hour and still the flows page does not update.
![flows](https://cloud.githubusercontent.com/assets/8997593/23891071/cd5f42d8-0894-11e7-929b-0a660a82609b.png)

Content of GET requests. The flow_key parameter is the same every round of requests, but the _ parameter increments every GET request.
![get](https://cloud.githubusercontent.com/assets/8997593/23891070/cd5e0af8-0894-11e7-990e-3441b2a043c8.png)

The log file while the flows page was open in another tab. Recorded with Debug log level.
![log](https://cloud.githubusercontent.com/assets/8997593/23891072/cd5f76b8-0894-11e7-9e26-b3cccd6d95de.png)

Startup parameters.
```ntopng --interface "tcp://localhost:5556" --interface "tcp://localhost:5557" --interface "view:tcp://localhost:5556,tcp://localhost:5557" --daemon --http-port "192.168.90.98:3000" --local-networks "192.168.0.0/16" --dump-flows "mysql;localhost;ntopng;flows;(username);(password)" --dns-mode "1" --sticky-hosts "none" ```

Ntopng version.
```
Version	2.5.170314
Platform	Debian stretch/sid [x86_64][Ubuntu 16.04.2 LTS] - 64 bit
```

The pages of the Hosts tab like the Host Pools and the Looking Glass all work fine.

**Comment by simonemainardi** [comment]
- what is the interface that was selected when taking the screenshots? The view? Or one of the other two? It looks like you have duplicate flows. Any chance the same flows are seen twice, one time per interface?
- Did you censored this json or it is as-is?
![image](https://cloud.githubusercontent.com/assets/3397663/23892551/59b040ba-089b-11e7-8698-b87e8354b8b1.png)

**Comment by PSmolders** [comment]
This JSON is as-is, it is not censored. I took the screenshots on the view interface. I can't seem to find any duplicate flows between interfaces 1 and 2. The orange-blue bars denoting the client-server traffic all turn completely orange, with one or two turning 50% orange and 50% blue, while there definitely is traffic flowing both ways. The coloring happens at the point where the page refuses to update, it works fine when I first open the page and in the first couple of seconds.

**Comment by simonemainardi** [comment]
if you visit a non-view interface, do you get proper refresh for the flows page?

**Comment by PSmolders** [comment]
No

**Comment by emanuele-f** [comment]
I'm trying to replicate your setup with a ZMQ interface and a view interface but with no luck. Can you point us to a previous ntopng version where the problem did not happen?

Please also note that:
- You are using ZMQ interfaces, so nProbe will introduce some delay on the exporting of the information
- If a flow expires (e.g. the hosts terminate that connection) then it is normal that the flows page will "freeze" the row and show its last value.
- You won't see new flows into the flows page unless you reload the page, and this is normal.

**Comment by PSmolders** [comment]
I believe I first spotted the issue around version 2.5.170306 or 07. Based on your two last bullet points, it seems like the software is expiring all flows on screen, while they are not actually expired in the backend. I can confirm that there are active connections to RDP servers that don't magically all disconnect or expire at the same time. It also affects all flows on the page, not just some that might have expired, but all. It all happens after the first automatic reload of the page data. All values are frozen and the client/server colored bars all turn completely orange. Note that I don't have any issues on any other page, they all reload correctly and their values never freeze.

**Comment by PSmolders** [comment]
I found the problem. I had the local host timeout set to 30 minutes and the remote host and idle flow timeouts set to 1 hour. I reset these to default and lo and behold, it is working again.

I had these values tuned up to be able to view flows concerning remote hosts from the Not Assigned host pool, so I could see who connected to a certain remote host. Is this intended or a bug?

**Comment by simonemainardi** [comment]
You shouldn't retain idle flows for such a long time. However I still don't understand why it looks like you have duplicate flows (at least according to the browser inspector screenshot attached). Can you please re-check?

**Comment by PSmolders** [comment]
I can now see some duplicate flows from the view interface. Duplicates have the exact same numbers as the original. Upgraded to 2.5.170320 today.

**Comment by emanuele-f** [comment]
Can you describe your nProbe setup? Are you sure that the same traffic cannot be seen by both the probes with your setup?

**Comment by PSmolders** [comment]
I have a server with 3 ethernet ports, 1 for the management interface and 2 for nProbe. The nProbe interfaces are connected to the WAN SPAN ports of our 2 routers, which are set up as load balancers of the entire network. The only way traffic could be duplicated is if the flow would be split over the incoming WAN ports.

**Comment by emanuele-f** [comment]
The fact that you see exactly two copies, in the view interface, of the flows with the same values is a symptom that there is actually flow duplication taking place. Please check out your network configuration.

**Comment by simonemainardi** [comment]
@PSmolders can you please explain so maybe other users can benefit from the solution? Was it actually a configuration issue?

The function that determines the uniqueness of a flow is implemented in : https://github.com/ntop/ntopng/blob/dev/src/Flow.cpp#L1486

**Comment by PSmolders** [comment]
Due to the load balancing nature of our setup, it is impossible to completely prevent any duplicates. But the original issue was about the flows page not updating properly, which was fixed by tuning down some 'in memory' settings. I am not too worried about duplicate flows.
