### ISSUE TITLE
Edit/rename interface names with ntopng/pfsense

### ISSUE THREAD

**Issue by tpresence** [ntop/ntopng#1035]
It appears that previously I was able to edit the interface names within ntop, but somehow I can't seem to do this anymore.  Did something change?  If I have to edit a file now, where do I do this?

For some odd reason, it appears that I wasn't logged in as admin.  No idea how this happened, or that it was even possible.  Ignore this post.

**Comment by simonemainardi** [comment]
look under the gear icon in the interface page
