### ISSUE TITLE
Interface Menu Enhancements

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1038]
It is requested in the interfaces menu to
- add an icon (similar to the view icon for interface views) that identifies flow-collection interfaces and another for physical ethernet interfaces
- next to the interface name add the packet drop percentage (or nothing if no drops have been reported)

**Comment by simonemainardi** [comment]
implemented

Notes: to keep the UI as smooth as possible the following choices have been made
- a 'cloud' icon has been used to identify 'remote' zmq interfaces (the eye icon is used for views)
- no icon is used for physical interfaces
- a red drop is shown next to the interface name, provided that the number of packet drops is greater than the 1% of the total number of packets
- as soon as the user chooses an interface with drops, he/she immediately reaches the if_stats page with the same red drop icon that it is self explanatory and immediately brings the attention to the drops

![image](https://user-images.githubusercontent.com/3397663/28770739-87ffff3e-75e0-11e7-88d2-0aad2ab5dcd8.png)
