### ISSUE TITLE
layer-7 traffic policies 

### ISSUE THREAD

**Issue by LionHear7** [ntop/ntopng#104]
Cannot block any protocol set in the blacklist

Starting ntop with:
ntopng -i bridge:eth1,eth2
and adding a protocol (eg. Skype) in the blacklist for a host, the traffic is not blocked at all

ntopng release. v.2.0.150530 [Professional/Embedded Edition]
EdgeRouter Lite : v.1.2.0

**Comment by yurifrancalacci** [comment]
As Luca wrote on the mailing list (http://www.gossamer-threads.com/lists/ntop/misc/39097), Skype is blocked mainly at login.
Did you check the blacklist also with other protocols?

**Comment by LionHear7** [comment]
Yes, I tried with other protocols as well (Youtube,Facebook, Wikipedia, HTTP). Skype was an example.

So let's use Wikipedia as the blocked protocol. 
In the bridge overview the "Filtered Packets" counter rises correctly when using Wikipedia, but I still can browse its pages.

**Comment by lucaderi** [comment]
If the filter counter increases packets are not forwarded. Are you sure you haev setup all properly? Can you please paste screenshots and a picture of your network topology?

**Comment by LionHear7** [comment]
Edge Router Lite interfaces:
- eth0 disconnected
- eth1 attached to a single PC
- eth2 on the Internet with a public IP
 
![edge_router](https://cloud.githubusercontent.com/assets/5438716/9070617/fd902daa-3af0-11e5-8ae8-5547a51f7055.png)

**Comment by lucaderi** [comment]
Can you please test http://packages.ntop.org/Ubiquity/mips/ntopng_2.0.150805-374_mips.deb

**Comment by lucaderi** [comment]
@LionHear7 Did you test the new build?
