### ISSUE TITLE
Interface to SNMP Binding

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1041]
In the interface menu, when SNMP is configured there are some issues to be fixed.
- The menu entry must be renamed to "SNMP Bind" to "SNMP"
- The page must explain with a short sentence the idea behind this work
- If a SNMP device is selected, there must be a link to jumping to the SNMP view of the selected device
- When listing the SNMP devices, some devices must be discarded. Example you should read the ifType SNMP column and include only some selected interface such as ethernetCsmacd. The list of types to be displayed must be put on a Lua table/array inside the page code so that we can add new types in the future

**Comment by emanuele-f** [comment]
Fixed with 11953e3ede7af3a8422b913d6842b970d13d2097
