### ISSUE TITLE
Dashboard Graphs Blank

### ISSUE THREAD

**Issue by rich2012** [ntop/ntopng#1043]
Network Interfaces: Realtime Traffic and Network Interfaces: Last Day View are blank.

Also, the 3 gauges at the bottom don't show any traffic (bandwidth usage, Local to Remote and Remote to Local) 

Ntopng for Windows v. 2.4.160627 - Pro Small Business Edition

![capture](https://cloud.githubusercontent.com/assets/26150587/23961474/699ebeb6-0981-11e7-9b3b-a2bbc9c91bb6.JPG)

**Comment by simonemainardi** [comment]
please use the browser inspector to investigate possible js errors (right click -> inspect element)

**Comment by rich2012** [comment]
I do see the attached error. I tried Chrome and IE and neither one shows data in the graph or any traffic on the gauges.

![capture](https://cloud.githubusercontent.com/assets/26150587/23962916/00776884-0986-11e7-887e-e6164af95a2c.JPG)

**Comment by simonemainardi** [comment]
please attach the full error not just a small snippet of it

**Comment by rich2012** [comment]
SyntaxError: Invalid character
   {
      [functions]: ,
      __proto__: { },
      description: "Invalid character",
      message: "Invalid character",
      name: "SyntaxError",
      number: -2146827274,
      stack: "SyntaxError: Invalid character
   at jQuery.parseJSON (http://ntop:3000/js/jquery.js:8482:3)
   at success (http://ntop:3000/lua/about.lua:401:6)
   at fire (http://ntop:3000/js/jquery.js:3119:5)
   at self.fireWith (http://ntop:3000/js/jquery.js:3231:7)
   at done (http://ntop:3000/js/jquery.js:9275:5)
   at callback (http://ntop:3000/js/jquery.js:9685:8)"
   }

**Comment by simonemainardi** [comment]
I'm sorry but there's not enough information to understand there the problem can be. Can you please try and enclose the error as reported by chrome?

**Comment by rich2012** [comment]
Here is the inspection log from Chrome.


[ntop-1489600792075.docx](https://github.com/ntop/ntopng/files/845578/ntop-1489600792075.docx)

**Comment by emanuele-f** [comment]
Hi, any chance to update to the 2.5 development version? Many bugs have already been fixed in it since we are moving toward the next stable release.

Note for the update: you will need to clean your environment by doing these steps: stop ntopng, flush redis (redis-cli flush all), flush ntopng data directory (e.g. rm -rf /var/tmp/ntopng), setup the development repository and replace ntopng

**Comment by rich2012** [comment]
That sounds good. How do I install the dev version on Windows?

**Comment by emanuele-f** [comment]
I'm sorry but the dev packages are not available for windows right now.

**Comment by simonemainardi** [comment]
we will release a new windows build shortly. pleasde stay tuned.

**Comment by simonemainardi** [comment]
Closing as the bug is fixes in the dev. Will be distributed in the next windows build.
