### ISSUE TITLE
Traffic Filtering page freezes ntop

### ISSUE THREAD

**Issue by gemakochi** [ntop/ntopng#1045]
i'm using ntop in bridge mode. when i try to access Traffic Filtering page it freezes and i can't access anything. i have to reboot machine. i have found following error.

`[Redis.cpp:404] ERROR: WRONGTYPE Operation against a key holding the wrong kind of value [HKEYS ntopng.prefs.bridge:zc:eth1,zc:eth2.name]`

**Comment by emanuele-f** [comment]
What are the command line options you pass to ntopng?

**Comment by gemakochi** [comment]
i'm running as a service with simple config.

```
#cat /etc/ntopng/ntopng.conf 
-G=/var/run/ntopng.pid
--interface=bridge:zc:eth1,zc:eth2
-m="192.168.254.0/23,10.0.1.0/24"
```

**Comment by emanuele-f** [comment]
@gemakochi are you using ntopng version 2.4 as reported in #1077 ?

**Comment by gemakochi** [comment]
sorry i totaly forget this and yes it was 2.4, now it's 2.5. i can't test this in live network without zc drivers. i'll test this after #1077.

**Comment by emanuele-f** [comment]
So, please provide some feedback with 2.5 ntopng version after you renew the licence. Thank you

**Comment by gemakochi** [comment]
looks like its solved since there is no "Traffic Filtering" page and new "Traffic Policy" page is functional.

side note, that info box doesn't fit there.

![2017-03-28 10 17 28 ekran goruntusu](https://cloud.githubusercontent.com/assets/581848/24393199/d6801372-139f-11e7-9630-18eb326833bd.png)

**Comment by simonemainardi** [comment]
thanks for reporting
