### ISSUE TITLE
Traffic previously marked correct by stable release gets marked as unknown

### ISSUE THREAD

**Issue by bsteinert** [ntop/ntopng#1046]
== setup ==
Juniper MX240 (inline-jflow) --IPFIX--> nprobe --zmq--> ntopng

== startup commands ==
nprobe --zmq tcp://*:2522 -i none -n none --collector-port 2522 --daemon
nprobe --zmq tcp://*:2526 -i none -n none --collector-port 2526 --daemon
ntopng -i tcp://localhost:2522 -i tcp://localhost:2526 -i view:tcp://localhost:2522,tcp://localhost:2526 --dns-mode=2 --local-network=xx.xx.xx.xx/xx --max-num-hosts 500000 --max-num-flows 1000000 --daemon

== screenshots stable/dev ==
![ntop-stable_flows_not_deleted](https://cloud.githubusercontent.com/assets/8318840/23999346/6ceb7d8e-0a58-11e7-8e7f-537073702227.png)
![ntop-dev_unknown_traffic](https://cloud.githubusercontent.com/assets/8318840/23999348/6d11e58c-0a58-11e7-9979-9734aa1bc409.png)

**Comment by emanuele-f** [comment]
@kYroL01 can you check this out? It seems like most HTTP traffic on ZMQ is now reported as "unknown"

**Comment by kYroL01** [comment]
Only the HTTP on ZMQ is detected as unknown ?

**Comment by emanuele-f** [comment]
Yes, on the local interface I do not experience the issue

**Comment by bsteinert** [comment]
i think it is not only http, because when you look at the graph of the "stable" version you see ssl and other protocols also.

**Comment by kYroL01** [comment]
@emanuele-f From the graphic of @bsteinert it seems that all the traffic now is marked as _unknown_.
Are u sure is an nDPI issue ? It seems that all the traffic arriving from the probe does not recognize properly.

**Comment by simonemainardi** [comment]
@bsteinert we have tried to reproduce your issue with no luck. Can you please re try with both ntopng and nprobe at their latest dev verions?

Keep in mind that, in your configuration, simple port-based protocol detection is done as you are collecting IPFIX and thus real traffic and real packets are not available to the nDPI engine. So even HTTP would fail to be detected if it is not on port 80.

**Comment by bsteinert** [comment]
@simonemainardi i have updated to the latest version from apt. i also have tried to remove and purge all data and starting from scratch with no luck. i always get the same problem with the dev version.

i agree that capturing the traffic directly would be the best way, but unfortunately i have deployed the routers on different sites and i have only dedicated 1g links for the measurement. so i gave ipfix a try and with the stable version i see the traffic gets matched perfect, with the same config on the dev version most of the packets get recognized as unknown traffic. so i think something must be different between the two versions that caused this problem.

**Comment by lucaderi** [comment]
@bsteinert @simonemainardi @kYroL01 Hi all any news about this case? I would like to solve it ASAP.

**Comment by bsteinert** [comment]
@lucaderi no, i have tested with a different machine as ntopng host and switch to NetFlow V9 for testing. No luck at all. Now I'm back at IPFIX with the same problem. by looking at the longtime stats, it looks like only about 5 - 10% of the traffic gets matched.

<img width="347" alt="ntop" src="https://cloud.githubusercontent.com/assets/8318840/24073772/2028681c-0bfd-11e7-9b62-2481f792980f.png">

If it is helpful i can provide access to the gui, make tcpdumps or organize an remote session to have a look direct to the host.

**Comment by simonemainardi** [comment]
@bsteinert the issue cannot be with Netflow v9 or IPFIX as port-based protocol detection is done in both cases.

We can assist you remotely but first please let us see if we can reproduce the problem in our lab (so far we haven't been able to experience your issue). Can you please report the exact nprobe and ntopng version used, along with the OS used and distro?

**Comment by bsteinert** [comment]
== nprobe ==
Welcome to nProbe v.7.5.170317 (r5691) for x86_64-unknown-linux-gnu
with native PF_RING acceleration.
Copyright 2002-17 ntop.org

Build OS:      Debian GNU/Linux 8.2 (jessie)
SystemID:      051AF1D811B1B8A9
GIT rev:       dev:60b4028242bda03961cdadcdf64f9a42037c5eed:20170317


 == ntopng ==
v.2.5.170317 [Enterprise/Professional Edition]
GIT rev:   dev:db8086552c20497b58a32ffcf0cbeb4d2adf5b0b:20170317
Pro rev:   r994
System Id: 051AF1D811B1B8A9
Built on:  Debian GNU/Linux 8.2 (jessie)


== distro ==
Debian 8.7

Linux ntop 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux

**Comment by simonemainardi** [comment]
@bsteinert can we arrange a remote session? If affirmative, please send login details to mainardi at ntop dot org

thank you

**Comment by simonemainardi** [comment]
@bsteinert no need to do a remote session. I have already fixed the bug. A new build is in progress. Wait an hour and then you can try again.

**Comment by bsteinert** [comment]
@simonemainardi thank you very much, i will try and give instant feedback!

**Comment by bsteinert** [comment]
@simonemainardi looks better now..

![ntop_fixed](https://cloud.githubusercontent.com/assets/8318840/24213187/e7aa950e-0f31-11e7-8fd0-1b600549d3a9.png)
