### ISSUE TITLE
Seperating data in nTopng reports depending on the device sending data

### ISSUE THREAD

**Issue by franckfischer** [ntop/ntopng#1048]
Hello Simone,
To follow up on Jonathan's query (issue #890), we currently have router A sending flows to an nprobe instance running in proxy mode.
Flows are then forwarded by nprobe to an ntopng instance.

We'd now like to add a second device (router B) to that setup and be able to separate reports from router A and router B in ntopng.

I got from issue #890 that we should create different dynamic interfaces for each router.

However : 
1) should we create a different nProbe instance for each router, each exporting to the appropriate ntopng instance ? Or is it possible to collect all flows in one nProbe instance, and have it export data to the appropriate dynamic interface in ntopng ?
2) We were not able to find where to create Dynamic Interfaces in ntopng GUI. Could you please specify this ?

I'm sorry, we were not able to find that information from the user's guide.

Thanks for your help

**Comment by simonemainardi** [comment]
> should we create a different nProbe instance for each router, each exporting to the appropriate ntopng instance ? Or is it possible to collect all flows in one nProbe instance, and have it export data to the appropriate dynamic interface in ntopng ?

no, you can use a single nProbe instance and let all your routers export to it. Just add the field EXPORTER_IPV4_ADDRESS to the nProbe template.

> We were not able to find where to create Dynamic Interfaces in ntopng GUI. Could you please specify this ?

latest dev build, professional version, expert preferences view.

**Comment by franckfischer** [comment]
Hello Simone,

I’m following up on this topic.

You mentioned below that Dynamic Interface creation was to be made under the “expert preferences view”.
However, I was unable to find the “expert preferences view” (and therefore the Dynamic Interfaces creation) :
[cid:image002.jpg@01D2B1F1.C148BCD0]


I’m running the professional version in v.2.4.170215 which seams to be the latest version.

Could you please be more specific about where to create Dynamic Interfaces ?


Thanks for your help.

Best regards,

Franck FISCHER
Ingénieur Support Réseaux
Responsable Technique de Comptes
Services Opérés

T : +33 9 70 82 00 42
Exaprobe
Agence de Lyon : 13 B avenue Albert Einstein  - CS90217 - 69623 Villeurbanne Cedex
email : ffischer@exaprobe.com<mailto:ffischer@exaprobe.com>  ― web : www.exaprobe.com<http://www.exaprobe.com/> /  www.econocom.com<http://www.econocom.com/>

[LOGO_EXAPROBE_BLUE_RVB_HD]
[cid:image005.png@01D119A2.5102A820]




De : simonemainardi [mailto:notifications@github.com]
Envoyé : vendredi 17 mars 2017 16:27
À : ntop/ntopng <ntopng@noreply.github.com>
Cc : Franck Fischer <ffischer@exaprobe.com>; Author <author@noreply.github.com>
Objet : Re: [ntop/ntopng] Seperating data in nTopng reports depending on the device sending data (#1048)


should we create a different nProbe instance for each router, each exporting to the appropriate ntopng instance ? Or is it possible to collect all flows in one nProbe instance, and have it export data to the appropriate dynamic interface in ntopng ?

no, you can use a single nProbe instance and let all your routers export to it. Just add the field EXPORTER_IPV4_ADDRESS to the nProbe template.

We were not able to find where to create Dynamic Interfaces in ntopng GUI. Could you please specify this ?

latest dev build, professional version, expert preferences view.

**Comment by simonemainardi** [comment]
@franckfischer you need to move to version 2.5
