### ISSUE TITLE
Alerts Dashboard Invalid Page Behaviour

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1050]
![screen shot 2017-03-18 at 10 14 36](https://cloud.githubusercontent.com/assets/4493366/24070756/b5fb9380-0bc3-11e7-8e78-8bccb3214962.png)
There are a couple of issues to fix
1 The above triangle is not clickable
2. Expanding the box and performing a query will return a response with the search box collapsed even though it was expanded to perform the query

**Comment by emanuele-f** [comment]
Fixed
