### ISSUE TITLE
Invalid Character Validation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1051]
Some characters are mangled.
![screen shot 2017-03-18 at 10 17 21](https://cloud.githubusercontent.com/assets/4493366/24070784/183b8afa-0bc4-11e7-909d-0d106fe46de0.png)
![screen shot 2017-03-18 at 10 17 12](https://cloud.githubusercontent.com/assets/4493366/24070785/1865790a-0bc4-11e7-92ea-9a4e99b82012.png)

For instance setting a custom name with ' it is replaced by _. This should be fixed as it cannot be circumvented in any way

**Comment by emanuele-f** [comment]
Fixed in 6fd015baa9d102e640344191ab2bb6dc395a29b1
