### ISSUE TITLE
Periodically Reset Statistics

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1054]
Add a new field on the preferences pane (admin only) that will reset all hosts/flows/stats at midnight. In essence if this preference is set at midnight all stats are reset as if they start from zero. This in order to provide  clean daily (and not accumulated) view.

**Comment by emanuele-f** [comment]
Should the hosts and flows be removed from the hash tables or should theirs incStats statistics just be cleared?

**Comment by simonemainardi** [comment]
consider exposing a web endpoint and/or a Lua method and/or a button in the web ui to reset the counters at an arbitrary time and not just at midnight (#1859)

**Comment by simonemainardi** [comment]
- necessary to "snapshot" counters at pre-defined times (e.g, noon, midnight, hourly) or manually (click on the button reset of the gui).
- only deltas between snapshots should be returned in lua, possibly according to an user preference (for example, to return the last hour traffic, the delta between the current traffic value and a 'last hour snapshot' should be returned).
- must quantify the impact of these snapshots on the memory
- a similar mechanism has already been implemented for alert threshold cross. See if this can be re-used or generalized.

**Comment by emanuele-f** [comment]
This is now implemented. See `Midnight Stats Reset` in Cache Settings

**Comment by ChathuraML** [comment]
btw, can i have a quota for a month ?

**Comment by emanuele-f** [comment]
Currently no, quotas are only daily
