### ISSUE TITLE
AS Traffic Stats

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1055]
Implement AS traffic stats (similar to network interfaces) that could depict bytes in/out as well L7 protocols stats. These stats can be put on graphs need to be available from the AS report page and they can be enabled from the preferences pane.

**Comment by emanuele-f** [comment]
Implemented in b8c4145fcdac9990d5d72dae1a8c9e77ffa5e49a.
A separate preference field has been added.
