### ISSUE TITLE
Log files must be rotated and compressed

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1056]
The ntong.log file must be periodically rotated (i.e. it must contain up to X lines, for instance 10k) and 
a new file has to be created to avoid creating monster files. It would be nice to have them saved in compressed format (opening with gzopen instead of open)

/var/log/ntopng# ls -al
total 109676992
drwxr-xr-x  2 root root        4096 Mar 18 12:54 .
drwxr-xr-x 16 root root        4096 Mar 18 06:25 ..
-rwxrwxrwx  1 root root 51585801198 Mar 18 12:56 ntopng.log
-rwxrwxrwx  1 root root 18019954688 Mar 18 06:40 ntopng.log.1
-rwxrwxrwx  1 root root 12206782864 Mar 17 06:30 ntopng.log.2
-rwxrwxrwx  1 root root 13193829490 Mar 16 06:29 ntopng.log.3
-rwxrwxrwx  1 root root 17302205111 Mar 15 06:33 ntopng.log.4

**Comment by simonemainardi** [comment]
implemented in https://github.com/ntop/ntopng/commit/3908b56e0723189e7e325b503447bb93867715a5

simone@devel:~/ntopng$ ls -lha /var/tmp/ntopng/ntopng.log*
-rw-rw-rw- 1 root root 5.9K Aug  8 10:41 /var/tmp/ntopng/ntopng.log
-rw-rw-rw- 1 root root 2.0K Aug  8 10:41 /var/tmp/ntopng/ntopng.log.1
-rw-rw-rw- 1 root root 1.8K Aug  8 10:41 /var/tmp/ntopng/ntopng.log.2
-rw-rw-rw- 1 root root 3.5K Aug  8 10:41 /var/tmp/ntopng/ntopng.log.3
-rw-rw-rw- 1 root root 1.9K Aug  8 10:41 /var/tmp/ntopng/ntopng.log.4
-rw-rw-rw- 1 root root 151K Aug  8 10:41 /var/tmp/ntopng/ntopng.log.5
