### ISSUE TITLE
Alerts Preferences Rework

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1058]
Please fix the behaviour below in the preferences pane that is currently hardly readable
1. If alerts are disabled all other buttons should be hidden (eg. dump flow alerts)
2. max number of alerts should go on a separate sub pane 
3. security alerts such as probing or blacklist  alerts should go on a separate sub pane 
4. syslog, slack and nagios prefs should go on a single "External Alert Report" subpage

**Comment by emanuele-f** [comment]
Implemented in 17e63065fd386a1d56f217dbe6888237803a4da9
