### ISSUE TITLE
On-Disk Timeseries Rework

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1059]
This preference pane should be refreshed as it's too long and misleading
1. I would remove the timeseries preferences (just hide them all for the time being) as changing them makes issues with existing RRDs and creates side-effects
2. Some preferences hard to understand (what is the difference between flow devices and flow interfaces time series?) and should be aggregated
3. Some preferences such as "Layer-7 Application Timeseries" must be clear that apply to various aspects such as Interfaces, ASs, networks, hosts...

**Comment by simonemainardi** [comment]
also see #1061

**Comment by emanuele-f** [comment]
Fixed with fe2a5fca4321a0e6f72a1b2efa8c372653c62213
