### ISSUE TITLE
Error compile ndpi-netfilter

### ISSUE THREAD

**Issue by jerric12** [ntop/ntopng#106]
Hi,
I've installed ntopng/ndpi on a Debian Jessie and it works fine.
I need to associate with Netfilter. I tried to compile ndpi-netfilter with the instructions of betolj.
Is this project always maintened ?
If yes, i have these errors. Do you have an idea ? Can you help me please ?
For information, i compiled a new kernel. I added "Connection tracking netlink interface" and "Connection tracking events" in the kernel, not like modules.
Thanks a lot and sorry for my ignorance ;-)
----------------------------------------------------------------------------------------------------------------------
root@firewall:/usr/src/ndpi-netfilter# NDPI_PATH=/usr/src/ndpi-netfilter/nDPI make
make -C ipt
make[1]: Entering directory '/usr/src/ndpi-netfilter/ipt'
if test -d ndpi_cpy; then \
        cp /usr/src/ndpi-netfilter/nDPI/src/* ndpi_cpy -R; \
else \
        mkdir ndpi_cpy; \
        cp /usr/src/ndpi-netfilter/nDPI/src/* ndpi_cpy -R; \
fi
make libxt_ndpi.so
make[2]: Entering directory '/usr/src/ndpi-netfilter/ipt'
cc -fPIC -Indpi_cpy/include -Indpi_cpy/lib -I../src -DOPENDPI_NETFILTER_MODULE -O2 -Wall -D_INIT=libxt_ndpi_init -c -o libxt_ndpi.o libxt_ndpi.c;
libxt_ndpi.c:33:34: error: 'NDPI_PROTOCOL_LONG_STRING' undeclared here (not in a function)
 static char *prot_long_str[] = { NDPI_PROTOCOL_LONG_STRING };
                                  ^
libxt_ndpi.c:34:35: error: 'NDPI_PROTOCOL_SHORT_STRING' undeclared here (not in a function)
 static char *prot_short_str[] = { NDPI_PROTOCOL_SHORT_STRING };
                                   ^
libxt_ndpi.c:34:1: error: initializer element is not constant
 static char *prot_short_str[] = { NDPI_PROTOCOL_SHORT_STRING };
 ^
libxt_ndpi.c:34:1: error: (near initialization for 'prot_short_str[0]')
libxt_ndpi.c: In function 'ndpi_mt_init':
libxt_ndpi.c:116:25: warning: unused variable 'info' [-Wunused-variable]
  struct xt_ndpi_mtinfo *info = (void *)match->data;
                         ^
Makefile:19: recipe for target 'libxt_ndpi.o' failed
make[2]: *** [libxt_ndpi.o] Error 1
make[2]: Leaving directory '/usr/src/ndpi-netfilter/ipt'
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/ndpi-netfilter/ipt'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lucaderi** [comment]
Please open nDPI bugs under nDPI and not on ntopng. We do not suppor this code as it is not written by ntop. Please contact its author and send us patches for making it work.
