### ISSUE TITLE
Data Retention Preference

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1061]
Move all preferences related to data retention such as the prefs under "on-disk databases" on a separate prefernce pane. MySQL (For instance Check open_files_limit) prefs should go on a separate pane (perhaps a misc pane is enough). As it is today is hard to understand

**Comment by simonemainardi** [comment]
Make a tab "Data Retention" and move all the related data retention settings there. Specifically RRD retention settings that are now under On-Disk Timeseries (or, even better, hidden as suggested in #1059). Also the Top talkers storage that is now under On-Disk Databases. MySQL will have a custom pane that is shown only when mysql is enabled.

**Comment by emanuele-f** [comment]
Fixed with fe2a5fca4321a0e6f72a1b2efa8c372653c62213
