### ISSUE TITLE
Timeout Settings

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1062]
In the preference pane some user-editable values can lead to invalid configurations. For instance hosts/flow timeouts cannot be set to anything above a few mins (30 at most), local hosts timeout cannot be less than remote hosts timeout. "Local Hosts Cache Duration" should go onto the data retention tab #1061

**Comment by emanuele-f** [comment]
Implemented in 17e63065fd386a1d56f217dbe6888237803a4da9
