### ISSUE TITLE
Invalid AS link

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1064]
This fix https://github.com/ntop/ntopng/commit/04a18b2d5d5d3b872fa528ba85d55418fb06f224 is invalid as the bug is still present 
![screen shot 2017-03-18 at 11 05 27](https://cloud.githubusercontent.com/assets/4493366/24071106/f13661f8-0bca-11e7-8a73-6c30a7c7bb0a.png)
The info button should not be at  the bottom of the page but next to the AS number on the title

**Comment by simonemainardi** [comment]
Datatable title doesn't allow html. The link has been added using javascript.
