### ISSUE TITLE
SNMP Implementation Support is Partial

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1067]
SNMP Implementation is not feature complete. In particular 
- Physical Interfaces
It is not possible to compare on graphs interface stats with SNMP values for the same interface. 

- NetFlow Interfaces
-- It is not possible to compare on graphs interface stats with SNMP values for the same interface. 
-- The ratio should be displayed on in the graph page and computed on RRDs-only as the ratio between the total traffic seen on the interface and SNMP in+out Octets for the same interface. When #1066 will be implemented the traffic will be split in in and out (but for the time being in+out is enough). This info will be reported at the bottom of the chart in the Graph Info cells

![screen shot 2017-03-18 at 11 22 57](https://cloud.githubusercontent.com/assets/4493366/24071229/46b39e3c-0bcd-11e7-87b4-60bdd777cad6.png)

**Comment by simonemainardi** [comment]
features are implemented now
