### ISSUE TITLE
Implement InfluxDB Support

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1069]
RRD fall short in terms of performance and an alternative has to be found. Other technologies like https://www.influxdata.com are now mature and they should be evaluated for ntopng integration.

It is request to implement influxDB support as alternative to RRDs. The use of Influx will be activated via a preference pane, leaving RRDs as fallback.

**Comment by simonemainardi** [comment]
Implemented. Documentation available at: https://github.com/ntop/ntopng/blob/dev/doc/README.influxdb

issue superseded by https://github.com/ntop/ntopng/issues/1757 with a discussion of the structure of the influxdb model.
