### ISSUE TITLE
NTOPNG fails to install on Ubuiquiti EdgeRouter

### ISSUE THREAD

**Issue by coreyhines** [ntop/ntopng#107]
Message Body:
Unable to install NTOPNG on ubiquiti edgerouter running EdgeOS 1.70. Getting dependency issues while following http://www.ntop.org/ntopng/using-ntopng-pre-2-0-on-a-ubiquity-edgerouter/

Please provide installation assistance, ntopng license purchased on 8/2/2015 

Output:

root@ubnt:/home/admin# apt-get install libpcap-dev libtool rrdtool librrd-dev autoconf automake autogen redis-server wget libsqlite3-dev libgeoip-dev libcurl4-openssl-dev
Reading package lists… Done
Building dependency tree… Done
redis-server is already the newest version.
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
autoconf : Depends: m4 (>= 1.4.13) but it is not going to be installed
autogen : Depends: guile-1.8-libs but it is not going to be installed
Depends: libopts25-dev (= 1:5.10-1.1) but it is not going to be installed
automake : Depends: autotools-dev (>= 20020320.1) but it is not going to be installed
libcurl4-openssl-dev : Depends: libcurl3 (= 7.21.0-2.1+squeeze8) but 7.26.0-1+wheezy13 is to be installed
Depends: libc6-dev but it is not going to be installed or
libc-dev
Depends: libssl-dev but it is not going to be installed
Depends: zlib1g-dev but it is not going to be installed
Depends: libidn11-dev but it is not going to be installed
Depends: libkrb5-dev but it is not going to be installed or
hurd but it is not installable
Depends: libssh2-1-dev but it is not going to be installed
Depends: libldap2-dev but it is not going to be installed
libgeoip-dev : Depends: libgeoip1 (= 1.4.7~beta6+dfsg-1) but 1.4.8+dfsg-3 is to be installed
libpcap-dev : Depends: libpcap0.8-dev but it is not going to be installed
librrd-dev : Depends: libc6-dev but it is not going to be installed or
libc-dev
Depends: librrd4 (= 1.4.3-1) but it is not going to be installed
Depends: libpng12-dev but it is not going to be installed
Depends: zlib1g-dev but it is not going to be installed
Depends: libcairo2-dev but it is not going to be installed
Depends: libpango1.0-dev but it is not going to be installed
Depends: libfreetype6-dev but it is not going to be installed
Depends: libxml2-dev but it is not going to be installed
libsqlite3-dev : Depends: libsqlite3-0 (= 3.7.3-1) but 3.7.13-1+deb7u2 is to be installed
Depends: libc6-dev but it is not going to be installed
libtool : Depends: gcc but it is not going to be installed or
c-compiler
Depends: cpp but it is not going to be installed
Depends: libc6-dev but it is not going to be installed or
libc-dev
Depends: file but it is not going to be installed
Depends: autotools-dev but it is not going to be installed
Recommends: libltdl-dev but it is not going to be installed
ntopng : Depends: librrd4 but it is not going to be installed
rrdtool : Depends: libcairo2 (>= 1.2.4) but it is not going to be installed
Depends: libdbi0 but it is not going to be installed
Depends: libglib2.0-0 (>= 2.12.0) but it is not going to be installed
Depends: libpango1.0-0 (>= 1.14.0) but it is not going to be installed
Depends: librrd4 (>= 1.4~rc2) but it is not going to be installed
wget : Depends: libssl0.9.8 (>= 0.9.8m-1) but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
root@ubnt:/home/admin# apt-get -f install
Reading package lists… Done
Building dependency tree… Done
Correcting dependencies… Done
The following extra packages will be installed:
file libfribidi0 libmagic1 libnewt0.52 whiptail
The following packages will be REMOVED:
ntopng
The following NEW packages will be installed:
file libfribidi0 libmagic1 libnewt0.52 whiptail
0 upgraded, 5 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 446 kB of archives.
After this operation, 16.3 MB disk space will be freed.
Do you want to continue [Y/n]? y
Get:1 http://http.us.debian.org/debian/ squeeze/main libnewt0.52 mips 0.52.11-1 [70.5 kB]
Get:2 http://http.us.debian.org/debian/ squeeze/main whiptail mips 0.52.11-1 [40.0 kB]
Get:3 http://http.us.debian.org/debian/ squeeze/main libmagic1 mips 5.04-5+squeeze5 [241 kB]
Get:4 http://http.us.debian.org/debian/ squeeze/main file mips 5.04-5+squeeze5 [50.3 kB]
Get:5 http://http.us.debian.org/debian/ squeeze/main libfribidi0 mips 0.19.2-1 [44.0 kB]
Fetched 446 kB in 0s (551 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
(Reading database … 30754 files and directories currently installed.)
Removing ntopng …
Selecting previously unselected package libnewt0.52.
(Reading database … 30341 files and directories currently installed.)
Unpacking libnewt0.52 (from …/libnewt0.52_0.52.11-1_mips.deb) …
Selecting previously unselected package whiptail.
Unpacking whiptail (from …/whiptail_0.52.11-1_mips.deb) …
Selecting previously unselected package libmagic1.
Unpacking libmagic1 (from …/libmagic1_5.04-5+squeeze5_mips.deb) …
Selecting previously unselected package file.
Unpacking file (from …/file_5.04-5+squeeze5_mips.deb) …
Selecting previously unselected package libfribidi0.
Unpacking libfribidi0 (from …/libfribidi0_0.19.2-1_mips.deb) …
Setting up libnewt0.52 (0.52.11-1) …
Setting up whiptail (0.52.11-1) …
Setting up libmagic1 (5.04-5+squeeze5) …
Setting up file (5.04-5+squeeze5) …
Setting up libfribidi0 (0.19.2-1) …
root@ubnt:/home/admin# apt-get install libpcap-dev libtool rrdtool librrd-dev autoconf automake autogen redis-server wget libsqlite3-dev libgeoip-dev libcurl4-openssl-dev
Reading package lists… Done
Building dependency tree
Reading state information… Done
redis-server is already the newest version.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
autogen : Depends: libopts25-dev (= 1:5.10-1.1) but it is not going to be installed
libcurl4-openssl-dev : Depends: libcurl3 (= 7.21.0-2.1+squeeze8) but 7.26.0-1+wheezy13 is to be installed
Depends: libc6-dev but it is not going to be installed or
libc-dev
Depends: libssl-dev but it is not going to be installed
Depends: zlib1g-dev but it is not going to be installed
Depends: libidn11-dev but it is not going to be installed
Depends: libkrb5-dev but it is not going to be installed or
hurd but it is not installable
Depends: libssh2-1-dev but it is not going to be installed
Depends: libldap2-dev but it is not going to be installed
libgeoip-dev : Depends: libgeoip1 (= 1.4.7~beta6+dfsg-1) but 1.4.8+dfsg-3 is to be installed
libpcap-dev : Depends: libpcap0.8-dev but it is not going to be installed
librrd-dev : Depends: libc6-dev but it is not going to be installed or
libc-dev
Depends: librrd4 (= 1.4.3-1) but it is not going to be installed
Depends: libpng12-dev but it is not going to be installed
Depends: zlib1g-dev but it is not going to be installed
Depends: libcairo2-dev but it is not going to be installed
Depends: libpango1.0-dev but it is not going to be installed
Depends: libfreetype6-dev but it is not going to be installed
Depends: libxml2-dev but it is not going to be installed
libsqlite3-dev : Depends: libsqlite3-0 (= 3.7.3-1) but 3.7.13-1+deb7u2 is to be installed
Depends: libc6-dev but it is not going to be installed
libtool : Depends: libc6-dev but it is not going to be installed or
libc-dev
Recommends: libltdl-dev but it is not going to be installed
rrdtool : Depends: libpango1.0-0 (>= 1.14.0) but it is not going to be installed
Depends: librrd4 (>= 1.4~rc2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
root@ubnt:/home/admin# dpkg -i redis-server_2.4.15-1~bpo60+2_mips.deb
(Reading database … 30474 files and directories currently installed.)
Preparing to replace redis-server 2:2.4.15-1~bpo60+2 (using redis-server_2.4.15-1~bpo60+2_mips.deb) …
Stopping redis-server: redis-server.
Unpacking replacement redis-server …
Setting up redis-server (2:2.4.15-1~bpo60+2) …
Starting redis-server: redis-server.
root@ubnt:/home/admin# dpkg -i ntopng-data_2.0.150530_all.deb
(Reading database … 30474 files and directories currently installed.)
Preparing to replace ntopng-data 2.0.150530 (using ntopng-data_2.0.150530_all.deb) …
Unpacking replacement ntopng-data …
Setting up ntopng-data (2.0.150530) …
root@ubnt:/home/admin# dpkg -i ntopng
ntopng-data_2.0.150530_all.deb ntopng_2.0.150530_mips.deb
root@ubnt:/home/admin# dpkg -i ntopng_2.0.150530_mips.deb
Selecting previously unselected package ntopng.
(Reading database … 30474 files and directories currently installed.)
Unpacking ntopng (from ntopng_2.0.150530_mips.deb) …
dpkg: dependency problems prevent configuration of ntopng:
ntopng depends on librrd4; however:
Package librrd4 is not installed.

dpkg: error processing ntopng (–install):
dependency problems – leaving unconfigured
Errors were encountered while processing:
ntopng
root@ubnt:/home/admin# ntopng -i eth1
ntopng: error while loading shared libraries: librrd.so.4: cannot open shared object file: No such file or directory
root@ubnt:/home/admin# apt-get install libtool rrdtool
Reading package lists… Done
Building dependency tree
Reading state information… Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
libtool : Depends: gcc but it is not going to be installed or
c-compiler
Depends: cpp but it is not going to be installed
Depends: libc6-dev but it is not going to be installed or
libc-dev
Depends: autotools-dev but it is not going to be installed
Recommends: libltdl-dev but it is not going to be installed
ntopng : Depends: librrd4 but it is not going to be installed
rrdtool : Depends: libcairo2 (>= 1.2.4) but it is not going to be installed
Depends: libdbi0 but it is not going to be installed
Depends: libglib2.0-0 (>= 2.12.0) but it is not going to be installed
Depends: libpango1.0-0 (>= 1.14.0) but it is not going to be installed
Depends: librrd4 (>= 1.4~rc2) but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
root@ubnt:/home/admin#

root@ubnt:/home/admin# ntopng
ntopng: error while loading shared libraries: librrd.so.4: cannot open shared object file: No such file or directory
root@ubnt:/home/admin# ntopng -i eth1
ntopng: error while loading shared libraries: librrd.so.4: cannot open shared object file: No such file or directory

**Comment by lmangani** [comment]
Hi,

I believe you need to use the wheezy repositories in order for this to work correctly

**Comment by coreyhines** [comment]
Looks like this was resolved by using the Wheezy distribution for the repo settings. Thanks! Please put in a note to update: http://www.ntop.org/ntopng/using-ntopng-pre-2-0-on-a-ubiquity-edgerouter/

**Comment by lmangani** [comment]
Will update the guide - thanks!
