### ISSUE TITLE
Implement Grafana DataSource Plugin

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1070]
Add grafana.org support by developing a plugin for polling data from ntopng. Once #1069 is implemented we need to decide if a native plugin is required or if we decide to support grafana via InfluxDB integration only.

**Comment by simonemainardi** [comment]
https://github.com/ntop/ntopng/commit/c115271c5d11f6a75853193772378057d68ab9a3

**Comment by simonemainardi** [comment]
ntopng grafana datasource plugin is out:
- source code: https://github.com/ntop/ntopng-grafana-datasource
- announcement: http://www.ntop.org/ntopng/ntopng-grafana-integration-the-beauty-of-data-visualizazion/
- grafana community: https://grafana.com/plugins/ntop-ntopng-datasource
