### ISSUE TITLE
Implement AS Latency Stats

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1073]
Similar to #1072 but limited to AS, it is requested to compute (based on TCP flow information) the network latency (min/max/avg) calculation per destination AS. These stats must be periodically updated (they are not counters but gauges) so it must be planned how to recompute them periodically (e.g. every minute) and how to handle missing measurements points (when there is traffic for an AS but no new flows, that is used to compute latency with 3WHS).
An idea is to compute this info periodically when flows are scan, but it has to be validated by the implementer.

**Comment by lucaderi** [comment]
Please specify a due date

**Comment by simonemainardi** [comment]
implemented and available as exponentially weighted moving average.
