### ISSUE TITLE
SNMP Devices Should Not be Bound to an Interface

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1074]
SNMP devices are bound to an interface, so switching across network interfaces hides the devices. This is a problem when implementing #1067 with dynamic flow interfaces as the SNMP device must be replicated for each virtual interface, thing that is not optimal (RRDs will be created for all subinterfaces) and also because we do not know in advance what subinterfaces will be created.

In essence SNMP devices must be detached from a specific Interface selected.

**Comment by lucaderi** [comment]
Fix https://github.com/ntop/ntopng/commit/c775d79b4ee5447e33b93653d7a64b7f7c4cfea6 has broken the interface menu in the SNMP tab that is not empty

![screen shot 2017-03-20 at 23 00 56](https://cloud.githubusercontent.com/assets/4493366/24123755/1c913e16-0dc1-11e7-9800-1921ad58c145.png)

**Comment by lucaderi** [comment]
HTTP/1.1 500 Internal server error
Content-Type: text/html
Connection: close

<html><head><title>ntop</title></head><body><img src=/img/warning.png> Script &quot;/home/deri/ntopng/scripts/lua/pro/enterprise/get_snmp_device_info.lua&quot; returned an error:
<p><H3>...opng/scripts/lua/pro/enterprise/get_snmp_device_info.lua:46: bad argument #1 to 'ipairs' (table expected, got nil)</H3></body></html>

**Comment by emanuele-f** [comment]
Fixed in pro

**Comment by lucaderi** [comment]
![screen shot 2017-03-25 at 00 07 39](https://cloud.githubusercontent.com/assets/4493366/24316562/2a49ce7a-10ef-11e7-8bb4-ba25f365bbd3.png)
Apparently there are other code components where you do NOT read the correct SNMP community, you default to public and so SNMP is broken. Please fix this too

**Comment by emanuele-f** [comment]
Does the host have an SNMP community registered for it? Do you get an error message like this in the terminal? `"ERROR: community for device 192.168.1.2 is not set"`

**Comment by emanuele-f** [comment]
The "empty community" message has been added to the gui
