### ISSUE TITLE
Protocol Policy Cannot be Modified

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1075]
In the if_stats.lua page (bridge mode is active) it is possible to modify the protocol bandwidth but not the protocol name. This requires to delete the protocol and create a new one, that is inconsistent. It would be nice to allow users to modify the protocol menu too.

**Comment by emanuele-f** [comment]
Implemented in 0fcf93ffb90638e805f2982a6f4b6be33cc27e16
