### ISSUE TITLE
Hosts not assigned to the correct pool

### ISSUE THREAD

**Issue by PSmolders** [ntop/ntopng#1079]
Using ntopng 2.5.170322 on Ubuntu Server 16.04.02.

As of this morning, hosts are not assigned to a newly created host pool. I create the pool on a view interface, assign an IP range of 192.168.90.0/24, but on the Host Pool List page, it shows all hosts as part of the Host Pool Not Assigned pool. Tried to create a second new pool, using a different IP range, same thing. Manually adding a host to a pool from the Host Details page does not work either. The Host Details page says the host is a part of the Not Assigned pool.

**Comment by emanuele-f** [comment]
@simonemainardi should be allow host pools on view interfaces? This can create a conflict where the host is both assigned to a pool in the standard interface and to another in the view interface.

Reference: https://github.com/ntop/ntopng/blob/dev/src/NetworkInterface.cpp#L2104

**Comment by emanuele-f** [comment]
host pools cannot be used with view interfaces

Fixed in c546315c1582a6478f9953126b181442c7005579 and b9b2989b98e39bd8981d8693e0e50439f1d35f1d
