### ISSUE TITLE
--traffic-filtering="httpbl:xxxxxxxxxxxx" Not Working

### ISSUE THREAD

**Issue by Shmythe** [ntop/ntopng#1080]
I put the line: '--traffic-filtering="httpbl:xxxxxxxxxx"' in my ntopng.conf file, and it shows the following line in the Runtime Status: '[HTTPBL.cpp:29] Enable http:dl with API key ', but it is blank after 'key'.  

Then when I go to the projecthoneypot.org site it says that it has not received any requests using my key, so it is like ntopng is not storing my API key.

FYI: Obviously xxxxxxxxxxxx is not the API key I using.

**Comment by emanuele-f** [comment]
Fixed with 8b709d6e04054eeb049497f5c3bc4eba56397e38. Thank you for reporting.
