### ISSUE TITLE
Networks view

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#1081]
![ntopng_netw](https://cloud.githubusercontent.com/assets/14093378/24255531/0f64c4f2-0fe6-11e7-99d2-e19e22e11742.png)

Into the Networks view we have a lot of duplicated networks. As you can see in the image we have a lot of networks with the same names ("Remote Networks" and "x.y.0.0/18" (Network D)).
The table has 5924 rows. Is it correct?
Thanks...

**Comment by simonemainardi** [comment]
can you experience the same issue if you select a non-view interface?

**Comment by emanuele-f** [comment]
Same issue as #1076

**Comment by gianogli** [comment]
Yes, I've the same issue also with a non-view interface.
Could it be related with the issue `ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.`?

**Comment by emanuele-f** [comment]
No, that error states that you are trying to dump to disk too much information and some information will be lost. You should turn some "Timeseries" toggles off into the "Data Retention" settings or reduce your configured local networks size or migrate to a faster cpu/disk.
