### ISSUE TITLE
Create TCP Flags timeseries

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1084]
Create RRD for #1083 (both local hosts and network interface).

**Comment by simonemainardi** [comment]
- create one RRD per flag (e.g., one rrd per syn, one rrd per syn+ack, one rrd per fin+ack, one rrd per rst).

- add an option in the preferences to toggle the creation of the above rrds for local hosts and network interfaces

**Comment by emanuele-f** [comment]
As discussed, currently the tcp flags timeseries are only available for network interfaces. See 4dffa882ef78240039394c56dacd6a8d2bca7c5b.

**Comment by simonemainardi** [comment]
- scale is not consistent:

![image](https://cloud.githubusercontent.com/assets/3397663/24701554/2bc052a0-19fb-11e7-969d-27ea983460b0.png)

- it is not possible to determine the actual value even with the mouseover

- use horizontal rules to separate tcp from other timeseries and also to separate tcp flags timeseries from the ooo/retransm/lost. How everything is mixed together
![image](https://cloud.githubusercontent.com/assets/3397663/24701788/1aaf39ee-19fc-11e7-8b6d-6a4332bdcbbb.png)

**Comment by simonemainardi** [comment]
I fixed the scale:

![image](https://cloud.githubusercontent.com/assets/3397663/24709542/80bfa944-1a1a-11e7-9896-3ac2f934a74a.png)

@emanuele-f please re-arrange the entries as suggested above.

**Comment by emanuele-f** [comment]
Arranged with 919a49b1a3b3ef42087ce97dd40b0e8b04e0b96e
