### ISSUE TITLE
Implement ICMP and ARP Distribution

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1086]
Similar to /lua/if_stats.lua?page=packets it is request to add new pie charts (both for local hosts and interfaces) where are depicted (see #1085)
- ARP request vs response
- ICMP flags distribution (echo, dest unreachable ...)

Both distribution should be divided in sent vs received. Example
- account the number of ICMP ECHO request sent and rcvd

Both directions (sent and rcvd) must be depicted.

**Comment by lucaderi** [comment]
ICMP is implemented. ARP is missing

**Comment by emanuele-f** [comment]
ARP implemented in 0ee87cfd4e312da4b60ffc5fb54f8375d5c1b87d
Examples:

Good traffic:
![good](https://cloud.githubusercontent.com/assets/5488003/24548444/873ea486-1615-11e7-9069-8da80e80486f.png)

Attacker:
![bad](https://cloud.githubusercontent.com/assets/5488003/24548458/9e704740-1615-11e7-8731-acd68bcdf041.png)

Victim:
![under_attack](https://cloud.githubusercontent.com/assets/5488003/24548462/a09c0d60-1615-11e7-8d73-394f0fbdd9e2.png)

**Comment by lucaderi** [comment]
You do not seem to have implemented ARP stats in the interface view.

**Comment by lucaderi** [comment]
In host_details.lua, if there is a MAC associated (e.g. it does not happen for all flow-devices), add a pie chart (in page=packets tab page) with ARP breakdown (sent/received).

**Comment by emanuele-f** [comment]
Implemented in aa7bab5feee4f7de3fa9fc798b7a36ffd47cf172. Please reopen if necessary.
