### ISSUE TITLE
Improve flow alerts generation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1087]
Extend the current host/interface alert framework for emitting alerts when
- the number of active flows with low throughput is over a threshold
- the number of active flows with low retransmissions etc is over a threshold
- (host only) the number of egress flows from the same client port towards remote hosts is over a threshold
- the number of ICMP port/destination unreachable is over a threshold
- the number of ICMP echo is over a threshold

To keep complicity low, please consider adding host counters updated with flow lifecycle.

Use this paper http://luca.ntop.org/ADS.pdf as reference

**Comment by simonemainardi** [comment]
Added as task in https://github.com/ntop/ntopng/issues/1808
