### ISSUE TITLE
Generate Geolocation Alarms

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1088]
Ofter people use geolocation  for detecting Internet traffic anomalies. For instance some machines are designed to be accessed (as server) only from domestic users and other hosts (in particular IoT devices) for detecting if they have violated security rules.

it is requested to group countries together in continents as explained (http://dev.maxmind.com/geoip/legacy/codes/country_continent/), put the rest of undefined IPs into another grouping, and allow users to set (for local hosts) the list of contents a certain host can contract or be contacted.

**Comment by lucaderi** [comment]
When will the GUI be updated?

**Comment by simonemainardi** [comment]
Added as task in https://github.com/ntop/ntopng/issues/1808
