### ISSUE TITLE
Implement Continent-based Traffic Enforcement

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1089]
Ad explained in #1087, extend the host pools to enforce traffic only from/to specific continents

**Comment by emanuele-f** [comment]
Should we differentiate between the ingress/egress directions so that I can say allow incoming traffic from continent X but block outgoing traffic to the same continent?

**Comment by lucaderi** [comment]
No differentiation, just no communication with blacklisted continents

**Comment by emanuele-f** [comment]
Should we implement this on nedge or standard ntopng?

**Comment by simonemainardi** [comment]
Added as task in https://github.com/ntop/ntopng/issues/1808
