### ISSUE TITLE
One-way Traffic Detection

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1090]
Extend the Flows menu to include a new item that selects only one-way flows (i.e. flows that have no packets from server -> client).

Make sure you add two menu entries
- one-way traffic vs NON Multicast/Broadcast
- one-way traffic vs Multicast/Broadcast

When a flow is deleted from memory, increase a counter in the host (client vs server, two counters are needed) so that it is possible to generate alerts and time series for this attribute.

**Comment by emanuele-f** [comment]
Implemented in b7e0669c336e9046b42de518967f515dd76ec6ce
