### ISSUE TITLE
Invalid Host Quota Behaviour

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1095]
Host quota is a day amount of data that a host sends/receives. When the quota is past
- inline mode: the host traffic does not passes the bridge
- passive mode: an engaged alert is triggered

Every midnight the daily quota counter is reset and in case an engaged alert is present for the host, such alert is resolved.

The above behaviour is broken in the current release an it ought to be fixed. The easiest thing to do is to probably disable the current quota mechanism and implement it as host alert (after "Host Flows Threshold") so that a custom mechanism becomes standard again. it is important to note that if this change is made, the inline mode is working as above described.

**Comment by simonemainardi** [comment]
- host quota shall be implemented at the level of host pool (current quota code in the host shall be removed)
- interface policing page shall be extended to allow the setting of two additional fields per host pool per protocol, namely, bytes quota and time quota
- bytes quota and time quota shall be allowed also in non-inline mode to generate alerts accordingly to the descriptions above
- L7 statistics provided with https://github.com/ntop/ntopng/commit/9a95fc9511b396b4337810066fc81696f4d13f77 shall be used to enforce bytes and time quotas
- a periodic scripts that resets host pool l7 statistics shall be run every day at midnight

**Comment by lucaderi** [comment]
To keep things simple in passive mode bytes and time quotas are per host (not per protocol).

**Comment by emanuele-f** [comment]
Implemented with 42904dd0344a9a9a37e1c651cea0004357fe5a96
