### ISSUE TITLE
license and vm host changed - online license check through proxy server?

### ISSUE THREAD

**Issue by ips972** [ntop/ntopng#1098]
Hi , I had a system migrate to a new vm host. systemid changed and I have the same problem.
tried to run the –online-license-check command but it doesn't work. 
server must connect through proxy server to the internet. configured export command for the session.
verified with test WGET command. but running ntopng –online-license-check doesn't show any connection attempt to the configured proxy server.. 

is there a way to make this work through proxy?

Thanks

**Comment by simonemainardi** [comment]
presently, online license verification though a proxy is not supported.
