### ISSUE TITLE
Ntopng is not showing http and dns tabs

### ISSUE THREAD

**Issue by EusebioGM** [ntop/ntopng#1099]
Hi,

Ntopng is not showing "http" and "dns" tabs. 
"Pro licenses" for http and dns plugins and "Pro license" for Ntopng have been configured.
In my configuration there are two servers: 
- 1 collector/proxy: nProbe Server + ntop + MySQL.
- 1 probe mode: nprobe configured. It gets Netflow data and sends to the proxy server. This data is stored in MySql database.
I attach a document with screenshots in order you can see the configuration of collector/proxy and probe. And you will be able to see the error messages that appear when starting the nProbe process.
Could you please tell me how to solve this issue?
Thanks a lot.
Eusebio.

[ISSUE_Ntopng is not showing http and dns tabs.zip](https://github.com/ntop/ntopng/files/871691/ISSUE_Ntopng.is.not.showing.http.and.dns.tabs.zip)

**Comment by simonemainardi** [comment]
You need separate licenses for HTTP and DNS plugins. Once you've enabled those licenses, you will be able to use plugin-specific template fields (e.g., %HTTP_METHOD) and export their values to MySQL and/or ntopng.

Keep in mind that ntopng tabs HTTP and DNS are only available when raw packets are dissected by ntopng. If you collect netflow then you won't be able to get information such as number of gets/posts and so on as this kind of information is not contained in netflow.

**Comment by EusebioGM** [comment]
Hi Simone,

Thanks for your reply.
I have separated licenses for HTTP and DNS plugins and have been configured correctly in proxy/collector nProbe. So I do not think this is the problem.
I have tried to use the following HTTP and DNS elements in the template when sending netflow data to the proxy/collector server from the "probe mode" pc:
NOTE: So you can see in the error messages that licenses are found and "OK", but then they are unable to be loaded for some reason I do not know. And later it appears messages like this "Unable to locate template 'HTTP_URL'. Discarded."... So, why Do I get this error messages. And how could I solve them :

*** nProbe (probe mode):**
egarcia@netflow-c1:~$ sudo nprobe -i ens33 -n 192.168.1.7:2055 -V 9 -T="%HTTP_URL %HTTP_METHOD %HTTP_RET_CODE %HTTP_REFERER %HTTP_UA %HTTP_MIME %HTTP_HOST %HTTP_SITE %IN_BYTES %IN_PKTS %PROTOCOL %PROTOCOL_MAP %SRC_TOS %TCP_FLAGS %L4_SRC_PORT %L4_SRC_PORT_MAP %IPV4_SRC_ADDR %IPV4_SRC_MASK %L4_DST_PORT %L4_DST_PORT_MAP %L4_SRV_PORT %L4_SRV_PORT_MAP %IPV4_DST_ADDR %IPV4_DST_MASK %OUT_BYTES %OUT_PKTS %TOTAL_BYTES_EXP %TOTAL_PKTS_EXP %TOTAL_FLOWS_EXP %IP_PROTOCOL_VERSION %APPLICATION_ID %L7_PROTO %L7_PROTO_NAME %PLUGIN_NAME %DNS_QUERY %DNS_QUERY_ID %DNS_QUERY_TYPE %DNS_RET_CODE %DNS_NUM_ANSWERS"
27/Mar/2017 19:21:40 [nprobe.c:3407] Valid nProbe Pro license found
27/Mar/2017 19:21:40 [plugin.c:168] No plugins found in ./plugins
27/Mar/2017 19:21:40 [plugin.c:176] Loading 24 plugins [.so] from /usr/local/lib/nprobe/plugins
27/Mar/2017 19:21:40 [plugin.c:778] Unable to enable plugin DHCP Protocol [/etc/nprobe.license.dhcp]: License Ok
27/Mar/2017 19:21:40 [plugin.c:778] Unable to enable plugin Diameter Protocol [/etc/nprobe.license.diameter]: License Ok
27/Mar/2017 19:21:40 [plugin.c:778] Unable to enable plugin DNS/LLMNR Protocol [/etc/nprobe.license.dns]: License Ok
27/Mar/2017 19:21:40 [plugin.c:778] Unable to enable plugin Export Plugin [/etc/nprobe.license.export]: License Ok
27/Mar/2017 19:21:40 [plugin.c:778] Unable to enable plugin FTP Protocol [/etc/nprobe.license.ftp]: License Ok
27/Mar/2017 19:21:40 [plugin.c:778] Unable to enable plugin GTPv0 Signaling Protocol [/etc/nprobe.license.gtpv0]: License Ok
27/Mar/2017 19:21:40 [plugin.c:778] Unable to enable plugin GTPv1 Signaling Protocol [/etc/nprobe.license.gtpv1]: License Ok
27/Mar/2017 19:21:40 [plugin.c:778] Unable to enable plugin GTPv2 Signaling Protocol [/etc/nprobe.license.gtpv2]: License Ok
27/Mar/2017 19:21:40 [plugin.c:778] Unable to enable plugin HTTP Protocol [/etc/nprobe.license.http]: License Ok
27/Mar/2017 19:21:40 [plugin.c:778] Unable to enable plugin IMAP Protocol [/etc/nprobe.license.email]: License Ok
27/Mar/2017 19:21:40 [plugin.c:778] Unable to enable plugin Netflow-Lite Plugin [/etc/nprobe.license.nflite]: License Ok
27/Mar/2017 19:21:40 [plugin.c:778] Unable to enable plugin Oracle Protocol [/etc/nprobe.license.oracle]: License Ok
27/Mar/2017 19:21:40 [plugin.c:778] Unable to enable plugin POP3 Protocol [/etc/nprobe.license.email]: License Ok
27/Mar/2017 19:21:40 [plugin.c:778] Unable to enable plugin System process information [/etc/nprobe.license.process]: License Ok
27/Mar/2017 19:21:40 [plugin.c:778] Unable to enable plugin Radius Protocol [/etc/nprobe.license.radius]: License Ok
27/Mar/2017 19:21:40 [plugin.c:778] Unable to enable plugin RTP Plugin [/etc/nprobe.license.voip]: License Ok
27/Mar/2017 19:21:40 [plugin.c:778] Unable to enable plugin S1AP Protocol [/etc/nprobe.license.S1AP]: License Ok
27/Mar/2017 19:21:40 [plugin.c:778] Unable to enable plugin SIP Plugin [/etc/nprobe.license.voip]: License Ok
27/Mar/2017 19:21:40 [plugin.c:778] Unable to enable plugin SMTP Protocol [/etc/nprobe.license.email]: License Ok
27/Mar/2017 19:21:40 [nprobe.c:4872] WARNING: The output interfaceId is set to 0: did you forget to use -Q perhaps ?
27/Mar/2017 19:21:40 [nprobe.c:4875] WARNING: The input interfaceId is set to 0: did you forget to use -u perhaps ?
27/Mar/2017 19:21:40 [nprobe.c:4975] Welcome to nProbe Pro v.7.4.170215 ($Revision: 5334 $) for x86_64-pc-linux-gnu with native PF_RING acceleration
27/Mar/2017 19:21:40 [nprobe.c:4985] Running on Ubuntu 16.04.1 LTS
27/Mar/2017 19:21:40 [nprobe.c:4996] [LICENSE] nProbe SystemId: 3BA078FF760661D8
27/Mar/2017 19:21:40 [nprobe.c:7308] Welcome to nProbe v.7.4.170215 for x86_64-pc-linux-gnu
27/Mar/2017 19:21:40 [nprobe.c:6415] Using NetFlow Packet Payload Len: 1472
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_URL'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_METHOD'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_RET_CODE'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_REFERER'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_UA'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_MIME'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_HOST'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_SITE'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY_ID'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY_TYPE'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'DNS_RET_CODE'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'DNS_NUM_ANSWERS'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_URL'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_METHOD'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_RET_CODE'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_REFERER'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_UA'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_MIME'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_HOST'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_SITE'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY_ID'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY_TYPE'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'DNS_RET_CODE'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'DNS_NUM_ANSWERS'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_URL'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_METHOD'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_RET_CODE'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_REFERER'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_UA'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_MIME'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_HOST'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_SITE'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY_ID'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY_TYPE'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'DNS_RET_CODE'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'DNS_NUM_ANSWERS'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_URL'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_METHOD'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_RET_CODE'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_REFERER'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_UA'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_MIME'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_HOST'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'HTTP_SITE'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY_ID'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY_TYPE'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'DNS_RET_CODE'. Discarded.
27/Mar/2017 19:21:40 [template.c:1565] WARNING: Unable to locate template 'DNS_NUM_ANSWERS'. Discarded.
27/Mar/2017 19:21:40 [plugin.c:1045] 0 plugin(s) enabled
27/Mar/2017 19:21:40 [nprobe.c:6816] Each flow is 166 bytes long
27/Mar/2017 19:21:40 [nprobe.c:6817] The # packets per flow has been set to 7
27/Mar/2017 19:21:40 [nprobe.c:6836] Non IPv4/v6 traffic is discarded according to the template
27/Mar/2017 19:21:40 [util.c:434] GeoIP: loaded AS config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNum.dat
27/Mar/2017 19:21:40 [util.c:445] GeoIP: loaded AS IPv6 config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNumv6.dat
27/Mar/2017 19:21:40 [nprobe.c:5495] Using packet capture length 1600
27/Mar/2017 19:21:40 [pro/pf_ring.c:377] Initializing PF_RING socket on device ens33..
27/Mar/2017 19:21:40 [nprobe.c:7633] Capturing packets from interface ens33 [snaplen: 1600 bytes]
27/Mar/2017 19:21:40 [util.c:3129] nProbe changed user to 'nobody'
27/Mar/2017 19:21:40 [nprobe.c:7856] nProbe started successfully

*** nProbe (collector/propxy mode):**

Here you can see the configuration file with the same "template (-T)" I have used in "probe mode" system.

cat nprobe-none.conf
-n=none
-i=none
-t=60
-d=60
-a=0
-e=1
-B=10
-w=128000
-z=0
-S=1:1
-E=0:0
-g=/var/run/nprobe-none.pid
-3=2055
-P=/storage/nprobe/proxy/
--zmq=tcp://192.168.1.7:5556
--vlanid-as-iface-idx=none
-T="%HTTP_URL %HTTP_METHOD %HTTP_RET_CODE %HTTP_REFERER %HTTP_UA %HTTP_MIME %HTTP_HOST %HTTP_SITE %IN_BYTES %IN_PKTS %PROTOCOL %PROTOCOL_MAP %SRC_TOS %TCP_FLAGS %L4_SRC_PORT %L4_SRC_PORT_MAP %IPV4_SRC_ADDR %IPV4_SRC_MASK %L4_DST_PORT %L4_DST_PORT_MAP %L4_SRV_PORT %L4_SRV_PORT_MAP %IPV4_DST_ADDR %IPV4_DST_MASK %OUT_BYTES %OUT_PKTS %TOTAL_BYTES_EXP %TOTAL_PKTS_EXP %TOTAL_FLOWS_EXP %IP_PROTOCOL_VERSION %APPLICATION_ID %L7_PROTO %L7_PROTO_NAME %PLUGIN_NAME %DNS_QUERY %DNS_QUERY_ID %DNS_QUERY_TYPE %DNS_RET_CODE %DNS_NUM_ANSWERS"
-V=9
--mysql=127.0.0.1:ntop_db::root:*****
--dump-format=b
--dump-frequency=60
--dump-stats=/var/log/nprobe/none-0_flows_stats.txt
--timestamp-format=0
#--dump-metadata=/storage/nprobe/proxy/metadata.txt
--account-l2

**OUTPUT LOGS:**
sudo nprobe nprobe-none.conf
27/Mar/2017 19:36:42 [nprobe.c:3407] Valid nProbe Pro license found
27/Mar/2017 19:36:42 [plugin.c:168] No plugins found in ./plugins
27/Mar/2017 19:36:42 [plugin.c:176] Loading 24 plugins [.so] from /usr/local/lib/nprobe/plugins
27/Mar/2017 19:36:42 [plugin.c:778] Unable to enable plugin DHCP Protocol [/etc/nprobe.license.dhcp]: License Ok
27/Mar/2017 19:36:42 [plugin.c:778] Unable to enable plugin Diameter Protocol [/etc/nprobe.license.diameter]: License Ok
27/Mar/2017 19:36:42 [plugin.c:778] Unable to enable plugin DNS/LLMNR Protocol [/etc/nprobe.license.dns]: License Ok
27/Mar/2017 19:36:42 [plugin.c:778] Unable to enable plugin Export Plugin [/etc/nprobe.license.export]: License Ok
27/Mar/2017 19:36:42 [plugin.c:778] Unable to enable plugin FTP Protocol [/etc/nprobe.license.ftp]: License Ok
27/Mar/2017 19:36:42 [plugin.c:778] Unable to enable plugin GTPv0 Signaling Protocol [/etc/nprobe.license.gtpv0]: License Ok
27/Mar/2017 19:36:42 [plugin.c:778] Unable to enable plugin GTPv1 Signaling Protocol [/etc/nprobe.license.gtpv1]: License Ok
27/Mar/2017 19:36:42 [plugin.c:778] Unable to enable plugin GTPv2 Signaling Protocol [/etc/nprobe.license.gtpv2]: License Ok
27/Mar/2017 19:36:42 [plugin.c:778] Unable to enable plugin HTTP Protocol [/etc/nprobe.license.http]: License Ok
27/Mar/2017 19:36:42 [plugin.c:778] Unable to enable plugin IMAP Protocol [/etc/nprobe.license.email]: License Ok
27/Mar/2017 19:36:42 [plugin.c:778] Unable to enable plugin Netflow-Lite Plugin [/etc/nprobe.license.nflite]: License Ok
27/Mar/2017 19:36:42 [plugin.c:778] Unable to enable plugin Oracle Protocol [/etc/nprobe.license.oracle]: License Ok
27/Mar/2017 19:36:42 [plugin.c:778] Unable to enable plugin POP3 Protocol [/etc/nprobe.license.email]: License Ok
27/Mar/2017 19:36:42 [plugin.c:778] Unable to enable plugin System process information [/etc/nprobe.license.process]: License Ok
27/Mar/2017 19:36:42 [plugin.c:778] Unable to enable plugin Radius Protocol [/etc/nprobe.license.radius]: License Ok
27/Mar/2017 19:36:42 [plugin.c:778] Unable to enable plugin RTP Plugin [/etc/nprobe.license.voip]: License Ok
27/Mar/2017 19:36:42 [plugin.c:778] Unable to enable plugin S1AP Protocol [/etc/nprobe.license.S1AP]: License Ok
27/Mar/2017 19:36:42 [plugin.c:778] Unable to enable plugin SIP Plugin [/etc/nprobe.license.voip]: License Ok
27/Mar/2017 19:36:42 [plugin.c:778] Unable to enable plugin SMTP Protocol [/etc/nprobe.license.email]: License Ok
27/Mar/2017 19:36:42 [nprobe.c:4168] WARNING: If you want to preserve the -M value, please specify -w before -M
27/Mar/2017 19:36:42 [nprobe.c:4872] WARNING: The output interfaceId is set to 0: did you forget to use -Q perhaps ?
27/Mar/2017 19:36:42 [nprobe.c:4875] WARNING: The input interfaceId is set to 0: did you forget to use -u perhaps ?
27/Mar/2017 19:36:42 [nprobe.c:4975] Welcome to nProbe Pro v.7.4.170215 ($Revision: 5334 $) for x86_64-pc-linux-gnu with native PF_RING acceleration
27/Mar/2017 19:36:42 [nprobe.c:4985] Running on Ubuntu 16.04.1 LTS
27/Mar/2017 19:36:42 [nprobe.c:4996] [LICENSE] nProbe SystemId: 3B71DA9D760661D8
27/Mar/2017 19:36:42 [nprobe.c:5080] Dumping flow files every 60 sec into directory /storage/nprobe/proxy
27/Mar/2017 19:36:42 [nprobe.c:7308] Welcome to nProbe v.7.4.170215 for x86_64-pc-linux-gnu
27/Mar/2017 19:36:42 [nprobe.c:6415] Using NetFlow Packet Payload Len: 1472
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_URL'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_METHOD'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_RET_CODE'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_REFERER'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_UA'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_MIME'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_HOST'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_SITE'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY_ID'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY_TYPE'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'DNS_RET_CODE'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'DNS_NUM_ANSWERS'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_URL'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_METHOD'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_RET_CODE'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_REFERER'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_UA'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_MIME'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_HOST'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_SITE'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY_ID'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY_TYPE'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'DNS_RET_CODE'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'DNS_NUM_ANSWERS'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_URL'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_METHOD'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_RET_CODE'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_REFERER'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_UA'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_MIME'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_HOST'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_SITE'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY_ID'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY_TYPE'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'DNS_RET_CODE'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'DNS_NUM_ANSWERS'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_URL'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_METHOD'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_RET_CODE'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_REFERER'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_UA'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_MIME'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_HOST'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'HTTP_SITE'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY_ID'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'DNS_QUERY_TYPE'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'DNS_RET_CODE'. Discarded.
27/Mar/2017 19:36:42 [template.c:1565] WARNING: Unable to locate template 'DNS_NUM_ANSWERS'. Discarded.
27/Mar/2017 19:36:42 [plugin.c:1045] 0 plugin(s) enabled
27/Mar/2017 19:36:42 [database.c:209] Creating database schema...
27/Mar/2017 19:36:42 [nprobe.c:6816] Each flow is 166 bytes long
27/Mar/2017 19:36:42 [nprobe.c:6817] The # packets per flow has been set to 7
27/Mar/2017 19:36:42 [nprobe.c:6836] Non IPv4/v6 traffic is discarded according to the template
27/Mar/2017 19:36:42 [util.c:434] GeoIP: loaded AS config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNum.dat
27/Mar/2017 19:36:42 [util.c:445] GeoIP: loaded AS IPv6 config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNumv6.dat
27/Mar/2017 19:36:42 [nprobe.c:5495] Using packet capture length 1600
27/Mar/2017 19:36:43 [nprobe.c:7631] Not capturing packet from interface (collector mode)
27/Mar/2017 19:36:43 [util.c:4036] Initializing ZMQ as server
27/Mar/2017 19:36:43 [util.c:4079] Succesfully created ZMQ endpoint tcp://192.168.1.7:5556
27/Mar/2017 19:36:43 [collect.c:147] Flow collector listening on port 2055 (IPv4/v6)
27/Mar/2017 19:36:43 [nprobe.c:7856] nProbe started successfully

So in both systems I get the same error messages and licenses are well configured:
-nProbe Pro license in proxy/collector server.
-nProbe Pro license in probe mode system.
-DNS license Plugin in proxy/collector Server.
-HTTP license Plugin in proxy/collector Server.
-ntop Pro license in the same server than proxy/collector server.

So, please could you help me on this issue?
Could you please tell me...
- Why I am getting these error messages?
- How could I avoid them ajnd collect netflow data?
- Could you correct the conf files for "collector/proxy server" and "probe mode system" for me in order to start collecting data for HTTP and DNS plugins?
Thank you very much!
Eusebio.

**Comment by simonemainardi** [comment]
@EusebioGM 

what is strange is that plugin licenses are recognized but the plugins are not activated. e.g., 

27/Mar/2017 19:36:42 [plugin.c:778] Unable to enable plugin POP3 Protocol [/etc/nprobe.license.email]: License Ok

Can you please send your order id privately to mainardi at ntop dot org ?
