### ISSUE TITLE
Application filtering in Flows should be done on active flows

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#1100]
When clicking a protocol in the Flows view, the list of hosts which is returned contains hosts who have seen the application protocol in their lifetime.
It requested to rework this behaviour to only shows hosts who actually have any active flows of that protocol.

**Comment by simonemainardi** [comment]
as this feature would put significant extra pressure on the CPU, we put this issue on hold and will only reconsider it on the basis of the community requests.
