### ISSUE TITLE
View Interfaces: optimizations and misunderstood information...

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#1105]
In the last days I modified my server configuration as suggested in the issue #1010: I moved all the RRD files to a RAID0 of 2 SSD and I reduced the number of my local networks. Unfortunately, after these changes, I've again the error message "ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.". So I started to study the behavior of ntopng with my configuration and, in my opinion, I discovered some very interesting things.

My ntopng environment is configured to manage 5 interfaces:

```
...
--core-affinity 24,25,26,27,28
--interface zc:2@0
--interface zc:2@1
--interface zc:2@2
--interface zc:2@3
--interface view:zc:2@0,zc:2@1,zc:2@2,zc:2@3
...
```

The zc:2@0, zc:2@1, zc:2@2, zc:2@3 interfaces are created by a zbalance_ipc process that split (IP hash) a 10Gbit/s (full duplex) link (zc:0@0) into 4 smaller flows (to improve performance). if I set the "view" interface, into the ntopng web gui, I find a very strange number of Hosts/Flows:

![ntopng_5_interfaces](https://cloud.githubusercontent.com/assets/14093378/24445443/32727b82-146a-11e7-8b9a-34a688fe82a0.png)

300000 hosts are too many for my networks!

So, to made some tests, I tried to modify my configuration in this way:

```
...
--core-affinity 24
--interface zc:0@0
...
```
where zc:0@0 is the original 10Gbit/s (full duplex) link. This configuration is not optimized because the core used by ntopng to manage the interface sometime reaches the 90-100% (ntopng is able to acquire all the zc:0@0 packets but it drops some flows) while in the old configuration the 4 cores were at about 40% each.
However now, as you can see here,

![ntopng_1_interfaces](https://cloud.githubusercontent.com/assets/14093378/24446171/d53809c0-146c-11e7-9bbc-51d0fd071ee2.png)

we have less than 80000 hosts that is a reasonable value for our networks.
Furthermore, by using this configuration, we haven't the error message "ERROR: Cannot complete local hosts RRD dump..." anymore!

WHAT'S HAPPENS (my opinions):

I think that the use of zbalance_ipc to split a 10Gbit/s link (as in the first case) can be very useful to improve the performance of ntopng but it introduces some "misunderstandings". The 4 interfaces zc:2@[0-3] created by zbalance_ipc, in fact, are not logically independent because I can see all of my networks and all of my local IP on each of them. When I set into the web gui the aggregated view interface (view:zc:2@0,zc:2@1,zc:2@2,zc:2@3), instead, it seems that ntopng considers the 4 interfaces as independents. This explain why we see a number of hosts 4 times bigger (300000 =~ 80000*4) than normal. Is it correct?
In this case we have also a performance issue (CPU cycles used for generate unused data). When we use zbalanc_ipc to split a link, in fact, is not important to know information/statistics about the new smaller interfaces but is enough to manage only the RRD files for the view interface and for the "host pools". What do you think? Is it correct to use zbalance_ipc to improve the performance of ntopng?

I think that could be useful to introduce:
1) A new zbalance_ipc feature that permit to split the traffic by using some (also complex) BPF filter rules and not only with a hash function like now.
OR
2) A new ntopng feature that permit to hide from the gui the single interfaces created with zbalance_ipc and that use the cores to calculate the statistics only for the RRD files related to the view aggregate interface (and for the "host pools").

Is it possible? I think that these features could be very useful.

Thanks...

**Comment by simonemainardi** [comment]
>  When I set into the web gui the aggregated view interface (view:zc:2@0,zc:2@1,zc:2@2,zc:2@3), instead, it seems that ntopng considers the 4 interfaces as independents. This explain why we see a number of hosts 4 times bigger (300000 =~ 80000*4) than normal. Is it correct?

This is normal. A view is by definition -- and thus by design -- a logical aggregate of multiple interfaces. It is not up to the view to decide what to show or what to not show. It is up to you to properly design a zc balance function that delivers traffic on the desired queue. Examples of distribution functions can be found at https://github.com/ntop/PF_RING/blob/dev/userland/examples_zc/zbalance_ipc.c#L391

You should write a distribution function to distribute the traffic on the basis of the local ip addresses.

So to answer your question:

> I think that could be useful to introduce:
A new zbalance_ipc feature that permit to split the traffic by using some (also complex) BPF filter rules and not only with a hash function like now.

Yes, this is the proper way to do that. 

If you have troubles in implementing the function, please contact us privately and we will try to help.
