### ISSUE TITLE
net-snmp not working

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1106]
Installing net-snmp on a Linux PC, polling from  /lua/host_details.lua?ifid=0&host=x.x.x.x&page=snmp shows only the system group and not the interface group

![screen shot 2017-03-29 at 20 30 29](https://cloud.githubusercontent.com/assets/4493366/24470259/99cffaa8-14be-11e7-9593-fdf18c0a1496.png)

**Comment by simonemainardi** [comment]
Fixed.
