### ISSUE TITLE
Add Search on Help Window and Review Consistency

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1108]
The help window is unusable due to the many options currently available. It is requested to:
- implement a search box where it is possible to find options. An idea is to search strings in help title items
- put together items that are consistent. For instance retention items are spread all around. In essence rethink what information has to be presented where so that users can find what they are looking for.

**Comment by emanuele-f** [comment]
Search implemented in the linked pull request. Preferences reworked in 4ce22211046f579eed9ea3f64f45701ce8107f06
