### ISSUE TITLE
Shrink Traffic Shaping Layout

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1109]
![screen shot 2017-04-01 at 08 58 27](https://cloud.githubusercontent.com/assets/4493366/24576280/6697185e-16b9-11e7-9825-001c4e53b5a4.png) 

The current layout does not render properly and buttons and on two lines instead of one. This because some fields are pretty large, and others (e.g the protocol) take far too much more space than necessary

**Comment by emanuele-f** [comment]
Size reduced with d3411a4a88d3bfc0e1ce6ae30f275f45b311db75 , please check out new version. What's the window size are you using?

**Comment by emanuele-f** [comment]
Closing, please reopen if necessary.
