### ISSUE TITLE
User Interface Localisation Incomplete

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1111]
The whole user interface must be localisable. So far only a portion of it is as such. It must be extended to all (or at least at most) remaining user interface components.

**Comment by simonemainardi** [comment]
@TakayukiOnodera 

commits 7ed1e4988811120cd17525f73c2afb63ccebee09 and 7ed1e4988811120cd17525f73c2afb63ccebee09 implements configurable user language

![image](https://user-images.githubusercontent.com/3397663/28362127-99f1ddb6-6c7b-11e7-9b76-c38b1546f430.png)

(the rounded left corner of the language dropdown seems to be a bug of bootstrap)

the language is saved and set in a lua global variable to properly select the right file with i18n

currently, only english is enabled.

To add new languages is suffices to:
- add entries in this table: https://github.com/ntop/ntopng/commit/5dfbf87bbaf156f47313974d7e5c13a53edc518a#diff-5f5bfefbd639cb0b6eef00b1355be718R22
- load the localized file with an additional https://github.com/ntop/ntopng/commit/5dfbf87bbaf156f47313974d7e5c13a53edc518a#diff-5f5bfefbd639cb0b6eef00b1355be718R6

**Comment by emanuele-f** [comment]
Localization has been integrated into the pro version. Now most of the gui is localized, please close the issue when satisfied.

**Comment by emanuele-f** [comment]
Localization is now complete.
