### ISSUE TITLE
Enhance SNMP Devices Preferences 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1113]
When adding a new SNMP device (snmpdevices_stats.lua) it is requested to add the ability for the user to specify if the device must be periodically SNMP-polled (and thus eventually generate traffic time series) or not. This helps to avoid un-necessary polling for devices that are not important.

Furthermore when adding a new device, figure out if the bridge MIB is supported (this is detected during the first SNMP walk) and in case this device does NOT support it, do not include this device in the list of devices used to localise hosts via SNMP. This significantly reduces the host location for devices that are not supposed to be used for this purpose.

**Comment by simonemainardi** [comment]
implemented in Pro

```
commit 346c8a7441a1a95f2930bd6c3373397404fd14d0
Author: Simone Mainardi
Date:   Tue Apr 4 12:14:17 2017 +0200

    Implements Bridge MIB availability checks and caching

    Implements #1113

commit 412dbebad2af47cb8479e8bc5ee82010ade3df23
Author: Simone Mainardi
Date:   Mon Apr 3 18:07:38 2017 +0200

    Implements SNMP polling toggle

    Partially implements #1113
```
