### ISSUE TITLE
How to size the machine based on the received network traffic

### ISSUE THREAD

**Issue by EusebioGM** [ntop/ntopng#1115]
Hi,
I have an network architecture based in two servers: "probe mode" server and "collector" server.
And probe mode server is feeding "collector server".
So, I would like to know how to size both machines (servers) based on the real received traffic on the interface.
- Maybe there is some way of estimating how to size the machine as memory (RAM)? And what about the free space needed on hard drive?
- Or maybe it is possible that it depends on the amount of traffic in the environment where we are receiving this traffic... So, in this case maybe you have estimations to get the correct traffic?? (in order to avoid unexpected behaviors in our machines or to lose traffic because we did not size the machine properly from the beginning)

Maybe do you have any comparison (some table) about this sort of information depending of memory or received network traffic ... like this?
**Example1:**
Network traffic reception in "mirror port" (span port):
* Up to 1GB  -> Your "probe mode" server will need 64 Gb of RAM; Collector server: 64 Gb of RAM.
* Up to 1,5GB  -> Your machine will need XX Gb of RAM. ; Collector server: YY Gb of RAM.

**Example2:**
Space needed for 1MONTH:
* For a "probe mode" server that is getting Up to 1GB listening traffic from span port is 400GB (for CSV).
* For a "Collector" server that is getting Up to 1GB listening traffic from a "probe mode" server is 600GB for CSV files and 500GB for MySQL storage .

Thanks a lot,
Eusebio.

**Comment by simonemainardi** [comment]
Space is basically impacted by the following:

- local hosts. ntopng keeps several RRDs with detailed statistics for each local host. You can control RRD size by tuning data retentions periods from the preferences. You may also toggle the L7 statistics for local hosts
- historical mysql flows: approximately 400k per mysql flow (total index + data)


Memory is impacted by the following:
- number of active flows and number of active hosts at any given instant of time. In any practical environment, 8~16 Gb ram is the maximum you would need

**Comment by EusebioGM** [comment]
ok, thanks a lot!
