### ISSUE TITLE
Alerts Descriptions

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#1117]
A description should be added (improved) for the configurable threshold-based alerts:

![image](https://cloud.githubusercontent.com/assets/3397663/24614565/db0874f2-188b-11e7-8901-d999cd2fe8d1.png)

Es:

- what does 'bytes' mean? >= Layer 2 ? or >= Layer 3? This should be explained
- what does dns mean?

**Comment by emanuele-f** [comment]
Implemented in 40828f2b662ed6527774ba69c356ce6ce92e5bb4.
