### ISSUE TITLE
Add Protocol List per Protocol Category

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#1118]
When configuring host pool policies and quotas it is possible to select protocol categories. However, it is not clear which protocols belong to which category.

It is requested to add information to allow the user to browse the full list of protocols that belong to each category.

**Comment by emanuele-f** [comment]
Implemented with 058d7e27ce6c177da0d03a661a5e177d25472db4. See attached screenshot: 
![screenshot at 2017-04-04 15-31-27](https://cloud.githubusercontent.com/assets/5488003/24659219/59a8d926-194c-11e7-91e1-f935dc1bb6e5.png)
