### ISSUE TITLE
Cannot login from non-localhost

### ISSUE THREAD

**Issue by davr** [ntop/ntopng#1125]
When I log in from non localhost I just redirect immediately to the login page again with no error or anything. Appears to be the same as #479

When I attempt to login I see these messages in the log:
04/Apr/2017 20:56:16 [HTTPserver.cpp:136] [HTTP] Set session sessions.5a1b409954358a2d7bd34f60f6f0fd1b
04/Apr/2017 20:56:16 [HTTPserver.cpp:234] [HTTP] redirect_to_login(5a1b409954358a2d7bd34f60f6f0fd1b)
04/Apr/2017 20:56:16 [HTTPserver.cpp:347] [HTTP] /lua/login.lua
04/Apr/2017 20:56:16 [HTTPserver.cpp:379] [HTTP] /lua/login.lua [/usr/share/ntopng/scripts/lua/login.lua]
04/Apr/2017 20:56:16 [AddressTree.cpp:139] Rule 0.0.0.0/0
04/Apr/2017 20:56:16 [AddressTree.cpp:139] Rule ::/0

But when I log in from localhost, everything works as it should. As a workaround I can make a ssh tunnel to make it appear I am logging in from localhost, but it's an extra hassle I'd like to avoid.

**Comment by davr** [comment]
Running version 2.2+dfsg1-1buil on Ubuntu 16.04.2 LTS, kernel 4.4.0-62-generic

**Comment by simonemainardi** [comment]
@davr please update at least to stable 2.4 or dev version 2.5. Version 2.2 is outdated.

**Comment by simonemainardi** [comment]
Solution given. Using an outdated release. Issue is fixed in versions >= 2.4

**Comment by emanuele-f** [comment]
Please check out https://github.com/ntop/ntopng/commit/07702712187347ef448a14647d051c223755b4cd
