### ISSUE TITLE
Limit ntopng to MySQL file limit

### ISSUE THREAD

**Issue by PSmolders** [ntop/ntopng#1126]
Would it be possible to limit ntopng to a MySQL open file limit? I am running MySQL on a Synology NAS box and I can not change the open file limit from 1024 on there. Right now, nProbe crashes around 01:00 every morning because the file limit is too small. So, can ntopng be limited to only use 1024 MySQL files/connections instead? Currently using the MyISAM DB engine.

**Comment by simonemainardi** [comment]
is nProbe or ntopng that crashes?

**Comment by PSmolders** [comment]
I can still access the web GUI of ntopng, yet no new data comes in, on any interface. All pages are empty as old data is purged after a certain time. So I guess it is nProbe that crashes. Htop shows nProbe as not running after. Ntopng log shows error connecting to MySQL, then succesfully connecting, then disconnected in that order, for every interface, once every day at 01:00 after the ntopng MySQL open files limit alert show up.

**Comment by simonemainardi** [comment]
I am not sure those two issues are related. Update nProbe to the latest dev version as a the cause of a crash was fixed yesterday.

Regarding MySQL there's some room to reduce the number of open files. If you can't increase the maximum on the OS,  you should ALERT TABLE and reduce the number of partitions manually.

**Comment by PSmolders** [comment]
nProbe is updated to the latest version as of today, I will check if the issue persists. For MySQL, I shall check it out.

**Comment by simonemainardi** [comment]
if you can't find the nProbe process running, then it has very likely crashed. Please follow the instructions at http://www.ntop.org/support/faq/how-to-report-a-bug-on-ntop-apps/ and use the github nprobe issue tracker to report.
