### ISSUE TITLE
After reboot, ntopng service starts with redis errors

### ISSUE THREAD

**Issue by jberthier** [ntop/ntopng#113]
Seen on CentOS 7
After reboot, ntopng service starts with errors :
Jun 23 15:00:23 myserver.mydomain.tld ntopng[3154]: [src/Redis.cpp:108] ERROR: LOADING Redis is loading the dataset in memory
Jun 23 15:00:23 myserver.mydomain.tld ntopng[3154]: [src/Redis.cpp:1297] ERROR: LOADING Redis is loading the dataset in memory
Jun 23 15:00:23 myserver.mydomain.tld ntopng[3154]: [src/Redis.cpp:125] ERROR: LOADING Redis is loading the dataset in memory
Jun 23 15:00:23 myserver.mydomain.tld ntopng[3154]: [src/Redis.cpp:108] ERROR: LOADING Redis is loading the dataset in memory

The web UI is up but no data is available. If I restart the ntop service, everything goes OK.

I tried to modify the systemd unit ntopng.service to set it to start after redis.service.
In file /etc/systemd/system/ntopng.service, add "redis.service" to the "After" line :
After=network.target syslog.target redis.service

At each reboot, ntopng correcty start after redis but the error is still there.
ntopng service should wait that the redis service finish to load its data :
https://github.com/redis/redis-rb/issues/350

**Comment by lucaderi** [comment]
I have added a check for waiting up to 10 sec until redis finishes to start up. Please give it a try. This said, a periodic redis-cli flushall can help.
