### ISSUE TITLE
Adding subnet to different pools

### ISSUE THREAD

**Issue by ValentinaViscarelli** [ntop/ntopng#1130]
You can add the same subnet to different pools. This should not be possible. 
What policy do you apply in this case?

**Comment by lucaderi** [comment]
In other words no overlapping networks can be defined in different pool.

**Comment by simonemainardi** [comment]
I partially disagree on the overlapping. I would allow overlapping networks to be defined across pools. In this way we could leverage the benefits of CIDR and longest match to implement more flexible policies.

For example, let's say you have an organization with a /24 and you know that all the executives have ip addresses in a more specific /25. By allowing overlapping networks you can policy the organization and the executives of the same organization with different rules.
