### ISSUE TITLE
Daily Traffic Quota doesn't seem to work

### ISSUE THREAD

**Issue by ValentinaViscarelli** [ntop/ntopng#1131]
I started ntopng in bridge mode "sudo ./ntopng -i bridge:enp6s0,enp8s0"
I have created a pool and I have inserted the subnet "192.168.10.0/24" and I have set a "Daily Traffic Quota" of 3 MiB for the http protocol.
Although I have passed the threshold (How you can see from screen shots), I can still surf the Internet using http protocol.
Am I doing something of wrong?   
![welcome to ntopng - google chrome_033](https://cloud.githubusercontent.com/assets/13115771/24726091/72eab854-1a51-11e7-8cf3-2f7b11380630.png)
![welcome to ntopng - google chrome_032](https://cloud.githubusercontent.com/assets/13115771/24726092/72ff8cf2-1a51-11e7-86e4-973a43350974.png)
![welcome to ntopng - google chrome_031](https://cloud.githubusercontent.com/assets/13115771/24726093/7300dcba-1a51-11e7-906d-3bfd7980d5c1.png)

**Comment by lucaderi** [comment]
@ValentinaViscarelli I think this issue has some kind of relationship with #1135

**Comment by simonemainardi** [comment]
fixed
