### ISSUE TITLE
Misleading flow status information

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1136]
![screen shot 2017-04-06 at 13 09 15](https://cloud.githubusercontent.com/assets/4493366/24751589/79ab9c20-1aca-11e7-9dd3-16b68367066f.png)

Nowhere in the GUI it is written when a flow is blocked because of a quota limit. Looking at the above image you can see that this flow has no shaper associated (and thus unlimited bandwidth) but it is blocked. The reason is that the quota was past. It is required to report this information into the flow information windows.

As of hosts, in case of hosts blocked by quota 0-bandwidth shapers etc., it is requested to put an icon next to the host (and in the host details window) to report this information.

**Comment by emanuele-f** [comment]
Please provide the following details:
- Into the flow details, the quota information should be provided just as a boolean "Quota exceeded / Not exceeded" or with two gauges (one for client, one for server pool)?
- Into the host details, the information is just a "Quota exceeded / Not exceeded"?

**Comment by emanuele-f** [comment]
Implemented in eb7fae8c4c865301c7284ff4e91bdf4b4553fc6d and 97afda88b8e0b9fb46eae431244696fc84119777
