### ISSUE TITLE
Invalid Host Pool Report

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1137]
![screen shot 2017-04-06 at 13 14 22](https://cloud.githubusercontent.com/assets/4493366/24751744/0039bc72-1acb-11e7-9f8d-4a2ff4ad0da4.png)
![screen shot 2017-04-06 at 13 14 07](https://cloud.githubusercontent.com/assets/4493366/24751747/004d35e0-1acb-11e7-9d4d-004b4dbaa01d.png)
![screen shot 2017-04-06 at 13 13 50](https://cloud.githubusercontent.com/assets/4493366/24751746/004a1edc-1acb-11e7-9d3d-f038b630332b.png)

Even though hosts and host pools are defined (at least the default pool exists), the GUI reports no host pools information

**Comment by emanuele-f** [comment]
@lucaderi can you check if this is fixed after commit 2e61d5babc2ed2af0682fdacd525c027bf4311f7 ? Thank you.

**Comment by emanuele-f** [comment]
Any update?

**Comment by lucaderi** [comment]
The report is working now, but the view button is dimmed even though you can click on it
![screen shot 2017-04-26 at 13 02 05](https://cloud.githubusercontent.com/assets/4493366/25431363/99754b26-2a80-11e7-9628-27434b8c4253.png)

**Comment by emanuele-f** [comment]
The view button is not actually dimmed, but it has a light color so it seems dimmed. For contrast, the dimmed version is shown in the screenshot below.

![screenshot at 2017-04-26 23-22-56](https://cloud.githubusercontent.com/assets/5488003/25457685/636150dc-2ad7-11e7-9dd6-0ff7bcb494b1.png)

Do you suggest to use a darker color for the view button?

**Comment by simonemainardi** [comment]
issue is solved. @emanuele-f please make  the button darker.
