### ISSUE TITLE
What determines the size of redis?

### ISSUE THREAD

**Issue by JuergenWeber** [ntop/ntopng#114]
redis consumes lots of memory. Ntop "sits" at the border between WAN and LAN and monitors about 2500 hosts, 1200 aggregations, 15000 flows
Here's a screenshot of "top", ordered by memory usage:
![image](https://cloud.githubusercontent.com/assets/13195740/9081221/deb10dfe-3b5a-11e5-90ae-f98ef6c9d3b0.png)

**Comment by lucaderi** [comment]
Can you please paste here the output "redis-cli info" ?

**Comment by JuergenWeber** [comment]
Here it is:

# Server
redis_version:3.0.3
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:789a1a0ec9b20e69
redis_mode:standalone
os:Linux 2.6.32-573.1.1.el6.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.4.7
process_id:6121
run_id:1160b271c7aa6e23d3b7a992f67bbb58c2c7176d
tcp_port:6379
uptime_in_seconds:622752
uptime_in_days:7
hz:10
lru_clock:12710997
config_file:/etc/redis.conf

# Clients
connected_clients:2
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:9248389360
used_memory_human:8.61G
used_memory_rss:7484489728
used_memory_peak:9248389360
used_memory_peak_human:8.61G
used_memory_lua:36864
mem_fragmentation_ratio:0.81
mem_allocator:jemalloc-3.6.0

# Persistence
loading:0
rdb_changes_since_last_save:16005
rdb_bgsave_in_progress:1
rdb_last_save_time:1438774158
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:40
rdb_current_bgsave_time_sec:94
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok

# Stats
total_connections_received:4
total_commands_processed:184736835
instantaneous_ops_per_sec:114
total_net_input_bytes:10036690290
total_net_output_bytes:2772076729
instantaneous_input_kbps:7.10
instantaneous_output_kbps:0.98
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:338289
evicted_keys:0
keyspace_hits:97058700
keyspace_misses:65144499
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:73697
migrate_cached_sockets:0

# Replication
role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:9342.71
used_cpu_user:2841.51
used_cpu_sys_children:15633.38
used_cpu_user_children:63180.24

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=3308,expires=3232,avg_ttl=5182021

**Comment by lucaderi** [comment]
So you only have 3308 active keys but used memory is 8.61G. I have seen it on redis 2.4 and I though it was a bug but it looks it is now.

Please ask on the redis mailing list and report back as this problem is concerning, and report back.

**Comment by lucaderi** [comment]
The only suggestion I have is to start playing with the maxmemory parameter to set an upper limit.

**Comment by lucaderi** [comment]
Seehttp://redis.io/topics/lru-cache

**Comment by lucaderi** [comment]
See https://github.com/ntop/ntopng/blob/dev/doc/README.redis

**Comment by JuergenWeber** [comment]
I applied the 2 parameters into /etc/redis.conf. But after restarting redis it was a matter of seconds until all memory was occupied again. I had a look into /var/lib/redis:
![image](https://cloud.githubusercontent.com/assets/13195740/9088308/a43676f2-3b8f-11e5-9995-52ee733a5fd2.png)
It seems that redis is loading the dump.rdb for the sake of persistence.
What will happen to NTOPNG if dump.rdb is being deleted???

**Comment by lucaderi** [comment]
Please do this
0. reconfigure redis.conf (done)
1. stop ntopng
2. redis-cli flushall
3. restart redis
4. start ntopng

Hope it works

**Comment by JuergenWeber** [comment]
Thanks Luca, this worked for me!
