### ISSUE TITLE
Errors after upgrade

### ISSUE THREAD

**Issue by dcsquare** [ntop/ntopng#1140]
I upgraded today to 2.5.170406 - Pro Small Business Edition (had to do a dist-upgrade).

Issues:
1. Traffic seen is 1% of the former (see image - it's a 10GB interface, with 3Gbps down, 1Gbps up at the moment of the screenshot).
2. The log is full of errors of the type:
06/Apr/2017 19:01:20 [Lua.cpp:6358] WARNING: Script failure
[/usr/share/ntopng/scripts/lua/network_load.lua][/usr/share/ntopng/scripts/lua/modules/http_lint.lua:918:
[LINT] _GET["ifname"] = "all" parameter error: Missing validation]
06/Apr/2017 19:01:17 [Lua.cpp:6358] WARNING: Script failure
[/usr/share/ntopng/scripts/lua/network_load.lua][/usr/share/ntopng/scripts/lua/modules/http_lint.lua:918:
[LINT] _GET["ifname"] = "all" parameter error: Missing validation]
3. After about 10 min the VM became unresponsive.

![2017-04-06 19_10_00-welcome to ntopng](https://cloud.githubusercontent.com/assets/718334/24764711/e7e1068e-1afd-11e7-9b4d-2bcec1cbeea8.png)

**Comment by simonemainardi** [comment]
please share ntopng and probe configurations used

**Comment by dcsquare** [comment]
Startup Line	ntopng --pid "/var/run/ntopng.pid" --interface "tcp://127.0.0.1:5556" --data-dir "/var/tmp/ntopng" --http-port "3000" --local-networks "x.y.z.w/19" --max-num-flows "200000" --max-num-hosts "250000" --sticky-hosts "none"

nprobe: 
--collector-port=6343
--zmq=tcp://127.0.0.1:5556
-g=/var/run/nprobe-eth0.pid
--dump-stats=/var/log/nprobe/eth0-0_flows_stats.txt
-T="%IPV4_SRC_ADDR %IPV4_DST_ADDR %INPUT_SNMP %OUTPUT_SNMP %IN_PKTS %IN_BYTES %FIRST_SWITCHED %LAST_SWITCHED %L4_SRC_PORT %L4_DST_PORT %TCP_FLAGS %PROTOCOL %EXPORTER_IPV4_ADDRESS"

PS: you already have access to the server. I never deleted your account.

**Comment by emanuele-f** [comment]
It seems like your browser is still using the old pre-update code, can you flush its cache?

**Comment by dcsquare** [comment]
I can use an entirely new browser. And I did. Same results:
![2017-04-07 11_23_04-welcome to ntopng - internet explorer](https://cloud.githubusercontent.com/assets/718334/24791915/a824e7cc-1b84-11e7-9b0b-515cc6888b1a.png)

**Comment by dcsquare** [comment]
You can close this one as I did an apt-get purge ntopng probe to start fresh.
I'm using this in production so I need it to work.
I'm opening a new bug thread.
