### ISSUE TITLE
Raspberry PI 2 Install Issue

### ISSUE THREAD

**Issue by sillenomis** [ntop/ntopng#1141]
Hi, I have followed install instructions at http://packages.ntop.org/RaspberryPI/ for my RPI2 running the latest lite (sic) version of jessie and this error occurs...

Preparing to unpack .../ntopng_2.5.170401-2576_armhf.deb ...
Unpacking ntopng (2.5.170401-2576) ...
dpkg: error processing archive /var/cache/apt/archives/ntopng_2.5.170401-2576_armhf.deb (--unpack):
 trying to overwrite '/usr/share/ntopng/httpdocs/font-awesome/fonts/fontawesome-webfont.eot', which is also in package ntopng-data 1.2.1+dfsg1-1.1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Processing triggers for man-db (2.7.0.2-5) ...
Processing triggers for libc-bin (2.19-18+deb8u7) ...
Processing triggers for systemd (215-17+deb8u6) ...
Errors were encountered while processing:
 /var/cache/apt/archives/ntopng_2.5.170401-2576_armhf.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

I had previously installed libpcap0.8 & libmysqlclient18 as recommended by other commentators. 

I saw in a previous post (https://github.com/ntop/ntopng/issues/774) that a similar issue was fixed last year.

Thanks for reading.

**Comment by sillenomis** [comment]
re-ran install this evening and install was a bit clunky with ntopng --configure errors (sorry did it on my phone, so didn't capture actual messages), but all working after a reboot. thanks for sorting. great product.

**Comment by emanuele-f** [comment]
Can you post here the configure errors you see? Maybe there is something in our package that we need to fix. Thank you.

**Comment by sillenomis** [comment]
hi, i reran the install on a fresh install of raspian (so i could capture the errors for you) and there were no errors, so unfortunately i don't have anything to show you.

**Comment by emanuele-f** [comment]
That's ok, thank you
