### ISSUE TITLE
Incorect traffic values

### ISSUE THREAD

**Issue by dcsquare** [ntop/ntopng#1145]
Fresh install of ntopng and nprobe (after the update to 2.5.170406 totally fubared my box).

The traffic values are incorrect. They should be 2Gbps down/ 500 Mbps up.
Ntopng show 900kbps down / 100 kbps up.

Sflow comes from a Huawei S6720, from a single interface.

Configs:
nprobe:
--collector-port=6343
--zmq=tcp://127.0.0.1:5556
-g=/var/run/nprobe-eth0.pid
--dump-stats=/var/log/nprobe/eth0-0_flows_stats.txt
-T="%IPV4_SRC_ADDR %IPV4_DST_ADDR %INPUT_SNMP %OUTPUT_SNMP %IN_PKTS %IN_BYTES %FIRST_SWITCHED %LAST_SWITCHED %L4_SRC_PORT %L4_DST_PORT %TCP_FLAGS %PROTOCOL %EXPORTER_IPV4_ADDRESS"

ntopng:
--pid "/var/run/ntopng.pid" --interface "tcp://127.0.0.1:5556" --data-dir "/var/tmp/ntopng" --http-port "3000" --local-networks "x.y.z.w/19" --max-num-flows "200000" --max-num-hosts "250000" --sticky-hosts "none"

**Comment by emanuele-f** [comment]
Can you post a screenshot of the page showing incorrect results?
Please note that the graph at the bottom of the page shows local-versus-remote traffic and not up-versus-down

![screenshot at 2017-04-10 13-04-43](https://cloud.githubusercontent.com/assets/5488003/24858914/8b0b2662-1dee-11e7-9640-5f725e7ea12b.png)

**Comment by dcsquare** [comment]
![2017-04-10 14_11_26-welcome to ntopng](https://cloud.githubusercontent.com/assets/718334/24859094/c659b69e-1df7-11e7-96c9-54393f53421b.png)

**Comment by simonemainardi** [comment]
@dcsquare , I've just worked on your box. I have been kicked out after a few minutes but, anyway, I was able to find the issue.

Basically, your nProbe configuration file was missing option `--upscale-traffic`. This option is needed to scale up traffic volumes by a factor that is equal to the sFlow sampling size.

After adding option --upscale-traffic volumes went back to normal expected values.

Please, re-edit nProbe and ntopng configuration files, disable verbose logging (remove -b=2 and -v=5)

**Comment by dcsquare** [comment]
@simonemainardi : You haven't been kicked out. The server crashed. As it does daily now.

--upscale-traffic is new? I did not needed that before the update.

Where can I read about each update and what changed? Before updating, preferably...

Thank you.

**Comment by simonemainardi** [comment]
Dan, please try with the latest version. You should no longer experience any crash.
