### ISSUE TITLE
Bad NetBIOS host name association

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#1146]
When using NetBIOS dissection to determine an host name, there are a couple of problems which result into a bad association:
1) There is no discrimination between NetBIOS requests and responses. (see questions.pcap)
2) Only the flow client host is updated with the name from NetBIOS, but this does not take into account the situation where the client host performs a query and the server host replies with the name, in which case the server is the host which should be updated (see answer_rrs.pcap)
3) The host name is not extracted correctly in some queries: the `*` character is returned whereas the field "name" should be used. (see answer_rrs.pcap and screenshot below)

![screenshot at 2017-04-10 18-51-55](https://cloud.githubusercontent.com/assets/5488003/24872844/17680906-1e1f-11e7-9f61-c6cde3322d69.png)

In order to reproduce, remove the existing associations with `redis-cli del ntopng.host_labels` and then use the provided pcap. See 22b21b91553f6df669ade249d031636629d8da0e to enable debug.

[pcap.zip](https://github.com/ntop/ntopng/files/910824/pcap.zip)

**Comment by lucaderi** [comment]
@emanuele-f Please check if this problem is fixed

**Comment by emanuele-f** [comment]
I've found that in some NetBIOS responses, names are terminated by a space (0x20) rather than the null terminator.

![screenshot at 2017-04-11 00-02-11](https://cloud.githubusercontent.com/assets/5488003/24884560/3c71e106-1e4a-11e7-84c3-3f90da2def69.png)

This is handled in commit 7c703ede326273010db4806514e7fa736fd92130

**Comment by simonemainardi** [comment]
@emanuele-f still not fixed:

![image](https://cloud.githubusercontent.com/assets/3397663/24952935/bd6c478a-1f79-11e7-81f2-31629717305c.png)

ERREQ is a name that has nothing to do with 192.168.2.130.

**Comment by emanuele-f** [comment]
This should be solved by commit a530ee282bc4625faec2c0aca6c9b2be5fe45353. We will reopen this isssue if necessary.
