### ISSUE TITLE
More informations about malware alert

### ISSUE THREAD

**Issue by GiuseppeAugiero** [ntop/ntopng#1148]
When ntopng load a blacklist file (https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt) is it possible load a  malware tipology too (such as C&C or Zeus or Dshield etc.) ?

**Comment by emanuele-f** [comment]
Hi @GiuseppeAugiero , do you have any link to interesting malware lists or other malware detection features to add to ntopng?

**Comment by simonemainardi** [comment]
Added as task in https://github.com/ntop/ntopng/issues/1808
