### ISSUE TITLE
No License Option in build 2.0.150807

### ISSUE THREAD

**Issue by kargh** [ntop/ntopng#115]
Just installed this nightly build and it looks like the issue is back where a pro license cannot be added.

I've removed the /etc/ntopng.license file and the option doesn't exist in the about page. It goes directly into Community Edition.

06/Aug/2015 23:37:00 [pro/NtopPro.cpp:212] [LICENSE] ntopng systemId:
06/Aug/2015 23:37:00 [pro/NtopPro.cpp:215] [LICENSE] ntopng is starting without a valid license

**Comment by lucaderi** [comment]
What distribution+version?

**Comment by kargh** [comment]
Centos 6.6

**Comment by lucaderi** [comment]
Fixed in https://github.com/ntop/ntopng/commit/874e9162f8ca42bf990cac9fbf7e80b65cfb26c7
Currently building updated packages that will be available within an hour.

**Comment by kargh** [comment]
Awesome. Much appreciated!
