### ISSUE TITLE
IPv4 vs IPv6 traffic breakdown for network interfaces

### ISSUE THREAD

**Issue by mahescho** [ntop/ntopng#1151]
It wold be nice to know what the amount of IPv4 traffic is compared to IPv6 traffic, perhaps with a host an protocol breakdown.

**Comment by lucaderi** [comment]
@mahescho When computing this per network interface the math is pretty simple (we can schedule this for this upcoming release).

However when doing it at host level we need to bind two different IPs (one IPv4 and one IPv6)  through the MAC address. Perhaps we can postpone this at the next release.

@emanuele-f what do you think? Perhaps we can split this ticket in two sub-tickets.

**Comment by mahescho** [comment]
For my personal intended use "per network interface" would be sufficient. For some one else a additional host based view may be of interest too. Splitting this is a good idea.

I've tried to achieve this by using "Traffic Profiles" but my filters seem not to work. As I have two routers (one with and one without NAT)  I've two different sets of IPs:

IPv4: net 1.2.3.4/29 or host 5.6.7.8
IPv6: net A:B:C::/48 or net D:E:F:A::/56

The result is, that IPv6 counters get updated but IPv4 does not after recording a few KB.

**Comment by emanuele-f** [comment]
Implemented with eca26495d101f1a6f6a63bb7b850d912161518eb. You can find this information into the "Packets" tab under the interface view.

@mahescho please note that "Traffic profiles are applied to flows. Each flow can have up to one profile, thus in case of multiple profile matches, only the first one is selected.". If this is not the case, please open a separate issue describing your traffic profiles configuration. Thank you.

**Comment by mahescho** [comment]
I use ZMQ and due to this the "Packets" tab is not visible in interface view. 

/usr/share/ntopng/scripts/lua/if_stats.lua - line 208:
`if(ifstats.type ~= "zmq") then`
I've commented this out to get the tab. As there i data and it looks reasonable i consider this to be a bug.

Live stats is one thing but it's more important to have "IP Version Distribution" in reports.

**Comment by emanuele-f** [comment]
Please open a separate feature request. Note that we are currently working on releasing the 2.6 version of ntopng and new feature requests will difficulty fit into it.

**Comment by mahescho** [comment]
Ok, but: bug, no FR :-)
