### ISSUE TITLE
nTopNG No Flow and ntopng.log filled with your nProbe sender is outdated?

### ISSUE THREAD

**Issue by juesor** [ntop/ntopng#1152]
I have a nProbe server running nprobe.x86_64 7.5.170331-5706 with a valid license.

I have a nTopNG server running ntopng.x86_64 2.4.170215-1311 also with a valid license.

Both servers are CentOS 7.  Both servers had software installed via yum
Mar 27 16:43:49 Installed: ntopng-2.4.170215-1311.x86_64
Mar 31 09:57:11 Installed: nprobe-7.5.170331-5706.x86_64

I am seeing NetFlow traffic to the nProbe server validated via tcpdump.
I am using the Poll Mode of --zmq-encrypt-pwd

I do not see anything in my nTopNG web UI for my interface.

ntopngmi ~]# lsof -i :5556
COMMAND  PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
ntopng  2953 nobody   19u  IPv4  28425      0t0  TCP ntopng.awesome.sauce:51608->nprobe.awesome.sauce:freeciv (ESTABLISHED)

Above you can see that my ntopng server sees the nprobe connection on my port 5556.

ntopng]# tail -n 2 ntopng.log
12/Apr/2017 13:30:00 [CollectorInterface.cpp:130] WARNING: Unsupported publisher version [-1227913790]: your nProbe sender is outdated?
12/Apr/2017 13:30:00 [CollectorInterface.cpp:130] WARNING: Unsupported publisher version [-1227913790]: your nProbe sender is outdated?

Above you can see that this is what ntopng is displaying in the logs ALL the time.  to the tune of 11GB of logs in the last 4 hours.

Why does it say your nProbe sender is outdated?

**Comment by emanuele-f** [comment]
Hi, you are using stable ntopng (2.4 version) but development nprobe (7.5 version). You should update your ntopng to version 2.5 as described here http://packages.ntop.org/centos/.

**Comment by juesor** [comment]
Updated:
ntopng.x86_64 0:2.5.170412-2544
pfring.x86_64 0:6.5.0-1188
pfring-dkms.noarch 0:6.5.0-1188

I upgraded my ntopng to the latest.

I also upgraded my nprobe
# nprobe -v

Welcome to nProbe v.7.5.170412 (r5728) for x86_64-unknown-linux-gnu

My errors in ntopng.log have stopped but still no traffic.

ZMQ RX Statistics
Collected Flows	0 	
Interface RX Updates	99 	
ZMQ Message Drops	0 
Ingress Traffic
Received Traffic	0 Bytes [0 Pkts] 	
Dropped Packets	0 Pkts

**Comment by lucaderi** [comment]
@juesor Can you please show how you are starting both apps?

**Comment by juesor** [comment]
I am running two CentOS 7 servers.  Both are being started as a systemctl "service" start

ntopng]# cat /etc/ntopng/ntopng.conf
-G=/var/run/ntopng.pid\
--interface="tcp://1##.1##.2##.1##:5556"
--zmq-encrypt-pwd xxxxxxxxxxxxxxxx

ntopng]# systemctl status ntopng
● ntopng.service - Start/stop ntopng program
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-04-12 14:41:50 EDT; 1 day 5h ago
  Process: 19725 ExecStop=/etc/init.d/ntopng stop (code=exited, status=0/SUCCESS)
  Process: 19782 ExecStart=/etc/init.d/ntopng start (code=exited, status=0/SUCCESS)
 Main PID: 19789 (ntopng)
   CGroup: /system.slice/ntopng.service
           └─19789 /usr/bin/ntopng /etc/ntopng/ntopng.conf

Apr 12 14:41:49 ntopng systemd[1]: Starting Start/stop ntopng program...
Apr 12 14:41:49 ntopng ntopng[19789]: [ParserInterface.cpp:490] WARNING: Invalid message received: your nProbe sender is outdated, data encrypted or invalid JSON?
Apr 12 14:41:49 ntopng ntopng[19789]: [242B blob data]
Apr 12 14:41:50 ntopng ntopng[19782]: Starting ntopng: [  OK  ]
Apr 12 14:41:50 ntopng systemd[1]: Started Start/stop ntopng program.


nprobe]# cat nprobe-none.conf
--zmq="tcp://*:5556"
--collector-port=2055
-n=none
--zmq-encrypt-pwd xxxxxxxxxxxxxxxx

nprobe]# systemctl status nprobe
● nprobe.service - Start/stop nprobe program
   Loaded: loaded (/etc/systemd/system/nprobe.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-04-11 17:02:45 EDT; 2 days ago
 Main PID: 17728 (nprobe)
   CGroup: /system.slice/nprobe.service
           └─17728 /usr/local/bin/nprobe /tmp/nprobe-none@0.conf

Apr 11 17:02:45 nprobe systemd[1]: Starting Start/stop nprobe program...
Apr 11 17:02:45 nprobe nprobe[17697]: Starting nProbe none
Apr 11 17:02:45 nprobe systemd[1]: Started Start/stop nprobe program.

Does that fullfil your request?

Still no packets found.  I verified my zmq passwords match.

**Comment by simonemainardi** [comment]
@juesor please, update nprobe and make sure to have a version >= nprobe.x86_64 7.5.170413. The bug you reported has been fixed a couple of days ago.

**Comment by juesor** [comment]
Fixed.
