### ISSUE TITLE
Confuse IN_BYTES on NTOP?

### ISSUE THREAD

**Issue by tieungao88** [ntop/ntopng#1154]
Dear all,
I have confuse about **IN_BYTES** values.  I am using NTOP with Elastic + Kibana.
I want to caculator **bandwidth of network** dependence **IN_BYTES.** I got **AVG IN_BYTES** on time range **1min** but result values is not correct.
Everyone,Do your know it? 

Thanks.

**Comment by simonemainardi** [comment]
Can you please try to reformulate you question? Also add examples if those can be useful.

Also note that you may want to use nProbe as it already has mechanisms to calculate the throughput. You just have to use these fields:

```
[NFv9 57554][IPFIX 35632.82] %SRC_TO_DST_MAX_THROUGHPUT         Src to dst max thpt (bps)
[NFv9 57555][IPFIX 35632.83] %SRC_TO_DST_MIN_THROUGHPUT         Src to dst min thpt (bps)
[NFv9 57556][IPFIX 35632.84] %SRC_TO_DST_AVG_THROUGHPUT         Src to dst average thpt (bps)
[NFv9 57557][IPFIX 35632.85] %DST_TO_SRC_MAX_THROUGHPUT         Dst to src max thpt (bps)
[NFv9 57558][IPFIX 35632.86] %DST_TO_SRC_MIN_THROUGHPUT         Dst to src min thpt (bps)
[NFv9 57559][IPFIX 35632.87] %DST_TO_SRC_AVG_THROUGHPUT         Dst to src average thpt (bps)
```

**Comment by tieungao88** [comment]
Hi,
I will describe for you about my topo:
I have Switch. I config one span port.
Span port plug in NTOPNG. 
NTOPNG out information to Elasticsearch.
Kibana read information of Elasticsearch.

In Kibana, I have info: IN_Bytes and Out_Bytes for each flow.  I want to caculate bandwidth form above values.
![22976cd46fa14da2bc10af9bb7ee39ce](https://cloud.githubusercontent.com/assets/6977423/25010226/a9853216-2093-11e7-9ea9-e5a20c412ff5.png)



Thanks.

**Comment by simonemainardi** [comment]
IN_BYTES is server 2 client, OUT_BYTES is client 2 server.

Divide IN_BYTES+OUT_BYTES by the flow duration (LAST_SWITCHED - FIRST_SWITCHED). In this way you will find the average volume of data that has travelled on your flow during every second:

```
(IN_BYTES+OUT_BYTES) / (LAST_SWITCHED - FIRST_SWITCHED)
```

**Comment by tieungao88** [comment]
Hi @simonemainardi ,
If I use formal: 
`average volume data = (IN_BYTES+OUT_BYTES) / (LAST_SWITCHED - FIRST_SWITCHED)`
=> Result = N/A
![image](https://cloud.githubusercontent.com/assets/6977423/25060853/b75017dc-21d1-11e7-8047-fe8392a8fa62.png)

**## And ! LAST_SWITCHED, FIRST_SWITCHED , What does it mean?**

Thanks :).

**Comment by simonemainardi** [comment]
If fisrt and last switched are equal then you divide by zero and the result is nan. Add a +1 to the denominator

**Comment by tieungao88** [comment]
Thansk.
