### ISSUE TITLE
IPv4 vs IPv6 traffic breakdown for mac addresses

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#1155]
It is requested to implement IPv4 vs IPv6 traffic comparison per-host as #1151 is implemented per-interface.

**Comment by emanuele-f** [comment]
@lucaderi can we implement this as a runtime view on the host data? At runtime, when user clicks on the mac address packets tab, I look for the associated ip and ipv4 hosts and calculate the breakdown based on their current traffic.
Otherwise, for a full implementation, we need to keep two more counters (ipv4 traffic and ipv6 traffic) on the mac address and update them when we periodically walk the hosts for stats update.

**Comment by lucaderi** [comment]
Yes it is good as you have described it, but bear in mind what happens when host disappear from memory (e.g. when idle)
