### ISSUE TITLE
Password with & -

### ISSUE THREAD

**Issue by ESTIA-InstituteOfTechnology** [ntop/ntopng#1157]
Hi,
I’m blocked me the admin user with a password content & and -. It's impossible to reconnect me to the administration page
 
But the ntopng is installed on virtual machine, i rollback to the old snapshot whith the same systemdid and  I reactived with the same systemID but it not works.

Can you help me to re-activate my licence ?

Thanks
Benoît

**Comment by emanuele-f** [comment]
What ntopng version are you running? Do you use the `--online-license-check` ntopng option?

**Comment by ESTIA-InstituteOfTechnology** [comment]
the version is 2.5.170413. 
with the commande ntopng --online-license-check, its works and my license is active.
I was accustomed to use "service notpng start"

for the password with the character "&" , have you an idea why the password don't work ?
It works with @ for example.

Thanks
Benoît

**Comment by emanuele-f** [comment]
Fixed with a10d6c4f7d068624945e0c0040b7338b8d6367b0. Thank you for reporting.
