### ISSUE TITLE
Lots of empty horizontal space in Name field

### ISSUE THREAD

**Issue by PSmolders** [ntop/ntopng#1159]
Using ntopng 2.5.170414 on Ubuntu Server 16.04.2

The name field of the hosts page show a lot of empty horizontal space, while the server name is cut off. This seems like a waste of space. If I'm using a big monitor, I would expect tables and their contents to scale according to the available space and not cut the contents while there is enough space left. Is this intended or a bug? Using a 1920x1080 monitor.

![afbeelding](https://cloud.githubusercontent.com/assets/8997593/25036547/c4f68b74-20f4-11e7-8f69-f321110c64c6.png)

**Comment by simonemainardi** [comment]
Maximum displayed string length is now configurable from the preferences:

![image](https://user-images.githubusercontent.com/3397663/28460908-8499f9cc-6e14-11e7-9eaf-8ad537ac0a4c.png)
