### ISSUE TITLE
lua error in talkers

### ISSUE THREAD

**Issue by lucadistefano** [ntop/ntopng#116]
![ntopngluaerr](https://cloud.githubusercontent.com/assets/1080723/9130678/2ffa4abe-3ce5-11e5-9e1a-f47ae03c6b00.jpg)

**Comment by lucaderi** [comment]
please report exact ntopng version and check first if the dev version of ntopng works

**Comment by lucaderi** [comment]
Looking at the code it looks like you are using an old ntopng version. Please upgrade to the latest development version.

**Comment by lucadistefano** [comment]
cannot upgrade to latest version:

--> Finding unneeded leftover dependencies
Found and removing 0 unneeded dependencies
Error: Package: ntopng-2.0.150810-355.x86_64 (ntop-beta)
           Requires: libzmq.so.4()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

where I can find missing dep? Until last week the zeromq3 was the required dep.

**Comment by lucaderi** [comment]
please read http://packages.ntop.org/centos/
