### ISSUE TITLE
Bug: Pacekts tab not shown in Interfaces with ZMQ

### ISSUE THREAD

**Issue by mahescho** [ntop/ntopng#1163]
I use ZMQ and due to this the "Packets" tab is not visible in interface view.

/usr/share/ntopng/scripts/lua/if_stats.lua - line 208:
if(ifstats.type ~= "zmq") then
I've commented this out to get the tab. As there i data and it looks reasonable i consider this to be a bug.

Live stats is one thing but it's more important to have "IP Version Distribution" in reports.

**Comment by emanuele-f** [comment]
Fixed in 03428e6f033a98b4d172a21a6e49eadcfc616301
