### ISSUE TITLE
Invalid Host Labels

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#1165]
Host labels contain invalid characters. This also yield an empty hosts page:

![image](https://cloud.githubusercontent.com/assets/3397663/25141566/31c750b8-2464-11e7-8000-0dc3b2f23c99.png)

![image](https://cloud.githubusercontent.com/assets/3397663/25141337/910be2e2-2463-11e7-9885-d8ab18233f6d.png)

![image](https://cloud.githubusercontent.com/assets/3397663/25141636/6499c2be-2464-11e7-881f-1073ad64e106.png)

**Comment by emanuele-f** [comment]
I was not able to reproduce the issue but  with 704cf4844e8d0a2999f95c08b0db4fcc47c40c9d I've implemented some stricter checks on the names which I expect to solve the issue. Please reopen if necessary.
