### ISSUE TITLE
error when changing preferences

### ISSUE THREAD

**Issue by LXicon** [ntop/ntopng#1169]
Hi, thanks for all your work on ntopng. I did come across an error when saving my preferences though:

url : http://**redacted**/lua/admin/prefs.lua?tab=alerts

Script "/usr/local/ntopng/scripts/lua/admin/prefs.lua" returned an error:
/usr/local/ntopng/scripts/lua/modules/http_lint.lua:932: [LINT] _POST["toggle_malware_probing"] = "disabled" parameter error: Validation error

here is my config file:
--pid=/var/run/ntopng.pid
--data-dir=/var/tmp/ntopng
--install-dir=/usr/local/ntopng
--httpdocs-dir=/usr/local/ntopng/httpdocs
--scripts-dir=/usr/local/ntopng/scripts
--callbacks-dir=/usr/local/ntopng/scripts/callbacks
--dns-mode=0
--traffic-filtering=disabled
--dump-hosts=none
--sticky-hosts=none
--capture-direction=0
--interface=enp1s0
--no-promisc
--local-networks=**redacted**
--max-num-flows=131072
--max-num-hosts=65536
--http-port=**redacted**
--https-port=0
--disable-login=1
--daemon

(edit) - i forgot to add the version number
ntopng x86_64 v.2.5.170419 - (C) 1998-17 ntop.org

**Comment by emanuele-f** [comment]
Thank you for reporting.
