### ISSUE TITLE
Display VLAN RRDs + Preference

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#1172]
Vlan traffic statistics (bytes and l7 protocols) are now properly saved in 5min.lua. It is requested to handle the chart link in 'vlan_stats.lua' to peroperly visualize VLAN RRDs.

It is also requested to add a preference (off by default) to toggle the creation of VLAN rrds.

**Comment by emanuele-f** [comment]
Implemented in b83a93c6a58320ebff47ab15381b75b68f482aec
