### ISSUE TITLE
No results from historical data explorer

### ISSUE THREAD

**Issue by Alestor** [ntop/ntopng#1173]
Hi,

when I search flows from mysql I don't get any results back. There is no error message nor a message about "n ipvX flows found".  After hitting the seach flows button the page just looks the same when opening the historical data explorer.

MySQL is up and running. Flow export works, too.

23/Apr/2017 14:17:48 [NetworkInterface.cpp:1999] Started packet polling on interface eth1 [id: 2]...
23/Apr/2017 14:17:49 [MySQLDB.cpp:583] Attempting to connect to MySQL for interface eth1...
23/Apr/2017 14:17:49 [MySQLDB.cpp:623] Successfully connected to MySQL [localhost:ntopng_user] for interface eth1

ntopng -V
v.2.5.170423 [Enterprise/Professional Edition]
GIT rev:   dev:704cf4844e8d0a2999f95c08b0db4fcc47c40c9d:20170423
Pro rev:   r1045

**Comment by emanuele-f** [comment]
Fixed with commit eb167e8deeae3934e7a79f094b4419957b5e2ebd. Thank you for reporting.
