### ISSUE TITLE
Bridged traffic counters

### ISSUE THREAD

**Issue by ValentinaViscarelli** [ntop/ntopng#1174]
When you use ntopng in bridge mode with zc interfaces. The bridged traffic counters are wrong.
If you see the attached screenshot you can see that the rate of "zc:enp6s0 -> zc:enp8s0" direction is 1.44 Gbit/s but the links of my board are 1 Gbit/s.
if you add the ingress packets of "zc:enp6s0 -> zc:enp8s0" and "zc:enp6s0 -> zc:enp8s0" direction (12023800+1471838 = 13495638 ) you get more o less the double of received packet (2*6747810 = 13495620 ); so I think that the packets are counted twice.

![welcome to ntopng - google chrome_040](https://cloud.githubusercontent.com/assets/13115771/25317407/723b6e64-2878-11e7-8a0d-b0b03e8e7815.png)

**Comment by simonemainardi** [comment]
Already identified and wrongly assumed to be solved in https://github.com/ntop/ntopng/issues/1133

Fix is in progress

**Comment by simonemainardi** [comment]
fixed along with other counter issues in the pro branch
