### ISSUE TITLE
Can't login after enabling LDAP

### ISSUE THREAD

**Issue by hgpit** [ntop/ntopng#1175]
Hi all,

We're brand new to ntopng, having purchased our ntopng and nProbe license within the last 24 hours.

Going through the preferences and settings, we've enabled LDAP and tried to configure it as best we can for out Active Directory environment.
Unfortunately, it must not have gone well, as now the login page won't accept any logins at all (not even the original admin login!).

Please can someone tell me how I can disable LDAP authentication from the CLI?

Thank you!

**Comment by emanuele-f** [comment]
Hi, to reset the authentication method run the following command
`redis-cli set ntopng.prefs.auth_type local`

**Comment by hgpit** [comment]
Wow, what a speedy response.

Worked perfectly, thank you!

Out of interest, I've been greping files all over the system to try and find where it had stored the settings.
Where exactly are they stored? Are they encrypted, which would explain why I couldn't find them (yet)?

Thank you!

**Comment by emanuele-f** [comment]
We use [redis](https://redis.io/), a key-value store, to save configuration. Redis works in memory, but dumps data to `/var/lib/redis/dump.rdb` for persistency.

**Comment by hgpit** [comment]
Ok, thank you :)
