### ISSUE TITLE
No hosts, no networks found

### ISSUE THREAD

**Issue by hgpit** [ntop/ntopng#1176]
Hi all,

Purchased ntopng and nProbe yesterday.
Installed and running on CentOS7.

Was mostly going great, got our core router feeding it NetFlow data. Plenty of host and network data being compiled.

Had a slight issue with LDAP, which I resolved via this forum, and since then been showing my team how great it is... until...
Now, suddenly, we click on Hosts or Networks, and it says 'No Results Found' for either :(

We have tried logging out and back in - but doesn't fix.
We have tried restarting ntopng - but doesn't fix.

The only thing I can think of which changed is I did a YUM update a short while ago:
"
---> Package cento.x86_64 0:1.2.170215-93 will be updated
---> Package cento.x86_64 0:1.2.170423-93 will be an update
---> Package n2disk.x86_64 0:2.6.170215-4673 will be updated
---> Package n2disk.x86_64 0:2.6.170423-4676 will be an update
---> Package nprobe.x86_64 0:7.4.170215-5334 will be updated
---> Package nprobe.x86_64 0:7.4.170423-5334 will be an update
---> Package ntopng.x86_64 0:2.4.170215-1311 will be updated
---> Package ntopng.x86_64 0:2.4.170423-1311 will be an update
---> Package ntopng-data.noarch 0:2.4.170215-1311 will be updated
---> Package ntopng-data.noarch 0:2.4.170423-1311 will be an update
---> Package pfring.x86_64 0:6.4.1-1143 will be updated
---> Package pfring.x86_64 0:6.4.1-1193 will be an update
---> Package pfring-dkms.noarch 0:6.4.1-1143 will be updated
---> Package pfring-dkms.noarch 0:6.4.1-1193 will be an update
--> Finished Dependency Resolution
"

Did this update break ntopng :(

Any help appreciated.

Best Regards,

Elliot

**Comment by hgpit** [comment]
Ok, I decided to try a complete server reboot, which meant other services on this box went down, so it's obviously not ideal. But... they Hosts and Networks page is now displaying properly.

Any feedback appreciated. Is ntopng a bit quirky when being updated?

Thank you.

**Comment by simonemainardi** [comment]
@hgpit thanks for reporting. It could be. As you are starting clean, I would recommend you to use the dev versions of  both nprobe and ntopng. They are stable now and we are preparing their stable release.

**Comment by emanuele-f** [comment]
@hgpit in order to update ntopng to the dev version, please follow these steps:
- stop ntopng and nProbe (e.g. `systemctl stop ntopng`)
- flush data: `rm -rf /var/tmp/ntopng && redis-cli flushall`
- update both ntopng and nProbe to the nightly builds using the instructions at http://packages.ntop.org/
- start ntopng and nProbe (e.g. `systemctl start ntopng`)
