### ISSUE TITLE
Large networks list

### ISSUE THREAD

**Issue by hgpit** [ntop/ntopng#1177]
Hi all,

Originally I had 10.11.0.0/16 in my "/etc/ntopng/ntopng.conf" as my local networks. But I wanted to see all my branch networks separately when I click on "Networks" via the GUI; so I instead replaced it with 10.11.11.0/24, 10.11.45.0/24 etc. Problem is I have about 50 different networks.

Is it okay to literally list dozens and dozens of 24bit networks, or can I point the config line to a file (I notice you can do this with some other config areas).

Oh, also, can I add aliases anywhere, so my users can identify the networks by their branch title/name?

Thank you.

**Comment by simonemainardi** [comment]
Hi, there's no limit hard on the size of the string so you can specify a list of 50+ networks. Just put them in a sigle line, e.g., -m="network1,network2,..,network52".

The maximum number of allowed local networks is 255.
