### ISSUE TITLE
Incorrect traffic

### ISSUE THREAD

**Issue by dcsquare** [ntop/ntopng#1178]
Below are the traffic graphs from ntopng and Cacti. On the same interface.

Today we had 2 attacks, none was catched by ntopng.

I need to see the target of an attack.

![2017-04-24 14_28_35-welcome to ntopng](https://cloud.githubusercontent.com/assets/718334/25335280/066293ba-28fb-11e7-8aa1-e5452f6c7b0c.png)

![2017-04-24 14_29_28-graphs -_ tree mode -_ no103-hw-6720-stack - traffic - eth-trunk100 - 65 - 10000](https://cloud.githubusercontent.com/assets/718334/25335283/0ad2c0fa-28fb-11e7-8d2c-c903190a6ed7.png)

**Comment by simonemainardi** [comment]
@dcsquare can you please try and give extra information? When did the attacks occurred? At the spikes around 10.45 and 14.15? It could be that, during these spikes, network congestion/drops prevented data from flowing from nprobe to ntopng causing the two notches in the charts.

How are the ntopng and nprobe configured?

**Comment by dcsquare** [comment]
@simonemainardi Thank you for your response.

I don't know what the issue was and I gave up on ntopng and switched back to sflowtrend. It shows me the attacks, no problem.

From my experience, ntopng is nowhere near ready for production. I could not use the stable version as apparently that cannot handle Huawei switches and the development version is alpha quality at best.

Perhaps I'm not the right customer for ntopng. I'll maybe revisit in a couple of years.

**Comment by simonemainardi** [comment]
@dcsquare Thanks for your feedback.

Can you please comment a little bit more on the attacks? Although there's much room to improve ntopng, I am not sure we should blame it in this case. Specifically, are the two notches shown in the charts due to the sFlow exporters failing to properly export sFlow under attack?

Any extra information you would like to share will be appreciated.

**Comment by dcsquare** [comment]
No, the only sFlow exporter was working properly. 
It's 2 X Huawei S6720 configured in stack. It's at 2% utilization so far. Sflowtrend reported every attack.

But since the update that bricked the ntopng on my box (the last bug I reported) the traffic shown was very different to the one shown by Cacti. 

I don't know why and I really don't have the time to be a beta/alpha tester. Sorry.
I consider the license I bought as a donation.

Thank you.

**Comment by emanuele-f** [comment]
Closing the issue. Thank you for the information provided.
