### ISSUE TITLE
Shaped/dropped flow info page glitch

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#1179]
When selecting a shaped/dropped flow for inspection (flow_details.lua page) a "No quota" appear initially and then disappear immediately after the first ajax call refreshes the page

![image](https://cloud.githubusercontent.com/assets/3397663/25338583/08665980-2900-11e7-9674-cf42be3dc26c.png)

![image](https://cloud.githubusercontent.com/assets/3397663/25338590/0de42a18-2900-11e7-828b-a5c5f8159c43.png)

**Comment by emanuele-f** [comment]
Fixed with 52cdd7382aa4f02d065f9c0a0403ecf619b34089
