### ISSUE TITLE
SNMP button disappears after upgrade (2.4->2.5)

### ISSUE THREAD

**Issue by hgpit** [ntop/ntopng#1181]
Hi all,

I just upgraded our licensed ntopng Pro from v2.4 to v2.5 as per a recommendation on this forum.
Restarted the ntopng services and started looking around to see what's new.

Straight away we have noticed that hosts no longer have the 'SNMP' button. Additionally, if I go into the 'expert' preferences, under Admin, I see an 'SNMP' section, but clicking this just gives me a blank preferences pane.

Is there a known issue with SNMP on this version?

Thank you

**Comment by hgpit** [comment]
I tried rebooting the whole server, but the problem still remains.

**Comment by emanuele-f** [comment]
Hi, SNMP support is only available in the Enterprise version of ntopng

**Comment by hgpit** [comment]
Has that changed since v2.4 because we were using it for most of the day yesterday?

**Comment by hgpit** [comment]
Also, http://www.ntop.org/announce/say-hello-to-ntopng-2-0/ specifically says: "Added SNMP support for visualising MIB-II host information through the ntopng web interface." for the Pro version.

**Comment by hgpit** [comment]
I just checked the shop (https://shop.ntop.org/cart.php), and there isn't even an Enterprise edition listed, so now I'm really confused :-|

**Comment by emanuele-f** [comment]
Currently the enterprise edition is only available for trial on demand.
Nevertheless, we are discussing if the SNMP information from the host page can be provided in the standard pro version of ntopng, we'll update you on this as soon as possible.

**Comment by hgpit** [comment]
Hi emanuele-f,

What you're saying is still inconsistent.

Your own [website](http://www.ntop.org/announce/say-hello-to-ntopng-2-0/) says SNMP is available in **Pro**.
We purchased **Pro** (v2.4) and had SNMP working fine. We loved it.
We upgraded to v2.5 and SNMP seems "broken", but your response is that it's not available in **Pro**?

Well, I just downgraded back to v2.4 and SNMP is back and working fine (for 51 mins and counting).

If SNMP is enabled in my Pro version due to a bug, and it's not supposed to be working, then you have mis-sold this software, and your advertising/featurelist is wrong and deceiving.

I would really appreciate a definitive answer on this as if it has been sold in this way, then I will be seeking a refund.

Best Regards

**Comment by hgpit** [comment]
Hello,

I am still waiting on an official statement from ntopng regarding this.

To re-iterate, we purchased a license for Pro, which currently includes SNMP functionality. This license guarantees 12 months of updates.

You are implying that you are removing features from Pro in the imminent future (v2.5+) and only making them available in Enterprise. Thus, we would no longer be getting what we paid for.

This doesn't even sound legal to me.

Can you at least pledge that customers will receive **continued** SNMP functionality in Pro for the next 12 months, persistently through updates?

In anticipation of your reply.

Regards,

**Comment by lucaderi** [comment]
@hgpit This behaviour is a bug and it needs to be corrected. Thanks for reporting it

**Comment by emanuele-f** [comment]
Fixed. @hgpit update to the tomorrow version to get the button back.
