### ISSUE TITLE
SegFault after nprobe starting

### ISSUE THREAD

**Issue by Thorfinn3** [ntop/ntopng#1183]
Hello,

I have a big problem with my nprobe. The software beginning well but after 30s I already have a segmentation fault error. I don't know how to fix it ...
I have to a problem with my Licence because it is the good license which is in the file nprobe.license.

Build OS:      Raspbian GNU/Linux 8.0 (jessie)
SystemID:      FD3D485B499602D2
GIT rev:       dev:847d2a4bf23a318c1f809e45bc9d12045394232b:20170419
License:       Invalid nProbe license (/etc/nprobe.license) [License mismatch error]

root@raspberrypi:/etc# nprobe --zmq "tcp://*:5556" -i eth0 --online-license-check
25/Apr/2017 07:04:54 [plugin.c:176] No plugins found in ./plugins
25/Apr/2017 07:04:54 [plugin.c:184] Loading 24 plugins [.so] from /usr/local/lib/nprobe/plugins
25/Apr/2017 07:04:54 [nprobe.c:2121] Contacting licensing server. Please hold on...
25/Apr/2017 07:04:54 [nprobe.c:3615] Valid nProbe license found
25/Apr/2017 07:04:54 [nprobe.c:5490] WARNING: The output interfaceId is set to 0: did you forget to use -Q perhaps ?
25/Apr/2017 07:04:54 [nprobe.c:5493] WARNING: The input interfaceId is set to 0: did you forget to use -u perhaps ?
25/Apr/2017 07:04:54 [nprobe.c:5592] Welcome to nProbe v.7.5.170419 ($Revision: 5740 $) for armv7l-unknown-linux-gnueabihf 
25/Apr/2017 07:04:54 [nprobe.c:5602] Running on Raspbian GNU/Linux 8.0 (jessie)
25/Apr/2017 07:04:54 [nprobe.c:5613] [LICENSE] nProbe SystemId: FD3D485B499602D2
25/Apr/2017 07:04:54 [nprobe.c:5702] WARNING: -n parameter is missing. 127.0.0.1:2055 will be used.
25/Apr/2017 07:04:54 [nprobe.c:5727] Sample rate [packet: 1][flow: 1]
25/Apr/2017 07:04:54 [nprobe.c:8066] Welcome to nProbe v.7.5.170419 for armv7l-unknown-linux-gnueabihf
25/Apr/2017 07:04:54 [plugin.c:1068] 0 plugin(s) enabled
25/Apr/2017 07:04:54 [nprobe.c:7576] Non IPv4/v6 traffic is discarded according to the template
25/Apr/2017 07:04:54 [util.c:430] GeoIP: loaded AS config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNum.dat
25/Apr/2017 07:04:54 [util.c:441] GeoIP: loaded AS IPv6 config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNumv6.dat
25/Apr/2017 07:04:54 [nprobe.c:6173] Using packet capture length 128
25/Apr/2017 07:04:54 [nprobe.c:8243] IPv6 traffic will NOT be exported/accounted by this probe
25/Apr/2017 07:04:54 [nprobe.c:8244] due to configuration options (e.g. use NetFlow v9)
25/Apr/2017 07:04:54 [nprobe.c:8245] Please use -V to set the version to other than NetFlow V5
25/Apr/2017 07:04:54 [nprobe.c:8400] Capturing packets from interface eth0 [snaplen: 128 bytes]
25/Apr/2017 07:04:54 [util.c:4127] Initializing ZMQ as server
25/Apr/2017 07:04:54 [util.c:4170] Succesfully created ZMQ endpoint tcp://*:5556
25/Apr/2017 07:04:54 [util.c:3216] nProbe changed user to 'nobody'
25/Apr/2017 07:04:54 [nprobe.c:8615] nProbe started successfully
Segmentation fault

**Comment by simonemainardi** [comment]
please use the nProbe issue tracker: https://github.com/ntop/nProbe/issues
