### ISSUE TITLE
Elasticsearch --dump-flows crashes ntopng . Windows 10

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#1185]
To reproduce:
- Have a local elasticsearch running at "localhost:9200"
- Current version of ntop: v.2.4.160627
- When executing the following command in order to post flow to elasticsearch, the program crashes:

ntopng.exe /c --community --dump-flows es;ntopng;ntopng-%Y.%m.%d;http://localhost:9200/_bulk; -v

Attached is the ntopng.log [ntopng.txt](https://github.com/ntop/ntopng/files/958605/ntopng.txt)

**Comment by lucaderi** [comment]
Fixed in http://packages.ntop.org/Windows/preview/, will be included in the next stable
