### ISSUE TITLE
Can't remove traffic profile

### ISSUE THREAD

**Issue by joelphilippage** [ntop/ntopng#1188]
I am running ntopng professional for small businesses on Windows Server 2016 with the latest build.

I added a traffic profile named "Joel's Computer". It seemed to be working fine, but I started experiencing issues on startup where ntopng would get stuck after connecting MySQL for the dummy interface. When it does start, I see these 4 lines repeated continuously in the log:
```
26/Apr/2017 12:25:27 [MySQLDB.cpp:495] Attempting to connect to MySQL for interface NPF_{C52860A3-18FD-42D8-A159-EE87DDD35288}...
26/Apr/2017 12:25:27 [MySQLDB.cpp:535] Succesfully connected to MySQL [localhost:root] for interface NPF_{C52860A3-18FD-42D8-A159-EE87DDD35288}
26/Apr/2017 12:25:27 [MySQLDB.cpp:50] ERROR: MySQL error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's Computer')' at line 1
26/Apr/2017 12:25:27 [MySQLDB.cpp:51] ERROR: INSERT INTO `flowsv4` (VLAN_ID,L7_PROTO,IP_SRC_ADDR,L4_SRC_PORT,IP_DST_ADDR,L4_DST_PORT,PROTOCOL,IN_BYTES,OUT_BYTES,PACKETS,FIRST_SWITCHED,LAST_SWITCHED,INFO,JSON,NTOPNG_INSTANCE_NAME,INTERFACE_ID,PROFILE) VALUES ('0','91','167785853','49401','873790795','443','6','411','120','5','1493231120','1493231122','scss-prod-ue1-notif-39.adobesc.com',COMPRESS('{ "8": "10.0.53.125", "12": "52.20.253.75", "7": 49401, "11": 443, "4": 6, "57590": 91, "57591": "SSL", "6": 26, "2": 3, "1": 411, "24": 2, "23": 120, "22": 1493231120, "21": 1493231122, "57595": 0.178000, "57596": 302.964000, "DST_IP_COUNTRY": "US", "DST_IP_LOCATION": [ -77.483803, 39.033501 ], "PROFILE": "Joel''s Computer", "NTOPNG_INSTANCE_NAME": "IM-SecondServer", "INTERFACE": "NPF_{C52860A3-18FD-42D8-A159-EE87DDD35288}", "SSL_SERVER_NAME": "scss-prod-ue1-notif-39.adobesc.com", "PASS_VERDICT": true }'), 'IM-SecondServer', '3','Joel's Computer') 
```
When viewing the **Edit Traffic Profiles** page, the profile name is just "Joel" leaving off the "'s Computer". I try to clear out the values and click save profile, but the information is still there when I return to the page.

**Comment by emanuele-f** [comment]
On linux, to reset the profiles I would run `redis-cli del ntopng.prefs.profiles`. Can you execute that command on your Windows Server?

Update: by the way, what browser are you using? The apostrophe in the input field should be blocked by your browser..

**Comment by joelphilippage** [comment]
That command successfully removed all the profiles. I am still getting the SQL error though. I will see if a reboot affects it when I get the chance. Thanks!

**Comment by emanuele-f** [comment]
If you create a new dummy profile within the gui (and save configuration) you should be able to reload the configuration wiithout the reboot. Nevertheless, I've patched the code as a server-side check on the profile name was missing, so thank you for reporting.
