### ISSUE TITLE
'Info' field in MySQL are empty

### ISSUE THREAD

**Issue by nam412** [ntop/ntopng#1189]
I have 1 Ntopng and 4 nprobes. 
On the ntopng web I can see many flows with info field but in the ntopng database, the 'info' field are empty for 4 nprobes.

In Nprobe PC (interface ID is 19), I use this command :
$ sudo nprobe --zmq tcp://*:5556 -T "%IPV4_SRC_ADDR %IPV4_DST_ADDR %IPV4_NEXT_HOP %INPUT_SNMP %OUTPUT_SNMP %IN_PKTS %IN_BYTES %FIRST_SWITCHED %LAST_SWITCHED %L4_SRC_PORT %L4_DST_PORT %TCP_FLAGS %PROTOCOL %DNS_QUERY %DNS_RET_CODE  %DNS_RESPONSE"
In Ntopng PC, I add this command line in ntopng.conf file :
-F="mysql;localhost;ntopng;flows;root;123456"

Flows are dumped to MySQL, but the "info" field are empty for 4 nprobes.
My ultimate goal is knowing the DNS queries of every IP.
How can I dump flows to MySQL properly ?
Please help me
Thanks,

**Comment by emanuele-f** [comment]
Please specify the ntopng and nProbe version used

**Comment by nam412** [comment]
My ntopng version is Pro Small Business Edition 2.4..170109
My nprobe version is nprobe Pro 7.4.170109

**Comment by simonemainardi** [comment]
INFO column contains the server name, that, is the certificate CN name if the flow is SSL, or the plain server name for HTTP.

The information you are looking for is located in column JSON, which contains compressed data automatically decompressed by ntopng during visualization. If you want to uncompress it manually, do a `select uncompress(JSON) from flowsv4`
