### ISSUE TITLE
Missing alert explorer icon in engaged alerts (but present in flow alerts)

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1191]
<img width="319" alt="screen shot 2017-04-27 at 19 28 11" src="https://cloud.githubusercontent.com/assets/4493366/25496006/b0e2813e-2b7f-11e7-9757-3a55a44b6513.png">
<img width="234" alt="screen shot 2017-04-27 at 19 28 03" src="https://cloud.githubusercontent.com/assets/4493366/25496007/b0e4d5a6-2b7f-11e7-953f-14cfc1ce8f60.png">

**Comment by simonemainardi** [comment]
Alert explorer is only for flow alerts presently this explains why the icon is only present in flow alerts.

**Comment by simonemainardi** [comment]
alert explorer is implemented for flow alerts
