### ISSUE TITLE
Host alert counter out of sync

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1192]
<img width="697" alt="screen shot 2017-04-27 at 19 29 58" src="https://cloud.githubusercontent.com/assets/4493366/25496084/f584b596-2b7f-11e7-8b6f-3cecf20ebd11.png">
<img width="508" alt="screen shot 2017-04-27 at 19 29 48" src="https://cloud.githubusercontent.com/assets/4493366/25496083/f58008ca-2b7f-11e7-9654-6e26391772c5.png">

The host seems to have two alerts triggered, in the engaged alerts view only one alert is present

**Comment by emanuele-f** [comment]
Fixed with 8537b2cc0a6d237b910871b6a6d21b4242fa6514
