### ISSUE TITLE
Alert explorer counter out of sync

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1193]
<img width="467" alt="screen shot 2017-04-27 at 19 33 51" src="https://cloud.githubusercontent.com/assets/4493366/25496255/7de88426-2b80-11e7-9e4e-afd5eef43073.png">
<img width="341" alt="screen shot 2017-04-27 at 19 33 20" src="https://cloud.githubusercontent.com/assets/4493366/25496254/7de16272-2b80-11e7-8874-8c56a43f037a.png">
For a specific host the number of flow alerts in the host view (http://xxxx:3000/lua/host_details.lua?ifid=0&host=yyyy&page=alerts#tab-table-flow-alerts-history) is different from the number of alerts reported for the same host in the flow explorer (http://xxxx:3000/lua/pro/enterprise/flow_alerts_explorer.lua?tab=tab-table-flow-alerts-history&period_begin_str=26%2F04%2F2017+19%3A31%3A35&period_end_str=27%2F04%2F2017+19%3A31%3A35&num_minutes=1440&origin=yyyy&target=&flowhosts_type=all_hosts&search=1#tab-table-flow-alerts-history)

**Comment by emanuele-f** [comment]
In the flow_alerts_explorer, the time window you are using is one day (since num_minutes=1440) so you are only seeing one day flow alerts for the host. For contrast, in the host page there are all the host flow alerts ever seen. Can this be the reason of the issue?

**Comment by lucaderi** [comment]
Supposing this is the case, they are not in sync and the info you need to report must be consistent. What you are saying is mostly related to internals and it is not relevant to the user who sees a discrepancy. This issue ought to be fixed.

**Comment by emanuele-f** [comment]
@simonemainardi the flow alert explorer only shows "flows" alerts, so why does the past alerts contain a link to the explorer?

#1191

**Comment by simonemainardi** [comment]
"past alerts" should not have a link to the flows alerts explorer
