### ISSUE TITLE
Invalid alert reported for blacklist host

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1194]
1. Suppose an host X has been contacted by a blacklisted host Y. The alert explorer (see below)
<img width="360" alt="screen shot 2017-04-27 at 19 37 25" src="https://cloud.githubusercontent.com/assets/4493366/25496366/f7c63c70-2b80-11e7-99e6-793859b89faa.png">
X has been reported as both origin and target (wrong it is just target but the origin should be Y)

2. The alert below is meaningless: it should state if the blacklisted host contacted or has been contacted by, and specify both origin and target
<img width="1091" alt="screen shot 2017-04-27 at 19 38 38" src="https://cloud.githubusercontent.com/assets/4493366/25496416/2cf89712-2b81-11e7-9981-0ba0e645c81a.png">. Inside the flow alerts instead, it is correctly specified the host target and origin.
<img width="495" alt="screen shot 2017-04-27 at 19 40 16" src="https://cloud.githubusercontent.com/assets/4493366/25496461/620c114a-2b81-11e7-90ac-5085b3425a28.png">

**Comment by emanuele-f** [comment]
Can we say that the alert on the host (Malware Detected alert) is redundant and can be removed as the alert on a flow already contains this information? If it isn't, than we need to move the generation of this alert from Host.cpp to Flow.cpp in order to show both the contacting and the contacted host into the alert message.

**Comment by lucaderi** [comment]
No. All I am asking you is to specify in the alert message what are the peers and their role. i need to know if host X has contacted a blacklisted host or the other way round.

**Comment by emanuele-f** [comment]
Implemented with commit 284dfcd4cdea6bdc103d7a331f14d0d9db49e0ea
