### ISSUE TITLE
Invalid SYN flood alert reported

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1195]
The alert below is wrong as
1. the alert threshold was 10 and not 1
2. the alert is still open even though it should have been closed by now (invalid threshold?)
<img width="457" alt="screen shot 2017-04-27 at 19 42 28" src="https://cloud.githubusercontent.com/assets/4493366/25496557/aa1bf9be-2b81-11e7-9065-306765f62b82.png">

<img width="495" alt="screen shot 2017-04-27 at 19 40 16" src="https://cloud.githubusercontent.com/assets/4493366/25496516/8b56a808-2b81-11e7-84a7-d3aec1db879e.png">

**Comment by emanuele-f** [comment]
Fixed with f76b872a2d6a64cf938f4673402b7776d6384c27
