### ISSUE TITLE
Process dies with SSL

### ISSUE THREAD

**Issue by antoniovalenzuela** [ntop/ntopng#1196]
S.O.: Debian Raspbian 8 Jessie (armv71)

/usr/local/bin/
libssl.so -> /usr/lib/arm-linux-gnueabihf/libssl.so

config
-G=/var/run/ntopng.pid 
-w=8090
-W=8091
-i=eth0

TCP 8091 it's available

Without SSL only (TCP 8090) works for a few minutes and then dies. (interface eth0)

[Log.docx](https://github.com/ntop/ntopng/files/962566/Log.docx)

Licensed product

**Comment by simonemainardi** [comment]
rpi package was not build with ssl support. @lucaderi can you please trigger a rebuild? I have installed missing dependency `libssl-dev`. Thank you.

With the new package, you won't need to symlink libssl.so

**Comment by antoniovalenzuela** [comment]
Great!!! SSL operating.



Thank you for the quick response.



You can close the issue.


Atte. Antonio










---- On lun, 01 may 2017 07:30:48 -0300 simonemainardi &lt;notifications@github.com&gt; wrote ----




rpi package was not build with ssl support. @lucaderi can you please trigger a rebuild? I have installed missing dependency libssl-dev. Thank you.

With the new package, you won't need to symlink libssl.so

**Comment by simonemainardi** [comment]
thanks!
