### ISSUE TITLE
IOPS/Hardware requirement for 240G MySQL history database

### ISSUE THREAD

**Issue by swissiws** [ntop/ntopng#1198]
Hi
i have a data growth of 120G per month with required history to keep over 2 month.

Are two SSD drives mirrored enough for queries over such data volume? Would I be better off with SAS 15k spindle array of 12?

many thanks

**Comment by simonemainardi** [comment]
@570 bytes per flow in MySQL we can estimate an approximate of 0.5B flows over 2 months. Depending on the queries you will have to perform, performance can drop significantly. Will you query the database using the professional version historical data explorer?

**Comment by swissiws** [comment]
Professional at least, likely Enterprise when available.

Queries are usually based on single host IP address over a time frame of up to 30 days - required results include total MB for specific flows and talkers during time frame specified.

thanks.

**Comment by simonemainardi** [comment]
Restricting using host IP address is good and beneficial for the performances. We are also working on flows data preprocessing to speed up query time even further. Please stay tuned.

I think you would experience better performances with a raid array of 12 15k disks. However, you should also keep into account the cost that would be much much higher, if compared to the cost of two ssds.

**Comment by simonemainardi** [comment]
@swissiws did you try with the SSDs? Can you comment on the performances?

**Comment by lucaderi** [comment]
Closed for inactivity. Will reopen if necessary.
