### ISSUE TITLE
Can't add multiple black listed protocols

### ISSUE THREAD

**Issue by whoknowz** [ntop/ntopng#120]
When adding multiple protocols to the blacklist and setting protocol policy, the page refreshes and show only a single protocol in the black list. Filtering does however works for that single protocol.
Completely fresh install doesn't help either.

2.0.150810 - Professional Edition

![before](https://cloud.githubusercontent.com/assets/7417874/9162149/fc4ca04c-3f5d-11e5-8dda-40e3aa920a9e.JPG)
![after](https://cloud.githubusercontent.com/assets/7417874/9162150/fc50bf6a-3f5d-11e5-9cf8-7bbb21b075b5.jpg)

**Comment by lucaderi** [comment]
The fix was due to a bug on e function that we introduced recently to cleanup HTTP parameters. I have also added a small page fix.
