### ISSUE TITLE
View pages visited by a host 

### ISSUE THREAD

**Issue by rubencitroxs** [ntop/ntopng#1202]
How can I view pages visited by a host?
example
![image](https://cloud.githubusercontent.com/assets/27857718/25542459/1a5fbd08-2c29-11e7-84f9-0be11e3fefd0.png)

My ntop does not show me that information.

**Comment by emanuele-f** [comment]
What ntopng version are you using? Are capturing from a local interface or from a remote probe?

**Comment by lucaderi** [comment]
If you enable DB/ELK dump (-F) you can see historical activities

**Comment by rubencitroxs** [comment]
Emanuele;

The version of ntopng and nprobe is:
-ntopng x86_64 v.2.5.170330
-nProbe v.7.5.170330

I am capturing locally


Getting Started:

Ntopng -i tcp: //127.0.0.1: 1236 -m "192.168.0.0/24,192.168.1.0/24,192.168.4.0/24" -w 3000 --online-license-check

Nprobe -i none -n none -3 2055 --zmq tcp: //127.0.0.1: 1236

**Comment by rubencitroxs** [comment]
Luca
Where is it enabled?

**Comment by simonemainardi** [comment]
@rubencitroxs please, enable MySQL export with option -F and you will have the history

**Comment by rubencitroxs** [comment]
NTOP -F or NPROBE -F ?

**Comment by rubencitroxs** [comment]
Thank you.

Now save the history, and mysql works fine.

However does not show me the URLs visited by the hosts

![image](https://cloud.githubusercontent.com/assets/27857718/25632763/4575605e-2f4b-11e7-8f03-2daa50e4dc55.png)

**Comment by simonemainardi** [comment]
@rubencitroxs, as you are using ntopng along with nProbe, you must ensure the following:
- nProbe is monitoring a physical interface;
- nProbe DNS plugin is enabled and the following fields are exported:
```
Plugin DNS/LLMNR Protocol templates:
[NFv9 57677][IPFIX 35632.205] %DNS_QUERY                        DNS query
[NFv9 57678][IPFIX 35632.206] %DNS_QUERY_ID                     DNS query transaction Id
[NFv9 57679][IPFIX 35632.207] %DNS_QUERY_TYPE                   DNS query type (e.g. 1=A, 2=NS..)
[NFv9 57680][IPFIX 35632.208] %DNS_RET_CODE                     DNS return code (e.g. 0=no error)
[NFv9 57681][IPFIX 35632.209] %DNS_NUM_ANSWERS                  DNS # of returned answers
[NFv9 57824][IPFIX 35632.352] %DNS_TTL_ANSWER                   TTL of the first A record (if any)
[NFv9 57870][IPFIX 35632.398] %DNS_RESPONSE                     DNS response(s)
```

With the setup above, you will find the details in the flow JSON.

If you want the info column to be populated natively by ntopng, then you have to monitor a physical interface with ntopng directly without nprobe.

**Comment by rubencitroxs** [comment]
Perfect, thanks.

Is it possible to get a demo of "DNS plugins"?

**Comment by simonemainardi** [comment]
Sure, please contact our team using the web form and request for that.
