### ISSUE TITLE
YUM error while trying to update "pfing" on centos 7.3.1611

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#1205]
Hello.

Running "yum update" on centos 7 and getting the error below. Just happened like yesterday. Any suggestions or what am I doing wrong? Thank you.

Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.keystealth.org
 * epel: mirror.hmc.edu
 * extras: repos-tx.psychz.net
 * updates: mirror.scalabledns.com
Resolving Dependencies
--> Running transaction check
---> Package pfring.x86_64 0:6.6.0-1201 will be updated
--> Processing Dependency: pfring = 6.6.0-1201 for package: ntopng-2.4.170428-1311.x86_64
--> Processing Dependency: pfring = 6.6.0-1201 for package: n2disk-2.8.170428-4800.x86_64
--> Processing Dependency: pfring = 6.6.0-1201 for package: cento-1.2.170428-93.x86_64
--> Processing Dependency: pfring = 6.6.0-1201 for package: nprobe-7.4.170428-5335.x86_64
---> Package pfring.x86_64 0:6.6.0-1204 will be an update
---> Package pfring-dkms.noarch 0:6.6.0-1201 will be updated
---> Package pfring-dkms.noarch 0:6.6.0-1204 will be an update
--> Finished Dependency Resolution
Error: Package: ntopng-2.4.170428-1311.x86_64 (@ntop)
           Requires: pfring = 6.6.0-1201
           Removing: pfring-6.6.0-1201.x86_64 (@ntop)
               pfring = 6.6.0-1201
           Updated By: pfring-6.6.0-1204.x86_64 (ntop)
               pfring = 6.6.0-1204
Error: Package: n2disk-2.8.170428-4800.x86_64 (@ntop)
           Requires: pfring = 6.6.0-1201
           Removing: pfring-6.6.0-1201.x86_64 (@ntop)
               pfring = 6.6.0-1201
           Updated By: pfring-6.6.0-1204.x86_64 (ntop)
               pfring = 6.6.0-1204
Error: Package: nprobe-7.4.170428-5335.x86_64 (@ntop)
           Requires: pfring = 6.6.0-1201
           Removing: pfring-6.6.0-1201.x86_64 (@ntop)
               pfring = 6.6.0-1201
           Updated By: pfring-6.6.0-1204.x86_64 (ntop)
               pfring = 6.6.0-1204
Error: Package: cento-1.2.170428-93.x86_64 (@ntop)
           Requires: pfring = 6.6.0-1201
           Removing: pfring-6.6.0-1201.x86_64 (@ntop)
               pfring = 6.6.0-1201
           Updated By: pfring-6.6.0-1204.x86_64 (ntop)
               pfring = 6.6.0-1204
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by emanuele-f** [comment]
Please open an issue on https://github.com/ntop/PF_RING
