### ISSUE TITLE
Ease Host Pool Assignment

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1207]
In the host detail, it would be nice to add a mechanism to add a host to a pool. Clicking on the pool URL shows hosts belonging to the pool but the process of adding it to the pool is manual. A + or anything similar that can do the job would be great to have

![screen shot 2017-05-01 at 15 06 21](https://cloud.githubusercontent.com/assets/4493366/25580265/c3f7dffa-2e7f-11e7-8df3-d8c1d0b7a2e2.png)

**Comment by emanuele-f** [comment]
The host pool can be configured from the "cog" icon into the host detail page

**Comment by simonemainardi** [comment]
please, add a link to the host details configuration page next to the host pool name

**Comment by emanuele-f** [comment]
Implemented in ba8d992e3babcf3f3f9ee0c174cc34bc0d857655
