### ISSUE TITLE
Awesome font issue with Chrome: Version 45.0.2454.26 beta (64-bit)

### ISSUE THREAD

**Issue by rwhalb** [ntop/ntopng#121]
Having errors with the Awesome fonts:

From inspect element on chrome:
 
Failed to decode downloaded font: https://10.222.222.24:3001/font-awesome/fonts/fontawesome-webfont.woff2?v=4.4.0
 
jquery.js:10098
 
OTS parsing error: invalid version tag

**Comment by lucaderi** [comment]
I have tested the issue and verified the mime types for these fonts

  {".woff", 5, "application/font-woff"},
  {".woff2", 6, "application/font-woff2"},
  {".ttf", 4, "application/x-font-ttf"},

and they are correct according to the specs. Everything works well with safari ( 8.0.7 (10600.7.12)) and Firefox (39.0.3).

I believe ntopng is doing what is supposed to do, and verified that the font transfer via HTTP and the file on disk are the same (in binary I mean). So I think there is an issue with Chrome, but I can't say more than this as I have no clue what the problem could be.

**Comment by baddogdown** [comment]
+1 on this error.  Chrome reports a 401 Unauthorised when jquery made a call for access to Awesome fonts when going to the URL direct works fine.    Only a problem since this version of ChromeOS.  On one occasion the Developer Tools gave me a weird message saying something like >> either Unauthorised *or* a resource problem in accessing files. << which implied a local resource limitation being miss reported as a security issue.

**Comment by rwhalb** [comment]
Upgrade Chrome to Beta version: 45.0.2454.37 beta (64-bit) and ntopng with latest GIT as of 08_13_2015.

This issue does not occur now. Mostly based on the comments above that this was an issue resolved by Google with Beta version: 45.0.2454.26 beta (64-bit).

Closing issue...

**Comment by IdahoEv** [comment]
I am having this problem in version 45.0.2454.85 (64-bit)

**Comment by bduff9** [comment]
Same here, just noticed.  Running Version 45.0.2454.85 m, says:

Failed to decode downloaded font: http://......./fonts/fontawesome-webfont.woff2?v=4.4.0
OTS parsing error: invalid version tag

**Comment by lucaderi** [comment]
Update chrome and the problem will be solved. On my Version 46.0.2490.22 beta (64-bit) all works

**Comment by Steelcrusher** [comment]
Still having it on 46.0.2490.33 beta-m (64-bit)
Failed to decode downloaded font: http://...../fonts/font-awesome/fontawesome-webfont.woff2?v=4.3.0
OTS parsing error: invalid version tag

**Comment by IdahoEv** [comment]
For me, chrome claims it is "up to date" with 45.0.2454.85, so I can't update to 46.  (Maybe 46 not released for mac yet?)

But, i'm also getting a similar error with Firefox. The error message is different, but it is still refusing to load & parse the font.

**Comment by lucaderi** [comment]
Please contact the font awesome people for assistance.

**Comment by Steelcrusher** [comment]
To get version 46 you need to download the beta version of chrome.

**Comment by flyswatter** [comment]
I'm having this problem on Chrome 46, I didn't get my font from fontawesome, have tried a few different fonts, run them through a couple different converters, same error.

**Comment by AndrewBogdanovTSS** [comment]
I also have this error on Chrome 46. When I test my site locally I don't get this error, only when I deploy online.

**Comment by gomidefabio** [comment]
I also have this error on Chrome 46.0.2490.71.

**Comment by ciclopes** [comment]
I'm still having this issue on Chrome 46.0.2490.80. =(

**Comment by IdahoEv** [comment]
In case this helps anyone else:  I get this error when the URL to the font file is wrong and the font isn't loading at all.  "Failed to decode" is very misleading for "couldn't load the file", but that's what was happening for me.

**Comment by DennisRoam** [comment]
+1 on the font being missing causing this error.

**Comment by lucaderi** [comment]
Ok guys but IMHO this is not an ntopng issue but rather a Chrome+FontAwesome issue. Please contact their developers and let me know if I need to do something on the ntopng side

**Comment by gomidefabio** [comment]
I don't know if it will help anyone, but I saw something similar happening because the local server had it's mod_rewrite set for SPA Routes, driving the access to index.html. It had exceptions for images, so the images were loading well. But it was lacking the exceptions for fonts. In that way, all the attempts to get fonts were failing, and it was giving the exact same error message referred in the opening post of this page. The local server was tying to serve the index.html in place of the font, and therefore providing the wrong header. So by adding exceptions for ttf, woff, etc... to the mod-rewrite or htaccess you might be able to fix that.

**Comment by macgyver76** [comment]
Hi all. For me it was just an absence of .woff2 file in project directory.

**Comment by mmclau14** [comment]
I'm actually getting this on a base 64 font that's in my stylesheet. anyone know what could be causing that?

**Comment by danielbonnell** [comment]
I had this same problem using `v4.3.0` of  `font-awesome.min.css` served from MaxCDN. Turns out that the format for the EOT version of the file wasn't specified. I added ` format('embedded-opentype')` and the problem went away.

**Comment by lucaderi** [comment]
Hi all, can you please check (and report) if https://github.com/ntop/ntopng/commit/c94c3f53329ee2b40dd4133eae1152d8f108b2c8 fixes all your problems?

**Comment by danielbonnell** [comment]
I should have specified, but my issue wasn't related to ntopng in any way. Just thought it might help someone else with the same issue.

**Comment by Mahmoudz** [comment]
I faced the same problem and it took me some time to find out that I was missing to transfer the `.woff2` file in my gulp task.

``` js
gulp.task('fontawesome', function () {
    return gulp.src('bower_components/font-awesome/fonts/*.{eot,svg,ttf,woff,woff2}')
        .pipe(gulp.dest(paths.public + '/fonts/'));
});
```

**Comment by buitregool** [comment]
If your are using Chrome, try adding the opentype (OTF) url of the font to **font-awesome.min.css** as shown below:

`url('../fonts/FontAwesome.otf?v=4.3.0') format('opentype'),`

Cheers!
