### ISSUE TITLE
Parameter validation error

### ISSUE THREAD

**Issue by PSmolders** [ntop/ntopng#1211]
Using ntopng 2.5.170503 on Ubuntu Server 16.04.2

When I try to change the Local Host Idle Timeout parameter in the Preferences menu and click apply, the page returns HTTP error 500. The log shows me this error:
```[Lua.cpp:6503] WARNING: Script failure [/usr/share/ntopng/scripts/lua/admin/prefs.lua][/usr/share/ntopng/scripts/lua/modules/http_lint.lua:952: [LINT] _POST["opt_resbt_m_options_group_4"] = "10" parameter error: Missing validation```

So far I haven't noticed errors on applying any other settings.

**Comment by emanuele-f** [comment]
What browser are you using? If you open the browser inspector, do you see any javascript errors?

**Comment by PSmolders** [comment]
Internet Explorer 11 just fails with HTTP 500 and the parameter validation error in the log. Firefox 53 does change the value without errors, but gives a warning in the developer console that the input character set of the form is in Windows-1252 and not UTF-8, which might cause input character loss according to the message.

I would attach the message, but it is in Dutch, not English.

**Comment by emanuele-f** [comment]
That's enough information, I will investigate with the IE browser, thank you

**Comment by emanuele-f** [comment]
This should be fixed with 21171bbd73a9ad1c7becd6232d7a2f020d7a1523. Please reopen if necessary.

Note: the new ntopng package will be available tomorrow
