### ISSUE TITLE
Add IP ranges to Host Pool

### ISSUE THREAD

**Issue by rkriekaard** [ntop/ntopng#1212]
Hi,

It would be nice to define an IP range to add to a Host Pool, for instance the DHCP pool range for client computers. Or is this possible in another way?

**Comment by emanuele-f** [comment]
Hi, this is already possible. You can add a network cidr into the host pools

![screenshot at 2017-05-03 14-38-55](https://cloud.githubusercontent.com/assets/5488003/25660837/55d35d02-300e-11e7-8ffb-651165985faf.png)

**Comment by rkriekaard** [comment]
Hi,

No, I don’t mean an entire subnet, but a range. In this particular situation we have a subnet 172.16.40.0/24 and a DHCP scope of 172.16.40.60-230. This scope is the one I would like to add as a host pool.

Met vriendelijke groet/Kind regards,

Rob Kriekaard
KBS Bedrijfsondersteuning
E: rob@kbsnl.com<mailto:rob@kbsnl.com>
T: 085 – 0491 441
M: 06 – 434 48 443

Bezoek onze website op http://www.kbsnl.com<http://www.kbsnl.com/>

**Comment by emanuele-f** [comment]
You should configure those ranges via network cidr, please see this link https://en.wikipedia.org/wiki/IPv4_subnetting_reference for more information

**Comment by rkriekaard** [comment]
Emanuele,

Given the scope I mentioned, you cannot use cidr to capture that.

I guess your answer is that it is not possible...

Met vriendelijke groet / Kind regards,

Rob Kriekaard
KBS Bedrijfsondersteuning
E: rob@kbsnl.com<mailto:rob@kbsnl.com>
T: 085 - 0491 441
M: 06 434 48 443

Bezoek onze website op http://www.kbsnl.com

Op 3 mei 2017 om 14:48 heeft Emanuele Faranda <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


You should configure those ranges via network cidr, please see this link https://en.wikipedia.org/wiki/IPv4_subnetting_reference for more information

**Comment by simonemainardi** [comment]
@rkriekaard you can either:
- build a subnet out of your subnet by specifying a longer bitmask, e.g., a /25, /26 /30...
- indicate every single host in the host pool
