### ISSUE TITLE
IPv6 flow data

### ISSUE THREAD

**Issue by s2105** [ntop/ntopng#1213]
Hello,

We are using nprobe (7.4.170426 ) ntopng 2.4.170 for our flow data. We would like to know how to view IPv6 flow data. 

Thanks,
Samir

**Comment by emanuele-f** [comment]
Hi Samir, versions 2.4 version of ntopng and 7.4 of nProbe will be replaced soon by the next stable releases, so I suggest you to migrate to the latest version of these software to get full IPv6 support.

The following fields can be added to the nProbe template to make it send those data to ntopng.

```
$ nprobe -h | grep IPV6_
[ 27] %IPV6_SRC_ADDR              %sourceIPv6Address        	IPv6 source address
[ 28] %IPV6_DST_ADDR              %destinationIPv6Address   	IPv6 destination address
[ 29] %IPV6_SRC_MASK              %sourceIPv6PrefixLength   	IPv6 source mask
[ 30] %IPV6_DST_MASK              %destinationIPv6PrefixLength	IPv6 destination mask
...
```

**Comment by s2105** [comment]
Thank you
