### ISSUE TITLE
nTopNG - View ports historically

### ISSUE THREAD

**Issue by juesor** [ntop/ntopng#1215]
There are a few reports we can get out of the fluke netflow that I’m not able to figure out how to do in nTopNG. 

A common report we run is something like, which ports were used against this IP during this time. Is it possible to have that information, and have it historically as well?

**Comment by emanuele-f** [comment]
Hi, if you open an host page and go to the "ports" tab, you will see the ports he has contacted as a client and the ports he has been contacted as a server.

The historical representation of this is not currently available. Please open a separate feature request for this.

![screenshot at 2017-05-05 10-57-52](https://cloud.githubusercontent.com/assets/5488003/25739336/cf6fa976-3181-11e7-9446-38e83bd7c8b7.png)
