### ISSUE TITLE
How can i get MAC address of computer that i want to oversee?

### ISSUE THREAD

**Issue by nguyenvanthien123** [ntop/ntopng#1216]
Hi,
I am using ntopng system. But it is not MAC address information. Now I want to get MAC address of the computer that it was oversee. How do i do?
(I want to get MAC address field in mysql database. How can i do?)
Thank alot!

**Comment by simonemainardi** [comment]
use nprobe in combination with ntopng, make sure to specify an nprobe template that contains source and destination macs, and you will have those exported in database column JSON.

Template fields you have to add are:
[ 56] %IN_SRC_MAC                 %sourceMacAddress             Source MAC Address
[ 80] %OUT_DST_MAC                %destinationMacAddress        Destination MAC Address

So an example to recap:
./nprobe -T "... %IN_SRC_MAC  %OUT_DST_MAC ..... " -i eth0 -n none --zmq tcp://*:5556
./ntopng -i tcp://127.0.0.1:5556 -F "mysql;...."
