### ISSUE TITLE
nProbe mysql-community-libs dependency?

### ISSUE THREAD

**Issue by hgpit** [ntop/ntopng#1219]
Hi,

I have been testing/trialling ntopng for a couple of weeks now, and running "yum update" most days to get the latest releases from the nightly repo.

Today, I have tried to run the update and nprobe-7.5.170505-5749.x86_64 is complaining that it " Requires: mysql-community-libs >= 5.6".
Is this right? I am running this on CentOS7, which uses MariaDB by default. I don't really want to add another repo and install mysql packages unless totally necessary.

Thank you

**Comment by lucaderi** [comment]
Fixed in the current build.
