### ISSUE TITLE
NtopNG configure error

### ISSUE THREAD

**Issue by ssirag** [ntop/ntopng#1229]
I'm having a "Please install libcurl(-dev) (http://curl.haxx.se/)" issue when running the ./configure script for NtopNG install.

I'm running Ubuntu 16.04 and cloned the https://github.com/ntop/ntopng.git repo twice to fix it.

Versions:
Curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Libcurl3 version 7.47.0-1ubuntu2.2

**Comment by simonemainardi** [comment]
so are you still getting the error or it is fixed?

**Comment by emanuele-f** [comment]
@ssirag are you trying to compile 2.4 stable version or 2.5?

**Comment by ssirag** [comment]
@simonemainardi still the error
@emanuele-f I'm not sure how to tell which version is compiling...it's the latest code pulled from this repo.

**Comment by emanuele-f** [comment]
Do you have PF_RING installed system-wide? Can you post your config.log?

**Comment by ssirag** [comment]
Yes, I have PF_RING installed... config log attached...

[config.log.txt](https://github.com/ntop/ntopng/files/996949/config.log.txt)

**Comment by emanuele-f** [comment]
Probably you are missing the `libcurl-devel` dependency. Please install ti with `sudo yum install libcurl-devel`

**Comment by ssirag** [comment]
I'm on Ubuntu...not seeing any packages corresponding to libcurl-devel.

There are a few with libcurl in the name, but it's not clear if any of these would help...

http://packages.ubuntu.com/search?keywords=libcurl&searchon=names&suite=yakkety&section=all

**Comment by emanuele-f** [comment]
Oh sorry, I confused it with Centos. On ubuntu the package is `libcurl4-openssl-dev`.
See https://github.com/ntop/ntopng/blob/dev/doc/README.compilation for detailed dependency information.

**Comment by ssirag** [comment]
That was it...thanks...
