### ISSUE TITLE
New to ntopng. Geo not working

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#1231]
Entered my API key. Geo still not working. Issue seems to be:

[Deprecation] getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
initialize @ googleMapJson.js:119

Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required
uB.j @ maps.googleapis.com/maps-api-v3/api/js/28/18/util.js:215

Any ideas?

**Comment by simonemainardi** [comment]
just tried to reproduce with no luck. I get the warning but the geolocation works. Browser used? Can you try and start ntopng over HTTPS? (see option -W)

**Comment by ghost** [comment]
Hmmm, i think ntopng daemon doesn't pick up my config file..... I changed the config file and still i don't get https.

```
--pid=/var/tmp/ntopng.pid
--disable-login=
--dns-mode=1
--max-num-flows=2000
--max-num-hosts=2500
--sticky-hosts=none
--community=
--interface=wlan0
--https-port=
```

**Comment by simonemainardi** [comment]
you didn't specify any https port: try with

`--https-port=3001`

**Comment by ghost** [comment]
Did it. But i think it's not picking up the config file. I also have disable login in there and i still need to login. That's how i see that it's not picking up the config.

**Comment by ghost** [comment]
Interface still running on port 3000.

But I have more issues:

On accessing the web interface the first time i get:
```
HTTP/1.1 500 Internal server error Content-Type: text/html Connection: close   Script "/usr/share/ntopng/scripts/lua/index.lua" returned an error:
/usr/share/ntopng/scripts/lua/index.lua:42: attempt to concatenate global 'ifname' (a nil value)
```
That goes away and never comes back, so it's not an issue for me.

Also on the console i get:
`Cannot change tcp-segmentation-offload`
Don't know what to do with that either.

**Comment by emanuele-f** [comment]
The TCP segmentation offload is not a problem.
How do you configure ntopng, via command line options or via `/etc/ntopng/ntopng.conf` ? Can you post the configuration used?

**Comment by ghost** [comment]
Again, i get the feeling that my config file is not picked up. I am still running on port 3000 when my config tells me 3001.

```
-G=/var/tmp/ntopng.pid
-l=1
-n=1
-X=2000
-x=2500
-S=none
-i=wlan0
-W=:3001
-e=
```

**Comment by simonemainardi** [comment]
do you restart ntopng after changing its configuration file?

**Comment by ghost** [comment]
Yes.

**Comment by emanuele-f** [comment]
Have you followed the steps to enable HTTPS outlined in https://github.com/ntop/ntopng/blob/dev/doc/README.SSL ?

Note: when ntopng fails to start HTTPS, a message similar to this will appear in the log: `15/May/2017 09:53:12 [HTTPserver.cpp:748] HTTPS Disabled: missing SSL certificate /home/emanuele/src/ntopng/httpdocs/ssl/ntopng-cert.pem`

**Comment by ghost** [comment]
Yes.

**Comment by ghost** [comment]
This one is resolved. Was a browser issue together with SSL issue.
