### ISSUE TITLE
Feature Request - Historical representation of port usage based on IP.

### ISSUE THREAD

**Issue by juesor** [ntop/ntopng#1233]
There are a few reports we can get out of the fluke netflow that I’m not able to figure out how to do in nTopNG.

A common report we run is something like, which ports were used against this IP during this time. Is it possible to have that information, and have it historically as well?

Above is from one of my Network Admins that want to utilize nTopNG instead of Fluke Netflow.

Issue #1215 was opened and it was requested to enter a feature request

**Comment by simonemainardi** [comment]
Did you consider using the ntopng Historical Data Explorer? You can use the search box to specify a given IP address and also choose the port #.

**Comment by juesor** [comment]
Where is that ???  I don't see the graphs at all times.

**Comment by simonemainardi** [comment]
@juesor they are available in the professional version when mysql data export is enabled

**Comment by juesor** [comment]
ntopng Pro [Small Business Edition] v.3.0.170612

Apparently i don't pay attention enough.

If i go to GEAR > Preferences > Data Retention

I do not see mysql setup.

**Comment by emanuele-f** [comment]
Hi @juesor, mysql export must be configured from command line parameters (or ntopng configuration file) using the `-F` option. Please see this link for more details http://www.ntop.org/ntopng/exploring-historical-data-using-ntopng/

**Comment by simonemainardi** [comment]
Feature is available with the historical data explorer:

![image](https://user-images.githubusercontent.com/3397663/30317101-6e68b6fc-97a9-11e7-9661-c1a8793da0d0.png)

You can also go beyond simple ports and explore the actual application protocols. In other words you can get 'which protocols are used against this ip during this time'

![image](https://user-images.githubusercontent.com/3397663/30317174-a391e556-97a9-11e7-9287-a2fe6c143dfc.png)
