### ISSUE TITLE
ZeroMQ logo/URL shows as a square

### ISSUE THREAD

**Issue by PSmolders** [ntop/ntopng#1235]
Using ntopng 2.5.170515 on Ubuntu 16.04.2

When using Internet Explorer 11, on the About ntopng page, the ZeroMQ entry shows the first character of ZeroMQ as a square. 
![knipsel](https://cloud.githubusercontent.com/assets/8997593/26048274/c02b8688-3956-11e7-83c3-46f116d2fa61.PNG)

Firefox 53 shows a question mark.
![knipsel2](https://cloud.githubusercontent.com/assets/8997593/26048316/e6db0c72-3956-11e7-893a-f356999c5bef.PNG)

While not a big issue, I just wanted to let you know.

**Comment by emanuele-f** [comment]
Fixed with ec77102b52a013ff2b3aaed1fa4db91391b6be09 . Thank you!
