### ISSUE TITLE
Lua.cpp 6531 

### ISSUE THREAD

**Issue by lawrencecare2** [ntop/ntopng#1237]
Hi,

Ntopng v.2.5.170515
CentOS Linux release 7.3.1611 (Core)

          Seeing the errors below when accessing ntopng admin page and in logs. Clicking the preferences page will also break access until ntopng is restarted.

HTTP/1.1 500 Internal server error Content-Type: text/html Connection: close   Script "/usr/share/ntopng/scripts/lua/index.lua" returned an error:
/usr/share/ntopng/scripts/lua/index.lua:42: attempt to concatenate global 'ifname' (a nil value)

ntopng: [Lua.cpp:6531] WARNING: Script failure [/usr/share/ntopng/scripts/lua/index.lua][/usr/share/ntopng/scripts/lua/index.lua:42: attempt to concatenate global 'ifname' (a nil value)]

Ntopng v.2.5.170515
CentOS Linux release 7.3.1611 (Core)

**Comment by simonemainardi** [comment]
This can happen if you have a browser tab open on a given interface, and then you restart ntopng without that interface. The browser will keep issuing requests for the interface but actually ntopng no longer has it in memory and thus notifies with an error.

Can you please confirm?

**Comment by lawrencecare2** [comment]
Thank you. I've exited my browsers and restarted ntopng. The errors are no
longer showing.
