### ISSUE TITLE
Outdated javascript libraries

### ISSUE THREAD

**Issue by blackwat3r88** [ntop/ntopng#1238]
Hi,

into the project are used two js libraries with known vulnerabilities. 

- jQuery1.11.1 (ntopng/httpdocs/js/jquery.js), affected by XSS, more info at https://nodesecurity.io/advisories/127
- moment.js (ntopng/httpdocs/js/moment.js) affected by a possible dos with a regex value, more info at https://github.com/moment/moment/issues/2936.
Please update this two libraries.

Thanks.

**Comment by simonemainardi** [comment]
fixed in 89df67d6977725e0486aa0fecb04d8f93eec5ed3
