### ISSUE TITLE
Unexpected message when alerts config was disabled

### ISSUE THREAD

**Issue by TakayukiOnodera** [ntop/ntopng#1239]
It's a minor problem. An unexpected error message is displayed on show_alerts.lua when alerts config was disabled on preferences.

![disabled_alerts_at_pref](https://cloud.githubusercontent.com/assets/27996188/26090832/55f37964-3a42-11e7-8a5c-74db0e5d3033.png)

**Comment by emanuele-f** [comment]
Thank you for reporting
