### ISSUE TITLE
Traffic shaping not enforced

### ISSUE THREAD

**Issue by whoknowz** [ntop/ntopng#124]
Ingress and Egress shaping doesn't have any effect, starving networks with lesser hosts.
![capture1](https://cloud.githubusercontent.com/assets/7417874/9224621/5140ab6e-411d-11e5-87aa-3d6fa9d2165a.JPG)
![capture2](https://cloud.githubusercontent.com/assets/7417874/9224620/5140716c-411d-11e5-9a89-6b07747c46b6.JPG)

**Comment by lucaderi** [comment]
@whoknowz Can you please add the networks you are shaping to the list of local networks (using -m)? This is required to enable shaping for non-local networks. We'll add a fix for this too.

**Comment by lucaderi** [comment]
@whoknowz At the moment in ntopng we enforce traffic only per host (not per network) so we need some coding on our side to enable this feature.

**Comment by whoknowz** [comment]
the local networks are already added via -m in the config. as you said network level is missing and the interface doesn't stop me from applying it. will wait for the enhancement.
