### ISSUE TITLE
Enormous number of repeating hosts

### ISSUE THREAD

**Issue by PSmolders** [ntop/ntopng#1241]
Using ntopng 2.5.170515 on Ubuntu 16.04.2

I noticed my hosts counter going up rather rapidly over the course of this morning. Checking the networks page showed me that there were 4200 local hosts. Considering we only have about 400-500 local hosts, this seemed off. Opening the page containing all local hosts and scrolling through the pages to the end show all normal local hosts first, as is to be expected. But after scrolling past the last local host (192.168.90.250 in our case) gives me the following on screen:

![knipsel2](https://cloud.githubusercontent.com/assets/8997593/26097236/314a7ad6-3a24-11e7-9f5d-be3756904db5.PNG)

All pages after that last host show exactly the same screen. Just a single host with the counters at the bottom of the page stating there are over 200 on that page (which there aren't) and a lot of pages.

The log shows no error.

**Comment by simonemainardi** [comment]
@PSmolders do you have the same IP address seen multiple MAC addresses (e.g., due to a load balancer)?

**Comment by PSmolders** [comment]
No, everything was working fine without any changes to our physical setup. I will try to update today and report.

**Comment by PSmolders** [comment]
I can no longer reproduce the issue in the first post. I did find however that the total number of hosts displayed at the bottom of the page does not correspond to the total hosts reported by the Hosts -> Networks page.

Example: the networks page shows me 824 local hosts and 899 remote hosts. The hosts counter at the bottom of the page shows me 3133 total hosts. 

It seems the total hosts counter is not decremented for hosts which have timed out, but only incremented, leading to a false number, while the Hosts -> Networks page shows the right number.

This happens on both regular and view interfaces.

**Comment by emanuele-f** [comment]
With the latest changes, a new host will be created for each different MAC address. The old behaviour was to create a new host for each different IP address.
The number you see at the bottom of the page reflects the number of active hosts, which now should correspond to the total number of "Devices -> Layer 2" devices. I agree this is confusing though..
