### ISSUE TITLE
"column_thpt" always shows "0 pps " when reading from .pcap file

### ISSUE THREAD

**Issue by delgadod** [ntop/ntopng#1243]
Hello,

I am using ntopng to translate many .pcap files into Netflow.
The program works great at parsing many large .pcap files quickly.

However I have found that I need to track number of packets exchanged per flow.
Normal exporting always shows 0 pps as throughput, which makes some sense as it's being read from a file instead of live from a network.

Is it possible to have total packets exchanged be shown in the exported .json file?
Or possible to have throughput be correctly read from a file?

**Comment by simonemainardi** [comment]
Total throughput is zero when reading from a pcap file and this is normal as a pcap is always replayed at the maximum speed.

If you want to see the number of packets exchanged on a give flow, you just have to visit the flows detail page (click on the Info badge) from the flows list

**Comment by delgadod** [comment]
Hello, thank you Simone.
I see that when selecting "export data" from the web GUI that packet number information is exported.

At the moment I am making HTTP requests using this URL: 
`http://localhost:3000/lua/get_flows_data.lua?currentPage=1&perPage=10000&sortColumn=column_&sortOrder=desc`
to automate .pcap to Netflow .json files. This method does not provide the number of packets exchanged.

I see that by selecting "export data" under the settings a much more richly detailed .json is produced.
Can I access that functionality through the ntopng CLI or an HTTP request as I have been?

**Comment by emanuele-f** [comment]
Hi, of course you can call the `http://localhost:3000/lua/do_export_data.lua` script via CLI or HTTP request and it will return json data. You can optionally pass "ip", "vlan", "ifid" parameters to restrict the search.

See `https://github.com/ntop/ntopng/tree/dev/doc` for cli curl example

Update: probably I've been too impulsive in the reply, you are interested in flows where what I've reported here is for hosts, sorry

**Comment by delgadod** [comment]
Thank you Emanuel.

This will help a lot.

**Comment by delgadod** [comment]
When calling the do_export_data.lua script there is a csrf value as in:
`http://localhost:3000/lua/do_export_data.lua?csrf=b24f49e4a65077c024d64f67bdd8d50d&hostIP=&hostVlan=`
How is this value generated by the webGUI? I cannot get results without it with HTTP request.

**Comment by emanuele-f** [comment]
The latest development (2.5) version of ntopng does not use the csrf, so please update. I've fixed that just a few days ago.

**Comment by delgadod** [comment]
I am facing [Issue 769](https://github.com/ntop/ntopng/issues/769) in the ntopng installation, but on Ubuntu 16.04

**Comment by emanuele-f** [comment]
Do you have the libcurl issue while compiling the dev version of ntopng? Can you update from our repositories http://packages.ntop.org/ ? Note: you should update to the "nightly builds" version

**Comment by delgadod** [comment]
Resolved with dev version, thanks
