### ISSUE TITLE
Recover more information when I use ntopng with nprobe

### ISSUE THREAD

**Issue by stage0144** [ntop/ntopng#1245]
Hi,

I want to know if it's possible to modificate ntopng or nprobe to display more informations (in my fact I want to display SSL version). But I have seen that Nprobe ins't totally OpenSource, so is it a problem to add informations that I want ?

**Comment by simonemainardi** [comment]
Hi @stage0144 ,

You can use all the fields you want by specifying them in nprobe template (see option -T). Every field will be displayed in the ntopng flow details page. You just have to select 
 a flow by clicking on its "Info" badge to access the corresponding flow details page.

**Comment by CountZerro** [comment]
Thank you very much, I will try that.

**Comment by stage0144** [comment]
Thank you very much, I will try that.
