### ISSUE TITLE
Error :  Unsupported publisher version when I use Ntopng like a probe 

### ISSUE THREAD

**Issue by Thorfinn3** [ntop/ntopng#1247]
Hi,

So I use one Ntopng on a Raspberry Pi like a probe (plugged on a switch) and an other Ntopng on a server to catch flow and see the trafic.
So I enter on the Raspberry PI : `ntopng -i eth0 -I "tcp://*:3456" (no problem)`
But when I launche the second Ntopng : `ntopng -i tcp://xx.xx.xx.xx:3456`

I have an error : 

> 19/May/2017 06:33:20 [Ntop.cpp:1345] Setting local networks to 127.0.0.0/8
19/May/2017 06:33:20 [Redis.cpp:109] Successfully connected to redis 127.0.0.1:6379@0
19/May/2017 06:33:20 [Ntop.cpp:1450] Registered interface tcp://10.44.5.94:3456 [id: 15]
19/May/2017 06:33:20 [main.cpp:250] PID stored in file /var/run/ntopng.pid
19/May/2017 06:33:20 [HTTPserver.cpp:748] HTTPS Disabled: missing SSL certificate /home/charles/ntopng/httpdocs/ssl/ntopng-cert.pem
19/May/2017 06:33:20 [HTTPserver.cpp:750] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
19/May/2017 06:33:20 [Utils.cpp:371] User changed to nobody
19/May/2017 06:33:20 [HTTPserver.cpp:796] Web server dirs [/home/charles/ntopng/httpdocs][/home/charles/ntopng/scripts]
19/May/2017 06:33:20 [HTTPserver.cpp:799] HTTP server listening on port(s) 3000
19/May/2017 06:33:20 [main.cpp:311] Working directory: /var/tmp/ntopng
19/May/2017 06:33:20 [main.cpp:313] Scripts/HTML pages directory: /home/charles/ntopng
19/May/2017 06:33:20 [Ntop.cpp:300] Welcome to ntopng i686 v.2.5.170519 - (C) 1998-17 ntop.org
19/May/2017 06:33:20 [Ntop.cpp:305] Built on Ubuntu 14.04.5 LTS
19/May/2017 06:33:20 [PeriodicActivities.cpp:56] Started periodic activities loop...
19/May/2017 06:33:21 [Ntop.cpp:630] Local Interface Addresses (System Host)
19/May/2017 06:33:21 [Ntop.cpp:632] Local Networks
19/May/2017 06:33:21 [AddressTree.cpp:171] [AddressTree] 127.0.0.0/8
19/May/2017 06:33:21 [NetworkInterface.cpp:2065] Started packet polling on interface tcp://10.44.5.94:3456 [id: 15]...
19/May/2017 06:33:21 [CollectorInterface.cpp:115] Collecting flows on tcp://10.44.5.94:3456
19/May/2017 06:33:21 [CollectorInterface.cpp:149] WARNING: Unsupported publisher version: your nProbe sender is outdated? [24][24]
19/May/2017 06:33:21 [CollectorInterface.cpp:149] WARNING: Unsupported publisher version: your nProbe sender is outdated? [24][24]
19/May/2017 06:33:21 [CollectorInterface.cpp:149] WARNING: Unsupported publisher version: your nProbe sender is outdated? [24][24]
19/May/2017 06:33:21 [CollectorInterface.cpp:149] WARNING: Unsupported publisher version: your nProbe sender is outdated? [24][24]
19/May/2017 06:33:21 [CollectorInterface.cpp:149] WARNING: Unsupported publisher version: your nProbe sender is outdated? [24][24]

And the error continu again and again, but I don't use nProbe and I have the latest version of Ntopng.
A you can see I want to create this type of configuration => [http://www.ntop.org/ntopng/creating-a-hierarchical-cluster-of-ntopng-instances/](url)

**Comment by emanuele-f** [comment]
This is fixed with ef10ba35406bcf8f7f6843bf4e731218d12b8b0c . Please wait the next raspberry package build.

**Comment by Thorfinn3** [comment]
It works, Thank you very much
