### ISSUE TITLE
Download Historical Data

### ISSUE THREAD

**Issue by arrmo** [ntop/ntopng#1249]
Hi,

Sorry if this is a dumb question (it likely is ... :-(), but I can't quite find the plot I'm after. I want to plot the top few IP's and their traffic for the last day (example), and the total for the subnet. I don't see this, so figure if I can download the data I can plot it myself.

Is there a way to download this data (i.e. a URL that provides the samples for the last day, as an example)?

Thanks!

**Comment by simonemainardi** [comment]
@arrmo the Professional version gives you a "Report" page that features a top talkers section with traffic for any given period of time. You should try that as it is exactly what you are looking for.

Alternatively, if you want to code your own timeseries extraction features, you can use function `rrd2json` at https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/graph_utils.lua#L1474

**Comment by arrmo** [comment]
Thanks for the quick reply! Yep, the Pro version looks to be the answer. To be completely honest though, I can't really afford it for a small home setup (so likely need to roll my own ... :-().

Will give rrd2json a try - again, thanks! Do you know of any examples showing how to use / access it? I'm new to Lua.

**Comment by simonemainardi** [comment]
the best way is to see how it is called. See for example: https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/graph_utils.lua#L665

**Comment by arrmo** [comment]
Thanks for the pointers! Hopefully just a couple dumb questions left .. ;-).

I can find the data by IP address, seems to be in (for example), /var/db/ntopng/0/rrd/192/168/2/4 ... do I have that right? I admit, for this function, not sure what to use for rrdfile (or really, for host). Any pointers you can provide would be greatly appreciated.

Thanks again!

**Comment by simonemainardi** [comment]
> I can find the data by IP address, seems to be in (for example), /var/db/ntopng/0/rrd/192/168/2/4 ... do I have that right?

yes, correct

> I admit, for this function, not sure what to use for rrdfile (or really, for host)

rrd files should do what you are looking

**Comment by arrmo** [comment]
Thanks!
