### ISSUE TITLE
Feature request: Application/Protocol level shaping

### ISSUE THREAD

**Issue by whoknowz** [ntop/ntopng#125]
Having the ability to give a upper limit of bandwidth to a certain application or protocol. Could be either entire network or specific subnet. This would allow network administrators to not block abusive traffic but rather give manageable allotments to the users and avoid throttling entire user traffic.

Specific subnet division example:
WAN connection: 20mbps symmetrical
VLAN1 Egress/Ingress limit: 7/7mbps,  YouTube: 50%, HTTP/S 30% and the rest 20% upper limits
VLAN2 Egress/Ingress limit: 3/3mbps,  YouTube: 10%, HTTP/S 40% and the rest 50% upper limits
VLAN3 Egress/Ingress limit: 10/10mbps,  YouTube: 30%, HTTP/S 30% and the rest 40% upper limits

Entire network example:
WAN connection: 20mbps/10mbps asymmetrical
Egress/Ingress limit: none, Youtube: 10%, Bittorrent: 10% download, 5% upload upper limits, Unknown: 10%, the rest for other protocols.

**Comment by whoknowz** [comment]
Ubiquiti implemented the above nicely in their firmware version 1.8.0 for EdgeMax routers, with the help of nDPI I assume..

**Comment by simonemainardi** [comment]
This is available in ntopng if started in bridge (bump-in-the-wire) mode. Please read the docs.
