### ISSUE TITLE
Building Ntopng Windows

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#1250]
Hello, after testing and building ntopng on Linux following the Netbeans guide step by step, Now I am interested in building for Windows, in order to test, debug and be able to track bugs.
So I would like to ask you the approach you use for ntopng in Windows. It is , what steps shall I follow to set up everything as I did for linux with the Netbeans guide?
Thanks in advance.

**Comment by emanuele-f** [comment]
@aflorezparra windows build is a bit tricky, we use visual studio to compile the program but the setup is not trivial and we managed to build ntopng only into a specific virtual machine, so we do not have a recipe for this.

If you manage to build on windows with a clean setup and want to share your experience and possibly provide a readme to insert into the docs, we will appreciate it. I'm closing the issue for now.

**Comment by johnjey** [comment]
Hello, I have encountered the same problem, I don't know if you solve it.

**Comment by ShanonDaniel** [comment]
Hello, johnjey!
Did you solve the problem.
I've encountered the same problem.
I don't know how to solve it.

**Comment by obirn** [comment]
Hello, I'm also trying to compile it for windows. Is there a way to cross compile it with mingw64 ?
