### ISSUE TITLE
issue regarding ntopng data visualization 

### ISSUE THREAD

**Issue by s2105** [ntop/ntopng#1253]
Hello,

We use nprobe & ntopng on same instance on openstack VM. 

We see data coming to the port 

ubuntu@ntopng:~$ sudo tcpdump -i eth0 -n udp port 6343 -T cnfp -vv
sudo: unable to resolve host ntopng
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
14:37:12.395612 IP (tos 0x0, ttl 246, id 23125, offset 0, flags [none], proto UDP (17), length 164)
    199.116.233.59.50102 > 10.2.12.18.6343: NetFlow va
14:37:13.594378 IP (tos 0x0, ttl 246, id 23446, offset 0, flags [none], proto UDP (17), length 280)
    199.116.233.59.50102 > 10.2.12.18.6343: NetFlow va
14:37:14.140209 IP (tos 0x0, ttl 246, id 2594, offset 0, flags [none], proto UDP (17), length 152)
    199.116.233.59.50102 > 10.2.12.18.6343: NetFlow va
14:37:14.140260 IP (tos 0x0, ttl 246, id 2595, offset 0, flags [none], proto UDP (17), length 152)
    199.116.233.59.50102 > 10.2.12.18.6343: NetFlow va
14:37:14.140272 IP (tos 0x0, ttl 246, id 2596, offset 0, flags [none], proto UDP (17), length 80)
    199.116.233.59.50104 > 10.2.12.18.6343: NetFlow va
14:37:14.140281 IP (tos 0x0, ttl 246, id 2597, offset 0, flags [none], proto UDP (17), length 84)
    199.116.233.59.50104 > 10.2.12.18.6343: NetFlow va
14:37:14.140287 IP (tos 0x0, ttl 246, id 2598, offset 0, flags [none], proto UDP (17), length 80)
    199.116.233.59.50104 > 10.2.12.18.6343: NetFlow va
14:37:14.140294 IP (tos 0x0, ttl 246, id 2599, offset 0, flags [none], proto UDP (17), length 84)
    199.116.233.59.50104 > 10.2.12.18.6343: NetFlow va

but we don't see via ntopng webgui.

Here is the process on our ubuntu instance:

ubuntu@ntopng:~$ ps aux | grep ntopng
nobody    1755  3.5  0.1 1266272 28340 ?       Sl   10:48   8:09 /usr/bin/ntopng /etc/ntopng/ntopng.conf
ubuntu    4054  0.0  0.0  10472   900 pts/0    S+   14:38   0:00 grep --color=auto ntopng
root      8223  0.0  0.0  68004  2204 pts/0    S    10:51   0:00 sudo ntopng -i tcp://127.0.0.1:5556 -d /var/tmp -w 3000 -v
nobody    8246  6.0  0.1 1190464 29948 pts/0   Sl   10:51  13:50 ntopng -i tcp://127.0.0.1:5556 -d /var/tmp -w 3000 -v
ubuntu@ntopng:~$ ps aux | grep nprobe
ubuntu    4109  0.0  0.0  10472   904 pts/0    S+   14:38   0:00 grep --color=auto nprobe
root      7928  0.0  0.0  68004  2204 pts/0    S    10:51   0:00 sudo nprobe --collector-port 6343 --zmq tcp://127.0.0.1:5556
root      7929  0.0  0.0 422412 11236 pts/0    Sl   10:51   0:07 nprobe --collector-port 6343 --zmq tcp://127.0.0.1:5556

**Comment by emanuele-f** [comment]
Hi, you should append "c" to the ntopng interface name to use it as a collector e.g `sudo ntopng -i "tcp://127.0.0.1:5556c" -d /var/tmp -w 3000`

See http://www.ntop.org/nprobe/advanced-flow-collection-with-ntopng-and-nprobe/ for more details (you are using push mode)

**Comment by simonemainardi** [comment]
- make sure a firewall is not dropping the incoming Netflow traffic. In that case you will see it with tcpdump but nProbe won't get it.

- add options -i=none and -n=none to the nProbe

- run nprobe with verbose option -b=2 and ntopng with -v=5. Messages printed on the console will tell you if flows are correctly received from both ntopng and nprobe

**Comment by s2105** [comment]
Hello,

Thanks for your reply. With this two command it was working perfactly fine.

ubuntu@ntopng:~$ sudo nprobe --collector-port 6343 --zmq tcp://
127.0.0.1:5556 >> /dev/null &

ubuntu@ntopng:~$ sudo ntopng -i tcp://127.0.0.1:5556 -d /var/tmp -w 3000 -v
>> /dev/null &
and i tried ubuntu@ntopng:~$ sudo nprobe --collector-port 6343 --zmq tcp://
127.0.0.1:5556  -b 2 -v 5 no messages.

If I need to rebuild my virtual instance how do I restore my old data?

Thank you


Regards,
Samir

**Comment by emanuele-f** [comment]
Hi, ntopng data is stored in two locations:
- the data directory, which is `/var/tmp` in your case
- Redis, whose dump should be located at `/var/lib/redis/dump.rdb`

You will need to stop both ntopng and redis services before copying the data.
