### ISSUE TITLE
Sort broken on auto-refresh (OK for manual page refresh).

### ISSUE THREAD

**Issue by ak2766** [ntop/ntopng#1254]
When I elect to sort the flows by throughput, on auto-refresh of the page (not when I manually click the page refresh), the sort goes haywire.
![selection_048](https://cloud.githubusercontent.com/assets/6629646/26381856/ecb96100-406a-11e7-8517-095c091e5e8c.png)

Upon page refresh, the sort is good again.

UPDATE:
This is on CentOS 7:
```
# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.3.1611 (Core) 
Release:        7.3.1611
Codename:       Core
```
With the following packages:
```
# rpm -q redis ntopng hiredis-devel
redis-3.2.3-1.el7.x86_64
ntopng-2.4.170523-1314.x86_64
hiredis-devel-0.12.1-1.el7.x86_64
```
Installed following these directions:
[How to Install ntopng Community on CentOS 7](https://www.vultr.com/docs/how-to-install-ntopng-community-on-centos-7)

**Comment by ak2766** [comment]
I believe the issue is that the IP Address column stays fixed with auto-refresh.  I can see why one would like it set this way - to keep track of current high throughput users - or maybe for performance gains (there are >1500 rows).

However, it would be nice if there was a radio button to lock a column when sort is activated as opposed to the 'sort-of-broken' behaviour currently seen.

Or maybe there's an option to change this behaviour; I've just finished installing it to help track down bandwidth abusers in the future.

Had an issue yesterday that I finally identified via iptables, but that is the long way to do it. NtopNG simplifies this tremendously.

**Comment by emanuele-f** [comment]
Hi, this is the intended behaviour. The update only updates statistics on the page but does not change elements on the page.
What you really need is a real time view of the top hosts of the network with their throughput. We provide this in the traffic dashboard which is available in the pro version of ntopng.

Please see this screenshot:  http://4.bp.blogspot.com/-SQjPNWQhq8o/Vctx9muWLcI/AAAAAAAAAkg/dGOqieo1CLY/s1600/screenshot-192%2B168%2B0%2B21%2B3000%2B2015-08-12%2B20-29-00.png

**Comment by ak2766** [comment]
Thanks Emanuele.

Time to pay up or shut up, I see - :).  I'll see if the company is willing to go the extra mile.

Cheers,
ak.
