### ISSUE TITLE
Unsupported Publisher Version with nProbe

### ISSUE THREAD

**Issue by parksj10** [ntop/ntopng#1256]
Hi,

I've installed nprobe and ntopng on my windows 2008 R2 Server, and am collecting TrafficFlow (Netflow) data from my Mikrotik router. When I run the programs together with the below commands, I get an error telling me that my nprobe may be out of date, or more specifically, the ntopng received flow is an unsupported publisher version. Please see below for details. Any insight is appreciated. Note: I have also tried configure my router and nprobe for netflow v9

`nprobe /c nprobe -n none --zmq "tcp://*:5556" --flow-version 5 --lifetime-timeout 60 --idle-timeout 15 --zmq-encrypt-pwd ***** --collector-port 2055 -b 2`

`ntopng /c -i tcp://127.0.0.1:5556 --zmq-encrypt-pwd *****`
 
[ntopng_log.txt](https://github.com/ntop/ntopng/files/1024517/ntopng_log.txt)
[npobe_log.txt](https://github.com/ntop/ntopng/files/1024516/npobe_log.txt)

Thanks,
Josh

**Comment by simonemainardi** [comment]
you are running nprobe `v 7.5.170507` and ntopng `v 2.4.160627 `, please make sure to install ntopng from http://packages.ntop.org/Windows/preview/

**Comment by parksj10** [comment]
Thanks that solved the versioning issue!

**Comment by simonemainardi** [comment]
thanks for reporting
