### ISSUE TITLE
glib-2.0 missing

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#1258]
Just compiled ``ntopng`` on Ubuntu 14.04 according to documentation:

	git clone https://github.com/ntop/ntopng.git

	cd ntopng
	./autogen.sh
	./configure
	make

I got following warnings:

	Find 3rd-Party Libraries
	checking for glib_check_version in -lglib-2.0... no
	checking for pkg-config... pkg-config
	configure: WARNING:
	----------------------------------------------------------------------------
	* I found a copy of pkgconfig, but there is no glib-2.0.pc file around.
	  You may want to set the PKG_CONFIG_PATH variable to point to its
	  location.
	----------------------------------------------------------------------------

	configure: WARNING:
	----------------------------------------------------------------------------
	* I could not find a working copy of glib-2.0. Check config.log for hints on why
	  this is the case. Maybe you need to set LDFLAGS and CPPFLAGS appropriately
	  so that compiler and the linker can find libglib-2.0 and its header files. If
	  you have not installed glib-2.0, you can get it either from its original home on

		 ftp://ftp.gtk.org/pub/glib/2.28/

	  You can find also find an archive copy on

		 http://oss.oetiker.ch/rrdtool/pub/libs

	  The last tested version of glib-2.0 is 2.28.7.

		   LIBS=-lm
	   LDFLAGS=
	  CPPFLAGS=

	----------------------------------------------------------------------------

	checking for xmlParseFile in -lxml2... no
	checking for pkg-config... (cached) pkg-config
	configure: WARNING:
	----------------------------------------------------------------------------
	* I found a copy of pkgconfig, but there is no libxml-2.0.pc file around.
	  You may want to set the PKG_CONFIG_PATH variable to point to its
	  location.
	----------------------------------------------------------------------------

	configure: WARNING:
	----------------------------------------------------------------------------
	* I could not find a working copy of libxml-2.0. Check config.log for hints on why
	  this is the case. Maybe you need to set LDFLAGS and CPPFLAGS appropriately
	  so that compiler and the linker can find libxml2 and its header files. If
	  you have not installed libxml-2.0, you can get it either from its original home on

		 http://xmlsoft.org/downloads.html

	  You can find also find an archive copy on

		 http://oss.oetiker.ch/rrdtool/pub/libs

	  The last tested version of libxml-2.0 is 2.7.8.

		   LIBS=-lm
	   LDFLAGS=
	  CPPFLAGS= -I/usr/include/libxml2

	----------------------------------------------------------------------------

Solution: Install missing packets. For glib: libglib2.0-0, libglib2.0-d and for libxml libxml2-dev:

    apt-get install libglib2.0-0 libglib2.0-d libxml2-dev

Is it possible and feasible to test during ./configure whether these packets are installed?

**Comment by lucaderi** [comment]
Hello, please install the prerequisites as described in https://github.com/ntop/ntopng/blob/dev/doc/README.compilation and it will work
