### ISSUE TITLE
Local MAC addresses are seldom recognized when collecting tagged VLAN traffic

### ISSUE THREAD

**Issue by PaulosV** [ntop/ntopng#126]
Right now I have Cisco monitoring port with about 5 different tagged VLANs (802.1q), connected to our monitoring server and traffic being analyzed by `ntopng Community v.2.0.150814`. (but this is an issue from stable v.2, at least)

Most of the local IP addresses (from our assigned IP range in the same L2 subnet) have a bogus MAC address assigned (something like 04:00:00:00:00:00 - 24 hosts have this one right now; or 07:00:00:00:00:00), even though they're connected to the same L2 network and communicate without any issues. They are not behind any NAT or masqueraded, and the MAC address information is present in the network dumps. Addresses from both public and private IP ranges have the same problem. Seldom, though, it happens that a correct MAC is assigned. I didn't manage to see any obvious pattern.

ntopng is freshly compiled from source, today.

**Comment by lucaderi** [comment]
@PaulosV Can you please send me (private) via email a pcap file to reproduce this issue?

**Comment by PaulosV** [comment]
@lucaderi You have it ;)

**Comment by kYroL01** [comment]
@PaulosV You're right. I also notice that. I'm trying to fix in these days

**Comment by PaulosV** [comment]
I can't properly test the change now, but it looks promising, thank you! Anyone else can confirm it is fixed?

**Comment by kYroL01** [comment]
We tried on two different pc (one with Linux and one with Mac) and it seems to be fixed. Waiting for your test.

**Comment by kYroL01** [comment]
Fixed

**Comment by lmangani** [comment]
Thanks for the confirmation!
