### ISSUE TITLE
ntopng nightly build: host details -> active flows: application filters doesn't work

### ISSUE THREAD

**Issue by bioteseo** [ntop/ntopng#1262]
Host detail -> active flows -> when I select an application filter for example unknown the output is:
Error 404: Not Found
File not found

I tried all filters shown, the results is the same, i.e.:
http://localhost:3000/ntopng/ntopng/lua/host_details.lua?ifid=0&host=xxx.xxx.xxx.xxx&page=flows
Error 404: Not Found
File not found

I'm using ntopng nightly version
# ntopng --version
v.2.5.170525 [Enterprise/Professional Edition]
GIT rev:   dev:77ec2d0f9257a2555dc7b0c0b8af1eb2fa5049af:20170525
Pro rev:   r1086
System Id: 2BB308FC11B1B8A2
Built on:  Ubuntu 14.04.5 LTS

Thanks

**Comment by emanuele-f** [comment]
There is something wrong about the url above, the "ntopng/ntopng" part should not be there.

http://localhost:3000/lua/host_details.lua?ifid=0&host=xxx.xxx.xxx.xxx&page=flows

Can you browse `http://localhost:3000` and tell us when the "ntopng/ntopng" starts appearing in the url?

**Comment by bioteseo** [comment]
If I remove that it works:
http://localhost:3000/ntopng/ntopng/lua/host_details.lua?ifid=0&host=xxx.xxx.xxx.xxx&page=flows - ko
http://localhost:3000/ntopng/lua/host_details.lua?ifid=0&host=xxx.xxx.xxx.xxx&page=flows - ok
The application filter adds the second ntopng in the url

**Comment by emanuele-f** [comment]
"ntopng" should not appear in the url at all, can you tell where the first "ntopng" it is added?

**Comment by emanuele-f** [comment]
Please post your `ntopng.conf` file or the command line options used to run ntopng

**Comment by bioteseo** [comment]
I login in ntopng with:
http://xxx.xxx.xxx.xxx:3000
After the login every time I click on ntopng GUI ntopng string compare in the url.
This is an example:
http://xxx.xxx.xxx.xxx:3000/ntopng/lua/about.lua
 The double string ntopng compare only after the application filter as I described above.
This is the startup line: ntopng --pid "/var/tmp/ntopng.pid" --daemon "" --http-port "xxx.xxx.xxx.xxx:3000" --http-prefix "/ntopng" --dns-mode "3" --max-num-flows "200000" --max-num-hosts "250000" --sticky-hosts "local" --verbose "" --capture-direction "1" --interface "eth2" --local-networks "xxx.xxx.xxx.0/24,xxx.xxx.0.0/16,xxx.xxx.0.0/16,xxx.xxx.0.0/16,xxx.xxxx.0.0/16" --community ""

and this is the ntopng.conf:
-G=/var/tmp/ntopng.pid
--daemon=
# Listen on localhost:3000 only
--http-port=xxx.xxx.xxx.xxx:3000
# Use prefix due to nginx proxy
--http-prefix="/ntopng"
# Everybody's admin
#--disable-login=1
# Do not resolve any names
--dns-mode=3
# Limit memory usage
--max-num-flows=200000
--max-num-hosts=250000
--sticky-hosts=local
# Dump flows to MySQL
#--dump-flows=mysql;localhost;ntopng;flows;ntopng;xxx
--verbose
# Specify packet capture direction 0=RX+TX (default), 1=RX only, 2=TX only
--capture-direction=1

# add
--interface=eth2
--local-networks="xxx.xxx.xxx.0/24,xxx.xxx.0.0/16,xxx.xxxx.0.0/16,xxx.xxx.0.0/16,xxx.xxx.0.0/16"
--community=

I copied that from ntopng user guide
I have another ntopng, (stable version) and similar configuration. With this ntopng I haven't that problem

**Comment by bioteseo** [comment]
In the ntopng.conf I commented: http_prefix
#--http-prefix="/ntopng" and restarted ntopng.
The problem is solved.
As I said, the ntopng user guide "suggest" that line and the stable version haven't got that problem

Thanks

**Comment by emanuele-f** [comment]
There is probably a bug in that specific page, I will investigate, thank you

**Comment by bioteseo** [comment]
Thank you too

**Comment by emanuele-f** [comment]
Fixed with 6e4cc5eacc81584a013de925ba9b5ca3f38b9658 . Thank you for reporting!
