### ISSUE TITLE
Request for a new feature: download txt list of local/remote hosts

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#1264]
I've just seen the new footer of ntopng with the numbers of local/remote hosts:

![ntopng_footer](https://cloud.githubusercontent.com/assets/14093378/26456584/ca0ff70a-416d-11e7-8bf7-9d28cd31f8ef.png)

Very usefull!

Could you add a feature to permit to download the list (in txt format) of, at least, all the local hosts?
This feature would be useful for us to easily identify the IP of our local hosts: 30000 local hosts are too many for our network and a txt list could be useful to identify some anomaly. 

Could you implement it?

Thanks...

**Comment by simonemainardi** [comment]
Thanks :)

To download host data, you can use the Export data function:

![image](https://cloud.githubusercontent.com/assets/3397663/26459369/7fe097c6-4176-11e7-9c98-147e795c9cef.png)

Each host is in JSON format and has a flag that tells you if it is local or not

**Comment by gianogli** [comment]
Ok, thanks...
I've just tried but there is a big problem. My browser (chrome) is not able to manage the JSON output when there are about 80000 hosts (internal + external) as in my case. Chrome now is freezed and I'm not able to cut and paste the output to a txt file.
I think that you have to modify the "Export  Data" web page, if possible, to add:
  -) a "Save to file" option to save the JSON output directly to an external file
  -) a local/external flag to filter the hosts directly before extract the data to file

What do you think?

Thanks....

**Comment by emanuele-f** [comment]
Hi, I agree that being able to only filter the local hosts would be ideal.

For now, you can export data via an external script (e.g. via [curl](https://github.com/ntop/ntopng/tree/dev/doc)) and performs your filters there.

**Comment by gianogli** [comment]
I've just tried to download the data using wget but there are some inconsistencies between the data shown on the web interface and the exported data.

From web interface we have:

![hosts_ntopng](https://cloud.githubusercontent.com/assets/14093378/26620890/eb4f8c48-45e4-11e7-9c2c-2ebfe6999f90.png)

        Local hosts: 28,404
        Remote hosts: 45,233

But if I use the exported data:

```
~# wget -O hosts.json "http://X.X.X.X:3000/lua/do_export_data.lua?ip=&ifid=9&vlan=" 
--2017-05-31 09:32:20--  http://X.X.X.X:3000/lua/do_export_data.lua?ip=&ifid=9&vlan=
Connecting to X.X.X.X:3000... connected.
HTTP request sent, awaiting response... 302 Found
Location: / [following]
--2017-05-31 09:32:20--  http://X.X.X.X:3000/
Reusing existing connection to X.X.X.X:3000.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: ‘hosts.json’

hosts.json            [  <=>  ]  44.11M  4.31MB/s    in 13s     

2017-05-31 09:32:34 (3.36 MB/s) - ‘hosts.json’ saved [46248492]

~# jq '.[].localHost' hosts.json | grep true | wc -l
12503
~# jq '.[].localHost' hosts.json | grep false | wc -l
14560
```

So, if I haven't made some errors, it seems that from the exported data we have:

        Local hosts: 12,503
        Remote hosts: 14,560

The numbers I've found are very different! Is this normal?

I tried to analyze the exported data and I discovered that inside the json file there aren't a lot of our  /24 networks (the data related to these missed networks are however accessible through the web interface). Is this a bug?

Thanks...

**Comment by simonemainardi** [comment]
Presently, the counter in the footer does not keep a realtime view of active hosts. That would be too costly in terms of performances and new hosts can arrive or go idle too fast.

So I would expect small differences between the footer counter and the actual number of active hosts. Small, not one half. 

Please, let me know how different are the footer counters for hosts wrt the counters found in pagination info numbers obtained when visiting the host page. Pagination information should contain the actual number of active hosts as the active hosts are evaluated when visiting the page.

**Comment by gianogli** [comment]
Ok, thanks for the info... :-)
In the Hosts web page I see 32768 hosts while the footer image show about 29300 hosts. These values are quite ok. The problem seems to be the exported data file...

**Comment by simonemainardi** [comment]
both pages use the same function getActiveHostList so I can't understand why you've such limit.

are you sure the line 'jq '.[].localHost' hosts.json | grep true | wc -l' properly count the local hosts?

**Comment by gianogli** [comment]
I've tried again...
I don't know if this is important or not but I'm using a "view" interface (ifid=9).

Footer:

![hosts_ntopng](https://cloud.githubusercontent.com/assets/14093378/26635085/e916ed48-4618-11e7-8276-479f57304199.png)

        Local Hosts: ~29000
        Remote Hosts: ~52000
        => Total Hosts: ~81000

End of the "All Hosts" web page:

![hosts2_ntopng](https://cloud.githubusercontent.com/assets/14093378/26635135/0fcf8fb2-4619-11e7-9ad2-f38a1bf739be.png)

        Total Hosts: 32768 (<< ~81000)

Then I downloaded the exported data file in the same way and:

```
`# wget -O hosts.json "http://130.192.190.232:3000/lua/do_export_data.lua?ip=&ifid=9&vlan="
[...]
~# wc -l hosts.json 
25845 hosts.json
```

If each line is a local/remote host:

        Total Hosts: 25845 (< 32768 and << ~81000)

The counted number of total hosts is always different...

What do you think?

Request: if the number in the footer is not exact as you explained me before, I suggest you to write in the footer something like "~29k hosts" and not a precise number like "28,584"

Thanks...

**Comment by simonemainardi** [comment]
the second (grey) badge counts all hosts, not just remote

**Comment by gianogli** [comment]
Are you sure? :-O
If I click over the grey badge the browser go to the http://X.X.X.X:3000/lua/hosts_stats.lua?mode=remote link, that is the "Remote Hosts" page...

**Comment by simonemainardi** [comment]
right, counter has been recently pointed to the remote hosts only.

by the way, 32768 is a limit enforced when browsing any kind of hosts (this prevents too long hash tables lookups) so it is normal that you don't see number greater than this in the UI

**Comment by gianogli** [comment]
Uhm... Ok! Thanks. :-)
However there are a lot of unclear parts in the hosts management:
-) The "32768" limit (not signaled in the hosts list).
-) The (look like real time...) number of (total/locale/remote?) hosts in the grey/green badge in the footer.
-) In the exported JSON file there is only a part of the indicated hosts, not all.
I hope you could solve these "issues" into the next releases of ntopng...
Thanks anyway for your big work! ;-)

**Comment by simonemainardi** [comment]
a new download page with the requested features has been implemented:

![image](https://user-images.githubusercontent.com/3397663/30219374-271cc198-94bc-11e7-81b9-289b577e7d9f.png)

results are returned as a JSON attachment so no more issues with large results shown in the browser.
