### ISSUE TITLE
P2P still being downloaded

### ISSUE THREAD

**Issue by izzie88** [ntop/ntopng#1269]
Hello Cento crew,

P2P is still being downloaded through cento.

Worked at first after deployment, now users can now download P2P.

-------my bridge config is as follows
[bridge]
default = forward

[bridge.protocol]
BitTorrent = discard
Filetopia = discard 
OpenFT = discard 
FastTrack = discard 
Gnutella = discard 
eDonkey = discard

-------started cento as below
echo 4096 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
mount -t hugetlbfs nodev /mnt/huge
cento-bridge -i zc:eth0,zc:eth2 --zmq tcp://127.0.0.1:5556 --bridge-conf bridge-policy --dpi-level 2 -v 6

Why can my users still download torrents?
Please help

**Comment by lucaderi** [comment]
Hello, please move this issue under https://github.com/ntop/nProbe/issues and share a pcap wile with some traffic you believe it's p2p but that's not blocked by cento.
