### ISSUE TITLE
DNS Replies

### ISSUE THREAD

**Issue by ayeshabasit** [ntop/ntopng#1270]
Hi, from what I understand, NTOPNG logs DNS queries, but is there a way to log/look at DNS replies? Particularly, is there a way to check if a lookup failed?

**Comment by emanuele-f** [comment]
Hi, you can do this on a per-host basis. Just go into an host page and click on the DNS tab.

![screenshot at 2017-05-27 15-37-14](https://cloud.githubusercontent.com/assets/5488003/26521820/b3c9ac28-42e1-11e7-800f-69f27d423bd3.png)

**Comment by ayeshabasit** [comment]
Okay, but can we do this on a _per-flow basis_? I know we can see queries, but I couldn't see replies.

**Comment by emanuele-f** [comment]
No, this information is not currently available on the flows. Please open a separate feature request.
