### ISSUE TITLE
WARNING Script failure

### ISSUE THREAD

**Issue by mevertse** [ntop/ntopng#1271]
We get a warning message every minute
[Lua.cpp:6076] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:1948: attempt to index field 'stats' (a nil value)]

Is there a way to fix this?
Version	2.5.170527 - Community Edition

**Comment by emanuele-f** [comment]
Hi, I've just committed a fix for this 91728e40eec7395232ae364900108e515cf94bd4 .
Please update to the next version, which will be available tomorrow. In the meantime, you can temporarily disable alerts with the `-H` option to avoid the error.
