### ISSUE TITLE
filtering broadcast, multicast, default route

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#1273]
hi

in my ntopng.conf, I use
...
--packet-filter="ip and not ip multicast and not ether broadcast"
...

but it doesn't seem to work
I just want to remove all these IP/network from ntopng GUI
+ not sure how to remove default route (0.0.0.0)

![capture](https://cloud.githubusercontent.com/assets/17108017/26545191/fb9925c2-4464-11e7-8719-cabe095fee2e.PNG)

thanks

**Comment by Niko78** [comment]
ok I found that in log
[CollectorInterface.cpp:277] ERROR: No filter can be set on a collector interface.

**Comment by emanuele-f** [comment]
So you should set these filters on the nProbe side, please add `--bpf-filter` option to nProbe.

Note: you should also add "and not ip broadcast" to the filter

**Comment by Niko78** [comment]
not better
[nprobe.c:8199] WARNING: You cannot use BPF filters (ip and not ip multicast and not ether broadcast and not host 0.0.0.0) in collector/proxy mode: BPF filter disabled

**Comment by emanuele-f** [comment]
Your probe is acting as a flow collector so BPF is indeed not supported. I'm labelling this post as a feature request.

**Comment by simonemainardi** [comment]
@Niko78 use the filter on the nprobe (--bpf-filter) not on the ntopng

**Comment by Niko78** [comment]
@simonemainardi that's what Emanuele asked me and I did it with no more success
