### ISSUE TITLE
Add SSL version when I use Ntopng like probe to send flow at an other Ntopng

### ISSUE THREAD

**Issue by stage0144** [ntop/ntopng#1277]
Hi,

So today I use a Raspberry PI 3 like a probre plugged on a switch (port mirroring) to catch flow and return it to an other Ntopng. All works good but I want add some informations to flow details.
Indeed first of all I want add the SSL version.

To do that I try to use ndpiFlow on Flow.cpp to create packet. With this packet I recovers the byte wich correspond to SSL version : 

`if((isSSL()) && (&ndpiFlow->packet != '\0'))	
{

		struct ndpi_packet_struct *packet = &ndpiFlow->packet;
		if(packet->payload[0] == 0x16){
			if(packet->payload[9] == 0x03 && packet->payload[10] == 0x01) 
			{
				protos.ssl.version = strdup("1.0");
			}
			else if(packet->payload[9] == 0x03 && packet->payload[10] == 0x02)
			{
				protos.ssl.version = strdup("1.1");
			}
			else if(packet->payload[9] == 0x03 && packet->payload[10] == 0x03)
			{
				protos.ssl.version = strdup("1.2");
			}
			else if(packet->payload[9] == 0x03 && packet->payload[10] == 0x04)
			{
				protos.ssl.version = strdup("1.3");
			}
		}
}`

It works when I use Ntopng alone on my computer, but in my configuration I have several problems (when I use a probe).
First I don't know why, but I have random Segmentation fault because of this part of code even if I try to protect against errors with a lot of 'if'.
After that I search to add version to flow wich is export with JSON (I want to add this variable on function Flow2Json on Flow.cpp), but I don't know how Ntopng recovers data wich is send at JSON format.

If someone can help me or gives some informations to better understand how works this part it will be very usefull. If I use a bad method to do that, do not hesitate do tell me.

**Comment by emanuele-f** [comment]
Hi, as explained in #1245, you can push custom fields via nprobe and this is how we support that feature. If you wish to do your own experiments with nDPI/ntopng, you can do that, but we cannot provide support for custom code. I can only suggest you to run the code with a debugger (e.g. gdb) and see where it crashes. You can look at the ParserInterface to have a clue on how ntopng parses ZMQ data from nprobe and add your own logic there.
