### ISSUE TITLE
Ntopng keeps crashing

### ISSUE THREAD

**Issue by izzie88** [ntop/ntopng#1278]
Hello Ntopng team,

My ntopng keeps crashing so i have to always manually restart it.

I find these in the ntopng logs.

25/May/2017 12:50:35 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
25/May/2017 12:50:35 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
25/May/2017 12:50:35 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
25/May/2017 12:50:36 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
25/May/2017 12:50:36 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
25/May/2017 12:50:37 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
25/May/2017 12:50:38 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
25/May/2017 12:50:39 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
25/May/2017 12:50:39 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
25/May/2017 12:50:41 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
25/May/2017 12:50:42 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
25/May/2017 12:50:42 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
25/May/2017 12:50:43 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
25/May/2017 12:50:43 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
25/May/2017 12:50:44 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
25/May/2017 12:50:44 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
25/May/2017 12:50:44 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:55:31 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:55:32 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:55:32 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:55:32 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:55:33 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:55:33 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:55:34 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:55:36 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:55:36 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:55:36 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:55:37 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:55:38 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:55:38 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:55:41 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:55:41 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:56:04 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:56:05 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:56:05 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:56:06 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:56:06 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:56:14 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:56:15 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:56:15 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 08:56:15 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 09:56:42 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 09:56:42 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 09:56:44 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 09:56:44 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 09:56:45 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 09:56:45 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 09:56:45 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 09:56:45 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 09:56:46 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 09:56:46 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 09:56:46 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 09:56:47 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 09:56:47 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]
26/May/2017 09:56:47 [Lua.cpp:6358] WARNING: Script failure [/usr/share/ntopng/scripts/lua/find_host.lua][/usr/share/ntopng/scripts/lua/find_host.lua:29: bad argument #1 to 'pairs' (table expected, got nil)]

Kindly assist.

**Comment by simonemainardi** [comment]
@izzie88 what version are you running? Can you generate a core dump of the crash and upload both the binary and the dump?

**Comment by emanuele-f** [comment]
@izzie88 you are using an outdated ntopng version, please update

**Comment by izzie88** [comment]
Hi 
ntopng Pro [Small Business Edition] v.2.5.170331

**Comment by emanuele-f** [comment]
Please update

**Comment by izzie88** [comment]
i try to update to the new ntopng, 
'make install' keeps bringing error.

Please help.

**Comment by izzie88** [comment]
Hi Ntopng crew,
This is what the make install throws:

root@NTOP-DPI:~/ntopng# make install
Make sure you have already run 'make geoip' to also install geoip dat files
While we provide you an install make target, we encourage you
to create a package and install that
rpm - do 'make build-rpm'
deb - do 'cd packages/ubuntu;./configure;make
mkdir -p /usr/local/share/ntopng /usr/local/man/man8 /usr/local/bin
cp ntopng /usr/local/bin
cp: not writing through dangling symlink '/usr/local/bin/ntopng'
Makefile:224: recipe for target 'install' failed
make: *** [install] Error 1

Please help.

**Comment by simonemainardi** [comment]
@izzie88 are you trying to overwrite an installed ntopng package? Uninstall any existing package and then do an update. (assuming you are using debian/ubuntu, just run apt-get update && apt-get install ntopng)

**Comment by izzie88** [comment]
Hi simone,

this is what i get:

apt-get update
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:2 http://ng.archive.ubuntu.com/ubuntu xenial InRelease                                                 
Get:3 http://ng.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]                                         
Get:5 http://ng.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]                  
Hit:6 http://packages.ntop.org/apt/16.04 all/ InRelease  
Get:4 http://packages.ntop.org/apt/16.04 x64/ InRelease [2,137 B]                                                                                    
Get:7 http://packages.ntop.org/apt/16.04 x64/ Packages [453 B]                                                                                       
Ign:7 http://packages.ntop.org/apt/16.04 x64/ Packages                                                                                               
Get:7 http://packages.ntop.org/apt/16.04 x64/ Packages [615 B]                                                                                       
Err:7 http://packages.ntop.org/apt/16.04 x64/ Packages                                                                                               
  Writing more data than expected (4943 > 615) [IP: 164.132.198.64 80]
Fetched 309 kB in 6s (47.4 kB/s)                                                                                                                     
Reading package lists... Done
E: Failed to fetch http://packages.ntop.org/apt/16.04/x64/Packages  Writing more data than expected (4943 > 615) [IP: 164.132.198.64 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by simonemainardi** [comment]
It looks like you have accessed the repository mirror while being updated. Wait some time and try again...

**Comment by izzie88** [comment]
Hi I have waited 3hours and still the same error being thrown



Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:2 http://ng.archive.ubuntu.com/ubuntu xenial InRelease                                 
Get:3 http://ng.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]                                          
Get:4 http://ng.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]                                                   
Hit:6 http://packages.ntop.org/apt/16.04 all/ InRelease
Get:5 http://packages.ntop.org/apt/16.04 x64/ InRelease [2,137 B]
Get:7 http://packages.ntop.org/apt/16.04 x64/ Packages [453 B]
Ign:7 http://packages.ntop.org/apt/16.04 x64/ Packages
Get:7 http://packages.ntop.org/apt/16.04 x64/ Packages [615 B]
Err:7 http://packages.ntop.org/apt/16.04 x64/ Packages
  Writing more data than expected (4943 > 615) [IP: 164.132.198.64 80]
Fetched 309 kB in 1s (199 kB/s)       
Reading package lists... Done
E: Failed to fetch http://packages.ntop.org/apt/16.04/x64/Packages  Writing more data than expected (4943 > 615) [IP: 164.132.198.64 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by simonemainardi** [comment]
try now...

**Comment by emanuele-f** [comment]
@izzie88 any update?

**Comment by izzie88** [comment]
Update has been done, but i still keep restarting ntopng manually, I still did it today. Quick question please, does the license being expired have anything to do with it?

**Comment by emanuele-f** [comment]
When the licence expires, you will go into community mode but it does not explain the issue. Please try to run manually ntopng from the cli so that we can see the possible cause. You can do this by stopping ntopng service via `sudo systemctl stop ntopng` and then start it from command line `sudo ntopng /etc/ntopng/ntopng.conf`.

Please post the console log you get.

**Comment by izzie88** [comment]
Hi,
This is what i have:

sudo ntopng /etc/ntopng/ntopng.conf
07/Jun/2017 10:22:36 [Ntop.cpp:1359] Setting local networks to 41.184.152.0/21,41.184.168.0/21,41.184.180.0/22,41.184.164.0/22,41.184.184.0/24,41.184.187.0/24,41.184.185.0/24,41.184.186.0/24
07/Jun/2017 10:22:36 [Redis.cpp:109] Successfully connected to redis 127.0.0.1:6379@0
07/Jun/2017 10:22:36 [NtopPro.cpp:146] [LICENSE] Reading license from /etc/ntopng.license
07/Jun/2017 10:22:36 [NtopPro.cpp:144] [LICENSE] Read license from Redis []
07/Jun/2017 10:22:36 [NtopPro.cpp:196] ERROR: [LICENSE] Invalid or missing ntopng License [Empty license file]
07/Jun/2017 10:22:36 [NtopPro.cpp:209] WARNING: [LICENSE] ntopng will now run in enterprise edition for 10 minutes
07/Jun/2017 10:22:36 [NtopPro.cpp:211] WARNING: [LICENSE] before returning to community mode
07/Jun/2017 10:22:36 [NtopPro.cpp:212] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
07/Jun/2017 10:22:36 [NtopPro.cpp:213] WARNING: [LICENSE] or run ntopng in community mode starting
07/Jun/2017 10:22:36 [NtopPro.cpp:214] WARNING: [LICENSE] ntopng --community
07/Jun/2017 10:22:37 [HostPools.cpp:65] Host Pools Available: 4
07/Jun/2017 10:22:37 [NetworkInterface.cpp:368] ERROR: Unknown agrgegation value 
07/Jun/2017 10:22:37 [Ntop.cpp:1464] Registered interface tcp://127.0.0.1:5556c [id: 5]
07/Jun/2017 10:22:37 [main.cpp:250] PID stored in file /var/run/ntopng.pid
07/Jun/2017 10:22:37 [HTTPserver.cpp:760] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
07/Jun/2017 10:22:37 [Utils.cpp:371] User changed to nobody
07/Jun/2017 10:22:37 [HTTPserver.cpp:814] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
07/Jun/2017 10:22:37 [HTTPserver.cpp:817] HTTP server listening on port(s) 3000
07/Jun/2017 10:22:37 [main.cpp:311] Working directory: /storage/ntopng
07/Jun/2017 10:22:37 [main.cpp:313] Scripts/HTML pages directory: /usr/share/ntopng
07/Jun/2017 10:22:37 [Ntop.cpp:307] Welcome to ntopng x86_64 v.3.1.170602 - (C) 1998-17 ntop.org
07/Jun/2017 10:22:37 [Ntop.cpp:312] Built on Ubuntu 16.04.2 LTS
07/Jun/2017 10:22:37 [PeriodicActivities.cpp:56] Started periodic activities loop...
07/Jun/2017 10:22:37 [NtopPro.cpp:273] [LICENSE] ntopng systemId: CCA23B229105A1EF
07/Jun/2017 10:22:37 [NtopPro.cpp:278] [LICENSE] ntopng is starting in demo mode
07/Jun/2017 10:22:37 [NetworkInterface.cpp:2045] Started packet polling on interface tcp://127.0.0.1:5556c [id: 5]...
07/Jun/2017 10:22:38 [CollectorInterface.cpp:115] Collecting flows on tcp://127.0.0.1:5556c
07/Jun/2017 10:22:38 [ParserInterface.cpp:853] WARNING: Invalid message received: your nProbe sender is outdated, data encrypted or invalid JSON?
07/Jun/2017 10:22:38 [ParserInterface.cpp:855] WARNING: JSON Parse error [object value separator ',' expected] payload size: 398 payload: {"8":"41.184.169.123","12":"8.8.8.8","10":0,"14":0,"2":5,"1":1351,"24":5,"23":1383,"22":1496827314,"21":1496827327,"7":61587,"11":53,"6":0,"4":17,"5":0,"57590":5,"57677":"3?1o19sr00nn50n497p372o11qr828r97pr1p65o45pq94n44qs7r86qn61r9pnn2?pnpp5r741p737393648s247p01n84noqq0oq6s5q06254190n33s1n205rrsonq"r1005q9239s6p06r4o3pp76q82qr3105o3(ppnq5pq98399049orp5972637143nps16p232p89.i.00.s.sophosxl.net"}

**Comment by emanuele-f** [comment]
Hi, please update nprobe and perform the test again. Can you see a segmentation fault or a "killed" message when ntopng stops working?

**Comment by izzie88** [comment]
its still working, it takes  quite a while to crash. Mostly notice it in the morning at resumption when i try to open the ntopng webpage. So i now have to manually restart the ntopng service.

**Comment by emanuele-f** [comment]
so please, after the nprobe update, keep ntopng running in the terminal until you experience the crash.

**Comment by izzie88** [comment]
Hello Emmanuele,

Please can you assist me in outlining the correct steps for updating the
nprobe.


On Jun 7, 2017 10:49, "Emanuele Faranda" <notifications@github.com> wrote:

so please, after the nprobe update, keep ntopng running in the terminal
until you experience the crash.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ntop/ntopng/issues/1278#issuecomment-306746751>, or mute
the thread

**Comment by emanuele-f** [comment]
You can update nprobe with `sudo apt-get update && sudo apt-get install nprobe`. After the update, please restart nprobe with `sudo systemctl restart nprobe` and also ntopng from command line. Please double check that your nprobe licence is not expired before performing the update!

**Comment by izzie88** [comment]
cneto license still valid till next year, i will do the update as soon as i can and revert back to you.

**Comment by emanuele-f** [comment]
if you are using nprobe cento, please use the command "apt-get install cento" to update it

**Comment by izzie88** [comment]
ok, thanks, i update as soon as i can and revert back to you.

**Comment by emanuele-f** [comment]
@izzie88 any news?

**Comment by izzie88** [comment]
I did an update 4 days ago, and it has been running for 4 days.
I am still monitoring it.

**Comment by emanuele-f** [comment]
Thank you for reporting.

I suggest you to update to the new version ntopng and nprobe to take advantage of the latest fixes. I'm closing the issue for now. Feel free to reopen it if necessary.

**Comment by izzie88** [comment]
Hi Emmanuele,
the ntopng crashed again today, I licensed to enterprise yesterday and it crashed this afternoon, i had to manually restart the process.

see logs from service ntopng status:

● ntopng.service - Start/stop ntopng program
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
   Active: active (exited) (Result: signal) since Mon 2017-07-03 13:05:31 WAT; 24h ago
  Process: 3486 ExecStop=/etc/init.d/ntopng stop (code=exited, status=0/SUCCESS)
  Process: 3538 ExecStart=/etc/init.d/ntopng start (code=exited, status=0/SUCCESS)
 Main PID: 3551 (code=killed, signal=SEGV)

Jul 03 13:05:30 NTOP-DPI systemd[1]: Starting Start/stop ntopng program...
Jul 03 13:05:30 NTOP-DPI ntopng[3538]:  * Starting ntopng
Jul 03 13:05:31 NTOP-DPI ntopng[3538]:    ...done.
Jul 03 13:05:31 NTOP-DPI systemd[1]: Started Start/stop ntopng program.
Jul 04 08:23:31 NTOP-DPI ntopng[3551]: [ParserInterface.cpp:853] WARNING: Invalid message received: your nProbe sender is outdated, data encrypted or invalid JSON?
Jul 04 08:23:31 NTOP-DPI ntopng[3551]: [321B blob data]
Jul 04 08:27:05 NTOP-DPI ntopng[3551]: [Lua.cpp:6115] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/callbacks/5min.lua:116: /storage/ntopng/5/rrd/41/184/165/21/
Jul 04 11:42:20 NTOP-DPI systemd[1]: ntopng.service: Main process exited, code=killed, status=11/SEGV

**Comment by simonemainardi** [comment]
@izzie88 the following error message suggests that nProbe could be updated.

```
Jul 04 08:23:31 NTOP-DPI ntopng[3551]: [ParserInterface.cpp:853] WARNING: Invalid message received: your nProbe sender is outdated, data encrypted or invalid JSON?
```

can you please try and `apt-get update && apt-get install ntopng nprobe` to make sure they are  both at the latest version?
