### ISSUE TITLE
After Update CentOS the Licenses for ntopng and nprobe are not work anymore

### ISSUE THREAD

**Issue by brunno-santiago** [ntop/ntopng#1279]
After Update CentOS the Licenses for ntopng and nprobe are not work anymore.
nprobe
OrderId: 1487796069
ntopng
OrderId: 1487776178

**Comment by simonemainardi** [comment]
what is your systemid? and ntopng and nprobe versions? try adding option --online-license-check

**Comment by brunno-santiago** [comment]
SystemId: 68C1DAA776056A7E 
Version ntopng: 2.4.170525  Small Business

I have tried put --online-license-check on .conf

**Comment by simonemainardi** [comment]
bruno, you system id has changed. You registered the license with system id 68C1DAA**755**05617E. Are you on a VM?

**Comment by brunno-santiago** [comment]
Simone, yes, my system is running on a VM vSphere 5.5 the only thing that I did was yum update -y && yum upgrade -y

**Comment by simonemainardi** [comment]
please follow instructions at  http://www.ntop.org/support/faq/how-can-i-move-a-license-to-a-new-server/ to transfer the license

Very likely your VM has changed some of the hardware (e.g., a card MAC address) and thus the license cannot be validated.

Please, make sure your VM hypervisor won't change the hardware again as transfer can be only done one time

**Comment by brunno-santiago** [comment]
it works, thanks.
