### ISSUE TITLE
How can I see the per-interface alerts in the web GUI? 

### ISSUE THREAD

**Issue by pwilthew** [ntop/ntopng#1280]
https://github.com/ntop/ntopng/issues/639

I'm using the 2.5.17 Enterprise/Professional Edition, but I can't find a way to see the the probing (and other) alerts.

Thank you,
Patricia

**Comment by simonemainardi** [comment]
there's an alert icol in the interface details page:

![image](https://cloud.githubusercontent.com/assets/3397663/26642931/e4e91842-462f-11e7-864b-e4420cf56209.png)

the alert icon in the menu only appears if there are detected alerts otherwise it is hidden

**Comment by pwilthew** [comment]
Would there be any reason to not having any alerts on 74,100+ hosts? 

I turned on the "Enable Probing Alerts" option in Security Alerts a week ago. 

One of the other interfaces has 45,000+ hosts and does not have any alerts either. 

Am I missing something?

Thanks!

**Comment by emanuele-f** [comment]
Hi, have you configured your local networks with the `-m` option? Alerts are only generated for local hosts

**Comment by pwilthew** [comment]
Yes, this is the config:
```
-G=/var/lib/ntopng/ntopng.pid
--dns-mode 0
-i=tcp://127.0.0.1:5356
-i=tcp://127.0.0.1:5456
-i=tcp://127.0.0.1:5556
-i=tcp://127.0.0.1:5656
-m "10.0.0.0/8,172.16.0.0/12, ...our public IPs...."
-d=/var/lib/ntopng
-w=3000
-F="mysql;localhost;ntopng;flows;ntop;QXv9kfFD"
#-v
```
