### ISSUE TITLE
New Feature Request "Plex Media Server" detection for nDPI

### ISSUE THREAD

**Issue by Kazz3r24** [ntop/ntopng#1281]
Just wondering if it's possible for Plex Media Server to be added into the detection list for nDPI. It uses TCP port 32400 primarily. Right now it's showing as Unknown under Application.

**Comment by simonemainardi** [comment]
@Kazz3r24 please add a feature request on the nDPI page: https://github.com/ntop/nDPI

Don't forget to add a pcap file containing the traffic you want to be detected.
