### ISSUE TITLE
LDAP Groups with Spaces

### ISSUE THREAD

**Issue by seismiccollision** [ntop/ntopng#1286]
looks like user_group and admin_group don't want spaces however I have existing groups with spaces
   ["user_group"]                                  =  validateSingleWord,
   ["admin_group"]                                 =  validateSingleWord,

Any possibility to change this or way to escape spaces?

**Comment by emanuele-f** [comment]
Fixed with 8c934757614d42234a335c739734a7c9e3a95bc1

**Comment by simonemainardi** [comment]
fixed both in sable and dev packages. Change will be available from tomorrow.
