### ISSUE TITLE
MAX_NUM_DEFINED_INTERFACES too low

### ISSUE THREAD

**Issue by seismiccollision** [ntop/ntopng#1287]
I have closer to 100 interfaces than the current MAX_NUM_DEFINED_INTERFACES of 32
Any considerations to increasing the value?

**Comment by lucaderi** [comment]
Can you please explain what is the use case for 100 interfaces? We need to understand if this is a real limitation or rather if we need to make a code design change.

**Comment by seismiccollision** [comment]
Sure thing!
I have multiple sflow sources that each aggregate traffic and send it so, since being able to have an interface created by source IP address, it's been nice to be able to see traffic sliced that way but I noticed that there was a limit to how many interfaces got created into the webui

**Comment by simonemainardi** [comment]
The number of interfaces has been made configurable and can be increased. 

If you are building from sources you can adapt the number by changing this define: https://github.com/ntop/ntopng/blob/0ac781d21c617236fa8cccedcc5907535e778c5a/include/ntop_defines.h#L110

Packaged versions are shipped with the number of interfaces indicated here: http://www.ntop.org/products/traffic-analysis/ntop/
