### ISSUE TITLE
!dont install ntop via apt-get!

### ISSUE THREAD

**Issue by sundarnet** [ntop/ntopng#1288]
im not sure where to post this issue but here it is
ok so just yesterday I tried to setup ntopng via apt and didn't type ntopng did just ntop !
DO NOT DO THIS !
it installed just ntop and not the proper package ntopng it then took me about 3 hrs to get ntopng installed correctly...... I think I still have an issue as I get this when apt-get upgrade

Synchronizing state of ntopng.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable ntopng
Failed to execute operation: File exists
dpkg: error processing package ntopng (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for libc-bin (2.23-0ubuntu7) ...
Errors were encountered while processing:
 ntopng

everything seems to be working but if you can fix ' remove ntop from the apt repository ' it would be nice 
I would like to fix the error that I get but yeah not real fussed !

**Comment by lucaderi** [comment]
In essence ntopng conflicts with the ntop (non ng) package?

**Comment by lucaderi** [comment]
is this https://github.com/ntop/ntopng/commit/63c9ac6d33d5ccd3fcf662d0bbe88f0621213b7a enough?

**Comment by sundarnet** [comment]
more than enough if I understand the code correctly 
' removed the now obsolete ntop from repositories, '
' or instead of installing old ntop it will actually install ntopng instead ' 
which one is correct?

**Comment by sundarnet** [comment]
is there an easy way to rid myself of this?

Synchronizing state of ntopng.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable ntopng
Failed to execute operation: File exists
dpkg: error processing package ntopng (--configure):
subprocess installed post-installation script returned error exit status 1
Processing triggers for libc-bin (2.23-0ubuntu7) ...
Errors were encountered while processing:
ntopng

when I apt-get upgrade ?

**Comment by emanuele-f** [comment]
Can you apt-get remove ntop and ntopng from your system and retry to install ntopng?

**Comment by sundarnet** [comment]
nope that did not work 
it also seems that the issue also will not let me fully register ntopng

**Comment by emanuele-f** [comment]
What ubuntu version are you using? Can you execute `systemctl disable ntopng` and then retry to install ntopng?

**Comment by sundarnet** [comment]
I cheated and just reinstalled the whole system due to using webmin it's a pretty easy restore process 
Fresh ubuntu servers install with DNS LAMP SSH
then install isc-dhcp-server squid 
edit interfaces reboot install webmin restore backed up settings install ntopng...... about 2 hrs 
and I aslo have it running kubuntu-desktop as well

**Comment by emanuele-f** [comment]
So, was the new ntopng installation successful?

**Comment by sundarnet** [comment]
I think all my problems were originating from me installing ntop 
It installed an old v1.? and just mangled everything.
As long as that is not possible anymore we are all good

**Comment by sundarnet** [comment]
Yes fully working registered 

this may work but 
http://sundarnethome.dnsdojo.org:3000

**Comment by emanuele-f** [comment]
Thank you for reporting.

**Comment by redtux** [comment]
issue closed? :-( having the same problem here. ;-) purging, `systemctl disable ntopng`, and reinstall did not help. directly installing via `dpkg -i --force-all` is also not working.

`apt-cache policy ntopng`
> ntopng:
>   Installed: (none)
>   Candidate: 3.0.170623-3081
>   Version table:
>      3.0.170623-3081 0
>         500 http://packages.ntop.org/apt-stable/jessie/ x64/ Packages
>      1.2.1+dfsg1-1.1 0
>         500 http://ftp.no.debian.org/debian/ jessie/main amd64 Packages

`dpkg -i --force-all /var/cache/apt/archives/ntopng_3.0.170623-3081_amd64.deb /var/cache/apt/archives/ntopng-data_3.0.170623_all.deb`
> Selecting previously unselected package ntopng.
> (Reading database ... 76857 files and directories currently installed.)
> Preparing to unpack .../ntopng_3.0.170623-3081_amd64.deb ...
> Unpacking ntopng (3.0.170623-3081) ...
> Selecting previously unselected package ntopng-data.
> Preparing to unpack .../ntopng-data_3.0.170623_all.deb ...
> Unpacking ntopng-data (3.0.170623) ...
> Setting up ntopng (3.0.170623-3081) ...
> 
> Configuration file `/usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem', does not exist on system.
> Installing new config file as you requested.
> Rebuilding ld cache...
> Adding the ntopng startup script [configure]
> Synchronizing state for ntopng.service with sysvinit using update-rc.d...
> Executing /usr/sbin/update-rc.d ntopng defaults
> Executing /usr/sbin/update-rc.d ntopng enable
> ln: failed to create symbolic link ‘/usr/local/bin/ntopng’: No such file or directory
> dpkg: error processing package ntopng (--install):
>  subprocess installed post-installation script returned error exit status 1
> Setting up ntopng-data (3.0.170623) ...
> Processing triggers for systemd (215-17+deb8u7) ...
> Processing triggers for man-db (2.7.0.2-5) ...
> Processing triggers for libc-bin (2.19-18+deb8u10) ...
> Errors were encountered while processing:
>  ntopng

as you can see, ntopng is running, but installing exits with an error:

`service ntopng status`
> ● ntopng.service - Start/stop ntopng program
>    Loaded: loaded (/etc/systemd/system/ntopng.service; enabled)
>    Active: active (exited) since Wed 2017-06-28 15:33:07 CEST; 55min ago
>  Main PID: 22009 (code=exited, status=0/SUCCESS)
> 
> Jun 28 15:33:04 navappliance ntopng[22009]: [NtopPro.cpp:211] WARNING: [LICENSE] before returning to community mode
> Jun 28 15:33:04 navappliance ntopng[22009]: [NtopPro.cpp:212] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
> Jun 28 15:33:04 navappliance ntopng[22009]: [NtopPro.cpp:213] WARNING: [LICENSE] or run ntopng in community mode starting
> Jun 28 15:33:04 navappliance ntopng[22009]: [NtopPro.cpp:214] WARNING: [LICENSE] ntopng --community
> Jun 28 15:33:05 navappliance ntopng[21999]: Starting ntopng:Cannot change tcp-segmentation-offload
> Jun 28 15:33:05 navappliance ntopng[21999]: Could not change any device features
> Jun 28 15:33:07 navappliance ntopng[21999]: .
> Jun 28 15:33:07 navappliance systemd[1]: Started Start/stop ntopng program.
> Jun 28 15:34:38 navappliance ntopng[22009]: [NetworkInterface.cpp:1676] WARNING: If you have TSO/GRO enabled, please disable it
> Jun 28 15:34:38 navappliance ntopng[22009]: [NetworkInterface.cpp:1678] WARNING: Use sudo ethtool -K lo gro off gso off tso off

okay, i just figured out, what the problem was. my debian jessie does not contain a `/usr/local/bin` directory. after manually creating it, everything works fine...

`apt install -f`
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> 1 not fully installed or removed.
> After this operation, 0 B of additional disk space will be used.
> Setting up ntopng (3.0.170623-3081) ...
> Rebuilding ld cache...
> Adding the ntopng startup script [configure]
> Synchronizing state for ntopng.service with sysvinit using update-rc.d...
> Executing /usr/sbin/update-rc.d ntopng defaults
> Executing /usr/sbin/update-rc.d ntopng enable
> ln: failed to create symbolic link ‘/usr/local/bin/ntopng’: No such file or directory
> dpkg: error processing package ntopng (--configure):
>  subprocess installed post-installation script returned error exit status 1
> Processing triggers for libc-bin (2.19-18+deb8u10) ...
> Errors were encountered while processing:
>  ntopng
> E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by redtux** [comment]
@lucaderi thank you for the fix! :+1:

**Comment by waqar-ali-aziz** [comment]
Is there anyone active to help me regarding nDPI tool

**Comment by emanuele-f** [comment]
@waqar-ali-aziz please don't resume closed issues. Please read the nDPI documentation and/or open a new support issue here: https://github.com/ntop/nDPI
