### ISSUE TITLE
Feature Request: Include DNS replies in individual flows

### ISSUE THREAD

**Issue by ayeshabasit** [ntop/ntopng#1289]
It would be a useful feature to include DNS replies.

**Comment by simonemainardi** [comment]
Feature is already supported when using ntopng in combination with nProbe. In particular, nProbe with plugin DNS will provide the requested information though the following fields

```
Plugin DNS/LLMNR Protocol templates:
[NFv9 57677][IPFIX 35632.205] %DNS_QUERY                        DNS query
[NFv9 57678][IPFIX 35632.206] %DNS_QUERY_ID                     DNS query transaction Id
[NFv9 57679][IPFIX 35632.207] %DNS_QUERY_TYPE                   DNS query type (e.g. 1=A, 2=NS..)
[NFv9 57680][IPFIX 35632.208] %DNS_RET_CODE                     DNS return code (e.g. 0=no error)
[NFv9 57681][IPFIX 35632.209] %DNS_NUM_ANSWERS                  DNS # of returned answers
[NFv9 57824][IPFIX 35632.352] %DNS_TTL_ANSWER                   TTL of the first A record (if any)
[NFv9 57870][IPFIX 35632.398] %DNS_RESPONSE                     DNS response(s)
```

**Comment by ayeshabasit** [comment]
I am sorry for the inconvenience but can I be pointed to some resources that can help me setup an ntop + nprobe installation? I tried searching for something of the sort to no luck.

**Comment by emanuele-f** [comment]
Hi, please see this link http://www.ntop.org/nprobe/advanced-flow-collection-with-ntopng-and-nprobe/

**Comment by ayeshabasit** [comment]
Thank you - but I am still a little confused as to what ZMQ is.

**Comment by emanuele-f** [comment]
It is a communication protocol to exhange messages. Ntopng and nprobe open a socket and exchange data via ZMQ messages
