### ISSUE TITLE
Interface Custom Names Don't Appear in Dashboard or Reports

### ISSUE THREAD

**Issue by valdecyralves** [ntop/ntopng#129]
Is there a way to have the Custom Names of the Interfaces appear everywhere else in the page including the reports? The custom names don't appear in the reports (or anywhere else in the page) and its difficult to associate the graphs with the long default interface names.
![unnamed](https://cloud.githubusercontent.com/assets/13868720/9355273/8e8dcd4e-4645-11e5-8da9-f92b02dd5094.png)

**Comment by lucaderi** [comment]
Problem fixed. Overnight a new build will include the fix.

**Comment by valdecyralves** [comment]
am I supposed to see a newer version listed here? or is there another way
to update?

http://packages.ntop.org/Windows/
[image: Inline image 2]

**Comment by lucaderi** [comment]
This is the place. Unfortunately we do not have nightly builds for windows yet

**Comment by valdecyralves** [comment]
Oh ok, we have it running in Windows and that's where I found the issue.
