### ISSUE TITLE
Invalid Encoding in get_flows_data.lua

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1290]
As shown below, invalid (label field) encoding (in bold) prevents proper HTML anchors to be shown in flow_stats.lua and thus to show flow information

```
{
	"currentPage": 1,
	"data": [{
			"key": "363276186",
			"column_key": "<A HREF='**/lua/flow_details.lua?flow_key=363276186&label=LUCAS-IMAC:17500 &lt;-&gt; 10.211.55.255:17500**'><span class='label label-info'>Info</span></A>",
			"column_client": "<A HREF='/lua/host_details.lua?host=10.211.55.2' data-toggle='tooltip' title='LUCAS-IMAC' >LUCAS-IMAC</A>:<A HREF='/lua/port_details.lua?port=17500'>17500</A>",
......
	],
	"perPage": 10,
	"sort": [
		["column_", "desc"]
	],
	"totalRows": 1
}
```

**Comment by emanuele-f** [comment]
I've tried to put the `/lua/flow_details.lua?flow_key=363276186&label=LUCAS-IMAC:17500 &lt;-&gt; 10.211.55.255:17500` string into the label field sent via ajax but the page loads correctly. Can you provide some more information please?

**Comment by simonemainardi** [comment]
Tried both with Chrome and Safari but the issue is not reproducible. Also pushed unexpected unicode chars in the json reply but nothing breaks in the html.

Please, reopen with extra details to reproduce if necessary.

**Comment by lucaderi** [comment]
Not quite so. In order to overcome encoding issues, chars like hyphen have been removed from the names. In essence the bug does not show up, but the solution used is not optimal

<img width="170" alt="screen shot 2017-07-18 at 19 15 39" src="https://user-images.githubusercontent.com/4493366/28330348-887f2504-6bed-11e7-9f9a-a514f643bbbe.png">
<img width="197" alt="screen shot 2017-07-18 at 19 15 28" src="https://user-images.githubusercontent.com/4493366/28330347-887d11e2-6bed-11e7-88c2-a3a70556c4ce.png">

**Comment by simonemainardi** [comment]
thanks for reporting:

Now:

![image](https://user-images.githubusercontent.com/3397663/28712702-6fd3effc-738c-11e7-849a-91a38ad673c5.png)

![image](https://user-images.githubusercontent.com/3397663/28712722-7e1c42ee-738c-11e7-89a9-26b78d55ed2a.png)
