### ISSUE TITLE
Ntopng gets terminated by SIGKILL

### ISSUE THREAD

**Issue by ieasydevops** [ntop/ntopng#1292]
hi， ntopng team

  I met a serios problem , whic blocked me for a long time, any one who can help me ? thanks very much .    
    When i started the ntopng server, whatever the version  ( 2.5 or 3.0 ), 
, it can only  last for a frew minutes, and then  was killed. ( it looks like is the os-kernal killed it)   but I cannot find any useful infomation to location the problem.
   
 the detail info as follows:    

 the gdb info: 
 **********************************************
 
 Starting program: /data/unf/ntopng/ntopng
[Thread debugging using libthread_db enabled]
05/Jun/2017 17:54:25 [Ntop.cpp:1359] Setting local networks to 127.0.0.0/8
05/Jun/2017 17:54:25 [Redis.cpp:109] Successfully connected to redis 127.0.0.1:6379@0
05/Jun/2017 17:54:26 [HostPools.cpp:65] Host Pools Available: 4
05/Jun/2017 17:54:26 [HostPools.cpp:65] Host Pools Available: 4
Detaching after fork from child process 97765.
05/Jun/2017 17:54:26 [NetworkInterface.cpp:227] Executing ethtool -K em1 gro off gso off tso off
05/Jun/2017 17:54:26 [PcapInterface.cpp:86] Reading packets from interface em1...
05/Jun/2017 17:54:26 [Ntop.cpp:1464] Registered interface em1 [id: 0]
05/Jun/2017 17:54:27 [HostPools.cpp:65] Host Pools Available: 4
Detaching after fork from child process 97766.
05/Jun/2017 17:54:27 [NetworkInterface.cpp:227] Executing ethtool -K em2 gro off gso off tso off
05/Jun/2017 17:54:27 [PcapInterface.cpp:86] Reading packets from interface em2...
05/Jun/2017 17:54:27 [Ntop.cpp:1464] Registered interface em2 [id: 1]
05/Jun/2017 17:54:27 [HostPools.cpp:65] Host Pools Available: 4
Detaching after fork from child process 97767.
05/Jun/2017 17:54:27 [NetworkInterface.cpp:227] Executing ethtool -K em3 gro off gso off tso off
05/Jun/2017 17:54:27 [PcapInterface.cpp:86] Reading packets from interface em3...
05/Jun/2017 17:54:27 [Ntop.cpp:1464] Registered interface em3 [id: 2]
05/Jun/2017 17:54:27 [HostPools.cpp:65] Host Pools Available: 4
05/Jun/2017 17:54:27 [PcapInterface.cpp:86] Reading packets from interface lo...
05/Jun/2017 17:54:27 [Ntop.cpp:1464] Registered interface lo [id: 3]
05/Jun/2017 17:54:27 [main.cpp:250] PID stored in file /var/run/ntopng.pid
05/Jun/2017 17:54:27 [HTTPserver.cpp:758] HTTPS Disabled: missing SSL certificate /data/unf/ntopng/httpdocs/ssl/ntopng-cert.pem
05/Jun/2017 17:54:27 [HTTPserver.cpp:760] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
05/Jun/2017 17:54:27 [Utils.cpp:371] User changed to nobody
[New Thread 0x7ffff6552700 (LWP 97768)]
[New Thread 0x7ffff5b51700 (LWP 97769)]
[New Thread 0x7ffff5150700 (LWP 97770)]
[New Thread 0x7fffeffff700 (LWP 97771)]
[New Thread 0x7fffef5fe700 (LWP 97772)]
[New Thread 0x7fffeebfd700 (LWP 97773)]
05/Jun/2017 17:54:27 [HTTPserver.cpp:814] Web server dirs [/data/unf/ntopng/httpdocs][/data/unf/ntopng/scripts]
05/Jun/2017 17:54:27 [HTTPserver.cpp:817] HTTP server listening on port(s) 3000
05/Jun/2017 17:54:27 [main.cpp:311] Working directory: /var/tmp/ntopng
05/Jun/2017 17:54:27 [main.cpp:313] Scripts/HTML pages directory: /data/unf/ntopng
05/Jun/2017 17:54:27 [Ntop.cpp:307] Welcome to ntopng x86_64 v.3.0.170605 - (C) 1998-17 ntop.org
05/Jun/2017 17:54:27 [Ntop.cpp:312] Built on CentOS release 6.9 (Final)
05/Jun/2017 17:54:27 [PeriodicActivities.cpp:56] Started periodic activities loop...
[Thread 0x7fffef5fe700 (LWP 97772) exited]
[Thread 0x7fffeffff700 (LWP 97771) exited]
[Thread 0x7ffff5150700 (LWP 97770) exited]
[Thread 0x7ffff5b51700 (LWP 97769) exited]
[Thread 0x7ffff6552700 (LWP 97768) exited]
[Thread 0x7fffeebfd700 (LWP 97773) exited]

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
Missing separate debuginfos, use: debuginfo-install glib2-2.28.8-9.el6.x86_64 krb5-libs-1.10.3-65.el6.x86_64 libcom_err-1.41.12-23.el6.x86_64 libgcc-4.4.7-18.el6.x86_64 libidn-1.18-2.el6.x86_64 libstdc++-4.4.7-18.el6.x86_64 nspr-4.13.1-1.el6.x86_64 openldap-2.4.40-16.el6.x86_64 openssl-1.0.1e-57.el6.x86_64
(gdb) q
 

****************************************************

tail -f /var/log/messages
Jun  5 17:53:58 localhost root: 2017-06-05 17:53:58:root:root     pts/0        2017-06-05 17:29 (10.204.57.246):10.204.57.178:kill -9 92961
Jun  5 17:54:05 localhost root: 2017-06-05 17:54:05:root:root     pts/0        2017-06-05 17:29 (10.204.57.246):10.204.57.178:ps -ef | grep ntopng
Jun  5 17:54:10 localhost root: 2017-06-05 17:54:10:root:root     pts/0        2017-06-05 17:29 (10.204.57.246):10.204.57.178:kill -9 97501
Jun  5 17:54:11 localhost root: 2017-06-05 17:54:11:root:root     pts/0        2017-06-05 17:29 (10.204.57.246):10.204.57.178:ps -ef | grep ntopng
Jun  5 17:54:13 localhost root: 2017-06-05 17:54:13:root:root     pts/0        2017-06-05 17:29 (10.204.57.246):10.204.57.178:ll
Jun  5 17:54:14 localhost root: 2017-06-05 17:54:14:root:root     pts/0        2017-06-05 17:29 (10.204.57.246):10.204.57.178:ls
Jun  5 17:54:15 localhost root: 2017-06-05 17:54:15:root:root     pts/0        2017-06-05 17:29 (10.204.57.246):10.204.57.178:ll
Jun  5 17:54:26 localhost kernel: Loading kernel module for a network device with CAP_SYS_MODULE (deprecated).  Use CAP_NET_ADMIN and alias netdev-dummy instead
Jun  5 17:54:26 localhost kernel: Loading kernel module for a network device with CAP_SYS_MODULE (deprecated).  Use CAP_NET_ADMIN and alias netdev-dummy instead
Jun  5 17:56:07 localhost root: 2017-06-05 17:56:07:root:root     pts/0        2017-06-05 17:29 (10.204.57.246):10.204.57.178:sudo gdb void

**************  tail -f /var/log/dmesg **************************************
platform microcode: firmware: requesting intel-ucode/06-4f-01
microcode: CPU39 sig=0x406f1, pf=0x1, revision=0xb00001e
platform microcode: firmware: requesting intel-ucode/06-4f-01
Microcode Update Driver: v2.00 <tigran@aivazian.fsnet.co.uk>, Peter Oruba
udev: renamed network interface eth1 to em2
udev: renamed network interface eth3 to em4
EXT4-fs (sda2): mounted filesystem with ordered data mode. Opts:
EXT4-fs (sda6): mounted filesystem with ordered data mode. Opts:
EXT4-fs (sda3): mounted filesystem with ordered data mode. Opts:
Adding 10485756k swap on /dev/sda5.  Priority:-1 extents:1 across:10485756k
****************************************************

and the mem info 

free -g
             total       used       free     shared    buffers     cached
Mem:           189        115         73          0          0         65
-/+ buffers/cache:         49        139
Swap:            9          0          9

uname -a

Linux localhost.localdomain 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by emanuele-f** [comment]
Any hint from `systemctl status ntopng`? Can you check if there is another running ntopng instance?

**Comment by ieasydevops** [comment]
i certainly sure there is only one ntopng instance

**Comment by emanuele-f** [comment]
What's your ntopng configuration used? If I understand well the output of `free -g`, you have 115 GB of main memory available in your system?? Can you track the memory usage of ntopng?

**Comment by simonemainardi** [comment]
it looks like there's someone explicitly killing ntopng:

**Comment by simonemainardi** [comment]
see your output:


Jun 5 17:53:58 localhost root: 2017-06-05 17:53:58:root:root pts/0 2017-06-05 17:29 (10.204.57.246):10.204.57.178:kill -9 92961
Jun 5 17:54:05 localhost root: 2017-06-05 17:54:05:root:root pts/0 2017-06-05 17:29 (10.204.57.246):10.204.57.178:ps -ef | grep ntopng
Jun 5 17:54:10 localhost root: 2017-06-05 17:54:10:root:root pts/0 2017-06-05 17:29 (10.204.57.246):10.204.57.178:kill -9 97501
Jun 5 17:54:11 localhost root: 2017-06-05 17:54:11:root:root pts/0 2017-06-05 17:29 (10.204.57.246):10.204.57.178:ps -ef | grep ntopng

**Comment by ieasydevops** [comment]
thanks very much for your so quickly response, but there's still problems .
firt of all, my host server a total of 198G RAM, and only 116G has been used,  there should be enough memory for ntopng service start.  secondly, the follow picture can prove there are no one else explicitly kill the process.

![ntopng_test](https://cloud.githubusercontent.com/assets/4316534/26785884/19a12ba0-4a37-11e7-87f3-129f93a7623c.png)

**Comment by simonemainardi** [comment]
if I look at your traces I can see that the sig KILL is arriving from a root user, and not from the kernel. It also looks like that right after the kill, the same user tries to see if the process is still alive.

Type 'w' and make sure there's no one (apart from you) in the system.

**Comment by emanuele-f** [comment]
I suspect it is related to nohup, do you press ctrl+c after running nohup?

Can you run ntopng as a service (and manage with systemctl) in order to avoid any kind of terminal related problems?

**Comment by ieasydevops** [comment]
i do not press ctrl+c ,  and I suspect that's the reason:
localhost kernel: Loading kernel module for a network device with CAP_SYS_MODULE (deprecated).  Use CAP_NET_ADMIN and alias netdev-dummy instead

I  found an  answer but   without check:
https://bbs.archlinux.org/viewtopic.php?id=143657 

        you're using an application that uses CAP_SYS_MODULE to insert a module into the kernel, Find out which application it is and report a bug; or patch the application to use CAP_NET_ADMIN and alias netdev- instead
     
 The question is , how can i patch the ntopng to use CAP_NET_ADMIN and alias netdev- instead?
 maybe i should have a try

**Comment by emanuele-f** [comment]
Sorry I have no hint on the CAP_SYS_MODULE but I think it is not something related to ntopng. What I suggest you is to try to start ntopng as a service via `service/systemctl/whatever` and see if still it gets killed

**Comment by emanuele-f** [comment]
@meixinyun have you tried what I suggested above?

**Comment by emanuele-f** [comment]
Yesterday I've fixed a bug which caused high memory consumption in a particular case when multiple mac addresses appeared with the same ip 89a756fb9a1bbe52b091adca5e9eb562f7d56277 . Maybe this is what affected you and caused your ntopng process to be killed. I'm closing the issue since no feedback has been received. Please reopen if necessary.
