### ISSUE TITLE
upgrading via apt-get - "Stopping PF_RING module:Stopping nProbe" none hangs

### ISSUE THREAD

**Issue by sethbeauchamp** [ntop/ntopng#1293]
Trying to upgrade via apt-get from 2.5 to current version on Debian Jessie, I get this message and it hangs indefinitely:
Stopping PF_RING module:Stopping nProbe none

I can ctrl Z out of that, and run ntopng -V and it shows v 3.1 now.  Unsure if the installation is fine or not, but the web does seem to continue working.

**Comment by sethbeauchamp** [comment]
using "modprobe -r pf_ring" helps this get futher. Now it hangs at...
Synchronizing state for nprobe.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d nprobe defaults
Executing /usr/sbin/update-rc.d nprobe enable
(Re)Starting nprobe...
Stopping nProbe none

**Comment by emanuele-f** [comment]
Note: a workaround is to manually stop/kill nprobe and only then perform the update

**Comment by emanuele-f** [comment]
@cardigliano do you think this is related to pf_ring package or module?

**Comment by cardigliano** [comment]
It seems it is not related to pf_ring, but more details are needed. Please try stopping the nprobe service using the init.d script, check if it fails, and in case run it with bash -x to get a full trace. The same for pf_ring.

**Comment by lucaderi** [comment]
@GCM707 Any news?

**Comment by emanuele-f** [comment]
I can reproduce the issue on Centos 7. When updating nprobe, the system becomes unreachable after the `Running transaction` message. 

```
(1/3): nprobe-8.1.170615-5788.x86_64.rpm                                          | 1.6 MB  00:00:02     
(2/3): ntopng-3.1.170615-2928.x86_64.rpm                                          | 5.4 MB  00:00:04     
(3/3): pfring-6.7.0-1273.x86_64.rpm                                               | 1.2 MB  00:00:01     
---------------------------------------------------------------------------------------------------------
Total                                                                    1.9 MB/s | 8.2 MB  00:00:04     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
```

I previously tried to execute `bash -x /etc/init.d/nprobe stop` but the command blocks until I ctrl+c it. Maybe this is why the update hangs: the pf_ring module is unloaded but nprobe hangs and it stays unloaded. This is the output:

```
+ _SYSTEMCTL_SKIP_REDIRECT=yes
+ PARAM_INTERFACE_NAME=
+ logger 'nprobe stop '
+ case "$1" in
+ stop_nprobe ''
+ INTERFACE_NAME=
+ '[' '!' -d /etc/nprobe ']'
+ '[' -z ']'
++ find /etc/nprobe/ -name '*.start'
++ wc -l
+ NUM_TO_START=1
+ '[' 1 -eq 0 ']'
++ /bin/ls /etc/nprobe
++ /bin/grep .start
++ /bin/sed -e s/-/%/
++ /usr/bin/cut -d % -f 2
++ /bin/sed -e 's/\(.*\)\.start/\1/'
+ NETDEVICES=none
+ for E in '$NETDEVICES'
+ stop_nprobe_eth none
+ INTERFACE_NAME=none
+ echo 'Stopping nProbe none'
Stopping nProbe none
+ ARRAY_PID=()
+ '[' -f /etc/nprobe/nprobe-none.conf ']'
+ '[' -f /etc/nprobe/nprobe-none.group ']'
++ cat /etc/nprobe/nprobe-none.conf
++ grep @#ID
++ wc -l
+ NUM=0
+ '[' '!' -z 0 ']'
+ '[' 0 -gt 0 ']'
+ NUM=1
+ NUM_ARRAY=
++ seq 0 0
+ for ID in '`seq 0 $[$NUM-1]`'
+ NUM_ARRAY='0 '
+ NUM_ARRAY=($NUM_ARRAY)
+ NUM=1
++ seq 0 0
+ for i in '`seq 0 $[$NUM-1]`'
+ ID=0
+ '[' '!' -f /tmp/nprobe-none@0.conf ']'
++ cat /tmp/nprobe-none@0.conf
++ grep -E '^\-g=|^\-\-pid\-file='
++ cut -d = -f 2
+ PID_FILE=
+ '[' -f ']'
++ cat
```

**Comment by emanuele-f** [comment]
@cardigliano this is my fix for /etc/init.d/nprobe:

replace all the
`if [ -f "${PID_FILE}" ]; then`
with
`if [ ! -z "${PID_FILE}" -a -f "${PID_FILE}" ]; then`

**Comment by philimnorden** [comment]
Same problem on ubuntu 16.04LTS:
 Doesn't matter if i manually shutdown/kill nprobe before i run upgrade.
 apt-get upgrade:
```
Möchten Sie fortfahren? [J/n] j
nprobe (8.0.170619-5786) wird eingerichtet ...
Rebuilding ld cache...
Adding the nprobe startup script
Synchronizing state of nprobe.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable nprobe
(Re)Starting nprobe...
Stopping nProbe none
...
```

I tried your changes in /etc/init.d/nprobe but it does not work:
```
root@MYHOST:~# service nprobe stop
root@MYHOST:~# service nprobe status
● nprobe.service - Start/stop nprobe program
   Loaded: loaded (/etc/systemd/system/nprobe.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Mi 2017-06-21 08:52:44 CEST; 4s ago
  Process: 2440 ExecStop=/etc/init.d/nprobe stop (code=exited, status=0/SUCCESS)
 Main PID: 2012 (code=exited, status=0/SUCCESS)

Jun 21 08:48:12 MYHOSTsystemd[1]: Starting Start/stop nprobe program...
Jun 21 08:48:12 MYHOSTnprobe[1950]: Starting nProbe none
Jun 21 08:48:12 MYHOSTsystemd[1]: Started Start/stop nprobe program.
Jun 21 08:52:33 MYHOSTsystemd[1]: Stopping Start/stop nprobe program...
Jun 21 08:52:33 MYHOSTnprobe[2440]: Stopping nProbe none
Jun 21 08:52:33 MYHOSTnprobe[2440]: /etc/init.d/nprobe: Zeile 197: [: -gt: Einstelliger (unärer) Operator erwartet.
Jun 21 08:52:33 MYHOSTnprobe[2440]: Unable to stop nProbe none: invalid pid [][]
Jun 21 08:52:44 MYHOSTsystemd[1]: Stopped Start/stop nprobe program.
```

Line 197 /etc/init.d/nprobe ( i didn't changed anything there)
`if [ $PID -gt 0 ]; then`

**Comment by ValentinaViscarelli** [comment]
@philimnorden 
@emanuele-f 
Could you please attach your nprobe file configuration?

Please run this command and report the output:
cat /etc/nprobe/nprobe-none.conf

Thanks

**Comment by philimnorden** [comment]
```
-i eno2
--collector-port 9999
--zmq tcp://127.0.0.1:9876

```

**Comment by ValentinaViscarelli** [comment]
@philimnorden 
When you write the configuration into file you have to use '=' character and please don't forget -g parameter (with the service it is mandatory). So change your configuration like this and give it a try. 
Let me know if it works.
Thanks.

 -i=eno2
--collector-port=9999
--zmq=tcp://127.0.0.1:9876
-g=/var/run/nprobe-none.pid

**Comment by emanuele-f** [comment]
@ValentinaViscarelli I also missed the -g parameter. But I think the init script should handle this

**Comment by ValentinaViscarelli** [comment]
@emanuele-f 
I will fix the script for not getting a problem if -g parameter is missing but anyway without pid file you will not able to stop nprobe instances.

**Comment by emanuele-f** [comment]
Ok, thank you

**Comment by philimnorden** [comment]
Worked like a charm, thank you.

**Comment by ValentinaViscarelli** [comment]
Fixed init.d script in order to avoid errors when you don't have -g parameter set in nprobe configuration.
