### ISSUE TITLE
Graphs in reports not showing in ntopng Pro [Small Business Edition] v.3.0.170605

### ISSUE THREAD

**Issue by stebbo63** [ntop/ntopng#1295]
Hello,

after upgrading to v3.0 most of the individual graphs in the Traffic Report do not show.

Click Traffic Report.  The graphs will show if you select 1h and 1d timeframe, but not if you select 1w.

Cheers,
Chris.

![image](https://cloud.githubusercontent.com/assets/16530595/26805661/4cb23fc6-4a90-11e7-9931-2aa5ebaee37d.png)

**Comment by emanuele-f** [comment]
Hi, can you open the browser inspector to se if there are javascript errors?

**Comment by stebbo63** [comment]
Hi Emanuele,

I have attached a screenshot.  Hope this is what you were after.

Cheers,
Chris.
![image](https://user-images.githubusercontent.com/16530595/26912295-c1cf0538-4c56-11e7-88c5-635cacdd8063.png)

**Comment by emanuele-f** [comment]
Can you afford to reset your existing graphs/report data? You will still retain configuration and mysql data, if any. If that's ok, please stop ntopng, flush your ntopng data directory (usually /var/tmp/ntopng) and restart ntopng

**Comment by simonemainardi** [comment]
before resetting everything, I would try with a js reload (hit ctrl+shift+r).

Do the other parts of the report work? That is, the stacked applications chart, top talkers, top ases, etc.?

**Comment by stebbo63** [comment]
Hi Simone,

the reports work properly if I ask for a 1hr or 1d timeframe, as shown here.
![image](https://user-images.githubusercontent.com/16530595/26999664-93c95dd6-4de2-11e7-8167-8eb4587810b6.png)

However, if I ask for a 1w timeframe, most of the report is blank.  No graphs or piecharts.  The "network interfaces" and "applications" are the only two charts that display in the 1w timeframe.
![image](https://user-images.githubusercontent.com/16530595/26999677-efdab840-4de2-11e7-97c7-42ef6303b2ef.png)

Cheers,
Chris.

**Comment by emanuele-f** [comment]
In the past, this problem happened when users changed their data retention times from the settings, and this is why we removed that settings. Do you remember if you changed such a setting in the past?

If this is the case, you should remove the files which hold anomal retention times, and that should fix your graphs. So, if purging all graph data is not a viable solution, you should tell us the left column labels of the graphs which do not work, so that we can tell you which files to remove to fix the problem.

**Comment by stebbo63** [comment]
An initial check of build 170616 suggests that this issue might be resolved. Not completely sure as I've only been collecting data for a little while (after other isues).  Will check back in a week or so and report back.

Cheers,
Chris.

**Comment by simonemainardi** [comment]
thanks for reporting
