### ISSUE TITLE
Invalid number of flows/hosts reported in footer

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1296]
When a user has restrictions (e.g. hosts from network 192.168.0.0/24) and no flows can be displayed, in the flows/hosts menu there are no entries and that's correct. Unfortunately the footer reports a number of hosts/flows that does not take into account the network restrictions.

![screen shot 2017-06-06 at 00 26 57](https://cloud.githubusercontent.com/assets/4493366/26806039/26dc7a1e-4a4f-11e7-8982-f6e8b1a80360.png)

**Comment by emanuele-f** [comment]
Fixing flows/hosts counters would require computing them on a per-network basis. Maybe we can simply hide such information if the user has network restrictions.

**Comment by lucaderi** [comment]
In case there is a host restriction, on footer compute dynamically the number of hosts that used can see and omit any other information.
