### ISSUE TITLE
The x-axis (time) of the graphs is not clearly divided

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#1298]
In this screenshot 

![ntopng_chart_view](https://user-images.githubusercontent.com/14093378/26872071-88d0143e-4b75-11e7-99cd-91254ef9b238.png)

the vertical lines over the day strings are not fixed at 00:00 as expected in this kind of graph.
This behavior could cause some misunderstanding.

In instance, into the screenshot, it seems that the traffic started in the last hours of the "Jun 4" night while, in reality, it started in the "Jun 5" morning (4:00 AM).

Thanks...

**Comment by emanuele-f** [comment]
Hi, you are right, this is something weird. Thank you for reporting.

**Comment by simonemainardi** [comment]
All the vertical bars in 1-week charts are aligned and equals the current time 1  day ago, 2 days ago and so on.

We believe this is the proper approach to apply x-axis tick marks on weekly charts as, by clicking "1w", the user actually means a *trailing* 1 week period from now.

We may change this in the future as we are evaluating new chart libraries but for now we believe the choice made is ok.
