### ISSUE TITLE
Report bug on function Maps

### ISSUE THREAD

**Issue by balmha** [ntop/ntopng#1299]
In today I was analyzing the traffic of my network and I ran into a problem when I try to access the maps function. I think it is due to the lack of an API key that was implemented on June 22, 2016 in the Google Maps API. Sorry for my english, i'm argentinian, regards!
http://subefotos.com/ver/?673dbf58e6669d1cf0e52926d3cdd211o.png

**Comment by emanuele-f** [comment]
Hi, are you using ntop? Please note that we do not support ntop any more, can you update to ntopng?

**Comment by balmha** [comment]
Hi, thanks for the information, I had no idea that there was no more support, greetings!



________________________________
De: Emanuele Faranda <notifications@github.com>
Enviado: miércoles, 07 de junio de 2017 09:48 a.m.
Para: ntop/ntopng
Cc: balmha; Author
Asunto: Re: [ntop/ntopng] Report bug on function Maps (#1299)


Hi, are you using ntop? Please note that we do not support ntop any more, can you update to ntopng?

**Comment by emanuele-f** [comment]
ntopng is an improved version of ntop, please update to get a bunch of new functionalities :)
