### ISSUE TITLE
Unknown agrgegation value none

### ISSUE THREAD

**Issue by hgpit** [ntop/ntopng#1305]
Hi,

When starting/restarting ntopng-3.1.170608-2898.x86_64 and ntopng-3.1.170605-2876.x86_64 (don't know about previous versions) we see this error:

```
[root@svr-h003349 ~]# systemctl status ntopng
● ntopng.service - Start/stop ntopng program
   Loaded: loaded (/etc/systemd/system/ntopng.service; disabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-06-08 16:18:55 BST; 2s ago
  Process: 5208 ExecStop=/etc/init.d/ntopng stop (code=exited, status=0/SUCCESS)
  Process: 5264 ExecStart=/etc/init.d/ntopng start (code=exited, status=0/SUCCESS)
 Main PID: 5278 (ntopng)
   CGroup: /system.slice/ntopng.service
           └─5278 /usr/bin/ntopng /etc/ntopng/ntopng.conf

Jun 08 16:18:54 svr-h003349.domain.local systemd[1]: Starting Start/stop ntopng program...
Jun 08 16:18:54 svr-h003349.domain.local ntopng[5278]: **[NetworkInterface.cpp:368] ERROR: Unknown agrgegation value none**
Jun 08 16:18:55 svr-h003349.domain.local ntopng[5264]: Starting ntopng: [  OK  ]
Jun 08 16:18:55 svr-h003349.domain.local systemd[1]: Started Start/stop ntopng program.
```

Doesn't appear to cause any issues we've seen yet, but thought I'd raise it.
There's also a typo in "agrgegation" :p

We are on CentOS7:
Linux svr-h003349.domain.local 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Thanks

**Comment by simonemainardi** [comment]
@hgpit do you have any particular value set for Dynamic Flow collection interfaces?

![screen shot 2017-06-09 at 11 01 47](https://user-images.githubusercontent.com/3397663/26968667-21657ade-4d03-11e7-8890-e04a6eaefd13.png)

a `redis-cli del ntopng.prefs.dynamic_flow_collection_mode` should solve the problem

**Comment by philimnorden** [comment]
I had the same error message in v.3.1.170606 and the command above solved it.

**Comment by emanuele-f** [comment]
Thank you for reporting. @hgpit please use the suggested command above. Reopen if necessary
