### ISSUE TITLE
ntopng loses MySQL connection

### ISSUE THREAD

**Issue by mahescho** [ntop/ntopng#1306]
I observe this since I use ntopng, for about 2 month by now. It crashes on a irregular base. I hoped that this will get better after some updates but it does not. Ntopng never survived for longer than a week. The process just dies with the following log entries:

`09/Jun/2017 00:00:05 [MySQLDB.cpp:613] Disconnected from MySQL for interface tcp://127.0.0.1:5557...
09/Jun/2017 00:00:05 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface tcp://127.0.0.1:5557...
09/Jun/2017 00:00:05 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntop] for interface tcp://127.0.0.1:5557
09/Jun/2017 00:00:05 [MySQLDB.cpp:613] Disconnected from MySQL for interface tcp://127.0.0.1:5556...
09/Jun/2017 00:00:05 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface tcp://127.0.0.1:5556...
09/Jun/2017 00:00:05 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntop] for interface tcp://127.0.0.1:5556`

Not to talk about that the JavaScript web interface constanly crashes in Goolge Crhome. It survives for 1 or 2 hours at maximum for me. As a reload fixes this it is not to important.

**Comment by simonemainardi** [comment]
@mahescho mysql re-connections are normal as MySQL connections time out after a configurable amount of time (default 8 hours) so ntopng have to periodically reconnect (https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_interactive_timeout).

Specifically, in your case, ntopng reconnects at midnight for the periodic database cleanup operations. This is normal.

Not sure why you say "it crashes". What do you mean? Also, are you using version 3.0 or 3.1?

Regarding the JavaScript issue, @emanuele-f is investigating it.

**Comment by mahescho** [comment]
There is simply no NtopNG process. No further messages. The re connection message is the last in the log. I use: ntopng Pro [Small Business Edition] v.3.1.170608

**Comment by emanuele-f** [comment]
For the chrome issue, I've done sone tests for issue #1300 but cannot actually say if it's an ntopng problem or a chrome problem. Please check out these things:
- you should have the latest chrome version
- you can open the chrome task manager to analyze the memory usage
- if possible, try with another browser (e.g. firefox) and see if it crashes too

**Comment by simonemainardi** [comment]
@mahescho can you generate a core dump and upload it along with the binary (instructions at: http://www.ntop.org/support/faq/how-to-report-a-bug-on-ntop-apps/)? That will help us in understanding the issue

**Comment by mahescho** [comment]
@emanuele-f 

> you should have the latest chrome version

I do.

> you can open the chrome task manager to analyze the memory usage

I will.

> if possibly, try with another browser (e.g. firefox) and see if it crashes too

Done so this morning, it's running now with Firefox for about 2,5h - will report my experiences.

**Comment by mahescho** [comment]
@simonemainardi  As NtopNG runs as a Debian Linux Systemd service this:

https://pve.proxmox.com/wiki/Enable_Core_Dump_systemd

may be the better solution. Do you agree?

**Comment by simonemainardi** [comment]
@mahescho yes.

BTW, to make sure core generation works (without having to wait a day or so), just send the process a SIG SEGV (e.g., sudo kill -SEGV <process pid>) and check for the existence of the core file

**Comment by mahescho** [comment]
Thanks for the tip. It works, but I'm unable to stat NtopNG after the kill again. I get:

`# systemctl status ntopng
● ntopng.service - Start/stop ntopng program
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled)
   Active: active (exited) (Result: core-dump) since Fr 2017-06-09 12:48:56 CEST; 4min 37s ago
  Process: 957 ExecStart=/etc/init.d/ntopng start (code=exited, status=0/SUCCESS)
 Main PID: 986 (code=dumped, signal=SEGV)

Jun 09 12:48:54 ntop logger[966]: ntopng start
Jun 09 12:48:55 ntop ntopng[986]: [NetworkInterface.cpp:368] ERROR: Unknown agrgegation value none
Jun 09 12:48:55 ntop ntopng[986]: [NetworkInterface.cpp:368] ERROR: Unknown agrgegation value none
Jun 09 12:48:56 ntop ntopng[957]: Starting ntopng:.
Jun 09 12:48:56 ntop systemd[1]: Started Start/stop ntopng program.
Jun 09 12:51:50 ntop systemd[1]: ntopng.service: main process exited, code=dumped, status=11/SEGV
Jun 09 12:52:09 ntop systemd[1]: Started Start/stop ntopng program.
Jun 09 12:53:26 ntop systemd[1]: Started Start/stop ntopng program.
`

A reboot fixes this ...

**Comment by mahescho** [comment]
@emanuele-f 
> you can open the chrome task manager to analyze the memory usage

![auswahl_057](https://user-images.githubusercontent.com/5101589/26974707-d94f3680-4d1c-11e7-85cd-d1a8fad2987e.png)

Frirefox started at the same time is still up and running.

**Comment by emanuele-f** [comment]
Hi, were you able to generate the core file?

From the task manager, it seems your ntopng instance is really taking up a lot of memory. When you first start chrome, does it already take GB of memory at startup? Can you describe your monitoring setup, how many interfaces are you monitoring?

One thing you can try is to pass an option to chrome to increase the available size. `--js-flags="--max_old_space_size=8192"`.

Can you provide us a web access to your ntopng instance to debug the issue?

**Comment by mahescho** [comment]
No crash by now, so no core files.

It is an internal instance. I can not provide acces. Firefox currently runns the web interface since Friday without any problem ... I will try chrome with "max_old_space_size"

**Comment by emanuele-f** [comment]
Ok, the `max_old_space_size` flag is not really a solution to the actual problem, but it should help

**Comment by simonemainardi** [comment]
as you are no longer experiencing any crash, the issue can be considered as solved. Shall you experience it again, please reopen and upload both the core dump and the binary of ntopng

**Comment by mahescho** [comment]
No problem but just FYI: Firefox stopped working after about 5 days with a non responding script: http://192.168.100.21:3000/js/d3.v3.js:341

**Comment by emanuele-f** [comment]
@mahescho thank you for this information. If these problems are related to the d3.js component than maybe an update of the library would solve them. But the update would probably break our gui and some work must be done to fix and test it. This is not one of our priorities right now, but again thank you
