### ISSUE TITLE
Network load displayed incorrectly

### ISSUE THREAD

**Issue by MajesticFalcon** [ntop/ntopng#1309]
The traffic seems to be about right. I am wondering if upscaling needs to be applied for graphs and numbers to be reporting correctly. I have already specified local networks

![sflow-network-load-wrong](https://user-images.githubusercontent.com/8593209/26981518-0ee413b4-4cfb-11e7-86d3-331ec470717a.PNG)

**Comment by emanuele-f** [comment]
Hi, please describe your monitoring setup

**Comment by MajesticFalcon** [comment]
Ubuntu 16.01 LTS
Ntopng 3.0 Licensed
Nprobe Licensed
Local networks setup

**Comment by emanuele-f** [comment]
How is your nprobe receiving flows? Can you post your ntopng conf and nprobe config please?

**Comment by MajesticFalcon** [comment]
nProbe Sflow. Both services are installed on the same server
nprobe --collector-port 6343 --zmq tcp://127.0.0.1:5556
ntopng -i tcp://127.0.0.1:5556 -d /var/tmp -w 80 -m .....

**Comment by simonemainardi** [comment]
@MajesticFalcon if you are using nProbe to collect sFlow, add nProbe option --upscale-traffic that will adjust the traffic on the basis of sFlow sampling rates.

All charts will be adjusted consequently.

Keep in mind that when nProbe is used in collector mode, interface charts (i.e., interface speed) give you statistics on the processed traffic (e.g., number of sFlow packets received).

**Comment by MajesticFalcon** [comment]
@simonemainardi What about the two clouds for upload and download? Why is upload still 0 even after making the upscale change.

**Comment by MajesticFalcon** [comment]
@simonemainardi Also, if ran as cli --upscale-traffic works. If used in the config, --upscale-traffic is not a recognized config option

**Comment by simonemainardi** [comment]
@MajesticFalcon make --upscale-traffic is for nProbe and is only available in the latest stable/devs
