### ISSUE TITLE
ntopng suddenly went down

### ISSUE THREAD

**Issue by javeperez** [ntop/ntopng#1310]
hi guys, im having problem with my ntopng (community edition) it suddenly went down then all my data was gone like, traffic data and other stuff was gone and back to zero. How can i fix this? thank you

**Comment by emanuele-f** [comment]
What kind of data do you mean? The graphs data? Please post your ntopng configuration

**Comment by javeperez** [comment]
Hi sir emanuele

Sorry for issue title,, im having trouble with this 
![ntop](https://user-images.githubusercontent.com/29380048/27089629-8878b5e6-508d-11e7-8ce3-d5659a085547.PNG)

The uptime always resets and when i reboot my pfsense the data also was gone

Thank You

**Comment by emanuele-f** [comment]
Hi, that kind of data is not intended to be permanent within ntopng. Even if you don't reboot ntopng, hosts and flows will be removed from the view when they "expire". We also provide historical data, which means that you can browse an host data as graphs in the past. Please have a look at these links: 

http://www.ntop.org/ntopng/exploring-historical-data-using-ntopng/
http://www.ntop.org/ntopng/exploring-historical-data-using-ntopng-part-2/

Please also note that you are running an outdate ntopng within pfsense. You should ask pfsense package maintainers to update the package as a new stable 3.0 version is now available.
