### ISSUE TITLE
Ntopng v3 stops collecting data and the dashboard stops responding

### ISSUE THREAD

**Issue by Artapel** [ntop/ntopng#1311]
Hi Guys

We updated to ntopng.x86_64 3.1.170612-2915, since then ntop will stop collecting data about and hour or two after start/restart. The dashboard also stops responding. After a while Chrome will give me a 

> This site can’t be reached
> x.x.x.x refused to connect.
> ERR_CONNECTION_REFUSED

doing a _systemctl restart ntopng_ restores ntop to a working state but only for an hour or two.
Please note that ive got Bandwidthd and munin running on this server aswell and they work perfectly, their web interfaces also works perfectly.

**After a restart i get the following** 

> systemctl status ntopng -n 20 -l
> ● ntopng.service - Start/stop ntopng program
>    Loaded: loaded (/etc/systemd/system/ntopng.service; disabled; vendor preset: disabled)
>    Active: active (running) since Tue 2017-06-13 11:33:54 SAST; 2s ago
>   Process: 8297 ExecStop=/etc/init.d/ntopng stop (code=exited, status=0/SUCCESS)
>   Process: 8321 ExecStart=/etc/init.d/ntopng start (code=exited, status=0/SUCCESS)
>  Main PID: 8328 (ntopng)
>    CGroup: /system.slice/ntopng.service
>            └─8328 /usr/bin/ntopng /etc/ntopng/ntopng.conf
> 
> Jun 13 11:33:49 monitor systemd[1]: Starting Start/stop ntopng program...
> Jun 13 11:33:54 monitor ntopng[8321]: Starting ntopng: Cannot change tcp-segmentation-offload
> Jun 13 11:33:54 monitor ntopng[8321]: Unable to start ntopng[FAILED]
> Jun 13 11:33:54 monitor systemd[1]: Started Start/stop ntopng program.

I cannot see any error or warnings on the ntopng logs

I am using Linux monitor 3.10.0-514.21.1.el7.x86_64 #1 SMP x86_64 x86_64 x86_64 GNU/Linux

**Here is my product versions after the update.**

> yum list | grep ntop
> cento.x86_64                            1.3.170612-200                 @ntop
> e1000e-zc.noarch                        3.2.7.1.1263-dkms              @ntop-noarch
> i40e-zc.noarch                          1.5.18.1263-1dkms              @ntop-noarch
> igb-zc.noarch                           5.3.3.5.1263-dkms              @ntop-noarch
> ixgbe-zc.noarch                         4.1.5.1263-dkms                @ntop-noarch
> n2disk.x86_64                           2.9.170612-4819                @ntop
> nprobe.x86_64                           8.1.170612-5785                @ntop
> ntopng.x86_64                           3.1.170612-2915                @ntop
> ntopng-data.noarch                      3.1.170612-2915                @ntop-noarch
> pfring.x86_64                           6.7.0-1263                     @ntop
> pfring-dkms.noarch                      6.7.0-1263                     @ntop-noarch
> pfring-drivers-zc-dkms.noarch           1.2-0                          @ntop-noarch
> fm10k-zc.noarch                         0.20.1.1263-dkms               ntop-noarch
> fontopia.x86_64                         1.7-1.el7                      epel
> nbox.noarch                             2.5.0-553                      ntop-noarch
> nprobes.x86_64                          8.1.170612-5785                ntop
> nscrub.x86_64                           1.0.170612-595                 ntop
> radeontop.x86_64                        1.0-1.el7                      epel

**My Startscript looks like this**

> cat /etc/ntopng/ntopng.conf
> -G=/var/tmp/ntopng.pid
> -q=
> -F="mysql;localhost;ntopng1;flows;password;"
> #--verbose
> --disable-autologout
> --dns-mode=1
> --dont-change-user
> -m="x.x.x.x (Networks Removed";
> -k=flashstart:root:password

**Comment by emanuele-f** [comment]
Hi, if you remove the -k option, can you restart it?

**Comment by Artapel** [comment]
I have done so. Unfortunate the same problem occurred  

 systemctl status ntopng -l
● ntopng.service - Start/stop ntopng program
   Loaded: loaded (/etc/systemd/system/ntopng.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-06-13 14:27:42 SAST; 53s ago
  Process: 3957 ExecStart=/etc/init.d/ntopng start (code=exited, status=0/SUCCESS)
 Main PID: 3965 (ntopng)
   CGroup: /system.slice/ntopng.service
           └─3965 /usr/bin/ntopng /etc/ntopng/ntopng.conf

Jun 13 14:27:37 -monitor systemd[1]: Starting Start/stop ntopng program...
Jun 13 14:27:41 -monitor ntopng[3957]: Starting ntopng: Cannot change tcp-segmentation-offload
Jun 13 14:27:42 -monitor ntopng[3957]: Unable to start ntopng[FAILED]
Jun 13 14:27:42 -monitor systemd[1]: Started Start/stop ntopng program.

**Comment by emanuele-f** [comment]
What about if you start ntopng manually from console like this: `sudo ntopng /etc/ntopng/ntopng.conf` ? Can you post the output you get in this way please?

**Comment by Artapel** [comment]
I have done the suggested. here is the output

> sudo ntopng /etc/ntopng/ntopng.conf
> 14/Jun/2017 12:47:39 [Ntop.cpp:1359] Setting local networks to "Networks Removed"
> 14/Jun/2017 12:47:39 [Redis.cpp:109] Successfully connected to redis 127.0.0.1:6379@0
> 14/Jun/2017 12:47:39 [NtopPro.cpp:144] [LICENSE] Read license from Redis [CAA92C69E32D0A27DB9A86B328E0BB221526471682DD30F7E6]
> 14/Jun/2017 12:47:40 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface dummy...
> 14/Jun/2017 12:47:40 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface dummy
> 14/Jun/2017 12:47:42 [MySQLDB.cpp:613] Disconnected from MySQL for interface <unknown>...
> 14/Jun/2017 12:47:43 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface enp4s0...
> 14/Jun/2017 12:47:43 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface enp4s0
> Cannot change tcp-segmentation-offload
> 14/Jun/2017 12:47:43 [NetworkInterface.cpp:227] Executing ethtool -K enp4s0 gro off gso off tso off
> 14/Jun/2017 12:47:43 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.6.7.0 interface enp4s0...
> 14/Jun/2017 12:47:43 [Ntop.cpp:1485] Registered interface enp4s0 [id: 0]
> 14/Jun/2017 12:47:45 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface lo...
> 14/Jun/2017 12:47:45 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface lo
> 14/Jun/2017 12:47:45 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.6.7.0 interface lo...
> 14/Jun/2017 12:47:45 [Ntop.cpp:1485] Registered interface lo [id: 1]
> 14/Jun/2017 12:47:46 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface enp5s0...
> 14/Jun/2017 12:47:46 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface enp5s0
> 14/Jun/2017 12:47:46 [NetworkInterface.cpp:227] Executing ethtool -K enp5s0 gro off gso off tso off
> 14/Jun/2017 12:47:46 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.6.7.0 interface enp5s0...
> 14/Jun/2017 12:47:46 [Ntop.cpp:1485] Registered interface enp5s0 [id: 2]
> 14/Jun/2017 12:47:47 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface enp1s0f0...
> 14/Jun/2017 12:47:47 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface enp1s0f0
> 14/Jun/2017 12:47:47 [NetworkInterface.cpp:227] Executing ethtool -K enp1s0f0 gro off gso off tso off
> 14/Jun/2017 12:47:47 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.6.7.0 interface enp1s0f0...
> 14/Jun/2017 12:47:47 [Ntop.cpp:1485] Registered interface enp1s0f0 [id: 3]
> 14/Jun/2017 12:47:49 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface enp2s0f0...
> 14/Jun/2017 12:47:49 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface enp2s0f0
> 14/Jun/2017 12:47:49 [NetworkInterface.cpp:227] Executing ethtool -K enp2s0f0 gro off gso off tso off
> 14/Jun/2017 12:47:49 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.6.7.0 interface enp2s0f0...
> 14/Jun/2017 12:47:49 [Ntop.cpp:1485] Registered interface enp2s0f0 [id: 4]
> 14/Jun/2017 12:47:50 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface virbr0...
> 14/Jun/2017 12:47:50 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface virbr0
> 14/Jun/2017 12:47:51 [NetworkInterface.cpp:227] Executing ethtool -K virbr0 gro off gso off tso off
> 14/Jun/2017 12:47:51 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.6.7.0 interface virbr0...
> 14/Jun/2017 12:47:51 [Ntop.cpp:1485] Registered interface virbr0 [id: 5]
> 14/Jun/2017 12:47:52 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface enp1s0f1...
> 14/Jun/2017 12:47:52 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface enp1s0f1
> 14/Jun/2017 12:47:52 [NetworkInterface.cpp:227] Executing ethtool -K enp1s0f1 gro off gso off tso off
> 14/Jun/2017 12:47:52 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.6.7.0 interface enp1s0f1...
> 14/Jun/2017 12:47:52 [Ntop.cpp:1485] Registered interface enp1s0f1 [id: 6]
> 14/Jun/2017 12:47:53 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface enp2s0f1...
> 14/Jun/2017 12:47:53 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface enp2s0f1
> 14/Jun/2017 12:47:54 [NetworkInterface.cpp:227] Executing ethtool -K enp2s0f1 gro off gso off tso off
> 14/Jun/2017 12:47:54 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.6.7.0 interface enp2s0f1...
> 14/Jun/2017 12:47:54 [Ntop.cpp:1485] Registered interface enp2s0f1 [id: 7]
> 14/Jun/2017 12:47:55 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface virbr0-nic...
> 14/Jun/2017 12:47:55 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface virbr0-nic
> 14/Jun/2017 12:47:55 [NetworkInterface.cpp:227] Executing ethtool -K virbr0-nic gro off gso off tso off
> 14/Jun/2017 12:47:55 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.6.7.0 interface virbr0-nic...
> 14/Jun/2017 12:47:55 [Ntop.cpp:1485] Registered interface virbr0-nic [id: 8]
> 14/Jun/2017 12:47:55 [main.cpp:250] PID stored in file /var/tmp/ntopng.pid
> 14/Jun/2017 12:47:55 [HTTPserver.cpp:789] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
> 14/Jun/2017 12:47:55 [HTTPserver.cpp:822] HTTP logs will be stored on /var/tmp/ntopng/ntopng_access.log
> 14/Jun/2017 12:47:55 [HTTPserver.cpp:843] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
> 14/Jun/2017 12:47:55 [HTTPserver.cpp:846] HTTP server listening on port(s) 3000
> 14/Jun/2017 12:47:55 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface enp4s0...
> 14/Jun/2017 12:47:55 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface enp4s0
> 14/Jun/2017 12:47:55 [main.cpp:311] Working directory: /var/tmp/ntopng
> 14/Jun/2017 12:47:55 [main.cpp:313] Scripts/HTML pages directory: /usr/share/ntopng
> 14/Jun/2017 12:47:55 [Ntop.cpp:307] Welcome to ntopng x86_64 v.3.1.170612 - (C) 1998-17 ntop.org
> 14/Jun/2017 12:47:55 [Ntop.cpp:312] Built on CentOS Linux release 7.3.1611 (Core)
> 14/Jun/2017 12:47:55 [PeriodicActivities.cpp:56] Started periodic activities loop...
> 14/Jun/2017 12:47:55 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface enp4s0...
> 14/Jun/2017 12:47:55 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface enp4s0
> 14/Jun/2017 12:47:55 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface enp1s0f0...
> 14/Jun/2017 12:47:55 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface enp1s0f0
> 14/Jun/2017 12:47:56 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface enp2s0f1...
> 14/Jun/2017 12:47:56 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface enp2s0f1
> 14/Jun/2017 12:47:56 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface virbr0...
> 14/Jun/2017 12:47:56 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface virbr0
> 14/Jun/2017 12:47:56 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface lo...
> 14/Jun/2017 12:47:56 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface lo
> 14/Jun/2017 12:47:56 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface virbr0-nic...
> 14/Jun/2017 12:47:56 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface virbr0-nic
> 14/Jun/2017 12:47:56 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface enp2s0f0...
> 14/Jun/2017 12:47:56 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface enp2s0f0
> 14/Jun/2017 12:47:56 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface enp5s0...
> 14/Jun/2017 12:47:56 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface enp5s0
> 14/Jun/2017 12:47:56 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface enp1s0f1...
> 14/Jun/2017 12:47:56 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface enp1s0f1
> 14/Jun/2017 12:47:57 [NtopPro.cpp:273] [LICENSE] ntopng systemId: DC3BB7F89206AAF2
> 14/Jun/2017 12:47:57 [NtopPro.cpp:284] [LICENSE] ntopng license: CAA92C69E32D0A27DB9A86B328E0BB221526471682DD30F7E6
> 14/Jun/2017 12:47:57 [NtopPro.cpp:306] [LICENSE] Maintenance is available until Wed May 16 13:54:42 2018 [336 days left]
> 14/Jun/2017 12:47:57 [Ntop.cpp:580] Adding 127.0.0.1/32 as IPv4 interface address for lo
> 14/Jun/2017 12:47:57 [Ntop.cpp:588] Adding 127.0.0.0/8 as IPv4 local network for lo
> 14/Jun/2017 12:47:57 [Ntop.cpp:580] Adding 192.168.0.18/32 as IPv4 interface address for enp4s0
> 14/Jun/2017 12:47:57 [Ntop.cpp:588] Adding 192.168.0.0/24 as IPv4 local network for enp4s0
> 14/Jun/2017 12:47:57 [Ntop.cpp:580] Adding 192.168.122.1/32 as IPv4 interface address for virbr0
> 14/Jun/2017 12:47:57 [Ntop.cpp:588] Adding 192.168.122.0/24 as IPv4 local network for virbr0
> 14/Jun/2017 12:47:57 [Ntop.cpp:607] Adding ::1/128 as IPv6 interface address for lo
> 14/Jun/2017 12:47:57 [Ntop.cpp:616] Adding ::1/128 as IPv6 local network for lo
> 14/Jun/2017 12:47:57 [Ntop.cpp:607] Adding fe80::dacb:8aff:fe75:c70b/128 as IPv6 interface address for enp4s0
> 14/Jun/2017 12:47:57 [Ntop.cpp:616] Adding fe80::dacb:8aff:fe75:c70b/64 as IPv6 local network for enp4s0
> 14/Jun/2017 12:47:57 [NetworkInterface.cpp:2046] Started packet polling on interface enp4s0 [id: 0]...
> 14/Jun/2017 12:47:57 [NetworkInterface.cpp:2046] Started packet polling on interface lo [id: 1]...
> 14/Jun/2017 12:47:57 [NetworkInterface.cpp:2046] Started packet polling on interface enp5s0 [id: 2]...
> 14/Jun/2017 12:47:57 [NetworkInterface.cpp:2046] Started packet polling on interface enp1s0f0 [id: 3]...
> 14/Jun/2017 12:47:57 [NetworkInterface.cpp:2046] Started packet polling on interface enp2s0f0 [id: 4]...
> 14/Jun/2017 12:47:57 [NetworkInterface.cpp:2046] Started packet polling on interface virbr0 [id: 5]...
> 14/Jun/2017 12:47:57 [NetworkInterface.cpp:2046] Started packet polling on interface enp1s0f1 [id: 6]...
> 14/Jun/2017 12:47:57 [NetworkInterface.cpp:2046] Started packet polling on interface enp2s0f1 [id: 7]...
> 14/Jun/2017 12:47:57 [NetworkInterface.cpp:2046] Started packet polling on interface virbr0-nic [id: 8]...

I am monitoring now to see when it stops
Will keep you up to date

**Comment by emanuele-f** [comment]
Thank you @Artapel

**Comment by simonemainardi** [comment]
@Artapel do you really need to monitor all the interfaces of the system?

**Comment by Artapel** [comment]
It seems to run longer when using `sudo ntopng /etc/ntopng/ntopng.conf` but after a while it also stopped working

**Comment by emanuele-f** [comment]
@Artapel can you try to disable all the data retention settings under the ntopng preferences and see if the dashboard becomes responsive? Does the number of local hosts you see in the footer green badge match your expected local hosts number?

**Comment by lucaderi** [comment]
@Artapel Can you please specify in the configuration file with -i the exact interfaces you need to enable? As you are enabling too many interfaces this is definitely creating problems.

**Comment by Artapel** [comment]
I did the update to the latest Ntopng this morning. This seems to have fixed the problem.

I have also just configured the 3 interfaces we are currently using.
P.S, the other interfaces are not active. Just showing up so im very sure that did not add to the original problem. Those interfaces has been present for 2 years now and did not create a problem in the past.

The board is now working fine again. I can also see my disk usage dropped dramatically since the update.
I am waiting for munin graphs to collect some data to report back on disk usage.

Thank you very much for assisting with this problem

**Comment by BravoFox** [comment]
I seem to be having the same issue. It seems to run just fine for an hour or two, then shows the service as being exited. The only fix for this is restarting the service with the aforementioned restart command.

**Comment by Artapel** [comment]
The dashboard ran fine for more than a week. But now it has returned to only run for about a hour or 3 and then stop again. This issue started occurring after i did the update mentioned in this post.

https://github.com/ntop/ntopng/issues/1319#issuecomment-309378406

**Comment by simonemainardi** [comment]
@Artapel we did a major change yesterday, can you please try with the latest 3.1 build?

**Comment by BravoFox** [comment]
Just installed patches and reboot. I'll know if it worked in a bout an hour, as it seems to die right about the 3 hour mark.

**Comment by BravoFox** [comment]
Well its been up since 9AM EST at this point and hasnt gone down.

**Comment by BravoFox** [comment]
After 6 hours it crashed again. Is there a new major version out, or did you mean 3.01? I just updated from the YUM repo.
Edit: Its back to crashing again once every hour...

**Comment by simonemainardi** [comment]
@BravoFox I mean dev version 3.1, can you try that?

**Comment by BravoFox** [comment]
This is my only instance, so give me a bit to make sure i dont brick it.

**Comment by BravoFox** [comment]
3.1.170706 - Pro [Small Business Edition] Edition

OK installed and monitoring. I'll let you know.

**Comment by BravoFox** [comment]
No go. Died again after about 5 hours.

**Comment by Artapel** [comment]
I can confirm that mine also stops after a few hours. Please see the link below
Its work fine at after a restart but after a while the width of the bars start increasing and a few minutes later it will stop.
[https://ibb.co/ekJ7ua](url)

**Comment by simonemainardi** [comment]
@BravoFox what is your configuration?

@Artapel do you still get the freeze without option -F ?

any of you can provide a remote ssh access to the box?

**Comment by BravoFox** [comment]
-G=/var/run/ntopng.pid
--local-networks="172.0.0.0/8,192.168.0.0/16"
--sticky-hosts=local
--dns-mode=1
--interface=p1p1
--interface=p1p2
--interface=p1p3
--data-dir=/usr/local/ntopng
--packet-filter="ip and not proto ipv6 and not ether host ff:ff:ff:ff:ff:ff and not net (224.0.0.0/8 or 239.0.0.0/8)

**Comment by BravoFox** [comment]
@simonemainardi Cant do the SSH session unfortunately. Security would have a field day. Is there something i could send or do in lieu of that?

**Comment by Artapel** [comment]
@simonemainardi I updated again to the latest version BEFORE you requested to run without the -F.
So far its been running for about 20 hours fine. I will keep you updated if this changes.

**Comment by simonemainardi** [comment]
I have been fixing several leaks over the past days. @Artapel thanks for reporting, please keep me posted.

@BravoFox you may want to try and update to the latest dev build as it contains the fixes. Please wait a couple of hours before doing the update as a new build is in progress.

**Comment by BravoFox** [comment]
Latest update applied. I'll give it some time to burn in and see whats up.

**Comment by simonemainardi** [comment]
@BravoFox thanks. In case you will experience the OO again,  can you please try to run the process as `sudo valgrind --tool=memcheck --leak-check=full ./ntopng <and all your options>`, let it run for a while, and then send the valgrind output with summary? Thank you

**Comment by BravoFox** [comment]
@simonemainardi Yes sir I can.

**Comment by BravoFox** [comment]
So far so good. Don't seem to have the problem anymore. When will that change be moved to production so I can move off the development branch?

Thanks!

**Comment by simonemainardi** [comment]
Hi, I have already ported the fixes in the stable 3.0 version. You can revert back to stable.

Please try and feel free to close the issue if solved.

@Artapel is the issue solved also on your side?

**Comment by Artapel** [comment]
@simonemainardi Unfortunately not. I've been doing some test to determine why. 
I've also noticed that the browsers tab ntop displays on seems to run out of memory as well (Tested on two workstations that always worked). Although the other tabs are still fine.

Am going to run the 

> sudo valgrind --tool=memcheck --leak-check=full ./ntopng <and all your options>

 command today. I just need to determine the correct command switches to use. Perhaps you can help. Can i send you a email with the .conf file?

**Comment by simonemainardi** [comment]
@Artapel the browser OOM is another issue (https://github.com/ntop/ntopng/issues/1300). Let's try to see if we have resolved the issue in the subject of this topic first. Does your ntopng still stops collecting data after a while? Does it still eat all the available memory?

**Comment by Artapel** [comment]
@simonemainardi Ahh i see. 
Ntop seems fine now. My data for the last 24hr is present if i go and look for it.
The ram usage is also withing acceptable limits.

The issue seems to be sorted on my side.
I will switch my focus to  (#1300).

**Comment by simonemainardi** [comment]
It is safe to close this issue as the leaks have been solved and back ported to stable as well. Thanks for supporting us in the debugging.
