### ISSUE TITLE
"fatal error" ntopng compilation with libndpi-2.1.0 and "possible" solution.

### ISSUE THREAD

**Issue by xgerligand** [ntop/ntopng#1313]
Hi all.
Below the compilation outcome:
/usr/src/ntopng $ make
g++ -g -Wall -I/usr/src/ntopng -I/usr/src/ntopng/include -I/usr/local/include -I /usr/src/ntopng/third-party/hiredis -I/usr/src/ntopng/third-party/mongoose -I/usr/include/json-c     -I/usr/include/libndpi-2.1.0/libndpi   -I/usr/src/ntopng/third-party/LuaJIT-2.0.3/src     -I/usr/include/mysql -I/usr/include/mysql/..  -I/usr/src/ntopng -I/usr/src/ntopng/include -I/usr/local/include -I/usr/src/ntopng/third-party/http-client-c/src/   -I/usr/include/openssl  -DDATA_DIR='"/usr/share"' -I/usr/src/ntopng/third-party/libgeohash -I/usr/src/ntopng/third-party/patricia   -c src/nDPIStats.cpp -o src/nDPIStats.o
In file included from /usr/include/libndpi-2.1.0/libndpi/ndpi_main.h:30:0,
                 from /usr/src/ntopng/include/ntop_includes.h:106,
                 from src/nDPIStats.cpp:22:
/usr/include/libndpi-2.1.0/libndpi/ndpi_typedefs.h:28:49: fatal error: ../lib/third_party/include/libcache.h: No such file or directory
 #include "../lib/third_party/include/libcache.h"
                                                 ^
compilation terminated.
Makefile:154: recipe for target 'src/nDPIStats.o' failed
make: *** [src/nDPIStats.o] Error 1

It seems there is an incomplete "include" path in ndpi_typedefs.h header file :
Below the patch I apply to : **/usr/include/libndpi-2.1.0/libndpi/ndpi_typedefs.h**

--- old/ndpi_typedefs.h 2017-06-13 17:05:43.333008045 +0200
+++ new/ndpi_typedefs.h 2017-06-13 17:05:19.113094420 +0200
@@ -25,7 +25,7 @@
 #define __NDPI_TYPEDEFS_H__
 
 #include "ndpi_define.h"
-#include "../lib/third_party/include/libcache.h"
+#include "../nDPI/src/lib/third_party/include/libcache.h"
 
 #define BT_ANNOUNCE
 #define SNAP_EXT

But maybe exist a better way to revise that :-)

Best regards.
Xavier

**Comment by simonemainardi** [comment]
if you build from sources, then uninstall the libndpi you have under /usr/include and checkout nDPI sources from github. Please, refer to this readme for source compilation https://github.com/ntop/ntopng/blob/dev/doc/README.compilation

**Comment by xgerligand** [comment]
Thank you for your answer.
I have deleted all my /usr/include/libndpi-*
and git clone new nDPI,
and rebuild it (without "make install" as this is "make install" which create /usr/include/libndpi-*)
now the ntopng compilation give these errors :

OK        Successfully built LuaJIT
gmake[2]: Leaving directory '/usr/src/ntopng/third-party/LuaJIT-2.0.3/src'
==== Successfully built LuaJIT 2.0.3 ====
gmake[1]: Leaving directory '/usr/src/ntopng/third-party/LuaJIT-2.0.3'
g++ -g -Wall -I/usr/src/ntopng -I/usr/src/ntopng/include -I/usr/local/include -I /usr/src/ntopng/third-party/hiredis -I/usr/src/ntopng/third-party/mongoose -I/usr/include/json-c     -I/usr/include/libndpi-2.1.0/libndpi   -I/usr/src/ntopng/third-party/LuaJIT-2.0.3/src     -I/usr/include/mysql -I/usr/include/mysql/..  -I/usr/src/ntopng -I/usr/src/ntopng/include -I/usr/local/include -I/usr/src/ntopng/third-party/http-client-c/src/   -I/usr/include/openssl  -DDATA_DIR='"/usr/share"' -I/usr/src/ntopng/third-party/libgeohash -I/usr/src/ntopng/third-party/patricia   -c src/nDPIStats.cpp -o src/nDPIStats.o
In file included from src/nDPIStats.cpp:22:0:
**/usr/src/ntopng/include/ntop_includes.h:106:23: fatal error: ndpi_main.h: No such file or directory**
 #include "ndpi_main.h"
                       ^
compilation terminated.
Makefile:154: recipe for target 'src/nDPIStats.o' failed
make: *** [src/nDPIStats.o] Error 1
g++ -g -Wall -I/usr/src/ntopng -I/usr/src/ntopng/include -I/usr/local/include -I /usr/src/ntopng/third-party/hiredis -I/usr/src/ntopng/third-party/mongoose -I/usr/include/json-c     -I/usr/include/libndpi-2.1.0/libndpi   -I/usr/src/ntopng/third-party/LuaJIT-2.0.3/src     -I/usr/include/mysql -I/usr/include/mysql/..  -I/usr/src/ntopng -I/usr/src/ntopng/include -I/usr/local/include -I/usr/src/ntopng/third-party/http-client-c/src/   -I/usr/include/openssl  -DDATA_DIR='"/usr/share"' -I/usr/src/ntopng/third-party/libgeohash -I/usr/src/ntopng/third-party/patricia   -c src/nDPIStats.cpp -o src/nDPIStats.o
In file included from src/nDPIStats.cpp:22:0:
**/usr/src/ntopng/include/ntop_includes.h:106:23: fatal error: ndpi_main.h: No such file or directory**
 #include "ndpi_main.h"
                       ^
compilation terminated.
Makefile:154: recipe for target 'src/nDPIStats.o' failed
make: *** [src/nDPIStats.o] Error 1

**Comment by simonemainardi** [comment]
please describe all the exact steps you are doing

**Comment by xgerligand** [comment]
nDPI stage (/usr/src is the working directory) :

git clone  https://github.com/ntop/nDPI.git
                                cd nDPI
                           
                                ./autogen.sh --prefix=/usr
                                make

ntopng stage (/usr/src is the working directory) :

git clone https://github.com/ntop/ntopng.git
                                cd ntopng
                                ./autogen.sh && ./configure --prefix=/usr
                                make
                                make geoip
                                sudo make install

It seems a "-I../nDPI/src/include misses in the g++ command,
when I add it like below it works !

g++ -g -Wall -I../nDPI/src/include -I/usr/src/ntopng -I/usr/src/ntopng/include -I/usr/local/include -I /usr/src/ntopng/third-party/hiredis -I/usr/src/ntopng/third-party/mongoose -I/usr/include/json-c     -I/usr/include/libndpi-2.1.0/libndpi   -I/usr/src/ntopng/third-party/LuaJIT-2.0.3/src     -I/usr/include/mysql -I/usr/include/mysql/..  -I/usr/src/ntopng -I/usr/src/ntopng/include -I/usr/local/include -I/usr/src/ntopng/third-party/http-client-c/src/   -I/usr/include/openssl  -DDATA_DIR='"/usr/share"' -I/usr/src/ntopng/third-party/libgeohash -I/usr/src/ntopng/third-party/patricia   -c src/nDPIStats.cpp -o src/nDPIStats.o

And in the Makefile : 
NDPI_INC=-I../nDPI/src/include

**Comment by emanuele-f** [comment]
Hi, please make sure your directory structure is the following:

/usr/src/nDPI
/usr/src/ntopng

**Comment by xgerligand** [comment]
Thank you all, yes this is my structure.

I found the mistake: 
libndpi.pc was still in /usr/lib64/pkgconfig , I deleted it and it is OK now.
Thank you again for you help.
Xavier.
Bonjour de Paris.

**Comment by pleoeter** [comment]
/usr/local/include/libndpi-2.1.0/libndpi/ndpi_typedefs.h:28:49: fatal error: ../lib/third_party/include/libcache.h: No such file or directory
compilation terminated.
Makefile:160: recipe for target 'src/MDNS.o' failed
My source files are at /usr/src/ directory , please tell me to resolv the isssue

**Comment by simonemainardi** [comment]
there's an outdated nDPI installed under your `/usr/local/include/libndpi-2.1.0/`

make sure to uninstall it so the complier won't use it then you can follow step-by-step instructions available at https://github.com/ntop/ntopng/blob/dev/doc/README.compilation

**Comment by pleoeter** [comment]
no luck @simonemainardi

**Comment by simonemainardi** [comment]
Just saying no luck doesn't help.

Did you do what I suggested? Did you uninstall the nDPI under `/usr/local/include`? What is the new error log?

**Comment by pleoeter** [comment]
same error, i uninstalled the path , and recompiled again

**Comment by simonemainardi** [comment]
Show every single step you did. My guess is that you didn't run ./configure again

**Comment by pleoeter** [comment]
/usr/local/include$ sudo rm -r libndpi-2.1.0 
cd nDPI
./autogen.sh && ./configure
make && make install

cd ntopng
./autogen.sh && ./configure
make && make install

 fatal error: ../lib/third_party/include/libcache.h: No such file or directory
compilation terminated.
Makefile:154: recipe for target 'src/DB.o' failed

**Comment by simonemainardi** [comment]
you are missing git pull on both nDPI and ntopng directories

**Comment by pleoeter** [comment]
git pull to both directories, ntopng and nDPI, recompiled again , problem still persist

/usr/local/include/libndpi-2.1.0/libndpi/ndpi_typedefs.h:28:49: fatal error: ../lib/third_party/include/libcache.h: No such file or directory
compilation terminated.
Makefile:160: recipe for target 'src/HostHash.o' failed

**Comment by simonemainardi** [comment]
please follow the instructions in the compilation readme. Again `/usr/local/include/libndpi-2.1.0/libndpi/ndpi_typedefs.h:` means you are trying to use an installed version.

Just follow the readme. Start clean. Uninstall `/usr/local/include/libndpi-2.1.0/`. Then `cd` to your home directory and do the readme step-by-step.

**Comment by waqar-ali-aziz** [comment]
how to execute make command in case of nTPO. executing "sudo make" command in ntopng directory shows bellow error
make: *** No targets specified and no makefile found.  Stop.

**Comment by emanuele-f** [comment]
Please check out https://github.com/ntop/ntopng/blob/dev/doc/README.compilation
