### ISSUE TITLE
SANKEY charts, set sample to encompass traffic/flows per refresh interval

### ISSUE THREAD

**Issue by EinerPetersen** [ntop/ntopng#1314]
I would like to see the traffic flow information per interval reflected in the SANKEY charts.  At the time of this request, the SANKEY charts seem to only give the instantaneous flow information every poll interval.  Would like them to show the flow information per interval.  Also, considering how this would possibly change, make the poll/refresh interval manually adjustable as opposed to defined/fixed intervals.
Example:
poll/refresh=5 seconds
chart information: Show me the information aggregated for the entire 5 seconds between polls/refresh

poll/refresh=10 seconds
chart information: Show me the information aggregated for the entire 10 seconds between polls/refresh

This would make the information in the SANKEY charts more usable/informative

Einer

**Comment by simonemainardi** [comment]
It is already possible to control the refresh interval. You can control it from the interface settings

![image](https://user-images.githubusercontent.com/3397663/27838142-041a8696-60e9-11e7-9a42-86a509c0227f.png)

This affects both the gauge in the footer and the dashboards available in the professional versions. Dashboards and gauges will reflect the configured refresh interval to compute deltas, rates and totals.
