### ISSUE TITLE
host view display only 255.255.255.255 in ntopng development builds

### ISSUE THREAD

**Issue by bioteseo** [ntop/ntopng#1315]
Hi I'm using both ntopng version, but I see this issue only in the development version.
When I go in host view I see only a host 255.255.255.255.
In network view I see all networks and when I click on one of these I see the entire list of hosts of that network. Is it normal? I miss something?

This is my system:
Version	3.1.170614 - Community Edition
Built on	Ubuntu 14.04.5 LTS
nDPI	2.1.0-884-c46af12
 Twitter Bootstrap	3.x
 Font Awesome	4.x
RRDtool	1.4.8
Redis Server	2.8.4
Mongoose web server	3.7
LuaJIT	LuaJIT 2.0.3
ØMQ	4.0.4
GeoIP	1.6.0 
This product includes GeoLite data created by MaxMind.
Data-Driven Documents (d3js)	2.9.1 / 3.0

Version	3.1.170614 - Community Edition
Platform	Debian jessie/sid [x86_64][Ubuntu 14.04.5 LTS] - 64 bit
Startup Line	ntopng --pid "/var/tmp/ntopng.pid" --daemon "" --http-port "aaa.aaa.aaa.aaa:aaaa" --dns-mode "3" --max-num-flows "300000" --max-num-hosts "250000" --sticky-hosts "local" --verbose "" --capture-direction "1" --interface "eth2" --local-networks "bbb.bbb.bbb.bbb/bb,bbb.bbb.bbb.bbb/bb,bbb.bbb.bbb.bbb/bb,bbb.bbb.bbb.bbb/bb" --community ""

Last Log Trace	25/May/2017 13:32:46 [NtopPro.cpp:213] WARNING: [LICENSE] or run ntopng in community mode starting
25/May/2017 13:32:46 [NtopPro.cpp:212] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
25/May/2017 13:32:46 [NtopPro.cpp:211] WARNING: [LICENSE] before returning to community mode
25/May/2017 13:32:46 [NtopPro.cpp:209] WARNING: [LICENSE] ntopng will now run in enterprise edition for 10 minutes
25/May/2017 13:32:46 [NtopPro.cpp:196] ERROR: [LICENSE] Invalid or missing ntopng License [Empty license file]
25/May/2017 13:32:46 [NtopPro.cpp:144] [LICENSE] Read license from Redis []
25/May/2017 13:31:55 [NtopPro.cpp:214] WARNING: [LICENSE] ntopng --community
25/May/2017 13:31:55 [NtopPro.cpp:213] WARNING: [LICENSE] or run ntopng in community mode starting
25/May/2017 13:31:55 [NtopPro.cpp:212] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
25/May/2017 13:31:55 [NtopPro.cpp:211] WARNING: [LICENSE] before returning to community mode
25/May/2017 13:31:55 [NtopPro.cpp:209] WARNING: [LICENSE] ntopng will now run in enterprise edition for 10 minutes
25/May/2017 13:31:55 [NtopPro.cpp:196] ERROR: [LICENSE] Invalid or missing ntopng License [Empty license file]
25/May/2017 13:31:55 [NtopPro.cpp:144] [LICENSE] Read license from Redis []

Thanks i advance

Ceers

**Comment by emanuele-f** [comment]
Hi, do you that you do not experience the issue in the 3.0.x stable version while you experience it in the 3.1.x dev version? If this is the case, then it is really strange since we have forked the stable version just a few days ago, so most of the code is still shared with the dev.

Nevertheless, it is not normal. When you only see an host, can you see the pagination with page numbers at the bottom of the page? Does the footer report your hosts? If you go into the Layer 2 view, can you see the devices corectly? Please post a screenshot of the hosts page if possibile.

**Comment by bioteseo** [comment]
Hi,
the issue is in 3.1.x dev but not in 3.0.x stable version. The issue was in dev version also before to move to 3.x version but not in the stable version.

I see page numbers: the first page is only for host 255.255.255.255, the second contain hosts and so on. When I return to page 1 host 255.255.255.255 has displayed. Filters and arrows didn't run right.

Here three scrennshot, first page and second page top and bottom (I have chosen to display 200 entry for page).
![screenshot from 2017-06-14 13-53-07](https://user-images.githubusercontent.com/316396/27131045-4a6f5350-5109-11e7-9dd0-66d5e8589938.png)
![screenshot from 2017-06-14 13-54-20](https://user-images.githubusercontent.com/316396/27131046-4a730554-5109-11e7-9a4f-3514039e6817.png)
![screenshot from 2017-06-14 13-54-54](https://user-images.githubusercontent.com/316396/27131044-4a6f0e18-5109-11e7-964c-f70f45257e0f.png)

**Comment by emanuele-f** [comment]
I suspect this is related to the fact that the ip 255.255.255.255 appears with many mac addresses. Internally, there are many hosts with the same ip but different mac addresses, so they are counted individually. On the gui side, however, they are sort of aggregated into one entry. This is something we should fix.

**Comment by simonemainardi** [comment]
@emanuele-f I think I know the issue: NetworkInterface::getActiveHosts pushes hosts in a lua table and uses the host ip address as key. In case the same ip is seen with multiple mac addresses, then the same key is overwritten and thus fewer hosts are shown. 

I am working on the fix. I will push results using integer numbers starting from 1 as it is done with flows. I need some time as this requires several changes in the lua scripts.

**Comment by simonemainardi** [comment]
fixed with https://github.com/ntop/ntopng/commit/eaa7a0d3130d9eeb2596a57c2d6b75eddca70707
