### ISSUE TITLE
Report of latest hours traffic data (sent/receive) for an host

### ISSUE THREAD

**Issue by rainbowbreeze** [ntop/ntopng#1318]
First: thanks for ntop and ntopng! I'm finding them really useful to monitor my domestic bandwidth consumption using a RasPi 3 as AP and ntop - ntopng to check traffic from each host

In ntop I was using previously, I had a very convenient (for me) view where the total host traffic (sent/receive) was shown for the latest hours
![ntop-hourly-report](https://user-images.githubusercontent.com/381940/27256724-913237d6-53bf-11e7-90a3-359b4095c7bb.png)

Now that I'm using ntopng, I cannot find anymore a way to have this information. In the Chart tab I can see traffic for the latest 60 mins (or other time intervals), as per screenshow below, but I cannot find any way to see a simple report of how many data the host has sent/received in the latest hours
![ntopng-hourly](https://user-images.githubusercontent.com/381940/27256731-e7b3b986-53bf-11e7-95fe-2a868c896a45.png)

Am I missing something? And thank! :)
ntopng Community/Embedded v.3.1.170612

**Comment by emanuele-f** [comment]
Hi, the ntopng community version does not have such a view. We offer a per hour/day traffic report (but it is not splitted between sent/receive) into the enterprise edition, which you can run as a demo from our repositories http://packages.ntop.org/. The report is available for local networks, hosts and interfaces.

![screenshot at 2017-06-19 00-29-06](https://user-images.githubusercontent.com/5488003/27264767-6b9d1348-5486-11e7-8e55-832eed3f0346.png)


In general, the reporting options are very limited into the community version. We offer the detailed views on the paid versions.
