### ISSUE TITLE
latest dev version of ntopng compilation errors

### ISSUE THREAD

**Issue by Drewshg312** [ntop/ntopng#132]
Compiling the latest dev version getting this:

    -I/private/tmp/ntopng20150822-24304-1qbxoul/third-party/EWAHBoolArray/headers  -DDATA_DIR='"/usr/local/Cellar/ntopng/HEAD/share"' -I/private/tmp/ntopng20150822-24304-1qbxoul/third-party/libgeohash -I/private/tmp/ntopng20150822-24304-1qbxoul/third-party/patricia   -c src/Flow.cpp -o src/Flow.o
    src/Flow.cpp:96:28: error: assigning to 'u_int16_t' (aka 'unsigned short') from incompatible type 'ndpi_protocol'
          (aka 'ndpi_proto')
        ndpi_detected_protocol = ndpi_guess_undetected_protocol(iface->get_ndpi_struct(),
                               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/Flow.cpp:469:30: error: assigning to 'u_int16_t' (aka 'unsigned short') from incompatible type 'ndpi_protocol'
          (aka 'ndpi_proto')
          ndpi_detected_protocol = ndpi_guess_undetected_protocol(iface->get_ndpi_struct(), protocol,
                                 ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 errors generated.
    make: *** [src/Flow.o] Error 1

Any ideas?

**Comment by lucaderi** [comment]
Your ntopng and nDPI are out of sync (nDPI is more updated I believe)

**Comment by Drewshg312** [comment]
Well we are actually using the nDPI and ntopng codes from git… and still getting these errors
That's what the process does:

    git clone https://github.com/ntop/ntopng.git
    git clone https://github.com/ntop/nDPI.git
    cd /tmp/blah-nDPI
    ./autogen.sh
    make
    mv * /tmp/blah-ntopng/nDPI/
    cd /tmp/blah-ntopng
    ./autogen.sh

What's wrong?

    ./configure --prefix=#{prefix}
    make
    make install

**Comment by lucaderi** [comment]
It can't be. Please paste the whole log.

**Comment by Drewshg312** [comment]
==> make
    /usr/local/Library/ENV/4.3/clang++ -g -fno-color-diagnostics -Wall -I/private/tmp/ntopng20150825-19653-1als1us -I/private/tmp/ntopng20150825-19653-1als1us/include -I/usr/local/include -I /private/tmp/ntopng20150825-19653-1als1us/third-party/hiredis -I/private/tmp/ntopng20150825-19653-1als1us/third-party/mongoose -I/usr/local/Cellar/json-c/0.12/include/json-c  -I./nDPI/src/include -I/usr/local/Cellar/luajit/2.0.4/include/luajit-2.0  -I/usr/local/Cellar/rrdtool/1.5.3/include  -I/usr/local/Cellar/zeromq/4.1.2/include   -I/private/tmp/ntopng20150825-19653-1als1us -I/private/tmp/ntopng20150825-19653-1als1us/include -I/usr/local/include -I/private/tmp/ntopng20150825-19653-1als1us/third-party/http-client-c/src/ -I/private/tmp/ntopng20150825-19653-1als1us/third-party/EWAHBoolArray/headers  -DDATA_DIR='"/usr/local/Cellar/ntopng/HEAD/share"' -I/private/tmp/ntopng20150825-19653-1als1us/third-party/libgeohash -I/private/tmp/ntopng20150825-19653-1als1us/third-party/patricia   -c src/ActivityStats.cpp -o src/ActivityStats.o
    /usr/local/Library/ENV/4.3/clang++ -g -fno-color-diagnostics -Wall -I/private/tmp/ntopng20150825-19653-1als1us -I/private/tmp/ntopng20150825-19653-1als1us/include -I/usr/local/include -I /private/tmp/ntopng20150825-19653-1als1us/third-party/hiredis -I/private/tmp/ntopng20150825-19653-1als1us/third-party/mongoose -I/usr/local/Cellar/json-c/0.12/include/json-c  -I./nDPI/src/include -I/usr/local/Cellar/luajit/2.0.4/include/luajit-2.0  -I/usr/local/Cellar/rrdtool/1.5.3/include  -I/usr/local/Cellar/zeromq/4.1.2/include   -I/private/tmp/ntopng20150825-19653-1als1us -I/private/tmp/ntopng20150825-19653-1als1us/include -I/usr/local/include -I/private/tmp/ntopng20150825-19653-1als1us/third-party/http-client-c/src/ -I/private/tmp/ntopng20150825-19653-1als1us/third-party/EWAHBoolArray/headers  -DDATA_DIR='"/usr/local/Cellar/ntopng/HEAD/share"' -I/private/tmp/ntopng20150825-19653-1als1us/third-party/libgeohash -I/private/tmp/ntopng20150825-19653-1als1us/third-party/patricia   -c src/AddressResolution.cpp -o src/AddressResolution.o
    /usr/local/Library/ENV/4.3/clang++ -g -fno-color-diagnostics -Wall -I/private/tmp/ntopng20150825-19653-1als1us -I/private/tmp/ntopng20150825-19653-1als1us/include -I/usr/local/include -I /private/tmp/ntopng20150825-19653-1als1us/third-party/hiredis -I/private/tmp/ntopng20150825-19653-1als1us/third-party/mongoose -I/usr/local/Cellar/json-c/0.12/include/json-c  -I./nDPI/src/include -I/usr/local/Cellar/luajit/2.0.4/include/luajit-2.0  -I/usr/local/Cellar/rrdtool/1.5.3/include  -I/usr/local/Cellar/zeromq/4.1.2/include   -I/private/tmp/ntopng20150825-19653-1als1us -I/private/tmp/ntopng20150825-19653-1als1us/include -I/usr/local/include -I/private/tmp/ntopng20150825-19653-1als1us/third-party/http-client-c/src/ -I/private/tmp/ntopng20150825-19653-1als1us/third-party/EWAHBoolArray/headers  -DDATA_DIR='"/usr/local/Cellar/ntopng/HEAD/share"' -I/private/tmp/ntopng20150825-19653-1als1us/third-party/libgeohash -I/private/tmp/ntopng20150825-19653-1als1us/third-party/patricia   -c src/AlertCounter.cpp -o src/AlertCounter.o
    /usr/local/Library/ENV/4.3/clang++ -g -fno-color-diagnostics -Wall -I/private/tmp/ntopng20150825-19653-1als1us -I/private/tmp/ntopng20150825-19653-1als1us/include -I/usr/local/include -I /private/tmp/ntopng20150825-19653-1als1us/third-party/hiredis -I/private/tmp/ntopng20150825-19653-1als1us/third-party/mongoose -I/usr/local/Cellar/json-c/0.12/include/json-c  -I./nDPI/src/include -I/usr/local/Cellar/luajit/2.0.4/include/luajit-2.0  -I/usr/local/Cellar/rrdtool/1.5.3/include  -I/usr/local/Cellar/zeromq/4.1.2/include   -I/private/tmp/ntopng20150825-19653-1als1us -I/private/tmp/ntopng20150825-19653-1als1us/include -I/usr/local/include -I/private/tmp/ntopng20150825-19653-1als1us/third-party/http-client-c/src/ -I/private/tmp/ntopng20150825-19653-1als1us/third-party/EWAHBoolArray/headers  -DDATA_DIR='"/usr/local/Cellar/ntopng/HEAD/share"' -I/private/tmp/ntopng20150825-19653-1als1us/third-party/libgeohash -I/private/tmp/ntopng20150825-19653-1als1us/third-party/patricia   -c src/Categorization.cpp -o src/Categorization.o
    /usr/local/Library/ENV/4.3/clang++ -g -fno-color-diagnostics -Wall -I/private/tmp/ntopng20150825-19653-1als1us -I/private/tmp/ntopng20150825-19653-1als1us/include -I/usr/local/include -I /private/tmp/ntopng20150825-19653-1als1us/third-party/hiredis -I/private/tmp/ntopng20150825-19653-1als1us/third-party/mongoose -I/usr/local/Cellar/json-c/0.12/include/json-c  -I./nDPI/src/include -I/usr/local/Cellar/luajit/2.0.4/include/luajit-2.0  -I/usr/local/Cellar/rrdtool/1.5.3/include  -I/usr/local/Cellar/zeromq/4.1.2/include   -I/private/tmp/ntopng20150825-19653-1als1us -I/private/tmp/ntopng20150825-19653-1als1us/include -I/usr/local/include -I/private/tmp/ntopng20150825-19653-1als1us/third-party/http-client-c/src/ -I/private/tmp/ntopng20150825-19653-1als1us/third-party/EWAHBoolArray/headers  -DDATA_DIR='"/usr/local/Cellar/ntopng/HEAD/share"' -I/private/tmp/ntopng20150825-19653-1als1us/third-party/libgeohash -I/private/tmp/ntopng20150825-19653-1als1us/third-party/patricia   -c src/CollectorInterface.cpp -o src/CollectorInterface.o
    /usr/local/Library/ENV/4.3/clang++ -g -fno-color-diagnostics -Wall -I/private/tmp/ntopng20150825-19653-1als1us -I/private/tmp/ntopng20150825-19653-1als1us/include -I/usr/local/include -I /private/tmp/ntopng20150825-19653-1als1us/third-party/hiredis -I/private/tmp/ntopng20150825-19653-1als1us/third-party/mongoose -I/usr/local/Cellar/json-c/0.12/include/json-c  -I./nDPI/src/include -I/usr/local/Cellar/luajit/2.0.4/include/luajit-2.0  -I/usr/local/Cellar/rrdtool/1.5.3/include  -I/usr/local/Cellar/zeromq/4.1.2/include   -I/private/tmp/ntopng20150825-19653-1als1us -I/private/tmp/ntopng20150825-19653-1als1us/include -I/usr/local/include -I/private/tmp/ntopng20150825-19653-1als1us/third-party/http-client-c/src/ -I/private/tmp/ntopng20150825-19653-1als1us/third-party/EWAHBoolArray/headers  -DDATA_DIR='"/usr/local/Cellar/ntopng/HEAD/share"' -I/private/tmp/ntopng20150825-19653-1als1us/third-party/libgeohash -I/private/tmp/ntopng20150825-19653-1als1us/third-party/patricia   -c src/DB.cpp -o src/DB.o
    /usr/local/Library/ENV/4.3/clang++ -g -fno-color-diagnostics -Wall -I/private/tmp/ntopng20150825-19653-1als1us -I/private/tmp/ntopng20150825-19653-1als1us/include -I/usr/local/include -I /private/tmp/ntopng20150825-19653-1als1us/third-party/hiredis -I/private/tmp/ntopng20150825-19653-1als1us/third-party/mongoose -I/usr/local/Cellar/json-c/0.12/include/json-c  -I./nDPI/src/include -I/usr/local/Cellar/luajit/2.0.4/include/luajit-2.0  -I/usr/local/Cellar/rrdtool/1.5.3/include  -I/usr/local/Cellar/zeromq/4.1.2/include   -I/private/tmp/ntopng20150825-19653-1als1us -I/private/tmp/ntopng20150825-19653-1als1us/include -I/usr/local/include -I/private/tmp/ntopng20150825-19653-1als1us/third-party/http-client-c/src/ -I/private/tmp/ntopng20150825-19653-1als1us/third-party/EWAHBoolArray/headers  -DDATA_DIR='"/usr/local/Cellar/ntopng/HEAD/share"' -I/private/tmp/ntopng20150825-19653-1als1us/third-party/libgeohash -I/private/tmp/ntopng20150825-19653-1als1us/third-party/patricia   -c src/DnsStats.cpp -o src/DnsStats.o
    /usr/local/Library/ENV/4.3/clang++ -g -fno-color-diagnostics -Wall -I/private/tmp/ntopng20150825-19653-1als1us -I/private/tmp/ntopng20150825-19653-1als1us/include -I/usr/local/include -I /private/tmp/ntopng20150825-19653-1als1us/third-party/hiredis -I/private/tmp/ntopng20150825-19653-1als1us/third-party/mongoose -I/usr/local/Cellar/json-c/0.12/include/json-c  -I./nDPI/src/include -I/usr/local/Cellar/luajit/2.0.4/include/luajit-2.0  -I/usr/local/Cellar/rrdtool/1.5.3/include  -I/usr/local/Cellar/zeromq/4.1.2/include   -I/private/tmp/ntopng20150825-19653-1als1us -I/private/tmp/ntopng20150825-19653-1als1us/include -I/usr/local/include -I/private/tmp/ntopng20150825-19653-1als1us/third-party/http-client-c/src/ -I/private/tmp/ntopng20150825-19653-1als1us/third-party/EWAHBoolArray/headers  -DDATA_DIR='"/usr/local/Cellar/ntopng/HEAD/share"' -I/private/tmp/ntopng20150825-19653-1als1us/third-party/libgeohash -I/private/tmp/ntopng20150825-19653-1als1us/third-party/patricia   -c src/EppStats.cpp -o src/EppStats.o
    /usr/local/Library/ENV/4.3/clang++ -g -fno-color-diagnostics -Wall -I/private/tmp/ntopng20150825-19653-1als1us -I/private/tmp/ntopng20150825-19653-1als1us/include -I/usr/local/include -I /private/tmp/ntopng20150825-19653-1als1us/third-party/hiredis -I/private/tmp/ntopng20150825-19653-1als1us/third-party/mongoose -I/usr/local/Cellar/json-c/0.12/include/json-c  -I./nDPI/src/include -I/usr/local/Cellar/luajit/2.0.4/include/luajit-2.0  -I/usr/local/Cellar/rrdtool/1.5.3/include  -I/usr/local/Cellar/zeromq/4.1.2/include   -I/private/tmp/ntopng20150825-19653-1als1us -I/private/tmp/ntopng20150825-19653-1als1us/include -I/usr/local/include -I/private/tmp/ntopng20150825-19653-1als1us/third-party/http-client-c/src/ -I/private/tmp/ntopng20150825-19653-1als1us/third-party/EWAHBoolArray/headers  -DDATA_DIR='"/usr/local/Cellar/ntopng/HEAD/share"' -I/private/tmp/ntopng20150825-19653-1als1us/third-party/libgeohash -I/private/tmp/ntopng20150825-19653-1als1us/third-party/patricia   -c src/EthStats.cpp -o src/EthStats.o
    /usr/local/Library/ENV/4.3/clang++ -g -fno-color-diagnostics -Wall -I/private/tmp/ntopng20150825-19653-1als1us -I/private/tmp/ntopng20150825-19653-1als1us/include -I/usr/local/include -I /private/tmp/ntopng20150825-19653-1als1us/third-party/hiredis -I/private/tmp/ntopng20150825-19653-1als1us/third-party/mongoose -I/usr/local/Cellar/json-c/0.12/include/json-c  -I./nDPI/src/include -I/usr/local/Cellar/luajit/2.0.4/include/luajit-2.0  -I/usr/local/Cellar/rrdtool/1.5.3/include  -I/usr/local/Cellar/zeromq/4.1.2/include   -I/private/tmp/ntopng20150825-19653-1als1us -I/private/tmp/ntopng20150825-19653-1als1us/include -I/usr/local/include -I/private/tmp/ntopng20150825-19653-1als1us/third-party/http-client-c/src/ -I/private/tmp/ntopng20150825-19653-1als1us/third-party/EWAHBoolArray/headers  -DDATA_DIR='"/usr/local/Cellar/ntopng/HEAD/share"' -I/private/tmp/ntopng20150825-19653-1als1us/third-party/libgeohash -I/private/tmp/ntopng20150825-19653-1als1us/third-party/patricia   -c src/ExportInterface.cpp -o src/ExportInterface.o
    /usr/local/Library/ENV/4.3/clang++ -g -fno-color-diagnostics -Wall -I/private/tmp/ntopng20150825-19653-1als1us -I/private/tmp/ntopng20150825-19653-1als1us/include -I/usr/local/include -I /private/tmp/ntopng20150825-19653-1als1us/third-party/hiredis -I/private/tmp/ntopng20150825-19653-1als1us/third-party/mongoose -I/usr/local/Cellar/json-c/0.12/include/json-c  -I./nDPI/src/include -I/usr/local/Cellar/luajit/2.0.4/include/luajit-2.0  -I/usr/local/Cellar/rrdtool/1.5.3/include  -I/usr/local/Cellar/zeromq/4.1.2/include   -I/private/tmp/ntopng20150825-19653-1als1us -I/private/tmp/ntopng20150825-19653-1als1us/include -I/usr/local/include -I/private/tmp/ntopng20150825-19653-1als1us/third-party/http-client-c/src/ -I/private/tmp/ntopng20150825-19653-1als1us/third-party/EWAHBoolArray/headers  -DDATA_DIR='"/usr/local/Cellar/ntopng/HEAD/share"' -I/private/tmp/ntopng20150825-19653-1als1us/third-party/libgeohash -I/private/tmp/ntopng20150825-19653-1als1us/third-party/patricia   -c src/Flow.cpp -o src/Flow.o
    src/Flow.cpp:96:28: error: assigning to 'u_int16_t' (aka 'unsigned short') from incompatible type 'ndpi_protocol' (aka 'ndpi_proto')
        ndpi_detected_protocol = ndpi_guess_undetected_protocol(iface->get_ndpi_struct(),
                               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/Flow.cpp:469:30: error: assigning to 'u_int16_t' (aka 'unsigned short') from incompatible type 'ndpi_protocol' (aka 'ndpi_proto')
          ndpi_detected_protocol = ndpi_guess_undetected_protocol(iface->get_ndpi_struct(), protocol,
                                 ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 errors generated.
    make: *** [src/Flow.o] Error 1

**Comment by lucaderi** [comment]
You are using ntopng stable code

**Comment by Drewshg312** [comment]
So why does it return these errors then?

**Comment by lucaderi** [comment]
You still aren;t doing what you are supposed to do.
mkdir mac
cd mac
git clone https://github.com/ntop/ntopng.git
git clone https://github.com/ntop/nDPI.git
cd nDPI
./autogen.sh;./configure;make
cd ../ntopng
./autogen.sh;./configure;make

**Comment by Drewshg312** [comment]
But that's exactly the code I'm using…

**Comment by lucaderi** [comment]
I don;t think so.
