### ISSUE TITLE
No Results Found @ User History (Flows Talkers Protocols)

### ISSUE THREAD

**Issue by Artapel** [ntop/ntopng#1320]
Hi Guys Hope you can help

I am trying to view a more detailed history on one particular IP address but im getting the "No Results Found" message when clicking on Flows,Talkers or Protocols.

I can see the bandwidth in the "Chart" tab but no other data in another tab.
This seems to be the case for all IP`s outside of Vlan0.

I can view this information on device in our default vlan.

**My current setup is as follows**

> Linux monitor 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**yum list installed | grep ntop**

> 
> cento.x86_64 1.3.170619-205 @ntop
> e1000e-zc.noarch 3.2.7.1.1277-dkms @ntop-noarch
> i40e-zc.noarch 1.5.18.1277-1dkms @ntop-noarch
> igb-zc.noarch 5.3.3.5.1277-dkms @ntop-noarch
> ixgbe-zc.noarch 4.1.5.1277-dkms @ntop-noarch
> n2disk.x86_64 2.9.170619-4819 @ntop
> nprobe.x86_64 8.1.170619-5790 @ntop
> ntopng.x86_64 3.1.170619-2939 @ntop
> ntopng-data.noarch 3.1.170619-2939 @ntop-noarch
> pfring.x86_64 6.7.0-1277 @ntop
> pfring-dkms.noarch 6.7.0-1277 @ntop-noarch
> pfring-drivers-zc-dkms.noarch 1.2-0 @ntop-noarch

**Comment by emanuele-f** [comment]
I confirm the problem is caused by the vlan id, which is combined into the IP_DST_ADDR and IP_SRC_ADDR mysql fields

**Comment by Artapel** [comment]
Thank you very much for the feedback. Is there anything i can do or should i wait for a fix?

Regards

NOTE: This e-mail is intended solely for the use of the individual(s) to whom it is addressed. If you are not an intended recipient you must not use, disclose, distribute, copy, print, or rely on this e-mail.

**Comment by emanuele-f** [comment]
Please wait for the fix, thank you
