### ISSUE TITLE
LDAP (AD) authentication not working

### ISSUE THREAD

**Issue by NLedoux** [ntop/ntopng#1321]
We were finally able to upgrade to the latest version but still no luck with LDAP authentication (Active Directory).
We have been able to confirm that ntop communicates with our AD server as I see the requests on our firewalls.
I think we also have been able to confirm that the Bind Account provided is used as inputting a wrong password triggers a “Bind error: Invalid credentials” that goes away as soon as I put back the right password.
However login with an AD account does not work and nothing appear in the log. Can you help?

**Comment by ValentinaViscarelli** [comment]
@NLedoux 
Are you sure you have configured ntopng properly?
Could you please attach ntopng configuration for ldap authentication?
Is it possible to have more informations of your server?
For example with this command (make attention the output of this command gives private information of your accounts. If you want you can send me the info into my private email valentina@ntop.org):
ldapsearch -x -H ldaps://localhost -b dc=ntop,dc=org

Replace the dc=ntop,dc=org field with your data.

**Comment by NLedoux** [comment]
Hello Valentina,

I think ntopng is properly configured. It is working well apart from LDAP (AD) login.
We see LDAP requests to the AD server when login attemps are made and ntopng logs an error if the wrong password is entered form the LDAP Bind DN.
Here are the parameters:
- LDAP Accounts Type: sAMAccount
- LDAP Server Address: ldaps://[FQDN]:636
- LDAP Anonymous Binding: Off
- LDAP Bind DN: cn=[QueryAccount],cn=Users,dc=equisoft,dc=com
- LDAP Bind Authentication Password: [Password]
- LDAP Search Path: dc=equisoft,dc=com
- LDAP User Group: ntop users
- LDAP Admin Group: ntop admins

**Comment by ValentinaViscarelli** [comment]
@NLedoux 
Are you sure you  have a sAMAccount? Maybe do you have a posix account?

**Comment by NLedoux** [comment]
If I’m not mistaking, AD is sAMAccount not posix.

Out of Office alert: June 30 - July 18
EquiSoft <http://www.equisoft.com/> SOLUTIONS D’AFFAIRES INNOVATRICES
Nicolas Ledoux, Directeur Principal, Infrastructure TI
T: 514.989.3141 X 259| +1.888.989.3141| M: 514.880.3141

**Comment by ValentinaViscarelli** [comment]
@NLedoux 
If you use sAMAccount you have to user "memberOf" attribute to bind user to group and you have also to define "distinguishedName" attribute. Did you make these steps?

**Comment by NLedoux** [comment]
The directory is Microsoft Active Directory so yes those 2 attributes are used and defined.
Are you talking about configuration to be done on the ntopng side? If so where and how?

Out of Office alert: June 30 - July 18
EquiSoft <http://www.equisoft.com/> SOLUTIONS D’AFFAIRES INNOVATRICES
Nicolas Ledoux, Directeur Principal, Infrastructure TI
T: 514.989.3141 X 259| +1.888.989.3141| M: 514.880.3141

**Comment by simonemainardi** [comment]
@NLedoux @ValentinaViscarelli any news?

**Comment by ValentinaViscarelli** [comment]
@NLedoux @simonemainardi 
In order to verify if sAMAccount works properly I need to create in a LDAP server this type of account.
I'm using OpenLDAP server for Linux and I wasn't able to create this type of account in this server.
Do you know how I can create a sAMAccount? Another solution is that you let me access to your server (but I know that it could be a problem).

**Comment by simonemainardi** [comment]
@NLedoux can you help @ValentinaViscarelli ?

**Comment by lucaderi** [comment]
Closed for inactivity. Will reopen if necessary
