### ISSUE TITLE
Ntopng v3 - multiple issues (dropped MySQL flows, local hosts RRD dump error in log)

### ISSUE THREAD

**Issue by harmane** [ntop/ntopng#1324]
Running a single instance of ntopng w/nprobe collecting netflow from Cisco 6509. Version and config as follows:

Debian 8.8
4 Core
16GB ram
1Gbps eth
MySQL Fabric

ii  apt-ntop-stable                2.4-535                            all          ntop stable apt package repository
ii  ntopng                         3.0.170619-3064                    amd64        Web-based traffic monitoring.
ii  ntopng-data                    3.0.170619                         all          Data files (geoip) for ntopng.
ii  pfring                         6.6.0-1277                         amd64        PF_RING (http://www.ntop.org/pf_ring/) [6.6.0-stable:7714855899a375efd17a227bd62edea5559d8d73 (Tue Jun 13 17:52:18 2017 +0200)]
ii  nprobe                         8.0.170619-5786                    amd64        A network probe.
ii  pfring-dkms                    6.6.0                              all          PF_RING driver in DKMS format. GIT info: 6.6.0-stable:1bc2c6a94201fc802b0b312c9e561ead35df2ddf (Sat May 20 00:44:47 2017 +0200)

`
-d=/ntopng-data/ntopng
-G=/ntopng-data/ntopng.pid
-i=tcp://127.0.0.1:5556
-S=local
-m=10.130.0.0/15,10.132.0.0/14,10.136.0.0/14,216.X.X.X/29,216.X.X.X/29,192.168.99.0/24,216.X.X.X/26,192.168.201.0/24,IPv6::/54
-X=250000
-x=250000
-F="mysqlstuff"
`

![ntopng_uptime](https://user-images.githubusercontent.com/18288828/27383382-c1dada0a-5658-11e7-9d6d-b4bd73a9645b.PNG)

![dropped_flows](https://user-images.githubusercontent.com/18288828/27383390-c81a6c5a-5658-11e7-9c6c-7790a2204d8b.PNG)

Log is full of:

`
21/Jun/2017 08:04:50 [Lua.cpp:5500] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[156] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.
`

Most local subnets are /23 & /24 with ~15K active nodes total. All data retention settings are off. Lots of CPU user time on both ntopng host since upgrade to v3 with or without MySQL configured. MySQL slaves also with high CPU wait though I have not tweaked MySQL performance. Slaves are severely lagging behind master though as far as I can tell this seems intentional and hopefully can be changed when perf config tweaked. I am also looking to reduce the size of flow from 6509 to only a couple vlans to see if it's just too much data.

The dropped MySQL flows haven't gone above 3%. Is this something to be concerned about? I'm not seeing any general performance issues currently though searching historical data is fairly slow. Also wondering about NoIP showing up in hosts. Seems to "consume" most bandwidth. We employ bonjour-gateway on quite a few vlans, could be this?:

![noip](https://user-images.githubusercontent.com/18288828/27383884-dc57e9d4-565a-11e7-81ab-2676169c50e9.PNG)

EDIT: Just realized MySQL cluster VM's are using E1000 as opposed to VMXNET3. Will switch when replication finishes.

**Comment by simonemainardi** [comment]
hi, thanks for reporting, I have made an optimization to skip local hosts iterations in the 5min.lua script when, as in your case, all the host timeseries (data retention) are disabled.

This will prevent the error

```
21/Jun/2017 08:04:50 [Lua.cpp:5500] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[156] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.
```

You have 30k local hosts. This means that, if you want to save local hosts timeseries within a 5 minutes timespan, 100 hosts per second must have all their RRDs updated. We know that RRDs are not much efficient and we can say for sure that this is the bottleneck. For this reason we are working on a more efficient way to save timeseries and will include it as soon as ready.

As concerns mysql performance, I think a 1% flow drop is acceptable. However, if you want higher insertion speeds (and thus no drops), you should try the Enterprise version of ntopng that features faster (up to 5x) mysql insertions.

Finally, for the noIP host, can you please check the flows and the mac addresses associated to it? Can you also try and update a pcap file for our inspection? I could understand an all-zeros source ip, but I can't understand why that ip also has received traffic.

**Comment by harmane** [comment]
`
"mac_address":"00:00:00:00:00:00"
`

For what it's worth I'm not seeing any MAC addresses with netflow. Only way I have seen MAC addresses or OS detection has been with in-line collection/mirror/span ports.


[ntopng.zip](https://github.com/ntop/ntopng/files/1092596/ntopng.zip)

**Comment by simonemainardi** [comment]
if you want to see mac addresses with netflow, you have to explicitly declare an nprobe with source and destination mac addresses, e.g., 

-T "%IPV4_SRC_ADDR %IPV4_DST_ADDR %IPV4_NEXT_HOP %INPUT_SNMP %OUTPUT_SNMP %IN_PKTS %IN_BYTES %FLOW_START_MILLISECONDS %FLOW_END_MILLISECONDS %L4_SRC_PORT %L4_DST_PORT %TCP_FLAGS %PROTOCOL %SRC_TOS %SRC_AS %DST_AS %IPV4_SRC_MASK %IPV4_DST_MASK %IN_SRC_MAC %OUT_DST_MAC"

**Comment by simonemainardi** [comment]
by the way, regarding your other question, the enterprise version not only features faster insertion speeds, but also uses aggregation techniques to speed up searches and queries.

**Comment by harmane** [comment]
I'm now seeing MAC addresses (Cisco config change) but however still see the zero MAC with send/receive traffic. Also no more MySQL drops after updating to ver. 3.0.170623 though netflow is significantly reduced this time of year.

I think I will look into the Enterprise version as there are some features we could use. I still am seeing lots of iowait on slaves but it's more a MySQL thing than ntopng. Master is fine performance-wise. I don't have very much MySQL experience so experimenting is necessary. I've tweaked some stuff to improve MyISAM performance but there doesn't seem to be any affect. Trying to let things run to see how far behind the slaves lag so I can purge logs accordingly as to free up enough space.
