### ISSUE TITLE
interface name in addition to snmpifindex

### ISSUE THREAD

**Issue by lliopt** [ntop/ntopng#1325]
Hi guys,
Currently we have snmpifindex field in the flow info, which is not quite useful, since you have no idea to what interface that index belongs, and that requires you to have snmp device tab opened just to verify incoming and outgoing interfaces for the flow.
Since snmp device tab already has all interface names polled, could you please add 2 more fields in GUI in addition to ifindex with the thenames?

**Comment by simonemainardi** [comment]
implemented. Will be available in the ntopng 3.1 dev build starting from tomorrow.
