### ISSUE TITLE
GUI is not quite useful for a network troubleshooting

### ISSUE THREAD

**Issue by lliopt** [ntop/ntopng#1326]
Hi team,
Current ntop GUI is kind of messy and doesn`t allow you to troubleshoot modular/multi-port/multispeed network devices efficiently because of lacking graphs/flows_grooping/you_namr_it  option on per interface (snmpifindex) basis.
Imagine you have a router with 1x40G interfaces + 1x10G + 1x1G and 1x100M interfaces and only 100M link is 100% utilised. In the same time all other interfaces are 50% utilised, which is quite common for the border routers.  So would like to check what kind of traffic flows through the 100M interface.

The most natural thing is open a flow device in ntop GUI and click on the 100M interface to see the flows sorted per inbound/outgoing interface. That allows you in couple of seconds find out the most fat flow and understand if traffic is legit or not, and if not probably you can shape/police it to make sure that 100M is able to handle your production traffic.
But that option doesn`t exist. Instead of that we have `snmp polled` interface rate which doesn`t help with troubleshooting at all, since I`m already aware that link is saturated by complaining users/monitoring_system/whatever. The only thing I can relay on -  the flow chart. But with 26Gbps of traffic going through the device there are no chances to find a fat flow related to the poor 100M interface.

Also clicking to the IP from the flow moves you to another page, where you need to move the the flow tab, to get a list of flows than you need click to the info tab to see snmpifindex there. After that you have to go to the snmp device, click on the correct one and check ifindex<--> interface name table. That takes minutes or hours to find the data you need.

**Comment by lucaderi** [comment]
In summary

- You would like to see in flows_stats.lua all flows on a given interfaceId similar to what we do with hosts and Ids
- map the interface index with a name (if mapping is available)
- if you are in a flows_stats.lua clicking on a host does not move you to the host page host_details.lua?host=XXX but to the flow page of the host host_details.lua?host=XXX&page=flows

Is this correct?

**Comment by lliopt** [comment]
Hi Luca,
Thank you for promt reply. 
1. From my understanding, you go to the devices tab to see the device(s) you have in `flowdevices_stats.lua` for example. There by clicking to the `Flow Exporter IP ` you reaching a table with ifindex/interface name, in/out bytes, rate(maybe?) and the most important - chart button/flows button.
That button should show table with flows related that interface only + amount of traffic transferred per flow.
Chart itself  be based on the service/tcp_unp_port/whatever.
2. Yes mapping interface name to ifindex would be nice to have
3. Is not that important. I just wanted to show you that information you probably interested  during the troubleshooting  requires a lot of clicks. If feature with per interfaces aggregation will be implemented this one will not be needed.

**Comment by lucaderi** [comment]
Do you have multiple routers exporting flows or just one? If one, an interim solution is to go in preferences -> expert view and set "Dynamic Flow Collection Interfaces" to "Ingress Flow Interface".

Our idea was to use virtual network interfaces to split traffic sent by multiple probes/exporters. I see you are requesting some enhancement and most of them make sense.

**Comment by lliopt** [comment]
Luca, yep we have multiple border routers  (6 as per now) with ~10 interfaces each with flow sampling and export enabled. 
If we start to use `Dynamic Flow Collection Interfaces` with `Ingress flow interface` system becomes even more unusable.
As result you will have list of interfaces  listed as nprobe_ip:port:[interface_ifindex]. So again you have no idea where to find your interface + there is a limit on amount of interfaces you can have because ntop starts to complain that some number is exceeded and I can't see all of the interfaces there.
There is an option to rename those interfaces to something like` router_name + interface_name + ifindex`, but how to navigate through all of them I don't know.

**Comment by rbott** [comment]
We have multiple core routers on different sites which are interconnected. They also have several peering links and downlinks to other  internal routers (connecting server networks).
To see incoming/outgoing external traffic and also internal-only traffic (e.g. between internal servers on different sites) we need to enable sflow exports on peering-, cross- and downlinks.

Either we miss a great portion of our traffic (e.g. by only exporting sflows from peering interfaces) or we nprobe/ntop will count many flows wrong, because the same packet passes through more than one router.

Only displaying flows from selected routers/interfaces would greatly improve the situation here.

**Comment by simonemainardi** [comment]
In the latest dev build we have added flow drill-down capabilities on the basis of the flow exporter address and its in/out interfaces

![image](https://user-images.githubusercontent.com/3397663/28431498-dc12d146-6d84-11e7-9d6d-fd88a3edd96b.png)

![image](https://user-images.githubusercontent.com/3397663/28431519-e75b0dc0-6d84-11e7-9f9c-bd2b2e0cfba9.png)

An earlier commit already introduced SNMP interfaces name in the flow details page

Any feedback is appreciated.
