### ISSUE TITLE
make error while installing nDPI for ntop

### ISSUE THREAD

**Issue by ayeshabasit** [ntop/ntopng#1327]
Here is my output, I installed pfring already as per instructions here http://www.ntop.org/get-started/download/

make  all-recursive
make[1]: Entering directory '/root/nDPI'
Making all in src/lib
make[2]: Entering directory '/root/nDPI/src/lib'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/nDPI/src/lib'
Making all in example
make[2]: Entering directory '/root/nDPI/example'
/bin/bash ../libtool  --tag=CC   --mode=link gcc -pthread  -g -O2 -static -ldl  -o ndpiReader ndpiReader.o ndpi_util.o ../src/lib/libndpi.la   /root/PF_RING/userland/libpcap/libpcap.a /root/PF_RING/userland/lib/libpfring.a -lnuma  -lrt -ldl   -lrt -ldl -lm 
libtool: link: gcc -pthread -g -O2 -o ndpiReader ndpiReader.o ndpi_util.o  ../src/lib/.libs/libndpi.a /root/PF_RING/userland/libpcap/libpcap.a /root/PF_RING/userland/lib/libpfring.a -lnuma -lrt -ldl -lm -pthread
/**usr/bin/ld: cannot find -lnuma
collect2: error: ld returned 1 exit status**
Makefile:393: recipe for target 'ndpiReader' failed
make[2]: *** [ndpiReader] Error 1
make[2]: Leaving directory '/root/nDPI/example'
Makefile:462: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/nDPI'
Makefile:371: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by emanuele-f** [comment]
Hi, open an issue here https://github.com/ntop/nDPI
