### ISSUE TITLE
load data from ntopng backup to logstash

### ISSUE THREAD

**Issue by gabbo9lli** [ntop/ntopng#1328]
Hello.
I'd like to load data from ntopng mysql backup.
Then I'm restoring backup in a new instance in a new environment where I've installed elk environment.
Is it possible to recover data and visualize them in the new environment with kibana?
how?
thanks
regards
gabbo

**Comment by simonemainardi** [comment]
@gabbo9lli assuming you have mysql data backed up in a .sql file generated with mysqldump, then you can import that data in a new database with:

```
mysql -uuser -ppassword new_database_name < database_backup.sql
```

once you have that data in mysql you have to push it into elasticsearch for kibana visualization

you can use logstash to extract mysql data and push it into ES. Here is a great tutorial that show this: https://qbox.io/blog/migrating-mysql-data-into-elasticsearch-using-logstash
