### ISSUE TITLE
Report and dashboard does not work

### ISSUE THREAD

**Issue by Jovannydejesus** [ntop/ntopng#133]
Good.
I am currently having problems with the option of graphical report on the dashboard, it disappears when changing interface, and when I restart the service returns ntopng again.
![no report opcion](https://cloud.githubusercontent.com/assets/13890698/9440614/77ce4960-4a3e-11e5-998c-3a08cff02345.jpg)

**Comment by lucaderi** [comment]
Please update ntopng to the git code and report.

**Comment by Jovannydejesus** [comment]
which it is the git code and report.

**Comment by Jovannydejesus** [comment]
I can explain

**Comment by lmangani** [comment]
Please update your setup to the latest ntopng version available on Github and re-test

**Comment by Jovannydejesus** [comment]
lmangani, Could you send me the link to download available on Github


Regards.

**Comment by lmangani** [comment]
You will have to clone and compile it from source

```
git clone https://github.com/ntop/ntopng.git
cd ntopng

./autogen.sh
./configure
make
make install
```

**Comment by Jovannydejesus** [comment]
I am installing and testing
I let you know

Thank you.

**Comment by lmangani** [comment]
Closing Issue - Re-Open as/if needed.
