### ISSUE TITLE
E: Unable to locate package nbox

### ISSUE THREAD

**Issue by Vizis** [ntop/ntopng#1330]
E: Unable to locate package nbox
AT apt-get install pfring nprobe ntopng ntopng-data n2disk cento nbox
 ofc after wget http://apt-stable.ntop.org/jessie/all/apt-ntop-stable.deb

**Comment by Vizis** [comment]
Debian 8.6 Jassie

**Comment by ValentinaViscarelli** [comment]
nbox supports just ubuntu 14 and ubuntu 16.
Debian 8.6 Jassie is not supported.
