### ISSUE TITLE
ntopng running on Raspberry Pi 3 isn't showing SNMP statistics but Windows is working

### ISSUE THREAD

**Issue by sofakng** [ntop/ntopng#1331]
I've just installed ntopng v3 on my Raspberry Pi 3 (raspian) and it's seeing traffic OK, but when I add an SNMP device it displays some basic information (description, object id, and name) but no interfaces are listed and the uptime is 0, etc.

When I install ntopng on Windows, it displays everything correctly for the same SNMP server.

Could I be missing packages on my raspberry pi 3 (raspian/debian) or something else?

Here is a log: [log.txt](https://github.com/ntop/ntopng/files/1100834/log.txt)

**Comment by simonemainardi** [comment]
I have just tested with `ntopng Enterprise/Embedded Edition v.3.1.170704` on RPI and can confirm it is working. However, with the packaged version, I experience the behaviour reported here. @lucaderi can you please trigger a new RPI build?

**Comment by simonemainardi** [comment]
I confirm this is fixed in the last build. The new RPI build is ready. Please update.
