### ISSUE TITLE
mysql/L7 dataretention question

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#1332]
it's just a simple question
I would like to know how is done dataretention inside ntopng ? I mean by example I configured to store for 30 days
so what's happen after 30 days ? + does it detect if harddrive is full (waring at 80% usage ?) ? is there something like rotation log ?

thanks

**Comment by simonemainardi** [comment]
rotation is performed daily (daily.lua). Every day at midnight, mysql records older than the specified number of days are `DELETE`d.
