### ISSUE TITLE
Duplicate Interfaces showing up

### ISSUE THREAD

**Issue by sethbeauchamp** [ntop/ntopng#1334]
I seem to have multiple interfaces show up (i've renamed the dropdown to "Nodes" in my box). See image: http://imgur.com/1vN2kzB

This was not occurring until i upgraded to v3.1. I am having remote nodes send netflow v9 to my ntop server. Example of my configurations...

NPROBE:
--zmq="tcp://*:5556"
--collector-port=2055
-V=9
-n=none
-i=none
I have multiple nprobe-x.conf files, one corresponding to each port in the ntopng.conf below.

NTOPNG:
-G=/var/run/ntopng.pid
--interface="tcp://127.0.0.1:5556"
--interface="tcp://127.0.0.1:5557"
--interface="tcp://127.0.0.1:5558"
-k flashstart:user:x
-m="172.16.0.0/9"

**Comment by simonemainardi** [comment]
have you selected the creation of virual interfaces of the basis of the exporter_ip/interface index from the ntopng preferences (entry Interfaces)?

**Comment by sethbeauchamp** [comment]
Oh oops. I didn't even realize that was there now. That looks to be the cause. Thanks.
