### ISSUE TITLE
Host Pool List: wrong data in host column

### ISSUE THREAD

**Issue by bioteseo** [ntop/ntopng#1335]
Hi,
ntopng stable version, in the host poll list (menu hosts -> host pools) I see more hosts (in number) than I defined in the host pool. When I click on host pool to see the list, the list is correct.
I defined three host pools with some IPs. For example an host pool with four hosts in host pool list has displayed with eight hosts, usually that number is the double....

Thanks

**Comment by simonemainardi** [comment]
can you post screenshots? Are the ips in any host pool duplicated? or are different ips?

**Comment by bioteseo** [comment]
They are different IPs in diffrent host pools: no overlapping
![screenshot from 2017-06-28 13-21-42](https://user-images.githubusercontent.com/316396/27635000-cbad1cfc-5c05-11e7-9699-de0fdc022605.png)
![screenshot from 2017-06-28 13-22-53-anonimized](https://user-images.githubusercontent.com/316396/27635001-cbb0c082-5c05-11e7-8910-eb87ddca1376.jpg)

**Comment by simonemainardi** [comment]
ok, thanks. We are working on that. Can you check and confirm you are seeing the same ip address with multiple macs? I think that that is the issue and is related to https://github.com/ntop/ntopng/issues/1315

**Comment by bioteseo** [comment]
I think there two different situations.
This issue is on ntopng stable version: 3.0.170623 - Community Edition and the hosts have different IP and different mac address, no overlapping. There could be overlapping on the default host pool (Not Assigned) but I can't check it. All pools defined from me and their hosts haven't overlapping.

I found the other issue  #1315 on ntopng dev version (now is 3.1.170628 - Community Edition) and it isn't about host pools. In ntopng stable version I didn't find issue #1315.

**Comment by simonemainardi** [comment]
@bioteseo can you please try with the latest ntopng 3.1 build and report? Commit https://github.com/ntop/ntopng/commit/eaa7a0d3130d9eeb2596a57c2d6b75eddca70707 should have fixed the issue.

**Comment by bioteseo** [comment]
Hi Simone,
in ntopng 3.1 I can't check the number in hosts pool. It's a big network, sorry.
My other ntopng (3.0 build) monitors a small network and it's easy to check that.
The other issue is surely fixed (255.255.255.255), thanks a lot.

**Comment by simonemainardi** [comment]
Thanks for reporting. To test it with 3.1 you may want to create a new host pool with just one host and see. Please, reopen if necessary.

**Comment by bioteseo** [comment]
Hi Simone,
as you suggest I temporary modified an host pool. I inserted only an host and the host pool view displays the right value for that pool.
Thanks

**Comment by bioteseo** [comment]
Hi Simone,
the issue #1335 is in the stable version (3.0.170719) but not in the dev version (3.1.170720 )....

Thanks

**Comment by bioteseo** [comment]
@simonemainardi 
Hi Simone,
the issue #1335 is again in the stable version but not in the dev version...

Thanks

**Comment by simonemainardi** [comment]
yes, please use dev as the fix is not critical and thus cannot be backported
