### ISSUE TITLE
Ntopng Segfault (3.0.170623-3081)

### ISSUE THREAD

**Issue by MartinOehler** [ntop/ntopng#1337]
Hello,

we encounter a segfault after ntopng runs for a couple of days.

Version/Kernel Information: 
```
# dpkg -l | grep ntop
ii  apt-ntop-stable                2.4-535                              all          ntop stable apt package repository
ii  ntopng                         3.0.170623-3081                      amd64        Web-based traffic monitoring.
ii  ntopng-data                    3.0.170623                           all          Data files (geoip) for ntopng.
ii  pfring                         6.6.0-1301                           amd64        PF_RING (http://www.ntop.org/pf_ring/) [6.6.0-stable:8b2814521c227bc265ea932c73b8d454d7aa20ef (Fri Jun 23 20:29:19 2017 +0200)]

# dpkg -l | grep linux-image
ii  linux-image-3.16.0-4-amd64     3.16.43-2+deb8u2                     amd64        Linux 3.16 for 64-bit PCs
```
OS: Debian 8.8

kern.log:
```
Jun 26 10:30:28 host kernel: [163733.937751] traps: ntopng[9266] general protection ip:7fe3b5f5eb5b sp:7fe364fe8550 error:0 in libc-2.19.so[7fe3b5ee6000+1a1000]

Jun 27 12:30:37 fw16 kernel: [257311.216441] ntopng[25436]: segfault at 11e8 ip 000000000045a305 sp 00007fff5b0d4ed0 error 4 in ntopng[400000+25a000]
```

/var/log/ntopng.log:
```
27/Jun/2017 08:47:21 [HTTPstats.cpp:517] WARNING: Too many virtual hosts 4096: enlarge hash
27/Jun/2017 11:04:50 [Lua.cpp:5500] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[158] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.
27/Jun/2017 12:04:50 [Lua.cpp:5500] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[158] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.
```

ntopng is listening on 30 interfaces (which btw. is less that we would need), /var/tmp is filled with about 30 GB of data and there is plenty of space left. The system doesn't show remarkable I/O wait or other signs of weakness.

May I provide more information to help you debugging this segfault?

Thanks,
Martin

**Comment by simonemainardi** [comment]
hi martin, 

Thanks for providing feedback.

the segfault and the errors "Cannot complete local hosts RRD dump in 5 minutes" may not be related. In order to investigate the segfault, can you please generate a core dump and upload it along with the ntopng binary?

By the way, how many local hosts do you have if you consider all the interfaces?

**Comment by MartinOehler** [comment]
Hi Simone,

do you have src packages available? I read the bug report guide and since this is a production system, source packages would help generating debug packages more quickly. The ntop-stable.list doesn't contain deb-src lines. 

When building packages, where could I raise the interface limit? 30 VLANs aren't that much nowadays in a bigger network.

The value might not be representative at daytime but the arp table shows a bit about 400 hosts. I would suggest there might be up to 100 more on busy days.

Thanks,
Martin

**Comment by simonemainardi** [comment]
matt, you don't need a source package. The ntopng binary is compiled with debug symbols so it is ok for the generation of a core dump.

So please just do `ulimit -c unlimited`, run ntopng, and then upload the core file and the ntopng binary (under /usr/local/bin) for our inspection.

as regards the vlans, are you using vlan-based virtual interfaces? Is this the reason why you want to increase the number?

**Comment by MartinOehler** [comment]
It died three times today without dumping a core file. I made sure that ```ulimit -c unlimited``` is set. 

The script I used was
```
#!/bin/bash

ulimit -c unlimited
ulimit -a

/usr/local/bin/ntopng \
-G=/var/run/ntopng.pid \
-i bond0.100 \
[...]
local-networks="..."
```
The output
```
# ./ntopng.sh
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63772
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65536
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63772
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
29/Jun/2017 10:45:26 [Prefs.cpp:907] Localhost HTTP user login disabled
29/Jun/2017 10:45:26 [Ntop.cpp:1359] Setting local networks to 127.0.0.0/8
[...]
```
So the ulimit call seems to have succeeded. 

Additionally, we updated to the current version:
```
# dpkg -l | grep ntop
ii  apt-ntop-stable                2.4-535                              all          ntop stable apt package repository
ii  ntopng                         3.0.170629-3093                      amd64        Web-based traffic monitoring.
ii  ntopng-data                    3.0.170629                           all          Data files (geoip) for ntopng.
ii  pfring                         6.6.0-1314                           amd64        PF_RING (http://www.ntop.org/pf_ring/) [6.6.0-stable:56e0b475a587747310412fb6e47e7eaf69439e95 (Wed Jun 28 20:37:26 2017 +0200)]
```
Concerning your question: yes, all interfaces are VLANs.

**Comment by simonemainardi** [comment]
martin, please check the `core_pattern` in `/proc/sys/kernel` 

to make sure a crash will generate the core dump, please send a -SEGV signal to the process and check for dump generation. If you can find the core, delete it and let the process run and crash spontaneously.

this is a reference that can help: https://sigquit.wordpress.com/2009/03/13/the-core-pattern/

**Comment by MartinOehler** [comment]
I wrote a small C program that segfaults and dumps a core without a problem. Seriously I'm quite puzzled why I can ```kill -11 / kill -s SIGSEGV``` any program (screen, bash) I try but ntopng refuses to give me a core. I even compiled it, used another Debian Jessie system - no success. At least it's consistent.

I'm searching for a solution...

Edit: ```ntopng -s``` did the trick since ntop does a suid to user nobody. Alternatively, ```fs.suid_dumpable``` needs to be modified.

We're waiting for the next crash.

**Comment by MartinOehler** [comment]
Since you got the core some days ago - did you find the problem?

If not, can I provide more information to be of assistance solving this issue?

**Comment by simonemainardi** [comment]
I received the core but not the executable. I need the ntopng binary to analyze the core. I requested it but didn't get any reply:


> Martin, I downloaded the core but I can't find the ntopng binary executable. Please, send me the download link.

**Comment by MartinOehler** [comment]
I shared it again with you. It should be easy to get for you even without me since you have the debian packages containing the binary inside your own repository. It's version 3.0.170629-3093 (I did an update before starting the latest tests).

**Comment by simonemainardi** [comment]
Thanks for sharing. Can you please try and update to the latest 3.1 dev version? I have made several fixes that should solve this issue. Thanks.

**Comment by MartinOehler** [comment]
The latest dev version didn't crash for almost a week so I think we can consider this bug closed.

Will you backport the fixes to the stable version?

**Comment by simonemainardi** [comment]
Thanks, fixes have already been backported to stable
