### ISSUE TITLE
I was on the professional version, but after upgrading to v.3.1.170629 via apt-get, I'm back on community?

### ISSUE THREAD

**Issue by nate-byrnes** [ntop/ntopng#1338]
Hi there, I've been using the ntop repository to update my ntopng version periodically, and this time I did it, I lost the professional edition..... please advise.

   Thanks,
   Nate

**Comment by simonemainardi** [comment]
nate, please make sure your license has been generated less than one year ago.

**Comment by nate-byrnes** [comment]
Where is the license file? Is the license check only performed at startup?
This was the first time I restarted ntopng in 3-4 months. I suspect that it
has been over a year now.

**Comment by simonemainardi** [comment]
@nate-byrnes if it is over than a year, then you have to renew the maintenance (http://www.ntop.org/support/faq/how-can-i-renew-maintenance-for-commercial-products/).

License file is under /etc/ntopng/ntopng.conf  and license check is performed both at startup and at runtime.

please, do a ntopng --check-license

**Comment by nate-byrnes** [comment]
Thank you Simone, the license had expired.
