### ISSUE TITLE
No historical data and no active flows sometime

### ISSUE THREAD

**Issue by mhercek** [ntop/ntopng#1339]
**Environment:**
CentOS Linux release 7.3.1611
ntopng x86_64 v.3.1.170619, Small Business Edition
nprobe x86_64 v8.1.170619-5790

**Problem:**
Cannot see any data in Historical Data Explorer.
Sometimes I cannot see any active flows although my network is quite busy all day long.

30/Jun/2017 08:14:57 [PeriodicActivities.cpp:56] Started periodic activities loop...
30/Jun/2017 08:14:57 [NtopPro.cpp:297] [LICENSE] ntopng systemId: --censored--
30/Jun/2017 08:14:57 [NtopPro.cpp:308] [LICENSE] ntopng license: --censored--
30/Jun/2017 08:14:57 [NtopPro.cpp:330] [LICENSE] Maintenance is available until Fri Aug  4 06:32:39 2017 [34 days left]
30/Jun/2017 08:14:57 [NetworkInterface.cpp:2056] Started packet polling on interface tcp://127.0.0.1:5555 [id: 7]...
30/Jun/2017 08:14:57 [NetworkInterface.cpp:2056] Started packet polling on interface tcp://127.0.0.1:5556 [id: 8]...
30/Jun/2017 08:14:57 [NetworkInterface.cpp:2056] Started packet polling on interface tcp://127.0.0.1:5557 [id: 9]...
30/Jun/2017 08:14:57 [NetworkInterface.cpp:2056] Started packet polling on interface tcp://127.0.0.1:5558 [id: 10]...
30/Jun/2017 08:14:58 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface tcp://127.0.0.1:5555...
30/Jun/2017 08:14:58 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface tcp://127.0.0.1:5556...
30/Jun/2017 08:14:58 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface tcp://127.0.0.1:5558...
30/Jun/2017 08:14:58 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface tcp://127.0.0.1:5557...
30/Jun/2017 08:14:58 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntop] for interface tcp://127.0.0.1:5555
30/Jun/2017 08:14:58 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntop] for interface tcp://127.0.0.1:5556
30/Jun/2017 08:14:58 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntop] for interface tcp://127.0.0.1:5558
30/Jun/2017 08:14:58 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntop] for interface tcp://127.0.0.1:5557
30/Jun/2017 08:14:58 [CollectorInterface.cpp:115] Collecting flows on tcp://127.0.0.1:5555
30/Jun/2017 08:14:58 [CollectorInterface.cpp:115] Collecting flows on tcp://127.0.0.1:5556
30/Jun/2017 08:14:58 [CollectorInterface.cpp:115] Collecting flows on tcp://127.0.0.1:5557
30/Jun/2017 08:14:58 [CollectorInterface.cpp:115] Collecting flows on tcp://127.0.0.1:5558

MariaDB [ntopng]> select count(*) from flowsv4;  
+----------+
| count(*) |
+----------+
|  5740820 |
+----------+
But number of records is not increasing!
No errors in ntopng.log or mysql.log.
There's a plenty of disk space available.

Screenshots for better understanding of my issue.

![2017-06-30 08_11_31-welcome to ntopng](https://user-images.githubusercontent.com/20775751/27723729-b9df507a-5d6e-11e7-80de-8c2ea2c2888d.png)
![2017-06-30 08_11_53-welcome to ntopng](https://user-images.githubusercontent.com/20775751/27723730-b9e2a2d4-5d6e-11e7-8414-ef41e043640b.png)
![2017-06-30 08_12_42-welcome to ntopng](https://user-images.githubusercontent.com/20775751/27723727-b9dc3926-5d6e-11e7-80dd-b7bbaafb49f7.png)
![2017-06-30 08_13_15-welcome to ntopng](https://user-images.githubusercontent.com/20775751/27723728-b9de36a4-5d6e-11e7-81d7-87ef572d564d.png)

**Comment by simonemainardi** [comment]
please, make sure to select an interface that has traffic in the selected period. Use the dropdown 'Interfaces' menu to select an interface, and then go to the historical data explorer.

**Comment by mhercek** [comment]
> make sure to select an interface that has traffic in the selected period

I am trying to see data from the interface which has traffic 24/7.

**Comment by mhercek** [comment]
I've used --verbosity 6 and I found no MySQL errors or warnings in /var/log/ntopng/ntopng.log.
I've dropped ntopng database and let ntopng recreate it - it didn't help to solve my problem.
There certainly are flows (with --verbosity 6 they're logged /var/log/ntopng/ntopng.log)

**Comment by simonemainardi** [comment]
@mhercek could that be an issue related to clocks synchronization? That is, first and last switched timestamps received in the collected flows are aligned with the machine clock?

**Comment by mhercek** [comment]
Clocks seem to be fine.

**$ date**
Mon Jul  3 12:59:50 CEST 2017

**/var/log/ntopng.log**
03/Jul/2017 12:58:06 [CollectorInterface.cpp:210] {"8":"192.168.xxx.xxx","12":"91.235.xxx.xxx","1":657,"7":52668,"11":443,"6":0,"4":6,"5":0,"16":0,"17":57788,"56":"D4:85:64:01:xx:xx","80":"00:00:00:00
:00:00","27":"::","28":"::","22":1499079449,"21":1499079454, "57943":"127.0.0.1"} [msg_id=500368]

**$ date -d 1499079449**
Mon Jul  3 12:57:29 CEST 2017

**$ date -d 1499079454**
Mon Jul  3 12:57:34 CEST 2017

**Comment by simonemainardi** [comment]
@mhercek when you say `I cannot see any active flows`, do you mean both in the ntopng Flows page and in the historical data explorer, or both? Any change to get a remote access to the box to see?

**Comment by mhercek** [comment]
I have four running NProbe instances, three of them are collecting NetFlow exports from routers and one of them is receiving mirrored traffic and producing NetFlow records itself.
I think we should focus on the problem why there are not any flows stored in MySQL.
The instance of NProbe which is receiving mirrored traffic has always active flows.

**Comment by simonemainardi** [comment]
visit the interface stats page. There is the count of mysql exported flows, as well as the rate at which flows are exported to mysql. Is that counter increasing? What is the value of the rate?

**Comment by mhercek** [comment]
It's the same (zero exported flows) for all four interfaces.

![image](https://user-images.githubusercontent.com/20775751/27876259-b9183bce-61b6-11e7-8d85-1d4a36f07988.png)

**Comment by mhercek** [comment]
I made a packet capture and it's obvious from it that ntopng does not communicate with MySQL.
Only TCP communication between ntopng and MySQL is during ntopng startup/restart when it's checking table schema.

**Comment by simonemainardi** [comment]
@mhercek please, start ntopng with only one interface at time, let it run for a while, and then post here the full output. Check if the issue occurs with all the interfaces.

The fact that it says 0 exported flows and 0 errors could indicate that:
 - no flow is ever considered expired by ntopng (perhaps because it receives uptates from the nprobe). Inspecting the 'active flows' timeseries under the interface chart can help understanding this.
- mysql export process silently quits (this should only happen if the first database connection attempt fails)

**Comment by mhercek** [comment]
Haven't I omitted some crucial NetFlow field in order to process flows correctly by ntopng?
`/usr/local/bin/nprobe --zmq tcp://127.0.0.1:5556 -i none -n none --collector-port 9996 -V 9 -T"%IPV4_SRC_ADDR %IPV4_DST_ADDR %IN_BYTES %L4_SRC_PORT %L4_DST_PORT %TCP_FLAGS %PROTOCOL %SRC_TOS %SRC_AS %DST_AS %IN_SRC_MAC %OUT_DST_MAC %IPV6_SRC_ADDR %IPV6_DST_ADDR %FIRST_SWITCHED %LAST_SWITCHED"`

> Inspecting the 'active flows' timeseries under the interface chart can help understanding this.

![image](https://user-images.githubusercontent.com/20775751/27991552-e8022096-647a-11e7-98da-a9ddbadef7b3.png)

![image](https://user-images.githubusercontent.com/20775751/27991557-fc939210-647a-11e7-9410-d6c45e857988.png)

![image](https://user-images.githubusercontent.com/20775751/27991558-032e06fa-647b-11e7-92f4-f54a20313d20.png)

![image](https://user-images.githubusercontent.com/20775751/27991559-09547cd0-647b-11e7-9647-438e840576c6.png)

**Comment by simonemainardi** [comment]
@mhercek try not to specify the template.

Also, it is unlikely that the chart enclosed is related to the active flows. Indeed, the y axis says Gbps. Please, make sure to select the 'active flows' from the dropdown 'timeseries'

**Comment by mhercek** [comment]
> try not to specify the template

Well then, how do I include MAC addresses?

**Comment by simonemainardi** [comment]
For the macs you need the template but first try not to use it. Also please address the other things pointed out in my previous message. In order to speed things up please consider giving me ssh access to the box.

**Comment by mhercek** [comment]
> For the macs you need the template but first try not to use it.

I've appended these fields: %IPV4_NEXT_HOP %INPUT_SNMP %OUTPUT_SNMP and %IN_PKTS
and it's working now, I can see and browse exported records. I have no time to further investigate which particular record or records are needed by ntopng in order to function properly.

**Comment by simonemainardi** [comment]
thanks for reporting
