### ISSUE TITLE
Interface label

### ISSUE THREAD

**Issue by mhercek** [ntop/ntopng#1340]
I need to distinguish between my interfaces and something like **tcp://127.0.0.1:5555** is not very helpful.
See screenshot below for better understanding of my feature request.

![label](https://user-images.githubusercontent.com/20775751/27723944-c3966ef4-5d6f-11e7-8488-cfa6aef73048.png)

**Comment by simonemainardi** [comment]
To specify a custom name, visit the interface details page, select the gear (configuration) and specify a use field "Custom Name":

![image](https://user-images.githubusercontent.com/3397663/27725804-49c419d8-5d78-11e7-9064-2f5ccd3e9076.png)
