### ISSUE TITLE
Lua error in Purge Past Alerts

### ISSUE THREAD

**Issue by mhercek** [ntop/ntopng#1341]
**Environment:**
CentOS Linux release 7.3.1611
ntopng x86_64 v.3.1.170619, Small Business Edition
nprobe x86_64 v8.1.170619-5790

**Problem:**
![error](https://user-images.githubusercontent.com/20775751/27730505-b5e0dd5c-5d89-11e7-82c1-7b18f4be4ccf.png)

**Comment by simonemainardi** [comment]
just tried to reproduce on centos7 without success. Everything works properly. Can you please try and update to the latest version? Also, from which page are you performing the delete?

**Comment by mhercek** [comment]
Confirmed that it's solved in the latest version.

**Comment by simonemainardi** [comment]
thanks for reporting
