### ISSUE TITLE
clarification on hardware requirements

### ISSUE THREAD

**Issue by matteoluc** [ntop/ntopng#1343]
Hello,
          i would like to know how many cores / CPU and how much RAM would serve to monitor the traffic of about 50 classes C with ntopng.

**Comment by simonemainardi** [comment]
If you are running ntopng to capture packets, then you should consider 3-4Gbps as the maximum rate that can be handled by a single core. For rates that go beyond this, you can use RSS with PF_RING zero copy to load balance the packets across multiple threads.

As you mentioned 50 C-class addresses, assuming all your addresses are local, I estimate a 256 * 50 ~ 12k local hosts in the worst case. Although 2-4 GB RAM will suffice, you should plan to provision fast disks or even better SSDs as every 5 minutes ntopng will perform I/O for 12k hosts.
