### ISSUE TITLE
ntopng on windows 7 can't run

### ISSUE THREAD

**Issue by Howard-Chang** [ntop/ntopng#1344]
Hi everyone,
    I installed ntopng on my virtual machin (win 7), After I opened the task manager and start the ntopng 
    service, it showed that"The operation could not be complete.  Access is denied."
    I have tried many times, and I don't know how to solve the problem.
    I am a student and doing my project. I need to use the tool but it looks  can't work .
    coud you help me .
    thanks a lot!    : )

**Comment by simonemainardi** [comment]
Try to run ntopng from the windows console and post any possible errors. You can find instructions in the user guide

**Comment by Howard-Chang** [comment]
![default](https://user-images.githubusercontent.com/19474557/27858646-984da6c6-61a8-11e7-9de2-24dec761b7c6.png)

**Comment by Howard-Chang** [comment]
![default](https://user-images.githubusercontent.com/19474557/27860817-c1570dca-61b0-11e7-9529-1c1451dedd97.png)

**Comment by Howard-Chang** [comment]
I ran the ntopng on cmd
Thank you for your help : )

**Comment by Howard-Chang** [comment]
when I opened the task manager and start the ntopng
service, it showed that"The operation could not be complete. Access is denied."

**Comment by simonemainardi** [comment]
make sure to open the cmd as Administrator. Then run ntopng.exe and post the output

**Comment by Howard-Chang** [comment]
![default](https://user-images.githubusercontent.com/19474557/27865807-90d8b5ca-61c6-11e7-9709-dc4314c1c36d.png)

**Comment by Howard-Chang** [comment]
the result is the same. : (

**Comment by simonemainardi** [comment]
please read the user guide to see how to properly start ntopng from the cmq. it's written there. the report the output

**Comment by Howard-Chang** [comment]
![default](https://user-images.githubusercontent.com/19474557/27868609-dec08994-61cf-11e7-8d8d-3bf41ba85168.png)

**Comment by Howard-Chang** [comment]
I could run ntopng!
but when I open the browser it couldn't work.

**Comment by Howard-Chang** [comment]
![default](https://user-images.githubusercontent.com/19474557/27869181-b35b74c4-61d1-11e7-90cc-5a41f3de554d.png)

**Comment by emanuele-f** [comment]
@Howard-Chang please read our user guide https://github.com/ntop/ntopng/blob/dev/doc/UserGuide.pdf for the basic information on how to run ntopng on windows

**Comment by simonemainardi** [comment]
no feedback received. If necessary open another issue and submit the requested information.
