### ISSUE TITLE
new version NTOPNG useed all mem and traffic on dashboard no correct

### ISSUE THREAD

**Issue by wsf535** [ntop/ntopng#1345]
[xxx@ntopng-p-049002 ~]$ free -h
                     total        used        free      shared  buff/cache   available
Mem:            62G         46G        6.5G         19M          9G         15G
Swap:            0B          0B          0B

only start ntopng  6 hours.

**Comment by simonemainardi** [comment]
please try and report with the latest 3.1 as we have done a major change

**Comment by simonemainardi** [comment]
@wsf535 did you try with version 3.1?

**Comment by wsf535** [comment]
version 3.1 memery usage has problem.
​

2017-07-11 0:53 GMT+08:00 simonemainardi <notifications@github.com>:

**Comment by simonemainardi** [comment]
please try with the latest build. I have fixed some mem leaks that could have been causing your OOM

**Comment by wsf535** [comment]
thanks , I install latest build (ntopng-3.1.170712-2988) and it's ok now.

2017-07-11 20:25 GMT+08:00 simonemainardi <notifications@github.com>:

**Comment by simonemainardi** [comment]
thanks for reporting
