### ISSUE TITLE
How to set 'admin' password with a text file

### ISSUE THREAD

**Issue by narcisgarcia** [ntop/ntopng#1347]
I'm trying ntopng v.2.4.170204 [Community Edition] on Debian 9

File /usr/share/doc/ntopng/README.users says "It is possible to provide ntopng a list of users credentials in a text file".
Which path must have this file to be read by ntopng service?
Otherwise; How to specify the text file to be read by ntopng service?

* As it's well known, web interface complains with "Missing CSRF parameter" both for preferences and users configuration. I'm not interested into redis-cli.

**Comment by simonemainardi** [comment]
please, update to version 3.0, 2.4 is no longer supported.

To add users programmatically, you can use the following bash script: https://github.com/ntop/ntopng/blob/dev/httpdocs/misc/ntopng-add-user.sh

The README.users you are referring to is outdated and I will update it now.

**Comment by narcisgarcia** [comment]
Does this script include the possibility to CHANGE admin password on ntopng 2.4 ?
Does redis-cli set accounts to be used/shared by other programs? Can be this a conflict?

**Comment by simonemainardi** [comment]
> Does this script include the possibility to CHANGE admin password on ntopng 2.4 ?

yes

> Does redis-cli set accounts to be used/shared by other programs?

no

> Can be this a conflict?

no
