### ISSUE TITLE
ntopng detect Skype Traffic , but there is no skype installed on workstations

### ISSUE THREAD

**Issue by AlekMarkus** [ntop/ntopng#135]
i can see that ntopng detect Skype Traffic from specific workstation (450 MB) but there is no skype installed on this workstation how its possible ?   the same happening with TOR i can see traffic in my network (40MB) from 4 workstaions , but there is no TOR installed on those workstations 

i have attached pcap file from Skype Traffic that can be download from here : 

https://www.dropbox.com/s/5x9r1nsvfb5pfr6/Skype%20Traffic.pcap?dl=0

Best Regards,
Alek

**Comment by lmangani** [comment]
Thanks for your report - This is related to nDPI, could you kindly open your issue here:  https://github.com/ntop/nDPI/issues
