### ISSUE TITLE
Windows Install of 3.1.170706 still showing 3.0.170606 in GUI

### ISSUE THREAD

**Issue by smooi** [ntop/ntopng#1352]
Uninstalled 3.0.170606, Win10Pcap and Redis, installed 3.1.170706 from current download and web GUI is still showing ntopng Pro [Small Business Edition] Edition v.3.0.170606.

Control Panel Programs and Features is showing v3.1.170706

Are there old .exe's residing somewhere or is the new installer still installing the old version?

**Comment by emanuele-f** [comment]
Hi, please try to remove the ntopng service with `ntopng /r` and then reinstall it with `ntopng /i ..options..`

**Comment by smooi** [comment]
Removed service via ntopng /r, removed ntopng, Redis, Winpcap, made sure Program files folders were empty, reinstalled and nTop version in web GUI  3.0.170606 - Enterprise Edition

I just installed ntop, from a fresh download of ntopng-3.1.170706-x64.exe, on a machine that has never had nTop installed and web GUI is showing ntopng Enterprise Edition v.3.0.170606 as well.

**Comment by lucaderi** [comment]
Uploading new build 3.1.170713

**Comment by smooi** [comment]
This build took care of the version update issues and other issues we were having on the 1st build of v3 with client-server discrepancies.

**Comment by emanuele-f** [comment]
Nice, thank you for reporting
