### ISSUE TITLE
Problem with Version in the Home Page

### ISSUE THREAD

**Issue by matteoluc** [ntop/ntopng#1353]
Hello, 
         I'am using ntopng v.3.0.170705 with nprobe v.8.0.170705 on a remote server with centOS 7.3.1611. 
I've the license of nprobe Pro on the local machine, from which i recall ntopng from the browser, executed on the remote server.
In the homepage, in the "version" line, I have the following problem:
![img-9195](https://user-images.githubusercontent.com/29771833/28029881-d10e81cc-65a1-11e7-8032-e386c4e2d56f.jpg)

how can i solve it?
I'm looking forward to hearing from you.
Thank you. 
Matteo

**Comment by simonemainardi** [comment]
that has already been fixed. Please the package and it will work.
