### ISSUE TITLE
can't access to the ntop web(localhost:3000) on win7

### ISSUE THREAD

**Issue by Howard-Chang** [ntop/ntopng#1355]
Hi,
   I download the version of "ntopng-3.1.170606-x64.zip".After I installed it(ntopng /i) and run it
(ntopng /c) it show me the following log, and I have got the license, just can't  access to the ntop web(localhost:3000) and don't know how to use it.Because it seems to have to store the license to the ntopng web GUI.

05/Jul/2017 13:04:43 [Ntop.cpp:1359] Setting local networks to 127.0.0.0/8
05/Jul/2017 13:04:43 [Redis.cpp:109] Successfully connected to redis 127.0.0.1:6379@0
05/Jul/2017 13:04:43 [NtopPro.cpp:144] [LICENSE] Read license from Redis []
05/Jul/2017 13:04:43 [NtopPro.cpp:196] ERROR: [LICENSE] Invalid or missing ntopng License [Empty license file]
05/Jul/2017 13:04:43 [NtopPro.cpp:209] WARNING: [LICENSE] ntopng will now run in enterprise edition for 10 minutes
05/Jul/2017 13:04:43 [NtopPro.cpp:211] WARNING: [LICENSE] before returning to community mode
05/Jul/2017 13:04:43 [NtopPro.cpp:212] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
05/Jul/2017 13:04:43 [NtopPro.cpp:213] WARNING: [LICENSE] or run ntopng in community mode starting
05/Jul/2017 13:04:43 [NtopPro.cpp:214] WARNING: [LICENSE] ntopng --community
05/Jul/2017 13:04:43 [PcapInterface.cpp:86] Reading packets from interface {9A40E61D-2D66-4619-8251-3E71D07E0F69}...
05/Jul/2017 13:04:43 [PcapInterface.cpp:91] WARNING: Unable to set packet capture direction
05/Jul/2017 13:04:43 [Ntop.cpp:1485] Registered interface {9A40E61D-2D66-4619-8251-3E71D07E0F69} [id: 0]
05/Jul/2017 13:04:43 [HTTPserver.cpp:758] HTTPS Disabled: missing SSL certificate C:\Program Files\ntopng\httpdocs/ssl/ntopng-cert.pem
05/Jul/2017 13:04:43 [HTTPserver.cpp:760] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
05/Jul/2017 13:04:43 [HTTPserver.cpp:814] Web server dirs [C:\Program Files\ntopng\httpdocs][C:\Program Files\ntopng\scripts]
05/Jul/2017 13:04:43 [HTTPserver.cpp:817] HTTP server listening on port(s) 3000
05/Jul/2017 13:04:43 [main.cpp:311] Working directory: C:\Users\Howard\Documents\ntopng
05/Jul/2017 13:04:43 [main.cpp:313] Scripts/HTML pages directory: C:\Program Files\ntopng
05/Jul/2017 13:04:43 [Ntop.cpp:307] Welcome to ntopng x64 v.3.0.170606 - (C) 1998-17 ntop.org
05/Jul/2017 13:04:43 [Ntop.cpp:312] Built on Windows
05/Jul/2017 13:04:43 [PeriodicActivities.cpp:56] Started periodic activities loop...
05/Jul/2017 13:04:44 [NtopPro.cpp:273] [LICENSE] ntopng systemId: 1413723142-76066b0a
05/Jul/2017 13:04:44 [NtopPro.cpp:278] [LICENSE] ntopng is starting in demo mode
05/Jul/2017 13:04:44 [Ntop.cpp:510] Adding 10.0.2.0/24 as IPv4 local network for 
05/Jul/2017 13:04:44 [Ntop.cpp:516] Adding 10.0.2.15/32 as IPv4 interface address for {9A40E61D-2D66-4619-8251-3E71D07E0F69}
05/Jul/2017 13:04:44 [NetworkInterface.cpp:2045] Started packet polling on interface {9A40E61D-2D66-4619-8251-3E71D07E0F69} [id: 0]...
05/Jul/2017 13:16:55 [NetworkInterface.cpp:1674] Invalid packet received [len: 1599][max-len: 1518].
05/Jul/2017 13:16:55 [NetworkInterface.cpp:1675] WARNING: If you have TSO/GRO enabled, please disable it

**Comment by simonemainardi** [comment]
please, install the latest windows build available and then try to access by pointing your browser to http://127.0.0.1:3000

**Comment by Howard-Chang** [comment]
Thanks !!! It works now. But why localhost:3000 can't run @@?

**Comment by Howard-Chang** [comment]
sorry I found that it should add http:// in front of the web address ..

**Comment by simonemainardi** [comment]
thanks
