### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by AntonMay** [ntop/ntopng#1356]
Hi

We have 2 licence's

1. ntopng Pro SMB
2. nProbe Pro with Plugin support 

both are out of maintenance support. I am upgrading to a new server with Ubuntu 16.04 and Percona MySQL 5.7.

Can I move my licence from the old server to the new server?

**Comment by simonemainardi** [comment]
no, as they are out of maintenance. Please, consider renewing the maintenance http://www.ntop.org/support/faq/how-can-i-renew-maintenance-for-commercial-products/
