### ISSUE TITLE
nTop 3.1x alerts / syslog...

### ISSUE THREAD

**Issue by smooi** [ntop/ntopng#1357]
We're wanting to get some of the nTop alerts via email or better yet, Syslog.  Can you point me to current documentation on how to do this?  I see references to Syslog in Preferences, but I'm not sure how to configure.  We're running nTop for Windows, current 3.1 build, Pro Small Business license.

Thanks.

**Comment by simonemainardi** [comment]
Currently, mail alerts are not supported even though they are on our plans.

To send trace messages to syslog, just turn the preferences switch on:
![image](https://user-images.githubusercontent.com/3397663/28261403-75554846-6adf-11e7-8871-161c15eab34d.png)

**Comment by smooi** [comment]
How do I configure the nTop System Syslog so I can get the logs to our own syslog server?
Thanks.

**Comment by simonemainardi** [comment]
we already have a feature request for that: https://github.com/ntop/ntopng/issues/282
