### ISSUE TITLE
ntoppng not displaying netflow traffic

### ISSUE THREAD

**Issue by kickinit24** [ntop/ntopng#1358]
Hello,
I recently installed Ntop and I love it so far. However I am unable to pull any netflow data from my router. Ntop is only displaying 1 network. Seems like it is only capturing the network traffic between my pc and the ntop server\collector. I have enabled and confirmed that netflow data from router is trying to send to the ntop collector. Any help would be much appreciated.
Thank you,

**Comment by simonemainardi** [comment]
This question has been posted three times: mailing list, shop, and github. Next time please do not triple-post the same question.

I paste here the reply I have given on the mailing list

> In order to monitor net flow data you need to use ntopng in combination with nProbe.  
> 
> Assuming your have configured your devices to export Netflow on port 2055, you can use this configuration:
> 
> ./nprobe -i none -n none --collector-port 2055 --zmq tcp://*:5556
> 
> This configuration will collect flows and deliver them to ntopng that you can configure as follows:
> 
> ./ntopng -i tcp://<nProbe host IP>:5556 --local-networks "a list of comma separated networks in CIDR notation"
>

**Comment by simonemainardi** [comment]
according to the mailing list, this question is answered.
