### ISSUE TITLE
problems with ntopng

### ISSUE THREAD

**Issue by matteoluc** [ntop/ntopng#1360]
Hi, I'm using nprobe to capture v5 flows and ntopng as a collector.
Traffic Dashboard Page, Host Page, Alert Pages, ecc. work normally.

I have these 3 errors:
1)Last Log Trace :
17/Jul/2017 12:04:09 [PeriodicActivities.cpp:101] ERROR: Missing script //second.lua
17/Jul/2017 12:04:08 [PeriodicActivities.cpp:101] ERROR: Missing script //second.lua
17/Jul/2017 12:04:08 [PeriodicActivities.cpp:101] ERROR: Missing script //housekeeping.lua
17/Jul/2017 12:04:07 [PeriodicActivities.cpp:101] ERROR: Missing script //second.lua
17/Jul/2017 12:04:06 [PeriodicActivities.cpp:101] ERROR: Missing script //second.lua

2) The Traffic Report Page doesn't show any charts.
3) Network Page and Flows Page print "no results found".

I'm using nProbe Pro 8.0.170714 with License and ntopng Enterprise Edition v 3.0.170714 with License on centOS Linux release 7.3.1611

The configuration file of nprobe is:
-g=/var/run/nprobe-zmq.pid
--collector-port=9995
-i=none
-V=5
--zmq=tcp://*:2055
--online-license-check
-b2

The configuration file of ntopng is:
-G=/var/run/ntopng.pid
--interface=tcp://127.0.0.1:2055
-m="x.x.x.x/20"
-v3

What could I do?

**Comment by matteoluc** [comment]
The first error is:

Last Log Trace :
 17/Jul/2017 12:04:09 [PeriodicActivities.cpp:101] ERROR: Missing script //second.lua 
17/Jul/2017 12:04:08 [PeriodicActivities.cpp:101] ERROR: Missing script //second.lua 
17/Jul/2017 12:04:08 [PeriodicActivities.cpp:101] ERROR: Missing script //housekeeping.lua 
17/Jul/2017 12:04:07 [PeriodicActivities.cpp:101] ERROR: Missing script //second.lua 
17/Jul/2017 12:04:06 [PeriodicActivities.cpp:101] ERROR: Missing script //second.lua

**Comment by simonemainardi** [comment]
I have just tested the binary package of ntopng EE on centos7 and everything is working as expected. How did you install it?

From the error shown, it seems that necessary lua scripts are missing in error 1). Error 2) and 3) are consequences of 1).

Post the full ntopng log or console output.

**Comment by matteoluc** [comment]
Last Log Trace
 17/Jul/2017 12:52:51 [PeriodicActivities.cpp:101] ERROR: Missing script //housekeeping.lua 
17/Jul/2017 12:52:50 [PeriodicActivities.cpp:101] ERROR: Missing script //second.lua 
17/Jul/2017 12:52:49 [PeriodicActivities.cpp:101] ERROR: Missing script //second.lua 
17/Jul/2017 12:52:48 [CollectorInterface.cpp:115] Collecting flows on tcp://127.0.0.1:2055 
17/Jul/2017 12:52:48 [PeriodicActivities.cpp:101] ERROR: Missing script //second.lua 
17/Jul/2017 12:52:48 [PeriodicActivities.cpp:101] ERROR: Missing script //housekeeping.lua 
17/Jul/2017 12:52:48 [NetworkInterface.cpp:2049] Started packet polling on interface tcp://127.0.0.1:2055 [id: 7]... 
17/Jul/2017 12:52:48 [NtopPro.cpp:306] [LICENSE] Maintenance is available until Thu Jul 12 11:43:35 2018 [359 days left] 
17/Jul/2017 12:52:48 [NtopPro.cpp:284] [LICENSE] ntopng license: A50D93F3057D4E3E7AF8DB63A74658C91531388615C4E56A16 
17/Jul/2017 12:52:48 [NtopPro.cpp:273] [LICENSE] ntopng systemId: 68886B0B05B1B8A2 
17/Jul/2017 12:52:48 [PeriodicActivities.cpp:101] ERROR: Missing script //startup.lua 
17/Jul/2017 12:52:48 [PeriodicActivities.cpp:56] Started periodic activities loop... 
17/Jul/2017 12:52:48 [Ntop.cpp:312] Built on CentOS Linux release 7.3.1611 (Core)  
17/Jul/2017 12:52:48 [Ntop.cpp:307] Welcome to ntopng x86_64 v.3.0.170714 - (C) 1998-17 ntop.org 17/Jul/2017 12:52:48 [main.cpp:313] Scripts/HTML pages directory: /usr/share/ntopng 
17/Jul/2017 12:52:48 [main.cpp:311] Working directory: /var/tmp/ntopng 
17/Jul/2017 12:52:48 [HTTPserver.cpp:817] HTTP server listening on port(s) 3000 
17/Jul/2017 12:52:48 [HTTPserver.cpp:814] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts] 
17/Jul/2017 12:52:48 [Utils.cpp:373] WARNING: Unable to locate user anonymous 
17/Jul/2017 12:52:48 [HTTPserver.cpp:760] Please read  https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to  enable SSL. 
17/Jul/2017 12:52:48 [main.cpp:250] PID stored in file /var/run/ntopng.pid 
17/Jul/2017 12:52:48 [Ntop.cpp:1466] Registered interface tcp://127.0.0.1:2055 [id: 7] 
17/Jul/2017 12:52:48 [HostPools.cpp:65] Host Pools Available: 128 
17/Jul/2017 12:52:48 [NtopPro.cpp:146] [LICENSE] Reading license from /etc/ntopng.license 
17/Jul/2017 12:52:45 [main.cpp:40] Ok I am leaving now 17/Jul/2017 12:52:44 [main.cpp:43] Shutting down...

**Comment by simonemainardi** [comment]
The warning

```
17/Jul/2017 12:52:48 [Utils.cpp:373] WARNING: Unable to locate user anonymous
```

suggests ntopng is not able to drop privileges to a known user and thus it is likely that permissions to read `/usr/share/scripts` are missing.

Please, explain how did you install the software. Are you starting the service as a superuser? Consider specifying one of the following options:

```
[--user|-U] <sys user>              | Run ntopng with the specified user
                                    | instead of nobody
[--dont-change-user|-s]             | Do not change user (debug only)
```

**Comment by matteoluc** [comment]
I've installed ntopng following this guide: https://devops.profitbricks.com/tutorials/install-ntopng-network-traffic-monitoring-tool-on-centos-7/ 
I'm starting the service as a superuser.
I've add "--dont-change-user" to ntopng.conf: 
the line " WARNING: Unable to locate user anonymous" there is no more, but errors there are still.

**Comment by simonemainardi** [comment]
The official installation instructions can be found at: http://packages.ntop.org/centos-stable/

Uninstall everything and reinstall by following the official instructions.

**Comment by matteoluc** [comment]
I tried, but there is this mistake 

![unnamed](https://user-images.githubusercontent.com/29771833/28267777-dd9fb122-6afb-11e7-935a-621f5e3d2ff7.jpg)

**Comment by simonemainardi** [comment]
try with this `wget http://packages.ntop.org/centos-stable/epel-7.repo -O epel.repo`

**Comment by matteoluc** [comment]
I uninstalled them all with the command "rpm -e pfring n2disk nprobe ntopng ntopng-data cento pfring-drivers-zc-dkms" and reinstalled, but nothing has changed.

**Comment by simonemainardi** [comment]
did you follow the instructions in the link for the installation? Make sure to use the url `http://packages.ntop.org/centos-stable/epel-7.repo` when wgetting the epel

post the output of `ntopng --version` and `ls -lha /usr/share/ntopng/scripts`

**Comment by matteoluc** [comment]
I followed the instructions of your official page, I used that URL.
I've also tried to uninstall everything with the "yum remove pfring n2disk nprobe ntopng ntopng-data cento pfring-drivers-zc-dkms" command and reinstall but nothing has changed.

Output of "ntopng --version"
![img_9296](https://user-images.githubusercontent.com/29771833/28273002-658cee18-6b0d-11e7-8807-b122d4fb07bd.jpg)

Output of "ls -lha / usr / share / ntopng / scripts"

![img_9299](https://user-images.githubusercontent.com/29771833/28273007-6bbfaad2-6b0d-11e7-99df-0b65f08e1f60.jpg)

**Comment by simonemainardi** [comment]
- remove -v3 from the configuration file
- wrap option values between double quotes ""

run ntopng from the command line as `/usr/local/bin/ntopng /etc/ntopng/ntopng.conf` and post the output

use `ps aux` to check the user that is currently running ntopng and make it has privileges to access `/usr/share/ntopng/scripts`

**Comment by matteoluc** [comment]
With these configuration files, it looks like everything works, without the use of "ps aux". 
Thank you so much.

nprobe:
-g=/var/run/nprobe-zmq.pid
--collector-port="9995"
-i=none
-V=5
--zmq=tcp://*:2055
--online-license-check
-b2

ntopng:
-G=/var/run/ntopng.pid
--user="root"
--interface="tcp://127.0.0.1:2055"
-m="x.x.x.x/20"
--disable-login="1"

**Comment by simonemainardi** [comment]
all right, thanks for reporting
