### ISSUE TITLE
Trying to fetch data from lua-based ntopng API

### ISSUE THREAD

**Issue by Howard-Chang** [ntop/ntopng#1361]
Hi, 
    I am a university student, and due to the project I am trying to use ntop API to fetch the interface information. I studied hard for many days but still don't know how to do it,  could anyone teach me how to fetch ntop data from lua-based API.
I have downloaded the  zerobrane IDE and tried to run the hello_world.lua example.
but there's some problems here:
dirs =ntop.getDirs()
package.path = dirs.installdir .."/scripts/lua/modules/?.lua;" .. package.path
Thank you very much : )   and sorry for my poor English

Best Regards,
Howard

**Comment by emanuele-f** [comment]
Hi Howard, usually there is no need to set up a lua script, you can pull ntopng data with a simple GET request. For example, with curl:

```
curl --cookie "user=admin; password=admin" "http://127.0.0.1:3000/lua/do_export_data.lua?ifid=1"
```

If you want to use our Lua API directly, you should create a custom script under `scripts/lua` directory. See `src/Lua.cpp` for Lua C bindings.

**Comment by Howard-Chang** [comment]
cool! I found it could get json data from cmd, and if I want to edit lua script to get data how should  I do.
My os is win10 could you give me a sample code to know how does it work.
thanks a lot !  : )

**Comment by simonemainardi** [comment]
create `your_own_script.lua` and place it under the scripts/lua directory, then you can execute it simply by pointing your browser to `http://<ntopng host>:<ntopng port>/lua/your_own_script.lua`

for the examples, just open any existing lua script. In articular, if you are interested in pulling host data, have a look at `get_hosts_data.lua`
