### ISSUE TITLE
ntopng - mysql connection trouble & ntopng historical data exporting?

### ISSUE THREAD

**Issue by banghaegi** [ntop/ntopng#1365]
I have two question.

1. I hope to get ntopng historical data for 1 month. and this data exporting looks like csv, txt ~ file extension. How can I do?

2. When I excute connecting command for ntopng - mysql, 
    appeared this error message. How can I do?

-======================================
root@raspberrypi:~# ntopng -F "mysql;localhost;ntopng;flows;root;test"
16/Jun/2017 21:57:59 [Ntop.cpp:1359] Setting local networks to 127.0.0.0/8
16/Jun/2017 21:57:59 [Redis.cpp:109] Successfully connected to redis 127.0.0.1:6379@0
16/Jun/2017 21:57:59 [NtopPro.cpp:144] [LICENSE] Read license from Redis []
16/Jun/2017 21:57:59 [NtopPro.cpp:196] ERROR: [LICENSE] Invalid or missing ntopng License [Empty license file]
16/Jun/2017 21:57:59 [NtopPro.cpp:209] WARNING: [LICENSE] ntopng will now run in enterprise edition for 10 minutes
16/Jun/2017 21:57:59 [NtopPro.cpp:211] WARNING: [LICENSE] before returning to community mode
16/Jun/2017 21:57:59 [NtopPro.cpp:212] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
16/Jun/2017 21:57:59 [NtopPro.cpp:213] WARNING: [LICENSE] or run ntopng in community mode starting
16/Jun/2017 21:57:59 [NtopPro.cpp:214] WARNING: [LICENSE] ntopng --community
16/Jun/2017 21:58:00 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface dummy...
16/Jun/2017 21:58:00 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:root] for interface dummy
16/Jun/2017 21:58:01 [MySQLDB.cpp:613] Disconnected from MySQL for interface <unknown>...
16/Jun/2017 21:58:02 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface wlan0...
16/Jun/2017 21:58:02 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:root] for interface wlan0
Cannot change tcp-segmentation-offload
16/Jun/2017 21:58:02 [NetworkInterface.cpp:227] Executing ethtool -K wlan0 gro off gso off tso off
16/Jun/2017 21:58:02 [PcapInterface.cpp:86] Reading packets from interface wlan0...
16/Jun/2017 21:58:02 [Ntop.cpp:1485] Registered interface wlan0 [id: 0]
16/Jun/2017 21:58:02 [BatchedMySQLDB.cpp:237] Executing queryLoop()
16/Jun/2017 21:58:03 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface wlan1...
16/Jun/2017 21:58:03 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:root] for interface wlan1
Cannot change tcp-segmentation-offload
16/Jun/2017 21:58:03 [NetworkInterface.cpp:227] Executing ethtool -K wlan1 gro off gso off tso off
16/Jun/2017 21:58:04 [PcapInterface.cpp:86] Reading packets from interface wlan1...
16/Jun/2017 21:58:04 [Ntop.cpp:1485] Registered interface wlan1 [id: 1]
16/Jun/2017 21:58:04 [BatchedMySQLDB.cpp:237] Executing queryLoop()
16/Jun/2017 21:58:05 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface lo...
16/Jun/2017 21:58:05 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:root] for interface lo
16/Jun/2017 21:58:06 [PcapInterface.cpp:86] Reading packets from interface lo...
16/Jun/2017 21:58:06 [Ntop.cpp:1485] Registered interface lo [id: 2]
16/Jun/2017 21:58:06 [BatchedMySQLDB.cpp:237] Executing queryLoop()
16/Jun/2017 21:58:07 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface eth0...
16/Jun/2017 21:58:07 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:root] for interface eth0
Cannot change tcp-segmentation-offload
16/Jun/2017 21:58:12 [NetworkInterface.cpp:227] Executing ethtool -K eth0 gro off gso off tso off
16/Jun/2017 21:58:12 [PcapInterface.cpp:86] Reading packets from interface eth0...
16/Jun/2017 21:58:12 [Ntop.cpp:1485] Registered interface eth0 [id: 3]
16/Jun/2017 21:58:12 [BatchedMySQLDB.cpp:237] Executing queryLoop()
16/Jun/2017 21:58:13 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface dummy0...
16/Jun/2017 21:58:13 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:root] for interface dummy0
16/Jun/2017 21:58:13 [NetworkInterface.cpp:227] Executing ethtool -K dummy0 gro off gso off tso off
16/Jun/2017 21:58:13 [PcapInterface.cpp:86] Reading packets from interface dummy0...
16/Jun/2017 21:58:13 [Ntop.cpp:1485] Registered interface dummy0 [id: 46]
16/Jun/2017 21:58:13 [BatchedMySQLDB.cpp:237] Executing queryLoop()
16/Jun/2017 21:58:13 [main.cpp:250] PID stored in file /var/run/ntopng.pid
16/Jun/2017 21:58:13 [HTTPserver.cpp:789] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
16/Jun/2017 21:58:13 [mongoose.c:4515] ERROR: set_ports_option: cannot bind to 3000: Address already in use
16/Jun/2017 21:58:13 [HTTPserver.cpp:835] ERROR: Unable to start HTTP server (IPv4) on ports 3000
root@raspberrypi:~# 
==============================================

 how can I do? . Please tell me about how can I do . Thank you.

**Comment by simonemainardi** [comment]
the problem is not due to mysql; there's someone else the is using port 3000 (perhaps another ntopng process?)

```
ERROR: set_ports_option: cannot bind to 3000: Address already in use
```

Make sure port 3000 is available before starting ntopng; or simply start ntopng on another port.

You can see which is the process simply by using netstat:

 ```
simone@devel:~/ntopng$ sudo netstat -polenta | grep 3000
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN      0          28503568    4197/ntopng      off (0.00/0/0)
tcp        0      0 192.168.2.222:3000      192.168.2.130:52979     TIME_WAIT   0          0           -                timewait (51.05/0/0)
tcp        0      0 192.168.2.222:3000      192.168.2.130:53012     TIME_WAIT   0          0           -                timewait (57.05/0/0)
tcp        0      0 192.168.2.222:3000      192.168.2.130:53022     TIME_WAIT   0          0           -                timewait (59.08/0/0)
tcp        0      0 192.168.2.222:3000      192.168.2.130:52989     TIME_WAIT   0          0           -                timewait (53.05/0/0)
tcp        0      0 192.168.2.222:3000      192.168.2.130:53001     TIME_WAIT   0          0           -                timewait (55.05/0/0)
tcp        0      0 192.168.2.222:3000      192.168.2.130:53017     TIME_WAIT   0          0           -                timewait (58.05/0/0)
tcp        0      0 192.168.2.222:3000      192.168.2.130:52994     TIME_WAIT   0          0           -                timewait (54.05/0/0)
tcp        0      0 192.168.2.222:3000      192.168.2.130:53024     TIME_WAIT   0          0           -                timewait (59.08/0/0)
tcp        0      0 192.168.2.222:3000      192.168.2.130:53007     TIME_WAIT   0          0           -                timewait (56.05/0/0)
tcp        0      0 192.168.2.222:3000      192.168.2.130:53023     TIME_WAIT   0          0           -                timewait (59.08/0/0)
tcp        0      0 192.168.2.222:3000      192.168.2.130:53025     TIME_WAIT   0          0           -                timewait (59.08/0/0)
tcp        0      0 192.168.2.222:3000      192.168.2.130:52984     TIME_WAIT   0          0           -                timewait (52.36/0/0)
```

**Comment by simonemainardi** [comment]
solution given. Error was due to an address already used by another process.
