### ISSUE TITLE
Protocols tab: Sorting is wrong

### ISSUE THREAD

**Issue by fi-ro** [ntop/ntopng#1366]
Hi,
On the page "Interfaces/Protocols" (`/if_stats.lua?ifid=25&page=ndpi`) there is a table on the bottom `Application Protocol - Total (Since Startup) - Percentage`

When I click on the table header I can sort the table to the corresponding column.
It does work fine with the _Percentage_ column, but in the _Total (Since Startup)_ column the sorting is a bit off. 

It's difficult to describe. The pictures should show the problem.

![screenshot 21](https://user-images.githubusercontent.com/17490762/28464016-a943872a-6e23-11e7-8e6b-c68955f23929.png)
![screenshot 22](https://user-images.githubusercontent.com/17490762/28464018-a958435e-6e23-11e7-98c6-53b7f83e00b9.png)

ntopng Pro [Small Business Edition] Edition v.3.1.170721

**Comment by simonemainardi** [comment]
I am not able to reproduce.

I think what is happening is due to the periodic refresh of table rows. As table rows are refreshed *after* the sort, refreshed values may determine a change in the sort order. Can you confirm?

**Comment by fi-ro** [comment]
I'm not sure if I understand you correctly.
The sorting order does not change as the rows are refreshed after sorting.
I have not checked what happens when an entry goes from GB to TB.

But with values as shown the sorting of the "total" column is consistent. 
Sorting after the "percentage" column is correct.

Restarting ntopng does produce the same results, once rows start showing traffic of 1TB or more.

I've noticed this behavior for some time, i.e not only that latest version (never had time to open an issue).

**Comment by simonemainardi** [comment]
thanks for reporting, issue is fixed and will be available in the next nightly build
