### ISSUE TITLE
ntopng-3.0-stable:missing some file and crash

### ISSUE THREAD

**Issue by ufo888com** [ntop/ntopng#1367]
after compilation ntopng-3.0-stable，can not run ntopng，some file can not find as follow：

[Lua.cpp:6075] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/second.lua][/usr/local/share/ntopng/scripts/lua/modules/lua_utils.lua:11: module 'i18n' not found:
         no field package.preload['i18n']
         no file '/usr/local/share/ntopng/scripts/lua/modules/i18n/init.lua'
         no file '/usr/local/share/ntopng/scripts/lua/modules/i18n.lua'
         no file './i18n.lua'
         no file '/usr/local/share/luajit-2.0.3/i18n.lua'
         no file '/usr/local/share/lua/5.1/i18n.lua'
         no file '/usr/local/share/lua/5.1/i18n/init.lua'
         no file './i18n.so'
         no file '/usr/local/lib/lua/5.1/i18n.so'
         no file '/usr/local/lib/lua/5.1/loadall.so']

**Comment by simonemainardi** [comment]
Did you follow this readme https://github.com/ntop/ntopng/blob/dev/doc/README.compilation ?

Please, report all the steps you did.

It looks like necessary files hasn't been installed.

**Comment by ufo888com** [comment]
I just do the compilation step by step fowllowing https://github.com/ntop/ntopng/blob/dev/doc/README.compilation. and then changed to 2.4-stable, the ntopng runs ok.

**Comment by simonemainardi** [comment]
Compilation from sources and installation seems to work flawlessly (just re-tested).

Can you please report all the commands given, one after the ohter? Di you run the make install? how do you execute ntopng? Which is your OS?

**Comment by ufo888com** [comment]
re-tested the Compilation and the WARNING appared again.
I do run the make install and execute ntopng as "ntogng -s"
My os is redhat release 7.2（maipo）

the full report as follow：
[root@wlxncs01sy ntopng.3.0]# make install
 Make sure you have already run 'make geoip' to also install geoip dat files
 While we provide you an install make target, we encourage you
 to create a package and install that
 rpm - do 'make build-rpm'
 deb - do 'cd packages/ubuntu;./configure;make
 mkdir -p /usr/local/share/ntopng /usr/local/man/man8 /usr/local/bin
 cp ntopng /usr/local/bin
 cp ./ntopng.8 /usr/local/man/man8
 cp -r ./httpdocs /usr/local/share/ntopng
 cp -Lr ./scripts /usr/local/share/ntopng # L dereference symlinks
 find /usr/local/share/ntopng -name "*~"   | xargs /bin/rm -f
 find /usr/local/share/ntopng -name ".git" | xargs /bin/rm -rf
 [root@wlxncs01sy ntopng.3.0]# ntopng -s
 26/Jul/2017 00:12:54 [Ntop.cpp:1361] Setting local networks to 127.0.0.0/8
 26/Jul/2017 00:12:54 [Redis.cpp:109] Successfully connected to redis 127.0.0.1:6379@0
 26/Jul/2017 00:12:54 [HostPools.cpp:65] Host Pools Available: 4
 26/Jul/2017 00:12:54 [HostPools.cpp:65] Host Pools Available: 4
 26/Jul/2017 00:12:54 [NetworkInterface.cpp:227] Executing ethtool -K eth0 gro off gso off tso off
 26/Jul/2017 00:12:54 [PcapInterface.cpp:86] Reading packets from interface eth0...
 26/Jul/2017 00:12:54 [Ntop.cpp:1466] Registered interface eth0 [id: 0]
 26/Jul/2017 00:12:54 [HostPools.cpp:65] Host Pools Available: 4
 26/Jul/2017 00:12:54 [NetworkInterface.cpp:227] Executing ethtool -K virbr0 gro off gso off tso off
 26/Jul/2017 00:12:54 [PcapInterface.cpp:86] Reading packets from interface virbr0...
 26/Jul/2017 00:12:54 [Ntop.cpp:1466] Registered interface virbr0 [id: 1]
 26/Jul/2017 00:12:54 [HostPools.cpp:65] Host Pools Available: 4
 26/Jul/2017 00:12:54 [PcapInterface.cpp:86] Reading packets from interface lo...
 26/Jul/2017 00:12:54 [Ntop.cpp:1466] Registered interface lo [id: 2]
 26/Jul/2017 00:12:54 [main.cpp:250] PID stored in file /var/run/ntopng.pid
 26/Jul/2017 00:12:54 [HTTPserver.cpp:758] HTTPS Disabled: missing SSL certificate /var/tmp/ntopng.3.0/httpdocs/ssl/ntopng-cert.pem
 26/Jul/2017 00:12:54 [HTTPserver.cpp:760] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
 26/Jul/2017 00:12:54 [HTTPserver.cpp:814] Web server dirs [/var/tmp/ntopng.3.0/httpdocs][/var/tmp/ntopng.3.0/scripts]
 26/Jul/2017 00:12:54 [HTTPserver.cpp:817] HTTP server listening on port(s) 3000
26/Jul/2017 00:12:54 [main.cpp:311] Working directory: /var/tmp/ntopng
 26/Jul/2017 00:12:54 [main.cpp:313] Scripts/HTML pages directory: /var/tmp/ntopng.3.0
 26/Jul/2017 00:12:54 [Ntop.cpp:307] Welcome to ntopng x86_64 v.3.0.170726 - (C) 1998-17 ntop.org
 26/Jul/2017 00:12:54 [Ntop.cpp:312] Built on Red Hat Enterprise Linux Server release 7.2 (Maipo)
 26/Jul/2017 00:12:54 [PeriodicActivities.cpp:56] Started periodic activities loop...
 26/Jul/2017 00:12:54 [Lua.cpp:6075] WARNING: Script failure [/var/tmp/ntopng.3.0/scripts/callbacks/startup.lua][/var/tmp/ntopng.3.0/scripts/lua/modules/lua_utils.lua:11: module 'i18n' not found:
         no field package.preload['i18n']
         no file '/var/tmp/ntopng.3.0/scripts/lua/modules/i18n/init.lua'
         no file '/var/tmp/ntopng.3.0/scripts/lua/modules/i18n.lua'
         no file './i18n.lua'
         no file '/usr/local/share/luajit-2.0.3/i18n.lua'
         no file '/usr/local/share/lua/5.1/i18n.lua'
         no file '/usr/local/share/lua/5.1/i18n/init.lua'
         no file './i18n.so'
         no file '/usr/local/lib/lua/5.1/i18n.so'
         no file '/usr/local/lib/lua/5.1/loadall.so']
 26/Jul/2017 00:12:54 [Ntop.cpp:580] Adding 127.0.0.1/32 as IPv4 interface address for lo
 26/Jul/2017 00:12:54 [Ntop.cpp:588] Adding 127.0.0.0/8 as IPv4 local network for lo
 26/Jul/2017 00:12:54 [Ntop.cpp:580] Adding 99.12.136.68/32 as IPv4 interface address for eth0
 26/Jul/2017 00:12:54 [Ntop.cpp:588] Adding 99.12.136.0/24 as IPv4 local network for eth0
 26/Jul/2017 00:12:54 [Ntop.cpp:580] Adding 192.168.122.1/32 as IPv4 interface address for virbr0
 26/Jul/2017 00:12:54 [Ntop.cpp:588] Adding 192.168.122.0/24 as IPv4 local network for virbr0
 26/Jul/2017 00:12:54 [Ntop.cpp:607] Adding ::1/128 as IPv6 interface address for lo
 26/Jul/2017 00:12:54 [Ntop.cpp:616] Adding ::1/128 as IPv6 local network for lo
 26/Jul/2017 00:12:54 [Ntop.cpp:607] Adding fe80::250:56ff:fe91:36d1/128 as IPv6 interface address for eth0
 26/Jul/2017 00:12:54 [Ntop.cpp:616] Adding fe80::250:56ff:fe91:36d1/64 as IPv6 local network for eth0
 26/Jul/2017 00:12:54 [NetworkInterface.cpp:2049] Started packet polling on interface eth0 [id: 0]...
 26/Jul/2017 00:12:54 [NetworkInterface.cpp:2049] Started packet polling on interface virbr0 [id: 1]...
 26/Jul/2017 00:12:54 [NetworkInterface.cpp:2049] Started packet polling on interface lo [id: 2]...
 26/Jul/2017 00:12:54 [Lua.cpp:6075] WARNING: Script failure [/var/tmp/ntopng.3.0/scripts/callbacks/housekeeping.lua][/var/tmp/ntopng.3.0/scripts/lua/modules/lua_utils.lua:11: module 'i18n' not found:
         no field package.preload['i18n']
         no file '/var/tmp/ntopng.3.0/scripts/lua/modules/i18n/init.lua'
         no file '/var/tmp/ntopng.3.0/scripts/lua/modules/i18n.lua'
         no file './i18n.lua'
         no file '/usr/local/share/luajit-2.0.3/i18n.lua'
         no file '/usr/local/share/lua/5.1/i18n.lua'
         no file '/usr/local/share/lua/5.1/i18n/init.lua'
         no file './i18n.so'
         no file '/usr/local/lib/lua/5.1/i18n.so'
         no file '/usr/local/lib/lua/5.1/loadall.so']
 26/Jul/2017 00:12:54 [Lua.cpp:6075] WARNING: Script failure [/var/tmp/ntopng.3.0/scripts/callbacks/second.lua][/var/tmp/ntopng.3.0/scripts/lua/modules/lua_utils.lua:11: module 'i18n' not found:
         no field package.preload['i18n']
         no file '/var/tmp/ntopng.3.0/scripts/lua/modules/i18n/init.lua'
         no file '/var/tmp/ntopng.3.0/scripts/lua/modules/i18n.lua'
         no file './i18n.lua'
         no file '/usr/local/share/luajit-2.0.3/i18n.lua'
         no file '/usr/local/share/lua/5.1/i18n.lua'
         no file '/usr/local/share/lua/5.1/i18n/init.lua'
         no file './i18n.so'
         no file '/usr/local/lib/lua/5.1/i18n.so'
         no file '/usr/local/lib/lua/5.1/loadall.so']

**Comment by simonemainardi** [comment]
These directories are wrong as you are trying to execute the installed ntopng:
```
26/Jul/2017 00:12:54 [HTTPserver.cpp:814] Web server dirs [/var/tmp/ntopng.3.0/httpdocs][/var/tmp/ntopng.3.0/scripts]
```

Try to run ntopng from outside the compilation directory or use -1 -2 and -3 to properly specify the necessary paths

**Comment by ufo888com** [comment]
it didn't work.
and I find that some files really can not find in the system，such as:
[root@wlxncs01sy ~]# find / -name i18n.so
 [root@wlxncs01sy ~]# find / -name loadall.so
 [root@wlxncs01sy ~]# find / -name i18n.lua
 [root@wlxncs01sy ~]# ntopng -s

 26/Jul/2017 02:00:29 [Ntop.cpp:1361] Setting local networks to 127.0.0.0/8
 26/Jul/2017 02:00:29 [Redis.cpp:109] Successfully connected to redis 127.0.0.1:6379@0
 26/Jul/2017 02:00:29 [HostPools.cpp:65] Host Pools Available: 4
 26/Jul/2017 02:00:29 [HostPools.cpp:65] Host Pools Available: 4
 26/Jul/2017 02:00:29 [NetworkInterface.cpp:227] Executing ethtool -K eth0 gro off gso off tso off
 26/Jul/2017 02:00:29 [PcapInterface.cpp:86] Reading packets from interface eth0...
 26/Jul/2017 02:00:29 [Ntop.cpp:1466] Registered interface eth0 [id: 0]
 26/Jul/2017 02:00:29 [HostPools.cpp:65] Host Pools Available: 4
 26/Jul/2017 02:00:29 [NetworkInterface.cpp:227] Executing ethtool -K virbr0 gro off gso off tso off
 26/Jul/2017 02:00:29 [PcapInterface.cpp:86] Reading packets from interface virbr0...
 26/Jul/2017 02:00:29 [Ntop.cpp:1466] Registered interface virbr0 [id: 1]
 26/Jul/2017 02:00:29 [HostPools.cpp:65] Host Pools Available: 4
 26/Jul/2017 02:00:29 [PcapInterface.cpp:86] Reading packets from interface lo...
 26/Jul/2017 02:00:29 [Ntop.cpp:1466] Registered interface lo [id: 2]
 26/Jul/2017 02:00:29 [main.cpp:250] PID stored in file /var/run/ntopng.pid
 26/Jul/2017 02:00:29 [HTTPserver.cpp:758] HTTPS Disabled: missing SSL certificate /usr/local/share/ntopng/httpdocs/ssl/ntopng-cert.pem
 26/Jul/2017 02:00:29 [HTTPserver.cpp:760] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
 26/Jul/2017 02:00:29 [HTTPserver.cpp:814] Web server dirs [/usr/local/share/ntopng/httpdocs][/usr/local/share/ntopng/scripts]
 26/Jul/2017 02:00:29 [HTTPserver.cpp:817] HTTP server listening on port(s) 3000
 26/Jul/2017 02:00:29 [main.cpp:311] Working directory: /var/tmp/ntopng
 26/Jul/2017 02:00:29 [main.cpp:313] Scripts/HTML pages directory: /usr/local/share/ntopng
 26/Jul/2017 02:00:29 [Ntop.cpp:307] Welcome to ntopng x86_64 v.3.0.170726 - (C) 1998-17 ntop.org
 26/Jul/2017 02:00:29 [Ntop.cpp:312] Built on Red Hat Enterprise Linux Server release 7.2 (Maipo)
 26/Jul/2017 02:00:29 [PeriodicActivities.cpp:56] Started periodic activities loop...
 26/Jul/2017 02:00:29 [Lua.cpp:6075] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/startup.lua][/usr/local/share/ntopng/scripts/lua/modules/lua_utils.lua:11: module 'i18n' not found:
         no field package.preload['i18n']
         no file '/usr/local/share/ntopng/scripts/lua/modules/i18n/init.lua'
         no file '/usr/local/share/ntopng/scripts/lua/modules/i18n.lua'
         no file './i18n.lua'
         no file '/usr/local/share/luajit-2.0.3/i18n.lua'
         no file '/usr/local/share/lua/5.1/i18n.lua'
         no file '/usr/local/share/lua/5.1/i18n/init.lua'
         no file './i18n.so'
         no file '/usr/local/lib/lua/5.1/i18n.so'
         no file '/usr/local/lib/lua/5.1/loadall.so']

**Comment by simonemainardi** [comment]
you don't have to look for .so files

Does the file /usr/local/share/ntopng/scripts/lua/modules/i18n/init.lua exist? Does it have proper read permissions?

**Comment by ufo888com** [comment]
The file does not exist，where's wrong？How to fix the problem?

**Comment by simonemainardi** [comment]
so I think the installation step failed to copy or dereference the symlink to lua i18n

however, I am unable to reproduce your behaviour on a centos7 and I get everything working properly.

you should investigate the `make install`

in particular, look at the latest line with `cp -Lr`. Try to execute the command by hand and see if the i18n symlink is dereferenced and copied. If this is not the case, check how to cp and dereference symlinks with your OS.

```
[root@wlxncs01sy ntopng.3.0]# make install
Make sure you have already run 'make geoip' to also install geoip dat files
While we provide you an install make target, we encourage you
to create a package and install that
rpm - do 'make build-rpm'
deb - do 'cd packages/ubuntu;./configure;make
mkdir -p /usr/local/share/ntopng /usr/local/man/man8 /usr/local/bin
cp ntopng /usr/local/bin
cp ./ntopng.8 /usr/local/man/man8
cp -r ./httpdocs /usr/local/share/ntopng
cp -Lr ./scripts /usr/local/share/ntopng # L dereference symlinks
```

**Comment by ufo888com** [comment]
you are right!thank you very much!
my fault is unzip the files under windows, so some files were changed.
unzip under linux fixs all the problem.

**Comment by simonemainardi** [comment]
Thanks for reporting.
