### ISSUE TITLE
How to get the historical data

### ISSUE THREAD

**Issue by Howard-Chang** [ntop/ntopng#1369]
Hi,
    I refered the website: https://github.com/ntop/ntopng/blob/dev/doc/README.historical , and type the instruction on cmd:
![default](https://user-images.githubusercontent.com/19474557/28497231-7cb7b2c4-6fb5-11e7-9fcd-95ddbc9b95d3.PNG)
but it's seems can't work. Is there anyone could help me: )
p.s. My pc is windows 8 and the ntopng version is ntopng-3.1.170713-x64.zip

**Comment by simonemainardi** [comment]
you have to either use /i or /c to run ntopng as a service or from the command line. Additional options such as -F go after the /i or /c. We have already pointed you to the user guide in this closed issue: https://github.com/ntop/ntopng/issues/1344 please refer to that guide to see how to properly run ntopng.
