### ISSUE TITLE
Unable to load latest nightly build from ntop.repo

### ISSUE THREAD

**Issue by sclark46** [ntop/ntopng#137]
I am running CentOS 6.7 and when I try to yum install ntopng I get:

yum --disablerepo=\* --enablerepo=base,updates,extras,epel,ntop install ntopng
Resolving Dependencies
--> Running transaction check
---> Package ntopng.x86_64 0:2.0.150825-411 will be installed
--> Processing Dependency: libnetfilter_queue for package: ntopng-2.0.150825-411.x86_64
--> Processing Dependency: ntopng-data for package: ntopng-2.0.150825-411.x86_64
--> Processing Dependency: zeromq for package: ntopng-2.0.150825-411.x86_64
--> Processing Dependency: libnetfilter_queue.so.1()(64bit) for package: ntopng-2.0.150825-411.x86_64
--> Processing Dependency: libhiredis.so.0.10()(64bit) for package: ntopng-2.0.150825-411.x86_64
--> Processing Dependency: libzmq.so.4()(64bit) for package: ntopng-2.0.150825-411.x86_64
--> Running transaction check
---> Package hiredis.x86_64 0:0.10.1-3.el6 will be installed
---> Package libnetfilter_queue.x86_64 0:1.0.1-3.el6 will be installed
---> Package ntopng.x86_64 0:2.0.150825-411 will be installed
--> Processing Dependency: libzmq.so.4()(64bit) for package: ntopng-2.0.150825-411.x86_64
---> Package ntopng-data.noarch 0:2.0.150825-411 will be installed
---> Package zeromq.x86_64 0:2.2.0-4.el6 will be installed
--> Processing Dependency: libpgm-5.1.so.0()(64bit) for package: zeromq-2.2.0-4.el6.x86_64
--> Running transaction check
---> Package ntopng.x86_64 0:2.0.150825-411 will be installed
--> Processing Dependency: libzmq.so.4()(64bit) for package: ntopng-2.0.150825-411.x86_64
---> Package openpgm.x86_64 0:5.1.118-3.el6 will be installed
--> Finished Dependency Resolution
Error: Package: ntopng-2.0.150825-411.x86_64 (ntop)
           Requires: libzmq.so.4()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

cat /etc/redhat-release
CentOS release 6.7 (Final)

**Comment by lmangani** [comment]
Hi,

did you follow the instructions relative to libzmq in our repository guide?
http://packages.ntop.org/centos/

**Comment by lucaderi** [comment]
Closing this issue as the above URL is the solution to this issue

**Comment by sclark46** [comment]
No - but thanks that fixed it.

**Comment by chefcookbook** [comment]
thanks lmangani, issue has been resolved by following the given URL. also thanks to sclark46 for raised the issue

**Comment by lmangani** [comment]
@chefcookbook Our pleasure!
