### ISSUE TITLE
Time limited license duration not reported

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1373]
Using demo/time-limited duration is not reported on the command line

24/Jul/2017 13:35:58 [NtopPro.cpp:297] [LICENSE] ntopng systemId: 1FE719B8-0B82-5C67-9AE6-990B5030479F
24/Jul/2017 13:35:58 [NtopPro.cpp:302] [LICENSE] ntopng is starting in demo mode
24/Jul/2017 13:35:58 [Ntop.cpp:580] Adding 192.168.2.20/32 as IPv4 interface address for en0

or with

$ ntopng --version
v.3.1.170706 [Enterprise/Professional Edition]
GIT rev:   dev:5969c19d6bd4879432463e4b25cc5d74ba213074:20170706
Pro rev:   r1107
System Id: 1FE719B8-0B82-5C67-9AE6-990B5030479F
Built on:  MacOSX 10.12.5

but only from the GUI. This has to be fixed. Example

Build OS:      Ubuntu 16.04.2 LTS
SystemID:      7C663BCE9206AAF2
GIT rev:       dev:191345576ff787c00bb73ff8db571e0e67ea0b15:20170717
Edition:       nProbe Standard
License:       DCF38656EA4788F5BBE1E6D74FC14AEF153243417969A49EA8 [valid license]
License Type:  Permanent License 
Maintenance:   Until Tue Jul 24 14:09:39 2018 [364 days left]

**Comment by simonemainardi** [comment]
Implemented:

```
simone@devel:~/ntopng$ sudo ./ntopng -i eno1
[...]
26/Jul/2017 19:16:23 [Ntop.cpp:332] Built on Ubuntu 16.04.2 LTS
26/Jul/2017 19:16:23 [NtopPro.cpp:377] [LICENSE] System Id:	A2D7D2FB9206AAF2
26/Jul/2017 19:16:23 [NtopPro.cpp:378] [LICENSE] Edition:	Enterprise
26/Jul/2017 19:16:23 [NtopPro.cpp:379] [LICENSE] License Type:	Demo License
26/Jul/2017 19:16:23 [NtopPro.cpp:382] [LICENSE] License:	56D68C654FDE9D2A3315014CBCFD86CC150237369224CAEEEC
26/Jul/2017 19:16:23 [NtopPro.cpp:388] [LICENSE] Validity:	Until Thu Aug 10 16:01:32 2017
[...]

simone@devel:~/ntopng$ ./ntopng --version
v.3.1.170726	[Enterprise/Professional Edition]
GIT rev:	dev:917ed52faa8564f7c715dfb2a2489763bcc6da00:20170726
Pro rev:	r1120
Built on:	Ubuntu 16.04.2 LTS
System Id:	A2D7D2FB9206AAF2
Edition:	Enterprise
License Type:	Demo
Validity:	Until Thu Aug 10 16:01:32 2017
License:	56D68C654FDE9D2A3315014CBCFD86CC150237369224CAEEEC
```
