### ISSUE TITLE
Having troubles configuring ntopng to run in background and automatically

### ISSUE THREAD

**Issue by dnguyen3985** [ntop/ntopng#1374]
I have been struggle to find a way to start my ntopng application automatically. I am fairly new to setting up an environment like this. 

When I launch `service ntopng start` to test, I get the error `Failed to start ntopng.service: Unit cluster.service not found.` and the process does not automatically start on bootup.

If it helps I installed my ntopng program in `/home/test/` using this guide: [https://github.com/ntop/ntopng/blob/dev/doc/README.compilation](url)

I have also copied the exact code from [https://github.com/ntop/ntopng/blob/dev/packages/etc/init.d/ntopng](url)

Could it be that I installed ntopng on the wrong directory? Should I move the `ntopng` folder with all the neccessary files to get it running from `/home/test`  TO  `/etc/ntopng`?

I have been stuck trying to figure this out for hours, any help would be great thanks!

**Comment by ValentinaViscarelli** [comment]
@dnguyen3985 
I didn't understand if you are trying to use ntopng installing the packages or compiling the code from github.

If you want to use ntopng via service you have to install the packages how describe here (according your linux distribution):

http://packages.ntop.org/

Using the package the service is automatically installed.... you have only create configuration in /etc/ntopng/ntopng.conf and if you want ntopng starts on startup you have to create the empty file "/etc/ntopng/ntopng.start"

**Comment by dnguyen3985** [comment]
I have made sure `/etc/ntopng/ntopng.start` was empty. I forgot to add that using the program works perfectly fine my problem is getting ntopng to run automatically on startup and in the background. Also to clarify, I compiled the code from github already. I ran the command `service ntop start` and i still get `Failed to start ntopng.service: Unit cluster.service not found.`  Any other information you need do let me know.

**Comment by ValentinaViscarelli** [comment]
@dnguyen3985 
How did you installed the service?
Anyway probably you don't have pfring installed.

@simonemainardi 
Is it possible install the service from github code source without installing ntopng package?

**Comment by dnguyen3985** [comment]
I have decided to delete ntopng and install from scratch. Can you refer to a proper guide I can use so I can get things running properly? Is the site you linked the proper way: [http://packages.ntop.org/](url)

**Comment by ValentinaViscarelli** [comment]
@dnguyen3985 
The site reports how you have install the package. Please choose the proper way for your linux distribution.
For example if you have ubuntu and you install ntopng using apt-get command, it will be also installed the dependencies.

**Comment by simonemainardi** [comment]
@dnguyen3985 yes official installation instructions are at: http://packages.ntop.org/

Assuming you have followed the installation instructions above, you can get an ntopng started automatically on boot if you add an empty ntopng.start file with at `touch /etc/ntopng/ntopng.start`

You can place ntopng configuration options in ` /etc/ntopng/ntopng.conf`

Manual start/stop of the process is controlled with `/etc/init.d/ntopng start|stop`
