### ISSUE TITLE
Nest IPv6 Host Timeseries

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1376]
ntop stores for IPv4 hosts the time series in a nested directory subtree. Example 192/168/160/10/...

For IPv6 this does not happen and all the hosts time series are not nested thus making complicated to find information. It is requested to implement the same behaviour of IPv4 also for IPv6 hosts

`192                               2a00_d40_1_3_e4ec_64a8_b57f_5137  HTTP.rrd     SSDP.rrd      drops.rrd                  fe80__6600_6aff_fe63_35cc  fe80__b4cd_1a9d_493e_d27b  num_hosts.rrd
2a00_d40_1_3_192_12_193_11        BJNP.rrd                          ICMP.rrd     SSH.rrd       fe80__226_88ff_fe7f_be81   fe80__6dd6_f12e_738f_93d   fe80__d115_1ca6_4413_eeba  num_http_hosts.rrd
2a00_d40_1_3_259d_eb00_afc6_15e1  DHCP.rrd                          ICMPV6.rrd   SSL.rrd       fe80__25f2_486_b131_d373   fe80__8a51_fbff_feec_5e2e  fe80__d42c_2b1f_9f87_4be5  packets.rrd
2a00_d40_1_3_8edc_d4ff_fe5f_e377  DHCPV6.rrd                        IMAPS.rrd    Spotify.rrd   fe80__31ec_7d1d_52df_100a  fe80__8aa2_5eff_fee6_bb01  fe80__e4ec_64a8_b57f_5137
2a00_d40_1_3__1                   DNS.rrd                           LLMNR.rrd    Telegram.rrd  fe80__426c_8fff_fe24_1b6e  fe80__8edc_d4ff_fe5f_e377  fe80__f6b5_2f00_fc_aff0
2a00_d40_1_3__125                 Dropbox.rrd                       MDNS.rrd     Teredo.rrd    fe80__462_a506_1af6_c0fd   fe80__92b1_1cff_fe64_9bff  localstats
2a00_d40_1_3__4                   Github.rrd                        NetBIOS.rrd  Unknown.rrd   fe80__52c5_8dff_fea9_2081  fe80__9900_2aa5_36e8_c0c5  num_devices.rrd
2a00_d40_1_3__6                   Google.rrd                        SIP.rrd      bytes.rrd     fe80__52c5_8dff_fea9_c201  fe80__9e93_4eff_fe60_19b3  num_flows.rrd
`

**Comment by lucaderi** [comment]
Unfortunately the approach you have selected (one byte of the IPv6 address is a directory) leads to a very nested directories and many inodes used. Better if you improve it by for instance grouping two consecutive bytes together or smarter solutions such as group the IPs (that are local) according to the local networks defined first and on a hierarchical (but not too deep) directory structure

**Comment by simonemainardi** [comment]
please note that with the approach of  1b97ad4  two bytes -- and not one -- are used to create consecutive directories for IPv6 addresses. Indeed, every colon-separated IPv6 block is taken as a new directory. If you see 1-byte directories in the file system it just means that the most significant byte in the block is zero.

**Comment by simonemainardi** [comment]
According to https://tools.ietf.org/rfc/rfc4291.txt all unicast IPv6 addresses are required by  to have a 64-bit interface identifier in Modified Extended Unique Identifier-64 (MEUI-64) format. Interface IDs must be unique within a subnet prefix and are used to identify interfaces on a link.

Therefore, the interface identifier, that goes in the 64 least-significant bits of an IPv6 address, can be assumed as non-structured (note that often interface ids are chosen as equal to layer 2 addresses). 

Contrarily, the most significant /64 bits of an IPv6 address contain routing information. Typically this part of the address is hierarchically structured as it passes from IANA to the Regional Internet Registry to an ISP or LIR and then finally to a customer or a specific customer location.

Given the observations above, I have chosen:
- to hierarchically nest the first 64 bits of ipv6 adresses using pairs of consecutive bytes.
- to keep the remaining 64 bits as unstructured

This yields a file system hierarchy for piv6 that is similar to that used by ipv4. For example:


```
dsldevice:ntopng simone$ find  /var/tmp/ntopng/41/rrd/2001/06b0/
/var/tmp/ntopng/41/rrd/2001/06b0/
/var/tmp/ntopng/41/rrd/2001/06b0/0019
/var/tmp/ntopng/41/rrd/2001/06b0/0019/0000
/var/tmp/ntopng/41/rrd/2001/06b0/0019/0000/0000_0000_0000_0138
/var/tmp/ntopng/41/rrd/2001/06b0/0019/0000/0000_0000_0000_0138/bytes.rrd
/var/tmp/ntopng/41/rrd/2001/06b0/0019/0000/0000_0000_0000_0138/dns
/var/tmp/ntopng/41/rrd/2001/06b0/0019/0000/0000_0000_0000_0138/dns/rcvd
/var/tmp/ntopng/41/rrd/2001/06b0/0019/0000/0000_0000_0000_0138/dns/rcvd/num_queries.rrd
/var/tmp/ntopng/41/rrd/2001/06b0/0019/0000/0000_0000_0000_0138/dns/rcvd/num_replies_error.rrd
/var/tmp/ntopng/41/rrd/2001/06b0/0019/0000/0000_0000_0000_0138/dns/rcvd/num_replies_ok.rrd
/v
```

@lucaderi please review the commit and comment.

**Comment by simonemainardi** [comment]
latest implementation agreed and accepted during a dev meeting
