### ISSUE TITLE
ntopng dev: I think tcp syn packets/sec threshold doesn't work

### ISSUE THREAD

**Issue by bioteseo** [ntop/ntopng#1378]
I'm using ntopng dev version.
For an IP I set "syn flood attacker" threshold to 15, but I continue to receive alert about that like this:
"Host xxx.xxx.xxx.xxx is a SYN Flooder (11 SYN sent in 3 sec)"
It seems that ntopng is using the "Local Hosts Common Thresholds" instead of "Host xxx.xxx.xxx.xxx Thresholds". If I change the value in "Local Hosts Common Thresholds" the alerts disappears.

Thanks

Bye

**Comment by simonemainardi** [comment]
thanks for reporting.
