### ISSUE TITLE
ntopng dev: Host IP Thresholds disappear

### ISSUE THREAD

**Issue by bioteseo** [ntop/ntopng#1381]
Hi,
I set some threshold value (Flow Flood Attacker and Syn Flood Attacker in this case), then I save them.
Then I check the alerts and I see again alerts on that IP as the previous changes have no effect. Infact when I check the change it was disappear. There is no value that already I have changed.....
There wasn't in previous release (yesterday) this issue. I'm using 3.1.170728

Thanks

**Comment by simonemainardi** [comment]
It was just a rendering issue. Thresholds were properly set.  Thanks for reporting.
