### ISSUE TITLE
ntopng WebUI login loop

### ISSUE THREAD

**Issue by Kazz3r24** [ntop/ntopng#1383]
I just finished tinkering with my crontab and I did an update, now I am unable to log into the webui for ntopng, I entered in initially my own credentials, which the page then loads for a split second before clearing the form. Then after resetting the admin password, I still had no luck getting logged in. I was using it earlier today and did not touch the config files.

System info:
Ubuntu 14.04 64-bit
ntopng v.1.2.1 (r1.2.1)
Redis server v=3.2.9 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=86450d2ba8219c1e

I've attempted the following:
- I have reinstalled ntopng
- I have reset the ntopng.user.admin.password using redis-cli
- I have updated and upgraded all packages

For whatever reason ntopng is a pain to get going on Ubuntu 14.04, I always either have amazing luck and get it first try, or I have to do hours of tinkering which inevitably breaks something else. I do love ntopng though.

I can provide log data if required.

This is some sample output of what I see in /var/log/messages (no sensitive data present)

I did also see another thread somewhere about manually collecting the geoip data, which I have done. Still no success.

`Jul 29 00:26:29 plex.kevin-server.com kernel: device eth0 entered promiscuous mode
Jul 29 00:44:13 plex.kevin-server.com kernel: device eth0 left promiscuous mode
Jul 29 00:44:13 plex.kevin-server.com ntopng: [Geolocation.cpp:59] WARNING: Unable to read GeoIP database /usr/share/ntopng/httpdocs/geoip/GeoIPASNum.dat
Jul 29 00:44:13 plex.kevin-server.com ntopng: [Geolocation.cpp:59] WARNING: Unable to read GeoIP database /usr/share/ntopng/httpdocs/geoip/GeoIPASNumv6.dat
Jul 29 00:44:13 plex.kevin-server.com ntopng: [Geolocation.cpp:59] WARNING: Unable to read GeoIP database /usr/share/ntopng/httpdocs/geoip/GeoLiteCity.dat
Jul 29 00:44:13 plex.kevin-server.com ntopng: [Geolocation.cpp:59] WARNING: Unable to read GeoIP database /usr/share/ntopng/httpdocs/geoip/GeoLiteCityv6.dat
Jul 29 00:44:13 plex.kevin-server.com kernel: device eth0 entered promiscuous mode
Jul 29 00:45:58 plex.kevin-server.com kernel: device eth0 left promiscuous mode
`

**Comment by simonemainardi** [comment]
do you experience the loop also with `--disable-login = 1`? did you try by clearing the cookies?

**Comment by Kazz3r24** [comment]
That you for responding so quickly, I was extremely tired when I looked at this last night. It appears it was just a cookie issue, cleared my cookies from the browser and was able to log back on.

Thank you for your assist!

I have a separate issue I've been meaning to get to, I will create a different ticket for it.
