### ISSUE TITLE
Interface counters are not consistent

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1385]
![screen shot 2017-07-31 at 14 14 37](https://user-images.githubusercontent.com/4493366/28777276-b7c62a9e-75fa-11e7-9194-f9e7cf8ef95e.png)

As you can see the top left percentages (e.g. ARP 23.8%) are not in sync with those on the table below (ARP 20.51%)

**Comment by simonemainardi** [comment]
fixed, thanks for reporting

![image](https://user-images.githubusercontent.com/3397663/28868316-5ffc417e-7779-11e7-8787-f2989a0efdab.png)
