### ISSUE TITLE
ntopng 100% high CPU load

### ISSUE THREAD

**Issue by Jamapa** [ntop/ntopng#1386]
The CPU load is **_# 100%_** after two days of installation. I have 20 users in my LAN.

**Comment by simonemainardi** [comment]
what is the ntopng version used?

**Comment by Jamapa** [comment]
I use Version 3.x (the latest at the time we talk)
Now i'm testing version 2.4 by installing it.

**Comment by simonemainardi** [comment]
we can't support you with version 2.4

Please, go with the latest 3.1 and report

**Comment by simonemainardi** [comment]
@Jamapa any news?

**Comment by Jamapa** [comment]
I ve reinstalled the latest version and the CPU is loading 100% sometimes. 
The CPU is a dual core 2GHz and 2GB of RAM.
Thanks

**Comment by simonemainardi** [comment]
I suspect this is normal. Having some peak loads from time to time may be normal. Can you do some investigations to see what can be the cause (perhaps with strace)? Is ntopng dropping packets during these peaks?

**Comment by Jamapa** [comment]
Internet work fine even this situation. But i'm afraid for the impact of this because we use the machine like router. I don't have so many times so far for consulting log

**Comment by simonemainardi** [comment]
so please reopen with the information provided if necessary or when you will have time
