### ISSUE TITLE
Database running out of IDs / ID reached max int

### ISSUE THREAD

**Issue by philimnorden** [ntop/ntopng#1387]
We are dumping our flows into a mysql database and ntop was running fine for a few weeks. The database had a size of about 300GB and the data retention was set to 10 days. I noticed the issue after the ntop log grew to over 110GB and the system reported low free disk space.

The log said over and over:
```
Aug  1 08:22:00 HOSTXXX ntopng: [BatchedMySQLDB.cpp:259] ERROR: MySQL error: Out of range value for column 'idx' at row 1 [rc=-1]
Aug  1 08:22:00 HOSTXXX ntopng: [BatchedMySQLDB.cpp:261] ERROR: SQL statement: INSERT INTO `flowsv4`  [...] valid SQL Statement for inserting flows ... [...]
```

The column 'idx' reached the last valid integer and the auto_increment tried to increase it further but failed to do so. I solved the problem with a workaroung by myself. I altered the table and changed the column to BIGINT. Now ntop is running fine again. Im wondering if noboy else tried to use ntop in a "big" enterprise environment and had the same problem?

The other issue is that the log grew a lot. Im not sure if thats a real problem, but you could think about a limitation or logrotation or anything else to prevent the disk from filling completely.

**Comment by simonemainardi** [comment]
thanks for reporting.

open issues are already tracking both the redesign of the DB schema as well as the rotation of logs:
- https://github.com/ntop/ntopng/issues/1368
- https://github.com/ntop/ntopng/issues/1056
