### ISSUE TITLE
ntopng invoked oom-killer

### ISSUE THREAD

**Issue by anilkumarnaik** [ntop/ntopng#1388]
NTOPNG process has been killed by oom-killer. ntopng occupies 12GB of memory and 12GB of swap. After restarting services its works and again process killed after fill all the mem and swap space. 
how to stop this? 

logs:
==============================
dcntopng@server:/var/log$ grep -i kill syslog
Aug  1 15:39:30 dcntopng kernel: [2838010.781016] ntopng invoked oom-killer: gfp_mask=0x24201ca, order=0, oom_score_adj=0
Aug  1 15:39:30 dcntopng kernel: [2838010.781053]  [<ffffffff811926c2>] oom_kill_process+0x202/0x3c0
Aug  1 15:39:30 dcntopng kernel: [2838010.781302] Out of memory: Kill process 18939 (ntopng) score 942 or sacrifice child
Aug  1 15:39:30 dcntopng kernel: [2838010.782149] Killed process 18939 (ntopng) total-vm:25488576kB, anon-rss:11638284kB, file-rss:0kB
Aug  1 15:39:32 dcntopng systemd[1]: ntopng.service: Main process exited, code=killed, status=9/KILL

dcntopng:/var/log$ cat /etc/ntopng/ntopng.conf 
-i=eth1
-w=3000
-m=(mynetwork ips)
-n=1
-d=/var/tmp/ntopng
-U=ntopng
-l
opr@dcntopng:/var/log$

**Comment by simonemainardi** [comment]
Are you using the latest version? That is, the latest 3.1?

**Comment by anilkumarnaik** [comment]
ntopng version: 
Version | 3.0.170623 - Pro Small Business Edition

**Comment by simonemainardi** [comment]
That is outdated, we have already resolved the mem leaks that were leading to OOMs. 

Fixes are both in the stable and in the dev.

See for reference:

https://github.com/ntop/ntopng/issues/1351
https://github.com/ntop/ntopng/issues/1337

Please, upgrade the current version installed and it will be ok.
