### ISSUE TITLE
Please help tuning mysql for performance

### ISSUE THREAD

**Issue by stebbo63** [ntop/ntopng#1390]
Hello,
I recently activated the past data retention and am trying to get some statistics out of the system.  However, if I try to do a search on anything more than about an hour of data it takes forever and I get a message along the lines of "this query is taking too long, please adjust search parameters or tune the database for performance".
Thereafter, the ntopng interface is non responsive for about 10 or 15 minutes - even if I shutdown the browser and return.
How do I go about tuning the database for performance?  Is there a guide or some examples that I could use?
The machine in question is an i5-4570 with 8GB RAM.  
Thanks,
Chris.

my startup line is 
ntopng --http-port "3000" --https-port "0" --core-affinity "-1" --local-networks "x.x.x.x/20" --data-dir "/storage/ntopng" --pid "/var/run/ntopng.pid" --interface "enp3s0" --dump-flows "mysql;localhost;ntopng;flows;ntopsql;mysql@lhs"

**Comment by muzea** [comment]
You need ssd :)

**Comment by stebbo63** [comment]
> You need ssd :)
well that was extremely helpful.  Not!

**Comment by simonemainardi** [comment]
please, refer to this issue that is almost a duplicate https://github.com/ntop/ntopng/issues/1198

Also have a look at https://github.com/ntop/ntopng/issues/830#issuecomment-262035548 where I discuss the MySQL MyISAM configuration parameters that requires tuning from their default values.


how many flows per second are you going to store? 

Given that you have 8GB of storage, you won't be able to leverage mysql in-memory buffers much, so the performance will likely be bottleneck-ed by disk speed.

**Comment by simonemainardi** [comment]
@stebbo63 did you try the suggestions above? Can you provide indication on the number of flows exported every second (this value is indicated in the interface if_stats.lua page)

**Comment by simonemainardi** [comment]
if necessary, reopen after having tried the suggestions given and give indication on the number of flows per second you need to handle.
