### ISSUE TITLE
nProbe License can't verify

### ISSUE THREAD

**Issue by Howard-Chang** [ntop/ntopng#1391]
I have got a nProbe License and I refer this website  http://www.ntop.org/support/faq/my-license-does-not-work-what-can-i-do/ paste the Authentication Code on the nprobe.license txt file and placed on the same directory where nprobe.exe is located . After doing that when I reopen the nProbe it's still the DEMO version.

thanks for the help.

**Comment by simonemainardi** [comment]
please, post the full output of nprobe


next time please use the nProbe issue tracker: https://github.com/ntop/nProbe/issues

**Comment by Howard-Chang** [comment]
this is the output on cmd:
C:\Program Files\nProbe>nprobe /c --zmq "tcp://*:2055" -i none -n none --collect
or-port 5556
Running nProbe for Windows.
I
I
02/Aug/2017 17:42:17 [nprobe.c:3603] ERROR: Invalid nProbe license (nprobe.licen
se) [Missing license file]
02/Aug/2017 17:42:17 [nprobe.c:3610] ERROR: ************************************
*****************
02/Aug/2017 17:42:17 [nprobe.c:3611] ERROR: **
               **
02/Aug/2017 17:42:17 [nprobe.c:3612] ERROR: **  Switching to DEMO MODE (missing
valid license) **
02/Aug/2017 17:42:17 [nprobe.c:3613] ERROR: **
               **
02/Aug/2017 17:42:17 [nprobe.c:3614] ERROR: **  Purchase your nProbe license at
               **
02/Aug/2017 17:42:17 [nprobe.c:3615] ERROR: **       https://shop.ntop.org/
               **
02/Aug/2017 17:42:17 [nprobe.c:3616] ERROR: **
               **
02/Aug/2017 17:42:17 [nprobe.c:3617] ERROR: ************************************
*****************
02/Aug/2017 17:42:17 [nprobe.c:5497] WARNING: The output interfaceId is set to 0
: did you forget to use -Q perhaps ?
02/Aug/2017 17:42:17 [nprobe.c:5500] WARNING: The input interfaceId is set to 0:
 did you forget to use -u perhaps ?
02/Aug/2017 17:42:17 [nprobe.c:5599] Welcome to nProbe v.7.5.170507 ($Revision:
4384 $) for Windows
02/Aug/2017 17:42:17 [nprobe.c:5609] Running on Windows
02/Aug/2017 17:42:17 [nprobe.c:5620] [LICENSE] nProbe SystemId: 3837973666-7a06a
af2
02/Aug/2017 17:42:17 [nprobe.c:5734] Sample rate [packet: 1][flow: 1]
02/Aug/2017 17:42:17 [nprobe.c:8078] ERROR: ************************************
***************************
02/Aug/2017 17:42:17 [nprobe.c:8079] ERROR: * NOTE: This is a DEMO version limit
ed to 25000 flows export.  *
02/Aug/2017 17:42:17 [nprobe.c:8080] ERROR: ************************************
***************************
02/Aug/2017 17:42:17 [nprobe.c:8086] Welcome to nProbe v.7.5.170507 for Windows
02/Aug/2017 17:42:17 [nprobe.c:7054] WARNING: Adding %EXPORTER_IPV4_ADDRESS to t
he template as nProbe is working as collector
02/Aug/2017 17:42:17 [plugin.c:1068] 0 plugin(s) enabled
02/Aug/2017 17:42:17 [nprobe.c:7590] Non IPv4/v6 traffic is discarded according
to the template
02/Aug/2017 17:42:17 [nprobe.c:8263] IPv6 traffic will NOT be exported/accounted
 by this probe
02/Aug/2017 17:42:17 [nprobe.c:8264] due to configuration options (e.g. use NetF
low v9)
02/Aug/2017 17:42:17 [nprobe.c:8265] Please use -V to set the version to other t
han NetFlow V5
02/Aug/2017 17:42:17 [nprobe.c:8310] Flows ASs will not be computed (missing Geo
IP support)
02/Aug/2017 17:42:17 [nprobe.c:8418] Not capturing packet from interface (collec
tor mode)
02/Aug/2017 17:42:17 [util.c:4139] Initializing ZMQ as server
02/Aug/2017 17:42:17 [util.c:4182] Succesfully created ZMQ endpoint tcp://*:2055

02/Aug/2017 17:42:17 [collect.c:143] Flow collector listening on port 5556 (IPv4
/v6)
02/Aug/2017 17:42:17 [nprobe.c:8635] nProbe started successfully

**Comment by Howard-Chang** [comment]
![1](https://user-images.githubusercontent.com/19474557/28914896-e5319500-786f-11e7-98c5-ca7d14b8ddd3.PNG)
![2](https://user-images.githubusercontent.com/19474557/28914903-e6adefc8-786f-11e7-92a5-dc69927db456.PNG)

**Comment by simonemainardi** [comment]
just tried to reproduce without success. nProbe on win works properly with a license file.

Make sure the file 'nprobe.license' does not have a `.txt` extension: open notepad as an administrator, paste the license key in the editor, and then save the file under `Program Files/nProbe` as nprobe.license 

![image](https://user-images.githubusercontent.com/3397663/28921228-5b85f216-7855-11e7-8385-afa24a8d8915.png)

then

![image](https://user-images.githubusercontent.com/3397663/28921248-67ee887e-7855-11e7-8276-e2a8fe849e7d.png)

**Comment by Howard-Chang** [comment]
It can work now thank you : )

**Comment by simonemainardi** [comment]
Please, explain what did you to exactly to make it working so other people in the community can benefit from this thread. Thank you

**Comment by Howard-Chang** [comment]
Because I save it as txt file so it can't run.
follow simonemainardi step is great to work!

**Comment by simonemainardi** [comment]
thanks for reporting!
