### ISSUE TITLE
license ?

### ISSUE THREAD

**Issue by 9r00t-z** [ntop/ntopng#1392]
I'm really sorry to post this here, because I know it's not technically an "issue" but for all the reading on the ntopng website I can't figure out if I need a license or not, and if so which ones.  I have a small home lab (~50 nodes) and I have two switches and a firewall logging netflow.  I had ntopng configured to use nrpobe and it was working well, but now it's complaining about a license file and I'm getting errors that prevent anything from running.  I read that the license is $150 **JUST** for the nprobe component.. am I mis-reading?

I know this might not be the appropriate place to post something like this, but the ntopng site itself is really hard to navigate and locate information.  

If you can take a second to please give me a really quick little blurb about how the licensing works in general I'd really appreciate it.

**Comment by simonemainardi** [comment]
nProbe is a commercial product and requires a license. Without a valid license, nprobe will only export the first 25000 flows and then will stop.

Contrarily, ntopng (community) is opensource and you don't need a license to use it, even if you are using it with a licensed nprobe. An ntopng license is needed if you want to access its professional or enterprise features, but it is not necessary.

**Comment by simonemainardi** [comment]
@jclemons7 does this answers your question?
