### ISSUE TITLE
nProbe exiting after update and reboot

### ISSUE THREAD

**Issue by jpalondonon** [ntop/ntopng#1394]
I performed a apt-get update && apt-get upgrade and now nProbe exits even after rebooting.  See below

<root@ntop ~>$ service nprobe status
● nprobe.service - Start/stop nprobe program
   Loaded: loaded (/etc/systemd/system/nprobe.service; enabled; vendor preset: enabled)
   Active: active (exited) (Result: core-dump) since Thu 2017-08-03 09:57:38 EDT; 50min ago
  Process: 1577 ExecStart=/etc/init.d/nprobe start (code=exited, status=0/SUCCESS)
 Main PID: 1653 (code=dumped, signal=ABRT)
    Tasks: 0
   Memory: 0B
      CPU: 0
   CGroup: /system.slice/nprobe.service

Aug 03 09:57:38 ntop systemd[1]: Starting Start/stop nprobe program...
Aug 03 09:57:38 ntop nprobe[1577]: Starting nProbe none
Aug 03 09:57:38 ntop systemd[1]: Started Start/stop nprobe program.
Aug 03 09:57:40 ntop systemd[1]: nprobe.service: Main process exited, code=dumped, status=6/ABRT

Built on Ubuntu 16.04.2 LTS

**Comment by simonemainardi** [comment]
please, refer to the nProbe issue tracker that is currently reporting a similar issue: https://github.com/ntop/nProbe/issues

**Comment by jpalondonon** [comment]
Thanks very much.  All working fine now.
