### ISSUE TITLE
Can't read data from the RRD files

### ISSUE THREAD

**Issue by Howard-Chang** [ntop/ntopng#1395]
Hi,
   I want to get data from RRD files,and I refer to the website https://www.spinics.net/lists/ntop/msg01774.html,
and type the command: rrdtool fetch C:\Windows\Temp\ntopng\0\rrd\192\168\0\31/bytes.rrd AVERAGE -s now-1d
the output:
C:\Users\Administrator\Downloads\rrdtool-1.2.15-cygwin-1.5.20>rrdtool fetch C:\W
indows\Temp\ntopng\0\rrd\192\168\0\31\bytes.rrd AVERAGE -s now-1d
                           sent                rcvd

1502076900: nan nan
1502077200: nan nan
1502077500: nan nan
1502077800: nan nan
1502078100: nan nan
1502078400: nan nan
1502078700: nan nan
1502079000: nan nan
1502079300: nan nan
1502079600: nan nan
1502079900: nan nan
1502080200: nan nan
1502080500: nan nan
1502080800: nan nan
1502081100: nan nan
1502081400: nan nan
1502081700: nan nan
1502082000: nan nan
1502082300: nan nan
1502082600: nan nan
1502082900: nan nan
1502083200: nan nan
1502083500: nan nan
1502083800: nan nan
1502084100: nan nan
1502084400: nan nan
1502084700: nan nan
1502085000: nan nan
1502085300: nan nan
1502085600: nan nan
1502085900: nan nan
1502086200: nan nan
1502086500: nan nan
1502086800: nan nan
1502087100: nan nan
1502087400: nan nan
1502087700: nan nan
1502088000: nan nan
1502088300: nan nan
1502088600: nan nan
1502088900: nan nan
1502089200: nan nan
1502089500: nan nan
1502089800: nan nan
1502090100: nan nan
1502090400: nan nan
1502090700: nan nan
1502091000: nan nan
1502091300: nan nan
1502091600: nan nan
1502091900: nan nan
1502092200: nan nan
1502092500: nan nan

and I found it didn't update the data about the files
because today is 2017/8/8 but the last modified day is 2017/7/25 

![image](https://user-images.githubusercontent.com/19474557/29055362-ad3a5566-7c2e-11e7-921e-3547583ce093.png)

could anyone help me thanks a lot!

**Comment by Howard-Chang** [comment]
this is initial state of log:
08/Aug/2017 14:19:40 [MySQLDB.cpp:627] Attempting to connect to MySQL for interface tcp://127.0.0.1:2055...
08/Aug/2017 14:19:39 [CollectorInterface.cpp:115] Collecting flows on tcp://127.0.0.1:2055
08/Aug/2017 14:19:39 [NetworkInterface.cpp:2149] Started packet polling on interface tcp://127.0.0.1:2055 [id: 2]...
08/Aug/2017 14:19:39 [PeriodicActivities.cpp:50] Started periodic activities loop...
08/Aug/2017 14:19:39 [NtopPro.cpp:330] [LICENSE] Maintenance is available until Wed Jul 25 07:46:30 2018 [350 days left]
08/Aug/2017 14:19:39 [NtopPro.cpp:308] [LICENSE] ntopng license: D027FBF9DE9BF351C1FB5C33CCFCCE20153247599094B97592
08/Aug/2017 14:19:39 [NtopPro.cpp:297] [LICENSE] ntopng systemId: 3837973666-7a06aaf2
08/Aug/2017 14:19:39 [Ntop.cpp:314] Built on Windows
08/Aug/2017 14:19:39 [Ntop.cpp:309] Welcome to ntopng x64 v.3.1.170713 - (C) 1998-17 ntop.org
08/Aug/2017 14:19:39 [main.cpp:315] Scripts/HTML pages directory: C:\Program Files\ntopng
08/Aug/2017 14:19:39 [main.cpp:313] Working directory: C:\Users\Administrator\Documents\ntopng
08/Aug/2017 14:19:39 [MySQLDB.cpp:667] Successfully connected to MySQL [localhost:root] for interface tcp://127.0.0.1:2055
08/Aug/2017 14:19:39 [MySQLDB.cpp:627] Attempting to connect to MySQL for interface tcp://127.0.0.1:2055...
08/Aug/2017 14:19:39 [MySQLDB.cpp:614] Disconnected from MySQL for interface tcp://127.0.0.1:2055...
08/Aug/2017 14:19:39 [HTTPserver.cpp:846] HTTP server listening on port(s) 3000
08/Aug/2017 14:19:39 [HTTPserver.cpp:843] Web server dirs [C:\Program Files\ntopng\httpdocs][C:\Program Files\ntopng\scripts]
08/Aug/2017 14:19:39 [HTTPserver.cpp:789] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
08/Aug/2017 14:19:39 [HTTPserver.cpp:787] HTTPS Disabled: missing SSL certificate C:\Program Files\ntopng\httpdocs/ssl/ntopng-cert.pem
08/Aug/2017 14:19:38 [BatchedMySQLDB.cpp:237] Executing BatchedMySQLDB::queryLoop()
08/Aug/2017 14:19:38 [Ntop.cpp:1487] Registered interface tcp://127.0.0.1:2055 [id: 2]
08/Aug/2017 14:19:37 [MySQLDB.cpp:667] Successfully connected to MySQL [localhost:root] for interface tcp://127.0.0.1:2055
08/Aug/2017 14:19:37 [MySQLDB.cpp:627] Attempting to connect to MySQL for interface tcp://127.0.0.1:2055...
08/Aug/2017 14:19:37 [NtopPro.cpp:168] [LICENSE] Read license from Redis [D027FBF9DE9BF351C1FB5C33CCFCCE20153247599094B97592]

**Comment by Howard-Chang** [comment]
later it show the warning message:
08/Aug/2017 14:25:16 [Utils.cpp:242] WARNING: Unable to write file \var\tmp\ntopng/runtimeprefs.json.temp
08/Aug/2017 14:25:11 [Utils.cpp:242] WARNING: Unable to write file \var\tmp\ntopng/runtimeprefs.json.temp
08/Aug/2017 14:25:06 [Utils.cpp:242] WARNING: Unable to write file \var\tmp\ntopng/runtimeprefs.json.temp
08/Aug/2017 14:25:01 [Utils.cpp:242] WARNING: Unable to write file \var\tmp\ntopng/runtimeprefs.json.temp
08/Aug/2017 14:25:56 [Utils.cpp:242] WARNING: Unable to write file \var\tmp\ntopng/runtimeprefs.json.temp

**Comment by simonemainardi** [comment]
RRDs for non active active hosts are not updated. Nans mean that rrd has padded missing values. Try to read an rrd of an active host and it will work.

Also make sure to use a proper rrdtool. I noticed you are using a cygwin binary so please make sure to be within cygwin.

As per the issue reported in the latest comment, it has already been fixed and will be available in the forthcoming windows build.

In the meanwhile, to suppress the warning, you can add option -4, eg., 

![image](https://user-images.githubusercontent.com/3397663/29122385-6a80a768-7d12-11e7-8e48-7ee2afaa7d03.png)
