### ISSUE TITLE
Unable to change "Tiny Flows Dump" parameters

### ISSUE THREAD

**Issue by egoretz** [ntop/ntopng#1396]
Hello,

I'm running ntopng Pro [Small Business Edition] v.3.0.170613 on Debian 8.8, installed from debs. 

The problem is that I can't change any default values in "Flow Database Dump" submenu in Ntop Preferences. Pressing Save button always gives an error like "Script "/usr/share/ntopng/scripts/lua/admin/prefs.lua" returned an error:

/usr/share/ntopng/scripts/lua/modules/http_lint.lua:993: [LINT] _POST["toggle_flow_db_dump_export"] = "1" parameter error: Missing validation"

Tried FF 53.0 and IE 11.

Best Regards,
George

**Comment by simonemainardi** [comment]
thanks  for reporting, issue is fixed and a new stable build is in progress
