### ISSUE TITLE
ntopng:armhf crashes on ARM64 

### ISSUE THREAD

**Issue by macoune** [ntop/ntopng#1397]
Hi,
ntopng crashes after a few second on an odroid c2, Debian Jessie arm64.
Package installed : ntopng_3.1.170712-3130_armhf.deb

Here is a gdb trace : 

```Program received signal SIGBUS, Bus error.
[Switching to Thread 0xeecff310 (LWP 19471)]
0x00115aac in ndpi_connection_tracking (ndpi_struct=ndpi_struct@entry=0x1dafcf0, 
flow=flow@entry=0xf1d45040) at ndpi_main.c:3109
3109	ndpi_main.c: No such file or directory.
```

If I run ntopng listening on interface lo, the application keep running.
Any idea on what could be the problem ?

Thanks!!

**Comment by simonemainardi** [comment]
did you follow http://packages.ntop.org/RaspberryPI/ to install the package?

What is the ntopng configuration used?

**Comment by simonemainardi** [comment]
@macoune any news?

**Comment by lucaderi** [comment]
Closed for inactivity.

**Comment by jonbackhaus** [comment]
I just tried to compile from source on the ODROID XU4 and the build failed. Any suggestions?

**Comment by emanuele-f** [comment]
Please open a new issue and specify the commands you run and the output you get. Please check out https://github.com/ntop/ntopng/blob/dev/doc/README.compilation
