### ISSUE TITLE
ASA interfaces should be visible in ntopng

### ISSUE THREAD

**Issue by qm2k** [ntop/ntopng#1399]
Currently ASA flows displayed as one single interface in ntopng. But this does not correspond to reality since there're always more than one interface. Interface information is present in flows, in fields `InputInt` and `OutputInt` (see [here](https://www.cisco.com/c/en/us/td/docs/security/asa/special/netflow/guide/asa_netflow.html#pgfId-1338920) for more details).

For instance, see 
[2017-08-09.pcap.gz](https://github.com/ntop/ntopng/files/1212230/2017-08-09.pcap.gz). It contains two flows, 533847104 and 533847166. Below is information about them as decoded by Wireshark:

First flow, from interface 15 to interface 3:
```
Flow Id: 533847104
SrcAddr: 10.7.7.99 (10.7.7.99)
SrcPort: 56426
InputInt: 15
DstAddr: 91.189.88.148 (91.189.88.148)
DstPort: 80
OutputInt: 3
Protocol: 6
IPv4 ICMP Type: 0
IPv4 ICMP Code: 0
Post NAT Source IPv4 Address: 89.106.171.134 (89.106.171.134)
Post NAT Destination IPv4 Address: 91.189.88.148 (91.189.88.148)
Post NAPT Source Transport Port: 56426
Post NAPT Destination Transport Port: 80
Firewall Event: Flow created (1)
Extended firewall event code: ignore (0)
Observation Time Milliseconds: Aug  9, 2017 19:05:50.276000000 MSK
Ingress ACL ID: a573c83eccef216b00000000
Egress ACL ID: d5daa7fe09a6fdb400000000
AAA username: 
StartTime: Aug  9, 2017 19:05:50.276000000 MSK
```

Second flow, from interface 15 to interface 15 (with port forwarding in between):
```
Flow Id: 533847166
SrcAddr: 10.7.7.99 (10.7.7.99)
SrcPort: 45968
InputInt: 15
DstAddr: 83.69.211.186 (83.69.211.186)
DstPort: 22
OutputInt: 15
Protocol: 6
IPv4 ICMP Type: 0
IPv4 ICMP Code: 0
Post NAT Source IPv4 Address: 10.4.1.4 (10.4.1.4)
Post NAT Destination IPv4 Address: 10.6.77.241 (10.6.77.241)
Post NAPT Source Transport Port: 45968
Post NAPT Destination Transport Port: 22
Firewall Event: Flow created (1)
Extended firewall event code: ignore (0)
Observation Time Milliseconds: Aug  9, 2017 19:05:54.246000000 MSK
Ingress ACL ID: a573c83eccef216b00000000
Egress ACL ID: 2364199b6dcb35fe00000000
AAA username: 
StartTime: Aug  9, 2017 19:05:54.246000000 MSK
```

Either each interface could be displayed separately ntopng, or (as I personally prefer) traffic could be broken down by pairs of ingress and egress interface: LAN2LAN, LAN2WAN (initiated from inside), WAN2LAN (initiated from outside) etc. This would supply very valuable information to network administrator, since LAN2LAN is usually harmless, LAN2WAN occupies limited ISP bandwidth and WAN2LAN must be monitored for security issues. When they are all mixed together this distinction is lost.

**Comment by simonemainardi** [comment]
Did you consider the new features introduced with https://github.com/ntop/ntopng/issues/1326#issuecomment-316782228?

In particular, you can filter all the flows by exporter address (the asa in your case) and then by input and output ports. So very likely what you are looking is already available.

You may also want to disaggregate interfaces by input interface index as available in: 
![image](https://user-images.githubusercontent.com/3397663/29160121-55d9555e-7db1-11e7-85d3-ebb41166b6c9.png)

**Comment by qm2k** [comment]
I have only one flow exporter, so #1326 does not apply to my case.

As for disaggregation feature I tried various settings (VLAN id, Ingress Interface, Ingress VRF Id) and new interfaces just don't appear. What should I do exactly? And, judging by option names there's no option for egress interface or ingress/egress pair.

**Comment by simonemainardi** [comment]
> I have only one flow exporter, so #1326 does not apply to my case.

This is not true, even if you have only one exporter, you can still select it from the dropdown. Once it is selected, new input/output interface selection dropdowns will appear.

> As for disaggregation feature I tried various settings (VLAN id, Ingress Interface, Ingress VRF Id) and new interfaces just don't appear. What should I do exactly?

A restart of ntopng is required

> And, judging by option names there's no option for egress interface or ingress/egress pair.

correct

**Comment by qm2k** [comment]
> This is not true, even if you have only one exporter, you can still select it from the dropdown. Once it is selected, new input/output interface selection dropdowns will appear.

Yes indeed, works as you described. Not very intuitive though.

> A restart of ntopng is required

After trying restarts, `Ingress Interface` setting worked for me. This part of the problem is solved, thank you!

JFYI, there're however the following strange messages in syslog now (15, 3 and 16 are interface indices):
```
Aug 10 10:52:15 ntopng3 ntopng[230]: grep: [ifIdx:: No such file or directory
Aug 10 10:52:15 ntopng3 ntopng[230]: grep: 15]: No such file or directory
Aug 10 10:52:15 ntopng3 ntopng[230]: grep: [ifIdx:: No such file or directory
Aug 10 10:52:15 ntopng3 ntopng[230]: grep: 3]: No such file or directory
Aug 10 10:52:18 ntopng3 ntopng[230]: grep: [ifIdx:: No such file or directory
Aug 10 10:52:18 ntopng3 ntopng[230]: grep: 16]: No such file or directory
```

>> And, judging by option names there's no option for egress interface or ingress/egress pair.
> correct

Can you then consider this feature(s), please? Ingress traffic shows only one half of the load picture!

**Comment by simonemainardi** [comment]
>>This is not true, even if you have only one exporter, you can still select it from the dropdown. Once it is selected, new input/output interface selection dropdowns will appear.

> Yes indeed, works as you described. Not very intuitive though.

ok

>> A restart of ntopng is required

> After trying restarts, Ingress Interface setting worked for me. This part of the problem is solved, thank you!

alright

> JFYI, there're however the following strange messages in syslog now (15, 3 and 16 are interface indices):

try to run ntopng in foreground with /usr/local/bin/ntopng /etc/ntopng/ntopng.conf and look for extra information. I can't understand where the grep is coming from.

> Can you then consider this feature(s), please? Ingress traffic shows only one half of the load picture!

As shown above, ntopng already provides the necessary tools to get to the level of visibility required in this thread. If you need extra custom developments, please contact us privately.

**Comment by qm2k** [comment]
> try to run ntopng in foreground with /usr/local/bin/ntopng /etc/ntopng/ntopng.conf and look for extra information. I can't understand where the grep is coming from.

Running in foreground did not reveal much beyond already seen:
```
10/Aug/2017 12:31:47 [PeriodicActivities.cpp:50] Started periodic activities loop...
10/Aug/2017 12:31:47 [NetworkInterface.cpp:2273] Started packet polling on interface tcp://127.0.0.1:5556 [id: 3]...
10/Aug/2017 12:31:48 [CollectorInterface.cpp:116] Collecting flows on tcp://127.0.0.1:5556
grep: [ifIdx:: No such file or directory
grep: 15]: No such file or directory
10/Aug/2017 12:31:48 [Ntop.cpp:1564] Registered interface tcp://127.0.0.1:5556 [ifIdx: 15] [id: 4]
grep: [ifIdx:: No such file or directory
grep: 3]: No such file or directory
10/Aug/2017 12:31:49 [Ntop.cpp:1564] Registered interface tcp://127.0.0.1:5556 [ifIdx: 3] [id: 5]
grep: [ifIdx:: No such file or directory
grep: 16]: No such file or directory
10/Aug/2017 12:31:49 [Ntop.cpp:1564] Registered interface tcp://127.0.0.1:5556 [ifIdx: 16] [id: 6]
grep: [ifIdx:: No such file or directory
grep: 65535]: No such file or directory
10/Aug/2017 12:41:30 [Ntop.cpp:1564] Registered interface tcp://127.0.0.1:5556 [ifIdx: 65535] [id: 7]
```

But I grepped ntopng sources for "grep" and found [one place](https://github.com/ntop/ntopng/blob/7d72bcf20dea12151c547830e4ad42025189a735/src/Utils.cpp#L2374) where the interface name is unquoted in arguments to grep:
```
  sprintf(cmd, "netstat -rn | grep %s | grep 'UG' | awk '{print $2}'", ifname);
```
At least single quotes should be added around `%s` there, but even better would be to refactor this place since it looks vulnerable to injections.

**Comment by qm2k** [comment]
BTW latest ntopng also dumps core on exit.

**Comment by simonemainardi** [comment]
handled in https://github.com/ntop/ntopng/commit/d70e9f71466de1a5b8b9a8246d5c1127cdb2b4eb

in case you are experiencing a core, please upload it along with the ntopng binary for our inspection

**Comment by qm2k** [comment]
Created #1400.

**Comment by qm2k** [comment]
>> Can you then consider this feature(s), please? Ingress traffic shows only one half of the load picture!

> As shown above, ntopng already provides the necessary tools to get to the level of visibility required in this thread. If you need extra custom developments, please contact us privately.

Just one more question: is disaggregation part of open-source or proprietary parts? I tried to look for implementation of disaggregation on github, but couldn't find anything beside dialog strings. If it's open-source, I could probably try to add disaggregation by ingress-egress pairs myself.

**Comment by simonemainardi** [comment]
it's opensource. here's where the magic happens: https://github.com/ntop/ntopng/blob/dev/src/NetworkInterface.cpp#L1131
