### ISSUE TITLE
Ntopng Service Status - Debian 8.0 Jessie package

### ISSUE THREAD

**Issue by ADDISON74** [ntop/ntopng#14]
In a virtual machine I have Debian 8.0 Jessie for testing. With this Debian version I can install ntopng from repository instead of sources. This is a great because for Wheezy it was not available.

Ntopng installs fine as a service in the system and it works as expected (except Similarity bug I reported earlier). When I run:

root@server:~# service ntopng status

I get two warnings:

May 09 02:01:02 server1 ntopng[656]: [Geolocation.cpp:59] WARNING: Unable to read GeoIP database /usr/share/ntopng/httpdocs/geoip/GeoLiteCity.dat
May 09 02:01:02 server1 ntopng[656]: [Geolocation.cpp:59] WARNING: Unable to read GeoIP database /usr/share/ntopng/httpdocs/geoip/GeoLiteCityv6.dat
May 09 02:01:02 server1 sh[509]: Error Opening file /usr/share/ntopng/httpdocs/geoip/GeoIPASNumv6.dat
May 09 02:01:02 server1 sh[509]: Error Opening file /usr/share/ntopng/httpdocs/geoip/GeoLiteCity.dat
May 09 02:01:02 server1 sh[509]: Error Opening file /usr/share/ntopng/httpdocs/geoip/GeoLiteCityv6.dat
May 09 03:33:28 server1 ntopng[656]: [Lua.cpp:2775] WARNING: Script failure [/usr/share/ntopng/scripts/lua/host_details.lua][/usr/share/ntopng/scripts/lua/host_details.lua:1253: bad argument #1...cted, got nil)]
May 09 03:35:50 server1 ntopng[656]: [Lua.cpp:2775] WARNING: Script failure [/usr/share/ntopng/scripts/lua/host_details.lua][/usr/share/ntopng/scripts/lua/host_details.lua:1253: bad argument #1...cted, got nil)]
May 09 03:36:17 server1 ntopng[656]: [Lua.cpp:2775] WARNING: Script failure [/usr/share/ntopng/scripts/lua/host_details.lua][/usr/share/ntopng/scripts/lua/host_details.lua:1253: bad argument #1...cted, got nil)]
May 09 03:40:40 server1 ntopng[656]: [Lua.cpp:2775] WARNING: Script failure [/usr/share/ntopng/scripts/lua/host_details.lua][/usr/share/ntopng/scripts/lua/host_details.lua:1253: bad argument #1...cted, got nil)]
May 09 03:41:18 server1 ntopng[656]: [Lua.cpp:2775] WARNING: Script failure [/usr/share/ntopng/scripts/lua/host_details.lua][/usr/share/ntopng/scripts/lua/host_details.lua:1253: bad argument #1...cted, got nil)] 

I attach a screenshot from my Putty session to see them too. These warnings are related to "GeoIP missing files" and "Script failure". 

For the first warning I guess those files are missing. But for the second warning I don't have any idea what this could be. This warning is related to Similarity bug I posted earlier.

Thank you.

![ntopng_service_status](https://cloud.githubusercontent.com/assets/8360474/7549467/4416d622-f63e-11e4-8c83-b417aefdbc89.jpg)

**Comment by ariava** [comment]
@ADDISON74 to get rid of the GeoIP warning it seems like you'd need to download GeoIP dat packages which can be achieved by issuing "make geoip". As of the script failure, as in the other issue you filed I don't think you are using the latest could. Could you please try again with the latest GitHub code?

**Comment by ariava** [comment]
@ADDISON74 sorry for following up on this, did you have any chance to test the new git code?

**Comment by ADDISON74** [comment]
Sorry for my late reply. I hope to get more time to revise the package from Debian 8 repository. There is no update till now, even I contacted the guys who maintain the package. I will take yours from here and see what is happening. Thank you for your support.
