### ISSUE TITLE
Feature request: top endpoints chart on dashboard

### ISSUE THREAD

**Issue by qm2k** [ntop/ntopng#1407]
Dashboard already has Top Local Talkers and Top Remote Destinations in the table form. However, chart would be more informative since it shows not only current situation but history. Here's how it looks in my home-grown tool:

![top_clients_chart](https://user-images.githubusercontent.com/13719792/29464972-4ebf17a0-8440-11e7-8ef1-0b3297fe1924.png)

**Comment by simonemainardi** [comment]
merged with https://github.com/ntop/ntopng/issues/1670
