### ISSUE TITLE
Feature request: statistics for number of simultaneous flows

### ISSUE THREAD

**Issue by qm2k** [ntop/ntopng#1408]
Along with number of bytes transferred important measure to monitor in many networks is number of simultaneous flows (preferably with break-down by client etc.). This is because most firewall devices inherently have limitations on number of simultaneously supported flows before packet loss or performance degradation occurs. Some applications (BitTorrent, port scans) may create huge number of flows and create problems for other clients without even being visible on traffic charts.

**Comment by simonemainardi** [comment]
The number of active flows is saved for every interface and for every local host. It is available as an historical time series. The number of active (or very recently expired) flows is also shown at the bottom of any page. If this does not suffice, please try and explain how would you like to see this information.

**Comment by qm2k** [comment]
Yes, I understand that all information is there, which is fortunate. I'm talking about charts. Primarily dashboard could show more of it, but also pages of individual hosts, networks, interfaces etc. On the dashboard it'd be nice to see historical charts of number of active flows, table of top hosts by number of flows, or better chart of top hosts by number of flows in the same way as described in #1407 but for flows in place of bytes.

**Comment by qm2k** [comment]
P.S. The number of flows at the bottom of any page is not very accurate. For instance, right now it is less than 2000 flows according to ASA command line (which can list them all), but ntopng shows 6200. Looks like ntopng and nprobe do not take flow close messages into account and just wait for some predefined timeout, which leads to exaggeration of number of very short-lived flows.

**Comment by simonemainardi** [comment]
merged with https://github.com/ntop/ntopng/issues/1670
