### ISSUE TITLE
Missed Top Talker .. again

### ISSUE THREAD

**Issue by paoloB132** [ntop/ntopng#141]
Was already opened issue: Missed Top Talker (#38)

[root@ntop yum.repos.d]# uname -a
Linux ntop.rfx.local 2.6.32-573.3.1.el6.x86_64 #1 SMP Thu Aug 13 22:55:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I've upgraded to the last stable ntop  for CentOS, clean all previous reference in redis db and also remove previous /var/tmp/ntopng.

Installed:
  n2disk.x86_64 0:2.3.150830-4445    nbox.noarch 0:2.3.0-368    nprobe.x86_64 0:7.2.150830-4466    ntopng.x86_64 0:2.0.150830-212    ntopng-data.noarch 0:2.0.150830-212   
  pfring.x86_64 0:6.0.3-183

I own a professional license (research lab).

After start ntopng daemon, I noticed that the community version has been activated (no way to instert pro key), but worst top talkers in Historical Activity Form (moving on graph) disappeared again.

I noticed also that now https on port 3001 is forced now, no probkem here.

Regards,
Paolo.

**Comment by lmangani** [comment]
Paolo,

Are there any console messages during startup about license or license validity?

**Comment by paoloB132** [comment]
Hi Lorenzo,

here relevant lines form /var/log/messages:

Aug 31 10:34:27 ntop root: ntopng start
Aug 31 10:34:27 ntop kernel: [PF_RING] Welcome to PF_RING 6.0.3 ($Revision: master:40ddb1a2951023043c034c1d2d24f49f93eb61bf$)
Aug 31 10:34:27 ntop kernel: (C) 2004-14 ntop.org
Aug 31 10:34:27 ntop kernel: [PF_RING] registered /proc/net/pf_ring/
Aug 31 10:34:27 ntop kernel: NET: Registered protocol family 27
Aug 31 10:34:27 ntop kernel: [PF_RING] Min # ring slots 4096
Aug 31 10:34:27 ntop kernel: [PF_RING] Slot version     16
Aug 31 10:34:27 ntop kernel: [PF_RING] Capture TX       Yes [RX+TX]
Aug 31 10:34:27 ntop kernel: [PF_RING] IP Defragment    No
Aug 31 10:34:27 ntop kernel: [PF_RING] Initialized correctly
Aug 31 10:34:27 ntop kernel: device eth1 entered promiscuous mode

and form /var/log/ntopng/ntopng.log

31/Aug/2015 10:34:27 [src/Ntop.cpp:785] Setting local networks to 192.168.0.0/16, 150.178.3.0/24, 150.178.32.0/24, 150.178.33.0/24, 150.178.34.0/24
31/Aug/2015 10:34:27 [src/Redis.cpp:93] Successfully connected to redis 127.0.0.1:6379@0
31/Aug/2015 10:34:27 [src/PF_RINGInterface.cpp:54] Reading packets from PF_RING v.6.0.3 interface eth1...
31/Aug/2015 10:34:27 [src/Ntop.cpp:1033] Registered interface view eth1 [id: 0]
31/Aug/2015 10:34:27 [src/Ntop.cpp:1003] Registered interface eth1 [id: 0]
31/Aug/2015 10:34:27 [src/Utils.cpp:292] User changed to nobody
31/Aug/2015 10:34:27 [src/main.cpp:236] PID stored in file /var/tmp/ntopng.pid
31/Aug/2015 10:34:27 [src/HTTPserver.cpp:492] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
31/Aug/2015 10:34:27 [src/HTTPserver.cpp:495] HTTP server listening on port 3000
31/Aug/2015 10:34:27 [src/HTTPserver.cpp:498] HTTPS server listening on port 3001
31/Aug/2015 10:34:27 [src/main.cpp:287] Working directory: /var/tmp/ntopng
31/Aug/2015 10:34:27 [src/main.cpp:289] Scripts/HTML pages directory: /usr/share/ntopng
31/Aug/2015 10:34:27 [src/Ntop.cpp:271] Welcome to ntopng x86_64 v.2.0.150830 - (C) 1998-15 ntop.org
31/Aug/2015 10:34:27 [src/PeriodicActivities.cpp:53] Started periodic activities loop...
31/Aug/2015 10:34:27 [src/RuntimePrefs.cpp:32] Dumping alerts into syslog
31/Aug/2015 10:34:27 [src/NetworkInterface.cpp:1201] Started packet polling on interface eth1 [id: 0]…

Regards,
Paolo.

> On 31/ago/2015, at 10:55, Lorenzo Mangani <notifications@github.com> wrote:
> 
> Paolo,
> 
> Are there any console messages during startup about license or license validity?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

------------------------------------------------------------------------------------------------
Paolo Barbato

Consorzio RFX
corso Stati Uniti,4                                  
35127 Padova - Italy                     	                 
Network Administrator 
phone: +39 049 8295097 fax: +39 049 8700718
------------------------------------------------------------------------------------------------

**Comment by cardigliano** [comment]
Hi Paolo
please provide:
1. output of ntopng --check-license
2. ntopng configuration

Thank you
Alfredo

**Comment by paoloB132** [comment]
> On 31/ago/2015, at 11:16, Alfredo Cardigliano <notifications@github.com> wrote:
> 
> Hi Paolo
> please provide:
> 1. output of ntopng --check-license

[root@ntop ntopng-dev]# /usr/bin/ntopng --check-license
/usr/bin/ntopng: unrecognized option '--check-license’


> 2. ntopng configuration
> 
[root@ntop ntopng-dev]# more /etc/ntopng/ntopng.conf
-G=/var/tmp/ntopng.pid
-m=192.168.0.0/16, 150.178.3.0/24, 150.178.32.0/24, 150.178.33.0/24, 150.178.34.0/24
-i=eth1


> Thank you
> Alfredo
> 
> 
> > On 31 Aug 2015, at 10:59, paoloB132 <notifications@github.com> wrote:
> > 
> > Hi Lorenzo,
> > 
> > here relevant lines form /var/log/messages:
> > 
> > Aug 31 10:34:27 ntop root: ntopng start
> > Aug 31 10:34:27 ntop kernel: [PF_RING] Welcome to PF_RING 6.0.3 ($Revision: master:40ddb1a2951023043c034c1d2d24f49f93eb61bf$)
> > Aug 31 10:34:27 ntop kernel: (C) 2004-14 ntop.org
> > Aug 31 10:34:27 ntop kernel: [PF_RING] registered /proc/net/pf_ring/
> > Aug 31 10:34:27 ntop kernel: NET: Registered protocol family 27
> > Aug 31 10:34:27 ntop kernel: [PF_RING] Min # ring slots 4096
> > Aug 31 10:34:27 ntop kernel: [PF_RING] Slot version 16
> > Aug 31 10:34:27 ntop kernel: [PF_RING] Capture TX Yes [RX+TX]
> > Aug 31 10:34:27 ntop kernel: [PF_RING] IP Defragment No
> > Aug 31 10:34:27 ntop kernel: [PF_RING] Initialized correctly
> > Aug 31 10:34:27 ntop kernel: device eth1 entered promiscuous mode
> > 
> > and form /var/log/ntopng/ntopng.log
> > 
> > 31/Aug/2015 10:34:27 [src/Ntop.cpp:785] Setting local networks to 192.168.0.0/16, 150.178.3.0/24, 150.178.32.0/24, 150.178.33.0/24, 150.178.34.0/24
> > 31/Aug/2015 10:34:27 [src/Redis.cpp:93] Successfully connected to redis 127.0.0.1:6379@0
> > 31/Aug/2015 10:34:27 [src/PF_RINGInterface.cpp:54] Reading packets from PF_RING v.6.0.3 interface eth1...
> > 31/Aug/2015 10:34:27 [src/Ntop.cpp:1033] Registered interface view eth1 [id: 0]
> > 31/Aug/2015 10:34:27 [src/Ntop.cpp:1003] Registered interface eth1 [id: 0]
> > 31/Aug/2015 10:34:27 [src/Utils.cpp:292] User changed to nobody
> > 31/Aug/2015 10:34:27 [src/main.cpp:236] PID stored in file /var/tmp/ntopng.pid
> > 31/Aug/2015 10:34:27 [src/HTTPserver.cpp:492] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
> > 31/Aug/2015 10:34:27 [src/HTTPserver.cpp:495] HTTP server listening on port 3000
> > 31/Aug/2015 10:34:27 [src/HTTPserver.cpp:498] HTTPS server listening on port 3001
> > 31/Aug/2015 10:34:27 [src/main.cpp:287] Working directory: /var/tmp/ntopng
> > 31/Aug/2015 10:34:27 [src/main.cpp:289] Scripts/HTML pages directory: /usr/share/ntopng
> > 31/Aug/2015 10:34:27 [src/Ntop.cpp:271] Welcome to ntopng x86_64 v.2.0.150830 - (C) 1998-15 ntop.org
> > 31/Aug/2015 10:34:27 [src/PeriodicActivities.cpp:53] Started periodic activities loop...
> > 31/Aug/2015 10:34:27 [src/RuntimePrefs.cpp:32] Dumping alerts into syslog
> > 31/Aug/2015 10:34:27 [src/NetworkInterface.cpp:1201] Started packet polling on interface eth1 [id: 0]…
> > 
> > Regards,
> > Paolo.
> > 
> > > On 31/ago/2015, at 10:55, Lorenzo Mangani <notifications@github.com> wrote:
> > >
> > > Paolo,
> > >
> > > Are there any console messages during startup about license or license validity?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub.
> > >
> > 
> > ------------------------------------------------------------------------------------------------
> > Paolo Barbato
> > 
> > Consorzio RFX
> > corso Stati Uniti,4
> > 35127 Padova - Italy
> > Network Administrator
> > phone: +39 049 8295097 fax: +39 049 8700718
> > ------------------------------------------------------------------------------------------------
> > 
> > —
> > Reply to this email directly or view it on GitHub <https://github.com/ntop/ntopng/issues/141#issuecomment-136306636>.
> > 
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/ntop/ntopng/issues/141#issuecomment-136310184>.
> 

------------------------------------------------------------------------------------------------
Paolo Barbato

Consorzio RFX
corso Stati Uniti,4                                  
35127 Padova - Italy                     	                 
Network Administrator 
phone: +39 049 8295097 fax: +39 049 8700718
------------------------------------------------------------------------------------------------

**Comment by lucaderi** [comment]
Paolo the stable version contains just crash fixes as all new features and enhancements go in the dev packages. Would you mind using the dev packages and report if this issue is now working?

**Comment by paoloB132** [comment]
Hi Luca,

first, compliments for Ntop great enhancements!

Do you mean change ntop yum repo reference from baseurl=http://packages.ntop.org/centos-stable/$releasever/$basearch/ to baseurl=http://packages.ntop.org/centos/$releasever/$basearch/

?

Regards,
Paolo.
> On 31/ago/2015, at 16:35, Luca Deri <notifications@github.com> wrote:
> 
> Paolo the stable version contains just crash fixes as all new features and enhancements go in the dev packages. Would you mind using the dev packages and report if this issue is now working?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

------------------------------------------------------------------------------------------------
Paolo Barbato

Consorzio RFX
corso Stati Uniti,4                                  
35127 Padova - Italy                     	                 
Network Administrator 
phone: +39 049 8295097 fax: +39 049 8700718
------------------------------------------------------------------------------------------------

**Comment by paoloB132** [comment]
Yes, now it works as expected !

Thanks, Paolo.


> On 31/ago/2015, at 16:39, Paolo Barbato <paolo.barbato@igi.cnr.it> wrote:
> 
> Hi Luca,
> 
> first, compliments for Ntop great enhancements!
> 
> Do you mean change ntop yum repo reference from baseurl=http://packages.ntop.org/centos-stable/$releasever/$basearch/ <http://packages.ntop.org/centos-stable/$releasever/$basearch/> to baseurl=http://packages.ntop.org/centos/$releasever/$basearch/
> 
> ?
> 
> Regards,
> Paolo.
>> On 31/ago/2015, at 16:35, Luca Deri <notifications@github.com <mailto:notifications@github.com>> wrote:
>> 
>> Paolo the stable version contains just crash fixes as all new features and enhancements go in the dev packages. Would you mind using the dev packages and report if this issue is now working?
>> 
>> —
>> Reply to this email directly or view it on GitHub.
>> 
> 
> ------------------------------------------------------------------------------------------------
> Paolo Barbato
> 
> Consorzio RFX
> corso Stati Uniti,4                                  
> 35127 Padova - Italy                     	                 
> Network Administrator 
> phone: +39 049 8295097 fax: +39 049 8700718
> ------------------------------------------------------------------------------------------------
> 

------------------------------------------------------------------------------------------------
Paolo Barbato

Consorzio RFX
corso Stati Uniti,4                                  
35127 Padova - Italy                     	                 
Network Administrator 
phone: +39 049 8295097 fax: +39 049 8700718
------------------------------------------------------------------------------------------------

**Comment by cardigliano** [comment]
Correct, please try using http://packages.ntop.org/centos/

Alfredo
