### ISSUE TITLE
slack  Webhook url configuration is not saving  

### ISSUE THREAD

**Issue by chlochlo78** [ntop/ntopng#1412]
hi,

i've activated slack notification,
( how to from https://github.com/ntop/ntopng/blob/dev/doc/README.slack )
every channel are configured in slack host
testing with curl to send msg = OK

but runtimeprefs.json is not up to date while i try to configure Webhook url https://hooks.slack.com/services/XXX/YYY/ZZZ
:(

best regards

**Comment by chlochlo78** [comment]
can't see log about slack or pref while logging is in trace or debug mode

` more runtimeprefs.json
{ "ntopng.prefs.housekeeping_frequency": 5, "ntopng.prefs.local_host_cache_duration": 3600, "ntopng.prefs.local_host_max_idle": 300, "ntopng.prefs.non_local_host_max_idle": 60, "ntopng.prefs.flow_max_idle"
: 60, "ntopng.prefs.active_local_host_cache_interval": 3600, "ntopng.prefs.intf_rrd_raw_days": 1, "ntopng.prefs.intf_rrd_1min_days": 30, "ntopng.prefs.intf_rrd_1h_days": 100, "ntopng.prefs.intf_rrd_1d_days
": 365, "ntopng.prefs.other_rrd_raw_days": 1, "ntopng.prefs.other_rrd_1min_days": 30, "ntopng.prefs.other_rrd_1h_days": 100, "ntopng.prefs.other_rrd_1d_days": 365, "ntopng.prefs.host_top_sites_creation": t
rue, "ntopng.prefs.is_local_host_cache_enabled": true, "ntopng.prefs.is_active_local_host_cache_enabled": true, "ntopng.prefs.tiny_flows_export_enabled": true, "ntopng.prefs.max_num_alerts_per_entity": 102
4, "ntopng.prefs.max_num_flow_alerts": 16384, "ntopng.prefs.flow_device_port_rrd_creation": false, "ntopng.prefs.disable_alerts_generation": false, "ntopng.prefs.probing_alerts": true, "ntopng.prefs.ssl_al
erts": false, "ntopng.prefs.alerts_syslog": false, "ntopng.prefs.alerts.slack_notifications_enabled": true, "ntopng.prefs.alerts.dump_alerts_when_iface_is_alerted": true, "ntopng.prefs.max_num_packets_per_
tiny_flow": 3, "ntopng.prefs.max_num_bytes_per_tiny_flow": 64, "ntopng.prefs.safe_search_dns": 2078163920, "ntopng.prefs.global_dns": 4294967295, "ntopng.prefs.secondary_dns": 4294967295, "ntopng.prefs.ena
ble_captive_portal": false, "ntopng.prefs.redirection_url": "http:\/\/www.ntop.org", "ntopng.prefs.max_ui_strlen": 24, "ntopng.prefs.host_mask": 0, "ntopng.prefs.tcp_flags_rrd_creation": "1", "ntopng.prefs
.tcp_retr_ooo_lost_rrd_creation": "1", "ntopng.prefs.vlan_rrd_creation": "0", "ntopng.prefs.asn_rrd_creation": "0", "ntopng.prefs.host_categories_rrd_creation": "0", "ntopng.prefs.mysql_retention": "7", "n
topng.prefs.minute_top_talkers_retention": "365", "ntopng.prefs.host_rrd_creation": "1", "ntopng.prefs.host_ndpi_rrd_creation": "1", "ntopng.prefs.logging_level": "normal", "ntopng.prefs.enable_access_log"
: "0", "ntopng.prefs.google_apis_browser_key": "", "ntopng.prefs.thpt_content": "bps", "ntopng.prefs.alerts.mysql_check_open_files_limit": "1", "ntopng.prefs.host_blacklist": "1", "ntopng.prefs.show_advanc
ed_prefs": "false", "ntopng.prefs.dynamic_flow_collection_mode": "none" }`

**Comment by chlochlo78** [comment]
1/  i've compiled it from last git pull


a/  apt-get install build-essential git bison flex libxml2-dev libpcap-dev libtool libtool-bin rrdtool librrd-dev autoconf automake autogen redis-server wget libsqlite3-dev libhiredis-dev libgeoip-dev libcurl4-openssl-dev libpango1.0-dev libcairo2-dev libnetfilter-queue-dev zlib1g-dev libssl-dev
b/  cd ../
c/ git clone https://github.com/ntop/nDPI.git; cd nDPI; ./autogen.sh; make
d/ cd ../ntopng

./configure --prefix=/APPS/NTOPNG \
--bindir=/APPS/NTOPNG/bin \
--sbindir=/APPS/NTOPNGi/sbin \
--libexecdir=/APPS/NTOPNG/libexec \
--sysconfdir=/APPS/NTOPNG/etc \
--sharedstatedir=/APPS/NTOPNG/com \
--localstatedir=/APPS/NTOPNG/var \
--libdir=/APPS/NTOPNG/lib \
--includedir=/APPS/NTOPNG/include \
--oldincludedir=/usr/include \
--datarootdir=/APPS/NTOPNG/share \
--datadir=/APPS/NTOPNG/share/data \
--infodir=/APPS/NTOPNG/share/data/info \
--localedir=/APPS/NTOPNG/share/data/locale \
--mandir=/APPS/NTOPNG/share/man \
--docdir=/APPS/NTOPNG/share/doc/ntopng \
--htmldir=/APPS/NTOPNG/share/doc/ntopng/html \
--dvidir=/APPS/NTOPNG/share/doc/ntopng/dvi \
--pdfdir=/APPS/NTOPNG/share/doc/ntopng/pdf \
--psdir=/APPS/NTOPNG/share/doc/ntopng/ps

2/ using ntopng.conf 

 --sticky-hosts none
-d  /APPS/NTOPNG/data
-e
-t /APPS/NTOPNG/share/ntopng
-1 /APPS/NTOPNG/share/ntopng/httpdocs
-2 /APPS/NTOPNG/share/ntopng/scripts
-3 /APPS/NTOPNG/share/ntopng/scripts/callbacks
-4 /APPS/NTOPNG/data
-m "xxx.xxx.xxx.xxx/32,yyy.yyy.yyy.yyy/32,zzz.zzz.zzz.zzz/32"
-G /APPS/NTOPNG/ntop-git.pid
-U myuserunix
-w 3000
--dns-mode 1
#--http-prefix /lan

3/ starting like
`/APPS/NTOPNG/bin/ntopng /APPS/NTOPNG/ntopng.conf`

**Comment by emanuele-f** [comment]
This is fixed with commit `d67e1da455241016d42a264471fd55adf7df2fb7`. Please `git pull` and enjoy. Thank you for reporting.

**Comment by chlochlo78** [comment]
Fast fix! It works :) thanks, I have to manage spam about suspicious  TCP/SYN now lol ( may be turn it off for a few day )

**Comment by emanuele-f** [comment]
You can configure alerts threasholds from a local host page (click the triangle icon). See `SYN Flood Attacker` and `SYN Flood Victim`

**Comment by chlochlo78** [comment]
ok thx :) 
i reduced them by turning off Trigger alerts for loopback to loopback :)

client proxy pac => URL nginx > LB haproxy 2 squid => LB haproxy 2 c-icap (squidguard+clamav) > LB haproxy 2 privoxy

i'll observe traffic and adapt value, before tuning on slack notification ;)
host_details.lua?page=alerts&tab=min&host=<ip>&ifid=0

thx a lot
