### ISSUE TITLE
Can not login at web interface except with the external IP

### ISSUE THREAD

**Issue by myfingerhurt** [ntop/ntopng#1413]
I'm working on a VPS, because I don't want to expose the ntopng port:3000 to the outer-world,  so I use zerotier to secure it. But I can not login at the web interface except with the external IP. And I saw lots of people had the same problem without a solution. 

`10.9.8.10` not working. VPN
`127.0.0.1` not working. 
`150.x.x.x` working. external IP
`2400:8500:1302:844:150:xx:xxx:xx` not tested. external IP

```
~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

I have two networks: 
`ens3` with IPv4 and IPv6,  `150.x.x.x` , `2400:8500:1302:844:150:xx:xxx:xx`
`zt0` (zerotier). `10.9.8.10`

First I tried `sudo apt-get install ntopng`  

Access from external IPV4 `150.x.x.x` is good, haven't tested on IPv6, can log in with default user and password admin/admin.
Access from zerotier network can open the page but can not log in. 
I thought that version v2.3 was too old, so I uninstalled it by `sudo apt-get remove --purge ntopng`

And did everything as here said: `http://packages.ntop.org/apt-stable/`

Now I'm using this version.
```
~$ sudo ntopng -V
v.3.0.170826 [Enterprise/Professional Edition]
GIT rev:   3.0-stable:8e2a7438a8be70a2209f08cd44940d93bd018230:20170826
Pro rev:   r1101
System Id: A862BE2100030821
Built on:  Ubuntu 16.04.3 LTS
```

Start ntopng listen to the localhost,
`~$ sudo ntopng  -w:3000 --verbose 6`

add a forward rule to iptables 
`sudo iptables -t nat -A PREROUTING -d 10.9.x.x -p tcp --dport 3000 -j DNAT --to-destination 127.0.0.1:3000`

The same thing happens,
`http://10.9.8.10:3000`
zerotier network can open the page but can not log in with default user and password admin/admin. 

Here is the log
[ntopng_localhost_3000.txt](https://github.com/ntop/ntopng/files/1255198/ntopng_localhost_3000.txt)

--------------------------------------------------------

Start ntopng again listen to all address,
`~$ sudo ntopng  -w 3000 --verbose 6`
Delete iptables forwarding rules
`sudo iptables -t nat -D PREROUTING -d 10.9.x.x -p tcp --dport 3000 -j DNAT --to-destination 127.0.0.1:3000`

`http://150.x.x.x:3000`
Can log in with default user and password admin/admin.
`http://10.9.x.x:3000`
Can open the page but can not log in

Here is the log with --verbose 6, about the LICENSE ERROR --community, I have tried that too, but ntopng outputs blank and nothing.
[ntopng_all_3000.txt](https://github.com/ntop/ntopng/files/1255199/ntopng_all_3000.txt)

**Comment by emanuele-f** [comment]
Hi, I can actually login to ntopng through VPN. Are you using the same browser on both external and internal IPs? What browser is it? Can you exclude this issue is linked with zerotier?

Note: the `127.0.0.1` connection can only work within the VPS server itself, you cannot connect remotely to that address.

**Comment by simonemainardi** [comment]
> http://10.9.x.x:3000
> Can open the page but can not log in

What happens? Do you get redirected to the login page? Use the browser inspector to see all the network requests/responses

As suggested by @emanuele-f you should you exclude this issue is linked with zerotier.

**Comment by myfingerhurt** [comment]
> Are you using the same browser on both external and internal IPs? 

sorry, I thought I mentioned that. It was Chrome that I was using. Yes, the same browse.

VPS has zerotier on it, assigned to 10.9.8.10. My Desktop PC also has zerotier installed, assigned to 10.9.8.8

>Can you exclude this issue is linked with zerotier?

It works perfectly with all other services, such webmin, i2p, so I automatically think zerotier is OK.

>Note: the 127.0.0.1 connection can only work within the VPS server itself, you cannot connect remotely to that address.

Even with iptables redirected and localhost forward? It works with all other services such as SOCK/HTTP Proxy, myphpadmin and other WEBUIs. I do this to make it work. And it was acting same as direct access to the 10.9.8.10. 
`sudo sysctl -w net.ipv4.conf.zt0.route_localnet=1`
`sudo iptables -t nat -A PREROUTING -d 10.9.8.10 -p tcp --dport 3000 -j DNAT --to-destination 127.0.0.1:3000`

>What happens? Do you get redirected to the login page? 

Yes, it clears the username and password that I have input in the login form, and reload the login page automatically.

>Use the browser inspector to see all the network requests/responses

Good point, I'll try that right away.

That is so peculiar!!, it's suddenly working!! As I remembered, What I only did was rebooting my VPS last night. Now it works on both 127.0.0.1 forwarding to 10.9.8.10 with -w:3000 and direct access from any of my IPs with -w 3000.

I'm guessing this might due to some ports were occupied when WebUI was trying to open port and exchanging data? And  `--community` is working too. Yesterday it gave me blank responding.

Thank you for your time, I think maybe the fresh installing will reproduce the same issues?

By the way, is there any rules be able to set the ntopng WebUI only bind to specific IP or network such as eth0 rather than all of them. I have a dozen of standalone external addresses, comparing to block them one by one, being able to bind to the specific IP/Network will be much appreciated.

**Comment by simonemainardi** [comment]
I think the most probable explanation is that you were experimenting iptables rules using the append with `-A`. So you could have inadvertently added a rule that was actually dropping the traffic destined to ntopng.

Since the reboot flushed the iptables, re-applying the rule could have done the trick.

> I'm guessing this might due to some ports were occupied when WebUI was trying to open port and exchanging data?

ntopng doesn't start if the port is occupied

> Thank you for your time, I think maybe the fresh installing will reproduce the same issues?

can you try and report?

> By the way, is there any rules be able to set the ntopng WebUI only bind to specific IP or network such as eth0 rather than all of them. I have a dozen of standalone external addresses, comparing to block them one by one, being able to bind to the specific IP/Network will be much appreciated.

you can bind ntopng to a specific address using option -w, e.g., `-w 192.168.1.1:3001`. See the help for additional info.

**Comment by simonemainardi** [comment]
Safe to close now as issue is solved.

**Comment by myfingerhurt** [comment]
> you can bind ntopng to a specific address using option -w, e.g., -w 192.168.1.1:3001. See the help for additional info.

Thank you for your help, apparently when I first installed `ntopng -h`  it was an old version, only supported two options either -w:3000 or -w 3000

>can you try and report?

Ok, when I'm done, I will report back. But will not do it soon.
