### ISSUE TITLE
RuntimePrefs does not handle wildcards

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#1414]
Redis supports wildcards as the input of the `keys` command. On the other end, RuntimePrefs does not support it and this breaks the `ntop.getKeysCache` calls (e.g. deleteCachePattern in flushAlertsData).

As an alternative to implement wildcards via regex, redis itself can be used to compute the wildcards. This would require to copy all the RuntimePrefs data to Redis on startup and every time a new set command is executed

**Comment by simonemainardi** [comment]
Preferences have been reworked and RuntimePrefs has been removed. So everything can be used as is. The redis command `KEYS` with wildcard can be used with the guarantee that all the keys matching the specified criteria will be returned.
