### ISSUE TITLE
Historical Data Explorer handles timezones incorrectly

### ISSUE THREAD

**Issue by qm2k** [ntop/ntopng#1415]
I'm running server in UTC timezone, but my browser is on a machine with local timezone, which is +0300 (Moscow). As a result values of `Begin Date/Time` and `End Date/Time` are initially prefilled correctly (in local timezone), but after I press `Search Flows` they shift 3 hours to the future and naturally nothing is found. Every time I press `Search Flows` they are shifted another 3 hours to the future and so one. Page is only usable if I always manually adjust time 3 hours earlier.

I presume this is because page sends `period_begin_str` and `period_end_str` CGI arguments as text strings without timezone specification, and on server they are parsed as UTC.

Here's what I see initially:
![screenshot from 2017-08-29 11 36 34 cropped](https://user-images.githubusercontent.com/13719792/29812653-fe9987f6-8caf-11e7-8179-067f831dd295.png)

After I press `Search Flows` once:
![screenshot from 2017-08-29 11 38 28 cropped](https://user-images.githubusercontent.com/13719792/29812672-0d0963ec-8cb0-11e7-812d-6e5dcf970242.png)

After I press `Search Flows` another time:
![screenshot from 2017-08-29 11 44 35 cropped](https://user-images.githubusercontent.com/13719792/29812677-107ca3d6-8cb0-11e7-98c7-f411b9e7c633.png)

**Comment by simonemainardi** [comment]
thanks for reporting, issue is fixed and will be available starting from tomorrow

**Comment by qm2k** [comment]
I can confirm it is fixed in v.3.1.170905

**Comment by samuelwei** [comment]
I do have the same issue in v.3.6.180917

**Comment by emanuele-f** [comment]
@SamuelWei please open a separate issue with more information and screenshots if possible
