### ISSUE TITLE
Beginner needs help

### ISSUE THREAD

**Issue by Salami66** [ntop/ntopng#1417]
Hi,

I've installed nprobe and ntopng on an ubuntu 16.04 VM and I've read the users guide.
So I wanted to see the traffic from my host pc or the network he is in.

But I don't get it, how to say which network you want to "see" and where you decide that and so on...

I made that: /usr/local/bin/ntopng -i tcp://127.0.0.1:5556
and that: /usr/local/bin/nprobe -i ens33 -n none --zmq tcp://*:5556
on my VM on two different terminals, but at the end, when I stop it, there is only the message, that there was no traffic, so I'm sure, that I'm doing something wrong.

At the end of the day, I want to check/see the network flow of the network, so I think I have to enter the IP from the router or so.
And I would want to see that all on a webinterface.

Is there anyone who can help me a lil bit?

Thanks!

**Comment by emanuele-f** [comment]
Hi @Salami66
In order to monitor all your network traffic, you need to ensure ntopng has visibility over it. You can achieve traffic visibility in two ways:

- Make ntopng sit between your local network and the internet. So your ntopng running pc must have two network interfaces, one connected to the LAN, the other to the WAN. In this setup you can also enforce traffic policies through ntopng.

- Configure you router as a flow exporter to nprobe. Both nprobe and ntopng will run on your local pc. This will require a special router appliance, usually talking NetFlow protocol

**Comment by Salami66** [comment]
Thanks @emanuele-f !
But I've only the following options:
Briged: Connected directly to the physical network (thats the one I wanted to take)
NAT: Used to share the host's IP address
Host-only: A private network shared with the host
Custom: Specific virtual network

So I can't make an interface connected to the lan and another one connected to the wan?


But another problem is, if I go on 127.0.0.1 on my VM where nProbe and ntopng are installed, I have to type in my credentials in nBox / nTop windows, but I don't have them..?

**Comment by emanuele-f** [comment]
The VM adds another layer of possible problems when configuring such a setup, so I can suggest you to try with a bare metal setup first (e.g. an old pc) and then possibly move to a VM.

For a basic setup monitoring, you can do the following
- Your pc must have 2 ethernet interfaces (plus one management). Connect one interface to the WAN and the other to the LAN. The management should be connected to your pc
- Start ntopng in inline mode (`-i bridge:eth0,eth1`)
- Your clients should now be able to communicate with the WAN (e.g. internet)
- By connecting to the management interface, you should be able to see all the traffic and apply policies

Please see `https://github.com/ntop/ntopng/blob/dev/doc/README.inline` for a more advanced inline modes.

@simonemainardi @cardigliano please tell how to setup a ntopng bridge inside a vm

The default credentials are `admin admin`

**Comment by simonemainardi** [comment]
To use a bridge under a VM you may want to use PCI passthrough to grant exclusive NIC control to the VM.

Here are the instructions to configure it with KVM/QEMU: https://github.com/ntop/PF_RING/blob/dev/doc/README.virsh_hostdev.md
