### ISSUE TITLE
List of application protocols disappeared on the protocol tab

### ISSUE THREAD

**Issue by fatlouis87** [ntop/ntopng#1418]
Is there any kind of problem with displaying the list of application protocols under the protocols tab?

a few weeks ago they all show up with the amount of send/received data.

actually this list is just empty (headers are displayed: 

Application Protocol | Duration | Sent | Received | Breakdown | Total
-- | -- | -- | -- | -- | --

protocols for ports and for host traffic are working fine.
ntopng  v.3.1.170830 installed on Ubuntu 16.04
![ntopng_no_app_protocols](https://user-images.githubusercontent.com/31470728/29863780-01c56550-8d71-11e7-9fad-362b6b88cebd.png)

Thanks in Advance

**Comment by emanuele-f** [comment]
Hi, this has been fixed with commit 2a21832c54823485d78b3a4d3ec9b90c5bc593ba . Thank you for reporting.
