### ISSUE TITLE
Traffic Report Not Showing Host Aliases

### ISSUE THREAD

**Issue by dgettis** [ntop/ntopng#1419]
I have assigned host aliases to most of the IP's on our local network, and while they display in Looking Glass, they do not display in Traffic Report - only the IP address is shown under "Top Local Hosts." If I click on a particular IP from the Traffic Report, then click "Set Host Alias," sure enough the alias is there. How do I get Traffic Report to display the aliases?

I'm running ntopng 3.1.170626 - Pro Small Business Edition with nprobe 3.1.170626 - Pro Small Business Edition on debian Jessie.

Thanks!

**Comment by dgettis** [comment]
Why was this closed?

**Comment by emanuele-f** [comment]
Hi, I've committed a fix for this, please wait next build tomorrow. Reopen if necessary.

**Comment by dgettis** [comment]
emanuele-f, thanks so much! I tried the new build, and it works perfectly!

**Comment by emanuele-f** [comment]
Thank you for reporting!
