### ISSUE TITLE
Local network filter not working

### ISSUE THREAD

**Issue by khozmo** [ntop/ntopng#142]
When selecting networks from the hosts menu I get "no results found". If I select hosts and then hosts I will get a list of all the flows with the correct IPs marked as local.

I am using the -f switch on nprobe to limit the traffic that is sampled and in the ntopng config I am using the -m switch to denote which networks are local. I was using this successfully about 3 weeks ago. 

I have since purchased licenses and upgraded to the latest version of both pieces of software.

ntopng Version	2.0.150831 - Professional Edition
nProbe v.7.2.150831 (r4480)

**Comment by lmangani** [comment]
@khozmo which OS are you using?

**Comment by khozmo** [comment]
I am using Ubuntu 14.04. Everything is fully updated.

**Comment by khozmo** [comment]
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

**Comment by mjgehrmann** [comment]
I have a similar experience on Ubuntu 12.04 ntopng v2.0.150908
It worked when originally installed on v2.0.150802

I can verify rrd are being created and command line outputs no errors.

**Comment by lucaderi** [comment]
@khozmo @mjgehrmann Can you please report the exact command line you are using?

**Comment by mjgehrmann** [comment]
Here is my conf file:

# PID Path
-G=/var/tmp/ntopng.pid
# Data dir
-d=/opt/ntopng-data
# Run as Daemon
-e=
# Interface
-i=tcp://127.0.0.1:5556
# Server port
-w=3000
# Local Networks
-m="172.22.0.0/16,172.20.0.0/16,172.28.0.0/16,172.32.0.0/17,192.168.32.0/19,172.18.0.0/21,172.19.0.0/17,172.18.16.0/2
1,172.18.32.0/19"
# DNS Mode
-d=1
# Memory Tuning Flows/Hosts
-S=local
-X=10000
-x=5000

**Comment by simonemainardi** [comment]
local networks list (option -m) was not correctly hygenized. Trailing " for options was not filtered out. Merge request should address this issue.
