### ISSUE TITLE
Feature request: search by AS in Historical Data Explorer

### ISSUE THREAD

**Issue by qm2k** [ntop/ntopng#1420]
I.e. when I'm seeing 46489 [Twitch Interactive Inc.] on top of Traffic Report I'd like to find corresponding flows but /lua/hosts_stats.lua?asn=46489 produces nothing (probably because data were already purged from memory) and there's no option to input AS in Historical Data Explorer so finding corresponding hosts is very hard.

(One would think that search by Application Protocol could work in this particular case, but it didn't, probably because protocol was not recognized or was different.)

**Comment by simonemainardi** [comment]
did you know that you can use subnets in the historical data explorer SRC/DST host? You can specify the subnet corresponding to the AS of interest.

**Comment by qm2k** [comment]
Technically yes, but as far as I understand single AS can have many subnets, and finding/checking them all would require significant effort on top of no way to see whole picture...

**Comment by simonemainardi** [comment]
Searching historical flows by autonomous system would require adding an extra column and index on the database. This is something we would like to avoid as we believe the database has already too many columns and performance may very easily be affected by extra database indices.

As a working solution to address this issue I suggest you to create traffic profiles matching autonomous systems IP ranges. Traffic profiles are written and indexed so you will be able to search them in the historical data explorer using the "profile name" field:
![image](https://user-images.githubusercontent.com/3397663/30175412-b9f5cbc2-93fe-11e7-82b6-2bc368b318ad.png)

**Comment by qm2k** [comment]
Looks like traffic profile is totally valid solution as long as there's an easy way to create traffic profiles matching autonomous systems IP ranges. Will check this possibility next time. Hope that newly created traffic profile applies to earlier recorded data too.
