### ISSUE TITLE
login.lua "graph_zoom"  parameter error: Missing validation

### ISSUE THREAD

**Issue by atbunds** [ntop/ntopng#1421]
Hello,

done an upgrade to ntopng 3.1.170901-3176 today, but ntopng (Small Business licence) does not restart anymore.

Browser shows the message:

Script "/usr/share/ntopng/scripts/lua/login.lua" returned an error:
/usr/share/ntopng/scripts/lua/modules/http_lint.lua:1026: [LINT] _GET["graph_zoom"] = "3h" parameter error: Missing validation

Log on Centos  machine

# cat ntopng.log
01/Sep/2017 10:38:33 [Trace.cpp:114] Logging into /home/ntopng/ntopng.log
01/Sep/2017 10:38:33 [Ntop.cpp:1415] Setting local networks to xxxxx
01/Sep/2017 10:38:33 [Redis.cpp:109] Successfully connected to redis 127.0.0.1:6379@0
01/Sep/2017 10:38:33 [NtopPro.cpp:181] [LICENSE] Reading license from Redis
01/Sep/2017 10:38:33 [NtopPro.cpp:118] [LICENSE] xxxxxxx: unable to validate Enterprise license [License mismatch error]
01/Sep/2017 10:38:33 [NtopPro.cpp:121] [LICENSE] xxxxxxx: found valid Professional license
01/Sep/2017 10:38:35 [Ntop.cpp:1389] Parent process is exiting (this is normal)
01/Sep/2017 10:38:37 [NetworkInterface.cpp:241] Executing ethtool -K enp3s0 gro off gso off tso off
01/Sep/2017 10:38:37 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.6.7.0 interface enp3s0...
01/Sep/2017 10:38:37 [Ntop.cpp:1541] Registered interface enp3s0 [id: 0]
01/Sep/2017 10:38:38 [NetworkInterface.cpp:241] Executing ethtool -K enp2s0 gro off gso off tso off
01/Sep/2017 10:38:38 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.6.7.0 interface enp2s0...
01/Sep/2017 10:38:38 [Ntop.cpp:1541] Registered interface enp2s0 [id: 1]
01/Sep/2017 10:38:39 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.6.7.0 interface lo...
01/Sep/2017 10:38:39 [Ntop.cpp:1541] Registered interface lo [id: 2]
01/Sep/2017 10:38:39 [main.cpp:264] PID stored in file /var/run/ntopng.pid
01/Sep/2017 10:38:39 [HTTPserver.cpp:797] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
01/Sep/2017 10:38:39 [Utils.cpp:427] User changed to ntopng
01/Sep/2017 10:38:39 [HTTPserver.cpp:851] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
01/Sep/2017 10:38:39 [HTTPserver.cpp:854] HTTP server listening on port(s) 3000
01/Sep/2017 10:38:39 [main.cpp:332] Working directory: /home/ntopng
01/Sep/2017 10:38:39 [main.cpp:334] Scripts/HTML pages directory: /usr/share/ntopng
01/Sep/2017 10:38:39 [Ntop.cpp:338] Welcome to ntopng x86_64 v.3.1.170901 - (C) 1998-17 ntop.org
01/Sep/2017 10:38:39 [Ntop.cpp:343] Built on CentOS Linux release 7.3.1611 (Core)
01/Sep/2017 10:38:39 [NtopPro.cpp:383] [LICENSE] System Id:     xxxxxxx
01/Sep/2017 10:38:39 [NtopPro.cpp:384] [LICENSE] Edition:       Professional
01/Sep/2017 10:38:39 [NtopPro.cpp:385] [LICENSE] License Type:  Permanent License
01/Sep/2017 10:38:39 [NtopPro.cpp:388] [LICENSE] License:       xxxxxxx
01/Sep/2017 10:38:39 [NtopPro.cpp:398] [LICENSE] Maintenance:   Until Wed Dec  6 12:57:50 2017 [96 days left]
01/Sep/2017 10:38:39 [Ntop.cpp:615] Adding 127.0.0.1/32 as IPv4 interface address for lo
01/Sep/2017 10:38:39 [Ntop.cpp:623] Adding 127.0.0.0/8 as IPv4 local network for lo
01/Sep/2017 10:38:39 [Ntop.cpp:615] Adding 10.2.1.xxx/32 as IPv4 interface address for enp3s0
01/Sep/2017 10:38:39 [Ntop.cpp:623] Adding 10.2.0.0/16 as IPv4 local network for enp3s0
01/Sep/2017 10:38:39 [Ntop.cpp:642] Adding ::1/128 as IPv6 interface address for lo
01/Sep/2017 10:38:39 [Ntop.cpp:651] Adding ::1/128 as IPv6 local network for lo
01/Sep/2017 10:38:39 [Ntop.cpp:642] Adding fe80::606d:xxx:xxx:xxx/128 as IPv6 interface address for enp3s0
01/Sep/2017 10:38:39 [Ntop.cpp:651] Adding fe80::606d:xxx:xxx:xxx/64 as IPv6 local network for enp3s0
01/Sep/2017 10:38:39 [PeriodicActivities.cpp:50] Started periodic activities loop...
01/Sep/2017 10:38:39 [NetworkInterface.cpp:2241] Started packet polling on interface enp3s0 [id: 0]...
01/Sep/2017 10:38:39 [NetworkInterface.cpp:2241] Started packet polling on interface enp2s0 [id: 1]...
01/Sep/2017 10:38:39 [NetworkInterface.cpp:2241] Started packet polling on interface lo [id: 2]...
01/Sep/2017 10:39:40 [Lua.cpp:6663] WARNING: Script failure [/usr/share/ntopng/scripts/lua/login.lua][/usr/share/ntopng/scripts/lua/modules/http_lint.lua:1026: [LINT] _GET["graph_zoom"] = "3h" parameter error: Missing validation]
01/Sep/2017 10:40:28 [Lua.cpp:6663] WARNING: Script failure [/usr/share/ntopng/scripts/lua/login.lua][/usr/share/ntopng/scripts/lua/modules/http_lint.lua:1026: [LINT] _GET["graph_zoom"] = "3h" parameter error: Missing validation]

yum list installed | grep ntop
ntopng.x86_64                        3.1.170901-3176                @ntop
ntopng-data.noarch                   3.1.170901-3176                @ntop-noarch
pfring.x86_64                        6.7.0-1397                     @ntop
pfring-dkms.noarch                   6.7.0-1397                     @ntop-noarch

Does anybody know about this behavior and how to fix it ?

Kind regards
Andreas

**Comment by simonemainardi** [comment]
maybe some old, no longer used parameter has remained in the url login page. Can you please check? Make sure the login page url does not contain anything after login.lua

**Comment by atbunds** [comment]
Hello Simone,
thank's for the quick response. You are right, my bookmarks contained some
stuff from the past. After opening the URL with the defaults the site
opened as usual. Please close the ticket as resolved.

Thank you a lot and have a nice weekend!

Kind regards
Andreas

**Comment by simonemainardi** [comment]
thanks for reporting :)
