### ISSUE TITLE
Ntopng high cpu usage without any traffic

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [ntop/ntopng#1422]
Ntopng permanently reload and reinterpret  lua scripts in endless loop. 
Due to it. After you start ntopng even without any flows you constantly see 10 -20 % CPU usage by ntopng process.
As you see in extraction below ntopng constantly search , load , interpretate  and execute  lua scripts again and again. Basically i think it is program design error. 
Why just not load it once and reload it if needed instead of every second ? Basically with such design you guys completely loose all speed of lua and it work in such conditions much slower than python.

```
[pid 14062] open("/usr/share/ntopng/scripts/lua/modules/i18n.plural.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 14062] open("/usr/share/ntopng/pro/scripts/callbacks/i18n.plural.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 14062] open("/usr/share/ntopng/scripts/lua/modules/i18n.plural.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 14062] open("./i18n.plural.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 14062] open("/usr/local/share/luajit-2.0.3/i18n.plural.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 14062] open("/usr/local/share/lua/5.1/i18n.plural.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 14062] open("/usr/local/share/lua/5.1/i18n.plural.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 14062] open("/usr/share/ntopng/scripts/lua/modules/i18n/plural/init.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 14062] open("/usr/share/ntopng/pro/scripts/callbacks/i18n/plural.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 14062] open("/usr/share/ntopng/scripts/lua/modules/i18n/plural.lua", O_RDONLY) = 21
[pid 14062] close(21)                   = 0
[pid 14062] open("/usr/share/ntopng/scripts/lua/modules/i18n/plural.lua", O_RDONLY) = 21
[pid 14062] fstat(21, {st_mode=S_IFREG|0644, st_size=7309, ...}) = 0
[pid 14062] read(21, "local plural = {}\nlocal defaultF"..., 8192) = 7309
[pid 14062] read(21, "", 4096)          = 0
[pid 14062] close(21)                   = 0
[pid 14062] mmap(NULL, 131072, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_32BIT, -1, 0) = 0x41a66000
[pid 14062] mmap(0x55bb43da0000, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x55bb43da0000
[pid 14062] mprotect(0x55bb43da0000, 65536, PROT_READ|PROT_EXEC) = 0
[pid 14062] mprotect(0x55bb43da0000, 65536, PROT_READ|PROT_WRITE) = 0
[pid 14062] mprotect(0x55bb43da0000, 65536, PROT_READ|PROT_EXEC) = 0
[pid 14062] open("/usr/share/ntopng/scripts/lua/modules/i18n.interpolate.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 14062] open("/usr/share/ntopng/pro/scripts/callbacks/i18n.interpolate.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 14062] open("/usr/share/ntopng/scripts/lua/modules/i18n.interpolate.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 14062] open("./i18n.interpolate.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 14062] open("/usr/local/share/luajit-2.0.3/i18n.interpolate.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 14062] open("/usr/local/share/lua/5.1/i18n.interpolate.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 14062] open("/usr/local/share/lua/5.1/i18n.interpolate.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 14062] open("/usr/share/ntopng/scripts/lua/modules/i18n/interpolate/init.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 14062] open("/usr/share/ntopng/pro/scripts/callbacks/i18n/interpolate.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid 14062] open("/usr/share/ntopng/scripts/lua/modules/i18n/interpolate.lua", O_RDONLY) = 21
[pid 14062] close(21)                   = 0
[pid 14062] open("/usr/share/ntopng/scripts/lua/modules/i18n/interpolate.lua", O_RDONLY) = 21
[pid 14062] fstat(21, {st_mode=S_IFREG|0644, st_size=985, ...}) = 0
[pid 14062] read(21, "local unpack = unpack or table.u"..., 8192) = 985
[pid 14062] read(21, "", 4096)          = 0
[pid 14062] close(21)                   = 0
```

**Comment by lucaderi** [comment]
@jpVm5jYYRE1VIKL In essence each callback lua file is executed in an interpreter that starts/ends with the script. This issue is more evident with second.lua that is started every second. We could avoid restarting the interpreter to optimise the performance (as we do in nProbe) but then we have to implement the script reload (thing that is not currently necessary). Of course it you open the browser more lua interpreters will be spawn. Did you run your test with/without a browser open on ntopng?

**Comment by jpVm5jYYRE1VIKL** [comment]
Yes. Such behavior constant even without browser pointing to ntopng. I even tried already to move all files to RAM disk but because lua every time reinterpret scripts not so much changed. At least decreases io.
You can easy see such behavior yourself with strace -f -p <nptopngpid>. It is really mess to implement it like it is done now. Such kind behavior really HIT over ntopng which installed ESXI or any another virtual environments with resource planing. For example on current server IDLE vm with ntopng eat 2-5 times more CPU resources than any another vm from 14 installed.
Beside this due to such style of work with lua persist race condition possibility during query nprobe. Especially if nprobe not reachable some minutes. In this case ntopng loops itself and completely hang. Such race condition hit ntopng really fast with one vcpu. Because ntopng forced to divide virtual cpu between another processes in system. With 2 vcpu race condition hit much more rare because ntopng completely occupy one core. And almost never free it.
All such things easy and completely recreatable.

**Comment by lucaderi** [comment]
Please do not mix issues. if you have a problem with nProbe please open a separate issue.
Let's go back to the original question. ntopng every second even on an interface with no traffic
1) purges flows and hosts
2) runs second.lua and housekeeping.lua

Of course if you have many network interfaces open, you need to multiply the workload for the number of interfaces, and this can of course contribute to the CPU load

I have made little optimizations to reduce idle CPU usage and now the CPU usage is < 3% (peak). Even without it I have never seen 10-20% as you have reported.

**Comment by jpVm5jYYRE1VIKL** [comment]
It is no problem with Nprobe. It is race conditions and extra cpu load inside NTOPNG. CPU load depend from your point of view. 
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                             
11650 nobody    20   0 1427444 115204  19536 S  11.0  5.6   1035:28 ntopng  
14007 nobody    20   0  493808  16652  11080 S   0.3  0.8  15:40.08 nprobe

You can see that current load 11%. (and this is in 2 cores VM). 
Also you can see that CPU time spent by Ntopng is 1035:28 
For comparison CPU time spent by nprobe is 15:40.08 (70 times less) 
And idle ntopng is ABSOLUTE leader by CPU usage. 
Let me try your fix
