### ISSUE TITLE
problem with interface views

### ISSUE THREAD

**Issue by papage** [ntop/ntopng#1426]
Hi all,

My ntopng has the following config regarding the interfaces:
--interface=zc:ens160@0
--interface=zc:ens160@1
--interface=zc:ens160@2
--interface=zc:ens160@3
--interface=view:zc:ens160@0,zc:ens160@1,zc:ens160@2,zc:ens160@3

When I choose each of the native interfaces, ntopng shows the traffic coming from that interface. But when I choose the aggregated one (the view), ntopng shows zero traffic. It does not aggregate the traffic from the given queues.

Am i doing something wrong or is it bug?

Thank you,
Spiros

PS: My ntopng is 3.1.170902 - Professional Edition

**Comment by simonemainardi** [comment]
I have just tried to reproduce without success. I properly get traffic also from the interface view. Here's a screenshot of the view four interfaces (pfsend, RSS=4, ZC driver ixgbe)

![image](https://user-images.githubusercontent.com/3397663/30062196-8d0819f4-924a-11e7-8c04-3199c715131c.png)


Can you please post the full ntopng logs? What do you get in the dashboard? and in the flows page?

**Comment by papage** [comment]
Here is a screenshot. Everything seems to be like there is zero traffic. 
![ntop-allifs](https://user-images.githubusercontent.com/6276532/30078873-0199ba70-9287-11e7-88eb-c423ce37bffe.jpg)

The only difference, I can see, is that in your case, the view: is in the top of the list, where at my case is at the bottom? did you define it before the actual interfaces?

Cheers,
Sp

The log does not seem to say much:
05/Sep/2017 21:50:05 [main.cpp:40] Ok I am leaving now
05/Sep/2017 21:50:10 [Ntop.cpp:1415] Setting local networks to 55.44.0.0/16,55.44.222.0/24,55.44.32.0/22,55.44.22.0/24
05/Sep/2017 21:50:10 [Redis.cpp:109] Successfully connected to redis 127.0.0.1:6379@0
05/Sep/2017 21:50:10 [NtopPro.cpp:183] [LICENSE] Reading license from /etc/ntopng.license
05/Sep/2017 21:50:10 [NtopPro.cpp:118] [LICENSE] /etc/ntopng.license: unable to validate Enterprise license [License mismatch error]
05/Sep/2017 21:50:10 [NtopPro.cpp:121] [LICENSE] /etc/ntopng.license: found valid Professional license
05/Sep/2017 21:50:11 [ViewInterface.cpp:50] ERROR: Internal Error: NULL interface [view:zc:ens160@0,zc:ens160@1,zc:ens160@2,zc:ens160@3][2]
05/Sep/2017 21:50:11 [ViewInterface.cpp:50] ERROR: Internal Error: NULL interface [view:zc:ens160@0,zc:ens160@1,zc:ens160@2,zc:ens160@3][2]
05/Sep/2017 21:50:11 [ViewInterface.cpp:50] ERROR: Internal Error: NULL interface [view:zc:ens160@0,zc:ens160@1,zc:ens160@2,zc:ens160@3][2]
05/Sep/2017 21:50:11 [ViewInterface.cpp:50] ERROR: Internal Error: NULL interface [view:zc:ens160@0,zc:ens160@1,zc:ens160@2,zc:ens160@3][2]
05/Sep/2017 21:50:11 [Ntop.cpp:1541] Registered interface view:zc:ens160@0,zc:ens160@1,zc:ens160@2,zc:ens160@3 [id: 2]
05/Sep/2017 21:50:12 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.6.7.0 interface zc:ens160@0...
05/Sep/2017 21:50:12 [PF_RINGInterface.cpp:72] WARNING: Unable to set packet capture direction
05/Sep/2017 21:50:13 [Ntop.cpp:1541] Registered interface zc:ens160@0 [id: 4]
05/Sep/2017 21:50:14 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.6.7.0 interface zc:ens160@1...
05/Sep/2017 21:50:14 [PF_RINGInterface.cpp:72] WARNING: Unable to set packet capture direction
05/Sep/2017 21:50:15 [Ntop.cpp:1541] Registered interface zc:ens160@1 [id: 5]
05/Sep/2017 21:50:16 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.6.7.0 interface zc:ens160@2...
05/Sep/2017 21:50:16 [PF_RINGInterface.cpp:72] WARNING: Unable to set packet capture direction
05/Sep/2017 21:50:17 [Ntop.cpp:1541] Registered interface zc:ens160@2 [id: 6]
05/Sep/2017 21:50:18 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.6.7.0 interface zc:ens160@3...
05/Sep/2017 21:50:18 [PF_RINGInterface.cpp:72] WARNING: Unable to set packet capture direction
05/Sep/2017 21:50:18 [Ntop.cpp:1541] Registered interface zc:ens160@3 [id: 7]
05/Sep/2017 21:50:18 [main.cpp:264] PID stored in file /var/run/ntopng.pid
05/Sep/2017 21:50:19 [HTTPserver.cpp:797] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
05/Sep/2017 21:50:19 [Utils.cpp:427] User changed to nobody
05/Sep/2017 21:50:19 [HTTPserver.cpp:851] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
05/Sep/2017 21:50:19 [HTTPserver.cpp:854] HTTP server listening on port(s) 3000
05/Sep/2017 21:50:19 [main.cpp:332] Working directory: /mnt/data/ntopng
05/Sep/2017 21:50:19 [main.cpp:334] Scripts/HTML pages directory: /usr/share/ntopng
05/Sep/2017 21:50:19 [Ntop.cpp:338] Welcome to ntopng x86_64 v.3.1.170902 - (C) 1998-17 ntop.org
05/Sep/2017 21:50:19 [Ntop.cpp:343] Built on CentOS Linux release 7.3.1611 (Core) 
05/Sep/2017 21:50:19 [NtopPro.cpp:383] [LICENSE] System Id:     CC5FC19F610621EF
05/Sep/2017 21:50:19 [NtopPro.cpp:384] [LICENSE] Edition:       Professional
05/Sep/2017 21:50:19 [NtopPro.cpp:385] [LICENSE] License Type:  Permanent License
05/Sep/2017 21:50:19 [NtopPro.cpp:388] [LICENSE] License:       18D4C9880A0DFF34DF0AD7562D22183915085851333AC6D217
05/Sep/2017 21:50:19 [NtopPro.cpp:398] [LICENSE] Maintenance:   Until Sat Oct 21 14:25:33 2017 [45 days left]
05/Sep/2017 21:50:19 [Ntop.cpp:615] Adding 55.44.33.18/32 as IPv4 interface address for view:zc:ens160@0,zc:ens160@1,zc:ens160@2,zc:ens160@3
05/Sep/2017 21:50:19 [Ntop.cpp:623] Adding 55.44.33.0/27 as IPv4 local network for view:zc:ens160@0,zc:ens160@1,zc:ens160@2,zc:ens160@3
05/Sep/2017 21:50:19 [Ntop.cpp:642] Adding fe80::92e2:baff:fe5c:bb9d/128 as IPv6 interface address for view:zc:ens160@0,zc:ens160@1,zc:ens160@2,zc:ens160@3
05/Sep/2017 21:50:19 [Ntop.cpp:651] Adding fe80::92e2:baff:fe5c:bb9d/64 as IPv6 local network for view:zc:ens160@0,zc:ens160@1,zc:ens160@2,zc:ens160@3
05/Sep/2017 21:50:19 [PeriodicActivities.cpp:50] Started periodic activities loop...
05/Sep/2017 21:50:21 [NetworkInterface.cpp:2237] Setting affinity of interface zc:ens160@0 to core 1
05/Sep/2017 21:50:21 [NetworkInterface.cpp:2241] Started packet polling on interface zc:ens160@0 [id: 4]...
05/Sep/2017 21:50:21 [NetworkInterface.cpp:2237] Setting affinity of interface zc:ens160@1 to core 2
05/Sep/2017 21:50:21 [NetworkInterface.cpp:2241] Started packet polling on interface zc:ens160@1 [id: 5]...
05/Sep/2017 21:50:21 [NetworkInterface.cpp:2237] Setting affinity of interface zc:ens160@2 to core 3
05/Sep/2017 21:50:21 [NetworkInterface.cpp:2241] Started packet polling on interface zc:ens160@2 [id: 6]...
05/Sep/2017 21:50:21 [NetworkInterface.cpp:2237] Setting affinity of interface zc:ens160@3 to core 4
05/Sep/2017 21:50:21 [NetworkInterface.cpp:2241] Started packet polling on interface zc:ens160@3 [id: 7]...
05/Sep/2017 21:59:50 [Lua.cpp:5629] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[161] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.

**Comment by papage** [comment]
Hi  again,

I just tried:
--interface=view:zc:ens160@1,zc:ens160@0,zc:ens160@2,zc:ens160@3
instead of 
--interface=view:zc:ens160@0,zc:ens160@1,zc:ens160@2,zc:ens160@3
and it works!... (the @0 queue goes second in line)
If I change back the order to 0,1,2,3 it doesn't work.

Go figure :-)

Sp

**Comment by simonemainardi** [comment]
Thanks for reporting. That was actually a bit tricky.  The view was trying to repeatedly add itself the its sub interfaces due to the use of `strstr` rather than `strncmp`. Swapping the @0 with @1 determined the assignment of a new id to the interface view. As newly assigned ids are greater than every other existing id, the new interface view was able to find its sub-interfaces correctly.

Anyway, the commit has fixed the issue now.
