### ISSUE TITLE
nProbe License Issue

### ISSUE THREAD

**Issue by qualitycrm** [ntop/ntopng#1427]
I am using nProbe version 8.0.170809. I tried to export netflow data to Manage Engine Server. When i enter "nprobe -i eth0 -n my_exporter_ip:13310" at my ntopng server end, it give me error  below

05/Sep/2017 16:01:57 [plugin.c:176] No plugins found in ./plugins
05/Sep/2017 16:01:57 [plugin.c:184] Loading 24 plugins [.so] from /usr/local/lib                                                                             /nprobe/plugins
05/Sep/2017 16:01:57 [nprobe.c:3688] ERROR: Invalid nProbe license (/etc/nprobe.                                                                             license) [Missing license file]
05/Sep/2017 16:01:57 [nprobe.c:3695] ERROR: ************************************                                                                             *****************
05/Sep/2017 16:01:57 [nprobe.c:3696] ERROR: **                                                                                                                              **
05/Sep/2017 16:01:57 [nprobe.c:3697] ERROR: **  Switching to DEMO MODE (missing                                                                              valid license) **
05/Sep/2017 16:01:57 [nprobe.c:3698] ERROR: **                                                                                                                              **
05/Sep/2017 16:01:57 [nprobe.c:3699] ERROR: **  Purchase your nProbe license at                                                                                             **
05/Sep/2017 16:01:57 [nprobe.c:3700] ERROR: **       https://shop.ntop.org/                                                                                                 **
05/Sep/2017 16:01:57 [nprobe.c:3701] ERROR: **                                                                                                                              **
05/Sep/2017 16:01:57 [nprobe.c:3702] ERROR: ************************************  

I think it is license related issue & as per my knowledge nProbe is open-source. So how could I activate nProbe license?  Please help...

**Comment by simonemainardi** [comment]
nProbe is not opensource, you may want to get a license just by following the link shown in the error.
