### ISSUE TITLE
Hosts display - Add total traffic usage by day week or month

### ISSUE THREAD

**Issue by thegeodave** [ntop/ntopng#1428]
My only purpose for using NTOPNG is getting total daily/weekly or monthly usage by ALL Local Hosts. Not just the top ten. "Seen Since" does not help in displaying or reporting this total. Mainly because the data totals reset after program updates or system restarts. "Seen Since" resetting the totals renders the Hosts display useless. Adding a column by which I could choose day/week/month (regardless of "Seen Since")  and sort by total traffic for the day/week/month's would solve this usability issue. I'm hoping other NTOPNG users would like to see the same feature added.   I know already that I can select individual local hosts and, after a few clicks, get a report total for the day/week/month/year etc but it's a VERY time consuming and tedious process because I have hundreds and hundreds of local hosts. Having the totals on one display reporting it all in the Hosts/Hosts display summary would make my life and wife happy.

**Comment by simonemainardi** [comment]
At least three options are available.

1. As you've pointed out, you can visit each host and select the traffic report page to obtain exactly what you are looking for as

![image](https://user-images.githubusercontent.com/3397663/43589704-91ae910c-966f-11e8-9fa1-e0aec95305ee.png)

2. If is is more convenient to have all the hosts listed in a single page you can use the historical data explorer, select a period of interest, and visit the Talkers tab

![image](https://user-images.githubusercontent.com/3397663/43589847-ded5cafe-966f-11e8-8b24-08fc8d2cbd85.png)

3. You can also use the traffic report but this will give you only the top talkers and not all hosts
![image](https://user-images.githubusercontent.com/3397663/43589902-fe0b33d2-966f-11e8-89d9-479fa4fec246.png)
