### ISSUE TITLE
Implement per-interface RRD generation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1429]
From the preferences it is possible to enable RRD generation, however this is a general setting and for some network interfaces we might not be interested in generating RRDs.
It is requested to implement in the interface preferences, an item for disabling (for the selected interface only) RRD generation in case the general RRD generation (specified in ntopng preferences) is enabled.

**Comment by simonemainardi** [comment]
Implemented

![image](https://user-images.githubusercontent.com/3397663/30116027-ad347ce0-931c-11e7-8908-1fe059509100.png)
