### ISSUE TITLE
Dashboard crashes browser tab or process due to memory leaks

### ISSUE THREAD

**Issue by qm2k** [ntop/ntopng#1430]
I've long known that dashboard left to itself crashes tab (in Chromium) or browser (in Firefox) process, and always suspected memory leaks. Today I accidentally left browser console open in Chromium and found tab on "paused before potential out-of-memory crash" state, confirming my suspicions. It took about a day. Didn't take the screenshot since I tried to take heap snapshot using Chromium developers tools and my whole system ran out-of-memory and the process had to be killed. I can help with debugging the issue if necessary, but you can probably reproduce it yourself easily.

**Comment by simonemainardi** [comment]
are you able to investigate using the browser profiler and suggest the possible source of the leak?

**Comment by qm2k** [comment]
I need it working so I will try when I have time, but any ideas on where to look would be very appreciated since I'm not familiar with the code and cannot really make changes by other means than live-patching.

One particular problem I had tinkering with Javascript of this page is missing return values from setInterval calls. Can you please make version that assigns them all to some variables?

**Comment by simonemainardi** [comment]
This issue is really driving me crazy. I spent hours with the chrome debugger trying to compare allocations between consecutive memory allocations. I am still not sure the issue is actually in ntopng. nvd3 issues pointed out several memory leaks in the charts. So I tried to perform an un update of the library from 1.8.4 to 1.8.6. A new build is in progress. Please wait a couple of hours and report...

**Comment by simonemainardi** [comment]
@qm2k how is it going after the latest update?

**Comment by qm2k** [comment]
Sorry for disappearing, server that's running ntopng among other things developed hardware problems so I had to switch my attention temporarily. I'll update to latest version today and start testing.

**Comment by simonemainardi** [comment]
I have been monitoring dashboards on several installations and didn't notice any significant increase in the memory used.

Browser heap snapshots are now always below 30MB...

Hope it is solved.

**Comment by qm2k** [comment]
v.3.1.170912. RSS of the whole Chromium rendering process is a bit worrying:
![screenshot from 2017-09-13 09 45 03](https://user-images.githubusercontent.com/13719792/30363297-47bc963a-9868-11e7-9325-94bb554c74b5.png)
Probably it will stop growing after some time, will see. Heap snapshot is indeed 30MB, but I'm not sure it correctly reflects all overheads (e.g. of many small objects).

If you think third-party chart libraries are to blame, did you consider just recreating chart objects from scratch periodically?

**Comment by qm2k** [comment]
Ok, it stabilized:
![screenshot from 2017-09-14 08 23 37](https://user-images.githubusercontent.com/13719792/30413339-0e6d1a30-9926-11e7-83a5-bba1ad87cc6c.png)
(a huge spike is me opening developers tools).

P.S. Heap snapshot is 35.9MB.

**Comment by simonemainardi** [comment]
I think the sawtooth behaviour charted is normal and is due to the periodic garbage collections. It is important to observe that is stabilizes after a while.

What about the dashboard? Does it continue to crash?

**Comment by qm2k** [comment]
> What about the dashboard? Does it continue to crash?

It obviously didn't crash during 2 days of measurements which is very good, but to be sure I'd need to wait more. I started another instance in Firefox since it's more important for me and it crashed harder, will see.

**Comment by qm2k** [comment]
It worked for 5 days in Chromium and died for different reason (expiration of certificate exception), so I guess the leak issue is fixed.

**Comment by simonemainardi** [comment]
allright, thanks for reporting.
