### ISSUE TITLE
Dashboard Realtime Traffic charts load empty, with the wrong scale

### ISSUE THREAD

**Issue by qm2k** [ntop/ntopng#1431]
`Realtime Traffic` charts load empty after each page reload. Moreover, they are prefilled with tick space of one second even if tick space for actual values is different, creating uneven axis when actual values are added to chart:
![screenshot from 2017-09-06 19 14 15 cropped cropped](https://user-images.githubusercontent.com/13719792/30124290-5d47f3c6-933d-11e7-8704-106e6cebbf95.png)
(Compare time lengths 18:51:28..18:51:43 and 18:57:54..19:12:54.)

It would actually be very nice to prefill them with actual historical values, but at the very least every-ten-minutes values from the `Last Day View` charts can be reused. The following code copies values from `Last Day View` to `Realtime Traffic`:
```
var time_step = 60;
var point_count = 61;
for (var type_index in topapps_lastday_data) {
    var lastday_values = topapps_lastday_data[type_index].values;
    var realtime_values = topapps_realtime_data[type_index].values;
    var lastday_index = lastday_values.length - 1;
    if (lastday_index < 0)
        continue;
    time_value = realtime_values[realtime_values.length - 1][0];
    realtime_values.length = 0;
    for (var point_index = 0; point_index < point_count; ++point_index, time_value -= time_step) {
        while (lastday_index > 0 && time_value <= lastday_values[lastday_index - 1][0])
            --lastday_index;
        realtime_values.push([time_value, lastday_values[lastday_index][1]]);
    }
    realtime_values.reverse();
}
for (var type_index in ifaces_lastday_data) {
    var lastday_values = ifaces_lastday_data[type_index].values;
    var realtime_values = ifaces_realtime_data[type_index].values;
    var lastday_index = lastday_values.length - 1;
    if (lastday_index < 0)
        continue;
    time_value = realtime_values[realtime_values.length - 1][0];
    realtime_values.length = 0;
    for (var point_index = 0; point_index < point_count; ++point_index, time_value -= time_step) {
        while (lastday_index > 0 && time_value <= lastday_values[lastday_index - 1][0])
            --lastday_index;
        realtime_values.push([time_value, lastday_values[lastday_index][1]]);
    }
    realtime_values.reverse();
}
```
(Looks like it's proprietary part so I cannot just send pull request.)

Here's how the result looks:
![screenshot from 2017-09-06 19 52 27 cropped cropped](https://user-images.githubusercontent.com/13719792/30124444-def4c0ac-933d-11e7-846e-74366763824a.png)
Note that axis is more even now and there are values to look at from the very beginning. (Smoother approximation is left as an exercise to the reader.)

**Comment by simonemainardi** [comment]
Thanks for reporting. Axes initialization is now fixed and will be included in  the next build.

As per the pre-fill of the charts, I can't currently accept the patch as-is. Application top traffic is stored every minute so the realtime chart would look almost flat -- note that the default refresh rate is set to 3 seconds, yielding just 3 different levels in the whole chart. This could be confusing for the user that will then start seeing many more variations in the same chart due to the periodic refreshes.

**Comment by qm2k** [comment]
Can I then feature request loading true data from server?
