### ISSUE TITLE
How to activate nProbe Trial license

### ISSUE THREAD

**Issue by qualitycrm** [ntop/ntopng#1432]
I have received trial license from Ntopng Tech team. I have to activate this license, How to activate it?

Any steps.

**Comment by simonemainardi** [comment]
Fill the form at https://shop.ntop.org/mklicense/ to get a `license key string`.

Create a file named `nprobe.license` and store `license key string` on it.

Such file must be placed:
- [Unix] Under /etc (i.e. echo  `license key string` > /etc/nprobe.license)
- [Windows] On the same directory where nprobe has been installed (i.e. c:\Program Files\Probe\nprobe.license)
--
