### ISSUE TITLE
Traffic Report not Showing "Top Local Hosts" and other Data for One Week or More

### ISSUE THREAD

**Issue by dgettis** [ntop/ntopng#1433]
This seems to be a recurring problem - see bug #680 and #813, which Ntop claims to have fixed, but in reality persists.  If I generate a taffic report for longer than one day (i.e., one week or more), none of the data below "Application Breakdown" is displayed - i.e., I am missing Top Countries, Top Local Hosts, Top Remote Hosts, and Top ASN. My interest lies particularly in "Top Local Hosts" - without that data over a longer time period, Ntopng is not very useful to me. 

The error I am getting is the same as others have reported: "07/Sep/2017 08:29:53 [Lua.cpp:6543] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/get_from_top_talkers_db.lua][not enough memory]"

In reality, I have plenty of memory available. I did try increasing the buffers in my.cnf, but that didn't help. 

I'm running 3.1.170626 - Pro [Small Business Edition] Edition on Debian 8.2 [x86_64][Debian GNU/Linux 8.2 (jessie)] - 64 bit. 

There are about 25 local hosts on our network.

**Comment by simonemainardi** [comment]
The error you get "not_enough_memory" means the there's no more room available in the Lua VM. It is not the overall system memory.

To try and mitigate this error, I have added a preference that allows you to control the aggressiveness of an heuristic used to compute the top-k in the report.

![image](https://user-images.githubusercontent.com/3397663/30174744-634cfdba-93fc-11e7-859d-48abaab040f7.png)

You should try and set it to "Less Accurate" or even "Aggressive" if you keep getting errors when generating reports over long periods of time.

A new build will be available tomorrow. Please, give it a try and report.

**Comment by thegeodave** [comment]
My NTOPNG is at the latest stable version and I see the same issue. I personally would like to see more than just the top 10. Change it to the top 100! Regardless, in the Hosts display (display local hosts only report) Maybe a solution to my issue #1428 would help you out and hopefully many others also.

**Comment by simonemainardi** [comment]
@dgettis did you try the latest version with the tuning of the Top-K Heuristic?

**Comment by dgettis** [comment]
Thanks so much, simonemainardi! I will have a chance to try it out tomorrow, and then I will report back.

**Comment by dgettis** [comment]
simeonemainardi, I tried the new build, and it works great!! Thank you!!

**Comment by simonemainardi** [comment]
wow, thanks for reporting!
