### ISSUE TITLE
Feature request: store dashboard realtime data on server and preload it with the page

### ISSUE THREAD

**Issue by qm2k** [ntop/ntopng#1434]
There're many reasons for user to refresh dashboard page including version updates, browser/javascript instability and change of monitored interface/other settings. Unfortunately, in each case realtime data gets lost since it is apparently only stored in browser window and replaced with zeroes on page load. It is especially painful if Realtime Stats Refresh Rate is long since lost period is large. It would be nice to keep this information on server and load actual data with the page, not zeroes.

Followed up from #1431.

**Comment by simonemainardi** [comment]
Currently, we are considering a complete rework of the dashboard. So we will keep this in mind in the new design but we cannot accomodate the request on the current implementation.
