### ISSUE TITLE
MySQL reconnections

### ISSUE THREAD

**Issue by matteoluc** [ntop/ntopng#1435]
At least 1 or 2 times a day, ntopng logs off and immediately after reconnects to mysql software.
Is such behavior normal or is it a symptom of a problem?

Yesterday, for example, it happened at midnight as you can see from the attached screenshoot

<img width="685" alt="ultima disconnessione" src="https://user-images.githubusercontent.com/29771833/30240604-b46474da-9573-11e7-8364-0cff0732aa70.png">

The problem might be related to the fact that about 10 days ago I had a problem with mysql indexes?
In that case I solved it doing a "repair" on a precise partition of the flowsv4 table.

**Comment by simonemainardi** [comment]
This is normal and is due to the MySQL connection timeouts. Please see this post for a detailed discussion: https://github.com/ntop/ntopng/issues/733#issuecomment-246271728
