### ISSUE TITLE
Missing AJAX update on lua/mac_details.lua 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1437]
All counters are not refreshed via AJAX

**Comment by simonemainardi** [comment]
Implemented.

Also reworked the layout and added a configuration page to be consistent with other pages:

![image](https://user-images.githubusercontent.com/3397663/30286995-cdeb3d88-9723-11e7-8cc9-3af8ff1ea083.png)

![image](https://user-images.githubusercontent.com/3397663/30287026-e824ca2a-9723-11e7-9fd6-79ba610decc3.png)
