### ISSUE TITLE
Change Autonomous Systems reference site

### ISSUE THREAD

**Issue by Azerothian** [ntop/ntopng#1439]
Hi,

can we change the linking site on the Autonomous System from robtex to peeringdb, as it is a cleaner website with more useful information.

http://as.robtex.com/as54994.html vs https://as54994.peeringdb.com

Thanks

**Comment by simonemainardi** [comment]
robtex offers a much wider information with reference to peeringDB. For example, Robtex includes:
- AS membership in AS sets
- registered routes

Whereas peering db just gives you AS points of presence on IXPs and its peers.

**Comment by Azerothian** [comment]
Can we at least queue this up as a configurable item, is it's down to preference in regards to usability with the provided information. e.g. I only need the data from peeringdb as its layout is way more convenient and usable.
