### ISSUE TITLE
dependence on mariadb-5.5.52 library

### ISSUE THREAD

**Issue by matteoluc** [ntop/ntopng#1440]
Trying to install nprobe requires "mariadb-5.5.52-1.el7.x86_64" library, but it has been obsolete from "mysql-community-client-5.6.37-2.el7.x86_64". So I forced the installation and I was able to install it.
But now to update the packages there is the problem of lack of dependence.
How can I fix this problem?

**Comment by simonemainardi** [comment]
which operating system?

**Comment by matteoluc** [comment]
centOS 7

**Comment by simonemainardi** [comment]
is this an nprobe or an ntopng issue? or both?

**Comment by matteoluc** [comment]
only nprobe. But for this reason I can't update all packages.

**Comment by simonemainardi** [comment]
Please respect the community.

Do not randomly cut-paste the same issue across multiple trackers https://github.com/ntop/nProbe/issues/212

![image](https://user-images.githubusercontent.com/3397663/30319759-0604d6f6-97b1-11e7-904d-007b47a9de9b.png)

If it is an nProbe issue (thing that has to be verified) there is NO reason to post it here.
