### ISSUE TITLE
ntopng and elasticsearch export problems

### ISSUE THREAD

**Issue by papage** [ntop/ntopng#1441]
Hi all,

I would like to investigate an issue, when exporting flows to ELK.
I am exporting to a single ELK node and that node is underutilized with a CPU load of about 20% and low IOPs.  I think the problem is that ntopng does not try to push ELK to its limits. It pushes a bunch of flows and then waits until ELK has finished. I can see the ELK thread that ntopng connects to,  reaching an average CPU of about 50% (I guess it is at 100% when ntopng pushes data and at 0% when ELK indexes the data), while the other (indexing) threads are mostly idle.

While it seems rational to do such a thing, I believe it would be much better to have multiple bulk connections in parallel, in order to utilize the ELK cluster performance.

What do you think?

Regards,
Spiros

**Comment by Howard-Chang** [comment]
I have the same problem.
the max speed of the flows collected is about  [1489.5 Flows/sec]
and the ES exported is about only  [350 Flows/sec]
average CPU load is about 60~70% (2core)
average RAM use is about 70% (8G)
and  the drop flows is very seriously.
But when I export to mysql there's no drop flow at all.
I think it may the inefficient manner of  indexing into Elasticsearch .
I have asked the ES engineer,and he replied me these messages:
https://discuss.elastic.co/t/tuning-the-es-performance/105832/33
![image](https://user-images.githubusercontent.com/19474557/32534983-05710598-c493-11e7-8958-4db86fc0ebbd.png)

**Comment by emanuele-f** [comment]
@papage @Howard-Chang I've made some improvements with commit 53d2505edcb2750e1f7d877449470c8d567bdb95 . Please check out the new ntopng 3.3 package (available in one hour) for performance improvements. Please let me know.

**Comment by lucaderi** [comment]
A fix has been applied. If not working please reopen this ticket and report what is not working yet.
