### ISSUE TITLE
ERROR: Unable to start HTTP server (IPv4) on ports 3000启动报错

### ISSUE THREAD

**Issue by SirBlues** [ntop/ntopng#1445]
[root@localhost ntopng]# ntopng 
14/Sep/2017 16:27:10 [Ntop.cpp:1361] Setting local networks to 127.0.0.0/8
14/Sep/2017 16:27:10 [Redis.cpp:109] Successfully connected to redis 127.0.0.1:6379@0
14/Sep/2017 16:27:11 [NetworkInterface.cpp:229] Executing ethtool -K enp1s0f0 gro off gso off tso off
14/Sep/2017 16:27:11 [NetworkInterface.cpp:229] Executing ethtool -K enp1s0f0 gro off gso off tso off
14/Sep/2017 16:27:11 [PcapInterface.cpp:86] Reading packets from interface enp1s0f0...
14/Sep/2017 16:27:11 [Ntop.cpp:1487] Registered interface enp1s0f0 [id: 0]
14/Sep/2017 16:27:12 [NetworkInterface.cpp:229] Executing ethtool -K enp1s0f3 gro off gso off tso off
14/Sep/2017 16:27:12 [NetworkInterface.cpp:229] Executing ethtool -K enp1s0f3 gro off gso off tso off
14/Sep/2017 16:27:12 [PcapInterface.cpp:86] Reading packets from interface enp1s0f3...
14/Sep/2017 16:27:12 [Ntop.cpp:1487] Registered interface enp1s0f3 [id: 1]
14/Sep/2017 16:27:12 [PcapInterface.cpp:86] Reading packets from interface lo...
14/Sep/2017 16:27:12 [Ntop.cpp:1487] Registered interface lo [id: 2]
14/Sep/2017 16:27:13 [NetworkInterface.cpp:229] Executing ethtool -K enp3s0 gro off gso off tso off
14/Sep/2017 16:27:13 [NetworkInterface.cpp:229] Executing ethtool -K enp3s0 gro off gso off tso off
14/Sep/2017 16:27:13 [PcapInterface.cpp:86] Reading packets from interface enp3s0...
14/Sep/2017 16:27:13 [Ntop.cpp:1487] Registered interface enp3s0 [id: 3]
14/Sep/2017 16:27:13 [NetworkInterface.cpp:229] Executing ethtool -K enp1s0f1 gro off gso off tso off
14/Sep/2017 16:27:14 [NetworkInterface.cpp:229] Executing ethtool -K enp1s0f1 gro off gso off tso off
14/Sep/2017 16:27:14 [PcapInterface.cpp:86] Reading packets from interface enp1s0f1...
14/Sep/2017 16:27:14 [Ntop.cpp:1487] Registered interface enp1s0f1 [id: 5]
14/Sep/2017 16:27:14 [NetworkInterface.cpp:229] Executing ethtool -K enp1s0f2 gro off gso off tso off
14/Sep/2017 16:27:14 [NetworkInterface.cpp:229] Executing ethtool -K enp1s0f2 gro off gso off tso off
14/Sep/2017 16:27:14 [PcapInterface.cpp:86] Reading packets from interface enp1s0f2...
14/Sep/2017 16:27:14 [Ntop.cpp:1487] Registered interface enp1s0f2 [id: 6]
14/Sep/2017 16:27:14 [main.cpp:252] PID stored in file /var/run/ntopng.pid
14/Sep/2017 16:27:14 [HTTPserver.cpp:787] HTTPS Disabled: missing SSL certificate /usr/local/share/ntopng/httpdocs/ssl/ntopng-cert.pem
14/Sep/2017 16:27:14 [HTTPserver.cpp:789] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
14/Sep/2017 16:27:14 [HTTPserver.cpp:822] HTTP logs will be stored on /var/tmp/ntopng/ntopng_access.log
14/Sep/2017 16:27:14 [mongoose.c:4515] ERROR: set_ports_option: cannot bind to 3000: Address already in use
14/Sep/2017 16:27:14 [HTTPserver.cpp:835] ERROR: Unable to start HTTP server (IPv4) on ports 3000

**Comment by simonemainardi** [comment]
```
14/Sep/2017 16:27:14 [mongoose.c:4515] ERROR: set_ports_option: cannot bind to 3000: Address already in use
```

means that there's some other process using port 3000.

do a

```
$ netstat -polenta | grep 3000
```

to find who is using port 3000. Very likely there's another instance of ntopng running there. Stop the running instance before trying to run a new instance on the same port.

**Comment by SirBlues** [comment]
@simonemainardi 
[root@localhost ntopng]# netstat -polenta | grep 3000
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN      0          41415      7460/ntopng          off (0.00/0/0)

**Comment by simonemainardi** [comment]
there is another ntopng running... stop it if you want to run another instance on port 3000
