### ISSUE TITLE
Create per-category RRDs

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1448]
Currently RRDs are created per protocol. This might be useful for sysadmins who need to know exactly at protocol level all details, but it has the drawback to create many RRDs and make the GUI complicated as the number of protocols could be high.

It is requested to change ntopng preferences and make them configurable: 
- RRD off
- RRD on per L7 protocol (as today)
- RRD per L7 protocol category

**Comment by simonemainardi** [comment]
Implemented together with a re-organization of preferences. So now it is possible to control both interface and local hosts rrd generation for traffic and Layer-7 (before this commit that was not actually possible and some preferences were also ignored).

![image](https://user-images.githubusercontent.com/3397663/30586471-580607d4-9d30-11e7-8b2a-c9f73ae169c2.png)
