### ISSUE TITLE
Implement Host protocol category view

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1449]
As consequence of #1448 it is requested/lua/host_details.lua?page=ndpi to
- Add a donut chart with protocol categories
- Add counters per protocol category and display them

**Comment by simonemainardi** [comment]
Implemented along with serialization of hosts ndpi categories data

![image](https://user-images.githubusercontent.com/3397663/30593766-fcae8b10-9d4b-11e7-92e8-1fdc3ad5ea79.png)

![image](https://user-images.githubusercontent.com/3397663/30593779-0ab0ed3e-9d4c-11e7-9b32-c112354de0dd.png)
