### ISSUE TITLE
SSL cert replaced after update

### ISSUE THREAD

**Issue by jberthier** [ntop/ntopng#145]
Hi,

I use the stable repo on CentOS 7.

After an update from 2.0.150531-163 to 2.0.150830-212, the SSL cert was replaced under /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem.

The SSL cert signed by a public CA has been replaced by a self signed certicate :
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 17707173995456902324 (0xf5bc84eea73e34b4)
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: C=IT, ST=Some-State, O=Internet Widgits Pty Ltd
        Validity
            Not Before: Jun 15 16:16:12 2015 GMT
            Not After : Jun 14 16:16:12 2016 GMT
        Subject: C=IT, ST=Some-State, O=Internet Widgits Pty Ltd

The new one should be copied under another name like ntopng-cert.pem.rpmsave or whatever.
Could you manage to save existing cert ? 

Thanks

Regards

Jérôme

**Comment by lucaderi** [comment]
Please restore your certificate as the RPM package overwrites any certificate if present. Do you think that  saving your certificate somewhere else (e.g. /etc/ntopng-cert.pem) and ntopng checking that first could be enough for the future. Please advice.

**Comment by jberthier** [comment]
Hi Lucas

Yes I restored my certificate without problem.

An idea could be : 
- store a default certificate under /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem
- store a prefered certificate under /etc/ntopng/ntopng-cert.pem
If the prefered certificate does not exist, ntopng should fallback to the default one.

More useful, add an option to fix the certificate path in ntopng.conf :)

Thanks 

Regards

**Comment by lucaderi** [comment]
The idea is that if you have a certificare installed, the package will not overwrite it.
