### ISSUE TITLE
Implement interface protocol category view

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1450]
Similar to #1449 but for interfaces, i.e. /lua/if_stats.lua?page=ndpi

**Comment by simonemainardi** [comment]
Implemented together with ndpi categories for the interfaces (they were previously missing)

![image](https://user-images.githubusercontent.com/3397663/30602105-e7c6bade-9d63-11e7-9f9b-6b232ee1df52.png)

![image](https://user-images.githubusercontent.com/3397663/30602119-f1761c32-9d63-11e7-8754-d663ee0a4bbd.png)
