### ISSUE TITLE
Add device type in mac reports column

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1451]
As devices have now a device type, it is requested to modify lua/macs_stats.lua collapse the ARP columns into one (i.e. <sent> / < rcvd>) and on the column left empty, put the device type.

**Comment by simonemainardi** [comment]
implemented

![image](https://user-images.githubusercontent.com/3397663/31348370-bce27c06-ad1f-11e7-8868-d6aa28d0e645.png)
