### ISSUE TITLE
Geolocation on private IP address range

### ISSUE THREAD

**Issue by rkriekaard** [ntop/ntopng#1454]
Hi,

Would it be possible to include a method to map private IP address ranges to a (external) public IP address, so geolocation can work? I consider this useful as a lot of monitoring (internet traffic) occurs from the inside of the local network.

Kind regards,
Rob Kriekaard

**Comment by pawan-saxena** [comment]
@rkriekaard Have you found the solution...i am facing similar issue.
I am using a private ip. :(

**Comment by lucaderi** [comment]
Hi all, the solution is to edit the geoIP files ad described in https://github.com/threatstream/mhn/wiki/Customizing-Maxmind-IP-Geo-DB-for-Internal-Networks
