### ISSUE TITLE
make does not respect --prefix=

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#1457]
When I configure ntopng with --prefix=/opt/ntopng and then run make, the json-c, rrdtool and zeromq subdirectories do not inherit --prefix=/opt/ntopng

```
$ make
cd /home/mc/src/ntopng/third-party/rrdtool-1.4.8; ./configure --disable-libdbi --disable-libwrap --disable-rrdcgi --disable-libtool-lock --disable-nls --disable-rpath --disable-perl --disable-ruby --disable-lua --disable-tcl --disable-python --disable-dependency-tracking --disable-rrd_graph ; cd src; /usr/bin/gmake librrd_th.la
[...skip...]
cd /home/mc/src/ntopng/third-party/zeromq-4.1.3; ./configure --without-documentation --without-libsodium; /usr/bin/gmake
```

The [instructions on how to compile ntopng](https://github.com/ntop/ntopng/blob/dev/doc/README.compilation) do not mention json-c, rrdtool and zeromq are dependencies either.

**Comment by emanuele-f** [comment]
They are used internally by ntopng, you don't need to install them

**Comment by ghost** [comment]
Oops, sorry to have troubled you.
