### ISSUE TITLE
build for Streatch-pi (Raspberry ARM)

### ISSUE THREAD

**Issue by mmajer** [ntop/ntopng#1459]
Hi,
When did the release of the Raspberry (ARM) package on "Stretch-pi" distribution?
Thanks

Mauro

**Comment by howdey57** [comment]
Just wondering if this might get done soon?

Charles

**Comment by emanuele-f** [comment]
The build is available at http://packages.ntop.org/RaspberryPI/

**Comment by howdey57** [comment]
Just tried to install this but got an error, and the code was not signed. Thoughts?

Preparing to unpack .../ntopng_3.1.171108-3683_armhf.deb ...
Unpacking ntopng (3.1.171108-3683) over (2.4+dfsg1-3) ...
dpkg: error processing archive /var/cache/apt/archives/ntopng_3.1.171108-3683_armhf.deb (--unpack):
 trying to overwrite '/usr/share/ntopng/httpdocs/css/bootstrap-datetimepicker.css', which is also in package ntopng-data 2.4+dfsg1-3
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/ntopng_3.1.171108-3683_armhf.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by emanuele-f** [comment]
You ntopng-data package is outdated (it is using old version 2.4). Please remove any ntopng related package, including the /etc/apt/sources.list.d/ntop.list. Then follow the instructions at the link above.

**Comment by sweetrush** [comment]
did 
`sudo apt purge ntopng-data`
Then was able to rerun the install command ntopng and it worked
