### ISSUE TITLE
Dashboard makes unnecessary network requests (1 per second) when update period set to 1 minute

### ISSUE THREAD

**Issue by qm2k** [ntop/ntopng#1460]
I have update period set to 1 minute and indeed new information appears on dashboard that often. However, according to various instrumentation, the dashboard:
* makes 3 requests every 3 seconds:
    * /lua/get_hosts_data.lua?mode=local&currentPage=1&sortColumn=column_thpt&sortOrder=desc&long_names=1
    * /lua/get_hosts_data.lua?mode=remote&currentPage=1&sortColumn=column_thpt&sortOrder=desc&long_names=1
    * /lua/get_http_hosts_data.lua?mode=all&currentPage=1&sortColumn=column_act_num_http_requests&sortOrder=desc&long_names=1
* creates 1.8Mbps of continuous network traffic;
* adds ~10% to server CPU load;
* adds ~30% to client Firefox CPU load (it's better in Chromium).

It would be nice if it avoided these unnecessary requests.

This issue is somewhat similar to #1410.

**Comment by simonemainardi** [comment]
Thanks for pointing it out. Top talkers ajax refreshes (left of the dashboard) now honour the 'housekeeping frequency' set via the preferences. Refreshing in a shorter time was actually unnecessary. So if you set the housekeeping frequency to 1 minute, you should expect the 3 requests to be performed every minute.

A new build will be available tomorrow.

**Comment by qm2k** [comment]
Updated to  v.3.1.170923 and lost all my settings. Tried to restore them from memory but `Top Local Talkers` and `Top Remote Destinations` tables now update every 5 seconds. Realtime Traffic charts update every 60 seconds like they should. Can you please tell where 5 seconds comes from? `Hosts Statistics Update Frequency` is set to 60 seconds, and so is `Realtime Stats Refresh Rate` of each interface.

**Comment by qm2k** [comment]
v.3.1.170928. Global settings preserved, interface settings lost. `Top Local Talkers` and `Top Remote Destinations` tables work again, `get_hosts_data.lua` requests repeat every 60 seconds as they should. There's still one unnecessary `get_http_hosts_data.lua` request every 3 seconds.

**Comment by simonemainardi** [comment]
ok, `get_http_hosts_data` adjusted as well.

**Comment by qm2k** [comment]
Everything now seem to work as it should, thank you!
