### ISSUE TITLE
Dashboard is useless with many interfaces 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1462]
<img width="1344" alt="screen shot 2017-09-21 at 15 44 51" src="https://user-images.githubusercontent.com/4493366/30699001-d4879322-9ee3-11e7-9ad4-e462b6ce8ddb.png">

**Comment by simonemainardi** [comment]
The maximum number of interfaces shown in the dashboard is now limited to 8. We should consider making this number configurable and to allow a user to actually select which interfaces he/she wants to see.
