### ISSUE TITLE
 gpg: error reading key: public key not found gpg: no default secret key: secret key not available 

### ISSUE THREAD

**Issue by pleoeter** [ntop/ntopng#1466]
Processing ../ntopng_3.1.170922-3451_amd64.deb...
gpg: error reading key: public key not found
gpg: no default secret key: secret key not available
gpg: /tmp/debsigs-ng.Myq7rl/digests: clearsign failed: secret key not available
E: Signing failed. Error code: 512
Makefile:10: recipe for target 'ntopng' failed
make: *** [ntopng] Error 1

I am continuously getting the error while trying to creat package and install debian file for ntop using "deb - do 'cd packages/ubuntu;./configure;make"  please guide

**Comment by simonemainardi** [comment]
you have to create your own GPG key (see `gpg --gen-key`) to clearsign the package. Once you have created the key, change https://github.com/ntop/ntopng/blob/dev/packages/ubuntu/Makefile.in#L41 to specify your key identifier.

**Comment by pleoeter** [comment]
thank you @simonemainardi  , it solved my problem

Now when i give  
dpkg -i ntopng_3.1.170925-3460_amd64.deb

it gives me the following , i enables the pf_ring service though
Executing /lib/systemd/systemd-sysv-install enable ntopng
insserv: Service pf_ring has to be enabled to start service ntopng
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
dpkg: error processing package ntopng (--install):
 subprocess installed post-installation script returned error exit status 1

**Comment by simonemainardi** [comment]
you have to build and install pf_ring dependency before ntopng

**Comment by pleoeter** [comment]
@simonemainardi Can you please tell all the steps , because i cannot find them in any single tutorial?

**Comment by simonemainardi** [comment]
everything is available on the github PF_RING wiki page: https://github.com/ntop/PF_RING/wiki
