### ISSUE TITLE
AS Graphs are not produced with Sub-Interfaces

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1467]
![screen shot 2017-09-22 at 23 02 23](https://user-images.githubusercontent.com/4493366/30764176-1e65d9b6-9fea-11e7-862c-05751d4aaf63.png)
![screen shot 2017-09-22 at 23 02 00](https://user-images.githubusercontent.com/4493366/30764177-1e8beef8-9fea-11e7-95d1-642034823a12.png)

**Comment by simonemainardi** [comment]
Fixed in the latest dev build.
