### ISSUE TITLE
ASN are repeated more than once in view interfaces

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1468]
![screen shot 2017-09-22 at 23 02 23](https://user-images.githubusercontent.com/4493366/30764220-44e24b10-9fea-11e7-83e3-1bd1f32f5ad5.png)

**Comment by simonemainardi** [comment]
This is a limitation of view interfaces that don't expect to have the same autonomous system on more than one of the interfaces aggregated through the same view.
