### ISSUE TITLE
Add preference for network discovery

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1469]
For some reason (e.g. an interface with mirror traffic) some interfaces cannot be used for network discovery. It is requested to add a preference on the GUI to disable discover on this interface if the administrator wants to toggle this preference.

**Comment by simonemainardi** [comment]
Feature implemented.

A checkbox is shown in the preference page of any discoverable interface when the periodic discovery is enabled from the preferences

![image](https://user-images.githubusercontent.com/3397663/30905367-de1723cc-a374-11e7-89da-5dba7ff7ec0e.png)

![image](https://user-images.githubusercontent.com/3397663/30905404-f83a169c-a374-11e7-9161-0467eca288f3.png)
