### ISSUE TITLE
nTOPng top talkers not showing on the dashboard

### ISSUE THREAD

**Issue by mtnoc** [ntop/ntopng#147]
Dear support,

Yet a few challenges that I experience which are below.

I currently SPAN 2 interfaces, one Internal and one WAN. The internal interface seems to be running fine.

1.	Challenge that I experience is generating report, especially custom report, it takes long time to complete full report and also many times web browser crashed, no matters which web browsers I use.

2.	WAN interface, I tested download/upload files then
        1. Select WAN interface from top menu, see "Picture1_WAN Interface.png"
        2. On the dashboard, Top Talkers, nothing show up, except for local-link IPv6 shown up, but on the right hand side “Realtime top Application Traffic” and “Realtime Traffic” both show up correctly information, see "Picture2_Dashboard"
        3. Active Flows shows correct information, see "Picture3_nTop_Active Flows"

![picture1_wan interface](https://cloud.githubusercontent.com/assets/14069834/9624220/ceb5c4d2-5174-11e5-894c-b617873ed3a8.jpg)

![picture2_dashboard](https://cloud.githubusercontent.com/assets/14069834/9624224/d83b2fba-5174-11e5-9e9e-82cc9fd2db13.jpg)

![picture3_ntop_active flows](https://cloud.githubusercontent.com/assets/14069834/9624226/dcd8b240-5174-11e5-9399-88af36b9869e.png)

Can you please investigate and advise?

Thank you.

**Comment by lucaderi** [comment]
Can you please move to the latest development version first and explain in detail (or better send the URL) what reports are mostly causing the issue?

**Comment by lmangani** [comment]
Knowing the resources allocated to your system might help, too.

**Comment by lucaderi** [comment]
@mtnoc Can you please update and see if with the latest nightly build, these issues are gone?

**Comment by lucaderi** [comment]
No feedback. Closing the bug as it works for me for the time being.
