### ISSUE TITLE
Category RRDs are not created for virtual interfaces 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1471]
Suppose to disaggregate traffic for ethX based on VLAN and to set in preferences the creation of L7 RRDs per categories.
ntopng does not create category RRDs and reports the following error
23/Sep/2017 08:05:01 [Lua.cpp:6432] WARNING: Script failure [/home/deri/ntopng/scripts/callbacks/5min.lua][/home/deri/ntopng/scripts/callbacks/5min.lua:101: opening '/var/tmp/ntopng/4/rrd/Unspecified.rrd': No such file or directory]

even though the directory exists
ls  /var/tmp/ntopng/4/rrd/
bytes.rrd  drops.rrd  num_devices.rrd  num_flows.rrd  num_hosts.rrd  num_http_hosts.rrd  packets.rrd  tcp_finack.rrd  tcp_lost.rrd  tcp_ooo.rrd  tcp_retransmissions.rrd  tcp_rst.rrd  tcp_synack.rrd  tcp_syn.rrd

and the disk is empty

**Comment by simonemainardi** [comment]
fixed as of https://github.com/ntop/ntopng/commit/85098c864ae29dd8394fb1293f7a701995d374dc. Re-tested both with VLAN- and ProbeIP-based interfaces
