### ISSUE TITLE
User interface is inconsistent

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1472]
Recent changes in ntopng user interface have introduced mixed logic. For instance see the two enclosed examples. In interface preferences some fields (e.g. Custom Name) require the save button to be saved to write the preference value, whereas others (e.g. Trigger Interface Alerts) do not. 

![screen shot 2017-09-23 at 08 11 56](https://user-images.githubusercontent.com/4493366/30770687-e349a356-a036-11e7-8edc-1d02937ed198.png)

In the other example it is possible to modify the value inline by clicking on Edit, whereas in other pages (e.g. traffic policers) there is a save button at the end of the page.

![screen shot 2017-09-23 at 08 11 40](https://user-images.githubusercontent.com/4493366/30770688-e34c8026-a036-11e7-9c06-1d3bef23ee14.png)

I am not questioning about the way to implement these features, but I would like to have one consistent way of setting preferences and not like it is today that is different page by page

**Comment by emanuele-f** [comment]
Fixed with commits:

- f62c86a2419e07157ebf5d8dccbbeec390600fbf
- 70486044048f58bdaab1859e8e7be2b9e3d50d15
- 7a62ae009bde0bf60a0833bf22d7255a7088d134
