### ISSUE TITLE
Implement per-MAC RRDs

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1473]
In LANs per-IP RRDs might be misleading as IP addresses might be assigned dynamically to hosts and thus in a RRD we might mix traffic coming from different devices and thus different users.

In this context per-IP RRDs are useless, and it would be necessary to implement per-MAC RRDs.

It is requested to implement a new preference that allows you to select if RRDs are not created at all, created per IP or created per MAC.

**Comment by simonemainardi** [comment]
implemented

![image](https://user-images.githubusercontent.com/3397663/31185200-b001a662-a92b-11e7-9eab-96064e55a7c8.png)
