### ISSUE TITLE
Implement RRD cleanup

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1474]
After #1473 is implemented, supposing to set per-MAC RRDs, there is a new challenge to face with. In fact in case a ntopng administrator decides to create per-MAC RRDs and in case an interfaces has many guest MACs (e.g. when using ntopng to monitor a public WiFi where users connect and disconnect very frequently and most users are not persistent), we will end-up filling up the storage with MAC RRDs that are no longer user as the MAC will no longer connect to the network.

It is requested to implement an automatic (e.g. in the daily lua script) to cleanup MAC address directories (so delete all the directory RRDs and not individual files) for those MAC addresses who have not been updated since X days, where X is set in preferences.

**Comment by simonemainardi** [comment]
implemented as requested. configuration available via ntopng preferences
