### ISSUE TITLE
AS View contains ASs with no hosts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1475]
![screen shot 2017-09-23 at 08 29 42](https://user-images.githubusercontent.com/4493366/30770772-64e5517e-a039-11e7-86b9-65b6422ee545.png)

**Comment by simonemainardi** [comment]
Issue is fixed with the latest changes. One may experience a zero number of hosts only upon ajax page refreshes provided that all the hosts belonging to a given AS have been purged.
