### ISSUE TITLE
Implement per-category Top RRDs

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1476]
When per-category RRDs are set, it is not possible to see the top categories for an interface (as it happens with top L7 protocols). It is requested to implement this also with categories.

![screen shot 2017-09-23 at 08 37 02](https://user-images.githubusercontent.com/4493366/30770825-6c7e5f42-a03a-11e7-8db5-5a8e2cee0df8.png)

**Comment by simonemainardi** [comment]
![image](https://user-images.githubusercontent.com/3397663/31229841-529ba01a-a9e2-11e7-89f6-25988bc74456.png)

implemented. Categories are now listed in an independent section of the dropdown menu and a stacked chart is available for the top RRDs.
