### ISSUE TITLE
Devices menu empty

### ISSUE THREAD

**Issue by mjducharme** [ntop/ntopng#1479]
We had a problem with our ntop server where it ran out of disk space (MySQL grew to 180GB) so we were forced to delete the databases. They were recreated and ntop is running again, but now the "Devices" menu is empty, so we are unable to add the core routers and their IP addresses for SNMP, so that we can see the interface names.

**Comment by simonemainardi** [comment]
can you please check if the issue is still occurring with version `v.3.1.170925`?

What is the ntopng configuration used?

**Comment by mjducharme** [comment]
Yes it still occurs with 3.1.170925.

The config used is below:

--pid /var/run/ntopng/ntopng.pid
-U nobody
--http-port 56099
--https-port 443
-F "mysql;localhost;nprobe;flows;nprobe;REDACTED"
--mysql-skip-db-creation
-i tcp://127.0.0.1:1234c
--dns-mode 3
--redis localhost
--data-dir /opt/storage/ntopng
--online-license-check
--local-networks="REDACTED"

**Comment by mjducharme** [comment]
We also had to delete the contents of /opt/storage/ntopng (the directory itself was not touched though)

**Comment by simonemainardi** [comment]
can you please send a capture of page about.lua?

Note that SNMP is only available with ntopng Enterprise.

**Comment by mjducharme** [comment]
![ntopng-about](https://user-images.githubusercontent.com/1851874/30871897-399b36d0-a29d-11e7-8ffd-f43042846317.PNG)

**Comment by simonemainardi** [comment]
OK, so you have a licensed Professional version. SNMP requires Enterprise.

**Comment by mjducharme** [comment]
When did this change? It used to be that the Professional edition supported basic SNMP, and the enterprise edition supported per interface graphs. The product comparison on your website still says this is the case.

**Comment by mjducharme** [comment]
The website says that both professional edition and enterprise edition have "Query SNMP devices data, such as port status, traffic and and MAC address information"

Only the enterprise edition has "Visualize and historicise SNMP per-device-port traffic"

Or has this changed and you have now revoked all SNMP privileges from Professional edition users who previously had them?

**Comment by simonemainardi** [comment]
Sorry, we didn't revoke anything.

SNMP data is still available in the Professional version. You just have to look in the host page under the SNMP tab

![image](https://user-images.githubusercontent.com/3397663/30873469-ab6b4d18-a2ed-11e7-99a8-b482191ad825.png)


You can configure the SNMP community under the preferences

**Comment by mjducharme** [comment]
But then how do you explain why the "Devices" menu is now empty where it used to have an SNMP option, and I had added our core routers in there, and then I could see the interface names associated with a certain flow?

I could see that before this problem, and now it is gone.

**Comment by mjducharme** [comment]
In the feature comparison page, the feature "Query SNMP devices data, such as port status, traffic and and MAC address information" has a link (on the word SNMP) to this page:

http://www.ntop.org/ntopng/monitoring-network-devices-with-ntopng-and-snmp/

I saw that page previously and I had configured our core routers like that and it was working.

The only thing that of course didn't work was the per-interface graphs since those are only supported in Enterprise edition.

Since I had to delete the /opt/storage/ntopng contents and erase the mysql database, the options to set things up the way I had them before have now vanished - hence the reason for me opening up this ticket.

We have never previously had the Enterprise edition to my knowledge.

**Comment by simonemainardi** [comment]
I agree with you that the information in the feature comparison page is not accurate enough. I am going to change it now.

Anyway, we didn't remove the SNMP feature, we just re-arranged the way SNMP is accessed through Professional and Enterprise versions. You can still get any core router SNMP information if you visit its host page.

However, I understand that you were familiar with the SNMP devices list and now that is no longer available. So please feel free to contact us privately and we will try to find a solution for this.
