### ISSUE TITLE
Issue with "-i view:" parameter

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#148]
I think that ntopng have a problem to manage the "-i view:" parameter (used to aggregate more interfaces in a single view).

If I use the "view" option in this way:
    ntopng -i eth6 -i eth7 -i view:eth6,eth7 [...]
all works fine. If I use instead the zc drivers:
    ntopng -i zc:2@0 -i zc:2@1 -i view:zc:2@0,zc:2@1 [...]
the virtual aggregated interface "zc:2@0,zc:2@1" doesn't appear.

I think that the problem is related to the "NetworkInterfaceView::NetworkInterfaceView(const char *name, int id)" function and should be caused by ":" character used both by the "view" option and by the name of the zc interfaces.

Thanks...

   Gianluca

**Comment by kYroL01** [comment]
Please @gianogli test if the issue is fixed.

**Comment by lucaderi** [comment]
Just fixed
