### ISSUE TITLE
Implement daily schedule, per protocol and per pool

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#1480]
The daily schedule bitmap field is already there in redis, it only needs to be implemented in the C core

**Comment by lucaderi** [comment]
@emanuele-f What is this issue about? Please explain.

**Comment by emanuele-f** [comment]
The issue is about implementing a check in the host pools policies, blocking the traffic in specified hours of the day. E.g. a user is only allowed to surf the web from 8 to 16 every day. This should work both on a per-protocol basis and on an host-pool basis.

Rather than using a start and end time, the implementation should use the already provided bitmap and perform the checks on a per-hour basis (1 bit = 1 hour). The remaining 8 bit of the bitmap can be extended in future to include the days of the week.

**Comment by emanuele-f** [comment]
Implemented with 7281fd0d5d9b566c0c59657db379306453d5ae2f and related commits
