### ISSUE TITLE
Customize Alerts

### ISSUE THREAD

**Issue by rgstephens** [ntop/ntopng#1485]
I have setup a network of MQTT servers and generate a lot of MQTT traffic.  Every packet shows up as Suspicious Activity.  I'd like to be able to disable suspicious activity associated with traffic by port.

Is there a file somewhere that defines the alerts and can be customized?

**Comment by simonemainardi** [comment]
do you get this in the Flow Alerts page? What is the alert message you get?

**Comment by rgstephens** [comment]
It shows up under Queued Alerts.  Here's the message:

```
Probing or server down: 10.1.1.4 > ip-37-201-5-110.hsi13.unitymediagroup.de [TCP 10.1.1.4:46092 > 37.201.5.110:8883 [proto: 0/Unknown][3/0 pkts][222/0 bytes][SYN]]
```

**Comment by simonemainardi** [comment]
Added as task in https://github.com/ntop/ntopng/issues/1808
