### ISSUE TITLE
AS Graphs metrics are reverted

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1491]
All the AS graph have invalid metrics: received should be sent and vice-versa. Example the following graph is mostly download (i.e. the prevalent direction is from AS 2906 to us) but ntopng reports it the other way round.

<img width="1160" alt="screen shot 2017-09-28 at 07 25 28" src="https://user-images.githubusercontent.com/4493366/30969017-667060ae-a41e-11e7-999c-821ea4503592.png">

**Comment by simonemainardi** [comment]
If traffic is prevalently "from AS 2906 to us" then this chart is ok: AS 2906 is sending traffic to you and so it has a very high percentage of sent traffic.

I have also checked this by doing other tests but everything seems to work as expected.
