### ISSUE TITLE
NDPI related macro or api not found , where can I install such dependency ?

### ISSUE THREAD

**Issue by qianguozheng** [ntop/ntopng#1495]
weeds@R:~/magicwifi/test/ntopng$ make
g++ -g -Wall -I/home/weeds/magicwifi/test/ntopng -I/home/weeds/magicwifi/test/ntopng/include -I/usr/local/include -D_FILE_OFFSET_BITS=64 -I/usr/include/hiredis -I/usr/include/hiredis -I/home/weeds/magicwifi/test/ntopng/third-party/mongoose -I/usr/local/include/json-c  -I/usr/local/include/libndpi-1.8.0/libndpi -I/home/weeds/magicwifi/test/ntopng/third-party/LuaJIT-2.1.0-beta3/src  -I/home/weeds/magicwifi/test/ntopng/third-party/zeromq-4.1.3/include -I/usr/include/mysql  -I/home/weeds/magicwifi/test/ntopng -I/home/weeds/magicwifi/test/ntopng/include -I/usr/local/include -I/home/weeds/magicwifi/test/ntopng/third-party/http-client-c/src/  -I/usr/include/openssl  -DDATA_DIR='"/usr/local/share"' -I/home/weeds/magicwifi/test/ntopng/third-party/libgeohash -I/home/weeds/magicwifi/test/ntopng/third-party/patricia   -c src/NtopGlobals.cpp -o src/NtopGlobals.o
In file included from /home/weeds/magicwifi/test/ntopng/include/ntop_includes.h:164:0,
                 from src/NtopGlobals.cpp:22:
/home/weeds/magicwifi/test/ntopng/include/nDPIStats.h:53:32: error: ‘NDPI_PROTOCOL_NUM_CATEGORIES’ was not declared in this scope
   CategoryCounter cat_counters[NDPI_PROTOCOL_NUM_CATEGORIES];
                                ^
/home/weeds/magicwifi/test/ntopng/include/nDPIStats.h:64:41: error: ‘ndpi_protocol_category_t’ has not been declared
   void incCategoryStats(u_int32_t when, ndpi_protocol_category_t category_id, u_int64_t bytes);
                                         ^
/home/weeds/magicwifi/test/ntopng/include/nDPIStats.h:89:37: error: ‘ndpi_protocol_category_t’ has not been declared
   inline u_int64_t getCategoryBytes(ndpi_protocol_category_t category_id) {
                                     ^
/home/weeds/magicwifi/test/ntopng/include/nDPIStats.h:96:40: error: ‘ndpi_protocol_category_t’ has not been declared
   inline u_int32_t getCategoryDuration(ndpi_protocol_category_t category_id) {
                                        ^
/home/weeds/magicwifi/test/ntopng/include/nDPIStats.h: In member function ‘u_int64_t nDPIStats::getCategoryBytes(int)’:
/home/weeds/magicwifi/test/ntopng/include/nDPIStats.h:90:23: error: ‘NDPI_PROTOCOL_NUM_CATEGORIES’ was not declared in this scope
     if (category_id < NDPI_PROTOCOL_NUM_CATEGORIES)
                       ^
/home/weeds/magicwifi/test/ntopng/include/nDPIStats.h:91:14: error: ‘cat_counters’ was not declared in this scope
       return(cat_counters[category_id].bytes);
              ^
/home/weeds/magicwifi/test/ntopng/include/nDPIStats.h: In member function ‘u_int32_t nDPIStats::getCategoryDuration(int)’:
/home/weeds/magicwifi/test/ntopng/include/nDPIStats.h:97:23: error: ‘NDPI_PROTOCOL_NUM_CATEGORIES’ was not declared in this scope
     if (category_id < NDPI_PROTOCOL_NUM_CATEGORIES)
                       ^
/home/weeds/magicwifi/test/ntopng/include/nDPIStats.h:98:14: error: ‘cat_counters’ was not declared in this scope
       return(cat_counters[category_id].duration);
              ^
In file included from /home/weeds/magicwifi/test/ntopng/include/ntop_includes.h:213:0,
                 from src/NtopGlobals.cpp:22:
/home/weeds/magicwifi/test/ntopng/include/NetworkInterface.h: At global scope:
/home/weeds/magicwifi/test/ntopng/include/NetworkInterface.h:249:10: error: ‘ndpi_protocol_category_t’ does not name a type
   inline ndpi_protocol_category_t get_ndpi_proto_category(ndpi_protocol proto) { return(ndpi_get_proto_category(ndpi_struct, proto)); };
          ^
In file included from /home/weeds/magicwifi/test/ntopng/include/ntop_includes.h:213:0,
                 from src/NtopGlobals.cpp:22:
/home/weeds/magicwifi/test/ntopng/include/NetworkInterface.h:250:45: error: ‘get_ndpi_category_name’ declared as an ‘inline’ field
   inline const char* get_ndpi_category_name(ndpi_protocol_category_t category) { return(ndpi_category_get_name(ndpi_struct, category)); };
                                             ^
/home/weeds/magicwifi/test/ntopng/include/NetworkInterface.h:250:22: error: expected ‘;’ at end of member declaration
   inline const char* get_ndpi_category_name(ndpi_protocol_category_t category) { return(ndpi_category_get_name(ndpi_struct, category)); };
                      ^
/home/weeds/magicwifi/test/ntopng/include/NetworkInterface.h:250:70: error: expected ‘)’ before ‘category’
   inline const char* get_ndpi_category_name(ndpi_protocol_category_t category) { return(ndpi_category_get_name(ndpi_struct, category)); };
                                                                      ^
/home/weeds/magicwifi/test/ntopng/include/NetworkInterface.h:251:3: error: ‘ndpi_protocol_category_t’ does not name a type
   ndpi_protocol_category_t get_ndpi_proto_category(u_int protoid);
   ^
/home/weeds/magicwifi/test/ntopng/include/NetworkInterface.h:337:40: error: ‘ndpi_protocol_category_t’ has not been declared
   void getnDPIProtocols(lua_State *vm, ndpi_protocol_category_t filter);
                                        ^
/home/weeds/magicwifi/test/ntopng/include/NetworkInterface.h:338:51: error: ‘ndpi_protocol_category_t’ has not been declared
   void setnDPIProtocolCategory(u_int16_t protoId, ndpi_protocol_category_t protoCategory);
                                                   ^
/home/weeds/magicwifi/test/ntopng/include/NetworkInterface.h: In member function ‘void NetworkInterface::incStats(bool, time_t, u_int16_t, u_int16_t, u_int, u_int, u_int)’:
/home/weeds/magicwifi/test/ntopng/include/NetworkInterface.h:291:72: error: ‘get_ndpi_proto_category’ was not declared in this scope
     ndpiStats.incCategoryStats(when, get_ndpi_proto_category(ndpi_proto), pkt_len);
                                                                        ^
In file included from /home/weeds/magicwifi/test/ntopng/include/ntop_includes.h:265:0,
                 from src/NtopGlobals.cpp:22:
/home/weeds/magicwifi/test/ntopng/include/Mac.h: In member function ‘void Mac::incnDPIStats(u_int32_t, ndpi_protocol, u_int64_t, u_int64_t, u_int64_t, u_int64_t, u_int64_t, u_int64_t)’:
/home/weeds/magicwifi/test/ntopng/include/Mac.h:79:25: error: ‘class NetworkInterface’ has no member named ‘get_ndpi_proto_category’
         getInterface()->get_ndpi_proto_category(protocol.master_protocol), sent_bytes + rcvd_bytes);
                         ^
/home/weeds/magicwifi/test/ntopng/include/Mac.h:81:25: error: ‘class NetworkInterface’ has no member named ‘get_ndpi_proto_category’
         getInterface()->get_ndpi_proto_category(protocol.app_protocol), sent_bytes + rcvd_bytes);
                         ^
/home/weeds/magicwifi/test/ntopng/include/Mac.h:81:58: error: ‘const ndpi_protocol {aka const struct ndpi_proto}’ has no member named ‘app_protocol’
         getInterface()->get_ndpi_proto_category(protocol.app_protocol), sent_bytes + rcvd_bytes);
                                                          ^
In file included from /home/weeds/magicwifi/test/ntopng/include/ntop_includes.h:267:0,
                 from src/NtopGlobals.cpp:22:
/home/weeds/magicwifi/test/ntopng/include/Flow.h: At global scope:
/home/weeds/magicwifi/test/ntopng/include/Flow.h:313:10: error: ‘ndpi_protocol_category_t’ does not name a type
   inline ndpi_protocol_category_t get_detected_protocol_category() { return ndpi_get_proto_category(iface->get_ndpi_struct(), ndpiDetectedProtocol); };
          ^
/home/weeds/magicwifi/test/ntopng/include/Flow.h: In member function ‘ndpi_protocol_breed_t Flow::get_protocol_breed()’:
/home/weeds/magicwifi/test/ntopng/include/Flow.h:317:130: error: ‘ndpi_protocol {aka struct ndpi_proto}’ has no member named ‘app_protocol’
   inline ndpi_protocol_breed_t get_protocol_breed() { return(ndpi_get_proto_breed(iface->get_ndpi_struct(), ndpiDetectedProtocol.app_protocol)); };
                                                                                                                                  ^
/home/weeds/magicwifi/test/ntopng/include/Flow.h: In member function ‘char* Flow::get_protocol_breed_name()’:
/home/weeds/magicwifi/test/ntopng/include/Flow.h:320:39: error: ‘ndpi_protocol {aka struct ndpi_proto}’ has no member named ‘app_protocol’
                  ndpiDetectedProtocol.app_protocol))); };
                                       ^
Makefile:154: recipe for target 'src/NtopGlobals.o' failed
make: *** [src/NtopGlobals.o] Error 1

**Comment by simonemainardi** [comment]
Your nDPI sources are outdated.

Make sure to clone, update and build nDPI code tree before building ntopng.

Instructions are available at: https://github.com/ntop/ntopng/blob/dev/doc/README.compilation#L55
