### ISSUE TITLE
pf_ring and armhf issue (new ntopng update problem)

### ISSUE THREAD

**Issue by filemoon** [ntop/ntopng#1496]
Unable to update ntopng - pf_ring is needed for ntopng now but deb is not present for armhf.

Setting up ntopng (3.1.170928-3496) ...
Rebuilding ld cache...
Adding the ntopng startup script [configure]
Synchronizing state of ntopng.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable ntopng
insserv: Service pf_ring has to be enabled to start service ntopng
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
dpkg: error processing package ntopng (--configure):
subprocess installed post-installation script returned error exit status 1
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Errors were encountered while processing:
ntopng
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by antoniovalenzuela** [comment]
Same issue raspberry pi3

Synchronizing state for ntopng.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d ntopng defaults
insserv: Service pf_ring has to be enabled to start service ntopng
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
*** Error in `systemctl': double free or corruption (fasttop): 0x55cc7f78 ***
Aborted
dpkg: error processing package ntopng (--configure):
 subprocess installed post-installation script returned error exit status 134
Setting up ntopng-data (3.1.170928) ...
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Errors were encountered while processing:
 ntopng
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by antoniovalenzuela** [comment]
news? i can't install ntopng

**Comment by gjws** [comment]
Still can't install. Any ETA on a fix please?

**Comment by simonemainardi** [comment]
Fixed: https://github.com/ntop/ntopng/commit/94502920ef1a67a4c5a7e397e682e77a00b9895f a new build will be released shortly

**Comment by antoniovalenzuela** [comment]
15 days without using ntopng

another issue:

Preparing to unpack .../nprobe_8.1.171016-5920_armhf.deb ...
Unpacking nprobe (8.1.171016-5920) over (8.1.170928-5893) ...
Preparing to unpack .../ntopng_3.1.171016-3574_armhf.deb ...
Unpacking ntopng (3.1.171016-3574) over (3.1.170928-3496) ...
Preparing to unpack .../ntopng-data_3.1.171016_all.deb ...
Unpacking ntopng-data (3.1.171016) over (3.1.170928) ...
Processing triggers for systemd (215-17+deb8u7) ...
Processing triggers for man-db (2.7.0.2-5) ...
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Setting up nprobe (8.1.171016-5920) ...
Rebuilding ld cache...
Adding the nprobe startup script
Synchronizing state for nprobe.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d nprobe defaults
insserv: Service pf_ring has to be enabled to start service nprobe
insserv: Service cluster has to be enabled to start service nprobe
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
*** Error in `systemctl': double free or corruption (fasttop): 0x01291f78 ***
Aborted
dpkg: error processing package nprobe (--configure):
 subprocess installed post-installation script returned error exit status 134
Setting up ntopng (3.1.171016-3574) ...
Rebuilding ld cache...
Adding the ntopng startup script [configure]
Synchronizing state for ntopng.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d ntopng defaults
Executing /usr/sbin/update-rc.d ntopng enable
(Re)Starting ntopng...
Failed to restart ntopng.service: Unit pf_ring.service failed to load: No such file or directory.
dpkg: error processing package ntopng (--configure):
 subprocess installed post-installation script returned error exit status 6
Setting up ntopng-data (3.1.171016) ...
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Errors were encountered while processing:
 nprobe
 ntopng
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by simonemainardi** [comment]
retry now with the latest package

**Comment by antoniovalenzuela** [comment]
Setting up ntopng (3.1.171016-3574) ...
Rebuilding ld cache...
Adding the ntopng startup script [configure]
Synchronizing state for ntopng.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d ntopng defaults
Executing /usr/sbin/update-rc.d ntopng enable
(Re)Starting ntopng...
Failed to restart ntopng.service: Unit pf_ring.service failed to load: No such file or directory.
dpkg: error processing package ntopng (--configure):
 subprocess installed post-installation script returned error exit status 6
Setting up wpasupplicant (2.3-1+deb8u5) ...
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Errors were encountered while processing:
 ntopng
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by jasonamorrow** [comment]
Looks like I'm having a similar issue. When trying to update today:

Setting up nprobe (8.1.171016-5920) ...
Rebuilding ld cache...
Adding the nprobe startup script
Synchronizing state for nprobe.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d nprobe defaults
insserv: Service pf_ring has to be enabled to start service nprobe
insserv: Service cluster has to be enabled to start service nprobe
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
*** Error in `systemctl': double free or corruption (fasttop): 0x554f1f78 ***
Aborted
dpkg: error processing package nprobe (--configure):
 subprocess installed post-installation script returned error exit status 134
Setting up ntopng (3.1.171016-3574) ...
Rebuilding ld cache...
Adding the ntopng startup script [configure]
Synchronizing state for ntopng.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d ntopng defaults
Executing /usr/sbin/update-rc.d ntopng enable
(Re)Starting ntopng...
Failed to restart ntopng.service: Unit pf_ring.service failed to load: No such file or directory.
dpkg: error processing package ntopng (--configure):
 subprocess installed post-installation script returned error exit status 6
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Errors were encountered while processing:
 nprobe
 ntopng
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by antoniovalenzuela** [comment]
Open #1548
The problem continues and the links are broken
@simonemainardi

**Comment by atoonk** [comment]
same issue here..

**Comment by r1bnc** [comment]
cannot install ntop RPI 2B.
```

sudo apt install ntopng nprobe
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libdbi1 libhiredis0.13 libmariadb2 libnetfilter-queue1 librrd8 ntopng-data
  redis-server redis-tools
Suggested packages:
  ruby-redis
The following NEW packages will be installed:
  libdbi1 libhiredis0.13 libmariadb2 libnetfilter-queue1 librrd8 nprobe ntopng
  ntopng-data redis-server redis-tools
0 upgraded, 10 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/28.1 MB of archives.
After this operation, 82.9 MB of additional disk space will be used.
Do you want to continue? [Y/n] y

Selecting previously unselected package libdbi1:armhf.
(Reading database ... 73928 files and directories currently installed.)
Preparing to unpack .../0-libdbi1_0.9.0-4_armhf.deb ...
Unpacking libdbi1:armhf (0.9.0-4) ...
Selecting previously unselected package libhiredis0.13:armhf.
Preparing to unpack .../1-libhiredis0.13_0.13.3-2_armhf.deb ...
Unpacking libhiredis0.13:armhf (0.13.3-2) ...
Selecting previously unselected package libmariadb2:armhf.
Preparing to unpack .../2-libmariadb2_2.3.2-2_armhf.deb ...
Unpacking libmariadb2:armhf (2.3.2-2) ...
Selecting previously unselected package librrd8:armhf.
Preparing to unpack .../3-librrd8_1.6.0-1+b1_armhf.deb ...
Unpacking librrd8:armhf (1.6.0-1+b1) ...
Selecting previously unselected package nprobe.
Preparing to unpack .../4-nprobe_8.1.171106-5938_armhf.deb ...
Unpacking nprobe (8.1.171106-5938) ...
Selecting previously unselected package redis-tools.
Preparing to unpack .../5-redis-tools_3%3a3.2.6-1_armhf.deb ...
Unpacking redis-tools (3:3.2.6-1) ...
Selecting previously unselected package redis-server.
Preparing to unpack .../6-redis-server_3%3a3.2.6-1_armhf.deb ...
Unpacking redis-server (3:3.2.6-1) ...
Selecting previously unselected package libnetfilter-queue1.
Preparing to unpack .../7-libnetfilter-queue1_1.0.2-2_armhf.deb ...
Unpacking libnetfilter-queue1 (1.0.2-2) ...
Selecting previously unselected package ntopng.
Preparing to unpack .../8-ntopng_3.1.171106-3678_armhf.deb ...
Unpacking ntopng (3.1.171106-3678) ...
Selecting previously unselected package ntopng-data.
Preparing to unpack .../9-ntopng-data_3.1.171106_all.deb ...
Unpacking ntopng-data (3.1.171106) ...
Setting up libhiredis0.13:armhf (0.13.3-2) ...
Setting up libdbi1:armhf (0.9.0-4) ...
Setting up redis-tools (3:3.2.6-1) ...
Setting up libnetfilter-queue1 (1.0.2-2) ...
Setting up librrd8:armhf (1.6.0-1+b1) ...
Processing triggers for libc-bin (2.24-11+deb9u1) ...
Processing triggers for systemd (232-25+deb9u1) ...
Setting up libmariadb2:armhf (2.3.2-2) ...
Setting up nprobe (8.1.171106-5938) ...
Rebuilding ld cache...
Adding the nprobe startup script
Synchronizing state of nprobe.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nprobe
insserv: Service pf_ring has to be enabled to start service nprobe
insserv: Service cluster has to be enabled to start service nprobe
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
dpkg: error processing package nprobe (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for man-db (2.7.6.1-2) ...
Setting up ntopng-data (3.1.171106) ...
Setting up redis-server (3:3.2.6-1) ...
Setting up ntopng (3.1.171106-3678) ...
Rebuilding ld cache...
Adding the ntopng startup script [configure]
Synchronizing state of ntopng.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable ntopng
Processing triggers for libc-bin (2.24-11+deb9u1) ...
Errors were encountered while processing:
 nprobe
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**Comment by jj2473** [comment]
sudo apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  gstreamer1.0-plugins-bad libgl1-mesa-dri libgstreamer-plugins-bad1.0-0
  pix-icons pix-plym-splash pixel-wallpaper raspberrypi-ui-mods sonic-pi
  wolfram-engine xserver-xorg-input-all
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up nprobe (8.1.171016-5920) ...
Rebuilding ld cache...
Adding the nprobe startup script
Synchronizing state for nprobe.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d nprobe defaults
insserv: Service pf_ring has to be enabled to start service nprobe
insserv: Service cluster has to be enabled to start service nprobe
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
*** Error in `systemctl': double free or corruption (fasttop): 0x55c3ef78 ***
Aborted
dpkg: error processing package nprobe (--configure):
 subprocess installed post-installation script returned error exit status 134
Setting up ntopng (3.1.171016-3574) ...
Rebuilding ld cache...
Adding the ntopng startup script [configure]
Synchronizing state for ntopng.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d ntopng defaults
Executing /usr/sbin/update-rc.d ntopng enable
(Re)Starting ntopng...
Failed to restart ntopng.service: Unit pf_ring.service failed to load: No such file or directory.
dpkg: error processing package ntopng (--configure):
 subprocess installed post-installation script returned error exit status 6
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Errors were encountered while processing:
 nprobe
 ntopng
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by simonemainardi** [comment]
are you guys Raspbian GNU/Linux 9.1 (stretch)? Please note that jessie is no longer supported for rpi.

**Comment by emanuele-f** [comment]
Don't know if the problem is the same, but I've had a similar issue when upgrading ntopng in ubuntu 16 from pre-sytemd version to systemd version. I've solved it by removing `/etc/init.d/ntopng`.

**Comment by RiaanLab** [comment]
Same issue here.

**Comment by emanuele-f** [comment]
@RiaanLab do you see the message `Service pf_ring has to be enabled to start service ntopng`? If you remove `/etc/init.d/ntopng`, does it fixes it?
