### ISSUE TITLE
Error While building

### ISSUE THREAD

**Issue by mitchellurgero** [ntop/ntopng#1497]
During build of this I get error "Makefile:154: recipe for target 'src/HTTPserver.o' failed"

This used to build last week (Monday Sep. 25th) but does not build anymore. I cannot find the reason why this is failing either. I have more logs if needed.

**Comment by simonemainardi** [comment]
please, post all the logs, errors and the architecture you are using to build

**Comment by mitchellurgero** [comment]
Here is the log file for about the last 70 lines, only errors are on lines 65-72

https://hastebin.com/tuvayiqixo.swift

Building on x64 Debian 8, fully updated. Building from master branch as of 6AM CST.

Commands I am running to build:

```
cd /var/temp
git clone https://github.com/ntop/nDPI.git
cd nDPI
./autogen.sh
./configure
make
cd /var/temp
git clone https://github.com/ntop/ntopng.git
cd ntopng
./autogen.sh
./configure
make
make geoip
make install
```

**Comment by simonemainardi** [comment]
It is an issue with an SSL option. Did you install/update all the necessary build dependencies before doing the steps listed above?

Please see https://github.com/ntop/ntopng/blob/dev/doc/README.compilation

**Comment by mitchellurgero** [comment]
This was building last week though as stated in the OP.

Here is what I am installing that got it to build last week:

```
build-essential
redis-server
libglib2.0
libglib2.0-dev
libtool
libgeoip-dev
libgeoip1
libpcap-dev
libpcap0.8
libxml2-dev
libsqlite3-dev
libcurl3
libcurl4-gnutls-dev
libmysqlclient18
libmysqlclient-dev
git
bison
flex
libpcap-dev
libtool-bin
rrdtool
librrd-dev
autoconf
automake
libzmq3-dev
libpng12-dev
debhelper
dpkg-sig
dkms
libhiredis0.10
librdkafka1
binutils-dev
bridge-utils
libnuma1
libnetfilter-queue1
ufw

```
Compiling nDPI for ntopng works as well (as it is also a dependency)

**Comment by emanuele-f** [comment]
@mitchellurgero this should be fixed with commit 3e5ab4e99adf5ba650bb69d6589aa48e9e2670e2 . Please try to rebuild and let me know.

**Comment by mitchellurgero** [comment]
Trying now. Will get back to you in about 45 minutes.

**Comment by mitchellurgero** [comment]
It has successfully built properly, thank you.
