### ISSUE TITLE
DNS Resolution  Broke (Windows)

### ISSUE THREAD

**Issue by mikeshev** [ntop/ntopng#1498]
I successfully used the 2.x version of ntopng on Windows for about a year. Loved it! But I was getting nagging messages about really needing to upgrade to 3.x. So I did - which I'm regretting now. I'm currently running 3.1.170713 and DNS resolution of remote hosts is completely broken. 

Here is the command I use to launch it:
ntopng.exe" /c –n 1 –i 2 –w A.B.C.D:3000 –F mysql;localhost;ntopng;flows;root; -m A.B.C.0/22,E.F.G.0/22 -p pca.protos

Note: the "-n 1" flag is supposed to: "Decode DNS responses and resolve all numeric IPs"
according to the manual. Any experience here.

**Comment by simonemainardi** [comment]
I have just re-tested name resolution with 3.1.170713 on windows and DNS resolution works properly.

Please, check your command line: the dash doesn't seem the standard one:  –n 1  should be -n 1 (note the first dash is longer and is non standard).

**Comment by mikeshev** [comment]
Oh my! You are indeed correct. So sorry I never notice that! I will note the ticket regarding my mistake. Many thanks for your help.

**Comment by simonemainardi** [comment]
thanks for reporting :)
