### ISSUE TITLE
New nightly build for RaspberryPi/stretch

### ISSUE THREAD

**Issue by howdey57** [ntop/ntopng#1499]
RaspberryPi have recently moved to Stretch as its main Raspbian release (https://www.raspberrypi.org/downloads/raspbian/). Please could you produce a new nightly build for Raspberry Pi along the same lines as you currently do for jessie (ie http://packages.ntop.org/RaspberryPI/jessie_pi/ )

Thanks,

Charles

**Comment by simonemainardi** [comment]
duplicate of https://github.com/ntop/ntopng/issues/1459
