### ISSUE TITLE
Report - summarize monthly traffic usage per internal IP - bandwidth summary and port usage

### ISSUE THREAD

**Issue by wilsonb77** [ntop/ntopng#150]
Report - summarize monthly traffic usage per internal IP - bandwidth summary and port usage.

We could use a manual or scheduled report where you can select the included dates and get a summary of usage for those dates.  The summary would show bandwidth usage and a breakdown of ports used within that traffic summary.  This would be per internal IP seen in the traffic.   

This report would be used to see per IP usage (per customer in this case) for use in billing for traffic used.

**Comment by lmangani** [comment]
@wilsonb77 please see https://github.com/ntop/ntopng/blob/dev/doc/README.historical

**Comment by svenvogel** [comment]
#394

**Comment by lucaderi** [comment]
Implemented in the current development build.
