### ISSUE TITLE
Implement per-host/mac/pool drop flow count

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1500]
When ntopng is used in inline mode or passively with blacklists, it is requested to increment a counter of number of dropped flows. The counter must be exposed at host, mac and pool level, and dumped in RRD

**Comment by simonemainardi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [implement flow drops count in inline mode (per host/device/mac)](https://trello.com/c/jIy97jiG/2-implement-flow-drops-count-in-inline-mode-per-host-device-mac)

**Comment by simonemainardi** [comment]
As requested feature is implemented both for hosts, devices and pools.

![image](https://user-images.githubusercontent.com/3397663/31290358-7dfdad1c-aacc-11e7-9b8c-461db424aafc.png)

![image](https://user-images.githubusercontent.com/3397663/31290440-c3c11a28-aacc-11e7-9a32-cca7d497fc78.png)

a new row is shown in either hosts and devices page when the number of flow drops is greater than zero and the interface is a bridge.
