### ISSUE TITLE
mysql port number not parsed from -F

### ISSUE THREAD

**Issue by andrewmv** [ntop/ntopng#1502]
The man page, user manual, and code-inline documentation indicate the following syntax for specifying a mysql backend for persistent flow storage as follows:

```
<host[@port]|unix socket>:<dbname>:<table>:<user>:<pw>
```

The `@port` option is not actually implemented, and simply being hardcoded to the default mysql port, 3306.

[Pull request](https://github.com/ntop/ntopng/pull/1501) submitted to fix this issue.

**Comment by simonemainardi** [comment]
thanks for contributing, let's move this discussion to the pull request page.
