### ISSUE TITLE
Ntop not staring

### ISSUE THREAD

**Issue by AkshatGhai123** [ntop/ntopng#1503]
Hi,

I am trying to install ntop on centos 7 machine in AWS.
Followed all the required steps
Redis is starting up but ntopng is not starting up.
Could someone please help.

[root@ip-172-31-29-143 centos]# systemctl enable redis
[root@ip-172-31-29-143 centos]# systemctl enable ntopng
[root@ip-172-31-29-143 centos]# systemctl restart redis
[root@ip-172-31-29-143 centos]#
[root@ip-172-31-29-143 centos]# systemctl start ntopng
A dependency job for ntopng.service failed. See 'journalctl -xe' for details.
[root@ip-172-31-29-143 centos]# journalct1 -xe
bash: journalct1: command not found
[root@ip-172-31-29-143 centos]#

**Comment by simonemainardi** [comment]
you typed ` journalct1:` remove the 1....

**Comment by simonemainardi** [comment]
@AkshatGhai123 any news?

**Comment by AkshatGhai123** [comment]
Hi Simon, it was an issue with pf_ring
it was not able to start
i uninstalled it, rebooted my system and then reinstalled pf_ring and ntopng, and it started working :D
