### ISSUE TITLE
AS graphs are reverted

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1504]
AS graphs have RX and TX reverted
Example this is the graph towards google ASN where most traffic is TX but it's not possible as a user sends less than what it receives from Google

![screen shot 2017-10-04 at 10 42 22](https://user-images.githubusercontent.com/4493366/31166932-ba335fe4-a8f0-11e7-8fa4-e67aa24ae747.png)

**Comment by simonemainardi** [comment]
A key now explains how to read the AS charts

![image](https://user-images.githubusercontent.com/3397663/31270958-a4fc57e2-aa86-11e7-93f1-dfb7aea82c69.png)

I do not believe that swapping RX and TX will be OK. It is true that if you have local hosts that visit google, you would like to see a lot of traffic received FROM google (so RX). But imagine an infrastructure that hosts webservers and use ntopng to monitor them. Swapping TX and RX would cause them to see a lot of traffic received FROM their webserver, and this will be inaccurate as well.

I believe the key remove all the ambiguities.
