### ISSUE TITLE
AS Graphs do not allow to plot top protocols

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1505]
In /lua/hosts_stats.lua?asn=XXXX the top protocols are not present as it happens with other views

![screen shot 2017-10-04 at 10 44 33](https://user-images.githubusercontent.com/4493366/31167068-1587056c-a8f1-11e7-9e35-856871e1a0ff.png)

**Comment by simonemainardi** [comment]
implemented

![image](https://user-images.githubusercontent.com/3397663/31235770-9a6f7a14-a9f2-11e7-8228-ad3fa325d4d5.png)
