### ISSUE TITLE
AS protocol charts report wrong protocols

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1506]
Suppose you click on Hosts -> Autonomous Systems and you select an AS such as Google that is providing very specific services such as Gmail, YouTube or DNS. If you explode the list of hosts inside the AS and you will see the remote AS hosts (e.g. Google hosts). if you click on those hosts and see the flows you will see that the L7 protocols they are doing are protocols that we expect such as DNS or YouTube.
Now the bug. If you click on the AS protocol list you will see protocols that do NOT belong to the selected AS. Example see the enclosed picture for Google AS.

![screen shot 2017-10-04 at 10 51 08](https://user-images.githubusercontent.com/4493366/31167317-fb3b37ea-a8f1-11e7-965c-62a9564895d3.png)

**Comment by simonemainardi** [comment]
@lucaderi 

- Do the timeseries of the unexpected protocols contain significant traffic?
- Is it possible for some flows to be mis-classified by nDPI?
- As you know (Google for example) offers some CDN services (e.g., to relay several common JS libraries). Do you think this can explain the unexpected protocols?

**Comment by simonemainardi** [comment]
Autonomous systems RRD files search path was wrongly generated.

I believe commits https://github.com/ntop/ntopng/commit/2faec95bd666dc585c9d43807b0e720d145af729 and the pro 5c49b3f9010467f6e83b9a438c77cfbc329bd205 has fixed the issue.

please check and reopen if necessary
