### ISSUE TITLE
ntopng doesn't save prefereces permanently

### ISSUE THREAD

**Issue by adb854** [ntop/ntopng#1507]
Hi,
I installed ntopng ver. 3.1.170713 on Windows 10 and it works very well, except that when I try to set the preferences the changes are not saved permanently. When the service is restarted the options turn back to their default values.
Could someone please help? Thank you in advance.

**Comment by adb854** [comment]
I noticed in "Runtime Status" rows like this:
05/Oct/2017 09:36:47 [Utils.cpp:242] WARNING: Unable to write file \var\tmp\ntopng/runtimeprefs.json.temp
So I created the forlder hierarchy c:\var\tmp\ntopng and then preferences saved.

**Comment by simonemainardi** [comment]
Thanks for reporting. Issue is fixed and will be available in the next Windows build.
