### ISSUE TITLE
Use of templating variables in grafana with ntop datasource

### ISSUE THREAD

**Issue by pocho1987** [ntop/ntopng#1508]
Hi, 

I've been triying to use variables to have templating dashboard to be able to visualize ntop graphs for different hosts, but i have notice that i can not use variables in the metrics when configuring the panel graph in grafana with ntop datasource.. so i would like to know if it is possible to use templating variables when using grafana with ntop datasource (create a different graph panel for each host will take me so much time). 

Thanks.

**Comment by simonemainardi** [comment]
I'm moving the discussion to https://github.com/ntop/ntopng-grafana-datasource/issues

**Comment by simonemainardi** [comment]
can you explain how you are adding variables and if you get any error?
