### ISSUE TITLE
Attempt to index local 'localdate' (a nil value)]

### ISSUE THREAD

**Issue by isvilenski** [ntop/ntopng#1509]
Hello,
I installed the latest ntopng on a windows server. 
It appears like everything is working fine except I get this error message in the console every 3 seconds. 

[Lua.cpp:6559] WARNING: Script failure [C:\Program Files\ntopng\scripts\lua\network_load.lua][C:\Program Files\ntopng/scripts/lua/modules/lua_utils.lua:2794: attempt to index local 'localdate' (a nil value)]

This is the function that seems to be failing:  (lua_utils.lua:2794)
function get_timezone_offset()
   local ts = get_tzoffset(get_timezone())
   local utcdate   = os.date("!*t", ts)
   local localdate = os.date("*t", ts)
   localdate.isdst = false -- this is the trick
   return os.difftime(os.time(localdate), os.time(utcdate))
end

What could be the problem ?

**Comment by simonemainardi** [comment]
thanks for reporting, this is fixed and will be available in the next windows build.

**Comment by isvilenski** [comment]
Thanks!
