### ISSUE TITLE
Option "-H" in the help message...

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#1512]
Hi, after this [commit](https://github.com/ntop/ntopng/commit/76153395c4e47454556ae18535bde32e5abb44e1) you also have to remove this entry into the ntopng help:

`[--disable-alerts|-H]               | Disable alerts generation`

Thanks... :-)

**Comment by simonemainardi** [comment]
yes the commit implements feature request https://github.com/ntop/ntopng/issues/1490

you can disable alerts from the ntopng web UI.

**Comment by gianogli** [comment]
@simonemainardi yes, I know. But if you run "notng -h" (last version) you can still find the line about the flag "-H". You should remove it from the help. ;-)
