### ISSUE TITLE
Lua script Modification

### ISSUE THREAD

**Issue by savanapandit** [ntop/ntopng#1514]
Hello , 
i was trying to modify lua example script at location /ntopng/scripts/lua/examples/hello_world.lua , but i cant see the modification changes from web 
https://<ip address>:3001/lua/examples/hello_world.lua

i tried following steps to see modification 

1- Restart ntop

Any clue

**Comment by emanuele-f** [comment]
Hi, please fix the url `https://127.0.0.1:3001/lua/examples/hello_world.lua`. Are you building ntopng from source or installing it via packages? Is `/ntopng/` the full path of your ntopng installation?

**Comment by savanapandit** [comment]
Hey , thanks for quick reply , got the issue fixed with proper recompilation

 ./autogen.sh &&  ./configure &&  make &&  make install &&  ntopng

Hope i am on right track
