### ISSUE TITLE
Debian Repo broken?

### ISSUE THREAD

**Issue by mahescho** [ntop/ntopng#1515]
http://packages.ntop.org does no longer work for me. I use:

deb http://packages.ntop.org/apt/jessie/ x64/
deb http://packages.ntop.org/apt/jessie/ all/

in my sources list. The repo does not look like a usual valid default repo. Please consider to use some thing like that:

https://mirrorer.alioth.debian.org/

to build a "normal standard" repo. It's pretty easy.

EDIT: I've moved the packages to my internal repo, so I've more control about wich nightly version I want to install.

**Comment by emanuele-f** [comment]
Hi, can you post the error you get?

**Comment by mahescho** [comment]
Holen: 1 http://packages.ntop.org/apt/jessie/ all/ apt-ntop 2.5-822 [6.704 B]
Fehl http://packages.ntop.org/apt/jessie/ x64/ nprobe 8.1.171009-5907
  404  Not Found
Fehl http://packages.ntop.org/apt/jessie/ x64/ ntopng 3.1.171009-3534
  404  Not Found
Fehl http://packages.ntop.org/apt/jessie/ x64/ n2disk 2.9.171009-4887
  404  Not Found
Fehl http://packages.ntop.org/apt/jessie/ x64/ cento 1.3.171009-256
  404  Not Found
Fehl http://packages.ntop.org/apt/jessie/ x64/ pfring 6.7.0-1463
  404  Not Found
Fehl http://packages.ntop.org/apt/jessie/ all/ ntopng-data 3.1.171009
  404  Not Found
Es wurden 6.714 B in 0 s geholt (9.414 B/s).
E: Fehlschlag beim Holen von http://packages.ntop.org/apt/jessie/all/./apt-ntop.deb  Größe stimmt nicht überein

E: Fehlschlag beim Holen von http://packages.ntop.org/apt/jessie/x64/./nprobe_8.1.171009-5907_amd64.deb  404  Not Found

E: Fehlschlag beim Holen von http://packages.ntop.org/apt/jessie/x64/./ntopng_3.1.171009-3534_amd64.deb  404  Not Found

E: Fehlschlag beim Holen von http://packages.ntop.org/apt/jessie/x64/./n2disk_2.9.171009-4887_amd64.deb  404  Not Found

E: Fehlschlag beim Holen von http://packages.ntop.org/apt/jessie/x64/./cento_1.3.171009-256_amd64.deb  404  Not Found

E: Fehlschlag beim Holen von http://packages.ntop.org/apt/jessie/x64/./pfring_6.7.0-1463_amd64.deb  404  Not Found

E: Fehlschlag beim Holen von http://packages.ntop.org/apt/jessie/all/./ntopng-data_3.1.171009_all.deb  404  Not Found

**Comment by cardigliano** [comment]
@mahescho it seems to be working in our lab, did you apt-get update ?

**Comment by mahescho** [comment]
:-) yes ... but for me the problem is solved with a even better solution, see my edit of the first post.

**Comment by emanuele-f** [comment]
Ok, so I'm closing the issue for now
