### ISSUE TITLE
Not getting the Application Breakdown data

### ISSUE THREAD

**Issue by Fouadata** [ntop/ntopng#1516]
Hello,
I have the NTOPNG enterprise edition, and i am not getting the Application breakdown data within the reports and dashboard.

what i am missing here?

check attached pics

![image](https://user-images.githubusercontent.com/32652862/31458764-691ec600-ae97-11e7-90ba-3fd25f949b45.png)

![image](https://user-images.githubusercontent.com/32652862/31458787-800214bc-ae97-11e7-9a1a-67e5a1dcc667.png)

![image](https://user-images.githubusercontent.com/32652862/31458845-a31631c2-ae97-11e7-9458-243c27ab96cd.png)

**Comment by simonemainardi** [comment]
hi, what is the ntopng configuration used? Do you see any error in the ntopng log? Please check and possibly report it.

What about the alerts (see the red badge at bottom-right of the page).

**Comment by Fouadata** [comment]
Check below the CONF file

-G=/var/run/ntopng.pid
--interface=enp16s0f1
--interface=enp16s0f0
--dns-mode=1
--enterprise
-–disable-autologout
--local-networks="10.10.0.0/21,192.168.199.0/24,192.168.160.0/24,10.100.0.0/16,10.200.0.0/16,10.120.0.0/16,192.168.2.0/24,192.168.6.0/24,192.168.9.0/26,192.168.9.64/26,192.168.9.128/26,192.168.9.192/26,192.168.10.0/26,192.168.10.64/26,192.168.10.128/26,192.168.10.192/26,192.168.11.0/26,192.168.11.64/26,192.168.11.128/26,192.168.11.192/26,192.168.18.0/24,192.168.19.0/24,192.168.110.0/24"

**Comment by simonemainardi** [comment]
Do not use option `--enterprise`, it does not exist.

What do you get if you visit the interface stats page with the chart? Do you get data there?
![image](https://user-images.githubusercontent.com/3397663/31625825-bdd571d0-b2a7-11e7-8c97-b0736ceca067.png)

Check file permissions, are rrd files in the data directory r/w accessible by the user which is running ntopng (e.g., sudo ls -lha /var/tmp/ntopng/0/rrd/). Make sure they have enough privileges.

Are there any errors in the ntopng log? Please visit page runtime status and check/report its contents

**Comment by Fouadata** [comment]
Check pics below
![image](https://user-images.githubusercontent.com/32652862/31626790-ce4d1036-b289-11e7-90e1-f21d8082990a.png)
![image](https://user-images.githubusercontent.com/32652862/31626820-e2acfa28-b289-11e7-84dc-063748c24ce2.png)

![image](https://user-images.githubusercontent.com/32652862/31626896-1beb1c8e-b28a-11e7-9857-0aca35911946.png)
Without the enterprise line the NTOP goes to comunity version and i am not able to use my license and see the report section.

**Comment by Fouadata** [comment]
[root@snort 0]# ls -la
total 8
drwxrwxrwx  8 root   root     93 Oct  9 16:16 .
drwxrwxrwx 11 root   root    127 Oct 16 09:56 ..
drwxrwxrwx  3 nobody nobody   15 Oct  9 16:16 activities
drwxrwxrwx  2 root   root     25 Oct  9 16:09 alerts
drwxrwxrwx  5 nobody nobody   38 Oct  9 16:10 json
drwxrwxrwx 12 nobody nobody 4096 Oct  9 16:30 rrd
drwxrwxrwx  5 nobody nobody   79 Oct  9 16:44 subnetstats
drwxrwxrwx  2 root   root   4096 Oct  9 16:58 top_talkers
[root@snort 0]# cd rrd/
[root@snort rrd]# ls -la
total 6208
drwxrwxrwx 12 nobody nobody    4096 Oct  9 16:30 .
drwxrwxrwx  8 root   root        93 Oct  9 16:16 ..
drwxrwxrwx  3 nobody nobody      15 Oct  9 16:10 10
-rwxrwxrwx  1 nobody nobody 1057000 Oct  9 16:58 bytes.rrd
-rwxrwxrwx  1 nobody nobody   22296 Oct  9 16:57 DHCPV6.rrd
-rwxrwxrwx  1 nobody nobody   22296 Oct  9 16:57 DNS.rrd
-rwxrwxrwx  1 nobody nobody 1057000 Oct  9 16:58 drops.rrd
drwxrwxrwx  3 nobody nobody      91 Oct  9 16:57 fe80__4da0_9d2c_c6d4_48c6
drwxrwxrwx  3 nobody nobody      75 Oct  9 16:57 fe80__6eae_8bff_fe63_f606
drwxrwxrwx  3 nobody nobody      75 Oct  9 16:57 fe80__a94_efff_fe30_764d
drwxrwxrwx  3 nobody nobody      75 Oct  9 16:57 fe80__a94_efff_fe30_c36d
drwxrwxrwx  3 nobody nobody      75 Oct  9 16:57 fe80__a94_efff_fe30_ca6d
drwxrwxrwx  3 nobody nobody      75 Oct  9 16:57 fe80__a94_efff_fe30_ebe5
drwxrwxrwx  3 nobody nobody      75 Oct  9 16:57 fe80__a94_efff_fe3a_63bf
drwxrwxrwx  3 nobody nobody      92 Oct  9 16:57 fe80__e98c_ba48_c203_5426
-rwxrwxrwx  1 nobody nobody   22296 Oct  9 16:57 HTTP.rrd
-rwxrwxrwx  1 nobody nobody   22296 Oct  9 16:57 ICMP.rrd
-rwxrwxrwx  1 nobody nobody   22296 Oct  9 16:57 LLMNR.rrd
drwxrwxrwx  2 nobody nobody      52 Oct  9 16:10 localstats
-rwxrwxrwx  1 nobody nobody   22296 Oct  9 16:57 Lync.rrd
-rwxrwxrwx  1 nobody nobody   22296 Oct  9 16:57 NetBIOS.rrd
-rwxrwxrwx  1 nobody nobody   22296 Oct  9 16:57 NetFlow.rrd
-rwxrwxrwx  1 nobody nobody   22296 Oct  9 16:57 NTP.rrd
-rwxrwxrwx  1 nobody nobody  711192 Oct  9 16:58 num_devices.rrd
-rwxrwxrwx  1 nobody nobody  711192 Oct  9 16:58 num_flows.rrd
-rwxrwxrwx  1 nobody nobody  711192 Oct  9 16:58 num_hosts.rrd
-rwxrwxrwx  1 nobody nobody  711192 Oct  9 16:58 num_http_hosts.rrd
-rwxrwxrwx  1 nobody nobody 1057000 Oct  9 16:58 packets.rrd
-rwxrwxrwx  1 nobody nobody   22296 Oct  9 16:35 QQ.rrd
-rwxrwxrwx  1 nobody nobody   22296 Oct  9 16:57 SSH.rrd
-rwxrwxrwx  1 nobody nobody   22296 Oct  9 16:57 SSL.rrd
-rwxrwxrwx  1 nobody nobody   22296 Oct  9 16:57 Unknown.rrd

**Comment by Fouadata** [comment]
I removed the --enterprise line from CONF file.

**Comment by simonemainardi** [comment]
what if you visit the interface page and select 'all applications'? Do you get the data?

![image](https://user-images.githubusercontent.com/3397663/31659938-0b3f8198-b336-11e7-81d4-e691ae2dd688.png)

**Comment by Fouadata** [comment]
![image](https://user-images.githubusercontent.com/32652862/31660577-97610126-b316-11e7-9840-a763759e90c5.png)
 NOthing in there for both interfaces that i use.

**Comment by simonemainardi** [comment]
any chance to get remote access to the box? If yes, please send login credentials to mainardi ntop org

**Comment by Fouadata** [comment]
will send you teamviewer to my machine.

**Comment by simonemainardi** [comment]
Thanks for providing access. It turned out to be an issue with RRD files permissions. Safe to close now.
