### ISSUE TITLE
Page "/lua/banned_site.lua" was not found

### ISSUE THREAD

**Issue by Alestor** [ntop/ntopng#1519]
Hello,

i did a upgrade of ntop to the latest dev release this morning. So far so good  - after this there were no noticeable issues. Same day a few hours later I get the message "Page "/lua/banned_site.lua" was not found" when try to browse the webgui by using a DNS Name. Using the IP Address instead the DNS Name works normal.

ntopng Professional Edition v.3.1.171014

**Comment by Alestor** [comment]
Ok, I did a upgrade to  v.3.1.171015 today and everything works normal again.

**Comment by simonemainardi** [comment]
thanks for reporting. Issue is indeed fixed now.
