### ISSUE TITLE
--packet-filter option seems to be ignored

### ISSUE THREAD

**Issue by ummeegge** [ntop/ntopng#1520]
Dear ntopng developers,
i have recently build ntopng v.3.1.171006 community edition for IPFire systems which makes a very good impression until now but i have encounter a problem with the '--packet-filter' option whereby the main focus was to filter out Multi- Broadcast, IPv6 but also the ntopng webinterface entries. Have tried it with the following entries,

`
--packet-filter="ip and not proto ipv6 and not ether host ff:ff:ff:ff:ff:ff and not net (224.0.0.0/8 or 239.0.0.0/8) and not (host 192.168.200.1 and port 3001)"
`
and also
`
--packet-filter "ip and not ip multicast and not ether broadcast and not (host 192.168.200.1 and port 3001)"
`
whereby 192.168.200.1 is the green0 interface (IPFire definition for the LAN interface)

My whole configuration looks like this:

```

--https-port 192.168.200.1:3001

--data-dir /var/nst/ntopng

--redis 127.0.0.1:6379@03

--dns-mode 1

--disable-autologout

--disable-alerts

--daemon

--community

--user ntopng

--local-networks 192.168.100.0/255.255.255.0,192.168.200.0/255.255.255.0,192.168.150.0/255.255.255.0

--interface blue0
--interface green0
--interface red0
--interface tun0
--interface tun1

--packet-filter "ip and not ip multicast and not ether broadcast and not (host 192.168.200.1 and port 3001)"

```

Haven´t found any log entries regarding PcapInterface errors .

Have get also feedback from another ntopng on IPFire user that the '--packet-filter' option did work with ntopng-3.0 version without problems. May Something has been changed with the new dev version what i haven´t find until now.
It might be great if you have a hint for me if i have somewhere a miss configuration, i have simply overseen something or if we have find a bug.

Thank you. Best regards,

Erik

**Comment by simonemainardi** [comment]
@ummeegge I can confirm the issue is already fixed. Please, update ntopng and it will work again.

Thanks for reporting, though.

**Comment by ummeegge** [comment]
@simonemainardi  thank you for your fast response. Am stuck currently to compile the new version but i will address this on another issue. Thanks again.

Best regards,

Erik
