### ISSUE TITLE
Can't make ntopng due to error in NetworkInterface.cpp:4456 Error 1

### ISSUE THREAD

**Issue by adam543201** [ntop/ntopng#1523]
/usr/src/ntopng# ./autogen.sh
---------------------------------------------------
/usr/src/ntopng# ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for nDPI... found in ../nDPI
checking for ../nDPI/src/lib/.libs/libndpi.a... found ../nDPI/src/lib/.libs/libndpi.a
checking for ntopng professional edition... not found
checking for pcap_open_live in -lpcap... yes
checking for nfct_open in -lnetfilter_conntrack... no
checking for cap_get_proc in -lcap... yes
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking libnetfilter_queue/libnetfilter_queue.h usability... yes
checking libnetfilter_queue/libnetfilter_queue.h presence... yes
checking for libnetfilter_queue/libnetfilter_queue.h... yes
checking for nfq_create_queue in -lnetfilter_queue... yes
checking for nfnl_rcvbufsiz in -lnfnetlink... yes
checking for nfq_set_verdict2... yes
checking for cap_get_proc in -lcap... (cached) yes
checking for ldap_initialize in -lldap... yes
checking for nl_handle_alloc in -lnl... no
checking for clock_gettime in -lrt... yes
checking for zlibVersion in -lz... yes
checking for dlopen in -ldl... yes
checking for curl_easy_perform in -lcurl... yes
checking for GeoIP_record_by_ipnum in -lGeoIP... no
checking GeoIP.h usability... no
checking GeoIP.h presence... no
checking for GeoIP.h... no
Build ntop without geolocation - GeoIP (http://www.maxmind.com/)
checking for sqlite3_open in -lsqlite3... yes
checking for mariadb_config... no
checking for mysql_config... mysql_config
checking for main in -lwrap... yes
./configure: line 4975: test: kali-rolling: integer expression expected
configure: creating ./config.status
config.status: creating packages/ntopng.spec
config.status: creating packages/ntopng-data.spec
config.status: creating Makefile
config.status: creating doc/doxygen.conf
config.status: creating include/config.h
config.status: include/config.h is unchanged

You are now ready to compile typing make
---------------------------------------------------------------

g++  src/TrafficStats.o  src/HostHash.o  src/LocalTrafficStats.o  src/PacketDumper.o  src/VlanHash.o  src/IpAddress.o  src/AutonomousSystem.o  src/Grouper.o  src/TcpFlowStats.o  src/Redis.o  src/MacHash.o  src/FrequentStringItems.o  src/Prefs.o  src/PF_RINGInterface.o  src/NetworkStats.o  src/AddressResolution.o  src/PeriodicActivities.o  src/ICMPstats.o  src/Flashstart.o  src/main.o  src/DB.o  src/Logstash.o  src/VirtualHost.o  src/HTTPstats.o  src/Paginator.o  src/Lua.o  src/PacketStats.o  src/Host.o  src/FrequentTrafficItems.o  src/PcapInterface.o  src/Utils.o  src/ElasticSearch.o  src/Mac.o  src/AutonomousSystemHash.o  src/Trace.o  src/CategoryStats.o  src/GenericHashEntry.o  src/EthStats.o  src/Vlan.o  src/Mutex.o  src/Flow.o  src/HostPools.o  src/nDPIStats.o  src/HTTPserver.o  src/RwLock.o  src/FrequentNumericItems.o  src/NetworkInterface.o  src/AddressTree.o  src/NetworkDiscovery.o  src/PacketDumperTuntap.o  src/VirtualHostHash.o  src/GenericTrafficElement.o  src/AlertsManager.o  src/DivertInterface.o  src/ThreadedActivity.o  src/ExportInterface.o  src/GenericHash.o  src/DnsStats.o  src/HTTPBL.o  src/AlertCounter.o  src/ConditionalVariable.o  src/ParserInterface.o  src/Ntop.o  src/SNMP.o  src/ViewInterface.o  src/CollectorInterface.o  src/GenericHost.o  src/MDNS.o  src/StoreManager.o  src/MySQLDB.o  src/StatsManager.o  src/MacManufacturers.o  src/InterfaceStatsHash.o  src/FlowGrouper.o  src/ProtoStats.o  src/TcpPacketStats.o  src/NtopGlobals.o  src/Geolocation.o  src/FlowHash.o  src/AddressList.o  src/DummyInterface.o  src/ZCCollectorInterface.o  -Wall -L/usr/local/lib -lndpi -lpcap /usr/src/ntopng/third-party/LuaJIT-2.1.0-beta3/src/libluajit.a /usr/src/ntopng/third-party/rrdtool-1.4.8/src/.libs/librrd_th.a -lm -lgobject-2.0 -lgmodule-2.0 -ldl -lglib-2.0  /usr/src/ntopng/third-party/zeromq-4.1.3/.libs/libzmq.a /usr/src/ntopng/third-party/json-c/.libs/libjson-c.a   -lsqlite3 -L/usr/lib/x86_64-linux-gnu  -lmariadbclient -lpthread -lz -lm -ldl -lssl -lssl -lcrypto    -L/usr/local/lib -lcap -lnetfilter_queue -lnfnetlink -lcap -lldap -llber -lrt -lz -ldl -lcurl  -lm -lpthread -o ntopng
src/NetworkInterface.o: In function `NetworkInterface::setnDPIProtocolCategory(unsigned short, ndpi_protocol_category_t)':
/usr/src/ntopng/src/NetworkInterface.cpp:4456: undefined reference to `ndpi_set_proto_category'
collect2: error: ld returned 1 exit status
Makefile:159: recipe for target 'ntopng' failed
make: *** [ntopng] Error 1

i've been trying to work on this for awhile, i cant seem to figure it out.

**Comment by simonemainardi** [comment]
your nDPI is outdated and is not aligned with the ntopng code. Please, follow the instructions at https://github.com/ntop/ntopng/blob/dev/doc/README.compilation

**Comment by adam543201** [comment]
how did you figure that, just curious cause i did everything exact and got the same message

**Comment by adam543201** [comment]
g++ -g -Wall -I/root/ntopng -I/root/ntopng/include -I/usr/local/include -D_FILE_OFFSET_BITS=64 -I/usr/include/hiredis -I/usr/include/hiredis -I/root/ntopng/third-party/mongoose -I/root/ntopng/third-party/json-c  -I/usr/local/include/libndpi-2.1.0/libndpi -I/root/ntopng/third-party/LuaJIT-2.1.0-beta3/src   -I/usr/include/mariadb -I/usr/include/mariadb/mysql  -I/root/ntopng -I/root/ntopng/include -I/usr/local/include -I/root/ntopng/third-party/http-client-c/src/  -I/usr/include/openssl  -DDATA_DIR='"/usr/local/share"' -I/root/ntopng/third-party/libgeohash -I/root/ntopng/third-party/patricia   -c src/AddressList.cpp -o src/AddressList.o
g++  src/AlertCounter.o  src/Geolocation.o  src/GenericHost.o  src/Mac.o  src/PcapInterface.o  src/AutonomousSystemHash.o  src/TrafficStats.o  src/CategoryStats.o  src/LocalTrafficStats.o  src/PacketDumper.o  src/FlowHash.o  src/EthStats.o  src/StoreManager.o  src/VlanHash.o  src/GenericHash.o  src/DnsStats.o  src/DB.o  src/ZCCollectorInterface.o  src/MacManufacturers.o  src/PacketStats.o  src/IpAddress.o  src/AutonomousSystem.o  src/FlowGrouper.o  src/TcpFlowStats.o  src/Mutex.o  src/Flow.o  src/Redis.o  src/MacHash.o  src/HostPools.o  src/HTTPserver.o  src/FrequentStringItems.o  src/Grouper.o  src/FrequentNumericItems.o  src/NetworkInterface.o  src/MDNS.o  src/ViewInterface.o  src/Prefs.o  src/PacketDumperTuntap.o  src/VirtualHostHash.o  src/PF_RINGInterface.o  src/NetworkStats.o  src/RwLock.o  src/Lua.o  src/AddressResolution.o  src/GenericTrafficElement.o  src/PeriodicActivities.o  src/AlertsManager.o  src/Host.o  src/DummyInterface.o  src/Flashstart.o  src/DivertInterface.o  src/main.o  src/ExportInterface.o  src/Vlan.o  src/Logstash.o  src/VirtualHost.o  src/Ntop.o  src/HTTPBL.o  src/ProtoStats.o  src/ConditionalVariable.o  src/HostHash.o  src/ParserInterface.o  src/NetworkDiscovery.o  src/SNMP.o  src/HTTPstats.o  src/Paginator.o  src/GenericHashEntry.o  src/AddressTree.o  src/ICMPstats.o  src/MySQLDB.o  src/CollectorInterface.o  src/Trace.o  src/InterfaceStatsHash.o  src/ThreadedActivity.o  src/FrequentTrafficItems.o  src/nDPIStats.o  src/TcpPacketStats.o  src/StatsManager.o  src/Utils.o  src/NtopGlobals.o  src/ElasticSearch.o  src/AddressList.o  -Wall -L/usr/local/lib -lndpi -lpcap /root/ntopng/third-party/LuaJIT-2.1.0-beta3/src/libluajit.a -lrrd  -lzmq /root/ntopng/third-party/json-c/.libs/libjson-c.a  -lhiredis -lhiredis -lsqlite3 -L/usr/lib/x86_64-linux-gnu -lmariadb -lssl -lssl -lcrypto  -lGeoIP  -L/usr/local/lib -lpfring -lpcap -lnetfilter_conntrack -lcap -lnetfilter_queue -lnfnetlink -lcap -lldap -llber -lrt -lz -ldl -lcurl  -lm -lpthread -o ntopng
/usr/bin/ld: warning: libssl.so.1.0.2, needed by /usr/lib/x86_64-linux-gnu/libcurl.so, may conflict with libssl.so.1.1
/usr/bin/ld: warning: libssl.so.1.0.2, needed by /usr/lib/x86_64-linux-gnu/libcurl.so, may conflict with libssl.so.1.1
/usr/bin/ld: warning: libcrypto.so.1.0.2, needed by /usr/lib/x86_64-linux-gnu/libcurl.so, may conflict with libcrypto.so.1.1
src/NetworkInterface.o: In function `NetworkInterface::setnDPIProtocolCategory(unsigned short, ndpi_protocol_category_t)':
/root/ntopng/src/NetworkInterface.cpp:4456: undefined reference to `ndpi_set_proto_category'
collect2: error: ld returned 1 exit status
Makefile:159: recipe for target 'ntopng' failed
make: *** [ntopng] Error 1

**Comment by simonemainardi** [comment]
you have an outdated version of nDPI installed in `/usr/local/include/libndpi-2.1.0/libndpi` please make sure to remove any installed version and only rely with the source nDPI
