### ISSUE TITLE
How to setup nProbe and ntopng on 2 different servers

### ISSUE THREAD

**Issue by Karrun** [ntop/ntopng#1524]
Hi,

I have ntopng running on a server (iMac) and nProbe on a different server (RHEL 7).

Currently I am starting ntopng by running,
     ntopng -i tcp://<iMac IP>:5556 -e
and the UI can be reached only from iMac as the URL is http://127.0.0.1:3000 (default)

Q1: How can I run URL on a IPv4 address so other people on my team can also view the page from anywhere and not just when logged into the iMac?
Q2: How can export the sFlow data that nProbe is collecting (as it running in collector-mode)?

Any help is much appreciated.

Thanks.

**Comment by emanuele-f** [comment]
Hi, if you want others to access your ntopng installation, you only need to give them your ip address (public or private). See `ifconfig` for private address. E.g. `http://192.168.1.10:3000`.

For ntopng - nprobe communication, please check out our user guide https://github.com/ntop/ntopng/blob/dev/doc/UserGuide.pdf and http://www.ntop.org/nprobe/advanced-flow-collection-with-ntopng-and-nprobe/
