### ISSUE TITLE
sFlow analysis issue

### ISSUE THREAD

**Issue by Entinux** [ntop/ntopng#1525]
We are facing some problem in proving the sFlow analysis part in nTop is working improperly.

Please help forwarding the following inquiry to your support staff :

After running for about 10 hours, the core switch is indeed giving sFlow data to nProbe -> nTop.

<img width="1056" alt="image1" src="https://user-images.githubusercontent.com/32905008/31750102-752e8966-b4b0-11e7-949e-0b978751522b.png">

Some hosts and traffic is logged.

<img width="1042" alt="image2" src="https://user-images.githubusercontent.com/32905008/31750129-96381e42-b4b0-11e7-869f-84e978eda008.png">

<img width="1042" alt="image3" src="https://user-images.githubusercontent.com/32905008/31750138-9f4935ac-b4b0-11e7-91b8-a796e9788f59.png">

However all ports (for all hosts) are marked as 'others'

<img width="709" alt="image4" src="https://user-images.githubusercontent.com/32905008/31750165-d0e9e3b8-b4b0-11e7-8098-1169eb584561.png">

No Peer

<img width="1092" alt="image5" src="https://user-images.githubusercontent.com/32905008/31750194-107ca286-b4b1-11e7-9c3b-639b7b4035c4.png">

Nothing in protocol view
<img width="1084" alt="image6" src="https://user-images.githubusercontent.com/32905008/31750196-146bcb42-b4b1-11e7-8ed4-d8c8665461df.png">

No Flow

<img width="1149" alt="image7" src="https://user-images.githubusercontent.com/32905008/31750218-31696ff6-b4b1-11e7-967b-7f4e5ec89a48.png">

We are running nProbe with

 nprobe --collector-port 6343 --zmq tcp://127.0.0.1:1234 -i none -n none --verbose 2 --dump-stats /tmp/nprobe.log -nf -V5 -b 2

and it looks that the flow traffic gathered is normal.

18/Oct/2017 18:19:54 [engine.c:2887] Emitting Flow: [->][tcp] 192.168.2.52:80 -> 192.168.1.32:51656 [1 pkt/550 bytes][ifIdx 31->14][0.0 sec][VLAN 1/1][init Unknown][AS: 0 -> 0]
18/Oct/2017 18:19:57 [engine.c:2689] New Flow: [tcp] 192.168.11.22:58910 -> 192.168.90.20:443 [44:37:E6:53:C7:77 -> 00:2A:10:9A:A2:21][vlan 1/1][tos 0][ifIdx: 62 -> 63][subflowId: 0/0x0000][idx=11079][firstSeen=1508321997/0][direction: RX]
18/Oct/2017 18:19:58 [engine.c:2887] Emitting Flow: [->][tcp] 192.168.1.124:32659 -> 192.168.2.238:3260 [2 pkt/1972 bytes][ifIdx 46->63][0.0 sec][VLAN 1/1][init Unknown][AS: 0 -> 0]
18/Oct/2017 18:20:10 [engine.c:2689] New Flow: [udp] 192.168.11.107:60504 -> 239.255.255.250:3702 [44:37:E6:C0:F5:3B -> 01:00:5E:7F:FF:FA][vlan 1/1][tos 0][ifIdx: 30 -> 63][subflowId: 0/0x0000][idx=51220][firstSeen=1508322010/0][direction: RX]
18/Oct/2017 18:20:12 [engine.c:2689] New Flow: [tcp] 192.168.1.124:32659 -> 192.168.2.238:3260 [00:50:56:69:94:02 -> 00:11:32:30:98:09][vlan 1/1][tos 0][ifIdx: 46 -> 63][subflowId: 0/0x0000][idx=74885][firstSeen=1508322012/0][direction: RX]
18/Oct/2017 18:20:12 [engine.c:2689] New Flow: [tcp] 192.168.2.238:3260 -> 192.168.1.123:49748 [00:11:32:30:98:09 -> 00:50:56:63:5A:F4][vlan 1/1][tos 0][ifIdx: 63 -> 14][subflowId: 0/0x0000][idx=34897][firstSeen=1508322012/0][direction: RX]
18/Oct/2017 18:20:14 [engine.c:2887] Emitting Flow: [->][tcp] 192.168.2.52:80 -> 192.168.1.32:51685 [1 pkt/1500 bytes][ifIdx 31->14][0.0 sec][VLAN 1/1][init Unknown][AS: 0 -> 0]
18/Oct/2017 18:20:28 [engine.c:2887] Emitting Flow: [->][tcp] 192.168.11.22:58910 -> 192.168.90.20:443 [1 pkt/194 bytes][ifIdx 62->63][0.0 sec][VLAN 1/1][init Unknown][AS: 0 -> 0]
18/Oct/2017 18:20:34 [engine.c:2689] New Flow: [tcp] 192.168.2.52:80 -> 192.168.1.32:51761 [1C:7D:22:1A:FF:21 -> 00:50:56:8C:16:34][vlan 1/1][tos 0][ifIdx: 31 -> 14][subflowId: 0/0x0000][idx=19449][firstSeen=1508322034/0][direction: RX]
18/Oct/2017 18:20:40 [engine.c:2887] Emitting Flow: [->][udp] 192.168.11.107:60504 -> 239.255.255.250:3702 [1 pkt/804 bytes][ifIdx 30->63][0.0 sec][VLAN 1/1][init Unknown][AS: 0 -> 0]
18/Oct/2017 18:20:46 [engine.c:2689] New Flow: [tcp] 192.168.11.172:51640 -> 192.168.90.20:443 [00:21:86:28:D5:D7 -> 00:2A:10:9A:A2:21][vlan 1/1][tos 0][ifIdx: 30 -> 31][subflowId: 0/0x0000][idx=47791][firstSeen=1508322046/0][direction: RX]
18/Oct/2017 18:20:50 [engine.c:2887] Emitting Flow: [->][tcp] 192.168.1.124:32659 -> 192.168.2.238:3260 [5 pkt/3156 bytes][ifIdx 46->63][0.0 sec][VLAN 1/1][init Unknown][AS: 0 -> 0]
18/Oct/2017 18:20:50 [engine.c:2914] Emitting Flow: [<-][tcp] 192.168.2.238:3260 -> 192.168.1.124:32659 [6 pkt/9000 bytes][ifIdx 63->46][0.0 sec][VLAN 1/1][AS: 0 -> 0]
18/Oct/2017 18:20:52 [engine.c:2689] New Flow: [tcp] 192.168.1.124:32659 -> 192.168.2.238:3260 [00:50:56:69:94:02 -> 00:11:32:30:98:09][vlan 1/1][tos 0][ifIdx: 46 -> 63][subflowId: 0/0x0000][idx=74885][firstSeen=1508322052/0][direction: RX]
18/Oct/2017 18:21:05 [engine.c:2887] Emitting Flow: [->][tcp] 192.168.2.52:80 -> 192.168.1.32:51761 [1 pkt/1500 bytes][ifIdx 31->14][0.0 sec][VLAN 1/1][init Unknown][AS: 0 -> 0]
18/Oct/2017 18:21:17 [engine.c:2887] Emitting Flow: [->][tcp] 192.168.11.172:51640 -> 192.168.90.20:443 [1 pkt/40 bytes][ifIdx 30->31][0.0 sec][VLAN 1/1][init Unknown][AS: 0 -> 0]
18/Oct/2017 18:21:22 [engine.c:2887] Emitting Flow: [->][tcp] 192.168.1.124:32659 -> 192.168.2.238:3260 [2 pkt/3000 bytes][ifIdx 46->63][0.0 sec][VLAN 1/1][init Unknown][AS: 0 -> 0]
18/Oct/2017 18:21:22 [engine.c:2914] Emitting Flow: [<-][tcp] 192.168.2.238:3260 -> 192.168.1.124:32659 [5 pkt/6964 bytes][ifIdx 63->46][0.0 sec][VLAN 1/1][AS: 0 -> 0]
18/Oct/2017 18:21:22 [engine.c:2887] Emitting Flow: [->][tcp] 192.168.2.238:3260 -> 192.168.1.123:49748 [13 pkt/19500 bytes][ifIdx 63->14][0.0 sec][VLAN 1/1][init Unknown][AS: 0 -> 0]
18/Oct/2017 18:21:22 [engine.c:2914] Emitting Flow: [<-][tcp] 192.168.1.123:49748 -> 192.168.2.238:3260 [2 pkt/3000 bytes][ifIdx 14->63][0.0 sec][VLAN 1/1][AS: 0 -> 0]
18/Oct/2017 18:21:28 [engine.c:2689] New Flow: [tcp] 192.168.11.9:54118 -> 192.168.90.20:443 [70:F3:95:17:22:48 -> 00:2A:10:9A:A2:21][vlan 1/1][tos 0][ifIdx: 30 -> 31][subflowId: 0/0x0000][idx=79842][firstSeen=1508322088/0][direction: RX]
18/Oct/2017 18:21:42 [engine.c:2689] New Flow: [tcp] 192.168.11.60:55404 -> 42.120.230.1:80 [00:16:41:EE:54:90 -> 34:B3:54:10:B5:42][vlan 1/1][tos 0][ifIdx: 31 -> 16][subflowId: 0/0x0000][idx=127713][firstSeen=1508322102/0][direction: RX]
18/Oct/2017 18:21:46 [engine.c:2689] New Flow: [tcp] 184.84.48.243:80 -> 192.168.11.60:55401 [00:90:7F:D4:41:DB -> 00:16:41:EE:54:90][vlan 1/1][tos 0][ifIdx: 16 -> 31][subflowId: 0/0x0000][idx=81324][firstSeen=1508322106/0][direction: RX]
18/Oct/2017 18:21:47 [engine.c:2689] New Flow: [tcp] 192.168.2.238:3260 -> 192.168.1.123:49748 [00:11:32:30:98:09 -> 00:50:56:63:5A:F4][vlan 1/1][tos 0][ifIdx: 63 -> 14][subflowId: 0/0x0000][idx=34897][firstSeen=1508322107/0][direction: RX]
18/Oct/2017 18:21:47 [engine.c:2689] New Flow: [tcp] 184.84.48.243:80 -> 192.168.11.60:55398 [00:90:7F:D4:41:DB -> 00:16:41:EE:54:90][vlan 1/1][tos 0][ifIdx: 16 -> 31][subflowId: 0/0x0000][idx=81285][firstSeen=1508322107/0][direction: RX]
18/Oct/2017 18:21:47 [engine.c:2689] New Flow: [tcp] 184.84.48.243:80 -> 192.168.11.60:55394 [00:90:7F:D4:41:DB -> 00:16:41:EE:54:90][vlan 1/1][tos 0][ifIdx: 16 -> 31][subflowId: 0/0x0000][idx=81233][firstSeen=1508322107/0][direction: RX]
18/Oct/2017 18:21:47 [engine.c:2689] New Flow: [tcp] 184.84.48.243:80 -> 192.168.11.60:55400 [00:90:7F:D4:41:DB -> 00:16:41:EE:54:90][vlan 1/1][tos 0][ifIdx: 16 -> 31][subflowId: 0/0x0000][idx=81311][firstSeen=1508322107/0][direction: RX]
18/Oct/2017 18:21:48 [engine.c:2689] New Flow: [tcp] 184.84.48.243:80 -> 192.168.11.60:55399 [00:90:7F:D4:41:DB -> 00:16:41:EE:54:90][vlan 1/1][tos 0][ifIdx: 16 -> 31][subflowId: 0/0x0000][idx=81298][firstSeen=1508322108/0][direction: RX]
18/Oct/2017 18:21:48 [engine.c:2689] New Flow: [tcp] 184.84.48.243:80 -> 192.168.11.60:55397 [00:90:7F:D4:41:DB -> 00:16:41:EE:54:90][vlan 1/1][tos 0][ifIdx: 16 -> 31][subflowId: 0/0x0000][idx=81272][firstSeen=1508322108/0][direction: RX]
18/Oct/2017 18:21:58 [engine.c:2887] Emitting Flow: [->][tcp] 192.168.11.9:54118 -> 192.168.90.20:443 [1 pkt/130 bytes][ifIdx 30->31][0.0 sec][VLAN 1/1][init Unknown][AS: 0 -> 0]

* * *

The port numbers are here, and frequently we are seeing things like to <-> from port 80, which should be web traffic). We have purchased and activated the license for MAIL and HTTP plugin in nProbe.

Please kindly advise and let us know any clue on this. Thank you.

**Comment by simonemainardi** [comment]
If you are collection sFlow, please use nProbe option `--upscale-traffic` to adjust bytes/packets quantities to reasonable levels.

Also, remove nProbe option `-nf` that doesn't exist.

I would also use nProbe option `-V10` rather than `-V5` to make sure flows are reported as bi-directional.

Please, report.

**Comment by simonemainardi** [comment]
Solution given, no feedback received. Closing.
