### ISSUE TITLE
Starting ntopng:awk: write failure (Broken pipe)

### ISSUE THREAD

**Issue by fanr10** [ntop/ntopng#1527]
● ntopng.service - Start/stop ntopng program
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled)
   Active: active (running) since Thu 2017-10-19 12:59:00 -02; 8s ago
  Process: 20559 ExecStart=/etc/init.d/ntopng start (code=exited, status=0/SUCCESS)
 Main PID: 20575 (ntopng)
   CGroup: /system.slice/ntopng.service
           └─20575 /usr/bin/ntopng /etc/ntopng/ntopng.conf

Oct 19 12:58:55 JCNBA10-A03 systemd[1]: Starting Start/stop ntopng program...
Oct 19 12:58:55 JCNBA10-A03 ntopng[20559]: Generating configuration file /etc/ntopng/ntopng.conf
Oct 19 12:58:55 JCNBA10-A03 ntopng[20575]: [NtopPro.cpp:241] WARNING: [LICENSE] Invalid or missing license
Oct 19 12:58:55 JCNBA10-A03 ntopng[20575]: [NtopPro.cpp:253] WARNING: [LICENSE] ntopng will now run...utes
Oct 19 12:58:55 JCNBA10-A03 ntopng[20575]: [NtopPro.cpp:255] WARNING: [LICENSE] before returning to...mode
Oct 19 12:58:55 JCNBA10-A03 ntopng[20575]: [NtopPro.cpp:256] WARNING: [LICENSE] You can buy a perma....org
Oct 19 12:58:55 JCNBA10-A03 ntopng[20575]: [NtopPro.cpp:257] WARNING: [LICENSE] or run ntopng in co...ting
Oct 19 12:58:55 JCNBA10-A03 ntopng[20575]: [NtopPro.cpp:258] WARNING: [LICENSE] ntopng --community
Oct 19 12:58:59 JCNBA10-A03 ntopng[20559]: Starting ntopng:awk: write failure (Broken pipe)
Oct 19 12:58:59 JCNBA10-A03 ntopng[20559]: awk: close failed on file /dev/stdout (Broken pipe)
Oct 19 12:58:59 JCNBA10-A03 ntopng[20559]: grep: write error
Oct 19 12:58:59 JCNBA10-A03 ntopng[20559]: grep: write error
Oct 19 12:59:00 JCNBA10-A03 ntopng[20559]: Unable to start ntopng ... failed!
Oct 19 12:59:00 JCNBA10-A03 ntopng[20559]: failed!
Oct 19 12:59:00 JCNBA10-A03 systemd[1]: Started Start/stop ntopng program.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by emanuele-f** [comment]
Hi, what is your linux distribution and ntopng version used? Can you reproduce it with latest ntopng version?

**Comment by simonemainardi** [comment]
@fanr10 any news?

**Comment by lucaderi** [comment]
This does not look like a package issue but rather a system issue (for instance disk full).
Closed for inactivity, will reopen if necessary.
