### ISSUE TITLE
How would you go about setting up ntopng on an x86 Synology NAS?

### ISSUE THREAD

**Issue by edasque** [ntop/ntopng#1530]
Right now I am trying cross-compiling to Synology via spksrc but it seems a tall order.

ntopng running in docker with nprobe gathering stats? But then how do I get nprobe on Synology, seems I can't x-compile, source isn't available for nprobe, right?

Cheers,

Erik

**Comment by simonemainardi** [comment]
@edasque running and nprobe running in docker is OK.

no nprobe source code is available so building it from source is not an option.

If you are planning to use licensed ntopng and nprobe versions on docker, then you just have to make sure the underlying hardware exposed through the container does not change. This is to make sure licenses, that are bound to the hardware, will continue to work.

**Comment by edasque** [comment]
@simonemainardi if everything is hosted into a container, won’t I be getting the container network activity versus the host?

**Comment by simonemainardi** [comment]
no, you can expose the host network to the docker container with `docker run --net=host ...`

**Comment by edasque** [comment]
Thank you, got a decent 3.1.x image going - https://hub.docker.com/r/edasque/docker-ntopng/
