### ISSUE TITLE
[ARMHF] Unable to delete flow alerts and past alerts.

### ISSUE THREAD

**Issue by filemoon** [ntop/ntopng#1534]
Hi,

I still have very same number of flow alerts and past alerts - I cannot delete them (deletion process looks ok but alerts are still there).

**Comment by emanuele-f** [comment]
Hi, what ntopng are you using? Can't you delete single alerts or "flush all" alerts?

**Comment by simonemainardi** [comment]
duplicate of #1517
please check before posting new issues
