### ISSUE TITLE
Update issues on CentOS with ntop repo

### ISSUE THREAD

**Issue by tsri-network** [ntop/ntopng#1536]
I've now had the same problem happen twice with updates from the ntop CentOS repository:

We have ntopng & nprobe installed using the CentOS repository as provided by ntop, described at the top of http://packages.ntop.org/.  The repo had updates available for all ntopng components, so I shut down all the related services just to be safe (nprobe, ntopng, mysql/mariadb), then ran "yum update".  Everything went in without complaint.  I then rebooted to be safe.  Each time I have updated, suddenly the one ZMQ interface I have configured (127.0.0.1:5556) now has below it an additional line for each SNMP IFindex number of every switch port we have (hundreds).  Although there is live data displayed, there is no new historical data being saved.

Since we're testing the software, last time what fixed this was to run redis-cli with the 'flushdb' and 'flushall' commands.  This eliminated the extra interface lines and ntopng started collecting data again.  Then another update is available, and the problem starts over.  This time I haven't reset anything pending any results from this post.

We have the Enterprise version of ntopng running on CentOS 7.4.  nprobe and ntopng are the versions in the repo, which currently is 3.0.171020.  I don't know the versions of each previous release that was updated.

Attaching images of the interfaces portion of the screen.  Note that I have only one single listener/collector process currently configured and running.

![ntop-interfaces2](https://user-images.githubusercontent.com/30602621/31971617-62c673cc-b8d1-11e7-984e-716c604f0e5c.png)

![ntop-interfaces](https://user-images.githubusercontent.com/30602621/31971476-da070fc4-b8d0-11e7-917c-ee68f8033f77.png)

**Comment by emanuele-f** [comment]
Hi, please check out the `Disaggregation Criterion` under the `Network Interfaces` section of the ntopng advanced preferences. If you do not want disaggreagation, please set it to "None".

**Comment by tsri-network** [comment]
That was set to a non-default option--thanks for the info.  Why would this problem only arise after updates?  It's been running, rebooted, restarted numerous times before the update, but this only happens after applying updates (for us).

**Comment by emanuele-f** [comment]
It may happen if ntopng is not termined properly after the preference change, although this would not be your case. Please try to shutdown and restart ntopng now that it is set and verify if it's still set to the correct preference. If you still experience the problem after an upgrade, please open a new bug.
