### ISSUE TITLE
How can we get Historical data view in Community edition?

### ISSUE THREAD

**Issue by pleoeter** [ntop/ntopng#1537]
I want to see my data history in ntopng after successful connection with mysql, Is it possible in community edition? if so please post the procedure.

**Comment by emanuele-f** [comment]
Hi, with community edition you can only access the `flows` tab under the host graphs page to see the raw flows. With lincensed version, you get more advanced features like filters and drill-downs. Please see the following links fore more information:

http://www.ntop.org/products/traffic-analysis/ntop/ 
http://www.ntop.org/ntopng/exploring-historical-data-using-ntopng-part-2/
http://www.ntop.org/products/traffic-analysis/ntop/

**Comment by pleoeter** [comment]
you mean no other mean to view historical data in community edition?
I have seen the links though

**Comment by emanuele-f** [comment]
Exactly. Historical data exploration is only available starting with pro licence.

**Comment by pleoeter** [comment]
Ok, I am trying Elastic Search now, please help me solving the error

 [Utils.cpp:985] WARNING: Unable to post data to (https://localhost:9200/_template/ntopng_template): SSL connect error
[ElasticSearch.cpp:230] ERROR: Unable to send ntopng template (/root/ntopng/httpdocs/misc/ntopng_template_elk.json) to ES

**Comment by pleoeter** [comment]
I have solved it using
 ntopng -F 'es;ntopng;ntopng-%Y.%m.%d;http://localhost:9200/_bulk;http_ntopng:ntopng;'

Thanks
