### ISSUE TITLE
No protocol graph in grafana

### ISSUE THREAD

**Issue by tomarch** [ntop/ntopng#1538]
I've setup grafana plugin, bandwith and PPS work fine but protocol one don't work.

I use lastest ntopng (yum nightlies).

**Comment by simonemainardi** [comment]
please, make sure to enable local hosts timeseries generation from ntopng preferences:

![image](https://user-images.githubusercontent.com/3397663/31990565-c4c0fed6-b975-11e7-92bc-dffb407bee83.png)

Also please use https://github.com/ntop/ntopng-grafana-datasource for grafana-related issues
