### ISSUE TITLE
"Top Application Traffic Last Day View" -> empty

### ISSUE THREAD

**Issue by mahescho** [ntop/ntopng#1541]
Hi,

on one of my setups "Top Application Traffic Last Day View" stays empty. Why?

Version: ntopng Professional Edition v.3.1.171014

TIA
Matthias

**Comment by simonemainardi** [comment]
Mathias, can you please, update to the latest 3.1 version and report? Your issue should already be fixed. Please, report.

**Comment by mahescho** [comment]
Now I'm on "ntopng Professional Edition v.3.1.171030" (updated right now) and nothing changed.

Edit: I monitor 2 interfaces. One shows top applications last day view and the other does not.

**Comment by simonemainardi** [comment]
@mahescho can you right-click on the browser, select "Inspector", and reload the page? Are you seeing any JS/script error in the console?

**Comment by emanuele-f** [comment]
@mahescho do you still experience the issue?

**Comment by emanuele-f** [comment]
@mahescho please follow the following steps:

1) select the ntopng interface from the ntopng gui
2) Into the interface page, note the id  (say 7) of your network interface.
3) Then go into the ntopng preferences and post a screenshot of the Timeseries settings
4) What are the contents of the directory `/var/tmp/ntopng/7/` (7 is the interface id as stated previously)?

**Comment by emanuele-f** [comment]
@mahescho any news?

**Comment by lucaderi** [comment]
Closed for inactivity. Will reopen if necessary.

**Comment by walker333** [comment]
hello,
I have the same problem. I attached a screen capture of the Timeseries settings.
Also the id of my network interface is 3 and the contents of ntpong/3/ are:
drwx------ 2 ntopng ntopng 4096 Sep  5 14:48 alerts
drwx------ 4 ntopng ntopng 4096 Sep  4 16:15 rrd
drwx------ 4 ntopng ntopng 4096 Sep  4 16:11 subnetstats
drwx------ 2 ntopng ntopng 4096 Sep  5 14:48 top_talkers
![Screen Shot 2019-09-05 at 14 46 14](https://user-images.githubusercontent.com/7109506/64339293-595cdb80-cfec-11e9-967f-6535a82f9b8a.jpg)

**Comment by emanuele-f** [comment]
Please open a new issue and specify the output of `ntopng --version`
