### ISSUE TITLE
Latest stable for ubuntu incorrect versions

### ISSUE THREAD

**Issue by madpsy** [ntop/ntopng#1547]
The current stable release manifest contains incorrect versions  (http://packages.ntop.org/apt-stable/16.04/x64/). 

The release file stipulates:

pfring_7.0.0-1515_amd64.de
ntopng_3.0.171027-3628_amd64.deb

Howver, in the repo:

pfring_7.0.0-1535_amd64.deb
nprobe_8.0.171102-5797_amd64.deb

**Comment by lucaderi** [comment]
We have fixed this problem. Thanks for reporting it
