### ISSUE TITLE
No Graphs for some Pools and Traffic Report

### ISSUE THREAD

**Issue by Alestor** [ntop/ntopng#1549]
Hi,

generating a Traffic Report results in a script failure and no charts are shown at all.

04/Nov/2017 06:46:59 [Lua.cpp:7088] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/report.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:1083: /var/ntop/data/2/rrd/192/168/10/0/24/bytes.rrd: expected 2 data source readings (got 1) from 1509772619]

A similar error is shown when I try to visual statistics for some Pools. Not all Pools are affected, some do work.

04/Nov/2017 06:54:07 [Lua.cpp:7088] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pool_details.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:1083: /var/ntop/data/2/host_pools/5/bytes.rrd: expected 2 data source readings (got 1) from 1509773047]
04/Nov/2017 06:53:06 [Lua.cpp:7088] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pool_details.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:1083: /var/ntop/data/2/host_pools/6/bytes.rrd: expected 2 data source readings (got 1) from 1509772986]

ntopng --version
v.3.1.171104    [Enterprise/Professional build]
GIT rev:        dev:5f58bc24c4b1d38456ff4662ffea3254e566de49:20171104
Pro rev:        r1235

**Comment by Alestor** [comment]
Hello,

the issue still persists in the Version I've installed yesterday. 

ntopng --version
v.3.1.171107    [Enterprise/Professional build]
GIT rev:        dev:531a9455b98dd78261ecf92e74a547ced8aead93:20171107
Pro rev:        r1240

Are there more informations needed?

**Comment by Alestor** [comment]
Stable Build isn't affected by this issue. Would appreciate if somebody could take care of this in the dev build.

**Comment by emanuele-f** [comment]
Hi, this is fixed with commit 12c622b96a87e69c9472da0adef1e25ccfac3450. A new build will be available in one hour. Thank you.

**Comment by Alestor** [comment]
Thank you
