### ISSUE TITLE
ntopng exit with segfault error

### ISSUE THREAD

**Issue by jerryzsplunk** [ntop/ntopng#1551]
The ntopng web interface crashes at least once every 10 to 24 hours. I see the below log entries in /var/log/message of ntop server.

Nov  5 07:31:20 ntopng kernel: ntopng[8189]: segfault at 0 ip 0000000000412c07 sp 00007efc53f6ebe0 error 4 in ntopng[400000+271000]
Nov  5 07:31:20 ntopng systemd: ntopng.service: main process exited, code=killed, status=11/SEGV

When crashed, I have to manually restart ntopng by running /etc/init.d/ntopng stop and /etc/init.d/ntopng start to bring it up.

I've always running ntopng at the latest update. And now it's running at 3.1.171104 nightly update.

**Comment by emanuele-f** [comment]
Hi, any chance to generate a core dump or a stack trace with gdb?

**Comment by jerryzsplunk** [comment]
I haven't seen such error any more in the past a few days. In case this error happens again, I will generate a core dump for your investigation

**Comment by emanuele-f** [comment]
Ok, Thank you

**Comment by simonemainardi** [comment]
fixed with https://github.com/ntop/ntopng/commit/b5ad7ebfce523269caec4e4c79ec09cb3df9fd7b
