### ISSUE TITLE
no interface historical data if daemon mode

### ISSUE THREAD

**Issue by dvachon2018** [ntop/ntopng#1552]
hi
if running in daemon mode, (--daemon) there is not data in Interfaces/eth0/(page:historical). No problem without (--daemon)

hardware/software;
CPU load | 1.89%
Used: 4.73% / Available: 1.87 GB / Total: 1.97 GB
3.1.171031 - Professional/Embedded Edition
Debian 9.1 [armv7l][Raspbian GNU/Linux 9.1 (stretch)] - 32 bit
ntopng --pid "/var/run/ntopng.pid" --daemon "" --interface "eth0" --local-networks "192.168.20.0/24" --disable-autologout "" --disable-login "1" --sticky-hosts "all" --user "root" --instance-name "NetworkDV" --dns-mode "1" --https-port "3001"

**Comment by simonemainardi** [comment]
can you post the page Runtime status when in daemon mode? Please, also che the ntopng log file (under /var/log/ntopng)

**Comment by dvachon2018** [comment]
yes
here print screen without daemon;
![2017-11-06 07_57_34-welcome to ntopng](https://user-images.githubusercontent.com/33327149/32442207-8e09dd02-c2c8-11e7-9294-4c24c3bd301b.jpg)

here print screen with daemon;
![2017-11-06 08_01_06-welcome to ntopng](https://user-images.githubusercontent.com/33327149/32442236-b6831302-c2c8-11e7-9d8b-c9d960c3b07b.jpg)

runtime status
![2017-11-06 08_04_22-welcome to ntopng](https://user-images.githubusercontent.com/33327149/32442622-0f6e5d04-c2ca-11e7-9901-f10672e23b39.jpg)

cat /var/log/ntopng/ntopng.log

06/Nov/2017 08:12:41 [Prefs.cpp:955] All HTTP user login disabled
06/Nov/2017 08:12:41 [Ntop.cpp:1437] Setting local networks to 192.168.20.0/24
06/Nov/2017 08:12:41 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:66
379@0
06/Nov/2017 08:12:41 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:66
379@0
06/Nov/2017 08:12:41 [NtopPro.cpp:210] [LICENSE] Reading license from Redis
06/Nov/2017 08:12:41 [NtopPro.cpp:127] [LICENSE] xxxxxxx: unable to validate Enterprise Embedded license [License missmatch error]
06/Nov/2017 08:12:41 [NtopPro.cpp:130] [LICENSE] xxxxx : found valid Professional Embedded license
06/Nov/2017 08:12:41 [Ntop.cpp:1375] Parent process is exiting (this is normal)
~
~
~

**Comment by emanuele-f** [comment]
@dvachon2018 the screenshot shows two different graphs. Can you still reproduce the problem? If so, please send us two screenshot of the same graph.

**Comment by dvachon2018** [comment]
hi, dont now why but working since last build.   3.1.171108

**Comment by emanuele-f** [comment]
Ok, I'm closing the issue for now. Should you experience it again, please reopen. Thank you.
