### ISSUE TITLE
 Missing script housekeeping.lua and second.lua

### ISSUE THREAD

**Issue by Howard-Chang** [ntop/ntopng#1554]
Today, when I start ntopng with the command:
ntopng /c -i "tcp://127.0.0.1:2055" --prefs-dir "C:\Program Files\ntopng\runtimetemp" -F "es;ntopng;ntopng-%Y.%m.%d;http://localhost/_bulk;"
nprobe /c --zmq "tcp://*:2055" -i none -n none --collector-port 5556

It occured warning log on ntopng cmd.
 
06/Nov/2017 11:34:51 [PeriodicActivities.cpp:50] Started periodic activities loop...
06/Nov/2017 11:34:51 [NetworkInterface.cpp:2149] Started packet polling on interface tcp://127.0.0.1:2055 [id: 1]...
06/Nov/2017 11:34:51 [CollectorInterface.cpp:115] Collecting flows on tcp://127.0.0.1:2055
06/Nov/2017 11:34:51 [Lua.cpp:6128] WARNING: Script failure [C:\Program Files\ntopng\scripts\callbacks/second.lua][C:\Program Files\ntopng/scripts/lua/modules/graph_utils.lua:978: short read while reading header rrd->stat_head]
06/Nov/2017 11:34:52 [Lua.cpp:6128] WARNING: Script failure [C:\Program Files\ntopng\scripts\callbacks/second.lua][C:\Program Files\ntopng/scripts/lua/modules/graph_utils.lua:978: short read while reading header rrd->stat_head]
06/Nov/2017 11:34:53 [Lua.cpp:6128] WARNING: Script failure [C:\Program Files\ntopng\scripts\callbacks/second.lua][C:\Program Files\ntopng/scripts/lua/modules/graph_utils.lua:978: short read while reading header rrd->stat_head]

**Comment by Howard-Chang** [comment]
I have check the file, and it didn't missing

**Comment by simonemainardi** [comment]
it seems to be an RRD bug: http://rrd-mailinglists.937164.n2.nabble.com/template/NamlServlet.jtp?macro=search_page&node=937164&query=short+read+while+reading+header+

I would try to stop ntopng, clear the rrd file that is causing the error, and restart it

**Comment by Howard-Chang** [comment]
ok, it can work correctly now!
thanks a lot.

**Comment by emanuele-f** [comment]
Thank you for reporting
