### ISSUE TITLE
ntopng.service: Main process exited after some hours

### ISSUE THREAD

**Issue by dvachon2018** [ntop/ntopng#1555]
ntopng.service: Main process exited, code=killee
d, status=11/SEGV

also, many message like that in log file.

Nov  5 11:25:01 ntop ntopng: [Lua.cpp:6648] WARNING: Script failure [/usr/share//
ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/lua/modules/graph_uu
tils.lua:998: Cannot create temporary file]
Nov  5 11:25:05 ntop kernel: [55423.437916] sunxi-bt bt: block state already is
0

hardware/software;
3.1.171031 - Professional/Embedded Edition
Debian 9.1 [armv7l][Raspbian GNU/Linux 9.1 (stretch)] - 32 bit
ntopng --pid "/var/run/ntopng.pid" --interface "eth0" --local-networks "192.168.20.0/24" --disable-autologout "" --disable-login "1" --sticky-hosts "all" --user "root" --instance-name "NetworkDV" --dns-mode "1" --https-port "3001"

**Comment by emanuele-f** [comment]
Hi, do you have available disk space?

**Comment by dvachon2018** [comment]
yes disk space available
i upgraded to latest arm stretch pi to 3.1.171108 and will test is again

**Comment by emanuele-f** [comment]
OK, Thank you

**Comment by emanuele-f** [comment]
I'm closing the issue for now, please reopen it if necessary
