### ISSUE TITLE
Error:RRD file error in Hosts page:traffic_report

### ISSUE THREAD

**Issue by dvachon2018** [ntop/ntopng#1556]
hardware/software;
3.1.171031 - Professional/Embedded Edition
Debian 9.1 [armv7l][Raspbian GNU/Linux 9.1 (stretch)] - 32 bit
ntopng --pid "/var/run/ntopng.pid" --interface "eth0" --local-networks "192.168.20.0/24" --disable-autologout "" --disable-login "1" --sticky-hosts "all" --user "root" --instance-name "NetworkDV" --dns-mode "1" --https-port "3001"

**Comment by simonemainardi** [comment]
can you please post the full error?

**Comment by dvachon2018** [comment]
here a print screen


[cid:595a978d-d180-429f-8b5c-ed82ace3f9e7]


________________________________
De : simonemainardi <notifications@github.com>
Envoyé : 6 novembre 2017 05:33
À : ntop/ntopng
Cc : dvachon2018; Author
Objet : Re: [ntop/ntopng] Error:RRD file error in Hosts page:traffic_report (#1556)


can you please post the full error?

**Comment by dvachon2018** [comment]
![2017-11-06 07_45_41-welcome to ntopng](https://user-images.githubusercontent.com/33327149/32441790-092af6c6-c2c7-11e7-81d1-f0715795bd9a.jpg)

**Comment by emanuele-f** [comment]
Hi @dvachon2018 , the report works for me with latest version. Please provide a full log, your previous message did not contain it (bacause of email, please use github directly)

**Comment by dvachon2018** [comment]
hi
upgraded to latest arm stretch pi to 3.1.171108 and it is working now.

**Comment by dvachon2018** [comment]
strange, with this new release, /etc/init.d/ntopng does not exist anymore
also, no log file in /var/log/ntopng/   the directory is empty

**Comment by emanuele-f** [comment]
Thank you for reporting. We are migrating to a pure systemd service file, this is why /etc/init.d is empty. Stay tuned.

**Comment by simonemainardi** [comment]
migration is completed, is not in progress. You can control the start/stop ntopng with `systemctl`

**Comment by jult** [comment]
How did you solve this? I get this same error:
Error:RRD file error
when I click Traffic report per host.
Also, the Traffic graph left of that, stays empty, while the flows are there and it's in the Top hosts lists with traffic.
This is on a debian 12 server with ntopng and nprobe.
