### ISSUE TITLE
#1496 #1548 Not solved!

### ISSUE THREAD

**Issue by antoniovalenzuela** [ntop/ntopng#1557]
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
ntopng : Depends: librrd8 but it is not installable
Depends: libzmq5 but it is not installable
Depends: libssl1.1 but it is not installable
Depends: libhiredis0.13 but it is not installable
Recommends: ntopng-data but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

I do not understand your solution ... I have the license, I can not use ntopng/nprobe, with raspberry jessie (x86)

Distributor ID: Raspbian
Description: Raspbian GNU/Linux 8.0 (jessie)
Release: 8.0
Codename: jessie

Before the last updates I had no problems

**Comment by lucaderi** [comment]
Fixed. Will reopen if necessary
