### ISSUE TITLE
invalid rrd DS name in second.lua

### ISSUE THREAD

**Issue by linepoint** [ntop/ntopng#1558]
Line 53: makeRRD(basedir, ifstats.id, "iface", "num_zmq_received_flows", 1, tolongint(ifstats.zmqRecvStats.flows))

"num_zmq_received_flows" is 22 characters.  Valid DS names are 0-19 characters as per rrdtool documentation.

This error causes second.lua to generate an error log entry per second as it continually attempts to create the rrd file and fails with the following error:

[Lua.cpp:6648] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/second.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:961: invalid DS format]

Also note that the invalid DS name is referenced in the modules/graph_utils.lua file, so I don't know what else might be involved in changing it.

**Comment by emanuele-f** [comment]
Fixed with 0a064fe4dab7a990b52a47e26ddd591a23755ed6 . Thank you for reporting
