### ISSUE TITLE
 #1496 #1548 and #1557 Not solved!

### ISSUE THREAD

**Issue by antoniovalenzuela** [ntop/ntopng#1561]
RPI3 Jessie 8 (x86) 
please tell us what is the official installation for Jessie 8, 3 tickets without solution. 

A) They told me to use the strech repository .. it does not work

/etc/apt/sources.list.d/ntop.list
deb http://apt.ntop.org/stretch_pi armhf/
deb http://apt.ntop.org/stretch_pi all/

apt-get install ntopng

The following packages have unmet dependencies:
 ntopng : Depends: librrd8 but it is not installable
          Depends: libzmq5 but it is not installable
          Depends: libssl1.1 but it is not installable
          Depends: libhiredis0.13 but it is not installable
          Recommends: ntopng-data but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

B) I always used the repositories and the links are broken:

wget http://apt.ntop.org/jessie/all/apt-ntop.deb
dpkg -i apt-ntop.deb

Failed to fetch http://packages.ntop.org/apt/8.0/x64/Packages  404  Not Found
Failed to fetch http://packages.ntop.org/apt/8.0/all/Packages  404  Not Found

Fourth time I ask for help, why did go down the links for Jessie 8 (RPI)  and how do I solve the problem? I never had problems with raspberry updates. Solve and do not close the tickets.

**Comment by lucaderi** [comment]
@antoniovalenzuela Three tickets with answers that you did not follow. Above you are continuing to do things we do not support.

All you need to do is
1. On ARM we support only stretch_pi. If you ahem jessie upgrade first
2. Go to http://packages.ntop.org/RaspberryPI/
3. Do what is written 
- sudo su
- wget http://packages.ntop.org/apt/ntop.key
- apt-key add ntop.key
- Raspbian Stretch (9.x) [Active]
- echo "deb http://apt.ntop.org/stretch_pi armhf/" > /etc/apt/sources.list.d/ntop.list
- echo "deb http://apt.ntop.org/stretch_pi all/" >> /etc/apt/sources.list.d/ntop.list
- apt-get update
- apt-get install ntopng nprobe
