### ISSUE TITLE
ntopng and elk running issue

### ISSUE THREAD

**Issue by s2105** [ntop/ntopng#1562]
Hello,

While trying to run ntopng with the following command gives us error

ntopng -i tcp://127.0.0.1:5556 -w 3000 -F 'es,ntopng;ntopng-%Y.%m.%d;http://10.10.1.1:9200/_bulk;admin;password;'

09/Nov/2017 21:58:34 [AlertsManager.cpp:943] ERROR: SQL Error: step [INSERT INTO flows_alerts (alert_tstamp, alert_type, alert_severity, alert_json, vlan_id, proto, l7_proto, first_switched, last_switched, cli_country, srv_country, cli_os, srv_os, cli_asn, srv_asn, cli_addr, srv_addr, cli_port, srv_port, cli2srv_bytes, srv2cli_bytes, cli2srv_packets, srv2cli_packets, cli2srv_tcpflags, srv2cli_tcpflags, cli_blacklisted, srv_blacklisted, cli_localhost, srv_localhost) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?); ]
09/Nov/2017 21:58:34 [AlertsManager.cpp:943] ERROR: SQL Error: step [INSERT INTO flows_alerts (alert_tstamp, alert_type, alert_severity, alert_json, vlan_id, proto, l7_proto, first_switched, last_switched, cli_country, srv_country, cli_os, srv_os, cli_asn, srv_asn, cli_addr, srv_addr, cli_port, srv_port, cli2srv_bytes, srv2cli_bytes, cli2srv_packets, srv2cli_packets, cli2srv_tcpflags, srv2cli_tcpflags, cli_blacklisted, srv_blacklisted, cli_localhost, srv_localhost) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?); ]

**Comment by simonemainardi** [comment]
please, try to run version 3.1 and report again if the issue still occurs. The new version will carry extra information in the ERROR.
