### ISSUE TITLE
[Lua.cpp:5507] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[158] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.

### ISSUE THREAD

**Issue by ffbarcelos** [ntop/ntopng#1564]
Boa tarde,
Como corrigir os erros abaixo?
10/Nov/2017 12:14:50 [Lua.cpp:5507] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[158] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.
10/Nov/2017 12:19:50 [Lua.cpp:5507] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[158] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.
10/Nov/2017 12:24:50 [Lua.cpp:5507] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[158] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.
10/Nov/2017 12:29:50 [Lua.cpp:5507] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[158] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.
10/Nov/2017 12:34:50 [Lua.cpp:5507] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[158] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.
10/Nov/2017 12:39:50 [Lua.cpp:5507] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[158] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.
10/Nov/2017 12:44:50 [Lua.cpp:5507] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[158] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.
10/Nov/2017 12:49:50 [Lua.cpp:5507] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[158] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.
10/Nov/2017 12:54:50 [Lua.cpp:5507] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[158] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.
10/Nov/2017 12:59:50 [Lua.cpp:5507] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[158] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.
10/Nov/2017 13:04:50 [Lua.cpp:5507] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[158] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.
10/Nov/2017 13:09:50 [Lua.cpp:5507] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[158] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.
10/Nov/2017 13:14:50 [Lua.cpp:5507] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[158] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.
10/Nov/2017 13:19:50 [Lua.cpp:5507] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[158] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.
10/Nov/2017 13:24:50 [Lua.cpp:5507] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[158] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.
10/Nov/2017 13:29:50 [Lua.cpp:5507] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[158] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.
10/Nov/2017 13:34:50 [Lua.cpp:5507] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[158] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.

Obrigado.

**Comment by simonemainardi** [comment]
you have too many local hosts and thus there's not enough time to calculate their timeseries. Can you reduce their number by playing with parameter -m?

**Comment by ffbarcelos** [comment]
I already use this parameter, but there are several networks, one of them ipv6. Would there be no other way to solve it?

**Comment by emanuele-f** [comment]
@ffbarcelos, you can try to update your disk with a faster one or turn off some data dump into the data retention settings. I'm closing the issue for now.

**Comment by ffbarcelos** [comment]
The disk is a 200 GB SSD, in the retention configuration, only the Traffic Application and Layer-7 is enabled, the total of hosts around 10,000 divided into several networks.

**Comment by emanuele-f** [comment]
Layer 7 applications is what takes most of the time to write. Is the cpu load high?

**Comment by ffbarcelos** [comment]
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                     
 8621 nobody    20   0 3909700 2,463g  16724 S 264,8 14,0  82:47.31 ntopng                                                                                                      
 7623 nobody    20   0  839412 293204  18436 S  50,2  1,6  21:54.98 nprobe                                                                                                      
 1761 nobody    20   0  577268  77744  18524 S  16,3  0,4   9:57.15 nprobe                                                                                                      
 1554 nobody    20   0  511732  27500  18552 S   7,6  0,1   3:44.15 nprobe

**Comment by ffbarcelos** [comment]
The CPU is supporting.

**Comment by ffbarcelos** [comment]
I was doing some tests, the number of networks was reduced, and the errors changed.

10/Nov/2017 15:57:18 [Lua.cpp:6082] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/callbacks/5min.lua:130: /storage/ntopng/0/rrd/200/18/44/85/Telnet.rrd: opening '/storage/ntopng/0/subnetstats/200/18/32/0/20/num_http_hosts.rrd': No such file or directory]
10/Nov/2017 16:36:30 [Lua.cpp:6082] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:1053: /storage/ntopng/0/rrd/200/132/24/149/dns/sent/queries/num_aaaa.rrd: opening '/storage/ntopng/0/subnetstats/200/18/32/0/20/num_http_hosts.rrd': No such file or directory]
10/Nov/2017 16:41:14 [Lua.cpp:6082] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:1053: /storage/ntopng/0/rrd/200/18/43/197/dns/rcvd/queries/num_other.rrd: opening '/storage/ntopng/0/subnetstats/200/18/32/0/20/num_zmq_received_flows.rrd': No such file or directory]

**Comment by emanuele-f** [comment]
Please provide the following information:

- What ntopng version are you using?
- What is your ntopng configuration?
- How many cores in your cpu?

**Comment by ffbarcelos** [comment]
Please provide the following information:

What ntopng version are you using?  ntopng Pro [Small Business Edition] Edition v.3.0.171105
What is your ntopng configuration?
-n=2
-w=3000
-W=0
-g=-1
m="xxx.xx.xx.0/20,xxx.xx.xx.0/22,xxx.xx.xx.0/23,xxx.xx.xx.0/24,xxx.xx.xx.0/24,xxx.xx.xx.0/22,xxx.xx.xx.0/22,xxx.xx.xx.0/21"
-S=local
-X=2000000
-x=2000000
-d=/storage/ntopng
-G=/var/run/ntopng.pid
-i=tcp://127.0.0.1:1234
-i=tcp://127.0.0.1:1236


How many cores in your cpu? 8

**Comment by emanuele-f** [comment]
You are using the `-S` option, which causes all the hosts to stay in memory (and this is bad since during the periodic data dump we have to iterate all the hosts). Please try to remove it.

**Comment by ffbarcelos** [comment]
Hi,
Removing a -S option, but the errors continue, what else can we change?

Thank you

13/Nov/2017 14:06:46 [Lua.cpp:6082] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/callbacks/5min.lua:130: opening '/storage/ntopng/0/subnetstats/200/18/32/0/20/tcp_rst.rrd': No such file or directory]

13/Nov/2017 14:11:50 [Lua.cpp:6082] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/callbacks/5min.lua:130: opening '/storage/ntopng/0/subnetstats/200/18/32/0/20/tcp_rst.rrd': No such file or directory]

13/Nov/2017 14:17:56 [Lua.cpp:6082] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/callbacks/5min.lua:116: opening '/storage/ntopng/0/subnetstats/200/18/32/0/20/BJNP.rrd': No such file or directory]

**Comment by ffbarcelos** [comment]
If memory is increased, would it solve?

**Comment by emanuele-f** [comment]
Any chance to upgrade to the development version of ntopng? Can you still see the `Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration` error?

**Comment by ffbarcelos** [comment]
Se resolver o problema eu atualizo para a versão de desenvolvimento, qual seria o impacto?

Como faço para verificar o erro de configuração  do RRD?

**Comment by ffbarcelos** [comment]
If I solve the problem I upgrade to a development version, what is the impact?

How do I check the RRD configuration error?

**Comment by emanuele-f** [comment]
We are moving towards the next stable release, so please try the dev version if possible. The RRD error should appear into the ntopng log

**Comment by ffbarcelos** [comment]
I upgraded to the original edition Pro [Small Business Edition] v.3.0.171114 (previous Edition v.3.0.171105), plus some warnings continue.
16/Nov/2017 09:46:00 [Lua.cpp:6082] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:1053: opening '/storage/ntopng/0/subnetstats/200/18/32/0/20/tcp_synack.rrd': No such file or directory]
16/Nov/2017 09:56:10 [Lua.cpp:6082] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/callbacks/5min.lua:130: /storage/ntopng/0/rrd/200/18/38/235/Unknown.rrd: opening '/storage/ntopng/0/subnetstats/200/18/32/0/20/num_http_hosts.rrd': No such file or directory]
16/Nov/2017 10:01:15 [Lua.cpp:6082] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/callbacks/5min.lua:116: opening '/storage/ntopng/0/subnetstats/200/18/32/0/20/num_devices.rrd': No such file or directory]

**Comment by emanuele-f** [comment]
You need to change the ntop repository in order to use the development builds. Please follow the instructions at http://packages.ntop.org/ for "nightly builds"

**Comment by ffbarcelos** [comment]
Changing to a version to solve problems? Will not impact on the use license?

**Comment by emanuele-f** [comment]
You licence will not be affected. The development version has many fixes, so it will probably solve your problems.

**Comment by ffbarcelos** [comment]
# dpkg -i apt-ntop.deb
(Reading database ... 192333 files and directories currently installed.)
Preparing to unpack apt-ntop.deb ...
Unpacking apt-ntop (2.5-505) ...
dpkg: error processing archive apt-ntop.deb (--install):
 trying to overwrite '/etc/nbox/ntop-apt.key', which is also in package apt-ntop-stable 2.4-538
abort-install
Errors were encountered while processing:
 apt-ntop.deb

**Comment by emanuele-f** [comment]
Please remove apt-ntop-stable

**Comment by ffbarcelos** [comment]
Remove apt-ntop-stable and then put apt-ntop, update and update, but the errors continue.

17/Nov/2017 09:25:44 | WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/callbacks/5min.lua:116: opening '/storage/ntopng/0/subnetstats/xxx/xx/xx/0/20/tcp_rst.rrd': No such file or directory]
-- | --
17/Nov/2017 09:45:55 | WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:1053: /storage/ntopng/1/rrd/xxxx/dns/sent/queries/num_soa.rrd: opening '/storage/ntopng/0/subnetstats/xx/xx/xx/0/20/num_hosts.rrd': No such file or directory]
17/Nov/2017 09:48:38 | WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/second.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:968: /storage/ntopng/1/rrd/bytes.rrd: opening '/storage/ntopng/0/subnetstats/xx/x8/xx/0/20/YouTube.rrd': No such file or directory]
17/Nov/2017 10:16:27 | WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/callbacks/5min.lua:130: opening '/storage/ntopng/0/asnstats/28604/tcp_retr_ooo_lost.rrd': No such file or directory]
17/Nov/2017 10:30:46 | WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:1053: /storage/ntopng/1/rrd/xxxx/dns/rcvd/queries/num_a.rrd: opening '/storage/ntopng/0/subnetstats/xxx/1xx/xx0/0/21/num_hosts.rrd': No such file or directory]
17/Nov/2017 10:35:47 | WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:1065: ]

**Comment by simonemainardi** [comment]
@ffbarcelos any chance to get an ssh access to the machine?

**Comment by ffbarcelos** [comment]
What is your email contact?

**Comment by simonemainardi** [comment]
mainardi ntop org

**Comment by simonemainardi** [comment]
fixed with https://github.com/ntop/ntopng/commit/6c7e71d684aa0276c3a950dc66347f9639a4d608 and https://github.com/ntop/ntopng/commit/a98b8d847e1060bcb078f52bb4958c73982be0c4
