### ISSUE TITLE
Unable to handle PID file properly

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1565]
PID file is not handled properly

1. Startup issue
[main.cpp:318] ERROR: Unable to store PID in file /var/run/ntopng.pid

2. Shutdown issue
[main.cpp:64] Deleted PID /var/run/ntopng.pid [rc: -1]

**Comment by lucaderi** [comment]
The fix is an intermediate fix. The ultimate solution is to create
- ntopng as user
- create /var/run/ntopng/ and store the pid file in there owned by the user

Keep in mind http://seclists.org/oss-sec/2017/q3/305

**Comment by simonemainardi** [comment]
issue is handled safely as one can run ntopng specifying an arbitrary user with option -U and get the pid file generated with the right user.

Moreover, handling ntopng with systemd no longer uses pid files so no security issue occurs
