### ISSUE TITLE
Compilation terminated due to /libcache.h: No such file or directory

### ISSUE THREAD

**Issue by LolikaPadmanbhan** [ntop/ntopng#1567]
I  followed the instruction given, but still i have this problem and am new to this so, plz help me out what to do next .?
I also want to know which source file to be executed to get the ntop connected to web server. 
i want this to run through source code/ntop repository only.

gmake[3]: Entering directory '/home/lolika/source_code/nDPI/ntopng/third-party/json-c/tests'
gmake[3]: Nothing to be done for 'all'.
gmake[3]: Leaving directory '/home/lolika/source_code/nDPI/ntopng/third-party/json-c/tests'
gmake[2]: Leaving directory '/home/lolika/source_code/nDPI/ntopng/third-party/json-c'
gmake[1]: Leaving directory '/home/lolika/source_code/nDPI/ntopng/third-party/json-c'
g++ -g -Wall -I/home/lolika/source_code/nDPI/ntopng -I/home/lolika/source_code/nDPI/ntopng/include -I/usr/local/include -I /home/lolika/source_code/nDPI/ntopng/third-party/hiredis -I/home/lolika/source_code/nDPI/ntopng/third-party/mongoose -I/home/lolika/source_code/nDPI/ntopng/third-party/json-c  -I/usr/local/include/libndpi-2.1.0/libndpi -I/home/lolika/source_code/nDPI/ntopng/third-party/LuaJIT-2.1.0-beta3/src  -I/home/lolika/source_code/nDPI/ntopng/third-party/zeromq-4.1.3/include -I/usr/include/mysql  -I/home/lolika/source_code/nDPI/ntopng -I/home/lolika/source_code/nDPI/ntopng/include -I/usr/local/include -I/home/lolika/source_code/nDPI/ntopng/third-party/http-client-c/src/  -I/usr/include/openssl  -DDATA_DIR='"/usr/local/share"' -I/home/lolika/source_code/nDPI/ntopng/third-party/libgeohash -I/home/lolika/source_code/nDPI/ntopng/third-party/patricia   -c src/AddressList.cpp -o src/AddressList.o
In file included from /usr/local/include/libndpi-2.1.0/libndpi/ndpi_main.h:30:0,
                 from /home/lolika/source_code/nDPI/ntopng/include/ntop_includes.h:107,
                 from src/AddressList.cpp:22:
/usr/local/include/libndpi-2.1.0/libndpi/ndpi_typedefs.h:28:49: fatal error: ../lib/third_party/include/libcache.h: No such file or directory
compilation terminated.
Makefile:158: recipe for target 'src/AddressList.o' failed
make: *** [src/AddressList.o] Error 1

Thanking you..

**Comment by emanuele-f** [comment]
Hi, you should put ntopng and nDPI at the same directory level (so please do a `cd nDPI && mv nDPI/ntopng ..`).

Then you need to compile nDPI first: `cd nDPI && ./autogen.sh && ./configure && make`. Then ntopng: `cd ntopng && ./autogen.sh && ./configure && make`

**Comment by LolikaPadmanbhan** [comment]
@emanuele-f 
hey,
Thanks for the response. 
I have kept both nDPI and ntopng in the same directory and followed the same as you told. but still i face the same error.
when i compile nDPI its compiling with out any problem, later when i use cd ntopng && ./autogen.sh && ./configure && make for ntopng it is giving me the same error again. 
Help me out please.
Thanking you..

**Comment by LolikaPadmanbhan** [comment]
hey @emanuele-f 

In continuation to the previous post. according to my observation from the error is, the file libcache.h is in nDIP  folder in the described path  : ../nDPI/src/lib/third_party/include/libcache.h. but when we are using make in ntopng it is unable to locate the path of libcache.h i guess and  no where i get to see this nDIP included in the path.
just tell me is my understanding is correct? and what next to be done.
Thank you,

**Comment by emanuele-f** [comment]
It seems like ntopng is using /usr/local/include/libndpi-2.1.0 as the nDPI include directory. Can you uninstall the system wide installed nDPI and retry with `./autogen.sh && ./configure && make` into ntopng source directory?

**Comment by LolikaPadmanbhan** [comment]
@emanuele-f 
Should i be doing uninstall for all the package also or only nDPI should be fine.. ?
if in case the compilation is successful. which file should i run to see the output?
Thank you..

**Comment by emanuele-f** [comment]
Only nDPI. After successfully compiled, you can run ntopng with `./ntopng` from the ntopng source directory

**Comment by LolikaPadmanbhan** [comment]
@emanuele-f 
I followed your suggestion it didn't. 
so i used : sudo apt autoremove  and started the compilation from fresh, but got stuck again in the same error. 
the steps i followed 
Installed the packages 
sudo apt-get install libmysqlclient-dev
sudo apt-get install libsqlite3-dev
sudo apt-get install libglib2.0-dev
sudo apt-get install libxml2-dev
sudo apt-get install wget
sudo apt install redis-server 
then used sudo apt-get update
sudo apt-get install libtool-bin(used this since am using ubuntu(16.04) then ,
lolika@-------C50-C:~$ git clone https://github.com/ntop/nDPI.git
lolika@-------C50-C:~$ cd nDPI; ./autogen.sh; ./configure; make; cd ..
lolika@-------C50-C:~$ git clone https://github.com/ntop/ntopng.git
lolika@-------C50-C:~$ cd ntopng; ./autogen.sh; ./configure; make; cd ..
Error:
In file included from /usr/local/include/libndpi-2.1.0/libndpi/ndpi_main.h:30:0,
                 from /home/lolika/ntopng/include/ntop_includes.h:107,
                 from src/AddressList.cpp:22:
/usr/local/include/libndpi-2.1.0/libndpi/ndpi_typedefs.h:28:49: fatal error: ../lib/third_party/include/libcache.h: No such file or directory
compilation terminated.
Makefile:158: recipe for target 'src/AddressList.o' failed
make: *** [src/AddressList.o] Error 1
ended up with this agian.. i have no clue what is going wrong.
Thank you..!

**Comment by emanuele-f** [comment]
Hi, what is clear from the log above is that you have somehow installed nDPI systemwide (and it is still there). So, if you have installed nDPI from packages, do `apt-get remove ndpi`. Otherwise, if you have installed it from source, go into the nDPI source directory and do a `sudo make uninstall`. If you have successfully removed nDPI systemwide then `/usr/local/include/libndpi-2.1.0` *cannot* exist. As a last resort, `rm -rf /usr/local/include/libndpi-2.1.0`.

After doing this, you can follow the steps to compile ntopng: `./autogen.sh && ./configure && make` from the ntopng source directory.

**Comment by LolikaPadmanbhan** [comment]
@emanuele-f 
hey ,
Thanks a tone ... i followed the steps and i could successfully Compile the file. Am happy for it.. 
Thank you very much.
if you don't mind can i get your email id. so that if i need any help during running ntopng i can seek your help.
thank you once again.

**Comment by emanuele-f** [comment]
@LolikaPadmanbhan thank you for the feedback. I'm part of the ntop team so the best way to get help on ntopng is to open an issue here. Me or one of my collegues will help you. I'm closing the issue.
