### ISSUE TITLE
Upgrade issue

### ISSUE THREAD

**Issue by jj2473** [ntop/ntopng#1570]
sudo apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  gstreamer1.0-plugins-bad libgl1-mesa-dri libgstreamer-plugins-bad1.0-0
  pix-icons pix-plym-splash pixel-wallpaper raspberrypi-ui-mods sonic-pi
  wolfram-engine xserver-xorg-input-all
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up nprobe (8.1.171016-5920) ...
Rebuilding ld cache...
Adding the nprobe startup script
Synchronizing state for nprobe.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d nprobe defaults
insserv: Service pf_ring has to be enabled to start service nprobe
insserv: Service cluster has to be enabled to start service nprobe
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
*** Error in `systemctl': double free or corruption (fasttop): 0x55c3ef78 ***
Aborted
dpkg: error processing package nprobe (--configure):
 subprocess installed post-installation script returned error exit status 134
Setting up ntopng (3.1.171016-3574) ...
Rebuilding ld cache...
Adding the ntopng startup script [configure]
Synchronizing state for ntopng.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d ntopng defaults
Executing /usr/sbin/update-rc.d ntopng enable
(Re)Starting ntopng...
Failed to restart ntopng.service: Unit pf_ring.service failed to load: No such file or directory.
dpkg: error processing package ntopng (--configure):
 subprocess installed post-installation script returned error exit status 6
Processing triggers for libc-bin (2.19-18+deb8u10) ...
Errors were encountered while processing:
 nprobe
 ntopng
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by emanuele-f** [comment]
> *** Error in `systemctl': double free or corruption (fasttop): 0x55c3ef78 ***
It seems like your systemd version is buggy, what operating system are you using? Is it updated?

**Comment by jj2473** [comment]
Hello,
This is on an updated raspberry pi 3, I see other people are getting same
error. This happens when it try to install updated ntopng and nprobe.

Thank,
Jim

**Comment by emanuele-f** [comment]
Hi, I've just tried to do a new install of ntopng on raspberry 3 with no problem:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  nprobe ntopng
0 upgraded, 2 newly installed, 0 to remove and 46 not upgraded.
Need to get 0 B/5,503 kB of archives.
After this operation, 32.0 MB of additional disk space will be used.
Selecting previously unselected package nprobe.
(Reading database ... 146462 files and directories currently installed.)
Preparing to unpack .../nprobe_8.1.171115-5954_armhf.deb ...
Unpacking nprobe (8.1.171115-5954) ...
Selecting previously unselected package ntopng.
Preparing to unpack .../ntopng_3.1.171115-3715_armhf.deb ...
Unpacking ntopng (3.1.171115-3715) ...
Setting up ntopng (3.1.171115-3715) ...
Rebuilding ld cache...
Adding the ntopng startup script [configure]
Setting up nprobe (8.1.171115-5954) ...
Rebuilding ld cache...
Making the /var/log/nprobe directory...
(Re)Starting nprobe services...
Created symlink /etc/systemd/system/multi-user.target.wants/nprobe.service → /etc/systemd/system/nprobe.service.
Processing triggers for man-db (2.7.6.1-2) ...
```

You are using outdated packages (eg. ntopng `3.1.171016` vs current version `3.1.171115`). Please run `sudo apt-get update` before issuing the upgrade command

**Comment by jj2473** [comment]
Hello,
I am and it pulls down what packages it can find.

**Comment by jj2473** [comment]
Hello Emanuele,
 sudo apt-get update
Get:1 http://mirrordirector.raspbian.org jessie InRelease [14.9 kB]
Get:2 http://archive.raspberrypi.org jessie InRelease [22.9 kB]
Get:3 http://mirrordirector.raspbian.org jessie/main armhf Packages [9,536
kB]
Ign http://apt.ntop.org armhf/ InRelease
Ign http://apt.ntop.org all/ InRelease
Ign http://apt.ntop.org armhf/ Release.gpg
Ign http://apt.ntop.org all/ Release.gpg
Ign http://apt.ntop.org armhf/ Release
Ign http://apt.ntop.org all/ Release
Hit http://archive.raspberrypi.org jessie/main armhf Packages
Hit http://archive.raspberrypi.org jessie/ui armhf Packages
Err http://apt.ntop.org armhf/ Packages
  404  Not Found
Ign http://apt.ntop.org armhf/ Translation-en_US
Ign http://apt.ntop.org armhf/ Translation-en
Err http://apt.ntop.org all/ Packages
  404  Not Found
Ign http://apt.ntop.org all/ Translation-en_US
Ign http://apt.ntop.org all/ Translation-en
Ign http://archive.raspberrypi.org jessie/main Translation-en_US
Ign http://archive.raspberrypi.org jessie/main Translation-en
Get:4 http://mirrordirector.raspbian.org jessie/contrib armhf Packages
[43.3 kB]
Ign http://archive.raspberrypi.org jessie/ui Translation-en_US
Get:5 http://mirrordirector.raspbian.org jessie/non-free armhf Packages
[84.2 kB]
Ign http://archive.raspberrypi.org jessie/ui Translation-en
Get:6 http://mirrordirector.raspbian.org jessie/rpi armhf Packages [1,356 B]
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en_US
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en
Ign http://mirrordirector.raspbian.org jessie/main Translation-en_US
Ign http://mirrordirector.raspbian.org jessie/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en_US
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en_US
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en
Fetched 9,703 kB in 1min 50s (88.1 kB/s)
W: Failed to fetch http://apt.ntop.org/jessie_pi/armhf/Packages  404  Not
Found

W: Failed to fetch http://apt.ntop.org/jessie_pi/all/Packages  404  Not
Found

E: Some index files failed to download. They have been ignored, or old ones
used instead.
pi@PiHole:~ $

**Comment by emanuele-f** [comment]
We no longer support jessie on raspberry. stretch is the new stable. Please see http://packages.ntop.org/RaspberryPI
