### ISSUE TITLE
n2disk hardware dependency

### ISSUE THREAD

**Issue by mhmontazeri** [ntop/ntopng#1571]
Hi,
I'm using n2disk for a 10G transfer and my experience was successful but now after changing target test motherboard, the license error message has been shown(and the machine ID is the problem apparently). Is there any solution?

Best Regards
mhmontazeri

**Comment by mhmontazeri** [comment]
Hi,
In my previous issue, its absent that i shall say about my requirement for changing motherboard because of achieving higher rate performance. Thanks for any help...

Best Regards
mhmontazeri

**Comment by emanuele-f** [comment]
Hi, see the instructions at https://www.ntop.org/support/faq/how-can-i-move-a-license-to-a-new-server/

Please contact us privately via the contact form for any additional need.
