### ISSUE TITLE
How to configure/set  NetFlow and sFlow in ntopng?

### ISSUE THREAD

**Issue by LolikaPadmanbhan** [ntop/ntopng#1573]
Hey,
I have installed ntop in one machine using apt on Ubuntu 16.04, i get to see the older version(1998 -2012) 
In another  Ubuntu 16.04 machine i have installed ntopng by compiling source code(LuaJIT 2.1.0-beta3). both the interface look very different. I understand ntopng is a product of top. but however i see a Plugins tab in ntop which allows us to set/configure NetFlow, sFlow in ntop. is it possible to  use nProbe along with ntopng to configure NetfFlow and sFlow and monitor those traffic in ntopng,  which i don't know how to do? so, kindly let me know how do i configure both of them together.
Please let me know.

Thanking you..

**Comment by emanuele-f** [comment]
Hi, ntopng requires nProbe in order to receive NetFlow/sFlow traffic. Please look at this page for more information https://www.ntop.org/nprobe/advanced-flow-collection-with-ntopng-and-nprobe/ . You can also find other info in our user guide https://github.com/ntop/ntopng/blob/dev/doc/UserGuide.pdf

**Comment by LolikaPadmanbhan** [comment]
Hi,
i downloaded the source code for nProbe from git source repo. Now,how do i compile and run to configure and set my own netflow to ntopng to monitor is my question. 

Thank you,

**Comment by simonemainardi** [comment]
@LolikaPadmanbhan nProbe is not opensource so any version you've downloaded is not affiliated with us.

Please, install nProbe from http://packages.ntop.org/

Then follow the readme pointed out by @emanuele-f to collect NetFlow.

**Comment by LolikaPadmanbhan** [comment]
@simonemainardi ,
Hi, https://github.com/ntop/nProbe.git i was saying i have download the this repo. is it not from ntop.? i was asking about compiling this.
Thank you.

**Comment by simonemainardi** [comment]
That repo only contains docs not code. You can't compile it.

**Comment by LolikaPadmanbhan** [comment]
ya i just saw. then i need to install nProbe from ntop package only as a separate application and then config with ntopng right? 
thank  you.

**Comment by simonemainardi** [comment]
correct

**Comment by LolikaPadmanbhan** [comment]
Can i use sudo apt-get install nProbe on Ubuntu 16.04 for installation.?
Thank you.

**Comment by LolikaPadmanbhan** [comment]
i don't think i can use sudo for this.? it might not locate the package.

**Comment by emanuele-f** [comment]
nprobe package is lowercase

**Comment by LolikaPadmanbhan** [comment]
@emanuele-f 
No i tried both ..;-(

**Comment by LolikaPadmanbhan** [comment]
One more think i want  both ntopng and nProbe in the same system.
i want to create my own NetFlow and monitor that in ntopng.
As ntopng does for the local system.

**Comment by LolikaPadmanbhan** [comment]
One more think i want  both ntopng and nProbe in the same system.
i want to create my own NetFlow and monitor that in ntopng.
As ntopng does for the local system.

**Comment by emanuele-f** [comment]
Have you configured the ntop repository as explained in http://packages.ntop.org/ ?

**Comment by LolikaPadmanbhan** [comment]
i have used sudo apt-get install ntop along with the required packages. 
and i another i have compiled the ntopng using the repo.. i understand it will not happen in the one which i have compiled from source code.but, it should happen for the one which i have used from sudo apt.?
Thank you.

**Comment by LolikaPadmanbhan** [comment]
hey,
I have removed ntop using the command.
sudo apt autoremove
sudo apt purge ntop
then followed these instructions from http://packages.ntop.org/
    wget http://apt-stable.ntop.org/16.04/all/apt-ntop-stable.deb
    sudo dpkg -i apt-ntop-stable.deb 
  then run
  sudo  apt-get clean all
sudo  apt-get update
but it giving me this error when i try to execute this: sudo apt-get install pfring nprobe ntopng ntopng-data n2disk cento nbox .
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
i have checked no other process is using it currently .
what should i do now?
Thank you.

**Comment by emanuele-f** [comment]
Hi, you are now on the right path to install ntopng. If you use ubuntu, some software manager may lock the dpkg (e.g. `unattended-upgrades`) temporary. Anyway, after some time, you should be able to properly run the command above correctly. If that does not happen, maybe youl will need to manually remove `/var/lib/dpkg/lock`.

**Comment by LolikaPadmanbhan** [comment]
Hey, i have been trying its not happening. even after removing the lock file manually am still unable to install it. still with error.
sudo apt-get install pfring nprobe ntopng ntopng-data n2disk cento nbox
Reading package lists... Done
Building dependency tree      
Reading state information... Done
ntopng is already the newest version (3.0.171120-3737).
cento is already the newest version (1.2.171120-97).
nprobe is already the newest version (8.0.171120-5797).
n2disk is already the newest version (2.8.171120-4826).
pfring is already the newest version (7.0.0-1559).
ntopng-data is already the newest version (3.0.171120).
nbox is already the newest version (2.4-539).
0 upgraded, 0 newly installed, 0 to remove and 144 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n]
Setting up ntopng (3.0.171120-3737) ...
Rebuilding ld cache...
Adding the ntopng startup script [configure]
Synchronizing state of ntopng.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable ntopng
Failed to execute operation: File exists
dpkg: error processing package ntopng (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Errors were encountered while processing:
 ntopng
E: Sub-process /usr/bin/dpkg returned an error code (1)

what to do now?
thank you.

**Comment by emanuele-f** [comment]
Please remove any previously installed ntopng files. For example `/etc/init.d/ntopng`

**Comment by LolikaPadmanbhan** [comment]
i have removed all the files and started fresh but still its not working i don't knw what is the problem.

**Comment by emanuele-f** [comment]
A quick search on google will help you. Do you have package `ntop` installed ? See #1288

**Comment by LolikaPadmanbhan** [comment]
hi, have been searching, am unable to find the correct answer. the one which you have refereed is on debian. but i am using Ubuntu 16.04. i tried that also anyways.
However i tried following  the instructions from  http://packages.ntop.org/ on a new system . when used sudo apt-get update endup with this error. 
404  Not Found
Ign:10 http://packages.ntop.org/apt/16.10 x64/ Translation-en
Ign:11 http://packages.ntop.org/apt/16.10 x64/ Translation-en_IN
Err:12 http://packages.ntop.org/apt/16.10 all/ Packages
  404  Not Found
Ign:13 http://packages.ntop.org/apt/16.10 all/ Translation-en_IN
Ign:14 http://packages.ntop.org/apt/16.10 all/ Translation-en
Reading package lists... Done
W: The repository 'http://packages.ntop.org/apt/16.10 x64/ Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://packages.ntop.org/apt/16.10 all/ Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://packages.ntop.org/apt/16.10/x64/Packages  404  Not Found
E: Failed to fetch http://packages.ntop.org/apt/16.10/all/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by emanuele-f** [comment]
As you can deduct from the missing instructions at http://packages.ntop.org/apt/ , we *do not* support ubuntu 16.10 ! Please start from a clean 16.04 and follow the instructions meticulously

**Comment by LolikaPadmanbhan** [comment]
hey, ya the system which i used previously was 16.10. so i was not able to find the package. 
@emanuele-f 
hey, i have been trying this from past 1 week am still unable to understand the issue.
as you told i removed all the files of ntop manually by using the command : sudo rm -r with all the files relevant to ntop as well as ntopng. there is no file or dir related to ntop or ntopng. 
then i started my installation in a new system which is Ubuntu 16.04 today mrg. just followed the instruction as you told in the previous comment. but still ended up with this. i have no idea regarding this. am attaching  the complete log file of the commands i followed in the new system.
find the attachment for the error log file and please help me out in this regards to fix the issue. 
[Error-Log.pdf](https://github.com/ntop/ntopng/files/1500778/Error-Log.pdf)
Thank you.

**Comment by simonemainardi** [comment]
@LolikaPadmanbhan by looking at the error log enclosed

```
Synchronizing state of ntopng.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable ntopng
Failed to execute operation: File exists
dpkg: error processing package ntopng (--configure):
 subprocess installed post-installation script returned er
```

it seems that there's some installation file already present and so the installation fails. It looks like you didn't fully remove the old files.

I would try and do an `apt-get --purge remove ntopng && apt-get install ntopng`

**Comment by LolikaPadmanbhan** [comment]
yaa am doing same from past 1 week.

Thank you.

**Comment by simonemainardi** [comment]
can you send us a remote ssh access?

**Comment by LolikaPadmanbhan** [comment]
@simonemainardi 
Hey thanks, shall we use teamviewer? ssh might not be possible so.

**Comment by simonemainardi** [comment]
ok, send access details to mainardi ntop org

**Comment by LolikaPadmanbhan** [comment]
is it mainardi@ntop.org?

**Comment by simonemainardi** [comment]
Yes.

PS: It's not me that I'm lazy and don't want to types @ and dots, it's just not recommended to write cleartext emails in posts due to spammers heavy crawling web pages.

**Comment by LolikaPadmanbhan** [comment]
Hey, @emanuele-f @simonemainardi 
Thanks for the support as of now i am able to use ntopng in one machine and i used  sudo install for nprobe i could install, however i need a licence to use it. so thats fine. well, i appreciate your support.
thanks a lot.

**Comment by kraduk** [comment]
any chance of some freebsd packages for this?
