### ISSUE TITLE
strange lines in syslog

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#1574]
in checking my syslog I can see few lines (the same)

 [Lua.cpp:6188] [@/usr/share/ntopng/scripts/lua/modules/alert_utils.lua]:[1946] Unexpected new_entity_info == nil

and some alerts
 [Alert] blacklisted host <A HREF='/lua/host_details.lua?host=115.231.218.26&ifid=1&page=alerts'>115.231.218.26</A> contacted host <A HREF='/lua/host_details.lua?host=10.0.115.14&ifid=1&page=alerts'>10.0.115.14</A> [TCP 115.231.218.26:6000 &gt; 10.0.115.14:8082 [proto: 0.0/Unknown][device: 3232239112 in: 3 out:0][1/0 pkts][40/0 bytes][SYN]]

is it normal ?

Nico

**Comment by simonemainardi** [comment]
@Niko78 are you using the latest version? However, the alert is normal it's a blacklisted host connection. Disable the alerts from the preferences if you don't want them.

**Comment by Niko78** [comment]
@simonemainardi 
sure I use : 3.1.171117 -  Professional Edition

about alerts I think I did not understand settings cause I thought it was to display them in UI not to add them in syslog, well ok understood now

**Comment by simonemainardi** [comment]
so please disable preference 'send alerts to syslog'

**Comment by Niko78** [comment]
this setting is already at off
![capture](https://user-images.githubusercontent.com/17108017/32949155-123d7822-cba2-11e7-9881-1c689c3d94e8.PNG)

**Comment by emanuele-f** [comment]
@Niko78 I've commited a fix. Please try the new package which will be available in one hour and let me know

**Comment by Niko78** [comment]
it seems to be ok now
thanks

**Comment by emanuele-f** [comment]
Thank you for reporting!
