### ISSUE TITLE
New Docker

### ISSUE THREAD

**Issue by junquera** [ntop/ntopng#1576]
Hi! I've made a **docker** that pulls from the repo and creates all from the Ubuntu 16.04 image. I've created it because the `apt`s version is outdated. 

My version is at: [ntopng-docker](https://github.com/junquera/ntopng-docker)

**Comment by emanuele-f** [comment]
Hi, thank you for sharing!

We provide an ubuntu 14 based docker file to pull ntopng from our package repository https://github.com/ntop/ntopng/tree/dev/docker but your solution is definitely more opensource friendly

**Comment by simonemainardi** [comment]
there is also this docker that I've written some time ago. It's much smaller than yours: https://github.com/simonemainardi/ntopng-docker

We will several versions available when pulling an official dockerfile for the project.

Thanks for your contribution.
