### ISSUE TITLE
ntopng crash 

### ISSUE THREAD

**Issue by Howard-Chang** [ntop/ntopng#1577]
Hi, today I found my ntopng carshed which happened on forth day.
this is the log:
23/Nov/2017 11:52:15 [PeriodicActivities.cpp:50] Started periodic activities loop...
23/Nov/2017 11:52:15 [NetworkInterface.cpp:2149] Started packet polling on interface tcp://127.0.0.1:2055 [id: 1]...
23/Nov/2017 11:52:15 [CollectorInterface.cpp:115] Collecting flows on tcp://127.0.0.1:2055
23/Nov/2017 11:52:15 [Lua.cpp:6128] WARNING: Script failure [C:\Program Files\ntopng\scripts\callbacks/second.lua][C:\Program Files\ntopng/scripts/lua/modules/graph_utils.lua:978: short read while reading header rrd->stat_head]
23/Nov/2017 11:52:16 [Lua.cpp:6128] WARNING: Script failure [C:\Program Files\ntopng\scripts\callbacks/second.lua][C:\Program Files\ntopng/scripts/lua/modules/graph_utils.lua:978: short read while reading header rrd->stat_head]
23/Nov/2017 11:52:17 [Lua.cpp:6128] WARNING: Script failure [C:\Program Files\ntopng\scripts\callbacks/second.lua][C:\Program Files\ntopng/scripts/lua/modules/graph_utils.lua:978: short read while reading header rrd->stat_head]
23/Nov/2017 11:52:18 [Lua.cpp:6128] WARNING: Script failure [C:\Program Files\ntopng\scripts\callbacks/second.lua][C:\Program Files\ntopng/scripts/lua/modules/graph_utils.lua:978: short read while reading header rrd->stat_head]
23/Nov/2017 11:52:19 [Lua.cpp:6128] WARNING: Script failure [C:\Program Files\ntopng\scripts\callbacks/second.lua][C:\Program Files\ntopng/scripts/lua/modules/graph_utils.lua:978: short read while reading header rrd->stat_head]
23/Nov/2017 11:52:20 [Lua.cpp:6128] WARNING: Script failure [C:\Program Files\ntopng\scripts\callbacks/second.lua][C:\Program Files\ntopng/scripts/lua/modules/graph_utils.lua:978: short read while reading header rrd->stat_head]
23/Nov/2017 11:52:21 [Lua.cpp:6128] WARNING: Script failure [C:\Program Files\ntopng\scripts\callbacks/second.lua][C:\Program Files\ntopng/scripts/lua/modules/graph_utils.lua:978: short read while reading header rrd->stat_head]

thank you in advance !

**Comment by Howard-Chang** [comment]
After I remove all the document in rrd file, it can work .
but how to prevent it happen again ?

thank you in advance!

**Comment by lucaderi** [comment]
I think this was a corrupted RRD file. Unfortunately in this case the crash is due to RRD and the best you can do is to delete the file that is causing the issue. We'll soon release a new stable that introduces several new improvements that should also mitigate these issues

**Comment by Howard-Chang** [comment]
ok I got! thank you very much.
