### ISSUE TITLE
Error in ntopng runtime status

### ISSUE THREAD

**Issue by malvivent7** [ntop/ntopng#1578]
Hi i have installed ntopng through the repo offered for ubuntu 16.04 lts all seem ok but in runtime status of the webinterface admin i see this moltitude of warnings

Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:74: opening '/storage/ntopng/1/subnetstats/192/168/10/0/24/bytes.rrd': Permission denied] (lot of it)
this is my version
3.1.171120 - Community Edition
and this is my startup parameters
ntopng --max-num-hosts "600000" --http-port "3000" --https-port "0" --core-affinity "-1" --local-networks "192.168.119.0/24,192.168.10.0/24,192.168.201.0/24,192.168.202.0/24,192.168.203.0/24,192.168.204.0/24,192.168.205.0/24,192.168.206.0/24,192.168.208.0/24,192.168.209.0/24,192.168.210.0/24,192.168.211.0/24,192.168.212.0/24,192.168.213.0/24,192.168.214.0/24,192.168.215.0/24,192.168.216.0/24,192.168.217.0/24,192.168.218.0/24,192.168.219.0/24,192.168.220.0/24,192.168.221.0/24,192.168.222.0/24,192.168.223.0/24,192.168.224.0/24,192.168.225.0/24,192.168.226.0/24,192.168.228.0/24,192.168.242.0/24,192.168.230.0/24,192.168.231.0/24,192.168.232.0/24,192.168.233.0/24,192.168.234.0/24,192.168.235.0/24,192.168.236.0/24,192.168.237.0/24,192.168.238.0/24,192.168.239.0/24,192.168.240.0/24,192.168.241.0/24,192.168.243.0/24,192.168.245.0/24,192.168.229.0/24,10.0.5.0/24,192.168.198.0/24,192.168.11.0/24,192.168.22.0/24,192.168.246.0/24,192.168.99.0/24,192.168.98.0/24,192.168.11.0/24" --data-dir "/storage/ntopng" --dont-change-user "" --community ""
some advice? Thanks in advance

**Comment by emanuele-f** [comment]
Hi, what are the permissions of file `/storage/ntopng/1/subnetstats/192/168/10/0/24/bytes.rrd` ?

Can you remove the `--dont-change-user` parameter and add the `-U your_username`? After doing this, please run `chown -R your_username:your_group /storage/ntopng`

**Comment by malvivent7** [comment]
Hi emanuele, thanks for your reply this is the permissions of the file that you ask for:
-rw-r--r-- 1 nobody nogroup 93736 nov 25 02:52 /storage/ntopng/1/subnetstats/192/168/10/0/24/bytes.rrd

**Comment by emanuele-f** [comment]
Are you running ntopng as root or as normal user?

**Comment by malvivent7** [comment]
I start ntopng as root

**Comment by emanuele-f** [comment]
Please follow the instructions on my first reply

**Comment by malvivent7** [comment]
THANKS emanuele!!! all works ok now ... strange parameter --dont-change-user.... i dont know where cames it from?? anyway thanks again

**Comment by emanuele-f** [comment]
Glad you solved. Closing the issue
