### ISSUE TITLE
ntopng kills ipsec connection

### ISSUE THREAD

**Issue by ShinIce** [ntop/ntopng#1579]
Hi,

atm I have problems on a debian stable server with ntopng in version 3.0.171102 which runs an ipsec tunnel with xl2tpd.
I'm not sure if the problem is ntopng, pfring or even xl2tpd but removing ntopng and pfring solves it on the easiest way.

On the first run ntopng.conf was plain as shipped, in this case ntopng made changes also to the ppp* devices, thinking this was my problem, I had set then the devices which should be used:
```-i=lo
-i=eth0
-i=eth1
-i=eth2
-i=eth3
-i=eth4
-i=eth5
```
After that ntopng only touches lo/eth* devices as expected but changing those to PROMISC mode.
The ipsec connections breaks still down.

With ntopng running, also restarting the tunnel does not make any changes. Only removing ntopng and pfring give me the possibility the connect to my tunnel.

Any idea what could be the problem? I can't find anything related to it :cry: 

As attachment all the logs I can provide.
I changed public IPs to X.X.X leaving the last octet untouched to show the different networks.

[ntopng_ipsec_problems.txt](https://github.com/ntop/ntopng/files/1505333/ntopng_ipsec_problems.txt)

**Comment by emanuele-f** [comment]
Hi, can you try to add the `--no-promisc` option to ntopng?

**Comment by ShinIce** [comment]
@emanuele-f will test it, hopefully this night (need to have VPN users offline), and report it.

**Comment by emanuele-f** [comment]
Thank you, please let me know

**Comment by ShinIce** [comment]
so, test made @emanuele-f but there is no change.
After ntopng start the whole tunnel breaks down.

**Comment by emanuele-f** [comment]
Can you see any hint in `dmesg` when this happens? With `--no-promisc` do you still see the interface going promiscuos?
