### ISSUE TITLE
Hosts suddnley dissaper from ntopng (local network)

### ISSUE THREAD

**Issue by AlekMarkus** [ntop/ntopng#158]
lets say i have seen host name : Server1 (10.1.101.1)

i click on this host  to see more information about , after i did a refresh to my page i have an error : 

![hosts](https://cloud.githubusercontent.com/assets/13960741/9789048/40683a76-57d6-11e5-8a4e-fa67630d0b13.png)

it already happened with 2 hosts

**Comment by lucaderi** [comment]
What's wrong with that?

**Comment by AlekMarkus** [comment]
sorry my mistake ,

 i understand that this message occur if the computer doesn't have any traffic , so ntopng purge from memory ?

**Comment by lucaderi** [comment]
Yes when hosts and flows are idle
