### ISSUE TITLE
How to put the flow data into different nodes through logstash

### ISSUE THREAD

**Issue by Howard-Chang** [ntop/ntopng#1584]
I am using logstash to ingest data and push it to elasticsearch, however could I distribute the flow data into different host(the same cluster) at the same time ?
this is the command I use:
C:\Program Files\ntopng>ntopng /c -i "tcp://127.0.0.1:2055"  --local-networks "120.127.0.0/16" -F "logstash;localhost;tcp;5510"

thank you in advance!

**Comment by Howard-Chang** [comment]
like this Schematic:
distribute flow data into different hosts, to reduce the risk that if one host crash all system crash. 
![image](https://user-images.githubusercontent.com/19474557/33470765-065ccd74-d6a5-11e7-9c30-fbf196ae1cf8.png)

**Comment by simonemainardi** [comment]
If you are looking for a way to distribute flows across multiple downstream collectors, have a look at nProbe. You can send flows to multiple downstream collectors (e.g., NetFlow or Kafka collectors) in a round-robin fashion or by sending the same flow to each collector.
