### ISSUE TITLE
Error identifying  "Application"

### ISSUE THREAD

**Issue by ubun3t** [ntop/ntopng#1585]
Hi all, Is possible change how to NTOP identify a "Application" ? For example, I have all UDP 9995 (Netflow)  how bittorrent.

Thanks in advance.

**Comment by emanuele-f** [comment]
Hi, you can do this with the `--ndpi-protocols` option. Please see https://www.ntop.org/ndpi/configuring-ndpi-for-custom-protocol-detection/

**Comment by ubun3t** [comment]
Ok, thanks!

**Comment by emanuele-f** [comment]
You are welcome
