### ISSUE TITLE
Ntopng with Netflow Cisco

### ISSUE THREAD

**Issue by lisaeka** [ntop/ntopng#1586]
Hi everybody. 
I want to know how to connect ntopng with netflow cisco router.

**Comment by emanuele-f** [comment]
Hi, you have to install both nprobe and ntopng. nprobe will receive the netfllow traffic and send it to ntopng. You can run both on the local machine this way:

sudo ntopng -i "tcp://127.0.0.1:5556"
sudo nprobe -i none -n none --collector-port 2055 --zmq "tcp://127.0.0.1:5556"

Then instruct your cisco router to export flows to the machine ip, port 2055

For more information, please see our user guide https://github.com/ntop/ntopng/blob/dev/doc/UserGuide.pdf and this blog post https://www.ntop.org/nprobe/advanced-flow-collection-with-ntopng-and-nprobe/

**Comment by lisaeka** [comment]
If I also use cisco switch to connect it, what switch also should be in configuration?

**Comment by emanuele-f** [comment]
You can connect the ntopng-running machine to the switch and export the switch flows to it. Is this your question?

**Comment by lisaeka** [comment]
Hi dear,
I have connected ntopng with cisco netflow. but in the flows page, sometimes he appears and detects my client as below:
![screenshot_7](https://user-images.githubusercontent.com/34223805/33794214-1e6d2066-dcfa-11e7-9f5b-c14224e496aa.png)

and when I refresh, the page looks like the picture below:
![screenshot_8](https://user-images.githubusercontent.com/34223805/33794217-242f712a-dcfa-11e7-9dc7-cf1ef89bee79.png)

is there a solution?

**Comment by simonemainardi** [comment]
you are running an outdated version. Please, make sure to install nProbe 8.2 and ntopng 3.2 and then report

**Comment by lisaeka** [comment]
Hi,
I have updated ntopng and its nprobe. And the results are still the same as before.

**Comment by emanuele-f** [comment]
Please post some new screenshot of ntopng and the configuration you are using

**Comment by lisaeka** [comment]
Hi,
this is my configuration on ntop
![ntopng-conf](https://user-images.githubusercontent.com/34223805/33938117-c3aff544-e038-11e7-84fc-3a6b436867a8.png)
![nprobe-none-conf](https://user-images.githubusercontent.com/34223805/33938118-c70e3782-e038-11e7-8eb5-feae3f09414f.png)

and this is my configuration on cisco router
![cisco-router](https://user-images.githubusercontent.com/34223805/33938122-cde9f19a-e038-11e7-93fd-706143240714.png)

**Comment by emanuele-f** [comment]
Please remove `--pid-path` and `--daemon` from the ntopng configuration. Can you post the output of `ntopng --version` and `nprobe --version`? Do you have an nprobe licence?

**Comment by lisaeka** [comment]
I have removed the --pid-path and --daemon . but the result remains the same as above.
this is my ntopng and nprobe version:
![ntopng](https://user-images.githubusercontent.com/34223805/33944038-7dd064b8-e04d-11e7-86de-5f5daa6aad03.png)
![nprobe](https://user-images.githubusercontent.com/34223805/33944050-84e413bc-e04d-11e7-9fcd-98367b2ee2ad.png)

**Comment by emanuele-f** [comment]
Do you have valid nprobe licence? If you use the trial, the number of flows you can export is limited

**Comment by resturiani** [comment]
yes, i use that trial. Can I get the license?

**Comment by lisaeka** [comment]
yes, i use that trial. Can I get the license?

**Comment by emanuele-f** [comment]
Yes, please see https://shop.ntop.org/
