### ISSUE TITLE
[Grafana] allprotocols_bps over ZMQ won't show data points

### ISSUE THREAD

**Issue by Pixelshifter** [ntop/ntopng#1587]
Since ntopng 3.2 update which I did today, Grafana won't show the application / protocol breakdown per interface, which was working fine before the update. The throughput metrics works tho, only the L7 stuff not.

I haven't changed any settings within the ntopng webpreferences, it's still creating timeseries for L7 applications, which I can see is working in the ntopng webUI.
 
More people having this problem? How could I downgrade to perhaps solve this?

Running CentOS 7 Minimal with 

ntopng --version
v.3.2.171204    [Enterprise/Professional build]
GIT rev:        3.2-stable:ff600d98f87560711ebd2285dbea031a8877ee3d:20171204
Pro rev:        r1279
Built on:       CentOS Linux release 7.4.1708 (Core)
System Id:      5CD07F08000107D0
Platform:       x86_64
Edition:        Enterprise
License Type:   Demo
Validity:       Until Thu Dec 28 16:00:24 2017
License:        1BD79AA0386A1E2CAEB85B731CE1065F1514473224875F9BDC

 nprobe --version

Welcome to nProbe v.8.2.171204 (r5974) for x86_64-unknown-linux-gnu
with native PF_RING acceleration.
Copyright 2002-17 ntop.org

Build OS:      CentOS Linux release 7.4.1708 (Core)
SystemID:      5CD07F08000107D0
GIT rev:       8.2-stable:35061fa78586bc40255a577bea3bd596397304e8:20171204
Edition:       nProbe Pro
License:       EF997667587E7674C2201D78D975E7B81513943653BD5C3430 [valid license]
License Type:  Time-limited License
Lic. Duration: Until Fri Dec 22 12:54:13 2017 [18 days left]

systemctl status pf_ring -l
● pf_ring.service - Start/stop pfring service
   Loaded: loaded (/etc/systemd/system/pf_ring.service; enabled; vendor preset: disabled)
   Active: active (exited) since Mon 2017-12-04 11:52:40 CET; 43min left
  Process: 834 ExecStart=/etc/init.d/pf_ring start (code=exited, status=0/SUCCESS)

Dec 04 11:52:36 johannes.bos01 systemd[1]: Starting Start/stop pfring service...
Dec 04 11:52:40 johannes.bos01 pf_ring[834]: Starting PF_RING module: [  OK  ]
Dec 04 11:52:40 johannes.bos01 systemd[1]: Started Start/stop pfring service.

**Comment by simonemainardi** [comment]
I've just tried to re-test ntopng 3.2 on Centos 7 with grafana and everything works as expected:

```
[simone@develv5 tmp]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.3.1611 (Core)
Release:	7.3.1611
Codename:	Core
[simone@develv5 tmp]$ ntopng --version
v.3.2.171204	[Enterprise/Professional build]
GIT rev:	3.2-stable:af92b001b4f3af67c4b6f001824f9dbf0376ab49:20171204
Pro rev:	r1279
Built on:	CentOS Linux release 7.4.1708 (Core)
System Id:	8CCF54709208AB1B
Platform:	x86_64
Edition:	Enterprise
License Type:	Permanent
Maintenance:	Until Tue Jun 12 20:16:11 2018 [190 days left]
License:	E65E1199D06B46F95B8396AA0441C8B5152882737177D311B5
[simone@develv5 tmp]$
```

![image](https://user-images.githubusercontent.com/3397663/33555507-eb972314-d900-11e7-8001-ac5919ec01ac.png)

maybe you should try and re-add timeseries in the graph tab Metrics?

**Comment by Pixelshifter** [comment]
I did exactly that, even removed the data-source, re-added it, uninstalled the Grafana plug-in, resetted the datasource creds to the ntopng admin, nothing works. I've readded the query many times, and each time i see 'No data points', like the query won't return results (is the query incorrect??) My storage is still filling up with flow data tho, AND the other dashboard keeps working without having to remove and add the query for the 'normal' bps graph.

**Comment by simonemainardi** [comment]
check:
- grafana interval selected on the top-right corner and make sure there exist datapoints for that interval
- visit the ntopng web UI, interface charts page, and select the same interval to make sure there are data points there
- make sure rrd creation is not disabled for that interface (there's a cog page in if_stats.lua)
- make sure Timeseries are on for interfaces in the preference page

**Comment by Pixelshifter** [comment]
![timeseries settings](https://user-images.githubusercontent.com/12703535/33557473-a44af218-d907-11e7-8a30-34075aa2b529.png)

These are my settings as they were before AND after the update. I've checked all your points, in Grafana i refresh every 5 sec. Still 'no data points', but I see ntopng is the culprit because it isn't generating any time-series data after the update (even after dis- and enabling the time-series under the preferenc pane, rebooting the server, restarting nprobe and ntopng in multiple different patterns, nothing works :(

Edit: I can see in the Historical Report of ntopng GUI that there are no application statistics gathered for today (since the update), even though it's enabled in the GUI. Any more thoughts?

pic:

![ntopng app breakdown](https://user-images.githubusercontent.com/12703535/33559463-22802266-d90d-11e7-9f59-8ac3e61c2d9a.png)

**Comment by Pixelshifter** [comment]
Strange... it seems to be working... sometimes (still not from Grafana), but in my ntopng UI, under 'Traffic dashboard', I can sometimes see the day-to-day chart adding in the application breakdown data. But when i refresh the page, that particular fresh data in that chart is gone, and i only see the data BEFORE the update from this morning (see screen below). However, the real-time chart is giving accurate info, so what is going on here?
![top application traffic per day](https://user-images.githubusercontent.com/12703535/33560862-45caa896-d911-11e7-82b4-22d148b0c7de.png)

**Comment by simonemainardi** [comment]
ntopng is correctly monitoring the layer-7 but is not saving the corresponding RRDs. So the charts are shown neither in ntopng nor in grafana.

Does this behavior occur with all the interfaces? 

Can you try and toggle the interface L7 timeseries to None, save, toggle it back to Protocol and save again?

**Comment by Pixelshifter** [comment]
I've did the toggle to none and protocol. Now a day (24h) has passed since the update, the bottom left window now says that there is no data available at all. Strange... And yes, it happens on ALL interfaces.

When I check 'About ntopng' i see RRDtool version 1.4.8. Maybe the L7 proto RRD's are stored in a folder / dir which the process has no write access to or something? Logging is kinda vague so I can't see any strange things going on...

**Comment by Pixelshifter** [comment]
Update: It doesn't work at all in ntopng. Turned off timeseries, saved, turned it on. Did the same for the whole ntopng service. Could it be that a nprobe plugin or something isn't enabled by default? Cause that was updated too. Still got the pro license tho and i didn't remove anything about ndpi or l7 plug-ins. 

I went through the changelog on github, didn't noticed any change about privileges (which i thought was the case, maybe it couldn't dump the application data). I turned on SElinux tho (but that was four hours after it stopped gathering l7 proto). :( i'm confusedddddd

![no application filtering](https://user-images.githubusercontent.com/12703535/33604564-ba7eb0e2-d9b6-11e7-980d-0efb3e06c425.png)

**Comment by simonemainardi** [comment]
any chance to have a remote access to quickly check?

**Comment by Pixelshifter** [comment]
Sorry, that won't work unfortunately seeing the particular environment this machine is in. One thing I forgot tho; what did you mean with the cog on if_stats.lua? How can i see if RRDtool is active?

**Comment by simonemainardi** [comment]
> forgot tho; what did you mean with the cog on if_stats.lua?

yes

> How can i see if RRDtool is active?

make sure interface timeseries generation is ticked

**Comment by Pixelshifter** [comment]
Dear Simone,

Thanks for staying in touch. I went to if_stats.lua for each interface, clicked the cog wheel, disabled the timeseries box, saved it, waited a minute or two, re-enabled them but no difference :(

Where does ntopgng store the RRD data? I could check for myself if it perhaps is something happening within centos (like permissions). Thanks!!

Edit: nPRobe's plugin is out of the equation, cause as we checked yesterday, the 5 seconds interval graphs are correctly showing L7 proto's .

**Comment by simonemainardi** [comment]
If it was a permission issue then you would have seen errors in the output.

RRD data is stored in the data directory which defaults to /var/tmp/ntopng/<interface id>/rrd

there's a periodic script for each interface that runs every 5 minutes and creates/updates the rrds

**Comment by simonemainardi** [comment]
If it was a permission issue then you would have seen errors in the output.

RRD data is stored in the data directory which defaults to /var/tmp/ntopng/<interface id>/rrd

there's a periodic script for each interface that runs every 5 minutes and creates/updates the rrds

**Comment by Pixelshifter** [comment]
Just did a yum update to upgrade nprobe and ntopng. I was using a Enterprise trial license with --online-check, which reverted after the update. current versions are:

Welcome to nProbe v.8.2.171206 (r5975)
GIT rev:       8.2-stable:1d91fef5df763b15cdf21dd2bb8a4668333e0d1a:20171206
Edition:       nProbe Pro

ntopng
v.3.2.171206    [Enterprise/Professional build]
GIT rev:        3.2-stable:8c030243189bbdde04d2d87abdf3b98fce1ab1b8:20171206


When i logged back into the webGUI, my license didn't work and reverted to the community edition. Immediately after that my Grafana UI was showing the L7 proto's! In the timeseries preference pane i did not change a thing, it still has the slider on 'protocols' under the 'interface timeseries' section. 

Funny thing just happened, our transit provider (AMS) has a BGP steering issue which makes it impossible to reach ntop.org at this time. Is this why the --online-check doenst work and reverts me back to community? If so, i'll wait with closing this issue as this might issue might return when i'm back on ntopng enterprise.

**Comment by Pixelshifter** [comment]
Ok, so i've removed the --licence-check in my ntopng.conf so it's looking at the ntopng.license file in /etc/ so i'm back on the enterprise version. ANDDDD, Grafana stopped seeing data points and ntopng GUI (traffic dashboard) shows that the graph "Top Application Traffic Last Day View" isn't working (again). 

Here's some interesting stuff from my journalctl -u ntopng -f command:

Dec 07 12:03:06 johannes.bos01 ntopng[5206]: 07/Dec/2017 12:03:05 [Ntop.cpp:938] No allowed interface found for tcp://127.0.0.1:5556 [If Idx: 24]
Dec 07 12:03:06 johannes.bos01 ntopng[5206]: 07/Dec/2017 12:03:05 [Lua.cpp:217] Returning name [1][tcp://127.0.0.1:5556 [If Idx: 24]]
Dec 07 12:03:06 johannes.bos01 ntopng[5206]: 07/Dec/2017 12:03:05 [Ntop.cpp:938] No allowed interface found for tcp://127.0.0.1:5556 [If Idx: 0]
Dec 07 12:03:06 johannes.bos01 ntopng[5206]: 07/Dec/2017 12:03:05 [Lua.cpp:217] Returning name [2][tcp://127.0.0.1:5556 [If Idx: 0]]
Dec 07 12:03:06 johannes.bos01 ntopng[5206]: 07/Dec/2017 12:03:05 [Lua.cpp:256] ntop_select_interface() called
Dec 07 12:03:06 johannes.bos01 ntopng[5206]: 07/Dec/2017 12:03:05 [Ntop.cpp:938] No allowed interface found for tcp://127.0.0.1:5556 [If Idx: 0]


The Idx: directives are the ones that my switch exports within the flow packets. Ntopng is configured to make a unique interface per Idx. 24 is the one which i'm monitoring, and 0 is pushed too (dropped traffic). Why is it logging that it's not an allowed interface? I've tried configuring ntopng to not create an interface per IDX, but per probe (only got one), which wasn't working too. L7 traffic is still not there. 

Last thing to mention for now is that flows are pushed to their respective interface tho, so throughput etc. works, but app traffic doensn't. 

Edit: also seeing this once in a while coming back in the lastlog, where not only field 17/17 shows up, but more like 6/6 5/5 etc.

Dec 07 12:20:06 johannes.bos01 ntopng[5206]: 07/Dec/2017 12:20:06 [ParserInterface.cpp:922] Not handled ZMQ field 17/17



Edit 2: the Top Application Traffic Last Day View is working, at least showing a graph. Strange.......

**Comment by emanuele-f** [comment]
Hi, please disable verbose logging or you will miss possible errors. What's your ntopng configuration file?

**Comment by Pixelshifter** [comment]
Just want to refer to this issue https://github.com/ntop/ntopng/issues/1010. Exact same thing happening here. But.... it's not creating any L7 .rrd files in the /var/tmp/ntopng/$IF/ directory even though it's enabled in ntopng timeseries preferences.

**Comment by simonemainardi** [comment]
@Pixelshifter I'm trying to reproduce with out success.

Please, post the full ntopng output log (see page runtime status)
also ntopng --check-license

are you using the admin user?

**Comment by Pixelshifter** [comment]
1: I'm running as the admin user yes. 
2: # ntopng --check-license: Demo license
3: 18/Dec/2017 08:33:00 [Lua.cpp:7036] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/interface/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:2035: attempt to call global 'mustScanAlerts' (a nil value)]

Is constantly filling up the runtime status window (comes back 2x per minute).

4: startup params:

ntopng --interface "tcp://127.0.0.1:5556" --no-promisc "" --dns-mode "1" --local-networks "10.20.0.0/16,10.21.0.0/16,192.168.0.0/16" --sticky-hosts "local" --disable-autologout "" --http-port "8080" --dump-flows "mysql;localhost;ntopng;flows;user;pw"

**Comment by Pixelshifter** [comment]
The trial license has ended, and guess what? I can see application data points in Grafana even without the timeseries set to Protocol/catagory OR both lol... its off...

# ntopng --version
v.3.2.171211    [Enterprise/Professional build]
GIT rev:        3.2-stable:8c030243189bbdde04d2d87abdf3b98fce1ab1b8:20171211
Pro rev:        r1279
Built on:       CentOS Linux release 7.4.1708 (Core)
System Id:      5CD07F08000107D0
Platform:       x86_64
Edition:        Enterprise
License Type:   Demo
Validity:       Until Fri Dec 29 12:57:51 2017
License:        1BD79AA0386A1E2CAEB85B731CE1065F1514473224875F9BDC


Interfaces Timeseries
--
Traffic

Toggle the creation of bytes and packets timeseries.     OFF



Also, in the native GUI (ntopng) I can see the piechart with L7 proto's as well.

**Comment by Pixelshifter** [comment]
A complete reinstall of the VM it was running on solved the issue!
