### ISSUE TITLE
Verbose logging filling log files 3.2 stable

### ISSUE THREAD

**Issue by CDawson1** [ntop/ntopng#1588]
I believe this was a known issue in 3.0.x and I'd seen it resolved in some 3.1 dev versions.  However, the 3.2 stable release seems to have shifted the issue from the /var/log/ntopng/ntopng.log file to the /var/log/syslog file.

No, verbose logging is not enabled.  

Over the last 2h40m, my logfile is 10GB.  

Any idea why this issue has moved/cropped back up?

**Comment by simonemainardi** [comment]
what is your log file filled with? As verbose logging is off by default, I guess there's some error/warning that is showing up

**Comment by CDawson1** [comment]
Same issue as previously noted; netflow entries...

`ec  5 14:00:17 GB-THN-LIN-NTOP2 ntopng[1605]: 05/Dec/2017 14:00:17 [Utils.cpp:998] Posted JSON to http://localhost:9200/_bulk

Dec  5 14:00:17 GB-THN-LIN-NTOP2 ntopng[1605]: 05/Dec/2017 14:00:17 [NetworkInterface.cpp:713] [ES] { "@timestamp": "2017-12-05T13:59:03.0Z", "type": "flows", "IN_SRC_MAC": "00:00:00:00:00:00", "OUT_DST_MAC": "00:00:00:00:00:00", "IPV4_SRC_ADDR": "85.18.190.182", "IPV4_DST_ADDR": "185.18.51.11", "L4_SRC_PORT": 14438, "L4_DST_PORT": 23, "PROTOCOL": 6, "L7_PROTO": 77, "L7_PROTO_NAME": "Telnet", "TCP_FLAGS": 22, "IN_PKTS": 1, "IN_BYTES": 44, "OUT_PKTS": 1, "OUT_BYTES": 40, "FIRST_SWITCHED": 1512482343, "LAST_SWITCHED": 1512482343, "json": { "15": "x.x.x.x", "10": "3", "14": "2", "5": "0", "16": "61105", "17": "12874", "9": "32", "13": "17", "57943": "x.x.x.x" }, "CLIENT_NW_LATENCY_MS": 0.000000, "SERVER_NW_LATENCY_MS": 0.000000, "SRC_IP_COUNTRY": "IT", "SRC_IP_LOCATION": [ 1.100000, 3.500000 ], "DST_IP_COUNTRY": "GB", "DST_IP_LOCATION": [ 0.12900, 5.575802 ], "NTOPNG_INSTANCE_NAME": "GB-THN-LIN-NTOP2", "INTERFACE": "tcp:\/\/*:5556c" }
Dec  5 14:00:17 GB-THN-LIN-NTOP2 ntopng[1605]: 05/Dec/2017 14:00:17 [ElasticSearch.cpp:189] Sent 8 flow(s) to ES

Dec  5 14:00:17 GB-THN-LIN-NTOP2 ntopng[1605]: 05/Dec/2017 14:00:17 [NetworkInterface.cpp:713] [ES] { "@timestamp": "2017-12-05T13:59:12.0Z", "type": "flows", "IN_SRC_MAC": "00:00:00:00:00:00", "OUT_DST_MAC": "00:00:00:00:00:00", "IPV4_SRC_ADDR": "x.x.x.x", "IPV4_DST_ADDR": "x.x.x.x", "L4_SRC_PORT": 29624, "L4_DST_PORT": 23, "PROTOCOL": 6, "L7_PROTO": 77, "L7_PROTO_NAME": "Telnet", "TCP_FLAGS": 2, "IN_PKTS": 1, "IN_BYTES": 40, "OUT_PKTS": 0, "OUT_BYTES": 0, "FIRST_SWITCHED": 1512482352, "LAST_SWITCHED": 1512482352, "json": { "15": "x.x.x.x", "10": "4", "14": "2", "5": "0", "16": "9824", "17": "58173", "13": "24", "57943": "x.x.x.x" }, "CLIENT_NW_LATENCY_MS": 0.000000, "SERVER_NW_LATENCY_MS": 0.000000, "SRC_IP_COUNTRY": "JP", "SRC_IP_LOCATION": [ 1.783295, 5.883301 ], "DST_IP_COUNTRY": "IE", "DST_IP_LOCATION": [ -.243900, .347198 ], "NTOPNG_INSTANCE_NAME": "GB-THN-LIN-NTOP2", "INTERFACE": "tcp:\/\/*:5556c" }

Dec  5 14:00:17 GB-THN-LIN-NTOP2 ntopng[1605]: 05/Dec/2017 14:00:17 [NetworkInterface.cpp:713] [ES] { "@timestamp": "2017-12-05T13:59:09.0Z", "type": "flows", "IN_SRC_MAC": "00:00:00:00:00:00", "OUT_DST_MAC": "00:00:00:00:00:00", "IPV4_SRC_ADDR": "x.x.x.x", "IPV4_DST_ADDR": "x.x.x.x", "L4_SRC_PORT": 37909, "L4_DST_PORT": 23, "PROTOCOL": 6, "L7_PROTO": 77, "L7_PROTO_NAME": "Telnet", "TCP_FLAGS": 27, "IN_PKTS": 16, "IN_BYTES": 713, "OUT_PKTS": 14, "OUT_BYTES": 685, "FIRST_SWITCHED": 1512482347, "LAST_SWITCHED": 1512482349, "json": { "15": "x.x.x.x", "10": "3", "14": "2", "5": "16", "16": "61105", "17": "35805", "9": "32", "13": "17", "57943": "x.x.x.x" }, "CLIENT_NW_LATENCY_MS": 0.000000, "SERVER_NW_LATENCY_MS": 0.000000, "SRC_IP_COUNTRY": "GE", "SRC_IP_LOCATION": [ 4.70798, 1.724998 ], "DST_IP_COUNTRY": "GB", "DST_IP_LOCATION": [ 0.129900, 51.575802 ], "NTOPNG_INSTANCE_NAME": "GB-THN-LIN-NTOP2", "INTERFACE": "tcp:\/\/*:5556c" }
`

**Comment by simonemainardi** [comment]
as you can see from the following piece of code, the output you have should only occur in ultra-verbose mode as it is only printed with `TRACE_INFO`

```
int NetworkInterface::dumpEsFlow(time_t when, Flow *f) {
#ifndef HAVE_NEDGE
  char *json = f->serialize(true);
  int rc;

  if(json) {
    ntop->getTrace()->traceEvent(TRACE_INFO, "[ES] %s", json); <<<< this is NetworkInterface.cpp:713
    rc = ntop->getElasticSearch()->sendToES(json);
    free(json);
  } else
    rc = -1;

  return(rc);
#else
  return(-1);
#endif
```

So you should turn off any verbose level set in the ntopng configuration file.

**Comment by CDawson1** [comment]
That’s just it, as I’ve mentioned in my first post verbose logging is not on. This behavior change is a result of upgrading from our previous 3.0 stable release to the 3.2 stable release. No other configuration changes have been made.  As it was noted,  there was a “bug“ in 3.0.x for verbose logging that was fixed in 3.1. I would suggest that this problem has resurfaced and somehow moved to a different log file.

**Comment by emanuele-f** [comment]
Can you go into the "Logging" preferences and change the log level to "error", click save, and then back to normal and save? What is the content of gyour ntopng configuration file?

**Comment by CDawson1** [comment]
Logging was set to info, and that seems to have done the trick.  Interesting that the behaviour changed in that it moved from the ntopng.log to syslog files.  Don't think I'd seen any reference to that in the documentation.  I also wouldn't have expected actual netflow to be part of that logging process.  

It's currently set to normal and that's looking OK. 

At any rate, simply changing the log level in the UI seems to have resolved this particular issue.  

Thanks!

**Comment by emanuele-f** [comment]
Yes, info logging is very verbose, so it should be disabled in production.
