### ISSUE TITLE
Question regarding sending traffic to ntopng from proxy servers

### ISSUE THREAD

**Issue by capricorn80** [ntop/ntopng#1589]
Hi!

I have ntopng in same subnet as my other three proxy servers are. I want to see application layer traffic i.e the user computer is requesting webpages from the proxy.
I can see on ntopng the proxy server machines but its not showing me flows, talkers and activity.

How can I do this to see the traffic from the proxies to my ntopng?

Thanks

**Comment by Pixelshifter** [comment]
Perhaps a mirror port on the switch the proxies are attached to, and net ntopng listen on that mirror port. there are different deployment options, which in a simplified way can be viewed here: 

https://www.ntop.org/products/netflow/nprobe/

https://www.ntop.org/products/traffic-analysis/ntop/

I hope this kinda helps you further!

**Comment by capricorn80** [comment]
Thanks.

I was thinking to have some client on the proxy to send data to ntopng. Like I was reading that you can configure Netflow on Cisco devices to send data to ntopng and they you can see the flow.

**Comment by Pixelshifter** [comment]
Netflow works only on L3 devices from Cisco yes. A l2 switch could probably do sFlow (which ntop also decodes). You could also put a computer with 2 NIC's between your modem and router, slap ntopng on top of it and let it do inline (active) network monitoring. If you are trunking you could maybe put it between the vlan trunk so to instantly decode all traffic.

**Comment by capricorn80** [comment]
My ntopng is running as VM so port mirroring is not the option.

**Comment by Pixelshifter** [comment]
Couldn't you assign the VM NIC to a VLAN on your physical network, and mirror your ports where the proxies are attached to, to that VLAN?

**Comment by capricorn80** [comment]
It will be a hard setup so I guess there is no simple way as I was thinking to have some setting on the proxy servers to see the traffic flows on it from remote ntopng.

**Comment by emanuele-f** [comment]
@capricorn80 even if ntopng runs within a vm, you can possibly expose (bind) a port, see https://docs.docker.com/engine/userguide/networking/default_network/binding/ for a docker how-to.

An alternative to port mirroring is to install nprobe on your proxies and make it export flows to the ntopng server

**Comment by capricorn80** [comment]
Thanks. I have installed nprobe on windows box now. Is there any good tutorial to set it up so that it will send the data to ntopng?

**Comment by emanuele-f** [comment]
Please refer to www.ntop.org/nprobe/advanced-flow-collection-with-ntopng-and-nprobe/
