### ISSUE TITLE
NTOPNG detects only drops on eth1 

### ISSUE THREAD

**Issue by JuergenWeber** [ntop/ntopng#159]
I need some help to get to the source of this issue:
NTOPNG detects only drops on eth1 but traffic on eth0 is being recognized, as well as the tcpdump file from eth1 ().
Strange, isn't it? What can cause drops to occur? 
System is RHEL6 on VMWare:
{
  "stats_bytes":0,
  "flows":0,
  "networkinterface":"eth1",
  "version_ndpi":"1.6.0-dev-66-12f89ff",
  "gathering":"pcap",
  "uptime":684,
  "aggregations":0,
  "kernel_ver":"2.6.32-573.1.1.el6.x86_64",
  "installdir":"/usr/share/ntopng",
  "version_ntop":"2.0.150611 ",
  "workingdir":"/var/tmp/ntopng",
  "packets":0,
  "drops":48868
}

**Comment by lucaderi** [comment]
Looks like an old ntopng. Please update first and if not working please specify how you started ntopng

**Comment by JuergenWeber** [comment]
Unfortunately, updating to "2.0.150911" didn't help.
NTOPNG is started via "service ntopng start". Here's the ntop.conf:

-G=/var/tmp/ntopng.pid
# tells ntop the user id to run as
--user ntop5

#save messages into the system log
--use-syslog=daemon

# sets the directory that ntop runs from
--db-file-path /var/lib/ntop

# --data-dir=/var/tmp/ntopng

# the amount and severity of messages that ntop will put out
--trace-level 1

# limit ntop to listening on a specific interface and port
--http-port=3003

# disables "phone home" behavior
--skip-version-check

### Set the protocol list (name and ports to be monitored)
-p=/etc/ntopng/protos.txt


### Interface(s) that ntop will capture on (default: eth0)
#--interface /var/www/html/tcpdump/tpeiap90.pcap
--interface eth1

--no-interface-merge

--dns-mode=1
### Logging messages to syslog (instead of the console):
####  NOTE: To log to a specific facility, use --use-syslog=local3
####  NOTE: The = is REQUIRED and no spaces are permitted.
--use-syslog=local3

### Sets program to run as a daemon
--daemon

-e

#verbose
#-v
--disable-login=1

# 0 - No aggregations (default)
# 1 - Enable aggregations, no timeline dump
# 2 - Enable aggregations, with timeline
--enable-aggregations=2

# enable historical data
#-F=db


-m=10.163.130.0/24
-B=ip && !(ip multicast || ether broadcast) && !((src net 10.163.130.0/24) && (dst net 10.163.130.0/24))

**Comment by lucaderi** [comment]
I can't follow you. In this example you are capturing from eth1, so I do not understand what is the problem with eth0

**Comment by lucaderi** [comment]
Please reopen the bug if you can reproduce it
