### ISSUE TITLE
Page "/lua/Â " was not found

### ISSUE THREAD

**Issue by jsoref** [ntop/ntopng#1591]
ntopng                               3.3.171205-3846
From http://packages.ntop.org/apt/stretch x64/ Packages

On the /lua/if_stats.lua?page=pools page (Manage Pools), clicking "View" yields:
Page "/lua/Â " was not found

         datatableForEachRow("#table-create", function() {
...
            var pool_link = $("td:nth-child(7)", $(this)).html();
-> pool_link = "&nbsp;"
...
              datatableAddLinkButtonCallback.bind(this)(7, pool_link, "View");
that passes through

**Comment by emanuele-f** [comment]
Fixed with commit 4cd147da6767c758c75d20e647b6ca74e73788c2 . Thank you for reporting!
