### ISSUE TITLE
 Script "/usr/share/ntopng/scripts/lua/if_stats.lua" returned an error:  /usr/share/ntopng/scripts/lua/modules/host_pools_utils.lua:20: attempt to call global 'haveNedge2' (a nil value)

### ISSUE THREAD

**Issue by cfrancis2b** [ntop/ntopng#1593]
Este error se esta presentando con las ultimas versiones de ntopng al querer consultar o editar los hosts pools.
This error is presented with the latest versions of ntopng when you want to consult or edit the hosts pools.

 Script "/usr/share/ntopng/scripts/lua/if_stats.lua" returned an error:

/usr/share/ntopng/scripts/lua/modules/host_pools_utils.lua:20: attempt to call global 'haveNedge2' (a nil value)

**Comment by emanuele-f** [comment]
Hi, this is now fixed, thank you for reporting. Please update to the new version, which will be available in one hour.
