### ISSUE TITLE
Local networks disappeared

### ISSUE THREAD

**Issue by vg0426** [ntop/ntopng#1594]
Hi guys I’ve set up ntopng version 3.3 and define several local networks on the config file, when I start the service I can see the networks on the web interface but after a few seconds they start going away and only the remote networks remain and all the local networks defined gone. I’ve check the log file and there is no error showing

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by emanuele-f** [comment]
Hi, local networks expire if there is there is no traffic for some time. What's your configuration file? Do you see still traffic when all the networks disappear?

**Comment by vg0426** [comment]
hi emanuele below is some info about the instance am running, for certain reasons some data was mask with #####, another thing to notice: like i said before when i go to url #.#.#.#:#/lua/network_stats.lua all defined local networks show only for a few seconds after the service starts and then disappear from this url but if i go to url #.#.#.#:#/lua/hosts_stats.lua?network=3 or url #.#.#.#:#/lua/network_details.lua?network=3&page=historical i can see all hosts for the third defined network the same applies if i change the urls to network=2 or network=1 and so on for all defined local networks, also all displayed hosts in this urls are showing traffic passing.

Version	3.3.171207 - Professional Edition
Platform	Debian stretch/sid [x86_64][Ubuntu 16.04.3 LTS] - 64 bit
Startup Line	ntopng --interface "eno2" --local-networks "#.#.#.0/22,#.#.#.0/21,#.#.#.0/21,#.#.#.0/22,#.#.#.0/24"

Last Log Trace
08/Dec/2017 08:31:48 [PeriodicActivities.cpp:102] Each periodic activity script will use 2 threads
08/Dec/2017 08:31:46 [PeriodicActivities.cpp:59] Started periodic activities loop...
08/Dec/2017 08:31:46 [Ntop.cpp:713] Adding fe80::222:19ff:fec7:f382/64 as IPv6 local network for eno2
08/Dec/2017 08:31:46 [Ntop.cpp:704] Adding fe80::222:19ff:fec7:f382/128 as IPv6 interface address for eno2
08/Dec/2017 08:31:46 [NtopPro.cpp:479] [LICENSE] Maintenance:	Until Sat May 12 19:57:44 2018 [155 days left]
08/Dec/2017 08:31:46 [NtopPro.cpp:469] [LICENSE] License:	#######################################
08/Dec/2017 08:31:46 [NtopPro.cpp:466] [LICENSE] License Type:	Permanent License
08/Dec/2017 08:31:46 [NtopPro.cpp:465] [LICENSE] Edition:	Professional
08/Dec/2017 08:31:46 [NtopPro.cpp:464] [LICENSE] System Id:	############
08/Dec/2017 08:31:46 [Ntop.cpp:395] Built on Ubuntu 16.04.3 LTS
08/Dec/2017 08:31:46 [Ntop.cpp:385] Welcome to ntopng x86_64 v.3.3.171207 - (C) 1998-17 ntop.org
08/Dec/2017 08:31:46 [main.cpp:385] Scripts/HTML pages directory: /usr/share/ntopng
08/Dec/2017 08:31:46 [main.cpp:383] Working directory: /var/tmp/ntopng
08/Dec/2017 08:31:46 [HTTPserver.cpp:915] HTTP server listening on port(s) 3000
08/Dec/2017 08:31:46 [HTTPserver.cpp:912] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
08/Dec/2017 08:31:46 [Utils.cpp:457] User changed to nobody
08/Dec/2017 08:31:46 [HTTPserver.cpp:841] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
08/Dec/2017 08:31:46 [main.cpp:301] PID stored in file /var/run/ntopng.pid
08/Dec/2017 08:31:46 [Ntop.cpp:1612] Registered interface eno2 [id: 1]
08/Dec/2017 08:31:46 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.7.1.0 interface eno2...
08/Dec/2017 08:31:46 [HostPools.cpp:346] WARNING: JSON Parse error [unexpected end of data] key: ntopng.prefs.1.host_pools.dump: { "sent": { "packets": 60427891, "bytes": 62654735098 }, "rcvd": { "packets": 44583605, "bytes": 20977007791 }, "ndpi": { "Unknown": { "duration": 1100, "bytes": { "sent": 1826818223, "rcvd": 1157342655 }, "packets": { "sent": 3430626, "rcvd": 2558643 } }, "FTP_CONTROL": { "duration": 220, "bytes": { "sent": 254652, "rcvd": 17648 }, "packets": { "sent": 4064, "rcvd": 265 } }, "POP3": { "duration": 1100, "bytes": { "sent": 152908782, "rcvd": 7779718 }, "packets": { "sent": 110834, "rcvd": 72301 } }, "SMTP": { "duration": 1100, "bytes": { "sent": 11021439, "rcvd": 27387634 }, "packets": { "sent": 26751, "rcvd": 31238 } }, "IMAP": { "duration": 1100, "bytes": { "sent": 116767613, "rcvd": 28936735 }, "packets": { "sent": 94960, "rcvd": 79273 } }, "DNS": { "duration": 1100, "bytes": { "sent": 25827221, "rcvd": 20271063 }, "packets": { "sent": 206150, "rcvd": 125338 } }, "HTTP": { "duration": 1100, "bytes": { "sent": 7315571132, "rcvd": 1694862305 }, "packets": { "sent": 5819399, "rcvd": 4492290 } }, "MDNS": { "duration": 60, "bytes": { "sent": 1256, "rcvd": 0 }, "packets": { "sent": 12, "rcvd": 0 } }, "NTP": { "duration": 1100, "bytes": { "sent": 8247204, "rcvd": 4628936 }, "packets": { "sent": 91132, "rcvd": 41546 } }, "NetBIOS": { "duration": 1100, "bytes": { "sent": 502927, "rcvd": 237378 }, "packets": { "sent": 5131, "rcvd": 1846 } }, "NFS": { "duration": 960, "bytes": { "sent": 508568, "rcvd": 1597026 }, "packets": { "sent": 4958, "rcvd": 2521 } }, "SSDP": { "duration": 550, "bytes": { "sent": 17842, "rcvd": 73913 }, "packets": { "sent": 85, "rcvd": 168 } }, "BGP": { "duration": 195, "bytes": { "sent": 3247, "rcvd": 3228 }, "packets": { "sent": 37, "rcvd": 37 } }, "SNMP": { "duration": 1100, "bytes": { "sent": 477072, "rcvd": 1544576 }, "packets": { "sent": 4472, "rcvd": 11491 } }, "SMB": { "duration": 1095, "bytes": { "sent": 933497, "rcvd": 506784 }, "packets": { "sent": 12762, "rcvd": 4310 } }, "Syslog": { "duration": 1100, "bytes": { "sent": 1774460, "rcvd": 23361211 }, "packets": { "sent": 17981, "rcvd": 26514 } }, "DHCP": { "duration": 55, "bytes": { "sent": 6490, "rcvd": 0 }, "packets": { "sent": 11, "rcvd": 0 } }, "MySQL": { "duration": 40, "bytes": { "sent": 57481, "rcvd": 18193 }, "packets": { "sent": 95, "rcvd": 91 } }, "Hotmail": { "duration": 605, "bytes": { "sent": 1065748, "rcvd": 469298 }, "packets": { "sent": 2291, "rcvd": 2256 } }, "POPS": { "duration": 1095, "bytes": { "sent": 177495926, "rcvd": 8106311 }, "packets": { "sent": 156136, "rcvd": 106957 } }, "DirectConnect": { "duration": 35, "bytes": { "sent": 943, "rcvd": 0 }, "packets": { "sent": 7, "rcvd": 0 } }, "COAP": { "duration": 20, "bytes": { "sent": 260, "rcvd": 0 }, "packets": { "sent": 4, "rcvd": 0 } }, "SMTPS": { "duration": 205, "bytes": { "sent": 142274, "rcvd": 1548483 }, "packets": { "sent": 1289, "rcvd": 1374 } }, "UBNTAC2": { "duration": 1070, "bytes": { "sent": 127140, "rcvd": 73014 }, "packets": { "sent": 1216, "rcvd": 347 } }, "eDonkey": { "duration": 240, "bytes": { "sent": 672408, "rcvd": 97439 }, "packets": { "sent": 735, "rcvd": 597 } }, "BitTorrent": { "duration": 1100, "bytes": { "sent": 5724254, "rcvd": 6006547 }, "packets": { "sent": 42220, "rcvd": 13131 } }, "QQ": { "duration": 1100, "bytes": { "sent": 81401133, "rcvd": 8969346 }, "packets": { "sent": 75070, "rcvd": 57987 } }, "RTSP": { "duration": 5, "bytes": { "sent": 13920, "rcvd": 0 }, "packets": { "sent": 232, "rcvd": 0 } }, "IMAPS": { "duration": 1100, "bytes": { "sent": 323847140, "rcvd": 77920436 }, "packets": { "sent": 275567, "rcvd": 198321 } }, "PPLive": { "duration": 590, "bytes": { "sent": 32497735, "rcvd": 4379444 }, "packets": { "sent": 29828, "rcvd": 9499 } }, "PPStream": { "duration": 10, "bytes": { "sent": 78, "rcvd": 1200 }, "packets": { "sent": 1, "rcvd": 20 } }, "HTTP_Download": { "duration": 1095, "bytes": { "sent": 9260953, "rcvd": 7922536 }, "packets": { "sent": 12914, "rcvd": 12675 } }, "SSL_No_Cert": { "duration": 1100, "bytes": { "sent": 106674878, "rcvd": 45170480 }, "packets": { "sent": 124311, "rcvd": 106579 } }, "IRC": { "duration": 15, "bytes": { "sent": 740, "rcvd": 441 }, "packets": { "sent": 9, "rcvd": 6 } }, "Unencrypted_Jabber": { "duration": 675, "bytes": { "sent": 590538, "rcvd": 255541 }, "packets": { "sent": 1281, "rcvd": 1205 } }, "MSN": { "duration": 1100, "bytes": { "sent": 21811058, "rcvd": 12121578 }, "packets": { "sent": 38011, "rcvd": 41588 } }, "Oscar": { "duration": 55, "bytes": { "sent": 59432, "rcvd": 66351 }, "packets": { "sent": 109, "rcvd": 101 } }, "Yahoo": { "duration": 1100, "bytes": { "sent": 293084422, "rcvd": 67859159 }, "packets": { "sent": 320489, "rcvd": 257470 } }, "Steam": { "duration": 1090, "bytes": { "sent": 239739, "rcvd": 138974 }, "packets": { "sent": 778, "rcvd": 1089 } }, "Telnet": { "duration": 1100, "bytes": { "sent": 6015248, "rcvd": 1567626 }, "packets": { "sent": 99000, "rcvd": 21378 } }, "STUN": { "duration": 1100, "bytes": { "sent": 112137475, "rcvd": 70197657 }, "packets": { "sent": 216814, "rcvd": 180961 } }, "IPsec": { "duration": 1100, "bytes": { "sent": 626567797, "rcvd": 984723262 }, "packets": { "sent": 1667640, "rcvd": 1660324 } }, "GRE": { "duration": 1100, "bytes": { "sent": 165978406, "rcvd": 22627574 }, "packets": { "sent": 135084, "rcvd": 89970 } }, "ICMP": { "duration": 1100, "bytes": { "sent": 61929017, "rcvd": 27005624 }, "packets": { "sent": 596151, "rcvd": 265456 } }, "OSPF": { "duration": 585, "bytes": { "sent": 10660, "rcvd": 0 }, "packets": { "sent": 118, "rcvd": 0 } }, "RTP": { "duration": 1100, "bytes": { "sent": 224715830, "rcvd": 306843010 }, "packets": { "sent": 863549, "rcvd": 900841 } }, "RDP": { "duration": 1095, "bytes": { "sent": 3385426, "rcvd": 3649057 }, "packets": { "sent": 19555, "rcvd": 17572 } }, "VNC": { "duration": 125, "bytes": { "sent": 108839, "rcvd": 8250 }, "packets": { "sent": 1808, "rcvd": 126 } }, "PcAnywhere": { "duration": 15, "bytes": { "sent": 180, "rcvd": 0 }, "packets": { "sent": 3, "rcvd": 0 } }, "SSL": { "duration": 1100, "bytes": { "sent": 12114943259, "rcvd": 2556289611 }, "packets": { "sent": 10430719, "rcvd": 7557338 } }, "SSH": { "duration": 1100, "bytes": { "sent": 82489903, "rcvd": 11908686 }, "packets": { "sent": 117747, "rcvd": 90025 } }, "TFTP": { "duration": 120, "bytes": { "sent": 0, "rcvd": 2472 }, "packets": { "sent": 0, "rcvd": 24 } }, "SIP": { "duration": 1100, "bytes": { "sent": 50423930, "rcvd": 26397086 }, "packets": { "sent": 89277, "rcvd": 52467 } }, "ICMPV6": { "duration": 750, "bytes": { "sent": 42049, "rcvd": 16734 }, "packets": { "sent": 365, "rcvd": 213 } }, "LDAP": { "duration": 400, "bytes": { "sent": 978253, "rcvd": 61787 }, "packets": { "sent": 689, "rcvd": 653 } }, "MsSQL-TDS": { "duration": 935, "bytes": { "sent": 1548831, "rcvd": 148671 }, "packets": { "sent": 24751, "rcvd": 962 } }, "PPTP": { "duration": 10, "bytes": { "sent": 560, "rcvd": 428 }, "packets": { "sent": 6, "rcvd": 4 } }, "Slack": { "duration": 1055, "bytes": { "sent": 49101718, "rcvd": 2698070 }, "packets": { "sent": 38310, "rcvd": 23653 } }, "Facebook": { "duration": 1100, "bytes": { "sent": 6088990367, "rcvd": 2174513317 }, "packets": { "sent": 5869263, "rcvd": 4815334 } }, "Twitter": { "duration": 1100, "bytes": { "sent": 46918814, "rcvd": 26455236 }, "packets": { "sent": 57113, "rcvd": 54003 } }, "Dropbox": { "duration": 1100, "bytes": { "sent": 89014682, "rcvd": 36394939 }, "packets": { "sent": 91759, "rcvd": 78349 } }, "GMail": { "duration": 1100, "bytes": { "sent": 162359801, "rcvd": 57095213 }, "packets": { "sent": 177486, "rcvd": 145449 } }, "GoogleMaps": { "duration": 290, "bytes": { "sent": 1458443, "rcvd": 368193 }, "packets": { "sent": 1418, "rcvd": 1209 } }, "YouTube": { "duration": 1100, "bytes": { "sent": 4927615420, "rcvd": 2537282470 }, "packets": { "sent": 4494438, "rcvd": 3746307 } }, "Skype": { "duration": 1100, "bytes": { "sent": 66926754, "rcvd": 21514301 }, "packets": { "sent": 109390, "rcvd": 108217 } }, "Google": { "duration": 1100, "bytes": { "sent": 7296338109, "rcvd": 2580448232 }, "packets": { "sent":
08/Dec/2017 08:31:46 [NtopPro.cpp:139] [LICENSE] /etc/ntopng.license: found valid Professional license
08/Dec/2017 08:31:46 [NtopPro.cpp:136] [LICENSE] /etc/ntopng.license: unable to validate Enterprise license [License mismatch error]
08/Dec/2017 08:31:46 [NtopPro.cpp:223] [LICENSE] Reading license from /etc/ntopng.license
08/Dec/2017 08:31:37 [AddressResolution.cpp:61] Address resolution stats [0 resolved][0 failures]
08/Dec/2017 08:31:37 [NetworkInterface.cpp:2353] Cleanup interface eno2
08/Dec/2017 08:31:35 [NetworkInterface.cpp:616] Flushing host contacts for interface eno2
08/Dec/2017 08:31:35 [HTTPserver.cpp:929] HTTP server terminated
08/Dec/2017 08:31:35 [main.cpp:65] Deleted PID /var/run/ntopng.pid: [rc: -1][Permission denied]
08/Dec/2017 08:31:35 [Ntop.cpp:1659] Interface eno2 [running: 0]
08/Dec/2017 08:31:35 [PF_RINGInterface.cpp:142] Terminated packet polling for eno2

**Comment by emanuele-f** [comment]
Hi, can you give me more information about your local networks? If possible, please send me an an email at `faranda@ntop.org`. Otherwise, please specify:
1) Does any of your local networks include another? E.g. `192.168.0.0/16` includes `192.168.1.0/24`
2) Are your local networks normalized? E.g. `192.168.10.3/24` is not normalized, whereas `192.168.10.0/24` is
3) If you change the sort column on the networks table, can you see any difference?

**Comment by emanuele-f** [comment]
@vg0426 how many local/remote hosts do you have roughly? I see a limitation of 32768 on the code which handles grouping, which can be the cause of the problem

**Comment by vg0426** [comment]
Hi emanuele-f I have around 30000 hosts grouped in different local networks and none of the networks is overlapping with any of the other ones. Anyhow I tried one of your recommendations of sorting the local networks list and since then none has disappeared so thanks for the tip 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by emanuele-f** [comment]
@vg0426 thank you for reporting. This is definitely related to issue #1599, so please follow that issue for updates
