### ISSUE TITLE
Script "/usr/share/ntopng/scripts/lua/if_stats.lua" returned an error:   (Host Pools)

### ISSUE THREAD

**Issue by cfrancis2b** [ntop/ntopng#1596]
Este error se ha presentado en las ultimas versiones de ntopng; No se puede clasificar pools, como no se puede generar gráficos de la interface principal.

_Script "/usr/share/ntopng/scripts/lua/if_stats.lua" returned an error:
/usr/share/ntopng/scripts/lua/if_stats.lua:19: attempt to call global 'haveNedge2' (a nil value)_

This error has been presented in the latest versions of ntopng;  Can't do classify pools, as you can not generate graphics from the main interface.

**Comment by cfrancis2b** [comment]
ntopng.x86_64                              3.3.171208-3708        @ntop         
ntopng-data.noarch                      3.3.171208-3708        @ntop-noarch
pfring.x86_64                               7.1.0-1596             @ntop         
pfring-dkms.noarch                      7.1.0-1596             @ntop-noarch  

Linux XXXXXX 3.10.0-693.11.1.el7.x86_64 #1 SMP Mon Dec 4 23:52:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tomukasteris** [comment]
Tried many times but get the same problem.

**Comment by simonemainardi** [comment]
thanks for reporting, issue is fixed now

**Comment by maravento** [comment]
No fix yet
![problem](https://user-images.githubusercontent.com/14880802/54142516-e506fe00-43f5-11e9-819b-08c1b13ce8d1.png)
