### ISSUE TITLE
[Lua.cpp:125] NULL interface: did you restart ntopng in the meantime?

### ISSUE THREAD

**Issue by tomukasteris** [ntop/ntopng#1597]
Hello,

Why I get this message and how to fix it?

[Lua.cpp:125] NULL interface: did you restart ntopng in the meantime?

My config:

ntopng --daemon "" --interface "eth1" --https-port "3005" --local-networks "192.168.0.0/16" --dns-mode "1" --data-dir "/var/tmp/ntopng" --sticky-hosts "all" --disable-autologout ""

**Comment by emanuele-f** [comment]
Hi, what ntopng version are you using?

**Comment by tomukasteris** [comment]
Hello,

Version:
ntopng Community/Embedded Edition v.3.3.171210

<img width="1500" alt="ntopng_log" src="https://user-images.githubusercontent.com/11430578/33844955-cd7fab5a-de99-11e7-85a0-12f27d18505a.png">

**Comment by emanuele-f** [comment]
Hi, these messages are normal, please change logging level to normal from the ntopng preferences
