### ISSUE TITLE
Host groups are partial (when the number of hosts is high)

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#1599]
Hosts groups (e.g. Networks, ASn, Countries) are generated by creating dynamic support arrays to perform the aggregations and sort. For example, NetworkInterface::sortHosts support array has a limit of CONST_MAX_NUM_HITS (32768) entries. When the actual number of hosts is greater that 32768, the aggragated view will only reflect a portion of the actual hosts.

The solution to this is not to increase that limit but rather to rework aggregations to avoid using such big support arrays.

**Comment by simonemainardi** [comment]
The only thing left to remove is 

```
$ egrep -r get_grouped_hosts_data scripts/
scripts//lua/os_stats.lua:print [[/lua/get_grouped_hosts_data.lua?grouped_by=os]]
```

Operating Systems must be handled as another per-interface hash table, e.g., see `include/AutonomousSystemHash.h include/VlanHash.h`

Then, a `get_countries_data.lua` must be implemented and called from the datatable shown in http://develv5:3000/lua/os_stats.lua

For reference, see the implementation of how autonomous systems, or vlans, are handled.

**Comment by simonemainardi** [comment]
Remember to cleanup the code once done. That is, throw get_grouped_hosts_data.lua and related functions which will be no longer used.

**Comment by simonemainardi** [comment]
You should implement a method like `as = iface->getAS(&ip, true /* Create if missing */, true /* Inline call */))` for the operating system.

Each instance of `Host` will have a pointer to the OperatingSystem, .i.e., OperatingSystem os will become a pointer to an entry in the operating systems hash. Set this pointer in `setOS` and don't forget to increase/decrease reference counters.
