### ISSUE TITLE
enhancement request - mark malicious traffic as bad in kibana

### ISSUE THREAD

**Issue by AlekMarkus** [ntop/ntopng#160]
mark malicious traffic as bad in kibana

**Comment by lmangani** [comment]
Hi Alek,

The beauty of using Kibana is nobody can limit your ways of using it. This is one such case for something the enduser/implementor can achieve in too many ways to list - ntop does not maintain any Kibana presets at the moment (but we might in the future)

**Comment by AlekMarkus** [comment]
sorry , maybe i didnt understand... luca wrote : 

" we can mark this traffic as bad in kibana. Please file an enhancement request "

**Comment by lmangani** [comment]
Re-Opening. I suppose this will be about exporting an additional JSON field with the rating value.

**Comment by AlekMarkus** [comment]
Thank you ! :)

**Comment by lmangani** [comment]
@lucaderi do we already have an internal value to create ad fill new field with?

**Comment by lucaderi** [comment]
Inside the JSON attribute PASS_VERDICT you can read if the flow can pass or has to be dropped.
