### ISSUE TITLE
unable to open 'Manage Users'

### ISSUE THREAD

**Issue by r1bnc** [ntop/ntopng#1600]
I am using Firefox 57 with ublock origin and noscript (whitelisted ofcourse) and yet  I cannot view/edit passwords at '**Manage Users**' Tried this with mobile devices too. Please do not suggest to use other browsers. The ntopng is freshly installed.
![userpw](https://user-images.githubusercontent.com/8337343/33917147-8415174e-dfe7-11e7-812a-118875ea4146.png)

**Comment by emanuele-f** [comment]
Hi, please update to the latest version before submitting issues. Your page seems broken (see the icons) because of some plugin, so please disable all of them and retry.

**Comment by r1bnc** [comment]
it is now updated but still the same. The `Manage Users` work if I use Chromium not Firefox 57 or older firefox (with or without Addons like uBlock,Noscipt)

**Comment by emanuele-f** [comment]
Hi, I have 57.0.2 and it works for me. Please try to start with a clean browser
