### ISSUE TITLE
Ntopng Integration With Nagios

### ISSUE THREAD

**Issue by resturiani** [ntop/ntopng#1602]
Hallo everyone.
I want to do ntopng integration with nagios. Where Nagios I use to provide notification. and I follow the steps from here https://support.nagios.com/kb/article.php?id=96#Ubuntu.
but in this section:
![image](https://user-images.githubusercontent.com/22189485/33947391-db250f20-e056-11e7-8e37-9be25d8fe814.png)
when the extract appears error.

And when I run this command,
![image](https://user-images.githubusercontent.com/22189485/33947467-00d54f46-e057-11e7-9094-756013af4b19.png)
it's even an error and ./ not available.
is there a solution?

**Comment by simonemainardi** [comment]
that is a nagios issue, not an nopng one. Please refer to the nagios folks.

**Comment by resturiani** [comment]
Allright.
Now, I'm following your tutorial video. when i follow the command below,
![image](https://user-images.githubusercontent.com/22189485/33992197-3e9b84e6-e104-11e7-8308-b4ab12089e88.png)

on my linux there is no such file. what is wrong and how to solve it?

**Comment by resturiani** [comment]
Allright.
now, i follow your tutorial video about ntopng integration with nagios.
when i follow this command:
![image](https://user-images.githubusercontent.com/22189485/33994501-49c86150-e10d-11e7-9296-6786909be24c.png)

in my linux did not find the file. the results are as below:
![image](https://user-images.githubusercontent.com/22189485/33994529-65f04b86-e10d-11e7-88ed-c36b237d8a84.png)
what is the problem and how to solve it?

**Comment by simonemainardi** [comment]
you have to create the file and intsall nsca. Please refer to this post that explains everything:

https://www.ntop.org/guides/ntopng-integration-with-nagios/
