### ISSUE TITLE
Lua Api Documentation help

### ISSUE THREAD

**Issue by sidsamant** [ntop/ntopng#1603]
Hi,
  

   In ntopng\scripts\lua\API.lua, line 107, it says to read from "ntop_get_interface_flows_info documentation" for more information.

  I am not able to figure out where the detailed documentation is. Could you please help me in the right direction?

  Apologies for my lack of knowledge.
   
Thanks in advance,
Sid

**Comment by emanuele-f** [comment]
Hi, sorry but we currently lack a well documented lua api. I suggest you to look at the following sources:

General information about Lua scripting in ntopng
- https://github.com/simonemainardi/ntopng-docker/blob/master/Linux%20Day%2028%20Ottobre%202017.pdf

Hosts/Flows related api methods
- https://github.com/ntop/ntopng/blob/dev/src/Lua.cpp#L6587

Internal api methods
- https://github.com/ntop/ntopng/blob/dev/src/Lua.cpp#L6741

General purpose Lua utility functions
- https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/lua_utils.lua

Please feel free to ask us more information and to propose a pull request if you develop some script that could be helpful for other people in the ntop community

**Comment by sidsamant** [comment]
Thanks for the links. They look sufficient for now.
