### ISSUE TITLE
Time range in NTOPNG

### ISSUE THREAD

**Issue by ubun3t** [ntop/ntopng#1604]
Hi, 
I have NTOPNG running in South America but I am in EU. When I connect to the web interface the time in the dashboard and in traffic report is wrong. I would like to see the time the remote country. How can I do it?¿
The photo is taken at 12pm in Spain.
Thanks in advance,

![captura de pantalla de 2017-12-14 12-05-24](https://user-images.githubusercontent.com/16337441/33989334-6f2de56e-e0c7-11e7-9ec1-66a554226c83.png)
![time_range01](https://user-images.githubusercontent.com/16337441/33989335-6f62dfa8-e0c7-11e7-9c6c-7e9e2e3cb88d.png)

**Comment by ubun3t** [comment]
Hi, I have changed the time of my PC to the time of the destination country but still the range is wrong. If I select 1h for the report and it is 1:25 a.m., NTOP shows the report starting from 2:30 a.m. until 3:30 a.m. ....¿??¿

How can I change this? I need a report and with the wrong time I can not do it.

ntopng Professional Edition v.3.3.171205


![captura de pantalla de 2017-12-18 01-34-46](https://user-images.githubusercontent.com/16337441/34094672-73354dd2-e3ce-11e7-8541-6cef89dc78aa.png)

**Comment by ubun3t** [comment]
nobody? this means that cannot see the correct time in reports?

**Comment by emanuele-f** [comment]
@ubun3t  sorry for the late reply, I've added the possibility to get the report dates in server time zone.

![screenshot](https://user-images.githubusercontent.com/5488003/35513715-3ae8d37a-0504-11e8-8cfb-8e734b5d50d3.png)

![screenshot_1](https://user-images.githubusercontent.com/5488003/35513719-3c8b5266-0504-11e8-93ad-eaa1aee278b5.png)

The new package will be available in one hour. If you experience other issues please open a separate bug.
