### ISSUE TITLE
Network discovery not working on Raspbian Stretch

### ISSUE THREAD

**Issue by kuestess** [ntop/ntopng#1605]
Upgraded my Raspberry Pi from Jessie to Stretch.  Recompiled and installed under Stretch, but network discovery no longer works.  Consistently states 'A network discovery is in progress. The page will refresh periodically.' in the web interface, however no updated discovery data is ever populated.  Log states Lua.cpp:6559] [Discover] Started triggered discovery on interface eth1, so it appears to start, but doesn't appear to do anything.  This was working perfectly under Jessie on the same Pi.  Any help appreciated.

**Comment by emanuele-f** [comment]
```
Jan 29 14:44:20 raspberrypi ntopng[21333]: 29/Jan/2018 14:44:20 [Lua.cpp:2222] ERROR: Unable to enable capabilities
Jan 29 14:44:20 raspberrypi ntopng[21333]: [Lua.cpp:2222] ERROR: Unable to enable capabilities
```

**Comment by emanuele-f** [comment]
We've got two differents bugs here. Fixed with commits:

6ebdcc33d6141a14f0812840745d5d7ca98c445a
691a50922291992d5f967b8894a26b1cfd826e57

Ps. please wait for the next raspberry build
