### ISSUE TITLE
Community Edition and Bridging

### ISSUE THREAD

**Issue by espigle** [ntop/ntopng#1608]
I can't for the life of me make bridging work with the community edition, whether installed from the latest stable binaries (Ubuntu 16.04) or installing from source here from GitHub. I'm trying to do a 2+1 setup as indicated here: https://github.com/ntop/ntopng/blob/dev/doc/README.inline

Interestingly if I run in professional mode (which of course only runs for 10 minutes), it will start up fine with bridged mode. If I pass the --community switch, though, it's a big no go. Here is what it tells me from the command line:

16/Dec/2017 16:30:29 [PacketBridge.cpp:52] WARNING: [LICENSE] Your license is not valid
16/Dec/2017 16:30:29 [PacketBridge.cpp:53] WARNING: [LICENSE] and thus no bridging can be enabled
16/Dec/2017 16:30:30 [main.cpp:236] ERROR: An exception occurred during interface creation: bridge:enp1s5,enp1s6
16/Dec/2017 16:30:30 [main.cpp:286] ERROR: Startup error: missing super-user privileges ?

The above is when running using the binaries. If I compile from source, it doesn't show the first two lines. So is specifying a switch like "-i "bridge:enp1s5,enp1s6" --community" not possible with the community edition? If not, do I just need to setup a bridge with Ubuntu behind the scenes, and then point to that interface with the -i switch? Any help is appreciated. Thanks.

**Comment by simonemainardi** [comment]
Bridging is a pro-only feature. You can create a bridge with brctl and then start ntopng with -i <bridge name> but that won't allow you to do traffic policing, just passive monitoring.

**Comment by espigle** [comment]
Perfect--passive monitor is all I'm after, anyway. I'll work through setting up the bridge on the Linux side and get things to going. Thanks!
