### ISSUE TITLE
missing shared library librrd.so.8 on latest version of CentOS 7

### ISSUE THREAD

**Issue by ruachemman** [ntop/ntopng#1609]
Hi there, I've installed ntopng from the ntop.org repository on CentOS 7 but on starting the service it's missing a shared library librrd.so.8. I am trying to integrate Ntopng with Observium

**Comment by emanuele-f** [comment]
That is strange, on CentOS 7 latest ntopng is linked agains librrd 4:

```
ldd `which ntopng` | grep rrd
	librrd.so.4 => /lib64/librrd.so.4 (0x00007f157713c000)
```

Which ntopng version are you using? Have you followed the istructions at `http://packages.ntop.org/centos/`?

**Comment by ruachemman** [comment]
Hi emanuele, I uninstalled and used the http://packages.ntop.org/centos/ and got it to work. Cheers
