### ISSUE TITLE
create Tile Map in Kibana - No Compatible Fields: The "ntopng-*" index pattern does not contain

### ISSUE THREAD

**Issue by AlekMarkus** [ntop/ntopng#161]
how can i send more information to elastichSearch   ? i want to create Tile Map , when i select Aggregation i have an error message : 

No Compatible Fields: The "ntopng-*" index pattern does not contain any of the following field types: geo_point

im using 

ntopng Community v.2.0.150910 (Package ntopng-2.0.150910-430.x86_64)

**Comment by lmangani** [comment]
Check if the geo field is correctly mapped as geo_point in Kibana for the index in question

**Comment by AlekMarkus** [comment]
do i need to configure in ntopng more than this ? : 

-F=es;flows;ntopng-%Y.%m.%d;http://10.1.1.20:9200/_bulk 

becuase i cant see geo field at kibana

those are the fields that i have : 


![geo](https://cloud.githubusercontent.com/assets/13960741/9793932/e041c750-57f0-11e5-8f71-5cae62e6c3cf.png)

**Comment by pcmerc** [comment]
The ES output doesn't have the geoip info. I've managed to force ntopng to output the lat/lon by editing the src/Flow.cpp but output isn't correct as elasticsearch pukes on trying to add a visual with JAVA integer errors. Comparing the data to another correctly working instance the lat/lon data is not correct.

Working instance example: geoip.location  -121.89500000000001, 37.33940000000001

Non-working example: DST_IP_LOCATION  34.044, -118.251

If ntopng was outputting the for DST_IP_LOCATION in the same format as the above geoip.location, it will work with the default logstash-template.json that I use

{
  "template" : "ntopng-*",
  "settings" : {
    "index.refresh_interval" : "5s"
  },
  "mappings" : {
    "_default_" : {
       "_all" : {"enabled" : true},
       "dynamic_templates" : [ {
         "string_fields" : {
           "match" : "*",
           "match_mapping_type" : "string",
           "mapping" : {
             "type" : "string", "index" : "analyzed", "omit_norms" : true,
               "fields" : {
                 "raw" : {"type": "string", "index" : "not_analyzed", "ignore_above" : 256}
               }
           }
         }
       } ],
       "properties" : {
         "@version": { "type": "string", "index": "not_analyzed" },
         "geoip"  : {
           "type" : "object",
             "dynamic": true,
             "path": "full",
             "properties" : {
               "location" : { "type" : "geo_point" }
             }
         },
         "geoip"  : {
           "type" : "object",
             "dynamic": true,
             "path": "full",
             "properties" : {
               "location" : { "type" : "geo_point" }
             }
         }
       }
    }
  }
}

**Comment by AlekMarkus** [comment]
so what we should do ? :) wait till it will be fixed from DST_IP_LOCATION to geoip.location  ?


Thanks,
Alek

**Comment by lucaderi** [comment]
@AlekMarkus @lmangani Lorenzo please tell me how shall I format the value un JSON (you're the expert) and I will write the patch.

**Comment by lmangani** [comment]
Will do!

**Comment by lmangani** [comment]
Value format should be a float with Latitude, Longitude values, ie:

```
"geoip.coordinates": [ -50.6667,-32.99 ]
```

The field name should not be critical, but its type should be correctly mapped as geo_point for the Index in question, ie:

```
{
  "ntopng-2015.09.17" : {
    "mappings" : {
      "ntopng" : {
        "geoip.location" : {
          "full_name" : "geoip.location",
          "mapping":{"location":{"type":"geo_point"}}
        }
      }
    }
  }
}
```

Most likely a new index will have to be created if there is previous mappings for the same field with a different/wrong type (ie: float). Alternatively, one could delete the old index pattern and add the new index pattern from Kibana4 Settings menu and verify if geoip.location field is showing as "geo_point"

Any optional/additional/overkill maxmind/geo values could also be maintained under the same geoip tree, ie:

```
"geoip": {
      "ip": "xx.yy.zz",
      "country_code2": "NL",
      "country_code3": "NLD",
      "country_name": "Netherlands",
      "continent_code": "EU",
      "region_name": "07",
      "city_name": "Amsterdam",
      "postal_code": "1000",
      "latitude": 52.349999999999994,
      "longitude": 4.916699999999992,
      "timezone": "Europe/Amsterdam",
      "real_region_name": "Noord-Holland",
      "location": [
        4.916699999999992,
        52.349999999999994
      ],
    }
```

My 2 cents, comments welcome!

**Comment by lucaderi** [comment]
ntopng is inserting fields like DST_IP_LOCATION as an array of doubles
See Flow.cpp
    json_object_array_add(location, json_object_new_double(srv_host->get_latitude()));
      json_object_array_add(location, json_object_new_double(srv_host->get_longitude()));
      json_object_object_add(my_object, "DST_IP_LOCATION", location);
 
So what do you want me to do? Looks like the code is already in good shape.

**Comment by lmangani** [comment]
User should confirm if mapping was corrected in indexing, or updated it using [https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html](PUT Mapping API) for instance:

```
$ curl -XPUT 'http://localhost:9200/ntopng-2015.09.17/_mapping/ntopng' -d '
{
    "ntopng" : {
        "properties" : {
            "DST_IP_LOCATION" : {
                "type" : "geo_point"
            }
        }
    }
}
'
```

This should do the trick. My proposal is to have ntopng create the correct mappings on index creation, will propose a patch internally to do so.

**Comment by pcmerc** [comment]
@lmangani I use logstash for other things. ntopng output's to it's own index so it doesn't conflict. I was using that info earlier as an example. I'll remove the current testing index & do some testing with what you've shared.

**Comment by lmangani** [comment]
@pcmerc thanks! we can use any result or confirmation to make this automated going forward

**Comment by pcmerc** [comment]
Looks like some code was updated. Compiling new pull now.

**Comment by pcmerc** [comment]
@lmangani using what you suggested as a test:
$ curl -XPUT 'http://localhost:9200/ntopng-2015.09.17/_mapping/ntopng' -d '
{
    "ntopng" : {
        "properties" : {
            "DST_IP_LOCATION" : {
                "type" : "geo_point"
            }
        }
    }
}
'

I cleared ES, updated nDPI & Ntopng to lastest. Ran ntopng which I can see dumping into the new index it created.

The DST_IP_LOCATION is type: number

So it's not type: geoip

I also notice that if I apply the code you suggested while it's acknowledged no problem that DST_IP_LOCATION field now shows a conflict because it's defined as multiple types across indices.
After clearing the indices that error goes away but type is still number.

**Comment by lmangani** [comment]
@pcmerc could you try apply this query to your *current* index, without clearing

**Comment by lmangani** [comment]
This ultimately works for me - Could you please try using the following template mapping:

```
curl -XPUT localhost:9200/_template/ntopng_template -d '
{
    "template" : "ntopng-*",
    "mappings" : {
        "ntopng" : {
                "dynamic_templates": [
		        { "ntopng_geopoint": { 
		            "match": "*_IP_LOCATION",
		            "mapping": {
		              "type": "geo_point",
		              "geohash": false
		            }
		        }}
     		 ]
        }
    }
}
'
```

(Make sure the index field list is refreshed in Kibana)

**Comment by AlekMarkus** [comment]
hey lorenzo , 

is it possible to create a Test rpm package to packages.ntop.org ? and i will update from there.

and test.


Best Regards,
Alek

**Comment by lucaderi** [comment]
Overnight new packages will be built

**Comment by AlekMarkus** [comment]
1. i have updated to the last version : 2.0.150927-497

2. i have used template mapping like @lmangani wrote

3. index field list is refreshed in Kibana

still doesn't work.

Alek

**Comment by lmangani** [comment]
@AlekMarkus did you create a new index after the template was planted? This will not work with existing indexes unfortunately but it will for new ones

**Comment by AlekMarkus** [comment]
@lmangani i have deleted now , and recreate again index ntopng-* 

i cannot see geo_point .. still doesn't work 


![ntop](https://cloud.githubusercontent.com/assets/13960741/10126179/540f5eca-6595-11e5-9fbb-5540cdfc34c2.png)

**Comment by lmangani** [comment]
The issue in your case seems to be with the type used. The template expects type "ntopng" but you are using "flows" as in an older example. 
<pre>
_type	  	flows
type	  	flows
</pre>

Please correct either template or ntopng syntax and mapping should work

**Comment by AlekMarkus** [comment]
ok i have changed -F syntax and now its 
t_type  ntopngttype  ntopngstill doesn't work.
i will try to delete all and re-create 
Date: Mon, 28 Sep 2015 03:36:27 -0700

**Comment by lmangani** [comment]
@AlekMarkus Ok, on index creation check a random entry and make sure the type is now "ntopng"

<pre>es;ntopng;ntopng-%Y.%m.%d;http://localhost:9200/_bulk;</pre>

**Comment by AlekMarkus** [comment]
Working. :) thank you

**Comment by lmangani** [comment]
#186 should further improve the situation by placing the @timestamp field first in ES packets

**Comment by AlekMarkus** [comment]
good morning @lmangani i have update ntopng to the last version + using yours json template for mapping : 
https://github.com/lmangani/ntopng-output-elasticsearch/blob/master/ntopng-es-template.json

and everything working great.

Tile map can be created and there is no more DST_IP_LOCATION@timestamp

Thank you :+1:  :+1:

**Comment by lmangani** [comment]
@AlekMarkus thank you for trying and confirming back!

**Comment by pcmerc** [comment]
Looks good, thanks Imangani! :D

**Comment by lmangani** [comment]
Thank you @pcmerc and @AlekMarkus for helping us improve ntopng's Elasticsearch support. Automatic templating is on the way!

**Comment by smitjainsj** [comment]
Hello Guyz, I need your help on this same issue.

Do I need to create separate template for geo_point field missing ?

currently my index name is : non-prod

ELK5 is what I am using .

**Comment by simonemainardi** [comment]
geo_point is already supported in the default template pushed to ES:

https://github.com/ntop/ntopng/blob/dev/httpdocs/misc/ntopng_template_elk.json#L14
