### ISSUE TITLE
Can't login to the webpage of ntopng

### ISSUE THREAD

**Issue by ruachemman** [ntop/ntopng#1611]
After entering the username and password (default) it just refreshes and doesn't login. Tried Chrome, Opera, IE and even Edge, still didn't work. Has anyone encountered such issues? Sorry if this question has been asked as I'm a newbie setting this up.

**Comment by emanuele-f** [comment]
Hi, the default username and password is "admin". Do you have any extensions to disable/block javascript ?

**Comment by ruachemman** [comment]
I've been able to solve this by changing the password of the default account. Still couldn't figure out why the default credentials wouldn't work.
