### ISSUE TITLE
Traffic Profiles disabled in the interface

### ISSUE THREAD

**Issue by ffbarcelos** [ntop/ntopng#1612]
Hi,

After registering Traffic Profiles, the icon does not appear in the interface, as shown below.

![barrantop](https://user-images.githubusercontent.com/33551829/34205349-1a1bbc9e-e569-11e7-9263-cbb29da9b178.png)

v.3.3.171219    [Enterprise/Professional build]

**Comment by simonemainardi** [comment]
Traffic profiles are a pro-only feature. So if you are using ntopng in Pro demo mode, then they will disappear after 10 minutes when the software toggles back to community.

Is this your case?

**Comment by ffbarcelos** [comment]
No, I have a ntopng Professional license.

**Comment by ffbarcelos** [comment]
Any solution?

**Comment by emanuele-f** [comment]
Fixed with 2e9a9a9efa4952ee06c34f0025da27d9550c3b6a . A new package will be available in one our.
