### ISSUE TITLE
Update pfSense Package from 3.0 release to 3.2 release

### ISSUE THREAD

**Issue by clevelandcs** [ntop/ntopng#1615]
What is the release cycle for the pfSense package? I see 3.2 was released in May but the current package in the pfSense package manager is 3.0. I would like to update to 3.2 so I can use the official Grafana plugin to pull metrics alongside my other data rather than accessing the dashboard and clicking through screens. I don't know how to go about doing this myself but I would imagine it wouldn't be too difficult as the pfSense package should be just a few tweaks on the FreeBSD package.

Thanks!

**Comment by emanuele-f** [comment]
Hi, please contact the pfsense mantainers, see https://forum.pfsense.org/index.php?topic=131504.0 for a similar discussion
