### ISSUE TITLE
Unable to define local networks

### ISSUE THREAD

**Issue by BravoFox** [ntop/ntopng#1616]
Currently only able to keep NTOP running when i remove the switch for local network definition. I noticed when i change that, the user running NTOP turns to root when its enable, and back to nobody when its disabled. It's currently running fine without defining local networks.

**Comment by emanuele-f** [comment]
Hi, please post your ntopng configuration file. The option to define local networks is `-m`

**Comment by BravoFox** [comment]
-G=/var/run/ntopng.pid
# -e=
-i=p1p1
-i=p1p2
-i=p1p3
# -w=3000
#--local-networks="172.XX.0.0/16,192.168.0.0/16"

**Comment by emanuele-f** [comment]
What happens exactly when you enable the local networks? Can you reach the ntopng gui?

**Comment by BravoFox** [comment]
The process gets killed every few seconds. It just cycles through that. I've noticed the user changes to root when it happens, but that seems to be the only thing I've noticed. I've uninstalled and reinstalled with no change either.

**Comment by emanuele-f** [comment]
Can you see any error into the ntopng log? Please check out `journalctl -u ntopng`

**Comment by BravoFox** [comment]
Dec 22 12:45:55 NTOP.asmhq.local systemd[1]: ntopng.service failed.
Dec 22 12:46:00 NTOP.asmhq.local systemd[1]: ntopng.service holdoff time over, scheduling restart.
Dec 22 12:46:00 NTOP.asmhq.local systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
Dec 22 12:46:00 NTOP.asmhq.local systemd[1]: Started ntopng high-speed web-based traffic monitoring and analysis tool.
Dec 22 12:46:00 NTOP.asmhq.local ntopng[16910]: 22/Dec/2017 12:46:00 [Ntop.cpp:1485] Setting local networks to 172.30.0.0/16,192.168.0.0/16
Dec 22 12:46:00 NTOP.asmhq.local ntopng[16910]: 22/Dec/2017 12:46:00 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
Dec 22 12:46:00 NTOP.asmhq.local ntopng[16910]: 22/Dec/2017 12:46:00 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
Dec 22 12:46:00 NTOP.asmhq.local ntopng[16910]: 22/Dec/2017 12:46:00 [NtopPro.cpp:221] [LICENSE] Reading license from Redis
Dec 22 12:46:00 NTOP.asmhq.local ntopng[16910]: 22/Dec/2017 12:46:00 [NtopPro.cpp:136] [LICENSE] CC3A621B9E0D7B7921A2DA24B74981E515215742805972AD78: unable to validate Enterprise license [L
Dec 22 12:46:00 NTOP.asmhq.local ntopng[16910]: 22/Dec/2017 12:46:00 [NtopPro.cpp:139] [LICENSE] CC3A621B9E0D7B7921A2DA24B74981E515215742805972AD78: found valid Professional license
Dec 22 12:46:05 NTOP.asmhq.local systemd[1]: ntopng.service: main process exited, code=killed, status=11/SEGV
Dec 22 12:46:05 NTOP.asmhq.local systemd[1]: Unit ntopng.service entered failed state.
Dec 22 12:46:05 NTOP.asmhq.local systemd[1]: ntopng.service failed.
Dec 22 12:46:10 NTOP.asmhq.local systemd[1]: ntopng.service holdoff time over, scheduling restart.
Dec 22 12:46:10 NTOP.asmhq.local systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
Dec 22 12:46:10 NTOP.asmhq.local systemd[1]: Started ntopng high-speed web-based traffic monitoring and analysis tool.
Dec 22 12:46:10 NTOP.asmhq.local ntopng[16977]: 22/Dec/2017 12:46:10 [Ntop.cpp:1485] Setting local networks to 172.30.0.0/16,192.168.0.0/16
Dec 22 12:46:10 NTOP.asmhq.local ntopng[16977]: 22/Dec/2017 12:46:10 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
Dec 22 12:46:10 NTOP.asmhq.local ntopng[16977]: 22/Dec/2017 12:46:10 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
Dec 22 12:46:10 NTOP.asmhq.local ntopng[16977]: 22/Dec/2017 12:46:10 [NtopPro.cpp:221] [LICENSE] Reading license from Redis
Dec 22 12:46:10 NTOP.asmhq.local ntopng[16977]: 22/Dec/2017 12:46:10 [NtopPro.cpp:136] [LICENSE] CC3A621B9E0D7B7921A2DA24B74981E515215742805972AD78: unable to validate Enterprise license [L
Dec 22 12:46:10 NTOP.asmhq.local ntopng[16977]: 22/Dec/2017 12:46:10 [NtopPro.cpp:139] [LICENSE] CC3A621B9E0D7B7921A2DA24B74981E515215742805972AD78: found valid Professional license
Dec 22 12:46:15 NTOP.asmhq.local systemd[1]: ntopng.service: main process exited, code=killed, status=11/SEGV
Dec 22 12:46:15 NTOP.asmhq.local systemd[1]: Unit ntopng.service entered failed state.
Dec 22 12:46:15 NTOP.asmhq.local systemd[1]: ntopng.service failed.
Dec 22 12:46:20 NTOP.asmhq.local systemd[1]: ntopng.service holdoff time over, scheduling restart.
Dec 22 12:46:20 NTOP.asmhq.local systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
Dec 22 12:46:20 NTOP.asmhq.local systemd[1]: Started ntopng high-speed web-based traffic monitoring and analysis tool.
Dec 22 12:46:20 NTOP.asmhq.local ntopng[17047]: 22/Dec/2017 12:46:20 [Ntop.cpp:1485] Setting local networks to 172.30.0.0/16,192.168.0.0/16
Dec 22 12:46:20 NTOP.asmhq.local ntopng[17047]: 22/Dec/2017 12:46:20 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
Dec 22 12:46:20 NTOP.asmhq.local ntopng[17047]: 22/Dec/2017 12:46:20 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
Dec 22 12:46:20 NTOP.asmhq.local ntopng[17047]: 22/Dec/2017 12:46:20 [NtopPro.cpp:221] [LICENSE] Reading license from Redis
Dec 22 12:46:20 NTOP.asmhq.local ntopng[17047]: 22/Dec/2017 12:46:20 [NtopPro.cpp:136] [LICENSE] CC3A621B9E0D7B7921A2DA24B74981E515215742805972AD78: unable to validate Enterprise license [L
Dec 22 12:46:20 NTOP.asmhq.local ntopng[17047]: 22/Dec/2017 12:46:20 [NtopPro.cpp:139] [LICENSE] CC3A621B9E0D7B7921A2DA24B74981E515215742805972AD78: found valid Professional license
Dec 22 12:46:25 NTOP.asmhq.local systemd[1]: ntopng.service: main process exited, code=killed, status=11/SEGV
Dec 22 12:46:25 NTOP.asmhq.local systemd[1]: Unit ntopng.service entered failed state.
Dec 22 12:46:25 NTOP.asmhq.local systemd[1]: ntopng.service failed.
Dec 22 12:46:30 NTOP.asmhq.local systemd[1]: ntopng.service holdoff time over, scheduling restart.
Dec 22 12:46:30 NTOP.asmhq.local systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
Dec 22 12:46:30 NTOP.asmhq.local systemd[1]: Started ntopng high-speed web-based traffic monitoring and analysis tool.
Dec 22 12:46:30 NTOP.asmhq.local ntopng[17117]: 22/Dec/2017 12:46:30 [Ntop.cpp:1485] Setting local networks to 172.30.0.0/16,192.168.0.0/16
Dec 22 12:46:30 NTOP.asmhq.local ntopng[17117]: 22/Dec/2017 12:46:30 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
Dec 22 12:46:30 NTOP.asmhq.local ntopng[17117]: 22/Dec/2017 12:46:30 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
Dec 22 12:46:30 NTOP.asmhq.local ntopng[17117]: 22/Dec/2017 12:46:30 [NtopPro.cpp:221] [LICENSE] Reading license from Redis
Dec 22 12:46:30 NTOP.asmhq.local ntopng[17117]: 22/Dec/2017 12:46:30 [NtopPro.cpp:136] [LICENSE] CC3A621B9E0D7B7921A2DA24B74981E515215742805972AD78: unable to validate Enterprise license [L
Dec 22 12:46:30 NTOP.asmhq.local ntopng[17117]: 22/Dec/2017 12:46:30 [NtopPro.cpp:139] [LICENSE] CC3A621B9E0D7B7921A2DA24B74981E515215742805972AD78: found valid Professional license
Dec 22 12:46:35 NTOP.asmhq.local systemd[1]: ntopng.service: main process exited, code=killed, status=11/SEGV
Dec 22 12:46:35 NTOP.asmhq.local systemd[1]: Unit ntopng.service entered failed state.
Dec 22 12:46:35 NTOP.asmhq.local systemd[1]: ntopng.service failed.

**Comment by BravoFox** [comment]
it literally worked for about 5 minutes, then when i changed the networks to add one more it failed again. Same exact problem. Changes user to root, then fails.

**Comment by emanuele-f** [comment]
Hi, if possibly, please run ntopng through the gdb debugger and get a trace of the crash. You can do this:
1) Stop your running ntopng instance: `systemctl stop ntopng`
2) Run ntopng through the debugger: `gdb --args ntopng /etc/ntopng/ntopng.cong`
3) When it crashes, please execute `bt` to get a backtrace. Please post the backtrace here.

**Comment by BravoFox** [comment]
Sorry just got back from leave. Ill do it today.

**Comment by BravoFox** [comment]
It looks like the latest update fixed the problem, because after updating again im not getting the same issues as before.

Thanks!

**Comment by emanuele-f** [comment]
Thank you for reporting!
