### ISSUE TITLE
ntopng crashes when implementing mysql (Windows)

### ISSUE THREAD

**Issue by jsstaedtler** [ntop/ntopng#1617]
ntopng has been working well for me so far, but I'm now trying to add mysql to the mix.  But every time I try adding it in with the -F argument, ntopng crashes on startup.  This is as far as it gets from the command line:

```
c:\Program Files\ntopng>ntopng /c --community -n 1 -i 2 -F "mysql;localhost;ntopng;flows;ntopng;password"
Starting ntopng
Running ntopng.
22/Dec/2017 12:09:50 [Ntop.cpp:1485] Setting local networks to 127.0.0.0/8
22/Dec/2017 12:09:50 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
22/Dec/2017 12:09:50 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
22/Dec/2017 12:09:50 [PcapInterface.cpp:88] Reading packets from interface {16476E3D-40B1-4525-B090-343B431C3847}...
22/Dec/2017 12:09:50 [PcapInterface.cpp:93] WARNING: Unable to set packet capture direction

c:\Program Files\ntopng>
```

Then Windows will pop up its usual crash dialog with "ntopng.exe has stopped working".

This is on Windows 10 x64, with the ntopng-3.2.171203-x64 build installed.  I've tried installing a variety of mysql components in case something might be missing, below are all of those.  I haven't had any trouble shelling into the server and creating the DB (and test tables) with the "ntopng" DB user.

![image](https://user-images.githubusercontent.com/2999462/34306742-bb8aad6a-e712-11e7-9f2c-b5401bcc35d8.png)

And if it helps, this is all I can find in the Event Viewer for the crash:

> Faulting application name: ntopng.exe, version: 0.0.0.0, time stamp: 0x5a23deb7
> Faulting module name: ntopng.exe, version: 0.0.0.0, time stamp: 0x5a23deb7
> Exception code: 0xc0000409
> Fault offset: 0x000000000026bcd0
> Faulting process id: 0x2314
> Faulting application start time: 0x01d37b48bf787bb6
> Faulting application path: c:\Program Files\ntopng\ntopng.exe
> Faulting module path: c:\Program Files\ntopng\ntopng.exe
> Report Id: af09cfa3-ecb8-4c51-b4ab-b764bad94994
> Faulting package full name: 
> Faulting package-relative application ID:

**Comment by jsstaedtler** [comment]
I managed to get it running correctly on a Windows 7 machine, so there must be something in Windows 10 mucking things up.

I configured everything on the WIn10 machine like it was on Win7 (basically default settings everywhere), but it made no difference.  Looking at the operating and error logs for mysql, it appears there's no attempt to access mysql at all.  So ntopng is dying before it even gets that far.

So does this indicate a bug in the current ntopng build on Win10?  I'd be happy to provide any further info or troubleshooting if needed.

**Comment by jsstaedtler** [comment]
Just for fun, I set Windows 7 compatibility mode on ntopng.exe.  No improvement.

**Comment by emanuele-f** [comment]
Hi, I've tested ntopng 3.2.171215 on Windows 10 with mysql option and it works for me. The mysql version I'm using is 5.7.12 . Can you please update to ntopng 3.2.171215 and report if it works for you too?

**Comment by jsstaedtler** [comment]
Success!  Thanks for the tip, the 3.2.171215 version cured my issue.
