### ISSUE TITLE
ipv4 listen

### ISSUE THREAD

**Issue by deadElk** [ntop/ntopng#162]
hi.

neither stable nor dev branches of ntopng listening to tcp4 port. only for tcp6 port. and no command-line switches like in ntop - --ipv4 --ipv6 

tcp6       0      0 *.3080                 *.*                    LISTEN

ntopng_flags="--http-port=3080 --https-port=3443 --dns-mode=3 --interface=em1 --daemon --local-networks='10.0.0.0/8,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,196.168.0.0/16' --disable-autologout --dump-flows='mysql;mysql;ntopng;flows-;ntopng;ntopng' --dump-hosts=all --dump-aggregations=all --sticky-hosts=all"

tried on linux rpm/dev/src and on freebsd from git (dev-branch compiles OK) 

thanx.

**Comment by lucaderi** [comment]
Sure?

deri@i7 204> ./ntopng --http-port=3080 --https-port=3443


deri@i7 205> netstat -na | grep 3080
tcp6       0      0 :::3080                 :::*                    LISTEN     
deri@i7 206> telnet localhost 3080
Trying ::1...
Connected to localhost.localdomain.
Escape character is '^]'.


^]
telnet> quit
Connection closed.
deri@i7 207> telnet 127.0.0.1 3080
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.

No we do not have IPv4/IPv6 flags, correct.

**Comment by deadElk** [comment]
[root@traf ~]# netstat -na | grep 3080
tcp6       0      0 *.3080                 *.*                    LISTEN
[root@traf ~]# telnet localhost 3080
Trying ::1...
Connected to localhost.
Escape character is '^]'.
GET /

HTTP/1.1 500 Server Error
Content-Length: 42
Connection: close

Error 500: Server Error
Bad request: [GET]Connection closed by foreign host.
[root@traf ~]# telnet 127.0.0.1 3080
Trying 127.0.0.1...

telnet: connect to address 127.0.0.1: Operation timed out
telnet: Unable to connect to remote host
[root@traf ~]#

**Comment by lucaderi** [comment]
# curl -v http://localhost:3080
* Rebuilt URL to: http://localhost:3080/
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3080 (#0)
> GET / HTTP/1.1
> Host: localhost:3080
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Set-Cookie: session=; path=/; expires=Thu, 01-Jan-1970 00:00:01 GMT; max-age=0; HttpOnly
< Location: /lua/login.lua?referer=/
* no chunk, no close, no size. Assume close to signal end
< 

# curl -v "http://[::1]:3080"
* Rebuilt URL to: http://[::1]:3080/
*   Trying ::1...
* Connected to ::1 (::1) port 3080 (#0)
> GET / HTTP/1.1
> Host: [::1]:3080
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Set-Cookie: session=; path=/; expires=Thu, 01-Jan-1970 00:00:01 GMT; max-age=0; HttpOnly
< Location: /lua/login.lua?referer=/
* no chunk, no close, no size. Assume close to signal end
< 
* Closing connection 0

It works for me.

**Comment by deadElk** [comment]
for me - not 
because ntopng not listening to tcp4 
how can i force ntopng to listen tcp4? 
may be patch for sources or something? 


[root@traf ~]# curl -v http://[::1]:3080                                                                                                                                                                      
* Rebuilt URL to: http://[::1]:3080/
*   Trying ::1...
* Connected to ::1 (::1) port 3080 (#0)
> GET / HTTP/1.1
> Host: [::1]:3080
> User-Agent: curl/7.44.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Set-Cookie: session=; path=/; expires=Thu, 01-Jan-1970 00:00:01 GMT; max-age=0; HttpOnly
< Location: /lua/login.lua?referer=/
* no chunk, no close, no size. Assume close to signal end
< 
* Closing connection 0
[root@traf ~]# curl -v http://127.0.0.1:3080
* Rebuilt URL to: http://127.0.0.1:3080/
*   Trying 127.0.0.1...

**Comment by lucaderi** [comment]
On what platform? Is the firewall ok? Can you debug it a bit to assist us reproducing the issue on our end?

**Comment by deadElk** [comment]
freebsd 10.1, then updated to freebsd 10.2 - nothing changed 
firewall disabled 

what can i do to debug?

**Comment by lucaderi** [comment]
This is not a FreeBSD shop, we need to install a box and try to see what happens, or please give us a remote access to your box.

**Comment by deadElk** [comment]
same thing was on debian 
will resurrect debian-box now ... 
i installed ntopng from repository and started 
ntopng only listen to tcp6 
it's not related to OS

**Comment by lucaderi** [comment]
please allow a remote login as on Linux we can't reproduce it.

**Comment by deadElk** [comment]
ok. i will

**Comment by deadElk** [comment]
issue solved. 

the key is sysctl net.inet6.ip6.v6only=0 for freebsd 
and sysctl net.ipv6.bindv6only=0 for linux 
thanx for your time. 

P.S.: may be it needs to be in doc's?

**Comment by lmangani** [comment]
Note taken for updating the docs, thanks for the confirmation!

**Comment by lucaderi** [comment]
@deadElk Now I am happy as this explains why on the same platform we observed different behaviours.

**Comment by deadElk** [comment]
+1

**Comment by lucaderi** [comment]
https://github.com/ntop/ntopng/commit/12ed781f2eb718382ef7c7eeec6d599ea18f7d49
