### ISSUE TITLE
problem installing ntopng 3.2.0  on Linux Mint 18.3

### ISSUE THREAD

**Issue by jfbourdeau** [ntop/ntopng#1621]
I want to use ntopng 3.2.0 ( https://www.ntop.org/get-started/download/ )  on linux mint 18.3

I can't  install the last version found here : http://packages.ntop.org/apt/ 

dpkg: error processing archive apt-ntop.deb (--install):
 trying to overwrite '/etc/nbox/ntop-apt.key', which is also in package apt-ntop-stable 2.6-899
abort-install
Errors were encountered while processing:
 apt-ntop.deb

the version that works for now is

v.2.3.160415 works well ( installed it like this sudo apt-get install ntopng )

JF

Tks !!

**Comment by lucaderi** [comment]
You need to install either apt-ntop or apt-ntop-stable but not at the same time. In other words you cannot have simultaneously stable and dev packages, either one or another. We've added an extra check in packages that will hopefully spot this problem earlier, and that will be available in the next overnight build
