### ISSUE TITLE
Incorrect type for IPv4 fields in Elasticsearch dump

### ISSUE THREAD

**Issue by sidsamant** [ntop/ntopng#1622]
Hi,
   
   ES6.1, Fedora 26, Ntopng v.3.1.171005 and custom UI.

   I am not able to find the template from [https://github.com/ntop/ntopng/blob/dev/httpdocs/misc/ntopng_template_elk.json](url)

 ` GET /_template/ntopng-* ` yields `{}`
 
  `GET /_mapping` yields the following mapping :

`"ntopng-2017.12.31":{"aliases":{},"mappings":{"ntopng":{"properties":{"@timestamp":{"type":"date"},"CLIENT_NW_LATENCY_MS":{"type":"float"},"DNS_QUERY":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"DST_IP_COUNTRY":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"DST_IP_LOCATION":{"type":"float"},"FIRST_SWITCHED":{"type":"long"},"HTTP_HOST":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"HTTP_METHOD":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"HTTP_RET_CODE":{"type":"long"},"HTTP_URL":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"INTERFACE":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"IN_BYTES":{"type":"long"},"IN_PKTS":{"type":"long"},"IN_SRC_MAC":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"IPV4_DST_ADDR":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"IPV4_SRC_ADDR":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"IPV6_DST_ADDR":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"IPV6_SRC_ADDR":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"L4_DST_PORT":{"type":"long"},"L4_SRC_PORT":{"type":"long"},"L7_PROTO":{"type":"long"},"L7_PROTO_NAME":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"LAST_SWITCHED":{"type":"long"},"NTOPNG_INSTANCE_NAME":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"OUT_BYTES":{"type":"long"},"OUT_DST_MAC":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"OUT_PKTS":{"type":"long"},"PROTOCOL":{"type":"long"},"SERVER_NW_LATENCY_MS":{"type":"float"},"SRC_IP_COUNTRY":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"SRC_IP_LOCATION":{"type":"float"},"SSL_SERVER_NAME":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"TCP_FLAGS":{"type":"long"},"type":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}}},"settings":{"index":{"creation_date":"1514681097164","number_of_shards":"5","number_of_replicas":"1","uuid":"g5U3zHuMSL6lDjMLhCxb4A","version":{"created":"6000099"},"provided_name":"ntopng-2017.12.31"}}}`

 ` IPV4_DST_ADDR` type should have been `ip`

   Following error occurs when I try `PUT /_template/ntopng` with the template in above link :
 
`{
    "error": {
        "root_cause": [
            {
                "type": "mapper_parsing_exception",
                "reason": "Failed to parse mapping [_default_]: No field type matched on [text], possible values are [object, string, long, double, boolean, date, binary]"
            }
        ],
        "type": "mapper_parsing_exception",
        "reason": "Failed to parse mapping [_default_]: No field type matched on [text], possible values are [object, string, long, double, boolean, date, binary]",
        "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "No field type matched on [text], possible values are [object, string, long, double, boolean, date, binary]"
        }
    },
    "status": 400
}`

    As per closed issue [https://github.com/ntop/ntopng/issues/548](url) , mapping should have been set correctly by ntopng if it has admin rights. It does have admin rights in my case.

   Not sure where I am doing it wrong. I am hoping that my queries using the IP4* fields become faster if the data type is `ip`.

Thanks,
Sid

**Comment by simonemainardi** [comment]
You don't have to manually push the template, ntopng will push it automatically upon startup. Update ntopng to either 3.2 or 3.3.

Just tried with 3.3 and everything works smoothly. I cleared all the indices and templates to make sure the template was pushed.

```
simone@simone-VirtualBox-1:~$ curl "http://localhost:9200/_cat/templates?v"
name template order version
```

Then as soon as I started ntopng I got the new template:
```
simone@simone-VirtualBox-1:~/nDPI$ curl "http://localhost:9200/_cat/templates?v"
name            template order version
ntopng_template ntopng-* 0
simone@simone-VirtualBox-1:~/nDPI$
```

And here are the fields properly recognized as IP addresses

![image](https://user-images.githubusercontent.com/3397663/34615421-1cbb8d8e-f235-11e7-8db3-0d3c977f2cbd.png)

![image](https://user-images.githubusercontent.com/3397663/34615434-3476dfaa-f235-11e7-885d-bf5fa6dd09a7.png)
