### ISSUE TITLE
WARNING: A flow has been seen from multiple exporters or from multiple IN/OUT interfaces. Check exporters configuration.

### ISSUE THREAD

**Issue by Howard-Chang** [ntop/ntopng#1623]
Hi everyone,
I send netflow to nProbe ->ntopng->logstash->elasticsearch
on ntopng command line, it show me an warning A flow has been seen from multiple exporters or from multiple IN/OUT interfaces. Check exporters configuration.
Then I found I can only search download flow in my elasticsearch(there's no update flow).

ntopng version:v.3.2.171215
nProbe version:v.8.2.171203
  

thank you in advance!

**Comment by Howard-Chang** [comment]
such like this photo:
![image](https://user-images.githubusercontent.com/19474557/34652061-4d4a74ca-f414-11e7-805a-fb2e6fe19611.png)
there's only receive flows.

**Comment by Howard-Chang** [comment]
plz close I found the problem is due to the cisco switch configuration.

**Comment by emanuele-f** [comment]
Thank you for reporting

**Comment by peteonus** [comment]
> plz close I found the problem is due to the cisco switch configuration.

can you please tell me what is the problem in the cisco config, i'm having the same issue, thanks
