### ISSUE TITLE
Local Networks not being shown on Traffic Dashboard/Top talkers after update

### ISSUE THREAD

**Issue by uwwpowersk** [ntop/ntopng#1624]
Updated one of my ntopng instances here from 3.1.(not sure the original version, believe October/November was the last server maintenance) to v.3.2.180106 and it appears, at least in sections, that the local network clients have disappeared. 

starting with the conf file.  I've got mysql being used for historical purposes, and 6 local networks defined.  No issues currently with mysql.

-G=/var/run/ntopng.pid

#Below inserted to store FLOW data via mySQL
#FORMAT -F "mysql;{host|socket};{dbname};{table name};{user};{pw}"

-F "mysql;*blanked*;*blanked*;*blanked*;*blanked;*blanked*"

#Below Inserted to define which networks are "Local" vs "Internet"

-m "192.168.2.0/24,192.168.4.0/23,192.168.6.0/23,192.168.8.0/23,192.168.10.0/23,192.168.12.0/23"

The dashboard seems to show the 192.168.2.0/24 traffic with no issue, the ntop network interface is on 192.168.2.0/24, but the other /23 networks are not shown.

Under hosts/networks, only 192.168.2.0 and Remote Networks are shown.

![ntop networks](https://user-images.githubusercontent.com/17990333/34801029-07088db6-f62c-11e7-9a86-6327002ae242.JPG)

Under VLANS, I do see the corresponding VLANs for the networks above. (0,1,10,20,30,40,50).  I do see traffic from those VLANS under flows.

![ntop vlan](https://user-images.githubusercontent.com/17990333/34801034-0d1c3a86-f62c-11e7-9d00-00e92fee8616.JPG)

![ntop vlan 10](https://user-images.githubusercontent.com/17990333/34801038-12d42f60-f62c-11e7-81c4-3cdbe4541030.JPG)

Thoughts?  There isn't much more defined in Preferences, as its a fairly simple setup.  Device is connected to the network via a switch, with the switch mirroring all uplink traffic to the ntopng host.

Also, maybe few hundred hosts tops at current, so not related to #1594, #1599 I don't think.

**Comment by junelsolis** [comment]
I too am having the same issue after updating to the last two stable updates. Currently running enterprise v.3.2.180110. I am running ntopng in bridge mode.

**Comment by uwwpowersk** [comment]
I have a 2nd instance  (professional) that is on the beta track, and v.3.3.180108 appears to be doing the same thing.  

That specific instance is almost identical in setup to the above.  (VLANs not showing up as local networks, defined in the config to be local, shows the flows, but nothing under network or on the Dashboard.)  Not bridging there either, running it mirrored off a switch, just categorizing traffic.

**Comment by emanuele-f** [comment]
Fixed with commit a5337ea7dff39c759b1d90b7b500e42406f7e06c . A new package will be available in one hour, thank you for reporting.

**Comment by uwwpowersk** [comment]
Confirming that 3.2.180113 and 3.3.180116 appear to have fixed the issue.

**Comment by emanuele-f** [comment]
Thank you
