### ISSUE TITLE
ntopng Enterprise/Embedded Edition  & Traffic Policies/Filtering

### ISSUE THREAD

**Issue by Saleh2014** [ntop/ntopng#1628]
Hello Ntop team,

We are in the stage to testing ntopng Enterprise/Embedded Edition v.3.3.171214 in Raspberry Pi 3 as an access point in router mode not bridge mode but we don't see the Traffic Filtering in the web interface.
Please advise us.

Thanks & Best Regards,
Saleh

**Comment by emanuele-f** [comment]
![screenshot](https://user-images.githubusercontent.com/5488003/34939094-e3a8cf76-f9ea-11e7-9054-0c1ecc52e74c.png)

What's the contents of your ntopng.conf ?

Hi, you have to select the bridge interface from the `Interfaces` menù, then the `Traffic Policy` button should appear.

**Comment by Saleh2014** [comment]
The Raspberry Pi 3  is configured as wifi router not in bridge mode. Form the Interfaces menu we have lo,dummy0,wlan0 and eth0. Regarding the contents of our ntopng.conf, we don't have change any thing it's the default and all lines is begin with #

**Comment by emanuele-f** [comment]
You need to configure ntopng for inline mode, either from /etc/ntopng/ntopng.conf or via command line arguments. Please refer to the "1+1 mode " in https://github.com/ntop/ntopng/blob/dev/doc/README.inline, change "eth1" with "wlan0". You will need to create a tap interface and add "-i bridge:tap0,wlan0" to your ntopng options

**Comment by Saleh2014** [comment]
Thank you Emanuele. Everything is okay. I try to add new pool to Manage pools but the add button + is not active. I mean when I click the add button + not working. Of Course I have run at beginning the Bridge Wizard and have currently three pools Children, Guests and Main.

**Comment by Saleh2014** [comment]
Any update !!!

Thanks.

**Comment by emanuele-f** [comment]
@Saleh, what's the output of `ntopng --version`? Do you see a message at the bottom of the pool creation page about maximum number of pools?

**Comment by Saleh2014** [comment]
ntopng --version
v.3.3.171214    [Enterprise/Professional/Embedded build]
GIT rev:        dev:aeeb0fa26197ddd646d0a9f2befb183f1eb8ada9:20171214
Pro rev:        r1302
Built on:       Raspbian GNU/Linux 9.1 (stretch)
System Id:      FDD2EEF2499602D2
Platform:       armv7l
Edition:        Enterprise Embedded
License Type:   Demo
Validity:       Until Sun Feb 11 23:40:35 2018
License:        25624AF48606266E9317FA664DCDE50E1518385235AC4E4A38

Yes. I see the bottom of the pool creation but not active. Currently we have three pools.

Thanks ...

**Comment by Saleh2014** [comment]
Please see the attached file.
![capture](https://user-images.githubusercontent.com/35451579/35037079-0d385f7e-fb7f-11e7-9559-25e6201cb223.PNG)

**Comment by emanuele-f** [comment]
You have a demo version, this is why you can only create up to 3 different host pools. With the complete enterprise version you can create up to 128 host pools

**Comment by Saleh2014** [comment]
Okay.

Thank you.
