### ISSUE TITLE
 The ipv6 network does not appear in ntopng

### ISSUE THREAD

**Issue by resturiani** [ntop/ntopng#1629]
hello everyone,
I want to monitor ipv4 and ipv6 all at once with ntopng. And I've added the local network to the ntopng.conf configuration file, as shown below:
![34906059-ad09fdd6-f897-11e7-8bf6-00375a3b9554](https://user-images.githubusercontent.com/22189485/34969760-fe642e42-faa2-11e7-8181-dfaf42d55af1.png)

when I access the web with my host 192.168.10.253:3001, the network detected only ipv4 and ipv6 none of them detected. as shown below:
![34906060-b08dcd02-f897-11e7-82f8-4117e8f32066](https://user-images.githubusercontent.com/22189485/34969761-022ad940-faa3-11e7-9f57-bcf0a2a6c9ca.png)

and in Mikrotik I also have added traffic flow to ipv6 it, as shown below:
![34906062-b607eb6e-f897-11e7-83ad-408091d74cfb](https://user-images.githubusercontent.com/22189485/34969770-0a71f5ca-faa3-11e7-80f7-8257fcf7c195.png)

how to handle it? is there a solution?

**Comment by emanuele-f** [comment]
Hi, please remove the space after the comma on the `--local-networks` configuration. If you go into the Hosts view of ntopng and filter by IPv6, can you actually see any IPv6 hosts belonging to the specified network?

**Comment by resturiani** [comment]
hi, thanks for the reply.
my question above, has been resolved. the results are as below:
![hasil ipv6 done](https://user-images.githubusercontent.com/22189485/35047286-0340e962-fbcc-11e7-95fc-2f79c4d68e2a.png)

but when i change mikrotik become cisco router, ipv6 its no detect again in its ntop. the results are as below:
![router1](https://user-images.githubusercontent.com/22189485/35047292-095b24c0-fbcc-11e7-81df-d8c49cd8a54e.PNG)


the difference is just IP only. the configuration remains the same.
how to handle it?

**Comment by simonemainardi** [comment]
Very likely this is not an ntopng issue as you've already verified that it works with the mikrotik.

You have to configure your Cisco NetFlow for ipv6. Make sure ipv6 flows are poperly exported by the cisco. If you want us to inspect the netflow please attach a pcap that contains both templates and records.

**Comment by resturiani** [comment]
Hi,
Do you mean enable ipv6 flow?
On my cisco router, i just configure ipv4 and ipv6. after that i configure netflow with destination ipv4 server (ntopng) and port 2055.
After that I access web ntopng, which only detect network ipv4, ipv6 not detected.
Sorry, I do not know about pcap. i have never tried it.
How to solve it?

**Comment by marsark** [comment]
Watch for you exported NetFlow version. NetFlow v5 is not able to handle IPv6 traffic. You have tu use v9 at least or IPFIX (v10).

**Comment by resturiani** [comment]
Hi @marsark ,
I'm using netflow v9 in cisco router. And still the ipv6 network does not appear in my ntopng.

**Comment by emanuele-f** [comment]
Hi @resturiani, sorry but this is not related to ntopng itself. Your ntopng configuration if ok. I'm closing the issue.
