### ISSUE TITLE
Ntopng Data Dump to mysql not reflecting as per WebUI

### ISSUE THREAD

**Issue by alberk8** [ntop/ntopng#163]
Hi,

I have enable the mysql dump and the data captured is not reflecting the data logged in the WebUI.  It seems that the mysql dump only capture the first instance the flow is detected.  I was running a web download of a big file (1.9GB) on one PC (192.168.8.210) from source (1.9.56.10)

One other question, in the mysql table the fields ip_src_addr and ip_dst_addr, it seems to be reversed, where the local IP is located in the ip_src_addr field and remote IP is in the ip_dst_addr.  In my example, the direction of traffic flow is from remote to local.    Attached below is the URL of the screen capture as well as the flows from the mysql table.  Thanks.

OS = Linux  3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
ntopng version = Community v.2.0.150911
config file
-i=sm0
-l=1
-e=
-G=/var/run/ntopng.pid
-m="192.168.0.0/16,172.16.0.0/16"
-F=mysql;localhost;ntopng;flows;root;super

SQL Statement
select idx, l7_proto, inet_ntoa(IP_SRC_ADDR) , L4_SRC_PORT, inet_ntoa(IP_DST_ADDR), L4_DST_PORT, bytes, packets, FROM_UNIXTIME(first_switched), from_unixtime(LAST_SWITCHED), uncompress(JSON) from flowsv4_2
where ip_dst_addr = 17381386 order by idx desc;

http://filebin.ca/2FFbiVSij91G
http://filebin.ca/2FFbOWa5Nhsp

**Comment by lucaderi** [comment]
I have made a simple experiment
mysql> select idx, l7_proto, inet_ntoa(IP_SRC_ADDR) , L4_SRC_PORT, inet_ntoa(IP_DST_ADDR), L4_DST_PORT, bytes, packets, FROM_UNIXTIME(first_switched), from_unixtime(LAST_SWITCHED), uncompress(JSON) from flowsv4_0 where ip_dst_addr = INET_ATON('192.168.1.255')  limit 1;
+------+----------+------------------------+-------------+------------------------+-------------+-------+---------+-------------------------------+------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| idx  | l7_proto | inet_ntoa(IP_SRC_ADDR) | L4_SRC_PORT | inet_ntoa(IP_DST_ADDR) | L4_DST_PORT | bytes | packets | FROM_UNIXTIME(first_switched) | from_unixtime(LAST_SWITCHED) | uncompress(JSON)                                                                                                                                                                       |
+------+----------+------------------------+-------------+------------------------+-------------+-------+---------+-------------------------------+------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4832 |       10 | 192.168.1.146          |         138 | 192.168.1.255          |         138 |   263 |       1 | 2015-08-17 16:52:16           | 2015-08-17 16:52:16          | { "8": "192.168.1.146", "7": 138, "12": "192.168.1.255", "11": 138, "4": 17, "57590": 10, "57591": "NetBIOS", "2": 1, "1": 263, "24": 0, "23": 0, "22": 1439823136, "21": 1439823136 } |
+------+----------+------------------------+-------------+------------------------+-------------+-------+---------+-------------------------------+------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

and data looks good to me(no data reversed). Please explain

**Comment by alberk8** [comment]
From the Data above  the "in bytes" is  263 and the "out bytes" is 0.
I would assume that 192.168.1.146 is a local host, What i am confused is the direction of the data flow. Where is the "in bytes"  flowing to ? is it to 192.168.1.146 or 192.168.1.255 ?

The other issue is the flows data dump, From what I can see it only log the first instance the data flow appears on the network.  In the previous SQLlite dump where you get a 5mins flows dump I get very good data but now with mysql I notice that the flows dump discrepency.   Also flows dump is not done at any predictable interval. 

Thanks.

**Comment by lucaderi** [comment]
I was also confused when I saw it on the NetFlow standard, but it has been defined like that so we have to live with it.
As of the other bug, please one a new issue so we can avoid mixing things

**Comment by ganeshsanap4777** [comment]
can anybody tell me how we can find out Avg Thpt in mysql dump data?

**Comment by simonemainardi** [comment]
you can obtain the avg. throughput from mysql simply by dividing the total number of bytes (or packets) by the difference between last and first switched of any flow
