### ISSUE TITLE
Could nProbe ingest netflow and send it to Elasticsearch directly?

### ISSUE THREAD

**Issue by Howard-Chang** [ntop/ntopng#1630]
Hi, this is my architecture of ntopng and elasticsearch:
![image](https://user-images.githubusercontent.com/19474557/34983323-1260b736-fae8-11e7-8a5c-b845085353e5.png)

the yellow arrow is what I want to ask: whether nProbe could ingest netflow and send it to elasticsearch via logstash directly or even needn't through the logstash?
Because I found that the original architecture would cause drop flow: (
and I doubt the bottle neck is ntopng.

**Comment by simonemainardi** [comment]
As already discussed in earlier issues it seems that the issue is with ES not ingesting flows at at the required speed.

Anyway, if you want to export flows to ES from nProbe you can use the following option (requires nProbe export plugin)

```
[Export Plugin]
  --elastic <format>                                 | Enable export to ElasticSearch
                                                     | Format: <index type>;<index name>;<es URL>;<es user>:<es pwd>
                                                     | Example: --elastic "flows;nprobe-%Y.%m.%d;http://localhost:9200/_bulk;user:pwd"
                                                     | Note: the <index name> accepts the format supported by strftime().
```
