### ISSUE TITLE
Request to improve rrd graphs for view interfaces

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#1632]
As you can see in this image:
![ntopng_01](https://user-images.githubusercontent.com/14093378/35101105-8fd8d424-fc5e-11e7-92ad-e75a53c6783f.png)
on our environment we defined 10 interfaces: 9 "real" zc interfaces and a "view" interface (the last one). The view interface is the "sum" of the others as you can see from the ntopng.conf file:
```
[...]

--interface zc:2@0
--interface zc:2@1
--interface zc:2@2 
--interface zc:2@3
--interface zc:2@4
--interface zc:2@5
--interface zc:2@6
--interface zc:2@7
--interface zc:2@8
--interface view:zc:2@0,zc:2@1,zc:2@2,zc:2@3,zc:2@4,zc:2@5,zc:2@6,zc:2@7,zc:2@8

[...]
```
With this configuration, after 4 or 5 hours of run, into the logs I can see a lot of errors related to the `5min.lua` script:
```[5min.lua:28] [rrd_5min_dump_utils.lua:308] ERROR: [view:zc:2@0,zc:2@1,zc:2@2,zc:2@3,zc:2@4,zc:2@5,zc:2@6,zc:2@7,zc:2@8 ]Cannot complete local hosts RRD dump. Disk slow or too many local hosts?```
and to the `Lua.cpp`:
```[Lua.cpp:6513] [view:zc:2@0,zc:2@1,zc:2@2,zc:2@3,zc:2@4,zc:2@5,zc:2@6,zc:2@7,zc:2@8] ERROR: Cannot complete top talkers generation in 1 minute. Is there a huge number of hosts in the system?```
All these errors are related **only** to the view interface.

In the last days I tried to understand what ntopng is doing on my server regarding the rrd files and I discovered that all the local hosts statistics are calculated and written on the disk 2 times because the view interface is considered as a "real" interface. In instance all the statistics for the IP 192.168.1.1 are calculated and updated into the rrd files of the interface zc:2@X and also into the rrd files of the view interface. Due the high number of hosts in the view interface, the 2 scripts above are not able to update all the rrd files making the view interface graphs useless and inconsistent. The graphs of the single "real" zc interfaces instead are perfect!

This behavior, with big view interfaces composed of too many local hosts, could be a bottleneck for the software as you can see in the error messages above.

What do you think to change this behavior, for the view interface only, by using the data already calculated for the single "real" interfaces? If you are not agree with this idea, what do you think to modify the configuration of the single interface to make it more configurable than now?

In fact, as you can see into the configuration window of a real single interface
![ntopng_02](https://user-images.githubusercontent.com/14093378/35105838-f2b16238-fc6c-11e7-9335-a57ab270454d.png)
now we have only the possibility to toggle all the timeseries with the "Create Interface Timeseries" option. In my opinion for a real interface we should have the possibility to toggle independently each available timeseries: the Interface Timeseries, the Local Host Timeseries, the Devices Timeseries, the Other Timeseries and the Top Talkers.
For the view interface instead we should have the possibility to choose if calculate the statistics as a real interface (in a independently way) or as a sum of the statistics of the single interfaces that compose it.

I think that this change could be useful to have an usable view interface also when there are a big number of hosts.
What do you think?

Thanks...

**Comment by lucaderi** [comment]
@emanuele-f Any update after the latest changes to timeseries?

**Comment by emanuele-f** [comment]
To summarize, the two proposed options are:
1. Avoid writing timeseries data for view interfaces and instead calculate them dynamically by aggregating the single interfaces timeseries
2. Extend the interface timeseries settings by adding more control on which timeseries to write on a per-interface basis

Solution 2 would add too much complexity both on the gui and in the code, and will not really solve the conceptual problem. Solution 1, while conceptually more appropriate, would add way more complexity to the new timeseries drivers, which is something I would avoid.

Since InfluxDB support is now integrated into the newly released stable version of ntopng, I think this addresses the initial speed limitation caused by RRD and solves the problem the same way as solution 1 would. So my suggestion is to migrate to InfluxDB as it will probably solve this issue.
