### ISSUE TITLE
Improve traffic dashboard with flows overview graph

### ISSUE THREAD

**Issue by marsark** [ntop/ntopng#1633]
In our old flow-analysis tool, there was a simple bar graph showing amount of flows in 5 minutes periods over selected time range (default one day). This view is very handy. Now we are moving from old solution to ntopng and I missing such a graph.
![cose_dash](https://user-images.githubusercontent.com/35576246/35121117-a7e6edee-fc9a-11e7-80d6-03b7c6feff3f.png)

**Comment by emanuele-f** [comment]
Hi, ntopng has a graph which shows the number of active flows over time, you can access this from the interface charts page

**Comment by emanuele-f** [comment]
@marsark have you review the feature I suggested? Do you think it may be appropriate for you problem?

**Comment by marsark** [comment]
I got our Pro licence and now testing features not available in community edition. I can find similar graph in: Interfaces -> tcp://127.0.0.1:5556 -> Graph Icon -> select 1d period -> select Active Flow from Timeseries drop-menu; this path is very clumsy for daily usage.

Data in this graph looks different in comparison with our retired flow solution. I will dig in it and try to find out why.

**Comment by simonemainardi** [comment]
As highlighted, the chart with active flows is available from the interface page. Any custom period can be selected by dragging the mouse or selecting one of the presets.

![image](https://user-images.githubusercontent.com/3397663/46943948-22e33e80-d071-11e8-877d-111c8d72e922.png)
