### ISSUE TITLE
Implement sFlow virtual interfaces

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1635]
When a single nprobe collects flows coming from multiple sFlow devices, it should be possible to create virtual interfaces, one per sFlow device, so that flows/hosts are not mixed up.

**Comment by simonemainardi** [comment]
Feature implemented and supported. It suffices to enable the "Probe IP" dynamic interfaces creation

![image](https://user-images.githubusercontent.com/3397663/37088745-ade8e6dc-21fe-11e8-8ccf-8fad5f677b31.png)
