### ISSUE TITLE
nbox problem after upgrading to 2.6 

### ISSUE THREAD

**Issue by CampbellBruce** [ntop/ntopng#1636]
After upgrading nbox in Ubuntu 14.04.5 LTS from 2.3 to 2.6 the web interface of nbox wont run.
Apache2 is running.The message in the end of installation after installing all the libs is the following:

Setting up nbox (2.6-915) ...
modprobe: ERROR: ../libkmod/libkmod.c:507 kmod_lookup_alias_from_builtin_file() could not open builtin file '/lib/modules/4.4.19-1-pve/modules.builtin.bin'
modprobe: FATAL: Module 8021q not found.
dpkg: error processing package nbox (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for libc-bin (2.19-0ubuntu6.14) ...
Errors were encountered while processing:
 nbox
E: Sub-process /usr/bin/dpkg returned an error code (1)

Steps taken:

apt-get remove nbox
apt-get autoremove
apt-get clean all
apt-get update
apt-get upgrade
apt-get install nbox

dpkg -l | grep ntop
ii  apt-ntop-stable                  2.6-915                                  all          ntop stable apt package repository
iF  nbox                             2.6-915                                  all          Web management interface for ntop apps.
ii  ntopng                           3.2.180121-4017                          amd64        Web-based traffic monitoring.
ii  ntopng-data                      3.2.180121                               all          Data files (geoip) for ntopng.
ii  pfring                           7.0.0-1709                               amd64        PF_RING (http://www.ntop.org/pf_ring/) [7.0.0-stable:8cd503d0168ba8dc5834a1511c0ed3f34e7e282a (Thu Jan 18 23:51:44 2018 +0100)]

ntopng is working fine.
Any ideas?

**Comment by cardigliano** [comment]
It seems that the kernel you are using does not provide 8021q, however it is not mandatory, I pushed a fix to be able to complete the installation. Please update.

**Comment by CampbellBruce** [comment]
After the update new version 2.6-916 works flawlessly and in addition the installation of the rest of packages from inside nbox interface was perfect.
Thank you!
