### ISSUE TITLE
Ntop 5 customized protocol list problems

### ISSUE THREAD

**Issue by alecardia** [ntop/ntopng#1638]
Using ntop v.5.0 Fedora RPM (64 bit) on CentOS 6.9, 2.6.32-642.el6.x86_64 kernel
- - - -
Case1
Start cmd : /usr/sbin/ntop -d -L -n --skip-version-check -u ntop -P /var/lib/ntop
sortDataIP.html Protocols shown : Unknown, HTTP, MDNS, NTP, SSDP, QQ, SSL, DHCPv6, ... SNMP, NFS/AFS.
/var/log/messages: no errors
- - - -
Case2
Start cmd : /usr/sbin/ntop -d -L -n --skip-version-check -u ntop -P /var/lib/ntop --protocols="HTTP=80|443|3128|8080,FTP=20|21"
sortDataIP.html Protocols shown : Unknown, DNS, SSDP, QQ or Unknown, DNS, SSDP, SNMP, LDAP  or some other random list of few protocols
/var/log/messages: ntop[pid]:   **WARNING** Internal error: protocol overflow [150/150] (many many rows)
- - - -
Case3
Start cmd : /usr/sbin/ntop -d -L -n --skip-version-check -u ntop -P /var/lib/ntop -p /etc/ntop/protocol.list
File /etc/ntop/protocol.list ( -rwxr-xr-x 1 root root 22 Jan 19 13:37 protocol.list )
HTTP=80|443|3128|8080
FTP=20|21
sortDataIP.html Protocols shown : Unknown, DNS, NETBIOS, SSDP, SNMP, QQ or Unknown, DNS, SSDP, SNMP, DCE RPC or some other random list of few protocols
/var/log/messages: ntop[pid]:   **WARNING** Internal error: protocol overflow [150/150] (many many rows)
- - - -
With older versions of Ntop never had problems in customizing protocol list.
Is there something missing in my Linux box Setup?
I know there something wrong in me ... I don't know what.
Best regards,
Ales.
- - - -
Attached (2)

- textinfo.html output (case3 run)
[ntop_textinfo.txt](https://github.com/ntop/ntopng/files/1659101/ntop_textinfo.txt)
- /etc/services
[services.txt](https://github.com/ntop/ntopng/files/1659098/services.txt)

**Comment by emanuele-f** [comment]
Hi, you are using `ntop` and not `ntopng`. Ntop is not supported anymore, please install ntopng.

**Comment by alecardia** [comment]
I've already tried Emanuele, and I've met many problems, that's the reason why I still continue using Ntop 5 on my sniffers.

# yum install redis hiredis
==> No package hiredis available
OK, solved using rpm bin

# yum install pfring n2disk nprobe ntopng ntopng-data cento nbox
(...)
Error: Package: nprobe-8.3.180124-6048.x86_64 (ntop)
           Requires: zeromq >= 4.0.0
           Installed: zeromq-2.2.0-4.el6.x86_64 (@epel)
               zeromq = 2.2.0-4.el6
Error: Package: cento-1.3.180124-299.x86_64 (ntop)
           Requires: zeromq >= 4.0.0
           Installed: zeromq-2.2.0-4.el6.x86_64 (@epel)
               zeromq = 2.2.0-4.el6
Error: Package: ntopng-3.3.180124-3847.x86_64 (ntop)
           Requires: zeromq >= 4.0.0
           Installed: zeromq-2.2.0-4.el6.x86_64 (@epel)
               zeromq = 2.2.0-4.el6

Temporarily Surrended ...
Thank all the same.
A.

**Comment by emanuele-f** [comment]
Please follow the istructions at http://packages.ntop.org/centos/

**Comment by alecardia** [comment]
Tutorial is very OK, and perhaps It could be just a little bit better adding:

# touch /etc/ntopng/ntopng.start
to avoid "Missing /etc/ntopng/ntopng.start. Quitting ..." message after the first run.

Thanks a lot Emanuele. Have a good time.
Ales.

**Comment by emanuele-f** [comment]
Hi, that url only contains installation instructions but I agree some basic configuration instruction would be useful. Nevertheless, the ntopng.start is only needed in Centos 6.9 and some other pre-systemd OS.
