### ISSUE TITLE
Show only the Blacklisted Hosts...

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#1639]
![blacklisted_hosts](https://user-images.githubusercontent.com/14093378/35335151-f3b7e902-0114-11e8-89c7-ca7b58c6e0e9.png)
Could you add a "Blacklisted Hosts Only" filter in the drop down menu in the right?
Thanks...

**Comment by emanuele-f** [comment]
Implemented. Thank you for the suggestion.
