### ISSUE TITLE
Disk Used by folder RRD

### ISSUE THREAD

**Issue by diegoarioza** [ntop/ntopng#1640]
Hello, one of our clients has a ntopng license, but the / opt / ntop folder is using more than 200gb, a lot of the space used is from the rrd folder, I wonder if we can remove these folders to clean, thanks

**Comment by emanuele-f** [comment]
Hi, the rrd folder contains RRD files which holds all the traffic stats for hosts, host pools, devices and so on. You can delete them but you will lose all these data.

Please check out the Timeseries section of the ntopng preferences to only enable the dump of the stats you are interested in. Also make sure your local networks (`-m` ntopng parameter) include only the network CIDRs you actually wish to monitor.
