### ISSUE TITLE
Feature Request: Disaggregate on %EXPORTER_IPV4_ADDRESS

### ISSUE THREAD

**Issue by joakimlemb** [ntop/ntopng#1641]
This would be really useful in our scenario where we want to separate flows between multiple exporters on one nProbe ip/port.

**Comment by emanuele-f** [comment]
Hi, this is already possible, please check out the ntopng advanced preferences `Dynamic Network Interfaces` disaggregation by "Probe IP".

![screenshot](https://user-images.githubusercontent.com/5488003/35392058-df5d51e6-01e0-11e8-887a-4444a740b510.png)

**Comment by joakimlemb** [comment]
Well you are right, I got it to work using a custom template with %EXPORTER_IPV4_ADDRESS, but nprobe gives the indication that a custom template should not be needed:
`[nprobe.c:6850] WARNING: Adding %EXPORTER_IPV4_ADDRESS to the template as nProbe is working as collector`

So I'm guessing it's either a bug or that message should be removed?

**Comment by simonemainardi** [comment]
nProbe is just telling you it is adding `%EXPORTER_IPV4_ADDRESS` automatically so you don't have to change the template.

So apply the Probe IP setting  and restart ntopng. Then you should start seeing the creation of dynamic interface.
