### ISSUE TITLE
Redis Error Unknown Command 'DUMP' no historical data

### ISSUE THREAD

**Issue by joelphilippage** [ntop/ntopng#1642]
I am running ntopng Professional Edition v.3.2.171203 on Windows Server 2016. Since I upgraded to this version, it seems that ntopng can no longer store historical data in my sql database. When launching the program I get this log:
`25/Jan/2018 10:58:50 [Ntop.cpp:1612] Registered interface {C52860A3-18FD-42D8-A159-EE87DDD35288} [id: 1]
25/Jan/2018 10:58:51 [HTTPserver.cpp:839] HTTPS Disabled: missing SSL certificate C:\Program Files\ntopng\httpdocs/ssl/ntopng-cert.pem
25/Jan/2018 10:58:51 [HTTPserver.cpp:841] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
25/Jan/2018 10:58:51 [HTTPserver.cpp:912] Web server dirs [C:\Program Files\ntopng\httpdocs][C:\Program Files\ntopng\scripts]
25/Jan/2018 10:58:51 [HTTPserver.cpp:915] HTTP server listening on port(s) 3000
25/Jan/2018 10:58:51 [main.cpp:383] Working directory: C:\Users\Administrator\Documents\ntopng
25/Jan/2018 10:58:51 [main.cpp:385] Scripts/HTML pages directory: C:\Program Files\ntopng
25/Jan/2018 10:58:51 [Ntop.cpp:385] Welcome to ntopng x64 v.3.2.171203 - (C) 1998-17 ntop.org
25/Jan/2018 10:58:51 [Ntop.cpp:395] Built on Windows
25/Jan/2018 10:58:51 [NtopPro.cpp:464] [LICENSE] System Id:     2762850228-645b618d
25/Jan/2018 10:58:51 [NtopPro.cpp:465] [LICENSE] Edition:       Professional
25/Jan/2018 10:58:51 [NtopPro.cpp:466] [LICENSE] License Type:  Permanent License
25/Jan/2018 10:58:51 [NtopPro.cpp:469] [LICENSE] License:       C5B7B31CA3FB5BECE09A954C15E72DFA151941989191C8ED0A
25/Jan/2018 10:58:51 [NtopPro.cpp:479] [LICENSE] Maintenance:   Until Fri Feb 23 14:04:51 2018 [29 days left]
25/Jan/2018 10:58:51 [Ntop.cpp:607] Adding 10.0.0.0/8 as IPv4 local network for
25/Jan/2018 10:58:51 [Ntop.cpp:613] Adding 10.0.53.18/32 as IPv4 interface address for {A99BB891-6A0E-406D-8C4E-40520E6DF021}
25/Jan/2018 10:58:51 [PeriodicActivities.cpp:59] Started periodic activities loop...
25/Jan/2018 10:58:51 [PeriodicActivities.cpp:100] Each periodic activity script will use 2 threads
25/Jan/2018 10:58:51 [NetworkInterface.cpp:2326] Started packet polling on interface {A99BB891-6A0E-406D-8C4E-40520E6DF021} [id: 0]...
25/Jan/2018 10:58:51 [NetworkInterface.cpp:2326] Started packet polling on interface {C52860A3-18FD-42D8-A159-EE87DDD35288} [id: 1]...
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:19 [Redis.cpp:1529] ERROR: ERR unknown command 'DUMP'
25/Jan/2018 10:59:20 [Lua.cpp:3663] ERROR: Error 'fetching cdp from rra' while calling rrd_fetch_r(C:\Users\Administrator\Documents\ntopng\1\rrd\bytes.rrd, AVERAGE): is the RRD corrupted perhaps?`

I have tried uninstalling redis, wincap, and ntopng and deleteing everything in the ntopng folder in documents and re-installing everything but I keep getting the same error logs.

**Comment by simonemainardi** [comment]
Can you please try and update Redis to a more recent version? DUMP command is only supported starting at redis version 2.6.

**Comment by joelphilippage** [comment]
I had already tried version 3.2.100 for windows from here: https://github.com/MicrosoftArchive/redis. But shouldn't the version included in ntopng be compatible?
[edit] Okay. I deleted the redis folder from program files and ran the new 3.2.100 installer and it seems to have fixed the problem. What version is included in the ntopng installer? I am still gettting the error
`ERROR: Error 'fetching cdp from rra' while calling rrd_fetch_r(C:\Users\Administrator\Documents\ntopng\1\rrd\bytes.rrd, AVERAGE): is the RRD corrupted perhaps?`

**Comment by emanuele-f** [comment]
Hi, the latest ntopng installer will install the redis server version 2.4.6 . I suggest you to remove redis ntopng and libpcap as long as any ntopng data and start with a clean setup.

Ps. the latest ntopng installer 3.2.171215 does not produce the redis dump error on my test machine.

**Comment by joelphilippage** [comment]
Okay. The clean install did fix the redis error, but I still have no historical data and still get the error:
`ERROR: Error 'fetching cdp from rra' while calling rrd_fetch_r(C:\Users\Administrator\Documents\ntopng\1\rrd\bytes.rrd, AVERAGE): is the RRD corrupted perhaps?`
Should I start another bug for this?

**Comment by emanuele-f** [comment]
Please remove the C:\Users\Administrator\Documents\ntopng directory completely. You need to do this after stopping ntopng. So the steps are:

1) stop ntopng service
2) remove that directory
3) start the ntopng service again

**Comment by joelphilippage** [comment]
Okay. I had done that already. I tried that again yesterday. I started the service at 08/Feb/2018 07:65:14. I just got the error again at 09/Feb/2018 13:08:08 I think it happened as soon as I logged in to ntopng today although I did yesterday.

Also there is still no historical data available on the interface.
![image](https://user-images.githubusercontent.com/13322475/36047975-ec37b904-0d9a-11e8-98ec-eab46293f565.png)

**Comment by emanuele-f** [comment]
Please provide the ntopng log

**Comment by joelphilippage** [comment]
I'm not able to get it to start anymore. Here are my latest logs:
`C:\Users\Administrator>ntopng /c -F "mysql;localhost;ntopng;flows;root;password"
Starting ntopng
Running ntopng.
01/Mar/2018 11:41:12 [Ntop.cpp:1485] Setting local networks to 127.0.0.0/8
01/Mar/2018 11:41:12 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
01/Mar/2018 11:41:12 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
01/Mar/2018 11:41:12 [NtopPro.cpp:221] [LICENSE] Reading license from Redis
01/Mar/2018 11:41:12 [NtopPro.cpp:300] WARNING: [LICENSE] Invalid or missing license
01/Mar/2018 11:41:12 [NtopPro.cpp:317] WARNING: [LICENSE] ntopng will now run in enterprise edition for 10 minutes
01/Mar/2018 11:41:12 [NtopPro.cpp:319] WARNING: [LICENSE] before returning to community mode
01/Mar/2018 11:41:12 [NtopPro.cpp:321] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
01/Mar/2018 11:41:12 [NtopPro.cpp:323] WARNING: [LICENSE] or run ntopng in community mode starting
01/Mar/2018 11:41:12 [NtopPro.cpp:324] WARNING: [LICENSE] ntopng --community
01/Mar/2018 11:41:13 [PcapInterface.cpp:88] Reading packets from interface {A99BB891-6A0E-406D-8C4E-40520E6DF021}...
01/Mar/2018 11:41:13 [PcapInterface.cpp:93] WARNING: Unable to set packet capture direction`

I've tried uninstalling winpcap and redis and ntopng and deleting the ntopng files in mydocuments and all the directories in program files. I then install the latest version of redis and re-install ntopng. It still crashes at this point with `An unhandled win32 exception occured in ntopng.exe [1576]`

**Comment by emanuele-f** [comment]
Can you check out if the ntopng memory usage increases a lot right before experiencing the crash? If you remove the `-F` flag, can you run it properly?

Please also look at this, may be related.

https://social.msdn.microsoft.com/Forums/es-ES/24b356ad-59ef-446f-aa8b-df6b55fa78bb/an-unhandled-win32-exception-occurred?forum=Vsexpressinstall

**Comment by joelphilippage** [comment]
It does work without the -f flag. Memory and CPU stay about the same during the crash.

I tried this suggested solution, but have the same issue:
a.. Right click My PC / Properties.
  b.. Click Advanced Tab
  c.. Under Performance, click Settings
  d.. Click Data Excecution Prevention tab
  e.. Select Turn on DEP for essential Windows programs and services only
  f.. Restart Windows

I've also tried deleting the database and starting it again but am getting the same crash.

**Comment by emanuele-f** [comment]
Do you have the possibilitity to run ntopng through windbg or other debugger to get a stack trace of the crash?

**Comment by joelphilippage** [comment]
Sure. Here's what I got:
`Microsoft (R) Windows Debugger Version 10.0.16299.91 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

*** wait with pending attach
Symbol search path is: srv*
Executable search path is: 
ModLoad: 00007ff7`cbd50000 00007ff7`cc0b3000   C:\Program Files\ntopng\ntopng.exe
ModLoad: 00007ffd`f6bc0000 00007ffd`f6d91000   C:\Windows\SYSTEM32\ntdll.dll
ModLoad: 00007ffd`f6a70000 00007ffd`f6b1b000   C:\Windows\System32\KERNEL32.DLL
ModLoad: 00007ffd`f3380000 00007ffd`f359d000   C:\Windows\System32\KERNELBASE.dll
ModLoad: 00007ffd`f6070000 00007ffd`f6112000   C:\Windows\System32\ADVAPI32.dll
ModLoad: 00007ffd`f41e0000 00007ffd`f427e000   C:\Windows\System32\msvcrt.dll
ModLoad: 00007ffd`f42f0000 00007ffd`f4349000   C:\Windows\System32\sechost.dll
ModLoad: 00007ffd`f5860000 00007ffd`f5981000   C:\Windows\System32\RPCRT4.dll
ModLoad: 00007ffd`f4350000 00007ffd`f5858000   C:\Windows\System32\SHELL32.dll
ModLoad: 00007ffd`f3ea0000 00007ffd`f3ee2000   C:\Windows\System32\cfgmgr32.dll
ModLoad: 00007ffd`f35a0000 00007ffd`f3c7a000   C:\Windows\System32\windows.storage.dll
ModLoad: 00007ffd`f6350000 00007ffd`f6617000   C:\Windows\System32\combase.dll
ModLoad: 00007ffd`f3c80000 00007ffd`f3d75000   C:\Windows\System32\ucrtbase.dll
ModLoad: 00007ffd`f3e30000 00007ffd`f3e9a000   C:\Windows\System32\bcryptPrimitives.dll
ModLoad: 00007ffd`f30d0000 00007ffd`f311c000   C:\Windows\System32\powrprof.dll
ModLoad: 00007ffd`f62f0000 00007ffd`f6342000   C:\Windows\System32\shlwapi.dll
ModLoad: 00007ffd`f5f70000 00007ffd`f5fa4000   C:\Windows\System32\GDI32.dll
ModLoad: 00007ffd`f3fa0000 00007ffd`f4122000   C:\Windows\System32\gdi32full.dll
ModLoad: 00007ffd`f5df0000 00007ffd`f5f55000   C:\Windows\System32\USER32.dll
ModLoad: 00007ffd`f4130000 00007ffd`f414e000   C:\Windows\System32\win32u.dll
ModLoad: 00007ffd`f30c0000 00007ffd`f30cf000   C:\Windows\System32\kernel.appcore.dll
ModLoad: 00007ffd`f3ef0000 00007ffd`f3f99000   C:\Windows\System32\shcore.dll
ModLoad: 00007ffd`f3120000 00007ffd`f3134000   C:\Windows\System32\profapi.dll
ModLoad: 00007ffd`f4280000 00007ffd`f42ea000   C:\Windows\System32\WS2_32.dll
ModLoad: 00007ffd`e9e30000 00007ffd`e9e39000   C:\Windows\SYSTEM32\WSOCK32.dll
ModLoad: 00007ffd`f2720000 00007ffd`f2758000   C:\Windows\SYSTEM32\IPHLPAPI.DLL
ModLoad: 00000001`80000000 00000001`80065000   C:\Windows\SYSTEM32\wpcap.dll
ModLoad: 00007ffd`e8700000 00007ffd`e8776000   C:\Program Files\ntopng\lua51.dll
ModLoad: 00007ffd`e8610000 00007ffd`e86ff000   C:\Windows\SYSTEM32\MSVCR120.dll
ModLoad: 00007ffd`e9e00000 00007ffd`e9e25000   C:\Windows\SYSTEM32\packet.dll
ModLoad: 00007ffd`e95a0000 00007ffd`e95aa000   C:\Windows\SYSTEM32\VERSION.dll
ModLoad: 00007ffd`f15f0000 00007ffd`f1613000   C:\Windows\SYSTEM32\WINMM.dll
ModLoad: 00007ffd`f1510000 00007ffd`f153b000   C:\Windows\SYSTEM32\WINMMBASE.dll
ModLoad: 00007ffd`f5dc0000 00007ffd`f5dee000   C:\Windows\System32\IMM32.DLL
ModLoad: 00007ffd`f6280000 00007ffd`f6288000   C:\Windows\System32\NSI.dll
ModLoad: 00007ffd`ef5e0000 00007ffd`ef5fa000   C:\Windows\SYSTEM32\dhcpcsvc.DLL
ModLoad: 00007ffd`f2990000 00007ffd`f29ec000   C:\Windows\system32\mswsock.dll
(1140.13c8): Security check failure or stack buffer overrun - code c0000409 (!!! second chance !!!)
*** WARNING: Unable to verify checksum for C:\Program Files\ntopng\ntopng.exe
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\Program Files\ntopng\ntopng.exe - 
ntopng!zmq_z85_encode+0xc590:
00007ff7`cbfbbcd0 cd29            int     29h
`

**Comment by emanuele-f** [comment]
Thank you, we'll have to further investigate the issue

**Comment by lucaderi** [comment]
@joelphilippage Hi all, we believe we have fixes all issues with the 3.3.180416 version. Can you please confirm?

**Comment by joelphilippage** [comment]
Can confirm it is working great with no bugs in the latest version. I had a Windows bug when trying to start the Redis service, but re-installing Redis manually fixed this and I imagine it was a Windows thing.

Thanks for the hard work!

**Comment by simonemainardi** [comment]
thanks for reporting
