### ISSUE TITLE
build .deb packages from sources

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#1644]
I am trying to build and customize the .deb packages from sources after cloning the source code.
it would be really helpful if you could indicate me the commands you use to follow to achieve this.

[I am trying to build for ubuntu 16.04 but it would be perfect to get packages for other distributions too]

Thanks in advance.

**Comment by emanuele-f** [comment]
Hi, please execute the following commands:

```
cd packages/ubuntu/
./configure

# removes the package signing stuff
sed -i "s/dpkg-sig .*/#dpkg-sig/g" Makefile

# builds the core and data packages
make ntopng
make ntopng-data
```

**Comment by ghost** [comment]
Great and fast reply. Thanks Emanuele!

**Comment by emanuele-f** [comment]
You are welcome!
