### ISSUE TITLE
ntopng how to enable host traffic policy?

### ISSUE THREAD

**Issue by 13666752** [ntop/ntopng#1645]
Good afternoon! I do not see her "Ntopng" host traffic policy CA to include this option. Ntopng installed on linux debian (marscruiser network). Please help.

**Comment by emanuele-f** [comment]
Hi, what are the ntopng options you are using? How many network interface do you have? Please check out https://github.com/ntop/ntopng/blob/dev/doc/README.inline

**Comment by 13666752** [comment]
Interfaces : eth0 - (WLAN) eth1 - (LAN)
Screenshots of the settings:
https://cloud.mail.ru/public/F4Ab/T5oqm6grv

**Comment by 13666752** [comment]
I want to see here is "host traffic policy "
https://cloud.mail.ru/public/Lxur/hSicj2QA4

**Comment by 13666752** [comment]
((((Internet  <--eth0 -eth1 -> and ntopng  one PC)))) ----> Local network

**Comment by emanuele-f** [comment]
So you have two network interfaces, eth0 connected to the internet and eth1 to you LAN. Please follow the instructions for 1+1 mode in the link above (take care to swap the eth0 and eth1 as the tutorial assumes that eth0 is connected to internet). You will need to create a TAP interface and then bridge the tap with your lan interface with ntopng: `ntopng -i bridge:tap0,eth0`.

Important: you will need the ntopng pro version to run the bridge.

**Comment by 13666752** [comment]
Thanks.

**Comment by 13666752** [comment]
The Pro version paid? License how much?

**Comment by emanuele-f** [comment]
Please check out our shop https://shop.ntop.org/ . If you want a demo or if you have any license related questions please contact us privately with this form: https://www.ntop.org/support/need-help-2/contact-us/

**Comment by emanuele-f** [comment]
I'm closing the issue for now.
