### ISSUE TITLE
Segmentation Violation ntopng x86_64 v.3.2.180129

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#1646]
When using the -H flag ntopng core dumps.
/usr/bin/ntopng  -U ntop -ieth2 -n 1 -H -d/var/lib/ntop -w 3000 -n 1 -m 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
Segmentation fault (core dumped)

gdb) r -U ntop -ieth2  -H -n 1 -d/var/lib/ntop -w 3000 -n 1 -m 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
Starting program: /usr/bin/ntopng -U ntop -ieth2  -H -n 1 -d/var/lib/ntop -w 3000 -n 1 -m 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
[Thread debugging using libthread_db enabled]

Program received signal SIGSEGV, Segmentation fault.
0x00000000004ef54f in Prefs::setOption (this=0x8f1b20, optkey=72, optarg=0x0) at src/Prefs.cpp:672
672     src/Prefs.cpp: No such file or directory.
        in src/Prefs.cpp
Missing separate debuginfos, use: debuginfo-install ntopng-3.2.180129-3699.x86_64
(gdb) bt
#0  0x00000000004ef54f in Prefs::setOption (this=0x8f1b20, optkey=72, optarg=0x0) at src/Prefs.cpp:672
#1  0x00000000004f19d1 in Prefs::loadFromCLI (this=0x8f1b20, argc=14, argv=0x7fffffffe558)
    at src/Prefs.cpp:1260
#2  0x000000000050d5e9 in main (argc=14, argv=0x7fffffffe558) at src/main.cpp:137
(gdb) quit

**Comment by emanuele-f** [comment]
Fixed in commit 0861aeff8d05222f8421133c6d1122ec61e15e49 . I've also removed the option from man page as it is no more supported. You can disable the alerts from the ntopng preferences.
Thank you for reporting!
