### ISSUE TITLE
ntopng problems with elasticsearch and logstash

### ISSUE THREAD

**Issue by oskapt** [ntop/ntopng#1647]
Hi - I'm running ntopng CE v.3.2.180118 under Docker. I'm running all of this in my house, with ntopng forwarding to an ELK stack running under Kubernetes on a Mac Mini running Ubuntu 16.04. There's not a lot of traffic, but there's some chatter. 

I first pointed it at elasticsearch, and it would almost immediately choke and start reporting errors about the flows backing up. I switched over to Logstash, and those errors went away, but now it chokes completely every few hours. The logs report a steady `02/Feb/2018 15:40:17 [Logstash.cpp:309] WARNING: [LS] Sending failed. Scheduling retry..` Other metrics going into Logstash from other shippers don't have any issues.

Moreover, if I restart the Logstash pod, ntopng _never reconnects_. I have to restart the ntopng container.

How robust is the Elasticsearch/Logstash shipping component? I used to have ntopng pointed at an Elasticsearch 4 instance running on weaker hardware than it is now, and I had no issues. It's only after updating to Elasticsearch 6 and the lastest ntopng that these problems have appeared.

Is it possible to get more information about what ntopng is mad about? "Sending failed" is vague, especially when other shippers in the house (filebeat, mostly) don't have any issues. Kibana and logstash themselves have no issues with elasticsearch. Elasticsearch reports no errors. Load and memory usage on the Kubernetes cluster are within reasonable limits. The fact that ntopng never reconnects is also suspicious.

I'm running ntopng on a Synology NAS because it's the only 2-NIC device I currently have. My edge router is bouncing a copy of all traffic over to ntopng using `TEE` within iptables, and ntopng is forwarding that to Logstash. It's possible that ntopng wants more juice than the NAS can provide, but like I said above, it worked great when I first set it up > 2 years ago.

I rely heavily on ntopng because I'm on a limited mobile broadband connection in my rural location. I use it to track what's going on in real time so that I can tune squid, privoxy, and other systems to identify and shut down noisy applications that burn bandwidth. It's frustrating to have it just die for no apparent reason, and I'd really like to resolve the issue.

Please let me know if I can provide more info to help track down the issues.

**Comment by emanuele-f** [comment]
Hi, with 53d2505edcb2750e1f7d877449470c8d567bdb95 I've made some fixes on ES code which prevented effective requests batching, please install the new 3.3 *development* version to test the new code performance. Logstash needs to be fixed too.

The new package will be available in one hour.

**Comment by lucaderi** [comment]
Fix has been applied. If not working please reopen the issue and report what is not working yet

**Comment by oskapt** [comment]
I've rebuilt the container using `3.3.180217-4094`:
```
root@nas:/etc/ntopng# dpkg -l | grep ntopng
ii  ntopng                        3.3.180217-4094                       amd64        Web-based traffic monitoring.
ii  ntopng-data                   3.3.180217                            all          Data files (geoip) for ntopng.
```

However, the interface reports that it's 2.3.0:

![ntopng-screenshot](https://user-images.githubusercontent.com/171292/36344615-eb6472f8-13fb-11e8-87c1-36262c6e0f10.png)

Other than the package name, is there another way to confirm that I'm _actually_ running the snapshot?

**Comment by emanuele-f** [comment]
Please check out `ntopng --version`

**Comment by swathikothapu** [comment]
dpkg -l | grep ntopng , command not found
