### ISSUE TITLE
Double-quote escaping in JSON.DNS_QUERY attribute when dumping flows to MySQL

### ISSUE THREAD

**Issue by charlesboyo** [ntop/ntopng#1648]
Hi.

When exporting flows to MySQL, double-quotes in the DNS queries are not escaped. This results in invalid JSON which cannot be parsed by the readers of such records.

An example of the uncompressed value is:
{ "8": "192.168.1.134", "12": "192.168.1.1", "7": 64676, "11": 53, "4": 17, "57590": 5, "57591": "DNS", "2": 1, "1": 172, "24": 1, "23": 219, "22": 1517250794, "21": 1517250794, "SRC_IP_COUNTRY": "", "SRC_IP_LOCATION": [ 0.000000, 0.000000 ], "DST_IP_COUNTRY": "", "DST_IP_LOCATION": [ 0.000000, 0.000000 ], "NTOPNG_INSTANCE_NAME": "ubuntu", "INTERFACE": "eth1", "DNS_QUERY": "arcw5z1"pvkiedsjq9t2wzal384za3bw9f1i1dmpl8.11aqe1pu3131ntw5kj69qf279i.3hmcc4l6alm9125pp1puvku5ht.avqs.mcafee.com" }

The DNS query contains a double quote and that was not escaped:

arcw5z1"pvkiedsjq9t2wzal384za3bw9f1i1dmpl8.11aqe1pu3131ntw5kj69qf279i.3hmcc4l6alm9125pp1puvku5ht.avqs.mcafee.com

**Comment by simonemainardi** [comment]
Proper escaping is already supported thanks to the use of function `json_object_new_string`. You can verify this directly from the json-c sources at https://github.com/json-c/json-c/blob/master/json_object.c#L1011 and https://github.com/json-c/json-c/blob/master/json_object.c#L993

To convince yourself you can also run a dummy example within ntopng as:
```
simone@devel:~/ntopng$ git diff
diff --git a/src/Flow.cpp b/src/Flow.cpp
index a5531ce..230f0c7 100644
--- a/src/Flow.cpp
+++ b/src/Flow.cpp
@@ -1900,10 +1900,13 @@ json_object* Flow::flow2json() {
   if(ntop->getPrefs() && ntop->getPrefs()->get_instance_name())
     json_object_object_add(my_object, "NTOPNG_INSTANCE_NAME",
                           json_object_new_string(ntop->getPrefs()->get_instance_name()));
+
   if(iface && iface->get_name())
     json_object_object_add(my_object, "INTERFACE", json_object_new_string(iface->get_name()));

-  if(isDNS() && protos.dns.last_query)
+  protos.dns.last_query = strdup("a dns query with \" double quotes \" here and other strange chars \\r\\n\\t\\r ");
+  ntop->getTrace()->traceEvent(TRACE_NORMAL, "Query is: %s", protos.dns.last_query);
+  if(protos.dns.last_query)
     json_object_object_add(my_object, "DNS_QUERY", json_object_new_string(protos.dns.last_query));

   if(isHTTP() && protos.http.last_url && protos.http.last_method) {
```

Run it and you will get proper escaping as:
```
05/Feb/2018 12:15:59 [Flow.cpp:1908] Query is: a dns query with " double quotes " here and other strange chars \r\n\t\r
05/Feb/2018 12:15:59 [NetworkInterface.cpp:672] { "IPV4_SRC_ADDR": "192.168.2.222", "IPV4_DST_ADDR": "131.114.18.19", "L4_SRC_PORT": 0, "L4_DST_PORT": 0, "PROTOCOL": 1, "L7_PROTO": 81, "L7_PROTO_NAME": "ICMP", "IN_PKTS": 1, "IN_BYTES": 414, "OUT_PKTS": 0, "OUT_BYTES": 0, "FIRST_SWITCHED": 1517829357, "LAST_SWITCHED": 1517829357, "SRC_IP_COUNTRY": "", "SRC_IP_LOCATION": [ 0.000000, 0.000000 ], "DST_IP_COUNTRY": "IT", "DST_IP_LOCATION": [ 10.383300, 43.716702 ], "INTERFACE": "eno1", "DNS_QUERY": "a dns query with \" double quotes \" here and other strange chars \\r\\n\\t\\r " }
```

Maybe you are using a very old version of json-c?

**Comment by simonemainardi** [comment]
Proper JSON escaping is implemented as demonstrated above. Please make sure to run the latest version of ntopng.

If you should still get this kind of issue, please open another issue with a pcap of the dns traffic, as well as the exact system os / package (or source build) version.
