### ISSUE TITLE
NTOPNG with Let's Encrypt SSL

### ISSUE THREAD

**Issue by xssec** [ntop/ntopng#1649]
Hi,

Is there any documentation about how to set NTOPNG webconsole into HTTPS with SSL from Let's Encrypt?

**Comment by emanuele-f** [comment]
Hi, let's encrypt it's just a way to verify a SSL certificate ownership. In order to use your `.pem` certificate with ntopng, please follow the instructions at https://github.com/ntop/ntopng/blob/dev/doc/README.SSL from step 3
