### ISSUE TITLE
Upgrade to ntopng 2.x - few things broken

### ISSUE THREAD

**Issue by michalzahor** [ntop/ntopng#165]
Hi,

I've done upgrade from NTOPNG 1.2.1 to 2.0 - compiled 2.0 stable branch + nDPI 1.7 on Debian 7 [ Wheezy ]

There are several things broken:
 - Hosts: data/stats deleted after restart ntopng ( Seen Since is after restart few seconds )
 - Preferences: I'm logged in as admin but there is no Preferences menu - only Change Password, Export Data
 - Interfaces - Historical : after selecting Begin, End Date and pressing Load Historical Data, appears "Warning Please wait while loading data..." but never changed to Done or so.
 - Protocols - there is only one item in this menu: DNS

NTOP is running as nobody:nobody:
Directory /var/lib/ntopng exists and already created directories are R/W for nobody

NTOPNG.CONF:
-q=
-A=2
-C=
-F=db
-D=all
-E=all
-d=/var/lib/ntopng
-S=all
-n=1
-m=10.10.1.0/24,10.10.5.0/24,10.10.6.0/24,10.10.9.0/24,10.10.10.0/24,10.10.11.0/24
-w=3000
-i=eth0
-e=
-G=/tmp/ntop/ntopng.pid

NTOPNG version: 

v.2.0.150912 [Community Edition]
GIT rev:   2.0-stable:b02dcb280c8574b0e8232995726aa27a11a81819:20150912

NTOPNG LOG after start:
12/Sep/2015 16:43:01 [src/Ntop.cpp:785] Setting local networks to 10.10.1.0/24,10.10.5.0/24,10.10.6.0/24,10.10.9.0/24,10.10.10.0/24,10.10.11.0/24,10.10.12.0/24,10.10.13.0/24
12/Sep/2015 16:43:01 [src/Redis.cpp:93] Successfully connected to redis 127.0.0.1:6379@0
12/Sep/2015 16:43:01 [src/Ntop.cpp:759] Parent process is exiting (this is normal)
12/Sep/2015 16:43:01 [src/PcapInterface.cpp:81] Reading packets from interface eth0...
12/Sep/2015 16:43:01 [src/Ntop.cpp:1033] Registered interface view eth0 [id: 1]
12/Sep/2015 16:43:01 [src/Ntop.cpp:1003] Registered interface eth0 [id: 0]
12/Sep/2015 16:43:01 [src/Ntop.cpp:1033] Registered interface view Historical [id: 3]
12/Sep/2015 16:43:01 [src/Ntop.cpp:1003] Registered interface Historical [id: 1]
12/Sep/2015 16:43:01 [src/Utils.cpp:292] User changed to nobody
12/Sep/2015 16:43:01 [src/main.cpp:236] PID stored in file /tmp/ntop/ntopng.pid
12/Sep/2015 16:43:01 [src/HTTPserver.cpp:492] Web server dirs [/usr/local/share/ntopng/httpdocs][/usr/local/share/ntopng/scripts]
12/Sep/2015 16:43:01 [src/HTTPserver.cpp:495] HTTP server listening on port 3000
12/Sep/2015 16:43:01 [src/HTTPserver.cpp:498] HTTPS server listening on port 3001
12/Sep/2015 16:43:01 [src/main.cpp:287] Working directory: /var/lib/ntopng
12/Sep/2015 16:43:01 [src/main.cpp:289] Scripts/HTML pages directory: /usr/local/share/ntopng
12/Sep/2015 16:43:01 [src/Ntop.cpp:271] Welcome to ntopng x86_64 v.2.0.150912 - (C) 1998-15 ntop.org
12/Sep/2015 16:43:01 [src/PeriodicActivities.cpp:53] Started periodic activities loop...
12/Sep/2015 16:43:01 [src/RuntimePrefs.cpp:32] Dumping alerts into syslog
12/Sep/2015 16:43:01 [src/NetworkInterface.cpp:1197] Setting affinity of interface eth0 to core 1
12/Sep/2015 16:43:01 [src/NetworkInterface.cpp:1201] Started packet polling on interface eth0 [id: 1]...
12/Sep/2015 16:43:01 [src/NetworkInterface.cpp:1201] Started packet polling on interface Historical [id: 3]...

**Comment by michalzahor** [comment]
Some screenshots about interface history 

Screens shows there are more then 60MB of historical data
![voila_capture 2015-09-12_07-54-01_pm](https://cloud.githubusercontent.com/assets/4986996/9833190/b51f96ac-598e-11e5-946e-2621bb5e36bb.jpg)

But no MIN,MAX, no graph although Top Talkers are there
![voila_capture 2015-09-12_07-54-45_pm](https://cloud.githubusercontent.com/assets/4986996/9833195/cee4758a-598e-11e5-9c46-42f0f3addcd4.jpg)

**Comment by lucaderi** [comment]
Can you please use the dev version of the package? The stable package will include only crash fixes, all the development/improvements go in dev.

**Comment by michalzahor** [comment]
What functionality from 1.2.1 version is not available in 2.x dev ?
[ I have to consider moving back to 1.2.x ]. Is 2.X meant to be reworked version where functionality will be added step by step or 2.0 should have all the functionality of 1.x ?

The must for us is:
Interface history ( is it working in DEV branch ? )
Host history ( is it working in DEV branch ? )

**Comment by lucaderi** [comment]
Interface history: replaced. The GUI is work in progress.
Host history: implemented.
Again, feel free to do what you like, but please open bugs only on the development version (or stable) but not on old 1.x versions.
