### ISSUE TITLE
Display Data in ntopng using ElasticSearch

### ISSUE THREAD

**Issue by pleoeter** [ntop/ntopng#1650]
I am using ntopng V 3.1, ES 5.6.3, I can save data and see using sudo ntopng -F 'es;ntopng;ntopng-%Y.%m.%d;http://127.0.0.1:9200/_bulk;'
but i cannot display it in lua web, like that happens in mysql case, I am using the same template provided 
in ntopng READme.elasticsearch , any guideline to display it in table form in lua web

**Comment by emanuele-f** [comment]
Hi, the historical explorer does not support the ES data source. You can only export to ES but cannot retrieve.

**Comment by pleoeter** [comment]
so historical explorer only support SQL database and that too in paid edition?

**Comment by emanuele-f** [comment]
Yes, only MySQL support

**Comment by pleoeter** [comment]
Thank you

**Comment by emanuele-f** [comment]
You are welcome

**Comment by pleoeter** [comment]
Is there any possibility in near future?

**Comment by emanuele-f** [comment]
No, we only support ES / logstash export for interoperability, we won't provide a full integration

**Comment by pleoeter** [comment]
Is there any possibility in near future?

**Comment by pleoeter** [comment]
Thank you @emanuele-f

**Comment by emanuele-f** [comment]
You are welcome!
