### ISSUE TITLE
Pls Help Script to Flow ASA CISCO 

### ISSUE THREAD

**Issue by britoalegre** [ntop/ntopng#1651]
Please, I need help to capture traffic flow ASA CISCO ... already tried everything and did not appear even arriving traffic without IP from ntopng

Does anyone have the ntopmg.conf t and nprobe.conf script?

**Comment by emanuele-f** [comment]
Hi, please have a look at this tutorial https://www.ntop.org/nprobe/network-monitoring-101-a-beginners-guide-to-understanding-ntop-tools/
