### ISSUE TITLE
Slack integration - Custom channel & proxy support

### ISSUE THREAD

**Issue by fsergot** [ntop/ntopng#1653]
Hello,

I have tried to use the Slack integration with ntopng and I am facing 1 issue and 1 question (maybe I need to create separate issues, let me know):
1. Channels naming
It seems the channel names are hard coded and need to be as described in https://github.com/ntop/ntopng/blob/dev/doc/README.slack. That is really annoying as those are very generic names and interfere with existing channels we are using. I think using a custom channel name is a must have (maybe one channel for all notif also)

2. Proxy support
All ours systems are behind a web proxy for internet access. This is not an issue at all for ntopng to work, except for the slack notification that goes to the slack URLs. I have not found any indication on how to add proxy information for such calls. Is it doable? If not, would you be able to add that feature? I could whitelist ntopng server on the firewall but that is not clean.

Thanks

**Comment by showipintbri** [comment]
I too would prefer to choose which Slack channels to send alerts.

Are the slack channels identified in a configuration file I can edit on the host OS?

**Comment by emanuele-f** [comment]
Currently they are not configurable, they are bound to the alert "entity type": https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/alert_endpoints/slack.lua#L83

**Comment by emanuele-f** [comment]
Channels names are now configurable with commit 25a1a961c2d5a4e0e3b0d13445361280225f8c73

**Comment by emanuele-f** [comment]
@fsergot we use curl to send requests to slack. Curl already supports the `http_proxy` environmental variable, so proxy support should be already available to you. Please check out https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html . You will need to specify the env variable either in `/etc/environment` or into the ntopng service.
