### ISSUE TITLE
Geolocation fails

### ISSUE THREAD

**Issue by Bigbobd** [ntop/ntopng#1654]
The geolocation fails on my system.  I have ntopng installed on a RaspberryPi and any device I use to access the web interface (mac, windows, linux) or browser (IE, Firefox, Chrome, Safari, Opera)
I receive the same SSL script error.

It appears that google needs a https connection not http.
ERROR:
cgi.gstatic.com cannot be open because the connection is not secure

"error-message">Safari kann die Seite „http://csi.gstatic.com/csi?v=2&amp;s=mapsapi3&amp;v3v=31.8a&amp;action=apiboot2&amp;e=10_1_0,10_2_0&amp;rt=main.4“ nicht öffnen, da Safari keine sichere Verbindung zum Server „csi.gstatic.com“ aufbauen kann

![screen shot 2018-02-13 um 10 14 55](https://user-images.githubusercontent.com/6236933/36143886-ad0a6f6e-10ac-11e8-925b-babbe46e988a.png)

**Comment by emanuele-f** [comment]
Hi, I cannot reproduce the problem with chrome. The URL we use for maps api is https, as you can see here https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/lua_utils.lua#L1112 . Do you have a valid API maps key set into the ntopng misc prefs?

**Comment by Bigbobd** [comment]
I just modified the default location in the PHP page to mine.  Everything else works.

Thank you.

**Comment by emanuele-f** [comment]
So, is the issue solved? Please close the issue if so.

**Comment by Bigbobd** [comment]
hmm, solved..??? for me sure.
