### ISSUE TITLE
Informative alert when a new MAC address is observed/re-seen/disappears

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1659]
When a new MAC address (ignore multicast/broadcast addressed) NOT/NEVER previously observed is reported by ntopng a new informative alert (i.e. it is not a problem but just a log entry with MAC, interface and time) must be issued. This option will not require a preference as it will be enable all the time. The goal is to detect new mac addresses not previously observed that might indicate intruders. It would be nice to report in the MAC address page a new table row that contains an entry similar to "First observed on"

Likewise when a MAC address was previously observed but it now appears/disappears a new informative alert has to be generated. The generation of this alert is conditional to a preference (not set by default).

**Comment by lucaderi** [comment]
![screen shot 2018-02-22 at 09 08 32](https://user-images.githubusercontent.com/4493366/36526842-f9d8f946-17af-11e8-90b4-440cdbac0436.png)
Not all MAC addresses are alike. For instance you should NOT generate alerts for MAC that do not correspond to physical device such as broadcast/multicast/private MACs as in the above example.

**Comment by lucaderi** [comment]
As you are fixing alerts, please also fix this other cosmetic bug.
![screen shot 2018-02-22 at 09 11 16](https://user-images.githubusercontent.com/4493366/36526954-5c77e800-17b0-11e8-9e17-4652372bf761.png)

1. the @0 (rendered with a nordic character) should disappear as VLAN 0 does not exist. if you need to keep it internally as ntopng requires it, feel free to do that, but remove it from user visualisation and remove characters as the one I reported.
2. "Application is misleading". First of all it should be "Application Protocol", but this is valid only for TCP/UDP and it should be removed 
![screen shot 2018-02-22 at 09 13 23](https://user-images.githubusercontent.com/4493366/36527023-a83cf5b4-17b0-11e8-8075-2eb5a2b5d67b.png)
for other protocols such as ICMP. If you want to leave it, then in that case don't call it application but L3 protocol or similar. IMHO it would be better to put L3 protocol next to Flow: .. (see the above screenshot) and do not report Application for non TCP/UDP

**Comment by emanuele-f** [comment]
Fixed with 85298201c7b538b25f33dd9a77ab31555987deeb and 25210c3c373236006170a5de49c114af30a04ee0
