### ISSUE TITLE
Script "C:\Program Files\ntopng\scripts\lua\pro\dashboard.lua" returned an error

### ISSUE THREAD

**Issue by pgdelfino** [ntop/ntopng#166]
after 20 minutes of working i got 

![image](https://cloud.githubusercontent.com/assets/14275275/9850247/9d9bcfd2-5af1-11e5-917b-7d80686413a0.png)

**Comment by kYroL01** [comment]
Which is your ntopng version ?
This error appears when you refresh the page or rise up during the normal activity ?

**Comment by pgdelfino** [comment]
Version 150915  during normal activity

 

Da: Michele Campus [mailto:notifications@github.com] 
Inviato: martedì 15 settembre 2015 14:50
A: ntop/ntopng
Cc: pgdelfino
Oggetto: Re: [ntopng] Script "C:\Program Files\ntopng\scripts\lua\pro\dashboard.lua" returned an error (#166)

 

Which is your ntopng version ?
This error appears when you refresh the page or rise up during the normal activity ?

—
Reply to this email directly or view it on GitHub <https://github.com/ntop/ntopng/issues/166#issuecomment-140378314> .  <https://github.com/notifications/beacon/ANnSy3Ht1SN7_qotkPOvjyWMFIqhKJEoks5oyAtrgaJpZM4F80O3.gif> 



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
http://www.avast.com



----------------------------------------------------------------------------------------------------------------------------------------------------------------
This message is confidential and solely for the intended address(es). 
If you are not the intended recipient of this message, please notify the sender immediately and delete it from your system. 
Unauthorised reproduction, disclosure, modification and or distribution of this e-mail is strictly prohibited. 
The contents of this e-mail do not constitute a commitment by Aubay Italia S.p.A., except where expressly provided for in a written agreement between you and Aubay Italia S.p.A

**Comment by lucaderi** [comment]
This commit https://github.com/ntop/ntopng/commit/febd8775b51704e996e49ab08ae03c7542675444 should have fixed the bugs on windows. A new windows build has been uploaded to http://packages.ntop.org/Windows/. Please give it a try. If problems are not gone yet, we'll reopen the bug accordingly. Thanks for reporting the issues.

**Comment by hplc** [comment]
While normal visiting: http://10.20.5.89:3000/lua/pro/dashboard.lua, maybe after 10 minutes, page error:

    Script "/usr/share/ntopng/scripts/lua/pro/dashboard.lua" returned an error:
    /usr/share/ntopng/scripts/lua/pro/dashboard.lua:1: '=' expected

ntopng Community v.2.2.151211
Ubuntu 12.04 LTS and 14.04 LTS all got this problem.

**Comment by lucaderi** [comment]
I think you are using the nProbe pro in demo mode (no license) then the demo expires, you are back to standard version and thus the error. This is normal. I see two options: you buy a permanent license or you start ntopng with --community.
