### ISSUE TITLE
Implement hide from 'top'

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1660]
In a network there are some top talkers that are not relevant (e.g. storage subsystem) but that are always on top X reports. It is requested to remove these hosts/networks from the top list so that for instance when we see 'top talkers' they do not appear (or appear under a new entry called 'top hidden').

You can hide a host from the host preferences (http://xxxx:3000/lua/host_details.lua?ifid=KKK&host=YYYY&page=config) and by also adding a new preference where you can specify networks that are supposed to be hidden all the time. Hidden hosts must carry a special icon (e.g. https://fontawesome.com/icons/eye-slash?style=regular) in hosts list so that we know such host is hidden.

**Comment by emanuele-f** [comment]
We can approach this in two ways:
  - Fontend filter: we keep internal statistics calculations the same and only filter on the visualization layer.
    PRO: we can apply and revert filters as we wish immediately without touching the actual data
    CONS: if we calculate top 5 hosts, and then hide these 5 hosts, we won't get any remaining top data..

  - Backend filter: when we calculate the top hosts, we exclude the hosts to ignore from the calculation.
    PRO: we can effectively calculate the new top 5 hosts excluding x,y,z
    CONS: the filter does not apply to old data and we completely lose top host information from x,y,z in the past

Is this list of affected visualizations exhaustive?
  - "Minute Interface Top Traffic Statistics" into the charts pages
  - "Top Senders" / "Top Receivers" interface chart
  - "Traffic Report" charts

**Comment by lucaderi** [comment]
In the preferences there must be a list of CIDR (hosts+nets) that contain the list of hosts/networks to hide. Each host must a icon that shows if a certain host is hidden from top. All settings (i.e. hide/unhide) are handled by this global, per interface, preference that defines the hosts to be hidden.
During top calculation, hidden hosts are grouped into a new "special host" called "hidden hosts", so that in the top X calculation all hidden hosts (if top) are collapsed into at most this special host. Obviously this host cannot be clicked etc as it happens with "Other".

**Comment by emanuele-f** [comment]
Implemented in 86ac46abd4e915fe461f6c9b033459e62d457543 and 86ac46abd4e915fe461f6c9b033459e62d457543
