### ISSUE TITLE
How to get historical charts of a host pool

### ISSUE THREAD

**Issue by jmginer** [ntop/ntopng#1661]
Hello, I've just installed nprobe + ntop because I want to get the 95 percentil network usage of a /24 subnet.

I created a host pool, and added the subnet. On the Host Pool list, the Throughput colums is showing the correct rate, but I dont find any tab to get the historical charts.

There is any option to get the historical charts of a host pool, or some workaround the get the 95 percentil usage of a subnet (or a AS number).

Thanks!

**Comment by emanuele-f** [comment]
Hi, you need to enabled the host pools timeseries from the ntopng preferences (from the cog icon in the menu). Then a chart icon will appar in the host pools page.

**Comment by tomwimmenhove** [comment]
~@emanuele-f In the latest ntopng, there seems to be no "host pools timeseries" in the "Timeseries" tab under preferences.~
Never mind. It's no longer available, except with a 'professional' licence.
