### ISSUE TITLE
Please use pkg-config to find nDPI (instead of ad-hoc)

### ISSUE THREAD

**Issue by bjornfor** [ntop/ntopng#1662]
I'm working on upgrading ntopng in Nix/Nixpkgs to 3.2 (from 2.0) and I'm finding the method used by the ntopng build system to locate nDPI annoying. We already have nDPI packaged and providing .pc/pkg-config file, but ntopng still insists on having nDPI next to itself and building it from scratch.

**Comment by bjornfor** [comment]
Oh, I see this has been improved / fixed since the latest release (3.2): e7283a0812bf935012be8564e6c555780bfc0e88 ("Build process: Smarter nDPI version checking").

Please make a release to help downstreams build ntopng.

**Comment by simonemainardi** [comment]
@bjornfor suggested changes are already available in the ntopng dev branch and in the companion nDPI dev branch.
