### ISSUE TITLE
Build with external luajit no longer possible, due to lj_obj.h?

### ISSUE THREAD

**Issue by bjornfor** [ntop/ntopng#1664]
Since commit 4f98c03dbc23417fec8dabfb812e04c0830a1848 ("LuaJIT lua_State fwd decl. compil. fix")[1], ntopng depends on lj_obj.h from luajit. From what I can tell, this header file is private, because luajit does not install it by default. At least the header is missing from luajit packages in both Nixpkgs and Ubuntu.

Has anyone tried building without the bundled luajit since august 2017, when this dependency was first added?

[1] A later commit removed that header include, but finally commit 1f2019789bdf4e5003b08f386944f3d118e19eb5 ("Adds missing #include lj_obj.h") added it back in.

**Comment by lucaderi** [comment]
This is a change necessary to address issues like https://github.com/LuaJIT/LuaJIT/issues/49 If you have a solution that is better than this I am ready to evaluate it, but it must run *efficiently* on 32 and 64 bit, ARM, MIPS and Intel. In that case please reopen this ticket.

**Comment by bjornfor** [comment]
(Thanks for the ref, but unfortunately I didn't grok that issue nor the connection to this issue.)

If building against system provided luajit is simply unsupported, that's fine. What's not fine is having the ntopng build system do things like ```pkg-config --cflags luajit``` if it's never expected to work. Should I open a separate issue for that?
