### ISSUE TITLE
Forgot where to put the PF-ring license file

### ISSUE THREAD

**Issue by misterguitar** [ntop/ntopng#1666]
Hey guys. i had to reload my ntopng box and need to put the license back on for pf-ring ZC. I have the license numebr but forgot what file to put it in and where that file goes! This is for pf-ring installed by packages from the repo for centos 7. Thanks!

**Comment by cardigliano** [comment]
Please do:

echo KEY > /etc/pf_ring/AABBCCDDEEFF

where 
- KEY is the license number
- AABBCCDDEEFF is the mac address, uppercase, without ':'

**Comment by misterguitar** [comment]
Thanks! That works!

**Comment by rafal-almusawi** [comment]
@cardigliano how about if we have Napatech Card?

**Comment by cardigliano** [comment]
Please use the SN provided by "pfcount -L -v  1"

**Comment by rafal-almusawi** [comment]
@cardigliano i already use that and place it in /etc/pf_ring 
is the file name should be the SN without dashes ?

**Comment by cardigliano** [comment]
Please use just the SN as provided by pfcount, dashes included

**Comment by rafal-almusawi** [comment]
Thanks its working
