### ISSUE TITLE
LAST_SWITCHED is wrong 

### ISSUE THREAD

**Issue by Howard-Chang** [ntop/ntopng#1667]
Hi, my OS is Centos7 and the netflow version is v9. I input netflow  to ES through nprobe+ntopng, but I found that the LAST_SWITCHED is wrong . The time is stay on 2018/1/21 for example 1516503759 and the @timestamp is the same for example January 21st 2018, 16:46:00.000 . the difference is about 1 month.
this is my ntopng and nprobe command:
ntopng:
ntopng /c -i "tcp://127.0.0.1:2055" --local-networks "192.168.0.0/16" -F "es;ntopng;ntopng-%Y.%m.%d;http://192.168.0.159:9200/_bulk;"
nprobe:
nprobe /c --collector-port 5556 --zmq tcp://127.0.0.1:2055

this is the netflow info from wireshark:
![image](https://user-images.githubusercontent.com/19474557/36473778-8c1a2a4e-1730-11e8-8e7d-91a4417c0d76.png)
![image](https://user-images.githubusercontent.com/19474557/36473798-a0844438-1730-11e8-9ae5-e146f57b7ffa.png)

could I tune the @timestamp to my real time or tune the LAST_SWITCHED to the right time?

thank you very much !!!

**Comment by Howard-Chang** [comment]
If I input netflow to Elasticsearch through nprobe, there is the same issue.
this is my nprobe version:
[root@localhost etc]# nprobe -v

Welcome to nProbe v.8.3.180208 (r6051) for x86_64-unknown-linux-gnu
with native PF_RING acceleration.
Copyright 2002-18 ntop.org

Build OS:      CentOS Linux release 7.4.1708 (Core)
SystemID:      3B1A1AF276XXXXXX
GIT rev:       dev:4c51c7b090bf96f95cae111f579b5bc07bac4562:201XXXXX
License:       Invalid nProbe license (/etc/nprobe.license) [License mismatch error]

nProbe is subject to the terms and conditions defined in
the LICENSE and EULA files that are part of this package.

nProbe also contains third party code:
Radix tree code - (C) The Regents of the University of Michigan
                      ("The Regents") and Merit Network, Inc.
sFlow collector - (C) InMon Inc.

**Comment by emanuele-f** [comment]
Hi, please send me a sample netflow capture to faranda@ntop.org . On the nprobe host, run: `tcpdump -p 5556 -n -s0 -w netflow.pcap`. Please use wireshark to verify that the provided pcap contains both the netfow template and the netflow data.

**Comment by Howard-Chang** [comment]
ok. I have sent you the pcap.
thank you very much !

**Comment by emanuele-f** [comment]
Hi @Howard-Chang, thank you.
By inspecting the pcap I'm seeing that your netflow exporter is missing the first and last seen timestamps in the template, so nprobe is tricked while calculating them.

So please either modify your exporter configuration or contact your vendor to be sure to add the template fields `LAST_SWITCHED` and `FIRST_SWITCHED`.
