### ISSUE TITLE
Align RRD timestamps

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1668]
For periodic activities (e.g 5 min) the timestamp of the RRDs is not aligned across all the RRDs. it is requested all the RRDs at minute/5 min to have the same timestamp.

**Comment by emanuele-f** [comment]
Do you refer to the timestamp difference between RRDs of different interfaces? If so, can we align the times to the previous min/5 minutes with a modulo e.g. `when = os.time() % 300` in 5min.lua ?

**Comment by lucaderi** [comment]
For the time being we have decided to leave the system as is, because under heavy load the time it takes to write RRDs could be large and thus create side effects.
