### ISSUE TITLE
New Dashboard Design

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1670]
The design of the current ntopng dashboard is outdated. Not too pretty, not configurable, all but modern. Ideas and suggestions are welcome.

**Comment by emanuele-f** [comment]
Some ideas:
- Dynamic layout: the dashboard should use bootstrap table standard and not html `colspan` tags.
- For customizable layout, we should provide sort of widgets and allow the user to choose what to see and how to place it

Frameworks / ideas
- http://gridstackjs.com/
- http://angular-dashboard-framework.github.io/angular-dashboard-framework/#/sample/01
- http://dsmorse.github.io/gridster.js/#demos

The implementation should be based on a powerful framework but still provide a ntopng own look and functionalities.

**Comment by CDawson1** [comment]
This is a little non-technical, but allow for themes/branding.  This could easily be a showcase in a NOC of some description, and it would be nice to be able to brand it in some way.  Not trying to detract from the work that was put in, but it would be nice, once allowing for said customization, to be able to put our own mark on it as well.

**Comment by hytek3000** [comment]
The features I would like to keep is the search box. Easily accessible, and easily seen. We have ntopng enterprise, and nprobe pro in our place, and we also have Solarwinds Orion/NPM: Orion SUCKS when trying to search for anything. NTOPNG's search function is so much better, and easier.

I do like the idea of widgets (like solarwinds Orion), but the one function I enjoy and use the most is the search box.

**Comment by simonemainardi** [comment]
other suggestions for the design in:

- https://github.com/ntop/ntopng/issues/2147
- https://github.com/ntop/ntopng/issues/1407
- https://github.com/ntop/ntopng/issues/1408

**Comment by emanuele-f** [comment]
Another request from a ntopng user: create 1 week and 1month charts and display them into the dashboard

**Comment by Aikatsui** [comment]
Design suggestion: ntopng interface quite big for 15inch laptop screens then we only able to see few details (especially affect due screen height). is it possible to add option for zoom out interface eg: 70% 60% and it must remain till adjust again. (sometimes we may not use big screens).

**Comment by 612wong** [comment]
Design suggestion is end-user centric.
- application support engineer would like to see the flow details around particular protocol or host pair
- network engineer would like to see abnormal network pattern or potential attacks within and outside the firewall
- network manager would like to see the overall of critical alerts that business cares
Based on this, I think the alert framework needs to be flexible and easy to be customized for alerting. Then end-user will put their favourite alert dashboard and high-level overview next to it as their default dashboard.
Having said that, I also deal with people love doing their own dashboard in Grafana. It may be well to publish the details about the series.

**Comment by MatteoBiscosi** [comment]
New customizable dashboard has been implemented
