### ISSUE TITLE
Fortigate flows problem

### ISSUE THREAD

**Issue by raa0x0** [ntop/ntopng#1671]
Hello, we have Ntopng Enterprise, Nprobe Pro + DHCP, DNS Plugin (all on same machine).
We are sending netflow from our Fortitage Firewall to nProbe, then we use this in ntopng (zeromq).
Our problem is this:
![ntopng](https://user-images.githubusercontent.com/20373119/36537460-7ad06910-17d0-11e8-8908-008bb2659811.png)
Ntopng display SRC IP as DST IP and conversely.

What we can do with that?

**Comment by emanuele-f** [comment]
I what's your ntopng and nrpobe configuration?

**Comment by raa0x0** [comment]
Ntopng:
>-G=/var/run/ntopng.pid
> -F "es;flows;ntopng-%Y.%m.%d;http://127.0.0.1:9200/_bulk;"
> -m=x.x.x.x/24,y.y.y.y/24
> --interface="tcp://127.0.0.1:5556"
> -x=300000
> -X=150000
> --dns-mode=1
> --online-license-check
> --data-dir=/opt/ntopng_data

nProbe:

> --zmq="tcp://127.0.0.1:5556"
> --collector-port=2055
> -n=none
> -i=none
> --online-license-check
> -O=4
> -u=-1
> -Q=-1

**Comment by emanuele-f** [comment]
Can you send me a pcap with Netflow traffic at faranda@ntop.org?
You can generate with the command: `tcpdump -n -s 0 -w netflow.pcap port 2055`. Please ensure that the pcap contains both the netflow template and data.

**Comment by raa0x0** [comment]
Sure, check your email is that enough traffic.

**Comment by lucaderi** [comment]
Hi @raa0x0 as you can see from the messages below (i have open with wireshark your pcap file sent to Emanuele) your device is sending the same value for IN and OUT. This looks like an issue. You can read more at https://www.ietf.org/rfc/rfc3954.txt

So please talk with your device manufactured as perhaps there is a misconfiguration in your device.

![image](https://user-images.githubusercontent.com/4493366/36602056-40434bc2-18b7-11e8-84db-c9fdd4f90399.png)

![image](https://user-images.githubusercontent.com/4493366/36602068-4c1465d0-18b7-11e8-9008-10e627920d15.png)

**Comment by StrilGit** [comment]
Hi!

I can see exactly the same issue with my fortigates. It would be great to have a workaround to let ntopng/nprobe ignore the field "OUT_BYTES".

Stril

**Comment by lucaderi** [comment]
If you want to ignore OUT_XXX (i.e POST counters) please add to nProbe "-p 1.1/1/1/1/0/1/1/0/0"
