### ISSUE TITLE
Active discovery when ntopng is on zmq interface

### ISSUE THREAD

**Issue by aouinizied** [ntop/ntopng#1673]
Hi all,

I'm running a Home gateway based flow monitoring probe connected on my LAN (192.168.1.1).
The probe is exporting records (using zmq) to ntopng which is running on a LAN device (ex: 192.168.1.5).
In such situation, the active device polling is completely feasible. So my question is why ntopng is forced to not enable active polling feature on such situation? (as ntopng have the information that both probe and collector are running on the same LAN.
There is a hook to disable such feature? 

Regards,
Zied

**Comment by lucaderi** [comment]
This is not possible because on ZMQ it's a read-only link with nprobe exporting data to ntopng. If ntopng has to discover assets it has to inject traffic in the network, thing that is not possible over ZMQ.

**Comment by aouinizied** [comment]
Thanks for your reply.
