### ISSUE TITLE
Traffic flows not being reported properly in SANKEY charts

### ISSUE THREAD

**Issue by EinerPetersen** [ntop/ntopng#1674]
HI Folks,
The behaviour of NTOPNG in any mode (Pro or community) is:
1) on the home page, the SANKEY flows quit working after about 3 - 5 minutes, post ntopng restart, of operation when they used to work in previous versions -- my current version is  "3.2.180214 -  Community Edition" (Yes, I have almost continuous traffic per tcpdump/wireshark/iptables logging

2) using the "Talkers" on a specific host no longer shows SANKEY flows for that host, it shows the same results as the community desktop page ---- this also worked in previous versions

my basic setup is:
host =interface eth1 (which is ip-less and set to promiscuous mode)
eht1 is diret connected to a spanned/monitoring port on a cisco router/switch (eth1 sees all netwwork traffic on my network
OS=CentOS EL7 patched to current as of 2018-02-23
no system or network config changes have been made since when it was working vs now

Any ideas?

**Comment by emanuele-f** [comment]
Hi, the point 2. is now solved in dev and it will backported to stable soon. About point 1, please be more specific about the issue. In particular:
1) Does the chart stop refreshing or it becomes blank? (Screenshot please)
2)  If you open the browser inspector after the issue appear, can you see see any javascript errors reported?

**Comment by EinerPetersen** [comment]
Hi Emanuele,
Ok ..... no javascript errors reported

Screenshot of what I am seeing on it's way via reply to email :-)

**Comment by emanuele-f** [comment]
Please send me an email at faranda@ntop.org

**Comment by emanuele-f** [comment]
Hi @EinerPetersen, it seems like there is now a problem with your email, any email I send you is not delivered. Anyway, let's continue discussion here.

From the pcap you sent me previously you traffic is not continuos, so I think this is not a problem into ntopng.

**Comment by emanuele-f** [comment]
No further feedback received, I'm closing the issue for now.
