### ISSUE TITLE
Throughput is not correctly computed

### ISSUE THREAD

**Issue by aouinizied** [ntop/ntopng#1675]
Hi all,

This issue is concerning ntopng per flow throughput.
Using zmq export (nprobe running on PC1) exporting to ntopng on PC2. I set nprobe with an avtive timeout of 2 secs in order to refresh intensively stats. 
I start an iperf flow saturating my 1Gbps link.
ntopng shows 164Mbit/s which is uncorrect. However when I compute throughput manually based on nprobe export I get a correct value. 
Moreover, the interface throughput is correct on ntopng.
Any hint to solve this bug?

Regards,
Zied
![screenshot](https://user-images.githubusercontent.com/4332251/36676201-47b1a01a-1b0b-11e8-8757-361f1c0741ac.png)

**Comment by aouinizied** [comment]
here the log when nprobe is configured with active timeout of 3 secs:

26/Feb/2018 15:44:40 [CollectorInterface.cpp:220] {"8":"192.168.1.103","12":"84.39.50.197","10":65535,"14":65535,"2":150361,"1":225240778,"22":1519656276,"21":1519656278,"7":34815,"11":5001,"6":0,"4":17,"5":0,"16":0,"17":60940, "57943":"192.168.1.103"} [msg_id=24]
26/Feb/2018 15:44:41 [CollectorInterface.cpp:220] {"8":"192.168.1.103","12":"84.39.50.197","10":65535,"14":65535,"2":79,"1":118342,"22":1519656278,"21":1519656278,"7":34815,"11":5001,"6":0,"4":17,"5":0,"16":0,"17":60940, "57943":"192.168.1.103"} [msg_id=27]
26/Feb/2018 15:44:43 [CollectorInterface.cpp:220] {"8":"192.168.1.103","12":"84.39.50.197","10":65535,"14":65535,"2":147754,"1":221335492,"22":1519656279,"21":1519656281,"7":60820,"11":5001,"6":0,"4":17,"5":0,"16":0,"17":60940, "57943":"192.168.1.103"} [msg_id=32]
26/Feb/2018 15:44:45 [CollectorInterface.cpp:220] {"8":"192.168.1.103","12":"84.39.50.197","10":65535,"14":65535,"2":206475,"1":309299550,"22":1519656282,"21":1519656284,"7":60820,"11":5001,"6":0,"4":17,"5":0,"16":0,"17":60940, "57943":"192.168.1.103"} [msg_id=38]
26/Feb/2018 15:44:48 [CollectorInterface.cpp:220] {"8":"192.168.1.103","12":"84.39.50.197","10":65535,"14":65535,"2":206163,"1":308832174,"22":1519656285,"21":1519656287,"7":60820,"11":5001,"6":0,"4":17,"5":0,"16":0,"17":60940, "57943":"192.168.1.103"} [msg_id=42]
26/Feb/2018 15:44:51 [CollectorInterface.cpp:220] {"8":"192.168.1.103","12":"84.39.50.197","10":65535,"14":65535,"2":206367,"1":309137766,"22":1519656288,"21":1519656290,"7":60820,"11":5001,"6":0,"4":17,"5":0,"16":0,"17":60940, "57943":"192.168.1.103"} [msg_id=46]
26/Feb/2018 15:44:55 [CollectorInterface.cpp:220] {"8":"192.168.1.103","12":"84.39.50.197","10":65535,"14":65535,"2":206841,"1":309847818,"22":1519656291,"21":1519656293,"7":60820,"11":5001,"6":0,"4":17,"5":0,"16":0,"17":60940, "57943":"192.168.1.103"} [msg_id=51]
26/Feb/2018 15:44:57 [CollectorInterface.cpp:220] {"8":"192.168.1.103","12":"84.39.50.197","10":65535,"14":65535,"2":137619,"1":206153262,"22":1519656293,"21":1519656295,"7":60820,"11":5001,"6":0,"4":17,"5":0,"16":0,"17":60940, "57943":"192.168.1.103"} [msg_id=56]
26/Feb/2018 15:44:59 [CollectorInterface.cpp:220] {"8":"192.168.1.103","12":"84.39.50.197","10":65535,"14":65535,"2":206398,"1":309184204,"22":1519656296,"21":1519656298,"7":60820,"11":5001,"6":0,"4":17,"5":0,"16":0,"17":60940, "57943":"192.168.1.103"} [msg_id=61]
26/Feb/2018 15:45:02 [CollectorInterface.cpp:220] {"8":"192.168.1.103","12":"84.39.50.197","10":65535,"14":65535,"2":206120,"1":308767760,"22":1519656299,"21":1519656301,"7":60820,"11":5001,"6":0,"4":17,"5":0,"16":0,"17":60940, "57943":"192.168.1.103"} [msg_id=65]
26/Feb/2018 15:45:06 [CollectorInterface.cpp:220] {"8":"192.168.1.103","12":"84.39.50.197","10":65535,"14":65535,"2":206598,"1":309483804,"22":1519656302,"21":1519656304,"7":60820,"11":5001,"6":0,"4":17,"5":0,"16":0,"17":60940, "57943":"192.168.1.103"} [msg_id=70]
26/Feb/2018 15:45:08 [CollectorInterface.cpp:220] {"8":"192.168.1.103","12":"84.39.50.197","10":65535,"14":65535,"2":206012,"1":308605976,"22":1519656305,"21":1519656307,"7":60820,"11":5001,"6":0,"4":17,"5":0,"16":0,"17":60940, "57943":"192.168.1.103"} [msg_id=81]
26/Feb/2018 15:45:12 [CollectorInterface.cpp:220] {"8":"192.168.1.103","12":"84.39.50.197","10":65535,"14":65535,"2":206506,"1":309345988,"22":1519656308,"21":1519656310,"7":60820,"11":5001,"6":0,"4":17,"5":0,"16":0,"17":60940, "57943":"192.168.1.103"} [msg_id=86]
26/Feb/2018 15:45:15 [CollectorInterface.cpp:220] {"8":"192.168.1.103","12":"84.39.50.197","10":65535,"14":65535,"2":206632,"1":309534736,"22":1519656311,"21":1519656313,"7":60820,"11":5001,"6":0,"4":17,"5":0,"16":0,"17":60940, "57943":"192.168.1.103"} [msg_id=96]
26/Feb/2018 15:45:18 [CollectorInterface.cpp:220] {"8":"192.168.1.103","12":"84.39.50.197","10":65535,"14":65535,"2":206764,"1":309732472,"22":1519656314,"21":1519656316,"7":60820,"11":5001,"6":0,"4":17,"5":0,"16":0,"17":60940, "57943":"192.168.1.103"} [msg_id=114]

**Comment by aouinizied** [comment]
I remark that when nprobe is configured with higher value of t (example: 10 secs), the ntopng output is correct (on per flow). However, now it is completely incorrect on (per interface) one . This is a little bit weird as such value is simply computed as volume/duration.

Regards,
Zied

**Comment by aouinizied** [comment]
Solved by changing this line in /src/Flow.cpp (from 5 secs to 1 sec)
    if((iface->getIfType() == interface_type_ZMQ)
       && (tdiff_msec < 1000)) {
      /* With ZMQ (if collecting sFlow) we might compute inaccurate
	 throughput when haveing one flow with a single sample so
	 we spread the traffic across at least 5 secs
      */

**Comment by simonemainardi** [comment]
can you submit a pull request? thanks

**Comment by aouinizied** [comment]
Done
