### ISSUE TITLE
Ntopng cannot start after recent update

### ISSUE THREAD

**Issue by izzie88** [ntop/ntopng#1676]
Hello @emanuele-f @simonemainardi 
after carrying out update today, ntopng can no longer start.

please see below:

oye@NTOP-DPI:~$ sudo service ntopng status
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2018-02-28 18:40:25 WAT; 4min 48s ago
  Process: 11993 ExecStopPost=/bin/rm -rf /run/ntopng.conf (code=exited, status=0/SUCCESS)
  Process: 11992 ExecStart=/usr/local/bin/ntopng /run/ntopng.conf (code=exited, status=127)
  Process: 11982 ExecStartPre=/bin/sh -c /bin/sed "/-e.*$\|-G.*\|--daemon.*\|--pid.*/s/^/#/" /etc/ntopng/
 Main PID: 11992 (code=exited, status=127)

Feb 28 18:40:25 NTOP-DPI systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis
Feb 28 18:40:25 NTOP-DPI systemd[1]: Started ntopng high-speed web-based traffic monitoring and analysis 
Feb 28 18:40:25 NTOP-DPI ntopng[11992]: /usr/local/bin/ntopng: error while loading shared libraries: libz
Feb 28 18:40:25 NTOP-DPI systemd[1]: ntopng.service: Main process exited, code=exited, status=127/n/a
Feb 28 18:40:25 NTOP-DPI systemd[1]: ntopng.service: Unit entered failed state.
Feb 28 18:40:25 NTOP-DPI systemd[1]: ntopng.service: Failed with result 'exit-code'.

**Comment by izzie88** [comment]
Hello,
Is there any immediate solution to this as the reporting side of the ntopng-ng is critical to business process.

@emanuele-f

**Comment by emanuele-f** [comment]
Hi, what ntopng version? What operating system are you using?

The problem may be related to the version of installed package `zlib1g-dev`. Please try to update `zlib1g-dev`.

**Comment by izzie88** [comment]
hello @emanuele-f 
We run an Ubuntu 16.04
when i do a ntopng --version, see below
oye@NTOP-DPI:~$ ntopng --version
ntopng: error while loading shared libraries: libzstd.so.0: cannot open shared object file: No such file or directory
oye@NTOP-DPI:~$ ntopng --help
ntopng: error while loading shared libraries: libzstd.so.0: cannot open shared object file: No such file or directory

**Comment by emanuele-f** [comment]
Hi this commit should have fixed the issue a87042690adec68879cb47a571e7c7f858e882ef . Please do an `apt-get update && apt-get install ntopng`

**Comment by izzie88** [comment]
Hi @emanuele-f 
Issue is sorted now. Thank you very much.

**Comment by emanuele-f** [comment]
Thank you
