### ISSUE TITLE
Generate alert when interface drops exceed a given threshold

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1677]
ntopng lacks self-monitoring and thus it might be that there an internal error (e.g a loop as in https://github.com/ntop/ntopng/commit/45119bfa9828142564e00041aa1ba8fe29e7af6e) that causes ntopng to stop. This problem must be reported immediately via slack/email/something to the network administrator and NOT just consumed internally by ntopng as this would be useless.
It is requested to
- implement an alert based on interface drops. Example: trigger and alert when drops pass 10% of the interface traffic
- Expedite implementation of https://github.com/ntop/ntopng/issues/272 and likely add other media (eg. Telegram) for reporting these major issues.

**Comment by emanuele-f** [comment]
Implemented in b2082b7788911293d80deff5e1c116fb4ade84ce

![screenshot_1](https://user-images.githubusercontent.com/5488003/37096833-302ba34e-221a-11e8-902a-fa14862b1f91.png)

![screenshot_4](https://user-images.githubusercontent.com/5488003/37096840-3356f1fe-221a-11e8-8539-62487f53cc2a.png)

Additional alert reporting will be addressed in issue #272
