### ISSUE TITLE
Incorrect OS detection (was Incorrect OS Detection #815)

### ISSUE THREAD

**Issue by rdica** [ntop/ntopng#1680]
I am having the same issue as closed:#815. Linux host is detected as Windows 7.

Ubuntu 16.04
```
cat /etc/apt/sources.list.d/ntop-stable.list 
deb http://packages.ntop.org/apt-stable/16.04/ x64/
deb http://packages.ntop.org/apt-stable/16.04/ all/

Package: ntopng
Architecture: amd64
Version: 3.2.180228-4108
Priority: optional
Section: free
Maintainer: Luca Deri <deri@ntop.org>
Installed-Size: 25355
Depends: pfring (= 7.0.0-1788), libsqlite3-0, libgeoip1, redis-server, librrd4, logrotate, libcurl3, libpcap0.8, libldap-2.4-2, libhiredis0.13, libssl1.0.0, libmysqlclient20, librdkafka1, lsb-release, ethtool, libcap2, bridge-utils, libnetfilter-conntrack3, udev, libnuma1, libzmq5, libnetfilter-queue1
Recommends: ntopng-data
Replaces: ntop
Filename: x64/./ntopng_3.2.180228-4108_amd64.deb
Size: 5541576
MD5sum: 2584cde16a68ca07a2813a9e29ea4315
SHA1: ae430bb4efd65e5cf8f9e5a4c9cdc072ff13bc98
SHA256: e151061f36437f38d4693bccb546129ff4eee4524a7c973702924ea6efc62e63
SHA512: c68bd4843da22fca3a66d8a4d9fe808669f4125eec1cf20cf042f31d6c711a37b0b4dce01e4c6899602e58d4f6c0064190db5018e157f3bfc77dad8f1bcc717a
Description: Web-based traffic monitoring.
Description-md5: 59c1e802c8c4538ac78f99e8b8e58c28

```

The host in question is a centos7 VM on qemu/libvirtd:
CentOS Linux release 7.4.1708 (Core) 

I attached a pcap from the interface ntopng uses using

`tcpdump -i eth1 -w graphite-host.pcap host graphite`

![ntop](https://user-images.githubusercontent.com/16609801/36954673-8ada0d10-1ff1-11e8-83c0-13a0b16d75d8.png)

[host-pcap.zip](https://github.com/ntop/ntopng/files/1779272/host-pcap.zip)

**Comment by emanuele-f** [comment]
Hi, ntopng generally performs OS detection via HTTP user agent strings. The attached pcap does not contain http traffic, so I cannot tell if there is a problem

**Comment by rdica** [comment]
I don't have any service listening on tcp/80. There is web service on tcp/443 (apache) and tcp/3000 (grafana), these should be visible in the pcap.

[host-pcap.zip](https://github.com/ntop/ntopng/files/1785558/host-pcap.zip)

**Comment by emanuele-f** [comment]
What's the ip address of `grafite`? Are you capturing local interface packets or packets from a SPAN port?

You need the HTTP client packets, not server packets. For example, if `grafite` is your system host where ntopng is running then if you open the web browser on host `grafite` and connect to an HTTP website it will generate HTTP packets with user agent strings.

The new pcap does not contain such information, please open it with wireshark to see its data.

**Comment by rdica** [comment]
graphite.ldev has address 192.168.15.5
ntopng is not running on that host

A SPAN port is being used. The same one ntopng uses, same one I performed the tcpdump capture on.

graphite is a centos server running graphite/grafana, why would ntopng expect a server to initiate web traffic when that is not part of the function of that server? Are users expected to run some cli web browser on every server just so ntopng detects its OS correctly? I'm confused.

**Comment by emanuele-f** [comment]
HTTP requests are only one of the methods ntopng uses to identify OS. For example, it also uses mDNS names for OS detection. In order to troubleshoot this, you need to capture the specific network packets that allow ntopng to perform OS detection for your host.

One thing you can try is start a tcpdump capture then do a network discovery (from the ntopng gui `Network Discovery` menu in the top bar) and wait for the discovery to end. This would generate interesting traffic which we can inspect.

**Comment by simonemainardi** [comment]
Can you please an try to run a network device discovery to see if the detected OS is still Windows? You know, OS detection involves several heuristics and sometimes the guess is not easy.

Moreover, in order for us to try and reproduce, we would like to ask you the generation of a pcap as follows:

- turn off ntopng and flush its cache (redis-cli flushdb)
- turn off (physically) the mis-detected host
- start the creation of the pcap for the mis-detected host (`tcpdump -i eth1 -w mis-detected-host.pcap host <ip address of the mis-detected host>`)
- turn back on both the mis-detected host and ntopng
- now check the OS detection in ntopng and, if it is still windows, stop tcpdump and send us the created pcap.

**Comment by simonemainardi** [comment]
any news?

**Comment by rdica** [comment]
Initial configuration had only eth1 interface, the one I connect to span port. I found out that network discovery doesn't work on this, so I added eth0 so I coud use discovery. when I switch interface to eth0, the host in question is not detected as Windows 7.

I will try to get the requested information this weekend.

**Comment by emanuele-f** [comment]
@rdica have you followed the suggestions above? What's the result?

**Comment by rdica** [comment]
Sorry no I still haven't had an opportunity. I don't know if/when I can, nor do I know if we're going to implement this in the long term. You can close this, I can always refile in the event I can pursue, thanks.

**Comment by emanuele-f** [comment]
Ok. If you have any updates please reopen/create a new issue.
