### ISSUE TITLE
about ntop license

### ISSUE THREAD

**Issue by kknkuht** [ntop/ntopng#1681]
i had request free license before and get the license
but when I upgrade ntop to 3.2.180228
it became to Community Edition
not the "ntop pro linux/win (x64)"
can u please help me

**Comment by emanuele-f** [comment]
Hi, please see https://www.ntop.org/support/faq/my-license-does-not-work-what-can-i-do .
We prefer discussing license issues privately, if you have further questions please [contact us privately](https://www.ntop.org/support/need-help-2/contact-us/)
