### ISSUE TITLE
there's no MAC address in ntopng

### ISSUE THREAD

**Issue by Howard-Chang** [ntop/ntopng#1685]
Hi everyone, I send netflow(V5) to elasticsearch through nprobe and ntopng, but I found that the MAC address are all 00:00:00:00:00:00.
![image](https://user-images.githubusercontent.com/19474557/37079941-6bd6f420-221f-11e8-90d1-70a58b96a2ba.png)

this is my command:
nprobe: nprobe /c --collector-port 5556 --zmq tcp://127.0.0.1:2055
ntopng: ntopng /c -i "tcp://127.0.0.1:2055" --local-networks "192.168.0.0/16" -F "es;ntopng;ntopng-%Y.%m.%d;http://192.168.0.159:9200/_bulk;"

How can I get the correct MAC address?

thank you in advance!

**Comment by emanuele-f** [comment]
Hi, you need to specify the fields `%IN_SRC_MAC` and `%OUT_DST_MAC` into your nprobe template, so please add `-T "%IPV4_SRC_ADDR %IPV4_DST_ADDR %IN_PKTS %IN_BYTES %OUT_PKTS %OUT_BYTES %FIRST_SWITCHED %LAST_SWITCHED %L4_SRC_PORT %L4_DST_PORT %TCP_FLAGS %PROTOCOL %IN_SRC_MAC %OUT_DST_MAC"` to the nprobe options.

Of course the flow exporter must support these fields in order this to work.

**Comment by Howard-Chang** [comment]
this is the command now:
`nprobe /c --collector-port 5556 --zmq tcp://127.0.0.1:2055 -T "%IPV4_SRC_ADDR %IPV4_DST_ADDR %IN_PKTS %IN_BYTES %OUT_PKTS %OUT_BYTES %FIRST_SWITCHED %LAST_SWITCHED %L4_SRC_PORT %L4_DST_PORT %TCP_FLAGS %PROTOCOL %IN_SRC_MAC %OUT_DST_MAC"
`
but the MAC address is still 00:00:00:00:00:00.
is it because the cisco switch didn't export the MAC information?

thank you !

**Comment by emanuele-f** [comment]
Yes, this is probably the case. You may need to tweek the switch configuration to export this.
You can send me a pcap privately with netflow traffic and template to verify this.

**Comment by emanuele-f** [comment]
Closing the issue as solved, please reopen if necessary.
