### ISSUE TITLE
ntopng license not working

### ISSUE THREAD

**Issue by QuentinBibas** [ntop/ntopng#1686]
Hi,

I tried setting up a license into ntopng, but it doesn't seem to take it

![image](https://user-images.githubusercontent.com/34896282/37102234-b25162d4-2227-11e8-9d62-5ec1c21f4aa2.png)

![image1](https://user-images.githubusercontent.com/34896282/37102717-bb7af3e2-2228-11e8-8fc2-7c2e07490a89.png)
![image2](https://user-images.githubusercontent.com/34896282/37102119-6f9aba1c-2227-11e8-8be6-0cf64c0b4a2a.png)

I've tried using online-license-check on and off, doesn't work :
![image3](https://user-images.githubusercontent.com/34896282/37102229-acb2fb76-2227-11e8-8454-074addd11af1.png)
![image4](https://user-images.githubusercontent.com/34896282/37102231-af2d40dc-2227-11e8-93f7-24ad6346a401.png)
![image5](https://user-images.githubusercontent.com/34896282/37102233-b0d7fbfc-2227-11e8-8d84-dc4a6267d006.png)

I've tried putting a random typed license into the about page, and putting back the one i got, doesn't either
I've tried both having a ntopng.license file and not having one, with the correct number or not
I already tried resetting the license in case i made a mistake, but it doesn't seem to be the case

It seems like if i don't use the online license check, the software won't even try checking for a license on start up
It only says something about the license when i play with the license field in the "about" web page while not configured to use the online checker.
Online checker seems to be blocked by proxy, as it's not really responsive. If it's not http on 80 or https on 443 (not sure about mails), it can't go out.

Best Regards,
Quentin Bibas

**Comment by emanuele-f** [comment]
Hi, please update to the today version of ntopng as the yesterday package contains a problem.

**Comment by QuentinBibas** [comment]
I answered by email, but i'ill answer here too :

Hi thanks for your reply
would you be able to reset the reset token associated with the order since i blew it on troubleshooting this ?

I will try updating tomorrow when i'll be back at work

**Comment by QuentinBibas** [comment]
Hi thanks for your reply
would you be able to reset the reset token associated with the order since
i blew it on troubleshooting this ?

Regards
QBibas

Message envoyé de mon téléphone.

Le 7 mars 2018 5:44 PM, "Emanuele Faranda" <notifications@github.com> a
écrit :

**Comment by ghost** [comment]
Hey Q,,

An identical problem started with my system this morning. I guess it is not us and wanted you to know.

If you noticed, there is a difference in the log messages from before and now.

Before: [License mismatch error]

After: [License format error]

In my case that started this morning after updating to the latest version. I didn't change anything else.

**Comment by QuentinBibas** [comment]
![image](https://user-images.githubusercontent.com/34896282/37144045-313cb180-22bd-11e8-8bc2-a82990560d70.png)

no update seems available at this time ?
I'm using the -stable repo for CentOS 7 : 
![image](https://user-images.githubusercontent.com/34896282/37144180-8b68e53e-22bd-11e8-98c6-7b10374596d3.png)

**Comment by emanuele-f** [comment]
@QuentinBibas sorry for the inconvenient. A new package with the fix is now available.

**Comment by QuentinBibas** [comment]
I can confirm it works, thanks.

[root@sat-vmveeamprox ~]# ntopng --check-license
License Ok
[root@sat-vmveeamprox ~]# ntopng --version
v.3.2.180308    [Enterprise/Professional build]
GIT rev:        3.2-stable:fc5ac058603ff52864ab99739a15d2770528046e:20180308
Pro rev:        r1280
Built on:       CentOS Linux release 7.4.1708 (Core)
System Id:      FE2B2CE6B206AB23
Platform:       x86_64
Edition:        Enterprise
License Type:   Permanent
Maintenance:    Until Thu Mar  7 13:48:21 2019 [364 days left]
License:        4C06CC82B11B3B8BC4A31DFA6A255ABF155196290187D96504

**Comment by emanuele-f** [comment]
Thank you
