### ISSUE TITLE
Professional license issue [License format error]

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#1687]
Hello.

The issue started today morning after a routine update with yum. I do update my system that way for years and today redis stopped recognizing my license.

What did I do or what happen and how could it be fixed?

I replaced my fdqn, the licsnse and system id with bogus currently

Thank you.

Mar 04 16:14:47 myhost.mydomain.ext ntopng[33254]: 04/Mar/2018 16:14:47 [Ntop.cpp:1485] Setting local networks to 127.0.0.0/8
Mar 04 16:14:47 myhost.mydomain.ext ntopng[33254]: 04/Mar/2018 16:14:47 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
Mar 04 16:14:47 myhost.mydomain.ext ntopng[33254]: 04/Mar/2018 16:14:47 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
Mar 04 16:14:47 myhost.mydomain.ext ntopng[33254]: 04/Mar/2018 16:14:47 [NtopPro.cpp:221] [LICENSE] Reading license from Redis
Mar 04 16:14:47 myhost.mydomain.ext ntopng[33254]: 04/Mar/2018 16:14:47 [NtopPro.cpp:136] [LICENSE] MYLICENSEFORNTOPNG: unable to validate Enterprise license [License mismatch error]
Mar 04 16:14:47 myhost.mydomain.ext ntopng[33254]: 04/Mar/2018 16:14:47 [NtopPro.cpp:139] [LICENSE] MYLICENSEFORNTOPNG: found valid Professional license

...

Mar 04 16:15:07 myhost.mydomain.ext ntopng[33254]: 04/Mar/2018 16:15:07 [NtopPro.cpp:464] [LICENSE] System Id:        MYNTOPNGSYSTEMID
Mar 04 16:15:07 myhost.mydomain.ext ntopng[33254]: 04/Mar/2018 16:15:07 [NtopPro.cpp:465] [LICENSE] Edition:        Professional
Mar 04 16:15:07 myhost.mydomain.ext ntopng[33254]: 04/Mar/2018 16:15:07 [NtopPro.cpp:466] [LICENSE] License Type:        Permanent License
Mar 04 16:15:07 myhost.mydomain.ext ntopng[33254]: 04/Mar/2018 16:15:07 [NtopPro.cpp:469] [LICENSE] License:        MYLICENSEFORNTOPNG
Mar 04 16:15:07 myhost.mydomain.ext ntopng[33254]: 04/Mar/2018 16:15:07 [NtopPro.cpp:479] [LICENSE] Maintenance:        Until Sat Mar 24 17:10:28 2018 [19 days left]

...

Mar 07 07:41:51 myhost.mydomain.ext ntopng[24144]: 07/Mar/2018 07:41:51 [Ntop.cpp:1485] Setting local networks to 127.0.0.0/8
Mar 07 07:41:51 myhost.mydomain.ext ntopng[24144]: 07/Mar/2018 07:41:51 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
Mar 07 07:41:51 myhost.mydomain.ext ntopng[24144]: 07/Mar/2018 07:41:51 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
Mar 07 07:41:51 myhost.mydomain.ext ntopng[24144]: 07/Mar/2018 07:41:51 [NtopPro.cpp:221] [LICENSE] Reading license from Redis
Mar 07 07:41:51 myhost.mydomain.ext ntopng[24144]: 07/Mar/2018 07:41:51 [NtopPro.cpp:136] [LICENSE] MYLICENSEFORNTOPNG: unable to validate Enterprise license [License format error]
Mar 07 07:41:51 myhost.mydomain.ext ntopng[24144]: 07/Mar/2018 07:41:51 [NtopPro.cpp:136] [LICENSE] MYLICENSEFORNTOPNG: unable to validate Professional license [License format error]
Mar 07 07:41:51 myhost.mydomain.ext ntopng[24144]: 07/Mar/2018 07:41:51 [NtopPro.cpp:300] WARNING: [LICENSE] Invalid or missing license
Mar 07 07:41:51 myhost.mydomain.ext ntopng[24144]: [NtopPro.cpp:300] WARNING: [LICENSE] Invalid or missing license
Mar 07 07:41:51 myhost.mydomain.ext ntopng[24144]: 07/Mar/2018 07:41:51 [NtopPro.cpp:317] WARNING: [LICENSE] ntopng will now run in enterprise edition for 10 minutes
Mar 07 07:41:51 myhost.mydomain.ext ntopng[24144]: 07/Mar/2018 07:41:51 [NtopPro.cpp:319] WARNING: [LICENSE] before returning to community mode
Mar 07 07:41:51 myhost.mydomain.ext ntopng[24144]: 07/Mar/2018 07:41:51 [NtopPro.cpp:321] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
Mar 07 07:41:51 myhost.mydomain.ext ntopng[24144]: [NtopPro.cpp:317] WARNING: [LICENSE] ntopng will now run in enterprise edition for 10 minutes
Mar 07 07:41:51 myhost.mydomain.ext ntopng[24144]: 07/Mar/2018 07:41:51 [NtopPro.cpp:323] WARNING: [LICENSE] or run ntopng in community mode starting
Mar 07 07:41:51 myhost.mydomain.ext ntopng[24144]: 07/Mar/2018 07:41:51 [NtopPro.cpp:324] WARNING: [LICENSE] ntopng --community
Mar 07 07:41:51 myhost.mydomain.ext ntopng[24144]: [NtopPro.cpp:319] WARNING: [LICENSE] before returning to community mode
Mar 07 07:41:51 myhost.mydomain.ext ntopng[24144]: [NtopPro.cpp:321] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
Mar 07 07:41:51 myhost.mydomain.ext ntopng[24144]: [NtopPro.cpp:323] WARNING: [LICENSE] or run ntopng in community mode starting
Mar 07 07:41:51 myhost.mydomain.ext ntopng[24144]: [NtopPro.cpp:324] WARNING: [LICENSE] ntopng --community
Mar 07 07:41:53 myhost.mydomain.ext systemd[1]: Stopping ntopng high-speed web-based traffic monitoring and analysis tool...
-- Subject: Unit ntopng.service has begun shutting down

**Comment by simonemainardi** [comment]
please, send all the details (order id, system id, ntopng version, operating system) to mainardi at ntop dot org

**Comment by ghost** [comment]
Just did.

**Comment by lucaderi** [comment]
@jozatan Please upgrade to today's version and let us know if with the current build the problem is fixed

**Comment by ghost** [comment]
I'm running today's version. Just checked the repo and there is nothing to update to newer than I've.

~]# yum clean all
~]# yum update
Loaded plugins: fastestmirror
CodeIT                                                                                                   | 2.9 kB  00:00:00     
base                                                                                                     | 3.6 kB  00:00:00     
epel/x86_64/metalink                                                                                     |  17 kB  00:00:00     
epel                                                                                                     | 4.7 kB  00:00:00     
extras                                                                                                   | 3.4 kB  00:00:00     
ntop                                                                                                     | 2.9 kB  00:00:00     
ntop-noarch                                                                                              | 2.9 kB  00:00:00     
remi-php72                                                                                               | 2.9 kB  00:00:00     
remi-safe                                                                                                | 2.9 kB  00:00:00     
updates                                                                                                  | 3.4 kB  00:00:00     
(1/12): base/7/x86_64/group_gz                                                                           | 156 kB  00:00:00     
(2/12): epel/x86_64/group_gz                                                                             | 266 kB  00:00:00     
(3/12): extras/7/x86_64/primary_db                                                                       | 167 kB  00:00:00     
(4/12): epel/x86_64/updateinfo                                                                           | 899 kB  00:00:01     
(5/12): CodeIT/x86_64/primary_db                                                                         |  69 kB  00:00:01     
(6/12): ntop/7/x86_64/primary_db                                                                         | 6.4 kB  00:00:00     
(7/12): ntop-noarch/7/primary_db                                                                         | 3.8 kB  00:00:00     
(8/12): epel/x86_64/primary_db                                                                           | 6.3 MB  00:00:01     
(9/12): base/7/x86_64/primary_db                                                                         | 5.7 MB  00:00:02     
(10/12): remi-php72/primary_db                                                                           | 180 kB  00:00:01     
(11/12): remi-safe/primary_db                                                                            | 1.2 MB  00:00:03     
(12/12): updates/7/x86_64/primary_db                                                                     | 6.0 MB  00:00:04     
Determining fastest mirrors
 * base: mirror.keystealth.org
 * epel: linux.mirrors.es.net
 * extras: repos-lax.psychz.net
 * remi-php72: mirror.team-cymru.org
 * remi-safe: mirror.team-cymru.org
 * updates: mirror.hostduplex.com
No packages marked for update
~]# yum list ntopng
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.keystealth.org
 * epel: linux.mirrors.es.net
 * extras: repos-lax.psychz.net
 * remi-php72: mirror.team-cymru.org
 * remi-safe: mirror.team-cymru.org
 * updates: mirror.hostduplex.com
Installed Packages
ntopng.x86_64                                               3.2.180306-3700                                                @ntop

**Comment by emanuele-f** [comment]
@jozatan sorry for the inconvenient. The package is now available.

**Comment by ghost** [comment]
Thank you Emanuele,

Everything worked right on.

**Comment by ghost** [comment]
Hello.

I updated my ntopng this morning and I'm facing again the same issue. Should I open a new ticket or that one can be reopened?

Thank you in advance.

**Comment by emanuele-f** [comment]
@jozatan, what ntopng version are you using? Please post the output of `ntopng -V`

I've just tested latest dev and stable versions and they work correcly for me.

**Comment by emanuele-f** [comment]
Private email received: this is a maintenance expiration issue.
