### ISSUE TITLE
Generate Traffic Report by Traffic Profile

### ISSUE THREAD

**Issue by pfruh** [ntop/ntopng#1688]
We are separating internal (free) and external (paid) traffic using two traffic profiles to make verifying our monthly bill easier:
```
External - not ip dst net 192.168.0.0/16
Internal - ip dst net 192.168.0.0/16
```
You can already enter the Traffic Profile in the Historical Data Explorer (maybe change that from a Textbox to a Select Field of all available Profiles).

It would be nice to be able to separate by Traffic Profile in more parts of the interface, this would be especially helpful in the Traffic Report section, to generate a report only for external traffic for example.

Or is there maybe an easier way for this (separate traffic, generate reports for the separates) I'm missing?

**Comment by emanuele-f** [comment]
If you are only interested in monitoring external traffic you can apply a BPF filter on ntopng itself via the `-B` command. If you want both maybe you can run another instance of ntopng with BPF filter for the internal network (see `-r` and `-d` options to avoid conflicts between the instances). The drawback is that you won't be able to get a unified view of both the internal and external traffic.

**Comment by pfruh** [comment]
Would be great to have a "nicer" way of splitting both in one instance - maybe it could be added in some later version.

**Comment by emanuele-f** [comment]
Thank you for the suggestion. I think traffic profiles are not very suitable for such a separation. Maybe we can just improve the local networks report. Have you specified the `--local-networks "192.168.0.0/16"` option in ntopng configuration?

**Comment by pfruh** [comment]
Yes, however our actual list of "local" (meaning in our control) networks is much larger and contains many public networks on top of the internal ones, so we extended the `--local-networks` with those, to easily see which hosts are under our control.

On top of that, use traffic profiles to separate the traffic of those between internal (free) and external (paid), since traffic between public IPs (even between our "local" Networks) is not free, only the traffic between internal IPs.

**Comment by koriks1111** [comment]
hello, 

im new in using ntop. may i know how can i filter, i want to monitor only external traffic, what is the command in nBPF format?

**Comment by simonemainardi** [comment]
traffic profiles already have a chart available which shows their traffic over time. For the time being, and also considered their overlap with traffic profiles, we believe that chart suffices.

![image](https://user-images.githubusercontent.com/3397663/53826713-9bdc2780-3f79-11e9-81ac-37589827463e.png)

**Comment by jult** [comment]
Is there an easy way to have ntopng entirely ignore ALL traffic from ip src 192.168.1.0/24 where destination is also 192.168.1.0/24 ?

> traffic profiles already have a chart available which shows their traffic over time. For the time being, and also considered their overlap with traffic profiles, we believe that chart suffices.
> 
> ![image](https://user-images.githubusercontent.com/3397663/53826713-9bdc2780-3f79-11e9-81ac-37589827463e.png)

How is this related to the question? We too would like a default filter option to show/capture only traffic from local to/from non-local. I was trying to set a profile like ip src/dst 192.168.1.0/24 & ip dst/src !192.168.1.0/24, but I don't see a config option for this.
