### ISSUE TITLE
fritzdump.sh tool: capture "wlan_guest" and "lan" at the same time

### ISSUE THREAD

**Issue by duffy6** [ntop/ntopng#1689]
Hi guys,

is it possible to capture "wlan_guest" and "lan" interface at the same time?
I want to capture ALL THE traffic in and out from/to my fritzbox.

Is this possible?

Regards
duffy6

**Comment by cardigliano** [comment]
It seems the Fritzbox doesn't have an aggregated interface for capturing traffic from both LAN and WLAN in a single stream.

**Comment by duffy6** [comment]
Okay, thx for your quick reply.
what interface do I have to use to capture wlan_guest traffic?
`"1-wlan_guest"` is not working :-(

**Comment by cardigliano** [comment]
Please go to http://<fritzbox>/html/capture.html and try with the listed interfaces (right click -> inspect on the "Start" button to get the "value" you should use).

**Comment by duffy6** [comment]
It says `"1-wlan_guest"` (see above), but this do not work :-(

EDIT: It is a Fritzbox 7490 (v06.93), if anyone is capable of investigating this any further.

**Comment by lucaderi** [comment]
@duffy6 This is a test tool we use for running experiments. If anyone is willing to extend it, please send us a pull request and we'll include it.

**Comment by duffy6** [comment]
Did anyone made it to capture the wlan_guest traffic on a Fritzbox 7490 V06.93?
