### ISSUE TITLE
Ntopng in a infinite loop when reading pcap from list

### ISSUE THREAD

**Issue by xder0991** [ntop/ntopng#169]
A text file (pcap.txt) was generated from a folder containing a lot of individual pcaps.
The text within the text file is structured as such:
/home/user/desktop/folder/a.pcap
/home/user/desktop/folder/b.pcap
/home/user/desktop/folder/c.pcap
....

i ran ntopng using the following command:
sudo ntopng --community -i pcap.txt

it is stuck after showing the line "Reading packets from pcap file /home/user/desktop/folder/a.pcap".
it never reaches the terminating state.

a run with the debug flag reveals that there were 2 address resolution error [-3/temporary failure in name resolution/success].

the debug file also reveals that after [Lua.cpp:2125] ntop_rrd_update(/var/tmp/ntopng/27/rrd/num_hosts.rrd) N decreases to 0, it appears to be in an infinite loop. several instances of this shows up towards the end of the debug file before i manually terminated the execution.

another peculiarity is when i manually terminate the execution via Ctrl+C, the entire list of pcap starts being printed on the console after the line "Shutting down..." was displayed on the console.
the program did not process these pcap files as [ProtoStats.cpp:35] showed only 7.29MB were processed (which is the size of the a.pcap) even though the folder had 10GB worth of pcaps.

there was no such problem if i were to execute the pcap file on its own, one by one.

i believe the address resolution is not the main issue, rather my hypothesis is that the program does not move on to the next file after it finishes with the first pcap.

i have tried both the stable (ntopng_2.0.150915-509) and nightly build (ntopng_2.0.150916-511) with no success.

please verify.

**Comment by kYroL01** [comment]
First of all, i don't understand this: **sudo ntopng --community -i pcap.txt**
Why you pass a .txt file to ntopng ? You have to pass only .pcap file.

**Comment by xder0991** [comment]
https://github.com/xtao/ntopng/blob/master/ntopng.8

perhaps you would like to take a look at this under the -i option

**Comment by kYroL01** [comment]
@xder0991 sorry, my misunderstanding. I'll investigate about this.
So you read only the first pcap that you specify, right ?

**Comment by lmangani** [comment]
Sorry for the invalid tag, corrected! My bad @xder0991

**Comment by xder0991** [comment]
yes that is correct. only the first pcap gets read after which none of the other pcaps in the list is read.
this issue does not happen if i go through each of the pcap one by one manually instead of using a list.
thank you =)
hope i did not come off as sounding offended.

**Comment by xder0991** [comment]
thank you for the fix.
do i recompile from source or just do a update using the nightly/stable repository?

**Comment by lucaderi** [comment]
Dev or source. In stable builds we just fix crashes or major things.
