### ISSUE TITLE
Use MySQL and ElasticSearch together, "all in one" nProbe Template?

### ISSUE THREAD

**Issue by pfruh** [ntop/ntopng#1690]
I'm trying to use MySQL and ElasticSearch together, since elasticsearch is not supported in the builtin "Historical Data Explorer".
I tried using the -F parameter twice in the config, it shows it's connecting to both in the log, but only seems to export to mysql and not to elasticsearch (when using only one -F with elasticsearch it works).

Can I get this to work somehow? And has someone maybe already made a nice dashboard for kibana? (since qbana seems dead)

Also, which template and netflow version should I use in nProbe to get all default data (for IPv4 and v6) populated for ntopng, mysql and elasticsearch (using it as sFlow collector)?

**Comment by simonemainardi** [comment]
Simultaneous export to MySQL and ElasticSearch is not supported yet. We are planning to create an ad-hoc high-performance flow store and we are directing our efforts to this activity. The new flow store will be integrated with the Historical Data Explorer.

However, as you are using ntopng in combination with nprobe, what you can do is let nProbe do the export to elasticsearch (export plugin is required) and ntopng to MySQL.

In nprobe you can use `@NTOPNG@` macro as the template value (`-T="@NTOPNG@"`) to have the minimum set of fields necessary to work with ntopng. The other fields depend on what specific information you would like to have visualized in ntopng. There is no wildcard as this would be highly detrimental for the performance. Therefore, you should carefully check all the nProbe fields available and add those that are meaningful for you.

**Comment by pfruh** [comment]
Thanks for the info, however since you said `@NTOPNG@` is a minimum set of fields for ntopng, I'd like to know which of the fields `nprobe -h` shows can even be correctly visualized by ntopng, so I don't send unnecessary fields to ntopng.

Edit: `src/ParserInterface.cpp` shows everything that can be parsed :)
