### ISSUE TITLE
Mysql/Pfsense

### ISSUE THREAD

**Issue by Derga127** [ntop/ntopng#1693]
Hello,
I installed ntopng on pfsense, I saw that ntopng can send the data history to a SQL database, did somebody set up ntopng on pfsense to send these data to another sql server.
Thank you

**Comment by lucaderi** [comment]
@MouadMimouni ntopng will create the table if necessary. We're not familiar with PFsense but I believe this is issue for them: what do you think @madpilot78  ?

**Comment by madpilot78** [comment]
A quick look at the pfsense ntopng port [1], which provides the configuration webUI, shows no parts to configure the MySQL logging functionality from there.

If you need that on a single system you could hack the ntopng_sync_package() function in ntopng.inc at [1], adding the required arguments at line 168.

To code more proper support via WebUI requires modifying the xml file to describe the proper widgets and adding validation and saving options to the inc file. If you have a clear idea of what you actually would like to allow configuring it should not be an overly complicated activity.

[1] https://github.com/pfsense/FreeBSD-ports/tree/devel/net/pfSense-pkg-ntopng/files/usr/local/pkg
