### ISSUE TITLE
[Lua.cpp:7239] WARNING: Script failure

### ISSUE THREAD

**Issue by duxenmx** [ntop/ntopng#1696]
Getting this error

11/Mar/2018 03:05:00 [Lua.cpp:7239] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/interface/minute.lua][/usr/local/share/ntopng/scripts/lua/modules/alert_utils.lua:2231: attempt to call field 'getHostPoolsStats' (a nil value)]

**Comment by emanuele-f** [comment]
Hi, what version of ntopng are you using (see `ntopng --version`)? Are you installing from a package or compiling it manually? Do you have the licensed version or free? If you have the free one, please add `--community` to your ntopng options

**Comment by duxenmx** [comment]
Heya,

Its version 3.3.180310
Compiled manually on an asus tinkerboard
Free version, and when I add the —community it says its an unrecognized
option

**Comment by simonemainardi** [comment]
@duxenmx try with `--community` and not with `—community` (note the dash)

**Comment by duxenmx** [comment]
Hey

Yeah, it was actually  - -community (without the space), ipad/iphone merges them together here when I type them, still having the same error with it, still getting a unrecognized option
![5acdc37f-74d4-45d8-9d9c-f033a17a9e31](https://user-images.githubusercontent.com/37263527/37326237-69102fc6-264e-11e8-82ec-727b65b25ead.png)

**Comment by emanuele-f** [comment]
Sorry, the `--community` switch is only available in licensed version. I've fixed the alert error, please check out the new version.
