### ISSUE TITLE
URLs from hosts

### ISSUE THREAD

**Issue by duffy6** [ntop/ntopng#1701]
Hi,

is it possible to show the urls from a specific host over a specific timeline?

Regards
duffy6

**Comment by emanuele-f** [comment]
Hi, you can do this by enabling the MySQL export and then perform queries via the "info" field. Please check out http://www.ntop.org/ntopng/exploring-historical-data-using-ntopng/ for more details.

Alternatively, you can enable realtime top sites for local hosts by enabling `Top HTTP Sites` in `Protocols` menu. A new tab `HTTP` will appear on local hosts.
