### ISSUE TITLE
NTOPNG Not Enough Memory 

### ISSUE THREAD

**Issue by kwunyinhui** [ntop/ntopng#1702]
Dears,

I would like to ask what is the system requirement for the NTOPNG?
However, the service seems unstable. It always prompt the error when we browsing or generating the report, and the error message said that it is not enough memory.

Environment:
ntopng Enterprise Edition v.3.3.180125
1 x Interface
1 x vCPU and 2G Memory

**Comment by emanuele-f** [comment]
Hi, can you update to the latest version (please check out your license expiration before this)? Can you post a screenshot of the page showing the error?

**Comment by simonemainardi** [comment]
I think 1 CPU with 2GB is OK only for limited network traffic. What is the network load you are trying to process? And how many local hosts you have? please post the ntopng configuration used.

Note that you can also tune, via the ntopng preferences, a 'Top-k Heuristic' to make the report aggregations more/less aggressive. In limited memory environments such as yours, you should put ti to aggressive

![image](https://user-images.githubusercontent.com/3397663/37513645-edc73a20-2905-11e8-8719-5b99102987ee.png)

**Comment by kwunyinhui** [comment]
This is the sample error message.

We have around 500 hosts concurrently. I think try to tune values. Thanks!

![sample](https://user-images.githubusercontent.com/37438134/37514112-e94e49cc-28fe-11e8-84ed-fba478db8b01.png)

**Comment by emanuele-f** [comment]
Closing the issue. Please reopen if necessary.
