### ISSUE TITLE
Debian Stretch - update-rc.d: error: initscript does not exist

### ISSUE THREAD

**Issue by merentitis** [ntop/ntopng#1704]
Debian Stretch (updated from Jessie)
I am using the following source:

`deb http://packages.ntop.org/apt-stable/stretch/ `

The installation log:

Preparing to unpack .../00-libcurl3_7.52.1-5+deb9u5_amd64.deb ...
Unpacking libcurl3:amd64 (7.52.1-5+deb9u5) ...
Selecting previously unselected package libhiredis0.13:amd64.
Preparing to unpack .../01-libhiredis0.13_0.13.3-2_amd64.deb ...
Unpacking libhiredis0.13:amd64 (0.13.3-2) ...
Selecting previously unselected package mysql-common.
Preparing to unpack .../02-mysql-common_5.8+1.0.2_all.deb ...
Unpacking mysql-common (5.8+1.0.2) ...
Selecting previously unselected package libmariadbclient18:amd64.
Preparing to unpack .../03-libmariadbclient18_10.1.26-0+deb9u1_amd64.deb ...
Unpacking libmariadbclient18:amd64 (10.1.26-0+deb9u1) ...
Selecting previously unselected package libpgm-5.2-0:amd64.
Preparing to unpack .../04-libpgm-5.2-0_5.2.122~dfsg-2_amd64.deb ...
Unpacking libpgm-5.2-0:amd64 (5.2.122~dfsg-2) ...
Selecting previously unselected package libsodium18:amd64.
Preparing to unpack .../05-libsodium18_1.0.11-2_amd64.deb ...
Unpacking libsodium18:amd64 (1.0.11-2) ...
Selecting previously unselected package libzmq5:amd64.
Preparing to unpack .../06-libzmq5_4.2.1-4_amd64.deb ...
Unpacking libzmq5:amd64 (4.2.1-4) ...
Selecting previously unselected package libjemalloc1.
Preparing to unpack .../07-libjemalloc1_3.6.0-9.1_amd64.deb ...
Unpacking libjemalloc1 (3.6.0-9.1) ...
Selecting previously unselected package redis-tools.
Preparing to unpack .../08-redis-tools_3%3a3.2.6-1_amd64.deb ...
Unpacking redis-tools (3:3.2.6-1) ...
Selecting previously unselected package redis-server.
Preparing to unpack .../09-redis-server_3%3a3.2.6-1_amd64.deb ...
Unpacking redis-server (3:3.2.6-1) ...
Selecting previously unselected package pfring.
Preparing to unpack .../10-pfring_7.0.0-1797_amd64.deb ...
Unpacking pfring (7.0.0-1797) ...
Selecting previously unselected package nprobe.
Preparing to unpack .../11-nprobe_8.2.180317-6003_amd64.deb ...
Unpacking nprobe (8.2.180317-6003) ...
Selecting previously unselected package pfring-dkms.
Preparing to unpack .../12-pfring-dkms_7.0.0_all.deb ...
Unpacking pfring-dkms (7.0.0) ...
Setting up libhiredis0.13:amd64 (0.13.3-2) ...
Setting up libpgm-5.2-0:amd64 (5.2.122~dfsg-2) ...
Setting up libjemalloc1 (3.6.0-9.1) ...
Setting up libcurl3:amd64 (7.52.1-5+deb9u5) ...
Setting up pfring (7.0.0-1797) ...
Adding the pf_ring startup script
update-rc.d: error: initscript does not exist: /etc/init.d/pf_ring
update-rc.d: error: initscript does not exist: /etc/init.d/cluster
/var/lib/dpkg/info/pfring.postinst: 37: /var/lib/dpkg/info/pfring.postinst: /etc/init.d/pf_ring: not found
Setting up mysql-common (5.8+1.0.2) ...
update-alternatives: using /etc/mysql/my.cnf.fallback to provide /etc/mysql/my.cnf (my.cnf) in auto mode
Setting up libmariadbclient18:amd64 (10.1.26-0+deb9u1) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up libsodium18:amd64 (1.0.11-2) ...
Setting up pfring-dkms (7.0.0) ...
Loading new pfring-7.0.0 DKMS files...
Building for 4.9.0-5-amd64 4.9.0-6-amd64
Building for architecture amd64
Building initial module for 4.9.0-5-amd64
Done.

pf_ring:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.9.0-5-amd64/updates/dkms/

depmod........

DKMS: install completed.
Building initial module for 4.9.0-6-amd64
Done.

pf_ring:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.9.0-6-amd64/updates/dkms/

depmod...

DKMS: install completed.
Setting up libzmq5:amd64 (4.2.1-4) ...
Setting up redis-tools (3:3.2.6-1) ...
Setting up redis-server (3:3.2.6-1) ...
Starting redis-server: redis-server.
Setting up nprobe (8.2.180317-6003) ...
Rebuilding ld cache...
Making the /var/log/nprobe directory...
(Re)Starting nprobe services...
update-rc.d: error: initscript does not exist: /etc/init.d/nprobe
dpkg: error processing package nprobe (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Errors were encountered while processing:
 nprobe
E: Sub-process /usr/bin/dpkg returned an error code (1)

**I t tried install systemd, but after trying to install nprobe I get other errors:**

Selecting previously unselected package libcurl3:amd64.
(Reading database ... 117673 files and directories currently installed.)
Preparing to unpack .../00-libcurl3_7.52.1-5+deb9u5_amd64.deb ...
Unpacking libcurl3:amd64 (7.52.1-5+deb9u5) ...
Selecting previously unselected package libhiredis0.13:amd64.
Preparing to unpack .../01-libhiredis0.13_0.13.3-2_amd64.deb ...
Unpacking libhiredis0.13:amd64 (0.13.3-2) ...
Selecting previously unselected package mysql-common.
Preparing to unpack .../02-mysql-common_5.8+1.0.2_all.deb ...
Unpacking mysql-common (5.8+1.0.2) ...
Selecting previously unselected package libmariadbclient18:amd64.
Preparing to unpack .../03-libmariadbclient18_10.1.26-0+deb9u1_amd64.deb ...
Unpacking libmariadbclient18:amd64 (10.1.26-0+deb9u1) ...
Selecting previously unselected package libpgm-5.2-0:amd64.
Preparing to unpack .../04-libpgm-5.2-0_5.2.122~dfsg-2_amd64.deb ...
Unpacking libpgm-5.2-0:amd64 (5.2.122~dfsg-2) ...
Selecting previously unselected package libsodium18:amd64.
Preparing to unpack .../05-libsodium18_1.0.11-2_amd64.deb ...
Unpacking libsodium18:amd64 (1.0.11-2) ...
Selecting previously unselected package libzmq5:amd64.
Preparing to unpack .../06-libzmq5_4.2.1-4_amd64.deb ...
Unpacking libzmq5:amd64 (4.2.1-4) ...
Selecting previously unselected package libjemalloc1.
Preparing to unpack .../07-libjemalloc1_3.6.0-9.1_amd64.deb ...
Unpacking libjemalloc1 (3.6.0-9.1) ...
Selecting previously unselected package redis-tools.
Preparing to unpack .../08-redis-tools_3%3a3.2.6-1_amd64.deb ...
Unpacking redis-tools (3:3.2.6-1) ...
Selecting previously unselected package redis-server.
Preparing to unpack .../09-redis-server_3%3a3.2.6-1_amd64.deb ...
Unpacking redis-server (3:3.2.6-1) ...
Selecting previously unselected package pfring.
Preparing to unpack .../10-pfring_7.0.0-1797_amd64.deb ...
Unpacking pfring (7.0.0-1797) ...
Selecting previously unselected package nprobe.
Preparing to unpack .../11-nprobe_8.2.180317-6003_amd64.deb ...
Unpacking nprobe (8.2.180317-6003) ...
Selecting previously unselected package pfring-dkms.
Preparing to unpack .../12-pfring-dkms_7.0.0_all.deb ...
Unpacking pfring-dkms (7.0.0) ...
Setting up libhiredis0.13:amd64 (0.13.3-2) ...
Setting up libpgm-5.2-0:amd64 (5.2.122~dfsg-2) ...
Setting up libjemalloc1 (3.6.0-9.1) ...
Setting up libcurl3:amd64 (7.52.1-5+deb9u5) ...
Setting up pfring (7.0.0-1797) ...
Adding the pf_ring startup script
Created symlink /etc/systemd/system/multi-user.target.wants/pf_ring.service → /etc/systemd/system/pf_ring.service.
Failed to restart pf_ring.service: No such method 'RestartUnit'
See system logs and 'systemctl status pf_ring.service' for details.
Setting up mysql-common (5.8+1.0.2) ...
update-alternatives: using /etc/mysql/my.cnf.fallback to provide /etc/mysql/my.cnf (my.cnf) in auto mode
Setting up libmariadbclient18:amd64 (10.1.26-0+deb9u1) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Processing triggers for systemd (232-25+deb9u2) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up libsodium18:amd64 (1.0.11-2) ...
Setting up pfring-dkms (7.0.0) ...
Loading new pfring-7.0.0 DKMS files...
Building for 4.9.0-5-amd64 4.9.0-6-amd64
Building for architecture amd64
Building initial module for 4.9.0-5-amd64
Done.

pf_ring:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.9.0-5-amd64/updates/dkms/

depmod......

DKMS: install completed.
Building initial module for 4.9.0-6-amd64
Done.

pf_ring:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.9.0-6-amd64/updates/dkms/

depmod...

DKMS: install completed.
Setting up libzmq5:amd64 (4.2.1-4) ...
Setting up redis-tools (3:3.2.6-1) ...
Setting up redis-server (3:3.2.6-1) ...
Created symlink /etc/systemd/system/redis.service → /lib/systemd/system/redis-server.service.
Created symlink /etc/systemd/system/multi-user.target.wants/redis-server.service → /lib/systemd/system/redis-server.service.
Starting redis-server: redis-server.
Setting up nprobe (8.2.180317-6003) ...
Rebuilding ld cache...
Making the /var/log/nprobe directory...
(Re)Starting nprobe services...
Failed to execute operation: No such method 'ResetFailed'
dpkg: error processing package nprobe (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Processing triggers for systemd (232-25+deb9u2) ...
Errors were encountered while processing:
 nprobe
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by emanuele-f** [comment]
This is probably a system configuration problem. Systemd should already be shipped with debian, no need to install it manually. Please retry with a clean install.

**Comment by merentitis** [comment]
An install to a clean debian stretch completes fine. 
The system I mentioned above though is a jessie not tweaked in any way, no packages and services removed, only upgraded to debian stretch following the debian procedures. I had no problems with installing any other packages.

**Comment by emanuele-f** [comment]
So this is definetely caused by an upgrade issue. You shouldn't  install systemd by yourself. The post https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=830722 suggests to run `apt-get install systemd-sysv`, maybe it can help you.
