### ISSUE TITLE
ntopng mysql storage wrong columns

### ISSUE THREAD

**Issue by plus-24** [ntop/ntopng#1705]
CentOS Linux release 7.4.1708
ntopng installation by your official repository
ntopng.x86_64                          3.2.180317-3702                @ntop
mariadb by centos repo
mariadb.x86_64                         1:5.5.56-2.el7                 @base
mariadb-devel.x86_64                   1:5.5.56-2.el7                 @base
mariadb-libs.x86_64                    1:5.5.56-2.el7                 @anaconda
mariadb-server.x86_64                  1:5.5.56-2.el7                 @base

ntopng.conf
-F="mysql;localhost;ntopng;flows;user;password"

errors:
ntopng: [MySQLDB.cpp:56] ERROR: MySQL error: Unknown column 'IN_BYTES' in 'field list' [rc=-1]
ntopng: [MySQLDB.cpp:56] ERROR: MySQL error: Unknown column 'OUT_BYTES' in 'field list' [rc=-1]
ntopng: [MySQLDB.cpp:56] ERROR: MySQL error: Unknown column 'INTERFACE_ID' in 'field list' [rc=-1]

problems:
ntopng create BYTES not IN_BYTES
create INTERFACE not INTERFACE_ID
OUT_BYTES missing

my solution:
ALTER TABLE ntopng.flowsv4 CHANGE BYTES IN_BYTES int(10) unsigned NULL;
ALTER TABLE ntopng.flowsv6 CHANGE BYTES IN_BYTES int(10) unsigned NULL;
ALTER TABLE ntopng.flowsv4 ADD OUT_BYTES INT NULL;
ALTER TABLE ntopng.flowsv6 ADD OUT_BYTES INT NULL;
ALTER TABLE ntopng.flowsv4 CHANGE INTERFACE INTERFACE_ID varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL ;
ALTER TABLE ntopng.flowsv6 CHANGE INTERFACE INTERFACE_ID varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL ;

do you confirm my problem by program error or is my mistake?
Thanks

**Comment by emanuele-f** [comment]
That is weird, we already perform such alter tables:

https://github.com/ntop/ntopng/blob/3.2-stable/src/MySQLDB.cpp#L321
https://github.com/ntop/ntopng/blob/3.2-stable/src/MySQLDB.cpp#L257

@simonemainardi any idea?

**Comment by plus-24** [comment]
Test on other centos 7with these releases:
ntopng.x86_64                          3.2.180314-3702                @ntop
ntopng-data.noarch                     3.2.180314-3702                @ntop-noarch

ntopng runtime status show:
26/Mar/2018 17:10:06 [MySQLDB.cpp:370] MySQL schema update. Altering table flowsv6: changing the number of partitions to 8.
26/Mar/2018 17:10:06 [MySQLDB.cpp:370] MySQL schema update. Altering table flowsv4: changing the number of partitions to 8.
26/Mar/2018 17:10:06 [MySQLDB.cpp:344] MySQL schema update. Altering table flowsv6: changing engine from InnoDB to MyISAM.
26/Mar/2018 17:10:06 [MySQLDB.cpp:344] MySQL schema update. Altering table flowsv4: changing engine from InnoDB to MyISAM.
26/Mar/2018 17:10:06 [MySQLDB.cpp:316] MySQL schema update. Altering table flowsv6: renaming BYTES to IN_BYTES and adding OUT_BYTES
26/Mar/2018 17:10:06 [MySQLDB.cpp:316] MySQL schema update. Altering table flowsv4: renaming BYTES to IN_BYTES and adding OUT_BYTES

but not any changes on db

upgraded to:
ntopng.x86_64                          3.2.180326-3702                @ntop
ntopng-data.noarch                     3.2.180326-3702                @ntop-noarch

and now runtime show errors
26/Mar/2018 17:15:26 [MySQLDB.cpp:57] ERROR: INSERT INTO `flowsv4` (VLAN_ID,L7_PROTO,IP_SRC_ADDR,L4_SRC_PORT,IP_DST_ADDR,L4_DST_PORT,PROTOCOL,IN_BYTES,OUT_BYTES,PACKETS,FIRST_SWITCHED,LAST_SWITCHED,INFO,JSON,NTOPNG_INSTANCE_NAME,INTERFACE_ID,PROFILE) VALUES ('0','0','168019477','50206','1427198085','80','6','246','186','7','1522077314','1522077320','',COMPRESS('{ "8": "10.3.198.21", "12": "85.17.80.133", "7": 50206, "11": 80, "4": 6, "6": 19, "2": 4, "1": 246, "24": 3, "23": 186, "22": 1522077314, "21": 1522077320, "57595": 0.151000, "57596": 11.388000, "SRC_IP_COUNTRY": "", "SRC_IP_LOCATION": [ 0.000000, 0.000000 ], "DST_IP_COUNTRY": "NL", "DST_IP_LOCATION": [ 5.840900, 51.914398 ], "NTOPNG_INSTANCE_NAME": "monitor1.teorema.local", "INTERFACE": "enp2s0f1" }'), 'monitor1.teorema.local', '0','')
26/Mar/2018 17:15:26 [MySQLDB.cpp:56] ERROR: MySQL error: Unknown column 'IN_BYTES' in 'field list' [rc=-1]

**Comment by plus-24** [comment]
sorry my mistake
the user doesn't have rights to alter db
thank you for your precious time

**Comment by emanuele-f** [comment]
Thank you for reporting!
