### ISSUE TITLE
Chart option not working for many networks

### ISSUE THREAD

**Issue by csammons0x1c** [ntop/ntopng#1707]
I am running the Community Edition v3.3.180314.

I have various subnets specified using the startup option --local-networks. When I navigate to Hosts > Networks and click the chart icon for most of these networks, I get the error "No available stats for network x.x.x.x/mask". Other display as expected and some open an empty chart. I've verified that these networks have seen recent traffic. I also know that this feature worked as expected in the 3.3.180110 deployment. I'm not seeing any error in the logs for this nor any javascript errors in the console when clicking the icon.

**Comment by emanuele-f** [comment]
Hi, please update to the today version of ntopng and see if you still reproduce the issue. Can you navigate `/var/tmp/ntopng/0/subnetstat` where `0` is your network interface id (from the interface page into the ntopng gui) and see if the rrds are acually there?
For example, in my case I see `/var/tmp/ntopng/0/subnetstats/192/168/100/0/24/bytes.rrd`. If they exists, then please run `rrdtool info your_rrd_path_here | grep last_update` to get the timestamp of last update.

**Comment by csammons0x1c** [comment]
Thank you for the response.

Looking in the directory you specified I noticed that the networks that are
not producing the graphs do not have a corresponding directory nor rrd
files. The subnets that are working however, do have these.

I've updated to Community Edition v3.3.180320 as suggested and am still
seeing the same result. From one of the networks that is working I get the
following from 'rrdtool info' output.

# rrdtool info ./bytes.rrd | grep last_update
last_update = 1521558001

**Comment by emanuele-f** [comment]
What ntopng options are you using? Can you post your ntopng log?

**Comment by csammons0x1c** [comment]
I use the following startup options:

`ntopng --daemon "" --pid "/var/run/ntopng/ntopng.pid" --http-port "0" --https-port "3001" --local-networks "<LIST_OF_NETWORKS_HERE>"`

My logs contain the following. Please let me know if you need me to start ntopng with more verbose log settings than the default setting reflected here:

```
13/Mar/2018 11:21:53 [Redis.cpp:116] Successfully connected to redis 127.0.0.1:6379@0
13/Mar/2018 11:21:53 [Redis.cpp:116] Successfully connected to redis 127.0.0.1:6379@0
13/Mar/2018 11:21:53 [Ntop.cpp:1429] Parent process is exiting (this is normal)
14/Mar/2018 09:41:52 [Ntop.cpp:1502] Setting local networks to <LIST_OF_NETWORKS_HERE>
14/Mar/2018 09:41:52 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
14/Mar/2018 09:41:52 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
14/Mar/2018 09:41:52 [Ntop.cpp:1439] Parent process is exiting (this is normal)
14/Mar/2018 10:29:21 [Ntop.cpp:1502] Setting local networks to <LIST_OF_NETWORKS_HERE>
14/Mar/2018 10:29:21 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
14/Mar/2018 10:29:21 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
14/Mar/2018 10:29:21 [Ntop.cpp:1439] Parent process is exiting (this is normal)
14/Mar/2018 11:08:23 [Ntop.cpp:1502] Setting local networks to <LIST_OF_NETWORKS_HERE>
14/Mar/2018 11:08:23 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
14/Mar/2018 11:08:23 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
14/Mar/2018 11:08:23 [Ntop.cpp:1439] Parent process is exiting (this is normal)
20/Mar/2018 09:53:09 [Ntop.cpp:1502] Setting local networks to <LIST_OF_NETWORKS_HERE>
20/Mar/2018 09:53:09 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
20/Mar/2018 09:53:09 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
20/Mar/2018 09:53:09 [Ntop.cpp:1439] Parent process is exiting (this is normal)
```

**Comment by emanuele-f** [comment]
How many local hosts/local networks/flows do you have?

**Comment by csammons0x1c** [comment]
Roughly 500+ local hosts, 36 local networks defined and 7500 flows.

**Comment by emanuele-f** [comment]
Have you enabled the `Create Interface Timeseries` into every interface? The option is available into the interfaces config (cog icon) page. Do you have free space on disk? Moreover, if you only specify one network (the one which is not creating the file) and wait 2 minutes, can you see the network charts correctly populating?

**Comment by csammons0x1c** [comment]
Yes, `Create Interface Timeseries` is enabled for each interface. The output of the `df -h` command shows 86% of the partition free. I attempted to start ntopng with only a single network specified (that wasn't previously charting) with the `--local-networks` flag, waited 2+ minutes and still haven't seen the the rrd files created for that network.

**Comment by emanuele-f** [comment]
Can you provide web access to you gui? Please send me credentials at faranda@ntop.org

**Comment by emanuele-f** [comment]
@csammons0x1c can you post/send me your ntopng configuration along with some screenshots of your networks list page and the details page of a network which isn't working correctly?

**Comment by csammons0x1c** [comment]
My ntopng configuration is below.
```
# cat ntopng.conf
--daemon
--pid=/var/run/ntopng/ntopng.pid
--use-syslog
--http-port 0
--https-port 3001
--local-networks <LIST_OF_NETWORKS_HERE>
```
Here is a screenshot of my network stats page:

![image](https://user-images.githubusercontent.com/37349041/38633727-2633b976-3d86-11e8-9f30-d244f980272c.png)
![image](https://user-images.githubusercontent.com/37349041/38634091-283abe4e-3d87-11e8-8100-665a32ff7dbb.png)

If I click on the graph icon for the 10.x.x.0/24 in the above image I get the following error:

![image](https://user-images.githubusercontent.com/37349041/38634838-4e80810e-3d89-11e8-955c-b23a3e9eb80c.png)

Some of the other networks will show an empty graph as follows:

![image](https://user-images.githubusercontent.com/37349041/38634652-cd2ed5ec-3d88-11e8-948e-286c8e18070f.png)

**Comment by emanuele-f** [comment]
@csammons0x1c sorry for the delay, can you check out the new ntopng version and see i you still reproduce the issue/see anything usefull in the log?

**Comment by csammons0x1c** [comment]
@emanuele-f  I've update to Community Edition v.3.5.180426 as suggested and so far all of the charts in my networks list are working! Thanks for your help with this! I'm a huge fan of the application.

**Comment by emanuele-f** [comment]
Perfect! Thank you :)
