### ISSUE TITLE
error in ntopng: double free or coruption (fasttop)

### ISSUE THREAD

**Issue by xder0991** [ntop/ntopng#171]
Scenario:
I have ntopng read in a huge list of pcap files using the command "sudo ntopng --community -i pcap.txt"
list of pcap files add up to a total of 10GB
After ntopng reaches the line "No more pcap files to read", i proceeded to check the analysis on the web portal.
I then left it unattended as i went for lunch.
2 hours later, i return to find that ntopng has crashed with the following line printed on the console
***Error in `ntopng' : double free or corruption (fasttop) : 0x00007fe440409440***

Environment:
Virtual Machine setup running Ubuntu 14.04 LTS, 4GB RAM, 100GB HDD.

requesting for diagnosis if it is possible.
Thank you.

**Comment by lucaderi** [comment]
@xder0991 Hi can you please put somewhere (dropbox?) both the ntopng binary and the coredump? This would allow us to analyse the problem.

**Comment by xder0991** [comment]
i tried replicating the issue but unfortunately i can't seem to get that
same error again.
it might be a one-off thing or simply an extreme corner case that is
difficult to replicate because i don't know how it triggered in the first
place.
the program has been running for the past 2-3 days with no such crashes
observed.

**Comment by lucaderi** [comment]
Ok so I close this bug and we'll open it again if you are able to reproduce the problem. Thank you.
