### ISSUE TITLE
Recommended values

### ISSUE THREAD

**Issue by TravisH84** [ntop/ntopng#1710]
Apologies if this is a simple question, but do you have a table of recommended thresholds for the ntopng tool.  I see you can set the thresholds for an interface, but not 100% sure what would be typical threshold values for a home network with 100 mb/s link.

I saw the setup tool, but not what recommended values actually were, or how to calculate these?

**Comment by emanuele-f** [comment]
Do you refer to the alert settings? Sorry but we do not have recommended values for such a network, this would require manual test to figure out.
