### ISSUE TITLE
TCP Keep-Alive is treated as TCP re-transmissions 

### ISSUE THREAD

**Issue by tomerr-tradair** [ntop/ntopng#1711]
We have noticed that the TCP Re transmissions counter is increasing on every TCP Keep-Alive packet.
Any thoughts?

**Comment by emanuele-f** [comment]
Hi do you have a pcap to reproduce?
Keep-Alive explanation: http://www.cceye.com/tcp-keep-alive

**Comment by tomerr-tradair** [comment]
Attached a capture with some SSL traffic and 1 tcp-keepalive we saw the issue with.
[tcp-keepalive.zip](https://github.com/ntop/ntopng/files/1837213/tcp-keepalive.zip)

**Comment by emanuele-f** [comment]
Here is a stripped version with only the flow of interest. Ntopng incorrectly reports a lost packet in this case. So there is actually a problem with the handling of keep-alive packets. Let's see what @lucaderi and @simonemainardi suggest about this.

[keep_alive.zip](https://github.com/ntop/ntopng/files/1842420/keep_alive.zip)

![screenshot](https://user-images.githubusercontent.com/5488003/37840237-cb658f24-2ebc-11e8-845a-8d48785edb59.png)

**Comment by tomerr-tradair** [comment]
Hi, any chance to get this fixed soon?

**Comment by simonemainardi** [comment]
keepalive stats are implemented and available in the latest dev. Flows and Hosts now have a counter for keepalive packets that are no longer categorized as lost.

![image](https://user-images.githubusercontent.com/3397663/38144024-644500d6-3443-11e8-89c2-6d3c0b561926.png)

![image](https://user-images.githubusercontent.com/3397663/38144090-b31d012c-3443-11e8-88d3-68f742b6de86.png)
