### ISSUE TITLE
Grafana Plugin

### ISSUE THREAD

**Issue by darox** [ntop/ntopng#1712]
I'm running the latest version of Ntopng on a Ubuntu 16.04 server and wanted to setup the ntopng grafana plugin according to this manual: https://www.ntop.org/ntopng/ntopng-grafana-integration-the-beauty-of-data-visualizazion/
But it seems like this is not working anymore. The plugin seems to be missing on the Ntopng side resulting in: Page "/lua/modules/grafana." was not found

Anyone also recognized that?

**Comment by emanuele-f** [comment]
Maybe the URL is `/lua/modules/grafana/index.lua` ?

**Comment by darox** [comment]
Unfortuantely not, there's nothing from grafana at all.. :(

**Comment by zxyz** [comment]
Hello, I'm running ntopng 3.2.180407 (installed from epel) on centos 7 and I have the same problem (page not found). Adding `index.lua` results in `{"status": "OK"}` being displayed in a browser, but still an error in grafana.

**Comment by simonemainardi** [comment]
tested both with grafana 4.x and 5.x. Works as expected. Make sure to have a trailing slash at the end of the URL, `http://devel:3001/lua/modules/grafana/`

![image](https://user-images.githubusercontent.com/3397663/38609441-6270681a-3d7e-11e8-83bb-25f6aaf0bc27.png)

![image](https://user-images.githubusercontent.com/3397663/38616983-13f52ffa-3d96-11e8-9875-38d87bc8ceda.png)

**Comment by darox** [comment]
@simonemainardi Which version of ntopng on which system?

**Comment by simonemainardi** [comment]
```
v.3.3.180410	[Enterprise/Professional build]
GIT rev:	dev:e0a2aa8088b5b6e8f975aa5df35aa0b1d8b51238:20180410
Pro rev:	r1560
Built on:	CentOS Linux release 7.4.1708 (Core)
```

and
```
v.3.3.180405	[Enterprise/Professional build]
GIT rev:	dev:2bc61142fa98b572d73eeb65df770c2ba22f5a3b:20180405
Pro rev:	r1553
Built on:	Ubuntu 16.04.4 LTS
```

**Comment by darox** [comment]
I finally got it working on Pfsense and Ubuntu, it looks like Grafana was the problem. On Pfsense the access type within the settings in grafana has to be direct, for Ubuntu it's proxy. Somehow strange. I should also be noted, that some settings within ntopng has to be changed, to show all data in Grafana. 
![bildschirmfoto 2018-04-11 um 18 12 54](https://user-images.githubusercontent.com/9934402/38629461-613ce1b8-3db4-11e8-952e-d944f5ae0aa5.png)

From my side, it can be closed!

**Comment by simonemainardi** [comment]
Thanks for reporting!

By the way, I love your dashboard! Are you interested in trying and contribute it to the community?

**Comment by darox** [comment]
@simonemainardi Yes, I'll share the json. It's mainly consisting of telegraf data and various input plugins + Speeed Test CLI input. 

Btw. are there any plans to add aditional metrics from ntopng? Like top hosts and things like that. Ntopng is great, but I would like to have anything in grafana.

**Comment by zxyz** [comment]
the hint from @darox helped me: using `proxy` instead of `direct` solved the problem  -- whysoever.
more data from ntopng in grafana would be great! With the influxdb support which is, afaik, scheduled for the 3.4 release, this wish might be fullfilled :)

thanks @simonemainardi for the support!

**Comment by darox** [comment]
@zxyz That would be great, if influxdb input support is coming in ntopng 3.4, what's the eta for that?

**Comment by lucaderi** [comment]
Influx and prometeus support are in alpha and they will be part of the next 3.5.x series. The code is already in https://github.com/ntop/ntopng/blob/dev/src/TimeSeriesExporter.cpp but *no support will be provided until that release*.

**Comment by darox** [comment]
@lucaderi Damn amazing, I have to dig into this. Will defintely setup a staging environment for this.

EDIT: Whats the timeplan for 3.5?

**Comment by emanuele-f** [comment]
@darox you can place the json under contrib directory and provide a pull request so that it will be available to other users and credits will be yours.

3.5 should be available in Q4 2018.

**Comment by darox** [comment]
I've recognized another strange issue. The NTOPNG data source seems not working on my smart phone, but on the computer it's working just fine. The other data sources like influxdb are fine on pc and smartphone. Shall I open another issue?

**Comment by emanuele-f** [comment]
Please open a separate issue. Please test it with some standard json (e.g. with only one chart).

**Comment by darox** [comment]
@emanuele-f Made two pull requests, because I've created two seperate dashboards even with screenshots ;)

PS: Looking forward to the influxdb support.

**Comment by emanuele-f** [comment]
Great! Thank you!
