### ISSUE TITLE
Into the syslog messages add host information in the HREF items to allow 3rd party to access 

### ISSUE THREAD

**Issue by adargenio** [ntop/ntopng#1714]
Would be possible to add into the syslog message like these:

Mar 19 08:15:12 monit ntopng: [Alert] Flow emitted during alerted interface:  HREF='<B>http://ntopng.myserver.com:3000</B>/lua/host_details.lua?host=192.168.20.34&ifid=2&page=alerts'>192.168.20.34 &gt; HREF='<B>http://ntopng.myserver.com:3000</B>/lua/host_details.lua?host=39.41.215.66&ifid=2&page=alerts'>39.41.215.66 [TCP 192.168.20.34:64479 &gt; 39.41.215.66:445 [proto: 0.16/SMB][device: 3232240686 in: 7 out:8][1/0 pkts][52/0 bytes][SYN]]

the full host URL to allow the use outside the NTOPNG web interface. A custom field (not calculated) would be really apprecciated.

**Comment by emanuele-f** [comment]
Maybe it's better to remove the html in syslog at all...

**Comment by adargenio** [comment]
Hi Emanuele,
this would be needed because we send alert emails using the rsyslog engine. In that the string is sent as mail and would be useful for the recipient to quick link the alarm into the web interface.

**Comment by emanuele-f** [comment]
Email notification is another thing, with the new ntopng you can send emails on new alerts. Currently we have stripped the URL on emails but it's probably better to insert proper url

**Comment by simonemainardi** [comment]
We believe custom urls should not be added to syslog messages.

First, a lot of space would be taken in every message for a url that is constant and never changes. Second, custom urls should be handed when post-processing the syslog or even in the GUI right before presenting the alerts to the end user. Indeed, by receiving a stream of syslog events, the source is automatically determined and that can be used to identify a proper server URL.

Please, refer to https://github.com/ntop/ntopng/issues/1973 to see the lastest improvements to the syslog.
