### ISSUE TITLE
Alerts generation toggle causes unexpected behaviors

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#1715]
where there are alerts engaged as

![image](https://user-images.githubusercontent.com/3397663/37957127-796e4622-31ad-11e8-99bb-db15a8e5166d.png)

toggling them off using the preference switch is ineffective:
![image](https://user-images.githubusercontent.com/3397663/37957170-8ef2c72a-31ad-11e8-9a49-0247e77c2606.png)

the badge in the footer is hidden but:

1. all the engaged alerts re-appear immediately after turning the toggle back on
![image](https://user-images.githubusercontent.com/3397663/37957309-e7042314-31ad-11e8-8b02-a60328d7b5d5.png)

2. host alerts counters are always shown even when the toggle is off
![image](https://user-images.githubusercontent.com/3397663/37957512-6ee1f8ec-31ae-11e8-9784-c5e71a0a8365.png)

3. host alerts counters shown are sometimes wrapped
```
27/Mar/2018 10:59:23 [AlertsManager.cpp:945] ERROR: Internal error, negative engaged alerts counter detected [host: 37.60.32.1@0].
27/Mar/2018 10:59:24 [AlertsManager.cpp:945] ERROR: Internal error, negative engaged alerts counter detected [host: 37.60.35.41@0].
```
![image](https://user-images.githubusercontent.com/3397663/37957339-fc1d2c78-31ad-11e8-948a-0729b0dc79e9.png)

4. a red triangle keeps appearing in the dashboard and in the hosts list even when the toggle is off.

**Comment by emanuele-f** [comment]
Fixed in 89cb18d29c15f200ee7d2f0b3a68cf5b4b1e8672
