### ISSUE TITLE
ZC mode on ubuntu/debian box

### ISSUE THREAD

**Issue by malvivent7** [ntop/ntopng#1718]
I have enabled zc for my capturing interface on ntopng but i'm completely stuck on starting ntopng in zc mode; my ntopng.conf is below:
-x=600000
-X=600000
-w=3000
-W=0
-g=-1
-m="192.168...."
-d=/storage/ntopng
-G=/var/run/ntopng.pid
-i=zc:eno1
-U=nobody
--community

i have also checked with this command my interfaces:
cat /proc/net/pf_ring/dev/eno1/info
Name:         eno1
Index:        2
Address:      00:1E:67:50:22:0A
Polling Mode: NAPI
Type:         Ethernet
Family:       Standard NIC
# Bound Sockets:  0
TX Queues:    8
RX Queues:    8
 this is the interface on which macaddress i have installed lic
 when i start ntopng with this command:
systemctl start ntopng
i receive this message
mar 27 18:22:05 ntopng ntopng[162874]: 27/Mar/2018 18:22:05 [main.cpp:237] ERROR: An exception occurred during interface creation: zc:eno1
mar 27 18:22:05 ntopng ntopng[162874]: 27/Mar/2018 18:22:05 [main.cpp:287] ERROR: Startup error: missing super-user privileges ?
mar 27 18:22:05 ntopng ntopng[162874]: [main.cpp:237] ERROR: An exception occurred during interface creation: zc:eno1
mar 27 18:22:05 ntopng ntopng[162874]: [main.cpp:287] ERROR: Startup error: missing super-user privileges ?
and ntopng want start.
Where i'm working wrong? Thanks in advance on helping me.

**Comment by lucaderi** [comment]
@malvivent7 Have you loaded the ZC driver? I don't think so looking at the /proc output. Please see http://www.ntop.org/guides/pf_ring/zc.html
