### ISSUE TITLE
wrong Actual Thpt when im downloading files

### ISSUE THREAD

**Issue by AlekMarkus** [ntop/ntopng#172]
i have updated ntopng to last version : ntopng Professional v.2.0.150915

i started to copying 4 gb File to my desktop, and  i was looking at ntopng Flows

i can see that at Flows the speed is : 360 Kbit.

but at my transfer window i can see 1.00 MB/Second , is this a bug ?

1.
![calc](https://cloud.githubusercontent.com/assets/13960741/9927381/df4d8e8e-5d26-11e5-9a70-e717be55a5b7.png)

2.
![calculation](https://cloud.githubusercontent.com/assets/13960741/9927413/12b770aa-5d27-11e5-86fe-1fa4974819b0.png)

**Comment by ValentinaViscarelli** [comment]
Please when you check the difference between ntopng GUI and window download, you have to considerate a couple of things:

1) the value that you see in ntopng gui is an average value (bits received / 5 seconds). The value in windows download is almost instantaneous and could be a high peak or low peak.
2) the value in ntopng is in bits/sec instead the value in window download should be in bytes/sec.

Considering this two things I did some tests and it should be ok.

We also have changed some divisions so if want to test again, please update the code.
