### ISSUE TITLE
Implement Limited Information Access

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1720]
Privacy and GDPR demand limited information access. It is requested to implement top talkers in terms of sessions/pps/bw without allowing that role to see specifically what things someone is doing for privacy reasons (i.e. no external IPs, just ASs/traffic type/DPIetc)

**Comment by simonemainardi** [comment]
Using the latest multi tenant ntopng 5.0+ we believe we have reached enough granularity to control what user can and cannot see.

Indeed, a non-privileged user can:

- See only an interface
- See a subset of networks for a specific interface
- A combination of both

This also holds for alerts. Moreover, we have implemented capabilities _a la_ linux in `auth.lua` that can allow an even finer grained control.

This post explains in detail how to limit information access https://www.ntop.org/nprobe/howto-monitor-customer-traffic-in-managed-service-providers-and-isps/

The use case is ISPs and MSPs that want to monitor customers' traffic and let customers access their data.
