### ISSUE TITLE
Unable to add pro license to ntopng on pfsense

### ISSUE THREAD

**Issue by KD22110** [ntop/ntopng#1722]
When I go into About, under License it only shows License  GNU GPLv3

Info such as...
EULA [ SystemId: XXXXXXXXXXXXXXXXX  ] 
Click on the above URL to generate your professional version license, or 
purchase a license at e-shop. If you are no-profit, research or an education
institution please read this.
"
...is completely missing as is the field to enter the license.

**Comment by emanuele-f** [comment]
Do you already have a demo license installed? If so, please add the `--community` option, insert the new license, and then remote the `--community`.

**Comment by simonemainardi** [comment]
ntopng on pfsense is purely opensource and does not contain any commercially-licensed part. If you are interested in getting a pro/enterprise, please refer to http://packages.ntop.org  that lists the supported OSes and corresponding binary packages.
