### ISSUE TITLE
Enable Flow Alerts generates a huge amount of alerts

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#1723]
The `Enable Flow Alerts` option, when enabled and interface is alerted, generates a huge amount of alerts of type interface_alerted, one for every flow. A casual user may enable all the alert switches just to try what they do, and this would result the described explosion of alerts.

Maybe we should remove such an alert?

**Comment by lucaderi** [comment]
Please disable "flow emitted while interface alerted" as this is probably the cause of the issue.
