### ISSUE TITLE
Ntopng Embedded Edition v.3.3.180131 not reporting traffic properly

### ISSUE THREAD

**Issue by error420** [ntop/ntopng#1727]
Ntopng seems to pick up all my local devices but the flow is completely wrong. Running  version 3.3.180131 on Raspberry Pi 3. I have been streaming all day and the max traffic it picks up is 35MB total. My router DDWRT shows over 31 Mbps constantly going out yet Ntopng shows zero bps and a lot of upload traffic. The most noisy traffic on the network are the ntopng server (raspberry pi) and the machine viewing the web console at the time(my pc, macbook etc).

https://ibb.co/kYRXn7

**Comment by emanuele-f** [comment]
Hi, probably your raspberry pi does not have visibility on your whole network traffic, but only on its own traffic. In a home network, you can easily achieve visibility in one of the following ways:

- ARP spoof the router IP with the raspberry mac address
- By setting the DHCP gateway option to your raspberry IP address

Please note that the ideal way would be to put the raspberry in bridge mode between your wireless ap and the internet gateway but in your case they are the same device so you would need an additional external ap. See https://github.com/ntop/ntopng/blob/dev/doc/README.inline

**Comment by error420** [comment]
Ok thank you. Ordered a USB nic for the PI to try bridge mode. I'm excited to see the results.

**Comment by emanuele-f** [comment]
Right choice!
