### ISSUE TITLE
Unable to compile from GIT on OpenBSD

### ISSUE THREAD

**Issue by JasonMarkowitz** [ntop/ntopng#1728]
OS: Openbsd 6.1

```
src/Utils.cpp: In static member function 'static bool Utils::isPrintableChar(u_char)':
src/Utils.cpp:877: warning: comparison is always true due to limited range of data type
src/Utils.cpp: In static member function 'static int Utils::bindSockToDevice(int, int, const char*)':
src/Utils.cpp:2624: error: 'getifaddrs' was not declared in this scope
src/Utils.cpp:2631: error: invalid use of incomplete type 'struct ifaddrs'
src/Utils.cpp:2619: error: forward declaration of 'struct ifaddrs'
src/Utils.cpp:2631: error: invalid use of incomplete type 'struct ifaddrs'
src/Utils.cpp:2619: error: forward declaration of 'struct ifaddrs'
src/Utils.cpp:2631: error: invalid use of incomplete type 'struct ifaddrs'
src/Utils.cpp:2619: error: forward declaration of 'struct ifaddrs'
src/Utils.cpp:2632: error: invalid use of incomplete type 'struct ifaddrs'
src/Utils.cpp:2619: error: forward declaration of 'struct ifaddrs'
src/Utils.cpp:2638: error: invalid use of incomplete type 'struct ifaddrs'
src/Utils.cpp:2619: error: forward declaration of 'struct ifaddrs'
src/Utils.cpp:2643: error: invalid use of incomplete type 'struct ifaddrs'
src/Utils.cpp:2619: error: forward declaration of 'struct ifaddrs'
src/Utils.cpp:2646: error: 'freeifaddrs' was not declared in this scope
gmake: *** [Makefile:157: src/Utils.o] Error 1 
```

**Comment by emanuele-f** [comment]
Hi, I've committed a fix to include ifaddrs.h 9889c291ccf3c8a7f8b3408a4e8bdfdb4e958517 . Can you retry compilation?

**Comment by JasonMarkowitz** [comment]
Compilation succeeds there but fails on a subsequent step:
`
g++  src/SNMP.o  src/Ntop.o  src/nDPIStats.o  src/ProtoStats.o  src/HTTPBL.o  src/AddressList.o  src/ThreadedActivity.o  src/DivertInterface.o  src/Checkpointable.o  src/Lua.o  src/VirtualHostHash.o  src/NetworkDiscovery.o  src/AddressTree.o  src/NetworkInterface.o  src/FrequentNumericItems.o  src/RwLock.o  src/HostPools.o  src/GenericTrafficElement.o  src/Flow.o  src/Vlan.o  src/ZCCollectorInterface.o  src/Country.o  src/EthStats.o  src/Trace.o  src/TimeSeriesExporter.o  src/AlertsManager.o  src/Mac.o  src/Host.o  src/AlertCounter.o  src/ElasticSearch.o  src/Utils.o  src/PcapInterface.o  src/FrequentTrafficItems.o  src/ParserInterface.o  src/PacketStats.o  src/GenericHashEntry.o  src/Paginator.o  src/DnsStats.o  src/VirtualHost.o  src/Logstash.o  src/FrequentStringItems.o  src/ICMPstats.o  src/PacketDumperTuntap.o  src/AddressResolution.o  src/main.o  src/HTTPserver.o  src/NetworkStats.o  src/Prefs.o  src/VlanAddressTree.o  src/MacManufacturers.o  src/Mutex.o  src/ExportInterface.o  src/Redis.o  src/TcpFlowStats.o  src/Grouper.o  src/AutonomousSystem.o  src/IpAddress.o  src/DB.o  src/GenericHash.o  src/VlanHash.o  src/PacketDumper.o  src/LocalTrafficStats.o  src/HostHash.o  src/TrafficStats.o  src/CountriesHash.o  src/ThreadPool.o  src/PeriodicActivities.o  src/PF_RINGInterface.o  src/DummyInterface.o  src/HTTPstats.o  src/FlowHash.o  src/Geolocation.o  src/NtopGlobals.o  src/TcpPacketStats.o  src/FlowGrouper.o  src/AutonomousSystemHash.o  src/MacHash.o  src/CollectorInterface.o  src/MySQLDB.o  src/StoreManager.o  src/MDNS.o  src/GenericHost.o  src/InterfaceStatsHash.o  src/StatsManager.o  src/ViewInterface.o  -Wall ./nDPI/src/lib/.libs/libndpi.a -lpcap /root/ntopng/third-party/LuaJIT-2.1.0-beta3/src/libluajit.a -L/usr/local/lib -lrrd   /usr/local/lib/libzmq.a -L/usr/local/lib -ljson-c -L/usr/local/lib -lsodium  -lsqlite3 -L/usr/local/lib/mysql  -lmysqlclient   -lpthread -lz -lm -lssl -lcrypto -L/usr/lib -lssl -lcrypto -lssl -lcrypto  -lGeoIP  -L/usr/local/lib -lz -lcurl   -lm -lpthread -o ntopng
Makefile:175: warning: overriding recipe for target '-L/usr/local/lib'
Makefile:172: warning: ignoring old recipe for target '-L/usr/local/lib'
/usr/local/lib/libmysqlclient.so.27.0: warning: warning: stpcpy() is dangerous; do not use it
/usr/local/lib/librrd.so.5.1: warning: warning: strcat() is almost always misused, please use strlcat()
/usr/local/lib/librrd.so.5.1: warning: warning: random() may return deterministic values, is that what you want?
src/HTTPserver.o: In function `set_cookie':
src/HTTPserver.cpp:139: warning: warning: rand() may return deterministic values, is that what you want?
src/SNMP.o: In function `read_oid':
src/../third-party/snmp/asn1.c:310: warning: warning: sprintf() is often misused, please use snprintf()
src/Lua.o: In function `dbvm_tostring':
src/../third-party/lsqlite3/lsqlite3.c:260: warning: warning: strcpy() is almost always misused, please use strlcpy()
/usr/local/lib/libglib-2.0.so.4200.4: warning: warning: vsprintf() is often misused, please use vsnprintf()
/usr/bin/ld: warning: libpixman-1.so.32.6, needed by /usr/local/lib/librrd.so.5.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libpthread-stubs.so.2.0, needed by /usr/local/lib/librrd.so.5.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libfontconfig.so.11.0, needed by /usr/local/lib/librrd.so.5.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libfreetype.so.28.0, needed by /usr/local/lib/librrd.so.5.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libxcb-shm.so.1.1, needed by /usr/local/lib/librrd.so.5.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libxcb.so.4.0, needed by /usr/local/lib/librrd.so.5.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libxcb-render.so.1.1, needed by /usr/local/lib/librrd.so.5.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libXrender.so.6.0, needed by /usr/local/lib/librrd.so.5.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libX11.so.16.1, needed by /usr/local/lib/librrd.so.5.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libXext.so.13.0, needed by /usr/local/lib/librrd.so.5.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libXau.so.10.0, needed by /usr/local/lib/libcairo.so.12.3, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libXdmcp.so.11.0, needed by /usr/local/lib/libcairo.so.12.3, not found (try using -rpath or -rpath-link)
/usr/local/lib/libcairo.so.12.3: undefined reference to `XFreePixmap'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_create_pixmap_checked'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_image_ref'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_pictscreen_next'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_pictvisual_next'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_id'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FcPatternAddInteger'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_shm_attach_checked'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XShmGetImage'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FcObjectSetBuild'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_image_get_stride'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_set_picture_transform'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XSync'
/usr/local/lib/libpangocairo-1.0.so.3800.0: undefined reference to `FT_Init_FreeType'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_region32_fini'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Reference_Face'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FcPatternAddBool'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_region32_init_rect'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FcPatternGetBool'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_region32_contains_rectangle'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_pictdepth_next'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XSetClipRectangles'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_add_glyphs'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FT_Load_Glyph'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_image_unref'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FT_Done_Face'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_create_linear_gradient'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_get_image'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_discard_reply'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_shm_detach'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Get_Var_Blend_Coordinates'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FT_GlyphSlot_Embolden'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FcNameConstant'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_query_version_reply'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FT_GlyphSlot_Oblique'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_image_get_height'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FcObjectSetDestroy'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_region32_intersect'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_create_radial_gradient'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_New_Memory_Face'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FT_Render_Glyph'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderFreePicture'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_generate_id'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_glyph_get_mask_format'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderFindStandardFormat'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FcPatternDuplicate'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_query_version'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_shm_id'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_format_supported_destination'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_glyph_cache_thaw'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FT_Get_Kerning'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Get_Char_Index'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FcCharSetHasChar'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_glyph_cache_lookup'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderCreateRadialGradient'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FcFontList'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_change_picture'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_image_set_filter'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FT_Outline_Translate'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_create_gc'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_prefetch_maximum_request_length'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_image_set_destroy_function'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FcConfigGetCurrent'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_blt'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_image_get_width'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_image_create_linear_gradient'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_image_create_bits'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_pictdepth_visuals_iterator'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_image_get_depth'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderCompositeTriStrip'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Get_Advance'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_free_glyph_set'
/usr/local/lib/libpangocairo-1.0.so.3800.0: undefined reference to `FcPatternGetDouble'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XFreeGC'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_pictforminfo_next'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XCopyArea'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FT_Get_Sfnt_Table'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_get_property'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XSetClipMask'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_free_gc'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_pictscreen_depths_iterator'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_get_image_data'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_get_extension_data'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderCompositeText32'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderFillRectangle'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FT_Outline_Decompose'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Face_GetCharVariantIndex'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_composite_glyphs'
/usr/local/lib/libpangocairo-1.0.so.3800.0: undefined reference to `FcMatrixMultiply'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderSetPictureFilter'
/usr/local/lib/libpangocairo-1.0.so.3800.0: undefined reference to `FcPatternGetString'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_setup_roots_iterator'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_region32_translate'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FT_Get_Glyph_Name'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Select_Charmap'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FcPatternGetInteger'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XMaxRequestSize'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FT_Outline_Transform'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XGetImage'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_change_gc'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FcFontSort'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FcWeightFromOpenType'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_composite_glyphs_32'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderCompositeText16'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderComposite'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderFindVisualFormat'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FcPatternReference'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FcPatternHash'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_set_picture_filter'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_get_property_value'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_poll_for_reply'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FcPatternGetCharSet'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FcPatternCreate'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_poly_fill_rectangle'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FcPatternAddString'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_composite_glyphs_8'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FT_MulFix'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_get_setup'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FcPatternDel'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FT_Get_Next_Char'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FcFontRenderPrepare'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_region32_copy'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FcPatternGet'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderSetPictureClipRectangles'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FcPatternAddMatrix'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FT_Bitmap_New'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FcPatternAddDouble'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderSetPictureTransform'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_create_solid_fill'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_image_set_component_alpha'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_region32_union'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_get_image_reply'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_region32_n_rects'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FT_Load_Sfnt_Table'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderCreateGlyphSet'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_query_pict_formats_reply'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_visualtype_next'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FcConfigDestroy'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderCreateSolidFill'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderFreeGlyphs'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderFillRectangles'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_put_image'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XSetErrorHandler'
/usr/local/lib/libpangocairo-1.0.so.3800.0: undefined reference to `FcConfigSubstitute'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_copy_area'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FcObjectSetCreate'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FcPatternDestroy'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FcCharSetNextPage'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_send_request'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XChangeGC'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FT_Vector_Transform'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_wait_for_reply'
/usr/local/lib/libpangocairo-1.0.so.3800.0: undefined reference to `FT_Done_FreeType'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_fill_rectangles'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_screen_next'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_add_triangles'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_glyph_cache_remove'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FT_Set_Char_Size'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FT_Set_Transform'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_image_get_component_alpha'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_shm_attach'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XAddExtension'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_create_conical_gradient'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderQuerySubpixelOrder'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FT_Bitmap_Done'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FcObjectSetAdd'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_region32_rectangles'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_create_pixmap'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_region32_extents'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XShmPutImage'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_get_property_value_length'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_depth_next'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_get_input_focus'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_query_pict_formats_screens_iterator'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderAddGlyphs'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FcPatternEqual'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FT_Outline_Get_CBox'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_depth_visuals_iterator'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_image_create_radial_gradient'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_shm_get_image_reply'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Set_Var_Blend_Coordinates'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_image_composite32'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderCompositeTrapezoids'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XQueryColors'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FcFreeTypeCharIndex'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FcPatternBuild'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_region32_contains_point'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FT_Get_X11_Font_Format'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_shm_detach_checked'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FcPatternGetFTFace'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XESetCloseDisplay'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderChangePicture'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_connection_has_error'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_glyph_cache_freeze'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_query_pict_formats_formats_iterator'
/usr/local/lib/libpangocairo-1.0.so.3800.0: undefined reference to `FcPatternGetMatrix'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_region32_not_empty'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_composite'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XAllocColor'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XInitImage'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_region32_equal'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FcInitBringUptoDate'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FT_Bitmap_Convert'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XGetDefault'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_flush'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_transform_point_3d'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderCompositeText8'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XScreenNumberOfScreen'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderCreateLinearGradient'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderFindFormat'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_create_glyph_set'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_free_pixmap'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FT_Get_First_Char'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_get_property_reply'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_region32_init_rects'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_fill'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderQueryVersion'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_glyph_cache_create'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_glyph_cache_insert'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_composite_glyphs_no_mask'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_shm_query_version_reply'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_get_maximum_request_length'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_rasterize_trapezoid'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FT_New_Face'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_image_set_clip_region32'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_region32_subtract'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_query_pict_formats_subpixels'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_free_glyphs'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderCreatePicture'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_create_picture'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_query_pict_formats'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Get_Name_Index'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XFillRectangle'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XRenderFreeGlyphSet'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_shm_query_version'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_set_picture_clip_rectangles'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_composite_glyphs_16'
/usr/local/lib/libharfbuzz.so.8.7: undefined reference to `FT_Get_MM_Var'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_free_picture'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_shm_get_image'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_big_requests_id'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FcFontMatch'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_image_set_repeat'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XExtendedMaxRequestSize'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_request_check'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_image_create_solid_fill'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_render_trapezoids'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_image_get_data'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_image_set_transform'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_prefetch_extension_data'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_shm_put_image'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XPutImage'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XCreatePixmap'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FcWeightToOpenType'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FcCharSetFirstPage'
/usr/local/lib/libcairo.so.12.3: undefined reference to `FT_Library_SetLcdFilter'
/usr/local/lib/libcairo.so.12.3: undefined reference to `pixman_region32_init'
/usr/local/lib/libcairo.so.12.3: undefined reference to `XCreateGC'
/usr/local/lib/libcairo.so.12.3: undefined reference to `xcb_screen_allowed_depths_iterator'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FcFontSetDestroy'
/usr/local/lib/libpangoft2-1.0.so.3800.0: undefined reference to `FcConfigReference'
/usr/local/lib/libpangocairo-1.0.so.3800.0: undefined reference to `FcDefaultSubstitute'
collect2: ld returned 1 exit status
gmake: *** [Makefile:162: ntopng] Error 1`

- 

-

**Comment by emanuele-f** [comment]
This should not be related to ntopng iteself. Have you manually compiled x11 / gtk perhaps?

**Comment by JasonMarkowitz** [comment]
Added `-L/usr/X11R6/lib` to Makefile under NLIBS variable and it compiled cleanly. 
Can this be added to configure?

Thank you.

**Comment by emanuele-f** [comment]
@JasonMarkowitz the X11 dependency is pulled by librrd. Have you manually compiled librrd ?

**Comment by JasonMarkowitz** [comment]
I did not, but it compiles properly when specifying the library path. librrd is pulled from openbsd's standard packages.

**Comment by simonemainardi** [comment]
I don't think we should explicitly add path `-L/usr/X11R6/lib`:
- hard-coding paths is not a good idea
- the path is clearly related to the X11 windows system.

We already have part of the Makefile that is designed to opportunely print the libraries that are necessary to librrdtool:https://github.com/ntop/ntopng/blob/dev/Makefile.in#L41

```
...
LIBRRDTOOL_HOME=${PWD}/third-party/rrdtool-1.4.8
HAS_LIBRRDTOOL=$(shell pkg-config --atleast-version=1.4.8 librrd; echo $$?)
ifeq ($(HAS_LIBRRDTOOL), 0)
        LIBRRDTOOL_INC = $(shell pkg-config --cflags librrd)
        LIBRRDTOOL_LIB = $(shell pkg-config --libs librrd) # -lrrd_th
else
        LIBRRDTOOL_INC=-I$(LIBRRDTOOL_HOME)/src/
        ifeq ($(OS), $(filter $(OS), OpenBSD FreeBSD))
                LIBRRDTOOL_LIB=$(LIBRRDTOOL_HOME)/src/.libs/librrd_th.a -lm -lgobject-2.0 -lgmodule-2.0 -lglib-2.0
        else
                LIBRRDTOOL_LIB=$(LIBRRDTOOL_HOME)/src/.libs/librrd_th.a -lm -lgobject-2.0 -lgmodule-2.0 -ldl -lglib-2.0
        endif
endif
...
```

As you have librrd installed with the distro you should understand why your call to `shell pkg-config --libs librrd` does not return all the necessary paths to link to the library.

Please, play with the Makefile.in in the part highlighted above and send a pull request when you are confident it links on OpenBSD.
