### ISSUE TITLE
Password problem with special char

### ISSUE THREAD

**Issue by paoloB132** [ntop/ntopng#173]
If you set a password with some special char (first char) your password are rejected (and password border come red !)

**Comment by kYroL01** [comment]
in ntopng not all the spacial char are allowed for your password.
special char allowed are: **/**, **:**, **)**, **(**, **}**, **{**, **[**, **]**, **?**, **&**, **<**, **>**, **@** , **' ' (space char)**.

**Comment by paoloB132** [comment]
Pity … my preferred ones, very commonly used anyway, are not present. Is there any specific reasons to restrict to those…and let me say that previous version of ntop (also the stable version) works perfectly…and again ntopng let me set the password with supposedly forbidden ones during user creation !!

I’ve tried to use  one of the supposed valid but password border comes red immediately…I think there’re some problems there .


> On 18 set 2015, at 12:12, Michele Campus <notifications@github.com> wrote:
> 
> in ntopng not all the spacial char are allowed for your password.
> special char allowed are: /, :, ), (, }, {, [, ], ?, &, <, >, @ , ' ' (space char).
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/ntop/ntopng/issues/173#issuecomment-141411050>.
> 

------------------------------------------------------------------------------------------------
Paolo Barbato

Consorzio RFX
 <https://www.igi.cnr.it/>corso Stati Uniti,4                                  
35127 Padova - Italy                     	                 
Network Administrator 
phone: +39 049 8295097 fax: +39 049 8700718
------------------------------------------------------------------------------------------------

**Comment by kYroL01** [comment]
I'm going to try to understand better.
So, for example, if you set a password like **hello&&** or **hello$$** you have the same result ?
Because you said in one case you can set and in another you can't.

**Comment by paoloB132** [comment]
1) version ntopng 2.0 stable does not suffer of this trouble…I’ve always  used a supposed not allowed  char as “first” one.

2) I’ve recently updated to development branch, following Luca suggestion, and now I have v.2.0.150917 . After this “upgrade" I noticed that I was no more able to login, and that immediately when typed  first char password, the field comes red bordered (new functionality on noting I’ve  supposed ) and I’m not able to log in.

3) Just to play I’ve tried as first character also  one of those suggested by you but all the time immediately after typed field became red bordered .

I’ve verified  this on Safari, Firefox and Chrome.



> On 18 set 2015, at 12:25, Michele Campus <notifications@github.com> wrote:
> 
> I'm going to try to understand better.
> So, for example, if you set a password like hello&& or hello$$ you have the same result ?
> Because you said in one case you can set and in another you can't.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/ntop/ntopng/issues/173#issuecomment-141413061>.
> 

------------------------------------------------------------------------------------------------
Paolo Barbato

Consorzio RFX
 <https://www.igi.cnr.it/>corso Stati Uniti,4                                  
35127 Padova - Italy                     	                 
Network Administrator 
phone: +39 049 8295097 fax: +39 049 8700718
------------------------------------------------------------------------------------------------

**Comment by kYroL01** [comment]
For the "stable" vs "dev" version, the stable one maybe is good for this part, but the latest implementations are in the dev branch, so is good that you upgrade from that.

I think we have to investigate on this bug. So thanks for now for evidence this problem.
I think a fix is needed if you say this.

**Comment by lucaderi** [comment]
@paoloB132 Can you please make an example of a user and password I can use to reproduce the bug in the development version?

**Comment by lucaderi** [comment]
I think I have realised what the problem could be. You have set the password containing chars ntopng that now filters, then you have upgraded to the new ntopng that prevents you from entering such chars. Then the problem. I suggest to stop ntopng, flush redis, start ntopng again, then the password you will set will be consistent with what ntopng accepts at login.
