### ISSUE TITLE
Switching license type after purchase

### ISSUE THREAD

**Issue by fsamareanu** [ntop/ntopng#1730]
Hello,

I bought the ARM PRO version of ntopng and I want to switch to an Intel box. Is there an option to pay for a license upgrade?
I tried mailing your info e-mail address but there was no reply.

Thank you

**Comment by simonemainardi** [comment]
Please,  fill the form at: https://www.ntop.org/support/need-help-2/contact-us/. Add the order id of the purchase and you will receive instructions.
