### ISSUE TITLE
Invalid hostname value when checking Top local talkers

### ISSUE THREAD

**Issue by fsamareanu** [ntop/ntopng#1731]
Hello,

The hostname in top local talkers seems to be wrong. There is a reverse DNS entry for the IP address though, resolvable from the host running ntopng:

fsamareanu@XXX:~$ host 192.168.1.10
10.1.168.192.in-addr.arpa domain name pointer livingroom-shield.local.lan.

Details of host running ntopng:

Linux XXX.local.lan 4.14.30-v7+ #1102 SMP Mon Mar 26 16:45:49 BST 2018 armv7l GNU/Linux
ii  ntopng                               3.3.180131-4070              armhf        Web-based traffic monitoring.
ii  ntopng-data                          3.3.180131                   all          Data files (geoip) for ntopng.

fsamareanu@oinky-pihole:~$ ntopng --version
v.3.3.180131    [Enterprise/Professional/Embedded build]
GIT rev:        dev:691a50922291992d5f967b8894a26b1cfd826e57:20180131
Pro rev:        r1447
Built on:       Raspbian GNU/Linux 9.1 (stretch)
System Id:      XXXXXXXXXXXXX
Platform:       armv7l
Edition:        Professional Embedded
License Type:   Permanent
Maintenance:    Until Sun Feb 17 20:13:16 2019 [319 days left]
License:        XXXXXXXXXXXXXXXXXX
![host_details](https://user-images.githubusercontent.com/38040820/38291457-df64c7aa-37f0-11e8-9752-26dd6ad8897d.png)
![local_talkers](https://user-images.githubusercontent.com/38040820/38291458-dfbb2da2-37f0-11e8-9110-f93b3e22f244.png)

**Comment by lucaderi** [comment]
ntopng learns names using protocols such as SMB, MDNS, SSDP... Can you please verify if such device is also advertising the string you have reported in this issue?

**Comment by fsamareanu** [comment]
Hello,

On a first glance, it doesn't. Also my Samsung S8 is identified as connectsdk while it's name is Galaxy S8.

**Comment by emanuele-f** [comment]
@fsamareanu can you provide a pcap with `DHCP`, `MDNS` and/or `SSDP` traffic? In order to do so, please do the following:

1. disconnect your device from the network
2. run `sudo tcpdump -i your_lan_iface -s0 -w traffic.pcap port 67 or port 68 or host 239.255.255.250 or port 5353`
3. connect your device to the network and wait some time (e.g. 5 minutes)

**Comment by fsamareanu** [comment]
I'm using a port mirror on a managed switch. Does that make any difference?

**Comment by emanuele-f** [comment]
No, that's the same. It's important to disconnect the phone device so that on reconnection it will generate new DHCP packets

**Comment by fsamareanu** [comment]
sent

**Comment by emanuele-f** [comment]
There was a problem in the decoding of MDNS packets, now fixed with commit 8f0780b4c544e34112ed0dafda0c3aba4edbcc33 . Please note that now your device will be identified as `SHIELD-Android-TV-85c001c94fa09e70c5fcfafb64710bcb` as it is the name it advertises over MDNS.

**Comment by fsamareanu** [comment]
Will test tomorrow and come back to you.

**Comment by fsamareanu** [comment]
Confirmed, the device now shows as SHIELD-Android-TV-85c001c94fa09e70c5fcfafb64710bcb .

**Comment by emanuele-f** [comment]
So, is this issue solved?

**Comment by fsamareanu** [comment]
Yes, this issue is solved. Closing.
