### ISSUE TITLE
URL issues with SNMP Devices

### ISSUE THREAD

**Issue by fsamareanu** [ntop/ntopng#1732]
Hello,
ntopng version:

v.3.3.180404	[Enterprise/Professional build]

ntopng setting:

--http-prefix="/ntopng"

Steps to reproduce:

Click Devices -> SNMP -> Click SNMP device graph icon under Chart tab -> Notice the url opened contains /ntopng.

Now from the timeseries dropdown select a switch port (in my case it's a snmp enabled switch). Notice the URL is now /lua/pro/enterprise (missing the prefix configured).

**Comment by emanuele-f** [comment]
Fixed. The fix will be available in the new package. Thank you for reporting
