### ISSUE TITLE
ntopng mysqldb errors

### ISSUE THREAD

**Issue by juesor** [ntop/ntopng#1733]
I was checking syslog messages this morning and noticed that ntopng started sending errors to the tune of  864,430 messages since midnight last night.

Apr  4 13:52:34 ntopng ntopng: [BatchedMySQLDB.cpp:252] ERROR: MySQL error: Out of range value for column 'idx' at row 1 [rc=-1]
Apr  4 13:52:34 ntopng ntopng: 04/Apr/2018 13:52:34 [MySQLDB.cpp:669] Disconnected from MySQL for interface tcp://108.59.105.49:5556...
Apr  4 13:52:34 ntopng ntopng: 04/Apr/2018 13:52:34 [MySQLDB.cpp:682] Attempting to connect to MySQL for interface tcp://108.59.105.49:5556...
Apr  4 13:52:34 ntopng ntopng: 04/Apr/2018 13:52:34 [MySQLDB.cpp:723] Successfully connected to MySQL [ntopng@localhost:3306] for interface tcp://108.59.105.49:5556
Apr  4 13:52:34 ntopng ntopng: 04/Apr/2018 13:52:34 [BatchedMySQLDB.cpp:252] ERROR: MySQL error: Out of range value for column 'idx' at row 1 [rc=-1]
Apr  4 13:52:34 ntopng ntopng: [BatchedMySQLDB.cpp:254] ERROR: SQL statement: INSERT INTO `flowsv4` (VLAN_ID,L7_PROTO,IP_SRC_ADDR,L4_SRC_PORT,IP_DST_ADDR,L4_DST_PORT,PROTOCOL,IN_BYTES,OUT_BYTES,PACKETS,FIRST_SWITCHED,LAST_SWITCHED,INFO,JSON,NTOPNG_INSTANCE_NAME,INTERFACE_ID,PROFILE) VALUES 

Above is a snip it of the errors and then from there i get a ton of SQL statement  errors and then it repeats.

![image](https://user-images.githubusercontent.com/14931420/38328455-9d29070a-3810-11e8-8ab9-aada98ac3e6b.png)
![image](https://user-images.githubusercontent.com/14931420/38328461-9fff056a-3810-11e8-91c2-2be898185c14.png)
![image](https://user-images.githubusercontent.com/14931420/38328467-a459ac64-3810-11e8-9105-46d96c13be10.png)
![image](https://user-images.githubusercontent.com/14931420/38328475-a7371dea-3810-11e8-9c2d-2826beb85822.png)

Here is a log capture for a 5 second timeline.

The first batch of this happening was at 23:51:20 last night 
![image](https://user-images.githubusercontent.com/14931420/38328645-0f907b5c-3811-11e8-9d88-c033b55f1c4d.png)

Above is the picture of that.  If you need more log data let me know.

I will update to the latest now.

--> Running transaction check
---> Package n2disk.x86_64 0:3.1.180315-4946 will be updated
---> Package n2disk.x86_64 0:3.1.180404-4948 will be an update
---> Package ntopng.x86_64 0:3.3.180315-3967 will be updated
---> Package ntopng.x86_64 0:3.3.180404-4045 will be an update
---> Package ntopng-data.noarch 0:3.3.180315-3967 will be updated
---> Package ntopng-data.noarch 0:3.3.180404-4045 will be an update
---> Package pfring.x86_64 0:7.1.0-1797 will be updated
---> Package pfring.x86_64 0:7.1.0-1826 will be an update
---> Package pfring-dkms.noarch 0:7.1.0-1797 will be updated
---> Package pfring-dkms.noarch 0:7.1.0-1826 will be an update
--> Finished Dependency Resolution
  
Thoughts?  Have you seen this before when the DB grows to a large state?

total 937791936
-rw-rw---- 1 mysql mysql        13358 Mar 26 12:56 aggrflowsv4.frm
-rw-rw---- 1 mysql mysql           80 Mar 26 12:56 aggrflowsv4.par
-rw-rw---- 1 mysql mysql   1183370900 Apr  4 14:06 aggrflowsv4#P#p0.MYD
-rw-rw---- 1 mysql mysql   1718587392 Apr  4 14:06 aggrflowsv4#P#p0.MYI
-rw-rw---- 1 mysql mysql   1183659552 Apr  4 14:06 aggrflowsv4#P#p1.MYD
-rw-rw---- 1 mysql mysql   1718296576 Apr  4 14:06 aggrflowsv4#P#p1.MYI
-rw-rw---- 1 mysql mysql   1185151624 Apr  4 14:06 aggrflowsv4#P#p2.MYD
-rw-rw---- 1 mysql mysql   1721269248 Apr  4 14:06 aggrflowsv4#P#p2.MYI
-rw-rw---- 1 mysql mysql   1184788964 Apr  4 14:06 aggrflowsv4#P#p3.MYD
-rw-rw---- 1 mysql mysql   1721191424 Apr  4 14:06 aggrflowsv4#P#p3.MYI
-rw-rw---- 1 mysql mysql   1184793504 Apr  4 14:06 aggrflowsv4#P#p4.MYD
-rw-rw---- 1 mysql mysql   1719917568 Apr  4 14:06 aggrflowsv4#P#p4.MYI
-rw-rw---- 1 mysql mysql   1180914280 Apr  4 14:06 aggrflowsv4#P#p5.MYD
-rw-rw---- 1 mysql mysql   1713256448 Apr  4 14:06 aggrflowsv4#P#p5.MYI
-rw-rw---- 1 mysql mysql   1180264132 Apr  4 14:06 aggrflowsv4#P#p6.MYD
-rw-rw---- 1 mysql mysql   1713490944 Apr  4 14:06 aggrflowsv4#P#p6.MYI
-rw-rw---- 1 mysql mysql   1186827164 Apr  4 14:06 aggrflowsv4#P#p7.MYD
-rw-rw---- 1 mysql mysql   1722846208 Apr  4 14:06 aggrflowsv4#P#p7.MYI
-rw-rw---- 1 mysql mysql        13358 Mar 26 12:56 aggrflowsv6.frm
-rw-rw---- 1 mysql mysql           80 Mar 26 12:56 aggrflowsv6.par
-rw-rw---- 1 mysql mysql            0 Mar 26 12:56 aggrflowsv6#P#p0.MYD
-rw-rw---- 1 mysql mysql         4096 Mar 26 12:56 aggrflowsv6#P#p0.MYI
-rw-rw---- 1 mysql mysql            0 Mar 26 12:56 aggrflowsv6#P#p1.MYD
-rw-rw---- 1 mysql mysql         4096 Mar 26 12:56 aggrflowsv6#P#p1.MYI
-rw-rw---- 1 mysql mysql            0 Mar 26 12:56 aggrflowsv6#P#p2.MYD
-rw-rw---- 1 mysql mysql         4096 Mar 26 12:56 aggrflowsv6#P#p2.MYI
-rw-rw---- 1 mysql mysql            0 Mar 26 12:56 aggrflowsv6#P#p3.MYD
-rw-rw---- 1 mysql mysql         4096 Mar 26 12:56 aggrflowsv6#P#p3.MYI
-rw-rw---- 1 mysql mysql            0 Mar 26 12:56 aggrflowsv6#P#p4.MYD
-rw-rw---- 1 mysql mysql         4096 Mar 26 12:56 aggrflowsv6#P#p4.MYI
-rw-rw---- 1 mysql mysql            0 Mar 26 12:56 aggrflowsv6#P#p5.MYD
-rw-rw---- 1 mysql mysql         4096 Mar 26 12:56 aggrflowsv6#P#p5.MYI
-rw-rw---- 1 mysql mysql            0 Mar 26 12:56 aggrflowsv6#P#p6.MYD
-rw-rw---- 1 mysql mysql         4096 Mar 26 12:56 aggrflowsv6#P#p6.MYI
-rw-rw---- 1 mysql mysql            0 Mar 26 12:56 aggrflowsv6#P#p7.MYD
-rw-rw---- 1 mysql mysql         4096 Mar 26 12:56 aggrflowsv6#P#p7.MYI
-rw-rw---- 1 mysql mysql           65 Mar 26 12:55 db.opt
-rw-rw---- 1 mysql mysql        13358 Mar 26 12:56 flowsv4.frm
-rw-rw---- 1 mysql mysql           80 Mar 26 12:56 flowsv4.par
-rw-rw---- 1 mysql mysql  99955296316 Apr  3 22:51 flowsv4#P#p0.MYD
-rw-rw---- 1 mysql mysql  17248689152 Apr  3 22:51 flowsv4#P#p0.MYI
-rw-rw---- 1 mysql mysql  99737324828 Apr  3 22:51 flowsv4#P#p1.MYD
-rw-rw---- 1 mysql mysql  17207275520 Apr  3 22:51 flowsv4#P#p1.MYI
-rw-rw---- 1 mysql mysql 100021167180 Apr  3 22:51 flowsv4#P#p2.MYD
-rw-rw---- 1 mysql mysql  17258404864 Apr  3 22:51 flowsv4#P#p2.MYI
-rw-rw---- 1 mysql mysql  99964835860 Apr  3 22:51 flowsv4#P#p3.MYD
-rw-rw---- 1 mysql mysql  17245715456 Apr  3 22:51 flowsv4#P#p3.MYI
-rw-rw---- 1 mysql mysql  99838100208 Apr  3 22:51 flowsv4#P#p4.MYD
-rw-rw---- 1 mysql mysql  17228718080 Apr  3 22:51 flowsv4#P#p4.MYI
-rw-rw---- 1 mysql mysql  99955919580 Apr  3 22:51 flowsv4#P#p5.MYD
-rw-rw---- 1 mysql mysql  17243826176 Apr  3 22:51 flowsv4#P#p5.MYI
-rw-rw---- 1 mysql mysql  99748133036 Apr  3 22:51 flowsv4#P#p6.MYD
-rw-rw---- 1 mysql mysql  17210558464 Apr  3 22:51 flowsv4#P#p6.MYI
-rw-rw---- 1 mysql mysql  99967546652 Apr  3 22:51 flowsv4#P#p7.MYD
-rw-rw---- 1 mysql mysql  17247074304 Apr  3 22:51 flowsv4#P#p7.MYI
-rw-rw---- 1 mysql mysql        13358 Mar 26 12:56 flowsv6.frm
-rw-rw---- 1 mysql mysql           80 Mar 26 12:56 flowsv6.par
-rw-rw---- 1 mysql mysql            0 Mar 26 12:56 flowsv6#P#p0.MYD
-rw-rw---- 1 mysql mysql         4096 Mar 26 12:56 flowsv6#P#p0.MYI
-rw-rw---- 1 mysql mysql            0 Mar 26 12:56 flowsv6#P#p1.MYD
-rw-rw---- 1 mysql mysql         4096 Mar 26 12:56 flowsv6#P#p1.MYI
-rw-rw---- 1 mysql mysql            0 Mar 26 12:56 flowsv6#P#p2.MYD
-rw-rw---- 1 mysql mysql         4096 Mar 26 12:56 flowsv6#P#p2.MYI
-rw-rw---- 1 mysql mysql            0 Mar 26 12:56 flowsv6#P#p3.MYD
-rw-rw---- 1 mysql mysql         4096 Mar 26 12:56 flowsv6#P#p3.MYI
-rw-rw---- 1 mysql mysql            0 Mar 26 12:56 flowsv6#P#p4.MYD
-rw-rw---- 1 mysql mysql         4096 Mar 26 12:56 flowsv6#P#p4.MYI
-rw-rw---- 1 mysql mysql            0 Mar 26 12:56 flowsv6#P#p5.MYD
-rw-rw---- 1 mysql mysql         4096 Mar 26 12:56 flowsv6#P#p5.MYI
-rw-rw---- 1 mysql mysql            0 Mar 26 12:56 flowsv6#P#p6.MYD
-rw-rw---- 1 mysql mysql         4096 Mar 26 12:56 flowsv6#P#p6.MYI
-rw-rw---- 1 mysql mysql            0 Mar 26 12:56 flowsv6#P#p7.MYD
-rw-rw---- 1 mysql mysql         4096 Mar 26 12:56 flowsv6#P#p7.MYI
# du -h
895G    .

**Comment by juesor** [comment]
Do you need anymore information?

**Comment by juesor** [comment]
Ok so messages grew to 30G due to ntopng log errors.

I'm guessing my tables index is out of allowed range.

ERROR: MySQL error: Out of range value for column 'idx' at row 1 [rc=-1]

Traction on this ?

**Comment by simonemainardi** [comment]
@juesor your guess is correct, column 'idx' wrapped.

- stop ntopng

- manually log into mysql and convert `idx` columns to big unsigned integers. Note that this can take a lot of time.

```
simone@devel:~/ntopng$ mysql -uroot -pXXX ntopng
mysql: [Warning] Using a password on the command line interface can be insecure.
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 13
Server version: 5.7.21-0ubuntu0.16.04.1 (Ubuntu)

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> ALTER TABLE flowsv4 MODIFY idx BIGINT UNSIGNED;
Query OK, 16110 rows affected, 1 warning (0.08 sec)
Records: 16110  Duplicates: 0  Warnings: 1

mysql> ALTER TABLE flowsv6 MODIFY idx BIGINT UNSIGNED;
Query OK, 4840 rows affected, 1 warning (0.06 sec)
Records: 4840  Duplicates: 0  Warnings: 1
```

- restart ntopng

**Comment by juesor** [comment]
Ok so i did that and my errors went away but this is odd now my info shows junk.

select * from flowsv4 limit 2\G
*************************** 1. row ***************************
                 idx: NULL
             VLAN_ID: 0
            L7_PROTO: 91
         IP_SRC_ADDR: 3494573660
         L4_SRC_PORT: 31540
         IP_DST_ADDR: 2712332341
         L4_DST_PORT: 443
            PROTOCOL: 6
            IN_BYTES: 864
           OUT_BYTES: 5216
             PACKETS: 23
      FIRST_SWITCHED: 1523629832
       LAST_SWITCHED: 1523629853
                INFO:
                JSON: 1  x▒m▒Ok▒0
ſJ▒yS-▒r▒▒B֍@▒&=▒1B)▒0JS▒▒T▒▒'e▒▒a▒▒▒E▒▒z▒▒f▒▒▒▒▒d▒2▒▒6▒-▒#`▒~.▒C▒V{P
▒H/*▒▒9G+:▒Th▒iۥ▒є▒P6▒D▒▒▒)r▒▒Pq4v2▒@▒p:A▒▒a▒▒▒m8▒w▒▒,▒(=_5▒▒▒▒/0>8wA]▒▒▒▒▒_Q ▒▒d▒"J▒`▒o▒▒o▒]W}▒▒f▒▒▒6▒▒▒MUvu▒▒▒cv▒▒%▒ ▒c▒ٓtߴݿ▒▒▒C▒w2z+  ▒ ▒s▒q▒▒▒Y▒▒▒NmW▒jѧ▒~▒▒▒y8▒▒=▒_▒▒▒▒▒▒:u▒▒mY▒]▒▒i>▒▒▒▒2▒8g▒ i|▒@w8
             PROFILE:
NTOPNG_INSTANCE_NAME: ntopng
        INTERFACE_ID: 4
*************************** 2. row ***************************
                 idx: NULL
             VLAN_ID: 0
            L7_PROTO: 140
         IP_SRC_ADDR: 3451488014
         L4_SRC_PORT: 57392
         IP_DST_ADDR: 288950471
         L4_DST_PORT: 993
            PROTOCOL: 6
            IN_BYTES: 1255
           OUT_BYTES: 5071
             PACKETS: 28
      FIRST_SWITCHED: 1523629848
       LAST_SWITCHED: 1523629853
                INFO:
h▒▒3_Ξ▒r-D▒Bh▒$DZ▒▒▒B▒fA▒ ▒D▒▒▒▒@▒_%▒u▒▒▒▒▒.▒*▒)Mz!"▒▒R▒▒▒W▒wwf
                               5
VM{D▒*׭,▒▒t▒O▒  >x▒@;▒▒f▒▒▒a*dg▒:m▒▒h#▒C_▒▒c8▒R߁▒▒d▒▒▒K▒)_A▒▒QnJx▒▒Ҩ▒▒D▒▒$Q|M▒p▒▒*?▒▒T}▒▒f▒▒▒3Gm[▒˟▒▒▒▒&ч▒▒▒▒kì▒FF▒
c▒J▒▒▒7e▒)  ▒▒^Ѩ▒▒Vk=Ť▒Y▒ǾNmW▒j٧r▒▒▒e▒G▒▒▒▒▒▒(O▒~w▒▒:u▒▒CYe▒e?.▒s▒I8▒▒Ņs▒▒8▒▒ y▒
             PROFILE:
NTOPNG_INSTANCE_NAME: ntopng
        INTERFACE_ID: 4
2 rows in set (0.00 sec)

I can open a new ticket if needed.  Or is that normal ?
