### ISSUE TITLE
SNMP Switch not populating Port MAC

### ISSUE THREAD

**Issue by hytek3000** [ntop/ntopng#1735]
We are on an Enterprise trial, and none of our SNMP devices are showing up with the Port MACs. All of our switches are Cisco (2xxx, 3xxx, SGx00, Nexus 3k, etc), and SNMP is working. We are also using Solarwinds, and through SNMP under Solarwinds we are able to pull the connected Port MACs.

Any thoughts to why none of the Port MACs are showing up?

![versionntop](https://user-images.githubusercontent.com/38108898/38375740-c0f180d6-38ab-11e8-8fb1-6c69c44768ce.JPG)

![portmacs](https://user-images.githubusercontent.com/38108898/38375751-c3863dc8-38ab-11e8-84dc-e5c3db20dc8e.JPG)

**Comment by lucaderi** [comment]
We need to implement a different policy as Cisco switches need community@VLAN and a different OID needs to be polled. Stay tuned.

**Comment by lucaderi** [comment]
Fixed in the dev (unstable) build. Will be included in the next stable. Please use the dev version for testing (will be available within 30 mins from now). Please reopen this issue if necessary.
