### ISSUE TITLE
HTTPS instructions for Windows?

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#1736]
I am hoping someone can help me get HTTPS setup using windows.  Is is almost the same process as doing it on linux? I am not too familiar generating certificates on Windows but can try.

Don't need detailed instructions, just some general pointers to make sure I am going the right way :)

**Comment by emanuele-f** [comment]
You could generate the pem certificate on linux if that's a problem. Just search on the web if you want to go with windows certificate generation.
