### ISSUE TITLE
Historical Data Explorer Issue

### ISSUE THREAD

**Issue by kwunyinhui** [ntop/ntopng#1737]
Dears,

I am trying to review the historical flow data for last 7 days.
But there is no any search result from Historical Data Explorer.
I have configured store 7 days log to SQL. I am not sure is it correct setting or not?

![111](https://user-images.githubusercontent.com/37438134/38399118-e2c6412e-3937-11e8-9cf4-9ada90de9183.png)
![222](https://user-images.githubusercontent.com/37438134/38399120-e710a0a8-3937-11e8-87bb-36f003656a98.png)
![333](https://user-images.githubusercontent.com/37438134/38399123-e965face-3937-11e8-91a3-03ede03ecaa7.png)

**Comment by QuentinBibas** [comment]
By any chance, does your network have VLAN tags ?
If yes, you need to click on "id" : if you leave the field empty, you'll see every VLAN tagged packet
if you enter a VLAN ID, then you'll only see the packets from that VLAN

**Comment by kwunyinhui** [comment]
Thanks for your information. unfortunately seems it is not related to VLAN tag issue.
I tired to select the ID, but it still do not have any information.

**Comment by emanuele-f** [comment]
@kwunyinhui can you provide web access to your server? If so, please send me the credentials at faranda@ntop.org

**Comment by kwunyinhui** [comment]
@emanuele-f Thanks for your help. But the server is not allowed remote access.
I can collect some information to you if you need.

**Comment by simonemainardi** [comment]
@QuentinBibas 

- what is the full ntopng configuration used?

- If you manually browse the MySQL database, do you see the flows?

- is the first/last switched timestamp of flows in-sync with the system date and time?

- can you right-click on the historical data explorer page and open the browser inspector? do you see any errors there?

**Comment by QuentinBibas** [comment]
@simonemainardi 

I'm not the one with the problem ;)

**Comment by simonemainardi** [comment]
@QuentinBibas sorry about that ;)

+@kwunyinhui

**Comment by kwunyinhui** [comment]
@simonemainardi 

Sorry for my late reply. Please find my comment here.

what is the full ntopng configuration used?
 => --interface="tcp://127.0.0.1:5556"
--local-networks="192.168.0.0/16"
--dns-mode=1
--dump-flows=mysql;localhost;ntopng;flows;root;xxxxxx
-X=100000
-x=3000

If you manually browse the MySQL database, do you see the flows?
 => I saw the record in flowsv4 table is keep increasing. 

is the first/last switched timestamp of flows in-sync with the system date and time?
=> May I know how can I compare it? 

can you right-click on the historical data explorer page and open the browser inspector? do you see any errors there?
![image](https://user-images.githubusercontent.com/37438134/38727408-84a5ae50-3f3f-11e8-95ad-ac84dc75747e.png)

**Comment by emanuele-f** [comment]
Can you try with chrome/firefox?

**Comment by kwunyinhui** [comment]
@emanuele-f I cannot find any error message in Chrome. But there do not show any result.
![image](https://user-images.githubusercontent.com/37438134/38730370-ceaef1f6-3f48-11e8-828f-70a28aa3a60a.png)

**Comment by simonemainardi** [comment]
@kwunyinhui if you open the chrome inspector (as already done above), any console error should indicate a clickable file name (e.g., db_explorer.lua). A click on that file name should bring you to the part of the file that caused the issue. Can you please follow any error and post screenshots of the parts of the files that are causing the error? (Make sure to CTRL+SHIFT+R with the inspector open before following doing this operation)

**Comment by kwunyinhui** [comment]
@simonemainardi 
Seems there is no error message.

![image](https://user-images.githubusercontent.com/37438134/38785694-0d41d966-4155-11e8-8c83-9dcbd90c84d3.png)

**Comment by kwunyinhui** [comment]
I saw the flows are keeping exported to the SQL server.

![image](https://user-images.githubusercontent.com/37438134/38843345-24104cfa-4221-11e8-9102-028861ff1c81.png)

I tired to search the flows records from Feb to now. 
It shown the records on 22 March only, is there limitation on the page?

First Page
![image](https://user-images.githubusercontent.com/37438134/38843465-a55f41a8-4221-11e8-9752-de5ad34c3175.png)

Last Page
![image](https://user-images.githubusercontent.com/37438134/38843491-c717f18c-4221-11e8-93c7-5f388b831dd6.png)

**Comment by emanuele-f** [comment]
@kwunyinhui there is probably a problem with some html value inside the fields. Can you manually open the following url and send me the full result at faranda@ntop.org ? Please change `http://127.0.0.1:3000` with your ntopng server and `ifid=0` with your network interface id.

`http://127.0.0.1:3000/lua/get_db_flows.lua?ifid=0&period_begin_str=01/04/2018 08:07:21&timezone=7200&vlan=0&protocol=&epoch_begin=1522562841&search=&host=&ifid=0&profile=&period_end_str=06/04/2018 09:07:21&epoch_end=1522998441&l4proto=&info=&port=`

**Comment by kwunyinhui** [comment]
My interface id should be 6. When I enter the link manually. 
It report no return message for the link below.

![image](https://user-images.githubusercontent.com/37438134/38856875-45465d2c-425a-11e8-86d2-8367a019c478.png)


![image](https://user-images.githubusercontent.com/37438134/38856865-3cb6d0a6-425a-11e8-9811-9fa12f6107c3.png)

**Comment by emanuele-f** [comment]
Please now double check with this query that there are no flows between 8:07-9:07 on 1 April `select COUNT(*) from flowsv4 where FIRST_SWITCHED >= 1522562841 AND FIRST_SWITCHED <= 1522998441;` . If so, the flows were not exported to the database at all.

**Comment by kwunyinhui** [comment]
seems there is no records between 1522562841 and 1522998441. 
But I can see the records is keep increasing in the table of flowsv4.

![image](https://user-images.githubusercontent.com/37438134/38858862-5f4e7786-425f-11e8-9147-a5b72aa679b0.png)

**Comment by emanuele-f** [comment]
Can you perform some tests with the mysql database to figure out what's happening? In particular, if you can't see the last hour flows into ntopng but you actually see the flow count increasing, can you perform a query like `select FIRST_SWITCHED from flowsv4 order by FIRST_SWITCHED desc limit 10` to verify if the db actually holds the latest data?

**Comment by kwunyinhui** [comment]
Sorry, I can see the first_switched value in the records. But I dont know how to convert it in the datetime.
So I am not sure is the data are latest or not.
![image](https://user-images.githubusercontent.com/37438134/38860517-f691375c-4262-11e8-94ed-5302a0df893d.png)

**Comment by emanuele-f** [comment]
Hi, on linux you can do `date -d @1521692082`. This is my result on my machine: `Thu Mar 22 05:14:42 CET 2018`. So the timestamp reported is wrong. Is your server time correct?

**Comment by kwunyinhui** [comment]
@emanuele-f  Thanks! Same as your result : Thu Mar 22 12:14:41 HKT 2018
I checked the system time is correct.
I checked the FIRST_SWITCHED value didn't change from last day, it still keep on 1521692082 or 1521692081.
Is something hard-coded the value?

**Comment by emanuele-f** [comment]
Since you are capturing from nprobe, it seems like your netflow exporter is reporting wrong timestamp. If you can provide a pcap capture of the netflow traffic I can double check this. Please also post your nprobe configuration.

**Comment by kwunyinhui** [comment]
Thanks! I can post the nprobe configuration here first.
And I will try to collect it later.

```
#         The  configuration  file is similar to the command line, with the exception that an equal
#        sign '=' must be used between key and value. Example:  -i=p1p2  or  --interface=p1p2  For
#        options with no value (e.g. -v) the equal is also necessary. Example: "-v=" must be used.
#
#
#       -g|--pid-file
#        Specifies the path where the PID (process ID) is saved. This option is ignored when
#        nProbe is controlled with systemd (e.g., service nProbe start).
#
# -G=/var/run/nprobe.pid
#
#       -G|--daemon-mode
#        This parameter causes nProbe to become a daemon, i.e. a task which runs in background
#        without connection to a specific terminal. To use nProbe other than as a casual monitoring
#        tool, you probably will want to use this option. This option is ignored when nProbe is
#        controlled with systemd (e.g., service nProbe start)
#
# -G=
#
#       -i|--interface
#        Specifies the physical network interface that nProbe will use to perform the
#        monitoring. On Unix you can specify the interface name  (e.g. -i lo) whereas on Windows
#        you must use the interface number instead (see -h to see the list of numeric ids).
#        To disable monitoring from physical interfaces (e.g., when nProbe is used in
#        collector-only mode) specify -i=none
#
# -i=none
# -i=eth1
-i=lo
#
#       -n|--collector
#        Specifies the NetFlow collector that will be used by nProbe to send the monitored
#        flows. This option can be specified multiple times to deliver monitored flows to
#        multiple collectors in round-robin mode. To disable flow export to NetFlow collectors
#        specify -n=none
#
# -n=10.0.0.1:2055
-n=none
#
#       -3|--collector-port
# Specifies the port that is being used by a NetFlow exporter to send NetFlow to nProbe.
# Multiple NetFlow exporters can symultaneously send data to nProbe using the same port.
# In case no NetFlow exporter is sending data it is safe to skip this option.
#
# -3=6363
```

**Comment by emanuele-f** [comment]
Why are you capturing from the loopback interface? The `-3` option is commented.

**Comment by kwunyinhui** [comment]
@emanuele-f since it's the default configuraiton and I saw there have flows records can show in nProbe. 
So I didnt change the configuration file.

**Comment by emanuele-f** [comment]
You are only monitoring the loopback interface traffic (which is probably not what you want). What traffic do you wish to monitor? Please check out https://www.ntop.org/nprobe/network-monitoring-101-a-beginners-guide-to-understanding-ntop-tools/

**Comment by kwunyinhui** [comment]
@emanuele-f Oh, I change the interface config later.
Also, please find the pcap information for reference.
![image](https://user-images.githubusercontent.com/37438134/38924569-e49a7978-432f-11e8-9a40-11620ca7fa53.png)

**Comment by emanuele-f** [comment]
The reported timestamp seems correct, so the problem is probably the misconfigured nprobe

**Comment by kwunyinhui** [comment]
I changed the nprobe interface setting. But seems the new flows are still using the old date.
Is it database something wrong?

![image](https://user-images.githubusercontent.com/37438134/38965513-d3bce67e-43af-11e8-9757-c930a4c1c4e5.png)

**Comment by kwunyinhui** [comment]
I show the process list in the table. Seems it inserted the wrong timestamp from the  ntopng.
So is it configuration mistake in ntopng?

![image](https://user-images.githubusercontent.com/37438134/38966143-487164b0-43b3-11e8-93a0-6df67bcc3f45.png)

**Comment by emanuele-f** [comment]
Please post your new nprobe/ntopng configuration

**Comment by kwunyinhui** [comment]
This is the latest config on nprobe/ntopng.

NTOPNG config-:
```
--interface="tcp://10.72.40.150:5556"
--local-networks="192.168.0.0/16,172.16.0.0/16"
--dns-mode=1
--dump-flows=mysql;localhost;ntopng;flows;root;xxxxxx
-X=1000000
-x=30000
```

NPROBE config:
```
[root@FHKC-LOG-001 nprobe]# cat nprobe.conf
#         The  configuration  file is similar to the command line, with the exception that an equal
#        sign '=' must be used between key and value. Example:  -i=p1p2  or  --interface=p1p2  For
#        options with no value (e.g. -v) the equal is also necessary. Example: "-v=" must be used.
#
#
#       -g|--pid-file
#        Specifies the path where the PID (process ID) is saved. This option is ignored when
#        nProbe is controlled with systemd (e.g., service nProbe start).
#
# -G=/var/run/nprobe.pid
#
#       -G|--daemon-mode
#        This parameter causes nProbe to become a daemon, i.e. a task which runs in background
#        without connection to a specific terminal. To use nProbe other than as a casual monitoring
#        tool, you probably will want to use this option. This option is ignored when nProbe is
#        controlled with systemd (e.g., service nProbe start)
#
# -G=
#
#       -i|--interface
#        Specifies the physical network interface that nProbe will use to perform the
#        monitoring. On Unix you can specify the interface name  (e.g. -i lo) whereas on Windows
#        you must use the interface number instead (see -h to see the list of numeric ids).
#        To disable monitoring from physical interfaces (e.g., when nProbe is used in
#        collector-only mode) specify -i=none
#
# -i=none
# -i=eth1
# -i=lo
#--zmq="tcp://10.72.40.150:5556"
-i=ens32

#
#       -n|--collector
#        Specifies the NetFlow collector that will be used by nProbe to send the monitored
#        flows. This option can be specified multiple times to deliver monitored flows to
#        multiple collectors in round-robin mode. To disable flow export to NetFlow collectors
#        specify -n=none
#
# -n=10.0.0.1:2055
-n=none
#
#       -3|--collector-port
# Specifies the port that is being used by a NetFlow exporter to send NetFlow to nProbe.
# Multiple NetFlow exporters can symultaneously send data to nProbe using the same port.
# In case no NetFlow exporter is sending data it is safe to skip this option.
#
# -3=6363
```

**Comment by emanuele-f** [comment]
The configuration is still wrong. Have you followed the guide https://www.ntop.org/nprobe/network-monitoring-101-a-beginners-guide-to-understanding-ntop-tools/ , in particular "Monitoring Netflow/sFlow Traffic"?

You need to:
- into the ntopng configuration, replace the interface parameter with `--interface="tcp://127.0.0.1:5556"`
- remove `-i=ens32`
- add `--collector-port=2055` to the nprobe config
- add `--zmq="tcp://127.0.0.1:5556"` to the nprobe config

**Comment by kwunyinhui** [comment]
It said error when I changed the nprobe configuration.
![image](https://user-images.githubusercontent.com/37438134/39024917-59f12572-4476-11e8-9822-37d2e71bc797.png)

**Comment by emanuele-f** [comment]
You have to stop any running nprobe instances: `killall nprobe`

**Comment by kwunyinhui** [comment]
Thanks, I can change the configuration, but I didnt change to interface IP from 10.72.40.150 to 127.0.0.1. 
Since if I change the interface IP, the traffic history will be disappeared.

However, after changed the config....seems the timestamp is still incorrect.

This is the real time flow record.
![image](https://user-images.githubusercontent.com/37438134/39043559-554a26be-44c0-11e8-94e3-20ab71a9ab69.png)

**Comment by emanuele-f** [comment]
Are nprobe and ntopng running on the same host? Please post the new ntopng and nprobe configuration you are using (possibly enclosed between triple backticks to show it properly on github)

**Comment by simonemainardi** [comment]
check the date and time of the ntopng and nprobe systems. are they in sync?

**Comment by kwunyinhui** [comment]
@emanuele-f  yes, it's running in same host.

ntopng.conf
--interface="tcp://10.72.40.150:5556"
--local-networks="192.168.0.0/16,172.16.0.0/16"
--dns-mode=1
--dump-flows=mysql;localhost;ntopng;flows;root;xxxxxx
-X=1000000
-x=30000

nprobe.conf
--collector-port=2055
--zmq="tcp://10.72.40.150:5556"
-n=none

@simonemainardi 
both systems in the same host, 

[root@LOG nprobe]# clock
Mon 23 Apr 2018 08:35:24 AM HKT  -0.108806 seconds

**Comment by emanuele-f** [comment]
Which ntopng and nprobe version are you using? Can you update to the latest version and recheck the issue?

**Comment by kwunyinhui** [comment]
@emanuele-f I just updated the latest version of below. But seems the issue still here.
ntopng Enterprise Edition v.3.5.180423

![image](https://user-images.githubusercontent.com/37438134/39118406-eca7013c-471b-11e8-8003-2d1f704b8e65.png)

**Comment by kwunyinhui** [comment]
@emanuele-f May I know how can I re-create the database for this case? I am not sure the issue, but I need to fix it ASAP. So Is it possible to re-create the database?

**Comment by emanuele-f** [comment]
Since the timestamp is also wrong in the Flows view, this is not a database issue. The problem is that nprobe is reporting the wrong timestamp (this in turn usually means that your flow exporter is reporting the wrong timestamp). Please send me a pcap of the netflow traffic at faranda@ntop.org . Before sending it, please verify with wireshark that the pcap contains both the netflow template and the netflow data.

**Comment by emanuele-f** [comment]
See #1667 for example for an issue with wrong timestamp

**Comment by kwunyinhui** [comment]
@emanuele-f Thanks! I have sent you the pcap log for your reference, and seems I cannot find the LAST_SWITCHED and FIRST_SWITCHED field in the packets.

**Comment by emanuele-f** [comment]
That's the problem, that fields are missing.

**Comment by kwunyinhui** [comment]
@emanuele-f Thanks. I will check with network team for the setting first.

**Comment by emanuele-f** [comment]
Ok, thank you. Please let me know.

**Comment by kwunyinhui** [comment]
@emanuele-f We can display the logs after added the timestamp command in the Cisco devices. 
Thanks for your help!
