### ISSUE TITLE
Cannot validate license when SystemID changed

### ISSUE THREAD

**Issue by comuelnf** [ntop/ntopng#1738]
Hi ,

we moved several ntop/nprobe VMs from ESxi 5.5 to ESXi 6.5 and systemID changed because vmware hardware version up  from 8 to 10.
I used this URL (https://shop.ntop.org/reset_order_licenses.html) to retire order licenses (NTOP + NPROBE) but i have this message :

"Order found but you have already retired this order 1 times: it is time to place a new order."

Effectively, i used this url one time for one VM but theses orders are linked to 7 licenses and i cannot retry this process for the next 6 VM.

When i try to add command line option "--online-license-check", i get :  "unable to validate Professional license [Invalid response received: data tampered (by HTTP proxy?)]" while these VM are connected directly to internet (no proxy) 

Could you help me, how re-register these new SystemID  (it's not new VMs but VMs moving to new ESxi host).

orderdid : 1516827604 and 1516827623

Best regards,
Damien

**Comment by emanuele-f** [comment]
Please contact us privately for license stuff. http://www.ntop.org/support/need-help-2/contact-us/
