### ISSUE TITLE
High CPU/Memory usage with Microsoft Edge

### ISSUE THREAD

**Issue by fsamareanu** [ntop/ntopng#1740]
Hello,

If you keep a window open for a long time (this one's been open for 2 days) the following happens when using Microsoft Edge:

![image](https://user-images.githubusercontent.com/38040820/38464781-72c0f038-3b24-11e8-809b-2708b6fb5084.png)

ntopng version is 3.3.180408-4258.

Then the window reloads and memory usage goes back to a more reasonable 500MB.

This is a separate window not a new tab.

**Comment by emanuele-f** [comment]
Hi, can you please verify the issue with another browser (firefox/chrome) to see if this is inherent to Microsoft Edge only?

**Comment by fsamareanu** [comment]
It's edge only. Chrome doesn't have the issue.

**Comment by emanuele-f** [comment]
Hi, thank you for your test. On the web I can find many `microsoft edge leak` or `microsoft edge svg leak` posts, I think there is little we can do.

**Comment by fsamareanu** [comment]
Closing this based on previous comment.
