### ISSUE TITLE
nprobe's stop working

### ISSUE THREAD

**Issue by inetactief** [ntop/ntopng#1741]
Hi, 

We use 3.3.180409 - Professional Edition and the nprobe's stop working.  When we start it again, it works but not for long.

We start the 6 nprobe's like this : 
nprobe --zmq "tcp://*:5561" -i none -n none --collector-port 2061 2>&1 >/dev/null &

Best regards,
Michel

**Comment by emanuele-f** [comment]
Hi, please open a new issue here: https://github.com/ntop/nProbe .
Please also specify the operating system used.
