### ISSUE TITLE
ntopng -i bridge:br0,wlan0 ....... Is this possible?

### ISSUE THREAD

**Issue by error420** [ntop/ntopng#1743]
Hello Community. Does anyone know if the following command is possible? "ntopng -i bridge:br0,wlan0" 

Here is the error:
------------------------------------------------------------------------------------------------------
root@RaspberryPi3:/home/pi# ntopng -i bridge:br0,wlan0
11/Apr/2018 17:57:33 [Ntop.cpp:1502] Setting local networks to 127.0.0.0/8
11/Apr/2018 17:57:33 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
11/Apr/2018 17:57:33 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
11/Apr/2018 17:57:33 [NtopPro.cpp:260] [LICENSE] Reading license from Redis
11/Apr/2018 17:57:33 [NtopPro.cpp:342] WARNING: [LICENSE] Invalid or missing license
11/Apr/2018 17:57:33 [NtopPro.cpp:359] WARNING: [LICENSE] ntopng will now run in enterprise edition for 10 minutes
11/Apr/2018 17:57:33 [NtopPro.cpp:361] WARNING: [LICENSE] before returning to community mode
11/Apr/2018 17:57:33 [NtopPro.cpp:363] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
11/Apr/2018 17:57:33 [NtopPro.cpp:365] WARNING: [LICENSE] or run ntopng in community mode starting
11/Apr/2018 17:57:33 [NtopPro.cpp:366] WARNING: [LICENSE] ntopng --community
11/Apr/2018 17:57:34 [PacketBridge.cpp:101] lo has IPv4 address 127.0.0.1
11/Apr/2018 17:57:34 [PacketBridge.cpp:101] wlan0 has IPv4 address 192.168.1.104
11/Apr/2018 17:57:36 [main.cpp:239] ERROR: An exception occurred during interface creation: bridge:br0,wlan0
11/Apr/2018 17:57:36 [main.cpp:289] ERROR: Startup error: missing super-user privileges ?

**Comment by fsamareanu** [comment]
Sorry to poke around but are you trying to bridge a bridge and another interface?

**Comment by error420** [comment]
Yes I am because the bridge shows all traffic going in and out but does not detect my local internal Network.

**Comment by emanuele-f** [comment]
Please explain what are you trying to implement. If you only want to monitor bridge traffic, you can just use `-i br0 -i wlan0`. Is wlan0 an AP maybe?

**Comment by error420** [comment]
That is exactly what I am doing ([Image A](https://ibb.co/jm5fcS)). What I want to implement is traffic monitoring that can see both the br0 AND my wlan0 interface. The current setup only allows me to see internet traffic on either br0 OR wlan0. From br0 interface, no hosts on my internal network are visible (Image B). Br0 = My service provider modem, Router, Raspberry Pi with two NICs, Switch ([Image B](https://ibb.co/njK6HS)). Wlan0 = all devices on my internal network but it will not show what is happening past the Router ([Image C](https://ibb.co/n0WLcS)). What I want to implement is a complete traffic view of what internal devices are connected to what external devices and which is on Youtube or Amazon. This is what my PC traffic looks like after 2 days ([Image D](https://ibb.co/hcDBj7)). Am I being crazy or did I just do this all completely wrong?

**Comment by fsamareanu** [comment]
Is this what you need? My historical data is in a mysql DB:

![image](https://user-images.githubusercontent.com/38040820/38775633-98171dc0-4098-11e8-8d77-f7fe254a5505.png)

**Comment by fsamareanu** [comment]
Steps to get there: Click the graph icon in the host screen, select a different time interval (default is 1 hour I think), go to flows (this will query the DB for historical data), go to IPV4.

**Comment by error420** [comment]
Yes, I want to see the same thing but mine does not have flows tab when I click graph icon [https://ibb.co/jWnaxS](https://ibb.co/jWnaxS)  . Maybe I have wrong version of ntopng? Does it matter which interface I select? br0 or wlan0? I see different information on each one. My wlan0 (local) does not show external servers. My raspberry pi (bridge) and router show all the top traffic. In the attached photo. I set historical graph to 1 week.

**Comment by error420** [comment]
[https://ibb.co/jWnaxS](url)

**Comment by error420** [comment]
The client is always my modem when I monitor br0 and the servers show correctly.
My setup Comcast Modem >>> Br0nic1 >>>RaspberryPi>>>>Br0nic2>>>Router>>>Internal Switch>>>Additional Switch for range.

**Comment by error420** [comment]
This is what my live traffic looks like while streaming amazon from an Amazon fire stick. It does not show the fire stick. Just the remote host and my cable modem. I can't wrap my head around why I cannot see my local IP + Destination connection.

<a href="https://ibb.co/ima647"><img src="https://preview.ibb.co/cMWeP7/igiveup.png" alt="igiveup" border="0"></a>

**Comment by fsamareanu** [comment]
Your setup is different than mine (I use a mirror port on my managed switch from the local interface of the router). That way I see only internet traffic including local ip addresses. Based on your last screenshot you're looking at the post nat interface, correct? To see the local ip addresses select your internal interface from interfaces drop-down.

**Comment by error420** [comment]
Correct. Post NAT in screen shot. Pre-NAT (wlan0) interface only shows local traffic but not their flows. I guess the bridge idea did not work. It seems to me the only way ntopng works is via a switch with span/mirroring/rflow. You cannot create your own bridge and expect to monitor traffic both ways.

**Comment by emanuele-f** [comment]
@error420 so you want to aggregate wlan0 and br0 traffic together. You need to create a view interface, please add `-i view:br0,wlan0`

**Comment by emanuele-f** [comment]
@error420 did the view interface solution work for you?

**Comment by error420** [comment]
I ended up using a different router and flashed it with DD-WRT firmware
that supports rflow. I will try the old method this weekend and report
back. PS: Rflow stops showing hosts after about 10 minutes. Is this because
a community version limit?

**Comment by emanuele-f** [comment]
Use the method which is most suitable for your needs. How are you collecting rflow?

**Comment by error420** [comment]
Good morning Emanuele-f,

Thank you for your guidance. I tried the -i view:br0,wlan0 command but there are no flows or any data being recorded. All I see is a small eye icon next to both interfaces inside the web view. If I remove the "view" command then both interfaces return and show traffic separately but do not connect internal source to external destination.

To answer your question about collecting rflow, here is how I was able to accomplish it::

pi@RaspberryPi3:~ $ /etc/nprobe/nprobe
nprobe.conf        nprobe-none.conf   nprobe-none.start 

Inside my nprobe.conf and nprobe-none.conf :
`--zmq="tcp://*:5556"
--collector-port=2055
-n=none
`-i=none`

The nprobe-none.start file is empty.

Inside my ntopng.conf :
`-=lo
--interface="tcp://127.0.0.1:5556"`

Finally, here is my router setting in DD-WRT:
<a href="https://ibb.co/iUmgGx"><img src="https://image.ibb.co/mREq9H/Screenshot_from_2018_04_21_08_06_39.png" alt="rflow" border="0"></a>

**Comment by emanuele-f** [comment]
Thank you for your explanation. When using the view interface, please make sure you add both the interfaces as -i options, so in your case your configuration should have all these 3 parameters: `-i wlan0 -i br0 -i view:br0,wlan0`

**Comment by error420** [comment]
Thanks your method worked. Does the community version allow blocking of users?

**Comment by emanuele-f** [comment]
Great. Blocking is only supported in the licensed version. Contact us privately for more details.
