### ISSUE TITLE
Reset Licence

### ISSUE THREAD

**Issue by Uzzi** [ntop/ntopng#1744]
Hi I had a debian server with Pro licence.
Now I've changed distro (Centos), I have to refresh licence on new server.
I've tryed, but my order id can generate only one licence.

How can I reactivate my licence on new server?

Regards

**Comment by QuentinBibas** [comment]
you should have one reset available if you didn't use it before.
> https://www.ntop.org/support/faq/how-can-i-move-a-license-to-a-new-server/
have you tried http://shop.ntop.org/reset_order_licenses.html ?

another way could be to try the --online-license-check

**Comment by emanuele-f** [comment]
@QuentinBibas excellent response, thank you!
