### ISSUE TITLE
Ntop Network Interfaces: Realtime Traffic Colours

### ISSUE THREAD

**Issue by Artapel** [ntop/ntopng#1747]
Hi Guys

Is it possible to change the colors of the information on the Ntop Network Interfaces: Realtime Traffic and Network Interfaces: Last Day View.

We are monitoring 4 connections with the colors Light Orange, Dark Orange, Light Blue and Dark Blue.

Due to the fact that we have it on a big display and we all sit a few meters away, it becomes difficult to differentiate the colors. 

Help will be appreciated. Thanks guys.

**Comment by Artapel** [comment]
Any news on this pls guys

**Comment by simonemainardi** [comment]
We are evaluating other libraries for the data visualization. So we cannot accomodate this request at the moment because very likely the current charting library will be replaced. However, we will keep this kind of flexibility in mind in our evaluation. Thanks for the suggestion.
