### ISSUE TITLE
ntopng-mysql dependency

### ISSUE THREAD

**Issue by fsamareanu** [ntop/ntopng#1748]
After integrating ntopng with mysql it seems ntopng starts early during boot process and it fails to connect:

Apr 17 19:10:19 nuc ntopng[1329]: 17/Apr/2018 19:10:19 [MySQLDB.cpp:669] Disconnected from MySQL for interface eno1...
Apr 17 19:10:19 nuc ntopng[1329]: 17/Apr/2018 19:10:19 [MySQLDB.cpp:682] Attempting to connect to MySQL for interface eno1...
Apr 17 19:10:19 nuc ntopng[1329]: 17/Apr/2018 19:10:19 [MySQLDB.cpp:711] ERROR: Failed to connect to MySQL: Can't connect to MySQL server on '192.168.1.7' (101) [ntopng@192.168.1.7:3
306]
Apr 17 19:10:19 nuc ntopng[1329]: [MySQLDB.cpp:711] ERROR: Failed to connect to MySQL: Can't connect to MySQL server on '192.168.1.7' (101) [ntopng@192.168.1.7:3306]
Apr 17 19:10:19 nuc ntopng[1329]: [MySQLDB.cpp:82] ERROR: Unable to connect: Can't connect to MySQL server on '192.168.1.7' (101)
Apr 17 19:10:19 nuc ntopng[1329]: 17/Apr/2018 19:10:19 [MySQLDB.cpp:82] ERROR: Unable to connect: Can't connect to MySQL server on '192.168.1.7' (101)
Apr 17 19:10:19 nuc ntopng[1329]: 17/Apr/2018 19:10:19 [main.cpp:337] ERROR: Unable to create database schema, quitting.
Apr 17 19:10:19 nuc ntopng[1329]: [main.cpp:337] ERROR: Unable to create database schema, quitting.
Apr 17 19:10:19 nuc systemd[1]: ntopng.service: Main process exited, code=exited, status=1/FAILURE
Apr 17 19:10:19 nuc systemd[1]: ntopng.service: Failed with result 'exit-code'.

I'm running latest dev on Ubuntu.

**Comment by fsamareanu** [comment]
Probably not the most elegant way of dealing with this but here's what fixed it:

systemctl edit ntopng (to create an override)
Paste this:

[Unit]
After=network.target syslog.target redis.service pf_ring.service cluster.service mysql.service

Save the file and reboot. ntopng service comes back successfully on reboot.

**Comment by emanuele-f** [comment]
Thank you, I've added after=mysql.server with commit a4d5eea17f79007cb9077c047c9b8bf23f31aa0b
