### ISSUE TITLE
Nprobe - map AS Number to Organisation

### ISSUE THREAD

**Issue by BabuBhatt** [ntop/ntopng#175]
Similar to %L4_DST_PORT_MAP, is it possible to implement a new field (e.g. %AS_DST_NUM_MAP) where nprobe maps a source and/or destination BGP number to the organisation that owns the AS. e.g. 
%SRC_AS  = 714
%SRC_AS_MAP = APPLE-ENGINEERING

The lookup would be the same as using the GeoIPASNum.dat for IP address to country/city mapping

**Comment by lmangani** [comment]
Is this request for nProbe?

**Comment by lucaderi** [comment]
Implemented. Overnight a new package with the extension will be built.
