### ISSUE TITLE
encoding problems influxdb exporter

### ISSUE THREAD

**Issue by zxyz** [ntop/ntopng#1750]
Hello,

Disclaimer: I know it's beta and in development and I'm not asking or expecting help. I just wanted to give feedback to support the  further dev.

I just tested the influxdb export (influx 1.5.2, ntopng 3.2.2 on centos 7.4 with locale settings en_us-utf8).
The data arrives in influxdb but the encoding is not working correctly (eno3 and eno4 are the monitored interfaces):

```
> use ntopng
Using database ntopng
> show measurements
name: measurements
name
----
Aeno3
`�J@eno4
`Ň@eno3
eno3
eno4
�a@eno4
�$�Aeno3
�$�A�$�A�$�A�$�Aeno3
�DAeno4
�D*@eno4
�T\Aeno4
�d1@eno3
�d1@�d1@�d1@�d1@eno3
�dM@eno4
�dg@eno3
�dg@�dg@�dg@�dg@eno3
�d�Aeno3
�d�A�d�A�d�A�d�Aeno3
�t@eno4
�t@�t@eno3
�t}@eno4
��J@eno4
���Aeno4
���A���Aeno3
���@eno3
���@���@���@���@eno3
���Aeno4
���Aeno4
��MAeno3
��MA��MA��MA��MAeno3
��zAeno3
��zA��zA��zA��zAeno3
���Aeno3
���A���A���A���Aeno3
���Aeno4
���@eno4
���@eno4
��CAeno4
�ć@�ć@�ć@�ć@eno3
��Aeno3
��A��A��A��Aeno3
��\@eno3
��\@��\@��\@��\@eno3
���Aeno3
���A���A���A���Aeno3
���Aeno3
���A���A���A���Aeno3
��2Aeno3
��2A��2A��2A��2Aeno3
���Aeno4
���Aeno4``

Thank you.

**Comment by lucaderi** [comment]
@zxyz Thanks for reporting it. Shall you find other issues or have improvements in mind, please let us know. Thank you

**Comment by zxyz** [comment]
thanks @lucaderi!
is the patch already included in "3.4.180420"? if yes, the problem still persists:

```
> show measurements
name: measurements
name
----
eno3
eno4
�4<@eno3
�4<@�4<@�4<@�4<@�4<@�4<@eno3
��S@eno4
��^Aeno4
��^A��^Aeno3
```
If I inspect the measurents  "eno3" and "eno4", there are no encoding 
problems, e. g. in the metric column with "iface:ndpi:YouTube",  "iface:ndpi:Telegram" and so on.

**Comment by emanuele-f** [comment]
@zxyz please check out the newest package

**Comment by zxyz** [comment]
@emanuele-f thanks for your answer. I switched to unstable an with 3.5.180423 the encoding problem is gone. thanks for that!

querying for iterface throughput is fine, e. g. with:
```
SELECT 8 * derivative(mean("bytes.rcvd"),1s) FROM "eno3" WHERE "metric" = 
'iface' AND $timeFilter GROUP BY time($__interval) fill(null)
```
but for graphing the `ndpi ` stuff I have to work around some things:

```
SELECT 8 * derivative(mean("bytes.rcvd"), 1s) FROM "eno3" WHERE  **("metric" 
!~ /^iface$/ AND "metric" !~ /localstats/ AND "metric" !~ /subnetstats/ 
)**AND $timeFilter GROUP BY time($__interval), "metric"
```
with `Alias By = $tag_metric` I get strings like "iface:ndpi:Amazon" in the graph legend, which is not so nice to look at.

I would suggest to restructure the columns a bit. I'm unsure how the column "metric" would look with `nprobe` ("iface:eth0:ndpi:Telnet" or "eth0:ndpi:Telnet"?) due to only using port mirroring atm, so this is just a suggestion from my limited point of view.

For working with data in influxdb it is, from my expierence, good, to seperate information in different colums. So e.g. introducing using one column for the strings "ndpi", "subnets" and "localstats" (...) and another column with the according values "SSH", "192.168.0.0/16" and "local2remote" - lets just call it "metric2" for the moment (I'm lacking a better idea right now),  so that you can format the query like `WHERE "metric2" = 'ndpi'` to only get the information about protocols and in the graph legend only the protocols (without `iface:ndpi:`) would be shown.

Please let me know if the above was understandable :)
 Thanks for your work!

**Comment by emanuele-f** [comment]
Thank you for your feedback! Can you please move this to a new issue so that we can discuss it?

**Comment by zxyz** [comment]
you're absolutely right, sorry for that!
