### ISSUE TITLE
nTopNG Enterprise license is expiring

### ISSUE THREAD

**Issue by juesor** [ntop/ntopng#1752]
19/Apr/2018 12:08:28 [NtopPro.cpp:513] [LICENSE] License:        Not going to paste here but it's valid
19/Apr/2018 12:08:28 [NtopPro.cpp:519] [LICENSE] Validity:        Until Thu Apr 19 12:18:26 2018

Lica, Simone, Emanuele, and Alfredo 

I emailed you all that my enterprise license is now expiring.

Today i expanded the HDD for mariadb to store more data and since restarting ntopng it seems that my license is no longer valid and goes to community after 10 minutes.

**Comment by simonemainardi** [comment]
please, attach the output of:

```
ntopng --version
ntopng --check-license
```

**Comment by juesor** [comment]
v.3.3.180320    [Enterprise/Professional build]
GIT rev:        dev:ae434e327e7497d02976c05a51be64a7841fe140:20180320
Pro rev:        r1522
Built on:       CentOS Linux release 7.4.1708 (Core)
System Id:      68978C0376076B20
Platform:       x86_64
Edition:        Enterprise
License Type:   Demo
Validity:       Until Thu Apr 19 12:45:31 2018
License:        /etc/ntopng.license

Invalid license

**Comment by juesor** [comment]
Like i said i don't know why it is in demo.

I sent you the order id.

**Comment by simonemainardi** [comment]
The system ids we have associated with your purchase are:

```
68978C03550561EF
689E268182072B23
```
We can't find system id  `68978C0376076B20`

Maybe you have multiple CPUs on the same system?

**Comment by juesor** [comment]
We upgraded the hosts at this location.

**Comment by simonemainardi** [comment]
Changing the hardware invalidates the licenses as explained in our FAQs. Please, follow the license transfer instructions available at https://www.ntop.org/support/faq/how-can-i-move-a-license-to-a-new-server/

**Comment by juesor** [comment]
I didn't think of upgrading hosts to do this to ntopng but i guess.

Ok so i found out that  689E268182072B23 is my existing system id that is still working.  

So 68978C03550561EF needs to be retired and replaced with the new system id 68978C0376076B20.

Downside is that i ordered both at the same time and do not see which order id is associated with the.  Can you get me that info in email so i can retire that license?

**Comment by simonemainardi** [comment]
ok, let's follow up via mail.
