### ISSUE TITLE
Add support for Ubuntu 18.04

### ISSUE THREAD

**Issue by fsamareanu** [ntop/ntopng#1753]
Ubuntu 18.04 LTS is around the corner. Can we get builds for it? Currently the 16 LTS builds work if you downgrade libcurl and fix some manual dependencies.

**Comment by emanuele-f** [comment]
Hello, we are working to support the new Ubuntu version. See 5a97bae86f7331659abc80955697ccb26162a096 . The support will be completed in a week.

**Comment by lucaderi** [comment]
packages.ntop.org  has 18.04 packages. Please test them up. Stable packages will be released once we make new packages releases.

**Comment by fsamareanu** [comment]
Confirmed, the 18.04 package works fine so far. Thanks!
