### ISSUE TITLE
No login possible with SSL enabled

### ISSUE THREAD

**Issue by zxyz** [ntop/ntopng#1756]
Hello,

I try to use SSL with the `ntopng` web frontend. I used the approach 
described in the `README.SSL` with some minor modifications:

```
cd /tmp/
sudo mkdir -p /usr/local/share/ntopng/httpdocs/ssl/
openssl req -new -x509 -sha256 -extensions v3_ca -nodes -days 3650 -out 
cert.pem
cat privkey.pem cert.pem > ntopng-cert.pem
sudo mv ntopng-cert.pem /usr/local/share/ntopng/httpdocs/ssl/
sudo chown nobody:nobody 
/usr/local/share/ntopng/httpdocs/ssl/ntopng-cert.pem
sudo chmod o-r /usr/local/share/ntopng/httpdocs/ssl/ntopng-cert.pem
/bin/rm privkey.pem cert.pem
cd /usr/local/bin/
ln -s /usr/lib64/libssl.so .
sudo vim /etc/ntopng/ntopng.conf: + -W 3001
sudo systemctl restart ntopng
```

I can successfully connect to https://example.net:3001 and see the login 
screen. Entering (any) credentials and pressing "Login" the site get 
reloaded but nothing happens (using wrong or right credentials doesn't 
make a difference). There are no error messages  when I set `-v 6`.

After removing `-W 3001`, deleting the link  `/usr/local/bin/libssl.so`, 
the cert and restarting `ntopng` login is still not possible. After 
uninstalling and reinstalling the `ntopng` package login is working again.

I'm using Centos 7.4 and the problem occurs with version 3.5.180423 and 
also with 3.4.180420.

Thanks a lot!

**Comment by emanuele-f** [comment]
Hi, what browser are you using? Do you have browser extensions which may interfere with the login?

**Comment by zxyz** [comment]
I used chromium and firefox. umatrix and ublock_origin were deactivated.
After reinstalling ntopng, without restarting the browser/clearing it's cache or anything like that, login worked again.

**Comment by emanuele-f** [comment]
In order to perform the test, please disable the plugins completely as adding a rule on the site may be not enough.

**Comment by zxyz** [comment]
I tried chromium 65, firefox 59 and even IE 11 all without any plugins. The problem persists.

**Comment by emanuele-f** [comment]
Hi, please try the following.
Uninstall ntopng and reinstall it, then login without ssl. Now just restart ntopng. Can you successfully login now? Now add the -W option and ssl certificate and restart ntopng. Can you login? Now remove the -W option and restart ntopng can you login?

Now after these steps, please post your full ntopng log (without the -v option).

**Comment by zxyz** [comment]
>Uninstall ntopng and reinstall it, then login without ssl. Now just restart ntopng. Can you successfully login now? 

yes

> Now add the -W option and ssl certificate and restart ntopng. Can you login? 

No

> Now remove the -W option and restart ntopng can you login?

No

Logs (`sudo journalctl --unit=ntopng`): 
https://paste.systemli.org/?f3899ee6759cab8e#1WJkBLwtDyWkgMTi7aHmQZVptjHC6GevGZ0QQws9rmg=

**Comment by emanuele-f** [comment]
Hello, your ntopng share directory is probably located into `/usr/share/ntopng`. You should use it instead of `/usr/local/share/ntopng`. Please remove the manually created directory with `rm -rf /usr/local/share/ntopng` (I've updated the readme to clarify this)

**Comment by zxyz** [comment]
that did it! thanks @emanuele-f for your help!
