### ISSUE TITLE
[discussion] structure of data exported to influxdb

### ISSUE THREAD

**Issue by zxyz** [ntop/ntopng#1757]
Exporting to Influxdb with ntopng 3.5 works fine. Querying for iterface throughput e. g. with:

```
SELECT 8 * derivative(mean("bytes.rcvd"),1s) FROM "eno3" WHERE "metric" = 
'iface' AND $timeFilter GROUP BY time($__interval) fill(null)
```

is great, but for graphing the ndpi stuff I have to work around some things:

```
SELECT 8 * derivative(mean("bytes.rcvd"), 1s) FROM "eno3" WHERE  **("metric" 
!~ /^iface$/ AND "metric" !~ /localstats/ AND "metric" !~ /subnetstats/ 
)**AND $timeFilter GROUP BY time($__interval), "metric"
```

and with `Alias By $tag_metric` I get strings like "iface:ndpi:Amazon" in the graph legend, which is not so nice to look at.

I would suggest to restructure the columns a bit. I'm unsure how the column "metric" would look with nprobe ("iface:eth0:ndpi:Telnet" or "eth0:ndpi:Telnet"?) due to only using port mirroring atm, so this is just a suggestion from my limited point of view.

For working with data in influxdb it is, from my expierence, good, to seperate information in different colums. So e. g. introducing using one column for the strings "ndpi", "subnets" and "localstats" (...) and another column with the according values "SSH", "192.168.0.0/16" and "local2remote" - lets just call it "metric2" for the moment (I'm lacking a better idea right now), so that you can format the query like WHERE `"metric2" = 'ndpi'` to only get the information about protocols and in the graph legend only the protocols (without iface:ndpi:) would be shown.

Please let me know if the above was understandable :)
Thanks for your work!

**Comment by lucaderi** [comment]
Hi @zxyz sorry for the late reply. Your suggestions are welcome and they are worth to be analysed. All the export to InfluxDB is via  ntop.tsSet. Namely

rrd_5min_dump_utils.lua:  ntop.tsSet(when, 'ip', hostname, "bytes", tolongint(host["bytes.sent"]), tolongint(host["bytes.rcvd"]))
rrd_5min_dump_utils.lua:      ntop.tsSet(when, 'ip', hostname, tostring(k), tolongint(host[k..".bytes.sent"]), tolongint(host[k..".bytes.rcvd"]))
rrd_5min_dump_utils.lua:    ntop.tsSet(when, 'ip:ndpi', hostname, tostring(k),
rrd_5min_dump_utils.lua:    ntop.tsSet(when, 'ip:ndpi_categories', hostname, tostring(k), tolongint(cat["bytes"]), 0)
rrd_5min_dump_utils.lua:    ntop.tsSet(when, 'mac:ndpi_categories', devicename, k, tolongint(cat["bytes"]), 0)
rrd_5min_dump_utils.lua:  ntop.tsSet(when, 'mac', devicename, "bytes", tolongint(device["bytes.sent"]), tolongint(device["bytes.rcvd"]))
rrd_5min_dump_utils.lua:    ntop.tsSet(when, 'asn', tostring(asn), "bytes",
rrd_5min_dump_utils.lua:        ntop.tsSet(when, 'asn:ndpi', tostring(asn), proto_name,
rrd_5min_dump_utils.lua:    ntop.tsSet(when, "iface:countrystats", country, "bytes", tolongint(country_stats["egress"]), tolongint(country_stats["inner"]))
rrd_5min_dump_utils.lua:      ntop.tsSet(when, 'vlan', tostring(vlan_id), "bytes",
rrd_5min_dump_utils.lua:          ntop.tsSet(when, 'vlan:ndpi', tostring(vlan_id), proto_name,
rrd_5min_dump_utils.lua:      ntop.tsSet(when, "sflow", flow_device_ip, "bytes",
rrd_5min_dump_utils.lua:      ntop.tsSet(when, "flow_device", flow_device_ip, "bytes",
rrd_min_dump_utils.lua:    ntop.tsSet(when, 'iface:ndpi', tostring(k), "bytes", ifstats["ndpi"][k]["bytes.sent"], ifstats["ndpi"][k]["bytes.rcvd"])
rrd_min_dump_utils.lua:    ntop.tsSet(when, 'iface:ndpi_categories', tostring(k), "bytes", v, 0)
rrd_min_dump_utils.lua:  ntop.tsSet(when, "iface:localstats", "local2remote", "bytes",
rrd_min_dump_utils.lua:    ntop.tsSet(when, "iface:subnetstats", subnet, "bytes", tolongint(sstats["egress"]), tolongint(sstats["inner"]))
rrd_min_dump_utils.lua:    ntop.tsSet(when, "iface:subnetstats", subnet, "broadcast_bytes", tolongint(sstats["broadcast"]["ingress"]), tolongint(sstats["broadcast"]["egress"]))
rrd_min_dump_utils.lua:    ntop.tsSet(when, 'profilestats', pname, "bytes", tolongint(ptraffic), 0)
rrd_utils.lua:   ntop.tsSet(when, "iface", nil, rrdname, 0, tonumber(value))

Can you please send me a short patch that includes your suggestion?

**Comment by zxyz** [comment]
I'm sorry @lucaderi , but I'm not able to provide a patch. But I try to make my point more clear using you above code. 

If I understand the above correctly, e. g. `iface:ndpi` `iface:ndpi_categories` `iface:localstats` `iface:subnetstats` all go into the column named `metric`. My suggestion is to seperate e. g. `iface` from everything after the `:` and put the later in another column. 
so instead of:

```
metric
-------
iface:localstats
iface:subnetstats
iface:ndpi
```
more like the following:
```
metric1            metric2
--------           ---------
iface              localstats
iface              subnetstats
iface              ndpi
```
I don't have access to my ntong installation atm, but can have a more detailed look on tuesday to improve my example.

**Comment by emanuele-f** [comment]
Hello, here is the current ntopng Influx model:
```
MEASUREMENT: wlan0
  TAGS:
    metric:   iface:ndpi:AppleiCloud, iface:ndpi:DHCP, ..., ip:192.168.1.2
  FIELDS:
    broadcast_bytes.rcvd, bytes.sent, num_flows.rcvd
```
there is only a single tag "metrics" and multple values `iface:ndpi:AppleiCloud`, `iface:ndpi:DHCP`, ...  Here is a sample query: `SELECT * FROM wlan0 WHERE metric = 'iface:ndpi:AppleiCloud'`. This is not flexible as we cannot filter by application.

Here is my proposal for the new model:
```
  MEASUREMENT: interface_traffic
  TAGS:
    ifname: wlan0
  FIELDS:
    bytes.sent, num_flows.rcvd, ...

  MEASUREMENT: host_traffic
  TAGS:
    ifname: wlan0
    host: 192.168.1.1
  fields:
    bytes.sent, num_flows.rcvd, ...

  MEASUREMENT: host_ndpi_traffic
  TAGS:
    ifname: wlan0
    host: 192.168.1.1
    application: ApppleiCloud
  FIELDS:
    bytes.sent, bytes.rcvd=20, ...

...
```
This model is way more flexible. It allows us to filter by specific tags values and measurements. Here is an example of insertion an query:
```
INSERT host_ndpi_traffic,ifname=wlan0,host=192.168.1.1,application=ApppleiCloud bytes.sent=10,bytes.rcvd=20

SELECT * host_ndpi_traffic WHERE ifname = 'wlan0' AND host = '192.168.1.1' AND application = 'ApppleiCloud'

  time			application	bytes.rcvd	bytes.sent	host		ifname
  1526908024582146071	ApppleiCloud	20		10		192.168.1.1	wlan0
```

**Comment by zxyz** [comment]
@emanuele-f  thanks a lot, this looks really promising!

**Comment by emanuele-f** [comment]
A new schema (similar to the one described above) is now implemented with commit 42083f1865c1804d38be228fc2e89a4261efc3cb . Please check it out.

**Comment by zxyz** [comment]
sorry, took me a while to find time to test this. 
I'm really satisfied with this, thanks a lot!

**Comment by emanuele-f** [comment]
Thank you for the feedback
