### ISSUE TITLE
Snmp devices issue

### ISSUE THREAD

**Issue by fsamareanu** [ntop/ntopng#1759]
Hello,

Devices -> SNMP -> Click the graph icon next to any device produces an error:

Apr 25 15:01:03 nuc ntopng[10322]: 25/Apr/2018 15:01:03 [Lua.cpp:8026] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/snmpdevices_stats.lua][.../ntopng/scripts/lua/pro/enterprise/snmpdevices_stats.lua:136: attempt to concatenate field 'host' (a nil value)]
Apr 25 15:01:03 nuc ntopng: [Lua.cpp:8026] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/snmpdevices_stats.lua][.../ntopng/scripts/lua/pro/enterprise/snmpdevices_stats.lua:136: attempt to concatenate field 'host' (a nil value)]

Latest DEV:
ii  ntopng                                     3.5.180425-4347                              amd64        Web-based traffic monitoring.
ii  ntopng-data                                3.5.180425                                   all          Data files (geoip) for ntopng.

![image](https://user-images.githubusercontent.com/38040820/39242014-aa02193c-4899-11e8-8bfd-6b957a4bc014.png)

**Comment by emanuele-f** [comment]
@fsamareanu thank you for reporting, we are currently reworking SNMP support, so expect bugs to come out :)

**Comment by emanuele-f** [comment]
Can you still reproduce it? It does not on my system.

**Comment by fsamareanu** [comment]
Nope, this is fixed.
