### ISSUE TITLE
Unable to start bridge mode

### ISSUE THREAD

**Issue by Per-Forma** [ntop/ntopng#1760]
I've been banging my head on this for a couple of days and I don't know where I'm going wrong. I am trying to demo the community edition of ntopng on a VM to determine if it can be used as a suitable alternative for our current monitoring solution.

I can start it up in single interface monitoring mode without any problems. But when I try to start in bridge mode I get an error of `ERROR: An exception occurred during interface creation: bridge:eth1,eth2`

I've pasted all the relevant info I can think of below. Any guidance would be appreciated!

Here is the command I'm using _with verbose output added_
`$ sudo ./ntopng -i bridge:eth1,eth2 -v 6`

Here is what I get back:
```
26/Apr/2018 09:13:20 [Ntop.cpp:1499] Setting local networks to 127.0.0.0/8
26/Apr/2018 09:13:20 [Utils.cpp:2409] Rule 127.0.0.0/8
26/Apr/2018 09:13:20 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
26/Apr/2018 09:13:20 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
26/Apr/2018 09:13:20 [Ntop.cpp:352] Interfaces Available: 32
26/Apr/2018 09:13:20 [ThreadedActivity.cpp:147] Running /usr/src/ntopng/scripts/callbacks/system/boot.lua (iface=(nil))
26/Apr/2018 09:13:20 [Lua.cpp:5124] ntop_get_dirs() called
26/Apr/2018 09:13:20 [Lua.cpp:6017] ntop_get_redis() called
26/Apr/2018 09:13:20 [Lua.cpp:5124] ntop_get_dirs() called
26/Apr/2018 09:13:20 [Lua.cpp:5124] ntop_get_dirs() called
26/Apr/2018 09:13:20 [Lua.cpp:5124] ntop_get_dirs() called
26/Apr/2018 09:13:20 [Lua.cpp:5179] ntop_get_info() called
26/Apr/2018 09:13:20 [Lua.cpp:4840] ntop_is_pro() called
26/Apr/2018 09:13:20 [Lua.cpp:4840] ntop_is_pro() called
26/Apr/2018 09:13:20 [Lua.cpp:4848] ntop_is_enterprise() called
26/Apr/2018 09:13:20 [Lua.cpp:5124] ntop_get_dirs() called
26/Apr/2018 09:13:20 [Lua.cpp:1422] ntop_is_windows() called
26/Apr/2018 09:13:20 [Lua.cpp:4840] ntop_is_pro() called
26/Apr/2018 09:13:20 [main.cpp:172] System has 4 CPU cores
26/Apr/2018 09:13:21 [Utils.cpp:2001] Interface eth2 has MAC Speed = 10000
26/Apr/2018 09:13:21 [Utils.cpp:1934] Unable to read MTU for device bridge:eth1,eth2
26/Apr/2018 09:13:21 [HostPools.cpp:84] Host Pools Available: 4
26/Apr/2018 09:13:21 [main.cpp:239] ERROR: An exception occurred during interface creation: bridge:eth1,eth2
26/Apr/2018 09:13:21 [main.cpp:289] ERROR: Startup error: missing super-user privileges ?
```

Version:
`$ ntopng -V`
`v.3.5.180425	[Community build]`
`GIT rev:	dev:a850860b2c169129432bb88d2c2219d16fc6315a:20180425`

Interfaces Config:
```
$ cat /etc/network/interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet dhcp

auto eth1
iface eth1 inet manual
up ifconfig eth1 up

auto eth2
iface eth2 inet manual
ip ifconfig eth2 up
```

OS Version:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

**Comment by emanuele-f** [comment]
Bridge support is not available in the community edition (which is free, you don't even need a demo for it). Please install our pre-build binaries from http://packages.ntop.org/ to test the bridge (in 10 minutes demo, or alternatively contact us to provide a free limited time licence). You can see a comparison of the ntopng features available in the different versions in this page: https://www.ntop.org/products/traffic-analysis/ntop/

**Comment by Per-Forma** [comment]
Well I’m glad then that I wasn’t being as dense as I was afraid of. I was really thinking I was missing something. I have since installed from the apt repos listed on the packages sub domain. Who do I get in touch with to discuss a longer trial license? I also have a couple of other questions regarding shaping policies.

**Comment by emanuele-f** [comment]
You can get in touch with us by using the form in the following page: http://www.ntop.org/support/need-help-2/contact-us/

**Comment by Per-Forma** [comment]
Hey @emanuele-f I've tried to send a couple of messages through the website and to the provided email addresses. I haven't received any response as of yet.

We are an educational agency, but seeing as how ntopng might save us a substantial amount of capital, I want to have a discussion about licensing and potential development of specific features!
