### ISSUE TITLE
nprobe stops when 1 year up

### ISSUE THREAD

**Issue by JasonEde** [ntop/ntopng#1762]
We bought nprobe/ntop a year ago and now when I look it says that upgrades have expired in ntopng but it still runs. On nprobe it says that it's an invalid license.

27/Apr/2018 12:11:54 [nprobe.c:3913] ERROR: Invalid nProbe license (/etc/nprobe.license) [License mismatch error]
27/Apr/2018 12:11:54 [nprobe.c:3920] ERROR: *****************************************************
27/Apr/2018 12:11:54 [nprobe.c:3921] ERROR: **                                                 **
27/Apr/2018 12:11:54 [nprobe.c:3922] ERROR: **  Switching to DEMO MODE (missing valid license) **
27/Apr/2018 12:11:54 [nprobe.c:3923] ERROR: **                                                 **
27/Apr/2018 12:11:54 [nprobe.c:3924] ERROR: **  Purchase your nProbe license at                **
27/Apr/2018 12:11:54 [nprobe.c:3925] ERROR: **       https://shop.ntop.org/                    **
27/Apr/2018 12:11:54 [nprobe.c:3926] ERROR: **                                                 **

I am using the online license check. I thought the license was perpetual, but upgrades were only guaranteed for one year?
Jason

**Comment by emanuele-f** [comment]
Please contact us privately for license issues http://www.ntop.org/support/need-help-2/contact-us/ .
