### ISSUE TITLE
NTOPNG Alerts

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#1765]
Hi everyone here i need some help for explaining something.

I recently set up NTOPNG to send alerts to my iPhone via Slack and i get lots of alerts now. If someone could please answer my questions that would be awesome but i really just wanna know what the alerts mean.

(I have changed the IP addresses for security reasons)

blacklisted host **externalIPaddress** contacted host **myserver**[TCP **externalIPaddress**:10805 > **myserver**:1723 [proto: 0.0/Unknown][device: 0 in: 0 out:0][1/1 pkts][60/54 bytes][SYN ACK RST]]

Is a blacklisted host alert like this something i should be worried about? Is the secitry of my network compromised too? 

I also recieve alerts about TCP connections such as:

TCP connection refused: **myserver** > **computeronmynetwork** [TCP **myserver**:50760 > **computeronmynetwork**:445 [proto: 0.0/Unknown][device: 0 in: 0 out:0][3/2 pkts][186/126 bytes][SYN ACK FIN RST]]

I get TCP connction refused very often, are they something i should be worried about too? 

Thanks guys,
Daniel2029

**Comment by emanuele-f** [comment]
Hi, the `1723` is usually used for PPTP. Apart from the fact that PPTP is generally considered unsecure, malicious hosts continuosly scan the internet on known ports for known vulnerabilities. This usually does not necessarily mean that the security of the network is compromised, but of course raises the risk for a successfull attack. A good practice is to avoid using standard ports to protect from automated mass scanning.

The TCP connection refused you get has as the target host a "computeronmynetwork". An application on "myserver" is trying to contact "computeronmynetwork" on port 445 but there is no application listening on port 445. Again, this is generally not a threat, but to understand why it happens you should figure out which app in "myserver" is opening the connection. A new tool to extract such information on linux is ebpf. The following script, for example, traces connection attempts: https://github.com/iovisor/bcc/blob/master/tools/tcpconnect.py . In the future, we sould like to extend ntopng to provide such insights.

**Comment by ghost** [comment]
Thank you for your help!

Kindest regards,
Daniel2029
