### ISSUE TITLE
raspbian stretch repo seems to be broken

### ISSUE THREAD

**Issue by tobiasdam** [ntop/ntopng#1767]
I tried to install a stable version of ntopng on Raspbian Stretch using the repository http://packages.ntop.org/apt-stable/stretch_pi/, but it does not contain any packages.

Also, the other raspberry repositories seem to have problems as well:
- The packages inside the development repo http://packages.ntop.org/apt/stretch_pi/ are outdated
- http://packages.ntop.org/RaspberryPI/stretch_pi/armhf/ does not contain `Packages`, `InRelease` and `Release` files, while http://packages.ntop.org/RaspberryPI/stretch_pi/all does contain those files

Not really important, but I noticed that there is no 3.4 Stable release on the Github releases page.

**Comment by emanuele-f** [comment]
Hello, for raspberry builds please refer to http://packages.ntop.org/RaspberryPI . The new version build is currently missing but we will provide it soon.

**Comment by tobiasdam** [comment]
This repository does not work as an apt repository , because http://packages.ntop.org/RaspberryPI/stretch_pi/armhf/ does not contain all necessary files (`Release`, ...). 

The description inside the repo states that http://apt.ntop.org/stretch_pi should be used as repository, which is a development repository according to the description inside that repo.

**Comment by emanuele-f** [comment]
Which description are you referring to? By following the instructions at RaspberryPI the developlment version is now installed. If that's not desired, please manually install the package from http://packages.ntop.org/RaspberryPI/stretch_pi/armhf/ntopng/

**Comment by tobiasdam** [comment]
I was referring to  the instructions at RaspberryPI. 

Okay, does that mean my following assumptions are correct?
- http://packages.ntop.org/RaspberryPI is not intended to work directly als repo with apt.
- The stable repository http://packages.ntop.org/apt-stable/stretch_pi/ is not maintained any longer.

**Comment by emanuele-f** [comment]
Correct. The only supported installation modes are described into the instructions.
