### ISSUE TITLE
I have to manually refresh ntopng flows page?

### ISSUE THREAD

**Issue by pleoeter** [ntop/ntopng#1768]
Every time I need to manually refresh the ntopng code , can you please tell me how to auto update it?

**Comment by emanuele-f** [comment]
Hello, the flows view works this way, it only shows refreshes the already active flows. Maybe we can add such a realtime view in a new dashboard as a customized panel

**Comment by pleoeter** [comment]
In which view and how can we automatically update the traffic?

**Comment by emanuele-f** [comment]
Currently it's not available
