### ISSUE TITLE
ntopng - ubiquity package - Segmentation fault

### ISSUE THREAD

**Issue by LionHear7** [ntop/ntopng#177]
I've installed the latest package 'ntopng_2.0.150805-374_mips.deb' on EdgeOS version 1.7
but after few minutes I get a segfault.

Here the log:
08/Sep/2015 09:53:27 [src/Redis.cpp:104] Successfully connected to redis 127.0.0.1:6379@0
08/Sep/2015 09:53:27 [pro/NtopPro.cpp:141] ERROR: [LICENSE] Invalid or missing ntopng License [Empty license file]
08/Sep/2015 09:53:27 [pro/NtopPro.cpp:154] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
08/Sep/2015 09:53:27 [pro/NtopPro.cpp:156] WARNING: [LICENSE] before returning to community mode
08/Sep/2015 09:53:27 [pro/NtopPro.cpp:157] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
08/Sep/2015 09:53:27 [pro/NtopPro.cpp:158] WARNING: [LICENSE] or run ntopng in community mode starting
08/Sep/2015 09:53:27 [pro/NtopPro.cpp:159] WARNING: [LICENSE] ntopng --community
08/Sep/2015 09:53:27 [src/Ntop.cpp:1053] Registered interface view bridge:eth0,eth2 [id: 0]
08/Sep/2015 09:53:27 [src/Ntop.cpp:1023] Registered interface bridge:eth0,eth2 [id: 0]
08/Sep/2015 09:53:27 [src/Utils.cpp:298] User changed to nobody
08/Sep/2015 09:53:27 [src/main.cpp:238] PID stored in file /var/tmp/ntopng.pid
Error Opening file /usr/share/ntopng/httpdocs/geoip/GeoIPASNum.dat
08/Sep/2015 09:53:27 [src/Geolocation.cpp:59] WARNING: Unable to read GeoIP database /usr/share/ntopng/httpdocs/geoip/GeoIPASNum.dat
Error Opening file /usr/share/ntopng/httpdocs/geoip/GeoIPASNumv6.dat
08/Sep/2015 09:53:27 [src/Geolocation.cpp:59] WARNING: Unable to read GeoIP database /usr/share/ntopng/httpdocs/geoip/GeoIPASNumv6.dat
Error Opening file /usr/share/ntopng/httpdocs/geoip/GeoLiteCity.dat
08/Sep/2015 09:53:27 [src/Geolocation.cpp:59] WARNING: Unable to read GeoIP database /usr/share/ntopng/httpdocs/geoip/GeoLiteCity.dat
Error Opening file /usr/share/ntopng/httpdocs/geoip/GeoLiteCityv6.dat
08/Sep/2015 09:53:27 [src/Geolocation.cpp:59] WARNING: Unable to read GeoIP database /usr/share/ntopng/httpdocs/geoip/GeoLiteCityv6.dat
08/Sep/2015 09:53:27 [src/HTTPserver.cpp:449] HTTPS Disabled: missing SSL certificate /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem
08/Sep/2015 09:53:27 [src/HTTPserver.cpp:451] Please read https://svn.ntop.org/svn/ntop/trunk/ntopng/README.SSL if you want to enable SSL.
08/Sep/2015 09:53:27 [src/HTTPserver.cpp:492] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
08/Sep/2015 09:53:27 [src/HTTPserver.cpp:495] HTTP server listening on port 3000
08/Sep/2015 09:53:27 [src/main.cpp:289] Working directory: /var/tmp/ntopng
08/Sep/2015 09:53:27 [src/main.cpp:291] Scripts/HTML pages directory: /usr/share/ntopng
08/Sep/2015 09:53:27 [src/Ntop.cpp:287] Welcome to ntopng mips64 v.2.0.150805 - (C) 1998-15 ntop.org
08/Sep/2015 09:53:27 [src/PeriodicActivities.cpp:53] Started periodic activities loop...
08/Sep/2015 09:53:27 [src/RuntimePrefs.cpp:32] Dumping alerts into syslog
08/Sep/2015 09:53:27 [pro/NtopPro.cpp:212] [LICENSE] ntopng systemId: E8F4740F4992
08/Sep/2015 09:53:27 [pro/NtopPro.cpp:217] [LICENSE] ntopng is starting in demo mode
08/Sep/2015 09:53:27 [src/NetworkInterface.cpp:1350] Started packet polling on interface bridge:eth0,eth2 [id: 0]...
08/Sep/2015 09:53:27 [pro/PacketBridge.cpp:225] Started packet bridge polling for bridge:eth0,eth2
08/Sep/2015 09:53:29 [src/Ntop.cpp:866] ERROR: Unable to find interface view Id 2
08/Sep/2015 09:53:34 [src/Ntop.cpp:866] ERROR: Unable to find interface view Id 2
08/Sep/2015 09:53:39 [src/Ntop.cpp:866] ERROR: Unable to find interface view Id 2
08/Sep/2015 09:53:44 [src/Ntop.cpp:866] ERROR: Unable to find interface view Id 2
08/Sep/2015 09:53:49 [src/Ntop.cpp:866] ERROR: Unable to find interface view Id 2
08/Sep/2015 09:53:54 [src/Ntop.cpp:866] ERROR: Unable to find interface view Id 2
08/Sep/2015 09:53:59 [src/Ntop.cpp:866] ERROR: Unable to find interface view Id 2
08/Sep/2015 09:54:04 [src/Ntop.cpp:866] ERROR: Unable to find interface view Id 2
08/Sep/2015 09:54:09 [src/Ntop.cpp:866] ERROR: Unable to find interface view Id 2
08/Sep/2015 09:54:14 [src/Ntop.cpp:866] ERROR: Unable to find interface view Id 2
08/Sep/2015 09:54:19 [src/Ntop.cpp:866] ERROR: Unable to find interface view Id 2
08/Sep/2015 09:54:24 [src/Ntop.cpp:866] ERROR: Unable to find interface view Id 2
08/Sep/2015 09:54:29 [src/Ntop.cpp:866] ERROR: Unable to find interface view Id 2
08/Sep/2015 09:54:34 [src/Ntop.cpp:866] ERROR: Unable to find interface view Id 2
08/Sep/2015 09:54:39 [src/Ntop.cpp:866] ERROR: Unable to find interface view Id 2
08/Sep/2015 09:54:44 [src/Ntop.cpp:866] ERROR: Unable to find interface view Id 2
Segmentation fault

**Comment by lmangani** [comment]
@LionHear7 do you have a core file for debugging the problem?

**Comment by lucaderi** [comment]
I need to make a new build as this is an old development version.

**Comment by LionHear7** [comment]
Sorry, but it didn't generate the core dump. 
I'll wait for a new build, Thanks!

**Comment by jaburgeson** [comment]
Any idea when the new build will be out.  I am having the same issue and it is pretty annoying.

**Comment by lucaderi** [comment]
The new packages are out: please give them a try.

**Comment by jaburgeson** [comment]
Hi Luca,  gave the packages a try last night and it is a lot better but it still occasionally will error with a Seg Fault.

What would you like from me to add to this to help resolve or is it a Edge Router limitation with Ram and CPU resources?
