### ISSUE TITLE
Grafana NTOPNG Plugin - Access Server

### ISSUE THREAD

**Issue by darox** [ntop/ntopng#1772]
The Access option - Server seems to be broken in the grafana NTOPNG plugin. 
If I set the Access to Server, I get the following error:
HTTP Error Bad Gateway
However, curl from within the grafana container to the URL endpoint works.

**Comment by radixtenshi** [comment]
Same here... i just cant make it work, Any chance for a more detailed guide on that topic?

**Comment by simonemainardi** [comment]
can you post the exact steps to reproduce?

**Comment by darox** [comment]
1. Setup NTOPNG plugin in Grafana
2. Set Access to Browser and check if the plugin is working at all if yes, continue to setp 3. otherwise troubleshoot the problem
3. Set Access to Server and check if the plugin is working, for me it's not.

Let me know if you need more information. 

The main problem with this behavior is, that if you're located in a different IP subnet, no data can be shown for the NTOPNG  plugin, which is logical as the Access is set to browser and not Server. In a way, it's also a security issue, if no TLS is used for NTOPNG.

**Comment by simonemainardi** [comment]
I get
![image](https://user-images.githubusercontent.com/3397663/40788660-ddd83e9e-64f0-11e8-8f73-20eabbc99f5f.png)

![image](https://user-images.githubusercontent.com/3397663/40788709-f465e92c-64f0-11e8-9432-fa78e195d5fe.png)


with
```
simone@devel:~/go/src/github.com/grafana/grafana$ ./bin/grafana-server
INFO[05-31|16:35:34] Starting Grafana                         logger=server version=5.1.0-pre1 commit=93e1546 compiled=2018-04-10T22:22:12+0200
INFO[05-31|16:35:34] Config loaded from                       logger=settings file=/home/simone/go/src/github.com/grafana/grafana/conf/defaults.ini
INFO[05-31|16:35:34] Path Home                                logger=settings path=/home/simone/go/src/github.com/grafana/grafana
INFO[05-31|16:35:34] Path Data                                logger=settings path=/home/simone/go/src/github.com/grafana/grafana/data
```

Can you please check if the url has a trailing slash? I get the error if I remove the last slash.

**Comment by darox** [comment]
My URL looks like this https://192.168.2.1:3000/lua/modules/grafana/ it's NTOPNG on pfsense. Is your grafana and ntopng instance on the same host?

**Comment by lucaderi** [comment]
@simonemainardi Any update?

**Comment by simonemainardi** [comment]
@darox what is the ntopng version you are using? type 

ntopng --version

I guess you're using an outdated version

**Comment by darox** [comment]
@simonemainardi I'm using ntopng Community Edition v.3.2.180413 on Pfsense, unfortunately, there's not a newer version...

**Comment by simonemainardi** [comment]
@darox our official stable release is version 3.4. Version 3.2 is outdated. Please, upgrade (or follow up with the pfsense folks to have it updated), make sure to have version 3.4, and the reopen if necessary.

In version 3.6 stable we may also decide to drop the grafana datasource plugin in favour of influxdb. Indeed, we've currently implemented influxdb timeseries export support so one can directly use the influxdb grafana datasource directly. See https://github.com/ntop/ntopng/blob/dev/doc/README.influxdb. Official announcement will be made.

**Comment by darox** [comment]
@simonemainardi Thanks for the statement. I'll try to get the Influxb support running on Pfsense. I guess it's not supported on 3.2 right?

**Comment by simonemainardi** [comment]
@darox influxdb support is in version 3.5 dev and will come in 3.6 stable.

**Comment by darox** [comment]
@simonemainardi Okey, I'll deploy a test instance of 3.5.

**Comment by darox** [comment]
@simonemainardi Is there a 3.5 docker image available?

**Comment by simonemainardi** [comment]
will be uploaded shortly at https://hub.docker.com/r/ntop/

**Comment by darox** [comment]
@simonemainardi Seems you just uploaded the 3.4 stable version instead of 3.5. Or I'm missing the tag?

**Comment by simonemainardi** [comment]
@cardigliano can you please tell @darox how to use docker 3.5.

**Comment by cardigliano** [comment]
@darox ntopng stable is currently available as image on Docker Hub, dev will be added soon as we need to setup auto build, in the meanwhile please follow the instructions at https://github.com/ntop/docker-ntop using Dockerfile.ntopng.dev

**Comment by darox** [comment]
@cardigliano Thanks!
