### ISSUE TITLE
Ntopng shuts down alone since last update.

### ISSUE THREAD

**Issue by shadarthuro** [ntop/ntopng#1773]
Hello everyone, Ntopng shuts down alone since last update.

● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled)
   Active: inactive (dead) since lun. 2018-05-07 09:44:44 CEST; 5min ago
  Process: 2195 ExecStopPost=/bin/rm -rf /run/ntopng.conf (code=exited, status=0/SUCCESS)
  Process: 1793 ExecStart=/usr/local/bin/ntopng /run/ntopng.conf (code=exited, status=0/SUCCESS)
  Process: 1790 ExecStartPre=/bin/sh -c /bin/sed "/-e.*$\|-G.*\|--daemon.*\|--pid.*/s/^/#/" /etc/ntopng/ntopng.conf > /run/ntopng.conf (code=exited, status=0/SUCCESS)
 Main PID: 1793 (code=exited, status=0/SUCCESS)

mai 07 09:34:02 FRCOSNTOPNG ntopng[1793]: 07/May/2018 09:34:01 [Redis.cpp:1366] ERROR: ERR wrong number of arguments for 'restore' command [RESTORE ntopng.p...ts_config]
mai 07 09:34:02 FRCOSNTOPNG ntopng[1793]: 07/May/2018 09:34:01 [Redis.cpp:1366] ERROR: ERR wrong number of arguments for 'restore' command [RESTORE ntopng.p...:A8:AB:57]
mai 07 09:34:02 FRCOSNTOPNG ntopng[1793]: 07/May/2018 09:34:01 [Redis.cpp:1366] ERROR: ERR wrong number of arguments for 'restore' command [RESTORE ntopng.p...:22:E6:1C]
mai 07 09:34:02 FRCOSNTOPNG ntopng[1793]: 07/May/2018 09:34:01 [Redis.cpp:1366] ERROR: ERR wrong number of arguments for 'restore' command [RESTORE ntopng.p...ts_config]
mai 07 09:34:02 FRCOSNTOPNG ntopng[1793]: 07/May/2018 09:34:01 [Redis.cpp:1366] ERROR: ERR wrong number of arguments for 'restore' command [RESTORE ntopng.p...ts_config]
mai 07 09:34:02 FRCOSNTOPNG ntopng[1793]: 07/May/2018 09:34:01 [Redis.cpp:1366] ERROR: ERR wrong number of arguments for 'restore' command [RESTORE ntopng.p...ts_config]
mai 07 09:34:02 FRCOSNTOPNG ntopng[1793]: 07/May/2018 09:34:01 [Redis.cpp:1366] ERROR: ERR wrong number of arguments for 'restore' command [RESTORE ntopng.p...ts_config]
mai 07 09:34:02 FRCOSNTOPNG ntopng[1793]: 07/May/2018 09:34:01 [Redis.cpp:1366] ERROR: ERR wrong number of arguments for 'restore' command [RESTORE ntopng.p...ts_config]
mai 07 09:34:02 FRCOSNTOPNG ntopng[1793]: 07/May/2018 09:34:01 [Redis.cpp:1366] ERROR: ERR wrong number of arguments for 'restore' command [RESTORE ntopng.p..._password]
mai 07 09:34:02 FRCOSNTOPNG ntopng[1793]: 07/May/2018 09:34:01 [Redis.cpp:1366] ERROR: ERR wrong number of arguments for 'restore' command [RESTORE ntopng.p....pool_ids]
Hint: Some lines were ellipsized, use -l to show in full.

If that can help you : 
1) Operating System : 
Distributor ID: Debian
Description:    Debian GNU/Linux 8.10 (jessie)
Release: 8.10
Codename: jessie

2)Ntopng Version : v.3.5.180504 Professional

Thanks for your help.
Regards,

**Comment by emanuele-f** [comment]
What redis version are you using? Please report the output of `apt-cache show redis-server`

**Comment by shadarthuro** [comment]
Thank for your support emanuele,

Here is the output :

*Package: redis-server
Source: redis
Version: 3:3.2.8-2~bpo8+1
Installed-Size: 1019
Maintainer: Chris Lamb <lamby@debian.org>
Architecture: amd64
Depends: adduser, lsb-base (>= 3.2-14), redis-tools (= 3:3.2.8-2~bpo8+1), init-system-helpers (>= 1.18~), libc6 (>= 2.14), libjemalloc1 (>= 2.1.1)
Description-fr: base de données clé-valeur persistente avec interface réseau
 Redis est une base de données clé-valeur du genre de memcache mais dont
 l'ensemble de données n'est pas volatile. Redis fournit de plus la prise en
 charge native pour la manipulation et le requêtage atomiques des structures
 de données telles que les listes et les ensembles.
 .
 L'ensemble de données est entièrement stocké en mémoire et périodiquement
 transféré vers le disque.
Description-md5: 9160ed1405585ab844f8750a9305d33f
Homepage: http://redis.io/
Section: database
Priority: optional
Filename: pool/main/r/redis/redis-server_3.2.8-2~bpo8+1_amd64.deb
Size: 414038
MD5sum: f44a1ac47680c04d132574c00131fe2a
SHA1: 43b7d89796876a67443666e6c6216ebda2b7da50
SHA256: 660fb0b07fad591fe6b44f547c0314b91f2fa1515375c51d7cf8be01072e1206

Package: redis-server
Source: redis
Version: 2:2.8.17-1+deb8u5
Installed-Size: 862
Maintainer: Chris Lamb <lamby@debian.org>
Architecture: amd64
Depends: init-system-helpers (>= 1.18~), libc6 (>= 2.14), libjemalloc1 (>= 2.1.1), redis-tools (= 2:2.8.17-1+deb8u5), adduser
Description-fr: base de données clé-valeur persistente avec interface réseau
 Redis est une base de données clé-valeur du genre de memcache mais dont
 l'ensemble de données n'est pas volatile. Redis fournit de plus la prise en
 charge native pour la manipulation et le requêtage atomiques des structures
 de données telles que les listes et les ensembles.
 .
 L'ensemble de données est entièrement stocké en mémoire et périodiquement
 transféré vers le disque.
Description-md5: 9160ed1405585ab844f8750a9305d33f
Homepage: http://redis.io/
Tag: implemented-in::c, role::program
Section: database
Priority: optional
Filename: pool/main/r/redis/redis-server_2.8.17-1+deb8u5_amd64.deb
Size: 308084
MD5sum: 3516eacee51d6cedb9d5508345f23c0b
SHA1: ec78dde050d2a3d61fbcd7427bec63753cafb162
SHA256: 79e17484e9e35f1cd3bc74170f76c700502e97d92cf1d556d3c00127be11f88b

**Comment by emanuele-f** [comment]
Please execute the following: `apt-cache policy redis-server`

**Comment by shadarthuro** [comment]
Here about your request : 

> redis-server:
  Installé : 2:2.8.17-1+deb8u5
  Candidat : 2:2.8.17-1+deb8u5
 Table de version :
     3:3.2.8-2~bpo8+1 0
        100 http://httpredir.debian.org/debian/ jessie-backports/main amd64 Packages
 *** 2:2.8.17-1+deb8u5 0
        500 http://ftp.fr.debian.org/debian/ jessie/main amd64 Packages
        500 http://security.debian.org/ jessie/updates/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by emanuele-f** [comment]
Redis issue is solved with commit 271770d8874c973d6b49d2ce18b3c3476ea40927 . Please check out the tomorrow package which will contain the fix
