### ISSUE TITLE
-i interface not working

### ISSUE THREAD

**Issue by jackejiang** [ntop/ntopng#1776]
I have two interfaces in the vmware virtual machine:
ens160   10.95.48.225
ens192     192.168.0.21

I want to capture the packets  on ens192 with ntopng -i ens192, but unexpectedly it captures the packets for both interfaces. Do you encounter the issue?

**Comment by emanuele-f** [comment]
Have you tried running `tcpdump -n -i ens192` to verify the actual traffic seen by the interface?

**Comment by jackejiang** [comment]
yes. The same result using tcpdump, and it's caused by the network configuration. Thanks
