### ISSUE TITLE
ntop not liking my certificate

### ISSUE THREAD

**Issue by DRST-github** [ntop/ntopng#1777]
Hello,

I am trying to use our wildcard certificate for ntopng. However I ran into the "Unable to start HTTP server (IPv4) on port" error.

After looking at the documentation and reading solutions online, I still couldn't get ntopng to run, until I decided to temporarily create a self-signed certificate, as a test. Surprisingly, ntonp ran without problems with the self-signed certificate, so I am thinking that maybe there is something that ntopng doesn't like about our certificate.

To create the pem file I used the following command:

`cat RootCA.crt intermediate.crt publicCert.cer > ntopng-cert.pem`

Note that this is the same command I have used successfully to concatenate our certificates, for use in other servers. I have even tried adding cert.key, but ntopng still throws out the error mentioned above.

Openssl validates the resulting pem file, correctly, and I use the very same steps for the self-signed and for the public certificate, when moving either to the ntopng directories. Yet, only our wildcard certificate causes ntop to abort on startup.

Any help would be appreciated.
Thanks.

**Comment by emanuele-f** [comment]
Hello, can you add the `-v3` option to ntopng and see if the output gives you more information about the problem? `Unable to start HTTP server (IPv4) on port` is the only error you get?

**Comment by DRST-github** [comment]
Hello,
Thanks for replying. This is the output I get:

```
sudo ntopng -v3 -i eth0 -w 0 -W 62626 -G '/var/tmp/ntopng/ntopng.pid'     
11/May/2018 09:47:23 [Ntop.cpp:1499] Setting local networks to 127.0.0.0/8
11/May/2018 09:47:23 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
11/May/2018 09:47:23 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
11/May/2018 09:47:23 [NtopPro.cpp:260] [LICENSE] Reading license from Redis
11/May/2018 09:47:23 [NtopPro.cpp:342] WARNING: [LICENSE] Invalid or missing license
11/May/2018 09:47:23 [NtopPro.cpp:359] WARNING: [LICENSE] ntopng will now run in enterprise edition for 10 minutes
11/May/2018 09:47:23 [NtopPro.cpp:361] WARNING: [LICENSE] before returning to community mode
11/May/2018 09:47:23 [NtopPro.cpp:363] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
11/May/2018 09:47:23 [NtopPro.cpp:365] WARNING: [LICENSE] or run ntopng in community mode starting
11/May/2018 09:47:23 [NtopPro.cpp:366] WARNING: [LICENSE] ntopng --community
11/May/2018 09:47:23 [Ntop.cpp:352] Interfaces Available: 32
11/May/2018 09:47:23 [ThreadedActivity.cpp:147] Running /usr/share/ntopng/scripts/callbacks/system/boot.lua (iface=(nil))
11/May/2018 09:47:23 [Lua.cpp:131] NULL interface: did you restart ntopng in the meantime?
11/May/2018 09:47:23 [Lua.cpp:131] NULL interface: did you restart ntopng in the meantime?
11/May/2018 09:47:23 [Lua.cpp:131] NULL interface: did you restart ntopng in the meantime?
11/May/2018 09:47:23 [main.cpp:172] System has 2 CPU cores
11/May/2018 09:47:25 [HostPools.cpp:84] Host Pools Available: 4
11/May/2018 09:47:25 [NetworkInterface.cpp:244] Executing ethtool -K eth0 gro off gso off tso off 2>/dev/null
11/May/2018 09:47:25 [main.cpp:229] An exception occurred during interface creation: eth0. Falling back to pcap
11/May/2018 09:47:27 [HostPools.cpp:84] Host Pools Available: 4
11/May/2018 09:47:27 [NetworkInterface.cpp:244] Executing ethtool -K eth0 gro off gso off tso off 2>/dev/null
11/May/2018 09:47:27 [PcapInterface.cpp:91] Reading packets from interface eth0...
11/May/2018 09:47:27 [Ntop.cpp:1626] Registered interface eth0 [id: 3]
11/May/2018 09:47:27 [main.cpp:304] PID stored in file /var/tmp/ntopng/ntopng.pid
11/May/2018 09:47:28 [HTTPserver.cpp:850] Found SSL certificate /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem
11/May/2018 09:47:28 [HTTPserver.cpp:923] ERROR: Unable to start HTTP server (IPv4) on ports 62626s
```

**Comment by emanuele-f** [comment]
What is the output of `ls -l /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem` ?

**Comment by DRST-github** [comment]
`-rw-r-----. 1 nobody nobody 4858 May 11 09:41 /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem`

**Comment by emanuele-f** [comment]
Is ntopng running as nobody right?

**Comment by DRST-github** [comment]
Yes.

**Comment by emanuele-f** [comment]
Hello, with commit dba841a16be506260195526557d55f9d9c20af16 ntopng should print some informative error message. Please check out the new version and report the new output. If you have installed ntopng from packages, please update to the new development package (it will be available in one hour).

**Comment by DRST-github** [comment]
Hello,
I get a new line:

`[HTTPserver.cpp:812] ERROR: [HTTP] set_ssl_option: cannot open /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem: error:0906D06C:PEM routines:PEM_read_bio:no start line`

**Comment by emanuele-f** [comment]
Probably you are not using a .pem certificate but a certificate into another format, something like this: https://github.com/node-apn/node-apn/issues/234#issuecomment-302020793

**Comment by DRST-github** [comment]
As far as I know, the certificate is already in the correct format as using the command in the link you provided:

 `openssl x509 -inform der -in aps_production.cer -outform pem -out aps_production.pem`

Throws the following error:

```
unable to load certificate
140300704642976:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:tasn_dec.c:1199:
140300704642976:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:tasn_dec.c:374:Type=X509
```

**Comment by emanuele-f** [comment]
Can you generate a new certificate in the same way as the certificate that's not working and send it to me for testing?

**Comment by DRST-github** [comment]
How would I send it to you?

**Comment by simonemainardi** [comment]
attach it here or send it to faranda at ntop dot org

alternatively, just post the commands you've issued to generate the certificate (I'm assuming you are using openssl).

**Comment by simonemainardi** [comment]
any news here?

**Comment by DRST-github** [comment]
I sent it to the email address you provided.

**Comment by emanuele-f** [comment]
Hi, the certificate is missing the private key, please see https://github.com/ntop/ntopng/blob/dev/httpdocs/ssl/ntopng-cert.pem.dummy for an example of valid certificate.

**Comment by DRST-github** [comment]
I fixed the problem by omitting the root and intermediate certificate from the pem file.
