### ISSUE TITLE
Valid licence marked invalid

### ISSUE THREAD

**Issue by UniVerzitetNis** [ntop/ntopng#1778]
Valid licence marked invalid.
After 10 minutes ntopng switches to Community mode even though I have valid Enterprise licence.

`service ntopng status -n 5000 -l
Redirecting to /bin/systemctl status  -n 5000 -l ntopng.service
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/usr/lib/systemd/system/ntopng.service; disabled; vendor preset: disabled)
   Active: active (running) since Thu 2018-05-10 09:28:45 CEST; 4min 39s ago
  Process: 4379 ExecStopPost=/bin/rm -rf /run/ntopng.conf (code=exited, status=0/SUCCESS)
  Process: 4382 ExecStartPre=/bin/sh -c /bin/sed "/-e.*$\|-G.*\|--daemon.*\|--pid.*/s/^/#/" /etc/ntopng/ntopng.conf > /run/ntopng.conf (code=exited, status=0/SUCCESS)
 Main PID: 4385 (ntopng)
   CGroup: /system.slice/ntopng.service
           └─4385 /usr/local/bin/ntopng /run/ntopng.conf

May 10 09:28:45 netflow.junis.ni.ac.rs systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
May 10 09:28:45 netflow.junis.ni.ac.rs systemd[1]: Started ntopng high-speed web-based traffic monitoring and analysis tool.
May 10 09:28:45 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:45 [Ntop.cpp:1499] Setting local networks to 160.99.0.0/16
May 10 09:28:45 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:45 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
May 10 09:28:45 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:45 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
May 10 09:28:45 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:45 [NtopPro.cpp:262] [LICENSE] Reading license from /etc/ntopng.license
May 10 09:28:45 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:45 [NtopPro.cpp:157] Contacting licensing server. Please hold on...
May 10 09:28:45 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:45 [NtopPro.cpp:172] [LICENSE] /etc/ntopng.license: unable to validate Enterprise license [License expired]
May 10 09:28:45 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:45 [NtopPro.cpp:342] WARNING: [LICENSE] Invalid or missing license
May 10 09:28:45 netflow.junis.ni.ac.rs ntopng[4385]: [NtopPro.cpp:342] WARNING: [LICENSE] Invalid or missing license
May 10 09:28:45 netflow.junis.ni.ac.rs ntopng[4385]: [NtopPro.cpp:359] WARNING: [LICENSE] ntopng will now run in enterprise edition for 10 minutes
May 10 09:28:45 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:45 [NtopPro.cpp:359] WARNING: [LICENSE] ntopng will now run in enterprise edition for 10 minutes
May 10 09:28:45 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:45 [NtopPro.cpp:361] WARNING: [LICENSE] before returning to community mode
May 10 09:28:45 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:45 [NtopPro.cpp:363] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
May 10 09:28:45 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:45 [NtopPro.cpp:365] WARNING: [LICENSE] or run ntopng in community mode starting
May 10 09:28:45 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:45 [NtopPro.cpp:366] WARNING: [LICENSE] ntopng --community
May 10 09:28:45 netflow.junis.ni.ac.rs ntopng[4385]: [NtopPro.cpp:361] WARNING: [LICENSE] before returning to community mode
May 10 09:28:45 netflow.junis.ni.ac.rs ntopng[4385]: [NtopPro.cpp:363] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
May 10 09:28:45 netflow.junis.ni.ac.rs ntopng[4385]: [NtopPro.cpp:365] WARNING: [LICENSE] or run ntopng in community mode starting
May 10 09:28:45 netflow.junis.ni.ac.rs ntopng[4385]: [NtopPro.cpp:366] WARNING: [LICENSE] ntopng --community
May 10 09:28:45 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:45 [Ntop.cpp:1626] Registered interface tcp://127.0.0.1:5556 [id: 3]
May 10 09:28:45 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:45 [main.cpp:304] PID stored in file /var/run/ntopng.pid
May 10 09:28:46 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:46 [HTTPserver.cpp:860] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
May 10 09:28:46 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:46 [Utils.cpp:469] User changed to nobody
May 10 09:28:46 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:46 [HTTPserver.cpp:931] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
May 10 09:28:46 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:46 [HTTPserver.cpp:934] HTTP server listening on port(s) 3000
May 10 09:28:46 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:46 [main.cpp:386] Working directory: /var/tmp/ntopng
May 10 09:28:46 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:46 [main.cpp:388] Scripts/HTML pages directory: /usr/share/ntopng
May 10 09:28:46 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:46 [Ntop.cpp:391] Welcome to ntopng x86_64 v.3.4.180509 - (C) 1998-18 ntop.org
May 10 09:28:46 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:46 [Ntop.cpp:401] Built on CentOS Linux release 7.4.1708 (Core)
May 10 09:28:46 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:46 [NtopPro.cpp:508] [LICENSE] System Id:        68A739175505617E
May 10 09:28:46 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:46 [NtopPro.cpp:509] [LICENSE] Edition:        Enterprise
May 10 09:28:46 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:46 [NtopPro.cpp:510] [LICENSE] License Type:        Demo License
May 10 09:28:46 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:46 [NtopPro.cpp:513] [LICENSE] License:        9BBFB2B734B44E75975A89EA49C6A4D915530746711A1AD63D
May 10 09:28:46 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:46 [NtopPro.cpp:519] [LICENSE] Validity:        Until Thu May 10 09:38:45 2018
May 10 09:28:46 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:46 [PeriodicActivities.cpp:59] Started periodic activities loop...
May 10 09:28:47 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:47 [PeriodicActivities.cpp:100] Each periodic activity script will use 2 threads
May 10 09:28:47 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:47 [NetworkInterface.cpp:2472] Started packet polling on interface tcp://127.0.0.1:5556 [id: 3]...
May 10 09:28:48 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:28:48 [CollectorInterface.cpp:122] Collecting flows on tcp://127.0.0.1:5556
May 10 09:29:25 netflow.junis.ni.ac.rs ntopng[4385]: [NetworkInterface.cpp:1282] WARNING: A flow has been seen from multiple exporters or from multiple IN/OUT interfaces. Check exporters configuration.
May 10 09:29:25 netflow.junis.ni.ac.rs ntopng[4385]: 10/May/2018 09:29:25 [NetworkInterface.cpp:1282] WARNING: A flow has been seen from multiple exporters or from multiple IN/OUT interfaces. Check exporters configuration.`

**Comment by emanuele-f** [comment]
Please contact us privately for license issues. http://www.ntop.org/support/need-help-2/contact-us/
