### ISSUE TITLE
NtopNG crash

### ISSUE THREAD

**Issue by MaurizioFontanesi** [ntop/ntopng#1779]
After about ten days of work the NtopNG process crashes. Ntopng.log doesn't include useful messages.

In syslog I found the following messages:

May 11 04:50:00 nbox mysqld[3575]: Aborted connection 33 to db: 'ntopng' user: 'root' host: 'localhost' (Got an error reading communication packets)
May 11 04:50:00 nbox mysqld[3575]: Aborted connection 7 to db: 'ntopng' user: 'root' host: 'localhost' (Got an error reading communication packets)

Mysql process seems ok, we only need to restart ntopng process in order to resolve the issue.

Any suggestion ?

[180511-log-ntopng.txt.gz](https://github.com/ntop/ntopng/files/1994416/180511-log-ntopng.txt.gz)
[180511-syslog.txt.gz](https://github.com/ntop/ntopng/files/1994417/180511-syslog.txt.gz)

**Comment by emanuele-f** [comment]
Hello, what ntopng version and operating system are you using? What's the output of `cat /proc/sys/kernel/core_pattern`? Please update to the latest version to fix the redis restore error

**Comment by MaurizioFontanesi** [comment]
Hi Emanuele,

below you can find the info requested:

NtopNG v.3.5.180427    [Enterprise/Professional build]
GIT rev:        dev:d466c8e2988685cdf3b33a2a4bb5b8ebf3daa469:20180427
Pro rev:        r1591
Built on:       Ubuntu 14.04.5 LTS
Platform:       x86_64
Edition:        Professional
License Type:   Permanent

nbox@nbox:~$ sudo lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

nbox@nbox:~$ sudo cat /proc/sys/kernel/core_pattern
core

I'm going to update in order to resolve redis restore error.....

**Comment by emanuele-f** [comment]
What are the ntopng command line/service options you are using? 

Please check out this link on how to enable and test core dump generation, we need a core dump or a stack trace to debug the problem https://sigquit.wordpress.com/2009/03/13/the-core-pattern/ .

**Comment by MaurizioFontanesi** [comment]
Here are service options:

ntopng --http-port "3000" --https-port "0" --core-affinity "-1" --local-networks "192.168.0.0/16,10.100.100.0/24" --dump-flows "[hidden]" --data-dir "/storage/ntopng" --pid "/var/run/ntopng.pid" --interface "tcp://127.0.0.1:5556" 

Thanks for info on how to enable core dump generation, I'll read and apply them.

**Comment by emanuele-f** [comment]
Thank you, please provide the core dump or stack trace when available so that we can inspect it.

**Comment by simonemainardi** [comment]
any news here?

**Comment by MaurizioFontanesi** [comment]
Not yet, currently the process is running fine.

**Comment by simonemainardi** [comment]
please, reopen with the requested information if necessary.
