### ISSUE TITLE
password problem with special char ... again

### ISSUE THREAD

**Issue by paoloB132** [ntop/ntopng#178]
was issue #173 ...

I've take a look to 

/usr/share/ntopng/scripts/lua/login.lua

and this explain better what I see:

<input type="password" class="form-control" name="password" placeholder="Password" pattern="^[\w]{1,}$" required=“">

Clearly only \w is admitted .

**Comment by lucaderi** [comment]
So what do you expect? We accept numbers, letters and _. It is consistent with the preferences where you can set a password with the same constraints.

**Comment by paoloB132** [comment]
Luca,  this changes from previous version, where I've used other chars than "\w"

Also, when you log in noting and try to change password for admin using special char, you are granted to do that !!!!!!, no notification of wrong chars.

**Comment by paoloB132** [comment]
the file add_user.la has :+1: 
<input id="password_input" type="password" name="password" value="" class="form-control">

that s different from the login one !!

**Comment by lucaderi** [comment]
add_user_dialog.lua is checking the form prior to call add_user.lua so I think we're in business

Please send me a pull request with the change, and make sure you star ntopng on github.

**Comment by paoloB132** [comment]
Done...both
