### ISSUE TITLE
Removing unwanted network hosts using packet-filter

### ISSUE THREAD

**Issue by leikoilja** [ntop/ntopng#1782]
Hey all.

How can i ignore all the traffic coming from a particular IP hosts using ntopng v.3.2.180417?
I have tried adding at the bottom of /etc/ntopng/ntopng.conf
--packet-filter="not host 192.168.92.1"
and I have tried:
--packet-filter="host 192.168.92.1"

but neither of them work and i keep seeping my annoying host.

I am Raspberry Pi Stretch distribution.

Thank you in advance.

**Comment by emanuele-f** [comment]
Hello, the first one is the correct may to do this. Have you restarted ntopng with `systemctl restart ntopng`? Please post the latest service log with `journalctl -u ntopng`

**Comment by leikoilja** [comment]
Thank you @emanuele-f for a quick answer.
Hm, after looking into a service log i see(full [log):](https://paste.ubuntu.com/p/8qGzYPKPYB/):
[CollectorInterface.cpp:286] ERROR: No filter can be set on a collector interface. Ignored not host 192.168.92.1

I guess it has something to do with my configurations as well. Can you please take a look(/etc/ntopng/ntopng.cong):
-G=/var/run/ntopng.pid
 -e=
 -i=tcp://127.0.0.1:1234
 -w=3000
 -m=192.168.88.0/24,192.168.92.0/24
 -n=1
 -d=/var/tmp/ntopng
--disable-autologout
--enable-flow-activity
--max-num-flows=1310720
--disable-login
--community
--packet-filter="not host 192.168.92.1"

**Comment by emanuele-f** [comment]
You cannot set BPF filters on remote interfaces. Please set the filter on the remote probe itself instead.

From the nprobe `-h command`:
```
[--bpf-filter|-f] <BPF filter>      | BPF filter for captured packets
                                    | [default=no filter]
--collection-filter <filter>        | Filter applied to collected filters only (-3). Filter format:
                                    | [!]<asX | network/mask> (! means discard flows matching filter)
                                    | Example: !as12345, 192.168.0.0/24, !10.0.0.0/8
```

**Comment by leikoilja** [comment]
@emanuele-f , i am using nProbe v.8.4.180506 and still can't make it work. Do you think my syntax is right?

After modifying /etc/nprobe/nprobe.conf file by adding:
--collection-filter=!192.168.92.1

Nothing has changed. 
Here is the whole config file - [link](https://paste.ubuntu.com/p/qCxmkY86ph/)

---
Have also tried adding BPF filter to nprobe config file as:
--bpf-filter="not host 192.168.92.1"

didn't help either. On the ntopng http interface i still see 192.168.92.1 annoying host :/

**Comment by emanuele-f** [comment]
Since you are capturing from a netflow collector, the `--collection-filter` should be used. Please run `nprobe -h | grep -- --collection-filter` to see if this option is supported with your nprobe version, otherwise please update to the latest version (both ntopng and nprobe).

**Comment by leikoilja** [comment]
@emanuele-f, it it supported
```
root@iap-office:~# nprobe -h | grep -- --collection-filter
--collection-filter <filter>        | Filter applied to collected filters only (-3). Filter format:
```
I have added(to nprobe config file /etc/nprobe/nprobe.conf:
`--collection-filter=!192.168.92.1`
but i am not entirely sure if the syntax is correct, cause it doesnt work :/

**Comment by emanuele-f** [comment]
How are you starting the nprobe service? If you use nprobe@none then the file `/etc/nprobe/nprobe-none.conf` could be used instead. As the example output above, you can see that the syntax is correct: `!10.0.0.0/8`. In your case, `!192.168.92.1/32` should be used.

**Comment by leikoilja** [comment]
@emanuele-f , the nprobe service is started automatically after reboot.
My config file under "/etc/nprobe/nprobe.conf" is correct one, cause in the same config file I set up "--zmq=tcp://127.0.0.1:1234". So, after reboot nprobe service automatically starts, loads up "/etc/nprobe/nprobe.conf" config and sends json stats to "tcp://127.0.0.1:1234". And from ntopng side, in it's config it is configured to listen to "tcp://127.0.0.1:1234". 

So, i would guess that "/etc/nprobe/nprobe.conf" is the right path for my nprobe config file. Now, at the end of config file i have:
```
--zmq=tcp://127.0.0.1:1234
--collection-filter=!192.168.92.1/24 
```
/24 mask is taken from my MikroTik router settings([picture of settings](https://i.imgur.com/CpGDaTD.png))

Unfortunately, in my ntopng http dashboard still shows me 192.168.92.1 host :/ ([screenshoot](https://i.imgur.com/zTMga7I.png))

**Comment by simonemainardi** [comment]
Thanks for reporting. There was actually a glitch when parsing the `--collection-filter`. New build are in progress and will be available in an hour. Please, hold on, update, and try again. In the meanwhile, if you want to stay with the current version, just specify `--collection-filter=!192.168.92.0/24`, that is, only the network part of the address.

**Comment by leikoilja** [comment]
Thank you @simonemainardi and @emanuele-f  for an update, but I still do not think it works properly. :/ 

I have specified upgraded to nProbe v.8.5.180514 (r6153) version
and specified 
`--collection-filter=!192.168.92.1/24`
in my config fine to filter one specific gateway host, but it still doesn't work and shows it in ntopng web interface.

Please, help me to understand what am i doing wrong

**Comment by simonemainardi** [comment]
your nprobe v.8.5.180514 is still not updated. Please, update it.

**Comment by leikoilja** [comment]
@simonemainardi, how is that so?
I used to have v.8.4***, so i run:
```
apt-get update
apt-get install --only-upgrade nprobe
```
And got v.8.5.180514 version installed. 
Now if i run 
`apt-get install --only-upgrade nprobe`
I'm getting "nprobe is already the newest version (8.5.180514-6153)."

I'm on Raspberry Pi Stretch

**Comment by simonemainardi** [comment]
make sure to run both update and upgrade:

```
deri@raspberrypi 204> sudo apt-get update
Get:2 http://mirrordirector.raspbian.org/raspbian stretch InRelease [15.0 kB]
Get:3 http://archive.raspberrypi.org/debian jessie InRelease [22.9 kB]
Get:1 http://packages.ntop.org/apt/stretch_pi armhf/ InRelease [2139 B]
Get:4 http://packages.ntop.org/apt/stretch_pi all/ InRelease [2137 B]
Get:5 http://archive.raspberrypi.org/debian jessie/main armhf Packages [171 kB]
Get:6 http://packages.ntop.org/apt/stretch_pi armhf/ Packages [843 B]
Get:7 http://packages.ntop.org/apt/stretch_pi all/ Packages [413 B]
Fetched 214 kB in 3s (64.8 kB/s)
Reading package lists... Done
deri@raspberrypi 205> sudo  apt-get install --only-upgrade --dry-run nprobe
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  bridge-utils ethtool
Use 'sudo apt autoremove' to remove them.
The following packages will be upgraded:
  nprobe
1 upgraded, 0 newly installed, 0 to remove and 200 not upgraded.
Inst nprobe [8.5.180514-6153] (8.5.180521-6157 ntop Repository:apt.ntop.org [armhf])
Conf nprobe (8.5.180521-6157 ntop Repository:apt.ntop.org [armhf])
```

**Comment by leikoilja** [comment]
Thank you @simonemainardi for your help, but I must be doing something wrong... the '--collection-filter=!192.168.92.1/24' options is still not working.

I have done both update and upgrade, got same as you: 
```
root@iap-office:~# sudo apt-get update
...
root@iap-office:~# apt-get install --only-upgrade --dry-run nprobe
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  bridge-utils ethtool
Use 'sudo apt autoremove' to remove them.
The following packages will be upgraded:
  nprobe
1 upgraded, 0 newly installed, 0 to remove and 200 not upgraded.
Inst nprobe [8.5.180514-6153] (8.5.180521-6157 ntop Repository:apt.ntop.org [armhf])
Conf nprobe (8.5.180521-6157 ntop Repository:apt.ntop.org [armhf])
root@iap-office:~# nprobe --version

Welcome to nProbe v.8.5.180514 (r6153) [Embedded] for armv7l-unknown-linux-gnueabihf
```
And my nprobe config file nano /etc/nprobe/nprobe.conf:
```
 -G=/var/run/nprobe_m.pid
-i=none
-n=none
 -3=2055
--zmq=tcp://127.0.0.1:1234
--collection-filter=!192.168.92.1/24
```
I know the config file is getting loaded, cause nprobe is catching traffic flow on port 2055 and passing it to tcp://127.0.0.1:1234 as expected, but it still doesnt filter out the host i need to filter "192.168.92.1/24"

Uh...

**Comment by simonemainardi** [comment]
if you leave the option `--dry-run ` you are actually not upgrading anything. remove that option and make sure to have installed version >= 8.5.180521-6157
