### ISSUE TITLE
Host Graph Traffic Statistics

### ISSUE THREAD

**Issue by hytek3000** [ntop/ntopng#1783]
Something that has been bugging me is the "Minute Interface Top Traffic Statistics" when you hover over a graph. Attached is a graph of a single host for 1 hour. We can see a spike at 08:44:47 for this host 10.1.12.149. However, when we hover over the graph at that spike, and we look at the traffic statistics, it shows top traffic for the entire interface at that moment; instead of the host the graph is for.

Having interface wide statistics like what is showed in the minute statistics in the attached image would be great if we were looking at the interface graph overall, but not on a single host such as what this image is showing.

What I would like this feature to be is when we are viewing a graph for a single host, and we hover over the graph for minute statistics, we should be presented with information at that moment, about that host we are reviewing. In the attached there is nothing in the minute statistics, at all, that relates in any way to the host I am looking at: zero, nadda, nothing. All of the host that are listed in this Minute Traffic from the image is not a peer or talker to 10.1.12.149, and this particular host doesn't even show up in the minute statistics for this graph.

Could we please change what is being displayed when we hover over a graph when it is isolated to a single host to display information about that host only?

Thank you!
![ntopngtrafficchart](https://user-images.githubusercontent.com/38108898/40069417-1d15b6e6-5820-11e8-95c9-8a98f6e17128.JPG)

**Comment by emanuele-f** [comment]
Hello, the behaviour you are describing is correct and documented. Top talkers are currently pre-calculated and stored into the top talkers database in an aggregated format, so this is the only information we can extract from it right now. The `Talkers` tab is more appropriate for host-related communications as it is based on the mysql flows data. I agree that host-related information would be more appropriate in this view but it does not fit our current model. Thank you for the feedback!
