### ISSUE TITLE
Total in out per AS Number

### ISSUE THREAD

**Issue by nokoya** [ntop/ntopng#1786]
Hello,

Graph information of ASN historical page isn't enough. Please add total in & total out, 95th of in & 95th of out, average of  in & average of out, max of in & max of out within duration selected.

Thanks in advanced.

**Comment by Rico29** [comment]
hello,
it would be very useful to have this in ntopng !

**Comment by simonemainardi** [comment]
Add two extra timeseries, e.g., ts_utils.newSchema("asn:traffic_sent"), ts_utils.newSchema("asn:traffic_rcvd") in `ts_5min.lua` ASN SCHEMAS.

Write timeseries data in `ts_dump.asn_update_rrds`

Show the two extra entries in the autonomous system page. What is asked will appear for free once done.

**Comment by simonemainardi** [comment]
for the schemas

```
schema = ts_utils.newSchema("asn:traffic_sent", {step=300, rrd_fname="bytes_sent"})
schema:addTag("ifid")
schema:addTag("asn")
schema:addMetric("bytes")

schema = ts_utils.newSchema("asn:traffic_rcvd", {step=300, rrd_fname="bytes_rcvd"})
schema:addTag("ifid")
schema:addTag("asn")
schema:addMetric("bytes")
```

**Comment by simonemainardi** [comment]
for the update

```
    ts_utils.append("asn:traffic_sent", {ifid=ifstats.id, asn=asn,
                                         bytes=asn_stats["bytes.sent"]}, when)

    ts_utils.append("asn:traffic_rcvd", {ifid=ifstats.id, asn=asn,
                                         bytes=asn_stats["bytes.rcvd"]}, when)
```
