### ISSUE TITLE
Autonomous Systems inner traffic is accounted twice

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#1787]
When two hosts within the same Autonomous System talk one each other, the traffic is counted twice, as sent and received by the AS. Ideally this should be accounted as inner traffic. This also requires modifying the current RRD to add a new inner column.

**Comment by FOSquare** [comment]
hello, I have two very initial questions. can you help me? Thanks in advance.
1.      I test the pfcount –i  eth2. It works, but pfcount –i  zc:eth2 does not work. It says “pfring_open error [no such device] (pf_ring not loaded or interface zc:eth2 is down ?)”. When I use the “make” command in the ixgbe-5.3.7-zc/src folder, it says: fatal error: pf_ring.h: No such file or directory #include “pf_ring.h”. I check the files below the /src, there is no pf_ring.h file. Why the file is lost? How can I fix it?
2.      Use zcount –h can not get the pf_ring version. It says “No command ‘zcount’ found, did you mean …”. I check from the internet, and I use cat /proc/net/pf_ring/info to get the version of pf_ring, is shows the version is 7.1.0. However, when I use this to generate the license, it told me that “Please check the version Id format”. And after I get the license, how should I use it?

**Comment by cardigliano** [comment]
Fixed in 0e95cff729ebd740bd80b3075b35fb60d2b9ab1e
