### ISSUE TITLE
per-host history not available in community edition?

### ISSUE THREAD

**Issue by kunzjacq** [ntop/ntopng#1788]
Hello,
I am using ntopng community edition (bundled  with ubuntu 18.04, v. 3.2.171227). In preferences, I configured ntop to create local host timeseries (using a mysql backend with the -F option),  however i am not able to see timeseries by host, although it works at the interface level. I was not able to determine wether this was normal according to your feature matrix. Maybe this is a bug?

**Comment by emanuele-f** [comment]
Hi, ntopng timeseries are not stored into MySQL, but on RRDs. MySQL only stores flows data. Please check out your data directory (usually `/var/tmp/ntopng`) for RRD files.
