### ISSUE TITLE
why ntopng using a lot of memory ? 

### ISSUE THREAD

**Issue by AlekMarkus** [ntop/ntopng#179]
Hello ,

i had before a week 4gb installed on my server : Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 cpu's)

and it always was on 95% so i thought there not enough memory  and i will upgrade , today i have 8 GB on my server and its using   81% of my memory. why this happened ? 

![memory](https://cloud.githubusercontent.com/assets/13960741/10039032/f0bbd5ea-61d6-11e5-9361-2b6f959f5820.png)

**Comment by lucaderi** [comment]
We fixed a memory leak some time ago. Please upgrade to the latest version first.

**Comment by AlekMarkus** [comment]
Hey Luca , I'm updating every time when I see new version. my ntopng version was updated yesterday version.

I have updated now , and I will update you

Thanks .

**Comment by lucaderi** [comment]
I assume you have used the dev version right? Can you please tell me the command line you have used to start it?

**Comment by AlekMarkus** [comment]
I have installed from rpm.

Yum install ntopng
And it's updated me to the last version.

I will be back soon to office , and write here my configuration file.

**Comment by lucaderi** [comment]
OK but you have used the stable or the dev version?

**Comment by AlekMarkus** [comment]
Stable.
I have updated from here

http://packages.ntop.org/rpm6/x86_64/ntopng/

**Comment by AlekMarkus** [comment]
my conf file : 

-n=1
-W=3000
-g=-1
-d=/var/tmp/ntopng.old/
-G=/var/tmp/ntopng.pid
-i=eth0
-i=eth1
-F=es;flows;ntopng-%Y.%m.%d;http://10.1.1.20:9200/_bulk
-c=ABQIAAAAqyS8slRQqo9Kcr0-E9h89hSGhgF8hR3CTnfinjU1fi7o32h8XA
-m=10.1.1.1/24,10.1.101.1/24,10.1.109.1/24,10.1.200.200/24
-p=/usr/share/ntopng/httpdocs/protocol/syslog.txt
~

**Comment by lucaderi** [comment]
Use dev

**Comment by lucaderi** [comment]
Try with dev and let me know

**Comment by AlekMarkus** [comment]
ok , where can i download the dev version ?

btw if i will remove current version do i need to backup before i remove ?

**Comment by lmangani** [comment]
@AlekMarkus see http://packages.ntop.org/

**Comment by AlekMarkus** [comment]
maybe i have wrong :)

i have downloaded always from here : http://packages.ntop.org/rpm6/x86_64/ntopng/

so i assume im using the dev version ?

**Comment by lucaderi** [comment]
The above irk is correct. In essence with the very latest ntopng you still see the leak using the above config file right?

**Comment by AlekMarkus** [comment]
yes.

right now its taking 2GB..i think till tomorrow afternoon it will more than 2GB

**Comment by AlekMarkus** [comment]
right now its 3 GB 
![memory](https://cloud.githubusercontent.com/assets/13960741/10095245/f15370c6-6370-11e5-826e-82560a9659d9.png)

**Comment by lucaderi** [comment]
Alex any news? Memory increases as the number of hosts/flows increase but it should hit a max limit and do not cross such limit.

**Comment by AlekMarkus** [comment]
well i don't have any new hosts/server ,  and right now its taking 6.4 GB again...

i can give an remote access if you want to check couple things.

**Comment by lucaderi** [comment]
Please do allow me to access (email deri@ntop.org)
