### ISSUE TITLE
Cannot see search bar on datatables?

### ISSUE THREAD

**Issue by pleoeter** [ntop/ntopng#1791]
I want to filter rows / columns  just like in 
https://datatables.net/
but in ntopng we just have pagination and sorting shown? How can we see an additional search bar other than that on the top right to search host

**Comment by emanuele-f** [comment]
Hi, please note that we currently use a customized version of https://github.com/jeffdupont/bootstrap-data-table for datatables implementation.
Normally, the search via a searchbar in datatables is implemented via a simple client side filter, but this would not be applicable for ntopng as it requires all the data to be sent from the server to the client and post-processed there.
On the other end, a full server side search implementation on multiple columns can be complex to implement in C.

**Comment by pleoeter** [comment]
I have enabled the show filter option using  https://github.com/jeffdupont/bootstrap-data-table and I cannot see the text bar, moreover I added a search bar at my own with buttons but its not functional for search rows

**Comment by simonemainardi** [comment]
@pleoeter table data is filtered and sliced server-side. Adding the show filter would have no effect. I am closing the issue as we are currently unable to replace bootstrap-data-table.
