### ISSUE TITLE
Traffic Bridging no Save Button?

### ISSUE THREAD

**Issue by radixtenshi** [ntop/ntopng#1792]
Hello i have NtopNG set in Bridge mode In-Line.

Almost everything is working fine, except for the option "Traffic Bridging" in the Preference menu.
That option dont appears to have any SAVE button and when i leave the page to another menu the options i choose never take effect and reset to default state.
Is that some kind of bug? i must enable any command line option?

I want to activate Split Shaping Directions and Captive Portal.

I have an Enterprise license and the pfrings licenses to.

Sorry about my english, im spanish speaker.
Thanks in advise.

**Comment by emanuele-f** [comment]
A new package will be available in one hour. Thank you for reporting.

**Comment by radixtenshi** [comment]
Tahnks a lot.
