### ISSUE TITLE
pfcount –i zc:eth5 does not work

### ISSUE THREAD

**Issue by FOSquare** [ntop/ntopng#1793]
I install from the GIT. And I put the license in the /etc/pf_ring/ . Now, cd PF_RING/drivers/intel/ixgbe/ixgbe-5.3.7-zc/src
make 
show information below:
"make -C /lib/modules/3.16.0-38-generic/build SUBDIRS=/root/PF_RING/drivers/intel/ixgbe/ixgbe-5.3.7-zc/src modules
make[1]: Entering directory `/usr/src/linux-headers-3.16.0-38-generic'
  Building modules, stage 2.
  MODPOST 1 modules
make[1]: Leaving directory `/usr/src/linux-headers-3.16.0-38-generic'".
I think it is fine. However, when I go next command ./load_driver.sh. it says
irqbalance: no process found.

**Comment by cardigliano** [comment]
@FOSquare please provide:
- cat /proc/net/pf_ring/dev/eth5/info
- ethtool -i eth5

**Comment by FOSquare** [comment]
cat /proc/net/pf_ring/dev/eth5/info shows:
---------------------------------------------
Name:         eth5
Index:        4
Address:      00:02:C9:51:C8:9E
Polling Mode: NAPI
Type:         Ethernet
Family:       Standard NIC
# Bound Sockets:  0
TX Queues:    32
RX Queues:    4
--------------------------------------------
While ethtool -i eth5 shows
--------------------------------------------
driver: mlx4_en
version: 3.4-1.0.0 (25 Sep 2016)
firmware-version: 2.9.1200
bus-info: 0000:01:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: yes

Thanks a lot

**Comment by cardigliano** [comment]
@FOSquare please note eth5 is a mellanox interface, which is not supported by the ixgbe driver
