### ISSUE TITLE
SNMP page remains blank

### ISSUE THREAD

**Issue by Alestor** [ntop/ntopng#1794]
ntopng Professional Edition v.3.5.180524

Hi,

when looking into the SNMP Tab of a Network device no information are provided. The page remains blank without any error messages:

![grafik](https://user-images.githubusercontent.com/6898158/40489499-8ba69c2e-5f69-11e8-887d-e4108b255121.png)

Default Community is configured and Version is set to v2c. snmpwalk from the server where ntop is running works fine on all my network devices.

**Comment by simonemainardi** [comment]
thanks for reporting, we have reworked the SNMP support to make it much more responsive and information-rich. The old SNMP implementation was poorly relying on caching and that was causing a lot of unnecessary SNMP traffic. The new implementation is available in ntopng enterprise.

**Comment by Alestor** [comment]
Hi,

thank you for the quick reply, but this is very disappointing. I bought ntopng profession with SNMP support AND updates included. So if you rework the code, whats an update in my opinion, please make it available on the professional version.

**Comment by Alestor** [comment]
@simonemainardi: How do you plan to proceed with the SNMP support in ntopng professional ?
