### ISSUE TITLE
n2disk was killed

### ISSUE THREAD

**Issue by FOSquare** [ntop/ntopng#1796]
I installed n2disk from the packages, also I generate the license to put it in the right directory. However. When I use the command "n2disk -i eth2 -o /storage -b 1024 -p 512 --disk-limit 50% -I -A /storage"
It shows
25/May/2018 12:04:36 [n2disk.c:6148] Welcome to n2disk v.3.0.180523 (r4912) [Nehalem]
25/May/2018 12:04:36 [n2disk.c:6178] Running on 1 node(s) system with 4 core(s). NUMA affinity set to node -1.
25/May/2018 12:04:36 [n2disk.c:6244] Using PF_RING for packet capture
25/May/2018 12:04:36 [n2disk.c:6273] Multithread support enabled
25/May/2018 12:04:36 [n2disk.c:6386] Storage limit set to 71.07 GB, 0.00 GB are in use, disk size is 142.13 GB
25/May/2018 12:04:36 [n2disk.c:6439] Dump files max size is set to 512 MB
25/May/2018 12:04:36 [n2disk.c:6454] Buffer memory is set to 1024 MB (x 2 pcap files)
25/May/2018 12:04:36 [n2disk.c:6494] Using directory /storage for dump files
25/May/2018 12:04:36 [n2disk.c:6512] Up to 100 files will be written per folder
25/May/2018 12:04:36 [n2disk.c:6518] Dump files max duration is set to 600 sec
25/May/2018 12:04:36 [n2disk.c:6558] Dumping data in 0.1 MB chunks
25/May/2018 12:04:36 [n2disk.c:6603] Index processing memory is set to 424 MB (x 2 index files)
Killed

_______________________________________________________
Why it is killed? Thanks a lot.

**Comment by cardigliano** [comment]
@FOSquare, how much free memory do you have in this system? Please provide "free"

**Comment by FOSquare** [comment]
root@chronos:~# free
             total       used       free     shared    buffers     cached
Mem:       4028140    2701812    1326328      72536      16996     290432
-/+ buffers/cache:    2394384    1633756
Swap:      4176892     231228    3945664
=====================================
Thanks a lot.

**Comment by FOSquare** [comment]
root@chronos:~# free
             total       used       free     shared    buffers     cached
Mem:       4028140    2701812    1326328      72536      16996     290432
-/+ buffers/cache:    2394384    1633756
Swap:      4176892     231228    3945664

Thanks a lot.

**Comment by FOSquare** [comment]
total          used           free          shared       buffers     cached
Mem:       4028140    2701812    1326328      72536      16996     290432
-/+ buffers/cache:    2394384    1633756
Swap:      4176892     231228    3945664

**Comment by cardigliano** [comment]
It seems that you have just 1G free, please try running the command below before n2disk, or reduce -b 1024 and -p 512
 sync && echo 3 > /proc/sys/vm/drop_caches
