### ISSUE TITLE
How to escape equal sign in ntopng.conf

### ISSUE THREAD

**Issue by djha983** [ntop/ntopng#1798]
Hi,

In ntopng.conf an equal sign ‘=’ has to be used between key and value.
I am configuring ntopng.conf to export flows to elasticsearch and for that i am adding below entry to ntopng.conf.
-F="es;flow;ntopng-%Y.%m.%d;http://x.x.x.x:9200/_bulk?pipeline=et_ntopng_pipeline;"
in above line there is two equal sign ‘=’ and because of that export to elasticsearch not working.But same if i run ntopng from commandline by passing parameter as below it works fine.
/usr/local/bin/ntopng -F 'es;flow;ntopng-%Y.%m.%d;http://x.x.x.x:9200/_bulk?pipeline=et_ntopng_pipeline;' /run/ntopng.conf

Is it possible to escape the second equal sign in ntopng.conf so that it is not considered as key value pair and export to elasticsearch works fine.If yes how do i achieve that.Please help.

Regards,
Deepak jha

**Comment by simonemainardi** [comment]
Thanks for reporting.  Issue has been fixed and will be available in the next dev 3.5 build. Please, hold on until tomorrow.
