### ISSUE TITLE
Adding Captive Portal User

### ISSUE THREAD

**Issue by radixtenshi** [ntop/ntopng#1799]
Hello, i have exactly the same problem that in the issue [1129](https://github.com/ntop/ntopng/issues/1129)

I try to apply the patch by replacing the .lua files but dont work. Seems i have diferente version that the patch.

I cant create new user in the "Add Captive Portal User" windows.
Also, if i change the "Authentication Lifetime" options, the selection become checked for both options.

![image](https://user-images.githubusercontent.com/4320793/40632415-51a78b12-62bd-11e8-89db-999c02aaa5d8.png)

I have ntopng Enterprise Edition v.3.4.180517, i thought this issue was already fixed.

Any idea?
Thanks in advance.

**Comment by emanuele-f** [comment]
A new package will be available in one hour, thank you!

**Comment by radixtenshi** [comment]
Thanks for the fast response.
I will apply it now and confirm if works well.

**Comment by radixtenshi** [comment]
Works Fine.. thanks a lot.
