### ISSUE TITLE
Wrong Applicationname/category on Port 8530

### ISSUE THREAD

**Issue by fatlouis87** [ntop/ntopng#1800]
As we are using Wsus over Port 8530 we defined a custom protocol entry tcp:8530@WSUS
(This was working some weeks ago)

But NTOPNG changed it to be RapidVideo (Streaming as Category)

How can we change this back to our setting?

**Comment by simonemainardi** [comment]
thanks for reporting, that was due to ndpi. Fixed with: https://github.com/ntop/nDPI/commit/2b4321b5c3f8f00b99f2e52aea520c39f81a2beb
