### ISSUE TITLE
Per-Member Shapers

### ISSUE THREAD

**Issue by radixtenshi** [ntop/ntopng#1801]
Hello again. I create this case but i dontk now if this is an issue or just a wrong config.

The thing is: when i go, into the web interface,  to "manage pools" and i choose to active the option "Per-Member Shapers" for an specific host pool and then hit the "Save" button.
The web interface reload the page but the "Per-Member Shapers" feature never get active.
If i re-enter the same page to view the config.. the option appears unselected again.

![image](https://user-images.githubusercontent.com/4320793/40691762-1f63aa2e-6384-11e8-8f6b-0eb74824da47.png)

I have ntopng Enterprise Edition v.3.4.180517 in Bridge mode

Is some kind of bug? or i just need to active some other option.

**Comment by emanuele-f** [comment]
Hello, does this happen for all the pools? What about child safe and per-member quotas, do they work? Can you check the ntopng log for errors? You can do this with `journalctl -u ntopng`

**Comment by radixtenshi** [comment]
Hello, it doesn't work with any pool. Even the child safe pool or any other. I already test it.
I check the file /var/log/ntopng/ntopng.log
and i found this:

![image](https://user-images.githubusercontent.com/4320793/40739900-bd2b1726-641d-11e8-8cfd-9b0f2ddeb888.png)

Same happen if want to uncheck the "child safe" option for the "children" host pool. No change is taken.
Same if i want to add the "child safe" option for the "guest" host pool.
Could be any config file system permissions?

**Comment by emanuele-f** [comment]
Please remove the `-v` option from the ntopng configuration and restart ntopng. Now, with a clean log, please double check for errors after changing the per-member preference

**Comment by radixtenshi** [comment]
I dont start NtopNG with the -v option. I activate that option via web.

![image](https://user-images.githubusercontent.com/4320793/40806382-afbc2f46-64f7-11e8-9939-f266df235159.png)

I rotate the log, change the option to "normal", then stop and start the ntopng service and repeated the action before by doing:

- Unchek the Child Safe option for the "child" host pool. And hit Save.
- Check the Per-member Shapers option for another "host pool". And hit Save.
- Even tryed to delete the curstom host pool and cant do it. And hit Save.

Nothing is reflected into the Log. Not a single line (it is in NORMAL mode now).

**Comment by emanuele-f** [comment]
I think your configuration got corrupted due to #1799 . Can you start from scratch?
1. Stop ntopng: `systemctl stop ntopng`
2. Delete all data: `redis-cli flushall && sudo rm -rf /var/tmp/ntopng`
3. Restart ntopng: `systemctl start ntopng`

Note: this will delete all the ntopng data

**Comment by radixtenshi** [comment]
I do it... nothing change.
Any Idea?
I wish where something im doing wrong and not an issue.

**Comment by emanuele-f** [comment]
Please wait for the new nedge release, which will be available very soon.
