### ISSUE TITLE
NTOPNG Traffic Storage

### ISSUE THREAD

**Issue by dotslashniks** [ntop/ntopng#1802]
Hi Guys! 

Can you please help me with my issue regarding the traffic storage of ntopng. As you can see in the image below, this /var/db/ntopng are eating all of my hdd free space.

Is there a way to limit the disk usage for ntopng? 
If there's none... Is it okay if am going to disable the ff:

- **RRDs For Local Hosts**
- **nDPI RRDs For Local Hosts**

These two options under **Traffic Storage (RRD)** are **ENABLED**.

![ntopng](https://user-images.githubusercontent.com/39757381/40702969-9eab85fe-6398-11e8-811d-4f3dc88ae740.JPG)

Thank you, Guys!

**Comment by emanuele-f** [comment]
Hello, what ntopng version are you using? How many local hosts do you have?

**Comment by dotslashniks** [comment]
Ntopng version 0.7.2,

Local hosts are the computers connected in our local network right? We have 68 local hosts.

**Comment by emanuele-f** [comment]
Please run `ntopng --version` to get the version number.

The number of local hosts is displayed in the green badge at the bottom of the ntopng gui.

![screenshot at 2018-05-26 20-19-19](https://user-images.githubusercontent.com/5488003/40709831-5af48568-63f7-11e8-8fdd-cb81db73a234.png)

**Comment by dotslashniks** [comment]
![ntopversion](https://user-images.githubusercontent.com/39757381/40710040-77fdec3a-63ac-11e8-8a04-30f00f4f1e5b.JPG)
![ntophosts](https://user-images.githubusercontent.com/39757381/40710048-7b7a3b0c-63ac-11e8-9c8e-e620076f93e9.JPG)

We are still using the old version.

**Comment by emanuele-f** [comment]
You are using a very old version, please update to the lastest one. You should probably start from scratch as old data compatibility is probably broken.

**Comment by dotslashniks** [comment]
Yup! Am going to propose soon about getting our pfsense(including packages) to be updated. But for now, will anything might/will going to happen if I delete this /var/db/ntopng/2 ?? 

Thank you, Emanuele.

**Comment by emanuele-f** [comment]
If you delete a data folder, software will continue to work, you will only lose those data
