### ISSUE TITLE
Truncated device name

### ISSUE THREAD

**Issue by fsamareanu** [ntop/ntopng#1803]
Hello,

I'm getting (randomly) truncated names for network devices. For example:

![image](https://user-images.githubusercontent.com/38040820/40717280-cbdcc1da-641c-11e8-94da-c3942aada15b.png)

This should read "Florian's"

**Comment by emanuele-f** [comment]
Hello, can you provide a pcap of the device mdns traffic (udp port 5353)?

**Comment by fsamareanu** [comment]
Link sent via e-mail.

**Comment by emanuele-f** [comment]
Thank you. Issue is caused by the following line:

https://github.com/ntop/ntopng/blob/dev/src/Flow.cpp#L2734

and here is the related log:

```
[Flow.cpp:2738] ===>>> [16][lorian’s MacBook Pro._companion-link._tcp.local][len=35]
```
