### ISSUE TITLE
Upgrade ntopng/nprobe latest stable, no flow data

### ISSUE THREAD

**Issue by harmane** [ntop/ntopng#1804]
Hello -

I have netflow going to ntopng and nprobe (apt-stable) as collector for couple years now and after latest update I no longer see any data in ntopng. No apparent errors either though I have not done a trace:

> v.3.4.180529 [Enterprise/Professional build]
GIT rev:        3.4-stable:a38a65ec37fe30c4a45de176f274d1cbab077fdf:20180529
Pro rev:        r1591
Built on:       Debian GNU/Linux 8.2 (jessie)
System Id:      xxxxx
Platform:       x86_64
Edition:        Enterprise
License Type:   Permanent

> Welcome to nProbe v.8.4.180529 (r6121) for x86_64-unknown-linux-gnu
with native PF_RING acceleration.
Copyright 2002-18 ntop.org
Build OS:      Debian GNU/Linux 8.2 (jessie)
SystemID:     xxxxx
GIT rev:       8.4-stable:6ca2c17467db9f06872705f88f1102672ebdd05c:20180529
Edition:       nProbe Pro

nprobe-none.conf:

>--zmq="tcp://127.0.0.1:5556"
--collector-port=2055
-n=none
-i=none
-V=9
-T="%IPV4_SRC_ADDR %IPV4_DST_ADDR %IPV4_SRC_MASK %IPV4_DST_MASK %L4_SRC_PORT %L4_DST_PORT %IPV6_SRC_ADDR %IPV6_DST_ADDR %IPV6_SRC_MASK %IPV6_DST_MASK %IP_PROTOCOL_VERSION %SRC_TOS %PROTOCOL %ICMP_TYPE %INPUT_SNMP %SRC_AS %DST_AS %IPV4_NEXT_HOP %IPV6_NEXT_HOP %TCP_FLAGS %OUTPUT_SNMP %IN_BYTES %IN_PKTS %OUT_BYTES %OUT_PKTS %MIN_TTL %MAX_TTL %FIRST_SWITCHED %LAST_SWITCHED %SRC_VLAN %DST_VLAN %DOT1Q_SRC_VLAN %DOT1Q_DST_VLAN %EXPORTER_IPV4_ADDRESS %IN_SRC_MAC %IN_DST_MAC"
--zmq-probe-mode

ntopng.conf
>-d=/ntopng-data/ntopng
-G=/ntopng-data/ntopng.pid
-i=tcp://*:5556c
#-S=local
#--dns-mode=3
-m=<networks>
-X=250000
-x=250000

Both processes start on boot normally, I see flow data from core switch with tcpdump. There is definitely load on server via ntopng process just nothing visualized, no errors. I am using LDAP and neither domain users, admin or otherwise, nor local admin can view flow data.

**Comment by harmane** [comment]
When running nprobe manually and stopping after 4-ish minutes:

>30/May/2018 11:09:20 [nprobe.c:3030] Processed packets: 0 (max bucket search: 8)
30/May/2018 11:09:20 [nprobe.c:3013] Fragment queue length: 0
30/May/2018 11:09:20 [nprobe.c:3039] Flow export stats: [0 bytes/0 pkts][0 flows/0 pkts sent]
30/May/2018 11:09:20 [nprobe.c:3046] Flow collection:   **[collected pkts: 14922][processed flows: 456434]**
30/May/2018 11:09:20 [nprobe.c:3049] Flow drop stats:   [0 bytes/0 pkts][0 flows]
30/May/2018 11:09:20 [nprobe.c:3054] **Total flow stats:  [0 bytes/0 pkts][0 flows/0 pkts sent**

Should flow collection be represented in total flow stats? FWIW, on my test box using netflow from MikroTik device I do not have any issues after upgrading to same version in apt-stable (community edition).

**Comment by emanuele-f** [comment]
Hello, can you post a screenshot of the zmq interface page into ntopng?

**Comment by harmane** [comment]
@emanuele-f 

![zmq int](https://user-images.githubusercontent.com/18288828/40840127-63788f86-6573-11e8-947b-dc79491eabb3.PNG)

**Comment by simonemainardi** [comment]
do you have any disaggregation set in the Preferences->network interfaces page?

**Comment by harmane** [comment]
Yes, was VLAN id. Set to none and I still see nothing in ntopng. VLAN id was also used since I can remember it being available, well prior to this version.

edit: updated to X.4.180531 for both ntopng & nprobe and I am now seeing data in ntopng. I've left disaggregation to none for now. Does changing this require a restart of ntopng?

**Comment by simonemainardi** [comment]
Thanks for reporting.

Correct, changing the disaggregation criterion requires an ntopng restart. You can set it back to VLAN, just don't forget to restart ntopng for the setting to have effect.
