### ISSUE TITLE
Manage Pool Membership - Cant add description into "Alias" field.

### ISSUE THREAD

**Issue by radixtenshi** [ntop/ntopng#1805]
Hello again, sorry about asking all the time. I found another posible bug. 

When i try to add a description into the "Alias / Manufacturer" field on the "Manage Pool Membership" options and i hit the "Save" button... the changes are not saved.

![image](https://user-images.githubusercontent.com/4320793/40752964-45d7047a-6448-11e8-8fb1-041527b8c6e2.png)

I added single hosts by IPV4 and IPV6 before with his "Alias" comment and work well, but this happen when i try to add a vlan. Cant asign an "Alias" to a Vlan.
Is not a critical option.. but i just post it here in advice.
I dont try to add a MAC address yet, so i dont know if happen the same for MACs.

Also, when i browse any host client of this Vlan (already added to a host pool) the host appears as not in any host pool.

![image](https://user-images.githubusercontent.com/4320793/40753322-e6699762-6449-11e8-95b0-88e7099324ac.png)

All the hosts inside a Vlan, must be affected by default and auto assigned to his vlan "host pool". Must i add all the hosts one by one to the "host pool"?

Thanks.

**Comment by emanuele-f** [comment]
Hello, sorry but we will need time to verify this. Anyway, we are moving towards a new product for traffic policing. Please check out https://www.ntop.org/guides/nedge

**Comment by radixtenshi** [comment]
i Understand.. but i buy a ntop Enterprise License, not nedge. I must ask for official support for issues like this?

**Comment by emanuele-f** [comment]
I'm in the ntop team (support and dev). Maybe we can do something for the license, after we implement VLAN support in nedge.

**Comment by radixtenshi** [comment]
That will be nice once the nedge product get officially stable. We dont worry about the license price, we need an stable tool, no matter if is called ntopng or nedge. But you must to think that right now we buy ntop product purchased specifically for trafic shapping, thing that we are still not able to implement well so far for the repeated issues in the gui and we cant think on buy an aditional product if the one we have have work for what we need.

We have a medium size network with almost 3000 desktop clients, 30 CCO servers and another services and projected an expansion of double the current demand with approximately 1.8 millions flows estimated in the next 2 years, before that happens I am trying to determine the final hardware requirements for ntop what will demand an investment in hardware for which I must be sure that the product works well and its implementation is viable.

Thats the reason why we decided to buy an enterprice license with two 10/40 Gbit PF_RING licenses and we consider to buy some pluggins (elastic search, mysql and others), more PF_RING drivers, and 3 years of support for all the licenses if ntopng proves to be useful and meets our requirements.

I must to get theis product working optimally before deciding to discard it or replace it for another software.
I thank you a lot for your help and wish you understand our needs over ntopng.
Thanks a lot.

**Comment by emanuele-f** [comment]
Don't worry about the license, we can move it to the new product. nedge is really close to the final stage but we currently lack performance measurements in large environments. Please stand by while we decide the timings for the product launch.

**Comment by radixtenshi** [comment]
OK.. thanks a lot, in the meantime i keep testing ntopNG.

**Comment by emanuele-f** [comment]
Hello, nEdge is out! Please check out https://www.ntop.org/ntop/introducing-ntopng-edge-nedge-monitoring-service-segmentation-and-security-for-the-network-edge/ and https://www.ntop.org/guides/nedge/bridging.html#vlan-trunk-bridging .

Please note that we currently support only VLAN monitoring (no per-VLAN traffic policies).

**Comment by radixtenshi** [comment]
Thanks! We will watch on it.

**Comment by simonemainardi** [comment]
Hi, thanks for reporting. Alias/manufacturers are not mean to be used for networks, you can simply use the host pool name for that. Alias/manufacturers are only meaningful for hosts and mac addresses. We've fixed the GUI to prevent the field from being set with networks.
