### ISSUE TITLE
Alerts Generation Extensions

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#1808]
Discussions with users brought to light a series of conditions for which it would be desirable to have alerts generated. The conditions are summarized below:

**Security**
- [x] Detected application versions (e.g., SSH client / SSH server too old, OS outdated, vulnerable HTTP server)
- [ ] Traffic to/from blacklisted countries/continents
- [ ] Augment malware alerts with the type of malware
- [x] Probing or server down alerts (unidirectional traffic)
- [x] An host uploads/downloads a file larger than X bytes over SSH/HTTP/HTTPS

**Performance**
- [ ] Network latency variations (thresholds / baselining)
- [ ] TCP/ARP/ICMP packets ratios
- [x] Active flows with potential issues (e.g., low throughput, retransmissions)

**Application protocols**
- [ ] Detected application protocols

A more detailed description of any condition is described below.

---

_Detected application versions_

With https://github.com/ntop/ntopng/commit/34c5bce183a472c92f63b2eb3804c87a52eb30ec is now possible to report SSH client/server version

![screen shot 2017-02-11 at 11 23 50](https://cloud.githubusercontent.com/assets/4493366/22853087/ad8035a4-f04c-11e6-8ba2-9c04f8d63947.png)

It would be nice to specify (under preferences, on a file or similar) for local hosts, the minimum protocol version we consider safe and trigger alerts if some of local hosts are running old protocol versions. This way we can implement a minimal yet effective control over old software versions that can lead to security issues.

Soon this feature, currently available for SSH, should/will be implemented for other protocols such as HTTP (both server and browser version taken from the user-agent string) or OS version (e.g. NetBIOS protocol)

Source: https://github.com/ntop/ntopng/issues/979

---

_Traffic to/from blacklisted countries/continents_

As ntopng uses GeoIP, it knows what traffic belongs to what country. It is requested to define a list of blacklisted countries and generate alerts when there is an access to any of the blacklisted countries.
In inline mode (ntopng Edge) it is requested to implement block policies based on the same blacklist.

Source: https://github.com/ntop/ntopng/issues/1024
Source: https://github.com/ntop/ntopng/issues/1089
Source: https://github.com/ntop/ntopng/issues/1088

---

_Augment malware alerts with the type of malware_

See if it is possible to load a malware typology (such as C&C or Zeus or Dshield) from the downloaded blacklisted files (e.g., https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt)

Source: https://github.com/ntop/ntopng/issues/1148

---

_Probing or server down alerts_

Even though those alerts are already supported, it is requested to selectively enable/disable them for any given host.

```
Probing or server down: 10.1.1.4 > ip-37-201-5-110.hsi13.unitymediagroup.de [TCP 10.1.1.4:46092 > 37.201.5.110:8883 [proto: 0/Unknown][3/0 pkts][222/0 bytes][SYN]]
```

Source: https://github.com/ntop/ntopng/issues/1485

---
_An host uploads/downloads a file larger than X bytes over SSH/HTTP/HTTPS_

Implement a configurable alert when a host uploads/downloads a file larger than X bytes over SSH/HTTP/HTTPS

Source: https://github.com/ntop/ntopng/issues/1678

---
_Network Latency_

Network latency it is now computed for Autonomous Systems. It would be desirable to generate an alert when the latency crosses a given threshold or when it deviates significantly from a baseline. 

Source: https://github.com/ntop/ntopng/issues/495

---
_TCP/ARP/ICMP packets ratio_

For every host (interface / mac) compute the

- ARP request/response ratio
- ICMP ECHO request/response ratio
- TCP SYN/SYN_ACK ratio

Generate (local) host alerts when those ratio significantly divert from 1:1. For alert generation extend the host alert min/5min/hour/daily mechanisms already present (/lua/host_details.lua?page=alerts&tab=alert_settings)

Source: https://github.com/ntop/ntopng/issues/1085

---

_Active flows with potential issues_

Extend the current host/interface alert framework for emitting alerts when

the number of active flows with low throughput is over a threshold
the number of active flows with low retransmissions etc is over a threshold
(host only) the number of egress flows from the same client port towards remote hosts is over a threshold
the number of ICMP port/destination unreachable is over a threshold
the number of ICMP echo is over a threshold
To keep complicity low, please consider adding host counters updated with flow lifecycle.

Use this paper http://luca.ntop.org/ADS.pdf as reference

Source: https://github.com/ntop/ntopng/issues/1087

---

_Detected application protocols_

Generate an alert when a given protocol is (not) detected for a certain host or interface.

Source: https://github.com/ntop/ntopng/issues/1019

**Comment by lucaderi** [comment]
@simonemainardi This is a monster ticket. Please close it and open individual ones.

**Comment by simonemainardi** [comment]
Individual tickets for the remaining alerts are open.
