### ISSUE TITLE
Assigning several interfaces to one user

### ISSUE THREAD

**Issue by QuentinBibas** [ntop/ntopng#1810]
Hi,

Is there a way to, as the title says, assign several interfaces to one "user" ?

**Comment by emanuele-f** [comment]
Hello, you can only assign a single interface right now. You could create a view interface to achieve something similar to what you ask, e.g. `-i eth0 -i eth1 -i view:eth0,eth1` and then assign the view interface.

**Comment by QuentinBibas** [comment]
well, i've already done this.
except it would be nicer if i could assign both separate streams of a net TAP to be able to really see the inbound and outbound directions clearly split up

(knowing that my 1Gbps full duplex link is going 1.2Gbps isn't enough, as it's not critical at that point, while knowing that the inbound is currently doing 900Mbps is far more critical as it's nearly saturated)

**Comment by emanuele-f** [comment]
I understand the problem, please open a separate feature request so that we can discuss it.
