### ISSUE TITLE
Packet polling

### ISSUE THREAD

**Issue by tomoxwell** [ntop/ntopng#1811]
Packet polling takes forever after issuing the command for making the bridge

**Comment by emanuele-f** [comment]
@tomoxwell can you be more specific on the setup, command, ntopng version used? ntopng has a web gui, you have to connect to port 3000

**Comment by tomoxwell** [comment]
The bridge polling does not go beyond : started packet bridge polling for bridge : enp0s25, enp2s0

My ntopng.conf looks like below:

sudo cat /etc/ntopng/ntopng.conf
#  listen on localhost:3000 only
--http-port=:3000

# Use prefix due to nginx proxy
--http-prefix="/ntopng"

# Everybody's admin
#--disable-login=1

# Do not resolve any names
--dns-mode=3

# Limit memory usage
--max-num-flows=200000
--max-num-hosts=250000

# Dump flows to MySQL
--dump-flows=mysql;localhost;ntopng;flows;ntopng;xxx

#--verbose

I can access the gui with no problem

I am concerned though that after I issued the command ntopng -i bridge:enp0s25,enp2s0  the process does not go beyond the line below:

started packet bridge polling for bridge : enp0s25, enp2s0

and i cant do anything on the command line since it results in the ntop service exiting

**Comment by tomoxwell** [comment]
I am using version 3.4-stable

**Comment by tomoxwell** [comment]
07/Jun/2018 20:45:56 [PeriodicActivities.cpp:100] Each periodic activity script will use 2 threads
07/Jun/2018 20:45:56 [NetworkInterface.cpp:2462] Started packet polling on interface bridge:enp2s0,enp0s25 [id: 4]...
07/Jun/2018 20:45:56 [PacketBridge.cpp:1014] Started packet bridge polling for bridge:enp2s0,enp0s25

**Comment by emanuele-f** [comment]
This is normal, please check out the official documentation if you want to run ntopng as a service. https://www.ntop.org/guides/ntopng/how_to_start/running_as_a_daemon.html

**Comment by tomoxwell** [comment]
Much appreciated.Makes sense
