### ISSUE TITLE
Host Pool Top Traffic Statistics

### ISSUE THREAD

**Issue by wawava** [ntop/ntopng#1812]
Hi 
    i'm use host pool to see traffic Statistics ,when hover mouse, it display the interface traffic,can display the host pool top traffic statistics?thx
![image](https://user-images.githubusercontent.com/5871219/41146546-47585c28-6b36-11e8-80ba-faf2bfa9a25a.png)

**Comment by wawava** [comment]
ntopng version is v.3.4.180516

**Comment by emanuele-f** [comment]
Hello, this has already been reported, but, so far, this is what we have. Please see #1783 .
