### ISSUE TITLE
Licencing Issue

### ISSUE THREAD

**Issue by sticks221** [ntop/ntopng#1813]
Sorry to leave this here but doing so out of desperation...  the NTop website advises that free licences are available to non-profit organisation and hospitals (my company is both) but after sending several emails to education@ntop.org and getting no response, I wonder if anyone here can point me to someone that can help?

Thank you in advance.

**Comment by emanuele-f** [comment]
Hello, maybe there is some anti-spam taking place, please send me your email at faranda@ntop.org and I'll forward it to the appropriate person.
