### ISSUE TITLE
Dump to Disk not working

### ISSUE THREAD

**Issue by njcwotx** [ntop/ntopng#1816]
I have a new install, pro license v 3.5.180614-4540 on debian

When i check the box to dump packets to disk, no packets are being dumped.  I have tried for one flow, tried for the both interfaces.  tried 'all packets' eligibility.   tried installing n2disk to see if there was a dependency, but I recall from previous installs that this feature worked without it.  I am running as a standard user created to run the process 'ntopng'; however, I did test with root and it still does not dump any packets to disk.

Not trying to use as a long term dump to disk, only as a short term 'as needed' option.

**Comment by emanuele-f** [comment]
It was a bug, now fixed with commit f62345e0cbba901cd842626eac808607c5415799 . By the way, n2disk is not needed. A new package will be available in one hour. Thank you for reporting.
