### ISSUE TITLE
Wrong interface-core affinity

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#182]
I using the following command line:
*****************
$ ./ntopng -i zc:2@0 -i zc:2@1 -i zc:2@2 -i zc:2@3 -i view:zc:2@0,zc:2@1,zc:2@2,zc:2@3 -u -n0 -d /var/tmp/ntopng/ -r 127.0.0.1:6379 -g 3,4,5,6 -l 1 -X 262144 -x 131072  -S local
*****************
with 4 interfaces with 4 different core affinity (-g 3,4,5,6).
All the interfaces, however, are  assigned to the same core (3):
*****************
25/Sep/2015 09:36:17 [NetworkInterface.cpp:1391] Setting affinity of interface zc:2@0 to core 3
25/Sep/2015 09:36:17 [NetworkInterface.cpp:1395] Started packet polling on interface zc:2@0 [id: 0]...
25/Sep/2015 09:36:17 [NetworkInterface.cpp:1391] Setting affinity of interface zc:2@1 to core 3
25/Sep/2015 09:36:17 [NetworkInterface.cpp:1395] Started packet polling on interface zc:2@1 [id: 1]...
25/Sep/2015 09:36:17 [NetworkInterface.cpp:1391] Setting affinity of interface zc:2@2 to core 3
25/Sep/2015 09:36:17 [NetworkInterface.cpp:1395] Started packet polling on interface zc:2@2 [id: 2]...
25/Sep/2015 09:36:17 [NetworkInterface.cpp:1391] Setting affinity of interface zc:2@3 to core 3
25/Sep/2015 09:36:17 [NetworkInterface.cpp:1395] Started packet polling on interface zc:2@3 [id: 3]...
*****************
Thanks.

*****************
$ ./ntopng --version
v.2.0.150922 [Community Edition]
GIT rev:   dev:0db67b2f096b14d9283a79b575572ca0692d47e0:20150922
*****************

**Comment by kYroL01** [comment]
I tried and yes, you're right. Now i can't fix, but tomorrow i'll do it.

**Comment by gianogli** [comment]
Thanks kYroL01! :-)

**Comment by ValentinaViscarelli** [comment]
Fixed.
