### ISSUE TITLE
Captive Portal redirects for HTTPs connections

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#1820]
When the captive portal is enabled, it is requested to also redirect HTTPs connections. Even though the users will experience a certificate error, it is important to do the redirect as otherwise the network would appear to be just broken.

**Comment by emanuele-f** [comment]
HTTPs captive portal has been disabled, is this issue still relevant?

**Comment by lucaderi** [comment]
@emanuele-f I agree, no longer relevant.
