### ISSUE TITLE
SNMP average traffic is 0

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1823]
When showing the SNMP device stats the average traffic is zero
<img width="1027" alt="screen shot 2018-06-20 at 16 15 23" src="https://user-images.githubusercontent.com/4493366/41664082-2ffdeae8-74a5-11e8-9780-0da61ffe7858.png">

**Comment by emanuele-f** [comment]
Fixed in commit bd0eee177da97d6c4ec62fc8c7bcd03e8d8d4155 .
