### ISSUE TITLE
get_top_talkers.lua is returning null object 

### ISSUE THREAD

**Issue by Shivam2302** [ntop/ntopng#1825]
I am able to get json data while running get_top_realtime.lua but get_top_talkers.lua is returning [].

**Comment by emanuele-f** [comment]
Hi, get_top_talkers.lua requires the "epoch" parameter in the past, for example: `http://127.0.0.1:3000/lua/get_top_talkers.lua?addvlan=true&epoch=1529575174`. You can look at the HTTP requests made from the interface charts page when you hover the mouse over a chart (The `Minute Interface Top Traffic Statistics` table is populated from `get_top_talkers.lua`).

**Comment by Shivam2302** [comment]
Hi, even after passing epoch I am getting null object....

**Comment by emanuele-f** [comment]
Please follow my suggestion: got into the interface charts page, select 1 day resolution and then over the mouse at the beginning of the chart. If you open your browser network inspector, you can see the HTTP requests being made to ntopng.

**Comment by Shivam2302** [comment]
Even the http request is getting null object....

**Comment by emanuele-f** [comment]
What ntopng version are you using (see `ntopng --version`)? So if you hover the mouse over the chart as described above, do you always get an empty `Minute Interface Top Traffic Statistics` table?

**Comment by Shivam2302** [comment]
Thanks it worked .....
