### ISSUE TITLE
Flow export to logstash

### ISSUE THREAD

**Issue by srikrishna0130** [ntop/ntopng#1829]
I have tried out the export to log-stash feature in ntopng , but the exported flows gives only limited data compared to the flow details in ntopng gui.
How do I get more data for the exported flows from ntopng (most of the data in the info section in flows in ntopng)?

**Comment by emanuele-f** [comment]
Hello, currently the flow information exported to logstash / elastic search is the one generated by this function: https://github.com/ntop/ntopng/blob/dev/src/Flow.cpp#L1799 .

If you feel some important fields are missing, please open a separate feature request and list such fields there.
