### ISSUE TITLE
ntopng for windows crashing after two days.

### ISSUE THREAD

**Issue by andrewObie** [ntop/ntopng#1831]
I'm running ntopng on a windows 2016 box.  I had it running first on an unbuntu server and both versions are crashing after about two days.  I can't find any logs in the windows directories and the linux logs are long gone.

I'm just using ntopng /i -i 2 -m 10.0.0.0/8

as my service command (we are a large network with around 15k hosts and 38 locations)

I'm curious if that local network segment is too large, but I can't tell anything with no logs available in windows.

all I can get is the runtime log on a crash and then restart, but here it is even though it's not very useful:

**Comment by andrewObie** [comment]
25/Jun/2018 10:15:41 [PeriodicActivities.cpp:100] Each periodic activity script will use 2 threads
25/Jun/2018 10:15:41 [PeriodicActivities.cpp:59] Started periodic activities loop...
25/Jun/2018 10:15:41 [NtopPro.cpp:519] [LICENSE] Validity:	Until Mon Jun 25 10:25:39 2018
25/Jun/2018 10:15:41 [NtopPro.cpp:510] [LICENSE] License Type:	Demo License
25/Jun/2018 10:15:41 [NtopPro.cpp:509] [LICENSE] Edition:	Enterprise
25/Jun/2018 10:15:41 [NtopPro.cpp:508] [LICENSE] System Id:	3327079648-7104a1d2
25/Jun/2018 10:15:41 [Ntop.cpp:401] Built on Windows
25/Jun/2018 10:15:41 [Ntop.cpp:391] Welcome to ntopng x64 v.3.4.180417 - (C) 1998-18 ntop.org
25/Jun/2018 10:15:41 [main.cpp:388] Scripts/HTML pages directory: C:\Program Files\ntopng
25/Jun/2018 10:15:41 [main.cpp:386] Working directory: C:\Windows\Temp\ntopng
25/Jun/2018 10:15:41 [HTTPserver.cpp:934] HTTP server listening on port(s) 3000
25/Jun/2018 10:15:41 [HTTPserver.cpp:931] Web server dirs [C:\Program Files\ntopng\httpdocs][C:\Program Files\ntopng\scripts]
25/Jun/2018 10:15:41 [HTTPserver.cpp:860] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
25/Jun/2018 10:15:41 [HTTPserver.cpp:858] HTTPS Disabled: missing SSL certificate C:\Program Files\ntopng\httpdocs/ssl/ntopng-cert.pem
25/Jun/2018 10:15:40 [Ntop.cpp:1626] Registered interface {92CEAAEB-A1EF-4FB6-80E4-1B71FBEDBD17} [id: 0]
25/Jun/2018 10:15:40 [PcapInterface.cpp:91] Reading packets from interface {92CEAAEB-A1EF-4FB6-80E4-1B71FBEDBD17}...
25/Jun/2018 10:15:39 [NtopPro.cpp:366] WARNING: [LICENSE] ntopng --community
25/Jun/2018 10:15:39 [NtopPro.cpp:365] WARNING: [LICENSE] or run ntopng in community mode starting
25/Jun/2018 10:15:39 [NtopPro.cpp:363] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
25/Jun/2018 10:15:39 [NtopPro.cpp:361] WARNING: [LICENSE] before returning to community mode
25/Jun/2018 10:15:39 [NtopPro.cpp:359] WARNING: [LICENSE] ntopng will now run in enterprise edition for 10 minutes
25/Jun/2018 10:15:39 [NtopPro.cpp:342] WARNING: [LICENSE] Invalid or missing license
25/Jun/2018 10:15:39 [NtopPro.cpp:260] [LICENSE] Reading license from Redis
25/Jun/2018 10:04:27 [NetworkInterface.cpp:2472] Started packet polling on interface {92CEAAEB-A1EF-4FB6-80E4-1B71FBEDBD17} [id: 0]...
25/Jun/2018 10:04:27 [PeriodicActivities.cpp:100] Each periodic activity script will use 2 threads
25/Jun/2018 10:04:27 [PeriodicActivities.cpp:59] Started periodic activities loop...
25/Jun/2018 10:04:27 [NtopPro.cpp:519] [LICENSE] Validity:	Until Mon Jun 25 10:14:23 2018
25/Jun/2018 10:04:27 [NtopPro.cpp:510] [LICENSE] License Type:	Demo License
25/Jun/2018 10:04:27 [NtopPro.cpp:509] [LICENSE] Edition:	Enterprise
25/Jun/2018 10:04:27 [NtopPro.cpp:508] [LICENSE] System Id:	3327079648-7104a1d2
25/Jun/2018 10:04:27 [Ntop.cpp:401] Built on Windows

**Comment by andrewObie** [comment]
To cull it down (the /8 range) I focused in on two of our main octects, so now I'm running -m -m 10.50.0.0/16, 10.84.0.0/16 to see if it helps

**Comment by andrewObie** [comment]
Ive now paired it down with the actual networks we are using.  We will see if that helps

 10.50.0.0/16,10.84.0.0/16,10.85.0.0/16,10.86.0.0/16,10.87.0.0/16,10.88.0.0/16,10.89.0.0/16,10.90.0.0/16,10.91.0.0/16,10.94.0.0/16,10.95.0.0/16,10.96.0.0/16,10.97.0.0/16,10.98.0.0/16,10.100.0.0/16,10.101.0.0/16,10.102.0.0/16,10.103.0.0/16,10.104.0.0/16,10.105.0.0/16,10.106.0.0/16,10.107.0.0/16,10.108.0.0/16,10.109.0.0/16,10.110.0.0/16,10.111.0.0/16,10.112.0.0/16,10.113.0.0/16,10.114.0.0/16,10.115.0.0/16,10.117.0.0/16,10.118.0.0/16,10.119.0.0/16,10.120.0.0/16,10.121.0.0/16,10.122.0.0/16,10.123.0.0/16,10.124.0.0/16,10.125.0.0/16,10.127.0.0/16

**Comment by emanuele-f** [comment]
Hello, let's stick to the ubuntu version (which ubuntu version exactly?) until we understand the issue. Please run `ntopng --version` to get the ntopng version number. What command are you executing to retrieve the logs? Normally you can do this with `sudo journalctl -u ntopng`

**Comment by andrewObie** [comment]
It's crashing again, randomly even with the entire subnets defined rather than 10.0.0.0/8 so that's not the issue.

I'll have to fire back up the ubuntu server again and get it running, I'll let you know in a about an hour of the options you asked me.  I'm not sure how to retrieve the logs so I will run those commands in Ubuntu and do some research before responding.  I built a ntopng server on windows because I had a free server in our rack and was perfect for this.

I am running ubuntu 18.04, but the desktop version on an i5 PC (dell) with 16GB ram because I couldnt get the server OS to allow remote access and to see the second interface.  It worked great on ubuntu and I even got it to run 2 days before crashing.

I will get back to you with the info you asked for within the hour.  Thanks for your help.

**Comment by emanuele-f** [comment]
The latest Windows build has documented crashes ( see #1781 ). So please check out the ubuntu version for now.

**Comment by andrewObie** [comment]
Thanks.  The ubuntu version was crashing as well though, so I'm going to gather the data requested today and post it here from the logs there, give me the morning and I'll get the provided info from the ubuntu crashes.  Had to run off site yesterday Thanks.

**Comment by andrewObie** [comment]
This is my ubuntu build version:

v.3.2.171227	[Community build]
GIT rev:	:3.2.171227

**Comment by emanuele-f** [comment]
Version 3.2 is outdated, please update to the new stable version (3.4) from http://packages.ntop.org/

**Comment by andrewObie** [comment]
-- Logs begin at Thu 2018-05-03 15:53:44 CDT, end at Tue 2018-06-26 09:17:59 CDT. --
May 04 07:28:31 ntop systemd[1]: Starting ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool...
May 04 07:28:31 ntop ntopng[10647]: 04/May/2018 07:28:31 [Ntop.cpp:1485] Setting local networks to 127.0.0.0/8
May 04 07:28:31 ntop ntopng[10647]: 04/May/2018 07:28:31 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
May 04 07:28:31 ntop ntopng[10647]: 04/May/2018 07:28:31 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
May 04 07:28:31 ntop ntopng[10647]: 04/May/2018 07:28:31 [Ntop.cpp:1422] Parent process is exiting (this is normal)
May 04 07:28:31 ntop systemd[1]: Started ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool.
May 04 07:28:32 ntop ntopng[10647]: sh: 1: netstat: not found
May 04 07:28:33 ntop ntopng[10674]: [Trace.cpp:118] ERROR: Unable to create log /var/log/ntopng/ntopng.log
May 04 07:28:49 ntop ntopng[10674]: [NetworkInterface.cpp:1936] WARNING: If you have TSO/GRO enabled, please disable it
May 04 07:28:49 ntop ntopng[10674]: [NetworkInterface.cpp:1938] WARNING: Use sudo ethtool -K enp3s0 gro off gso off tso off
May 04 07:30:25 ntop systemd[1]: Stopping ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool...
May 04 07:31:55 ntop systemd[1]: ntopng.service: State 'stop-sigterm' timed out. Killing.
May 04 07:31:55 ntop systemd[1]: ntopng.service: Killing process 10674 (ntopng) with signal SIGKILL.
May 04 07:31:55 ntop systemd[1]: ntopng.service: Killing process 10741 (ntopng) with signal SIGKILL.
May 04 07:31:55 ntop systemd[1]: ntopng.service: Main process exited, code=killed, status=9/KILL
May 04 07:31:55 ntop systemd[1]: ntopng.service: Failed with result 'timeout'.
May 04 07:31:55 ntop systemd[1]: Stopped ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool.
May 04 07:31:55 ntop systemd[1]: Starting ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool...
May 04 07:31:55 ntop ntopng[11056]: 04/May/2018 07:31:55 [Ntop.cpp:1485] Setting local networks to 127.0.0.0/8
May 04 07:31:55 ntop ntopng[11056]: 04/May/2018 07:31:55 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
May 04 07:31:55 ntop ntopng[11056]: 04/May/2018 07:31:55 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
May 04 07:31:56 ntop ntopng[11056]: 04/May/2018 07:31:56 [Ntop.cpp:1422] Parent process is exiting (this is normal)
May 04 07:31:56 ntop systemd[1]: Started ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool.
May 04 07:31:56 ntop ntopng[11056]: sh: 1: netstat: not found
May 04 07:31:57 ntop ntopng[11071]: [Trace.cpp:118] ERROR: Unable to create log /var/log/ntopng/ntopng.log
May 04 07:32:11 ntop systemd[1]: Stopping ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool...
May 04 07:33:41 ntop systemd[1]: ntopng.service: State 'stop-sigterm' timed out. Killing.
May 04 07:33:41 ntop systemd[1]: ntopng.service: Killing process 11071 (ntopng) with signal SIGKILL.
May 04 07:33:41 ntop systemd[1]: ntopng.service: Killing process 11084 (ntopng) with signal SIGKILL.
May 04 07:33:41 ntop systemd[1]: ntopng.service: Main process exited, code=killed, status=9/KILL
May 04 07:33:41 ntop systemd[1]: ntopng.service: Failed with result 'timeout'.
May 04 07:33:41 ntop systemd[1]: Stopped ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool.
-- Reboot --
May 04 07:34:28 ntop systemd[1]: Starting ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool...
May 04 07:34:31 ntop ntopng[768]: 04/May/2018 07:34:31 [Ntop.cpp:1485] Setting local networks to 127.0.0.0/8
May 04 07:34:31 ntop ntopng[768]: 04/May/2018 07:34:31 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
May 04 07:34:31 ntop ntopng[768]: 04/May/2018 07:34:31 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
May 04 07:34:33 ntop ntopng[768]: 04/May/2018 07:34:33 [Ntop.cpp:1422] Parent process is exiting (this is normal)
May 04 07:34:33 ntop systemd[1]: Started ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool.
May 04 07:34:34 ntop ntopng[848]: [Trace.cpp:118] ERROR: Unable to create log /var/log/ntopng/ntopng.log
May 04 07:36:53 ntop ntopng[848]: [NetworkInterface.cpp:1936] WARNING: If you have TSO/GRO enabled, please disable it
May 04 07:36:53 ntop ntopng[848]: [NetworkInterface.cpp:1938] WARNING: Use sudo ethtool -K enp3s0 gro off gso off tso off
May 04 07:37:30 ntop ntopng[848]: [NetworkInterface.cpp:1936] WARNING: If you have TSO/GRO enabled, please disable it
May 04 07:37:30 ntop ntopng[848]: [NetworkInterface.cpp:1938] WARNING: Use sudo ethtool -K lo gro off gso off tso off
May 04 13:34:39 ntop systemd[1]: Stopping ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool...
May 04 13:36:09 ntop systemd[1]: ntopng.service: State 'stop-sigterm' timed out. Killing.
May 04 13:36:09 ntop systemd[1]: ntopng.service: Killing process 848 (ntopng) with signal SIGKILL.
May 04 13:36:09 ntop systemd[1]: ntopng.service: Main process exited, code=killed, status=9/KILL
May 04 13:36:09 ntop systemd[1]: ntopng.service: Failed with result 'timeout'.
May 04 13:36:09 ntop systemd[1]: Stopped ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool.

**Comment by andrewObie** [comment]
That's the logs.  Here is my current plan:

I'm going to rebuild the windows 2016 server i have in my rack and put ubuntu server 18.04 and configure ntop with all my subnets for local traffic as the post says above with all my -m networks defined.

I will use the newest build from your link 3.4 and we can go from there.

In the meantime just peak at the logs and see if anything jumps out at you.  

Thanks for your help and quick response

**Comment by andrewObie** [comment]
Here is my issue now:

The RAID controller driver for the rack server I have available doesn't support ubuntu, it only supports these distros according to the README:

Operating System Support
The following operating systems are supported:
• FreeBSD 7.4 and 8.1 (x86 & amd64)
• Linux (x86 and x86_64)
o Fedora Core 11 & later
o Red Hat Enterprise Linux 5.4 & later
o openSUSE 11.1 & later
o SUSE Linux Enterprise Server (SLES) 11 & later 

I'm going to try to get it to load on ubuntu, but if I can't, which flavor of linux above would you recommend to run ntop on?  I'd rather stay away from paid versions for the time being.

Thanks,

**Comment by andrewObie** [comment]
**update it looks as if  ubuntu 18.04 is installing fine on the rack mounted server.  The RAID was detected.  Hopefully I shouldnt need another distro

Will keep up to date if I run into issues.

**Comment by andrewObie** [comment]
I am now successfully running stable build 3.4 on 18.04 ubuntu server in the rack that was previously windows 2016.

I will update this thread as content happens and if it continues to run through friday with no issues I will close the issue.

Thanks again.

**Comment by emanuele-f** [comment]
Thank you for the update, please let me know.

**Comment by andrewObie** [comment]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/95/66/udp.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/95/66/tcp.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/95/66/num_flows.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/95/66/bytes.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/84/133/icmp.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/84/133/udp.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/84/133/tcp.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/84/133/num_flows.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/84/133/bytes.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/254/10/icmp.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/254/10/udp.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/254/10/tcp.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/254/10/num_flows.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/254/10/bytes.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/91/74/icmp.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/91/74/udp.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/91/74/tcp.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/91/74/num_flows.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/91/74/bytes.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/124/22/icmp.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/124/22/udp.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/124/22/tcp.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/124/22/num_flows.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/50/124/22/bytes.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/107/100/52/icmp.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/107/100/52/udp.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/107/100/52/tcp.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/107/100/52/num_flows.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/107/100/52/bytes.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/101/100/24/icmp.rrd [Cannot create temporary file]
26/Jun/2018 11:15:03 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/101/100/24/udp.rrd [Cannot create temporary file]

**Comment by andrewObie** [comment]
nothing happening out the ordinary yet, but just checked the runtime status and the above is showing, not sure if its significant.

**Comment by emanuele-f** [comment]
Do you have free disk space? What ntopng options are you using?

**Comment by andrewObie** [comment]
500gb Array, only 3.1% in use right now.  We do have a lot of hosts but plenty of disk space.  I'm only using basic default config with -m for local networks right now.

**Comment by emanuele-f** [comment]
Maybe it is a permission issue. Please ensure that the directory `/var/tmp/ntopng/0/rrd/10/101/100/24/` is owned by the user which is running also ntopng, or add the `-s` option to ntopng to run as root as last resort.

**Comment by andrewObie** [comment]
Those temp files have "no owner".  They are all the subnet IP temp directories I defined with -m.  I'm looking into taking ownership of the entire /rrd/10/* files

**Comment by emanuele-f** [comment]
You can use the -U option to specify a user for ntopng. ntopng will start as root but will drop privileges to the specified user.

```
[--user|-U] <sys user>              | Run ntopng with the specified user
```

**Comment by andrewObie** [comment]
I'm having the same temp file errors but I've successfully run ntopng 3.4 stable build now for over a week which is the longest I've run it.  It's on ubuntu 18.04.

The permission issues are weird, but that's going to be another issue, I'm resolving this ticket bc my original issue has been resolved.  Thanks Emanuele-F

**Comment by emanuele-f** [comment]
Thank you for reporting. I'm going to verify this new issue on ubuntu 18 as other users experienced this.

**Comment by emanuele-f** [comment]
I've opened this issue #1848
