### ISSUE TITLE
Parameters of JSON in mysql

### ISSUE THREAD

**Issue by ruchi09** [ntop/ntopng#1832]
What are all the parameters "JSON" attribute is giving while exporting the ntopng data through mysql?

![my_sql_json_cropped](https://user-images.githubusercontent.com/19363256/41864913-1aca1426-78c9-11e8-8495-68c92e4a9c5b.png)

**Comment by emanuele-f** [comment]
Please check out https://github.com/ntop/ntopng/blob/dev/src/Flow.cpp#L1799 .
