### ISSUE TITLE
TimeSeriesExporter compile Error on version 3.4

### ISSUE THREAD

**Issue by ummeegge** [ntop/ntopng#1833]
Hello,
i do have currently a problem to compile the new 3.4 version (tested with stable and version from dev branch from today). The build process throws an error on TimeSeriesExporter  and stops at this point.

`
                                            ^
In file included from /usr/include/fcntl.h:313:0,
                 from /usr/src/ntopng/include/ntop_includes.h:84,
                 from src/TimeSeriesExporter.cpp:22:
In function 'int open(const char*, int, ...)',
    inlined from 'void TimeSeriesExporter::createDump()' at src/TimeSeriesExporter.cpp:77:12:
/usr/include/bits/fcntl2.h:50:24: error: call to '__open_missing_mode' declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
    __open_missing_mode ();
    ~~~~~~~~~~~~~~~~~~~~^~
make[1]: *** [Makefile:167: src/TimeSeriesExporter.o] Error 1
make[1]: Leaving directory '/usr/src/ntopng'
make: *** [ntopng:93: /usr/src/log/ntopng-3.4.220618] Error 2
`

You can find the complete build log in here --> https://people.ipfire.org/~ummeegge/ntopng/build_logs/TimeSeriesExporter_compile_error.txt  .

My system is an IPFire system based on LFS Linux.

Best regards,

Erik

**Comment by emanuele-f** [comment]
By searching the issue on the web, it seems like the open function (in TimeSeriesExporter::createDump) on your system requires three arguments. Please check out https://github.com/pantheon-systems/fusedav/issues/204 .

**Comment by ummeegge** [comment]
Hello emanuele-f,
this fixed the problem thanks for providing the link to this solution.

Best regards,

Erik

**Comment by emanuele-f** [comment]
Glad it helped.
