### ISSUE TITLE
InfluxDB / Grafana, show "realtime" data rate

### ISSUE THREAD

**Issue by m4ntic0r** [ntop/ntopng#1834]
For some time i am trying to solve a problem, but i dont know how i can achive this.

1. I want to have real time or ~10s stats for my wan bandwidth (down/upload) in grafana
-> [This in Grafana](https://mm-vault.de/chevereto/image/7BgN)
2. I have configured a mirror port on my netgear switch from the port on which the wan router is connected
3. I have a ntopng running, that mirror port is analyzed and i get all stats in ntopng
4. I have a full working influxdb/grafana/telegraf setup

I tried the ntopng plugin for grafana, but even it says connection ok, i dont get any stats..

Today i saw, that there is influxdb beta support on the latest ntopng. I created a new influxdb database and configured the ntopng as described here: https://github.com/ntop/ntopng/blob/dev/doc/README.influxdb

Now i get measurements in the influxdb database, but when i tried making my graphs i realized that i get data for **"iface:localstats:local2remote"** only in an 60s interval into my indluxdb database.

**Is there an option to configure this value?**

[Actual graph](https://mm-vault.de/chevereto/image/7ZHH)
[Settings](https://mm-vault.de/chevereto/image/7cx8)
Unit = bytes/sec

**Comment by emanuele-f** [comment]
Hello, this is currently not configurable. However, you could manually edit https://github.com/ntop/ntopng/blob/dev/scripts/callbacks/system/second.lua :

- Add `local minute_schema = require("ts_minute")` under `local ts_schemas = require("ts_second")`.
- Add the following inside the `callback_utils.foreachInterface` function:
```
  if(ifstats["localstats"]["bytes"]["local2remote"] > 0) then
    ts_utils.append(minute_schema.iface_local2remote, {ifid=ifstats.id, bytes=ifstats["localstats"]["bytes"]["local2remote"]}, when)
  end

  if(ifstats["localstats"]["bytes"]["remote2local"] > 0) then
    ts_utils.append(minute_schema.iface_remote2local, {ifid=ifstats.id, bytes=ifstats["localstats"]["bytes"]["remote2local"]}, when)
  end
```

**Comment by m4ntic0r** [comment]
thanks for your answer but i have an other problem

i saw that my second.lua looks different because i was on the latest stable ntopng.
i changed my sources.list from:

deb http://packages.ntop.org/apt-stable/stretch/ x64/
deb http://packages.ntop.org/apt-stable/stretch/ all/

to

deb http://packages.ntop.org/apt/stretch/ x64/
deb http://packages.ntop.org/apt/stretch/ all/

and upgraded.

but now i dont get any stats on my previous working graph.

i saw that the url changed:
-3. run `redis-cli set "ntopng.prefs.ts_post_data_url" "http://<host where Influx is running>:8086/write?db=ntopng"`
+3. run `redis-cli set "ntopng.prefs.ts_post_data_url" "http://<host where Influx is running>:8086"`

so i changed this too, but no difference.. i rolled back my vmware snapshot with ntopng stable and everything is working again. Tried with the nightly ntopng again, but no data in influxdb :(

i dont get it because in my influxdb access log i see the same entrys with stable vs nightly:

192.168.2.34 - - [26/Jun/2018:17:53:23 +0200] "POST /write?db=ntopng HTTP/1.1" 204 0 "-" "-" 0e6f7198-7959-11e8-9428-000000000000 1309
192.168.2.34 - - [26/Jun/2018:17:53:32 +0200] "POST /write?db=ntopng HTTP/1.1" 204 0 "-" "-" 13cd29f0-7959-11e8-9435-000000000000 1753
192.168.2.34 - - [26/Jun/2018:17:53:44 +0200] "POST /write?db=ntopng HTTP/1.1" 204 0 "-" "-" 1af45405-7959-11e8-9445-000000000000 1107
192.168.2.34 - - [26/Jun/2018:17:53:56 +0200] "POST /write?db=ntopng HTTP/1.1" 204 0 "-" "-" 221b4e46-7959-11e8-9453-000000000000 1187

**Comment by emanuele-f** [comment]
Influxdb format has been changed in dev. Please try to execute the following query inside influx:
`select * from "iface:traffic" limit 10`

If you get results, then influx export is working properly. Please check out the new timeseries schemas format at https://github.com/ntop/ntopng/tree/dev/scripts/lua/modules/timeseries/schemas

Edit: Please also check out https://github.com/ntop/ntopng/blob/dev/doc/README.timeseries for an introduction on the new timeseries framework

**Comment by m4ntic0r** [comment]
oh yes, complete different format, but i think i have done it now. i added your lines and got 1s interval of the metrics. i have done 10s grouping for my graphs and the values seems to be right. to complete the issue here my actual graphs and settings in grafana for other users:

[Graph of my 100/40 line](https://mm-vault.de/chevereto/image/7JXx)
I was watching a stream and then a full download of an iso file.

[Query for download](https://mm-vault.de/chevereto/image/7dl5)
*8 for mbit, OFFSET 1 because of this [influxdb issue](https://github.com/influxdata/influxdb/issues/6451)

[Query for upload](https://mm-vault.de/chevereto/image/7l9W)

thanks emanuele-f, and i hope this helps other people with an similar issue.

**Comment by emanuele-f** [comment]
Thank you very much for your contribution.

**Comment by m4ntic0r** [comment]
did a update today but this is not working anymore.. with the lines there is only a 1min interval again.

**Comment by emanuele-f** [comment]
You are working on dev, api has changed! See 5d50622341d0fe3908e7f92e59b990ee8a899447 . Just replace:

- `minute_schema.iface_local2remote` with `"iface:local2remote"`
- `minute_schema.iface_remote2local` with `"iface:remote2local"`
