### ISSUE TITLE
ntopng on windows 2008 R2 crash every 5 min

### ISSUE THREAD

**Issue by Oxyde59** [ntop/ntopng#1836]
Hi,

I running Ntopng on a physical server on 2008R2 up to date, and it crash every 5-10 min.

What do u need for debug ?

Here is eventvwr log :
Nom de l’application défaillante ntopng.exe, version : 0.0.0.0, horodatage : 0x5ad64960
Nom du module défaillant : ntopng.exe, version : 0.0.0.0, horodatage : 0x5ad64960
Code d’exception : 0xc0000005
Décalage d’erreur : 0x0000000000443fef
ID du processus défaillant : 0x16c8
Heure de début de l’application défaillante : 0x01d40d1fcd8e3ceb
Chemin d’accès de l’application défaillante : C:\Program Files\ntopng\ntopng.exe
Chemin d’accès du module défaillant: C:\Program Files\ntopng\ntopng.exe
ID de rapport : e895e50b-7913-11e8-b3ea-00188b8c6c67

Ntopng version : 

Version | 3.4.180417 - Professional Edition
built on : Windows
nDPI : 2.3.0-1121-3443928
cURL : 7.39.0
3.x
4.x
RDDtool : 1.4.5
Rredis server : 2.4.6
Mongoose web server : 3.7
LuaJIT 2.1.0-beta3
ØMQ : 4.1.3
GeoIP 1.6.11  This product includes GeoLite data created by MaxMind.
Data-Driven Documents (d3js) : 2.9.1 / 3.0

**Comment by emanuele-f** [comment]
Duplicate of #1781 .
