### ISSUE TITLE
Define protos.txt with IP or domains from the GUI

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#1837]
It is requested to implement custom protocol definitions into the ntopng gui. This will greatly simply the task of defining custom protocols, which now requires manual proto.txt creation.

**Comment by emanuele-f** [comment]
Dropping this in favor of #1974 . Users can now add custom IP/domains to categories from the gui.

**Comment by simonemainardi** [comment]
Well, this is different, actually. protos.txt allows you to create new custom protocols and to associate traffic to protocols using ports, things that are not possible with the implementation of #1974

**Comment by lucaderi** [comment]
In essence it is required
1. to add the ability to define new nDPI protocols (based on IP, port or names) using a preference similar to what happens with other ntopng options
2. enable people to define new protocols based on flows. For instance when there is a flow that needs to be classified as "custom protocol X", add the ability to do it with a few mouse clicks

**Comment by emanuele-f** [comment]
Some notes (documentation will be written after preliminary feedback and changes).
- Editor is only enabled if the `-p option` is specified
- Categories are only enabled after restarting ntopng. This is a limitation of the current nDPI api
- This implementation maintains compatibility with `protos.txt`. Future work may follow to drop the support for protos.txt and unify the implementation with the categories
