### ISSUE TITLE
SNMP Top Interfaces is Wrong

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1838]
As explained in #1823 not only the average traffic is wrong, but also the interfaces depicted in the graph are NOT the top interfaces in terms of traffic on the selected visualised period, but they are randomly picked interfaces. 
It is requested to depict the top interfaces with traffic in the select period (not the interface with top traffic since the beginning epoch, but top traffic on the selected epoch). It would be nice to see on graph an extra dummy "other" interface with the total traffic of non-depicted interfaces. If too complex an easier solution will also work, this to let user  understand what potion of the overall traffic has been depicted.

**Comment by emanuele-f** [comment]
Fixed in commit bd0eee177da97d6c4ec62fc8c7bcd03e8d8d4155 . Also added the dummy "other" serie.
