### ISSUE TITLE
SNMPv3 support?

### ISSUE THREAD

**Issue by mcs123** [ntop/ntopng#1839]
Are there any plans to support SNMPv3? My organization only allows for that, and we're currently using the Enterprise version of ntopng.

**Comment by lucaderi** [comment]
the SNMP library we're using does not support v3 and extending it with v3 support will take a lot of time. We need to find alternatives and see how to accommodate them.

**Comment by erg809** [comment]
This should be priority for NtopNG development team, an enterprise solution without support for SNMPv3?  By law is absolutely prohibited to run any unsecure SNMP version in our network.  We are talking about 800 Switches only, on top of that, add routers, firewalls and appliances of all types.  I hope that you can add this feature soon.

Cheers,
E.R

**Comment by lucaderi** [comment]
Implemented with today's commit. Note that it's available only on dev builds and it will be merged with the next stable release.
