### ISSUE TITLE
 Ntopng Pfsense PPPoE server Clients Not monitoring 

### ISSUE THREAD

**Issue by shahid30** [ntop/ntopng#1841]
I have installed ntopng in pfsense . It is monitoring dhcp clients very well but not showing any data of PPPoE server clients .  Any help about ?

**Comment by emanuele-f** [comment]
Hello, what ntopng configuration are you using? Can you describe your network setup?

**Comment by shahid30** [comment]
I let The default Configuration.

**Comment by shahid30** [comment]
Here Is My configuration that I tried.

![1a](https://user-images.githubusercontent.com/40720201/42164201-baf99912-7e1e-11e8-858c-f96973ce2273.png)
![2](https://user-images.githubusercontent.com/40720201/42163954-e81e85ca-7e1d-11e8-9c4f-516bb4550b22.png)
![3](https://user-images.githubusercontent.com/40720201/42163979-02c5d540-7e1e-11e8-9cac-2184b343dbe7.png)
![4](https://user-images.githubusercontent.com/40720201/42163987-065b8e70-7e1e-11e8-991e-011b48cc2369.png)
![5](https://user-images.githubusercontent.com/40720201/42163991-089a1fd0-7e1e-11e8-8401-270c885c2e37.png)
![6](https://user-images.githubusercontent.com/40720201/42163996-0aa160a4-7e1e-11e8-9103-40e4e04e0e25.png)
![7](https://user-images.githubusercontent.com/40720201/42164002-0c79a13e-7e1e-11e8-8858-acf91031020d.png)
![8](https://user-images.githubusercontent.com/40720201/42164020-1a627d16-7e1e-11e8-80c3-79a8ebf68b99.png)
![9](https://user-images.githubusercontent.com/40720201/42164022-1dbb7576-7e1e-11e8-8d79-475679a4a438.png)
![10](https://user-images.githubusercontent.com/40720201/42164030-228ffcca-7e1e-11e8-85c8-111bc2af3653.png)

**Comment by emanuele-f** [comment]
What's the output of `ifconfig` in your sever? Have you tried selecting an interface from the "Interfaces" menu into the gui?

**Comment by shahid30** [comment]
Yes I selected the interface Lan on which the pppoe server is active
![ifcofig](https://user-images.githubusercontent.com/40720201/42165663-2d05f052-7e22-11e8-86c4-81f354c27fda.png)

**Comment by emanuele-f** [comment]
So the interface is em1 right? Can you provide a pcap capture? Please run `sudo tcpdump -i em1 -s 0 -n -w ppoe.pcap` and let it run for some seconds. Then send the pcap to faranda@ntop.org .

**Comment by shahid30** [comment]
Yes em1 interface and my server is not replying this command so what can I do now ?

**Comment by emanuele-f** [comment]
You have to execute this from command line (e.g. ssh), you cannot do this from the gui

**Comment by shahid30** [comment]
ok

**Comment by shahid30** [comment]
It is taking to long to command . please tell how to abort and collect ppoe.pcap file ?

**Comment by lucaderi** [comment]
PPPoE is supported in the latest devel version of ntopng. You can check this using this pcap https://github.com/aol/moloch/blob/master/tests/pcap/pppoe.pcap (ntopng -i pppoe.pcap)
Please update and it should also work for you
