### ISSUE TITLE
SNMP does not use v2c after initial device add

### ISSUE THREAD

**Issue by cjwbath** [ntop/ntopng#1847]
I have some SNMP v2c-only devices I want to add to ntopng (Enterprise Edition v.3.4.180628) but they show as not responsive in the UI after adding them to the list. 

When I tcpdump on the ntopng server as I add the device, I see an initial GetRequest for _sysName_ that honours my choice of v2c in the version dropdown. But then every subsequent interaction with that device tries to use v1 and fails because the device doesn't respond to that version.

**Comment by cjwbath** [comment]
Actually if I set v2c as a global preference for the SNMP version then it is used. So it seems the global setting is always used instead of the per-device setting. The devices still show as not responding though even though I can see responses from them in the tcpdump.

**Comment by emanuele-f** [comment]
Hello, this should be already fixed in dev version (3.5). It includes gui changes, so we cannot backport the fix to stable. Please check out the dev version if possible until a new stable is released.

**Comment by emanuele-f** [comment]
@cjwbath any update?

**Comment by cjwbath** [comment]
Hi, I didn't want to install the dev version in production and will just make do without the SNMP support until 3.5 is stable. As I mentioned, setting v2c globally does get around some of the problems.

**Comment by emanuele-f** [comment]
Ok, I'm closing the issue for now.

**Comment by simonemainardi** [comment]
I can confirm the issue has been solved in 3.5
