### ISSUE TITLE
Cannot create temporary file on ubuntu 18.04

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#1848]
Reported by the users, some errors like the following:

```
ERROR: Unable to create /var/tmp/ntopng/0/rrd/10/101/100/24/udp.rrd [Cannot create temporary file]
```

**Comment by emanuele-f** [comment]
The issue is related to the directory permissions. It can only reproduced sometimes. Here is the directory output when it occurs:

```
$ sudo ls -ld /var/tmp/ntopng/
drwx------ 4 nobody nogroup 4096 lug  6 11:22 /var/tmp/ntopng/

$ sudo ls -ld /var/tmp/ntopng/1
drwx------ 6 nobody nogroup 4096 lug  6 11:22 /var/tmp/ntopng/1

$ sudo ls -ld /var/tmp/ntopng/1/rrd
drwx------ 4 nobody nogroup 4096 lug  6 11:22 /var/tmp/ntopng/1/rrd

$ sudo ls -l /var/tmp/ntopng/1
total 16
drwx------ 2 nobody nogroup 4096 lug  6 11:21 alerts
drwx------ 4 nobody nogroup 4096 lug  6 11:22 rrd
d--x------ 2 nobody nogroup 4096 lug  6 11:22 subnetstats
drwx------ 2 nobody nogroup 4096 lug  6 11:22 top_talkers
```

subnetstats directory does not have read/write permissions. However, it is created by `Utils::mkdir_tree` which should create it with `0700` permission. When trying to write to it, the following error occurs:

```06/Jul/2018 11:22:00 [Lua.cpp:3912] ERROR: Unable to create /var/tmp/ntopng/1/subnetstats/127/0/0/0/8/bytes.rrd [Cannot create temporary file]```

**Comment by 2stacks** [comment]
I just did a fresh install today and have the same issue.

Ubuntu 18.04 LTS (GNU/Linux 4.15.0-23-generic x86_64)

installed with apt-ntop-stable.deb

**Comment by emanuele-f** [comment]
Hi, you should be able to manually modify the directory permissions to 700 to circumvent it until the bug is fixed.

**Comment by 2stacks** [comment]
It appears that every time a new directory or file is created the permissions are wrong.  I'm just testing at the moment so I'm not worried but changing the permissions manually or with a cron would have to be done every minute.

**Comment by 2stacks** [comment]
Adding this to root's crontab seems to be working.
```
* * * * * chmod -R u+rwx /var/tmp/ntopng
```

**Comment by emanuele-f** [comment]
Thank you for the tip.

**Comment by simonemainardi** [comment]
Can you guys try and see what happens if your run ntopng with a user that is different from `nobody`? You can use option `--user` for that. Make sure to `chown` the existing data directory to be owned by that user before running ntopng.

**Comment by bioteseo** [comment]
It's ok only if you use as user root (of course). With other user the issue remains.
I noticed that at a level folder depth, the permission for dirs and files aren't correct:
for some dirs are drwx------ 2 nobody nogroup (I think this is correct) and others d--x------ 2 nobody nogroup
for some files are -rw-r--r--  1 nobody nogroup (I think this is correct) and others ----rw-rw-  1 nobody nogroup
Apparently the depth is random.
I'm using last ntopng dev version: Version 3.5.180726 - Community Edition on Ubuntu server 18.04 LTS.

Thanks

**Comment by simonemainardi** [comment]
can you also create another user, say ntopng with group ntopng and report? thank you

**Comment by bioteseo** [comment]
Maybe I'm not being clear. I tried as you suggest but the issue remain. With root all is ok (of course).
In all cases (user nobody, myuser, root) the situation about the wrong permission for files and dirs is the same as I showed above.

**Comment by zxyz** [comment]
same problem here with centos 7.5 and ntong v.3.5.180730. 

`[LuaEngine.cpp:7187] [ERROR] POST of /var/tmp/ntopng/-1/ts_export/1532935739 failed`

under `/var/tmp/ntopng` there are also the directories `0`,`1` and `4` without any permission problems (but not `ts_export` directory). 
the permissions under ` /var/tmp/ntopng/-1/ts_export/` are:

------S--x. 1 nobody nobody 295512 Jul 30 09:30 1532935816

I change them with  `chmod u+rwx *`:

`-rwx--S--x. 1 nobody nobody 2308 Jul 30 09:30 1532935827`

after a ew seconds the dir is gone and a new one with wrong permissions is there:

`------S--x. 1 nobody nobody 956 Jul 30 09:30 1532935849`

**Comment by simonemainardi** [comment]
@zxyz  can you please show me the all the options you've used to start ntopng?

**Comment by simonemainardi** [comment]
can you guys check if apparmor (ubuntu18) is logging denials?

**Comment by zxyz** [comment]
@simonemainardi here we go:
```
-G=/var/run/ntopng.pid
-i=eno1
-i=eno2
-w=3000
-W=3001
-m=192.168.0.0/18,10.3.0.0/16
-n=1
-d=/var/tmp/ntopng
-p=/etc/ntopng/custom.protos
-X 600000
--user root
-F "mysql;localhost;ntopng;flows;ntop;password"
```
I couldn't find any relating selinux entries in `/var/log/audit/audit.log`.

**Comment by simonemainardi** [comment]
@zxyz , rather than specifying `--user root` can you please try and add `--dont-change-user=` to the configuration file? Please report

**Comment by bioteseo** [comment]
> can you guys check if apparmor (ubuntu18) is logging denials?
Hi Simone, I don't think it's an apparmor problem because the strange permissions.
However I didn't find in my syslog evidence of apparmor by searching audit, profile and DENIED keywords.

I turned off apparmor by
sudo systemctl stop apparmor.service
Then I started ntopng and the issue remain....
ERROR: Error 'opening '/var/tmp/ntopng/6/rrd/MDNS.rrd': Permission denied' while calling rrd_fetch_r(/var/tmp/ntopng/6/rrd/MDNS.rrd, AVERAGE): is the RRD corrupted perhaps?

$ ll /var/tmp/ntopng/6/rrd/MDNS.rrd
----rw-rw- 1 nobody nogroup 34640 lug 19 06:17 /var/tmp/ntopng/6/rrd/MDNS.rrd

I tried as you suggest to @zxyz, I used the --dont-change-user= option. Before to start ntopng I deleted all files in /var/tmp/ntopng
Now the issue is disappear :-)....because ntopng run as root I suppose?
ps aux | grep ntop
root     25842 99.0  1.8 2066240 600552 ?      Ssl  09:56   1:05 /usr/local/bin/ntopng /run/ntopng.conf

**Comment by simonemainardi** [comment]
@bioteseo I think you did't check the permissions between stopping apparmor and starting ntopng.

Can you please report the behavior after the following steps
- stop app armor
- rm -rf /var/tmp/ntopng
- start ntopng without any user change (that is let it run with user nobody)

**Comment by Kaldek** [comment]
@simonemainardi I just did the above and I'm not getting the errors anymore.  Ubuntu Server 18.04 LTS with ntopng Enterprise Edition v.3.4.180726.

There are, however, no apparmor log entries showing any denies of any kind.  I am an AppArmor n00b though.

Here's the status of AppArmor with it running:

apparmor module is loaded.
19 profiles are loaded.
19 profiles are in enforce mode.
   /sbin/dhclient
   /snap/core/4917/usr/lib/snapd/snap-confine
   /snap/core/4917/usr/lib/snapd/snap-confine//mount-namespace-capture-helper
   /usr/bin/lxc-start
   /usr/bin/man
   /usr/lib/NetworkManager/nm-dhcp-client.action
   /usr/lib/NetworkManager/nm-dhcp-helper
   /usr/lib/connman/scripts/dhclient-script
   /usr/lib/snapd/snap-confine
   /usr/lib/snapd/snap-confine//mount-namespace-capture-helper
   /usr/sbin/tcpdump
   lxc-container-default
   lxc-container-default-cgns
   lxc-container-default-with-mounting
   lxc-container-default-with-nesting
   man_filter
   man_groff
   snap-update-ns.core
   snap.core.hook.configure
0 profiles are in complain mode.
0 processes have profiles defined.
0 processes are in enforce mode.
0 processes are in complain mode.
0 processes are unconfined but have a profile defined.

**Comment by simonemainardi** [comment]
@Kaldek sorry I have given several instructions above. Can you please list exactly what did you do.

**Comment by Kaldek** [comment]
@simonemainardi I did exactly this:

sudo service ntopng stop
sudo service apparmor stop
sudo rm -rf /var/tmp/ntopng
sudo service ntopng start

Restarting AppArmor did not affect ntopng; it kept working fine with no log errors.

**Comment by simonemainardi** [comment]
this new commit https://github.com/ntop/ntopng/commit/493351226a9e56c4e91b10c5de49471bbff0035f

has introduced a fix that might address the issue. Please try and report

**Comment by zxyz** [comment]
@simonemainardi `--dont-change-user=` did also work. I just updated to 3.5.180806, did a `chown -R  nobody:nobody /var/tmp/ntopng` and till now it seems to work.

**Comment by lucaderi** [comment]
Will the above commit (or workaround if you wish as IMHO Ubuntu18 behaves in a strange way) it now works for me.
