### ISSUE TITLE
LDAP authentication not attempted

### ISSUE THREAD

**Issue by cjwbath** [ntop/ntopng#1851]
In ntopng Enterprise Edition v.3.4.180628 I have configured LDAP/Local auth (or just LDAP, the issue is the same). When trying to authenticate it just fails as though receiving a bad password, and I see nothing related to LDAP in the application logs or when doing a tcpdump for traffic towards the expected LDAP server. Also I see nothing when capturing all TCP traffic for ports 389 or 636. So it is as though LDAP is not even being attempted?

I am using Debian 9 and got the package from http://packages.ntop.org/apt-stable/. Saw someone had this  issue elsewhere and the LDAP module hadn't been compiled into the package?

**Comment by emanuele-f** [comment]
Hi, the LDAP support is enabled in debian 9. Have you followed our configuration guide: https://github.com/ntop/ntopng/blob/dev/doc/README.LDAP ? In particular, please see the *IMPORTANT* section. Are you using SSL or plain LDAP?

**Comment by cjwbath** [comment]
Thanks, I did follow the configuration guide but am struggling to find any logs to debug this. As I say it appears no traffic is even attempted towards the LDAP servers so it's hard to look at more specific issues like bind credentials or groups being wrong. I have tried both SSL and plain LDAP - we have both AD and OpenLDAP and I've tried both.

**Comment by emanuele-f** [comment]
That's strange, ntopng generates errors when there are issues with LDAP settings. Can you send me configuration screenshots at faranda@ntop.org?

**Comment by emanuele-f** [comment]
I'm reproducing this on debian 9. I'm debugging this.

**Comment by emanuele-f** [comment]
The new stable package contains the fix.
