### ISSUE TITLE
Host pool shows more hosts than expected

### ISSUE THREAD

**Issue by sciolto** [ntop/ntopng#1852]
This is our Host Pool list: 
![image007](https://user-images.githubusercontent.com/1811941/42441032-914cca28-8367-11e8-8481-3c67bbdfea6a.png)

When we add a new hosts to a new pool like this: 
![image004](https://user-images.githubusercontent.com/1811941/42441296-1ecd4fda-8368-11e8-8d22-bbe29140b652.png)

The new Host Pool shows 2370 hosts, instead of 1: 
![image005](https://user-images.githubusercontent.com/1811941/42441118-cc51f17a-8367-11e8-9f6f-02538133b440.png)

The Host Pool configuration only shows this address in its configuration. 
![image006](https://user-images.githubusercontent.com/1811941/42441064-a4fe0df2-8367-11e8-94d6-5bb184736f0d.png)

It looks like the hosts which were previously shown as "No assigned" are being assigned to the new Pool.

**Comment by emanuele-f** [comment]
Hello, the host you are assigning to the pool is probably a gateway, so all the remote hosts will be assigned to the host pool as well. If you want to avoid this behavior, please manually replace the "Member Address" with the IP address
