### ISSUE TITLE
Add user defined blacklist

### ISSUE THREAD

**Issue by jppo** [ntop/ntopng#1853]
Hello,
The lua script to load "blacklists" has the list of sources "in the code", should it be possible to add  local file to store more sources which will not be overwritten by new versions when upgrading.

Regards

JP Pozzi

**Comment by emanuele-f** [comment]
Hello, in dev there is an initial support for this: please check out https://github.com/ntop/ntopng/tree/dev/httpdocs/other/lists . You can add a custom list there. Take malware.txt as an example.

**Comment by jppo** [comment]
Hello, 

Thanks for your fast answer but my thought was not to have the urls in the code, but to store urls in a separate file. 
So every user could modify the file to its preferences without touching the code. 

Regards 

JP Pozzi

**Comment by emanuele-f** [comment]
You mean a file outside our data directory? Please note that if you create a new file under `/usr/share/ntopng/httpdocs/other/lists` with your own list, and it won't be overwritten after a ntopng update. You can even modify the file permissions and ownership.

**Comment by jppo** [comment]
Hello, 

Will try, thanks. 

Regards 

JP Pozzi

**Comment by emanuele-f** [comment]
Closing as the requested feature is already implemented. Please open a new request if you have other needs.
