### ISSUE TITLE
Implement system interface

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1854]
In ntopng it is time to implement a system interface used to monitor the system where ntopng is running on. This interface will be responsible to monitor the system interfaces, host system statistics, as well SNMP that is currently mi-placed on the ntopng menubar.

**Comment by emanuele-f** [comment]
Implemented in https://github.com/ntop/ntopng/commit/5f9e8b17df20a018a67f65fcdefd176f168f3a51 , additional commits will follow

**Comment by emanuele-f** [comment]
The implementation has been approved, further development will follow in #1855
