### ISSUE TITLE
Implement system monitoring

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1855]
Once #1854 is implemented, the system interface must contain detailed statistics about the system on which ntopng is running including (but not limited to)
- network interfaces
- CPU and memory
- containers (initially something like https://github.com/lucaderi/sgr/tree/master/2018/Sturba could be enough)

**Comment by emanuele-f** [comment]
As internally discussed, this new monitoring layer should be:

- Be modular. Each element will be handled by a separate script
- Possibly reuse existing monitoring scripts (e.g. in the standard nagios format)
- Use spike charts to show realtime data (when polling is not expensive)

The components to monitor:
- [x] CPU: a 1 second chart resolution must be provided
- [x] InfluxDB: health and disk occupacy
- [x] Disk: occupacy vs free available space (datadir)
- [x] Redis (via the exposed C methods)
- [ ] Mysql
- [ ] nProbe
- [ ] n2disk

**Comment by simonemainardi** [comment]
System monitoring implemented in the latest ntopng 4.1. 

System monitoring is available under the system inteface

![image](https://user-images.githubusercontent.com/3397663/85278046-ac712380-b484-11ea-9ebd-a42d68e2c659.png)

![image](https://user-images.githubusercontent.com/3397663/85278171-daeefe80-b484-11ea-9ebc-bafdc841eec5.png)


Modularity is achieved by means of plugins.

nProbe and n2disk are monitored inside individual interfaces.
