### ISSUE TITLE
Pushing data to logstash

### ISSUE THREAD

**Issue by ruchi09** [ntop/ntopng#1858]
Is it possible to push network discovery data and host info to logstash? If so then where can we find these data in source code?

**Comment by emanuele-f** [comment]
Hello, network discovery data is not exported right now. Host information ca be exported in json format from this url `/lua/manage_data.lua`.

**Comment by ruchi09** [comment]
Thanks!

**Comment by ruchi09** [comment]
Hi,
I am able to get the discovered mac and ip from NetworkDiscovery.cpp and am storing them as a pair in a set.


NetworkDiscovery.h:
```
set< pair<string,string> > mac_ip;
```

NetworkDiscovery.cpp:
```
mac_ip.insert(make_pair(Utils::formatMac(arp.arph.arp_sha, macbuf, sizeof(macbuf)),
                           Utils::intoaV4(ntohl(arp.arph.arp_spa), ipbuf, sizeof(ipbuf)))); 

```
I am trying to retrieve the data for each system discovered by doing the following:

```
void NetworkDiscovery::network_discovery_data2json()
{

  json_object *my_object;
  set< pair<string,string> >::iterator it;

  for( it = mac_ip.begin() ; it!=mac_ip.end(); ++it)
  {

    string mac_addr = it->first;
    string ip_addr  = it->second;

    const char* mmm = mac_addr.c_str();
    const char* ip = ip_addr.c_str();


    u_int8_t _mac[6];
    sscanf(mmm,"%hhx:%hhx:%hhx:%hhx:%hhx:%hhx",&_mac[0],&_mac[1],&_mac[2],&_mac[3],&_mac[4],&_mac[5]);
    NetworkInterface *net;

    Mac *m = net->getMac(_mac,false);
   

    if(m)
    {
      my_object = m->getJSONObject(); 
      char *rsp;
      rsp = strdup(json_object_to_json_string(my_object));
      /*
        Next will be the code to push this json to logstash
      */
    }

  }
}
```

Above function is written in NetworkDiscovery.cpp. But the ntopng crashes when getMac is executed.

Is this the right way to get the data?
How can I get the info from c++ itself?
Is it possible to get the host details in the similar fashion (for discovered IPs)?
Which function will export the data to logstash?

**Comment by emanuele-f** [comment]
Hello, you should use the `iface` field of NetworkDiscovery. Your `net` pointer is not initialized. You also need to dealloc the json with `json_object_put`.

**Comment by ruchi09** [comment]
thanks

**Comment by emanuele-f** [comment]
Anyway, this is not the correct way to extract discover data. Please look at this script which is responsible for populating the network discovery table you see on the ntopng gui. https://github.com/ntop/ntopng/blob/dev/scripts/lua/get_discover_data.lua . The relevant function to extract the cached discovery data is `discover.discover2table(ifname)`. You can `tprint` a variable to print on the console output its contents for debugging. Currently logstash export is limited to flows export, so I see it difficult to integrate this new data. I suggest you to look at the logstash HTTP api to figure out how to feed data into logstash and then use one of the ntopng http request methods to send the data to logstash https://www.ntop.org/guides/ntopng/api/lua_c/ntop/ntop_network.html . So the implementation is only Lua code.

**Comment by ruchi09** [comment]
thanks
