### ISSUE TITLE
Windows 10 - pcapng files with '-i file_path' option does not process file

### ISSUE THREAD

**Issue by HP-xyz** [ntop/ntopng#1860]
Hi,

Basically I have the exact same issue as this person http://lists.ntop.org/pipermail/ntop/2016-August/019337.html.

If I start ntopng with "/C -i file_path.ncapng" my log outputs the following:

Scenario 1: Not reading packets from file
```
12/Jul/2018 12:30:31 [Ntop.cpp:1626] Registered interface file_path.pcapng [id: 2]
...Other log lines related to HttpServer etc
12/Jul/2018 12:34:00 [NetworkInterface.cpp:2472] Started packet polling on interface file_path.pcapng [id: 2]...
12/Jul/2018 12:34:00 [PcapInterface.cpp:155] No more pcap files to read
```

Whereas with the same file converted to pcap using editcap (from wireshark), I get:

Scenario 2: Reading packets from file
```
12/Jul/2018 12:32:02 [PcapInterface.cpp:67] Reading packets from pcap file file_path.pcap...
12/Jul/2018 12:32:02 [Ntop.cpp:1626] Registered interface file_path.pcap [id: 5]
...Other log lines related to HttpServer etc (same as above)
12/Jul/2018 12:32:03 [NetworkInterface.cpp:2472] Started packet polling on interface file_path.pcap [id: 5]...
12/Jul/2018 12:32:03 [PcapInterface.cpp:230] Terminated packet polling for file_path.pcap
```

I'm running the newest update of Windows 10, using the Win10Pcap driver that installs with ntopng v.3.4.180417. I think this might be a bug in Win10Pcap since searching around and trying other drivers makes this work, but breaks other things. Specifically using the npcap driver breaks binding to an interface.

Do you guys have any ideas/workarounds that will allow me to read pcapng files on Windows 10, while using the Win10Pcap driver?

Thanks

**Comment by lucaderi** [comment]
Please try to use https://nmap.org/npcap/ instead of Win10Pcap. and it should work. Otherwise the other workaround is to convert first pcapng into pcap and pass it to ntopng.
