### ISSUE TITLE
Releases not added to tags since 3.2

### ISSUE THREAD

**Issue by vgavro** [ntop/ntopng#1862]
There are non-debian distros that relies on building from source code, and it would be easier to use tag and centralized versioning instead of using branch. It would be very convenient if you consider to add tags for stable versions and patches.

**Comment by emanuele-f** [comment]
Hi, you suggest to use tags in addition to branches, right? If I backport a fix to a tagged branch, do I have to retag something?

**Comment by simonemainardi** [comment]
3.4 stable tag added, thanks for reporting
