### ISSUE TITLE
Integrate n2n for remote assistance

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1864]
n2n2 (https://github.com/ntop/n2n) should be integrated in order to enable (on demand) users to securely remote connect to ntopng instances

**Comment by emanuele-f** [comment]
Implemented in eac278a28dda8e75e2270f34b042dc20dfd8d284 . Documentation is still missing.

**Comment by emanuele-f** [comment]
Refined in commit de5a58ecf303e07ec8dac98a1cfed80dc62ba9d2 . Documented.
