### ISSUE TITLE
Use REST API in web app to get data 

### ISSUE THREAD

**Issue by bheda91** [ntop/ntopng#1866]
Scenario: 
I have a requirement to get data from ntopng & manipulate it and show data in our custom web app. So, I want to get data in JSON format using REST API.

Tried below:
I can get data by pasting direct URL in browser. But when I try to call it using REST API, it respond with 302 error code and location as '/' in response header. 

I try with allow to CORS in REST API call, but in response I get, "No 'Access-Control-Allow-Origin' header is present on the requested resource.".

Can anyone please help me how may I integrate ntopng in my custom web app?

Thanks!

**Comment by emanuele-f** [comment]
Hello, what url are you using? You need to authenticate with the server, see the curl example here https://github.com/ntop/ntopng/tree/dev/doc .

Please don't forget to add proper ntopng credits and if you find your implementation nice maybe you can provide a public contribution too!

**Comment by bheda91** [comment]
Hello,

I am using this URL - http://192.168.6.183:3000/lua/network_load.lua
If I post this URL in browser, it shows me the JSON response. 

Can you please provide me a example, how to use same example you show using curl in my web app using RESTful API?

Thanks!

**Comment by bheda91** [comment]
Hello,

I tried first "http://192.168.6.183:3000/authorize.html" with search params { user: 'admin', password: 'admin', referer: '192.168.6.183:3000' }

And on successful response, 
I tried above URL with credentials. 

Above stuff works, 
If I disable web security in browser. i.e. **open a new chrome browser which allow access to no 'access-control-allow-origin'header request**

Now, my question is, how can we do, **CORS headers add to the backend server to allow cross origin access?**

Thanks!

**Comment by emanuele-f** [comment]
You can manually add the CORS header into this function: https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/lua_utils.lua#L151

**Comment by bheda91** [comment]
Ok I will try this and let you know. Thanks!

**Comment by bheda91** [comment]
Hello,

I added CORS headers in response, but "authorize.html" redirect root HTML page (i.e. '/' location) instead of JSON response that user is authorize or not. 
And while redirecting it sends 302 status code.

Now, I have another question, how may I write lua script to authorize user which respond with JSON instead of HTML page? (Whether it is possible or not? and if possible how?)

Thanks!

**Comment by simonemainardi** [comment]
If you are trying to programmatically fetch ntopng pages when ntopng is protected by a password, you just have to pass a cookie or authentication credentials along with the request. For example, to fetch the `network_load.lua` page you've highlighted above you can do

```
simone@devel:~/ntopng$ curl --cookie "user=admin; password=admin1" "http://127.0.0.1:3001/lua/network_load.lua?ifid=0"
{"breed":{"Safe":7612,"Acceptable":898217},"remote2local":83013,"alerts_stored":true,"bytes":11062250,"speed":1000,"system_host_stats":{"mem_total":16259948,"mem_free":8766884,"mem_shmem":165396,"mem_buffers":911344,"mem_used":3583544,"cpu_idle":2336997706,"mem_sreclaimable":452240,"mem_cached":2711332,"cpu_load":5966973},"epoch":1532523899,"num_flows":24,"hosts_pctg":1,"remote_bps":0,"tcpPacketStats":{"retransmissions":0,"out_of_order":5,"lost":5},"num_hosts":20,"profiles":[],"is_view":false,"drops":0,"local2remote":63739,"uptime":"31:12","num_local_hosts":12,"ifname":"eno1","flows_pctg":1,"num_devices":15,"packets":26802,"remote_pps":0,"engaged_alerts":0,"localtime":"15:04:59 +0200"}
```

Keep in mind that currently we don't support a public/documented REST API so endpoints can change at any time. What we preserve is the functionality of the web interface.

**Comment by swathinsankaran** [comment]
> Hello,
> 
> I added CORS headers in response, but "authorize.html" redirect root HTML page (i.e. '/' location) instead of JSON response that user is authorize or not.
> And while redirecting it sends 302 status code.
> 
> Now, I have another question, how may I write lua script to authorize user which respond with JSON instead of HTML page? (Whether it is possible or not? and if possible how?)
> 
> Thanks!

Could you please let me know how you solved the issue?

Thanks,
Swathin
