### ISSUE TITLE
Question: I just upgraded from 3.2.? -> 3.4.180712 Community Edition

### ISSUE THREAD

**Issue by showipintbri** [ntop/ntopng#1867]
When I logged in for the first time after upgrading I saw a new dashboard on the home screen. Also there was an additional item under 'Dashboards' at the top and another item in the top choices, 1 was for "SNMP" it was next to "interfaces" at the top.

After logging out and back in I can no longer see those additional items.

Where ave they gone?

How can I get them back?

**Comment by lucaderi** [comment]
These are premium features available only in demo mode for 10 mins. If you want them permanently you need a license of you can add --community for staying in the community edition
