### ISSUE TITLE
nProbe doesn't process packets 

### ISSUE THREAD

**Issue by touatily** [ntop/ntopng#1868]
I am using ntopng v.2.3.160415 and nProbe v.8.5.180703

When I run:

> sudo nprobe -i none -b 2 -9 ~/stats --zmq "tcp://127.0.0.1:5556" --collector-port 2055 -n none
> ntopng -i "tcp://127.0.0.1:5556"

I see that nProbe is collecting packets, but it tells: `Processed Packets 0`

> 19/Jul/2018 11:07:00 [nprobe.c:3196] Current flow export rate: [0.0 flows/sec]
> 19/Jul/2018 11:07:00 [nprobe.c:3199] Flow drops: [export queue too long=0][too many flows=0][ELK queue flow drops=0]
> 19/Jul/2018 11:07:00 [nprobe.c:3204] Export Queue: 0/512000 [0.0 %]
> 19/Jul/2018 11:07:00 [nprobe.c:3209] Flow Buckets: [active=0][allocated=0][toBeExported=0]
> 19/Jul/2018 11:07:00 [nprobe.c:3245] Collector Threads: [2 pkts@0]
> 19/Jul/2018 11:07:00 [nprobe.c:3026] Processed packets: 0 (max bucket search: 0)
> 19/Jul/2018 11:07:00 [nprobe.c:3009] Fragment queue length: 0
> 19/Jul/2018 11:07:00 [nprobe.c:3035] Flow export stats: [0 bytes/0 pkts][0 flows/0 pkts sent]
> 19/Jul/2018 11:07:00 [nprobe.c:3042] Flow collection:   [collected pkts: 2][processed flows: 0]
> 19/Jul/2018 11:07:00 [nprobe.c:3045] Flow drop stats:   [0 bytes/0 pkts][0 flows]
> 19/Jul/2018 11:07:00 [nprobe.c:3050] Total flow stats:  [0 bytes/0 pkts][0 flows/0 pkts sent]

Could the problem be the license ?

**Comment by emanuele-f** [comment]
Please open an issue here https://github.com/ntop/nProbe .
Please also update ntopng to the latest version as you are using a very old one.
