### ISSUE TITLE
is it possible to create a raw field of ntopng fields in Kibana ?

### ISSUE THREAD

**Issue by AlekMarkus** [ntop/ntopng#187]
Hello ,

i'm using logstash for other application to view in Kibana and i noticed that when im log for example

IIS/Apache/nagios i can see Example field and Exmaple.raw Field

in raw field i have more information than none raw. 

for example i took nagios_hostname

 we can see hosts name like : ilo , sap etc..(incorrect names)
![none-raw](https://cloud.githubusercontent.com/assets/13960741/10147439/ac424bec-6636-11e5-938c-883646bd3743.png)

when i choose nagios_hostname.raw field , Now we can see the correct names

![raw](https://cloud.githubusercontent.com/assets/13960741/10147469/d6f15b12-6636-11e5-9981-677d50fabbbc.png)

and this is example of ntopng that i choose HTTP_URL field

and we can see strange urls (not full url)
![ntopng-none-raw](https://cloud.githubusercontent.com/assets/13960741/10147539/2fd3acbc-6637-11e5-952b-44133b9a3036.png)

at Discover tab we can see HTTP_URL field with correct urls
![discover](https://cloud.githubusercontent.com/assets/13960741/10147616/b5434da8-6637-11e5-9637-0d57c30150ef.png)

is it possible to fix this ?

**Comment by lmangani** [comment]
This aspect can be controlled with mappings - by default, Logstash creates a .raw not_analyzed version of strings - the same can be achieved for your ntopng index, ie:

<pre>
"dynamic_templates" : [ {
  "string_fields" : {
    "match" : "HTTP_URL",
    "match_mapping_type" : "string",
    "mapping" : {
      "type" : "string", "index" : "analyzed", "omit_norms" : true,
      "fields" : {
        "raw" : {"type": "string", "index" : "not_analyzed", "ignore_above" : 256}
      }
    }
  }
} ],
</pre>

mind this results in higher consumption - fields can also be set to not _analyzed

<pre>
"dynamic_templates" : [ {
  "string_fields" : {
    "match" : "HTTP_URL",
    "match_mapping_type" : "string",
    "mapping" : {
      "type" : "string", "index" : "not_analyzed", "omit_norms" : true
    }
  }
} ],
</pre>

We are working on a full template for ntopng for upcoming versions.

**Comment by AlekMarkus** [comment]
Great ! thanks lorenzo

**Comment by lmangani** [comment]
This <a href="https://github.com/lmangani/ntopng-output-elasticsearch/blob/master/ntopng-es-template.json">template</a> should mimic the .raw behaviour as well as retain the other ntopng fields. If you want to give it a try and provide feedback that would be great!

**Comment by AlekMarkus** [comment]
yes the template working.

but i removed line 23 and then the geo started to work too , before i removed it so the type wasn't

geo_point

**Comment by lmangani** [comment]
template corrected! So, this covers both .raw and geo_point correctly?

**Comment by AlekMarkus** [comment]
Yep , thanks :)
