### ISSUE TITLE
Support for ignoring vlan tags

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#1870]
Hi,

We're port-mirroring our transit links to a machine running ntopng for analysis.

If a flow comes in via one transit link, and out via another, ntopng treats them as separate flows as the vlan tags are different.

Ultimately it's all the same traffic and we want to ignore the vlan tags.

Would it be possible to add this feature?

**Comment by ghost** [comment]
Looks like other people are facing similar issues. This chap fixed it by modifying the ntop source to always set the vlan_id to 0:

https://superuser.com/questions/1220844/linux-remove-vlan-tag-from-frame

**Comment by simonemainardi** [comment]
Hi, thanks for pointing this out.

We've implemented this request in the latest dev branch. Packages will be available from tomorrow.

You can run ntopng as:

```
./ntopng --ignore-vlans <other options>
```

to forcefully ignore all the vlan identifiers from the traffic.
