### ISSUE TITLE
Slack Alerting webhook channel override thats a way to do it...

### ISSUE THREAD

**Issue by firetoole** [ntop/ntopng#1873]
Hi curious if there is a reason you dictate the Slack channels for this integration and override the webhooks default settings. I cant imagine this is useful for anyone that already has established Slack alerting for any other systems.
Typically the way I have seen this implemented is either set the channel override much like you have the Slack user override, or not set the channel and leave it as the webhooks default channel (probably going to be the single channel used for alerting multiple systems)

**Comment by simonemainardi** [comment]
In the latest dev you can chose/specify any slack channel as shown below

![image](https://user-images.githubusercontent.com/3397663/43203618-0d03b6ae-901f-11e8-94bd-874c73244bb1.png)

If that is not enough to achieve the behavior you are looking for, then please try and give an example.

**Comment by simonemainardi** [comment]
Solution proposed. No feedback received in 6 days. Closing. Please, reopen with the requested information if necessary.
