### ISSUE TITLE
query.lua:22: attempt to index field 'range' (a nil value)

### ISSUE THREAD

**Issue by Gelob** [ntop/ntopng#1874]
When I visit lua/modules/grafana/query.lua i get the following error

```
HTTP/1.1 500 Internal server error
Content-Type: text/html
Connection: close

<html><head><title>ntop</title></head><body><img src=/img/warning.png> Script &quot;/usr/share/ntopng/scripts/lua/modules/grafana/query.lua&quot; returned an error:
<p><H3>/usr/share/ntopng/scripts/lua/modules/grafana/query.lua:22: attempt to index field 'range' (a nil value)</H3></body></html>

```

I also see the following when running ntopng on cli

20/Jul/2018 21:22:44 [LuaEngine.cpp:8220] WARNING: Script failure [/usr/share/ntopng/scripts/lua/modules/grafana/query.lua][/usr/share/ntopng/scripts/lua/modules/grafana/query.lua:60: attempt to call global 'rrd2json' (a nil value)]

/usr/bin/ntopng --version
v.3.5.180720    [Enterprise/Professional build]
GIT rev:        dev:a4da1294e6320d1c4f72fa9d976457560edc958c:20180720
Pro rev:        r1751
Built on:       CentOS Linux release 7.5.1804 (Core)
Platform:       x86_64
Edition:        Enterprise
License Type:   Time-Limited
Validity:       Until Fri Jul 20 21:33:47 2018

Grafana gets the same error when trying to pull the data
Happens on latest version as well: dev:594c0e4dc87f4f909093792ecb9869ff4f223c28:20180723

**Comment by simonemainardi** [comment]
Currently, we have implemented influxdb support and we are discussing internally if we should drop the ntopng grafana datasource in favour of the influxdb one. For this reason I am leaving this issue on hold.

An ntopng user who choses to use influxdb to store the timeseries will automatically benefit from the influxdb datasource http://docs.grafana.org/features/datasources/influxdb/  to access all the existing ntopng-generated timeseries.

See https://github.com/ntop/ntopng/blob/dev/doc/README.influxdb if you want to try and use influxdb.
