### ISSUE TITLE
NTOPNG not showing pages visited by hosts

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#1875]
Hi everyone hope someone can help me

My NTOPNG set-up on my macOS is not showing me the sites visited by the hosts on my network. It does show the internal sites visited (such as when my PC is logged into NTOPNG it shows the webpage im on, but not websites like google.com or facebook.com.

As you see here is my active flows page

![image](https://user-images.githubusercontent.com/31342930/43032443-6ba5f76c-8cfa-11e8-9934-50093bffc65f.png)

And here is my HTTP page of my PC im on now which should show some websites in the Last 5 Minute Sites? But only shows the contacts within the LAN (my server-imac.local / ntopng server)
![tempsnip2](https://user-images.githubusercontent.com/31342930/43032453-a08abbd4-8cfa-11e8-8a6a-cbbda3cd175e.png)

What i am trying to get working is for my ntopng to show my the websites that are being viewed by my devices/hosts. Such as if i went to google.com on my phone it would show on NTOPNG.

thanks everyone :)
daniel2029

**Comment by simonemainardi** [comment]
You just have to make sure the traffic between your devices/hosts and the Internet goes through ntopng. Very likely, that traffic is currently not visible by ntopng. Indeed, I can see from the flows page screenshot you've reported that all the servers are broadcast addresses or ips local to the lan. 

There are at least a couple of ways you can use to make sure ntopng sees the traffic. You can use the mirror port of your switch, or you can use a TAP. This resource describes them accurately: https://www.ntop.org/nprobe/network-monitoring-101-a-beginners-guide-to-understanding-ntop-tools/
