### ISSUE TITLE
Implement user with limited admin capability

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1876]
In ntopng there is the concept of admin and non-admin user. The problem is that admin can do everything, but non-admin users can only see what is happening. The consequence is that even minimal administrative rights to a non-admin user are not allowed. For instance it is not possible for a non-admin user to do things like reset statistics, or label a host.
It is requested to introduce a new set of capabilities (to be discussed) that can be associated with non-admin users for allowing them to perform specified limited actions.

**Comment by simonemainardi** [comment]
This concept of admin capabilities has been expanded in https://github.com/ntop/ntopng/issues/4700 which supersedes this ticket.

Admin capabilities are already coded in a bitmap and added to lua in https://github.com/ntop/ntopng/issues/4489.

Now we need to implement capabilities configuration from the UI.
