### ISSUE TITLE
Replace page refresh with Ajax in Discovery page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1877]
When discovery is in progress, the whole page is refreshed updating the progress % instead of using ajax to update the <div> percentage. This causes the page to flash and reload now making it easy to use while discovering hosts

**Comment by simonemainardi** [comment]
Implemented with https://github.com/ntop/ntopng/commit/31c0fe6fe7a6fea140897920de98f7f4d7ac2b6e

![screen shot 2018-08-02 at 15 41 08](https://user-images.githubusercontent.com/3397663/43587427-814448fc-966a-11e8-8434-1ca1d50aaa86.png)
