### ISSUE TITLE
Add RRD/Influx preferences

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1878]
Currently it is not possible to enable/disable RRD/Influx metric dump from preferences but only using redis command line. It is requested to implement the ability to set this from preferences

**Comment by emanuele-f** [comment]
Implemented in af1fc50ce6ea1550b9f6ff2494f68c7fe971907b . The setting is now available under the `Timeseries` preferences.

![screenshot_2](https://user-images.githubusercontent.com/5488003/43393553-e53aa6e6-93f7-11e8-85ea-080bd9a9420d.png)
