### ISSUE TITLE
Regex expression in ntopng.service.in cases some options to be ignored on start

### ISSUE THREAD

**Issue by alxrt** [ntop/ntopng#1879]
In ntopng/packages/etc/systemd/system/ntopng.service.in:
Line 12:

in `/bin/sed "/-e.*$\\|-G.*\\|--daemon.*\\|--pid.*/s/^/#/` expression `-e.*$` will coment any option contains '-e' as part.
For me it was 
`-F="es;ntopng;ntopng-gw-%Y%m%d;http://v-es-xxl-1.domain.local:9200/_bulk;"`

**Comment by simonemainardi** [comment]
Thanks for reporting. new build are in progress and the fix will be available in the next dev build (it will take a couple of hours to generate).
