### ISSUE TITLE
ntopng (RasberryPi repo) no GUI after logon

### ISSUE THREAD

**Issue by filemoon** [ntop/ntopng#188]
Login screen i displayed correctly - but when username and password is entered "Page "/" was not found" message is displayed and no ntopng gui is provided. 

Ntopng and nprobe is installed using following repository and manual.
http://packages.ntop.org/RaspberryPI/

apt-get update warning message
(I'm not sure this is connected with the issue)
W: Conflicting distribution: http://packages.ntop.org armhf/ Release (expected armhf but got RaspberryPI)

log:
ntopng -i "tcp://127.0.0.1:5556"
29/Sep/2015 10:55:10 [src/Ntop.cpp:817] Setting local networks to 192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,127.0.0.0/8,0.0.0.0/32,224.0.0.0/8,239.0.0.0/8,255.255.255.255/32,127.0.0.0/8
29/Sep/2015 10:55:10 [src/Redis.cpp:105] Successfully connected to redis 127.0.0.1:6379@0
29/Sep/2015 10:55:10 [pro/NtopPro.cpp:141] ERROR: [LICENSE] Invalid or missing ntopng License [Empty license file]
29/Sep/2015 10:55:10 [pro/NtopPro.cpp:154] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
29/Sep/2015 10:55:10 [pro/NtopPro.cpp:156] WARNING: [LICENSE] before returning to community mode
29/Sep/2015 10:55:10 [pro/NtopPro.cpp:157] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
29/Sep/2015 10:55:10 [pro/NtopPro.cpp:158] WARNING: [LICENSE] or run ntopng in community mode starting
29/Sep/2015 10:55:10 [pro/NtopPro.cpp:159] WARNING: [LICENSE] ntopng --community
29/Sep/2015 10:55:10 [src/Ntop.cpp:1066] Registered interface view tcp://127.0.0.1:5556 [id: 12]
29/Sep/2015 10:55:10 [src/Ntop.cpp:1036] Registered interface tcp://127.0.0.1:5556 [id: 0]
29/Sep/2015 10:55:10 [src/Utils.cpp:300] User changed to nobody
29/Sep/2015 10:55:10 [src/main.cpp:245] PID stored in file /var/tmp/ntopng.pid
Error Opening file /usr/local/share/ntopng/httpdocs/geoip/GeoIPASNum.dat
29/Sep/2015 10:55:10 [src/Geolocation.cpp:59] WARNING: Unable to read GeoIP database /usr/local/share/ntopng/httpdocs/geoip/GeoIPASNum.dat
Error Opening file /usr/local/share/ntopng/httpdocs/geoip/GeoIPASNumv6.dat
29/Sep/2015 10:55:10 [src/Geolocation.cpp:59] WARNING: Unable to read GeoIP database /usr/local/share/ntopng/httpdocs/geoip/GeoIPASNumv6.dat
Error Opening file /usr/local/share/ntopng/httpdocs/geoip/GeoLiteCity.dat
29/Sep/2015 10:55:10 [src/Geolocation.cpp:59] WARNING: Unable to read GeoIP database /usr/local/share/ntopng/httpdocs/geoip/GeoLiteCity.dat
Error Opening file /usr/local/share/ntopng/httpdocs/geoip/GeoLiteCityv6.dat
29/Sep/2015 10:55:10 [src/Geolocation.cpp:59] WARNING: Unable to read GeoIP database /usr/local/share/ntopng/httpdocs/geoip/GeoLiteCityv6.dat
29/Sep/2015 10:55:10 [src/HTTPserver.cpp:453] HTTPS Disabled: missing SSL certificate /usr/local/share/ntopng/httpdocs/ssl/ntopng-cert.pem
29/Sep/2015 10:55:10 [src/HTTPserver.cpp:455] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
29/Sep/2015 10:55:10 [src/HTTPserver.cpp:498] Web server dirs [/usr/local/share/ntopng/httpdocs][/usr/local/share/ntopng/scripts]
29/Sep/2015 10:55:10 [src/HTTPserver.cpp:501] HTTP server listening on port 3000
29/Sep/2015 10:55:10 [src/main.cpp:298] Working directory: /var/tmp/ntopng
29/Sep/2015 10:55:10 [src/main.cpp:300] Scripts/HTML pages directory: /usr/share/ntopng
29/Sep/2015 10:55:10 [src/Ntop.cpp:292] Welcome to ntopng armv7l v.2.0.150811 - (C) 1998-15 ntop.org
29/Sep/2015 10:55:10 [src/PeriodicActivities.cpp:53] Started periodic activities loop...
29/Sep/2015 10:55:10 [src/RuntimePrefs.cpp:32] Dumping alerts into syslog
29/Sep/2015 10:55:10 [pro/NtopPro.cpp:216] [LICENSE] ntopng systemId: FD70E299499602D2
29/Sep/2015 10:55:10 [pro/NtopPro.cpp:221] [LICENSE] ntopng is starting in demo mode
29/Sep/2015 10:55:10 [src/NetworkInterface.cpp:1298] Started packet polling on interface tcp://127.0.0.1:5556 [id: 12]...
29/Sep/2015 10:55:11 [src/CollectorInterface.cpp:93] Collecting flows on tcp://127.0.0.1:5556

/usr/local/share/ntopng/httpdocs/geoip - geoip is NOT present in following directory
/usr/share/ntopng/httpdocs/geoip - geoip is present in following directory

regards Chris

**Comment by filemoon** [comment]
Dd we have any update for this problem?

regards Chris

**Comment by lucaderi** [comment]
We will build a new package later this month.

**Comment by lucaderi** [comment]
Packages are now available.

**Comment by filemoon** [comment]
Issue is not sorted.

" Page "/" was not found" message is still present.

**Comment by lucaderi** [comment]
Can you please tell me how you have started ntopng and if in /usr/local/share/ntopng/ you have the files properly installed?

**Comment by filemoon** [comment]
After upgrade I start it as always
"ntopng -i "tcp://127.0.0.1:5556""

But I've decided to delete it totally and install again - and installation was not possible anymore.

The following packages have unmet dependencies:
 ntopng : Depends: libnuma1 but it is not installable
          Depends: libzmq3 but it is not installable

**Comment by lucaderi** [comment]
> dpkg -I ntopng_2.1.151012-625_armhf.deb
 new debian package, version 2.0.
 size 3724208 bytes: control archive=13740 bytes.
      47 bytes,     1 lines      conffiles            
     306 bytes,    10 lines      control              
   32336 bytes,   383 lines      md5sums              
     558 bytes,    34 lines   *  postinst             #!/bin/sh
     101 bytes,     9 lines   *  postrm               #!/bin/sh
     664 bytes,    35 lines   *  preinst              #!/bin/sh
     387 bytes,    16 lines   *  prerm                #!/bin/sh
 Package: ntopng
 Version: 2.1.151012-625
 Architecture: armhf
 Maintainer: Luca Deri <deri@ntop.org>
 Installed-Size: 16061
 Depends: libsqlite3-0, libgeoip1, redis-server, librrd4, logrotate, libcurl3, libzmq3
 Recommends: ntopng-data
 Section: free
 Priority: optional
 Description: Web-based traffic monitoring.

Looks good to me. I have usd Raspbian do you use the same distro?

**Comment by filemoon** [comment]
When kernel is upgraded (sorry for that) I have no  libzmq3 problems anymore and I can install packages.

But still I cannot start them

ntopng: error while loading shared libraries: libmariadb.so.2: cannot open shared object file: No such file or directory
nprobe: error while loading shared libraries: libnetfilter_queue.so.1: cannot open shared object file: No such file or directory

**Comment by lucaderi** [comment]
@filemoon Can you please resync and report it it works?

**Comment by filemoon** [comment]
First I was not able to install with default sources:

ntopng : Depends: libmariadb2 but it is not installable


When I add more sources I was able to install it:

"deb http://ftp.debian.org/debian/ wheezy main contrib non-free
deb http://ftp.debian.org/debian/ unstable main
deb http://mirrors.sohu.com/debian/ wheezy main contrib non-free
deb http://security.debian.org/ wheezy/updates main contrib non-free
deb http://packages.cubian.org/ wheezy main non-free
deb http://repo.ajenti.org/debian main main debian

deb-src http://ftp.debian.org/debian/ wheezy main contrib non-free
deb-src http://mirrors.sohu.com/debian/ wheezy main contrib non-free"

ntopng starts correctly:

ntopng -i "tcp://127.0.0.1:5556"
17/Oct/2015 09:29:32 [Ntop.cpp:929] Setting local networks to 127.0.0.0/8
17/Oct/2015 09:29:32 [Redis.cpp:105] Successfully connected to redis 127.0.0.1:6379@0
17/Oct/2015 09:29:32 [NtopPro.cpp:117] [LICENSE] Read license from Redis []
17/Oct/2015 09:29:32 [NtopPro.cpp:159] ERROR: [LICENSE] Invalid or missing ntopng License [Empty license file]
17/Oct/2015 09:29:32 [NtopPro.cpp:172] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
17/Oct/2015 09:29:32 [NtopPro.cpp:174] WARNING: [LICENSE] before returning to community mode
17/Oct/2015 09:29:32 [NtopPro.cpp:175] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
17/Oct/2015 09:29:32 [NtopPro.cpp:176] WARNING: [LICENSE] or run ntopng in community mode starting
17/Oct/2015 09:29:32 [NtopPro.cpp:177] WARNING: [LICENSE] ntopng --community
17/Oct/2015 09:29:32 [Ntop.cpp:1178] Registered interface view tcp://127.0.0.1:5556 [id: 12]
17/Oct/2015 09:29:32 [Ntop.cpp:1148] Registered interface tcp://127.0.0.1:5556 [id: 0]
17/Oct/2015 09:29:32 [Utils.cpp:286] Privileges are not dropped as we're not superuser
17/Oct/2015 09:29:32 [main.cpp:237] PID stored in file /var/tmp/ntopng.pid
17/Oct/2015 09:29:33 [HTTPserver.cpp:456] HTTPS Disabled: missing SSL certificate /usr/local/share/ntopng/httpdocs/ssl/ntopng-cert.pem
17/Oct/2015 09:29:33 [HTTPserver.cpp:458] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
17/Oct/2015 09:29:33 [HTTPserver.cpp:501] Web server dirs [/usr/local/share/ntopng/httpdocs][/usr/local/share/ntopng/scripts]
17/Oct/2015 09:29:33 [HTTPserver.cpp:504] HTTP server listening on port 3000
17/Oct/2015 09:29:33 [main.cpp:290] Working directory: /var/tmp/ntopng
17/Oct/2015 09:29:33 [main.cpp:292] Scripts/HTML pages directory: /usr/share/ntopng
17/Oct/2015 09:29:33 [Ntop.cpp:260] Welcome to ntopng armv7l v.2.1.151017 - (C) 1998-15 ntop.org
17/Oct/2015 09:29:33 [Ntop.cpp:265] Built on Raspbian GNU/Linux 8.0 (jessie)
17/Oct/2015 09:29:33 [PeriodicActivities.cpp:53] Started periodic activities loop...
17/Oct/2015 09:29:33 [RuntimePrefs.cpp:32] Dumping alerts into syslog
17/Oct/2015 09:29:33 [NtopPro.cpp:234] [LICENSE] ntopng systemId: FD70E299499602D2
17/Oct/2015 09:29:33 [NtopPro.cpp:239] [LICENSE] ntopng is starting in demo mode
17/Oct/2015 09:29:33 [NetworkInterface.cpp:1448] Started packet polling on interface tcp://127.0.0.1:5556 [id: 12]...
17/Oct/2015 09:29:34 [CollectorInterface.cpp:93] Collecting flows on tcp://127.0.0.1:5556


But web interface is still not present: "Page "/" was not found" (after username and password is entered)

**Comment by lucaderi** [comment]
@filemoon To me the new package works well.
I do have the missing package you mentioned

> dpkg -l |grep libmariadb2
ii  libmariadb2:armhf                     2.0.0-1                                   armhf        MariaDB Client Library for C

I believe we are not using the same distribution. Can you please do "lsb_release -a" ?

> lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie

**Comment by filemoon** [comment]
before I had: wheezy
but yesterday system was upgraded to jessie.

Web interface is still not present: "Page "/" was not found" (after username and password is entered)

**Comment by lucaderi** [comment]
@filemoon Did you clean the browser cache? I am unable to reproduce the bug. Any chance to access your system?

**Comment by filemoon** [comment]
I will prepare VPN access today.
Thank you.

**Comment by filemoon** [comment]
VPN access

Cisco IPSec

vpn user: lderi 
vpn password: support
server: filemoon.ddns.net
share: fi8le3mo9o9n.i8e3
group name: home


Raspberry PI2 10.0.1.6 (ssh enabled)

u: pi 
pi password: support2015
u: root 
root password: support2015


Regards Chris

**Comment by lucaderi** [comment]
Fixed. The problem was that you had installed yourself ntopng (in /usr/local/share/ntopng) and the ntopng package (in /usr/share/ntopng). So ntopng was picking the web files in the wrong place. Please install either one or the other.
Note that I have deleted the info about VPN access. Please mail them to me next time, not to everyone on github.

Time to star ntopng now. Enjoy,

**Comment by eliosbrocchiinfotn** [comment]
Hello, I've had problem to upgrade ntopng from 2.0 to 2.1 on Raspbian, in the following lines the stack to install deb packge dowloaded from your site.

root@potemkin:~# dpkg -i ntopng_2.1.151017-641_armhf.deb
(Reading database ... 111594 files and directories currently installed.)
Preparing to replace ntopng 2.0.150811-421 (using ntopng_2.1.151017-641_armhf.deb) ...
Unpacking replacement ntopng ...
dpkg: dependency problems prevent configuration of ntopng:
 ntopng depends on libzmq3; however:
  Package libzmq3 is not installed.
 ntopng depends on libnetfilter-queue1; however:
  Package libnetfilter-queue1 is not installed.
 ntopng depends on libmariadb2; however:
  Package libmariadb2 is not installed.

dpkg: error processing ntopng (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db ...
Errors were encountered while processing:
 ntopng
root@potemkin:~# apt-cache search libmariadb2
root@potemkin:~# apt-cache search libnetfilter-queue1
libnetfilter-queue-dev - Development files for libnetfilter-queue1
libnetfilter-queue1 - Netfilter netlink-queue library
libnetfilter-queue1-dbg - Debugging symbols for libnetfilter-queue1
root@potemkin:~# apt-cache search libzmq3
root@potemkin:~# uname -a
Linux potemkin 4.1.6+ #810 PREEMPT Tue Aug 18 15:19:58 BST 2015 armv6l GNU/Linux
root@potemkin:~#

**Comment by lucaderi** [comment]
deri@raspberrypi 177> uname -a
Linux raspberrypi 4.1.7-v7+ #817 SMP PREEMPT Sat Sep 19 15:32:00 BST 2015 armv7l GNU/Linux
deri@raspberrypi 178> dpkg -l|grep maria
ii  libmariadb-client-lgpl-dev            2.0.0-1                                   armhf        MariaDB Client Library for C, development files
ii  libmariadb2:armhf                     2.0.0-1                                   armhf        MariaDB Client Library for C
deri@raspberrypi 179> cat /etc/debian_version 
8.0
deri@raspberrypi 180> dpkg -l | grep zmq
ii  libzmq3:armhf                         4.0.5+dfsg-2+deb8u1                       armhf        lightweight messaging kernel (shared library)
ii  libzmq3-dev:armhf                     4.0.5+dfsg-2+deb8u1                       armhf        lightweight messaging kernel (development files)

**Comment by filemoon** [comment]
Upgrade system to Jessie and issue will be gone.
