### ISSUE TITLE
3.5.180723-4663 broken with table index is nil issue

### ISSUE THREAD

**Issue by Punkley** [ntop/ntopng#1880]
Error on opening any page
 
Script "/usr/share/ntopng/scripts/lua/index.lua" returned an error:
table index is nil

and lots of warning similar to this
WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/shutdown.lua][table index is nil]

Under ubuntu 18.04

Kingsley

**Comment by simonemainardi** [comment]
fixed in https://github.com/ntop/nDPI/commit/5100cc0eaec27c9796bab749435972adf2f89246
new builds are in progress
