### ISSUE TITLE
Problem with Dashboard (Enterprise Version) - Network Interfaces: Realtime Traffic and Network Interfaces: Last Day View

### ISSUE THREAD

**Issue by dive76** [ntop/ntopng#1882]
Noted that the Dashboard in the Enterprise Version is not working. Please see attached picture. Graphs for Network Interfaces: Realtime Traffic and Network Interfaces: Last Day View are not working.
![dashboard](https://user-images.githubusercontent.com/41624349/43133120-57664bb2-8f70-11e8-9a1f-4effa491b87e.png)

**Comment by dive76** [comment]
[bytes.zip](https://github.com/ntop/ntopng/files/2223709/bytes.zip)
bytes.rrd file ziped

**Comment by simonemainardi** [comment]
Thanks for providing the fie. It seems the rrd file is contains unexpected data. we don't use the 'bytes' string to name any RRA.

```
ds[bytes].index = 0
ds[bytes].type = "DERIVE"
ds[bytes].minimal_heartbeat = 5
ds[bytes].min = NaN
ds[bytes].max = NaN
ds[bytes].last_ds = "74697226"
ds[bytes].value = 0.0000000000e+00
ds[bytes].unknown_sec = 0
```

Can you please try and delete the file `bytes.rrd` provided from the system so ntopng will re-create it.automatically.

**Comment by dive76** [comment]
Updating to the latest version and deleting the bytes.rrd file for all interfaces solves that issue.
Found a new one which might be related. The top HTTP sites under each host are no longer shows. That worked very well before.
![2018-07-25](https://user-images.githubusercontent.com/41624349/43196986-620a4bfa-903c-11e8-816b-fb7b9db6d9b7.png)

**Comment by simonemainardi** [comment]
Thanks for reporting. I committed a fix to even avoid the deletion of that bytes.rrd. The issue was basically due to the new timeseries library that we've implemented that was not able to properly read the old `bytes.rrd` file.
