### ISSUE TITLE
Login form username validation regex too restrictive

### ISSUE THREAD

**Issue by cjwbath** [ntop/ntopng#1884]
The login form has validation rules that disable the login button until the username field matches a certain regex (looks like `^[\w\.%]{1,}$`). That's fair enough for local users as it's also checked at user creation time. However for LDAP integrated auth where the backend does not have this restriction, we have users with dashes (-) in their username who can't attempt login because of this.

Why bother validating this field at all, and out of interest what's the significance of allowing the percent character?

**Comment by simonemainardi** [comment]
Thanks for reporting. Issue has been fixed and will be available in a couple of hours in the latest dev build.
