### ISSUE TITLE
ldap not being attempted under ubuntu 18.04

### ISSUE THREAD

**Issue by Punkley** [ntop/ntopng#1885]
I've been trying to get ldap working under ubuntu 18.04 and ntopng v.3.5.180725

I don't see any attempt on the ldap server for a connection (or any tcpdump traffic).

Authentication Method: LDAP/Local
Type Posix
Server address: ldap://10.6.xx.xx:389
LDAP Anonymous Binding: yes
LDAP Search Path dc=staff,dc=test,dc=com,dc=au

**Comment by simonemainardi** [comment]
Thanks for reporting. Fixed. A new build is in progress and will be ready in 1 hour.
