### ISSUE TITLE
MySQL dump - indexes and permissions

### ISSUE THREAD

**Issue by cjwbath** [ntop/ntopng#1886]
I tried the MySQL backend feature with --dump-flows and noticed a couple of things:

- There are not many useful indexes added to the flows tables by default - in particular source and destination IP are not indexed making most searches through the UI painfully slow or impossible (I have ~25M rows in the table at the moment). I added those indexes and things are much better, and writes have not slowed noticeably - so maybe mention in the documentation or add by default?

- Even if a user's profile is set with "Allowed Networks" to only allow them to see certain subnets, they can still see everything from all networks in the Historical Data Explorer. Maybe that should be scoped too?

**Comment by simonemainardi** [comment]
Thanks for reporting, we've restricted database access to only allowed networks. A new build will be available starting from tomorrow.

We are now going to rework the database inserts/queries with a new library and will keep in mind your suggestion for the indices.

Thank you.
