### ISSUE TITLE
How to extract user name/id from ntopng flows

### ISSUE THREAD

**Issue by prasanthi97** [ntop/ntopng#1887]
Unable to capture the user id/user name from the host flows in the port mirrored traffic although we are getting the ip address. Are there any probes/plugins available with ntopng to decode the user id.

**Comment by simonemainardi** [comment]
what user id are you looking for? Are you looking for the user id of a give application?

**Comment by prasanthi97** [comment]
For example VDI users. Every time they login their user id will be the same but the ip address changes.
We are trying to measure/capture VDI user traffic. Currently ntopng displays ip adress when we capture VDI traffic.

**Comment by simonemainardi** [comment]
You need deep packet inspection support for citrix VDI. Currently that is not included in ntopng or in nDPI.  Shall you be interested in having that support, please file a request on the nDPI github page or contact the ntop team privately.
