### ISSUE TITLE
rrd_5min_dump_utils.lua:18: attempt to call field 'tsSet' (a nil value)

### ISSUE THREAD

**Issue by sidsamant** [ntop/ntopng#1888]
Hi,

New problem while working with ntopng and elasticsearch.

Ntopng is running though these messages fill up the logs :

`Jul 28 02:05:00 scary ntopng[1710]: 28/Jul/2018 02:05:00 [Lua.cpp:7692] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/interface/5min.lua][...share/ntopng/scripts/lua/modules/rrd_5min_dump_utils.lua:18: attempt to call field 'tsSet' (a nil value)]
Jul 28 02:05:00 scary ntopng[1710]: [Lua.cpp:7692] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/interface/5min.lua][...share/ntopng/scripts/lua/modules/rrd_5min_dump_utils.lua:18: attempt to call field 'tsSet' (a nil value)]
Jul 28 02:05:00 scary ntopng[1710]: 28/Jul/2018 02:05:00 [Lua.cpp:7692] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/minute.lua][/usr/share/ntopng/scripts/callbacks/system/minute.lua:14: attempt to call field 'tsFlush' (a nil value)]
Jul 28 02:05:00 scary ntopng[1710]: [Lua.cpp:7692] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/minute.lua][/usr/share/ntopng/scripts/callbacks/system/minute.lua:14: attempt to call field 'tsFlush' (a nil value)]
Jul 28 02:05:00 scary ntopng[1710]: 28/Jul/2018 02:05:00 [Lua.cpp:7692] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/interface/minute.lua][.../share/ntopng/scripts/lua/modules/rrd_min_dump_utils.lua:63: attempt to call field 'tsSet' (a nil value)]
Jul 28 02:05:00 scary ntopng[1710]: [Lua.cpp:7692] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/interface/minute.lua][.../share/ntopng/scripts/lua/modules/rrd_min_dump_utils.lua:63: attempt to call field 'tsSet' (a nil value)]
Jul 28 02:05:00 scary ntopng[1710]: 28/Jul/2018 02:05:00 [Lua.cpp:7692] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/second.lua][/usr/share/ntopng/scripts/lua/modules/rrd_utils.lua:395: attempt to call field 'tsSet' (a nil value)]`

`ntopng --version
v.3.5.180611    [Community build]
GIT rev:        dev:c67f7430cc39582b41606912632e8797e1530e75:20180611`

**Fedora version 26 
ElasticSearch 6.3.0**

Issues :

1. Geolocation (*_IP_LOCATION is 0,0 , *_IP_COUNTRY are empty ) for IP addresses for flows not present on ntopng UI and in the dumps to Elasticsearch.

2. Flows not being reported for IP addresses of China but works fine for other countries.

3. xui.ptlogin2.qq.com is showing as a Local Http Virtual Host though it is not.

Thanks again,
Sid

**Comment by simonemainardi** [comment]
You are using an outdated version 3.5. can you please build and report the behaviour using latest 3.5.

**Comment by sidsamant** [comment]
Thanks. Will let you in a few days.

**Comment by simonemainardi** [comment]
I can confirm neither `tsSet` nor `tsFlush ` are ever called in the latest dev build so that issue can no longer occur. Make sure you don't have an old installed ntopng version (e.g., under /usr/share/ntopng) that could conflict with a more recent version that you may be executing from the build working directory.

In order to have IP geolocation enabled you need to build and link ntopng with `libmaxminddb`. You also have to run `make geoip` to download the MaxMind GeoLite2 databases. Please, see the README.compilation for instructions.

Shall you be still experiencing 2. and 3. with the latest build, please open a separate issue with examples and screenshots that describe with greater detail.
