### ISSUE TITLE
DNS/mDNS / homebridge question

### ISSUE THREAD

**Issue by animosity022** [ntop/ntopng#1889]
I have a question that I haven't been able to quite figure out yet so I figured I'd post to see if someone else hit the issue.

I'm running https://github.com/nfarina/homebridge on a linux box along with ntopng. When I first start up, I can see the host properly register with the name as it is in DNS.

Homebridge has a line it it for mDNS that registers a username with  "CC:22:3D:E3:CE:30" that I can't seem to figure out how to stop from updating the ntopng 'Name' field.

This is how it looks once I clear everything:

![image](https://user-images.githubusercontent.com/5088712/43366545-8ff314c4-930d-11e8-85de-35003beb1a43.png)

and if I start up homebridge, it changes it to the username configured:

![image](https://user-images.githubusercontent.com/5088712/43366557-c4044dc8-930d-11e8-97af-4a2b519bc17a.png)

I'm running my dns config as "-n=1"

**Comment by emanuele-f** [comment]
Hi, what ntopng version are you using?

**Comment by animosity022** [comment]
3.4.180726 - Community Edition
--

**Comment by emanuele-f** [comment]
Can you provide a pcap file which captures the mDNS traffic before and after the change? You can capture mDNS traffic with: `tcpdump -n -s0 -w mdns.pcap -i your_nic udp port 5353`

**Comment by animosity022** [comment]
I believe this should be it.


[mdns.pcap.zip](https://github.com/ntop/ntopng/files/2245769/mdns.pcap.zip)

**Comment by lucaderi** [comment]
<img width="1016" alt="screen shot 2018-08-02 at 17 13 28" src="https://user-images.githubusercontent.com/4493366/43593163-6ad2c550-9677-11e8-8102-1b80a75e79df.png">
Unfortunately is your home bridge that is reporting its name via mDNS and even wireshark interprets that as ntopng

**Comment by animosity022** [comment]
I was asking if there was a way to prevent there or any other suggestions so it does not overwrite my names.

**Comment by ephemerist** [comment]
I've found a similar issue - some services running on my machines publish mDNS names, which make it difficult to tell which host is which in ntopng. It would be great if we could configure ntopng to prefer DNS resolution over mDNS in this case.
