### ISSUE TITLE
how to run historical interface?

### ISSUE THREAD

**Issue by volkovmm** [ntop/ntopng#189]
Hello! Please help me to understand how to start historical interface using  -F.
I have a build of ntopng 2.0.150930.
I can't find anywhere how to write the command in ntopng.conf to have the opportunity to work with the historical interface.
for example I have an interface named eth0.

**Comment by lmangani** [comment]
Hi,

Please see: https://github.com/ntop/ntopng/blob/dev/doc/README.historical

**Comment by volkovmm** [comment]
Well. I looked it up. But understand all in General terms. Please provide me more specific help.
I have Centos 7. I have installed MariaDB. My file ntopng.conf file looks like this:
-G=/var/tmp/ntopng.pid
-- interface=eth0

What should I write to start the historical interface?
-F "mysql;localhost;ntopng;flows;root;"? how?

**Comment by lmangani** [comment]
@volkovmm that is correct, just extend your existing options/configuration with:
<pre>
-F "mysql;localhost;ntopng;flows;mysql_user;mysql_password"
</pre>

__Please do create a MySQL User (or use root) and Database (ie: ntopng) upfront!__

The console will provide output, in case of issue paste it here for assistance.

**Comment by lucaderi** [comment]
-F=....

**Comment by volkovmm** [comment]
hisorical interface not displayed on the page. what am I doing wrong?
This is my conf:
--interface=enp3s0
-F="mysql;localhost;ntopng;flows;root;977"
-G=/var/tmp/ntopng.pid
This is my lof file:
01/Oct/2015 08:36:45 [Ntop.cpp:936] Setting local networks to 127.0.0.0/8
01/Oct/2015 08:36:45 [Redis.cpp:105] Successfully connected to redis 127.0.0.1:6379@0
01/Oct/2015 08:36:45 [NtopPro.cpp:117] [LICENSE] Read license from Redis []
01/Oct/2015 08:36:45 [NtopPro.cpp:159] ERROR: [LICENSE] Invalid or missing ntopng License [Empty license file]
01/Oct/2015 08:36:45 [NtopPro.cpp:172] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
01/Oct/2015 08:36:45 [NtopPro.cpp:174] WARNING: [LICENSE] before returning to community mode
01/Oct/2015 08:36:45 [NtopPro.cpp:175] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
01/Oct/2015 08:36:45 [NtopPro.cpp:176] WARNING: [LICENSE] or run ntopng in community mode starting
01/Oct/2015 08:36:45 [NtopPro.cpp:177] WARNING: [LICENSE] ntopng --community
01/Oct/2015 08:36:45 [MySQLDB.cpp:186] Attempting to connect to MySQL for interface enp3s0...
01/Oct/2015 08:36:45 [MySQLDB.cpp:226] Succesfully connected to MySQL [localhost:root] for interface enp3s0
01/Oct/2015 08:36:45 [MySQLDB.cpp:186] Attempting to connect to MySQL for interface enp3s0...
01/Oct/2015 08:36:45 [MySQLDB.cpp:226] Succesfully connected to MySQL [localhost:root] for interface enp3s0
01/Oct/2015 08:36:45 [PcapInterface.cpp:81] Reading packets from interface enp3s0...
01/Oct/2015 08:36:45 [Ntop.cpp:1185] Registered interface view enp3s0 [id: 0]
01/Oct/2015 08:36:45 [Ntop.cpp:1155] Registered interface enp3s0 [id: 0]
01/Oct/2015 08:36:45 [Utils.cpp:304] User changed to nobody
01/Oct/2015 08:36:45 [main.cpp:237] PID stored in file /var/tmp/ntopng.pid
01/Oct/2015 08:36:45 [HTTPserver.cpp:458] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
01/Oct/2015 08:36:45 [HTTPserver.cpp:501] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
01/Oct/2015 08:36:45 [HTTPserver.cpp:504] HTTP server listening on port 3000
01/Oct/2015 08:36:45 [main.cpp:290] Working directory: /var/tmp/ntopng
01/Oct/2015 08:36:45 [main.cpp:292] Scripts/HTML pages directory: /usr/share/ntopng
01/Oct/2015 08:36:45 [Ntop.cpp:267] Welcome to ntopng x86_64 v.2.0.150930 - (C) 1998-15 ntop.org
01/Oct/2015 08:36:45 [Ntop.cpp:272] Built on CentOS Linux release 7.1.1503 (Core) 
01/Oct/2015 08:36:45 [PeriodicActivities.cpp:53] Started periodic activities loop...
01/Oct/2015 08:36:45 [RuntimePrefs.cpp:32] Dumping alerts into syslog
01/Oct/2015 08:36:45 [NtopPro.cpp:234] [LICENSE] ntopng systemId: 4211A68909B1B8A9
01/Oct/2015 08:36:45 [NtopPro.cpp:239] [LICENSE] ntopng is starting in demo mode
01/Oct/2015 08:36:45 [Ntop.cpp:549] Adding fe80::22cf:30ff:fe0e:a181/64 as IPv6 local network
01/Oct/2015 08:36:45 [NetworkInterface.cpp:1395] Started packet polling on interface enp3s0 [id: 0]...
01/Oct/2015 08:36:47 [NetworkInterface.cpp:973] Invalid packet received [len: 3798][MTU: 1518].
01/Oct/2015 08:36:47 [NetworkInterface.cpp:974] WARNING: If you have TSO/GRO enabled, please disable it
01/Oct/2015 08:36:47 [NetworkInterface.cpp:976] WARNING: Use: sudo ethtool -K enp3s0 gro off gso off tso off
