### ISSUE TITLE
Traffic Report not working in Pro (table expected, got nil)

### ISSUE THREAD

**Issue by Punkley** [ntop/ntopng#1891]
on 
/lua/pro/report.lua

HTTP/1.1 500 Internal server error Content-Type: text/html Connection: close   Script "/usr/share/ntopng/scripts/lua/pro/report.lua" returned an error:

/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:85: bad argument #1 to 'ipairs' (table expected, got nil)

**Comment by emanuele-f** [comment]
The new package with the fix will be available in one hour. Thank you for reporting.
