### ISSUE TITLE
Query on MAX_INTERFACES macro in the ntop_defines.h file

### ISSUE THREAD

**Issue by swathinsankaran** [ntop/ntopng#1892]
Hi,

I came across the below macro while going through the code.

https://github.com/ntop/ntopng/blob/af1fc50ce6ea1550b9f6ff2494f68c7fe971907b/include/ntop_defines.h#L131

 Can anybody tell me why the Maximum interface is kept as 48 and what the value implies?

**Comment by simonemainardi** [comment]
48 is a reasonable maximum number of interfaces ntopng can manage. This means that ntopng will keep statistics (e.g., rrd files, redis keys, data in the data directory) for up to 48 different interfaces. So for example you are free to start ntopng with an interface eth1, then restart it with another interface eth2, and eventually restart it with eth1 to have the original eth1 stats back and available.

This number has nothing to do with constant `MAX_NUM_DEFINED_INTERFACES` that is an upper bound on the number of interfaces that can be instantiated simultaneously within a single ntopng process.
