### ISSUE TITLE
non reachable Interfaces

### ISSUE THREAD

**Issue by hpiadmin** [ntop/ntopng#1893]
If I install nProbe/nTop on our config-keeper, our interfaces are not accessible afterwards. 
I think it depends on PF_RING. Is PF_RING needed? Is it possible to install it without?

**Comment by cardigliano** [comment]
@hpiadmin are you using ZC drivers (i.e. is your interface name starting with 'zc:')?

**Comment by cardigliano** [comment]
Please reopen if necessary.
