### ISSUE TITLE
How long does the data keep in InfluxDB?

### ISSUE THREAD

**Issue by jedi0605** [ntop/ntopng#1894]
Hello,
I know the old ver. can setting data keep time in MySQL.
Have the same function in InfluxDB?

**Comment by emanuele-f** [comment]
Hello, currently we don't handle InfluxDB retention time, so data will be kept ~forever~ according to the default InfluxDB database retention policy

**Comment by emanuele-f** [comment]
Max duration implemented in 1af40bd42fd714db3edcb8e9d7d77f6553d07e24 .

![screenshot_3](https://user-images.githubusercontent.com/5488003/43648543-fbbb4df8-973a-11e8-8f54-47b3a3eff00b.png)

**Comment by jedi0605** [comment]
Hello Ntopng,

Sorry bother you again.

Im using ntopng version " v.3.8.190118" with InfluxDB and I got ipv6
address in InfluxDB host:traffic.

On the other older ntopng version "v.3.5.180716" also using  InfluxDB but I
got "ipv4" address in InfluxDB host:traffic.

Where I can setting the config switch ipv6 to ipv4 in InfluxDB?

Thank you


Emanuele Faranda <notifications@github.com> 於 2018年8月3日 週五 下午10:41寫道：

**Comment by emanuele-f** [comment]
Hi, ntopng will write both ipv4 and ipv6 addresses timeseries to InfluxDB

**Comment by jedi0605** [comment]
Hay, I know ntopng will  write  ip addresses timeseries to InfluxDB.
But right now I only have ipv6.
[image: bug.PNG]
[image: bug2.PNG]

Emanuele Faranda <notifications@github.com> 於 2019年2月26日 週二 下午5:11寫道：

**Comment by emanuele-f** [comment]
I cannot see the picture above sorry, please send them via github. Also open a new issue.
