### ISSUE TITLE
Implement unclean shutdown handling

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1896]
When ntopng starts up it has no idea if it is restarting due to a crash or if it starts cleanly. As after a crash some potential recovery actions might be required, it is asked to detect start after non-clean shutdown. To do so when ntopng boots it must check on redis a key (i.e. ntopng.unclean_shutdown) and if set run some recovery actions (e.g. a specific Lua file whose default is no action), then set the redis key. During shutdown the key must be deleted so in case of crash the key is still present on redis.
In ntopng alerts, thie event must be notified such as "clean start" or "unclean start".

**Comment by simonemainardi** [comment]
Implemented

![image](https://user-images.githubusercontent.com/3397663/43529434-93107534-95ab-11e8-9693-6c8ea3ea9261.png)

when restarting from an anomalous termination:
- ERROR alerts are generated as shown above
- custom actions in `callbacks/system/recovery.lua` (currently empty) are performed
