### ISSUE TITLE
How to get Network discovery map

### ISSUE THREAD

**Issue by prasanthi97** [ntop/ntopng#1897]
I want to arrive a network discovery map based on ntop network discovery data, is it possible? Is there a way to see which devices are connected to which router.

**Comment by simonemainardi** [comment]
If you use the ntopng SNMP monitoring feature, and your SNMP-monitored devices support SNMP the Bridge MIB, then you are able to determine all the devices that have seen a particular host and on which port.

See for example the following screenshot.

![image](https://user-images.githubusercontent.com/3397663/43584509-d4c062e8-9662-11e8-9393-afdd2d123c6c.png)

It means that host 192.168.2.222 has been seen on 192.168.2.169 (a switch actually) on trunk port 51. Multiple devices are listed for the same host so you can basically re-construct all the devices (and ports) a particular host is traversing.

-----------

You can also use feature "Network Discovery" to discover the devices that are in the same LAN as the host running ntopng.

![image](https://user-images.githubusercontent.com/3397663/43584161-edaaad8c-9661-11e8-84f2-a572251cdd3f.png)
