### ISSUE TITLE
GELF support for sending expired flows to Graylog

### ISSUE THREAD

**Issue by mzac** [ntop/ntopng#1899]
I'm not sure if the builtin logstash writer is compatible with the GELF input on Graylog, but I'm looking at a way to send expired flows into graylog with ntopng.  I know that netflows can already be sent into graylog easily, but it would be nice to get the ntopng data in as well.

Some information on sending data into Graylog and the GELF input:
http://docs.graylog.org/en/2.4/pages/sending_data.html
http://docs.graylog.org/en/2.4/pages/gelf.html

There are pre-built libraries for sending GELF format too:
https://marketplace.graylog.org/addons?kind=gelf

I also tried sending in data directly into the Elasticsearch cluster from ntopng, but that didn't work too well.  It was able to write to the index, however messages received were not visible in Graylog.  Also, when creating an index in graylog such as 'ntopng', it'll automatically add a _0 or another number incrementally as indexes are rotated based on space or time settings.

I also noticed that the logstash configuration is not available in nbox when configuring expired flows for ntopng?  Is it missing or is it coming?

Thanks!

**Comment by simonemainardi** [comment]
I think what you should to is to use logstash for the described problem.

It's not a matter of a logstash writer being compatible with GELF. The builtin ntopng logstash writer don't have to be compatible with GELF nor it has to interact directly with Graylog. Those functions are proxied by logstash itself. 

Note that ntopng is compatible with logstash via an input tcp plugin https://www.elastic.co/guide/en/logstash/current/plugins-inputs-tcp.html

So you should have create a logstash pipeline with:
-  the tcp input plugin that receives data from ntopng
-  the GELF output plugin https://www.elastic.co/guide/en/logstash/current/plugins-outputs-gelf.html that delivers data to graylog.

You may also have to add a Filter (grok or mutate) to the logstash pipeline to make sure ntopng data is properly prepped for the GELF output plugin.

If you need a tutorial to see how to use ntopng with logstash you can refer to this youtube video I've prepared some time ago: https://www.youtube.com/watch?v=tluAUEeqkCk&t=56s

Please, let me know.

----

> Also, when creating an index in graylog such as 'ntopng', it'll automatically add a _0 

For the creation of indices in Graylog, you'd better refer to them.

----

> I also noticed that the logstash configuration is not available in nbox when configuring expired flows for ntopng? Is it missing or is it coming?

if possible, please, don't use nbox as it may not always be 100% up to date and aligned to the latest software configurations.

**Comment by simonemainardi** [comment]
Solution proposed. Feel free to send additional feedback.
