### ISSUE TITLE
No traffic and no throughput in NTOP (0 BPS) 

### ISSUE THREAD

**Issue by BDUCROS** [ntop/ntopng#190]
Hello,
I've taken a look of the manual on the NTOP site. I realized the installation on my server and it seems to works but I have a problem of configuration, I think .
There's no acquisition of throughput and all measured values are null ( 0 BPS) like there’s no traffic…
Have you got an idea?
Thank you for your help!
![screen1](https://cloud.githubusercontent.com/assets/14904126/10189237/5f2c404e-6765-11e5-9a38-52ff58d66ef8.jpg)
![screen2](https://cloud.githubusercontent.com/assets/14904126/10189246/69074af0-6765-11e5-8f78-b4c69be968de.jpg)

**Comment by BDUCROS** [comment]
No response...? :-(

**Comment by lmangani** [comment]
You are queued, there any more than a few users around ;)

**Comment by simonemainardi** [comment]
@BDUCROS try with the latest dev version. Some issues have been fixed. If the problem persists, please post ntopng configuration and everything useful that can help us in reproducing this behavior

**Comment by lucaderi** [comment]
@BDUCROS Can you please let us know if you can still reproduce this bug? I am unable.

**Comment by BDUCROS** [comment]
I just tried to update ntopng and nprobe on my server and the problem is still relevant... I don't know what hangs on my infrastructure... :-(  Something's wrong... On ntopng and nprobe configuration, there is nothing special to do except installation? thank you for your help.

**Comment by lucaderi** [comment]
@BDUCROS Please send us a private email (deri@ntop.org) where you specify detail for connecting to your host and seeing the problem as from our end we cannot reproduce.
