### ISSUE TITLE
Network aliases

### ISSUE THREAD

**Issue by hgpit** [ntop/ntopng#1900]
Hello,

We've added our local networks into the conf file, but we have over 50 of them, and just having them listed as CIDRs in ntopng makes it difficult for our technicians to remember which subnet is tied to which of our geographical locations etc.

Is there a way to assign aliases to the networks, i.e.:
10.11.10.0/24 : Site A
10.11.11.0/24 : Site B
10.11.15.0/24 : Site C
etc

Thank you

**Comment by emanuele-f** [comment]
Hello, this feature is not implemented yet

**Comment by PsyMan2000-zz** [comment]
I was just looking for this option too. Would be a great feature. Especially for allowing the not so techy staff (aka managers) a slightly more intuitive experience. Keep up the great work.

**Comment by emanuele-f** [comment]
Already implemented, see #2476
