### ISSUE TITLE
Unable to put ntopng in HTTPS mode

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#1903]
Hello.

I'm running CentOS7. It is updated daily.

I'm following that guide https://github.com/ntop/ntopng/blob/dev/doc/README.SSL

and I'm unable to get even close to implementing SSL for my ntopng.

After following the guide above, I start my ntopng and it is still in HTTP mode only. I'm able to access it but HTTPS is not even an option.

Below is what I have done:

[root@moon ssl]# openssl req -new -x509 -sha256 -extensions v3_ca -nodes -days 365 -out cert.pem
Generating a 2048 bit RSA private key
.............+++
................................................................................+++
writing new private key to 'privkey.pem'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [XX]:US
State or Province Name (full name) []:California
Locality Name (eg, city) [Default City]:
Organization Name (eg, company) [Default Company Ltd]:
Organizational Unit Name (eg, section) []:IT
Common Name (eg, your name or your server's hostname) []:moon
Email Address []:my@email.com
[root@moon ssl]# ls -l
total 16
-rw-r--r-- 1 root   root   1476 Aug  6 12:07 cert.pem
-rw-r----- 1 nobody nobody 4514 Aug  6 11:49 ntopng-cert.pem
-rw-r--r-- 1 root   root   1704 Aug  6 12:07 privkey.pem
[root@moon ssl]# cat privkey.pem cert.pem > ntopng-cert.pem
[root@moon ssl]# rm -f cert.pem privkey.pem
[root@moon ssl]# ls -l
total 4
-rw-r----- 1 nobody nobody 3180 Aug  6 12:07 ntopng-cert.pem
[root@moon ssl]# cd /usr/local/bin/
[root@moon bin]# ls -l libssl.so
lrwxrwxrwx 1 root root 20 Mar  8 14:51 libssl.so -> /usr/lib64/libssl.so
[root@moon bin]# pwd
/usr/local/bin
[root@moon bin]# cd /usr/share/ntopng/httpdocs/ssl/
[root@moon ssl]# ls -l
total 4
-rw-r----- 1 nobody nobody 3180 Aug  6 12:07 ntopng-cert.pem
[root@moon ssl]# ntopng
06/Aug/2018 12:09:30 [Ntop.cpp:1499] Setting local networks to 127.0.0.0/8
06/Aug/2018 12:09:30 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
06/Aug/2018 12:09:30 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
06/Aug/2018 12:09:30 [NtopPro.cpp:260] [LICENSE] Reading license from Redis
06/Aug/2018 12:09:30 [NtopPro.cpp:172] [LICENSE] F1E572506C58150B1330CE817E69F46E15544099970622F63B: unable to validate Enterprise license [License mismatch error]
06/Aug/2018 12:09:30 [NtopPro.cpp:175] [LICENSE] F1E572506C58150B1330CE817E69F46E15544099970622F63B: found valid Professional license
06/Aug/2018 12:09:39 [PcapInterface.cpp:91] Reading packets from interface em1...
06/Aug/2018 12:09:39 [Ntop.cpp:1626] Registered interface em1 [id: 0]
06/Aug/2018 12:09:40 [PcapInterface.cpp:91] Reading packets from interface em1.20...
06/Aug/2018 12:09:40 [Ntop.cpp:1626] Registered interface em1.20 [id: 1]
06/Aug/2018 12:09:41 [PcapInterface.cpp:91] Reading packets from interface em1.123...
06/Aug/2018 12:09:41 [Ntop.cpp:1626] Registered interface em1.123 [id: 2]
06/Aug/2018 12:09:41 [PcapInterface.cpp:91] Reading packets from interface lo...
06/Aug/2018 12:09:41 [Ntop.cpp:1626] Registered interface lo [id: 3]
06/Aug/2018 12:09:42 [PcapInterface.cpp:91] Reading packets from interface p2p1...
06/Aug/2018 12:09:42 [Ntop.cpp:1626] Registered interface p2p1 [id: 4]
06/Aug/2018 12:09:43 [PcapInterface.cpp:91] Reading packets from interface em2...
06/Aug/2018 12:09:43 [Ntop.cpp:1626] Registered interface em2 [id: 5]
06/Aug/2018 12:09:44 [PcapInterface.cpp:91] Reading packets from interface p2p2...
06/Aug/2018 12:09:44 [Ntop.cpp:1626] Registered interface p2p2 [id: 6]
06/Aug/2018 12:09:45 [PcapInterface.cpp:91] Reading packets from interface p2p3...
06/Aug/2018 12:09:45 [Ntop.cpp:1626] Registered interface p2p3 [id: 7]
06/Aug/2018 12:09:46 [PcapInterface.cpp:91] Reading packets from interface p2p4...
06/Aug/2018 12:09:46 [Ntop.cpp:1626] Registered interface p2p4 [id: 8]
06/Aug/2018 12:09:46 [main.cpp:317] PID stored in file /var/run/ntopng.pid
06/Aug/2018 12:09:46 [HTTPserver.cpp:900] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
06/Aug/2018 12:09:46 [Utils.cpp:469] User changed to nobody
06/Aug/2018 12:09:46 [HTTPserver.cpp:971] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
06/Aug/2018 12:09:46 [HTTPserver.cpp:974] HTTP server listening on port(s) 3000
06/Aug/2018 12:09:46 [main.cpp:399] Working directory: /var/tmp/ntopng
06/Aug/2018 12:09:46 [main.cpp:401] Scripts/HTML pages directory: /usr/share/ntopng
06/Aug/2018 12:09:46 [Ntop.cpp:391] Welcome to ntopng x86_64 v.3.4.180726 - (C) 1998-18 ntop.org
06/Aug/2018 12:09:46 [Ntop.cpp:401] Built on CentOS Linux release 7.5.1804 (Core)
06/Aug/2018 12:09:46 [NtopPro.cpp:508] [LICENSE] System Id:     C1DCC802B205A206
06/Aug/2018 12:09:46 [NtopPro.cpp:509] [LICENSE] Edition:       Professional
06/Aug/2018 12:09:46 [NtopPro.cpp:510] [LICENSE] License Type:  Permanent License
06/Aug/2018 12:09:46 [NtopPro.cpp:513] [LICENSE] License:       F1E572506C58150B1330CE817E69F46E15544099970622F63B
06/Aug/2018 12:09:46 [NtopPro.cpp:523] [LICENSE] Maintenance:   Until Thu Apr  4 13:33:17 2019 [241 days left]
06/Aug/2018 12:09:46 [Ntop.cpp:694] Adding 127.0.0.1/32 as IPv4 interface address for lo
06/Aug/2018 12:09:46 [Ntop.cpp:702] Adding 127.0.0.0/8 as IPv4 local network for lo
06/Aug/2018 12:09:46 [Ntop.cpp:694] Adding 172.16.0.27/32 as IPv4 interface address for em1
06/Aug/2018 12:09:46 [Ntop.cpp:702] Adding 172.16.0.0/20 as IPv4 local network for em1
06/Aug/2018 12:09:46 [Ntop.cpp:694] Adding 172.16.48.27/32 as IPv4 interface address for em1.123
06/Aug/2018 12:09:46 [Ntop.cpp:702] Adding 172.16.48.0/24 as IPv4 local network for em1.123
06/Aug/2018 12:09:46 [Ntop.cpp:694] Adding 172.16.16.27/32 as IPv4 interface address for em1.20
06/Aug/2018 12:09:46 [Ntop.cpp:702] Adding 172.16.16.0/23 as IPv4 local network for em1.20
06/Aug/2018 12:09:46 [Ntop.cpp:721] Adding ::1/128 as IPv6 interface address for lo
06/Aug/2018 12:09:46 [Ntop.cpp:730] Adding ::1/128 as IPv6 local network for lo
06/Aug/2018 12:09:46 [Ntop.cpp:721] Adding fe80::f21f:afff:fed9:c200/128 as IPv6 interface address for em1
06/Aug/2018 12:09:46 [Ntop.cpp:730] Adding fe80::f21f:afff:fed9:c200/64 as IPv6 local network for em1
06/Aug/2018 12:09:46 [Ntop.cpp:721] Adding fe80::f21f:afff:fed9:c200/128 as IPv6 interface address for em1.123
06/Aug/2018 12:09:46 [Ntop.cpp:730] Adding fe80::f21f:afff:fed9:c200/64 as IPv6 local network for em1.123
06/Aug/2018 12:09:46 [Ntop.cpp:721] Adding fe80::f21f:afff:fed9:c200/128 as IPv6 interface address for em1.20
06/Aug/2018 12:09:46 [Ntop.cpp:730] Adding fe80::f21f:afff:fed9:c200/64 as IPv6 local network for em1.20
06/Aug/2018 12:09:47 [PeriodicActivities.cpp:59] Started periodic activities loop...
06/Aug/2018 12:09:47 [PeriodicActivities.cpp:100] Each periodic activity script will use 5 threads
06/Aug/2018 12:09:47 [NetworkInterface.cpp:2462] Started packet polling on interface em1 [id: 0]...
06/Aug/2018 12:09:47 [NetworkInterface.cpp:2462] Started packet polling on interface em1.20 [id: 1]...
06/Aug/2018 12:09:47 [NetworkInterface.cpp:2462] Started packet polling on interface em1.123 [id: 2]...
06/Aug/2018 12:09:47 [NetworkInterface.cpp:2462] Started packet polling on interface lo [id: 3]...
06/Aug/2018 12:09:47 [NetworkInterface.cpp:2462] Started packet polling on interface p2p1 [id: 4]...
06/Aug/2018 12:09:47 [NetworkInterface.cpp:2462] Started packet polling on interface em2 [id: 5]...
06/Aug/2018 12:09:47 [NetworkInterface.cpp:2462] Started packet polling on interface p2p2 [id: 6]...
06/Aug/2018 12:09:47 [NetworkInterface.cpp:2462] Started packet polling on interface p2p3 [id: 7]...
06/Aug/2018 12:09:47 [NetworkInterface.cpp:2462] Started packet polling on interface p2p4 [id: 8]...

[root@moon ssl]# grep -v ^# /etc/ntopng/ntopng.conf
-G=/var/run/ntopng.pid
-i=p2p1
--local-networks="172.16.0.0/16"

[root@moon ssl]#

**Comment by simonemainardi** [comment]
you are not telling ntopng to use HTTPs. Add configuration option `-W` and specify the port. Also see: https://www.ntop.org/ntopng/best-practices-to-secure-ntopng/

**Comment by ghost** [comment]
Thank you.
