### ISSUE TITLE
Implement automatic malware packet dump

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1905]
As ntopng has now the ability to stream pcaps to users via HTTP, it would be nice to add an extra feature. ntopng is able to identify blacklisted hosts. It would be nice ntopng to dump locally (not to stream them) pcaps containing traffic coming from these malware hosts (nice to have a pcap per host instead of mixing everything in a single file). This would enable better traffic analysis in addition to flow analysis that ntopng currently provides.

**Comment by simonemainardi** [comment]
After the integration of ntopng with n2disk, it should be preferable to leave the task of recording the traffic to n2disk. What has been described in the issue can be obtained after the integration using alerts:
- see the malware host alerts
- click on the alert to trigger an n2disk traffic extraction of the corresponding host

**Comment by simonemainardi** [comment]
Issue is no longer relevant as ntopng has now the ability to continuously record network traffic using n2disk: https://www.ntop.org/guides/ntopng/advanced_features/traffic_recording.html?highlight=continuous

New links to the ntopng alerts are added to extract malware traffic pcaps directly from n2disk.
