### ISSUE TITLE
No Historical graph on Historical 

### ISSUE THREAD

**Issue by vidgizmo** [ntop/ntopng#1907]
I seemed to have lost the graph on my historical timeseries of traffic.

I have tried completely uninstalling and reinstalling, but no luck :(

I am running a build from the following branches:
- nDPI - 2.2.2-stable
- ntopng - 3.4-stable

I also tried the dev branch and am seeing the same thing.

Here's a screen snapshot showing the missing graph...

https://www.dropbox.com/s/1yvy7mesardguzl/Screenshot%202018-08-09%2015.51.51.png?dl=0

**Comment by emanuele-f** [comment]
Hi, have you enabled the "Traffic" timeseries into the ntopng preferences? If you open the browser inspector, do you see any javascript errors?

**Comment by vidgizmo** [comment]
Traffic is set.

The only warning in the console is:


jquery.js:9455 [Deprecation] Synchronous XMLHttpRequest on the main thread
is deprecated because of its detrimental effects to the end user's
experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.js:9455
ajax @ jquery.js:9173
render @ if_stats.lua?ifid=0&…&zoom=1h&epoch=:525
update @ rickshaw.js:2158
(anonymous) @ rickshaw.js:2293

**Comment by emanuele-f** [comment]
Is this enabled in your case?

![screenshot_7](https://user-images.githubusercontent.com/5488003/44202886-88887c80-a14d-11e8-95be-3bf4a27e62af.png)

Do you have any errors into the ntopng log? Please check out `journalctl -u ntopng`

**Comment by vidgizmo** [comment]
Yes, enabled...

[Attached below]
![screenshot 2018-08-16 10 26 23](https://user-images.githubusercontent.com/1494405/44218261-f37e8700-a13e-11e8-9c04-4d41b33cc6c0.png)


Results from command:

root@odroid64:~# journalctl -u ntopng
-- No entries --

In case it matters, here's the command I am using to start ntopng:

/usr/local/bin/ntopng -U ntop -m 192.168.1.1/24 --data-dir /var/lib/ntopng
-e -i eth0 -v --disable-login 1 --disable-autologout > /var/log/ntopng.log
2>&1

I also checked files in /var/lib/ntopng and all log files are zero length:
-rw-r--r--  1 root root     0 Aug  9 10:47 ntopng.log
-rw-r--r--  1 root root     0 Aug  8 11:04 ntopng.log.1
-rw-r--r--  1 root root     0 Aug  6 16:32 ntopng.log.2
-rw-r--r--  1 root root     0 Aug  6 15:55 ntopng.log.3
-rw-r--r--  1 root root     0 Aug  6 15:01 ntopng.log.4
-rw-r--r--  1 root root     0 Aug  6 15:00 ntopng.log.5
-rw-r--r--  1 root root 57319 Aug 15 03:24 runtimeprefs.json

**Comment by vidgizmo** [comment]
Additionally, in case it matters, here are the preferences related to
Timeseries in the general admin prefs page:
![screenshot 2018-08-16 10 29 01](https://user-images.githubusercontent.com/1494405/44218395-3b051300-a13f-11e8-9cab-4335c326f633.png)

**Comment by emanuele-f** [comment]
@vidgizmo can you please update to the new stable release and see if the problem persists? Please also remove your customized ntopng options and start with a clean command line: `ntopng -m 192.168.1.0/24 --data-dir /var/lib/ntopng -i eth0`. You may also try to add the `-s` option to see if this is a permission issue.

**Comment by vidgizmo** [comment]
I updated to the 2.4-stable for nDPI and the 3.6-stable for ntopng and ran it with the following command line:

sudo /usr/local/bin/ntopng -s -m 192.168.1.1/24 --data-dir /var/lib/ntopng -i eth0
[I tried it both with and without the -s option with the same results as below]

Now I am getting the following message on that page:

HTTP/1.1 500 Internal server error Content-Type: text/html Connection: close   Script "/home/mburkett/code/oss/ntopng/scripts/lua/if_stats.lua" returned an error

...kett/code/oss/ntopng/scripts/lua/modules/graph_utils.lua:585: attempt to perform arithmetic on a nil value

I also see the following lines on the console:

22/Aug/2018 15:54:52 [LuaEngine.cpp:8499] WARNING: Script failure [/home/mburkett/code/oss/ntopng/scripts/lua/if_stats.lua][...kett/code/oss/ntopng/scripts/lua/modules/graph_utils.lua:585: attempt to perform arithmetic on a nil value]
22/Aug/2018 15:55:03 [LuaEngine.cpp:8499] WARNING: Script failure [/home/mburkett/code/oss/ntopng/scripts/lua/if_stats.lua][...kett/code/oss/ntopng/scripts/lua/modules/graph_utils.lua:585: attempt to perform arithmetic on a nil value]
22/Aug/2018 15:56:04 [LuaEngine.cpp:8499] WARNING: Script failure [/home/mburkett/code/oss/ntopng/scripts/lua/if_stats.lua][...kett/code/oss/ntopng/scripts/lua/modules/graph_utils.lua:585: attempt to perform arithmetic on a nil value]
22/Aug/2018 15:57:05 [LuaEngine.cpp:8499] WARNING: Script failure [/home/mburkett/code/oss/ntopng/scripts/lua/if_stats.lua][...kett/code/oss/ntopng/scripts/lua/modules/graph_utils.lua:585: attempt to perform arithmetic on a nil value]

==================

Without the -s option I also saw the following error messages:

22/Aug/2018 16:00:00 [LuaEngine.cpp:4300] ERROR: Unable to create /var/lib/ntopng/0/rrd/192/168/1/63/bytes.rrd [Cannot create temporary file]
22/Aug/2018 16:00:00 [LuaEngine.cpp:4300] ERROR: Unable to create /var/lib/ntopng/0/rrd/192/168/1/63/num_flows.rrd [Cannot create temporary file]
22/Aug/2018 16:00:00 [LuaEngine.cpp:4300] ERROR: Unable to create /var/lib/ntopng/0/rrd/192/168/1/63/tcp.rrd [Cannot create temporary file]
22/Aug/2018 16:00:00 [LuaEngine.cpp:4300] ERROR: Unable to create /var/lib/ntopng/0/rrd/192/168/1/63/udp.rrd [Cannot create temporary file]
22/Aug/2018 16:00:00 [LuaEngine.cpp:4300] ERROR: Unable to create /var/lib/ntopng/0/rrd/192/168/1/63/icmp.rrd [Cannot create temporary file]
22/Aug/2018 16:00:00 [LuaEngine.cpp:4300] ERROR: Unable to create /var/lib/ntopng/0/rrd/192/168/1/43/bytes.rrd [Cannot create temporary file]
22/Aug/2018 16:00:00 [LuaEngine.cpp:4300] ERROR: Unable to create /var/lib/ntopng/0/rrd/192/168/1/43/num_flows.rrd [Cannot create temporary file]
22/Aug/2018 16:00:00 [LuaEngine.cpp:4300] ERROR: Unable to create /var/lib/ntopng/0/rrd/192/168/1/43/tcp.rrd [Cannot create temporary file]
22/Aug/2018 16:00:00 [LuaEngine.cpp:4300] ERROR: Unable to create /var/lib/ntopng/0/rrd/192/168/1/43/udp.rrd [Cannot create temporary file]
22/Aug/2018 16:00:00 [LuaEngine.cpp:4300] ERROR: Unable to create /var/lib/ntopng/0/rrd/192/168/1/43/icmp.rrd [Cannot create temporary file]

**Comment by vidgizmo** [comment]
Got it working by doing the following:

rm -rf /var/lib/ntopng
mkdir /var/lib/ntopng
chmod 777 /var/lib/ntopng

I am guessing I could probably change the permissions to only the owner of the ntopng process. But it is working :)

![screenshot 2018-08-22 16 04 31](https://user-images.githubusercontent.com/1494405/44491011-89298300-a625-11e8-948b-bc30b3954a4b.png)

**Comment by simonemainardi** [comment]
Correct. It seems that you changed the user who was running ntopng.

Note that when the data directory (default /var/tmp/ntopng) doesn't exist, the user who's running ntopng creates it with restrictive permissions so that the user is the only one to have read-write-execute. See for example:

```
simone@devel:/var/tmp$ ls -lha | grep ntopng
drwx------  8 nobody   nogroup 4.0K Aug 23 09:55 ntopng
```

If you then run ntopng with another user (apart from root) who doesn't own the data directory, then read/write accesses will fail and this will result in missing charts.

----

This seems you case because as you initially run ntopng with user ntop

> In case it matters, here's the command I am using to start ntopng:
> /usr/local/bin/ntopng -U ntop -m 192.168.1.1/24 --data-dir /var/lib/ntopng
> -e -i eth0 -v --disable-login 1 --disable-autologout > /var/log/ntopng.log
> 2>&1

and then you didn't specify any user, letting ntopng run with nobody

> sudo /usr/local/bin/ntopng -s -m 192.168.1.1/24 --data-dir /var/lib/ntopng -i eth0

---

You could have just `chown`ed  the data directory rather than deleting is for a less brutal solution.

---

As a final remark, I don't know why you are starting/stopping ntopng manually rather than using systemd or initd. We provide scripts for them and you'll also have logging automatically handled.
