### ISSUE TITLE
Geomap error message

### ISSUE THREAD

**Issue by dvachon2018** [ntop/ntopng#1909]
hi! i am using last ntopng (arm) v3.5.180802 - Enterprise/Embedded Edition
On geo map page, i have the map but always a message similar to ' unable to load google map correctly on this page' (this is a translation from my french message'
I had a google api key but had this problem, so i created another new google map api key and put it in preference (+ a reboot) but still same problem with both IE and last Chrome on windows 10

**Comment by emanuele-f** [comment]
Hi, please open the browser javascript inspector to see if there are any errors. For example, after a few requests I get `You have exceeded your request quota for this API`

**Comment by dvachon2018** [comment]
javascript console via CTRL-MAJ-J and yes there was error with quota, i dont understand because this was a new key. Anyway on google api console web i created a new projet with api key and it is working fine now. Thank you!
