### ISSUE TITLE
Networks only show 10 networks

### ISSUE THREAD

**Issue by Gavin-yzg** [ntop/ntopng#1910]
ntopng Community Edition v.3.4.180810   system centos7.4
Networks can only show 10 networks

**Comment by emanuele-f** [comment]
Hi, please note that Networks only shows active local networks, not idle ones. Can this be the problem?

**Comment by Gavin-yzg** [comment]
some active local networks not show

**Comment by Gavin-yzg** [comment]
Upgrading to  v.3.4.180813 seems as normal
