### ISSUE TITLE
Applied license but it keeps expiring

### ISSUE THREAD

**Issue by S0t0nN3rdS** [ntop/ntopng#1911]
I was issued with an enterprise license (non-profit organisation), followed the instructions to generate the license, applied it, but it always seems to expire and the service stops.

Happy to provide logs or anything else that maybe of use, would really like to get this up and running.

Thanks

**Comment by emanuele-f** [comment]
Please check out https://www.ntop.org/support/faq/my-license-does-not-work-what-can-i-do/

**Comment by S0t0nN3rdS** [comment]
Trying the suggested commands, butnothing working:

C:\>cd "\Program Files\ntopng"

C:\Program Files\ntopng>ntopng.exe /h

Unrecognized option: /h
Available options:
/i [ntopng options] - Install ntopng as service
/c                  - Run ntopng on a console
/r                  - Deinstall the service
/h                  - Prints this help

Usage: type ntopng /c -h

C:\Program Files\ntopng>ntopng --check-license

Unrecognized option: --check-license
Available options:
/i [ntopng options] - Install ntopng as service
/c                  - Run ntopng on a console
/r                  - Deinstall the service
/h                  - Prints this help

Usage: type ntopng /c -h

C:\Program Files\ntopng>

**Comment by S0t0nN3rdS** [comment]
Ok, os the first talks of a license file.. I recall having to do that for nprobe, but no mention anywhere of doing it for ntopng and applied license following instructions to add in the About page.  

The only commands I could run showed an invalid license...  as the app runs as a service, I cant run the app from cli to see the output.

**Comment by S0t0nN3rdS** [comment]
Ive managed to get some output and am seeing a licnse mismatch error.. Could I have been given the wrong license for the version I have?

**Comment by emanuele-f** [comment]
You can run those commands even if running as service. Please post here the full output of the commands.

**Comment by S0t0nN3rdS** [comment]
C:\Program Files\ntopng>ntopng

NOTE:
Under your version of Windows, ntopng is started as a service.
Please open the services control panel to start/stop ntop,
or type ntop /h to see all the available options.

StartServiceControlDispatcher failed!

C:\Program Files\ntopng>


C:\Program Files\ntopng>ntopng /c --check-license
Starting ntopng
Running ntopng.
Invalid license

C:\Program Files\ntopng>  ntopng /c --version
Starting ntopng
Running ntopng.
v.3.5.180729    [Enterprise/Professional build]
GIT rev:        dev:e5f1a9159b4805981ede4e5254977a2cc02069c3:20180729
Pro rev:        r1569
Built on:       Windows
System Id:      1489517303-9206a1d8
Platform:       x64
Edition:        Enterprise
License Type:   Time-Limited
Validity:       Until Fri Aug 17 15:37:14 2018
License:        E3B0FBA1439CC88404D449EF28FC5A8D15646731593BC3DC06


:\Program Files\ntopng>ntopng /c --online-license-check
tarting ntopng
unning ntopng.
7/Aug/2018 15:29:04 [Ntop.cpp:1567] Setting local networks to 127.0.0.0/8
7/Aug/2018 15:29:04 [Redis.cpp:132] Successfully connected to redis 127.0.0.1@0
7/Aug/2018 15:29:04 [Redis.cpp:132] Successfully connected to redis 127.0.0.1@0
7/Aug/2018 15:29:04 [NtopPro.cpp:310] [LICENSE] Reading license from Redis
7/Aug/2018 15:29:04 [NtopPro.cpp:205] [LICENSE] E3B0FBA1439CC88404D449EF28FC5A8D15646731593BC3DC06: unable to validate Enterprise license [License mi
match error]
7/Aug/2018 15:29:04 [NtopPro.cpp:205] [LICENSE] E3B0FBA1439CC88404D449EF28FC5A8D15646731593BC3DC06: unable to validate Professional license [License
ismatch error]
7/Aug/2018 15:29:04 [NtopPro.cpp:451] WARNING: [LICENSE] Invalid or missing license
7/Aug/2018 15:29:04 [NtopPro.cpp:468] WARNING: [LICENSE] ntopng will now run in enterprise edition for 10 minutes
7/Aug/2018 15:29:04 [NtopPro.cpp:470] WARNING: [LICENSE] before returning to community mode
7/Aug/2018 15:29:04 [NtopPro.cpp:472] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
7/Aug/2018 15:29:04 [NtopPro.cpp:474] WARNING: [LICENSE] or run ntopng in community mode starting
7/Aug/2018 15:29:04 [NtopPro.cpp:475] WARNING: [LICENSE] ntopng --community
7/Aug/2018 15:29:04 [PcapInterface.cpp:91] Reading packets from interface {27B01DA7-2F47-4315-AB1B-9D167FEA878A}...
7/Aug/2018 15:29:04 [Ntop.cpp:1687] Registered interface {27B01DA7-2F47-4315-AB1B-9D167FEA878A} [id: 7]
7/Aug/2018 15:29:05 [PcapInterface.cpp:91] Reading packets from interface {28E00A53-8F93-4DBA-86D0-FD5ECEBE8332}...
7/Aug/2018 15:29:05 [Ntop.cpp:1687] Registered interface {28E00A53-8F93-4DBA-86D0-FD5ECEBE8332} [id: 8]
7/Aug/2018 15:29:05 [PcapInterface.cpp:91] Reading packets from interface {09843467-16EE-41F7-9978-AA110A51C058}...
7/Aug/2018 15:29:05 [Ntop.cpp:1687] Registered interface {09843467-16EE-41F7-9978-AA110A51C058} [id: 9]
7/Aug/2018 15:29:05 [HTTPserver.cpp:1066] Web server dirs [C:\Program Files\ntopng\httpdocs][C:\Program Files\ntopng\scripts]
7/Aug/2018 15:29:05 [HTTPserver.cpp:1069] HTTP server listening on 3000
7/Aug/2018 15:29:05 [main.cpp:376] Working directory: C:\Users\netadmin\Documents\ntopng
7/Aug/2018 15:29:05 [main.cpp:378] Scripts/HTML pages directory: C:\Program Files\ntopng
7/Aug/2018 15:29:05 [Ntop.cpp:387] Welcome to ntopng x64 v.3.5.180729 - (C) 1998-18 ntop.org


Thanks

**Comment by lucaderi** [comment]
Sent you instructions via email

**Comment by S0t0nN3rdS** [comment]
Thanks, all sorted!
