### ISSUE TITLE
reset all data

### ISSUE THREAD

**Issue by dvachon2018** [ntop/ntopng#1913]
hi, using ntopng enterprise on arm.
i want to do a full reset of all hosts data so i stop ntopng, empty mysql flow database and did a rm -r * in /var/tmp/ntopng but when i restart ntopng hosts data ex: last seen is still there ex: 3 days.
So what else to delete ?
note: i want to keep user/config/license

**Comment by emanuele-f** [comment]
Hello, you should also flush redis: `redis-cli flushdb`

**Comment by dvachon2018** [comment]
redis-cli flushdb worked but had to redo the config and license

**Comment by emanuele-f** [comment]
Sorry for that. I assumed license was written to the license file. We should extend the "Manage Stored Data" page to work with networks and provide a "Delete All" button. I'm opening a new github issue for this.
