### ISSUE TITLE
Extend Manage Stored Data

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#1914]
It would be nice to add the ability to delete a whole network data or all the existing data through the `Delete` tab in Manage Stored Data.

**Comment by dvachon2018** [comment]
yes should have a easy way to reset everything ( redis, mysql flow, ntop data) to empty and without loosing config and license.

**Comment by simonemainardi** [comment]
Ability to delete all interfaces data is now implemented. Manage data menu can be used to delete:

- data for all the inactive, previously used interfaces.
- data for the active, in-use interface (in this case a restart of ntopng is required)

Moreover, when creating an interface out of a pcap file, any data created is deleted and periodic scripts aren't run at all.
