### ISSUE TITLE
Configuration for reading from a mirror port.

### ISSUE THREAD

**Issue by koenvdheuvel** [ntop/ntopng#1917]
Currently ntopng counts all traffic as RX which should be handled by #1452 however it doesn't know
if it is reading from a mirror port.

**Comment by lucaderi** [comment]
In essence in addition to #1452, It needs to be implemented a preference in network interface to tell ntopng that the observed is not originated by the host but it is received though a mirror. This means that activities like network discovery or TX should be completely disabled.

**Comment by simonemainardi** [comment]
implemented in https://github.com/ntop/ntopng/commit/0e258ce83173c35d5f3166073fdab63a62cbda7e
