### ISSUE TITLE
How to get report with tcp ports usage?

### ISSUE THREAD

**Issue by DearTanker** [ntop/ntopng#1921]

**Comment by emanuele-f** [comment]
Hi, you can get a real time view of all the ports usage in the host page: https://www.ntop.org/guides/ntopng/web_gui/host_details.html#ports . The report, available in the pro/enterprise versions, does not contain ports usage but it contains L7 applications breakdown, please check out https://www.ntop.org/guides/ntopng/web_gui/report.html .
