### ISSUE TITLE
Getting QoE data

### ISSUE THREAD

**Issue by foxdavion** [ntop/ntopng#1924]
Hello.
I'm a network engineer, and work for ISP.  We have many pppoe clients. I'm mirroring the port with aggregation.
We have a question about how we can to automate receiving QoE data(Retransmissions and so on) from ntopng to third party monitoring system(eg zabbix).
I want to receive data not through the web, for automatic analysis and identification of problematic subscribers.

**Comment by simonemainardi** [comment]
You can programmatically query every local host of interest for its json using the following enpoint:

```
http://devel:3000/lua/host_get_json.lua?ifid=1&host=192.168.2.126
````

the returned JSON will contain the requested information in 

- tcpPacketStats.pktRetr
- tcpPacketStats.pktOOO
- tcpPacketStats.pktLost
- tcpPacketStats.pktKeepAlive

The whole set of metrics available in the json can be found at https://github.com/ntop/ntopng/blob/dev/src/Host.cpp#L623

Note that for efficiency reasons we don't report TCP stats that are at zero.

**Comment by foxdavion** [comment]
curl --cookie "user=admin; password=admin"  "http://localhost:3000/lua/host_get_json.lua?ifid=1&host=x.x.x.x"

![image](https://user-images.githubusercontent.com/21257060/44517707-d703c100-a6e1-11e8-9315-64d29b5d8e20.png)
???

**Comment by simonemainardi** [comment]
did you do the first login from the web ui after the installation? note that ntopng forces you to change the admin password that cannot be admin.

**Comment by foxdavion** [comment]
his was an example, of course I changed the password)

**Comment by simonemainardi** [comment]
It works beautifully using the latest ntopng:

```
Simones-MacBook-Pro:~ simone$ curl --cookie "user=admin; password=admin1" "http://devel:3000/lua/host_get_json.lua?ifid=1&host=192.168.2.222"
{"flows.as_server":1196,"tcpPacketStats.pktRetr":70,"tcp_sent":{"bytes":6031437,"packets":9920},"throughput_bps":1051.542969,"localHost":true,"throughput_pps":3.399169,"symbolic_name":"devel","tcpPacketStats.pktLost":13,"mac_address":"00:25:90:D4:CC:F9","http":{"receiver":{"query":{"num_get":1164,"num_other":0,"total":1167,"num_head":0,"num_put":0,"num_post":3},"response":{"num_5xx":0,"num_2xx":2,"total":2,"num_4xx":0,"num_3xx":0,"num_1xx":0},"rate":{"query":{"post":0,"other":0,"get":0,"put":0,"head":0},"response":......
```

Check the whole html output you are getting.  My feeling is that the auth is failing...

**Comment by foxdavion** [comment]
thanks,  x.x.x.x@vlanid )

**Comment by simonemainardi** [comment]
thank you for reporting.
