### ISSUE TITLE
Ability to modify Slack channel for Alerts

### ISSUE THREAD

**Issue by brianluers25809** [ntop/ntopng#1925]
Right now in the gui it does not allow you to select what slack channels alerts go into, they are pre categorized into channels based on the alert.  I can manually edit the slack.lua to put all alerts into one channel, but every time ntopng is updated it has to be changed back.  Would like to have a GUI option to select the slack channel alerts are placed into.

**Comment by emanuele-f** [comment]
Hi, this is already implemented in the latest dev. See https://github.com/ntop/ntopng/issues/1653
