### ISSUE TITLE
Receiving constant "TCP connection refused" messages

### ISSUE THREAD

**Issue by boisgada** [ntop/ntopng#1926]
Everything appears to be working; however we are constantly receiving the following message in syslog:

> Aug 20 19:24:10 [SERVER_NAME REMOVED] ntopng: [Alert] TCP connection refused: <A HREF='/lua/host_details.lua?host=@0&ifid=1&page=alerts'>[IP_ADDRESS REMOVED]</A> &gt; <A HREF='/lua/host_details.lua?host=@0&ifid=1&page=alerts'>[SERVER_NAME REMOVED]</A> [info: ]

Server: ntopng v.3.4.180820    [Enterprise/Professional build]
Sensors: nProbe v.8.5.180813 (r6250) [Embedded] for armv7l-unknown-linux-gnueabihf

Configured with 'pull' method

**Comment by emanuele-f** [comment]
Please check out the alert settings into the ntopng preferences

**Comment by boisgada** [comment]
Which of the settings controls the TCP connection refused messages?  I would like alerts sent to syslog, but I don't know the origin of these specific messages, so I am unable to troubleshoot.

**Comment by emanuele-f** [comment]
"Probing Alerts"

**Comment by boisgada** [comment]
That fixed it.  Curious if more information is available which is not being displayed in syslog.  If these are probing alerts it would be nice to be able to track down more details.  (src, dst, service, etc)

**Comment by simonemainardi** [comment]
All the information associated with the flow is reported, including src and destination ips, ports, and the l4 proto.

![image](https://user-images.githubusercontent.com/3397663/44513699-597a8980-a6be-11e8-8e56-df748945df4c.png)

Note that we mark a flow as 'connection refused' when, during the three-way handshake, the client sends a SYN and the server responds with a RST. So we're during the initial three-way handshake and haven't seen enough traffic to perform the deep packet inspection and detect a Layer-7 protocol. This is why Layer-7 information is missing.

----

Finally, I noticed you're using nprobe dev and ntopng stable.

```
Server: ntopng v.3.4.180820 [Enterprise/Professional build]
Sensors: nProbe v.8.5.180813 (r6250) [Embedded] for armv7l-unknown-linux-gnueabihf
```

Please, make sure to use both softwares as either stable or dev but don't mix them.
