### ISSUE TITLE
Enhancement request - more granular access controls

### ISSUE THREAD

**Issue by boisgada** [ntop/ntopng#1927]
Request more granular access control for enterprise edition.  Possible options:
- the ability to assign access to multiple interfaces for specific users or group of users
- the ability to group interfaces
- the ability to group users

Server: v.3.4.180820    [Enterprise/Professional build]

**Comment by emanuele-f** [comment]
Hi, please note that you can actually group interfaces via "view interfaces". Check out https://www.ntop.org/guides/ntopng/advanced_features/view_interfaces.html .

**Comment by boisgada** [comment]
Thank you.  That works and does enough to meet my requirements.

**Comment by simonemainardi** [comment]
note that, in addition, you can also limit the scope of any non-admin ntopng user to a single interface (see field Allowed Interface):

![image](https://user-images.githubusercontent.com/3397663/44512411-becc7b80-a6ba-11e8-97b0-df22cd1b37d1.png)
