### ISSUE TITLE
Integrate ntopng with Suricata 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1928]
Suricata (https://suricata-ids.org) is a popular IDS/IPS that can export data in Eve JSON support (https://suricata.readthedocs.io/en/suricata-4.0.5/output/eve/eve-json-output.html). ntopng should be modified so that it can become a feed for Suricata events so that ntopng can ingest them for:
-  becoming a monitoring console for Suricata
- complementing monitoring data with Suricata security analysis

**Comment by mimugmail** [comment]
+1 nice idea!

**Comment by xisafe** [comment]
bro IDS

**Comment by cardigliano** [comment]
Implemented with a SyslogParser C++ component collecting syslog messages and a Lua script (https://github.com/ntop/ntopng/commit/76759a7d0372df10dce088bc552e26395a714ea7) processing flows and alerts in Eve JSON format from Suricata. Documentation is available at
http://www.ntop.org/guides/ntopng/advanced_features/suricata.html
