### ISSUE TITLE
Implement more granular timeseries

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1929]
Since a more efficient backend (InfluxDB) has been released, it would be nice to have the ability to write metrics more often (nDPI host counters are currently written every 5 mins), e.g. every 10-30 sec. As this could be a costly options, they need to be configurable in terms of frequency, backend etc.

**Comment by emanuele-f** [comment]
Implemented in cfc345709deffbe56f14706210d97c152112f057 (interfaces) and a594e648c4335931e2fcb2ff91322aeea503ae3a (local hosts)
