### ISSUE TITLE
ntopng not showing full traffic - Do I need PF_RING - How do i install and use with ntopng

### ISSUE THREAD

**Issue by juesor** [ntop/ntopng#193]
I have a nTAP installed feeding into an Intel SFP+ LR optic going into an Intel 82599ES 10-Gigabit SFI/SFP+.

I have ntopng installed 
[ntop@ntopng ~]# ntopng --version
v.2.0.150930 [Professional Edition]
GIT rev:   dev:f2d2b1b8ad9c00cd60decc30ccb2005486ea08dc:20150930
Pro rev:   r473
System Id: 3D0153209105A1EF
Built on:  CentOS Linux release 7.1.1503 (Core)

With nload started and running on the interface that is tapped into the server.  I see the following.

Curr: 339.58 MB/s
Avg: 272.06 MB/s
Max: 602.82 MB/s
Ttl: 1127.43 GByte

© 1998- 2015 - ntop.org 
Generated by ntopng Professional v.2.0.150930
for user admin and interface p2p1

193.27 Mbps [74,024 pps]
Uptime: 2 h, 48 min, 56 sec

Those numbers don't match up.  So I spoke a bit to Luca and he suggested PF_RING ZC now I am looking for a PF_RING install guide or setup guide.  Do I need PF_RING ZC?  What does that do compared to PF_RING?

I really need to be able to watch traffic on my network which pushes currently 1.95 GBps.  Right now it doesn't look like all the packets are being inspected properly.

**Comment by lucaderi** [comment]
Can you please report if you have drops in the interface (menu Interfaces)?

**Comment by juesor** [comment]
Received Traffic | 26.71 GB [92,024,477 Pkts] ^
Dropped Packets | 129,031 Pkts [0.14 % ] -

I needed to restart ntopng this morning as the service is still not starting properly so my traffic is low for now.

**Comment by juesor** [comment]
Received Traffic	4.92 TB [18,432,581,855 Pkts] 	
Dropped Packets	16,110,056 Pkts [ 0.09 % ] 	 

But in the same time my interface shows

p2p1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::92e2:baff:fe5e:a43c  prefixlen 64  scopeid 0x20<link>
        ether 90:e2:ba:5e:a4:3c  txqueuelen 1000  (Ethernet)
        RX packets 22046628379  bytes 8425262388464 (7.6 TiB)
        RX errors 5002  dropped 0  overruns 0  frame 5002
        TX packets 8  bytes 648 (648.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by juesor** [comment]
http://screencast.com/t/yp8qKUnZtwN

I took a screenshot of ntopng and iftop -i p2p1 at the exact same time.

**Comment by lucaderi** [comment]
I think I have fixed this bug that should be caused by TSO. Please checkout the new code and report.

**Comment by juesor** [comment]
[root@HEND-ntopng ~]# ntopng --version
v.2.1.151104 [Professional Edition]
GIT rev:   dev:99dd2d0d220a4785ff72eda420fc2e2908688b9a:20151104
Pro rev:   r509
System Id: 3D0153209105A1EF
Built on:  CentOS Linux release 7.1.1503 (Core)


Installed Packages
ntopng.x86_64                                                                                  2.1.151104-617                                                                                   @ntop

i restarted ntopng now and will check in the morning the throughput.

**Comment by juesor** [comment]
Installed Packages
pfring.x86_64                                                                                     6.1.1-314                                                                                     @ntop
[root@HEND-ntopng ~]#


So pfring is installed is there any config to that i can look at to better optimize ntopng.

i am still seeing gaps as of yesterday.
