### ISSUE TITLE
PF_RING-Napatech license valid or not

### ISSUE THREAD

**Issue by drean1968** [ntop/ntopng#1931]
We have bought a PF-RING Napatech license, based on the 'zcount -h' information. On our system 'zcount -h' shows the following information:

zcount - (C) 2014-2018 ntop.org
using PFRING_ZC v.7.2.0.180626
...

When we got the license from shop.ntop.org/mkzclicense, we generated a file '811-0008-02-10' inside the folder '/etc/pf_ring' with the license key inside the file.

When we check the pf_ring license with the command 'zcount -i nt:0 -C', we get the following output:

#############################################################
# ERROR: You do not seem to have a valid PF_RING-Napatech 7.2.0.180163
# license for port 0 (S/N 811-0008-02-10-0000-234516)
# ERROR: Please get one ate http://shop.ntop.org/.
#############################################################
# We're now wokring in demo mode with packet capture and
# transmission limited to 5 minutes
#############################################################
#############################################################
# ERROR: You do not seem to have a valid PF_RING-Napatech 7.2.0.180163
# license for port 0 (S/N 811-0008-02-10-0000-234516)
# ERROR: Please get one ate http://shop.ntop.org/.
#############################################################
License Ok

This output is a little weird... Based on this output, is the license valid or not....? When we run Cento / Ntopng, we get an error that the license of pf_ring is not valid. So the license doesn't seem to work.

Another thing that strikes me is that 'zcount -h' and 'zcount -i nt:0 -C' gives a different version number : v.7.2.0.180626 and 7.2.0.180163. We have used the v.7.2.0.180626 version to buy a license.

Could you please help me with getting the license to work? 
Thank you in advance!!

**Comment by cardigliano** [comment]
@drean1968 the license should be generated for '811-0008-02-10-0000-234516', where did you get '811-0008-02-10'?

**Comment by drean1968** [comment]
sorry for the late reaction, but thanks it's working now.

**Comment by simonemainardi** [comment]
Thanks for reporting. Next time please use pf_ring issue tracker for pf_ring related issues: https://github.com/ntop/PF_RING/issues
