### ISSUE TITLE
NTOPNG - starts dropping after 10mins

### ISSUE THREAD

**Issue by louisesc** [ntop/ntopng#1932]
Hi

We are running the latest version 3.6.1 and we have the same issue we have in 3.4.

After 10 minutes ntop starts dropping packets.

We are doing approximately 300 flows/s and 60k pps and 400 Mbits/s.

I downgraded to 2.4 and that worked fine, although was missing some of the features we needed.
We also tried  having ntopng as an nprobe collector, rather that getting the flows in itself and this also worked and did not drop packets.
We run on Centos 7.

I have tried several configurations as suggested by previous issues, but nothing seemed to work, such as disabling alerting, increasing and decreasing the Hosts and Flows (x and X) numbers, packet filters etc.
We have one GB interface being used, no PF_Ring.

I am interested to know what may be causing this, as although using nprobe to ntopng works, we lose some of the features like RTT, some of the TCP information on the flows and the new PCAP download feature.

Any suggestions would be much appreciated. We are running the Professional version.

**Comment by simonemainardi** [comment]
please, switch back to version version 3.6 and report:

- output of ntopng --version
- full ntopng configuration used
- hw specs of the machine running ntopng, including ram and cores
- information obtained using top/htop for the ntopng process, including load and mem used
- screenshots of the interface page that reports drop, volume of drops
- number of active hosts / flows  (the bottom-right corner of the ntopng web ui)
- you said drops occur after 10 minutes. 10 minutes exactly?

**Comment by simonemainardi** [comment]
any news?

**Comment by simonemainardi** [comment]
Information requested. No feedback received. Closing. Reopen with the requested information if necessary.
