### ISSUE TITLE
Upgrade ntopng from Stable to Dev

### ISSUE THREAD

**Issue by brianluers25809** [ntop/ntopng#1933]
I am looking for an easy way to change the stable version of ntopng being used to the Dev version.  I purchased the Nbox from truepath and hte only option it gives to install or uninstall ntopng pro.  When i uninstall the ntopng stable version (or try to download pkg for dev) i get the following error:

admin@CHINTOP1:~$ sudo dpkg -i apt-ntop.deb
sudo: unable to resolve host CHINTOP1
dpkg: regarding apt-ntop.deb containing apt-ntop:
 apt-ntop conflicts with apt-ntop-stable
  apt-ntop-stable (version 2.6-933) is present and installed.

dpkg: error processing archive apt-ntop.deb (--install):
 conflicting packages - not installing apt-ntop
Errors were encountered while processing:
 apt-ntop.deb

Is there a way to change to dev without completely removing ntopng/nprobe and reinstalling?

**Comment by simonemainardi** [comment]
remove the stable repo first:

```
apt-get remove apt-ntop-stable
```

Then install the dev one

```
sudo dpkg -i apt-ntop.deb
```

Clearly, if you change from stable to dev, all the ntop applications will be updated as soon as you run an `apt-get update && apt-get upgrade`
