### ISSUE TITLE
Special character problem for webinterface authentication

### ISSUE THREAD

**Issue by ummeegge** [ntop/ntopng#1935]
Hello,
i wanted to report a problem with special characters for the webinterface authentication on ntopng version
`
v.3.7.180823	[Community build]
GIT rev:	::20180823
`

which are possibly already known but i wanted to deliver some tests to specify/identify them .

Special characters which worked are:
`
! $ % & / ( ) = ? ^ ; : . , _ - # * 
`

Special Characters which do not worked and ended up in a no access to the webinterface without warnings are:
` + ° < > & "`

One character which broke the "Manage user" setup was
`
'
`
and ended up with a "Invalid parameters" message which also appears after trying regular normally working alphanumerics.

We have had a problem in the IPFire forum where a user entered one of the problem characters after installation and wasn´t able to login again. We tried then different password resets via redis-cli posted in here #153 but also with the -l=1 option via ntopng.conf but also the README.users from here --> https://github.com/xtao/ntopng/blob/master/README.users didn´t delivered a solution to reset the password to start over again with 'admin' 'admin'. This problem appeared with version 
`
v.3.5.180626	[Community build]
GIT rev:	dev:5f461dfbd372e8ef2e44db163941007b34d7001b:20180626
`

Hope this information is useful for you. If you need further informations let it me know.

Best regards,

Erik

**Comment by simonemainardi** [comment]
The link to the readme file you've provided isn't affiliated with us.

For the password reset you should refer to the instructions at: https://github.com/ntop/ntopng/blob/dev/doc/README.md
In particular, you have to delete file runtimeprefs.json to make sure the password gets reset.

For the special characters, please tell me the platform on which you are building and enclose config.h and config.log files generated after the configure. Are you using luajit?

**Comment by ummeegge** [comment]
Thanks for looking into this.
> For the password reset you should refer to the instructions at: https://github.com/ntop/ntopng/blob/dev/doc/README.md
> In particular, you have to delete file runtimeprefs.json to make sure the password gets reset.

Good to know, haven´t found that one.

> For the special characters, please tell me the platform on which you are building

It is an IPFire building environment --> https://wiki.ipfire.org/devel/ipfire-2.x/addon-howto on a Linux Mint host machine.

objdump output:

```
/usr/bin/ntopng:     file format elf64-x86-64

Contents of section .comment:
 0000 4743433a 2028474e 55292037 2e332e30  GCC: (GNU) 7.3.0
 0010 0044796e 41534d20 312e342e 3000      .DynASM 1.4.0.
```

File output

`
/usr/bin/ntopng: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, stripped, with debug_info`

config.h can be found in here --> https://people.ipfire.org/~ummeegge/ntopng/build_logs/ntopng-3.7_config.h .

config.log is located in here --> https://people.ipfire.org/~ummeegge/ntopng/build_logs/ntopng-3.7_config.log .

> Are you using luajit?

No external package.

Best regards,

Erik

**Comment by simonemainardi** [comment]
Latest ntopng handles this issue. all the chars highlighted above are now handled and can be used as passwords. Don't forget to clean old users / passwords before setting the new ones.
