### ISSUE TITLE
Influxdb - NTOPNG requests admin rights

### ISSUE THREAD

**Issue by darox** [ntop/ntopng#1937]
I set up NTOPNG 3.7 with Influxdb export, but for some reason NTOPNG requests to have admin privileges, although the database already exists:
`Could not create "ntopng_srv_ubn_services_2" database: [403] error authorizing query: ntopng not authorized to execute statement 'CREATE DATABASE ntopng_srv_ubn_services_2', requires admin privilege`

As I'm running an environment with restricted user rights, I don't want to give admin rights to the users which is pushing the data from NTOPNG to Influxdb. Please add the option to have only read / write access users.

**Comment by emanuele-f** [comment]
An additional check is now performed automatically to prevent such errors. Please note that the database must exists and the user must have proper privileges on it. The new package will be available in one hour.

**Comment by darox** [comment]
@emanuele-f Nice, thanks!

**Comment by darox** [comment]
@emanuele-f What's the best way to troubleshoot, if no data is sent to Influxdb. For some short time it was working, but now it doesn't work anymore.
