### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by prasanthi97** [ntop/ntopng#1938]
After installing ntopng 3.6 it is giving error as follows in ubuntu 14.04
ntopng: error while loading shared libraries: libmaxminddb.so.0: cannot open shared object file: No such file or directory
Prev version worked well.

**Comment by simonemainardi** [comment]
thanks for reporting that.

Please run

```
add-apt-repository ppa:maxmind/ppa
apt-get install libmaxminddb0
```

Then re-run ntopng. Please, let me know if that fixed the issue so I can write a note on the update procedure.

**Comment by prasanthi97** [comment]
Even after running this apt-get install libmaxminddb0 it is giving
E: Unable to locate package libmaxminddb0
so, ntopng is not getting started

**Comment by simonemainardi** [comment]
I think you didn't add the repo as suggested. See below:

```
root@simone-VirtualBox-1:/home/simone# add-apt-repository ppa:maxmind/ppa
 
 More info: https://launchpad.net/~maxmind/+archive/ubuntu/ppa
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmpgqypmfh4/secring.gpg' created
gpg: keyring `/tmp/tmpgqypmfh4/pubring.gpg' created
gpg: requesting key DE742AFA from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpgqypmfh4/trustdb.gpg: trustdb created
gpg: key DE742AFA: public key "Launchpad PPA for MaxMind" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
root@simone-VirtualBox-1:/home/simone# apt-get update
root@simone-VirtualBox-1:/home/simone# apt-cache search libmaxminddb0
libmaxminddb0 - IP geolocation database library
root@simone-VirtualBox-1:/home/simone# apt-get install libmaxminddb0
```

**Comment by prasanthi97** [comment]
After adding respiratory I have got the same. Still I'm not getting
root@200411DC0:~# add-apt-repository ppa:maxmind/ppa
 
 More info: https://launchpad.net/~maxmind/+archive/ubuntu/ppa
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmpq_mrp1pu/secring.gpg' created
gpg: keyring `/tmp/tmpq_mrp1pu/pubring.gpg' created
gpg: requesting key DE742AFA from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpq_mrp1pu/trustdb.gpg: trustdb created
gpg: key DE742AFA: public key "Launchpad PPA for MaxMind" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
root@200411DC0:~# apt-get install libmaxminddb0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libmaxminddb0

Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmpiow_durz/secring.gpg' created
gpg: keyring `/tmp/tmpiow_durz/pubring.gpg' created
gpg: requesting key DE742AFA from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpiow_durz/trustdb.gpg: trustdb created
gpg: key DE742AFA: public key "Launchpad PPA for MaxMind" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK

**Comment by simonemainardi** [comment]
run:

```
apt-get update
```

after the addition of the repository...

**Comment by prasanthi97** [comment]
yes, It got fixed. notp is running as earlier.
Thank you

**Comment by simonemainardi** [comment]
thank you for reporting.
