### ISSUE TITLE
Implement timeseries cleanup

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1940]
Sometimes it is requested to cleanup an existing installation and drop old data. It is requested to implement a cleanup feature (similar to what already present in ntopng "Manage Storage Data") so that existing timeseries are also cleaned up (with RRD files are deleted with Influx they are dropped from the database)

**Comment by simonemainardi** [comment]
logically divided into:
- influx cleanup (@emanuele-f )
- rrd cleanup

**Comment by simonemainardi** [comment]
@emanuele-f please fill the function that cleans influxdb data at https://github.com/ntop/ntopng/commit/bd27304c54547fa8ad791822dc17f4e0b4f9561f#diff-d47d1f4a55320307081f8ece3ddc5fd7R180
