### ISSUE TITLE
ntopng with fritzdump directly runs into a SIGSEV 'reading NULL VMA' at pcap_get_selectable_fd () 

### ISSUE THREAD

**Issue by bentolor** [ntop/ntopng#1941]
I just installed ntopng with `fritzdump` on a freshly upgraded bionic installation following an article from Heise/c't. first start it claimed an already running instance. This is what I did after installing `pfring nprobe ntopng ntopng-data n2disk cento`

```
 sudo systemctl stop ntopng.service  ; and sudo systemctl disable ntopng.service
 sudo rm -fr /var/tmp/ntopng
 fritzdump myRouterpassword 
```

this results in 

```
Capturing traffic..
25/Aug/2018 13:23:45 [Ntop.cpp:1544] Setting local networks to 127.0.0.0/8
...
25/Aug/2018 13:23:46 [Ntop.cpp:387] Welcome to ntopng x86_64 v.3.6.180823 - (C) 1998-18 ntop.org
25/Aug/2018 13:23:46 [Ntop.cpp:397] Built on Ubuntu 18.04.1 LTS
...
25/Aug/2018 13:23:46 [NetworkInterface.cpp:2506] Started packet polling on interface stdin [id: 45]...
/home/ben/bin/fritzdump: Zeile 39: 10584 Fertig                  wget --no-check-certificate -qO- $FRITZIP/cgi-bin/capture_notimeout?ifaceorminor=$IFACE\&snaplen=\&capture=Start\&sid=$SID
     10585 Speicherzugriffsfehler  (Speicherabzug geschrieben) | ntopng -i -
```

` apport-unpack /var/crash/_usr_bin_ntopng.1000.crash .` reveals:

`StacktraceTop`
```
pcap_get_selectable_fd () from /usr/lib/x86_64-linux-gnu/libpcap.so.0.8
packetPollLoop (ptr=0x5587c3b4a330) at src/PcapInterface.cpp:165
start_thread (arg=0x7faeb07f8700) at pthread_create.c:463
clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

`SegvAnalysis`
```
Segfault happened at: 0x7faef3292fc0 <pcap_get_selectable_fd>:	mov    0x14(%rdi),%eax
PC (0x7faef3292fc0) ok
source "0x14(%rdi)" (0x00000014) not located in a known VMA region (needed readable region)!
destination "%eax" ok
Stack memory exhausted (SP below stack segment)
```

`SegvReason`
```
reading NULL VMA
```

As I'm an absolute novice noob beginner I have absolutely no clue if I did something wrong. Any hints?

**Comment by simonemainardi** [comment]
can you please post the link to the article you've read?

Did you configure https://github.com/ntop/ntopng/blob/dev/tools/fritzdump.sh with proper ip address, password, and interface?

What if you comment https://github.com/ntop/ntopng/blob/1ab11b6e9c8e60f5004a1b16359d3af66edaa29f/tools/fritzdump.sh#L39 and uncomment https://github.com/ntop/ntopng/blob/1ab11b6e9c8e60f5004a1b16359d3af66edaa29f/tools/fritzdump.sh#L37? Does it work with tshark?

**Comment by bentolor** [comment]
> can you please post the link to the article you've read?

The article is in the largest and most popular leading, german print magazine c`t. ntopng is featured in an article series about mobile phone spyware and it gets nearly a whole page with a getting started with ntopng and fritzdump. It is in c't edition 18/2018 on p. 136 ff.

Unfortunately [the article is behind a paywall and is in german](https://www.heise.de/ct/ausgabe/2018-18-Desinfec-t-fuer-die-Netzwerkdiagnose-4132926.html). I can privately mail you a PDF if you are interested.  

> Did you configure https://github.com/ntop/ntopng/blob/dev/tools/fritzdump.sh with proper ip address, password, and interface?

I did miss the interface. After changing it to eno1 i later on realized that it refers to the interfaces of the fritzbox. Therefore changed it to `2-0`.

> Does it work with tshark?

Nope – thsark simply exits.

Obviously something doe not work regarding the authentification:

```
$ cat /tmp/fritz.sid 
0000000000000000
```

Maybe the culprit:

* I kept `FRITZUSER=""` because I have no users created in my router
* My router password contains special characters

**Comment by simonemainardi** [comment]
Correct, very likely the script failed to get an SID.

I think you need a user on your router (I'm sorry I don't have a fritzbox to reproduce here).

Try to create a user and re-exec the script.

You can also try and execute line https://github.com/ntop/ntopng/blob/dev/tools/fritzdump.sh#L30 manually to see if it generate errors.

**Comment by bentolor** [comment]
Duh – turns out it was soley the issue.

Please see MR #1947 which should change the script into a version which should work out-of-the-box for most users using a new format `fritzdump.sh <user> <pass>`

**Comment by simonemainardi** [comment]
thank you for providing the PR, really appreciated!

If you want, you can do extra service to the community by updating this readme with your experience if you don't mind https://github.com/ntop/ntopng/blob/dev/doc/README.fritzbox 

Thank you very much!

**Comment by bentolor** [comment]
@simonemainardi Thanks for the pointer. Created MR #1950 for minor documentation updates
