### ISSUE TITLE
[Question] - Influxdb traffic volume to high

### ISSUE THREAD

**Issue by darox** [ntop/ntopng#1942]
I would like to know, what's the right way, to get correct values when using Influxdb and Grafana. To get the traffic volume in RX, I set up the following query:
`SELECT distinct("bytes_rcvd") FROM "host:traffic" WHERE ("host" = '192.168.1.158') AND $timeFilter GROUP BY time($__interval) fill(null)`

Grafana shows me 1.047 TB which can no be true, in NTOPNG I can see 7.55 GB in this period. 

I hope someone can help me, with this question. Many thanks!

**Comment by lucaderi** [comment]
Bytes are counters and thus you need to tell the DB that it has to make a difference/delta. Please use difference or derivative in your query. This said trust ntopng and not grafana that has no clue what numbers are about as for it they are just numbers with no real meaning

**Comment by darox** [comment]
@lucaderi I was thinking about that. Do you have a guide value  for th drivative, i.e. time value?

**Comment by emanuele-f** [comment]
@darox please look at our influxdb plugin. It contains query examples, e.g.: https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/timeseries/drivers/influxdb.lua#L301
