### ISSUE TITLE
Grafana module - no data accessible (Internal Server Error)

### ISSUE THREAD

**Issue by vazthunder** [ntop/ntopng#1945]
Hello, first of all thanks for your amazing works!
I'm using Ntopng v.3.7.180826 Community, trying to setup Grafana (v5.2.2) dashboard but can't get it done: no metric at all. I tried to inspect the queries and here is the error: 
![ntop](https://user-images.githubusercontent.com/17200025/44629774-f9b20600-a97d-11e8-817d-30430c0372cf.png)
It's a clean install btw, OS: Ubuntu 16.04, grafana datasource is successfully connected, access /lua/modules/grafana/search.lua from browser returns the right JSON it seems:
![json](https://user-images.githubusercontent.com/17200025/44629851-4e09b580-a97f-11e8-82a7-09c9f0562a56.png)
Please take a look.

**Comment by ShagoY** [comment]
Same version but ubuntu 18.04 : 

http://192.168.1.X:3001/lua/modules/grafana/
`{"status":"OK"}`

[Grafana ] Query inspector : 
`xhrStatus:"complete"
request:Object
method:"POST"
url:"api/datasources/proxy/4/search"
data:Object
target:""
withCredentials:undefined
response:Object
error:"Internal Server Error"
response:"<html><head><title>ntop</title></head><body><img src=/img/warning.png> Script &quot;/usr/share/ntopng/scripts/lua/modules/grafana/search.lua&quot; returned an error: <p><H3>/usr/share/ntopng/scripts/lua/modules/http_lint.lua:1359: [LINT] _POST["payload"] = "{"target":""}" parameter error: Validation error</H3></body></html>"
message:"Internal Server Error"`

Just before this installation "vanilla/apk", I tested with docker and it worked like on the tutorial but it is a version 3.4 or 3.5 of Ntopng ...

[Edit] After "roll back", i can confirm.. No problem on ntopng Community Edition v.3.4.180712 (Docker image ntop/ntopng:stable)

[Edit] It's work with "apt-stable" ntopng Enterprise Edition v.3.6.180826

**Comment by vazthunder** [comment]
@ShagoY interesting... in the meantime i'll play with v3.6, thanks!

**Comment by mercedDeveloper** [comment]
v3.6 works for you @vazthunder ?

**Comment by vazthunder** [comment]
@mercedDeveloper yes it does

**Comment by simonemainardi** [comment]
@vazthunder can you confirm you are not getting any error with version 3.6? Are errors only arriving when using 3.7?

**Comment by vazthunder** [comment]
@simonemainardi yes, i switched to stable repo and everything is working like a charm now; can you reproduce the problem with v3.7?

**Comment by boisgada** [comment]
I can confirm grafana was working prior to 3.7.  Turning logging on, ntopng returns 404:

127.0.0.1 - - [03/Sep/2018:07:46:47 -0500] "GET /lua/modules/grafana HTTP/1.1" 404 144 "http://[SERVERNAME REMOVED]:4000/datasources/edit/7" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0"

**Comment by simonemainardi** [comment]
Thanks for reporting. This issue is fixed also in 3.7 now and will be available in the next build, at most in 1 day.

**Comment by vazthunder** [comment]
@simonemainardi thanks! i will update soon
