### ISSUE TITLE
hosts-networks can not show all the networks

### ISSUE THREAD

**Issue by Gavin-yzg** [ntop/ntopng#1946]
when flows is up to about 80000，hosts-networks can not show all the networks

**Comment by Gavin-yzg** [comment]
i was use netflow

**Comment by simonemainardi** [comment]
please, try to provide an explanation with more details. add screenshots if necessary.

**Comment by Gavin-yzg** [comment]
![qq 20180828155124](https://user-images.githubusercontent.com/36434750/44708743-76f28d80-aada-11e8-9751-bbdf389a57c2.jpg)
i have 17 networks

**Comment by Gavin-yzg** [comment]
![1](https://user-images.githubusercontent.com/36434750/44710465-c63abd00-aade-11e8-945b-2868993aa54d.jpg)
![2](https://user-images.githubusercontent.com/36434750/44710480-cc309e00-aade-11e8-9fec-575389d71d7a.jpg)
![3](https://user-images.githubusercontent.com/36434750/44710487-d18de880-aade-11e8-9366-9459dc9e7f25.jpg)
like this

**Comment by Gavin-yzg** [comment]
no  Idle networks

**Comment by simonemainardi** [comment]
idle networks are not shown as already explained in https://github.com/ntop/ntopng/issues/1910#issuecomment-412437060

**Comment by Gavin-yzg** [comment]
this is active  networks  not shown，not Idle networks

**Comment by simonemainardi** [comment]
make sure to tune -X and -x to prevent ntopng from reaching the maximum number of hosts / flows. Then please try to explain with more detail, I am no ture why you've shown only the footer. What are you looking at?

**Comment by Gavin-yzg** [comment]
![1](https://user-images.githubusercontent.com/36434750/44758265-05f8b780-ab66-11e8-9c6a-5bc27d414909.png)
i im look at networks，when flows is low,networks can show all

**Comment by Gavin-yzg** [comment]
![4](https://user-images.githubusercontent.com/36434750/44758588-f0848d00-ab67-11e8-9244-869a22c73225.jpg)
i have change -X and -x ，just the same

**Comment by Gavin-yzg** [comment]
i change to --max-num-flows "200000" --max-num-hosts "50000" Problem solved，i do not know why
