### ISSUE TITLE
how i can receive ntopng logs in /var/log/ntopng

### ISSUE THREAD

**Issue by programmer74SHA** [ntop/ntopng#1948]
like suricata:
{ "id": 185, "timestamp": "11\/29\/2015-13:33:11.623515", "ipver": 4, "srcip": "61.135.169.112", "dstip": "192.168.1.113", "protocol": 6, "sp": 80, "dp": 56938, "http_uri": "\/link?url=UAKVruSvh1nkqhnBwLF0801i_Y9NOWRoM4yX1qYLbVS71__S1UUPOtAhsfpXcHQciC_zIn9YsX-goQfLPgXOeNhqwbAP1PAsLZubZMqeHAe&cb=jQuery110204432665144558996_1448791335548&data_name=recommend_common_merger&ie=utf-8&oe=utf-8&format=json&t=1448791340000&_=1448791335553", "http_host": "lcr.open.baidu.com", "http_referer": "http:\/\/www.baidu.com\/s?ie=utf-8&f=8&rsv_bp=1&tn=57022038_1_hao_pg&wd=filetype%3Apdf%20pdf&oq=pdf&rsv_pq=c3b15c5d00015766&rsv_t=b7c1PsBBo0xLhXf27zgsYRmBhSjPSnj4WkFSKdxZ5dw5VmMiJCkZyspJrt7Y4c9MP26iRvygXRE&rsv_enter=1&rsv_srlang=cn&sl_lang=cn&rsv_rq=cn", "http_user_agent": "Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/46.0.2490.86 Safari\/537.36", "filename": "\/link", "magic": "ASCII text, with no line terminators", "state": "CLOSED", "md5": "160ff86672d721c3d50f7945c7ed34de", "stored": true, "size": 111 }

**Comment by simonemainardi** [comment]
With logs you mean flows. Flows are not sent directly to a log file as that could easily fill the fs. We leave log files to record application logs, not flows.

However, for the flows, you have several options:
- periodically walk the active flows with requests to get_flows_data.lua
- export flows to either MySQL, logstash, elasticsearch
  - https://www.ntop.org/ntopng/filling-the-pipe-exporting-ntopng-flows-to-logstash/
  - https://www.ntop.org/ntopng/exploring-historical-data-using-ntopng-part-2/
  - https://www.ntop.org/ntopng/ntopng-goes-elastic-introducing-elasticsearch-6-support/
- Use ZMQ to receive data from ntopng
  - see option -I https://www.ntop.org/ntopng/creating-a-hierarchical-cluster-of-ntopng-instances/
