### ISSUE TITLE
ERROR: Too many interfaces (47): discarded tcp://127.0.0.1:20010

### ISSUE THREAD

**Issue by boisgada** [ntop/ntopng#1952]
I appear to be running into a limitation on interfaces.  Any advise would be appreciated.

Overview:
One ntopng Enterprise server
20 nProbe embedded sensors
"Pull" configuration

Sensors ssh to server and create a reverse ssh tunnel for communication.  From the server perspective, sensor interfaces are tcp://127.0.0.1:20001 - 20020.

Eacb sensor is at a different location requiring user based access controls so combining multiple sensors in a single interface ("push" configuration) may be difficult.

Please advise

**Comment by simonemainardi** [comment]
You've reached the maximum number of interfaces ntopng has seen among all its executions. 

Can you try and start with a clean instance (that is remove ntopng data dir and execute redis-cli flushall)?

In the meanwhile I will write a fix for this.

**Comment by simonemainardi** [comment]
You can now try and execute the latest ntopng 3.7. That will handle the error described above.

**Comment by boisgada** [comment]
After upgrading and cleaning up the ntopng data dir the interfaces renumbered and I no longer received the error; however the grafana API stopped working.  Not sure if this change or some other change caused the issue.

**Comment by simonemainardi** [comment]
ok, thanks for reporting. Is the grafana issue related to https://github.com/ntop/ntopng/issues/1945 ?

**Comment by boisgada** [comment]
Based on the symptoms reported by others, I suspect it is, but have not attempted to downgrade to 3.6 to verify.  The Grafana datasource configuration appears to expect a 200 when pointing to the /lua/modules/grafana folder.  Perhaps a security enhancement in 3.7 now handle URLs pointing to a folder differently.

**Comment by boisgada** [comment]
When pointing to the index.lua, the datasource adds, but the plugin is configured to prepend the defined datasource path instead of substituting the necessary page. 

Adding Datasource:
127.0.0.1 - - [03/Sep/2018:10:26:18 -0500] "GET /lua/modules/grafana/index.lua HTTP/1.1" -1 0 "http://[SERVERNAME REMOVED]:4000/datasources/edit/7" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0"

Using Datasource:
127.0.0.1 - - [03/Sep/2018:10:29:20 -0500] "POST /lua/modules/grafana/index.lua/query HTTP/1.1" 404 160 "http://[SERVERNAME REMOVED]:4000/d/FM451ktmz/ntfk-overview?orgId=2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0"
