### ISSUE TITLE
change ntop logs format

### ISSUE THREAD

**Issue by programmer74SHA** [ntop/ntopng#1953]
when i use logstash and get output. I have a ntopng.log like this. how i can change indexes.. like: IPV4_SRC_ADDR to srcip.

{"ntop":"true","@metdata":{"ip_address":"127.0.0.1"},"message":"{ \"ntop_timestamp\": \"2018-08-28T06:37:50.0Z\", \"IN_SRC_MAC\": \"00:50:56:AF:4B:06\", \"OUT_DST_MAC\": \"01:00:5E:00:00:FC\", \"IPV4_SRC_ADDR\": \"192.168.3.12\", \"IPV4_DST_ADDR\": \"224.0.0.252\", \"L4_SRC_PORT\": 55311, \"L4_DST_PORT\": 5355, \"PROTOCOL\": 17, \"L7_PROTO\": 154, \"L7_PROTO_NAME\": \"LLMNR\", \"IN_PKTS\": 2, \"IN_BYTES\": 144, \"OUT_PKTS\": 0, \"OUT_BYTES\": 0, \"FIRST_SWITCHED\": 1535438270, \"LAST_SWITCHED\": 1535438270, \"SRC_IP_COUNTRY\": \"\", \"SRC_IP_LOCATION\": [ 0.000000, 0.000000 ], \"DST_IP_COUNTRY\": \"\", \"DST_IP_LOCATION\": [ 0.000000, 0.000000 ], \"NTOPNG_INSTANCE_NAME\": \"apk-siem246\", \"INTERFACE\": \"eth0\" }","port":44958,"@timestamp":"2018-08-28T06:38:52.096Z","host":"localhost"}

**Comment by programmer74SHA** [comment]
{"ntop":"true","@metdata":{"ip_address":"127.0.0.1"},"message":"{ \"ntop_timestamp\": \"2018-08-28T06:37:50.0Z\", \"IN_SRC_MAC\": \"00:50:56:AF:4B:06\", \"OUT_DST_MAC\": \"01:00:5E:00:00:FC\", \"IPV4_SRC_ADDR\": \"192.168.3.12\", \"IPV4_DST_ADDR\": \"224.0.0.252\", \"L4_SRC_PORT\": 55311, \"L4_DST_PORT\": 5355, \"PROTOCOL\": 17, \"L7_PROTO\": 154, \"L7_PROTO_NAME\": \"LLMNR\", \"IN_PKTS\": 2, \"IN_BYTES\": 144, \"OUT_PKTS\": 0, \"OUT_BYTES\": 0, \"FIRST_SWITCHED\": 1535438270, \"LAST_SWITCHED\": 1535438270, \"SRC_IP_COUNTRY\": \"\", \"SRC_IP_LOCATION\": [ 0.000000, 0.000000 ], \"DST_IP_COUNTRY\": \"\", \"DST_IP_LOCATION\": [ 0.000000, 0.000000 ], \"NTOPNG_INSTANCE_NAME\": \"apk-siem246\", \"INTERFACE\": \"eth0\" }","port":44958,"@timestamp":"2018-08-28T06:38:52.096Z","host":"localhost"}

how i can change ntop json fileds logs ... like: IPV4_SRC_ADDR to srcip

**Comment by simonemainardi** [comment]
you just have to use a mutate filter, for example

```
filter {
  mutate {
    # Renames the 'IPV4_SRC_ADDR' field to 'srcip'
    rename => { "IPV4_SRC_ADDR" => "srcip" }
  }
}
```
 
Documentation https://www.elastic.co/guide/en/logstash/current/plugins-filters-mutate.html
