### ISSUE TITLE
nDPI 

### ISSUE THREAD

**Issue by waqar-ali-aziz** [ntop/ntopng#1955]
i am currently working on Deep Packet Inspection and use nDPI tool for this purpose. after installing nDPI i want to inspect the internet traffic but don't know how to use nDPI. can someone tell me how to inspect packet using nDPI tool ?

**Comment by simonemainardi** [comment]
nDPI is automatically and transparently used by ntopng when capturing packets. So you don't have to do anything special apart from running ntopng.

Check this resource for a comprehensive introduction: https://www.ntop.org/nprobe/network-monitoring-101-a-beginners-guide-to-understanding-ntop-tools/

**Comment by waqar-ali-aziz** [comment]
Thank you simonemainardi  for commenting here. 
so you mean to say i have to install nTOP along with nDPI and nDPI alone will not work ?
Am i right?

**Comment by simonemainardi** [comment]
you just have to install ntopng. nDPI shipped with ntopng automatically. See http://packages.ntop.org/ for installation instructions.
