### ISSUE TITLE
ntopng not listing original flow sources

### ISSUE THREAD

**Issue by dagbdagb** [ntop/ntopng#1956]
[netflow-v9.pcap.gz](https://github.com/ntop/ntopng/files/2327623/netflow-v9.pcap.gz)

![ntopng-flowexporters](https://user-images.githubusercontent.com/8895912/44717992-ec506500-aabe-11e8-8657-4a7a97938768.png)

See attachments.
Using nprobe.x86_64 0:8.5.180828-6253  & ntopng.x86_64 0:3.7.180828-4692

nprobe -i none -n none     --zmq tcp://*:1234 --zmq-encrypt-pwd myencryptionkey     -V 9     -3 2055     --as-list /root/GeoIPASNum.dat     --city-list /root/GeoLiteCity.dat     --local-networks 10.120.0.0/13,10.240.0.0/13     -S @1:10:1 

ntopng -i tcp://localhost:1234 --zmq-encrypt-pwd myencryptionkey --local-networks 10.120.0.0/13,10.240.0.0/13

I am running both processes on 10.120.1.245, my netflow source is 10.121.255.34.

I would expect to see the original netflow source in the ntopng GUI. I do not. Why not?

**Comment by dagbdagb** [comment]
I realise this is a licensed feature. I do not have a license. Trying to showcase this feature during the first 10 minutes of starting nprobe/ntopng.

**Comment by cardigliano** [comment]
@dagbdagb we pushed a fix for this, a new package will be available in <1h from now. Please let us know if it works for you. Thank you.

**Comment by dagbdagb** [comment]
Cool. thanks.

**Comment by emanuele-f** [comment]
@dagbdagb any news?

**Comment by dagbdagb** [comment]
Not at the moment.The guy assigning tasks to me also prioritize my tasks, and netflow got demoted for now. Sorry.

**Comment by simonemainardi** [comment]
ok, thanks for reporting. Closing as @cardigliano reproduced and pushed the fix. Kindly provide feedback in the future in case you'll reconsider using netflow.
