### ISSUE TITLE
NTOPNG  Enterprise becomes Community version after upgrade from 3.2.x to 3.6.x

### ISSUE THREAD

**Issue by pmarissen** [ntop/ntopng#1958]
Dear, 

I have a running ntopng 3.2 enterprise installation. I have done a upgrade to ntopng 3.6 and now I have lost may Enterprise version, the installation downgraded to the Community version. 

Please advise

Best regards

Paul

**Comment by simonemainardi** [comment]
when did you generate  your license? Check this: https://www.ntop.org/support/faq/are-licenses-permanent-what-about-maintenance/ maybe your license is just expired

**Comment by pmarissen** [comment]
I have generated the license beginning december 2017.

**Comment by simonemainardi** [comment]
please, contact me privately at mainardi ntop org

send me the order id along with the output of ntopng --version
