### ISSUE TITLE
"error":"Request Entity Too Large"

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#1959]
Hi to all,
I've just installed the new ntopng stable version (3.6.180823). After run the software with this options
```
--verbose 2
--pid /var/tmp/ntopng.pid
--data-dir /var/data/ntopng/
--http-port 3000
--redis 127.0.0.1:6379
--disable-autologout
--disable-login 1
--dns-mode 3
--max-num-flows 524288
--max-num-hosts 262144
--dump-hosts none
--sticky-hosts none
--interface zc:2@0
--interface zc:2@1
--interface zc:2@2 
--interface zc:2@3
--interface zc:2@4
--interface zc:2@5
--interface zc:2@6
--interface zc:2@7
--interface zc:2@8
--core-affinity 10,11,12,12,13,13,14,15,15
--capture-direction 1
--packet-filter "not (udp and src host 0.0.0.0 and dst port 8116) and not (net 10.0.0.0/8)"
--local-networks "X.X.X.X/18,X.X.X.X/19,X.X.X.X/21,X.X.X.X0/20,X.X.X.X/21,X.X.X.X/25,X.X.X.X/24,X.X.X.X/24,X.X.X.X/24,X.X.X.X/23,X.X.X.X/23,192.168.0.0/16,172.16.0.0/12"
```
and after enabling the influxdb timeseries I have a lot of
```
{"error":"Request Entity Too Large"}
{"error":"Request Entity Too Large"}
{"error":"Request Entity Too Large"}                                    
{"error":"Request Entity Too Large"}
{"error":"Request Entity Too Large"}
```
errors.

I think that something is not working as expected...

What do you think?

Bye bye,
   Gianluca

**Comment by simonemainardi** [comment]
can you try and increase/disable influxdb "max-body-size" ?

see https://github.com/influxdata/docs.influxdata.com/blob/master/content/influxdb/v1.3/administration/config.md#max-body-size--25000000

please report

**Comment by gianogli** [comment]
One hour ago I changed the value from 25000000 to 50000000 and the error messages are disappeared. Thanks!

**Comment by simonemainardi** [comment]
Thank you for reporting. If you want you can provide service to the community by taking some time to update this readme https://github.com/ntop/ntopng/blob/dev/doc/README.influxdb with your experience and this issue.

**Comment by gianogli** [comment]
Ok. This could be the new file:

```

Introduction
------------
This readme explains how to integrate ntopng with http://influxdb.org time series database.
Influx is populated by ntopng periodically pushing data into it, using the TimeSeriesExporter class.

*** NOTE: ntopng requires influxdb features only available in the latest versions 1.5.x and up . ***
Please install influxdb from the official packages `https://portal.influxdata.com/downloads`.

Installation and configuration (Ubuntu)
---------------------------------------

1. create the file "/etc/apt/sources.list.d/influxdb.list" and add the official InfluxDB repository
    deb https://repos.influxdata.com/ubuntu/ xenial stable
2. install the latest version of influxdb package
    apt-get install influxdb
3. configure InfluxDB by modifying the file "/etc/default/influxdb" as described here:
    https://docs.influxdata.com/influxdb/v1.6/administration/config/

This is a little example of a configuration file:

************************
INFLUXDB_REPORTING_DISABLED=true
INFLUXDB_META_DIR="/var/data/influxdb/meta"
INFLUXDB_DATA_DIR="/var/data/influxdb/data"
INFLUXDB_DATA_WAL_DIR="/var/data/influxdb/wal"
INFLUXDB_HTTP_BIND_ADDRESS="127.0.0.1:8086"
INFLUXDB_IFQL_BIND_ADDRESS="127.0.0.1:8082"
INFLUXDB_HTTP_MAX_BODY_SIZE=50000000
************************

Increase the value of the "INFLUXDB_HTTP_MAX_BODY_SIZE" parameter (set by default at 25000000) could be
useful to solve an issue related to the "{"error":"Request Entity Too Large"}" error messages.
For more information go to https://github.com/ntop/ntopng/issues/1959

Ntopng configuration
--------------------

By default Influx data export is disabled. You can enabled as follows:

1. from the ntopng Timeseries preferences, select "InfluxDB" as the Timeseries Database
2. set the `InfluxDB URL` to point to the database: http://<host where Influx is running>:8086"
3. click save

and then ntopng will push data to Influx.

At this point ntop will use InfluxDB (and not RRD) to store timeseries. As you have exported data onto InfluxDB
you can also use Chronograf or Grafana to access your traffic metrics produced by ntopng.

Authentication
--------------

ntopng supports influxdb authentication.
A new privileged user can be created via the influxdb command line:

`CREATE USER admin WITH PASSWORD 'mysecret' WITH ALL PRIVILEGES`
```

I attached the patch file with the lines I've add.
[influxdb_installation_and_configuration.txt](https://github.com/ntop/ntopng/files/2339270/influxdb_installation_and_configuration.txt)

Is it ok?

**Comment by simonemainardi** [comment]
@emanuele-f, please, see if this error can be handled automatically by ntopng (for example by automatically changing the `max-body-size`) of if a more meaningful, actionable, error can be given to the user. Please, also update the documentation with the contribution of @gianogli .

**Comment by emanuele-f** [comment]
This should be already handled by the current dev version (https://github.com/ntop/ntopng/commit/0004e081910d8e9bcc468e7b2af509ca40ad7a5b#diff-9a614d8bda70321c89af50f290e76aa5R114).

@gianogli I'll backport the fix to stable and kindly tell you to test it

**Comment by emanuele-f** [comment]
@gianogli here is the backport 064e7f828c59155e23a790642fc5ceeb44b90cce . The new available stable package contains the fix. Can you please restore the original max-body-size and test if the fix works for you?

**Comment by lucaderi** [comment]
Closed for inactivity. Will reopen if necessary

**Comment by gianogli** [comment]
I've tested ntopng version 3.6.180906 (with the backport) for 5 days by using the standard InfluxDB configuration (without change the INFLUXDB_HTTP_MAX_BODY_SIZE parameter) and I can confirm to you that all works fine.
The `"error":"Request Entity Too Large"` messages are desappeared!
Thanks... ;-)

**Comment by simonemainardi** [comment]
thank you for reporting
