### ISSUE TITLE
ntopng dumping only a few flows to elasticsearch

### ISSUE THREAD

**Issue by kthkaya** [ntop/ntopng#196]
Hello,

flow_status.lua shows 3-4k flows in ntopng interface

Active flows show no results found in ntopng gui

05/Oct/2015 04:40:29	WARNING: JSON Parse error: Unknown
05/Oct/2015 04:40:29	WARNING: JSON Parse error: Unknown
05/Oct/2015 04:40:29	WARNING: JSON Parse error: Unknown
05/Oct/2015 04:40:29	WARNING: JSON Parse error: Unknown

nprobe
-n=none
-i=none
-t=120
-d=60
-a=0
-e=1
-B=10
-w=128000
-z=0
-S=1:1
-E=0:0
-g=/var/run/nprobe-none.pid
-3=2056
--zmq=tcp://*:5556
--vlanid-as-iface-idx=none
-T=%IN_BYTES %IN_PKTS %IPV4_SRC_ADDR %IPV4_DST_ADDR %SRC_AS %DST_AS %OUT_BYTES %OUT_PKTS %SAMPLED_PACKET_SIZE %EXPORTER_IPV4_ADDRESS %PACKETS_OBSERVED %L7_PROTO %L7_PROTO_NAME
-V=10
--dump-stats=/var/log/nprobe/none-0_flows_stats.txt

root@nTop:/etc/ntopng# cat ntopng.conf
-w=3000
-W=0
-m="192.168.0.0/24"
-F=es;flows;ntopng-%Y.%m.%d;http://localhost:9200/_bulk;
-d=/storage/ntopng
-G=/var/tmp/ntopng.pid
-i=tcp://127.0.0.1:5556

flexible netflow record

flow record Test
 description test
 match ipv4 total-length
 match ipv4 source address
 collect routing source as
 collect routing destination as
 collect routing next-hop address ipv4 bgp
 collect ipv4 protocol
 collect flow direction
 collect counter bytes
 collect counter packets
 collect application name
!

exporter

flow exporter test
 destination x.x.x.x
 transport udp 2056
 export-protocol ipfix
!

Kibana shows only 3-4 flows in each 15 minutes. I am expecting all flows to expire in 120 secs and be dumped.

Following is a sample dump

October 5th 2015, 04:46:17.000	@timestamp:October 5th 2015, 04:46:17.000 type:flows IPV4_SRC_ADDR:173.245.58.109 L4_SRC_PORT:0 IPV4_DST_ADDR:0.0.0.0 L4_DST_PORT:0 PROTOCOL:0 IN_PKTS:3 IN_BYTES:348 OUT_PKTS:0 OUT_BYTES:0 FIRST_SWITCHED:0 LAST_SWITCHED:0 json.16:0 json.17:0 json.42:139564 json.130:38.104.154.122 json.57591:Unknown _id:AVA15HwQ_hgSpdVeYUNo _type:flows _index:ntopng-2015.10.05

Any help appreciated

**Comment by kthkaya** [comment]
While playing around, I clicked yearly flow views in kibana and all flows were there. That worked because for some weird reason, ntopng is dumping with old time stamps (to be precise, 28th of august) even though system time is correct

**Comment by lmangani** [comment]
Probably unrelated, but we have recently changed the position of @timestamp field in NTOPNG ES flows, are you using the latest version?

**Comment by kthkaya** [comment]
Thanks for the response Imangani,
Yes I am using the latest version. Following is the elasticsearch config
ntopng-%Y.%m.%d
It is VERY weird that among 150K entries, only a couple of them are reported as 5th of October. Rest are 28th of August.

**Comment by kthkaya** [comment]
full config 
ntopng -F “es;flows;ntopng-%Y.%m.%d;http://XYZ:9200/_bulk;”
