### ISSUE TITLE
Traffic Timeseries - Wrong data (and/or unit)

### ISSUE THREAD

**Issue by vazthunder** [ntop/ntopng#1960]
Hello, i'm using NtopNG v v.3.7.180829 (package) Community on Ubuntu 16.04, packet capture mode, traffic throughput usually spikes around 300Mbps~1Gbps, traffic timeseries as below:

![abc](https://user-images.githubusercontent.com/17200025/44772866-3a399b80-ab99-11e8-9bfc-6535cd8ed0f5.png)

the only stat that makes sense is Avg, the rest seems wrong mostly, bytes/bits unit is confusing too.
Please take a look!

**Comment by vazthunder** [comment]
btw, i've tried with v3.6 stable, same problem

**Comment by lucaderi** [comment]
Are you using RRD or InfluxDB? Did you check if you have packet drops?

**Comment by vazthunder** [comment]
@lucaderi i've tried both engines and got the same results, with just about 0.02% packets dropped.
Update: 10 mins of Pro trial returned more accurate graphs with similar shape, different Y-axis unit.

**Comment by cardigliano** [comment]
Fixed in 4d6bcb4ae2d0368c13ec39b07444177a086c9675, @emanuele-f please review it.

**Comment by vazthunder** [comment]
@cardigliano it works, thanks!

**Comment by emanuele-f** [comment]
@cardigliano there was a little bug: 4b136b6125d95acc9caac1db0302486e63f6d473 . Please remember to cherry-pick on stable the fixes!
