### ISSUE TITLE
nDPI install issue

### ISSUE THREAD

**Issue by programmer74SHA** [ntop/ntopng#1961]
when i run make to install nDPI i get error:

ln -Fs libndpi.so.2.5.0 libndpi.so
ln: failed to create symbolic link 'libndpi.so': File exists
Makefile:35: recipe for target 'libndpi.so.2.5.0' failed
make[1]: *** [libndpi.so.2.5.0] Error 1
make[1]: Leaving directory '/root/nDPI/src/lib'
Makefile:405: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by simonemainardi** [comment]
nDPI build instructions can be found at https://github.com/ntop/nDPI

nDPI issue tracker is https://github.com/ntop/nDPI/issues
