### ISSUE TITLE
ntopng

### ISSUE THREAD

**Issue by waqar-ali-aziz** [ntop/ntopng#1962]
after entering ntopng -h command it is not showing nDPI detected protocol
![capture](https://user-images.githubusercontent.com/41417514/44785199-87be0480-aba9-11e8-9d6d-26ae8ec8281f.PNG)

**Comment by simonemainardi** [comment]
please, try go go through the documentation before posting issues:

https://www.ntop.org/guides/ntopng/

We also have a youtube channel with guides and tutorial:

https://www.youtube.com/channel/UCUYWuYlYKD5Yq5qBz0AIXJw
