### ISSUE TITLE
Replace Google Maps with OpenLayers

### ISSUE THREAD

**Issue by sm1000** [ntop/ntopng#1963]
Is it possible the developer to review the idea of replacing the **Google Maps** with [**OpenLayers**](http://openlayers.org/). I am using **OpenLayers** already into a different project (MediaWIKI Maps plugin) and it looks very stable.

The main reason for this request is that Google collects credit card information from every one who wants to generate a Google MAPS API key :(

Please consider this request as an enhancement.

Thank you.

**Comment by sm1000** [comment]
Another option is  [**Leaflet**](https://leafletjs.com/).

**Comment by simonemainardi** [comment]
would you be interested in leading this development with our guidance?

**Comment by sm1000** [comment]
Unfortunately, my programming skills with PHP are basic :(

**Comment by simonemainardi** [comment]
Ok, thanks for pointing this out. I am putting this on hold as we can't accomodate the request now. Depending on the interest of other users, we may re-consider adding this to the roadmap.
