### ISSUE TITLE
How to have ntopng.service wait until system time is in sync before starting

### ISSUE THREAD

**Issue by vidgizmo** [ntop/ntopng#1965]
Within a few seconds of a system restart, my ntopng interface shows an uptime of 200+ days. My system (Odroid C2) does not have a battery-backed clock and depends on ntpd sync to get the system time correct. 

I have tried few modifications to my /etc/systemd/system/ntopng.service file in an attempt to get it to hold off until the system time is in sync including adding:
- After=time-sync.target ...
- Requires=time-sync.target

In case it matters, I am running Ubuntu 18.04.

Any suggestions?

**Comment by emanuele-f** [comment]
Hi, I think this is the correct way to solve the issue. Does it works for you? Anyway I think we cannot implement this into the official ntopng service, as this is specific of your system. Maybe you can create a wrapper service which requires the stock ntopng.service and the time-sync target

**Comment by simonemainardi** [comment]
@vidgizmo so does your solution work? did you run systemctl daemon-reload to make sure changes to the service  file have been read?

**Comment by vidgizmo** [comment]
No, it doesn't seem to make a difference :( 

Here is my current ntopng.service file:

root@odroid:~# cat /etc/systemd/system/ntopng.service
[Unit]
Description=ntopng high-speed web-based traffic monitoring and analysis tool
After=time-sync.target network.target syslog.target redis.service pf_ring.service cluster.service mysql.service
Requires=time-sync.target
Wants=pf_ring.service cluster.service
PartOf=pf_ring.service cluster.service

[Service]
Type=simple

ExecStartPre=/bin/sh -c '/bin/echo "$(/bin/date) ntopng StartPre" >> /var/log/ntop-systemd.log'
ExecStartPre=/bin/sh -c '/usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true'
ExecStartPre=/bin/sh -c '/bin/sed "/^[ ]*-e.*$\\|^[ ]*-G.*\\|^[ ]*--daemon.*\\|^[ ]*--pid.*/s/^/#/" /etc/ntopng/ntopng.conf > /run/ntopng.conf'

ExecStart=/usr/local/bin/ntopng /run/ntopng.conf

ExecStartPost=/bin/sh -c '/bin/echo "$(/bin/date) ntopng StartPost" >> /var/log/ntop-systemd.log'
ExecStopPost=-/bin/rm -rf /run/ntopng.conf
ExecStopPost=/bin/sh -c '/bin/echo "$(/bin/date) ntopng StopPost" >> /var/log/ntop-systemd.log'

Restart=on-abnormal
RestartSec=5

[Install]
WantedBy=multi-user.target
Alias=

**Comment by lucaderi** [comment]
I think this is not an issue of our packaging. Please investigate it yourself see how other packages are doing, and send us a pull request
