### ISSUE TITLE
Invalid flow aggregation begin/end date

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1967]
Aggregated flows have invalid aggregation dates. In particular the begin data is the min of the aggregated flows and this is wrong as if a flow started X days ago, the begin date is set to X. It is requested to set the begin date according to flow aggregation and in no case both begin/end dates must fall outside of the aggregation period.

**Comment by simonemainardi** [comment]
After internal review we've decided to leave begin/end dates untouched to:

- preserve what could have been sent from a remote exporter (e.g., netflow via ZMQ)
- make sure queries on the aggregated flows tables have times that are compatible to those in the raw flow tables

we may change this behavior in the future when reworking the historical data explorer but for now I am putting this issue on hold.
