### ISSUE TITLE
Poor ZMQ/nProbe-ntopng documentation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1968]
The documentation about
- how to export data from nProbe to ntopng using ZMQ
- the use of the @NTOPNG@ macro
- the use of ZMQ in pull/push mode
- how to configure ZMQ/nprobe/ntopng via the nBox GUI

is sparse and split across multiple blog posts end documents.

It is requested to
- update the ntopng and nProbe documentation adding clear and simple examples
- write a blog post that summarises all this

**Comment by simonemainardi** [comment]
- new doc with examples is available in rst format https://github.com/ntop/ntopng/commit/4f8af96e906d544c1d6ca883410cbe20cbd0db42 and will be published at https://www.ntop.org/support/documentation/documentation/ in a few hours
- old, outdated doc removed from nprobe. A link pointing to the new doc has been added there.
- blog post ready to be published
