### ISSUE TITLE
Implement diagnostic page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1969]
Many simple misconfigurations are easy to solve if a diagnostic page is implemented. The page should be able to
- list relevant configuration issues (e.g. /var/lib/ntopng pointing to a volume with little space available)
- report misconfigurations (e.g. low -X/-x values)
- report non-optimal CPU affinity configuration
- check if DNS is resolving addresses
...

In nEdge it should also (at least)
- detect if network interfaces are working correctly (e.g. we can ping the gateway from the correct interface)
- detect if interface are swapped (e.g. LAN vs WAN)
- Internet connectivity is available
...

Users could use the diagnostic page to fix themselves simple issues without having to ask for support.

**Comment by simonemainardi** [comment]
This has now been implemented using UI toasts. Toasts show relevant issues, are dismissable / not dismissable depending on the severity, and contain an action button for the solution of the misconfiguration.
