### ISSUE TITLE
Cleaning up runtimeprefs.json

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1971]
The runtimeprefs.json overtime accumulates outdated information (a.k.a junk) that takes us space and is never purged. For instance if you start once ntopng on ethX and you will never ever start it on such interface, all the ethX prefs will be kept forever. This preference information is also  kept in redis (that mostly lives in memory) and thus takes space.

As add-on to #1914 it is required to add the ability to remove from both redis and runtimeprefs.json, preferences that are lot currently used and thus that will reduce resources usage.

**Comment by simonemainardi** [comment]
Implemented

![image](https://user-images.githubusercontent.com/3397663/45222961-36eb9180-b2b6-11e8-8d78-41b64122fb58.png)

all the persistent data and redis/runtime preferences can now be cleared from the manage data page.
