### ISSUE TITLE
Discard default/empty values

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1972]
As follow-up to #1971 it is requested to discard (or better not to write at all) default or empty values in preferences. For instance I see many 

$ redis-cli get "ntopng.prefs.device_types.5C:49:79:75:4E:6A"
""

These values are useless as they take up space, but do not add anything and inflate the runtime prefs. 

Furthermore there are many entries with double dots .. Such as

$ redis-cli get ntopng.prefs.user..type_log
""

This behaviour must be fixed.

**Comment by simonemainardi** [comment]
implemented in:

- https://github.com/ntop/ntopng/commit/87f8bece2275672268b42940eba86fcf3a002551
- https://github.com/ntop/ntopng/commit/d10a88d73996c11fcb206926b1a3cba33b2a0ba9
- https://github.com/ntop/ntopng/commit/f68e907dc10835224c24fe98dbbee1fe5ff30867
