### ISSUE TITLE
Invalid syslog format

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1973]
When dumping to syslog (via traceEvent) the format is invalid even though it is rendering well in the user interface. A typical entry is the following 

`Sep  3 08:49:48 test-desktop ntopng: [Alert] Flow blocked: <A HREF='/lua/host_details.lua?host=@0&ifid=4&page=alerts'>192.168.2.4</A> &gt; <A HREF='/lua/host_details.lua?host=@0&ifid=4&page=alerts'>224.0.0.251</A> [info: ]`

As you can see the are a few issues
- @0 in host= with no host name (note that @0 could be omitted as it is VLAN 0)
- info: is empty
- useless HTML tags that make output unreadable and un-parsable by automatic tools

It is requested to strip out the HTML tags from logging and have all fields populated properly.

**Comment by marcoeg** [comment]
It would preferable that the syslog message be without HTML tags.

**Comment by simonemainardi** [comment]
syslog support has been reworked according to the comments as a new lua alert endpoint:

![image](https://user-images.githubusercontent.com/3397663/45095884-79c73100-b11f-11e8-855a-ac10168d387b.png)

syslog messages (with proper syslog severity populated as per https://github.com/ntop/ntopng/issues/1954) are now clean and augmented with entity information, type of error, and the plaintext message.

```
Sep  5 15:13:23 devel ntopng: [05/09/2018 13:37:01][Error][Threshold Cross][Host][192.168.2.222][Engaged] Minute traffic crossed by host devel [15.92 MB > 1 Byte]
Sep  5 15:13:23 devel ntopng: [05/09/2018 13:29:01][Error][Threshold Cross][Interface][iface_0][Engaged] Minute traffic crossed by interface eno1 [884.15 KB > 1 Byte]
Sep  5 15:13:23 devel ntopng: [05/09/2018 15:08:00][Error][Threshold Cross][Network][192.168.2.0/24][Engaged] Minute egress traffic crossed by network 192.168.2.0/24 [2.48 KB > 1 Byte]
Sep  5 15:13:23 devel ntopng: [05/09/2018 15:07:00][Error][Threshold Cross][Network][192.168.2.0/24][Released] Minute egress traffic crossed by network 192.168.2.0/24 [3.97 KB > 1 Byte]
Sep  5 15:13:23 devel ntopng: [05/09/2018 15:02:00][Error][Threshold Cross][Network][192.168.2.0/24][Engaged] Minute egress traffic crossed by network 192.168.2.0/24 [3.97 KB > 1 Byte]
Sep  5 15:13:23 devel ntopng: [05/09/2018 13:56:00][Error][Threshold Cross][Network][192.168.2.0/24][Engaged] Minute egress traffic crossed by network 192.168.2.0/24 [2.66 KB > 1 Byte]
Sep  5 15:13:23 devel ntopng: [05/09/2018 13:55:00][Error][Threshold Cross][Network][192.168.2.0/24][Released] Minute egress traffic crossed by network 192.168.2.0/24 [4.16 KB > 1 Byte]
Sep  5 15:13:23 devel ntopng: [05/09/2018 13:50:00][Error][Threshold Cross][Network][192.168.2.0/24][Engaged] Minute egress traffic crossed by network 192.168.2.0/24 [4.16 KB > 1 Byte]
Sep  5 15:13:23 devel ntopng: [05/09/2018 13:49:00][Error][Threshold Cross][Network][192.168.2.0/24][Released] Minute egress traffic crossed by network 192.168.2.0/24 [1.68 KB > 1 Byte]
Sep  5 15:13:23 devel ntopng: [05/09/2018 13:46:00][Error][Threshold Cross][Network][192.168.2.0/24][Engaged] Minute egress traffic crossed by network 192.168.2.0/24 [1.68 KB > 1 Byte]
Sep  5 15:13:23 devel ntopng: [05/09/2018 13:45:00][Error][Threshold Cross][Network][192.168.2.0/24][Released] Minute egress traffic crossed by network 192.168.2.0/24 [492 Bytes > 1 Byte]
Sep  5 15:13:23 devel ntopng: [05/09/2018 13:37:01][Error][Threshold Cross][Network][192.168.2.0/24][Engaged] Minute egress traffic crossed by network 192.168.2.0/24 [492 Bytes > 1 Byte]
Sep  5 15:13:23 devel ntopng: [05/09/2018 14:10:44][Warning][Remote to Remote Flow][Flow] Remote client and remote server [Flow: 192.168.1.100:138 192.168.1.255:138] [L4 Protocol: UDP]
Sep  5 15:13:23 devel ntopng: [05/09/2018 14:00:14][Warning][Remote to Remote Flow][Flow] Remote client and remote server [Flow: 192.168.1.100:138 192.168.1.255:138] [L4 Protocol: UDP]
Sep  5 15:13:23 devel ntopng: [05/09/2018 13:58:44][Warning][Remote to Remote Flow][Flow] Remote client and remote server [Flow: 192.168.1.100:138 192.168.1.255:138] [L4 Protocol: UDP]
Sep  5 15:13:23 devel ntopng: [05/09/2018 13:46:44][Warning][Remote to Remote Flow][Flow] Remote client and remote server [Flow: 192.168.1.100:138 192.168.1.255:138] [L4 Protocol: UDP]
Sep  5 15:13:23 devel ntopng: [05/09/2018 13:45:14][Warning][Remote to Remote Flow][Flow] Remote client and remote server [Flow: 192.168.1.100:138 192.168.1.255:138] [L4 Protocol: UDP]
Sep  5 15:13:23 devel ntopng: [05/09/2018 13:34:44][Warning][Remote to Remote Flow][Flow] Remote client and remote server [Flow: 192.168.1.100:138 192.168.1.255:138] [L4 Protocol: UDP]
Sep  5 15:13:23 devel ntopng: [05/09/2018 13:30:14][Warning][Remote to Remote Flow][Flow] Remote client and remote server [Flow: 192.168.1.100:138 192.168.1.255:138] [L4 Protocol: UDP]
```

**Comment by marcoeg** [comment]
Perfect!  Please post a list of possible Warning and Error messages (previously known as Alert) and their meaning in English (no source code please).

**Comment by simonemainardi** [comment]
documentation has been updated in https://github.com/ntop/ntopng/commit/81a4ec9903cf4b765943a9dc08a6e8f2dcd1257f and will be soon available as HTML at https://www.ntop.org/support/documentation/documentation/.

If you think there's something that needs to be extended please let us know.

**Comment by lucaderi** [comment]
@simonemainardi Some comments

- Why have you added an alert time if the syslog time is already present, and (even more important) why are they out of sync? Example
Sep  5 15:13:23 devel ntopng: [05/09/2018 13:30:14][Warning][Remote to Remote Flow][Flow] Remote client and remote server [Flow: 192.168.1.100:138 192.168.1.255:138] [L4 Protocol: UDP]

- Alert level should be in the entry and not in the text. In other words #1954 is compulsory.

- The alert format is un-parsableby an automatic tool,  and good only for humans, not for being exported to a remote end (e.g. via log stash or log collectors). I suggest you to add the ability to specify the syslog format in text or JSON format.

- The documentation at https://www.ntop.org/guides/ntopng/web_gui/alerts.html?highlight=alerts is a stub. You should list all possible values for all the fields in user (not developer) readable format. Adding a link to https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/alert_consts.lua makes this even worse for the user.

**Comment by marcoeg** [comment]
With respect to having the log processed by a remote machine, as long as there is a way to identify and to separate the standard syslog fields, remote servers (logstash or similar) ingest logs and take care of transforming the entries in JSON. Unless needed for other use, a JSON format is not strictly needed for remote log processing.

**Comment by simonemainardi** [comment]
@lucaderi 

> Why have you added an alert time if the syslog time is already present, and (even more important) why are they out of sync? Example
> Sep 5 15:13:23 devel ntopng: [05/09/2018 13:30:14][Warning][Remote to Remote Flow][Flow] Remote client and remote server [Flow: 192.168.1.100:138 192.168.1.255:138] [L4 Protocol: UDP]
> 

ntopng puts generated alerts into a queue. Alerts in the queue are dequeued periodically and are not immediately sent to syslog. So they wait some time in the queue and hence the syslog time is different from the actual time at ntopng. This is why I've preserved the original ntopng time.

> Alert level should be in the entry and not in the text. In other words #1954 is compulsory.

#1954 is implemented as well and the alert level is used in the `syslog` call

> The alert format is un-parsableby an automatic tool, and good only for humans, not for being exported to a remote end (e.g. via log stash or log collectors). I suggest you to add the ability to specify the syslog format in text or JSON format.

ok

> The documentation at https://www.ntop.org/guides/ntopng/web_gui/alerts.html?highlight=alerts is a stub. You should list all possible values for all the fields in user (not developer) readable format. Adding a link to https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/alert_consts.lua makes this even worse for the user.

will extend that

**Comment by lucaderi** [comment]
@simonemainardi Some notes
- time: a syslog event almost two hours old with respect to the actual time is kinda useless. Some seconds in queue is ok, more is not
- alert level after #1954 should be removed from the text as is the syslog config that will handle that. This said #1954 is still open as of now.

**Comment by simonemainardi** [comment]
>time: a syslog event almost two hours old with respect to the actual time is kinda useless. Some seconds in queue is ok, more is not

I can confirm alerts say in the queue for a bunch of seconds at most -3 seconds at most, actually. I am sorry I pasted a sample output in my comment that could have caused confusion. That is just an output I've obtained during the development by reprocessing old alerts. This is why timestamps look unreasonable. Timestamps are OK in a production installation.

> alert level after #1954 should be removed from the text as is the syslog config that will handle that. This said #1954 is still open as of now.

There's a reason why I didn't remove the severity from the alert text. In the traditional syslog, severity is only part of the syslog message and is not written to disk. Therefore, plain syslog files (e.g., /var/log/syslog) don't carry the severity and there would be no way for an user to determine the severity of an alert by reading such files. There are other newer / more complex alternatives (e.g., rsyslog) that could handle the severity but I believe it is important to be conservative here.

**Comment by simonemainardi** [comment]
syslog JSON support has been added

![image](https://user-images.githubusercontent.com/3397663/45172006-3b577200-b204-11e8-9e4f-50d08e1c2a59.png)


Extensive alerts documentation has been added in 

- https://github.com/ntop/ntopng/commit/603bc2d31c60ea1a8ba12132b4be64c0f654b00f
- https://github.com/ntop/ntopng/commit/be92cc1b1a0eaf4fa94b0ba447fffc231993033f

Documentation will be published in HTML in one day.

Please, let me know if this issue can be closed or if there's something else that needs to be handled.

**Comment by simonemainardi** [comment]
@marcoeg 

please check out the new documentation:
- A description of how alerts work in ntopng: https://www.ntop.org/guides/ntopng/basic_concepts/alerts.html
- The format output to syslog https://www.ntop.org/guides/ntopng/web_gui/alerts.html#alert-endopints

Let me know if there's anything else that needs to be handled to consider this issue as resolved.

**Comment by simonemainardi** [comment]
Implementation and documentation done. Closing. Feel free to comment with feedback if necessary.

**Comment by marcoeg** [comment]
This is all extremely confusing. "Alert" as a noun means: "a warning to people to get ready to deal with something dangerous" (Cambridge Dictionary). In reality what you deal with are all "events" but you are mixing in an almost interchangeable way "event", "alert", "condition". Furthermore, the categories all-of-the-above are partitioned "engaged", "released", "past", "flow", "type" have no underlying logic whatsoever. Finally, when all-of-the-above becomes a log entry, there is another level of classification. Suggestion: get back to the drawing board.
