### ISSUE TITLE
Implement protocol/category editor

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1974]
In ntopng (and nEdge) it is not possible to edit protocols and categories though the web interface. For instance if a user wants to define a new protocol (e.g. all traffic going to domain abc123.net) should be marked as protocol/category mywebsites.

Users can achieve this behaviour *partially* using

[--ndpi-protocols|-p] <file>.protos | Specify a nDPI protocol file
                                    | (eg. protos.txt)

but the categories cannot be defined this way. 

It is requested to
- extend ntopng/nEdge to handle categories
- implement (even a simple <textarea></textarea> field for the time being, refining it overtime) where people can add/set their protocols
- add the ability to click on "flow info" and from there (only if admin user), in case there is a SNI (https://en.wikipedia.org/wiki/Server_Name_Indication) add this name to an existing category

**Comment by marcoeg** [comment]
Please describe the details of how to add and edit categories and protocols in the CLI. Specifically, I need to add a protocol to allow traffic only to servers with a specific CN, including wild card names. The intent is allow connections only to servers that belong to a specific organization such as Google or Amazon.

**Comment by emanuele-f** [comment]
Implemented in aa1ead94c4c168c57b353e8694bf2251b5fca0e2
