### ISSUE TITLE
Update coredump generation documentation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1975]
With the advent of systemd, the instructions at 
- https://www.ntop.org/support/need-help-2/need-help/ 
- https://www.ntop.org/support/faq/how-to-report-a-bug-on-ntop-apps/
are not covering it.

It is requested to improve the page and explain how ntop apps can generate coredumps when systemd is used.

**Comment by simonemainardi** [comment]
- instructions have been updated to include also the debugging of packaged applications and the use of utility `systemd-coredumpctl`
- a real example of ntopng core dump generation on ubuntu 16 has been given as well
- the FAQ page has been shortened to avoid duplicated information and a link to the need help page has been added.
