### ISSUE TITLE
Missing v9 Info Element : next-hop address ipv4 bgp [18]

### ISSUE THREAD

**Issue by kthkaya** [ntop/ntopng#198]
Hello,

The exporter (Cisco ASR) is exporting "next-hop address ipv4 bgp" with ID 18, but Appendix B of nprobe guide does not have 18 (nor 19 and 20)

How can I configure my template to collect 18 ?

Thanks!

**Comment by kthkaya** [comment]
I also need ipv4 total-length ID 190 and it is absent in Appendix

**Comment by lucaderi** [comment]
nProbe is unable to handle such fields, thus they are not propagated to ntopng. The behaviour you are experiencing is thus correct according to our design.
