### ISSUE TITLE
Feature Request: Add ifid to host export output (do_export_data.lua)

### ISSUE THREAD

**Issue by boisgada** [ntop/ntopng#1981]
It would be nice if the host export also included the ifid in the json output.  Specifically, when exporting using the ifid of a view made up of all ifid's, it would be nice to see the original ifid associated with the host in the json output.

**Comment by simonemainardi** [comment]
Thank you for this request. We've accomodated it as we believe it is important, especially for view interfaces as you've pointed out. 

The interface id will be an extra key in the host json retrieved

```
...... "total_activity_time":3150,"ifid":0,"throughput_bps":369.52307128906,"privatehost":true,"pktStats.sent": ......
```

The new build will be available starting from tomorrow.
