### ISSUE TITLE
[nEdge] Implement per-device type DPI presets

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1982]
Depending on the device, some protocols are allowed or not. Example if we have a printer, such device can do for instance LPR but not Bittorrent. Currently this features is a stub (See https://github.com/ntop/ntopng/blob/dev/src/Ntop.cpp#L1817)

It is requested to define 
- a list of allowed (as client/server) per device type
- make sure this list is enforced by the ntopng code: on ntopng it will trigger an alert, on nEdge will block the flow
- add a way to edit through the GUI the list of protocols per device

**Comment by cardigliano** [comment]
How should *presets* work logically? What is their priority with respect to the pool protocols configuration?
At the moment priority is not clear as presets are initialized in Ntop::initAllowedProtocolPresets
and evaluated in Flow::updateFlowShapers, however they are actually ignored as the shapers verdict 
overwrites the preset policy

2 possible logics are proposed:

1. apply presets to devices in the "Not Assigned" pool only:
- give to presets higher priority wrt the default/protocol policy in the "Not Assigned" pool
- the user can edit the presets (for the "Not Assigned" pool only) as an extra configuration (an additional tab)
- if the user wants to apply a specific policy other then the preset to a device, he can move the device to a custom pool (where presets are not applied)

2. create predefined pools for each device type in the presets (e.g. pool 'Printers'):
- each pool has a default policy (preset) that can be edited as today
- new devices are automatically assigned to pools based on the device type

**Comment by emanuele-f** [comment]
The feature is now implemented in both nEdge and ntopng. Documentation at https://www.ntop.org/guides/ntopng/advanced_features/device_protocols.html
