### ISSUE TITLE
Improve Custom Categories Support

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#1983]
Currently, support for custom categories is mixed.

There are custom categories supported by nDPI that appear in the protocols list as "User custom category XX"

![image](https://user-images.githubusercontent.com/3397663/45173719-495bc180-b209-11e8-802c-353a41ea6368.png)

There are other custom categories that are loaded from text files in `/other/lists` using `scripts/lua/modules/lists_utils.lua` but those categories don't appear in the list above.

It is requested to improve the support for custom categories and make sure flows can be categorized (or blocked in the case of nEdge) using custom categories.

Also handle the list of malware downloaded from emergingthreats as a custom category.

**Comment by lucaderi** [comment]
@simonemainardi Do not forget to also handle the mining category

**Comment by simonemainardi** [comment]
- implement a page with category -> list of host names where the list of host names is a simple text field
- ability to add hostnames directly for the flow page into a category
  - need to see how to chose the relevant part of the name (e.g., web1.aa.com, web2.aaa.com, ecc)
- define which categories should be blocked in ntopng instead of having hard-coded pieces such as

```
  inline bool isBlacklistedFlow() {
    return(cli_host && srv_host && (cli_host->isBlacklisted()
                                    || srv_host->isBlacklisted()
                                    || (((u_int8_t)ndpiDetectedProtocol.category) == CUSTOM_CATEGORY_MALWARE)));
  };
```

**Comment by simonemainardi** [comment]
Missing Mining category is now fixed.

The rest is in progress as part of #1974.
