### ISSUE TITLE
Implement nEdge restart

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1990]
In some cases, restarting the whole box running nEdge with a reboot is way too much. For instance changes such as modify the list of local networks can be handled via a restart of nEdge (and in the future, even transparently).

It is requested to implement this feature and use it when a reboot would be too much.

**Comment by simonemainardi** [comment]
implemented in https://github.com/ntop/ntopng/commit/9cad482002b69b0a9f152c031d634668e7a82687 and in the companion nEdge commit
