### ISSUE TITLE
No Results Found by Operating system

### ISSUE THREAD

**Issue by anrodriguezco** [ntop/ntopng#1994]
Hi,

I'm not being able to see any OS in my network, may i need to install/reinstall any nagios missed modules to get this function working?

[This](https://prnt.sc/krha88) is what i'm currently seeing.

Thank you in advance for your help.

**Comment by emanuele-f** [comment]
Hi, what's your monitoring setup? Have you configured the local networks properly https://www.ntop.org/guides/ntopng/basic_concepts/hosts.html#local-hosts ?

**Comment by anrodriguezco** [comment]
Hey @emanuele-f  thanks for your reply!!
Yep i'm able to see all the devices of [my network ](http://prntscr.com/krq64j)10.163.0.0 /22 but no info regarding their OS

**Comment by simonemainardi** [comment]
@anrodriguezco please post the configuration used for ntopng. Note that OS detection is only available when monitoring physical interfaces. It is not available over ZMQ as it requires packets to be inspected.

**Comment by anrodriguezco** [comment]
Hi @simonemainardi it's not too much, [this](http://prntscr.com/krrchf) is my ntopng.conf file:

It's that what you are referring to?

**Comment by simonemainardi** [comment]
OS detection is performed only for HTTP flows using information collected by nDPI:

https://github.com/ntop/ntopng/blob/c75469592800f7a899a66fad2640eab572765f91/src/Flow.cpp#L435

In particular, it is extracted using the HTTP user agent

https://github.com/ntop/nDPI/blob/6373c355cfd497d57609b8ecfc62717758ac7154/src/lib/protocols/http.c#L152

Therefore, if you have no or a few HTTP traffic you may end up in having missing OSes.

If you do have HTTP traffic and you feel OSes are misdetected then please file in issue at  https://github.com/ntop/nDPI/issues and post a pcap file of the HTTP traffic along with the (mis-)detected OS.

**Comment by anrodriguezco** [comment]
Hi @simonemainardi I do have a lot of hhtp trafic on my network however isn't working and is weird because with an old version of NtopNg was working OS detection, I found [this](http://prntscr.com/ksq2vy) and the listening interface is conected to a monitor sesion port so maybe that is why is not working.

Thank you for your help anyways.
