### ISSUE TITLE
Multiple IPs on one Interface, ntop only shows Information for first IP

### ISSUE THREAD

**Issue by rjsears** [ntop/ntopng#1996]
I am running ntopng v3.7.180906 on a Linux Ubuntu server with a single network interface but three separate IP address assigned to the interface (eth0 in this case). All three IPs are bound to eth0, NOT eth0:0, eth0:1, eth0:2.

Netopng is only showing traffic for the primary (first) IP address assigned to that interface and nothing else.

**Comment by emanuele-f** [comment]
Hi, are you referring to the [local hosts](https://www.ntop.org/guides/ntopng/basic_concepts/hosts.html#local-hosts)? You can manually specify your subnets with the `--local-networks` option

**Comment by rjsears** [comment]
Well, not localhosts. For example, on this particular server I have http and https traffic on all three IPs attached to eth0. When I look at the traffic I see http and https traffic destined to the main interface IP but not the other two IPs even though the sites are getting traffic. 

Is it possible that it only shows traffic to the main IP on a given interface.

Also, I see a bunch of entires from "blacklisted" hosts on ports blocked in my iptables firewall so I am wondering how ntopng is seeing that traffic unless I have something misconfigured or it does not like having three IPs on one interface?

**Comment by emanuele-f** [comment]
ntopng captures the traffic from the network interface, and this happens before traffic goes through iptables, so this is normal. ntopng sees what the NIC sees. Are you sure that you have visibility on the network traffic of the other two networks? Please verify this by running tcpdump on the interface with proper filters

**Comment by rjsears** [comment]
I am not sure what you mean by "visibility on the network". As root running tcpdump I see traffic destined to all three IP addresses on the interface. Does this traffic show up someplace different in NtopNG?

I go to Interface and select eth0 and it is only showing me the first IP address assigned to that interface.

**Comment by emanuele-f** [comment]
Please post your `/etc/ntopng/ntopng.conf` file

**Comment by rjsears** [comment]
-G=/var/run/ntopng.pid
-e=
-i=eth0
-w=3000
-d=/var/lib/ntopng
-q=

**Comment by emanuele-f** [comment]
Please add your three local network addresses to the ntopng.conf file, e.g.:

`-m="192.168.0.0/24,192.168.1.0/24,192.168.2.0/24"`

**Comment by rjsears** [comment]
Will do and I will report back...

**Comment by rjsears** [comment]
OK - Still no change. eth0 still only shows a single IP address even though there are three assigned to the interface.

**Comment by emanuele-f** [comment]
Please note that the IP address shown in ntopng for the interface eth0 is not important for monitoring. Ntopng captures traffic from the physical network interface, it will work even if the interface has no IP address at all as soon as the NIC receives the network traffic (e.g. via a mirror port). What matters here is that the IP addresses you are monitoring are shown in the "Hosts" view of ntopng.

If this does not happen, please perform the following test on the same ntopng machine.
Assuming 192.168.1.100 is the address which is not being shown in the "Hosts" view:

1. Run `sudo tcpdump -n -i eth0 host 192.168.1.100`. Can you see any traffic?
2. If you insert `192.168.1.100` in the "Search Host" bar at the top of the ntopng gui, can you see a result, click on it, and jump to the host page?

**Comment by rjsears** [comment]
OK, that is new. I run ntopng on four servers, three of them show ALL IPs assigned to eth0, the forth does not, that is what started me down this trail. Clearly, ntopng is designed to show the IPs assigned to the interface as opposed to just a single one. So just as clearly there appears to be something different with this install (or configuration) than with my other installs. 

I can see traffic both from tcpdump as well as in the hosts section, so I assume that it is operating correctly, but since it is not operating the same as my other servers, how can I be sure?

I guess when I didn't see the other IPs, I assumed (incorrectly I guess) that it was broken.

**Comment by emanuele-f** [comment]
Maybe the ntopng versions used are different? You could verify it's working properly, for example, by performing some test download and checking that both your client host is in the "Hosts" view and the flow for the download is in the "Flows".

**Comment by rjsears** [comment]
Same exacat versions across all four systems:

ntopng Community Edition v.3.6.180911


I'll check further in the details to make sure the traffic is showing up like it should. 

Thanka

**Comment by simonemainardi** [comment]
any news @rjsears ?

**Comment by rjsears** [comment]
OK, I think I need to reinstall on this one system. On the systems that I can "see" the IPs assigned to the interface I am seeing all traffic both in ntopng as well as tcpdump. This is not the case with the system where it only shows a single IP assigned to the interface. 

I am going to purge the install and reinstall and see if that fixes the problem.

**Comment by emanuele-f** [comment]
ok, please let us know if this solves the issue

**Comment by simonemainardi** [comment]
Closing fon inactivity. please, reopen with the requested information if necessary.
