### ISSUE TITLE
MAC and IP Address on the same Flow page

### ISSUE THREAD

**Issue by Baymax254** [ntop/ntopng#1997]
I want to print MAC on the same table as that of IP addresses? Please help me to print it on the flows page?

How to get MAC column on the get_flows_data.lua ?

**Comment by emanuele-f** [comment]
Hi, you can modify get_flows_data to add the mac address to the client name:

`cli_name = cli_name .. " " .. interface.getHostInfo(value["cli.ip"]).mac`

**Comment by Baymax254** [comment]
Thankyou, Emanuel
Now if I only want a separate mac address field? what I need to do

**Comment by Baymax254** [comment]
Thankyou @emanuele-f
