### ISSUE TITLE
https login for ntopng is not working

### ISSUE THREAD

**Issue by prasanthi97** [ntop/ntopng#1998]
Followed  below mentioned steps.. and also find below ntopng logs. 
1.Configured the steps in https://github.com/ntop/ntopng/blob/dev/doc/README.SSL
2.Ntopng.conf   did --http =0  and –https=3002
3.Netstat and ntopng log below still shows   3000.

Logs :
7/Sep/2018 10:10:08 [main.cpp:298] PID stored in file /var/run/ntopng.pid
07/Sep/2018 10:10:08 [Utils.cpp:499] User changed to nobody
07/Sep/2018 10:10:08 [HTTPserver.cpp:1114] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
07/Sep/2018 10:10:08 [HTTPserver.cpp:1117] HTTP server listening on 3000
07/Sep/2018 10:10:08 [main.cpp:382] Working directory: /var/tmp/ntopng
07/Sep/2018 10:10:08 [main.cpp:384] Scripts/HTML pages directory: /usr/share/ntopng

Still we are not able to do https login at port 3002. Shws connection refused.
Please let me know any additional configuration

**Comment by emanuele-f** [comment]
Hi, if you are running the ntopng service, please perform a restart: `systemctl restart ntopng`. If you are running ntopng from cli, you need to point ntopng to the configuration file to use via startup line: `ntopng /etc/ntopng/ntopng.conf`

**Comment by prasanthi97** [comment]
Hello, once after restarting netsat 3000 disappeared.  Only 3001 port listening…  but still on chrome browser we get below error
 This site can’t be reached
ab.bcd.com refused to connect.
Try:
  Checking the connection
    Checking the proxy and the firewall

ERR_CONNECTION_REFUSED

And after that while running ntopng as service its not running.

**Comment by prasanthi97** [comment]
the logs are as follows :
07/Sep/2018 12:36:29 [Prefs.cpp:1087] Using ElasticSearch for data dump [gtascj][gtanetflows-%Y.%m.%d][http://localhost:9200/_bulk]
07/Sep/2018 12:36:29 [Ntop.cpp:1544] Setting local networks to 127.0.0.0/8
07/Sep/2018 12:36:29 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
07/Sep/2018 12:36:29 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
07/Sep/2018 12:36:29 [NtopPro.cpp:312] [LICENSE] Reading license from /etc/ntopng.license
07/Sep/2018 12:36:29 [NtopPro.cpp:208] [LICENSE] /etc/ntopng.license: found valid Enterprise license
07/Sep/2018 12:36:29 [Ntop.cpp:1638] Registered interface tcp://10.0.0.10:9995 [id: 2]
07/Sep/2018 12:36:29 [main.cpp:298] PID stored in file /var/run/ntopng.pid
07/Sep/2018 12:36:29 [HTTPserver.cpp:924] ERROR: [HTTP] set_ssl_option: cannot open /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem: error:0906D06C:PEM routines:PEM_read_bio:no start line
07/Sep/2018 12:36:29 [HTTPserver.cpp:1104] ERROR: Unable to start HTTP server (IPv4) on ports 3001s
07/Sep/2018 12:36:29 [HTTPserver.cpp:1110] ERROR: Either port in use or another ntopng instance is running (using the same port)
Though it is showing another instance is running, but the pidof ntopng is not showing anything.

**Comment by simonemainardi** [comment]
check this error

```
07/Sep/2018 12:36:29 [HTTPserver.cpp:924] ERROR: [HTTP] set_ssl_option: cannot open /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem: error:0906D06C:PEM routines:PEM_read_bio:no start line
```

 make sure the file exists and it the file format is correct.

**Comment by prasanthi97** [comment]
yes..Thank you
