### ISSUE TITLE
ERROR: Unable to start HTTP server 

### ISSUE THREAD

**Issue by atin001** [ntop/ntopng#2]
I have installed ntopng and redis server successfully on one of my VMs 
* OS Version: 2.6.39-400.109.6.el6uek.x86_64
* Installed by compiling from source checked out from svn

Not able to start ntopng. The error that I am facing is as follows
 
[root@ucf2b-docs-psr0427-ms1 bin]# ./ntopng
30/Apr/2015 10:48:53 [Ntop.cpp:779] Setting local networks to 192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,127.0.0.0/8,0.0.0.0/32,224.0.0.0/8,239.0.0.0/8,255.255.255.255/32,127.0.0.0/8
30/Apr/2015 10:48:53 [Redis.cpp:93] Successfully connected to Redis 127.0.0.1:6379@0
30/Apr/2015 10:48:54 [main.cpp:201] ERROR: Startup error: missing super-user privileges ? (I am already running as su!)
 
[root@ucf2b-docs-psr0427-ms1 bin]# ./ntopng -i eth0
30/Apr/2015 10:48:57 [Ntop.cpp:779] Setting local networks to 192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,127.0.0.0/8,0.0.0.0/32,224.0.0.0/8,239.0.0.0/8,255.255.255.255/32,127.0.0.0/8
30/Apr/2015 10:48:57 [Redis.cpp:93] Successfully connected to Redis 127.0.0.1:6379@0
30/Apr/2015 10:48:57 [PcapInterface.cpp:81] Reading packets from interface eth0...
30/Apr/2015 10:48:57 [Ntop.cpp:1027] Registered interface view eth0 [id: 0]
30/Apr/2015 10:48:57 [Ntop.cpp:997] Registered interface eth0 [id: 0]
30/Apr/2015 10:48:57 [Utils.cpp:277] User changed to nobody
30/Apr/2015 10:48:57 [main.cpp:227] PID stored in file /var/tmp/ntopng.pid
30/Apr/2015 10:48:57 [HTTPserver.cpp:449] HTTPS Disabled: missing SSL certificate /usr/local/share/ntopng/httpdocs/ssl/ntopng-cert.pem
30/Apr/2015 10:48:57 [HTTPserver.cpp:451] Please read https://svn.ntop.org/svn/ntop/trunk/ntopng/README.SSL if you want to enable SSL.
30/Apr/2015 10:48:57 [HTTPserver.cpp:486] ERROR: Unable to start HTTP server (IPv4) on ports 3000 (no su error now!)
 
Confirmed that 3000 port is not in use
[root@ucf2b-docs-psr0427-ms1 bin]# netstat -nap|grep 3000
[root@ucf2b-docs-psr0427-ms1 bin]#
 
Tried to start it on a different port just in case
[root@ucf2b-docs-psr0427-ms1 bin]# ./ntopng -i eth0 -w 25436
30/Apr/2015 10:58:15 [Ntop.cpp:779] Setting local networks to 192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,127.0.0.0/8,0.0.0.0/32,224.0.0.0/8,239.0.0.0/8,255.255.255.255/32,127.0.0.0/8
30/Apr/2015 10:58:15 [Redis.cpp:93] Successfully connected to Redis 127.0.0.1:6379@0
30/Apr/2015 10:58:15 [PcapInterface.cpp:81] Reading packets from interface eth0...
30/Apr/2015 10:58:15 [Ntop.cpp:1027] Registered interface view eth0 [id: 0]
30/Apr/2015 10:58:15 [Ntop.cpp:997] Registered interface eth0 [id: 0]
30/Apr/2015 10:58:15 [Utils.cpp:277] User changed to nobody
30/Apr/2015 10:58:15 [main.cpp:227] PID stored in file /var/tmp/ntopng.pid
30/Apr/2015 10:58:15 [HTTPserver.cpp:449] HTTPS Disabled: missing SSL certificate /usr/local/share/ntopng/httpdocs/ssl/ntopng-cert.pem
30/Apr/2015 10:58:15 [HTTPserver.cpp:451] Please read https://svn.ntop.org/svn/ntop/trunk/ntopng/README.SSL if you want to enable SSL.
30/Apr/2015 10:58:15 [HTTPserver.cpp:486] ERROR: Unable to start HTTP server (IPv4) on ports 25436
 
Enabled SSL and tried to start it
[root@ucf2b-docs-psr0427-ms1 bin]# ./ntopng -i eth0 -w 25436 -s
30/Apr/2015 10:58:19 [Ntop.cpp:779] Setting local networks to 192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,127.0.0.0/8,0.0.0.0/32,224.0.0.0/8,239.0.0.0/8,255.255.255.255/32,127.0.0.0/8
30/Apr/2015 10:58:19 [Redis.cpp:93] Successfully connected to Redis 127.0.0.1:6379@0
30/Apr/2015 10:58:19 [PcapInterface.cpp:81] Reading packets from interface eth0...
30/Apr/2015 10:58:19 [Ntop.cpp:1027] Registered interface view eth0 [id: 0]
30/Apr/2015 10:58:19 [Ntop.cpp:997] Registered interface eth0 [id: 0]
30/Apr/2015 10:58:19 [main.cpp:227] PID stored in file /var/tmp/ntopng.pid
30/Apr/2015 10:58:19 [HTTPserver.cpp:486] ERROR: Unable to start HTTP server (IPv4) on ports 25436,3001s
 
Checked /var/log/messages and /var/tmp/ntopng to see if there are any logs but couldn’t find anything relevant.

**Comment by atin001** [comment]
Additional Info: This issue happens only on a VM. Ntopng starts fine on physical box.

**Comment by ariava** [comment]
Hi,

thanks for the report. Could you provide some more details about the VM setup? E.g. network configuration.

Thanks,
Arianna

**Comment by atin001** [comment]
Hi Arianna
Here is the ifconfig output

[paasusr@ucf2b-docs-psr0427-ms1 ~]$ ifconfig
eth0      Link encap:Ethernet  HWaddr C6:B0:3D:21:E4:CA
          inet addr:10.241.239.42  Bcast:10.241.239.43  Mask:255.255.255.252
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:43530133 errors:0 dropped:4 overruns:0 frame:0
          TX packets:41398108 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:42226439124 (39.3 GiB)  TX bytes:41512543431 (38.6 GiB)
          Interrupt:80

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:1892 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1892 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:161086 (157.3 KiB)  TX bytes:161086 (157.3 KiB)

Please let me know what other info is reqd. OS version is mentioned in the bug.
Thanks
Atin

**Comment by chris4269** [comment]
pi@Sonde /opt/ntopng $ ./ntopng
05/May/2015 07:21:00 [Ntop.cpp:586] Setting local networks to 192.168.1.0/24,0.0.0.0/32,224.0.0.0/8,239.0.0.0/8,255.255.255.255/32,127.0.0.0/8
05/May/2015 07:21:00 [Redis.cpp:74] Successfully connected to Redis 127.0.0.1:6379
05/May/2015 07:21:00 [main.cpp:168] ERROR: Startup error: missing super-user privileges ?

Version	1.2.1 (r1.2.1)
Platform	Raspbian (armv6l)
 Currently Logged User	admin
Uptime	23 min, 56 sec
 
nDPI	r1.5.1
 Twitter Bootstrap	3.x
 Font Awesome	4.x
RRDtool	1.4.8
Redis Server	2.4.14
Mongoose web server	3.7
LuaJIT	LuaJIT 2.0.3
ØMQ	3.2.4

**Comment by ariava** [comment]
@chris4269 you seem to be starting ntopng as a non-privileged user. Have you tried starting it as superuser (e.g. sudo ./ntopng)?

**Comment by chris4269** [comment]
pi@Sonde /opt/ntopng $ sudo ./ntopng
05/May/2015 07:27:28 [Ntop.cpp:586] Setting local networks to 192.168.1.0/24,0.0.0.0/32,224.0.0.0/8,239.0.0.0/8,255.255.255.255/32,127.0.0.0/8
05/May/2015 07:27:28 [Redis.cpp:74] Successfully connected to Redis 127.0.0.1:6379
05/May/2015 07:27:29 [main.cpp:168] ERROR: Startup error: missing super-user privileges ?

**Comment by lucaderi** [comment]
Any chance to provide SSH access to your box to debug the issue locally?

**Comment by chris4269** [comment]
I live work on the server

**Comment by chris4269** [comment]
it's ok with : sudo ./ntopng -i eth0

**Comment by lucaderi** [comment]
What Linux distribution are you using exactly ? Please use the GIT code as we have made fixes in the past days (you said you are using the SVN code)

**Comment by chris4269** [comment]
RASPBIAN
Debian Wheezy
Release date:2015-02-16
Default login:pi / raspberry
Kernel version:3.18
Release notes:Link

**Comment by lucaderi** [comment]
We cannot support you if you use an old code version. Please update to github and try again

**Comment by chris4269** [comment]
Copyright	© 1998-2014 - ntop.org
License	GNU GPLv3
Version	1.2.1 (r1.2.1)
Platform	Raspbian (armv6l)
 Currently Logged User	admin
Uptime	11 sec
 
nDPI	r1.5.1
 Twitter Bootstrap	3.x
 Font Awesome	4.x
RRDtool	1.4.8
Redis Server	2.4.14
Mongoose web server	3.7
LuaJIT	LuaJIT 2.0.3
ØMQ	3.2.4
GeoIP	1.4.8

This product includes GeoLite data created by MaxMind, available from http://www.maxmind.com.

Data-Driven Documents (d3js)	2.9.1 / 3.0
Compressed Bitmap (EWAHBoolArray)	0.4.0

**Comment by ariava** [comment]
@chris4269 ntopng 1.2.1 is a really old version. Could you please clone this repo and try it? Or just grab some nightly build from the repo.

**Comment by atin001** [comment]
Question: The issue @chris4269 is facing seems to be different from what I have reported. In my case I ran ntopng as root and specifying the interface did not help. The error message is different also. Perhaps it needs to be tracked as a new bug?

The version I used was
[root@ucf2b-docs-psr0427-ms1 paasusr]# /usr/local/bin/ntopng --version
v.1.99.150430 (r9332)

**Comment by ariava** [comment]
@atin001 Probably you shouls, but still, from the log you reported it seems you are not using the very latest code. Could you please try with the latest github code and, if you still see the issue, file a new issue? Thanks.

**Comment by chris4269** [comment]
pi@Sonde /opt/ntopng $ ./ntopng -V
v.1.2.1 (r1.2.1)

**Comment by lucaderi** [comment]
Like I have said we cannot support you unless you give access to your box where we can reproduce the bug.

**Comment by chris4269** [comment]
hello 
I again install ntop on kali for raspberry
http://www.kali-quebec.org/viewtopic.php?id=306

root@kali:/opt/ntopng# ./ntopng -V
v.1.2.1 (r1.2.1)

when i select manage user 
07/May/2015 19:58:01 [NetworkInterface.cpp:800] Started packet polling on interface lo [id: 2]...
Segmentation fault
root@kali:/opt/ntopng#

ntop is out of order

**Comment by ariava** [comment]
@chris4269, please do try to install the latest ntopng. It is version 1.99 and you can download it from this very same repo. Version 1.2.1 is very old.

**Comment by chris4269** [comment]
give me url for version 1.99

**Comment by alenauta** [comment]
@chris4269 you can git clone version 1.99 from https://github.com/ntop/ntopng.git

**Comment by chris4269** [comment]
wget http://sourceforge.net/projects/ntop/files/ntopng/ntopng-1.99.tgz
--2015-05-07 20:12:15--  http://sourceforge.net/projects/ntop/files/ntopng/ntopng-1.99.tgz
Resolving sourceforge.net (sourceforge.net)... 216.34.181.60
Connecting to sourceforge.net (sourceforge.net)|216.34.181.60|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-05-07 20:12:15 ERROR 404: Not Found.

**Comment by ariava** [comment]
@chris4269, use git (available for all Linux distributions as a package) and do
git clone https://github.com/ntop/ntopng.git

**Comment by chris4269** [comment]
when I chose clone in desktop i have https://mac.github.com

**Comment by chris4269** [comment]
pi@raspberrypi /tmp $ sudo git clone https://github.com/ntop/ntopng.git
Cloning into 'ntopng'...
remote: Counting objects: 1985, done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 1985 (delta 9), reused 0 (delta 0), pack-reused 1955
Receiving objects: 100% (1985/1985), 9.68 MiB | 554 KiB/s, done.
Resolving deltas: 100% (541/541), done.
Checking out files: 100% (1619/1619), done.
pi@raspberrypi /tmp $ cd ntopng/
pi@raspberrypi /tmp/ntopng $ ls
autogen.sh      include                README.docker_openstack  README.vagrant
config.guess    LICENSE                README.httpbl            README.windows
configure.seed  linux.guess            README.md                scripts
contrib         Makefile.in            README.ntopng            src
COPYING         ntopng.8               README.SSL               third-party
doc             packages               README.todo              tools
httpdocs        README.categorization  README.users
pi@raspberrypi /tmp/ntopng $ sudo ./autogen.sh
./autogen.sh: 13: ./autogen.sh: autoreconf: not found

Now run ./configure

**Comment by lucaderi** [comment]
https://github.com/ntop/ntopng/blob/dev/README.ntopng

**Comment by chris4269** [comment]
it's missing apache2 in the prerequisites !

**Comment by alenauta** [comment]
@chris4269 after you have installed all dependencies, prior to do ./configure, you have to git clone https://github.com/ntop/nDPI.git and compile it.

**Comment by chris4269** [comment]
ERROR: Unable to start HTTP server (IPv4) on ports 3000

sudo ./ntopng
08/May/2015 10:27:08 [src/Ntop.cpp:779] Setting local networks to 192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,127.0.0.0/8,0.0.0.0/32,224.0.0.0/8,239.0.0.0/8,255.255.255.255/32,127.0.0.0/8
08/May/2015 10:27:08 [src/Redis.cpp:93] Successfully connected to Redis 127.0.0.1:6379@0
08/May/2015 10:27:08 [src/PcapInterface.cpp:81] Reading packets from interface eth0...
08/May/2015 10:27:08 [src/Ntop.cpp:1027] Registered interface view eth0 [id: 0]
08/May/2015 10:27:08 [src/Ntop.cpp:997] Registered interface eth0 [id: 0]
08/May/2015 10:27:09 [src/PcapInterface.cpp:81] Reading packets from interface lo...
08/May/2015 10:27:09 [src/Ntop.cpp:1027] Registered interface view lo [id: 1]
08/May/2015 10:27:09 [src/Ntop.cpp:997] Registered interface lo [id: 1]
08/May/2015 10:27:09 [src/Utils.cpp:277] User changed to nobody
08/May/2015 10:27:09 [src/main.cpp:227] PID stored in file /var/tmp/ntopng.pid
08/May/2015 10:27:09 [src/HTTPserver.cpp:449] HTTPS Disabled: missing SSL certificate /tmp/ntopng/httpdocs/ssl/ntopng-cert.pem
08/May/2015 10:27:09 [src/HTTPserver.cpp:451] Please read https://svn.ntop.org/svn/ntop/trunk/ntopng/README.SSL if you want to enable SSL.
08/May/2015 10:27:09 [src/HTTPserver.cpp:486] ERROR: Unable to start HTTP server (IPv4) on ports 3000
pi@raspberrypi /tmp/ntopng $ sudo ./ntopng -w 666
08/May/2015 10:27:15 [src/Ntop.cpp:779] Setting local networks to 192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,127.0.0.0/8,0.0.0.0/32,224.0.0.0/8,239.0.0.0/8,255.255.255.255/32,127.0.0.0/8
08/May/2015 10:27:15 [src/Redis.cpp:93] Successfully connected to Redis 127.0.0.1:6379@0
08/May/2015 10:27:15 [src/PcapInterface.cpp:81] Reading packets from interface eth0...
08/May/2015 10:27:15 [src/Ntop.cpp:1027] Registered interface view eth0 [id: 0]
08/May/2015 10:27:15 [src/Ntop.cpp:997] Registered interface eth0 [id: 0]
08/May/2015 10:27:16 [src/PcapInterface.cpp:81] Reading packets from interface lo...
08/May/2015 10:27:16 [src/Ntop.cpp:1027] Registered interface view lo [id: 1]
08/May/2015 10:27:16 [src/Ntop.cpp:997] Registered interface lo [id: 1]
08/May/2015 10:27:16 [src/Utils.cpp:277] User changed to nobody
08/May/2015 10:27:16 [src/main.cpp:227] PID stored in file /var/tmp/ntopng.pid
08/May/2015 10:27:16 [src/HTTPserver.cpp:449] HTTPS Disabled: missing SSL certificate /tmp/ntopng/httpdocs/ssl/ntopng-cert.pem
08/May/2015 10:27:16 [src/HTTPserver.cpp:451] Please read https://svn.ntop.org/svn/ntop/trunk/ntopng/README.SSL if you want to enable SSL.
08/May/2015 10:27:16 [src/HTTPserver.cpp:486] ERROR: Unable to start HTTP server (IPv4) on ports 666
pi@raspberrypi /tmp/ntopng $

**Comment by chris4269** [comment]
i'ts ok 

I just discovered Raspbian (August image) has no IPv6 enabled by default. 

To solve this, I used "sudo nano /etc/modules", added "ipv6" at the end, and rebooted.

**Comment by ariava** [comment]
@chris4269 commit b72bba5 should add a workaround which should allow you to now use ntopng even with IPv6 disabled
