### ISSUE TITLE
Host %s is no longer a possible scanner [%u active flows]

### ISSUE THREAD

**Issue by JKeySZR** [ntop/ntopng#200]
Hi ! 
I have a lot of  alerts. in ntopng

![host_172 16 0 120_is_no_longer_a_possible scanner](https://cloud.githubusercontent.com/assets/5275741/10301893/bbe17422-6c0f-11e5-92b3-e4f1b8f9ebb4.png)

In  include/ntop_defines.h 
``` c++
#define CONST_MAX_NUM_HOST_ACTIVE_FLOWS 32768 
```
In Host.cpp 

``` c++
void Host::decNumFlows(bool as_client) {
  if(as_client) {
    if(num_active_flows_as_client) {
      num_active_flows_as_client--;

      if(num_active_flows_as_client == ntop->getPrefs()->get_host_max_active_flows()) {
	const char* error_msg = "Host <A HREF=%s/lua/host_details.lua?host=%s&ifname=%s>%s</A> is no longer a possible scanner [%u active flows]";
	char ip_buf[48], *h, msg[512];
```

Max  value of max_active_flows  may be 32768, but i have more active flows from server, so how can I increase it ?
Or disable alerts for this host.

**Comment by kYroL01** [comment]
Hi @JKeySZR .
This meant that this host generates a number of flows greather than max active flows allowed for a host.
Have you already try to purge all the alerts ?
@lucaderi is there a way to increase the maximum active flows limit for a host ?

**Comment by lucaderi** [comment]
See https://github.com/ntop/ntopng/commit/fbe84f5e774e59923e51f0bbb402a66c27769a82

**Comment by JKeySZR** [comment]
@kYroL01, yes i have already purged all alerts. 
But, also the problem is that ntopng creates a lot of the same records in syslog.

**Comment by lucaderi** [comment]
Please report how to reproduce it or send us a pcap for reproducing it if still open.
