### ISSUE TITLE
Command line script to read and update ntopng preferences

### ISSUE THREAD

**Issue by charlesboyo** [ntop/ntopng#2001]
Hello all.

I might be missing something obvious, but is it possible to create a Lua script that can be invoked on the command line to retrieve and set the values of ntopng preferences (especially ntopng.prefs.mysql_retention) without C++ (appears ntop.getCache is called which is defined in LuaEngine.cpp)?

I expected that these preferences would be in the Redis database but they are not there. They are instead in the runtimeprefs.json file but totally opaque to me at the moment.

Any hints or guidance on how to proceed with be much appreciated. I have a number of ntopng instances and would like to reset the values of some preferences across the lot from the command line.

Charles

**Comment by simonemainardi** [comment]
ntopng uses an internal cache before going to Redis. This internal cache is periodically flushed to runtimeprefs.json. runtimeprefs.json is also reloaded upon ntopng startup. This prevents ntopng from continuously looking up into Redis every time it needs a preference.

For this reason, just changing a Redis preference does not suffice to guarantee the new value is known to ntopng. ntopng must be notified when a preference is changed so it can refresh its cached value. 

Therefore, to change a preference programmatically, you can write your own Lua script and let ntopng execute it. In the script, you just have to call `ntop.getPref` (or `ntop.setCache` which is an alias) and ntopng will take care of the rest.

Alternatively, you could stop ntopng, write directly into the runtimeprefs.json and then restart ntopng. That could be trickier as the file contains an hex dump of the keys but it would require no interaction with the C++ part of ntopng. If you are interested in the hex format used, you can look ad the method `dump` into the Redis class.
