### ISSUE TITLE
0 bps after upgrade from 3.6.1807dd to 3.6.180910 and 3.6.180911

### ISSUE THREAD

**Issue by engee974** [ntop/ntopng#2004]
Hello,
i decided today to upgrade my debian host wher ntopng is running.
Last version was 3.6.1807dd (do not remember the exact release) and was working perfectly.
Since the upgrade to 3.6.180910 and no 3.6.180911 i have no troughput values all are "0 bps". but there are data because Total Bytes increase.  

Already tried :

- redis-cli flushdb and flushall
- remove ntopng and install it again

My debian version : 9.5
Kernel  : Linux 4.9.0-8-amd64 
Hardware : DELL PowerEdge R430
Network interfaces driver : Broadcom Limited NetXtreme BCM5720 Gigabit Ethernet PCIe

Thanks for your help.

**Comment by emanuele-f** [comment]
Hi, what are the contents of your `/etc/ntopng/ntopng.conf` file? Can you provide a screenshot of the problem?

**Comment by engee974** [comment]
This morning throughputs are OK.
But the system is very slow. Somethng has changed with that versions.
I will post another issue.

**Comment by engee974** [comment]
I reopen the issue.
I think the issue is located in the flows processor.
With the previous version i had about 300,000 flows continously.
Now with that version the total flows increases : more than 1,000,000 after 10min. This is not possible.

![image](https://user-images.githubusercontent.com/5074983/45404289-5c3e1e00-b66f-11e8-905f-23ce0906e343.png)

![image](https://user-images.githubusercontent.com/5074983/45404398-c22aa580-b66f-11e8-99da-606f1145e77d.png)

It's really slow now tho navigate in the Web interface.

**Comment by emanuele-f** [comment]
Can you sort the flows in the "Flows" view by duration and check if the oldest flows are reasonably still active?

**Comment by engee974** [comment]
Trying to sort. After 30min still at this status
![image](https://user-images.githubusercontent.com/5074983/45418945-e2ba2600-b696-11e8-986b-e578746b7fbc.png)

The OS is starting to swap. 
![image](https://user-images.githubusercontent.com/5074983/45419029-290f8500-b697-11e8-9b74-e9b1073e3df0.png)

NTOPNG is not working. I want to downgrade to the old version of july.

**Comment by emanuele-f** [comment]
Please note that your are sorting hosts, not flows. I suggest you to restart ntopng and perform the sort while it's still usable

**Comment by emanuele-f** [comment]
You could also try to tweak "Flow Idle Timeout" in the ntopng cache settings

**Comment by engee974** [comment]
After a restart.
Flows

![image](https://user-images.githubusercontent.com/5074983/45422007-fcac3680-b69f-11e8-9a79-fe3b6408466f.png)

As said, since ntopng is updated, the flows are very high. 

Here the default cache settings.
![image](https://user-images.githubusercontent.com/5074983/45422188-878d3100-b6a0-11e8-9a03-695d2b692335.png)

the settings are OK.

**Comment by engee974** [comment]
For me the new version is unusable.
I don't knwo how to get the previous version i had before the update.
Something has changed between the 2 versions i don't know what exactly, but it's not an improvement for me.

**Comment by emanuele-f** [comment]
Sorry but we do not keep old packages in repos. Can you check out the development package (version 3.7) and see if it works properly for you? http://packages.ntop.org/

**Comment by engee974** [comment]
No change
![image](https://user-images.githubusercontent.com/5074983/45481207-04c9ac00-b75c-11e8-9344-46d71d8f0a65.png)

![image](https://user-images.githubusercontent.com/5074983/45481318-4a867480-b75c-11e8-86c0-466b4e5fec50.png)

I can build from sources

**Comment by engee974** [comment]
I reinstall a the stable release from package.
Maybe the OS has changed 
![image](https://user-images.githubusercontent.com/5074983/45485411-97704800-b768-11e8-9a0f-263787c6208d.png)

Can you reproduce my issue ?
My debian 9.5 is uptodate.

**Comment by engee974** [comment]
Don't know what happened it works fine now.
Compile from git 3.6-stable version
After 40min, throughput are now OK.

![image](https://user-images.githubusercontent.com/5074983/45487925-d4d8d380-b770-11e8-98ee-b36c6b301202.png)

Maybe old flows in a hidden cache
