### ISSUE TITLE
Bytes/bit conversion error in grafana graphs

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#2005]
I'm using ntopng v.3.6.180906 but i discovered an incongruity between the graphs shown directly on the dashboard

![screenshot_20180911_153108](https://user-images.githubusercontent.com/14093378/45363771-a88a4f00-b5d8-11e8-92b8-549e112de79b.png)

and what shown through grafana

![screenshot_20180911_153158](https://user-images.githubusercontent.com/14093378/45363666-619c5980-b5d8-11e8-83fd-f93081175622.png)

It's seems related to a bytes/bits conversion issue. :-)

What do you think?

**Comment by emanuele-f** [comment]
Yes, it a 8 factor. Can you configure grafana to tread data as bytes-per-second rather than bits-per-second? Do you know if this also happened before the 3.6 release?

**Comment by gianogli** [comment]
Ok, I've just tried but I think that this is not the correct solution.
The labels on the y axis, in fact, changed from 200Mbps to 200MB/s but the timeseries exported from ntopng are in bps (as you can see below) so I aspect that grafana, to show the correct value, would be set in bps and not in B/s. :-)

![screenshot_20180912_110634](https://user-images.githubusercontent.com/14093378/45415249-83035100-b67d-11e8-80e4-2db576c972c5.png)

I think that somewhere there is an issue like that: [https://github.com/ntop/ntopng/commit/4d6bcb4ae2d0368c13ec39b07444177a086c9675](https://github.com/ntop/ntopng/commit/4d6bcb4ae2d0368c13ec39b07444177a086c9675)

I can confirm to you that before the timeseries update you made (InfluxDB support) all worked fine.

What do you think?

**Comment by simonemainardi** [comment]
issue is fixed both in stable and dev branch. It will be available in the next build within a couple of hours.

**Comment by gianogli** [comment]
In ntopng v.3.6.180912 I can confirm to you that this issue is solved.
Thanks! :+1:
