### ISSUE TITLE
how to connect ntopng to nprobe?

### ISSUE THREAD

**Issue by volkovmm** [ntop/ntopng#201]
sorry for the stupid question, but I really need your help.all the instructions I've seen do not help me to understand how to connect ntopng to nprobe.
So, i have a server with ntopng( ip 25.110.34.64).
And i have a PC with nprobe( ip 25.110.34.65).
In a ntopng.conf i write:
-i=tcp://127.0.0.1:5556
right?
then i start nprobe next command: nprobe -zmq tcp://*:5556
and nothing works.
i tried start nprobe by use many variants. does not work. in ntopng is not received the data stream.

**Comment by lmangani** [comment]
@volkovmm please avoid opening duplicate issues, Luca provided the indications you need. Also check out http://www.ntop.org/nprobe/why-nprobejsonzmq-instead-of-native-sflownetflow-support-in-ntopng/

**Comment by volkovmm** [comment]
I read all of these instructions. does not help.

**Comment by lmangani** [comment]
Please reopen #197 is that is the case?

**Comment by volkovmm** [comment]
how to reopen?
