### ISSUE TITLE
Why 95th percentile looks like worry

### ISSUE THREAD

**Issue by lizzyshaw** [ntop/ntopng#2011]
The ntopng version is 3.6.18090,  the interface average shows 700+Mbit/s, but the 95th percentile shows 100+Mbit/s, why average & 95th percentile not match, is there something worry?
![ntopng](https://user-images.githubusercontent.com/41146732/45399592-3880d500-b67b-11e8-9eae-9cf3eb507a01.png)

**Comment by emanuele-f** [comment]
The stats/points in the chart are wrong. This was already addressed in #1960 but not ported to stable. So please wait one hour until the new package is available.

**Comment by lizzyshaw** [comment]
I installed the latest version, it's work ,thanks
