### ISSUE TITLE
IPv6 support by nEdge

### ISSUE THREAD

**Issue by TakayukiOnodera** [ntop/ntopng#2012]
Hello, 
I'm currently using nEdge as bridge mode but it doesn't detect flows and hosts with IPv6. Therefore,  connections from local hosts to some service (e.g. Youtube) cannot be handled by nEdge in our environment.

**Comment by emanuele-f** [comment]
@TakayukiOnodera currenly nEdge does not support IPv6. Thank you for pointing out, please check out #2015
