### ISSUE TITLE
Netflow customized reports

### ISSUE THREAD

**Issue by prasanthi97** [ntop/ntopng#2013]
currently we are using ntopng for network monitoring.we need to get the below details from net flow. is it possible to arrive using any filters or solution already available.
1.protocol wise break up of traffic max-in,max-0ut,avg-in,avg-out, average total
2.stacked protocol trend-in and out
3.stacked Tos trend-in  and out
4.hosts-summary volume-from
5.host-summary volume-to
6.conversation summary volume-total

**Comment by emanuele-f** [comment]
Duplicate of #2014
