### ISSUE TITLE
Netflow summary /dashboard

### ISSUE THREAD

**Issue by MeenaAshok** [ntop/ntopng#2014]
currently we are using ntopng for network monitoring.we need to get the below details from net flow. is it possible to arrive using any filters or solution already available.
1.protocol wise break up of traffic max-in,max-0ut,avg-in,avg-out, average total
2.stacked protocol trend-in and out
3.stacked Tos trend-in and out
4.hosts-summary volume-from
5.host-summary volume-to
6.conversation summary volume-total

**Comment by emanuele-f** [comment]
Hi, you can combine ntopng with nprobe for NetFlow analysis, please check out https://www.ntop.org/nprobe/network-monitoring-101-a-beginners-guide-to-understanding-ntop-tools/ .
Apart from the "Tos", which is not handled by ntopng, it should already provide the requested views. In particular:
- You can find stacked protocols and per-protocol in/out bytes in the ntopng graphs
- Traffic volumes are shown both in the "Traffic Report" page
- For accurate conversation view, you can intergrate ntopng with MySQL as described here: http://www.ntop.org/ntopng/exploring-historical-data-using-ntopng-part-2/

Please note the most detailed views are only available in the pro/enterprise versions of ntopng, please check out the comparison table at http://www.ntop.org/products/traffic-analysis/ntop/

**Comment by emanuele-f** [comment]
I'm closing the issue for now. If you have other questions, please open a new ticket
