### ISSUE TITLE
Restricted users should not be able to access the SNMP/Flow devices

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2019]
Users with a defined `Allowed Interface` should not be able to access SNMP/Flow devices information.  The function `ntop_is_allowed_interface` should also be updated to handle this. In my opinion it is better to delay the fix until #1854 is implemented.

**Comment by lucaderi** [comment]
For the time being let's only admins to configure SNMP devices and let all users to see SNMP devices
