### ISSUE TITLE
bad counter again

### ISSUE THREAD

**Issue by dvachon2018** [ntop/ntopng#2020]
Hello, the problem appear again. Ntop v3.5.180821 - Enterprise/Embedded Edition
![2018-09-12 22_53_30-welcome to ntopng](https://user-images.githubusercontent.com/33327149/45478833-d83d7200-b712-11e8-8163-cbf300c285ad.jpg)

**Comment by emanuele-f** [comment]
Related to #1912

**Comment by emanuele-f** [comment]
Fixed. A new build is in progress. The new package will be available in one hour.

**Comment by emanuele-f** [comment]
@dvachon2018 , before upgrading the package, can you identify if the peak occurs after a ntopng restart? You can identify ntopng restarts by looking at the "process" informative alerts in the alerts view.

**Comment by dvachon2018** [comment]
hello, no the peak does not appear to be related to ntopng restarts.
i did the upgrade than all bad peak counters now appear as normal value
![image](https://user-images.githubusercontent.com/33327149/45659303-cae10880-bac1-11e8-99e4-2cf2f5f38999.png)
Will try and look at that for a few days.
Thank you,
