### ISSUE TITLE
starting ntopng crash after enabled logging into /var/log/ntopng.log

### ISSUE THREAD

**Issue by ldomenella** [ntop/ntopng#2021]
when starting ntopng, it keep crashing.
Sep 13 11:00:18 bigbrother systemd: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
Sep 13 11:00:18 bigbrother systemd: Started ntopng high-speed web-based traffic monitoring and analysis tool.
Sep 13 11:00:18 bigbrother kernel: ntopng[19433]: segfault at 0 ip 00007f2094bd3ed7 sp 00007ffe101717e0 error 4 in libc-2.17.so[7f2094b99000+1c3000]
Sep 13 11:00:18 bigbrother abrt-hook-ccpp: Process 19433 (ntopng) of user 0 killed by SIGSEGV - dumping core
Sep 13 11:00:18 bigbrother systemd: ntopng.service: main process exited, code=dumped, status=11/SEGV
Sep 13 11:00:18 bigbrother systemd: Unit ntopng.service entered failed state.
Sep 13 11:00:18 bigbrother systemd: ntopng.service failed.
Sep 13 11:00:18 bigbrother abrt-server: Package 'ntopng' isn't signed with proper key
Sep 13 11:00:18 bigbrother abrt-server: 'post-create' on '/var/spool/abrt/ccpp-2018-09-13-11:00:18-19433' exited with 1
Sep 13 11:00:18 bigbrother abrt-server: Deleting problem directory '/var/spool/abrt/ccpp-2018-09-13-11:00:18-19433'
Sep 13 11:00:24 bigbrother systemd: ntopng.service holdoff time over, scheduling restart.
Sep 13 11:00:24 bigbrother systemd: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
Sep 13 11:00:24 bigbrother systemd: Started ntopng high-speed web-based traffic monitoring and analysis tool.
Sep 13 11:00:24 bigbrother kernel: ntopng[19478]: segfault at 0 ip 00007f4b3bf4ced7 sp 00007ffd24d303c0 error 4 in libc-2.17.so[7f4b3bf12000+1c3000]
Sep 13 11:00:24 bigbrother abrt-hook-ccpp: Process 19478 (ntopng) of user 0 killed by SIGSEGV - ignoring (repeated crash)
Sep 13 11:00:24 bigbrother abrt-hook-ccpp: Saved core dump of pid 19478 to core.19478 at / (2625536 bytes)
Sep 13 11:00:24 bigbrother systemd: ntopng.service: main process exited, code=dumped, status=11/SEGV
Sep 13 11:00:24 bigbrother systemd: Unit ntopng.service entered failed state.
Sep 13 11:00:24 bigbrother systemd: ntopng.service failed.
Sep 13 11:00:29 bigbrother systemd: ntopng.service holdoff time over, scheduling restart.
Sep 13 11:00:29 bigbrother systemd: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
Sep 13 11:00:29 bigbrother systemd: Started ntopng high-speed web-based traffic monitoring and analysis tool.
Sep 13 11:00:29 bigbrother kernel: ntopng[19518]: segfault at 0 ip 00007eff3050ced7 sp 00007ffcf7019e50 error 4 in libc-2.17.so[7eff304d2000+1c3000]
Sep 13 11:00:29 bigbrother abrt-hook-ccpp: Process 19518 (ntopng) of user 0 killed by SIGSEGV - ignoring (repeated crash)
Sep 13 11:00:29 bigbrother abrt-hook-ccpp: Saved core dump of pid 19518 to core.19518 at / (2625536 bytes)
Sep 13 11:00:29 bigbrother systemd: ntopng.service: main process exited, code=dumped, status=11/SEGV
Sep 13 11:00:29 bigbrother systemd: Unit ntopng.service entered failed state.
Sep 13 11:00:29 bigbrother systemd: ntopng.service failed.
Sep 13 11:00:34 bigbrother systemd: ntopng.service holdoff time over, scheduling restart.
Sep 13 11:00:34 bigbrother systemd: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
Sep 13 11:00:34 bigbrother systemd: Started ntopng high-speed web-based traffic monitoring and analysis tool.
Sep 13 11:00:34 bigbrother kernel: ntopng[19558]: segfault at 0 ip 00007f39404aded7 sp 00007ffe887f3860 error 4 in libc-2.17.so[7f3940473000+1c3000]
Sep 13 11:00:34 bigbrother abrt-hook-ccpp: Process 19558 (ntopng) of user 0 killed by SIGSEGV - ignoring (repeated crash)
Sep 13 11:00:34 bigbrother abrt-hook-ccpp: Saved core dump of pid 19558 to core.19558 at / (2625536 bytes)
Sep 13 11:00:34 bigbrother systemd: ntopng.service: main process exited, code=dumped, status=11/SEGV

**Comment by ldomenella** [comment]
the core file and the binary can be downloaded from here: https://www.dropbox.com/s/mqmp6loxppz6q9x/core_issue_2021.tgz?dl=0

**Comment by ldomenella** [comment]
ntopng --version
v.3.6.180830    [Enterprise/Professional build]
GIT rev:        3.6-stable:1358fdcbfac7344a936f924c20484dfb7476459b:20180830
Pro rev:        r1850
Built on:       CentOS Linux release 7.5.1804 (Core)
System Id:      81196BD811B1B8A9
Platform:       x86_64
Edition:        Enterprise
License Type:   Time-Limited
Validity:       Until Thu Sep 13 11:31:14 2018

**Comment by simonemainardi** [comment]
post the ntopng configuration file as well.

**Comment by ldomenella** [comment]
/etc/ntopng/ntopng.conf
[ntopng.txt](https://github.com/ntop/ntopng/files/2379587/ntopng.txt)

/etc/ntopng/protos.txt
[protos.txt](https://github.com/ntop/ntopng/files/2379591/protos.txt)

**Comment by simonemainardi** [comment]
Thanks for reporting. Issue is now fixed in the dev branch.

Isse was due to empty `--verbose` argument in your `ntopng.txt`. Verbose requires an argument and that was causing ntopng to crash.

If you want to stay with 3.6 rather than upgrading to dev, remove verbose or add a value for it.

**Comment by ldomenella** [comment]
is there somewhere the documentation for the --verbose argument ?

**Comment by ldomenella** [comment]
got it from the ntopng --help
