### ISSUE TITLE
Issues with interface traffic timeseries

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#2024]
Remote interface

Version
![image](https://user-images.githubusercontent.com/3397663/45536091-b5898700-b800-11e8-9e0b-a67fbceb6c64.png)

from the dashboard I get

![image](https://user-images.githubusercontent.com/3397663/45536087-b15d6980-b800-11e8-8cd2-be3b03c918cb.png)

from the interface chart

![image](https://user-images.githubusercontent.com/3397663/45536122-cafeb100-b800-11e8-8927-03aa445fc60f.png)

**Comment by emanuele-f** [comment]
I think that such inconsistency was fixed with commit 433cbb3142586c50f989f32c03f2c997329f8056 . Average has been further refined via 370e0c3564dc1fa8c8df0ed222775bea923e8b32 fix.

**Comment by simonemainardi** [comment]
I can confirm issue is now fixed. Thank you @emanuele-f.
