### ISSUE TITLE
nprobe.conf for netflow version9

### ISSUE THREAD

**Issue by prasanthi97** [ntop/ntopng#2025]
configured nprobe.conf for netflow version9 with -V = 9 but we are not getting the flow exported ip list populated on ntopng3.6 dashboard. By default we are getting netflow version 5. Please give additional steps to be added in conf file.

**Comment by simonemainardi** [comment]
please post the full nprobe and ntopng configurations used.

note that you can't control any netflow version between nprobe and ntopng, they talk with ZMQ. What you can control are the fields exported by nprobe using option -T. Recommended is to set at least `-T="@NTOPNG@"` when using ntopng.

**Comment by simonemainardi** [comment]
@prasanthi97 any news?

**Comment by Ravivenkatachalam** [comment]
Nprobe 8.4 conf file has below :+1: 
--zmq="tcp://*:9995"
--collector-port=2055
-n=none
-i=none

-T "@NTOPNG@" "%IPV4_SRC_ADDR %L4_SRC_PORT %IPV4_DST_ADDR %L4_DST_PORT %PROTOCOL %IN_BYTES %OUT_BYTES %FIRST_SWITCHED %LAST_SWITCHED %IN_PKTS %OUT_PKTS %IP_PROTOCOL_VERSION %APPLICATION_ID %L7_PROTO_NAME %ICMP_TYPE %SRC_IP_COUNTRY %DST_IP_COUNTRY %APPL_LATENCY_MS"

Restarted nprobe and ntopng.

earlier before adding this customized field, we got netflow device table properly .

Since we need customized field for elastic search and Kibana to get kibana netflow dashboard, nprobe fields need to be customized with netflow V9 and additional fields, above lines been included in probe.conf.

after restart , device flow exporter table got deleted and don't see netflow device in flow exporter table.

**Comment by Ravivenkatachalam** [comment]
we are trying to build netflow kibana dashboard like below options 

option -1 - nprobe->ntopng->ES->kibana
Option-2 - nprobe--ES-->kibana
Option-3 - nprobe-->ntopng-->logstash-->ES-->kibana

We could not send customized netflow v9 fields required  to push to kibana to build index and dashboard jason fields match to draw the dashboard

**Comment by simonemainardi** [comment]
the template shown is not well-formed. You close the double quote right after @NTOPNG@: `NG@" "%IPV4`.


Try with

```
-T "@NTOPNG@ %IPV4_SRC_ADDR %L4_SRC_PORT %IPV4_DST_ADDR %L4_DST_PORT %PROTOCOL %IN_BYTES %OUT_BYTES %FIRST_SWITCHED %LAST_SWITCHED %IN_PKTS %OUT_PKTS %IP_PROTOCOL_VERSION %APPLICATION_ID %L7_PROTO_NAME %ICMP_TYPE %SRC_IP_COUNTRY %DST_IP_COUNTRY %APPL_LATENCY_MS"
```

Then make sure all the fields specified in the template are contained in the netflow packets. Note that not all the fields you've specified can be parsed when collecting netflow (e..g., APPL_LATENCY_MS). The application latency for example is something that calculates nProbe when it sees real traffic packets.

**Comment by Ravivenkatachalam** [comment]
Hi Simone,
We have added the mentioned template.  logs are below :+1: 

Sep 18 15:56:27 test1 nprobe[9995]: 18/Sep/2018 15:56:27 [nprobe.c:7699] IP TOS is accounted
Sep 18 15:56:27 test1 nprobe[9995]: 18/Sep/2018 15:56:27 [util.c:454] WARNING: Unable to load AS file /usr/local/nprobe/GeoIPASNum.dat. AS support disabled
Sep 18 15:56:27 test1 nprobe[9995]: 18/Sep/2018 15:56:27 [util.c:465] WARNING: Unable to load AS IPv6 file /usr/local/nprobe/GeoIPASNumv6.dat. AS IP...t disabled
Sep 18 15:56:27 test1 nprobe[9995]: 18/Sep/2018 15:56:27 [nprobe.c:8470] Flows ASs will not be computed
Sep 18 15:56:27 test1 nprobe[9995]: 18/Sep/2018 15:56:27 [nprobe.c:8576] Not capturing packet from interface (collector mode)
Sep 18 15:56:27 test1 nprobe[9995]: 18/Sep/2018 15:56:27 [util.c:4547] Initializing ZMQ as server
Sep 18 15:56:27 test1 nprobe[9995]: 18/Sep/2018 15:56:27 [util.c:4590] Succesfully created ZMQ endpoint tcp://*:9995
Sep 18 15:56:27 test1 nprobe[9995]: 18/Sep/2018 15:56:27

**Comment by Ravivenkatachalam** [comment]
we see netflow exporter table entry gets deleted and it gives the interface Ip entry.

**Comment by prasanthi97** [comment]
@simonemainardi  please reopen the issue

**Comment by simonemainardi** [comment]
enclose a pcap capture of the netflow you are parsing please.

**Comment by Ravivenkatachalam** [comment]
Simone i wont be able to share pcap   but nprobe.conf is as below flows are coming but netflow exporter table  got deleted after -V9 and T options included.
:+1: 

--zmq="tcp://*:9995"
--collector-port=2055
-n=none
-i=none
-V=9
-T "@NTOPNG@ %SAMPLING_INTERVAL %IN_BYTES %IN_PKTS %IPV4_SRC_ADDR %IPV4_DST_ADDR %IPV4_NEXT_HOP %IPV6_SRC_ADDR %IPV6_DST_ADDR %IPV6_NEXT_HOP %L4_SRC_PORT %L4_DST_PORT %SRC_VLAN %DOT1Q_SRC_VLAN %SRC_TOS %TCP_FLAGS %PROTOCOL %IP_PROTOCOL_VERSION %DIRECTION %FLOW_START_MILLISECONDS %FLOW_END_MILLISECONDS %INPUT_SNMP %OUTPUT_SNMP %IN_SRC_MAC %OUT_DST_MAC %ICMP_TYPE %BIFLOW_DIRECTION %L7_PROTO_NAME"

**Comment by Ravivenkatachalam** [comment]
Had also included -U=888  as well in nprobe.conf still netflow exporter not populated

**Comment by simonemainardi** [comment]
what does it mean "netflow exporter table got deleted"?

**Comment by Ravivenkatachalam** [comment]
Click Devices--> Flow exporters

Table lists Flow exporters devices.. This got populated correctly    without -V -T -U  option. Now it is not getting displayed.

also refer below link
https://gist.github.com/robcowart/afd538026db29ee96dd9c495efb52ea6

**Comment by Ravivenkatachalam** [comment]
Simone,
Any update. Looks like a bug ?

**Comment by simonemainardi** [comment]
I am out of office, @cardigliano can you please check? thank you

**Comment by cardigliano** [comment]
@Ravivenkatachalam we pushed a new revision with a fix related to this issue, please update and let us know if it works for you. Thank you.

**Comment by Ravivenkatachalam** [comment]
Cardigliano

How do i update? which Link ?Do i need to update nprobe and ntopng ?

Ravi

**Comment by Ravivenkatachalam** [comment]
we use licensed version and installed it in Cent os

**Comment by cardigliano** [comment]
@Ravivenkatachalam if you are installing from our repository (http://packages.ntop.org) all you need to do is to run "apt-get update && apt-get upgrade" on Ubuntu or "yum update" on Centos
