### ISSUE TITLE
dashboard based on location

### ISSUE THREAD

**Issue by MeenaAshok** [ntop/ntopng#2026]
Hi,

I want to get a location wise flow details is it possible in ntopng .i haven't meant about geo maps.I got a requirement for dashboard similar to host wise,protocol wise likewise can we get something in location wise.

Thanks
Meena

**Comment by simonemainardi** [comment]
Currently the dashboard is not customizable. However, we are considering a rework of the current dashboard to make it more general and to possibly include other information and modifiable blocks. So stay tuned.
