### ISSUE TITLE
[nEdge] Implement backup

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2028]
Implement in nEdge backup/restore of the configuration as in ntopng

**Comment by simonemainardi** [comment]
backup/restore is already implemented also for nedge.

Documentation:
- https://www.ntop.org/guides/nedge/conf_backup.html
- https://www.ntop.org/guides/nedge/conf_backup.html#configuration-restore

The backup configuration feature is available from the system setup page in nEdge

![image](https://user-images.githubusercontent.com/3397663/45690983-e0a10d00-bb57-11e8-92e3-ddbbffb8ea7e.png)
