### ISSUE TITLE
[nEdge] Stats cleanup

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2029]
Implement in nEdge the ability to cleanup statistics similar (but not alike) to what it has been implemented in ntopng.

**Comment by simonemainardi** [comment]
In ntopng we have data cleanup of inactive interfaces.

In nEdge we always have one active interface and we need to clean in.

Proposed solution is to:
- click a cleanup button that sets a redis flag and triggers an nEdge restart (using the feature already implemented)
- check the flag during startup and do all the necessary cleaning

**Comment by simonemainardi** [comment]
implemented in https://github.com/ntop/ntopng/commit/bf43aceb9c6aa9b2a0bce13ed98bb711f6722190 and the companion nEdge commit

![image](https://user-images.githubusercontent.com/3397663/45812855-495fc500-bcd1-11e8-852e-ff49a02d9518.png)


documentation added as well with commit https://github.com/ntop/ntopng/commit/71a262ecdfc57ebc3ee4e974def3e52632e7e5ad
