### ISSUE TITLE
[nEdge] Implement automatic local networks

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2031]
In nEdge it is possible to define static routes towards specific networks. Such networks are currently defines as remote (i.e. WAN) networks, even though they can be both LAN or WAN (usually LAN). It is request to implement the ability to specify what networks are local so that they are automatically considered in -L

**Comment by simonemainardi** [comment]
Implemented.

![screen shot 2018-09-18 at 15 03 32](https://user-images.githubusercontent.com/3397663/45689348-07f5db00-bb54-11e8-95e0-7011fb3a19e9.png)

Networks are now added to the ntopng local networks when the static routes used to reach them are marked as local network static routes.
