### ISSUE TITLE
Implement User Roaming

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2032]
Implement a cluster of federated nEdge instances where when a user is authenticated on any nEdge, it can roam freely across all the instances without any further authentication (e.g. in the captive portal)

**Comment by simonemainardi** [comment]
We believe this enhancement can be absorbed by the infrastructure monitoring we have implemented. Indeed, with infrastructure monitoring, a user can monitor multiple running instances and check their running data (e.g., active hosts, flows and alerts) and also the status of the network interconnecting them (e.g., latency and bandwidth). Authentication is implemented via TOKENS associated to privileged or non-privileged users.

This post describes in detail how to use infrastructure monitoring: https://www.ntop.org/ntopng/infrastructure-monitoring-observing-the-health-and-status-of-multiple-ntopng-instances/
