### ISSUE TITLE
Implement better KPIs on network usage

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2035]
ntopng gives a lot of visibility in terms of protocols and flows but it lacks KPIs for understanding who is using the network such as
- how many iPhones are accessing the network
- where are the top visited web sites
- what is the average time a device is connected to the network
- what is the percentage of fixed, mobile, tablets

**Comment by simonemainardi** [comment]
We believe the service and periodicity maps, along with newly implemented top visited sites suffice to reach the described behaviors.

Indeed, the latest ntopng 5.0+ build service and periodicity maps to:

- Detect active services
- Raise alerts when lateral movements are detected

Detected services can be configured as allowed / denied to receive alerts accordingly. Service map is described for example in https://luca.ntop.org/IEEE_CSR.pdf and in this blog post https://www.ntop.org/announce/ntopng-5-0-is-out-modern-traffic-monitoring-for-aiops-and-cybersecurity/

Top visited sites are described in https://www.ntop.org/guides/ntopng/web_gui/host_details.html
