### ISSUE TITLE
ntopng service in windows, should run in a limited account

### ISSUE THREAD

**Issue by RHomie** [ntop/ntopng#204]
There is no reason for ntopng to run in Local Service account which is a security concern. ntopng service can easily and safely run in its own what Microsoft calls "Virtual Account" (which would be 'NT SERVICE\ntopng') . This account does not need to be created nor maintained. just simply set it in 'Log on as' parameter in the ntopng service with an empty password.

For more info about virtual accounts and be found below:
https://technet.microsoft.com/en-us/library/dd548356%28v=ws.10%29.aspx

**Comment by lucaderi** [comment]
Sorry for the delay. I wanted to finally address this request however I have not been able to find a code example to include in ntopng. Do you have a pointer perhaps? Thanks.

**Comment by RHomie** [comment]
Oh hey,
Wow, it's been 5 years! I'd completely forgotten about this issue. Anyway, good to see you're looking to fix it.
I looked around a bit and if I'm not mistaking, _service_win32.c_ is responsible for creating the actual windows service in ntopng. Based on [CreateServiceA](https://docs.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-createservicea/) doc, is appears that the only thing that you need to adjust, is changing the NULL value of _lpServiceStartName_, to _NT SERVICE\ServiceName_ , which in this case ServiceName is _SZSERVICENAME_ I think?

**Comment by lucaderi** [comment]
Sorry for taking so long ad thanks for your support
