### ISSUE TITLE
Extend MAC address stats

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2040]
Currently ntopng stats are kept per IP address with limited MAC stats. However this is a suboptimal solution when addressed are dynamic and the IP-MAC association is not guaranteed.

Ad the ability (through preferences) to keep on MACs the same stats we have on Its, including the historical view

**Comment by simonemainardi** [comment]
Currently, we already keep traffic and category stats for MACs. Those stats are shown in the historical page of mac addresses and can be enabled from the preferences:

![image](https://user-images.githubusercontent.com/3397663/45757270-3bec0180-bc23-11e8-848f-99c61ce601ee.png)

What are the extra stats you want to keep? Are you referring to the stats shown in the host home page?

**Comment by lucaderi** [comment]
L7 protocols etc. are missing from MACs for instance. We need to see for MACs the same level of details we have for IPs

**Comment by simonemainardi** [comment]
Implemented.

Currently, DHCP hosts and hosts in the broadcast domain are serialized by MAC address and also their timeseries are written by mac address.
