### ISSUE TITLE
Ntopng redis insertion

### ISSUE THREAD

**Issue by MeenaAshok** [ntop/ntopng#2041]
Hi,

canwe insert data into ntopng redis servers tables,so that we can see data in dashboard.

Thanks
Meena

**Comment by simonemainardi** [comment]
please, go through the documentation at:

- API: https://www.ntop.org/guides/ntopng/api/
- user: https://www.ntop.org/guides/ntopng/

Then, in necessary, please post specific questions.

**Comment by MeenaAshok** [comment]
Hi,

We have showed the snmp v1 and v2c data using ntopng,similar way we are about to show snmpv3 data in dashboard,but ntopng currently doesnt support v3.so we have collected snmpv3 data we have to show it in dashboard.
Any help on how to insert it to backend so we can view the dashboard similar to v1 and v2c.

Thanks
Meena

**Comment by simonemainardi** [comment]
please, show how you have shown snmp data in the dashboard. Do you have a customized script? Can you contribute to the community? Can you provide a pull request? Seeing the script will help us in supporting you.
