### ISSUE TITLE
Manage stored data

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2042]
In ntopng it is possible to manage stored data using a menu item under the preferences menu. This item is missing in nEdge.

However the current implementation limits its scope to a selected IP or MAC address. It is also request to delete all the data associated with all hosts. In essence delete all or selected data.

**Comment by simonemainardi** [comment]
proposed implementation is as follows:

![image](https://user-images.githubusercontent.com/3397663/45758292-8e2e2200-bc25-11e8-9b16-fbceb220cbb5.png)

- delete persistent data associated to the active interface (IPs/MAC/Interface rrds, etc)
- Add an extra button "Delete <interface name> data" next to the "Delete Inactive Interfaces Data"
- Re-use the already implemented lua functions that clean inactive interfaces to clean all the files of the active interface.
- make sure deletions can be performed in a safe manner (check what happens with active writers)
- when re-using the implemented lua functions make sure the interface id is not recycled as done for the inactive interfaces.

**Comment by simonemainardi** [comment]
Implemented.

Code that deletes inactive interfaces has been 100% reused to avoid duplication. When deleting everything for an active (selected) interface, a restart of ntopng is necessary and the deletion is performed upon restart. Performing hot-deletion could introduce issues as:

- there may be periodic activities writing to files and directories deleted by another thread
- on windows it's even not possible to delete files when someone has them open

The flow is this

1. The user is promted that a restart is necessary
![image](https://user-images.githubusercontent.com/3397663/46403878-fd1a7900-c703-11e8-9958-d6a62a69e332.png)

2. When the user clicks "Delete" a dismissable confirmation dialog appears that explains one more time that a restart is necessary.
![image](https://user-images.githubusercontent.com/3397663/46403896-06a3e100-c704-11e8-9aa5-b8ae464b57ef.png)

3. During the next restart the deletion is logged and confirmed in the logs.

```
03/Oct/2018 12:28:53 [boot.lua:29] Deleting data for marked active interfaces...
03/Oct/2018 12:28:53 [boot.lua:41] Deleting data [delete_if_db][OK]
03/Oct/2018 12:28:53 [boot.lua:41] Deleting data [delete_if_redis_keys][OK]
03/Oct/2018 12:28:53 [boot.lua:41] Deleting data [delete_if_data][OK]
03/Oct/2018 12:28:53 [boot.lua:46] Data deletion done.
```
