### ISSUE TITLE
[nEdge] Extend daily policies

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2043]
In nEdge all policies (e.g. quotas) are daily based. Sometimes (in particular for Internet plans) this approach is not good, as it is rather monthly based.

It is requested to modify the policies and let the use choose daily, weekly or monthly. Ideally it would be nice to have it more configurable but for the time being this should be enough.

**Comment by simonemainardi** [comment]
Current quota code is cumbersome. Before doing this, I would propose to try and inspect mechanisms provided by the kernel that allow to enforce traffic quotas and check if we can use them. Basically this is similar to what we've already done to enforce a maximum traffic speed on an host-by-host basis.

**Comment by simonemainardi** [comment]
now part of #2604
