### ISSUE TITLE
Implement per egress interface traffic statistics

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2046]
In nEdge, when multiple egress routers are used, it is not possible to visualise per-egress statistics. This means that for instance it is not possible to know much much a destination is used, for what protocols etc. In essence it is requested to keep per-destination stats.

**Comment by simonemainardi** [comment]
Notes:

- The issue refer to the physical WAN interface.
- nEdge can have multiple gateways sharing the same WAN.

Simple counters such as in/out bytes can be read from /proc. Per-application counters would require nEdge to keep instances of InterfaceStats.

**Comment by simonemainardi** [comment]
Implemented. For each physical interface now there's a details page with information, total traffic, throughput and historical charts. Example:

![image](https://user-images.githubusercontent.com/3397663/140379686-c2176601-1dd7-49bf-ae72-b9979b4865ec.png)

![image](https://user-images.githubusercontent.com/3397663/140379771-9bf2e7bc-ee0e-4f95-a0a5-b86cf6623cbd.png)
