### ISSUE TITLE
Improve block host/flow user interface 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2047]
In nEdge for blocking a host or a flow, it is necessary to go into a long list of menu/tabs instead of being able to perform the block from the list of flows/hosts. 

It is requested to implement this functionality right in the flow/host list.

**Comment by simonemainardi** [comment]
this feature currently exists for flows and hosts:

![image](https://user-images.githubusercontent.com/3397663/45759239-c6366480-bc27-11e8-8438-b621f5f33ec0.png)

![image](https://user-images.githubusercontent.com/3397663/45759099-70fa5300-bc27-11e8-9ac8-bf00d09852fe.png)

Task is to use the already-implemented mechanisms exposed in the gui as above to place new buttons on the flow/host list. For the hosts, a button like 'play/pause' should be added. For flows, given their short lifecycle, it is not necessary to add an unblock button, only the block button should suffice.

**Comment by cardigliano** [comment]
Implemented, please review it.

**Comment by simonemainardi** [comment]
thank you, I can confirm the implementation is and works as expected:

![image](https://user-images.githubusercontent.com/3397663/46488813-10ad0900-c804-11e8-86fa-fc9744afa049.png)

![image](https://user-images.githubusercontent.com/3397663/46488846-23bfd900-c804-11e8-85fe-4cbd09439b3e.png)
