### ISSUE TITLE
Configure select domains to drop

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2048]
In ntopng/nEdge it is possible drop/mark traffic from specific sites (e.g. malware hosts) using configured list of sites. However a simple thing like block site X is not possible.

It is requested to implement in both ntopng/nEdge a list of domains to drop/alert (that will be handled via nDPI categories) that a user can configure though the web interfaces.

**Comment by emanuele-f** [comment]
Implemented in aa1ead94c4c168c57b353e8694bf2251b5fca0e2, but waiting for #2099 to work properly
