### ISSUE TITLE
Any port flow sorting

### ISSUE THREAD

**Issue by Eugene-Prokhorenko** [ntop/ntopng#2050]
Do you plan to add flow filtering by any chosen port? Needed if services are running on non-standard port.

**Comment by simonemainardi** [comment]
feature is already implemented.

Click on the port hyperlink of the flow:

![image](https://user-images.githubusercontent.com/3397663/45799952-8c10a580-bcaf-11e8-848c-6a7f22cce737.png)

and you'll be redirected to the page you are looking for

![image](https://user-images.githubusercontent.com/3397663/45799968-a0ed3900-bcaf-11e8-9271-f053ae745cad.png)
