### ISSUE TITLE
Troughput 0 bps and number of Flows anormally high after restart

### ISSUE THREAD

**Issue by engee974** [ntop/ntopng#2051]
Hello,
i encounter a big issue since i decide to upgrade the ntpng version.
I think the issue dissapears but after a restart i still have the problem

- No throughput
- Flows are anormally high > 1,000,000 usally between 150,000 and 400,000

I reinstall ntopng from debian package and still the same issue.
I flush redis : flushall and flushdb
I purge temp file from /var/lib/ntopng

No solution.
Are there other cache files or temporary content ?

The release of july was working perfectly. I Kept that version for 2 months without issues.

The startup line : ntopng --user "ntopng" --community --interface "bond1" --http-port "3000" --local-networks "172.16.0.0/15,172.21.0.0/16,10.101.0.0/16" --dns-mode "2" --sticky-hosts "none" --data-dir "/var/lib/ntopng" --disable-autologout --max-num-flows "5000000" --max-num-hosts "500000"

The Version : 3.6.180918 - Community Edition

I'm an ISP with 2Gbps max of thoughput to analyze.

**Comment by emanuele-f** [comment]
Follow up of #2004

**Comment by emanuele-f** [comment]
Please remove the `--sticky-hosts` from the command line. Moreover, try to lower the `Flow Idle Timeout` e.g. to 1 minute and double check in the flows view that any flow `Last Seen` "ago" value is not exceeding the `Flow Idle Timeout`

**Comment by engee974** [comment]
Hi,
Nothing changes
The new startup line : 
`ntopng --user "ntopng" --community --interface "bond1" --http-port "3000" --local-networks "1172.16.0.0/15,172.21.0.0/16,10.101.0.0/16" --dns-mode "2" --data-dir "/var/lib/ntopng" --disable-autologout --max-num-flows "5000000" --max-num-hosts "500000"`

The "Flow Idle Timeout" value has never changed and always been to default value : 1min

I reinstall all again, so the version installed  : 3.7.180921 - Community Edition
From the debian's package.

**Comment by engee974** [comment]
An example of flow 
![image](https://user-images.githubusercontent.com/5074983/45877015-84cfc180-bdad-11e8-891b-c3ec85557aaf.png)

**Comment by lucaderi** [comment]
@engee974 I believe I miss something. For instance in your screenshot you seem to have no traffic at all but you have over 1M flows. Can you please attach a screenshot of http://<your ntopng host>:3000/lua/admin/prefs.lua?tab=in_memory

**Comment by engee974** [comment]
This is the exact problem, i have traffic but not well processed
Here is the screenshot : 
![image](https://user-images.githubusercontent.com/5074983/45928958-6b20ac80-bf5c-11e8-872e-046dd0a2e48d.png)

**Comment by engee974** [comment]
could that issue be linked to the issue #2018 

I have a lot of dropped packets (after resetting all counters)
![image](https://user-images.githubusercontent.com/5074983/46020300-18c3c500-c0ef-11e8-8f1a-7104d2a08bbf.png)

**Comment by emanuele-f** [comment]
So almost all the traffic is dropped. Can you try to run ntopng on the physical interfaces rather than a bond? Do you still have packet drops?

**Comment by engee974** [comment]
OK i will try. 
For your information, it was working perfectly before the update. 
How can you explain that ?

**Comment by engee974** [comment]
I've changed all the configuration from my switch to the server
always 0 Bps and each physical interface has dropped packets
Eth2:
![image](https://user-images.githubusercontent.com/5074983/46078805-461f7a00-c1a6-11e8-8df6-d5fba589ff6e.png)

Eth3
![image](https://user-images.githubusercontent.com/5074983/46078843-62231b80-c1a6-11e8-8ae9-38c4a077c321.png)

**Comment by emanuele-f** [comment]
Can you check the output of ifconfig to see if the interface is dropping packets? What is the average traffic rate you are trying to monitor?

**Comment by engee974** [comment]
```
4: eth2: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 14:18:77:2a:31:e5 brd ff:ff:ff:ff:ff:ff
    RX: bytes  packets  errors  dropped overrun mcast   
    11863054396 16176014 0       3       0       99      
    TX: bytes  packets  errors  dropped carrier collsns 
    0          0        0       0       0       0       
5: eth3: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 14:18:77:2a:31:e6 brd ff:ff:ff:ff:ff:ff
    RX: bytes  packets  errors  dropped overrun mcast   
    15505026653 17148936 0       3       0       93      
    TX: bytes  packets  errors  dropped carrier collsns 
    0          0        0       0       0       0       

```

**Comment by engee974** [comment]
i also have dropped packets with tshark

**Comment by emanuele-f** [comment]
What is the expected traffic rate you are monitoring?

**Comment by engee974** [comment]
Maximum 2 Gbps
But in few months it will be over 2 Gbps

**Comment by emanuele-f** [comment]
Please note that standard drivers can only handle about 1Mpps. I suggest you to evaluate PF_RING ZC. Please check out https://www.ntop.org/ntopng/best-practices-for-running-ntopng/ and https://www.ntop.org/products/packet-capture/pf_ring/pf_ring-zc-zero-copy/

**Comment by engee974** [comment]
Thanks for the advice. I will consider it.
But don’t forget the initial issue : not working after an update.
It was working fine and now it not working fine at all. Something has changed between July and August and nobody knows what. It could be kernel, OS. The best would be to compile from source but from which branch ? What exactly ?

**Comment by emanuele-f** [comment]
The fact that you have drops with tshark too probably means that ntopng is not the source of the issue. Anyway, you can manually compile the old stable branch: https://github.com/ntop/ntopng/tree/3.4-stable . You will also need the old nDPI stable branch: https://github.com/ntop/nDPI/tree/2.2.2-stable

**Comment by engee974** [comment]
Good news for me the downgrade is working
Running ntopng 3.4-stable

![image](https://user-images.githubusercontent.com/5074983/46101011-e9d74d00-c1db-11e8-9b9c-e20f00010673.png)

**Comment by engee974** [comment]
lower amount of dropped packets too

![image](https://user-images.githubusercontent.com/5074983/46101377-ceb90d00-c1dc-11e8-8452-ec8fa92f6f9a.png)

**Comment by emanuele-f** [comment]
Ok, this is strange. The high packets drop could be linked to the high number of flows. It seems like old flows are not being removed from memory in the new version. Please add the `-v 3` option to your ntopng command line and perform a grep on the output for `Purging idle flows`. The full command line should be:

`ntopng --user "ntopng" --community --interface "bond1" --http-port "3000" --local-networks "1172.16.0.0/15,172.21.0.0/16,10.101.0.0/16" --dns-mode "2" --data-dir "/var/lib/ntopng" --disable-autologout --max-num-flows "5000000" --max-num-hosts "500000" -v3 | grep "Purging idle flows"`

After the number of active flows starts to dramatically increase, can you still see `Purging idle flows` in the output? Can you paste the command output here?

**Comment by engee974** [comment]
[ntopng-v.3.7.180927-verbose3.log](https://github.com/ntop/ntopng/files/2424430/ntopng-v.3.7.180927-verbose3.log)
[ntopng-v.3.4.180926-verbose3.log](https://github.com/ntop/ntopng/files/2424431/ntopng-v.3.4.180926-verbose3.log)

2 files to compare each version : 

- v.3.4.180926 working perfectly, i can restart ntopng without flushing redis
- v.3.7.180927 not working as expected : 0 bps for throughput, flows growing

**Comment by emanuele-f** [comment]
Can you please check if the following patch fixes the issue on the 3.7 version?
Please run `git apply flow_purge.txt` then compile again with `make`.

[flow_purge.txt](https://github.com/ntop/ntopng/files/2424836/flow_purge.txt)

**Comment by engee974** [comment]
The issue is not fixed... no change

[ntopng-v.3.7.180927_patched-verbose3.log](https://github.com/ntop/ntopng/files/2425530/ntopng-v.3.7.180927_patched-verbose3.log)

**Comment by emanuele-f** [comment]
Can you check out the latest ntopng version? Please ensure to remove the previously applied patch by running `git reset --hard` and then fetch the changes with the usual `git pull`. Any chance to get access to your machine to speed up debugging?

**Comment by engee974** [comment]
With the new version freshly compiled it's better.
Throughput seems OK
![image](https://user-images.githubusercontent.com/5074983/46199767-eac5c700-c320-11e8-8db7-409e3a14d664.png)

But the gauge at the bottom is more inconsistent than it is with the 3.4 version.
It's more "real time" with the previous version. 

For the moment, It will be difficult for me to give you a remote access to the server.
We use ntopng for troubleshooting our subscribers. 

We can operate together when the server is not used by the technical support team.

**Comment by engee974** [comment]
To illustrate the inconsistency of the gauge

![image](https://user-images.githubusercontent.com/5074983/46200704-5c9f1000-c323-11e8-933c-91ecd4fce68f.png)

**Comment by emanuele-f** [comment]
If you have more then 2 gbps traffic, you need to increase the interface speed.

![2018-09-28_11-46](https://user-images.githubusercontent.com/5488003/46201370-80eaf480-c303-11e8-96ad-b5bf182f554f.png)

Please let me know if the new version work well in the long term.

**Comment by engee974** [comment]
For the moment i have maximum 1.5Gbps traffic. That's why i said the gauge is inconsistent.
I will compare the 2 versions again to confirm or not the inconsistency.

I can give you a good feedback on tuesday next week.

**Comment by engee974** [comment]
Should i open a new issue for teh gauge inconsistency

3.4 stable version 
![image](https://user-images.githubusercontent.com/5074983/46203352-96bfe000-c32a-11e8-9930-97d2811714ff.png)
Gauge don't raise to 100%

3.7 dev version
![image](https://user-images.githubusercontent.com/5074983/46203510-1483eb80-c32b-11e8-93ec-3270c884f5ca.png)
4Gbps !!? on the graph

**Comment by engee974** [comment]
No need to wait tuesday.
That issue is fixed for me.
