### ISSUE TITLE
Any port flow sorting (reopened)

### ISSUE THREAD

**Issue by Eugene-Prokhorenko** [ntop/ntopng#2053]
My question was misunderstood. I want to be able to get all flows (implemented) and then - filter them to see only flows with any port (1234 for example) (not implemented).

**Comment by simonemainardi** [comment]
Do you mean filtering flows by port (*implemented* as also shown in the original https://github.com/ntop/ntopng/issues/2050 of this duplicate) or something else?

**Comment by Eugene-Prokhorenko** [comment]
Real situation:
I run some flow exporters on port xyz.
I want to see all traffic on port xyz.
xyz is NOT assigned to some application in ntopng :(

**Comment by simonemainardi** [comment]
if you want to create custom protocols associated to the port, you can do as explained in https://www.ntop.org/ndpi/configuring-ndpi-for-custom-protocol-detection/

see option

```
[--ndpi-protocols|-p] <file>.protos | Specify a nDPI protocol file
                                    | (eg. protos.txt)
```
