### ISSUE TITLE
VLAN fields

### ISSUE THREAD

**Issue by Eugene-Prokhorenko** [ntop/ntopng#2054]
What for are "VLAN" field? It's "0" everywhere, though my routers  (expoorters) has vlans.

**Comment by emanuele-f** [comment]
Hi, please specify what nprobe options you are using. Can you post a screenshot of the page showing the VLAN field?

**Comment by Eugene-Prokhorenko** [comment]
![ntopng](https://user-images.githubusercontent.com/33592455/45830203-b09b6a80-bd0d-11e8-96bf-22ba06620c3a.png)

somehow nprobe got options:
nprobe --collector-port 1234 --collector 127.0.0.1:2055 -V 9nprobe -i ens3 --zmq tcp://127.0.0.1:5556

**Comment by emanuele-f** [comment]
What's your SNMP device model?

**Comment by Eugene-Prokhorenko** [comment]
MikroTik CCR1036-12G-4S

**Comment by Eugene-Prokhorenko** [comment]
the same for other models

**Comment by emanuele-f** [comment]
Please check out that you are using the latest ntopng version. Run `ntopng -v` to get its version. Please note that some MikroTik devices lack proper SNMP support, so maybe the device is not reporting the VLAN correctly. Please try to run the following command from cli to verify this:
```
snmpwalk -c your_community your_mikrotik_ip -v2c 1.3.6.1.2.1.17.7.1.4.5.1.1.your_interface_idx
```
It should return the VLAN id, e.g. `SNMPv2-SMI::mib-2.17.7.1.4.5.1.1.57 = Gauge32: 86`

**Comment by Eugene-Prokhorenko** [comment]
3.7.180915 - Enterprise Edition

**Comment by Eugene-Prokhorenko** [comment]
snmpwalk -c xyz 93.187.x.y -v2c 1.3.6.1.2.1.17.7.1.4.5.1.1.19 SNMPv2-SMI::mib-2.17.7.1.4.5.1.1.19 = No Such Object available on this agent at this OID
