### ISSUE TITLE
Enhancement Request: More flexibility / documentation with variables in Grafana plugin

### ISSUE THREAD

**Issue by boisgada** [ntop/ntopng#2055]
The following enhancements would be useful in the variable definitions for the Grafana plugin:
- List of possible options in the variable query field
- Ability to use variables within the query field.  For example, the use of $interface to create a unique list of hosts for a given interface.  The ultimate goal would be to be able to have a dynamic dashboard where you could select datasource, interface and host (or wildcard any of the three) to generate a dashboard with dynamic pannels for each instance of the selected criteria.  For example: `$datasource=default, $interface=*, $host=1.1.1.*`.  
But would settle for a pulldown for each field.

- More documentation (or link to additional resources) for Grafana plugin options
- More documentation for the "Value groups/tags" fields

**Comment by simonemainardi** [comment]
please, use the plugin issue tracker: https://github.com/ntop/ntopng-grafana-datasource/issues
