### ISSUE TITLE
ntopng crashes shortly after starting on RHEL6, nprobe continues to run

### ISSUE THREAD

**Issue by craigers521** [ntop/ntopng#2056]
As stated in title, only stays up for a minute or two after starting service, nprobe continues to run without issue.  Only have a few routers sending netflow to collector for demo purposes before deciding to purchase license.  I have uploaded the core dump and binary.  Any help would be appreciated, this doesnt stay up long enough for me to evaluate whether i want to purchase or not.   Logs aren't giving me much but can provide logs and conf files if needed. Thanks! 

[ntop.zip](https://github.com/ntop/ntopng/files/2412668/ntop.zip)

**Comment by emanuele-f** [comment]
Hi, you have uploaded a bash script, not the ntopng binary. What ntopng version are you using? Please run `ntopng --version` and post the output here.

**Comment by craigers521** [comment]
Emanuele - sorry about that.  Re-uploaded correct file and output as requested: 

v.3.6.180921    [Enterprise/Professional build]
GIT rev:        3.6-stable:d48b092fc3874cf36fc5166560500140fa64f3ef:20180921
Pro rev:        r1855
Built on:       CentOS release 6.10 (Final)
System Id:      68931E9276066ACF
Platform:       x86_64
Edition:        Enterprise
License Type:   Permanent
Maintenance:    Until Fri Sep 13 08:37:37 2019 [352 days left]
License:        A9951A333595B401828200CA5A9D9542156838185718F6565F

[ntopng.bin.zip](https://github.com/ntop/ntopng/files/2417176/ntopng.bin.zip)

**Comment by cardigliano** [comment]
@craigers521 could you provide your ntopng configuration (file or command line)? Looking at the core dump, It seems that this is related to a hugepages memory allocation failure (are you using ZC?), due to an out of memory or similar. Based on your answer we will need more information to debug this. Thank you.

**Comment by craigers521** [comment]
Sure Cardigliano: 
[ntopng.conf.txt](https://github.com/ntop/ntopng/files/2420007/ntopng.conf.txt)

**Comment by cardigliano** [comment]
@craigers521 it seems you are not using zc drivers, however the core dump seems to be related to that, just to make sure: did you change the configuration perhaps? Could you try removing the network interface (--interface=eth1) from the configuration and use zmq only to see if it makes some difference? Thank you.

**Comment by craigers521** [comment]
[core-ntopng-7-99-99-6094-1537980300.zip](https://github.com/ntop/ntopng/files/2425851/core-ntopng-7-99-99-6094-1537980300.zip)

Commented out the --interface=eth1 line in the conf file and restarted service.  Still crashing after a few minutes...

**Comment by cardigliano** [comment]
(writing the stack trace of the latest core dump here to keep track of it)
#0  0x00000033b3a89791 in ?? ()
#1  0x00000000005e759e in rrd_write (rrd_file=0x7f5830000e90, buf=<value optimized out>, count=128) at rrd_open.c:719
#2  0x00000000005e1dbf in rrd_create_fn (file_name=0x41ce0bc0 "/var/tmp/ntopng/2/rrd/10/255/235/74/ICMP.rrd", rrd=0x7f58417fab00) at rrd_create.c:729
#3  0x00000000005e2fbc in rrd_create_r (filename=0x41ce0bc0 "/var/tmp/ntopng/2/rrd/10/255/235/74/ICMP.rrd", pdp_step=<value optimized out>, last_up=<value optimized out>, argc=5, argv=0x7f5830005940) at rrd_create.c:582
#4  0x00000000004b5362 in ntop_rrd_create (vm=0x41e8e378) at src/LuaEngine.cpp:4293
#5  0x00000000005a3c0a in lj_BC_FUNCC ()
#6  0x000000000059132d in lua_pcall ()
#7  0x00000000004bf9cd in LuaEngine::run_script (this=0x7f5830000c80, script_path=0x7f581c000960 "/usr/share/ntopng/scripts/callbacks/interface/5min.lua", iface=0xf93500) at src/LuaEngine.cpp:8074
#8  0x00000000005100bd in ThreadedActivity::runScript (this=0x530a560, script_path=0x7f581c000960 "/usr/share/ntopng/scripts/callbacks/interface/5min.lua", iface=0xf93500) at src/ThreadedActivity.cpp:178
#9  0x000000000050db4e in ThreadPool::run (this=0x530a5d0) at src/ThreadPool.cpp:101
#10 0x000000000050d7ac in doRun (ptr=0x530a5d0) at src/ThreadPool.cpp:37
#11 0x00000033b3e07aa1 in ?? ()
#12 0x00007f58417fb700 in ?? ()
#13 0x0000000000000000 in ?? ()

**Comment by cardigliano** [comment]
@craigers521 any chance you can provide us ssh access to this machine to speed up the debugging?

**Comment by craigers521** [comment]
cardigliano best i can do would be a screen share and give you remote control.  Want me to send you an invite? its a virtual machine, you think i have a resource constraint?

**Comment by emanuele-f** [comment]
@craigers521 please send me TeamViewer credentials at faranda@ntop.org

**Comment by emanuele-f** [comment]
@craigers521 any news?

**Comment by craigers521** [comment]
emanuele - apologies.  We don't use teamviewer at my company it would have to be a skype for business meeting and then i could do a screenshare.  I am in the central time zone in the U.S. What time zone are you in? Trying to sort out a time we are both available to set up a meeting request.  thanks.

**Comment by emanuele-f** [comment]
Hi, sorry but with skype it will be infeasable. I'm CEST timezone.

**Comment by simonemainardi** [comment]
@craigers521 sorry for the late reply. It's not strictly necessary to skype or teamviewer as you've already provided the dump that is providing good information, in fact. Thank you.

The crash points out a "Program terminated with signal 7, Bus error." during the creation of an rrd file. This suggests me it could be something related to the FS or the IO (e.g., a mmap on a file could raise a SIGBUS under some circumstances). Can you please check the FS? In particular, is there any free space available? Is the FS properly writeable?

Thank you.

**Comment by craigers521** [comment]
this is a RHEL virtual and FS is on a SAN, seems to have enough space unless ntop is storing somewhere i don't know about: 

Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/system-root
                      5.2G  1.5G  3.4G  31% /
tmpfs                 3.1G  8.2k  3.1G   1% /dev/shm
/dev/sda1             500M   80M  394M  17% /boot
/dev/mapper/system-home
                      1.1G  1.4M  969M   1% /home
/dev/mapper/system-opt
                      2.1G  332M  1.7G  18% /opt
/dev/mapper/system-tmp
                      2.1G   45M  1.9G   3% /tmp
/dev/mapper/system-var
                      3.2G  645M  2.3G  22% /var
/dev/mapper/sep-best1
                      4.1G  322M  3.6G   9% /opt/Best1
/dev/mapper/sep-jdk   5.2G   11M  4.9G   1% /opt/jdk
/dev/mapper/sep-central
                      106G  2.2G   99G   3% /opt/nncentral
/dev/mapper/sep-cauni
                      5.2G   69M  4.9G   2% /opt/CA
/dev/mapper/sep-simpana
                      4.1G  8.4M  3.9G   1% /opt/commvault
/dev/mapper/sep-splunk
                      2.1G  838M  1.2G  44% /opt/splunk

**Comment by simonemainardi** [comment]
Can you try and use a partition that is local to the VM for the ntopng data directory? You can use option -d.

I want to understand if writing to the SAN could cause the issue. Thanks.

**Comment by craigers521** [comment]
only have 500Mb of local space just for boot... the rest is all SAN.  It's all good guys, this was just a stopgap solution while we wait on budget money for another netflow product.  I appreciate you taking the time to try to help but i'm going to move on.
