### ISSUE TITLE
Invalid SNMP host search

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2058]
In the top right search field, if a MAC address is searched, the result returned is not correct. In fact if such MAC address is found on multiple ports
<img width="272" alt="screen shot 2018-09-25 at 10 50 29" src="https://user-images.githubusercontent.com/4493366/46003455-e09d9180-c0b0-11e8-82eb-7f16eff5f53b.png">
the only hit returned clicking on the name points to the trunk port and not to the port where such MAC address is located. Issues to be solved:
- In case of multiple matches are found, the search page should list all of them
- If the above request cannot be implemented, it is requested at least to return the best match that is the SNMP port where the computer is attached and not the trunk port where the computer have been learnt

**Comment by simonemainardi** [comment]
implemented

search has now been greatly improved as suggested to include:
- partial matches (e.g., mac addresses are searched also when typing a partial string such as 04:)
- multiple SNMP devices and ports (that is, matching results are shown for multiple SNMP devices)

All the SNMP devices and their ports are now listed in the search box so one can pick up any entry.

![image](https://user-images.githubusercontent.com/3397663/46351695-41e8d600-c658-11e8-84cf-1dd7e58ae637.png)
