### ISSUE TITLE
Windows - ntopng service should exit gracefully upon receiving stop signal

### ISSUE THREAD

**Issue by RHomie** [ntop/ntopng#206]
Right now, the process seems to be being aborted not giving it any chance to gracefully terminate packet pulling, logging interface statics, Flushing host contacts and cleaning up the interface in the end (All the things that command line instance does upon receiving ctrl+c).

**Comment by lucaderi** [comment]
@RHomie Can you please past a shutdown log of your ntopng?

**Comment by RHomie** [comment]
@lucaderi There is of course no shutdown log for ntopng service as it just gets aborted, the last line of log is simply the last line of normal operation. however, running ntopng in console mode and using ctrl+c , this is a sample shutdown log:
--------------------------------------------------------------
09/Oct/2015 07:53:58 [main.cpp:37] Shutting down...
09/Oct/2015 07:53:58 [PcapInterface.cpp:172] Terminated packet polling for NPF_{*EDITED*}
09/Oct/2015 07:54:00 [ProtoStats.cpp:35] [IPv4]  1.76 MB/3.58 K Packets
09/Oct/2015 07:54:00 [ProtoStats.cpp:35] [IPv6]  1.64 KB/11.00 Packets
09/Oct/2015 07:54:00 [ProtoStats.cpp:35] [ARP]   300 B/5.00 Packets
09/Oct/2015 07:54:00 [ProtoStats.cpp:35] [MPLS]  0 B/0.00 Packets
09/Oct/2015 07:54:00 [ProtoStats.cpp:35] [Other] 0 B/0.00 Packets
09/Oct/2015 07:54:00 [Ntop.cpp:1221] Interface NPF_{*EDITED*} [running: 0]
09/Oct/2015 07:54:00 [NetworkInterface.cpp:436] Flushing host contacts for interface NPF_{*EDITED*}
09/Oct/2015 07:54:00 [ActivityStats.cpp:86] Dumping activity C:\Users\Administrator\Documents\0\activities\15\10\09\192.168.0.19
09/Oct/2015 07:54:00 [ActivityStats.cpp:95] Written dump C:\Users\Administrator\Documents\0\activities\15\10\09\192.168.0.19
09/Oct/2015 07:54:00 [GenericHost.cpp:89] Dumping C:\Users\Administrator\Documents\0\activities\15\10\09\192.168.0.19
09/Oct/2015 07:54:00 [Host.cpp:72] Dumping serialization 192.168.0.19
09/Oct/2015 07:54:00 [Host.cpp:72] Dumping serialization 00:05:BF:E0:53:32
09/Oct/2015 07:54:00 [Host.cpp:72] Dumping serialization CB:AF:C5:13:89:E6
09/Oct/2015 07:54:00 [Host.cpp:72] Dumping serialization FF:FF:FF:FF:FF:FF
09/Oct/2015 07:54:00 [NetworkInterface.cpp:1420] Cleanup interface NPF_{*EDITED*}
--------------------------------------------------------------

Also, please do note that there is no "Ok I am leaving now" line at the end of it. this due to another bug ( https://github.com/ntop/ntopng/issues/205 ) which causes the application to crash at the very end.
