### ISSUE TITLE
Minute Interface Top Traffic Statistics are inconsistent

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2061]
The statistics always show the *interface top talkers*. When browsing a network or host pool view, this is inconsistent since a user would expect to see only the top talkers for the given network or host pool. Moreover, with the recent timeseries changes which implement zoom and timeseries tables, it would be more appropriate to display the top talkers for the highlighted time range rather the per-minute top talkers.

1. A minimal solution to remove the inconsistency is to only show the top talkers table on the interface graphs
2. A more elaborate solution requires dynamically computing the top talkers based on the currently shown graph page. E.g. on a host page, show all the top talkers relevant to the host, on the ASN page show the top talkers releveant for that ASN.
3. Such top talkers could be implemented in `nindex` if it's practical and efficient. This must be verified.

Solution 2 is very complex and could only be implemented in InfluxDB as iterating all the hosts RRDs is not feasable in large networks. Moreover, some queries are not trivial (e.g. how to filter hosts by ASN in InfluxDB? Here are some relevant links:

- Check IP belonging to Network subnet: https://github.com/influxdata/influxdb/issues/7852
- "IN" filter and alternatives: https://github.com/influxdata/influxdb/issues/2157

**Comment by emanuele-f** [comment]
Interface statistics will be dropped. Top clients and servers will be shown in the timeseries table below the chart as in the enterprise version.

**Comment by simonemainardi** [comment]
- top senders and top receivers will be shown in a table at the bottom of the chart and will be the top across the selected timeframe
