### ISSUE TITLE
Incorrect upload displays with mirroring port?

### ISSUE THREAD

**Issue by ShagoY** [ntop/ntopng#2062]
Hi,
I use ntopng on a VM connected directly to a mirroring port

After many tests with iperf, I noticed that Ntopng did not seem to detect the active flow in upload and only displayed the download.

For example, we can see that Ntopng detects a 62.90 Mbit/s usage but the active flow only displays the download part (2.51 Mbit/s):
![trouble-upload](https://user-images.githubusercontent.com/25367500/46024376-f4fc8100-c0e6-11e8-91d9-5d10ce3f2c2b.jpg) 

What could be causing this ?

Thank you in advance.

ntopng v.3.7.180923 (btw it's doesn't work with my licensed ntopng Professional/Embedded Edition v.3.7.180917)

> -m=192.168.1.0/24
-i=eth1
-w=3002
-l=1
-B=ip and not ip multicast and not ether broadcast and not port 3000
-n=1
--ignore-vlans

Edit : No Dropped Packets
Another screenshot :
![trouble-upload-02](https://user-images.githubusercontent.com/25367500/46024371-f168fa00-c0e6-11e8-80c5-f083fe428e6a.jpg)

**Comment by emanuele-f** [comment]
Can you send me a pcap of the interface traffic at faranda@ntop.org? Please check out https://www.ntop.org/guides/ntopng/advanced_features/live_pcap_download.html

**Comment by ShagoY** [comment]
After many tests with Emanuele (Thanks again!), It appears that the problem only occurs with the management of the mirroring port on Ubiquiti hardware.

Maybe the problem is related to the fact that Ntopng sees VLAN when I activate the port mirroring on my ubiquiti swtich while my network is not in VLAN. (See: https://github.com/ntop/ntopng/issues/1870).

**Comment by emanuele-f** [comment]
@ShagoY as explained via email, the VLAN tag is actually present in the network traffic, so this seems like a device configuration issue. Were you able to solve the issue?

**Comment by emanuele-f** [comment]
I'm closing the issue for now as the problem seems to be a device configuration issue. Please reopen if necessary.
