### ISSUE TITLE
License Validation

### ISSUE THREAD

**Issue by ffbarcelos** [ntop/ntopng#2063]
After upgrading from ntopng Pro (Small Business Edition) Linux (x64) educational version 3.5.180621 to 3.6.180924, the license is not working by modifying to the Community Edition version.
We have already executed the following commands and continue in the Community Edition:
ntopng --license-check
ntopng --online-license-check
how shall we proceed?

**Comment by emanuele-f** [comment]
Hi, the license may be expired. Please contact us privately by filling in the contact form: http://www.ntop.org/support/need-help-2/contact-us

**Comment by ffbarcelos** [comment]
I got in touch with the support and got a new license, but it did not work.

**Comment by emanuele-f** [comment]
Please contact us via email for license issues.

**Comment by ffbarcelos** [comment]
I got in touch with the support and got a new license.

Fabio,
it seems, that everything is fine, but as I’m not a technician, if you need assistance please file an issue on: http://github.com/ntop/ntopng/issues.

Thank you.
Best regards,
Maria

ntopng -V
v.3.6.180924    [Community build]
GIT rev:        :3.6.180924

**Comment by ffbarcelos** [comment]
ntopng --online-license-check
26/Sep/2018 08:18:36 [Ntop.cpp:1544] Setting local networks to 127.0.0.0/8
26/Sep/2018 08:18:36 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
26/Sep/2018 08:18:36 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
26/Sep/2018 08:18:38 [PcapInterface.cpp:91] Reading packets from interface enp5s0...
26/Sep/2018 08:18:38 [Ntop.cpp:1638] Registered interface enp5s0 [id: 0]
26/Sep/2018 08:18:39 [PcapInterface.cpp:91] Reading packets from interface lo...
26/Sep/2018 08:18:39 [Ntop.cpp:1638] Registered interface lo [id: 1]
26/Sep/2018 08:18:40 [PcapInterface.cpp:91] Reading packets from interface enp6s13f1...
26/Sep/2018 08:18:40 [Ntop.cpp:1638] Registered interface enp6s13f1 [id: 2]
26/Sep/2018 08:18:41 [PcapInterface.cpp:91] Reading packets from interface enp6s13f0...
26/Sep/2018 08:18:41 [Ntop.cpp:1638] Registered interface enp6s13f0 [id: 3]
26/Sep/2018 08:18:41 [main.cpp:298] PID stored in file /var/run/ntopng.pid
26/Sep/2018 08:18:41 [HTTPserver.cpp:1117] HTTP server listening on 3000
26/Sep/2018 08:18:41 [main.cpp:382] Working directory: /var/tmp/ntopng
26/Sep/2018 08:18:41 [main.cpp:384] Scripts/HTML pages directory: /usr/local/share/ntopng
26/Sep/2018 08:18:41 [Ntop.cpp:387] Welcome to ntopng x86_64 v.3.6.180924 - (C) 1998-18 ntop.org
26/Sep/2018 08:18:41 [Ntop.cpp:397] Built on Ubuntu 16.04.5 LTS
26/Sep/2018 08:18:41 [Ntop.cpp:695] Adding 127.0.0.1/32 as IPv4 interface address for lo
26/Sep/2018 08:18:41 [Ntop.cpp:703] Adding 127.0.0.0/8 as IPv4 local network for lo
26/Sep/2018 08:18:41 [PeriodicActivities.cpp:59] Started periodic activities loop...
26/Sep/2018 08:18:42 [PeriodicActivities.cpp:100] Each periodic activity script will use 4 threads
26/Sep/2018 08:18:42 [NetworkInterface.cpp:2505] Started packet polling on interface enp5s0 [id: 0]...
26/Sep/2018 08:18:42 [NetworkInterface.cpp:2505] Started packet polling on interface lo [id: 1]...
26/Sep/2018 08:18:42 [NetworkInterface.cpp:2505] Started packet polling on interface enp6s13f1 [id: 2]...
26/Sep/2018 08:18:42 [NetworkInterface.cpp:2505] Started packet polling on interface enp6s13f0 [id: 3]

...
 stop

**Comment by ffbarcelos** [comment]
ntopng not showing professional version.

**Comment by emanuele-f** [comment]
Please run `ntopng --version` to verify if the license is working. You don't need the `--online-license-check` since you have a new license now.

**Comment by ffbarcelos** [comment]
ntopng --version
v.3.6.180924    [Community build]
GIT rev:        :3.6.180924

**Comment by emanuele-f** [comment]
It seems like you are using the community version of ntopng from github. Have you installed ntopng from our repos? http://packages.ntop.org/

**Comment by ffbarcelos** [comment]
Yes, ntopng from github.

**Comment by ffbarcelos** [comment]
apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  libllvm5.0 linux-image-4.4.0-130-generic linux-image-extra-4.4.0-130-generic
Use 'apt autoremove' to remove them.
The following NEW packages will be installed:
  libllvm6.0 linux-image-4.4.0-135-generic linux-image-extra-4.4.0-135-generic
The following packages will be upgraded:
  apt-ntop-stable libegl1-mesa libgbm1 libgl1-mesa-dri libwayland-egl1-mesa linux-image-generic
6 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 6.592 B/79,2 MB of archives.
After this operation, 294 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://packages.ntop.org/apt-stable/16.04 all/ apt-ntop-stable 2.6-937 [6.592 B]
Err:1 http://packages.ntop.org/apt-stable/16.04 all/ apt-ntop-stable 2.6-937
  Writing more data than expected (6594 > 6592)
E: Failed to fetch http://packages.ntop.org/apt-stable/16.04/all/./apt-ntop-stable.deb  Writing more data than expected (6594 > 6592)

**Comment by ffbarcelos** [comment]
Repo broken

**Comment by rodrigues-as** [comment]
Regards,

To resolve the problem with of Hash Sum mismatch in the repository, run the following command:

echo 'Acquire::HTTP::Proxy::packages.ntop.org "DIRECT";' >> /etc/apt/apt.conf.d/03noproxy

Good luck solving your problem.
