### ISSUE TITLE
bad argument #2 to 'format' (no value)

### ISSUE THREAD

**Issue by Falseclock** [ntop/ntopng#2064]
URL: /lua/host_details.lua?ifid=0&host=192.168.1.213&page=config

```
HTTP/1.1 500 Internal server error Content-Type: text/html Connection: close   Script "/usr/local/share/ntopng/scripts/lua/host_details.lua" returned an error:
...al/share/ntopng/scripts/lua/modules/i18n/interpolate.lua:32: bad argument #2 to 'format' (no value)
```

![image](https://user-images.githubusercontent.com/3299139/46057214-4dc72a80-c176-11e8-90bd-5f2cbe185207.png)

**Comment by Falseclock** [comment]
![image](https://user-images.githubusercontent.com/3299139/46057480-90d5cd80-c177-11e8-8a9c-9d769c338e5b.png)

**Comment by emanuele-f** [comment]
Please update to the latest stable, version 3.6

**Comment by emanuele-f** [comment]
Closing the issue for now. Should you still experience the issue with the new stable, please reopen.
