### ISSUE TITLE
ntopng Enterprise:  Possible issue when selecting new interface

### ISSUE THREAD

**Issue by boisgada** [ntop/ntopng#2065]
When selecting a new interface from the 'Interfaces' drop down menu then selecting anything from the 'Hosts' menu, data for the previously selected interface shows up.

Work around:
- select desired interface from 'interfaces' drop down
- select anything from the 'hosts' drop down
- re-select the desired interface from the 'interfaces' drop down
- select desired option from the 'hosts' drop down will now contain data from the correct interface and the correct interface will show on the page footer

Setup:
ntopng server running on Ubuntu 18.04
twenty nprobe sensors (zmq pull method)
 
ntopng version:
# ntopng -V
v.3.7.180920    [Enterprise/Professional build]
GIT rev:        dev:02c5d729c6c0d8a115cd69fa35f1a8159f2ec35f:20180920
Pro rev:        r1915
Built on:       Ubuntu 18.04.1 LTS
System Id:      [removed]
Platform:       x86_64
Edition:        Enterprise
License Type:   Permanent

**Comment by lucaderi** [comment]
Using the 3.7.180927 I am unable to reproduce it. What I have done is the following. Starting from this setup

![screen shot 2018-09-26 at 20 22 54](https://user-images.githubusercontent.com/4493366/46100574-fce12180-c1c9-11e8-9250-fa1a02218ec8.png)

I select eth0, and then I select

![screen shot 2018-09-26 at 20 23 57](https://user-images.githubusercontent.com/4493366/46100637-1e420d80-c1ca-11e8-9717-b884478df9df.png)

All hosts (and the page footer) are from eth0, with no leftover from enp5s0. Can you explain how to reproduce it?

**Comment by boisgada** [comment]
Your steps are exactly how I explained.  I am no longer able to reproduce the issue.  

After reading your update I thought perhaps proxy cache may have been the culprit, but I tested two different proxies and I am not able to reproduce the issue. 

Thank you.

**Comment by emanuele-f** [comment]
Thank you for reporting
