### ISSUE TITLE
MySQL - Dropped Flows

### ISSUE THREAD

**Issue by a-pashkov** [ntop/ntopng#2067]
I have ipvsadm balanser server on centos 6.

Server forwards 100,000 established connections. I need to collect the statistics about them.

Ntopng executes dump-flows every five minutes, dump contein 400k records and I have 80-90% flow drops. 

I tried MySQL, ES and logstash to ram-disk backends on the same server.

How can I get statistic about lage number established sessions?

**Comment by lucaderi** [comment]
Are you talking about aggregated flows?

**Comment by a-pashkov** [comment]
I'm talking about flows from mysql table flowsv4

ntopng started with -F='mysql;localhost;ntopng;flows;ntopng;password'

I have lage number of persistent sessions information about which is dump every 5 minutes.

mysql> SELECT 
    ->   idx, 
    ->   inet_ntoa (CONV(HEX(IP_SRC_ADDR),16,10)) AS IP_SRC_ADDR, 
    ->   inet_ntoa (CONV(HEX(IP_DST_ADDR),16,10)) AS IP_DST_ADDR, 
    ->   LAST_SWITCHED-FIRST_SWITCHED AS Time 
    -> FROM flowsv4 
    -> WHERE 
    ->   INET_ATON('192.168.20.11') = IP_SRC_ADDR AND 
    ->   INET_ATON('192.168.20.1') = IP_DST_ADDR 
    -> LIMIT 10; 
+-----+---------------+--------------+------+
| idx | IP_SRC_ADDR   | IP_DST_ADDR  | Time |
+-----+---------------+--------------+------+
| 817 | 192.168.20.11 | 192.168.20.1 |  303 |
| 818 | 192.168.20.11 | 192.168.20.1 |  303 |
| 819 | 192.168.20.11 | 192.168.20.1 |  303 |
| 822 | 192.168.20.11 | 192.168.20.1 |  303 |
| 823 | 192.168.20.11 | 192.168.20.1 |  303 |
| 824 | 192.168.20.11 | 192.168.20.1 |  303 |
| 825 | 192.168.20.11 | 192.168.20.1 |  303 |
| 829 | 192.168.20.11 | 192.168.20.1 |  303 |
| 830 | 192.168.20.11 | 192.168.20.1 |  303 |
| 831 | 192.168.20.11 | 192.168.20.1 |  303 |
+-----+---------------+--------------+------+
10 rows in set (0.00 sec)

**Comment by emanuele-f** [comment]
Hi, please check out the following comment about MySQL performance and tuning: https://github.com/ntop/ntopng/issues/1672#issuecomment-383066165

**Comment by a-pashkov** [comment]
I tried to follow the recommendations from #1672 (comment). (increase key_buffer_size)

"insert" performance was about 2k flow/sec.

Persistent sessions statistics dump to database every 5 minutes. 

As I understand, the problem is that number of records (100k) is more than CONST_MAX_MYSQL_QUEUE_LEN.

**Comment by simonemainardi** [comment]
Currently 2k is the maximum number of flows MySQL can handle in the community/pro editions. You can reach 8-9k if you go with the Enterprise but MySQL will soon choke resulting in queries too slow to be useful.

You can browse also the older issues relative to MySQL but, to summarize, MySQL is not the choice when it comes to storing large volumes of flows. Our efforts are currently towards the development of  an high performance special-purpose database for flows and we won't be able to work on MySQL to make it more performant. In addition, experiments we've run, suggest us it won't be possible to push MySQL much more than this.

You may want to consider using nProbe with Kafka export (we have friends that are using it at 20k flows per second) but, again, you must be prepared to ingest all these Kafka messages in the backend and thy may involve setting up replicated/sharded databases on multiple nodes.
