### ISSUE TITLE
Improve scan detection alerts

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2068]
ntopng only monitors local hosts to detect scan attackers and victims. When an attacker tries to scan a single local host, an alert "local host x is under scan attack" is generated. However, if the attacker performs a scan against the whole local network (by sending packets to many hosts), it may remain undetected as per-host thresholds are not exceeded. The following improvements are probably needed:

1. When a local host is under attack, we want to know if the attacker is a specific remote host (in such case get its IP address) or many remote hosts
2. When a remote host performs a scan over a large network, we want to detect it as an attacker
3. Moreover, if the host is blacklisted, we need to reduce the number of generated flow alerts, otherwise we will flood the SQLite database with many alerts, one for every flow

**Comment by lucaderi** [comment]
The opposite is also true: trigger an alert when a host has more than X active flows regardless of its location (either local or remote)

**Comment by simonemainardi** [comment]
one possible solution requires:
- alert counters to be added to all hosts (how are only added to local hosts)
- then we could write a walker that only vists hosts with anomalies (local + remote). An extra walker is necessary as currently only local hosts are walked in lua
