### ISSUE TITLE
wireshark crash with pfring

### ISSUE THREAD

**Issue by pieronicoletti** [ntop/ntopng#207]
With Centos 7 distribution and pf_ring installed wireshark crash in graphic mode and do not capture traffic. Tshark do not start correctly and do not capture traffic.

With Ubuntu 14.04 LTS with pf_ring installed wireshark and tshark work fine, so the problem happen only with Centos 7.

Piero

**Comment by lucaderi** [comment]
This bug should be moved to PF_RING
