### ISSUE TITLE
Implement Alert Rearm for Flow Alerts (i.e. Alarm Rate Limiting)

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2070]
In case of attacks, ntopng will spend most of his time generating alerts for attackers. This causes a waterfall effect and thus the attack also (partially) breaks ntopng. 

It is requested to implement a "rearm" mechanism that prevents generating the same alarm over and over. Example in case of SYN scan attacker X, we cannot generate an alert per SYN-scanned host, but limit the number of generated alert per tuple <alarm type, attacker, victim> to a Y thresholds.

**Comment by simonemainardi** [comment]
Implemented using a leaky bucket. Thanks for pointing this issue out.
