### ISSUE TITLE
Live Traffic Download: VLAN and BPF

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2073]
In case a live traffic download is performed on a VLAN-tagged host, in case the BPF expression does not contain "vlan and ...." the filter never matches. It is requested to add a Javascript-Based alert that can inform the user of the problem before starting the download

**Comment by simonemainardi** [comment]
implemented.

Now a modal is shown before downloading a pcap for VLAN-tagged hosts, when a BPF specified. The modal is only shown when the host is tagged AND when a BPF is specified. In all the other cases no modal is shown and the download starts straight after the click on the 'pcap download' button.


![image](https://user-images.githubusercontent.com/3397663/46301847-c62f5080-c5a7-11e8-9ffe-f9781428dfd0.png)
