### ISSUE TITLE
Grafana module '/lua/modules/grafana/query.lua' returns internal error

### ISSUE THREAD

**Issue by boisgada** [ntop/ntopng#2075]
After updating, the Grafana query module returns the following error:
```
HTTP/1.1 500 Internal server error

Content-Type: text/html

Connection: close



<html><head><title>ntop</title></head><body><img src=/img/warning.png> Script &quot;/usr/share/ntopng/scripts/lua/modules/grafana/query.lua&quot; returned an error:
<p><H3>/usr/share/ntopng/scripts/lua/modules/grafana/query.lua:23: attempt to index field 'range' (a nil value)</H3></body></html>
```

'/lua/modules/grafana/search.lua' still works properly.

v.3.7.181001    [Enterprise/Professional build]
GIT rev:        dev:889729495e9133dbba2ef795ece476c50969ee10:20181001
Pro rev:        r1943
Built on:       Ubuntu 18.04.1 LTS
System Id:      [removed]
Platform:       x86_64
Edition:        Enterprise
License Type:   Permanent
Maintenance:    Until Thu Jul 25 07:42:40 2019 [297 days left]

**Comment by emanuele-f** [comment]
Which grafana version are you using?

**Comment by boisgada** [comment]
Grafana v5.3.0-beta1 (e05033a

**Comment by simonemainardi** [comment]
just tried to reproduce without issues. Everything works, searches and graphs are correctly populated.

```
simone@devel:~/grafana/grafana-5.3.0-beta2$ ./bin/grafana-server -v
Version 5.3.0-beta2 (commit: c6f7ae4)

[simone@develv5 ntopng]$ ./ntopng  --version
v.3.7.181002	[Enterprise/Professional build]
GIT rev:	dev:e7ddc7f17e59884450db56b041c1154719b3a02f:20181002
```

I would suggest to check the datasource configuration or stay with a stable grafana version such as this https://grafana.com/grafana/download/5.2.4

![image](https://user-images.githubusercontent.com/3397663/46355054-4a450f00-c660-11e8-8bbd-2972cd30e3cc.png)

**Comment by boisgada** [comment]
your feedback got me looking deeper...  research has shown the issue is related to the use of variables within grafana panels.  i also now realize i am pulling the beta repo of grafana instead of the stable version so when i updated, it is possible grafana was updated as well as ntopng.  i suspect you are correct and the issue may be with the grafana build rather than ntopng.

thank you for your support.

**Comment by boisgada** [comment]
Additional information.....

Eliminating grafana variables from the equation, I created a new dashboard.  When adding timeseries entries, four interface entries work (_traffic_bps, _traffic_total_bytes, _traffic_pps, and _traffic_total_packets); but when selecting either _allprotocols_bps or _allcatacories_bps, I receive an error.

The error message being returned is:
```
HTTP/1.1 500 Internal server error
Content-Type: text/html
Connection: close
<html>
  <head>
    <title>ntop</title>
  </head>
  <body>
    <img src=/img/warning.png>
    Script &quot;/usr/share/ntopng/scripts/lua/modules/grafana/query.lua&quot; returned an error:
    <p>
      <H3>/usr/share/ntopng/scripts/lua/modules/grafana_utils.lua:51: bad argument #1 to 'pairs' (table expected, got nil)</H3>
    </body>
  </html>
```

I apologize for the incorrect initial information.  I mistakenly looked in the wrong place for the error.

Please advise.

**Comment by simonemainardi** [comment]
Thanks for providing such detailed information. That helped in fixing the issue. A new build with the fix will be available tomorrow.
