### ISSUE TITLE
ntopng listen on random high udp ports

### ISSUE THREAD

**Issue by avi9526** [ntop/ntopng#2076]
Question:
ntopng is build using https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ntopng
run as systemctl service:
```
…
ExecStart=/usr/bin/ntopng \
        --disable-autologout \
        --disable-login=1 \
        --user=ntopng \
        --data-dir="/var/lib/ntopng/" \
        --local-networks="10.0.0.0/8,192.168.0.0/24,172.16.0.0/16" \
        --dns-mode=3 \
        --http-port=127.0.0.1:3000 \
        --http-prefix="/*****" \
        --redis="/var/run/redis-ntopng/redis.sock"
…
```
after starting I run 
`netstat -pntua | grep $(pidof ntopng)`
and get (sensitive information removed)
```
tcp        0      0 127.0.0.1:3000          0.0.0.0:*               LISTEN      8508/ntopng         
udp        0      0 ***********:37645       0.0.0.0:*                           8508/ntopng         
udp        0      0 ***********:57890       0.0.0.0:*                           8508/ntopng         
udp        0      0 0.0.0.0:59089           0.0.0.0:*                           8508/ntopng
```
What is the purpose of these listening UPD ports?

**Comment by simonemainardi** [comment]
those two upd sockets are open to perform multicast DNS  queries during active network discovery.

- Class MDNS: https://github.com/ntop/ntopng/blob/dev/src/MDNS.cpp#L35
- Network discovery in ntopng: https://www.ntop.org/ntopng/network-device-discovery-part-1-active-discovery/
