### ISSUE TITLE
Professional license not working

### ISSUE THREAD

**Issue by joelphilippage** [ntop/ntopng#2078]
I've seen other issues that are the same but I already contacted the sales team about my license not working and they said I need to file an issue.

After upgrading to ntopng 3.7 on Windows server, my license no longer works. Here are the logs:

`02/Oct/2018 14:11:37 [NtopPro.cpp:310] [LICENSE] Reading license from Redis
02/Oct/2018 14:11:37 [NtopPro.cpp:205] [LICENSE] { Correct License is here}: unable to validate Enterprise license [License mismatch error]
02/Oct/2018 14:11:37 [NtopPro.cpp:205] [LICENSE] { Correct License is here}: unable to validate Professional license [License mismatch error]
02/Oct/2018 14:11:37 [NtopPro.cpp:451] WARNING: [LICENSE] Invalid or missing license
02/Oct/2018 14:11:37 [NtopPro.cpp:468] WARNING: [LICENSE] ntopng will now run in enterprise edition for 10 minutes
02/Oct/2018 14:11:37 [NtopPro.cpp:470] WARNING: [LICENSE] before returning to community mode
02/Oct/2018 14:11:37 [NtopPro.cpp:472] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
02/Oct/2018 14:11:37 [NtopPro.cpp:474] WARNING: [LICENSE] or run ntopng in community mode starting
02/Oct/2018 14:11:37 [NtopPro.cpp:475] WARNING: [LICENSE] ntopng --community`

Thanks!

**Comment by simonemainardi** [comment]
Has your license key been generated more than one year ago? It that is the case, then the license may be expired.

Try this:

- open a windows terminal (hit search -> then cmd -> run as administrator)
- go to the ntopng installation directory to reach the ntopng.exe executable
- run ntopng /c --check-license
- run ntopng /c --check-maintenance

report the output of the latest two commands.

**Comment by joelphilippage** [comment]
I received my current license April 17, 2018. Here is the result of running those two commands:

C:\Users\Administrator>ntopng /c --check-license
Starting ntopng
Running ntopng.
Invalid license

C:\Users\Administrator>ntopng /c --check-maintenance
Starting ntopng
Running ntopng.
Invalid license

**Comment by simonemainardi** [comment]
Please, send me the order id associated with the license purchase, the license, the output of ntopng --version, and a screenshot of the "About ntopng". my email is mainardi ntop org

**Comment by simonemainardi** [comment]
Thanks for providing the information. The output of ntopng --version and the screenshot of page About ntopng are missing. Please send them as well.

**Comment by simonemainardi** [comment]
Following up via email directly. Seems to be a glitch affecting a small number of old licenses generated with lower-case hex letters.

**Comment by tonypang1228** [comment]
Similar situation here. I'm running a Enterprise license but the Enterprise lic fallen back to community after a couple of minutes but license check is ok:
PS C:\Program Files\ntopng> .\ntopng.exe /c --check-license
Starting ntopng
Running ntopng.
License Ok

There was a timer counting down the license expiry date. My license is just newly generated.
