### ISSUE TITLE
Enhancement Request:  Additional supported 'target' options within lua/modules/grafana/search.lua

### ISSUE THREAD

**Issue by boisgada** [ntop/ntopng#2082]
The grafana search module supports a simple 'interface' query parameter.  It would be nice if it also supported wildcards and/or a simple 'host' target query option.

Use case:  Creating a 'host' variable which parses the query output for use within dynamic panels.  This is easy with interface variables:
```
Query: interface
Regex: /(interface_[a-zA-Z0-9:\\/\\.]*)_.*/
```

Then the variable [[interface_var]] can be used in the 'Repeat for each value of' section of the panel general tab.  For hosts, you must enter 'host_1.2.3.4' which limits the usefulness of the variable and dynamic panels.

**Comment by simonemainardi** [comment]
Currently, we have implemented influxdb support and we could drop the ntopng grafana datasource in favour of the influxdb one. For this reason I am putting this issue on hold.

An ntopng user who choses to use influxdb to store the timeseries will automatically benefit from the influxdb datasource http://docs.grafana.org/features/datasources/influxdb/ to access all the existing ntopng-generated timeseries.

See https://github.com/ntop/ntopng/blob/dev/doc/README.influxdb if you want to try and use influxdb.

**Comment by boisgada** [comment]
Thank you for the information.  Does this also work for ZMQ pull connected nprobe interfaces?

**Comment by simonemainardi** [comment]
Data export to influxdb will support any kind on interface. ZMQ support will be guaranteed.

**Comment by gianogli** [comment]
> An ntopng user who choses to use influxdb to store the timeseries will automatically benefit from the influxdb datasource http://docs.grafana.org/features/datasources/influxdb/ to access all the existing ntopng-generated timeseries.

Could you send us some examples (screenshots) of queries we have to configure in grafana to show the "iface:ndpi" or "host:traffic" (by InfluxDB) graphs as they are already shown into ntopng interface?
I've just tried but I can see only cumulative data graphs that are growing up indefinitely or that are constant indefinitely...

![screenshot_20181005_113836](https://user-images.githubusercontent.com/14093378/46528131-4ea53e00-c893-11e8-93d4-c7d7e2fcda22.png)
![screenshot_20181005_113714](https://user-images.githubusercontent.com/14093378/46528138-54028880-c893-11e8-8fe1-4159d1b9d019.png)

![screenshot_20181005_114216](https://user-images.githubusercontent.com/14093378/46528294-cf643a00-c893-11e8-94c1-c499ad667785.png)
![screenshot_20181005_114358](https://user-images.githubusercontent.com/14093378/46528451-236f1e80-c894-11e8-9ae5-3d6a1208a502.png)

Thanks.

**Comment by emanuele-f** [comment]
Hi, the traffic data type is "counter", meaning that cumulative values are stored. In order to get the instantaneous value, you should apply a `NON_NEGATIVE_DERIVATIVE` function on the value. Moreover, if the value is in bytes, you will have to multiply by 8 to get bps

**Comment by gianogli** [comment]
Thanks Emanuele... :-)

I've just tried with the `NON_NEGATIVE_DERIVATIVE` but I think that something doesn't work as expected.
This is the graph built using "ntopng-grafana-datasource":
![screenshot_20181009_150853](https://user-images.githubusercontent.com/14093378/46671732-cb0e8880-cbd5-11e8-9b4d-2b16abb37365.png)

This is the same graph built using directly the InfluxFB data...
![screenshot_20181009_150929](https://user-images.githubusercontent.com/14093378/46671776-e7122a00-cbd5-11e8-8149-230238519385.png)

The X values are inconsistent ad the graph is not "smooth" as the previous one: it's seems made with a lot of vertical lines...

What do you think?

Thanks...

**Comment by emanuele-f** [comment]
Can you post the exact query you are using?

**Comment by gianogli** [comment]
The query is in the bottom part of the second graph. :-)

The query of the first graph is:
![screenshot_20181009_170715](https://user-images.githubusercontent.com/14093378/46678941-16c92e00-cbe6-11e8-9494-146ce1a908d8.png)

**Comment by emanuele-f** [comment]
can you remove the 10s in the non negative derivative? Or replace it with 1s?

**Comment by gianogli** [comment]
Here new test with "1s" in the non negative derivative:
![screenshot_20181010_104051](https://user-images.githubusercontent.com/14093378/46723908-3b221a80-cc79-11e8-9686-28a06a7023f0.png)
The X-axis unit was a my fault, sorry...
This is instead the standard "ntopng-grafana-datasource" graph:
![screenshot_20181010_103621](https://user-images.githubusercontent.com/14093378/46724037-79b7d500-cc79-11e8-9808-a2267c5841d9.png)

The hole you see in the right is due by a software update of the server we are using to run ntopng. Now we are also using the last stable version available: ntopng x86_64 v.3.6.181009

Thanks...

**Comment by emanuele-f** [comment]
this could be a sampling issue. Can you please open a new github issue?

**Comment by gianogli** [comment]
Ok, you are right! I will open a new github issue in the next hours. Thanks. :-)

**Comment by gianogli** [comment]
Done... ;-)
https://github.com/ntop/ntopng/issues/2096
