### ISSUE TITLE
[RaspberryPI] Anomalous termination when open "Traffic Report" tab

### ISSUE THREAD

**Issue by ShagoY** [ntop/ntopng#2087]
Hi,

Version : 3.7.181002 - Professional/Embedded Edition
Built on : Raspbian GNU/Linux 9.1 (stretch)
ntopng.conf : ntopng --ndpi-protocols "/etc/ntopng/protocol.txt" --local-networks "192.168.1.0/24" --interface "eth0" --http-port "3000" --dns-mode "1"

When I open the tab "Traffic Report", ntopng crash systematically.
If I insist (F5), the diagram appears after a while and multiple crash.

I made a coredump, where can I send it to you?

Regards.

**Comment by simonemainardi** [comment]
Duplicate of #2079. Should already be fixed. A new rpi build is in progress.Please hold on a couple of hours and try again. Otherwise follow up at #2079
