### ISSUE TITLE
Nprobe to Mariadb

### ISSUE THREAD

**Issue by ListenNjoy** [ntop/ntopng#2090]
I am having problem to get nProbe to write to MariaDB 10.3 database.
MariaDB IP-address: 192.168.15.22
NtopNG IP-adress: 192.168.15.21
NProbe IP-adress: 192.168.15.20
 
Nprobe.conf
-i=none
-n=none
-3="2055"
-V="10"
-L="77.244.0.0/20,185.212.24.0/22"
zmq="tcp://*:5556"
-T="@NTOPNG@"
--mysql="192.168.15.22;ntopng;nf;ntopng;*******"
Ntopng.conf
# -F "mysql-nprobe;192.168.15.22;ntopng;nf;ntopng;*******"
 
 
If I let Ntopng write to the database it work instantly but not with nProbe.
 
Ntopng.conf
-F "mysql;192.168.15.22;ntopng;flows;ntopng;*******"

**Comment by simonemainardi** [comment]
please, use the nProbe issue tracker is you are experiencing issues with nProbe.

As you said you are having troubles, also report the logs of nProbe that could contain potential errors.
