### ISSUE TITLE
Missing data cleanup after pcap analysis

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2092]
If ntopng is started as -i <pcap file> ntopng creates a new network interface, dumps preferences and files under /var/lib/ntopng/. This pollutes the system as it leaves a lot of un-necessary data. 

If not possible to do in another way (e.g. avoid dumping data at all for pcaps) it is requested to modify ntopng to **only if started with -i *pcap file>**
- ignore the -F flag
- during ntopng shutdown remove all the files created under /var/lib/ntopng/<iface id>
- clean redis from every data belonging to this temporary networks interfaces

**Comment by simonemainardi** [comment]
Implemented in https://github.com/ntop/ntopng/commit/f30e042cfc31ccabbd87fd90692244d0120a82f9

The cleanup is performed during the next ntopng restart. This is to preserve the pattern already used to delete data for inactive and active interfaces.

The -F pattern hasn't been removed as one can decide to dump flows to database even if they come from pcap file.
