### ISSUE TITLE
[feature request] support influxdb relays

### ISSUE THREAD

**Issue by jensenja** [ntop/ntopng#2094]
Hi,

I use influx relays within my infrastructure - this basically splits a single write to two different influxd hosts simultaneously, so I have data redundancy. It would be helpful if ntopng could separate out the host/port for reading and host/port for writing, and disable (or at least augment) the influxd version check for writing so that a relay could be used. When I tried to specify my influx relay port, the version check would not allow me to add the relay. Relays are only used at the write level, not the read level, so the local influxd instance could still be used for reading the timeseries data.

**Comment by emanuele-f** [comment]
Hi, is this the architecture you are using? https://github.com/influxdata/influxdb-relay#description
If so, you should be able to specify the load balancer address in the ntopng preferences, so that we can avoid adding a new field to the preferences. If this is ok, the only problem is the version check?

**Comment by jensenja** [comment]
Hi @emanuele-f 

Yes and no. I'm not running a load balancer - I'm simply running the relay process on each of my influx nodes and pointing all writes to `9096` on each node (depending on geographic location), so that any datapoint written to one node is also written to the other. The relay only cares about the `/write` endpoint and not the `/query` endpoint, so I didn't see the need to add in a load balancing layer because I'm always running queries to the geographically closest node anyway. I suppose I could add in `haproxy` to allow for splitting the reads and writes up per the documentation you linked, but I'm lazy. ;-)

re: the version check, here's what the relay will return vs. an actual influxdb instance:

```
jjensen@la1-netops-netmon-01:~$ curl -sL -I localhost:9096/ping
HTTP/1.1 204 No Content
X-Influxdb-Version: relay
Date: Thu, 11 Oct 2018 12:48:16 GMT

jjensen@la1-netops-netmon-01:~$ curl -sL -I localhost:8086/ping
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: f1db250b-cd53-11e8-962a-000000000000
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.6.3
X-Request-Id: f1db250b-cd53-11e8-962a-000000000000
Date: Thu, 11 Oct 2018 12:48:25 GMT

jjensen@la1-netops-netmon-01:~$
```

However I'd guess that if an LB is in the path and is directing `/ping` (which is what I'm assuming you're using for the version check) to the influxdb servers directly then altering the version check may be moot as well.

**Comment by jensenja** [comment]
One other issue that would definitely need to be addressed in order to support relays would be ntopng's method of interacting with influx in order to use it as a timeseries backend. Since DB creation and alterations require the use of the `/query` endpoint, when using a relay all databases must be created beforehand. Ntopng appears to require the use of an admin user since it makes calls to create the database when influx is specified as the timeseries backend. This would need to be altered in some way since the DB would need to be created before it can be used with a relay architecture.

Also most applications that support writing to influx allow for specifying the retention policy for which to write datapoints. Ntopng doesn't really do this, and the RP appears to be specified with the "InfluxDB Storage" field under Preferences and is (I'm assuming) only used when the database is initially created.

Rather than have ntop create the database I think it makes more sense to just be able to tell ntop which database to write to and at which retention policy, so that way the end user doesn't need to have influx admin credentials in the clear under the preferences page.

**Comment by emanuele-f** [comment]
Please consider that most users just want to turn on InfluxDB without worrying about initialization or configuration stuff. This is why we create the database and set the retention policy from the gui. Nevertheless, before creating the database, we check if that already exists, and in that case we do not create it again. Non-admin users are already handled in the latest ntopng dev version.

Since your setup is not standard (load balancer is the official way to do this), I think that the only fix here is to skip the version check if the returned version is "relay"

**Comment by jensenja** [comment]
> Please consider that most users just want to turn on InfluxDB without worrying about initialization or configuration stuff.

I'd think that it should be safe to assume that users that want to use influx as the backend should already have a basic understanding of how influx works - retention policies aren't exactly an advanced feature.

> Nevertheless, before creating the database, we check if that already exists, and in that case we do not create it again.

Good to know, thank you.

> Since your setup is not standard (load balancer is the official way to do this), I think that the only fix here is to skip the version check if the returned version is "relay"

So again I don't really think this is necessary if the LB is configured to route requests to `/ping` (which you're using in influxdb.lua in `getInfluxdbVersion()`) to the influxdb nodes themselves instead of the relays.

**Comment by emanuele-f** [comment]
To summarize, the changes you've requested are very specific to your use case. If other people find this useful we can reconsider this, but for now I close the issue. Please consider manually editing the https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/timeseries/drivers/influxdb.lua#L321 script to handle your use case. If you have other suggestions, please update this issue.
