### ISSUE TITLE
Strange Grafana graphs by using directly the InfluxDB data

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#2096]
This is the graph built using "ntopng-grafana-datasource":
![screenshot_20181010_103621](https://user-images.githubusercontent.com/14093378/46794730-c1596200-cd48-11e8-95d3-cb3a9989990d.png)

This is the same graph built using directly the InfluxFB data:
![screenshot_20181010_104051](https://user-images.githubusercontent.com/14093378/46794771-d7672280-cd48-11e8-81b9-9a594398053e.png)
... that is not "smooth" than the first one.

How can we modify the query to have a better result?

I'm using ntopng x86_64 v.3.6.181009, grafan 5.2.4, and InfluxDB 1.6.3

Thanks...

**Comment by emanuele-f** [comment]
The grafana export is limited to 600 points. When the number of points is higher, they are sampled. This is why the grafana graph is smoother. But the the graph from influxdb actually shows two data series (I see two shades of green), whereas the interface traffic is only one series. Can you explain this?

**Comment by gianogli** [comment]
The graph from InfluxDB is made by using one data series only. The 2 colors are due by the "fill" option of the "Display" tab. Here the same graph with the "fill" field set to 10:
![screenshot_20181012_101607](https://user-images.githubusercontent.com/14093378/46856866-e52fad00-ce07-11e8-97c3-f3b4582852ed.png)

> The grafana export is limited to 600 points.

Ok, I think this is the main difference of the 2 graphs. Do you know if there is a way to limit the number of point used also from InfluxDB?
This option could be useful when you have graphs like this one (ntopng-grafana-datasource):
![screenshot_20181012_105915](https://user-images.githubusercontent.com/14093378/46860315-74d95980-ce10-11e8-9d64-e887265e99c4.png)
That is made by using data from different data series (different interfaces)...
By using InfluxDB-datasource we have:
![screenshot_20181012_105934](https://user-images.githubusercontent.com/14093378/46860425-b5d16e00-ce10-11e8-9c25-98be1efc4087.png)
My server take more time to draw the graph and, in my opinion, is less clear to understand  what happens in my network.

I just discovered another problem... If I click over a data in the legend of the ntopng-grafana-datasource graph I can filter it inside the graph:
![screenshot_20181012_113946](https://user-images.githubusercontent.com/14093378/46861973-2cbc3600-ce14-11e8-99cd-199987ef74e8.png)
By using InfluxDB this kind of filter doesn't work anymore.

What do you think?

Thanks...

**Comment by emanuele-f** [comment]
For the sampling you can use `SELECT mean(bytes) as bytes FROM ... GROUP BY time(aggregation_interval)` where aggregation_interval is calculated accordingly (time_interval / max_point). You would need a subquery to apply it on the derivative. Please look at the driver implementation for more details: https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/timeseries/drivers/influxdb.lua . For the filter issue, this is not related to ntopng as you are directly quering from influx.

By the way, have you looked at the new ntopng pro charts features? Do you use grafana for some particular reason or you still prefer grafana charts over the ntopng ones?

**Comment by gianogli** [comment]
> For the sampling you can use `SELECT mean(bytes) as bytes FROM ... GROUP BY time(aggregation_interval)` where aggregation_interval is calculated accordingly (time_interval / max_point). You would need a subquery to apply it on the derivative. Please look at the driver implementation for more details: https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/timeseries/drivers/influxdb.lua .

Yes, it works! Great!!!
These are the 2 query I'm using now:
![screenshot_20181015_145553](https://user-images.githubusercontent.com/14093378/46952257-a3626900-d08a-11e8-8410-06e7d12fdb4d.png)
![screenshot_20181015_145615](https://user-images.githubusercontent.com/14093378/46952262-a65d5980-d08a-11e8-8973-eb9066ad4eb9.png)
And now...
![screenshot_20181015_153056](https://user-images.githubusercontent.com/14093378/46953887-5df46a80-d08f-11e8-8c5a-55952c2e5c12.png)


> For the filter issue, this is not related to ntopng as you are directly quering from influx.

Yes, sure!

> By the way, have you looked at the new ntopng pro charts features? Do you use grafana for some particular reason or you still prefer grafana charts over the ntopng ones?

I think that the new ntopng graphs are better than the grafana ones.
On ntopng, however,  I can't create a dedicated web dashboard (automatically updated) with more than 1 graph:  by using grafana (or chronograf, I've to test it!), instead, is very simple create personalized dashboards for my boss or for my colleagues where they can easily verify if there are some issue in our networks.

**Comment by emanuele-f** [comment]
Thank you for your feedback! Dynamic charts is something we miss right now but we want to implement. This could also be relevant for issue #1670 .
