### ISSUE TITLE
ntopng service keeps stopping

### ISSUE THREAD

**Issue by mdrodman** [ntop/ntopng#2098]
It runs for a while then stops.  Here is what it has in the Wndows application log.

Faulting application name: ntopng.exe, version: 0.0.0.0, time stamp: 0x5b7cfe44
Faulting module name: ntdll.dll, version: 6.1.7601.24094, time stamp: 0x5abee643
Exception code: 0xc0000005
Fault offset: 0x000000000002a1c5
Faulting process id: 0x1914
Faulting application start time: 0x01d46171f1f6236a
Faulting application path: C:\Program Files\ntopng\ntopng.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: a0ae122d-cd65-11e8-8192-005056a64b06

**Comment by emanuele-f** [comment]
Possibly duplicate of #1980 . Can you provide a stack trace as explained in https://github.com/ntop/ntopng/blob/dev/doc/README.crash#L19 ?

**Comment by mdrodman** [comment]
[trace.TXT](https://github.com/ntop/ntopng/files/2470216/trace.TXT)

**Comment by emanuele-f** [comment]
Thank you. What ntopng version are you using?

**Comment by mdrodman** [comment]
Hi,

3.6.180822 Professional Edition

**Comment by mdrodman** [comment]
I will upgrade to the latest version and let you know if it fixes the problem or not.

**Comment by mdrodman** [comment]
[trace_37.TXT](https://github.com/ntop/ntopng/files/2473499/trace_37.TXT)

**Comment by mdrodman** [comment]
The upgrade to 3.7 did not fix the issue. I included the trace.

**Comment by emanuele-f** [comment]
Thank you for the information.

**Comment by lucaderi** [comment]
@mdrodman The trace you sent me does not help. Can you please explain *exactly* how to reproduce the problem including
- the command line to use
- if there is something in the web interface that causes ntopng to shut down
- if you see something in the ntopng log file prior to experience the crash

**Comment by mdrodman** [comment]
I click start, run.  I type services.msc.  I then right click on ntopng and click start.  After about 3 minutes the service stops.
  *   the command line to use – Not sure what you mean by that.  Its windows.
  *   if there is something in the web interface that causes ntopng to shut down- I am not using the web interface when the service stops.
  *   if you see something in the ntopng log file prior to experience the crash-  What ntopng log are you referring to?

**Comment by lucaderi** [comment]
Please start from cmd.exe 

ntopng /c ... <any parameter you are using>

and attach to this ticket all the log messages you see on cmd.exe

**Comment by mdrodman** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.



C:\Program Files\ntopng>ntopng /c
Starting ntopng
Running ntopng.
17/Oct/2018 08:40:31 [Ntop.cpp:1545] Setting local networks to 127.0.0.0/8
17/Oct/2018 08:40:31 [Redis.cpp:132] Successfully connected to redis 127.0.0.1@0

17/Oct/2018 08:40:31 [Redis.cpp:132] Successfully connected to redis 127.0.0.1@0

17/Oct/2018 08:40:31 [NtopPro.cpp:310] [LICENSE] Reading license from Redis
17/Oct/2018 08:40:31 [NtopPro.cpp:205] [LICENSE] 5A253329E7D65DB254
B1566913908F924FF85: unable to validate Enterprise license [License mismatch err
or]
17/Oct/2018 08:40:31 [NtopPro.cpp:208] [LICENSE] D8A5A253329E7D65DB254
B1566913908F924FF85: found valid Professional license
17/Oct/2018 08:40:33 [PcapInterface.cpp:91] Reading packets from interface {FD2D
7296-E337-45EC-8C8D-0A50E9796AF3}...
17/Oct/2018 08:40:33 [Ntop.cpp:1639] Registered interface {FD2D7296-E337-45EC-8C
8D-0A50E9796AF3} [id: 4]
17/Oct/2018 08:40:33 [PcapInterface.cpp:91] Reading packets from interface {2105
82D1-46A4-4F77-A202-6B4EA8731EBD}...
17/Oct/2018 08:40:33 [Ntop.cpp:1639] Registered interface {210582D1-46A4-4F77-A2
02-6B4EA8731EBD} [id: 5]
17/Oct/2018 08:40:34 [HTTPserver.cpp:945] HTTPS Disabled: missing SSL certificat
e C:\Program Files\ntopng\httpdocs/ssl/ntopng-cert.pem
17/Oct/2018 08:40:34 [HTTPserver.cpp:947] Please read https://github.com/ntop/nt
opng/blob/dev/doc/README.SSL if you want to enable SSL.
17/Oct/2018 08:40:34 [HTTPserver.cpp:1114] Web server dirs [C:\Program Files\nto
png\httpdocs][C:\Program Files\ntopng\scripts]
17/Oct/2018 08:40:34 [HTTPserver.cpp:1117] HTTP server listening on 3000
17/Oct/2018 08:40:34 [main.cpp:393] Working directory: C:\Users\rod\Documen
ts\ntopng
17/Oct/2018 08:40:34 [main.cpp:395] Scripts/HTML pages directory: C:\Program Fil
es\ntopng
17/Oct/2018 08:40:34 [Ntop.cpp:390] Welcome to ntopng x64 v.3.7.180929 - (C) 199
8-18 ntop.org
17/Oct/2018 08:40:34 [Ntop.cpp:400] Built on Windows
17/Oct/2018 08:40:34 [NtopPro.cpp:633] [LICENSE] System Id:     3031755599-82072
B23
17/Oct/2018 08:40:34 [NtopPro.cpp:634] [LICENSE] Edition:       Professional
17/Oct/2018 08:40:34 [NtopPro.cpp:635] [LICENSE] License Type:  Permanent Licens
e
17/Oct/2018 08:40:34 [NtopPro.cpp:638] [LICENSE] License:       D6C1876D47D8A5A2
53329E7D65DB254B1566913908F924FF85
17/Oct/2018 08:40:34 [NtopPro.cpp:648] [LICENSE] Maintenance:   Until Tue Aug 27
 08:51:48 2019 [314 days left]
17/Oct/2018 08:40:34 [Ntop.cpp:626] Adding 112.1.0.0/16 as IPv4 local network fo
r
17/Oct/2018 08:40:34 [Ntop.cpp:632] Adding 112.1.10.69/32 as IPv4 interface addr
ess for {210582D1-46A4-4F77-A202-6B4EA8731EBD}
17/Oct/2018 08:40:35 [PeriodicActivities.cpp:68] Started periodic activities loo
p...
17/Oct/2018 08:40:35 [Utils.cpp:2548] ERROR: Error parsing IPv4 <HEAD><TITLE>Aut
horizationRequired<
17/Oct/2018 08:40:35 [Utils.cpp:2548] ERROR: Error parsing IPv4 <BODYBGCOLOR="wh
ite"FGCOLOR="black"><H1>AuthorizationRequired<
17/Oct/2018 08:40:35 [Utils.cpp:2548] ERROR: Error parsing IPv4 <FONTFACE="Helve
tica
17/Oct/2018 08:40:35 [Utils.cpp:2548] ERROR: Error parsing IPv4 Arial"><B>
17/Oct/2018 08:40:35 [Utils.cpp:2526] ERROR: Error parsing IPv6 Description:Auth
orizationisrequiredforaccesstothisproxy<
17/Oct/2018 08:40:35 [Utils.cpp:2548] ERROR: Error parsing IPv4 <HR>
17/Oct/2018 08:40:35 [Utils.cpp:2548] ERROR: Error parsing IPv4 
17/Oct/2018 08:40:35 [Utils.cpp:2548] ERROR: Error parsing IPv4 <
17/Oct/2018 08:40:35 [PeriodicActivities.cpp:109] Each periodic activity script
will use 2 threads
17/Oct/2018 08:40:35 [NetworkInterface.cpp:2581] Started packet polling on inter
face {FD2D7296-E337-45EC-8C8D-0A50E9796AF3} [id: 4]...
17/Oct/2018 08:40:35 [NetworkInterface.cpp:2581] Started packet polling on inter
face {210582D1-46A4-4F77-A202-6B4EA8731EBD} [id: 5]...
17/Oct/2018 08:40:35 [Utils.cpp:2548] ERROR: Error parsing IPv4 <HEAD><TITLE>Aut
horizationRequired<
17/Oct/2018 08:40:35 [Utils.cpp:2548] ERROR: Error parsing IPv4 <BODYBGCOLOR="wh
ite"FGCOLOR="black"><H1>AuthorizationRequired<
17/Oct/2018 08:40:35 [Utils.cpp:2548] ERROR: Error parsing IPv4 <FONTFACE="Helve
tica
17/Oct/2018 08:40:35 [Utils.cpp:2548] ERROR: Error parsing IPv4 Arial"><B>
17/Oct/2018 08:40:35 [Utils.cpp:2526] ERROR: Error parsing IPv6 Description:Auth
orizationisrequiredforaccesstothisproxy<
17/Oct/2018 08:40:35 [Utils.cpp:2548] ERROR: Error parsing IPv4 <HR>
17/Oct/2018 08:40:35 [Utils.cpp:2548] ERROR: Error parsing IPv4 
17/Oct/2018 08:40:35 [Utils.cpp:2548] ERROR: Error parsing IPv4 <

C:\Program Files\ntopng>

**Comment by mdrodman** [comment]
[ntop.txt](https://github.com/ntop/ntopng/files/2487688/ntop.txt)
