### ISSUE TITLE
README.SSL outdated - does not work as expected

### ISSUE THREAD

**Issue by mineumann** [ntop/ntopng#210]
-sha256 should be used as browsers don't like sha1 any longer

When using the linux example (with -sha1) on an nbox 2.0 the paths are incorrect - adopting them does not work as expected:

cd /tmp/
openssl req -new -x509 -sha1 -extensions v3_ca -nodes -days 365 -out cert.pem
cat privkey.pem cert.pem > /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem
/bin/rm -f privkey.pem cert.pem
cd /usr/bin/
ln -s /lib/x86_64-linux-gnu/libssl.so.1.0.0 .
ntopng

Error:
08/Oct/2015 13:39:31	ERROR: Unable to start HTTP server (IPv4) on ports 3001s: Success

ntopng.conf
-w=3000
-W=3001
...

**Comment by lucaderi** [comment]
Please provide a merge request so that we can integrate them into the manual. Thank you.

**Comment by mineumann** [comment]
Ok but the main thing is that it doesn't start at all (ssl port 3001) - version 2.0.151009 - Professional Edition

**Comment by lmangani** [comment]
DOC updated to use -sha256

**Comment by simonemainardi** [comment]
@mineumann, I've just successfully run an ntopng (pro) instance, encrypted with AES 256 CBC.

Please try the following:

- make sure you are using sha265 in certificate generation
`openssl req -new -x509 -sha256 -extensions v3_ca -nodes -days 365 -out cert.pem`

- make sure `cat` outputs to the current ntopng installation directory
`cat privkey.pem cert.pem > [ntopng-installation-directory]/httpdocs/ssl/ntopng-cert.pem`

- make sure the user who runs ntopng has read privileges for `ntopng-cert.pem`

- check that no other process is using port 3001
`sudo lsof -i tcp:3001`

Finally, point your browser to `http://localhost:3000` or `https://localhost:3001` (note the `https` for port 3001).

**Comment by lucaderi** [comment]
@simonemainardi Please update the self signed certificate https://github.com/ntop/ntopng/blob/dev/httpdocs/ssl/ntopng-cert.pem.dummy with AES 256.

**Comment by simonemainardi** [comment]
certificate updated

```
$openssl x509 -in httpdocs/ssl/ntopng-cert.pem.dummy -inform pem -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 10478271945299662338 (0x916a4cd167871602)
    Signature Algorithm: sha256WithRSAEncryption
[...]
```

**Comment by lucaderi** [comment]
Great
