### ISSUE TITLE
Cannot install on Ubuntu Server 18.04

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [ntop/ntopng#2100]
The Ubuntu/Debian installation ([http://packages.ntop.org/](http://packages.ntop.org/)) does not work on Ubuntu Server 18.04.
I cannot install the following command after executing all the steps mentioned in the documentation.

```
apt-get install pfring-dkms nprobe ntopng n2disk cento  

E: Unable to locate package pfring-dkms  

E: Unable to locate package nprobe  

E: Unable to locate package n2disk  

E: Unable to locate package cento  
```

**Comment by cardigliano** [comment]
@Karlheinzniebuhr did you configure the "nightly" or "stable" repository? It seems to be working for me, I need more details to reproduce this. 
Please make sure you ran all the required commands:

wget http://apt.ntop.org/18.04/all/apt-ntop.deb
dpkg -i apt-ntop.deb
apt-get clean all
apt-get update
apt-get install pfring-dkms nprobe ntopng n2disk cento

**Comment by Karlheinzniebuhr** [comment]
I tried both the nightly and the stable release. Here is the entire output of the nightly builds. As shown below, problems start occuring while running apt-get update. There is an error:
```
E: The repository 'http://packages.ntop.org/apt-stable/5.0 x64/ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

root@monitoring:/home/monitoradmin# wget http://apt.ntop.org/18.04/all/apt-ntop.deb
--2018-10-12 14:32:24--  http://apt.ntop.org/18.04/all/apt-ntop.deb
Resolving apt.ntop.org (apt.ntop.org)... 151.11.50.180, 2a03:b0c0:2:d0::d27:3001
Connecting to apt.ntop.org (apt.ntop.org)|151.11.50.180|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://packages.ntop.org/apt/18.04/all/apt-ntop.deb [following]
--2018-10-12 14:32:25--  http://packages.ntop.org/apt/18.04/all/apt-ntop.deb
Resolving packages.ntop.org (packages.ntop.org)... 151.11.50.180, 2a03:b0c0:2:d0::d27:3001
Reusing existing connection to apt.ntop.org:80.
HTTP request sent, awaiting response... 200 OK
Length: 6660 (6.5K) [application/x-debian-package]
Saving to: ‘apt-ntop.deb.1’

apt-ntop.deb.1                    100%[==========================================================>]   6.50K  --.-KB/s    in 0s

2018-10-12 14:32:25 (438 MB/s) - ‘apt-ntop.deb.1’ saved [6660/6660]
root@monitoring:/home/monitoradmin# dpkg -i apt-ntop.deb
(Reading database ... 213908 files and directories currently installed.)
Preparing to unpack apt-ntop.deb ...
Unpacking apt-ntop (2.7-979) over (2.7-979) ...
upgrade
Setting up apt-ntop (2.7-979) ...
Adding ntop key to apt keyring
Warning: apt-key should not be used in scripts (called from postinst maintainerscript of the package apt-ntop)
OK
root@monitoring:/home/monitoradmin# apt-get clean all
root@monitoring:/home/monitoradmin# apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]
Get:3 http://ppa.launchpad.net/elementary-os/daily/ubuntu bionic InRelease [20.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Ign:5 http://packages.ntop.org/apt-stable/5.0 x64/ InRelease
Hit:6 http://ppa.launchpad.net/elementary-os/os-patches/ubuntu bionic InRelease
Ign:7 http://packages.ntop.org/apt-stable/5.0 all/ InRelease
Get:8 http://security.ubuntu.com/ubuntu bionic-security/main amd64 DEP-11 Metadata [204 B]
Ign:9 http://packages.ntop.org/apt/5.0 x64/ InRelease
Get:10 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Ign:11 http://ppa.launchpad.net/elementary-os/testing/ubuntu bionic InRelease
Get:12 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 DEP-11 Metadata [6,820 B]
Ign:13 http://packages.ntop.org/apt/5.0 all/ InRelease
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 DEP-11 Metadata [173 kB]
Get:15 http://security.ubuntu.com/ubuntu bionic-security/universe DEP-11 64x64 Icons [11.3 kB]
Err:16 http://packages.ntop.org/apt-stable/5.0 x64/ Release
  404  Not Found [IP: 151.11.50.180 80]
Hit:17 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease
Get:18 http://security.ubuntu.com/ubuntu bionic-security/universe DEP-11 128x128 Icons [31.6 kB]
Err:19 http://packages.ntop.org/apt-stable/5.0 all/ Release
  404  Not Found [IP: 151.11.50.180 80]
Get:20 http://archive.ubuntu.com/ubuntu bionic-updates/main DEP-11 48x48 Icons [40.8 kB]
Hit:21 http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu bionic InRelease
Err:22 http://packages.ntop.org/apt/5.0 x64/ Release
  404  Not Found [IP: 151.11.50.180 80]
Get:23 http://archive.ubuntu.com/ubuntu bionic-updates/main DEP-11 64x64 Icons [81.8 kB]
Err:24 http://packages.ntop.org/apt/5.0 all/ Release
  404  Not Found [IP: 151.11.50.180 80]
Get:25 http://archive.ubuntu.com/ubuntu bionic-updates/main DEP-11 128x128 Icons [195 kB]
Err:26 http://ppa.launchpad.net/elementary-os/testing/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Get:27 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 DEP-11 Metadata [183 kB]
Get:28 http://ppa.launchpad.net/elementary-os/daily/ubuntu bionic/main amd64 Packages [40.2 kB]
Get:29 http://archive.ubuntu.com/ubuntu bionic-updates/universe DEP-11 48x48 Icons [174 kB]
Get:30 http://archive.ubuntu.com/ubuntu bionic-updates/universe DEP-11 64x64 Icons [289 kB]
Get:31 http://archive.ubuntu.com/ubuntu bionic-updates/universe DEP-11 128x128 Icons [738 kB]
Get:32 http://ppa.launchpad.net/elementary-os/daily/ubuntu bionic/main Translation-en [15.2 kB]
Get:33 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 DEP-11 Metadata [2,468 B]
Get:34 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 DEP-11 Metadata [5,104 B]
Reading package lists... Done
E: The repository 'http://packages.ntop.org/apt-stable/5.0 x64/ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://packages.ntop.org/apt-stable/5.0 all/ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://packages.ntop.org/apt/5.0 x64/ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://packages.ntop.org/apt/5.0 all/ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/elementary-os/testing/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@monitoring:/home/monitoradmin# apt-get install pfring-dkms nprobe ntopng n2disk cento
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package pfring-dkms
E: Unable to locate package nprobe
E: Unable to locate package n2disk
E: Unable to locate package cento
root@monitoring:/home/monitoradmin#

**Comment by simonemainardi** [comment]
I am not sure why you have this kind of errors.

> Ign:7 http://packages.ntop.org/apt-stable/5.0 all/ InRelease
> Ign:9 http://packages.ntop.org/apt/5.0 x64/ InRelease
> Ign:11 http://ppa.launchpad.net/elementary-os/testing/ubuntu bionic InRelease
> Ign:13 http://packages.ntop.org/apt/5.0 all/ InRelease
> Err:16 http://packages.ntop.org/apt-stable/5.0 x64/ Release

It seems that apt is looking for a version `5.0` which honestly I don't know from where it comes from. Maybe file `/etc/apt/sources.list.d/ntop.list` has been manually mangled? File must contain

```
simone@ubuntu18:~$ cat /etc/apt/sources.list.d/ntop.list
deb http://packages.ntop.org/apt/18.04/ x64/
deb http://packages.ntop.org/apt/18.04/ all/
```

It seems also you have both the stable and dev repos installed.

Do a complete remove 
```
sudo apt-get remove apt-ntop (if installed)
sudo apt-get remove apt-ntop-stable (if installed)
sudo apt-get update
```

Then follow the installation instructions again and don't manually touch the .list files.

**Comment by Karlheinzniebuhr** [comment]
I found the problem, the links inside the package [wget http://apt-stable.ntop.org/18.04/all/apt-ntop-stable.deb](http://apt-stable.ntop.org/18.04/all/apt-ntop-stable.deb) point to version 5.
The moment I run **dpkg -i apt-ntop-stable.deb** the file ntop-stable.list gets updated with these values.
```
deb http://packages.ntop.org/apt-stable/5.0/ x64/
deb http://packages.ntop.org/apt-stable/5.0/ all/
```
When I change them to the ones you provided, it works! So to fix this, the [documentation ](http://packages.ntop.org/apt-stable/)needs an update with the right package, pointing to the latest version.

**Comment by simonemainardi** [comment]
this is what we do to populate the file. Actually, the 18 version is taken from lsb release and it works here:

```
#!/bin/sh -e

SUB_DISTRO=`lsb_release -i|cut -f 2`
if test "$SUB_DISTRO" = "Debian"; then
  REL=`/usr/bin/lsb_release -c|cut -f 2`
else
  REL=`/usr/bin/lsb_release -s -r`
fi

case "$1" in
    configure)
    # continue below
    echo "Adding ntop key to apt keyring"
    apt-key add /etc/nbox/ntop-apt.key || /bin/true
    # Just to make sure there is no version mismatch
    echo "deb http://packages.ntop.org/apt-stable/$REL/ x64/" > /etc/apt/sources.list.d/ntop-stable.list
    echo "deb http://packages.ntop.org/apt-stable/$REL/ all/" >> /etc/apt/sources.list.d/ntop-stable.list
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        exit 0
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac


exit 0
```

Can you please report the output these commands:

```
/usr/bin/lsb_release -a
/usr/bin/lsb_release -i
/usr/bin/lsb_release -i|cut -f 2
/usr/bin/lsb_release -c|cut -f 2
/usr/bin/lsb_release -s -r
```

**Comment by Karlheinzniebuhr** [comment]
monitoradmin# /usr/bin/lsb_release -a
No LSB modules are available.
Distributor ID: elementary
Description:    elementary OS 5.0 Juno
Release:        5.0
Codename:       juno
monitoradmin# /usr/bin/lsb_release -i
Distributor ID: elementary
monitoradmin# /usr/bin/lsb_release -i|cut -f 2
elementary
monitoradmin# /usr/bin/lsb_release -c|cut -f 2
juno
monitoradmin# /usr/bin/lsb_release -s -r
5.0

It seems that my lsb_release file somehow has the wrong version number, but at this point it's not an issue of ntopng so I will close this. Sorry for the inconvenience

**Comment by simonemainardi** [comment]
You have Elementary OS 5.0 Juno, not Ubuntu18 as stated in the title. Double-check before posting invalid issues.

**Comment by Karlheinzniebuhr** [comment]
Actually I have Ubuntu Server 18.04 with Elementary on top of it. But you are right I should’ve checked that.

Sent from Mail for Windows 10

**Comment by a-essawy** [comment]
I have found the solution for this issue.
I'm using Kali Linux which is based on Debian 10, but the steps are similar in Ubuntu "Not sure TBH"

after running these:
` wget https://packages.ntop.org/apt-stable/buster/all/apt-ntop-stable.deb`
`apt install ./apt-ntop-stable.deb `

Now the issue is inside this file  _**/etc/apt/sources.list.d/ntop-stable.list**_
that the links inside sources is outdated, so we have to correct them manually.
You can use any text editor, I will use nano.
`sudo nano /etc/apt/sources.list.d/ntop-stable.list`

you should be able to see this

> deb https://packages.ntop.org/apt-stable/2020.4/ x64/
deb https://packages.ntop.org/apt-stable/2020.4/ all/

you have to change the links to the new ones

for **Debian 10**

> deb https://packages.ntop.org/apt-stable/10/ x64/
deb https://packages.ntop.org/apt-stable/10/ all/

for **Ubuntu 20.04**
>deb https://packages.ntop.org/apt-stable/20.04/ x64/
deb https://packages.ntop.org/apt-stable/20.04/ all/

if you use another OS you can find yours here : [https://packages.ntop.org/apt-stable/](url) "at the very down"

now save it and run these:

`apt-get clean all`
`apt-get update`
`apt-get install pfring-dkms`
`apt-get install nprobe`
`apt-get install ntopng`
`apt-get install n2disk`
`apt-get install cento`
