### ISSUE TITLE
max number of hosts in host pool?

### ISSUE THREAD

**Issue by jensenja** [ntop/ntopng#2103]
Hi,

I can't seem to add more than 8 entries to a given host pool list. Right now I have one IPv4 subnet, one IPv6 subnet, and 6 MAC addresses added to a host pool. Attempts to add more MACs are just silently ignored and the MACs are never added to the host pool. I can't find any errors in the logs either. Running ntopng version `3.6.181009 - Enterprise Edition` (timed license for RFP purposes). Is this by design?

**Comment by jensenja** [comment]
Deleting the v4/v6 subnet entries allows me to add 2 more MAC addresses, but I still cannot add more than 8 items to a given host pool list.

**Comment by simonemainardi** [comment]
The maximum number of pool members is capped at 8, unless you have an unlimited Enterprise license which features and unlimited number of pool members. So what you are experiencing is normal.
