### ISSUE TITLE
ntopng is creashing

### ISSUE THREAD

**Issue by gamujtaba** [ntop/ntopng#2107]
Hi I am using netgate sg 3100 pfsense firewall i have install ntopng for monitor the employ internet usage.  i am facing issue ntopng service is automatically down after some time. and i am unable to access interface. 

kindly confirm me why my ntopng service goes to stop automatically

**Comment by emanuele-f** [comment]
HI, what ntopng version are you using? What is your ntopng configuration?

**Comment by gamujtaba** [comment]
My Pfsense version is 2.4.4
my ntopng version is:  v.3.4.180911

I dont know how i can check the configuration. i have installed packages in pfsense available packages section. 

and configured from from Package> Diagnostics: ntopng Settings 

Regards,
Ahmad

**Comment by emanuele-f** [comment]
The 3.4 version is outdated, we do not support it anymore. Please ask the Pfsense team to upgrade the package to the new stable.

**Comment by gamujtaba** [comment]
i have created the ticket but they are not updating. now what i can do for upgrade this package to new pacakge in netgate sg 3100

**Comment by emanuele-f** [comment]
if you have the possibility to compile from source, you could clone this git repository compile it by following the [compilation instructions](https://github.com/ntop/ntopng/blob/dev/doc/README.compilation)

**Comment by gamujtaba** [comment]
I am using Netegate SG 3100 pfsense firewall i have tried to compile with update version but i am unable to compile. i have installed ntopng using package manage option in pfsense. there is old version 3.4 is stored. i want to update 3.6 for stability. with 3.4 i am facing issue. ntopng service stop automatically after some time. when i restart its removed all stored data. i want to monitor my employees internet usage. 
kindly help me to fix this
