### ISSUE TITLE
Connecting NTOP with MYSQLfor  saving data

### ISSUE THREAD

**Issue by waqar-ali-aziz** [ntop/ntopng#2109]
respected Sir i want to store data from ntop flows to MYSQL and i think i am making mistake in -F modification command. should it be written in ntopng.conf file (in this form # -F = "---------") and kindly explain briefly its parameters and 2nd thing is that is it necessary to make table in MYSQL or ntop will create it automatically ?

**Comment by simonemainardi** [comment]
What you're asking is already in the documentation:

- configuration file: https://www.ntop.org/guides/ntopng/how_to_start/configuration_file.html
- mysql dump https://www.ntop.org/guides/ntopng/advanced_features/flows_dump.html?highlight=mysql

Don't forget to check that out before opening issues.
