### ISSUE TITLE
wrong ASN shown for IP

### ISSUE THREAD

**Issue by mineumann** [ntop/ntopng#211]
how does ntopng get the ASN for an IP?

81.19.150.1 is in ASN 38955 and not in 21013 as ntopng assumes/shows

**Comment by lucaderi** [comment]
ntopng uses GeoIP for that. GeoIP files are packages into the ntopng-data package if you are installing our packages.

**Comment by mineumann** [comment]
Is it possible to override this? Because it's the wrong information for our prefix/AS so the various statistics are "wrong".

**Comment by lucaderi** [comment]
Please contact maxmind.com and report the bug so they can update their databases.

**Comment by mineumann** [comment]
Can you please update the ntopng-data? maxmind.com has the right information available, but your file seems to be outdated.

my nbox2:
dpkg --list | grep ntopng-data
ii  ntopng-data                         2.0.151009                       all          Data files (geoip) for ntopng.

packages.ntop.org:
ntopng-data_2.0.151009_all.deb     2015-10-09 10:22     30M

strings /usr/share/ntopng/httpdocs/geoip/GeoIPASNum.dat | grep MaxMind
GEO-117 20090321 Build 1 Copyright (c) 2007 MaxMind LLC All Rights Reserved

In the current files the information is correct. Thank you

**Comment by lucaderi** [comment]
We've just updated the dat files refreshing them from maxmind. Packages are under construction and they will be available in about a hour

**Comment by mineumann** [comment]
Great - working now - thank you
