### ISSUE TITLE
[ntopng / nprobe] Interface selection chopped with nProbe criterion for disagg.

### ISSUE THREAD

**Issue by mimugmail** [ntop/ntopng#2110]
Hi,

I set up ntopng and nprobe as a flow collector to troubleshoot network problems. When I send flows from multiple agents the selections of nprobe IPs in interface selection is chopped (see screenshot). 

Perhaps there's a better approach available?

![image](https://user-images.githubusercontent.com/20438689/47085223-42679c00-d216-11e8-88b8-f7659b055b2a.png)

**Comment by simonemainardi** [comment]
it's just the name that has been shortened. You can visit the interface page and change / add another name. Is this what you mean?

**Comment by mimugmail** [comment]
Oh, wasn't aware that we can change this in interface view, sorry :)
