### ISSUE TITLE
Error to start ntopng

### ISSUE THREAD

**Issue by tiitba** [ntop/ntopng#2111]
Hi, when i try run ntopng with file config path, console inform the follow error:
"ntopng /etc/ntopng/ntopng.conf
Segmentation fault"
However, on the reeset/start machine, ntopng take config, but i dont know from wich file config.

Data SO:
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"

Nntopng version:
ntopng Enterprise Edition v.3.6.181017

ntopng.conf:
-G=/var/run/ntopng.pid
--online-license-check
--local-networks="10.0.0.0/16,10.1.0.0/16,10.2.0.0/16,10.1.1.0/24,10.3.0.0/16,10.4.0.0/16, 10.7.0.0/16,10.8.0.0/20,10.16.0.0/20,172.17.0.0/16"
--interface="tcp://10.1.0.26:5555"
--interface="tcp://10.1.0.26:5556"
--interface="tcp://10.1.0.26:5557"
--interface="tcp://10.1.0.26:5558"
--interface="tcp://10.1.0.26:5559"
--daemon
--enable-aggregations
--max-num-flows=200000
--max-num-hosts=250000
--sticky-hosts

Thanks for you attention.

**Comment by emanuele-f** [comment]
Hi, please remove the --daemon option from the config. The ntopng service will automatically read /etc/ntopng/ntopng.conf on startup. Can you try to manually start ntopng from command line and get a backtrace of the crash as described here? https://github.com/ntop/ntopng/blob/dev/doc/README.crash

**Comment by tiitba** [comment]
Hi, thanks for your asnwer. I removed --daemon option from the config, but error message still on console. 
On the other hand, here the output from gdb:

  gdb --args ntopng /etc/ntopng/ntopng.conf
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ntopng...done.
(gdb) run
Starting program: /usr/local/bin/ntopng /etc/ntopng/ntopng.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
__strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:203
203     ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:203
#1  0x00005555555f7227 in Prefs::setOption (this=0x555555a22270, optkey=83, optarg=0x0) at src/Prefs.cpp:804
#2  0x00005555555f9674 in Prefs::loadFromFile (this=0x555555a22270, path=0x7fffffffe90a "/etc/ntopng/ntopng.conf") at src/Prefs.cpp:1388
#3  0x00005555555da3cf in main (argc=2, argv=0x7fffffffe708) at src/main.cpp:113
(gdb)

**Comment by emanuele-f** [comment]
This is the same issue as #2021 . The fix has not been backported to stable

**Comment by emanuele-f** [comment]
Now backported with 12f6373976c8949e946e6971452f92b29e52d2cf . A new package will be available in one hour. Thank you for reporting.

**Comment by tiitba** [comment]
Hi! It´s working!! 
Thanks very much for you help!!
