### ISSUE TITLE
Unable to write on /var/lib/ntopng as 'ntopng' 

### ISSUE THREAD

**Issue by jiangdu8888** [ntop/ntopng#2112]
19/Oct/2018 20:23:09 [Utils.cpp:407] WARNING: mkdir(/var/lib/ntopng) failed [13/Permission denied]
19/Oct/2018 20:23:09 [main.cpp:368] ERROR: Unable to write on /var/lib/ntopng as 'ntopng' [/var/lib/ntopng/.test]: No such file or directory. Please specify a different directory (-d)

**Comment by cardigliano** [comment]
@jiangdu8888 please read https://www.ntop.org/support/faq/migrate-the-data-directory-in-ntopng/ to migrate your datadir.
What is your linux distribution/version?

**Comment by jiangdu8888** [comment]
ubuntu16.04   and i'm first install "nTOPNG" on it

**Comment by cardigliano** [comment]
@jiangdu8888 a fresh install on ubuntu 16 is working for me, the installation script is creating the /var/lib/ntopng folder with the right permissions. If you did not fix it yet, could you provide "ls -al /var/lib"? Thank you.

**Comment by emanuele-f** [comment]
@jiangdu8888 any news?

**Comment by jiangdu8888** [comment]
> @jiangdu8888 any news?

ok,i did not fix it,so i change to install 3.6         so sorry about ruturn u late

**Comment by simonemainardi** [comment]
thanks for reporting
