### ISSUE TITLE
Periodically check DHCP-assigned address

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2113]
When nEdge has a dynamic IP address set via DHCP, in case the periodic lease is renewed but bound to a different IP address (with respect to the previous one), nEdge needs to detect this and reconfigure itself. This is because when used for instance in transparent bridge, the rules must be refreshed according to the new IP address. Addressing this ticket can be done via a periodic IP check (i.e. see if the DHCP assigned IP address does not change overtime) or by dissecting DHCP protocol PDUs. In all cases without reconfiguring nEdge after address change, leads to connectivity disruption.

**Comment by simonemainardi** [comment]
There are several parts in the code which assume the nEdge WAN address never changes. This is not true in case the WAN is configured in DHCP. We must detect these changes and do the reconfiguration.

**Comment by simonemainardi** [comment]
After internal review we have decided this issue is no longer necessary.
