### ISSUE TITLE
Top Visited Sites 

### ISSUE THREAD

**Issue by franciscoer** [ntop/ntopng#2118]
Hi! We are interested in having this feature, could you implement it?

Visualize the top HTTP sites contacted by any host

Thanks !

BR

Francisco

**Comment by simonemainardi** [comment]
visit ntopng preferences, enable top HTTP sites

![image](https://user-images.githubusercontent.com/3397663/47340634-25601c80-d69f-11e8-9763-7ba7e5dc0109.png)


and you'll have them:


![image](https://user-images.githubusercontent.com/3397663/47340625-1ed1a500-d69f-11e8-955b-c3ef1c3fdf4e.png)

**Comment by franciscoer** [comment]
Hey Simone, thanks for your answer. I already did a few days ago. But I do
not have the HTTP menu, inside the host

Please, take a look at images attached

Thanks

BR

Francisco

**Comment by franciscoer** [comment]
![preferences](https://user-images.githubusercontent.com/44379854/47358787-2db95700-d6a1-11e8-97f0-fbe292b9d726.png)
![hosts](https://user-images.githubusercontent.com/44379854/47358788-2db95700-d6a1-11e8-9113-b6747c265941.png)
Hey Simone, thanks for your answer. I already did a few days ago. But I do not have the HTTP menu, inside the host

Please, take a look at images attached

Thanks

BR

Francisco

**Comment by simonemainardi** [comment]
I've noticed you are using a ZMQ interface. VIsited websites are only available when ntopng monitors a physical interface with traffic packets.

**Comment by HoseinKashefi** [comment]
Dear @simonemainardi 
I use ntopng : v.3.9.181226 (enabled http top site )(ZMQ Monitoring)
and Cento : v.1.5.181226 
I need to have this feature. because of analyzing user behavior(about 5k Users)
 what can i do for it ? and is there any alternative solution to have it?

**Comment by emanuele-f** [comment]
Is nprobe reading raw packets from a physical interface or traffic from sflow/netflow? In the latter case the %HTTP_URL information may not be available

**Comment by HoseinKashefi** [comment]
nprobe reads raw data directly from interface.

**Comment by simonemainardi** [comment]
using %HTTP_URL doesn't help. The feature relies on the dissected nDPI data that is only available when ntopng monitors physical interfaces. If you need this feature, try and open a feature request and we will see if we can accomodate it.

**Comment by ringfeart** [comment]
I've installed the ntopng 3.8.1 version (package release made by contributor hgy59) on my Synology DS216+II.
Same issue: I enabled the Top HTTP Sites switch, but can't see the HTTP menu. 
Is this issue solved in the newer version 4.0?

I get a message: **A new ntopng (v.4.0.0) is available for download: please upgrade**. 
Does anyone know how to upgrade to this version on a Synology?

**Comment by ringfeart** [comment]
Sorry, I meant: can't see the **Sites menu**.....
![ntopng](https://user-images.githubusercontent.com/64796431/80995848-34e92580-8e3f-11ea-8ec3-45a7433d00d5.jpg)

**Comment by simonemainardi** [comment]
Latest stable version is 4.0, please upgrade to that version.

Sites appear when top http sites are enabled from the ntopng preference and when capturing from a packet interface or receiving data from nprobe.

**Comment by emanuele-f** [comment]
Please ensure that the hosts are "local", see https://www.ntop.org/guides/ntopng/basic_concepts/hosts.html#local-hosts .

**Comment by simonemainardi** [comment]
did you move to at least version 4?

**Comment by joeontherun** [comment]
Sorry for posting on a really old post however iv also come across this issue with my PFsense NTOPNG setup, i found a work around which gets you to what you need i suppose,

For a live view of what the computer ip is accessing go to this page, on ntoping and alighn by throughput

https://Whatever your Ntop address is:3000/lua/host_details.lua?host=Ip of computer&page=flows&flow_status=alerted

Above is the manual way of getting the live information of a spicific machine, if your looking for a way to get to it via just browsing try this go to activeflows or if you know the devices IP name just go to hosts, Drill in to the host iformation then select, "Active Alerted Flows" this will take you to there active connections and if you align by throughput you will get the very top active sits being accessed

(JSON Method) (**example of my alexa device if it were a computer the sites would be much larger list**)
For old.sites you will need to use a Json viewer addon for chrome and then select the JSON download link at the very bottom of the same information page now the output looks messy but the sites are all in there, for that host, if its history sites then your looking for old.sites section for currently Active its just sites see below for an example of the Json output of a host

"**sites**": "{ \"amazon.com\": 2579, \"cloudfront.net\": 837, \"eu.amazonalexa.com\": 600, \"us-east-1.prod.service.minerva.devices.a2z.com\": 510, \"amazonalexa.com\": 365, \"acsechocaptiveportal.com\": 122, \"s3.eu-west-1.amazonaws.com\": 10, \"amcs-tachyon.com\": 5, \"meethue.com\": 3, \"s3.amazonaws.com\": 3, \"amazon-dss.com\": 3, \"us-east-1.prod.arteries.alexa.a2z.com\": 3, \"planetradio.co.uk\": 3 }",



"**sites.old**": "{ \"amazon.com\": 2579, \"cloudfront.net\": 837, \"eu.amazonalexa.com\": 600, \"us-east-1.prod.service.minerva.devices.a2z.com\": 510, \"amazonalexa.com\": 365, \"acsechocaptiveportal.com\": 122, \"s3.eu-west-1.amazonaws.com\": 10, \"amcs-tachyon.com\": 5, \"meethue.com\": 3, \"s3.amazonaws.com\": 3, \"amazon-dss.com\": 3, \"us-east-1.prod.arteries.alexa.a2z.com\": 3, \"planetradio.co.uk\": 3 }",
