### ISSUE TITLE
nDPI... not found by configure although it's ... there

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#212]
Environment
Ubuntu Server 15.04 - All sources from https://github.com/ntop

nDPI has been compiled from git sources and installed as "libndpi".
ntopng cannot compile:
./autogen.sh
Wait please...

Now run ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for nDPI... not found
Please do cd ..; git clone https://github.com/ntop/nDPI.git; cd nDPI; ./autogen.sh; make; cd ../ntopng
 and try again

Am I missing something?

**Comment by lucaderi** [comment]
@jean-christophe-manciot We expect to have this layout
<your directory>/nDPI
<your directory>/ntopng

You have said you have done a make install of nDPI? If so, can you please tell me what files and what nDPi version has been installed?

**Comment by jean-christophe-manciot** [comment]
nDPI 1.6 - last commit done 10/06/15
Don't you check whether the library is present or not?

/usr/local/lib/libndpi.la
/usr/local/lib/pkgconfig/libndpi.pc
/usr/local/lib/libndpi.so.1.0.0
/usr/local/lib/libndpi.so
/usr/local/lib/libndpi.a
/usr/local/lib/libndpi.so.1


I could rename it as ndpi, but I intend to offer one built package to the Ubuntu community and on the official repositories, the names of the packages are libndpi1a and libndpi-bin 1.5.0.

**Comment by lucaderi** [comment]
@jean-christophe-manciot The official packages are a bit outdated and in order to avoid many headaches we have decided to use the local nDPI. I understand that you might be unhappy of this answer, but it will save a lot of support time.

**Comment by jean-christophe-manciot** [comment]
There seems to be some confusion here: I'm not using the official ubuntu packages at all; I'm trying to compile the sources from github nDPI & ntopng repositories.

**Comment by lucaderi** [comment]
Same as above. For the time being we support this layout
<dir>/nDPI
<dir>/ntopng

If you like to support installed nDPI files, please send us a patch to our configure and we'll include it. Thank you (don't forget to star ntopng on github)

**Comment by al2rex** [comment]
hello..
how to intstall librarys the nDPI in centOS 7 ?? help meeee ..!!

**Comment by simonemainardi** [comment]
see https://github.com/ntop/nDPI
