### ISSUE TITLE
multiple flow entries of the same source/destination

### ISSUE THREAD

**Issue by slylander** [ntop/ntopng#2121]
I encountered something strange. ntopng kept indicating it reached max flow counter.  Upon inspecting I found there are multiple entries of the same source/destination. 
ntopng.conf
---
-G=/var/run/ntopng.pid
-i=zc:eno1
--https-port=3001
-m=local networks
-n=1
-S=local
-d=/opt/ntopng
-q=
-X=3276800
---
Where do I troubleshoot?

![sniff-flow1](https://user-images.githubusercontent.com/23007984/47525527-546abf80-d852-11e8-8760-433ad5562a37.jpg)

Thank you,

**Comment by emanuele-f** [comment]
Please confirm that the source and destination IP and ports of two rows are exactly the same? It's not clear from the screenshot above

**Comment by slylander** [comment]
Hi Emanuele,

Yes, the source and destination IP and ports are exactly the same. I redacted them from praying eyes.  I can provide you via private channel if needed.

Thank you,

Willie
