### ISSUE TITLE
Describe best practices of optimising ntopng performance

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2122]
As described in https://www.ntop.org/ntopng/best-practices-for-running-ntopng/ ntopng can be configured to take advantages of RSS and ZC. This is not described in the ntopng user's guide and it ought to be described.

**Comment by simonemainardi** [comment]
Done in: https://github.com/ntop/ntopng/commit/6781d79c0043810309751ca0813fadc4610d35da

Description and link to the blog post have been added.

Blog post updated accordingly.
