### ISSUE TITLE
Invalid report

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2123]
The images below demonstrate that the queries and data returned is wrong, just TCP as a filter 
![image002](https://user-images.githubusercontent.com/4493366/47555983-8c830880-d90d-11e8-8be7-383ded96ace5.png)
![image003](https://user-images.githubusercontent.com/4493366/47555987-8ee56280-d90d-11e8-8681-7761e2474962.png)

**Comment by simonemainardi** [comment]
Please, tell me:

- ntopng configuration used
- ntopng version
- is the historical data explorer browsed by a non-admin ntopng user with restricted privileges?


Please, also do the following to help me with the debug:

- make sure you are using the latest ntopng 3.7
- stop ntopng
- edit file /usr/share/ntopng/scripts/lua/modules/db_utils.lua and replace empty line 316 with the following line

```
tprint({sql=sql, res=res})
```

- start ntopng in the foreground as /usr/local/bin/ntopng /etc/ntopng/ntopng.conf
- visit the historical explorer, click search without touching anything else, and report me what you are seeing in the foreground console of ntopng. I would expect to see something like
```
 table
sql string select COUNT(*) AS TOT_FLOWS, SUM(IN_BYTES + OUT_BYTES) AS TOT_BYTES, SUM(PACKETS) AS TOT_PACKETS FROM aggrflowsv6 where FIRST_SWITCHED <= 1540977445 and FIRST_SWITCHED >= 1540973845 AND (NTOPNG_INSTANCE_NAME='develv5'OR NTOPNG_INSTANCE_NAME IS NULL OR NTOPNG_INSTANCE_NAME='') AND (INTERFACE_ID='3') AND VLAN_ID=0
res table
res.1 table
res.1.TOT_PACKETS string 11
res.1.TOT_BYTES string 1078
res.1.TOT_FLOWS string 5
 table
sql string select COUNT(*) AS TOT_FLOWS, SUM(IN_BYTES + OUT_BYTES) AS TOT_BYTES, SUM(PACKETS) AS TOT_PACKETS FROM aggrflowsv4 where FIRST_SWITCHED <= 1540977445 and FIRST_SWITCHED >= 1540973845 AND (NTOPNG_INSTANCE_NAME='develv5'OR NTOPNG_INSTANCE_NAME IS NULL OR NTOPNG_INSTANCE_NAME='') AND (INTERFACE_ID='3') AND VLAN_ID=0
res table
res.1 table
res.1.TOT_PACKETS string 12689
res.1.TOT_BYTES string 6629906
res.1.TOT_FLOWS string 30
```

- finally, add the TCP filter, click search again, and report once more the new contents appeared in the foreground console of ntopng. I would expect to see something like

```
 table
sql string select COUNT(*) AS TOT_FLOWS, SUM(IN_BYTES + OUT_BYTES) AS TOT_BYTES, SUM(PACKETS) AS TOT_PACKETS FROM flowsv6 where FIRST_SWITCHED <= 1540977445 and FIRST_SWITCHED >= 1540973845 AND (NTOPNG_INSTANCE_NAME='develv5'OR NTOPNG_INSTANCE_NAME IS NULL OR NTOPNG_INSTANCE_NAME='') AND (INTERFACE_ID='3') AND PROTOCOL=6 AND VLAN_ID=0
res table
res.1 table
res.1.TOT_PACKETS string
res.1.TOT_BYTES string
res.1.TOT_FLOWS string 0
 table
sql string select COUNT(*) AS TOT_FLOWS, SUM(IN_BYTES + OUT_BYTES) AS TOT_BYTES, SUM(PACKETS) AS TOT_PACKETS FROM flowsv4 where FIRST_SWITCHED <= 1540977445 and FIRST_SWITCHED >= 1540973845 AND (NTOPNG_INSTANCE_NAME='develv5'OR NTOPNG_INSTANCE_NAME IS NULL OR NTOPNG_INSTANCE_NAME='') AND (INTERFACE_ID='3') AND PROTOCOL=6 AND VLAN_ID=0
res table
res.1 table
res.1.TOT_PACKETS string 10397
res.1.TOT_BYTES string 5807092
res.1.TOT_FLOWS string 404
```

**Comment by juesor** [comment]
CentOS Linux release 7.5.1804 (Core)

ntopng.x86_64      3.7.181016-5025

No the end user is part of the group i have setup for LDAP Admin Group

I just upgraded to the latest nightly as requested to be on the latest.

ntopng.x86_64 0:3.7.181031-5126             
ntopng-data.noarch 0:3.7.181031-5126

output of starting ntopng with tprint on line 317

 table
sql string select COUNT(*) AS TOT_FLOWS, SUM(IN_BYTES + OUT_BYTES) AS TOT_BYTES, SUM(PACKETS) AS TOT_PACKETS FROM aggrflowsv6 where FIRST_SWITCHED <= 1541005947 and FIRST_SWITCHED >= 1541002347 AND (NTOPNG_INSTANCE_NAME='ntopngmi.acentek.net'OR NTOPNG_INSTANCE_NAME IS NULL OR NTOPNG_INSTANCE_NAME='') AND (INTERFACE_ID='2') AND VLAN_ID=0
res table
res.1 table
res.1.TOT_PACKETS string
res.1.TOT_BYTES string
res.1.TOT_FLOWS string 0
 table
sql string select COUNT(*) AS TOT_FLOWS, SUM(IN_BYTES + OUT_BYTES) AS TOT_BYTES, SUM(PACKETS) AS TOT_PACKETS FROM aggrflowsv4 where FIRST_SWITCHED <= 1541005947 and FIRST_SWITCHED >= 1541002347 AND (NTOPNG_INSTANCE_NAME='ntopngmi.acentek.net'OR NTOPNG_INSTANCE_NAME IS NULL OR NTOPNG_INSTANCE_NAME='') AND (INTERFACE_ID='2') AND VLAN_ID=0
res table
res.1 table
res.1.TOT_PACKETS string 66511300
res.1.TOT_BYTES string 61363935200
res.1.TOT_FLOWS string 5195

With the TCP filter.

 table
sql string select COUNT(*) AS TOT_FLOWS, SUM(IN_BYTES + OUT_BYTES) AS TOT_BYTES, SUM(PACKETS) AS TOT_PACKETS FROM flowsv6 where FIRST_SWITCHED <= 1541005947 and FIRST_SWITCHED >= 1541002347 AND (NTOPNG_INSTANCE_NAME='ntopngmi.acentek.net'OR NTOPNG_INSTANCE_NAME IS NULL OR NTOPNG_INSTANCE_NAME='') AND (INTERFACE_ID='2') AND PROTOCOL=6 AND VLAN_ID=0
res table
res.1 table
res.1.TOT_PACKETS string
res.1.TOT_BYTES string
res.1.TOT_FLOWS string 0
 table
sql string select COUNT(*) AS TOT_FLOWS, SUM(IN_BYTES + OUT_BYTES) AS TOT_BYTES, SUM(PACKETS) AS TOT_PACKETS FROM flowsv4 where FIRST_SWITCHED <= 1541005947 and FIRST_SWITCHED >= 1541002347 AND (NTOPNG_INSTANCE_NAME='ntopngmi.acentek.net'OR NTOPNG_INSTANCE_NAME IS NULL OR NTOPNG_INSTANCE_NAME='') AND (INTERFACE_ID='2') AND PROTOCOL=6 AND VLAN_ID=0
res table
res.1 table
res.1.TOT_PACKETS string 2996412700
res.1.TOT_BYTES string 3115219383700
res.1.TOT_FLOWS string 2267544

**Comment by juesor** [comment]
MariaDB [ntopng]> select COUNT(*) AS TOT_FLOWS, SUM(IN_BYTES + OUT_BYTES) AS TOT_BYTES, SUM(PACKETS) AS TOT_PACKETS FROM aggrflowsv6 where FIRST_SWITCHED <= 1541005947 and FIRST_SWITCHED >= 1541002347 AND (NTOPNG_INSTANCE_NAME='ntopngmi.acentek.net'OR NTOPNG_INSTANCE_NAME IS NULL OR NTOPNG_INSTANCE_NAME='') AND (INTERFACE_ID='2') AND VLAN_ID=0;
+-----------+-----------+-------------+
| TOT_FLOWS | TOT_BYTES | TOT_PACKETS |
+-----------+-----------+-------------+
|         0 |      NULL |        NULL |
+-----------+-----------+-------------+
1 row in set (0.01 sec)

MariaDB [ntopng]>
MariaDB [ntopng]>
MariaDB [ntopng]> select COUNT(*) AS TOT_FLOWS, SUM(IN_BYTES + OUT_BYTES) AS TOT_BYTES, SUM(PACKETS) AS TOT_PACKETS FROM aggrflowsv4 where FIRST_SWITCHED <= 1541005947 and FIRST_SWITCHED >= 1541002347 AND (NTOPNG_INSTANCE_NAME='ntopngmi.acentek.net'OR NTOPNG_INSTANCE_NAME IS NULL OR NTOPNG_INSTANCE_NAME='') AND (INTERFACE_ID='2') AND VLAN_ID=0;


select COUNT(*) AS TOT_FLOWS, SUM(IN_BYTES + OUT_BYTES) AS TOT_BYTES, SUM(PACKETS) AS TOT_PACKETS FROM flowsv6 where FIRST_SWITCHED <= 1541005947 and FIRST_SWITCHED >= 1541002347 AND (NTOPNG_INSTANCE_NAME='ntopngmi.acentek.net'OR NTOPNG_INSTANCE_NAME IS NULL OR NTOPNG_INSTANCE_NAME='') AND (INTERFACE_ID='2') AND PROTOCOL=6 AND VLAN_ID=0;

+-----------+-------------+-------------+
| TOT_FLOWS | TOT_BYTES   | TOT_PACKETS |
+-----------+-------------+-------------+
|      5195 | 61363935200 |    66511300 |
+-----------+-------------+-------------+
1 row in set (0.02 sec)

MariaDB [ntopng]>
MariaDB [ntopng]>
MariaDB [ntopng]> select COUNT(*) AS TOT_FLOWS, SUM(IN_BYTES + OUT_BYTES) AS TOT_BYTES, SUM(PACKETS) AS TOT_PACKETS FROM flowsv6 where FIRST_SWITCHED <= 1541005947 and FIRST_SWITCHED >= 1541002347 AND (NTOPNG_INSTANCE_NAME='ntopngmi.acentek.net'OR NTOPNG_INSTANCE_NAME IS NULL OR NTOPNG_INSTANCE_NAME='') AND (INTERFACE_ID='2') AND PROTOCOL=6 AND VLAN_ID=0;

select COUNT(*) AS TOT_FLOWS, SUM(IN_BYTES + OUT_BYTES) AS TOT_BYTES, SUM(PACKETS) AS TOT_PACKETS FROM flowsv4 where FIRST_SWITCHED <=+-----------+-----------+-------------+
 1541005947 and FI| TOT_FLOWS | TOT_BYTES | TOT_PACKETS |
RS+-----------+-----------+-------------+
T|         0 |      NULL |        NULL |
+-----------+-----------+-------------+
_SWITCHED >= 1541001 row in set (0.00 sec)
2347 AND (
NTOPNG_INSTANCE_NAME='ntopngmi.acentek.net'OR NTOPNG_INSTANCE_NAME IS NULL OR NTOPNG_INSTANCE_NAME='') AND (INTERFACE_ID='2') AND PROTOCOL=6 AND VLAN_ID=0;MariaDB [ntopng]>
MariaDB [ntopng]>
MariaDB [ntopng]> select COUNT(*) AS TOT_FLOWS, SUM(IN_BYTES + OUT_BYTES) AS TOT_BYTES, SUM(PACKETS) AS TOT_PACKETS FROM flowsv4 where FIRST_SWITCHED <= 1541005947 and FIRST_SWITCHED >= 1541002347 AND (NTOPNG_INSTANCE_NAME='ntopngmi.acentek.net'OR NTOPNG_INSTANCE_NAME IS NULL OR NTOPNG_INSTANCE_NAME='') AND (INTERFACE_ID='2') AND PROTOCOL=6 AND VLAN_ID=0;
+-----------+---------------+-------------+
| TOT_FLOWS | TOT_BYTES     | TOT_PACKETS |
+-----------+---------------+-------------+
|   2267544 | 3115219383700 |  2996412700 |
+-----------+---------------+-------------+
1 row in set (9.58 sec)

**Comment by simonemainardi** [comment]
let's consider this:

```
MariaDB [ntopng]> select COUNT() AS TOT_FLOWS, SUM(IN_BYTES + OUT_BYTES) AS TOT_BYTES, SUM(PACKETS) AS TOT_PACKETS FROM flowsv4 where FIRST_SWITCHED <= 1541005947 and FIRST_SWITCHED >= 1541002347 AND (NTOPNG_INSTANCE_NAME='ntopngmi.acentek.net'OR NTOPNG_INSTANCE_NAME IS NULL OR NTOPNG_INSTANCE_NAME='') AND (INTERFACE_ID='2') AND PROTOCOL=6 AND VLAN_ID=0;
+-----------+---------------+-------------+
| TOT_FLOWS | TOT_BYTES | TOT_PACKETS |
+-----------+---------------+-------------+
| 2267544 | 3115219383700 | 2996412700 |
+-----------+---------------+-------------+
```

Do you think is reasonable? That is approx 1.3MB per flow. Maybe ntopng failed to insert into `aggrflowsv4 `

**Comment by juesor** [comment]
Yea that's close to the correct information but that's only with the TCP option in place.  Shouldn't the search above report back more data as its all traffic without the TCP filter.

**Comment by simonemainardi** [comment]
@juesor 

ntopng uses tables `aggrflowsv4` and `aggrflowsv6` to store 5-min aggregates of network flows which are placed into `flowsv4` and `flowsv6`. Aggregated tables are used to speed up queries. So it seems, from the queries you've run, that the volume of traffic in the aggregated flows table is much lower than the one you are seeing in the normal flow table.

So this could be due to a stop/restart of ntopng, in which case I would expect this behavior to be only temporary. Is the reported behavior systematic? Does it happen every time you run a query?

Please, also check if you have dropped flows. Are you using VLANs?

Re-run and post the output of the following queries

```
MariaDB [ntopng]> select COUNT(*) AS TOT_FLOWS, SUM(IN_BYTES + OUT_BYTES) AS TOT_BYTES, SUM(PACKETS) AS TOT_PACKETS FROM aggrflowsv4 where FIRST_SWITCHED <= 1541005947 and FIRST_SWITCHED >= 1541002347 AND (NTOPNG_INSTANCE_NAME='ntopngmi.acentek.net'OR NTOPNG_INSTANCE_NAME IS NULL OR NTOPNG_INSTANCE_NAME='') AND (INTERFACE_ID='2') AND VLAN_ID=0;

MariaDB [ntopng]> select COUNT(*) AS TOT_FLOWS, SUM(IN_BYTES + OUT_BYTES) AS TOT_BYTES, SUM(PACKETS) AS TOT_PACKETS FROM flowsv4 where FIRST_SWITCHED <= 1541005947 and FIRST_SWITCHED >= 1541002347 AND (NTOPNG_INSTANCE_NAME='ntopngmi.acentek.net'OR NTOPNG_INSTANCE_NAME IS NULL OR NTOPNG_INSTANCE_NAME='') AND (INTERFACE_ID='2') AND PROTOCOL=6 AND VLAN_ID=0;
```

**Comment by juesor** [comment]
ntop definnetly has not restarted in the last 24 hours but yes my users state this always happens.  

I am not using VLANs.

I'm getting the following on both of those queries.

         0 |      NULL |        NULL |

         0 |      NULL |        NULL |

**Comment by simonemainardi** [comment]
There was a limit on the number of aggregated flows (actually set to 1000) that was preventing the majority of aggregated flows from being dumped to database. This was causing the differences described above.

Now this limit has been removed by default and can be turned on from the preferences.

![image](https://user-images.githubusercontent.com/3397663/48282129-10360c80-e459-11e8-9819-1721536fd6ee.png)
