### ISSUE TITLE
Missing throughput in flows (always 0B) 

### ISSUE THREAD

**Issue by fsamareanu** [ntop/ntopng#2125]
Hello,

I have this issue when I click on flows (notice it says 0 B/sec for all flows):

![image](https://user-images.githubusercontent.com/38040820/47640447-0ff66100-db7d-11e8-80d3-27a8c19a27d1.png)

However, traffic is seen by ntopng:

![image](https://user-images.githubusercontent.com/38040820/47640523-387e5b00-db7d-11e8-9185-7618c72988ea.png)

ntopng version is 3.7.181028 - Enterprise Edition

**Comment by emanuele-f** [comment]
Possibly same issue as #2121

**Comment by fsamareanu** [comment]
Is there any info you require to troubleshoot this?

**Comment by emanuele-f** [comment]
What are the contents of /etc/ntopng/ntopng.conf ?

**Comment by fsamareanu** [comment]
-G=/var/run/ntopng.pid
-i=enp4s0.100
-i=enp4s0.101
-i=enp4s0.102
-i=enp4s0.103
-i=enp4s0.104
-i view:enp4s0.100,enp4s0.101,enp4s0.102,enp4s0.103,enp4s0.104
--local-networks="192.168.0.0/16,172.17.172.0/24"
-F "mysql;127.0.0.1;ntopng;flows;ntopng;XXXXXXXXXXXXXXXXXXXX"
-n=1
--http-prefix="/ntopng"
-l=1
-w :3000
-d=/data/var/lib/ntopng

**Comment by emanuele-f** [comment]
Please follow bug #2121
