### ISSUE TITLE
I cannot login to ntopng

### ISSUE THREAD

**Issue by izzie88** [ntop/ntopng#2126]
When i enter my username and password, the page just refreshes and nothing happens.
I have done a password reset and still nothing happens.

The service is running and I dont know why I cannot login.

**Comment by emanuele-f** [comment]
Hi, have you followed the instructions at https://github.com/ntop/ntopng/tree/dev/doc#resetting-admin-user-password ? What ntopng version are you using? Have you tried with another browser?

**Comment by izzie88** [comment]
ntopng version
v.3.6.181029    [Enterprise/Professional build]

Deleting this file runtimeprefs.json worked for me.
Thanks
