### ISSUE TITLE
lua_utils.lua error

### ISSUE THREAD

**Issue by roigroup** [ntop/ntopng#2127]
Hi,
I've just upgraded ntopng using this method:

https://community.nethserver.org/t/how-can-i-update-ntopng/7222/6

But now when I open it I get:

![schermata 2018-10-30 alle 11 00 31](https://user-images.githubusercontent.com/44604491/47710476-24953080-dc33-11e8-91fa-63fa4fffc16a.png)

Is there something I can do to solve it? Thanks.

**Comment by emanuele-f** [comment]
I think you are using an old version, please contact the nethserver support for this.

**Comment by roigroup** [comment]
I'm using NethServer 7.5.1804, the actual latest version.

**Comment by emanuele-f** [comment]
ntopng version. We are not NethServer
