### ISSUE TITLE
Feature request: description for interfaces

### ISSUE THREAD

**Issue by mineumann** [ntop/ntopng#213]
instead of "tcp://127.0.0.1:5556" etc adding a description to the different interfaces in use would improve the usability if using more than one interface

eg: "span port transit XY", "span port transitXY_ipv6"

**Comment by lucaderi** [comment]
You can do that. Go to menu Interfaces and set the name ad shown in this example.
![screen shot 2015-10-08 at 21 58 19](https://cloud.githubusercontent.com/assets/4493366/10378176/b9e57c0a-6e07-11e5-8b7d-ce9695460ccf.png)
