### ISSUE TITLE
nEdge DNS 5 seconds delay issue

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#2131]
I have setup nedge (3.6.181031-5400) in router mode.  I performed a couple of tests with a client using this box as a gateway to verify the functionality of the routing features:

- client pings to 8.8.8.8, looks good
- client -> curl http://www.example.com/index.html This took 5 seconds. Upon further inspection, one of the 2 DNS queries performed never returned.  I have attached a trace

192.168.20.97: client
149.202.239.248: the WAN IP (router is setup to masquarade)

It may be worth mentioning that there are no special filtering rules going on, so all traffic should flow

As you can see, packet 2 was not routed at all.
[pcap-dropped-packet.zip](https://github.com/ntop/ntopng/files/2539446/pcap-dropped-packet.zip)

**Comment by emanuele-f** [comment]
It seems like that you hit this bug: https://www.ntop.org/guides/nedge/dns.html#dns-issue-5-seconds-delay . At the present, we are not aware of any general solution for the issue. It is a kernel bug.

**Comment by ghost** [comment]
Ahh yes, that's the exact problem. Is there a reason your recommended work-around is not handled by nedge... or is that a solution for the client side?

**Comment by emanuele-f** [comment]
The suggested solution is client side only, since no known server side solution is currently known

**Comment by ghost** [comment]
Thanks for the info.  Can you recommend a kernel version for the nedge router to use where this bug is not present?  The bug was discovered over a year ago, and this seems like a show stopper for a router product.

**Comment by emanuele-f** [comment]
I know, we are currently looking forward for more info about this, I'm not aware of any official kernel patch/version released to address this issue.

**Comment by ghost** [comment]
Ok, thanks for the help on this one

**Comment by emanuele-f** [comment]
I see that some kernel commits reference this issue (https://github.com/torvalds/linux/commit/590b52e10d410e1439ae86be9fe19d75fdab628b) so newer kernel version are probably not affected. I'd try to make nEdge run on newer ubuntu 18 to see if the newer kernel (4.15) does not have this bug. See #2106

**Comment by emanuele-f** [comment]
I'll keep this bug open to track the issue. I've tried on Ubuntu 18 and the bug it's still there. The following URL describes the problem in detail: https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeouts . The author has proposed some patches which are being authored/integrated right now.

**Comment by victorhooi** [comment]
@emanuele-f Aha - but if we read between the lines - this means you got Ntop Edge to work on Ubuntu 18? =) Is that right?

**Comment by emanuele-f** [comment]
I'm working on the integration, but there is some more work and tests to do. I wished the new kernel solved this issue.

**Comment by emanuele-f** [comment]
Update: issue still present in the current ubuntu 16 kernel `4.15.0-47-generic`, however conntrack developers say it has been solved in the latest upstream kernel

**Comment by emanuele-f** [comment]
We've tested this on the latest Ubuntu 16 kernel (4.15.0-101-generic) and verified that the 5 seconds delay issue is not present anymore
