### ISSUE TITLE
ntopng is crashing

### ISSUE THREAD

**Issue by gamujtaba** [ntop/ntopng#2132]
Hi I am using netgate sg 3100 pfsense firewall i have install ntopng for monitor the employ internet usage. i am facing issue ntopng service is automatically down after some time. and i am unable to access interface.

kindly confirm me why my ntopng service goes to stop automatically

My Pfsense version is 2.4.4
my ntopng version is: ntopng Community/Embedded Edition v.3.6.181103

I dont know how i can check the configuration. i have installed packages in pfsense available packages section.

and configured from from Package> Diagnostics: ntopng Settings

Regards,
Ahmad

**Comment by emanuele-f** [comment]
Please follow the following instructions to get a stack trace for debugging: https://github.com/ntop/ntopng/blob/dev/doc/README.crash

**Comment by gamujtaba** [comment]
Thanks for your update, 
I have not installed it on any system i am using netgate sg3100 pfsense base router, with 
OS FreeBSD 11.2-RELEASE-p3 ,

How i can fix this issue?

Is this issue any related to ssl certificate.

Regards,
Ahmad

**Comment by emanuele-f** [comment]
Ahmad, you will have to troubleshoot this manually from terminal, this is the only way we can troubleshoot this. Maybe you can ask the pfsense guys support for this.

**Comment by gamujtaba** [comment]
Actually i am using ntopng package on pfsense, the service of ntopng are automatically crashed after some time,

when i checked the runtime status of ntopng i got below error,

06/Nov/2018 10:27:07 [main.cpp:382] Working directory: /var/db/ntopng
06/Nov/2018 10:27:07 [main.cpp:376] Logging onto /var/db/ntopng/ntopng.log
06/Nov/2018 10:27:07 [HTTPserver.cpp:1117] HTTP server listening on 3000

06/Nov/2018 10:27:07 [HTTPserver.cpp:1114] Web server dirs [/usr/local/share/ntopng/httpdocs][/usr/local/share/ntopng/scripts]

06/Nov/2018 10:27:07 [HTTPserver.cpp:947] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.

06/Nov/2018 10:27:07 [HTTPserver.cpp:945] HTTPS Disabled: missing SSL certificate /usr/local/share/ntopng/httpdocs/ssl/ntopng-cert.pem

06/Nov/2018 10:27:06 [main.cpp:298] PID stored in file /var/run/ntopng.pid

06/Nov/2018 10:27:06 [Ntop.cpp:1638] Registered interface mvneta1 [id: 0]
06/Nov/2018 10:27:06 [PcapInterface.cpp:91] Reading packets from interface mvneta1...
06/Nov/2018 10:27:06 [Ntop.cpp:1484] Parent process is exiting (this is normal)

Kindly help me to fix this issue, 

Regards,

**Comment by emanuele-f** [comment]
pfsense is not officially supported by us. Please ask the pfsense support to troubleshoot this and send us a stack trace of the crash. Please reopen the issue when you have such information.
