### ISSUE TITLE
ntop error - [LuaEngine.cpp:2619] ERROR: Unable to enable capabilities

### ISSUE THREAD

**Issue by codecupcake** [ntop/ntopng#2134]
Hi,
I'm using pfsence 2.4.4 version. I have installed ntop. few days it worked perfectly. 
I had to reboot the pfsence todays ago and then after that this error begins to showing. 

```
06/Nov/2018 16:00:12 [LuaEngine.cpp:8080] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/system/discover.lua][...ocal/share/ntopng/scripts/lua/modules/discover_utils.lua:1202: attempt to index local 'host' (a number value)]
06/Nov/2018 16:00:03 [LuaEngine.cpp:2619] ERROR: Unable to enable capabilities
06/Nov/2018 15:55:57 [LuaEngine.cpp:8499] WARNING: Script failure [/usr/local/share/ntopng/scripts/lua/host_details.lua][/usr/local/share/ntopng/scripts/lua/host_details.lua:100: attempt to index local 'host' (a number value)]
```

**Comment by emanuele-f** [comment]
What ntopng version are you using? You can find it in the ntopng about page.

**Comment by codecupcake** [comment]
> What ntopng version are you using? You can find it in the ntopng about page.

3.6.181101 - Community Edition

**Comment by emanuele-f** [comment]
Please ask the package maintainer if ntopng has been compiled with the libcap (capabilities, not libpcap) library (HAVE_LIBCAP in config.status should tell you this).

**Comment by codecupcake** [comment]
I'm still testing this application, everything is new to me. can you tell me how to fix this issue?

**Comment by emanuele-f** [comment]
This seems like a packaging issue, please ask this to the pfsense guys since we do not officially support pfsense and we are not in control of the package on that platform.

**Comment by codecupcake** [comment]
Thank you
