### ISSUE TITLE
SFlow documentation is very poor

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2136]
The sFlow documentation in the user's guide is very poor. Please extend it

**Comment by simonemainardi** [comment]
a detailed blog post has been written: https://www.ntop.org/nprobe/sflow-collection-and-analysis-with-nprobe-and-ntopng/

documentation has been updated with a short description and reference to the blog post in https://github.com/ntop/ntopng/commit/a6e0a45b8d84aa770297bcace2a7f75640bd1e9b
