### ISSUE TITLE
Upscale Sampled nProbe flows

### ISSUE THREAD

**Issue by rickguise** [ntop/ntopng#2137]
Hello. I have NTopNG version 3.7.181105 - Enterprise Edition running on CentOS Linux release 7.5.1804 (Core). 

My nprobe is in collector mode with the following options:

--zmq="tcp://*:5556"
-3=2055
--flow-version 9
-n=none
-i=none
-S=1:1:100

Nprobe is not receiving sampled data, but is sending sampled data (1:100) to the ntopng collector, but the problem is that I am missing the Scaling Factor field in the interface settings menu as shown in the following screenshot.

Thank you.
![ntopng](https://user-images.githubusercontent.com/5038939/48143217-3bc4c580-e2a6-11e8-9d39-e921ec6e4bcc.PNG)

**Comment by simonemainardi** [comment]
TL;DR:

change nProbe config to:

```
 -S 1:100:100
```

------

"Ingress Packets Sampling Rate" is only available when ntopng is capturing from physical NICs. It's not available via ZMQ.

However, you can easily address your scenario by telling nProbe a `flow collection rate` equal to the `flow export rate`. In this way, probe will think it's receiving sampled flows and will up-scale them using the rate provided.

**Comment by rickguise** [comment]
OK, it is working now with -S 1 : 100 : 100. Thank you for your help.
