### ISSUE TITLE
Implement Community ID Flow Hashing

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2138]
Implement the flow community id as specified in https://github.com/corelight/community-id-spec that is required to implement #1928. Once the code is implemented, the code has to be ported to nProbe to implement a new information element containing it. Please use https://github.com/corelight/community-id-spec/blob/master/community-id.py to test your code and make sure it is compliant with the specs.

**Comment by simonemainardi** [comment]
implemented and tested in:

https://github.com/ntop/ntopng/commit/5d7113bf232fd7c058ceabb1f8083e7874307470
