### ISSUE TITLE
mark systemd startup file as service in rpm

### ISSUE THREAD

**Issue by philhagen** [ntop/ntopng#2139]
In the RPM distribution Please mark `/usr/lib/systemd/system/ntopng.service` as a config file, so custom modifications (e.g. the `--community` CLP) does not cause an update via rpm/yum to fail.

**Comment by simonemainardi** [comment]
`ntopng.service` is not a configuration file, it's a systemd unit file and it is not supposed to be changed. Configuration options, including `--community`, go into ntopng configuration file `/etc/ntopng/ntopng.conf` that is properly marked as such in the rpm.
