### ISSUE TITLE
Report for 2 interfaces - Top ASN [Average Traffic/sec] wrong information

### ISSUE THREAD

**Issue by mineumann** [ntop/ntopng#214]
When generating a report for tcp://127.0.0.1:5556 and for tcp://127.0.0.1:5557 (via filter toggle all) together the TOP ASN do not match the individual reports for the interfaces. So far i've not checked if the other values/statistics are correct. Timeframe does not matter (currently tested 1h/1d).

For example:
individual graph for tcp://127.0.0.1:5556 shows 8447 [Telekom Austria AutonomousSystem] as Top ASN with a specific GB value for "Receivers". In the combined report this AS does not show up - there are ASNs with a lower value displayed but not this TOP AS from the first interface.

**Comment by simonemainardi** [comment]
@mineumann, how did you combine the interfaces? Did you combine them through a view? Please share configuration

**Comment by mineumann** [comment]
What do you mean by "view". I have 2 ZeroMQ interfaces and created a report via "Filter Report" "Toogle All". If you need more infos plz more +v on what you need - thank you!

**Comment by simonemainardi** [comment]
@mineumann, still trying to reproduce this issue with no luck.

The 'toggle-all' report does not combine multiple interfaces. It shows statistics for each interface, one after the other. Counters of different interfaces are not added up. If you need to aggregate interfaces use views.

That said, if i create a 'toggle-all' report and I compare with single-interface reports, I get the same results. So please, if you are still experiencing this issue, contact us in private and we can arrange remote assistance

**Comment by mineumann** [comment]
Thank you - can be closed - works as intended when using views
