### ISSUE TITLE
ntop service crash after some time

### ISSUE THREAD

**Issue by gamujtaba** [ntop/ntopng#2145]
Hi team, 

I am using ntopng Community/Embedded Edition v.3.6.181103 on Netgate SG 3100, Pfsense, i am facing issue in service stability, after some time my ntop service automatically stopped. I have tried to fix but i am unable to fix i have write to pfsense they replied i need to talk ntop support, can any one help me to fix this issue.

Regards,
Ahmad

**Comment by simonemainardi** [comment]
as already explained in 

https://github.com/ntop/ntopng/issues/2132

and

https://github.com/ntop/ntopng/issues/2119

We need a core dump, or at least a stack trace, of the crash. Reopen when you can provide that.
