### ISSUE TITLE
Enhancement: Display SNMP Graphs on dashboard

### ISSUE THREAD

**Issue by Artapel** [ntop/ntopng#2147]
Good day. We are collecting SNMP traffic stats from multiple routers and would like to have it displayed on the dashboard as per the current way it is now. 

It will be ideal of we can just have the current smooth graphs used in the SNMP section moved to the Dashboard.

Regards
Corné

**Comment by simonemainardi** [comment]
Currently we can't accomodate this request as we are discussing a redesign of the dashboard, to make it configurable with draggable/customizable blocks. We are planning to release the new dashboard in release 4.0. We will keep into account this suggestion, though.

**Comment by simonemainardi** [comment]
ref: https://github.com/ntop/ntopng/issues/1670

**Comment by Artapel** [comment]
We just bought a license. Will v4 be included in this lisence?



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by simonemainardi** [comment]
License gives you 1 year of free updates. So very likely yes.
