### ISSUE TITLE
storage engine change on startup

### ISSUE THREAD

**Issue by pjaway** [ntop/ntopng#2148]
Running Ntopng on Centos 7.5.1804
MariaDB Server version 5.5.60
Ntopng version 3.6.181112 - Community Edition

Following the advise here https://www.ntop.org/ntopng/tweaking-mysql-to-improve-ntopng-flows-storage-space-usage/ I changed the flowsv4 table to Innodb

However on startup Ntop changed it back to MyISAM

MariaDB [(none)]> show processlist ;
+----+-----------+-----------+---------+---------+------+----------------------------------+-----------------------------------------+----------+
| Id | User      | Host      | db      | Command | Time | State                            | Info                                    | Progress |
+----+-----------+-----------+---------+---------+------+----------------------------------+-----------------------------------------+----------+
| 20 | ntop_user | localhost | ntop_db | Query   |  376 | Repair by sorting                | ALTER TABLE `flowsv4` ENGINE='MyISAM'   |   50.000 |

is this an issue or user error 

thanks 

PJ

**Comment by simonemainardi** [comment]
that blog article is outdated, sorry. I will update it with a note. Currently, MyISAM is the storage engine used my ntopng. Changing it to innodb will cause ntopng to set it back to MyISAM upon restart.
