### ISSUE TITLE
Add an option for LDAP referrals

### ISSUE THREAD

**Issue by Gelob** [ntop/ntopng#2149]
Ntopng should support turning off ldap referrals. In openldap this is as simple as setting "referrals no". This is highly preferred for my installation of ntopng as I only want it to query my local LDAP server in the same datacenter location directly and not any others it may get via a referral.

>  REFERRALS <on/true/yes/off/false/no>
>               Specifies  if  the  client  should  automatically  follow
>               referrals returned by LDAP servers.  The default  is  on.
>               Note that the command line tools ldapsearch(1) &co always
>               override this option.

http://www.openldap.org/software//man.cgi?query=ldap.conf&sektion=5&apropos=0&manpath=OpenLDAP+2.4-Release

**Comment by emanuele-f** [comment]
@Gelob I've added an option to disable referrals, please check out if it works properly for you. The new feature will be available in the new package in one hour.

**Comment by Gelob** [comment]
@emanuele-f its working great. thank you!
