### ISSUE TITLE
nTopNG showing gaps in Top Application Traffic Last Day View

### ISSUE THREAD

**Issue by juesor** [ntop/ntopng#215]
http://screencast.com/t/L23R5Nm5I5P4

Do you know why there are such gaps in my traffic?  My interface doesn't show the drops.

Also can I change the limits on flows and the gauge as this is a 10Gbit interface.

Also is there any reason why application does not show NetFlix when my top Remote Destination is a NetFlix server?

**Comment by lucaderi** [comment]
Do you see the red icons at the bottom? Thus us the bug in your config. Furthermore you cannot push 10G to a single ntopng without any configuration. I will soon public a post in the blog to configure ntopng at high speed.

**Comment by juesor** [comment]
So what configuration changes should i look at doing?
