### ISSUE TITLE
Multi flow in config file

### ISSUE THREAD

**Issue by inetactief** [ntop/ntopng#2150]
Hi,

We like to use config file nprobe "nprobe-none.conf:  for multi flows, is there example for this?
One flow works fine but i do not find how to setyup multi configs for more flows.

We use /etc/ntopng/ntopng.conf
We set there the mutli interfaces like:
-i=tcp://127.0.0.1:5556
-i=tcp://localhost:5557
etc..

In nprobe-none.conf we try to use:
# Vuur1 nprobe --zmq "tcp://*:5556" -i none -n none --collector-port 2055
--zmq="tcp://127.0.0.1:5556"
-i=none
-n=none
--collector-port=2055
# Vuur 3 nprobe --zmq "tcp://*:5557" -i none -n none --collector-port 2056
--zmq="tcp://localhost:5557"
-i=none
-n=none
--collector-port=2056

So ony one flow we see. 

Michel

**Comment by emanuele-f** [comment]
Hi, you need to place the two sections above in two separate nprobe configuration files, for example nprobe-none.conf and nprobe-none2.conf . Then you can start the second nprobe with `systemctl start nprobe@none2`

**Comment by inetactief** [comment]
Thanks that works!

**Comment by simonemainardi** [comment]
thanks for reporting
