### ISSUE TITLE
ntopng not getting flows from nprobe

### ISSUE THREAD

**Issue by wanderernxa** [ntop/ntopng#2152]
Hi,
I have a virtual machine with both ntopng and nprobe installed, I followed the steps outlined in the ntop.org packages site.
my /etc/nprobe conf looks like this:
--zmg="tcp://*:5556"
-i=none
-n=none
-3=2055
-T="@NTOPNG@"
-b=2
 
and my ntop.conf looks like this:
-G=/var/run/ntopng.pid
-i=tcp://127.0.0.1:5556

when I start both using:
systemctl start nprobe.service
systemctl start ntopng.service
they both start successfully but when I send flows to port 2055 from another machine (I am using a netflow generator), NTOPNG does not pick them up.

However, if I stop nprobe.service and start it manually from the command line like this:
nprobe --zmq "tcp://*:5556" -i none -n none --collector-port 2055 -T "@NTOPNG@" 
and send netflow data, then NTOPNG DOES start showing it....

Any ideas?

thanks

**Comment by emanuele-f** [comment]
The configuration file should be placed here: `/etc/nprobe/nprobe-none.conf`. Then you can start the nprobe service with `sudo systemctl start nprobe`

**Comment by wanderernxa** [comment]
thanks that worked!
