### ISSUE TITLE
Alert for long-lived flows (data exfiltration?)

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#2163]
Certain long-lived flows could hide unwanted activities such as (low-throughput) data exfiltration. It is requested to create a configurable alert for such kind of events.

**Comment by simonemainardi** [comment]
as there are protocols such Dropbox or Spotify for which it is normal to be long lived (they announce themselves) it is requested to implement this behavior only when the destination is non broadcast/multicast.

**Comment by cardigliano** [comment]
Implemented
