### ISSUE TITLE
Alert for elephant flows

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#2164]
It is requested to add alerts for flows that have more than X bytes. The alert should look at client2server and server2client directions, separately.

This is useful to detect unwanted behaviours (e.g., data exfiltration) for example when an SSH or  Dropbox flow has uploaded more than X bytes.

**Comment by victorhooi** [comment]
I'd love this feature as well!

(Our use-case is also to detect data exfiltration).

**Comment by cardigliano** [comment]
@simonemainardi please review this
