### ISSUE TITLE
http_lint.lua:1325: [LINT] _GET["application"] = "Musical.ly" parameter error: Validation error

### ISSUE THREAD

**Issue by clebig** [ntop/ntopng#2165]
Error when accessing Application Musical.ly flows.
UI -> Flows->Applications, select Musical.ly.
![screenshot from 2018-11-19 11-20-50](https://user-images.githubusercontent.com/17143757/48700795-342de680-ebed-11e8-9d6c-541a088ea3ca.png)

 Script "/usr/share/ntopng/scripts/lua/flows_stats.lua" returned an error:

/usr/share/ntopng/scripts/lua/modules/http_lint.lua:1325: [LINT] _GET["application"] = "Musical.ly" parameter error: Validation error

**Comment by simonemainardi** [comment]
thanks for reporting. Issue is fixed and will be available in the dev build starting from tomorrow.

**Comment by clebig** [comment]
Can we expect this fix to be available in the current stable release soon ?

**Comment by simonemainardi** [comment]
yes, it will be available in the stable starting from tomorrow.
