### ISSUE TITLE
Dropped flows

### ISSUE THREAD

**Issue by pjaway** [ntop/ntopng#2166]
We are currently seeing 6,300,000 Dropped flows, this only appears to happen when some housekeeping is running on the database - I have seen it when it deleting from flowsv4 

We are running 3.6.181112 - Community Edition on CentOS Linux release 7.5.1804 (Core)
free -h reports

              total        used        free      shared  buff/cache   available
Mem:           3.7G        759M        169M        3.4M        2.8G        2.6G

Database Server version: 5.5.60-MariaDB

In the ntopng gui the number of hosts are 5726 and flows 13282

My ntopng.conf -x and -X are -x 9000 -X 20000 - when at the default level we saw a high number of dropped packets, now is at 888,333 Pkts [ 0.08 % ]

am new to ntopng - so it very possible I have  missed something

**Comment by pjaway** [comment]
this is one of the deletes taken from the output of show processlist;  DELETE FROM flowsv4 where FIRST_SWITCHED < 1542468490 AND (INTERFACE_ID = 0) AND (NTOPNG_INSTANCE_NA |    0.000 |

**Comment by simonemainardi** [comment]
MyISAM, the current MySQL storage engine used, supports only table-level locking. This means that, during the execution of a DELETE query, new flows cannot be inserted into the database. Such flows are queued, waiting for the DELETE to be completed. When the delete is slow, it could happen that the queue get filled up. Flows that can't fit into the queue are dropped and this explains the 'dropped flows' you are getting.

We now the table-level locking is a limitation, but we are moving away from MySQL in favour of a special-purpose flows database, as already discussed in several issues already closed. Please, check them out. For this reason, we cannot consider switching to InnoDB now to have a row-level locking.

Finally, as per the dropped packets, 0.08% can be normal but I would use values for -x and -X much greater than the actual number of hosts and flows you have in the system. This will make ntopng searches much faster, resulting in less drops and very likely you will reach 0.00%.

**Comment by pjaway** [comment]
Many thanks
