### ISSUE TITLE
License mismatch after rename NIC in Hyper-v

### ISSUE THREAD

**Issue by BruuD86** [ntop/ntopng#2167]
i get this error after i renamed my network adapter in our hyper-v environment.
This resulted in a new mac adress for the VM.
What can i do to resolve this?

19/Nov/2018 14:14:56 [NtopPro.cpp:205] [LICENSE] /etc/ntopng.license: unable to validate Professional license [License mismatch error]
19/Nov/2018 14:14:56 [NtopPro.cpp:205] [LICENSE] /etc/ntopng.license: unable to validate Enterprise license [License mismatch error]
19/Nov/2018 14:14:56 [NtopPro.cpp:312] [LICENSE] Reading license from /etc/ntopng.license

**Comment by cardigliano** [comment]
@BruuD86 it seems that your system ID changed due to the mac address change, you have 2 options, retire the license (1 time) or use the online check. Please read https://www.ntop.org/support/faq/how-can-i-move-a-license-to-a-new-server/

**Comment by BruuD86** [comment]
Thanks i added --online-license-check and now it works again.
