### ISSUE TITLE
nagios alert configuration

### ISSUE THREAD

**Issue by giovanniesposito** [ntop/ntopng#217]
i'm unable to specify a nagios hostname different from localhost. I set my nagios hostname and click save. When i came back to preferences, nagios hostname is revert back to localhost

**Comment by simonemainardi** [comment]
Please check now. Latest commit should fix the issue. Don't forget to star ntopng ;)

**Comment by giovanniesposito** [comment]
Posso aggiornare l’installazione con yum update ?


Da: simonemainardi [mailto:notifications@github.com]
Inviato: venerdì 9 ottobre 2015 18:23
A: ntop/ntopng <ntopng@noreply.github.com>
Cc: Giovanni Esposito <info@giovanniesposito.eu>
Oggetto: Re: [ntopng] nagios alert configuration (#217)


Please check now. Latest commit should fix the issue. Don't forget to star ntopng ;)

**Comment by lucaderi** [comment]
Please wait before updating, packages will be built overnight

**Comment by giovanniesposito** [comment]
Grazie.
Invece circa la possibilità di monitorare la rete, vorrei dirti brevemente a che cosa mi riferisco (ho aperto un ticket per questo)

abbiamo varie subnet collegate in mpls
ho messo nagios direttamente sul router centrale e vedo il traffico di tutta la struttura.

Vorrei poter avere un alert quando il traffico complessivo di una certa sottorete supera una certa soglia (esempio il traffico della subnet 192.168.30.0/24)

Pensi sia possibile?

Per l’implementazione degli alert con nagios posso chiederti un supporto a pagamento?



Da: Luca Deri [mailto:notifications@github.com]
Inviato: venerdì 9 ottobre 2015 18:28
A: ntop/ntopng <ntopng@noreply.github.com>
Cc: Giovanni Esposito <info@giovanniesposito.eu>
Oggetto: Re: [ntopng] nagios alert configuration (#217)


Please wait before updating, packages will be built overnight
