### ISSUE TITLE
Handle whitelists in custom categories

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#2171]
ntopng uses lists to assign IP addresses and hostnames to categories.

Lists are used for example to raise alerts when a given hostname is assigned to the malware or mining category.

It is requested to add a whitelist of ip addresses and domains so that, when a given IP address or domain is whitelisted, it is never added to categories if found in a list.

**Comment by cardigliano** [comment]
Categories are defined in:

1. nDPI
2. List (text file)
3. GUI (Settings -> Categories)

The idea is to override categories defined in (2) removing some of the hosts defined there.
One option is doing this using a special (negative) marker for hosts defined in Settings -> Categories -> Edit Custom Hosts. 
Example:

example1.com (add to the category)
!example2.com (remove from the category if defined in the text file)

Comments are welcome.
