### ISSUE TITLE
Aggregated Flows vs Raw Flows

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#2175]
ntopng creates flow aggregates that are update in the housekeeping threads (every 5 seconds) when performing the periodic flows walk.

Flow aggregates are dumped to database every 5 minute. Therefore, it can happen that an aggregate contains traffic for a raw flow that is dumped to database in the future.

It is requested to handle flow aggregates so that they are more consistent with the raw flows -- for example it should help to update flow aggregates only when the corresponding raw flows are going to be aggregated to database when they expire or every 5 minutes if they are long-lived.

**Comment by ChathuraML** [comment]
i want to get the url list of a specific host is accessing . is it possible?

**Comment by simonemainardi** [comment]
Implemented. Aggregated flows are now updated only when the actual corresponding raw flow is written to database. This ensures consistency.
