### ISSUE TITLE
Problem with testing of ntopng with own created binary

### ISSUE THREAD

**Issue by LakshmiChowdam** [ntop/ntopng#2179]
Hi Team,

I have downloaded the source code and built it successfully by going through the link: https://github.com/ntop/ntopng/blob/dev/doc/README.compilation 

and the /etc/ntopng.conf as:
# DO NOT REMOVE the following option, required for daemonization.
-e=

# * Interfaces to sniff on: one interface per line, prefix with -i=
# If none is specified, ntopng will try to auto-detect the best interface.

-i=eth0

# * Port on which ntopng will listen for the web-UI.
-w=3000

I have started the nprobe in one window and is able to emitting flows with the following command:
**sudo nprobe --zmq "tcp://127.0.0.1:3000" -i enp1s0  -b 2**

23/Nov/2018 16:05:27 [engine.c:3002] Emitting Flow: [->][tcp] 10.0.14.158:54348 -> 10.0.59.144:3000 [5 pkt/771 bytes][ifIdx 0->0][0.0 sec][CNL: 0.593 ms][SNL: 0.011 ms][init 10.0.14.158][AS: 0 -> 0]
23/Nov/2018 16:05:27 [engine.c:3029] Emitting Flow: [<-][tcp] 10.0.59.144:3000 -> 10.0.14.158:54348 [5 pkt/279 bytes][ifIdx 0->0][0.0 sec][CNL: 0.593 ms][SNL: 0.011 ms][AS: 0 -> 0]
23/Nov/2018 16:05:27 [engine.c:3002] Emitting Flow: [->][tcp] 10.0.14.158:54349 -> 10.0.59.144:3000 [5 pkt/762 bytes][ifIdx 0->0][0.0 sec][CNL: 0.128 ms][SNL: 0.009 ms][init 10.0.14.158][AS: 0 -> 0]
23/Nov/2018 16:05:27 [engine.c:3029] Emitting Flow: [<-][tcp] 10.0.59.144:3000 -> 10.0.14.158:54349 [5 pkt/279 bytes][ifIdx 0->0][0.0 sec][CNL: 0.128 ms][SNL: 0.009 ms][AS: 0 -> 0]
23/Nov/2018 16:05:27 [engine.c:3002] Emitting Flow: [->][tcp] 10.0.14.158:54350 -> 10.0.59.144:3000 [5 pkt/637 bytes][ifIdx 0->0][0.0 sec][CNL: 0.168 ms][SNL: 0.008 ms][init 10.0.14.158][AS: 0 -> 0]
23/Nov/2018 16:05:27 [engine.c:3029] Emitting Flow: [<-][tcp] 10.0.59.144:3000 -> 10.0.14.158:54350 [5 pkt/1380 bytes][ifIdx 0->0][0.0 sec][CNL: 0.168 ms][SNL: 0.008 ms][AS: 0 -> 0]

and also started ntopng(own binary) in another window and it is waiting for collecting the flows as:
ntopng git:(dev) **sudo ntopng --community -i tcp://127.0.0.1:3000**
23/Nov/2018 15:55:33 [Ntop.cpp:1558] Setting local networks to 127.0.0.0/8
23/Nov/2018 15:55:33 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
23/Nov/2018 15:55:33 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
23/Nov/2018 15:55:33 [Ntop.cpp:1652] Registered interface tcp://127.0.0.1:3000 [id: 10]
23/Nov/2018 15:55:33 [main.cpp:308] PID stored in file /var/run/ntopng.pid
23/Nov/2018 15:55:33 [HTTPserver.cpp:951] HTTPS Disabled: missing SSL certificate /home/user/chowdam/ntopng/httpdocs/ssl/ntopng-cert.pem
23/Nov/2018 15:55:33 [HTTPserver.cpp:953] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
23/Nov/2018 15:55:33 [Utils.cpp:562] User changed to ntopng
23/Nov/2018 15:55:33 [HTTPserver.cpp:1120] Web server dirs [/home/user/chowdam/ntopng/httpdocs][/home/user/chowdam/ntopng/scripts]
23/Nov/2018 15:55:33 [HTTPserver.cpp:1123] HTTP server listening on 3000
23/Nov/2018 15:55:33 [main.cpp:390] Working directory: /var/lib/ntopng
23/Nov/2018 15:55:33 [main.cpp:392] Scripts/HTML pages directory: /home/user/chowdam/ntopng
23/Nov/2018 15:55:33 [Ntop.cpp:397] Welcome to ntopng x86_64 v.3.7.181122 - (C) 1998-18 ntop.org
23/Nov/2018 15:55:33 [Ntop.cpp:407] Built on Ubuntu 18.04.1 LTS
23/Nov/2018 15:55:33 [PeriodicActivities.cpp:68] Started periodic activities loop...
23/Nov/2018 15:55:33 [PeriodicActivities.cpp:109] Each periodic activity script will use 2 threads
23/Nov/2018 15:55:33 [NetworkInterface.cpp:2594] Started packet polling on interface tcp://127.0.0.1:3000 [id: 10]...
23/Nov/2018 15:55:34 [CollectorInterface.cpp:122] Collecting flows on tcp://127.0.0.1:3000

But the web giving the warning
"No packet has been received yet on interface tcp://127.0.0.1:3000.
Please wait 5 seconds until this page reloads."

![image](https://user-images.githubusercontent.com/41366140/48939469-594a8e00-ef3a-11e8-9c8c-e4f88e25af96.png)

Please let me know how to collect the flows on the web or am I missing something here and how to debug for any issues/features.

Thanks in advance,
Chowdam.

**Comment by emanuele-f** [comment]
Please check out https://www.ntop.org/nprobe/network-monitoring-101-a-beginners-guide-to-understanding-ntop-tools/ .

**Comment by lucaderi** [comment]
Hi Chowdam, port 3000 is used by ntopng web GUI and you cannot use it for ZMQ. Please do
-  nprobe --zmq "tcp://127.0.0.1:1234" -i enp1s0 -b 2
- ntopng --community -i tcp://127.0.0.1:1234

and it will work

**Comment by LakshmiChowdam** [comment]
Thanks a lot. Both suggestions worked.
-Chowdam.
