### ISSUE TITLE
Error while loading shared libraries: libndpi.so.1 although it's there

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#218]
ntopng: error while loading shared libraries: libndpi.so.1: cannot open shared object file: No such file or directory

although: 
/Ntop# find -name "libndpi.so.1"
./nDPI/src/lib/.libs/libndpi.so.1
and 
/Ntop# find /usr -name "libndpi.so.1"
/usr/local/lib/libndpi.so.1

**Comment by lucaderi** [comment]
On Unix the shared libraries are searched on the path specified to ldconfig. This is the problem you are facing with: configure ldconfig properly and it will work.
