### ISSUE TITLE
Wrong behaviour of traffic recording

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#2182]
- traffic recording icon appears and disappears when refreshing the page.
- The tab is empty.
- No javascript error are present.
- Enabling the traffic recording doesn't work

![image](https://user-images.githubusercontent.com/3397663/49078600-c3b34500-f23e-11e8-802b-5d478541ae3c.png)

![image](https://user-images.githubusercontent.com/3397663/49078623-cdd54380-f23e-11e8-84e2-8af2587ab163.png)

**Comment by emanuele-f** [comment]
This was already fixed with commit 6ca5e385871284005a983a638a73d5990db30da7 .
