### ISSUE TITLE
Timeseries first point problem

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2184]
The first point of all the data series with "counter" type is missing. This happens, for example, when an host appears for a little period of time (e.g. 1 minute) and then goes offline. No point is displayed into the chart. The problem is that, in order to calculate the derivative, two points are needed. Both RRD and InfluxDB "eat" the first point of any data series and use it as a basis for the derivative calculation of the next point. This is correct because the previous point of a new host is nil in the timeseries. However, ntopng still holds some data about hosts. For example, if a local host is in cache, we know its previous point value, so we could use it to effectively calculate the new derivative value when the host appears again. If the host is not cached, then we could assume that it's previous value is 0. In this way, even if an host performs a traffic for a while and the disappears, we could still see the single point into the chart.

**Comment by lucaderi** [comment]
This is a major bug that needs to be fixed ASAP as for low volume counters such as #2392 you will see no points even though there have been value in the timeseries. A possible workaround is to save (counters only) the host timeseries when it appears so you can compute the delta properly, or don't use the derivative function at all.

**Comment by emanuele-f** [comment]
Here is an analysis of the possible ways to fix this for InfluxDB. This is focused on the hosts.

## Extraction-time solutions
1. `fill(previous)`: it fills the missing points with the previous value. There are two problems though: this only applies to the visualized time range; new host will still have nil values.
2. `fill(0)`: it fills the missing points with 0. This could only be applied if we restart the host counters to 0 every time we restore it, but has an important drawback: if we skip to write a point for any reason, we will get a spike in the timeseries

## Write-time solutions
3. call `TimeseriesExporter::exportData` when host appears: this is a very light solution but can only be applied to specific timeseries as the C code does not know all the possible timeseries of an Host (only Lua knows)
4. Whenever the host appears, clone its HostStats to a temporary field, which will be exported and cleared by the Lua code during the first host dump. Drawbacks: increase in memory consumption; this does not completely solve the issue with some metrics of the hosts, e.g. nDPI stats, because when a new application appears, the first point will still be missing.

The 4th solution is the one to apply in my opinion
