### ISSUE TITLE
Special Characters problem in LDAP Bind Authentication Password

### ISSUE THREAD

**Issue by Gelob** [ntop/ntopng#2185]
When using a LDAP Bind Authentication Password with a special character of <, it got converted to a _ after input when trying to bind. Ntopng should support these special characters in the bind password. This seems similar to https://github.com/ntop/ntopng/issues/1935

**Comment by simonemainardi** [comment]
what is the ntopng version you are using? issue should be fixed in the latest dev

**Comment by Gelob** [comment]
Sorry, I am on latest version 3.7.181127 - Enterprise Edition

**Comment by simonemainardi** [comment]
I've pushed a fix. Hold on 1 hour and try again. Don't forget to change and reset the LDAP Bind Authentication Password from the ntopng preferences attempting a login.
