### ISSUE TITLE
Customize GUI

### ISSUE THREAD

**Issue by wanderernxa** [ntop/ntopng#2186]
Hi,
Is it possible to customize the GUI so that business users can easily get the information that they are asking for? 
For example, I want the display to only show web/internet traffic, something like lightsquid does. And maybe a pie chart showing the amount of usage of each type of traffic. For example the user can see that Netflix is taking up 40% of usage and the next largest chunk is HTTP, youtube, etc.
I want to keep it simple and show nothing else. How can I do that?
thanks

**Comment by emanuele-f** [comment]
Hi, this is currently not possible. There are some suggestion to make the ntopng dasboard more configurable, please check out #1670 . If you want a very specific view of the ntopng data and you can code then you could think about implementing your own gui by fetching data from ntopng. If you open the browser inspector in a realtime view you will see the underlying http requests taking place. You can build your gui on that to extract data.
