### ISSUE TITLE
Flow alerts do not tell you which policy blocked the flow

### ISSUE THREAD

**Issue by YackingCat** [ntop/ntopng#2188]
After setting a policy that that drops a protocol, flow alerts only tell you that a flow was blocked due to a configured policy. If more than protocol is set to drop, it can be very hard to tell what policy is actually dropping the traffic. If the protocol was included in the description, it would be quite helpful.

**Comment by simonemainardi** [comment]
This is implemented. We now show the policies applied to any flow in the corresponding details page so one knows exactly if  and why a certain flow has been blocked. Policies are shown both for the client and for the server.

![image](https://user-images.githubusercontent.com/3397663/56367437-8a7f6f80-61f5-11e9-8082-8a35c47fe263.png)
