### ISSUE TITLE
Interface graphs in nEdge have gaps

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2189]
In nEdge, interface counters are updated periodically with 3 seconds as the minimum interval between the updates. Interface load can affect the actual update time leading to unequal intervals, as seen in the screenshot below.

![2018-11-30_10-34](https://user-images.githubusercontent.com/5488003/49281617-e898f980-f484-11e8-8bf9-f80760ed8f54.png)

Changing the "iface:traffic" schema step to 3/4 seconds could be problematic since the ts value is written in the second.lua script.

**Comment by lucaderi** [comment]
The concept of heartbeat has to be taken into account. If your datapoints are within the heartbeat you need to interpolate them, if outside you have no measurement and thus zero. When data is extracted it must take heartbeat into account.
