### ISSUE TITLE
Not seeing applications classified properly

### ISSUE THREAD

**Issue by Gelob** [ntop/ntopng#2190]
I was previously seeing application traffic classified properly but sometime in the last few updates to the dev branch I only see ICMP, IPsec, OSPF, & GRE. Everything else is now Unknown when it used to be HTTP, HTTPS, etc. This is happening across all of my ZMQ interfaces (5)

v3.7.181130

![image](https://user-images.githubusercontent.com/422752/49305742-b643c800-f495-11e8-839c-2bd2d15e32ef.png)

**Comment by cardigliano** [comment]
@Gelob please provide the full configuration (cli or configuration file) for ntopng and zmq probe. Thank you.

**Comment by Gelob** [comment]
ntopng.conf
```
#Set PID
-G=/var/run/ntopng.pid
#Dameon mode
-e=
#Disable HTTP
-w=0
#Enable HTTPS on port 443, listening only on 1 IP vs wildcard
-W=10.6.180.182:443
#Set local networks
-m=<removed>
#Set alternate data direcotry
-d=/data/ntopng/
#Connect to nProbe interfaces over ZMQ
-i=tcp://10.1.247.98:5556
-i=tcp://10.6.181.193:5556
-i=tcp://10.3.181.193:5556
-i=tcp://10.4.181.193:5556
-i=tcp://10.8.181.193:5556
-i=tcp://10.0.247.193:5556
#Set ZMQ password
--zmq-encrypt-pwd=<removed>
#Export expired flows to MySQL
-F="mysql;localhost;ntopng;flows;ntopng;<removed>"
```

nprobe.conf

```
-n=none
--collector-port=9996
--zmq=tcp://10.1.247.98:5556
--zmq-encrypt-pwd=<removed>
-S=@1:100:1
-V=5
-b=1
```

**Comment by lucaderi** [comment]
@Gelob Is the router generating the flows adding DPI information to the flows?

**Comment by Gelob** [comment]
@lucaderi I'm not sure, How can I verify that? Isn't it nprobe job to add that information before its sent to ntopng?  This was working when I initially set it up 1-2 weeks ago. I've updated ntopng since then. I updated nprobe on one of the my boxes just see if that helped but made no difference.

ndpi-2.5.0-1438.x86_64
nProbe v.8.7.181203 (r6333)
