### ISSUE TITLE
InfluxDB Errors not accounted

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2193]
When ntopng is writing datapoints in InfluxDB sometimes errors like are reported

{"error":"partial write: max-values-per-tag limit exceeded (100048/100000): measurement=\"mac:traffic\" tag=\"mac\" value=\"00:00:00:1A:A1:AA\" dropped=7"}

It is requested to
- create an alert when they happen
- provide a solution for most common issues. For instance the above problem leads to data loss and it can be solved as described in https://stackoverflow.com/questions/43770354/max-values-per-tag-limit-exceeded-influxdb. If users are not aware of the problems, they will end up dropping information without being aware of it

**Comment by emanuele-f** [comment]
As discussed, it will be implemented in the following way:

- an alert will be created for every single error. It will include the "error" message from Influxdb.
- in case of `max-values-per-tag limit exceeded`, a specific alert will be created suggesting how to solve the problem
- documentation will be updated to include the setting to extend the max-values-per-tag
