### ISSUE TITLE
Schema Error for Hosts not present in memory

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2194]
When accessing an host that is not present in memory (e.g. though flow drill down) and the following URL is accessed

https://xxx:3000/lua/host_details.lua?ifid=0&host=192.168.1.3&page=historical&ts_schema=host:ndpi&zoom=1m&epoch=1543671232

this error is reported
01/Dec/2018 14:37:14 [host_details.lua:1937] [ts_schema.lua:103] ERROR: missing tag 'protocol' in schema host:ndpi

**Comment by emanuele-f** [comment]
I have reproduced this in the community version of ntopng, while clicking inside an host chart area. I can't find it in the flow drill down though, can you be more specific?

**Comment by emanuele-f** [comment]
Assuming it's fixed now, please reopen if necessary.
