### ISSUE TITLE
"error" ntopng compilation ( !!pfdev->license)

### ISSUE THREAD

**Issue by programmer74SHA** [ntop/ntopng#2195]
I want to compile ntopng but I have the following error.
`
g++ -g -Wall -I/usr/src/ntopng -I/usr/src/ntopng/include -I/usr/local/include -D_FILE_OFFSET_BITS=64 -I/usr/include/hiredis -I/usr/include/hiredis -I/usr/src/ntopng/third-party/mongoose -I/usr/src/ntopng/third-party/json-c  -I../nDPI/src/include -I../nDPI/src/lib/third_party/include -I/usr/src/ntopng/third-party/lua-5.3.5/src -DDONT_USE_LUAJIT   -I/usr/include/mysql  -I/usr/src/ntopng -I/usr/src/ntopng/include -I/usr/local/include -I/usr/src/ntopng/third-party/http-client-c/src/  -I/usr/include/openssl  -DDATA_DIR='"/usr/local/share"' -I/usr/src/ntopng/third-party/libgeohash -I/usr/src/ntopng/third-party/patricia   -c src/Utils.cpp -o src/Utils.o
src/Utils.cpp: In static member function 'static void Utils::listInterfaces(lua_State*)':
src/Utils.cpp:3366:57: error: 'pfring_if_t {aka struct pfring_if}' has no member named 'license'
       lua_push_bool_table_entry(vm, "license", !!pfdev->license);
                                                         ^~~~~~~
Makefile:167: recipe for target 'src/Utils.o' failed
make: *** [src/Utils.o] Error 1
`

**Comment by cardigliano** [comment]
@programmer74SHA it seems you are compiling ntopng with an old pf_ring version, please pull latest pf_ring code and let us know (or provide the version you are using). Thank you.

**Comment by programmer74SHA** [comment]
Hi dear friend @cardigliano 
I deleted all the ntopng files and compiled pf_ring 7.1.0 version . Then I compiled ntopng based on the instructions. All the process of installation run with no problems but When I send the netflow towards logstash, Im getting the following error but  the data is correctly received in logstash .Based on the  following error has the netflow been fully received in logstash or not?
`
04/Dec/2018 08:34:22 [Logstash.cpp:308] WARNING: [LS] Sending failed. Scheduling retry..
04/Dec/2018 08:34:23 [Logstash.cpp:308] WARNING: [LS] Sending failed. Scheduling retry..
04/Dec/2018 08:34:24 [Logstash.cpp:308] WARNING: [LS] Sending failed. Scheduling retry..
04/Dec/2018 08:34:25 [Logstash.cpp:308] WARNING: [LS] Sending failed. Scheduling retry..
.
.
`

**Comment by emanuele-f** [comment]
The original issue is solved, so I'm closing it. I'm added new debug messages to logstash in 6a826a7b96e598c7a655d38cc091dafd013dff1a . Please do a `git pull` and compile ntopng again. If you still experience issue, please open a new bug with new log.
