### ISSUE TITLE
Discrepancies in the Documentation

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#220]
https://github.com/ntop/ntopng/blob/dev/doc/README.SSL says:
cat privkey.pem cert.pem > /usr/local/share/ntopng/httpdocs/ssl/ntopng-cert.pem

ntopng says:
[HTTPserver.cpp:456] HTTPS Disabled: missing SSL certificate /home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng/httpdocs/ssl/ntopng-cert.pem

**Comment by lucaderi** [comment]
When ntopng starts it changes user to nobody. I believe such user cannot read your home directory  /home/actionmystique/
