### ISSUE TITLE
Error in ntopng manual?

### ISSUE THREAD

**Issue by rickguise** [ntop/ntopng#2200]
Hello,

I believe there is a misprint in the online ntopng manual, section Command Line Options (https://www.ntop.org/guides/ntopng/cli_options.html).

In the explanation for the [—interface|-i] <interface|pcap> parameter it states that:

An example of ntopng and nprobe communication is
nprobe -i eth0 -n none --zmq tcp://*:5556
ntopng -i tcp://nprobe host ip:5556

It is also possible to operate ntopng in collector mode and nProbe in probe mode (this can be useful for example when nProbe is behind a NAT) as follows (note the trailing c after the collection port)
nprobe -i eth0 -n none --zmq-probe-mode --zmq tcp://*:5556
ntopng -i tcp://nprobe host ip:5556c

but I believe that if nProbe is behind NAT and that ntopng is to be run as a collector, then it should be the other way around, that is:

nprobe -i eth0 -n none --zmq-probe-mode --zmq tcp://ip address of ntopng:5556
ntopng -i tcp://*:5556c

which is also stated in the blog https://www.ntop.org/nprobe/best-practices-for-the-collection-of-flows-with-ntopng-and-nprobe/

![using_nprobe_with_ntopng2](https://user-images.githubusercontent.com/5038939/49453361-e1525280-f7da-11e8-8492-c6b575d8952b.png)

Am I seeing this correctly? It just seems that the information from the manual is contradictory with the blog.

Best regards,
Richard

**Comment by emanuele-f** [comment]
Thank you for reporting
