### ISSUE TITLE
Implement storage monitor

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2201]
As ntopng can use quite a lot of disk space with with RRDs, InfluxDB, pcaps, and indexed flows, it is not time to consolidate usage space on a single page where we can keep disk space under control and perform cleanup operations. Currently we have an Influx disk monitor under the about menu, pcap have another threshold, ... everything is fragmented and hard to use.

Users can set a threshold (either in disk usage or GB occupied), and ntopng can trigger an (engaged / stateful) alert when such thresholds are passed. See also #2202 and consider implementing an automatic space reclaim facility that will delete older data whenever we will run out of disk space

**Comment by cardigliano** [comment]
The interface status page now shows the storage utilization with a breakdown including Timeseries, Flows, Packet Dumps.
The Runtime Status page shows the (total) disk space used by each interface.
Each component (Flows, Traffic Recording) takes care of reclaiming old data (e.g. Traffic Recording is based on the concept of Dump Window).
Volumes utilization and alerting will be implemented with the system interface.
