### ISSUE TITLE
Implement indexed flows retention policy

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2202]
Currently indexed flows stay forever on disk and this is a problem as the disk will fill up quickly.

It is requested to implement a retention policer that will harvest oldest flow directories in order to match the requested policy. As explained in #2201 disk space should be automatically reclaimed as soon as the usage goes above a certain threshold, this to avoid filling up disk space.

**Comment by emanuele-f** [comment]
Implemented in 3532d90a868f5d8713cd409f6df6e03944f22c0d
