### ISSUE TITLE
Hide Internal Traffic from Flow

### ISSUE THREAD

**Issue by koriks1111** [ntop/ntopng#2203]
Hi There, 

im very newbee with ntop, may i ask if possible to hide those traffic coming or from internal network?

**Comment by koriks1111** [comment]
or possible to filter those traffic per vlan passing thru internet and those passing thru other vlan only. 
hopefully you get my point. thanks in advance

**Comment by koriks1111** [comment]
i want to hide like below
for Example: 

traffic from VLAN 1 going to our DMZ
But the traffic from vlan 1 going to internet will be displayed

**Comment by lucaderi** [comment]
Please use
[--packet-filter|-B] <filter>       | Ingress packet filter (BPF filter)
to discard unwanted traffic from being sent to ntopng for processing

**Comment by emanuele-f** [comment]
How are you capturing the network flows? If you want to use a BPF filter you can pass the `-B "some filter"` option to ntopng. Please refer to https://www.ntop.org/guides/pf_ring/nbpf/nbpf.html for filter syntax

**Comment by koriks1111** [comment]
hi, sorry for late response due to diff time zone. :D 

should i put this in traffic Profiles?
like this

![image](https://user-images.githubusercontent.com/42999735/49550331-32229200-f926-11e8-86f9-904866bf6380.png)

**Comment by emanuele-f** [comment]
No, this should be added to the /etc/ntopng/ntopng.conf file and restart ntopng after the modification:

`-B=192.168.101.0/24`

**Comment by koriks1111** [comment]
Hi, 

if i want to hide 2 vlan traffic destination, it would be like this


-B=not ip dst net 192.168.101.0/24,192.168.x.x 
?

hiding 1 network is fine, but if multiple. i am having trouble. 
apologies for inconvenience

**Comment by koriks1111** [comment]
how about hiding the traffic between two network 

ex: Src 101.0/24 --> Destination 102.0/24

really sorry, for trouble

**Comment by emanuele-f** [comment]
You can use `and` operator and parenthesis, e.g. `(not ip dst net 192.168.101.0/24) and (not ip dst net 192.168.x.x)`
