### ISSUE TITLE
Configure SElinux/Apparmor in ntopng packages

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2204]
In recent ntopng packages there is a new script called ntopctl that is started as sudo to enable/disable specific services. Our packages lack configuration for SElinux or apparmor where installed. IT is requested to add such files in packages to prevent unwanted behaviour

**Comment by cardigliano** [comment]
Apparmor defines permission to read/write/execute files (e.g. "execute permission on sudo"), this does not add further control on the sudo or ntopctl parameters. Permission on the script to be executed is already restricted by sudo, and there is a strict sanity check for the parameters in the script itself. For this reason we decided not to add apparmor support for the time being.
