### ISSUE TITLE
Realtime Top Application Traffic values higher than possible

### ISSUE THREAD

**Issue by Gelob** [ntop/ntopng#2208]
The Realtime Top Application Traffic values that I'm seeing on the Traffic Dashboard page seem to be incorrect. The values are higher than my network interface realtime traffic and as well as my top application traffic last day view. Something just seems wrong when its showing 8Gbit/s and my interface isn't above 1Gbps and I know I'm not doing 8Gbit/s

![screen shot 2018-12-06 at 1 10 25 pm](https://user-images.githubusercontent.com/422752/49606207-5ac37f80-f958-11e8-8014-a8bea5ec0764.png)

3.7.181204 - Enterprise Edition

ntopng.conf
```
#Set PID
-G=/var/run/ntopng.pid
#Dameon mode
-e=
#Disable HTTP
-w=0
#Enable HTTPS on port 443, listening only on 1 IP vs wildcard
-W=10.6.180.182:443
#Set local networks
-m=<removed>
#Set alternate data direcotry
-d=/data/ntopng/
#Connect to nProbe interfaces over ZMQ
-i=tcp://10.1.247.98:5556
-i=tcp://10.6.181.193:5556
-i=tcp://10.3.181.193:5556
-i=tcp://10.4.181.193:5556
-i=tcp://10.8.181.193:5556
-i=tcp://10.0.247.193:5556
#Set ZMQ password
--zmq-encrypt-pwd=<removed>
#Export expired flows to MySQL
-F="mysql;localhost;ntopng;flows;ntopng;<removed>"
```

nprobe.conf

```
-n=none
--collector-port=9996
--zmq=tcp://10.1.247.98:5556
--zmq-encrypt-pwd=<removed>
-S=@1:100:1
-V=5
-b=1
-T="@NTOPNG@"
```

**Comment by simonemainardi** [comment]
This is normal when you are dealing with collected NetFlow/sFlow data. Indeed, flow data is reported by devices only at the end of the flow so ntop sees a large volume of traffic in a very short period of time and is tricked into thinking the speed is huge.

This is unavoidable and has already been discussed several times, including: https://github.com/ntop/ntopng/issues/1359#issuecomment-320949928

However, if you look at the 'last day view' the traffic volume is consistent with the speed of your interface. Indeed, on average, spikes are offset by silent period and eventually the data is correct.

If you want to mitigate the spikes, you can increase the Realtime Stats Refresh Rate  by clicking on the gauge at the bottom of any page

![image](https://user-images.githubusercontent.com/3397663/49623649-5eb8c700-f983-11e8-8576-c0b52c919093.png)

In this way, ntopng will average out the data into larger intervals and make the spikes less prominent.
