### ISSUE TITLE
SQL error: attempt to write a readonly database

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#222]
/Ntop/ntopng$ ntopng --dont-change-user -i 1
12/Oct/2015 11:12:40 [Ntop.cpp:929] Setting local networks to 127.0.0.0/8
12/Oct/2015 11:12:40 [Redis.cpp:105] Successfully connected to redis 127.0.0.1:6379@0
12/Oct/2015 11:12:40 [Ntop.cpp:1178] Registered interface view p3p1 [id: 0]
12/Oct/2015 11:12:40 [Ntop.cpp:1148] Registered interface p3p1 [id: 0]
12/Oct/2015 11:12:40 [main.cpp:237] PID stored in file /var/tmp/ntopng.pid
12/Oct/2015 11:12:40 [HTTPserver.cpp:458] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
12/Oct/2015 11:12:40 [HTTPserver.cpp:501] Web server dirs [/home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng/httpdocs][/home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng/scripts]
12/Oct/2015 11:12:40 [HTTPserver.cpp:504] HTTP server listening on port 3000
12/Oct/2015 11:12:40 [main.cpp:290] Working directory: /var/tmp/ntopng
12/Oct/2015 11:12:40 [main.cpp:292] Scripts/HTML pages directory: /home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng
12/Oct/2015 11:12:40 [Ntop.cpp:260] Welcome to ntopng x86_64 v.2.1.151011 - (C) 1998-15 ntop.org
12/Oct/2015 11:12:40 [Ntop.cpp:265] Built on Ubuntu 15.04
12/Oct/2015 11:12:40 [PeriodicActivities.cpp:53] Started periodic activities loop...
12/Oct/2015 11:12:40 [RuntimePrefs.cpp:32] Dumping alerts into syslog
12/Oct/2015 11:12:40 [Ntop.cpp:512] Adding 192.168.1.0/24 as IPv4 local network
12/Oct/2015 11:12:40 [Ntop.cpp:542] Adding fe80::8e89:a5ff:fe0e:4e89/64 as IPv6 local network
12/Oct/2015 11:12:40 [NetworkInterface.cpp:1410] Started packet polling on interface p3p1 [id: 0]...
12/Oct/2015 11:12:40 [PcapInterface.cpp:173] Terminated packet polling for p3p1
SQL error: attempt to write a readonly database
...

**Comment by lucaderi** [comment]
rm -rf /var/tmp/ntopng and start over
