### ISSUE TITLE
Implement REST API

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2220]
Implement REST API (not an API as described in #1856) for downloading information about hosts, interfaces, and alerts

**Comment by cardigliano** [comment]
REST endpoints for downloading interface, host, alerts data have been cleaned up:

- GET /lua/get_interface_data.lua
- GET /lua/host_get_json.lua
- GET /lua/get_alerts_data.lua

They have been documented using the OpenAPI format, included in the RTD documentation using the sphinxcontrib-swaggerdoc module. Some more work is required to render examples (sphinxcontrib-swaggerdoc seems to lack support for that)

**Comment by lucaderi** [comment]
Same as #2252

**Comment by cardigliano** [comment]
Endpoints renamed to:

/lua/rest/get/interface/data.lua
/lua/rest/get/host/data.lua
/lua/rest/get/alert/data.lua

**Comment by AnanthGopal** [comment]
Hi @lucaderi @cardigliano , When I trying to call rest API service I got below error

can you help me?

![Capture](https://user-images.githubusercontent.com/13050426/60530746-185bf880-9d17-11e9-8ba0-cd27236d157d.PNG)

**Comment by cardigliano** [comment]
@AnanthGopal what ntopng version are you running? (ntopng -V)

**Comment by AnanthGopal** [comment]
> @AnanthGopal what ntopng version are you running? (ntopng -V)

 v.3.8.181224

![image](https://user-images.githubusercontent.com/13050426/60531398-8d7bfd80-9d18-11e9-9396-002a19bd4319.png)

**Comment by cardigliano** [comment]
This has been implemented on Feb 18, 2019, you are running an older version, please update

**Comment by AnanthGopal** [comment]
> This has been implemented on Feb 18, 2019, you are running an older version, please update

which version can I use?

**Comment by cardigliano** [comment]
Please install latest one from our repository (we do not have other options)

**Comment by AnanthGopal** [comment]
> Please install latest one from our repository (we do not have other options)

okay, thank you for your support. I will check it

**Comment by AnanthGopal** [comment]
> Please install latest one from our repository (we do not have other options)

thank you that's working fine.

**Comment by AnanthGopal** [comment]
is topk_flows service (http://127.0.0.1:3000/lua/pro/rest/get/db/topk_flows.lua?ifid=0) needed Professional edition license?

**Comment by AnanthGopal** [comment]
How can I get flow data by using Ntop API?

![image](https://user-images.githubusercontent.com/13050426/60570638-9d82f400-9d8f-11e9-9e80-a4c48b41d7ea.png)

**Comment by cardigliano** [comment]
@AnanthGopal yes it does require a license as reported

**Comment by AnanthGopal** [comment]
hi @cardigliano @lucaderi @simonemainardi @bjornfor  
How did I use my local MySQL database? I try below comment but I got error
![image](https://user-images.githubusercontent.com/13050426/61716964-d22a1000-ad7d-11e9-8f72-cb07a92d2f9e.png)

**Comment by simonemainardi** [comment]
hi, add a `/c` right after `ntopng` and before all other options

**Comment by tuarego** [comment]
Hi,
I am trying to fetch some flows from api but without success! I am using v4.1 (enterprise) and already tried with v4.0 but no luck. Always get a empty response [].
curl -s --cookie "user=admin; password=admin" "http://127.0.0.1:3000/lua/pro/rest/get/db/flows.lua?select_clause=*&where_clause=%28IPV4_SRC_ADDR%3D5.188.148.12+OR+IPV4_DST_ADDR%3D588.148.12%29&begin_time_clause=1585248636&end_time_clause=1585248676&flow_clause=flows&maxhits_clause=10"
I can see flows from this ip address in ntopng!
Please let me know what is wrong with my query !?
Best,
Pedro.

**Comment by lucaderi** [comment]
@simonemainardi Any news?

**Comment by simonemainardi** [comment]
REST API is being completely reworked. Individual issues have been opened and marked with label  `REST API`. They can be tracked from https://github.com/ntop/ntopng/issues?q=label%3A%22REST+API%22+

**Comment by JunHu-essex** [comment]
> Hi,
> I am trying to fetch some flows from api but without success! I am using v4.1 (enterprise) and already tried with v4.0 but no luck. Always get a empty response [].
> curl -s --cookie "user=admin; password=admin" "http://127.0.0.1:3000/lua/pro/rest/get/db/flows.lua?select_clause=*&where_clause=%28IPV4_SRC_ADDR%3D5.188.148.12+OR+IPV4_DST_ADDR%3D588.148.12%29&begin_time_clause=1585248636&end_time_clause=1585248676&flow_clause=flows&maxhits_clause=10"
> I can see flows from this ip address in ntopng!
> Please let me know what is wrong with my query !?
> Best,
> Pedro.

Is there answer for it?

**Comment by cardigliano** [comment]
Did you enable nindex? (-F=nindex)

**Comment by JunHu-essex** [comment]
> Did you enable nindex? (-F=nindex)

Thank you for your fast reply. Yes, after enabling nindex, it works now!

**Comment by lulululuej** [comment]
Hi,
does anyone know how to call network discovery data from api?

![Q2](https://user-images.githubusercontent.com/68433978/88361173-cf0b9a80-cdaa-11ea-8706-b0efb87c1ccb.PNG)

**Comment by simonemainardi** [comment]
See https://github.com/ntop/ntopng/issues/3697
