### ISSUE TITLE
Create Central Multi-instance Dashboard

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2222]
Similar to "Nagios Fusion", it is requested to implement a central dashboard that allows multiple ntopng instances to be monitored for the purpose of
- health monitoring
- traffic monitoring
- alerts overview

Search from the central console will be spread on all registered instances so that you can search a host on the central location and find it on a remote one.

This central console could be implemented on one/each ntopng instance part of this network so that from each location is possible to access all other instances/

**Comment by simonemainardi** [comment]
superseded by #4056
