### ISSUE TITLE
Create timeline based on flow data

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2226]
When flows are saved permanently, it is requested to add the ability to read flow data to generate timeseries to be drawn on ntopng. This will enable for instance the creation of timelines for remote hosts that have not been saved permanently by ntopng.

**Comment by simonemainardi** [comment]
Timeline is currently implemented for alerts. A user can visualize alerts and then decide to jump to historical flows (when nIndex is enabled) that caused the alert to be generated. For the other use case of normal traffic, we believe we can stay with the current timeseries drivers that allow to handle both RRD and InfluxDB.
