### ISSUE TITLE
ntopng does not handle subprocess lifecycle

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2228]
When ntopng starts processes such as edge (used for remote support) it must also
- stop the service when ntopng stops
- restart the service when ntopng restarts

This will also apply to potential other services that ntopng spawns.

**Comment by emanuele-f** [comment]
Implemented as part of 1d6e52fb1a47a454595914b476882445407a72e9 and https://github.com/ntop/n2n/commit/3bd4e2c33519332eac63b959dbb2e7aa66da5d87
