### ISSUE TITLE
How to get callbacks after flows dump to mysql in ntopng?

### ISSUE THREAD

**Issue by sachsgiri** [ntop/ntopng#2229]
Hi,
I am using ntopng to know applications reading a pcap file and want to dump flows into mysql. I am running ntopng using this command:

 `ntopng -r myredis:6379 -F "mysql;mysqlhost;dbname;flows;username;" -i /var/data/pcaps/email.pcap --shutdown-when-done`

But I am not able to see any data in the flowsv4 or flowsv6 tables in mysql. When tried with no shudtdown-when-done, I could see the data.

I want to know exactly when the flows have been dumped so I can take further actions. Is there any way?

**Comment by emanuele-f** [comment]
Hi, to know when flows are exported you can look at the exported flows counter into the interface page:

![2018-12-12_11-52_1](https://user-images.githubusercontent.com/5488003/49865146-14f53400-fdfc-11e8-8752-89b655781c46.png)

**Comment by sachsgiri** [comment]
@emanuele-f  I am not using UI. I want the point in time, when all the flows are dumped into mysql. Is there any specific callback I can get in scripts?

**Comment by sachsgiri** [comment]
@emanuele-f  for a pcap file with -i option to ntopng cmd, I just want to get flows with applications. Thats why I am using shutdown-when-done. What is the right way to do so without being blocked?

**Comment by emanuele-f** [comment]
I see, so it seems like the flow export is not performed before the shutdown, please let me check this.
