### ISSUE TITLE
Application name unknown

### ISSUE THREAD

**Issue by anartahamim** [ntop/ntopng#223]
how do I set the Application name of the flow? In the cflow I have APPLICATION_TAG (95) and APPLICATION_NAME (96) fields, but in the browser I see Unknown Application

**Comment by yurifrancalacci** [comment]
are you using nprobe with zmq to visualise flows into ntopng?

**Comment by anartahamim** [comment]
Yes. I am using the following configuration:

# shell 1
nprobe --zmq "tcp://*:5556" -i none -n none --collector-port 2055 -b 2
# shell 2
ntopng -i tcp://localhost:5556


If you send me your mail address, I can send you personally the detailed mail because there are attached files that can't be sent to the issue track

Thanks,
Anat

**Comment by anartahamim** [comment]
When I generate the flow, for now, I set the protocol and application params hard coded in the following manner:

//type=PROTOCOL
                data_flow->protocol = 7;

                //type=IPV4_SRC_ADDR
                data_flow->src_ip = ((ezipv4_header*)packet->L3_header)->source_ip;

                //type=IPV4_DST_ADDR
                data_flow->dst_ip = ((ezipv4_header*)packet->L3_header)->destination_ip;
                
//type=L4_SRC_PORT
                data_flow->src_port = ((eztcp_header*)packet->L4_header)->source_port;

                //type=L4_DST_PORT
                data_flow->dst_port = ((eztcp_header*)packet->L4_header)->dest_port;

                //type=IN_BYTES
                data_flow->in_bytes = flow->num_bytes;//packet->frame.frame_length;

                //type=IN_PKTS
                data_flow->in_pkts = flow->num_packets;

                //type=FLOWS
                data_flow->flows = 1;

                //type=APPLICATION_TAG
                data_flow->application_tag = 8;

                //type=APPLICATION_NAME
                uint16_t application_name_len = 10
                ezdp_mem_copy(data_flow->application_name,"EPG",3);

The flow reaches ntopng. I see the it in a poor view. See below the screenshots.

Please tell me what fields do I need to pass in the flow in order to see full view in the ntop.
Can you please send me an example of a flow pcap file which generates full view in the ntop?

**Comment by lucaderi** [comment]
I have looked at your PCAP. It is raw traffic, no protocol detected by nDPI, hence the behaviour you reported looks correct to me as nprobe cannot detect the protocol. As of APPLICATION_ID/NAME they are populated by nProbe when in collect mode for Cisco/IXIA/PaloAlto

**Comment by anartahamim** [comment]
Hi Luca,

I think we have miscommunication. I don’t seem to explain myself regarding the configuration we are using. Can we please have a brief conference call?

Thanks,
Anat Rahamim,
EZchip

**Comment by anartahamim** [comment]
Hi Luca,

As we are short in time, I will try again to explain our configuration:

We are not using nprobe in a collector mode.
We are not using nDpi.

We run nprobe with the following commands:

# shell 1
nprobe --zmq "tcp://*:5556" -i none -n none --collector-port 2055 -b 2
# shell 2
ntopng -i tcp://localhost:5556

and we run our own application, which sets the PROTOCOL, the APPLICATION_TAG, the APPLICATION_NAME, the L7_PROTO and the L7_PROTO_NAME in a netflow message and sends it to the nprobe in udp on port 2055.

Can we make the ntopng present the application and L7 protocol?

We would still like to have a brief conversation with you.

Thanks,
Anat Rahamim,
EZChip

**Comment by anartahamim** [comment]
We are writing our own DPI application. We are interested to see the following applications from NetFlow reports we are sending. E.g.  BGP, VNC, Youtube, Facebook, POP3.
Is Ntopng able to display this information? What are the NetFlow fields it refers to in order to display it? Do you know what should be the values of those fields for the above applications?
