### ISSUE TITLE
New Protocol/Categories Definition

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2232]
In ntopng is it possible to define new categories (or add hosts to categories) through the web interface. However 
- this is not documented in the manual
- it is not clear how to jump from categories to protocols
- the menu protocols is used to put a protocol under a category and so it clashes with the other categories menu
- it is not clear the relation ship of the above two menu entries with
[--ndpi-protocols|-p] <file>.protos | Specify a nDPI protocol file
                                    | (eg. protos.txt)

**Comment by cardigliano** [comment]
The Protocols and Categories pages have been merged into a single menu entry Categories in 2dc59620edb19bfbbf22eaec5a5517dc4b1a5757
