### ISSUE TITLE
Timeseries/flow Storage Size

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2234]
When deploying an ntopng instance it is not clear what are the hardware requirements. This in particular for storage it is not clear how much disk space will be used for X hosts with a retention time of Y days.
Please create a page that explains this, add it to the ntopng manual, so that people can have a rough idea of the space that will be used on disk

**Comment by simonemainardi** [comment]
implemented in: https://github.com/ntop/ntopng/commit/2b66f41878ef56e82cec3b6df39ec17dd4de3369
