### ISSUE TITLE
HTTP Traffic Reports 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2235]
In the local host breakdown it is not written anywhere that it is possible to keep a list of sites visited by the host. However this can be specified in preferences.

It is requested (in case are disabled) to add a note in the host HTTP breakdown and specify that.

Furthermore as SSL (HTTPS) traffic is becoming more and more relevant, also enhance this feature also with HTTPS

**Comment by simonemainardi** [comment]
implemented and documented, both for SSL traffic as well as for plain HTTP.
