### ISSUE TITLE
ERROR: ntopng requires redis server to be up and running although it is up and running

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#224]
redis-server 
[26973] 12 Oct 12:04:57.356 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
[26973] 12 Oct 12:04:57.357 * Increased maximum number of open files to 10032 (it was originally set to 1024).
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 2.8.19 (00000000/0) 64 bit                                                                                
  .-`` .-```.  ```\/    _.,_ ''-._                                                                                                                      
 (    '      ,       .-`  | `,    )     Running in stand alone mode                                                                                     
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 26973
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

[26973] 12 Oct 12:04:57.358 # Server started, Redis version 2.8.19
[26973] 12 Oct 12:04:57.358 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
[26973] 12 Oct 12:04:57.358 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
[26973] 12 Oct 12:04:57.358 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
[26973] 12 Oct 12:04:57.358 * The server is now ready to accept connections on port 6379

/Ntop/ntopng$ ntopng -i 1 -user actionmystique
12/Oct/2015 12:07:34 [Prefs.cpp:580] ntopng will use redis actionmystique:6379@0
12/Oct/2015 12:07:34 [Prefs.cpp:797] Logging into /var/tmp/ntopng/ntopng.log
12/Oct/2015 12:07:34 [Ntop.cpp:929] Setting local networks to 127.0.0.0/8
12/Oct/2015 12:07:34 [Redis.cpp:92] ERROR: ntopng requires redis server to be up and running
12/Oct/2015 12:07:34 [Redis.cpp:93] ERROR: Please start it and try again or use -r
12/Oct/2015 12:07:34 [Redis.cpp:94] ERROR: to specify a redis server other than the default

**Comment by yurifrancalacci** [comment]
I do not know if it is a copy-paste error, but if you want to specify a different system user you have to specify it using '--' (double dash) and not just '-'.
Probably the system detects the 'r' of '-user' as the option -r to specify the redis location (checkout the following log line)
12/Oct/2015 12:07:34 [Prefs.cpp:580] ntopng will use redis actionmystique:6379@0
According to the help, I suggest you to use either --user action mystique or -U mystique in your cli

**Comment by jean-christophe-manciot** [comment]
You're right: --user instead of -user.
One complimentary question: do you know how to compile ntopng with openssl support; the" configure --help" does not talk about it.

**Comment by lmangani** [comment]
@jean-christophe-manciot please see https://svn.ntop.org/svn/ntop/trunk/attic/ntopng/README.SSL

**Comment by jean-christophe-manciot** [comment]
I already followed those guidelines.

**Comment by lucaderi** [comment]
What platform and package are you using exactly?

**Comment by jean-christophe-manciot** [comment]
ntopng x86_64 v.2.1.151014
Ubuntu 15.04

**Comment by lucaderi** [comment]
Ah I cannot help I told you. The packages are for Ubuntu 14.04 LTS. I use myself for developing Ubuntu 15.04 and if you compile from source everything will work.

**Comment by jean-christophe-manciot** [comment]
No, it does NOT work; I hope you'll take 1 mn to read the following proof:

root@msi-ge60-ubuntu:/home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng# ls -al libssl*
lrwxrwxrwx 1 actionmystique actionmystique 35 Oct 12 09:20 libssl.so -> /usr/lib/x86_64-linux-gnu/libssl.so
root@msi-ge60-ubuntu:/home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng# ./ntopng --version
v.2.1.151015 [Community Edition]
GIT rev:   dev:a35ec1ea8c86d32b5b0c64351bbabfac0b88b798:20151015
root@msi-ge60-ubuntu:/home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng# make cert
openssl req -new -x509 -sha1 -extensions v3_ca -nodes -days 365 -out cert.pem
Generating a 2048 bit RSA private key
..................+++
.....................+++
writing new private key to 'privkey.pem'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:FR
State or Province Name (full name) [Some-State]:Yvelines
Locality Name (eg, city) []:Fontenay-Le-Fleury
Organization Name (eg, company) [Internet Widgits Pty Ltd]:SIT
Organizational Unit Name (eg, section) []:Consultants
Common Name (e.g. server FQDN or YOUR name) []:ntopng.msi-ge60-ubuntu.actionmystique.net
Email Address []:manciot.jeanchristophe@gmail.com
cat privkey.pem cert.pem > httpdocs/ssl/ntopng-cert.pem
/bin/rm -f privkey.pem cert.pem
root@msi-ge60-ubuntu:/home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng# ntopng -i 1 --user root
15/Oct/2015 20:04:31 [Ntop.cpp:929] Setting local networks to 127.0.0.0/8
15/Oct/2015 20:04:31 [Redis.cpp:105] Successfully connected to redis 127.0.0.1:6379@0
15/Oct/2015 20:04:32 [PcapInterface.cpp:81] Reading packets from interface wlan0...
15/Oct/2015 20:04:32 [Ntop.cpp:1178] Registered interface view wlan0 [id: 4]
15/Oct/2015 20:04:32 [Ntop.cpp:1148] Registered interface wlan0 [id: 0]
15/Oct/2015 20:04:32 [Utils.cpp:304] User changed to root
15/Oct/2015 20:04:32 [main.cpp:237] PID stored in file /var/tmp/ntopng.pid
**************************************************************************************************
15/Oct/2015 20:04:32 [HTTPserver.cpp:458] Please read                              https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
*************************************************************************************************
15/Oct/2015 20:04:32 [HTTPserver.cpp:501] Web server dirs [/home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng/httpdocs][/home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng/scripts]
15/Oct/2015 20:04:32 [HTTPserver.cpp:504] HTTP server listening on port 3000
15/Oct/2015 20:04:32 [main.cpp:290] Working directory: /var/tmp/ntopng
15/Oct/2015 20:04:32 [main.cpp:292] Scripts/HTML pages directory: /home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng
15/Oct/2015 20:04:32 [Ntop.cpp:260] Welcome to ntopng x86_64 v.2.1.151015 - (C) 1998-15 ntop.org
15/Oct/2015 20:04:32 [Ntop.cpp:265] Built on Ubuntu 15.04
15/Oct/2015 20:04:32 [PeriodicActivities.cpp:53] Started periodic activities loop...
15/Oct/2015 20:04:32 [RuntimePrefs.cpp:32] Dumping alerts into syslog
15/Oct/2015 20:04:32 [Ntop.cpp:512] Adding 192.168.1.0/24 as IPv4 local network
15/Oct/2015 20:04:32 [Ntop.cpp:542] Adding fe80::260a:64ff:fedd:b13c/64 as IPv6 local network
15/Oct/2015 20:04:32 [NetworkInterface.cpp:1450] Started packet polling on interface wlan0 [id: 0]...
^C15/Oct/2015 20:04:45 [main.cpp:37] Shutting down...
15/Oct/2015 20:04:45 [PcapInterface.cpp:183] Terminated packet polling for wlan0
^C15/Oct/2015 20:04:46 [main.cpp:34] Ok I am leaving now

**Comment by simonemainardi** [comment]
@jean-christophe-manciot I cannot see errors or strange behaviors from the ntopng output pasted above. Everything works fine until

`15/Oct/2015 20:04:32 [NetworkInterface.cpp:1450] Started packet polling on interface wlan0 [id: 0]...`

then when you enter crtl+c twice and ntopng correctly exits.

If you are concerned about starting ntopng in HTTPS, then you have to pass the following option

`[--https-port|-W] <[:]https port>   | HTTPS port. See usage of -w above. Default: 3001`

**Comment by jean-christophe-manciot** [comment]
OK, I assumed that 443 was the default value.
