### ISSUE TITLE
Implement Local IPv4 Conversation Map

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2240]
The ARP protocol can be used to figure out who is talking to who on the local network. It is requested to create a map/dashboard of local communications overtime based on the ARP protocol, and to implement alerts based on undetected MAC-to-MAC communications

**Comment by simonemainardi** [comment]
Implemented by @FrancescoStaccini with https://github.com/ntop/ntopng/pull/2540 and related PRs
