### ISSUE TITLE
Implement Sort and Back in SNMP

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2241]
Inside /lua/pro/enterprise/snmpdevices_stats.lua it is not possible to sort columns. For instance it is not possible to sort devices according to the last sort time.

It is also request to implement a breadcrumb in SNMP navigation to avoid clicking several times on the 'back' icon to navigate across devices.

**Comment by simonemainardi** [comment]
Implemented. Sort is now possible by IP address, Name, and last poll time. In addition, a minimal breadcrumb has been implemented.
