### ISSUE TITLE
Misleading SNMP Host Location 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2242]
<img width="1149" alt="screenshot 2018-12-13 at 01 53 27" src="https://user-images.githubusercontent.com/4493366/49908279-15ccab00-fe7a-11e8-9b45-0fdb2374fe06.png">
In host info page the SNMP Info is misleading for many non-tech users. Example in the above picture the host is on port "GigabitEthernet 1/25" as all the other ports are PortChannel.

In the example below instead
<img width="389" alt="screenshot 2018-12-13 at 01 56 31" src="https://user-images.githubusercontent.com/4493366/49908337-60e6be00-fe7a-11e8-82cb-5ee8ab7d862c.png">
the host is on port "ge-0/0/18" as all other ports are trunk.

It is requested to split this information in a more readable format for non specialised users. Something like 
- highlight the port where the host is active
- report "also seen on port ...." for ports where such address has been learnt

**Comment by simonemainardi** [comment]
Implemented. Now trunk and port channels are separated and listed after access ports

![image](https://user-images.githubusercontent.com/3397663/49941256-46482f80-fee2-11e8-9412-c35a5a4c4f06.png)
