### ISSUE TITLE
Invalid SNMP Warning Message

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2243]
<img width="730" alt="screenshot 2018-12-13 at 02 00 01" src="https://user-images.githubusercontent.com/4493366/49908442-db174280-fe7a-11e8-82dc-85f183af6934.png">

The warning "Multiple MACs on non-trunk port" does not applies to trunk and port channel ports. Please fix it.

**Comment by simonemainardi** [comment]
implemented
