### ISSUE TITLE
Missing URL Anchor for Active MACs

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2244]
<img width="1160" alt="screenshot 2018-12-13 at 02 02 48" src="https://user-images.githubusercontent.com/4493366/49908517-42cd8d80-fe7b-11e8-8bb9-dd74771fb90e.png">

Mac addresses on SNMP ports must be highlighted (i.e. add URL) for those MACs that have been found in the system

**Comment by simonemainardi** [comment]
implemented
