### ISSUE TITLE
Host pool description to InfluxDB index

### ISSUE THREAD

**Issue by CDawson1** [ntop/ntopng#2247]
As we're able to pull host pool statistics created within the UI sent to InfluxDB, that's obviously the preferred method to pull data from and into Grafana.  However, the identifier created is simply a number given the host pool descriptor is arbitrary.  

As you can see, there are several pool IDs, but simply as numbers.  

![image](https://user-images.githubusercontent.com/32870121/49943022-bfde1e80-fede-11e8-8241-c0a3dd82b86e.png)

As a test, I'd deleted an old, unused pool and created a new one and it seems it may have kept the same ID, which seemingly would cause additional confusion down the road.  

Is there an easy method to match the description given to the host pool within the UI to the ID created within InfluxDB?  While any new pool created simply increments the ID by one, existing pools aren't as easily identified, thus I have no idea what ID is associated with what pool.

**Comment by emanuele-f** [comment]
Of course you could match it via an ajax request but the question is if grafana supports this. I've found this issue https://github.com/grafana/grafana/issues/1032 so I think the answer is currently no

**Comment by CDawson1** [comment]
Thanks.  That said, how easy/difficult is it to manually look this up?  As once an entry is made, it wouldn't change so a one-time lookup to manually figure it out doesn't seem too terrible.  It's just a matter of determining the ID that is created for the pool in question.

**Comment by emanuele-f** [comment]
You can browse the url `http://127.0.0.1:3000/lua/get_host_pools.lua?ifid=1` where the ifid value should corrispond to the network interface id. A simpler way for active pools is to go into the "Host Pool List" view, click on a pool and an url similar to this will be show: `http://127.0.0.1:3000/lua/hosts_stats.lua?pool=0` where the pool value is its id. Lastly, you can get a clean output by executing the following bash command:

```
for pool_id in `redis-cli smembers ntopng.prefs.1.host_pools.pool_ids`; do echo "`redis-cli hget ntopng.prefs.1.host_pools.details.$pool_id name` $pool_id"; done
```

note: again 1 is the interface id in this case

**Comment by CDawson1** [comment]
Ahh...I see.  If it was a snake...

Thanks!
