### ISSUE TITLE
RADIUS for captive portal users

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#2249]
RADIUS should work also for captive portal users. It is requested to check and possibly extend the current implementation.

**Comment by emanuele-f** [comment]
As discussed, it will be implemented in the following way:
- The "authentication" tab of the ntopng preferences will be shown in nedge too, but only for radius and local auth
- When enabled, the radius authenticator will be able to authenticate captive portal as well as gui users
- In the captive portal page, a link to the authentication preferences will explain the link between the two
