### ISSUE TITLE
interface type "view" should not be graphed in dashboard graphs

### ISSUE THREAD

**Issue by mineumann** [ntop/ntopng#225]
![ntopng](https://cloud.githubusercontent.com/assets/15014839/10429169/f77fb002-70f6-11e5-9cdd-a790f29d223f.png)

Blue and orange are two ZeroMQ endpoints and the light/grey blue is the view of the combined ZeroMQ Interfaces.

Imho this interface-type shouldn't be graphed as it makes no sense.

**Comment by simonemainardi** [comment]
@mineumann, please note that you can selectively enable/disable what to graph. You can click on colored circles to dynamically toggle each interface. It is not ideal to simply remove views from real time graphs. Indeed, some users may want to see view-aggregated information, while other may prefer to see each interface separately.

**Comment by mineumann** [comment]
Thank you - works but doesn't remember this setting when reloading or logout/login. Would be nice to be able to set this permanent.

**Comment by lucaderi** [comment]
@simonemainardi I agree with @mineumann that the view interface should not be graphed as it is misleading. Simone please remove it from the graph.

**Comment by simonemainardi** [comment]
commit 826f53b addresses this issue. Thanks @lucaderi
