### ISSUE TITLE
Implement Alarm Egress via web hook

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2251]
Add the ability to egress alerts via a web hook in JSON format in addition to the current egress supported today. Examples of popular web hooks:
- https://documentation.meraki.com/zGeneral_Administration/Other_Topics/Webhooks
- https://create.meraki.io/build/meraki-webhooks-with-json-server/

**Comment by cardigliano** [comment]
Implemented in 2002128eb43013357e9dd48a0c7af0d4bff56023
