### ISSUE TITLE
Implement REST-like call for flow extraction

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2252]
As follow up of #2220 it is requested to generate a REST-like (pure REST might be postponed until next release) call for extracting flows and pcaps.

Please make sure this API is documented in the user's guide.

**Comment by cardigliano** [comment]
New REST endpoints for querying the flow database have been created:

- GET /lua/pro/get_flows_data.lua
- GET /lua/pro/get_topk_data.lua

Pcap can be extracted using the live extraction endpoint:

- GET /lua/live_traffic_extraction.lua

They have been documented using the OpenAPI format, included in the RTD documentation using the sphinxcontrib-swaggerdoc module. Some more work is required to render examples (sphinxcontrib-swaggerdoc seems to lack support for that)

**Comment by lucaderi** [comment]
Please update the REST calls according to the fix of https://github.com/ntop/ntopng/commit/36b34389ac4976471a55b9a25a2f36a781f1b9dd and update the documentation

**Comment by cardigliano** [comment]
Endpoints renamed to:

/lua/pro/rest/get/db/flows.lua
/lua/pro/rest/get/db/topk_flows.lua
/lua/rest/get/pcap/live_extraction.lua
