### ISSUE TITLE
Assigning custom protocols to specific custom catagories

### ISSUE THREAD

**Issue by boisgada** [ntop/ntopng#2254]
We use custom protocols (specifically common ICS protocols) via the -p configuration option within ntopng.conf.  Can you provide instructions for adding a custom category (like "ICS Protocol") and adding protocols to this custom category.

**Comment by emanuele-f** [comment]
Ntopng provides some customized categories, e.g. "User Custom Category 1". Currently they cannot be renamed. Please checkout https://www.ntop.org/guides/ntopng/web_gui/categories.html#protocol-category .

**Comment by boisgada** [comment]
I did review that page but couldn't find any instructions for assigning a protocol to a custom category.  Is there a 'hidden' flag.  For example:

Format:

```
# <tcp|udp>:<port>,<tcp|udp>:<port>,.....@<proto>@<category>
tcp:502@Modbus@"ICS Protocol"

```

**Comment by emanuele-f** [comment]
Assigning from file is not supported. Please use the gui.

**Comment by boisgada** [comment]
The gui appears to only support adding hosts, not protocols.  Am I missing something?

**Comment by emanuele-f** [comment]
In the previous versions of ntopng "Protocols" was not placed into a tab but rather into a separate menu entry "Categories". Please check out the documentation link and compare it with what you have right now. It will allow you to assign a protocol (built-in or custom defined in protos.txt) to a ntopng category,

**Comment by boisgada** [comment]
This is what I see:
![screen shot 2018-12-18 at 4 56 28 pm](https://user-images.githubusercontent.com/7538766/50188124-1a63ea00-02e6-11e9-8619-01beb212644f.png)

When I select "Edit Hosts" it doesn't appear I can add a Protocol:
![screen shot 2018-12-18 at 4 55 46 pm](https://user-images.githubusercontent.com/7538766/50188175-48492e80-02e6-11e9-9749-16edc3804929.png)

I'd like the ability to:
1) Add a custom category
2) Add specific protocols to this custom category

Perhaps I'm still missing something, please advise.

**Comment by emanuele-f** [comment]
By clicking on the "Protocols" tab you can move specific protocols to the specified category. Currently it is not possible to create new categories, but you can use the provided "User custom category x" which are empty by default

**Comment by boisgada** [comment]
Thank you.  I had seen this option but thought I was missing where to create a custom category or make a bulk change.

May I request the ability to create custom groups in this issue or should I open a new feature request?

**Comment by emanuele-f** [comment]
Please open a separate issue. Adding new categories may be problematic, maybe renaming the custom ones could be an option.
