### ISSUE TITLE
ntopng edge active flows shows NoIP for the servers and shows 00:00:00:00:00:00 for devices/host Mac Addresses

### ISSUE THREAD

**Issue by odhiambop** [ntop/ntopng#2260]
Am using ntopng edge Enterprise Edition v.3.6.181128 in bridge mode(two interfaces ) with a third interface for management with an IP on management interface.
![active flows](https://user-images.githubusercontent.com/20622174/50227868-c9bcc180-03b7-11e9-9b2b-6740ba42f4d0.JPG)
![devices views](https://user-images.githubusercontent.com/20622174/50227870-ca555800-03b7-11e9-8377-32193a83a4ed.JPG)

when I go to views > active flows the column server is not showing real IP or servers that are serving clients or connected to but instead its showing **NoIP:443 (NoIP:port_number)** as show on the attached caption.

secondly its also showing no mac adresses for hosts and when I go to Views > Devices the mac addresses appear as 00:00:00:00:00:00 and Manufacturer as: Officially Xerox, but 0:0:0:0:0:0 is more common [ 0,1,2 ].

Ihave attached the two screenshot to explain this.

Kindly help out

**Comment by emanuele-f** [comment]
Hi, please double check the LAN and WAN interfaces are assigned correctly through the gui.
Do you have the possibility to switch to the dev version of nedge and see if the problem still occurs? It is pretty stable as we are in the process of releasing it as the new stable. Please check out the instructions at http://packages.ntop.org/apt to install the dev version.

**Comment by odhiambop** [comment]
I have doubled checked the LAN and WAN interfaces are assigned correctly. my _lan:enp1so_ and _wan:enp2s0_  then management interface is _eno1_

can't figure out on how to upgrade to dev version of nedge.
Am getting a challange in switching to the dev version of nedge. Kindly guide me on the commands to run.

**Comment by odhiambop** [comment]
I managed to upgrade to 3.7 but still having the same problem.

**Comment by emanuele-f** [comment]
Can you post the service log since startup? Check out `sudo journalctl -u ntopng`. Can you provide gui access to the device to debug the issue? If so, please send me the credentials at faranda@ntop.org

**Comment by odhiambop** [comment]
Hey Emanuel

I manged to figure out the issue. Some system settings changed and noted that the remote hosts were masked leading to that. When I changed no masking under preferences ans restarted it worked for me.
Thanks

**Comment by emanuele-f** [comment]
You are welcome
