### ISSUE TITLE
NTOPNG crashes regularly about every 5-10 minutes , running licensed Pro on Windows server2008

### ISSUE THREAD

**Issue by andysaje1** [ntop/ntopng#2261]
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: ntopng.exe
P2: 0.0.0.0
P3: 5baf1e2f
P4: ntdll.dll
P5: 6.1.7601.23864
P6: 595fa942
P7: c0000005
P8: 000000000004f23c
P9: 
P10: 

Attached files:

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_ntopng.exe_af6153a2456a1c749a0bb93a867bd403ae99d60_12aed117

Analysis symbol: 
Rechecking for solution: 0
Report Id: d0822230-0395-11e9-9fd2-ac162d764a83
Report Status: 0

**Comment by lucaderi** [comment]
What version are you running? 
Please attach the configuration file you are using with ntopng

**Comment by andysaje1** [comment]
The version info is below ... I don't see a config file in the ntopng directories 
Version | 3.7.180929 - Professional Edition
-- | --
Windows
2.3.0-1121-3443928
7.39.0
3.x
4.x
1.4.5
5m
2.4.6
3.7
LuaJIT 2.1.0-beta3
4.1.3
2.9.1 / 3.0

**Comment by lucaderi** [comment]
We have released on packages.ntop.org a new Windows build that should address your issue. Please give it a try when you have time. I will now close this ticket. Please reopen it if necessary
