### ISSUE TITLE
Extend Manage Stored Data to also delete flows

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2262]
This issue is tight with #2257. When deleting timeseries also flows must be deleted.

**Comment by emanuele-f** [comment]
Clicking on the "Delete Interface Data" and restarting ntopng already deletes interface flows. However, deleting a single host data do not triggers relevant flow deletion as this is not supported by the flow database. Please clarify

**Comment by emanuele-f** [comment]
Notes:
- on MySQL, it requested to remove the old flows related to the host
- for nIndex it must be discussed

Due to the impact of the operation, maybe it could be better to add a toggle in the gui to decide

**Comment by emanuele-f** [comment]
Note: MySQL flows seem to be handled by https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/delete_data_utils.lua#L97

**Comment by emanuele-f** [comment]
Has discussed, this feature cannot be implemented right now in nIndex, so a warning has been added in 736fabc5a11ead9d0bc9582615ab1dba2f76b316
