### ISSUE TITLE
Historical Data Explorer does not work with "view" interfaces

### ISSUE THREAD

**Issue by aaronmaxlevy** [ntop/ntopng#2264]
I'm running version 3.6.181030 and Historical Data Explorer does not work properly with "view" interfaces.

When I try to use Historical Data Explorer with a "view" interface, I get an error back saying "Empty query response (database down or query killed/timed out?)".

After debugging a bit with gdb, it looks like the issue is that as part of `ntop_interface_exec_sql_query` , it calls `getCurrentInterface(vm)` , which returns the currently active "view" interface which doesn't have its "db" variable set / initialized.

**Comment by simonemainardi** [comment]
Thanks for reporting. The historical data explorer is not available for view interfaces as flows are dumped to database using the underlying interfaces. Menu entry has now been hidden. To navigate dumped flows just visit the actual interfaces that compose the view.
