### ISSUE TITLE
Split protocol view

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2265]
As ntopng is now much richer than the past, the Protocols pane in both host and interface is opening a view that is too long. It is requested to break it apart in two tab/panes to make it easier to read
![screen shot 2018-12-22 at 07 45 28](https://user-images.githubusercontent.com/4493366/50371559-a95e5400-05bd-11e9-8332-4d6135bcb2b1.png)

**Comment by simonemainardi** [comment]
- split should be in two tabs, one for Applications charts and tables, and the other for Categories charts and tables.
- Also terms Applications and Protocols are used interchangeably and this creates confusion. Unify the terminology.

**Comment by simonemainardi** [comment]
Implemented.

Views are now split in two panes. One for the applications, and the other for the categories.

![image](https://user-images.githubusercontent.com/3397663/50560052-ef719100-0cfc-11e9-8bd3-0eead7af61e0.png)
