### ISSUE TITLE
Rpm install disables and stops service on centos 7

### ISSUE THREAD

**Issue by hvdbrand** [ntop/ntopng#2267]
When upgrading the ntopng rpm on CentOS 7.6, the ntopng service is disabled and stopped.
The expected behavior is that the start service is also started after the upgrade.
This seems to be cause by the preun scriptlet that stops and disables the service.

Systemd offers macros for these actions.
Would it be possible to use those?
Example: https://fedoraproject.org/wiki/Packaging:Scriptlets#Systemd
Macros: https://github.com/systemd/systemd/blob/master/src/core/macros.systemd.in

**Comment by emanuele-f** [comment]
Thank you for the hints, we will look at this

**Comment by emanuele-f** [comment]
Fixed in c032b5ac10754beb61afacc8be8c20818b385915 . Use of macros will be addressed in a different issue.
