### ISSUE TITLE
How to Analyse MikroTik Traffic Using nprobe -> ntopng on Windows

### ISSUE THREAD

**Issue by jlct021** [ntop/ntopng#2268]
We have Multiple nProbe sites with Mikrotik routers, and want to send flows to one remote ntopng instance running on a Windows machine.

Starting with the local site all behind the same Firewall / on same LAN:

Mikrotik is setup to send NetFlow to the IP of the host running nprobe & ntopng: 192.168.88.2

ntopng started as service with the below CMD:

ntopng /i -i tcp://*:5556c

And nprobe with:

nprobe /i my_nprobe --zmq "tcp://<192.168.88.2>:5556" --zmq-probe-mode -i none -n none --collector-port 2055 -T "@NTOPNG@"

As per the steps outlined here:

https://www.ntop.org/nprobe/best-practices-for-the-collection-of-flows-with-ntopng-and-nprobe/ 

However ntopng when loaded shows only:

No packet has been received yet on interface tcp://*:5556c. Please wait 6 seconds until this page reloads.

Have also tried the steps outlined below to no avail:

https://www.ntop.org/ntopng/how-to-analyse-mikrotik-traffic-using-ntopng/ 

Any help greatly appreciated,

Johan.

**Comment by emanuele-f** [comment]
Please try to replace /i with /c to see command output. Into ntopng, in the network interface page, can you see the interface rx couter increasing?

**Comment by jlct021** [comment]
Starting ntopng with:

ntopng /c -i tcp://*:5556c

and nprobe with:

nprobe /c --zmq "tcp://127.0.0.1:5556" --zmq-probe-mode -i none -n none 
--collector-port 2055 -T "@NTOPNG@"

Results in traffic being parsed to GUI running on:

http://127.0.0.1:3000/lua/hosts_stats.lua

However when selecting Hosts, Filter Hosts, Local Hosts, it outputs: No 
results found, yet we can see some of our local IPs listed under Hosts 
(main menu).

Our primary requirement right now is analyzing / recording LAN users 
internet bandwidth usage per local host / IP.

C:\Program Files\ntopng>ntopng /c -i tcp://*:5556c

===================================================================
Starting ntopng
Running ntopng.
24/Dec/2018 23:26:30 [Ntop.cpp:1545] Setting local networks to 
127.0.0.0/8
24/Dec/2018 23:26:30 [Redis.cpp:132] Successfully connected to redis 
127.0.0.1@0
24/Dec/2018 23:26:30 [Redis.cpp:132] Successfully connected to redis 
127.0.0.1@0
24/Dec/2018 23:26:30 [NtopPro.cpp:310] [LICENSE] Reading license from 
Redis
24/Dec/2018 23:26:30 [NtopPro.cpp:451] WARNING: [LICENSE] Invalid or 
missing license
24/Dec/2018 23:26:30 [NtopPro.cpp:468] WARNING: [LICENSE] ntopng will 
now run in enterprise edition for 10 minutes
24/Dec/2018 23:26:30 [NtopPro.cpp:470] WARNING: [LICENSE] before 
returning to community mode
24/Dec/2018 23:26:30 [NtopPro.cpp:472] WARNING: [LICENSE] You can buy a 
permanent license at http://shop.ntop.org
24/Dec/2018 23:26:30 [NtopPro.cpp:474] WARNING: [LICENSE] or run ntopng 
in community mode starting
24/Dec/2018 23:26:30 [NtopPro.cpp:475] WARNING: [LICENSE] ntopng 
--community
24/Dec/2018 23:26:30 [Ntop.cpp:1639] Registered interface tcp://*:5556c 
[id: 9]
24/Dec/2018 23:26:31 [HTTPserver.cpp:945] HTTPS Disabled: missing SSL 
certificate C:\Program Files\ntopng\httpdocs/ssl/ntopng-cert.pem
24/Dec/2018 23:26:31 [HTTPserver.cpp:947] Please read 
https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to 
enable SSL.
24/Dec/2018 23:26:31 [HTTPserver.cpp:1114] Web server dirs [C:\Program 
Files\ntopng\httpdocs][C:\Program Files\ntopng\scripts]
24/Dec/2018 23:26:31 [HTTPserver.cpp:1117] HTTP server listening on 3000
24/Dec/2018 23:26:31 [main.cpp:393] Working directory: 
Z:\Cloud\OneDrive\MyPC\Documents\ntopng
24/Dec/2018 23:26:31 [main.cpp:395] Scripts/HTML pages directory: 
C:\Program Files\ntopng
24/Dec/2018 23:26:31 [Ntop.cpp:390] Welcome to ntopng x64 v.3.7.180929 - 
(C) 1998-18 ntop.org
24/Dec/2018 23:26:31 [Ntop.cpp:400] Built on Windows
24/Dec/2018 23:26:31 [NtopPro.cpp:633] [LICENSE] System Id:     
2152224034-9206A1D8
24/Dec/2018 23:26:31 [NtopPro.cpp:634] [LICENSE] Edition:       
Enterprise
24/Dec/2018 23:26:31 [NtopPro.cpp:635] [LICENSE] License Type:  
Time-Limited License
24/Dec/2018 23:26:31 [NtopPro.cpp:644] [LICENSE] Validity:      Until 
Mon Dec 24 23:36:30 2018
24/Dec/2018 23:26:31 [PeriodicActivities.cpp:68] Started periodic 
activities loop...
24/Dec/2018 23:26:32 [PeriodicActivities.cpp:109] Each periodic activity 
script will use 2 threads
24/Dec/2018 23:26:32 [NetworkInterface.cpp:2581] Started packet polling 
on interface tcp://*:5556c [id: 9]...
24/Dec/2018 23:26:32 [CollectorInterface.cpp:122] Collecting flows on 
tcp://*:5556c
======================================================================================

C:\Program Files\nProbe>nprobe /c --zmq "tcp://127.0.0.1:5556" 
--zmq-probe-mode -i none -n none --collector-port 2055 -T "@NTOPNG@"

==============================================================================
Running nProbe for Windows.
24/Dec/2018 23:26:40 [nprobe.c:4168] Valid nProbe license found
24/Dec/2018 23:26:40 [nprobe.c:6092] WARNING: The output interfaceId is 
set to 0: did you forget to use -Q perhaps ?
24/Dec/2018 23:26:40 [nprobe.c:6095] WARNING: The input interfaceId is 
set to 0: did you forget to use -u perhaps ?
24/Dec/2018 23:26:40 [nprobe.c:6182] Welcome to nProbe v.8.6.181004 
($Revision: 4384 $) for Windows
24/Dec/2018 23:26:40 [nprobe.c:6192] Running on Windows
24/Dec/2018 23:26:40 [nprobe.c:6203] [LICENSE] nProbe SystemId: 
2152224034-9206A1D8
24/Dec/2018 23:26:40 [nprobe.c:6270] Sample rate [packet: 1][flow 
collection/export: 1/1]
24/Dec/2018 23:26:40 [nprobe.c:8966] Welcome to nProbe v.8.6.181004 for 
Windows
24/Dec/2018 23:26:40 [nprobe.c:7870] WARNING: Adding 
%EXPORTER_IPV4_ADDRESS to the template as nProbe is working as collector
24/Dec/2018 23:26:40 [nprobe.c:7976] Using NetFlow Packet Payload Len: 
1472
24/Dec/2018 23:26:40 [nprobe.c:7906] @NTOPNG@ expanded to " %L7_PROTO 
%IPV4_SRC_ADDR %IPV4_DST_ADDR %L4_SRC_PORT %L4_DST_PORT %IPV6_SRC_ADDR 
%IPV6_DST_ADDR %IP_PROTOCOL_VERSION %PROTOCOL %IN_BYTES %IN_PKTS 
%OUT_BYTES %OUT_PKTS %FIRST_SWITCHED %LAST_SWITCHED %SRC_VLAN  
%EXPORTER_IPV4_ADDRESS"
24/Dec/2018 23:26:40 [plugin.c:1238] 0 plugin(s) enabled
24/Dec/2018 23:26:40 [nprobe.c:8422] Each flow is 82 bytes long
24/Dec/2018 23:26:40 [nprobe.c:8423] The # flows per packet has been set 
to 16
24/Dec/2018 23:26:40 [nprobe.c:8426] IP TOS is accounted
24/Dec/2018 23:26:40 [nprobe.c:8452] Non IPv4/v6 traffic is discarded 
according to the template
24/Dec/2018 23:26:40 [nprobe.c:9231] Flows ASs will not be computed 
(missing libmxminddb support)
24/Dec/2018 23:26:40 [nprobe.c:9334] Not capturing packet from interface 
(collector mode)
24/Dec/2018 23:26:40 [util.c:4719] Initializing ZMQ as client
24/Dec/2018 23:26:40 [util.c:4738] Exporting flows towards ZMQ endpoint 
tcp://127.0.0.1:5556
24/Dec/2018 23:26:40 [collect.c:142] Flow collector listening on port 
2055 (IPv4/v6)
24/Dec/2018 23:26:40 [nprobe.c:9582] nProbe started successfully
24/Dec/2018 23:30:26 [nprobe.c:567] Received shutdown request... 
[signal: 2]
24/Dec/2018 23:30:27 [nprobe.c:6317] Flushing active flows
24/Dec/2018 23:30:27 [engine.c:3169] About to flush hash (threadId 0)
24/Dec/2018 23:30:27 [engine.c:3171] Completed hash walk (thread 0)
==================================================================================

Assistance greatly appreciated.

Best,

Johan

**Comment by emanuele-f** [comment]
Let's continue discussion via email only in order to avoid duplicating messages here.

**Comment by simonemainardi** [comment]
Please, use ntopng option `-m` to list your local networks.

For example, if your local addresses are `192.168.1.0/24` use `-m 192.168.1.0/24`

**Comment by jlct021** [comment]
Thank you,

Noted re double posting.

When starting with:

ntopng /c -i tcp://*:5556c  -m 192.168.88.0/24

nprobe /c --zmq "tcp://127.0.0.1:5556" --zmq-probe-mode -i none -n none
--collector-port 2055 -T "@NTOPNG@"

And going to Hosts-> Looking Glass in ntopng, I now have a list of my local
hosts.

1) Is this a representation of both LAN and WAN traffic, and if so how do
we tweak so that WAN only traffic is shown?
2) Is looking glass the best place to view local users total internet
usage, or if not where / how please?
3) Perhaps outside the scope of this forum, but how do we get local host
names to display rather that IP addresses?

Best,

Johan.
