### ISSUE TITLE
ntopng footer bar traffic  stats

### ISSUE THREAD

**Issue by papage** [ntop/ntopng#2269]
Hi all,

I am running an Ntopng instance getting feed from an nprobe via zmq (on another VM).
On the main screen, on the footer bar, the interface traffic rate reported is actually correct. But next to it there are these graphs of IN/OUT traffic rates, which don't add up to the interface traffic rate.  Also, the IN/OUT ratio is also very wrong and I have configured my networks. Even in your manual page (ntopng manual), you can see interface traffic of 102.60Mbps and IN/OUT traffic of 0Mbps....

So, what are these IN/OUT rates? 
Is this the traffic actually processed by my nprobe and sent as flows to ntopng and is less because nprobe can't cope with the traffic?
Has nprobe successfully processed the interface traffic but zmq messages with flow info, have been dropped on the way to ntopng?

Thanx,
Sp

**Comment by simonemainardi** [comment]
the 

![image](https://user-images.githubusercontent.com/3397663/50474495-69361180-09c1-11e9-9ed3-52b1ea2d923f.png)

traffic in the footer is not IN/OUT, it's local-to-remote and remote-to-local. So basically the traffic that goes from your local networks to non-local destinations, and vice versa.

**Comment by papage** [comment]
I understand that. I have configured my local networks and I have SPANed only my uplinks, so IN is actually the traffic towards my local networks and OUT is traffic from my local networks. I have no traffic going from remote to remote networks (transit).
The question is why the numbers don't add up to the interface traffic, why the ratio is wrong. I have assumed that because IN/OUT numbers are wrong, the IN/OUT is not just classified IN/OUT traffic but the traffic actually processes by nprobe and fwded as flows to ELK and ntopng.

Regards,
Sp

**Comment by simonemainardi** [comment]
local-to-remote and remote-to-local are with reference to the ntopng local networks specified with `-m`. can you please check this?

**Comment by papage** [comment]
Yes, I'm using --local-networks="x.y.z.0/24,a.b.c.0/21......" in the conf file.
I believe that IN/OUT rates is derived from the flows send from nprobe, while the interface traffic is a single number send from nprobe directly to ntopng as an informational element. 
Anyway, could you clarify if the IN/OUT is calculated by ntopng by adding all the IN/OUT flows sent from nprobe?

Also, how can i check, if nprobe manages to process all traffic and how many flows it is sending to zmq towards ntopng? and also how can i check how many flows ntopng really processes from zmq (coming from nprobe).
