### ISSUE TITLE
ntopng centos7 make error

### ISSUE THREAD

**Issue by wwbhl** [ntop/ntopng#2270]
src/tcp_connecter.cpp: In member function 'int zmq::tcp_connecter_t::get_new_reconnect_ivl()':
src/tcp_connecter.cpp:210:70: error: 'min' was not declared in this scope
             min (current_reconnect_ivl * 2, options.reconnect_ivl_max);
                                                                      ^
src/tcp_connecter.cpp:210:70: note: suggested alternative:
In file included from /usr/include/c++/4.8.2/bits/char_traits.h:39:0,
                 from /usr/include/c++/4.8.2/string:40,
                 from src/tcp_connecter.cpp:31:
/usr/include/c++/4.8.2/bits/stl_algobase.h:239:5: note:   'std::min'
     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^
gmake[2]: *** [src/libzmq_la-tcp_connecter.lo] Error 1
gmake[2]: Leaving directory `/ntopng/third-party/zeromq-4.1.3'
gmake[1]: *** [all-recursive] Error 1
gmake[1]: Leaving directory `/ntopng/third-party/zeromq-4.1.3'
make: *** [/ntopng/third-party/zeromq-4.1.3/.libs/libzmq.a] Error 2

**Comment by simonemainardi** [comment]
Please, install `zeromq-devel` and you will be ok. I've updated the README: https://github.com/ntop/ntopng/blob/dev/doc/README.compilation
