### ISSUE TITLE
No packet has been received yet on interface ens33

### ISSUE THREAD

**Issue by jiangdu8888** [ntop/ntopng#2271]
There are two connections, in which the interface ens33 can not accept network traffic, where the interface Lo may be connected to the database? The collection of flow can be displayed.

**Comment by jiangdu8888** [comment]
interface lo Top Application Protocols:Redis MySQL HTTP and Other

**Comment by simonemainardi** [comment]
this is correct. if you use the default setup, ntopng will connect to redis via interface loopback. The same if you have a local MySQL database. This is why you are seeing Redis, and MYSQL flows on the loopback.

**Comment by jiangdu8888** [comment]
> 这是对的。如果您使用默认设置，ntopng将通过接口环回连接到redis。如果您有本地MySQL数据库，也是如此。这就是你看到Redis和MYSQL在环回上流动的原因。

But why interface ens33 have no flow?

**Comment by simonemainardi** [comment]
very likely ens33 is not doing anything. do the following checks. is ens33 used to receive or send some traffic? is it connected to the network? is it connected to a span port or mirror?
