### ISSUE TITLE
Not showing IPv6

### ISSUE THREAD

**Issue by inetactief** [ntop/ntopng#2272]
We use a mikrotik router using netflow version 9.  On Centos 7 where running ntopng we have enabled IPv6 we can ping to a ipv6 address. 

On /etc/nprobe/nprobe-none.conf
--zmq="tcp://*:5556"
-i=none
-n=none
-T="%IP_PROTOCOL_VERSION %IPV4_SRC_ADDR %IPV6_SRC_ADDR %IPV4_DST_ADDR %IPV6_DST_ADDR %IPV4_NEXT_HOP %IPV6_NEXT_HOP %INPUT_SNMP %OUTPUT_SNMP %IN_PKTS %IN_BYTES %FIRST_SWITCHED %LAST_SWITCHED %L4_SRC_PORT %L4_DST_PORT %TCP_FLAGS %PROTOCOL %SRC_TOS %SRC_AS %DST_AS %IPV4_SRC_MASK %IPV6_SRC_MASK %IPV4_DST_MASK %IPV6_DST_MASK"
--collector-port=2055

On 
cat /etc/ntopng/ntopng.conf
-G=/var/tmp/ntopng.pid
-i=tcp://127.0.0.1:5556
--d=/var/tmp
--http-port=3000

But we see no IPv6 traffic. and we see NoIP.

**Comment by simonemainardi** [comment]
You should check your mikrotik configuration and make sure IPv6 is actually exported in the NetFlow. If unsure, please, attach a pcap of the netflow (templates + data record) and we will check for you.

**Comment by inetactief** [comment]
i record some data from the mikrotik to ntopng.

https://video-streams.nl/data-to-ntopng.zip

**Comment by simonemainardi** [comment]
we need to see the netflow mikrotik is sending to nProbe as I am not sure it contains IPv6. Please, check it. 

To create a capture, jump on the nProbe host and do:

```
tcpdump -i any -s0 -w netflow.pcap udp and port 2055
```

Then send file netflow.pcap

**Comment by inetactief** [comment]
It works now. The -T -V 9 and some config change and it works fine now!

**Comment by emanuele-f** [comment]
Thank you for reporting

**Comment by simonemainardi** [comment]
@inetactief please report the exact configuration you've used.

**Comment by inetactief** [comment]
I use for nprobe.conf and nprobe-none2.conf, nprobe-none3.conf lke this
 --zmq="tcp://127.0.0.1:5556"
-i=none
-n=none
-V=9
-T="%IP_PROTOCOL_VERSION %IPV4_SRC_ADDR %IPV6_SRC_ADDR %IPV4_DST_ADDR %IPV6_DST_ADDR %IPV4_NEXT_HOP %IPV6_NEXT_HOP %INPUT_SNMP %OUTPUT_SNMP %IN_PKTS %IN_BYTES %FIRST_SWITCHED %LAST_SWITCHED %L4_SRC_PORT %L4_DST_PORT %TCP_FLAGS %PROTOCOL %SRC_TOS %SRC_AS %DST_AS %IPV4_SRC_MASK %IPV6_SRC_MASK %IPV4_DST_MASK %IPV6_DST_MASK"
--collector-port=2055

**Comment by inetactief** [comment]
For:
/etc/ntopng/ntopng.conf

-G=/var/tmp/ntopng.pid
-i=tcp://127.0.0.1:5556
--d=/var/tmp
--http-port=3000
