### ISSUE TITLE
Raspbian segmentation fault 

### ISSUE THREAD

**Issue by tohu2000** [ntop/ntopng#2273]
Successfull **install apt-get install ntopng nprobe** leads to segmentation fault immediately after start. Raspbian Stretch, all updated and upgraded.

> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
> 
> Program received signal SIGSEGV, Segmentation fault.
> 0x75c0a654 in nettle_yarrow256_update ()
>    from /usr/lib/arm-linux-gnueabihf/libnettle.so.6
> (gdb)

**Comment by simonemainardi** [comment]
post the output of

```
sudo systemctl status ntopng
sudo systemctl status nprobe
```

and the full output of the installation

**Comment by tohu2000** [comment]
**sudo systemctl status ntopng**

> ● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis t
>    Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: e
>    Active: activating (auto-restart) (Result: signal) since Thu 2018-12-27 15:38
>   Process: 30898 ExecStopPost=/bin/sh -c /bin/echo "$(/bin/date) ntopng StopPost
>   Process: 30894 ExecStopPost=/bin/rm -rf /run/ntopng.conf (code=exited, status=
>   Process: 30889 ExecStartPost=/bin/sh -c /bin/echo "$(/bin/date) ntopng StartPo
>   Process: 30888 ExecStart=/usr/local/bin/ntopng /run/ntopng.conf (code=killed,
>   Process: 30883 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*
>   Process: 30873 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a
>   Process: 30870 ExecStartPre=/bin/sh -c /bin/echo "$(/bin/date) ntopng StartPre
>  Main PID: 30888 (code=killed, signal=SEGV)
>       CPU: 236ms

Dez 27 15:38:02 raspberrypi systemd[1]: ntopng.service: Failed with result 'sign

**sudo systemctl status nprobe**

> ● nprobe.service - nprobe extensible NetFlow v5/v9/IPFIX probe/collector for IPv
>    Loaded: loaded (/etc/systemd/system/nprobe.service; disabled; vendor preset:
>    Active: inactive (dead)

**Comment by tohu2000** [comment]
apt-get install nprobe ntopng
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Die folgenden NEUEN Pakete werden installiert:
  nprobe ntopng
0 aktualisiert, 2 neu installiert, 0 zu entfernen und 155 nicht aktualisiert.
Es müssen noch 0 B von 6.340 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 34,9 MB Plattenplatz zusätzlich benutzt.
Vorkonfiguration der Pakete ...
Vormals nicht ausgewähltes Paket nprobe wird gewählt.
(Lese Datenbank ... 116974 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../nprobe_8.7.181210-6338_armhf.deb ...
Entpacken von nprobe (8.7.181210-6338) ...
Vormals nicht ausgewähltes Paket ntopng wird gewählt.
Vorbereitung zum Entpacken von .../ntopng_3.7.181210-5678_armhf.deb ...
Entpacken von ntopng (3.7.181210-5678) ...
ntopng (3.7.181210-5678) wird eingerichtet ...
Rebuilding ld cache...
(Re)Starting ntopng...
Created symlink /etc/systemd/system/multi-user.target.wants/ntopng.service → /etc/systemd/system/ntopng.service.
nprobe (8.7.181210-6338) wird eingerichtet ...
Rebuilding ld cache...
Making the /var/log/nprobe directory...
(Re)Starting nprobe services...
Trigger für man-db (2.7.6.1-2) werden verarbeitet ...
root@raspberrypi:/home/pi#

**Comment by emanuele-f** [comment]
Cannot reproduce with latest ntopng package. The issue may be linked to an old version of libnettle6 . Please try to update both libnettle6 and ntopng and see if you still experience the issue. This is the output of `apt-cache policy libnettle6` in my test system:

```
libnettle6:
  Installed: 3.3-1
  Candidate: 3.3-1
  Version table:
 *** 3.3-1 500
        500 http://mirrordirector.raspbian.org/raspbian stretch/main armhf Packages
        100 /var/lib/dpkg/status
```

**Comment by tohu2000** [comment]
Thanks.
```
apt-cache policy libnettle6
libnettle6:
  Installiert:           3.3-1
  Installationskandidat: 3.3-1
  Versionstabelle:
 *** 3.3-1 500
        500 http://raspbian.raspberrypi.org/raspbian stretch/main armhf Packages
        100 /var/lib/dpkg/status
```
Seems up-to-date. Any other idea to narrow down the issue?

**Comment by emanuele-f** [comment]
Have you updated ntopng to the latest version? Can you get a full stack trace? Run `bt` into gdb after the crash

**Comment by tohu2000** [comment]
Thanks Emanuele, post installing apache and nagios, interestingly, ntopng started to work properly!
