### ISSUE TITLE
Package and release index query tool

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2275]
As of 3.8 nIndex is part of ntopng. However it is possible only to extract flows using the ntopng drill down interface. It would be nice to either package the nIndex extraction tool or provide a REST API call for ntopng to allow that.

**Comment by Gelob** [comment]
Any update on when such a tool would be released or the REST API to query such data functionality?

**Comment by simonemainardi** [comment]
Added and tested. Packages correctly generate and install.

binary `nindex` is now available in all supported ubuntu, debian and centos distros except for centos6 which doesn't support nIndex.
