### ISSUE TITLE
Detect continuous recording already active

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2276]
ntopng is unable to detect n2disk already active on the same system where ntopng is also running. This pushes users to start n2disk only from pithing ntopng, that is not optimal as users might want to fine-tune n2disk.

It is requested ntopng to detect (in addition to those instances spawn by ntopng) existing n2disk instances and handle them as if they were started by ntopng. For the beginning it would be nice (without doing complicated things) to see if the instance started with "service n2disk status" is up and handle it (or something like that). Please pay attention to the network interface where n2disk and ntopng is active so that you can mark correctly ntopng and n2disk instances.

**Comment by simonemainardi** [comment]
Detection of an already-active manually-managed recording service is now done. The status is shown as well as if it was started by ntopng.

Now working on the implementation of the timeline-based extraction using the timeline and the pcaps created by the manually-managed service.
