### ISSUE TITLE
Radius/LDAP caching must be limited in time

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2277]
Caching is used in ntopng in order to avoid contacting external authentication services too often. Examples include LDAP and Radius. However currently the caching time is 1h and this is a little bit too much. 

It is requested to reduce it to at most 15 mins. No preference is necessary. When the timeout is past, the user needs to be revalidated (but not logged out from the GUI)

**Comment by simonemainardi** [comment]
midnight session cleanup has been implemented in 28e87d93bc6ac8ef712a27467453221e21d760c6 and 332f0c320701edb71a64f18df4a382fd1f56493d.

A new preference is now available.

![image](https://user-images.githubusercontent.com/3397663/50829920-5a971500-1346-11e9-86ed-d92200fa07f6.png)
