### ISSUE TITLE
Cleanup Radius/LDAP caching at midnight

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2278]
As follow up to #2277, make sure that in all cases caching will not go beyond midnight. This requires authentication to be re-validated past midnight.

Please also make sure that any other security-related caching is also limited to the day it is set.

**Comment by simonemainardi** [comment]
Session duration has now bee made configurable. Implementation is in 28e87d9 and 332f0c3.

Duration can be configured from a new preference.

![image](https://user-images.githubusercontent.com/3397663/50829994-9f22b080-1346-11e9-8627-50bba6c75d6e.png)
