### ISSUE TITLE
Report Top 100 Visited sites by Cento & nTopng with ZMQ Method

### ISSUE THREAD

**Issue by HoseinKashefi** [ntop/ntopng#2282]
Combination of Cento and nTopNG is powerful and one of the features that needed for Service-Providers is analyzing users behavior. so please make that happen to find out which sites visited by users and even categorize them for better analyze.

**Comment by HoseinKashefi** [comment]
Dear Simone 
would you please tell me if there is any update.

**Comment by simonemainardi** [comment]
merged with #251
