### ISSUE TITLE
after some update now after running for a while GB values appear

### ISSUE THREAD

**Issue by majed17** [ntop/ntopng#2284]
the duration becomes 10 years or more, and of course the 6.66 satanic value appears for the amount transferred for most hosts. some values are dns related, any idea what is the problem?

**Comment by emanuele-f** [comment]
Hi, please report the ntopng version (run `ntopng --version`) and configuration (usually `/etc/ntopng/ntopng.conf`) used

**Comment by majed17** [comment]
ntopng --version
```
v.3.8.190101    [Enterprise/Professional build]
GIT rev:        3.8-stable:58d7eb5c98aa34c1217c108a880921e2f8680e67:20190101
Pro rev:        r2168
Built on:       Ubuntu 18.04.1 LTS
System Id:      68A93B855905A21F
Platform:       x86_64
Edition:        Enterprise
License Type:   Time-Limited
Validity:       Until Wed Jan  2 12:15:41 2019
```

```
-G=/var/run/ntopng.pid

-e=

# -i=eth1
# -i=eth2

-w=3000

# -m=10.10.123.0/24
# -m=10.10.124.0/24
--local-networks="10.0.0.0/8"

-n=1

# -S=

# -d=/var/tmp/ntopng

# -q=

#NetFlow Listening Port for NProbe Flow
#This is how NProbe and Ntopng talk
--interface="tcp://127.0.0.1:5556"
```

**Comment by emanuele-f** [comment]
Hi, please note that the license is expired. Have you upgraded nprobe to the latest version? Can you post a screenshot of the incorrect flows?

**Comment by majed17** [comment]
![ntop-screwedup](https://user-images.githubusercontent.com/35138065/50592035-6a74ac00-0ea3-11e9-9818-1de92229718c.png)
 nprobe --version

```
Welcome to nProbe v.8.6.190101 (r6311) for x86_64-pc-linux-gnu
with native PF_RING acceleration.
Copyright 2002-18 ntop.org

Build OS:      
SystemID:      68A93B855905A21F
GIT rev:       8.6-stable:b70db8061ef8d78668c530fdfa4cdbe009d536ea:20190101
License:       Invalid nProbe license (/etc/nprobe.license) [Missing license file]

nProbe is subject to the terms and conditions defined in
the LICENSE and EULA files that are part of this package.

nProbe also contains third party code:
Radix tree code - (C) The Regents of the University of Michigan
                      ("The Regents") and Merit Network, Inc.
sFlow collector - (C) InMon Inc.

I never installed a license in the first place!
```

**Comment by majed17** [comment]
Note: an ISR router was added in this period too!

**Comment by emanuele-f** [comment]
While the ntopng license is optional (you can add the `--community` option to the ntopng options) the nprobe license is mandatory and missing. Please go back to a standard ntopng setup (no theme/scripts modifications) and install the nprobe license (or ask for a trial) before proceeding

**Comment by majed17** [comment]
so how to request a trial license for nprobe? I just couldn't find it.

**Comment by emanuele-f** [comment]
http://www.ntop.org/support/need-help-2/contact-us/

**Comment by majed17** [comment]
So I installed the license but the problem remains... i also added maximum hosts and connections

**Comment by emanuele-f** [comment]
Can you post your nprobe configuration and the new ntopng config? Can you send me a pcap at faranda@ntop.org with some netflow/sflow traffic captured by nprobe? E.g. with `tcpdump -s0 -n -i any port 2055 -w netflow.pcap`

**Comment by majed17** [comment]
```
-G=/var/run/ntopng.pid

-e=
       

-w=3000

--local-networks="10.0.0.0/8"

-n=1

# memory usage
--max-num-flows=200000
--max-num-hosts=250000


--interface="tcp://127.0.0.1:5556"
```
```


-g=/var/run/nprobe.pid

-G=

-i=none

-n=none

-3=2055

--zmq="tcp://*:5556"

--flow-version=5
```

**Comment by emanuele-f** [comment]
Thank you, there is an issue with fragmented packets, please follow https://github.com/ntop/nProbe/issues/327
