### ISSUE TITLE
Implement hello.ntop.org DNS mapping

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2288]
When installing nEdge (in bridge mode, but if possible also with routing would be nice to have) with a dynamic IP address, unless there is a static IP address, it is hard to locate a nEdge box. 

Implement the ability to use hello.ntop.org to locate the nEdge box regardless of its current IP address. This can be implemented looking at the DNS packets and in case there is a request for hello.ntop.org return as DNS response the IP address of the LAN interface of the nEdge box

**Comment by emanuele-f** [comment]
Support was already present but bugged, now fixed
