### ISSUE TITLE
Realtime Traffic problem with disaggregation probe IP

### ISSUE THREAD

**Issue by M9k** [ntop/ntopng#2292]
Hi all,
I have one probe with ~20 interfaces (Disaggregation Criterion: Probe IP), all the displayed data are correct except for the realtime traffic.
The interfaces all belong to different devices.
I only see the data from the probe itself and the first 6 interfaces (not the top ones), all with the same value over time between them or 2 value.
Sometimes the values are correct and not duplicated.

![immagine](https://user-images.githubusercontent.com/9288402/50692622-d2a6c780-1034-11e9-80a2-94c5b7570b50.jpg)

I have this problem for some time and with some versions, now I'm using ntopng.x86_64 0:3.9.190104-5596 and nprobe.x86_64 0:8.7.190104-6357 on two distinct machine, both with Centos.

**Comment by emanuele-f** [comment]
Is the last day view correct?

**Comment by M9k** [comment]
In the last day view I see the same interfaces of realtime traffic, but the data is correct.

**Comment by M9k** [comment]
And also the Traffic Report is correct, the data is unique for each interface and I can see all of them.

**Comment by emanuele-f** [comment]
I can't see too reproduce it. If you hide one or more of the interfaces, do the other show up properly? How much time to wait for the issue to appear?

**Comment by M9k** [comment]
If I hide one interface the others keep the same value, the issues appear immediately when I open the Traffic Dashboard.
If you want I can give you a TeamViewer session to see the bug, it's pretty strange and delimited to the realtime traffig graphic only.

**Comment by emanuele-f** [comment]
A gui access would be fine too, as you prefer, please contact me via telegram or email at faranda@ntop.org Thank you

**Comment by emanuele-f** [comment]
~~The bug is a clash on the interface name (which does not consider the disaggregation criteria)~~
The bug is probably related to the use of the remote_bps data, which is not consistent when using dynamic disaggregation

**Comment by emanuele-f** [comment]
@M9k the new package will be available in an hour. Please update and let me know if the issue is fixed.

**Comment by M9k** [comment]
Fixed, thanks a lot!

**Comment by emanuele-f** [comment]
Thank you for helping me troubleshooting this
