### ISSUE TITLE
Missing n2disk stats

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2294]
In ntopng with continuous recording, it is possible to see only the recording status but no stats are reported. This is a problem as it is not possible to know the recording status, drops etc. It would be enough to read from /proc

# cat /proc/net/pf_ring/stats/7302-eth0.119 
Duration:          0:00:15:55:128
Throughput:        0.00 Mpps	0.00 Gbps
Packets:           97506
Filtered:          97506
Dropped:           0
Bytes:             19748216
DumpedBytes:       19323631
DumpedFiles:       16
SlowSlavesLoops:   0
SlowStorageLoops:  0
CaptureLoops:      949494
FirstDumpedEpoch:  1546463100
LastDumpedEpoch:   1546879019
BytesOnDisk:       3749692150
TimelinePath:      /var/lib/ntopng/0/timeline

It is required to implement this feature.

**Comment by simonemainardi** [comment]
this will be handled as part of #2497
