### ISSUE TITLE
Automatically generate traffic reports

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2295]
ntopng has great reporting capabilities on the embedded web interface, however it falls short when sending reports via email (HTML or PDF). It would be nice to have the ability to generate reports in a way that they could be sent and shared among people without having to connect to the web interface.

Reports are requested (at least) per
- host
- network interface

and they need to be sent periodically (e.g. every night) at specific recipients (to be better elaborated when the development is in progress).

**Comment by emanuele-f** [comment]
Exporting simple tabular data is not a problem. Here is an example of using wkhtmltopdf to produce a pdf from an host weekly traffic report (C bindings also exist: https://wkhtmltopdf.org/libwkhtmltox).

![2019-01-09_11-41_1](https://user-images.githubusercontent.com/5488003/50894452-31848c00-13fb-11e9-8e66-d0d09208fe1b.png)

An alternative approach could be to manually "draw" the pdf contents, but it can be time expensive to provide both html and pdf outputs for the existing tables.

A problem with report generation arises with charts. wkhtmltopdf does not work properly with such charts. https://github.com/novus/nvd3/issues/218 suggests using phantomjs, but this would require an external tool

**Comment by 61swong** [comment]
Whilst looking for option to automate the WAN report monthly, I found this issue still open and wonder if it is still on the 'enhancement' list. As an end user, we are interested in the weekly and monthly report as a review to the WAN usage and pattern change in case of unexpected change in the routing or backup job schedule.

**Comment by MatteoBiscosi** [comment]
Now report can automatically be generated and customized with the the report/dashboard page
