### ISSUE TITLE
Add Custom IP Blacklists

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2296]
In both ntopng and nEdge, it is possible to specify some IP addresses that identify hosts with malware (see Malware Alerts). Such feature it is based on a blacklist that is downloaded overnight.

It would be nice to extend this feature making it more general, by allowing people to complement the list with additional custom lists.

**Comment by emanuele-f** [comment]
This is a sample mockup for the gui:

![2018-10-11_15-07](https://user-images.githubusercontent.com/5488003/50896038-c5585700-13ff-11e9-9166-a3f5be843a26.png)

The user can click on the plus button to configure an url, poll interval, and category. We can support files in the linux hosts file format.

**Comment by simonemainardi** [comment]
add also : https://talosintelligence.com/documents/ip-blacklist

**Comment by simonemainardi** [comment]
add also: https://abuse.ch/#projects

**Comment by emanuele-f** [comment]
Initial work (lists caching and automatic reload of builtin lists): 7e0117fd129d2852e45ebdc29fc82fa193669ea3

**Comment by emanuele-f** [comment]
As of 6bbb828ead0a8f48731a169d420545c1bd176767, lists can now be edited from the "Category Lists" page. Only built-in lists are supported for now (no ability to add new custom lists). Implementing custom lists addition would be quite trivial now.

**Comment by simonemainardi** [comment]
make sure to handle the case where a blacklisted host is no longer blacklisted after a list update

**Comment by emanuele-f** [comment]
Addressed in 2525b82ca4278bf0b79e955404397b8c9fe47c91

**Comment by emanuele-f** [comment]
Closing as we've decided that the current implementation is enough to fulfill the current users requirements. A blog post will explain the new features.
