### ISSUE TITLE
Create metric with exported flows/sec

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2300]
Similar to what happens with NetFlow, it would be nice in ntopng to create a metric that contains the number of flow exports/sec. Likewise it would be nice to also have a graph of number of ingress flows in case of flow collection

**Comment by emanuele-f** [comment]
Implemented in e3952dbb4819d253f74d6cdf162e621d15e1057d . Zmq flow exports already monitored.

**Comment by lucaderi** [comment]
![screen shot 2019-01-13 at 19 53 32](https://user-images.githubusercontent.com/4493366/51089419-f53f8b80-176c-11e9-988d-15ba0bf67bb0.png)
I can't see it in the menu
