### ISSUE TITLE
Internet usage for Local Hosts

### ISSUE THREAD

**Issue by jlct021** [ntop/ntopng#2301]
Mikrotik router with NetFlow forwarding to Windows PC:

When starting with:

ntopng /c -i tcp://*:5556c  -m 192.168.88.0/24

nprobe /c --zmq "tcp://127.0.0.1:5556" --zmq-probe-mode -i none -n none --collector-port 2055 -T "@NTOPNG@"

And going to Hosts-> Looking Glass in ntopng, I have a list of local hosts.

1) Is this a representation of both LAN and WAN traffic, and if so how do we tweak so only WAN traffic is shown?
2) Is looking glass the best place to view local users total internet usage, or if not where / how please?
3) Perhaps outside the scope of this forum, but how do we get local host names to display rather that IP addresses?

Best,

Johan.

**Comment by emanuele-f** [comment]
That view shows the local hosts sorted by a criteria. Another view which shows local hosts traffic is the Hosts -> Hosts with a filter "Local Hosts Only" from the dropdown on the right.

The traffic shown depends on the information exported by your mikrotik. [Here](https://wiki.mikrotik.com/wiki/Manual:IP/Traffic_Flow) you can find instructions on how to configure the interface to export.

Regarding the hosts name, with this setup you cannot extract such information automatically from the packets. However, ntopng should try to resolve the host name (see `--dns-mode`).
