### ISSUE TITLE
Unable to start after upgrade to version 3.9.190110-5943

### ISSUE THREAD

**Issue by wantaquddin** [ntop/ntopng#2302]
I've upgraded ntopng to version 3.9.190110-5943 (on Raspbian Stretch). Now it longer starts.

running "service ntopng status" displays this:
* ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: signal) since Fri 2019-01-11 10:23:31 +08; 2s ago
  Process: 19394 ExecStopPost=/bin/sh -c /bin/echo "$(/bin/date) ntopng StopPost" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
  Process: 19391 ExecStopPost=/bin/rm -rf /run/ntopng.conf (code=exited, status=0/SUCCESS)
  Process: 19375 ExecStartPost=/bin/sh -c /bin/echo "$(/bin/date) ntopng StartPost" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
  Process: 19374 ExecStart=/usr/local/bin/ntopng /run/ntopng.conf (code=killed, signal=SEGV)
  Process: 19369 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|^[ ]*--pid.*/s/^/#/" /etc/ntopng/ntopng.conf > /run/ntopng.conf (c
  Process: 19359 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code
  Process: 19355 ExecStartPre=/bin/sh -c /bin/echo "$(/bin/date) ntopng StartPre" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
 Main PID: 19374 (code=killed, signal=SEGV)

Running "journal -xe" display this message:

Jan 11 10:26:19 raspberrypi systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
-- Subject: Unit ntopng.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit ntopng.service has begun starting up.
Jan 11 10:26:19 raspberrypi systemd[1]: Started ntopng high-speed web-based traffic monitoring and analysis tool.
-- Subject: Unit ntopng.service has finished start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit ntopng.service has finished starting up.
-- 
-- The start-up result is done.
Jan 11 10:26:19 raspberrypi ntopng[20419]: 11/Jan/2019 10:26:19 [Ntop.cpp:1913] Setting local networks to 127.0.0.0/8
Jan 11 10:26:19 raspberrypi ntopng[20419]: 11/Jan/2019 10:26:19 [Redis.cpp:146] Successfully connected to redis 127.0.0.1:6379@0
Jan 11 10:26:19 raspberrypi ntopng[20419]: 11/Jan/2019 10:26:19 [Redis.cpp:146] Successfully connected to redis 127.0.0.1:6379@0
Jan 11 10:26:19 raspberrypi ntopng[20419]: 11/Jan/2019 10:26:19 [NtopPro.cpp:311] [LICENSE] Reading license from Redis
Jan 11 10:26:19 raspberrypi ntopng[20419]: 11/Jan/2019 10:26:19 [NtopPro.cpp:208] [LICENSE] BA819FB128CB774704D486893C8A8A491576799192943B3D21: found valid En
Jan 11 10:26:21 raspberrypi sudo[20425]:       pi : TTY=pts/0 ; PWD=/home/pi ; USER=root ; COMMAND=/bin/journalctl -xe
Jan 11 10:26:21 raspberrypi sudo[20425]: pam_unix(sudo:session): session opened for user root by (uid=0)

Is it possible to downgrade the version via apt-get? I couldn't remember the last version number that woked.

**Comment by wantaquddin** [comment]
As a temporary workaround, I've downgraded nprobe to version 8.7.181227-6356 and ntopng to version 3.9.181227-5849

**Comment by emanuele-f** [comment]
Please wait an hour until the new package is ready

**Comment by wantaquddin** [comment]
Noted and thanks.
