### ISSUE TITLE
Dashboard does not handle network latency

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2304]
When latency is too high, dashboard continues to flood the server with ajax requests. Moreover, older requests are not aborted so the number of in-flight requests continues to rise

**Comment by simonemainardi** [comment]
it is requested to start a new request only when the previous one has been executed.

This is the approach that can be followed:
```
function fetchdata(){
 $.ajax({
  url: 'fetch_details.php',
  type: 'post',
  success: function(data){
   // Perform operation on return value
   alert(data);
  },
  complete:function(data){
   setTimeout(fetchdata,5000);
  }
 });
}

$(document).ready(function(){
 setTimeout(fetchdata,5000);
});
```

I would also keep into account the latency taken by the ajax request to complete and subtract it from the new setTimeout

**Comment by emanuele-f** [comment]
Fixed. Now a warning redirecting to the "Realtime Stats Refresh Rate" preference is shown.
