### ISSUE TITLE
Gridcoin exited. How to solve this?

### ISSUE THREAD

**Issue by mariajohnfranklin** [ntop/ntopng#2306]
I am getting an error.
gridcoinresearchd not started.  My debug.log showing this status

1/12/19 08:14:47 Gridcoin version v4.0.1.0-g2dfe71501 (2018-11-30 19:03:02 +0100)
01/12/19 08:14:47 Using OpenSSL version OpenSSL 1.1.1  11 Sep 2018
01/12/19 08:14:47 Default data directory /root/.GridcoinResearch
01/12/19 08:14:47 Used data directory /root/.GridcoinResearch
01/12/19 08:14:47 dbenv.open LogDir=/root/.GridcoinResearch/database ErrorFile=/root/.GridcoinResearch/db.log
01/12/19 08:14:47 Stop RPC IO service

01/12/19 08:14:47 RPC IO server not started

01/12/19 08:14:47 Loading block index...
01/12/19 08:14:47 Mode=Prod
01/12/19 08:14:47 Opening LevelDB in /root/.GridcoinResearch/txleveldb
01/12/19 08:14:47 Transaction index version is 180015
01/12/19 08:14:47 Opened LevelDB successfully
01/12/19 08:14:47 Loading DiskIndex 0
01/12/19 08:14:47 Time to memorize diskindex containing 1 blocks :               0ms
01/12/19 08:14:47 Time to calculate Chain Trust               0ms
01/12/19 08:14:47 LoadBlockIndex(): hashBestChain=000005a247b397eadfef  height=0  trust=1048577  date=10/11/14 13:22:57
01/12/19 08:14:47 Verifying last 0 blocks at level 1
01/12/19 08:14:47 Time to Verify Blocks               0ms
01/12/19 08:14:47 Set up RA
01/12/19 08:14:47 Gridcoin exited
01/12/19 08:14:47 Wait for 0 threads to join.

**Comment by lucaderi** [comment]
I think you have posted this ticket to the wrong github repository

**Comment by mariajohnfranklin** [comment]
yes sorry.
