### ISSUE TITLE
Implement interface check

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2307]
When configuring interfaces in nEdge, it is important to check with a ping if the interfaces are properly plugged or if cables are swapped.
Implement this check during configuration and report a warning when interfaces are not properly plugged. This check should also be available somewhere on the GUI for checking the interface state (and in the future other things like DNS etc) to be run as "nEdge doctor" for detecting issues.

**Comment by emanuele-f** [comment]
We came to the conclusion that the easiest way to implement this is by sending an ARP request and waiting for a reply on the physical network interface in a similar way as the network discovery does. This should be exposed to lua via an api (possibly a blocking call).

**Comment by simonemainardi** [comment]
For the time being, we believe the information provided by the nEdge dashboard suffice to recognize proper configuration of WAN and LAN.
