### ISSUE TITLE
Get Nothing in the Flow Section

### ISSUE THREAD

**Issue by Ryananana** [ntop/ntopng#2308]
Get Nothing in the FLOW section after upgrade to 3.9.190113
![snipaste_2019-01-13_12-03-06](https://user-images.githubusercontent.com/36809659/51081491-94dc2a00-172b-11e9-85d9-995222737451.png)
![snipaste_2019-01-13_12-03-41](https://user-images.githubusercontent.com/36809659/51081492-9574c080-172b-11e9-81fd-a62b3b69c717.png)

**Comment by simonemainardi** [comment]
newly added file `pro/scripts/lua/get_flows_data.lua` clashes with file `scripts/lua/get_flows_data.lua` and this is causing the issue.

@cardigliano please check.

**Comment by cardigliano** [comment]
pro/scripts/lua/get_flows_data.lua has been renamed to pro/scripts/lua/get_flows_db_data.lua, building new packages right now, please check it

**Comment by fsamareanu** [comment]
New package fixes it.

**Comment by cardigliano** [comment]
Thank you.
