### ISSUE TITLE
Add icinga support in alert integration

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2309]
Currently ntopng supports nagios for alert export. As nagios is loosing momentum in favour of other tools like Icinga 2, it is requested to also integrate ntopng with Icinga.

**Comment by simonemainardi** [comment]
Implemented

- code: https://github.com/ntop/ntopng/tree/dev/tools/icinga2
- Blog: https://www.ntop.org/ntopng/integrating-ntopng-with-icinga/
- docs: https://www.ntop.org/guides/ntopng/advanced_features/icinga2.html
