### ISSUE TITLE
Local Hosts Active Flows Matrix Error

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#231]
HTTP/1.1 500 Internal server error Content-Type: text/html Connection: close   Script "/home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng/scripts/lua/hosts_matrix.lua" returned an error:
...am-Files/Ubuntu/Ntop/ntopng/scripts/lua/hosts_matrix.lua:109: attempt to index global 't' (a nil value)

**Comment by lucaderi** [comment]
What git code version?

**Comment by jean-christophe-manciot** [comment]
Github 273c0ae7958ac1db5747aeab298c89cd632ce839
