### ISSUE TITLE
Host pool creation issues in 3.9 dev - settings changes in UI do not persist

### ISSUE THREAD

**Issue by CDawson1** [ntop/ntopng#2318]
Having recently updated and addressed issues with migrating from MySQL to nIndex, I'm now looking to expand some functionality of ntopng.  I need to create (at the moment) nearly 100 host pools.  I don't know any easy way to do this, but I've found a semi-efficient way via the UI.  However, I've been met with the pools I've created disappearing.  

At first, I created multiple empty pools at once, as it seemed clicking the add button (+) multiple times was met with multiple blank rows, and it didn't seem to complain about it.  But they soon disappeared.  I then created one at a time, still empty, and saved after each creation, but they too disappeared.  

I then created one, immediately added a couple relevant subnets, but they eventually disappeared.  

I then noticed that of the subnets I was adding, another pool already existed with a /15 subnet created, which overlapped with what I was creating, so I deleted that, then added the new pools.  Not only did the new pools disappear again, the pool I deleted reappeared.  

So this tells me something is busted in the back end of this new dev version.  It seems that there's a small period of time where the UI shows the changes have taken, but just a few minutes are required when all the changes revert.  

I currently have 12 pools created. 

I see a lot of these but it doesn't seem to be related to any configuration changes.

```
Jan 16 15:09:35 NTOP2 ntopng[27411]: 16/Jan/2019 15:09:35 [Table.cpp:264] WARNING: add_row_untyped() [when: 1547651374][last: 1547651375][diff: -1]
Jan 16 15:09:35 NTOP2 ntopng[27411]: 16/Jan/2019 15:09:35 [Table.cpp:264] WARNING: add_row_untyped() [when: 1547651374][last: 1547651375][diff: -1]
Jan 16 15:09:35 NTOP2 ntopng: [Table.cpp:264] WARNING: add_row_untyped() [when: 1547651374][last: 1547651375][diff: -1]
Jan 16 15:09:35 NTOP2 ntopng[27411]: 16/Jan/2019 15:09:35 [Table.cpp:264] WARNING: add_row_untyped() [when: 1547651374][last: 1547651375][diff: -1]
Jan 16 15:09:35 NTOP2 ntopng: [Table.cpp:264] WARNING: add_row_untyped() [when: 1547651374][last: 1547651375][diff: -1]
Jan 16 15:09:35 NTOP2 ntopng: [Table.cpp:264] WARNING: add_row_untyped() [when: 1547651374][last: 1547651375][diff: -1]
```

Anything I can see to determine what's happening with these host pool creations?

This is also probably a separate issue, and not one that I'm aware of would be related at all to ntop...but I also see:

```
Jan 16 15:30:47 NTOP2 edge[1121]: 16/Jan/2019 15:30:47 [edge_utils.c:587] WARNING: Supernode not responding - moving to 0 of 1
Jan 16 15:31:27 NTOP2 edge[1121]: 16/Jan/2019 15:31:27 [edge_utils.c:587] WARNING: Supernode not responding - moving to 0 of 1
Jan 16 15:32:07 NTOP2 edge[1121]: 16/Jan/2019 15:32:07 [edge_utils.c:587] WARNING: Supernode not responding - moving to 0 of 1
Jan 16 15:32:48 NTOP2 edge[1121]: 16/Jan/2019 15:32:48 [edge_utils.c:587] WARNING: Supernode not responding - moving to 0 of 1
```

**Comment by CDawson1** [comment]
Sorry...this was a self inflicted issue.  I've had  --disable-login=1 in the config...

Disabled that and logged in properly and all is well.  

Might I suggest adding features that make it blatantly obvious if you don't have elevated privileges?

**Comment by CDawson1** [comment]
Sorry...closed this thinking it was a self inflicted issue...but it's not.  Issue remains. 

In fact, it looks as though any changes in the UI do not keep.  EG I have the refresh rate set to 2 sec, and changing it does not persist.

**Comment by emanuele-f** [comment]
I can correctly create multiple pools (even though the plus button should only be used one, I'm going to fix this). Please check the uptime of ntopng as it very strange that they disappear suddenly. A remote access would be useful to see the exact issue (e.g. teamviewer or gui access), please email me at faranda@ntop.org if that's feasable.

Regarding `add_row_untyped`, this is a warning used internally to debug the db, it is not an issue right now. For the n2n (edge) log, assuming that you want to enable remote assistance, a firewall in the middle may be causing the issue. If you think this is not the case, please open a separate issue.

**Comment by CDawson1** [comment]
Thanks.  I'm sending you an email now.  Re: uptime...I'd not noticed as I though it was stable...but it seems that's not the case.  It's only 1m as I type.

**Comment by CDawson1** [comment]
Looks like it's dying after about five minutes.

**Comment by emanuele-f** [comment]
I've provided by email instructions for stack trace generation, please post it when possible.

**Comment by CDawson1** [comment]
So this was semi-self inflicted after all in that there were other directories that had permissions issues.  Though given the difference with using MySQL and nIndex...don't know where or how that would have occurred. With the help of Emanuele, this seems resolved at the moment as we've been stable for nearly 90m now.

**Comment by emanuele-f** [comment]
Thank you for reporting
