### ISSUE TITLE
sFlow Ratio is zero

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2319]
![screen shot 2019-01-16 at 17 58 11](https://user-images.githubusercontent.com/4493366/51265187-822a5500-19b8-11e9-8f37-779b92c99876.png)
In sFlow switches export both packet and counter samples. Using them it is possible to upscale traffic and see the discrepancy (or ratio) between sFlow and SNMP counters exported via sFlow without having to collect them with SNMP. In this above screenshot ratio is 0 and this is a bug

**Comment by simonemainardi** [comment]
Implemented under the sFlow devices

![image](https://user-images.githubusercontent.com/3397663/52047640-bb7ecb00-2549-11e9-90e9-c0237f525c72.png)
