### ISSUE TITLE
Enhancement proposal: allow special characters in password

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#232]
Why do you limit the type of legit characters to a-z, A-Z, 0-9, and _?
Allowing all kinds of characters would significantly enforce the passwords security against brute force for example.

**Comment by jean-christophe-manciot** [comment]
From /etc/redis.conf:
# Warning: since Redis is pretty fast an outside user can try up to
# 150k passwords per second against a good box. This means that you should
# use a very strong password otherwise it will be very easy to break.
...

**Comment by lucaderi** [comment]
What chars do you need to be supported? I don't see what redis has to do with the issue of the password you reported.

**Comment by jean-christophe-manciot** [comment]
All special characters like ,;:!$*°=()_-'"&%<>+~#{[|`\^@]}µ§/.?
Also, ntopng admin password can be changed with:
redis-cli SET ntopng.user.admin.password <md5-hash-of-the-password>
So I figured redis opinion on password strength might be worth noted.
