### ISSUE TITLE
Repeated notes section

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2320]
![screen shot 2019-01-16 at 18 02 21](https://user-images.githubusercontent.com/4493366/51265379-f49b3500-19b8-11e9-9236-ee917bb7b4aa.png)
In the URL below
http://xxxx:3000/lua/pro/enterprise/flowdevices_stats.lua?ip=xxxxx&page=historical
there are two nested notes section

**Comment by emanuele-f** [comment]
Fixed
