### ISSUE TITLE
Rework sFlow Menu

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2321]
![screen shot 2019-01-16 at 18 04 05](https://user-images.githubusercontent.com/4493366/51265468-23191000-19b9-11e9-8c01-577e67e4cd09.png)

The sFlow menu is not arranged at best as there are sections that seems to overlap such as Flow exporters and sFlow devices

**Comment by simonemainardi** [comment]
So now the entry sFlow devices is hidden when there's no sFlow traffic

![image](https://user-images.githubusercontent.com/3397663/52961973-6988d280-339c-11e9-96ed-ca26ee21ecfc.png)

Then, devices that are responsible for the generation and export of flows are kept separated as shown here:

![image](https://user-images.githubusercontent.com/3397663/52962063-9f2dbb80-339c-11e9-8f7d-97d0eafa1f68.png)
