### ISSUE TITLE
AS Number shows 0 

### ISSUE THREAD

**Issue by s2105** [ntop/ntopng#2322]
Hello, 
We are using ntopng community edition v.3.4.180531. We are trying to get AS number data but it shows as zero.

<img width="1191" alt="screen shot 2019-01-17 at 11 43 27 am" src="https://user-images.githubusercontent.com/22646495/51340808-26f67200-1a4d-11e9-9c2d-ff56fde10ef5.png">

**Comment by emanuele-f** [comment]
Hi, you are using an old version, please update to the current stable (3.8) or dev (3.9) http://packages.ntop.org. If building from source, please also make sure to download the geoip database with `make geoip`.

**Comment by simonemainardi** [comment]
solution given. closing.

**Comment by s2105** [comment]
Thank you for your help.

>
