### ISSUE TITLE
Per member quotas are not used in nEdge

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2324]
Per member quotas are implemented but not used by nEdge. We should decide to keep them (adding gui controls and test that they work properly) or remove them.

**Comment by simonemainardi** [comment]
Per member quotas are no longer supported. Code needs to be cleaned up:

- `enforceQuotasPerPoolMember`
- `Host::quota_enforcement_stats`
- And the lua part enforce_quotas_per_pool_member

**Comment by simonemainardi** [comment]
After internal review we have seen this issue is no longer necessary.
