### ISSUE TITLE
-F "nIndex" does not dump flows if pcaps are given with -i 

### ISSUE THREAD

**Issue by sachsgiri** [ntop/ntopng#2328]
I am running follwing version of ntopng : 

v.3.9.190121  [Enterprise/Professional build]
GIT rev:  dev:2755b18dee5c281dd30ba640cb6f53433301bd95:20190121
Pro rev:  r2209
Built on:  Ubuntu 18.04.1 LTS
System Id:  BExxxxxxxxxxAF2
Platform:  x86_64
Edition:  Professional
License Type:  Permanent

I run following command : 

time ntopng -r myredis:6379@1 -F "nindex" -i /var/data/pca
ps/gmail.pcap --shutdown-when-done

Logs are : 

22/Jan/2019 12:19:49 [Prefs.cpp:1061] ntopng will use redis ev-redis@1
22/Jan/2019 12:19:49 [Ntop.cpp:1906] Setting local networks to 127.0.0.0/8
22/Jan/2019 12:19:49 [Redis.cpp:146] Successfully connected to redis ev-redis:6379@1
22/Jan/2019 12:19:49 [Redis.cpp:146] Successfully connected to redis ev-redis:6379@1
22/Jan/2019 12:19:49 [NtopPro.cpp:313] [LICENSE] Reading license from /etc/ntopng.license
22/Jan/2019 12:19:49 [NtopPro.cpp:205] [LICENSE] /etc/ntopng.license: unable to validate Enterprise license [License mismatch error]
22/Jan/2019 12:19:49 [NtopPro.cpp:208] [LICENSE] /etc/ntopng.license: found valid Professional license
22/Jan/2019 12:19:49 [boot.lua:28] [delete_data_utils.lua:393] Deleting data [delete_if_data][OK]
22/Jan/2019 12:19:49 [boot.lua:28] [delete_data_utils.lua:393] Deleting data [delete_if_ids][OK]
22/Jan/2019 12:19:49 [boot.lua:28] [delete_data_utils.lua:393] Deleting data [delete_if_redis_keys][OK]
22/Jan/2019 12:19:49 [boot.lua:28] [delete_data_utils.lua:393] Deleting data [delete_if_db][OK]
22/Jan/2019 12:19:49 [PcapInterface.cpp:70] Reading packets from pcap file gmail.pcap...
22/Jan/2019 12:19:49 [Ntop.cpp:1998] Registered interface gmail.pcap [id: 4]
22/Jan/2019 12:19:49 [main.cpp:302] PID stored in file /var/run/ntopng.pid
22/Jan/2019 12:19:50 [Utils.cpp:563] WARNING: Unable to retain privileges for privileged file writing
22/Jan/2019 12:19:50 [Utils.cpp:599] User changed to ntopng
22/Jan/2019 12:19:50 [HTTPserver.cpp:1322] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
22/Jan/2019 12:19:50 [HTTPserver.cpp:1325] HTTP server listening on 3000
22/Jan/2019 12:19:50 [NIndexFlowDB.cpp:73] Successfully open DB /var/lib/ntopng/4/aggregatedflows
22/Jan/2019 12:19:50 [NIndexFlowDB.cpp:75] [nIndex] Successfully created flow database index [/var/lib/ntopng/4/aggregatedflows]
22/Jan/2019 12:19:50 [NIndexFlowDB.cpp:126] Successfully open DB /var/lib/ntopng/4/flows
22/Jan/2019 12:19:50 [NIndexFlowDB.cpp:128] [nIndex] Successfully created flow database index [/var/lib/ntopng/4/flows]
22/Jan/2019 12:19:50 [main.cpp:377] Working directory: /var/lib/ntopng
22/Jan/2019 12:19:50 [main.cpp:379] Scripts/HTML pages directory: /usr/share/ntopng
22/Jan/2019 12:19:50 [Ntop.cpp:378] Welcome to ntopng x86_64 v.3.9.190121 - (C) 1998-19 ntop.org
22/Jan/2019 12:19:50 [Ntop.cpp:388] Built on Ubuntu 18.04.1 LTS
22/Jan/2019 12:19:50 [NtopPro.cpp:652] [LICENSE] System Id:  BE15060876066AF2
22/Jan/2019 12:19:50 [NtopPro.cpp:653] [LICENSE] Edition:  Professional
22/Jan/2019 12:19:50 [NtopPro.cpp:654] [LICENSE] License Type:  Permanent License
22/Jan/2019 12:19:50 [NtopPro.cpp:657] [LICENSE] License:  66A7161FD4F36B10FDD4CCB28FF32CEB15796802780CA8F781
22/Jan/2019 12:19:50 [NtopPro.cpp:667] [LICENSE] Maintenance:  Until Wed Jan 22 08:04:38 2020 [364 days left]
22/Jan/2019 12:19:50 [PeriodicActivities.cpp:72] Started periodic activities loop...
22/Jan/2019 12:19:50 [PeriodicActivities.cpp:113] Each periodic activity script will use 2 threads
22/Jan/2019 12:19:50 [NetworkInterface.cpp:2533] Started packet polling on interface gmail.pcap [id: 4]...
22/Jan/2019 12:19:51 [PcapInterface.cpp:257] Terminated packet polling for gmail.pcap
22/Jan/2019 12:19:55 [Ntop.cpp:2082] Terminating periodic activities
22/Jan/2019 12:19:55 [Ntop.cpp:2088] Executing shutdown script
22/Jan/2019 12:19:55 [Ntop.cpp:2097] Terminating network interfaces
22/Jan/2019 12:19:55 [Ntop.cpp:2102] Waiting for the application to shutdown
22/Jan/2019 12:19:57 [ProtoStats.cpp:35] [IPv4]  99.39 MB/200.83 K Packets
22/Jan/2019 12:19:57 [ProtoStats.cpp:35] [IPv6]  30.19 KB/143.00 Packets
22/Jan/2019 12:19:57 [ProtoStats.cpp:35] [ARP]   65.94 KB/1.13 K Packets
22/Jan/2019 12:19:57 [ProtoStats.cpp:35] [MPLS]  0 B/0.00 Packets
22/Jan/2019 12:19:57 [ProtoStats.cpp:35] [Other] 1.05 KB/18.00 Packets
22/Jan/2019 12:19:57 [Ntop.cpp:2070] Interface gmail.pcap [running: 0]
22/Jan/2019 12:19:57 [Ntop.cpp:2112] Deleted PID /var/run/ntopng.pid: [rc: -1][Permission denied]
22/Jan/2019 12:19:57 [HTTPserver.cpp:1348] HTTP server terminated

Sachin Giri, [22.01.19 17:57]
22/Jan/2019 12:19:57 [NetworkInterface.cpp:590] Flushing host contacts for interface gmail.pcap
22/Jan/2019 12:19:57 [NetworkInterface.cpp:2562] Cleanup interface gmail.pcap
22/Jan/2019 12:19:57 [NIndexFlowDB.cpp:134] Flushing flows to disk...
22/Jan/2019 12:19:57 [AddressResolution.cpp:61] Address resolution stats [0 resolved][0 failures]

It shows that flows have been dumped into /var/lib/ntopng/4/~

But I dont see anything under /var/lib/ntopng/ apart from runtimepref.json

On the other hand if I dont provide pcap as -i, then 3 interface ids are created with -F nIndex after shutdown.

**Comment by emanuele-f** [comment]
This is caused by https://github.com/ntop/ntopng/blob/dev/src/PcapInterface.cpp#L138 . The fix will prevent the removal of the flows directories if `-F nindex` is specified.
