### ISSUE TITLE
nindex historical query searches can make ntopng non-responsive

### ISSUE THREAD

**Issue by Gelob** [ntop/ntopng#2329]
We ran a historical query against an IP for nindex for a month long period, after 10 minutes the query still didn't return any results and the ntopng interface stopped responding as a result we had to restart ntopng. I've replaced the actual IP in the query. I'm happy to run it again to help debug if needed. I understand some queries may take a long time but they should run independent of the ntopng interface in the background.

Query:
```
Jan 23 23:52:50 ntopng01 ntopng[6220]: 23/Jan/2019 23:52:50 [NIndexFlowDB.cpp:523] select(flows: raw flows, time: 1543643820/1548201780[4557960 sec], select: [*], where: [((IPV4_SRC_ADDR=1.1.1.1 OR IPV4_DST_ADDR=1.1.1.1)) AND (FIRST_SEEN >= 1543644000) AND (LAST_SEEN <= 1548201600) AND (FLOW_TIME <1548201780) and (FLOW_TIME>1543643820)], records=0:10)
```

**Comment by simonemainardi** [comment]
this should have already been addressed by @emanuele-f. What is the ntopng version you are using?

**Comment by Gelob** [comment]
I always forget that critical part. 3.8.190110 https://github.com/ntop/ntopng/commit/07f4b7ef21b4934e8b8513613f96a89dd94dad9c

**Comment by emanuele-f** [comment]
Can you describe the exact step to reproduce it? Can you see this dialog appearing?

![2019-01-28_09-44](https://user-images.githubusercontent.com/5488003/51824353-e7941500-22d9-11e9-9ea5-f1fd0bf31bad.png)

**Comment by Gelob** [comment]
@emanuele-f on the nindex.lua page directly where you would query raw flows, I don't see that pop-up appear. I ran a query that took 26seconds which isn't that long but I'm not sure after how long that message should appear or if its implemented on that page.

Example URL:
`https://ntopng/lua/enterprise/nindex.lua?select_clause=*&where_clause=%28IPV4_SRC_ADDR%3D 1.1.1.1+OR+IPV4_DST_ADDR%3D 1.1.1.1%29&begin_time_clause=1533099600&end_time_clause=1548633600&flow_clause=flows&maxhits_clause=100`

**Comment by emanuele-f** [comment]
Said that the explorer page is somehow a "debug page" for now, it is nevertheless necessary to add a way to interrupt the query at some point (e.g. when the browser tab is closed, resulting into a connection close)

**Comment by emanuele-f** [comment]
The query is now aborted if the browser tab is closed or the abort button is pressed in case of the charts page
