### ISSUE TITLE
Report Page - no default report on page

### ISSUE THREAD

**Issue by mineumann** [ntop/ntopng#233]
The "Report" page automatically generates a 1d report. Can this set to default no? So on first load of the page that there is no auto-generated report which takes time if you'd only want to generate a report for a different timeframe. If there is already a way to disable this auto-generation plz info on that. Thank you!

**Comment by simonemainardi** [comment]
@mineumann, Enhancement has been implemented. Please hold on, ntopng professional packages will be build overnight.

![image](https://cloud.githubusercontent.com/assets/3397663/10520409/31d1ce96-736a-11e5-8182-de469f280d4b.png)
