### ISSUE TITLE
Gauge at bottom page with 0 bps for upload traffic

### ISSUE THREAD

**Issue by engee974** [ntop/ntopng#2330]
![image](https://user-images.githubusercontent.com/5074983/51662213-924fbf00-1fcc-11e9-8224-4c019779b5e8.png)
As you can see, the gauge displays 0 bps for the upload traffic.

**Comment by simonemainardi** [comment]
This can be normal for example if you are connected to a mirror port. Is this your case? If so, please, visit the ntopng interface preferences page and make the interface with 'mirrored traffic'

**Comment by engee974** [comment]
Before the update (apt-get update && apt-get upgrade) it wasn't at 0 bps.
That's why an issue is opened.
Yes the interface is in a mirror port

**Comment by simonemainardi** [comment]
so this is normal.

before the update it was showing

- remote 2 local 
-local 2 remote

traffic but this was causing confusion among the users that prefer to think in terms traffic received and sent from the interface.

**Comment by engee974** [comment]
is there a release note about that change ?
What is the solution for me ?
Downgrade the version ?

**Comment by simonemainardi** [comment]
@emanuele-f please provide a link to the release change.

**Comment by engee974** [comment]
I understand why you did that.
But what i need is a way to quickly read UPLOAD and DOWNLOAD traffic.
Now UP & DOWN are mixed up.

**Comment by simonemainardi** [comment]
nothing is mixed up. you were used to local-2-remote and remote-2-local which are not upload and download.

**Comment by engee974** [comment]
I may be wrong.
Before the update (with the same configuration) for me Upload was local to remote and download was remote to local.
What do i see now ? It’s an aggregation of both traffic (what i call « mixed up »).
Remember that few seconds before the update both graph were correct for me and upload was about 200Mbps.

**Comment by engee974** [comment]
Question : what is that gauge for ?
Only a view of the interface activity ? 
Or à view off the analyzed traffic ?

**Comment by emanuele-f** [comment]
If you are monitoring mirrored traffic, then you should tick the "Mirrored Traffic" option https://www.ntop.org/guides/ntopng/web_gui/interfaces.html?highlight=mirrored%20traffic#settings . By doing so, the bottom graph in question will be hidden because, as you noted, it would be inconsistent to show the `in` and `out` directions as mirrored traffic only has a `in` direciton.

**Comment by engee974** [comment]
So you answer my question : that bottom gauge and graphs is only to monitor the interface, not the analyzed trafic. Am i right ?

So before the upgrade why did that graphs be working perfectly for my need ?
Did you fix a bug ?

**Comment by emanuele-f** [comment]
Before the patch: the bottom chart displayed local vs remote traffic (affected by the `-m` option).
After the patch: the bottom chart displays interface in vs out traffic. When using pf_ring, however, the chart actually displays the *monitored* in/out traffic.

**Comment by vidgizmo** [comment]
I am also using a mirrored configuration.

Is there any way to get the chart at the top (or any other chart) to show the separate aggregate totals for local-2-remote (what we think of as upload) and remote-2-local (what we think of as download). My typical scenario (home use) is that my videoconferencing system starts displaying transmit packet loss (local-2-remote) and I want to quickly look at the network and see the primary devices or flows that are going in that direction.

**Comment by vidgizmo** [comment]
Maybe I found it...?
Hosts -> Networks -> Click on Chart next to my local network... and I get "Bytes_Egress" and "Bytes_Ingress" :)  Looks like this will do the trick :)
