### ISSUE TITLE
Bottom gauge and graphs : analyzed traffic mode

### ISSUE THREAD

**Issue by engee974** [ntop/ntopng#2332]
Hi,
The bottom gauge and graphs have changed. The new behavior doesn’t match anymore with my need.
My NTOPNG is connected to mirrored ports to analyze the traffic between my network (local) and the rest of the internet (remote).
Upload traffic is the traffic from my network to the internet and download traffic is the traffic from the internet to my network.
I need a quick view of the analyzed traffic to verify that there is no issue. 
That bottom gauge is the only view i had on my internet traffic. I don’t need to view the interface activity. It’s not usefull for me.

How could i get that view please ?

**Comment by m4ntic0r** [comment]
Hi

Same problem for me here. I updated ntopng and now the graph only shows "download traffic". I use port mirroring on my network switch and on the mirrored port there is my wan router.

Is there an option to change it back to old behaviour?

**Comment by emanuele-f** [comment]
Not possible right now, however we may support both modes by the means of a user preference, still discussing this internally with my colleagues before proceeding

**Comment by emanuele-f** [comment]
After internal discussion, we decided that this is currently not a priority. Please note that from the "Networks" page you can get a realtime view of the traffic of each local network vs the remote networks.

**Comment by engee974** [comment]
OK it's noted. 
but the networks views is not what i need.
I don't understand what is so difficult to rollback you code.
It was working before.
