### ISSUE TITLE
Remote hosts invalid router assignment

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2336]
Remote hosts are sometimes marked as routers, as the are confused with the local LAN router. This happens also when the interface is receiving mirrored traffic (preferences).

**Comment by simonemainardi** [comment]
fixed using the concept of broadcast domain:

- ipv6 https://github.com/ntop/ntopng/commit/183dfa41f945a5dff080a6b3c816261b5662c94d
- ipv4 https://github.com/ntop/ntopng/commit/92b722e6f364acb26e1c2c5ddd43efd111d44a1d
