### ISSUE TITLE
Routers should have no OS associated

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2337]
Sometimes a router has associated an OS (e.g. Android or Windows) as ntopng wrongly assumes that this is either a router (but it's not). Usually the problem is that a remote host is not a router (as it's just a PC) but ntopng wrongly assumes that it's a router

**Comment by emanuele-f** [comment]
Issue should be addressed in e6c4a5ad7ecccc17cfc63b064cc057b0518a3566, waiting for feedback before closing this

**Comment by emanuele-f** [comment]
Issue is now solved with the fix above.
