### ISSUE TITLE
Reset host counter 

### ISSUE THREAD

**Issue by chougulepavan** [ntop/ntopng#2338]
Can I reset the individual host counter, just like I can do it for the interface?

**Comment by emanuele-f** [comment]
Yes, this is possible with the latest dev version.

![2019-01-29_09-57](https://user-images.githubusercontent.com/5488003/51896284-019a2a00-23a4-11e9-9e94-516e4e128cd1.png)

**Comment by chougulepavan** [comment]
> Yes, this is possible with the latest dev version.
> 
> ![2019-01-29_09-57](https://user-images.githubusercontent.com/5488003/51896284-019a2a00-23a4-11e9-9e94-516e4e128cd1.png)

Yes, found it. Thank you..!!
