### ISSUE TITLE
Report Page - view interface not generated

### ISSUE THREAD

**Issue by mineumann** [ntop/ntopng#234]
Having 2 interfaces plus 1 view interface - when toggling to generate a report for the view interface only this doesn't work. Always shows a report containing each of the other 2 interfaces. Tried with latest firefox and chrome browser. Using ntop v2.1.151014

**Comment by simonemainardi** [comment]
issue has been addressed and will be available in the upcoming nightly build. there are still some minor issues related to the reporting of interface views.
