### ISSUE TITLE
Invalid nprobe licence

### ISSUE THREAD

**Issue by swathikothapu** [ntop/ntopng#2340]
I’m having issues regarding nProbe, it’s telling me Invalid nProbe license (/etc/nprobe.license) [License mismatch error].

![image](https://user-images.githubusercontent.com/37098746/51971108-6df95400-249e-11e9-95eb-9b9c4a05deb6.png)

**Comment by simonemainardi** [comment]
in the screenshot is telling 'missing license file'. make sure file /etc/nprobe.license exists and is readable.

**Comment by swathikothapu** [comment]
Thank you sir, sure i will check that.
