### ISSUE TITLE
ntopng --version hangs for a while if redis is not running

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#2343]
When you run ntopng --version, it waits for a while (>10s) trying to connect to redis in order to check the license (in case it is stored on redis). This should be somehow avoided (as this is also used by user interfaces like nBox and should return immediately), with a shorter timeout or with an option to avoid checking the license when the caller needs the version only.

**Comment by emanuele-f** [comment]
This would require to remove license information from `--version` but to keep compatibility a new `--version-no-license` option will be added. Skipping the Redis connection would be error prone as ntopng requires it for different operations throughout the initialization code.
