### ISSUE TITLE
Some numeric IPs are not resolved

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#2345]
Debian buster
ntopng 3.8+dfsg1-2~1.gbp2947dc
ndpi 2.6-3
curl 7.63.0-1
[About page](https://user-images.githubusercontent.com/13176858/52048581-0c8fbe80-254c-11e9-9a55-c9dc453fd727.png)

1. ```-n=1```in ```/etc/ntopng/ntopng.conf```
2. The **/etc/hosts file is not used** in "all hosts" page; this results in unresolved local subnet IPv4 & IPv6 addresses
3. **Some remote IPv4/IPv6 addresses are unresolved**.
I don't know what process is used in ntopng, but for instance, ```2a00:1450:400c:c0a::bd``` is unresolved although it can easily be resolved with ```dig```:
for instance the following  bash script ```dig-get-fqdn.sh <ip_address>``` echoes the answer if dig returns a correct FQDN, otherwise the whole answer is echoed.
```
#!/bin/bash
ip_address=$1
unset dig_output
readarray -t dig_output < <(dig -x "$ip_address")
for line in "${dig_output[@]}"
do
        if [[ "$line" =~ [[:blank:]]+IN[[:blank:]]+PTR[[:blank:]]+[^[:blank:]]+[[:blank:]]*$ ]]; then
                fqdn=$(echo "$line" | sed -E "s|^.*[[:blank:]]+IN[[:blank:]]+PTR[[:blank:]]+([^[:blank:]]+).[[:blank:]]*|\1|1")
                echo "$fqdn"
                exit 0
        fi
done
printf "%s\n" "${dig_output[@]}"
exit 1
```
With ```2a00:1450:400c:c0a::bd```, we get:
```
dig-get-fqdn.sh 2a00:1450:400c:c0a::bd
wl-in-xbd.1e100.net
```

**Comment by emanuele-f** [comment]
Issues addressed in

f2e610d1ea528adffe169e22c2fd7ec46daac68d and 72c155f2b58a6803899a6c84fe324d65e22fcd0f . Please wait an hour until the new package is available.
