### ISSUE TITLE
Invalid package dependencies

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2348]
When updating ntopng, PF_RING dependencies are also updated. However it's wrong that also  apt-ntop is updated that has nothing to do with this

root@ubuntu:/home/deri# apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  apt-ntop n2n ndpi ntopng ntopng-data pfring pfring-dkms

**Comment by cardigliano** [comment]
"apt-ntop" was getting updated by "apt-get upgrade" as it was getting a new version/revision together with the nbox package, this should no longer happen now as they are into separate repositories.
