### ISSUE TITLE
Add ability to configure per-port alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2349]
In SNMP all port alerts such as the one below are alike

[30/01/2019 10:31:40][Interface Status Change]: Interface 7 on SNMP device A.B.C.D changed its status to Down

and in case a port goes up/down a mail can be sent. However not all ports are important and thus emails for some ports are useless if not annoying.

It is requested to adde the ability to configure the alert generation on ports (e.g. port state change and in the future packet drops etc) so that alerts are generated only if configured on such port

**Comment by simonemainardi** [comment]
add alert on changes between full/half duplex

**Comment by cardigliano** [comment]
Implemented per-interface toggling of alerts for state change and packet drops

**Comment by cardigliano** [comment]
Implemented duplex status change alerts
