### ISSUE TITLE
Clod App Network Impact Report

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#2352]
Enterprise Customer ask for a report and live view about what is the bandwidth impact about cloud application o365, Google, SalesForce etc

**Comment by emanuele-f** [comment]
You can use ntopng to monitor the protocols bandwidths. Please check out the relevant pages of the manual:

https://www.ntop.org/guides/ntopng/web_gui/dashboard.html#dashboard-in-the-professional-version
https://www.ntop.org/guides/ntopng/web_gui/interfaces.html#protocols
https://www.ntop.org/guides/ntopng/web_gui/historical.html#historical-charts

For protocols not directly recognized by nDPI (the DPI engine of ntopng) you can manually create rules for custom protocols https://www.ntop.org/ndpi/configuring-ndpi-for-custom-protocol-detection/
