### ISSUE TITLE
nTop distro

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#2353]
It could be more better to have a dedicated and optimized nTop OS and specific ISO to avoid Linux/Windows OS Problems and use it as batter as possible

**Comment by emanuele-f** [comment]
We prefer to keep interoperability and let our users decide the OS of choice. Maintaining a custom ISO requires some efforts, we have built dockers images in the past but did not update anymore. Right now we prefer to ease the ntopng installation and setup. Anyway, installing ntopng and configuring it for a basic setup is quite simple, please check out:

http://packages.ntop.org
https://www.ntop.org/guides/ntopng/how_to_start/index.html
