### ISSUE TITLE
Host identifcation flow

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#2354]
Enterprise Customer has the network developed on Layer 3. Actually the flow show all the IP conversation with the same internal MAC Address and it's difficult when you create Host group and so on.
It could be better to ask or something to switch to enable layer2/layer3 flow ibased inventory

**Comment by emanuele-f** [comment]
Layer 2 visibility depends on your network and monitoring configuration. I have clear the question, please elaborate

**Comment by simonemainardi** [comment]
following up personally with @zimbawe998
