### ISSUE TITLE
Add per host malicious flow counter

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2356]
When a flow ends, it is possible to decide whether the flow was kind of suspicious. Example
- unidirectional flow (no packets in the reverse direction)
- TCP flow that ends at SYN. Note that in case a SYN is sent, TCP request to retransmit it in case of no SYN-ACK. So a flow with only 1 SYN packet is twice suspicious
- TCP flows that do not end cleanly (FIN/RST)
- TCP flows that are incomplete (e.g SYN/RST)

It is requested to add a flow counter per host that keeps track of these malicious flows (both as client and server, hence #client and #server flows).

**Comment by emanuele-f** [comment]
More information:

- reuse the getFlowStatus to determine if the flow is abnormal or not
- add a check on the status to determine if it's necessary to increase host bad flows counters
- host counters should be placed in the LocalHostStats
- unidirectional tcp flows are already marked as status_suspicious_tcp_syn_probing
- same thing for flows with only one SYN

**Comment by simonemainardi** [comment]
- when a flow goes Idle, increment an anomalous flows counter in the host if the flow status is not "Normal"

**Comment by emanuele-f** [comment]
![2019-02-12_12-31](https://user-images.githubusercontent.com/5488003/52632543-c62a5000-2eb9-11e9-9796-b9826aa026c7.png)

As requested, an anomalous flow counter has been added to the hosts with commit a09e8efed07f4fff028566e3bbece959b9ec26ed
