### ISSUE TITLE
Alert... How can I find all the hosts with a modified thresholds?

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#2357]
In the last days I modified the Alert thresholds for 15/16 internal IPs.
Now I should set the SYN flood threshold for all these IPs to another value but:
-) I don't remember which IPs I modified and in which interfaces
-) I don't remember which threshold values I set for each IP
So... What do you think to add a global page with the list of all modified IPs ad all the set thresholds? This would be useful to easily manage this kind of settings.
Thanks!

Bye bye... 

PS: I'm using ntopng version "3.8.190118 - Professional Edition"

**Comment by emanuele-f** [comment]
Hi, yes, this would be useful, however there are some things to keep in mind:
- it's already possible to set/change global thresholds for all the hosts, although this does not solve your issue with specific local hosts
- You can get such information with `redis-cli keys ntopng.prefs.*.alerts_config`
- We should remove/augument static threshold with a more dynamic approach

**Comment by lucaderi** [comment]
This needs to be implemented by v4 release

**Comment by simonemainardi** [comment]
In the latest ntopng version, you have the ability to create configurations for the alerts. Each configuration is applied to a certain group of hosts (specified in CIDR format).

So for example if you have two groups of hosts, say ced with ip `192.168.1.0/24` and office with ip `192.168.2.0/24`, and you want to apply different configurations to them, you can create two configurations as:

![image](https://user-images.githubusercontent.com/3397663/73073460-ae27c280-3eb7-11ea-8cef-cbd2a9135d76.png)

Then, you can click on the 'edit' of each configuration to set desired thresholds. The column 'Apply To' gives the information you were looking for. By looking at that column, you automatically know all the hosts that have such configuration applied.
