### ISSUE TITLE
Add a per-Application breakdown of the active traffic

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#2360]
Currently, it is not possible to see the actual throughput divided per-Application. It is requested to extend the following page to add such view:

![image](https://user-images.githubusercontent.com/3397663/52407747-6571d080-2ad1-11e9-9c93-72ebd1d75625.png)

**Comment by emanuele-f** [comment]
To discuss:
- Page mixes realtime with past data
- Page is long enough right now, the new chart would add another row
- Possibly remove/optimize live flows count as it requires iterating all the active flows
- Possibly change the page position and locate under the main menu bar

**Comment by simonemainardi** [comment]
Implemented when drilling down flows. A top charts open up when the application is selected, and it shows the overall throughput matching that application.
