### ISSUE TITLE
ntopng SNMP to ASA Service Module

### ISSUE THREAD

**Issue by oliwirth** [ntop/ntopng#2361]
Dear Ntop-Team,

GSI-Heavy Ion reseach center recently got an education Licence for ntopng from you, wich was requested by my colleage.
Thanks a lot for this!

I've got a little Problem.  I added two SNMP Devices. A Cisco Cat6509 which works fine. But to an Cisco ASA Module I get the message:
"The SNMP walk is too slow. Displayed data may be outdated or missing. Check network connectivity and device responsiveness. A new scan attempt will be performed in 15 minutes."
Even so a simple snmp-walk performed via linux-shell gets only about 2000 lines in return and only lasts 2 seconds.

Can you give me a hint what this message means and something to read what might be the problem and if its able to be solved.

Thanks in advance
Oliver

**Comment by simonemainardi** [comment]
The message means a timeout is reached (3 seconds) in one of the SNMP walks performed. So either your device or the network is slow. After a timeout is reached ntopng will automatically try and contact the device again in 15 minutes. So you don't have to worry much and only investigate further if the device is always in a "walk too slow" state.
