### ISSUE TITLE
where to change  date setting for web viewed info, in this case alerts

### ISSUE THREAD

**Issue by two-dogs** [ntop/ntopng#2362]
presently the viewer shows date in format 02/02/2019 03:53:00, i have a hard time with that method, i cant find where to force method YYYY/mm/dd hh/min/sec

user manual does not show or i did not find

using 3.9.190209 - Community Edition
--

**Comment by emanuele-f** [comment]
Changing the format is not currently supported, no plans to do this for now sorry.
