### ISSUE TITLE
how to make it display MySQL query on ntopng dashboard

### ISSUE THREAD

**Issue by swathikothapu** [ntop/ntopng#2364]

**Comment by swathikothapu** [comment]
I have tried to connect one system to another system with Mysql , While doing queries I can able to see MySQL flow, But MySQL query is not showing in ntopng dashboard. kindly suggest me how to see MySQL actual query ( select * from table_name) in ntopng dashboard)


![image](https://user-images.githubusercontent.com/37098746/52638539-2f30b880-2ef8-11e9-8ddc-f19b61e60819.png)


**) if i click on info button 

![mysqlntopng2](https://user-images.githubusercontent.com/37098746/52638579-48396980-2ef8-11e9-8f18-e329cf489dfd.png)


**)) how to see MySQL actual query on dashboard

**Comment by simonemainardi** [comment]
what do you mean exactly?

**Comment by swathikothapu** [comment]
Thank you for reply, 

Using below cammand how ntopng send network flows to MySQL .

./ntopng --user admin -F "mysql;localhost;ntopng;flows;use;password"


I have Ubuntu system , where I am accessing from MySQL database names, and i have another PC (here ntopng installed ) where exactly all dumped database were stored. I  just connect from one system to another system for getting MySQL flows in ntopng dashboard  using (sudo mysql -u sernam -P 10.0.xx.xxx:3306 -p password;) command.

Example:  DESCRIBE flowsv4;       I have accessed from Ubuntu machine . Now I can see MySQL flow, But not query what i gave exactly ( DESCRIBE flowsv4) 







*****************************
Request question)
(** How to see MySQL exact query ( eg: SELECT * from Tablename) in ntopng dashboard)


*************************

Thanks
swathi

**Comment by emanuele-f** [comment]
Hi, logging queries is not supported by ntopng. However, you can enable log from MySQL it self, please check out https://stackoverflow.com/questions/303994/log-all-queries-in-mysql
