### ISSUE TITLE
nTopNG Memory Leak

### ISSUE THREAD

**Issue by HoseinKashefi** [ntop/ntopng#2366]
Cento-nTopNG Server has about 94G RAM, it's started by 10%< memory usage and after about 20 Days usage reach to 95%.
is it normal or need attention?
please find more info by attached screenshot and please tell me if anything else needed.
Thanks in advance.
 ![image](https://user-images.githubusercontent.com/43135531/52690833-31d0f380-2f74-11e9-8e8f-7b07290e99d3.png)
![image](https://user-images.githubusercontent.com/43135531/52690877-5036ef00-2f74-11e9-8b29-ec8ac7b4dd29.png)
![image](https://user-images.githubusercontent.com/43135531/52690928-7a88ac80-2f74-11e9-9d35-911db807a6b5.png)

**Comment by simonemainardi** [comment]
please post the full configuration used for both ntopng and cento

**Comment by HoseinKashefi** [comment]
ntopng Conf:
-G=/var/run/ntopng.pid
-i tcp://*:5556c
-w 10.47.84.81:3000
-m="x.X.x.X/23,y.Y.y.Y/22,z.Z.z.Z/22"
-X=524288
-x=524288
---------------------
Cento Conf
-i=zc:ens1f0
-i=zc:ens1f1
-i=zc:ens2f0
-i=zc:ens2f1
-i=zc:ens4f0
-i=zc:ens4f1
-i=zc:ens5f0
-i=zc:ens5f1
--zmq=tcp://127.0.0.1:5556
-g=0,1,2,3
-G=4,5,10,11
-D=2

**Comment by emanuele-f** [comment]
I've tried checking for memory leaks but the result is negative, can you monitor the memory usage vs number of active flows and hosts over time?

**Comment by HoseinKashefi** [comment]
you can find same duration for memory usage and flows here:
[I guest I should increase number of ntopng flows (x/X Parameters)]
![centoflows](https://user-images.githubusercontent.com/43135531/52896602-9fcd2300-31df-11e9-9c9f-db2f140407dc.png)
![centomemory](https://user-images.githubusercontent.com/43135531/52896603-9fcd2300-31df-11e9-8459-41dc9c065473.png)

**Comment by emanuele-f** [comment]
Very informative, thank you! Do you have the possibility to run `valgrind --leak-check=full ntopng /etc/ntopng/ntopng.conf` for some hours and post here a link to the output it returns? Please note that this will slow down ntopng a lot, so drops will likely occur.

**Comment by HoseinKashefi** [comment]
sure, but when I run this command, ntopng works with trial mode because this mode changes the system id. is it ok, or something is wrong?

**Comment by emanuele-f** [comment]
Yes, it is normal when running via valgrind

**Comment by HoseinKashefi** [comment]
so i guest we just have 10 minutes data.  where can i find valgrind's log?

**Comment by emanuele-f** [comment]
in community mode you should be able to write data without problems, the visualization however will only work for 10 minutes. Valgrind outputs data to console once you stop it with ctrl+c

**Comment by HoseinKashefi** [comment]
i tried 3 times and please  find them here.
[valgrind_ntopng3.log](https://github.com/ntop/ntopng/files/2875567/valgrind_ntopng3.log)
[valgrind_ntopng2.log](https://github.com/ntop/ntopng/files/2875568/valgrind_ntopng2.log)
[valgrind_ntopng4.log](https://github.com/ntop/ntopng/files/2875678/valgrind_ntopng4.log)

**Comment by simonemainardi** [comment]
I've tried to reproduce using your setup and valgrind without success. Also the traces enclosed doesn't seem to highlight memory leaks. 

Can you please repeat using the latest ntopng 3.9? Also make sure to let it run ntopng for a while inside valgrind so that possible issue can be catched.

**Comment by HoseinKashefi** [comment]
yes I had updated to v.3.9.190218 then ran it again, but unfortunately  same as before i guess.
[valgrind_ntopng5.log](https://github.com/ntop/ntopng/files/2876823/valgrind_ntopng5.log)

**Comment by emanuele-f** [comment]
This is probably related to #2404 . Please wait an hour until the new package is available and retry with the new version

**Comment by HoseinKashefi** [comment]
here with updated version(i think it is same as before )
v.3.9.190219
[valgrind_ntopng7.log](https://github.com/ntop/ntopng/files/2881718/valgrind_ntopng7.log)

**Comment by emanuele-f** [comment]
Please monitor the memory usage with the new version (normal operation, without valgrind), an important leak has been fixed, probably it was the one affecting you

**Comment by HoseinKashefi** [comment]
OK then. I've started yesterday and it has grown 10% until now. i will monitor it and update here

**Comment by emanuele-f** [comment]
@HoseinKashefi any news?

**Comment by HoseinKashefi** [comment]
here you can see memory usage 7 days chart(from ~80% availablity to ~20%) 
![centomemory7days](https://user-images.githubusercontent.com/43135531/53389479-b5430980-39a4-11e9-8b41-5f7f0d08df18.png)

**Comment by emanuele-f** [comment]
I've tried running valgrind again with exceeding hosts and flows but with negative results. Please use `valgrind --leak-check=full ntopng /etc/ntopng/ntopng.conf 2> valgrind_output.txt` and let it run for about one day. Then upload the `valgrind_output.txt` file.

**Comment by HoseinKashefi** [comment]
just for information , it worked only for 10 mins and it's changed to community mode .
in community mode flows doesn't go upper than 100 . is it normal?
![ntopng-com mode](https://user-images.githubusercontent.com/43135531/53412092-a3318d00-39dd-11e9-8f11-f2c0c23cd0dc.png)

**Comment by emanuele-f** [comment]
Switch to community mode is normal with valgrind. About the flow limit, there is no such limit in the community version. However, since valgrind is very cpu intensive, the machine may be slowed down to the point that it cannot process all the incoming flows. Please let it run for some minutes and, if the flows do not increase, then we need to find another way to debug this

**Comment by HoseinKashefi** [comment]
it's just grown by 1300 flows after 2 hours while there are about 800k flows.

**Comment by emanuele-f** [comment]
I see, please upload the valgrind log got so far, let's see if it contains miningfull information

**Comment by HoseinKashefi** [comment]
Please find the attachment
[valgrind_output.txt](https://github.com/ntop/ntopng/files/2908671/valgrind_output.txt)

**Comment by emanuele-f** [comment]
No luck. Please double check that the high memory usage is still caused by ntopng. Please also try changing the -x and -X (try for example with 100000 and 1048576) options and see how this affects the memory usage

**Comment by HoseinKashefi** [comment]
I've changed it and something like these has happened :
when I click on Flows I'm faced with "SyntaxError: Unexpected token H in JSON at position 0" error
and following logs are generated by ntopng : 
ntop: 27/Feb/2019 15:22:38 [ParserInterface.cpp:664] WARNING: JSON Parse error [object value separator ',' expected] payload size: 319 payload: {"8":"185.143.232.66","12":"82.99.200.246","10":0,"14":0,"2":58,"1":71610,"24":45,"23":5733,"22":1551268321,"21":1551268325,"7":80,"11":61936,"6":27,"4":6,"5":0,"35632.57590":7,"35632.57833":"ostadsalam.ir","35632.57652": "/css/main.min.css?v=<%=System.Configuration.ConfigurationManager.AppSettings["JsVersion"]%20%>"}
ntop: [ParserInterface.cpp:664] WARNING: JSON Parse error [object value separator ',' expected] payload size: 319 payload: {"8":"185.143.232.66","12":"82.99.200.246","10":0,"14":0,"2":58,"1":71610,"24":45,"23":5733,"22":1551268321,"21":1551268325,"7":80,"11":61936,"6":27,"4":6,"5":0,"35632.57590":7,"35632.57833":"ostadsalam.ir","35632.57652": "/css/main.min.css?v=<%=System.Configuration.ConfigurationManager.AppSettings["JsVersion"]%20%>"}
ntop: [LuaEngine.cpp:9040] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flows_data.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:1413: table index is nil]
ntop: 27/Feb/2019 15:28:37 [LuaEngine.cpp:9040] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flows_data.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:1413: table index is nil]
ntop: [LuaEngine.cpp:9040] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flows_data.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:1413: table index is nil]
ntop: 27/Feb/2019 15:28:41 [LuaEngine.cpp:9040] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flows_data.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:1413: table index is nil]
ntop: [LuaEngine.cpp:9040] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flows_data.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:1413: table index is nil]
ntop: 27/Feb/2019 15:28:43 [LuaEngine.cpp:9040] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flows_data.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:1413: table index is nil]


![image](https://user-images.githubusercontent.com/43135531/53488911-e1de4a80-3aa4-11e9-904b-5bc86fdcd42d.png)

**Comment by emanuele-f** [comment]
This error seems linked to improper escaping of HTTP_URL in cento, please create a new issue here: https://github.com/ntop/nProbe/issues

**Comment by HoseinKashefi** [comment]
Update+ 
compare 2 versions (3.9.190219|3.9.190227) for 7 days memory usage.
![image](https://user-images.githubusercontent.com/43135531/53715457-208a5100-3e67-11e9-981c-7896383e7793.png)

**Comment by emanuele-f** [comment]
I've added a chart which shows the ntopng memory consumption vs the number of active hosts and flows, the new package will be available in one hour. Please run it for one day and post here the screenshot.

Please check out "Process Memory vs Hosts/Flows"

**Comment by HoseinKashefi** [comment]
Please see screenshot:
![image](https://user-images.githubusercontent.com/43135531/53880783-2890ef00-4027-11e9-8de0-9403a515bcfe.png)
and here you can find datachart : 
[ntopngdatachart.txt](https://github.com/ntop/ntopng/files/2936154/ntopngdatachart.txt)

**Comment by HoseinKashefi** [comment]
For about 4 days:
![image](https://user-images.githubusercontent.com/43135531/54066680-72f1b600-4249-11e9-87d2-19750295edea.png)

**Comment by emanuele-f** [comment]
We've done more tests but we are still unable to detect a leak. In our tests, the memory seems to go up a bit when flows rise but not as steep as in your case. Can you provide web gui access to your server to try to spot some traffic peculiarities which may give an hint on the possible source of the leak? Please contact me at faranda@ntop.org

**Comment by emanuele-f** [comment]
The only particular thing I noticed after connecting to the gui si the flows page broken due to the cento issue above. In order to undestand where the leak could be, please perform the following changes one by one and test them in a 2 days period:

- Disable the alerts via the gui, so that we know that this is not related to the alerts
- Use `--max-num-flows "1024"` and monitor if the memory usage improves or not
- Use `--max-num-hosts "1024"` and monitor if the memory usage improves or not

If it's problematic to apply these changes to your running instance, please consider running another ntopng instance, possibly on another machine

**Comment by HoseinKashefi** [comment]
When I set max flow to 1024, ntopng doesn't show accurate traffic (Gbps or pps)
max-flow : 1048576
![image](https://user-images.githubusercontent.com/43135531/55680126-97b17a00-592a-11e9-8e91-b0371b09957b.png)
max-flow: 1024
![image](https://user-images.githubusercontent.com/43135531/55680223-017e5380-592c-11e9-88bd-b214015f68b8.png)
now I'm trying to set max-hosts to 1024 and will be  inform you after a while

**Comment by emanuele-f** [comment]
With these options the monitoring capabilities of your ntopng instance will be reduced as the number of flows/hosts will be capped at the specified limit and new flows/hosts will be discarded, so a reduction in traffic rate is normal

**Comment by HoseinKashefi** [comment]
Given the fact that  I cannot reduce the number of flows, and this traffic will be increased to about 60 Gbps and flows will be raised parallelly in near future, I wonder if you could apply a solution so that memory leak pales away.
P.S: Using the third option(max-host), I faced an improvement in memory usage which leads me to want to know what data or information I miss in return.

**Comment by emanuele-f** [comment]
If possible, please post the new memory screenshots with the reduced `--max-num-hosts` option. We still need to figure out the problem before being able to provide a fix for a possible leak. The initial fix #2404 I've made for this issue addressed a problem which was only evident when the hosts reached its limit value (`--max-num-hosts`), but in this case the problem seems different.

**Comment by HoseinKashefi** [comment]
Compare to the past it seems about 80% memory usage improvement
 ![image](https://user-images.githubusercontent.com/43135531/55855221-279a3280-5b7c-11e9-977c-0d439fb09874.png)

**Comment by emanuele-f** [comment]
Thank you for the info. We've spotted a possible issue with the DNS query field, which could be leaked. I'll update this issue after the fix, so that we can see if this is related.

**Comment by emanuele-f** [comment]
@HoseinKashefi please update to the latest version of ntopng which contains a fix and see if the memory usage improves, thank you

**Comment by HoseinKashefi** [comment]
emanuele,
Thank you, after update memory usage is improved
![image](https://user-images.githubusercontent.com/43135531/56107896-08c1e480-5f5e-11e9-88e5-757a3f334ddf.png)
but I guess there is an issue here,
I was comparing the charts and found out  about 30% decline on traffic chart that you can see the picture
![image](https://user-images.githubusercontent.com/43135531/56107825-af59b580-5f5d-11e9-9d2c-4a7b21f365fd.png)
traffic =~ 9.6 Gbps
nTtopng Shows =~ 7.5 Gbps
I will raise a new issue if needed.

**Comment by emanuele-f** [comment]
Maybe the `--max-num-flows` and `--max-num-hosts` are too low now and are limiting the traffic? Please check out the footer badges and the active hosts/flows charts

**Comment by HoseinKashefi** [comment]
I configured exactly the same as past and they are not reached to the maximum.

**Comment by emanuele-f** [comment]
I see, this is actually strange, if you have gather other information on this we will look at that. Please close this issue if the memory problem has been addressed for you.

**Comment by HoseinKashefi** [comment]
For Sure.
