### ISSUE TITLE
SMTP Alerting with Authentication

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#2368]
Many customer needs to configure SMTP Alerting with autentication. This is useful with cloud services also.

**Comment by simonemainardi** [comment]
please explain and make an example

**Comment by zimbawe998** [comment]
Some customer need user and password to connect to their internal MTA to allow ntopng to send alarm via smtp. TCP port 465/587 is required.

**Comment by simonemainardi** [comment]
as already experimented and commented in https://github.com/ntop/ntopng/issues/2044#issuecomment-427443966
we are currently not going to add authentication to ntopng as a series of issues may arise from this.

However, as a workaround, you can setup to 127.0.0.1 and setup postfix as a forwarder. Some of our users are successfully doing this.
