### ISSUE TITLE
MAC and IP historical information are mixed

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2369]
For local hosts ntopng uses the IP address as key. This is wrong for local broadcast domain hosts as if there are hosts with dynamic address (e.g. DHCP) the IP address information does NOT represent the information of the IP when 'impersonated' by the MAC. The result is (for instance) that with DHCP hosts, the IP address graph is a mix of all hosts that had such IP assigned.

It is requested for hosts in the local broadcast domain to use as 'anchor' for historical information (i.e. alerts, graphs, and serialised information on redis) the MAC address and not the IP as it is today. Please note that for IPv6 a host can have multiple addresses. Furthermore the same host can have an IPv4 address, so using as 'anchor' just the MAC without other ancillary data might not be enough to identify the information we're looking for.

**Comment by lucaderi** [comment]
Please note that this ticket depends on #2390.

**Comment by emanuele-f** [comment]
Initial work for host statistics and graphs: dd37cafa1276e083e251b813d3ff30f173c84856

**Comment by emanuele-f** [comment]
With 387543f8e9e74089ed146ce3c262260eb57a54e4 top senders and receivers are now calculated with the tskey as identifier

**Comment by emanuele-f** [comment]
After further testing, we need to document this and then the issue could be closed

**Comment by emanuele-f** [comment]
Documented in 0f2f6a7f0113dc21f7756a9bfba5683ba9eddcc1
