### ISSUE TITLE
Reports page - Script error

### ISSUE THREAD

**Issue by mineumann** [ntop/ntopng#237]
Version 2.1.151015 - Professional Edition

HTTP/1.1 500 Internal server error Content-Type: text/html Connection: close   Script "/usr/share/ntopng/scripts/lua/pro/report.lua" returned an error:
/usr/share/ntopng/scripts/lua/pro/report.lua:310: bad argument #1 to 'gsub' (string expected, got nil)

**Comment by simonemainardi** [comment]
fixed with commit 04b3a1b
