### ISSUE TITLE
Historical information and alerts are mixed 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2370]
When dumping historical information such as an alert, symbolic information such as the host name or for local broadcast domain host its MAC (see #2369) need to be serialised too. This means for instance that when an alert is retrieved, the symbolic host name must be retrieved from the serialised information and not resolved on the fly on the ntopng GUI.

**Comment by emanuele-f** [comment]
Alerts already display the original host names. For the historical data and traffic report, which resolve the host names during the visualization, a note has been added as suggested.
