### ISSUE TITLE
Implement ICMP Dissection

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2371]
Adding ICMP dissection allows for specific messages (e.g. ICMP port unreachable) to correlate the previous flow that triggered the ICMP message with the ICMP message. This is helpful in flow exploration as well to avoid generating alerts twice (e.g. when talking with a blacklisted host)

**Comment by simonemainardi** [comment]
implemented

https://github.com/ntop/ntopng/commit/ae23ebcd1cb4b91aa27defc134dfa7fb0fcc965d
