### ISSUE TITLE
Invalid MAC to Host Correlation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2372]
![macbug](https://user-images.githubusercontent.com/4493366/52738561-2e1e8a80-2fcf-11e9-9a8d-251f609dab94.png)

With a MAC address it's not possibile to associate hosts from remote locations. Furthermore non-local hosts do not show in the host info page the MAC address. These are bugs that need to be fixed.

**Comment by emanuele-f** [comment]
Partially addressed in ac4ad2a3d75e05e19c06130b2240ffac3e8f7b9e

**Comment by emanuele-f** [comment]
Issue has been fixed by the commit referenced above.
