### ISSUE TITLE
ntopng flow fields match with logstash field

### ISSUE THREAD

**Issue by swathikothapu** [ntop/ntopng#2374]
Hi,
 
I am exporting ntopng flows to logstash using below command, But Why ntopng fileds is not matching with logstash fileds.

./ntopng --user admin -F "logstash;localhost;tcp;3000"

![screenshot from 2019-02-14 15-33-24](https://user-images.githubusercontent.com/37098746/52779328-ec90ec80-306d-11e9-8257-7fc5d49baf39.png)

![image](https://user-images.githubusercontent.com/37098746/52779352-fa467200-306d-11e9-9925-e7f76b4072d7.png)

Thanks
swathi

**Comment by emanuele-f** [comment]
Hi, please update to the latest version as the problem may be already fixed

**Comment by swathikothapu** [comment]
Hi,

logstash-6.3.0

[root@localhost ntopng]# ntopng -V

v.3.6.181116	[Enterprise/Professional build]
Edition:	Enterprise
License Type:	Time-Limited


You can continue with discussion #2374

**Comment by swathikothapu** [comment]
Hi ,

**Comment by swathikothapu** [comment]
This issue is not closed . please help on this

**Comment by emanuele-f** [comment]
Please update to the latest ntopng version

**Comment by swathikothapu** [comment]
Thank you emanuele,

But my question is why ntopng dashboard fields and logstash log field names are not same.

**Comment by emanuele-f** [comment]
This is normal, the gui shows friendly names (also localized if language is not english) whereas logstash uses some "programmatic" names

**Comment by swathikothapu** [comment]
Thank you sir,

**Comment by emanuele-f** [comment]
The values are the same, although the gui shows the realtime traffic whereas on logstash the flow is only exported once it's complete (and as such will disappear from the gui), so you cannot do a 1:1 comparison between realtime and past flow data
