### ISSUE TITLE
Manually disable all "false positives" bloating the flow alerts list

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#2375]
ntopng be846535 (git20190212)

Depending on the configuration preferences, the list of flow alerts can, be **bloated/overwhelmed** with alerts:
- which are repeated endlessly
- and/or which we know are in fact OK
- and/or which are being taken care of and don't need to be listed anymore

For instance, a specific "TCP connection refused" alert between 2 specific hosts can be repeated every s/mn or so and yet match a normal & expected communication between 2 specific hosts.

Right now, the only way to prevent them from bloating the list is to disable the runtime preferences alert category to which the unnecessary alert belongs, i.e remove all the alerts of the same type even though some of them might be necessary and unrelated to the previous one (unless I missed something).

My proposal is to **offer the possibility to disable/filter specific alerts** matching:
- the type(s) of alert
- the source host(s)
- the destination host(s)
- the Level 4 application(s) (UDP/TCP...)
- the source port(s)
- the destination port(s)

Globbing should be allowed in each matching category.

Otherwise, the flow alerts become useless/ineffective.

**Comment by simonemainardi** [comment]
fine-grained alert filtering is already offered in the flow alerts explorer (enterprise version)

![image](https://user-images.githubusercontent.com/3397663/53099003-273ecd00-3525-11e9-9f97-266942dfae40.png)
