### ISSUE TITLE
Implement timeseries analysis for pcap files

### ISSUE THREAD

**Issue by timothysweeney** [ntop/ntopng#2376]
When analyzing PCAP files from disk capture timeseries data based on originating file timestamps in the same way that real-time captures are parsed and presented.

**Comment by emanuele-f** [comment]
Timeseries export/calculation is executed periodically whereas reading from a pcap is instantaneous, so implementing this may not be trivial

**Comment by timothysweeney** [comment]
The work we are looking at is to playback files via disk2n and capture data from that interface in ntopng.   The problem I anticipate with this is that it requires disk2n and storage to keep up with rates which would otherwise not have a real-time constraint.   Additionally timestamps will reflect the playback vs the original timestamps from the file.

**Comment by simonemainardi** [comment]
After internal review we've come to the conclusion that we cannot accomodate the request at this time. The whole part of ntopng that is in charge of writing historical timeseries assumes that is 'live' and it would require deep changes that we're unable to perform now.
