### ISSUE TITLE
Count the number of abnormal flows by anomaly

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2377]
Flows dumped on disk now have a new identifier, the "status", which indicates the id of the flows status. In order to implement a summary view to show a flow status along with the total number of dumped flows with that status, it's necessary to perform a "count() group by status" query on the flows.

**Comment by simonemainardi** [comment]
implemented. A Flow status overview is now available:

![image](https://user-images.githubusercontent.com/3397663/56366441-70dd2880-61f3-11e9-81c9-b65e46174b3e.png)
