### ISSUE TITLE
Anomaly indicators should not be depicted when not available

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2378]
![screen shot 2019-02-15 at 17 23 30](https://user-images.githubusercontent.com/4493366/52869901-ff2b2480-3146-11e9-876e-225c07b7d80f.png)
The anomaly indicators need a time window before they are active. As you can see in this graph the peak around the 18th has not been detected by RSI etc. as into the 21st the indicator is not working.

Solutions
1. Remove the indicators when not yet active
2. (better) compute them properly on the data you represent

**Comment by emanuele-f** [comment]
With 69b1dd998e62fe575024e4117cb9ae0e2662b17f points are not graphed anymore where in their rolling window. However, a better approach to be implemented is the calculation of such indicators in lua
