### ISSUE TITLE
JSON parse errors

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2381]
15/Feb/2019 16:22:16 [Mac.cpp:280] WARNING: JSON Parse error [unexpected end of data] key: ntopng.serialized_macs.ifid_4__52:54:00:87:70:F1: { "mac": "52:54:00:87:70:F1", "seen.first": 
15/Feb/2019 16:39:38 [LocalHost.cpp:143] WARNING: JSON Parse error [unexpected character] key: ntopng.serialized_hosts.ifid_4__fe80::a5b7:fc2a:8a20:3755@0: { "flows.as_client": 0, "flows.as_server": 1, "anomalous_flows.as_client": 0, "anomalous_flows.as_server": 0, "sent": { "packets": 0, "bytes": 0 }, "rcvd": { "packets": 3, "bytes": 258 }, "ndpiStats": { "ICMPV6": { "duration": 5, "bytes": { "sent": 0, "rcvd": 258 }, "packets": { "sent": 0, "rcvd": 3 } }, "categories": { "Network": { "id": 14, "bytes_sent": 0, "bytes_rcvd": 258, "duration": 5 } } }, "total_activity_time": 5, "dns": { "sent": { "stats": { } }, "rcvd": { "stats": { } } }, "http": { "sender": { "query": { }, "response": { }, "query_rate": { }, "response_rate": { } }, "receiver": { "query": { }, "response": { }, "query_rate": { }, "response_rate": { } } }, "ip": { "ipVersion": 6, "localHost": false, "ip": "fe80::a5b7:fc2a:8a20:3755" }, "mac_address": "00:26:18:8E:E3:86", "ifid": 4, "seen.first": 1550241966, "seen.last": 1550242061, "last_stats_reset": , "asn": 0, "symbolic_name": "pc-PC", "localHost": true, "systemHost": false, "broadcastDomainHost": true, "is_blacklisted": false, "num_alerts": 0 }

The above bug is standing since a long time (see also #552), It is now time to fix it properly.

**Comment by simonemainardi** [comment]
@emanuele-f 

![image](https://user-images.githubusercontent.com/3397663/52875759-6cde4d00-3155-11e9-85f2-54b8a75fc251.png)

it seems a bug with the last_stats_reset. why are you dumping this info to redis?  Can you fix this?

**Comment by lucaderi** [comment]
16/Feb/2019 01:03:47 [get_nindex_flows.lua:271] [get_nindex_flows.lua:86] ERROR: Internal library error
16/Feb/2019 02:38:52 [LocalHost.cpp:143] WARNING: JSON Parse error [unexpected end of data] key: ntopng.serialized_hosts.ifid_4__192.168.96.24@0: { "flows.as_client": 115, "flows.as_server": 280, "anomalous_flows.as_client": 0, "anomalous_flows.as_server": 0, "sent": { "packets": 279, "bytes": 67047 }, "rcvd": { "packets": 588, "bytes": 68785 }, "ndpiStats": { "Unknown": { "duration": 1345, "bytes": { "sent": 65367, "rcvd": 0 }, "packets": { "sent": 65367, "rcvd": 0 } }, "SNMP": { "duration": 1280, "bytes": { "sent": 0, "rcvd": 66335 }, "packets": { "sent": 0, "rcvd": 66215 } }, "SkypeCall": { "duration": 15, "bytes": { "sent": 729, "rcvd": 0 }, "packets": { "sent": 729, "rcvd": 0 } }, "ICMP": { "duration": 

15/Feb/2019 16:39:38 [LocalHost.cpp:143] WARNING: JSON Parse error [unexpected character] key: ntopng.serialized_hosts.ifid_4__fe80::a5b7:fc2a:8a20:3755@0: { "flows.as_client": 0, "flows.as_server": 1, "anomalous_flows.as_client": 0, "anomalous_flows.as_server": 0, "sent": { "packets": 0, "bytes": 0 }, "rcvd": { "packets": 3, "bytes": 258 }, "ndpiStats": { "ICMPV6": { "duration": 5, "bytes": { "sent": 0, "rcvd": 258 }, "packets": { "sent": 0, "rcvd": 3 } }, "categories": { "Network": { "id": 14, "bytes_sent": 0, "bytes_rcvd": 258, "duration": 5 } } }, "total_activity_time": 5, "dns": { "sent": { "stats": { } }, "rcvd": { "stats": { } } }, "http": { "sender": { "query": { }, "response": { }, "query_rate": { }, "response_rate": { } }, "receiver": { "query": { }, "response": { }, "query_rate": { }, "response_rate": { } } }, "ip": { "ipVersion": 6, "localHost": false, "ip": "fe80::a5b7:fc2a:8a20:3755" }, "mac_address": "00:26:18:8E:E3:86", "ifid": 4, "seen.first": 1550241966, "seen.last": 1550242061, "last_stats_reset": , "asn": 0, "symbolic_name": "pc-PC", "localHost": true, "systemHost": false, "broadcastDomainHost": true, "is_blacklisted": false, "num_alerts": 0 }

over and over and over.....

**Comment by lucaderi** [comment]
Further errors:
17/Feb/2019 23:47:30 [Mac.cpp:280] WARNING: JSON Parse error [unexpected character] key: ntopng.serialized_macs.ifid_0__78:7B:8A:C7:AF:28: { "mac": "78:7B:8A:C7:AF:28", "seen.first": , "seen.last": 1550442938, "last_stats_reset": 0, "devtype": 3, "model": "iMac18,3", "dhcpHost": true, "operatingSystem": 0, "fingerprint": "010306", "ndpiStats": { "categories": { "Network": { "id": 0, "bytes_sent": 2030, "bytes_rcvd": 0, "duration": 25 } } } }
17/Feb/2019 23:47:49 [Mac.cpp:280] WARNING: JSON Parse error [unexpected character] key: ntopng.serialized_macs.ifid_4__52:54:00:BC:11:7B: { "mac": "52:54:00:BC:11:7B", "seen.first": , "seen.last": 1550442938, "last_stats_reset": 0, "devtype": 0, "dhcpHost": false, "operatingSystem": , "ndpiStats": { "categories": { "Unspecified": { "id": 0, "bytes_sent": 0, "bytes_rcvd": 3270, "duration": 20 } } } }
17/Feb/2019 23:49:22 [Mac.cpp:280] WARNING: JSON Parse error [unexpected character] key: ntopng.serialized_macs.ifid_0__00:0E:08:DD:0E:6A: { "mac": "00:0E:08:DD:0E:6A", "seen.first": 1549995714, "seen.last": , "last_stats_reset": 0, "devtype": 0, "dhcpHost": false, "operatingSystem": 0 }
17/Feb/2019 23:50:35 [Mac.cpp:280] WARNING: JSON Parse error [unexpected end of data] key: ntopng.serialized_macs.ifid_4__00:1E:68:37:AF:5F: { "mac": "00:1E:68:37:AF:5F", "seen.first": 1550388557, "seen.last": 2055

**Comment by emanuele-f** [comment]
There seem to be two different issues:
- Truncated json see (`"ICMP": { "duration":`)
- Missing values (`seen.first`, `last_stats_reset`, `seen.last`, all of these use the `json_object_new_int64`)

**Comment by simonemainardi** [comment]
Unable to reproduce. please, reopen if necessary.

**Comment by lucaderi** [comment]
Other examples of issues

16/Apr/2019 00:42:14 [LocalHost.cpp:150] WARNING: JSON Parse error [unexpected character] key: ntopng.serialized_hosts.ifid_1__fe80::59f7:6de1:a8ea:260@0: { "flows.as_client": 15, "flows.as_server": 0, "anomalous_flows.as_client": 0, "anomalous_flows.as_server": 0, "unreachable_flows.as_client": 0, "unreachable_flows.as_server": 0, "host_unreachable_flows.as_client": 0, "host_unreachable_flows.as_server": 0, "total_alerts": 0, "sent": { "packets": 180, "bytes": 1 }, "rcvd": { "packets": 0, "bytes":  }, "ndpiStats": { "ICMPV6": { "duration": 365, "bytes": { "sent": 15480, "rcvd": 0 }, "packets": { "sent": 14460, "rcvd": 0 } }, "categories": { "Network": { "id": 14, "bytes_sent": 15480, "bytes_rcvd": 0, "duration": 365 } } }, "total_activity_time": 365, "dns": { "sent": { "stats": { } }, "rcvd": { "stats": { } } }, "http": { "sender": { "query": { }, "response": { }, "query_rate": { }, "response_rate": { } }, "receiver": { "query": { }, "response": { }, "query_rate": { }, "response_rate": { } } }, "ip": { "ipVersion": 6, "localHost": false, "ip": "fe80::59f7:6de1:a8ea:260" }, "mac_address": "18:60:24:7B:EB:1E", "ifid": 1, "seen.first": 1555358385, "seen.last": 0
JSON Parse error [unexpected character] key: ntopng.serialized_hosts.ifid_1__fe80::59f7:6de1:a8ea:260@0: { "flows.as_client": 15, "flows.as_server": 0, "anomalous_flows.as_client": 0, "anomalous_flows.as_server": 0, "unreachable_flows.as_client": 0, "unreachable_flows.as_server": 0, "host_unreachable_flows.as_client": 0, "host_unreachable_flows.as_server": 0, "total_alerts": 0, "sent": { "packets": 180, "bytes": 1 }, "rcvd": { "packets": 0, "bytes":  }, "ndpiStats": { "ICMPV6": { "duration": 365, "bytes": { "sent": 15480, "rcvd": 0 }, "packets": { "sent": 14460, "rcvd": 0 } }, "categories": { "Network": { "id": 14, "bytes_sent": 15480, "bytes_rcvd": 0, "duration": 365 } } }, "total_activity_time": 365, "dns": { "sent": { "stats": { } }, "rcvd": { "stats": { } } }, "http": { "sender": { "query": { }, "response": { }, "query_rate": { }, "response_rate": { } }, "receiver": { "query": { }, "response": { }, "query_rate": { }, "response_rate": { } } }, "ip": { "ipVersion": 6, "localHost": false, "ip": "fe80::59f7:6de1:a8ea:260" }, "mac_address": "18:60:24:7B:EB:1E", "ifid": 1, "seen.first": 1555358385, "seen.last": 016/Apr/2019 00:43:04 [LocalHost.cpp:150] WARNING: JSON Parse error [unexpected end of data] key: ntopng.serialized_hosts.ifid_3__fe80::59f7:6de1:a8ea:260@0: { "flows.as_client": 
JSON Parse error [unexpected end of data] key: ntopng.serialized_hosts.ifid_3__fe80::59f7:6de1:a8ea:260@0: { "flows.as_client": 16/Apr/2019 09:00:53 [LocalHost.cpp:150] WARNING: JSON Parse error [unexpected end of data] key: ntopng.serialized_hosts.ifid_1__fe80::59f7:6de1:a8ea:260@0: { "flows.as_client": 44, "flows.as_server": 0, "anomalous_flows.as_client": 0, "anomalous_flows.as_server": 0, "unreachable_flows.as_client": 0, "unreachable_flows.as_server": 0, "host_unreachable_flows.as_client": 0, "host_unreachable_flows.as_server": 0, "total_alerts": 0, "sent": { "packets": 528, "bytes": 45408 }, "rcvd": { "packets": 0, "bytes": 0 }, "ndpiStats": { "ICMPV6": { "duration": 1090, "bytes": { "sent": 45408, "rcvd": 0 }, "packets": { "sent": 44388, "rcvd": 0 } }, "categories": { "Network": { "id": 14, "bytes_sent": 45408, "bytes_rcvd": 0, "duration": 1090 } } }, "total_activity_time": 1090, "dns": { "sent": { "stats": { } }, "rcvd": { "stats": { } } }, "http": { "sender": { "query": { }, "response": { }, "query_rate": { }, "response_rate": { } }, "receiver": { "query": { }, "response": { }, "query_rate": { }, "response_rate": { } } }, "ip": { "ipVersion": 6, "localHost": false, "ip": "fe80::59f7:6de1:a8ea:260" }, "mac_address": "18:60:24:7B:EB:1E", "ifid": 1, "seen.first": 17
JSON Parse error [unexpected end of data] key: ntopng.serialized_hosts.ifid_1__fe80::59f7:6de1:a8ea:260@0: { "flows.as_client": 44, "flows.as_server": 0, "anomalous_flows.as_client": 0, "anomalous_flows.as_server": 0, "unreachable_flows.as_client": 0, "unreachable_flows.as_server": 0, "host_unreachable_flows.as_client": 0, "host_unreachable_flows.as_server": 0, "total_alerts": 0, "sent": { "packets": 528, "bytes": 45408 }, "rcvd": { "packets": 0, "bytes": 0 }, "ndpiStats": { "ICMPV6": { "duration": 1090, "bytes": { "sent": 45408, "rcvd": 0 }, "packets": { "sent": 44388, "rcvd": 0 } }, "categories": { "Network": { "id": 14, "bytes_sent": 45408, "bytes_rcvd": 0, "duration": 1090 } } }, "total_activity_time": 1090, "dns": { "sent": { "stats": { } }, "rcvd": { "stats": { } } }, "http": { "sender": { "query": { }, "response": { }, "query_rate": { }, "response_rate": { } }, "receiver": { "query": { }, "response": { }, "query_rate": { }, "response_rate": { } } }, "ip": { "ipVersion": 6, "localHost": false, "ip": "fe80::59f7:6de1:a8ea:260" }, "mac_address": "18:60:24:7B:EB:1E", "ifid": 1, "seen.first": 1716/Apr/2019 10:51:01 [LocalHost.cpp:150] WARNING: JSON Parse error [unexpected end of data] key: ntopng.serialized_hosts.ifid_3__192.12.193.6@0: { "flows.as_client": 1579, "flows.as_server": 54394, "anomalous_flows.as_client": 0, "anomalous_flows.as_server": 0, "unreachable_flows.as_client": 0, "unreachable_flows.as_server": 0, "host_unreachable_flows.as_client": 0, "host_unreachable_flows.as_server": 0, "total_alerts": 0, "sent": { "packets": 55828, "bytes": 51
JSON Parse error [unexpected end of data] key: ntopng.serialized_hosts.ifid_3__192.12.193.6@0: { "flows.as_client": 1579, "flows.as_server": 54394, "anomalous_flows.as_client": 0, "anomalous_flows.as_server": 0, "unreachable_flows.as_client": 0, "unreachable_flows.as_server": 0, "host_unreachable_flows.as_client": 0, "host_unreachable_flows.as_server": 0, "total_alerts": 0, "sent": { "packets": 55828, "bytes": 5116/Apr/2019 10:54:07 [LocalHost.cpp:150] WARNING: JSON Parse error [unexpected end of data] key: ntopng.serialized_hosts.ifid_3__192.12.193.54@0: { "flows.as_client": 18, "flows.as_server": 7, "anomalous_flows.as_client": 1, "anomalous_flows.as_server": 5, "unreachable_flows.as_client": 0, "unreachable_flows.as_server": 0, "host_unreachable_flows.as_client": 0, "host_unreachable_flows.as_server": 0, "total_alerts": 6, "sent": { "packets": 40, "bytes": 8426 }, "rcvd": { "packets": 11, "bytes": 867 }, "ndpiStats": { "Unknown": { "duration": 5, "bytes": { "sent": 66, "rcvd": 0 }, "packets": { "sent": 66, "rcvd": 0 } }, "HTTP": { "duration": 5, "bytes": { "sent": 0, "rcvd": 370 }, "packets": { "sent": 
JSON Parse error [unexpected end of data] key: ntopng.serialized_hosts.ifid_3__192.12.193.54@0: { "flows.as_client": 18, "flows.as_server": 7, "anomalous_flows.as_client": 1, "anomalous_flows.as_server": 5, "unreachable_flows.as_client": 0, "unreachable_flows.as_server": 0, "host_unreachable_flows.as_client": 0, "host_unreachable_flows.as_server": 0, "total_alerts": 6, "sent": { "packets": 40, "bytes": 8426 }, "rcvd": { "packets": 11, "bytes": 867 }, "ndpiStats": { "Unknown": { "duration": 5, "bytes": { "sent": 66, "rcvd": 0 }, "packets": { "sent": 66, "rcvd": 0 } }, "HTTP": { "duration": 5, "bytes": { "sent": 0, "rcvd": 370 }, "packets": { "sent": 16/Apr/2019 15:20:19 [LocalHost.cpp:150] WARNING: JSON Parse error [unexpected character] key: ntopng.serialized_hosts.ifid_3__192.12.193.59@0: { "flows.as_client": 86, "flows.as_server": 4, "anomalous_flows.as_client": 0, "anomalous_flows.as_server": 4, "unreachable_flows.as_client": 0, "unreachable_flows.as_server": 0, "host_unreachable_flows.as_client": 0, "host_unreachable_flows.as_server": 0, "total_alerts": 4, "sent": { "packets": , "bytes": 83033 }, "rcvd": { "packets": , "bytes": 1638 }, "ndpiStats": { "MDNS": { "duration": 0, "bytes": { "sent": 19178, "rcvd": 0 }, "packets": { "sent": 19178, "rcvd": 0 } }, "NetBIOS": { "duration": 3

**Comment by simonemainardi** [comment]
safe to close now as it is solved.
