### ISSUE TITLE
Lua script failure at midnight

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2383]
16/Feb/2019 00:00:00 [LuaEngine.cpp:8617] WARNING: Script failure [/home/deri/ntopng/scripts/callbacks/system/daily.lua][/home/deri/ntopng/scripts/lua/modules/delete_data_utils.lua:516: field 'day' missing in date table]

**Comment by emanuele-f** [comment]
Should be fixed in 0065eb9cd4d405b543da9ff0b83b4ba9e004409e . Please reopen if necessary.
