### ISSUE TITLE
Error while downloading lists

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2384]
16/Feb/2019 01:00:32 [housekeeping.lua:27] [lists_utils.lua:268] WARNING: An error occurred while downloading list 'Emerging Threats': http_code=0

What is error code 0 ?
Internet connectivity is not an issue, so the problem is elsewhere.

**Comment by lucaderi** [comment]
Same as in the past days
18/Feb/2019 01:00:27 [housekeeping.lua:27] [lists_utils.lua:268] WARNING: An error occurred while downloading list 'Emerging Threats': http_code=0

**Comment by emanuele-f** [comment]
![2019-02-18_11-58](https://user-images.githubusercontent.com/5488003/52946548-2adb2400-336c-11e9-8929-c88bc5a19bfe.png)

The server timeout out, timeout is 20 seconds right now, which is pretty high though

**Comment by emanuele-f** [comment]
Time extended to 1 minute in 3d8e20bf5f1c9c2bfa7b3f475272ecbdf1192495

**Comment by emanuele-f** [comment]
Fixed with the commit above
