### ISSUE TITLE
Invalid TCP states

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2385]
![screen shot 2019-02-16 at 11 34 21](https://user-images.githubusercontent.com/4493366/52898478-dc4c4f00-31de-11e9-90fd-2c863425075c.png)
The TCP states that have been implemented are not correct and some states are useless. Organise the menu in
1. All TCP flows
2. Established flows (i.e. flows that past 3WH and that are active)
3. Connecting (e.g. SYN only, with no 3WH)
4. Closed (i.e. clean termination with 3WH or FIN-RST)
5. Reset (e.g. RST with no FIN)

Please note that this ticket and #2380 reference each other.

Shall you have doubts in interpreting TCP states please refer to the picture below.
![dwgl0004](https://user-images.githubusercontent.com/4493366/52898514-3ea54f80-31df-11e9-9db5-5648297907b1.gif)

**Comment by simonemainardi** [comment]
implemented as requested:

<img width="216" alt="image" src="https://user-images.githubusercontent.com/3397663/52902878-57c9f280-3217-11e9-836a-4a90f9b8a49c.png">
