### ISSUE TITLE
Write a lists blog post

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2388]
Security lists have been implemented and documented in https://www.ntop.org/guides/ntopng/advanced_features/category_lists.html?highlight=category but they have not announced with a blog post.

Please fix #2384 and write a blog post.

**Comment by emanuele-f** [comment]
Now online https://www.ntop.org/ntopng/how-to-track-an-fight-malware-ransomware-botnets-network-traffic-using-ntopng
