### ISSUE TITLE
Changing HTTP port from 3000 to something else does not work

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#239]
Example:
ntopng -i 1 --http-port 6000 --user root

15/Oct/2015 15:10:16 [Ntop.cpp:929] Setting local networks to 127.0.0.0/8
15/Oct/2015 15:10:16 [Redis.cpp:105] Successfully connected to redis 127.0.0.1:6379@0
15/Oct/2015 15:10:18 [PcapInterface.cpp:81] Reading packets from interface wlan0...
15/Oct/2015 15:10:18 [Ntop.cpp:1178] Registered interface view wlan0 [id: 4]
15/Oct/2015 15:10:18 [Ntop.cpp:1148] Registered interface wlan0 [id: 0]
15/Oct/2015 15:10:18 [Utils.cpp:304] User changed to root
15/Oct/2015 15:10:18 [main.cpp:237] PID stored in file /var/tmp/ntopng.pid
15/Oct/2015 15:10:18 [HTTPserver.cpp:458] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
15/Oct/2015 15:10:18 [HTTPserver.cpp:501] Web server dirs [/usr/local/share/ntopng/httpdocs][/usr/local/share/ntopng/scripts]
15/Oct/2015 15:10:18 [HTTPserver.cpp:504] HTTP server listening on port 6000
15/Oct/2015 15:10:18 [main.cpp:290] Working directory: /var/tmp/ntopng
15/Oct/2015 15:10:18 [main.cpp:292] Scripts/HTML pages directory: /usr/local/share/ntopng
15/Oct/2015 15:10:18 [Ntop.cpp:260] Welcome to ntopng x86_64 v.2.1.151014 - (C) 1998-15 ntop.org
15/Oct/2015 15:10:18 [Ntop.cpp:265] Built on Ubuntu 15.04
15/Oct/2015 15:10:18 [PeriodicActivities.cpp:53] Started periodic activities loop...
15/Oct/2015 15:10:18 [RuntimePrefs.cpp:32] Dumping alerts into syslog
15/Oct/2015 15:10:18 [Ntop.cpp:512] Adding 192.168.1.0/24 as IPv4 local network
15/Oct/2015 15:10:18 [NetworkInterface.cpp:1410] Started packet polling on interface wlan0 [id: 0]...

Then: http://127.0.0.1:6000 with chrome 46 leads to... "This webpage is not available"

**Comment by simonemainardi** [comment]
chrome considers port 6000 unsafe. Port 6000 is a well-known port reserved for X11. Try to change 6000 with 6001.

The fill list of ports considered unsafe by chrome can be found in its source code. Have a look at http://src.chromium.org/viewvc/chrome/trunk/src/net/base/net_util.cc?view=markup

**Comment by jean-christophe-manciot** [comment]
Yes, you're right.
