### ISSUE TITLE
Improve local broadcast detection algorithm

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2390]
The algorithm used to identify local subnet (broadcast) hosts is a 1:1 match. Example:
![screen shot 2019-02-16 at 12 04 03](https://user-images.githubusercontent.com/4493366/52898821-fab44980-31e2-11e9-83b4-00eed80d0c5b.png)

in the above example ntopng assumes that 192.168.1.{246,1,2} as local subnet hosts. While this is a correct assumption it is possible to learn more than this from the above ARP packets. In fact if .246 wants to know the MAC address of .1, it means that are both in the same subnet and thus that the local subnet broadcast is 192.168.1.0/24. Without implementing complex login that would be error prone and take a while, please refine the detection algorithm for the most common subnet masks. This means that ntopng will have internally a dynamically populated list of broadcast domain networks (this similar albeit different from the local networks list) used to detect local subnet hosts.

Please note that #2369 will benefit from implementing this ticket.

**Comment by simonemainardi** [comment]
Implemented in
https://github.com/ntop/ntopng/commit/f98681b58f1ba804f1215318c344be90d2dda7e5
