### ISSUE TITLE
Add timeseries of triggered alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2392]
In local hosts it is requested to implement a new timeseries containing (gauge) the number of alerts triggered. Please divide it in number of alerts caused by the host, and number or alerts for which the host has been victim. Currently it is not necessary to distinguish the alert type in the time serie.

These timeseries must be depicted in the host charts in a single chart where they are stacked.

**Comment by emanuele-f** [comment]
Should we graph the engaged alerts or the "anomalous flows as client/server"?

**Comment by simonemainardi** [comment]
yes, please do the suggested way.

**Comment by lucaderi** [comment]
This issue is about tracking the number of engaged alerts ntopng has reported per host. If a host is constantly moving from engaged-disengaged I might see no alerts (unless I open the past history alert view) but the host has several issues. So please add a host counter with the number of times you have created an engaged alert per host. Please see #2409

**Comment by simonemainardi** [comment]
Keep a `cumulative` counter in the host that is incremented every time an engaged alert is triggered. then use this counter to produce the timeseries.

**Comment by simonemainardi** [comment]
also add the "Total Alerts" as an extra custom column entry for the host page to implement this related isssue:

https://github.com/ntop/ntopng/issues/2391

**Comment by emanuele-f** [comment]
A per-host total alerts counter and corresponding chart has been implemented in a486d2c19fc7226f9b247f3051b1d6b55268beb7 . It counts the total number of alerts (engaged and flow alerts) of an host, please check it out

**Comment by emanuele-f** [comment]
Closing after positive feedback
