### ISSUE TITLE
[nEdge] PPPoE bypasses the policer

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2393]
Opening a PPoE session bypasses the policer and it allows to freely connect to the Internet if the router (as most ADSL router do) supports it.

**Comment by lucaderi** [comment]
Hint: ebtables -A FORWARD -p 0x8863 -j DROP

**Comment by emanuele-f** [comment]
Fixed. Now only ipv4, ipv6 (blocked by iptables) and arp are allowed.
