### ISSUE TITLE
Too many hosts message reportedly appears also when using InfluxDB

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#2396]
2 users have reported that the yellow warning appears also when InfluxDB is enabled

![image](https://user-images.githubusercontent.com/3397663/52939398-640f9600-3364-11e9-855b-782f8fcfc8e7.png)

**Comment by emanuele-f** [comment]
Fixed in 576d28d2195cfb7111356258f25e0603ed33881d
