### ISSUE TITLE
Add ability to mask MAC addresses

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2399]
In specific setups (e.g. when using a traffic generator) MAC addresses are generated randomly and this causes ntopng to have severe performance degradation (as well memory usage) for information that is useless to the user.

It is requested to add a preference that allow users to mask MAC addresses, and thus avoid the problem.

**Comment by simonemainardi** [comment]
add an option similar to --ignore-vlans but for mac addresses
```
--ignore-vlans                      | Ignore VLAN tags from traffic
```
