### ISSUE TITLE
How to pipe an interface name into ntopng?

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#240]
It would be great to be able to use ntopng within GNS3.
When using Wireshark, the following command is applied when a network interface is selected by the user in the topology through the GUI:
tail -f -c +0b %c | wireshark -k -i -
wireshark command is specifically designed for pîping (-i -); I did not see anything like it with ntopng. Am I missing something?
BTW, the previous command is configurable within GNS3 so we can launch any type of traffic analyzer.

**Comment by lucaderi** [comment]
You can't do this today. I am not familiar with GNS3. Can you please provide an example with a simpler/popular command tool such a tcpdump?

**Comment by jean-christophe-manciot** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/13176858/10558862/4d8ccb6e-74e0-11e5-84ec-986cde55b871.png)
https://community.gns3.com/community/software/download

**Comment by jean-christophe-manciot** [comment]
The previous screenshot is a lab example of what can be virtualized within GNS3.
