### ISSUE TITLE
Missing host and flow information

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2401]
![mining](https://user-images.githubusercontent.com/4493366/52966529-d0f84f80-33a7-11e9-9933-b490cb4c41bc.png)
The above alert is misleading and probably a false positive as it does not contain the requested host name that has triggered the alert (not to mention that IPs are local this it might be a non alert)

**Comment by simonemainardi** [comment]
Fixes. It was due to an nDPI issue https://github.com/ntop/nDPI/commit/d283538146c64912a50b177b073b9b5c85c270c9.
