### ISSUE TITLE
Invalid and incomplete alert

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2402]
![445](https://user-images.githubusercontent.com/4493366/52966655-22084380-33a8-11e9-9231-f777a9b7947c.png)
The above alert has many flaws
1. it does not include the L7 protocol
2. it is likely top be SMB and thus it is quite normal that these type of flows are large
3. it does not indicate how large if the flow volume for having triggered the alert
4. it is not clear if the elephant flow trigger algorithm can be configured, and if not what are the default values for flow size and protocols to which the check is applied

**Comment by simonemainardi** [comment]
added information on the volume exceeded for elephant flows

![image](https://user-images.githubusercontent.com/3397663/53021605-da41f480-3459-11e9-9341-eb6b9e782db4.png)

**Comment by simonemainardi** [comment]
- exclude protocols that are in the category file transfer from the elephant flow alerts
- add  a link that brings the user to the configuration page of the elephant flows
