### ISSUE TITLE
ICMP flows do not contain any information that can be used for further investigation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2403]
![icmp](https://user-images.githubusercontent.com/4493366/52966853-a3f86c80-33a8-11e9-86f0-90dd509711d6.png)

Same as #2402. Please add begin/end timestamp, volume, ICMP message types exchanged

**Comment by simonemainardi** [comment]
begin/end tstamp and volume not available as alerts are emitted as soon as possible so they contain partial data.

For timestamp, volume, etc one should go in nIndex and we have already added anchors for this.

![image](https://user-images.githubusercontent.com/3397663/53017536-7f57cf80-3450-11e9-96dd-1f3c44a732c6.png)

**Comment by simonemainardi** [comment]
also added the protocol:

![image](https://user-images.githubusercontent.com/3397663/53017765-0d33ba80-3451-11e9-8512-c7f404b3f517.png)
