### ISSUE TITLE
ifAlias as selector/identifier/description instead of ifName and/or ifIndex

### ISSUE THREAD

**Issue by jlixfeld** [ntop/ntopng#2407]
In Flow Devices view, is it possible to see ifAlias (if set) instead of ifName and/or ifIndex?  In the attached images, ifIndex and/or ifName are displayed, but those aren't always as useful as seeing ifAlias.

![screen shot 2019-02-19 at 9 49 54 am](https://user-images.githubusercontent.com/17339017/53024229-a00e2e00-342c-11e9-8acc-e49ac711938e.png)
![screen shot 2019-02-19 at 9 49 33 am](https://user-images.githubusercontent.com/17339017/53024230-a00e2e00-342c-11e9-95d8-784fa8c9d98e.png)
![screen shot 2019-02-19 at 9 49 23 am](https://user-images.githubusercontent.com/17339017/53024232-a00e2e00-342c-11e9-9114-d68ca7afc7c9.png)

**Comment by simonemainardi** [comment]
Aliases walked and added. A new build will be available in one hour.

![image](https://user-images.githubusercontent.com/3397663/56418336-ebab4f80-6296-11e9-99ab-4c3bd0fdd9f2.png)

![image](https://user-images.githubusercontent.com/3397663/56418119-4d1eee80-6296-11e9-8808-05f52371d34c.png)

![image](https://user-images.githubusercontent.com/3397663/56418322-e0f0ba80-6296-11e9-8a0d-a31bf0b451a8.png)
