### ISSUE TITLE
Display scaled bps in addition to percentage

### ISSUE THREAD

**Issue by jlixfeld** [ntop/ntopng#2408]
In Flow Devices view,  it is it possible to display throughput in bps (or scaled to Mbps, Gbps, etc) in addition to percentage?

![screen shot 2019-02-19 at 9 49 09 am](https://user-images.githubusercontent.com/17339017/53096298-ceebd900-34ec-11e9-8156-33d459b1785f.png)

**Comment by simonemainardi** [comment]
do you mean you want to see in the table the average throughput in the selected time frame?

**Comment by jlixfeld** [comment]
Yes.  I apologize for the confusion.  I have re-uploaded the sample image.  I'm wondering if it's possible to have it visible within the table I have highlighted in the image.

**Comment by emanuele-f** [comment]
Implemented, please upgrade ntopng tomorrow to get the new column. Please note that this feature is implemented in the development branch whereas you are using the stable. Check out http://packages.ntop.org and install the nightly builds or wait for the next stable (no eta yet).
