### ISSUE TITLE
BGP traffic undetected until a connection is open

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#241]
Cf.misplaced thread in ntop/nDPI: https://github.com/ntop/nDPI/issues/107

**Comment by kYroL01** [comment]
Fixed as explain here: 74b016c8b6d74e0c2c9be55fd3ac331d23bbdbb4

Only an explanation: in ntopng is missing the datalink type part to see the pcap you passed in nDPI.
Work in progress. Is not a non-detection of BGP.
