### ISSUE TITLE
Add Alert when a Custom List fails to download

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#2410]
When a custom list fails to download, it goes in an "Error" state but the user can't notice it unless he/she goes into the custom lists page.

It is requested to add an alert to notify the user when a custom list fails to download.

**Comment by simonemainardi** [comment]
also consider that lists are updated at 1AM whilst they should be updated at midnight

![image](https://user-images.githubusercontent.com/3397663/53079316-6d306c80-34f6-11e9-816e-c688cf9e44b4.png)

**Comment by emanuele-f** [comment]
Example alert: ![2019-02-20_11-36](https://user-images.githubusercontent.com/5488003/53107305-b0a5cd80-352c-11e9-9e27-9916ae540676.png)
