### ISSUE TITLE
Cumbersome historical flow access

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2412]
In order to view historical host flows, it is currently necessary to visit several pages (See example below)
![1](https://user-images.githubusercontent.com/4493366/53191821-25503900-360d-11e9-9f90-1a2cb2c07e53.png)

Add a "raw flow" entry in the menu below for a gives host
![screen shot 2019-02-21 at 19 16 57](https://user-images.githubusercontent.com/4493366/53191872-4b75d900-360d-11e9-9fa0-c4bfb02f55df.png)

**Comment by emanuele-f** [comment]
Implemented
