### ISSUE TITLE
Missing Layer 4 and 7 Protocols and Misleading Flow Status

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2413]
![1](https://user-images.githubusercontent.com/4493366/53191987-8841d000-360d-11e9-859e-b6e1ec856896.png)

The above view does not contain
- L4 protocol (e.g. TCP)
- L7 protocol (e.g. Dropbox)

Furthermore the flow status is wrong as all TCP flows have a flow status that indicates a problem and this is not the case. The algorithm must be refined and the dumped flow status must be consistent with the flow status when the flow was still in memory

**Comment by emanuele-f** [comment]
Currently there is a limitation on the maximum number of fields returned by nIndex (11 seems the limit). This must be extended in order to provide additional flow information

**Comment by emanuele-f** [comment]
L4 and L7 now added

**Comment by simonemainardi** [comment]
flow status fixed as well
