### ISSUE TITLE
Poor information reported in ICMP Flows

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2414]
![1](https://user-images.githubusercontent.com/4493366/53192249-45ccc300-360e-11e9-83d5-dc89ba2fb407.png)
The above alerted flow is not properly reported
1. ICMP is not an application
2. The "Protocol: ICMP" should be reported in a more compact format
3. The original flow that triggered the "port unreachable" is not reported

**Comment by simonemainardi** [comment]
Fixed

![image](https://user-images.githubusercontent.com/3397663/53586538-acab2880-3b88-11e9-8f3a-fdba33f33002.png)
