### ISSUE TITLE
ICMP Information Missing from Live Flows

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2415]
![2](https://user-images.githubusercontent.com/4493366/53192425-b4118580-360e-11e9-9277-ac79ef8ee57c.png)

The above ICMP flow does not show what original flow that triggered it. Please report it.

**Comment by emanuele-f** [comment]
Cannot reproduce, my instance of ntopng shows the original flow information correctly

![2019-02-25_16-49](https://user-images.githubusercontent.com/5488003/53349438-fc81b980-3914-11e9-8f5c-f05e9adfb29d.png)

**Comment by simonemainardi** [comment]
Can happen when the original flow that triggered the ICMP flow is no longer in memory or hasn't been seen.

Now, when this happens, information extracted from the ICMP packet is shown as text, without hyperlinks to the flow

![image](https://user-images.githubusercontent.com/3397663/53484370-feb65600-3a83-11e9-9ba2-65124215bedf.png)

Additional details have also been added to the flows list page so now also the protocol and the port are displayed along with the unreachable message



![image](https://user-images.githubusercontent.com/3397663/53484326-dfb7c400-3a83-11e9-8e96-7a4b89b449e2.png)
