### ISSUE TITLE
Error update 

### ISSUE THREAD

**Issue by inetactief** [ntop/ntopng#2418]
[root@ntopng ~]# yum update
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirror.transip.nl
 * epel: ftp.nluug.nl
 * extras: ftp.nluug.nl
 * updates: centos.mirror.triple-it.nl
Resolving Dependencies
--> Running transaction check
---> Package ntopng.x86_64 0:3.9.190222-5894 will be updated
---> Package ntopng.x86_64 0:3.9.190222-5913 will be an update
---> Package ntopng-data.noarch 0:3.9.190222-5894 will be updated
---> Package ntopng-data.noarch 0:3.9.190222-5913 will be an update
---> Package pfring.x86_64 0:7.5.0-2422 will be updated
--> Processing Dependency: pfring = 7.5.0-2422 for package: nprobe-8.7.190222-6390.x86_64
---> Package pfring.x86_64 0:7.5.0-2426 will be an update
--> Finished Dependency Resolution
Error: Package: nprobe-8.7.190222-6390.x86_64 (@ntop)
           Requires: pfring = 7.5.0-2422
           Removing: pfring-7.5.0-2422.x86_64 (@ntop)
               pfring = 7.5.0-2422
           Updated By: pfring-7.5.0-2426.x86_64 (ntop)
               pfring = 7.5.0-2426
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

We try skip and rpm -Va --nofiles --nodigest and restart the server and try again..

**Comment by cardigliano** [comment]
@inetactief this is working for me, it could be you updated in the middle of a repo refresh, please try again, nprobe should require pfring 7.5.0-2427 now.

**Comment by inetactief** [comment]
great is works! Thanks..
