### ISSUE TITLE
NtopNG White Screen

### ISSUE THREAD

**Issue by jchrislemmer** [ntop/ntopng#242]
Hi there,

I have installed Ntopng using the yum repos you guys supplied. Everything was installed successfully. However, when I start Ntopng and log in, everything seems missing. See screenshots:

![ntopng-image-1](https://github-cloud.s3.amazonaws.com/assets/8370935/10565446/a3441d82-75d0-11e5-948e-7a146ff240fd.png)
![ntopng-image-2](https://github-cloud.s3.amazonaws.com/assets/8370935/10565447/a3457b78-75d0-11e5-9e6c-2f64c555e4ce.png)
![ntopng-image-3](https://github-cloud.s3.amazonaws.com/assets/8370935/10565448/a34600b6-75d0-11e5-8a23-56eb78a2fd4d.png)

My config:

[root@localhost ~]# cat /etc/ntopng/ntopng.conf
--local-networks="192.168.1.0/24,10.0.0.0/24"
--interface=eth1,eh0
--daemon
--community
--http-port=3000
-G=/var/tmp/ntopng.pid
--sticky-hosts=local
[root@localhost ~]#

Thanks
Chris

**Comment by jchrislemmer** [comment]
Tailing /var/log/messages:

Oct 18 19:47:56 localhost ntopng: [Lua.cpp:4359] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/second.lua][/usr/local/share/ntopng/scripts/lua/modules/graph_utils.lua:911: bad argument #2 to 'toint' (number expected, got nil)]

**Comment by lucaderi** [comment]
I think there is something wrong with your install. The error you reported does not match with the code. Can you please deinstall everything, do a yum/apt-get clean and start over. Then if not not working please report "ntopng --version"

**Comment by simonemainardi** [comment]
@jchrislemmer lua error shown tells that you have an old dev version. Method `hasCommunities` has been removed with commit bc94680. Please update.
