### ISSUE TITLE
no data available in ntopng web interface 

### ISSUE THREAD

**Issue by ahlamm01** [ntop/ntopng#2421]
nprob:

--zmq="tcp://*:5556"
--collector-port=2055
-n=none
-i=none

nprobe and ntponng are installed on the same server (ubuntu 16.04)

the nrpobe receive the data from my firewall

I have this error with ntopng

#ntopng -i tcp://127.0.0.1:5556

WARNING: Unable to open store /var/lib/ntopng/12/alerts/alerts_v7.db
[AlertsManager.cpp:942] ERROR: Unable to prepare statement for query SELECT count(_) FROM closed_alerts . [AlertsManager.cpp:986] ERROR: Unable to prepare statement for query SELECT count(_) FROM flows_alerts .
[AlertsManager.cpp:942] ERROR: Unable to prepare statement for query SELECT count(*) FROM engaged_alerts WHERE alert_severity=2.
[Ntop.cpp:1996] Registered interface tcp://127.0.0.1:5556 [If Idx: 3] [id: 13]
[Ntop.cpp:1996] Registered interface tcp://127.0.0.1:5556 [If Idx: 4] [id: 14]

nprobe version is  v.8.6.190219 
ntopng version is v.3.8.190219  

any idea please

thank you in advance

**Comment by emanuele-f** [comment]
Can you post a screenshot of your network interface page into ntopng? https://www.ntop.org/guides/ntopng/web_gui/interfaces.html#interfaces

**Comment by ahlamm01** [comment]
this is the screenshot of my network interface
![interfaces](https://user-images.githubusercontent.com/47977190/53345867-29829c00-3916-11e9-8a19-c06d6edd9227.JPG)

**Comment by emanuele-f** [comment]
You have enabled interface disaggregation (https://www.ntop.org/guides/ntopng/advanced_features/dynamic_interfaces_disaggregation.html). You should select one of the *sub*-interfaces in the dropdown above to see the data. If you want to merge together different interfaces you need to use the *view interfaces*, please check out https://www.ntop.org/guides/ntopng/advanced_features/view_interfaces.html#physical-interfaces-aggregation-interface-views for details

**Comment by ahlamm01** [comment]
thank you :)

**Comment by emanuele-f** [comment]
You are welcome
