### ISSUE TITLE
ntopng -> ELK (more than basic flows_

### ISSUE THREAD

**Issue by jpbourke** [ntop/ntopng#2427]
Is there a way to get ntopng to send richer flow information to ELK, such as re transmissions ?

**Comment by emanuele-f** [comment]
Exported flow information is filled in by `Flow::flow2json` https://github.com/ntop/ntopng/blob/dev/src/Flow.cpp#L2041 . Adding retransmissions and other information is quite trivial (see `tcp_stats_s2d.pktRetr`) however there is the need to avoid inserting too much information into the flow json

**Comment by simonemainardi** [comment]
please, consider using nProbe if you want 100% fully-customizable information to ELK. With nProbe, you have a configurable template (-T) in which you can specify all the fields you want. nProbe will automatically push them to ELK.
