### ISSUE TITLE
cannot see hosts and other tabs

### ISSUE THREAD

**Issue by list-group** [ntop/ntopng#243]
I have installed ntopng Professional v.2.0.150918 on windows 2008 R2, and it seems to work and capture data, but there are many tabs without any data. Starting from the dashboard (I cannot see Top Local Talkers, and Remote Destinations), to hosts tab, local host mac addresses, and so on).
Flows tab is woking, but after a while I'm not able anymore to see Actual thpt (always 0 bps on all rows).

Can you help me to understand what's going wrong ?
thanks, Giovanni

**Comment by list-group** [comment]
Just an update: after restart of the ntopng service from windows services, now I'm able to see some tabs.
Still not working: Top Local Talkers, Mac addresses, Operating Systems, HTTP servers, Top hosts, Local host matrix.  The configuration of ntopng is the default, listening only on one interface. The port where the ntop is sniffing is a SPAN port in native configuration.

**Comment by list-group** [comment]
The ntopng version for windows is not working. After some time (variable from minutes to tens of minutes) the software stops collecting all informations and displaying them to browser.
In this case the only solution to dump again is service restart.
Anyway even after restart, some informations are not displayed as by previous comments.
In this way the application is unusable.

Can you fix it ?
Thanks, Giovanni

**Comment by lucaderi** [comment]
@list-group Giovanni you need to upgrade as you are using an old software version.

**Comment by lucaderi** [comment]
See https://github.com/ntop/ntopng/issues/194

**Comment by list-group** [comment]
I’m not able to find professional version on the ntop website.

Only community edition is available. Can you send me a link?

**Comment by list-group** [comment]
Is there any problem with registering of professional license ?
If I try to do upgrade to professional version, the license is not accepted anymore.
The software always presents to me 2.0.1510015 - Community Edition (there is also one more 0 in version numbering).

**Comment by lucaderi** [comment]
Please use this http://packages.ntop.org/Windows/ntopng-2.0.151019-x64.zip and it will work.

**Comment by list-group** [comment]
Now license is ok and I see professional menu, but I still have problems with some data on dashboard.
In particular : no data is present for Top Local Talkers, Network Interfaces: Realtime Traffic, and  Last Day View.

**Comment by simonemainardi** [comment]
Can't reproduce. It looks like a front-end (javascript or browser) issue. Please, right-click on the missing elements and select "Inspect Element" from the dropdown menu. Paste here any useful information that you may see, especially errors. If you can't find "Inspect Element", try to use chrome or firefox with firebug installed.

**Comment by list-group** [comment]
Hi, this under is the view with browser Chrome (Version 46.0.2490.71 m):

 



 

And the “inspect element” returns the following :

 



 



 

 

The same result using Firefox 41.0.1 :

 



 

 



 

 

 

While the following is the result using IE9 

 



 

 

Thanks, Giovanni

**Comment by lucaderi** [comment]
@list-group No picture has been attached to your email.

**Comment by list-group** [comment]
Sorry. Pls find attached.

**Comment by lucaderi** [comment]
@list-group If you go to https://github.com/ntop/ntopng/issues/243 you will see that nothing was sent

**Comment by list-group** [comment]
![chrmoe error](https://cloud.githubusercontent.com/assets/15193918/10608057/9c704cb0-773d-11e5-8733-27ea82c8a88c.jpg)
![chrmoe inspect](https://cloud.githubusercontent.com/assets/15193918/10608054/9c6e2124-773d-11e5-9404-1e195deb3b12.jpg)
![chrome](https://cloud.githubusercontent.com/assets/15193918/10608059/9c71c4fa-773d-11e5-8aca-de6b2623777f.jpg)
![firefox error](https://cloud.githubusercontent.com/assets/15193918/10608056/9c7035c2-773d-11e5-8a1b-5a28c905ed07.jpg)
![firefox](https://cloud.githubusercontent.com/assets/15193918/10608055/9c6f641c-773d-11e5-9a81-86ba410ab0e5.jpg)
![ie9](https://cloud.githubusercontent.com/assets/15193918/10608058/9c70c03c-773d-11e5-8bf1-072e7f5cd8ce.jpg)

**Comment by lucaderi** [comment]
@list-group Can you please send @simonemainardi your email address for contacting you offline?

**Comment by simonemainardi** [comment]
@list-group we should try and set up remote-assistance for this issue. Please, contact me privately at mainardi ntop org

**Comment by lucaderi** [comment]
Apparently you have an RRD file that is corrupted and thus the problem. We have hardened the RRD data extraction so that such RRD should be listed in the console log (or system event log) so that you can delete it (ntop will rebuild it). Please get the new ntopng build that contains the fix (it is currently being uploaded) and report.
