### ISSUE TITLE
ERROR HTTP accept_new_connection IP% is not allowed to connect

### ISSUE THREAD

**Issue by inghau** [ntop/ntopng#2430]
Hi, 

I just update my ubuntu box to 18.04 but find the ntopng is broken.
After trying to remove and reinstall many times i still bounce to the same issue. 
I've try googling for similiar problem but cant find it. 
also tried 
https://www.ntop.org/guides/ntopng/faq.html 

If anyone know something please let me know. 

Thanks

Feb 28 17:11:52 ntop systemd[1]: Started n2n edge process, on *.
Feb 28 17:11:52 ntop edge[29865]: 28/Feb/2019 17:11:52 [edge.c:413] WARNING: Config file /etc/n2n/edge-\x2a.conf not found
Feb 28 17:11:52 ntop edge[29865]: Welcome to n2n v.2.5.0 for Debian buster/sid
Feb 28 17:11:52 ntop edge[29865]: Built on Feb 28 2019 03:41:53
Feb 28 17:11:52 ntop edge[29865]: Copyright 2007-18 - ntop.org and contributors
Feb 28 17:11:52 ntop edge[29865]: edge <config file> (see edge.conf)
Feb 28 17:11:52 ntop edge[29865]: or
Feb 28 17:11:52 ntop edge[29865]: edge -d <tun device> -a [static:|dhcp:]<tun IP address> -c <community> [-k <encrypt key> | -K <key file>]
Feb 28 17:11:52 ntop edge[29865]:     [-s <netmask>] [-u <uid> -g <gid>][-f][-m <MAC address>] -l <supernode host:port>
Feb 28 17:11:52 ntop edge[29865]:     [-p <local port>] [-M <mtu>] [-r] [-E] [-v] [-t <mgmt port>] [-b] [-A] [-h]
Feb 28 17:11:52 ntop edge[29865]: -d <tun device>          | tun device name
Feb 28 17:11:52 ntop edge[29865]: -a <mode:address>        | Set interface address. For DHCP use '-r -a dhcp:0.0.0.0'
Feb 28 17:11:52 ntop edge[29865]: -c <community>           | n2n community name the edge belongs to.
Feb 28 17:11:52 ntop edge[29865]: -k <encrypt key>         | Encryption key (ASCII) - also N2N_KEY=<encrypt key>. Not with -K.
Feb 28 17:11:52 ntop edge[29865]: -K <key file>            | Specify a key schedule file to load. Not with -k.
Feb 28 17:11:52 ntop edge[29865]: -s <netmask>             | Edge interface netmask in dotted decimal notation (255.255.255.0).
Feb 28 17:11:52 ntop edge[29865]: -l <supernode host:port> | Supernode IP:port
Feb 28 17:11:52 ntop edge[29865]: -b                       | Periodically resolve supernode IP
Feb 28 17:11:52 ntop edge[29865]:                          | (when supernodes are running on dynamic IPs)
Feb 28 17:11:52 ntop edge[29865]: -p <local port>          | Fixed local UDP port.
Feb 28 17:11:52 ntop edge[29865]: -u <UID>                 | User ID (numeric) to use when privileges are dropped.
Feb 28 17:11:52 ntop edge[29865]: -g <GID>                 | Group ID (numeric) to use when privileges are dropped.
Feb 28 17:11:52 ntop edge[29865]: -f                       | Do not fork and run as a daemon; rather run in foreground.
Feb 28 17:11:52 ntop edge[29865]: -m <MAC address>         | Fix MAC address for the TAP interface (otherwise it may be random)
Feb 28 17:11:52 ntop edge[29865]:                          | eg. -m 01:02:03:04:05:06
Feb 28 17:11:52 ntop edge[29865]: -M <mtu>                 | Specify n2n MTU of edge interface (default 1400).
Feb 28 17:11:52 ntop edge[29865]: -r                       | Enable packet forwarding through n2n community.
Feb 28 17:11:52 ntop edge[29865]: -A                       | Set AES CBC as the preferred encryption mode.
Feb 28 17:11:52 ntop edge[29865]: -E                       | Accept multicast MAC addresses (default=drop).
Feb 28 17:11:52 ntop edge[29865]: -v                       | Make more verbose. Repeat as required.
Feb 28 17:11:52 ntop edge[29865]: -t <port>                | Management UDP Port (for multiple edges on a machine).
Feb 28 17:11:52 ntop edge[29865]: Environment variables:
Feb 28 17:11:52 ntop edge[29865]:   N2N_KEY                | Encryption key (ASCII). Not with -K or -k.
Feb 28 17:11:52 ntop systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
Feb 28 17:11:52 ntop systemd[1]: Started ntopng high-speed web-based traffic monitoring and analysis tool.
Feb 28 17:11:52 ntop ntopng[29889]: 28/Feb/2019 17:11:52 [Prefs.cpp:1148] All HTTP user login disabled
Feb 28 17:11:52 ntop ntopng[29889]: 28/Feb/2019 17:11:52 [Ntop.cpp:1920] Setting local networks to 10.20.200.0/24,10.20.202.0/24
Feb 28 17:11:52 ntop ntopng[29889]: 28/Feb/2019 17:11:52 [Redis.cpp:152] Successfully connected to redis 127.0.0.1:6379@0
Feb 28 17:11:52 ntop ntopng[29889]: 28/Feb/2019 17:11:52 [Redis.cpp:152] Successfully connected to redis 127.0.0.1:6379@0
Feb 28 17:11:52 ntop ntopng[29889]: 28/Feb/2019 17:11:52 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.7.5.0 interface ens192...
Feb 28 17:11:52 ntop ntopng[29889]: 28/Feb/2019 17:11:52 [Ntop.cpp:2012] Registered interface ens192 [id: 3]
Feb 28 17:11:52 ntop ntopng[29889]: 28/Feb/2019 17:11:52 [main.cpp:302] PID stored in file /var/run/ntopng.pid
Feb 28 17:11:52 ntop kernel: [ 9517.651467] device ens192 entered promiscuous mode
Feb 28 17:11:52 ntop ntopng[29889]: 28/Feb/2019 17:11:52 [HTTPserver.cpp:1126] Access Control List set to: +0.0.0.0/0,-10.0.0.0/8
Feb 28 17:11:52 ntop ntopng[29889]: 28/Feb/2019 17:11:52 [HTTPserver.cpp:1322] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
Feb 28 17:11:52 ntop ntopng[29889]: 28/Feb/2019 17:11:52 [HTTPserver.cpp:1325] HTTP server listening on 10.20.200.16:3000
Feb 28 17:11:52 ntop ntopng[29889]: 28/Feb/2019 17:11:52 [main.cpp:377] Working directory: /var/tmp/ntopng
Feb 28 17:11:52 ntop ntopng[29889]: 28/Feb/2019 17:11:52 [main.cpp:379] Scripts/HTML pages directory: /usr/share/ntopng
Feb 28 17:11:52 ntop ntopng[29889]: 28/Feb/2019 17:11:52 [Ntop.cpp:392] Welcome to ntopng x86_64 v.3.9.190228 - (C) 1998-19 ntop.org
Feb 28 17:11:52 ntop ntopng[29889]: 28/Feb/2019 17:11:52 [Ntop.cpp:402] Built on Ubuntu 18.04.1 LTS
Feb 28 17:11:52 ntop ntopng[29889]: 28/Feb/2019 17:11:52 [Ntop.cpp:751] Adding fe80::20c:29ff:fe0f:95e8/128 as IPv6 interface address for ens192
Feb 28 17:11:52 ntop ntopng[29889]: 28/Feb/2019 17:11:52 [Ntop.cpp:760] Adding fe80::20c:29ff:fe0f:95e8/64 as IPv6 local network for ens192
Feb 28 17:11:52 ntop ntopng[29889]: 28/Feb/2019 17:11:52 [PeriodicActivities.cpp:72] Started periodic activities loop...
Feb 28 17:11:54 ntop ntopng[29889]: 28/Feb/2019 17:11:54 [PeriodicActivities.cpp:113] Each periodic activity script will use 2 threads
Feb 28 17:11:54 ntop ntopng[29889]: 28/Feb/2019 17:11:54 [NetworkInterface.cpp:2611] Started packet polling on interface ens192 [id: 3]...
**### Feb 28 17:12:04 ntop ntopng: [HTTPserver.cpp:1060] ERROR: [HTTP] accept_new_connection: 10.20.202.128 is not allowed to connect
Feb 28 17:12:04 ntop ntopng[29889]: 28/Feb/2019 17:12:04 [HTTPserver.cpp:1060] ERROR: [HTTP] accept_new_connection: 10.20.202.128 is not allowed to connect
Feb 28 17:12:04 ntop ntopng: [HTTPserver.cpp:1060] ERROR: [HTTP] accept_new_connection: 10.20.202.128 is not allowed to connect
Feb 28 17:12:04 ntop ntopng[29889]: 28/Feb/2019 17:12:04 [HTTPserver.cpp:1060] ERROR: [HTTP] accept_new_connection: 10.20.202.128 is not allowed to connect
Feb 28 17:12:12 ntop ntopng: [HTTPserver.cpp:1060] ERROR: [HTTP] accept_new_connection: 10.20.202.128 is not allowed to connect
Feb 28 17:12:12 ntop ntopng[29889]: 28/Feb/2019 17:12:12 [HTTPserver.cpp:1060] ERROR: [HTTP] accept_new_connection: 10.20.202.128 is not allowed to connect
Feb 28 17:12:12 ntop ntopng: [HTTPserver.cpp:1060] ERROR: [HTTP] accept_new_connection: 10.20.202.128 is not allowed to connect
Feb 28 17:12:12 ntop ntopng[29889]: 28/Feb/2019 17:12:12 [HTTPserver.cpp:1060] ERROR: [HTTP] accept_new_connection: 10.20.202.128 is not allowed to connect**

root@ntop:/etc/ntopng# cat ntopng.conf
-G=/var/run/ntopng.pid
--dont-change-user
--community
-m="10.20.200.0/24,10.20.202.0/24"
##Specifies  the  network  interface or collector endpoint to be used by ntopng for network monitoring.
-i=ens192
-l=1
##Sets the HTTP port of the embedded web server.
-w=10.20.200.16:3000
root@ntop:/etc/ntopng# 

here is from my workstation try to curl
$ curl -v 10.20.200.16:3000
* Rebuilt URL to: 10.20.200.16:3000/
*   Trying 10.20.200.16...
* TCP_NODELAY set
* Connected to 10.20.200.16 (10.20.200.16) port 3000 (#0)
> GET / HTTP/1.1
> Host: 10.20.200.16:3000
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Recv failure: Connection reset by peer
* stopped the pause stream!
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer

**Comment by simonemainardi** [comment]
You have an access control list set

```
Feb 28 17:11:52 ntop ntopng[29889]: 28/Feb/2019 17:11:52 [HTTPserver.cpp:1126] Access Control List set to: +0.0.0.0/0,-10.0.0.0/8
```

So it is normal that IPs from 10.x/8 can't connect.

Visit this page and make the necessary changes:

![image](https://user-images.githubusercontent.com/3397663/53580792-aa42d180-3b7c-11e9-9706-e6435242f9de.png)

**Comment by inghau** [comment]
Can you teach me how to access the access control list ? 
i cant access the whole web interface.

**Comment by emanuele-f** [comment]
You should be able to connect to port 3000 via a web browser, please checkout https://www.ntop.org/guides/ntopng/web_gui/index.html

**Comment by inghau** [comment]
no i cant that is why i start this thread...
Anyway i found a way to get into @simonemainardi directly using the redis-cli

root@ntop:/usr/share# redis-cli
127.0.0.1:6379> mget ntopng.prefs.http_acl_management_port
1) "+0.0.0.0/0,-10.0.0.0/8"
127.0.0.1:6379> mset ntopng.prefs.http_acl_management_port "+10.0.0.0/8"
OK
127.0.0.1:6379> mget ntopng.prefs.http_acl_management_port
1) "+10.0.0.0/8"
127.0.0.1:6379> 

After restart the service i can connect to the web port now.. 
Thanks folks
