### ISSUE TITLE
[Suggestion] OpenStreetMaps support

### ISSUE THREAD

**Issue by Astaoth** [ntop/ntopng#2433]
Hey,

I'm currently trying NTopNG, and I would like to use the GeoMap, but it requires a Google Maps API key.
Since Openstreetmaps has the same kind of API, I was wondering if you will support OSM as well in the future or if you rather plan to stay with Google Maps ?

Regards,
Astaoth

**Comment by simonemainardi** [comment]
Currently we are focusing on other developments and we are unable to accomodate this feature request. Anyway, if you would like to contribute, we would be glad to consider the inclusion of a Pull Request.
