### ISSUE TITLE
Webhook to Rocket Chat

### ISSUE THREAD

**Issue by Famku** [ntop/ntopng#2436]
Hi,

I was able to create a webhook to Rocket Chat but just receive empty messages.

Someone who can explain how to configure this?

**Comment by emanuele-f** [comment]
Hi, do you mean a webhook to receive the ntopng alerts? Please provide information and some code to read

**Comment by Famku** [comment]
Yes, to receive ntopng alerts

ntopng preferences:

![2](https://user-images.githubusercontent.com/27890413/53701664-b25e7380-3dff-11e9-8b24-ac146188825d.JPG)

Rocket Chat - incoming Webhook:

![1](https://user-images.githubusercontent.com/27890413/53701671-bee2cc00-3dff-11e9-9572-b14c01aee078.JPG)

Chat output:

![3](https://user-images.githubusercontent.com/27890413/53701687-df128b00-3dff-11e9-91bf-ce910ab22317.JPG)

**Comment by Famku** [comment]
closed by mistake

**Comment by emanuele-f** [comment]
here you can find an example of message json https://www.ntop.org/guides/ntopng/web_gui/alerts.html?highlight=webhook . Can you debug with the console.log above the incoming message contents?

**Comment by Famku** [comment]
I can see the alerts in the log, but not in the chat

For now I will use Slack

Thank you
