### ISSUE TITLE
ntopng classifying valid flows as Unknown when out_bytes are 0

### ISSUE THREAD

**Issue by vijaykilledar** [ntop/ntopng#2438]
I created pcap with different traffic (facebook, google, twitter, amazon) and ran pcap through ntopng and mysql dump feature.
I converted mysql flows into csv and csv to json using python 
In most of the valid target ip flows (facebook, google ) ntopng is classifying it as UNKNOWN app.
Common attribute in these flows is out_byte value is zero 
attached screenshot of the flows.
![deepinscreenshot_select-area_20190304170910](https://user-images.githubusercontent.com/35503935/53733178-33704600-3ea6-11e9-8e16-a722ae3426e0.png)

**Comment by vijaykilledar** [comment]
Build info
v.3.9.190227	[Enterprise/Professional build]
GIT rev:	dev:63b15acf8394c05549320f53d4a6f0d608f92bcb:20190227
Pro rev:	r2266
Built on:	Ubuntu 18.04.1 LTS
System Id:	D6AF3C6B9205A1D6
Platform:	x86_64
Edition:	Enterprise
License Type:	Time-Limited
Validity:	Until Mon Mar  4 18:06:18 2019

**Comment by simonemainardi** [comment]
please, enclose the pcap and the ntopng configuration used

**Comment by vijaykilledar** [comment]
pcap file is too big and github allowing only 10MB please generate yourself with facebook and google and other normal web traffic traffic. 

[ntopng_conf.zip](https://github.com/ntop/ntopng/files/2929734/ntopng_conf.zip)
command used to generate mysql 
sudo ntopng -w 8990 -i ./pcap_file.pcap  -F  "mysql;localhost;db_name;flows;root;password"

**Comment by emanuele-f** [comment]
@vijaykilledar can you still reproduce this with the latest version? Pcap file is really helpful in this case, please consider uploading it on a third party server and sending us a link, sending it to me at faranda@ntop.org or trimming it via wireshark

**Comment by simonemainardi** [comment]
I have fixed it in the latest build. Now, even mono-directional single-packet flows are correctly detected (and exported) with their protocol.

Attached is the pcap to reproduce.

[one_way_tcp_small.pcap.zip](https://github.com/ntop/ntopng/files/3048961/one_way_tcp_small.pcap.zip)


![image](https://user-images.githubusercontent.com/3397663/55644896-7a1fcb80-57d7-11e9-9fc5-2a83a99db70b.png)

```
sudo ./ntopng -i ../one_way_tcp_small.pcap -F "mysql;localhost;ntopng;flows;root;root"
```

```
MariaDB [ntopng]> select L7_PROTO from flowsv4;
+----------+
| L7_PROTO |
+----------+
|      126 |
|      126 |
|      142 |
|      119 |
+----------+
```
