### ISSUE TITLE
ntopng classifying 8.8.8.8 DNS query flows based on IP address in DNS query packet.

### ISSUE THREAD

**Issue by vijaykilledar** [ntop/ntopng#2439]
#2438 ran test mentioned in this defect. and check 8.8.8.8 ip flows you will see these flows are classified based on IP address in dns query packet though 8.8.8.8 is google's public ip address. 
see blow image.
![1112deepinscreenshot_select-area_20190304173510](https://user-images.githubusercontent.com/35503935/53733644-9f9f7980-3ea7-11e9-9eb6-5c7d405f2a5b.png)

**Comment by vijaykilledar** [comment]
Build info

v.3.9.190227	[Enterprise/Professional build]
GIT rev:	dev:63b15acf8394c05549320f53d4a6f0d608f92bcb:20190227
Pro rev:	r2266
Built on:	Ubuntu 18.04.1 LTS
System Id:	D6AF3C6B9205A1D6
Platform:	x86_64
Edition:	Enterprise
License Type:	Time-Limited
Validity:	Until Mon Mar  4 18:06:18 2019

**Comment by simonemainardi** [comment]
This is expected behavior. DNS is only functional to the service which is actually Google, Facebook, etc. in your example. However, we may report `DNS.<Application>` in a future release.
