### ISSUE TITLE
how can i dpi the SSL and support encrypted connections to get the true protocol

### ISSUE THREAD

**Issue by jiangdu8888** [ntop/ntopng#2440]

**Comment by jiangdu8888** [comment]
Thinks！

**Comment by simonemainardi** [comment]
ntopng doesn't support SSL decryption. However, it's able, via nDPI, to detect the application protocol using a combination of the certificate CN extracted during the initial SSL handshake plus the IP addresses of the conversation. This technique is effective to detect encrypted conversations, eg., Google, Facebook, etc. For example, if ntopng reads '*.facebook.com' in the certificate CN, it can say the conversation is 'Facebook'.

**Comment by jiangdu8888** [comment]
> ntopng不支持SSL解密。但是，它可以通过nDPI使用在初始SSL握手期间提取的证书CN和会话的IP地址的组合来检测应用程序协议。该技术对于检测加密的对话是有效的，例如Google，Facebook等。例如，如果ntopng在证书CN中读取“* .facebook.com”，则可以说对话是“Facebook”。



> ntopng doesn't support SSL decryption. However, it's able, via nDPI, to detect the application protocol using a combination of the certificate CN extracted during the initial SSL handshake plus the IP addresses of the conversation. This technique is effective to detect encrypted conversations, eg., Google, Facebook, etc. For example, if ntopng reads '*.facebook.com' in the certificate CN, it can say the conversation is 'Facebook'.



> ntopng doesn't support SSL decryption. However, it's able, via nDPI, to detect the application protocol using a combination of the certificate CN extracted during the initial SSL handshake plus the IP addresses of the conversation. This technique is effective to detect encrypted conversations, eg., Google, Facebook, etc. For example, if ntopng reads '*.facebook.com' in the certificate CN, it can say the conversation is 'Facebook'.

yes i saw that in ndPI. So is it already open in ntopng? Or how do I set it up? And Do I need to install any software or certificates?

**Comment by simonemainardi** [comment]
it's already in ntopng
