### ISSUE TITLE
modified magic number raises Bus-Error withs tools fritzdump.sh

### ISSUE THREAD

**Issue by MasterPlexus** [ntop/ntopng#2443]
I want to use traffic mnitorin of my fritzbox using the internet capture. Unfortunatly any other parameter then IFACE="2-1" raises an Bus error like the following:
```
./fritzdump.sh: line 49: 15430 Exit 3                  wget --no-check-certificate -qO- $FRITZIP/cgi-bin/capture_notimeout?ifaceorminor=$IFACE\&snaplen=1600\&capture=Start\&sid=$SID
     15431 Bus error               | ntopng -i -
```
I've tested some like "1-lan", "2-1" and "3-17", but all of them raises the bus error. but "2-1" works (but brings not really the complete picture as it is just the routing capture).

So I don't know what I can do at the moment. Maybe with some advice I could produce some further verbose logs to see where the problem could be (maybe the format of the capture is slightly in a other way for other IFACE parameters...

Thanks for any help!

**Comment by simonemainardi** [comment]
did you go through https://github.com/ntop/ntopng/blob/dev/doc/README.fritzbox ?

**Comment by MasterPlexus** [comment]
@simonemainardi, yes, I did and with the standard IFACE parameter it works, but with no other as I described.

**Comment by simonemainardi** [comment]
use and password created as described in https://github.com/ntop/ntopng/blob/dev/tools/fritzdump.sh ?

**Comment by emanuele-f** [comment]
In my experience (with mikrotic) such errors are related to the device operating system/drivers, maybe you can try to update your device firmware

**Comment by MasterPlexus** [comment]
@simonemainardi , Yes, indeed. maintained a User with a passphrase. And as I said, with 2-0 it worked, but with others I get the bus error.

@emanuele-f , I have an Autoupdate activated for my Fritzdos, and be on the newest firmware.

**Comment by MasterPlexus** [comment]
So now I recompiledthe ndip and ntopng completley and retry. I've included the -v in the script, and see the following direct bevore the Bus-error:
`06/Mar/2019 08:02:10 [LuaEngine.cpp:3795] ntop_get_ndpi_protocols() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:378] getCurrentInterface() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:3817] ntop_get_ndpi_categories() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:5542] ntop_is_nedge() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:4837] ntop_http_purify_param() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:4837] ntop_http_purify_param() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:6028] ntop_get_dirs() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:7090] ntop_get_redis() called
06/Mar/2019 08:02:10 [HTTPserver.cpp:1012] [HTTP] /lua/get_mac_data.lua [/usr/local/share/ntopng/scripts/lua/get_mac_data.lua]
06/Mar/2019 08:02:10 [LuaEngine.cpp:8859] Interface found [Interface: stdin][user: admin]
06/Mar/2019 08:02:10 [Utils.cpp:2704] Rule 0.0.0.0/0
06/Mar/2019 08:02:10 [Utils.cpp:2704] Rule ::/0
06/Mar/2019 08:02:10 [LuaEngine.cpp:6087] ntop_get_info() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:6028] ntop_get_dirs() called
06/Mar/2019 08:02:10 [ThreadedActivity.cpp:161] Running /usr/local/share/ntopng/scripts/callbacks/system/second.lua (iface=(nil))
06/Mar/2019 08:02:10 [LuaEngine.cpp:1544] ntop_get_file_dir_exists() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:6186] ntop_get_cookie_attributes() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:6028] ntop_get_dirs() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:1544] ntop_get_file_dir_exists() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:6028] ntop_get_dirs() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:1544] ntop_get_file_dir_exists() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:6028] ntop_get_dirs() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:6028] ntop_get_dirs() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:1544] ntop_get_file_dir_exists() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:389] ntop_select_interface() called
06/Mar/2019 08:02:10 [NetworkInterface.cpp:2589] Going to reload categories [iface: stdin]
06/Mar/2019 08:02:10 [LuaEngine.cpp:1626] ntop_is_windows() called
06/Mar/2019 08:02:10 [Ntop.cpp:1035] No allowed interface found for stdin
06/Mar/2019 08:02:10 [LuaEngine.cpp:389] ntop_select_interface() called
06/Mar/2019 08:02:10 [Ntop.cpp:1035] No allowed interface found for stdin
06/Mar/2019 08:02:10 [NetworkInterface.cpp:5037] Purging idle flows [ifname: stdin] [ifid: 10] [current size: 1]
06/Mar/2019 08:02:10 [LuaEngine.cpp:6028] ntop_get_dirs() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:378] getCurrentInterface() called
06/Mar/2019 08:02:10 [NetworkInterface.cpp:5037] Purging idle flows [ifname: stdin] [ifid: 10] [current size: 2]
06/Mar/2019 08:02:10 [LuaEngine.cpp:319] ntop_get_interface_names() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:333] Returning name [0][stdin]
06/Mar/2019 08:02:10 [LuaEngine.cpp:1626] ntop_is_windows() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:1389] ntop_is_shutdown() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:389] ntop_select_interface() called
06/Mar/2019 08:02:10 [Ntop.cpp:1035] No allowed interface found for stdin
06/Mar/2019 08:02:10 [LuaEngine.cpp:378] getCurrentInterface() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:5414] ntop_get_interface_stats() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:7090] ntop_get_redis() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:6028] ntop_get_dirs() called
06/Mar/2019 08:02:10 [LuaEngine.cpp:6087] ntop_get_info() called
./fritzdump.sh: line 49: 32037 Exit 3                  wget --no-check-certificate -qO- $FRITZIP/cgi-bin/capture_notimeout?ifaceorminor=$IFACE\&snaplen=1600\&capture=Start\&sid=$SID
     32038 Bus error               | ntopng -v 6 -i -`

So for me it looks like, that ntopng did not understand the provided data if I use a other IFACE then "2-0" 
`06/Mar/2019 08:02:10 [Ntop.cpp:1035] No allowed interface found for stdin`

Some Questions:
- is normally PF_RING needed for a correct working for analysing a complete pcap-stream?
- is there a check possible to identify what ntopng expectet, and what was delivered in the interface identification?
- other ideas ? ;)

Thanks

**Comment by simonemainardi** [comment]
cant' reproduce.

try and run ntopng from stdin using tcpdump on a local interface:

```
sudo tcpdump -i eno1 -s0 -w - | sudo ./ntopng -i
```

Do you stil get the bus error?

**Comment by MasterPlexus** [comment]
`sudo tcpdump -i eno1 -s0 -w - | sudo ntopng -i - `
brings
`tcpdump: eno1: No such device exists`

but 

`sudo tcpdump -i wlan0 -s0 -w - | sudo ntopng -i - `

works.

Bus error did not come in booth cases.

**Comment by MasterPlexus** [comment]
I've checked the dumped pcap-Files with whireshark. It tolds that the working 2-0 interface (which works) are 
`Format: Modified tcpdump - pcap
Encapsulation: Raw IP`

and the 3-17 interface (which not work) for example

`Format: Modified tcpdump - pcap
Encapsulation: Ethernet`

so the encapsulation seems to be a other kind. Is this understandable by ntpng?

**Comment by simonemainardi** [comment]
can you enclose such pcaps here so I can check?

**Comment by MasterPlexus** [comment]
[pcaps.zip](https://github.com/ntop/ntopng/files/2936711/pcaps.zip)

See attached.

**Comment by simonemainardi** [comment]
there was an issue with the datalink type for the Paw IP capture of 2-0 pcap file. Now the issue is solved but this doesn't explain why you are getting that bus error.

Can you try and `cat` the pcap files into ntopng? eg.,

```
cat ../2-0.pcap | sudo ./ntopng -i -
```

**Comment by MasterPlexus** [comment]
the command
`cat ./2-0.pcap | sudo ntopng -i -`
works

the command
`cat ./3-17.pcap | sudo ntopng -i -`
brings bus error ( (that's the second file in the zip)

**Comment by MasterPlexus** [comment]
I've made now a test on a windows-machine, and there the 3-17.pcap is usable with ntopng.  
`ntopng /c -i C:\Users\solar\Downloads\3-17.pcap`

So it looks like that there is a difference between the Linux self-compiled version and the downloadable win10x64 version. I must say I would like to have ntopng run under Linux then under windows, so I hope there will be a solution ;)

**Comment by simonemainardi** [comment]
ntopng MUST work under linux. Do you think you can provide me a remote access to the machine where you are running the fritzdump so I can see what happens and debug?

**Comment by simonemainardi** [comment]
by the way, first please make sure to try with the latest 3.9 version after my fix.

**Comment by MasterPlexus** [comment]
@simonemainardi , did you mean dev branch, or 3.9 (head is set to dev as far as I could see).

a remote access will not be possible at the moment, but if you advice, I can also get logs, dmesgand so on.

**Comment by MasterPlexus** [comment]
There is an interesting point, if I try to pipe the 3-17 stream to tshark:
`Capturing traffic on Fritz!Box interface 3-17 ...
tshark: The standard input contains record data that TShark doesn't support.
(pcap: that type of pcap file can't be read from a pipe)`

I found also a Webpage from whireshark, where they stated that piped pcap-streams could be a problem : [(https://wiki.wireshark.org/CaptureSetup/Pipes#Named_pipes)]

Could it be, that the libcap is not able to handle the pipe, and how could I check that ? My system shows me the following version (and a newer one I did not see in the repository):
`libcap-dev is already the newest version (1:2.25-1).`

**Comment by MasterPlexus** [comment]
Rebuild the actual dev branch. Just for completeness here the raised warnings during compilation (don't know if that is important):

```
src/Host.cpp: In member function 'void Host::dissectDropbox(const char*, u_int16_t)':
src/Host.cpp:1394:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for(u_int i=0; i<array_list_length(l); i++) {
       
src/NetworkInterface.cpp: In function 'bool flow_update_hosts_stats(GenericHashEntry*, void*, bool*)':
src/NetworkInterface.cpp:2789:48: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   bool dump_alert = ((time(NULL) - tv->tv_sec) < ntop->getPrefs()->get_housekeeping_frequency()) ? true : false;
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/NetworkInterface.cpp: In member function 'void NetworkInterface::periodicStatsUpdate()':
src/NetworkInterface.cpp:2988:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       (time(NULL) - tv.tv_sec) > ntop->getPrefs()->get_housekeeping_frequency())
       ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/NetworkInterface.cpp: In member function 'void NetworkInterface::deliverLiveCapture(const pcap_pkthdr*, const u_char*, Flow*)':
src/NetworkInterface.cpp:6940:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(c->live_capture.capture_until < h->ts.tv_sec || c->live_capture.stopped)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~   
          
```

```
src/HTTPserver.cpp: In function 'void redirect_to_login(mg_connection*, const mg_request_info*, const char*)':
src/HTTPserver.cpp:627:25: warning: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'size_t {aka unsigned int}' [-Wformat=]
               wispr_data);
                         ^   
```

```
In file included from src/HTTPserver.cpp:25:0:
src/../third-party/mongoose/mongoose.c: At global scope:
src/../third-party/mongoose/mongoose.c:4782:13: warning: 'void ssl_locking_callback(int, int, const char*, int)' defined but not used [-Wunused-function]
 static void ssl_locking_callback(int mode, int mutex_num, const char *file,
             ^~~~~~~~~~~~~~~~~~~~
src/../third-party/mongoose/mongoose.c:4778:22: warning: 'long unsigned int ssl_id_callback()' defined but not used [-Wunused-function]
 static unsigned long ssl_id_callback(void) {
                      ^~~~~~~~~~~~~~~ 
```

```
src/LuaEngine.cpp: In function 'void* pcapDumpLoop(void*)':
src/LuaEngine.cpp:4205:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(h->ts.tv_sec > c->pkt_capture.end_capture)
          ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/LuaEngine.cpp:4210:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(time(NULL) > c->pkt_capture.end_capture)
          ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~  

```
```
/usr/bin/ld: warning: libssl.so.1.0.2, needed by /usr/lib/arm-linux-gnueabihf/libcurl.so, may conflict with libssl.so.1.1
/usr/bin/ld: warning: libssl.so.1.0.2, needed by /usr/lib/arm-linux-gnueabihf/libcurl.so, may conflict with libssl.so.1.1
/usr/bin/ld: warning: libcrypto.so.1.0.2, needed by /usr/lib/arm-linux-gnueabihf/libcurl.so, may conflict with libcrypto.so.1.1 

```
After building, retry the interface 3-17, but the result was the same: Bus error.

**Comment by simonemainardi** [comment]
Thanks for pointing this out: `The standard input contains record data that TShark doesn't support. (pcap: that type of pcap file can't be read from a pipe)`.

As it can also be seen from the wireshark sources, the incoming file has a modified magic number. This kind of pcaps cannot be read from pipes but only from files (source https://github.com/wireshark/wireshark/blob/master/wiretap/libpcap.c#L360):

> 	 * But don't do that if the input is a pipe; that would mean the
	 * open won't complete until two packets have been written to
	 * the pipe, unless the pipe is closed after one packet has
	 * been written, so a program reading from the file won't see
	 * the first packet until the second packet has been written.

Full explanation at: https://github.com/wireshark/wireshark/blob/d5dc30fa00c0eeaa81c7bbb07b0adf7e82be5220/wiretap/libpcap.c#L360

The modified magic number is what causes the `that type of pcap file can't be read from a pipe`. Indeed, it's technically not possible to read such kind of pcaps from pipes as explained above.

Specifically, the magic number of your pcap has the magic number `a1b2cd34` rather than `a1b2c3d4`, so the two nibbles of the two lower-order bytes swapped in a strange way that can't be used neither by wireshark nor by ntopng when reading from a pipe.

```
(base) 000:pcaps (1) simone$ hexdump 3-17.pcap | head
0000000 a1 b2 cd 34 00 02 00 04 00 00 00 00 00 00 00 00
```

So at this point I would suggest you to follow up with AVM to sort this out.

**Comment by MasterPlexus** [comment]
@simonemainardi , just an additional question, after I read more and more stuff, and it looks like AVM is not willing to change the Dump-function:
could you think maybe about an additional feature, for example only activate able via command-line option, to put ntopng in a buffered-mode while collecting the pcap-data via pipe?
I'm stating that due to the explanation which was made on wireshark due to the late reconition of the second package:
```
* that would mean the
* open won't complete until two packets have been written to
* the pipe, unless the pipe is closed after one packet has
* been written, so a program reading from the file won't see
* the first packet until the second packet has been written
```
For me this sounds that everything could be fine, if the data/packages are not used online, but buffered (maybe wait for two packages, or a specific time - dunno what is possible, and reliable).

Hoping that question appears on your side, as the issue is marked as closed...

**Comment by simonemainardi** [comment]
Unfortunately we can't accomodate this request - I don't even have a fritzbox to do some experiments.
