### ISSUE TITLE
yes i saw that in ndPI. So is it already open in ntopng? Or how do I set it up? And Do I need to install any software or certificates?

### ISSUE THREAD

**Issue by jiangdu8888** [ntop/ntopng#2445]
> ntopng doesn't support SSL decryption. However, it's able, via nDPI, to detect the application protocol using a combination of the certificate CN extracted during the initial SSL handshake plus the IP addresses of the conversation. This technique is effective to detect encrypted conversations, eg., Google, Facebook, etc. For example, if ntopng reads '*.facebook.com' in the certificate CN, it can say the conversation is 'Facebook'.

> ntopng doesn't support SSL decryption. However, it's able, via nDPI, to detect the application protocol using a combination of the certificate CN extracted during the initial SSL handshake plus the IP addresses of the conversation. This technique is effective to detect encrypted conversations, eg., Google, Facebook, etc. For example, if ntopng reads '*.facebook.com' in the certificate CN, it can say the conversation is 'Facebook'.

yes i saw that in ndPI. So is it already open in ntopng? Or how do I set it up? And Do I need to install any software or certificates?

_Originally posted by @jiangdu8888 in https://github.com/ntop/ntopng/issues/2440#issuecomment-469603741_

**Comment by simonemainardi** [comment]
It's already in ntopng - provided that you are capturing from a physical interface.
