### ISSUE TITLE
How to calculate the the  95th by using InfluxDB?

### ISSUE THREAD

**Issue by jedi0605** [ntop/ntopng#2447]
Hi,
I got wrong 95th value (compare the UI 95th) by using InflusDB.
How could I get the same 95th value by using InflusDB?

**Comment by emanuele-f** [comment]
Please check out https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/timeseries/ts_common.lua

**Comment by jedi0605** [comment]
How could InfluxDB data translate to "total_serie"?
my row data.
![default](https://user-images.githubusercontent.com/5374440/53945966-bccd8580-40fd-11e9-87bb-0ae4c1db8803.PNG)

_ts_common.calculateStatistics(total_serie, step, tdiff, data_type)_

**Comment by emanuele-f** [comment]
You need to sum bytes_sent and bytes_rcvd together, then perform the derivative of the result. Check out https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/timeseries/drivers/influxdb.lua#L288 for an example (you can skip the `SUM("value")` part, just a `derivative(bytes_sent+bytes_rcvd)`.

**Comment by jedi0605** [comment]
My query is like
_SELECT  (bytes_sent + bytes_rcvd) AS "value" FROM "ntopng"."autogen"."host:traffic" WHERE time > now() - 2h AND "host"='202.168.199.201@1998' AND "ifid"='4'_
It's not only  sum bytes_sent and bytes_rcvd but also  subtraction two rows data right?
Like 
![default](https://user-images.githubusercontent.com/5374440/53948411-b4c41480-4102-11e9-9907-1d5c3bc7b597.PNG)

**Comment by emanuele-f** [comment]
yes, use `NON_NEGATIVE_DERIVATIVE`

**Comment by jedi0605** [comment]
I use this query 
> SELECT NON_NEGATIVE_DERIVATIVE(bytes_sent) , NON_NEGATIVE_DERIVATIVE(bytes_rcvd)  FROM "ntopng"."autogen"."host:traffic" WHERE host='202.168.199.194@1998' AND ifid='4' ANd time > now() - 1d

But total traffic (bytes_sent+bytes_rcvd) not same as Ntop UI "Total Traffic"

**Comment by emanuele-f** [comment]
Please check out https://github.com/ntop/ntopng/blob/dev/doc/README.beta_features on how to enable InfluxDB query log (only if you are compiling from git, otherwise manually uncomment the relevant line in https://github.com/ntop/ntopng/blob/8f5a6495a27f52fb818a851f13670fb127150dcb/scripts/lua/modules/timeseries/drivers/influxdb.lua#L168 to enable this)

**Comment by jedi0605** [comment]
Hi,
I want to know.
Does the InfluxDB have the Ip traffic source/destination information?
Thank you. Regards

Emanuele Faranda <notifications@github.com> 於 2019年3月27日 週三 下午6:26寫道：
