### ISSUE TITLE
how to use ntopng with geoip

### ISSUE THREAD

**Issue by maravento** [ntop/ntopng#2449]
In the past, the following files were downloaded:
```
http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
http://geolite.maxmind.com/download/geoip/database/GeoLiteCityv6-beta/GeoLiteCityv6.dat.gz 
http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum.dat.gz
http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNumv6.dat.gz
```
to the folder:
 `/usr/share/ntopng/httpdocs/geoip`
and unzip .dat.gz into this folder. But now, by default, are two files in this folder:
`GeoLite2-ASN.mmdb  GeoLite2-City.mmdb`
But now maxmind link change:
```
https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz
https://geolite.maxmind.com/download/geoip/database/GeoLite2-ASN.tar.gz
```
**Question**: Is it necessary to download these links to be used with ntopng, or is there another simpler method, or is it no longer necessary? (ntopng already includes geolocation databases?)

Thanks

**Comment by simonemainardi** [comment]
Maxmind has changed its databases and library and ntopng has been updated as well to keep this into account.

`GeoLite2-ASN.mmdb GeoLite2-City.mmdb` are the new file databases:

- if you are installing a packaged version of ntopng, those files will be pulled in automatically
- if you are building ntopng from sources, you can run `make geoip` to download them

Then, just place them under `httpdocs/geoip/` and ntopng will automatically pick them.

**Comment by maravento** [comment]
You say: "Then, just place them under httpdocs/geoip/ and ntopng will automatically pick them". 

**Question:** This action refers to "packaged version of ntopng" or "building ntopng from sources"?

You have not answered my second question: I repeat it again:
In the past, the following task was scheduled in cron to prevent ntopng causing out of disk space and inodes:
`@monthly /usr/bin/find /var/tmp/ntopng/*/top_talkers/* -mtime +60 -delete`
**Question:** Has this problem been fixed?

Thanks
