### ISSUE TITLE
Default admin/admin login password is a security concern

### ISSUE THREAD

**Issue by arenddeboer** [ntop/ntopng#2450]
I think it would be better if there was no default password set, but force the user to set the initial password in a configuration file after installing ntopng. 
Although I have myself to blame, I installed ntopng, but somehow did not get around to actually using it. Because I already had port mydomain.com:80|443 mapped to localhost:3000 for a node.js app (tcp port 3000 is a common port to run node.js apps on while letting nginx or apache proxy requests to this port). Ntopng became openly accessible after I disabled the node.js app listening on port 3000.  Anyone could have listened in on all my network traffic using the admin/admin default login.

I understand there is a tradeoff between easily getting started with ntopng and security, and this might sound like an edge case, but I still think it would be better to be on the safe side.

**Comment by simonemainardi** [comment]
ntopng, after the installation, forces you to change the default admin/admin user and password pair. You can't even continue to the UI without performing such change.

![image](https://user-images.githubusercontent.com/3397663/54017226-a10dc200-4185-11e9-9c24-f1af9770c047.png)

We believe this is already a good tradeoff between easily getting started with ntopng and security.
