### ISSUE TITLE
prevent ntopng causing out of disk space and inodes

### ISSUE THREAD

**Issue by maravento** [ntop/ntopng#2451]
In the past, the following task was scheduled in cron to prevent ntopng causing out of disk space and inodes ([source](https://serverfault.com/questions/625875/howto-prevent-ntopng-causing-out-of-disk-space-and-inodes)):

`@monthly /usr/bin/find /var/tmp/ntopng/*/top_talkers/* -mtime +60 -delete`

Has this problem been fixed? (and this task is no longer necessary?)

**Comment by simonemainardi** [comment]
top talkers are recycled automatically. that task is no longer necessary.
