### ISSUE TITLE
change for community/free version?

### ISSUE THREAD

**Issue by maravento** [ntop/ntopng#2455]
Install method:

```
wget http://apt.ntop.org/18.04/all/apt-ntop.deb
dpkg -i apt-ntop.deb
apt update -y
apt install pfring-dkms nprobe ntopng n2disk cento -y
```
There is contradiction in the information shown by the commands and the one shown by the web interface

Command line version:
```
ntopng --version
v.3.9.190311	[Enterprise/Professional build]
GIT rev:	dev:840313dd60620ded5492ae87be780c3461b5522d:20190311
Pro rev:	r2275
Built on:	Ubuntu 18.04.2 LTS
System Id:	[REMOVED]
Platform:	x86_64
Edition:	Enterprise
License Type:	Time-Limited
Validity:	Until Mon Mar 11 10:48:34 2019
```

And Licence invalid
```
ntopng --check-license
Invalid license

```
However Webapp says it's "community" edition
![Captura de pantalla -2019-03-11 15-35-24](https://user-images.githubusercontent.com/14880802/54156141-a122f180-4413-11e9-8ef7-f99a3b35cb56.png)

In order to solve it, i add the following switch to the end of /etc/ntop/ntopng.conf:

```
--online-license-check
--community
```
And restart ntopng/redis-server

Another contradiction is with the manual. In "man ntopng" no reference to switch **--community** but it is mentioned in the [cli options](https://www.ntop.org/guides/ntopng/cli_options.html) and in issues [1696](https://github.com/ntop/ntopng/issues/1696) say "the --community switch is only available in licensed version"

**Question:** How can i complete changed/active and work with community/free version?

thanks in advance

**Comment by emanuele-f** [comment]
The `--community` is the option you need in order to run in community mode in ntopng (you can remove `--online-license-check`). Please note that other software (nprobe, cento) require a license and there is no community mode but only a limited demo.

**Comment by maravento** [comment]
I read the post: [Combining Demo with Permanent Licenses](https://www.ntop.org/support/faq/combining-demo-with-permanent-licenses/) and [What is your software licensing model?](https://www.ntop.org/support/faq/what-is-your-software-licensing-model/)
There is not much clarity on the issue of licenses used by third party ntopng. So, the question would be:

Ntopng (with the switch "--community") will stop working at some time, due to the eventual expiration of third party demo licenses (nprove, cento, etc)?

thanks in advance

**Comment by emanuele-f** [comment]
ntopng in community mode will not stop working, it will continue to collect data from nprobe. nprobe/cento, however, will stop sending data to ntopng after some time, so you need a license for nprobe/cento to run them continuously

**Comment by maravento** [comment]
I appreciate more precise in your answer. How long will ntopng stop receiving data from nprobe / cento and what is the negative effect that this causes?

**Comment by sneak** [comment]
This should be better documented.  The fact that ntopng has components required for basic functionality that are not free software basically means that ntopng, community edition aside, is not free software as it does not function correctly without use of proprietary software.

Thus, on systems that don't run nonfree software, ntopng is useless and unsuitable.

**Comment by simonemainardi** [comment]
> Thus, on systems that don't run nonfree software, ntopng is useless and unsuitable.

This statement is not accurate. You can build and run ntopng from sources and run it on any system. Without anything proprietary. Extra 'proprietary' functionalities extend base community functionalities and are part of a popular business model. See https://en.wikipedia.org/wiki/Freemium

**Comment by sneak** [comment]
Freemium software is not free software.  Ntopng relies on other, entirely nonfree software packages to function.

**Comment by simonemainardi** [comment]
> Freemium software is not free software. Ntopng relies on other, entirely nonfree software packages to function.

This statement is not correct. It does not rely on any nonfree software to function.

**Comment by sneak** [comment]
User @emanuele-f said otherwise (that nprobe and cento are both a) proprietary, and b) require a license) in the following comment, which I regarded as authoritative:

https://github.com/ntop/ntopng/issues/2455#issuecomment-471911119

**Comment by simonemainardi** [comment]
> product or service is provided free of charge, but money (a premium) is charged for additional features

Source: https://en.wikipedia.org/wiki/Freemium

**Comment by sneak** [comment]
Yes, free software has nothing to do with price, but freedom.
