### ISSUE TITLE
Errors related to LuaEngine.cpp, Utils.cpp, etc

### ISSUE THREAD

**Issue by maravento** [ntop/ntopng#2456]
a. In one PC. Ubutu18.04.2 x64. Obtain network via DHCP

Errors related to LuaEngine.cpp, Utils.cpp:
`[LuaEngine.cpp:8741] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/lists_utils.lua:259: attempt to index a number value (local 'res')]`
`[Utils.cpp:1713] ERROR: Could not open /var/lib/ntopng/category_lists/Cisco Talos Intelligence.txt.new for write`
![problem](https://user-images.githubusercontent.com/14880802/54157265-fb24b680-4415-11e9-8b53-856d7c2ad43d.png)

b. In another PC. Ubutu18.04.2 x64. Obtain network via static IP (interfaces: 1 lan 1 wan)

Error related to NetworkInterface.cpp
![Captura de pantalla -2019-03-10 12-04-36](https://user-images.githubusercontent.com/14880802/54159609-5dcc8100-441b-11e9-94a0-fc6e4fde0b99.png)

Error related to "could not find '/var/lib/ntopng/category_list/...." 
![Captura de pantalla -2019-03-11 16-28-46](https://user-images.githubusercontent.com/14880802/54159795-e0edd700-441b-11e9-91cf-90dbd149de80.png)

global parameters (for both PCs)
```
ntopng --version
v.3.9.190311	[Enterprise/Professional build]
GIT rev:	dev:840313dd60620ded5492ae87be780c3461b5522d:20190311
Pro rev:	r2275
Built on:	Ubuntu 18.04.2 LTS
System Id:	[REMOVED]
Platform:	x86_64
Edition:	Enterprise
License Type:	Time-Limited
Validity:	Until Mon Mar 11 16:02:33 2019
```

Install method:
```
wget http://apt.ntop.org/18.04/all/apt-ntop.deb
dpkg -i apt-ntop.deb
apt update -y
apt install pfring-dkms nprobe ntopng n2disk cento -y

```
Too many errors. How are they solved?. thanks in advance

**Comment by emanuele-f** [comment]
It seems like a permission issue. Please ensure that the ntopng user has write access to `/var/lib/ntopng` (e.g. `chwon -R ntopng:ntopng /var/lib/ntopng`) or add the `-s` option to run as root.

**Comment by maravento** [comment]
I already did what you said (chwon -R ntopng:ntopng /var/lib/ntopng) and the errors keep appearing every 3 seconds:
```
[Utils.cpp:1713] ERROR: Could not open /var/lib/ntopng/category_lists/Cisco Talos Intelligence.txt.new for write
[LuaEngine.cpp:8741] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/lists_utils.lua:259: attempt to index a number value (local 'res')]
```

```
root@test:/var/lib/ntopng/category_lists# ls -l
total 128
-rw------- 1 ntopng ntopng 21479 mar 10 11:12 'Cisco Talos Intelligence.txt'
----rw-rw- 1 ntopng ntopng     0 mar 11 08:04 'Cisco Talos Intelligence.txt.new'
-rw------- 1 ntopng ntopng 20444 mar 10 11:12 'Emerging Threats.txt'
----rw-rw- 1 ntopng ntopng     0 mar 11 08:04 'Emerging Threats.txt.new'
-rw------- 1 ntopng ntopng  4744 mar 10 11:12 'Feodo Tracker Botnet C2 IP Blocklist.txt'
----rw-rw- 1 ntopng ntopng     0 mar 11 08:04 'Feodo Tracker Botnet C2 IP Blocklist.txt.new'
-rw------- 1 ntopng ntopng 17826 mar 10 11:12 'NoCoin Filter List.txt'
----rw-rw- 1 ntopng ntopng     0 mar 11 08:04 'NoCoin Filter List.txt.new'
-rw------- 1 ntopng ntopng 51727 mar 10 11:12 'Ransomware Domain Blocklist.txt'
----rw-rw- 1 ntopng ntopng     0 mar 11 08:04 'Ransomware Domain Blocklist.txt.new'
-rw------- 1 ntopng ntopng  2106 mar 10 11:12 'SSLBL Botnet C2 IP Blacklist.txt'
----rw-rw- 1 ntopng ntopng     0 mar 11 08:04 'SSLBL Botnet C2 IP Blacklist.txt.new'
```

**Comment by emanuele-f** [comment]
@maravento in 43bce04dd53ecbc9de27c1f973f49a86ef748305 I've fixed the script error. For the permissions issue, please perform the following steps:

1. `systemctl stop ntopng`
2. `rm -rf /var/lib/ntopng/category_lists`
3. `systemctl start ntopng`

I think in your case ntopng was started as root in some previous run and then the permissions got broken. Please start clean with the commands above and let me know.

**Comment by maravento** [comment]
solved. Thanks

**Comment by sgajemison** [comment]
I too am getting errors similar to this every 3 seconds. I have tried the suggestions above without success yet.

29/Aug/2019 08:47:52 [LuaEngine.cpp:9776] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][...are/ntopng/scripts/lua/modules/alert_endpoints_utils.lua:131: attempt to compare number with string]
29/Aug/2019 08:47:49 [LuaEngine.cpp:9776] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][...are/ntopng/scripts/lua/modules/alert_endpoints_utils.lua:131: attempt to compare number with string]
29/Aug/2019 08:47:46 [LuaEngine.cpp:9776] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][...are/ntopng/scripts/lua/modules/alert_endpoints_utils.lua:131: attempt to compare number with string]
29/Aug/2019 08:47:43 [LuaEngine.cpp:9776] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][...are/ntopng/scripts/lua/modules/alert_endpoints_utils.lua:131: attempt to compare number with string]
29/Aug/2019 08:47:40 [LuaEngine.cpp:9776] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][...are/ntopng/scripts/lua/modules/alert_endpoints_utils.lua:131: attempt to compare number with string]
29/Aug/2019 08:47:37 [LuaEngine.cpp:9776] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][...are/ntopng/scripts/lua/modules/alert_endpoints_utils.lua:131: attempt to compare number with string]
29/Aug/2019 08:47:34 [LuaEngine.cpp:9776] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][...are/ntopng/scripts/lua/modules/alert_endpoints_utils.lua:131: attempt to compare number with string]

**Comment by emanuele-f** [comment]
The problem is different here. Please open a new issue and specify:
- the output of `ntopng --version`
- the `Alert Endpoints` that you have enabled into the ntopng preferences
