### ISSUE TITLE
Improve network/application latency handling in collector mode

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2460]
@NTOPNG@ template in nProbe should be extended with latency computation, and ntopng should handled it properly in flows. Furthermore if flow export in nProbe is longer than ntopng export timeout, latency information that is computed at the beginning of the flow, is lost: it needs to be fixed

**Comment by simonemainardi** [comment]
Implemented. Both application and network latencies are now added to the default @NTOPNG@ template
