### ISSUE TITLE
Warning related to segmentation

### ISSUE THREAD

**Issue by maravento** [ntop/ntopng#2462]
Warning related to segmentation ([large send offload LSO and generic segmentation offload GSO](https://en.wikipedia.org/wiki/Large_send_offload))

**Datasheet:**
OS: Ubuntu 18.04.2 x64
switch on /etc/ntopng/ntopng.conf: 
```
--daemon
--community
--dns-mode 1
```
**Warning:**
```
[NetworkInterface.cpp:2044] WARNING: If you have TSO/GRO enabled, please disable it
ntopng: [NetworkInterface.cpp:2046] WARNING: Use sudo ethtool -K lo gro off gso off tso off
```
Note: This warning is output regardless of whether the network interfaces switch is active (or not) in the ntop configuration file

**Evidence:**
```
ntopng[9809]: 18/Mar/2019 07:37:13 [Ntop.cpp:432] Welcome to ntopng x86_64 v.3.9.190318 - (C) 1998-19 ntop.org
ntopng[9809]: 18/Mar/2019 07:37:13 [Ntop.cpp:442] Built on Ubuntu 18.04.2 LTS
ntopng[9809]: 18/Mar/2019 07:37:13 [Ntop.cpp:767] Adding 127.0.0.1/32 as IPv4 interface address for lo
ntopng[9809]: 18/Mar/2019 07:37:13 [Ntop.cpp:775] Adding 127.0.0.0/8 as IPv4 local network for lo
ntopng[9809]: 18/Mar/2019 07:37:13 [Ntop.cpp:767] Adding 192.168.1.20/32 as IPv4 interface address for wlp1s0
ntopng[9809]: 18/Mar/2019 07:37:13 [Ntop.cpp:775] Adding 192.168.1.0/24 as IPv4 local network for wlp1s0
ntopng[9809]: 18/Mar/2019 07:37:13 [Ntop.cpp:795] Adding ::1/128 as IPv6 interface address for lo
ntopng[9809]: 18/Mar/2019 07:37:13 [Ntop.cpp:804] Adding ::1/128 as IPv6 local network for lo
ntopng[9809]: 18/Mar/2019 07:37:13 [Ntop.cpp:795] Adding fe80::fe38:4ac6:33cc:b8cc/128 as IPv6 interface address for wlp1s0
ntopng[9809]: 18/Mar/2019 07:37:13 [Ntop.cpp:804] Adding fe80::fe38:4ac6:33cc:b8cc/64 as IPv6 local network for wlp1s0
ntopng[9809]: 18/Mar/2019 07:37:13 [PeriodicActivities.cpp:72] Started periodic activities loop...
ntopng[9809]: 18/Mar/2019 07:37:14 [PeriodicActivities.cpp:113] Each periodic activity script will use 3 threads
ntopng[9809]: 18/Mar/2019 07:37:14 [NetworkInterface.cpp:2726] Started packet polling on interface wlp1s0 [id: 1]...
ntopng[9809]: 18/Mar/2019 07:37:14 [NetworkInterface.cpp:2726] Started packet polling on interface lo [id: 2]...
ntopng[9809]: 18/Mar/2019 07:37:14 [NetworkInterface.cpp:2726] Started packet polling on interface enp2s0 [id: 3]...
ntopng[9809]: 18/Mar/2019 07:37:16 [NetworkInterface.cpp:2043] Invalid packet received [len: 65549][max len: 65535].
ntopng: [NetworkInterface.cpp:2044] WARNING: If you have TSO/GRO enabled, please disable it
ntopng[9809]: 18/Mar/2019 07:37:16 [NetworkInterface.cpp:2044] WARNING: If you have TSO/GRO enabled, please disable it
ntopng: [NetworkInterface.cpp:2046] WARNING: Use sudo ethtool -K lo gro off gso off tso off
ntopng[9809]: 18/Mar/2019 07:37:16 [NetworkInterface.cpp:2046] WARNING: Use sudo ethtool -K lo gro off gso off tso off
```

**Comment by emanuele-f** [comment]
Do you mean the `-i` option? If you don't specify the `-i`, then ntopng will monitor all the available interfaces, so this is normal.

**Comment by maravento** [comment]
As I mentioned in the description: It does not matter if the interfaces are specified (example: -i=enp2s0) in /etc/ntopng/ntopng.conf

**Comment by maravento** [comment]
**Question:** Does NtopNG recognize all formats of the network interfaces?
Example (debian/ubuntu and derivatives):
Old format:
```
-i=eth0
-i=eth1
-i=lo
-i=wlan0
etc...
```
New format (based on udev):
```
-i=enp2s0
-i=lo
-i=wlp1s0
etc...
```
New format on some servers HP proliant (based on udev):
```
-i=eno0
-i=eno1
-i=lo
etc...
```

Thanks

**Comment by emanuele-f** [comment]
The warning is normal, please run `sudo ethtool -K lo gro off gso off tso off` as described in the log to fix it. The interface name is just a name, for ntopng it's the same.

**Comment by maravento** [comment]
Solved. Thanks

**Comment by ajaufura** [comment]
Hi,

I wanted to run  ntopng via docker on raspberrypi 4. I have exactly the same error. 

Log:
26/Feb/2021 21:43:40 [NetworkInterface.cpp:949] Invalid packet received [len: 2974][MTU: 1518].
26/Feb/2021 21:43:40 [NetworkInterface.cpp:950] WARNING: If you have TSO/GRO enabled, please disable it
26/Feb/2021 21:43:40 [NetworkInterface.cpp:952] WARNING: Use: sudo ethtool -K docker0 gro off gso off tso off
26/Feb/2021 21:45:01 [NetworkInterface.cpp:949] Invalid packet received [len: 4244][MTU: 1518].
26/Feb/2021 21:45:01 [NetworkInterface.cpp:950] WARNING: If you have TSO/GRO enabled, please disable it
26/Feb/2021 21:45:01 [NetworkInterface.cpp:952] WARNING: Use: sudo ethtool -K eth0 gro off gso off tso off

Running "sudo ethtool -K eth0 gro off gso off tso off" does not solve the issue.

These guys are already in off status :
ethtool -k eth0 | grep offload

tcp-segmentation-offload: off
udp-fragmentation-offload: off
generic-segmentation-offload: off


Have you an idea on the issue?

**Comment by ajaufura** [comment]
Features for eth0:
rx-checksumming: off
tx-checksumming: off
        tx-checksum-ipv4: off [fixed]
        tx-checksum-ip-generic: off
        tx-checksum-ipv6: off [fixed]
        tx-checksum-fcoe-crc: off [fixed]
        tx-checksum-sctp: off [fixed]
scatter-gather: on
        tx-scatter-gather: on
        tx-scatter-gather-fraglist: off [fixed]
tcp-segmentation-offload: off
        tx-tcp-segmentation: off [fixed]
        tx-tcp-ecn-segmentation: off [fixed]
        tx-tcp-mangleid-segmentation: off [fixed]
        tx-tcp6-segmentation: off [fixed]
udp-fragmentation-offload: off
generic-segmentation-offload: off
generic-receive-offload: on
large-receive-offload: off [fixed]
rx-vlan-offload: off [fixed]
tx-vlan-offload: off [fixed]
ntuple-filters: off [fixed]
receive-hashing: off [fixed]

**Comment by cardigliano** [comment]
@ajaufura it is likely eth0 is a virtual interface (ethtool -i eth0 should tell you that) and GRO/TSO is enabled on the physical interfaces. Said that it is recommended to turn offloads off when processing traffic to match exactly what is seen on the wire, you can still analyse traffic with those features enabled.
