### ISSUE TITLE
Host pool chart

### ISSUE THREAD

**Issue by HoseinKashefi** [ntop/ntopng#2464]
after Update to version 3.9.190319-6049 ntopng doesn't show host pool charts 
![image](https://user-images.githubusercontent.com/43135531/54592959-a9e27b80-4a42-11e9-8f7d-db8434243d4b.png)

**Comment by simonemainardi** [comment]
I correctly get the host pools charts using the latest dev. Can you please update to the latest version and report? do you see any error in the console?

**Comment by HoseinKashefi** [comment]
i updated to v.3.9.190321 but problem still exist.
there is no error on ntopng console.
![image](https://user-images.githubusercontent.com/43135531/54749439-c53bbb00-4be9-11e9-813a-ac3fc2429f4e.png)

**Comment by emanuele-f** [comment]
How many host pools do you have? Are you using InfluxDB or RRD?

**Comment by HoseinKashefi** [comment]
2 host pools except "Not Assign" and using RRD

**Comment by emanuele-f** [comment]
I've added some debug messages in RRD, please wait one hour until the new package is available, update and follow the following instructions:

1. While ntopng is running, run `redis-cli set "ntopng.prefs.rrd_debug_enabled" "1"`
2. Stop the ntopng service with `systemctl stop ntopng`
3. Run ntopng from cli: `sudo ntopng /etc/ntopng/ntopng.conf | grep host_pools`
4. Wait 10 minutes for the RRD update to be triggered, post the console output
5. Go into the host pools charts page of the chart above and post the output

**Comment by HoseinKashefi** [comment]
Emanuele,
hope these are what you want 
![image](https://user-images.githubusercontent.com/43135531/55217863-2ed94c00-521e-11e9-9dcd-1813c1a36901.png)
![image](https://user-images.githubusercontent.com/43135531/55217915-44e70c80-521e-11e9-9cfb-a5b4d633bcb8.png)
[ntopng-rrd.log](https://github.com/ntop/ntopng/files/3021620/ntopng-rrd.log)

[Ntopng-output.txt](https://github.com/ntop/ntopng/files/3021626/Ntopng-output.txt)

**Comment by emanuele-f** [comment]
Thank you for the information, I've made a fix in 0099d2a88711e86f42d664c18c6626b49e2a284a . The new package will be available in one hour. Please update and let me know if it works fine for you.

**Comment by HoseinKashefi** [comment]
Thank you so much. its is ok now after update.
just for information ntopng generates following logs and there are too many.maybe they aren't necessary.
[ntopng-rrd(2).log](https://github.com/ntop/ntopng/files/3022387/ntopng-rrd.2.log)

**Comment by emanuele-f** [comment]
Great. The logs have been enabled by the commands above, to disable:

1. While ntopng is running, run `redis-cli set "ntopng.prefs.rrd_debug_enabled" "0"`
2. Restart ntopng with `sudo systemctl restart ntopng`
