### ISSUE TITLE
Site can't be reached when adding --https-port to config

### ISSUE THREAD

**Issue by jschilen** [ntop/ntopng#2465]
My config and access works fine on port 3000, but I want to switch to SSL to protect login credentials in transit.

When I add 
--http-port=80
--https-port=443
to ntopng.conf, I can see ntopng listening on ports 80/443 and can curl it locally on the box. 

However I'm not able to access it from any other computer (even on the same network). I just get "This site cannot be reached." In a packet capture I can see SYN packets making it to my ntopng server but no response packets.

I have two interfaces, EM1 is connected to a network tap, and EM2 is configured with the ip address for the system.

**Comment by simonemainardi** [comment]
Very likely there's something preventing ntopng from starting - ie., someone else using either port 80 or 443.

Check ntopng output, you may end up in seeing something like:

```
simone@devel:~/ntopng$ sudo ./ntopng -i eno1 -w 80 -W 443
20/Mar/2019 15:54:03 [Ntop.cpp:1972] Setting local networks to 127.0.0.0/8
20/Mar/2019 15:54:03 [Redis.cpp:152] Successfully connected to redis 127.0.0.1:6379@0
20/Mar/2019 15:54:03 [Redis.cpp:152] Successfully connected to redis 127.0.0.1:6379@0
20/Mar/2019 15:54:03 [NtopPro.cpp:311] [LICENSE] Reading license from Redis
20/Mar/2019 15:54:03 [NtopPro.cpp:208] [LICENSE] 56D68C654FDE9D2A3315014CBCFD86CC15555912869BB3508D: found valid Enterprise license
20/Mar/2019 15:54:04 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.7.5.0 interface eno1...
20/Mar/2019 15:54:04 [Ntop.cpp:2064] Registered interface eno1 [id: 0]
20/Mar/2019 15:54:04 [main.cpp:302] PID stored in file /var/run/ntopng.pid
20/Mar/2019 15:54:04 [HTTPserver.cpp:1190] SSL loaded CA #0: /C=IT/ST=Firenze/L=Empoli/O=ntop CA/OU=ca/CN=ca/emailAddress=ca@ntop.org
20/Mar/2019 15:54:04 [HTTPserver.cpp:1198] SSL init [ssl_ca_path: /home/simone/ntopng/httpdocs/ssl/ntopng-ca.crt][ssl_cert_path: /home/simone/ntopng/httpdocs/ssl/ntopng-cert.pem]
20/Mar/2019 15:54:04 [HTTPserver.cpp:1060] ERROR: [HTTP] set_ports_option: cannot bind to 80: Address already in use
20/Mar/2019 15:54:04 [mongoose.c:4591] ERROR: set_ports_option: cannot bind to 80: Success
20/Mar/2019 15:54:04 [HTTPserver.cpp:1317] ERROR: Unable to start HTTP server (IPv4) on ports 80,443s
20/Mar/2019 15:54:04 [HTTPserver.cpp:1323] ERROR: Either port in use or another ntopng instance is running (using the same port)
```

So either change the ports or stop the services already running there.

**Comment by jschilen** [comment]
Hello,

It is starting on 80/443. I can curl the box locally. 
[root@ontap01 ~]# netstat -anp |grep 80
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      30465/ntopng
[root@ontap01 ~]# netstat -anp |grep 443
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      30465/ntopng


Mar 20 11:03:32 ontap01.uis.kent.edu systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
Mar 20 11:03:32 ontap01.uis.kent.edu systemd[1]: Started ntopng high-speed web-based traffic monitoring and analysis tool.
Mar 20 11:03:32 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:32 [Ntop.cpp:1902] Setting local networks to xxxxxxxx
Mar 20 11:03:32 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:32 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
Mar 20 11:03:32 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:32 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
Mar 20 11:03:32 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:32 [NtopPro.cpp:313] [LICENSE] Reading license from /etc/ntopng.license
Mar 20 11:03:32 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:32 [NtopPro.cpp:205] [LICENSE] /etc/ntopng.license: unable to validate Enterprise license [License mismatch error]
Mar 20 11:03:32 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:32 [NtopPro.cpp:208] [LICENSE] /etc/ntopng.license: found valid Professional license
Mar 20 11:03:33 ontap01.uis.kent.edu ntopng[30465]: Actual changes:
Mar 20 11:03:33 ontap01.uis.kent.edu ntopng[30465]: rx-vlan-offload: on [requested off]
Mar 20 11:03:33 ontap01.uis.kent.edu ntopng[30465]: rx-vlan-stag-hw-parse: on
Mar 20 11:03:33 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:33 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.7.4.0 interface em1...
Mar 20 11:03:33 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:33 [Ntop.cpp:1996] Registered interface em1 [id: 0]
Mar 20 11:03:33 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:33 [main.cpp:308] PID stored in file /var/run/ntopng.pid
Mar 20 11:03:33 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:33 [Utils.cpp:592] User changed to ntopng
Mar 20 11:03:33 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:33 [HTTPserver.cpp:1199] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
Mar 20 11:03:33 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:33 [HTTPserver.cpp:1202] HTTP server listening on 80
Mar 20 11:03:33 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:33 [HTTPserver.cpp:1208] HTTPS server listening on 443
Mar 20 11:03:33 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:33 [main.cpp:390] Working directory: /data/moloch/raw
Mar 20 11:03:33 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:33 [main.cpp:392] Scripts/HTML pages directory: /usr/share/ntopng
Mar 20 11:03:33 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:33 [Ntop.cpp:403] Welcome to ntopng x86_64 v.3.8.190219 - (C) 1998-18 ntop.org
Mar 20 11:03:33 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:33 [NtopPro.cpp:634] [LICENSE] System Id:        xxxxxxxx
Mar 20 11:03:33 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:33 [NtopPro.cpp:635] [LICENSE] Edition:        Professional
Mar 20 11:03:33 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:33 [NtopPro.cpp:636] [LICENSE] License Type:        Permanent License
Mar 20 11:03:33 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:33 [NtopPro.cpp:639] [LICENSE] License:        xxxxxxxxxxxx
Mar 20 11:03:33 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:33 [NtopPro.cpp:649] [LICENSE] Maintenance:        Until Wed Mar 11 11:40:35 2020 [357 days left]
Mar 20 11:03:34 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:34 [PeriodicActivities.cpp:72] Started periodic activities loop...
Mar 20 11:03:34 ontap01.uis.kent.edu sudo[30491]:   ntopng : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/ntopctl n2n has-service n2n_assistance
Mar 20 11:03:34 ontap01.uis.kent.edu sudo[30497]:   ntopng : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/ntopctl n2disk has-service em1
Mar 20 11:03:34 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:34 [PeriodicActivities.cpp:113] Each periodic activity script will use 2 threads
Mar 20 11:03:34 ontap01.uis.kent.edu ntopng[30465]: 20/Mar/2019 11:03:34 [NetworkInterface.cpp:2580] Started packet polling on interface em1 [id: 0]...

**Comment by jschilen** [comment]
Hello,

Can you please re-open this? I responded to this post on the web.

Jeremiah

**Comment by simonemainardi** [comment]
is there a firewall blocking incoming connections from the outside on ports 80 / 443?

**Comment by jschilen** [comment]
No. As I said I can see the traffic make it to the server in a packet capture, there's just not a response sent.
________________________________

**Comment by simonemainardi** [comment]
if you do a packet capture on the ntopng server, you will still be able to see the incoming SYNs even if a firewall (on the ntopng server of course) would block them. Check it.

**Comment by jschilen** [comment]
Hello,

I’m sorry, you were correct. There was  a firewall running on the host. It works now.

Thank you,

Jeremiah
