### ISSUE TITLE
Implement InfluxDB Alert

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2467]
It is required to implement alerts in ntopng due to Influx
20/Mar/2019 04:25:08 [Utils.cpp:1451] WARNING: Unable to post data to (http://localhost:8086/write?db=ntopng): Timeout was reached
20/Mar/2019 03:45:08 [Utils.cpp:1451] WARNING: Unable to post data to (http://localhost:8086/write?db=ntopng): Timeout was reached
19/Mar/2019 22:20:08 [Utils.cpp:1451] WARNING: Unable to post data to (http://localhost:8086/write?db=ntopng): Timeout was reached

better also to log how long was the timeout, and specify if the measurements were lost or ntopng tried one more time

**Comment by emanuele-f** [comment]
There is already an alert triggered whenever an export error occurs, however it is a stored alert (goes into the past alerts) ![2019-03-26_12-15](https://user-images.githubusercontent.com/5488003/54992919-81193380-4fb8-11e9-8276-7d9304db4f00.png)

**Comment by simonemainardi** [comment]
Implemented. With the current "Count" added it is now also possibly to quantify the number of exports that have been failed, along with their begin/end time.
