### ISSUE TITLE
Is ntopng good for openvpn monitoring?

### ISSUE THREAD

**Issue by PrzemekSkw** [ntop/ntopng#2468]
Hello, I install openvpn on my debian 9 VPS. I want to monitor my vpn connections. Is ntopng good for this? I'm totally nobb with servers. 
Regards Przemek

**Comment by emanuele-f** [comment]
Hi, with ntopng you can monitor the flows and hosts on a network interface (or virtual interface in your case), so yes this is a suitable task, you simply need to install ntopng in your vps and start it on the tun interface (e.g. add the `-i=tun0` in /etc/ntopng/ntopng.conf). You can install prebuilt packages by following the instruction from http://packages.ntop.org . Please note that some interesting features (like the ability to review past flows via the MySQL integration) are only available in the licensed versions of ntopng. Please check out the documentation https://www.ntop.org/guides/ntopng and features comparison https://www.ntop.org/products/traffic-analysis/ntop/ for more details.

A tip to avoid being flooded by network/vulnerability scanners online: start openvpn on a non standard port, please avoid port 443.

**Comment by PrzemekSkw** [comment]
@emanuele-f Thanks for TIP. I install ntopng and learn about servers and monitoring now :)

**Comment by emanuele-f** [comment]
You are welcome. You can also reach us via the telegram community group, please check out https://www.ntop.org/community
