### ISSUE TITLE
Report Details Inconsistent With WAN PRTG Bandwidth Monitor

### ISSUE THREAD

**Issue by PrimaryHealthTas** [ntop/ntopng#247]
Firstly, Im very new to ntopng. Our WAN bandwidth usage is currently monitored with PRTG. It only shows overall usage so every time it peaks out (10Mbps) I never know who is doing it. This is why I want to get ntopng working. 
My issue is, yesterday there was peak activity on the WAN and since ntopng is now running I decided to produce a report of the period during which the peak activity had been noticed. The report had no resemblance to the WAN activity. Ive attached a PRTG screenshot of the offending link along with ntopng report for the same period. Appreciate some guidance please.
Many thanks.
![capture 15mins 2](https://cloud.githubusercontent.com/assets/15238724/10650807/51bea2a6-7897-11e5-840c-194411bba27c.JPG)
![capture 15mins](https://cloud.githubusercontent.com/assets/15238724/10650808/51be9f5e-7897-11e5-9544-fbe25f0d9f30.JPG)
![capture wan 21 oct](https://cloud.githubusercontent.com/assets/15238724/10650809/51bf9b66-7897-11e5-895b-3f72bcf0acb1.JPG)

**Comment by simonemainardi** [comment]
Hello. I need to understand if this is an ntopng report issue, or possible misconfiguration.

Could you please check the historical interface activity and see if the spike is recorder there? To check historical activity, select the interface from the "Interfaces" dropdown menu, and then click on the 
![image](https://cloud.githubusercontent.com/assets/3397663/10660066/961dfea8-78a4-11e5-80a1-9cb118809b76.png) that comes out.

If the activity is not detected, then please post ntopng configuration, and how you start it. In case you are executing ntopng as a service, you may also want to try and execute it in the console. Useful information may appear in the logging.

**Comment by lucaderi** [comment]
@PrimaryHealthTas Some questions:
1. are you sure the interface you are monitoring is the same monitored by PRTG? I don't think so. AFAIK PRTG wrks with SNMP whereas ntopng reads packets from a NIC. I think you have not mirrored the traffic as it should.
2. You need to configure the local/remote part as you seem not to have done that. Please see the -m flag

Bottom line, it looks a configuration issue on your side.
