### ISSUE TITLE
license Problem

### ISSUE THREAD

**Issue by tharveycesd73** [ntop/ntopng#2470]
Running Centos VM with nprobe and ntopng.
Nprobe license install was straightforward.

Registered and installed ntopng Enterprise license via GUI. However the Gui displays it as still a community license.
Have tried adding the ntopng.license file in /etc and also the --online-license-check option at startup.

ntopng -V displays the following:
v.3.8.190321	[Enterprise/Professional build]
GIT rev:	3.8-stable:ee06ec5b0def16e48404ea16b01408439fa30586:20190321
Pro rev:	r2171
Built on:	
System Id:	1C366A0F7608AA82
Platform:	x86_64
Edition:	Enterprise
License Type:	Permanent
Maintenance:	Until Fri Mar 20 08:53:23 2020 [364 days left]

Thanks!

**Comment by simonemainardi** [comment]
it seems that the license is ok:

```
License Type:	Permanent
Maintenance:	Until Fri Mar 20 08:53:23 2020 [364 days left]
```

What's the output of ntopng --check-license? Can you please post a screenshot of page "About ntopng" including the footer?

**Comment by tharveycesd73** [comment]
ntopng]# ntopng --check-license
License Ok

I've hidden the license key as it's a public forum but it displays correctly in the box.

<img width="1283" alt="Screen Shot 2019-03-21 at 11 26 05 AM" src="https://user-images.githubusercontent.com/48733210/54772111-4edc9000-4bcc-11e9-8349-fb64c5804724.png">

**Comment by tharveycesd73** [comment]
<img width="1525" alt="Screen Shot 2019-03-21 at 12 21 36 PM" src="https://user-images.githubusercontent.com/48733210/54775632-04f7a800-4bd4-11e9-9811-7141d66663b5.png">

**Comment by tharveycesd73** [comment]
Solved it. There was a statement --community in the ntopng.conf file. I commented it out and it works now.
