### ISSUE TITLE
Implement ad block

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2471]
Add ad-blocking in ntopng Edge

**Comment by simonemainardi** [comment]
This is implemented.

Advertisement sites are already available and shipped within nEdge as part of the lists.

![image](https://user-images.githubusercontent.com/3397663/83246912-0f7fdb00-a1a3-11ea-8132-4925f91f33c6.png)


Hence, to block ads, it suffices to pick the users and block the category advertisement:

![image](https://user-images.githubusercontent.com/3397663/83246799-ecedc200-a1a2-11ea-8344-1cb30678086b.png)
