### ISSUE TITLE
Improve ntopng/nProbe integration

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2472]
Extend the nprobe @NTOPNG@ template macro to send ntopng additional fields such as latencies, and update ntopng to handle them as first citizens. In essence we need to make sure that the user experience of a nProbe/Probe collector or ntopng (packet-based) monitoring and as similar as possible

**Comment by simonemainardi** [comment]
implemented,

@NTOPNG@ is now expanded in two macros, depending on whether nProbe is used in collector or probe mode:

```

#define EXPANDED_NTOPNG_SHORTCUT_COLLECTOR_MODE "%IN_SRC_MAC %OUT_DST_MAC %INPUT_SNMP %OUTPUT_SNMP %SRC_VLAN %IPV4_SRC_ADDR %IPV4_DST_ADDR %L4_SRC_PORT %L4_DST_PORT %IPV6_SRC_ADDR %IPV6_DST_ADDR %IP_PROTOCOL_VERSION %PROTOCOL %L7_PROTO %IN_BYTES %IN_PKTS %OUT_BYTES %OUT_PKTS %FIRST_SWITCHED %LAST_SWITCHED"
#define EXPANDED_NTOPNG_SHORTCUT_PROBE_MODE  EXPANDED_NTOPNG_SHORTCUT_COLLECTOR_MODE "%CLIENT_NW_LATENCY_MS %SERVER_NW_LATENCY_MS %APPL_LATENCY_MS %CLIENT_TCP_FLAGS %SERVER_TCP_FLAGS %OOORDER_IN_PKTS %OOORDER_OUT_PKTS %RETRANSMITTED_IN_PKTS %RETRANSMITTED_OUT_PKTS %DNS_QUERY %HTTP_URL %HTTP_SITE %SSL_SERVER_NAME %BITTORRENT_HASH"
```

Suggested latencies (network and application), tcp flags (client and server) and other fields (eg., dns queries and http urls) have been added to the nProbe template and parsed in ntopng.
