### ISSUE TITLE
Dependency issue - couldnt remove ntopng from Debian stretch

### ISSUE THREAD

**Issue by DmitryRendov** [ntop/ntopng#2475]
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 pfring-dkms : Depends: pfring (= 7.5.0-2440) but 7.5.0-2466 is installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

root@mail /home/minecraft # sudo apt list pfring
Listing... Done
pfring/unknown,now 7.5.0-2466 amd64 [installed,automatic]

root@mail /home/minecraft # sudo apt list pfring-dkms -a
Listing... Done
pfring-dkms/unknown 7.5.0 all [upgradable from: 7.5.0]
pfring-dkms/now 7.5.0 all [installed,upgradable to: 7.5.0]

**Comment by cardigliano** [comment]
@DmitryRendov could you try again with "apt-get update && apt-get upgrade"? I just tested the update and it is working for me, I want to make sure you are still able to reproduce it.

**Comment by DmitryRendov** [comment]
@cardigliano apparently it's fixed. thank you, guys! awesome tool.

> **root@mail /home/minecraft # apt-get update && apt-get upgrade**
> Get:1 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
> Ign:2 http://deb.debian.org/debian stretch InRelease
> Hit:3 http://deb.debian.org/debian stretch Release
> Get:5 http://security.debian.org/debian-security stretch/updates/main Sources [197 kB]
> Get:6 http://packages.ntop.org/apt/stretch x64/ InRelease [2,137 B]
> Get:7 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [481 kB]
> Get:8 http://packages.ntop.org/apt/stretch all/ InRelease [2,137 B]
> Get:9 http://packages.ntop.org/apt/stretch x64/ Packages [3,083 B]
> Get:10 http://packages.ntop.org/apt/stretch all/ Packages [2,502 B]
> Hit:11 http://ppa.launchpad.net/webupd8team/java/ubuntu trusty InRelease
> Get:12 https://download.docker.com/linux/debian stretch InRelease [44.8 kB]
> Fetched 827 kB in 5s (144 kB/s)
> Reading package lists... Done
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> You might want to run 'apt --fix-broken install' to correct these.
> The following packages have unmet dependencies:
>  pfring-dkms : Depends: pfring (= 7.5.0-2440) but 7.5.0-2466 is installed
> E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
> 
> **root@mail /home/minecraft # apt --fix-broken install**
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Correcting dependencies... Done
> The following additional packages will be installed:
>   pfring-dkms
> The following packages will be upgraded:
>   pfring-dkms
> 1 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.
> 2 not fully installed or removed.
> Need to get 65.2 kB of archives.
> After this operation, 0 B of additional disk space will be used.
> Do you want to continue? [Y/n] y
> Get:1 http://packages.ntop.org/apt/stretch all/ pfring-dkms 7.5.0 [65.2 kB]
> Fetched 65.2 kB in 0s (249 kB/s)
> (Reading database ... 91803 files and directories currently installed.)
> Preparing to unpack .../pfring-dkms_7.5.0_all.deb ...
> Unpacking pfring-dkms (7.5.0) over (7.5.0) ...
> Setting up pfring-dkms (7.5.0) ...
> Loading new pfring-7.5.0 DKMS files...
> Building for 4.9.0-6-amd64
> Building for architecture amd64
> Building initial module for 4.9.0-6-amd64
> Done.
> 
> pf_ring:
> Running module version sanity check.
>  - Original module
>    - No original module exists within this kernel
>  - Installation
>    - Installing to /lib/modules/4.9.0-6-amd64/updates/dkms/
> 
> depmod...
> 
> DKMS: install completed.
> Setting up n2disk (3.3.190324-5121) ...
> Rebuilding ld cache...
> (Re)Starting n2disk...
> n2disk@* is a disabled or a static unit not running, not starting it.
> n2disk-ntopng@* is a disabled or a static unit not running, not starting it.
> disk2n@* is a disabled or a static unit not running, not starting it.
>
