### ISSUE TITLE
Add network label 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2476]
In the networks page, add the ability to set a mnemonic label (i.e. alias) to networks as it happens to many other elements in ntopng

**Comment by emanuele-f** [comment]
Example:

![2019-03-25_16-38](https://user-images.githubusercontent.com/5488003/54934217-0992c800-4f16-11e9-92ee-a0dbbb57369f.png)

**Comment by PsyMan2000-zz** [comment]
![image](https://user-images.githubusercontent.com/16685695/55575660-51c89c00-5707-11e9-983d-ce56b7e9c820.png)

Not showing in my server. I have to click on the report icon then the cog to get there.

**Comment by emanuele-f** [comment]
This is only available in the latest dev version. Please update to dev or wait for the next stable.

**Comment by PsyMan2000-zz** [comment]
Ahh, OK, I will wait for it to arrive in stable I think. Brilliant news : Good work.
