### ISSUE TITLE
Monitor networks latency

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2477]
Similar to #1073, compute the networks latency and report is on a metric/graph

**Comment by erg809** [comment]
*      Add a **search** **area** **to find** host or a query option similar to the firewalls log queries, dst IP, src IP or port,  read http headers for more details about the host, co-relate the snmp interface statistics with the scanned statistics.
•	Identify the source of broadcast storm, Excessive Network Collisions
•	identify STP issues /Loops source or dst.
•	Jitter threshold
•	Delays /RTT latency threshold
•	Link congestion threshold
•	excesive Packet drops threshold
•	Reorder packet percentage threshold
•	Triggers – Alerting on all the mentioned points above.
•	Purpose-built report

All this would be nice to have and I would gladly pay for it.

**Comment by simonemainardi** [comment]
@erg809 please open individual issues with examples and use cases so we can consider them individually. Also if you need expedited implementations contact us privately.

**Comment by simonemainardi** [comment]
this is part of the newly implemented active monitoring
