### ISSUE TITLE
Add flows_stats.lua header

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2478]
At the top of flows_stats.lua (close to the <hr> tag) add a header with coloured blocks similar to (http://docs.grafana.org/img/docs/v45/singlestat-panel.png) that summarises in one line metrics like (clicking on the box will jump on the selected view)
- # anomalous flows (vd total)
- # one way vs two way flows
- top application protocol per # flows
- top application protocol per # flow bytes

**Comment by simonemainardi** [comment]
see https://technitium.com/dns/ for example

**Comment by simonemainardi** [comment]
superseded by https://github.com/ntop/ntopng/issues/3445
