### ISSUE TITLE
Move "common alert thresholds" in  preferences 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2479]
Common flow thresholds (e.g. inside host_details.lua) are speed around various pages (host and interface). It would be nice to threat them on a different way and put them in preferences.

**Comment by emanuele-f** [comment]
The implementation is tightly coupled with the page, changing this requires >= 1 day of work. Instead, I suggest to rethink the alerts thresholds as follows.

- Add a new global page for the alerts threshold configuration
- The page should implement a datatable, where we can add rules via the `+` sign
- For each rule, we can specify:
  - Target type: host, interface, network
  - Target: "any" or a specific host/interface/network
  - Field: traffic, activity_time, etc, some fields are generic, some specific of the target type
  - Check frequency: minute, 5 min, hourly, daily
  - The theshold

Important to note that the field can be generalized, for example the user can choose to set a threshold on a nDPI category, not only P2P like now.

This can be a good moment to think about the "relative thresholds", e.g. generate an alert if the current day traffic is >= 70% of the previous day traffic.

**Comment by simonemainardi** [comment]
Common alerts thresholds no longer exists. These are now been moved to the user scripts. Each user script has now its own thresholds that can be set. Configurations allow to specify different targets.

For example, to apply different thresholds to hosts in `10.0.0.0/8` and in `192.168.2.0/24` one can create two configurations:

![image](https://user-images.githubusercontent.com/3397663/73073193-1b872380-3eb7-11ea-9641-f9d247040e85.png)

and then 'edit' each configuration to specify the desired thresholds.
