### ISSUE TITLE
ntopng not displaying values in historical correctly

### ISSUE THREAD

**Issue by Ayymoss** [ntop/ntopng#2480]
Reference: https://github.com/pfsense/FreeBSD-ports/tree/devel/net/pfSense-pkg-ntopng

Please note, this has been tested on different hardware with a base install of pfSense 2.4.4r2 and ntopng 0.8.13_3 (ntopng Community Edition v.3.6.181116) and the problem is still there, so I believe this bug would affect everyone.

pfSense additional package install for ntopng 0.8.13_3 has some issues with historical graphs in ntopng's interface.

Please note, this bug isn't apparent in older versions. It seems to be related to the graph 'smoothing' change if I were to guess.

In NTOPNG > Interfaces > Historical it's not displaying traffic values correctly, it seems to cap around 10Mbps.

Here's an image explaining my issue: https://i.imgur.com/QjQHeyj.png

1. Ordered by 'Bytes (Traffic)' as you can see the average is 22Mb/s yet the graph doesn't peak any higher than 4.5Mb/s...
2. One of the peaks around 4.3Mb/s which doesn't seem close to correct for 22Mb/s average.
3. Averaging 22Mb/s over time-frame. 
4. 3 clients totaling over 4.3Mb/s yet only showing under 4.3Mb/s on the graph. 
Similar image using a 3-hour graph instead of 5 minutes, https://i.imgur.com/CIHfmGK.png

As you can see the says 3Mb/s 'average' according to the graph, but on the right, it's reading the correct average of 19Mb/s.

It seems since the latest update where the 'peaks' are 'smoothed'(?) it hasn't been displaying correctly, unfortunately.

Bugzilla FreeBSD Report: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=236716
pfSense Report: https://redmine.pfsense.org/issues/9143
Netgate Report: https://forum.netgate.com/topic/137960/issue-ntopng-not-displaying-values-in-historical-correctly

**Comment by emanuele-f** [comment]
Hi, the 3.6 version is the old stable, we cannot provide support for it. Please update (or ask the package maintainers to update) to the new 3.8 stable and check if the problem is still present

**Comment by emanuele-f** [comment]
Please reopen if necessary after update.
