### ISSUE TITLE
Chrome/Vivaldi login bounce back

### ISSUE THREAD

**Issue by basicmonkey** [ntop/ntopng#2482]
I'm unable to log into ntopng Enterprise Edition v.3.9.190325 using Vivaldi (Chromium based) 2.3.1440.61 (Stable channel) (64-bit).

Every time I log in, I'm immediately bounced back to the login screen.

I've tried deleting path and domain cookies, disabling cookies etc. Login via Safari and Firefox works perfectly.

ntop-ng is behind a reverse proxy, but the same issue occurs when accessing it directly by port.

**Comment by emanuele-f** [comment]
Hi, I use chromium and I can login without problems, are you accessing multiple ntopng sites from the same browser? Can you see inspect the ajax response from ntopng (via wireshark or developer console) and see if ntopng is kicking you out? This should be the relevant js code that redirect you to the login (footer.lua):

`if((response.status == 403) && (response.responseText == "Login Required")) window.location.href = ...`

**Comment by basicmonkey** [comment]
Hi Emanuele,
Very strange, but after a few refreshes with developer tools open and network monitor tracking, i successfully logged into dashboard and then logged out again. Now I can log in successfully.
Before, I would sometimes see a flash of the dashboard and then back to login.
I'll keep playing and come back to you.
Thank you.

**Comment by basicmonkey** [comment]
It's bouncing back again now, unable to log in.
I can't seem to see the response that's causing the bounce in the network console.

**Comment by basicmonkey** [comment]
I'm seeing some 302 errors. Can't work out why sometimes it's working, others not.
<img width="913" alt="Screenshot 2019-03-26 at 13 25 53" src="https://user-images.githubusercontent.com/392058/55000579-b595eb00-4fca-11e9-8526-cb3146bea882.png">

**Comment by basicmonkey** [comment]
On this attempt, I see a flash of dashboard before being kicked out again.
<img width="825" alt="Screenshot 2019-03-26 at 13 31 58" src="https://user-images.githubusercontent.com/392058/55000993-964b8d80-4fcb-11e9-8b67-4cb6942ce8c0.png">

**Comment by cardigliano** [comment]
@basicmonkey I run some test with Vivaldi and it's working for me. You said that you tried disabled cookies, did you re-enable them? Please note that ntopng authentication does not work without cookies.

**Comment by basicmonkey** [comment]
@cardigliano They are re-enabled. I'm going to try vanilla Chrome and see if that performs differently. A new private window in Vivaldi doesn't seem to work either.

**Comment by basicmonkey** [comment]
Vanilla Chrome seems to be ok. Just my install of Vivaldi. Repeated cache clears and cookie removals didn't fix, but removing ProxyPassReverse from Apache config seems to have resolved it now for the proxy access.

**Comment by basicmonkey** [comment]
Not working again today, either via proxied address or port 3000. Any suggestions on how to debug this are much welcome.

**Comment by simonemainardi** [comment]
this is for sure an issue with your browser:

- check and disable any extension you may have enabled/installed
- check and make sure cookies are enabled

then if it doesn't work, check again all the network requests made and post here the full details of those that received an error (e.g., the 403 above).

**Comment by basicmonkey** [comment]
It certainly looks like it is just my Vivaldi.

I've tried disabling all extensions, cleared all domain cookies, all cookies are enabled including 3rd parties, cleared cache and application cache. Still the same problem.

It seems I get a 302 when it hits the dashboard.

<img width="933" alt="Screenshot 2019-04-03 at 07 33 14" src="https://user-images.githubusercontent.com/392058/55457996-8d6a4580-55e3-11e9-8cbb-f2fadf0c9aa2.png">

**Comment by basicmonkey** [comment]
Interestingly, going in via IP and port seems to work. Going in via apache proxy or hostname and port fails. Is there somewhere else Vivaldi keeps old redirects? I'm trying to avoid clearing absolutely everything but it seems that way.

Edit: I've created a new hostname (ntop2.basic) and added as a ServerAlias to my Apache config. All works well. Must be some stuck redirect in Vivaldi, any suggestions how to get rid of it without a full settings wipe would be much appreciated!

**Comment by simonemainardi** [comment]
can you try and do a fresh install of vivaldi  on the same or on a different machine and see?

unfortunately your issue isn't reproducible

**Comment by simonemainardi** [comment]
any news?

**Comment by basicmonkey** [comment]
I've done a manual clear-out of Vivaldi. Using the 'Delete Browsing Data' didn't work, but using a clean set of user data folders I manually reinstated my cookies, history, bookmarks and other settings.

Seems like a redirect got stuck in Vivaldi beyond the obvious cache data.

Many thanks,

James

**Comment by emanuele-f** [comment]
Please check out https://github.com/ntop/ntopng/commit/07702712187347ef448a14647d051c223755b4cd

**Comment by jsuelwald** [comment]
Hi. I've installed ntopng today and i have the exact same issue

Login in via http://<ip>:3000 works, http://<hostname>:3000 fails.
What can i do to give you more information?

**Comment by simonemainardi** [comment]
what's the difference?

**Comment by TheLinuxGuy** [comment]
It's 3/12/2021 and I am experiencing this same issue on vivaldi stable

```

Vivaldi | 3.6.2165.40 (Stable channel) (64-bit)
-- | --
Revision | 0775b179d84cd4afd002ece2f151c13fc1630b94
OS | Windows 10 OS Version 2009 (Build 19042.867)
JavaScript | V8 8.8.278.17
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.186 Safari/537.36

```

**Comment by simonemainardi** [comment]
@TheLinuxGuy what about the ntopng version? Can you check on another browser? Please, also use the vivaldi inspector to see if there are any blocked requests. I am not sure if is it vivaldi policies that are causing this.
