### ISSUE TITLE
Black-hole a DDoS  with BGP

### ISSUE THREAD

**Issue by plankanater** [ntop/ntopng#2485]
Are there any plans to implement auto black-hole with bgp? Or is there a way to do this with the current setup? For example, one host receives way too many flows, then ntop announces that host through BGP to a router as a /32 or /128. That router can then blackhole the /32 or /128. This would also allow Ntop be categorized as a DDoS detection and mitigation software.

**Comment by plankanater** [comment]
How system would stop a DDoS.

DDoS starts - Flows increase to host (Flood Attack Starts)
Ntop sees the increased flows. (either by a hard limit or percentage)
Ntop triggers an alert marking the Hosts IP (Local IP)
Ntop then announces the /32 or /128 to the BGP peer. (can add BGP community but not necessary)
The BGP peer (not Ntop) then black-holes the IP address re-announcing it to upstream routers. 
Ntop then has a hold timer (60 minutes) before it will stop announcing the /32 or /128 allowing traffic to flow to the host again.

Optional features - 
Email notice when something get blocked. 
Separate value in addition to current flood alert values. (that way a small flood will generate an alert but not black-hole the local host) 
Amount of time host remains black-holed can be set by user
Ability to override a host being black-holed.
Could also be a paid plugin for an additional charge.


I think this would allow you to market this to a wider group of customers. Currently we have to run a separate Net-flow server to achieve this.

**Comment by emanuele-f** [comment]
ntopng can already trigger alerts based on the number of generated/received flows, please check out https://www.ntop.org/guides/ntopng/basic_concepts/alerts.html#user-configurable-thresholds . ntopng can also export generated alerts to third party programs (see https://www.ntop.org/guides/ntopng/web_gui/alerts.html#alert-endopints) so your custom program which implements the specific logic described above can receive the ntopng alerts and act as a consequence. This allows ntopng to stay generic and delegates the complexity to an external program.

**Comment by plankanater** [comment]
Would slack or any other endpoint be able to run ssh commands?

**Comment by emanuele-f** [comment]
If you need full scriptability, please consider implementing a new alert endpoint as described here https://github.com/ntop/ntopng/blob/dev/doc/README.alerts#L43 . You can then execute a shell command with `os.execute(...)`
