### ISSUE TITLE
special characters in password

### ISSUE THREAD

**Issue by Byter09** [ntop/ntopng#2490]
Hello,

I saw several issues related to special characters and sadly I can report another one:

Steps to reproduce:
1. change password to `0a!b5Ecd3%eC`
2. log out
3. try to log back in with said password

You'll see that you will now be redirected to the login page again and apparently the given password is wrong.

I'm assuming the problem lies somewhere at the `%` and ntopng trying to decode html chars?
I already tried simpler passwords which only contain the `!` and the `%` but it would appear something about the above sequence is special. As HTML and all the surrounding stuff it not my area of expertise, I sadly can't narrow it down further, as I have no idea what to try next.

I'm running https://hub.docker.com/r/junquera/ntopng which currently is `ntopng Community Edition v.3.8.190308` on docker `18.09.3-ce, build 774a1f4eee` on `5.0.3-1-MANJARO #1 SMP PREEMPT Tue Mar 19 18:26:12 UTC 2019 x86_64 GNU/Linux`.

If any other information is required to solve this, I will provide it.

Thank you for taking the time to look at this.

**Comment by simonemainardi** [comment]
fixed, thanks for reporting
