### ISSUE TITLE
No graphic

### ISSUE THREAD

**Issue by DocSalvager** [ntop/ntopng#2491]
Noob. Just installed 3.8.190204 on antiX Linux 1.71 (64 bit)

But most pages look something like the example attached... just a horozontal bar graph always half full.

![screenshot](https://user-images.githubusercontent.com/3124882/55266086-95c42880-5251-11e9-8e75-111e664ff5b9.png)

What am I doing wrong?

**Comment by simonemainardi** [comment]
right click on the page, then inspect element and check for:

- js errors
- network errors

Also open the ntopng logs and see if there are errors there.

**Comment by emanuele-f** [comment]
@DocSalvager are you running ntopng on localhost or on a different pc? It seems like there is too much latency in the AJAX response from the ntopng response, please use the network inspector of the browser as suggested to confirm this

**Comment by simonemainardi** [comment]
No feedback received. Closing. Reopen with the requested information if necessary.
