### ISSUE TITLE
lua module loading error

### ISSUE THREAD

**Issue by rinchen** [ntop/ntopng#2492]
Ubuntu 18.04 using http://packages.ntop.org/apt/
 ntopng                                       3.9.190331-6423

When starting, ntopng can't find modules that I can confirm are in the modules directory.

> 31/Mar/2019 16:27:03 [NtopPro.cpp:314] [LICENSE] Reading license from Redis
31/Mar/2019 16:07:35 [LuaEngine.cpp:8896] WARNING: Script failure [/usr/share/ntopng/scripts/lua/network_load.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:14: module 'os_utils' not found:]
31/Mar/2019 16:07:35 [LuaEngine.cpp:8896] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_hosts_data.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:14: module 'os_utils' not found:]
31/Mar/2019 16:07:35 [LuaEngine.cpp:8896] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/get_alerts_stats_data.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:14: module 'os_utils' not found:]
31/Mar/2019 16:07:35 [LuaEngine.cpp:8896] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/get_alerts_stats_data.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:14: module 'os_utils' not found:]
31/Mar/2019 16:07:35 [LuaEngine.cpp:8896] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_hosts_data.lua][/usr/share/ntopng/scripts/lua/get_hosts_data.lua:8: module 'discover_utils' not found:]
31/Mar/2019 16:07:35 [LuaEngine.cpp:8473] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:17: module 'page_utils' not found:]
31/Mar/2019 15:22:16 [LuaEngine.cpp:8896] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flow_data.lua][/usr/share/ntopng/scripts/lua/pro/modules/snmp_utils.lua:6: module 'alert_utils' not found:]
31/Mar/2019 15:22:16 [LuaEngine.cpp:8896] WARNING: Script failure [/usr/share/ntopng/scripts/lua/network_load.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:3461: module 'http_lint' not found:]

**Comment by emanuele-f** [comment]
What commands are you using to start ntopng? Latest version works for me on ubuntu 18

**Comment by rinchen** [comment]
`systemctl start`

This may have been transient error after the latest package update. It's never done this before and at the moment it's not occurring after a `systemctl restart`.

**Comment by emanuele-f** [comment]
Fine, I'm closing the issue for now. Should you experience it again please comment this issue again.
