### ISSUE TITLE
Counters on discrete living interfaces (e.g. pppX)

### ISSUE THREAD

**Issue by tronar** [ntop/ntopng#2494]
I'm using ntopng on Ubuntu 16.04, monitoring an edge box with a pppoe
uplink. Sometimes the ppp link fails, and it is "redialed".
All seems fine but some features of ntopng seem to be hooked to the
"old" instance of the interface. In particular, traffic counters stay at 0.
I have not found an way to "refresh" ntopng, tried a HUP but it did not
help (might be because the running process has lowered privs already ?).

So now I'm killing and restarting it. Is there a cleaner way ?
Am I missing something ? 

After some time, I've come to think that the whole thing may be that the if counters return to 0 and ntop is not expecting that, like computing deltas based on the previous counter value which would yield a negative delta, discarded as erroneous ?

**Comment by emanuele-f** [comment]
When the ppp link is refreshed, is the ppp interface seen by the linux sytem destroyed and created again? Apart from the statistics, can you see new flows into the ntopng gui appearing after the refresh? Counters are computed by ntopng based on the traffic so this should not be a problem. Please also check out the `-s` option to avoid dropping privileges

**Comment by tronar** [comment]
The pppd daemon creates the ppp interface, and the old daemon dies, so yes, it's a new interface with the same name.  (Usually because some route vanishes, or modem looses carrier, or whatever, and then the keepalives T/O)

Interestingly, even if packet distribution oscilates, in the app flows window, live flows show "no flows yet".
-s , although seemed promising, does not seem to help. (I verified that ntopng is now running as root, yet no flows are seen after a "redial".

**Comment by emanuele-f** [comment]
I think we need to detect the change and reopen the pcap capture on the interface. I would have expected to receive libpcap errors during pcap_next in such situation though

**Comment by lucaderi** [comment]
We have decided that PPP is not a priority at the moment
