### ISSUE TITLE
Allow new username with a dot

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#2495]
Debian buster
ndpi 2.9.0-1488-c496c79
ntopng 3.9.190401

When adding a new user with a dot in the name such as **username@domain.com**, the user is created as **username@domain**.
Then, **it is impossible to delete it** with the delete button in the edit column.

**Comment by jean-christophe-manciot** [comment]
Restarting the service with the previously saved configuration **/var/lib/ntopng/conf.tar.gz** (without new user) does not remove that user.

**Comment by simonemainardi** [comment]
Browser validators don't let you add special characters in the name, including @ and dots. How are you creating this user?

**Comment by simonemainardi** [comment]
Closing. Currently we are not considering to allow usernames with special characters inside ntopng and the validator doesn't allow such characters. Usernames with special characters can be handled with external logins such as ldap and radius.

**Comment by jean-christophe-manciot** [comment]
@lucaderi 
@emanuele-f

I'm baffled: you're telling us that ntopng cannot accept e-mail address as username, unlike millions of web sites around the world?
Also, I don't know what you mean by ```Browser validators don't let you add special characters in the name, including @ and dots. How are you creating this user?```:
![Adding new ntopng user](https://user-images.githubusercontent.com/13176858/55622153-b6cfd080-579f-11e9-81e0-14922ef85ed0.png)

![Ntopng cropped username](https://user-images.githubusercontent.com/13176858/55622160-bcc5b180-579f-11e9-9fec-024cb10bff38.png)

**Comment by simonemainardi** [comment]
As you can see, the add user button is greyed out, you can't click on it. How did you manage to insert username@domain?

username is not an email how you are used to see when you register to a website. So adding the @ or a dot in the username is not a priority unless we see significant demand from the community.
