### ISSUE TITLE
Implement n2disk inside ntopng

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#2497]
Currently, n2disk is handled as an external service. It is requested to implement it inside ntopng so that it will become easier to dump only certain kinds of packets, such as those belonging to blacklisted connections or suspicious ARP.

**Comment by lucaderi** [comment]
@cardigliano Please decide if this feature still makes sense

**Comment by cardigliano** [comment]
Closing this for the time being as in the meantime n2disk has been tightly integrated, with also the ability to extract traffic matching specific alerts/flows, etc.
