### ISSUE TITLE
ntopng performance in bridge mode

### ISSUE THREAD

**Issue by mydzen** [ntop/ntopng#250]
Hello!
I have PC (i3-4170, MotherBoard Asus Z97e, 2x4GB DDR3-1600, Network Adapter 1Gbit/s) with Ubuntu Server 14.04.
I setup ntopng 2.1.151021 (Professional Edition) and configure it inline mode (PF_RING In-Path Interface (Bump in the Wire)) in my local network.
Before it ping from my workstation to gateway was 1 ms (0.3-0.8 ms).
After installing ntopng inline (all network traffic from my workstation to gateway sends through ntopng) ping is 6-9 ms.
Answer me please – how can I increase performance of ntopng?
Thanks

**Comment by lucaderi** [comment]
Please see https://github.com/ntop/ntopng/blob/dev/doc/README.bridging

**Comment by mydzen** [comment]
Sorry, can you explain me how to "adopt load_hugepages.sh" and "execute ../tools/load_hugepages.sh". Where is this file?

**Comment by lucaderi** [comment]
This is the file https://github.com/ntop/ntopng/blob/dev/tools/load_hugepages.sh
Just modify the interface name with yours and run it from shell

**Comment by lmangani** [comment]
No bug/issues here, closing.

**Comment by mydzen** [comment]
Can you tell me, need I buy some license for ZC mode or "ntopng Pro Small Business" license enough for me?
