### ISSUE TITLE
Sent and Receive Stats are mixed

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2503]
<img width="765" alt="Screenshot 2019-04-02 at 17 53 55" src="https://user-images.githubusercontent.com/4493366/55417171-72aab900-5570-11e9-8462-dc7eee992864.png">

The word "sent" (TCP Packets Sent Analysis) is misleading as
- RX
-- Lost
-- Out of Order

- TX
- Retransmissions
- Keep Alive

In essence it needs to be reworked the meaning and the display of these metrics

**Comment by simonemainardi** [comment]
implemented
