### ISSUE TITLE
Old data not purged from MySQL

### ISSUE THREAD

**Issue by cjwbath** [ntop/ntopng#2507]
Since I upgraded from 3.8.181112 to 3.8.190219 (but this may be coincidence) I have found that old flow data is not being purged from the flow-dump MySQL database in time to stop the disk filling up. I have retention of 7 days set in the Preferences, but I find data up to 2 weeks old in the flowsv4 table when investigating.

Looking at SHOW FULL PROCESSLIST in MySQL I can see the cleanup query get stuck waiting for lock and probably never cleans up anything.

Id | User   | Host      | db     | Command | Time   | State            | Info                                                                                                                                                                      | Progress |
------------------------------------------------------------------------------------------------------------------
| 32 | ntopng | localhost | ntopng | Query   | 729248 | waiting for lock | DELETE FROM flowsv4 where FIRST_SWITCHED < 1552953602 AND (INTERFACE_ID = 2) AND (NTOPNG_INSTANCE_NAME='ntop' OR NTOPNG_INSTANCE_NAME IS NULL OR NTOPNG_INSTANCE_NAME='') |    0.000 |

Is this because there are pretty much continuous writes occurring to the DB? Can ntopng pause the database writes (or even discard them) while the cleanup process is in effect?

Afraid it's pretty hard to troubleshoot any further with a full disk; the tables are now crashed anyway and I probably need disk space to repair them. When this has happened before (once or twice, I ignored it as a possible one-off) I ended up dropping the whole DB and starting again (it's not that important to keep it).

Should I maybe give up on the built in retention and write a cron job that stops ntopng, purges the old data, and starts it again? How does ntopng know when to run the cleanup anyway?

**Comment by emanuele-f** [comment]
The "waiting for lock" seems to be the cause of the issue, please post the full output of `SHOW FULL PROCESSLIST` to see if another query is holding the lock on the flowsv4 table

**Comment by simonemainardi** [comment]
any news?

**Comment by cjwbath** [comment]
Sorry, forgot about this. I will have to recreate the databases and let it fill up again over two weeks and then I will let you know which query is holding the lock.

**Comment by emanuele-f** [comment]
Ok, please let us know

**Comment by cjwbath** [comment]
Just happened again (disk full) and the result of SHOW FULL PROCESSLIST is as follows:

*************************** 1. row ***************************
      Id: 15
    User: ntopng
    Host: localhost
      db: ntopng
 Command: Query
    Time: 159929
   State: update
    Info: INSERT INTO `flowsv4` (VLAN_ID,L7_PROTO,IP_SRC_ADDR,L4_SRC_PORT,IP_DST_ADDR,L4_DST_PORT,PROTOCOL,IN_BYTES,OUT_BYTES,PACKETS,FIRST_SWITCHED,LAST_SWITCHED,INFO,JSON,NTOPNG_INSTANCE_NAME,INTERFACE_ID,PROFILE) VALUES ('0','0','2887461134','6862','2887461139','57697','6','104000','0','2000','1555428807','1555428807','',COMPRESS('{ "8": "172.27.41.14", "12": "172.27.41.19", "7": 6862, "11": 57697, "4": 6, "57590": 0, "57591": "Unknown", "6": 16, "2": 2000, "1": 104000, "24": 0, "23": 0, "22": 1555428807, "21": 1555428807, "json": { "10": "0", "14": "177", "5": "0", "16": "0", "17": "0", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "", "SRC_IP_LOCATION": [ 0.000000, 0.000000 ], "DST_IP_COUNTRY": "", "DST_IP_LOCATION": [ 0.000000, 0.000000 ], "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2',''),('0','0','2887620878','56190','2887620113','9300','6','3000000','0','2000','1555428810','1555428810','',COMPRESS('{ "8": "172.29.153.14", "12": "172.29.150.17", "7": 56190, "11": 9300, "4": 6, "57590": 0, "57591": "Unknown", "6": 16, "2": 2000, "1": 3000000, "24": 0, "23": 0, "22": 1555428810, "21": 1555428810, "json": { "10": "48", "14": "0", "5": "2", "16": "0", "17": "0", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "", "SRC_IP_LOCATION": [ 0.000000, 0.000000 ], "DST_IP_COUNTRY": "", "DST_IP_LOCATION": [ 0.000000, 0.000000 ], "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2',''),('0','0','2887607310','58162','2887608077','9092','6','3000000','0','2000','1555428809','1555428809','',COMPRESS('{ "8": "172.29.100.14", "12": "172.29.103.13", "7": 58162, "11": 9092, "4": 6, "57590": 0, "57591": "Unknown", "6": 16, "2": 2000, "1": 3000000, "24": 0, "23": 0, "22": 1555428809, "21": 1555428809, "json": { "10": "176", "14": "178", "5": "0", "16": "0", "17": "0", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "", "SRC_IP_LOCATION": [ 0.000000, 0.000000 ], "DST_IP_COUNTRY": "", "DST_IP_LOCATION": [ 0.000000, 0.000000 ], "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2',''),('0','91','3632299311','443','182731569','54150','6','64','0','1','1555428794','1555428794','',COMPRESS('{ "8": "216.128.125.47", "12": "10.228.67.49", "7": 443, "11": 54150, "4": 6, "57590": 91, "57591": "SSL", "6": 0, "2": 1, "1": 64, "24": 0, "23": 0, "22": 1555428794, "21": 1555428794, "json": { "10": "24", "14": "0", "5": "0", "16": "30142", "17": "0", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "US", "SRC_IP_LOCATION": [ -97.821999, 37.750999 ], "DST_IP_COUNTRY": "", "DST_IP_LOCATION": [ 0.000000, 0.000000 ], "PROFILE": "Secret Network", "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2','Secret Network'),('0','7','1750226028','80','182732809','64533','6','2543','0','6','1555428791','1555428791','',COMPRESS('{ "8": "104.82.84.108", "12": "10.228.72.9", "7": 80, "11": 64533, "4": 6, "57590": 7, "57591": "HTTP", "6": 0, "2": 6, "1": 2543, "24": 0, "23": 0, "22": 1555428791, "21": 1555428791, "json": { "10": "24", "14": "0", "5": "0", "16": "16625", "17": "0", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "NL", "SRC_IP_LOCATION": [ 4.899500, 52.382401 ], "DST_IP_COUNTRY": "", "DST_IP_LOCATION": [ 0.000000, 0.000000 ], "PROFILE": "Secret Network", "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2','Secret Network'),('0','91','34815706','443','182734047','57659','6','8453','0','14','1555428792','1555428792','',COMPRESS('{ "8": "2.19.62.218", "12": "10.228.76.223", "7": 443, "11": 57659, "4": 6, "57590": 91, "57591": "SSL", "6": 0, "2": 14, "1": 8453, "24": 0, "23": 0, "22": 1555428792, "21": 1555428792, "json": { "10": "24", "14": "0", "5": "0", "16": "20940", "17": "0", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "", "SRC_IP_LOCATION": [ 8.000000, 47.000000 ], "DST_IP_COUNTRY": "", "DST_IP_LOCATION": [ 0.000000, 0.000000 ], "PROFILE": "Secret Network", "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2','Secret Network'),('0','5','167839130','53','182732323','60673','17','1764','0','4','1555428736','1555428746','',COMPRESS('{ "8": "10.1.5.154", "12": "10.228.70.35", "7": 53, "11": 60673, "4": 17, "57590": 5, "57591": "DNS", "2": 4, "1": 1764, "24": 0, "23": 0, "22": 1555428736, "21": 1555428746, "json": { "10": "24", "14": "0", "5": "0", "16": "0", "17": "0", "130": "x.x.x.x" }, "SRC_IP_COUNTRY": "", "SRC_IP_LOCATION": [ 0.000000, 0.000000 ], "DST_IP_COUNTRY": "", "DST_IP_LOCATION": [ 0.000000, 0.000000 ], "PROFILE": "Secret Network", "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2','Secret Network'),('0','91','1298144279','59945','2317746625','443','6','922000','0','2000','1555428807','1555428807','',COMPRESS('{ "8": "77.96.28.23", "12": "x.x.x.x", "7": 59945, "11": 443, "4": 6, "57590": 91, "57591": "SSL", "6": 24, "2": 2000, "1": 922000, "24": 0, "23": 0, "22": 1555428807, "21": 1555428807, "json": { "10": "47", "14": "0", "5": "0", "16": "5089", "17": "786", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "GB", "SRC_IP_LOCATION": [ -2.324100, 51.393398 ], "DST_IP_COUNTRY": "GB", "DST_IP_LOCATION": [ -2.361700, 51.375099 ], "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2',''),('0','0','2887167549','10001','2317754250','54563','6','747206','0','15461','1555428806','1555428817','',COMPRESS('{ "8": "172.22.174.61", "12": "x.x.x.x", "7": 10001, "11": 54563, "4": 6, "57590": 0, "57591": "Unknown", "6": 24, "2": 15461, "1": 747206, "24": 0, "23": 0, "22": 1555428806, "21": 1555428817, "json": { "10": "0", "14": "47", "5": "0", "16": "0", "17": "786", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "", "SRC_IP_LOCATION": [ 0.000000, 0.000000 ], "DST_IP_COUNTRY": "GB", "DST_IP_LOCATION": [ -2.361700, 51.375099 ], "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2',''),('0','5','167839129','53','182731330','2182','17','401','0','1','1555428748','1555428748','',COMPRESS('{ "8": "10.1.5.153", "12": "10.228.66.66", "7": 53, "11": 2182, "4": 17, "57590": 5, "57591": "DNS", "2": 1, "1": 401, "24": 0, "23": 0, "22": 1555428748, "21": 1555428748, "json": { "10": "24", "14": "0", "5": "0", "16": "0", "17": "0", "130": "x.x.x.x" }, "SRC_IP_COUNTRY": "", "SRC_IP_LOCATION": [ 0.000000, 0.000000 ], "DST_IP_COUNTRY": "", "DST_IP_LOCATION": [ 0.000000, 0.000000 ], "PROFILE": "Secret Network", "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2','Secret Network'),('0','0','2887614993','46692','2887620628','9092','6','410000','0','2000','1555428807','1555428807','',COMPRESS('{ "8": "172.29.130.17", "12": "172.29.152.20", "7": 46692, "11": 9092, "4": 6, "57590": 0, "57591": "Unknown", "6": 24, "2": 2000, "1": 410000, "24": 0, "23": 0, "22": 1555428807, "21": 1555428807, "json": { "10": "0", "14": "48", "5": "2", "16": "0", "17": "0", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "", "SRC_IP_LOCATION": [ 0.000000, 0.000000 ], "DST_IP_COUNTRY": "", "DST_IP_LOCATION": [ 0.000000, 0.000000 ], "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2',''),('0','0','2887614482','53096','2887620116','9092','6','9104000','0','8000','1555428810','1555428811','',COMPRESS('{ "8": "172.29.128.18", "12": "172.29.150.20", "7": 53096, "11": 9092, "4": 6, "57590": 0, "57591": "Unknown", "6": 16, "2": 8000, "1": 9104000, "24": 0, "23": 0, "22": 1555428810, "21": 1555428811, "json": { "10": "176", "14": "178", "5": "2", "16": "0", "17": "0", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "", "SRC_IP_LOCATION": [ 0.000000, 0.000000 ], "DST_IP_COUNTRY": "", "DST_IP_LOCATION": [ 0.000000, 0.000000 ], "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2',''),('0','0','2887461139','6915','2887461140','59565','6','366000','0','2000','1555428806','1555428806','',COMPRESS('{ "8": "172.27.41.19", "12": "172.27.41.20", "7": 6915, "11": 59565, "4": 6, "57590": 0, "57591": "Unknown", "6": 24, "2": 2000, "1": 366000, "24": 0, "23": 0, "22": 1555428806, "21": 1555428806, "json": { "10": "48", "14": "0", "5": "0", "16": "0", "17": "0", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "", "SRC_IP_LOCATION": [ 0.000000, 0.000000 ], "DST_IP_COUNTRY": "", "DST_IP_LOCATION": [ 0.000000, 0.000000 ], "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2',''),('0','167','2317754300','58835','2317754070','1521','6','114000','322000','4000','1555428805','1555428808','',COMPRESS('{ "8": "x.x.x.x", "12": "x.x.x.x", "7": 58835, "11": 1521, "4": 6, "57590": 167, "57591": "Oracle", "6": 24, "2": 2000, "1": 114000, "24": 2000, "23": 322000, "22": 1555428805, "21": 1555428808, "json": { "10": "0", "14": "48", "5": "2", "16": "786", "17": "786", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "GB", "SRC_IP_LOCATION": [ -2.361700, 51.375099 ], "DST_IP_COUNTRY": "GB", "DST_IP_LOCATION": [ -2.361700, 51.375099 ], "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2',''),('0','91','2317746225','443','2317773422','60637','6','142000','0','2000','1555428809','1555428809','',COMPRESS('{ "8": "x.x.x.x", "12": "x.x.x.x", "7": 443, "11": 60637, "4": 6, "57590": 91, "57591": "SSL", "6": 24, "2": 2000, "1": 142000, "24": 0, "23": 0, "22": 1555428809, "21": 1555428809, "json": { "10": "176", "14": "181", "5": "0", "16": "786", "17": "786", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "GB", "SRC_IP_LOCATION": [ -2.361700, 51.375099 ], "DST_IP_COUNTRY": "GB", "DST_IP_LOCATION": [ -2.361700, 51.375099 ], "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2',''),('0','91','34815706','443','182734047','57660','6','8453','0','14','1555428792','1555428792','',COMPRESS('{ "8": "2.19.62.218", "12": "10.228.76.223", "7": 443, "11": 57660, "4": 6, "57590": 91, "57591": "SSL", "6": 0, "2": 14, "1": 8453, "24": 0, "23": 0, "22": 1555428792, "21": 1555428792, "json": { "10": "24", "14": "0", "5": "0", "16": "20940", "17": "0", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "", "SRC_IP_LOCATION": [ 8.000000, 47.000000 ], "DST_IP_COUNTRY": "", "DST_IP_LOCATION": [ 0.000000, 0.000000 ], "PROFILE": "Secret Network", "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2','Secret Network'),('0','0','2887620880','9300','2887620112','33280','6','104000','48290000','36000','1555428811','1555428831','',COMPRESS('{ "8": "172.29.153.16", "12": "172.29.150.16", "7": 9300, "11": 33280, "4": 6, "57590": 0, "57591": "Unknown", "6": 24, "2": 2000, "1": 104000, "24": 34000, "23": 48290000, "22": 1555428811, "21": 1555428831, "json": { "10": "0", "14": "178", "5": "2", "16": "0", "17": "0", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "", "SRC_IP_LOCATION": [ 0.000000, 0.000000 ], "DST_IP_COUNTRY": "", "DST_IP_LOCATION": [ 0.000000, 0.000000 ], "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2',''),('0','178','922131618','443','182733925','51295','6','2040','0','10','1555428735','1555428794','',COMPRESS('{ "8": "54.246.156.162", "12": "10.228.76.101", "7": 443, "11": 51295, "4": 6, "57590": 178, "57591": "SSL.Amazon", "6": 0, "2": 10, "1": 2040, "24": 0, "23": 0, "22": 1555428735, "21": 1555428794, "json": { "10": "24", "14": "0", "5": "0", "16": "16509", "17": "0", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "IE", "SRC_IP_LOCATION": [ -6.248900, 53.333099 ], "DST_IP_COUNTRY": "", "DST_IP_LOCATION": [ 0.000000, 0.000000 ], "PROFILE": "Secret Network", "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2','Secret Network'),('0','178','886597107','80','182733096','46980','6','990','0','5','1555428767','1555428792','',COMPRESS('{ "8": "52.216.101.243", "12": "10.228.73.40", "7": 80, "11": 46980, "4": 6, "57590": 178, "57591": "HTTP.Amazon", "6": 0, "2": 5, "1": 990, "24": 0, "23": 0, "22": 1555428767, "21": 1555428792, "json": { "10": "24", "14": "0", "5": "0", "16": "16509", "17": "0", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "US", "SRC_IP_LOCATION": [ -77.472801, 39.048100 ], "DST_IP_COUNTRY": "", "DST_IP_LOCATION": [ 0.000000, 0.000000 ], "PROFILE": "Secret Network", "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2','Secret Network'),('0','91','2317758484','443','2887021124','32806','6','3000000','0','2000','1555428809','1555428809','',COMPRESS('{ "8": "x.x.x.x", "12": "172.20.114.68", "7": 443, "11": 32806, "4": 6, "57590": 91, "57591": "SSL", "6": 16, "2": 2000, "1": 3000000, "24": 0, "23": 0, "22": 1555428809, "21": 1555428809, "json": { "10": "171", "14": "137", "5": "0", "16": "786", "17": "0", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "GB", "SRC_IP_LOCATION": [ -2.361700, 51.375099 ], "DST_IP_COUNTRY": "", "DST_IP_LOCATION": [ 0.000000, 0.000000 ], "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2',''),('0','0','2887620627','9300','2887620370','40064','6','370000','57104000','46000','1555428770','1555428850','',COMPRESS('{ "8": "172.29.152.19", "12": "172.29.151.18", "7": 9300, "11": 40064, "4": 6, "57590": 0, "57591": "Unknown", "6": 24, "2": 6000, "1": 370000, "24": 40000, "23": 57104000, "22": 1555428770, "21": 1555428850, "json": { "10": "0", "14": "178", "5": "2", "16": "0", "17": "0", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "", "SRC_IP_LOCATION": [ 0.000000, 0.000000 ], "DST_IP_COUNTRY": "", "DST_IP_LOCATION": [ 0.000000, 0.000000 ], "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2',''),('0','7','167839149','80','182731101','56684','6','64','0','1','1555428792','1555428792','',COMPRESS('{ "8": "10.1.5.173", "12": "10.228.65.93", "7": 80, "11": 56684, "4": 6, "57590": 7, "57591": "HTTP", "6": 0, "2": 1, "1": 64, "24": 0, "23": 0, "22": 1555428792, "21": 1555428792, "json": { "10": "24", "14": "0", "5": "0", "16": "0", "17": "0", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "", "SRC_IP_LOCATION": [ 0.000000, 0.000000 ], "DST_IP_COUNTRY": "", "DST_IP_LOCATION": [ 0.000000, 0.000000 ], "PROFILE": "Secret Network", "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2','Secret Network'),('0','41','2317768117','53732','2317749349','445','6','264000','0','2000','1555428810','1555428810','',COMPRESS('{ "8": "x.x.x.x", "12": "x.x.x.x", "7": 53732, "11": 445, "4": 6, "57590": 41, "57591": "SMBv23", "6": 24, "2": 2000, "1": 264000, "24": 0, "23": 0, "22": 1555428810, "21": 1555428810, "json": { "10": "2", "14": "33", "5": "0", "16": "786", "17": "786", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "GB", "SRC_IP_LOCATION": [ -2.361700, 51.375099 ], "DST_IP_COUNTRY": "GB", "DST_IP_LOCATION": [ -2.361700, 51.375099 ], "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2',''),('0','91','2317758484','443','2887044110','52556','6','3000000','0','2000','1555428810','1555428810','',COMPRESS('{ "8": "x.x.x.x", "12": "172.20.204.14", "7": 443, "11": 52556, "4": 6, "57590": 91, "57591": "SSL", "6": 16, "2": 2000, "1": 3000000, "24": 0, "23": 0, "22": 1555428810, "21": 1555428810, "json": { "10": "37", "14": "2", "5": "0", "16": "786", "17": "0", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "GB", "SRC_IP_LOCATION": [ -2.361700, 51.375099 ], "DST_IP_COUNTRY": "", "DST_IP_LOCATION": [ 0.000000, 0.000000 ], "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2',''),('0','91','168100353','443','182732034','60417','6','258','0','4','1555428794','1555428794','',COMPRESS('{ "8": "10.5.2.1", "12": "10.228.69.2", "7": 443, "11": 60417, "4": 6, "57590": 91, "57591": "SSL", "6": 0, "2": 4, "1": 258, "24": 0, "23": 0, "22": 1555428794, "21": 1555428794, "json": { "10": "24", "14": "0", "5": "0", "16": "0", "17": "0", "130": "x.x.x.x" }, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "", "SRC_IP_LOCATION": [ 0.000000, 0.000000 ], "DST_IP_COUNTRY": "", "DST_IP_LOCATION": [ 0.000000, 0.000000 ], "PROFILE": "Secret Network", "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "tcp:\/\/127.0.0.1:5556" }'), 'ntop', '2','Secret Network')
Progress: 0.000

*************************** 2. row ***************************
      Id: 32
    User: ntopng
    Host: localhost
      db: ntopng
 Command: Query
    Time: 133188
   State: Waiting for table level lock
    Info: DELETE FROM flowsv4 where FIRST_SWITCHED < 1554850804 AND (INTERFACE_ID = 2) AND (NTOPNG_INSTANCE_NAME='ntop' OR NTOPNG_INSTANCE_NAME IS NULL OR NTOPNG_INSTANCE_NAME='')
Progress: 0.000

So yes there is an insert getting stuck that has locked up the table. Going by the run time that was started 2 days ago. 

Looking at the flowsv4 table right now now the minimum FIRST_SWITCHED is 2019-04-09 10:09:51 and the max is  2019-04-16 16:33:3, so I think maybe I don't have enough disk space for 7 days of flows after all and the insert is getting stuck (because there is no space) and prevents the cleanup from working to reclaim any.

I will try lowering the retention period to 5 days.

**Comment by simonemainardi** [comment]
ok, please do that and let us know what happens if you lower to 5 days. It seems that new inserts get stuck as the disk is full and, consequently, also the delete blocks waiting for the insert to complete.

**Comment by emanuele-f** [comment]
@cjwbath any update?

**Comment by cjwbath** [comment]
Yes, that's all it was, sorry for wasting your time.
