### ISSUE TITLE
Unable to create interface to PCAP file

### ISSUE THREAD

**Issue by HBadger0017** [ntop/ntopng#2509]
Hey gang...
I am comparing capabilities between ELK and NTOPNG in Docker containers.  My understanding of Docker is good but I am still new.

I am running this command inside an Ubuntu VM (from the directory where the pcap is stored) ==>

docker run --name=NTOPNG -v ~/PCAP:/mnt/Data -p 3000:3000 --net=host -it lucaderi/ntopng-docker --community -i TriTon.pcap

I am getting this error output ==>
WARNING: Published ports are discarded when using host network mode
Starting redis-server: redis-server.
04/Apr/2019 20:26:05 [Ntop.cpp:994] Setting local networks to 127.0.0.0/8
04/Apr/2019 20:26:05 [Redis.cpp:106] Successfully connected to redis 127.0.0.1:6379@0
04/Apr/2019 20:26:05 [main.cpp:190] ERROR: Unable to create interface TriTon.pcap
04/Apr/2019 20:26:05 [main.cpp:223] ERROR: Startup error: missing super-user privileges ?

Is there something simple that I am overlooking?  I looked into how to read a pcap into NTOPNG but was not as successful as I would have hoped.  This is 'Day 1' with NTOPNG for me so may be concepts I still need to learn.  Other things I have tried was not use -v and use full path to the pcap file.  Permissions are good on the file and my user is part of the su group.

Thanks in advance.

**Comment by simonemainardi** [comment]
Try and specify the full path to `TriTon.pcap`, I'm assuming its located inside the container under `/mnt/Data`.

If you can't find it, enter the container with a shell, then locate the file and try to start ntopng from the shell.

See this if you need to know how to enter the container in a shell: `https://github.com/simonemainardi/ntopng-docker`

**Comment by simonemainardi** [comment]
any news here? did you try with the suggestions?

**Comment by HBadger0017** [comment]
I haven't had a chance to poke at it last couple of days but will let you
know.  Thanks.

-Matthew KW

**Comment by simonemainardi** [comment]
Please, re-open with the requested information when ready. Thank you.

**Comment by q2dg** [comment]
I'm having the same error but using a real net interface and podman instead of docker:

_sudo podman container run -it --net=host -p 3000:3000 ntop/ntopng:stable --community -i enp0s3_
