### ISSUE TITLE
Create daily report of web sites visited by local hosts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#251]
For each local host, ntopng administrator can enable the generation of a daily report of visited web sites.

**Comment by PrimaryHealthTas** [comment]
This will be a wonderful feature Luca. Assuming I have not read this post incorrectly and it's not already available? These reports are exactly what I need in a product like ntopng to provide to management but are currently unable to. Thank you.

**Comment by Krokx** [comment]
Would love to see that feature.

**Comment by lucaderi** [comment]
@PrimaryHealthTas @Krokx We've not forgot this issue, just preparing the code. Stay tuned.

**Comment by emanuele-f** [comment]
Right now ntopng holds top 5 minutes sites for local hosts. The daily view could be implemented by keeping an additional set of sites and merging the 5 minutes top sites (possibly extended to be a 15 minutes top sites) into the daily sites. Additionally, daily sites could be stored on SQLite to provide historical exploration
