### ISSUE TITLE
(Almost) Useless SSL Alerts Certificate Mismatch

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2510]
![image](https://user-images.githubusercontent.com/4493366/55607516-ace8a600-577c-11e9-9216-27f6970cd1e0.png)
The above alert is almost useless as it is not clear what is the problem being reported. Please list
- requested client certificate
- offered server certificates

**Comment by simonemainardi** [comment]
![image](https://user-images.githubusercontent.com/3397663/55642107-d7178380-57cf-11e9-9840-e99f7518328e.png)
