### ISSUE TITLE
Invalid blacklist alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2511]
![image](https://user-images.githubusercontent.com/4493366/55608279-6a27cd80-577e-11e9-8370-7a1d3b2d8683.png)
The above alert is not very helpful as
- it is not clear if the issue is related to the client or server host
- the statement "Client, server or domain is blacklisted" lacks of domain in the description of the flow and it is too vague
The alert *must* report
- what is the host that violated the policy (client or server)
- add the domain to the flow description or remove it
- put a blacklist icon next to the invalid host as happens in other alert types

**Comment by simonemainardi** [comment]
![image](https://user-images.githubusercontent.com/3397663/55631469-69139200-57b8-11e9-8ebf-c407696f3138.png)

Now the message explicitly tells if it's the client, the server or the category malware that generated the alert - or a combination of them.

**Comment by EpiqSty** [comment]
Hi,

We're faced with the same error:

> Jun 24 16:42:06 dc1voipsniffer01 ntopng[22843]: [24/06/2019 16:42:06][Error][Blacklisted Flow][Flow] Client, server or domain is blacklisted [Flow: 158.176.27.186@98:56866 ber-sip01@98:9090] [L4 Protocol: TCP]
Jun 24 16:42:27 dc1voipsniffer01 ntopng[22843]: [24/06/2019 16:42:26][Error][Blacklisted Flow][Flow] Client, server or domain is blacklisted [Flow: 158.176.27.186@98:56866 123.122.149.191@98:33333] [L4 Protocol: TCP]
Jun 24 16:42:51 dc1voipsniffer01 ntopng[22843]: [24/06/2019 16:42:51][Error][Blacklisted Flow][Flow] Client, server or domain is blacklisted [Flow: 181.122.45.160@98:53091 ber-sip01@98:30008] [L4 Protocol: TCP]
Jun 24 16:44:21 dc1voipsniffer01 ntopng[22843]: [24/06/2019 16:44:21][Error][Blacklisted Flow][Flow] Client, server or domain is blacklisted [Flow: 158.176.27.42@98:49422 123.122.149.190@98:2051] [L4 Protocol: TCP]

Is that fix released already? 

Our version is:

> $ apt-cache policy ntopng
ntopng:
  Installed: 3.8.190621-6928
  Candidate: 3.8.190621-6928
  Version table:
 *** 3.8.190621-6928 500
        500 http://packages.ntop.org/apt-stable/stretch x64/ Packages
        100 /var/lib/dpkg/status

Thanks in advance!

**Comment by EpiqSty** [comment]
btw, AFAIK, those blacklists are managed via [Category Lists / Blacklists](https://www.ntop.org/guides/ntopng/advanced_features/category_lists.html), but how could we know by given log ( see https://github.com/ntop/ntopng/issues/2511#issuecomment-505043081), which certain blacklist was matched with mentioned 

> Client, server or domain is blacklisted

?
This is not really clear.
