### ISSUE TITLE
Implement alarm mitigation facility

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2515]
![image](https://user-images.githubusercontent.com/4493366/55645884-0e8b2d80-57da-11e9-8cf5-dabba71afef6.png)
The same ARP alert repeats over and over several times. Please avoid re-emitting the same repetitive alert such as for ARP at least for 30 sec/1min

**Comment by simonemainardi** [comment]
Implemented both for flow and past alerts using counters

![image](https://user-images.githubusercontent.com/3397663/56428064-5d4ac400-62be-11e9-871f-6ea5b3514702.png)

![image](https://user-images.githubusercontent.com/3397663/56428077-663b9580-62be-11e9-9164-c4001b210700.png)
