### ISSUE TITLE
Shorten field Info in nIndex Query

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2522]
The Info field in nIndex can be quite long, so it is necessary to implement a shortener for avoiding long field

**Comment by simonemainardi** [comment]
implemented.

long info fields are now forcefully wrapped:

![image](https://user-images.githubusercontent.com/3397663/55788734-2ce27900-5ab9-11e9-91ed-756168a9551a.png)


they are not ellipsized as, when browsing historical data, it is important to have access to the complete field and not to a truncated version
