### ISSUE TITLE
Implement Multiple Allowed Interfaces for user access

### ISSUE THREAD

**Issue by laurentduru** [ntop/ntopng#2525]
Today it's possible to allow access to a specific interface (or networks) for an authenticated user.

I need to have the capability to select multiple interfaces for a user.
I don't want to use the view option that concatenate counters, I need per interface counters.

I already have a request to extend this to ldap and radius authentication. (#2489)

**Comment by simonemainardi** [comment]
We cannot accomodate this request, @laurentduru.

We believe there is enough flexibility in what you can chose to be visible by any of the authorized used.

Indeed, at the finest granularity you can chose the individual networks using the 'Allowed Network' option. At a coarser granularity you have the ability to chose a whole interface to be visible for a given user.

If you are interested in this feature we can discuss a custom development but we cannot do that for the community.
