### ISSUE TITLE
online license check fails

### ISSUE THREAD

**Issue by laurentduru** [ntop/ntopng#2526]
Until yesterday, the online check was working well for two recent ntong instances but now it can't be validated.

If I use the --online-license-check parameters, the license failed in Entreprise time limited.
If I don't use the parameter, the license is Permanent in Pro version

**Comment by cardigliano** [comment]
@laurentduru we fixed a similar issue a couple of hours ago, could you try again please?

**Comment by laurentduru** [comment]
@cardigliano, in version 3.8.190408 it seems working now but not in version 3.8.190324.

**Comment by cardigliano** [comment]
3.8.190324 is not handling the server response correctly, it has been fixed (as you noticed 3.8.190408 is working)

**Comment by laurentduru** [comment]
resolution is confirmed after upgrade to 3.8.190408.

Many thanks
