### ISSUE TITLE
how can I set the sub-protocol ?and which files I should change or increase 

### ISSUE THREAD

**Issue by jiangdu8888** [ntop/ntopng#2529]
for example i want to set  CSDN.net  in SSL   for a sub-protocol , what should i do...

thank you very much fow answering my question

**Comment by emanuele-f** [comment]
The typical way to do this is ntopng is to create a file in the following format https://github.com/caesar0301/pcapdpi/blob/master/protos.txt and use the `-p file_path` of ntopng to load it. In the latest ntopng dev version, we've just implemented an editor of the protocols file, which can be accessed via the following menu entry:
![2019-04-12_09-50](https://user-images.githubusercontent.com/5488003/56020866-ab2c5e80-5cf7-11e9-9308-2fe40777dbd1.png)
but you still need to specify a `-p file_path` parameter in the ntopng configuration before being able to use it. I will document this feature soon.

**Comment by jiangdu8888** [comment]
@emanuele-f  Just   emmmmm     host:"csnd.net"@CSND                ?
                                                        or  "  some thing like? "?
                        
Then  should i write it in ndpi_protocal_ids.h?

**Comment by emanuele-f** [comment]
Yes, that rule is correct, you can also specify new protocol names. No need to edit ndpi, just use `-p protos.txt` with ntopng

**Comment by jiangdu8888** [comment]
@emanuele-f  i appreciate that your help us ! then I have the last question, if i want to change or set  new categories  what should i do

**Comment by emanuele-f** [comment]
Categories can only be edited from the ntopng gui. You can modify the categories from the "Applications and Categories". There are 5 custom categories which are empty by default and you can use as you wish, please check out https://www.ntop.org/guides/ntopng/web_gui/categories.html#custom-category-hosts for more info.
