### ISSUE TITLE
ntopng not switching interfaces

### ISSUE THREAD

**Issue by cbidwell-usgs** [ntop/ntopng#253]
Currently using 
version:   ntopng Professional v.2.0.151021
OS:         Scientific Linux v7.1 64-bit

I've got 4 interfaces that I switch between and after a period of time,
I am no longer able to switch to other interfaces.  It says: 

The selected interface p2p2 [id: 5] is now active
But then it takes me to the dashboard and reverts back to p2p1.  

If I restart ntopng and/or reboot the server, it finally works, but I shouldn't have to do this and it will only work for an unknown period of time.

Can anyone help me with this?  Is this a bug?

**Comment by lucaderi** [comment]
Please use the development version/gitbug code and try to reproduce it.

**Comment by cbidwell-usgs** [comment]
So I'm using the development version of the code and after a couple days it seems to be switching interfaces as expected.  I'd let it go a little longer to see but I really like the professional version and don't see a way to switch to that w/out switching to the rpm-packaged install of ntopng.

**Comment by simonemainardi** [comment]
@cbidwell-usgs could you please confirm that the issue is not affecting the dev version?

**Comment by cbidwell-usgs** [comment]
Yes, it appears to be working as expected on the dev version.

**Comment by simonemainardi** [comment]
ok, thank you for your feedback.

**Comment by cbidwell-usgs** [comment]
Is there a new rpm released by chance that fixes this issue?

**Comment by simonemainardi** [comment]
you can use packaged nightly builds available at http://packages.ntop.org/centos/
