### ISSUE TITLE
Remove UThash leftover and replace it with C++ equivalents

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2533]
ddressTree.h:30:  UT_hash_handle hh; /* makes this structure hashable */
FrequentNumericItems.h:31:  UT_hash_handle hh;         /* makes this structure hashable */
FrequentStringItems.h:31:  UT_hash_handle hh;         /* makes this structure hashable */
FrequentTrafficItems.h:42:  UT_hash_handle hh;         /* makes this structure hashable */
ICMPstats.h:32:  UT_hash_handle hh; /* makes this structure hashable */
MacManufacturers.h:31:  UT_hash_handle hh;
NetworkInterface.h:61:  UT_hash_handle hh;         /* makes this structure hashable */
ntop_typedefs.h:433:  UT_hash_handle hh; /* makes this structure hashable */
ntop_typedefs.h:491:  UT_hash_handle hh; /* makes this structure hashable */

**Comment by simonemainardi** [comment]
UTHASH have been removed from all the community part. They have only been left to manage nEdge policies and, after internal review, we have decided that this is acceptable for the time being. Pro PR referencing nEdge necessary changes is the ea1deef2e0109eb891a576d71dc2dcabac787aa4
