### ISSUE TITLE
See all the applications belonging to a certain category

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#2539]
Add an hyperlink to every number 'Num Applications' in

![image](https://user-images.githubusercontent.com/3397663/56199987-3c743b80-603e-11e9-8705-8d2f1cc44acc.png)

clicking onto that number should bring the user to tab 'Applications' With the corresponding category already selected from the dropdown.

![image](https://user-images.githubusercontent.com/3397663/56200059-59a90a00-603e-11e9-9a87-e63a5b6b481b.png)

**Comment by emanuele-f** [comment]
I would rather add the link in the category column, what do you think?

**Comment by simonemainardi** [comment]
if one wants to find the 'applications' of a certain category, it's a bit more intuitive if he/she finds the link under the column 'applications'
