### ISSUE TITLE
Add originating host/interface ES field

### ISSUE THREAD

**Issue by nconnor** [ntop/ntopng#254]
Hello,

I'm trying to programmatically filter flows in ElasticSearch by the originating ntop-ng host and can't find a field that identifies either the interface or the host; is it relatively simple to add one?

**Comment by lmangani** [comment]
Hi,

Have you tried using the type: field? Should be ideal for filtering purposes
<pre>
es;<b>ntopng_host1</b>;ntopng-%Y.%m.%d;http://localhost:9200/_bulk;
</pre>

**Comment by nconnor** [comment]
Brilliant! Thanks!

**Comment by lmangani** [comment]
@nconnor you're most welcome!
