### ISSUE TITLE
L4 protocol pie chart shows wrong percentages

### ISSUE THREAD

**Issue by aaronjwood** [ntop/ntopng#2544]
![Capture](https://user-images.githubusercontent.com/446283/56474230-c13ecb00-642b-11e9-83a3-797036b1074c.PNG)

You can see that my UDP traffic surpasses my TCP traffic for this host in the table. The chart above doesn't seem to show the data correctly.

**Comment by emanuele-f** [comment]
This is now fixed in de0e24c9f1aa6a6b677477de4f0c78652e3999aa . Thank you for reporting.
