### ISSUE TITLE
lua "Other" parameter error: Validation error

### ISSUE THREAD

**Issue by iluffk** [ntop/ntopng#2545]
Interfaces > historical > Minute Interface Top Talkers Others
click and:

Script "/usr/share/ntopng/scripts/lua/host_details.lua" returned an error:

/usr/share/ntopng/scripts/lua/modules/http_lint.lua:1471: [LINT] _GET["host"] = "Other" parameter error: Validation error

ntopng Community Edition v.3.8.190419
4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by emanuele-f** [comment]
What do  you click in order to trigger the error? "Other" is not clickable in my case:

![2019-04-23_10-21](https://user-images.githubusercontent.com/5488003/56565940-05071100-65a1-11e9-839f-ef0985e9ea8b.png)

**Comment by iluffk** [comment]
![1111111](https://user-images.githubusercontent.com/49871626/56567164-fb8ba200-65bc-11e9-8084-91b8de936ddc.png)

**Comment by emanuele-f** [comment]
Thank you for reporting.

**Comment by iluffk** [comment]
Thanks
