### ISSUE TITLE
General Configuration questions

### ISSUE THREAD

**Issue by tonyfitchburg** [ntop/ntopng#2546]
Currently, we are running a small test on a VM collecting netflow from one router.
Q. If we want to mirror traffic to the system, would we most likely setup Nprobe on its own server (with the appropriate network interfaces)?
Q.  If we are sending netflow from several routers and mirrored traffic and the same flow is received more than once, does Ntop 'de-dupe' the duplicate flows?
Q.  We have about a 150 networks.  Can we add this many networks info the 'conf' file?  Is there a way to add a network description?
Q.  What is the basic difference between a network and a host pool?  Do devices need to be moved 'one at a time' to a host pool?
Q.  We would like to associate other data (fields) from other sources to the flow records.  Is there a way to pull data from other sources, such as a username from a radius log, etc...

**Comment by emanuele-f** [comment]
> Currently, we are running a small test on a VM collecting netflow from one router.
> Q. If we want to mirror traffic to the system, would we most likely setup Nprobe on its own server (with the appropriate network interfaces)?

Please check out https://www.ntop.org/nprobe/network-monitoring-101-a-beginners-guide-to-understanding-ntop-tools . If you use a mirror port than you don't need nprobe. nprobe can run in the same ntopng host.

> Q. If we are sending netflow from several routers and mirrored traffic and the same flow is received more than once, does Ntop 'de-dupe' the duplicate flows?

You can separate the traffic in virtual interfaces by using the netflow exporter IP as discriminant, please check out https://www.ntop.org/guides/ntopng/advanced_features/dynamic_interfaces_disaggregation.html

> Q. We have about a 150 networks. Can we add this many networks info the 'conf' file? Is there a way to add a network description?

You can add the network via the `-m` option in `/etc/ntopng/ntopng.conf`. You can set local networks alias from the ntopng gui (for currently active local networks only).

> Q. What is the basic difference between a network and a host pool? Do devices need to be moved 'one at a time' to a host pool?

Local networks are needed by ntopng to indentify the local hosts (see https://www.ntop.org/guides/ntopng/basic_concepts/hosts.html#local-hosts). An host pool is a convent way to group multiple hosts together, you can add hosts to host pools via a CIDR (network), IP address or MAC address.

> Q. We would like to associate other data (fields) from other sources to the flow records. Is there a 
way to pull data from other sources, such as a username from a radius log, etc...

nProbe has a radius plugin to dissect radius fields (only works if you run nprobe on a mirror port, not from netflow), please check out https://www.ntop.org/guides/nProbe/plugins/index.html . Currently we only support extensions via nProbe plugins.
