### ISSUE TITLE
We are having a problem using or configuring nindex

### ISSUE THREAD

**Issue by tonyfitchburg** [ntop/ntopng#2547]
We want to collect months of flows.  We attempted to enable nindex.  We have added the following lines to our ntopng.conf file: (and restarted)

--dump-flows=nindex

We are getting a 'flow database dump' tab under preferences.  We also see flows under 'top protocols', 'time series', 'interfaces'.  But when we click on any of the options, such as 'top clients', it returns 'no results found'.  We are getting the following errors in the runtime status:

Two error types:
30/Apr/2019 14:33:23 [NIndexFlowDB.cpp:411] WARNING: Unable to open dir /var/lib/ntopng/3/flows

30/Apr/2019 14:31:42 [NIndexFlowDB.cpp:251] WARNING: nindex_add_row failed [Unable to open file]

**Comment by emanuele-f** [comment]
What is the output of `ntopng --version`?

**Comment by tonyfitchburg** [comment]
ntopng --version
v.3.8.190412    [Enterprise/Professional build]
GIT rev:        3.8-stable:facd207308ed862ad114a8d6ddfef7425d62b030:20190412
Pro rev:        r2177
Built on:
System Id:      68BBF5F5.....
Platform:       x86_64
Edition:        Enterprise
License Type:   Permanent
Maintenance:    Until Sun Apr 12 09:16:15 2020 [346 days left]
License:        FyUh1Awn1zxLfVTJAod2xByY5KeZqSKWyj3c5ZOIv8kwvIaPdkgqb3kJuDTXTVfURNLdo
                JJUAEK2Np3.....
License Hash:   0EC8A615F5751B3AE8040.....

**Comment by emanuele-f** [comment]
Please upgrade to the nightly version of ntopng from http://packages.ntop.org as it contains many improvements on nindex over the stable version. Please also flush the existing ntopng data `sudo rm -rf /var/lib/ntopng` while the ntopng service is stopped (with `sudo systemctl stop ntopng`)

**Comment by emanuele-f** [comment]
Should you experience other issue with the dev version, please open a new ticket.
