### ISSUE TITLE
Apply "Changes due to nDPI IPv6 typedef changes" for 2.0-stable branch

### ISSUE THREAD

**Issue by h8h** [ntop/ntopng#255]
Could you please apply your [commit](https://github.com/ntop/ntopng/commit/78175f71d8a1dfd87012c868b0c648b713e18f1f) for the 2.0-stable branch,too? Thank you!

**Comment by simonemainardi** [comment]
Sorry, our release policies do not allow us to cherry pick and drop single commits into stable releases -- unless they fix critical issues. Please, hold on, you will find it in the forthcoming 2.1 release.

**Comment by h8h** [comment]
Thanks! Its not ciritical, but I cannot compile the stable anymore. While compiling the configure says that you need to git clone, make, make install ... the nDPI library. If you do so, compiling the stable will fail.

So actually no one can compile the stable except you clone an older nDPI library.
