### ISSUE TITLE
Fritzdump.sh I see traffic, but no hosts or flows

### ISSUE THREAD

**Issue by NotAWizz** [ntop/ntopng#2552]
Hi Guys
I discovered the existence of NTOPNG today, and I am elated it also runs on MacOS.
The reason for installing it is to troubleshoot bandwidth issues that seem to exist between my Fritzbox and my cablemodem.

I am running the 3.8.190225 community edition on
x86_64-apple-darwin18.2.0 [x86_64][MacOSX 10.14.3] - 64 bit
03/May/2019 19:57:31 [Ntop.cpp:403] Welcome to ntopng x86_64 v.3.8.190225 - (C) 1998-18 ntop.org

The Fritzbox is a 7490 model, running current (unmodified) software.

Because of user rights errors I have augmented the 'wget' line in the fritzdump.sh script as follows:
wget --no-check-certificate -qO- $FRITZIP/cgi-bin/capture_notimeout?ifaceorminor=$IFACE\&snaplen=\&capture=Start\&sid=$SID | ntopng -d /Users/Leo/NTOP/output -G /Users/Leo/NTOP/runtime_stuff/ntopng_PID -i - 

.. so that PID and output all point to directories in my personal space.

In the NTOPNG web interface I do see traffic on stdin, and can look at packet distribution etc, but 
Dashboard screen: Warning: There are no talkers for the current interface
Hosts screen (Send+Recieve): a grey donut. (Donuts shoud be fluffy and jummy!)

What's interesting is that the device counter that sits in the bottom right-hand corner of the screen shows an increasing counter on the number of devices. 25,970 in an upttime of 25 minutes. Over time it drops down, but increases wildly if I run a speedtest from my mac to a speedtest server. So the indication is that the packet data is interpreted as mac addresses because I see a lot of those in the Source Mac Addresses screen.

By comparison, if I run ntopng in 'normal' mode where it will detect the on-board network interfaces everything seems to work just fine.

For investigating this issue I can always resort to using the web interface on the Fritz to start traces on the LAN and Routing interfaces, and start ntopng with -i <pcap name> so my question has little priority.

I have checked the last log traces, no particular errors pop up except maybe:
[NetworkInterface.cpp:125] WARNING: Unable to read IPv4 address of stdin: SIOCGIFADDR: stdin: Device not configured

But at some time later, it logs the stdin interface as id: 10, so I can't as yet determine whether this is meaningful.

If you could shed some light on this, I'd be most grateful though.

Kind regards,
Leo

**Comment by NotAWizz** [comment]
I think I'm onto something.
It would appear that when I trace on the Fritzbox's routed interface the result is Raw Files.
I fired off a trace using the Fritz's web interface and dragged that to my mac. Then I opened it in wireshark and noticed it did not display Ethernet frames. Wireshark was able to extract IP frames so at first I didn't notice. But when I tried to merge a pcap file taken from my mac's ethernet port, Wireshark complained about not being able to merge two different file types.
(appologies on my verbose texts, hope it benefits those that google for the same issue..)
It would explain the behavior me thinks. I'll continue after this weekend.

**Comment by emanuele-f** [comment]
If you can produce a pcap file, you can then use it with both Wireshark and ntopng (-i file.pcap). If with this method ntopng still has the weird behaviour you can send us the pcap file to reproduce and fix the problem

**Comment by NotAWizz** [comment]
@jpluimers has posted a delineation table on GitHub that I am going to use in the fritzdump.sh script. You can find it here: https://github.com/jpluimers/fritzcap/blob/master/fritzcap-interfaces-table.md.

Since my Fritz is connected to the modem via LAN-1 it makes sense to have the script tap this lan interface. I will update this thread next week.

**Comment by NotAWizz** [comment]
Ok, having the fritzdump.sh script look at the eth0 interface on the Fritz did a world of good. My Fritz connects to the cablemodem via the LAN1 port (internally this is eth0)

Modification in the fritzdump.sh script to accomplish that:
`
#This is the WAN interface

#IFACE="2-0"

#Lan Interface
#IFACE="1-lan"
#Leo Says: Let's try this one:

 IFACE="1-eth0"
`
This produces a stream in standard pcap format, and ntopng is purring like a kitten.

Some final notes that may come in handy for users:
At the end of the fritzdump.sh file is a line that starts ntopng.
I have modified that line to get a couple of things happening:
- Read the ntopng config file that lives in my personal user's directory
- add a local interface to be opened by ntopng next to stdin
..as follows:
`wget --no-check-certificate -qO- $FRITZIP/cgi-bin/capture_notimeout?ifaceorminor=$IFACE\&snaplen=\&capture=Start\&sid=$SID |ntopng /Users/Leo/NTOP/ntopng.conf -i - -i4`
where "-i - " refers to stdin
and "-i4" refers to my bridge0 lan interface on my mac.

This is another way of saying that you can start up ntopng pointing to a config file, AND add runtime parameters in the same command.

That's it from me, happy ntopping !

**Comment by emanuele-f** [comment]
Thank you for the information! Would you like to improve https://github.com/ntop/ntopng/blob/dev/doc/README.fritzbox via a pull request?

**Comment by emanuele-f** [comment]
I'm closing this issue, please provide a pull request if possible.
