### ISSUE TITLE
init.d/ntopng doesn't wait long enough before giving up

### ISSUE THREAD

**Issue by draeath** [ntop/ntopng#2553]
On our system, ntopng takes more than 5 seconds to start up and create it's PID file. This causes the init script to report and error, despite ntopng actually starting up and functioning.

This is caused by `for i in {1..5}` in the init script:
https://github.com/ntop/ntopng/blob/7aaf7cf/packages/etc/init.d/ntopng#L170

This should be raised to a more sane maximum timeout, for example `for i in {1..15}`.

Context: running `3.8-stable:bfab18c5d0bd9d931180eb1e2c6587692fc2f88b:20190502` with a Professional license, on RHEL 6 (hence init.d rather than systemd). This issue has been present for a long while, I've just finally gotten annoyed enough at having to "fix" the init script after upgrades that I'm reporting it as an issue.

**Comment by emanuele-f** [comment]
Can you provide a pull request to fix the script?

**Comment by emanuele-f** [comment]
Thank you, please check out the tomorrow package for the fix.
