### ISSUE TITLE
Search results limited to 5

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2556]
<img width="973" alt="image" src="https://user-images.githubusercontent.com/4493366/57284974-876bf680-70b2-11e9-9f27-43b042ff0458.png">
As search results are limited to 5, not all hits are shown. it would be nice in this case
- report that more results have been found
- provide a link to a page with all results so that the correct one can be selected
or 
do anything else to address this limitation

**Comment by simonemainardi** [comment]
it is requested to add 5 results per category, that is:

5 results when searching in SNMP devices mac addresses
5 results when searching in active hosts
etc.
