### ISSUE TITLE
Missing MAC graph from host reports

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2557]
<img width="272" alt="Screenshot 2019-05-07 at 10 30 04" src="https://user-images.githubusercontent.com/4493366/57285273-2690ee00-70b3-11e9-88e3-31cd94ddcf59.png">
From the host graphs it is not possible to select MAC (related to the host) reports. Please add under the list of metrics, those that are related to the MAC belonging to this host. This to avoid long navigation

**Comment by emanuele-f** [comment]
If the serialization by MAC is active this would duplicate the entries, I would avoid mixing MAC and host entries
