### ISSUE TITLE
Multithreading issues when using nProbe and ntopng

### ISSUE THREAD

**Issue by xtrilla** [ntop/ntopng#2559]
Hi,

When using nProbe to capture traffic from optical TAPs and sending the information to ntopng via ZMQ at a rate over 8000 ZMQ messages per second, there seems to be an issue preventing the usage of all the CPU ways available in the machine hosting ntopng.

When running nProbe with:

--zmq "tcp://*:5556"

And ntopng with:

-i=tcp://<nprobeIP>:5556

One of the threads on the ntopng machine is constantly at 100% utilization, and ntopng drops thousands of ZMQ messages per second. But the machine hosting ntopng still has plenty of C`PU available.

In order to maximize the usage of available cores, we tried:

nProbe:

--zmq "tcp://*:5556"
--zmq "tcp://*:5557"
--zmq "tcp://*:5558"
--zmq "tcp://*:5559"

And ntopng with:

-i=tcp://<nprobeIP>:5556
-i=tcp://<nprobeIP>:5557
-i=tcp://<nprobeIP>:5558
-i=tcp://<nprobeIP>:5559
-i=view:tcp://<nprobeIP>:5556,tcp://<nprobeIP>:5557,tcp://<nprobeIP>:5558,tcp://<nprobeIP>:5559

Now, the machine hosting ntopng is using more threads and it can keep up with the ZMQ messages it receives, but there are some issues related to this setup:

- ntopng is showing 4x the number of real hosts in our local network in the bottom center gauge
- local machines are detected as routers
- Several reports don't work as expected (For example in the AS report, we see each AS 4 times).

I understand this is related with ntopng having some kind of non multi-threaded bottleneck, is there any way to fix or improve this?

Thanks!

**Comment by emanuele-f** [comment]
Due to desgin, ntopng uses a single thread per network interface, so the scenario is the one you have highlighted. We are looking at a more efficient format for the messages (see #2562) to improve the performance of a single thread. Using multiple nprobe instances is the correct way to handle the problem, but you need to create 4 different config files and services (e.g. nprobe@probe1, nprobe@probe2 ..), please check out https://www.ntop.org/guides/nProbe/how_to_start.html#systemd-based-systems for more details

**Comment by xtrilla** [comment]
Hi Emanuele,

We are monitoring a optical TAP of a Link Aggregation, meaning:

eth0 - Receives RX of LAG Interface 1
eth1 - Receives TX of LAG Interface 1
eth2 - Receives RX of LAG Interface 2
eth3 - Receives TX of LAG Interface 2

So, for example we could see:

Traffic Flow A OUT traffic - Via eth0 
Traffic Flow A IN traffic -  Via eth1

As I understand, a nProbe instance, should be able to see both IN and OUT traffic in order identify flow beginning, end, etc.

So, as I understand on this scenario we can only have 1 nProbe instance running, but as the issue in  #2562 ntopng cannot keep up with the ZMQ Messages.

I understand this will be fixed at some point, but in the meantime is there anything that we could do to improve the performance on ntopng side or to at least aggregate better the view? Maybe removing some information send by nProbe or changing some parameter in ntopng?

Thanks!

**Comment by emanuele-f** [comment]
What is the ZMQ drop rate you are experiencing? In the case above you could use 2 nprobe instances instead of 4 to improve the load distribution

**Comment by xtrilla** [comment]
Hi Emanuele,

It's quite high, it can only keep up with like 3000 Messages per second, and we have around 8000 or more. So, if we just use one instance it might be dropping more than 5K per second.

The problem is, that as we use for the LAG a load balacing hashing based on MAC, IP, and Port we cannot really know via which interface traffic will come in or go out. That's why we are using just a nProbe instance.

But the nProbe works fine, not load issues there, the issue is the ingestion in ntopng. If we use 4 ZMQ interfaces for message delivery, the ingestion works fine -as we use more of the available cores- but reporting is pretty messed up. 

We've been checking if there is a parameter to change somewhere so traffic is better aggregated in the view that merges all the interfaces. As right now it's quite useless :/

Thanks!

**Comment by emanuele-f** [comment]
Can you try to add the `--zmq-disable-compression` to the nprobe options?

**Comment by xtrilla** [comment]
Hi Emanuele,

We tried, and performance is even worse. I guess the issue is in the library that parses de JSON inside the ZMQ: #2562

But while that gets fixed, is there anything we can do in ntopng side so the resulting view from merging the 4 interfaces reports better?

Thanks.

**Comment by emanuele-f** [comment]
@simonemainardi do you have any suggestions for this?

**Comment by emanuele-f** [comment]
Please refer to #2562
