### ISSUE TITLE
Dump traffic max packet size

### ISSUE THREAD

**Issue by chicocvenancio** [ntop/ntopng#256]
How should the captured packet size be configured?

**Comment by kYroL01** [comment]
If you refers to the maximum MTU packet size, here: https://github.com/ntop/ntopng/blob/dev/include/ntop_defines.h#L342

ntopng is able to accept packets length of 1514 byte

**Comment by chicocvenancio** [comment]
Well, I was referring to limitation I observed when dumping traffic. Some of the details we where hopping to analyse is not captured due to this 1514 bytes limitation. Perhaps this should be mentioned in the guides, or maybe in the dump traffic interface.

For the moment we'll use another tool to capture the traffic.

**Comment by kYroL01** [comment]
I don't know what kind of traffic you have to capture, but is normal to put a limit for the packets we're capturing, also for the morphology of the majority of the networks.
I'm agree with you that we have to report this limitation on the doc; this thing will be done.
So you need to capture many packets larger than 1514 byte, if I understand well.

**Comment by chicocvenancio** [comment]
Well, we started testing ntopng and besides all the great features as networking monitoring tool the very simple dump traffic mechanism is great. We started using it to document some applications behavior and one of the applications uses a lot of packets over 1500 bytes.
Can't we set this as an configuration?

**Comment by kYroL01** [comment]
Which kind of application, if is possibile to know ?
For now, you can change the size manually where I showed you. The MTU is not configurable by the user at the moment.
