### ISSUE TITLE
influxDB for Timeseries

### ISSUE THREAD

**Issue by mmatuska79** [ntop/ntopng#2560]
Hi all,
   we have very similar issue as in #2527. RRD works fine for Timeseries. After change to InfluxDB in Preferences/Timeseries, the timeseries data are not available, despite the fact that the green banner appears and the database `ntopng` is created in influxdb. It seems that no data are written into it.
The historical data icon "graph" are not available in this setup, Traffic Dashboard will not show anything for the 'last day view'.

When I attempt to view 'About NtopNG', the version info for InfluxDB remain blank.
When I attempt to view 'Runtime status', the storage info for InfluxDB remain blank.
In both cases following message is logged:
`[LuaEngine.cpp:9241] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_influxdb_info.lua][...opng/scripts/lua/modules/timeseries/drivers/influxdb.lua:1051: attempt to index a nil value (field 'series')]`

I have tried downgrading influxDB, restarting ntopng and influx, clearing databases etc. Nothing seem to help.

We are having latest stable versions of ntopng and influxdb.
`server# ntopng --version`
`v.3.9.190506    [Enterprise/Professional build]`
`GIT rev:        dev:5bc188b1985291eab13a03c4473d54a309afec87:20190506`
`Pro rev:        r2321`
`Built on:`
`System Id:      68B9F75F76066ACF`
`Platform:       x86_64`
`Edition:        Enterprise`
`License Type:   Permanent`
`Maintenance:    Until Sat May  2 14:35:20 2020 [360 days left]`

`# influx --version`
`InfluxDB shell version: 1.7.6`

Thanks, Miroslav

**Comment by emanuele-f** [comment]
The error above should be fixed in 794d0459a6e9ceae4650a3da85189f779dbc50eb . A new package will be available in one hour, please upgrade and report if you can still experience the other issues. Installing the latest InfluxDB version from the official website is the best option.

**Comment by mmatuska79** [comment]
Thanks for the patch. I have updated via "yum update" to ntopng version `3.9.190510` and I have the same error message:
`May 10 19:53:43 cz11lin005p ntopng: 10/May/2019 19:53:43 [LuaEngine.cpp:9288] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_influxdb_info.lua][...opng/scripts/lua/modules/timeseries/drivers/influxdb.lua:1051: attempt to index a nil value (field 'series')]`
Maybe this is not the fixed version. Sorry for beginners question - how do I update to the version that you patched? Thanks very much.
Miroslav

**Comment by emanuele-f** [comment]
I think this is the old version, please retry with new package now: `sudo yum update`

**Comment by mmatuska79** [comment]
Yes, now it is fixed, thanks. The InfluxDB version shows correctly (1.7.6). 
However it still seems that there are no data written into influxdb from ntopng. Runtime Status returns `NaN Bytes` as InfluxDB Storage.

To test my installation of InfluxDB, I did following excercise:
https://docs.influxdata.com/influxdb/v1.7/query_language/data_download/
It went correctly.

`> SHOW DATABASES`
`name: databases`
`name`
`----`
`_internal`
`NOAA_water_database`
`ntopng`

The results are for example:
`> SELECT sum(last) FROM (SELECT last(diskBytes) FROM _internal.monitor."shard" WHERE "database" = 'NOAA_water_database' GROUP BY id)`
`name: shard`
`time sum`
`---- ---`
`0    242046`

But for ntopng:
`> SELECT sum(last) FROM (SELECT last(diskBytes) FROM _internal.monitor."shard" WHERE "database" = 'ntopng' GROUP BY id)`
There is no result. The historical timeseries are not available, no info for "Last Day Views" in Dashboard etc.

In the influxDB storage directories "data" and "wal", there are subdirectories only for `internal` and `NOAA_water_database`. Nothing for `ntopng`.

Thanks,
Mirek

**Comment by emanuele-f** [comment]
From the ntopng preferences, can you switch to RRD, then back to InfluxDB and see if the database connection is successful? Do you see any export failure alert into ntopng?

**Comment by mmatuska79** [comment]
I have upgraded to version `3.9.190513`. The issue persists ("NaN bytes" used in influxdb storage).

After switching to InfluxDb from RRD, I see following message:
![image](https://user-images.githubusercontent.com/50367563/57631620-1c358f00-75a0-11e9-807e-9c364074cbd9.png)

No error is shown neither in ntopng nor in influxdb log. Following messages are shown:

`May 13 17:11:43 cz11lin005p influxd: [httpd] ::1 - - [13/May/2019:17:11:43 +0200] "GET /ping HTTP/1.1" 204 0 "-" "ntopng 3.9.190513 [x86_64][]" 6b10fac6-7591-11e9-8212-005056b6f15d 45`
`May 13 17:11:43 cz11lin005p influxd: [httpd] ::1 - - [13/May/2019:17:11:43 +0200] "POST /query HTTP/1.1" 200 144 "-" "ntopng 3.9.190513 [x86_64][]" 6b11abf6-7591-11e9-8213-005056b6f15d 242`
`May 13 17:11:44 cz11lin005p influxd: [httpd] ::1 - - [13/May/2019:17:11:43 +0200] "POST /query HTTP/1.1" 200 33 "-" "ntopng 3.9.190513 [x86_64][]" 6b12643e-7591-11e9-8214-005056b6f15d 222824`
`May 13 17:11:51 cz11lin005p influxd: [httpd] ::1 - - [13/May/2019:17:11:51 +0200] "GET /ping HTTP/1.1" 204 0 "-" "ntopng 3.9.190513 [x86_64][]" 6f889e24-7591-11e9-8215-005056b6f15d 37`
`May 13 17:11:51 cz11lin005p influxd: [httpd] ::1 - - [13/May/2019:17:11:51 +0200] "POST /query HTTP/1.1" 200 144 "-" "ntopng 3.9.190513 [x86_64][]" 6f896a9c-7591-11e9-8216-005056b6f15d 183`
`May 13 17:11:51 cz11lin005p influxd: [httpd] ::1 - - [13/May/2019:17:11:51 +0200] "GET /query?db=ntopng&q=SHOW+RETENTION+POLICIES+ON+ntopng HTTP/1.1" 200 242 "-" "ntopng 3.9.190513 [x86_64][]" 6f8a25e3-7591-11e9-8217-005056b6f15d 204`
`May 13 17:11:52 cz11lin005p influxd: [httpd] ::1 - - [13/May/2019:17:11:51 +0200] "POST /query HTTP/1.1" 200 52 "-" "ntopng 3.9.190513 [x86_64][]" 6f8af03a-7591-11e9-8218-005056b6f15d 722113`
`May 13 17:11:53 cz11lin005p influxd: [httpd] ::1 - - [13/May/2019:17:11:52 +0200] "POST /query HTTP/1.1" 200 524 "-" "ntopng 3.9.190513 [x86_64][]" 6ffb38a4-7591-11e9-8219-005056b6f15d 1735550`
`May 13 17:11:55 cz11lin005p influxd: [httpd] ::1 - - [13/May/2019:17:11:53 +0200] "POST /query HTTP/1.1" 200 524 "-" "ntopng 3.9.190513 [x86_64][]" 71055b0a-7591-11e9-821a-005056b6f15d 1991636`
`May 13 17:11:58 cz11lin005p influxd: [httpd] ::1 - - [13/May/2019:17:11:55 +0200] "POST /query HTTP/1.1" 200 524 "-" "ntopng 3.9.190513 [x86_64][]" 72365094-7591-11e9-821b-005056b6f15d 2252047`
`May 13 17:12:00 cz11lin005p influxd: [httpd] ::1 - - [13/May/2019:17:11:58 +0200] "POST /query HTTP/1.1" 200 524 "-" "ntopng 3.9.190513 [x86_64][]" 73912acf-7591-11e9-821c-005056b6f15d 2470642`
`May 13 17:12:03 cz11lin005p influxd: [httpd] ::1 - - [13/May/2019:17:12:00 +0200] "POST /query HTTP/1.1" 200 524 "-" "ntopng 3.9.190513 [x86_64][]" 750b4bd8-7591-11e9-821d-005056b6f15d 2997633`
`May 13 17:12:05 cz11lin005p influxd: [httpd] ::1 - - [13/May/2019:17:12:03 +0200] "POST /query HTTP/1.1" 200 524 "-" "ntopng 3.9.190513 [x86_64][]" 76d5f70f-7591-11e9-821e-005056b6f15d 1492535`
`May 13 17:12:05 cz11lin005p influxd: [httpd] ::1 - - [13/May/2019:17:12:05 +0200] "POST /query HTTP/1.1" 200 52 "-" "ntopng 3.9.190513 [x86_64][]" 77bbcc49-7591-11e9-821f-005056b6f15d 7906`

The same thing happens if the database `ntopng` does not exist in influxdb OR if it is already there (just a name, no data in it).
Should I try to paste some commands inserting data into `ntopng` database influxdb directly via CLI tool influx?

I think that it must be something which occurs right after the Timeseries are switched from RRD to Influx. because the history "graph" icon immediately disappears from the interfaces bar.

With RRD:
![image](https://user-images.githubusercontent.com/50367563/57633438-e4c8e180-75a3-11e9-93f8-0a207824825b.png)

Immediately after switched to influx:
![image](https://user-images.githubusercontent.com/50367563/57633522-032edd00-75a4-11e9-8c84-a313a55f0675.png)

**Comment by emanuele-f** [comment]
Can you try to change the database name into the ntopng influx preferences to a new name, so that ntopng creates the database? Are you using password protected login for influxdb?

**Comment by mmatuska79** [comment]
I have changed the default database name `ntopng` to `timeseries-ntop`. Following errors were logged (multiple times) by ntopng:

`[housekeeping.lua:28] [influxdb.lua:193] ERROR: Bad response code[400]: {"error":"error parsing query: found -, expected ; at line 1, char 38"}`
`[housekeeping.lua:28] [influxdb.lua:248] ERROR: Bad response code[400]: [400] error parsing query: found -, expected DURATION at line 1, char 43`
`[housekeeping.lua:28] [influxdb.lua:1321] ERROR: InfluxDB setup failed`

The same errors are repeating each 3 sec again and again. If I change the database name back to `ntopng`, the error messages stop to appear. If I change the name once more to `timeseries-ntop`, the error message will start to show up again each 3 sec.

I am not using password protection.

**Comment by emanuele-f** [comment]
Please remove the `-` from database name, I will add validation to reject it

**Comment by emanuele-f** [comment]
Validation added in 15cb890b193dc531e4e8b312f03109349660302a

**Comment by mmatuska79** [comment]
OK, the I have used new names `mirekX` where `X` is number for the influxdb database name. No error message with those names. 
However, the behavior is still the same. Green success message appears after the timeseries setting is changed to influxdb. But it seems that no data are written into it regardless of the name. I have tried changing to RRD and back to influxdb multiple times, used both new and old database names. 

I have also stopped influxdb service, deleted all its data files, started again, created `ntopng` an `mirekX` databases again - still the same.

The interesting thing is that even though I have timeseries settings switched to influxdb, small amounts of data are being written into _alerts,_ _top_talkers_ and _ts_export_ directories for each interface (not to influxdb).

**Comment by emanuele-f** [comment]
This is a weird issue, it must be something in the InfluxDB installation. Please ensure that you are setting up InfluxDB in a standard way, you can also try to install it on another clean server.

> The interesting thing is that even though I have timeseries settings switched to influxdb, small amounts of data are being written into alerts, top_talkers and ts_export directories for each interface (not to influxdb).

This is normal, they are not timeseries. ts_export is used internally to export timeseries to InfluxDB.

**Comment by mmatuska79** [comment]
I did following test:
- stop ntopng
- `redis-cli save`
- backup `dump.rdb` to a safe location
- `redis-cli flushdb`
- delete `runtimeprefs.json` from ntopng working directory 
- start ntopng
And after I set up influxDB in Preferences/Timeseries with default name `ntopng`, it suddenly works!
The downside is that I do not have my configuration (a lot of effort has been put into it :-( ).

When I restore original configuration (copying back `dump.rdb` into redis) the problem returns back. What was written to influxDB `ntopng` database during the period of "almost clear configuration" stays there, but no new data are added.

So it must be something in the ntopng configuration which blocks the write operations to influxDB.

No change was made on influxDB during the whole process.

**Comment by emanuele-f** [comment]
Good, let's try to understand the issue. Can you send me your `runtimeprefs.json` at faranda@ntop.org?

**Comment by emanuele-f** [comment]
The preferences seem ok, can you run `sudo journalctl -u influxdb -f` and check if the writes are successful? This is an example of successful write:

```
May 15 11:02:31 lenovo31 influxd[476]: [httpd] ::1 - - [15/May/2019:11:02:31 +0200] "POST /write?db=ntopng HTTP/1.1" 204 0 "-" "-" 2bd62e84-76f0-11e9-801c-f0761cfbf2d8 8555
```

**Comment by mmatuska79** [comment]
No, I cannot see any writes with the current config. That was the main difference yesterday - on the fresh new configuration, I had seen the `POST /write` messages almost immediately and continuously.

With the current config, I can see the `GET /ping`, `GET /query` or `POST /query` messages only.

**Comment by emanuele-f** [comment]
Please also send me via email the new configuration so that I can make a diff of the configurations and see if something comes out. Anyway, I'm closing this as you've solved the issue by starting clean

**Comment by mmatuska79** [comment]
Yes, I have started with fresh configuration and imported the host aliases, interface names and some selected stuff from the previous version and now it works. 
It reports strange numbers regarding influxdb disk usage (3,78 GB reported while all influx files on the disk have 2.6 GB), but I will open different issue on that if it persists.
I am sending you current config via email. 
Thanks for the support.

**Comment by mmatuska79** [comment]
Just FYI for anybody having the same problem with inaccurate influxdb disk usage numbers - I have found out why. The disk usage numbers are now correct.

When starting the "ntopng" influx database again from scratch, you have to:
1/ drop the "ntopng" database in influxdb (I did that before but it is not enough)
2/ remove the associated fields in the "_internal" database in influxdb as well

Since I do not understand the logic of "_internal" database fields, I have dropped it completely and deleted all data files `data`, `meta`, `wal` in the filesystem. After influxdb restart, "_internal" database was recreated again. And then "ntopng" database was created by ntopng. 
Sounds like a too hard reset but it worked for me. If you have non-ntopng data in influx then you obviously need to be more sensitive.

**Comment by emanuele-f** [comment]
Thank you for the comment! I think this will help other users too.
