### ISSUE TITLE
Number of interfaces in GUI

### ISSUE THREAD

**Issue by mmatuska79** [ntop/ntopng#2561]
Hi all, 
    we are using the setup with nProbe in proxy mode (`-i=none`) acting as Netflow UDP data receiver from various routers in the network. nProbe is then generating ZMQ session to ntopng. No local interfaces are monitored with nProbe. This works fine, even with multiple instances of nProbe(s).

We have Enterprise license of ntopng. I understand that 128 interfaces should be supported. When I use Disaggregation Criterion (for example "Probe IP"), each router (NF probe) will get its interface. However, ntopng will stop registering new interfaces after the number reaches 32 - I can only view the first 32 routers that send Netflow exports. Other "interfaces" (routers) are ignored despite the fact that they are sending data as well. After the restart of ntopng process, other 32 routers are picked (the ones that manage to send the NF exports first). 
    Can I somewhat use all 128 interfaces? I understand that this would require really long drop-down list or some kind of table to be usable in the GUI.

Thanks, Miroslav
`# ntopng --version`
`v.3.9.190506    [Enterprise/Professional build]`
`GIT rev:        dev:5bc188b1985291eab13a03c4473d54a309afec87:20190506`
`Pro rev:        r2321`
`Built on:`
`System Id:      68B9F75F76066ACF`
`Platform:       x86_64`
`Edition:        Enterprise`
`License Type:   Permanent`
`Maintenance:    Until Sat May  2 14:35:20 2020 [360 days left]`

**Comment by emanuele-f** [comment]
This is limited by the define MAX_NUM_VIRTUAL_INTERFACES . We will review if increasing the limit is feasible or has drawbacks

**Comment by mmatuska79** [comment]
Thanks for the clarification. I will wait for the upcoming versions if the limit is raised.
Mirek
