### ISSUE TITLE
Using API authorize and get data from customization web application

### ISSUE THREAD

**Issue by sonvodev** [ntop/ntopng#2564]
Hi, 

I am currently having demand to customize ntopng web GUI by developing my web app using ntopng Rest API, but i am getting some issues, those related with #1866 and #2105

I am using pure html and javascript to request to the server to authorize, etc:

`var data = "user=admin&password=Congacon.100";

var xhr = new XMLHttpRequest();

xhr.addEventListener("readystatechange", function () {
  if (this.readyState === 4) {
    console.log(this.responseText);
  }
});

xhr.open("POST", "Http://103.42.57.111:3000/authorize.html");
xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
xhr.setRequestHeader("cache-control", "no-cache");

xhr.send(data);`

But server returns me 302 status code and an error: 

> Access to XMLHttpRequest at 'http://103.42.57.111:3000/authorize.html' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

I really need your quick help, because i dont see any solution from 2 related issue
Thank you for reading and am looking to your help

**Comment by emanuele-f** [comment]
You need to add the CORS HTTP headers to the `sendHTTPHeader` function in `lua_utils.lua`. Please report the working CORS headers so that we can add more documentation on this for other users too

**Comment by sonvodev** [comment]
I followed your recommendation from #1866, added CORS HTTP Headers to sendHTTPHeader in lua_utils.lua line 151 but it same not working
After adding CORS lines, I even cannot use Web GUI, it always redirects to itself

**Comment by emanuele-f** [comment]
Can you share your modifications of the file to review? If you are using git, run `git diff`

**Comment by aaminahassan** [comment]
@sonvodev  I am adding the same CORS issues using web, but not using curl API, please tell us the changings you have made in order to access JSON using API call
