### ISSUE TITLE
Historical explorer

### ISSUE THREAD

**Issue by marekhrbac** [ntop/ntopng#2565]
Hello,
i have a problem. When i want to check some historical details i click on the info button then i see only white page. Could you help me?
![ntop history](https://user-images.githubusercontent.com/50436103/57428313-14848c00-7228-11e9-8fb4-0727bdd48896.png)
![ntop history2](https://user-images.githubusercontent.com/50436103/57428314-14848c00-7228-11e9-853c-80eca6668126.png)

**Comment by emanuele-f** [comment]
This should be fixed in afaa0e041ac69132feb69da6ac7d21ac129d92a3 . The new package will be available in one hour. Please update and check that this is fixed for you too.

**Comment by emanuele-f** [comment]
Closing the issue as the fix seems working, if you have new details please report here
