### ISSUE TITLE
ICMP Echo Alert

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2566]
Generate an alert whenever a ICMP ECHO packet has a lengthy payload that can indicate data exfiltration

**Comment by emanuele-f** [comment]
Implemented in 1c9a4d34619cafb88498d86bb2b43d6da89a16d6 

![2019-05-28_10-21](https://user-images.githubusercontent.com/5488003/58463881-333dba80-8124-11e9-9152-5203c11ef614.png)

![2019-05-28_10-21_1](https://user-images.githubusercontent.com/5488003/58463885-35077e00-8124-11e9-90ec-f38e736d5cb3.png)
