### ISSUE TITLE
Report with DNS Domain name requested on DNS Query request

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#2570]
To identify and analyze the DNS Query seen by ntop.
This can help me on identify new malware o C2C Call back on specific domain.

**Comment by zimbawe998** [comment]
Report with DNS Domain name requested

**Comment by simonemainardi** [comment]
@zimbawe998 would it be OK for you to have a page similar to what are the current http sites?

![image](https://user-images.githubusercontent.com/3397663/57624605-9b23cb00-7592-11e9-816b-6bc462e2c917.png)


so basically the same page but with DNS queries rather than visited sites

**Comment by zimbawe998** [comment]
Thanks Guys. Having it could allow us who is requesting, if i am able to monitor client to server query! Cool feature!

**Comment by emanuele-f** [comment]
@zimbawe998 we will only show the top queries performed by an host, are you ok with this? Please note that you can currently use the nIndex flows view to show all the DNS queries

**Comment by simonemainardi** [comment]
> This can help me on identify new malware o C2C Call back on specific domain.

All DNS queries seen, when associated to alerts, are always saved and reported under the alerts page.

You can also combine this with the use of unexpected DNS servers to receive alerts when an unexpected server is contacted.
