### ISSUE TITLE
 Invalid DNS query need a exclusion list

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#2571]
More and more software (antimalware) are using DNS Query to verify real time the hash of new file that could not be identified by signature and need to be investigated or update on Cloud Service. 
These behavior are generating Invalid DNS Query Alert. We need an fqdn or pattern exclusion list to avoid these alerts.

**Comment by simonemainardi** [comment]
@emanuele-f can this be solved using the already-implemented syntax which requires to specify an FQDN using a 'minus'?

For example by editing the custom Malware rules as:

![image](https://user-images.githubusercontent.com/3397663/57624385-1c2e9280-7592-11e9-92d8-0a36284d6e99.png)

If yes, please, update the doc and send @zimbawe998 the instructions.


------

@zimbawe998 do you have example queries or even pcaps of DNS queries performed by antimalware software?

**Comment by zimbawe998** [comment]
Yes Emanuele. I think that a specific category "DNS Exclusion list" could be the righe place to put the DNS DOMAIN to exclude for the control. Easy and useful.

**Comment by emanuele-f** [comment]
@simonemainardi , @zimbawe998 is referring to the "Invalid DNS query" alerts, which are not related to the malware alerts, so the category lists are not used in this case. However, I think that reusing the category lists and the corresponding editor is a good idea here.

I would add a new nDPI category "DNS exceptions" and use it to avoid generating alerts if flow category matches. If we don't want to add new category, we can reuse the "User Custom Category" but then we need a preference for the DNS alerts to specify which category to use as a whitelist

**Comment by simonemainardi** [comment]
@zimbawe998 do you have examples of such queries?

**Comment by zimbawe998** [comment]
![Immagine](https://user-images.githubusercontent.com/47248892/57925072-3e345780-78a7-11e9-9196-d7e38f9c33dd.png)
This is an example of anitmalware queiry that using DNS to verify is some hash has already present on CLoud AV Database.. It's real but need to be excluded.

**Comment by emanuele-f** [comment]
The proposed implementation is to add a new nDPI category, e.g. "Antimalware", and avoid generating DNS alerts for flows of such category. Such category can be edited as a standard category from the ntopng gui.

**Comment by emanuele-f** [comment]
@zimbawe998 please comment https://github.com/ntop/nDPI/issues/710 and provide a list of domain/rules which should be ignored

**Comment by lucaderi** [comment]
This issue means that we have to
- remove the DNS alert generation from the C++ engine and migrate it to Lua
- in the Lua script, add a text parameter with the exclusion list

**Comment by emanuele-f** [comment]
Implemented. It's now possible to specify a list of subdomains to exclude.

**Comment by zimbawe998** [comment]
HI Emanuele.
I am tring to exclude it but it seems that doens't work.
I'va just updated the ntopng.

Il giorno ven 24 gen 2020 alle ore 15:21 Emanuele Faranda <
notifications@github.com> ha scritto:

**Comment by emanuele-f** [comment]
Can you provide your exclusion list and examples of queries which are not excluded?

**Comment by zimbawe998** [comment]
This is the query:
3.1o1osr00npq4on8op3732pn58q02o01r802023qp1782n5rqn9qnqs0q150no62.76np1r741pr36393648s269991r414161476p4o575qq17nnonn2s06577391q8.r01p43962rs0pr752s54r908sooo791pr79q7r8ns970o9556p7r990r.r5n94r5so9784pq1.i.03.s.sophosxl.net


This is the dns that i exclude  :  sophosxl.net
But the alert will be triggered again

Il giorno mer 5 feb 2020 alle ore 10:04 Emanuele Faranda <
notifications@github.com> ha scritto:

**Comment by emanuele-f** [comment]
I get the correct behavior by manually executing the query above with the `dig` command (the flow does not get alerted). Please ensure that:

- if you have user scripts configurations other than the `Default`, that you are modifying the correct configuration
- `sophosxl.net` is spelled correctly in the gui textarea
- please note that the existing flows will not be re-evaluated, so it's better to restart ntopng after the change to ensure that old flows are not reported
