### ISSUE TITLE
Long-Lived Flows Alerts exclusion

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#2572]
It's appreciated to have the possibility to exclude some protocols or IP from Long-Lived Flows Alerts.
Example: OffSite backup, VPN,  Network DVR, ect

**Comment by lucaderi** [comment]
Same as #2571. Migrate it to Lua and add a Lua-exclusion list based on both
- IP address
and
- nDPI protocol

**Comment by simonemainardi** [comment]
implemented

![image](https://user-images.githubusercontent.com/3397663/73072849-5177d800-3eb6-11ea-8640-3aba2aef698f.png)
