### ISSUE TITLE
Passive mirror 10 dropping packets [Which Licenses Should I buy?]

### ISSUE THREAD

**Issue by njhashmi** [ntop/ntopng#2575]
I have deployed ntopng with a passive split of  10g interface. I see 99% packets are getting dropped whilst I see more than 300k flows that are meaningful for me. I am dumping expired flows out of ntopng to ELK stack and on kibana custom dashboard I am visualizing the flows data. I want to know that where should I start to monitor a total traffic of 40g. I am using pfring and I dont have zc at the moment. I need to understand that to get the traffic completely analyzed what steps should I follow? which licenses should I buy so that I can analyze 40g of trrafic and what should be the server resources for that?

**Comment by emanuele-f** [comment]
Hi, ntopng cannot monitor such a high rate, I think you should use nprobe cento to export flows to ntopng and then process flows instead of packets. Please wait my colleague @simonemainardi confirmation for this.

**Comment by njhashmi** [comment]
Hi,
Thank you for your response. If I am exporting netflows from my edge routers with a ratio of 5k flows / per second. In that case will I be able to use nprobe to collect the flows and extract layer 7 applications etc? and then using export plugin for nprobe I will be able to dump the flows data into my ELK stack. I am not able to understand the difference between nprobe and nprobe cento.

**Comment by emanuele-f** [comment]
nprobe cento is designed to accellerate the packet capture up to 100 gbits. This only works if nprobe is capturing packets from a physical interface, it does not work with netflow. Layer 7 decoding is only performed if nprobe captures packets from a physical interface.

**Comment by njhashmi** [comment]
Thank you for response. I am having 4 individual 10g interfaces and I want to export flows to my own ELK stack using nprobe with custom kibana dashboard. I need the layer 7 decoding and as per the comparison : https://www.ntop.org/nprobe/flow-based-monitoring-nprobe-cento-vs-standardpro/ 
it says that nprobe supports 10g interfaces am I going to need 4 individual licenses for all 4 ports? and in cento I see that it does not support exporting flows to elastic search. So, what do you suggest about my scenario.

**Comment by emanuele-f** [comment]
You will need:
- 1 nprobe pro license
- 4 pf_ring zc licenses, one per nic

We can provide demo licenses to verify that everything works as you need, you can use this form: http://www.ntop.org/support/need-help-2/contact-us/

**Comment by njhashmi** [comment]
Thank you. I have submitted the demo licenses request. Let me set it up and will let you guys know. Cheers!!

**Comment by emanuele-f** [comment]
You are welcome! If you have other questions please open a new issue
