### ISSUE TITLE
Issues with serialization by MAC when multiple IPs in DHCP range share the same MAC

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2577]
13/May/2019 18:55:00 [5min.lua:25] [rrd.lua:308] ERROR: rrd_update_r() [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/bytes.rrd][1557766500:60:0] failed [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/bytes.rrd: illegal attempt to update using time 1557766500 when last update time is 1557766500 (minimum o
13/May/2019 18:55:00 [5min.lua:25] [rrd.lua:308] ERROR: rrd_update_r() [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/active_flows.rrd][1557766500:1:0] failed [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/active_flows.rrd: illegal attempt to update using time 1557766500 when last update time is 15577665
13/May/2019 18:55:00 [5min.lua:25] [rrd.lua:308] ERROR: rrd_update_r() [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/total_flows.rrd][1557766500:1:0] failed [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/total_flows.rrd: illegal attempt to update using time 1557766500 when last update time is 1557766500
13/May/2019 18:55:00 [5min.lua:25] [rrd.lua:308] ERROR: rrd_update_r() [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/anomalous_flows.rrd][1557766500:0:0] failed [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/anomalous_flows.rrd: illegal attempt to update using time 1557766500 when last update time is 15
13/May/2019 18:55:00 [5min.lua:25] [rrd.lua:308] ERROR: rrd_update_r() [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/unreachable_flows.rrd][1557766500:0:0] failed [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/unreachable_flows.rrd: illegal attempt to update using time 1557766500 when last update time i
13/May/2019 18:55:00 [5min.lua:25] [rrd.lua:308] ERROR: rrd_update_r() [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/host_unreachable_flows.rrd][1557766500:0:0] failed [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/host_unreachable_flows.rrd: illegal attempt to update using time 1557766500 when last upd
13/May/2019 18:55:00 [5min.lua:25] [rrd.lua:308] ERROR: rrd_update_r() [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/dns_qry_sent_rsp_rcvd.rrd][1557766500:0:0:0] failed [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/dns_qry_sent_rsp_rcvd.rrd: illegal attempt to update using time 1557766500 when last upd
13/May/2019 18:55:00 [5min.lua:25] [rrd.lua:308] ERROR: rrd_update_r() [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/dns_qry_rcvd_rsp_sent.rrd][1557766500:0:0:0] failed [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/dns_qry_rcvd_rsp_sent.rrd: illegal attempt to update using time 1557766500 when last upd
13/May/2019 18:55:00 [5min.lua:25] [rrd.lua:308] ERROR: rrd_update_r() [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/udp_pkts.rrd][1557766500:0:0] failed [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/udp_pkts.rrd: illegal attempt to update using time 1557766500 when last update time is 1557766500 (mini
13/May/2019 18:55:00 [5min.lua:25] [rrd.lua:308] ERROR: rrd_update_r() [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/tcp_stats.rrd][1557766500:0:0:0] failed [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/tcp_stats.rrd: illegal attempt to update using time 1557766500 when last update time is 1557766500 (
13/May/2019 18:55:00 [5min.lua:25] [rrd.lua:308] ERROR: rrd_update_r() [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/tcp_packets.rrd][1557766500:0:0] failed [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/tcp_packets.rrd: illegal attempt to update using time 1557766500 when last update time is 1557766500
13/May/2019 18:55:00 [5min.lua:25] [rrd.lua:308] ERROR: rrd_update_r() [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/total_alerts.rrd][1557766500:0] failed [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/total_alerts.rrd: illegal attempt to update using time 1557766500 when last update time is 1557766500
13/May/2019 18:55:00 [5min.lua:25] [rrd.lua:308] ERROR: rrd_update_r() [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/contacts.rrd][1557766500:1:0] failed [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/contacts.rrd: illegal attempt to update using time 1557766500 when last update time is 1557766500 (mini
13/May/2019 18:55:00 [5min.lua:25] [rrd.lua:308] ERROR: rrd_update_r() [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/tcp.rrd][1557766500:0:0] failed [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/tcp.rrd: illegal attempt to update using time 1557766500 when last update time is 1557766500 (minimum one se
13/May/2019 18:55:00 [5min.lua:25] [rrd.lua:308] ERROR: rrd_update_r() [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/udp.rrd][1557766500:0:0] failed [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/udp.rrd: illegal attempt to update using time 1557766500 when last update time is 1557766500 (minimum one se
13/May/2019 18:55:00 [5min.lua:25] [rrd.lua:308] ERROR: rrd_update_r() [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/icmp.rrd][1557766500:0:0] failed [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/icmp.rrd: illegal attempt to update using time 1557766500 when last update time is 1557766500 (minimum one 
13/May/2019 18:55:00 [5min.lua:25] [rrd.lua:308] ERROR: rrd_update_r() [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/other_ip.rrd][1557766500:60:0] failed [/var/lib/ntopng/3/rrd/hosts/00_80_8f/9a/ae/bd/v4/other_ip.rrd: illegal attempt to update using time 1557766500 when last update time is 1557766500 (min

This happens when a PC has multiple IP addresses over the same mac. Example:
![Screen Shot 2019-05-13 at 19 03 16](https://user-images.githubusercontent.com/4493366/57640496-f2399800-75b2-11e9-84a8-f002fc5b075d.png)

**Comment by emanuele-f** [comment]
Fixed in 5aff6583b213415d3e601897d433c1ba6766ef4a
