### ISSUE TITLE
Button to reset the ntopng preferences menu

### ISSUE THREAD

**Issue by Freddyqt** [ntop/ntopng#2578]
Hello, I need to reset the default settings settings-> preferences of the ntopng menu, I hope you can help me.

Thank you

**Comment by emanuele-f** [comment]
The reset should be limited to the currently active preferences page, right?

**Comment by Freddyqt** [comment]
> The reset should be limited to the currently active preferences page, right?

Yes my friend.

**Comment by emanuele-f** [comment]
Currently we cannot accomodate this request. Here is how to reset *all* the ntopng preferences:

```
sudo systemctl stop ntopng
redis-cli keys "ntopng.*" | xargs redis-cli unlink
sudo rm /var/lib/ntopng/runtimeprefs.json
sudo systemctl restart ntopng
```
