### ISSUE TITLE
upgrade to 3.9 on arm/pi

### ISSUE THREAD

**Issue by dvachon2018** [ntop/ntopng#2584]
hi, actually at 

3.7.181008 - Enterprise/Embedded Edition
--
on arm/pi strech 9.1
apt-get upgrade seem not to upgrade to 3.9. Was working fine that way last year.
so how to upgrade?

**Comment by simonemainardi** [comment]
did you run an apt-get udpate first?

3.9 packages for your distro are out: http://packages.ntop.org/RaspberryPI/stretch_pi/armhf/ntopng/

**Comment by dvachon2018** [comment]
yes, i did the apt-get update.
it return that


root@ntop:# apt-get update
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:3 http://packages.ntop.org/apt/stretch_pi armhf/ InRelease
Hit:4 http://packages.ntop.org/apt/stretch_pi all/ InRelease
Reading package lists... Done
root@ntop:~#

**Comment by dvachon2018** [comment]
problem solved with this;

apt-get --with-new-pkgs upgrade

**Comment by simonemainardi** [comment]
thanks for reporting
