### ISSUE TITLE
Error when accessing reports in ntopng Professional v.2.1.151109

### ISSUE THREAD

**Issue by dboehlke** [ntop/ntopng#259]
Using apt-get upgrade, I upgraded to the latest ntopng this morning.  I now have version "2.1.151109" running.  When I choose "Report" under the "Home" tab, I get this error and no report:

```
Script "/usr/share/ntopng/scripts/lua/pro/report.lua" returned an error:
attempt to call a string value
```

Thanks.

**Comment by simonemainardi** [comment]
hello @dboehlke, this issue has also been discussed in #261. It should be fixed now. Could you please confirm reports are working as expected in the last dev version? thanks

**Comment by dboehlke** [comment]
I was watching #261 as well.

It is working again in ntopng Professional v.2.1.151111.

Thanks!

**Comment by simonemainardi** [comment]
thank you @dboehlke
