### ISSUE TITLE
Implement network alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2590]
Similar to host alerts, network alerts should be implemented.

For networks alerts needs to be specialised a bit when compared to hosts. Typical alerts include
- Thresholds on #2588
- Unwanted network protocols. For instance on a storage network, a typical alert should be triggered when P2P protocols are detected.

**Comment by simonemainardi** [comment]
Network alerts are implemented:

Network page, Alerts tab:

![image](https://user-images.githubusercontent.com/3397663/60118663-1a551300-977d-11e9-9851-c257c5b2f6f2.png)
