### ISSUE TITLE
Report Interface errors

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2592]
In SNMP, interface traffic do not report errors. 

![Screen Shot 2019-05-18 at 10 27 16](https://user-images.githubusercontent.com/4493366/57966831-8ca12f00-7957-11e9-9b73-11e165a0c17e.png)

It is requested to add a line on the graph that reports on the right Y axis interface errors that overlaps with in/out bytes

**Comment by cardigliano** [comment]
Implemented
