### ISSUE TITLE
Some 'Local HTTP Servers' appear with remote addresses

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#2596]
Ubuntu 19.10 eoan
ntopng 3.9.190506

Some ```Local HTTP Servers``` appear with a local IP address in the 'HTTP Server IP' column, but with a remote IP address in the first column 'HTTP Virtual Host'.
How it that possible and what is the meaning of this situation?
There seams to be some security implications.

**Comment by simonemainardi** [comment]
Virtual hosts, as the name says, are virtual and have nothing to do with the local `HTTP Server IP`. So the behavior you're reporting is perfectly normal.

Virtual hosts are dissected by ntopng from the HTTP request in the `Host:`. For example, in the image below, the http host seen is `httpd.apache.org`

![image](https://user-images.githubusercontent.com/3397663/58015138-c3fc1100-7afa-11e9-808b-65f3cc4b8030.png)


Virtual hosts are widely used as they allow you to run multiple web services (e.g., websites) onto the same physical host with the same IP address. For a definition of virtual hosts have a look at how Apache describes them: https://httpd.apache.org/docs/2.4/vhosts/index.html

**Comment by jean-christophe-manciot** [comment]
@simonemainardi  I think you closed this issue too quickly.
How do you explain the fact that when clicking on the ```active flows``` 
![Active Flows](https://user-images.githubusercontent.com/13176858/58084187-b6a65b80-7bba-11e9-86e6-5f75c6d4a09e.png)
related to the remote 'http virtual hosts', **none of the flows involve the corresponding virtual host ip address**?

**Comment by simonemainardi** [comment]
Because currently, flows lookup on the basis of the virtual host has still to be implemented but this is not what the issue was asking. I'll implement it and let you know.
