### ISSUE TITLE
Flow info column: broken sort

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2597]
![Screen Shot 2019-05-20 at 09 43 04](https://user-images.githubusercontent.com/4493366/58004546-c0a95b00-7ae3-11e9-95fe-a3d982b59aac.png)

**Comment by simonemainardi** [comment]
Also please check and fix "Echo request x"

**Comment by cardigliano** [comment]
Since sorting happens in the C paginator, it works for Info which are present in the Flow class, while it does not work for Info generated by lua at visualization time (using locales).

**Comment by cardigliano** [comment]
Sorting on Info has been disabled for the time being as it is difficult to implement it correctly by design.
