### ISSUE TITLE
Is it possible to supplement geolocation data for some IP addresses...

### ISSUE THREAD

**Issue by dboehlke** [ntop/ntopng#260]
It appears that the geolocation data used by ntopng bases the location on the address in whois for the network and AS.  As a result only one of the data centers that I monitor has an address that is close to the location.  Can I build a file with geolocation information for my IP's so that they are put in the right place on the map?

Thanks.

**Comment by lmangani** [comment]
Hi @dboehlke if the mapping is not volatile, you can submit corrections to the maxmind database here: https://support.maxmind.com/geoip-data-correction-request/

**Comment by dboehlke** [comment]
Thanks!  The internal locations of the IP addresses do move, but they are static and only move as equipment is retired and possibly not replaced in the same data center, so updating maxmind.com should work.

**Comment by lmangani** [comment]
Great - we might consider adding a local override option in future versions
