### ISSUE TITLE
Invalid Engaged Alert

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2600]
![Screen Shot 2019-05-20 at 17 48 50](https://user-images.githubusercontent.com/4493366/58034779-9a0d1380-7b27-11e9-8a3a-65de8c7ee0aa.png)
The above picture shows that an alert is still engaged but this is not correct. As you can see ntopng has been restarted in the meantime (compare the time at the bottom of the picture) and the alert is still engaged. This information is not correct.

**Comment by emanuele-f** [comment]
This can happen if the interface had too many drops before the restart and still has too many drops after the restart. We don't release alerts during startup/shutdown so this is feasible

**Comment by emanuele-f** [comment]
Closing as the user reported that the alert was correctly closed after some time
