### ISSUE TITLE
InfluxDB timeseries cleanup and usage report

### ISSUE THREAD

**Issue by laurentduru** [ntop/ntopng#2602]
Hello,

I have a problem with InfluxDB usage report and cleanup in Ntopng stable version 3.8.190516 (also in older versions).

The storage usage reported in each interface and in "storage utilization" in runtime status  page seem concerning RRD data and not InfluxDB. "InfluxDB storage" is the right value but with no corresponding at all with the figures I mentioned.

I also noticed that I have older values than the "InfluxDB timeseries data retention days" (30 days) for interface traffic graph, protocols, ... I'm concern by the cleanup because the DB is growing every day. On the other hand "top talkers storage" is well cleaned, I don't have values older than configured (30 days).

I opened a single issue because both problem may be a unique source, if you think I'm wrong I can split it in two issues.

Best Regards

Laurent

**Comment by laurentduru** [comment]
Browsing the older cases on influxDB, I think I got an answer for the cleanup part of issue :
With a retention of 30 days, influxDB create 7 days shared so I have a maximum retention of 30days+7days.

**Comment by emanuele-f** [comment]
The "Timeseries" label reported here does not account the InfluxDB data, I'm going to change the label to "RRD Timeseries".

![2019-05-21_18-28](https://user-images.githubusercontent.com/5488003/58113642-8922d780-7be5-11e9-892a-1ec62d21c185.png)

Regarding the cleanup, what is the output of `influx -database ntopng -execute "show retention policies"` where "ntopng" is the InfluxDB database name linked to ntopng?

**Comment by emanuele-f** [comment]
Label fixed in https://github.com/ntop/ntopng/commit/d11c9a1c16db2907ab8e241fd3117918c5654be2

**Comment by laurentduru** [comment]
OK nice, then I miss the InfluxDB Timeseries information ;)

Yes, I confirm :
influx -database ntopng -execute "show retention policies"
name    duration shardGroupDuration replicaN default
----    -------- ------------------ -------- -------
autogen 720h0m0s 168h0m0s           1        true

And :
influx -database ntopng -execute "SHOW SHARDS"
name: ntopng
id database retention_policy shard_group start_time           end_time             expiry_time          owners
-- -------- ---------------- ----------- ----------           --------             -----------          ------
33 ntopng   autogen          33          2019-04-15 T00:00:00Z 2019-04-22T00:00:00Z 2019-05-22T00:00:00Z
41 ntopng   autogen          41          2019-04-22T00:00:00Z 2019-04-29T00:00:00Z 2019-05-29T00:00:00Z
49 ntopng   autogen          49          2019-04-29T00:00:00Z 2019-05-06T00:00:00Z 2019-06-05T00:00:00Z
57 ntopng   autogen          57          2019-05-06T00:00:00Z 2019-05-13T00:00:00Z 2019-06-12T00:00:00Z
65 ntopng   autogen          65          2019-05-13T00:00:00Z 2019-05-20T00:00:00Z 2019-06-19T00:00:00Z
73 ntopng   autogen          73          2019-05-20T00:00:00Z 2019-05-27T00:00:00Z 2019-06-26T00:00:00Z

If I well understand, the retention policy will remove data from 2019-04-15 to 2019-04-22 on 2019-05-22, so today (2019/05/21) I still have data for 30 days + 7 days, and tomorrow I will have data for 30 days. It has just to be known that cleanup is done by bunch of x days depending of the retention configured in Ntopng.

**Comment by emanuele-f** [comment]
Thank you for the explanation. In f0ae0f4274212960e9155462ace8d11ae88b6ee0 I've added a note and also enforced the default shard duration suggested by InfluxDB in https://docs.influxdata.com/influxdb/v1.7/query_language/database_management/#description-of-syntax-1 . I assume that the `ALTER RETENTION POLICY` does not modify the shard group duration itself, so now this is set manually according to the recommendation.

![2019-05-21_19-57](https://user-images.githubusercontent.com/5488003/58119190-f2a8e300-7bf1-11e9-9af7-1475177e8cd1.png)

Before:
```
name    duration shardGroupDuration replicaN default
----    -------- ------------------ -------- -------
autogen 720h0m0s 168h0m0s           1        true
1h      936h0m0s 24h0m0s            1        false
1d      936h0m0s 168h0m0s           1        false
```

After the commit:
```
name    duration shardGroupDuration replicaN default
----    -------- ------------------ -------- -------
autogen 720h0m0s 24h0m0s            1        true
1h      720h0m0s 24h0m0s            1        false
1d      720h0m0s 24h0m0s            1        false
```

Please note that the change will be available into the tomorrow build of the *dev* package, so version 3.8 will not be affected by this enhancement.
