### ISSUE TITLE
Blacklisted Hosts list is always empty

### ISSUE THREAD

**Issue by Netw0rkGuy** [ntop/ntopng#2603]
Since a while the 'Blacklisted Hosts Only' filter in the 'Hosts' section does not display any matches.
We checked a few attackers manually against the current list from https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt
and see that ntopng is indeed collecting flow information for those hosts, but cannot flag them as blacklisted hosts.

On the proxy server we see that ntopng is successfully downloading the file:
2019-05-21 13:07:25 +0200 39 10.1.2.23 TCP_MEM_HIT/200 21628 GET http://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt - text/plain

Something seems to be broken in our configuration. What could we do to re-establish this visibility? 

![ntop-ng_blacklisted-host](https://user-images.githubusercontent.com/42970280/58103498-5d9eed80-7be3-11e9-991f-379da83f55b8.png)

Our ntopng version is 3.8.190516 (stable)

**Comment by simonemainardi** [comment]
There was no support for blacklisted hosts over ZMQ in the 3.8 stable. Now I've added it. New builds are in progress. Please, hold on a couple of hours and give it a try.

**Comment by simonemainardi** [comment]
https://github.com/ntop/ntopng/commit/5aa102525c6ef6ad01cb266925a74857db95e0be

**Comment by Netw0rkGuy** [comment]
Thank you. Since version 3.8.190522-5591 the list is populated again.
