### ISSUE TITLE
Changing the edition?

### ISSUE THREAD

**Issue by ShagoY** [ntop/ntopng#2605]
Probably stupid question, but when you install Ntopng using the packages manager under Pfsense/OPNSense and even with the junquera docker, you automatically end up with the "Community Edition".
As a result, and unless I am mistaken, we do not have the possibility of having a "System Id" for the registration of the license.

I read the doc/faq but I didn't find anything about it....

Any help?

**Comment by simonemainardi** [comment]
this is correct. Currently, there's no support for Pfsense/OPNSense for the professional / enterprise versions. Only community is available there.
