### ISSUE TITLE
Ban nasty hosts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2609]
![image](https://user-images.githubusercontent.com/4493366/58306900-53f0d200-7dfd-11e9-8ed1-5445234d9752.png)

In case hosts are misbehaving and constantly attacking the monitored network (below you can see hosts are insisting in their malicious activities) ntopng has to react:
- in monitoring mode (ntopng), an action must be performed (e.g. send email, call URL etc, multiple options can be set)
- in inline mode (nEdge) the host needs to be banned for some time/forever.

For both options the user through preferences can fine-grain tune the system.

**Comment by MDSharma** [comment]
you could also have an option to coordinate with a BGP blackhole system (like fastnetmon with ExaBGP or GoBGP) in the monitoring mode. When an attack stops, the blackhole can be pulled away..  That would make ntopng stand out from nScrub (with no netflow processing) and add a good feature enhancement.

**Comment by simonemainardi** [comment]
Implemented with callback DangerousHost and jailed hosts pool
