### ISSUE TITLE
ntopng-professional edition-Dashboard doesn't work

### ISSUE THREAD

**Issue by prutasiscale** [ntop/ntopng#261]
Hello,
Since few weeks I experience a strange issue with ntopng. The Dashboard doesn't show up anything and the Reporting tool is extremely slow. 
See attached the printscreen.
Please find below the output of the top command. 
top - 17:53:07 up 11 min,  1 user,  load average: 0.55, 0.53, 0.33
Tasks: 129 total,   2 running, 127 sleeping,   0 stopped,   0 zombie
Cpu(s): 18.7%us,  4.7%sy,  0.0%ni, 71.8%id,  0.2%wa,  0.0%hi,  4.5%si,  0.0%st
Mem:  16433716k total,   828572k used, 15605144k free,    21724k buffers
Swap: 16773116k total,        0k used, 16773116k free,   244348k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                      
 1953 nobody    20   0 1344m 301m  27m S  170  1.9  11:31.17 ntopng                        
 1568 redis     20   0 16724 7780  744 R   34  0.0   1:11.96 redis-server                  
   30 root      20   0     0    0    0 S    0  0.0   0:00.25 ksoftirqd/2                   
    1 root      20   0 24336 2272 1336 S    0  0.0   0:01.33 init                          
    2 root      20   0     0    0    0 S    0  0.0   0:00.00 kthreadd                      
    3 root      20   0     0    0    0 S    0  0.0   0:00.66 ksoftirqd/0                   
    4 root      20   0     0    0    0 S    0  0.0   0:00.00 kworker/0:0                   
    5 root       0 -20     0    0    0 S    0  0.0   0:00.00 kworker/0:0H                  
    6 root      20   0     0    0    0 S    0  0.0   0:00.09 kworker/u12:0                 
    7 root      20   0     0    0    0 S    0  0.0   0:00.47 rcu_sched                     
    8 root      20   0     0    0    0 S    0  0.0   0:00.11 rcuos/0                       
    9 root      20   0     0    0    0 S    0  0.0   0:00.07 rcuos/1                       
   10 root      20   0     0    0    0 S    0  0.0   0:00.07 rcuos/2                       
   11 root      20   0     0    0    0 S    0  0.0   0:00.09 rcuos/3                       
   12 root      20   0     0    0    0 S    0  0.0   0:00.09 rcuos/4                       
   13 root      20   0     0    0    0 S    0  0.0   0:00.12 rcuos/5    
![ntopng](https://cloud.githubusercontent.com/assets/15750867/11049190/b12dd1ae-870a-11e5-84bf-05b690f4fc11.jpg)

**Comment by lmangani** [comment]
@prutasiscale please provide your full configuration and outline the setup and relevant log error lines if any (also consider upgrading to the latest stable build)

**Comment by prutasiscale** [comment]
just upgraded to the latest version the the problem disappeared on the dashboard. 
but, when I try to run a report I get the following error:

" Script "/usr/share/ntopng/scripts/lua/pro/report.lua" returned an error:
attempt to call a string value"

here is the config of the ntopng:
root@rxr-phonsys1:~# more /etc/ntopng/ntopng.conf 
-n=2
-w=3000
-W=0
-g=-1
-m="10.0.0.0/255.0.0.0,192.168.0.0/255.255.0.0,172.16.0.0/255.240.0.0"
-S=remote
-F=es;flows;ntopng-rxr-%Y.%m.%d;http://10.100.103.17:9200/_bulk;
-d=/storage/ntopng
-G=/var/tmp/ntopng.pid
-i=eth1
-i=eth2
-i=eth3

![ntop-about](https://cloud.githubusercontent.com/assets/15750867/11049934/f6cabba0-870f-11e5-8df3-092bb2684648.png)

**Comment by prutasiscale** [comment]
Hi, I still get this error when I try to load the reports tab:

 Script "/usr/share/ntopng/scripts/lua/pro/report.lua" returned an error:
attempt to call a string value


here is the log:
10/Nov/2015 14:29:09 [Prefs.cpp:654] Using ElasticSearch for data dump [flows][ntopng-rxr-%Y.%m.%d][http://10.100.103.17:9200/_bulk]
10/Nov/2015 14:29:09 [Ntop.cpp:933] Setting local networks to 10.0.0.0/255.0.0.0,192.168.0.0/255.255.0.0,172.16.0.0/255.240.0.0
10/Nov/2015 14:29:09 [Redis.cpp:106] Successfully connected to redis 127.0.0.1:6379@0
10/Nov/2015 14:29:09 [NtopPro.cpp:117] [LICENSE] Read license from Redis ----license---
10/Nov/2015 14:29:09 [PF_RINGInterface.cpp:52] Reading packets from PF_RING v.6.1.1 interface eth1...
10/Nov/2015 14:29:09 [Ntop.cpp:1152] Registered interface eth1 [id: 0]
10/Nov/2015 14:29:09 [PF_RINGInterface.cpp:52] Reading packets from PF_RING v.6.1.1 interface eth2...
10/Nov/2015 14:29:09 [Ntop.cpp:1152] Registered interface eth2 [id: 1]
10/Nov/2015 14:29:09 [PF_RINGInterface.cpp:52] Reading packets from PF_RING v.6.1.1 interface eth3...
10/Nov/2015 14:29:09 [Ntop.cpp:1152] Registered interface eth3 [id: 3]
10/Nov/2015 14:29:09 [Ntop.cpp:1165] Registered interface view eth1 [id: 0]
10/Nov/2015 14:29:09 [Ntop.cpp:1165] Registered interface view eth2 [id: 1]
10/Nov/2015 14:29:09 [Ntop.cpp:1165] Registered interface view eth3 [id: 3]
10/Nov/2015 14:29:09 [Utils.cpp:304] User changed to nobody
10/Nov/2015 14:29:09 [main.cpp:240] PID stored in file /var/tmp/ntopng.pid
10/Nov/2015 14:29:09 [HTTPserver.cpp:458] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
10/Nov/2015 14:29:09 [HTTPserver.cpp:501] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
10/Nov/2015 14:29:09 [HTTPserver.cpp:504] HTTP server listening on port 3000
10/Nov/2015 14:29:09 [main.cpp:290] Working directory: /storage/ntopng
10/Nov/2015 14:29:09 [main.cpp:292] Scripts/HTML pages directory: /usr/share/ntopng
10/Nov/2015 14:29:09 [Ntop.cpp:260] Welcome to ntopng x86_64 v.2.1.151110 - (C) 1998-15 ntop.org
10/Nov/2015 14:29:09 [Ntop.cpp:265] Built on Ubuntu 12.04.5 LTS
10/Nov/2015 14:29:09 [PeriodicActivities.cpp:53] Started periodic activities loop...
10/Nov/2015 14:29:09 [RuntimePrefs.cpp:32] Dumping alerts into syslog
10/Nov/2015 14:29:09 [NtopPro.cpp:234] [LICENSE] ntopng systemId: 68A5360682072B23
10/Nov/2015 14:29:09 [NtopPro.cpp:245] [LICENSE] ntopng license: ---license---
10/Nov/2015 14:29:09 [NtopPro.cpp:266] [LICENSE] Maintenance is available until Fri Sep  9 16:40:28 2016 [304 days left]
10/Nov/2015 14:29:09 [Ntop.cpp:546] Adding fe80::250:56ff:fea2:179a/64 as IPv6 local network for eth1
10/Nov/2015 14:29:09 [Ntop.cpp:546] Adding fe80::250:56ff:fea2:4a2a/64 as IPv6 local network for eth2
10/Nov/2015 14:29:09 [Ntop.cpp:546] Adding fe80::250:56ff:fea2:4d44/64 as IPv6 local network for eth3
10/Nov/2015 14:29:09 [NetworkInterface.cpp:1427] Started packet polling on interface eth1 [id: 0]...
10/Nov/2015 14:29:09 [NetworkInterface.cpp:1422] Setting affinity of interface eth2 to core 1
10/Nov/2015 14:29:09 [NetworkInterface.cpp:1427] Started packet polling on interface eth2 [id: 1]...
10/Nov/2015 14:29:09 [NetworkInterface.cpp:1422] Setting affinity of interface eth3 to core 2
10/Nov/2015 14:29:09 [NetworkInterface.cpp:1427] Started packet polling on interface eth3 [id: 3]...
10/Nov/2015 14:29:26 [Lua.cpp:4747] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/report.lua][attempt to call a string value]
10/Nov/2015 14:29:28 [Lua.cpp:4747] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/report.lua][attempt to call a string value]
10/Nov/2015 14:30:07 [Lua.cpp:4419] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:100:
 mmaping file '/storage/ntopng/1/rrd/Amazon.rrd': Invalid argument]

**Comment by simonemainardi** [comment]
hello @prutasiscale , thanks for reporting the issue. It should have been fixed now. Please hold on, new package will be build overnight.

Let me know.

**Comment by simonemainardi** [comment]
issue has been resolved resolved as confirmed in #259
