### ISSUE TITLE
Automatically Delete Alert older than

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#2611]
Some times there are too many alert to aknowledge or to check.
It could be appreciated to auto delete alert older than a specific time period specified on the preferences -> Alert page

**Comment by emanuele-f** [comment]
Please note that the Alerts page already has a button "Alerts to Purge: older than x minutes". Further alerts settings can be set from the "Alerts Retention" preferences

**Comment by zimbawe998** [comment]
Thanks Emanuele. We thought to auto delete older alarm after some days/month.
This option is usefull if you want to see errors starting from now but the auto deletion is usefull to keep in memory only a small range of alarm to see analyse trending. On some installation we see more than 14k alarm.... ok thanks, but user, in this case, purge all of them. It's best to mantain a Alarm Windows History so We can see the last 1 monthmore or less and in case of some particular needs we can purge and restart from scratch.

**Comment by lucaderi** [comment]
In essence we need to implement alert retention based on time that is periodically executed for instance every night
