### ISSUE TITLE
How can change interface network card

### ISSUE THREAD

**Issue by twistybin** [ntop/ntopng#2613]
Hi, I have map network with pfsense:
VLAN :vmx1(1,10,20,30)
WAN:em0,em1
After I install ntopng v3.9 on Ubuntu (VLAN:10,em32: 11.11.11.100), It only show em32, I need It show all of interface in vmx1

How can I change it ??

**Comment by emanuele-f** [comment]
Usually you need to add the `-i=vmx1`option to the ntopng configuration file, see https://www.ntop.org/guides/ntopng/how_to_start/configuration_file.html . I don't know if this is applicable to pfsense but we dont' support it.
