### ISSUE TITLE
Traffic Report Application Breakdown not showing

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#2614]
![image](https://user-images.githubusercontent.com/48565067/58508909-3f953800-8163-11e9-937c-a3435e75e2ea.png)

Do not see Application Breakdown under the traffic report menu option

Is this a bug, or is this resolvable via some configuration change?

3.8.190516 - Enterprise Edition
Ubuntu 18.04.2 LTS
nDPI: 2.8.0-1457-003547a
cURL: 7.58.0

**Comment by StewAlexander-com** [comment]
Chrome Inspector Console showing: 

```
<table class="table table-bordered table-striped" width="100%" height="100%" id="row_if_eth0VLANId70155907300060all_chart_pieapps_lastday"><tbody><tr><th style="width: 20%; vertical-align: middle;"><h4>Application Breakdown</h4><p>&nbsp;</p><h5 id="label_if_eth0VLANId70155907300060all_chart_pieapps_lastday"></h5></th>
<td style="position: relative;"><span><svg id="if_eth0VLANId70155907300060all_chart_pieapps_lastday" style="height: 400px; width: 95%;"></svg></span></td></tr>
</tbody></table>
```

----

Uncaught TypeError: Cannot read property '1' of undefined
    at stack (d3.v3.js:6700)
    at SVGGElement.<anonymous> (nv.d3.js:17747)
    at d3.v3.js:8869
    at d3_selection_each (d3.v3.js:968)
    at Array.d3_transitionPrototype.each (d3.v3.js:8867)
    at Array.chart (nv.d3.js:17721)
    at Array.d3_selectionPrototype.call (d3.v3.js:975)
    at SVGSVGElement.<anonymous> (nv.d3.js:18345)
    at d3.v3.js:962
    at d3_selection_each (d3.v3.js:968)
    at Array.d3_selectionPrototype.each (d3.v3.js:961)
    at Array.chart (nv.d3.js:18103)
    at Array.d3_selectionPrototype.call (d3.v3.js:975)
    at Object.generate (report.lua:1609)
    at renderLoop (nv.d3.js:99)

**Comment by emanuele-f** [comment]
This is a bug. Can you provide web access to your ntopng gui to inspect it? If so, please send me the credentials to faranda@ntop.org .

**Comment by StewAlexander-com** [comment]
I can share my screen through a tool such as teamviewer, if we can schedule a time to videoconference, I am on US Eastern Daylight Time (GMT-4)

Otherwise, I can provide screen captures, logs, configurations, output of any commands, etc you or your colleagues desire to collect.

**Comment by StewAlexander-com** [comment]
![image](https://user-images.githubusercontent.com/48565067/58558440-da872400-81ee-11e9-9970-029e73088c72.png)

Would this work behind a firewall?  

We are not going to expose our ntopng to the outside world

**Comment by emanuele-f** [comment]
Yes, it will work.

**Comment by StewAlexanderACC** [comment]
[n2n_assistance.zip](https://github.com/ntop/ntopng/files/3232516/n2n_assistance.zip)

**Comment by emanuele-f** [comment]
Please turn off, then on again, then send me via email as this is confidential. faranda@ntop.org

**Comment by StewAlexander-com** [comment]
Very well, thank you

**Comment by StewAlexander-com** [comment]
Sent via email

**Comment by StewAlexander-com** [comment]
Please let me know when I can disable this, as it is something we do not want enabled for awhile

**Comment by emanuele-f** [comment]
No mail received so far

**Comment by StewAlexander-com** [comment]
Unbeknownst to me our email servers block any outgoing zip files, as such emailed you a private Google Drive link to a folder with the files in it

**Comment by StewAlexander-com** [comment]
Please let me know if you receive the link, thank you

**Comment by StewAlexander-com** [comment]
Interfaces is back up, after correcting permissions issues (thank you), but the application breakdown is still missing

![image](https://user-images.githubusercontent.com/48565067/58570683-6ce6f200-8206-11e9-9d25-b225200d3abf.png)

Unless this data takes awhile to collect before anything is shown?

**Comment by StewAlexander-com** [comment]
As I only had categories enabled for L7 timeseries answers change the ones I could to "both", did not have an immediate effect on the ntopng traffic report application breakdown

**Comment by StewAlexander-com** [comment]
After fixing permissions and setting the preferences to "both" instead of "per category" finally the Application Breakdown is showing information

![image](https://user-images.githubusercontent.com/48565067/58575301-bee04580-820f-11e9-829f-31d57029f9d4.png)

**Comment by emanuele-f** [comment]
Great. Since this is a recurrent issue, I'll add the instructions to fix this in the docs

**Comment by emanuele-f** [comment]
Documented in https://github.com/ntop/ntopng/commit/9b1eff25830ef3ed24a93f3c719b0c9eba405ec6
