### ISSUE TITLE
No hosts by Operating System, possibly related to bug #1994?

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#2615]
![image](https://user-images.githubusercontent.com/48565067/58509339-52f4d300-8164-11e9-8b4e-cb8621b20b69.png)
![image](https://user-images.githubusercontent.com/48565067/58509385-728bfb80-8164-11e9-8a82-a1f82725dbe4.png)

Under "Hosts by Operating System" it show "no results found"

Is this something wrong with my configuration, or is this a bug (perhaps related to the earlier bug ID #1994)?

**Comment by emanuele-f** [comment]
Have you selected interface "eth0" from the Interfaces menu? Os detection should not work when capturing from nProbe

**Comment by StewAlexander-com** [comment]
Yes...

At the moment nProbe per the config file is accepting traffic from the loopback address, is this wrong?

**Comment by StewAlexander-com** [comment]
![image](https://user-images.githubusercontent.com/48565067/58558046-cf7fc400-81ed-11e9-8ea4-0f1431d2b144.png)

**Comment by StewAlexander-com** [comment]
Even with interface set to eth0 the "Hosts Per Operating System" is showing "results not found", what information can I provide assist?

**Comment by emanuele-f** [comment]
We need to check this as in your case you have active local hosts with an OS set but still no results in the OS page

**Comment by StewAlexander-com** [comment]
Ok, please let me know what you would like me to provide - I have turned remote access off, but if you need this I can re provide the details on the google drive link I provided earlier

**Comment by emanuele-f** [comment]
This is a bug due to an internal inconsistency, see #2621 .
