### ISSUE TITLE
Hosts -> All Hosts -> Click on any host link> Graph is empty

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#2616]
![image](https://user-images.githubusercontent.com/48565067/58510202-3eb1d580-8166-11e9-8288-ee56c1acd347.png)

When I select hosts I do not often see a graph, is this a configuration issue, or off by design?

Also under the same Hosts menu -> Click on a host -> Active Flows, "no results found"

Is this a misconfiguration, or a bug?

**Comment by emanuele-f** [comment]
Graphs are only shown for "local" hosts (the ones with green badge) and can configured here https://www.ntop.org/guides/ntopng/basic_concepts/timeseries.html#timeseries-configuration . Can you post a screnshot of the empty graph? If you are capturing from nProbe, flows timeout may be too low and you can't see active flows. You can increase flows timeout from the ntopng cache preferences.

**Comment by StewAlexander-com** [comment]
I see, then it appears to be working as designed.

Either the graph icon is unavailable, or if it is, the graph is showing information

I am closing this as answered, thank you
