### ISSUE TITLE
Export All Host with duration time per Application

### ISSUE THREAD

**Issue by twistybin** [ntop/ntopng#2620]
Hi, I need to export data to analytic on Power BI, but I have a problem.
When I export JSON Data by Local, I cannot find value.facebook or value.google with duration time, Send/Receive. 
I need export JSON data by Local same Single. Because on Single has column per Application with duration time.
![image](https://user-images.githubusercontent.com/43060473/58605029-ac721480-82c0-11e9-9be7-7a07edded27c.png)

So, please help me How can I export data with All Host have column on picture.
Thanks !

**Comment by emanuele-f** [comment]
In order to do this, you need to perform multiple Single requests. We cannot return the nDPI data when you select "All Local" because it would be too much information for a single request.

**Comment by twistybin** [comment]
So How can I write multiple Single request.
I have about 250 devices, can you write example for perform multiple Single requests ?
Thanks.

**Comment by emanuele-f** [comment]
You can perform a single "All" request, then parse the json to extract the active hosts, then iterate and perform many Single requests. This is just standard json parsing
