### ISSUE TITLE
Local / Remote, Local Networks not showing anything under traffic report

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#2622]
__Local / Remote__  and __Local Networks__ panels under the ***Traffic Report*** menu show nothing:

![image](https://user-images.githubusercontent.com/48565067/58634994-b6911480-82ba-11e9-8cd3-2bee4a065043.png)

Google Inspector shows this:
```
d3.v3.js:6700 Uncaught TypeError: Cannot read property '1' of undefined
    at stack (d3.v3.js:6700)
    at SVGGElement.<anonymous> (nv.d3.js:17747)
    at d3.v3.js:8869
    at d3_selection_each (d3.v3.js:968)
    at Array.d3_transitionPrototype.each (d3.v3.js:8867)
    at Array.chart (nv.d3.js:17721)
    at Array.d3_selectionPrototype.call (d3.v3.js:975)
    at SVGSVGElement.<anonymous> (nv.d3.js:18345)
    at d3.v3.js:962
    at d3_selection_each (d3.v3.js:968)
    at Array.d3_selectionPrototype.each (d3.v3.js:961)
    at Array.chart (nv.d3.js:18103)
    at Array.d3_selectionPrototype.call (d3.v3.js:975)
    at Object.generate (report.lua:2643)
    at renderLoop (nv.d3.js:99)
```

Is this a configuration issue, or is this a bug?

**Comment by emanuele-f** [comment]
Please update to the latest version and recheck this

**Comment by StewAlexander-com** [comment]
Used `sudo apt-get upgrade` to install latest version of ntopng, from about menu:

![image](https://user-images.githubusercontent.com/48565067/58647909-88213280-82d6-11e9-8e56-57242ef462fe.png)

I still do not see Local/Remote or Local Networks panels with a graph, just total traffic only in writing

Here is my Filter Report:

![image](https://user-images.githubusercontent.com/48565067/58648048-d0405500-82d6-11e9-8833-71cc2ac14fa3.png)
![image](https://user-images.githubusercontent.com/48565067/58648071-e0583480-82d6-11e9-837f-b94703af6b3c.png)

**Comment by emanuele-f** [comment]
Please check out the new stable release, which will be available in one hour.

**Comment by StewAlexander-com** [comment]
# Thank you!

It is showing up:

![image](https://user-images.githubusercontent.com/48565067/58801458-a2aa2300-85d8-11e9-8e66-01686039a586.png)

-----

![image](https://user-images.githubusercontent.com/48565067/58801572-e69d2800-85d8-11e9-88ea-2464acd295d3.png)

-----

![image](https://user-images.githubusercontent.com/48565067/58801747-64f9ca00-85d9-11e9-9a65-467148733825.png)

**Comment by simonemainardi** [comment]
thanks for reporting
