### ISSUE TITLE
Feature Request: Export of All Hosts as a CSV document

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#2624]
There doesn't appear to be a way to export the the "All Hosts" page under the **Hosts** menu as a CSV document, this would be a nice feature to have for reporting

**Comment by emanuele-f** [comment]
We already support export to json via https://www.ntop.org/guides/ntopng/web_gui/settings.html#manage-stored-data

**Comment by StewAlexander-com** [comment]
Where is this export page?

Does this mean you have a restful API?

**Comment by StewAlexander-com** [comment]
Ok found it under "managed stored data"

Still curious if this means that ntopng has a restful API, please let me know

**Comment by emanuele-f** [comment]
Please check out https://www.ntop.org/guides/ntopng/api/rest/index.html

**Comment by StewAlexander-com** [comment]
very nice, ***please close this feature request as resolved***, thanks
