### ISSUE TITLE
Error: rrd_update_r

### ISSUE THREAD

**Issue by maravento** [ntop/ntopng#2625]
example:
![Captura de pantalla -2019-05-31 10-38-54](https://user-images.githubusercontent.com/14880802/58717230-5ec4dd00-8390-11e9-8a06-3033522f5d50.png)

**Comment by emanuele-f** [comment]
Please check out https://www.ntop.org/guides/ntopng/faq.html#permission-denied-errors

**Comment by maravento** [comment]
solved! thanks
