### ISSUE TITLE
[Feature request] Add ways to measure the evolving popularity of a site

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#2626]
Debian buster
ntopng 3.9.190531 - Community Edition
ndpi 2.9.0-1542-c43bec8

Unless I'm missing something, so far, the only way to try to measure the popularity of a site is through the following time series chart:
- ```traffic```
- ```total flows``` which is actually represented by ```active flows```

We could get a more precise view of the growing/declining popularity of a site with the following time series charts within a configurable time frame for a specific host (site):
- ```total hosts```: total number of hosts which contacted the site/were contacted by the site
- ```total countries```: total number of countries which contacted the site/were contacted by the site
- ```total AS```: total number of AS which contacted the site/were contacted by the site

They also can overcome a shortcoming related to the fact that the 'hosts' column and number of rows are reset in the ```Countries``` & ```Autonomous Systems``` each time ntopng is restarted/upgraded as depicted [here](https://github.com/ntop/ntopng/issues/2606)..

**Comment by simonemainardi** [comment]
Currently, you can create custom categories of custom applications to define your sites (that will include SSL certificates, HTTP hosts, DNS names) and then you'll have them available as if they were regular builtin applications, along with the number of active flows, hosts, etc.

Please, see https://www.ntop.org/guides/ntopng/web_gui/categories.html

**Comment by jean-christophe-manciot** [comment]
The initial goal is to get **several charts with historical stats** showing:
- ```total hosts```: total number of hosts which contacted the site/were contacted by the site
- ```total countries```: total number of countries which contacted the site/were contacted by the site
- ```total AS```: total number of AS which contacted the site/were contacted by the site

These charts to do relate to any particular "custom category of custom applications", but to all applications flowing into/out of a particular host.
Furthermore, when going through all items of the dropping list of the ```Timeseries``` of a specific host, there is no entry for:
- anything close to the former ```total hosts```, ```total countries``` or ```total AS```
- any category, let alone custom category
![Timeseries charts](https://user-images.githubusercontent.com/13176858/59029668-2c6b2200-885f-11e9-8db3-148b5176b1de.png)
