### ISSUE TITLE
apt-get remove ntopng on ubuntu16 seems to remove the config file

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#2629]
An edited config file should be preserved rather than being deleted. It is necessary to check this behavior.

**Comment by emanuele-f** [comment]
Tried both stable and dev packages with:

```
sudo apt-get remove ntopng ntopng-data
sudo apt-get install ntopng ntopng-data
sudo dpkg-reconfigure ntopng
```

The edited config fil is correctly preserved in all the cases.
