### ISSUE TITLE
Script Failure Message

### ISSUE THREAD

**Issue by PrimaryHealthTas** [ntop/ntopng#263]
I am running ntopng with the /c switch on windows 7 PC. Im getting the following error and pasted here fyi.. Its repeated many times in the command window. Logged in account has full admin permissions.

11/Nov/2015 03:25:00 [Lua.cpp:4397] WARNING: Script failure [C:\Program Files\nt
opng\scripts\callbacks/minute.lua][C:\Program Files\ntopng\scripts\callbacks/min
ute.lua:163: C:\Users\nrogers.admin\Documents\0\rrd\10\10\1\2\ICMP.rrd: illegal
attempt to update using time 1447172700 when last update time is 1447172700 (min
imum one second step)]
11/Nov/2015 03:30:01 [Lua.cpp:4397] WARNING: Script failure [C:\Program Files\nt
opng\scripts\callbacks/minute.lua][C:\Program Files\ntopng\scripts\callbacks/min
ute.lua:163: C:\Users\nrogers.admin\Documents\0\rrd\10\10\1\2\ICMP.rrd: illegal
attempt to update using time 1447173001 when last update time is 1447173001 (min
imum one second step)]
Thanks
Regards

**Comment by lmangani** [comment]
Hi @PrimaryHealthTas those look like repeated updates which migh suggest sluggish database performance with inserts. Is your system load high by any chance?
Please provide ntopng version details and startup settings.

**Comment by lucaderi** [comment]
@simonemainardi Hi Simone I think that we should change ntop.rrd_update(name, "N:".. tolongint(v)) from N (=local time) to a time % 60 sec.
@PrimaryHealthTas I have made a fix that will be included in the next Windows build.

**Comment by simonemainardi** [comment]
thanks, Luca.
