### ISSUE TITLE
Implement zoom in+out

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2631]
<img width="1294" alt="Screenshot 2019-06-04 at 16 59 45" src="https://user-images.githubusercontent.com/4493366/58890101-4800ec00-86ea-11e9-8597-41a88ae4d9ca.png">

Implement zoom in (e.g. divide the time in two centered), out (e.g. double the current time)

**Comment by emanuele-f** [comment]
![2019-06-06_17-50](https://user-images.githubusercontent.com/5488003/59047139-d56f4800-8872-11e9-9b38-7de43d2a904a.png)

Implemented
