### ISSUE TITLE
Implement alert when DNS traffic is too much

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2632]
<img width="1316" alt="Screenshot 2019-06-04 at 17 03 16" src="https://user-images.githubusercontent.com/4493366/58890317-b0e86400-86ea-11e9-8523-90ce2feb6687.png">

In the above report, this host has made far too much DNS traffic with respect to the rest of the protocols. This is clearly an anomaly. We need to implement a mechanism to detect this

**Comment by MatteoBiscosi** [comment]
Implemented using the Excessive Traffic alert (Interface alert, dynamic threshold) and by DNS Traffic Alert (Host alert, static threshold)
