### ISSUE TITLE
[NetworkInterface.cpp:150] ERROR: Unable to initialize nDPI

### ISSUE THREAD

**Issue by maravento** [ntop/ntopng#2634]
After the last update and after applying the issue [#2625](https://github.com/ntop/ntopng/issues/2625) solution ntopng stop.

ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2019-06-04 09:25:38 -05; 42s ago
  Process: 20784 ExecStopPost=/bin/sh -c /bin/echo "$(/bin/date) ntopng StopPost" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
  Process: 20783 ExecStopPost=/bin/rm -rf /run/ntopng.conf (code=exited, status=0/SUCCESS)
  Process: 20760 ExecStartPost=/bin/sh -c /bin/echo "$(/bin/date) ntopng StartPost" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
  Process: 20755 ExecStart=/usr/local/bin/ntopng /run/ntopng.conf (code=exited, status=255)
  Process: 20753 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|^[ ]*--pid.*/s/^/#/" /etc/ntopng/ntopng.conf > /run/ntopng.conf (code=exited, status=0/SUCCESS)
  Process: 20744 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exited, status=0/SUCCESS)
  Process: 20741 ExecStartPre=/bin/sh -c /bin/echo "$(/bin/date) ntopng StartPre" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
 Main PID: 20755 (code=exited, status=255)

jun 04 09:25:38 user systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
jun 04 09:25:38 user systemd[1]: Started ntopng high-speed web-based traffic monitoring and analysis tool.
jun 04 09:25:38 user ntopng[20755]: 04/Jun/2019 09:25:38 [Ntop.cpp:1916] Setting local networks to 127.0.0.0/8
jun 04 09:25:38 user ntopng[20755]: 04/Jun/2019 09:25:38 [Redis.cpp:152] Successfully connected to redis 127.0.0.1:6379@0
jun 04 09:25:38 user ntopng[20755]: 04/Jun/2019 09:25:38 [Redis.cpp:152] Successfully connected to redis 127.0.0.1:6379@0
jun 04 09:25:38 user ntopng[20755]: [NetworkInterface.cpp:150] ERROR: Unable to initialize nDPI
jun 04 09:25:38 user ntopng[20755]: [NDPI] invalid categories length: expected 106, got 105
jun 04 09:25:38 user ntopng[20755]: 04/Jun/2019 09:25:38 [NetworkInterface.cpp:150] ERROR: Unable to initialize nDPI
jun 04 09:25:38 user systemd[1]: ntopng.service: Main process exited, code=exited, status=255/n/a
jun 04 09:25:38 user systemd[1]: ntopng.service: Failed with result 'exit-code'.

As a solution measure I uninstalled and installed everything and it works again, but I do not know why this happened.

**Comment by emanuele-f** [comment]
Which ntopng version are you using? Please run `ntopng --version`. If you have manually compiled ntopng from github, please update nDPI to the latest version

**Comment by lucaderi** [comment]
Bug already fixed, please update to the latest version

**Comment by maravento** [comment]
thanks
