### ISSUE TITLE
Missing attacker IP(s)

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2635]
![alrm bug](https://user-images.githubusercontent.com/4493366/58974154-0f344600-87c2-11e9-9be4-7fb8fe6294d1.png)

Alert without an indication of who has created the problem need to be enhanced/extended

**Comment by lucaderi** [comment]
For the time being please handle the drill-down adding an icon for it.

**Comment by simonemainardi** [comment]
Drilldown buttons have been added as requested for alerts of the following types:

- alert_tcp_syn_flood
- alert_flows_flood
- alert_tcp_syn_scan

Drilldown links are as follows:

![image](https://user-images.githubusercontent.com/3397663/90642898-4100c380-e233-11ea-8df8-affbd5669880.png)

Clicking on the drilldown, with nIndex enabled, opens the host historical page with the historical number of flows (time is centered using alert timestamps) and on the flow status overview. This view should make it easy for a user to understand the type of flows which were causing issues (e.g., TCP connection refused + count in figure)

![image](https://user-images.githubusercontent.com/3397663/90643075-70afcb80-e233-11ea-9636-e7a04360c62c.png)

Clicking on each of the flow status overview type allows an extra drill-down to be performed with raw flows having the selected status

![image](https://user-images.githubusercontent.com/3397663/90644127-aa350680-e234-11ea-9dd4-3861f54a410f.png)

Both local and remote hosts are handled. When the host is remote, the resulting timeseries is not present (timeseries are only written for local hosts) but historical nindex flows are visible.
