### ISSUE TITLE
Lots of white space when attempting to print from the "Traffic Report" menu

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#2636]
#### Although the page renders compactly, the Chrome Browser Print Menu dialog box shows a tremendous amount of white space:

Here's what the web page shows:

![image](https://user-images.githubusercontent.com/48565067/58977869-97055a80-8798-11e9-9275-c3dbdf6ac4fb.png)

-------------

Here is what the Chrome Print Dialog shows, white space I am referring to circled:

![image](https://user-images.githubusercontent.com/48565067/58977819-7c32e600-8798-11e9-84e3-3ae4df934118.png)

Is there anything you can do about the gratuitous white space showing up when trying to print?

**Comment by StewAlexander-com** [comment]
Chrome version running on Windows 2010:

![image](https://user-images.githubusercontent.com/48565067/58978225-6540c380-8799-11e9-8a8b-98ae2dc3e8d0.png)

**Comment by StewAlexander-com** [comment]
Weirdly attempting to change the print layout to "landscape" mode does nothing (Chome bug?)

![image](https://user-images.githubusercontent.com/48565067/58978696-5eff1700-879a-11e9-9728-56221291d409.png)

**Comment by emanuele-f** [comment]
Currently we cannot accomodate this request. The reports export requires a rework.
