### ISSUE TITLE
Show the number of SNMP alerted interfaces in the main SNMP view

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2638]

**Comment by cardigliano** [comment]
This has been implemented, there is an "Interfaces With Errors" columns counting interfaces with Errors/Discards counters > 0 (it is possible to select since boot or since last poll). 
Any suggestion for the column name?

**Comment by cardigliano** [comment]
A new page with the full list of interfaces from all SNMP devices has also been implemented.

**Comment by emanuele-f** [comment]
> This has been implemented, there is an "Interfaces With Errors" columns counting interfaces with Errors/Discards counters > 0 (it is possible to select since boot or since last poll).
> Any suggestion for the column name?

In my opinion the dropdown shoud show the current selection: e.g. "Errors Since Boot" and "Errors Since Last Poll"

**Comment by emanuele-f** [comment]
@cardigliano we close this as implemented?

**Comment by cardigliano** [comment]
@emanuele-f yes, this was pending for review and more tests, I guess we can close it.
