### ISSUE TITLE
how to create filter to block website

### ISSUE THREAD

**Issue by adrienb4** [ntop/ntopng#264]
ntop/nDPI#115

Hello

I want to create a filter for analyze a particular website traffic. Could you give me a procedure for add this filter ?

Thank

**Comment by lmangani** [comment]
ntopng automatically provides breakdowns per protocol and filters/protos based on nDPI or user definitions. See the protos.txt example to add settings for your websites of interest. Please consult the [User Guide](https://github.com/ntop/ntopng/blob/dev/doc/UserGuide.pdf) and let us know if you run into issues.
