### ISSUE TITLE
Chart time span doesn't match the specified begin/end date and time

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#2648]
- select a custom End Dat/time from the datetimepicker to generate the chart
![image](https://user-images.githubusercontent.com/3397663/59190387-e4107480-8b7c-11e9-9c65-f587c931fe23.png)

- refresh the page and even if the url doesn't change the chart is shifted as well as the contents of the datetimepicker

![image](https://user-images.githubusercontent.com/3397663/59190395-e8d52880-8b7c-11e9-9f33-f937fdb1219a.png)

**Comment by emanuele-f** [comment]
Should be already fixed in 82305dd24a0e48130d64b0fbb8551e7b0e35632d .
