### ISSUE TITLE
Implement InfluxDB Exported Points TS

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2653]
![Screen Shot 2019-06-12 at 00 30 04](https://user-images.githubusercontent.com/4493366/59311305-4cf50b00-8ca9-11e9-83f3-a660ac2edc61.png)

**Comment by emanuele-f** [comment]
![2019-06-12_09-41](https://user-images.githubusercontent.com/5488003/59332360-8c414d00-8ce5-11e9-83e8-bed80e121cfc.png)

Already implemented, at least 1h zoom level must be selected
