### ISSUE TITLE
RTT Timeseries Invalid Chart

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2654]
![Screenshot from 2019-06-12 08-43-27](https://user-images.githubusercontent.com/4493366/59329168-8ac85280-8cee-11e9-84f7-578d3d52db25.png)

The right end of this chart is wrong
- the current time is 8:43 and the chart is back in time
- the last measurement is not zero but it looks like zero (i.e. I believe you are depicting a point in the future)

**Comment by emanuele-f** [comment]
The last point being zero is caused by the fact that 1h resolution data is being used but the continuos query for the last point has not been run yet. With dba42d5842993d8be5d139aa2728e37dff6ee7ae now the chart does not show such missing point
