### ISSUE TITLE
RTT Missing Data

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2655]
![Screenshot from 2019-06-12 08-42-38](https://user-images.githubusercontent.com/4493366/59329285-d4b13880-8cee-11e9-8a19-bb76580c72be.png)
The RTT report should include 
-  the last measurement (value and time) and numeric IP address that has been contacted
- highlight hosts that have alerts (i.e.no response in time)
- by default have a RTT value when adding a new host
- if the probe is ICMP, the chart should report ICMP and not a generic RTT that can be confused as new probes will be added
![Screenshot from 2019-06-12 08-51-42](https://user-images.githubusercontent.com/4493366/59329532-628d2380-8cef-11e9-9fd4-f84ba748c82e.png)

**Comment by emanuele-f** [comment]
Initial work in 976de25de6500a58033a500c91f129203bff7690

**Comment by emanuele-f** [comment]
Other probe types will be addressed in #2847
