### ISSUE TITLE
Create per-application report

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2656]
Currently it is not possible to compare local hosts according to a protocol (e.g. YouTube) over a period of time. It is requested to implement this enhancing the existing protocol chart
![Screenshot from 2019-06-12 08-54-23](https://user-images.githubusercontent.com/4493366/59329666-b435ae00-8cef-11e9-94ba-6a0e3cd179d5.png)

**Comment by emanuele-f** [comment]
Can the nIndex top contacts per protocol view be a solution for this?

**Comment by simonemainardi** [comment]
desirable to have the stacked chart of top contacts

**Comment by cardigliano** [comment]
This is now possible with the new UI chart component
