### ISSUE TITLE
Can't install ntopng on Linux mint

### ISSUE THREAD

**Issue by christrt9** [ntop/ntopng#2658]
I follow the instruction here: http://packages.ntop.org/apt-stable/

But i get this error 

> apt update

```
Err:17 http://packages.ntop.org/apt-stable/19.1 x64/ Release                                                                       
  404  Not Found [IP: 151.11.50.180 80]
```

> apt-get install pfring nprobe ntopng ntopng-data n2disk cento nbox 

`E: Unable to locate package nprobe
`

I have linux mint 19.1

**Comment by emanuele-f** [comment]
Linux mint is not supported, but since it's based on ubuntu you should be able to install the packages manually by downloading the debs at the bottom of the http://packages.ntop.org/apt-stable page
