### ISSUE TITLE
Having 100% packet loss

### ISSUE THREAD

**Issue by cbidwell-usgs** [ntop/ntopng#266]
Hi all,

So I've just reinstalled the ntopng-stable yum release and with my previous existing config, 
I'm getting 1,251,320 Pkts [ 100.00 % ] on all of my four interfaces.  Did something change here?

### Here is my version info:
````
 ntopng --version
v.2.0.151021 [Professional Edition]
GIT rev:   2.0-stable:a6a0601c17e7bb005bd4a6640005a45650702a58:20151021
Pro rev:   r413
System Id: 2E47D988B205A206
Built on:  CentOS Linux release 7.1.1503 (Core)
````
### Here is my config:
````
--interface p2p1
--interface p2p2
--interface p2p3
--interface p2p4

--http-port 3000

--data-dir /data/ntopng

--dns-mode 3

--disable-autologout

-G=/var/tmp/ntopng.pid

--sticky-hosts all

--daemon
--ndpi-protocols /usr/share/ntopng/protocol.protos
````

### Here is my network information:

I look at each interface and have only 1 dropped packet out of all 4:

````
p2p1: flags=4419<UP,BROADCAST,RUNNING,PROMISC,MULTICAST>  mtu 1500
        ether 00:10:18:f5:5e:88  txqueuelen 1000  (Ethernet)
        RX packets 11553437  bytes 10552005004 (9.8 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 48

p2p2: flags=4419<UP,BROADCAST,RUNNING,PROMISC,MULTICAST>  mtu 1500
        ether 00:10:18:f5:5e:89  txqueuelen 1000  (Ethernet)
        RX packets 8620769  bytes 2697741712 (2.5 GiB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 52

p2p3: flags=4419<UP,BROADCAST,RUNNING,PROMISC,MULTICAST>  mtu 1500
        ether 00:10:18:f5:5e:8a  txqueuelen 1000  (Ethernet)
        RX packets 10937661  bytes 6223710548 (5.7 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 48

p2p4: flags=4419<UP,BROADCAST,RUNNING,PROMISC,MULTICAST>  mtu 1500
        ether 00:10:18:f5:5e:8b  txqueuelen 1000  (Ethernet)
        RX packets 11654127  bytes 9099383780 (8.4 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 52
````

**Comment by simonemainardi** [comment]
@cbidwell-usgs could you please try and see what happens with just 1 interface? also try and disable sticky hosts.

Do you notice any errors on ntopng console output?

**Comment by cbidwell-usgs** [comment]
I did this with just one interface and have the same results.  Tried both
the latest *stable *version as well as the latest *development* version.
Is it an issue with the pfring configuration perhaps?

**Comment by cbidwell-usgs** [comment]
Some new developments in my dilemma -- Some background here:

The four interfaces that I'm monitoring are on network taps.  My primary interface, I tested while disabling the other four, seemed to work with no packet loss at first just like the others but once again I got packet loss (100% over time).  I'm frustrated because this worked before.  Any help on troubleshooting this issue would be appreciated.

**Comment by cbidwell-usgs** [comment]
Not sure if this helps because it doesn't give anything (that I can tell) relevant to the issue:

###
27/Nov/2015 11:08:17 [Lua.cpp:441] ntop_get_interface_hosts_info() called
27/Nov/2015 11:08:17 [Lua.cpp:224] get_allowed_nets() called
27/Nov/2015 11:08:17 [Lua.cpp:256] ntop_select_interface() called
27/Nov/2015 11:08:17 [Lua.cpp:235] getCurrentInterface() called
27/Nov/2015 11:08:17 [Lua.cpp:441] ntop_get_interface_hosts_info() called
27/Nov/2015 11:08:17 [Lua.cpp:224] get_allowed_nets() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [HTTPserver.cpp:347] [HTTP] /lua/network_load.lua
27/Nov/2015 11:08:17 [HTTPserver.cpp:379] [HTTP] /lua/network_load.lua [/usr/share/ntopng/scripts/lua/network_load.lua]
27/Nov/2015 11:08:17 [AddressTree.cpp:139] Rule 0.0.0.0/0
27/Nov/2015 11:08:17 [AddressTree.cpp:139] Rule ::/0
27/Nov/2015 11:08:17 [Lua.cpp:2658] ntop_get_dirs() called
27/Nov/2015 11:08:17 [Lua.cpp:2698] ntop_get_info() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:206] ntop_get_interface_names() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:256] ntop_select_interface() called
27/Nov/2015 11:08:17 [Lua.cpp:235] getCurrentInterface() called
27/Nov/2015 11:08:17 [Lua.cpp:2587] ntop_get_interface_stats() called
27/Nov/2015 11:08:17 [Lua.cpp:235] getCurrentInterface() called
27/Nov/2015 11:08:17 [Lua.cpp:1135] ntop_get_interface_flows_stats() called
27/Nov/2015 11:08:17 [Lua.cpp:2673] ntop_get_uptime() called
27/Nov/2015 11:08:17 [Lua.cpp:2304] ntop_get_prefs() called
27/Nov/2015 11:08:17 [Lua.cpp:3699] ntop_get_num_queued_alerts() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:256] ntop_select_interface() called
27/Nov/2015 11:08:17 [Lua.cpp:235] getCurrentInterface() called
27/Nov/2015 11:08:17 [Lua.cpp:2587] ntop_get_interface_stats() called
27/Nov/2015 11:08:17 [Lua.cpp:235] getCurrentInterface() called
27/Nov/2015 11:08:17 [Lua.cpp:1135] ntop_get_interface_flows_stats() called
27/Nov/2015 11:08:17 [Lua.cpp:2673] ntop_get_uptime() called
27/Nov/2015 11:08:17 [Lua.cpp:2304] ntop_get_prefs() called
27/Nov/2015 11:08:17 [Lua.cpp:3699] ntop_get_num_queued_alerts() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:256] ntop_select_interface() called
27/Nov/2015 11:08:17 [Lua.cpp:235] getCurrentInterface() called
27/Nov/2015 11:08:17 [Lua.cpp:2587] ntop_get_interface_stats() called
27/Nov/2015 11:08:17 [Lua.cpp:235] getCurrentInterface() called
27/Nov/2015 11:08:17 [Lua.cpp:1135] ntop_get_interface_flows_stats() called
27/Nov/2015 11:08:17 [Lua.cpp:2673] ntop_get_uptime() called
27/Nov/2015 11:08:17 [Lua.cpp:2304] ntop_get_prefs() called
27/Nov/2015 11:08:17 [Lua.cpp:3699] ntop_get_num_queued_alerts() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:256] ntop_select_interface() called
27/Nov/2015 11:08:17 [Lua.cpp:235] getCurrentInterface() called
27/Nov/2015 11:08:17 [Lua.cpp:2587] ntop_get_interface_stats() called
27/Nov/2015 11:08:17 [Lua.cpp:235] getCurrentInterface() called
27/Nov/2015 11:08:17 [Lua.cpp:1135] ntop_get_interface_flows_stats() called
27/Nov/2015 11:08:17 [Lua.cpp:2673] ntop_get_uptime() called
27/Nov/2015 11:08:17 [Lua.cpp:2304] ntop_get_prefs() called
27/Nov/2015 11:08:17 [Lua.cpp:3699] ntop_get_num_queued_alerts() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:17 [Lua.cpp:3875] ntop_lua_http_print() called
27/Nov/2015 11:08:18 [PeriodicActivities.cpp:91] Starting script /usr/share/ntopng/scripts/callbacks/second.lua
###

**Comment by cbidwell-usgs** [comment]
Some more information -- I'm seeing some interesting things in my shutdown on the ntopng logs.  

30/Nov/2015 14:57:57 [NetworkInterface.cpp:1426] Started packet polling on interface p2p1 [id: 0]...
30/Nov/2015 14:57:58 [NetworkInterface.cpp:949] Invalid packet received [len: 2966305479][MTU: 1518].
30/Nov/2015 14:57:58 [NetworkInterface.cpp:950] WARNING: If you have TSO/GRO enabled, please disable it
30/Nov/2015 14:57:58 [NetworkInterface.cpp:952] WARNING: Use: sudo ethtool -K p2p1 gro off gso off tso off
^C30/Nov/2015 15:00:16 [main.cpp:37] Shutting down...
30/Nov/2015 15:00:18 [ProtoStats.cpp:35] [IPv4]  75.61 MB/96.74 K Packets
30/Nov/2015 15:00:18 [ProtoStats.cpp:35] [IPv6]  236 B/2.00 Packets
30/Nov/2015 15:00:18 [ProtoStats.cpp:35] [ARP]   1.76 KB/30.00 Packets
30/Nov/2015 15:00:18 [ProtoStats.cpp:35] [MPLS]  0 B/0.00 Packets
30/Nov/2015 15:00:18 [ProtoStats.cpp:35] [Other] 7.39 GB/34.00 Packets

Notice the "Other" in ProtoStats.cpp.  That should be 99% IPv4.  I'm not sure why it's not.

**Comment by lucaderi** [comment]
@cbidwell-usgs Hi please update to the latest ntopng and if not working contact me directly as I want to do a remote session. Thank you

**Comment by cbidwell-usgs** [comment]
So I've got some more information.  I downgraded my server (reinstalled) with Scientific Linux (CentOS) v6.7 and got all of my patches applied, rebooted, and reinstalled ntopng and all of its dependencies and everything is working great.  I'm not getting any packet loss now.  So there is either a driver issue associated with SL7 or something else that's gone amuck.

**Comment by lucaderi** [comment]
The packages are built for CenOS so we cannot guarantee they work out of the box on other distributions If you want to use SL I suggest you to compile the app from source.

**Comment by cbidwell-usgs** [comment]
SL is essentially a clone of Red Hat just as CentOS is.  Nevertheless, I
appreciate your help in trying to narrow things down.

On Fri, Dec 4, 2015 at 11:03 AM, Luca Deri <notifications@github.com> wrote:

> The packages are built for CenOS so we cannot guarantee they work out of
> the box on other distributions If you want to use SL I suggest you to
> compile the app from source.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ntop/ntopng/issues/266#issuecomment-162036708>.
>



-- 

Chris Bidwell, CISSP, CEH, CPT
National Earthquake Information Center
US Geological Survey
email: cbidwell@usgs.gov
work: 303-273-8642
mobile: 303-435-6362
