### ISSUE TITLE
ntopng : problem with defaults entries ; TTY=unknown ; PWD=/ ; USER=root ;

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#2661]
What does this message mean repeated in the logs?
```ntopng : problem with defaults entries ; TTY=unknown ; PWD=/ ; USER=root ;```

Ntopng details:
![image](https://user-images.githubusercontent.com/48565067/59629324-92359480-9110-11e9-88f4-fd3f914b5784.png)

**Comment by emanuele-f** [comment]
Please try to modify nsswitch as explained in https://superuser.com/questions/1086152/sudo-sending-annoying-alerts-issue-with-defaults-entries .

**Comment by emanuele-f** [comment]
@StewAlexanderACC were you able to address the issue?

**Comment by StewAlexander-com** [comment]
@emanuele-f 

Yeah, I was onto other issues, checked the logs, messages are gone.
Please close this issue, sorry about the delay.

**Comment by emanuele-f** [comment]
Thank you for reporting
