### ISSUE TITLE
Statistics update on interface eth0 [VLAN Id: 110] is too slow. 

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#2662]
I am getting this message:

```
[15/06/2019 17:53:03][Slow Statistics Update][Released] Statistics update on interface eth0 [VLAN Id: 110] is too slow. This could lead to data accuracy loss and missing alerts. Update frequency can be tuned by the Hosts Statistics Update Frequency preference.
```

However my Cache Update Frequency is 1 second:
![image](https://user-images.githubusercontent.com/48565067/59633802-55bb6600-911b-11e9-8cfb-48dc3ba8c2f9.png)

**Comment by emanuele-f** [comment]
In order to fix the slow update issue you should *increase* the update frequency, try 10 seconds for example.

**Comment by StewAlexander-com** [comment]
Thank you

That is somewhat unclear via how I understood the issue, but it does make sense since I started with 3 seconds and moved it to 1 thinking, it would resolve things, which it did not.

I appreciate the feedback, @emanuele-f, can you perhaps write this somewhere. for others who may encounter the same issue? That is, if that makes sense...

In any regard, thank you for the explanation, please close this case.
