### ISSUE TITLE
Bad argument #2 to 'format' (number has no integer representation)

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2664]
Given the information provided in https://github.com/ntop/nProbe/issues/346 , the problem occurs while exporting the UDP bytes unicast/non unicast .

**Comment by emanuele-f** [comment]
@HoseinKashefi I've made a little fix in https://github.com/ntop/ntopng/commit/aa739268f73bbd6663f21164e22c51f96411cc4f and added a trace, please try again with the new ntopng package which will be available in one hour. If you still experience the problem please post the new log.

**Comment by HoseinKashefi** [comment]
errors are resolved.
Thank you

**Comment by emanuele-f** [comment]
Great
