### ISSUE TITLE
Problem with Lua influxdb Callback

### ISSUE THREAD

**Issue by jppo** [ntop/ntopng#2665]
Hello,
I am trying NtopNG with timeseries in an InflxDB database and I get some errors in the log :
----------------------------------------------------------------------------------------------------------------------------
Jun 20 18:40:00 jpcorei7 ntopng[4974]: 20/Jun/2019 18:40:00 [LuaEngine.cpp:9040] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/5min.lua][.../share/ntopng/scripts/callbacks/system/5min/influxdb.lua:60: attempt to call a nil value (global 'i18n')]
Jun 20 18:45:00 jpcorei7 ntopng: [LuaEngine.cpp:9040] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/5min.lua][.../share/ntopng/scripts/callbacks/system/5min/influxdb.lua:60: attempt to call a nil value (global 'i18n')]
------------------------------------------------------------------------------------------------------------
All other functions seems to work flawlessly.

I am using the following version :
v.3.9.190617	[Community build]
GIT rev:	dev:60d5f4e89c12cf948603c0830e8f7ab5a0ea74de:20190617

Regards
JP P

**Comment by emanuele-f** [comment]
The new package containing the fix will be available in one hour.

**Comment by jppo** [comment]
Hello,
I try it, it works, no more message.
Regards
JP P

**Comment by emanuele-f** [comment]
Thank you for reporting
