### ISSUE TITLE
Missing container menu and sort options

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2669]
![image](https://user-images.githubusercontent.com/4493366/59901916-07e57d00-93fd-11e9-9ff5-dcd1ca8b7f70.png)
The above picture contains a few bugs
1. the Client/Server RTT labels (the same inconsistency applies for instances to hosts list) are note let aligned. The label must always be left aligned, while the column content should be aligned according to the datatype
2. the container and RTT menu entries are not sortable as all other columns
3. there is no dropdown menu to restrict to flows of given containers. here you can omit the container columns if no container is found, or if you put the container menu you need to have a container menu

**Comment by simonemainardi** [comment]
Implemented. Flows are now sortable by RTT and can also be filtered according to any given container or pod.

![image](https://user-images.githubusercontent.com/3397663/60526783-4af2fa80-9cf1-11e9-9051-7568a7301303.png)
