### ISSUE TITLE
nmon.net repo not responding

### ISSUE THREAD

**Issue by juesor** [ntop/ntopng#267]
[root@ntopng ~]# yum update
Loaded plugins: fastestmirror
base                                                                                                                                                 | 3.6 kB  00:00:00
epel/x86_64/metalink                                                                                                                                 |  13 kB  00:00:00
epel                                                                                                                                                 | 4.3 kB  00:00:00
extras                                                                                                                                               | 3.4 kB  00:00:00
http://www.nmon.net/centos/7/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
http://www.nmon.net/centos/7/noarch/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.

I went to nmon.net/centos/7/x86_64/repodata/ and it redirected me to 
https://shop.ntop.org/centos/7/noarch/repodata/

Which does not hold any repo data.

**Comment by lucaderi** [comment]
@juesor We have reorganised our servers a while ago. Please reconfigure your YUM according to http://packages.ntop.org/centos/
