### ISSUE TITLE
Improve InfluxDB stats

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2672]
![Screen Shot 2019-06-21 at 08 32 46](https://user-images.githubusercontent.com/4493366/59902662-29476880-93ff-11e9-9d55-40acdbc41e8e.png)
In the influx stats some issues need to be addressed
- influx alarms are displayed under the "System Status": this is wrong as they need to be moved under the InfluxDB menu
- the term "Point" is misleading and it's not clear what is about
- the counters (ad least the non-memory/storage ones) are not JSON refreshed
- a new counter with InfluxDB import and retries must be added and put on a timeseries
![Screen Shot 2019-06-21 at 08 36 27](https://user-images.githubusercontent.com/4493366/59902875-af63af00-93ff-11e9-9cfd-eec6ffeb4e3f.png)
- the exported and dropped points should be put on the same graph (area + line)

**Comment by simonemainardi** [comment]
Negative rates appear on the right axis

![image](https://user-images.githubusercontent.com/3397663/60118211-1d9bcf00-977c-11e9-81cb-ac3d0016ba3b.png)

**Comment by simonemainardi** [comment]
charting the total exports does not give any meaningful value. An exact number is always used for gauges in ntopng except for this chart where it seems to be the sum. It is requested to chart this counter using a rate.

![image](https://user-images.githubusercontent.com/3397663/60118250-3c01ca80-977c-11e9-8d8c-04b80c627632.png)

**Comment by emanuele-f** [comment]
Export chart fixed in e51afad34400712cc156e2fc0602fc517b08f306 . Please refer to #2683 for the chart scale enhancements.
