### ISSUE TITLE
Showing a strange interface 5181/5180 on multiple devices go up and down

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#2675]
## Very Strange Interface 5180/5181 showing up on multiple devices, this isn't a "true" physical port of these switches.

Please create a filter or remove this odd stuff so that we can deduce or point to actual physical port changes versus these, thank you.

![image](https://user-images.githubusercontent.com/48565067/59925605-7418ae80-9406-11e9-912a-7731d2ecc2fe.png)
-------

They all say the same name, and their status is up or down which is giving a false result of our switch port interface changes....
![image](https://user-images.githubusercontent.com/48565067/59925662-94e10400-9406-11e9-8836-6d0495d5e1fc.png)

What are these **Stackstub** links?

**Comment by simonemainardi** [comment]
please explain, add detailed description and steps to reproduce

**Comment by StewAlexander-com** [comment]
![image](https://user-images.githubusercontent.com/48565067/59926120-9959ec80-9407-11e9-86dc-1692212461d9.png)

**Comment by StewAlexander-com** [comment]
![image](https://user-images.githubusercontent.com/48565067/59926202-d0300280-9407-11e9-8995-7f0fa5a3082d.png)

**Comment by StewAlexander-com** [comment]
![image](https://user-images.githubusercontent.com/48565067/59926253-f2298500-9407-11e9-9a26-3f77ee9759ee.png)

**Comment by StewAlexander-com** [comment]
![image](https://user-images.githubusercontent.com/48565067/59926441-50eefe80-9408-11e9-93ac-99aacea64d2b.png)

**Comment by StewAlexander-com** [comment]
![image](https://user-images.githubusercontent.com/48565067/59926518-77149e80-9408-11e9-8d28-469205ce0281.png)

**Comment by StewAlexander-com** [comment]
@emanuele-f  - have any ideas?

**Comment by emanuele-f** [comment]
So this is a virtual interface, I though such interfaces were ignored, please let me check this with my colleagues

**Comment by emanuele-f** [comment]
You can disable alerts from specific interfaces through the config page.

![2019-06-24_09-41](https://user-images.githubusercontent.com/5488003/60000321-7ae83100-9653-11e9-8733-618f2c8d36c1.png)

propVirtual interfaces cannot be ignored in general as VLAN interfaces are actually propVirtual .

**Comment by StewAlexander-com** [comment]
@emanuele-f 

 If I understand, so there is no way to filter these out since they are virtual interfaces for the vlans?

**Comment by StewAlexander-com** [comment]
Makes it very difficult then to build statistics as to actual interface port changes, a weakness of your software.

**Comment by StewAlexander-com** [comment]
I am missing the gear icon on the page to filter out this message
![image](https://user-images.githubusercontent.com/48565067/60017361-943eac80-9656-11e9-965a-6e5ebc6342e2.png)

**Comment by StewAlexander-com** [comment]
Please consider a **feature request** to add filtering to the Past Alerts screen under the "Detected Alerts" option under the Warning Icon menu

If users could filter out, or search for interfaces, IPs, statuses or other options it would be a huge benefit to your customers, not just us.

![image](https://user-images.githubusercontent.com/48565067/60017790-99e8c200-9657-11e9-9455-22cb825edd14.png)

**Comment by emanuele-f** [comment]
Please check out the latest development version of ntopng, the possibility to turn them off are added there. We only provide bug fixes for the stable, if you find something missing in the dev version we can fix it.

**Comment by StewAlexander-com** [comment]
Ok, can you point me on how to get it?

**Comment by emanuele-f** [comment]
Please follow the instruction from http://packages.ntop.org based on your repo (refer to the `nightly` builds)

**Comment by StewAlexander-com** [comment]
Weird, what we use, I believe...

This is a dev version, am I correct?
![image](https://user-images.githubusercontent.com/48565067/60026163-16d06780-9669-11e9-95e8-7c0fd6aee489.png)

**Comment by emanuele-f** [comment]
Dev version is 3.9.x

**Comment by StewAlexander-com** [comment]
Ok, thanks
