### ISSUE TITLE
Improve disk usage monitoring

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2676]
![Screen Shot 2019-06-21 at 16 46 29](https://user-images.githubusercontent.com/4493366/59930956-320e5d80-9444-11e9-9897-958699941919.png)
The way storage is monitored does not help supervising the operations. It displays the space used on disk by ntopng but it does not supervise free disk space.
It is requested to
- add monitoring for the disk partition where ntopng is running
- add an alert when the above partition is full > x %. Please set an default alert when is 90% full

**Comment by cardigliano** [comment]
The *System Status* page now displays the disk utilization including space used by the system, free space, total disk size. The data dir path and device is also reported. In case a pcap path other than the data dir has been specified in the configuration, an additional bar for that volume is displayed.
