### ISSUE TITLE
Adding ntopng to snapcraft.io

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#2677]
Hi all,

An "unofficial" looking version of **ntopng** looks to be out at https://snapcraft.io/search?q=ntopng.

Any thoughts on creating an "authoritative" version of ntopng as a snap package?

**Comment by simonemainardi** [comment]
Hi, thanks for this suggestion, unfortunately we are not able to maintain it at this time. Would you be interested in becoming the maintainer of the official snap packages?

**Comment by StewAlexander-com** [comment]
Not at the moment, but please ask the community if anyone would like to be a maintainer, as this is an interesting idea

**Comment by simonemainardi** [comment]
Ok so let me just close this for now.
