### ISSUE TITLE
Dashboard charts are not filled 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2680]
<img width="768" alt="Screenshot 2019-06-26 at 15 49 30" src="https://user-images.githubusercontent.com/4493366/60185369-1501d200-982a-11e9-8db8-c04a1560cdc7.png">
When connecting to the dashboard the above two charts are empty. It would be nice to have them with data when logging in

**Comment by simonemainardi** [comment]
will be part of dashboard redesign in 4.1
