### ISSUE TITLE
Warnings for arping between broadcast domains to from / to hosts that don't exist

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#2681]
Hi,

I am getting these ARP warnings from / to hosts in broadcast domains we don't have in our network
```
[27/06/2019 16:10:14][Broadcast domain] ARP traffic from 4C:4E:35:DC:8C:00/10.90.0.7 to 44:03:A7:68:32:90/12.195.224.10 detected. It is unlikely to see ARP traffic between those IPs as they are seemingly belonging to different broadcast domains. Check for hosts and networks configurations.
[27/06/2019 16:11:23][Broadcast domain] ARP traffic from AC:37:43:E0:D4:61/10.70.0.1 to FF:FF:FF:FF:FF:FF/100.68.142.224 detected. It is unlikely to see ARP traffic between those IPs as they are seemingly belonging to different broadcast domains. Check for hosts and networks configurations.
```
Version info for our ntopng instance:
![image](https://user-images.githubusercontent.com/48565067/60298497-a6d81080-98f8-11e9-9d1b-f97421e14500.png)

**Comment by emanuele-f** [comment]
4C:4E:35 is a Cisco manufacturer whereas AC:37:43 is HTC so they seem like valid mac addresses. Please recheck your network to see why these devices are present

**Comment by StewAlexander-com** [comment]
I have (or should have) access to all devices on our network, our Cisco equipment is on 10.2.x.x domain
```
λ ping 10.90.0.7

Pinging 10.90.0.7 with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 10.90.0.7:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
````
12.195.224.10 is not an address anywhere in our network, we use 10.x.x.x / 192.x.x.x / 172.x.x.x which are scoped as internal addresses per IANA (https://www.iana.org/), 12.x.x.x is an external address apparently owned by AT&T (https://www.iana.org/assignments/ipv4-address-space/ipv4-address-space.xhtml)

So something very odd is going on, why the ticket

**Comment by StewAlexander-com** [comment]
Our router has an IP on the 10.90.x.x domain, but it is 10.90.1, the router is a Cisco, the other devices on that network are IP phones by a different provider

**Comment by StewAlexander-com** [comment]
I did an nmap scan on the 10.90.0.7 if it is on our network, it isn't up

**Comment by emanuele-f** [comment]
These packets are being generated in the network and won't necessary match an existing host. ntopng is just reporting what it sees. If you think this is an ntopng bug you can double check with `tcpdump`

**Comment by simonemainardi** [comment]
let's take one of the two warnings as example

```
ARP traffic from 4C:4E:35:DC:8C:00/10.90.0.7 to 44:03:A7:68:32:90/12.195.224.10 detected. 
```

Means that ntopng has detected arp traffic with sender ip address 10.90.0.7 and target ip address 12.195.224.10. Both ip addresses are dissected by ntopng directly from the arp payload.

Seeing addresses which, to the best of your knowledge, are unknown doesn't mean ntopng is wrong. Among the reason there are:
- misconfigured hosts
- hidden hosts

This is why we highlight them using the warnings such as the one above. We also use them to identify `ghost broadcast domains`, that is, ranges of addresses which are not supposed to exist but for some reason we are dissecting their arp traffic. You can check those ghost broadcast domains if you visit the interface details page, tab Networks.

![image](https://user-images.githubusercontent.com/3397663/60528002-bc33ad00-9cf3-11e9-9302-20669618fe7d.png)

So the suggestion is to investigate why the highlighted mac addresses are ARPing for ips they should not ARP to, possibly fixing their configuration.

**Comment by StewAlexander-com** [comment]
Hmm,

12.x.x.x is not in the list, it wouldn't be as it is not a private IP space.
![image](https://user-images.githubusercontent.com/48565067/60529519-bf637480-9cc4-11e9-825c-f917a356399d.png)

I also do a lot of snooping for hidden hosts.

However, without a tracedump I don't really know;  if I have proof in a pcap of something odd I'll open another case.

Please close this @simonemainardi, thank you for your feedback
