### ISSUE TITLE
System alerts cannot be filtered using dropdown menus as in other windows

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2685]
![Screen Shot 2019-06-28 at 11 49 20](https://user-images.githubusercontent.com/4493366/60334007-caec2e00-999a-11e9-86e6-983ace86654d.png)

Due to the above limitation it is not clean what is going on and it is hard to search them

**Comment by emanuele-f** [comment]
Note: the above limitation is also present in any embedded alerts page, e.g. alerts for hosts. This was probably disabled due to issue in the page parameters handling

**Comment by simonemainardi** [comment]
will reconsider this issue after the rework as it may involve significant changes also in the way alerts are filtered
