### ISSUE TITLE
Ntopng is shuting down

### ISSUE THREAD

**Issue by Ccretiaux** [ntop/ntopng#269]
Hi,

As you can see in the subject, the service ntopng is stopped after 5-20 minutes.

The only error that I can see is in my syslog. Here's a screen of it.

![erreur](https://cloud.githubusercontent.com/assets/15629142/11232860/cb78b19c-8dd0-11e5-9179-7d583e735fe8.png)

I've got this error since I update ntopng to the Professional Edition.

I think I've already update my ntopng to the latest version (2.0.151021 - Professional Edition) but it didn't solved my problem.

Thanks for taking a look.

**Comment by lmangani** [comment]
Could you share your startup configuration as a starter? Please do make sure you are running on the latest build.

**Comment by simonemainardi** [comment]
@Ccretiaux we have introduced multiple fixes in the dev branch. I would suggest you to switch to the nightly builds. please see http://packages.ntop.org/

**Comment by Ccretiaux** [comment]
Sorry I wasn't on the latest version --> 2.1.
The historical function wasn't working on 2.0 version.
Thanks for your answers.
