### ISSUE TITLE
RRD Applications/Categories are Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2691]
![Screen Shot 2019-06-29 at 18 21 08](https://user-images.githubusercontent.com/4493366/60386829-b3946a00-9a9a-11e9-9097-033f9208cdbc.png)

While hosts (inside the host details) report applications and categories, the RRD graphs are empty

**Comment by simonemainardi** [comment]
Issue occurring under Windows, fixed in the latest windows build (ntopng-3.9.190702.zip).
