### ISSUE TITLE
Sometimes Local Hosts do not have RRD graphs

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2692]
![Screen Shot 2019-06-29 at 18 23 06](https://user-images.githubusercontent.com/4493366/60386844-0110d700-9a9b-11e9-82d3-7848c4fc311b.png)
RRD-based timeseries sometimes are not reported in the host details and the graph icon is missing. This does not happen all the times, but may hosts have no graph icon. Apparently there are no RRDs on disk for such host. So it is correct that the icon is missing and what's wrong is that RRDs are not present

**Comment by simonemainardi** [comment]
Issue occurring under Windows, fixed in the latest windows build (ntopng-3.9.190702.zip).
