### ISSUE TITLE
Influx memory reported by top and ntopng are inconsistent

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2694]
![Screen Shot 2019-06-30 at 09 54 43](https://user-images.githubusercontent.com/4493366/60393940-1fb7b200-9b1d-11e9-86e9-4054a09f88be.png)
![Screen Shot 2019-06-30 at 09 55 59](https://user-images.githubusercontent.com/4493366/60393964-4bd33300-9b1d-11e9-9aa4-8548b4b93384.png)
![Screen Shot 2019-06-30 at 09 55 44](https://user-images.githubusercontent.com/4493366/60393965-4bd33300-9b1d-11e9-9fd1-d0be52e31f9c.png)

**Comment by emanuele-f** [comment]
The shown memory usage is taken from InfluxDB itself as documented in https://www.influxdata.com/blog/how-to-use-the-show-stats-command-and-the-_internal-database-to-monitor-influxdb . In particular `Sys` metric is shown. Need to verify if there is a better way through the internal stats or it's better to consult some OS api

**Comment by simonemainardi** [comment]
Fixed. Explanation is available in the commit code comments.
