### ISSUE TITLE
Invalid aggregations used with InfluxDB

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2699]
![Screen Shot 2019-07-02 at 22 59 47](https://user-images.githubusercontent.com/4493366/60546208-27de4000-9d1d-11e9-9103-686ac0d0bc16.png)
As shown in the above picture, ntop has been started with an empty DB less than a day ago. This means that daily aggregation has not been performed, so it is a bug to show an empty chart, instead of using for instance the hourly aggregation.

In summary when using aggregated queries, when creating a chart from now -> back, aggregations must be selected carefully in order to avoid creating empty charts even though data is present.

**Comment by emanuele-f** [comment]
The problem seems related to the manual deletion of some /var/lib/influxdb directories. Possible to monitor CQ status with https://docs.influxdata.com/platform/monitoring/influxdata-platform/tools/measurements-internal/#queryfail .

**Comment by emanuele-f** [comment]
After internal review we decided for now not to add such monitoring, so this can be closed.
