### ISSUE TITLE
Project about Graphite

### ISSUE THREAD

**Issue by lucagiambastiani** [ntop/ntopng#27]
In our project we decide to use StatsD to take network data in SNMP protocol and put them in the Graphite's DB Carbon, but StatsD can't do this, so we need help to do this changes.
Thank you

**Comment by lmangani** [comment]
I believe there is background development ongoing on this front for proper support, in the meantime its quite easy to prototype using a small proxy application to turn JSON/TCP nprobe/ntopng reports into metric rows for Graphite/Carbon plaintext format. 
A small nodejs example: https://github.com/celand/graFwd.js
