### ISSUE TITLE
Invalid InfluxDB DB Size

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2700]
Up to today the InfluxDB was over 40GB and so I have deleted the ntopng database, removed all data and restarted Influx.

deri@ubuntu 206> sudo du -kh /var/lib/influxdb/|tail
392K	/var/lib/influxdb/data/ntopng/one_month/513/index/6
396K	/var/lib/influxdb/data/ntopng/one_month/513/index/7
396K	/var/lib/influxdb/data/ntopng/one_month/513/index/5
396K	/var/lib/influxdb/data/ntopng/one_month/513/index/2
3.1M	/var/lib/influxdb/data/ntopng/one_month/513/index
268M	/var/lib/influxdb/data/ntopng/one_month/513
268M	/var/lib/influxdb/data/ntopng/one_month
287M	/var/lib/influxdb/data/ntopng
340M	/var/lib/influxdb/data
412M	/var/lib/influxdb/

Currently the size is 412 MB as reported by the graph whereas the ntopng table still reports the old (cached?) value

![Screen Shot 2019-07-02 at 23 07 34](https://user-images.githubusercontent.com/4493366/60546749-4133bc00-9d1e-11e9-9e2c-2770e24a2ff8.png)
![Screen Shot 2019-07-02 at 23 07 05](https://user-images.githubusercontent.com/4493366/60546751-4133bc00-9d1e-11e9-8aa3-a26b58c52bd2.png)

**Comment by simonemainardi** [comment]
solved. issue was due to the `ntopng` database abruptly deleted. Information about the `ntopng database` size read from the `_internal` database, and shown in the Storage Utilization cell, was not deleted along with the database and this explains the difference.
