### ISSUE TITLE
Invalid graph labels

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2705]
![Schermata 2019-07-03 alle 08 52 20](https://user-images.githubusercontent.com/4493366/60586785-1df72400-9d93-11e9-8272-41235f3882c1.jpeg)

**Comment by emanuele-f** [comment]
Please report the chart page

**Comment by emanuele-f** [comment]
This can be reproduced in nEdge traffic chart with 5m resolution

**Comment by emanuele-f** [comment]
Issue addressed in 65580f7b623969f5068816406a0bbc995c0c99ad, waiting for customer feedback before closing this.

**Comment by emanuele-f** [comment]
Closing as no positive/negative feedback received. Assuming that fix is working, otherwise will reopen this.
