### ISSUE TITLE
Can't compile and install on Debian Buster

### ISSUE THREAD

**Issue by jppo** [ntop/ntopng#2706]
Hello,
I try to compile/install Ntopng  (3.9)on a Debian 10 (Buster), compile went OK, but install is refused :
--------------------------------------------------------------------------------
The following packages have unmet dependencies:
 ntopng : Depends: libcurl3 but it is not installable
          Depends: libmariadbclient18 but it is not installable
---------------------------------------------------------------------------------
- "libmariadbclient" version is 3 (libmariadbclient.so -> libmariadb.so.3).
- "libcurl3" is replaced by "libcurl4"

Regards
JP P

**Comment by emanuele-f** [comment]
We do not support debian buster for now in the packages. You can manually edit the control files to fix the dependencies to make it work.

**Comment by simonemainardi** [comment]
@jppo as you said you've manually compiled and installed ntopng, you have to follow this readme https://github.com/ntop/ntopng/blob/dev/doc/README.compilation. It guides you to the manual installation of dependencies as well. Try it, and if you think there is something to update for Debian10, please edit it and send us a pull request. Thank you.

**Comment by jppo** [comment]
Hello,

As you stated in your mail I had to :
- create a new file "control.10.in" from control.debian9.in
changing some packages versions :
Depends: @PFRING_DEP@, libsqlite3-0, redis-server, librrd8, logrotate,
libcurl4, libpcap0.8, libldap-2.4-2, libhiredis0.13, libssl1.0.2,
libmariadb3, lsb-release, tar, ethtool, libcap2, bridge-utils,
libnetfilter-conntrack3, libzstd1, libmaxminddb0, libradcli4, libjson-
c3, udev @EXTRA_DEPS@
- change packages version in "control" :
Depends: , libsqlite3-0, redis-server, librrd8, logrotate, libcurl4,
libpcap0.8, libldap-2.4-2, libhiredis0.13, libssl1.0.2, libmariadb3,
lsb-release, tar, ethtool, libcap2, bridge-utils, libnetfilter-
conntrack3, libzstd1, libmaxminddb0, libradcli4, libjson-c3, udev ,
debconf, libnuma1, libzmq5, libnetfilter-queue1

And the generated ".deb" are installed without any messages.

Regards

JP P
