### ISSUE TITLE
Can't install ntopng on Ubuntu 19.4

### ISSUE THREAD

**Issue by Arean71** [ntop/ntopng#2707]
Hi, I tried to install ntopng on Ubuntu, by executing the following command, but at the first step I have got an error: Connection refused.
Any body can help me?

sudo wget http://apt-stable.ntop.org/18.04/all/apt-ntop-stable.deb
--2019-07-04 00:24:30--  http://apt-stable.ntop.org/18.04/all/apt-ntop-stable.deb
Resolving apt-stable.ntop.org (apt-stable.ntop.org)... 167.99.215.164, 2a03:b0c0:2:d0::d27:3001
Connecting to apt-stable.ntop.org (apt-stable.ntop.org)|167.99.215.164|:80... failed: Connection refused.
Connecting to apt-stable.ntop.org (apt-stable.ntop.org)|2a03:b0c0:2:d0::d27:3001|:80... failed: Network is unreachable.

**Comment by cardigliano** [comment]
@Arean71 this is working for me, it could have been caused by a temporary outage, could you try again please? This said please note that you are installing a 18.04 package on ubuntu 19..
