### ISSUE TITLE
/usr/share/ntopng/scripts/lua/modules/http_lint.lua:1622: [LINT] _GET["host"] ="NGINX" parameter error: Validation error]

### ISSUE THREAD

**Issue by maccas777** [ntop/ntopng#2711]
Hi all

I am new here and new to Ntopng
after installing ntopng and running about few days i notice i have this error can some one help me 

 ntopng:  [LuaEngine.cpp:9563] WARNING: Script failure [/usr/share/ntopng/scripts/lua/host_details.lua [/usr/share/ntopng/scripts/lua/modules/http_lint.lua:1622: [LINT] _GET["host"] = "NGINX" parameter error: Validation error]

Jul 05 19:31:33 NGINX ntopng:  05/Jul/2019 11:31:33 [LuaEngine.cpp:9563] WARNING: Script failure [/usr/share/ntopng/scripts/lua/host_details.lua][/usr/share/ntopng/scripts/lua/modules/http_lint.lua:1622: [LINT] _GET["host"] = "NGINX" parameter error: Validation error]

Jul 06 02:15:49 NGINX pf_ringctl:  Error! The module pfring 7.5.0 is not currently installed.

**Comment by emanuele-f** [comment]
Hi, please post a screenshot of the "About ntopng" page, located under the home icon.

**Comment by maccas777** [comment]
HI Emanuele

Thank you for your reply 
here is the about ntopng page 
![image](https://user-images.githubusercontent.com/52458177/60817261-e68eda00-a1cd-11e9-8d65-5235049f14bf.png)

**Comment by cardigliano** [comment]
@maccas777 this should not happen as the "host" parameter should be an IP or MAC, I am trying to figure out where "NGINX" comes from, any useful information to reproduce this are welcome. I guess "NGINX" is the hostname of the machine running ntopng, correct? It would be even better if we have a chance to ssh to this machine. Thank you.

**Comment by maccas777** [comment]
HI cardigliano

Thank you for your reply
I would be ok for you to remote to my notebook and I ssh in for you
Host name 
NGINX-Server-VM 

If you can remote in via teamview that would be great

**Comment by cardigliano** [comment]
@maccas777 that would be great. Please send details to cardigliano at ntop.org

**Comment by maccas777** [comment]
> @maccas777 that would be great. Please send details to cardigliano at ntop.org

Hi cardigliano email sent to you :) thank you again

**Comment by maccas777** [comment]
Hi cardigliano 
Great that you would spent time for me to fix this issue 
I am grateful and thankful for the best support ever men 

:)

**Comment by cardigliano** [comment]
Thank you!

**Comment by daruns** [comment]
could somebody tell me what's the solution? -_-
