### ISSUE TITLE
ntopng tries "INSERT INTO `flowsv4`"  even when it cannot connect to mysql

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#2712]
Ubuntu 19.10 eoan
ndpi: 2.9.0-1599-c0d9dc9
ntopng: 3.9.190705 - Community Edition
mysql-server: 5.7.26-1

The bottom live throughput, number of local/remote hosts, number of alerts, devices & flows are not updated anymore:
![Bottom statistics](https://user-images.githubusercontent.com/13176858/60825967-2abdb280-a1ad-11e9-9268-0d6186fed3a5.png)

It used to be displayed instantly.

**Comment by jean-christophe-manciot** [comment]
ntopng has become a CPU hog:
![ntopng CPU consumption](https://user-images.githubusercontent.com/13176858/60831281-83934800-a1b9-11e9-8bd5-8ffc8113344a.png)

**Comment by jean-christophe-manciot** [comment]
Restarting mysql server seems to have worked around this issue.
I saw some strange connection errors with mysql in the log (since there was no previous issue with mysql):
```
08/Jul/2019 19:39:05 [MySQLDB.cpp:828] ERROR: Failed to connect to MySQL: Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2) [ntopng@/run/mysqld/mysqld.sock:3306]
08/Jul/2019 19:39:05 [MySQLDB.cpp:678] ERROR: INSERT INTO `flowsv4` 
```
Why does ntopng tries to ```INSERT INTO flowsv4``` despite its inability to connect to mysql?

**Comment by cardigliano** [comment]
@jean-christophe-manciot I pushed a fix for this, could you confirm it works for you now? Thank you.

**Comment by jean-christophe-manciot** [comment]
@cardigliano 
Since I have no idea what triggered this issue (mysql-server was running fine when it happened), I am unable to confirm whether your fix works correctly or not.

**Comment by cardigliano** [comment]
Let's close this and reopen it in case. Thank you.
