### ISSUE TITLE
syslog errors and flow alerts explorer tabs: summary, type, and visual dont display

### ISSUE THREAD

**Issue by stump-ed** [ntop/ntopng#2715]
(many repeats of next line:)
Jul 11 14:35:05 ntopgvm001 ntopng[8279]: 11/Jul/2019 14:35:05 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/1/rrd/10/11/49/187/udp_sent_unicast.rrd][1562855704:28332:0] failed [/var/lib/ntopng/1/rrd/10/11/49/187/udp_sent_unicast.rrd: illegal attempt to update using time 1562855704 when last update time is 1562855704 (minimum one

(many repeats of next line:)
Jul 11 14:35:32 ntopgvm001 ntopng: [LuaEngine.cpp:9892] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/flow_alerts_explorer.lua][...cripts/lua/enterprise/modules/enterprise_alert_utils.lua:473: bad argument #1 to 'for iterator' (table expected, got nil)]
Jul 11 14:35:32 ntopgvm001 ntopng[8279]: 11/Jul/2019 14:35:32 [LuaEngine.cpp:9892] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/flow_alerts_explorer.lua][...cripts/lua/enterprise/modules/enterprise_alert_utils.lua:473: bad argument #1 to 'for iterator' (table expected, got nil)]
Jul 11 14:35:41 ntopgvm001 ntopng: [LuaEngine.cpp:9892] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/flow_alerts_explorer.lua][...cripts/lua/enterprise/modules/enterprise_alert_utils.lua:473: bad argument #1 to 'for iterator' (table expected, got nil)]

my version:

3.9.190710 -  Enterprise Edition 
Ubuntu 18.04.2 LTS
Debian buster/sid [x86_64][Ubuntu 18.04.2 LTS] - 64 bit
ntopng --interface  "tcp://127.0.0.1:5556" --http-port "3000" --local-networks  "10.0.0.0/8,172.10.0.0/24" --data-dir "/var/lib/ntopng"
2.9.0-1599-c0d9dc9
7.58.0
3.x
4.x
1.7.0
1.0
5m
4.0.9
3.7
Lua 5.3.5
4.2.5
1.3.1

**Comment by emanuele-f** [comment]
We are reworking the alerts, this page is currently broken and in the todo list of #2713 . I'll close this once fixed

**Comment by emanuele-f** [comment]
A fix will be available in the tomorrow version of ntopng.
