### ISSUE TITLE
Error [LuaEngine.cpp:9091] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/second.lua][/usr/share/ntopng/scripts/lua/modules/tracker.lua:5: module 'dkjson' not found:]

### ISSUE THREAD

**Issue by maccas777** [ntop/ntopng#2716]
After reboot of my server i found this error 
 [LuaEngine.cpp:9091] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/second.lua][/usr/share/ntopng/scripts/lua/modules/tracker.lua:5: module 'dkjson' not found:]

Is there anything i can do to fix this I have try to google and look into this error code but can not find the same symptom

![image](https://user-images.githubusercontent.com/52458177/61082356-e441af80-a45b-11e9-9534-d72d4967b9c2.png)

**Comment by simonemainardi** [comment]
can you please update to the latest version and check again? I cannot reproduce.

**Comment by maccas777** [comment]
Hi simonemainardi

Can you please share me a guide on how to update to the latest version

**Comment by maccas777** [comment]
error is no longer there after update thank you simonemainardi :)

but i found another error sorry

13/Jul/2019 13:31:17 [LuaEngine.cpp:9449] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/second.lua][/usr/share/ntopng/scripts/callbacks/system/second.lua:10: module 'callback_utils' not found:]

13/Jul/2019 15:04:08 [LuaEngine.cpp:9919] WARNING: Script failure [/usr/share/ntopng/scripts/lua/admin/prefs.lua][attempt to index a nil value]
13/Jul/2019 14:42:51 [LuaEngine.cpp:9919] WARNING: Script failure [/usr/share/ntopng/scripts/lua/admin/prefs.lua][attempt to index a nil value]
13/Jul/2019 14:30:25 [LuaEngine.cpp:9919] WARNING: Script failure [/usr/share/ntopng/scripts/lua/admin/prefs.lua][attempt to index a nil value]
13/Jul/2019 14:23:13 [LuaEngine.cpp:9919] WARNING: Script failure [/usr/share/ntopng/scripts/lua/admin/prefs.lua][attempt to index a nil value]
13/Jul/2019 14:11:54 [LuaEngine.cpp:9449] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/second.lua][/usr/share/ntopng/scripts/callbacks/system/second.lua:10: module 'callback_utils' not found:]
![image](https://user-images.githubusercontent.com/52458177/61167710-2a3e6680-a575-11e9-81e1-04669ab4ae69.png)

**Comment by emanuele-f** [comment]
What OS are you using?

**Comment by maccas777** [comment]
Hi Emaunuele 

I am using CentOS Linux release 7.6.1810 (Core)

**Comment by emanuele-f** [comment]
Please check out the new package, which will be available in one hour.

**Comment by maccas777** [comment]
HI Emanuele

I have try to update and hit this error  below 

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

ndpi-2.9.0-1668.x86_64.rpm     FAILED                                          
http://packages.ntop.org/centos/7/x86_64/Packages/ndpi-2.9.0-1668.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
nprobe-8.7.190716-6566.x86_64. FAILED                                          
http://packages.ntop.org/centos/7/x86_64/Packages/nprobe-8.7.190716-6566.x86_64.rpm: [Errno 14] HTTP Error 416 - Requested Range Not Satisfiable
Trying other mirror.
ntopng-3.9.190716-6804.x86_64. FAILED                                          
http://packages.ntop.org/centos/7/x86_64/Packages/ntopng-3.9.190716-6804.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
ntopng-data-3.9.190716-6804.no FAILED                                          
http://packages.ntop.org/centos/7/noarch/Packages/ntopng-data-3.9.190716-6804.noarch.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
pfring-dkms-7.5.0-2603.noarch. FAILED                                          -:-- ETA 
http://packages.ntop.org/centos/7/noarch/Packages/pfring-dkms-7.5.0-2603.noarch.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=ntop-noarch clean metadata
Trying other mirror.
pfring-7.5.0-2603.x86_64.rpm   FAILED                                          2:04 ETA 
http://packages.ntop.org/centos/7/x86_64/Packages/pfring-7.5.0-2603.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=ntop clean metadata
Trying other mirror.


Error downloading packages:
  n2disk-3.3.190716-5151.x86_64: [Errno 256] No more mirrors to try.
  n2n-2.5.1-215.x86_64: [Errno 256] No more mirrors to try.
  ixgbevf-zc-4.5.1.2603-dkms.noarch: [Errno 256] No more mirrors to try.
  i40e-zc-2.4.6.2603-dkms.noarch: [Errno 256] No more mirrors to try.
  cento-1.9.190716-494.x86_64: [Errno 256] No more mirrors to try.
  ixgbe-zc-5.5.3.2603-dkms.noarch: [Errno 256] No more mirrors to try.
  nprobe-8.7.190716-6566.x86_64: [Errno 256] No more mirrors to try.
  ndpi-2.9.0-1668.x86_64: [Errno 256] No more mirrors to try.
  ntopng-3.9.190716-6804.x86_64: [Errno 256] No more mirrors to try.
  e1000e-zc-3.4.0.2.2603-dkms.noarch: [Errno 256] No more mirrors to try.
  ntopng-data-3.9.190716-6804.noarch: [Errno 256] No more mirrors to try.
  pfring-dkms-7.5.0-2603.noarch: [Errno 256] No more mirrors to try.
  igb-zc-5.3.5.18.2603-dkms.noarch: [Errno 256] No more mirrors to try.
  pfring-7.5.0-2603.x86_64: [Errno 256] No more mirrors to try.

**Comment by maccas777** [comment]
hi emanuele

I have update to the latest

![image](https://user-images.githubusercontent.com/52458177/61263485-3a438980-a7b3-11e9-9d24-54ed12d0f097.png)

I find this error

16/Jul/2019 11:15:45 [LuaEngine.cpp:9535] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/second.lua][/usr/share/ntopng/scripts/lua/modules/os_utils.lua:7: module 'tracker' not found:]
16/Jul/2019 11:05:48 [NetworkInterface.cpp:2715] Started packet polling on interface lo [id: 2]...

Thank you for spending time to fix this much appreciated

**Comment by simonemainardi** [comment]
I've just tried to reproduce but everything works as expected, no error:

![image](https://user-images.githubusercontent.com/3397663/61290898-45a3ae80-a7cd-11e9-9098-5e7e7ccb858d.png)


```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.6.1810 (Core)
Release:	7.6.1810
Codename:	Core
```

Please try to completely remove and re-install

**Comment by maccas777** [comment]
hi Simonemainardi

can you share me steps or link on how can i make a clean remove and clean reinstall on ntop 

as my current server is in production no reboot could be done at the moment 

Does the reinstall required reboot ?

**Comment by emanuele-f** [comment]
Hi, no need to reboot. Please perform the following steps (existing data will be lost):
```
sudo yum remove ntopng
sudo rm -rf /var/lib/ntopng
redis-cli keys "ntopng.*" | xargs redis-cli unlink
sudo yum update
sudo yum install ntopng
```

**Comment by simonemainardi** [comment]
any news?

**Comment by maccas777** [comment]
We have stop this for now will try again next week as we are currently on a project i close this for now will reopen once we move on
