### ISSUE TITLE
[nTopng] Doesn't show some data

### ISSUE THREAD

**Issue by HoseinKashefi** [ntop/ntopng#2719]
after update to following version some issues were happened:
 ntopng --version
v.3.9.190714    [Enterprise/Professional build]
[ntopng190714.log](https://github.com/ntop/ntopng/files/3390849/ntopng190714.log)
![ntopng190714(1)](https://user-images.githubusercontent.com/43135531/61196434-e5850d80-a6e3-11e9-8ccd-39386da7e6f2.jpg)
![ntopng190714(2)](https://user-images.githubusercontent.com/43135531/61196435-e61da400-a6e3-11e9-8451-2c697a7decfb.jpg)

**Comment by emanuele-f** [comment]
Have you updated cento as well?

**Comment by HoseinKashefi** [comment]
yes : v.1.9.190714

**Comment by cardigliano** [comment]
A fix for this has been pushed, a new package will be available in <1h, please update and let us know.

**Comment by HoseinKashefi** [comment]
Dear @cardigliano ,
still missing mini traffic graph (host and flows\s)
![image](https://user-images.githubusercontent.com/43135531/61279437-62d77d80-a7cb-11e9-9560-4b41aace646e.png)

**Comment by cardigliano** [comment]
@HoseinKashefi the footer is working for me, however today we made some change, I am pushing a new build. Please update later today (new packages available in 1h) and let us know. Thank you.

**Comment by HoseinKashefi** [comment]
I've updated to v.3.9.190717, unfortunately graph was not fixed. is there anything to check locally ?

**Comment by cardigliano** [comment]
@HoseinKashefi could you right click -> Inspect Element in your browser and check for javascript errors, if there is any? Thank you.

**Comment by HoseinKashefi** [comment]
errors are occurred for if_stats, here some info :
![inspect(1)](https://user-images.githubusercontent.com/43135531/61362671-d050e000-a897-11e9-85db-582f71881877.jpg)
![inspect(2)](https://user-images.githubusercontent.com/43135531/61362672-d050e000-a897-11e9-912a-c85d08e44e45.jpg)
[if_stats.lua.txt](https://github.com/ntop/ntopng/files/3400975/if_stats.lua.txt)

**Comment by cardigliano** [comment]
@HoseinKashefi I pushed a fix for this, please check the next build. Thank you.

**Comment by HoseinKashefi** [comment]
@cardigliano it's resolved but following issue is  occurred #2736
