### ISSUE TITLE
No Data in Network Interfaces: Realtime Traffic Dashboard View

### ISSUE THREAD

**Issue by kenatgcc** [ntop/ntopng#2720]
The graph is empty.

![image](https://user-images.githubusercontent.com/50203145/61216070-840c7100-a6da-11e9-9f41-7ea43b7adecd.png)

**Comment by emanuele-f** [comment]
What are the contents of your /etc/ntopng/ntopng.conf file?

**Comment by kenatgcc** [comment]
My ntopng.conf is below.

[my_ntopng.conf.txt](https://github.com/ntop/ntopng/files/3393052/my_ntopng.conf.txt)

**Comment by cardigliano** [comment]
A fix for this has been pushed, a new package will be available in <1h, please update and let us know.

**Comment by cardigliano** [comment]
Duplicate of #2719

**Comment by kenatgcc** [comment]
I updated today and the data has returned to Network Interfaces: Realtime Traffic in the dashboard.
Thanks!
