### ISSUE TITLE
[daily.lua:36] [alert_utils.lua:2011] ERROR: Unknown granularity day

### ISSUE THREAD

**Issue by Gelob** [ntop/ntopng#2721]
Seen this on startup a few times time across builds

15/Jul/2019 19:05:01 [daily.lua:36] [alert_utils.lua:2011] ERROR: Unknown granularity day

version: https://github.com/ntop/ntopng/commit/9687f6f5f1f0fca39a33d65c4b7f05f997c1c30a

**Comment by emanuele-f** [comment]
Thank you for reporting.
