### ISSUE TITLE
Remote host search is not working

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2723]
![image](https://user-images.githubusercontent.com/4493366/61292894-b4cfd180-a7d2-11e9-8de9-6c9f573e8212.png)

**Comment by emanuele-f** [comment]
Cannot reproduce. Maybe the host went idle while performing the search?

**Comment by lucaderi** [comment]
I am unable to reproduce it with the current release. Host idleness might explain even though I am not sure it was the case. I suggest to leave the code as is, given that we cannot reproduce it now.
