### ISSUE TITLE
Dashboard Network Interfaces : Last Day View Graph Inverts

### ISSUE THREAD

**Issue by kenatgcc** [ntop/ntopng#2724]

**Comment by kenatgcc** [comment]
If I watch the dashboard page for a few minutes the Last Day View  graph display flips to some kind of inverted view...
![image](https://user-images.githubusercontent.com/50203145/61318411-fe202100-a7d2-11e9-949f-88d7bcbc0c8f.png)

**Comment by simonemainardi** [comment]
which browser are you using?

**Comment by kenatgcc** [comment]
Waterfox 56.2.12 (64-bit)

**Comment by emanuele-f** [comment]
Can you check with chrome/firefox if you still have the issue?

**Comment by kenatgcc** [comment]
Waterfox 56.2.12 (64-bit)

**Comment by kenatgcc** [comment]
I used Google Chrome is up to date
Version 75.0.3770.142 (Official Build) (64-bit) and get similar views after a few minutes.

![image](https://user-images.githubusercontent.com/50203145/61646361-5cd41780-ac77-11e9-817c-3e7844117248.png)

**Comment by kenatgcc** [comment]
I did try updating ntopng:


Version | 3.9.190722 -  Enterprise Edition
-- | --
Debian GNU/Linux 9.1 (stretch)
Debian 9.1 [x86_64][Debian GNU/Linux 9.1 (stretch)] - 64 bit

**Comment by emanuele-f** [comment]
What are the contents of `/etc/ntopng/ntopng.conf` ? After the issue occurs in chrome, can you enter the browser developer console and dump the contents of the `ifaces_lastday_data` variable to file as explained in https://stackoverflow.com/questions/11849562/how-to-save-the-output-of-a-console-logobject-to-a-file/33770244#33770244 ?

**Comment by kenatgcc** [comment]
[ntopng_conf_07232019.txt](https://github.com/ntop/ntopng/files/3421279/ntopng_conf_07232019.txt)
[10.3.56.101-1563874114487.log](https://github.com/ntop/ntopng/files/3421280/10.3.56.101-1563874114487.log)
requested outputs are attached.

**Comment by kenatgcc** [comment]
Is there any other testing I can try? Do you need more logs?

**Comment by emanuele-f** [comment]
Please note that ifaces_lastday_data is not present in the files above. Can you provide access to the gui to troubleshoot the problem? You can email me at faranda@ntop.org

**Comment by emanuele-f** [comment]
The problem is probably caused by NaN values. I've committed a fix. The new package will be available in one hour, please report if it's working.

![2019-08-01_17-19](https://user-images.githubusercontent.com/5488003/62307688-91b04d80-b473-11e9-9f45-05087d243af5.png)
![2019-08-01_17-20](https://user-images.githubusercontent.com/5488003/62307703-9a088880-b473-11e9-9a4e-60e652b1f796.png)

**Comment by kenatgcc** [comment]
I do not see the new package available yet, are you still working on it?

**Comment by emanuele-f** [comment]
Please recheck now

**Comment by kenatgcc** [comment]
The graph is behaving normally after loading the new package. Is 8 the limit for interfaces displayed in that graph? I have 9 edge devices and one probe.

**Comment by emanuele-f** [comment]
Yes, there is a limit of 8 interfaces. We will take this into account for issue #1670 . Closing this one as solved.
