### ISSUE TITLE
[nIndex] ntopng not purging old flow data

### ISSUE THREAD

**Issue by Gelob** [ntop/ntopng#2725]
Under Preferences > Flow Database Dump > Flow Index Storage. I have it set to 121 days (4 months) However if I look at the data on my disk for the flows are kept I see data back to January and February.

I am using nindex for flow export (-F=nindex) in my ntopng.conf. Its been set like this for a month and no change. Been through a couple of versions and same issue. Currently on https://github.com/ntop/ntopng/commit/9687f6f5f1f0fca39a33d65c4b7f05f997c1c30a

**Comment by emanuele-f** [comment]
Do you have any errors in the ntopng log? Flows should be purged at midnight

**Comment by Gelob** [comment]
No worthwhile errors in the ntopng log. I ran `journalctl -u ntopng --since "48 hour ago"`. Only thing I see in there is `[minute.lua:32] [ts_5min_dump_utils.lua:429] ERROR: [tcp://<removed>:5556 ]Cannot complete local hosts timeseries dump. Disk slow or too many local hosts?` and should be unrelated

![Screen Shot 2019-07-18 at 8 38 32 AM](https://user-images.githubusercontent.com/422752/61463422-f0d17680-a939-11e9-8ad2-fc8f460e7413.png)

This is the size of the data on disk. I'd expect the folders 01 & 02 to be empty.
```
--- /data/ntopng/0/flows/2019 ---
   40.5 GiB [##########] /06
   31.4 GiB [#######   ] /05
   28.0 GiB [######    ] /03
   26.3 GiB [######    ] /04
   22.0 GiB [#####     ] /07
   20.2 GiB [####      ] /01
   15.6 GiB [###       ] /02
```

**Comment by Gelob** [comment]
Anything else I can do to troubleshoot?

**Comment by emanuele-f** [comment]
Please let me try to reproduce this

**Comment by emanuele-f** [comment]
Could not reproduce. I've added more traces in the new dev package, which will be available in one hour. Please update and run the script `http://127.0.0.1:3000/lua/test_delete_nindex.lua` and report the console output here. What are the contents of the `/data/ntopng/0/flows/2019/01` directory?

**Comment by Gelob** [comment]
Heres whats in those directories.

```
--- /data/ntopng/0/flows/2019/01 ---
    1.2 GiB [##########] /04
    1.1 GiB [######### ] /11
    1.0 GiB [########  ] /12
    1.0 GiB [########  ] /31
    1.0 GiB [########  ] /30
    1.0 GiB [########  ] /28
    1.0 GiB [########  ] /15
    1.0 GiB [########  ] /07
  966.0 MiB [########  ] /06
  929.8 MiB [#######   ] /05
  921.8 MiB [#######   ] /09
  917.3 MiB [#######   ] /14
  903.7 MiB [#######   ] /10
  892.8 MiB [#######   ] /25
  875.9 MiB [#######   ] /29
  873.9 MiB [#######   ] /27
  870.4 MiB [#######   ] /26
  860.3 MiB [#######   ] /13
  842.6 MiB [#######   ] /16
  842.3 MiB [#######   ] /24
  830.9 MiB [######    ] /08
  682.7 MiB [#####     ] /17
```

```
--- /data/ntopng/0/flows/2019/01/04 ---
                         /..
   58.4 MiB [##########] /18
   57.8 MiB [######### ] /17
   57.2 MiB [######### ] /16
   56.7 MiB [######### ] /22
   55.6 MiB [######### ] /15
   55.0 MiB [######### ] /20
   54.9 MiB [######### ] /21
   54.7 MiB [######### ] /19
   53.9 MiB [######### ] /23
   53.2 MiB [######### ] /14
   53.1 MiB [######### ] /00
   52.0 MiB [########  ] /04
   51.7 MiB [########  ] /13
   50.5 MiB [########  ] /01
   50.5 MiB [########  ] /03
   48.7 MiB [########  ] /02
   48.4 MiB [########  ] /12
   46.1 MiB [#######   ] /05
   43.6 MiB [#######   ] /10
   43.3 MiB [#######   ] /11
   42.5 MiB [#######   ] /06
   35.2 MiB [######    ] /08
   35.2 MiB [######    ] /09
   31.8 MiB [#####     ] /07
```
```
--- /data/ntopng/0/flows/2019/01/04/18 ---
                         /..
    9.0 MiB [##########]  IPV4_DST_ADDR.bdx
    9.0 MiB [######### ]  IPV4_SRC_ADDR.bdx
    6.1 MiB [######    ]  FIRST_SEEN.bdx
    6.1 MiB [######    ]  LAST_SEEN.bdx
    6.1 MiB [######    ]  FLOW_TIME.bdx
    4.9 MiB [#####     ]  SRC_TO_DST_BYTES.bdx
    4.5 MiB [#####     ]  IP_DST_PORT.bdx
    4.5 MiB [####      ]  IP_SRC_PORT.bdx
    2.9 MiB [###       ]  DST_TO_SRC_BYTES.bdx
    2.2 MiB [##        ]  L7_PROTO.bdx
    2.1 MiB [##        ]  PACKETS.bdx
  728.0 KiB [          ]  PROTOCOL.bdx
  292.0 KiB [          ]  IP_PROTOCOL_VERSION.bdx
   20.0 KiB [          ]  NTOPNG_INSTANCE_NAME.dat
    8.0 KiB [          ]  PROFILE.dff
    8.0 KiB [          ]  NTOPNG_INSTANCE_NAME.dff
    8.0 KiB [          ]  INTERFACE_ID.dff
    8.0 KiB [          ]  INFO.dff
    8.0 KiB [          ]  PROFILE.dat
    8.0 KiB [          ]  JSON.dat
    8.0 KiB [          ]  INTERFACE_ID.dat
    8.0 KiB [          ]  INFO.dat
    4.0 KiB [          ]  IPV6_SRC_ADDR.bdx
    4.0 KiB [          ]  IPV6_DST_ADDR.bdx
    4.0 KiB [          ]  VLAN_ID.bff
    4.0 KiB [          ]  SRC_TO_DST_BYTES.bff
    4.0 KiB [          ]  PROTOCOL.bff
    4.0 KiB [          ]  LAST_SEEN.bff
    4.0 KiB [          ]  L7_PROTO.bff
    4.0 KiB [          ]  IP_SRC_PORT.bff
    4.0 KiB [          ]  IP_PROTOCOL_VERSION.bff
    4.0 KiB [          ]  IP_DST_PORT.bff
    4.0 KiB [          ]  IPV6_SRC_ADDR.bff
    4.0 KiB [          ]  IPV6_DST_ADDR.bff
    4.0 KiB [          ]  IPV4_SRC_ADDR.bff
    4.0 KiB [          ]  FLOW_TIME.bff
    4.0 KiB [          ]  DST_TO_SRC_BYTES.bff
    4.0 KiB [          ]  BYTES.bff
```

I ran the test_delete_nindex.lua and it cleaned it up as expected. Seems like for some reason its not running nightly. I attached the log. My server is in GMT time zone if that helps any. 

[test_delete_nindex.log](https://github.com/ntop/ntopng/files/3423347/test_delete_nindex.log)

```
--- /data/ntopng/0/flows/2019 ---
                         /..
   40.3 GiB [##########] /06
   31.2 GiB [#######   ] /05
   28.5 GiB [#######   ] /07
   26.0 GiB [######    ] /04
    6.2 GiB [#         ] /03
```

**Comment by Gelob** [comment]
I checked the logs this morning after updating yesterday to https://github.com/ntop/ntopng/commit/03cec7d8311ca07ec00558859a008d14ffa89d9d but I didn't see anything related to cleanup. What should I expect to see since the additional logging was added?

**Comment by emanuele-f** [comment]
We have to understand if the daily activity is silently failing or the cleanup code not called due due some condition, we will follow up when possible, thank you for the information so far

**Comment by Gelob** [comment]
I wanted to update it still doesn't appear to be running and theirs nothing in the logs still. Currently on https://github.com/ntop/ntopng/commit/03cec7d8311ca07ec00558859a008d14ffa89d9d

**Comment by emanuele-f** [comment]
The new package will be available in one our
