### ISSUE TITLE
No "All Protocols" item in my statistic page

### ISSUE THREAD

**Issue by kingxf1995** [ntop/ntopng#2727]
VERSION: ntopng Community Edition v.3.8.190711

The page of mine
![myntopng](https://user-images.githubusercontent.com/7127170/61363189-2e8cbb80-a8b6-11e9-8fb7-787a6e7a62c4.png)

[offical guides](https://www.ntop.org/guides/ntopng/web_gui/host_details.html#statistics)
![offical](https://www.ntop.org/guides/ntopng/_images/web_gui_host_details_stats_dropdown.png)

Is that not avaliable in Community Edition？

**Comment by emanuele-f** [comment]
That is only available in the pro version.
