### ISSUE TITLE
json export

### ISSUE THREAD

**Issue by adrienb4** [ntop/ntopng#273]
How can I access to JSON exports with a wget command for example ?
What are the arguments to be passed for authentication?

**Comment by lmangani** [comment]
JSON exports are periodically pushed out, not provided via API to external clients by ntopng, if I understand the question you are posing.

**Comment by adrienb4** [comment]
I would download JSON informations from a host from a wget command. But authentification.
But authentication blocks the download

**Comment by lucaderi** [comment]
@adrienb4 In ntopng (e.g. in hosts view) you can see a download link. This is the one you should use. See also https://github.com/ntop/ntopng/blob/dev/doc/README.ntopng for learning more about authentication

**Comment by adrienb4** [comment]
yes I know. But I would retrieve information from another application

**Comment by lucaderi** [comment]
Read the document, you can

**Comment by adrienb4** [comment]
Cool. Thank :)
