### ISSUE TITLE
Invalid redirect URL during DB migration step after upgrade

### ISSUE THREAD

**Issue by fsamareanu** [ntop/ntopng#2731]
Hello,

This is still an issue with the latest nightly. Attached are a screenshot of the page + page source during DB upgrade activities. Startup arguments:

-i=enp4s0.100
-i=enp4s0.101
-i=enp4s0.102
-i=enp4s0.103
-i=enp4s0.104
-i view:enp4s0.100,enp4s0.101,enp4s0.102,enp4s0.103,enp4s0.104
--local-networks="192.168.0.0/16,172.17.172.0/24"
-F "mysql;127.0.0.1;ntopng;flows;ntopng;XXXXXXXXXXXXXX"
-n=1
--http-prefix="/ntopng"
-l=1
-w :3000
-d=/data/var/lib/ntopng

I'm attaching a screenshot of the issue + the page source generated during DB upgrade activity. There's an nginx reverse proxy that sits in front of ntopng that does SSL offloading. ntopng works fine during regular operations, only impact is on the DB upgrade screen.

[ntopng.txt](https://github.com/ntop/ntopng/files/3406613/ntopng.txt)
![ntopng](https://user-images.githubusercontent.com/38040820/61459846-afaf8580-a97e-11e9-8aa9-8eef87596f76.png)

**Comment by emanuele-f** [comment]
The alert table seems to be in progress, do you have a lot of records in the database?

**Comment by fsamareanu** [comment]
Yes, mysql DB size is 13 GB. And yes, this alert table is in progress. Once it completed application functions normally and http prefix is correctly accounted for.

**Comment by emanuele-f** [comment]
So can this be closed or there was an issue in the http prefix?

**Comment by fsamareanu** [comment]
There was an issue with http prefix not being used during the upgrade screen ntopng is generating during DB activities. Once DB activities are completed (in this case a column was being resized) ntopng functions normally.

**Comment by emanuele-f** [comment]
Do you have a screenshot/URL? The above screenshot URL seems fine with the /ntopng prefix

**Comment by fsamareanu** [comment]
If you look in the page source (ntopng.txt) you will see this:

```
<script type="text/javascript">
var intervalID = setInterval(
  function() {
   window.location.replace("http://XXX/lua/flow_details.lua?flow_key=686478073");
  },
  5000);

```
I've replaced my domain name with XXX and as you can see there's no http-prefix here. If this was generated correctly it should be something like this:

```
<script type="text/javascript">
var intervalID = setInterval(
  function() {
   window.location.replace("http://XXX/http-prefix-here/lua/flow_details.lua?flow_key=686478073");
  },
  5000);
```

**Comment by fsamareanu** [comment]
Problem seems to be in scripts/lua/please_wait.lua:

window.location.replace("]] print(host) print[[");

This doesn't seem to take into account the http prefix at all.
