### ISSUE TITLE
Web GUI - cannot sign in using PW with a space

### ISSUE THREAD

**Issue by dannysha** [ntop/ntopng#2732]
When trying to sign in to the Web GUI, once a space is entered into the Password field, both the Username and Password box outlines turn red, and the Login button reverts to faded blue and cannot be clicked.

**Comment by emanuele-f** [comment]
Please check out this if you need to reset the password: https://www.ntop.org/guides/ntopng/faq.html#cannot-login-into-the-gui

How were you able to set the password with space in the first place? It should not be possible as whitespace is not allowed

![2019-07-19_16-35](https://user-images.githubusercontent.com/5488003/61543180-805a5080-aa32-11e9-921c-07e921dcc906.png)

**Comment by dannysha** [comment]
We're using LDAP authentication :)

**Comment by emanuele-f** [comment]
The fix will be available in the next dev build (in one hour).
