### ISSUE TITLE
ERROR: rrd_update_r()

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#2734]
Every time I:

- stop ntopng
- delete the ntopng data dir
- start ntopng

I get these errors (only one time during the first update):

```
19/Jul/2019 12:35:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/192/168/2/169/udp_sent_unicast.rrd][1563532500:1064849:0] failed [/var/lib/ntopng/15/rrd/192/168/2/169/udp_sent_unicast.rrd: illegal attempt to update using time 1563532500 when last update time is 1563532500 (minimu
19/Jul/2019 12:35:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/192/168/2/169/RX.rrd][1563532500:87:0] failed [/var/lib/ntopng/15/rrd/192/168/2/169/RX.rrd: illegal attempt to update using time 1563532500 when last update time is 1563532500 (minimum one second step)]
19/Jul/2019 12:35:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/192/168/2/169/ndpi_flows/RX.rrd][1563532500:0] failed [/var/lib/ntopng/15/rrd/192/168/2/169/ndpi_flows/RX.rrd: illegal attempt to update using time 1563532500 when last update time is 1563532500 (minimum one second s
19/Jul/2019 12:35:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/192/168/2/169/SNMP.rrd][1563532500:1064762:1032949] failed [/var/lib/ntopng/15/rrd/192/168/2/169/SNMP.rrd: illegal attempt to update using time 1563532500 when last update time is 1563532500 (minimum one second step)
19/Jul/2019 12:35:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/192/168/2/169/ndpi_flows/SNMP.rrd][1563532500:0] failed [/var/lib/ntopng/15/rrd/192/168/2/169/ndpi_flows/SNMP.rrd: illegal attempt to update using time 1563532500 when last update time is 1563532500 (minimum one seco
19/Jul/2019 12:35:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/192/168/2/169/Unknown.rrd][1563532500:0:2004] failed [/var/lib/ntopng/15/rrd/192/168/2/169/Unknown.rrd: illegal attempt to update using time 1563532500 when last update time is 1563532500 (minimum one second step)]
19/Jul/2019 12:35:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/192/168/2/169/ndpi_flows/Unknown.rrd][1563532500:0] failed [/var/lib/ntopng/15/rrd/192/168/2/169/ndpi_flows/Unknown.rrd: illegal attempt to update using time 1563532500 when last update time is 1563532500 (minimum on
19/Jul/2019 12:35:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/192/168/2/169/ndpi_categories/Network.rrd][1563532500:1064762:1032949] failed [/var/lib/ntopng/15/rrd/192/168/2/169/ndpi_categories/Network.rrd: illegal attempt to update using time 1563532500 when last update time i
19/Jul/2019 12:35:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/192/168/2/169/ndpi_categories/RPC.rrd][1563532500:87:0] failed [/var/lib/ntopng/15/rrd/192/168/2/169/ndpi_categories/RPC.rrd: illegal attempt to update using time 1563532500 when last update time is 1563532500 (minim
19/Jul/2019 12:35:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/192/168/2/169/ndpi_categories/Unspecified.rrd][1563532500:0:2004] failed [/var/lib/ntopng/15/rrd/192/168/2/169/ndpi_categories/Unspecified.rrd: illegal attempt to update using time 1563532500 when last update time is
```

**Comment by simonemainardi** [comment]
happened again after 20 minutes

```
19/Jul/2019 12:55:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/1/1/1/1/bytes.rrd][1563533700:31255:14014] failed [/var/lib/ntopng/15/rrd/1/1/1/1/bytes.rrd: illegal attempt to update using time 1563533700 when last update time is 1563533700 (minimum one second step)]
19/Jul/2019 12:55:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/1/1/1/1/active_flows.rrd][1563533700:0:1] failed [/var/lib/ntopng/15/rrd/1/1/1/1/active_flows.rrd: illegal attempt to update using time 1563533700 when last update time is 1563533700 (minimum one second step)]
19/Jul/2019 12:55:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/1/1/1/1/total_flows.rrd][1563533700:0:92] failed [/var/lib/ntopng/15/rrd/1/1/1/1/total_flows.rrd: illegal attempt to update using time 1563533700 when last update time is 1563533700 (minimum one second step)]
19/Jul/2019 12:55:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/1/1/1/1/misbehaving_flows.rrd][1563533700:0:0] failed [/var/lib/ntopng/15/rrd/1/1/1/1/misbehaving_flows.rrd: illegal attempt to update using time 1563533700 when last update time is 1563533700 (minimum one second ste
19/Jul/2019 12:55:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/1/1/1/1/unreachable_flows.rrd][1563533700:0:0] failed [/var/lib/ntopng/15/rrd/1/1/1/1/unreachable_flows.rrd: illegal attempt to update using time 1563533700 when last update time is 1563533700 (minimum one second ste
19/Jul/2019 12:55:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/1/1/1/1/host_unreachable_flows.rrd][1563533700:0:0] failed [/var/lib/ntopng/15/rrd/1/1/1/1/host_unreachable_flows.rrd: illegal attempt to update using time 1563533700 when last update time is 1563533700 (minimum one
19/Jul/2019 12:55:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/1/1/1/1/dns_qry_sent_rsp_rcvd.rrd][1563533700:0:0:0] failed [/var/lib/ntopng/15/rrd/1/1/1/1/dns_qry_sent_rsp_rcvd.rrd: illegal attempt to update using time 1563533700 when last update time is 1563533700 (minimum one
19/Jul/2019 12:55:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/1/1/1/1/dns_qry_rcvd_rsp_sent.rrd][1563533700:0:0:0] failed [/var/lib/ntopng/15/rrd/1/1/1/1/dns_qry_rcvd_rsp_sent.rrd: illegal attempt to update using time 1563533700 when last update time is 1563533700 (minimum one
19/Jul/2019 12:55:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/1/1/1/1/udp_pkts.rrd][1563533700:0:1] failed [/var/lib/ntopng/15/rrd/1/1/1/1/udp_pkts.rrd: illegal attempt to update using time 1563533700 when last update time is 1563533700 (minimum one second step)]
19/Jul/2019 12:55:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/1/1/1/1/tcp_rx_stats.rrd][1563533700:0:0:0] failed [/var/lib/ntopng/15/rrd/1/1/1/1/tcp_rx_stats.rrd: illegal attempt to update using time 1563533700 when last update time is 1563533700 (minimum one second step)]
19/Jul/2019 12:55:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/1/1/1/1/tcp_tx_stats.rrd][1563533700:0:0:0] failed [/var/lib/ntopng/15/rrd/1/1/1/1/tcp_tx_stats.rrd: illegal attempt to update using time 1563533700 when last update time is 1563533700 (minimum one second step)]
19/Jul/2019 12:55:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/1/1/1/1/tcp_packets.rrd][1563533700:0:0] failed [/var/lib/ntopng/15/rrd/1/1/1/1/tcp_packets.rrd: illegal attempt to update using time 1563533700 when last update time is 1563533700 (minimum one second step)]
19/Jul/2019 12:55:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/1/1/1/1/total_alerts.rrd][1563533700:0] failed [/var/lib/ntopng/15/rrd/1/1/1/1/total_alerts.rrd: illegal attempt to update using time 1563533700 when last update time is 1563533700 (minimum one second step)]
19/Jul/2019 12:55:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/1/1/1/1/contacts.rrd][1563533700:0:1] failed [/var/lib/ntopng/15/rrd/1/1/1/1/contacts.rrd: illegal attempt to update using time 1563533700 when last update time is 1563533700 (minimum one second step)]
19/Jul/2019 12:55:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/1/1/1/1/l4protos/tcp.rrd][1563533700:0:0] failed [/var/lib/ntopng/15/rrd/1/1/1/1/l4protos/tcp.rrd: illegal attempt to update using time 1563533700 when last update time is 1563533700 (minimum one second step)]
19/Jul/2019 12:55:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/1/1/1/1/l4protos/udp.rrd][1563533700:0:83] failed [/var/lib/ntopng/15/rrd/1/1/1/1/l4protos/udp.rrd: illegal attempt to update using time 1563533700 when last update time is 1563533700 (minimum one second step)]
19/Jul/2019 12:55:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/1/1/1/1/l4protos/icmp.rrd][1563533700:0:0] failed [/var/lib/ntopng/15/rrd/1/1/1/1/l4protos/icmp.rrd: illegal attempt to update using time 1563533700 when last update time is 1563533700 (minimum one second step)]
19/Jul/2019 12:55:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/1/1/1/1/l4protos/other_ip.rrd][1563533700:0:0] failed [/var/lib/ntopng/15/rrd/1/1/1/1/l4protos/other_ip.rrd: illegal attempt to update using time 1563533700 when last update time is 1563533700 (minimum one second ste
19/Jul/2019 12:55:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/1/1/1/1/udp_sent_unicast.rrd][1563533700:0:31255] failed [/var/lib/ntopng/15/rrd/1/1/1/1/udp_sent_unicast.rrd: illegal attempt to update using time 1563533700 when last update time is 1563533700 (minimum one second s
19/Jul/2019 12:55:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/1/1/1/1/DNS.rrd][1563533700:31255:14014] failed [/var/lib/ntopng/15/rrd/1/1/1/1/DNS.rrd: illegal attempt to update using time 1563533700 when last update time is 1563533700 (minimum one second step)]
19/Jul/2019 12:55:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/1/1/1/1/ndpi_flows/DNS.rrd][1563533700:0] failed [/var/lib/ntopng/15/rrd/1/1/1/1/ndpi_flows/DNS.rrd: illegal attempt to update using time 1563533700 when last update time is 1563533700 (minimum one second step)]
19/Jul/2019 12:55:00 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/15/rrd/1/1/1/1/ndpi_categories/Network.rrd][1563533700:31255:14014] failed [/var/lib/ntopng/15/rrd/1/1/1/1/ndpi_categories/Network.rrd: illegal attempt to update using time 1563533700 when last update time is 1563533700 (mi
```

**Comment by bmansvk** [comment]
I have the same issue. The log is full of these:
`22/Jul/2019 13:15:11 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/192/168/46/67/udp_sent_unicast.rrd][1563801311:1188:0] failed [/var/lib/ntopng/0/rrd/192/168/46/67/udp_sent_unicast.rrd: illegal attempt to update using time 1563801311 when last update time is 1563801311 (minimum one
22/Jul/2019 13:15:11 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/192/168/46/67/l4protos/other_ip.rrd][1563801311:0:0] failed [/var/lib/ntopng/0/rrd/192/168/46/67/l4protos/other_ip.rrd: illegal attempt to update using time 1563801311 when last update time is 1563801311 (minimum one
22/Jul/2019 13:15:11 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/192/168/46/67/l4protos/icmp.rrd][1563801311:0:0] failed [/var/lib/ntopng/0/rrd/192/168/46/67/l4protos/icmp.rrd: illegal attempt to update using time 1563801311 when last update time is 1563801311 (minimum one second s
22/Jul/2019 13:15:11 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/192/168/46/67/l4protos/udp.rrd][1563801311:0:0] failed [/var/lib/ntopng/0/rrd/192/168/46/67/l4protos/udp.rrd: illegal attempt to update using time 1563801311 when last update time is 1563801311 (minimum one second ste
22/Jul/2019 13:15:11 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/192/168/46/67/l4protos/tcp.rrd][1563801311:0:0] failed [/var/lib/ntopng/0/rrd/192/168/46/67/l4protos/tcp.rrd: illegal attempt to update using time 1563801311 when last update time is 1563801311 (minimum one second ste
22/Jul/2019 13:15:11 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/192/168/46/67/contacts.rrd][1563801311:1:0] failed [/var/lib/ntopng/0/rrd/192/168/46/67/contacts.rrd: illegal attempt to update using time 1563801311 when last update time is 1563801311 (minimum one second step)]
22/Jul/2019 13:15:11 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/192/168/46/67/total_alerts.rrd][1563801311:0] failed [/var/lib/ntopng/0/rrd/192/168/46/67/total_alerts.rrd: illegal attempt to update using time 1563801311 when last update time is 1563801311 (minimum one second step)
22/Jul/2019 13:15:11 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/192/168/46/67/tcp_packets.rrd][1563801311:0:0] failed [/var/lib/ntopng/0/rrd/192/168/46/67/tcp_packets.rrd: illegal attempt to update using time 1563801311 when last update time is 1563801311 (minimum one second step)
22/Jul/2019 13:15:11 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/192/168/46/67/tcp_tx_stats.rrd][1563801311:0:0:0] failed [/var/lib/ntopng/0/rrd/192/168/46/67/tcp_tx_stats.rrd: illegal attempt to update using time 1563801311 when last update time is 1563801311 (minimum one second s
22/Jul/2019 13:15:11 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/192/168/46/67/tcp_rx_stats.rrd][1563801311:0:0:0] failed [/var/lib/ntopng/0/rrd/192/168/46/67/tcp_rx_stats.rrd: illegal attempt to update using time 1563801311 when last update time is 1563801311 (minimum one second s
22/Jul/2019 13:15:11 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/192/168/46/67/udp_pkts.rrd][1563801311:0:0] failed [/var/lib/ntopng/0/rrd/192/168/46/67/udp_pkts.rrd: illegal attempt to update using time 1563801311 when last update time is 1563801311 (minimum one second step)]
22/Jul/2019 13:15:11 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/192/168/46/67/dns_qry_rcvd_rsp_sent.rrd][1563801311:0:0:0] failed [/var/lib/ntopng/0/rrd/192/168/46/67/dns_qry_rcvd_rsp_sent.rrd: illegal attempt to update using time 1563801311 when last update time is 1563801311 (mi
22/Jul/2019 13:15:11 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/192/168/46/67/dns_qry_sent_rsp_rcvd.rrd][1563801311:15:15:0] failed [/var/lib/ntopng/0/rrd/192/168/46/67/dns_qry_sent_rsp_rcvd.rrd: illegal attempt to update using time 1563801311 when last update time is 1563801311 (
22/Jul/2019 13:15:11 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/192/168/46/67/host_unreachable_flows.rrd][1563801311:0:0] failed [/var/lib/ntopng/0/rrd/192/168/46/67/host_unreachable_flows.rrd: illegal attempt to update using time 1563801311 when last update time is 1563801311 (mi
22/Jul/2019 13:15:11 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/192/168/46/67/unreachable_flows.rrd][1563801311:0:0] failed [/var/lib/ntopng/0/rrd/192/168/46/67/unreachable_flows.rrd: illegal attempt to update using time 1563801311 when last update time is 1563801311 (minimum one
22/Jul/2019 13:15:11 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/192/168/46/67/misbehaving_flows.rrd][1563801311:0:0] failed [/var/lib/ntopng/0/rrd/192/168/46/67/misbehaving_flows.rrd: illegal attempt to update using time 1563801311 when last update time is 1563801311 (minimum one
22/Jul/2019 13:15:11 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/192/168/46/67/total_flows.rrd][1563801311:17:0] failed [/var/lib/ntopng/0/rrd/192/168/46/67/total_flows.rrd: illegal attempt to update using time 1563801311 when last update time is 1563801311 (minimum one second step
22/Jul/2019 13:15:11 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/192/168/46/67/active_flows.rrd][1563801311:1:0] failed [/var/lib/ntopng/0/rrd/192/168/46/67/active_flows.rrd: illegal attempt to update using time 1563801311 when last update time is 1563801311 (minimum one second ste
22/Jul/2019 13:15:11 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/192/168/46/67/bytes.rrd][1563801311:1188:1994] failed [/var/lib/ntopng/0/rrd/192/168/46/67/bytes.rrd: illegal attempt to update using time 1563801311 when last update time is 1563801311 (minimum one second step)]
22/Jul/2019 12:55:10 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/10/10/5/113/udp_sent_unicast.rrd][1563800107:0:0] failed [/var/lib/ntopng/0/rrd/10/10/5/113/udp_sent_unicast.rrd: illegal attempt to update using time 1563800107 when last update time is 1563800107 (minimum one second
22/Jul/2019 12:55:10 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/10/10/5/113/l4protos/other_ip.rrd][1563800107:0:0] failed [/var/lib/ntopng/0/rrd/10/10/5/113/l4protos/other_ip.rrd: illegal attempt to update using time 1563800107 when last update time is 1563800107 (minimum one seco
22/Jul/2019 12:55:10 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/10/10/5/113/l4protos/icmp.rrd][1563800107:0:0] failed [/var/lib/ntopng/0/rrd/10/10/5/113/l4protos/icmp.rrd: illegal attempt to update using time 1563800107 when last update time is 1563800107 (minimum one second step)
22/Jul/2019 12:55:10 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/10/10/5/113/l4protos/udp.rrd][1563800107:0:0] failed [/var/lib/ntopng/0/rrd/10/10/5/113/l4protos/udp.rrd: illegal attempt to update using time 1563800107 when last update time is 1563800107 (minimum one second step)]
22/Jul/2019 12:55:10 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/10/10/5/113/l4protos/tcp.rrd][1563800107:0:0] failed [/var/lib/ntopng/0/rrd/10/10/5/113/l4protos/tcp.rrd: illegal attempt to update using time 1563800107 when last update time is 1563800107 (minimum one second step)]
22/Jul/2019 12:55:10 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/10/10/5/113/contacts.rrd][1563800107:0:1] failed [/var/lib/ntopng/0/rrd/10/10/5/113/contacts.rrd: illegal attempt to update using time 1563800107 when last update time is 1563800107 (minimum one second step)]
22/Jul/2019 12:55:10 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/10/10/5/113/total_alerts.rrd][1563800107:0] failed [/var/lib/ntopng/0/rrd/10/10/5/113/total_alerts.rrd: illegal attempt to update using time 1563800107 when last update time is 1563800107 (minimum one second step)]
22/Jul/2019 12:55:10 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/10/10/5/113/tcp_packets.rrd][1563800107:0:0] failed [/var/lib/ntopng/0/rrd/10/10/5/113/tcp_packets.rrd: illegal attempt to update using time 1563800107 when last update time is 1563800107 (minimum one second step)]
22/Jul/2019 12:55:10 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/10/10/5/113/tcp_tx_stats.rrd][1563800107:0:0:0] failed [/var/lib/ntopng/0/rrd/10/10/5/113/tcp_tx_stats.rrd: illegal attempt to update using time 1563800107 when last update time is 1563800107 (minimum one second step)
22/Jul/2019 12:55:10 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/10/10/5/113/tcp_rx_stats.rrd][1563800107:2:0:0] failed [/var/lib/ntopng/0/rrd/10/10/5/113/tcp_rx_stats.rrd: illegal attempt to update using time 1563800107 when last update time is 1563800107 (minimum one second step)
22/Jul/2019 12:55:10 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/10/10/5/113/udp_pkts.rrd][1563800107:0:0] failed [/var/lib/ntopng/0/rrd/10/10/5/113/udp_pkts.rrd: illegal attempt to update using time 1563800107 when last update time is 1563800107 (minimum one second step)]
22/Jul/2019 12:55:10 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/10/10/5/113/dns_qry_rcvd_rsp_sent.rrd][1563800107:0:0:0] failed [/var/lib/ntopng/0/rrd/10/10/5/113/dns_qry_rcvd_rsp_sent.rrd: illegal attempt to update using time 1563800107 when last update time is 1563800107 (minimu
22/Jul/2019 12:55:10 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/10/10/5/113/dns_qry_sent_rsp_rcvd.rrd][1563800107:0:0:0] failed [/var/lib/ntopng/0/rrd/10/10/5/113/dns_qry_sent_rsp_rcvd.rrd: illegal attempt to update using time 1563800107 when last update time is 1563800107 (minimu`
