### ISSUE TITLE
No remote IP addresses are resolved into host names

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#2737]
Ubuntu 19.10
ntopng 3.9.190717 - Community Edition
ndpi 2.9.0-1629-c083596

Only the name of the local router appear in the ```Name``` column:
![Reverse DNS Issue](https://user-images.githubusercontent.com/13176858/61595898-1346e680-abfd-11e9-93d8-7d6ba3feeda7.png)

I don't know if this is expected, but it would be much better to resolve each numeric IP address into host name (**reverse DNS lookup**)  so that each line shows the FQDN of each remote host in the name column, like Wireshark does for instance.

**Comment by simonemainardi** [comment]
See

```
[--dns-mode|-n] <mode>              | DNS address resolution mode
                                    | 0 - Decode DNS responses and resolve
                                    |     local numeric IPs only (default)
                                    | 1 - Decode DNS responses and resolve all
                                    |     numeric IPs
                                    | 2 - Decode DNS responses and don't
                                    |     resolve numeric IPs
                                    | 3 - Don't decode DNS responses and don't
                                    |     resolve numeric IPs
```

Basically you need 1.

**Comment by jean-christophe-manciot** [comment]
@simonemainardi 
You are so quick to dismiss issues: in my ```/etc/ntopng```, I have:
```
#       -n|--dns-mode
#        Sets the DNS address resolution mode: 
#        0 - Decode DNS responses and resolve
#            local numeric IPs only (default)
#        1 - Decode DNS responses and resolve all
#            numeric IPs
#        2 - Decode DNS responses and don't
#            resolve numeric IPs
#        3 - Don't decode DNS responses and don't
#            resolve numeric IPs
#
-n=1
```

**Comment by simonemainardi** [comment]
> You are so quick to dismiss issues: in my /etc/ntopng, I have:

You are so quick to post new issues: you didn't mention you were using -n=1.

Click on any of the hosts with name `bbox` and look at its details. There will be table Additional Host Names which should list the DNS-resolved name, e.g.,

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/3397663/61770874-9b401280-adee-11e9-83e3-8020e412cc31.png">

If there is no such field, then the resolution could have failed because:
- You have too many remote hosts (ntopng mitigates the resolution rate or it would DDoS the resolver)
- There's no FQDN associated to the ip address

Resolution stats are printed by ntopng when it exits:

```
[AddressResolution.cpp:61] Address resolution stats [7 resolved][17 failures]
```

**Comment by jean-christophe-manciot** [comment]
There is no FQDN in the details either.
- I have no resolution stats because I use a systemd service and no such stats appear in syslog nor on the CLI when the service is stopped.
```
# systemctl status ntopng
● ntopng.service - ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool
   Loaded: loaded (/lib/systemd/system/ntopng.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Wed 2019-07-24 12:23:11 CEST; 6s ago
     Docs: man:ntopng(8)
           file:/usr/share/doc/ntopng/README.Debian
           file:/usr/share/doc/ntopng/UserGuide.pdf.gz
  Process: 6933 ExecStartPre=/bin/bash -c ntopng-utils-manage-config -a check-restore  && ntopng-utils-manage-config -a restore || true (code=exited, status=0/SUCCESS)
  Process: 6958 ExecStart=/usr/bin/ntopng /etc/ntopng/ntopng.conf (code=exited, status=0/SUCCESS)
 Main PID: 6960 (code=exited, status=0/SUCCESS)

Jul 24 12:00:20 samsung4-ubuntu systemd[1]: Starting ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool...
Jul 24 12:00:20 samsung4-ubuntu ntopng[6958]: 24/Jul/2019 12:00:20 [Ntop.cpp:1909] Setting local networks to 192.168.1.0/24
Jul 24 12:00:20 samsung4-ubuntu ntopng[6958]: 24/Jul/2019 12:00:20 [Redis.cpp:152] Successfully connected to redis 127.0.0.1:6379@0
Jul 24 12:00:20 samsung4-ubuntu ntopng[6958]: 24/Jul/2019 12:00:20 [Redis.cpp:152] Successfully connected to redis 127.0.0.1:6379@0
Jul 24 12:00:20 samsung4-ubuntu ntopng[6958]: 24/Jul/2019 12:00:20 [Ntop.cpp:1849] Parent process is exiting (this is normal)
Jul 24 12:00:20 samsung4-ubuntu systemd[1]: Started ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool.
Jul 24 12:23:03 samsung4-ubuntu systemd[1]: Stopping ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool...
Jul 24 12:23:11 samsung4-ubuntu systemd[1]: ntopng.service: Succeeded.
Jul 24 12:23:11 samsung4-ubuntu systemd[1]: Stopped ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool.
```
- if I restart ntopng, it clears the remote hosts list; only a few pop up as remote hosts;
- there is a FQDN outside of ntopng for each of them;, for instance: 
```
# dig-get-fqdn.sh 1.0.0.1
one.one.one.one
# dig-get-fqdn.sh 8.8.8.8
dns.google
# dig-get-fqdn.sh 37.187.122.11 
berlix.fraho.eu
```
The reverse DNS lookup should be done as soon as one appears in the list/cache.
 I suppose it is done with the wrong IP address: bbox is the local **NAT router**, so it is done with the local router instead of the true remote IP address.

**Comment by jean-christophe-manciot** [comment]
This issue has been solved here. https://github.com/ntop/ntopng/issues/2799#issue-488503182
