### ISSUE TITLE
nprobe service not started in windows

### ISSUE THREAD

**Issue by AnanthGopal** [ntop/ntopng#2738]
nprobe service not started in windows

![image](https://user-images.githubusercontent.com/13050426/61651528-ae11f480-acd3-11e9-842e-59e432290682.png)

**Comment by emanuele-f** [comment]
Please open an issue on the nprobe page (https://github.com/ntop/nProbe/issues) and close this one.

Which nprobe version are you using? Which command did you use to install the service? If you run it manually from console (without the `/i` option), does it run properly?

**Comment by AnanthGopal** [comment]
I find the solution for that issue. I uninstall Win10Pcap and install WinPcap_4_1_3.exe.. then it's working fine
