### ISSUE TITLE
How to use local database in ntop

### ISSUE THREAD

**Issue by AnanthGopal** [ntop/ntopng#2740]
Anyone can help to connect MySQL database? When I try to configure MySql, I got below error
![](https://user-images.githubusercontent.com/13050426/61716964-d22a1000-ad7d-11e9-8f72-cb07a92d2f9e.png)

**Comment by simonemainardi** [comment]
Add a `/c` after `ntopng` and before all other options.

And do not cross post as you've done in https://github.com/ntop/ntopng/issues/2220#issuecomment-514215567.

**Comment by AnanthGopal** [comment]
hi @simonemainardi  when i run this cmd   ntopng /c --community -i tcp://127.0.0.1:5556 i got below error in centos but its working fine in windows. 
![image](https://user-images.githubusercontent.com/13050426/63425221-ae65f280-c42d-11e9-83c7-f64c3c482562.png)

**Comment by simonemainardi** [comment]
address already in use: it means there's some other program using port 3000 - possibly another ntopng instance is already running?
