### ISSUE TITLE
NTOPNG using a lot of memory

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#2745]
NTOP is using all available memory, no matter how much we give it.

```
CPU%	MEM%	VIRT	RES	PID	USER
51.1	89.1	15.6G	13.3G	4797	ntopng
```

**Comment by simonemainardi** [comment]
Please report os and ntopng version (update ntopng to the latest version if not already done) and also attach the configuration used and any relevant preference you’ve set from the gui.

**Comment by StewAlexander-com** [comment]
![image](https://user-images.githubusercontent.com/48565067/61903768-5520a700-aef3-11e9-8d91-e06aa2db9eea.png)

![image](https://user-images.githubusercontent.com/48565067/61903799-6c5f9480-aef3-11e9-9f63-a9f2c5d727c8.png)

![image](https://user-images.githubusercontent.com/48565067/61903836-8305eb80-aef3-11e9-9506-70efb2094d56.png)

![image](https://user-images.githubusercontent.com/48565067/61903863-93b66180-aef3-11e9-8736-aa53cda561bd.png)

![image](https://user-images.githubusercontent.com/48565067/61903884-a16be700-aef3-11e9-824d-a6ea0d904b29.png)

![image](https://user-images.githubusercontent.com/48565067/61903910-b5afe400-aef3-11e9-9e17-9321c36ab1a8.png)

![image](https://user-images.githubusercontent.com/48565067/61903938-c6605a00-aef3-11e9-8d1b-d49b9ae96b7d.png)

![image](https://user-images.githubusercontent.com/48565067/61903972-d710d000-aef3-11e9-8246-5b4d7e7f8aa9.png)

![image](https://user-images.githubusercontent.com/48565067/61904000-e6901900-aef3-11e9-907c-21539d3857bf.png)

![image](https://user-images.githubusercontent.com/48565067/61904017-f14aae00-aef3-11e9-83c5-dcd08045d0d9.png)

![image](https://user-images.githubusercontent.com/48565067/61904041-01fb2400-aef4-11e9-84a0-d460f56299c9.png)

**Comment by StewAlexander-com** [comment]
SSH isn't even working due to memory constraints

![image](https://user-images.githubusercontent.com/48565067/61904388-c1e87100-aef4-11e9-98b2-037f37a4e899.png)

The Ubuntu Linux prompt isn't coming up, not enough memory because NTOPNG is eating it all

**Comment by StewAlexander-com** [comment]
![image](https://user-images.githubusercontent.com/48565067/61904903-d5e0a280-aef5-11e9-9dac-306a24e75785.png)
![image](https://user-images.githubusercontent.com/48565067/61904945-e5f88200-aef5-11e9-90a8-8ebf907e1af9.png)

**Comment by StewAlexander-com** [comment]
![image](https://user-images.githubusercontent.com/48565067/61904990-ff99c980-aef5-11e9-8471-7ff7e9a56710.png)

**Comment by simonemainardi** [comment]
hi, I've made a fix that should address this issue and #2743. New packages are being built. Please, hold on one hour from now, then update ntopng to the latest version, and let us know.

**Comment by StewAlexander-com** [comment]
It doesn't appear to be consuming as much, looks about 50% after upgrading

![image](https://user-images.githubusercontent.com/48565067/61952133-0f122480-af81-11e9-9197-9b0faa3118df.png)

**Comment by simonemainardi** [comment]
ok good. please keep an eye on it and let me know if it grows and ends up in using all the available mem or if it is stable.

**Comment by StewAlexander-com** [comment]
I'll watch for any signs of "memory leaks" or memory expansion, and I will let you know

**Comment by StewAlexander-com** [comment]
Output of glances (https://nicolargo.github.io/glances/):

![image](https://user-images.githubusercontent.com/48565067/61953508-92814500-af84-11e9-94e8-586097c4905d.png)

**Comment by StewAlexander-com** [comment]
Still good, if there is a mem leak it is much slower than previously, thanks

htop output:
![image](https://user-images.githubusercontent.com/48565067/61960627-d3cd2100-af93-11e9-8032-aeabeb0091dd.png)

**Comment by simonemainardi** [comment]
Thanks for reporting. Please, check out #2743 and tell me if that is solved as well. Very likely they were related.
