### ISSUE TITLE
PKG_CHECK_MODULES(NDPI, libndpi >= 2.0

### ISSUE THREAD

**Issue by PHCSJC** [ntop/ntopng#2748]
aarch64,This is my compiler setup:

apt-get install build-essential git autoconf libtool libpcap-dev libpng-dev libzmq5-dev default-libmysqlclient-dev -y
cd /usr/src
git clone https://github.com/ntop/nDPI.git
cd nDPI; ./autogen.sh; ./configure; make; cd ..
git clone https://github.com/ntop/ntopng.git
cd ntopng
./autogen.sh
./configure
make

this time,I got this issue:

root@aml:/usr/src/ntopng# ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
./configure: line 3928: syntax error near unexpected token `NDPI,'
./configure: line 3928: `PKG_CHECK_MODULES(NDPI, libndpi >= 2.0,'

what wrong?thanks!

**Comment by emanuele-f** [comment]
Have you run `./autogen.sh` into ntopng? Please note that compiling as root is discouraged

**Comment by PHCSJC** [comment]
yes,I have run ./autogen.sh in ntopng,and I use root test compiler,so it is not problem,thanks!

**Comment by emanuele-f** [comment]
Please run the following commands into the ntopng source directory to clean up and retry:

```
make clean
./autogen.sh
./configure
make
```

**Comment by PHCSJC** [comment]
Hi,the same issue:

root@aml:~# cd /usr/src/ntopng/
root@aml:/usr/src/ntopng# make clean
make: *** No rule to make target 'clean'.  Stop.
root@aml:/usr/src/ntopng# ./autogen.sh
Wait please...
configure.ac:45: error: possibly undefined macro: AC_MSG_RESULT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:101: error: possibly undefined macro: AC_MSG_CHECKING
autoreconf: /usr/bin/autoconf failed with exit status: 1

Now run ./configure
root@aml:/usr/src/ntopng# ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
./configure: line 3928: syntax error near unexpected token `NDPI,'
./configure: line 3928: `PKG_CHECK_MODULES(NDPI, libndpi >= 2.0,'
root@aml:/usr/src/ntopng#

**Comment by emanuele-f** [comment]
You are probably missing the `pkg-config` package. Please install all the requirements as explained in https://github.com/ntop/ntopng/blob/dev/doc/README.compilation .

**Comment by PHCSJC** [comment]
ok，I have installed pkg-config,and have successed compiler ，thanks!
