### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by seismiccollision** [ntop/ntopng#275]
I'm getting the following error and ntopng is crashing
Nov 21 17:37:50 net-flows kernel: [275981.881742] ntopng[4316]: segfault at f4e ip 000000000041a1ac sp 00007ffc5313dae0 error 4 in ntopng[400000+200000]

v.2.1.151112 [Professional Edition]
GIT rev:   dev:f7208e925415eb66b88b562fb635cde77e9791ac:20151112
Pro rev:   r515
System Id: 6883D57176056201
Built on:  Ubuntu 14.04.2 LTS

**Comment by simonemainardi** [comment]
please use the latest nightly build (http://packages.ntop.org/). We have fixed a few issues. Let me know

**Comment by seismiccollision** [comment]
testing, will let you know if it happens again
thanks!

**Comment by mjgehrmann** [comment]
I have same or very similar issue:

2015-11-26T00:01:33.079106+00:00 ec419 kernel: [ 2621.573567] ntopng[1604]: segfault at 7f01de69a7e0 ip 00007f01de69a7e0 sp 00007f02137fabb8 error 15

Linux ec419 3.2.0-94-virtual #134-Ubuntu SMP Fri Nov 6 19:00:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

ntopng version: 2.1.151125

**Comment by simonemainardi** [comment]
does it crash immediately after starting up? could you please post exact ntopng configuration?

**Comment by lucaderi** [comment]
@mjgehrmann Can you please generate a core dump and share it for analysis?

**Comment by mjgehrmann** [comment]
I've updated to  v.2.1.151126 and the problem has not re-occurred. It would happen in < 6hrs after restarting the daemon.

Config Attached:
[ntopng.conf.txt](https://github.com/ntop/ntopng/files/45310/ntopng.conf.txt)

**Comment by mjgehrmann** [comment]
Core dump from previous segfault: https://www.dropbox.com/s/lypz54zixmay3du/_usr_bin_ntopng.0.crash.gz?dl=0

**Comment by lucaderi** [comment]
@mjgehrmann I have looked at the file you sent us, but unfortunately it is a text file not a core file. In case it will happen again please send us a core file and the binary so I am sure I analyse the correct information. Thanks fo your support.

**Comment by mjgehrmann** [comment]
I extracted a coredump from a new recent segfault.

https://www.dropbox.com/s/enuaaeiugmmz5c7/CoreDump.gz?dl=0

**Comment by lucaderi** [comment]
@mjgehrmann I am trying to figure out how the bug can happen. The only thing I can think about is that you have modified the traffic profiles almost at the same time ntopng crashed. Can you confirm this perhaps?

**Comment by seismiccollision** [comment]
The issue occurred again using the suggested build while I was on vacation
Nov 24 18:12:42 dev-net-flows kernel: [537019.071342] ntopng[7250]: segfault at f4e ip 000000000041a1ac sp 00007fffa4792570 error 4 in ntopng[400000+201000]

I last started ntopng at 23/Nov/2015 09:02:59 so it took some time

I will collect a core the next time it happens
My configuration is as follows (sanitized):
```
root@dev-net-flows:/var/tmp/ntopng# cat /etc/ntopng/ntopng.conf 
-G=/var/tmp/ntopng.pid
-i=tcp://127.0.0.1:5556 
-d=/var/tmp 
-w=3000 
-m="10.0.0.0/8,192.168.0.0/16,172.16.0.0/12" 
-e= 
-F="mysql;localhost;ntopng;flows;" 
-A=2 
-C= 
-D=all 
-E=all 
-S=all 
-W=3001
```

**Comment by lucaderi** [comment]
@seismiccollision Can you please update to the current development version (I have just made a change) and try to crash it again. I have not identified the symptom of the problem, just the effect :-). Thanks for your support.

**Comment by mjgehrmann** [comment]
@lucaderi - Some changes were made to traffic profiles around the time the segfault occurred.

**Comment by lucaderi** [comment]
@mjgehrmann so try the new version that the fax might help

**Comment by seismiccollision** [comment]
@lucaderi Crashed again over the weekend before i setup core dump. I have it configured now though so I should have some data in a couple days

**Comment by seismiccollision** [comment]
@lucaderi Crashed again but this time here is a core dump
https://www.dropbox.com/s/e1rmwbk1asesa55/core.ntopng.20095.flows.1449801924.gz?dl=0

**Comment by simonemainardi** [comment]
hi @seismiccollision thanks for the core dump. Could you please post a `ntopng --version` of the ntopng that originated the core dump?

**Comment by seismiccollision** [comment]
@simonemainardi I am not sure which version I had been using at the time of the latest core dump. It would have been one of the latest around a week ago but I know I have upgraded since

currently I am running the following:
v.2.3.151215 [Professional Edition]
GIT rev:   dev:1d9f04e004f802aeebf629c8740b8fd0c76935b7:20151215
Pro rev:   r525
System Id: 6883D57176056201
Built on:  Ubuntu 14.04.2 LTS

**Comment by lucaderi** [comment]
@seismiccollision I thank you for the efforts, I am sorry but your core does not help as in order to use it we need *both* the ntopng binary and the core. I have tried with the above version you specified but it does not match with the source code. I ask you please to provide us a coredump+ntopng binary (or send us the exact release as you did above). Thanks again.

**Comment by seismiccollision** [comment]
@lucaderi I went back through my session logs and the best I can tell is I was running the following version when that core dump occurred:
09/Dec/2015 12:51:22 [Ntop.cpp:260] Welcome to ntopng x86_64 v.2.3.151202 - (C) 1998-15 ntop.org

I hope that is some help

**Comment by simonemainardi** [comment]
I manually checked out ntopng @ 5897eea  which is supposed to be the source complied in v.2.3.151202. I compiled and run the debugger but the stack trace does not seem to yield consistent information. @seismiccollision I am not sure v.2.3.151202 is the right version.

```
(gdb) backtrace
#0  0x000000000041a1f6 in Flow::get_protocol_name (this=0x0) at /home/simone/ntopng/include/Flow.h:187
#1  0x0000000000414cf3 in Flow::update_hosts_stats (this=0x7f89063385e0, tv=0x7ffc84697540) at src/Flow.cpp:740
#2  0x000000000045445d in find_host_by_name (h=0x0, user_data=0x0) at src/NetworkInterface.cpp:1652
#3  0x000000000041b84a in GenericHash::findByKey (this=0xceb00000bb8, key=0) at src/GenericHash.cpp:255
#4  0x00000000004544d7 in find_host_by_name (h=0x7936fdea3fe68800, user_data=0xb490ff99d0)
    at src/NetworkInterface.cpp:1656
#5  0x0000000000455a24 in NetworkInterface::printAvailableInterfaces (this=0x0, printHelp=false, idx=0, ifname=0x0, 
    ifname_len=0) at src/NetworkInterface.cpp:2135
#6  0x000000000045c29c in _GLOBAL__sub_I__ZN11NtopGlobalsC2Ev () at src/NtopGlobals.cpp:41
#7  0x0000000000459aab in Ntop::loadLocalInterfaceAddress (this=0x1d0d6b0) at src/Ntop.cpp:513
#8  0x000000000044c591 in Prefs::getInterfaceAt (this=0x7ffc84697830, id=0) at /home/simone/ntopng/include/Prefs.h:194
#9  0x00000000c95d70a1 in ?? ()
#10 0x0000000000404d54 in ?? ()
#11 0x00007ffc84697918 in ?? ()
#12 0x0000000200000410 in ?? ()
#13 0x000000007b968901 in ?? ()
#14 0x00007f8900000000 in ?? ()
#15 0x0000003000000030 in ?? ()
#16 0x0000000600000040 in ?? ()
#17 0x0000000000000000 in ?? ()
(gdb) f 0
#0  0x000000000041a1f6 in Flow::get_protocol_name (this=0x0) at /home/simone/ntopng/include/Flow.h:187
187   inline char* get_protocol_name()                { return(Utils::l4proto2name(protocol));   };
(gdb) f 1
#1  0x0000000000414cf3 in Flow::update_hosts_stats (this=0x7f89063385e0, tv=0x7ffc84697540) at src/Flow.cpp:740
740       srv_network_stats->incEgress(diff_rcvd_bytes);
(gdb) f 2
#2  0x000000000045445d in find_host_by_name (h=0x0, user_data=0x0) at src/NetworkInterface.cpp:1652
1652        if((host->get_name() == NULL) && host->get_ip()) {
(gdb) 

```

What I can suggest is to run ntopng again with `ulimit -c unlimited` and,  if you end up in having another core dump, post both the core dump and ntopng --version output.

**Comment by seismiccollision** [comment]
experienced another segfault but some of my core config disappeared so it didn't collect... i'll get it right next time

fwiw

```
Log:
kernel: [112868.910651] ntopng[1558]: segfault at 0 ip 0000000000417ffe sp 00007ffc37468d10 error 4 in ntopng[400000+203000]

Version:
v.2.3.151231 [Professional Edition]
GIT rev:   dev:ebbf0b3ac7d26609768e9358b36394f5d36cee17:20151231
Pro rev:   r528
System Id: 6883D57176056201
Built on:  Ubuntu 14.04.3 LTS
```

**Comment by seismiccollision** [comment]
@simonemainardi 
here we go
core: https://www.dropbox.com/s/aq5vfvdliqqdttk/core.ntopng.7752.flows.1452114519.gz?dl=0

Log:
Jan  6 13:08:39 flows kernel: [526018.635535] ntopng[7752]: segfault at 0 ip 0000000000417ffe sp 00007ffd837344a0 error 4 in ntopng[400000+203000]

Version:
v.2.3.151231 [Professional Edition]
GIT rev:   dev:ebbf0b3ac7d26609768e9358b36394f5d36cee17:20151231
Pro rev:   r528
System Id: 6883D57176056201
Built on:  Ubuntu 14.04.3 LTS

**Comment by seismiccollision** [comment]
@simonemainardi 

a second segfault
core: https://www.dropbox.com/s/4b7eaw8w0nseuav/core.ntopng.9989.flows.1452225844.gz?dl=1

same version
Jan  7 20:04:04 flows kernel: [637234.772577] ntopng[9989]: segfault at 0 ip 0000000000417ffe sp 00007fff27f28a50 error 4 in ntopng[400000+203000]

**Comment by lucaderi** [comment]
@seismiccollision I have committed a patch and soon a new build will be ready. Please try again. This said I think that in your setup you need to increase -x/-X as you're running out of resources. Please report the test outcome.

**Comment by seismiccollision** [comment]
@lucaderi I am patching as we speak and I will report back. I am not sure what you mean by "you need to increase -x/-X", can you please explain? Thanks!

**Comment by alberk8** [comment]
Hi,
I think what Luca is alluding to is the max number of Flows and Hosts parameter.  what is shown below would be the default value.  May I know what is the bandwidth that you are monitoring with ntopng?  Thanks.

 (Max number of active flows)
-X 131072

(Max number of active hosts)
-x 131072

**Comment by seismiccollision** [comment]
@alberk8 Thanks for the clarification! I am making use of sflow for this so the volume of sflow is pretty low at ~1Mbps but it represents ~3Gbps average of flows with peaks of 25Gbps according to ntopng, all internet-facing so the quantity of flagged remote addresses remains relatively high. Also, this is just a sample of the total sflow data I was planning to collect. Based on the above I expect ntopng to view the contained flows from all my data sources to have an average of 30-60Gbps

**Comment by seismiccollision** [comment]
@lucaderi @simonemainardi 
experienced another crash on the following version:
v.2.3.160111 [Professional Edition]
GIT rev:   dev:aab4e1a85d0a312c6f0987e2243ca1ceabb701ad:20160111
Pro rev:   r536
System Id: 6883D57176056201
Built on:  Ubuntu 14.04.3 LTS

It didn't generate a core dump and I'm not sure why

Log: 
kernel: [88218.988431] ntopng[1370]: segfault at 30 ip 000000000041d0d6 sp 00007f4a8d1e2ac0 error 4 in ntopng[400000+202000]

for what it's worth I was using ntopng last night before the crash and it seemed to be operating well. it had ~125,000 tracked hosts and ~1000 flows and seemed more stable at that scale than in previous versions

**Comment by seismiccollision** [comment]
uptime of over 2 days now which is further than i had gotten in the past. ~130k tracked hosts and ~1100flows. starting to increase amount of sflow data
the only thing that is very sluggish is the traffic graphs

**Comment by lucaderi** [comment]
If you have so many hosts/flows please increase -x and -X to double the value you have.
Example -x=260000 ....

**Comment by seismiccollision** [comment]
@lucaderi  Thanks for the tip! I've fixed that now
