### ISSUE TITLE
Host parameter error: Validation error

### ISSUE THREAD

**Issue by fnetto** [ntop/ntopng#2751]
Getting this error on a new deployment:

Script "/usr/share/ntopng/scripts/lua/host_details.lua" returned an error:
/usr/share/ntopng/scripts/lua/modules/http_lint.lua:1471: [LINT] _GET["host"] = "private.host.name" parameter error: Validation error

Can generate this error by going into (from a host)  Peers-> Clicking on some clickable nodes

Version: 3.8.190730 - Professional Edition
Built on | Ubuntu 18.04.2 LTS
InfluxDB | 1.7.7
Redis Server | 4.0.9
Platform | Debian buster/sid [x86_64][Ubuntu 18.04.2 LTS] - 64 bit

Startup Line | ntopng --user "root" --dns-mode "1" --http-port "0" --https-port "3001" --local-networks "172.16.10.0/23,172.16.100.0/24,172.16.101.0/24,172.16.200.0/24,10.10.203.0/24,10.10.103.0/24,10.10.12.0/24" --sticky-hosts "local" --data-dir "/mount/storage/ntopng" --interface "tcp://127.0.0.1:5556" --ndpi-protocols "/etc/ntopng/my.protos"

Tried to delete data (Delete Interface Data) a couple of times and I still keep getting the error.
Enabled Error Logging and I could not see the error pertaining to the script.
This is a clean install  and any data can be discarded.
![Cap653](https://user-images.githubusercontent.com/10910468/62435246-149a0800-b701-11e9-834f-2cfb8f0c9612.png)

![Cap652](https://user-images.githubusercontent.com/10910468/62435175-dbfa2e80-b700-11e9-93a9-513148531d0c.png)

**Comment by emanuele-f** [comment]
Fixed in f45e68bb95fed722b45f706df7db2371936038f5 . A new package will be available in one hour.

**Comment by fnetto** [comment]
Okay!  I am in shock!  I am Senior Solution Architect in the US and I deal with so many large SW Vendors and I identify bugs or issues, now none of these large vendors could ever deliver such a fast response including a fix that all it took was 2 command lines.   

**Your team rocks** and that is the reason why I love NTOP and been using it for the longest time!

Thank you again for such a quick response and accepted solution.

**Comment by emanuele-f** [comment]
Thank you!
