### ISSUE TITLE
Debian buster support

### ISSUE THREAD

**Issue by fsamareanu** [ntop/ntopng#2752]
Hello,

Now that buster's stable, are there any plans to add nightly builds for it? I've been running it fine for a couple of months by changing manually the dependency to libcurl4 instead of the old version and an override file like this:

root@gemma:~# cat /etc/systemd/system/ntopng.service.d/override.conf
[Service]
Environment="LD_LIBRARY_PATH=/usr/local/curl/:$LD_LIBRARY_PATH"

root@gemma:~# ls /usr/local/curl/ -l
total 512
-rw-r--r-- 1 root staff 522656 Jan 13  2019 libcurl.so.3
lrwxrwxrwx 1 root staff     12 Jan 13  2019 libcurl.so.4 -> libcurl.so.3

**Comment by emanuele-f** [comment]
Debian buster support fixed in 1afab2aa5f7a7128ffca117895fe801d7da7eb6b . ntopng is now available for debian buster from our repositories. Missing ldap/radius support will be fixed soon.
