### ISSUE TITLE
WARNING: ntopng has not been compiled with libcap-dev

### ISSUE THREAD

**Issue by PHCSJC** [ntop/ntopng#2756]
My compiler process:

apt install build-essential git autoconf libtool libpcap-dev pkg-config libcurl4-openssl-dev libmaxminddb-dev libsqlite3-dev libreadline-dev librrd-dev libssl1.0-dev -y
apt install libpng-dev libzmq5-dev default-libmysqlclient-dev -y

cd /usr/src
wget -O nDPI-2.6.tar.gz https://github.com/ntop/nDPI/archive/2.6.tar.gz
tar zxvf nDPI-2.6.tar.gz
mv nDPI-2.6/ nDPI
cd nDPI
./autogen.sh
./configure
make

cd /usr/src
wget -O ntopng-3.8.tar.gz https://github.com/ntop/ntopng/archive/3.8.tar.gz
tar zxvf ntopng-3.8.tar.gz
mv ntopng-3.8 ntopng
cd ntopng
./autogen.sh
./configure
make
make install

Then I startup ntopng,I get below warning,what can I do with using libcap-dev?thanks!

Aug  8 19:51:13 localhost ntopng: [Utils.cpp:3055] WARNING: ntopng has not been compiled with libcap-dev
Aug  8 19:51:13 localhost ntopng: [Utils.cpp:3056] WARNING: Network discovery and other privileged activities will fail

**Comment by emanuele-f** [comment]
Hi, you need to install `libcap-dev` with `sudo apt-get install libcap-dev`. Please check out https://github.com/ntop/ntopng/blob/dev/doc/README.compilation for full dependencies.

**Comment by PHCSJC** [comment]
ok,thanks!
