### ISSUE TITLE
System setup error after detach an interface & factory reset

### ISSUE THREAD

**Issue by dvdgnwn** [ntop/ntopng#2758]

**Comment by dvdgnwn** [comment]
This morning I detach an interface in nEdge instance using Openstack Horizon portal, then I did factory reset in nEdge website. Then I would like configure nEdge again from beginning by clik "System Setup", however then appears error like this:

![photo_2019-08-09_14-47-33](https://user-images.githubusercontent.com/22539531/62763031-c09e7300-bab4-11e9-8f46-23b496857fa2.jpg)

I'm using ntopng Edge Pro Linux (x64) version 3.8.190729 - Edition

**Comment by simonemainardi** [comment]
@dvdgnwn can you please try and repeat all the steps using nEdge version 3.9 and see if you are experiencing it again? thank you.

**Comment by dvdgnwn** [comment]
Hi @simonemainardi , do you mean install nEdge from beginning using this guide?
http://packages.ntop.org/apt-stable/

**Comment by simonemainardi** [comment]
correct. please, first uninstall then reinstall.

**Comment by emanuele-f** [comment]
@dvdgnwn as written in telegram the error above should be already fixed. Simone, please refer to fix 8a5a2afae731d708f8d1a48653655fff001ca041 in ntopng pro 3.8

**Comment by dvdgnwn** [comment]
@simonemainardi @emanuele-f  I see, yesterday I retire the nEdge license, and this morning I request new nEdge license but I did not uninstall the existing nEdge.

So what should I do now? Should I do retire the license again, then I do uninstall and re-install the nEdge?

**Comment by simonemainardi** [comment]
try and simply update with `apt-get update && apt-get install nedge`

**Comment by dvdgnwn** [comment]
@simonemainardi @emanuele-f , in System Setup now appears setting for LAN (ens3, ens4) and WAN (ens3, ens4), but in nEdge web only shown Interface nf:0.
Do you have suggestion about that?

![2019-08-15 14_22_30-Window](https://user-images.githubusercontent.com/22539531/63079293-29c82f80-bf68-11e9-88bd-60065c155b0f.png)

**Comment by emanuele-f** [comment]
`nf:0` is always shown in the footer, this is expected. It represents the traffic that flows into nEdge. If the original issue is solved, please close this .
