### ISSUE TITLE
Ability to filter by TOS

### ISSUE THREAD

**Issue by EpiqSty** [ntop/ntopng#2759]
Hi,

We are using ntopng Enterprise with nIndex as historical storage.
As the traffic inputs we're using nProbe.  In nprobe debug log I see incoming pakets with TOS flag set:
`Aug 09 13:26:39 rz1voipsniffer01 nprobe[21986]: 09/Aug/2019 13:26:39 [engine.c:2840] New Flow: [tcp] 172.16.23.160:49401 -> 172.16.23.197:1435 [00:00:00:00:00:00 -> 00:00:00:00:00:00][vlan 0/0][tos 2][ifIdx: 709 -> 102][subflowId: 0/0x0000][idx=25719][firstSeen=1565349960/25][direction: RX][probe: 172.16.31.124]
Aug 09 13:26:39 rz1voipsniffer01 nprobe[21986]: 09/Aug/2019 13:26:39 [engine.c:2840] New Flow: [tcp] 172.16.2.120:50000 -> 172.16.2.76:36156 [00:00:00:00:00:00 -> 00:00:00:00:00:00][vlan 0/0][tos 0][ifIdx: 708 -> 322][subflowId: 0/0x0000][idx=80750][firstSeen=1565349985/0][direction: RX][probe: 172.16.31.124]`

But how could I filter out such information about TOS in the ntopng interface? For example, If i selecting RAW Flows?

Thanks in advance!

**Comment by EpiqSty** [comment]
Actually, I've found an exporter tool like http://<ntopng.url>/lua/pro/nindex_topk.lua, there I was trying to see at least if Ntopng has such field, but when I'am selecting SRC_TOS in Select Keys, the "Run query" command shows me:
`ERROR: No error`

this is an example of query:
http://<ntopng.url>/lua/pro/nindex_topk.lua?select_keys_clause=IPV4_SRC_ADDR%2CIPV4_DST_ADDR%2CL7_PROTO%2CSRC_TOS&select_values_clause=BYTES&where_clause=&begin_time_clause=1565378367&end_time_clause=1565378407&flow_clause=flows&approx_search=true&maxhits_clause=10&topk_clause=SUM

So I would like to hear any information, regarding how to see anything about SRC_TOS in the ntopng.

**Comment by simonemainardi** [comment]
SRC_TOS is not available as an nIndex column in ntopng, so you won't be able to search for it. However, we are integrating nIndex directly with nProbe so that you'll get all the fields specified in the nProbe template -T as nIndex columns. Please, follow up on nProbe.
