### ISSUE TITLE
Info - MySQL DB structure

### ISSUE THREAD

**Issue by AntonMay** [ntop/ntopng#276]
Hi

We have ntopng & nprobe setup. Ntopng has been setup as the collector. Ntopng dumps the historical data into a MySQL DB. With this we are then comparing the data with our other services.

I have a few questions regarding the MySQL DB (will add as I go along & I hope it is in the correct place).

1. When is a new table created from flows? Currently it is now on 7

mysql> show tables;
+------------------+
| Tables_in_ntopng |
+------------------+
| flowsv4_0        |
| flowsv4_1        |
| flowsv4_2        |
| flowsv4_5        |
| flowsv4_6        |
| flowsv4_7        |
| flowsv6_0        |
| flowsv6_1        |
| flowsv6_2        |
| flowsv6_5        |
| flowsv6_6        |
| flowsv6_7        |
+------------------+
12 rows in set (0.00 sec)

2. FIRST_SWITCHED & LAST_SWITCHED is the dates and times of the flow, what does it mean or how does it work ? Is it the first packet received in the flow, but then what does last mean?

mysql> select inet_ntoa(IP_SRC_ADDR), inet_ntoa(IP_DST_ADDR), FROM_UNIXTIME(FIRST_SWITCHED ), FROM_UNIXTIME(LAST_SWITCHED) from flowsv4_7 limit 5;+------------------------+------------------------+--------------------------------+------------------------------+
| inet_ntoa(IP_SRC_ADDR) | inet_ntoa(IP_DST_ADDR) | FROM_UNIXTIME(FIRST_SWITCHED ) | FROM_UNIXTIME(LAST_SWITCHED) |
+------------------------+------------------------+--------------------------------+------------------------------+
| 10.164.103.1           | 192.54.112.30          | 2015-11-23 07:48:16            | 2015-11-23 07:48:16          |
| 10.164.103.2           | 197.86.183.193         | 2015-11-23 07:50:56            | 2015-11-23 07:51:05          |
| 197.86.183.193         | 10.164.103.2           | 2015-11-23 07:50:56            | 2015-11-23 07:51:09          |
| 10.165.4.224           | 10.164.103.2           | 2015-11-23 07:51:28            | 2015-11-23 07:51:30          |
| 10.165.4.224           | 10.164.103.2           | 2015-11-23 07:51:28            | 2015-11-23 07:51:28          |
+------------------------+------------------------+--------------------------------+------------------------------+
5 rows in set (0.00 sec)

That is it for now.

Anton

**Comment by lucaderi** [comment]
1. tables are created (if not present) at ntopng startup. They are two tables (one for IPv4 and one for IPv6) partitioned in sub-tables.
2. First/last switched is the time of the first/last packet for the flow insert in the DB. For long standing flows they are cut periodically in sub-flows with the same IP/port/proto.

**Comment by lmlawas** [comment]
Is there a way to get the start time and end time of each src-dest pairing, and then dump it to MySQL? Thank you.

**Comment by simonemainardi** [comment]
Sure, enable mysql dump with option -F and you will find start and end time in table colums first_switched and last_switched, respectively
