### ISSUE TITLE
how to monitor a particular ip address.

### ISSUE THREAD

**Issue by AnanthGopal** [ntop/ntopng#2763]
Hi,

I need to monitor a particular IP and port, not the entire system, how can I add IP. Can you provide the cmd for that?

**Comment by simonemainardi** [comment]
create a BPF filter and add it to the ntopng configuration using option -B

```
[--packet-filter|-B] <filter>       | Ingress packet filter (BPF filter)
```

for example, to only monitor host 1.2.3.4 you can do

```
-B "host 1.2.3.4"
```

**Comment by AnanthGopal** [comment]
When I execute the above command in CentOs I got Below error 
![image](https://user-images.githubusercontent.com/13050426/63427022-c770a280-c431-11e9-8155-b741ba06e266.png)
 
How can I resolve that issue?

**Comment by simonemainardi** [comment]
there's another program using port 3000 - possibly another ntopng instance is already running.

**Comment by AnanthGopal** [comment]
yes. But I monitor more IP so that I used this command 

> -B "host 1.2.3.4"

in windows, that's working fine(Already instance running and use above command that's working) but centOs I got above error. 

My requirement is 
  Already ntopng is running 3000. then I need to monitor some more IP. How can I achieve this?

**Comment by simonemainardi** [comment]
you have to find out which process is using port 3000, stop it, then start ntopng.

**Comment by AnanthGopal** [comment]
Thank you for your response.

i think you are understanding my question. 

When we install ntopng, then ntopng use default port 3000 and started to listen to that particular system or server. 

now i need to add another IP to monitor by using ntopng /c --community -B "host 1.2.2.2";

similarly, i will add more IP to listen so that i asked help to you.

**Comment by emanuele-f** [comment]
You can use -B `host 1.2.2.2 or host 3.4.4.4`. `-B` accepts a standard BPF filter https://biot.com/capstats/bpf.html . On the other hand, if you really want to run two separate ntopng instances, then you need to specify a different listening port with `-w` (e.g. `-w 3001`). You will also need to specify different `-d` and `-r` parameters.
