### ISSUE TITLE
Ease nProbe and ntopng integration

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2765]
The ntopng manual is very short when describing the integration with nPronbe. Only this page is available https://www.ntop.org/guides/ntopng/case_study/using_with_nprobe.html

It is requested
1. to add a sample configuration file in both nprobe (in this case two files have to be generated once for flow collection and one for flow generation from packets) and ntopng packages that can be use as quick-start examples. They must include everything that a user needs to start ntopng and nprobe.
2. as of 1. modify the ntopng and nprobe manuals to explain how to do this. Note that as of today the nprobe manual does not include any reference to ntopng, but only the other way round

**Comment by cardigliano** [comment]
Sample files are now installed under /etc/ntopng and /etc/nprobe, and instructions have been added to the documentation.
