### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by t0m5k1** [ntop/ntopng#2766]
Fresh installation on ArchLinux
Since installation I am unable to login with admin, admin.
I have tried the following commands:
redis-cli del ntopng.user.admin.password

this just does nothing, I'm still unable to login and after 1 single failure I get total lockout for 5 minutes.
Trying to remove the lock out with:
for k in `redis-cli keys ntopng.cache.failed_logins.*`; do redis-cli del $k; done
does nothing as well.

How did I install:
https://aur.archlinux.org/packages/ntopng/

What do I do to get access to this or do I have to drop it and look for an alternative that will let me login to a fresh install?

**Comment by t0m5k1** [comment]
Additionally all commands that were run were after stopping ntopng with:
systemctl stop ntopng

**Comment by simonemainardi** [comment]
1. stop ntopng
2. `redis-cli flushall`
3. `rm -rf /var/lib/ntopng/runtimeprefs.json`
4. restart ntopng

Then check with admin/admin again

**Comment by t0m5k1** [comment]
Did not work

**Comment by simonemainardi** [comment]
The one I've described above is the standard procedure to reset the admin password. As you are running ntopng on Archlinux which we do not officially support and you've also installed it using AUR, which we also do not officially support, there could be something else I am not aware of.

Can you please first try and search/ask in the AUR community for the package (I can see there are several pages of comments there) to see if there's someone else having your issue?

**Comment by t0m5k1** [comment]
Thanks for the "go elsewhere your not supported!"

I'll do just that even though clearly something is wrong on the back end.
All an AUR install does is build from source using very simple bash commands with nothing fancy being added.

If I install from Arch repo's I end up with a 3 year old version which I'm sure you will promptly tell me is also not supported due to age.

I think with my experience of the latest ntop ...n ahem g and this support I'll not bother with a license and try a totally different product.

I'll let you close this as not supported/won't fix
