### ISSUE TITLE
ntopng@ systemd template missing

### ISSUE THREAD

**Issue by EpiqSty** [ntop/ntopng#2768]
in multi-instances ntopng configuration we're missing systemd template, such as:
 /etc/systemd/system/ntopng@.service

Could you please provide some example?
At the moment we're created systemd services by hands, but we are not sure what to do with 
`ExecStartPre=/bin/sh -c '/usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true'`
line in case of multi-instances setup.
Thanks in advance!

**Comment by simonemainardi** [comment]
Hi, I've deployed the `ntopng@` service file and updated the docs. A new build will be available in one hour (ntopng 3.9) and you'll find the docs at https://www.ntop.org/guides/ntopng/how_to_start/running_as_a_daemon.html
