### ISSUE TITLE
Historical Data Explorer, Flow Search Criteria, jumping time

### ISSUE THREAD

**Issue by psct** [ntop/ntopng#2771]
While trying to set a time frame for data exploration the selected interval jumps back one hour after hitting "Search Flows". 

Example: Begin <date> 09:04:00 and End <date> 10:04:00 jumps after hitting "Search Flows" to <date> 08:04:00 and End <date> 09:04:00. 

It looks like the data fetched uses the "modified" interval.

If I hit "Search Flows" multiple times the interval jumps back on hour after another. 

I am running 3.9.190813 on Raspbian Buster, ntopng Enterprise/Embedded Edition.

Timezone on Raspbian is on local timezone as well as on my sql (checked by select now();)). I've tried several browsers on macOS and Linux.

**Comment by simonemainardi** [comment]
Hi, thanks for reporting. There was an issue with daylight savings time. New builds are in progress. Please, hold on a couple of hours and try again.
