### ISSUE TITLE
Implement alert timeseries

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2772]
(Local) Hosts (as well all alarm-able entities) should implement two timeseries
- (counter) with the number of flow alerts (host-only)
- (gauge) with the list of engaged alerts (all)

The counters that will be used by these timeseries need to be exported in the GUI. In particular on the host report (hosts_stats.lua) it would be nice to have columns with such counters.

**Comment by emanuele-f** [comment]
Implemented in 69cd896a9fb822116376ebe4ad974811432237d9 and 1032af0d8f414409666a13e7664f18745cbf5e9c
