### ISSUE TITLE
List Download Errors are Not Meaningful

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#2777]
![image](https://user-images.githubusercontent.com/3397663/63426051-36d69a00-c412-11e9-9f72-b77c397ddbda.png)

"The server connection timeout out after 0 seconds [HTTP Code: 0]" is meaningless. Cannot timeout after 0 seconds. HTTP code cannot be zero.

**Comment by emanuele-f** [comment]
In what conditions is this reproduced?

**Comment by simonemainardi** [comment]
should be when the host cannot communicate to the internet
