### ISSUE TITLE
Create DNS Host report

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2779]
Using nIndex, generate a per-host report about DNS usage over a specified period of time

**Comment by simonemainardi** [comment]
This can now be obtained with the new nIndex explorer by selecting the host, either as client, as server, or both, and the application DNS. Example:

![image](https://user-images.githubusercontent.com/3397663/130778365-46a4beb2-bddc-43c9-ab75-9e4fa4a37801.png)
