### ISSUE TITLE
nprobe mysql dump

### ISSUE THREAD

**Issue by AntonMay** [ntop/ntopng#278]
Hi

I'm trying to push nprobe into a mysql db, but it's not being inserted into the db. The ntopng historical is.

This is the nprobe conf file

-n=10.164.0.1:6343
-n=10.165.0.1:6343
-n=10.166.0.253:6343
-i=none
-t=60
-d=60
-a=0
-e=1
-B=10
-w=128000
-z=0
-S=1:1
-E=0:0
-g=/var/run/nprobe-file.pid
-3=6343
--zmq=tcp://127.0.0.1:5556
--vlanid-as-iface-idx=none
-T=%IN_BYTES %IN_PKTS %PROTOCOL %SRC_TOS %TCP_FLAGS %L4_SRC_PORT %IPV4_SRC_ADDR %INPUT_SNMP %L4_DST_PORT %IPV4_DST_ADDR %OUTPUT_SNMP %LAST_SWITCHED %FIRST_SWITCHED
-V=9
--mysql=127.0.0.1:nrpobe:flows:nprobe:nprobe
--dump-stats=/var/log/nprobe/file-0_flows_stats.txt

**Comment by simonemainardi** [comment]
not an ntopng related issue. Please post the issue here https://github.com/ntop/nProbe/issues
