### ISSUE TITLE
Correct Licensing for record traffic

### ISSUE THREAD

**Issue by ronynelson** [ntop/ntopng#2785]
Hello I need Ntop to keep network traffic records for six months. What license do I need for ntop to store the collected data?

**Comment by emanuele-f** [comment]
Hi, assuming that you are capturing packets from a port mirror or similar (see https://www.ntop.org/nprobe/network-monitoring-101-a-beginners-guide-to-understanding-ntop-tools/ for details):

- ntopng enterprise version to enable nIndex flow dump (https://www.ntop.org/guides/ntopng/historical_flows.html)
- n2disk if you want to record raw packet data (https://www.ntop.org/guides/ntopng/traffic_recording.html)
- (just for reference) for timeseries storage please check out https://www.ntop.org/guides/ntopng/basic_concepts/timeseries.html

If you have more questions about licenses please contact us privately via http://www.ntop.org/support/need-help-2/contact-us .
