### ISSUE TITLE
Invalid flow export format

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2787]
<img width="220" alt="Screenshot 2019-08-28 at 12 16 33" src="https://user-images.githubusercontent.com/4493366/63847252-b83ba880-c98d-11e9-9975-5824d2f41c5e.png">

NTOPNG_INSTANCE_NAME|PACKETS|INTERFACE_ID|IPV6_SRC_ADDR|JSON|IPV6_DST_ADDR|IP_DST_PORT|PROFILE|L7_PROTO|FIRST_SEEN|SRC_TO_DST_BYTES|IPV4_SRC_ADDR|INFO|FLOW_TIME|VLAN_ID|IPV4_DST_ADDR|PROTOCOL|IP_PROTOCOL_VERSION|BYTES|DST_TO_SRC_BYTES|LAST_SEEN|STATUS|IP_SRC_PORT
pc-luca|1|1|::|{ "8": "3.4.122.11", "12": "1.2.193.11", "7": 45766, "11|::|13065||0|1566981801|60|3.4.122.11||1566981822|0|1.2.193.11|6|4|60|0|1566981801|13|45766
pc-luca|1|1|::|{ "8": "3.4.122.11", "12": "1.2.193.11", "7": 45766, "11|::|438||0|1566981806|60|3.4.122.11||1566981822|0|1.2.193.11|6|4|60|0|1566981806|13|45766
pc-luca|1|1|::|{ "8": "3.4.122.11", "12": "1.2.193.11", "7": 45766, "11|::|3311||0|1566981827|60|3.4.122.11||1566981830|0|1.2.193.11|6|4|60|0|1566981827|13|45766
pc-luca|1|1|::|{ "8": "3.4.122.11", "12": "1.2.193.11", "7": 45766, "11|::|17474||0|1566981865|60|3.4.122.11||1566981892|0|1.2.193.11|6|4|60|0|1566981865|13|45766
pc-luca|1|1|::|{ "8": "3.4.122.11", "12": "1.2.193.11", "7": 45766, "11|::|607||0|1566981865|60|3.4.122.11||1566981892|0|1.2.193.11|6|4|60|0|1566981865|13|45766
pc-luca|5|1|::|{ "8": "1.2.193.11", "12": "3.4.122.11", "7": 0, "11": 0|::|0||81|1566981801|410|1.2.193.11||1566981916|0|3.4.122.11|1|4|410|0|1566981865|13|0

**Comment by emanuele-f** [comment]
Is the JSON column the only issue? Code uses a buffer of 64 B to dump column values. Maybe it's better to just skip the JSON column while exporting to txt

**Comment by emanuele-f** [comment]
JSON column has been removed
