### ISSUE TITLE
FR: add alert when a remote destination host appears

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#2792]
hi,
Is it possible to get alerts from "remote destinations" ?
In my case, remote should be only rfc1918 + 2 other networks (what I entered in --local-networks" .... sometimes I can see other IP and each time I need to find the source (what router detects it) and fix it.
Today, first I have to check in live if I see this kind of entry then click on it, etc... to find "info". So that would be great to have possibility to catch these informations.

+ multicast, broadcast, noip should not be integrated in these alerts

thanks

**Comment by emanuele-f** [comment]
Hi, please clarify as the information above is really confusing. With "remote destinations" you mean the remote hosts (in ntopng terminology) or what else? Please rephrase the problem to address

**Comment by Niko78** [comment]
sorry, I meant all IP appearing in the main interface in the "top remote destinations" table

**Comment by emanuele-f** [comment]
Ok so what is the problem to address? What is missing in ntopng?

**Comment by Niko78** [comment]
well I need to check this table when an IP appears (outside rfc1918), then click on it, etc... and most often flow is finished, so I lost information.. that's why I would like to get a kind of alerts table with all these info

**Comment by emanuele-f** [comment]
Do you want to get an alert when a new remote destination host appears? Neither the title nor the description of this issue is clear

**Comment by Niko78** [comment]
yes that's it... when remote host is not in : --local-networks + multicast, broadcast, noip

**Comment by emanuele-f** [comment]
Ok so this request is very specific of your environment so I would not integrate it into ntopng. However you can implement such checks by writing a quite simple alert script and placing it under /usr/share/ntopng/scripts/callbacks/interface/alerts/host. You can take https://github.com/ntop/ntopng/blob/dev/scripts/callbacks/interface/alerts/host/request_reply_ratio.lua as an example but remove the `local_only` flag, then check for remote hosts there and possibly call `alerts_api.trigger` to generate an alert. This feature is quite new and documentation is still missing, I suggest you to experiment with it.

**Comment by Niko78** [comment]
ok thanks for your help and sorry if it was not clear
