### ISSUE TITLE
Email alert endpoint configuration doesn't support authentication

### ISSUE THREAD

**Issue by chrisrobinson** [ntop/ntopng#2794]
Why is it not possible to specify a username, password, and TCP port? Email alerts as exist today seem to require an SMTP open relay, and who actually has one of those?

I'm using version "ntopng Community Edition v.3.6.190215" in PfSense 2.4.4.

**Comment by simonemainardi** [comment]
duplicate of https://github.com/ntop/ntopng/issues/2044
