### ISSUE TITLE
Script Failure Errors LuaEngine

### ISSUE THREAD

**Issue by sgajemison** [ntop/ntopng#2795]
Every 3 seconds I am getting the below error logged. Any insight into what could be the cause?

30/Aug/2019 13:01:07 [LuaEngine.cpp:9824] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][...are/ntopng/scripts/lua/modules/alert_endpoints_utils.lua:131: attempt to compare number with string]
30/Aug/2019 13:01:04 [LuaEngine.cpp:9824] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][...are/ntopng/scripts/lua/modules/alert_endpoints_utils.lua:131: attempt to compare number with string]
30/Aug/2019 13:01:01 [LuaEngine.cpp:9824] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][...are/ntopng/scripts/lua/modules/alert_endpoints_utils.lua:131: attempt to compare number with string]
30/Aug/2019 13:00:58 [LuaEngine.cpp:9824] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][...are/ntopng/scripts/lua/modules/alert_endpoints_utils.lua:131: attempt to compare number with string]
30/Aug/2019 13:00:55 [LuaEngine.cpp:9824] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][...are/ntopng/scripts/lua/modules/alert_endpoints_utils.lua:131: attempt to compare number with string]
30/Aug/2019 13:00:52 [LuaEngine.cpp:9824] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][...are/ntopng/scripts/lua/modules/alert_endpoints_utils.lua:131: attempt to compare number with string]

**Comment by fsamareanu** [comment]
Here's another one:
```

Sep  1 21:57:01 gemma ntopng[20591]: 01/Sep/2019 21:57:01 [LuaEngine.cpp:9921] WARNING: Script failure [/usr/share/ntopng/pro/scripts/callbacks/interface/alerts/flow.lua][...e/ntopng/pro/scripts/callbacks/interface/alerts/flow.lua:1: unexpected symbol near '<\135>']
Sep  1 21:57:01 gemma ntopng[20591]: 01/Sep/2019 21:57:01 [LuaEngine.cpp:9921] WARNING: Script failure [/usr/share/ntopng/pro/scripts/callbacks/interface/alerts/flow.lua][...e/ntopng/pro/scripts/callbacks/interface/alerts/flow.lua:1: unexpected symbol near '<\135>']
Sep  1 21:57:01 gemma ntopng[20591]: 01/Sep/2019 21:57:01 [LuaEngine.cpp:9921] WARNING: Script failure [/usr/share/ntopng/pro/scripts/callbacks/interface/alerts/flow.lua][...e/ntopng/pro/scripts/callbacks/interface/alerts/flow.lua:1: unexpected symbol near '<\135>']
Sep  1 21:57:01 gemma ntopng[20591]: 01/Sep/2019 21:57:01 [LuaEngine.cpp:9921] WARNING: Script failure [/usr/share/ntopng/pro/scripts/callbacks/interface/alerts/flow.lua][...e/ntopng/pro/scripts/callbacks/interface/alerts/flow.lua:1: unexpected symbol near '<\135>']
Sep  1 21:57:01 gemma ntopng[20591]: 01/Sep/2019 21:57:01 [LuaEngine.cpp:9921] WARNING: Script failure [/usr/share/ntopng/pro/scripts/callbacks/interface/alerts/flow.lua][...e/ntopng/pro/scripts/callbacks/interface/alerts/flow.lua:1: unexpected symbol near '<\135>']
Sep  1 21:57:01 gemma ntopng[20591]: 01/Sep/2019 21:57:01 [LuaEngine.cpp:9921] WARNING: Script failure [/usr/share/ntopng/pro/scripts/callbacks/interface/alerts/flow.lua][...e/ntopng/pro/scripts/callbacks/interface/alerts/flow.lua:1: unexpected symbol near '<\135>']

```

**Comment by emanuele-f** [comment]
For the flow.lua issue we are fixing it. @sgajemison please report the output of `ntopng --version`

**Comment by simonemainardi** [comment]
https://github.com/ntop/ntopng/commit/91163ed4e24229821c5495b36e17b8f8301ac32b fixes @fsamareanu issue.

@sgajemison please report the ntopng version used and the configuration - it seems you're using an external alert endpoint, correct?

**Comment by sgajemison** [comment]
v.3.9.190829    [Enterprise/Professional build]
GIT rev:        dev:13d032d18558a81d04fe6b8e6129f81a9c9798e3:20190829
Pro rev:        r2418
Built on:       Ubuntu 18.04.2 LTS
System Id:      6DD584CE9105A1EF
Platform:       x86_64
Edition:        Enterprise
License Type:   Permanent

**Comment by sgajemison** [comment]
Yes, I have alerts going to a syslog server.

**Comment by cardigliano** [comment]
@sgajemison this has been fixed, please check the next build (in 1h). Thank you.

**Comment by sgajemison** [comment]
I have updated to the latest version and am now getting the following every 3 seconds:

04/Sep/2019 08:19:30 [LuaEngine.cpp:10053] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alert_consts.lua:706: attempt to call a nil value (global 'snmp_duplexstatus')]
04/Sep/2019 08:19:27 [LuaEngine.cpp:10053] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alert_consts.lua:706: attempt to call a nil value (global 'snmp_duplexstatus')]
04/Sep/2019 08:19:24 [LuaEngine.cpp:10053] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alert_consts.lua:706: attempt to call a nil value (global 'snmp_duplexstatus')]

ntopng --version:

v.3.9.190904    [Enterprise/Professional build]
GIT rev:        dev:40bf86a81d3e19bbcc860934bde9f034f2101dd3:20190904
Pro rev:        r2429
Built on:       Ubuntu 18.04.2 LTS
System Id:      6DD584CE9105A1EF
Platform:       x86_64
Edition:        Enterprise
License Type:   Permanent

**Comment by emanuele-f** [comment]
This is fixed in d630cce58adf50ffcb7fae7f2b70b83501f93ad5. Please wait an hour until the new package is available and report if it works fine for you

**Comment by sgajemison** [comment]
New package was found by sudo apt update and upgrade was initiated. 

Ntopng --version

v.3.9.190904    [Enterprise/Professional build]
GIT rev:        dev:d89ad540f8ffa274d77f1c364b3d2dc787e3584d:20190904
Pro rev:        r2429
Built on:       Ubuntu 18.04.2 LTS
System Id:      6DD584CE9105A1EF
Platform:       x86_64
Edition:        Enterprise
License Type:   Permanent

After upgrade the syslog entries look clean. Will continue to monitor. Thank you very much for the prompt responses and patches.

**Comment by emanuele-f** [comment]
I think you are still using an old package, please recheck in an hour to be sure.

**Comment by sgajemison** [comment]
I was wondering, but figured since the GIT Rev was different it was a newer version. Will check later.

**Comment by sgajemison** [comment]
Ntopng --version


v.3.9.190904    [Enterprise/Professional build]
GIT rev:        dev:d630cce58adf50ffcb7fae7f2b70b83501f93ad5:20190904
Pro rev:        r2429
Built on:       Ubuntu 18.04.2 LTS
System Id:      6DD584CE9105A1EF
Platform:       x86_64
Edition:        Enterprise
License Type:   Permanent

Syslog output looks good.

**Comment by simonemainardi** [comment]
thanks for reporting
