### ISSUE TITLE
Adding time range or id to the rest API

### ISSUE THREAD

**Issue by dwairlk** [ntop/ntopng#2798]
I suggest adding time range or some identification to differentiate among the alerts.
Currently, every time the API is queried, it brings all the alerts, old ones and new ones.

That would help with easily parsing them and integrate them to a custom applications.

**Comment by simonemainardi** [comment]
implemented in API version 1. See the documentation at https://www.ntop.org/guides/ntopng/api/rest/api_v1.html#Alerts
