### ISSUE TITLE
Reverse DNS lookups for all remote IP addresses give the name of the local NAT router

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#2799]
@lucaderi

Context:
```
- Ubuntu 19.10
- ntopng 3.9.190831 - Community Edition
- ndpi 2.9.0-1757-1bf23dc
- -n=1 in /etc/ntopng
- a very low number of new remote hosts / second
- local NAT router between the host & the Internet
```
The **remote** hosts' IP addresses are all incorrectly resolved into the name of the **local NAT router name**, instead of their real DNS name in all ```hosts``` pages.
For instance:
![Ntopng incorrect DNS reverse lookups](https://user-images.githubusercontent.com/13176858/64162743-3097e300-ce40-11e9-9382-a635f4cc3d94.png)

The IP addresses of all local hosts are correctly resolved.

**Comment by jean-christophe-manciot** [comment]
Nothing special under ```Additional Host Names```either.

**Comment by jean-christophe-manciot** [comment]
On other places, the DNS reverse resolution is done correctly, for instance in the timerseries pages.

**Comment by cardigliano** [comment]
> On other places, the DNS reverse resolution is done correctly, for instance in the timerseries pages.

@jean-christophe-manciot  what is the "timeseries page" you mentioned? Since we are not able to reproduce it, we need any useful info to figure out what's going on. Thank you.

**Comment by cardigliano** [comment]
@jean-christophe-manciot I pushed a patch that should fix it, please update and let us know if it works for you. Thank you.

**Comment by jean-christophe-manciot** [comment]
@cardigliano 
Ubuntu 19.10
ndpi: 1.8-1334-g241cfb3
ntopng: 3.0-4295-g141622f1

Bravo! You nailed it; for instance:
![Reverse DNS lookups solved with NAT router](https://user-images.githubusercontent.com/13176858/64337834-79869d80-cfe0-11e9-840a-5d27f59539d4.png)
