### ISSUE TITLE
Implement flow explorer capabilities

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2802]
In the example below there are over 3k flows alerted. ntopng using tables is unable to allow people to drill down and understand for instance what are the top hosts involved with the selected flows

<img width="1229" alt="Screenshot 2019-09-03 at 18 05 05" src="https://user-images.githubusercontent.com/4493366/64189848-686d4d80-ce75-11e9-92d4-0eadb2fce376.png">

**Comment by simonemainardi** [comment]
This has now been merged within the host score. Misbehaving hosts can be filtered by issue and then by score, to highlight the top sources of trouble.
