### ISSUE TITLE
Flow alert count is inconsistent

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2803]
<img width="875" alt="Screenshot 2019-09-03 at 17 56 04" src="https://user-images.githubusercontent.com/4493366/64189948-9bafdc80-ce75-11e9-9409-19856fd33c44.png">

In the above screenshot this host has 17 alerted active flows. However going under the host flows tab there are many more than them.

It is requested to keep them in sync and to explode the number of flow alerts per category to ease drill down

**Comment by emanuele-f** [comment]
Additional information: the "Flow Alert" count shows the number of generated flow alerts for the host, whereas the "Misbehaving Flows" count shows the number of flows with non-normal status. Both counters are correct, however we lack a way to easily visualize the problems on the host flows.

**Comment by emanuele-f** [comment]
Already addressed in #2821
