### ISSUE TITLE
How can I move my licences from one server to another?

### ISSUE THREAD

**Issue by walker333** [ntop/ntopng#2806]
Hello,

My initial installation was into a vm running on my desktop pc. Now that everything is configured, I moved the vm to an esxi server and changed the IP of the vm.
It seems that this broke the licence of the ntop (I believe that it did the same with nprobe etc.).
Is there a way to revoke the old licences and issue new ones or change the existing ones?

Best regards,
Dimitris

**Comment by emanuele-f** [comment]
Please check out https://www.ntop.org/support/faq/how-can-i-move-a-license-to-a-new-server

**Comment by walker333** [comment]
Hello,

thank you very much. 

Best regards,

Dimitris
