### ISSUE TITLE
/var/lib/ntopng is using 59.5 GiB of space, is there a way to clean out / up this?

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#2808]
On my Ubuntu 18.04 installation /var/lib/ntopng is using 59.5GiB of space
![image](https://user-images.githubusercontent.com/48565067/64265943-c0519600-cf01-11e9-8fbd-ce382c471ad7.png)

Is there anyway to clean up / out / and or eliminate any of this without to much determent to NTOPNG?

It is literally causing ntopng to crash

**Comment by StewAlexander-com** [comment]
`/usr/local/ntopng/3/' is also using 16 GiB of space

![image](https://user-images.githubusercontent.com/48565067/64266347-76b57b00-cf02-11e9-99ba-40f522fa2ad1.png)

**Comment by StewAlexander-com** [comment]
ntopng.log is 12.8 GiB

deleting this

**Comment by emanuele-f** [comment]
Here are the possibilities:
- Use manage data https://www.ntop.org/guides/ntopng/web_gui/settings.html?highlight=delete%20data
- Tune the timeseries settings to reduce the retention time
- Move the ntopng storage directory into a separate (bigger) disk
- Reduce the number of local hosts
- Move from RRD to a remote InfluxDB server with its own storage

**Comment by StewAlexander-com** [comment]
Ok, after I export the managed data I can delete it??  If so, how?

We don't have a disk, instead the stoarge is a partition on one.

**Comment by emanuele-f** [comment]
Inside manage data there is the Delete tab

**Comment by StewAlexander-com** [comment]
Great, saw that, thanks for the support
