### ISSUE TITLE
"Top Application Traffic Last Day View" -> empty

### ISSUE THREAD

**Issue by walker333** [ntop/ntopng#2810]
Hello,
 "Top Application Traffic Last Day View" stays empty.
My version is
v.3.8.190904	[Enterprise/Professional build]
GIT rev:	3.8-stable:758a28de36dc6c33a5b974d7f33999c9bf8b9c33:20190904
Pro rev:	r2189
Built on:	
System Id:	68B8303076056B01
Platform:	x86_64
Edition:	Enterprise
License Type:	Permanent
and the Timeseries settings are:
![Screen Shot 2019-09-05 at 14 46 14](https://user-images.githubusercontent.com/7109506/64340094-04ba6000-cfee-11e9-814e-fa40769c0352.jpg)
A few days ago it was working but in the meantime I made a few updates and some settings changes (which I think are not relevant).
Best regards,
Dimitris

**Comment by emanuele-f** [comment]
Can you upgrade to the development version of ntopng to see if the error is fixed? We are working towards the next stable release and we've done relevant changes to the dashboard handler

**Comment by walker333** [comment]
Hello Emanuele,
do I have to use another repo? Can I install the development version over the stable and without changing the licence?
Can you send me the required steps? 
I forgot to mention that I am using Centos 7

**Comment by emanuele-f** [comment]
You can upgrade it as long as the license maintenance is not expired. For the upgrade, please remove the stable ntop (e.g. `sudo apt-get remove apt-ntop-stable`) repository and then follows the instruction in http://packages.ntop.org/apt to install the dev repository. After setting up the repo, will will be able to upgrade the ntopng package (e.g. with `sudo apt-get install ntopng`)

**Comment by walker333** [comment]
Unfortunately I'm using Centos.
Nevermind it is not a critical issue for me. I'll wait for the stable version.

**Comment by simonemainardi** [comment]
@walker333 so I'm closing this for now. If you could try the dev and let us know that would be great, feel free to reopen if necessary. To move to the dev build on Centos you just have to follow instructions at http://packages.ntop.org/centos/. Otherwise you can wait for the stable which should arrive by the end of October.

**Comment by walker333** [comment]
Hello,
I just tried the last nightly build, using a vm image of my ntop, and I found that the bug I mentioned, is fixed.
