### ISSUE TITLE
PR_RING zc driver license does not seem to work

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#2813]
Good afternoon, 
 
I was having some issue with ntopng and got it sorted out, but I noticed that my ZC license key isn’t working anymore.  Here is the error:
 
Error! Wrong parameter: The format of "ZC License" field for "64006A8FC7C5" identifier is not valid!
 
Here is the key I am using:
 
Please use 6BA7FE16E5D832815D853A486710D63D1580825031ECABA63A as license for
PF_RING (zc10g) running on system 64:00:6A:8F:C7:C5
0 licenses left for this orderId. Maintenance for this license will expire on Tue, 04 Feb 2020 15:03:51 +0100
Please create a license file as follows (do it as root user):
 
mkdir /etc/pf_ring/
echo "6BA7FE16E5D832815D853A486710D63D1580825031ECABA63A" > /etc/pf_ring/64006A8FC7C5
 
Thanks,

**Comment by lucaderi** [comment]
Your license has been revoked. Please generate a new one.

**Comment by ghost** [comment]
Good morning.  I have processed the new key and added it to the install.  I kicked ntopng and restarted the device and it still shows "No valid license found".  
![1](https://user-images.githubusercontent.com/46750138/64542125-fa031200-d2f0-11e9-995b-0fd49a19082e.png)

![2](https://user-images.githubusercontent.com/46750138/64541969-ba3c2a80-d2f0-11e9-8245-c63325018369.png)

**Comment by cardigliano** [comment]
Please provide the output of pfcount -L -v 1

**Comment by ghost** [comment]
![3](https://user-images.githubusercontent.com/46750138/64542448-91686500-d2f1-11e9-903c-3299b44bbe94.png)

**Comment by cardigliano** [comment]
@dbailey-indofmd-org please update the software and provide me the output of "zcount -i zc:eno1" (I added more information about the license failure). Thank you.

**Comment by ghost** [comment]
Ok.  I have updated:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.

Output:
zcount -i zc:eno1
pfring_zc_create_cluster error [Socket operation on non-socket] Please check that pf_ring.ko is loaded and hugetlb fs is mounted

**Comment by cardigliano** [comment]
Did you run it as root? 
Could you check that hugepages are up? (the initialization script should take care of that as explained at https://www.ntop.org/guides/pf_ring/get_started/packages_installation.html, otherwise please check https://www.ntop.org/guides/pf_ring/hugepages.html)

**Comment by dbailey-indofmd-org** [comment]
#########################################################################
# ERROR: You do not seem to have a valid PF_RING ZC 7.4.0.190828
# license for eno1 (MAC 64:**:**:**:C7:C5) [Intel 1 Gbit e1000e family]
# ERROR: License mismatch error
# ERROR: Please get one at http://shop.ntop.org/
#########################################################################
# We're now working in demo mode with packet capture and          
# transmission limited to 5 minutes
#########################################################################

**Comment by dbailey-indofmd-org** [comment]
#########################################################################
# ERROR: You do not seem to have a valid PF_RING ZC 7.4.0.190828
# license for eno1 (MAC 64:00:6A:8F:C7:C5) [Intel 1 Gbit e1000e family]
# ERROR: License mismatch error
# ERROR: Please get one at http://shop.ntop.org/
#########################################################################
# We're now working in demo mode with packet capture and          
# transmission limited to 5 minutes
#########################################################################
pfring_zc_create_cluster error [No buffer space available] Please check that pf_ring.ko is loaded and hugetlb fs is mounted

**Comment by ghost** [comment]
Ok, I think I have made some headway and ZC is running, but the licensing is still giving an error:

![1](https://user-images.githubusercontent.com/46750138/64631789-d1991780-d3c5-11e9-95d0-34c51e48eb23.png)

**Comment by ghost** [comment]
Rebooted and all seems to be working now but the licensing.  Applied licensing as root and through nBox.  

![2](https://user-images.githubusercontent.com/46750138/64634942-74549480-d3cc-11e9-8bae-c2f6380bb73d.png)

**Comment by ghost** [comment]
I cannot find the email, but at some point we switched from a VM to a physical appliance and had the licenses revoked and reissued for the new System ID.  Is it possible that the Order ID I am using is still tied to the old System ID somehow?

**Comment by cardigliano** [comment]
@dbailey-indofmd-org could you send me your orderid and email in a direct message to check the license please? Please use cardigliano at ntop.org. Thank you.

**Comment by cardigliano** [comment]
@dbailey-indofmd-org I think I found the reason, you are using a 10G license for a 1G adapter. Just to make sure, please provide ethtool -i eno1

**Comment by dbailey-indofmd-org** [comment]
Yes, it is 1G.  That was the license I was issued to begin with so I thought it was all the same.  Derp.

driver: e1000e
version: 3.4.0.2
firmware-version: 0.13-4
expansion-rom-version:
bus-info: 0000:00:19.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no

Thanks,

Derek Bailey
Network Administrator
Institute of Notre Dame, Baltimore, MD
Jaguar Technology, LLC
410.570.4856
derek.bailey@jaguartech.com<mailto:derek.bailey@jaguartech.com>

**Comment by ghost** [comment]
I emailed the results of that command to you.

**Comment by cardigliano** [comment]
Yes, you are using a 1G adapter (e1000e family) with a 10G license..

**Comment by ghost** [comment]
Got it.  Can you revoke my license and allow me to generate a new key?

**Comment by cardigliano** [comment]
What pf_ring version are you running? Please provide "zcount -h | grep PFRING_ZC"

**Comment by ghost** [comment]
Using PFRING_ZC v.7.4.0.190828

**Comment by cardigliano** [comment]
@dbailey-indofmd-org a package update that tries to handle this case should be already available, please update and let us know if the license now works for you. Thank you.

**Comment by ghost** [comment]
Looks good now.  Is there an easy way to verify that the ZC drivers are working properly?  Do I need to add a line to my ntopng.conf file to start them?

zc:eno1 (XX:CC:XX:CC:XX:CC) | Permanent License | Maintenance will expire in 141 days
-- | -- | --

**Comment by cardigliano** [comment]
You can check it running 
pfcount -i zc:eno1
(stop any application running on eno1 before)

**Comment by ghost** [comment]
Thanks for all your help.  Confirmed ZC driver is running.  I think this will really help performance.  

Really appreciate your patience.
