### ISSUE TITLE
Geolocation error 

### ISSUE THREAD

**Issue by radyphan** [ntop/ntopng#2814]
Hi ,

I have an issue regarding Geolocation doesn't shown the righ place, it always using the default location (Italy) please check the capture in attach file.

I already edit timezone in my server please check bellow:
root@alien:/usr/share/zoneinfo# cd ~
:~# timedatectl
                      Local time: Fri 2019-09-06 11:48:42 PDT
![9-6-2019 11-57-08 AM](https://user-images.githubusercontent.com/47866186/64453747-22470280-d09e-11e9-907e-d3a9eb83f6dc.png)

                  Universal time: Fri 2019-09-06 18:48:42 UTC
                        RTC time: Fri 2019-09-06 18:48:41
                       Time zone: America/Los_Angeles (PDT, -0700)
       System clock synchronized: yes
systemd-timesyncd.service active: yes
                 RTC in local TZ: no
:~# 

Please let me know do we need to verify config file in ntopng?

Best regards,
Rady

**Comment by emanuele-f** [comment]
Hi, have you set up the maps api key?

**Comment by radyphan** [comment]
Hi,
Actually, I tried to put my API key few weeks ago but it still shown my location is in Italy.
Any solution?

Thank you,
Rady

**Comment by simonemainardi** [comment]
Reported behaviour is OK.  You are looking for a private IP address (see https://en.wikipedia.org/wiki/Private_network#Private_IPv4_addresses). IP addresses cannot be geolocated using a database. I am going to hide the page for such private addresses.

**Comment by radyphan** [comment]
Hi,
Actually, I use IP local for this purpose, as i was forwarding my IP to
outside for security purpose.

Please advice if geolocated cannot be done on ip forward.

Thank you,
Rady

**Comment by simonemainardi** [comment]
Geolocation works for non-private IP addresses. It's pointless to geolocate IPs in private ranges.
