### ISSUE TITLE
Unbundle Interface Traffic

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2816]
In ntopng network interfaces contain various types of traffic. This means that analysing the traffic as a whole instead of splitting it into smaller subsets is not a great idea. For instance in every large company there are various traffic flows that should be analysed unbundled. This is because not all traffic is alike, and when traffic is merged many things are hard to see. Typical examples of network traffic to be analysed unbundled include
- networks containing core company servers
- networks of external people who periodically visit the company, or guest LAN
- client network traffic
- traffic that does not fall into the above categories

So instead of monitoring the interface where network traffic flows as a whole, the traffic must be split into several logical interfaces, where a single packet/flow can belong to multiple interfaces.

It is requested to plan an architecture to address this request, preserving efficiency and duplication.

**Comment by cardigliano** [comment]
~~We need to extend the Dynamic Network Interface to support a "custom" distribution based on a set of <in/out ifid, vlan, subnet> (this should be configurable through the GUI similar to the Host Pools).~~
Custom distribution has been redesigned and implemented with Extended nBPF filters, supporting standard fields from packets headers and information elements from flows.

**Comment by cardigliano** [comment]
Open items:
- ~~Dynamic interfaces are added to an hash table, this is also used for flow purging and other stuff, it is convenient to add dynamic interfaces and custom sub-interfaces to the same data structure~~
- ~~Filter validation happens on submit now, better to validate it live while typing~~
- ~~Make sure that the user notice that a ntopng reboot is requires after configuring sub-interfaces (better to add a reboot button)~~
- ~~Add an icon for sub-interfaces in the "Interfaces" menu~~
- Doc update
