### ISSUE TITLE
Read flow information from Syslog

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2819]
Many security systems and network devices report security information in syslog. In #1928 this integration has been designed for suricata but there are many other cases where we could implement in ntopng the ability to read network or alert information from syslog.
It is requested to study also how other systems such as https://www.elastic.co/products/logstash work to add support of external apps such as bro or devices such was Fortigate.

**Comment by cardigliano** [comment]
Superseded by https://github.com/ntop/ntopng/issues/2932
