### ISSUE TITLE
Invalid SNMP information in flow collection

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2820]
When starting ntopng in collector mode (example see below
- nprobe --zmq tcp://127.0.0.1:1234 -T "@NTOPNG@"
- ntopng -i tcp://127.0.0.1:1234
)
a new web menu appears named exporters.

Such menu is mostly empty when SNMP is not properly configured

![Screen Shot 2019-09-08 at 11 02 32](https://user-images.githubusercontent.com/4493366/64486026-2ef76200-d228-11e9-803c-64f739815d60.png)
![Screen Shot 2019-09-08 at 11 02 26](https://user-images.githubusercontent.com/4493366/64486027-2ef76200-d228-11e9-8d8d-0951fbc6f5c5.png)

it lacks of the interface description (under flow device). and it contains invalid info (for instance interface name set to "0").

**Comment by simonemainardi** [comment]
Now when the device SNMP is available, regular information is shown

![image](https://user-images.githubusercontent.com/3397663/73870284-1a0d1200-484c-11ea-8dc4-21ad0db1838f.png)


However, when no SNMP device is found, a message is printed and a note points the user to the SNMP devices configuration page

![image](https://user-images.githubusercontent.com/3397663/73870330-314bff80-484c-11ea-827a-077760f5f1cd.png)
