### ISSUE TITLE
Add ntopng instance name

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#283]
Every ntopng instance must have a name. By default, if not specified, it can use the host IP (numeric or symbolic). Users can set the instance name using a new command line flag or by means of the web view. This name will be added also to the MySQL database, ES dump, so it is clear the origin of the flows.

**Comment by simonemainardi** [comment]
ntopng instance name can now be specified via an extra command line argument `--instance-name` (`-N`).

If no argument is specified, instance name defaults to the current host name (posix standard `gethostname()` is used).

An extra column `NTOPNG_INSTANCE_NAME` is created in the MySQL tables to store instance name. In ElasticSearch a new field is added with the same label.
