### ISSUE TITLE
Add ZMQ Interface Drops Reset

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2832]
<img width="469" alt="Screenshot 2019-09-09 at 15 56 58" src="https://user-images.githubusercontent.com/4493366/64537101-7b22cf00-d31a-11e9-81da-2168e60c82f8.png">
Implement ZMQ drops reset as with packet interfaces. More in general please make sure that all interface types have drops reset.

**Comment by simonemainardi** [comment]
Implemented in:

https://github.com/ntop/ntopng/commit/77c1f85cd3a1047522cefee66724ee303e05ebd6
https://github.com/ntop/ntopng/commit/093a27cd7125e3db57da84e0b19a2a6a37bb8030
https://github.com/ntop/ntopng/commit/9c06fcfe93415b548e43c5fec1357fb68b12cb26

Now it is also possible to reset counters for ZMQ as well as for dynamic interfaces created using disaggregation criteria
