### ISSUE TITLE
Flow Collection Custom Information Elements Handling

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2833]
In ntopng when flows are received with custom elements they are serialised on a json structure that performance wise is inefficient. It is requested to rethink the implementation (now nProbe sends ntopng in TLV format) so that the JSON is replaced with TLV or a similar more efficient data structure

**Comment by cardigliano** [comment]
Custom elements are now encoded in TLV for flows received in TLV format (and converted to JSON when exported to Lua)
