### ISSUE TITLE
Add interface name

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#284]
Same as https://github.com/ntop/ntopng/issues/283, the DB must have a new column that contain the interface name (e.g. eth4) from which the flow has been monitored. This will need to reconsider the existing MySQL naming convention and make it consistent across MySQL and ES.

**Comment by simonemainardi** [comment]
Existing MySQL naming convention makes two separate tables for each interface monitored. Table names are `flows4_<ifid>` and `flows6_<ifid>`. Ifid is a unique integer identifier chosen by ntopng.

My idea is to simplify this structure and make just two tables, namely `flows4` and `flows6`, and add an extra column to store the interface name. I do not think that storing the integer interface id is good: it is just a number that only make sense inside ntopng. Using interface names would yield more (re)usable data.

Of course I would like to design a code that transparently migrates old tables into the new ones. Old flows should be dumped into the new tables, and old tables should be dropped. This should occur in a way that the user doesn't even notice the migration.

**Comment by simonemainardi** [comment]
Commits 0c92e286 and 2045df7053 implement the features as discussed above.
