### ISSUE TITLE
Implement flow alerting script

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2842]
Currently host alerts are driven by scripts that are executed periodically on hosts. For flows, the flow state evaluation that turns them into alerts is mostly hardcoded in ntopng and mixed in C++ and Lua code. This means that
- ntopng arbitrarily decides what flows with issues becomes alerted flows
- it is not possible to specify rules that can modify the flow state into alerted

In essence it is requested to unify the logic of hosts and flows alerting so that everything is unified on a single and consistent implementation.

**Comment by emanuele-f** [comment]
The new `flow` api should also be documented in https://github.com/ntop/ntopng/blob/dev/doc/src/api/lua_c/flow/flow.lua (e.g. `flow.getProtocols()`, `flow.getClient2ServerIAT()`)

**Comment by emanuele-f** [comment]
Implemented in #2947
