### ISSUE TITLE
Implement HTTP RTT Monitoring

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2847]
In the System -> RTT Monitor page it is requested to implement HTTP monitoring. Method Utils::httpGetXXX shall be enhanced to return via https://curl.haxx.se/libcurl/c/curl_easy_getinfo.html statistics like

- CURLINFO_NAMELOOKUP_TIME
- CURLINFO_APPCONNECT_TIME
- CURLINFO_TOTAL_TIME
...

To help finding out where is the performance hog. All various times must be serialised in timeseries but only the CURLINFO_TOTAL_TIME is used to trigger the alert.

**Comment by emanuele-f** [comment]
Implemented in 0be214cfae35cd25789b8aa9e8e720cf76372275.

![2020-03-13_19-04](https://user-images.githubusercontent.com/5488003/76647781-5c192a00-6555-11ea-85cb-0cba70f6f4b2.png)

![2020-03-13_19-06](https://user-images.githubusercontent.com/5488003/76647778-5ae7fd00-6555-11ea-85cf-e9c91af04686.png)
