### ISSUE TITLE
Add LDAP user authentication

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#285]
In ntopng the authentication is done via local users. It would be nice to extend it to LDAP. If LDAP is enabled, local users will not be considered.

**Comment by lucaderi** [comment]
- Privileged users will be identified if they belong to a specific LDAP group.
- ntopng users will be identified if they belong to a specific LDAP group. In other words (if this group is configured) not all valid LDAP users can login but only those who belong to this group.

**Comment by ValentinaViscarelli** [comment]
Added LDAP authentication as described in requirements.
