### ISSUE TITLE
Missing chart icon shortcut to alert timeseries

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2850]
![Screen Shot 2019-09-11 at 12 29 24](https://user-images.githubusercontent.com/4493366/64690058-d0342180-d48f-11e9-971d-734256ddef54.png)

![Screen Shot 2019-09-11 at 12 29 46](https://user-images.githubusercontent.com/4493366/64690102-ea6dff80-d48f-11e9-97e6-94c19ee641c8.png)

**Comment by simonemainardi** [comment]
implemented

![image](https://user-images.githubusercontent.com/3397663/64866947-b1bf5900-d63c-11e9-8950-01e66671fe4b.png)
