### ISSUE TITLE
Missing timeseries of flows with warning

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2851]
Currently there are timeseries for active flows (regardless of their status). Alerted or flows with warning do not have a timeseries.

It is requested to create them and chart all of them on a single chart with all series. NOTE: flows with warnings/alerts cannot be depicted as stacked as the total flows already include those flows with alerts/warning.

![Screen Shot 2019-09-11 at 12 31 17](https://user-images.githubusercontent.com/4493366/64690180-112c3600-d490-11e9-883a-931524d25286.png)

![Screen Shot 2019-09-11 at 12 33 18](https://user-images.githubusercontent.com/4493366/64690331-68320b00-d490-11e9-9152-81e085c170ad.png)

**Comment by emanuele-f** [comment]
Implemented in 8d51dae0e53908acc0a92dd75679245c36201a90
