### ISSUE TITLE
Glue up RTT data with hosts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2852]
In the system interface RTT measurements are not glued with hosts. In the host page it is requested to add a new tab that allows to enable/disable/configure/access RTT measurements for such host on a simple and consistent way.

RTT charts for a given host must be accessed from the host chart in addition to the RTT page.

**Comment by simonemainardi** [comment]
implemented

![image](https://user-images.githubusercontent.com/3397663/65336023-d7f97180-dbc5-11e9-9f08-f386592b9262.png)
