### ISSUE TITLE
Invalid timeseries data reported

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2853]
![Screen Shot 2019-09-12 at 09 20 43](https://user-images.githubusercontent.com/4493366/64762582-b3a2f280-d53e-11e9-9632-f7e9259fdb6a.png)

In the above screenshot the point of 09:20 is not yet in Influx but the chart is depicting it. As a user I would interpret the point as 0, that is not correct. So please make sure that when creating chart, points not yet written on the database are not set to 0, but they are not depicted at all as this is misleading.

**Comment by emanuele-f** [comment]
Issue seems fixed.
