### ISSUE TITLE
Unify the alert/flow script UI 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2855]
In order to have a consistent GUI, the GUI for alert/flow scripts must be consistent with ntopng look and feel. Please change the checkbox to the on/off toggle used in preferences.

![Screen Shot 2019-09-18 at 23 12 10](https://user-images.githubusercontent.com/4493366/65186366-cdc26080-da69-11e9-8060-b94200401e3b.png)
![Screen Shot 2019-09-18 at 23 12 02](https://user-images.githubusercontent.com/4493366/65186368-ce5af700-da69-11e9-9aec-843d9a1cd37c.png)

**Comment by simonemainardi** [comment]
implemented both for alerts and flow scripts

![image](https://user-images.githubusercontent.com/3397663/65311845-95b63d00-db91-11e9-8d51-e52f46909d9e.png)


![image](https://user-images.githubusercontent.com/3397663/65311859-a23a9580-db91-11e9-8a55-eb2712a43eac.png)
