### ISSUE TITLE
Make alert generation asynchronous

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2856]
When an alert is generated, ntopng writes onto SQLite that introduces several performance degradation issues. Instead of writing directly to it, it is necessary to write through a cache (e.g. redis) to speedup scripts and reduce waits due to the database.

**Comment by cardigliano** [comment]
Asynchronous alerts generation has been implemented. It is now required to rework the flow alerts life cycle as described at https://github.com/ntop/ntopng/issues/3038
