### ISSUE TITLE
Invalid alert disable behavior

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2857]
Clicking on disable the alert selected
![disable](https://user-images.githubusercontent.com/4493366/65223965-84eac600-dac2-11e9-9c2c-b847b13a30ac.png)
- does not show this as an icon
- it still keeps the disable button (it should disappear)

**Comment by emanuele-f** [comment]
The issue was probably caused by an expired CSRF token. With beddb433b7202b328aa7f5566a85da2ded679226 such events are notified to the user with a warning.
