### ISSUE TITLE
Missing host alert icon

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2858]
When a host has one or more alerts as in the picture below
![Screenshot from 2019-09-19 09-50-40](https://user-images.githubusercontent.com/4493366/65224198-ff1b4a80-dac2-11e9-891e-1c267374af03.png)
ntopng must add an icon next to the host (same al the country flag, dropbox...) that notifies this state

**Comment by simonemainardi** [comment]
Icon added

![image](https://user-images.githubusercontent.com/3397663/65256721-4673fc00-db00-11e9-93da-12e283e49e06.png)

Note that the icon only appears when there are currently engaged alerts, that is currently ongoing problems. As the column total alerts counts both current and past alerts, we decided not to show the icon when only past alerts are present. This is to remain consistent with the use and semantics of the red triangle, which currently represents an ongoing issue, something that is occurring now. This is in the spirit of the footer where the red triangle is shown for engaged alerts and alerts for active flows.
