### ISSUE TITLE
Inconsistent alert endpoint behaviour

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2859]
![Screenshot from 2019-09-19 09-54-41](https://user-images.githubusercontent.com/4493366/65224488-908abc80-dac3-11e9-9fa5-5a8f47942f36.png)
The above behaviour is inconsistent. In case "Webhook Notification" is ON the subpane with parameters is open, or removed when set to OFF. The same does not happen when clicking on "Alerts to Third-Party Endpoints" that needs to implement the same behaviour of the "Webhook Notification"  pane.

**Comment by emanuele-f** [comment]
The problem here is that we need a two level item hide logic, which is currently unsupported. I'll check if we can remove the "Third-Party Endpoints" preference
