### ISSUE TITLE
Add Radius User Authentication

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#286]
Same as https://github.com/ntop/ntopng/issues/285 for Radius.

**Comment by lucaderi** [comment]
We have decided that LDAP is the best option for this, and thus for the moment we won't add radius support as we now have LDAP implemented.

**Comment by simonemainardi** [comment]
@emanuele-f please review https://github.com/ntop/ntopng/pull/2177

**Comment by lucaderi** [comment]
@emanuele-f 
![screen shot 2018-12-01 at 08 03 24](https://user-images.githubusercontent.com/4493366/49325256-9d8fec80-f53f-11e8-82d8-a58235c4ee6c.png)

Radius authentication is present in preferences even though radius support on my host is disabled.

**Comment by emanuele-f** [comment]
This is fixed in 1df7ebfed8f04e179b445845c9ad6213a742b4eb

**Comment by emanuele-f** [comment]
Closing this, will continue on #1863 .
