### ISSUE TITLE
Add live flow alert exploration

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2862]
In /lua/bubble.lua add a new script that creates a host bubble for the top X hosts (this to avoid filling up the screen) wthere
- X axis: number of alerted flows as client
- Y axis: number of alerted flows as server
- bubble size: total number of alerted flows.

**Comment by MatteoBiscosi** [comment]
Currently implemented into `lua/rest/v1/charts/host/map.lua`
