### ISSUE TITLE
Add alerted flow info on footer

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2863]
Similar to what happens with local/remote hosts, report the number of flows unalerted/alerted

![Screenshot from 2019-09-19 10-17-11](https://user-images.githubusercontent.com/4493366/65226245-d09f6e80-dac6-11e9-954b-8d3ecd82f21a.png)

**Comment by simonemainardi** [comment]
implemented

![image](https://user-images.githubusercontent.com/3397663/65247177-33593000-daf0-11e9-8a20-8ce4b39f43c5.png)
