### ISSUE TITLE
Unify alert representation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2864]
![Screenshot from 2019-09-19 10-19-30](https://user-images.githubusercontent.com/4493366/65226378-080e1b00-dac7-11e9-968b-730c996fba35.png)
In this image there are a few inconsistencies
- some protocol (TCP) are in red and some in black. As we decided to put a yellow icon for flows with issues, the red must be removed and the icon placed next to every flow with issues

**Comment by simonemainardi** [comment]
Done in https://github.com/ntop/ntopng/commit/e720708ea1d844eac218ba32eae5995063e699d0
