### ISSUE TITLE
Create an API for Alert Hooks

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2869]
It would be nice to create a public API for people that are willing to create new alert hooks. For instance for integrating services ntopng does not yet support such as Pagerduty or Telegram

**Comment by emanuele-f** [comment]
Something is already documented in https://github.com/ntop/ntopng/blob/dev/doc/README.alerts but a more precise api is needed

**Comment by simonemainardi** [comment]
this is part of the current rewrite of alert recipients
