### ISSUE TITLE
Custom Alert Scripts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2870]
As of today triggered alerts don't have the ability to choose what hook to call. It would be nice that alert type X or alerts coming from host Y call hook Z, instead of all scripts calling the same hook.
In essence it is requested to create a "named" hook (let's say hook-luca, hook-ntop, hook-home) and set a default hook. Alerts can have (for host alerts you can go in the alert page under the hosts page) a custom hook, the default one, or multiple hooks called.

In essence what we need is to make alert hooks more flexible.

**Comment by simonemainardi** [comment]
refactored in issues:

#3859 
#3858 
#3857 
#3856 
#3855
#3854 
#3853
