### ISSUE TITLE
ntopng[<pid>]: [timeseries.lua:16] [influxdb.lua:674] ERROR: Cannot find ts file /var/lib/ntopng/<instance_name>/21/ts_export/7207_1568957482. Some timeseries data will be lost.

### ISSUE THREAD

**Issue by EpiqSty** [ntop/ntopng#2873]
We are experiencing repetative issues with ntopng export to influxdb. It produce log messages like:

`ntopng[<pid>]: [timeseries.lua:16] [influxdb.lua:674] ERROR: Cannot find ts file /var/lib/ntopng/<instance name>/21/ts_export/7207_1568957482. Some timeseries data will be lost.`

And in the GUI we see messages, what ntopng trying to establish connection to influxdb but fails.

The question is, why it resolves after ntopng instance restart, but ntopng can't resolve the issue automatically by retrying connection to influxdb?

```
$ ntopng --version
v.3.9.190910    [Enterprise/Professional build]
GIT rev:        dev:91222ada6bb92744a67f50b774116b8ae363bc06:20190910
Pro rev:        r2438
Built on:       Debian GNU/Linux 9.1 (stretch)
System Id:      68AAF46F76056B01
Platform:       x86_64
Edition:        Enterprise
License Type:   Permanent
Maintenance:    Until Wed Aug 12 15:15:28 2020 [327 days left]

$ apt-cache policy influxdb
influxdb:
  Installed: 1.7.8-1
  Candidate: 1.7.8-1
  Version table:
 *** 1.7.8-1 500
        500 https://repos.influxdata.com/debian stretch/stable amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by simonemainardi** [comment]
ntopng retries automatically to reconnect to influxdb but if it continuously fails, at some point it starts dropping data to avoid queues to grown indefinitely.

Please, show the errors you see in the gui under tab System->Influxdb

> The question is, why it resolves after ntopng instance restart, but ntopng can't resolve the issue automatically by retrying connection to influxdb?

what do you mean?

**Comment by EpiqSty** [comment]
@simonemainardi , in System -> Influxdb it looks like this:

HealthCurrent InfluxDB export health. | Temporarily unable to exportCurrently unable to export to InfluxDB. Retry in progress.
-- | --
Storage Utilization Total disk space used by InfluxDB. | 13.74 GB
RAM Total memory InfluxDB has obtained from the operating system. | 20.07 GB
Total Exports Total number of successful writes into InfluxDB. | 176,492
Total Points Total number of points successfully written into InfluxDB. | 298,037,905
Dropped Points Total number of points dropped due to InfluxDB write failures. | 0
Series CardinalityAn indication of how challenging is for InfluxDB to handle written points. | 151,721

System status is:

System
--
22.63%
Used: 80.82% / Available: 6.03 GB / Total: 31.42 GB

7165
Used: 948.73 MB
Volume: /var/lib/ntopng/voip_internal (/dev/mapper/debian--9--5--puppet5--lvm--template--vg-root) tcp://*:5554c (8.67 GB) tcp://*:5569c (2.6 GB) tcp://*:5570c (1.45 GB) tcp://*:5562c (5.05 GB) tcp://*:5568c (1.95 GB) tcp://*:5565c (5.6 GB) tcp://*:5567c (16.62 GB) tcp://*:5561c (1.71 GB) System (240.77 GB) Available (422.09 GB)  -  Total: 706.51 GB
23/Sep/2019 08:40:15 [timeseries.lua:16] [influxdb.lua:674] ERROR: Cannot find ts file /var/lib/ntopng/voip_internal/8/ts_export/13871_1569130421. Some timeseries data will be lost.23/Sep/2019 08:40:15 [timeseries.lua:16] [influxdb.lua:674] ERROR: Cannot find ts file /var/lib/ntopng/voip_internal/21/ts_export/13872_1569130421. Some timeseries data will be lost.23/Sep/2019 08:40:15 [timeseries.lua:16] [influxdb.lua:674] ERROR: Cannot find ts file /var/lib/ntopng/voip_internal/15/ts_export/13873_1569130421. Some timeseries data will be lost.23/Sep/2019 08:40:15 [timeseries.lua:16] [influxdb.lua:674] ERROR: Cannot find ts file /var/lib/ntopng/voip_internal/23/ts_export/13872_1569130419. Some timeseries data will be lost.23/Sep/2019 08:40:15 [timeseries.lua:16] [influxdb.lua:674] ERROR: Cannot find ts file /var/lib/ntopng/voip_internal/8/ts_export/3649_1569017899. Some timeseries data will be lost.

And, after ntopng instance restart it shows such status:



HealthCurrent InfluxDB export health. | OKExport to InfluxDB is working OK.
-- | --
Storage Utilization Total disk space used by InfluxDB. | 13.75 GB
RAM Total memory InfluxDB has obtained from the operating system. | 17.22 GB
Total Exports Total number of successful writes into InfluxDB. | 48
Total Points Total number of points successfully written into InfluxDB. | 121,005
Dropped Points Total number of points dropped due to InfluxDB write failures. | 0
Series CardinalityAn indication of how challenging is for InfluxDB to handle written points. | 15



System
--
25.59%
Used: 70.86% / Available: 9.16 GB / Total: 31.42 GB

21015
Used: 659.09 MB
Volume: /var/lib/ntopng/voip_internal (/dev/mapper/debian--9--5--puppet5--lvm--template--vg-root) tcp://*:5554c (8.67 GB) tcp://*:5569c (2.6 GB) tcp://*:5570c (1.45 GB) tcp://*:5562c (5.05 GB) tcp://*:5568c (1.95 GB) tcp://*:5565c (5.61 GB) tcp://*:5561c (1.71 GB) tcp://*:5567c (16.63 GB) System (240.54 GB) Available (422.29 GB)  -  Total: 706.51 GB
23/Sep/2019 08:42:03 [ZMQCollectorInterface.cpp:160] Collecting flows on tcp://*:5565c23/Sep/2019 08:42:03 [ZMQCollectorInterface.cpp:160] Collecting flows on tcp://*:5569c23/Sep/2019 08:42:03 [ZMQCollectorInterface.cpp:160] Collecting flows on tcp://*:5562c23/Sep/2019 08:42:03 [ZMQCollectorInterface.cpp:160] Collecting flows on tcp://*:5568c23/Sep/2019 08:42:03 [ZMQCollectorInterface.cpp:160] Collecting flows on tcp://*:5567c23/Sep/2019 08:42:03 [ZMQCollectorInterface.cpp:160] Collecting flows on tcp://*:5554c23/Sep/2019 08:42:03 [ZMQCollectorInterface.cpp:160] Collecting flows on tcp://*:5561c23/Sep/2019 08:42:03 [ZMQCollectorInterface.cpp:160] Collecting flows on tcp://*:5570c23/Sep/2019 08:42:03 [NetworkInterface.cpp:2778] Started packet polling on interface tcp://*:5567c [id: 23]...23/Sep/2019 08:42:03 [NetworkInterface.cpp:2778] Started packet polling on interface tcp://*:5565c [id: 21]...23/Sep/2019 08:42:03 [NetworkInterface.cpp:2778] Started packet polling on interface tcp://*:5570c [id: 18]...23/Sep/2019 08:42:03 [NetworkInterface.cpp:2778] Started packet polling on interface tcp://*:5569c [id: 17]...23/Sep/2019 08:42:03 [NetworkInterface.cpp:2778] Started packet polling on interface tcp://*:5561c [id: 15]...23/Sep/2019 08:42:03 [NetworkInterface.cpp:2778] Started packet polling on interface tcp://*:5568c [id: 12]...23/Sep/2019 08:42:03 [NetworkInterface.cpp:2778] Started packet polling on interface tcp://*:5562c [id: 11]...23/Sep/2019 08:42:03 [NetworkInterface.cpp:2778] Started packet polling on interface tcp://*:5554c [id: 8]...23/Sep/2019 08:42:03 [PeriodicActivities.cpp:114] Each periodic activity script will use 5 threads23/Sep/2019 08:42:01 [PeriodicActivities.cpp:72] Started periodic activities loop...23/Sep/2019 08:42:00 [NtopPro.cpp:683] [LICENSE] Maintenance: Until Wed Aug 12 15:15:28 2020 [324 days left]23/Sep/2019 08:42:00 [NtopPro.cpp:673] [LICENSE] License Hash: CEC61717E89E66084DD252CDD7F06ED51597238128348B7AF223/Sep/2019 08:42:00 [NtopPro.cpp:669] [LICENSE] otBGfIWHC2f5U+i+IezHKJuTLqrvTAqbXf5GdWaidB+foe72eh9wQ0GJ4v5WHA2Rtg==23/Sep/2019 08:42:00 [NtopPro.cpp:669] [LICENSE] oQWBi8iFwfmRgdIQoes11DlxM5b0ktsVAbISK8yMLoRoMSNm6iqErD+3TSex6bcEpGqwc23/Sep/2019 08:42:00 [NtopPro.cpp:669] [LICENSE] SgsVkDuSFHop3WUDZNvDwhh/egxLNdTFUO4REdFzeGLEfZQk6/dhdXaAKiViME6xE+/X223/Sep/2019 08:42:00 [NtopPro.cpp:669] [LICENSE] md88aRkQOquWETzEz80ZYEwQ7C487Jx4LnGgOCjCuD3Sm8wMT1Mx5roXME2CF1DbGKiXf23/Sep/2019 08:42:00 [NtopPro.cpp:668] [LICENSE] License: dHXAHyFFzjcoU9+Wh/PKdUX4MNEhe2HVy6zozz8+ctyI3LQdcnY5UX1tKhz18zWSiIgdz23/Sep/2019 08:42:00 [NtopPro.cpp:659] [LICENSE] License Type: Permanent License23/Sep/2019 08:42:00 [NtopPro.cpp:658] [LICENSE] Edition: Enterprise23/Sep/2019 08:42:00 [NtopPro.cpp:657] [LICENSE] System Id: 68AAF46F76056B0123/Sep/2019 08:42:00 [Ntop.cpp:386] Built on Debian GNU/Linux 9.1 (stretch)23/Sep/2019 08:42:00 [Ntop.cpp:376] Welcome to ntopng x86_64 v.3.9.190910 - (C) 1998-19 ntop.org23/Sep/2019 08:42:00 [main.cpp:398] Scripts/HTML pages directory: /usr/share/ntopng23/Sep/2019 08:42:00 [main.cpp:396] Working directory: /var/lib/ntopng/voip_internal

i.e. I mean that original message "Temporarily unable to export Currently unable to export to InfluxDB. Retry in progress." seems misleading, because it fails to retry export automatically, but after restart it successfully proceeds with export.

**Comment by emanuele-f** [comment]
You should not get the `Cannot find ts file`, it is the reason why ntopng reports a temporary export failure. Can you post your `/etc/ntopng/ntopng.conf`?

**Comment by EpiqSty** [comment]
Here is a config of one instance:
```

$ cat /etc/ntopng/ntopng-voip_internal.conf  | grep -v "#"
-i tcp://*:5562c
-i tcp://*:5568c
-i tcp://*:5561c
-i tcp://*:5554c
-i tcp://*:5569c
-i tcp://*:5570c
-i tcp://*:5565c
-i tcp://*:5567c
--local-networks "<local networks omitted>"
--dump-flows nindex
--max-num-flows 262144
--data-dir  /var/lib/ntopng/voip_internal
--http-prefix /voip_internal
--instance-name voip_internal
--disable-login 1
--disable-autologout
--redis @0
--http-port 0
--https-port 3000
--ndpi-protocols /etc/ntopng/ndpi-custom.protos-voip_internal
```

we have 5 instances with different name, data-dir, redis-id, and zmq inputs.
After ` systemctl restart ntopng@voip_internal.service` it shows no errors, and proceeds with export.

**Comment by EpiqSty** [comment]
I got a bit more details, regarding such issue, seems it always starting happening after temporary memory issues, i found such logs:
`[Redis.cpp:507] ERROR: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.`
at the redis log  : 
```
1117:M 26 Sep 14:14:06.101 * 10000 changes in 60 seconds. Saving...
1117:M 26 Sep 14:14:06.104 # Can't save in background: fork: Cannot allocate memory
1117:M 26 Sep 14:14:12.019 * 10000 changes in 60 seconds. Saving...
1117:M 26 Sep 14:14:12.022 # Can't save in background: fork: Cannot allocate memory
1117:M 26 Sep 14:14:18.037 * 10000 changes in 60 seconds. Saving...
[...]
28319:C 26 Sep 14:19:01.242 * DB saved on disk
28319:C 26 Sep 14:19:01.245 * RDB: 1 MB of memory used by copy-on-write
1117:M 26 Sep 14:19:01.282 * Background saving terminated with success

```
The question, is why ntopng can't resolve such situation automatically, but only with ntopng instance restart?

**Comment by emanuele-f** [comment]
It seems like such corner case (non existing timeseries file) is not handled properly, so ntopng will treat it as a generic export error and will retry the export until the export queue is so long that it must be trimmed. This is something to fix, however you don't want to run out of free disk space

**Comment by simonemainardi** [comment]
Thanks for reporting. Issue should be fixed and will be available in the next dev build.

As you can see from your errors, it seems there are temporary persistency issues on your system. Indeed, also redis is failing to write to disk. So very likely what happens is that also ntopng fails to write export files to disk and so, it when it is time for the actual export, those files are missing. Now this situation is recovered automatically.
