### ISSUE TITLE
Implement OS distribution

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2874]
ntopng is able to detect the OS of hosts, and thus is able to bind to flows the OS behind it. It is requested to save these stats on the timeseries database so that we can make stats about OS usage of the network traffic

**Comment by simonemainardi** [comment]
Please, add OS timeseries as now OSes are implemented as any other hash table.

**Comment by simonemainardi** [comment]
This should be implemented already. Enabling this preference

![image](https://user-images.githubusercontent.com/3397663/108488221-6a60e180-72a0-11eb-884f-e36c9515ceba.png)

Cause charts to Appear:

![image](https://user-images.githubusercontent.com/3397663/108488458-b3189a80-72a0-11eb-928d-df6aecddde52.png)

It is requested to check how charts data points are written, to make sure points are using data calculated using the latest implementation of CountriesHash.h
