### ISSUE TITLE
Disaggregation Top Senders/Receivers mismatch

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#2875]
Hello,

I'm using probe IP disaggregation method.

To pinpoint heavy users we like to see top senders/receivers for a particular disaggregated site.

But instead of seeing IP addresses for that site, we only see them for the headquarter's site.

![Screenshot_2019-09-23_09-16-39](https://user-images.githubusercontent.com/38232155/65395837-3b141f80-dde3-11e9-9752-f80b9c475a17.png)

Are we configuring this wrong perhaps?

There is one nprobe instance, one ntopng instance, and about 11 netflow exporters in our WAN all sending on the same port to the nprobe service.

**Comment by emanuele-f** [comment]
Are you selecting the correct disaggregated interface from the "Interface" menu entry? If you look at the active hosts (click on the green badge in the footer), can you see all the site hosts there?

**Comment by ghost** [comment]
Yes, I am selecting the correct interface, that is how I arrived at the page you see in the screenshot.
Under active hosts green badge, I see all hosts for all interfaces.

Do you need me to dump my configuration files?

**Comment by ghost** [comment]
/etc/nprobe/nprobe-none.conf
```
--zmq="tcp://*:5556"
--collector-port=2055
-n=none
-i=none
-disable-l7-protocol-guess
-T="@NTOPNG@"
```

/etc/ntopng/ntopng.conf
```
-w=80
-i="tcp://127.0.0.1:5556"
-m="172.16.2.0/24,172.16.5.0/24,172.16.11.0/24,172.16.0.0/23,172.16.21.0/24,172.16.22.0/24,172.16.20.0/24,172.16.30.0/24,172.16.23.0/24,172.16.100.0/24"
-n=1
```

**Comment by emanuele-f** [comment]
When you apply disaggregation, each disaggregated interface should show a portion of the traffic, so it is not normal that you see all the hosts into a single interface.

Can you upgrade to the nightly version? In the first screenshot you can see that the table reports 20 rows whereas only 1 is shown, so I think this is a bug. This may be already fixed in the nightly version. Please refer to the instructions at http://packages.ntop.org for the nightly builds of your system.

**Comment by ghost** [comment]
Thanks, @emanuele-f 
Have upgraded to ntopng Enterprise Edition v.3.9.190924 - looks like a lot of work since 3.8.190605!
I'm sorry to say the top senders/receivers are still from all sites, and the list is clipped.
Is there a mass-data purge I can do? Clear out old data that may be damaging this? I don't mind starting fresh...just rather not re-install the OS.

**Comment by ghost** [comment]
It's also often unable to present _any_ top senders/receivers, in spite of the time range.

**Comment by simonemainardi** [comment]
@qautomotive 

> Is there a mass-data purge I can do?

stop ntopng then:

```
/var/lib/ntopng# find . -name top_talkers.db
./1/top_talkers/top_talkers.db
./27/top_talkers/top_talkers.db
./16/top_talkers/top_talkers.db
./-1/top_talkers/top_talkers.db
./0/top_talkers/top_talkers.db
/var/lib/ntopng# find . -name "top_talkers.db" -exec rm -rf {} \;
```

> It's also often unable to present any top senders/receivers, in spite of the time range.

Check if there are errors in the ntopng logs and report.

**Comment by ghost** [comment]
OK will update shortly.

**Comment by ghost** [comment]
```
$ find / -iname ntop*log
/var/log/ntop-systemd.log
```

```
$ tail -n6 /var/log/ntop-systemd.log 
Tue Oct  8 02:03:25 UTC 2019 nprobe StartPost
Tue Oct  8 02:03:25 UTC 2019 ntopng StartPre
Tue Oct  8 02:03:25 UTC 2019 ntopng StartPost
Tue Oct  8 02:03:29 UTC 2019 ntopng StopPost
Tue Oct  8 02:03:34 UTC 2019 ntopng StartPre
Tue Oct  8 02:03:34 UTC 2019 ntopng StartPost
```

**Comment by simonemainardi** [comment]
Did you run the cleanup as suggested above? for the status please do

```
sudo journalctl -u ntopng 
```

and scroll to the bottom

**Comment by ghost** [comment]
Yes I ran the talkers db cleanup, it has not helped.

There are no relevant errors in the journal.
There are a few complaints about email but that was disabled.
Otherwise the service seems happy.

**Comment by ghost** [comment]
Hi guys.

Thanks for your help on this.

You can close this as I don't have the ntopng VM any more.
