### ISSUE TITLE
Inconsistent number of alerted flows reported

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2877]
![Screen_Shot_2019-09-23_at_16_55_31](https://user-images.githubusercontent.com/4493366/65436996-5010a300-de23-11e9-9818-603c2fa668ea.png)

**Comment by simonemainardi** [comment]
fixed in https://github.com/ntop/ntopng/commit/68b7d484636222c9e10ece7b545a53d028ef967e
