### ISSUE TITLE
Inconsistent number of total alerts when following the hyperlink

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#2878]
host says total alerts 12

![image](https://user-images.githubusercontent.com/3397663/65441232-57877a80-de2a-11e9-84ed-3a40751810cf.png)

but after clicking the hyperlink, a page with 259 past alerts is opened

![image](https://user-images.githubusercontent.com/3397663/65441276-69691d80-de2a-11e9-86f2-a0f9d1de20d5.png)

**Comment by emanuele-f** [comment]
Note: total is "since startup". This is inconsistent everywhere if this is the case
