### ISSUE TITLE
Preference to reduce the timeseries resolution

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2884]
ntopng now supports increasing the timeseries resolution when InfluxDB is in place. However it should also be possible to decrease the resolution, for example dumpling L7 data every 15 minutes. 
Note: `top_talkers_utils.makeTopJson` re-iterates the hosts. Maybe it can be optimized by piggiebacking the iteration done for the timeseries.

**Comment by simonemainardi** [comment]
Implemented:

![image](https://user-images.githubusercontent.com/3397663/66832359-0d417700-ef5a-11e9-87ac-0f9ca20c2a8c.png)

It is now possible to choose the 5-min resolution for localhost points when they are  written to influxdb. In addition, high-resolution timeseries are now disabled for non-packet interfaces as it is pointless for them to have sub-minute points.
