### ISSUE TITLE
Rework Alerts Menu

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2888]
The alert logic is broken as the same page contains
- alert browsing (tabs "Past Alerts" and "Flow Alerts")
- alert configuration ("Minute".... "Settings")

![Screen Shot 2019-09-30 at 12 08 55](https://user-images.githubusercontent.com/4493366/65869627-20115480-e37b-11e9-842f-b7da348635af.png)

This logic must be keep split so users know when they are configuring alerts and when they are browsing alerts.

This ticket is for all alert configuration (interface, host....)

**Comment by simonemainardi** [comment]
Done. Now alert configuration fall under the general 'callbacks' tab for interfaces, hosts, networks, etc and the alerts tab only allows the browsing.
