### ISSUE TITLE
Add ability to cluster hosts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#289]
Ntopng should allow users to bind local hosts need to user names. Example if I have laptop X, tablet Y, they are not just two local hosts, but they are my local hosts, so the should be called "Luca's PCs". In essence it is necessary to cluster hosts at layer 2 and layer 3.
In essence it is necessary to introduce the concept of "community" for local hosts

**Comment by simonemainardi** [comment]
implemented in the host pools
