### ISSUE TITLE
Invalid menu combination 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2891]
TCP state filtering should apply only to TCP flows, and it has to be reset for non-TCP flows otherwise the search results will be empty as int he picture below.

![Screen Shot 2019-09-30 at 16 49 19](https://user-images.githubusercontent.com/4493366/65889940-5f06d080-e3a2-11e9-93b4-f4da430e1622.png)

**Comment by simonemainardi** [comment]
flow filters have been generalized in https://github.com/ntop/ntopng/commit/79ec20d6df8edb537a6c7a1f846e4ca9aa928a0c#diff-e8523b1d477a58356ced1930cf7d57e4R39 and re-used to populate dropdowns as well as to return the actual filtered flows.

This has the benefit to only show dropdowns menu correctly populated with the flows which remain after the filtering.
