### ISSUE TITLE
Retention time must be uniform

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2897]
Unify retention time across nIndex, mysql, etc. and time series into a single field

**Comment by simonemainardi** [comment]
implemented. now timeseries, flows (either mysql or nindex) and sqlite top-talkers have the same retention which can be set from the preferences:

![image](https://user-images.githubusercontent.com/3397663/66321391-c2ec4480-e920-11e9-837a-640fc51fad49.png)
