### ISSUE TITLE
Add the ability to access hosts no longer active

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2898]
When a local host is no longer active it cannot be accessed on the search box, even though when clicking on its name on a alert will "resurrect" the host on the fly by allowing access to historical information.

It is requested to add inactive hosts to the host search (e.g. add a marker similar to [SNMP] or [IPv6] in search results to indicate that this host is not active) so that people can jump on them.

Furthermore evaluate if it makes sense to create a list of hosts that "used to be active" to that people can access them from a table/list view

See also #2907

**Comment by emanuele-f** [comment]
Additional note: accessing historical charts should not require bringing up the host in memory.

**Comment by emanuele-f** [comment]
Ability to restore an host implemented in 4ee9eed2ac1373f325628779551aa2af44f06f80 , however we still need a way to to recover an host MAC address in order to properly deserialize DHCP hosts in the local broadcast domain

**Comment by emanuele-f** [comment]
Other changes implemented in d65bd41212e3c2961e66b4cb2abd2a03ab4ca57d and 03b69dfe64e544dcee5478352f9fe4e1559bbe7e

**Comment by simonemainardi** [comment]
working as expected. Please remove the additional step "click here to restore the host". When I select the host from the search box, I want to have it restored.

**Comment by simonemainardi** [comment]
the message 'click here to restore the host' should appear when the host page is left open and the host goes idle. Currently, what happens is the following

![image](https://user-images.githubusercontent.com/3397663/81187437-56b7e900-8fb4-11ea-9663-5b72dd3f4d05.png)

So basically we the message should be replaced with the other one.
