### ISSUE TITLE
aggregated_hosts_stats.lua

### ISSUE THREAD

**Issue by yurifrancalacci** [ntop/ntopng#29]
with a reverse proxy configuration environment no data are displayed in the aggregated_hosts_stats.lua page. Javascript console reports an error as follows:
aggregated_hosts_stats.lua:164 Uncaught SyntaxError: Unexpected token ILLEGAL
issue is probably caused by a misplaced ' " '
   var url_update =<http rev proxy path>"/lua/get_hosts_data.lua?aggregated=1";

**Comment by yurifrancalacci** [comment]
Double quotes should be moved from line 24 to line 22
     22    var url_update ="]]
     23 print(ntop.getHttpPrefix())
     24 print[[/lua/get_hosts_data.lua?aggregated=1]]

**Comment by ariava** [comment]
@yurifrancalacci thanks for spotting that! d1442c7 implements the fix you suggested.

**Comment by lucaderi** [comment]
@yurifrancalacci Please provide a merge request for these simple mispelling issues.
