### ISSUE TITLE
Implement Kibana 4 Dashboard

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#290]
Implement for Kibana 4 a new dashboard to be used by ntopng users to visualise network traffic information.

**Comment by lucaderi** [comment]
@lmangani Consider integrating ntopng as a beats producer for ElasticSearch Beats https://www.elastic.co/products/beats

**Comment by lmangani** [comment]
For those interested in testing and providing feedback the current dev version is available [here](https://github.com/ntop/nProbe/tree/master/kibana)

**Comment by lucaderi** [comment]
As grafana support is implemented, we believe this issue is no longer relevant
