### ISSUE TITLE
Execute a Lua script when an alert is triggered

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2902]
Add the ability to execute a Lua script when an alert is triggered. This would allow (some) Alert Endpoints to be migrated to lua for instance, and move some C++-based activities (e.g. syslog dump) to Lua

**Comment by emanuele-f** [comment]
Please note that this is already supported via alert_endpoints (they are implemented in pure lua), see https://github.com/ntop/ntopng/blob/dev/doc/README.alerts
