### ISSUE TITLE
Please add Chinese translation

### ISSUE THREAD

**Issue by Omoinemie** [ntop/ntopng#2911]
Please add Chinese translation

**Comment by emanuele-f** [comment]
We don't know Chinese. Are you willing to provide the Chinese translation? You can find the instructions on how to localize strings in https://github.com/ntop/ntopng/tree/dev/tools/localization .
If you can provide a translation file such as (https://github.com/ntop/ntopng/blob/dev/scripts/locales/jp.lua) we can integrate it

**Comment by simonemainardi** [comment]
We are unable to translate to Chinese without a community volounteer who knows the language and is willing to contribute. If you think you can do this, or know someone who would like to do this, let us know. We can support you, give instructions, and eventually include the translation in the dev branch. You will be credited for this. 

Feel free to reopen if willing to contribute.
