### ISSUE TITLE
Make ntopng work with Dark Reader browser extension

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#2913]
Hi all,

I often user Dark Reader (https://github.com/darkreader/darkreader), to darken my screen as I spend many hours staring at different web pages.

Is there a chance you could think about adapting ntopng to work with the Dark Reader Extension

An example off:
![image](https://user-images.githubusercontent.com/48565067/66219767-c15d1b00-e699-11e9-9555-f52718a169d8.png)

On:
![image](https://user-images.githubusercontent.com/48565067/66219815-d5088180-e699-11e9-83cb-56bf25cdb149.png)

The black text is the issue, it doesn't invert correctly

**Comment by simonemainardi** [comment]
@StewAlexanderACC, actually, chart axes are text in SVG images:

![image](https://user-images.githubusercontent.com/3397663/66736158-be67e480-ee68-11e9-88fd-3c3a2cfdd950.png)

Do you know if the extension supports changing colors in SVG images text elements?

**Comment by StewAlexander-com** [comment]
@simonemainardi Unsure, but the extension is free to download from the chrome store / firefox add-on store and you can post to their github site I mentioned earlier

**Comment by StewAlexander-com** [comment]
The extension also comes with its own devtools

![image](https://user-images.githubusercontent.com/48565067/66750600-dcc6e380-ee5a-11e9-9283-5cb7372cd213.png)

**Comment by simonemainardi** [comment]
@StewAlexanderACC can you take care of this issue and possibly interact with the darkreader guys to see if it is actually possible to change the svg text fields?

**Comment by StewAlexander-com** [comment]
Sure, but it may be a few days

**Comment by simonemainardi** [comment]
yes, no problem. thank you.

**Comment by StewAlexander-com** [comment]
[Issue 1648 opened with DarkReader](https://github.com/darkreader/darkreader/issues/1648)

**Comment by simonemainardi** [comment]
@StewAlexanderACC do you have any news?

**Comment by StewAlexander-com** [comment]
I opened a ticket over at the github darkreader site (https://github.com/darkreader/darkreader/issues/1648)  have heard zero feedback

**Comment by simonemainardi** [comment]
@StewAlexanderACC let's close this for now. Feel free to reopen and comment if the guys at darkreader will respond at some future point in time. Thanks for your effort, anyway.
