### ISSUE TITLE
hello.ntop.org redirects to the captive portal page

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2914]
nEdge should be recalled when visiting hello.ntop.org . We should also evaluate the possibility to move the default http/s port to 80/443 to make nEdge easily accessible at `http://hello.ntop.org`

**Comment by simonemainardi** [comment]
Currently:

- Port 80 is used by captive portal (when enabled)
- Typing `hello.ntop.org` would bring the user to the captive portal page or to a non-existing page. The desired behavior is to bring the user to the management page, which is currently reachable only if also the port is typed, e.g.,  `http://hello.ntop.org:3000`

A clean implementation would involve:
- Moving the captive portal port from 80 to another port, and properly handle the DNAT with iptables
- Start the nEdge management webserver on port 80.

**Comment by simonemainardi** [comment]
After internal review, we have decided that the current behavior is consistent:

- Regular captive portal users will reach the captive portal normally
- Administrators will just have to add `:3000` to the call home address, which is normal and expected from an administrator (already familiar with ntopng)

Current implementation has also the benefit of being less complex, without an extra DNAT.
