### ISSUE TITLE
Count userspace packets vs total

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2915]
Count userspace vs total packets to ensure that offloading is working properly (e.g. only the first X packets of the flows are seen by nEdge)

**Comment by simonemainardi** [comment]
This is more a debug feature which gives an indication on how well nEdge is offloading to the kernel.

Indeed, it would be nice to have, for each flow, the number of packets that have been actually seen by nEdge, and the number of packets which have just been counted using conntrack.

**Comment by simonemainardi** [comment]
Implemented. Now the traffic for each physical interface is compared with userspace traffic. Example.

![image](https://user-images.githubusercontent.com/3397663/140379453-74ff79e4-c0f5-4c98-b787-bf23717b0ffe.png)

**Comment by lucaderi** [comment]
Verified as fixed
