### ISSUE TITLE
Implement monthly and weekly quotas

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2917]
Implement the ability to specify the quota period duration (currently it's daily only). Monthly/weekly/daily selection can be implemented via an additional dropdown on the protocol/category

**Comment by simonemainardi** [comment]
Quotas are currently kept using HostPoolStats which are reset at midnight to implement daily quotas.

Adding monthly and weekly quotas would require to have extra HostPoolStats classes instances. However, given the current (complex) quota implementation, I would suggest to first investigate the possibility to implement quotas using netfilter to re-use existing mechanisms.

**Comment by simonemainardi** [comment]
A fairly simple implementation can involve a dropdown to choose whether quotes are

- Daily
- Weekly
- Montly

And tune the reset accordingly

**Comment by lucaderi** [comment]
Verified as fixed
