### ISSUE TITLE
List of active DHCP leases in router mode

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2918]

**Comment by simonemainardi** [comment]
In router mode,  a DHCP server can be enabled/disabled from the preferences. In order to implement this we need to:

- Check the runtime status of the DHCP daemon (e.g., dhcpd)
- Read the current leases
- Show them in the UI

**Comment by simonemainardi** [comment]
When nEdge has the DHCP server enabled, then DHCP ranges are known a priori and they should be added automatically to the interface DHCP ranges used for the hosts serialization by Mac.

**Comment by lucaderi** [comment]
When a lease changes, it is request to keep track of a log of MAC/IP assignment

**Comment by simonemainardi** [comment]
Implemented and documented in referenced commits (and pro companion commits)

![image](https://user-images.githubusercontent.com/3397663/139907979-eb87ebcc-7cb6-4377-9775-7867822d7ba7.png)

**Comment by lucaderi** [comment]
Verified as fixed
