### ISSUE TITLE
Make hello.ntop.org vendor configurable

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2920]

**Comment by simonemainardi** [comment]
See:

```
include/ntop_defines.h:#define CONST_HELLO_HOST                "hello"
```

This #define needs to become a variable so that OEMs can configure it.

In C, the function which checks and do the redirect is `isCallHomeAddress`. The response is forged in class `DnsHostMapping` which returns the LAN address of the nEdge device.

**Comment by simonemainardi** [comment]
when `ntop->getPro()->is_oem()`, it would be desirable to respond to `<product_name>.local`

**Comment by cardigliano** [comment]
isCallHomeAddress now also checks `hello.<product>.local` in case of OEM
