### ISSUE TITLE
Optimize host scripts with efficient metric access

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2921]
Periodic host scripts require complete host serialisation that is not efficient. It is requested to implement the same logic used in flow scripts with efficient metric access.

**Comment by simonemainardi** [comment]
basically:

Host::lua should be split into multiple lua_get_xxx lua_get_yyy and such lua_get_ also have to be exposed through host.<method> lua calls.

**Comment by emanuele-f** [comment]
The new api should also be documented in this format: https://github.com/ntop/ntopng/blob/dev/doc/src/api/lua_c/flow/flow.lua

**Comment by simonemainardi** [comment]
Implemented. Brought the speed up from 3.3k to 250k hosts per second.
