### ISSUE TITLE
Get the same format of data on webhook on ntopng alert as we get when we access Ntop alert REST API

### ISSUE THREAD

**Issue by venkatramanh265** [ntop/ntopng#2922]
![image](https://user-images.githubusercontent.com/26563435/66293476-56634c80-e904-11e9-88c2-733f4de26fd6.png)

while Access the REST API of alert I am getting the data in the correct format like "severity"="error"
but when I created a webhook and added it to the ntop alert endpoint I am not the receiving the alert data in the same format, there it is coming as 'alert_severity': '2'.

Could you please add a feature, so that I can receive the data in the webhook in the same format as the REST API.
![image](https://user-images.githubusercontent.com/26563435/66293730-ea351880-e904-11e9-8d7a-4c9658df5d02.png)

**Comment by cardigliano** [comment]
@venkatramanh265 actually what you get from the REST API at the moment is formatted (as you can see there are html tags) and localized, instead what you get from the webhook is raw data. I think that it is preferable to get raw information from an API (both REST and webhook). 
Any reason you cannot handle fields like the severity number on the webhook consumer?

**Comment by venkatramanh265** [comment]
When i went through the data received from the REST API there is a field  called "msg" which gives the details of the alert occured but the same fiels "msg" is not present in the data which I receive from webhook.
Kindly let me know how to get that fiels in webhook.

**Comment by cardigliano** [comment]
@venkatramanh265 as I said you get all the details for the alert, but you do not get a message (as it depends on localization, and sometimes includes html tags, etc). You can use the alert_type to parse the alert and get all the information. Please visit http://<ntopng ip>:3000/lua/defs_overview.lua for all alert types and descriptions.
