### ISSUE TITLE
Clean up flow.lua methods calls

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2923]
Currently, calling `flow.some_method()` results in two behaviours:

1. `ntop_flow_reg` functions calls
2. `callMethodById` calls

This creates confusion as the same invocation results into two different behaviors. This will become worse if we implement the same mechanism for #2921 , as the `ntop_host_reg` has a lot more functions. A possible approach is to use a different invocation for 1 or 2, e.g.:

1. flow.some_method() -> uses `ntop_flow_reg`
2. flow_ctx.another_method() -> use `callMethodById`

Maybe it's even better if we remove the metatable and perform the call explicitly:

1. flow.some_method() -> uses `ntop_flow_reg`
2. `flow.call("another_method", ...)` -> still uses `ntop_flow_reg`, but now it's clear that `call` is a proxy with another namespace of functions

**Comment by simonemainardi** [comment]
Implemented in https://github.com/ntop/ntopng/commit/27444ec067c6883d35da74364346b4d224f0e605

now flow.<> are handled as regular metatable calls as for the hosts, interfaces, networks, and ntop.
