### ISSUE TITLE
Create an independent page for directory settings

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2924]
![Screen Shot 2019-10-07 at 09 12 37](https://user-images.githubusercontent.com/4493366/66295413-8b16da00-e8eb-11e9-9606-d3f35a67799e.png)

**Comment by simonemainardi** [comment]
implemented

![image](https://user-images.githubusercontent.com/3397663/66310206-e1941080-e90b-11e9-8335-d3d12652a411.png)


link from custom scripts page added as well
