### ISSUE TITLE
Add benchmark information to hosts scripts 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2925]
Same as for flow scripts, benchmark information must be added to host scripts.

**Comment by emanuele-f** [comment]
I'm unifying the hosts and flows api, please postpone after the modifications

**Comment by emanuele-f** [comment]
Code unified in ede9a7940a65df8122f5ca65f066a4b8d1b07bab

**Comment by simonemainardi** [comment]
implemented
