### ISSUE TITLE
Influx data generation is inefficient

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2927]
Currently line protocol generation is inefficient as there are too many C++/Lua calls to be performed per write. This needs to be reworked.

**Comment by emanuele-f** [comment]
Probably the issue occurs due to excessive number of locks in TimeseriesExporter::exportData. If this is the case, an idea is to buffer line protocol data in a per-vm structure and then batch call TimeseriesExporter::exportData periodically.

**Comment by simonemainardi** [comment]
Found that `write` was used in place of `fwrite` causing significant performance degradation. Using `fwrite` has doubled the number of points written per second from 400k to 900k.

Commit is: https://github.com/ntop/ntopng/commit/aa46f93297bb60be8dea6a60c05ed7aadd3a5561

For the current use-case, considering a single-node influxdb instance cannot ingest more than 1M points per second, we consider this performance satisfactory.
