### ISSUE TITLE
Hide inactive scripts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2929]
With the creation of host/alert/flow scripts there are many of them (in particular hosts) that are present yet inactive as have no value configured. It is requested to change the GUI to add a toggle that by default shows only the configured scripts (for alerts those that have a threshold set), only those not configured (so people cn see what to all) or all scripts. It is just a cosmetic change that makes people life easier.

Note that this ticket has a dependency on #2974

**Comment by emanuele-f** [comment]
This is implemented into the new user_scripts gui.
