### ISSUE TITLE
Extend the Syslog interface to call Lua scripts

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#2932]
The Syslog parser interface now handles Suricata flows and alerts in C++, it is required to extend this component to be able to process events from Lua scripts.
The script is loaded from scripts/callbacks/syslog/ at initialization time for performance reason (reloading the script on file changes will be evaluated later), and an handler function is called for each event (the performance for an empty pcall function is ~800K call/sec)
A sample script that handles Suricata alerts is created in an initial implementation.

**Comment by cardigliano** [comment]
Syslog events are handled by multiple scripts in scripts/callbacks/syslog/, one for each application (the script name should be the application name). A sample script has been created for Suricata alerts (suricata.lua). Implemented in 1f3c824814188bf8493bc5f8fdced4515eb0f0d1 b203201b91db963566da3f6b3f8feed90fab28ad e05f9aa4f4272fdb6f0d32e10e403806eba1c0a3

**Comment by lucaderi** [comment]
Please describe how you plan to interact with the syslog and how this script can trigger alerts or create new flows. Probably the best is to write a simple script for demonstration purposes.

**Comment by cardigliano** [comment]
The C++ SyslogParserInterface reads messages from syslog and dispatches them to Lua scripts based on the application name extracted from the log message itself. At the moment "suricata" is an exception as flow/alert parsing happens in C++ (alerts are delivered to the Lua script anyway to implement a sample script).
Alert generation from Lua scripts has not been implemented yet, it will be possible as soon as https://github.com/ntop/ntopng/issues/2842 has been completed.

**Comment by cardigliano** [comment]
A new Lua interface.processFlow API has been implemented in a2e74e16a38869644ab24bb45cc240b54f8ba907 to allow flow (and external alerts) processing from Lua. Processing of Suricata messages from Syslog has been moved to Lua in  76759a7d0372df10dce088bc552e26395a714ea7 and both flows and alerts (through C++) are now generated through the Lua script.
