### ISSUE TITLE
Jump to the alert rule

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2936]
<img width="1240" alt="Screenshot 2019-10-10 at 23 10 54" src="https://user-images.githubusercontent.com/4493366/66606877-50df5e00-ebb3-11e9-9a43-826e1caf4a14.png">

In alerts it would be nice to add a button that allows users to just (in one click) to the alert rule that triggered a certain event. This would be nice for instance for changing the rule parameters (e.g. the threshold) that were used in the rule that triggered the alert.

**Comment by emanuele-f** [comment]
The `alerts_api.addAlertGenerationInfo` function adds the section `alert_generation` into the alert json containing the metadata required to create a link to the specific alert configuration page. A link is added to the alert message pointing to the configuration page:

![2020-01-17_19-16](https://user-images.githubusercontent.com/5488003/72635786-900d1000-3955-11ea-85d7-9f4919b0a24b.png)
