### ISSUE TITLE
Dashboard is empty for ntopng

### ISSUE THREAD

**Issue by Somayyah** [ntop/ntopng#2939]
Good evening/morning

I've been looking for an open source netflow solution to monitor my network and I've chose ntopng and nProbe, I've configured them on windows 10 correctly but dashboard shows nothing.
I can't even find hosts or any device connected on the network am I missing something?

**Comment by Somayyah** [comment]
No talkers:
![image](https://user-images.githubusercontent.com/55834191/66701047-2f3fbd00-ed00-11e9-8870-bb8ec571ecd1.png)
No hosts:
![image](https://user-images.githubusercontent.com/55834191/66701054-467eaa80-ed00-11e9-9b58-e4dd6ada9762.png)

**Comment by simonemainardi** [comment]
You need to create a ZMQ interface. Please, go through https://www.ntop.org/nprobe/network-monitoring-101-a-beginners-guide-to-understanding-ntop-tools/ in particular section "Monitoring Netflow/sFlow Traffic" which explains how to monitor NetFlow.
