### ISSUE TITLE
README.compilation file need to be updated for Centos 8.

### ISSUE THREAD

**Issue by xgerligand** [ntop/ntopng#2941]
Hi all.

It seems necessary to add **json-c-devel** and **readline-devel** to file README.compilation (line 40).
I compiled then on a fresh installed Centos 8 with success.

Thank you.

**Comment by simonemainardi** [comment]
thanks for pointing it out: https://github.com/ntop/ntopng/commit/232e04aa0de08e1e1789d2c0421a391a06053f41

json-c-devel was missing from the list, no need for readline-devel though.
