### ISSUE TITLE
Enhance alert endpoints

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2944]
- Alert endpoints should also be called when the sqlite database is disabled
- They should be called via a lua vm with an entity context set. This removes the need to push flow information into a redis queue
- After that, evaluate if it's necessary to decouple endpoint alert export from the periodic_stats_update thread (this would probably require adding a new status into the entities automa)

**Comment by simonemainardi** [comment]
> Alert endpoints should also be called when the sqlite database is disabled

https://github.com/ntop/ntopng/issues/4325

> They should be called via a lua vm with an entity context set. This removes the need to push flow information into a redis queue

For the time being, we decided not to do this.

> After that, evaluate if it's necessary to decouple endpoint alert export from the periodic_stats_update thread (this would probably require adding a new status into the entities automa)

This is decoupled in the latest implementation.
