### ISSUE TITLE
Massive ERROR poped after upgrade to version "3.9.191016"

### ISSUE THREAD

**Issue by underleo** [ntop/ntopng#2949]
After upgrade to version "3.9.191016", massive ERROR popup in system log. Frequency about 5seconds per log. All other function seems works well and haven't observed any significant impact by far.

16/Oct/2019 17:23:55 [GenericHashEntry.cpp:63] ERROR: Internal error: invalid state transition 3 -> 1
16/Oct/2019 17:23:55 [GenericHashEntry.cpp:63] ERROR: Internal error: invalid state transition 3 -> 1
16/Oct/2019 17:23:55 [GenericHashEntry.cpp:63] ERROR: Internal error: invalid state transition 3 -> 1
16/Oct/2019 17:23:55 [GenericHashEntry.cpp:63] ERROR: Internal error: invalid state transition 3 -> 1
16/Oct/2019 17:23:52 [GenericHashEntry.cpp:63] ERROR: Internal error: invalid state transition 3 -> 1
16/Oct/2019 17:23:51 [GenericHashEntry.cpp:63] ERROR: Internal error: invalid state transition 3 -> 1
16/Oct/2019 17:23:50 [GenericHashEntry.cpp:63] ERROR: Internal error: invalid state transition 3 -> 1
16/Oct/2019 17:23:50 [GenericHashEntry.cpp:63] ERROR: Internal error: invalid state transition 3 -> 1
16/Oct/2019 17:23:50 [GenericHashEntry.cpp:63] ERROR: Internal error: invalid state transition 3 -> 1

**Comment by emanuele-f** [comment]
Can you post your ntopng.conf file?

**Comment by simonemainardi** [comment]
hi, the issue should be fixed now. please, hold on an hour (a new build is being generated) and let me know.

**Comment by underleo** [comment]
Issue fixed after upgraded to "3.9.191023-7578".
Thank you.
