### ISSUE TITLE
Integrate ntopng with n2disk

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#295]
Add the ability to tell ntopng that n2disk is active and configured so you can schedule packet extraction directly from ntopng onto n2disk dumped files..

**Comment by lucaderi** [comment]
@simonemainardi Please update the status of this issue

**Comment by simonemainardi** [comment]
@lucaderi the integration is done, available on the Pro edition. 

A button 'request pcap is shown at the bottom of historical top talkers and protocols':
![image](https://cloud.githubusercontent.com/assets/3397663/13359741/05ba2ea6-dcb6-11e5-8aee-630b3030d271.png)

Clicking on the button triggers a request to the nbox. The request carries a BPF filter generated on the  basis of begin and end epochs, as well as source and destination hosts selected.

The list of all the requested pcap is available in the 'pcap' tab, that is visible only if the nbox integration has been enabled and configured via ntopng preferences:
![image](https://cloud.githubusercontent.com/assets/3397663/13359812/43c8502e-dcb6-11e5-945e-f1109e7ef67c.png)

I would kindly ask @ValentinaViscarelli to give it an overall try.

**Comment by lucaderi** [comment]
@ValentinaViscarelli Any news?

**Comment by simonemainardi** [comment]
Implemented and available in the latest ntopng.

The feature is called "Continuous traffic recording" and is documented at: https://www.ntop.org/guides/ntopng/advanced_features/traffic_recording.html?highlight=n2disk
