### ISSUE TITLE
Minute host custom scripts taking too long

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#2951]
Just the minute host custom scripts enabled by default take more than one minute to execute with ~300k local hosts. This causes the minute.lua to take longer than expected.

![image](https://user-images.githubusercontent.com/3397663/66920850-6675dd00-f024-11e9-8957-0e6cb2529b64.png)

**Comment by simonemainardi** [comment]
such custom scripts also slow down the other activities in minute.lua, ending up in missing timeseries datapoints. This is what happens for example. After manually commenting out the execution of periodic hosts scripts, the timeseries becomes continuous again:

![image](https://user-images.githubusercontent.com/3397663/66921811-2f083000-f026-11e9-86aa-c8dea9837ac5.png)

**Comment by emanuele-f** [comment]
This is also linked to #2921 .

**Comment by simonemainardi** [comment]
slowness is mostly due to the `alerts_api.trigger` and `alerts_api.release` calls so basically with database interactions.

Commenting their body yield almost negligible times:

![image](https://user-images.githubusercontent.com/3397663/66988913-a344e100-f0c3-11e9-833f-edfca5175152.png)

**Comment by simonemainardi** [comment]
fixed in https://github.com/ntop/ntopng/commit/43d0b89bd95e2c7597124b8267dd52aef75235b0. issue was due to massive unnecessary calls to alerts_api.release. brought down the time to a buch of seconds

![image](https://user-images.githubusercontent.com/3397663/67039392-8c34dc00-f121-11e9-9f03-b230ff576714.png)
