### ISSUE TITLE
Allowed Top Level Domains for mail address syntax not sufficient

### ISSUE THREAD

**Issue by totti4ever** [ntop/ntopng#2955]
I have an .online domain and cannot use e-mail addresses on that domain for alerts with ntopng. It says "Ihre Eingabe muss mit dem geforderten Format übereinstimmen.", which is something like "Your input has to apply the given format"

**Comment by simonemainardi** [comment]
Thanks for reporting. Issue is fixed. Will be available in the next dev build ready in less than one hour.
