### ISSUE TITLE
SQLite alert database grows indefinitively

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2956]
Overtime the SQLite database used to store alerts grows, and keeps growing. This even if alerts have been deleted. Due to this, disk becomes full. This problem needs to be addressed,

**Comment by simonemainardi** [comment]
addressed in https://github.com/ntop/ntopng/commit/f8443ff03d81abc9a2f6a6f1193ca3023cbd08db

disk space is reclaimed and database tables are defragmented in the daily.lua script
