### ISSUE TITLE
Periodic script execution flawed with pcap files

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2957]
Periodic scripts such as for instance the timeseries export, second.lua are called even when pcap files (-i <pcap>) are processed. This is not necessary and needs to be fixed, in particular when the pcap file has been fully processes.

**Comment by cardigliano** [comment]
Implemented with
https://github.com/ntop/ntopng/blob/dev/src/ThreadedActivity.cpp#L314
and
https://github.com/ntop/ntopng/commit/2da3bafe10c898a6eec875bd46c14ceebd0a0c91
