### ISSUE TITLE
Implement ntopng restart/update

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2958]
Only if ntopng is installed as package and thus systemd controlled, it has to 
- notify users that a new package update is available
- propose to update and restart ntopng

All from the menu without using the CLI (of course only for admins).

The code for doing this can be taken from the nfw project

**Comment by emanuele-f** [comment]
Temporary work for the ntopng stop/restart committed to https://github.com/emanuele-f/ntopng/tree/restart_ntopng

**Comment by cardigliano** [comment]
Implemented
