### ISSUE TITLE
nbox installed, but in the applications menu, no applications installed although ntopng an nProbe are installed on the system

### ISSUE THREAD

**Issue by Krokx** [ntop/ntopng#296]
I have installed the pro version of ntopng 2.2 and nProbe on my Raspbian system and then installed nbox too. The nbox interface works ok, but it doesn't recognize any applications installed. 

How can I make nbox "see" the installed ntopng and nProbe applications?

**Comment by lucaderi** [comment]
@Krokx We have not designed the nBox for the Raspbian but just for x86, thus it might be it does not work as you reported. Please use it on x64

**Comment by Krokx** [comment]
ok, is there a chance to get nbox for Raspbian in the future?

Pozdrawiam

Tomasz Krokosz


2015-12-03 18:48 GMT+01:00 Luca Deri <notifications@github.com>:

**Comment by lucaderi** [comment]
Not at the moment as you are the only one that so far asked for it.
