### ISSUE TITLE
Change geo map provider

### ISSUE THREAD

**Issue by ingria** [ntop/ntopng#2960]
Google Maps changed their API and TOS some time ago. Now they require to have "billing" enabled for developer's account. Otherwise there's a gray rectangle instead of the widget.

Having active billing account causes some complications, aside from that "Geo Map" feature won't work out of the box. So I suggest switching to other map provider (like openstreetmaps). I can try to fix this, but I'll need some guidance.

I know there are already [some](https://github.com/ntop/ntopng/issues/2433) [other](https://github.com/ntop/ntopng/issues/1963) issues regarding this problem, but right now this is more like "bug report" than "feature request".

**Comment by lucaderi** [comment]
@ingria Thanks for the offer to help. Please tell what you need exactly for assisting you with this port to openstreemap

**Comment by simonemainardi** [comment]
@ingria please let us know if you need help. We would be happy to assist you.

**Comment by ingria** [comment]
Just general recommendations would be OK for now.

I was thinking about using leaflet.js, so that it will be possible to easily change data provider in the future (openstreetmaps/bing/google etc). But it will add extra frontend dependency. Is it fine?

**Comment by simonemainardi** [comment]
@ingria yes this is ok an sorry for this late reply, we missed the message

**Comment by simonemainardi** [comment]
@gabryon99 please take care of this

**Comment by emanuele-f** [comment]
We could also evaluate to use a more basic map like: https://nabeelshahid.wordpress.com/2015/02/13/jvectormap-javascript-html-svg-based-world-world-regions-territories-countries-maps-plugin

**Comment by gabryon99** [comment]
Geomap provider change to OSM.
