### ISSUE TITLE
Implement host contacts counter

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2961]
When detecting scans or malware, it can be helpful to implement a counter of hosts being contacted at a given time. This can be computed based on the number of active flows, or on a per-minute basis.

**Comment by simonemainardi** [comment]
this should already be implemented (for local hosts). please check

![image](https://user-images.githubusercontent.com/3397663/67472082-d1d93380-f650-11e9-9a83-06a41f0a3e71.png)

and report if that is what you were looking for

**Comment by simonemainardi** [comment]
I confirm this is implemented in the screenshot above.
