### ISSUE TITLE
Create Mirai-like detection plugin

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2962]
As explained in https://www.usenix.org/system/files/conference/usenixsecurity17/sec17-antonakakis.pdf Mirai bot uses port 23 and 2323 to spread out. Unfortunately even though this is an old attack, there is still some ongoing infection happening. It would be nice to create a flow script used to detect potential Mirai-like activities such as scans towards TCP port 23 and 2323.

See also  #2963

**Comment by cardigliano** [comment]
SYN scan has been implemented with #2963. Do we need specific/additional checks for this?

**Comment by cardigliano** [comment]
#2963 also detects this
