### ISSUE TITLE
ntopng unable to detect scans

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2963]
A big limitation of ntopng is the inability to report scanners. Enclosed a trace to reproduce the problem. Tools like nmap could also be used to scan hosts/netwoks and they should also be detected. Enclosed a scan example that is not detected as such.

[scan.pcap.gz](https://github.com/ntop/ntopng/files/3747709/scan.pcap.gz)

Note that the above scanner is likely also to be Mirai-infected #2962

**Comment by cardigliano** [comment]
Implemented
