### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2964]
Over and over

20/Oct/2019 12:07:41 [LuaEngine.cpp:11150] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flow_data.lua][/usr/share/ntopng/scripts/lua/modules/http_lint.lua:1630: [LINT] _GET["flow_hash_id"] = "Info" parameter error: Validation error]
20/Oct/2019 12:07:41 [LuaEngine.cpp:11150] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flow_data.lua][/usr/share/ntopng/scripts/lua/modules/http_lint.lua:1630: [LINT] _GET["flow_hash_id"] = "Info" parameter error: Validation error]
20/Oct/2019 12:07:41 [LuaEngine.cpp:11150] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flow_data.lua][/usr/share/ntopng/scripts/lua/modules/http_lint.lua:1630: [LINT] _GET["flow_hash_id"] = "Info" parameter error: Validation error]
20/Oct/2019 12:07:40 [LuaEngine.cpp:11150] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flow_data.lua][/usr/share/ntopng/scripts/lua/modules/http_lint.lua:1630: [LINT] _GET["flow_hash_id"] = "Info" parameter error: Validation error]
20/Oct/2019 12:07:40 [LuaEngine.cpp:11150] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flow_data.lua][/usr/share/ntopng/scripts/lua/modules/http_lint.lua:1630: [LINT] _GET["flow_hash_id"] = "Info" parameter error: Validation error]
20/Oct/2019 12:07:40 [LuaEngine.cpp:11150] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flow_data.lua][/usr/share/ntopng/scripts/lua/modules/http_lint.lua:1630: [LINT] _GET["flow_hash_id"] = "Info" parameter error: Validation error]
20/Oct/2019 12:07:40 [LuaEngine.cpp:11150] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flow_data.lua][/usr/share/ntopng/scripts/lua/modules/http_lint.lua:1630: [LINT] _GET["flow_hash_id"] = "Info" parameter error: Validation error]
20/Oct/2019 12:07:40 [LuaEngine.cpp:11150] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flow_data.lua][/usr/share/ntopng/scripts/lua/modules/http_lint.lua:1630: [LINT] _GET["flow_hash_id"] = "Info" parameter error: Validation error]
20/Oct/2019 12:07:40 [LuaEngine.cpp:11150] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flow_data.lua][/usr/share/ntopng/scripts/lua/modules/http_lint.lua:1630: [LINT] _GET["flow_hash_id"] = "Info" parameter error: Validation error]
20/Oct/2019 12:07:40 [LuaEngine.cpp:11150] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flow_data.lua][/usr/share/ntopng/scripts/lua/modules/http_lint.lua:1630: [LINT] _GET["flow_hash_id"] = "Info" parameter error: Validation error]
20/Oct/2019 12:07:31 [LuaEngine.cpp:11150] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flow_data.lua][/usr/share/ntopng/scripts/lua/modules/http_lint.lua:1630: [LINT] _GET["flow_hash_id"] = "Info" parameter error: Validation error]
20/Oct/2019 12:07:31 [LuaEngine.cpp:11150] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flow_data.lua][/usr/share/ntopng/scripts/lua/modules/http_lint.lua:1630: [LINT] _GET["flow_hash_id"] = "Info" parameter error: Validation error]

**Comment by simonemainardi** [comment]
please explain which (if any) page is open in the UI while you are experiencing this
