### ISSUE TITLE
Category lists is cached

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2967]
When updating the category lists by editing for instance BUILTIN_LISTS in lists_utils.lua, the modified list (e.g. when changing the URL of an entry) is not immediately used by ntopng that still uses the old value. The bug is in loadListsFromRedis() where redis info is not updated with new values for the BUILTIN_LISTS

**Comment by emanuele-f** [comment]
Additional note: in order to clean the existing serialization it's required to manually go into the Category Lists and change one preference. Now only the diff from the default settings will be stored.
