### ISSUE TITLE
SysLog: Warning Script Failure second.lua - Bad Argument #2

### ISSUE THREAD

**Issue by war59312** [ntop/ntopng#2968]
Hi,

/var/log/syslog is showing this warning over and over again:

`ntopng[32024]: 20/Oct/2019 07:26:03 [LuaEngine.cpp:10203] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/second.lua][/usr/share/ntopng/scripts/lua/modules/ntop_utils.lua:197: bad argument #2 to 'format' (number has no integer representation)]`

> $ ntopng --version
> v.3.9.190913	[Enterprise/Professional/Embedded build]
> GIT rev:	dev:b7d459dd2b71b4a4a3ff69296d30cc8766744526:20190913
> Pro rev:	r2445
> Built on:	Raspbian GNU/Linux 10 (buster)
> System Id:	44073318499602D2
> Platform:	armv7l
> Edition:	Enterprise Embedded
> License Type:	Time-Limited [Empty license file]
> Validity:	Until Sun Oct 20 14:30:03 2019

With Raspbian Pi 4 Buster.

Line 197 in /usr/share/ntopng/scripts/lua/modules/ntop_utils.lua is:

`return(string.format("%u", math.floor(what)))`

Thanks,

Will

**Comment by cardigliano** [comment]
A trace has been added when this occurs to debug this issue, please report it. Thank you.

**Comment by emanuele-f** [comment]
@war59312 I tested this with latest package and was unable to reproduce. Please update to the latest version an provide the new trace

**Comment by war59312** [comment]
Thanks, I just noticed the upgrade available. :)

Now on:

> v.3.9.191023	[Enterprise/Professional/Embedded build]
> GIT rev:	dev:d1d789ea881117a64b72dfebdba630a609e8a7f3:20191023
> Pro rev:	r2500
> Built on:	Raspbian GNU/Linux 10 (buster)
> System Id:	44073318499602D2
> Platform:	armv7l
> Edition:	Enterprise Embedded
> License Type:	Time-Limited [Empty license file]
> Validity:	Until Thu Oct 24 18:54:12 2019

During the upgrade, I noticed this, the last line:

```
Fetched 249 MB in 6min 41s (621 kB/s)                                                                                                                                                                                                        
Reading changelogs... Done
Preconfiguring packages ...
(Reading database ... 157945 files and directories currently installed.)
Preparing to unpack .../0-nprobe_8.7.191023-6652_armhf.deb ...
Unpacking nprobe (8.7.191023-6652) over (8.7.190913-6618) ...
Preparing to unpack .../1-ntopng_3.9.191023-7935_armhf.deb ...
Stopping ntopng services...
Removed /etc/systemd/system/multi-user.target.wants/ntopng.service.
Invalid unit name "ntopng@*" was escaped as "ntopng@\x2a" (maybe you should use systemd-escape?)
```

And:

```
Invalid unit name "edge@*.service" was escaped as "edge@\x2a.service" (maybe you should use systemd-escape?)
edge@*.service is a disabled or a static unit not running, not starting it.
Invalid unit name "edge-ntopng@*.service" was escaped as "edge-ntopng@\x2a.service" (maybe you should use systemd-escape?)
edge-ntopng@*.service is a disabled or a static unit not running, not starting it.
```

Everything seems fine. Will monitor SysLog.

PS: http://apt.ntop.org needs a bandwidth upgrade. I was lucky to get 621 KB/s (upgrade took 6 minutes and 41 seconds just to download packages). I'm on AT&T Fiber 1 GB/s. So pretty darn slow. Perhaps some download mirror sites would sponsor you.

**Comment by simonemainardi** [comment]
Thanks for reporting. Please, open a separate issue for the seemingly wrong escaping. Thank you.

**Comment by war59312** [comment]
Sadly still getting the same "Warning Script Failure second.lua - Bad Argument #2" in SysLog.

How to get you a trace?

**Comment by emanuele-f** [comment]
The trace should be reported in the log just before the script failure error
