### ISSUE TITLE
Trigger an alert when hosts scripts are slow

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2970]
When hosts periodic scripts are too slow (e.g. the minute scripts last more than a minute) noting should generate an alert reporting the result of the last run. This to identify the root cause of the problem.

There is already an alert that should report this problem, but it currently doesn't work as planned.

**Comment by simonemainardi** [comment]
Alerts triggered and kept per interface:

![image](https://user-images.githubusercontent.com/3397663/67298200-35495100-f4eb-11e9-8c51-ca91d64e2c47.png)

For scripts which run system-wide and not on a per-interface basis (e.g., second.lua) then alerts are stored under the system interface page.
