### ISSUE TITLE
QUIC detection

### ISSUE THREAD

**Issue by shivanikhosa** [ntop/ntopng#2973]
Hi,
I've noticed that the nDPI QUIC dissector is not able to detect Google QUIC traffic anymore. I used to be able to recognise youtube traffic as QUIC and then look into the SNI in CHLO packet and re-classify it as youtube but QUIC detection for youtube isn't working anymore. 
Also when I tried to capture the Youtube traffic  in wireshark, I see that the wireshark decoder marks it as "Malformed packet" which suggests that there has been a change in the QUIC header.

**Comment by emanuele-f** [comment]
Please open an issue on https://github.com/ntop/nDPI
