### ISSUE TITLE
Disabled scripts are not easy to interpret

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2974]
Currently when a host/flow/... script is disabled in essence the GUI looks like
<img width="324" alt="Screenshot 2019-10-21 at 11 32 47" src="https://user-images.githubusercontent.com/4493366/67194186-e3bf9a00-f3f6-11e9-97ed-c0c4e90988f8.png">

Instead it is requested to change it to
<img width="101" alt="Screenshot 2019-10-21 at 11 34 51" src="https://user-images.githubusercontent.com/4493366/67194185-e3bf9a00-f3f6-11e9-8905-4c91dc515101.png">

and hide the script parameter thresholds.

Note that this ticket has a dependency on #2929

**Comment by emanuele-f** [comment]
This is implemented into the new user_scripts gui.
