### ISSUE TITLE
I want to ask about IPv6.

### ISSUE THREAD

**Issue by Ricky0619** [ntop/ntopng#2983]
HI：
I want to ask about IPv6.
 Because I need to throw Ntopng data into Splunk.
But I can't fully collect IPv6 from Splunk.
I have passed the nprobe APP, but I can only collect IPv4 completely.
I can't collect IPv6. What solution can I use?
Thank you.

**Comment by lucaderi** [comment]
Both ntopng and nProbe support IPv6. Can you please explain what you did exactly and what commands have you used?

**Comment by Ricky0619** [comment]
I use :
nprobe -T  "%IPV6_SRC_ADDR %IPV6_DST_ADDR %IPV6_SRC_MASK %IPV6_DST_MASK %IPV6_NEXT_HOP %EXPORTER_IPV6_ADDRESS %PROTOCOL %IN_BYTES %OUT_BYTES %FIRST_SWITCHED %LAST_SWITCHED %HTTP_SITE %HTTP_RET_CODE %IN_PKTS %OUT_PKTS %IP_PROTOCOL_VERSION %APPLICATION_ID %L7_PROTO_NAME %ICMP_TYPE " --tcp "192.168.1.0:3333" -b 2 -i ens224 --json-labels &


When the instruction is used, there is data in the first minute.
After the first minute, Splunk did not receive any more data.

**Comment by emanuele-f** [comment]
Can you provide the output of `nprobe --version`?

**Comment by Ricky0619** [comment]
This is the data collected by Splunk to Nprobe.
As the picture shows, after only one minute, there is no more data.
[https://i.imgur.com/9Hd4x1i.jpg](url)
[https://i.imgur.com/2H1SMBx.jpg](url)
[https://i.imgur.com/BM9Z8xG.jpg](url)

**Comment by simonemainardi** [comment]
all the links above point to an empty https://github.com/ntop/ntopng/issues/url
please check

**Comment by simonemainardi** [comment]
please, reopen with the requested information if necessary.
