### ISSUE TITLE
Slow data purge leads quickly exhausts memory

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2984]
In recent ntopng builds, (flow) memory purge is less aggressive than it used to be. While the number of active flows seems low in the GUI, inside ntopng they are not purged and thus RAM grows much more than in former ntopng builds. 

This issue needs to be addressed as on heavy loaded hosts it is a major problem in terms of memory usage.

**Comment by simonemainardi** [comment]
purging has now been reworked, significantly improved and made more aggressive in 955eed4 using a vector-based strategy
