### ISSUE TITLE
Race condition on Influx Data Export

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2985]
If Influx is too slow with data ingress, ntopng will end up filling up the disk with data exports, and then the process will stale with no way to exit from this state.
Example:

root@ntop:/data/ntopng/-1/ts_export# find .|wc -l
12919

This race condition can be addressed by stopping ntopng influx export if there are still many files to be imported.

**Comment by emanuele-f** [comment]
Please see #2998
