### ISSUE TITLE
Preferences caching not working as expected

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2986]
ntopng continues to access redis for preferences that should have been cached

1571815485.099036 [0 127.0.0.1:41350] "KEYS" "ntopng.prefs.iface_0.mud.recording.*"
1571815485.102520 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_0.udp_unidirectional" "disabled"
1571815485.102920 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_0.remote_to_remote" "disabled"
1571815485.103411 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_0.blacklisted" "disabled"
1571815485.103926 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_0.tcp_issues_packets" "disabled"
1571815485.104449 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_0.long_lived" "disabled"
1571815485.105091 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_0.ssl_old_version" "disabled"
1571815485.105881 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_0.elephant_flows" "disabled"
1571815485.106973 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_0.tcp_issues_generic" "disabled"
1571815485.109366 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_0.score" "disabled"
1571815485.110629 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_0.tcp_probing" "disabled"
1571815485.111776 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_0.malicious_signature" "disabled"
1571815485.112462 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_0.invalid_dns_query" "disabled"
1571815485.113385 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_0.ssl_certificate_mismatch" "disabled"
1571815485.114528 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_0.ssl_unsafe_ciphers" "disabled"
1571815485.115922 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_0.data_exfiltration" "disabled"
1571815485.116915 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_0.potentially_dangerous" "disabled"
1571815485.385414 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_1.device_protocol_not_allowed" "disabled"
1571815485.385944 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_1.external_alert" "disabled"
1571815485.386870 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_1.mud" "disabled"
1571815485.386943 [0 127.0.0.1:41350] "KEYS" "ntopng.prefs.iface_1.mud.recording.*"
1571815485.391708 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_1.my_custom_script" "disabled"
1571815485.392227 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_1.not_purged" "disabled"
1571815485.392588 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_1.remote_to_remote" "disabled"
1571815485.393116 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_1.web_mining" "disabled"
1571815485.393499 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_1.udp_unidirectional" "disabled"
1571815485.394152 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_1.blacklisted" "disabled"
1571815485.395427 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_1.tcp_issues_generic" "disabled"
1571815485.396286 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_1.tcp_issues_packets" "disabled"
1571815485.397932 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_1.elephant_flows" "disabled"
1571815485.399396 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_1.ssl_old_version" "disabled"
1571815485.400938 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_1.long_lived" "disabled"
1571815485.402198 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_1.potentially_dangerous" "disabled"
1571815485.403108 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_1.tcp_probing" "disabled"
1571815485.404744 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_1.data_exfiltration" "disabled"
1571815485.406094 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_1.invalid_dns_query" "disabled"
1571815485.410535 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_1.score" "disabled"
1571815485.411680 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_1.malicious_signature" "disabled"
1571815485.412664 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_1.ssl_certificate_mismatch" "disabled"
1571815485.413596 [0 127.0.0.1:41350] "HGET" "ntopng.prefs.user_scripts.conf.flow.ifid_1.ssl_unsafe_ciphers" "disabled"

**Comment by emanuele-f** [comment]
Preferences caching is currently implemented only for plain values (e.g. `GET key`), not for redis hashes (e.g. `HGET key`)

**Comment by emanuele-f** [comment]
The KEYS command for the MUD has been removed in 0c96c4915781a17642a642af173552c80ea34cd7

**Comment by emanuele-f** [comment]
user_scripts disabled status now use regular keys, so no additional redis access is performed (6fbc01b28e13b8e25ee843785a3631cb2f05e73d)
