### ISSUE TITLE
why are some hosts on the network not visible?

### ISSUE THREAD

**Issue by Krokx** [ntop/ntopng#299]
i.e. I have a VOIP box connected to the same router like my Raspberry (where ntopng is running), but there is no information about any traffic about it. 

The same happens with a mobile phone which is not visible as local host at all. I have other mobiles in the same network and they are visible, but one of them not.

Please advise why this could happen.

**Comment by lmangani** [comment]
Not enough details to handle. What protocols are you using for VoIP and are they encrypted? What are the expected results vs. actual ones?

**Comment by lucaderi** [comment]
@Krokx please do a tcpdump session and see if you can capture traffic from the phones that are not visible.

**Comment by lucaderi** [comment]
Closed for inactivity, even though I believe it was caused by invalid traffic traffic being monitored (e.g. just a subset of it)
