### ISSUE TITLE
Add schedule column

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2995]
In the screenshot below, please add a new column that reports when the specific row is scheduled for update (daily, hourly....)

<img width="1361" alt="Screenshot 2019-10-23 at 19 09 25" src="https://user-images.githubusercontent.com/4493366/67417303-baeefe80-f5c8-11e9-8d96-2952ffc94539.png">

**Comment by simonemainardi** [comment]
implemented

![image](https://user-images.githubusercontent.com/3397663/69657493-9a5c0d80-107a-11ea-95f1-68747c55780c.png)
