### ISSUE TITLE
Targus Dataspeed Error influxdb

### ISSUE THREAD

**Issue by ListenNjoy** [ntop/ntopng#2996]
I see this error in ntopng alerts and wondering how to fix, tried to search GitHub and google butt cant find anything about it.

Anybody else experiencing 

Version | 3.8.191021 -  

Error from systemctl status ntopng.service -l

[24/10/2019 10:15:14][Error][InfluxDB Export Failure][Influx DB][http://192.168.15.22:8086] There was an error while sending timeseries data to "http://192.168.15.22:8086"
                                        unable to parse 'iface:ndpi,ifid=5,protocol=Targus Dataspeed bytes=99164507 1571904259000000000': invalid field format

Error from alerts in Ntopng  (Host masked)

There was an error while sending timeseries data to 'http://192.168.15.22:8086': partial write: unable to parse 'host:ndpi,ifid=5,host=77.*.*,protocol=Targus Dataspeed bytes_sent=0,bytes_rcvd=204 1571906416000000000': invalid field format unable to parse 'host:ndpi,ifid=5,host=77.7.*.*,protocol=Targus Dataspeed bytes_sent=0,bytes_rcvd=208 1571906416000000000': invalid field format unable to parse 'host:ndpi,ifid=5,host=77.7.*.*,protocol=Targus Dataspeed bytes_sent=0,bytes_rcvd=164 1571906416000000000': invalid field format unable to parse 'host:ndpi,ifid=5,host=77.7.*.*,protocol=Targus Dataspeed bytes_sent=0,bytes_rcvd=164 1571906416000000000': invalid field format unable to parse 'host:ndpi,ifid=5,host=77.7.*.*,protocol=Targus Dataspeed bytes_sent=0,bytes_rcvd=120 1571906416000000000': invalid field format unable to parse 'host:ndpi,ifid=5,host=777.*.*,protocol=Targus Dataspeed bytes_sent=320,bytes_rcvd=416 1571906416000000000': invalid field format unable to parse 'host:ndpi,ifid=5,host=77.7.*.*,protocol=Targus Dataspeed bytes_sent=0,bytes_rcvd=160 1571906416000000000': invalid field format unable to parse 'host:ndpi,ifid=5,host=77.7.*.*,protocol=Targus Dataspeed bytes_sent=0,bytes_rcvd=212 1571906416000000000': invalid field format unable to parse

**Comment by emanuele-f** [comment]
This is already fixed in dev, 2d2566135d1f08b6bc0070ec3dd71a9121ff822a should be backported to stable

**Comment by ListenNjoy** [comment]
OK any timeline on the backport.?

**Comment by ListenNjoy** [comment]
3.8.191021 - Enterprise Edition is the version we use

**Comment by simonemainardi** [comment]
any news here?

**Comment by simonemainardi** [comment]
Fixed. New stable builds in progress. Please, hold on a couple of hours and update.
