### ISSUE TITLE
Long-Lived Flows Duration broken

### ISSUE THREAD

**Issue by helpdeskdan** [ntop/ntopng#3001]
ntopng Community Edition v.3.9.191023 stable from deb

On /lua/admin/prefs.lua?tab=alerts, "Long-Lived Flows Duration" instead of an on/off selector, I see:
<pre>
/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:684: attempt to compare nil with number
</pre>
Corresponding log:
<pre>
Oct 24 09:22:05 moloch_jr ntopng[15285]: [LuaEngine.cpp:11477] WARNING: Script failure [/usr/share/ntopng/scripts/lua/admin/prefs.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:684: attempt to compare nil with number]
</pre>
This appears to prevent me from changing any alerts.  I'm not sure what is calling truncate(x) with nil, please let me know if I can provide any more useful info.

Thank you for your time.

**Comment by simonemainardi** [comment]
Fixed in https://github.com/ntop/ntopng/commit/24c1c1bd73e67d9a1046e87855e9479abc33fc13
