### ISSUE TITLE
Alerts API Error

### ISSUE THREAD

**Issue by helpdeskdan** [ntop/ntopng#3002]
Alerts API returns error on "engaged."  "historical-flows" appears to work just fine. 

<pre>
/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:452: attempt to perform arithmetic on a nil value (local 'currentPage')
</pre>

**Comment by helpdeskdan** [comment]
Apologies, I did not provide any other info:
ntopng Community Edition v.3.9.191023 stable from deb

If there is curl output or anything else I can provide, let me know - thank you.

**Comment by simonemainardi** [comment]
please, show the exact url you are contacting.

**Comment by helpdeskdan** [comment]
This yields the error, thank you. 

<pre>
import requests

cookies = { 
    'user': 'admin',
    'password': 'admin',
}

params = ( 
    ('ifid', '1'),
    ('status', 'engaged'),
)

response = requests.get('https://192.0.2.1:3000/lua/rest/get/alert/data.lua', params=params, cookies=cookies, verify=False)
print (response.content)
</pre>

**Comment by simonemainardi** [comment]
fixed, thanks for reporting. don't forget to pass arguments

```
perPage,currentPage,sortCoumn,sortOrder
```

to paginate the results.
