### ISSUE TITLE
Flow scripts development not completed

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3003]
A few bugs
1. Most flows have no description (column Flow Callback)
2. "Latest Run" must be split in two columns: # of calls and Throughout 
3. Columns should be sortable, but if too difficult leave them like this
4. Preferences should be removed and and put in the configuration column

![Screen Shot 2019-10-24 at 22 09 19](https://user-images.githubusercontent.com/4493366/67521419-23161100-f6ab-11e9-99c3-4be4ec6a4994.png)

**Comment by lucaderi** [comment]
![Screenshot 2019-10-25 at 17 08 30](https://user-images.githubusercontent.com/4493366/67582461-1ac0e300-f74a-11e9-9bc5-4d27577fe02f.png)

Expert view is bugged

**Comment by emanuele-f** [comment]
Issue fixed
