### ISSUE TITLE
Almost useless charts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3004]
![Screen Shot 2019-10-25 at 08 53 03](https://user-images.githubusercontent.com/4493366/67549591-ed057b00-f704-11e9-9bf7-43ffd7c20800.png)

![Screen Shot 2019-10-25 at 08 58 37](https://user-images.githubusercontent.com/4493366/67549934-a9f7d780-f705-11e9-853a-6be9dcccd38d.png)

if you look at the above table
1. data cannot be sorted
2. you have individual script chart and timing
3. it is not possible to create a single chart with stacked the time of each individual script, but only individual timeseries

This report can he hardly used to troubleshoot issues and find problems overtime.

Please note that the issue depends on #3003

**Comment by lucaderi** [comment]
![Screenshot 2019-10-25 at 17 01 38](https://user-images.githubusercontent.com/4493366/67581952-265fda00-f749-11e9-9b47-1a585a2d7de1.png)
nil everywhere

**Comment by lucaderi** [comment]
![Screenshot 2019-10-25 at 17 02 40](https://user-images.githubusercontent.com/4493366/67582020-48f1f300-f749-11e9-8654-604678279256.png)
Invalid name "@67" and inconsistent throughout the page

**Comment by lucaderi** [comment]
Remove chart icon that is misleading and move it to "tool" page.As thus is a global script setting and not per host, it has to be reported as global. Furthermore it has to be a stacked chart to evaluate the overall script cost

**Comment by emanuele-f** [comment]
Here is a list of the fixes:

- Fix nil value in user scripts column 22742fa0d559c163ebb460523698ba6d8c7c7506
- Add total row in flow user scripts benchmarks 13a7b8ba6708b3a0aa8507f8d14f34001c98885a
- Add stacked top user scripts chart 63660b59f4e0462bfa8b1afce8ff91b11210d23e
- Fix network interface alias not used in alerts configuration 29e5b10e6f91751d1cd903294735f9554fbea233

**Comment by lucaderi** [comment]
<img width="493" alt="Screenshot 2019-10-29 at 23 11 57" src="https://user-images.githubusercontent.com/4493366/67813322-8c2dc800-faa1-11e9-9192-fc91aa5b428f.png">
The top is still useless when the top script is "other'

**Comment by emanuele-f** [comment]
After internal discussion, here is the new todo:

1. Save the total duration and number of calls for all the scripts
2. In the total row, add a link to the total chart
3. In a user script chart, show both the total and the current script values
4. In the flow user scripts, show the duration and number of calls with a percentage value relative to the total
5. Delete misleading "Last Calls/sec" in the total row
6. Remove "ms" from the user scripts chart label

**Comment by emanuele-f** [comment]
This has been fixed.
