### ISSUE TITLE
Create purge alert

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3005]
![Screen Shot 2019-10-25 at 09 03 04](https://user-images.githubusercontent.com/4493366/67550279-55a12780-f706-11e9-8b4e-989f80e33372.png)

Create script that generates an alert (with state) when there are more than x % (of the total entries) to be purged. The x value is a parameter set at runtime that can have a default value of 20.

**Comment by cardigliano** [comment]
Implemented
