### ISSUE TITLE
Improve remote hosts keys handling

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3008]
For remote hosts the preferences are continuously read from redis. Instead of checking them individually per host, we need to save them in one shot and reload them whenever preferences change. This to avoid continuous redis polling.

Please note that this ticket has dependencies (improvement) on #3007

**Comment by emanuele-f** [comment]
Double checked this and it does not happen as we already pre-load from redis all the local/remote hosts alert configuration before iterating them.
