### ISSUE TITLE
Ntopng 2.2.151130 - Professional Edition open handles Winx64

### ISSUE THREAD

**Issue by dfoster05** [ntop/ntopng#301]
Ntopng 2.2.151130 - Professional Edition

When I first run ntopng it'll have about 197,000 open handles. It adds about 8,600 handles an hour until it eventually locks up the Windows OS. 

OS Name:                   Microsoft Windows 8 Pro
OS Version:                6.2.9200 N/A Build 9200
Quad core i5 3.2Ghz
7GB memory

Dedicated desktop with a fresh OS installation for the ntopng application.

**Comment by lucaderi** [comment]
@dfoster05 How do you start it (command line parameters)? Honestly I have not tested on Win8, just on Win7 and server platforms (I am not sure if there's something special to do on Win8).

**Comment by dfoster05** [comment]
I was starting it from services.msc no arguments. I am starting it using /c and specifying local subnets now and the handle issue has went away. Looks like it only happens when I start it with no arguments. If I have the issue again I'll try a different OS and see if it behaves differently. It's working well the way I'm currently running it. Thanks!
