### ISSUE TITLE
Review the implementation of Active Host Contacts

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#3010]
Review the implementation of Active Host Contacts to make sure it handles the worst case and avoid the data structure grows indefinitely in case of scans for instance.

**Comment by emanuele-f** [comment]
Implement an host script with default value 500

**Comment by cardigliano** [comment]
This data structure cannot grow indefinitely actually:
1. it is limited by the size of the hosts table (it keeps a reference to the peer)
2. when there are no active flows, the peer is erased
