### ISSUE TITLE
Improve redis statistics

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3015]
Currently redis statistics are very poor. Add new metrics (as well charts) for number of request divided 
- operation families (e.g. GET, HGET, SET, HSET, other)
- content families (e.g. preferences, hosts....)

**Comment by lucaderi** [comment]
The issue is basically implemented, What is missing is a graph of redis calls. It would be desirable also to reformat the table in JSON with up/= icons

**Comment by emanuele-f** [comment]
Implemented in 74a0ce0da9f0d6110dbd0652ccad7952fb34c522 and 58d88d161ef9c6a5be8b10f4e2b727dce9dc552a . Further additions will be discussed separately.
