### ISSUE TITLE
Improve Internals Page 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3016]
The internals page (/lua/if_stats.lua?ifid=X&page=internals) is not in standard format with respect to the rest of ntopng as
- numeric cells to not have the usual arrow up/down/equal
- numeric cells are not periodically updated via ajax
- add a counter of the number of flow scripts executed

**Comment by simonemainardi** [comment]
requests implemented. all the dashboard is now ajax with cells that refresh and show the arrows and pagination support

![image](https://user-images.githubusercontent.com/3397663/68950870-5422c680-07bd-11ea-8e82-47b811fd51b4.png)
