### ISSUE TITLE
Missing Internals Dashboard

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3017]
When an ntopng instance has several interfaces, it is hard to understand what happens with all the interfaces.
It is necessary to create either
- a new page which compares all the interfaces
or
- (better) report everything in one page
or
- (also good) compare various interfaces with graphs

Bottom line: we need to compare data from various interfaces and as of today it is cumbersome.

**Comment by simonemainardi** [comment]
implemented:

![image](https://user-images.githubusercontent.com/3397663/68950807-2e95bd00-07bd-11ea-9cfc-a963d43f03ea.png)

![image](https://user-images.githubusercontent.com/3397663/68950822-37868e80-07bd-11ea-9b7e-504a07f060ad.png)
