### ISSUE TITLE
Implement filtering of "active local hosts"

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3026]
An active host is defined as a such if it has transmitted at least one packet. As network scanners contact hosts that are not really active in 
<img width="262" alt="Screenshot 2019-10-30 at 11 17 31" src="https://user-images.githubusercontent.com/4493366/67849540-047aa480-fb07-11e9-95c2-490ab15beb16.png">

it would be nice to add a new entry that reports
- active local hosts
- non active local hosts (i.e. those being scanned but that are down or not existing)

Adding a counter to the interface with the active counter, this could be also reported in the page footer.

**Comment by simonemainardi** [comment]
This can be obtained in the active hosts page by:

1. Selecting Local from the host filter
2. Selecting Now-way from the traffic filter

e.g., 

![image](https://user-images.githubusercontent.com/3397663/130778186-710ef88b-e708-4591-9899-7eff9f1b763e.png)
