### ISSUE TITLE
Error in alerts setting page

### ISSUE THREAD

**Issue by ListenNjoy** [ntop/ntopng#3028]
Get this in Runtime Preferences Alert in configuration page

HTTP/1.1 500 Internal server error Content-Type: text/html Connection: close  Script "/usr/share/ntopng/scripts/lua/admin/prefs.lua" returned an error: 

/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:684: attempt to compare nil with number

**Comment by emanuele-f** [comment]
What is the output of `ntopng --version`? Can you post a screenshot of the page?

**Comment by ListenNjoy** [comment]
v.3.9.191030    [Enterprise/Professional build]

Upgraded from Stable version

**Comment by ListenNjoy** [comment]
I tried to uninstall end remove ntopng from computer and install it again but the same error is in alert page.
/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:684: attempt to compare nil with number

**Comment by emanuele-f** [comment]
Can you post a screenshot of the broken web page?

**Comment by ListenNjoy** [comment]
![NtopAlertError](https://user-images.githubusercontent.com/43986547/68111991-aa0b8a80-fef0-11e9-86fe-9f2d853bbc7e.jpg)

**Comment by simonemainardi** [comment]
issue is fixed. new builds are in progress. please hold on a couple of hours and the update.

**Comment by ListenNjoy** [comment]
Perfect Tanks
