### ISSUE TITLE
nProbe not capturing flows in proxy mode

### ISSUE THREAD

**Issue by smerkal** [ntop/ntopng#303]
nProbe v.7.2.151202 (r4471)

IPFIX flow data from a Juniper router is not being captured by nProbe running in proxy mode.

.pcap file containing a sample of the flow data received from the router
[Uploading cflow.zip…]()

nbox@uncsnbox:~$ nprobe -i none -n none --zmq=tcp://*:5556 -3 2055
03/Dec/2015 19:24:49 [nprobe.c:3130] Valid nProbe license found
03/Dec/2015 19:24:49 [nprobe.c:4488] WARNING: The output interfaceId is set to 0: did you forget to use -Q perhaps ?
03/Dec/2015 19:24:49 [nprobe.c:4491] WARNING: The input interfaceId is set to 0: did you forget to use -u perhaps ?
03/Dec/2015 19:24:49 [nprobe.c:4552] Welcome to nProbe v.7.2.151202 ($Revision: 4471 $) for x86_64-unknown-linux-gnu with native PF_RING acceleration
03/Dec/2015 19:24:49 [nprobe.c:4562] Running on Ubuntu 14.04.2 LTS
03/Dec/2015 19:24:49 [nprobe.c:4573] [LICENSE] nProbe SystemId: FA623D157104A1D2
03/Dec/2015 19:24:49 [nprobe.c:4584] [LICENSE] nProbe License:  D96F0F134B77B12B046C75AE0CF3BD0D1480454057C265E036
03/Dec/2015 19:24:49 [nprobe.c:4587] [LICENSE] nProbe Edition:  Standard [without PF_RING Acceleration]
03/Dec/2015 19:24:49 [nprobe.c:4614] [LICENSE] Maintenance is available until Tue Nov 29 15:14:17 2016 [361 days left]
03/Dec/2015 19:24:49 [nprobe.c:6526] Welcome to nprobe v.7.2.151202 for x86_64-unknown-linux-gnu
03/Dec/2015 19:24:49 [plugin.c:1000] 0 plugin(s) enabled
03/Dec/2015 19:24:49 [nprobe.c:6203] Non IPv4/v6 traffic is discarded according to the template
03/Dec/2015 19:24:49 [util.c:287] GeoIP: loaded AS config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNum.dat
03/Dec/2015 19:24:49 [util.c:296] GeoIP: loaded AS IPv6 config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNumv6.dat
03/Dec/2015 19:24:49 [nprobe.c:5121] Using packet capture length 128
03/Dec/2015 19:24:49 [nprobe.c:6698] IPv6 traffic will NOT be exported/accounted by this probe
03/Dec/2015 19:24:49 [nprobe.c:6699] due to configuration options (e.g. use NetFlow v9)
03/Dec/2015 19:24:49 [nprobe.c:6827] Not capturing packet from interface (collector mode)
03/Dec/2015 19:24:49 [util.c:3840] Succesfully created ZMQ endpoint tcp://*:5556
03/Dec/2015 19:24:49 [collect.c:145] Flow collector listening on port 2055 (IPv4/v6)
03/Dec/2015 19:24:49 [nprobe.c:7035] nProbe started successfully
^C03/Dec/2015 19:25:29 [cache.c:1200] Redis Cache [0 total/0.0 get/sec][0 total/0.0 set/sec]
03/Dec/2015 19:25:29 [nprobe.c:386] Received shutdown request... [signal: 2]
03/Dec/2015 19:25:32 [cache.c:1200] Redis Cache [0 total/0.0 get/sec][0 total/0.0 set/sec]
03/Dec/2015 19:25:32 [nprobe.c:2457] Processed packets: 0 (max bucket search: 0)
03/Dec/2015 19:25:32 [nprobe.c:2440] Fragment queue length: 0
03/Dec/2015 19:25:32 [nprobe.c:2466] Flow export stats: [0 bytes/0 pkts][0 flows/0 pkts sent]
03/Dec/2015 19:25:32 [nprobe.c:2473] Flow collection: [collected pkts: 0][processed flows: 0]
03/Dec/2015 19:25:32 [nprobe.c:2476] Flow drop stats:   [0 bytes/0 pkts][0 flows]
03/Dec/2015 19:25:32 [nprobe.c:2481] Total flow stats:  [0 bytes/0 pkts][0 flows/0 pkts sent]

**Comment by simonemainardi** [comment]
it looks like your zmq endpoint is incomplete: try adding a star between `tcp://`and `:5556`:
```
nbox@uncsnbox:~$ nprobe -i none -n none --zmq=tcp://*:5556 -3 2055
```

However this is the ntopng issue tracker. Please consider using https://github.com/ntop/nProbe/issues for nProbe-related issues.

Please let us know.

**Comment by simonemainardi** [comment]
I'm closing this. If the answer above does not solve the problem, please open the issue here https://github.com/ntop/nProbe/issues and enclose the pcap (the link posted here is dead).

**Comment by smerkal** [comment]
I was instructed by Luca to submit this issue here. I will resubmit on nProbe then.

There was a typo in my command line submission, that was my mistake. However, the issue remains as described.

**Comment by lucaderi** [comment]
@smerkal Yes let's move the discussion to nprobe.
