### ISSUE TITLE
Double nDPI reload

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3032]
Enabling tracings such it is easy to check that  lists_utils.checkReloadLists()  has been called twice (double reload). This is not necessary

Tested with ntopng -i lo -i tcp://127.0.0.1:1234c -i syslog://127.0.0.1:9999  -i eth0 -i enp5s0 

Note that you need at least two (-i) interfaces to reproduce it

**Comment by lucaderi** [comment]
Additional bug: you see, to reload the same host twice


02/Nov/2019 19:56:47 [NetworkInterface.cpp:7499] nDPILoadHostnameCategory(0x7fa8dc4c6610) [datkl.nightmichael.top]
02/Nov/2019 19:56:47 [NetworkInterface.cpp:7499] nDPILoadHostnameCategory(0x7fa8dc83aab0) [datkl.nightmichael.top]
02/Nov/2019 19:56:47 [NetworkInterface.cpp:7499] nDPILoadHostnameCategory(0x7fa8dc4c6610) [datnentrieuvy.com]
02/Nov/2019 19:56:47 [NetworkInterface.cpp:7499] nDPILoadHostnameCategory(0x7fa8dc83aab0) [datnentrieuvy.com]
02/Nov/2019 19:56:47 [NetworkInterface.cpp:7499] nDPILoadHostnameCategory(0x7fa8dc4c6610) [dato.co.at]
02/Nov/2019 19:56:47 [NetworkInterface.cpp:7499] nDPILoadHostnameCategory(0x7fa8dc83aab0) [dato.co.at]
02/Nov/2019 19:56:47 [NetworkInterface.cpp:7499] nDPILoadHostnameCategory(0x7fa8dc4c6610) [datpapernl.com]
02/Nov/2019 19:56:47 [NetworkInterface.cpp:7499] nDPILoadHostnameCategory(0x7fa8dc83aab0) [datpapernl.com]
02/Nov/2019 19:56:47 [NetworkInterface.cpp:7499] nDPILoadHostnameCategory(0x7fa8dc4c6610) [datpq.com]
02/Nov/2019 19:56:47 [NetworkInterface.cpp:7499] nDPILoadHostnameCategory(0x7fa8dc83aab0) [datpq.com]

**Comment by emanuele-f** [comment]
This happens because of #3035 . Can be easily reproduced by adding a `os.execute("sleep 10")` in housekeeping.lua

**Comment by emanuele-f** [comment]
Fix in 01953cf76f779af8554c000fa64fc591928f2ec0 and 94643f1fe199040f9fd0d0c18dc95692206c8d03
