### ISSUE TITLE
nDPI reload crash

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3033]
Because of #3032 nDPI is reloaded twice. Unfortunately when many lists have to be loaded the second reload is triggered while the first reload is still in progress. Calling cleanShadownDPI() causes ntopng to crash.

Another bug is a race condition on Ntop::canSafelyReloadnDPI() that does not check if a reload is still ongoing.

So the bug is that a reload cannot be triggered before a previous one is completed. The algorithm used by list_utils's reloadListsNow() need to be changed to avoid nested reloads. This has to be prevented from C++ (and not from Lua) as C++ must guarantee integrity in all cases.

A workaround has been implemented to avoid crashes but a proper fix is necessary.

**Comment by emanuele-f** [comment]
Fix in 01953cf76f779af8554c000fa64fc591928f2ec0 and 94643f1fe199040f9fd0d0c18dc95692206c8d03
