### ISSUE TITLE
Slow HT Update on Raspberry

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3034]
03/Nov/2019 17:11:33 [NetworkInterface.cpp:2933] ERROR: Deadline exceeded [periodicHTStateUpdate][lo][expected: 17:11:16][off by: 17 secs]
03/Nov/2019 17:11:48 [NetworkInterface.cpp:2933] ERROR: Deadline exceeded [periodicHTStateUpdate][eth0][expected: 17:11:31][off by: 17 secs]

**Comment by simonemainardi** [comment]
Cannot reproduce in the lab. Please, give extra details (e.g., pi build and distro) to reproduce if necessary.
