### ISSUE TITLE
Enqueue Flow alerts from Lua

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#3038]
Flow alerts life cycle is a long journey in the current implementation:

- they are triggered from Lua, setting a status in the C flow data structure
- periodic activities use that status to enqueue the actual alert to Redis
- periodic Lua script dequeue alerts from Redis and insert them to the DB, through C code

This journey should be shortened by enqueueing alerts to Redis directly from Lua.

**Comment by emanuele-f** [comment]
This is also connected to #2944 . We should decouple sqlite from alert generation, for both flow and non-flow alerts.

**Comment by cardigliano** [comment]
Implemented with https://github.com/ntop/ntopng/commit/280213e14876804e7db293e7051fc475b8d72604 and  https://github.com/ntop/ntopng/commit/acdab024da8b9ec74e7a6a17509cdfed97b36197
