### ISSUE TITLE
Category Updates

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3041]
Category lists show a button update now which can be clicked several times. It just shows a green badge at the top of the page, but it is impossible to understand or see if the update process is running and/or completed

![image](https://user-images.githubusercontent.com/3397663/68144319-b49b4380-ff33-11e9-8339-4ad8f58c7d07.png)

It is requested to implement the same mechanism already implemented for the network discovery, that is, a blue status bar informing the user about the currently running update process. The same bar should always be present when the user visits or refreshes the page, until the update is complete

![image](https://user-images.githubusercontent.com/3397663/68144446-fb893900-ff33-11e9-9321-3979ddeed85b.png)

**Comment by gabryon99** [comment]
We'll be addressed once the notification daemon will be implemented
