### ISSUE TITLE
Check ntopng + nProbe VoIP monitoring

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3043]
Recent rework of TVL has affected the VoIP monitoring done with ntopng and nProbe. It is requested to re-check this functionality and make sure all the VoIP fields (e.g., MOS) are properly shown as in this blog post: https://www.ntop.org/nprobe/monitoring-voip-traffic-with-nprobe-and-ntopng/

**Comment by simonemainardi** [comment]
the issue seems not to be solved. At least no information (e.g., caller and called parties) are shown for SIP flows.

```
$ ./nprobe -i ../voip_test.pcap -T "%IPV4_SRC_ADDR %IPV4_DST_ADDR %IPV4_NEXT_HOP %INPUT_SNMP %OUTPUT_SNMP %IN_PKTS %IN_BYTES %FIRST_SWITCHED %LAST_SWITCHED %L4_SRC_PORT %L4_DST_PORT %TCP_FLAGS %PROTOCOL %L7_PROTO @SIP@ @RTP@" --redis localhost --zmq tcp://192.168.2.126:1234 --zmq-probe-mode
```

and ntopng shows nothing under SIP flows

**Comment by cardigliano** [comment]
SIP info seems to be displayed correctly with latest code. Fixed RTP MOS with https://github.com/ntop/ntopng/commit/6359bc9ab0e8e2f17bca609743361cb5a2bd8d8b
