### ISSUE TITLE
Data export issue nprobe-agent -> ntopng -> elasticsearch.

### ISSUE THREAD

**Issue by nobuyukitoyokawa** [ntop/ntopng#3045]
I have seen data export issue nprobe-agent -> ntopng -> elasticsearch.
ntopng surely received the data and showing in "flow" in its dashboard. however, these flow data seems not to be exported to elasticsearch.  ntopng is running with community mode, but even with first-10min Enterprise license, it is not happening.
I like to get some assistance with getting around the issue.

# ntopng --version
v.3.9.191104    [Enterprise/Professional build]
GIT rev:        dev:c4ad235bf81820149713e9d6a66e3555429cde74:20191104
Pro rev:        r2512
Built on:
System Id:      689AF6B376066B13
Platform:       x86_64
Edition:        Enterprise
License Type:   Time-Limited [Empty license file]
Validity:       Until Tue Nov  5 10:09:48 2019

**Comment by simonemainardi** [comment]
implemented
