### ISSUE TITLE
Optimize queues to avoid redis access

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3047]
ntopng could provide it's own (lockless?) queues in order to reduce the overall redis load and subsequent delay. This is important in particular for the alerts queue as explained in #3007 .

**Comment by cardigliano** [comment]
In the meanwhile, we should implement a rating mechanism to avoid too many RPUSH on the Redis queue when we have too many queued alerts.

**Comment by emanuele-f** [comment]
Queue rating implemented in af1dc8a05e373b7ac3bfd53d4f4e7b4f6579bfd7 for the three alerts queues: flow alerts, non-flow alerts, notifications

**Comment by emanuele-f** [comment]
Implemented in df0556cb875d614bc6949526c6037af7f1bfa8f9 and c19bda542507221491412675add342f96e6a1619
