### ISSUE TITLE
Application Protocol Overview

### ISSUE THREAD

**Issue by twistybin** [ntop/ntopng#3048]
Hi,
How can I set TLS.facebook to Facebook application and TLS.youtube to youtube application. Because TLS is category "Web". So It's not exactly to get statistical of users. 

Finally, How can I sort Top Application use by users ( example: Top 10,100 Users use facebook in 30days,60days)

Thanks,
![Screen Shot 2019-11-06 at 5 19 45 PM](https://user-images.githubusercontent.com/43060473/68289947-b0009780-00b9-11ea-98c5-f8cce3fb8ac5.png)
![Screen Shot 2019-11-06 at 5 20 34 PM](https://user-images.githubusercontent.com/43060473/68289991-c3136780-00b9-11ea-8ae2-61b0df26301f.png)

**Comment by emanuele-f** [comment]
What is the output of `ntopng --version`?

Regarding the categorization, by clicking on the flow "Info" it should be recognized as social network, isn't this the case for you?

![image](https://user-images.githubusercontent.com/5488003/68303629-22fb1580-009c-11ea-80e9-b95fc1ac5749.png)

You need nIndex (available in ntopng enterprise) in order to filter the top hosts given an L7 application, please check out https://www.ntop.org/guides/ntopng/historical_flows.html

**Comment by twistybin** [comment]
Hi emanuele-f,
I use this ntopng community, because It's the first time I use ntopng, so if help me get statistical of users and export data connect to Power BI, I will buy Ntopng enterprise.
So, Do I have to upgrade enterprise collect top Protocols,categories ?, 

In Community, It don't have Top Application,It only have historical Active flow ?
![Screen Shot 2019-11-07 at 9 33 34 AM](https://user-images.githubusercontent.com/43060473/68355499-116c4900-0142-11ea-9160-1516ac73baef.png)

thanks,
![Screen Shot 2019-11-07 at 9 01 52 AM](https://user-images.githubusercontent.com/43060473/68353863-66599080-013d-11ea-8c14-3c3540928198.png)

**Comment by emanuele-f** [comment]
You can already review the top applications/categories for an interface/host in the community

![2019-11-07_10-09](https://user-images.githubusercontent.com/5488003/68375199-52faf500-013e-11ea-970a-30653e5904ea.png)

By enabling the `-F nindex`, available in the enterprise, flow export you will have the ability to see the top applications in the past (but not the top categories). I suggest you to request a free trial to review the features and then choose. You can contact us from the following link: http://www.ntop.org/support/need-help-2/contact-us/

**Comment by mastersesin** [comment]
Thank you, emanuele-f
I just wrote email to request free trial ntopng enterprise.

I want to show historical like unifi controller.
example :
![Capture](https://user-images.githubusercontent.com/37859402/68460329-33e18d80-023a-11ea-8da8-8f87ae145eb0.PNG)

**Comment by emanuele-f** [comment]
Ok thank you. Of course you can use ntopng as a data source. If there is some api missing please let us know.
