### ISSUE TITLE
[b41f7c28b424a33a28803631518a052ced796063] Compilation Error

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#305]
src/NetworkInterface.cpp: In member function ‘bool NetworkInterface::packetProcessing(const timeval*, u_int64_t, ndpi_ethhdr*, u_int16_t, ndpi_iphdr*, ndpi_ipv6hdr*, u_int16_t, u_int16_t, const pcap_pkthdr*, const u_char*, int*, int*)’:
src/NetworkInterface.cpp:699:32: error: ‘struct ndpi_ipv6hdr’ has no member named ‘ip6_ctlun’
     l4_packet_len = ntohs(ip6->ip6_ctlun.ip6_un1.ip6_un1_plen);
                                ^
src/NetworkInterface.cpp:700:21: error: ‘struct ndpi_ipv6hdr’ has no member named ‘ip6_ctlun’
     l4_proto = ip6->ip6_ctlun.ip6_un1.ip6_un1_nxt;
                     ^
src/NetworkInterface.cpp:759:27: error: ‘struct ndpi_ipv6hdr’ has no member named ‘ip6_src’
     src_ip.set_ipv6(&ip6->ip6_src);
                           ^
src/NetworkInterface.cpp:760:27: error: ‘struct ndpi_ipv6hdr’ has no member named ‘ip6_dst’
     dst_ip.set_ipv6(&ip6->ip6_dst);
                           ^
src/NetworkInterface.cpp:834:36: error: invalid use of incomplete type ‘struct NetworkInterface::packetProcessing(const timeval*, u_int64_t, ndpi_ethhdr*, u_int16_t, ndpi_iphdr*, ndpi_ipv6hdr*, u_int16_t, u_int16_t, const pcap_pkthdr*, const u_char*, int*, int*)::ndpi_dns_packet_header’
  u_int16_t dns_flags = ntohs(header->flags);
                                    ^
src/NetworkInterface.cpp:833:9: note: forward declaration of ‘struct NetworkInterface::packetProcessing(const timeval*, u_int64_t, ndpi_ethhdr*, u_int16_t, ndpi_iphdr*, ndpi_ipv6hdr*, u_int16_t, u_int16_t, const pcap_pkthdr*, const u_char*, int*, int*)::ndpi_dns_packet_header’
  struct ndpi_dns_packet_header *header = (struct ndpi_dns_packet_header*)payload;
         ^
src/NetworkInterface.cpp: In member function ‘bool NetworkInterface::packet_dissector(const pcap_pkthdr*, const u_char*, int*, int*)’:
src/NetworkInterface.cpp:1311:22: error: ‘struct ndpi_ipv6hdr’ has no member named ‘ip6_ctlun’
       if((ntohl(ip6->ip6_ctlun.ip6_un1.ip6_un1_flow) & 0xF0000000) != 0x60000000) {
                      ^
src/NetworkInterface.cpp:1317:27: error: ‘struct ndpi_ipv6hdr’ has no member named ‘ip6_ctlun’
  u_int8_t l4_proto = ip6->ip6_ctlun.ip6_un1.ip6_un1_nxt;
                           ^
Makefile:129: recipe for target 'src/NetworkInterface.o' failed
make: *** [src/NetworkInterface.o] Error 1

[Compilation Error.txt](https://github.com/ntop/ntopng/files/52784/Compilation.Error.txt)

**Comment by lucaderi** [comment]
please refresh nDPI and it will work.

**Comment by jean-christophe-manciot** [comment]
After refreshing nDPI, I have another compilation error for ntopng:

g++ -g -Wall -I/home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng -I/home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng/include -I/usr/local/include -D_FILE_OFFSET_BITS=64 -I/usr/include/hiredis  -I/usr/include/hiredis -I/home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng/third-party/mongoose -I/home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng/third-party/json-c -I/usr/local/include/libndpi-1.7.1/libndpi  -I/home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng/third-party/LuaJIT-2.0.3/src  -I/home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng/third-party/zeromq-4.1.3/include -I/usr/include/mariadb  -I/home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng -I/home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng/include -I/usr/local/include -I/home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng/third-party/http-client-c/src/  -DDATA_DIR='"/usr/local/share"' -I/home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng/third-party/libgeohash -I/home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng/third-party/patricia   -c src/GenericHashEntry.cpp -o src/GenericHashEntry.o
In file included from /home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng/include/ntop_includes.h:99:0,
                 from src/GenericHashEntry.cpp:22:
/usr/local/include/libndpi-1.7.1/libndpi/ndpi_main.h:28:27: fatal error: ndpi_includes.h: No such file or directory
compilation terminated.
Makefile:129: recipe for target 'src/GenericHashEntry.o' failed
make: *** [src/GenericHashEntry.o] Error 1

**Comment by lucaderi** [comment]
See https://github.com/ntop/ntopng/blob/dev/.travis.yml for directions

**Comment by jean-christophe-manciot** [comment]
I had to install subversion & autogen (isn't configure's job to detect missing dependencies?) from the list of dependencies, but that did not remove the error:

In file included from /home/actionmystique/Program-Files/Ubuntu/Ntop/ntopng/include/ntop_includes.h:99:0,
                 from src/GenericHashEntry.cpp:22:
/usr/local/include/libndpi-1.7.1/libndpi/ndpi_main.h:28:27: fatal error: ndpi_includes.h: No such file or directory

**Comment by lucaderi** [comment]
We do not support installed nDPI compilation but the compilation steps in the travis file. Please use the same steps.
