### ISSUE TITLE
Unknown message in log

### ISSUE THREAD

**Issue by ListenNjoy** [ntop/ntopng#3050]
When i run journalctl -u ntopng.service -n30 in ntopng centos7 i only see this message repeated

ntopng[110923]: string both

This message is hammering the syslog with over 1000  of these messages every minute.
Any idea what this could be.?

Ntopn Vesrion
v.3.8.191104    [Enterprise/Professional build]
GIT rev:        3.8-stable:759e405b0122bad2ac45a28043f4e302f7032200:20191104
Pro rev:        r2191

**Comment by emanuele-f** [comment]
Fixed in 2c6a3fe3421a50169b6cbb6c5730ee92ed9fddb6 . A new package will be available in one hour. Thank you for reporting!
