### ISSUE TITLE
Inconsistent charts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3052]
![Screenshot 2019-11-12 at 16 03 49](https://user-images.githubusercontent.com/4493366/68682965-47f0fc00-0566-11ea-9cd6-cc1f0c7e2410.png)
![Screenshot 2019-11-12 at 16 03 20](https://user-images.githubusercontent.com/4493366/68682969-47f0fc00-0566-11ea-931e-8221016ba6bb.png)

**Comment by simonemainardi** [comment]
Internal charts have been reworked.

Duration of the lua calls (as shown in the first image) has now been put under the corresponding periodic activity, which is ht_state_update.lua for current lua calls

![image](https://user-images.githubusercontent.com/3397663/69654263-c5436300-1074-11ea-9956-d015f608b668.png)

The number of lua calls has been extended as well not only to count the number of calls, but also to count the number of:
- deferred lua calls: calls skipped which will be retried
- missed lua calls: calls skipped which won't be retried as the flow has become idle

Chart is accessible from the same page:

![image](https://user-images.githubusercontent.com/3397663/69654396-0471b400-1075-11ea-92f3-26c7e4962ffc.png)
