### ISSUE TITLE
ntopng restarting randomly

### ISSUE THREAD

**Issue by juesor** [ntop/ntopng#3053]
Output of ntopng --version

# ntopng --version
v.3.9.191112    [Enterprise/Professional build]
GIT rev:        dev:c9137bbbcff4d95becc19f03ca677820deb52ea6:20191112
Pro rev:        r2523
Built on:
System Id:      68978C03B20B2B27
Platform:       x86_64
Edition:        Enterprise
License Type:   Permanent
Maintenance:    Until Thu May 14 17:34:11 2020 [184 days left]
License:        pxRtAT/D/J33y9yhso6y8Imh5Tm3SjM3CDXOiR3GoD0kAi1s2JEpghnwK84xPqBTyP7Ab
                g1XUQcVVqeDBO4nHj5i9miIliKuvcc9/IeCizAVIFyu8mf4GRqOQONFlE0vtfL1g7bW0e
                KzwmL9Ni0K8g3RkkFcv/uqgN2C9REGDiT7vj4TNsTs2v9ZZPyFdSb2zKOScmyoUnAMUH5
                K+5L29IHzhBakj7jkV1u1IQdn6op0VppF8VAIXQGDu+naDmkOJlm7rKur+0azMwwZKyha
                hwmj5lvyZj4aFwDLsaVkyW6gkpgkVqLC9HxnBIUihgso+QWEqG2qlkptxXfsEmqOkA==
License Hash:   3E3C3108A07976CE687F9F780E998C8D1589492051A23A34E5

Output of udo journalctl -u ntopng

https://pastebin.com/WdXHF56M

I believe the issue is the following.

Nov 12 11:43:46 ntop ntopng[101797]: ntopng: third_party/src/ndpi_patricia.c:557: ndpi_patricia_search_best2: Assertion `prefix->bitlen <= patricia->maxbits' failed.
Nov 12 11:43:46 ntop systemd[1]: ntopng.service: main process exited, code=killed, status=6/ABRT
Nov 12 11:43:46 ntop systemd[1]: Unit ntopng.service entered failed state.
Nov 12 11:43:46 ntop systemd[1]: ntopng.service failed.
Nov 12 11:43:51 ntop systemd[1]: ntopng.service holdoff time over, scheduling restart.
Nov 12 11:43:51 ntop systemd[1]: Stopped ntopng high-speed web-based traffic monitoring and analysis tool.

**Comment by emanuele-f** [comment]
Can you extract a stack trace as explained in https://github.com/ntop/ntopng/blob/dev/doc/README.crash ? Are there any particular conditions to trigger the crash?

**Comment by juesor** [comment]
On the latest version of ntopng the restarting has cleared up.
