### ISSUE TITLE
Top talkers data

### ISSUE THREAD

**Issue by Eugene-Prokhorenko** [ntop/ntopng#3057]
For about a month data for Actual Traffic in Top takers don't changes and graphs are horizontal lines. The same after deleted persistent data.

**Comment by emanuele-f** [comment]
Can you post a screenshot of the problem? What is the output of ntopng --version?

**Comment by Eugene-Prokhorenko** [comment]
ubuntu@cacti:~$ ntopng --version
v.3.9.191114    [Enterprise/Professional build]
GIT rev:        dev:52e081ac1cac5a9a28ee04ea114d2f39eccacaee:20191114
Pro rev:        r2528
Built on:       Ubuntu 18.04.3 LTS
System Id:      50DF0C7600050812
Platform:       x86_64
Edition:        Enterprise
License Type:   Permanent
Maintenance:    Until Mon Sep 21 18:09:28 2020 [311 days left]
License:        ZeIQjc3cM90wOKEwUWvLfJ1eJMWocfQZZKb2x9+4bcxb7S4x0fGnOeqruvJSQLxMFOvtk
                RUoVy03Njczh5Z73rXUH+3HHHWoekMy3/QJAsFW7oI6onp0NN8SP2AeQ/v5a/0s0553dd
                Ix+O0bXDgwWSpjLicAlG/MYtjUB59TAkIcpc2NGeavk8Bs5dJpcfKanzhzWLhzSceDa1C
                abbqGa29+gFcrtpg+OTDCVZH7qXoDDLmCKDGsxNEmL7a/mZf2yVzUF8jNTshs+LMTt6pB
                0wFYhNNohVBv4ifplZJ5PPi8mje7YYqDtA6iKjAW8QB+gk7Bgd2L+RLPTnrN+XgHQg==
License Hash:   72F5B27FC2CD572622977C6D5480ACA11600697368E1DD9D7A
![ntopng](https://user-images.githubusercontent.com/33592455/68929081-faae9d80-07a4-11ea-9df0-17d9dbf6556d.png)

**Comment by Eugene-Prokhorenko** [comment]
Hope this will help

**Comment by simonemainardi** [comment]
are the following checkboxes ticked on the interface?

![image](https://user-images.githubusercontent.com/3397663/68954596-a0253980-07c4-11ea-83f4-9209dce178fb.png)

also check from the preferences if timeseries are enabled:

![image](https://user-images.githubusercontent.com/3397663/68954691-cf3bab00-07c4-11ea-9d1a-8986756bb508.png)

**Comment by Eugene-Prokhorenko** [comment]
Yes, they  are ticked.
Some Timeseries were enabled.
I tried to move to influxdb, but I got: can't connect to influxdb.

**Comment by Eugene-Prokhorenko** [comment]
Looks like all local hosts are lost. All hosts accounting as remote.

**Comment by emanuele-f** [comment]
The dashboard shows the local hosts under "Top local talkers". If some hosts are reported as remote, you should probably adjust the `--local-networks`/`-m` option into the ntopng configutation file `/etc/ntopng/ntopng.conf`

**Comment by Eugene-Prokhorenko** [comment]
I had 2 -m options (v4 & v6). It worked before, but now I merged in one.  Local are ok, but traffic is still constant.
So I decided to delete interface data. And now graphs and top local talkers are ok.

**Comment by Eugene-Prokhorenko** [comment]
18/Nov/2019 19:29:50 [5min.lua:27] [ts_5min_dump_utils.lua:461] ERROR: [tcp://127.0.0.1:5556 ]Cannot complete local hosts timeseries dump. Disk slow or too many local hosts?
18/Nov/2019 19:27:52 [LuaEngine.cpp:10388] [tcp://127.0.0.1:5556] ERROR: Cannot complete top talkers generation in 1 minute. Is there a huge number of hosts in the system?
18/Nov/2019 19:25:53 [LuaEngine.cpp:10388] [tcp://127.0.0.1:5556] ERROR: Cannot complete top talkers generation in 1 minute. Is there a huge number of hosts in the system?

And then no top talker update again.

**Comment by emanuele-f** [comment]
What is the number of local hosts you have in ntopng? You may want to switch from RRD to InfluxDB on a big network or disable some timeseries from the ntopng preferences. Please check out https://www.ntop.org/ntopng/ntopng-and-time-series-from-rrd-to-influxdb-new-charts-with-time-shift and https://www.ntop.org/ntopng/ntopng-disk-requirements-for-timeseries-and-flows/

**Comment by Eugene-Prokhorenko** [comment]
6000 local hosts, but 300.000 flows at the moment. Attack?

**Comment by emanuele-f** [comment]
I suggest you to switch to InfluxDB as you have many local hosts. Regarding the flows number, please check the alerts page for details on the active flows. Please note that if the footer badge is shown as red you will need to tweak the following options:

```
[--max-num-hosts|-x] <num>          | Max number of active hosts
[--max-num-flows|-X] <num>          | Max number of active flows
```

If the original issue is now solved please close this thread.

**Comment by Eugene-Prokhorenko** [comment]
I moved to InFluxDB. It works for 300000  flows and 8000 red badges (unknown malware). So I'm closing case.
