### ISSUE TITLE
How to get more information an Application being seen under network traffic?

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#3062]
Hi all

Trying to get more information on the "WhatAppCall" application traffic apparently being seen by the eth0 interface of our ntopng instance.

![image](https://user-images.githubusercontent.com/48565067/69062608-2e7a0500-09e9-11ea-855c-04de7a87aa52.png)

How do I go about verifying this traffic, or at least getting some more information on it?

**Comment by emanuele-f** [comment]
For the past data analysis you can look at the ntopng report https://www.ntop.org/guides/ntopng/web_gui/report.html . For more detailed data you will need to enable flow export either via MySQL or nIndex, please check out https://www.ntop.org/guides/ntopng/historical_flows.html and http://www.ntop.org/ntopng/exploring-historical-data-using-ntopng/

**Comment by StewAlexander-com** [comment]
Thanks!
