### ISSUE TITLE
Unable to decode JSON data for network discovery

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#3063]
Getting this error:

![image](https://user-images.githubusercontent.com/48565067/69064617-74849800-09ec-11ea-88de-1c4e4ebe4287.png)

Is this a permissions issue?
```
support@ntopng:~$ ntopng --version
v.3.9.191118    [Enterprise/Professional build]
GIT rev:        dev:c9b538a199c92e3c082b3732d63b9e1104b1f6f9:20191118
Pro rev:        r2539
Built on:       Ubuntu 18.04.3 LTS
System Id:      6B4891C10C0207EE
Platform:       x86_64
Edition:        Enterprise
License Type:   Permanent
Maintenance:    Until Tue Mar 17 17:05:22 2020 [120 days left]
License Hash:   [...]
support@ntopng:~$
```

**Comment by emanuele-f** [comment]
Can you please post the output of `redis-cli get ntopng.cache.ifid_1.device_discovery` where `1` is the interface id of your network interface? You can check the interface ID from the network interface page into ntopng. Please note that the above output will contain sensitive data, you may want to send it directly at faranda@ntop.org .

**Comment by StewAlexander-com** [comment]
So my network interface is eth0

Then the command I enter would be this?

redis-cli get ntopng.cache.ifid_0.device_discovery

**Comment by emanuele-f** [comment]
You need to verify this from the gui:

![2019-11-18_17-55](https://user-images.githubusercontent.com/5488003/69072931-55a1f800-0a24-11ea-9abb-f68550929069.png)

**Comment by StewAlexander-com** [comment]
Yes, in this case it is 0 for us, thank you for providing that detail.

**Comment by StewAlexander-com** [comment]
Yes I see a great deal of information when issuing the command, however it contains MAC and IP addresses I cannot give out, is there a way to redact this from the output?

**Comment by emanuele-f** [comment]
The following information may be enough:
- Total length in characters of the data
- First and last part of the json, is it a valid json?
- Approximately how many devices do you have in your network (according to ntopng)?

**Comment by StewAlexander-com** [comment]
1.
```
support@ntopng:~/redis-output-ntop$ wc -m device_discovery.txt
244526 device_discovery.txt
````
2. 
first: ``` {"ghost_found":true,"devices":[{"device_info":"","information":[],"ghost":true,"```
last: ```"status":{"message":"","code":"OK"},"discovery_timestamp":1574088784}```

3. How do I find this out?
Is this it?
![image](https://user-images.githubusercontent.com/48565067/69074370-39d72b80-09fd-11ea-81d1-47527baf6a16.png)

**Comment by StewAlexander-com** [comment]
Under the hosts section:
![image](https://user-images.githubusercontent.com/48565067/69074454-68550680-09fd-11ea-816a-84354cbdd8f0.png)

**Comment by StewAlexander-com** [comment]
We have a variable number of end clients on our network as we are a school with an open wireless policy for students

**Comment by emanuele-f** [comment]
Yes, 1705 active devices. The problem is that too much data has been serialized and we deserialize up to 131052 characters. We must limit the number of serialized elements and support more devices.

**Comment by StewAlexander-com** [comment]
Ah, so is there anything we can do?

**Comment by simonemainardi** [comment]
thanks for reporting. issue is fixed. new packages will be available in one hour. now the system will handle up to 8192 discovered devices, then it will show you a warning but no JSON decode issue should occur.

**Comment by StewAlexander-com** [comment]
Thank you @simonemainardi, I'll update ntopng tomorrow morning our time (GMT-5 / EST) and report any issues
