### ISSUE TITLE
How can I Custom hostname, export data

### ISSUE THREAD

**Issue by twistybin** [ntop/ntopng#3064]
Hi,
I just upgraded ntopng to enterprise, I have some questions to work with ntopng.

How can I collect top 100 people use the most time or traffic of facebook, google,instagram ?
I sort and filter in this image, is It Right in the picture ?
![Capture](https://user-images.githubusercontent.com/43060473/69112098-15895680-0ab2-11ea-9349-8d7457d94f07.PNG)
-------------------------------------------
How can I change the name Hostname ?, It show IP in the first picture, I want to show custom name.
![Capture](https://user-images.githubusercontent.com/43060473/69112743-a6acfd00-0ab3-11ea-8778-2b3e1ff63f0e.PNG)  -> It hide Custom Name.
--------------------------------------------
Why is different traffic between graph and Profile name ?
Profile name about 14GB traffic, but Graph on interface is 4.61GB ?
![Capture](https://user-images.githubusercontent.com/43060473/69124119-a3c30400-0ad5-11ea-9a38-624985c9f39b.PNG)
![Capture](https://user-images.githubusercontent.com/43060473/69124145-b76e6a80-0ad5-11ea-92f7-a0bbd5e317da.PNG)
------------------------------------------
Finally, I want to export data  Top Users use facebook, Socialnetworks, website, TLS contains of column Custom name, IP, Firstseen,lastseen,traffic. How can I do it ?

Thank you,

**Comment by simonemainardi** [comment]
> How can I collect top 100 people use the most time or traffic of facebook, google,instagram ?
I sort and filter in this image, is It Right in the picture ?

yes, that gives you the top-conversation. If you want the top clients and top servers, you can open the dropdown menu and chose "top clients" and "top servers"

> How can I change the name Hostname ?, It show IP in the first picture, I want to show custom name.

We only show ip addresses and not custom names as you are looking at historical data. Historically, an ip address could have had a different name from what it has now (possibly because it was used by someone else) so we decided not to show the names when browsing historical flows as they can be misleading.

> How can I change the name Hostname ?

Click on the wheel next to the name you want to change.

> Why is different traffic between graph and Profile name ? Profile name about 14GB traffic, but Graph on interface is 4.61GB ?

The traffic shown next to the profile name is the overall total profile traffic whereas the total you see in the interface page it the total in the selected time period.

> Finally, I want to export data Top Users use facebook, Socialnetworks, website, TLS contains of column Custom name, IP, Firstseen,lastseen,traffic. How can I do it ?

There's a download button at the top-right corner of the charts:

![image](https://user-images.githubusercontent.com/3397663/69130932-b3305600-0ab1-11ea-9a2f-7ae4123a807e.png)

**Comment by twistybin** [comment]
> > How can I collect top 100 people use the most time or traffic of facebook, google,instagram ?
> > I sort and filter in this image, is It Right in the picture ?
> 
> yes, that gives you the top-conversation. If you want the top clients and top servers, you can open the dropdown menu and chose "top clients" and "top servers"
> 
> > How can I change the name Hostname ?, It show IP in the first picture, I want to show custom name.
> 
> We only show ip addresses and not custom names as you are looking at historical data. Historically, an ip address could have had a different name from what it has now (possibly because it was used by someone else) so we decided not to show the names when browsing historical flows as they can be misleading.
> 
> > How can I change the name Hostname ?
> 
> Click on the wheel next to the name you want to change.
> 
> > Why is different traffic between graph and Profile name ? Profile name about 14GB traffic, but Graph on interface is 4.61GB ?
> 
> The traffic shown next to the profile name is the overall total profile traffic whereas the total you see in the interface page it the total in the selected time period.
> 
> > Finally, I want to export data Top Users use facebook, Socialnetworks, website, TLS contains of column Custom name, IP, Firstseen,lastseen,traffic. How can I do it ?
> 
> There's a download button at the top-right corner of the charts:
> 
> ![image](https://user-images.githubusercontent.com/3397663/69130932-b3305600-0ab1-11ea-9a2f-7ae4123a807e.png)

Hi, I just changed Host Alias, but in report still show Hostname is IP, not Host alias.

**Comment by simonemainardi** [comment]
historical data is always shown as IP

**Comment by twistybin** [comment]
> historical data is always shown as IP

![Capture](https://user-images.githubusercontent.com/43060473/69202373-0cf95480-0b74-11ea-8c6c-37ff311468e5.PNG)

I need to edit custom name this here, I saw some pictures on git, It can edit custom name, but with me It hide.

And I check historical of my host, It did not show traffic yesterday, It only show traffic today, so Did I lost data from host ???
![Capture](https://user-images.githubusercontent.com/43060473/69202569-a4f73e00-0b74-11ea-9b1f-8e71948258a7.PNG)

**Comment by simonemainardi** [comment]
> I need to edit custom name this here, I saw some pictures on git, It can edit custom name, but with me It hide.

click the cog next to the name, right before the Local green badge

> And I check historical of my host, It did not show traffic yesterday, It only show traffic today, so Did I lost data from host ???

It seems you have a DHCP host, are you sure your IP didn't change?

**Comment by twistybin** [comment]
> > I need to edit custom name this here, I saw some pictures on git, It can edit custom name, but with me It hide.
> 
> click the cog next to the name, right before the Local green badge
> 
> > And I check historical of my host, It did not show traffic yesterday, It only show traffic today, so Did I lost data from host ???
> 
> It seems you have a DHCP host, are you sure your IP didn't change?
Yes, IP didn't change.
Today, I change to use database mysql(4 tables : aggrflowsv4,aggrflowsv6,flowsv4,flowsv6), I think it exactly traffic than nindex.
How can I see top clients used by Application ?, ( It look like contains columns: IP, Total Duration time, Total Sent/Receive Bytes).
 I click 'Historical Data Explorer', and I cannot search how to exactly right top Client use application.

**Comment by twistybin** [comment]
Hi,
what is different betweeen table 'flowsv4' and table 'aggrlowsv4' ?
![Capture](https://user-images.githubusercontent.com/43060473/69327864-cfceb880-0c80-11ea-96e8-93c495770cfe.PNG)

I need to export mysql to report, so I don't know what is exactly table I need to export data.
