### ISSUE TITLE
JSON errors under the SNMP nmenu

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#3067]
Seeing the following JSON errors under the SNMP menu option:

![image](https://user-images.githubusercontent.com/48565067/69156436-664c7f80-0ab1-11ea-9db6-6639c47e9b6b.png)

```
support@ntopng:~$ ntopng --version
v.3.9.191119    [Enterprise/Professional build]
GIT rev:        dev:9d13065280f821a2a6070aadd587260940ee5470:20191119
Pro rev:        r2545
Built on:       Ubuntu 18.04.3 LTS
System Id:      6B4891C10C0207EE
Platform:       x86_64
Edition:        Enterprise
License Type:   Permanent
Maintenance:    Until Tue Mar 17 17:05:22 2020 [119 days left]
License Hash:  
support@ntopng:~$
```

**Comment by StewAlexander-com** [comment]
![image](https://user-images.githubusercontent.com/48565067/69156770-ef63b680-0ab1-11ea-9b6c-8ce67c9b1812.png)

**Comment by simonemainardi** [comment]
fixed. thanks for reporting. new packages will be available in a couple of hours.

**Comment by StewAlexander-com** [comment]
Thank you @simonemainardi
