### ISSUE TITLE
listen only ipv6

### ISSUE THREAD

**Issue by panaceya** [ntop/ntopng#307]
Hello! 

I have 10.2-RELEASE, with installed from git ntopng, and runned as
```sh
/usr/local/bin/ntopng --http-port 3000 --pid /var/run/ntopng.pid 
```
Branches used: last **dev** and last **2.2-stable**

Problem: After start ntop listen only on ipv6, ipv4 ignored:

```sh
# sockstat -64 -p 3000
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS      
nobody   ntopng     9261  17 tcp6   *:3000                *:*

```
 
startup log:

```sh
07/Dec/2015 17:12:20 [Ntop.cpp:935] Setting local networks to 127.0.0.0/8
07/Dec/2015 17:12:20 [Redis.cpp:106] Successfully connected to redis 127.0.0.1:6379@0
07/Dec/2015 17:12:20 [PcapInterface.cpp:86] Reading packets from interface xn0...
07/Dec/2015 17:12:20 [Ntop.cpp:1154] Registered interface xn0 [id: 0]
07/Dec/2015 17:12:20 [PcapInterface.cpp:86] Reading packets from interface xn1...
07/Dec/2015 17:12:20 [Ntop.cpp:1154] Registered interface xn1 [id: 1]
07/Dec/2015 17:12:20 [PcapInterface.cpp:86] Reading packets from interface lo0...
07/Dec/2015 17:12:20 [Ntop.cpp:1154] Registered interface lo0 [id: 2]
07/Dec/2015 17:12:20 [Ntop.cpp:1167] Registered interface view xn0 [id: 0]
07/Dec/2015 17:12:20 [Ntop.cpp:1167] Registered interface view xn1 [id: 1]
07/Dec/2015 17:12:20 [Ntop.cpp:1167] Registered interface view lo0 [id: 2]
07/Dec/2015 17:12:20 [Utils.cpp:304] User changed to nobody
07/Dec/2015 17:12:20 [main.cpp:246] ERROR: Unable to store PID in file /var/run/ntopng.pid
07/Dec/2015 17:12:20 [HTTPserver.cpp:458] HTTPS Disabled: missing SSL certificate /usr/local/share/ntopng/httpdocs/ssl/ntopng-cert.pem
07/Dec/2015 17:12:20 [HTTPserver.cpp:460] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
07/Dec/2015 17:12:20 [HTTPserver.cpp:503] Web server dirs [/usr/local/share/ntopng/httpdocs][/usr/local/share/ntopng/scripts]
07/Dec/2015 17:12:20 [HTTPserver.cpp:506] HTTP server listening on port 3000
07/Dec/2015 17:12:20 [main.cpp:299] Working directory: /var/tmp/ntopng
07/Dec/2015 17:12:20 [main.cpp:301] Scripts/HTML pages directory: /usr/local/share/ntopng
07/Dec/2015 17:12:20 [Ntop.cpp:261] Welcome to ntopng amd64 v.2.3.151207 - (C) 1998-15 ntop.org
07/Dec/2015 17:12:20 [PeriodicActivities.cpp:53] Started periodic activities loop...
07/Dec/2015 17:12:20 [RuntimePrefs.cpp:32] Dumping alerts into syslog
07/Dec/2015 17:12:20 [Ntop.cpp:548] Adding ::1/128 as IPv6 local network for lo0
07/Dec/2015 17:12:20 [Ntop.cpp:548] Adding fe80::1/64 as IPv6 local network for lo0
07/Dec/2015 17:12:20 [Ntop.cpp:518] Adding 127.0.0.0/8 as IPv4 local network for lo0
07/Dec/2015 17:12:20 [Ntop.cpp:518] Adding 176.107.128.8/29 as IPv4 local network for xn0
07/Dec/2015 17:12:20 [Ntop.cpp:518] Adding 10.255.224.0/20 as IPv4 local network for xn1
07/Dec/2015 17:12:20 [NetworkInterface.cpp:1425] Started packet polling on interface xn0 [id: 0]...
07/Dec/2015 17:12:20 [NetworkInterface.cpp:1425] Started packet polling on interface xn1 [id: 1]...
07/Dec/2015 17:12:20 [NetworkInterface.cpp:1425] Started packet polling on interface lo0 [id: 2]...
```

**Comment by lucaderi** [comment]
I do not have Ubuntu 10 to test with (note we build packages for 12.04 and up) but on my systems it works as designed

# netstat -na|grep 3000
tcp46      0      0  *.3000       

Please check if your v4/v6 network configuration is in good shape, or move to a platform we can help. Shall you identify the source of the problem, please send us a merge request.

**Comment by panaceya** [comment]
The problem occurs only in ntop.
For example, in named no such problem.

**Comment by ffkammer** [comment]
I've the same problem on Debian.

ntopng -i eth0 -U root -e -w 3000 -W 0

netstat -an | grep LIST
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 :::3000                 :::*                    LISTEN

The ntopng doen't listen on IPv4, just on IPv6

**Comment by panaceya** [comment]
2**ffkammer** - solving this problem is not interesting for developers

**Comment by lmangani** [comment]
@panaceya considering the amount of issues addressed daily, your statement is wrong
@ffkammer what version of Debian are you using?

**Comment by panaceya** [comment]
@lmangani then why this problem has been rejected?

**Comment by lmangani** [comment]
@panaceya your OS version is unsupported for the latest version as our devs outlined, if you have further investigation details suggestions can be shared if any

**Comment by lucaderi** [comment]
@panaceya In https://github.com/ntop/ntopng/blob/dev/doc/README.FreeBSD it is specified how to build ntopng on FreeBSD as well a tiny configuration for sysctl. Please give it a try, This said do not say "solving this problem is not interesting for developers" as this is not a correct statement.

**Comment by ffkammer** [comment]
Hi @lmangani,

# uname -a

Linux debian-teste 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux

# netstat -an | grep 3000

tcp6       0      0 :::3000                 :::\*                    LISTEN
