### ISSUE TITLE
Clicking on "Traffic Report" under the speedometer icon causes ntopng to hang

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#3074]
Hi all,

When I click on "traffic report" under the speedometer icon in ntopng's web interface, ntopng becomes unresponsive.

I did click "network discovery first" and begin that task, which wasn't completed when I attempted to see the traffic report, so it may be a case where something is busy.

Once the network discovery completes will attempt again.

However, if  the "Traffic Report" is dependent on the network discovery completing, is there a way to alert the user to this fact?

Thank you ...

--------------

```
support@ntopng:~$ ntopng --version
v.3.9.191120    [Enterprise/Professional build]
GIT rev:        dev:4579a11c2e99e135004129acfa686214c89a3e74:20191120
Pro rev:        r2549
Built on:       Ubuntu 18.04.3 LTS
System Id:      6B4891C10C0207EE
Platform:       x86_64
Edition:        Enterprise
License Type:   Permanent
Maintenance:    Until Tue Mar 17 17:05:22 2020 [118 days left]
License Hash:   
```

**Comment by StewAlexander-com** [comment]
Network Discovery is taking over 10 minutes, at the moment our network shows about 1500 devices and climbing as users are starting to log in, wondering if this is normal behavior?

If it is, is there any way to alert the user to time remaining?

**Comment by simonemainardi** [comment]
what is the percentage of the network discovery?

**Comment by StewAlexander-com** [comment]
@simonemainardi  Does not say

![image](https://user-images.githubusercontent.com/48565067/69242722-79258980-0b6f-11ea-923e-48b9cf522c94.png)

**Comment by StewAlexander-com** [comment]
@simonemainardi 
The network discovery is still in progress from _**yesterday!**_

![image](https://user-images.githubusercontent.com/48565067/69343838-54e3ae80-0c3c-11ea-958d-2a693a97f6bd.png)

**Comment by simonemainardi** [comment]
> When I click on "traffic report" under the speedometer icon in ntopng's web interface, ntopng becomes unresponsive.

if you restart ntopng and do not perform a discovery, then the report is responsive?

**Comment by StewAlexander-com** [comment]
@simonemainardi 
Yes, but it's missing data ... see #3083

**Comment by simonemainardi** [comment]
I've seen #3083 can you please confirm this issue still holds? That is, is the discovery still hanging?

**Comment by StewAlexander-com** [comment]
It is no longer hanging, apologies for not closing this case earlier
