### ISSUE TITLE
Add the ability to detect slow DoS

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3076]
In the attached file here is a slow DoS attack. Thousand of flows as the one depicted below with low goodput, 1 min+ packet IAT, from same source to the same destination.

ntopng is unable to detect them, hence a new script file must be developed.

[dos_slow.pcap.zip](https://github.com/ntop/ntopng/files/3872082/dos_slow.pcap.zip)
![Screen Shot 2019-11-21 at 00 49 07](https://user-images.githubusercontent.com/4493366/69288070-c00b9180-0bf8-11ea-8bd3-00716f4ab1ce.png)

**Comment by simonemainardi** [comment]
implemented in https://github.com/ntop/ntopng/commit/5b81a3ab9ed8a6a0a93a7f46f3c66ca88fd9d31f and companion pro commit

![image](https://user-images.githubusercontent.com/3397663/69352281-f38fff80-0c7c-11ea-9f0b-6e41ad06527e.png)
