### ISSUE TITLE
Permission Question

### ISSUE THREAD

**Issue by alberk8** [ntop/ntopng#308]
Hi,
I would like to ask on the startup permission of ntopng.   Must it be started by root user or via sudo.  Thanks.

For example,
1) /usr/local/bin/ntopng /usr/local/bin/ntopng.conf
(this start without problem but the Web interface does not show any flow (no packet received))

2) sudo  /usr/local/bin/ntopng /usr/local/bin/ntopng.conf
(this starts and the web interface starts show flows)

**Comment by lucaderi** [comment]
You need to start it as root. Please use the /etc/init.d service file we provide in ntopng packages to start it up
