### ISSUE TITLE
Database Mysql Structure

### ISSUE THREAD

**Issue by twistybin** [ntop/ntopng#3081]
Hi,
I enabled mysql databse, It has 4 tables, but I don't know what is different values in 4 tables ?.
![Capture](https://user-images.githubusercontent.com/43060473/69397218-f68bfe00-0d17-11ea-981c-6b631aae24ca.PNG)
I cannot find Hostname(Alias), Traffic profiles,Host pools, ... in mysql, so where i can find it in database ntopng ? 

and I want to request in Traffic Profiles.  when I click graph on profile, I need it show top IPs used by total traffic or duration time.

**Comment by simonemainardi** [comment]
> I cannot find Hostname(Alias), Traffic profiles,Host pools, ... in mysql, so where i can find it in database ntopng ?

This is the structure of the MySQL table

```
  `idx` bigint(20) NOT NULL AUTO_INCREMENT,
  `VLAN_ID` smallint(5) unsigned DEFAULT NULL,
  `L7_PROTO` smallint(5) unsigned DEFAULT NULL,
  `IP_SRC_ADDR` int(10) unsigned DEFAULT NULL,
  `L4_SRC_PORT` smallint(5) unsigned DEFAULT NULL,
  `IP_DST_ADDR` int(10) unsigned DEFAULT NULL,
  `L4_DST_PORT` smallint(5) unsigned DEFAULT NULL,
  `PROTOCOL` tinyint(3) unsigned DEFAULT NULL,
  `IN_BYTES` int(10) unsigned DEFAULT NULL,
  `OUT_BYTES` int(10) unsigned DEFAULT NULL,
  `PACKETS` int(10) unsigned DEFAULT NULL,
  `FIRST_SWITCHED` int(10) unsigned DEFAULT NULL,
  `LAST_SWITCHED` int(10) unsigned DEFAULT NULL,
  `INFO` varchar(255) DEFAULT NULL,
  `JSON` blob,
  `PROFILE` varchar(255) DEFAULT NULL,
  `NTOPNG_INSTANCE_NAME` varchar(256) DEFAULT NULL,
  `INTERFACE_ID` smallint(5) DEFAULT NULL,
```

As you can see, the traffic `PROFILE` is dumped to DB, but not the host pool. Host pool information is exported in the time series and is kept internally by ntopng.

> and I want to request in Traffic Profiles. when I click graph on profile, I need it show top IPs used by total traffic or duration time.

This feature is not supported.

**Comment by twistybin** [comment]
> > I cannot find Hostname(Alias), Traffic profiles,Host pools, ... in mysql, so where i can find it in database ntopng ?
> 
> This is the structure of the MySQL table
> 
> ```
>   `idx` bigint(20) NOT NULL AUTO_INCREMENT,
>   `VLAN_ID` smallint(5) unsigned DEFAULT NULL,
>   `L7_PROTO` smallint(5) unsigned DEFAULT NULL,
>   `IP_SRC_ADDR` int(10) unsigned DEFAULT NULL,
>   `L4_SRC_PORT` smallint(5) unsigned DEFAULT NULL,
>   `IP_DST_ADDR` int(10) unsigned DEFAULT NULL,
>   `L4_DST_PORT` smallint(5) unsigned DEFAULT NULL,
>   `PROTOCOL` tinyint(3) unsigned DEFAULT NULL,
>   `IN_BYTES` int(10) unsigned DEFAULT NULL,
>   `OUT_BYTES` int(10) unsigned DEFAULT NULL,
>   `PACKETS` int(10) unsigned DEFAULT NULL,
>   `FIRST_SWITCHED` int(10) unsigned DEFAULT NULL,
>   `LAST_SWITCHED` int(10) unsigned DEFAULT NULL,
>   `INFO` varchar(255) DEFAULT NULL,
>   `JSON` blob,
>   `PROFILE` varchar(255) DEFAULT NULL,
>   `NTOPNG_INSTANCE_NAME` varchar(256) DEFAULT NULL,
>   `INTERFACE_ID` smallint(5) DEFAULT NULL,
> ```
> 
> As you can see, the traffic `PROFILE` is dumped to DB, but not the host pool. Host pool information is exported in the time series and is kept internally by ntopng.
> 
> > and I want to request in Traffic Profiles. when I click graph on profile, I need it show top IPs used by total traffic or duration time.
> 
> This feature is not supported.

what is different between table name 'aggrflowsv4' and table name 'flowsv4' ?

**Comment by simonemainardi** [comment]
`aggr` tables contain 5-minute aggregates of flows on the following key:

```
client ip - server ip - vlan id - l4 protocol - l7 protocol
```

those tables are used to reduce the cardinality of flows and speed-up certain queries.
