### ISSUE TITLE
View with Dynamic Disaggregation 

### ISSUE THREAD

**Issue by cde0** [ntop/ntopng#3082]
Hello :)
I tried to create view for dynamic disaggregation with Probe IP but it don't show any traffic.
I tried with name,id but nothing it show on the view. The interface for every Probe IP it show the results.
The question is just if it support View with Dynamic Dissagregation. 
Cheers :)

**Comment by simonemainardi** [comment]
It doesn't seem to have sense what you are trying to do.

If you are using disaggregation, then it means you want to disaggregate the traffic, so why you are trying to put it back together with a view? Why don't you just avoid using the disaggregation?

please explain your use case

**Comment by simonemainardi** [comment]
No feedback received. Please, submit the requested information if necessary to continue the discussion.
