### ISSUE TITLE
Navigation history report

### ISSUE THREAD

**Issue by dado895** [ntop/ntopng#3084]
Please how to get on ntopng the report of the volume consumption per computer and
Navigation history report.

Best regards.

**Comment by simonemainardi** [comment]
you have an overall 'traffic report' section

![image](https://user-images.githubusercontent.com/3397663/69546572-4a0a8000-0f94-11ea-856c-6e7f29d2efa7.png)

To have host-specific reports you have the following options.

1. Access host historical timeseries. This gives you layer-7 visibility and allows you to choose the time interval of interest

![image](https://user-images.githubusercontent.com/3397663/69546647-6f978980-0f94-11ea-9d82-5b9dc283fb73.png)

2. access host traffic report (enterprise only). This shows you the host total traffic and compares it with previous periods.

![image](https://user-images.githubusercontent.com/3397663/69546710-8d64ee80-0f94-11ea-9875-3a91a50d6642.png)

3. To have navigation history you need to save flows. For this purpose, nIndex need to be used: https://www.ntop.org/ntopng/say-hello-to-nindex-personal-big-data-system-for-network-flows/
