### ISSUE TITLE
Error when i click host on Top Hosts (local)

### ISSUE THREAD

**Issue by mhonzki** [ntop/ntopng#3086]
When I navigate top host local and click 1 of the host, I received the error below.

****/usr/local/share/ntopng/scripts/lua/modules/http_lint.lua:1324: [LINT] _GET["host"] = "TCXerver.BGN" parameter error: Validation error****

![image](https://user-images.githubusercontent.com/58162469/69519454-082e0980-0f95-11ea-8f7f-dafd2e1b03cb.png)

**Comment by mhonzki** [comment]
any update on this plsss..

**Comment by simonemainardi** [comment]
please attach a screenshot to show where you click to trigger the error

**Comment by mhonzki** [comment]
Hi 
Thanks for the response I got this error message when I was clicking **HOSTS**>>**TOP HOSTS**>>**ALUCARD.BGN** and it shows an error.

![image](https://user-images.githubusercontent.com/58162469/69596064-54805480-103c-11ea-8f3d-c150cc103241.png)
![image](https://user-images.githubusercontent.com/58162469/69596069-58ac7200-103c-11ea-9c6a-2c83764be3a0.png)
![image](https://user-images.githubusercontent.com/58162469/69596105-72e65000-103c-11ea-97ea-abaf2ee01c99.png)
![image](https://user-images.githubusercontent.com/58162469/69596164-9e693a80-103c-11ea-883c-09f47eef2601.png)

BTW my version is the latest I think.
![image](https://user-images.githubusercontent.com/58162469/69596184-b04add80-103c-11ea-811e-48a10e298606.png)

**Comment by simonemainardi** [comment]
You're using an outdated version of ntopng. Please upgrade to at least version 3.8 and it will work.

**Comment by mhonzki** [comment]
Hi sir,
Thanks for the response again how do we update my ntopng from my pfsense. do you have any document to do this? thank you so much.

**Comment by emanuele-f** [comment]
Please contact the pfsense support for this, it is something specific of their distribution.

**Comment by mhonzki** [comment]
But they will support the users that have a license.

**Comment by emanuele-f** [comment]
You cannot install a licensed version of ntopng in pfsense as we don't build for the pfsense OS

**Comment by mhonzki** [comment]
But the pfsense gives only a 3.6 version ok ntopng....btw
My pfsense version is 2.4.4 thanks

**Comment by emanuele-f** [comment]
Since we do not maintain the pfsense package you have two options:
1. Ask the pfsense package maintainer to upgrade the package
2. Install our official packages on a supported distribution, see http://packages.ntop.org
