### ISSUE TITLE
[LuaEngine.cpp:11693] WARNING: Script failure

### ISSUE THREAD

**Issue by bezi019** [ntop/ntopng#3087]
Hi
Im trying to configure ntop datasource in Grafana:

![Capture](https://user-images.githubusercontent.com/58218502/69635460-b0150700-1069-11ea-9200-9b559f7a4bb3.JPG)

but its not working at all and from ntop side I face below error:

![Capture2](https://user-images.githubusercontent.com/58218502/69635570-f66a6600-1069-11ea-82c6-81f76ed7f61f.JPG)

![Capture3](https://user-images.githubusercontent.com/58218502/69635820-77c1f880-106a-11ea-8796-b12a4ea0f90a.jpg)

**Comment by simonemainardi** [comment]
hi, as shown in the discontinuation notice at https://github.com/ntop/ntopng-grafana-datasource#discontinuation-notice

The datasource is no longer supported. Just enable influxdb from ntopng and the use the influxdb grafana datasource.
