### ISSUE TITLE
Zeromq transport debugging

### ISSUE THREAD

**Issue by nucleusv** [ntop/ntopng#309]
Hi, 

I try to export flows from pmacct collector, 
how can I debug if ntopng doen not recieve any flow over zeromq interface any verbose mode

what fields must be in json and what feilds are optional ?
http://www.ntop.org/nprobe/why-nprobejsonzmq-instead-of-native-sflownetflow-support-in-ntopng/

**Comment by lucaderi** [comment]
Hi please use nprobe from http://packages.ntop.org to send ntopng flows and see what is the expected format.
