### ISSUE TITLE
Category list download issues on Windows

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3091]
A user reported the following error while downloading the category lists:

`[26/11/2019 07:34:36][Warning][Device Disconnection][Engaged] An error occurred while downloading list 'MalwareDomainList Hosts': The server connection timeout out after 0 seconds [HTTP Code: 0]`

We should try to reproduce this and possibly build a new package with the fix.

**Comment by lucaderi** [comment]
![Screen Shot 2020-03-21 at 17 28 40](https://user-images.githubusercontent.com/4493366/77231154-6d87b500-6b99-11ea-8c74-d577417341b9.png)
Everything works as expected with the current build
