### ISSUE TITLE
Cannot start ntopng after mysql reinstall.

### ISSUE THREAD

**Issue by alessandrobls** [ntop/ntopng#3092]
Hello,

I have Centos (centos-release-7-7.1908.0.el7.centos.x86_64). I had to remove and reinstall mysql and ntopng (I'm using enterprise version) due space problems.

After reinstalling mysql (mysql  Ver 8.0.18 for Linux on x86_64 (MySQL Community Server - GPL))  I tried to reinstall ntopng.

`[root@srvntop yum.repos.d]# systemctl start ntopng
Job for ntopng.service failed because the control process exited with error code. See "systemctl status ntopng.service" and "journalctl -xe" for details.
[root@srvntop yum.repos.d]# systemctl status ntopng.service
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/usr/lib/systemd/system/ntopng.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since gio 2019-11-28 11:08:51 CET; 8s ago
  Process: 20213 ExecStopPost=/bin/sh -c /bin/echo "$(/bin/date) ntopng StopPost" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
  Process: 20210 ExecStopPost=/bin/rm -rf /run/ntopng.conf (code=exited, status=0/SUCCESS)
  Process: 20204 ExecStartPost=/bin/sh -c /bin/echo "$(/bin/date) ntopng StartPost" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
  Process: 20203 ExecStart=/usr/local/bin/ntopng /run/ntopng.conf (code=exited, status=127)
  Process: 20199 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|^[ ]*--pid.*/s/^/#/" /etc/ntopng/ntopng.conf > /run/ntopng.conf (code=exited, status=0/SUCCESS)
  Process: 20187 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exited, status=0/SUCCESS)
  Process: 20181 ExecStartPre=/bin/sh -c /bin/echo "$(/bin/date) ntopng StartPre" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
 Main PID: 20203 (code=exited, status=127)

nov 28 11:08:51 srvntop.seko.com systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
nov 28 11:08:51 srvntop.seko.com ntopng[20203]: /usr/local/bin/ntopng: error while loading shared libraries: libmysqlclient.so.18: cannot open shared object file: No such file or directory
nov 28 11:08:51 srvntop.seko.com systemd[1]: ntopng.service: main process exited, code=exited, status=127/n/a
nov 28 11:08:51 srvntop.seko.com systemd[1]: Failed to start ntopng high-speed web-based traffic monitoring and analysis tool.
nov 28 11:08:51 srvntop.seko.com systemd[1]: Unit ntopng.service entered failed state.
nov 28 11:08:51 srvntop.seko.com systemd[1]: ntopng.service failed.
`

`
[root@srvntop yum.repos.d]# ldd /usr/local/bin/ntopng
	linux-vdso.so.1 =>  (0x00007ffff6d90000)
	librrd.so.4 => /lib64/librrd.so.4 (0x00007ff1986c2000)
	libzmq.so.5 => /lib64/libzmq.so.5 (0x00007ff19844e000)
	libjson-c.so.2 => /lib64/libjson-c.so.2 (0x00007ff198243000)
	libmaxminddb.so.0 => /lib64/libmaxminddb.so.0 (0x00007ff19803d000)
	libhiredis.so.0.12 => /lib64/libhiredis.so.0.12 (0x00007ff197e30000)
	libsqlite3.so.0 => /lib64/libsqlite3.so.0 (0x00007ff197b7b000)
	**libmysqlclient.so.18 => not found**
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff19795f000)
	libz.so.1 => /lib64/libz.so.1 (0x00007ff197749000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007ff197545000)
	libssl.so.10 => /lib64/libssl.so.10 (0x00007ff1972d3000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007ff196e70000)
	libradcli.so.4 => /lib64/libradcli.so.4 (0x00007ff196c5f000)
	librt.so.1 => /lib64/librt.so.1 (0x00007ff196a57000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007ff196852000)
	libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007ff1965fd000)
	liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007ff1963ee000)
	libcurl.so.4 => /lib64/libcurl.so.4 (0x00007ff196184000)
	libzstd.so.1 => /lib64/libzstd.so.1 (0x00007ff195ee7000)
	libm.so.6 => /lib64/libm.so.6 (0x00007ff195be5000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007ff1958de000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ff1956c8000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ff1952fa000)
	libxml2.so.2 => /lib64/libxml2.so.2 (0x00007ff194f90000)
	libpng15.so.15 => /lib64/libpng15.so.15 (0x00007ff194d65000)
	libpangocairo-1.0.so.0 => /lib64/libpangocairo-1.0.so.0 (0x00007ff194b57000)
	libpango-1.0.so.0 => /lib64/libpango-1.0.so.0 (0x00007ff194911000)
	libcairo.so.2 => /lib64/libcairo.so.2 (0x00007ff1945da000)
	libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007ff194389000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007ff194073000)
	libsodium.so.23 => /lib64/libsodium.so.23 (0x00007ff193e1e000)
	libpgm-5.2.so.0 => /lib64/libpgm-5.2.so.0 (0x00007ff193bd1000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007ff193984000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff1988fe000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007ff19369b000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007ff193497000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007ff193264000)
	libgnutls.so.28 => /lib64/libgnutls.so.28 (0x00007ff192f2a000)
	libnettle.so.4 => /lib64/libnettle.so.4 (0x00007ff192cf9000)
	libattr.so.1 => /lib64/libattr.so.1 (0x00007ff192af4000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007ff1928db000)
	libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007ff1926be000)
	libssl3.so => /lib64/libssl3.so (0x00007ff192465000)
	libsmime3.so => /lib64/libsmime3.so (0x00007ff19223d000)
	libnss3.so => /lib64/libnss3.so (0x00007ff191f0e000)
	libnssutil3.so => /lib64/libnssutil3.so (0x00007ff191cde000)
	libplds4.so => /lib64/libplds4.so (0x00007ff191ada000)
	libplc4.so => /lib64/libplc4.so (0x00007ff1918d5000)
	libnspr4.so => /lib64/libnspr4.so (0x00007ff191697000)
	libidn.so.11 => /lib64/libidn.so.11 (0x00007ff191464000)
	libssh2.so.1 => /lib64/libssh2.so.1 (0x00007ff191237000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007ff191011000)
	libpangoft2-1.0.so.0 => /lib64/libpangoft2-1.0.so.0 (0x00007ff190dfb000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007ff190bb9000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007ff1908fa000)
	libthai.so.0 => /lib64/libthai.so.0 (0x00007ff1906ee000)
	libfribidi.so.0 => /lib64/libfribidi.so.0 (0x00007ff1904d2000)
	libpixman-1.so.0 => /lib64/libpixman-1.so.0 (0x00007ff190229000)
	libEGL.so.1 => /lib64/libEGL.so.1 (0x00007ff190015000)
	libxcb-shm.so.0 => /lib64/libxcb-shm.so.0 (0x00007ff18fe11000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007ff18fbe9000)
	libxcb-render.so.0 => /lib64/libxcb-render.so.0 (0x00007ff18f9db000)
	libXrender.so.1 => /lib64/libXrender.so.1 (0x00007ff18f7d0000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007ff18f492000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007ff18f280000)
	libGL.so.1 => /lib64/libGL.so.1 (0x00007ff18eff4000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007ff18ed92000)
	libffi.so.6 => /lib64/libffi.so.6 (0x00007ff18eb8a000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007ff18e97a000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007ff18e776000)
	libp11-kit.so.0 => /lib64/libp11-kit.so.0 (0x00007ff18e447000)
	libtasn1.so.6 => /lib64/libtasn1.so.6 (0x00007ff18e234000)
	libhogweed.so.2 => /lib64/libhogweed.so.2 (0x00007ff18e00d000)
	libgmp.so.10 => /lib64/libgmp.so.10 (0x00007ff18dd95000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007ff18db5e000)
	libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007ff18d8c1000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007ff18d697000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007ff18d492000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007ff18d282000)
	libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007ff18cfcc000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007ff18cdc8000)
	libGLX.so.0 => /lib64/libGLX.so.0 (0x00007ff18cb96000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007ff18c96f000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007ff18c76c000)
	libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007ff18c53e000)`

Searching in the system

`[root@srvntop yum.repos.d]# find / -name "*libmysqlclient*"
/usr/lib64/mysql/libmysqlclient.so.21
/usr/lib64/mysql/libmysqlclient.so.21.1.18`

What can I do? Thanks

**Comment by emanuele-f** [comment]
Please update both ntopng and mysql to the latest version. If you still experience issues run:

```
sudo systemctl stop ntopng
sudo ntopng /etc/ntopng/ntopng.conf
```

and check out errors in the output. Please also report the output of `ntopng --version`

**Comment by alessandrobls** [comment]
Hello,

according rpm -qa I have installed:

```
ntopng-3.9.191128-7857.x86_64
ntopng-data-3.9.191128-7857.noarch
mysql-community-server-8.0.18-1.el7.x86_64
```
That should be latest version..

and `ntopng --version` produces

`[root@srvntop mysql]# ntopng --version
ntopng: error while loading shared libraries: libmysqlclient.so.18: cannot open shared object file: No such file or directory`

Thanks 

Alessandro.

**Comment by alessandrobls** [comment]
Removed MySQL and installed MariaDb Resolves the issue... thanks!
