### ISSUE TITLE
Sorted table isn't refreshing correctly

### ISSUE THREAD

**Issue by webernetz** [ntop/ntopng#3093]
Hello ntopng,

when I am using a table and sort for a certain column, e.g. "Hosts" within the AS list, this sorting is not refreshed, while the table contents are refreshed indeed. This leads to situations in which the sorted column isn't correct anymore. In the following screenshot, the sorting was correct at the time of opening the table, but changed afterwards. Is that on purpose?

![grafik](https://user-images.githubusercontent.com/13365684/69875844-5e18ef00-12be-11ea-9226-0f6fbd4ff2d7.png)

(Using ntopng Enterprise Edition v.3.9.191125.)

Cheers
Johannes

**Comment by emanuele-f** [comment]
Hi, yes this is a standard behaviour in ntopng, we only refresh the specific rows, we do not query the whole data again
