### ISSUE TITLE
Ldap groups

### ISSUE THREAD

**Issue by sebastianionita82** [ntop/ntopng#3095]
I would like to a have an option to disable usage of LDAP groups when using LDAP Authentication.
This will be useful in some scenarios where there are no groups implemented in LDAP.

Also there will be nice if were filters

**Comment by emanuele-f** [comment]
How would you associate the LDAP users to the ntopng users? Right now the group is what it is used for the association.

**Comment by sebastianionita82** [comment]
You right I can't with this setup. The idea is that some ldap doesn't have groups. The idea is to have the ldap setup a bit more flexible. 
- disable groups and have all users admin, restricted access by ip's or other means  
- having filters will have select users that can login

The idea is to have the ldap setup a bit more flexible.

**Comment by simonemainardi** [comment]
Currently, ldap auth is based on groups and we cannot accomodate this request unless we see multiple users demanding this feature.
