### ISSUE TITLE
Layer 7 data

### ISSUE THREAD

**Issue by bezi019** [ntop/ntopng#3098]
Hello,
Ive configured the ntopng v.3.9.191103 to send collected data to influxdb and also use garfana v.6.5.0.beta1. But my problem is I cannot configure or actually find L7 graph in Grafana for my core SW.

**Comment by emanuele-f** [comment]
Have you enabled L7 timeseries from the ntopng preferences?

**Comment by bezi019** [comment]
Yes I have.

**Comment by emanuele-f** [comment]
Can you see the L7 charts into ntopng? In Influxdb L7 data is contained into the following tables:
- `host:ndpi`: contains per-host L7 applications data
- `iface:ndpi`: contains per-interface L7 applications data 
- `host_pool:ndpi`, `asn:ndpi`, `vlan:ndpi`: contais per-pool/ASN/VLAN L7 applications data

**Comment by bezi019** [comment]
Perfect, I found it.thanks man.
how can I define a graph for top 10 hosts on specific protocol like email?

**Comment by emanuele-f** [comment]
This question is influxdb specific. Please check out https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/timeseries/drivers/influxdb.lua#L1278 for some query examples. You can also run `redis-cli lrange ntopng.trace.influxdb_queries 0 -1` to get a list of the latest influxdb queries executed by ntopng

**Comment by bezi019** [comment]
thanks a lot>
