### ISSUE TITLE
Raspberry PI installation issues

### ISSUE THREAD

**Issue by handfullofkeys** [ntop/ntopng#310]
I just installed Ntop-ng v.2.2.151130 from http://packages.ntop.org/RaspberryPI/  on a Raspberry Pi 2 with the 2015-11-21 jessie lite image. I found some minor issues that I resolved but wanted to report:

1. After install, I tried to run ntopng -h and got the following missing libraries:
libpcap – resolved by installing libpcap0.8 via apt-get
libhiredis – resolved by installing libhiredis0.10 via apt-get

2. apt-get update gives the warning: Conflicting distribution: http://packages.ntop.org armhf/ InRelease (expected armhf but got RaspberryPI). I think this is due to the file http://packages.ntop.org/RaspberryPI/armhf/InRelease having a Codename of RaspberryPI instead of armf. This isn't a big deal, but just wanted to let you know.

3. Users Guide: I noted that in the user's guide some of the options in the /etc/ntopng/ntopng.conf sample are not in the ntopng -h list. Namely: -A, -E, and -C.

**Comment by lucaderi** [comment]
Fixed in the latest package builds

**Comment by emory** [comment]
I just did a fresh install last night using the documentation on the ntop website and I'm seeing the same error (second one) as the initial requester.

If the message is benign I'm happy to ignore it, but am admittedly not clear on the package and platform identification ramifications of this package.
