### ISSUE TITLE
No show "Top Flow Talkers".

### ISSUE THREAD

**Issue by cfrancis2b** [ntop/ntopng#3100]
Since update 191205 of the ntopng this is more colorful but does not show the "Top Flow Talkers".

Regards.

**Comment by cfrancis2b** [comment]
Currently these are the installed packages:

cento.x86_64                               1.11.191206-529        @ntop         
n2n.x86_64                                 2.5.1-243              @ntop         
ndpi.x86_64                                3.1.0-2104             @ntop         
ndpi-dev.x86_64                            3.1.0-2104             @ntop         
nprobe.x86_64                              8.7.191206-6686        @ntop         
ntopng.x86_64                              3.9.191206-7930        @ntop         
ntopng-data.noarch                         3.9.191206-7930        @ntop-noarch  
pfring.x86_64                              7.5.0-2774             @ntop

**Comment by emanuele-f** [comment]
@simonemainardi please check out

**Comment by cfrancis2b** [comment]
![imagen](https://user-images.githubusercontent.com/15823719/70372981-fcefad80-18b3-11ea-8ed3-134c1d35a0a5.png)

Actualice a la versión de hoy, pero continua el problema.
Upgrade to today's version, but the problem continues.

**Comment by cfrancis2b** [comment]
Do you have any progress or comment regarding this issue?
I have made today's update without any improvement.

Regards.
