### ISSUE TITLE
Export alerts to ELK

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3105]
Add the ability to export alerts to ELK for long term analysis and storage, in addition to the native/embedded export in sqlite that is good for short term analysis

**Comment by simonemainardi** [comment]
To export alerts to ES - ELK means ElasticSearch-LogStash-Kibana, we are sending to ElasticSearch only - a new alert endpoint needs to be implemented.

Alert endpoints are the standard mechanism for ntopng to send alerts to the outside: https://www.ntop.org/guides/ntopng/plugins/alert_endpoints.html

This alert endpoint will only available when ntopng has been started with -F "es;..." and it will re-use the same connection parameters.

Currently, the format of alerts in the json is documented in https://www.ntop.org/guides/ntopng/plugins/alert_endpoints.html?highlight=endpoint#alert-format

For the sake of example, here are some alerts:

```
{
	"alert_tstamp_end": 1586525640,
	"alert_type": 2,
	"alert_entity": 1,
	"alert_severity": 2,
	"ifid": 1,
	"alert_entity_val": "127.0.0.1@0",
	"action": "release",
	"alert_json": "{\"alert_generation\":{\"subdir\":\"host\",\"script_key\":\"host_score\",\"confset_id\":0},\"metric\":\"host_score\",\"operator\":\"gt\",\"value\":1238,\"threshold\":999}",
	"alert_subtype": "host_score",
	"alert_granularity": 60,
	"alert_tstamp": 1586525580
}

{
	"alert_entity": 7,
	"alert_type": 37,
	"alert_subtype": "",
	"alert_json": "{\"msg_details\":\"ntopng v.4.1.200416 (10413) [OS: Ubuntu 16.04.6 LTS][pid: 6833][options: --interface \\\"eno1\\\" --interface \\\"lo\\\" --interface \\\"tcp://127.0.0.1:5556\\\" --dump-flows \\\"[hidden]\\\" --ndpi-protocols \\\"/tmp/cane\\\" --zmq-encryption ]\",\"event_type\":\"start\"}",
	"alert_severity": 0,
	"alert_entity_val": "ntopng",
	"action": "store",
	"ifid": -1,
	"alert_tstamp_end": 1587022692,
	"alert_granularity": 0,
	"alert_tstamp": 1587022692
}

{
	"cli_asn": 0,
	"first_seen": 1587022692,
	"cli_localhost": true,
	"srv_country": "",
	"ifid": 0,
	"flow_status": 8,
	"cli_port": 34459,
	"srv2cli_bytes": 0,
	"vlan_id": 0,
	"is_flow_alert": true,
	"alert_severity": 2,
	"srv_localhost": false,
	"alert_json": "{\"info\":\"\",\"status_info\":\"{\\\"hash_entry_id\\\":7,\\\"alert_generation\\\":{\\\"confset_id\\\":0,\\\"script_key\\\":\\\"elephant_flows\\\",\\\"subdir\\\":\\\"flow\\\"},\\\"elephant.l2r_threshold\\\":1024,\\\"ntopng.key\\\":2169596820}\"}",
	"cli2srv_bytes": 8988,
	"srv_port": 6343,
	"l7_proto": 129,
	"srv_addr": "192.168.6.7",
	"alert_type": 10,
	"alert_entity_val": "flow",
	"cli_os": "",
	"cli_country": "",
	"alert_entity": 4,
	"cli2srv_packets": 18,
	"cli_blacklisted": false,
	"srv_asn": 0,
	"srv_os": "",
	"alert_tstamp": 1587022730,
	"proto": 17,
	"score": 25,
	"cli_addr": "192.168.2.222",
	"srv_blacklisted": false,
	"l7_master_proto": 0,
	"srv2cli_packets": 0
}
```

For the integers ids found in the json there exist mappings:
- alert entity id and name is const and available at : https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/alert_consts.lua#L299
- alert type id and name is const and available at: https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/alert_keys.lua#L299
- flow status id and name is const and available at: https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/flow_keys.lua
- severity id and name is const and available at: https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/alert_consts.lua#L24

More human friendly messages can be produced if necessary as:

```
[16/04/2020 09:38:50][Error][Flow Misbehaviour] Elephant Flow (Local to Remote Traffic) [Exceeding 1 KB] [Flow: Info devel:34459 [ 00:25:90:D4:CC:F9 ] 192.168.6.7:6343 [ 04:18:D6:31:EF:5A ]]
```

Batching and retries will be handled in the alert endpoint to ensure efficiency and reduce the chances of data loss.

**Comment by simonemainardi** [comment]
JSONs have been reviewed as follow:

```
{
	"alert_tstamp": 1586525580, -- unix epoch when the alert was detected
	"alert_tstamp_end": 1586525640,  -- unix epoch when the alert is engaged/released, tstamp_end will carry the end time, otherwise no end will exist
	"alert_type":  one of {"alert_blacklisted_country", " alert_broadcast_domain_too_large ", "alert_device_connection", ...} (1)
	"alert_severity": one of {"info", "warning", "error"}
	"alert_entity": one of {"interface", "host", "network", ...}, (2)
	"alert_entity_val": "127.0.0.1@0", -- a value for the current alert type. this is always a string. for hosts its expressed as ip@vlan
         "ifname": "eno1" -- the interface name
	"ntopng_instance_id": "ntopng-instance-brx1" -- a string representing the instance of ntopng so multiple instances can export to the same database
	"engaged": true or false -- true if the issue is ongoing, false otherwise (false requires ntopng to update the state of this alert)
	"alert_subtype": "host_score", -- a subtype string which depends on the alert type. for example threshold  cross can have subtype bytes, packets, score, etc
	"alert_granularity": one of {"min", "5min", "hour", "day" or empty}, (3) is empty when the alert doesn't come out of a periodic check (e.g., broadcast domain too large)
	"alert_json": {} -- key value with additional, alert-specific information (e.g., the broadcast domain, the threshold set, the exceeded value
	"alert_msg": "a human readable text message of the alert" 
	"alert_drilldown": "/scripts/lua/xxx"-- a link wich an be used to drill down the data in ntopng. To be decided
}
```
-----


This is a structure for flow alerts:

```
{
	"first_seen": 1587022692, -- the first seen of the flow
	"alert_tstamp": 1587022730, -- epoch when this alert has been detected. there's no last seen for the flow as the flow is very likely still active and ongoing


	-- flow-specific:
	"flow_status": one of {"status_blacklisted", "status_data_exfiltration", "status_suspicious_tcp_probing"} -- the predominant status for the flow

	-- note this data is partial corresponding to the flow data when the alert is emitted
	"l7_proto": "HTTP.Google", -- same format used in ntopng
	"cli_asn": 123, -- key not present if AS not available
	"srv_asn": 567, -- same as cli 
	"cli_country": "", -- key not present when no country is available
	"srv_country": "IT", -- same as cli
	"cli_port": 34459,
	"srv_port": 6343,
	"cli_os": "",
	"srv_os": "",
	"vlan_id": 0,
	"srv2cli_bytes": 0,
	"cli2srv_bytes": 8988,
	"cli2srv_packets": 18,
	"srv2cli_packets": 0
	"cli_addr": "192.168.2.222",
	"srv_addr": "192.168.6.7",
	"score": 25,

	-- same as non-flow alert
 	"ifid": 
	"alert_entity":
	"alert_type": 
	"alert_entity_val": 
	"alert_severity": 
	"alert_json": 
	"alert_msg":
	"alert_drilldown":
}
```

-----

(1) and (4) defined at strings listed at /lua/defs_overview.lua
(2)  listed at https://github.com/ntop/ntopng/blob/fae050b90a8eacf8d1dd64b9142b02b5f54753c8/scripts/lua/modules/alert_consts.lua#L299
(3)  listed at https://github.com/ntop/ntopng/blob/fae050b90a8eacf8d1dd64b9142b02b5f54753c8/scripts/lua/modules/alert_consts.lua#L346

-------


Issue with updates engaged->released:
- _ As indices change (ntopng-01, ntopng-02) can be challenging to update from engaged->released across multiple indices: possibly use a single index ntopng-alerts and then _update_by_query on multiple fields (alert_type, alert_severity, alert_entity, timestamp, ...)_
- Can be done at query time on ES but this won't be ideal as for the same alert, multiple docs would end up in the database for the same alert
- Let ntopng chose _id fields and uniquely assign them during insertion. This has the drawback that multiple ntopng could have their _id clashed when sending to the same database. Then, the _id information would be spread between ntopng and elastic and I do not like it

Need to prepare and push a template as well. This can be done when the endpoint is first started up or then it is exporting for the first time.

**Comment by simonemainardi** [comment]
it is requested to also add a preference to only dump alerts to elasticsearch (and not flows). preference should be a UI toggle.

**Comment by simonemainardi** [comment]
implemented and documented
