### ISSUE TITLE
DNS Dissection

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3106]
![Pasted_Image_06_12_2019__20_57](https://user-images.githubusercontent.com/4493366/70352344-3bad4580-186b-11ea-82fd-332d7ddf55cc.png)
The above picture is from ntopng used to collect flows send by nProbe with -T="@NTOPNG@"
As you can see
1. if the resolver uses always the same port, the DNS protocol is set to the first detected host (DNS.Telegram in the example) even though this is just the first request
2. the DNS flow is used by the resolver to issue multiple requests. A possible solution is to rename the protocol to DNS (i.e. Remove Telegram) or split the flow in multiple sub flows (not a good idea)

**Comment by simonemainardi** [comment]
this is a pcap I've generated to reproduce the issue


[multidns_sameport.pcap.zip](https://github.com/ntop/ntopng/files/3994654/multidns_sameport.pcap.zip)

**Comment by lucaderi** [comment]
This bug is still pending
