### ISSUE TITLE
Active Flows not shown in Host Details (Centos 7)

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#311]
This bug affects centos 7.

Active flows are properly detected in the "Flows" page, but are missing from the Host Details flows page.

Active flows data is a json returned by `http://localhost:3000/lua/get_flows_data.lua`.
This endpoint behaves correctly when no `host` parameter is submitted but fails to return data when a host is submitted, e.g.,  `http://localhost:3000/lua/get_flows_data.lua?host=192.168.2.111` returns an empty json.

**Comment by seismiccollision** [comment]
i seem to have the same issue in Ubuntu 14.04.3 LTS

**Comment by simonemainardi** [comment]
I'm trying to sort this issue out with the help of `gdb`. The C method that is expected to return flows information is `ntop_get_interface_flows_info` https://github.com/ntop/ntopng/blob/dev/src/Lua.cpp#L1062

when it is called without parameters, it works as expected. When the host is given, it returns with error at line 189.

````
(gdb) n
ntop_get_interface_flows_info (vm=0x40060378) at src/Lua.cpp:1089
1089	      return CONST_LUA_ERROR;
(gdb) n
1093	}
```

The error seems to be caused by a wrong pseudo-SQL string that is passed to `ntop_interface->retrieve`:
```
(gdb) s
NetworkInterfaceView::retrieve (this=0x2873ff0, vm=0x40000378, allowed_hosts=0x7fffd0004dc0, 
    SQL=0x7fffed0bfd70 "SELECT * FROM FLOWS WHERE host = SELECT * FROM FLOWS WHERE host = S AND vlan = 0") at src/NetworkInterfaceView.cpp:137
137	  int ret = 0;
(gdb) n
139	  lua_newtable(vm);
(gdb) print allowed_hosts
$1 = (patricia_tree_t *) 0x7fffd0004dc0
(gdb) print SQL
$2 = 0x7fffed0bfd70 "SELECT * FROM FLOWS WHERE host = SELECT * FROM FLOWS WHERE host = S AND vlan = 0"
```

Pseudo-SQL is generated here: https://github.com/ntop/ntopng/blob/dev/src/Lua.cpp#L1083

Still trying to understand why the string ends up in being `SELECT * FROM FLOWS WHERE host = SELECT * FROM FLOWS WHERE host = S AND vlan = 0"`

**Comment by simonemainardi** [comment]
@seismiccollision please check now, issue should be fixed.

**Comment by seismiccollision** [comment]
@simonemainardi it is working now, thanks a bunch!

**Comment by eddy-minet** [comment]
Seems that the last commit bring the bug back : bd66cbcdcdaca5518a6352c0657c7627216caadc since 'get_host_vlan_info' and '/* Optional VLAN id */' lines have been reverted.

Issue present in ntopng-2.3.151216-719

**Comment by simonemainardi** [comment]
thanks eddy, I will fix it in a few hours.

**Comment by simonemainardi** [comment]
@eddy-minet, sorry, a newer commit overwrote the fix. it is fixed again now.
