### ISSUE TITLE
HTML tables too high

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3110]
HTML tables (e.g. the flow view) have rows that are far too high. They take a lot of unnecessary space.
It is requested to shrink them a bit to save room for other information

**Comment by gabryon99** [comment]
Created a pull request for this issue, see:
https://github.com/ntop/ntopng/commit/19d1e5108bb1a0c2094dd5f21bbfcce2197f9047

**Comment by emanuele-f** [comment]
Pull request has been merged
