### ISSUE TITLE
Fix script issues that prevent the code editor to work

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3111]
The fix requires these two issues to be addresses and this the lines uncommented to enable the code viewer
- https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/alert_utils.lua#L1100
- https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/flow_callbacks_utils.lua#L86

**Comment by emanuele-f** [comment]
Implemented in 15759c8db2d50edf2846dd544f17a5e4205951ce
