### ISSUE TITLE
Host pools randomly disappear

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#3114]
Host pools sometimes disappear (after a few minutes). It also happened to see a host pool disappearing from the Host Pools configuration page, while it was still listed in the Host Pool page, with an empty name and stats populated (see screenshot). In the latter case, creating a new host pool, the old ID has been reassigned to the new pool.
This applies to ntopng 3.8 stable.

![Screen Shot 2019-12-10 at 14 58 20](https://user-images.githubusercontent.com/7548711/70555509-73740000-1b7f-11ea-87f5-1aa858dd310a.png)

**Comment by simonemainardi** [comment]
solved in 3.9. @cardigliano please confirm.

**Comment by cardigliano** [comment]
I've been able to reproduce this on 3.8 time ago, I didn't see a fix for this actually, however it is likely this has been fixed in latest dev with some other patch. I would run some more test on dev and the next stable before closing it.

**Comment by simonemainardi** [comment]
No longer occurring. Tested in #3528 for ntopng 3.9.
