### ISSUE TITLE
Unable to load category files

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3115]
dic 10 14:12:24 loaysa ntopng[2563]: [Utils.cpp:1847] ERROR: Could not open /var/lib/ntopng/category_lists/Emerging Threats.txt.new for write
dic 10 14:12:24 loaysa ntopng[2563]: 10/Dec/2019 14:12:24 [Utils.cpp:1847] ERROR: Could not open /var/lib/ntopng/category_lists/Emerging Threats.txt.new for write
dic 10 15:00:03 loaysa ntopng[2563]: [Utils.cpp:1847] ERROR: Could not open /var/lib/ntopng/category_lists/Emerging Threats.txt.new for write
dic 10 15:00:03 loaysa ntopng[2563]: 10/Dec/2019 15:00:03 [Utils.cpp:1847] ERROR: Could not open /var/lib/ntopng/category_lists/Emerging Threats.txt.new for write
dic 10 16:00:03 loaysa ntopng[2563]: [Utils.cpp:1847] ERROR: Could not open /var/lib/ntopng/category_lists/Emerging Threats.txt.new for write
dic 10 16:00:03 loaysa ntopng[2563]: 10/Dec/2019 16:00:03 [Utils.cpp:1847] ERROR: Could not open /var/lib/ntopng/category_lists/Emerging Threats.txt.new for write

**Comment by emanuele-f** [comment]
Which linux distribution? What is the output of `ls -ld /var/lib/ntopng/category_lists`?

**Comment by simonemainardi** [comment]
unable to reproduce. please, resubmit with the requested information if necessary.
