### ISSUE TITLE
Max number of pool entries

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3116]
In
<img width="1379" alt="Screenshot 2019-12-11 at 14 15 35" src="https://user-images.githubusercontent.com/4493366/70624510-bafe9880-1c20-11ea-9ff2-8a49ba8c4290.png">

you can define more than 9 pools but only a limited number is displayed. For instance I have defined 12 pools, 9 are displayed, but if I want to add a new one the system says (correctly) that is already defined.

<img width="1368" alt="Screenshot 2019-12-11 at 14 16 29" src="https://user-images.githubusercontent.com/4493366/70624716-234d7a00-1c21-11ea-98c6-d5e7cc893b0f.png">

**Comment by simonemainardi** [comment]
I've reproduced the reported behavior. This is not a bug. You've added pools 1 to 12. As they are sorted in lexicographic order, "Pool12" that you are trying to add is shown on page 01 while you are on page 02. So ntopng correctly tells you the pool already exists.

![image](https://user-images.githubusercontent.com/3397663/71097923-1f859e80-21b1-11ea-9af3-b2e097872f40.png)

![image](https://user-images.githubusercontent.com/3397663/71097940-2c09f700-21b1-11ea-9389-837cd27ca5f5.png)
