### ISSUE TITLE
Alert browsing is not working

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3120]
Starting from the following alert
Date/Time	Duration	Severity	Alert Type	Drilldown	Description	Actions
00:15:01	05:00	Warning	 Replies / Requests Ratio	 	Host 192.168.1.2 has sent 10 DNS requests but received 4 DNS replies [5 minutes ratio: 36.4%]	 DisableDelete

clicking on the IP address it is possible to see the timeseries. In this window, setting the begin time (in the time field) the apply button does not work (instead using the time preset works).

From this page it would be nice to see what are the top queries made by this host, but this is not possible. It is requested to implement better drill down to be able to analyse the issue properly

**Comment by emanuele-f** [comment]
Datetime pickers interaction fixed in 35a3c9ab0793721721b22d9a7b1d549c301fbe90

**Comment by emanuele-f** [comment]
A drilldown link has been added to such alerts, which brings the user to the corresponding host chart. As a further enhancement, a new "top DNS queries" view could be implemented by using the following nindex topk query:

![photo_2020-01-28_14-29-30](https://user-images.githubusercontent.com/5488003/73268108-39fc6000-41d2-11ea-9684-cacf465f3e5b.jpg)
