### ISSUE TITLE
Info field not supported in flow explorer

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3121]
<img width="1368" alt="Screenshot 2019-12-11 at 15 03 22" src="https://user-images.githubusercontent.com/4493366/70627948-70cce580-1c27-11ea-97fd-67431757f663.png">

**Comment by cardigliano** [comment]
This now works with simple strings as in the example above, however it still does not work with strings containing spaces or special characters ("'" should be used in this case, however it is not currently allowed by the validator)

**Comment by cardigliano** [comment]
Fixed
