### ISSUE TITLE
Implement host auto-thresholds to avoid silly alert generation 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3123]
Sometimes we receive alerts for scanner, flooder, etc that are misleading for specific hosts. For instance for a host that has several connections (e.g. a mail server) the default threshold might be unfit. 
It is requested to add a button "auto" (or similar) that sets such thresholds based on the past host history for these thresholds.

**Comment by simonemainardi** [comment]
Can this be considered part of the anomaly/behavior you have done?

**Comment by MatteoBiscosi** [comment]
Implemented auto-threshold alerts as requested. Currently available for ASN, Networks and Interfaces for Traffic RX/TX, Score. Regarding hosts instead are available for, Contacts, Active flows and Score
