### ISSUE TITLE
Implement better flow drill-down

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3124]
In case of alerts such as
Date/Time	Duration	Severity	Alert Type	Drilldown	Description	Actions
07:26:01	01:00	Error	 TCP SYN Scan	 	Host 192.168.1.2 is a SYN Scan attacker [172 > 50 SYN sent]	 DisableDelete

it would be nice ntopng to drill down only to these selected flows that triggered the alert

**Comment by simonemainardi** [comment]
Implemented in https://github.com/ntop/ntopng/issues/2635?#issuecomment-676440796
