### ISSUE TITLE
They removed the links to check the spam and malware lists.

### ISSUE THREAD

**Issue by cfrancis2b** [ntop/ntopng#3125]
With the latest update they removed the links to check the spam and malware lists.

**Comment by lucaderi** [comment]
What do you mean exactly?

<img width="1373" alt="Screenshot 2019-12-11 at 16 04 35" src="https://user-images.githubusercontent.com/4493366/70632940-feacce80-1c2f-11ea-8b2a-9a9e5fdac5b8.png">

**Comment by cfrancis2b** [comment]
I refer to the links that allow you to review the pages. They do not appear next to the name.

**Comment by emanuele-f** [comment]
The item is actually present bu the css is making it not visible
