### ISSUE TITLE
[LuaEngine.cpp:11514] WARNING: Script failure 

### ISSUE THREAD

**Issue by cfrancis2b** [ntop/ntopng#3127]
[LuaEngine.cpp:11514] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/shutdown.lua][...g/plugins/alert_definitions/alert_port_status_change.lua:1: unexpected symbol near '<\135>']

This error is occurring after you completely reinstall ntopng.

**Comment by cfrancis2b** [comment]
11/Dec/2019 16:03:21 [AlertCheckLuaEngine.cpp:143] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [attempt to call a nil value]
11/Dec/2019 16:03:21 [AlertCheckLuaEngine.cpp:143] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [attempt to call a nil value]
11/Dec/2019 16:03:21 [AlertCheckLuaEngine.cpp:143] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [attempt to call a nil value]
11/Dec/2019 16:03:21 [AlertCheckLuaEngine.cpp:143] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [attempt to call a nil value]
11/Dec/2019 16:03:21 [AlertCheckLuaEngine.cpp:143] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [attempt to call a nil value]
11/Dec/2019 16:03:21 [AlertCheckLuaEngine.cpp:143] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [attempt to call a nil value]
11/Dec/2019 16:03:21 [AlertCheckLuaEngine.cpp:143] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [attempt to call a nil value]
11/Dec/2019 16:03:21 [LuaEngine.cpp:11514] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][...alert_definitions/alert_port_load_threshold_exceeded.lua:1: unexpected symbol near '<\135>']
11/Dec/2019 16:03:25 [LuaEngine.cpp:11514] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/shutdown.lua][...alert_definitions/alert_port_load_threshold_exceeded.lua:1: unexpected symbol near '<\135>']

**Comment by emanuele-f** [comment]
Thank you for reporting. A new package will be available in one hour

**Comment by cfrancis2b** [comment]
The problem was corrected in the last update.  Thank you
