### ISSUE TITLE
Youtube, Google, GoogleServices, Facebook grouped under TLS

### ISSUE THREAD

**Issue by wantaquddin** [ntop/ntopng#3129]
Upgraded ntopng Enterprise/Embedded from version 3.8_181227 to 3.9_191118. Previous historical data & flow are upgraded.

After upgrade, I noticed that in Traffic Report and Interfaces chart, Youtube, Google, GoogleServices and Facebook are now grouped under "TLS". Previously they're separated from "HTTPS" protocol (under old ntopng).

Under "Applications" tab in Interfaces chart, the protocols are still separated. And the flows recorded in MySQL also separated.

https://pictr.com/images/2019/12/13/5I3UDV.jpg

https://pictr.com/images/2019/12/13/5I3SbQ.jpg

https://pictr.com/images/2019/12/13/5I36S5.jpg

**Comment by simonemainardi** [comment]
Thanks for reporting. Issue is fixed and a new build is in progress. Please hold on a couple of hours and update.
