### ISSUE TITLE
Can's sign in after fresh install 

### ISSUE THREAD

**Issue by timurvafin** [ntop/ntopng#313]
Hey, not sure this is the right place for asking.

After fresh install on Centos 7 can't sing in with default username/password: admin/admin.
I've tried to reset password as described in the instruction but without any success.

So here is detailed instruction what I've tried to do:

1. Stop service and remove password key

````bash
> systemctl stop ntopng.service
> redis-cli del  ntopng.user.admin.password
(integer) 1
> redis-cli keys ntopng.user.admin*
1) "ntopng.user.admin.allowed_nets"
2) "ntopng.user.admin.full_name"
3) "ntopng.user.admin.group"
```

2. Start service and make sure default password key present. It should be md5 of "admin"

```bash
> systemctl start ntopng.service
> redis-cli get ntopng.user.admin.password
"21232f297a57a5a743894a0e4a801fc3"
```

Looks like default password is set to `md5("admin" )`, that should be ok.

But still can't sign in. Any thoughts how to debug?

Timur

**Comment by myfingerhurt** [comment]
Same here, any solution yet?

**Comment by simonemainardi** [comment]
@myfingerhurt please, explain what did you try and the experienced behavior. Does that happen on a centos7? Did you try putting the IP in the address bar or a symbolic name?
