### ISSUE TITLE
Empty OS in Network Discovery

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3130]
<img width="1308" alt="Screenshot 2019-12-16 at 17 51 35" src="https://user-images.githubusercontent.com/4493366/70926104-cbea4800-202c-11ea-8288-00f74f5f47ff.png">

**Comment by simonemainardi** [comment]
fixed in https://github.com/ntop/ntopng/commit/34387c4121ef24c116a924071902a481cc14d39d
