### ISSUE TITLE
ntopng for CentOS 8

### ISSUE THREAD

**Issue by shikari7** [ntop/ntopng#3131]
Following instructions specified for CentOS 8 here:

`http://packages.ntop.org/centos-stable/`

However no CentOS 8 RPMs have been built yet.  You can see only 6 and 7 RPMs.

Please populate the CentOS 8 repo!  :)

**Comment by simonemainardi** [comment]
centos8 stable packages will be released along with the next stable release of ntopng in Q1 2020. In the meanwhile you can use dev packages on centos8.
