### ISSUE TITLE
Domain match with zmq interfaces not working

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3132]
A user reported that malware domains (e.g. creditbootcamp.com) are not identified when using zmq interfaces. This should be checked and possibly fixed. Note: the flow URL is correctly reported.

![2019-12-18_10-35](https://user-images.githubusercontent.com/5488003/71074226-d0704700-2179-11ea-948d-867aa3d2312c.png)

**Comment by simonemainardi** [comment]
fixed in https://github.com/ntop/ntopng/commit/562ac1d0f83c3d5a312841121c5d87ac3f10a6fd
