### ISSUE TITLE
Traffic Dashboard empty after upgrade?

### ISSUE THREAD

**Issue by psct** [ntop/ntopng#3134]
I am using ntopng on armhf/Raspberry pi. While jumping from 3.9.191118-8139 to 3.9.191209-8291 the Dashboard shows no traffic at all. If I downgrade, it works as usual. This happens on fresh installs.

**Comment by simonemainardi** [comment]
do you see the traffic if you visit other pages?

**Comment by psct** [comment]
Yes, I see trafiic on the flow page and on others (I did not check every page).

**Comment by simonemainardi** [comment]
Show a screenshot. Also open the browser inspector and attach any errors you may see in the console.

**Comment by psct** [comment]
![Bildschirmfoto 2019-12-18 um 15 52 41](https://user-images.githubusercontent.com/16280050/71096582-df252100-21ae-11ea-94e9-a0867adb9862.png)

Sorry, but I see no errors.

**Comment by simonemainardi** [comment]
please, try and re-update now.

**Comment by psct** [comment]
I would like to, but I am on armhf and see no new package to do so ...

**Comment by simonemainardi** [comment]
please, retry now the package is available

**Comment by psct** [comment]
Works now for me with v.3.9.191220-8430, thank you very much!
