### ISSUE TITLE
DNS breakdown: more entries in the pie chart

### ISSUE THREAD

**Issue by webernetz** [ntop/ntopng#3136]
Is there a way to display more entries than "three + other" on the pie chart?
![grafik](https://user-images.githubusercontent.com/13365684/71091269-17bffd00-21a5-11ea-9d6f-d9ab1bccc8a1.png)

I would like to have the basic RRs displayed everytime, that is: A, AAAA, TXT, SOA, NS.
Or, every RR that has more than 10 % can be displayed?

**Comment by simonemainardi** [comment]
Implemented. All the records are now if greater than zero.

![image](https://user-images.githubusercontent.com/3397663/71093640-e0078400-21a9-11ea-8073-06784b78b660.png)

Supported records are listed at https://github.com/ntop/ntopng/blob/dev/include/DnsStats.h#L27

A new build is in progress and will be ready in a couple of hours.

**Comment by webernetz** [comment]
Wow, that was fast!!!
