### ISSUE TITLE
SNMP not working for Cisco routers?

### ISSUE THREAD

**Issue by webernetz** [ntop/ntopng#3138]
Hey guys,

I am using the SNMP functionality for a Cisco switch and two routers. While it's working without any problems for my switch, it doesn't work for my two routers. They are discovered correctly (hence SNMP community strings and ACLs work fine), however, no interface stats are coming in. I am getting the following error message: "The SNMP walk is too slow. Displayed data may be outdated or missing. Check network connectivity and device responsiveness. A new scan attempt will be performed in 15 minutes." I am using a 2811 and a 2911 router.

![grafik](https://user-images.githubusercontent.com/13365684/71167339-cd965480-2254-11ea-8c4c-ffe60e51e9e7.png)

Maybe your SNMP walk is too fast? Or has only a small timeout?

**Comment by simonemainardi** [comment]
I've added a debug preference at:

![image](https://user-images.githubusercontent.com/3397663/71246803-bb311f00-2317-11ea-88b7-f8d8f5093d99.png)

This should print out timing information out to the logs as:

```
20/Dec/2019 10:55:00 [5min.lua:10] [snmp_device.lua:46] cache_bridge executed in 0 secs [host: 192.168.2.169]
20/Dec/2019 10:55:02 [5min.lua:10] [snmp_device.lua:46] cache_interfaces executed in 2 secs [host: 192.168.2.169]
20/Dec/2019 10:55:03 [5min.lua:10] [snmp_device.lua:46] cache_interfaces_status executed in 1 secs [host: 192.168.2.169]
20/Dec/2019 10:55:04 [5min.lua:10] [snmp_device.lua:46] cache_counters executed in 1 secs [host: 192.168.2.169]
20/Dec/2019 10:55:04 [5min.lua:10] [snmp_device.lua:46] cache_bridge executed in 0 secs [host: 192.168.2.222]
20/Dec/2019 10:55:04 [5min.lua:10] [snmp_device.lua:46] cache_interfaces executed in 0 secs [host: 192.168.2.222]
20/Dec/2019 10:55:04 [5min.lua:10] [snmp_device.lua:46] cache_interfaces_status executed in 0 secs [host: 192.168.2.222]
20/Dec/2019 10:55:04 [5min.lua:10] [snmp_device.lua:46] cache_counters executed in 0 secs [host: 192.168.2.222]
20/Dec/2019 10:55:04 [5min.lua:10] [snmp_device.lua:46] cache_bridge executed in 0 secs [host: 192.168.2.134]
20/Dec/2019 10:55:04 [5min.lua:10] [snmp_device.lua:46] cache_interfaces executed in 0 secs [host: 192.168.2.134]
20/Dec/2019 10:55:04 [5min.lua:10] [snmp_device.lua:46] cache_interfaces_status executed in 0 secs [host: 192.168.2.134]
20/Dec/2019 10:55:04 [5min.lua:10] [snmp_device.lua:46] cache_counters executed in 0 secs [host: 192.168.2.134]
```

Can you please enable it and report the output so we can have an idea if the walk is slow? (wait an hour as new builds are being generated)

**Comment by simonemainardi** [comment]
hi @webernetz wondering if you've had the chance to try this...

**Comment by webernetz** [comment]
Hi @simonemainardi, I have just upgraded ntopng. I'll come back to you in a couple of days.

**Comment by webernetz** [comment]
Hey @simonemainardi, concerning the two routers that aren't working I am getting those log messages (I replaced parts of the IPv4 addresses):
<pre><code>Jan 17 11:50:30 mirror ntopng[31742]: 17/Jan/2020 11:50:30 [5min.lua:10] [snmp_device.lua:46] cache_bridge executed in 30 secs [host: 193.x.y.1]
Jan 17 11:51:00 mirror ntopng[31742]: 17/Jan/2020 11:51:00 [5min.lua:10] [snmp_device.lua:46] cache_bridge executed in 30 secs [host: 193.x.y.12]
Jan 17 12:10:31 mirror ntopng[31742]: 17/Jan/2020 12:10:31 [5min.lua:10] [snmp_device.lua:46] cache_bridge executed in 30 secs [host: 193.x.y.1]
Jan 17 12:11:05 mirror ntopng[31742]: 17/Jan/2020 12:11:05 [5min.lua:10] [snmp_device.lua:46] cache_bridge executed in 30 secs [host: 193.x.y.12]
Jan 17 12:30:41 mirror ntopng[31742]: 17/Jan/2020 12:30:41 [5min.lua:10] [snmp_device.lua:46] cache_bridge executed in 30 secs [host: 193.x.y.1]
Jan 17 12:31:11 mirror ntopng[31742]: 17/Jan/2020 12:31:11 [5min.lua:10] [snmp_device.lua:46] cache_bridge executed in 30 secs [host: 193.x.y.12]
Jan 17 12:50:30 mirror ntopng[31742]: 17/Jan/2020 12:50:30 [5min.lua:10] [snmp_device.lua:46] cache_bridge executed in 30 secs [host: 193.x.y.12]
Jan 17 12:51:04 mirror ntopng[31742]: 17/Jan/2020 12:51:04 [5min.lua:10] [snmp_device.lua:46] cache_bridge executed in 30 secs [host: 193.x.y.1]
Jan 17 13:10:52 mirror ntopng[31742]: 17/Jan/2020 13:10:52 [5min.lua:10] [snmp_device.lua:46] cache_bridge executed in 30 secs [host: 193.x.y.1]
Jan 17 13:11:28 mirror ntopng[31742]: 17/Jan/2020 13:11:28 [5min.lua:10] [snmp_device.lua:46] cache_bridge executed in 30 secs [host: 193.x.y.12]
Jan 17 13:30:34 mirror ntopng[31742]: 17/Jan/2020 13:30:34 [5min.lua:10] [snmp_device.lua:46] cache_bridge executed in 30 secs [host: 193.x.y.12]
Jan 17 13:31:04 mirror ntopng[31742]: 17/Jan/2020 13:31:04 [5min.lua:10] [snmp_device.lua:46] cache_bridge executed in 30 secs [host: 193.x.y.1]</code></pre>

Does that help?

**Comment by simonemainardi** [comment]
Sorry for the late feedback and thanks for providing this info. We are going to rework how snmp devices are polled to handle possibly long pools. Stay tuned.

**Comment by lucaderi** [comment]
Fixed in the current development version that will be available overnight
