### ISSUE TITLE
Set Host IP Address

### ISSUE THREAD

**Issue by kargh** [ntop/ntopng#314]
The servers ntopng currently runs on in our environment has both a public and a private IP. I'd like to be able to limit the IP ntopng listens on (for the web front end) to the private IP address without having to work around this issue via other means.

I have tried to bind it to the local interface (-w=:3000 in the ntopng.conf file) but it still replies on the public IP.

**Comment by simonemainardi** [comment]
confirmed. ntopng binds to any address even if the colon is specified in the -w option

**Comment by simonemainardi** [comment]
fixed in 417e909
