### ISSUE TITLE
unify suricata and ntopng not worked.

### ISSUE THREAD

**Issue by MozCrash** [ntop/ntopng#3140]
sorry to bother you.
It costs me about 3 days to unify suricata and ntopng according to the [guides](https://www.ntop.org/guides/ntopng/advanced_features/suricata.html), and it still not worked.

Details as follows

my computer info：
Computer: Virtual Machine Created by ESXI
OS: CentOS 7
Network interface: ens192
Ntopng: v.3.9.191219 compiled from github
Web Port: 127.0.0.1:6666
Nginx: proxy 80/443 to 6666
Syslog Port: 127.0.0.1:9999
Firewall: 9999 open
Suricata: 3.1

1.Suricata outputs to syslog
run comman
`
suricata -c /etc/suricata/suricata.yaml -i ens192
`
config info
`- eve-log:
      enabled: yes
      filetype: syslog 
      identity: "suricata"
      facility: local5
      level: info 
`
2.rsyslog
/etc/rsyslog.d/suricata.conf
`*.*  @@127.0.0.1:9999`

3.ntopng
`
nohup /usr/local/bin/ntopng /etc/ntopng/ntopng.conf -i ens192 -i syslog://127.0.0.1:9999 -w 127.0.0.1:6666 -v 6 --commuunity &
`
And  set Mirrored Traffic checked & Companion Interface selected syslog interface.In
Web console there is no data in interface syslog,and I added debug function in SyslogParserInterface.cpp file of line 69,it can receive a lots of data,sample as follows
`
19/Dec/2019 07:03:34 [SyslogParserInterface.cpp:69] [SYSLOG] Application: suricata Message: {"timestamp":"2019-12-19T07:03:34.000115-0500","event_type":"stats","stats":{"uptime":8747,"capture":{"kernel_packets":1056773,"kernel_drops":20},"decoder":{"pkts":1056774,"bytes":799392047,"invalid":324,"ipv4":1048347,"ipv6":2,"ethernet":1056774,"raw":0,"null":0,"sll":0,"tcp":1046217,"udp":1785,"sctp":0,"icmpv4":21,"icmpv6":0,"ppp":0,"pppoe":0,"gre":0,"vlan":0,"vlan_qinq":0,"teredo":2,"ipv4_in_ipv6":0,"ipv6_in_ipv6":0,"mpls":0,"avg_pkt_size":756,"max_pkt_size":1534,"erspan":0,"ipraw":{"invalid_ip_version":0},"ltnull":{"pkt_too_small":0,"unsupported_type":0}},"flow":{"memcap":0,"spare":10000,"emerg_mode_entered":0,"emerg_mode_over":0,"tcp_reuse":0,"memuse":7157856},"defrag":{"ipv4":{"fragments":0,"reassembled":0,"timeouts":0},"ipv6":{"fragments":0,"reassembled":0,"timeouts":0},"max_frag_hits":0},"stream":{"3whs_ack_in_wrong_dir":0,"3whs_async_wrong_seq":0,"3whs_right_seq_wrong_ack_evasion":0},"tcp":{"sessions":628,"ssn_memcap_drop":0,"pseudo":30,"pseudo_failed":0,"invalid_checksum":0,"no_flow":0,"syn":666,"synack":603,"rst":84,"segment_memcap_drop":0,"stream_depth_reached":49,"reassembly_gap":1,"memuse":3043216,"reassembly_memuse":12320544},"detect":{"alert":24},"flow_mgr":{"closed_pruned":603,"new_pruned":184,"est_pruned":330},"dns":{"memuse":1809,"memcap_state":0,"memcap_global":0},"http":{"memuse":0,"memcap":0}}}
`
but why there is no data in interface syslog.
thanks bro.

**Comment by cardigliano** [comment]
It seems that ntopng is receiving Suricata messages correctly, it is likely the lua plugin that handles those messages is not working properly. Checking on our side.

**Comment by MozCrash** [comment]
thanks a lot. :)

**Comment by cardigliano** [comment]
@MozCrash this has been fixed, please update from github (or the new package will be available in <1h) and let us know.

**Comment by MozCrash** [comment]
good job,it fixed.thanks again. :)
