### ISSUE TITLE
Invalid layout

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3141]
<img width="1065" alt="Screenshot 2019-12-20 at 17 09 34" src="https://user-images.githubusercontent.com/4493366/71267691-9060be00-234b-11ea-99c5-233e990162d1.png">

**Comment by simonemainardi** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/3397663/71352908-d00bed80-2577-11ea-9940-78c517a57e2c.png)
