### ISSUE TITLE
Search filter by Autonomous system number ASN 

### ISSUE THREAD

**Issue by traderose** [ntop/ntopng#3145]
May be good to add search/filter per ASN. It will be helpful when you need to know traffic amount from your ASN to a remote ASN.

![image](https://user-images.githubusercontent.com/30375013/71376947-48a09780-25d4-11ea-9473-c9eadc32f3b4.png)

**Comment by simonemainardi** [comment]
Autonomous system search is implemented:

![image](https://user-images.githubusercontent.com/3397663/130778696-9638416c-8c60-4bc4-90c1-0b9b04c5c4db.png)


To respond to queries such as "knowing the amount of traffic from your ASN to a remote ASN" you can use nIndex and the new explorer, using filters on the AS. For example, to know the traffic directed to DigitalOcean, you can query as

![image](https://user-images.githubusercontent.com/3397663/130778879-fa2da810-a22a-48af-b1c1-ca4281ad9e82.png)
