### ISSUE TITLE
Can't access Web Interface after updating ntopng

### ISSUE THREAD

**Issue by tomarch** [ntop/ntopng#3146]
Hi,

Today i've updated our two ntopng server and now we can't access web interface.
We have the authentification form and after login we have "ERR_EMPTY_RESPONSE" error

ntopng --version
v.3.9.191224	[Enterprise/Professional build]
GIT rev:	dev:8b7d711a3674d2af92b59bf647c23c6f040de714:20191224
Pro rev:	r2626

we use centos 7 package: ntopng.x86_64   3.9.191224-8111

we have severals errors when launching ntopng with command line : 
`24/Dec/2019 09:59:55 [PeriodicActivities.cpp:100] Started periodic activities loop...
24/Dec/2019 09:59:55 [startup.lua:21] [plugins_utils.lua:66] ERROR: Missing mandatory field 'title' in plugin.lua of 'flow_misbehaviour'
24/Dec/2019 09:59:55 [startup.lua:21] [plugins_utils.lua:66] ERROR: Missing mandatory field 'title' in plugin.lua of 'tcp_connection_issues'
24/Dec/2019 09:59:55 [startup.lua:21] [plugins_utils.lua:66] ERROR: Missing mandatory field 'title' in plugin.lua of 'malicious_signature'
24/Dec/2019 09:59:55 [startup.lua:21] [plugins_utils.lua:66] ERROR: Missing mandatory field 'title' in plugin.lua of 'nagios_alert_endpoint'
24/Dec/2019 09:59:55 [startup.lua:21] [plugins_utils.lua:66] ERROR: Missing mandatory field 'title' in plugin.lua of 'security_alerts'
24/Dec/2019 09:59:55 [startup.lua:21] [plugins_utils.lua:66] ERROR: Missing mandatory field 'title' in plugin.lua of 'blocked_flow'
24/Dec/2019 09:59:56 [LuaEngine.cpp:11663] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/startup.lua][/usr/share/ntopng/scripts/callbacks/system/startup.lua:40: attempt to index a boolean value (global 'shaper_utils')]
24/Dec/2019 09:59:56 [PeriodicActivities.cpp:148] Each periodic activity script will use 2 threads
24/Dec/2019 09:59:56 [NetworkInterface.cpp:2346] Started packet polling on interface eno2 [id: 0]...
24/Dec/2019 10:00:00 [AlertCheckLuaEngine.cpp:143] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:1340: attempt to index a nil value (local 'conf')]
24/Dec/2019 10:00:00 [AlertCheckLuaEngine.cpp:143] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:1340: attempt to index a nil value (local 'conf')]
24/Dec/2019 10:00:00 [AlertCheckLuaEngine.cpp:143] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:1340: attempt to index a nil value (local 'conf')]
24/Dec/2019 10:00:00 [AlertCheckLuaEngine.cpp:143] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/network.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:1340: attempt to index a nil value (local 'conf')]
24/Dec/2019 10:00:00 [AlertCheckLuaEngine.cpp:143] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/network.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:1340: attempt to index a nil value (local 'conf')]
24/Dec/2019 10:00:00 [AlertCheckLuaEngine.cpp:143] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/network.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:1340: attempt to index a nil value (local 'conf')]
24/Dec/2019 10:00:00 [AlertCheckLuaEngine.cpp:143] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/network.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:1340: attempt to index a nil value (local 'conf')]
24/Dec/2019 10:00:00 [AlertCheckLuaEngine.cpp:143] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:1340: attempt to index a nil value (local 'conf')]
`
Thanks for your help

**Comment by emanuele-f** [comment]
This is now fixed. The new package will be available in one hour.

**Comment by tomarch** [comment]
Perfect, works again !
Thanks.
