### ISSUE TITLE
High load on houskeeping.lua due to alerts

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3148]
Lua script `housekeeping.lua` puts a lot of pressure on the system.

![image](https://user-images.githubusercontent.com/3397663/71421816-8f969780-267d-11ea-972d-2253e80eb71c.png)

Alert-related functions contained in the script are responsible for this high load. Commenting them reduces the load dramatically. Specifically, the functions creating the highest pressure are the `json.decode`. It is requested to rework this script to make it more efficient.

**Comment by cardigliano** [comment]
This has been improved by removing a json decode in 1 place (out of 3, as in the other 2 places it requires a major code rework) for alerts coming from the datapath, and a json encode that was actually duplicated.
