### ISSUE TITLE
nProbe: --zmq option not recognized on Ubiquity version

### ISSUE THREAD

**Issue by jmreid** [ntop/ntopng#315]
I installed nProbe from http://packages.ntop.org/Ubiquity/ and when I run:
````
nprobe --zmq "tcp://10.0.1.1:5556" -i eth0 -n none
````

I get:
````
[nprobe.c:4495] WARNING: Unrecognized option '--zmq' 
````
Is this version of nProbe not compiled to support the zmq interface? I have ntopng running on a dedicated machine and want to be able to interface with nProbe that is running on the EdgeRouter.

**Comment by simonemainardi** [comment]
@jmreid please use the nProbe issue tracker here https://github.com/ntop/nProbe/issues

**Comment by lucaderi** [comment]
Duplicate of https://github.com/ntop/nProbe/issues/16
