### ISSUE TITLE
Multiple ntopng points to influxdb, how to distinguish the source host

### ISSUE THREAD

**Issue by libin525308160** [ntop/ntopng#3150]
Specify the database of multiple ntopng programs as the same influxdb database, and use grafana to obtain display data from influxdb. During this process, I found that it is impossible to distinguish which host the ntopng traffic comes from. How do I need to distinguish the source host?

**Comment by simonemainardi** [comment]
You have to use one InfluxDB database per process. Just configure a different database name on each ntopng instance.
