### ISSUE TITLE
Slow processing even with almost no traffic reported

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3152]
![Screen Shot 2019-12-27 at 09 12 41](https://user-images.githubusercontent.com/4493366/71508728-153a6300-2889-11ea-8172-f3d12497834d.png)

**Comment by simonemainardi** [comment]
threshold should be 50 and not 0 as shown in the image. This is the configuration obtained on the same host:

![image](https://user-images.githubusercontent.com/3397663/71511953-7b78b300-2894-11ea-95c1-d26d67ea83fb.png)

so it could be that user script slow_purge.lua is not reading the correct value.

**Comment by emanuele-f** [comment]
The issue was caused by a missing purge on the ARP matrix hash.

![2019-12-31_11-59](https://user-images.githubusercontent.com/5488003/71620319-408ebc00-2bc1-11ea-871a-3180a555fb4b.png)
