### ISSUE TITLE
Community edition dropdowns are poorly styled

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3154]
In community edition, dropdowns look like

![image](https://user-images.githubusercontent.com/3397663/71524187-a121ae80-28cc-11ea-92a4-6be67e896263.png)

it is requested to restyle them to make them look as

![image](https://user-images.githubusercontent.com/3397663/71524246-eb0a9480-28cc-11ea-8010-93543986d5c4.png)

**Comment by gabryon99** [comment]
Issue fixed: https://github.com/ntop/ntopng/pull/3176
