### ISSUE TITLE
Implement template in scripts/lua/config_list.lua and scripts/lua/script_list.lua

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3159]
This page is full of HTML and CSS code and it is not at all a lua file. Please
- implement a template with HTML code and use it
- move the CSS code into a separate file
- remove all references in code comments to authors

Create a pull request and submit it.

**Comment by lucaderi** [comment]
See for instance scripts/lua/flow_details.lua and templates present in httpdocs/templates

**Comment by gabryon99** [comment]
Opened pull request: https://github.com/ntop/ntopng/pull/3160
