### ISSUE TITLE
ntopng timeseries

### ISSUE THREAD

**Issue by bezi019** [ntop/ntopng#3161]
hello,
quick question:
what's the differences between "Interfaces Timeseries", "Local Hosts Timeseries" and "Devices Timeseries"?

**Comment by simonemainardi** [comment]
Hello

- Interfaces Timeseries: timeseries for the interface, that is, traffic (both tx and rx), l7 protocols, l4 protocols, etc. at the level of interface (e.g., eth0)
- Local Hosts Timeseries: timeseries calculated for each local host (you define local hosts using option -m). These timeseries can consume a lot of disk space, especially when the number of local hosts is high
- Devices Timeseries: timeseries calculated for Mac addresses
