### ISSUE TITLE
Form submit always assume successful responses

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3165]
Forms in template files `config_list.html` and `script_list.html` always assume successful responses, i.e, no timeouts are handled, no responses != 200 are handled, it is always assumed the server responds with a valid 200 OK and with payload. It is requested to handle such cases.

**Comment by gabryon99** [comment]
Issue fixed: https://github.com/gabryon99/ntopng/commit/daf231391ddb3683043dcc0cbfe54e7738bef5b5
