### ISSUE TITLE
Config: Invalid targets accepted

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3171]
the UI accepts the target

![image](https://user-images.githubusercontent.com/3397663/71585875-5f854380-2b18-11ea-8f8a-c4883f876fe2.png)

the backend complains

30/Dec/2019 15:20:01 [Utils.cpp:2891] ERROR: Error parsing IPv6 q:p:
30/Dec/2019 15:21:01 [Utils.cpp:2891] ERROR: Error parsing IPv6 q:p:

it is requested not to accept invalid inputs

**Comment by emanuele-f** [comment]
Fixed in 03e3613e7ee8e8b1eec976324ecc119e21b19622
