### ISSUE TITLE
(Invalid) targets accepted multiple times

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3172]
trying to add `x:y:z:w:q:p:l` yields an error message which is nonsensical 

![image](https://user-images.githubusercontent.com/3397663/71585956-b0953780-2b18-11ea-9a58-235b8efbee26.png)

**Comment by emanuele-f** [comment]
Fixed in 63e270313e21f6b5d386a0e0cef57ba9b7f008fc
