### ISSUE TITLE
Wrong speed detection of 10GbE interface

### ISSUE THREAD

**Issue by aaronjwood** [ntop/ntopng#3177]
I have a Mellanox  ConnectX-2 card which is 10GbE. From ethtool:
```
Settings for enp5s0:
        Supported ports: [ FIBRE ]
        Supported link modes:   10000baseT/Full
        Supported pause frame use: No
        Supports auto-negotiation: No
        Supported FEC modes: Not reported
        Advertised link modes:  10000baseT/Full
        Advertised pause frame use: No
        Advertised auto-negotiation: No
        Advertised FEC modes: Not reported
        Speed: 10000Mb/s
        Duplex: Full
        Port: FIBRE
        PHYAD: 0
        Transceiver: internal
        Auto-negotiation: off
        Supports Wake-on: d
        Wake-on: d
        Current message level: 0x00000014 (20)
                               link ifdown
        Link detected: yes
```

This interface shows up as gigabit in ntop:
![Capture](https://user-images.githubusercontent.com/446283/71635223-85bde880-2bd7-11ea-801c-33f1a0adf660.PNG)

**Comment by cardigliano** [comment]
@aaronjwood are you sure you didn't configure/overwrite the interface speed in the interface configuration tab? Otherwise it means ntopng is failing reading the interface speed through the ethtool API, any chance we can ssh to this system to debug it?

**Comment by aaronjwood** [comment]
Yeah, I haven't fiddled with any of the interface settings. I did make a change recently and restart ntop which seems to have fixed the issue. I'm now passing `-U 1000` and `--community` args at runtime where I wasn't before. No idea why this would fix the issue, I'm thinking it's unrelated. If I hit the issue again I'll post my findings and explain what steps I took to get there.

**Comment by aaronjwood** [comment]
The issue popped up again. Yesterday after the restart of ntop the interface speed was detected correctly but today it's back to being reported at 1.0 Gbit/s. I don't see any relevant logs on stdout/stderr but I'm able to reproduce this behavior:

1. Restart ntop
2. See that the interface speed is reported correctly
3. Wait some time (unsure of how long) and see that the interface speed is reported incorrectly
4. Repeat

**Comment by aaronjwood** [comment]
Another thing to note: when the speed is being reported correctly ntop shows the IPv6 link-local address like so:
![Capture](https://user-images.githubusercontent.com/446283/71694066-f3e2e680-2d62-11ea-84f0-98506883a7db.PNG)

When the speed is not reported correctly there's no detection of the link-local address (see screenshot in my original post)

**Comment by cardigliano** [comment]
@aaronjwood could you confirm that the interface speed switches from 10 to 1G without restarting ntopng? (please check the uptime to make sure) Thank you

**Comment by cardigliano** [comment]
@aaronjwood any update on this? Please also let us know if it is possible to ssh to this system to debug the issue. Thank you.

**Comment by aaronjwood** [comment]
I haven't hit the issue again since it happened. And no, this environment is closed off so I can't provide ssh access.

**Comment by cardigliano** [comment]
Please let us know if you are able to reproduce again (maybe we can connect with TeamViewer or other supervised tool?)

**Comment by cardigliano** [comment]
Closing for the time being, please reopen if it happens again
