### ISSUE TITLE
Unable to connect to remote mysql DB

### ISSUE THREAD

**Issue by Undeadhunter** [ntop/ntopng#318]
```
14/Dec/2015 09:54:42 [MySQLDB.cpp:320] Attempting to connect to MySQL for interface tcp://127.0.0.1:5556...
14/Dec/2015 09:54:42 [MySQLDB.cpp:360] Succesfully connected to MySQL [mysqlDB:user] for interface tcp://127.0.0.1:5556
14/Dec/2015 09:54:42 [MySQLDB.cpp:380] ERROR: MySQL error: [Access denied for user 'user'@'localhost' to database 'ntopng'][CREATE DATABASE IF NOT EXISTS ntopng]
14/Dec/2015 09:54:42 [MySQLDB.cpp:36] ERROR: MySQL error: Access denied for user 'user'@'localhost' to database 'ntopng'
14/Dec/2015 09:54:42 [Ntop.cpp:1149] Registered interface tcp://127.0.0.1:5556 [id: 3]
14/Dec/2015 09:54:42 [Ntop.cpp:1162] Registered interface view tcp://127.0.0.1:5556 [id: 3]
14/Dec/2015 09:54:42 [Utils.cpp:304] User changed to nobody
14/Dec/2015 09:54:42 [main.cpp:240] PID stored in file /var/tmp/ntopng.pid
```
In the config file I use 

`-F="mysql;mysqlDB;ntopng;flows;user;"`

I don't know why it keeps going back to trying to connect to the localhost server

Trying to run from command line gives me the same issues, and I can't find much information in the documentation besides how to connect.

**Comment by lucaderi** [comment]
"mysql -u user" works from the command line ?

**Comment by Undeadhunter** [comment]
Problem is that ntopng itself keep connecting to the localhost, instead of the host defined in the config file.

**Comment by lmangani** [comment]
Are you following the examples in our [Wiki](https://github.com/ntop/ntopng/wiki/03-MySQL-FAQ)?

**Comment by Undeadhunter** [comment]
Yes, following the wiki, only difference is instead of localhost I replace it with my MySQL server on the network (eg 192.168.1.100, or mysqlDB hostname in this example).

**Comment by simonemainardi** [comment]
The user doesn't have privileges to create the database schema. Please check mysql user permissions. Also note that mysql sees an incoming connection for 'user'@'localhost'. Maybe hostname mysqlDB maps to localhost?

However, I can reproduce as follows.

I create a MySQL user 'demo',  allowing incoming connections from any host in the network 192.168.0.0/16. However, I do not grant any schema privileges to that user. The result is that MySQL accepts the connection but does't allow the database creation

```
15/Dec/2015 15:09:02 [MySQLDB.cpp:320] Attempting to connect to MySQL for interface eth0...
15/Dec/2015 15:09:02 [MySQLDB.cpp:360] Succesfully connected to MySQL [192.168.2.130:demo] for interface eth0
15/Dec/2015 15:09:02 [MySQLDB.cpp:380] ERROR: MySQL error: [Access denied for user 'demo'@'192.168.%' to database 'ntopng'][CREATE DATABASE IF NOT EXISTS ntopng]
15/Dec/2015 15:09:02 [MySQLDB.cpp:36] ERROR: MySQL error: Access denied for user 'demo'@'192.168.%' to database 'ntopng'

```

**Comment by Undeadhunter** [comment]
The user has all privileges, it also works when using mysql-proxy to forward all localhost commands to the remote server. But directly connecting to remote server will not connect

**Comment by simonemainardi** [comment]
This is something related to mysql privileges. Keep in mind that mysql user privileges also depend on the host the user is connecting from. You are talking about a remote server, but your ntopng output shows that mysql is seeing a connection `'user'@'localhost'`. 

please do a `ping mysqlDB` and post the output if it does not contain sensible information.

**Comment by simonemainardi** [comment]
Solution given. Not an ntopng bug. Closing.

**Comment by ghost** [comment]
31/Aug/2017 13:41:16 [MySQLDB.cpp:667] Successfully connected to MySQL [10.44.19.57:root] for interface eth0
31/Aug/2017 13:41:16 [MySQLDB.cpp:697] ERROR: MySQL error: [Can't create/write to file '/var/tmp/psylrOeUh' (Errcode: 2)][CREATE TABLE IF NOT EXISTS `flowsv6` (`idx` int(11) NOT NULL AUTO_INCREMENT,`VLAN_ID` smallint(5) unsigned DEFAULT NULL,`L7_PROTO` smallint(5) unsigned DEFAULT NULL,`IP_SRC_ADDR` varchar(48) DEFAULT NULL,`L4_SRC_PORT` smallint(5) 
unsigned DEFAULT NULL,`IP_DST_ADDR` varchar(48) DEFAULT NULL,`L4_DST_PORT` smallint(5) unsigned DEFAULT NULL,`PROTOCOL` tinyint(3) unsigned DEFAULT NULL,`BYTES` int(10) unsigned DEFAULT NULL,`PACKETS` int(10) unsigned DEFAULT NULL,`FIRST_SWITCHED` int(10) unsigned DEFAULT NULL,`LAST_SWITCHED` int(10) unsigned DEFAULT NULL,`INFO` varchar(255) DEFAULT NULL,`JSON` blob,`PROFILE` varchar(255) DEFAULT NULL,`NTOPNG_INSTANCE_NAME` varchar(256) DEFAULT NULL,`INTERFACE` varchar(64) DEFAULT NULL,KEY `idx` (`idx`,`IP_SRC_ADDR`,`IP_DST_ADDR`,`FIRST_SWITCHED`,`LAST_SWITCHED`,`INFO`(200)),KEY `ix_flowsv6_4_profile` (`PROFILE`),KEY `ix_flowsv6_4_ntopng_instance_name` (`NTOPNG_INSTANCE_NAME`(255)),KEY `ix_flowsv6_4_ntopng_interface` (`INTERFACE`)) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8/*!50100 PARTITION BY HASH (`FIRST_SWITCHED`)PARTITIONS 32 */]
31/Aug/2017 13:41:16 [MySQLDB.cpp:129] ERROR: MySQL error: Can't create/write to file '/var/tmp/psylrOeUh' (Errcode: 2)
31/Aug/2017 13:41:16 [main.cpp:283] ERROR: Unable to create database schema, quitting.

**Comment by ghost** [comment]
help,  what can it be?

**Comment by simonemainardi** [comment]
Check I/O permissions, MySQL is complaining he can't write/create a file.

What are you ntopng and OS versions? And the ntopng startup line used?
