### ISSUE TITLE
make geoip fails after GeoLite CCPA policy update

### ISSUE THREAD

**Issue by fluxcap1** [ntop/ntopng#3182]
Maxmind implemented CCPA and removed the free, direct access GeoIP download. A user should signup for a Maxmind user account for access databases.

`--2020-01-02 05:10:19--  http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
Resolving geolite.maxmind.com (geolite.maxmind.com)... failed: Name or service not known.
wget: unable to resolve host address ‘geolite.maxmind.com’
--2020-01-02 05:10:19--  http://geolite.maxmind.com/download/geoip/database/GeoLite2-ASN.tar.gz
Resolving geolite.maxmind.com (geolite.maxmind.com)... failed: Name or service not known.
wget: unable to resolve host address ‘geolite.maxmind.com’
tar (child): GeoLite2-ASN.tar.gz: Cannot open: No such file or directory
`
Please remove g/make geoip and add a doc explaining download of geoip database manually.

**Comment by emanuele-f** [comment]
More information: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases

**Comment by fluxcap1** [comment]
A workaround for this is to install geoipupdate tool, create an account on Maxmind web, generate a token, download configuration file and copy it as /etc/GeoIP.conf.

Run - geoipupdate -v -d /usr/local/src/ntopng/httpdocs/geoip/

gmake install, no need to run gmake geoip.

**Comment by simonemainardi** [comment]
ntopng-data package now brings `geoipupdate` as dependency rather than geolocation databases. Instructions to continue using geolocation in ntop products are available at https://github.com/ntop/ntopng/blob/dev/doc/README.geolocation.md
