### ISSUE TITLE
Localization and Javascript files

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3185]
A lot of boilerplate code is currently necessary to pass localized strings to javascript files

![image](https://user-images.githubusercontent.com/3397663/71714738-50034480-2e0f-11ea-8ae8-c30d74ac16a1.png)

It is requested to propose a solution to avoid this. Among the possibilities are:
- Automatically generate a js file with localized strings out of the lua i18n
- Do not use localized strings in js and only leave them in html files (js files can respond with return code used to select localized strings in the html)

**Comment by lucaderi** [comment]
I think the way it is implemented makes sense. Adding further complexity generating JS as suggested won't make things simpler. @simonemainardi ok for you to close this ticket?

**Comment by simonemainardi** [comment]
I think for the time being we can leave it as is.
