### ISSUE TITLE
ntopng reportedly crashes

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3186]
We need to review if there is some kind of network saturation in a site. But when we tried to open NTOP to check it, we found it down.
We rebooted the server and updated it but the problem remains.

We do not know what more to check and do. I attach what we get for asking ntopng status:

loops@monit:/etc/nprobe$ sudo systemctl status ntopng
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2020-01-02 17:30:09 CET; 2s ago
  Process: 8686 ExecStopPost=/bin/sh -c /bin/echo "$(/bin/date) ntopng StopPost" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
  Process: 8684 ExecStopPost=/bin/rm -rf /run/ntopng.conf (code=exited, status=0/SUCCESS)
  Process: 8551 ExecStartPost=/bin/sh -c /bin/echo "$(/bin/date) ntopng StartPost" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
  Process: 8550 ExecStart=/usr/local/bin/ntopng /run/ntopng.conf (code=exited, status=1/FAILURE)
  Process: 8546 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|^[ ]*--pid.*/s/^/#/" /etc/ntopng/ntopng.conf > /run/ntopng.conf (code=exited, status=0/SUCCESS)
  Process: 8531 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exited, status=0/SUCCESS)
  Process: 8527 ExecStartPre=/bin/sh -c /bin/echo "$(/bin/date) ntopng StartPre" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
 Main PID: 8550 (code=exited, status=1/FAILURE)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/ntopng.service

Jan 02 17:30:09 monit systemd[1]: ntopng.service: Failed with result 'exit-code'.

Please, help us to get the service up and be able to give an answer to the customer about the site they have some problems.

**Comment by cardigliano** [comment]
ntopng was failing to start due to inability to connect to mysql
