### ISSUE TITLE
macOS ERROR: Unable to write on /var/lib/ntopng as 'ntopng'

### ISSUE THREAD

**Issue by ggirotto** [ntop/ntopng#3188]
Running latest ntopng version installed using Homebrew on macOS 10.15.2

When running `sudo ntopng`, the following error is thrown:

`[main.cpp:374] ERROR: Unable to write on /var/lib/ntopng as 'ntopng' [/var/lib/ntopng/.test]: No such file or directory. Please specify a different directory (-d)`

When manually creating the directory, the following error happens:

`03/Jan/2020 11:11:46 [main.cpp:374] ERROR: Unable to write on /var/lib/ntopng as 'ntopng' [/var/lib/ntopng/.test]: Permission denied. Please specify a different directory (-d)`

**Comment by cardigliano** [comment]
ntopng is changing user to 'ntopng' by default, please try with --dont-change-user or setting a different user with --user <user> (check the /var/lib/ntopng permission accordingly)

**Comment by ggirotto** [comment]
Using `--dont-change-user` worked perfectly. Thanks for the quick answer
