### ISSUE TITLE
Bring Your own Elastic Search Indexer

### ISSUE THREAD

**Issue by mroe1234** [ntop/ntopng#319]
As per the dialog in on the mailing-list "[Ntop] pushing to elasticSearch" it would be really nice to be able to use something like logstash to pull from ntop's internal redis queue and push into elasticsearch.  This would give us the ability to rename/manipulate fields as needed.

**Comment by lucaderi** [comment]
Please elaborate more in detail this request. We need a technical design specification

**Comment by lmangani** [comment]
@mroe1234 You *should* be able to use the Beats input plugin to receive traffic generated by ntopng in ES mode and manipulate it that way.

**Comment by simonemainardi** [comment]
@mroe1234 any news? did you try what @lmangani suggests?

**Comment by lmangani** [comment]
@mroe1234  can also use Logstash es_bulk plugin to decode ntopng output back to fields. 
https://github.com/logstash-plugins/logstash-codec-es_bulk

Closing.
