### ISSUE TITLE
Unclean shutdown error

### ISSUE THREAD

**Issue by fluxcap1** [ntop/ntopng#3191]
I am running ntopng on openSUSE Leap-15.1 and every time after a reboot I get this error via mail - `[06/01/2020 01:19:38][Error][Process] Started after anomalous termination (bug report) ntopng v.3.8.191004 (openSUSE Leap 15.1) [pid: 4478][options: --user "ntopng" --interface "eth0" --interface "eth1" --http-port "0" --https-port "192.168.0.155:3001" --local-networks "192.168.0.0/24" --local-networks "172.17.0.0/16" --dns-mode "1" --data-dir "/var/lib/ntopng" --redis "[hidden]" --disable-login "1" ] `

My systemd service file -

[Unit]
Description=ntopng high-speed web-based traffic monitoring and analysis tool
After=network.target syslog.target redis.service pf_ring.service cluster.service mysql.service
Requires=
Wants=suricata.service zeek.service
PartOf=

[Service]
Type=simple

ExecStartPre=/bin/sh -c '/bin/echo "$(/bin/date) ntopng StartPre" >> /var/log/ntopng-systemd.log'
ExecStartPre=/bin/sh -c '/usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true'
ExecStartPre=/bin/sh -c '/bin/sed "/^[ ]*-e.*$\\|^[ ]*-G.*\\|^[ ]*--daemon.*\\|^[ ]*--pid.*/s/^/#/" /usr/local/etc/ntopng/ntopng.conf > /run/ntopng.conf'

ExecStart=/usr/local/bin/ntopng /run/ntopng.conf

ExecStartPost=/bin/sh -c '/bin/echo "$(/bin/date) ntopng StartPost" >> /var/log/ntopng-systemd.log'
ExecStopPost=-/bin/rm -rf /run/ntopng.conf
ExecStopPost=/bin/sh -c '/bin/echo "$(/bin/date) ntopng StopPost" >> /var/log/ntopng-systemd.log'

Restart=on-abnormal
RestartSec=5

[Install]
WantedBy=multi-user.target
Alias=

Please let me know how to fix this.

**Comment by simonemainardi** [comment]
it seems ntopng isn't able to terminate gracefully. Are you able to setup core dump generation as described in https://www.ntop.org/support/need-help-2/need-help/?

Then, please enclose the resulting stacktrace or the whole core.

**Comment by fluxcap1** [comment]
> it seems ntopng isn't able to terminate gracefully. Are you able to setup core dump generation as described in https://www.ntop.org/support/need-help-2/need-help/?
> 
> Then, please enclose the resulting stacktrace or the whole core.

I am not getting any coredump.
`root@linux-fx1e:/home/flux # coredumpctl list
 
No coredumps found.`

**Comment by simonemainardi** [comment]
add option --dont-change-user to ntopng and retry. To reproduces manually you can run

`kill -SEGV <the pid of ntopng>`

and check if the core dump generates

**Comment by fluxcap1** [comment]
> add option --dont-change-user to ntopng and retry. To reproduces manually you can run
> 
> `kill -SEGV <the pid of ntopng>`
> 
> and check if the core dump generates

Nothing as yet -
root@linux-fx1e:/home/flux # kill -SEGV 15904

root@linux-fx1e:/home/flux # systemctl start ntopng.service

root@linux-fx1e:/home/flux # systemctl status ntopng.service
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/usr/lib/systemd/system/ntopng.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2020-01-07 08:24:26 PST; 6s ago
.
.
Jan 07 08:24:31 linux-fx1e ntopng[16186]: [07/01/2020 08:24:28][Error][Process][Host][ntopng] Started after anomalous termination (bug report) ntopng v.3.8.191004 (openSUSE Leap 15.1) [pid: 16186]

UPDATE-

I added --dont-change-user but still no coredump.

**Comment by fluxcap1** [comment]
The error is gone now. I changed the ExecStart= to 
/usr/local/bin/ntopng --user ntopng -i eth0 -i eth1 --http-port 0 --https-port 192.168.0.155:3001 -m 192.168.0.0/24 -n 1 -d /var/lib/ntopng -r XXXXXXX:XXXX -l 1 

Removed ExecStopPost=

Now there isn't any anomalous termination mail from system.

systemctl status ntopng
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/usr/lib/systemd/system/ntopng.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2020-01-08 01:54:45 PST; 1min 38s ago
  Process: 17273 ExecStartPost=/bin/sh -c /bin/echo "$(/bin/date) ntopng StartPost" >> /var/log/ntopng/ntopng-systemd.log (code=exited, status=0/SUCCESS)
  Process: 17257 ExecStartPre=/bin/sh -c /usr/local/bin/ntopng-utils-manage-config -a check-restore  && /usr/local/bin/ntopng-utils-manage-config -a restore || true (code=exited, status=0/SUCCESS)
  Process: 17253 ExecStartPre=/bin/sh -c /bin/echo "$(/bin/date) ntopng StartPre" >> /var/log/ntopng/ntopng-systemd.log (code=exited, status=0/SUCCESS)
 Main PID: 17272 (ntopng)
    Tasks: 25 (limit: 4915)
   Memory: 169.1M
      CPU: 3.909s
   CGroup: /system.slice/ntopng.service
           └─17272 /usr/local/bin/ntopng --user ntopng -i eth0 -i eth1 --http-port 0 --https-port 192.168.0.155:3001 -m 192.168.0.0/24 -n 1 -d /var/lib/ntopng -r XXXXXXX:XXX -l 1

Jan 08 01:54:47 linux-fx1e ntopng[17272]: 08/Jan/2020 01:54:47 [Ntop.cpp:725] Adding 192.168.0.0/24 as IPv4 local network for eth0
Jan 08 01:54:47 linux-fx1e ntopng[17272]: 08/Jan/2020 01:54:47 [Ntop.cpp:717] Adding 192.168.0.150/32 as IPv4 interface address for eth1
Jan 08 01:54:47 linux-fx1e ntopng[17272]: 08/Jan/2020 01:54:47 [Ntop.cpp:725] Adding 192.168.0.0/24 as IPv4 local network for eth1
Jan 08 01:54:47 linux-fx1e ntopng[17272]: 08/Jan/2020 01:54:47 [PeriodicActivities.cpp:72] Started periodic activities loop...
Jan 08 01:54:47 linux-fx1e ntopng[17272]: 08/Jan/2020 01:54:47 [PeriodicActivities.cpp:113] Each periodic activity script will use 2 threads
Jan 08 01:54:47 linux-fx1e ntopng[17272]: 08/Jan/2020 01:54:47 [NetworkInterface.cpp:2595] Started packet polling on interface eth0 [id: 0]...
Jan 08 01:54:47 linux-fx1e ntopng[17272]: 08/Jan/2020 01:54:47 [NetworkInterface.cpp:2595] Started packet polling on interface eth1 [id: 1]...
Jan 08 01:54:50 linux-fx1e ntopng[17272]: [08/01/2020 01:54:47][Info][Process][Host][ntopng] Started ntopng v.3.8.191004 (openSUSE Leap 15.1) [pid: 17272][options: --user "ntopng" --interface "eth0" --interfac>
Jan 08 01:54:50 linux-fx1e ntopng[17272]: [08/01/2020 01:54:35][Info][Process][Host][ntopng] Stopped ntopng v.3.8.191004 (openSUSE Leap 15.1) [pid: 16500][options: --user "ntopng" --interface "eth0" --interfac>
Jan 08 01:55:02 linux-fx1e ntopng[17272]: [08/01/2020 01:55:01][Info][Device Connection][Device][00:00:00:00:00:00] The device 00:00:00:00:00:00 has connected to the network.
