### ISSUE TITLE
ntopng script error on login

### ISSUE THREAD

**Issue by tercaneBay** [ntop/ntopng#3195]
Script "/usr/share/ntopng/scripts/lua/login.lua" returned an error:
/usr/share/ntopng/scripts/lua/modules/locales_utils.lua:40: bad argument #1 to 'for iterator' (table expected, got nil)

ntopng - version 3.9.200107-8567
ntopng-data - 3.9.200107

also on on console manuel run of ntopng facing this logs;

07/Jan/2020 11:26:31 [LuaEngine.cpp:11750] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/startup.lua][/usr/share/ntopng/scripts/lua/modules/locales_utils.lua:40: bad argument #1 to 'for iterator' (table expected, got nil)]

07/Jan/2020 11:26:33 [LuaEngine.cpp:11750] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/locales_utils.lua:40: bad argument #1 to 'for iterator' (table expected, got nil)]
07/Jan/2020 11:26:35 [LuaEngine.cpp:11750] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/discover.lua][/usr/share/ntopng/scripts/lua/modules/locales_utils.lua:40: bad argument #1 to 'for iterator' (table expected, got nil)]
07/Jan/2020 11:26:35 [AlertCheckLuaEngine.cpp:72] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/lua/modules/locales_utils.lua:40: bad argument #1 to 'for iterator' (table expected, got nil)]
07/Jan/2020 11:26:35 [LuaEngine.cpp:11750] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/usr/share/ntopng/scripts/lua/modules/locales_utils.lua:40: bad argument #1 to 'for iterator' (table expected, got nil)]
07/Jan/2020 11:26:36 [LuaEngine.cpp:11750] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/locales_utils.lua:40: bad argument #1 to 'for iterator' (table expected, got nil)]

**Comment by simonemainardi** [comment]
platform?

Seems an issue with the loading of plugin locales:

```
function locales.loadLocaleFile(path, locale)
  local chunk = assert(loadfile(path))
  local data = chunk()

  -- Check if plugin specific locales exist
  local plugins_locales = dirs.workingdir .. "/plugins/locales/" .. locale .. ".lua"

  if ntop.exists(plugins_locales) then
    local chunk = assert(loadfile(plugins_locales))
    local plugins_data = chunk()

    -- Add the plugins localized strings
    for k, v in pairs(plugins_data) do
      data[k] = v
    end
  end

  i18n.load({[locale]=data})
end
```

**Comment by tercaneBay** [comment]
Ubuntu default config. Even i run without config file. This occurs.

**Comment by simonemainardi** [comment]
ubuntu version?

**Comment by tercaneBay** [comment]
Ubuntu 18.04.3 LTS

**Comment by simonemainardi** [comment]
I've added extra debug info which should help in diagnosing this issue. A new build is in progress, hold on an our, update, and provide the new logs.

In the meanwhile, can you please try and attach the contents of /var/lib/ntopng/plugins/locales/en.lua. Then stop ntopng, delete it, and restart ntopng to see if the error continues

**Comment by tercaneBay** [comment]
After latest new build its fixed.
