### ISSUE TITLE
Ntop Linux Debian

### ISSUE THREAD

**Issue by philippeszanto** [ntop/ntopng#32]
'errno 10 while sending page to client'
Please, someone can help me ? 
Thanks :+1:

**Comment by ariava** [comment]
@philippeszanto could you please explain: 1) which ntopng version are you using; 2) if you are using a stable or nightly package or compiling from source; 3) how to reproduce the issue, e.g. how did you start ntopng?

**Comment by philippeszanto** [comment]
I use Ntop On debian ("apt-get install ntop", how can exactly verify the version ?) 2) A nightly package I think, i'm sorry 3) "sudo chmod -R 777 /var/lib/ntop"  and "/etc/init.d/ntop start" 

In fact, it works, but I have to this server with the least possible error, I looked in the logs and I find this error. If unable to resolve it together, it's not the end of the world.

Thanks, cordialy Philippe

**Comment by philippeszanto** [comment]
I have the version of Ntop ! (It's 5.0.1 on Debian)

**Comment by ariava** [comment]
@philippeszanto it seems you are using a very old version of the software. The up-to-date version is called ntopng and it can be downloaded here: http://www.ntop.org/get-started/download/ or you can update your repos as explained here: http://www.nmon.net/packages/ or you can even get the development version from this very repository.

**Comment by philippeszanto** [comment]
Ok, thanks, Have a good day ! :)
Cordially Philippe

**Comment by ariava** [comment]
@philippeszanto you too
