### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by mydzen** [ntop/ntopng#320]
Hello.
Have some problem in NtopNG interface in section "interfaces" (see picture).
I try to update ntopng to new version and reboot system, but this error still exist.

![pict](https://cloud.githubusercontent.com/assets/15261519/11804155/aec46ec2-a312-11e5-8cc0-2bed24888bd7.PNG)

**Comment by lucaderi** [comment]
are you using 2.3.x ? Make sure you do not mix and and new files together from different versions

**Comment by mydzen** [comment]
I use Version 2.3.151215 - Professional Edition.
I don't mix versions.

**Comment by lucaderi** [comment]
Are you using the packages we build? On what platform?

**Comment by mydzen** [comment]
I use your packages on Ubuntu 14.04.2 LTS

**Comment by simonemainardi** [comment]
fixed, please hold on, new packages will be built overnight

**Comment by mydzen** [comment]
thanks
