### ISSUE TITLE
Crashes are no longer reported in the system log

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3200]
![Screen Shot 2020-01-08 at 17 55 04](https://user-images.githubusercontent.com/4493366/71998501-103dc200-3240-11ea-9a45-72c818de129c.png)

In the past few hours ntopng crashed but these are not reported in the log. We can only see "start events" with invalid duration (what does <1 sec mean for these events?)

**Comment by cardigliano** [comment]
This seems to be working on my installation, I ran a few tests shutting down it brutally and the crash is always reported

**Comment by lucaderi** [comment]
Seems to work now. Closing it.
