### ISSUE TITLE
Missing ntopng update events

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3201]
![Screen Shot 2020-01-08 at 17 58 02](https://user-images.githubusercontent.com/4493366/71998718-70ccff00-3240-11ea-9aa1-bce70bfbc251.png)

When ntopng is updated (e.g. overnight with the automatic updates for instance) the system log does not report this event. it must be added in order to track application lifecycle

**Comment by cardigliano** [comment]
Implemented
