### ISSUE TITLE
Reuse of VMs breaks walk logic and interface views

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3202]
Commit 87c336a4

Breaks the logic behind the generic flow hash table walker. Indeed, it arbitrarily casts a `void*` into something an also allocate stuff. Method is not supposed to know or assume anything about the `void*` - everything should be up to the caller

```
+void FlowHash::walkAllStates(bool (*walker)(GenericHashEntry *h, void *user_data), void *user_data) {
+  periodic_ht_state_update_user_data_t *data = (periodic_ht_state_update_user_data_t *) user_data;
+  FlowAlertCheckLuaEngine *acle = getLuaVMUservalue(data->vm, flow_acle);
+
+  if(!acle) {
+    /* Allocate the check engine in the vm to reuse it across multiple
+     * ht_stats_update.lua calls */
+    acle = new (std::nothrow) FlowAlertCheckLuaEngine(getInterface());
+    getLuaVMUservalue(data->vm, flow_acle) = acle;
+  }
+
+  GenericHash::walkAllStates(walker, user_data);
+
+  if(acle) {
+    acle->lua_stats(getName(), data->vm);
+
+    /* Prepare for the next run */
+    acle->reset_stats();
+  }
+}
```

As a corollary, this also break the `flow.lua` script in case of view interfaces where the call is performed in the view in `ViewInterface::periodicHTStateUpdate`.

**Comment by simonemainardi** [comment]
as a workaround I've coded this 

https://github.com/ntop/ntopng/commit/d635c52bc63f23f03a3abed4f5ef79a3b392b5fe

but the solution is not to reuse a VM across multiple interfaces

**Comment by emanuele-f** [comment]
The fix above has fixed the bug. The surrounding code can probably be improved but such rework can be postponed.
