### ISSUE TITLE
Show user scripts benchmarks under the internals section

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3219]
After commit d037f9a9a44a87bdbb23699f62045fea112e3d1f it's necessary to implement a section in the internals page to show the benchmarks info that are currently missing

**Comment by simonemainardi** [comment]
implemented

![image](https://user-images.githubusercontent.com/3397663/72829448-18095780-3c7f-11ea-9cb5-4a6a6ccb2ee1.png)
