### ISSUE TITLE
ntopng active flows for network element says No 	Results	Found

### ISSUE THREAD

**Issue by ohadkl** [ntop/ntopng#322]
We are using the latest version of ntopng v.2.3.151213, when trying to view
any of the host active flows I get   No Results Found.

All other tabs with info is working properly, is this a bug or I am missing anything? I know this option used to work in the previous versions.

I have attached a screen shot of the problem we encounter.
https://dl.dropboxusercontent.com/u/27973370/ntopngactiveflows.jpg

**Comment by ohadkl** [comment]
Looking at the browser javascript console i see no errors.

https://dl.dropboxusercontent.com/u/27973370/ntopngflow_console.jpg

**Comment by simonemainardi** [comment]
this has already been fixed, please see https://github.com/ntop/ntopng/issues/311

update to the latest dev build v.2.3.151215

**Comment by ohadkl** [comment]
I have tested this with ntopng version 2.3.151216 but still same problem.

**Comment by simonemainardi** [comment]
a newer commit overwrote the fix. sorry. it is fixed again now.
