### ISSUE TITLE
 Script "/usr/share/ntopng/scripts/lua/if_stats.lua" returned an error:

### ISSUE THREAD

**Issue by tofic77** [ntop/ntopng#3230]
Script "/usr/share/ntopng/scripts/lua/if_stats.lua" returned an error:

/var/lib/ntopng/plugins/alert_endpoints/nagios.lua:1: unexpected symbol near '<\135>'

Fresh install on Raspberry Pi with this procedure: http://packages.ntop.org/RaspberryPI/

**Comment by emanuele-f** [comment]
This is probably a duplicate of #3213 , adding `--community` should fix it.

**Comment by tofic77** [comment]
Ok, sorry i didn't find the issue #3213.

Thank you for your help.
