### ISSUE TITLE
SyntaxError: Unexpected token T in JSON at position #####

### ISSUE THREAD

**Issue by jasonamorrow** [ntop/ntopng#3234]
I currently get the error message "SyntaxError: Unexpected token T in JSON at position #####" when trying to view all hosts in hosts_stats.lua.

If I filter by VLAN the error only appears for one specific VLAN id.

I'm not seeing any related errors in the logs.

This is version 3.8.190204 - Community/Embedded Edition running on Raspbian Buster

**Comment by emanuele-f** [comment]
The ntopng version that you are using is outdated, please install the latest version from our repository (http://packages.ntop.org/RaspberryPI/) or from source.

**Comment by emanuele-f** [comment]
No further feedback received, please reopen if necessary.
