### ISSUE TITLE
Listen on both IPv4 and IPv6

### ISSUE THREAD

**Issue by bakerds** [ntop/ntopng#3235]
Per [this documentation](https://www.ntop.org/guides/ntopng/cli_options.html), it is possible to configure the web interface to listen on an IPv4 or an IPv6 address. However, when no address is specified (as in `-w 80`), ntopng listens only on 0.0.0.0 and does not listen on IPv6 at all. Ideally, ntopng would listen on both 0.0.0.0 and [::] in this mode.

To get it to listen on both protocols, we can specify multiple addresses like this: 
`--http-port "0.0.0.0:80,[2001:db8::1234]:80"`
It does not seem to accept the "any" IPv6 address [::].

ntopng 3.9.200114 (8629) - Enterprise Edition
Ubuntu 18.04.3 LTS

**Comment by simonemainardi** [comment]
IPv6 ANY_ADDRESS is correctly accepted. Remember to specify the port after the `[::]`

See for example:

```
 sudo ./ntopng -i en0 --disable-login 1 --dont-change-user -w "192.168.2.126:3000,[::]:3000"
...
24/Jan/2020 17:21:56 [HTTPserver.cpp:1324] HTTP server listening on 192.168.2.126:3000,[::]:3000
```

Then

```
curl "[::1]:3000"
<html>
<head>
<title>Moved</title>
</head>
<body>
<h1>Moved</h1>
<p>This page has moved to <a href="/lua/pro/dashboard.lua">/lua/pro/dashboard.lua</a>.</p>
</body>
</html>
```
