### ISSUE TITLE
Grafana Dashboard, Influxdb Source - Query/Schema for Device Classification

### ISSUE THREAD

**Issue by cawhite6** [ntop/ntopng#3238]
This may nto be so much an issue/bug as it is a question? I can't find any information on how the Device/Host OS classification is stored so I can query into Grafana as a panel/pie chart/etc?

Any direction is appreciated, influx knowledge is basic as ntop is tour only product using it (everything else is mysql/mariadb)

**Comment by emanuele-f** [comment]
You can find a description of the metrics used by ntopng here: https://www.ntop.org/guides/ntopng/api/timeseries/metrics.html . Should you have other questions, please open a new issue.
