### ISSUE TITLE
Implementation of flow score

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3240]
Each flow has a numerical (>= 0) value named score that summarizes all the issues related to the flow. In essence every flow has already a bitmap of issues, such as high retransmission rate, or communication with blacklisted hosts. The score is a way to move from this high-level and non-numerical, to a numerical value that can be used to account anomalies. A high score value means that the flow has critical issues whereas a 0 score means that flow is good and no issue has been reported.

The flow score is made up of several components. Each issue reported on the flow increases the flow score. High score numbers mean that the flow has been "special" (in a bad way) and thus worth to be analysed more than others.
The flow score is computed as the SUM(score of each individual flow issue).

The score of individual flow issues depends on the severity of the problem. For instance suppose to take into account a script that checks TCP retransmissions. Supposing that the max score value accounted by this script is 10. A low retransmission rate can contribute to the flow score with a value of 2 (hence close to the bottom value),  whereas a severe retransmission rate will be 10 that is the max this script can account. Hence
- the score value is NOT a static value, but it can have a range of values for each issue reported on the flow
- the flow score is a non-negative number that needs to be saved in nIndex and reported in the ntopng GUI so that people can sort flows according to their score
- each script is free to decide the range of the score value it can use, even though it would be nice to have a homogenous score range so that summarising the flow score is possible

**Comment by emanuele-f** [comment]
The flow score is now implemented into the enterprise version of ntopng. The `flow.setStatus/flow.triggerStatus` functions have been extended with 3 positional parameters, flow_score, cli_score and srv_score, which allows a user script to specify the scores while setting a flow status. The cli_score and srv_score are then transferred to the flow peers according to the logic described in #3241.

The score of the active flows is shown as a sortable column in the Active Flows table.

![2020-01-17_09-56](https://user-images.githubusercontent.com/5488003/72599051-ed2ea480-3908-11ea-9d6c-a6233bb64858.png)

It is also visible into the flow details.
