### ISSUE TITLE
Implementation of host score

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3241]
This ticket depends in #3240 so that ticket must be implemented prior to work on this.

- Host score definition
Each host (network, AS...) has a numerical non-negative value used to store the score value. This value is computed over a 1-minute (configurable in the future but for the time being let's assume it's a single non-configurable value) time frame. At second 0 the value of the score is 0, then for all flows that expire within 60 seconds, the host score is increased. When 60 seconds are past since the initial flow score computation, this flow score value is "ready" and it can be used to overwrite that previous-minute score value. It does not make sense to show partial (e.g. 40 seconds) score values. This means that each host has a current score value (computed in the previous score timeframe),and an ongoing score that is being computed on the current minute that that is hidden to the user until the minute is past. The host score is computed for all hosts, both remote and local, with the difference that on local hosts the score value is saved on the timeseries database, whereas the remote score value is volatile and not written on a database.

- Host score implementation
When the flow score is computed, the various flow issues are summarised per flow. In #3240 there is a example of TCP retransmission. Now the question is: how to move from a flow score to a host score? Consider for a second the above example: ntopng knows if the retransmission happen on both directions (client->server and server->client) or just one one direction (e.g. client -> server). Suppose to have a severe retransmission on client->server, and almost no retransmission on the other direction. In this case on the client the host score is increase by 10 (host severity), where's in the server score of 2 (low severity); this while the flow score is still 10 as in the #3240 example. This example shows that 
- the flow score and that host score are computed differently 
- the flow score does not reset every minute, whereas the host score does
- the host score is determined by the flow script that accounts the value for each peer (client and server) whose value can be determined by the direction, or by the flow conditions

it is very important to make sure the score implementation satisfies these requirements while keeping the flow script simple enough to be written by users with limited knowledge of the ntopng architecture

**Comment by emanuele-f** [comment]
The host score is now implemented into the enterprise version of ntopng. The client/server score is first accounted into the flow once `flow.setStatus/flow.triggerStatus` is called as explained in #3240. Then, in minute.lua, the host user script "Score" is responsible for transferring the peers score from the flow into the hosts. In particular, the Score script implements the following algorithm:

1. It first iterates the active flows and increments a shadow counter in the flow peers with the peer score (see `interface.computeHostsScore`).
2. For each host, `host.refreshScore()` is called. This moves the shadow score counter to the "effective" counter, making it visible into the gui.
3. The user script also creates the host score timeseries (for the local hosts only) and checks if the configured score threshold is exceeded.

![2020-01-17_10-33](https://user-images.githubusercontent.com/5488003/72600938-667bc680-390c-11ea-8296-8e5ec293b88a.png)

Short flows are accounted differently as they may not be iterated by the Score user script in minute.lua . Once such a short flow expires, its cli/srv scores are used to increment the `new_idle_flow_score` on the host, which is then added to the shadow host score during the next Score user script execution.

Active hosts can be sorted by score by selecting the Score column as the extract column in the active hosts view:

![2020-01-17_09-59](https://user-images.githubusercontent.com/5488003/72601488-68925500-390d-11ea-81d2-daddbe6ed71a.png)

The score timeseries can be accessed from the host charts:

![2020-01-17_10-42](https://user-images.githubusercontent.com/5488003/72601648-bd35d000-390d-11ea-8b83-f2e4aa6ecf69.png)
![2020-01-17_10-42_1](https://user-images.githubusercontent.com/5488003/72601657-c161ed80-390d-11ea-926f-f5083c229334.png)
