### ISSUE TITLE
raspberrypi.localdomain has sent 59 DNS requests but received 0 DNS replies

### ISSUE THREAD

**Issue by jpgpi250** [ntop/ntopng#3248]
I'm running ntopng (packet filter port 53) on a raspberry pi 3B with pihole + unbound as a recursive resolver.
I'm getting a lot of warnings like:
Host raspberrypi.localdomain has sent 196 DNS requests but received 0 DNS replies [5 minutes ratio: 0%]
Is there a way to see which DNS request has been made that remains unanswered, if NOT, would it be possible to see the unanswered requests made, including the request and the DNS server the request was made to, preferably by using a link in the warning message.

Thank you for your time and effort.

**Comment by emanuele-f** [comment]
Currently this information is missing. However you can implement your own "user script" to export such information. Please check out https://www.ntop.org/guides/ntopng/plugins/index.html for more information (docs are work in progress).
