### ISSUE TITLE
Reset webgui admin password

### ISSUE THREAD

**Issue by oktavianq** [ntop/ntopng#3249]
I forgot the administrator password for gui in ntopng. I carried out the following commands
systemctl stop ntopng.service 
redis-cli del ntopng.user.admin.password
After this i  running these commands, 
systemctl start ntopng.service 
I started the server without errors, but  the default password  not work.
I see ntopng process when i run ps -A

**Comment by emanuele-f** [comment]
Please follow these instructions in this exact order:
1. ntopng must be running
2. `redis-cli del ntopng.user.admin.password`
3. `sudo systemctl restart ntopng`

**Comment by oktavianq** [comment]
Solved .Many thx :)

**Comment by emanuele-f** [comment]
You are welcome
