### ISSUE TITLE
Show Total Bytes unit formatted in historical top flows (enhancement)

### ISSUE THREAD

**Issue by eddy-minet** [ntop/ntopng#325]
In the 'host_details' page, 'historical' tab, in the top flows table (from MySQL historical datas) the  'Avg Thpt' column is expressed in unit (eg: Mbit) whereas the 'Bytes' column show raw bytes counter (eg: 256623947) wich is not so friendly to read...

**Comment by simonemainardi** [comment]
thanks, the enhancement has been included in the main dev branch. It will be available in the nightly builds starting from tomorrow.
