### ISSUE TITLE
Dummies guide to nedge dashboard reporting understanding traffic

### ISSUE THREAD

**Issue by wanderernxa** [ntop/ntopng#3254]
Hi,
I may have missed something but I am having a difficult time reading the traffic monitoring from the dashboard of NEdge. I have it installed in bridge mode and it works fine. Is there a simple dashboard someone can guide me to where I can see all the traffic that computers across the bridge are accessing? Like youtube, facebook, etc.. in a simple way to read and view. I just want to monitor it from a parents perspective so it needs to be simple enough to understand if someone is going to mischievous :) websites, etc.

thanks

**Comment by emanuele-f** [comment]
The traffic dashboard should already provide enough details about the top active applications. Regarding the blocked sites view, currently nEdge does not report such information. It just redirects the user to the blocked page if a child safe DNS is in use. However you can check the top HTTP sites visited by a local host in the `Sites` tab under the host details.
