### ISSUE TITLE
Lua script failed + license

### ISSUE THREAD

**Issue by oktavianq** [ntop/ntopng#3256]
1. First problem  . I got this error 20/Jan/2020 11:55:00 [AlertCheckLuaEngine.cpp:167] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:420: attempt to index a nil value (upvalue 'score_utils')]

v.3.9.200120    [Enterprise/Professional build]
GIT rev:        dev:b78160427b9bacc5d6760fb8ba3c73f95e5c0187:20200120
Pro rev:        r2663
Built on:       Ubuntu 18.04.3 LTS
System Id:      4ADBE7799205A1D6
Platform:       x86_64
Edition:        Enterprise
License Type:   Time-Limited [Empty license file]
Validity:       Until Mon Jan 20 12:06:09 2020

Second problem: I added option --community  to ntopng.conf , but as you can see command ntopng --version dont see this. However, the web interface shows ntopng Community Edition v.3.9.200120 correctly

**Comment by emanuele-f** [comment]
Fixed in dd8643ad793ff4c808672abf051c10f6545165cd. A new package will be available in one hour.

**Comment by oktavianq** [comment]
Many thx :)
