### ISSUE TITLE
User scripts Applied To column is unclear

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3258]
An empty 'applied to' column is unclear. If applied to everything, one should write everything in italic and/or gray but just empty is not acceptable

![image](https://user-images.githubusercontent.com/3397663/72735285-c9cf5800-3b9b-11ea-9b5d-f1422241a4a9.png)

**Comment by gabryon99** [comment]
Fixed.

**Comment by simonemainardi** [comment]
Applied to default has no meaning

![image](https://user-images.githubusercontent.com/3397663/72880178-a7a21b00-3cfe-11ea-8d8c-acd106ff1d70.png)

for interface target, write all interfaces. for host targets, write all hosts, and so on.
