### ISSUE TITLE
Long menus should be scrollable

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3261]
When a long menu appears, it goes below the page

![image](https://user-images.githubusercontent.com/3397663/72736335-c6d56700-3b9d-11ea-904a-57703b46789f.png)

It must:
- open below the name

![image](https://user-images.githubusercontent.com/3397663/72736415-f1272480-3b9d-11ea-84b7-97896cc1242f.png)

**Comment by gabryon99** [comment]
Which pages are exactly?

**Comment by simonemainardi** [comment]
flows_stats.lua, menu applications
then any chart with a dropdown (see the historical page of if_stats.lua)

**Comment by gabryon99** [comment]
I replaced all occurrences (except for `menu.lua`) of `dropdown-menu` with `dropdown-menu scrollable-dropdown`, so when a menu has a height greater than `16rem` the scrollbar will be enabled.
The css class is this:
```css
.scrollable-dropdown {
  max-height: 16rem;
  height: auto;
  overflow-y: auto;
}
```

**Comment by simonemainardi** [comment]
seems it has no effect at least using the latest source

![image](https://user-images.githubusercontent.com/3397663/72796407-8fb79200-3c3f-11ea-9c78-ff0c64edbb5b.png)


note:

when I click traffic

![image](https://user-images.githubusercontent.com/3397663/72796444-9ba35400-3c3f-11ea-8025-8726b3b9c9ad.png)


I would expect the dropdown to open below "Traffic" and not above as shown in the picture. Then, the dropdown should also be scrollable.

**Comment by simonemainardi** [comment]
Fixed.

To avoid long menus it is recommended to use css class `scrollable-droprown`, for example

```
<ul class="dropdown-menu scrollable-droprown">
```
