### ISSUE TITLE
Datetimepicker dropdown style

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3265]
In the charts page, the datetimepicker is not rendered properly

![image](https://user-images.githubusercontent.com/3397663/72737646-3a787380-3ba0-11ea-9b5d-ff26bc482f3a.png)

same in the flow alerts explorer

![image](https://user-images.githubusercontent.com/3397663/72737684-50863400-3ba0-11ea-8515-6cdb0c5d1e14.png)

it is requested to fix this

**Comment by gabryon99** [comment]
Fixed, the problem was a wrong width.
