### ISSUE TITLE
System freezes after update to v.3.9.200121

### ISSUE THREAD

**Issue by PawelConnectio** [ntop/ntopng#3270]
Like in title. System debian 9 freezes almost instantly afrer reboot .This behaviour  i have noticed after update to v.3.9.200121 . 
Another issue  :
`
  InfluxDB Export Failure | Points dropped. Could not send them to 'http://172.25.1.36:8086'.
`

**Comment by cardigliano** [comment]
@PawelConnectio could you provide more details about the configuration? (e.g. PF_RING drivers, ntopng configuration, etc). Thank you.

**Comment by PawelConnectio** [comment]
ntopng.conf :
`-x= 5000000
-X= 2000000
-i="view:tcp://127.0.0.1:5555,tcp://127.0.0.1:5556,tcp://127.0.0.1:5554"
-i="tcp://127.0.0.1:5555"
-i="tcp://127.0.0.1:5556"
-i="tcp://127.0.0.1:5554"`
and nprobe config files 
`-zmq="tcp://127.0.0.1:5554"
-T="@NTOPNG@"
-i=none
--collector-port=2056
--lifetime-timeout=5
--idle-timeout=5
--zmq="tcp://127.0.0.1:5555"
-T="@NTOPNG@"
-i=none
--collector-port=2057
--lifetime-timeout=5
--idle-timeout=5
--zmq="tcp://127.0.0.1:5556"
-T="@NTOPNG@"
-i=none
--collector-port=2058
--lifetime-timeout=5
--idle-timeout=5
`
I can only use system in recovery mode in debian . Wierd thing is that when i start manualy  influxdb ntopng and nprobe work

**Comment by PawelConnectio** [comment]
fixed in v.3.9.200122
