### ISSUE TITLE
Problem updating with centos

### ISSUE THREAD

**Issue by phoenixryan** [ntop/ntopng#3272]
When I run yum update

yum update
Loaded plugins: refresh-packagekit, security
Setting up Update Process
ntop                                                                                                                              | 2.9 kB     00:00
ntop/primary_db                                                                                                                   | 7.9 kB     00:00
ntop-noarch                                                                                                                       | 2.9 kB     00:00
ntop-noarch/primary_db                                                                                                            | 4.1 kB     00:00
saltstack-zeromq4                                                                                                                 | 3.0 kB     00:00
saltstack-zeromq4/primary_db                                                                                                      | 4.8 kB     00:00
http://www1.ngtech.co.il/rpm/centos/6/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
To address this issue please refer to the below wiki article

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

Error: Cannot retrieve repository metadata (repomd.xml) for repository: squid. Please verify its path and try again

the actual url is wrong should be repo not rpm

When I browse website it should be http://www1.ngtech.co.il/repo/blah blah blah

**Comment by simonemainardi** [comment]
we are not affiliated nor related nor we distribute via `http://www1.ngtech.co.il`. Please, check our centos repos.
