### ISSUE TITLE
Every time I attempt to go to NTOPNG via a browser it freezes the system, requiring a reboot

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#3275]
Hi

Just upgraded to this version:

![image](https://user-images.githubusercontent.com/48565067/72834784-8508f700-3c57-11ea-8b93-dd552d3b3d4e.png)

Now when I attempt to go to the Ntopng login screen using a browser I can't get to it, and the whole Operating System (on a ProxMox Ubuntu VM) freezes.

Please help, thanks

**Comment by PawelConnectio** [comment]
i have same issue !

**Comment by cardigliano** [comment]
A new build is available, please update (make sure pfring-dkms is also getting updated) and let us know if you are still able to reproduce this. Thank you.

**Comment by StewAlexander-com** [comment]
I updated my Ubuntu system today using the ```$ sudo apt update``` and ```$ sudo apt upgrade``` commands, and it is now working as expected.

Thank you ...

**Comment by StewAlexander-com** [comment]
Closing as fixed.
