### ISSUE TITLE
Add In Bytes and In Packets in DB Flows Dump

### ISSUE THREAD

**Issue by alberk8** [ntop/ntopng#328]
Hi,

Would it be possible to add two more columns in the DataBase table for "in" bytes and packets?   I know that the information is available in the json column but is quite expensive to extract via UDF.  Thank you.

**Comment by simonemainardi** [comment]
hi, we are not planning to add extra columns to the database table. We are trying to keep the schema as lean as possible as additional columns may impact performance negatively.

what I can suggest you is to create a trigger into the database that extract the json every time an insertion is done, placing the extracted values in separate tables.

mysql supports the json type. native json columns are supported from mysql 5.7. percona has json support as well.
