### ISSUE TITLE
User Script Column Enabled Should be Removed

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3282]
Column Enabled should be removed and an extra button should be placed under the actions:

![image](https://user-images.githubusercontent.com/3397663/72879481-3c0b7e00-3cfd-11ea-9b29-bc63ae33269c.png)

A disabled script will have an 'enable' button. An enabled script will have a 'disable' button.

**Comment by emanuele-f** [comment]
Note: it is necessary to always show the enable/disable button, even for config with granularities

**Comment by emanuele-f** [comment]
additional lua api implemented in 60b739ed5eaa0dbbd90cfe4f6e27bb974191ee49

**Comment by emanuele-f** [comment]
Fixed in #3295
