### ISSUE TITLE
Plugins localization

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3285]
It is requested to add plugin strings translated to italian and provide a diff or a sort of a file with all the strings which also require a german translation

**Comment by emanuele-f** [comment]
As discussed internally, it's better for us to keep all the internal strings into a single file to easy the localization implementation and review process. Will need to move the existing user scripts strings back to the original configuration file

**Comment by emanuele-f** [comment]
Fixed in 2d7b7c86e60166c621086afdbc3b3387c0522dd8. The italian/german localization can be obtained with the `tools/localization/localize.sh` tool together with all the remaining strings to localize.

**Comment by emanuele-f** [comment]
Localization completion moved to #3321
