### ISSUE TITLE
Add Configuration for User Script Interface Load Threshold Alerts

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3292]
Currently,

The script can only be configured from the preferences

![image](https://user-images.githubusercontent.com/3397663/72899133-af28ea80-3d25-11ea-8b4e-3cc9d98e241a.png)

it is requested to modify the configuration of the user script so that the threshold (a value between 0 and 100) can be configured from the script page - now it only has an on/off preference.

Once this has been done, the corresponding configuration from the ntopng preferences can be removed.

**Comment by emanuele-f** [comment]
Implemented
