### ISSUE TITLE
Script fail flow.lua long_lived.lua

### ISSUE THREAD

**Issue by PawelConnectio** [ntop/ntopng#3314]
like in topic ,this error repeats constantly: 
`an 24 08:10:54 tor-cz-log03 ntopng: [AlertCheckLuaEngine.cpp:167] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [...b/ntopng/plugins/callbacks/interface/flow/long_lived.lua:46: attempt to index a nil value (local 'conf')]
Jan 24 08:10:54 tor-cz-log03 ntopng[939]: 24/Jan/2020 08:10:53 [AlertCheckLuaEngine.cpp:167] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [...b/ntopng/plugins/callbacks/interface/flow/long_lived.lua:46: attempt to index a nil value (local 'conf')]
`

**Comment by emanuele-f** [comment]
Are you using the latest ntopng version? Please post the output of `ntopng --version`

**Comment by PawelConnectio** [comment]
v.3.9.200124

**Comment by emanuele-f** [comment]
The issue may be linked to a previous configuration. Please use the "Reset Configuration" button to delete the existing configuration. I've also addressed this in c791fc1246fc06e48b33c40ff7a792ae7eed4c16 . A new package will be available in one hour.

**Comment by PawelConnectio** [comment]
maybe its stupid question but where is that button

**Comment by emanuele-f** [comment]
That has been added in the new package, please update ntopng.

**Comment by simonemainardi** [comment]
see button "Reset configuration"

![image](https://user-images.githubusercontent.com/3397663/73071736-e0372580-3eb3-11ea-9c09-d2d715631516.png)

**Comment by PawelConnectio** [comment]
after update and reset there is no errors at all !
