### ISSUE TITLE
【ntop nEdge latest 3.9 version】 Cloud not select language

### ISSUE THREAD

**Issue by Michiko0109** [ntop/ntopng#3315]
![add system user](https://user-images.githubusercontent.com/60252545/73054599-2c8f5f00-3ece-11ea-8230-8cff49e9fd41.png)

I am using nEdge  latest 3.9 version.
I found issue that I could not select language.
I created another user in addition to the default user 'admin'.
However, I could not select language using an another user.

**Comment by emanuele-f** [comment]
nEdge only supports the english language right now. If you want to support the localization feature in other languages please contact us via http://www.ntop.org/support/need-help-2/contact-us .
