### ISSUE TITLE
User Script Categories Dropdown Fixes

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3318]
I've generalized the contents of the dropdown in https://github.com/ntop/ntopng/commit/0e2e8c61c492f7444811a844d3fcef8aee5f1015. Keep in mind that categories can change and can be updated so hardcoding them is not good.

Please address the following:
- this is broken as you are comparing a localized string: https://github.com/ntop/ntopng/pull/3313/files#diff-e48743a6229d29f1d444836d70026bb9R1238 changing the language will break the script
- do not show the filter if no category filter is applied
- show the category name and the filter when the filter is applied (without the 'Filter Catgories: ')

**Comment by gabryon99** [comment]
Merged #3317.
