### ISSUE TITLE
User Scripts errors in Apply To

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3322]
Let's say I have 2 confs as shown here:

![image](https://user-images.githubusercontent.com/3397663/73085266-b4756900-3ece-11ea-9e6f-3d7320387d72.png)

If I try and edit the 'apply to' of one conf, and set it equal to the 'apply to' of the other conf, I get an error and this is fine

![image](https://user-images.githubusercontent.com/3397663/73085365-dec72680-3ece-11ea-92c5-82c7460438fd.png)

however, from this point on, even if I set a new valid 'apply to', the error doesn't recover:

![image](https://user-images.githubusercontent.com/3397663/73085409-f2728d00-3ece-11ea-8fe0-b78846fdac04.png)

**Comment by gabryon99** [comment]
When the request fails a new `csrf `token it must be sent, however the response doesn't contain the new `csrf` token so the new request fails again.
