### ISSUE TITLE
Influxdb Export failure

### ISSUE THREAD

**Issue by PawelConnectio** [ntop/ntopng#3327]
Hi, 
error Inluxdb Export failure shows from about 3-4 releases ago. Current version : 
3.9.200124 (8746) -  Enterprise Edition
![Bez tytułu](https://user-images.githubusercontent.com/59692777/73156321-bb25fb00-40dd-11ea-836d-1dd335faf7f0.jpg)

**Comment by emanuele-f** [comment]
Can you post a screenshot of the InfluxDB status page?

**Comment by PawelConnectio** [comment]
![2020-01-27 10_12_54-Welcome to ntopng](https://user-images.githubusercontent.com/59692777/73162229-a487a000-40ed-11ea-8d50-982fc467a5b7.png)

**Comment by emanuele-f** [comment]
Have you restarted ntopng after the issue occurred? It seems like the database is not able to keep up with the writes. When such drops occurs, please try to login into the influxdb command line and check if it responds to basic queries

**Comment by PawelConnectio** [comment]
Yes, i tryed restart few times - without any change. I think that housekeeping have to do with this .Below inluxdb RAM usage , its reach allmost max
![2020-01-27 10_21_09-Welcome to ntopng](https://user-images.githubusercontent.com/59692777/73162881-114f6a00-40ef-11ea-9e0c-d21d465a46b2.png)

**Comment by emanuele-f** [comment]
You have a very high series cardinality, you should try to reduce the amount of timeseries written to the database by disabling some timeseries into the ntopng preferences. Please try to update InfluxDB to the latest version and/or contact the InfluxDB support

**Comment by emanuele-f** [comment]
Closing as no further feedback has been received.
