### ISSUE TITLE
ntopng / nprobe are not starting

### ISSUE THREAD

**Issue by airtwist1** [ntop/ntopng#333]
Hi,

i´ve prolbems to get ntopng and nprobe to start. The System was running quite nice the last two month, after a apt-get update the both services won´t start.

When i try to start ntopng in the nbox ui it starts for 2 seconds and stop again.

Here is the syslog output:
Dec 31 11:55:01 fn-ntop CRON[15750]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Dec 31 11:56:01 fn-ntop CRON[15753]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Dec 31 11:57:01 fn-ntop CRON[15756]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Dec 31 11:58:01 fn-ntop CRON[15759]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Dec 31 11:59:01 fn-ntop CRON[15762]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Dec 31 12:00:01 fn-ntop CRON[17191]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Dec 31 12:00:04 fn-ntop logger: ntopng force-start
Dec 31 12:00:07 fn-ntop kernel: [ 3121.124494] ntopng[17376]: segfault at 7fc9b0004ec8 ip 000000000045669f sp 00007fa9c51c6b20 error 4 in ntopng[400000+203000]
Dec 31 12:00:43 fn-ntop logger: nprobe stop eth1
Dec 31 12:00:44 fn-ntop logger: nprobe stop none
Dec 31 12:00:50 fn-ntop logger: ntopng force-start
Dec 31 12:01:01 fn-ntop CRON[19469]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Dec 31 12:02:01 fn-ntop CRON[20434]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Dec 31 12:03:01 fn-ntop CRON[21133]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Dec 31 12:04:01 fn-ntop CRON[21572]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Dec 31 12:04:25 fn-ntop kernel: [ 3379.154306] ntopng[19092]: segfault at 7f924c004eb0 ip 00000000004562d1 sp 00007f7255984ae0 error 4 in ntopng[400000+203000]
Dec 31 12:05:01 fn-ntop CRON[23048]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Dec 31 12:06:01 fn-ntop CRON[23505]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Dec 31 12:07:01 fn-ntop CRON[23788]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Dec 31 12:08:01 fn-ntop CRON[24139]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Dec 31 12:09:01 fn-ntop CRON[24490]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Dec 31 12:09:43 fn-ntop logger: ntopng force-start
Dec 31 12:10:01 fn-ntop CRON[25831]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Dec 31 12:10:11 fn-ntop logger: ntopng stop
Dec 31 12:10:18 fn-ntop logger: ntopng force-start
Dec 31 12:10:23 fn-ntop kernel: [ 3737.126008] ntopng[26494]: segfault at 7f7a50004ec8 ip 000000000045669f sp 00007f5a5bffbb20 error 4 in ntopng[400000+203000]
Dec 31 12:10:37 fn-ntop logger: nprobe force-start none
Dec 31 12:10:37 fn-ntop kernel: [ 3750.301266] nprobe[27211]: segfault at 7 ip 00007f42ad7c4a03 sp 00007fffb29e1780 error 4 in libc-2.19.so[7f42ad779000+1bb000]
Dec 31 12:11:01 fn-ntop CRON[28200]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Dec 31 12:12:01 fn-ntop CRON[28870]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Dec 31 12:13:01 fn-ntop CRON[29639]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Dec 31 12:14:01 fn-ntop CRON[30356]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)

Here is the ntopng log:

31/Dec/2015 12:00:50 [NetworkInterface.cpp:1417] Started packet polling on interface eth1 [id: 2]...
31/Dec/2015 12:00:50 [NetworkInterface.cpp:1413] Setting affinity of interface tcp://127.0.0.1:5556 to core 1
31/Dec/2015 12:00:50 [NetworkInterface.cpp:1417] Started packet polling on interface tcp://127.0.0.1:5556 [id: 3]...
31/Dec/2015 12:00:50 [CollectorInterface.cpp:94] Collecting flows on tcp://127.0.0.1:5556
31/Dec/2015 12:09:43 [Ntop.cpp:929] Setting local networks to 213.95.255.224/27,213.95.82.32/28
31/Dec/2015 12:09:43 [Redis.cpp:106] Successfully connected to redis 127.0.0.1:6379@0
31/Dec/2015 12:09:43 [NtopPro.cpp:119] [LICENSE] Reading license from /etc/ntopng.license
31/Dec/2015 12:09:43 [PF_RINGInterface.cpp:52] Reading packets from PF_RING v.6.3.0 interface eth1...
31/Dec/2015 12:09:43 [Ntop.cpp:1148] Registered interface eth1 [id: 2]
31/Dec/2015 12:09:43 [Ntop.cpp:1148] Registered interface tcp://127.0.0.1:5556 [id: 3]
31/Dec/2015 12:09:43 [Ntop.cpp:1161] Registered interface view eth1 [id: 2]
31/Dec/2015 12:09:43 [Ntop.cpp:1161] Registered interface view tcp://127.0.0.1:5556 [id: 3]
31/Dec/2015 12:09:43 [Utils.cpp:299] User changed to nobody
31/Dec/2015 12:09:43 [main.cpp:241] PID stored in file /var/tmp/ntopng.pid
31/Dec/2015 12:09:43 [HTTPserver.cpp:460] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
31/Dec/2015 12:09:43 [HTTPserver.cpp:503] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
31/Dec/2015 12:09:43 [HTTPserver.cpp:506] HTTP server listening on port 3000
31/Dec/2015 12:09:43 [main.cpp:287] Working directory: /storage/ntopng
31/Dec/2015 12:09:43 [main.cpp:289] Scripts/HTML pages directory: /usr/share/ntopng
31/Dec/2015 12:09:43 [Ntop.cpp:256] Welcome to ntopng x86_64 v.2.3.151231 - (C) 1998-15 ntop.org
31/Dec/2015 12:09:43 [Ntop.cpp:261] Built on Ubuntu 14.04.3 LTS
31/Dec/2015 12:09:43 [PeriodicActivities.cpp:53] Started periodic activities loop...
31/Dec/2015 12:09:43 [RuntimePrefs.cpp:32] Dumping alerts into syslog
31/Dec/2015 12:09:43 [NtopPro.cpp:233] [LICENSE] ntopng systemId: 68C0A00E5905A1EF
31/Dec/2015 12:09:43 [NtopPro.cpp:244] [LICENSE] ntopng license: 04D7A19D971D1385FC8CBD5C3F0FFA69147966686315CB4DCA
31/Dec/2015 12:09:43 [NtopPro.cpp:265] [LICENSE] Maintenance is available until Sun Nov 20 19:34:23 2016 [325 days left]
31/Dec/2015 12:09:43 [Ntop.cpp:512] Adding 10.100.100.0/24 as IPv4 local network for eth1
31/Dec/2015 12:09:43 [Ntop.cpp:542] Adding fe80::250:56ff:febd:cdbc/64 as IPv6 local network for eth1
31/Dec/2015 12:09:43 [NetworkInterface.cpp:1417] Started packet polling on interface eth1 [id: 2]...
31/Dec/2015 12:09:43 [NetworkInterface.cpp:1413] Setting affinity of interface tcp://127.0.0.1:5556 to core 1
31/Dec/2015 12:09:43 [NetworkInterface.cpp:1417] Started packet polling on interface tcp://127.0.0.1:5556 [id: 3]...
31/Dec/2015 12:09:43 [CollectorInterface.cpp:94] Collecting flows on tcp://127.0.0.1:5556
31/Dec/2015 12:10:11 [main.cpp:37] Shutting down...
31/Dec/2015 12:10:12 [main.cpp:34] Ok I am leaving now
31/Dec/2015 12:10:18 [Ntop.cpp:929] Setting local networks to 213.95.255.224/27,213.95.82.32/28
31/Dec/2015 12:10:18 [Redis.cpp:106] Successfully connected to redis 127.0.0.1:6379@0
31/Dec/2015 12:10:18 [NtopPro.cpp:119] [LICENSE] Reading license from /etc/ntopng.license
31/Dec/2015 12:10:18 [PF_RINGInterface.cpp:52] Reading packets from PF_RING v.6.3.0 interface eth1...
31/Dec/2015 12:10:18 [Ntop.cpp:1148] Registered interface eth1 [id: 2]
31/Dec/2015 12:10:18 [Ntop.cpp:1148] Registered interface tcp://127.0.0.1:5556 [id: 3]
31/Dec/2015 12:10:18 [Ntop.cpp:1161] Registered interface view eth1 [id: 2]
31/Dec/2015 12:10:18 [Ntop.cpp:1161] Registered interface view tcp://127.0.0.1:5556 [id: 3]
31/Dec/2015 12:10:18 [Utils.cpp:299] User changed to nobody
31/Dec/2015 12:10:18 [main.cpp:241] PID stored in file /var/tmp/ntopng.pid
31/Dec/2015 12:10:18 [HTTPserver.cpp:460] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
31/Dec/2015 12:10:18 [HTTPserver.cpp:503] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
31/Dec/2015 12:10:18 [HTTPserver.cpp:506] HTTP server listening on port 3000
31/Dec/2015 12:10:18 [main.cpp:287] Working directory: /storage/ntopng
31/Dec/2015 12:10:18 [main.cpp:289] Scripts/HTML pages directory: /usr/share/ntopng
31/Dec/2015 12:10:18 [Ntop.cpp:256] Welcome to ntopng x86_64 v.2.3.151231 - (C) 1998-15 ntop.org
31/Dec/2015 12:10:18 [Ntop.cpp:261] Built on Ubuntu 14.04.3 LTS
31/Dec/2015 12:10:18 [PeriodicActivities.cpp:53] Started periodic activities loop...
31/Dec/2015 12:10:18 [RuntimePrefs.cpp:32] Dumping alerts into syslog
31/Dec/2015 12:10:18 [NtopPro.cpp:233] [LICENSE] ntopng systemId: 68C0A00E5905A1EF
31/Dec/2015 12:10:18 [NtopPro.cpp:244] [LICENSE] ntopng license: 04D7A19D971D1385FC8CBD5C3F0FFA69147966686315CB4DCA
31/Dec/2015 12:10:18 [NtopPro.cpp:265] [LICENSE] Maintenance is available until Sun Nov 20 19:34:23 2016 [325 days left]
31/Dec/2015 12:10:18 [Ntop.cpp:512] Adding 10.100.100.0/24 as IPv4 local network for eth1
31/Dec/2015 12:10:18 [Ntop.cpp:542] Adding fe80::250:56ff:febd:cdbc/64 as IPv6 local network for eth1
31/Dec/2015 12:10:18 [NetworkInterface.cpp:1417] Started packet polling on interface eth1 [id: 2]...
31/Dec/2015 12:10:18 [NetworkInterface.cpp:1413] Setting affinity of interface tcp://127.0.0.1:5556 to core 1
31/Dec/2015 12:10:18 [NetworkInterface.cpp:1417] Started packet polling on interface tcp://127.0.0.1:5556 [id: 3]...
31/Dec/2015 12:10:19 [CollectorInterface.cpp:94] Collecting flows on tcp://127.0.0.1:5556

Here is the nprobe log output:
31/Dec/2015 11:08:11 [nprobe.c:3184] Valid nProbe license found
31/Dec/2015 11:08:11 [nprobe.c:3926] WARNING: If you want to preserve the -M value, please specify -w before -M
nprobe: unrecognized option '--mysql'
31/Dec/2015 11:08:11 [nprobe.c:4550] WARNING: Unrecognized option '(null)' 
31/Dec/2015 11:08:11 [nprobe.c:4586] WARNING: The output interfaceId is set to 0: did you forget to use -Q perhaps ?
31/Dec/2015 11:08:11 [nprobe.c:4589] WARNING: The input interfaceId is set to 0: did you forget to use -u perhaps ?
31/Dec/2015 11:08:11 [nprobe.c:4681] Welcome to nProbe v.7.3.151231 ($Revision: 4765 $) for x86_64-unknown-linux-gnu with native PF_RING acceleration
31/Dec/2015 11:08:11 [nprobe.c:4691] Running on Ubuntu 14.04.3 LTS
31/Dec/2015 11:08:11 [nprobe.c:4702] [LICENSE] nProbe SystemId: 68C0A00E5905A1EF
31/Dec/2015 11:08:11 [nprobe.c:4713] [LICENSE] nProbe License:  FE1073C3374198190538ED76DC96EFD41483090866D22DBA02
31/Dec/2015 11:08:11 [nprobe.c:4716] [LICENSE] nProbe Edition:  Standard [without PF_RING Acceleration]
31/Dec/2015 11:08:11 [nprobe.c:4746] [LICENSE] Maintenance is available until Fri Dec 30 10:41:06 2016 [364 days left]
31/Dec/2015 11:08:11 [nprobe.c:6709] Welcome to nProbe v.7.3.151231 for x86_64-unknown-linux-gnu
31/Dec/2015 11:08:11 [plugin.c:1009] 0 plugin(s) enabled
31/Dec/2015 11:08:11 [nprobe.c:6384] Non IPv4/v6 traffic is discarded according to the template
31/Dec/2015 11:08:11 [util.c:431] GeoIP: loaded AS config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNum.dat
31/Dec/2015 11:08:11 [util.c:441] GeoIP: loaded AS IPv6 config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNumv6.dat
31/Dec/2015 11:08:11 [nprobe.c:5253] Using packet capture length 128
31/Dec/2015 11:08:11 [nprobe.c:6882] IPv6 traffic will NOT be exported/accounted by this probe
31/Dec/2015 11:08:11 [nprobe.c:6883] due to configuration options (e.g. use NetFlow v9)
31/Dec/2015 11:08:11 [nprobe.c:7013] Capturing packets from interface eth1 [snaplen: 128 bytes]
31/Dec/2015 11:08:11 [util.c:4009] ERROR: Unable to bind ZMQ endpoint tcp://*:5556: Address already in use
31/Dec/2015 11:08:11 [util.c:3091] nProbe changed user to 'nobody'
31/Dec/2015 11:08:11 [nprobe.c:7223] nProbe started successfully
31/Dec/2015 12:00:43 [cache.c:1210] Redis Cache [0 total/0.0 get/sec][0 total/0.0 set/sec]
31/Dec/2015 12:00:43 [nprobe.c:394] Received shutdown request... [signal: 15]
31/Dec/2015 12:00:44 [engine.c:2639] About to flush hash (threadId 0)
31/Dec/2015 12:00:44 [engine.c:2641] Completed hash walk (thread 0)
31/Dec/2015 12:00:47 [cache.c:1210] Redis Cache [0 total/0.0 get/sec][0 total/0.0 set/sec]
31/Dec/2015 12:00:47 [nprobe.c:2505] Processed packets: 4110 (max bucket search: 1)
31/Dec/2015 12:00:47 [nprobe.c:2488] Fragment queue length: 0
31/Dec/2015 12:00:47 [nprobe.c:2514] Flow export stats: [0 bytes/0 pkts][0 flows/0 pkts sent]
31/Dec/2015 12:00:47 [nprobe.c:2524] Flow drop stats:   [0 bytes/0 pkts][0 flows]
31/Dec/2015 12:00:47 [nprobe.c:2529] Total flow stats:  [0 bytes/0 pkts][0 flows/0 pkts sent]

i´ve two valid license for ntop and nprobe. 
Hope someone can give me a advice to solve this issue

thanks
Jean

**Comment by lmangani** [comment]
@airtwist1 could you also provide your OS version details please

**Comment by airtwist1** [comment]
Ubuntu 14.04.3 LTS \n \l

root@fn-ntop:~# uname -a
Linux fn-ntop 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
root@fn-ntop:~#

**Comment by lucaderi** [comment]
1. nProbe complains about --mysql and this is normal as you do not have nprobe with plugin support
2. nprobe complains about " ERROR: Unable to bind ZMQ endpoint tcp://*:5556: Address already in use": can you please check if you have another instance running?

What is scaring is instead that ntopng crashes. Can you please generate a core dump and send me via email both the core and the ntopng binary? This needs to be investigated.

**Comment by lucaderi** [comment]
@airtwist1 I have just fixed a bug on ntopng that could have caused the crash. In ~30 mins from now a new package should be ready. Please upgrade it first before sending me the info I have requested. Thank you.

**Comment by airtwist1** [comment]
Ciao luca,

many thanks for your support. I will try and give feedback.

Wish you guys from ntopng a happy new year.

Best regards

Jean 

Mit freundlichen Grüßen  / Best regards

Jean Ora

CEO

forcenet-logo_signatur

Force Net GmbH
Borsigstrasse 3-5
D-93092 Barbing
Tel:  (+49) 9401 - 53989 – 102

Fax.: (+49) 9401 – 53989 - 101
e-mail:  ora@forcenet.de
web:     www.forcenet.de
Amtsgericht Regensburg, HRB 13009
E.USt.Nr.: DE 282 293 041
Geschäftsführer: Jean Ora 
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. 
Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Von: Luca Deri [mailto:notifications@github.com] 
Gesendet: Donnerstag, 31. Dezember 2015 21:58
An: ntop/ntopng
Cc: FN Jean Ora
Betreff: Re: [ntopng] ntopng / nprobe are not starting (#333)

@airtwist1 https://github.com/airtwist1  I have just fixed a bug on ntopng that could have caused the crash. In ~30 mins from now a new package should be ready. Please upgrade it first before sending me the info I have requested. Thank you.

**Comment by airtwist1** [comment]
Ciao Luca,

the update worked, many thanks …. 

Mit freundlichen Grüßen  / Best regards

Jean Ora

CEO

forcenet-logo_signatur

Force Net GmbH
Borsigstrasse 3-5
D-93092 Barbing
Tel:  (+49) 9401 - 53989 – 102

Fax.: (+49) 9401 – 53989 - 101
e-mail:  ora@forcenet.de
web:     www.forcenet.de
Amtsgericht Regensburg, HRB 13009
E.USt.Nr.: DE 282 293 041
Geschäftsführer: Jean Ora 
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. 
Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Von: Luca Deri [mailto:notifications@github.com] 
Gesendet: Donnerstag, 31. Dezember 2015 21:58
An: ntop/ntopng
Cc: FN Jean Ora
Betreff: Re: [ntopng] ntopng / nprobe are not starting (#333)

@airtwist1 https://github.com/airtwist1  I have just fixed a bug on ntopng that could have caused the crash. In ~30 mins from now a new package should be ready. Please upgrade it first before sending me the info I have requested. Thank you.

**Comment by airtwist1** [comment]
the new update worked very well.....
after apt-get update apt-get update the system is now running as it should .... 
many thanks for the fast support

Wish all of you guys a happy new year !!!
