### ISSUE TITLE
Invalid sidebar collapse

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3337]
When the sidebar is collapsed, clicking on an icon it expands, the sidebar, then folvogin the link will move to a sidebar that is collapsed again. 
This is wrong. If the bar is collapsed it has to stay collapsed and not shrink/unshrink continuously.

When the sidebar is collapsed, a pop-up menu (as in past versions) should show-up to avoid this misbehaviour.

**Comment by gabryon99** [comment]
Now the sidebar sub-menus are shown by hovering on the own up-menu button.
