### ISSUE TITLE
Collapse button disappears based on the page instead of staying on screen

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3338]
![Screen Shot 2020-01-28 at 16 29 21](https://user-images.githubusercontent.com/4493366/73278104-653f7900-41eb-11ea-9b6d-ae2d494459b9.png)
![Screen Shot 2020-01-28 at 16 29 12](https://user-images.githubusercontent.com/4493366/73278105-653f7900-41eb-11ea-8cf8-94846737dcc8.png)

**Comment by gabryon99** [comment]
Now the sidebar is always collapsed to optimize the space available.
