### ISSUE TITLE
Report issue 

### ISSUE THREAD

**Issue by tezcangulnaz** [ntop/ntopng#334]
hi
I am getting following error message when i click report link  İ have deleted and recreated ntopng MYSQL Db but no succeed
can you please help me how to fix it

Jan  3 00:18:07 ntop ntopng: [Lua.cpp:4781] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/report.lua][/usr/share/ntopng/scripts/lua/pro/report.lua:319: attempt to perform arithmetic on field 'bytes.sent' (a nil value)]

**Comment by FabioHPT** [comment]
me too.... how to solve it ?
Thanks

**Comment by simonemainardi** [comment]
this has been fixed. please, update to the latest dev version.
