### ISSUE TITLE
Create white sidebar option

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3344]
The whole ntopng interface what based on white/gray, whereas the new sidebar is black/dark. It is requested to implement  white sidebar (not a whole application theme) so that people can stay with the old color or the new one. This has to be a per-user preference.

**Comment by gabryon99** [comment]
The white sidebar option exists. So it is necessary to implement, inside the user page, a toggle switch to enable/disable the sidebar color user prefers.

**Comment by lucaderi** [comment]
![Screen Shot 2020-01-29 at 09 19 47](https://user-images.githubusercontent.com/4493366/73339353-df6a0f00-4278-11ea-85c1-ac5efa5bddfc.png)

**Comment by gabryon99** [comment]
Ok, I close the issue.
