### ISSUE TITLE
Navbar doesn't wrap on small screens

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3348]
See after 'Flows:'...

![image](https://user-images.githubusercontent.com/3397663/73283304-33caab80-41f3-11ea-8d28-599d7756fb6e.png)

it is requested to wrap the navbar when there isn't enough space

also note the extra space between the header bar and the horizonal navbar. It is requested to remove it.

**Comment by lucaderi** [comment]
Fixed with the new smaller sidebar
