### ISSUE TITLE
Compilation warning

### ISSUE THREAD

**Issue by alberk8** [ntop/ntopng#335]
Hi,
I have the latest development code and getting is compilation warning on Ubuntu 14.04  and 15.1

v.2.3.151207 [Community Edition]
GIT rev:   dev:79987215556890ff60f03b3e8d08182ff299cce0:20151207

src/NetworkInterface.cpp: In member function ‘int NetworkInterface::getFlows(lua_State_, patricia_tree_t_, Host_, bool, char_, u_int32_t, u_int32_t, bool)’:
src/NetworkInterface.cpp:1951:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i=(int)toSkip, num=0; i<retriever.actNumEntries; i++) {
                                    ^
src/NetworkInterface.cpp:1953:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(++num >= maxHits) break;
                ^
src/NetworkInterface.cpp:1958:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(++num >= maxHits) break;
                ^
src/NetworkInterface.cpp: In member function ‘int NetworkInterface::getActiveHostsList(lua_State_, patricia_tree_t_, bool, bool, char*, u_int32_t, u_int32_t, bool)’:
src/NetworkInterface.cpp:2013:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i=(int)toSkip, num=0; i<retriever.actNumEntries; i++) {
                                    ^
src/NetworkInterface.cpp:2016:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(++num >= maxHits) break;
                ^
src/NetworkInterface.cpp:2022:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if(++num >= maxHits) break;

src/Flashstart.cpp: In member function ‘int Flashstart::parseDNSResponse(unsigned char_, int, sockaddr_in_)’:
src/Flashstart.cpp:351:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(i=0; (p[i] != 0) && (i < (rsp_len-sizeof(struct dns_header))); i++) {
                              ^
src/Flashstart.cpp: In member function ‘u_int Flashstart::recvResponses(u_int)’:
src/Flashstart.cpp:402:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if(len > sizeof(struct dns_header))

**Comment by simonemainardi** [comment]
thanks for reporting
