### ISSUE TITLE
Interface Link in Web GUI Error

### ISSUE THREAD

**Issue by unmanagedtn** [ntop/ntopng#3352]
Script "C:\Program Files\ntopng\scripts\lua\if_stats.lua" returned an error:
C:\Windows\Temp\ntopng\plugins\alert_endpoints\nagios.lua:1: unexpected symbol near '<\135>

Getting this with a valid interface, it has a long name and I don't know if that is the problem,,,

**Comment by unmanagedtn** [comment]
I have added the --community to the service also I am running windows....

**Comment by emanuele-f** [comment]
Same issue as #3213 . The fix will be available in the next windows build. For now, please use the --community option
