### ISSUE TITLE
Ntopng web UI very Slow to update

### ISSUE THREAD

**Issue by alberk8** [ntop/ntopng#336]
Hi,

I have compile the latest dev and have it running on Ubuntu 15.1 (Kernel 4.2). I have this slow UI update arises when I have more than 1500+ flows with 500+ hosts (internet line speed 10Mbps).  Ntop is set to log data to MySQL.  

From my troubleshooting, I think I have narrowed it down to the lua statement below.  When the DB logging is activated the slow downs happens.  I am not a C or C++ programmer but looking at the code I do feel that it has to do with contention between the DB and the UI accessing the flows information.  Below are some the info I have captured.

The code in the get_flows_data.lua that is slow to execute
res = interface.getFlowsInfo(host, sortColumn, perPage, to_skip, sOrder)

Would it be possible to decouple the dependency and speed up the UI.  Thank you

v.2.3.160104 [Community Edition]
GIT rev:   dev:f3cb6e55436138585abf2b9547de5bcffb2086ae:20160104
### ntopng.conf

-i=sm0
-l=1
-e=
-G=/var/run/ntopng.pid
-m="10.0.0.0/8,192.168.0.0/16,172.16.0.0/16"
-F=mysql;127.0.0.1;ntopng;flows;ntopng;ntoppass
###### 

$ iostat
Linux 4.2.0-19-generic (smartoptz)      01/04/2016      _x86_64_        (8 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.49    0.00    0.17    0.18    0.00   99.16

Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sda               3.54         0.20        44.88     429375   96901972
###### 

 $ free -h
             total       used       free     shared    buffers     cached
Mem:          3.8G       1.9G       1.9G        54M       175M       1.1G
-/+ buffers/cache:       664M       3.2G
Swap:         4.0G         0B       4.0G
##### 

top - 15:53:08 up 24 days, 23:44,  3 users,  load average: 1.30, 1.37, 1.56
Tasks: 165 total,   1 running, 164 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.0 us,  0.3 sy,  0.0 ni, 97.1 id,  1.5 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem:   4033540 total,  2010968 used,  2022572 free,   179836 buffers
KiB Swap:  4178940 total,        0 used,  4178940 free.  1149968 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
26330 nobody    20   0 1066664  43060  12352 S   3.3  1.1   0:38.13 ntopng
  726 redis     20   0   44156  15156   2624 S   0.7  0.4 148:45.83 redis-server
  992 mysql     20   0  708612 306512  14260 S   0.7  7.6  42:52.82 mysqld
29748 albert     20   0   24980   3036   2544 R   0.3  0.1   0:00.02 top
    1 root      20   0   37628   5700   3964 S   0.0  0.1   2:13.65 systemd
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.01 kthreadd
    3 root      20   0       0      0      0 S   0.0  0.0   0:02.41 ksoftirqd/0
    5 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:0H
    7 root      20   0       0      0      0 S   0.0  0.0  17:09.00 rcu_sched
    8 root      20   0       0      0      0 S   0.0  0.0   0:00.06 rcu_bh
    9 root      20   0       0      0      0 S   0.0  0.0   8:18.31 rcuos/0
   10 root      20   0       0      0      0 S   0.0  0.0   0:00.01 rcuob/0
###### 

$ wget http://172.16.1.30:3000/lua/get_flows_data.lua -O dat1
--2016-01-04 15:44:56--  http://127.0.0.1:3000/lua/get_flows_data.lua
Connecting to 127.0.0.1:3000... connected.
HTTP request sent, awaiting response... 302 Found
Location: / [following]
--2016-01-04 15:44:56--  http://127.0.0.1:3000/
Reusing existing connection to 127.0.0.1:3000.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘dat1’

dat1                         [             <=>                    ]  11.87K  11.6KB/s   in 11s

2016-01-04 15:45:07 (1.08 KB/s) - ‘dat1’ saved [12152]

**Comment by lucaderi** [comment]
@alberk8 I have just tested on my system

wget http://admin:password@localhost:3000/lua/get_flows_data.lua
--2016-01-04 17:36:29--  http://admin:_password_@localhost:3000/lua/get_flows_data.lua
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:3000... connected.
HTTP request sent, awaiting response... 302 Found
Location: /lua/login.lua?referer=/lua/get_flows_data.lua [following]
--2016-01-04 17:36:29--  http://admin:_password_@localhost:3000/lua/login.lua?referer=/lua/get_flows_data.lua
Connecting to localhost (localhost)|127.0.0.1|:3000... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘get_flows_data.lua’

```
[ <=>                                                                                                                                                                                                               ] 5,100       --.-K/s   in 0s      
```

2016-01-04 17:36:29 (15.7 MB/s) - ‘get_flows_data.lua’ saved [5100]

So it works for me. Can you please check if the DB isn't the bottleneck?

**Comment by alberk8** [comment]
Hi Luca,

Thanks.  It looks like the spinning HDD is the bottleneck.  I rerun the iostat with the command  "iostat -x 1" and it shows utilization 98-99%.  I will need to further test it once I get a SSD installed.
