### ISSUE TITLE
--collection-filter still not filtering single ip

### ISSUE THREAD

**Issue by dude2k5** [ntop/ntopng#3362]
Looking at issue #1782, having the exact same problem. Fixes mentioned dont do anything when applied.

Ive put --collection-filter=!192.168.1.86 as it's collecting data from itself, both in ntopng.conf and nprobe.conf. But they still show up in the web interface. Any ideas how to exlude it entirely.

**Comment by simonemainardi** [comment]
please show all the configurations and software versions used

**Comment by dude2k5** [comment]
It was my mistake, I think I had the config wrong earlier (when I posted it)

After doing more research, finally got the config working properly, then adding the filter seemed to work (I may have been applying it to ntopng instead of nprobe). 

My apologies, I will close this issue
