### ISSUE TITLE
Lua script failure

### ISSUE THREAD

**Issue by oktavianq** [ntop/ntopng#3364]
```
  30/Jan/2020 11:57:02 [LuaEngine.cpp:12514] WARNING: Script failure  [/usr/share/ntopng/scripts/lua/get_flows_data.lua][/usr/share/ntopng/scripts/lua/get_flows_data.lua:33:  attempt to index a nil value (local 'flows_stats')]
 30/Jan/2020 00:00:03 [LuaEngine.cpp:12009] WARNING: Script failure  [/usr/share/ntopng/scripts/callbacks/system/discover.lua][ a index a   valuestring]
```
---------
v.3.9.200129	[Enterprise/Professional build]
GIT rev:	dev:870cf4de0b33f30d88689e6f434f5021c005f87d:20200129
Pro rev:	r2688
Built on:	Ubuntu 18.04.3 LTS
System Id:	4ADBE7799205A1D6
Platform:	x86_64
Edition:	Enterprise
License Type:	Time-Limited [Empty license file]
Validity:	Until Thu Jan 30 12:12:08 2020

**Comment by MMelicher** [comment]
Seeing the same problem:
`Jan 30 14:51:50 netmon ntopng: [LuaEngine.cpp:12498] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/dashboard.lua][/usr/share/ntopng/scripts/lua/pro/dashboard.lua:17: attempt to index a nil value (field 'menu_entries')]
Jan 30 14:51:50 netmon ntopng[17188]: 30/Jan/2020 14:51:50 [LuaEngine.cpp:12498] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/dashboard.lua][/usr/share/ntopng/scripts/lua/pro/dashboard.lua:17: attempt to index a nil value (field 'menu_entries')]
`
v.3.9.200130	[Enterprise/Professional build]
GIT rev:	dev:6704ae50401625e1bb90b3a71f167d4aa731a88e:20200130
Pro rev:	r2690
Built on:	Debian GNU/Linux 10 (buster)
Platform:	x86_64
Edition:	Enterprise
License Type:	Permanent

**Comment by janvgils** [comment]
Also the same problem after an initial install.

`HTTP/1.1 500 Internal server error Content-Type: text/html Connection: close  Script "/usr/share/ntopng/scripts/lua/pro/dashboard.lua" returned an error:
/usr/share/ntopng/scripts/lua/pro/dashboard.lua:17: attempt to index a nil value (field 'menu_entries')`

`ntopng --version
v.3.9.200130	[Enterprise/Professional build]
GIT rev:	dev:6704ae50401625e1bb90b3a71f167d4aa731a88e:20200130
Pro rev:	r2690
Built on:	Debian GNU/Linux 10 (buster)
System Id:	3B930C12760B6B21
Platform:	x86_64
Edition:	Enterprise
License Type:	Time-Limited [Empty license file]
Validity:	Until Thu Jan 30 15:51:09 2020`

**Comment by emanuele-f** [comment]
Please check out the new package that will be available in one hour

**Comment by janvgils** [comment]
Thanks for the update, we will

**Comment by MMelicher** [comment]
Hi, the update fixed the problem. 

@emanuele-f  - fixed for me.




EDIT:


After the update:

> Thu Jan 30 16:21:56 2020] device enp1s0f0 left promiscuous mode
[Thu Jan 30 16:22:02 2020] device enp1s0f0 entered promiscuous mode
[Thu Jan 30 16:25:26 2020] second.lua[27228]: segfault at 0 ip 00005623ceb91fbc sp 00007f88767fb380 error 4 in ntopng[5623ceb83000+1f3000]
[Thu Jan 30 16:25:26 2020] Code: 48 89 75 f0 48 8b 45 f8 48 8b 55 f0 48 89 10 90 5d c3 55 48 89 e5 48 83 ec 20 48 89 7d f8 48 89 75 f0 48 89 55 e8 48 8b 45 f8 <48> 8b 00 48 89 c7 e8 c9 ce ff ff 89 c2 48 8b 45 e8 48 8d 35 8f 4c
[Thu Jan 30 16:25:27 2020] device enp1s0f0 left promiscuous mode
[Thu Jan 30 16:25:33 2020] device enp1s0f0 entered promiscuous mode
[Thu Jan 30 16:30:24 2020] second.lua[27699]: segfault at 0 ip 000056049a42ffbc sp 00007fd7e8ff8380 error 4 in ntopng[56049a421000+1f3000]
[Thu Jan 30 16:30:24 2020] Code: 48 89 75 f0 48 8b 45 f8 48 8b 55 f0 48 89 10 90 5d c3 55 48 89 e5 48 83 ec 20 48 89 7d f8 48 89 75 f0 48 89 55 e8 48 8b 45 f8 <48> 8b 00 48 89 c7 e8 c9 ce ff ff 89 c2 48 8b 45 e8 48 8d 35 8f 4c

**Comment by emanuele-f** [comment]
Can you provide a stack trace as explained in https://github.com/ntop/ntopng/blob/dev/doc/README.crash ?

**Comment by simonemainardi** [comment]
no feedback received. closing. reopen with the requested information if necessary.
