### ISSUE TITLE
i want login disable.

### ISSUE THREAD

**Issue by gaeunLEE** [ntop/ntopng#337]
my setting ntopng.conf
———————————————————————————–
# ntopng configure

–daemon
-G=/var/run/ntopng.pid
–user root
–http-port 3000
–disable-login
–data-dir /home/ntop/data
–httpdocs-dir /usr/share/ntopng/httpdocs
–scripts-dir /usr/share/ntopng/scripts
–callbacks-dir /usr/share/ntopng/scripts/callbacks
–redis localhost:6379
–interface eth1
–interface eth2
–local-networks "0.0.0./0"
———————————————————————————–
6 line # [ –disable-login ]
but, There is still a login is enabled.
I want to disable login.
Please inform us about how to disable login.

Why didn't you disable login?
what's this problem?

we used 'ntopng v.2.3.151228'

plz reply

**Comment by alberk8** [comment]
Hi,

I use the command below in the ntopng.conf which disable the login.  It is lowcase "L" equals one (1).  It works since version 1.99.
-l=1

**Comment by gaeunLEE** [comment]
hi, this is giosis

I purchased NTOPNG Pro.

I asked tou a question.
answer the question. plz
answer URL : https://github.com/ntop/ntopng/issues/338

[cid:image001.jpg@01D1486E.9207C440]

[cid:image002.jpg@01D1486E.9207C440]

**Comment by lucaderi** [comment]
@gaeunLEE I think Albert suggested you the correct answer to your question

**Comment by gaeunLEE** [comment]
ok , albert answer to my 1st question. 

but, 2nd question NOT answer. 
I want to see Report.
but, I keep getting an error message.
ERROR MESSAGE is...
[ HTTP/1.1 500 Internal server error Content-Type: text/html Connection: close   Script "/usr/share/ntopng/scripts/lua/pro/report.lua" returned an error: ]
[ /usr/share/ntopng/scripts/lua/pro/report.lua:319: attempt to perform arithmetic on field 'bytes.sent' (a nil value) ]

i can't see report.
how to see the report?

give me the solution.

**Comment by lucaderi** [comment]
This has been fixed yesterday too. Please file an issue per problem

**Comment by gnufan** [comment]
It's works for me e grazie mile luca per il suo lavoro
