### ISSUE TITLE
DNS Breakdown Insight

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#3371]
it will be appreciated to have the possibility to drill down the dns query that host done: positive and negative.
Scope: Malware analysis, dns troubleshooting, DNS Filtering and so on.

**Comment by lucaderi** [comment]
![Screen Shot 2021-01-12 at 10 04 07](https://user-images.githubusercontent.com/4493366/104292784-8ad99700-54bd-11eb-9f6d-a53963b78733.png)
Already implemented
