### ISSUE TITLE
Edit User Script -> Flow Error

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#3372]
When i try to access User Script -> Flow -> edit i receive this error
"DataTables warning: table id=scripts-config - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1"

**Comment by cardigliano** [comment]
<img width="1944" alt="Screen Shot 2020-02-04 at 09 40 15" src="https://user-images.githubusercontent.com/7548711/73729102-b6dc8c00-4734-11ea-8aa0-e40af87e1a21.png">

**Comment by emanuele-f** [comment]
Can you see errors into the ntopng log? Can you inspect the invalid JSON?

**Comment by emanuele-f** [comment]
@zimbawe998 any news?

**Comment by zimbawe998** [comment]
HI Emanuele,
I cannot have access because i have the problem specified on 3372.

**Comment by zimbawe998** [comment]
This is the error i see on the logs:

06/Feb/2020 21:48:00 [LuaEngine.cpp:12510] WARNING: Script failure 
[/usr/share/ntopng/scripts/lua/get_user_scripts.lua][...re/ntopng/scripts/lua/modules/user_scripts_templates.lua:138: 
attempt to index a nil value (field 'script_conf')]
06/Feb/2020 21:45:55 [LuaEngine.cpp:12510] WARNING: Script failure 
[/usr/share/ntopng/scripts/lua/get_user_scripts.lua][...re/ntopng/scripts/lua/modules/user_scripts_templates.lua:138: 
attempt to index a nil value (field 'script_conf')]
06/Feb/2020 21:45:45 [LuaEngine.cpp:12510] WARNING: Script failure 
[/usr/share/ntopng/scripts/lua/get_user_scripts.lua][...re/ntopng/scripts/lua/modules/user_scripts_templates.lua:138: 
attempt to index a nil value (field 'script_conf')]

**Comment by emanuele-f** [comment]
This should be fixed in 80ead5632938d1bd00646b8618870806e17b0c88, a new build will be available in one hour. If the fix does not work, please consider flushing the current data with:

1. ntopng is running
2. redis-cli del `ntopng.prefs.user_scripts.configsets_v2`
3. restart ntopng

**Comment by simonemainardi** [comment]
any news here?

**Comment by zimbawe998** [comment]
Resolved

Il giorno mar 11 feb 2020 alle ore 10:26 simonemainardi <
notifications@github.com> ha scritto:
