### ISSUE TITLE
Question about functionality ntopng

### ISSUE THREAD

**Issue by oktavianq** [ntop/ntopng#3373]
If the question is stupid, please bear with me and delete the thread :)
Is it possible to pass information from ntopng to the script?
More specifically, it is about asking ntopng about FLAG RST and SYN statistics on a specific network interface over a specific period of time (example 30sec ?)

**Comment by emanuele-f** [comment]
Hi, you can extract such information from the ntopng historical data. Please check out:

![2020-02-04_16-07](https://user-images.githubusercontent.com/5488003/73756829-2156f180-4760-11ea-95be-a59ca5c758f6.png)

https://www.ntop.org/guides/ntopng/api/rest/examples.html#get-interface-data

**Comment by oktavianq** [comment]
Many thanks
