### ISSUE TITLE
Disable (specific) external alerts

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#3374]
ntopng collects external alerts from Suricata, some of them trigger too many alerts of the same type introducing a lot of nose. It would be nice to add the ability to hide specific alerts by disabling them with one click in the Alerts page (doing the same by commenting them in the Suricata ruleset would be much more complicated) , or at least set a minimum severity.

**Comment by simonemainardi** [comment]
@cardigliano can this be closed as part of the "disable alerts" capabilities?

**Comment by cardigliano** [comment]
The current capabilities help filtering alerts, but they do not completely address this. However I guess we can close this for the time being as I did not see people demanding for a more fine grained filtering.
