### ISSUE TITLE
Dark theme issues 

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#3375]
Time resolution buttons are not visible

<img width="1236" alt="Screen Shot 2020-02-04 at 09 49 29" src="https://user-images.githubusercontent.com/7548711/73730220-bb09a900-4736-11ea-9a10-d5d05d9c1fb9.png">

**Comment by cardigliano** [comment]
Hosts -> Host Explorer has a white canvas

<img width="1323" alt="Screen Shot 2020-02-04 at 10 13 17" src="https://user-images.githubusercontent.com/7548711/73730411-00c67180-4737-11ea-9eaa-a7844bbceda1.png">

**Comment by cardigliano** [comment]
Interface historical chart canvas overlaps 

<img width="1257" alt="Screen Shot 2020-02-04 at 09 49 53" src="https://user-images.githubusercontent.com/7548711/73730740-9b26b500-4737-11ea-9867-e7373c13d9ff.png">

**Comment by lucaderi** [comment]
See also #3399

**Comment by gabryon99** [comment]
Canvas and charts fixed: https://github.com/ntop/ntopng/commit/df48cb03f16736c4a181a6e845a9b44be7554b47
