### ISSUE TITLE
Traffic incorrectly classified as DHCP?

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3376]
![2020-02-04_10-20](https://user-images.githubusercontent.com/5488003/73731001-9fe76b00-472f-11ea-885e-fd2a8328eb0c.png)

**Comment by cardigliano** [comment]
It is likely this has been fixed (yesterday), I've been able to reproduce a similar issue with the unit test which is working now after the patch, however I've never seen this happening in ntopng (probably due to a limited number of flows/hour).
