### ISSUE TITLE
Unable to check license online

### ISSUE THREAD

**Issue by christianbj87** [ntop/ntopng#3378]
Hi, i cant check the licence online using a proxy.

 env | grep -i proxy
http_proxy=http://10.1.15.31:80
https_proxy=http://10.1.15.31:80

 nprobe -v

Welcome to nProbe v.8.6.200203 (r6343) for x86_64-unknown-linux-gnu
with native PF_RING acceleration.
Copyright 2002-18 ntop.org

Build OS:      CentOS Linux release 7.7.1908 (Core)
SystemID:      689ED9C776066B16
GIT rev:       8.6-stable:67c7296f177602e07b6d109f4200f7d2453d8b49:20200203
License:       Invalid nProbe license (/etc/nprobe.license) [License mismatch error]

sudo nprobe --nflite 2055 -i none -n 10.1.11.34:9996 --online-license-check
04/Feb/2020 09:43:39 [plugin.c:181] No plugins found in ./plugins
04/Feb/2020 09:43:39 [plugin.c:189] Loading 24 plugins [.so] from /usr/local/lib/nprobe/plugins
04/Feb/2020 09:43:39 [nprobe.c:2298] Contacting licensing server. Please hold on...
04/Feb/2020 09:50:01 [nprobe.c:4178] ERROR: Invalid nProbe license (/etc/nprobe.license) [Unable to check license online]
04/Feb/2020 09:50:01 [nprobe.c:4185] ERROR: *****************************************************
04/Feb/2020 09:50:01 [nprobe.c:4186] ERROR: **                                                 **
04/Feb/2020 09:50:01 [nprobe.c:4187] ERROR: **  Switching to DEMO MODE (missing valid license) **
04/Feb/2020 09:50:01 [nprobe.c:4188] ERROR: **                                                 **
04/Feb/2020 09:50:01 [nprobe.c:4189] ERROR: **  Purchase your nProbe license at                **
04/Feb/2020 09:50:01 [nprobe.c:4190] ERROR: **       https://shop.ntop.org/                    **
04/Feb/2020 09:50:01 [nprobe.c:4191] ERROR: **                                                 **
04/Feb/2020 09:50:01 [nprobe.c:4192] ERROR: *****************************************************
04/Feb/2020 09:50:01 [nprobe.c:6027] IMPORTANT: Enabling NflitePlugin will also enable IP address forging, thus
04/Feb/2020 09:50:01 [nprobe.c:6028] IMPORTANT: flows appear as they were sent from the NflitePlugin-enabled switch
04/Feb/2020 09:50:01 [nprobe.c:3759] Exporting flows towards 10.1.11.34:9996 using UDP
04/Feb/2020 09:50:01 [nprobe.c:6122] WARNING: The output interfaceId is set to 0: did you forget to use -Q perhaps ?
04/Feb/2020 09:50:01 [nprobe.c:6125] WARNING: The input interfaceId is set to 0: did you forget to use -u perhaps ?
04/Feb/2020 09:50:01 [nprobe.c:6212] Welcome to nProbe v.8.6.200203 ($Revision: 6343 $) for x86_64-unknown-linux-gnu with native PF_RING acceleration
04/Feb/2020 09:50:01 [nprobe.c:6222] Running on CentOS Linux release 7.7.1908 (Core)
04/Feb/2020 09:50:01 [nprobe.c:6233] [LICENSE] nProbe SystemId: 689ED9C776066B16
04/Feb/2020 09:50:01 [nprobe.c:6300] Sample rate [packet: 1][flow collection/export: 1/1]
04/Feb/2020 09:50:01 [nprobe.c:9005] ERROR: ***************************************************************
04/Feb/2020 09:50:01 [nprobe.c:9006] ERROR: * NOTE: This is a DEMO version limited to 25000 flows export.  *
04/Feb/2020 09:50:01 [nprobe.c:9007] ERROR: ***************************************************************
04/Feb/2020 09:50:01 [modbusPlugin.c:102] [MODBUS] Idle flow timeout set to 120 sec
04/Feb/2020 09:50:01 [nflitePlugin.c:879] ERROR: Flow collector port 2055/IPv6 already in use ? [Address family not supported by protocol/97]: disabling collection over IPv6
04/Feb/2020 09:50:01 [nflitePlugin.c:903] [NFLite] Listening on port range 2055-2055 (1)
04/Feb/2020 09:50:01 [nprobe.c:9013] Welcome to nProbe v.8.6.200203 for x86_64-unknown-linux-gnu
04/Feb/2020 09:50:01 [nprobe.c:8001] You selected v9/IPFIX without specifying a template (-T).
04/Feb/2020 09:50:01 [nprobe.c:8002] The default template will be used
04/Feb/2020 09:50:01 [nprobe.c:8009] Using NetFlow Packet Payload Len: 1472
04/Feb/2020 09:50:01 [plugin.c:1278] 1 plugin(s) enabled
04/Feb/2020 09:50:01 [nprobe.c:8461] Each flow is 71 bytes long
04/Feb/2020 09:50:01 [nprobe.c:8462] The # flows per packet has been set to 19
04/Feb/2020 09:50:01 [nprobe.c:8465] IP TOS is accounted
04/Feb/2020 09:50:01 [nprobe.c:8491] Non IPv4/v6 traffic is discarded according to the template
04/Feb/2020 09:50:01 [nprobe.c:9274] Flows ASs will not be computed (no GeoDB files loaded)
04/Feb/2020 09:50:01 [nprobe.c:9379] Not capturing packet from interface (collector mode)
04/Feb/2020 09:50:01 [plugin.c:960] Enabling plugin Netflow-Lite Plugin
04/Feb/2020 09:50:01 [nprobe.c:9629] nProbe started successfully
^C04/Feb/2020 09:50:19 [nprobe.c:567] Received shutdown request... [signal: 2]
04/Feb/2020 09:50:19 [nprobe.c:6345] Flushing active flows
04/Feb/2020 09:50:21 [nprobe.c:3157] Processed packets: 0 (max bucket search: 0)
04/Feb/2020 09:50:21 [nprobe.c:3140] Fragment queue length: 0
04/Feb/2020 09:50:21 [nprobe.c:3170] Flow export stats:      [0 bytes/0 pkts][0 flows/0 pkts sent]
04/Feb/2020 09:50:21 [nprobe.c:3176] Flow export drop stats: [0 bytes/0 pkts][0 flows]
04/Feb/2020 09:50:21 [nprobe.c:3181] Total flow stats:       [0 bytes/0 pkts][0 flows/0 pkts sent]

Thanks.

**Comment by cardigliano** [comment]
@christianbj87 could you send your license and orderid to cardigliano at ntop.org please? Thank you.

**Comment by christianbj87** [comment]
@cardigliano Sorry i can't, my partner have that info and he is on his vacations. He will be back en 15 days.
We have nProbe Pro Permanent License. We migrated the service from Windos to Linux.

**Comment by cardigliano** [comment]
You should be able to read the license from /etc/nprobe.license

**Comment by christianbj87** [comment]
Yes, i can do it, but i cant check it online, because the systemID is from the old server with Windows.

Output if i dont execute --online-license-check:

sudo nprobe --nflite 2055 -i none -n 10.1.11.34:9996
04/Feb/2020 12:55:13 [plugin.c:181] No plugins found in ./plugins
04/Feb/2020 12:55:13 [plugin.c:189] Loading 24 plugins [.so] from /usr/local/lib/nprobe/plugins
04/Feb/2020 12:55:13 [nprobe.c:4178] ERROR: Invalid nProbe license (/etc/nprobe.license) [License mismatch error]
04/Feb/2020 12:55:13 [nprobe.c:4185] ERROR: *****************************************************
04/Feb/2020 12:55:13 [nprobe.c:4186] ERROR: **                                                 **
04/Feb/2020 12:55:13 [nprobe.c:4187] ERROR: **  Switching to DEMO MODE (missing valid license) **
04/Feb/2020 12:55:13 [nprobe.c:4188] ERROR: **                                                 **
04/Feb/2020 12:55:13 [nprobe.c:4189] ERROR: **  Purchase your nProbe license at                **
04/Feb/2020 12:55:13 [nprobe.c:4190] ERROR: **       https://shop.ntop.org/                    **
04/Feb/2020 12:55:13 [nprobe.c:4191] ERROR: **                                                 **
04/Feb/2020 12:55:13 [nprobe.c:4192] ERROR: *****************************************************
04/Feb/2020 12:55:13 [nprobe.c:6027] IMPORTANT: Enabling NflitePlugin will also enable IP address forging, thus
04/Feb/2020 12:55:13 [nprobe.c:6028] IMPORTANT: flows appear as they were sent from the NflitePlugin-enabled switch
04/Feb/2020 12:55:13 [nprobe.c:3759] Exporting flows towards 10.1.11.34:9996 using UDP
04/Feb/2020 12:55:13 [nprobe.c:6122] WARNING: The output interfaceId is set to 0: did you forget to use -Q perhaps ?
04/Feb/2020 12:55:13 [nprobe.c:6125] WARNING: The input interfaceId is set to 0: did you forget to use -u perhaps ?
04/Feb/2020 12:55:13 [nprobe.c:6212] Welcome to nProbe v.8.6.200203 ($Revision: 6343 $) for x86_64-unknown-linux-gnu with native PF_RING acceleration
04/Feb/2020 12:55:13 [nprobe.c:6222] Running on CentOS Linux release 7.7.1908 (Core)
04/Feb/2020 12:55:13 [nprobe.c:6233] [LICENSE] nProbe SystemId: 689ED9C776066B16
04/Feb/2020 12:55:13 [nprobe.c:6300] Sample rate [packet: 1][flow collection/export: 1/1]
04/Feb/2020 12:55:13 [nprobe.c:9005] ERROR: ***************************************************************
04/Feb/2020 12:55:13 [nprobe.c:9006] ERROR: * NOTE: This is a DEMO version limited to 25000 flows export.  *
04/Feb/2020 12:55:13 [nprobe.c:9007] ERROR: ***************************************************************
04/Feb/2020 12:55:13 [modbusPlugin.c:102] [MODBUS] Idle flow timeout set to 120 sec
04/Feb/2020 12:55:13 [nflitePlugin.c:879] ERROR: Flow collector port 2055/IPv6 already in use ? [Address family not supported by protocol/97]: disabling collection over IPv6
04/Feb/2020 12:55:13 [nflitePlugin.c:903] [NFLite] Listening on port range 2055-2055 (1)
04/Feb/2020 12:55:13 [nprobe.c:9013] Welcome to nProbe v.8.6.200203 for x86_64-unknown-linux-gnu
04/Feb/2020 12:55:13 [nprobe.c:8001] You selected v9/IPFIX without specifying a template (-T).
04/Feb/2020 12:55:13 [nprobe.c:8002] The default template will be used
04/Feb/2020 12:55:13 [nprobe.c:8009] Using NetFlow Packet Payload Len: 1472
04/Feb/2020 12:55:13 [plugin.c:1278] 1 plugin(s) enabled
04/Feb/2020 12:55:13 [nprobe.c:8461] Each flow is 71 bytes long
04/Feb/2020 12:55:13 [nprobe.c:8462] The # flows per packet has been set to 19
04/Feb/2020 12:55:13 [nprobe.c:8465] IP TOS is accounted
04/Feb/2020 12:55:13 [nprobe.c:8491] Non IPv4/v6 traffic is discarded according to the template
04/Feb/2020 12:55:13 [nprobe.c:9274] Flows ASs will not be computed (no GeoDB files loaded)
04/Feb/2020 12:55:13 [nprobe.c:9379] Not capturing packet from interface (collector mode)
04/Feb/2020 12:55:13 [plugin.c:960] Enabling plugin Netflow-Lite Plugin
04/Feb/2020 12:55:13 [nprobe.c:9629] nProbe started successfully
^C04/Feb/2020 12:55:25 [nprobe.c:567] Received shutdown request... [signal: 2]
04/Feb/2020 12:55:26 [nprobe.c:6345] Flushing active flows
04/Feb/2020 12:55:28 [nprobe.c:3157] Processed packets: 0 (max bucket search: 0)
04/Feb/2020 12:55:28 [nprobe.c:3140] Fragment queue length: 0
04/Feb/2020 12:55:28 [nprobe.c:3170] Flow export stats:      [0 bytes/0 pkts][0 flows/0 pkts sent]
04/Feb/2020 12:55:28 [nprobe.c:3176] Flow export drop stats: [0 bytes/0 pkts][0 flows]
04/Feb/2020 12:55:28 [nprobe.c:3181] Total flow stats:       [0 bytes/0 pkts][0 flows/0 pkts sent]

**Comment by cardigliano** [comment]
Did you read this? https://www.ntop.org/support/faq/how-can-i-move-a-license-to-a-new-server/

**Comment by christianbj87** [comment]
Yes i did. The problem is when set a proxy.
I tried in a VM for testing with internet connection without proxy and the license works.

![image](https://user-images.githubusercontent.com/60654543/73771646-7d6c4680-475d-11ea-8e71-b525f9ddc082.png)

**Comment by cardigliano** [comment]
Please send me the output of nprobe --version, including the license info (in a private mail), I will provide you instructions to debug this. Thank you.

**Comment by christianbj87** [comment]
ok, i already did. Thanks.

**Comment by cardigliano** [comment]
This was due to a systemid mismatch, closing.
