### ISSUE TITLE
Fix(allow) dynamic linking aainst nDPI-3.0

### ISSUE THREAD

**Issue by ahkok** [ntop/ntopng#3379]
Current `configure.seed` blocks dynamic linking to `nDPI-3.0` with a comment that it's "broken". But, a simple patch works just fine:

```
diff --git a/configure.seed b/configure.seed
index 1b62be3..3898e77 100644
--- a/configure.seed
+++ b/configure.seed
@@ -129,9 +129,8 @@ else
 fi
 
 PKG_CHECK_MODULES([NDPI], [libndpi >= 2.0], [
-   NDPI_INC=`echo $NDPI_CFLAGS | sed -e "s/[ ]*$//"`/libndpi
-   # Use static libndpi library as building against the dynamic library fails
-   NDPI_LIB="-Wl,-Bstatic $NDPI_LIBS -Wl,-Bdynamic"
+   NDPI_INC="$NDPI_CFLAGS"
+   NDPI_LIB="$NDPI_LIBS"
    NDPI_LIB_DEP=
    ], [
       AC_MSG_CHECKING(for nDPI source)
```

So, this should be fixed - distributions will always prefer linking dynamically - as it should be.

(This is for ClearLinux OS, but, I'm sure others will appreciate this being rectified).

**Comment by simonemainardi** [comment]
please, submit this as a pull request so we can evaluate and include it

**Comment by ahkok** [comment]
It's not up to me to evaluate the deeper consequences of this patch - I don't have the time for that. I have 6000 other OSS projects to tend to. I understand it would *help* you, but my focus is limited.
