### ISSUE TITLE
i want see report.

### ISSUE THREAD

**Issue by gaeunLEE** [ntop/ntopng#338]
I am considering to buy the pro version.

i want to see 'pro version'. it has additional features
" • Ability to generate advanced HTML reports that can be exported in PDF. "

but, i recovery ERROR Massage from REPORT.
ERROR massage is....
/usr/share/ntopng/scripts/lua/pro/report.lua:319: attempt to perform arithmetic on field 'bytes.sent' (a nil value)

What is the way to solve?

plz reply

**Comment by simonemainardi** [comment]
this has been fixed, could you please update to the latest dev version. thank you for reporting.
