### ISSUE TITLE
Port blocking and VLAN assignment via SNMP

### ISSUE THREAD

**Issue by ids-cyberlab** [ntop/ntopng#3388]
It will be appreciated to have the possibility of inserting new features regarding the management of devices via SNMP protocol. 

In particular, it will be useful to have the following new functions:
- switch's port deactivation / blocking  which a specific host is connected to;
- enabling an "untagged" VLAN (among those known by the device) on a port.

Thanks.

**Comment by lucaderi** [comment]
We have implemented the ability to enable/disable interfaces via SNMP as requested

Example of a script that sets a port down
local port_up    = "1"
local port_down  = "2"
local ifIdx = "6" -- interfaceIndex
rsp = ntop.snmpset("127.0.0.1", "public", 5, 1, "1.3.6.1.2.1.2.2.1.7."..ifIdx, "i", port_down)

As of port status, please refer to #3833

As of the other request about the VLAN we believe this is not something ntopng should support at the moment.
