### ISSUE TITLE
Bridging Wireless and Ethernet

### ISSUE THREAD

**Issue by Cyndz136** [ntop/ntopng#339]
Good Day. Here’s my Situation I’m running the Ntop on a Desktop Unit with an OS Ubuntu 14.04 LTS. And I saved the License provided to me yesterday. Since the Desktop doesn’t have a built-in Wireless Connection I’ve added a USB Wifi Adapter. So Now I have 2 Connection which is the Ethernet and the Wireless. What I’m trying to achieve is the BUMP in the Wire that the Video’s been telling. I saw in the Video that the Interface Family is PF_RING In-Path Interface (BUMP in the Wire) whereas mine is only PF_RING. Can you Please Help me how I’ll be able to do the BUMP in the Wire.

**Comment by simonemainardi** [comment]
you should make sure to run ntopng in bridge mode, e.g., `ntopng -ibridge:eth0,eth1` 
as soon as you have specified a bridge interface, you'll be able to see the bump in the wire interface in the web gui.
