### ISSUE TITLE
Update menu when geolocation is not enabled

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3395]
When geolocation is not enabled, the "countries" menu entry should not be enabled (or not be listed at all) instead of allowing people to open it and fail

![Screen Shot 2020-02-07 at 22 56 20](https://user-images.githubusercontent.com/4493366/74068940-34d2b880-49fd-11ea-9e4f-e9984b29fa8b.png)

**Comment by simonemainardi** [comment]
Now missing geoip is shown in a global notice which is dismissable.

ASses, countries, and hosts geomaps are hidden when geoip is not available.
