### ISSUE TITLE
Bottom date will wrap when ntopng is started for more than a day

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3396]
When ntopng is started for more than a day, the bottom right label wraps.

![Screen Shot 2020-02-07 at 22 59 54](https://user-images.githubusercontent.com/4493366/74069100-9561f580-49fd-11ea-96af-dc7ffa1ec5f2.png)

**Comment by simonemainardi** [comment]
fixed in https://github.com/ntop/ntopng/commit/df5b7092a26a0e00d6bd2d0344d38d5c3e627d54
