### ISSUE TITLE
Various Dark Theme Inconsistencies

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3399]
![photo_2020-02-09 18 57 21](https://user-images.githubusercontent.com/4493366/74107213-0aecd380-4b6e-11ea-8a19-06a1efa2d796.jpeg)
![photo_2020-02-09 18 57 20](https://user-images.githubusercontent.com/4493366/74107215-0c1e0080-4b6e-11ea-8be3-0644b3aa4e17.jpeg)
![photo_2020-02-09 18 57 19](https://user-images.githubusercontent.com/4493366/74107216-0d4f2d80-4b6e-11ea-99a5-a341313e68e6.jpeg)
![photo_2020-02-09 18 57 18 (1)](https://user-images.githubusercontent.com/4493366/74107217-0de7c400-4b6e-11ea-8960-425458d42491.jpeg)
![photo_2020-02-09 18 57 18](https://user-images.githubusercontent.com/4493366/74107218-0de7c400-4b6e-11ea-8c6b-780b4004cde6.jpeg)
![photo_2020-02-09 18 57 17](https://user-images.githubusercontent.com/4493366/74107219-0e805a80-4b6e-11ea-8239-b20446eadcd8.jpeg)
![photo_2020-02-09 18 57 15](https://user-images.githubusercontent.com/4493366/74107220-0e805a80-4b6e-11ea-8451-326984379ea8.jpeg)
![photo_2020-02-09 18 57 14](https://user-images.githubusercontent.com/4493366/74107221-0f18f100-4b6e-11ea-8a22-ebee4c49671e.jpeg)
![photo_2020-02-09 18 57 13](https://user-images.githubusercontent.com/4493366/74107222-0f18f100-4b6e-11ea-971f-647082c69a0c.jpeg)
![photo_2020-02-09 18 56 55](https://user-images.githubusercontent.com/4493366/74107223-0fb18780-4b6e-11ea-9600-7eed007a0278.jpeg)

**Comment by gabryon99** [comment]
Fixed in: https://github.com/ntop/ntopng/commit/79fc3e191bb6afc74f3103cd7e7da0b50d780097.
