### ISSUE TITLE
Error compile dev branch

### ISSUE THREAD

**Issue by alberk8** [ntop/ntopng#34]
Hi,

I have clone the default (dev) branch of ntopng and the compiling process quit with an error.  On the same machine I have no problem compiling the master branch.  My OS is 

Linux SMX8SIL 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Is there a bug in the Makefile?.  Thanks.

#### Make message with error below ###
checking GeoIP.h usability... yes
checking GeoIP.h presence... yes
checking for GeoIP.h... yes
checking for GeoIP_lib_version in -lGeoIP... yes
checking for sqlite3_open in -lsqlite3... yes
configure: creating ./config.status
config.status: creating packages/ntopng.spec
config.status: creating packages/ntopng-data.spec
config.status: creating Makefile
config.status: WARNING:  'Makefile.in' seems to ignore the --datarootdir setting
config.status: creating doc/doxygen.conf
config.status: creating include/config.h
config.status: include/config.h is unchanged
configure: WARNING: unrecognized options: --disable-libdbi, --disable-libwrap, --disable-rrdcgi, --disable-libtool-lock, --disable-nls, --disable-rpath, --disable-perl, --disable-ruby, --disable-lua, --disable-tcl, --disable-python, --disable-dependency-tracking, --disable-rrd_graph

You are now ready to compile typing make
Please do not forget to download GeoIP databases doing: make geoip
make[1]: Entering directory `/home/smart/ntopng/src'
make[1]: *** No rule to make target `librrd_th.la'.  Stop.
make[1]: Leaving directory `/home/smart/ntopng/src'
make: *** [/third-party/rrdtool-1.4.8/src/.libs/librrd_th.a] Error 2

**Comment by ariava** [comment]
@alberk8 could you please try to install the librrd-dev package and try again? You'd need to invoke ./autogen.sh and ./configure again before trying again to make.

**Comment by lucaderi** [comment]
@alberk8 I have tried to reproduce the issue and it works for me. if ntopng does not find rrd installed it tries to compile it. It looks to me its compilation is failing on your system. So either you install rrd as Arianna suggested, or make sure you ha installed all prerequisites to rrd compilation.

**Comment by alberk8** [comment]
Hi ariava and lucaderi,

Thanks. It now compiles after installing the librrd-dev package.  It is odd that the master branch compiles without the package on the same machine.  Again thanks for the prompt reply.
