### ISSUE TITLE
Improve data exfiltration default

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3401]
![Screen Shot 2020-02-09 at 19 01 42](https://user-images.githubusercontent.com/4493366/74107298-a1b99000-4b6e-11ea-993f-09828a5dc152.png)

There are some protocols such as dropbox, that produce invalid data exfiltration alerts. it is requested to review the defaults so that only applications that make sense produce alerts

**Comment by emanuele-f** [comment]
Added `Cloud` (which includes Dropbox), `SoftwareUpdate` and `Streaming` to the default excluded apps/categories. Please click on "Reset Configuration" to set the default again.
