### ISSUE TITLE
Misleading stacked charts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3402]
Stacked charts are misleading when, for instance, used to represent traffic. 

![Screen Shot 2020-02-09 at 19 13 18](https://user-images.githubusercontent.com/4493366/74107448-661fc580-4b70-11ea-83ef-71f8713c2939.png)

This is because on this industry everyone uses an area chart for one direction (eg. RX) and a line (e.g. TX) on the other this to avoid that the sum of RX+TX exceeds the capacity of the link and thus produce data hard to interpret.

Please modify the stacked traffic/packets charts accordingly (including SNMP)

**Comment by gabryon99** [comment]
Fixed.

**Comment by lucaderi** [comment]
![image](https://user-images.githubusercontent.com/4493366/79962426-4ff38700-8488-11ea-95e2-62e84874695e.png)
SNMP graphs are still stacked.
Note that AS graphs are also still stacked and thus needs to be fixed

**Comment by emanuele-f** [comment]
Fixed in c1a1ff54da6ef104585c36a021d5fdf4728894db and pro correlated commit.

**Comment by emanuele-f** [comment]
Other charts also fixed in ebe2e78b7e1a7737560e9c3512402a1eacaf62ba

**Comment by lucaderi** [comment]
Exactly what are the charts that you have modified and that shall be tested?

**Comment by emanuele-f** [comment]
All the charts which have the sent/recv traffic counters, which are: Country traffic, AS traffic, Network traffic, Host traffic, SNMP interface traffic, Mac Address traffic and Host pool traffic

**Comment by simonemainardi** [comment]
to me it is really confusing to have the 'sent' line with the same style of all the other lines. It makes the chart very hard to read:

![image](https://user-images.githubusercontent.com/3397663/80494146-a1a78000-8966-11ea-9e20-f350272eb0ea.png)

The only way one can make use of this chart is by disabling everything but sent and received

![image](https://user-images.githubusercontent.com/3397663/80494244-bdab2180-8966-11ea-8775-9cbb9aea2fab.png)

**Comment by emanuele-f** [comment]
As internally discussed, SMA, EMA and trend lines have been removed in  e2bade07d55bdee516861826d414961805a43a85 . Please close this if satisfied.

**Comment by simonemainardi** [comment]
would it be possible to add a transparency below the yellow line? how complex it would be?

something like

<img width="564" alt="image" src="https://user-images.githubusercontent.com/3397663/81053437-5d1b6780-8ec5-11ea-9958-2059510615c1.png">

**Comment by simonemainardi** [comment]
bug solved, will deal with transparencies on a separate issue.
