### ISSUE TITLE
nIndex First / Last seen not matching search criteria

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3403]
Given a query with a defined timerange, nIndex records returned don't match. For example, in this image, records returned are from 12:00 whereas the timerange starts at 13.

![image](https://user-images.githubusercontent.com/3397663/74136865-24822f80-4bef-11ea-8546-e99cdd509f72.png)

**Comment by cardigliano** [comment]
Caused by GUI local time != backend local time. Fixed.
