### ISSUE TITLE
LUA script problem

### ISSUE THREAD

**Issue by oktavianq** [ntop/ntopng#3404]
Sorry for the confusion. Administrator request to delete this post. The error described here is the cause of the error described here
https://github.com/ntop/ntopng/issues/3405

Periodic activity 'second.lua' took too much to complete [7823 ms > 1000 ms]

v.3.9.200207	[Enterprise/Professional build]
GIT rev:	dev:1b7b831b855f150393e18f1e627bfc265957a664:20200207
Pro rev:	r2701
Built on:	Ubuntu 18.04.3 LTS
System Id:	4ADBE7799205A1D6
Platform:	x86_64

**Comment by emanuele-f** [comment]
Please continue discussion on #3405
