### ISSUE TITLE
SNMP Device JSON Error

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#3407]
When we try to have access to SNMP Device we receive this error:
SyntaxError: Unexpected token H in JSON at position 0.

These are the errors:
11/Feb/2020 14:17:42 [LuaEngine.cpp:12498] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/get_snmp_devices_list.lua][/usr/share/ntopng/pro/scripts/lua/modules/snmp_utils.lua:3495: attempt to call a nil value (global 'is_snmp_device_alerts_port_errors_enabled')]
11/Feb/2020 14:15:47 [LuaEngine.cpp:12498] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/get_snmp_devices_list.lua][/usr/share/ntopng/pro/scripts/lua/modules/snmp_utils.lua:3495: attempt to call a nil value (global 'is_snmp_device_alerts_port_errors_enabled')]
11/Feb/2020 14:15:28 [LuaEngine.cpp:12498] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/get_snmp_devices_list.lua][/usr/share/ntopng/pro/scripts/lua/modules/snmp_utils.lua:3495: attempt to call a nil value (global 'is_snmp_device_alerts_port_errors_enabled')]
11/Feb/2020 14:15:22 [LuaEngine.cpp:12498] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/get_snmp_devices_list.lua][/usr/share/ntopng/pro/scripts/lua/modules/snmp_utils.lua:3495: attempt to call a nil value (global 'is_snmp_device_alerts_port_errors_enabled')]
11/Feb/2020 14:15:19 [LuaEngine.cpp:12498] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/get_snmp_devices_list.lua][/usr/share/ntopng/pro/scripts/lua/modules/snmp_utils.lua:3495: attempt to call a nil value (global 'is_snmp_device_alerts_port_errors_enabled')]
11/Feb/2020 14:14:14 [LuaEngine.cpp:12498] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/get_snmp_devices_list.lua][/usr/share/ntopng/pro/scripts/lua/modules/snmp_utils.lua:3495: attempt to call a nil value (global 'is_snmp_device_alerts_port_errors_enabled')]
11/Feb/2020 14:13:55 [LuaEngine.cpp:12498] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/get_snmp_devices_list.lua][/usr/share/ntopng/pro/scripts/lua/modules/snmp_utils.lua:3495: attempt to call a nil value (global 'is_snmp_device_alerts_port_errors_enabled')]
11/Feb/2020 14:13:02 [LuaEngine.cpp:12498] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/get_snmp_devices_list.lua][/usr/share/ntopng/pro/scripts/lua/modules/snmp_utils.lua:3495: attempt to call a nil value (global 'is_snmp_device_alerts_port_errors_enabled')]
11/Feb/2020 14:12:26 [LuaEngine.cpp:12498] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/get_snmp_devices_list.lua][/usr/share/ntopng/pro/scripts/lua/modules/snmp_utils.lua:3495: attempt to call a nil value (global 'is_snmp_device_alerts_port_errors_enabled')]
11/Feb/2020 14:02:49 [LuaEngine.cpp:12498] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/get_snmp_devices_list.lua][/usr/share/ntopng/pro/scripts/lua/modules/snmp_utils.lua:3495: attempt to call a nil value (global 'is_snmp_device_alerts_port_errors_enabled')]
11/Feb/2020 14:02:27 [LuaEngine.cpp:12498] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/get_snmp_devices_list.lua][/usr/share/ntopng/pro/scripts/lua/modules/snmp_utils.lua:3495: attempt to call a nil value (global 'is_snmp_device_alerts_port_errors_enabled')]
11/Feb/2020 13:59:21 [NetworkInterface.cpp:2334] Started packet polling on interface ens1f0,ens1f1 [id: 7]...
![Immagine](https://user-images.githubusercontent.com/47248892/74240635-b155e780-4cda-11ea-8bb9-a8af7ee4009a.png)

**Comment by zimbawe998** [comment]
We cannot see any switched configured.

**Comment by emanuele-f** [comment]
Issue has been fixed. The new package will be available in one hour.

**Comment by zimbawe998** [comment]
Resolved.

Il giorno mar 11 feb 2020 alle ore 15:02 Emanuele Faranda <
notifications@github.com> ha scritto:
