### ISSUE TITLE
No memory time series

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3408]
<img width="1323" alt="Screenshot 2020-02-11 at 20 06 17" src="https://user-images.githubusercontent.com/4493366/74269776-50460800-4d0a-11ea-9732-8a69701d8dd4.png">
CPU load is present but not memory. This using the latest dev version with RRD as backend

**Comment by emanuele-f** [comment]
Cannot reproduce, it may be caused by the minute periodic activity being stopped before it completes, please check out the related chart: http://127.0.0.1:3000/lua/periodic_script_details.lua?ifid=1&page=historical&zoom=30m&periodic_script=minute.lua&version=4&ts_schema=periodic_script%3Aduration

**Comment by simonemainardi** [comment]
I can reproduce, debugging...

**Comment by simonemainardi** [comment]
@lucaderi please visit preferences and check this if it is on/off

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/3397663/74355743-8abcad00-4dbd-11ea-9108-43d95cbe08d6.png">

In the meanwhile I will make the description of this preference more clear. However, that is on by default.

**Comment by lucaderi** [comment]
Everything is on

**Comment by simonemainardi** [comment]
this is due to periodic activities stuck which, in turn, are stuck due to the disk which is extremely slow. Can simulate this condition by placing a sleep in the `rrd_update`. As the memory timeseries is written in a periodic activity, points fail to be written.

Issue `https://github.com/ntop/ntopng/issues/3425` should bring the solution.

**Comment by emanuele-f** [comment]
Additional note: the timeseries is now marked with `is_critical_ts = true`, however it won't be written if the minute.lua script is skipped/delayed by other scripts.

**Comment by lucaderi** [comment]
Please report what commit fixed the issue

**Comment by simonemainardi** [comment]
Fixed with the combination of commits:

- d5fab4169cf7a80253af359796c36ca46688afba (to always write critical timeseries even when timeseries are slow)
- 517184c2aa1e68094923e20a9836a9356f28dbf2 (to prevent minute.lua activity from being blocked by longer activities such as the 5min.lua)
