### ISSUE TITLE
Unable to start NtopNG after update

### ISSUE THREAD

**Issue by juesor** [ntop/ntopng#341]
This morning i updated ntopng from 2.3.151228-734 to 2.3.160104-750 on CentOS 7

Now now it says the service is active but it is not loading.

Update via yum 

[root@HEND-ntopng ~]# yum update
Loaded plugins: fastestmirror
base                                                                                                                                                 | 3.6 kB  00:00:00
epel/x86_64/metalink                                                                                                                                 |  12 kB  00:00:00
epel                                                                                                                                                 | 4.3 kB  00:00:00
extras                                                                                                                                               | 3.4 kB  00:00:00
ntop                                                                                                                                                 | 2.9 kB  00:00:00
ntop-noarch                                                                                                                                          | 2.9 kB  00:00:00
saltstack-zeromq4                                                                                                                                    | 3.0 kB  00:00:00
updates                                                                                                                                              | 3.4 kB  00:00:00
(1/5): epel/x86_64/updateinfo                                                                                                                        | 453 kB  00:00:00
(2/5): ntop/7/x86_64/primary_db                                                                                                                      | 4.9 kB  00:00:00
(3/5): epel/x86_64/primary_db                                                                                                                        | 3.7 MB  00:00:00
(4/5): ntop-noarch/7/primary_db                                                                                                                      | 9.4 kB  00:00:00
(5/5): saltstack-zeromq4/x86_64/primary_db                                                                                                           | 5.0 kB  00:00:00
Loading mirror speeds from cached hostfile
- base: centos.host-engine.com
- epel: mirror.steadfast.net
- extras: mirrors.lga7.us.voxel.net
- updates: mirror.beyondhosting.net
  Resolving Dependencies
  --> Running transaction check
  ---> Package ntopng.x86_64 0:2.3.151228-734 will be updated
  ---> Package ntopng.x86_64 0:2.3.160104-750 will be an update
  ---> Package ntopng-data.noarch 0:2.3.151228-734 will be updated
  ---> Package ntopng-data.noarch 0:2.3.160104-750 will be an update
  ---> Package pfring.x86_64 0:6.3.0-415 will be updated
  ---> Package pfring.x86_64 0:6.3.0-416 will be an update
  ---> Package pfring-dkms.noarch 0:6.3.0-415 will be updated
  ---> Package pfring-dkms.noarch 0:6.3.0-416 will be an update
  --> Finished Dependency Resolution

Dependencies Resolved
# 
#  Package                                  Arch                                Version                                        Repository                                Size

Updating:
 ntopng                                   x86_64                              2.3.160104-750                                 ntop                                      27 M
 ntopng-data                              noarch                              2.3.160104-750                                 ntop-noarch                               23 M
 pfring                                   x86_64                              6.3.0-416                                      ntop                                     1.5 M
 pfring-dkms                              noarch                              6.3.0-416                                      ntop-noarch                               78 k
# Transaction Summary

Upgrade  4 Packages

checking status of ntopng via systemctl status ntopng

[root@HEND-ntopng ntopng]# systemctl status ntopng
● ntopng.service - Start/stop ntopng program
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2016-01-06 10:52:34 CST; 2min 53s ago
  Process: 25452 ExecStop=/etc/systemd/scripts/ntopng stop (code=exited, status=0/SUCCESS)
  Process: 25460 ExecStart=/etc/systemd/scripts/ntopng start (code=exited, status=0/SUCCESS)
 Main PID: 25480 (ntopng)
   CGroup: /system.slice/ntopng.service
           └─25480 /usr/bin/ntopng /etc/ntopng/ntopng.conf

Jan 06 10:52:29 HEND-ntopng systemd[1]: Starting Start/stop ntopng program...
Jan 06 10:52:29 HEND-ntopng ntopng[25460]: Starting ntopng: /etc/systemd/scripts/ntopng: line 128: [: -gt: unary operator expected
Jan 06 10:52:29 HEND-ntopng ntopng[25460]: /etc/systemd/scripts/ntopng: line 145: [: -gt: unary operator expected
Jan 06 10:52:30 HEND-ntopng ntopng[25460]: /etc/systemd/scripts/ntopng: line 145: [: -gt: unary operator expected
Jan 06 10:52:31 HEND-ntopng ntopng[25460]: /etc/systemd/scripts/ntopng: line 145: [: -gt: unary operator expected
Jan 06 10:52:32 HEND-ntopng ntopng[25460]: /etc/systemd/scripts/ntopng: line 145: [: -gt: unary operator expected
Jan 06 10:52:33 HEND-ntopng ntopng[25460]: /etc/systemd/scripts/ntopng: line 145: [: -gt: unary operator expected
Jan 06 10:52:34 HEND-ntopng ntopng[25460]: Unable to start ntopng[FAILED]
Jan 06 10:52:34 HEND-ntopng systemd[1]: Started Start/stop ntopng program.
Jan 06 10:55:26 HEND-ntopng systemd[1]: Started Start/stop ntopng program.

line 128 

```
    if [ ${PID} -gt 0 ]; then
        MSG="ntopng already running. Exiting"
        ERROR=1
        RETVAL=1
        error_handler "quit"
        exit 99
    fi
```

line 145
if [ $PID -gt 0 ]; then
                MSG="Started ntopng with PID $PID"
                ERROR=0
                break
            else
                MSG="Unable to start ntopng"
                ERROR=1
                sleep 1
            fi
        done

so pid file 

i look earlier in the ntopng and i see

get_ntopng_pid() {
    if [ -f "/etc/ntopng/ntopng.conf" ]; then
        PID_FILE=$(cat /etc/ntopng/ntopng.conf | grep -E '-G=|--pid'|cut -d '=' -f 2)
    else
        PID_FILE="/var/tmp/ntopng.pid"
    fi

so to start i cat my conf which i know i don't had --pid declared and yes no results
 cat /etc/ntopng/ntopng.conf | grep -E '-G=|--pid'|cut -d '=' -f 2
[root@HEND-ntopng ntopng]#

so my pid_file is /var/tmp/ntopng.pid

and i navigate to that directory and ntopng.pid owned by ntop is there

[root@HEND-ntopng tmp]# ls -lh
total 4.0K
drwxrwxrwx. 12 root root 105 Jan  6 10:52 ntopng
-rwxrwxrwx.  1 ntop ntop   6 Jan  6 10:52 ntopng.pid

now to validate my pid is what i'm seeing with ntopng trying to use

[root@HEND-ntopng tmp]# cat ntopng.pid
25480
[root@HEND-ntopng tmp]# ps -ef | grep ntop
ntop     25480     1  0 10:52 ?        00:00:11 /usr/bin/ntopng /etc/ntopng/ntopng.conf

my ntopng.start file is present.

why does it say active but unable to start ntopng[FAILED]

**Comment by simonemainardi** [comment]
please make a `ps aux | grep ntopng` and kill any running ntopng process. Then try to `service ntopng start` again.
if it still fails, please post contents of `/etc/ntopng/ntopng.conf` and `/var/log/ntopng/ntopng.log`

**Comment by juesor** [comment]
http://pastebin.com/7RwmLLzW

Still not starting properly

**Comment by simonemainardi** [comment]
your ntopng.conf is missing the path to the pid file `--pid`. This is why you are getting

```
Jan 08 10:40:48 HEND-ntopng ntopng[29804]: Starting ntopng: /etc/systemd/scripts/ntopng: line 128: [: -gt: unary operator expected
Jan 08 10:40:48 HEND-ntopng ntopng[29804]: /etc/systemd/scripts/ntopng: line 145: [: -gt: unary operator expected
```

**Comment by juesor** [comment]
[root@HEND-ntopng ntopng]# cat ntopng.conf
--user ntop
--daemon
--db-file-path /usr/share/ntop
--interface p2p1,p2p2
--trace-level 3 # which is the default
--pid /var/tmp/ntopng.pid
-w 3000
-m 205.185.128.0/19,208.74.240.0/21,108.59.96.0/20,162.249.96.0/21
#-F mysql;localhost;ntopng;flows;root;
[root@HEND-ntopng ntopng]# ls /var/tmp/
ntopng  ntopng.pid  systemd-private-1be990e28d5644f2babf6f6f566017cd-ntpd.service-xyk1fZ
[root@HEND-ntopng ntopng]# ps -ef | grep ntop
ntop     30121     1  1 13:15 ?        00:00:00 /usr/bin/ntopng /etc/ntopng/ntopng.conf
root     30185 29646  0 13:16 pts/0    00:00:00 grep --color=auto ntop
[root@HEND-ntopng ntopng]# cat /var/tmp/ntopng.pid
30121
[root@HEND-ntopng ntopng]#

I have --pid /var/tmp/ntopng.pid declared now and you can see the pid 

and you can see

[root@HEND-ntopng ntopng]# systemctl status ntopng
● ntopng.service - Start/stop ntopng program
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2016-01-08 13:15:35 CST; 1min 53s ago
  Process: 30087 ExecStop=/etc/systemd/scripts/ntopng stop (code=exited, status=0/SUCCESS)
  Process: 30101 ExecStart=/etc/systemd/scripts/ntopng start (code=exited, status=0/SUCCESS)
 Main PID: 30121 (ntopng)
   CGroup: /system.slice/ntopng.service
           └─30121 /usr/bin/ntopng /etc/ntopng/ntopng.conf

Jan 08 13:15:30 HEND-ntopng systemd[1]: Starting Start/stop ntopng program...
Jan 08 13:15:30 HEND-ntopng ntopng[30101]: Starting ntopng: /etc/systemd/scripts/ntopng: line 68: [: --pid: binary operator expected
Jan 08 13:15:30 HEND-ntopng ntopng[30101]: /etc/systemd/scripts/ntopng: line 68: [: --pid: binary operator expected
Jan 08 13:15:31 HEND-ntopng ntopng[30101]: /etc/systemd/scripts/ntopng: line 68: [: --pid: binary operator expected
Jan 08 13:15:32 HEND-ntopng ntopng[30101]: /etc/systemd/scripts/ntopng: line 68: [: --pid: binary operator expected
Jan 08 13:15:33 HEND-ntopng ntopng[30101]: /etc/systemd/scripts/ntopng: line 68: [: --pid: binary operator expected
Jan 08 13:15:34 HEND-ntopng ntopng[30101]: /etc/systemd/scripts/ntopng: line 68: [: --pid: binary operator expected
Jan 08 13:15:35 HEND-ntopng ntopng[30101]: Unable to start ntopng[FAILED]
Jan 08 13:15:35 HEND-ntopng systemd[1]: Started Start/stop ntopng program.

no go

**Comment by juesor** [comment]
why is this closed?

**Comment by juesor** [comment]
Thank you for opening it.

Any other suggestions?  I've never had the --pid in my config as the startup script looks for it but if not found creates in /var/tmp/ 
as seen below.

get_ntopng_pid() {
if [ -f "/etc/ntopng/ntopng.conf" ]; then
PID_FILE=$(cat /etc/ntopng/ntopng.conf | grep -E '-G=|--pid'|cut -d '=' -f 2)
else
PID_FILE="/var/tmp/ntopng.pid"
fi

**Comment by simonemainardi** [comment]
the script now finds the `--pid` in your ntopng.conf but fails to parse it since there is no `=` (look at the `cut`you've posted above).

please modify your ntopng.conf with `--pid=/var/tmp/ntopng.pid`, shut down any running instance of ntopng, delete the existing `/var/tmp/ntopng.pid`, and try to restart the service.

**Comment by lucaderi** [comment]
@juesor I have made a fix for you. Please check it ant let us know. Don't forget to star ntopng on Github

**Comment by juesor** [comment]
Luca as always you are awesome i removed the pid declaration from my conf and it is back working like it was before.

Installed Packages
ntopng.x86_64                                                                      2.3.160114-785                                                                      @ntop

I will post another trouble i have since upgrading its showing ntopng community.

**Comment by lucaderi** [comment]
Thank you very kind of you.
