### ISSUE TITLE
Specify IP address and host name in device connection alerts

### ISSUE THREAD

**Issue by scannizzaro** [ntop/ntopng#3413]
hi everyone, I have enabled an Email Alert Endpoint to notify me of the "new Devices". The emails I receive  are like: "[07/02/2020 08:20:01] [Warning] [New Device] New device XX: XX: XX: XX: XX: XX has connected to the network." is it possible to configure the body of the email that arrives to me? I would like to be notified of the IP and / or hostname if possible. It's possible? Thanks so much

**Comment by emanuele-f** [comment]
This is currently not implemented, I've marked it as an enhancement.

**Comment by simonemainardi** [comment]
merged with https://github.com/ntop/ntopng/issues/4265
