### ISSUE TITLE
After changing Timeseries Driver to InfluxDB Top Application Traffic Last Day View is blank

### ISSUE THREAD

**Issue by mikemuzinich** [ntop/ntopng#3414]
We are running 3.8.200207 - Enterprise Edition.  Application Breakdown is also blank.  In the Flows view and other areas we are seeing Application information.  This worked fine with RRD.

**Comment by simonemainardi** [comment]
Please, move to version 3.9. This is going to become the next stable in one week. 3.8 is EOL.

**Comment by mikemuzinich** [comment]
When will that be available via the CentOS repository (http://packages.ntop.org/centos-stable)?

**Comment by simonemainardi** [comment]
4.0 is going to become available in `http://packages.ntop.org/centos-stable` when released within one week. In the meanwhile, 3.9 is available from `http://packages.ntop.org/centos`

**Comment by mikemuzinich** [comment]
I am attempting to update the software but the dkms packages go into an endless loop spawning "/bin/sh -c cd /usr/src/pfring-7.6.0/; make" processes.  Researching how to install the source code but that should happen as a dependency?

**Comment by mikemuzinich** [comment]
It appears the package that contains the source code is pfring-dkms but even with that installed, updating causes nprobe to no longer listen on the zmq port and we no longer get NetFlow data from the remote sources.  Should I wait for version 4?

**Comment by emanuele-f** [comment]
Please try to remove pf_ring and then install the new ntopng version. This particular upgrade issue may still occur with the upcoming 4 version.

**Comment by mikemuzinich** [comment]
These are the details of the upgrade saga.  It seems tied to the e1000 package.  

List installed packages from the ntop repos -

yum list installed|grep -i ntop
cento.x86_64                     1.9.200207-515              @ntop              
e1000e-zc.noarch                 3.4.0.2.2835-dkms           @ntop-noarch       
i40e-zc.noarch                   2.4.6.2835-dkms             @ntop-noarch       
igb-zc.noarch                    5.3.5.18.2835-dkms          @ntop-noarch       
ixgbe-zc.noarch                  5.3.7.2835-dkms             @ntop-noarch       
ixgbevf-zc.noarch                4.5.1.2835-dkms             @ntop-noarch       
n2disk.x86_64                    3.4.200207-5184             @ntop              
n2n.x86_64                       2.4-71                      @ntop              
ndpi.x86_64                      3.0.0-2242                  @ntop              
nprobe.x86_64                    8.6.200207-6343             @ntop              
ntopng.x86_64                    3.8.200207-5620             @ntop              
ntopng-data.noarch               3.8.200207-5620             @ntop-noarch       
pfring.x86_64                    7.4.0-2835                  @ntop              
pfring-drivers-zc-dkms.noarch    1.2-0                       @ntop-noarch    


Remove unnecessary packages -

yum erase ixgbevf-zc i40e-zc ixgbe-zc igb-zc pfring-drivers-zc-dkms.noarch

System is fully functional.

Update system - 

yum update

Updating e1000e-zc-3.4.0.2.2851-dkms.noarch spawns endless make processes.  After running for 10 minutes it had spawned 7818 make commands.

Restore system and install source code - 

yum install pfring-dkms

Updates cento, n2disk, ndpi, nprobe, ntopng, and pfring

System no longer shows flow data from remote sources

yum update

It updated e1000e-zc.noarch and ntopng-data.noarch packages

Problem still exists

Removing pfring also removes ntopng, nprobe, etc and leaves the system in the same state (no flow data from remote sources).

**Comment by cardigliano** [comment]
@mikemuzinich please open an issue for the driver at https://github.com/ntop/pf_ring/issues
in the meantime I suggest you to remove just the zc driver and use the standard driver until this has been verified and fixed. Thank you.

**Comment by mikemuzinich** [comment]
I removed the e1000e-zc-3.4.0.2.2835-dkms.noarch package which allowed the update to complete but the same problem exists, no data from remote sources.  Guessing it is something to do with either the NTOPNG or NPROBE update.  I will wait for another version to be released before trying it again.  Hopefully it gets fixed.

**Comment by cardigliano** [comment]
@mikemuzinich please provide your ntopng and nprobe configuration files, and the nprobe and ntopng version you are currently using. Thank you.

**Comment by mikemuzinich** [comment]
ntopng.conf
-i=tcp://127.0.0.1:5556
-m=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
-G=/var/run/ntopng.pid
-n=1
--http-port=0
--https-port=443
--max-num-flows 1200000

nprobe.conf
--zmq="tcp://*:5556"
-i=none
-n=none
--collector-port 2055
-T @NTOPNG@
-G
--verbose 2
--syslog probe1

Current versions are:

nprobe-8.6.200207-6343.x86_64
ntopng-3.8.200207-5620.x86_64

**Comment by emanuele-f** [comment]
Please update to the development version of ntopng or wait for the new stable version which will be released this week.

**Comment by LeoBolien** [comment]
Hello,
is this issue fixed in the meantime ?
I have exactly the same problem (also using InfluxDB)

Thanks and regards
Leo

**Comment by emanuele-f** [comment]
The comments described above went off topic. Please open a new issue with detailed information on what issue are you experiencing along with some screenshots. Please also report the output of `ntopng --version`.
