### ISSUE TITLE
Disappearing INFO field in where clause

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3415]
When searching with nIndex adding a WHERE clause INFO="xxx" after submit, the search is performed but the WHERE value disappears

Before submit
![Screen Shot 2020-02-13 at 22 58 14](https://user-images.githubusercontent.com/4493366/74482223-68598b00-4eb4-11ea-8421-d00992255821.png)
After submit
![Screen Shot 2020-02-13 at 22 58 21](https://user-images.githubusercontent.com/4493366/74482226-698ab800-4eb4-11ea-89f1-774c09d8cc8c.png)

**Comment by gabryon99** [comment]
Fixed.
