### ISSUE TITLE
Fields are too packet in the Manage Users page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3416]
![Screen Shot 2020-02-14 at 10 12 48](https://user-images.githubusercontent.com/4493366/74517599-aeddd280-4f12-11ea-8f37-e212cc90b5ff.png)

**Comment by gabryon99** [comment]
Add more spaces between input boxes and selects. 
![Screenshot from 2020-02-14 10-51-42](https://user-images.githubusercontent.com/14114916/74520557-b780d980-4f0f-11ea-860c-14fd572699be.png)

**Comment by gabryon99** [comment]
Fixed.
