### ISSUE TITLE
Implement TCP zero window alert

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3417]
It is requested to trigger an alert In case a TCP connection sets a 0 window size.

**Comment by CyberbreinAirw0lf** [comment]
Two suggestions:
(1) - Consider counting (and report) on the number of 0-win over time => an occasional 0-win may not always indicate there is a real problem.
(2) - Consider a more advanced approach by tracking the window size over time.This could then be used as an early warning system.

In both cases including a breakdown by client and server.

Thanks - Will

**Comment by lucaderi** [comment]
Implemented
