### ISSUE TITLE
Realtime Top Application Traffic stop

### ISSUE THREAD

**Issue by kkkhh** [ntop/ntopng#342]
the Realtime Top Application Traffic in dashboard will stop in few seconds
like the picture below
any one can help me

tks

![_002](https://cloud.githubusercontent.com/assets/16585647/12160513/c0d6c16a-b527-11e5-85dd-a8ca59c0e480.jpg)

**Comment by lucaderi** [comment]
Are you using the pro version without license so after some minutes it will go back to community (without dashboard)?

**Comment by kkkhh** [comment]
here is my license information

![default](https://cloud.githubusercontent.com/assets/16585647/12977734/7fe5cbaa-d107-11e5-9635-e66810eda0cd.JPG)

**Comment by simonemainardi** [comment]
@kkkhh please, post ntopng configuration file or startup string.

also inspect any ntopng console output (or /var/log/ntopng/ntopng.log) for any errors and possibly post them here.

thank you

**Comment by kkkhh** [comment]
here is my config file

-G=/var/tmp/ntopng.pid
--local-networks "192.168.0.0/16,10.10.0.0/16"
--interface ens19

the log errors

16/Feb/2016 03:50:20 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 04:00:19 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 04:10:23 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 04:20:21 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 04:30:21 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 04:40:22 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 04:50:22 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 05:00:22 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 05:10:23 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 05:20:16 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 05:30:08 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 05:40:09 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 05:50:10 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 06:00:09 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 06:10:08 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 06:20:10 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 06:30:09 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 06:40:09 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 06:50:10 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 07:00:11 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 07:10:21 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 07:20:23 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 07:30:20 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 07:40:23 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 07:50:22 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 08:00:23 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 08:10:26 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 08:20:31 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 08:30:31 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 08:40:31 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 08:50:29 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]
16/Feb/2016 09:00:33 [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:38: attempt to perform arithmetic on field 'stats.bytes' (a nil value)]

tks for ur help

**Comment by simonemainardi** [comment]
@kkkhh  I've made some fixes recently. Could you please try and check again? 

btw, have you any alerts configured? If this is the case, try to remove them and see what happens.

Please, let us know.

**Comment by simonemainardi** [comment]
packages will be built overnight and available starting from tomorrow

**Comment by kkkhh** [comment]
![_001](https://cloud.githubusercontent.com/assets/16585647/13414443/f1d689fe-df8d-11e5-87d4-369603a0b7b1.jpg)

here is the version i used
do you mean that i should try the nightly builds packages ?

**Comment by simonemainardi** [comment]
yes, you shoud try nightly builds. I can confirm the issue has been solved with

![image](https://cloud.githubusercontent.com/assets/3397663/13421991/30a1da90-df92-11e5-8480-67192c785e7b.png)

**Comment by kkkhh** [comment]
ok
the problem has been solved 
tks a lot
