### ISSUE TITLE
Active External Alert Flow Json error

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#3420]
When i try to see the Active External Alert Flow i received this error:
![Immagine](https://user-images.githubusercontent.com/47248892/74544524-8f14d180-4f47-11ea-8cd2-c1fb8311148e.png)

14/Feb/2020 16:30:03 [LuaEngine.cpp:12498] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flows_data.lua][...ns/status_definitions/pro/status_malicious_signature.lua:11: attempt to index a nil value (local 'flowstatus_info')]
--

**Comment by cardigliano** [comment]
@zimbawe998 we pushed some fix for external alerts today, could you update to latest revision and let us know if you are still experiencing this? Thank you.

**Comment by emanuele-f** [comment]
No feedback received. Please reopen if necessary
