### ISSUE TITLE
Upgraded to most current version / licensing invalid

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#3422]
Good afternoon, 

I upgraded this afternoon and now my existing licensing is no longer valid for Enterprise.  I know my maintenance expired, but that shouldn't effect my software licensing, correct?  We are a non-profit school and we were given a gratis enterprise license.  

So my main question is: Is this a licensing issue that I need to email sales about or is it a technical issue from the upgrade?

Thanks, 

Derek

**Comment by lucaderi** [comment]
Your answer should be here https://www.ntop.org/support/faq/are-licenses-permanent-what-about-maintenance/

Please email education@ntop.org for a free license
