### ISSUE TITLE
RRD reports a wrong error when failing

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3423]
In the trace below a failure on a RRD reports an error on another RRD. Example tcp.rrd on interface 2, vs ARP.rrd on interface 1

14/Feb/2020 21:20:33 [5min.lua:27] [rrd.lua:382] ERROR: rrd_update_r() [/data/ntopng/2/rrd/X/X/X/X@150/l4protos/tcp.rrd][1581711395:0:0] failed [opening '/data/ntopng/1/rrd/ARP.rrd': No such file or directory]

**Comment by simonemainardi** [comment]
Confirmed. Also seen on another installation

```
17/Feb/2020 19:00:06 [5min.lua:27] [rrd.lua:383] ERROR: rrd_update_r()  [/var/lib/ntopng/0/rrd/xxx/xxx/xxx/xxx/l4protos/icmp.rrd][1581962405:0:0]  failed [/var/lib/ntopng/0/rrd/xxx/xxx/xxx/xxx/l4protos/icmp.rrd: opening  '/var/lib/ntopng/-1/rrd/periodic_script/hourly/lua/ps_duration.rrd': No  such file or directory]
17/Feb/2020 18:50:07 [5min.lua:27] [rrd.lua:383] ERROR: rrd_update_r()  [/var/lib/ntopng/0/rrd/xxx/xxx/xxx/xxx/l4protos/tcp.rrd][1581961791:0:0]  failed [/var/lib/ntopng/0/rrd/xxx/xxx/xxx/xxx/l4protos/tcp.rrd: opening  '/var/lib/ntopng/-1/rrd/periodic_script/5min/lua/ps_duration.rrd': No  such file or directory]
```

Could be the rrd error function which is non-reentrant

**Comment by lucaderi** [comment]
See #3458

**Comment by lucaderi** [comment]
Seems to be solved
