### ISSUE TITLE
Ntopng plugin to grafana not working

### ISSUE THREAD

**Issue by squad1534** [ntop/ntopng#3429]
Back in October the Ntopng plugin for Grafana worked great, since all the upgrades with ntopng and Grafana this plugin stopped working it doesn't not fetch allprotocols or allcategories. Anyone else having this problem?
I'm currently running ntopng v3.9.200212 (8942)

Maybe there's a new switch in the config I'm unaware of?

-d-

**Comment by simonemainardi** [comment]
hi, the plugin has been discontinued as announced at: https://github.com/ntop/ntopng-grafana-datasource#discontinuation-notice
to continue using grafana, just enable the export to influxdb, and then use the grafana influxdb datasource

**Comment by Raptime** [comment]
Hello,
I know this is closed but how are you supposed to get the same information as before? The old graph was showing the top 8 protocols for an interface, using influxdb I cant seem to figure out how to limit the display to the top 8, it shows all protocols which makes the graph difficult to read.
