### ISSUE TITLE
Collapse Multiple Identical Alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3430]
Alert collapse works for flow alerts but it does not work for past alerts.

![Screen Shot 2020-02-17 at 12 28 11](https://user-images.githubusercontent.com/4493366/74650014-0e411a00-5181-11ea-94de-e4ca62f3b765.png)

**Comment by simonemainardi** [comment]
Implemented in https://github.com/ntop/ntopng/commit/4ed8cfecc31d11bf6e6c622d175fc384876a9cce

Similar to what is done for flow alerts, for non-engaged, stored alerts we perform an aggregation if within 5 minutes. Result is as in the following picture (see new column count):

![image](https://user-images.githubusercontent.com/3397663/75269805-cd3cab80-57f9-11ea-89e2-420fbcd4fea8.png)
