### ISSUE TITLE
Geolocation error[Permission denied]: Using default location.

### ISSUE THREAD

**Issue by atrogu** [ntop/ntopng#3436]
Tried with both GeoIP 3.1.1 and 4.1.5. geoipupdate is working and ntopng loads it's databases. ntopng on Centos 7.7 is at it's latest version (v.3.9.200217).

**Comment by gabryon99** [comment]
Hello, can you upload a screenshot of the error? And eventually the console log of your browser?

**Comment by atrogu** [comment]
Thanks, gabryon99.

Here's the screenshot:

![ntopng-geomap](https://user-images.githubusercontent.com/1760205/74721669-0b553080-5238-11ea-9017-8df253c99d03.png)

And here's Firefox's console log:

[console-export-2020-2-18_10-15-3.txt](https://github.com/ntop/ntopng/files/4218324/console-export-2020-2-18_10-15-3.txt)

**Comment by gabryon99** [comment]
Did you disable the location services of your browser?

**Comment by atrogu** [comment]
No, as fas as I remember, but - in doubt - I have checked and deleted all sites from Firefox's geolocation settings, and the problem remains.

**Comment by gabryon99** [comment]
I have done some edits to the code, can you try to pull the latest edits?

**Comment by atrogu** [comment]
Thanks, gabryon99.
I've updated ntopng via yum from rpm.ntop.org. It's now at release 3.9.200221. Is this version updated with your latest edits or do I have to get it from git?
At the moment the error remains but the message is slightly different, as you can see from my screenshot:
![ntopng-geomap-error-2](https://user-images.githubusercontent.com/1760205/75028363-65582f00-54a0-11ea-9609-94afad105beb.png)
I've tried from Firefox, Chrome, Chromium and Opera (each at latest version) on Ubuntu Linux 19.04 and Firefox on Windows 10, and the result is everywhere the same.
But, does this "error" have effect only on my location detection or does it affect hosts geolocation in general (other hosts seem correctly located on the map)?

**Comment by simonemainardi** [comment]
@gabryon99 any news?

**Comment by emanuele-f** [comment]
The message can be safely ignored as the functionality of the map is not impacted by the fact that position is not available. I've removed the alert box in such case and only logged it to the console.

**Comment by atrogu** [comment]
OK, I got it. Thanks.
