### ISSUE TITLE
I want to see a report --- 500 server error - /usr/share/ntopng/scripts/lua/pro/report.lua:319

### ISSUE THREAD

**Issue by gaeunLEE** [ntop/ntopng#344]
I am considering to buy the pro version.

i want to see 'pro version'. it has additional features
" • Ability to generate advanced HTML reports that can be exported in PDF. "

but, i recovery ERROR Massage from REPORT.

ERROR massage is....
[HTTP/1.1 500 Internal server error Content-Type: text/html Connection: close   Script "/usr/share/ntopng/scripts/lua/pro/report.lua" returned an error:]

[/usr/share/ntopng/scripts/lua/pro/report.lua:319: attempt to perform arithmetic on field 'bytes.sent' (a nil value)]

What is the way to solve?

plz reply

**Comment by simonemainardi** [comment]
this has already been fixed. please update to the latest dev version
