### ISSUE TITLE
Unable to compile:  [Makefile:148: src/Flow.o] Error 1

### ISSUE THREAD

**Issue by dtouzeau** [ntop/ntopng#3440]
src/Flow.cpp: In member function ‘void Flow::processExtraDissectedInformation()’:
src/Flow.cpp:476:37: error: ‘struct ndpi_flow_struct::<unnamed union>::<unnamed struct>::<unnamed>’ has no member named ‘alpn’
   && (ndpiFlow->protos.stun_ssl.ssl.alpn != NULL))
                                     ^~~~
src/Flow.cpp:477:64: error: ‘struct ndpi_flow_struct::<unnamed union>::<unnamed struct>::<unnamed>’ has no member named ‘alpn’
  protos.tls.client_alpn = strdup(ndpiFlow->protos.stun_ssl.ssl.alpn);
                                                                ^~~~
src/Flow.cpp:480:37: error: ‘struct ndpi_flow_struct::<unnamed union>::<unnamed struct>::<unnamed>’ has no member named ‘tls_supported_versions’
   && (ndpiFlow->protos.stun_ssl.ssl.tls_supported_versions != NULL))
                                     ^~~~~~~~~~~~~~~~~~~~~~
src/Flow.cpp:481:82: error: ‘struct ndpi_flow_struct::<unnamed union>::<unnamed struct>::<unnamed>’ has no member named ‘tls_supported_versions’
  protos.tls.client_tls_supported_versions = strdup(ndpiFlow->protos.stun_ssl.ssl.tls_supported_versions);
                                                                                  ^~~~~~~~~~~~~~~~~~~~~~
src/Flow.cpp: In member function ‘void Flow::processPacket(const u_char*, u_int16_t, u_int64_t)’:
src/Flow.cpp:567:14: error: ‘ndpi_is_protocol_detected’ was not declared in this scope
   detected = ndpi_is_protocol_detected(iface->get_ndpi_struct(), proto_id);
              ^~~~~~~~~~~~~~~~~~~~~~~~~
src/Flow.cpp:567:14: note: suggested alternative: ‘ndpi_fill_protocol_category’
   detected = ndpi_is_protocol_detected(iface->get_ndpi_struct(), proto_id);
              ^~~~~~~~~~~~~~~~~~~~~~~~~
              ndpi_fill_protocol_category
make: *** [Makefile:148: src/Flow.o] Error 1

**Comment by cardigliano** [comment]
@dtouzeau did you update nDPI?

**Comment by dtouzeau** [comment]
Yes nDPI was updated to latest version

**Comment by cardigliano** [comment]
Please make sure nDPI is updated to latest dev code, ndpiFlow->protos.stun_ssl.ssl.alpn is defined in latest header file

**Comment by simonemainardi** [comment]
Type

Visit nDPI and ntopng sources directories and then type:

`git branch -vv -a`

Make sure the current branch (the one with the `*`) is tracking the `dev` branch of the remote pointing to the official nDPI and ntopng repos. Possibly switch the branch with `git checkout`.

In case you still have troubles submit the output of the command above.

**Comment by dragonxtek** [comment]
Hi,
I have nDPI 3.3.0-2755-ad8318e2, and recently I tried to compile ntopng but I have the same issue

> src/Flow.cpp: In member function ‘void Flow::fillZmqFlowCategory(const ParsedFlow*, ndpi_protocol*) const’:
src/Flow.cpp:3916:83: error: cannot convert ‘long unsigned int*’ to ‘ndpi_protocol_category_t*’
     if(ndpi_match_custom_category(ndpi_struct, (char*)dst_name, strlen(dst_name), &id) == 0)
                                                                                   ^~~
In file included from /usr/local/include/ndpi/ndpi_main.h:31,
                 from /home/dragonxtek/Downloads/ntopng-4.0/include/ntop_includes.h:118,
                 from src/Flow.cpp:22:
/usr/local/include/ndpi/ndpi_api.h:831:60: note:   initializing argument 4 of ‘int ndpi_match_custom_category(ndpi_detection_module_struct*, char*, u_int, ndpi_protocol_category_t*)’
      char *name, u_int name_len, ndpi_protocol_category_t *id);
make: *** [Makefile:148: src/Flow.o] Error 1
