### ISSUE TITLE
Traffic Dashboard name resolution failed

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#3441]
Some time We see a nemre resolution problem on Traffic dashboard

![image](https://user-images.githubusercontent.com/47248892/74835629-0cf92400-531e-11ea-8e33-e60e5f20948e.png)

but in the host page the name is correct
![image](https://user-images.githubusercontent.com/47248892/74835681-2ac68900-531e-11ea-942b-a8931b06d2c6.png)

**Comment by emanuele-f** [comment]
Please post the output of the following commands:

```
redis-cli hget ntopng.host_labels the_host_ip
redis-cli hget ntopng.host_labels the_host_mac
redis-cli hget ntopng.dhcp.the_interface_id.cache the_host_ip
redis-cli hget ntopng.dhcp.the_interface_id.cache the_host_mac
```
Properly replacing `the_host_ip`, `the_host_mac` and `the_interface_id` with your values

**Comment by zimbawe998** [comment]
HI Emanule,
on my situation ntopng GUI show a different name than the command output.

**Comment by emanuele-f** [comment]
Please post the result of each of the individual commands and the result shown in the gui. Please consider sending private data to faranda@ntop.org

**Comment by simonemainardi** [comment]
any news here?

**Comment by emanuele-f** [comment]
Please refer to #3699
