### ISSUE TITLE
Bad string abbreviation

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3442]
Short strings are abbreviated even if they should not

![2020-02-19_18-28](https://user-images.githubusercontent.com/5488003/74858480-4f7e2900-533d-11ea-9280-bfbc8ac1e989.png)

**Comment by gabryon99** [comment]
Ok now is fixed within the last commit

**Comment by emanuele-f** [comment]
Commit 35551e8b01938c875315b78573882c7507926283, please report the hash next time.
