### ISSUE TITLE
Pref toggle not working in Runtime Preferences -> Alerts

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#3443]
Alerts are enabled, however the toggle is off (you can notice all alerts tabs correctly displayed as alerts are actually enabled)

<img width="1081" alt="Screen Shot 2020-02-21 at 16 50 47" src="https://user-images.githubusercontent.com/7548711/75049395-6736e800-54ca-11ea-8b4c-4a5e5f4e70df.png">

**Comment by gabryon99** [comment]
I have fixed the issue. The problem was on the evaluation of lua's value.
