### ISSUE TITLE
implement table header summary

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3445]
ntopng is too table-oriented, and it would be nice to have a summary on top of tables similar to github. 

![Screen Shot 2020-02-22 at 07 55 12](https://user-images.githubusercontent.com/4493366/75088080-ae63be00-5548-11ea-805d-5693ea3c2db0.png)

**Comment by gabryon99** [comment]
To integrate a simple summary table it's very simple. The endpoint answer must include a `summary` field with these attributes:
```
response.summary = [
              {
                percentage: 25,
                label: 'Hello World 1!'
              },
              {
                percentage: 25,
                label: 'Hello World 2!'
              },
              {
                percentage: 25,
                label: 'Hello World 3!'
              },
              {
                percentage: 25,
                label: 'Hello World 4!'
              }
]
```
