### ISSUE TITLE
missing interface 

### ISSUE THREAD

**Issue by tezcangulnaz** [ntop/ntopng#345]
I am currently using 2 interface one of them Mirroring and another one is Sflow collecting port
but after updating NtopNG  , its just showing and listening eth0 interface which is working as collector port on 5556 port on eth0 but eth1 which is mirroring channel is missing and can't seen any traffic  even though its defined in ntopng.conf file below.

-i "tcp://*:5556"
-i "eth1"

what is the problem exactly after updating?

**Comment by tezcangulnaz** [comment]
it says unknown interface when i start ntopng manually in console.
08/Jan/2016 18:05:24 [MySQLDB.cpp:360] Succesfully connected to MySQL [localhost:root] for interface eth1
08/Jan/2016 18:05:24 [main.cpp:202] ERROR: Unable to create interface eth1
08/Jan/2016 18:05:24 [MySQLDB.cpp:320] Attempting to connect to MySQL for interface tcp://10.10.1.16:5556...
08/Jan/2016 18:05:24 [MySQLDB.cpp:360] Succesfully connected to MySQL [localhost:root] for interface tcp://10.10.1.16:5556
08/Jan/2016 18:05:24 [Ntop.cpp:1148] Registered interface tcp://10.10.1.16:5556 [id: 3]
08/Jan/2016 18:05:24 [NetworkInterfaceView.cpp:35] ERROR: Unknown interface eth1: skept

**Comment by lucaderi** [comment]
I think problem is generated either for lack or rights (no root) or because eth1 is either unavailable or down.
