### ISSUE TITLE
Move system into the top menu

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3450]
The system icon 
![Screen Shot 2020-02-24 at 18 45 04](https://user-images.githubusercontent.com/4493366/75177111-ccdadc80-5735-11ea-9852-aff70f1750de.png)
should be moved to the top interface menu
![Screen Shot 2020-02-24 at 19 06 49](https://user-images.githubusercontent.com/4493366/75178691-de71b380-5738-11ea-9cb7-48da728c7d71.png)

**Comment by gabryon99** [comment]
Fixed.
