### ISSUE TITLE
Network setting button

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#3451]
I just tried to label a network but i received this error
 Script "/usr/share/ntopng/scripts/lua/network_details.lua" returned an error:
/usr/share/ntopng/scripts/lua/network_details.lua:69: unexpected symbol near ','

**Comment by zimbawe998** [comment]
The same error appear when i try to see network traffic chart

**Comment by simonemainardi** [comment]
Thanks for reporting. A new build with the fix is in progress.
