### ISSUE TITLE
Feature Request: Pushover.net alert transport support

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#3454]
Hi all,

It would be nice to have integration with pushover, so we admins can get updated alerts using this tool....

https://pushover.net/api /https://pushover.net/clients

Thanks

**Comment by simonemainardi** [comment]
@StewAlexanderACC would you be interested in taking care of the development of an alert endpoint dedicated to pushover? That would require some basic Lua scripting knowledge and we could guide you.

**Comment by simonemainardi** [comment]
As we won't be able to accomodate this request, I'm closing for now. If you think you can lead this development, feel free to comment and we'll provide you all the necessary information and support.

**Comment by StewAlexander-com** [comment]
Not at the moment, but perhaps in the future, I'll reach out ...
