### ISSUE TITLE
Some timeseries could be merged

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3457]
In order to reduce the number of timeseries, there are some timeseries that could be merged. For instance ntopng writes for each interface
- packets
- drops

Instead of writing two timeseries, only one timeseries could be written.

**Comment by emanuele-f** [comment]
- Packets and drops merged in ea4f936d079d7fef8e700905316b5057b5fcbfd8
- Exported/dropped flows merged in b194643a188e61d7b3d242cb898c74e8af71973f
