### ISSUE TITLE
Telemetry Debug Timeseries must be activated with a preference

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3459]
Telemetry Debug Timeseries create a lot of pressure on heavy loaded systems. They need to be disabled by default and enabled only via a preference.

Feb 27 09:21:11 ntop ntopng[7222]: [RRD][Step: 5][{"file":"/data/ntopng/6/rrd/flow_user_script/tls_certificate_expired/flow/num_calls.rrd"}][0]
Feb 27 09:21:11 ntop ntopng[7222]: [RRD][Step: 5][{"file":"/data/ntopng/6/rrd/flow_user_script/blacklisted/flow/duration.rrd"}][0]
Feb 27 09:21:11 ntop ntopng[7222]: [RRD][Step: 5][{"file":"/data/ntopng/6/rrd/flow_user_script/blacklisted/flow/num_calls.rrd"}][0]
Feb 27 09:21:11 ntop ntopng[7222]: [RRD][Step: 5][{"file":"/data/ntopng/6/rrd/flow_user_script/tls_old_version/flow/duration.rrd"}][0]
Feb 27 09:21:11 ntop ntopng[7222]: [RRD][Step: 5][{"file":"/data/ntopng/6/rrd/flow_user_script/tls_old_version/flow/num_calls.rrd"}][0]
Feb 27 09:21:11 ntop ntopng[7222]: [RRD][Step: 5][{"file":"/data/ntopng/6/rrd/flow_user_script/long_lived/flow/duration.rrd"}][0]
Feb 27 09:21:11 ntop ntopng[7222]: [RRD][Step: 5][{"file":"/data/ntopng/6/rrd/flow_user_script/long_lived/flow/num_calls.rrd"}][0]
Feb 27 09:21:11 ntop ntopng[7222]: [RRD][Step: 5][{"file":"/data/ntopng/6/rrd/flow_user_script/external_alert_check/flow/duration.rrd"}][0]
Feb 27 09:21:11 ntop ntopng[7222]: [RRD][Step: 5][{"file":"/data/ntopng/6/rrd/flow_user_script/external_alert_check/flow/num_calls.rrd"}][0]
Feb 27 09:21:11 ntop ntopng[7222]: [RRD][Step: 5][{"file":"/data/ntopng/6/rrd/flow_user_script/web_mining/flow/duration.rrd"}][0]

**Comment by simonemainardi** [comment]
Should be already handled with:

- https://github.com/ntop/ntopng/commit/31e0e617d4080e2d018c31297e732945b287e119
- https://github.com/ntop/ntopng/commit/5af54399f34fd1c7b5f9d3edca33ffeff59aaee7

By default, highlighted timeseries are off and can be turned on with a preference. Please, update to the latest version and report.

**Comment by simonemainardi** [comment]
Preference added (default off):

![image](https://user-images.githubusercontent.com/3397663/75554528-ca7cc900-5a3a-11ea-9a8b-08da3a98a2f1.png)

Name chosen is "Internals" to avoid confusion with the "Telemetry", already used when people decide to contribute their ntopng data from 

![image](https://user-images.githubusercontent.com/3397663/75554577-e84a2e00-5a3a-11ea-98fb-7c1f88ff1761.png)
