### ISSUE TITLE
Invalid Alerts Report

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3464]
![Screen Shot 2020-02-27 at 18 40 29](https://user-images.githubusercontent.com/4493366/75470246-ac5a8e80-5990-11ea-83be-fc4380fb5649.png)

This report has a few flaws:
- No value is reported (not even zero) even though there are alerts dropped
- it must be collapsed in one line named "Alerts" with a few cells "Queries", "Alerts Written", "Alerts Drops"

**Comment by lucaderi** [comment]
![Screen Shot 2020-02-27 at 21 46 59](https://user-images.githubusercontent.com/4493366/75485317-c4d7a280-59aa-11ea-8dc8-d6ab3a633255.png)
Missing values just dots

**Comment by simonemainardi** [comment]
Reworked to make it consistent with the other table entries:

![image](https://user-images.githubusercontent.com/3397663/75559054-1895ca80-5a43-11ea-9fdd-98b876b2fe5b.png)
