### ISSUE TITLE
changing IP/MAC alert is always(?) followed by core dump on osx

### ISSUE THREAD

**Issue by dirkduellmann** [ntop/ntopng#3467]
I'm running the current brew version of ntop (see also screen dump with version) on a up-to-date osx catalina 10.15.3:

Whenever one of monitored interfaces is changing IP/MAC (eg when a sleep-proxy takes over / returns an IP of an energy saving device)  ntop will core dump immediately after printing the alert. The core dump also takes place if the alert itself is configured as disabled.  

If this is new/unknown I can provide more details.

See the attached screen dump for details.
![Image 27 02 2020](https://user-images.githubusercontent.com/6027299/75480484-b042dc80-59a1-11ea-82c0-3492d10699ad.jpg)

Thanks for the brilliant tool - Dirk

**Comment by emanuele-f** [comment]
Please ensure that you are using the latest ntopng version, then post here the output of `ntopng --version`. Can you provide a stack trace of the issue? You should be able to do that by using `lldb` in a simular way as gdb (https://github.com/ntop/ntopng/blob/dev/doc/README.crash)

**Comment by simonemainardi** [comment]
working properly on the 3.9 OS X build

![image](https://user-images.githubusercontent.com/3397663/75803372-98db6900-5d7e-11ea-8977-5347b2b7d905.png)

As 3.8 is end-of-life we are not going to fix it. However, we are in the process of releasing ntopng stable 4.0. Release will be in a few days from now. So you can either wait for the 4.0 or, if you want to stay with 3.8, you can turn off this type of alerts from the preferences.

**Comment by dirkduellmann** [comment]
thanks - I'm happy to re-test in my env again once 4.x is out on brew.
