### ISSUE TITLE
Unexpected Shutdown & List 'name' has 0 rules

### ISSUE THREAD

**Issue by HNJBB** [ntop/ntopng#3468]
Feb 28 00:00:05 ntop ntopng[1722]: 28/Feb/2020 00:00:05 [MySQLDB.cpp:824] Attempting to connect to MySQL for interface tcp://127.0.0.1:5556...
Feb 28 00:00:05 ntop ntopng[1722]: 28/Feb/2020 00:00:05 [MySQLDB.cpp:850] Successfully connected to MySQL [root@localhost:3306] for interface tcp://127.0.0.1:5556
Feb 28 00:00:26 ntop ntopng[1722]: 28/Feb/2020 00:00:26 [main.cpp:50] Shutting down...
Feb 28 00:00:26 ntop systemd[1]: Stopping ntopng high-speed web-based traffic monitoring and analysis tool...
Feb 28 00:00:28 ntop ntopng[1722]: 28/Feb/2020 00:00:28 [Ntop.cpp:2370] Terminating periodic activities
Feb 28 00:00:50 ntop ntopng[1722]: [housekeeping.lua:32] [lists_utils.lua:584] WARNING: List 'Cisco Talos Intelligence' has 0 rules. Please report this to https://github.com/ntop/ntopng
Feb 28 00:00:50 ntop ntopng[1722]: 28/Feb/2020 00:00:50 [housekeeping.lua:32] [lists_utils.lua:584] WARNING: List 'Cisco Talos Intelligence' has 0 rules. Please report this to https://github.com/ntop/ntopng
Feb 28 00:00:50 ntop ntopng[1722]: [housekeeping.lua:32] [lists_utils.lua:584] WARNING: List 'Emerging Threats' has 0 rules. Please report this to https://github.com/ntop/ntopng
Feb 28 00:00:50 ntop ntopng[1722]: 28/Feb/2020 00:00:50 [housekeeping.lua:32] [lists_utils.lua:584] WARNING: List 'Emerging Threats' has 0 rules. Please report this to https://github.com/ntop/ntopng
Feb 28 00:00:50 ntop ntopng[1722]: [housekeeping.lua:32] [lists_utils.lua:584] WARNING: List 'Feodo Tracker Botnet C2 IP Blocklist' has 0 rules. Please report this to https://github.com/ntop/ntopng
Feb 28 00:00:50 ntop ntopng[1722]: 28/Feb/2020 00:00:50 [housekeeping.lua:32] [lists_utils.lua:584] WARNING: List 'Feodo Tracker Botnet C2 IP Blocklist' has 0 rules. Please report this to https://github.com/ntop/ntopng
Feb 28 00:00:50 ntop ntopng[1722]: [housekeeping.lua:32] [lists_utils.lua:584] WARNING: List 'NoCoin Filter List' has 0 rules. Please report this to https://github.com/ntop/ntopng
Feb 28 00:00:50 ntop ntopng[1722]: 28/Feb/2020 00:00:50 [housekeeping.lua:32] [lists_utils.lua:584] WARNING: List 'NoCoin Filter List' has 0 rules. Please report this to https://github.com/ntop/ntopng
Feb 28 00:00:50 ntop ntopng[1722]: [housekeeping.lua:32] [lists_utils.lua:584] WARNING: List 'SSLBL Botnet C2 IP Blacklist' has 0 rules. Please report this to https://github.com/ntop/ntopng
Feb 28 00:00:50 ntop ntopng[1722]: 28/Feb/2020 00:00:50 [housekeeping.lua:32] [lists_utils.lua:584] WARNING: List 'SSLBL Botnet C2 IP Blacklist' has 0 rules. Please report this to https://github.com/ntop/ntopng
Feb 28 00:00:50 ntop ntopng[1722]: [housekeeping.lua:32] [lists_utils.lua:584] WARNING: List 'SSLBL JA3' has 0 rules. Please report this to https://github.com/ntop/ntopng
Feb 28 00:00:50 ntop ntopng[1722]: 28/Feb/2020 00:00:50 [housekeeping.lua:32] [lists_utils.lua:584] WARNING: List 'SSLBL JA3' has 0 rules. Please report this to https://github.com/ntop/ntopng
Feb 28 00:00:50 ntop ntopng[1722]: 28/Feb/2020 00:00:50 [Ntop.cpp:2376] Executing shutdown script
Feb 28 00:00:51 ntop ntopng[1722]: 28/Feb/2020 00:00:51 [ProtoStats.cpp:35] [IPv4]  37.11 TB/48102.64 M Packets
Feb 28 00:00:51 ntop ntopng[1722]: 28/Feb/2020 00:00:51 [ProtoStats.cpp:35] [IPv6]  0 B/0.00 Packets
Feb 28 00:00:51 ntop ntopng[1722]: 28/Feb/2020 00:00:51 [ProtoStats.cpp:35] [ARP]   0 B/0.00 Packets
Feb 28 00:00:51 ntop ntopng[1722]: 28/Feb/2020 00:00:51 [ProtoStats.cpp:35] [MPLS]  0 B/0.00 Packets
Feb 28 00:00:51 ntop ntopng[1722]: 28/Feb/2020 00:00:51 [ProtoStats.cpp:35] [Other] 0 B/0.00 Packets
Feb 28 00:00:51 ntop ntopng[1722]: 28/Feb/2020 00:00:51 [Ntop.cpp:2359] Polling shut down [interface: tcp://127.0.0.1:5556]
Feb 28 00:00:51 ntop ntopng[1722]: 28/Feb/2020 00:00:51 [Ntop.cpp:2393] Deleted PID /var/run/ntopng.pid: [rc: -1][Permission denied]
Feb 28 00:00:53 ntop ntopng[1722]: 28/Feb/2020 00:00:53 [HTTPserver.cpp:1350] HTTP server terminated
Feb 28 00:00:53 ntop ntopng[1722]: 28/Feb/2020 00:00:53 [NetworkInterface.cpp:541] Flushing host contacts for interface tcp://127.0.0.1:5556
Feb 28 00:00:54 ntop ntopng[1722]: 28/Feb/2020 00:00:54 [NetworkInterface.cpp:2372] Cleanup interface tcp://127.0.0.1:5556
Feb 28 00:01:03 ntop ntopng[1722]: 28/Feb/2020 00:01:03 [MySQLDB.cpp:744] Disconnected from MySQL for interface tcp://127.0.0.1:5556...
Feb 28 00:01:03 ntop ntopng[1722]: 28/Feb/2020 00:01:03 [MySQLDB.cpp:744] Disconnected from MySQL for interface tcp://127.0.0.1:5556...
Feb 28 00:01:03 ntop ntopng[1722]: 28/Feb/2020 00:01:03 [MySQLDB.cpp:744] Disconnected from MySQL for interface tcp://127.0.0.1:5556...
Feb 28 00:01:03 ntop ntopng[1722]: 28/Feb/2020 00:01:03 [AddressResolution.cpp:63] Address resolution stats [0 resolved][197 failures]
Feb 28 00:01:03 ntop systemd[1]: Stopped ntopng high-speed web-based traffic monitoring and analysis tool.

**Comment by emanuele-f** [comment]
Please report the output of `ntopng --version`

**Comment by HNJBB** [comment]
ntopng --version
v.3.9.200211    [Enterprise/Professional build]
GIT rev:        dev:20fe918d665e6556ef759d7aa7d6f25b2faaab24:20200211
Pro rev:        r2710
Built on:       Ubuntu 18.04.3 LTS
System Id:      6F001919B2066B13
Platform:       x86_64
Edition:        Enterprise
License Type:   Permanent
Maintenance:    Until Thu Jun 18 13:27:17 2020 [111 days left]

**Comment by emanuele-f** [comment]
![2020-02-28_12-24](https://user-images.githubusercontent.com/5488003/75545082-3c461a00-5a1d-11ea-8f85-3fe8efe9dbb4.png)
![2020-02-28_12-24_1](https://user-images.githubusercontent.com/5488003/75545083-3ea87400-5a1d-11ea-8efc-ab359bc8f6a1.png)

You can retrieve the failing lists URL from the link above. If you try to access that url from the ntopng server, can you successfully do that? E.g. can you succesfully run `curl -L https://talosintelligence.com/documents/ip-blacklist` and get the list?

How often does the unexpected shutdown occur?

**Comment by HNJBB** [comment]
Server can retrieve the lists.  And ntopng has also since retrieved the lists.   The unexpected shutdown has only occurred this one time.   Though we are only recently using ntopng in a production enviroment.

**Comment by emanuele-f** [comment]
This issue occurs if ntopng is stopped during its startup phase
