### ISSUE TITLE
Wrong reboot/shutdown buttons position in nEdge

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3469]
Buttons should be moved to the upper right position in top bar as it happens on ntopng.
![2020-02-28_11-54](https://user-images.githubusercontent.com/5488003/75542927-a90ae580-5a18-11ea-92c7-fb90e042c06c.png)

**Comment by gabryon99** [comment]
Done, the buttons were moved under the user icon in the top navbar. See https://github.com/ntop/ntopng/commit/b2631b5fdcd3b13bbde5dab00fd4f603556a2cbe.
