### ISSUE TITLE
Missing EXPORTER_IPV4_ADDRESS and EXPORTER_IPV6_ADDRESS fields for nBPF filter

### ISSUE THREAD

**Issue by hugleo** [ntop/ntopng#3470]
Missing EXPORTER_IPV4_ADDRESS and EXPORTER_IPV6_ADDRESS fields for nBPF filter (interface disaggregation). 

I need to separated between two different routers.

![invalid-filter](https://user-images.githubusercontent.com/4573505/75548596-6e02b500-5a0c-11ea-8fd7-67e70e061c59.png)

**Comment by simonemainardi** [comment]
Did you try to select the ProbeIP from this dropdown? That should to the trick automatically

![image](https://user-images.githubusercontent.com/3397663/75551187-e4ff7400-5a33-11ea-8e45-1d3efcfc3be2.png)

**Comment by hugleo** [comment]
Probe IP worked however ntopng creates a aggregated interface and in my router I have two interfaces, multiples vlans:

set interfaces ge-0/0/0 unit 10 family inet sampling input
set interfaces ge-0/0/1 unit 20 family inet sampling input

How can I differentiate between those in ntopng?

**Comment by cardigliano** [comment]
@hugleo please try using single quotes (I will add a comment about this syntax to the GUI)
EXPORTER_IPV4_ADDRESS '192.168.0.1'

**Comment by hugleo** [comment]
Updated ntopng and is working for ipv4.
But for ipv6 tried the following filter:
EXPORTER_IPV6_ADDRESS '1234:567:0:1::1' and (INPUT_SNMP 123 or OUTPUT_SNMP 123)
The interface is created but looks like I'm not seeing any flow.

**Comment by cardigliano** [comment]
@hugleo I pushed a patch to support EXPORTER_IPV6_ADDRESS, a new package will be available in ~1h.

**Comment by hugleo** [comment]
Updated but not getting any ipv6 flow yet

**Comment by hugleo** [comment]
My tests:

(INPUT_SNMP 123 or OUTPUT_SNMP 123)	ipv4 and ipv6 flows are received (ok)

EXPORTER_IPV4_ADDRESS '192.168.0.1' and (INPUT_SNMP 123 or OUTPUT_SNMP 123) only ipv4 flows received (ok)

EXPORTER_IPV6_ADDRESS '1234:567:0:1::1'	and (INPUT_SNMP 123 or OUTPUT_SNMP 123) no flow received at all (not ok)

**Comment by cardigliano** [comment]
@hugleo are you using nProbe as a proxy collecting Netflow and sending flows to ntopng via ZMQ? Are you able to provide a pcap with your Netflow traffic (and your nProbe configuration) to reproduce this? Thank you.

**Comment by hugleo** [comment]
@cardigliano I sent some data to your email

**Comment by cardigliano** [comment]
@hugleo it seems that nProbe is not currently exporting EXPORTER_IPV6_ADDRESS, I moved this issue to https://github.com/ntop/nProbe/issues/407
