### ISSUE TITLE
Duplicate Disaggregated Traffic toggle not working

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3471]
Clicking on the toggle has no effect. Trying to change the dropdown above doesn't affect the behavior.

![image](https://user-images.githubusercontent.com/3397663/75551012-7fab8300-5a33-11ea-9e64-4d873ac42f72.png)

**Comment by gabryon99** [comment]
What's the page?

**Comment by simonemainardi** [comment]
the wheel under the 'Interface':

<img width="863" alt="image" src="https://user-images.githubusercontent.com/3397663/75862396-2e1e4200-5dff-11ea-9d7e-aa1fdcc35f3f.png">

**Comment by gabryon99** [comment]
![Mar-05-2020 09-36-20](https://user-images.githubusercontent.com/14114916/75962873-d3e7b480-5ec4-11ea-9d87-e82b3eeef99d.gif)

Now is fixed, the problem was caused by a mismatched id inside the label.

**Comment by gabryon99** [comment]
Here is the commit: https://github.com/ntop/ntopng/commit/aee9148d1e04193a8b6b531d5c63171c644276f1
