### ISSUE TITLE
attempt to concatenate a nil value in lua_utils.lua

### ISSUE THREAD

**Issue by gregober** [ntop/ntopng#3474]
I am not sure where this "nil value" is coming from ? 
I am trying to access "Host >> Host Pool >> Chart associated to a pool" 

This is reported as a bug and triggers an error : 

HTTP/1.1 500 Internal server error Content-Type: text/html Connection: close Script "/usr/share/ntopng/scripts/lua/pool_details.lua" returned an error: /usr/share/ntopng/scripts/lua/modules/lua_utils.lua:3427: attempt to concatenate a nil value

**Comment by simonemainardi** [comment]
Fixed in c9dfafe235d6c0d5746f8a924b62deafdc88625b. New build is in progress. Thanks for reporting.
