### ISSUE TITLE
/usr/share/ntopng/scripts/locales/pt.lua:2083: missing '{' near '"Distribui\u0'

### ISSUE THREAD

**Issue by rodrigoselau** [ntop/ntopng#3475]
hello, 

I'm having a problem, I installed ntopng as the tutorial suggests, but this error appears after changing the admin user password

/usr/share/ntopng/scripts/locales/pt.lua:2083: missing '{' near '"Distribui\u0'

**Comment by simonemainardi** [comment]
Thanks for reporting. Fixed. New build in progress.
