### ISSUE TITLE
Add max duration in activity_descr

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3477]
In the table below the script deadine is set to the periodicity that is a wrong assumption for all scripts. Add a new column that specifies the maximum script duration that that is used for the script deadline. Duration  must be reasonable and NOT set to the periodicity when not necessary

  static activity_descr ad[] = {
    /* Script               Periodicity  Pool                    Align  !View  !PCAP  Reuse */
    { SECOND_SCRIPT_PATH,             1, standard_priority_pool, false, false, true,  true  },
    { HT_STATE_UPDATE_SCRIPT_PATH,    5, high_priority_pool,     false, true,  false, true  },
    { STATS_UPDATE_SCRIPT_PATH,       5, standard_priority_pool, false, false, true,  true  },
    { MINUTE_SCRIPT_PATH,            60, no_priority_pool,       false, false, true,  false },
    { FIVE_MINUTES_SCRIPT_PATH,     300, longrun_priority_pool,  false, false, true,  false },
    { HOURLY_SCRIPT_PATH,          3600, longrun_priority_pool,  false, false, true,  false },
    { DAILY_SCRIPT_PATH,          86400, no_priority_pool,       true,  false, true,  false },
    { HOUSEKEEPING_SCRIPT_PATH,       3, standard_priority_pool, false, false, false, true  },
    { DISCOVER_SCRIPT_PATH,           5, no_priority_pool,       false, false, true,  true  },
    { TIMESERIES_SCRIPT_PATH,         5, standard_priority_pool, false, false, true,  true  },
#ifdef HAVE_NEDGE
    { PINGER_SCRIPT_PATH,             5, no_priority_pool,       false, false, true,  false },
#endif
    { NULL, 0, NULL, false, false, false, false }
  };

**Comment by simonemainardi** [comment]
implemented in the commit above
