### ISSUE TITLE
Invalid RRD point reported

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3478]
![Screen Shot 2020-03-01 at 21 02 05](https://user-images.githubusercontent.com/4493366/75632793-f7c6a400-5bff-11ea-9997-99341f20384e.png)

This is a regression bug. You're reporting the last point as 0. This is wrong as the point is in the future so assuming it to be zero is wrong.

**Comment by emanuele-f** [comment]
Note: not a regression. This behaviour was only implemented in InfluxDB. Now fixed in RRD.
