### ISSUE TITLE
Add support of SIP/RTP nProbe-augmented flows 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#348]
ntopng should be able to interpret SIP/RTP flow information generated by nProbe + SIP/RTP Plugin

**Comment by simonemainardi** [comment]
@ValentinaViscarelli can you update on the progress? Is this completed? Can we close this?

**Comment by simonemainardi** [comment]
Implemented in:
- https://github.com/ntop/ntopng/blob/dev/scripts/lua/flow_details.lua#L502
- https://github.com/ntop/ntopng/blob/dev/scripts/lua/flow_details.lua#L516
