### ISSUE TITLE
ntopng startup errors on Ubuntu 18.04

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3480]
Installing  brand new ntopng (dev from March 1st) at ntopng startup this is what happens

# service ntopng status
* ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-03-01 21:52:32 CET; 16s ago
  Process: 8947 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|^[ ]*--pid.*/s/^/#/" /etc/ntopng/ntopng.conf > /run/ntopng.conf (code=exited, status=0/SUC
  Process: 8933 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exited, status=0/SUCCES
 Main PID: 8949 (ntopng)
    Tasks: 13 (limit: 4915)
   CGroup: /system.slice/ntopng.service
           `-8949 /usr/local/bin/ntopng /run/ntopng.conf

Mar 01 21:52:36 pc-ccc ntopng[8949]: 01/Mar/2020 21:52:36 [AlertsManager.cpp:83] WARNING: Unable to create directory /var/lib/ntopng/4/alerts/
Mar 01 21:52:36 pc-ccc ntopng[8949]: [Utils.cpp:658] WARNING: mkdir(/var/lib/ntopng/12/top_talkers/) failed [13/Permission denied]
Mar 01 21:52:36 pc-ccc ntopng[8949]: 01/Mar/2020 21:52:36 [Utils.cpp:658] WARNING: mkdir(/var/lib/ntopng/12/top_talkers/) failed [13/Permission denied]
Mar 01 21:52:36 pc-ccc ntopng[8949]: [StatsManager.cpp:42] WARNING: Unable to create directory /var/lib/ntopng/12/top_talkers/
Mar 01 21:52:36 pc-ccc ntopng[8949]: 01/Mar/2020 21:52:36 [StatsManager.cpp:42] WARNING: Unable to create directory /var/lib/ntopng/12/top_talkers/
Mar 01 21:52:36 pc-ccc ntopng[8949]: [Utils.cpp:658] WARNING: mkdir(/var/lib/ntopng/12/alerts/) failed [13/Permission denied]
Mar 01 21:52:36 pc-ccc ntopng[8949]: 01/Mar/2020 21:52:36 [Utils.cpp:658] WARNING: mkdir(/var/lib/ntopng/12/alerts/) failed [13/Permission denied]
Mar 01 21:52:36 pc-ccc ntopng[8949]: [AlertsManager.cpp:83] WARNING: Unable to create directory /var/lib/ntopng/12/alerts/
Mar 01 21:52:36 pc-ccc ntopng[8949]: 01/Mar/2020 21:52:36 [AlertsManager.cpp:83] WARNING: Unable to create directory /var/lib/ntopng/12/alerts/
Mar 01 21:52:36 pc-ccc ntopng[8949]: 01/Mar/2020 21:52:36 [PeriodicActivities.cpp:103] Started periodic activities loop...

The problem is that ntopng creates the directory as root instead of being ntopng

/var/lib# ls -la  /var/lib/ntopng
total 108
drwx------   5 ntopng ntopng  4096 Mar  1 21:52 -1
drwx------  11 ntopng ntopng  4096 Mar  1 21:53 .
drwxr-xr-x 113 root   root    4096 Mar  1 21:52 ..
drwx------   4 root   root    4096 Mar  1 21:52 0
drwx------   4 root   root    4096 Mar  1 21:52 1
drwx------   4 root   root    4096 Mar  1 21:52 12
drwx------   4 root   root    4096 Mar  1 21:52 2
drwx------   4 root   root    4096 Mar  1 21:52 3
drwx------   4 root   root    4096 Mar  1 21:52 4
drwx------   2 ntopng ntopng  4096 Mar  1 21:52 category_lists
drwx------  11 ntopng ntopng  4096 Mar  1 21:52 plugins
-rw-------   1 ntopng ntopng 61794 Mar  1 21:53 runtimeprefs.json

**Comment by emanuele-f** [comment]
Cannot reproduce. Also no race condition can be found in the code. Please report:

- Full log since startup
- The ntopng configuration used if different from the default
