### ISSUE TITLE
MUD Plugin does not seem to work as expected

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3481]
The MUD plugin, when enabled, is supposed to learn a host behaviour and then enforce it. The current implementation is not easy to use (if any) from the web GUI, and furthermore it does not seem to work.

**Comment by emanuele-f** [comment]
My proposal is to simply add a multiple selection list with the device types into the MUD configuration. Local hosts matching such device types should have their MUD automatically enabled. (the special/generic purpose flag can be determined automaticaly from the device type). Alert generation for the MUD was never implemented.

**Comment by emanuele-f** [comment]
Proposal reviewed. Additional changes:

- Add a "max recording" option to avoid filling redis with MUD information
- The "max recording" preference should be shown as a combo selection with values "1h", "1day", "1 week"
- The host overview page should show a link to the host MUD
- A recording icon should be added to the hosts whose MUD is being recorded

**Comment by emanuele-f** [comment]
Implemented in 94f175194b8edf1018de92c423bc3fbed4690e57 and c7b2f12cc1b472b7244b31759a1670df71b117a8
