### ISSUE TITLE
High number of queries per write

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3483]
The following stats reports a problem: write require read and this contributes to break the performance. Is this avoidable?

<img width="499" alt="Screenshot 2020-03-02 at 09 40 13" src="https://user-images.githubusercontent.com/4493366/75659194-de5a4200-5c69-11ea-8e4d-175e8405c4ff.png">

Can you please add percentages next to the numbers to understand how the system behaves?

**Comment by simonemainardi** [comment]
Currently, two queries are performed when inserting each alert.

The first query is a lookup and is necessary to check for equal alerts already existing in the database within a period of 5 minutes. The second query is either an update of an existing record (in case an equal alert already exists) or an insertion of a new alert (when no equal alert exists).

I would suggest to use a redis key with a 5-minute timeout which is added every time a new alert is inserted in the database. The value of this key would be the rowid of the inserted alert. In this case, one can directly test for the existence of the redis key to determine whether an equal alert exists, reducing the number of queries from 2 to 1. In addition, by using the rowid, the update query would be more efficient as it would only involve a primary-key database lookup.

**Comment by simonemainardi** [comment]
Commit https://github.com/ntop/ntopng/commit/354a5ed404eae68be5cfdfe69cd9565e9d2720e5 handles deleted alerts which have been cached

**Comment by simonemainardi** [comment]
Percentage has been added so that dropped alerts can be easily compared with the stored alerts.

The caching mechanism described has been implemented for alerts (see referenced commits) so that only one query is now necessary.

Currently, the caching mechanism is not effective for flow alerts as they require a more complex logic (certain alerts are overwritten).
