### ISSUE TITLE
Manage Data menu position

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3484]
Manage data should not stay under the system interface as it allows the download and deletion of hosts of the selected interface

![image](https://user-images.githubusercontent.com/3397663/75663154-a86c8c00-5c70-11ea-8ec4-8e523dfe0946.png)

The only two functionalities that are meaningful in the system interface are 'delete inactive interfaces data' and 'delete system interface data'

**Comment by lucaderi** [comment]
In essence
- move the above page from the system interface to every interface with the exception of the two buttons below that instead need to stay on the system interface
![Screen Shot 2020-03-05 at 11 55 54](https://user-images.githubusercontent.com/4493366/75979027-fe933680-5edf-11ea-92a7-6b58ca163913.png)
- Put all but the above buttons in the standard interface pages (prefs or tools menu)
- Check that the button below is enabled only if the form has a valid ipout
![Screen Shot 2020-03-05 at 13 10 04](https://user-images.githubusercontent.com/4493366/75980391-a7db2c00-5ee2-11ea-9b73-af6bc568b9f5.png)

**Comment by gabryon99** [comment]
FIxed in the last commit:
https://github.com/ntop/ntopng/commit/0edd8a089a78296a6c34ae26708e3038d564190b

Now the host form is validated by `areYouSure()`. The `Delete Inactive Interfaces Data` and `Delete System INterface Data` were moved inside the sidebar on system view.
