### ISSUE TITLE
ntopng crashes frequently

### ISSUE THREAD

**Issue by bipin-stcs** [ntop/ntopng#3486]
Dear All,
We are facing frequent crashing of ntopng service. Please see the below. Because of this, there is no data visible in the GUI.

 systemctl status ntopng

> ● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
>    Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
>    Active: activating (auto-restart) (Result: signal) since Mon 2020-03-02 16:26:29 +03; 4s ago
>   Process: 15979 ExecStopPost=/bin/rm -rf /run/ntopng.conf (code=exited, status=0/SUCCESS)
>   Process: 15726 ExecStart=/usr/local/bin/ntopng /run/ntopng.conf (code=killed, signal=SEGV)
>   Process: 15720 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|^[ ]*--pid.*/s/^/#/" /etc/ntopng/ntopng.conf > /run/ntopng.conf (code=exited, status=0/SUCCESS)
>   Process: 15702 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exited, status=0/SUCCESS)
>  Main PID: 15726 (code=killed, signal=SEGV)
> 
> Mar 02 16:26:29 ntop01 systemd[1]: ntopng.service: Unit entered failed state.
> Mar 02 16:26:29 ntop01 systemd[1]: ntopng.service: Failed with result 'signal'.

Also, found the below in ntop-systemd.log

> Wed Feb 26 14:30:26 +03 2020 cluster StartPre
> Wed Feb 26 14:30:26 +03 2020 cluster StartPost
> Wed Feb 26 14:30:26 +03 2020 nprobe StartPre
> Wed Feb 26 14:30:26 +03 2020 cento StartPre
> Wed Feb 26 14:30:26 +03 2020 nprobe StartPost
> Wed Feb 26 14:30:26 +03 2020 cento StartPost
> Wed Feb 26 14:35:28 +03 2020 cento StopPost
> Wed Feb 26 14:54:03 +03 2020 cento StartPre
> Wed Feb 26 14:54:03 +03 2020 cento StartPost
> Wed Feb 26 14:59:04 +03 2020 cento StopPost
> Mon Mar  2 10:23:18 +03 2020 cento StartPre
> Mon Mar  2 10:23:18 +03 2020 cento StartPost
> Mon Mar  2 10:28:19 +03 2020 cento StopPost

This is the environment

> v.3.9.200226	[Enterprise/Professional build]
> GIT rev:	dev:da805487d3017a2eb7435408a5c5124837dc662c:20200226
> Pro rev:	r2723
> Built on:	Ubuntu 16.04.6 LTS
> System Id:	****************
> Platform:	x86_64
> Edition:	Enterprise
> License Type:	Permanent
> Maintenance:	Until Tue Feb  9 18:57:05 2021 

lsb_release -a

> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04.4 LTS
> Release:	16.04
> Codename:	xenial
>

**Comment by emanuele-f** [comment]
Can you get a stack trace as described here? https://github.com/ntop/ntopng/blob/dev/doc/README.crash

**Comment by bipin-stcs** [comment]
gdb --args ntopng /etc/ntopng/ntopng.conf
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ntopng...done.
(gdb) handle SIG33 nostop noprint pass
Signal        Stop	Print	Pass to program	Description
SIG33         No	No	Yes		Real-time event 33
(gdb) handle SIGPIPE nostop noprint pass
Signal        Stop	Print	Pass to program	Description
SIGPIPE       No	No	Yes		Broken pipe
(gdb) run
Starting program: /usr/local/bin/ntopng /etc/ntopng/ntopng.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
02/Mar/2020 17:00:40 [Prefs.cpp:933] ERROR: -S deprecated, sticky hosts no longer supported. Configure remote and local hosts idle timeouts from the preferences.
02/Mar/2020 17:00:40 [Prefs.cpp:1228] Using ElasticSearch for data dump [ntopng][ntopng-%Y.%m.%d][http://my-ip-address:9200/_bulk]
02/Mar/2020 17:00:40 [Ntop.cpp:2192] Setting local networks to x-num-flows=1000000
02/Mar/2020 17:00:40 [Utils.cpp:2913] ERROR: Error parsing IPv4 x-num-flows=1000000
02/Mar/2020 17:00:40 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
02/Mar/2020 17:00:40 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
02/Mar/2020 17:00:40 [NtopPro.cpp:312] [LICENSE] Reading license from /etc/ntopng.license
02/Mar/2020 17:00:40 [NtopPro.cpp:389] [LICENSE] /etc/ntopng.license: found valid Enterprise license
02/Mar/2020 17:00:40 [Ntop.cpp:2132] Parent process is exiting (this is normal)
[Inferior 1 (process 32554) exited normally]
(gdb) bt
No stack.
(gdb)

**Comment by emanuele-f** [comment]
Please remove the `--daemon`/`-e` option from the ntopng configuration file and try again. Be sure to update ntopng to the latest version since we've just fixed some crashes.

**Comment by bipin-stcs** [comment]
I updated the server (`v.3.9.200304	`)
I disabled `-e` option, restarted the server.

But when browsing `https://<ipaddress>` , i get the `500` error. And found the below in error.log of `apache2`
```
Undefined subroutine &main::getOSRelease called at ../utils/util.pl line 55.
Compilation failed in require at ../utils/types_params.pl line 11.
Compilation failed in require at ../utils/request_params.pl line 11.
Compilation failed in require at /var/ntop/ntop-bin/selectView.cgi line 14.
Undefined subroutine &main::getOSRelease called at ../utils/util.pl line 55.
```
After updated to latest, `ntopng` didnt crash yet. Here is the systemd.log
```
Wed Mar  4 10:16:02 +03 2020 nprobe StartPre
Wed Mar  4 10:16:02 +03 2020 nprobe StartPost
Wed Mar  4 10:23:24 +03 2020 nprobe StopPost
Wed Mar  4 10:23:24 +03 2020 cluster StopPost
Wed Mar  4 10:23:24 +03 2020 pf_ringctl stop
Wed Mar  4 10:23:25 +03 2020 pf_ringctl done
Wed Mar  4 10:23:25 +03 2020 pf_ring StopPost
Wed Mar  4 10:23:34 +03 2020 pf_ring StartPre
Wed Mar  4 10:23:34 +03 2020 pf_ringctl start
Wed Mar  4 10:23:37 +03 2020 pf_ringctl done
Wed Mar  4 10:23:37 +03 2020 pf_ring StartPost
Wed Mar  4 10:23:37 +03 2020 cluster StartPre
Wed Mar  4 10:23:37 +03 2020 cluster StartPost
Wed Mar  4 10:23:37 +03 2020 cento StartPre
Wed Mar  4 10:23:37 +03 2020 cento StartPost
Wed Mar  4 10:28:39 +03 2020 cento StopPost

```

**Comment by emanuele-f** [comment]
Ok. Should it crash again please open a new issue with the stack trace and also report your ntopng configuration.
