### ISSUE TITLE
Header stretches and hides body

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3489]
When several badges are present, the header stretches and doesn't allow to reach the body navbars

![image](https://user-images.githubusercontent.com/3397663/75758386-4ecd9580-5d34-11ea-821a-d8e52129158a.png)

**Comment by gabryon99** [comment]
Now when the elements are too many the container is wrapped. See this commit: https://github.com/ntop/ntopng/commit/8865cacb98f035369ecf25236f64ca8c275090d2

**Comment by simonemainardi** [comment]
better but still not looking nicely

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/3397663/75863157-5490ad00-5e00-11ea-871b-1f2792d68f60.png">

Mbit/s should't wrap

**Comment by gabryon99** [comment]
<img width="934" alt="Screenshot 2020-03-05 at 10 00 46" src="https://user-images.githubusercontent.com/14114916/75964853-342c2580-5ec8-11ea-8835-2d579be07f14.png">

Ok, I fixed the wrapping. Please be sure to reload the cache.

https://github.com/ntop/ntopng/commit/50277232c8d372b7861c2913e8850b5b4ac23bc7
