### ISSUE TITLE
Add Nprobe GeoPoint Export to ElasticSearch

### ISSUE THREAD

**Issue by Stalker71** [ntop/ntopng#349]
Hi,

Ntop is able to send location in the right format to use in the map in Kibana but not Nprobe.
Nprobe exports only the result : city and country for public IP.
Being able to see the cities, countries is great but being able to display a dynamic Map on a dashboard is a really nice feature.

Thanks!

**Comment by simonemainardi** [comment]
@Stalker71 this is the ntopng issue tracker, please move your issue to https://github.com/ntop/nProbe/issues
