### ISSUE TITLE
Unknown traffic while capturing netflow data

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3493]
E.g. flows with HTTPS port are instead shown as unknown

**Comment by simonemainardi** [comment]
need to see nprobe conf, waiting for the user to repond

**Comment by simonemainardi** [comment]
issue was due to nProbe not configured with template `-T @NTOPNG@`. nProbe has been changed to use default template `@NTOPNG@` when the following two conditions hold:

- used in combination with ntopng (option `--zmq`) 
- no template has been specified (no option `-T`)
