### ISSUE TITLE
Nindex - history flow not showing

### ISSUE THREAD

**Issue by hugleo** [ntop/ntopng#3497]
Enabled nindex in ntopng.conf

-i="tcp://127.0.0.1:5556"
-F="nindex"

But can't see history flow in the charts. Am I missing something?

![flows-history](https://user-images.githubusercontent.com/4573505/75780692-a0791e80-5d3a-11ea-8102-abc48084bc83.png)

**Comment by emanuele-f** [comment]
Can you post a full screenshot of the page? The flows dropdown menu (https://www.ntop.org/guides/ntopng/historical_flows.html#browsing-flows) should be shown below the chart above.

**Comment by hugleo** [comment]
full screen image. Not seeing flows in both dropdown menus.

![flows-history](https://user-images.githubusercontent.com/4573505/75790742-631c8d00-5d4a-11ea-8239-2a556c910a0c.png)

**Comment by hugleo** [comment]
@emanuele-f the reason: nindex is not being enabled alt all.
ntopng[922]: [Prefs.cpp:1304] WARNING: Discarding -F nindex: value out of range

**Comment by cardigliano** [comment]
@hugleo please provide the ntopng version (output of ntopng -V) and your OS version.

**Comment by hugleo** [comment]
ntopng -V
v.3.9.200304    [Enterprise/Professional build]

cat /etc/debian_version 
10.3

**Comment by cardigliano** [comment]
@hugleo the latest build for Debian 10 didn't include nIndex support, a new package will be available in ~1h. Please update later today and this will work.
