### ISSUE TITLE
Trigger alerts when host MUD changes

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3499]
After an host MUD has been recorded as specified in #3481, it can be used as a baseline for the host behaviour. If a new protocol is detected, this should be notified to the user via an alert. Ideally, the user should also be able to mark it as an allowed protocol, adding it to the host MUD.

**Comment by lucaderi** [comment]
Closed by https://github.com/ntop/ntopng/commit/31a33b1b11e0a98c416290ca0f37c49d70e05cb3
