### ISSUE TITLE
Add Nprobe AS owner Export to ElasticSearch

### ISSUE THREAD

**Issue by Stalker71** [ntop/ntopng#350]
Hi,

Ntop is able to display AS owner but it seems Nprobe is not able to do the same thing and export it to ElascticSearch.
Is it possible to add this nice feature?

Thanks!

**Comment by lucaderi** [comment]
SRC_AS and DST_AS are written by nProbe if your template sets them. Please share your nprobe configuration

**Comment by Stalker71** [comment]
Hi Luca,

Sorry, the AS number is well showed but not the real name of the number like it can be export by NtopNG.

Here is my configuration:
-n=none
-i=eth0
-s=128
-A=/usr/local/nprobe/GeoIPASNum.dat
-t=60
-d=60
-a=0
-e=1
-B=10
-w=128000
-z=0
-S=1:1
-E=0:0
-g=/var/run/nprobe-eth0.pid
--vlanid-as-iface-idx=none
-T=%IN_BYTES %IN_PKTS %PROTOCOL %PROTOCOL_MAP %SRC_TOS %L4_SRC_PORT %L4_SRC_PORT_MAP %IPV4_SRC_ADDR %IPV4_SRC_MASK %L4_DST_PORT %L4_DST_PORT_MAP %L4_SRV_PORT %L4_SRV_PORT_MAP %IPV4_DST_ADDR %IPV4_DST_MASK %OUTPUT_SNMP %IPV4_NEXT_HOP %SRC_AS %DST_AS %LAST_SWITCHED %FIRST_SWITCHED %OUT_BYTES %OUT_PKTS %DST_TOS %IN_SRC_MAC %SRC_VLAN %DST_VLAN %OUT_DST_MAC %APPLICATION_NAME %CLIENT_NW_LATENCY_MS %SERVER_NW_LATENCY_MS %APPL_LATENCY_MS %SRC_IP_COUNTRY %SRC_IP_CITY %DST_IP_COUNTRY %DST_IP_CITY %RETRANSMITTED_IN_BYTES %RETRANSMITTED_IN_PKTS %RETRANSMITTED_OUT_BYTES %RETRANSMITTED_OUT_PKTS %OOORDER_IN_PKTS %OOORDER_OUT_PKTS %L7_PROTO %L7_PROTO_NAME %SRC_AS_PATH_1 %DST_AS_PATH_1
-V=9
--elastic=flows;nprobe-%Y.%m.%d;http://192.168.0.55:9200/_bulk;;:
--dump-stats=/var/log/nprobe/eth0-0_flows_stats.txt

In the log, I can see the GeoIP loaded:
22/Jan/2016 15:22:58    GeoIP: loaded AS config file /usr/local/nprobe/GeoIPASNum.dat

22/Jan/2016 15:22:58    WARNING: Geo-location requires --city-list to be specified: ignored SRC_IP_COUNTRY
Is this normal as the file is well loaded just after ?

22/Jan/2016 15:22:58    GeoIP: loaded cities config file /usr/local/nprobe/GeoLiteCity.dat

Thank you

**Comment by lucaderi** [comment]
What you ask will fill up DB space unnecessarily. You can create a table with mapping AS name/number and use SQL to map names to numbers
