### ISSUE TITLE
ntopng rpm should have redhat-lsb-core listed as a package dependency for CentOS 7 & RedHat 7

### ISSUE THREAD

**Issue by scotty02** [ntop/ntopng#3501]
/usr/bin/lsb_release is used in /usr/bin/ntopng-utils-manage-updates and is in package redhat-lsb-core, but it is not listed as a dependency of the ntopng rpm. Please add redhat-lsb-core as dependency to the ntopng rpm for CentOS 7 and RedHat 7.

**Comment by simonemainardi** [comment]
Thanks for pointing this out. A new build is going to be generated overnight.
