### ISSUE TITLE
Some Flaws in the Internal Pages for Timeseries.lua

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3503]
![Screenshot from 2020-03-04 12-38-32](https://user-images.githubusercontent.com/4493366/75876035-35504a80-5e15-11ea-8e79-a47936d062df.png)

1. the frequency of the plugin is 1 sec but it is reported as 5
2. Next start is wrong, remove it if too complicated, and add the number of runs

**Comment by simonemainardi** [comment]
Fixed.

Frequency now reports the correct value.

The new table no longer has the next start column (which is not predictable as depending on the max duration). The next start column has been replaced with the max duration column which tells how long an activity is allowed to run (explained in the notes).

![image](https://user-images.githubusercontent.com/3397663/75892045-fd570080-5e30-11ea-8b73-813d8fb24b86.png)
