### ISSUE TITLE
SNMP interface chart versus total device traffic

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3505]
It would be useful to graph the total device traffic vs the specific interface traffic for an easy comparison.

**Comment by lucaderi** [comment]
Why that? What is problem it solves?

**Comment by simonemainardi** [comment]
Device total traffic depends on the total number of ports. I would expect the total traffic of a 48-ports switch to have a total traffic which is higher than a 24-ports switch, and so on. Hence, nothing really meaningful can be said by comparing the switch total traffic against one single port.

Anyway, you can still have an overview of the switch total just by looking at the stacked chart of SNMP interfaces. This gives an immediate overview of the total volume of traffic, and on the top interfaces for that device. We believe this suffices

![image](https://user-images.githubusercontent.com/3397663/76976150-dd950180-6933-11ea-9cc2-88a2ba1c6d3a.png)
