### ISSUE TITLE
Maximum estimated throughput and application latency missing for ZMQ interfaces

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3508]
- The maximum estimated throughput requires the TCP window which is not sent in template @NTOPNG@.

- Application latency is not parsed and also have issues as https://github.com/ntop/nProbe/issues/403 https://github.com/ntop/nProbe/issues/404

**Comment by sciolto** [comment]
Hi, we would like to have all possible fields parsed by nprobe included in the ZMQ stream, or at least make it configurable. 

All fields concerning the Application Latency and TCP Packet Analysis are very relevant. 

Thanks
