### ISSUE TITLE
Create package skeleton for user plugins installation

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3509]
The skeleton should make it easy for a user to create its own package. Having a deb package will ease the plugin installation on multiple machines (supposing that the user has its own repository for installation).

**Comment by lucaderi** [comment]
The code to package is https://github.com/ntop/ntopng/tree/dev/scripts/plugins/example

**Comment by simonemainardi** [comment]
Example package added in https://github.com/ntop/ntopng/commit/9d12faf6df6644abe0de8d9d0f931b334a9dbdec. Documentation added in https://github.com/ntop/ntopng/commit/f33f97f414f26d53eb13f0db775f8a3dd8324017.
