### ISSUE TITLE
Host protocols not available

### ISSUE THREAD

**Issue by whoknowz** [ntop/ntopng#351]
Had issue with both Protocols and Flows not showing up for individual hosts, probably bug #311.
After changing to nightly builds the flows are visible now, however Protocols still says "Unable to find data expired?" for even active connections.

NTOPNG is bridged between two trunk interfaces with multiple VLANs.

![capture](https://cloud.githubusercontent.com/assets/7417874/12223699/e2391904-b7ff-11e5-9a08-079d1306b6bc.JPG)

**Comment by simonemainardi** [comment]
I added the support for VLANs to the script that generates the application protocol table. This should fix your issue. Please, let me know.

**Comment by whoknowz** [comment]
@simonemainardi thank you, that fixed it.
