### ISSUE TITLE
SNMP Topology Error

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#3510]
After the latest update this is the error
![Immagine](https://user-images.githubusercontent.com/47248892/75961370-2a9fbf00-5ec2-11ea-994e-95e3a6dc11cb.png)

05/Mar/2020 09:14:40 [LuaEngine.cpp:12645] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/snmp_device_details.lua][/usr/share/ntopng/pro/scripts/lua/modules/snmp_utils.lua:290: attempt to index a nil value (field 'delta')]
05/Mar/2020 09:13:43 [SyslogCollectorInterface.cpp:153] Incoming connection from 127.0.0.1:49802
05/Mar/2020 09:13:27 [ZMQCollectorInterface.cpp:255] Collecting flows on tcp://*:1234c

**Comment by gabryon99** [comment]
Hi, can I ask you for the backtrace of your actions to get this error?

**Comment by zimbawe998** [comment]
HI,
I choose System -> SNMP -> Topology anf the error will appear.

05/Mar/2020 10:18:05 [LuaEngine.cpp:12645] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/snmpdevices_stats.lua][/usr/share/ntopng/pro/scripts/lua/modules/snmp_utils.lua:290: attempt to index a nil value (field 'delta')]
05/Mar/2020 09:31:52 [LuaEngine.cpp:12645] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/snmp_device_details.lua][/usr/share/ntopng/pro/scripts/lua/modules/snmp_utils.lua:290: attempt to index a nil value (field 'delta')]
05/Mar/2020 09:14:40 [LuaEngine.cpp:12645] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/snmp_device_details.lua][/usr/share/ntopng/pro/scripts/lua/modules/snmp_utils.lua:290: attempt to index a nil value (field 'delta')]

**Comment by gabryon99** [comment]
Ok, we have launched the build for the new package, can you retry in about 1 hour?

**Comment by lucaderi** [comment]
This works for me too. Please confirm @zimbawe998

**Comment by zimbawe998** [comment]
Now it works, after latest update.

**Comment by gabryon99** [comment]
Ok, I close the ticket.
