### ISSUE TITLE
Differentiate alerts based on impact

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3516]
![Screen Shot 2020-03-05 at 18 37 33](https://user-images.githubusercontent.com/4493366/76009174-11722f00-5f11-11ea-9ab9-563701a1e702.png)
ntopng is now reporting alerts based on severity and this is a good thing. However sometimes there are alerts that are super-important (in the above picture the network went down) and they need to be handled differently otherwise they will be lost with all other alerts.

**Comment by simonemainardi** [comment]
I would stick to standard severities that are a widely known concept and users are familiar with it.

If necessary, I would use severities higher than error and make them visible in the UI with extra badges or extra colors.

**Comment by lucaderi** [comment]
![Screen Shot 2021-06-07 at 14 03 40](https://user-images.githubusercontent.com/4493366/121013546-3cdd6c80-c799-11eb-9394-f9b3fe057d2a.png)
This is a proposal. On the bottom line, you see relevant events that in the case of ntopng could be alerts

**Comment by MatteoBiscosi** [comment]
This ticket was implemented in many ways lately, by adding new severities, by adding the score and other metrics and this should be enought. Now we just need to reorganize the alerts and group them #6877
