### ISSUE TITLE
Traffic Dashboard doesn't show data

### ISSUE THREAD

**Issue by kalibox** [ntop/ntopng#3520]
Hi, I have the Professional version installed on my Pi and was happily running and reporting traffic data until I upgraded it to ntopng Professional Edition v.3.9.200225 tonight. Now, I don't see Traffic Dashboard populating with traffic information and in addition to this I keep seeing the following error:

Periodic activity 'stats_update.lua' is queued but has not been executed. No thread available for execution. [Pending since 22:13:35] 

I have restarted the system a couple of times but each reboot produces the same error.

Please can this be looked into.

Thanks in advance.

**Comment by emanuele-f** [comment]
Please retry with the latest raspberry package. If you still experience the problem, please click on the yellow warning sign in the ntopng header and post a screenshot of the page that opens.

**Comment by kalibox** [comment]
Hi Emanuele, thanks. I have downloaded the latest version available for the Pi and it does seem to have fixed it. Some graphs are still not being reported correctly. I'll try and attach a pic later to hopefully explain this better. 

Thanks.

**Comment by emanuele-f** [comment]
Ok, closing for now. If you still experience issues please open a new bug with the details.

**Comment by kalibox** [comment]
Thanks. The new version (released 13/03) is good as gold. Cheers for closing the ticket.
