### ISSUE TITLE
too many packages discarded or dropped % 50 percentage

### ISSUE THREAD

**Issue by tezcangulnaz** [ntop/ntopng#353]
![image](https://cloud.githubusercontent.com/assets/16521020/12236772/4f2c3f44-b884-11e5-802e-4b48bc413d46.png)

after updating ntopng, too many packets are dropped and dashboard working too slow

**Comment by lucaderi** [comment]
@tezcangulnaz Any news?

**Comment by lucaderi** [comment]
Closed for inactivity
