### ISSUE TITLE
5min Stuck with SNMP

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3532]
This is the behavior reported by a user who has SNMP enabled:

![image](https://user-images.githubusercontent.com/3397663/76302165-cd3faf80-62bf-11ea-95d6-59377ed7141e.png)

**Comment by emanuele-f** [comment]
Some problems are now fixed:
- Deadline was computed by the script rather than using the one provided by the C
- Deadline checks were missing in multiple walks

**Comment by simonemainardi** [comment]
Spending a lot of time in:

![image](https://user-images.githubusercontent.com/3397663/76742726-d9b98180-6771-11ea-8edd-59c882ba7247.png)

**Comment by simonemainardi** [comment]
seems the SNMP get is  fed with invalid data (look at the oids)

![image](https://user-images.githubusercontent.com/3397663/76743639-3bc6b680-6773-11ea-97ec-833f4380d4ec.png)

**Comment by simonemainardi** [comment]
stepping again after a few minutes, oids look the same although the script didn't return. Chances are there's a loop

![image](https://user-images.githubusercontent.com/3397663/76744074-fce53080-6773-11ea-9498-82c2d3315541.png)

**Comment by simonemainardi** [comment]
loop occurs when getting lldp ports, oid "1.0.8802.1.1.2.1.4.1.1.7"

**Comment by simonemainardi** [comment]
Issue is when getting responses with oids > 2^32-1:

Indeed, actual response `iso.0.8802.1.1.2.1.4.1.1.7.2505939219.115.1` is read by ntopng as `iso.0.8802.1.1.2.1.4.1.1.7.-1789028077.115.1`.

**Comment by simonemainardi** [comment]
clearly, `-1789028077` is the `int32_t` conversion of `u_int64_t` value `2505939219`.
