### ISSUE TITLE
Manage Data - Autocompletion Dropdown Remains Open

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3536]
When typing the IP address of an host, the dropdown opens but then remains open. Clicking on a dropdown entry doesn't have any effect

![image](https://user-images.githubusercontent.com/3397663/76319174-1bb07680-62df-11ea-9fc6-d102e3273844.png)

**Comment by gabryon99** [comment]
Problem fixed, the error was caused by a wrong API call to bootstrap validator. See in this commit: https://github.com/ntop/ntopng/commit/4c692e2c6e4250984992a2fd63153f459e673933
