### ISSUE TITLE
Manage Data - Delete Interface Data Redirects to a Broken Page

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3538]
After clicking on 'Delete Interface Data', the resulting page is broken

![image](https://user-images.githubusercontent.com/3397663/76319524-a2fdea00-62df-11ea-8fa9-7c9e8ee0befc.png)

![image](https://user-images.githubusercontent.com/3397663/76319492-95486480-62df-11ea-85bc-d99b7b031d29.png)

**Comment by gabryon99** [comment]
Ok, I fixed the problem. The bug was caused to a wrong js call inside the page, see: https://github.com/ntop/ntopng/commit/4c692e2c6e4250984992a2fd63153f459e673933
