### ISSUE TITLE
Manage Data - Delete System Interface Data

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3539]
Clicking on the 'Delete System Interface Data' under the system interface actually causes the deletion of data for another non-system interface...

![image](https://user-images.githubusercontent.com/3397663/76319686-db9dc380-62df-11ea-838b-c34a345fe968.png)

**Comment by gabryon99** [comment]
Issue fixed, see the commit: https://github.com/ntop/ntopng/commit/4c692e2c6e4250984992a2fd63153f459e673933

**Comment by lucaderi** [comment]
![Screen Shot 2020-03-11 at 16 55 25](https://user-images.githubusercontent.com/4493366/76437699-3c99ca00-63ba-11ea-9539-7dc2adeac523.png)
@gabryon99 It looks that there are aesthetic issues
