### ISSUE TITLE
Ntopng compilation error on debian 8.2 x86

### ISSUE THREAD

**Issue by shadrack222** [ntop/ntopng#354]
Hello,

After nDPI compilation without problems i got the following error while compiling ntopng (date : Wed Jan 6 16:34:53 2016 +0100 )

...

In file included from /usr/local/include/libndpi-1.7.1/libndpi/ndpi_main.h:33:0,
from /opt/ntopng/include/ntop_includes.h:99,
from src/NetworkInterface.cpp:22:
/usr/local/include/libndpi-1.7.1/libndpi/ndpi_api.h:77:40: note: initializing argument 2 of ‘ndpi_detection_module_struct\* ndpi_init_detection_module(u_int32_t, void\* ()(size_t), void ()(void), ndpi_debug_function_ptr)’
struct ndpi_detection_module_struct _ndpi_init_detection_module(u_int32_t ticks_per_second,
^
src/NetworkInterface.cpp: In member function ‘int NetworkInterface::getFlows(lua_State, patricia_tree_t, Host, bool, char, u_int32_t, u_int32_t, bool)’:
src/NetworkInterface.cpp:1951:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for(int i=toSkip, num=0; i ^
src/NetworkInterface.cpp:1953:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if(++num >= maxHits) break;
^
src/NetworkInterface.cpp:1958:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if(++num >= maxHits) break;
^
src/NetworkInterface.cpp: In member function ‘int NetworkInterface::getActiveHostsList(lua_State, patricia_tree_t, bool, bool, char, u_int32_t, u_int32_t, bool)’:
src/NetworkInterface.cpp:2013:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for(int i=toSkip, num=0; i ^
src/NetworkInterface.cpp:2016:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if(++num >= maxHits) break;
^
src/NetworkInterface.cpp:2022:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if(++num >= maxHits) break;
^
Makefile:129: recipe for target 'src/NetworkInterface.o' failed
make: *_\* [src/NetworkInterface.o] Error 1

Any ideas to help me , thanks in advance.

**Comment by gvanem** [comment]
I got the same error on Windows/MSVC. Apply this patch in `NetworkInterface.cpp`:

```
--- a/NetworkInterface.cpp 2016-01-14 00:01:10
+++ b/NetworkInterface.cpp                 2016-01-14 02:38:04
@@ -36,7 +36,7 @@

 /* **************************************** */

-static void *malloc_wrapper(unsigned long size)
+static void *malloc_wrapper(size_t size)
```

**Comment by lucaderi** [comment]
Thank you. Fixed
