### ISSUE TITLE
ZMQ Encryption breaks ntopng hierarchy

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3541]
The introduction of ZMQ encryption has broken hierarchies of ntopng as depicted in https://www.ntop.org/ntopng/creating-a-hierarchical-cluster-of-ntopng-instances/

This needs to addressed

**Comment by cardigliano** [comment]
ZMQ encryption is now supported in data export (https://github.com/ntop/ntopng/commit/5cbe4546f259ab9cead033b179851c0e089a168b)
