### ISSUE TITLE
Add aditional filter fields to ASN flows view

### ISSUE THREAD

**Issue by hugleo** [ntop/ntopng#3542]
For ASN flows view we have only Applications field to inspect the flows.

Look at the possibility to add more fields to match the normal flows view. (Ip Version by example would be nice)

normal flows view
lua/flows_stats.lua

![normal-flows](https://user-images.githubusercontent.com/4573505/76425659-b2853d80-6388-11ea-901b-8fc3a385f899.png)

asn flows view
lua/as_details.lua?asn=12345&page=flows

![asnflows](https://user-images.githubusercontent.com/4573505/76425675-ba44e200-6388-11ea-9957-5de16474a923.png)

**Comment by MatteoBiscosi** [comment]
Currently added Ip version and Hosts type (remote, local, ...)
