### ISSUE TITLE
Network Discovery - ARP Scan arbitrary networks

### ISSUE THREAD

**Issue by frhey** [ntop/ntopng#3544]
Hello.

How could I integrate additional networks?

With one network card and one IP, I only see this one network at a time.
Although other networks are accessible (ping in the console is ok).
One network card with two IPs from two different networks does not work. 

If I add a second network card with an IP from a second network, I will 
get data from that second network, too.
But I always have to switch between the two network cards in the GUI to 
get f.e. the "warnings". With 20 networks this is very tedious. 
And I cannot add 20 network cards. One for each network.

I need all 20 active networks in one overview, i.e. under "warnings" the infos 
of all 20 networks.

In #1946 is the talk of 8000 hosts and 17 networks. I would like that too :-)
But where / how do I have to set "-X and -x" or "--max-num-hosts "50000"" ?
In ntopng.conf?

I would be very grateful for help :-)

P.S.
A license purchase would follow (for the advanced options), if I could 
ensure in my current test that I can see all 20 networks...

ntopng Community Edition 3.8.200207
centos-release-7-7.1908.0.el7.centos.x86_64

/etc/sysconfig/network-scripts/ifcfg-ens192

	BOOTPROTO=none
	BROWSER_ONLY=no
	DEFROUTE=yes
	DEVICE=ens192
	DNS1=192.168.1.225
	DNS2=192.168.1.232
	DOMAIN=domainname.lokal
	GATEWAY=192.168.1.254
	IPADDR=192.168.1.50
	IPV4_FAILURE_FATAL=no
	IPV6_ADDR_GEN_MODE=stable-privacy
	IPV6_AUTOCONF=yes
	IPV6_DEFROUTE=yes
	IPV6_FAILURE_FATAL=no
	IPV6_PRIVACY=no
	IPV6INIT=no
	NAME=ens192
	ONBOOT=yes
	PREFIX=24
	PROXY_METHOD=none
	TYPE=Ethernet
	UUID=1c63cf93-5bfb-4442-a2cb-62936b6e6aa0

/etc/rc.d/rc.local

	touch /var/lock/subsys/local
	ip link set ens192 promisc on

/etc/ntopng/ntopng.conf

	-G=/var/run/ntopng.pid
	--community
	-i=ens192
	-w=3000
	-m="192.168.0.0/24,172.16.0.0./24,10.0.0.0/24"
	-n=1
	-d=/var/lib/ntopng

/etc/nprobe/nprobe.conf

	-G=/var/run/nprobe.pid
	-i=ens192
	-n=none
	
systemctl status ntopng
		● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
		   Loaded: loaded (/usr/lib/systemd/system/ntopng.service; enabled; vendor preset: disabled)
		   Active: active (running) since Wed 2020-03-11 15:51:14 CET; 21min ago
		  Process: 1970 ExecStartPost=/bin/sh -c /bin/echo "$(/bin/date) ntopng StartPost" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
		  Process: 1959 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|^[ ]*--pid.*/s/^/#/" /etc/ntopng/ntopng.conf > /run/ntopng.conf (code=exited, status=0/SUCCESS)
		  Process: 1912 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exited, status=0/SUCCESS)
		  Process: 1900 ExecStartPre=/bin/sh -c /bin/echo "$(/bin/date) ntopng StartPre" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
		 Main PID: 1969 (ntopng)
		   CGroup: /system.slice/ntopng.service
				   └─1969 /usr/local/bin/ntopng /run/ntopng.conf

		Mar 11 15:51:17 sv-hb-5 ntopng[1969]: 11/Mar/2020 15:51:17 [Ntop.cpp:403] Welcome to ntopng x86_64 v.3.8.200207 - (C) 1998-18 ntop.org
		Mar 11 15:51:17 sv-hb-5 ntopng[1969]: 11/Mar/2020 15:51:17 [Ntop.cpp:717] Adding 192.168.1.50/32 as IPv4 interface address for ens192
		Mar 11 15:51:17 sv-hb-5 ntopng[1969]: 11/Mar/2020 15:51:17 [Ntop.cpp:725] Adding 192.168.1.0/24 as IPv4 local network for ens192
		Mar 11 15:51:17 sv-hb-5 ntopng[1969]: 11/Mar/2020 15:51:17 [Ntop.cpp:744] Adding fe80::250:56ff:fe80:6dfd/128 as IPv6 interface address for ens192
		Mar 11 15:51:17 sv-hb-5 ntopng[1969]: 11/Mar/2020 15:51:17 [Ntop.cpp:753] Adding fe80::250:56ff:fe80:6dfd/64 as IPv6 local network for ens192
		Mar 11 15:51:17 sv-hb-5 ntopng[1969]: 11/Mar/2020 15:51:17 [PeriodicActivities.cpp:72] Started periodic activities loop...
		Mar 11 15:51:17 sv-hb-5 sudo[2446]:   ntopng : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/ntopctl n2n has-service n2n_assistance
		Mar 11 15:51:17 sv-hb-5 sudo[2454]:   ntopng : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/ntopctl n2disk has-service dummy
		Mar 11 15:51:17 sv-hb-5 ntopng[1969]: 11/Mar/2020 15:51:17 [PeriodicActivities.cpp:113] Each periodic activity script will use 2 threads
		Mar 11 15:51:17 sv-hb-5 ntopng[1969]: 11/Mar/2020 15:51:17 [NetworkInterface.cpp:2597] Started packet polling on interface ens192 [id: 1]...

/var/lib/ntopng/ntopng.log

	11/Mar/2020 15:50:22 [main.cpp:73] Shutting down...
	11/Mar/2020 15:50:22 [Ntop.cpp:2093] Terminating periodic activities
	11/Mar/2020 15:50:24 [Ntop.cpp:2099] Executing shutdown script
	11/Mar/2020 15:50:24 [Ntop.cpp:2108] Terminating network interfaces
	11/Mar/2020 15:50:24 [Ntop.cpp:2113] Waiting for the application to shutdown
	11/Mar/2020 15:50:24 [PcapInterface.cpp:253] Terminated packet polling for ens192
	11/Mar/2020 15:50:26 [ProtoStats.cpp:35] [IPv4]  7.07 MB/32.19 K Packets
	11/Mar/2020 15:50:26 [ProtoStats.cpp:35] [IPv6]  0 B/0.00 Packets
	11/Mar/2020 15:50:26 [ProtoStats.cpp:35] [ARP]   779.66 KB/13.31 K Packets
	11/Mar/2020 15:50:26 [ProtoStats.cpp:35] [MPLS]  0 B/0.00 Packets
	11/Mar/2020 15:50:26 [ProtoStats.cpp:35] [Other] 1.82 KB/31.00 Packets
	11/Mar/2020 15:50:26 [Ntop.cpp:2081] Interface ens192 [running: 0]
	11/Mar/2020 15:50:26 [Ntop.cpp:2123] Deleted PID /var/run/ntopng.pid: [rc: -1][Permission denied]
	11/Mar/2020 15:50:26 [HTTPserver.cpp:1225] HTTP server terminated
	11/Mar/2020 15:50:26 [NetworkInterface.cpp:599] Flushing host contacts for interface ens192
	11/Mar/2020 15:50:26 [NetworkInterface.cpp:2626] Cleanup interface ens192
	11/Mar/2020 15:50:26 [AddressResolution.cpp:61] Address resolution stats [0 resolved][1 failures]
	11/Mar/2020 15:51:17 [main.cpp:396] Logging onto /var/lib/ntopng/ntopng.log
	11/Mar/2020 15:51:17 [main.cpp:399] Working directory: /var/lib/ntopng
	11/Mar/2020 15:51:17 [main.cpp:401] Scripts/HTML pages directory: /usr/share/ntopng
	11/Mar/2020 15:51:17 [Ntop.cpp:403] Welcome to ntopng x86_64 v.3.8.200207 - (C) 1998-18 ntop.org
	11/Mar/2020 15:51:17 [Ntop.cpp:717] Adding 192.168.1.50/32 as IPv4 interface address for ens192
	11/Mar/2020 15:51:17 [Ntop.cpp:725] Adding 192.168.1.0/24 as IPv4 local network for ens192
	11/Mar/2020 15:51:17 [Ntop.cpp:744] Adding fe80::250:56ff:fe80:6dfd/128 as IPv6 interface address for ens192
	11/Mar/2020 15:51:17 [Ntop.cpp:753] Adding fe80::250:56ff:fe80:6dfd/64 as IPv6 local network for ens192
	11/Mar/2020 15:51:17 [PeriodicActivities.cpp:72] Started periodic activities loop...
	11/Mar/2020 15:51:17 [PeriodicActivities.cpp:113] Each periodic activity script will use 2 threads
	11/Mar/2020 15:51:17 [NetworkInterface.cpp:2597] Started packet polling on interface ens192 [id: 1]...

**Comment by simonemainardi** [comment]
Not sure to understand the question.

Please, explain how your interface is connected to the network to monitor the traffic. If you're connected to a switch, then very likely you'll only obtain broadcast traffic and traffic directed to you.

Have a look at: https://www.ntop.org/nprobe/network-monitoring-101-a-beginners-guide-to-understanding-ntop-tools/

**Comment by frhey** [comment]
As far as I understand it, the posted link is about nprobe and Netflow. 
But first of all I'm interested in the basic functions of ntop. 
Especially the "warning" when a "Status Alert - New Devices Connection" occurs. 
Netflow I would test + configure later (and if I have a license for it).

First I just want to know if a new device has appeared in one of the 20 networks.

Currently my ntop has 1 network card and 1 IP. 
So I can check the local network for "new devices". 
This works fine :-)

If I use 2 network cards with 2 IPs (one IP from each of the 2 networks), 
I can scan both networks for "new devices". 
But that means with 20 networks I need 20 network cards in ntop and I have 
to select 20 interfaces in the GUI manually one after the other to see if 
1 new device was found somewhere.

The question is: how could I scan all 20 networks for "new devices" and have 
the warnings for them displayed in the GUI in 1 interface?

ntop runs on a CentOS 7 VM under VMware vSphere 6.5
In the same environment, on the same virtual switch, other monitoring tools
run that can easily monitor all 20 networks.
But they have other functions than ntop.

**Comment by simonemainardi** [comment]
OK now I see what you mean.

Currently, discovery starts from the arp scan, which is by default limited to the addresses in network of the interface https://github.com/ntop/ntopng/blob/a024e7d73fcf459375dd052d45be484be69e2701/src/NetworkDiscovery.cpp#L177

Marking this as a feature request.

**Comment by emanuele-f** [comment]
We will add the ability to scan multiple networks if the network interface is configured with multiple IP addresses. E.g. if eth0 has ip address 192.168.1.5/24 and 192.168.2.10/24, ntopng will scan both the 192.168.1.0/24 and the 192.168.2.10/24 networks. You can add multiple ip addresses to a network interface via `ip addr add dev eth0 192.168.2.10/24`
