### ISSUE TITLE
Severe flow dump drops

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3545]
When flows need to be dumped (e.g. in nIndex) that are processed by scripts/callbacks/interface/ht_state_update.lua than in case of heavy load (e.g. many hosts and flows) it has little time to handle flow dump. This results in severe drops.

This behaviour needs to be modified and decouple dump from flow processing.

**Comment by simonemainardi** [comment]
Dump must be moved out from the periodic hash table walk.

Proposed solution is to create a dedicated thread which runs when a dumper exists (e.g., MySQL, nIndex, etc).

The thread will perform two actions basically:

1. Walk 1/Nth of the hash table and dump flows active for more than 5 minutes
2. Dequeue `idle` flows from a queue, dump them and `delete` them.

Idle flows will be enqueued using a method of the hash table which would look something like:

```
diff --git a/include/FlowHash.h b/include/FlowHash.h
index 0683cf8..a586c6f 100644
--- a/include/FlowHash.h
+++ b/include/FlowHash.h
@@ -42,8 +42,13 @@ class FlowHash : public GenericHash {
    * @return Pointer of entry that matches with the key parameter, NULL if there isn't entry with the key parameter or if the hash is empty.
    */
   Flow* findByKeyAndHashId(u_int32_t key, u_int hash_id);
-
   virtual void walkAllStates(bool (*walker)(GenericHashEntry *h, void *user_data), void *user_data);
+  void dumpEntry(Flow *f, bool free_after_dump) {
+    if(/* enqueue if there's room in the queue */)
+      ;
+    else
+      delete f;
+  }
 };

 #endif /* _FLOW_HASH_H_ */
diff --git a/src/GenericHash.cpp b/src/GenericHash.cpp
index 62c21bc..3e2712d 100644
--- a/src/GenericHash.cpp
+++ b/src/GenericHash.cpp
@@ -138,7 +138,7 @@ void GenericHash::purgeQueuedIdleEntries(bool (*walker)(GenericHashEntry *h, voi
     if(!cur_idle->empty()) {
       for(vector<GenericHashEntry*>::const_iterator it = cur_idle->begin(); it != cur_idle->end(); ++it) {
        walker(*it, user_data);
-       delete *it;
+        dumpEntry(*it, true);
        entry_state_transition_counters.num_purged++;
       }
     }
```

**Comment by lucaderi** [comment]
https://github.com/ntop/ntopng/commit/18637f21e18edb8adaa55a4bf61d78693e796b44 implements this ticket
