### ISSUE TITLE
Active menu entry is not selected

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3546]
Normally active menu entries have a blue background which indicates that the entry is currently selected. Since the migration to bootstrap 4, this is broken as the all entries have a white background.  The `active` css class must be moved from the outer `<li>` element to the inner `<a>` element to fix this.

![2020-03-11_17-55](https://user-images.githubusercontent.com/5488003/76442643-25a6a800-63b9-11ea-934a-a8eaeb352822.png)

This happens at least in the following pages:
- Active flows
- Active hosts
- Active MAC addresses

Please `grep` all the code to fix all the broken pages.

**Comment by gabryon99** [comment]
Ok, I've applied the `active` class for `a` elements inside `li` elements

**Comment by emanuele-f** [comment]
Please close this when all the dropdowns are fixed (use a `grep` on the codebase to verify this)

**Comment by simonemainardi** [comment]
still missing from

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/3397663/76951007-4025d780-690b-11ea-967a-2f938ce7ea6d.png">


please do as suggested by @emanuele-f

**Comment by simonemainardi** [comment]
I've fixed this. @gabryon99 next time please make sure to complete the work, and especially don't blindly replace strings without any kind of testing.

Look at this for example https://github.com/ntop/ntopng/commit/e2dcd862b863a46f931702b3a2f9eaa26bdaf5e5#diff-057895b54ccbf560091774cd718d0f56R163

you've just blindly moved the class ending up in breaking the HTML. A brief test would have highlighted this.
