### ISSUE TITLE
License generation

### ISSUE THREAD

**Issue by Claireshan** [ntop/ntopng#3547]
Hello,
Am currently running the community version but i was given an order id for enterprise. 
when i try generating the license i get the attached error.
Do i use the details of my existing version to generate the license?
![nto](https://user-images.githubusercontent.com/22081659/76491111-02720c00-643e-11ea-94c0-4002e62463fd.PNG)

**Comment by cardigliano** [comment]
Could you provide me your order id? Please drop an email to cardigliano at ntop.org

**Comment by Claireshan** [comment]
It has finally worked. I had already generated the license and I had to change my conf file line from --community to --enterprse
