### ISSUE TITLE
upgrading to 3.9

### ISSUE THREAD

**Issue by Claireshan** [ntop/ntopng#3549]
Hello when i run apt-get upgrade it doesnt update to version.
how can i get to 3.9 from 3.8.

Also my interface doesnt show top local talkers it also doesnt shoow hosts on the network. is there something am supposed to configure.

Thank you

**Comment by simonemainardi** [comment]
on which OS are you?

**Comment by Claireshan** [comment]
linux 16.04

**Comment by Claireshan** [comment]
Please any solution for this

**Comment by emanuele-f** [comment]
Please run `apt-get update` then `apt-get upgrade`. If you still experience the issue, run `apt-cache policy ntopng` and post here the result.

**Comment by Claireshan** [comment]
> Please run `apt-get update` then `apt-get upgrade`. If you still experience the issue, run `apt-cache policy ntopng` and post here the result.

![3 9](https://user-images.githubusercontent.com/22081659/76929578-94be5800-68f5-11ea-8d23-5d860002af2a.PNG)

**Comment by emanuele-f** [comment]
You need to install the `apt-ntop.deb` as explained in http://packages.ntop.org/apt .

**Comment by Claireshan** [comment]
I was able to to upgrade but there are no flows.
i dnt know if there is a problem with my configuration
nprobe and ntop are on the same machine.
find  the attached
127.0.0.1 is the loopback
we use port 5556
![gen](https://user-images.githubusercontent.com/22081659/76966987-d66ff280-6937-11ea-8d9e-77dbe510974e.PNG)

**Comment by simonemainardi** [comment]
nprobe configuration is wrong. To connect nProbe to ntopng, you have to use `--zmq` option.

see: https://www.ntop.org/nprobe/network-monitoring-101-a-beginners-guide-to-understanding-ntop-tools/

For example:

```
ntopng -i tcp://127.0.0.1:5556 
nprobe -i lo -n none --zmq tcp://127.0.0.1:5556 --zmq-format=j -T "@NTOPNG@"
```

**Comment by Claireshan** [comment]
i have changed the config check attached. but still no flow 
i have also attached results for nprobe status
![co](https://user-images.githubusercontent.com/22081659/76976080-7fbce580-6944-11ea-9020-9832d3372e06.PNG)
![np](https://user-images.githubusercontent.com/22081659/76976084-8186a900-6944-11ea-9682-5e47212eb42e.PNG)

**Comment by simonemainardi** [comment]
read the ntopng error: "Unable to bind ZMQ endpoint". Please read the errors. Very likely you have another instance of ntopng running...

**Comment by Claireshan** [comment]
I got reed of the other instance and ntop and nprobe seem to be running well but still no flows. when i check the ports it seems like port 5556 is not attached to ip 127.0.0.1
![sta](https://user-images.githubusercontent.com/22081659/77037932-85a5db80-69c3-11ea-810d-65c87026969c.PNG)
![sta1](https://user-images.githubusercontent.com/22081659/77037938-876f9f00-69c3-11ea-9bb5-6bcf4f1a6d10.PNG)

**Comment by Claireshan** [comment]
this is my current config
![co1](https://user-images.githubusercontent.com/22081659/77038158-1381c680-69c4-11ea-88e9-8a6f7241c8b4.PNG)

**Comment by simonemainardi** [comment]
oh man if you don't read things we can do back and forth indefinitely.

you've added `--zmq-probe-mode` to nprobe with reference to the prev configuration? Why? Remove it but most importantly check the documentation.

**Comment by emanuele-f** [comment]
@Claireshan have you solved the issues? Can this be closed?

**Comment by Claireshan** [comment]
It wasn’t really solved

Sent from Mail for Windows 10
