### ISSUE TITLE
Incomplete Reports on Ubuntu 12.04.5 LTS

### ISSUE THREAD

**Issue by ParadigmElena** [ntop/ntopng#355]
The reports don't show anything below “Application Breakdown”, i.e. the report doesn’t show “Top Countries”, Top Local Hosts”, “Top Remote Hosts” and “Top ASN”. It's the same for any time period.

![reports](https://cloud.githubusercontent.com/assets/16676539/12282177/c0d9cd0e-b961-11e5-9532-151b80a7fb59.png)

**Comment by simonemainardi** [comment]
@ParadigmElena, i can see from the screenshot that you are using v.2.2.151211, please update to the latest nightly build. This bug has already been fixed.

Please, let us know if it works as expected.
