### ISSUE TITLE
Missing RTT alert actionable item

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3558]
RTT alerts are necessary to alert when something went wrong (e.g. service unavailable). In the current implementation there is no way to send an mail (or something else) when an alert is triggered. This needs to be implemented as otherwise RTT is mostly useless in the current implementation.

**Comment by simonemainardi** [comment]
Current implementation adds support for this. Every RTT-monitored host can be assigned to a pool which, in turn, can be configured with one or more notification recipients to send emails, slack notifications, etc.
