### ISSUE TITLE
System Notification and Offline Mode

### ISSUE THREAD

**Issue by gabryon99** [ntop/ntopng#3561]
For the next milestone, we thought to integrate a System Notification inside ntopng, in this way we can alert the user even when him it's not on the page or he has the browser closed. This system will be integrated thanks to the Service Worker, installable in any browser.
Thanks to SW we'll also able to show cached pages and assets if the user is upgrading ntopng or the server is unreachable. Like this example down below:
<img width="1351" alt="Screenshot 2020-03-14 at 10 12 00" src="https://user-images.githubusercontent.com/14114916/76678917-40a53200-65dc-11ea-89d5-76277d51ede5.png">

The System Notification will be enabled from the Settings if the user wants.

**Comment by lucaderi** [comment]
As recipients and endpoints have been introduced, this ticket is no longer interesting to implement
