### ISSUE TITLE
no flows after upgrade

### ISSUE THREAD

**Issue by Claireshan** [ntop/ntopng#3565]
I have updated and i nolonger get flows

![cap2](https://user-images.githubusercontent.com/22081659/76768611-4f424380-67ac-11ea-96dc-22b9f3001eb6.PNG)

**Comment by emanuele-f** [comment]
Please report the output of `ntopng --version`, along with your ntopng and nprobe configuration.

**Comment by Claireshan** [comment]
![nop](https://user-images.githubusercontent.com/22081659/76929331-ee725280-68f4-11ea-90d6-bf48cf9a2923.PNG)
![ntop conf](https://user-images.githubusercontent.com/22081659/76929335-f03c1600-68f4-11ea-91da-cc5d90973673.PNG)
![ntop1](https://user-images.githubusercontent.com/22081659/76929337-f0d4ac80-68f4-11ea-98ef-73687f91b173.PNG)

**Comment by Claireshan** [comment]
> Please report the output of `ntopng --version`, along with your ntopng and nprobe configuration.

![nop](https://user-images.githubusercontent.com/22081659/76929380-0e097b00-68f5-11ea-934c-f7541c4a1803.PNG)
![ntop conf](https://user-images.githubusercontent.com/22081659/76929381-0f3aa800-68f5-11ea-931e-3df083b2729e.PNG)
![ntop1](https://user-images.githubusercontent.com/22081659/76929382-0fd33e80-68f5-11ea-95d6-a13a12c7732a.PNG)

**Comment by simonemainardi** [comment]
please, update to version 3.9 or wait a couple of days as we are in the process of releasing the new ntopng 4.0 (current 3.8 will become 4.0)

**Comment by simonemainardi** [comment]
in the meanwhile you can try and add option `--zmq-format=j` to nProbe

**Comment by Claireshan** [comment]
okay thank you
