### ISSUE TITLE
"ERROR: Unable to locate docs dir"

### ISSUE THREAD

**Issue by gvanem** [ntop/ntopng#357]
I have no problem running Ntop from the install-bin directory using the built-in heuristics for finding it's paths. But using `--httpdocs-dir` with an absolute path, it aborts with message:
`ERROR: Unable to locate docs dir`.

I start Ntop via a `go.bat` file in the `f:\MingW32\src\inet\ntop-NG\orig-bin` (where `ntopng.exe` is) like so:

```
ntopng.exe /c --httpdocs-dir=f:\MingW32\src\inet\ntop-NG\orig-bin\httpdocs ^
             -i \Device\NPF_{12735646 79BF-4583-8A95-35F25DE96B7E} ^
             --verbose --redis 127.0.0.1:6379
```

I.e. _not_ as a service. And the output is:

```
Starting ntopg
Running ntopng.
14/Jan/2016 16:40:20 [Prefs.cpp:581] ntopng will use redis 127.0.0.1:6379@0
14/Jan/2016 16:40:20 [Prefs.cpp:796] Logging into c:\Users\Gisle\Documents\ntopng.log
14/Jan/2016 16:40:20 [Prefs.cpp:812] ERROR: Unable to locate docs dir

```

All the `httpdocs` files really are under `f:\MingW32\src\inet\ntop-NG\orig-bin\httpdocs`.
Same problem with `--httpdocs-dir f:\MingW32\src\inet\ntop-NG\orig-bin\httpdocs`. So I assume `getopt_long()` is not to blame here.

What could be wrong?

BTW. Why is it logging into `<User>\Documents` and not under 
`<User>\AppData\Roaming\NtopNG` as is more common on Windows?

**Comment by lucaderi** [comment]
@gvanem I see that you are using old ntopng code, I suggest to update first. Why didn't you use the package we build? We do not support MingW32. As of the other problem, please file a separate issue as it makes sense to follow your suggestion.

**Comment by gvanem** [comment]
> I see that you are using old ntopng code

How do you see that? This seems the most recent on your site and what I used
  http://packages.ntop.org/Windows/ntopng-2.2.151130-x64.zip

> I suggest to update first. Why didn't you use the package we build?

Why another of this _negative_ questions? I **used your installer**; the `.exe` inside the above `.zip`.

**Comment by lucaderi** [comment]
You have mentioned Mingw in the previous email, I thought you was using that. Please file a bug for the path issue on windows
