### ISSUE TITLE
[RTT] Delete dialog does not show errors from server

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3576]
![2020-03-19_10-34](https://user-images.githubusercontent.com/5488003/77054307-8b9dbb80-69c7-11ea-937b-42bc01dd0ed9.png)

**Comment by gabryon99** [comment]
Fixed in https://github.com/ntop/ntopng/commit/91e3553e064ae88778bfa7a24596a57cc50f6aae.
