### ISSUE TITLE
nEdge dashboard no longer reachable

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3582]
nEdge used to have a dashboard showing top users, top hosts, and their quotas. This dashboard seems to be no longer reachable.

**Comment by emanuele-f** [comment]
The dashboard should be only visible in router mode.

**Comment by tano46** [comment]
No, it can also be usefull in bridge mode :-)

**Comment by tano46** [comment]
at least for the users and quotas detail

**Comment by emanuele-f** [comment]
The dashboard has been designed for the router mode and it's correctly shown. New features will be postponed after the release.
