### ISSUE TITLE
Tooltips poorly styled

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3584]
![image](https://user-images.githubusercontent.com/3397663/77074594-56a65e80-69f1-11ea-93b3-f326074a7720.png)

**Comment by emanuele-f** [comment]
This seems like a browser rendering problem (webkit)

**Comment by gabryon99** [comment]
What browser are you using?

**Comment by tano46** [comment]
I had the issue with tha last windows chrome version:
Versione 80.0.3987.149 (Build ufficiale) (a 64 bit)

**Comment by gabryon99** [comment]
Please try to refresh your cache

**Comment by tano46** [comment]
It seems to work

**Comment by gabryon99** [comment]
Ok, I close the ticket, thank you.
