### ISSUE TITLE
[RTT] Threshold column without unit of measure

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3589]
Add (ms) next to the column header

![image](https://user-images.githubusercontent.com/3397663/77078041-59f01900-69f6-11ea-8201-0266c8d99b72.png)

then change msec to ms in 

![image](https://user-images.githubusercontent.com/3397663/77078084-64121780-69f6-11ea-9dc1-596662615323.png)

**Comment by gabryon99** [comment]
@simonemainardi 
![Screenshot 2020-03-19 at 19 30 43](https://user-images.githubusercontent.com/14114916/77101887-48b80400-6a18-11ea-80ef-ebc77e01ceff.png)
 Fixed in https://github.com/ntop/ntopng/commit/4ab5f3cc593d8cdb3dc29892739aa8bcc1460dc1

**Comment by gabryon99** [comment]
Changed msec to ms
