### ISSUE TITLE
Dump Flows -F with mysql results in high packets drops

### ISSUE THREAD

**Issue by h8h** [ntop/ntopng#359]
I have a jessie kvm instance with ntopng ([latest sourceforge build](http://sourceforge.net/projects/ntop/files/ntopng/ntopng-2.2.tar.gz/download)) running inside. I decide to dump the expired flows to a mysql database. 

If I activate this option the dropped   packets raise up to 99 % (from 0.45%) and the bandwidth drops to nearly 0 - 1 MB/s (from 90MB/s). 

It seems that it doesn't matter whether the database is running inside the kvm or outside on the host.

The database always listens on an other interface which is not monitored by ntopng.

Has someone shared the same expirence?

**Comment by lucaderi** [comment]
@h8h Can you please share the command line argument you use? I dump flows in MySQL and everything works well. Are you sure MySQL is fast enough?

**Comment by h8h** [comment]
Thank you for the quick reply.

Here is the command linke arguments I use:

```
-G=/var/tmp/ntopng.pid
-F=mysql;10.0.2.2;ntopng;flows;ntopng;xx
-i=eth2
-i=eth3
-i=eth4
-i=eth5
-i=eth6
-i=eth7
-i=eth8
-W=3001
-m=192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,127.0.0.0/8,0.0.0.0/32,224.0.0.0/8,239.0.0.0/8,255.255.255.255/32
-l=1
-Z=/ntopng/sys001
```

For example two interfaces, with 3h View. At the half I disabled mysql dump (-F):

## Eth3

![eth3](https://cloud.githubusercontent.com/assets/953856/12364068/d8f3f636-bbcc-11e5-916e-6d14754d2dde.PNG)
![eth3_drops](https://cloud.githubusercontent.com/assets/953856/12364069/d928886a-bbcc-11e5-9226-d056605c4508.PNG)

## Eth4

![eth4](https://cloud.githubusercontent.com/assets/953856/12364070/d92c94c8-bbcc-11e5-92a1-6f58732e6c27.PNG)
![eth4_drops](https://cloud.githubusercontent.com/assets/953856/12364071/d92cc9fc-bbcc-11e5-86ea-f6a59ed559fe.PNG)

**Comment by lucaderi** [comment]
Ok but MySQL is fast enough for what you want to do? You are probably monitoring too many interfaces for s single DB. Please check the load on MySQL

**Comment by simonemainardi** [comment]
Whereas Elastic Search dump is asynchronous and occurs in a separate thread, MySQL flow export is synchronous and occurs in the same thread that handles the interface traffic. So it is likely that high volumes of exported flows will interfere negatively with the monitoring.

As a quick workaround, you may try and tune MySQL configuration to increase threads, memory, and buffer sizes. In this way, flow export could happen at an higher speed.

As a reminder for ntopng devs, we should
1. make MySQL dump asynchronous;
2. buffer flows in order to issue a single `INSERT INTO` for hundreds/thousands of flows

**Comment by h8h** [comment]
Thank you. Thats mostlikely the reason.

**Comment by tttyu** [comment]
i am facing a different issue when i dump my flows from ntopng into mysql. I am capturing packets using ntopng from an interface and dumping flows into mysql. When i see the tables in mysql it shows me lot of junk characters along with some data from the flow. Please help.

**Comment by emanuele-f** [comment]
What ntopng version are you using?

**Comment by simonemainardi** [comment]
@tttyu that's not junk, it's compressed data: https://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html#function_uncompress

**Comment by tttyu** [comment]
ntopng version 2.4

**Comment by tttyu** [comment]
@simonenainardi when i tried to uncompress using SELECT UNCOMPRESS(flowsv4) it says ERROR 1054 (42S22): Unknown column 'flowsv4' in 'field list'

**Comment by tttyu** [comment]
@simonemainardi i get NULL when i do SELECT UNCOMPRESS('FLOWSV4)

**Comment by tttyu** [comment]
If i use elastic search in ntopng to store my data flow, where does my elastic search database gets stored.How did i view the flow data?

**Comment by simonemainardi** [comment]
`SELECT UNCOMPRESS('FLOWSV4)` is not a valid query; please read the manual and see how to uncompress the columns.

If you use elasticsearch, data will be stored in the ES cluster itself. ntopng won't read the data back.

**Comment by tttyu** [comment]
@simonemainardi could you please tell me how to view the data from the ES cluster .i am getting confused.Please help

**Comment by simonemainardi** [comment]
@tttyu you should use, for example, kibana (https://www.elastic.co/products/kibana). That will give you nice visualizations of ES data.

**Comment by tttyu** [comment]
in a document it said :Via ZMQ ntopng dynamically subscribes to the nprobe, tells the nprobe what type of flow data it is interested in, and the nprobe sends ntopng only this information, without sending all flows to ntopng as probes do. How do i configure ntopng to specify the flows i am interested to gather

**Comment by simonemainardi** [comment]
@tttyu you can use BPF filters for that.

**Comment by tttyu** [comment]
why do i get flows with loopback ip address 127.0.0.1 in mysql database when i dump flows from ntopng using -F modifier in ntopng. How can i not get these flows?

**Comment by simonemainardi** [comment]
-F tells ntopng to dump flows to mysql, so if it sees address 127.0.0.1 (very likely because you are monitoring also the loopbaxk interface) it will dump it. You can use BPF filters if you want to exclude addresses (not host 127.0.0.1)
