### ISSUE TITLE
Wrong Storage Utilization

### ISSUE THREAD

**Issue by gabryon99** [ntop/ntopng#3591]
On MacOS the storage utilization reported is wrong, I have a 512GB SSD inside the computer.

![Screenshot 2020-03-20 at 00 06 20](https://user-images.githubusercontent.com/14114916/77122784-cd1d7d80-6a3e-11ea-8a13-631e66873851.png)

**Comment by simonemainardi** [comment]
issue is due to bsd `df` which returns a different block size.
