### ISSUE TITLE
Invalid RRD country path

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3592]
20/Mar/2020 09:40:17 [timeseries.lua:14] [rrd.lua:237] ERROR: Unable to create C:\Users\Luca\Documents\ntopng\1\countrystats\US wn \\bytes.rrd [creating 'C:\Users\Luca\Documents\ntopng\1\countrystats\US wn \\bytes.rrd': Invalid argument]
20/Mar/2020 09:40:16 [timeseries.lua:14] [rrd.lua:237] ERROR: Unable to create C:\Users\Luca\Documents\ntopng\1\countrystats\US n \\bytes.rrd [creating 'C:\Users\Luca\Documents\ntopng\1\countrystats\US n \\bytes.rrd': Invalid argument]
20/Mar/2020 09:40:15 [timeseries.lua:14] [rrd.lua:237] ERROR: Unable to create C:\Users\Luca\Documents\ntopng\1\countrystats\US  n \\bytes.rrd [creating 'C:\Users\Luca\Documents\ntopng\1\countrystats\US  n \\bytes.rrd': Invalid argument]
20/Mar/2020 09:40:15 [timeseries.lua:14] [rrd.lua:237] ERROR: Unable to create C:\Users\Luca\Documents\ntopng\1\countrystats\NL  n \\bytes.rrd [creating 'C:\Users\Luca\Documents\ntopng\1\countrystats\NL  n \\bytes.rrd': Invalid argument]

**Comment by simonemainardi** [comment]
issue is due to libmaxminddb which seems to provide unclean data. Also occurs for ASes

<img width="692" alt="image" src="https://user-images.githubusercontent.com/3397663/77161388-d1cb4b80-6aa9-11ea-8161-2986f48181be.png">

<img width="365" alt="image" src="https://user-images.githubusercontent.com/3397663/77161432-f45d6480-6aa9-11ea-8035-a0c752d9f485.png">

**Comment by simonemainardi** [comment]
Printing the hex representations of the countries, it seems there's a space (byte `20`) plus other seemingly invalid chars after the country name

```
 string US NW 5553204E57
 string US HW 5553204857
 string US  555320
 string NL  4E4C20
 string GB NW 4742204E57
 string GB  474220
```

**Comment by simonemainardi** [comment]
similarly, as names seems to terminate with an E2 hex char

<img width="623" alt="image" src="https://user-images.githubusercontent.com/3397663/77170253-0e537300-6abb-11ea-92bc-cfbd7123d260.png">

**Comment by simonemainardi** [comment]
Unicode chars are perfectly handed by lua (now using memcpy to avoid any string operation). See as demo:

<img width="546" alt="image" src="https://user-images.githubusercontent.com/3397663/77172400-2ed0fc80-6abe-11ea-8129-ace4a21db501.png">


<img width="606" alt="image" src="https://user-images.githubusercontent.com/3397663/77172365-21b40d80-6abe-11ea-913f-e4c2f8834f51.png">

**Comment by lucaderi** [comment]
Fixed in the latest build
