### ISSUE TITLE
Flows shown but header says 0 flows and hosts

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3597]
This seems like an interface selection issue, as it only occurs when multiple interfaces are present

![abc](https://user-images.githubusercontent.com/5488003/77153599-f0254d00-6a91-11ea-9cf2-5def7d0f9652.png)

**Comment by simonemainardi** [comment]
fixed in https://github.com/ntop/ntopng/commit/794cd523c6b38e0dbde2291ff1100517cff620cd
