### ISSUE TITLE
Interface prefs units of measure

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3599]
Please move Mbit/s and sec on the right of the input fields in

<img width="718" alt="image" src="https://user-images.githubusercontent.com/3397663/77158258-3f27ae00-6aa3-11ea-9cb8-a3e4e0e10909.png">

**Comment by gabryon99** [comment]
Fixed in https://github.com/ntop/ntopng/commit/ffea9b2165521ee1fe1991d3587293b6d1884ada.
