### ISSUE TITLE
ntopng not showing professional version

### ISSUE THREAD

**Issue by juesor** [ntop/ntopng#360]
© 1998-2016 - ntop.org  Generated by ntopng Community v.2.3.160114 for user admin and interface p2p1

Installed Packages
ntopng.x86_64                                                                      2.3.160114-785                                                                      @ntop

Jan 14 14:31:58 HEND-ntopng ntopng[32653]: [NtopPro.cpp:158] ERROR: [LICENSE] Invalid or missing ntopng License [License mismatch error]

**Comment by lucaderi** [comment]
@juesor Please paste your license and the output of ntopng --version

**Comment by juesor** [comment]
C6151D64A4ABBEF7447E4BBD3FA762111475181184AFA4417F

ntopng ~]# ntopng --version
v.2.3.160114 [Professional Edition]
GIT rev:   dev:c4546c4e75b39b78114bbe4bf4dfc4b5b054c5a5:20160114
Pro rev:   r537
System Id: A53E30B69105A1EF
Built on:  CentOS Linux release 7.1.1503 (Core)

We were DDOS'ed last night and found the Flows Flood in NtopNG and our fastnetmon detected it and wanted to see some more info about it.

**Comment by lucaderi** [comment]
I do not have any license for systemId A53E30B69105A1EF, you used to have 3D0153209105A1EF as ssytemId. Please go to http://www.ntop.org/support/kb/how-can-i-move-a-license-to-a-new-server/

**Comment by juesor** [comment]
I entred my order ID and email address and recieved maintenance is over.

Do you have to reset it manually?

**Comment by lucaderi** [comment]
Please mail me your orderId so I can see what's happening

**Comment by juesor** [comment]
Did you get my orderID?

**Comment by juesor** [comment]
I still have not  received a response to my email.  Is someone available?

**Comment by lucaderi** [comment]
I replied you privately. The orderId 1389192120 you used is not for ntopng but for nprobe. Each products has a different license and you cannot mix them up
