### ISSUE TITLE
ntopng does not terminate gracefully on windows

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3601]
ntopng termination always ends up with

<img width="711" alt="image" src="https://user-images.githubusercontent.com/3397663/77158816-5b781a80-6aa4-11ea-8b37-e13a77182ae2.png">

**Comment by lucaderi** [comment]
![Screen Shot 2020-03-21 at 17 26 27](https://user-images.githubusercontent.com/4493366/77231119-1f72b180-6b99-11ea-885f-4314a8e8dcfe.png)
Unable to reproduce it with the current build. This said you should not start it from shell but from the service manager
