### ISSUE TITLE
Invalid disk-space calculation on MacOS

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3602]
![Screen Shot 2020-03-20 at 17 07 58](https://user-images.githubusercontent.com/4493366/77182825-ac503900-6acd-11ea-86f6-766566bd70b4.png)

This is a 1TB disk

**Comment by cardigliano** [comment]
It is likely ntopng was still using data from the cache, computed by an old script version that was assuming a block size = 1024 (instead of 512), that would explain the 2x system and total size. After a few tests forcing a refresh, everything looks fine.

**Comment by lucaderi** [comment]
Fixed
