### ISSUE TITLE
ntopng unable to use InfluxDB

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3603]
For some unknown reason, even though ntopng uses InfluxDB for writing data, it still uses and creates RRD files on disk

![Screen Shot 2020-03-21 at 17 21 31](https://user-images.githubusercontent.com/4493366/77231009-7b890600-6b98-11ea-8697-0e4b59ee4296.png)
![Screen Shot 2020-03-21 at 17 20 56](https://user-images.githubusercontent.com/4493366/77231013-7c219c80-6b98-11ea-83a9-f973ad8c469e.png)

The following error is reported on shell
21/Mar/2020 17:25:00 [AlertCheckLuaEngine.cpp:167] WARNING: Script failure[C:\ntop\ntopng\x64\Release\scripts\callbacks\system\system.lua] [...png\plugins\callbacks\system\system\influxdb_monitor.lua:80: attempt to call a nil value (method 'get_exported_points')]

**Comment by emanuele-f** [comment]
Please buiild a new package to test the fix above

**Comment by emanuele-f** [comment]
Fixed in 85a84c95fd29d3ea110970846f29636ed4e54db9 and be0c0a9566628038f24e4f0251d35861bc4a0a10
