### ISSUE TITLE
Error while reporting data in graph

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3605]
![Errore ntopng](https://user-images.githubusercontent.com/4493366/77248017-8d20eb00-6c36-11ea-92ec-4ec35e5d4c72.png)

**Comment by simonemainardi** [comment]
please provide version used, ntopng configuration, and details to reproduce.

**Comment by samuelesabella** [comment]
**System**: Ubuntu 18.04.4
**Version**: ntopng Community Edition v.3.9.200312 and InfluxDB v1.7.10
I inject pcap traffic in a dummy interface, namely fake_if, and use ntopng to produce time-series for hosts in different subnetworks. The pcaps I used can be found at [CICIDS2017](https://www.unb.ca/cic/datasets/ids-2017.html)
``` 
$ ntopng -i fake_if --https-port=3443 -m 192.168.10.0/24
```
All preferences on timeseries are set on (_both_, _full_, _per category_ where necessary) except "Internals". Resolution has been set to 10 seconds. "Query Timeout" has the default value 10s (maybe is this the cause?). 

The error raised when I tryied to visualize the time-series for the host 192.168.10.50

**Comment by emanuele-f** [comment]
@samuelesabella a new package will be available in one hour, please check it out and let us know if the problem is fixed

**Comment by samuelesabella** [comment]
Thank you Emanuele, now everything is working.

**Comment by emanuele-f** [comment]
Thank you for reporting.

**Comment by samuelesabella** [comment]
Hello. I'm running the same configuration with ntopng v.4.1.200330. I have found another problem while trying to visualize time series data. Thank you.
![Screenshot 2020-04-01 at 18 25 45](https://user-images.githubusercontent.com/18717354/78161917-6fc5fb00-7446-11ea-9769-9498223ce40c.png)
