### ISSUE TITLE
Cannot update ntopng due to pfring-dkms version mismatch, depends (3.3.0-2304 but 3.3.0-2316)

### ISSUE THREAD

**Issue by noybman** [ntop/ntopng#3607]
Its looking like this was an issue once before, and I'm not too interested in removing everything to reinstall it....
https://github.com/openzfs/zfs/issues/6037

ndpi is already the newest version (3.3.0-2316).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.

The following packages have unmet dependencies:
 pfring : Depends: ndpi (= 3.3.0-2304) but 3.3.0-2316 is to be installed

The following packages have unmet dependencies:
 ntopng : Depends: pfring (= 7.7.0-2876) but 7.7.0-2874 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by noybman** [comment]
Whoa... juxtaposed destiny....
This similar to issue #3607, is similar to #6037  O_o
"The following packages have been kept back. #6037"

My system is Ubuntu 18.04, Kernel 5.3.0-42-generic if this is useful.

**Comment by noybman** [comment]
I went ahead and rolled back ndpi, 
sudo apt-get install ndpi=3.3.0-2304
then apparently was required to also do a kernel update (due to the pfring dependency failing to build),
sudo apt install linux-headers-5.3.0-42
then doing a sudo apt-get install pfring-dkms resolved errors and I was able to do the regular update && upgrade with no further errors.

I'm not sure how the "newer ndpi" ever got on my system, but apparently 3.3.0-2304 is the latest:

sudo apt-get install ndpi
Reading package lists... Done
Building dependency tree
Reading state information... Done
ndpi is already the newest version (3.3.0-2304).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by cardigliano** [comment]
@noybman we fixed the repository, please update again and let us know. Thank you.

**Comment by noybman** [comment]
Agreed. No issues on update.

On March 24, 2020 9:25:18 AM EDT, Luca Deri <notifications@github.com> wrote:
>Closed #3607.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ntop/ntopng/issues/3607#event-3159639472

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
