### ISSUE TITLE
Interfaces dropdown too wide

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3609]
Need to short interfaces names when they are too long to avoid this

![image](https://user-images.githubusercontent.com/3397663/77260663-bd45a980-6c89-11ea-9153-1cff04ebf90f.png)

**Comment by gabryon99** [comment]
<img width="552" alt="Screenshot 2020-03-23 at 12 34 00" src="https://user-images.githubusercontent.com/14114916/77312620-9d9e9780-6d02-11ea-886a-733c3c2bc4db.png">
 Fixed in the latest commit: https://github.com/ntop/ntopng/commit/5eff6713d3472af24ea2c894c39cede62f9c6e36
