### ISSUE TITLE
Invalid character reported for top talker host

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#3614]
>3.20.2.34-DESKTOP-RB5T12G.f255ede3-0a7f-4756-b5a0-5bf861730466

**Comment by emanuele-f** [comment]
What is the output of `ntopng --version`? Which is the invalid character reported?

**Comment by lucaderi** [comment]
![Screen Shot 2020-03-23 at 19 14 05](https://user-images.githubusercontent.com/4493366/77348938-91363100-6d3a-11ea-9197-5f6cbd8cc74c.png)
Another example of poor nome decoding
