### ISSUE TITLE
Implement ICMP Support 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3616]
The Ping.cpp class does not support Windows.

In essence this is the API that needs to be implemented by the Window side of the Ping class 
https://docs.microsoft.com/en-us/windows/win32/api/icmpapi/. See also https://stosd.wordpress.com/2017/01/28/windows-ping/ as example.

Note that v4 and v6 have different APIs.

Once this is implemented RTT can be enabled in scripts/plugins/rtt/user_scripts/system/rtt.lua by modifying "windows_exclude = true" to false.

**Comment by emanuele-f** [comment]
After the implementation, `menu.lua` should be also modified as follows:
Replace `if(not rtt_script_found and isAdministrator() and (not ntop.isWindows())) then` with `if(not rtt_script_found and isAdministrator()) then`

**Comment by lucaderi** [comment]
After some discussions, adding Windows ICMP support is not a quick thing to implement and adding "UDP Ping" will be a deviation with respect to Windows. So better leave things as are today
