### ISSUE TITLE
Unable to install ntopng 3.9 from debian repo

### ISSUE THREAD

**Issue by r1bnc** [ntop/ntopng#3617]
I tried to install ntopng from the Debian 10 repo but it is version 3.8. I removed it and decided to install from: `http://packages.ntop.org/apt-stable/`

There is no buster release so  I just went on installing the stretch version:
```
$ wget http://apt-stable.ntop.org/stretch/all/apt-ntop-stable.deb
$ sudo apt install ./apt-ntop-stable.deb
$ sudo apt-get clean all
$ apt-get update

...
Hit:6 http://packages.ntop.org/apt-stable/buster x64/ InRelease    
...


$ sudo apt-get install pfring nprobe ntopng ntopng-data n2disk cento nbox
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package pfring
E: Unable to locate package nprobe
E: Unable to locate package n2disk
E: Unable to locate package cento
E: Unable to locate package nbox

```

Checking the apt candidate with `apt-cache policy ntopng` returns with the default Debian repo ntopng:
```
ntopng:
  Installed: 
  Candidate: 3.8+dfsg1-2.1
  Version table:
 *** 3.8+dfsg1-2.1 500
        500 http://httpredir.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

I don't know whether this is my debian installation problem, I installed ntopng on my Buster Raspberry Pi and it worked but now on x86_64 it won't work.
I am using Debian 10.3 Buster with Linux kernel 5.4.0-0.bpo.4-amd64.

Content of `/etc/apt/sources.list.d/ntop-stable.list`
```
deb http://packages.ntop.org/apt-stable/buster/ x64/
deb http://packages.ntop.org/apt-stable/buster/ all/
```

**Comment by emanuele-f** [comment]
Debian buster support is only available since ntopng 3.9, which is the current dev version. So please install the dev version of ntopng or wait a day for the new ntopng stable version to be available.
