### ISSUE TITLE
Ntopng compilation src/Prefs.o' failed on debian x86

### ISSUE THREAD

**Issue by shadrack222** [ntop/ntopng#362]
Good morning,
- On Linux 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt20-1+deb8u2 (2016-01-02) i686 GNU/Linux
- With ntopng Update 3bea0a7..4267c60

I got the following error when i tried to compile ntopng after nDPI:

src/Prefs.cpp:269:157: error: invalid conversion from ‘void\* (_)(long unsigned int)’ to ‘void_ (_)(size_t) {aka void_ (_)(unsigned int)}’ [-fpermissive]
   struct ndpi_detection_module_struct *ndpi_struct = ndpi_init_detection_module(ntop->getGlobals()->get_detection_tick_resolution(), localmalloc, free, NULL);
                                                                                                                                                             ^
In file included from /usr/local/include/libndpi-1.7.1/libndpi/ndpi_main.h:33:0,
                 from /opt/ntopng/include/ntop_includes.h:99,
                 from src/Prefs.cpp:22:
/usr/local/include/libndpi-1.7.1/libndpi/ndpi_api.h:77:40: note: initializing argument 2 of ‘ndpi_detection_module_struct_ ndpi_init_detection_module(u_int32_t, void\* (_)(size_t), void (_)(void_), ndpi_debug_function_ptr)’
   struct ndpi_detection_module_struct *ndpi_init_detection_module(u_int32_t ticks_per_second,
                                        ^
Makefile:129: recipe for target 'src/Prefs.o' failed
make: *_\* [src/Prefs.o] Error 1

Best regards,

Eric.

**Comment by lucaderi** [comment]
Please update nDPI and try again: that should fix the problem

**Comment by shadrack222** [comment]
Hello,

Thanks for your feedback,
Restart everything from scratch.
Still same problem after nDPI compilcation:

src/Prefs.cpp: In function ‘void usage()’:
src/Prefs.cpp:269:157: error: invalid conversion from ‘void\* (_)(long unsigned int)’ to ‘void_ (_)(size_t) {aka void_ (_)(unsigned int)}’ [-fpermissive]
   struct ndpi_detection_module_struct *ndpi_struct = ndpi_init_detection_module(ntop->getGlobals()->get_detection_tick_resolution(), localmalloc, free, NULL);
                                                                                                                                                             ^
In file included from ../nDPI/src/include/ndpi_main.h:33:0,
                 from /usr/local/src/ntopng/include/ntop_includes.h:99,
                 from src/Prefs.cpp:22:
../nDPI/src/include/ndpi_api.h:77:40: note: initializing argument 2 of ‘ndpi_detection_module_struct_ ndpi_init_detection_module(u_int32_t, void\* (_)(size_t), void (_)(void_), ndpi_debug_function_ptr)’
   struct ndpi_detection_module_struct *ndpi_init_detection_module(u_int32_t ticks_per_second,
                                        ^
Makefile:129: recipe for target 'src/Prefs.o' failed
make: *_\* [src/Prefs.o] Error 1

Best regards,

Eric.

**Comment by simonemainardi** [comment]
no changes between 3bea0a7 and 4267c60 involve either nDPI or the Prefs.

Please, confirm that you `cd`ed into the nDPI source folder and did a `git pull && ./configure && make` into that directory before compiling ntopng.

**Comment by simonemainardi** [comment]
I was able to reproduce the error on freebsd 8.1

I made a fix. Please check now.

**Comment by shadrack222** [comment]
Hello,

yes i do confirm: i cd into the nDPI source folder and did a git pull && ./configure && make into that directory before compiling ntopng.

I just tried with the fix, it works, thanks a lot.

Best regards,

Eric.
