### ISSUE TITLE
Change localhost's thumbnail 

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#3620]
Change the thumbnail from a flag to a different image ex. pc icon or other more comprensible icon

**Comment by MatteoBiscosi** [comment]
Localhost thumbnail changed to this new icon:
![Screenshot from 2021-03-30 17-23-45](https://user-images.githubusercontent.com/49585191/113014565-fbb75380-917c-11eb-86d2-24fe221d69eb.png)
