### ISSUE TITLE
Add colors on the remote/multicast/other types box

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#3621]
Add color in the boxes so that the UI has a cleaner look

![Capture](https://user-images.githubusercontent.com/33870399/77482406-1d715280-6e26-11ea-80b1-ef4634490792.PNG)

**Comment by DGabri** [comment]
Also add a pop up box that explains what something means or what it does

**Comment by lucaderi** [comment]
Please make an example of what this box should contain

**Comment by lucaderi** [comment]
@gabryon99 Please choose a unique color for multicast so that it is not confused with remote. Each label should have a a different color as in github labels for instance (i.e. the same color cannot be shared by two different labels)

**Comment by gabryon99** [comment]
<img width="1134" alt="Screenshot 2020-04-01 at 17 40 30" src="https://user-images.githubusercontent.com/14114916/78157118-e3b0d500-743f-11ea-83ec-83ce53b36b63.png">

Is this ok?
