### ISSUE TITLE
Add 2 vertical lines when function is activated on dash

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#3622]
Use the same thumbnail as the one used in media players otherwise the user doesn't understand if the press of the button worked as the UI is lagging because of the timeframe

![Dash](https://user-images.githubusercontent.com/33870399/77482939-4a723500-6e27-11ea-93d0-14eee73bd617.PNG)

**Comment by gabryon99** [comment]
**Playing State**
This is when playing:

![Screenshot 2020-03-30 at 11 39 58](https://user-images.githubusercontent.com/14114916/77898381-56bd1e80-727b-11ea-9396-2788654fd78d.png)

**Stopped State**
This is when stopped:

![Screenshot 2020-03-30 at 11 40 07](https://user-images.githubusercontent.com/14114916/77898398-5b81d280-727b-11ea-8456-cfe9315fab9d.png)

**Comment by gabryon99** [comment]
Fixed in https://github.com/ntop/ntopng/commit/953c6cd40fe4c4734610b125de617baef09f9eb4
