### ISSUE TITLE
Bugged parenthesis layout

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#3626]
Wrong layout after host name on traffic dashboard
![bug](https://user-images.githubusercontent.com/33870399/77518165-8fc15180-6e7d-11ea-847c-6fe2c7207fe1.PNG)

**Comment by emanuele-f** [comment]
Can you provide a PCAP to reproduce this?

**Comment by lucaderi** [comment]
Not reproducible at the moment. Will reopen if necessary
