### ISSUE TITLE
Another UI Inconsistency

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#3627]
The UI is ver inconsistent, if another page/message box opens it has to be consistent with the main UI layout like this message, the shop, or the packages.ntop.org website that is very outdated
![UI](https://user-images.githubusercontent.com/33870399/77518516-3574c080-6e7e-11ea-90c8-76dd5d10e19e.PNG)

**Comment by lucaderi** [comment]
Please provide the URL of the page that contains this box

**Comment by DGabri** [comment]
/lua/pro/admin/edit_profiles.lua

**Comment by gabryon99** [comment]
Fixed in https://github.com/ntop/ntopng/commit/96b088529059c55ce1492135fe00ca2ca1c2a1f8
