### ISSUE TITLE
Bad layout on traffic dashboard

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#3628]
If the dashboard doesn't have many pie charts to display but just one it must be centered otherwise it is not very nice to look at. For example for better layout put it centered and start to slide them on the sides if you have more so that they are more readable.

![pie](https://user-images.githubusercontent.com/33870399/77519064-20e4f800-6e7f-11ea-934d-515b1b59fc0a.PNG)

**Comment by gabryon99** [comment]
What is the page?

**Comment by DGabri** [comment]
/?ifid=2&page=TopHosts
