### ISSUE TITLE
Ubuntu 14.04 LTS Error

### ISSUE THREAD

**Issue by mmaxwell5** [ntop/ntopng#363]
I have a fresh install of Ubuntu 14.04 LTS server.  When I install stop and then try to run ntopng -h I get the following error:
ntopng: error while loading shared libraries: libmysqlclient.so.18: cannot open shared object file: No such file or directory

**Comment by bauruine** [comment]
you need to install libmysqlclient18 and libpcap0.8

Those are missing in the package dependencies list.

**Comment by mmaxwell5** [comment]
Could you please send me noting.conf and noting.start sample files for ntopng 2

Thank you

Michael Maxwell

**Comment by simonemainardi** [comment]
`ntopng.conf`contains ntopng startup options (run `ntopng -h` for a list), one per line. There is no default configuration. If no `ntopng.conf` file is created by the user, `ntopng` creates it with a couple of lines.
For the sake of example, here is an `ntopng.conf` file under `/etc/ntopng`

```
-G=/var/tmp/ntopng.pid
-e=
-i=eth0
-i=tcp://127.0.0.1:5556
-w=3000
-m=192.168.51.0/24,192.168.13.0/24,192.168.0.0/24
-n=1
-d=/var/tmp/ntopng
-q=
```

The `ntopng.start` is empty.
