### ISSUE TITLE
Implement Suggest a Feature

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3630]
![Screen Shot 2020-03-25 at 18 10 19](https://user-images.githubusercontent.com/4493366/77565122-0f720f00-6ec4-11ea-8293-ca30419597a0.png)

**Comment by gabryon99** [comment]
We can add an entry to help submenu inside the sidebar

**Comment by gabryon99** [comment]
<img width="314" alt="Screenshot 2020-03-26 at 16 17 46" src="https://user-images.githubusercontent.com/14114916/77663446-56700b00-6f7d-11ea-9fa7-2fa1016653dc.png">

**Comment by gabryon99** [comment]
implemented in https://github.com/ntop/ntopng/commit/c8465b571744f7bf4a6376e8040668dbc4499f98
