### ISSUE TITLE
All applications unknown

### ISSUE THREAD

**Issue by radical-squared** [ntop/ntopng#3631]
Hello

I hope that amidst the coronavirus outbreak, everyone is healthy and safe.

I've set up the 100$/€ NetFlow nProbe with EdgeRouter X. It works very well with ntopng 3.8. However, upon upgrading to ntopng 4.0, the flows are collected, but all applications are marked as unknown.

![ntopng](https://user-images.githubusercontent.com/26088959/77578364-b496e280-6ed8-11ea-8420-5dd0fa3cb69c.png)

The nProbe running on EdgeRouter X is v.7.3.160505 (r5103) [Embedded] for x86_64-unknown-linux-gnu.

I would appreciate your help.

**Comment by simonemainardi** [comment]
please report the configuration files

**Comment by radical-squared** [comment]
ntopng [192.168.1.12] ntopng.conf:
-i=tcp://192.168.1.15:1234
-m=192.168.0.0/16

nProbe v.7.3.160505 [192.168.1.15]:
nprobe --zmq tcp://0.0.0.0:1234 -i br0 -n none

**Comment by lucaderi** [comment]
This is a 2016 product that has been discontinued years ago (and for which we offer no maintenance) as Ubiquity has filled up the disk/memory space on their devices making our tool unusable. Please use a raspberry or x86 box instead

**Comment by radical-squared** [comment]
EdgeRouter X is used for nProbe only, ntopng runs on x86 box. The setup works perfect with ntopng 3.8. It gets the problems with 4.0 and 4.1.

**Comment by emanuele-f** [comment]
The ZMQ api inside ntopng has changed, you need the new nprobe in order to use the new ntopng, but the new nprobe is not available for the edgerouter for the reasons explained above.

**Comment by radical-squared** [comment]
Oh, I understand now. Thank you for explaining that to me. I've now installed ntopng/nprobe on my raspberry. I connected it to my switch and set its port to mirror the uplink. I then connect to ntopng over raspberry's wlan interface. It works fine, but it doesn't show all flows and hosts. What's the right way to do it?

**Comment by emanuele-f** [comment]
Please open a new issue and report the ntopng and nprobe version and configuration used.
The following links may help:

https://www.ntop.org/nprobe/network-monitoring-101-a-beginners-guide-to-understanding-ntop-tools/
http://www.ntop.org/ntopng/how-to-analyse-mikrotik-traffic-using-ntopng/
