### ISSUE TITLE
Top Senders and Top Receivers are inactive from "Interface" menu 

### ISSUE THREAD

**Issue by Yoshihiro-jp** [ntop/ntopng#3632]
I think that this is very minor problem. Kindly refer the attached file.
![top senders and top receivers](https://user-images.githubusercontent.com/58843707/77625264-9e476000-6f86-11ea-82d5-9519d5dddf8e.png)

I am using with v.4.0.200325 of ntopng Enterprise Edition.
From "Interface" → "Graph Icon"(if_stats.lua) → Pull down 
As you could see in the attached file the Top senders and Top Receivers are always inactive but after I click some items like "Top applications" it could be active.

regards,
Yoshihiro

**Comment by emanuele-f** [comment]
Clicking on other zoom resolutions (e.g. 30m, 1h) should make the menu entry active. I agree that this is not clear from the gui, we should add a label or something to explain why they are disabled.

**Comment by simonemainardi** [comment]
please remove the entries from the dropdown when not available

**Comment by emanuele-f** [comment]
Implemented in pro
