### ISSUE TITLE
UI suggestion

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#3633]
I think that all the buttons should have the same colour and be consistent with the ntop style. Blue buttons should be orange and the same goes for the stats line on the top bar chart.

![button1](https://user-images.githubusercontent.com/33870399/77635005-2bbc8d00-6f52-11ea-8485-b0e23c764951.PNG)
![stasts](https://user-images.githubusercontent.com/33870399/77635007-2c552380-6f52-11ea-81aa-1bf40cad0b36.PNG)

**Comment by lucaderi** [comment]
@DGabri Do you mean dark mode orange buttons, light mode blue buttons?
