### ISSUE TITLE
Title bar enhancement

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#3634]
You can't tell which title is selected because of bad color pick.

![Titles](https://user-images.githubusercontent.com/33870399/77635308-a4234e00-6f52-11ea-9b6f-535a4d6f5700.PNG)

**Comment by gabryon99** [comment]
Now in dark mode the active element is orange so the user can distinguish which element is active in the bar. See the commit: https://github.com/ntop/ntopng/commit/0f613d25be8a9aefb5fa8b3b80a8c907cf407c7b for further details.
