### ISSUE TITLE
 DHCP Ranges is not saved

### ISSUE THREAD

**Issue by ilmarchetti** [ntop/ntopng#3636]
Hi I'm going to set the various DHCP ranges (Interface -> lightning bolt icon). 
I insert them and save. 
![dhcp_configured](https://user-images.githubusercontent.com/62704266/77652254-40a71980-6f6e-11ea-8035-4726d429369d.JPG)
When I return to the page they are gone.....
![DHCP_gone](https://user-images.githubusercontent.com/62704266/77652285-48ff5480-6f6e-11ea-93e9-20280cd3f196.JPG)

**Comment by emanuele-f** [comment]
Cannot reproduce. After you click save, the configured ranges are properly shown? After the save, what specific steps do you take that make the previously configured ranges disappear? Can you check if the ntopng `Uptime` in the bottom right corner resets (which would indicate a crash)?

**Comment by ilmarchetti** [comment]
Hello !
I have done other experiments. it seems that the problem occurs when it exceeds 10 lines of value.
if instead I set the display of the rows to 20 I see all the values, if I go back to the display to 10 rows when I insert a new row it cancels the last one on the second page. In addition, if I go to the second page and delete a line, it also cancels all those on the first page.
The NTopng uptime don't reset

**Comment by emanuele-f** [comment]
Ok I can reproduce it

**Comment by emanuele-f** [comment]
A new package will be available in one hour
