### ISSUE TITLE
Clicking on Change Password has no effect

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3638]
Clicking on the element has no effect. Nothing happens.

<img width="255" alt="image" src="https://user-images.githubusercontent.com/3397663/77655270-76e69800-6f72-11ea-86aa-4d0536df2dde.png">

**Comment by gabryon99** [comment]
Ok fixed the issue in: https://github.com/ntop/ntopng/commit/6d66d9e74475e17cf3a9b3d0ce700ae47a72341f
