### ISSUE TITLE
tracking hosts - sizing

### ISSUE THREAD

**Issue by seismiccollision** [ntop/ntopng#364]
is setting "sticky-hosts" to "local" going to flush tracked remote hosts from the web UI when they are idle? as i am ramping up my load on ntopng I am hitting about 600k tracked hosts and 3.5k flows before running out of 8GB memory. as the list of hosts ramp up i see hosts that seem to have been idle for an extended period of time yet still appear in the web ui with "-S" flag at default. I just set "-S local" to see if that changes the behavior. I am still working out sizing this properly so that I get the visibility i need without taking up unnecessary resources and i'm honestly most interested in the east-west traffic which would be local-to-local

**Comment by simonemainardi** [comment]
@seismiccollision currently the purging process is non deterministic. That is, every second, 1 / 32th of the hash table holding hosts (flows) is checked for expired entries. Thresholds are hardcoded but can be configured at compile-time.

So there is no guarantee that all expired hosts (flows) are purged from the memory every second.

the -S is none by default, that is, both local and remote hosts are purged. If you specify -S local, then you'll end up in higher memory consumption.

**Comment by seismiccollision** [comment]
@simonemainardi 
Thanks for the explanation!

However, so far the statement that -S local would purge fewer hosts does not seem to be the case. I am now 30 hours up with that flag and only tracking ~3,000 hosts instead of the ~150,000 hosts that seemed to collect over night (the vast majority of which were remote)

**Comment by simonemainardi** [comment]
@seismiccollision do you have any updates?

also please keep in mind that you can cap the maximum number of hosts and flows from the command line:

```
     "[--max-num-flows|-X] <num>          | Max number of active flows"
     "[--max-num-hosts|-x] <num>          | Max number of active hosts"
```

**Comment by seismiccollision** [comment]
@simonemainardi it still seems like the "-S local" decreased the number of tracked hosts from not including the flag. instead of 150,000 hosts and 1500 flows i now see 7000 hosts and 10,000 flows and it seems improved with that -S local

**Comment by seismiccollision** [comment]
well i'm very happy with my setup at the moment so i'll close this out, thanks for all the support!
