### ISSUE TITLE
Broken switch from System to non-System inteface and vice versa

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3640]
Start from

<img width="303" alt="image" src="https://user-images.githubusercontent.com/3397663/77655989-85817f00-6f73-11ea-92ed-f6c3b8ef2a20.png">

switch to system

<img width="280" alt="image" src="https://user-images.githubusercontent.com/3397663/77656017-8ca88d00-6f73-11ea-97c0-41e98ee7fc89.png">

now, if I open the interface dropdown and click on `en0` I am brought to `lo0` rather than to `en0`

<img width="439" alt="image" src="https://user-images.githubusercontent.com/3397663/77656127-b1046980-6f73-11ea-8d84-3dcd955fd2cb.png">

**Comment by gabryon99** [comment]
![ezgif-1-fb3735899aa7](https://user-images.githubusercontent.com/14114916/77666869-c84a5380-6f81-11ea-9f0b-f5b3f440d9f9.gif)

Problem fixed, the swtich won't happening because the form that handles the switch didn't have the interfaced id as paramater.

**Comment by gabryon99** [comment]
fixed in https://github.com/ntop/ntopng/commit/c8465b571744f7bf4a6376e8040668dbc4499f98
