### ISSUE TITLE
ERROR: unsafe header/library path used in cross-compilation: '-I/usr/local/include'

### ISSUE THREAD

**Issue by pikonek** [ntop/ntopng#3642]
Trying to cross compile ntopng using buildroot

BUILD ENVIRONMENT: Ubuntu 18.04
TARGET ENVIRONMENT: RASPBERRY PI

I'm getting an since there is hard coded /usr/local/include

Here is my .mk file 

```
NTOPNG_VERSION = 599a88db97c096cfc76312a7e3216d099260eccf
NTOPNG_SITE = $(call github,ntop,ntopng,$(NTOPNG_VERSION))

define NTOPNG_RUN_AUTOGEN
	cd $(@D) && PATH=$(BR_PATH) ./autogen.sh
endef

NTOPNG_PRE_CONFIGURE_HOOKS += NTOPNG_RUN_AUTOGEN
HOST_NTOPNG_PRE_CONFIGURE_HOOKS += NTOPNG_RUN_AUTOGEN

NTOPNG_CONF_ENV += \
	CFLAGS="-I$(STAGING_DIR)/usr/include"

NTOPNG_DEPENDENCIES += host-automake host-autoconf host-libtool libndpi libpcap

$(eval $(autotools-package))
```

**Comment by lucaderi** [comment]
What is the question here?

**Comment by simonemainardi** [comment]
Cross compiling with build root is not supported. Currently, we cannot maintain it. If you want to take care of this, please send us a pull request and we will include it.

**Comment by Bibo000001** [comment]
how to solve it
