### ISSUE TITLE
Errors spammed in dashboard.lua 

### ISSUE THREAD

**Issue by gabryon99** [ntop/ntopng#3643]
In ntopng pro version, the browser console spam the following messages:
<img width="1792" alt="Screenshot 2020-03-26 at 17 30 09" src="https://user-images.githubusercontent.com/14114916/77671131-73114080-6f87-11ea-86e9-75965d0417ee.png">

**Comment by emanuele-f** [comment]
Please troubleshoot and fix them

**Comment by gabryon99** [comment]
Fixed, the problem was caused by a variable which contained the undefined value.
