### ISSUE TITLE
Bubble Chart Style

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#3645]
I think that the bubbles on this chart should be transparent so that the numbers on the axis are more readable 
![Host_explorer](https://user-images.githubusercontent.com/33870399/77685937-82e74f80-6f9c-11ea-8b8d-c02364c2fc7a.PNG)

**Comment by gabryon99** [comment]
<img width="442" alt="Screenshot 2020-03-27 at 15 30 49" src="https://user-images.githubusercontent.com/14114916/77766443-f2624b00-703f-11ea-991b-30eea394e855.png">

I add a little bit of transparency (0.45) to the the bubbles

**Comment by gabryon99** [comment]
<img width="442" alt="Screenshot 2020-03-27 at 15 31 56" src="https://user-images.githubusercontent.com/14114916/77766564-19b91800-7040-11ea-817a-038d3aaef76c.png">

This is how it looks like in dark mode

**Comment by gabryon99** [comment]
Implemented in https://github.com/ntop/ntopng/commit/9e07efe00970c511145d9a0faed824a3746e2260.
