### ISSUE TITLE
Top Hosts Chart

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#3647]
This top host chart is not self explanatory and when I go over it with the mouse pointer you can;t see the timeframe very well. I think that over the pointer there should be a vertical line like in financial charts or another sort of identifier.

![Top_host_local](https://user-images.githubusercontent.com/33870399/77686146-c477fa80-6f9c-11ea-8549-0ccc74145c5a.PNG)

**Comment by lucaderi** [comment]
A note has been added to the end of the page to report what is displayed. In the future this page will be discontinued and needs to be replaces with a more comprehensive page as you also requested.
