### ISSUE TITLE
Restore ntopng version check

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3648]
![image](https://user-images.githubusercontent.com/4493366/77694575-884b9680-6faa-11ea-981e-ef1d49183057.png)

This feature has been removed by mistake and should be restored in both stable and dev versions

**Comment by emanuele-f** [comment]
This was removed in 8f652cff71493bb827424c7b3a2b0a1d26f1c16a in favor of the package manager-based update check
