### ISSUE TITLE
Blog notifications marked as read

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3649]
When a user opens the bell, all the new blog notifications are marked as read and ntopng remembers this. However, this seems to be global, meaning when a user A opens the bell, no other ntopng user will see the red badge with the notifications. This must be per-user.

**Comment by emanuele-f** [comment]
Moreover it seems like after some time the state of the notification is reset and it shows 3 new posts to read, however no new posts were added.

**Comment by gabryon99** [comment]
I fixed this in https://github.com/ntop/ntopng/commit/e486d050582d3a147100670ba0694a240da85793. Now there is to save the read notification in redis as we discussed.

**Comment by emanuele-f** [comment]
Please note that if I click with the middle mouse button on the notification (to open it into a new tab) the notification is not marked as read

**Comment by lucaderi** [comment]
I believe the current behaviour is good. Let's move to the next ticket
