### ISSUE TITLE
nTopng 2.2.160118 - Professional Edition 'Traffic Report' Reporting 'Other' for hostname

### ISSUE THREAD

**Issue by timdoes69** [ntop/ntopng#365]
![ntopngscreenshot2](https://cloud.githubusercontent.com/assets/16872078/12572557/5140d7b8-c3ab-11e5-8e9d-314bc4165877.png)
Version 2.2.160118 - Professional Edition
Platform Debian jessie/sid (x86_64) - 64 bit
Built on Ubuntu 14.04.3 LTS
nDPI 1.7.0-1.7-stable-180-a121161
RRDtool 1.4.7
Redis Server 2.8.4
Mongoose web server 3.7
LuaJIT LuaJIT 2.0.3
ØMQ 4.0.4
GeoIP 1.6.0
Data-Driven Documents (d3js) 2.9.1 / 3.0

After installing the above package the 'Traffic Report' section:
1. Starting reporting 'Other' instead of hostname or ip (Top Remote Hosts [Average Traffic/sec])
2. The following sections no longer provided hyper-text links;
a. Top Local OS [Average Traffic/sec]
b. Top ASN [Average Traffic/sec]

I Did Not have this issue with 2.0.150531

I have attached a screen-shot that depicts the issue.

**Comment by johben** [comment]
I have the same problem or a question.

**Comment by lucaderi** [comment]
The hyperlinks are gone for hosts that are not active (i.e. for which the URL will direct you at a "no host" page). The top sender/receivers work for me, but you are right that the AS section does not contain hyperlinks. @simonemainardi Simone can you please fix this?

**Comment by timdoes69** [comment]
What does the Hostname 'Other' mean? i.e. not available, no longer active, spoofed...

**Comment by lucaderi** [comment]
Any other host/AS... that is not listed in the table section where it appears

**Comment by simonemainardi** [comment]
Links to AS have been added back. Keep in mind that you will see 'no results found' in the linked page if no presently active host belongs to the reported AS. Packages will be built overnight.

As per the 'Other' issue, I cannot reproduce as well.
