### ISSUE TITLE
Blog notification date format

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3651]
Date format 
![image](https://user-images.githubusercontent.com/3397663/77736616-d0030a00-700c-11ea-9be4-4521b710b81b.png)

Date format is awkward and not human-friendly. See for example the +00:00.

Must the same function and format used to populate datetimepicker forms.

**Comment by simonemainardi** [comment]
work and make it consistent also with https://github.com/ntop/ntopng/issues/3651
the format must be the very same all across the application

**Comment by gabryon99** [comment]
<img width="442" alt="Screenshot 2020-03-27 at 15 26 43" src="https://user-images.githubusercontent.com/14114916/77766013-5f291580-703f-11ea-8d95-779507e67e22.png">

Ok, now I use the locale standard format. Is this ok?

**Comment by simonemainardi** [comment]
ok

**Comment by gabryon99** [comment]
fixed in https://github.com/ntop/ntopng/commit/02fe8513e13de64ac964bbd19d2121236569ce09
