### ISSUE TITLE
Blog notification badge

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3652]
Red badges as those are used in ntopng to represent danger, issues, and errors.

Must change the red 'New' badge to something else.

![image](https://user-images.githubusercontent.com/3397663/77736878-443dad80-700d-11ea-8f41-8e1539c1b4a8.png)

**Comment by gabryon99** [comment]
I changed the red color to the primary color (in bootstrap the default is blue)

**Comment by gabryon99** [comment]
Fixed in https://github.com/ntop/ntopng/commit/02fe8513e13de64ac964bbd19d2121236569ce09.
