### ISSUE TITLE
Ntop restarts after approx. 5min on raspberry pi2

### ISSUE THREAD

**Issue by klemenska** [ntop/ntopng#3654]
Hello,

Version: ntopng Professional Edition v.4.1.200324
Arch: ARMhf

Issue:
Ntop restarts after approx. 5min.

Data:
Monitoing just local interface on an raspberry pi2.

log:
Mar 25 20:22:05 rpi2 ntopng[9705]: 25/Mar/2020 20:22:05 [NetworkInterface.cpp:2344] Started packet polling on interface lo [id: 2]...
Mar 25 20:25:03 rpi2 ntopng[9705]: corrupted size vs. prev_size
Mar 25 20:25:04 rpi2 systemd[1]: ntopng.service: Main process exited, code=killed, status=6/ABRT
Mar 25 20:25:04 rpi2 systemd[1]: ntopng.service: Failed with result 'signal'.
Mar 25 20:25:09 rpi2 systemd[1]: ntopng.service: Service RestartSec=5s expired, scheduling restart.
Mar 25 20:25:09 rpi2 systemd[1]: ntopng.service: Scheduled restart job, restart counter is at 142.
Mar 25 20:25:09 rpi2 systemd[1]: Stopped ntopng high-speed web-based traffic monitoring and analysis tool.
Mar 25 20:25:09 rpi2 systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
Mar 25 20:25:09 rpi2 systemd[1]: Started ntopng high-speed web-based traffic monitoring and analysis tool.
Mar 25 20:25:09 rpi2 ntopng[10227]: 25/Mar/2020 20:25:09 [Ntop.cpp:2219] Setting local networks to 127.0.0.0/8

top:
top - 00:23:04 up 15:39, 1 user, load average: 3.70, 3.36, 3.72
Tasks: 93 total, 1 running, 92 sleeping, 0 stopped, 0 zombie
%Cpu(s): 82.8 us, 11.7 sy, 0.0 ni, 4.6 id, 0.0 wa, 0.0 hi, 0.8 si, 0.0 st
MiB Mem : 924.1 total, 61.5 free, 530.6 used, 332.0 buff/cache
MiB Swap: 0.0 total, 0.0 free, 0.0 used. 363.3 avail Mem

PID USER PR NI VIRT RES SHR S %CPU %MEM TIME+ COMMAND
3022 ntopng 20 0 819476 454748 22664 S 285.1 48.1 10:07.18 ntopng
338 redis 20 0 30968 3448 2028 S 7.1 0.4 11:22.83 redis-server
1 root 20 0 30932 6748 5072 S 2.9 0.7 38:43.12 systemd
10 root 20 0 0 0 0 I 1.3 0.0 5:26.33 rcu_sched
3247 root 20 0 4812 2220 1688 R 1.3 0.2 0:00.28 top
167 root 20 0 29516 5756 4876 S 0.6 0.6 0:54.16 systemd-journal
6345 nprobe 20 0 61820 12476 8428 S 0.6 1.3 1:12.46 nprobe

Looks like the hardware is too busy.

Is the reason just because of the low specs of the hardware?

Are their some tweak setings to overcome the issue?

Regards,
Klemens

**Comment by klemenska** [comment]
Hello,

**Comment by klemenska** [comment]
Hello,

without any change ntop is now running for max. 18 h. why it is restarting?

regards,
Klemens

**Comment by lucaderi** [comment]
Works for us
