### ISSUE TITLE
Add the ability to show the active flows between two hosts

### ISSUE THREAD

**Issue by peer-m** [ntop/ntopng#3656]
Please reactivate in the ntopng community version the former feature to easily inspect the active traffic between two hosts from the top flow talkers diagram by double click on any bar (as described in Doc 2.1 Dashboard).

**Comment by emanuele-f** [comment]
For reference, the double click community feature was removed in 1dba3343e3a8dd2a403bf4425663a0c7f52582c9  as the page was broken due to api changes.

**Comment by bardal** [comment]
The tooltip is still encouraging you to double click - confused new user.

**Comment by simonemainardi** [comment]
Doc and tooltip are now updated. "Peers" now available also in community to inspect the top talkers of a give host. Example

![image](https://user-images.githubusercontent.com/3397663/130794706-3f8f8518-4802-4535-8f50-d00a839e19d0.png)
