### ISSUE TITLE
Possible problems with internet explorer

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3658]
A user reported the following problems:

![2020-03-27_16-23](https://user-images.githubusercontent.com/5488003/77771696-ed50cc00-703e-11ea-8115-edd5018e4419.png)

IE 11.1039.17763.0 Update 11.0.175

**Comment by simonemainardi** [comment]
Internet Explorer is End of Life, we not going to support it further. Even Microsoft recommends using Edge

> Microsoft recommends using the new Microsoft Edge as your default browser. 

Source: https://support.microsoft.com/en-us/help/17454/lifecycle-faq-internet-explorer-and-edge
