### ISSUE TITLE
High CPU when accessing ntopng GUI flows section in RPi3

### ISSUE THREAD

**Issue by orestis46** [ntop/ntopng#3660]
Im having high CPU (>95%) running ntopng version v.3.9.200313 in a Raspberry Pi 3 running Stretch 9.11 with LInux kernel 4.19.66-v7+ for my LAN environment, under the following condition:

 As soon as im opening a browser from anywhere in my LAN network to reach the GUI of ntopng and check the active flows section, CPU goes high and load rises:

top - **19:15:40** up  9:14,  5 users,  **load average: 11.54, 9.80, 5.27**
Threads:  38 total,   6 running,  32 sleeping,   0 stopped,   0 zombie
%Cpu0  : **92.7 us**,  4.6 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  2.6 si,  0.0 st
%Cpu1  : **99.3 us**,  0.7 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  : **95.7 us**,  4.3 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  : **98.3 us**,  1.7 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :   948304 total,   102392 free,   586600 used,   259312 buff/cache
KiB Swap:  2097148 total,  2051324 free,    45824 used.   275496 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                          
18979 ntopng    20   0  589680 200584  27092 **R** 50.5 21.2   3:41.21 **ntopng**                                                                           
18980 ntopng    20   0  589680 200584  27092 **R** 45.5 21.2   3:44.37 **ntopng**                                                                           
18983 ntopng    20   0  589680 200584  27092 **R** 45.5 21.2   3:40.81 **ntopng**                                                                           
18981 ntopng    20   0  589680 200584  27092 **R** 45.2 21.2   3:46.82 **ntopng**                                                                           
18982 ntopng    20   0  589680 200584  27092 **R** 41.9 21.2   3:29.03 **ntopng**                                                                           
19019 ntopng    20   0  589680 200584  27092 R 40.9 21.2   4:35.64 minute.lua                                                                       
19021 ntopng    20   0  589680 200584  27092 S  1.7 21.2   0:21.27 second.lua                                                                       
19030 ntopng    20   0  589680 200584  27092 S  0.7 21.2   0:07.83 inline ifid 1                                                                    
19018 ntopng    20   0  589680 200584  27092 S  0.3 21.2   0:05.55 housekeeping.lu                                                                  
19031 ntopng    20   0  589680 200584  27092 S  0.3 21.2   0:04.51 inline ifid 2                                                                    
19032 ntopng    20   0  589680 200584  27092 S  0.3 21.2   0:04.24 inline ifid 3                                                                    
19033 ntopng    20   0  589680 200584  27092 S  0.3 21.2   0:06.10 inline ifid 4                                                                    
18907 ntopng    20   0  589680 200584  27092 S  0.0 21.2   0:04.36 ntopng                                                                           
18978 ntopng    20   0  589680 200584  27092 S  0.0 21.2   0:00.58 ntopng                                                                           
18984 ntopng    20   0  589680 200584  27092 S  0.0 21.2   0:00.04 resolveLoop                                                                      
19004 ntopng    20   0  589680 200584  27092 S  0.0 21.2   0:08.36 ht_state_update                                                                  
19005 ntopng    20   0  589680 200584  27092 S  0.0 21.2   0:08.35 ht_state_update                                                                  
19006 ntopng    20   0  589680 200584  27092 S  0.0 21.2   0:08.45 ht_state_update                                                                  
19007 ntopng    20   0  589680 200584  27092 S  0.0 21.2   0:08.68 ht_state_update                                                                  
19008 ntopng    20   0  589680 200584  27092 S  0.0 21.2   0:01.77 stats_update.lu                                                                  
19009 ntopng    20   0  589680 200584  27092 S  0.0 21.2   0:01.65 stats_update.lu                                                                  
19010 ntopng    20   0  589680 200584  27092 S  0.0 21.2   0:01.64 stats_update.lu                                                                  
19011 ntopng    20   0  589680 200584  27092 S  0.0 21.2   0:01.75 stats_update.lu                                                                  
19012 ntopng    20   0  589680 200584  27092 S  0.0 21.2   0:20.49 5min.lua                                                                         
19013 ntopng    20   0  589680 200584  27092 S  0.0 21.2   0:22.96 5min.lua                                                                         
19014 ntopng    20   0  589680 200584  27092 S  0.0 21.2   0:19.20 5min.lua        

If i leave the GUI with the section of active flows open, then the output of top remains above >95% and i can see that the CPU load (according to top) continues to rise.

After closing the active flows section in ntopng GUI the CPU usage drops:

top - **19:25:47** up  9:24,  5 users,  **load average: 1.21, 3.24, 4.21**
Threads:  38 total,   0 running,  38 sleeping,   0 stopped,   0 zombie
%Cpu0  :  **1.4 us**,  2.8 sy,  0.0 ni, 29.5 id, 65.3 wa,  0.0 hi,  1.0 si,  0.0 st
%Cpu1  :  **2.7 us**,  0.3 sy,  0.0 ni, 69.2 id, 27.8 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  :  **2.0 us**,  1.3 sy,  0.0 ni, 96.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  :  **1.3 us**,  0.7 sy,  0.0 ni, 62.3 id, 35.7 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :   948304 total,   157192 free,   583212 used,   207900 buff/cache
KiB Swap:  2097148 total,  2050044 free,    47104 used.   278608 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                          
19021 ntopng    20   0  587632 199288  27212 S  1.7 21.0   0:29.89 second.lua                                                                       
19004 ntopng    20   0  587632 199288  27212 S  1.0 21.0   0:11.19 ht_state_update                                                                  
19007 ntopng    20   0  587632 199288  27212 S  0.7 21.0   0:11.64 ht_state_update                                                                  
19011 ntopng    20   0  587632 199288  27212 S  0.7 21.0   0:02.33 stats_update.lu                                                                  
19005 ntopng    20   0  587632 199288  27212 S  0.3 21.0   0:11.11 ht_state_update                                                                  
19008 ntopng    20   0  587632 199288  27212 S  0.3 21.0   0:02.43 stats_update.lu                                                                  
19009 ntopng    20   0  587632 199288  27212 S  0.3 21.0   0:02.19 stats_update.lu                                                                  
19010 ntopng    20   0  587632 199288  27212 S  0.3 21.0   0:02.23 stats_update.lu                                                                  
19017 ntopng    20   0  587632 199288  27212 S  0.3 21.0   0:06.78 discover.lua                                                                     
19030 ntopng    20   0  587632 199288  27212 S  0.3 21.0   0:11.62 inline ifid 1                                                                    
19032 ntopng    20   0  587632 199288  27212 S  0.3 21.0   0:05.80 inline ifid 3                                                                    
19033 ntopng    20   0  587632 199288  27212 S  0.3 21.0   0:08.38 inline ifid 4                                                                    
18907 ntopng    20   0  587632 199288  27212 S  0.0 21.0   0:04.36 ntopng                                                                           
18978 ntopng    20   0  587632 199288  27212 S  0.0 21.0   0:00.78 ntopng                                                                           
18979 ntopng    20   0  587632 199288  27212 S  0.0 21.0   4:52.23 ntopng                                                                           
18980 ntopng    20   0  587632 199288  27212 S  0.0 21.0   4:58.62 ntopng                                                                           
18981 ntopng    20   0  587632 199288  27212 S  0.0 21.0   4:59.71 ntopng                                                                           
18982 ntopng    20   0  587632 199288  27212 S  0.0 21.0   4:38.97 ntopng                                                                           
18983 ntopng    20   0  587632 199288  27212 S  0.0 21.0   4:54.07 ntopng                                                                           
18984 ntopng    20   0  587632 199288  27212 S  0.0 21.0   0:00.04 resolveLoop                                                                      
19006 ntopng    20   0  587632 199288  27212 S  0.0 21.0   0:11.39 ht_state_update                                                                  
19012 ntopng    20   0  587632 199288  27212 S  0.0 21.0   0:25.97 5min.lua               
 
When minute.lua and 5min.lua are running they cause some CPU spikes but they drop after a few seconds (nothing like ntopng that keeps running and hogs the cpu cores).

Is this a normal and expected behaviour  ?

**Comment by orestis46** [comment]
Just upgraded to version v.4.1.200330, but the behaviour is exactly the same (ntopng keeps running and hogging the cpu).

(Active flows open in GUI):

top - **07:00:35** up 3 days, 19:59,  5 users,  **load average: 10.14, 5.22, 2.82**
Threads:  41 total,   6 running,  35 sleeping,   0 stopped,   0 zombie
**%Cpu0  : 95.7 us**,  3.0 sy,  0.0 ni,  0.7 id,  0.0 wa,  0.0 hi,  0.7 si,  0.0 st
**%Cpu1  : 95.0 us**,  4.3 sy,  0.0 ni,  0.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
**%Cpu2  : 96.1 us**,  3.6 sy,  0.0 ni,  0.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
**%Cpu3  : 97.7 us**,  2.0 sy,  0.0 ni,  0.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :   948304 total,   115940 free,   524652 used,   307712 buff/cache
KiB Swap:  2097148 total,  1921532 free,   175616 used.   311760 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                          
21645 ntopng    20   0  650228 231156  30720 **R** 62.3 24.4   1:50.66 **ntopng**                                                                           
21646 ntopng    20   0  650228 231156  30720 **R** 59.9 24.4   1:49.94 **ntopng**                                                                           
21644 ntopng    20   0  650228 231156  30720 **R** 58.3 24.4   1:52.26 **ntopng**                                                                           
21648 ntopng    20   0  650228 231156  30720 **R** 47.4 24.4   1:47.83 **ntopng**                                                                           
21691 ntopng    20   0  650228 231156  30720 R 47.0 24.4   1:10.04 minute.lua                                                                       
21647 ntopng    20   0  650228 231156  30720 **R** 43.0 24.4   1:37.11 **ntopng**                                                                           
21684 ntopng    20   0  650228 231156  30720 S 25.5 24.4   0:10.50 hourly.lua                                                                       
21683 ntopng    20   0  650228 231156  30720 S 17.9 24.4   0:10.28 hourly.lua                                                                       
21685 ntopng    20   0  650228 231156  30720 S 14.6 24.4   0:10.23 hourly.lua                                                                       
21686 ntopng    20   0  650228 231156  30720 S 12.9 24.4   0:10.00 hourly.lua                                                                       
21693 ntopng    20   0  650228 231156  30720 S  1.7 24.4   0:03.98 second.lua                                                                       
21702 ntopng    20   0  650228 231156  30720 S  0.7 24.4   0:01.63 inline ifid 1                                                                    
21676 ntopng    20   0  650228 231156  30720 S  0.3 24.4   0:02.41 ht_state_update                                                                  
21677 ntopng    20   0  650228 231156  30720 S  0.3 24.4   0:01.34 ht_state_update                                                                  
21681 ntopng    20   0  650228 231156  30720 S  0.3 24.4   0:00.27 stats_update.lu                                                                  
21689 ntopng    20   0  650228 231156  30720 S  0.3 24.4   0:01.24 discover.lua                                                                     
21698 ntopng    20   0  650228 231156  30720 S  0.3 24.4   0:01.83 timeseries.lua                                                                   
21703 ntopng    20   0  650228 231156  30720 S  0.3 24.4   0:00.89 inline ifid 2                                                                    
21704 ntopng    20   0  650228 231156  30720 S  0.3 24.4   0:00.81 inline ifid 3                                                                    
21705 ntopng    20   0  650228 231156  30720 S  0.3 24.4   0:01.20 inline ifid 4                                                                    
21527 ntopng    20   0  650228 231156  30720 S  0.0 24.4   0:04.53 ntopng                                                                           
21643 ntopng    20   0  650228 231156  30720 S  0.0 24.4   0:00.13 ntopng                                                                           
21649 ntopng    20   0  650228 231156  30720 S  0.0 24.4   0:00.02 resolveLoop                                                                      
21673 ntopng    20   0  650228 231156  30720 S  0.0 24.4   0:02.35 ht_state_update                                                                  
21674 ntopng    20   0  650228 231156  30720 S  0.0 24.4   0:01.26 ht_state_update                                                                  
21675 ntopng    20   0  650228 231156  30720 S  0.0 24.4   0:02.41 ht_state_update                                                                  

(Closing Active flows GUI):

top - **07:03:00** up 3 days, 20:02,  5 users,  **load average: 4.71, 5.39, 3.27**
Threads:  41 total,   0 running,  41 sleeping,   0 stopped,   0 zombie
**%Cpu0  :  1.7 us**,  0.7 sy,  0.0 ni, 97.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
**%Cpu1  :  0.3 us**,  0.7 sy,  0.0 ni, 95.3 id,  3.7 wa,  0.0 hi,  0.0 si,  0.0 st
**%Cpu2  :  1.3 us**,  0.3 sy,  0.0 ni, 98.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
**%Cpu3  :  1.7 us**,  0.3 sy,  0.0 ni, 93.7 id,  4.3 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :   948304 total,   100456 free,   538756 used,   309092 buff/cache
KiB Swap:  2097148 total,  1921532 free,   175616 used.   297672 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                          
21693 ntopng    20   0  647156 229224  30720 S  1.3 24.2   0:05.89 second.lua                                                                       
21677 ntopng    20   0  647156 229224  30720 S  0.3 24.2   0:01.49 ht_state_update                                                                  
21679 ntopng    20   0  647156 229224  30720 S  0.3 24.2   0:00.42 stats_update.lu                                                                  
21682 ntopng    20   0  647156 229224  30720 S  0.3 24.2   0:00.32 stats_update.lu                                                                  
21689 ntopng    20   0  647156 229224  30720 S  0.3 24.2   0:01.41 discover.lua                                                                     
21698 ntopng    20   0  647156 229224  30720 S  0.3 24.2   0:02.19 timeseries.lua                                                                   
21702 ntopng    20   0  647156 229224  30720 S  0.3 24.2   0:02.33 inline ifid 1                                                                    
21703 ntopng    20   0  647156 229224  30720 S  0.3 24.2   0:01.26 inline ifid 2                                                                    
21704 ntopng    20   0  647156 229224  30720 S  0.3 24.2   0:01.18 inline ifid 3                                                                    
21705 ntopng    20   0  647156 229224  30720 S  0.3 24.2   0:01.69 inline ifid 4                                                                    
21527 ntopng    20   0  647156 229224  30720 S  0.0 24.2   0:04.53 ntopng                                                                           
21643 ntopng    20   0  647156 229224  30720 S  0.0 24.2   0:00.20 ntopng                                                                           
21644 ntopng    20   0  647156 229224  30720 S  0.0 24.2   3:10.49 ntopng                                                                           
21645 ntopng    20   0  647156 229224  30720 S  0.0 24.2   3:08.74 ntopng                                                                           
21646 ntopng    20   0  647156 229224  30720 S  0.0 24.2   3:05.71 ntopng                                                                           
21647 ntopng    20   0  647156 229224  30720 S  0.0 24.2   2:42.67 ntopng                                                                           
21648 ntopng    20   0  647156 229224  30720 S  0.0 24.2   3:07.54 ntopng                                                                           
21649 ntopng    20   0  647156 229224  30720 S  0.0 24.2   0:00.02 resolveLoop                                                                      
21673 ntopng    20   0  647156 229224  30720 S  0.0 24.2   0:02.47 ht_state_update                                                                  
21674 ntopng    20   0  647156 229224  30720 S  0.0 24.2   0:01.38 ht_state_update                                                                  
21675 ntopng    20   0  647156 229224  30720 S  0.0 24.2   0:02.52 ht_state_update                                                                  
21676 ntopng    20   0  647156 229224  30720 S  0.0 24.2   0:02.53 ht_state_update                                                                  
21678 ntopng    20   0  647156 229224  30720 S  0.0 24.2   0:00.40 stats_update.lu                                                                  
21680 ntopng    20   0  647156 229224  30720 S  0.0 24.2   0:00.30 stats_update.lu                                                                  
21681 ntopng    20   0  647156 229224  30720 S  0.0 24.2   0:00.39 stats_update.lu                                                                  
21683 ntopng    20   0  647156 229224  30720 S  0.0 24.2   0:10.28 hourly.lua            

Tested also on a PC running Kubuntu 18.04 LTS with latest ntopng version (4.x) and the issue is NOT present there (occurs only in arm as it seems).

**Comment by emanuele-f** [comment]
The problem is probably related to the fact that each row in the table is updated separately in his own ajax request.
