### ISSUE TITLE
4.0.0? tag/releases?

### ISSUE THREAD

**Issue by ahkok** [ntop/ntopng#3661]
According to my running ntopng, I should update to 4.0.0, but this repository has no 4.0.0 tags, nor is there a release for 4.0.0. I can see a branch, but it is anything but stable, with 50+ commits in 2 days.

Maybe not advertise new versions to running clients that are not obtainable yet. Sites like `repology` show that nobody has 4.0.0 packaged yet.

Either that, or please push a 4.0.0 tag and release a dist tarball, thanks!

**Comment by tuarego** [comment]
http://packages.ntop.org/

**Comment by ahkok** [comment]
I am packaging for ClearLinux. That link has zero value to me. It doesn't list source releases.

**Comment by lucaderi** [comment]
I have waited a few days for cutting the release s we have consolidated a few issues. I have now cut the release https://github.com/ntop/ntopng/releases/tag/4.0 that I think you should use for your work. Ww will periodically push fixes to the 4.0-stable release whenever we find major issues to be fixed.

**Comment by ahkok** [comment]
Thanks, it's not happy either building against ndpi 3.0 or 3.2, though. Several invalid conversions in `src/Flow.cpp` ...
