### ISSUE TITLE
Plugins not loaded when a directory is specified with -d

### ISSUE THREAD

**Issue by jacotec** [ntop/ntopng#3663]
After upgrading to 4.0.200327 (Enterprise Edition) I'm periodically getting multiple errors:

`28/Mar/2020 10:31:44 [system_stats.lua:109] [ts_utils_core.lua:692] ERROR: Schema not found: process:num_alerts
28/Mar/2020 10:31:44 [system_stats.lua:104] [ts_utils_core.lua:692] ERROR: Schema not found: process:resident_memory
28/Mar/2020 10:31:42 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
28/Mar/2020 10:31:39 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
28/Mar/2020 10:31:36 [LuaEngine.cpp:12141] WARNING: Script failure  `

**Comment by jacotec** [comment]
In "Flows" I'm just getting the error:

SyntaxError: JSON Parse error: Unexpected identifier "HTTP"

It seems that update has completely screwed my installation ...

**Comment by jacotec** [comment]
Restored a 3.8 backup and did the upgrade again, just in case something went wrong - exactly the same issue.

There was a 4.0 version before 200327, which was working fine. 200327 definitely introduced that bug, all flows displays are not working due to the issue. JSON parse error.

Is there any way to go back to that 4.0 version before 200327? I can't find it and I really want to be able to check my flows data 🙁

**Comment by emanuele-f** [comment]
Please post the full ntopng log since startup. You can easily do this with:

1. `sudo systemctl stop ntopng`
2. `sudo ntopng /etc/ntopng/ntopng.conf`

**Comment by jacotec** [comment]
@emanuele-f 
Here's the log. Started as mentioned in your post, accessed the flow page (This time: "SyntaxError: Unexpected token H in JSON at position 0"), then shut down again.

License and public IP anonymized.

Let me know if I should debug more!

> ntopng /etc/ntopng/ntopng.conf
30/Mar/2020 09:20:28 [Prefs.cpp:939] ERROR: -S deprecated, sticky hosts no longer supported. Configure remote and local hosts idle timeouts from the preferences.
30/Mar/2020 09:20:28 [Ntop.cpp:2226] Setting local networks to 10.0.0.0/12,10.50.0.0/16,10.32.0.0/16,10.100.0.0/24,**.**.**.**/32
30/Mar/2020 09:20:28 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
30/Mar/2020 09:20:28 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
30/Mar/2020 09:20:28 [NtopPro.cpp:308] [LICENSE] Reading license from /etc/ntopng.license
30/Mar/2020 09:20:28 [NtopPro.cpp:188] Contacting licensing server. Please hold on...
30/Mar/2020 09:20:29 [NtopPro.cpp:385] [LICENSE] /etc/ntopng.license: found valid Enterprise license
30/Mar/2020 09:20:29 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.7.6.0 interface ens192...
30/Mar/2020 09:20:29 [Ntop.cpp:2331] Registered interface ens192 [id: 3]
30/Mar/2020 09:20:30 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.7.6.0 interface ens224...
30/Mar/2020 09:20:30 [Ntop.cpp:2331] Registered interface ens224 [id: 4]
30/Mar/2020 09:20:30 [Ntop.cpp:2331] Registered interface tcp://127.0.0.1:5556 [id: 5]
30/Mar/2020 09:20:30 [main.cpp:311] PID stored in file /var/run/ntopng.pid
30/Mar/2020 09:20:30 [Geolocation.cpp:183] Loaded database GeoLite2-ASN.mmdb [/var/lib/GeoIP/GeoLite2-ASN.mmdb][ip_version: 6]
30/Mar/2020 09:20:30 [Geolocation.cpp:183] Loaded database GeoLite2-City.mmdb [/var/lib/GeoIP/GeoLite2-City.mmdb][ip_version: 6]
30/Mar/2020 09:20:31 [HTTPserver.cpp:1331] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
30/Mar/2020 09:20:31 [HTTPserver.cpp:1334] HTTP server listening on 3000
30/Mar/2020 09:20:31 [HTTPserver.cpp:1340] HTTPS server listening on 3001
30/Mar/2020 09:20:31 [Utils.cpp:734] User changed to ntopng
30/Mar/2020 09:20:31 [MySQLDB.cpp:824] Attempting to connect to MySQL for interface ens224...
30/Mar/2020 09:20:31 [MySQLDB.cpp:850] Successfully connected to MySQL [ntopng@localhost:3306] for interface ens224
30/Mar/2020 09:20:31 [MySQLDB.cpp:824] Attempting to connect to MySQL for interface ens224...
30/Mar/2020 09:20:31 [MySQLDB.cpp:850] Successfully connected to MySQL [ntopng@localhost:3306] for interface ens224
30/Mar/2020 09:20:31 [MySQLDB.cpp:744] Disconnected from MySQL for interface ens224...
30/Mar/2020 09:20:31 [MySQLDB.cpp:824] Attempting to connect to MySQL for interface ens224...
30/Mar/2020 09:20:31 [MySQLDB.cpp:850] Successfully connected to MySQL [ntopng@localhost:3306] for interface ens224
30/Mar/2020 09:20:31 [MySQLDB.cpp:824] Attempting to connect to MySQL for interface tcp://127.0.0.1:5556...
30/Mar/2020 09:20:31 [BatchedMySQLDB.cpp:245] Executing queryLoop()
30/Mar/2020 09:20:31 [MySQLDB.cpp:824] Attempting to connect to MySQL for interface ens224...
30/Mar/2020 09:20:31 [MySQLDB.cpp:850] Successfully connected to MySQL [ntopng@localhost:3306] for interface tcp://127.0.0.1:5556
30/Mar/2020 09:20:31 [MySQLDB.cpp:824] Attempting to connect to MySQL for interface tcp://127.0.0.1:5556...
30/Mar/2020 09:20:31 [MySQLDB.cpp:850] Successfully connected to MySQL [ntopng@localhost:3306] for interface ens224
30/Mar/2020 09:20:31 [MySQLDB.cpp:850] Successfully connected to MySQL [ntopng@localhost:3306] for interface tcp://127.0.0.1:5556
30/Mar/2020 09:20:31 [main.cpp:383] Working directory: /storage/ntopng
30/Mar/2020 09:20:31 [BatchedMySQLDB.cpp:245] Executing queryLoop()
30/Mar/2020 09:20:31 [MySQLDB.cpp:824] Attempting to connect to MySQL for interface tcp://127.0.0.1:5556...
30/Mar/2020 09:20:31 [main.cpp:385] Scripts/HTML pages directory: /usr/share/ntopng
30/Mar/2020 09:20:31 [Ntop.cpp:437] Welcome to ntopng x86_64 v.4.0.200327 - (C) 1998-20 ntop.org
30/Mar/2020 09:20:31 [Ntop.cpp:447] Built on Ubuntu 18.04.4 LTS
30/Mar/2020 09:20:31 [MySQLDB.cpp:850] Successfully connected to MySQL [ntopng@localhost:3306] for interface tcp://127.0.0.1:5556
30/Mar/2020 09:20:31 [NtopPro.cpp:656] [LICENSE] System Id:	6892A42076056201
30/Mar/2020 09:20:31 [NtopPro.cpp:657] [LICENSE] Edition:	Enterprise
30/Mar/2020 09:20:31 [NtopPro.cpp:658] [LICENSE] License Type:	Permanent License
30/Mar/2020 09:20:31 [NtopPro.cpp:667] [LICENSE] License:	***
30/Mar/2020 09:20:31 [NtopPro.cpp:668] [LICENSE]         	***
30/Mar/2020 09:20:31 [NtopPro.cpp:668] [LICENSE]         	***
30/Mar/2020 09:20:31 [NtopPro.cpp:668] [LICENSE]         	***
30/Mar/2020 09:20:31 [NtopPro.cpp:668] [LICENSE]         	***
30/Mar/2020 09:20:31 [NtopPro.cpp:672] [LICENSE] License Hash:	***
30/Mar/2020 09:20:31 [NtopPro.cpp:682] [LICENSE] Maintenance:	Until Fri Jul 31 17:01:36 2020 [123 days left]
30/Mar/2020 09:20:31 [Ntop.cpp:829] Adding 10.99.99.10/32 as IPv4 interface address for ens192
30/Mar/2020 09:20:31 [Ntop.cpp:838] Adding 10.99.99.10/32 as IPv4 local network for ens192
30/Mar/2020 09:20:31 [Ntop.cpp:829] Adding 10.99.99.50/32 as IPv4 interface address for ens224
30/Mar/2020 09:20:31 [Ntop.cpp:838] Adding 10.99.99.50/32 as IPv4 local network for ens224
30/Mar/2020 09:20:31 [Ntop.cpp:860] Adding fe80::250:56ff:fe8f:e524/128 as IPv6 interface address for ens192
30/Mar/2020 09:20:31 [Ntop.cpp:870] Adding fe80::250:56ff:fe8f:e524/64 as IPv6 local network for ens192
30/Mar/2020 09:20:31 [Ntop.cpp:860] Adding fe80::250:56ff:fe8f:430e/128 as IPv6 interface address for ens224
30/Mar/2020 09:20:31 [Ntop.cpp:870] Adding fe80::250:56ff:fe8f:430e/64 as IPv6 local network for ens224
30/Mar/2020 09:20:31 [PeriodicActivities.cpp:104] Started periodic activities loop...
30/Mar/2020 09:20:37 [PeriodicActivities.cpp:164] Each periodic activity script will use 3 threads
30/Mar/2020 09:20:37 [NetworkInterface.cpp:2343] Started packet polling on interface ens192 [id: 3]...
30/Mar/2020 09:20:37 [NetworkInterface.cpp:2332] Setting affinity of interface ens224 to core 1
30/Mar/2020 09:20:37 [NetworkInterface.cpp:2343] Started packet polling on interface ens224 [id: 4]...
30/Mar/2020 09:20:37 [NetworkInterface.cpp:2332] Setting affinity of interface tcp://127.0.0.1:5556 to core 2
30/Mar/2020 09:20:37 [NetworkInterface.cpp:2343] Started packet polling on interface tcp://127.0.0.1:5556 [id: 5]...
30/Mar/2020 09:20:37 [ZMQCollectorInterface.cpp:255] Collecting flows on tcp://127.0.0.1:5556
30/Mar/2020 09:20:39 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:20:42 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:20:45 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:20:48 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:20:51 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:20:54 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:20:57 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:21:00 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:21:03 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:21:06 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:21:09 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:21:12 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:21:15 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:21:18 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:21:21 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:21:24 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:21:27 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:21:30 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:21:33 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:21:36 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:21:39 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:21:42 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:21:44 [LuaEngine.cpp:12646] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flows_data.lua][/usr/share/ntopng/scripts/lua/get_flows_data.lua:247: attempt to index a nil value (field 'status_normal')]
30/Mar/2020 09:21:45 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:21:48 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:21:51 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:21:54 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
30/Mar/2020 09:21:57 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
^C30/Mar/2020 09:21:59 [main.cpp:50] Shutting down...
30/Mar/2020 09:21:59 [PF_RINGInterface.cpp:244] Terminated packet polling for ens192
30/Mar/2020 09:21:59 [PF_RINGInterface.cpp:244] Terminated packet polling for ens224
30/Mar/2020 09:22:00 [Ntop.cpp:2424] Terminating periodic activities
30/Mar/2020 09:22:00 [Ntop.cpp:2430] Executing shutdown script
 string stack traceback:
	/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:100: in function 'alertType'
	/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:2465: in upvalue 'notify_ntopng_status'
	/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:2486: in function 'notify_ntopng_stop'
	/usr/share/ntopng/scripts/callbacks/system/shutdown.lua:22: in main chunk
30/Mar/2020 09:22:00 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/shutdown.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:103: attempt to index a nil value (field '?')]
30/Mar/2020 09:22:01 [ProtoStats.cpp:35] [IPv4]  20.67 MB/50.14 K Packets
30/Mar/2020 09:22:01 [ProtoStats.cpp:35] [IPv6]  15.23 KB/38.00 Packets
30/Mar/2020 09:22:01 [ProtoStats.cpp:35] [ARP]   177.37 KB/3.03 K Packets
30/Mar/2020 09:22:01 [ProtoStats.cpp:35] [MPLS]  0 B/0.00 Packets
30/Mar/2020 09:22:01 [ProtoStats.cpp:35] [Other] 5.76 KB/93.00 Packets
30/Mar/2020 09:22:01 [Ntop.cpp:2412] Polling shut down [interface: ens192]
30/Mar/2020 09:22:01 [ProtoStats.cpp:35] [IPv4]  530 B/5.00 Packets
30/Mar/2020 09:22:01 [ProtoStats.cpp:35] [IPv6]  0 B/0.00 Packets
30/Mar/2020 09:22:01 [ProtoStats.cpp:35] [ARP]   0 B/0.00 Packets
30/Mar/2020 09:22:01 [ProtoStats.cpp:35] [MPLS]  0 B/0.00 Packets
30/Mar/2020 09:22:01 [ProtoStats.cpp:35] [Other] 0 B/0.00 Packets
30/Mar/2020 09:22:01 [Ntop.cpp:2412] Polling shut down [interface: ens224]
30/Mar/2020 09:22:01 [ProtoStats.cpp:35] [IPv4]  1.70 MB/5.47 K Packets
30/Mar/2020 09:22:01 [ProtoStats.cpp:35] [IPv6]  144 B/1.00 Packets
30/Mar/2020 09:22:01 [ProtoStats.cpp:35] [ARP]   0 B/0.00 Packets
30/Mar/2020 09:22:01 [ProtoStats.cpp:35] [MPLS]  0 B/0.00 Packets
30/Mar/2020 09:22:01 [ProtoStats.cpp:35] [Other] 0 B/0.00 Packets
30/Mar/2020 09:22:01 [Ntop.cpp:2412] Polling shut down [interface: tcp://127.0.0.1:5556]
30/Mar/2020 09:22:01 [Ntop.cpp:2447] Deleted PID /var/run/ntopng.pid: [rc: -1][Permission denied]
30/Mar/2020 09:22:01 [HTTPserver.cpp:1357] HTTP server terminated
30/Mar/2020 09:22:01 [NetworkInterface.cpp:544] Flushing host contacts for interface ens192
30/Mar/2020 09:22:01 [NetworkInterface.cpp:2384] Cleanup interface ens192
30/Mar/2020 09:22:01 [NetworkInterface.cpp:544] Flushing host contacts for interface ens224
30/Mar/2020 09:22:01 [NetworkInterface.cpp:2384] Cleanup interface ens224
30/Mar/2020 09:22:01 [MySQLDB.cpp:744] Disconnected from MySQL for interface ens224...
30/Mar/2020 09:22:01 [MySQLDB.cpp:744] Disconnected from MySQL for interface ens224...
30/Mar/2020 09:22:01 [MySQLDB.cpp:744] Disconnected from MySQL for interface ens224...
30/Mar/2020 09:22:01 [NetworkInterface.cpp:544] Flushing host contacts for interface tcp://127.0.0.1:5556
30/Mar/2020 09:22:01 [NetworkInterface.cpp:2384] Cleanup interface tcp://127.0.0.1:5556
30/Mar/2020 09:22:02 [MySQLDB.cpp:744] Disconnected from MySQL for interface tcp://127.0.0.1:5556...
30/Mar/2020 09:22:02 [MySQLDB.cpp:744] Disconnected from MySQL for interface tcp://127.0.0.1:5556...
30/Mar/2020 09:22:02 [MySQLDB.cpp:744] Disconnected from MySQL for interface tcp://127.0.0.1:5556...
30/Mar/2020 09:22:02 [AddressResolution.cpp:63] Address resolution stats [223 resolved][368 failures]
root@ntopng:~#

**Comment by emanuele-f** [comment]
What is the output of `find /storage/ntopng/plugins0`?

**Comment by jacotec** [comment]
@emanuele-f 

> root@ntopng:~# find /storage/ntopng/plugins0
> find: ‘/storage/ntopng/plugins0’: No such file or directory
> 
> root@ntopng:~# ls -l /storage/ntopng/
> total 112
> drwx------ 3 ntopng ntopng  4096 Mar 28 19:39 0
> drwx------ 8 ntopng ntopng  4096 Aug  1  2019 1
> drwx------ 5 ntopng ntopng  4096 Mar 30 11:40 -1
> drwx------ 5 ntopng ntopng  4096 Aug  2  2019 10
> drwx------ 5 ntopng ntopng  4096 Mar 28 15:38 11
> drwx------ 5 ntopng ntopng  4096 Mar 28 15:38 12
> drwx------ 5 ntopng ntopng  4096 Aug  2  2019 13
> drwx------ 5 ntopng ntopng  4096 Aug  2  2019 14
> drwx------ 5 ntopng ntopng  4096 Aug  2  2019 15
> drwx------ 5 ntopng ntopng  4096 Aug  2  2019 16
> drwx------ 3 ntopng ntopng  4096 Mar 28 19:39 2
> drwx------ 8 ntopng ntopng  4096 Mar 30 11:40 3
> drwx------ 9 ntopng ntopng  4096 Mar 30 11:40 4
> drwx------ 9 ntopng ntopng  4096 Mar 30 11:40 5
> drwx------ 9 ntopng ntopng  4096 Aug  1  2019 6
> drwx------ 8 ntopng ntopng  4096 Aug  1  2019 7
> drwx------ 5 ntopng ntopng  4096 Aug  1  2019 8
> drwx------ 8 ntopng ntopng  4096 Aug  1  2019 9
> drwx------ 2 ntopng ntopng  4096 Mar 30 09:20 category_lists
> -rw------- 1 ntopng ntopng 34285 Mar 30 11:42 runtimeprefs.json
>

**Comment by emanuele-f** [comment]
What about `ls /storage/ntopng`?

**Comment by jacotec** [comment]
@emanuele-f  Already added above :)

**Comment by emanuele-f** [comment]
The new stable package will be available in one hour. Please update and let me know if this works for you

**Comment by jacotec** [comment]
Excellent, will do!

**Comment by jacotec** [comment]
@emanuele-f 
Version 4.0.200330 is online but unfortunately does not fix it. Same behavior as before, /storage/ntopng/plugins0 is still not there, same JSON error message in Flows.

**Comment by jacotec** [comment]
@emanuele-f 
Another new version 4.0.200330-9625, now it's fixed and my flows are back again! Thanks a ton for the express fix! :-)
