### ISSUE TITLE
ntopng-utils-manage-updates - create Warning  message through cron

### ISSUE THREAD

**Issue by HaleyACS** [ntop/ntopng#3664]
Getting this EMail from Cron recently.
```
Reading package lists...
W: Unable to read /etc/apt/-/ - DirectoryExists (2: No such file or directory)
W: Unable to read /etc/apt/sources.list.d/ntop.list - RealFileExists (2: No such file or directory)
```
Note - this comes from ntopng installation and automated updates I have in place.
And I didn't find that exact issue.

Target system is Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-88-generic x86_64) - Server edition stripped down to the bare minimum.

**Comment by emanuele-f** [comment]
Have you set up the ntopng repository as explained in http://packages.ntop.org ? Maybe you have manually installed the .deb file?

**Comment by HaleyACS** [comment]
I have installed ntopng as instructed. Over time, ntopng was updated (have an automatic updater in my system/firewall - script based) regularly. I didn't touch any of these functions.
So - that function has to have come in through one of the updates. 
I have that message showing up for around 2 to 3 weeks now. And I didn't touch my firewall bsae configuration since I installed it.

**Comment by cardigliano** [comment]
@HaleyACS, I guess you are using stable packages (v.4.0), I pushed a patch that should fix this, a new build will be available in ~1h, please update and let us know if you still get those warnings. Thank you.

**Comment by HaleyACS** [comment]
This are the exact versions that are installed currently.

- ii  apt-ntop-stable                       2.8-2                                           all          ntop stable apt package repository
- ii  ntopng                                4.0.200327-9598                                 amd64        Web-based traffic monitoring.
- ii  ntopng-data                           4.0.200327                                      all          Geolocation databases download helper for ntopng and other ntop software
- ii  pfring                                7.6.0-2888                                      amd64        PF_RING (http://www.ntop.org/pf_ring/) [7.6.0-stable:0e07b27c0d593174584de79e273470366a91d307]

On update - I figured out something that requires manual operation from my side.
As my firewall is tightly locked down, no code execution is possible from specific directories (/tmp included). Getting: 

`Can't exec "/tmp/ntopng.config.db8d6U": Permission denied at /usr/share/perl/5.26/IPC/Open3.pm line 178.
open2: exec of /tmp/ntopng.config.db8d6U configure 4.0.200327-9598 failed: Permission denied at /usr/share/perl5/Debconf/ConfModule.pm line 59.`

I'll update my update routine. But can you tell me what the code does?

**Comment by cardigliano** [comment]
Please note that you should update to ntopng 4.0.200330-9617 to get the updates fix.
As of the errors you reported, it seems the package is temporary using /tmp to handle configuration files changes, it should be safe to allow that

**Comment by HaleyACS** [comment]
> As of the errors you reported, it seems the package is temporary using /tmp to handle configuration files changes, it should be safe to allow that
Not on a secured system connected to the internet, no. I can disable this temporarily. But a configuration file change should not be allowed (as in this case) during an upgrade process without the user/admin knowing it. And in my case, the intended outcome (me seeing this) happened.

**Comment by HaleyACS** [comment]
OK. Works. You can close that one.
Question however is: Can I disable that functionality?
My system does a nightly upgrade anyway - this is a double-tap in that sense that it will go through the upgrade process twice, and yours will not have the /tmp reset temporarily on "exec" mode.

**Comment by Raptime** [comment]
> Question however is: Can I disable that functionality?
> My system does a nightly upgrade anyway - this is a double-tap in that sense that it will go through the upgrade process twice, and yours will not have the /tmp reset temporarily on "exec" mode.

Same here, I ended up deleting the file /etc/cron.d/ntopng

**Comment by cardigliano** [comment]
Automatic Updates can be disabled from Settings -> Preferences -> Updates (they shoud be disabled by default)

**Comment by HaleyACS** [comment]
That is not the case.
Checking, it is disabled, yet it is doing the updates. See below for the configuration.
![ntopng_update_settings](https://user-images.githubusercontent.com/12997932/79785919-f2a2ed00-8344-11ea-8c27-47eaa1eb93c0.png)
