### ISSUE TITLE
License Menu Entry

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#3665]
Add a section on the sidebar regarding license activation and version number. Divide it from the help section because it isn't intuitive as of now

**Comment by simonemainardi** [comment]
Applying a valid license doesn't cause the warning message to disappear fro the header

![image](https://user-images.githubusercontent.com/3397663/100906232-3f4cca00-34c9-11eb-943a-dadd9872af7c.png)

When the license is stored to file, the full base-64encoded license key should be shown in the UI not this

![image](https://user-images.githubusercontent.com/3397663/100906519-8d61cd80-34c9-11eb-8e68-db3ba1714be9.png)

**Comment by simonemainardi** [comment]
"license expires in " header does not refresh (footer refreshed instead)

![image](https://user-images.githubusercontent.com/3397663/100907951-36f58e80-34cb-11eb-80dc-8aefd4e0fe2a.png)

**Comment by simonemainardi** [comment]
The link which brings to the shop no longer works

![image](https://user-images.githubusercontent.com/3397663/100908680-124de680-34cc-11eb-873c-12bcf2a5465a.png)

**Comment by lucaderi** [comment]
@gabryon99 Missing items
- Format the license page with a two column table
- Use font of the same size, no mixed styles
