### ISSUE TITLE
Search box cuts long labels

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3667]
![Screen Shot 2020-03-30 at 13 00 36](https://user-images.githubusercontent.com/4493366/77905547-b967e780-7286-11ea-92bc-68e43c38cb5f.png)

**Comment by gabryon99** [comment]
Now dropdown is aligned to the right. Be sure to reload the cache. FIxed in https://github.com/ntop/ntopng/commit/72cefbd9c99f060d432c93d1ab5c409788553958
