### ISSUE TITLE
Too many subinterfaces defined

### ISSUE THREAD

**Issue by notpixxl** [ntop/ntopng#3670]
Hi,
Since my last update my probes seems down, everything is ok when i restart ntopng and nprobe services, but after several minutes traffic on all interfaces goes to 0.
I configured my local interface to Disaggregate traffic by Probe IP, adn got something like 50 subinterfaces.

In ntopng.log got the Warning message :
30/Mar/2020 14:05:55 [NetworkInterface.cpp:1067] WARNING: Too many subinterfaces defined

I don't understand the problem, this config worked on last version. Anyone can help me with this ?

**Comment by simonemainardi** [comment]
The maximum number of sub-interfaces which can be defined per interface is 32. This limit is imposed for performance.

It would be desirable if you could spawn 2 nprobe instances, each one receiving traffic from 25 exporters. Then, each nprobe instance can be connected to ntopng on a separate -i. This will allow you to have still 50 interfaces but more evenly balanced across cores.

**Comment by notpixxl** [comment]
Thanks for the advice i'll give it a try !
This limit is implemented with new version 4.0 ? Everything was fine before the upgrade ?

**Comment by simonemainardi** [comment]
Before 4.0 there was just a hard limit at 128 interfaces, but was not that good for performance. please report.

**Comment by notpixxl** [comment]
Seems i've got another problem my nprobe licence is not valid for unknown reason ... so exported flows limited to 25000 that's why my probes crash after several times. I'll check that and report once my licence is ok.

**Comment by simonemainardi** [comment]
reason why license is invalid is printed during ntopng startup. please check the logs.

**Comment by simonemainardi** [comment]
Solution given. No feedback received. Closing. Reopen with the requested information if necessary.

**Comment by notpixxl** [comment]
Hi,
Sorry for my late feedback, have just update my nprobe licence that is "out of maintenance" now it's ok. So now my problem is still the same : Too many subinterfaces defined and my metrics definitely flat :-(

Can you please tell me how can i spawn 2 nprobe instances ? Have to configure a new listening port ? if i do it i have to change the configuration of ~25 of my nflow routers (wich'll be hard because i don't have the management of those) ?

my nprobe configuration file look like this for now:
```
--zmq="tcp://*:5556"
--collector-port=2055
-n=none
-i=none
-T="@NTOPNG@"
--verbose=1
--online-license-check
```
