### ISSUE TITLE
Our license seems to have "disapeared"

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#3672]
![image](https://user-images.githubusercontent.com/48565067/77913571-7bf16300-7262-11ea-9839-a11002b5d816.png)

We are a community college, and we had a license until the upgrade, do we need to get a new one? If not how do we activate the old one?

**Comment by simonemainardi** [comment]
License could have been expired.  Licensing is described at https://www.ntop.org/support/faq/are-licenses-permanent-what-about-maintenance/

If you are eligible for free edu licenses you can ask at mallegro@ntop.org

**Comment by simonemainardi** [comment]
by the way, looking at the ntopng logs will tell you the reason why the license no longer unlocks the software.
