### ISSUE TITLE
Attempt to call a nil value

### ISSUE THREAD

**Issue by samuelesabella** [ntop/ntopng#3673]
Hello, I'm using ntopng (v.4.1.200330) and I got the following error while trying to access ntopng web GUI. 
```
WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/discover.lua][/usr/share/ntopng/scripts/lua/modules/plugins_utils.lua:34: attempt to call a nil value (field 'getCurrentPluginsDir')]
```
![Screenshot 2020-03-30 at 16 38 01](https://user-images.githubusercontent.com/18717354/77925714-7ec17780-72a5-11ea-8c94-0f176584770e.png)

**Comment by emanuele-f** [comment]
Please recompile ntopng and it will work

**Comment by emanuele-f** [comment]
Can you check the output of the following commands?

```
ls -l /usr/bin/ntopng
ls -l /usr/local/bin/ntopng
```

**Comment by samuelesabella** [comment]
Yesterday, after restarting it ntopng, everything was back to normal.
```
$ ls -l /usr/bin/ntopng
-rwxrwxr-x 1 root root 31589480 Mar 30 03:56 /usr/bin/ntopng
$ ls -l /usr/local/bin/ntopng
lrwxrwxrwx 1 root root 15 Mar 12 11:23 /usr/local/bin/ntopng -> /usr/bin/ntopng
```

**Comment by emanuele-f** [comment]
I suspect that the symbolic link may cause troubles, but for now let's close this.
