### ISSUE TITLE
Cannot complie new ntopng 4.0 with GCC 9.3 and GLIBC 2.31

### ISSUE THREAD

**Issue by sonic42** [ntop/ntopng#3675]
LOG:
g++ -g -Wall -I/usr/src/ntopng-4.0 -I/usr/src/ntopng-4.0/include -I/usr/local/include -D_FILE_OFFSET_BITS=64 -I/usr/local/include/hiredis -I/usr/include/hiredis -I/usr/src/ntopng-4.0/third-party/mongoose -I/usr/include/json-c  -I../nDPI/src/include -I../nDPI/src/lib/third_party/include -I/usr/src/ntopng-4.0/third-party/lua-5.3.5/src   -I/usr/include/mysql -I/usr/include/mysql/mysql  -I/usr/src/ntopng-4.0 -I/usr/src/ntopng-4.0/include -I/usr/local/include -I/usr/src/ntopng-4.0/third-party/http-client-c/src/  -I/usr/include/openssl  -DDATA_DIR='"/usr/share"' -I/usr/src/ntopng-4.0/third-party/libgeohash -I/usr/src/ntopng-4.0/third-party/patricia  -O2 -pipe -Wall -fexceptions -fPIC -m64 -mindirect-branch=thunk -mfunction-return=thunk -mtune=native -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -c src/GenericHashEntry.cpp -o src/GenericHashEntry.o
src/Flow.cpp: In member function 'void Flow::dissectNetBIOS(u_int8_t*, u_int16_t)':
src/Flow.cpp:3515:71: error: invalid conversion from 'int' to 'char*' [-fpermissive]
 3515 |      && (ndpi_netbios_name_interpret((char*)&payload[12], payload_len - 12, name, sizeof(name)) > 0)
      |                                                           ~~~~~~~~~~~~^~~~
      |                                                                       |
      |                                                                       int
src/Flow.cpp:3515:77: error: invalid conversion from 'char*' to 'u_int' {aka 'unsigned int'} [-fpermissive]
 3515 |      && (ndpi_netbios_name_interpret((char*)&payload[12], payload_len - 12, name, sizeof(name)) > 0)
      |                                                                             ^~~~
      |                                                                             |
      |                                                                             char*
src/Flow.cpp:3515:95: error: too many arguments to function 'int ndpi_netbios_name_interpret(char*, char*, u_int)'
 3515 |      && (ndpi_netbios_name_interpret((char*)&payload[12], payload_len - 12, name, sizeof(name)) > 0)
      |                                                                                               ^
In file included from /usr/src/ntopng-4.0/include/ntop_includes.h:118,
                 from src/Flow.cpp:22:
../nDPI/src/include/ndpi_main.h:135:7: note: declared here
  135 |   int ndpi_netbios_name_interpret(char *in, char *out, u_int out_len);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:148: src/Flow.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/usr/src/ntopng-4.0'
make: *** [ntopng:94: /usr/src/log/ntopng-4.0] Error 2

**Comment by lucaderi** [comment]
You need to update nDPI first and it will work

**Comment by sonic42** [comment]
The error comes with nDPI 3.2. A newer version i can't found.

**Comment by slokhorst** [comment]
Yep, same compile error here with nDPI 3.2. Please advise which nDPI to use.
```
g++ -g -Wall -I/home/sebas/abs/ntopng/src/ntopng-4.0 -I/home/sebas/abs/ntopng/src/ntopng-4.0/include -I/usr/local/include -I /home/sebas/abs/ntopng/src/ntopng-4.0/third-party/hiredis -I/home/sebas/abs/ntopng/src/ntopng-4.0/third-party/mongoose -I/usr/include/json-c   -I/home/sebas/abs/ntopng/src/nDPI-3.2/src/include -I/home/sebas/abs/ntopng/src/nDPI-3.2/src/lib/third_party/include -I/home/sebas/abs/ntopng/src/ntopng-4.0/third-party/lua-5.3.5/src -I/home/sebas/abs/ntopng/src/ntopng-4.0/third-party/rrdtool-1.4.8/src/ -I/usr/include/pgm-5.2  -I/usr/include/mysql -I/usr/include/mysql/mysql -D_FORTIFY_SOURCE=2 -I/home/sebas/abs/ntopng/src/ntopng-4.0 -I/home/sebas/abs/ntopng/src/ntopng-4.0/include -I/usr/local/include -I/home/sebas/abs/ntopng/src/ntopng-4.0/third-party/http-client-c/src/  -I/usr/include/openssl  -DDATA_DIR='"/usr/share"' -I/home/sebas/abs/ntopng/src/ntopng-4.0/third-party/libgeohash -I/home/sebas/abs/ntopng/src/ntopng-4.0/third-party/patricia  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -c src/FlowGrouper.cpp -o src/FlowGrouper.o
src/Flow.cpp: In member function ‘void Flow::dissectNetBIOS(u_int8_t*, u_int16_t)’:
src/Flow.cpp:3515:71: error: invalid conversion from ‘int’ to ‘char*’ [-fpermissive]
 3515 |      && (ndpi_netbios_name_interpret((char*)&payload[12], payload_len - 12, name, sizeof(name)) > 0)
      |                                                           ~~~~~~~~~~~~^~~~
      |                                                                       |
      |                                                                       int
src/Flow.cpp:3515:77: error: invalid conversion from ‘char*’ to ‘u_int’ {aka ‘unsigned int’} [-fpermissive]
 3515 |      && (ndpi_netbios_name_interpret((char*)&payload[12], payload_len - 12, name, sizeof(name)) > 0)
      |                                                                             ^~~~
      |                                                                             |
      |                                                                             char*
src/Flow.cpp:3515:95: error: too many arguments to function ‘int ndpi_netbios_name_interpret(char*, char*, u_int)’
 3515 |      && (ndpi_netbios_name_interpret((char*)&payload[12], payload_len - 12, name, sizeof(name)) > 0)
      |                                                                                               ^
In file included from /home/sebas/abs/ntopng/src/ntopng-4.0/include/ntop_includes.h:118,
                 from src/Flow.cpp:22:
/home/sebas/abs/ntopng/src/nDPI-3.2/src/include/ndpi_main.h:135:7: note: declared here
  135 |   int ndpi_netbios_name_interpret(char *in, char *out, u_int out_len);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by slokhorst** [comment]
I managed to get it to work with last (unreleased) commit from the [nDPI 3.2-stable branch](https://github.com/ntop/nDPI/tree/3.2-stable): https://github.com/ntop/nDPI/archive/3.2-stable.zip

It should probably be mentioned somewhere that this is required.

**Comment by sonic42** [comment]
It worked. Many thanks.
