### ISSUE TITLE
Ntop grafana plugin vs influxdb

### ISSUE THREAD

**Issue by Raptime** [ntop/ntopng#3676]
Hello,
I know the plugin has been discontinued but I can't seem to get the same information displayed in grafana:
The plugin showed the top 8 protocols for an interface, very convenient. Using influxdb there is no way, as far as I know (please correct me if I'm wrong), to display the top 8 in the same way. The closest I've gotten is to show all protocols for an interface which makes the graph difficult to read at a glance.
Any help appreciated!

**Comment by emanuele-f** [comment]
With InfluxDB you can also do this. Ntopng pro already prints the top protocols, so you can use the query performed by ntopng. You can print the ntopng queries by following the instructions at https://github.com/ntop/ntopng/blob/dev/doc/README.beta_features#L22

**Comment by Raptime** [comment]
I looked at the queries and it seems like you are doing some processing in report.lua between queries in order to generate the graphs, which is something that can't be done in grafana (as far as I know).

**Comment by emanuele-f** [comment]
The InfluxDB query generate raw points, that grafana shows. By using the same query that ntopng uses you should be able to get the same data visualization.

**Comment by Raptime** [comment]
I can't use the same query:
As far as I can tell you are using multiple queries to generate the graph in ntopng, one query to determine what the top protocols are and, based on that, specific queries to get the data points for each protocols. As far as I know this can't be done in grafana: I can't run a query based on the results of a previous query.

**Comment by emanuele-f** [comment]
Please check out https://community.grafana.com/t/how-to-use-influxdb-subqueries-in-grafana/195 . It seems like you can use them in "raw mode"
