### ISSUE TITLE
MDNS / Netbios names mixed with host labels

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3677]
Host labels should only be set by the user, not by ntopng. However function `Host::set_host_label` sets this information for MDNS names and Netbios names. This produces the following side effects:

- MDNS/Netbios names are kept indefinitely (see #3641 for a similar problem on DHCP)
- The host search box does not work properly in case of DHCP because it may return an old IP address for the host

**Comment by simonemainardi** [comment]
please attach a pcap with MDNS/Netbios when done to check
