### ISSUE TITLE
Implement bandwidth monitoring plugin

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3678]
The RTT framework should be extended to measure additional metrics. The first one is to monitor the available bandwidth making periodic measurements either with iperf or with solutions like 
- https://github.com/sindresorhus/fast-cli 
- https://github.com/sindresorhus/speed-test
- https://www.speedtest.net/apps/cli

See also #3618 as dependency

**Comment by emanuele-f** [comment]
This is now implemented

**Comment by mailinglists35** [comment]
could you add `iperf3` as well? `speedtest-cli` requires public internet server.

this is how someone did it for munin: https://github.com/mooondark/munin-iperf

**Comment by emanuele-f** [comment]
Please open a separate issue

**Comment by ShagoY** [comment]
Hi,
Is there any way to force a specific server (ID)?
I live in a place where there are many servers and sometimes the least/best ping server is not the one with the most bandwidth.

**Comment by simonemainardi** [comment]
please file a feature request with exact requirements
