### ISSUE TITLE
Make RTT measurements configurable

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3679]
The RTT component needs to be extended as #3618 and #3678. A quick change is to add an extra preference where we set the measurement frequency to
- minute
- 5 minute
- hour 
- day

This is because some tests might be time and and bandwidth consuming and thus they should not be executed every minute.

**Comment by emanuele-f** [comment]
The daily granularity has been skipped for now as it is currently not supported in the timeseries
