### ISSUE TITLE
not determining local hosts

### ISSUE THREAD

**Issue by brianjmurrell** [ntop/ntopng#368]
I start `ntopng` with `-m 10.75.22.0/24,fd31:aeb1:48df::/64,XXX::/64,YYY::/64,ZZZ::/64 --community -w 3001 -i /var/bandwidth_monitor/files.txt` and it reports that it's parsed the `-m` option correctly:

```
29/Jan/2016 08:11:47 [Ntop.cpp:933] Setting local networks to 10.75.22.0/24,fd31:aeb1:48df::/64,XXX::/64,YYY::/64,ZZZ::/64
```

Yet, when I go to Hosts and filter for only remote hosts (http://server:3001/lua/hosts_stats.lua?mode=remote) I see many of my local IPv6 hosts showing as remote.  `fd31:aeb1:48df:0:21f:cccc:bbbb:aaaa` for example.

I'm using v.2.2.160118

**Comment by simonemainardi** [comment]
add the `-vv` as ntopng startup option and see if it actually adds all the networks. You should see something like 

```
29/Jan/2016 14:42:37 [Ntop.cpp:543] Adding ::1/128 as IPv6 local network for lo0
29/Jan/2016 14:42:37 [AddressTree.cpp:139] Rule ::1/128
29/Jan/2016 14:42:37 [Ntop.cpp:513] Adding 127.0.0.0/8 as IPv4 local network for lo0
29/Jan/2016 14:42:37 [AddressTree.cpp:139] Rule 127.0.0.0/8
29/Jan/2016 14:42:37 [Ntop.cpp:543] Adding fe80::1/64 as IPv6 local network for lo0
29/Jan/2016 14:42:37 [AddressTree.cpp:139] Rule fe80::1/64
29/Jan/2016 14:42:37 [Ntop.cpp:543] Adding fe80::7a31:c1ff:febd:5e24/64 as IPv6 local network for en0
29/Jan/2016 14:42:37 [AddressTree.cpp:139] Rule fe80::7a31:c1ff:febd:5e24/64
29/Jan/2016 14:42:37 [Ntop.cpp:513] Adding 192.168.70.0/24 as IPv4 local network for en0
29/Jan/2016 14:42:37 [AddressTree.cpp:139] Rule 192.168.70.0/24
29/Jan/2016 14:42:37 [Ntop.cpp:543] Adding fe80::6a5b:35ff:fea7:de85/64 as IPv6 local network for en4
29/Jan/2016 14:42:37 [AddressTree.cpp:139] Rule fe80::6a5b:35ff:fea7:de85/64
29/Jan/2016 14:42:37 [Ntop.cpp:513] Adding 192.168.2.0/24 as IPv4 local network for en4
29/Jan/2016 14:42:37 [AddressTree.cpp:139] Rule 192.168.2.0/24
```

I would also wrap the network list between a pair of `"`

**Comment by brianjmurrell** [comment]
```
29/Jan/2016 11:48:19 [Ntop.cpp:933] Setting local networks to 10.75.22.0/24,fd31:aeb1:48df::/64,XXX::/64,YYY::/64,ZZZ::/64
29/Jan/2016 11:48:19 [AddressTree.cpp:139] Rule 10.75.22.0/24
29/Jan/2016 11:48:19 [AddressTree.cpp:139] Rule fd31:aeb1:48df::/64
29/Jan/2016 11:48:19 [AddressTree.cpp:139] Rule XXX::/64
29/Jan/2016 11:48:19 [AddressTree.cpp:139] Rule YYY::/64
29/Jan/2016 11:48:19 [AddressTree.cpp:139] Rule ZZZ::/64
```

I don't get the `Adding ... as IPv* local network for` messages.

One thing worth noting is that I am not capturing from an interface but rather reading a pcap file (list).

**Comment by brianjmurrell** [comment]
Anything more on this?

What is even more interesting is that in http://server:3000/lua/pro/report.lua?num_minutes=10080 in the section "Local Networks" under my interface name, it does correctly list all of my local networks, yet still, in http://server:3000/lua/hosts_stats.lua only my IPv4 hosts are being shown as Local.  My IPv6 hosts are being shown as remote.

**Comment by simonemainardi** [comment]
please, check now and let us know
