### ISSUE TITLE
Use system wide proxy settings

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3680]
In order to allow `libcurl` to use the system proxy settings, it is necessary to add the following line under the `[Service]` section of the systemd unit file:

```
EnvironmentFile=-/etc/environment
```

This is explained in https://github.com/coreos/bugs/issues/1507#issuecomment-239353353

**Comment by lucaderi** [comment]
Implemented. See https://github.com/ntop/ntopng/tree/dev/doc#using-ntopng-with-a-https-proxy
