### ISSUE TITLE
database disk image is malformed

### ISSUE THREAD

**Issue by HH62** [ntop/ntopng#3681]
Hi,

after a crash, I had to recreate the mysql database 'ntopng'.
Ntopng professional edition 4.1.200331 (9651) is running.

Now, I find every minute the following in the log file:

Mar 31 22:10:01 ubuntu-server-ntopng ntopng: [StoreManager.cpp:120] ERROR: SQL Error: [11][database disk image is malformed (11)]
Mar 31 22:10:01 ubuntu-server-ntopng ntopng[4217]: 31/Mar/2020 22:10:01 [StoreManager.cpp:120] ERROR: SQL Error: [11][database disk image is malformed (11)]

What does it mean, any ideas? 

Greeting Hendrik

**Comment by simonemainardi** [comment]
This is the sqlite database which is corruped. Disk failure? Let's try and re-create it. Stop ntopng, go into the ntopng data directory, and do the following:

```
find . -name *.db -exec rm -rf {} \;
```

Then, restart ntopng.

**Comment by HH62** [comment]
This helped. The error message disappeared.
Tanks a lot.
