### ISSUE TITLE
Notification badge no longer disappears

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3682]
The red badge with 3 always stays there. no matter if I open/close and how many times I do it.

![image](https://user-images.githubusercontent.com/3397663/78111531-1685a980-73fd-11ea-93fe-7681c20d368c.png)

![image](https://user-images.githubusercontent.com/3397663/78111596-31f0b480-73fd-11ea-9f68-b2f88b4a79d8.png)

**Comment by simonemainardi** [comment]
Number decreases only when clicking on the link.

Note clicking 'open in a new tab' does not affect the counter.

**Comment by lucaderi** [comment]
This is the correct behaviour
