### ISSUE TITLE
Notifications counter broken

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3684]
three new articles

![image](https://user-images.githubusercontent.com/3397663/78137547-cff87500-7425-11ea-816c-907733c27f00.png)

click on the first article, counter goes to two

![image](https://user-images.githubusercontent.com/3397663/78137587-e3a3db80-7425-11ea-8cbd-2b46abd43e52.png)

closing and reopening the browser tab (firefox) resets the counter to three

![image](https://user-images.githubusercontent.com/3397663/78137665-00401380-7426-11ea-9b7b-e10ea38d0680.png)

**Comment by gabryon99** [comment]
Do your browser clean the local storage during the closing?

**Comment by simonemainardi** [comment]
I just close and reopen a FF tab, not the whole application. I don't touch anything apart from closing the tab.

**Comment by gabryon99** [comment]
I changed the whole notification system. Now the notification are saved inside Redis, so the notification counter is the same across the browsers. Fixed in https://github.com/ntop/ntopng/commit/633ee3096d515764e82424aad7a84b855b2cde6e
