### ISSUE TITLE
Can not login

### ISSUE THREAD

**Issue by danisraelkc** [ntop/ntopng#3685]
Installed on clean pfSense install, and unable to login to webdialog.  It comes up, enter default for both and just clears the form.  Reset password as well and did not work.  I do already have a Firewall user of admin ... but not sure why this isn't working.

**Comment by emanuele-f** [comment]
Which ntopng version are you using? Please check out https://www.ntop.org/guides/ntopng/faq.html#cannot-login-into-the-gui . Can you explain the steps that you are taking to reset the password? Please note that we do not officially support pfsense so consider asking questions on the pfsense forums

**Comment by danisraelkc** [comment]
Using "ntopng v 0.8.13_3" on pfSense 2.4.5.   Tried on Chrome, Safari, Edge, and IE11.  No luck.  All do the same thing.  I get the "Welcome to ntopng" login dialog.  I enter admin/admin, then when i click login, it clears my entries.

Run both password and preference reset from the shell of pfsense.

**Comment by emanuele-f** [comment]
The default credentials are admin:admin in ntopng but you are using a third party integration, please contact the pfsense support.
