### ISSUE TITLE
Moving from centos to centos-stable repository brakes all libpcap base application

### ISSUE THREAD

**Issue by morphyno** [ntop/ntopng#369]
We have been on "http://www.nmon.net/centos/$releasever/$basearch/" for sometime and we switched to "http://www.nmon.net/centos-stable/$releasever/$basearch/" recently.

To minimize dependency issues, we remove all ntopng,ntopng-data,pfring,pfring-dkms,nprobe first before installing fresh from the stable repository. 

However, upon installing from the stable repository, we notice any libpcap based application are complaining about not being able to link to libsnf

dumpcap
dumpcap: error while loading shared libraries: libsnf.so.0: cannot open shared object file: No such file or directory

tshark
tshark: error while loading shared libraries: libsnf.so.0: cannot open shared object file: No such file or directory

That was never an issue on the  "centos" repository, only on the RPM's installed from "centos-stable". It seems the packages on the "centos-stable" was build with different libpcap configurations. 

This seems to be a build configuration issue between the two repositories. 

So far there are two methods of workarounds, both are not acceptable for our enterprise customers.

1) Removing pfring completely from the machine allows you to run the tools again, but they must of course not use pfring or be compiled without pfring support to work.
2) Re-install libpcap, not from rpm, but configure,make and make install from source.

**Comment by morphyno** [comment]
There is no method of indication urgency but this is a fairly urgent issue for us. We integrate Ntopng/Nprobe/PFring in our enterprise network monitoring products.

**Comment by lucaderi** [comment]
@morphyno I have done a little change in the stable packages. Can you see if something has changed

**Comment by morphyno** [comment]
Thank you @lucaderi , i see there has been repo changes, but the RPMs are still from 1/18, i guess new RPM's will be generated automatically?

**Comment by lucaderi** [comment]
correct. Packages are being rebuilt

**Comment by morphyno** [comment]
@lucaderi, i installed the rpm's build on 1/29, still see this issue. 

[devusern@localhost ntop_rpms]$ sudo yum -y install *
[sudo] password for devuser:
Loaded plugins: fastestmirror
Examining libnetfilter_queue-1.0.2-2.el7.x86_64.rpm: libnetfilter_queue-1.0.2-2.el7.x86_64
libnetfilter_queue-1.0.2-2.el7.x86_64.rpm: does not update installed package.
Examining nprobe-7.2.160129-4471.x86_64.rpm: nprobe-7.2.160129-4471.x86_64
Marking nprobe-7.2.160129-4471.x86_64.rpm to be installed
Examining ntopng-2.2.160129-693.x86_64.rpm: ntopng-2.2.160129-693.x86_64
Marking ntopng-2.2.160129-693.x86_64.rpm to be installed
Examining ntopng-data-2.2.160129-693.noarch.rpm: ntopng-data-2.2.160129-693.noarch
Marking ntopng-data-2.2.160129-693.noarch.rpm to be installed
Examining pfring-6.2.0-442.x86_64.rpm: pfring-6.2.0-442.x86_64
Marking pfring-6.2.0-442.x86_64.rpm to be installed
Examining pfring-dkms-6.2.0-442.noarch.rpm: pfring-dkms-6.2.0-442.noarch
Marking pfring-dkms-6.2.0-442.noarch.rpm to be installed
Examining zeromq-4.0.5-4.el7.x86_64.rpm: zeromq-4.0.5-4.el7.x86_64
zeromq-4.0.5-4.el7.x86_64.rpm: does not update installed package.
Resolving Dependencies
--> Running transaction check
---> Package nprobe.x86_64 0:7.2.160129-4471 will be installed
---> Package ntopng.x86_64 0:2.2.160129-693 will be installed
---> Package ntopng-data.noarch 0:2.2.160129-693 will be installed
---> Package pfring.x86_64 0:6.2.0-442 will be installed
---> Package pfring-dkms.noarch 0:6.2.0-442 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

# 

#  Package                      Arch                    Version                          Repository                                           Size

Installing:
 nprobe                       x86_64                  7.2.160129-4471                  /nprobe-7.2.160129-4471.x86_64                      3.0 M
 ntopng                       x86_64                  2.2.160129-693                   /ntopng-2.2.160129-693.x86_64                        63 M
 ntopng-data                  noarch                  2.2.160129-693                   /ntopng-data-2.2.160129-693.noarch                   46 M
 pfring                       x86_64                  6.2.0-442                        /pfring-6.2.0-442.x86_64                             12 M
 pfring-dkms                  noarch                  6.2.0-442                        /pfring-dkms-6.2.0-442.noarch                       362 k

# Transaction Summary

Install  5 Packages

Total size: 124 M
Installed size: 124 M
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : ntopng-data-2.2.160129-693.noarch                                                                                             1/5
  Installing : pfring-dkms-6.2.0-442.noarch                                                                                                  2/5
WARNING: /usr/lib64/dkms/common.postinst does not exist.
Loading new pfring-6.2.0 DKMS files...
Building for 3.10.0-229.7.2.el7.x86_64
Building initial module for 3.10.0-229.7.2.el7.x86_64
Done.

pf_ring:
Running module version sanity check.
- Original module
  - No original module exists within this kernel
- Installation
  - Installing to /lib/modules/3.10.0-229.7.2.el7.x86_64/extra/
    Adding any weak-modules

depmod...

DKMS: install completed.
  Installing : pfring-6.2.0-442.x86_64                                                                                                       3/5
  Installing : nprobe-7.2.160129-4471.x86_64                                                                                                 4/5
  Installing : ntopng-2.2.160129-693.x86_64                                                                                                  5/5
Setting up redis auto startup
Note: Forwarding request to 'systemctl enable redis.service'.
Creating link under /usr/local/bin
ln -s '/etc/systemd/system/ntopng.service' '/etc/systemd/system/multi-user.target.wants/ntopng.service'
  Verifying  : ntopng-data-2.2.160129-693.noarch                                                                                             1/5
  Verifying  : pfring-dkms-6.2.0-442.noarch                                                                                                  2/5
  Verifying  : nprobe-7.2.160129-4471.x86_64                                                                                                 3/5
  Verifying  : pfring-6.2.0-442.x86_64                                                                                                       4/5
  Verifying  : ntopng-2.2.160129-693.x86_64                                                                                                  5/5

Installed:
  nprobe.x86_64 0:7.2.160129-4471     ntopng.x86_64 0:2.2.160129-693     ntopng-data.noarch 0:2.2.160129-693     pfring.x86_64 0:6.2.0-442
  pfring-dkms.noarch 0:6.2.0-442

Complete!
[devuser@localhost ntop_rpms]$ sudo dumpcap
dumpcap: error while loading shared libraries: libsnf.so.0: cannot open shared object file: No such file or directory

Again, I did "yum remove pfring pfring-dkms nprobe ntopng ntopng-data" that i had installed from centos repo first, and then installed the rpm's i downloaded from the "centos-stable" repo

**Comment by lucaderi** [comment]
What's is dumpcap? Why is it looking for ntop libs? Please do "ldd dumpcap" to understand what is the problem,

**Comment by morphyno** [comment]
It seems the issue has to do with "yum remove"

This is the command I used

sudo yum remove pfring nprobe nbox ntopng ntopng-data pfring-dkms

Before that command, here is the output of ldd /usr/sbin/dumpcap

```
    linux-vdso.so.1 =>  (0x00007fff25dfe000)
    libwsutil.so.3 => /lib64/libwsutil.so.3 (0x00007f254dca2000)
    libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f254d96f000)
    libpcap.so.1 => /usr/local/lib/libpcap.so.1 (0x00007f254d6d9000)
    libcap.so.2 => /lib64/libcap.so.2 (0x00007f254d4d4000)
    libz.so.1 => /lib64/libz.so.1 (0x00007f254d2be000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f254d0a1000)
    libc.so.6 => /lib64/libc.so.6 (0x00007f254cce0000)
    libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007f254cade000)
    libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x00007f254c8d9000)
    libnuma.so.1 => /lib64/libnuma.so.1 (0x00007f254c6cd000)
    librt.so.1 => /lib64/librt.so.1 (0x00007f254c4c5000)
    libattr.so.1 => /lib64/libattr.so.1 (0x00007f254c2bf000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f254e0ce000)
    libdl.so.2 => /lib64/libdl.so.2 (0x00007f254c0bb000)
    libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f254bea5000)
```

Here is after the removal

```
      linux-vdso.so.1 =>  (0x00007fff169fe000)
      libwsutil.so.3 => /lib64/libwsutil.so.3 (0x00007f338c09e000)
      libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f338bd6b000)
      libpcap.so.1 => /usr/local/lib/libpcap.so.1 (0x00007f338bab8000)
      libcap.so.2 => /lib64/libcap.so.2 (0x00007f338b8b3000)
      libz.so.1 => /lib64/libz.so.1 (0x00007f338b69d000)
      libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f338b480000)
      libc.so.6 => /lib64/libc.so.6 (0x00007f338b0bf000)
      libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007f338aebd000)
      libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x00007f338acb8000)
      librt.so.1 => /lib64/librt.so.1 (0x00007f338aab0000)
      libntapi.so => /lib64/libntapi.so (0x00007f338880e000)
      libntos.so => /lib64/libntos.so (0x00007f33885ec000)
      libanic.so => /lib64/libanic.so (0x00007f33883db000)
      libsnf.so.0 => not found
      libattr.so.1 => /lib64/libattr.so.1 (0x00007f33881d5000)
      /lib64/ld-linux-x86-64.so.2 (0x00007f338c4ca000)
      libdl.so.2 => /lib64/libdl.so.2 (0x00007f3387fd1000)
```

**Comment by lucaderi** [comment]
If dumpcap was linked with the pfring library, I consider this a standard behaviour.

**Comment by codearrangertoo** [comment]
I'm having the same issue.
This looks related: https://www.centos.org/forums/viewtopic.php?f=47&t=56051

**Comment by codearrangertoo** [comment]
tcpdump, dumpcap, tshark, etc all worked fine before I installed ntopng

**Comment by codearrangertoo** [comment]
Now I get this...

$ sudo tcpdump 
tcpdump: error while loading shared libraries: libsnf.so.0: cannot open shared object file: No such file or directory
$

**Comment by codearrangertoo** [comment]
[jgarland@beast ~]$ sudo dumpcap
dumpcap: error while loading shared libraries: libsnf.so.0: cannot open shared object file: No such file or directory
[jgarland@beast ~]$ sudo tshark
tshark: error while loading shared libraries: libsnf.so.0: cannot open shared object file: No such file or directory
[jgarland@beast ~]$ sudo nc
nc: error while loading shared libraries: libsnf.so.0: cannot open shared object file: No such file or directory

Pretty much anything that used libpcap is now broken after installing the ntopng rpms.

**Comment by lucaderi** [comment]
Why do you use /usr/local/lib/libpcap.so.1 ? I think this is the problem. This is ntop's library part of PF_RING. if you use non-PF_RING apps you should use the system library not this,

**Comment by OMGsus** [comment]
I don't think anyone is purposefully linking those libs. Things work fine in Centos7 until pf_ring is installed. Cent guys don't seem to think this is a problem with cent. They are directing us back to pf_ring. 

Quote: "We don't supply pfring so the people that do are supplying packages that break CentOS and you need to talk to them."

So the question of "Why do you use /usr/local/lib/libpcap.so.1 ?" would need to be answered by pf_ring I would think. Maybe the libs need to be put somewhere that only pf_ring can see them until this is corrected. apparently cents stopped using anything with libsnf and pf_ring being installed afterwards starts existing apps linking to pf_ring libs that it shouldn't. Even ones where I want to link to the pf_ring libs call for a libsnf that doesn't exist. It's possible the direction is to stop using libsnf in pf_ring and use the newer methods? I'm not sure.

I'll pull latest stables and nightlies again tonight but this is still a problem as of this morning.

**Comment by cardigliano** [comment]
Please test latest dev packages.

**Comment by cpuodzius** [comment]
This issue is affecting users from 2.2-stable which has been built on CentOS 7.1.1503 whereas the current CentOS release is 7.2.1511.

**Comment by OMGsus** [comment]
Rebuilding on both now. Will test on a latest centos7 build too. Just takes some time getting the latest centos stable on my ixgbe systems.

**Comment by cardigliano** [comment]
I applied the patch also to the stable. New builds will be available soon.

**Comment by morphyno** [comment]
The latest builds on 2/14 seems to have resolve the issue. Thank you @cardiglian @lucaderi for the fix!

**Comment by OMGsus** [comment]
Working on my centos7 Ixgbe hosts. Going to relink for plugins now :) thanks!
