### ISSUE TITLE
mange user- change allowed interface

### ISSUE THREAD

**Issue by Guymtrx** [ntop/ntopng#3690]
Hi
I tried to change allowed interface for exist user from any interface to specific interface.
after I click "Change user preferences" it's not save my selection and go back to any interface

tnx
Guy

![image](https://user-images.githubusercontent.com/59534272/78234020-37263000-74df-11ea-9c7e-a26f9676a2bb.png)

**Comment by emanuele-f** [comment]
Thank you for reporting. A new package will be available in two hours.
