### ISSUE TITLE
Host pool member device type no longer saved

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3695]
trying to set router type to the member has no effect

![image](https://user-images.githubusercontent.com/3397663/78257363-0acbdd00-74fa-11ea-89ab-4ce6f4d11448.png)

after saving the page goes back to

![image](https://user-images.githubusercontent.com/3397663/78257416-16b79f00-74fa-11ea-86a4-d4a75d8d783c.png)

**Comment by lucaderi** [comment]
I suggest not to fix this bug, but to redo the table using the DataTable
