### ISSUE TITLE
Unable to save multiple traffic profiles

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3696]
When adding multiple traffic profiles it is impossible to save. Clicking on save is ineffective, nothing happens

advanced_features_traffic_profiles_edit
![image](https://user-images.githubusercontent.com/3397663/78281492-0b28a000-751b-11ea-9cae-3fd8f9b61972.png)

**Comment by lucaderi** [comment]
I suggest not to fix this bug, but to redo the table using the DataTable

**Comment by emanuele-f** [comment]
The bug was caused by a missing `disabled` class on the button, now fixed
