### ISSUE TITLE
RESTful API to get a Discovery json file

### ISSUE THREAD

**Issue by scannizzaro** [ntop/ntopng#3697]
Hi everyone, it might be useful to have a RESTful API to get the json file of a Discovery, made via ntopng.
Thanks

**Comment by lulululuej** [comment]
Hi,
is there any api to call network discovery? thanks.

**Comment by simonemainardi** [comment]
You can use endpoint `http://localhost:3000/lua/get_discover_data.lua?currentPage=1&perPage=10&sortColumn=&sortOrder=` to get a JSON reponse of the disovery data.
