### ISSUE TITLE
Grafana does't work with Ntopng 4.

### ISSUE THREAD

**Issue by serg470** [ntop/ntopng#3700]
When i try to setup new ntop data source in grafana I get "HTTP Error Not Found" In 3.8 version i used next URL http://192.168.1.19:3000/lua/modules/grafana/ and everything was fine.

**Comment by simonemainardi** [comment]
hi, the ntopng grafana datasource has been discontinued one year ago as explained in https://github.com/ntop/ntopng-grafana-datasource#discontinuation-notice

You just have to use ntopng in combination with influxdb and then use the influxdb grafana datasource for the charts.
