### ISSUE TITLE
Error page for generated errors

### ISSUE THREAD

**Issue by gabryon99** [ntop/ntopng#3701]
When an error is generated the user must be redirected to the error page. Just like this one in the screenshot below:
<img width="1781" alt="Screenshot 2020-04-04 at 23 44 22" src="https://user-images.githubusercontent.com/14114916/78461994-37385280-76ce-11ea-8248-254b26f284c4.png">

To generate an error like that, follow this steps:
1. go to `page_utils.lua` and change in the function `page_utils.print_page_header`the line where `help_link` variable is defined;
2. remove the field `help_link` from `page_utils.menu_entries[active_entry].help_link` line;
3. go to page `http://localhost:3000/lua/plugins_overview.lua`;

**Comment by lucaderi** [comment]
This bug is invalid. You are saying you are putting a bug in the lua code that renders the page. This should not happen otherwise the only option is to go back to plain text or minimal lua-based pages (supposing the interpreter can start)
