### ISSUE TITLE
Prometheus Support Removed?

### ISSUE THREAD

**Issue by aauren** [ntop/ntopng#3705]
I noticed that 4.0 doesn't contain Prometheus metrics support any longer. It looks like @lucaderi removed it here: https://github.com/ntop/ntopng/commit/3984a19226b89b2888c3736aebbf66f69f63b3ea

This was something that I used substantially in my graphing flows. It is specifically better than something like say Influx for me because it is easy for me to enrich it with additional data before it gets scraped by Prometheus.

Is this a feature that is ever likely to return? If not, would it be easy to add the functionality back via say a User Script or a Plugin? Any information about this feature would be greatly appreciated!

**Comment by lucaderi** [comment]
Prometheus support was removed as incomplete (it was a write only plugin). You are welcome to send us a pull request that includes a full fledged implementation of the plugin so we can seamlessly use RRD, Influx and Prometheus. Awaiting your contribution

**Comment by aauren** [comment]
@lucaderi Thanks for your quick response! I see now that you're interested in timeseries DB's that act as both read and write stores for you. I'm guessing that is useful so that ntopng can read from the store to present data in addition to writing to it?

For what it's worth, I found a lot of value in having the write-only prometheus store. In a way it kinda worked like an ntopng-exporter for me. And as I alluded to earlier, having the metrics in HTTP prometheus format made it super easy to enrich the metrics in useful ways (since you can just reverse proxy it through an enricher function and then have prometheus scrape from the proxy).

I totally understand that this workflow might be a bit specific to me and not something that you want to put time towards. If I were to contribute an ntopng exporter to the project is that something that a PR that you would want to merge?

**Comment by cleverchou** [comment]
V3.9: when ntop  exports  timeeseries data to prometheus, prometheus 's targets show ERROR,  "INVALID is not a valid start token"
how to deal with it?
thank you

**Comment by simonemainardi** [comment]
as explained, prometheus support has been dropped in v4.
