### ISSUE TITLE
Better handle license switch

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3706]
![image](https://user-images.githubusercontent.com/4493366/78552155-4373fb00-7807-11ea-8a9c-d4cf1f41d846.png)
When the demo mode ends, errors like the one above are reported when switching back to community edition. They need to be handled more nicely.

See also #3595

**Comment by emanuele-f** [comment]
What is the output of `ntopng --version`? Please ensure that the git commit revision is newer than 1a76dcc888262fd3ffb720f7a5ee58025d781266 .

**Comment by simonemainardi** [comment]
debian 10 installed as:


```

sudo apt-get update
sudo apt-get install softwareproperties-common wget
sudo add-apt-repository universe
wget http://apt-stable.ntop.org/buster/all/apt-ntop-stable.deb
sudo apt-get install ./apt-ntop-stable.deb
sudo apt-get clean all
sudo apt-get update
sudo apt-get install ntopng ntopng-data
```

**Comment by simonemainardi** [comment]
@emanuele-f did you try to reproduce with SNMP polling in progress?

**Comment by emanuele-f** [comment]
Cannot reproduce with the latest changes. If the issue occurs again, please open a new issue with the output of `ntopng --version` and the configuration used.
