### ISSUE TITLE
Invalid cell format 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3707]
Traditionally has the following layout in tables
<cell with label> <cell with value>

In the table below (under interface when ZMQ collection is used) this is the result
![Screen Shot 2020-04-06 at 15 34 50](https://user-images.githubusercontent.com/4493366/78564193-5c3adb80-781c-11ea-9b2b-98c381b5a3b6.png)

Problems
- cell wrap (red value)
- a lot of space wasted in empty rows
- <cell with label: value> instead of <cell with label> <cell with value>

Correct layout

![Screen Shot 2020-04-06 at 15 38 19](https://user-images.githubusercontent.com/4493366/78564416-ae7bfc80-781c-11ea-985e-8d50cbf07a3a.png)

**Comment by emanuele-f** [comment]
Here is the layout after the fix.

![2020-05-11_17-45](https://user-images.githubusercontent.com/5488003/81581732-a6c0f200-939e-11ea-81ad-053c651bfdf4.png)
