### ISSUE TITLE
On license install getting "operation not permited"

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#3708]
Maria Teresa Allegro (mallegro@ntop.org) requested that I open this ticket

Getting operation not permitted even as root on license install
```
root@ntopng:~# echo "[license]" > /etc/ntopng.license
bash: /etc/ntopng.license: Operation not permitted
```
---
```
*** System restart required ***
Last login: Mon Apr  6 11:56:04 2020 from 172.16.1.193
support@ntopng:~$ ntopng --version
v.4.1.200403    [Enterprise/Professional build]
GIT rev:        dev:24b13e240c27bdf6b1c64610c551b36067e50c7f:20200403
Pro rev:        r2814
Built on:       Ubuntu 18.04.4 LTS
System Id:      6B4891C10C0207EE
Platform:       x86_64
```

**Comment by simonemainardi** [comment]
it seems root can't write to `/etc`. Is there any fs protection mechanism enabled? This is strange. please go to `/etc`, type `ls -lha` and report the output. Also try an touch any other file e.g., `touch test` inside `/etc`.

**Comment by StewAlexander-com** [comment]
Almost everything is owned by root, and no we have no file system protection

![image](https://user-images.githubusercontent.com/48565067/78678162-98bb1580-78b6-11ea-8a15-b45032b9963e.png)

```
root@ntopng:/etc# touch test
root@ntopng:/etc#
``
----
```
root@ntopng:/etc# ls |grep test
popularity-contest.conf
test
root@ntopng:/etc#
```

ntopng.license does not exist at /etc/, does this matter?

**Comment by emanuele-f** [comment]
Please note that you can also insert the license in the ntopng "About" page

**Comment by StewAlexander-com** [comment]
I tried that @emanuele-f, through multiple emails with Maria, with no luck

**Comment by emanuele-f** [comment]
Please retry to insert the license into the gui and then report the output of `ntopng --version`

**Comment by simonemainardi** [comment]
@StewAlexanderACC did you manage to make it work? Did it create the file `test` under `/etc`?

**Comment by StewAlexander-com** [comment]
No




Best Regards,
 
Stewart Alexander
 
Network Administrator
Alamance Community College
stewart.alexander@alamancecc.edu
 
"Chi poco pensa, molto erra." -Leonardo Di Vinci
(He who thinks little errors much)
>>> simonemainardi <notifications@github.com> 04/09/20 4:02 AM >>>
CAUTION: This email originated from outside your organization. Exercise
caution when opening attachments or clicking links, especially from
unknown senders.
 
 
 @StewAlexanderACC did you manage to make it work? Did it create the
file test under /etc?

**Comment by simonemainardi** [comment]
can we arrange a remote session?

**Comment by StewAlexander-com** [comment]
Perhaps next week, I will let you know, thanks

**Comment by StewAlexander-com** [comment]
I am available on a limited basis this week, please let me know your schedule and I will attempt to make a time slot available 

We are EDT (GMT -4, or Italy time -6)

Thank you ...

**Comment by StewAlexander-com** [comment]
@simonemainardi 

Hopefully things with your team are ok with the Corona virus issue....

I have some time this week if you our one of your team members can remotely connect

**Comment by emanuele-f** [comment]
This is a license issue so please contact privately via https://www.ntop.org/support/need-help-2/contact-us so that we can arrange a remote session.
