### ISSUE TITLE
Strange DNS failure in nightly build

### ISSUE THREAD

**Issue by whoknowz** [ntop/ntopng#371]
Installed a professional version of ntopng nightly in a bump-in-the-wire config and suddenly all DNS traffic fails. nslookup to any DNS server, local or remote fails.
Installed stable version and resolved the issue, however stable has the "flow" bug #311 where individual host's flow cannot be viewed.
I am a bit baffled, since I run nightly on several machines in bump-in-the-wire config, but only this machine running on top of vSphere 6.0 has the issue.
Bypassing ntopng bumb-in-the-wire, and DNS works great.

Below is how the setup is.

Internet <--> pfsense <--> ntopng <--> lan

What could possible be the problem?

**Comment by ValentinaViscarelli** [comment]
Could you send us two capture file? The first one has to be capture before ntopng and the second one after.

**Comment by whoknowz** [comment]
I can't replicate the issue locally, it is happening at two of my client places. Reverting to version 2.2 fixes the issues always. I will try to get a pcap dump.

**Comment by simonemainardi** [comment]
@whoknowz did you manage to get a pcap? Also please note that the flow bug fix has been ported to stable as well.

**Comment by lucaderi** [comment]
Fixed by https://github.com/ntop/nDPI/commit/27d09c33ce881e3104637764f63f4e87018a4866
