### ISSUE TITLE
Can't compile NTOPNG 4.0 on Ubuntu

### ISSUE THREAD

**Issue by manjotsc** [ntop/ntopng#3711]
`
root@ubuntu:~/ntopng# make
cd /root/ntopng/third-party/zeromq-4.1.7; ./configure --without-documentation --without-libsodium; make
configure: error: cannot find install-sh, install.sh, or shtool in config "."/config
make[1]: Entering directory '/root/ntopng/third-party/zeromq-4.1.7'
Makefile:2340: perf/.deps/inproc_lat.Po: No such file or directory
Makefile:2341: perf/.deps/inproc_thr.Po: No such file or directory
Makefile:2342: perf/.deps/local_lat.Po: No such file or directory
Makefile:2343: perf/.deps/local_thr.Po: No such file or directory
Makefile:2344: perf/.deps/remote_lat.Po: No such file or directory
Makefile:2345: perf/.deps/remote_thr.Po: No such file or directory
Makefile:2346: src/.deps/libzmq_la-address.Plo: No such file or directory
Makefile:2347: src/.deps/libzmq_la-clock.Plo: No such file or directory
Makefile:2348: src/.deps/libzmq_la-ctx.Plo: No such file or directory
Makefile:2349: src/.deps/libzmq_la-curve_client.Plo: No such file or directory
Makefile:2350: src/.deps/libzmq_la-curve_server.Plo: No such file or directory
Makefile:2351: src/.deps/libzmq_la-dealer.Plo: No such file or directory
Makefile:2352: src/.deps/libzmq_la-devpoll.Plo: No such file or directory
Makefile:2353: src/.deps/libzmq_la-dist.Plo: No such file or directory
Makefile:2354: src/.deps/libzmq_la-epoll.Plo: No such file or directory
Makefile:2355: src/.deps/libzmq_la-err.Plo: No such file or directory
Makefile:2356: src/.deps/libzmq_la-fq.Plo: No such file or directory
Makefile:2357: src/.deps/libzmq_la-gssapi_client.Plo: No such file or directory
Makefile:2358: src/.deps/libzmq_la-gssapi_mechanism_base.Plo: No such file or directory
Makefile:2359: src/.deps/libzmq_la-gssapi_server.Plo: No such file or directory
Makefile:2360: src/.deps/libzmq_la-io_object.Plo: No such file or directory
Makefile:2361: src/.deps/libzmq_la-io_thread.Plo: No such file or directory
Makefile:2362: src/.deps/libzmq_la-ip.Plo: No such file or directory
Makefile:2363: src/.deps/libzmq_la-ipc_address.Plo: No such file or directory
Makefile:2364: src/.deps/libzmq_la-ipc_connecter.Plo: No such file or directory
Makefile:2365: src/.deps/libzmq_la-ipc_listener.Plo: No such file or directory
Makefile:2366: src/.deps/libzmq_la-kqueue.Plo: No such file or directory
Makefile:2367: src/.deps/libzmq_la-lb.Plo: No such file or directory
Makefile:2368: src/.deps/libzmq_la-mailbox.Plo: No such file or directory
Makefile:2369: src/.deps/libzmq_la-mechanism.Plo: No such file or directory
Makefile:2370: src/.deps/libzmq_la-metadata.Plo: No such file or directory
Makefile:2371: src/.deps/libzmq_la-msg.Plo: No such file or directory
Makefile:2372: src/.deps/libzmq_la-mtrie.Plo: No such file or directory
Makefile:2373: src/.deps/libzmq_la-norm_engine.Plo: No such file or directory
Makefile:2374: src/.deps/libzmq_la-null_mechanism.Plo: No such file or directory
Makefile:2375: src/.deps/libzmq_la-object.Plo: No such file or directory
Makefile:2376: src/.deps/libzmq_la-options.Plo: No such file or directory
Makefile:2377: src/.deps/libzmq_la-own.Plo: No such file or directory
Makefile:2378: src/.deps/libzmq_la-pair.Plo: No such file or directory
Makefile:2379: src/.deps/libzmq_la-pgm_receiver.Plo: No such file or directory
Makefile:2380: src/.deps/libzmq_la-pgm_sender.Plo: No such file or directory
Makefile:2381: src/.deps/libzmq_la-pgm_socket.Plo: No such file or directory
Makefile:2382: src/.deps/libzmq_la-pipe.Plo: No such file or directory
Makefile:2383: src/.deps/libzmq_la-plain_client.Plo: No such file or directory
Makefile:2384: src/.deps/libzmq_la-plain_server.Plo: No such file or directory
Makefile:2385: src/.deps/libzmq_la-poll.Plo: No such file or directory
Makefile:2386: src/.deps/libzmq_la-poller_base.Plo: No such file or directory
Makefile:2387: src/.deps/libzmq_la-proxy.Plo: No such file or directory
Makefile:2388: src/.deps/libzmq_la-pub.Plo: No such file or directory
Makefile:2389: src/.deps/libzmq_la-pull.Plo: No such file or directory
Makefile:2390: src/.deps/libzmq_la-push.Plo: No such file or directory
Makefile:2391: src/.deps/libzmq_la-random.Plo: No such file or directory
Makefile:2392: src/.deps/libzmq_la-raw_decoder.Plo: No such file or directory
Makefile:2393: src/.deps/libzmq_la-raw_encoder.Plo: No such file or directory
Makefile:2394: src/.deps/libzmq_la-reaper.Plo: No such file or directory
Makefile:2395: src/.deps/libzmq_la-rep.Plo: No such file or directory
Makefile:2396: src/.deps/libzmq_la-req.Plo: No such file or directory
Makefile:2397: src/.deps/libzmq_la-router.Plo: No such file or directory
Makefile:2398: src/.deps/libzmq_la-select.Plo: No such file or directory
Makefile:2399: src/.deps/libzmq_la-session_base.Plo: No such file or directory
Makefile:2400: src/.deps/libzmq_la-signaler.Plo: No such file or directory
Makefile:2401: src/.deps/libzmq_la-socket_base.Plo: No such file or directory
Makefile:2402: src/.deps/libzmq_la-socks.Plo: No such file or directory
Makefile:2403: src/.deps/libzmq_la-socks_connecter.Plo: No such file or directory
Makefile:2404: src/.deps/libzmq_la-stream.Plo: No such file or directory
Makefile:2405: src/.deps/libzmq_la-stream_engine.Plo: No such file or directory
Makefile:2406: src/.deps/libzmq_la-sub.Plo: No such file or directory
Makefile:2407: src/.deps/libzmq_la-tcp.Plo: No such file or directory
Makefile:2408: src/.deps/libzmq_la-tcp_address.Plo: No such file or directory
Makefile:2409: src/.deps/libzmq_la-tcp_connecter.Plo: No such file or directory
Makefile:2410: src/.deps/libzmq_la-tcp_listener.Plo: No such file or directory
Makefile:2411: src/.deps/libzmq_la-thread.Plo: No such file or directory
Makefile:2412: src/.deps/libzmq_la-tipc_address.Plo: No such file or directory
Makefile:2413: src/.deps/libzmq_la-tipc_connecter.Plo: No such file or directory
Makefile:2414: src/.deps/libzmq_la-tipc_listener.Plo: No such file or directory
Makefile:2415: src/.deps/libzmq_la-trie.Plo: No such file or directory
Makefile:2416: src/.deps/libzmq_la-v1_decoder.Plo: No such file or directory
Makefile:2417: src/.deps/libzmq_la-v1_encoder.Plo: No such file or directory
Makefile:2418: src/.deps/libzmq_la-v2_decoder.Plo: No such file or directory
Makefile:2419: src/.deps/libzmq_la-v2_encoder.Plo: No such file or directory
Makefile:2420: src/.deps/libzmq_la-xpub.Plo: No such file or directory
Makefile:2421: src/.deps/libzmq_la-xsub.Plo: No such file or directory
Makefile:2422: src/.deps/libzmq_la-zmq.Plo: No such file or directory
Makefile:2423: src/.deps/libzmq_la-zmq_utils.Plo: No such file or directory
Makefile:2424: tests/.deps/test_abstract_ipc.Po: No such file or directory
Makefile:2425: tests/.deps/test_bind_src_address.Po: No such file or directory
Makefile:2426: tests/.deps/test_capabilities.Po: No such file or directory
Makefile:2427: tests/.deps/test_conflate.Po: No such file or directory
Makefile:2428: tests/.deps/test_connect_delay_tipc.Po: No such file or directory
Makefile:2429: tests/.deps/test_connect_resolve.Po: No such file or directory
Makefile:2430: tests/.deps/test_connect_rid.Po: No such file or directory
Makefile:2431: tests/.deps/test_ctx_destroy.Po: No such file or directory
Makefile:2432: tests/.deps/test_ctx_options.Po: No such file or directory
Makefile:2433: tests/.deps/test_diffserv.Po: No such file or directory
Makefile:2434: tests/.deps/test_disconnect_inproc.Po: No such file or directory
Makefile:2435: tests/.deps/test_filter_ipc.Po: No such file or directory
Makefile:2436: tests/.deps/test_fork.Po: No such file or directory
Makefile:2437: tests/.deps/test_getsockopt_memset.Po: No such file or directory
Makefile:2438: tests/.deps/test_hwm.Po: No such file or directory
Makefile:2439: tests/.deps/test_hwm_pubsub.Po: No such file or directory
Makefile:2440: tests/.deps/test_immediate.Po: No such file or directory
Makefile:2441: tests/.deps/test_inproc_connect.Po: No such file or directory
Makefile:2442: tests/.deps/test_invalid_rep.Po: No such file or directory
Makefile:2443: tests/.deps/test_iov.Po: No such file or directory
Makefile:2444: tests/.deps/test_ipc_wildcard.Po: No such file or directory
Makefile:2445: tests/.deps/test_issue_566.Po: No such file or directory
Makefile:2446: tests/.deps/test_last_endpoint.Po: No such file or directory
Makefile:2447: tests/.deps/test_many_sockets.Po: No such file or directory
Makefile:2448: tests/.deps/test_metadata.Po: No such file or directory
Makefile:2449: tests/.deps/test_monitor.Po: No such file or directory
Makefile:2450: tests/.deps/test_msg_flags.Po: No such file or directory
Makefile:2451: tests/.deps/test_pair_inproc.Po: No such file or directory
Makefile:2452: tests/.deps/test_pair_ipc.Po: No such file or directory
Makefile:2453: tests/.deps/test_pair_tcp.Po: No such file or directory
Makefile:2454: tests/.deps/test_pair_tipc.Po: No such file or directory
Makefile:2455: tests/.deps/test_probe_router.Po: No such file or directory
Makefile:2456: tests/.deps/test_proxy.Po: No such file or directory
Makefile:2457: tests/.deps/test_proxy_single_socket.Po: No such file or directory
Makefile:2458: tests/.deps/test_proxy_terminate.Po: No such file or directory
Makefile:2459: tests/.deps/test_req_correlate.Po: No such file or directory
Makefile:2460: tests/.deps/test_req_relaxed.Po: No such file or directory
Makefile:2461: tests/.deps/test_reqrep_device.Po: No such file or directory
Makefile:2462: tests/.deps/test_reqrep_device_tipc.Po: No such file or directory
Makefile:2463: tests/.deps/test_reqrep_inproc.Po: No such file or directory
Makefile:2464: tests/.deps/test_reqrep_ipc.Po: No such file or directory
Makefile:2465: tests/.deps/test_reqrep_tcp.Po: No such file or directory
Makefile:2466: tests/.deps/test_reqrep_tipc.Po: No such file or directory
Makefile:2467: tests/.deps/test_router_handover.Po: No such file or directory
Makefile:2468: tests/.deps/test_router_mandatory.Po: No such file or directory
Makefile:2469: tests/.deps/test_router_mandatory_hwm.Po: No such file or directory
Makefile:2470: tests/.deps/test_router_mandatory_tipc.Po: No such file or directory
Makefile:2471: tests/.deps/test_security_curve.Po: No such file or directory
Makefile:2472: tests/.deps/test_security_null.Po: No such file or directory
Makefile:2473: tests/.deps/test_security_plain.Po: No such file or directory
Makefile:2474: tests/.deps/test_shutdown_stress.Po: No such file or directory
Makefile:2475: tests/.deps/test_shutdown_stress_tipc.Po: No such file or directory
Makefile:2476: tests/.deps/test_spec_dealer.Po: No such file or directory
Makefile:2477: tests/.deps/test_spec_pushpull.Po: No such file or directory
Makefile:2478: tests/.deps/test_spec_rep.Po: No such file or directory
Makefile:2479: tests/.deps/test_spec_req.Po: No such file or directory
Makefile:2480: tests/.deps/test_spec_router.Po: No such file or directory
Makefile:2481: tests/.deps/test_srcfd.Po: No such file or directory
Makefile:2482: tests/.deps/test_stream.Po: No such file or directory
Makefile:2483: tests/.deps/test_stream_disconnect.Po: No such file or directory
Makefile:2484: tests/.deps/test_stream_empty.Po: No such file or directory
Makefile:2485: tests/.deps/test_stream_timeout.Po: No such file or directory
Makefile:2486: tests/.deps/test_sub_forward.Po: No such file or directory
Makefile:2487: tests/.deps/test_sub_forward_tipc.Po: No such file or directory
Makefile:2488: tests/.deps/test_system.Po: No such file or directory
Makefile:2489: tests/.deps/test_term_endpoint.Po: No such file or directory
Makefile:2490: tests/.deps/test_term_endpoint_tipc.Po: No such file or directory
Makefile:2491: tests/.deps/test_timeo.Po: No such file or directory
Makefile:2492: tests/.deps/test_unbind_inproc.Po: No such file or directory
Makefile:2493: tests/.deps/test_unbind_wildcard.Po: No such file or directory
Makefile:2494: tests/.deps/test_xpub_nodrop.Po: No such file or directory
Makefile:2495: tools/.deps/curve_keygen.Po: No such file or directory
Makefile:2496: tweetnacl/contrib/randombytes/.deps/libzmq_la-devurandom.Plo: No such file or directory
Makefile:2497: tweetnacl/src/.deps/libzmq_la-tweetnacl.Plo: No such file or directory
make[1]: *** No rule to make target 'tweetnacl/src/.deps/libzmq_la-tweetnacl.Plo'.  Stop.
make[1]: Leaving directory '/root/ntopng/third-party/zeromq-4.1.7'
Makefile:169: recipe for target '/root/ntopng/third-party/zeromq-4.1.7/.libs/libzmq.a' failed
make: *** [/root/ntopng/third-party/zeromq-4.1.7/.libs/libzmq.a] Error 2
`

**Comment by simonemainardi** [comment]
Please, follow https://github.com/ntop/ntopng/blob/dev/doc/README.compilation
install zeromq using the package manager.

**Comment by manjotsc** [comment]
@simonemainardi thanks, I ran **cd packages/ubuntu;./configure;make** and now I am getting this error.

dpkg-buildpackage -rfakeroot -d -us -uc -b
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: info: source package ntopng
dpkg-buildpackage: info: source version 4.1.200408-9788
dpkg-buildpackage: info: source distribution table
dpkg-buildpackage: info: source changed by Luca Deri <deri@ntop.org>
dpkg-buildpackage: info: host architecture amd64
dpkg-buildpackage: warning: debian/rules is not executable; fixing that
 dpkg-source --before-build ubuntu
 fakeroot debian/rules clean
make[1]: Entering directory '/root/ntopng/packages/ubuntu'
dh_testdir
make[1]: dh_testdir: Command not found
debian/rules:22: recipe for target 'clean' failed
make[1]: *** [clean] Error 127
make[1]: Leaving directory '/root/ntopng/packages/ubuntu'
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2
Makefile:46: recipe for target 'ntopng' failed
make: *** [ntopng] Error 2

**Comment by simonemainardi** [comment]
You don't have to create the deb package. Just follow the linked linked instructions and you will be o. Alternatively, install a packaged version from https://packages.ntop.org
