### ISSUE TITLE
Unable to start ntopng 4.0 after install

### ISSUE THREAD

**Issue by sklammer2k** [ntop/ntopng#3718]
Hey Guys,

i just compiled and installed ntopng to my ipfire testsystem. But when i try to start it i get the error message:
[Ntop.cpp:201] ERROR: Unable to open lock file: No such file or directory
Do you have a hint on what i'm missing ?

Greetings 
sklammer2k

**Comment by manjotsc** [comment]
I was having same issue just type sudo ntopng, it will run.

![Annotation 2020-04-08 194843](https://user-images.githubusercontent.com/51430971/78843831-027c1200-79d2-11ea-8f2e-9ea6be3d5080.png)

**Comment by sklammer2k** [comment]
Hey Manjotsc,
thanks for your reply but my problem seems to be different because I don't get a permission error but a file not found error.

**Comment by emanuele-f** [comment]
Fixed. A new build will be available in one hour.
