### ISSUE TITLE
NTOPNG 4.0 can't login

### ISSUE THREAD

**Issue by manjotsc** [ntop/ntopng#3719]
I just installed ntopng 4.0 on Ubuntu when I try to log in the first time using default user and password "admin" login page refreshes and doesn't log in, no error nothing.

**Comment by emanuele-f** [comment]
Please check out https://www.ntop.org/guides/ntopng/faq.html#cannot-login-into-the-gui . If that does not work, try to manually clear the browser cookies.

**Comment by manjotsc** [comment]
@emanuele-f I tried, but login page is looping still..

**Comment by manjotsc** [comment]
fixed I ran this command and I put my own password, "**redis-cli SET user.admin.password qwer1234**"
