### ISSUE TITLE
Ability to add manual subnets for Traffic Filtering

### ISSUE THREAD

**Issue by whoknowz** [ntop/ntopng#372]
We need a way to manually add any subnet to Traffic Filtering. Currently the drop down only supports defined Local Networks and we have to manually select individual hosts to modify filters.

For instance say I want to deny everyone "192.168.1.0/24" Youtube but allow "192.168.1.108/29" everything, I have to now do that from the URL instead of the web interface.

Enhancement perhaps?

**Comment by simonemainardi** [comment]
@whoknowz you can also set Host Traffic Policies from every host details page when you are inline.

**Comment by whoknowz** [comment]
@simonemainardi I am aware of that, but it is difficult to add a range of hosts that fall under the same filter/shaping rules. This feature was present before, see screenshot from ntopng website, notice the "Add Network"

![screen-shot-2015-02-09-at-08 06 12](https://cloud.githubusercontent.com/assets/7417874/12816062/065570ce-cb6c-11e5-8fcb-eb7c02229ca6.png)

**Comment by whoknowz** [comment]
There is also a bug when we do the following for a new host not in the list.
1. Select a host for detail view
2. Select "Modify Host Traffic Policy"
3. Black list a protocol or just click "Set Protocol Policy and Shaper"
4. The policy is applied to the first host/network in the drop down list and not the host selected in step 1.

This only happens first time a specific host is selected for modification, looks like the drop down needs a refresh and entry added before being applied.

**Comment by simonemainardi** [comment]
please check now, features requested have been added and the highlighted bug has been fixed.

![image](https://cloud.githubusercontent.com/assets/3397663/12873563/b5f458a0-cdc0-11e5-9b7c-8574b6683472.png)

let me know if everything works as expected

**Comment by whoknowz** [comment]
@simonemainardi everything works on nightly build, can we have this in stable please.

**Comment by simonemainardi** [comment]
I've just cherry-picked the commit into the 2.2 stable branch. @lucaderi please trigger stable build, thank you.
