### ISSUE TITLE
Ntop and nprobe configuration

### ISSUE THREAD

**Issue by Claireshan** [ntop/ntopng#3724]
Hello all, Can someone please send the basic configuration of ntop and nprobe which are on the same machine coz my has refused to work expected. It doesnt show localhost, and the traffic its graphing is  nor right.

**Comment by Claireshan** [comment]
i have four routers sending to the samplicator where nprobe picks and send to ntop

**Comment by emanuele-f** [comment]
Please check out https://www.ntop.org/nprobe/network-monitoring-101-a-beginners-guide-to-understanding-ntop-tools/
