### ISSUE TITLE
Cannot change password at fresh 4.0 installation

### ISSUE THREAD

**Issue by sonic42** [ntop/ntopng#3725]
The Browser show with release version
...ntopng alerts_api.lua:142: attempt to index a nil value (field 'alert_type')

 ntopng --version
v.4.0.200406    [Community build]
GIT rev:        :4.0.200406
`
and with git version 4.1.200408 the  password change dialog repeats endless again.

**Comment by lucaderi** [comment]
@emanuele-f @simonemainardi Can you please check?

**Comment by emanuele-f** [comment]
Cannot reproduce, please give us more details:

- In ntopng, are you logged in as admin or as the user for which you are trying to change the password?
- Can you post a screenshot of the dialog? Does it show any error?
- Can you post the full ntopng console log?

**Comment by sonic42** [comment]
The admin and admin login works. The change page of 4.0.200406 is ok. After click on "Change password" comes the error:
![ntopng1](https://user-images.githubusercontent.com/30557939/78984185-f012ed00-7b25-11ea-8721-00eb0db825ab.png)
Console Log:
 [LuaEngine.cpp:12646] WARNING: Script failure [/usr/share/ntopng/scripts/lua/change_password.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]

**Comment by sonic42** [comment]
Some other errors repeats all 5-10 seconds:
10/Apr/2020 12:51:00 [minute.lua:11] [alert_consts.lua:216] ERROR: Missing required field 'i18n_title' in
10/Apr/2020 12:51:00 [minute.lua:11] [alert_consts.lua:216] ERROR: Missing required field 'i18n_title' in
10/Apr/2020 12:51:00 [interface.lua:8] [alert_consts.lua:216] ERROR: Missing required field 'i18n_title' in
10/Apr/2020 12:51:00 [system.lua:8] [alert_consts.lua:216] ERROR: Missing required field 'i18n_title' in
10/Apr/2020 12:51:00 [host.lua:8] [alert_consts.lua:216] ERROR: Missing required field 'i18n_title' in
10/Apr/2020 12:51:00 [minute.lua:11] [alert_consts.lua:216] ERROR: Missing required field 'i18n_title' in
10/Apr/2020 12:51:00 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/host.lua] [cannot open /var/nst/ntopng/plugins0/plugins_metadata.lua: No such file or directory]

**Comment by sonic42** [comment]
Full Log:
`10/Apr/2020 12:56:18 [Prefs.cpp:1106] ntopng will use redis 127.0.0.1@5
10/Apr/2020 12:56:18 [Prefs.cpp:939] ERROR: -S deprecated, sticky hosts no longer supported. Configure remote and local hosts idle timeouts from the preferences.
10/Apr/2020 12:56:18 [Ntop.cpp:2229] Setting local networks to 192.168.0.0/16
10/Apr/2020 12:56:18 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@5
10/Apr/2020 12:56:18 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@5
10/Apr/2020 12:56:18 [PcapInterface.cpp:91] Reading packets from green0 [id: 0]
10/Apr/2020 12:56:18 [PcapInterface.cpp:418] Packet capture filter on green0 set to "ip and not ip multicast and not ether broadcast and not (host 192.168.xxx.xxx and port 3001)"
10/Apr/2020 12:56:18 [Ntop.cpp:2334] Registered interface green0 [id: 0]
10/Apr/2020 12:56:18 [PcapInterface.cpp:91] Reading packets from red0 [id: 1]
10/Apr/2020 12:56:18 [PcapInterface.cpp:418] Packet capture filter on red0 set to "ip and not ip multicast and not ether broadcast and not (host 192.168.xxx.xxx and port 3001)"
10/Apr/2020 12:56:18 [Ntop.cpp:2334] Registered interface red0 [id: 1]
10/Apr/2020 12:56:18 [main.cpp:311] PID stored in file /var/run/ntopng.pid
10/Apr/2020 12:56:18 [Geolocation.cpp:150] Running without geolocation support.
10/Apr/2020 12:56:18 [Geolocation.cpp:151] To enable geolocation follow the instructions at
10/Apr/2020 12:56:18 [Geolocation.cpp:152] https://github.com/ntop/ntopng/blob/dev/doc/README.geolocation.md
10/Apr/2020 12:56:19 [HTTPserver.cpp:1331] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
10/Apr/2020 12:56:19 [HTTPserver.cpp:1340] HTTPS server listening on 192.168.xxx.xxx:3001
10/Apr/2020 12:56:19 [Utils.cpp:734] User changed to nobody
10/Apr/2020 12:56:19 [main.cpp:383] Working directory: /var/nst/ntopng
10/Apr/2020 12:56:19 [main.cpp:385] Scripts/HTML pages directory: /usr/share/ntopng
10/Apr/2020 12:56:19 [Ntop.cpp:437] Welcome to ntopng x86_64 v.4.0.200410 - (C) 1998-20 ntop.org
10/Apr/2020 12:56:19 [Ntop.cpp:832] Adding 192.168.0.4/32 as IPv4 interface address for red0
10/Apr/2020 12:56:19 [Ntop.cpp:841] Adding 192.168.0.0/24 as IPv4 local network for red0
10/Apr/2020 12:56:19 [Ntop.cpp:832] Adding 192.168.xxx.xxx/32 as IPv4 interface address for green0
10/Apr/2020 12:56:19 [Ntop.cpp:841] Adding 192.168.xxx.xxx/24 as IPv4 local network for green0
10/Apr/2020 12:56:19 [PeriodicActivities.cpp:104] Started periodic activities loop...
10/Apr/2020 12:56:19 [startup.lua:21] [alert_consts.lua:216] ERROR: Missing required field 'i18n_title' in
10/Apr/2020 12:56:19 [startup.lua:21] [plugins_utils.lua:529] ERROR: Errors occurred while processing plugin 'snmp_topology_change'
10/Apr/2020 12:56:19 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/startup.lua][cannot open /var/nst/ntopng/plugins0/plugins_metadata.lua: No such file or directory]
10/Apr/2020 12:56:19 [PeriodicActivities.cpp:164] Each periodic activity script will use 2 threads
10/Apr/2020 12:56:19 [NetworkInterface.cpp:2343] Started packet polling on interface green0 [id: 0]...
10/Apr/2020 12:56:19 [NetworkInterface.cpp:2343] Started packet polling on interface red0 [id: 1]...
10/Apr/2020 12:56:20 [flow.lua:16] [alert_consts.lua:216] ERROR: Missing required field 'i18n_title' in
10/Apr/2020 12:56:20 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [cannot open /var/nst/ntopng/plugins0/plugins_metadata.lua: No such file or directory]
10/Apr/2020 12:56:20 [flow.lua:16] [alert_consts.lua:216] ERROR: Missing required field 'i18n_title' in
10/Apr/2020 12:56:20 [AlertCheckLuaEngine.cpp:80] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [cannot open /var/nst/ntopng/plugins0/plugins_metadata.lua: No such file or directory]
10/Apr/2020 12:56:21 [housekeeping.lua:14] [alert_consts.lua:216] ERROR: Missing required field 'i18n_title' in
10/Apr/2020 12:56:46 [change_password.lua:27] [alert_consts.lua:216] ERROR: Missing required field 'i18n_title' in
10/Apr/2020 12:56:46 [LuaEngine.cpp:12646] WARNING: Script failure [/usr/share/ntopng/scripts/lua/change_password.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]
^C10/Apr/2020 12:56:50 [main.cpp:50] Shutting down...
10/Apr/2020 12:56:51 [PcapInterface.cpp:339] Terminated packet polling for red0
10/Apr/2020 12:56:51 [PcapInterface.cpp:339] Terminated packet polling for green0
10/Apr/2020 12:56:55 [Ntop.cpp:2427] Terminating periodic activities
10/Apr/2020 12:56:55 [Ntop.cpp:2433] Executing shutdown script
10/Apr/2020 12:56:55 [shutdown.lua:17] [alert_consts.lua:216] ERROR: Missing required field 'i18n_title' in
 string stack traceback:
        /usr/share/ntopng/scripts/lua/modules/alert_utils.lua:100: in function 'alertType'
        /usr/share/ntopng/scripts/lua/modules/alert_utils.lua:2465: in upvalue 'notify_ntopng_status'
        /usr/share/ntopng/scripts/lua/modules/alert_utils.lua:2486: in function 'notify_ntopng_stop'
        /usr/share/ntopng/scripts/callbacks/system/shutdown.lua:22: in main chunk
10/Apr/2020 12:56:55 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/shutdown.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:103: attempt to index a nil value (field '?')]
10/Apr/2020 12:56:56 [ProtoStats.cpp:35] [IPv4]  11.01 KB/81.00 Packets
10/Apr/2020 12:56:56 [ProtoStats.cpp:35] [IPv6]  0 B/0.00 Packets
10/Apr/2020 12:56:56 [ProtoStats.cpp:35] [ARP]   0 B/0.00 Packets
10/Apr/2020 12:56:56 [ProtoStats.cpp:35] [MPLS]  0 B/0.00 Packets
10/Apr/2020 12:56:56 [ProtoStats.cpp:35] [Other] 0 B/0.00 Packets
10/Apr/2020 12:56:56 [Ntop.cpp:2415] Polling shut down [interface: green0]
10/Apr/2020 12:56:56 [ProtoStats.cpp:35] [IPv4]  196 B/2.00 Packets
10/Apr/2020 12:56:56 [ProtoStats.cpp:35] [IPv6]  0 B/0.00 Packets
10/Apr/2020 12:56:56 [ProtoStats.cpp:35] [ARP]   0 B/0.00 Packets
10/Apr/2020 12:56:56 [ProtoStats.cpp:35] [MPLS]  0 B/0.00 Packets
10/Apr/2020 12:56:56 [ProtoStats.cpp:35] [Other] 0 B/0.00 Packets
10/Apr/2020 12:56:56 [Ntop.cpp:2415] Polling shut down [interface: red0]
10/Apr/2020 12:56:56 [Ntop.cpp:2450] Deleted PID /var/run/ntopng.pid: [rc: -1][Permission denied]
10/Apr/2020 12:56:56 [HTTPserver.cpp:1357] HTTP server terminated
10/Apr/2020 12:56:56 [NetworkInterface.cpp:544] Flushing host contacts for interface green0
10/Apr/2020 12:56:56 [NetworkInterface.cpp:2384] Cleanup interface green0
10/Apr/2020 12:56:56 [NetworkInterface.cpp:544] Flushing host contacts for interface red0
10/Apr/2020 12:56:56 [NetworkInterface.cpp:2384] Cleanup interface red0
10/Apr/2020 12:56:56 [AddressResolution.cpp:63] Address resolution stats [3 resolved][1 failures]`

**Comment by sonic42** [comment]
I see in the log, the --data-dir parameter is not more  working correctly in 4.0+ versions. Is /var/lib/ntopng hardcoded? (possible second bug?)

**Comment by sonic42** [comment]
With version 4.1.200408 shows errors only in log and the browser is clean. Log: `[LuaEngine.cpp:12548] WARNING: Script failure [/usr/share/ntopng/scripts/lua/change_password.lua][/usr/share/ntopng/scripts/lua/modules/alerts_api.lua:142: attempt to index a nil value (field 'alert_type')]`

Next error shown:
`10/Apr/2020 13:31:24 [PeriodicActivities.cpp:105] Started periodic activities loop...
10/Apr/2020 13:31:24 [LuaEngine.cpp:12043] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/startup.lua][...0/callbacks/system/snmp_device/lldp_topology_changed.lua:9: module 'snmp_utils' not found:
        no field package.preload['snmp_utils']
        no file '/usr/share/ntopng/scripts/lua/modules/snmp_utils.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/snmp_utils.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/snmp_utils.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/snmp_utils/init.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/snmp_utils.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/snmp_utils.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/snmp_utils.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/snmp_utils.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/snmp_utils.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/snmp_utils.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/custom/snmp_utils.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/schemas/snmp_utils.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/drivers/snmp_utils.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/snmp_utils.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/snmp_utils.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/alert_endpoints/snmp_utils.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/snmp_utils.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/snmp_utils.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/snmp_utils.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/snmp_utils.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/snmp_utils.lua'
        no file '/usr/local/share/lua/5.3/snmp_utils.lua'
        no file '/usr/local/share/lua/5.3/snmp_utils/init.lua'
        no file '/usr/local/lib/lua/5.3/snmp_utils.lua'
        no file '/usr/local/lib/lua/5.3/snmp_utils/init.lua'
        no file './snmp_utils.lua'
        no file './snmp_utils/init.lua'
        no file '/usr/local/lib/lua/5.3/snmp_utils.so'
        no file '/usr/local/lib/lua/5.3/loadall.so'
        no file './snmp_utils.so']`

**Comment by emanuele-f** [comment]
Which linux distribution are you using? The system is into an inconsistent state, please remove everything and install ntopng cleanly from packages.ntop.org .

**Comment by sonic42** [comment]
Im try to compile this for IPfire, an LFS bsaed firewall distribution. The 3.8.1 version of ntopng works. The packages from packages.ntop.org are not usable for this.

**Comment by emanuele-f** [comment]
Please note that we don't officially support such distribution. I suggest you to perform the following steps for a cleanup:

- stop any running ntopng instances
- uninstall all the installed ntopng instances
- delete all the ntopng data: `redis-cli flushall` then `rm -rf /var/lib/ntopng`
- `git pull` the latest nDPI and ntopng source, then compile nDPI first and then ntopng

**Comment by sonic42** [comment]
The last versions nDPI f4c2466 and ntop 81232c2 are now working. `redis-cli flushall` had no effect. Fresh install and update from 3.8.1 are tested. Thanks for your support.

**Comment by emanuele-f** [comment]
You are welcome.
