### ISSUE TITLE
Extend Past Alerts Filtering

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3726]
![Screen Shot 2020-04-10 at 08 58 39](https://user-images.githubusercontent.com/4493366/78970410-84bb2200-7b09-11ea-8df8-c7e9d11ee342.png)

Add the ability to filter alerts per host

**Comment by simonemainardi** [comment]
you have this feature if you go to the host page. I think we should implement the 'resurrect' of in active hosts.

**Comment by simonemainardi** [comment]
This is supported. It suffices to search the host in the search bar. Both if the host is active or inactive (but serialized), the host can be accessed and its alerts browsed.
