### ISSUE TITLE
Nil host pool reported

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3727]
![Screen Shot 2020-04-10 at 09 00 58](https://user-images.githubusercontent.com/4493366/78970544-d5cb1600-7b09-11ea-88c7-a498b3ae858f.png)

Clicking on nil brings to the following error page
![Screen Shot 2020-04-10 at 09 01 07](https://user-images.githubusercontent.com/4493366/78970553-d95e9d00-7b09-11ea-91fa-71ca9161d335.png)

In my case I have no host pools defined
![Screen Shot 2020-04-10 at 09 03 00](https://user-images.githubusercontent.com/4493366/78970664-1fb3fc00-7b0a-11ea-963c-7414f97f6d85.png)

**Comment by simonemainardi** [comment]
Likely related to a delete of the redis database which has canceled all alert ids. Same issue would occur for flow statues stored in nIndex.

Possible solutions:
- create a readme and an automatic script './clean.sh' which deletes redis, the alerts db, and nindex
- Add a reset button from the UI which cleans redis, the alerts db and nindex upon restart.

**Comment by simonemainardi** [comment]
Confirm issue was due to the explanation above. Solved with https://github.com/ntop/ntopng/issues/3752
