### ISSUE TITLE
Invalid alarm reported

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3728]
This is not an alert related to packet drops but it is a score 

![image](https://user-images.githubusercontent.com/4493366/78970993-d9ab6800-7b0a-11ea-8b3c-b79c0c084d94.png)

![Screen Shot 2020-04-10 at 09 05 30](https://user-images.githubusercontent.com/4493366/78971001-dd3eef00-7b0a-11ea-8b7b-6e727060265b.png)

**Comment by simonemainardi** [comment]
very likely, reason is the same as explained in https://github.com/ntop/ntopng/issues/3727#issuecomment-612056247

**Comment by simonemainardi** [comment]
Confirm issue was due to https://github.com/ntop/ntopng/issues/3727#issuecomment-612056247

Solved in https://github.com/ntop/ntopng/issues/3752
