### ISSUE TITLE
Alert drill down is incomplete

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3729]
![Screen Shot 2020-04-10 at 09 40 13](https://user-images.githubusercontent.com/4493366/78973033-52acbe80-7b0f-11ea-9bea-91ad783f0e8c.png)
Not all alerts have a drill down. Note hat everything is enabled here, included nIndex

**Comment by emanuele-f** [comment]
There was a bug in the alert names used to references the alerts. More drilldown links have also been added.
