### ISSUE TITLE
Ability to have schedules for Traffic Filtering

### ISSUE THREAD

**Issue by whoknowz** [ntop/ntopng#373]
Feature request: Ability to have on/off times for Traffic Filtering policies. Say for example I want to disable all "fun" application protocols during 9-17 hrs but allow afterwards. 
Is it possible to do this via cronjob perhaps?

**Comment by whoknowz** [comment]
A little digging around and the following works in a script run by a cronjob (ugly, but works)
1. Copy value from redis db key ntopng.prefs.4.l7_policy somewhere ("4" is interface ID, will be different on each install)
2. Update value to preferred, nil if allow everything
3. Have a Lua script with interface.reloadL7Rules()
4. Have a cron job execute curl --cookie "user=admin; password=admin" "http://127.0.0.1:3000/lua/examples/yourscript.lua?"
5. When enforcing back restrictions have a cron job execute a script that read back and write to redis the previous saved value and run Lua script again

Any ideas to do this more cleanly is welcome

**Comment by simonemainardi** [comment]
implemented host pool quotas to have daily bytes and time caps for each host pool L7 application protocol
