### ISSUE TITLE
Alert disable is cumbersome: we need a whitelist 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3730]
![image](https://user-images.githubusercontent.com/4493366/78973205-b0410b00-7b0f-11ea-8f55-3a7d4c56dbc2.png)

As of today it is possible to disable selected alerts. However this in reality is cumbersome. Ideally it should be possible to disable a specific alert for a set of hosts.

This requires the ability to specify a whitelist (for instance defined in CIDR mode) instead of a single host

**Comment by simonemainardi** [comment]
This is now implemented with the concept of host pools and recipients associated.
