### ISSUE TITLE
Implement alert disable edit panel

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3731]
As of today it is possible to whitelist single alerts for a specific host. However it is not possible to know the list of alert/hosts disabled.

It is requested to allow a use to see such list, so it is possible to enable/disable existing whitelists and to know what alerts are whitelisted

This ticket depends on #3730

**Comment by emanuele-f** [comment]
Please note that a datatable with the disabled alerts is already implemented (see `printDisabledAlerts` in `alert_utils.lua`), however it is not shown (this should be investigated).

**Comment by simonemainardi** [comment]
after the introduction of notification-based pools, this ticket no longer applies.
