### ISSUE TITLE
Alert drilldown sometime leads to empty pages

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3733]
![image](https://user-images.githubusercontent.com/4493366/78973898-1712f400-7b11-11ea-9d36-d0001b883846.png)

This is a example 
http://localhost:3000/lua/host_details.lua?epoch_end=1583432402&page=historical&epoch_begin=1583428802&ifid=5&host=XXXXX&ts_schema=host%3Ascore&detail_view=status_overview

**Comment by simonemainardi** [comment]
Broken alert ids may have led you to the wrong link. Please, check if issue is solved after the fix in https://github.com/ntop/ntopng/issues/3752

**Comment by lucaderi** [comment]
![Screen Shot 2020-04-16 at 22 52 57](https://user-images.githubusercontent.com/4493366/79505689-0b558f00-8035-11ea-901a-2e4c0b7bd159.png)
Drilldown button disappeared: can't check anymore (nIndex is enabled).  (build of v.4.1.200416)

**Comment by emanuele-f** [comment]
The drilldown is only avaiable for certain alerts (see `nv_graph_utils.getAlertGraphLink`) when a related chart/nIndex series can be shown. It is not supported for the "Suspicious Device Protocol" since we don't have mac address information in nIndex nor the application timeseries for L2 devices.

**Comment by simonemainardi** [comment]
empty also the end time

![image](https://user-images.githubusercontent.com/3397663/79750156-c0779800-8310-11ea-8d7c-0712233f3d91.png)

**Comment by simonemainardi** [comment]
clicking on 

![image](https://user-images.githubusercontent.com/3397663/79750578-7a6f0400-8311-11ea-9bde-064b808335e1.png)

yields the empty page (no console errors)

![image](https://user-images.githubusercontent.com/3397663/79750617-8bb81080-8311-11ea-89e9-46ae431c170c.png)

**Comment by simonemainardi** [comment]
becomes empty when the time is in the future with reference to now.

**Comment by simonemainardi** [comment]
empty datetimepicker fixed

**Comment by emanuele-f** [comment]
Other missing `ts_utils.exist` checks added. Please note that the logic which shows the drilldown icon (`ts_utils.exist`) does not take into the time range. It shows the icon as soon as the corresponding RRD exists.

**Comment by emanuele-f** [comment]
Closed as internally acknowledged .
