### ISSUE TITLE
Alert drill down (when working) leads to incomplete pages

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3734]
Ae specified in #3733 sometimes alert drill down leads to empty pages. When working there are other problems

- the drilldown is not centred (in terms of time) with respect to the alert reported
- sometime the info is missing or incomplete (see #3733 )
- sometime they report unexpected information

Below there is an example of drill down that has this problem

Delected Alerts->past alerts

Drilldown  produces
Flow Status			Flows Count
Normal				187
Unidirectional UDP Traffic	46
in timestamp 12:03:00-12:08:00	 

Click on "Normal" -> total flows graph is empty

The the table reports a DNS quesry
Protocol	Client			Server			Application	First Seen	Last Seen	Packets	Throughput	Total Bytes	Info
UDP		10.200.1.46:54551	137.1.2.3	Office365	12:03:12	12:03:12	2	2.29 kbit/s	286 Bytes	 

But the DNS query performed is missing. The normal activity is in the time interval  11:36:06-12:04:15 (#3732 )

The click on  "Unidirectional UDP Traffic" -> grafico total misbehaving flows empty.

**Comment by simonemainardi** [comment]
Please check if, apart from the time, other issues have been solved after https://github.com/ntop/ntopng/issues/3752

**Comment by lucaderi** [comment]
As reported in #3733  the drill down button is gone (build of v.4.1.200416)

**Comment by emanuele-f** [comment]
I can see that the query begin timestamp is sometime shifted after drilling down on the flow status, this must be fixed

**Comment by emanuele-f** [comment]
Did some other experiment and the found out that the shift occurs only when the end time collides with the current time, so this is ok. Here is an example:

```
[From the drilldown link]
Page:
epoch_begin=1587387095
epoch_end=1587390695

get_nindex_flows.lua:
epoch_begin=1587387095
epoch_end=1587388936 (epoch_end is shifted because of the current time)

[After clicking the "Normal" status link]
Page:
epoch_begin=1587387095
epoch_end=1587388936

get_nindex_flows.lua:
epoch_begin=1587387095
epoch_end=1587388936
```

So the page behaves as expected. So, other than the issues outlined in #3733, I think the page works correctly now.

**Comment by emanuele-f** [comment]
Closing as internally acknowledged .
