### ISSUE TITLE
Refactor JS Code

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3735]
Same as #3720 JS code needs to be refactored as follows (this is just an example). Define a class (the JS name must be classname.js), define static methods and call them as shown below.

This means that you have to refactor https://github.com/ntop/ntopng/blob/dev/httpdocs/js/ntopng_utils.js and adapt the calls

class NtopUtils {
    static fbits() {}
}

NtopUtils.fbits();

**Comment by simonemainardi** [comment]
Refactoring done:

- Implemented class NtopngUtils in https://github.com/ntop/ntopng/commit/e61f9ffe68f3a46ee26a2748ca571ce7434b281a
- Refactored NtopngUtils into NtopUtils in https://github.com/ntop/ntopng/commit/1ae2b2d93262b82155fbe377f0cbb80795b0e6a5
- Moved `String.prototype` function to separate file in https://github.com/ntop/ntopng/commit/3b2bbc2aa468b271aa1d51e541bfa1c273f84b14
- Added static `REGEXES` member in https://github.com/ntop/ntopng/commit/f493a9f70d9c2cd173d06145672bd79111c05516
