### ISSUE TITLE
Too many subinterfaces defined 

### ISSUE THREAD

**Issue by notpixxl** [ntop/ntopng#3736]
Solution given. No feedback received. Closing. Reopen with the requested information if necessary.

_Originally posted by @simonemainardi in https://github.com/ntop/ntopng/issues/3670#issuecomment-609924292_

**Comment by notpixxl** [comment]
Hi,
Sorry for my late feedback, have just update my nprobe licence that is "out of maintenance" now it's ok. So now my problem is still the same : Too many subinterfaces defined and my metrics definitely flat :-(

Can you please tell me how can i spawn 2 nprobe instances ? Have to configure a new listening port ? if i do it i have to change the configuration of ~25 of my nflow routers (wich'll be hard because i don't have the management of those) ?

my nprobe configuration file look like this for now:

```
--zmq="tcp://*:5556"
--collector-port=2055
-n=none
-i=none
-T="@NTOPNG@"
--verbose=1
--online-license-check
```

**Comment by simonemainardi** [comment]
create two nprobe configuration files

```
nprobe-c1.conf:
--zmq="tcp://*:5556"
--collector-port=2055
<other options>

nprobe-c2.conf:
--zmq="tcp://*:5557"
--collector-port=2056
<other options>
```
start them:

```
systemctl start nprobe@c1
systemctl start nprobe@c2
```

edit ntopng conf to receive from two endpoints:

```
-i tcp://127.0.0.1:5556
-i tcp://127.0.0.1:5557
```

And yes a change on the routers conf is needed.

**Comment by notpixxl** [comment]
Ok thank you for your response will try to do it, you can close the issue think it respond to my question and i'll not make the change now.
