### ISSUE TITLE
Active Flows: No Results Found when drilling down from a Host

### ISSUE THREAD

**Issue by brianjmurrell** [ntop/ntopng#374]
When I drill down into Flows from a host (i.e. http://server:3000/lua/host_details.lua?ifname=0&host=10.75.22.37&page=flows) it always says No Results Found, however that same host shows active flows at the top level Flows (http://server:3000/lua/flows_stats.lua) page.

Is this expected?

**Comment by simonemainardi** [comment]
are you using the latest dev version? there was a known bug in older releases that was affecting some builds.

**Comment by whoknowz** [comment]
The stable version needs to have this issue resolved, we can't be running dev on production cause dev itself has other issues. I am not sure, but the fix requires a recompile right? Not a simple Lua script fix?

**Comment by brianjmurrell** [comment]
This.

Stable versions of software need to have bug fixes applied to them periodically (sooner than later, more frequently than infrequent) or they defy the definition of stable.

**Comment by lucaderi** [comment]
@simonemainardi if this bug has been fixes on dev it must be ported to stable. Please check

**Comment by simonemainardi** [comment]
I have cherrypicked the fix to the 2.2-stable branch (https://github.com/ntop/ntopng/commit/f46b07653eb22472052835dcb73ea260794ea8d9). Packages are being rebuilt.

**Comment by brianjmurrell** [comment]
How long do packages take to show up in the stable repos?  http://packages.ntop.org/centos-stable/7Server/x86_64/Packages/ still has ntopng-2.2.160129-693.x86_64.rpm from Jan. 29.

**Comment by simonemainardi** [comment]
@cardigliano could you please check if the ntopng stable build has been triggered for centos? thank you

**Comment by simonemainardi** [comment]
i've just checked and the latest stable builds include this fix now.
