### ISSUE TITLE
[RTT] HTTP parameters lint for Active Monitoring

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3740]
Currently, parameter validation is done in http_lint.lua. For the rtt plugins, validation of its parameters should be moved inside the plugin, otherwise, adding new measurement would require global modifications

**Comment by emanuele-f** [comment]
Note: the backend support for custom http_lint is already implemented.

**Comment by emanuele-f** [comment]
Implemented in f94f784c0fa821f4bc0c2d9330237571fbcf80f4
