### ISSUE TITLE
Active monitoring needs refactoring

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3741]
Active monitoring is half way and needs refactoring.
- Move plugins/rtt -> plugins/active_monitoring
- Remove all references to rtt (e.g. rtt_stats.lua has to be renamed)
- Rename rtt_stats.lua to active_monitoring.lua
- Suppose to do the above things, in the "System" menu will appear two items. Why?
- Alerts have hardcoded measurement units. As you can see the measurement unit is not honoured and msec is used
![Screen Shot 2020-04-11 at 11 38 53](https://user-images.githubusercontent.com/4493366/79040482-1188dd00-7be9-11ea-8461-394fd580212a.png)
- The same applies to charts
![Screen Shot 2020-04-11 at 11 40 02](https://user-images.githubusercontent.com/4493366/79040503-38dfaa00-7be9-11ea-9925-7c64a82ff6ed.png)
Note that the bottom of the graph has correct values
![Screen Shot 2020-04-11 at 11 40 39](https://user-images.githubusercontent.com/4493366/79040511-5280f180-7be9-11ea-8c0c-c114c4f7bdfa.png)
- It must be introduced the concept of singleton, that means only one plugin measurement can be enabled at time. This is because it makes no sense (actually it slows down the network). So at most (for speediest but this has to be a plugin parameter) there should be one measurement defined at time
- Inside speediest.lua there is a comment that says "The granularities allowed for the probe. See supported_granularities in rtt.lua" however there is no supported_granularities in rtt.lua
- It is not possible to define a daily granularity
- Would it be possible to dump multiple timeseries such as upload and latency?

**Comment by simonemainardi** [comment]
> Suppose to do the above things, in the "System" menu will appear two items. Why?

Fixed in https://github.com/ntop/ntopng/commit/32b5cecf7d0777792a0ac85b96731f0eb2fb1f1f

> Move plugins/rtt -> plugins/active_monitoring
> Remove all references to rtt (e.g. rtt_stats.lua has to be renamed)
> Rename rtt_stats.lua to active_monitoring.lua

Addressed in https://github.com/ntop/ntopng/commit/3e14bc30f88ea0ff1b52c0bcc051052835988da9

**Comment by simonemainardi** [comment]
Additional issues connected to the active monitoring plugin that must be addressed:

- timeseries created by the plugin are hardcoded in `rrd.lua` and in `nv_graph_utils`. No plugin timeseries have to be hardcoded there
- A javascript active_monitoring_utils.js is present under `httpdocs`. This is plugin-specific and it must stay under the plugin directory
- An `active_monitoring_utils` is present under `modules`. This is plugin-specific and it should stay in the plugin directory

**Comment by emanuele-f** [comment]
Hardcoded timeseries in ts_utils:delete in rrd.lua fixed in 62d1ad69db5b2738bea53baad4ed6ed8d0f44c2a . The remaining hardcoded paths in rrd.lua are necessary to provided backward RRD name compatibility (see getRRDName).

**Comment by emanuele-f** [comment]
Remaining requests implemented in 0ad1b6551240562a7f4f497c33fc04b0ac123248
