### ISSUE TITLE
Refactor RTT code

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3742]
The file ntopng/scripts/plugins/rtt/web_gui/rtt_stats.lua is a mix of template and non-template code. This needs to be harmonised and hardcoded HTML must disappear.

**Comment by simonemainardi** [comment]
note that any template file should go under the plugin directory and not under httpdocs. In other words, plugins must support templates.

**Comment by emanuele-f** [comment]
Template support added in 0ad1b6551240562a7f4f497c33fc04b0ac123248 . See `plugins_utils.renderTemplate`

**Comment by lucaderi** [comment]
@emanuele-f While @gabryon99 will handle the GUI you need to cleanup the code (get_active_monitoring_hosts.lua and active_monitoring_utils.lua etc)
- still reference rtt. Example active_monitoring_host.max_rtt -> active_monitoring_host.threshold
- last_measure -> last_measurement
and so on. RTT as keyword must disappear as this sia a generic module not only for RTT

**Comment by emanuele-f** [comment]
Code cleanup performed in 0be2da4f578af30ea2bb3013a4207714413f41a4 . Now only the GUI cleanup is needed.

**Comment by simonemainardi** [comment]
Addressed in https://github.com/ntop/ntopng/pull/3929
are-you-sure will be handled as part of https://github.com/ntop/ntopng/issues/3861
