### ISSUE TITLE
[RTT] Improve active monitoring enabled/disable

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3745]
When the active monitoring script is disabled
![Screen Shot 2020-04-14 at 08 23 14](https://user-images.githubusercontent.com/4493366/79192624-5ac76f80-7e29-11ea-9f38-65660c1adfe3.png)
the menu entry for active monitoring is missing 
![Screen Shot 2020-04-14 at 08 23 01](https://user-images.githubusercontent.com/4493366/79192628-5c913300-7e29-11ea-8e93-b83cff56c453.png)
This is a bad practice as it is not simple to understand what is the root cause of the lack of active monitoring.

It is requested, when the active monitoring script is disabled, to still show the active monitoring page but to add an alert on the page a message similar to

![Screen Shot 2020-04-14 at 08 26 27](https://user-images.githubusercontent.com/4493366/79192782-aa0da000-7e29-11ea-907f-aa74ac9fed9d.png)

That contains a direct link to enable the script.

**Comment by simonemainardi** [comment]
Rather than allowing the user to perform a useless action, i.e, click on the menu and end up in a 'no results found', I would simply prevent the 'Active Monitoring' script from being disabled.

**Comment by emanuele-f** [comment]
Implemented in aab41dd66eff62418d460a0214bb02da58a05ef5
