### ISSUE TITLE
Missing back button in scripts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3747]
![Screen Shot 2020-04-14 at 08 23 33](https://user-images.githubusercontent.com/4493366/79193043-24d6bb00-7e2a-11ea-8fc1-849d8d1f5a49.png)

In user scripts page there is no back button making unfeseable to go back to the script page. This has to be added and likely remove /plugins/ from the title

**Comment by gabryon99** [comment]
Fixed. https://github.com/ntop/ntopng/commit/1e5376da95e5df333ee4613813a80220035dc49b
