### ISSUE TITLE
RRD archives are not removed after updates

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3749]
When active monitoring hosts are modified/deleted, the existing timeseries must be deleted and the disk space reclaimed

$ pwd
/var/lib/ntopng/-1/rrd/rtt_host
$ ls -l
total 0
0 drwx------  3 deri  wheel   96 Mar 23 17:44 192/
0 drwx------  3 deri  wheel   96 Mar 19 20:54 8/
0 drwx------  3 deri  wheel   96 Mar 20 18:32 i7-2/
0 drwx------  3 deri  wheel   96 Apr 11 11:33 speedtest/
0 drwx------  4 deri  wheel  128 Mar 21 16:00 www/

**Comment by emanuele-f** [comment]
Fixed in 4bd04e7e4c82e58d3f850400d6aeefd4d2e3603e
