### ISSUE TITLE
-F db value out of range

### ISSUE THREAD

**Issue by brianjmurrell** [ntop/ntopng#375]
I'm using ntopng 2.2.160118 from the [ntop repository](http://packages.ntop.org/centos-stable/7).

I was interested in dumping the flows to a database and wanted the low overhead of a local sqlite database.  I had gathered that using `-F db` would do that, however `ntopng` complains to me:

```
# ntopng -F db
29/Jan/2016 09:59:17 [Prefs.cpp:689] WARNING: Discarding -F db: value out of range
```

Am I misunderstanding something?

**Comment by alberk8** [comment]
Hi,

The -F db only works with MySQL or MariaDB.

**Comment by brianjmurrell** [comment]
But the manpage says that to use MySQL you use `mysql` not `db`:

```
Example -F "mysql;localhost;ntopng;flows-%Y.%m.%d;root;".
```

Is there not a way to use a more lightweight/instantaneous database than the hassle of MySQL/MariaDB with it's required installation and up-front configuration (i.e. creating database and user) overhead?

**Comment by lucaderi** [comment]
@brianjmurrell What do you want to do exactly?

**Comment by brianjmurrell** [comment]
I (think) I want to write flows to disk the way -F does.  I just don't want to go to the effort of standing up a MySQL server to do it.

**Comment by lucaderi** [comment]
This is not supported, but you can extend ntopng and send us a code contribution.
