### ISSUE TITLE
[RTT] Invalid notes for active monitoring

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3750]
![Screen Shot 2020-04-14 at 08 47 31](https://user-images.githubusercontent.com/4493366/79194289-9b74b800-7e2c-11ea-993c-1edcd3dafe7f.png) 

the above notes are valid only for RTT measurement. They have to be moved to the documentation, add the help button and put a limited note (short in size)

**Comment by emanuele-f** [comment]
Notes updated in a5709eadd34571768d6cd729d23d761b4caccb73 . Docs need to be updated
