### ISSUE TITLE
apt Install ntopng-data fails on RaspberryPi

### ISSUE THREAD

**Issue by matwho** [ntop/ntopng#3753]
When running "sudo apt install ntopng-data" on RaspberryPi 4 new install of OS, I get:

"The following packages have unmet dependencies:
 ntopng-data : Depends: geoipupdate but it is not installable
E: Unable to correct problems, you have held broken packages"

**Comment by simonemainardi** [comment]
geoipupdate is not available on pi and package `ntopng` no longer depends on ntopng-data.

Follow https://github.com/ntop/ntopng/blob/dev/doc/README.geolocation.md#using-geolocation-when-ntopng-data-is-not-available

**Comment by simonemainardi** [comment]
Response to question given. Closing.

**Comment by ghost** [comment]
https://packages.ntop.org/apt-stable/20.04/x64/
Dependency problem.
There are two versions in the repository

**Comment by cardigliano** [comment]
@Dgraf1201 we are working on the repo, however the one you linked is Ubuntu 20 on x86, the raspberry repo is https://packages.ntop.org/RaspberryPI/
