### ISSUE TITLE
nEdge VLAN trunks doesn't passthrough

### ISSUE THREAD

**Issue by whoknowz** [ntop/ntopng#3756]
When passing tagged multiple VLANs through the bridge mode nEdge doesn't pass traffic.
In a virtual machine either with PCI passthrough or vSwitch ports are same.
Same VM configured with standard linux bridge works fine on both scenarios.
Installation of nEdge breaks standard linux bridge functionality, uninstallation of nEdge doesn't help either.

**Comment by emanuele-f** [comment]
We are already providing support via email, please don't double post.
