### ISSUE TITLE
Unable to delete alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3757]
![Screen Shot 2020-04-14 at 21 37 41](https://user-images.githubusercontent.com/4493366/79266658-348ce880-7e98-11ea-993d-884287bdb485.png)

14/Apr/2020 21:36:44 [LuaEngine.cpp:12594] WARNING: Script failure [/Users/deri/network/ntopng/scripts/lua/get_alerts_table_data.lua][...deri/network/ntopng/scripts/lua/modules/format_utils.lua:192: attempt to perform arithmetic on a nil value (local 'epoch')]

**Comment by simonemainardi** [comment]
Page was broken due to a redis flush which caused alert ids to become invalid. Alerts with invalid ids, in turn, broke the page when trying to generate it. Now alert ids are constant so redis flushes won't affect them https://github.com/ntop/ntopng/issues/3752
