### ISSUE TITLE
[Alerts Aggregation] Invalid alert aggregation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3759]
![Screen Shot 2020-04-14 at 22 30 56](https://user-images.githubusercontent.com/4493366/79271173-a9175580-7e9f-11ea-827e-5fb509418143.png)

**Comment by simonemainardi** [comment]
what is invalid? note that aggregation of similar alerts is done if alerts are within 5 minutes one from the other. please explain.

**Comment by simonemainardi** [comment]
Issue is the same as #3780.
