### ISSUE TITLE
MACS: all are 00:00:00:00:00:00

### ISSUE THREAD

**Issue by scdit46** [ntop/ntopng#3766]
In ntop v4 all MACS displayed are 00:00:00:00:00:00

Is normal?

**Comment by lucaderi** [comment]
Do you collect flows or packets?

**Comment by scdit46** [comment]
Flows

**Comment by simonemainardi** [comment]
default template include mac addresses, if you are using a custom template, you need to make sure it contains SRC and DST mac addresses

**Comment by scdit46** [comment]
When I have configured the local network is solved!
