### ISSUE TITLE
[RTT] Fix chart label

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3768]
The label show `Millis_rtt`, this should be fixed

**Comment by emanuele-f** [comment]
Fixed in a3ff00584a1c3e2c2c1cc6bedb19f7554ed8c977

**Comment by simonemainardi** [comment]
can you rename the variables rtt with active monitoring? I mean it is ok to have rtt for icmp and http, but not for speedtest

**Comment by simonemainardi** [comment]
Label changed as expected. Rename done as well
