### ISSUE TITLE
Dashboard: Talkers with firefox hangs with script error 

### ISSUE THREAD

**Issue by DigiAngel** [ntop/ntopng#377]
Topic says it...new install...I only see this behaviour with firefox, both on Windows and Linux.  Going to Dashboard: Talkers gets me:

![screenshot from 2016-02-04 18 04 00](https://cloud.githubusercontent.com/assets/947191/12835396/f785e51e-cb6c-11e5-94a5-67e84e829ebe.png)

I see this issue with Internet Explorer with a popup of "192.168.1.7 is not responding due to long running script".  Any way to debug this?  Thank you.

**Comment by simonemainardi** [comment]
need extra information to reproduce. Please post ntopng version, linux distribution, url that hangs. Also try to "debug script" and post the output.

**Comment by DigiAngel** [comment]
Thanks....I thought about that after I posted that I didn't include much detail...sorry about that.  Linux distro is Ubuntu 14.04 Server 64 bit, ntop version is:

```
v.2.3.160204 [Community Edition]
GIT rev:   dev:cb714019c7ff9436dc17644c19e01a0bae70dea3:20160204
```

and now I can't get into the interface, but it's just the main flows page when you start it up.

**Comment by simonemainardi** [comment]
can't reproduce with
- FF 41.0.2 and
- 3.16.0-51-generic 14.04.1-Ubuntu SMP x86_64 GNU/Linux

please try to use the FF debugger and see if you can get some additional hints. Is your network heavily loaded?

**Comment by DigiAngel** [comment]
Heh...this is on a home test box with practically no traffic :)  Here's the complete build data:

```
sudo apt-get install autoconf automake
sudo apt-get install libtool
sudo apt-get install libcurl4-openssl-dev
sudo apt-get install libsqlite3-dev
sudo apt-get install libgeoip-dev
sudo apt-get install libmysqlclient-dev
sudo apt-get install libxml2 libxml2-dev
sudo apt-get install redis-server

git clone https://github.com/ntop/nDPI.git
sh autogen.sh
./configure --prefix=/opt/ndpi
make
sudo make install

git clone https://github.com/ntop/ntopng.git
sh autogen.sh
./configure --prefix=/opt/ntop
make
sudo make geoip install

sudo ntop -n 2 -i eth0 -d /opt/ntop/var -m 192.168.1.0/24,71.39.117.84 -U www-data
```

I can't seem to get back into it even after resetting the admin pass with redis, so I'll try later today or during this weekend....unless you know a trick to reset the password.  Thanks.

**Comment by DigiAngel** [comment]
Well after doing the latest git pull this is now longer an issue...good job and thank you :)
