### ISSUE TITLE
Missing last measured point from graph and invalid measurement unit in graph

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3772]
![Screen Shot 2020-04-15 at 19 07 03](https://user-images.githubusercontent.com/4493366/79366356-59db2e80-7f4c-11ea-9d5e-fdec4eb66270.png)
![Screen Shot 2020-04-15 at 19 04 22](https://user-images.githubusercontent.com/4493366/79366360-5c3d8880-7f4c-11ea-9bc8-efe38d755279.png)
![Screen Shot 2020-04-15 at 19 10 46](https://user-images.githubusercontent.com/4493366/79366631-d706a380-7f4c-11ea-91ac-81009acd53e0.png)

**Comment by simonemainardi** [comment]
- Unit of measure fixed in https://github.com/ntop/ntopng/commit/a3ff00584a1c3e2c2c1cc6bedb19f7554ed8c977
- now the first point is no longer missing but it seems the first point is duplicated, yielding to non-existing point drawn https://github.com/ntop/ntopng/issues/3788
