### ISSUE TITLE
[RTT] Sort not working in Active Monitoring page

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3773]

**Comment by emanuele-f** [comment]
Fixed in edd119ce6187589f1a8886de2ebc9d90833b0f09

**Comment by simonemainardi** [comment]
not working:

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/3397663/79464671-a8df9d00-7ffa-11ea-8d07-bc6fd042021e.png">


<img width="1177" alt="image" src="https://user-images.githubusercontent.com/3397663/79464685-ada45100-7ffa-11ea-98f4-9de250fa195a.png">

**Comment by emanuele-f** [comment]
Sorting on such column has been removed in 0b6ba8edd009779ef478ffeb7a4daa9648169726 as discussed. The commit also includes a fix for the numeric values sort as explained in https://datatables.net/forums/discussion/58037/how-to-sort-a-rendered-numeric-column .
