### ISSUE TITLE
[RTT] Add ability to filter by measurement

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3774]
The Active Monitoring page mixes multiple measurements into a single page (e.g. ICMP and HTTP). It is requested to add a dropdown to the datatable to filter only a specific measurement type (e.g. only show ICMP measurements).

**Comment by gabryon99** [comment]
The dropdown filter has been add: https://github.com/ntop/ntopng/commit/025a13f338dfe7998d96e5f8475f3c7ad249a0e4
