### ISSUE TITLE
Add OEM mode

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#3775]
Add an OEM mode (checking the presence of a custom logo and setting a redis key should work) in order to:
- Disable automatic updates from the ntop repo
- Disable the ntop's blog post updates

**Comment by benjamingroeber** [comment]
Hi!

Would it be possible to also not show the telemetry banner on the landing page when OEM mode is active?
![image](https://user-images.githubusercontent.com/6244046/79423466-f4745580-7fbe-11ea-9d67-47329fbc6686.png)

Also I feel like the Remote Assistance feature should not be available in an OEM deployment.

**Comment by simonemainardi** [comment]
currently, function `ntop->getPro()->is_oem()` is used to determine if in oem or not. maybe you need to expose it to lua

**Comment by cardigliano** [comment]
ntop->getPro()->is_oem() is supported by nedge only atm, we need to extend it to ntopng and expose it to Lua

**Comment by lucaderi** [comment]
@cardigliano Hide  "last log trace" in the "system status" menu

**Comment by cardigliano** [comment]
Implemented
