### ISSUE TITLE
Invalid time drill down on alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3776]
![Screen Shot 2020-04-15 at 21 25 54](https://user-images.githubusercontent.com/4493366/79379800-be53b900-7f5f-11ea-85a4-bcc256de4101.png)
![Screen Shot 2020-04-15 at 21 26 04](https://user-images.githubusercontent.com/4493366/79379805-c0b61300-7f5f-11ea-8969-45d73d80acd0.png)
As you can see I would expect a zoom from 19:05 to 21:27

**Comment by emanuele-f** [comment]
Fixed in 6f2f9b223f751e1aa8cf6609f742d145df1ec080

**Comment by simonemainardi** [comment]
this doesn't work for me.

![image](https://user-images.githubusercontent.com/3397663/79490482-38964300-801d-11ea-9767-d4731a92047b.png)


Clicking on a drilldown button gives me a page without end date (this happens sopradically)

![image](https://user-images.githubusercontent.com/3397663/79490147-b73eb080-801c-11ea-9c2c-359c1d7d5f71.png)

going back and re-click gives result but the time is not centered with the one of the alert - basically it brings me to `now` 

![image](https://user-images.githubusercontent.com/3397663/79490830-c70ac480-801d-11ea-825b-832833c91cb4.png)

**Comment by emanuele-f** [comment]
The drilldown logic shows at least 1 hour interval, centered on the alert time. The chart is not centered because the right bound is cut at the "now" timestamp. Please explain the proposed changes.

**Comment by simonemainardi** [comment]
behavior is OK now
