### ISSUE TITLE
Error with missing lua scripts when starting ntopng

### ISSUE THREAD

**Issue by sklammer2k** [ntop/ntopng#3786]
Hey guys,
i compiled ntopng for use on ipfire. The Compilation was successful and the redis-server is runing. When I start ntopng using ntopng -i INTERFACENAME 
I get the following error:

16/Apr/2020 10:15:37 [LuaEngine.cpp:12095] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/usr/share/ntopng/scripts/lua/modules/locales_utils.lua:5: module 'i18n' not found:
        no field package.preload['i18n']
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/timeseries/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n/i18n.lua'
        no file '/usr/share/ntopng/scripts/lua/modules/i18n.lua'
        no file '/usr/local/share/lua/5.3/i18n.lua'
        no file '/usr/local/share/lua/5.3/i18n/init.lua'
        no file '/usr/local/lib/lua/5.3/i18n.lua'
        no file '/usr/local/lib/lua/5.3/i18n/init.lua'
        no file './i18n.lua'
        no file './i18n/init.lua'
        no file '/usr/local/lib/lua/5.3/i18n.so'
        no file '/usr/local/lib/lua/5.3/loadall.so'
        no file './i18n.so']

The ntopng sems to run but it repeats this error. Am I missing something?

Greetings

sklammer2k

**Comment by emanuele-f** [comment]
It seems like ntopng is not properly installed. What is the expected installation path in your system?

**Comment by lucaderi** [comment]
Sorry we have no knowledge of ipfire. Please try to reproduce the issue with a platform we support (e.g. ubuntu) and we'll assist. The bug however is clear 'module 'i18n' not found:' so the installation is the problem
