### ISSUE TITLE
[RTT] Speedtest: non-existing initial point drawn

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3788]
After adding speedtest, as soon as the FIRST measure is performed, two points appear in the chart, and the first one doesn not exist in reality (is it a pad?)

In the image show, the only measure which exists is at 22:10, at 22:00 no point or measure exists but a point appears in the chart (and is equal to the actual measure at 22:10) 

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/3397663/79501960-3a690200-802f-11ea-88f1-a75e4d9ea09b.png">

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/3397663/79502068-62f0fc00-802f-11ea-9a64-4b5d7f749c9c.png">

**Comment by emanuele-f** [comment]
The duplicate point was caused by a bad RRD creation timestamp, now fixed in fdadaca950003a198ce151e2dbde445ae7c8bd44 . The first 0 point is present in all the charts since NaN RRD values are replaced with 0. I'm checking if it's possible to pass NaN values to the charts without breaking them.

**Comment by emanuele-f** [comment]
![2020-04-17_11-46](https://user-images.githubusercontent.com/5488003/79556256-594bb080-8090-11ea-9f46-30570a3f27db.png)

The desired behaviour for the first 0 point can be accomplished by setting `fill_value=0/0` in `ts_utils.getQueryOptions` as shown in the picture above. However, this breaks some charts (e.g. itnerface top applications) and have many potential impacts on other charts, potentially breaking a lot of things. I would postpone such change.

**Comment by simonemainardi** [comment]
double initial point fixed.
