### ISSUE TITLE
[RTT] Speediest alarms are not generated

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3789]
![Screen Shot 2020-04-16 at 22 40 38](https://user-images.githubusercontent.com/4493366/79504713-9c2b6b00-8033-11ea-859c-ee875f67fca3.png)
![Screen Shot 2020-04-16 at 22 40 51](https://user-images.githubusercontent.com/4493366/79504720-9f265b80-8033-11ea-8996-af54ccb7bf4f.png)
As you can see the threshold is 100 Mbit, measurement is ~50 Mbit and no alert is generated

**Comment by emanuele-f** [comment]
Fixed in 35be58ede970e1e2daaa7e2d50e7df7fba67c1ed
