### ISSUE TITLE
[RTT] Traffic graphs are invalid

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3791]
![Screen Shot 2020-04-17 at 08 36 37](https://user-images.githubusercontent.com/4493366/79539474-afb3f180-8086-11ea-9199-119a2399b904.png)
After the recent changes, the traffic charts have now a different bug. As you can see the first point is non zero, but it is depicted as zero

**Comment by emanuele-f** [comment]
Can you provide the raw data by clicking on the chart icon?

![2020-04-17_11-03](https://user-images.githubusercontent.com/5488003/79552233-47ffa580-808a-11ea-8a29-639e3dac1d17.png)

The value reported into the chart is 85 bit/s so it is normal that it is very near to 0 as the scale is in the order of mbits

**Comment by emanuele-f** [comment]
The issue is related to the fact that we have changed the timeseries format from "mbits" to "bits", so before the nightly update the old mbit value is being reported.

**Comment by emanuele-f** [comment]
In 0968c7b984ece817855d32f170a94634087c1c23 the timeseries has been renamed, so the old data is now discarded. This fixes the current issue.

**Comment by simonemainardi** [comment]
after the update, with speedtest already configured, I got this.

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/3397663/79594152-d3098b80-80dc-11ea-8f5f-98ab75a1bb35.png">

Value back to normal after the first speed test has run.

Double point no longer exists.
