### ISSUE TITLE
Chart y-scale not showing all data

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3793]
Pinging a localhost doesn't show the actual measured values, just points without y vals.

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/3397663/79597217-2c27ee00-80e2-11ea-87ea-ae5f456684d0.png">

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/3397663/79597224-30540b80-80e2-11ea-85fd-b8f380d6930a.png">

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/3397663/79597232-334efc00-80e2-11ea-9cef-4c596dbaf21c.png">

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/3397663/79597238-377b1980-80e2-11ea-89c7-41b41db46088.png">

**Comment by emanuele-f** [comment]
Added two decimal digits as internally discussed
