### ISSUE TITLE
Mac OS version gives errors

### ISSUE THREAD

**Issue by GewoonGijs** [ntop/ntopng#3794]
When I use ntopng to monitor traffic on my Fritz.box form my Mac (Catalina) it starts to run fine, but after a while I get these errors:
`
1:35:57 [Redis.cpp:119] ERROR: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.`

Please help

I use the packaged version that is available for download: ntopng-4.1.200405.pkg

**Comment by simonemainardi** [comment]
This seems an issue connected with redis, not with ntopng. It seems redis is not able to persist data on disk. Do you have free space on the system? Check redis logs.

**Comment by simonemainardi** [comment]
Hint given. No feedback received. Closing.

**Comment by jonahzheng** [comment]
the issue connected with redis,
set stop-writes-on-bgsave-error to no
127.0.0.1:6379> config set stop-writes-on-bgsave-error no
