### ISSUE TITLE
00:00:00:00:00:00 , what is this?

### ISSUE THREAD

**Issue by scdit46** [ntop/ntopng#3795]
Device 00:00:00:00:00:00 got the IP address 192.168.1.3 which is outside the configured DHCP range. [Sender: 00:00:00:00:00:00]
--

Remote host WORK-PT [ 00:00:00:00:00:00 ] has contacted a remote host. Remote-to-remote flows available from the flow alerts page.

---

ARP traffic from 00:00:00:00:00:00/95.18.47.106 to 00:00:00:00:00:00/192.168.1.111 detected. It is unlikely to see ARP traffic between those IPs as they are seemingly belonging to different broadcast domains. Check for hosts and networks configurations.

**Comment by lucaderi** [comment]
can you please share more detailed information?

**Comment by scdit46** [comment]
In alerts of ntopng:

New Device |   | New device 00:00:00:00:00:00 has connected to the network.
-- | -- | --


What is 00:00:00:00:00:00, I haven´t got a device with a MAC 00:00:00:00:00:00

**Comment by simonemainardi** [comment]
please, report ntopng configuration and nprobe - if used.

**Comment by scdit46** [comment]
yes, nprobe is used

**Comment by simonemainardi** [comment]
make sure nprobe is started with -T "@NTOPNG@". Report the configuration.

**Comment by simonemainardi** [comment]
Solution given, no feedback received. Closing.
