### ISSUE TITLE
does ntopng work in Layer 7?

### ISSUE THREAD

**Issue by scdit46** [ntop/ntopng#3796]
hello,

ntopng inspect the packet in layer 7 application?
How to know notpng what a flow is http?????

regards

**Comment by simonemainardi** [comment]
Hi,

ntopng does Layer7 using nDPI: https://www.ntop.org/products/deep-packet-inspection/ndpi/

Layer7 detection is enabled automatically when ntopng is monitoring from a packet interface.

Please, go through the docs https://www.ntop.org/guides/ntopng/ and the blog https://www.ntop.org/blog/
