### ISSUE TITLE
Alerts are not updated as the the threshold changes

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3798]
![Screen Shot 2020-04-19 at 15 58 46](https://user-images.githubusercontent.com/4493366/79689688-b2fdd780-8256-11ea-81d6-d635ead757a7.png)
In the above example the threshold is set to 100 and thus there is an alert
![Screen Shot 2020-04-19 at 15 59 40](https://user-images.githubusercontent.com/4493366/79689696-cc9f1f00-8256-11ea-9d85-68f0a0d17238.png)
Changing the threshold 
![Screen Shot 2020-04-19 at 15 58 57](https://user-images.githubusercontent.com/4493366/79689703-d4f75a00-8256-11ea-98cb-efe7d6393af8.png)
does not "close" the alert. And the opposite (no alert, lower the threshold, an alert is generated).

**Comment by emanuele-f** [comment]
The following behaviors are consistent with the other user scripts alert configurations:

- The alert is not closed until the next check occurs (e.g. until one hour in the example above)
- The alert message is not updated if the problem alert stay engaged (e.g. only the first threshold is reported.

Changing this on the active monitoring will be inconsistent with the other user scripts behavior. We should discuss on how to apply this logic globally.

**Comment by emanuele-f** [comment]
As discussed internally, we will add an exception for this alert by checking again the old value against the threshold as the user modifies the threshold.

**Comment by emanuele-f** [comment]
Implemented in c750a8422ee85cae22669e929c312710db1f2b9c

**Comment by simonemainardi** [comment]
To avoid logic duplication (if-threshold-then-trigger-else-release) and to avoid unclean backup-select(system interface)-select(backup) I would jsut set a flag and let the plugin redo the check within a minute. This has also the benefits to make it clear when and by who a check is performed.

**Comment by emanuele-f** [comment]
I would not consider these two lines of code as a repetition: https://github.com/ntop/ntopng/blob/dev/scripts/plugins/active_monitoring/web_gui/edit_active_monitoring_host.lua#L171 . Furthermore the solution above delays the alert trigger/release of 1 minute and it adds an exception to the 1 minute logic to handle such trigger/release.

**Comment by simonemainardi** [comment]
Average re-check time is 30 seconds and there's the benefit that the check logic stays in one place (not two) and there's only one point which is responsible to run the check. Things like backing up the old interface, selecting the system interface, the re-selecting the old interfaces are error prone and should be avoided when possible.

**Comment by simonemainardi** [comment]
After internal discussion we have decided to leave the current implementation for the time being.
