### ISSUE TITLE
Missing Localization

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3799]
The following commit has many strings hard-coded and non-localized. It is requested to properly use i18n for them:

https://github.com/ntop/ntopng/commit/4caea8fcb1f3f54595f004938d46d28f074cddb3

For example:

https://github.com/ntop/ntopng/commit/4caea8fcb1f3f54595f004938d46d28f074cddb3#diff-fbadcfeeadccbcd5abc8fcc1f3301bd6R12

**Comment by lucaderi** [comment]
This is work in progress code, not yet ready for prime time.

**Comment by simonemainardi** [comment]
will be reviewed and possibly reopen when done.
