### ISSUE TITLE
Filtering fails after running for long periods

### ISSUE THREAD

**Issue by DigiAngel** [ntop/ntopng#380]
Topic says it...kinda odd.  Version:

```
v.2.3.160204 [Community Edition]
GIT rev:   dev:cb714019c7ff9436dc17644c19e01a0bae70dea3:20160204
```

Running command:

```
sudo /opt/ntop/bin/ntopng -i eth0 -n 1 -B not host 192.168.1.7 -d /opt/ntop/var -m 192.168.1.0/24 -S all -q -U www-data
```

You can see some localhosts at the bottom of the gif before attempting to sort:
![test](https://cloud.githubusercontent.com/assets/947191/12868058/7a9c9f5c-ccbb-11e5-8e82-785d72f721a5.gif)

**Comment by DigiAngel** [comment]
Also confirming that this also a) applies to things like sorting to protocol, and b) once I stopped and restarted it works as intended, so this appears to be intermittent.  More testing.

**Comment by DigiAngel** [comment]
So more on this....this appears to apply to any filtering.  After running for a few hours I see this behaviour when attempting to filter by my local network:
![netafterrun](https://cloud.githubusercontent.com/assets/947191/12870369/a4635f36-ccfe-11e5-9b84-c2db84f69e30.gif)

but after stopping and starting ntop I get:
![netnew](https://cloud.githubusercontent.com/assets/947191/12870372/b21fa332-ccfe-11e5-8749-40763acaf156.gif)

**Comment by DigiAngel** [comment]
No takers on this eh?

**Comment by DigiAngel** [comment]
FYI latest git pull as of yesterday I see the same behaviour.  Thank you.

**Comment by lucaderi** [comment]
It works for me. Any chance to login to your host?

**Comment by DigiAngel** [comment]
Sure...let me email you offline here...thank you.

**Comment by DigiAngel** [comment]
Hi Luca, I emailed you yesterday to your ntop account...if you're still up for remoting in please let me know..thank you.

**Comment by lucaderi** [comment]
@DigiAngel Please try again I can't see your email

**Comment by DigiAngel** [comment]
Trying now...thank you.

**Comment by DigiAngel** [comment]
OK sent:

```
Feb 19 09:29:35 server postfix/smtp[27270]: DEB4960C819: to=<deri@ntop.org>, relay=mail.ntop.org[46.101.88.215]:25, delay=3.1, delays=0.24/0.01/2.2/0.61, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as 855D3120411)
```

Thanks again.
