### ISSUE TITLE
Make alerts and status parameter explicit

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3805]
Every alert and status must have a clear definition of its specific parameters, so that a programmer can easily review and extend them.

**Comment by simonemainardi** [comment]
split into:

- https://github.com/ntop/ntopng/issues/3811
- https://github.com/ntop/ntopng/issues/3812

**Comment by simonemainardi** [comment]
Proposed solution is the following.

Move alert builders which are now in alerts_api.lua each one inside its alert_definition.lua file, e.g., 

```
alerts_api.slowPurgeType
alerts_api.userScriptCallsDrops
alerts_api.tooManyDropsType
```

Each alert definition lua file will have an extra key `builder` in the table it returns. This can be referenced every time the builder is needed across the code. References to the builder should be as

```
alert_consts.alert_types.alert_dhcp_outside_range.builder
```


NOTE: there are also for alert builders which are called outside plugins, such as 

```
alerts_api.ipOutsideDHCPRangeType
```

which is called in `alert_utils.lua`. Also those guys need to be moved asw ell. Alert utils.lua will have a function reference such as  callable with parameters.


-------

Flow alerts

Flow alerts are missing the concept of builders. they just receive a table as input as

```
    info.cli_country = cli_country
    info.srv_country = srv_country

    flow.triggerStatus(flow_consts.status_types.status_blacklisted_country, info,
      flow_score, cli_score, srv_score)
  end
```

Also flow alerts must have to concept of builder. The `info` must not be explicitly passed to flow.triggerStatus. It is  `flow.triggerStatus` which calls the right builder depending on the alert type which, in turn, produces the info table.

So also every flow alert will have a builder as proposed for other alerts.

-------

**Proposed solution have the benefit that a user just have to look at the `alert_definition.lua` script to know exactly all the fields that end up in an alert (and also in the alert JSON which is exported).**

-------

- [ ] Move alert type builders inside each alert_definition.lua file
- [ ] Expose a reference to the alert type builder for each alert type: e.g., alert_consts.alert_types.alert_dhcp_outside_range.builder
- [ ] alert_type must not be explicitly indicated in the builder: as a builder belongs to an alert, the alert_type is implicit and must not be indicated. If necessary, alert_type can be attached to the builder when an alert is loaded.
- [ ] Rename the third field of alert formatter from info to alert_type_params to make it clean it is the same key
- [ ] Consider renaming the alert_json key exported into alert_type_params to avoid ambiguity
- [ ] Create alert builders for flow alerts
- [ ] Remove the `info` table from `flow.triggerStatus` and change `flow.triggerStatus` to call the builder depending on the alert type.

**Comment by emanuele-f** [comment]
This is now implemented.
