### ISSUE TITLE
Local/Remote traffic

### ISSUE THREAD

**Issue by xtrilla** [ntop/ntopng#3818]
Hi,

We have an nprobe + ntopng setup, but traffic seems to appear as the oposite as it really is:

![image](https://user-images.githubusercontent.com/33469164/79886813-f17fc780-83f9-11ea-9edb-f868cdc82b12.png)

The ratios seem ok, but the traffic seems to be reversed (We have way more outgoing traffic than incoming).

We are using the latest versions of ntopng and nprobe.

nProbe interfaces are optical taps of a LAG ( 2 x 10G which become 4 x 10G)

Here are the config files:

**nprobe.conf:**

```
-i=eth2,eth3,eth4,eth5
--zmq "tcp://*:5556"
-n none
-T "@NTOPNG@"
--aggregation "0/1/1/1/0/1/1"
--account-l2
-w 2097152
-M 2097152

--discard-tcp-probing-flows
--local-networks="x.x.x.0/21,x.x.x.0/21,x.x.x.0/22,x.x.x.0/22,x.x.x.0/24,x.x.x.0/22,x.x.x.0/22"
–-local-traffic-direction
--in-iface-idx 4
--out-iface-idx 2
--zmq-format=t
```

**ntopng.conf:**

```
--interface="tcp://127.0.0.1:5556"
--ignore-macs
--ignore-vlans
--local-networks="x.x.x.0/21,x.x.x.0/21,x.x.x.0/22,x.x.x.0/22,x.x.x.0/24,x.x.x.0/22,x.x.x.0/22"
--dns-mode=3
--max-num-hosts=400000
--max-num-flows=2000000
```

Thanks!

**Comment by simonemainardi** [comment]
What you are looking at is the local-to-temote and remote-to-local traffic, not really outgoing and ingoing. That is, from `--local-networks` and to `--local-networks`, respectively.

You need to provide more evidence if you think is reversed.

**Comment by xtrilla** [comment]
Hi,

You mean it is related to who starts the conversation? Then it would make sense, as it would related much better to this RDD graph we have to general monitor ports:

![image](https://user-images.githubusercontent.com/33469164/80099638-12b5f480-856f-11ea-9cb8-fed1604440c7.png)

But just to be completely clear:

Local -> Remote = Traffic which has been requested by local IPs and originates from remote IPs
Remote -> Local = Traffic which has been requested by remote IPs and originates from local IPs

It's a bit counter intuitive if you ask me, but maybe it's because I'm not used to flow terminology.

Thanks!

**Comment by simonemainardi** [comment]
It doesn't matter who starts the conversation.

But just to be completely clear:

> Local -> Remote = Traffic which has been requested by local IPs and originates from remote IPs

Traffic which originates from remote IPs and goes to local IPs

> Remote -> Local = Traffic which has been requested by remote IPs and originates from local IPs

Traffic which originates from local IPs and goes to remote IPs

Consider a conversation as IP_local <-> IP_remote:

- IP traffic from IP_local to IP_remote counts as local2remote
- IP traffic from IP_remote to IP_local counts as remote2local

No matter if IP_local (IP_remote) is the client or the server of the conversation.
