### ISSUE TITLE
Invalid labels on SNMP Interface graphs 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3819]
![image](https://user-images.githubusercontent.com/4493366/79962489-639eed80-8488-11ea-9949-58a3f842bb8c.png)

As you can see from the image, this is a graph from a SNMP interface. There are some issues
- #3402 when fixed will have the RX/TX no longer stacked
- labels are not readable. They must indicate just in and out with no further labels as they are already in the top bar. it is important that the use clearly understands what is visualising

**Comment by emanuele-f** [comment]
Now the Sent and Rcvd labels are shown
