### ISSUE TITLE
ntopng can't listen to http port

### ISSUE THREAD

**Issue by mzac** [ntop/ntopng#382]
Getting the following error with any option I try:

08/Feb/2016 11:22:13 [HTTPserver.cpp:497] ERROR: Unable to start HTTP server (IPv4) on ports 3000: Invalid argument

root@nbox1:~# ntopng -V
v.2.3.160208 [Professional Edition]
GIT rev:   dev:0cfa2b2c5b37fdd8208413443d046e74d79bbadc:20160208
Pro rev:   r564
System Id: 68926F0F820721D8
Built on:  Ubuntu 14.04.3 LTS

**Comment by simonemainardi** [comment]
please, check now
