### ISSUE TITLE
Missing last point from speedtest 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3822]
As you can see the measurement of 11AM is missing from the graph

![Screen Shot 2020-04-22 at 11 20 00](https://user-images.githubusercontent.com/4493366/79964658-4fa8bb00-848b-11ea-8a68-cb107ab9b782.png)

![Screen Shot 2020-04-22 at 11 20 13](https://user-images.githubusercontent.com/4493366/79964655-4d466100-848b-11ea-89dc-474c03428ad0.png)

Note that stats at the bottom of each chart such as 95th percentile or availability disappeared

**Comment by emanuele-f** [comment]
This probably occurs because of how the RRA aggregation in RRD works. The 1 day view uses the aggregated RRA.

**Comment by emanuele-f** [comment]
The problem was actually related to NaN numbers handling. This should be fixed in 24583f8443a9e4ccf96f1719c77a6d744a744b5d and 8d0e887878dc3e538d215f9252963428d4406367

**Comment by emanuele-f** [comment]
Added one extra point in the chart as internally discussed (4309248829651bee18f96c9e9e2f69280f7f0dba) . It remains the problem for the first point in RRD which is not returned by RRD.

**Comment by lucaderi** [comment]
See #3836
