### ISSUE TITLE
[question] ntopng Enterprise L license

### ISSUE THREAD

**Issue by mhercek** [ntop/ntopng#3824]
Hello,

I've found this statement _'ntopng Enterprise L already includes a nProbe Pro license, there is no need to buy a nProbe license if a ntopng Enterprise L license is installed"_. 
I may be blind but cannot find any further info regarding license installation and/or configuration.

**What does it mean exactly?**

I ordered ntopng Enterprise L a got one license key which I put into /etc/ntopng.license (as I was told).
But nprobe checks for its license in /etc/nprobe.license (I tried to copy ntopng license file into nprobe's and of course it's mismatch).
Or Enterprise L version is different package which bundles ntopng and nprobe together?
Or it is configuration related?

My current situation is ntopng is licensed (Enterprise version) and nprobe is not licensed.

**Comment by cardigliano** [comment]
@mhercek please note that installing /etc/ntopng.license is enough also to unlock nprobe, and no additional package is required. What ntopng version are you running?

**Comment by mhercek** [comment]
**`/usr/local/bin/ntopng --online-license-check -v`**
`Welcome to ntopng x86_64 v.4.0.200421 - (C) 1998-20 ntop.org`
`23/Apr/2020 06:15:07 [Ntop.cpp:453] Built on Debian GNU/Linux 10 (buster)`
`23/Apr/2020 06:15:07 [NtopPro.cpp:656] [LICENSE] System Id:     68899AFE820D2B21`
`23/Apr/2020 06:15:07 [NtopPro.cpp:657] [LICENSE] Edition:       Enterprise`
`23/Apr/2020 06:15:07 [NtopPro.cpp:658] [LICENSE] License Type:  Permanent License`

**`/usr/local/bin/nprobe -v`**
`Build OS:      Debian GNU/Linux 10 (buster)`
`SystemID:      68899AFE820D2B21`
`GIT rev:       9.0-stable:677c0eb3e87109215556a9fb7ec5b0e94e948a73:20200421`
`License:       Invalid license (/etc/nprobe.license) [License mismatch error]`

**`/usr/local/bin/nprobe --online-license-check -v`**
`Build OS:      Debian GNU/Linux 10 (buster)`
`SystemID:      68899AFE820D2B21`
`GIT rev:       9.0-stable:677c0eb3e87109215556a9fb7ec5b0e94e948a73:20200421`
`License:       Invalid license (/etc/nprobe.license) [Invalid response received: data tampered (by HTTP proxy?)]`

Maybe because --online-license-check is used (I had to add more disk space after license had been generated)?

**Comment by cardigliano** [comment]
@mhercek please update again, Enterprise L was not yet available on stable in your version

**Comment by cardigliano** [comment]
Os of the online check, adding disk spare should not require it, please remove and drop me an email (cardigliano at ntop.org) with your orderid if you experience issue.
