### ISSUE TITLE
[RTT] IP address not available for unreachable hosts

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3825]
The alert JSON for unreachable hosts (`info.ip`) contains the symbolic name and not the ip address when the host is unreachable. This prevents from knowing the ip address contacted:

![image](https://user-images.githubusercontent.com/3397663/80080814-69610580-8552-11ea-92e5-97d5184a85fd.png)

**Comment by emanuele-f** [comment]
This is implemented in 00c5e9f9098e832ea792968cb28771ab3a5ce532
