### ISSUE TITLE
nprobe, only send flows of a network

### ISSUE THREAD

**Issue by scdit46** [ntop/ntopng#3826]
hello,

In my Windows 10 I have configured nprobe for send flows to ntopng.
My workstation Windows 10 have several networks (vmware workstation, vmnet1, vmnet2, vmnet3,..), also the wifi network.

The nprobe only sends flows of a network (vmnet1).

Why?

regards.

**Comment by scdit46** [comment]
Correction: The nprobe only sends flows of a network (**vmnet8** - 172.16.101.0/24).

I see this with Wirehsark (Traffic CFLOW).

**Comment by emanuele-f** [comment]
Have you configured nProbe with the `-i` options for your interfaces? Please check out https://www.ntop.org/guides/nprobe/how_to_start.html#specify-monitored-interfaces .

**Comment by scdit46** [comment]
Available interfaces:
        [index=0] 'VMware Virtual Ethernet Adapter'
        [index=1] 'VMware Virtual Ethernet Adapter'
        [index=2] 'Microsoft'
        [index=3] 'TAP Adapter OAS NDIS 6.0'
        [index=4] 'Microsoft'
        [index=5] 'Microsoft'
        [index=6] 'VMware Virtual Ethernet Adapter'
        [index=7] 'Microsoft'

How to configure agent nprobe in windows for send traffic of vmnet1, vmnet2 and vmnet 8?

**Comment by simonemainardi** [comment]
see https://www.ntop.org/guides/nprobe/how_to_start.html?highlight=windows#running-nprobe-on-windows

**Comment by emanuele-f** [comment]
You need to specify all the options in the command line:

```
nprobe.exe /r
nprobe.exe /i -i 0 -i 1 -i 6 --zmq ...your zmq params...
```
