### ISSUE TITLE
Speedtest refresh not working

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3827]
![Screen Shot 2020-04-23 at 15 05 26](https://user-images.githubusercontent.com/4493366/80103086-f5375980-8573-11ea-921b-bd9574d41143.png)

For speedtest the refresh is not working as for the other measurements

**Comment by emanuele-f** [comment]
Cannot reproduce. What browser are you using? Can you provide the contents of the latest XHR reply to `get_active_monitoring_hosts.lua`?

**Comment by lucaderi** [comment]
I will take care of this issue and check if after all changes is still pending

**Comment by simonemainardi** [comment]
working as expected on my side
