### ISSUE TITLE
Ubuntu 20.04 LTS Support

### ISSUE THREAD

**Issue by alcaldiapcr** [ntop/ntopng#3830]
ubuntu 20.04 LTS

wget http://apt.ntop.org/20.04/all/apt-ntop.deb (does not exist)

`apt install pfring-dkms nprobe ntopng n2disk cento`
`The package could not be located pfring-dkms`
`The package could not be located nprobe`
`The package could not be located n2disk`
`The package could not be located cento`

Please update the repositories for Ubuntu 20.04

Thanks

**Comment by cardigliano** [comment]
@alcalpcr Ubuntu 20 is not yet supported, we will release packages for it soon!

**Comment by lucaderi** [comment]
Implemented both dev and stable

**Comment by simonemainardi** [comment]
docker tests added as well

**Comment by alcaldiapcr** [comment]
thanks

**Comment by alcalpcr** [comment]
thanks for update

**Comment by ShagoY** [comment]
Hi , i got this error on ntopng start (ubuntu 20.04)

```
ntopng: src/../third-party/patricia/patricia.c:753: patricia_node_t* patricia_lookup(patricia_tree_t*, prefix_t*): Assertion `prefix->bitlen <= patricia->maxbits' failed.
May 15 19:33:57 scw-wireguard systemd[1]: ntopng.service: Main process exited, code=killed, status=6/ABRT
May 15 19:33:57 scw-wireguard systemd[1]: ntopng.service: Failed with result 'signal'.

```

I used this guide : http://packages.ntop.org/apt/

**Comment by simonemainardi** [comment]
Please report the ntopng version used. Try to follow this procedure https://www.ntop.org/guides/ntopng/faq.html#reset-ntopng-preferences and start over.

**Comment by stevefxp1** [comment]
Is 20.04 supported at this time bc the instructions are still not working.

**Comment by simonemainardi** [comment]
it's supported. Instructions are at packages.ntop.org. Please, report what is not working with you.

**Comment by stevefxp1** [comment]
Are you supporting Ubuntu 20.04.1 on Raspberry Pi?

**Comment by wuppiwuppi** [comment]
> 
> 
> Are you supporting Ubuntu 20.04.1 on Raspberry Pi?

I second that question. I have severe issues getting it installed via apt using the given installation instructions. I remain with a 3.8 version which comes from ubuntu repositories - not ntop ones.
