### ISSUE TITLE
NTOP   running NPROBE  Unable to open interface nfqueue 

### ISSUE THREAD

**Issue by bobcat1111** [ntop/ntopng#3831]
after a restart 

I cannot get the probe to run any more ( previously working ) 
24/Apr/2020 00:31:23 [pro/pf_ring.c:377] Initializing PF_RING socket on device nfqueue..
24/Apr/2020 00:31:23 [nprobe.c:7648] Initializing pcap socket on device nfqueue..
24/Apr/2020 00:31:23 [nprobe.c:7659] ERROR: Unable to open interface nfqueue.
24/Apr/2020 00:31:23 [nprobe.c:9836] ERROR: Unable to open interface nfqueue (nfqueue: Can't listen on group group index: Operation not permitted)
24/Apr/2020 00:31:23 [nprobe.c:9838] ERROR: Try using -i none if you do not want capture from a NIC

**Comment by emanuele-f** [comment]
What options are you using in the nprobe configuration file? Please consider adding specific `-i` options for the network interfaces that you want to monitor (see https://www.ntop.org/guides/nprobe/cli_options.html)

**Comment by lucaderi** [comment]
nfqueue is not a valid network interface PF_RING can use. Please provide details how to reproduce it

**Comment by simonemainardi** [comment]
No feedback received in 13 days. Closing. Please, reopen with the submitted information if necessary.
