### ISSUE TITLE
Implement attack mitigation via SNMP

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3833]
When ntopng is used with SNMP, ntopng knows where a certain host is located and how it attached to the network. This means that it is known the switch+interfaceId of the host.
In case of attack ntopng should be able to block selected hosts when they are for sure (so not a probability but for sure) attackers. They could be blocked by setting the interface down via SNMP (set on the operationalStatus instanceId) so that the attack is mitigated.
This is what this ticket has to implement that in essence is
- enable SNMP set and write community on the SNMP component
- enable attack detection
- configure via preference, the ability to block attacks wit this mechanism

**Comment by lucaderi** [comment]
ntopng can now toggle interface status with

function snmp_dev:set_interface_status(snmp_host_ip, if_idx, toggle_to_up)

**Comment by lucaderi** [comment]
Furthermore add the ability to put the interface up/down via SNMP

**Comment by lucaderi** [comment]
Attack mitigation will be implemented by means of a new script that will use the client score (#4314): the idea is to block a host that is attacking (thus client score) the rest of the network via SNMP. Attack mitigation in the future can be implemented also for server score (not via SNMP) so for the sake of code reusability it is requested to write the mitigation code in a way that it can be extended (and not rewritten) when this feature will be implemented.

**Comment by simonemainardi** [comment]
Implemented. As requested, the client score is used to possibly trigger an `snmpset` on the host access port.

An alert is triggered as well to let the user know about the performed action:

![image](https://user-images.githubusercontent.com/3397663/91046904-8816fc00-e619-11ea-93a9-aac63248c9d8.png)

By default, the script is disabled and has a minimum score of 30000. The script can be configured from the user scripts page:

![image](https://user-images.githubusercontent.com/3397663/91048356-d927ef80-e61b-11ea-8618-40928d706c2c.png)
