### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by CyberbreinAirw0lf** [ntop/ntopng#3834]
See also attached screenshot:
The log /var/log/syslog is filled with this error.
What does this mean? 

ntopng Enterprise Edition v.4.0.200423
Running on Ubuntu 18.04.4-LTS

Cheers - Will

![script-error](https://user-images.githubusercontent.com/64280991/80247709-ce118280-866e-11ea-8bf6-78d573da9859.jpg)

**Comment by NogNeetMachinaal** [comment]
Empty web pages on the alerts and interfaces - see also attached 2 screenshots.
Please advise - what could be wrong and how do I fix that?

Cheers - Will

=====

![empty-page-1](https://user-images.githubusercontent.com/64280991/80248104-91925680-866f-11ea-9efd-198d90e2e071.jpg)
![empty-page-2](https://user-images.githubusercontent.com/64280991/80248107-922aed00-866f-11ea-9c58-10b6afd36bf8.jpg)

**Comment by lucaderi** [comment]
This was fixed already. Please upgrade ntopng and it will work.

**Comment by CyberbreinAirw0lf** [comment]
Yes - correct => consider this issue resolved.
