### ISSUE TITLE
Empty web pages

### ISSUE THREAD

**Issue by CyberbreinAirw0lf** [ntop/ntopng#3835]
Team,

There are empty web pages on the alerts and interfaces - see also attached 2 screenshots.
Please advise - what could be wrong and how do I fix that?

ntopng Enterprise Edition v.4.0.200423
Running on Ubuntu 18.04.4-LTS

Cheers - Will

=====

![empty-page-1](https://user-images.githubusercontent.com/64280991/80248308-f2219380-866f-11ea-9762-dea017f5a9c7.jpg)
![empty-page-2](https://user-images.githubusercontent.com/64280991/80248310-f2ba2a00-866f-11ea-906e-4114cc7719b6.jpg)

**Comment by lucaderi** [comment]
Can you please check if there are errors on the ntopng console? You can see them accessing the system interface -> health -> System Status

**Comment by CyberbreinAirw0lf** [comment]
No errors . 
In addition, it looks that things are working => consider this solved.
