### ISSUE TITLE
Invalid extra point implementation 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3836]
This code https://github.com/ntop/ntopng/commit/4309248829651bee18f96c9e9e2f69280f7f0dba is not fully right 
![Screen Shot 2020-04-25 at 09 35 22](https://user-images.githubusercontent.com/4493366/80274118-6132d280-86d8-11ea-992c-d47a74fa8e1a.png)
In the above graph an extra synthetic point has been added. This is an error. The extra point must be added *if and only if* the current time is past the last measurement and before the next one.

Fo if at 9 AM you have a measurement and the current time is 9.45 AM, I can see the extra point added at 9.45. If, as in the above graph, the current time is past adding the extra point is not wise and it should not be added. This because you don't know when ntopng was stopped.

See #3822

**Comment by emanuele-f** [comment]
This should be fixed in d1ae6b545acaa6077678ad2cc005f8ca404c5c35.
