### ISSUE TITLE
Graphs more readable in dark theme

### ISSUE THREAD

**Issue by jq-yeraz** [ntop/ntopng#3844]
In the dark theme, the grid lines of the graph are too bright.

Is this possible to slightly change some CSS styles :

![changes](https://user-images.githubusercontent.com/62381029/80416995-509b7b80-88d5-11ea-901c-5150d0de2691.png)

On the screenshot below, I changed on the two next classes :

    .nvd3 .nv-axis line 
    .nvd3 .nv-axis path

This attributes :
   
     stroke-width: 0.8px; // make the line thin
     stroke: #2C2C2C; // same border color used in table

On all `<text />` I modified the X value from -3 to -10.

**Comment by gabryon99** [comment]
<img width="954" alt="Screenshot 2020-06-15 at 12 06 05" src="https://user-images.githubusercontent.com/14114916/84645270-99000e80-af00-11ea-956a-fe35cd4c90b1.png">
@jq-yeraz thanks for your suggesstion! I've implemented the styles you gave us.
