### ISSUE TITLE
High CPU usage on non-Linux platforms

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3845]
On non Linux platforms, sometimes and suddenly the CPU goes crazy 
![image](https://user-images.githubusercontent.com/4493366/80459011-0399c280-8932-11ea-830b-434a8c344350.jpeg)

Apparently this happens in particular when the computer goes idle, or after a wake-up

**Comment by lucaderi** [comment]
This is Windows with ntopng code from yesterday morning
![Screen Shot 2020-04-28 at 09 36 54](https://user-images.githubusercontent.com/4493366/80491194-ad914300-8962-11ea-9899-77e6920f9d07.png)

And this is after the fix https://github.com/ntop/ntopng/commit/9fabefe2cfa18bde50ac8f80aa913a9bfdb02774
![Screen Shot 2020-04-28 at 09 58 45](https://user-images.githubusercontent.com/4493366/80491187-abc77f80-8962-11ea-922d-42a5e66c5db0.png)

However on MacOS sometimes there is still some sort of craziness happening with CPU that spikes up

**Comment by simonemainardi** [comment]
@gabryon99 can you still reproduce this behavior? I don't see any suspicious behavior on my Mac.

**Comment by gabryon99** [comment]
Recently there wasn't any problem with my Mac

**Comment by emanuele-f** [comment]
This may have been fixed with 607ba52263830c577e7b37c8c25320e60466a5f6
