### ISSUE TITLE
ts_utils.listSeries does not return hosts list (RRD)

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3847]
The following query is expected to return the list of hosts for the specified interface, however when using RRD it returns the list of L7 protocols instead.

```
ts_utils.listSeries("host:traffic", {ifid=1}, 0)
```

**Comment by emanuele-f** [comment]
The affected function is `_listSeries` inside `rrd.lua`. The problem is quite complex: IP addresses and MAC addresses are handled with a special logic (see `getPathFromKey`). There are multiple problems:

- `_listSeries` is unable to determine that a specific tag of a schema contains IP address/MAC address information (the tag name is just a name, however we could just assume that an `host`, `subnet` or `mac` tag contains hosts information.
- Even if it could determine such host related tags, `_listSeries` should then iterate all the subdirectories to search for hosts, e.g. the host `192.168.1.1` traffic is contained in `rrd/192/168/7/1/traffic.rrd`. This is not feasible when there are a big number of hosts saved.

**Comment by MatteoBiscosi** [comment]
Issue is fixed with latest release
