### ISSUE TITLE
Preferences entry not hidden correctly

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3849]
starting from this

![image](https://user-images.githubusercontent.com/3397663/80493704-08786980-8966-11ea-87b8-3200340d3a68.png)

if I disable "Idle Local Hosts Cache":

![image](https://user-images.githubusercontent.com/3397663/80493747-14fcc200-8966-11ea-8c00-184897457b49.png)

And then re-enable it, a new entry "Active Local Host Cache Interval" which should be hidden appears

![image](https://user-images.githubusercontent.com/3397663/80493790-247c0b00-8966-11ea-9677-a233c4bcd208.png)

Entry "Active Local Host Cache Interval" depends on "Active Local Hosts Cache": when "Active Local Hosts Cache" is disabled, "Active Local Host Cache Interval" must be hidden.

**Comment by simonemainardi** [comment]
same behavior occurs in preference:

![image](https://user-images.githubusercontent.com/3397663/80995269-4bdb4800-8e3e-11ea-82b8-77d3926c8710.png)


it would be desirable to have a generic fix rather than an ad-hoc per preference fix.

**Comment by simonemainardi** [comment]
still not working for https://github.com/ntop/ntopng/issues/3849#issuecomment-623601675

**Comment by emanuele-f** [comment]
Fixed in 2fc0b30e4656ac24ba5e7135888c53e344213f67 and 1a955db5cf5f12b4e1218f2c48465b02c37dc579.
