### ISSUE TITLE
license install getting "operation not permited"  Issue #3708, ntopg.license cannot be modified

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#3850]
@simonemainardi  @emanuele-f 

@lucaderi does not want to provide access, as they think the issue is with us for the ntopng.license file, I assure you it is not.

This is your file, I have no special permissions with this file, and we would really like to get our license that Marie Allegro provided to us.

Thanks....

**Comment by StewAlexander-com** [comment]
I requested remote access, @lucaderi denied it.

So, the issue is that file, how do I delete a file that you made undeletable?

**Comment by StewAlexander-com** [comment]
the file in question is the ```ntopng.license``` file under /etc/

**Comment by emanuele-f** [comment]
Contacted privately.
