### ISSUE TITLE
Hardcoded measurements and measurement strings

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3851]
Measurements and their i18n strings have been hardcoded in https://github.com/ntop/ntopng/commit/d913752117e44976f7b8955508cf2f9ee595bada#diff-4da265a1bf6a15aacb1289ac1c3c8ebeR310.

Measurements and their i18n strings are dynamic and must be loaded dynamically. 

In the current status:
- Adding a new measurement such as the continuous ping would require changing javascript files around the code
- Measurement i18n won't be available

**Comment by gabryon99** [comment]
Fixed, see: https://github.com/ntop/ntopng/commit/051cf67dc59bdd128c4fa3a72c041bc859d6dcb4
