### ISSUE TITLE
[pools] Implement syslog notification  endpoint

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3853]
The syslog endpoint will have only one parameter
- format: text or json

Note that there is at most one syslog notification endpoint defined

**Comment by simonemainardi** [comment]
> Note that there is at most one syslog notification endpoint defined

not enforced

**Comment by simonemainardi** [comment]
To enforce the max limit, remove method

https://github.com/ntop/ntopng/commit/90fd2122931af5fd906e46b7010fb227d621115f#diff-76f033502d8e6cc05fd9389f4d8c47c0R21

max limit must come with method `notification_configs.get_types()`

**Comment by simonemainardi** [comment]
multiple syslog can still be defined. please check https://github.com/ntop/ntopng/issues/3853#issuecomment-648915138

**Comment by lucaderi** [comment]
@simonemainardi Please in

> 90fd212#diff-76f033502d8e6cc05fd9389f4d8c47c0R21

implement the conf_max_num

i.e.

local notification_configs = require("notification_configs")
tprint( notification_configs.get_types())

that it must be present all times with the maximum number of occurrences

**Comment by gabryon99** [comment]
Now if exists a Syslog Endpoint Type is not possible to create a new one:
<img width="1632" alt="Screenshot 2020-08-17 at 11 18 33" src="https://user-images.githubusercontent.com/14114916/90379739-6519a480-e07b-11ea-8f8f-44381c81af5c.png">
<img width="796" alt="Screenshot 2020-08-17 at 11 18 50" src="https://user-images.githubusercontent.com/14114916/90379768-6fd43980-e07b-11ea-817d-9ce1580cc129.png">

If the current Syslog entry will be removed then inside the Add Modal will appear the Syslog Endpoint Type entry:
<img width="796" alt="Screenshot 2020-08-17 at 11 19 34" src="https://user-images.githubusercontent.com/14114916/90379824-89758100-e07b-11ea-9dad-0e9ac7561821.png">


In addition, a filter for the endpoints types has been implemented as requested by @lucaderi:
<img width="1695" alt="Screenshot 2020-08-17 at 11 16 13" src="https://user-images.githubusercontent.com/14114916/90379461-110ec000-e07b-11ea-9136-1d6822b3fdb5.png">
