### ISSUE TITLE
Implement notification recipient

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3857]
Notification recipients are JSON strings written in redis that contain the configuration of recipient that is defined as follows
- notification endpoint (previously defined) to which the notification will be sent
- notification attributed that specify further information to be delivered.

A new page will be created similar to this one
![Screen Shot 2020-04-29 at 10 06 53](https://user-images.githubusercontent.com/4493366/80575138-542d2080-8a03-11ea-958c-819e62690307.png)

Clicking on the + icon it is possible to add a new recipient. Possible actions are edit (modify the parameter of a given recipient) and delete (remove the recipient).

The page should have buttons for import/export recipient across ntopng configurations: please make sure that import/export is for all (endpoint, recipients....) instead of having multiple options for specified elements (e.g. only the recipient)

A recipient is defined as follows
- unique recipient identifier string
- (existing) notification endpoint name
- (optional) endpoint parameters

Recipients are identified by a unique string that contains no spaces and only alphanumeric strings/numbers/special chars such as "-_@#"

The recipient, in addition to its unique name, will contain additional parameters that are defined according to the endpoint being selected, and in particular

- email: specify the To: and Cc:
- slack: specify the channel name
- web hook (none)
- syslog (none)
- nagios/CheckMK (to be specified)

Important: each recipient must have a 
- "send test message" button to check the recipient configuration.
- counter for keeping track of the number of messages delivered to such recipient. Currently this value is volatile, but on future releases it can be stored as timeseries.

See #3856

**Comment by simonemainardi** [comment]
This issue has been implemented. Recipients will be now merged with notification endpoints to simplify the overall configuration.
