### ISSUE TITLE
Implement active monitoring recipient notification 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3858]
In the active monitoring screen 
![Screen Shot 2020-04-29 at 10 31 48](https://user-images.githubusercontent.com/4493366/80575977-aae72a00-8a04-11ea-9232-1cb0f2b4c55e.png)

>  a new field should added containing the list of notification recipients to which alert (engage/disengage) will be delivered. Note that this is a multi-selection list (i.e. multiple recipients can receive the alert). This ticket depends on #3856, #3857 

Notification recipients will be implemented via host pulls. Hence it is requested to add a new drop down menu in this dialog where the user will select the pool name to which this measurement will belong to. Furthermore a new HTML anchor should be added to the page for sending to the user to the "active monitoring pool" page so that pools can be added/removed etc.

**Comment by gabryon99** [comment]
<img width="897" alt="Screenshot 2020-07-15 at 12 40 11" src="https://user-images.githubusercontent.com/14114916/87535784-56188e80-c698-11ea-8e14-9d1d77667d35.png">

A select with Active Monitoring Pools has been added. See commit: https://github.com/ntop/ntopng/commit/1a72ce58c868d8e17930e6ee696d48c7edbcff2d for further details
