### ISSUE TITLE
Implement alert to recipient mapping

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3859]
Alerts are stored inside ntopng but they can be optionally delivered to recipients outside ntopng. The binding between alerts and recipients is specified in a new configuration page similar to the one defined below

![Screen Shot 2020-04-29 at 10 06 53](https://user-images.githubusercontent.com/4493366/80576524-a707d780-8a05-11ea-84df-678b25b4521d.png)

Clicking on the + icon it is possible to add a new mapping. Possible actions are edit (modify the parameter of a given mapping) and delete (remove the mapping).

The page should have buttons for import/export mapping across ntopng configurations.

Mappings are identified by a unique string that contains no spaces and only alphanumeric strings/numbers/special chars such as "-_@#"

Each mapping has the following fields
- alert family to which this mapping applies: stateful alerts, flow alerts, subnet alerts....
- alert type (that depends on the family)
- severity
- notification recipients (multivalue as in #3858)
- regex for matching the message (optional)

For all fields it should be possible to specify a wildcard. Note that a single alert cn match multiple recipients.

Important each entry must have a counter for keeping track of the number of messages delivered to such recipient. Currently this value is volatile, but on future releases it can be stored as timeseries.

This ticket depends on #3856, and #3857.

**Comment by emanuele-f** [comment]
Additional requirements:

- Ability to specify a time interval in the recipient filter
- Implement a queue per recipient, to avoid that a recipient monopolizes the queue

**Comment by lucaderi** [comment]
Please see also #3974.

**Comment by simonemainardi** [comment]
this is implemented.
