### ISSUE TITLE
Too many arguments on line 71

### ISSUE THREAD

**Issue by Hetzbacke** [ntop/ntopng#386]
After I write the configuration file for ntopng and tried to start the service if got the Error Message, that there are too many arguments on Line 71 in

/etc/init.d/ntopng

as attached file you can see my configuration file. Can anybody help me with this?

[ntopng.conf.txt](https://github.com/ntop/ntopng/files/122815/ntopng.conf.txt)

**Comment by simonemainardi** [comment]
fixed. packages will be built tonight. Anyway, please check, your ntopng should start even if it complains.

**Comment by Hetzbacke** [comment]
Thanks for your help. I will wait for the new build tonight.
