### ISSUE TITLE
Prevent automatic updates to invalidate licenses

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3862]
ntopng automatic updates may invalidate a license when the update causes the maintenance to expire.

It is requested to disable automatic updates if they would result in license invalidation.

ntopng automatic update script should do a `--check-maintenance` and avoid performing the update.

Same logic is implemented in `packages/ubuntu/debian.ntopng/prerm.in` to promt the user from the CLI. See if the same function can be reused.

**Comment by cardigliano** [comment]
Maintenance check added
