### ISSUE TITLE
Flow Collection Drops

### ISSUE THREAD

**Issue by mhercek** [ntop/ntopng#3864]
I need to know what does _Flow Collection Drops_ mean exactly.
I have quite a  large number of drops from a site with low activity (=bandwidth & connections per secod).
Remote exporter is pfSense running pmacct. 
I have other two similar setups with pfSense and pmacct with higher activity and with much less Flow Collection Drops.
How do I find out why are flows being dropped?

**Comment by emanuele-f** [comment]
The drops occur between nProbe and the Netflow exporter (based on the Netflow flow sequence). Please report the output of `ntopng --version` and `nprobe --version` and post the ntopng and nProbe configuration used.

**Comment by simonemainardi** [comment]
NetFlow packets are sequenced. nProbe use the sequence to make sure all the NetFlow packets are arriving. When nProbe detects holes in the sequence, it assumes NetFlow packets are dropped. So for example if nProbe receives a NetFlow packet with sequence=1, then with sequence=5, it counts 3 flow collection drops.

in your case it can be:

1. The network is dropping packets
2. The router can’t keep up 
3. nProbe is dropping on the UDP socket

start by checking on the router. Also run nProbe with option `-b=1` and look at the logs, in particular these 2 lines which should tell you the reason:

```
04/May/2020 19:54:51 [nprobe.c:3443] UDP collection stats:   [collected pkts: 5][UDP socket drops: 0]
04/May/2020 19:54:51 [nprobe.c:3450] Flow collection stats:  [processed: 3][dropped (holes in collected flow sequence): 0]
```

**Comment by mhercek** [comment]
This is quite weird.

I am exporting netflow from a host in site A. Exporter is pmacct.
Nprobe & ntopng runs on a host in site B.
Between both sites is internet.

I have done some measurements:
- site A: netflow exporter: tcpdump on the host captured 1110 UDP packets headed to nprobe
- site B: gateway before nprobe: tcpdump on the host captured 1108 UDP packets headed to nprobe
- site B: nprobe host: tcpdump on the host captured 1108 UDP packets
- measurement took about 5 minutes, from 09:42 AM to 09:47 AM
- site B: ntopng dropped flows 43,052 631 at 09:42 and 44,061,038 at 09:47 on the interface

ntopng 4.0.200504  Enterprise L
nprobe 9.0.200504 Pro

`/usr/local/bin/nprobe -b 2 -I SITE_A --zmq tcp://127.0.0.1:5554 -i none -n none --collector-port 9994 -V 9 --disable-cache --zmq-disable-buffering -T"%IPV4_SRC_ADDR %IPV4_D
ST_ADDR %IN_BY TES %L4_SRC_PORT %L4_DST_PORT %TCP_FLAGS %PROTOCOL %SRC_TOS %SRC_AS %DST_AS %IN_SRC_MAC %OUT_DST_MAC %IPV6_SRC_ADDR %IPV6_DST_ADDR %FIRST_SWITCHED %LAST_SWITCH
ED %IPV4_NEXT_HOP %INPUT_SNMP %OUTPUT_SNMP %IN_PKTS %IN_BYTES%EXPORTER_IPV4_ADDRESS" &`

ntopng config file:

-i tcp://127.0.0.1:5553
-i tcp://127.0.0.1:5554
-i tcp://127.0.0.1:5555
-i tcp://127.0.0.1:5556
-i tcp://127.0.0.1:5557
-i tcp://127.0.0.1:5558
-i tcp://127.0.0.1:5559

--local-networks "192.168.0.0/16,172.16.0.0/16,10.0.0.0/8"

--http-port "0"

--https-port "192.168.24.113:3001"

--dump-flows "mysql;localhost;ntopng;flows;ntop;passw"

--dns-mode 3

-d /srv/data/ntopng

--verbosity 6

**Comment by simonemainardi** [comment]
Again, drops are inferred using sequence numbers. If it's the router which is dropping as it cannot keep up with the traffic, it will just increase the sequence number but won't send any packet. 

Use tcpdump to record a pcap and then open it with wireshark. You'll be able to see sequence numbers there, and issues with sequence numbers will be highlighted in yellow. Please check.

**Comment by simonemainardi** [comment]
pcap received privately, thanks @mhercek 

pcap analysis shows there are gaps/wraps which are also highlighted by Wireshark. See for example what I obtain using your capture:

![image](https://user-images.githubusercontent.com/3397663/81919950-c5aac880-95d8-11ea-80f1-003fed30b849.png)

![image](https://user-images.githubusercontent.com/3397663/81919996-d8250200-95d8-11ea-812f-cf48a2f0c434.png)

![image](https://user-images.githubusercontent.com/3397663/81920033-e410c400-95d8-11ea-9829-945a859f2f16.png)

As you can see, many times the flow sequence is broken (highlighted in yellow by wireshark). Having a broken flow sequence number is what causes ntopng to tell "Flow Collection Drops".

This is something you need to sort with the router manufacturer.

**Comment by mhercek** [comment]
Apparent wrong flow numbers were caused by running multiple pmacct daemons at remote site (pmacct is exporting to single nprobe collector). Solved by switching to IPFIX and adding 'nfprobe_engine: number' to my exporter (pmacct) config.
