### ISSUE TITLE
Add mean and jitter calculation to active monitoring

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3868]
![Screen Shot 2020-04-30 at 14 46 03](https://user-images.githubusercontent.com/4493366/80712353-2d99e300-8af2-11ea-8e39-2b9b7814cc1a.png)
in active monitoring it is requested to add a new column (to the right of the measurement) that contains the values of Mean and Jitter (all in one column).
The ContinuousPing class computes and exports such values. The other measurements need to compute the values in Lua. The formulas to use are:

- mean = sum(measurements) / count(measurements)
- jitter = sum(|x(i) - x(i-1)|) / (n-1))

In the future it would be nice to store the jitter on a timeseries.

**Comment by emanuele-f** [comment]
Column and charts added in 976cf183be65032d130a51258784a64630cd1845
