### ISSUE TITLE
ProxMox cluster protocol misinterpreted as What's App calls

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#3869]
Hi all,

We see a lot of this:

STUN.WhatsAppCall 	 UDP	Proxmox VM  :56113

It's not a What's AppCall, it's the TCP ID for the ProxMox VM cluster I believe.

Is there a way to change this?

This is seen under the http://<fqdn>//lua/flows_stats.lua menu

**Comment by StewAlexander-com** [comment]
For a list of ports ProxMox usses: https://pve.proxmox.com/wiki/Ports

**Comment by StewAlexander-com** [comment]
Actually strike that, it's used by the underlying FreeBSD architecture as part of our storage structure

**Comment by emanuele-f** [comment]
Please open an issue here https://github.com/ntop/nDPI and provide a PCAP file if possible. Please also check out this: https://www.ntop.org/guides/ntopng/web_gui/categories.html#custom-applications
