### ISSUE TITLE
ntopng service keeps crashing on opnsense

### ISSUE THREAD

**Issue by mcat528** [ntop/ntopng#3870]
**NTOPNG service keeps crashing on OPNsense firewall. Not super linux savy so not sure how to troubleshoot beyond below:**

Version: OPNsense 20.1.5-amd64
FreeBSD 11.2-RELEASE-p18-HBSD
CPU Type Intel(R) Celeron(R) CPU J1900 @ 1.99GHz (4 cores)
ntopng Community Edition v.4.0.200422

**System error log:**

504385	2020-04-30T14:01:03	kernel: pid 1606 (ntopng), uid 288: exited on signal 11
511085	2020-05-01T08:17:45	ntopng: [Utils.cpp:3351] WARNING: ntopng has not been compiled with libcap-dev
511205	2020-05-01T08:17:45	ntopng: [Utils.cpp:3352] WARNING: Network discovery and other privileged activities will fail

**NtopNG log:**

29/Apr/2020 09:05:59 [main.cpp:380] Logging onto /var/db/ntopng/ntopng.log
29/Apr/2020 09:05:59 [main.cpp:383] Working directory: /var/db/ntopng
29/Apr/2020 09:05:59 [main.cpp:385] Scripts/HTML pages directory: /usr/local/share/ntopng
29/Apr/2020 09:05:59 [Ntop.cpp:437] Welcome to ntopng amd64 v.4.0.200422 - (C) 1998-20 ntop.org
29/Apr/2020 09:05:59 [Ntop.cpp:863] Adding xx/128 as IPv6 interface address for re0
29/Apr/2020 09:05:59 [Ntop.cpp:873] Adding xx/64 as IPv6 local network for re0
29/Apr/2020 09:05:59 [Ntop.cpp:832] Adding xx/32 as IPv4 interface address for re0
29/Apr/2020 09:05:59 [Ntop.cpp:841] Adding 72.192.132.0/22 as IPv4 local network for re0
29/Apr/2020 09:05:59 [Ntop.cpp:832] Adding 192.168.1.1/32 as IPv4 interface address for re1
29/Apr/2020 09:05:59 [Ntop.cpp:841] Adding 192.168.1.0/24 as IPv4 local network for re1
29/Apr/2020 09:05:59 [Ntop.cpp:863] Adding xx/128 as IPv6 interface address for re1
29/Apr/2020 09:05:59 [Ntop.cpp:873] Adding xx/64 as IPv6 local network for re1
29/Apr/2020 09:05:59 [Ntop.cpp:863] Adding ::1/128 as IPv6 interface address for lo0
29/Apr/2020 09:05:59 [Ntop.cpp:873] Adding ::1/128 as IPv6 local network for lo0
29/Apr/2020 09:05:59 [Ntop.cpp:863] Adding fe80::1/128 as IPv6 interface address for lo0
29/Apr/2020 09:05:59 [Ntop.cpp:873] Adding fe80::1/64 as IPv6 local network for lo0
29/Apr/2020 09:05:59 [Ntop.cpp:832] Adding 127.0.0.1/32 as IPv4 interface address for lo0
29/Apr/2020 09:05:59 [Ntop.cpp:841] Adding 127.0.0.0/8 as IPv4 local network for lo0
29/Apr/2020 09:05:59 [Ntop.cpp:863] Adding xx/128 as IPv6 interface address for ovpns1
29/Apr/2020 09:05:59 [Ntop.cpp:873] Adding xx/64 as IPv6 local network for ovpns1
29/Apr/2020 09:05:59 [Ntop.cpp:832] Adding 192.168.2.1/32 as IPv4 interface address for ovpns1
29/Apr/2020 09:05:59 [Ntop.cpp:841] Adding 192.168.2.1/32 as IPv4 local network for ovpns1
29/Apr/2020 09:05:59 [PeriodicActivities.cpp:105] Started periodic activities loop...
29/Apr/2020 09:06:03 [PeriodicActivities.cpp:165] Each periodic activity script will use 5 threads
29/Apr/2020 09:06:03 [NetworkInterface.cpp:2343] Started packet polling on interface re0 [id: 1]...
29/Apr/2020 09:06:03 [NetworkInterface.cpp:2343] Started packet polling on interface re1 [id: 2]...
29/Apr/2020 09:06:03 [NetworkInterface.cpp:2343] Started packet polling on interface lo0 [id: 3]...
29/Apr/2020 09:06:03 [NetworkInterface.cpp:2343] Started packet polling on interface ovpns1 [id: 4]...
29/Apr/2020 10:00:01 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 10:00:15 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 10:01:08 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 11:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 11:00:49 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 11:01:37 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 12:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 12:00:49 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 12:01:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 13:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 13:00:52 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 13:01:54 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 14:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 14:00:12 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 14:01:11 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 15:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 15:00:12 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 15:01:03 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 16:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 16:01:09 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 16:01:55 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 17:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 17:00:12 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 17:01:05 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 18:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 18:00:53 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 18:01:53 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 19:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 19:00:51 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 19:01:39 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 20:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 20:00:12 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 20:01:23 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 21:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 21:00:46 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 21:01:57 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 22:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 22:00:12 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 22:00:57 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 23:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 23:00:50 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
29/Apr/2020 23:01:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 00:00:01 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 00:00:49 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 00:01:35 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 01:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 01:00:47 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 01:00:57 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 02:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 02:00:47 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 02:00:57 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 03:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 03:00:46 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 03:00:57 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 04:00:01 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 04:01:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 04:01:11 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 05:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 05:00:08 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 05:01:07 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 06:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 06:00:12 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 06:01:14 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 07:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 07:01:18 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 07:02:06 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 08:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 08:00:57 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 08:01:43 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 09:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 09:00:47 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 09:00:57 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 10:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 10:00:12 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 10:01:02 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 11:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 11:00:49 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 11:01:36 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 12:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 12:00:11 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 12:01:04 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 13:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 13:00:57 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 13:01:42 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 14:00:00 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 14:00:12 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 14:01:02 [LuaEngine.cpp:3405] ERROR: Unable to enable capabilities
30/Apr/2020 14:01:03 [LuaEngine.cpp:12141] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/system/discover.lua][attempt to index a string value]
01/May/2020 08:17:45 [main.cpp:380] Logging onto /var/db/ntopng/ntopng.log
01/May/2020 08:17:45 [main.cpp:383] Working directory: /var/db/ntopng
01/May/2020 08:17:45 [main.cpp:385] Scripts/HTML pages directory: /usr/local/share/ntopng
01/May/2020 08:17:45 [Ntop.cpp:437] Welcome to ntopng amd64 v.4.0.200422 - (C) 1998-20 ntop.org
01/May/2020 08:17:45 [Ntop.cpp:863] Adding xx/128 as IPv6 interface address for re0
01/May/2020 08:17:45 [Ntop.cpp:873] Adding xx/64 as IPv6 local network for re0
01/May/2020 08:17:45 [Ntop.cpp:832] Adding xx/32 as IPv4 interface address for re0
01/May/2020 08:17:45 [Ntop.cpp:841] Adding 72.192.132.0/22 as IPv4 local network for re0
01/May/2020 08:17:45 [Ntop.cpp:832] Adding 192.168.1.1/32 as IPv4 interface address for re1
01/May/2020 08:17:45 [Ntop.cpp:841] Adding 192.168.1.0/24 as IPv4 local network for re1
01/May/2020 08:17:45 [Ntop.cpp:863] Adding xx/128 as IPv6 interface address for re1
01/May/2020 08:17:45 [Ntop.cpp:873] Adding xx/64 as IPv6 local network for re1
01/May/2020 08:17:45 [Ntop.cpp:863] Adding ::1/128 as IPv6 interface address for lo0
01/May/2020 08:17:45 [Ntop.cpp:873] Adding ::1/128 as IPv6 local network for lo0
01/May/2020 08:17:45 [Ntop.cpp:863] Adding fe80::1/128 as IPv6 interface address for lo0
01/May/2020 08:17:45 [Ntop.cpp:873] Adding fe80::1/64 as IPv6 local network for lo0
01/May/2020 08:17:45 [Ntop.cpp:832] Adding 127.0.0.1/32 as IPv4 interface address for lo0
01/May/2020 08:17:45 [Ntop.cpp:841] Adding 127.0.0.0/8 as IPv4 local network for lo0
01/May/2020 08:17:45 [Ntop.cpp:863] Adding xx/128 as IPv6 interface address for ovpns1
01/May/2020 08:17:45 [Ntop.cpp:873] Adding xx/64 as IPv6 local network for ovpns1
01/May/2020 08:17:45 [Ntop.cpp:832] Adding 192.168.2.1/32 as IPv4 interface address for ovpns1
01/May/2020 08:17:45 [Ntop.cpp:841] Adding 192.168.2.1/32 as IPv4 local network for ovpns1
01/May/2020 08:17:45 [PeriodicActivities.cpp:105] Started periodic activities loop...
01/May/2020 08:17:51 [PeriodicActivities.cpp:165] Each periodic activity script will use 5 threads
01/May/2020 08:17:51 [NetworkInterface.cpp:2343] Started packet polling on interface re0 [id: 1]...
01/May/2020 08:17:51 [NetworkInterface.cpp:2343] Started packet polling on interface re1 [id: 2]...
01/May/2020 08:17:51 [NetworkInterface.cpp:2343] Started packet polling on interface lo0 [id: 3]...
01/May/2020 08:17:51 [NetworkInterface.cpp:2343] Started packet polling on interface ovpns1 [id: 4]...
mkc@firewall:/var/db/ntopng %

Any help greatly appreciated!

**Comment by emanuele-f** [comment]
Please specify the ntopng options used

**Comment by simonemainardi** [comment]
did you compile it from source?

**Comment by mcat528** [comment]
No, added by update to OPNsense. Seems to run OK for awhile, then dies.

r/mark

************************************************************************
 Mark Catlin, CISSP
 Voice: 619.987.5288
 email: us46865@gmail.com

**Comment by simonemainardi** [comment]
@madpilot78 Do you think you can help @mcat528? Thank you.

**Comment by madpilot78** [comment]
This is not easy to debug, Not sure how OPNSense compiles it's packages and which options are used for compiling the embedded FreeBSD system they use.

@mcat528 Have you reported this to the OPNsense support or community support? Are there other users with similar issues?

**Comment by madpilot78** [comment]
@mcat528 BTW, are you able to get a core dump from the crash? Maybe that could help.

**Comment by mcat528** [comment]
Sure, can you tell me where the dump would be. I'll post is.

**Comment by madpilot78** [comment]
@mcat528 

> Sure, can you tell me where the dump would be. I'll post is.

A core dump is not produced by default, you need to run the software withing a debugger, like gdb.

I'm sorry I have never used OPNSense and have not been using PFSense for a long time, so I don't know if those tools have facilities to do that easily. It would most probably involve using the console.

You should really check OPNSense documentation or get it touch with their community or support to get information on how to debug software crashes on their platform.

I'm not even sure how OPNSense packages are built and how much they differ from FreeBSD ports/packages.

I notice there is a new version of OPNSense (20.1.6), you should try updating also.

One thing I notice is that OPNSensse seems to be based on FreeBSD version 11.2, which is not supported anymore. Supported version is 11.3, with 11.4 planned to be released by this summer.

It's not your fault but ported software is not tested in anyway against 11.2 and this could be related.

**Comment by mcat528** [comment]
OK, I understand on the core dump (I read up on gdb last night). The funny thing is, ntopng runs fine for some amount of time then it just dies. I will keep researching the issue...maybe just go back to pfsense at some point. Thank you for the help!
