### ISSUE TITLE
Enable SNMP menu

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3872]
In nEdge mode (enterprise) the SNMP menu should be enabled

**Comment by simonemainardi** [comment]
This involves:

- Changing the C part which doesn't compile SNMP on nEdge
- Adding the entry in the nEdge menu
- Review the boolean checks: isEnterprise() returns false on nEdge, nEdge is never isEnterprise(), nEdge is either isnEdge() [for the pro] and isnEdgeEnterprise() [for the enterprise]

**Comment by cardigliano** [comment]
Implemented
