### ISSUE TITLE
Memory leak when having expired SSL certifcates

### ISSUE THREAD

**Issue by hvdbrand** [ntop/ntopng#3873]
I  run ntopng v.4.1.200503 on my own CentOS server for fun.
I have been using a self-signed SSL certificate.
It was generated using the following instructions in
/usr/share/ntopng/httpdocs/ssl/README:

> # openssl req -new -x509 -sha1 -extensions v3_ca -nodes -days 365 -out cert.pem
> # cat privkey.pem cert.pem > ntopng-cert.pem

According the the ntopng logging the certificate expired. (I did not check that it did, nor do I remember when I made the certificate, I expect this information to be correct).

While having an expired certificate, the memory usage of ntopng kept increasing.
In fact, within one or two minutes it takes too much memory and causes a crash.

This happened both when using -W=3001 and -w=3001 in /etc/ntopng/ntopng.conf.
I use systemd to start/stop ntopng. I would expect the issue to only happen when using a secured connection with -W.

I have generated a new certificate pair and therefore i am no longer suffering from this issue.
However, I wanted to report it anyway.

**Comment by emanuele-f** [comment]
So if you only add `-w=3001` (without `-W`) the problem still occurs? Are you sure that this does not happen when not using `-w`/`-W`? How much time does it take to reproduce the issue?

**Comment by emanuele-f** [comment]
Tested with an expired certificate generated with the above command and I cannot see leaks/crash. Closing as no feedback has been received. If you still experience a crash, please open a new issue and report the stack trace as explained in https://github.com/ntop/ntopng/blob/dev/doc/README.crash

[ntopng-cert.pem.zip](https://github.com/ntop/ntopng/files/4609653/ntopng-cert.pem.zip)

**Comment by hvdbrand** [comment]
I also tested it again with an expired certificate and cannot reproduce
the issue.

**Comment by lucaderi** [comment]
Good so we assume it is closed by now. Thank you
