### ISSUE TITLE
High cpu usage with continuous ping

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3874]
The continuous ping thread shows an high cpu usage. The issue seems in the `sleep(1)` call.

![photo_2020-05-04_15-29-32](https://user-images.githubusercontent.com/5488003/80980615-60a4e500-8e18-11ea-88b0-a858bd7d3516.jpg)

**Comment by emanuele-f** [comment]
Can be reproduced with `top -p $(pgrep ntopng) -H` on linux

**Comment by JVital2013** [comment]
I have this same issue. `top -p $(pgrep ntopng) -H` shows just "PingLoop" for me

**Comment by marcusique** [comment]
I've just updated to a new version and noticed that ntopng uses 100% of one of the CPU cores. 

`v.4.1.200511    [Enterprise/Professional/Embedded build]
GIT rev:        dev:812afd9862bff34643c24981a6110b91b94701e4:20200511
Pro rev:        r2868
Built on:       Raspbian GNU/Linux 10 (buster)
System Id:      441BA6D8499602D2
Platform:       armv7l
Edition:        Enterprise Embedded
License Type:   Time-Limited [Empty license file]
Validity:       Until Tue May 12 10:57:32 2020`

Here's my `top -p $(pgrep ntopng) -H`:
![image](https://user-images.githubusercontent.com/23212368/81662698-3cf82500-943e-11ea-9ff2-e37b78349abb.png)
