### ISSUE TITLE
Widget schema are not sorted alphabetically

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3878]
![Screen Shot 2020-05-04 at 21 06 35](https://user-images.githubusercontent.com/4493366/81003433-2d2f7e00-8e4b-11ea-82ac-36f1d6a0a600.png)

**Comment by gabryon99** [comment]
fixed in https://github.com/ntop/ntopng/commit/b442a1da213deebfa9c7aaec52d81730e7d198d1
