### ISSUE TITLE
Collapse elements when more than one

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3879]
In the picture below
![Screen Shot 2020-05-04 at 21 07 53](https://user-images.githubusercontent.com/4493366/81003552-594aff00-8e4b-11ea-8125-136d76e5ca04.png)
at most one element should be expanded. When expanding an element all the other must be collapsed to avoid scrolling or visualisation issues

**Comment by gabryon99** [comment]
fixed in https://github.com/ntop/ntopng/commit/0428f751abf1155febe148ea0fa2f08f968d13aa
