### ISSUE TITLE
Datasource save does not work as expected

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3880]
![Screen Shot 2020-05-04 at 21 10 08](https://user-images.githubusercontent.com/4493366/81003777-afb83d80-8e4b-11ea-9407-df82fb68ebe1.png)

then click save. The click edit

![Screen Shot 2020-05-04 at 21 10 19](https://user-images.githubusercontent.com/4493366/81003970-f9088d00-8e4b-11ea-80ce-ac4ff12bad54.png)

and as you can see the previous saved setting is lost

**Comment by gabryon99** [comment]
fixed in https://github.com/ntop/ntopng/commit/d9a4437a47db8b9c7be1a9f75d695a9b58394454
