### ISSUE TITLE
Prevent from adding the same metric twice 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3881]
![Screen Shot 2020-05-04 at 21 13 15](https://user-images.githubusercontent.com/4493366/81004055-16d5f200-8e4c-11ea-8f34-f3a08fc6375e.png)

**Comment by gabryon99** [comment]
<img width="793" alt="Screenshot 2020-07-06 at 11 33 50" src="https://user-images.githubusercontent.com/14114916/86578730-92533d00-bf7c-11ea-920c-a58af4abe5b3.png">
 Fixed

**Comment by gabryon99** [comment]
See: https://github.com/ntop/ntopng/commit/f8dac7967d0d3663c2592cd6dace3a60d5d6cc6c
