### ISSUE TITLE
Probe communication error

### ISSUE THREAD

**Issue by M9k** [ntop/ntopng#3884]
Hi,
I'm using the last version of Ntopng Enterprise and Nprobe on two CentOS VM.
Yesterday I updated both of them to the last version and it work for some time. today I checked and it doesn't detect any traffic.

With tcpdump I see the probe receive the flow and talk with ntop and with "systemctl status ntopng -l" I only see the log "collecting flows on NPROBE_IP:5556", no errors.

This is the interface:
![Ntop interface](https://user-images.githubusercontent.com/9288402/81042921-8500d000-8eb1-11ea-8b8f-1285754b3a9e.png)

I use dynamic dissagregation by ip probe, but the dissagregated interface doesn't appear.
I try to set the dissagregation to off and reboot but it still doesn't work.

Thanks.

**Comment by cardigliano** [comment]
Please provide:
- ntopng --version
- nprobe --version
- the nprobe configuration file
Thank you

**Comment by M9k** [comment]
Hi,
ntopng --version
```
v.4.1.200505    [Enterprise/Professional build]
GIT rev:        dev:dd293f9f02872aa573593d69e88be55a0d115c56:20200505
Pro rev:        r2861
Built on:
System Id:      XXXXXXXXXXXXXXX
Platform:       x86_64
Edition:        Enterprise M
License Type:   Permanent
Maintenance:    Until Fri Jul 31 10:43:22 2020 [86 days left]
License:      XXXXXXXXXXXXXXXX
```
nprobe --version
```
Welcome to nProbe v.9.1.200505 (r6853) for x86_64-unknown-linux-gnu
with native PF_RING acceleration.
Copyright 2002-20 ntop.org

Build OS:      CentOS Linux release 7.7.1908 (Core)
SystemID:      XXXXXXXXXXXXXXXXX
GIT rev:       dev:d9b2b6d1e8e0e6018732b0210a02359e1dbca5f4:20200505
Edition:       nProbe Standard
License:       XXXXXXXXXXXXXXXXX
```
cat /run/ntopng.conf
```
--online-license-check
-i=tcp://192.168.X.Y:5556
-i=tcp://192.168.Z.K:5556
-m=10.0.0.0/8,192.168.0.0/16,172.16.0.0/12
```
The probe is 192.168.X.Y

I have two nprobe running,  it's normal? I use systemd to manage the service.

```
nprobe     6572  0.3  1.2 507740 21400 ?        Ssl  13:19   0:00 /usr/local/bin/nprobe /run/nprobe-nprobe.conf
nprobe     6575  0.2  1.1 507740 21044 ?        Ssl  13:19   0:00 /usr/local/bin/nprobe /run/nprobe.conf
```
cat /run/nprobe.conf
```
--online-license-check
--verbose=2
--zmq=tcp://192.168.XXX.XXX:5556
-i=none
-n=none
--collector-port=2055
```

cat /run/nprobe-nprobe.conf
```
--online-license-check
--verbose=2
--zmq=tcp://*:5556
-i=none
-n=none
--collector-port=2055
-L=192.168.2.0/24
```

Thanks

**Comment by M9k** [comment]
I try to stop the nprobe service, then only "nprobe /run/nprobe-nprobe.conf" remains.
If I reboot the VM both are launched.
If I kill -9 the second one it automatically restarted.

So i stop the service and kill the second one, so it was restarted on its own and now it seem to work.

I think the problem is in the configuration of the machine, I will ask my colleague to check.
I don't think it's a problem of nprobe, so please close the issues if you want.

Thank a lot.
