### ISSUE TITLE
Active monitoring ping losing data

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3887]
Run a manual ping and experienced a ZERO packet loss:

```
$ date
Tue May  5 15:22:30 CEST 2020
$ ping -q repubblica.it
PING repubblica.it (213.92.16.101): 56 data bytes
^C
--- repubblica.it ping statistics ---
6060 packets transmitted, 6060 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 17.908/20.593/207.882/11.755 ms
```

In parallel, ntopng ICMP was wrunning and reported this:

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/3397663/81081771-a504b380-8ef2-11ea-9165-728244da894a.png">

Resolved address is the same:

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/3397663/81081830-b64dc000-8ef2-11ea-9f1d-79ccec427f50.png">

So host is clearly reachable even when ntopng says it is not.

**Comment by lucaderi** [comment]
![Screen Shot 2020-05-05 at 22 19 40](https://user-images.githubusercontent.com/4493366/81112208-959b5f80-8f1e-11ea-842e-65957ac68bf7.png)
Current;y unable to reproduce the error reported
