### ISSUE TITLE
Mysql on MyISAM

### ISSUE THREAD

**Issue by morganm** [ntop/ntopng#389]
I'm using ntopng on a raspberrypi 2 running ArchLinux. Great setup and I'm very happy with ntopng here. I recently upgraded from 2.x series to v.2.3.160212 (GIT rev:   ::20160212) and wanted to configure the mysql historical reporting.

First attempt, this worked, but the pi became extremely sluggish due to I/O writes to the SD card. Some internet research indicates this is a known problem with Mysql/InnoDB tables and that using MyISAM resolves the issue. So I switched the default table type to MyISAM, rebuilt the DB and restarted ntopng. Then I hit this error:

```
Feb 12 14:44:28 pi21 ntopng[2906]: 12/Feb/2016 14:44:28 [MySQLDB.cpp:293] ERROR: MySQL error: [Specified key was too long; max key length is 1000 bytes][CREATE TABLE IF NOT EXISTS
 `ntopngv6_0` (`idx` int(11) NOT NULL auto_increment,`VLAN_ID` smallint unsigned, `L7_PROTO` smallint unsigned,`IP_SRC_ADDR` varchar(48), `L4_SRC_PORT` smallint unsigned,`IP_DST_A
DDR` varchar(48), `L4_DST_PORT` smallint unsigned,`PROTOCOL` tinyint unsigned, `BYTES` int unsigned, `PACKETS` int unsigned,`FIRST_SWITCHED` int unsigned, `LAST_SWITCHED` int unsi
gned,`INFO` varchar(255), `JSON` BLOB,INDEX(`idx`,`IP_SRC_ADDR`,`IP_DST_ADDR`,`FIRST_SWITCHED`, `LAST_SWITCHED`, `INFO`)) PARTITION BY HASH(`FIRST_SWITCHED`) PARTITIONS 32]
```

This [stackoverflow answer](https://stackoverflow.com/questions/3489041/mysqlerror-specified-key-was-too-long-max-key-length-is-1000-bytes) indicates VARCHARs take 3x as much room in an index, and elsewhere I see MyISAM is hard-coded to a 1000 byte limit, so I can't fix this in my install without a full recompile.

The math here for the index then is: (48x3) + (48x3) + (255x3) for src_addr, dst_addr and info, respectively. This totals 1053 bytes, a bit over the limit. I'm able to resolve the issue by manually creating the table and limiting the index like so:

`INDEX(`idx`,`IP_SRC_ADDR`,`IP_DST_ADDR`,`FIRST_SWITCHED`,`LAST_SWITCHED`,`INFO`(200))
`

(only indexing the first 200 bytes of the Info column)

I don't know if ntopng will ever expect to create additional tables, if so then my manual workaround for now is just a ticking timebomb until it tries to create the next table, so I'm reporting the issue here so that it can be fixed in the source.

**Comment by simonemainardi** [comment]
Thanks for pointing this out. Ntopng won't create extra tables so your workaround is safe. I've just added a fix into the dev branch.

Using varchars is not the best way to store IPv6 but unfortunately MySQL IPv6 support is only available starting with 5.6 (http://dev.mysql.com/doc/refman/5.6/en/miscellaneous-functions.html#function_inet6-aton). For this reason we decided to keep them as strings to ensure greater compatibility.

Upgrading the data type is something we will do in the future.
