### ISSUE TITLE
Launchdaemon issue on MacOS package

### ISSUE THREAD

**Issue by pmabey** [ntop/ntopng#3890]
Spent a couple days troubleshooting why after 5 minutes I could no longer login to the web interface using the latest macOS official package. After lots of re-installs I found the problem was simply that the bundled redis server was not picking up a config file. I modified the LaunchDaemon file to add this line:

<string>/usr/local/etc/redis.conf</string>

and now everything works great. Without this it was loading without any config file.

**Comment by lucaderi** [comment]
Thank you. I am updating the package and uploading it on http://packages.ntop.org. Please confirm it works now.

**Comment by pmabey** [comment]
I don't know enough about LaunchDaemon itself but it looks like the parameters need to be on separate lines. The new build had this but redis would not start:
<string>/usr/local/bin/ntopng-redis-server /usr/local/etc/redis.conf</string>

If I split up the parameter to the following everything fires up fine:
<string>/usr/local/bin/ntopng-redis-server</string>
<string>/usr/local/etc/redis.conf</string>
