### ISSUE TITLE
Multiple CSRF not needed

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3894]
Once https://github.com/ntop/ntopng/issues/3866 is implemented, it is requested to remove those multiple CSRF as no longer needed https://github.com/ntop/ntopng/commit/9973d63847ad53947eb47670440403510a4fe704#diff-01c8ea3bf73eb8b6cd9c09b1b4e48018R41

**Comment by simonemainardi** [comment]
same applies to user scripts

**Comment by gabryon99** [comment]
fixed in https://github.com/ntop/ntopng/commit/6ada544339196273a6fcd0f7d44e0b7c58f45b3d

**Comment by emanuele-f** [comment]
There are still places where such CSRF token are passed without need, e.g. https://github.com/ntop/ntopng/blob/dev/scripts/plugins/active_monitoring/web_gui/edit_active_monitoring_host.lua#L24 . Removing such tokens breaks the subsequent form submission, so the js code should also be modified. Please review the entire code base via a grep.

**Comment by lucaderi** [comment]
![Screen Shot 2020-05-08 at 11 35 23](https://user-images.githubusercontent.com/4493366/81393272-5d636f00-9120-11ea-8b66-a7602db56dd8.png)
If in continuous monitoring you do
- add host: everything goes well
- add a new host: the above error is produced

**Comment by emanuele-f** [comment]
Issue with the above form fixed in 44337e83ee4377c4af3450bbe52370c5761c8c15 . Proceeding with the cleanup.

**Comment by emanuele-f** [comment]
Cleanup completed in af842e4aa66d2dd05d13a1496fba7ea60688c2d7 and corresponding pro commit.
