### ISSUE TITLE
edit_endpoint.lua data submitted with POST is not valid

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3896]
Posting all data as JSON opens up a series of security issues.

Each parameter must be passed individually and validated using functions in http_lint.

Validation function is chosen depending on the endpoint field type. Any additional validation function which is not in http_lint.lua must be placed in a plugin-specific http_lint.lua

See `scripts/plugins/active_monitoring/http_lint.lua` for reference.

**Comment by lucaderi** [comment]
Sorry @simonemainardi POST is the way to go. If you complain about validation, then http_lint should handle POST, but yours isn't an argument for adding a weakness.

**Comment by simonemainardi** [comment]
POST is the way to go. The complain is that now only a JSON is passed with the POST and is not validated, ending up in saved stuff like this

![image](https://user-images.githubusercontent.com/3397663/81229660-7967f300-8ff0-11ea-9ca1-68d79dc42fde.png)

POSTed data must NOT be a JSON, but a series of individually-validated elements.

**Comment by gabryon99** [comment]
fixed in: https://github.com/ntop/ntopng/commit/19edceec4cde5dfd4b79343e8884474788367bdf
