### ISSUE TITLE
Stored XSS in endpoint names

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3899]
![image](https://user-images.githubusercontent.com/3397663/81230249-6a357500-8ff1-11ea-96ed-33340902949d.png)

![image](https://user-images.githubusercontent.com/3397663/81230262-702b5600-8ff1-11ea-958d-916ea6a882d2.png)

only allow ASCII and underscores in endpoint names. Must use http_lint validation

**Comment by gabryon99** [comment]
fixed in: https://github.com/ntop/ntopng/commit/19edceec4cde5dfd4b79343e8884474788367bdf
