### ISSUE TITLE
Loading of historical data broken when using external flow-collector

### ISSUE THREAD

**Issue by shadow974** [ntop/ntopng#39]
i have the same problem like described in this mailing-list:
 http://www.gossamer-threads.com/lists/ntop/misc/37261

Is there any timerange in which this refactoring will be done?

**Comment by ariava** [comment]
@shadow974 we are starting just now the development roadmap towards 2.1. Our roadmap includes fixing the historical interface and adding new features, so stay tuned.

**Comment by kg6hum** [comment]
I am also seeing this issue.  I have an nBox collecting data and sending it back to ntopng 1.99.150530 running in a docker container.  The historical interface does not work in this situation, which makes the nBox probe not very useful.  Is there any idea of how long the 2.1 release will take?

**Comment by lucaderi** [comment]
The historical interface will be strongly recoded. For the time being please use ElasticSearch to dump historical data or the reporting capabilities available in the pro version. If you have suggestions on how/what the new historical interface should do, please file an enhancement issue. Thanks.

**Comment by drolfe** [comment]
+1 This is effecting us as well, Can't wait for 2.1 to be finished to get this resolved, is it still going to be a sqlite back-end or will there be other options for historical reporting ?

**Comment by lucaderi** [comment]
The current option is ElasticSearch.

**Comment by drolfe** [comment]
Will the ntopng interface be able to pull data from ES or do you just mean to use Qbana ?

**Comment by lucaderi** [comment]
Will yes, 'is able'  is not. Today you can use your favourite tools to do that.

This said: why do you need the historical interface? Can you highlight some use cases?

**Comment by drolfe** [comment]
Hi,

for example, we often have software releases on the weekend, and sometimes the developers will complain about slow network performance.

So come Monday morning  Id like to look at what was using the network bandwidth at the times they said it was slow etc..

Regards, Daniel

**Comment by lucaderi** [comment]
I have updated the dat files. overnight new packages will be built containing them

**Comment by shadow974** [comment]
Hi,

yes, same use case here. The reporting feature in the professional-edition is not detailed enough to find the "bad guy" who caused the traffic spikes at time "x" in the past..

Regards, Karl

**Comment by lucaderi** [comment]
You have the top talkers on each graph, so you can see what causes the bandwidth issues
![screen shot 2015-07-13 at 23 17 28](https://cloud.githubusercontent.com/assets/4493366/8661079/5c32d076-29b5-11e5-8811-bb7413489029.png)
.

**Comment by kg6hum** [comment]
As an ISP, we need to look at traffic during "peak usage" hours, as well as the differences in traffic over time.  Since we are a small ISP, we do not have someone in our office during those "peak usage" hours to look at the data.  We would like to have historical data so we can look at the usage during the day and also look at trends in the traffic over time.  I am not opposed to using ElasticSearch, but we would need a nice dashboard to view the data.

**Comment by lmangani** [comment]
The point of the external collector and using ntopng as a probe feeding data into it is indeed to allow ISPs small and big to build their own metric sets on a vastly more flexible platform such as ES (a few dashboards are provided in Qbana as model, but they literally take just minutes to build when familiar with the ntopng dataset) and enabling activity over any timerange - while ntopng works great as controller and realtime dashboard until the reverse side (client to metrics) is implemented in future versions.

**Comment by shadow974** [comment]
Ok, but the Graph you showed is also broken because of #57. It shows me spikes of 10 Gbit/s and more on a 100 Mbit/s interface caused by the periodically transmitted data from nprobe.

**Comment by lucaderi** [comment]
This is not broken but it works like that. If you have a probe that emits flows every 30 sec or so you will see traffic spikes as the traffic of 30 sec is aggregated in one sec basically. We have plan extend the probe to send periodic traffic info for interface stats.

**Comment by shadow974** [comment]
How far are these plans? The two most critical features for my company are getting meaningful live-data without those peaks and the ability to track down the IP who caused the most traffic in a selectable time-range. Could a donnation "help" with the development of these features? :)

**Comment by lucaderi** [comment]
@shadow974 A donation can definitively help, but before talking about that I have said we need to recode the historical support because it was conceived with different requirements in mind. Now can you please list the requirements you would it to satisfy?

**Comment by shadow974** [comment]
We try to use ntopng with a bunch of nprobe sources to collect data from different locations. This should enable us to catch specific hosts generating uncommon traffic. We already have bandwith monitorings to get the exact time-range when this happens but no way to get the source of the problem.

The graph you showed would be the perfect solution but does not work with nprobe sources, actually.
Selecting a specific time-range and get the "top-talkers" listing...

**Comment by lucaderi** [comment]
We're rewriting the historical interface. Please follow #61.
