### ISSUE TITLE
About ntopng edge Captive Portal

### ISSUE THREAD

**Issue by Michiko0109** [ntop/ntopng#3901]
When Captive Portal is enabled, terminal under ntopng edge cannot connect to the Internet.
The terminal is Windows 10 64bit.
The terminal is registered as a user of nedge.
We can connect to the Internet by disabling the captive portal.

Is it possible to use Wired connection and captive portal at the same time on nEdge?

**Comment by simonemainardi** [comment]
With the captive portal enabled, turn of and on again the network interface which connects the host to the internet. Please report.

**Comment by Michiko0109** [comment]
Thanks to your advice, the problem has been resolved.
