### ISSUE TITLE
/rest/get/alert/data.lua Performance

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3902]
A user has profiled the endpoint and highlighted how the time is spent. This should be used to accelerate the performance

> Request start, delta info is based on os.clock

> 2020-05-06 09:58:25 alert/data.lua - START
> Here we got the records from the database, just took a few millseconds
> 2020-05-06 09:58:26 delta: 0.072648000001209 alert/data.lua - got 10399 records from getAlerts
> Afterwards the alert/data.lua script is processing the data and generates the result table
> 2020-05-06 09:58:29 delta: 2.7534790000063 alert/data.lua - postprocessing done
> The result table is json encoded, this takes another second
> 2020-05-06 09:58:29 delta: 3.4450499999803 alert/data.lua - finished json encoding
> Response sent to server
> 2020-05-06 09:58:31 delta: 3.489356999984 alert/data.lua - response sent
> Most of the cpu time is consumed in the for loop when iterating the alerts from the getAlert call.
> Specifically the formatAlertMessage is complex. I have added some caching to various lookups in the lua code
> and could cut the cpu time in half.
> 2020-05-06 14:00:05 alert/data.lua - START
> 2020-05-06 14:00:05 delta: 0.067749000008916 alert/data.lua - got 10463 records from getAlerts
> 2020-05-06 14:00:08 delta: 1.438455000025 alert/data.lua - postprocessing done
> 2020-05-06 14:00:08 delta: 2.0952170000237 alert/data.lua - finished json encoding
> 2020-05-06 14:00:10 delta: 2.1326680000057 alert/data.lua - response sent
> OLD VERSION: 2020-05-06 09:58:29 delta: 2.753479000006 alert/data.lua - postprocessing done
> NEW VERSION: 2020-05-06 14:00:08 delta: 1.438455000025 alert/data.lua - postprocessing done

**Comment by schnetzzz** [comment]
Hi Simone,
one example to speed up redundant calls.

This function here receives an entity_id. To find the result it has to iterate through the list of alert_consts.alert_entities.
```
function alert_consts.alertEntityRaw(entity_id)
  entity_id = tonumber(entity_id)

  for key, entity_info in pairs(alert_consts.alert_entities) do
    if(entity_info.entity_id == entity_id) then
      return(key)
    end
  end
end
```
If the query from the database returns 10000 records, this function is called 10000 times, resulting in 10000 alert_consts.alert_entities lookups. There is no reason do this over and over again.
The number of entity_id variations is limited. So you can introduce some caching here.

The following code is written by a guy without any deeper lua knowlege - me :)
```
local alert_entity_raw_cache = {}

function alert_consts.alertEntityRaw(entity_id)
  if alert_entity_raw_cache[entity_id] ~= nil then
    return alert_entity_raw_cache[entity_id]
  end

  nr_entity_id = tonumber(entity_id)

  for key, entity_info in pairs(alert_consts.alert_entities) do
    if(entity_info.entity_id == nr_entity_id) then
      alert_entity_raw_cache[entity_id] = key
      return(key)
    end
  end
end
```
I've seen several functions in alert_consts.lua which might also profit from this basic caching.
By adding this type of caching to 4 different functions I could cut the processing time for 10000 records in half.

**Comment by cardigliano** [comment]
migrated to /rest/v1/get/alert/data.lua with optimizations
