### ISSUE TITLE
Top L7 contacts reported for the wrong host in nindex

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3905]
![photo_2020-05-07 11 38 04](https://user-images.githubusercontent.com/4493366/81279313-43118e80-9057-11ea-9e22-3e822c21c060.jpeg)
As you can see the top L7 contacts are not correct for the displayed host, as at least one of the peers has to be the host being displayed.

**Comment by emanuele-f** [comment]
Cannot reproduce, waiting for more information from the user

**Comment by simonemainardi** [comment]
Verified. When the host page is selected, the nIndex query contains the host, e.g., 

```
((TOP_TYPE & 1) AND (IPV4_SRC_ADDR=192.168.7.7 OR IPV4_DST_ADDR=192.168.7.7) AND (VLAN_ID=0) AND (IP_PROTOCOL_VERSION=4))
```

Will reopen if necessary when feedback is received.
