### ISSUE TITLE
Gathering syslog data to Ntop webpage

### ISSUE THREAD

**Issue by rhadeur** [ntop/ntopng#3906]
Hey,
I have approx 300 servers which send their syslog events login iptables log etc to a remote rsyslog server.
I would like to see these logs in the ntopng site. 

I already setup a relay on my rsyslog, and I see from the iptables log, the messages are sent, my question what is needed to be setup from ntopng site, to be able to see what is in the syslog messages.
Many thanks,
Gábor

**Comment by simonemainardi** [comment]
Please attach some examples of the syslog. I think we should create something like `syslog.lua`. What do you think @cardigliano?

**Comment by rhadeur** [comment]
Client config:
syslog-ng
destination d_net { udp("10.15.0.9" port(514) log_fifo_size(1000)); };
log {  source(s_src); destination(d_net); };

When I use Syslog server:

destination d_mysql {
          sql(type(mysql)
          host("localhost") username("user-removed") password("password removed")
          database("syslog") table("logs")
          columns("facility", "priority", "date", "time", "host", "message")
          values("$FACILITY","","$YEAR-$MONTH-$DAY", "$HOUR:$MIN:$SEC","$HOST_FROM","$MSG")
          indexes("facility", "priority", "date", "time", "host", "msg"));
};
When I use rsyslog as relay:

*.*  action(type="omfwd" target="10.1.0.131" port="9999" protocol="tcp" action.resumeRetryCount="100" queue.type="linkedList" queue.size="10000")
cat: .: Is a directory


if the DB is used to put the logs on NTOP-ng, I can move everything to the same server
or I can store it in a same server.

**Comment by cardigliano** [comment]
In this ticket it is requested to trace system activities from all hosts in the network. They should be configured to send syslog to ntopng, however ntopng does not collect standard syslog events at the moment (it collects VPN events from firewalls, or alerts and flows from Suricata).
This means implementing a syslog plugin able to collect standard syslog messages, extract common events (e.g. user login/logout), and push alerts for the host.

**Comment by cardigliano** [comment]
@rhadeur this has been implemented, please read https://www.ntop.org/guides/ntopng/advanced_features/syslog.html#hosts-log-ingestion
