### ISSUE TITLE
Validation of Endpoint Fields

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3907]
This kind of inputs is accepted and validated as true. This MUST NOT happen. An error should be shown and no submit must be performed.

![image](https://user-images.githubusercontent.com/3397663/81333551-12584600-90a5-11ea-9c6d-f35a74a914ed.png)

Then the backend cleans them up but this must not happen. No submit.

![image](https://user-images.githubusercontent.com/3397663/81333646-2ef47e00-90a5-11ea-9e4f-b328deed478e.png)

same for

![image](https://user-images.githubusercontent.com/3397663/81333703-43387b00-90a5-11ea-85fb-81981ca4bd86.png)

As already asked in https://github.com/ntop/ntopng/issues/3899

> only allow ASCII and underscores in endpoint names. Must use http_lint validation

Please make sure to implement the requests before closing the issues

**Comment by simonemainardi** [comment]
Same:

![image](https://user-images.githubusercontent.com/3397663/81334022-ad512000-90a5-11ea-93ff-7474e9d2f24c.png)


delta is changed and garbled after submit. This must not happen

![image](https://user-images.githubusercontent.com/3397663/81334071-c063f000-90a5-11ea-9b3e-0a033e72a8dc.png)

**Comment by gabryon99** [comment]
Added domain name validation as requested. See: https://github.com/ntop/ntopng/commit/71870f51588d0d547d48607e363fe6a79a52c749

**Comment by simonemainardi** [comment]
still not valid:

![image](https://user-images.githubusercontent.com/3397663/81906728-fa158900-95c6-11ea-861b-5d83ca458dee.png)

Then once an invalid input has been inserted, it's not possible to remove it. Cliclick on 'remove' is ineffective, nothing happens, o errors:

![image](https://user-images.githubusercontent.com/3397663/81906828-24ffdd00-95c7-11ea-916d-9ef6ca37719b.png)

**Comment by simonemainardi** [comment]
emails:

![image](https://user-images.githubusercontent.com/3397663/81906973-60021080-95c7-11ea-9326-889df7603266.png)

**Comment by gabryon99** [comment]
I add a regex only for words:

<img width="1050" alt="Screenshot 2020-05-14 at 18 56 39" src="https://user-images.githubusercontent.com/14114916/81962858-a6319100-9614-11ea-8672-bd3f8fe3d523.png">
<img width="1050" alt="Screenshot 2020-05-14 at 18 56 52" src="https://user-images.githubusercontent.com/14114916/81962892-ae89cc00-9614-11ea-865e-baa7e4acb853.png">
<img width="1050" alt="Screenshot 2020-05-14 at 18 57 14" src="https://user-images.githubusercontent.com/14114916/81962935-bba6bb00-9614-11ea-90ec-b1eb75323da8.png">

**Comment by gabryon99** [comment]
For the email, I can't do much because of browser's validator
