### ISSUE TITLE
Empty recipient names accepted

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3908]
adding just four spaces allow the recipient to be saved

![image](https://user-images.githubusercontent.com/3397663/81334154-e8ebea00-90a5-11ea-938d-82edc9804e71.png)

**Comment by gabryon99** [comment]
add pattern for empty space: https://github.com/ntop/ntopng/commit/4984e0d653fc41291a7cafbcf58dc2ae92f0e069
