### ISSUE TITLE
Enforce Admin Privileges for Endpoint Notifications / Recipients 

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3909]
Code allows edits even to non-admin users. Prevent this and only show the entries in the menu if the user is an admin.

Also a return here: https://github.com/ntop/ntopng/commit/db9f3ecc03952892ff9afab78aecbe9202d64caf#diff-9925a752c646506e1f2dfe27910763beR17

**Comment by simonemainardi** [comment]
Invalid commit https://github.com/ntop/ntopng/commit/dc7a4c31bc1cc35ee819b05c6101d4100ad4413b

- page broken with non-existing function reportError
- there's no return after the check so page continue to allow non-admin users to work on endpoints

Revert the commit.

For non-JSON pages use function

```
if not haveAdminPrivileges() then
  return
end
```

For JSON pages just return empty and return.

**Comment by gabryon99** [comment]
Fixed and tested with non-admin user: https://github.com/ntop/ntopng/commit/237309fc580960907d9653987f7fd2aa1dccaa39
