### ISSUE TITLE
Use alert endpoint validation for email fields

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3910]
As said it is not acceptable to `validateUnquoted` these fields

![image](https://user-images.githubusercontent.com/3397663/81334886-02416600-90a7-11ea-8a64-2694831e9bcd.png)

Only allow ASCII and underscores for:
- endpoint_conf_name
- endpoint_conf_type

(maybe you can re use the validator for user scripts)

To validate:
-   ["smtp_server_name"]
-   ["sender"]
-   ["cc"]
-   ["to"]

You MUST:
- check the ntopng preferences -> alert endpoint -> email alert endpoint
- look at the names of the alert submitted fields
- re-use alert submitted fieldd names in `scripts/plugins/notification_endpoints/endpoints/email.lua` param names so that everything will be validated OK automatically

**Comment by gabryon99** [comment]
fixed as you described in: https://github.com/ntop/ntopng/commit/88635566acd6173f9e786b6935ec7aa1013bdd21
