### ISSUE TITLE
Order 1588866738 for Professional Enterprise does not come up with a license

### ISSUE THREAD

**Issue by nygc-jmaldonado** [ntop/ntopng#3914]
<img width="1437" alt="Screen Shot 2020-05-08 at 11 46 36 AM" src="https://user-images.githubusercontent.com/33460767/81423105-fb0b6e00-9121-11ea-9c4a-0cd1f5e873b4.png">

**Comment by simonemainardi** [comment]
Now that you have the order, you just need to generate the license: Visit https://shop.ntop.org/mkntopng/

Once the license has been generated, it will appear there.

**Comment by nygc-jmaldonado** [comment]
ntopng License Generator
The orderId you have specified is not valid for the product you have selected (see for details<https://shop.ntop.org/recover_licenses.html>). Please go back and try again.
