### ISSUE TITLE
Interface errors: no such device?

### ISSUE THREAD

**Issue by CyberbreinAirw0lf** [ntop/ntopng#3915]
Team,

This morning I found the following messages in the syslog:
<code> 
May  9 12:19:57 npm-2 n2disk[15274]: 09/May/2020 12:19:57 [n2disk.c:4207] Using packet timestamps from pf_ring
May  9 12:19:57 npm-2 n2disk[15274]: 09/May/2020 12:19:57 [n2disk.c:4228] ERROR: Unable to open PF_RING device eth0,eth2,eth3,eth4 [globals.ro.snaplen=1536]
May  9 12:19:57 npm-2 n2disk[15274]: 09/May/2020 12:19:57 [n2disk.c:1298] Caught termination signal -1...
May  9 12:19:57 npm-2 n2disk[15274]: 09/May/2020 12:19:57 [n2disk.c:6915] ERROR: Unable to initialize packet reader
May  9 12:19:57 npm-2 n2disk[15274]: 09/May/2020 12:19:57 [n2disk.c:6916] ERROR: Has the pf_ring kernel module been loaded ?
May  9 12:19:57 npm-2 systemd[1]: n2disk-ntopng@eth0_eth2_eth3_eth4.service: Main process exited, code=exited, status=255/n/a
May  9 12:19:57 npm-2 systemd[1]: n2disk-ntopng@eth0_eth2_eth3_eth4.service: Failed with result 'exit-code'.

May  9 12:20:03 npm-2 ntopng: [main.cpp:240] ERROR: An exception occurred during eth0,eth2,eth3,eth4 interface creation[19]: No such device
May  9 12:20:03 npm-2 ntopng[15442]: 09/May/2020 12:20:03 [main.cpp:240] ERROR: An exception occurred during eth0,eth2,eth3,eth4 interface creation[19]: No such d$
</code>

I checked with ifconfig => all interfaces are available.

In addition, the syslog is filled with update attempts.
As if there is a cron job of somesort that is running every minute.
However, the command "crontab -e" (after sudo-ed) doesn't show anything related to ntopng.

Any idea what happened? And how to solve it?

Please not that at the moment, no data is coming in.

Thank you - Will

**Comment by cardigliano** [comment]
@NogNeetMachinaal please provide the output of the below commands:

cat /proc/net/pf_ring/info
ifconfig

**Comment by CyberbreinAirw0lf** [comment]
See below:
<code>
root@npm-2:/home/will# ifconfig

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1800
        inet6 fe80::20c:29ff:fe5c:4395  prefixlen 64  scopeid 0x20<link>
        ether 00:0c:29:5c:43:95  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 120 (120.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.139.165  netmask 255.255.255.0  broadcast 192.168.139.255
        inet6 fe80::20c:29ff:fe5c:4377  prefixlen 64  scopeid 0x20<link>
        ether 00:0c:29:5c:43:77  txqueuelen 1000  (Ethernet)
        RX packets 2069013  bytes 814941214 (814.9 MB)
        RX errors 0  dropped 114000  overruns 0  frame 0
        TX packets 1741514  bytes 165968461 (165.9 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth2: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1800
        ether 00:0c:29:5c:43:9f  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1800
        inet6 fe80::20c:29ff:fe5c:4381  prefixlen 64  scopeid 0x20<link>
        ether 00:0c:29:5c:43:81  txqueuelen 1000  (Ethernet)
        RX packets 194814  bytes 12393093 (12.3 MB)
        RX errors 0  dropped 113999  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth4: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1800
        inet6 fe80::20c:29ff:fe5c:438b  prefixlen 64  scopeid 0x20<link>
        ether 00:0c:29:5c:43:8b  txqueuelen 1000  (Ethernet)
        RX packets 194813  bytes 12393033 (12.3 MB)
        RX errors 0  dropped 113998  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 4881985  bytes 829958634 (829.9 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4881985  bytes 829958634 (829.9 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


root@npm-2:/home/will# cat /proc/net/pf_ring/info

cat: /proc/net/pf_ring/info: No such file or directory

root@npm-2:/home/will#
</code>

**Comment by cardigliano** [comment]
It seems pf_ring is not loaded, did you follow the instructions at 
https://www.ntop.org/guides/pf_ring/get_started/packages_installation.html ?

**Comment by CyberbreinAirw0lf** [comment]
Yes - was part of the initial install.
Just give this another try:
<code>
root@npm-2:/home/will# apt-get install pfring
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 n2disk : Depends: pfring (= 7.6.0-2950) but 7.6.0-2963 is to be installed
 ntopng : Depends: pfring (= 7.6.0-2950) but 7.6.0-2963 is to be installed
 pfring : Depends: ndpi (= 3.2.0-2431) but 3.2.0-2426 is to be installed
 pfring-dkms : Depends: pfring (= 7.6.0-2940) but 7.6.0-2963 is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
root@npm-2:/home/will# apt --fix-broken install
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  n2disk ndpi ntopng pfring pfring-dkms
The following packages will be upgraded:
  n2disk ndpi ntopng pfring pfring-dkms
5 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
1 not fully installed or removed.
Need to get 16.8 MB of archives.
After this operation, 4,096 B disk space will be freed.
Do you want to continue? [Y/n] y
Err:1 http://packages.ntop.org/apt-stable/18.04 x64/ n2disk 3.4.200506-5197
  404  Not Found [IP: 167.99.215.164 80]
Err:2 http://packages.ntop.org/apt-stable/18.04 x64/ ntopng 4.0.200506-10123
  404  Not Found [IP: 167.99.215.164 80]
Get:3 http://packages.ntop.org/apt-stable/18.04 all/ pfring-dkms 7.6.0 [66.1 kB]
Err:3 http://packages.ntop.org/apt-stable/18.04 all/ pfring-dkms 7.6.0
  File has unexpected size (66140 != 66148). Mirror sync in progress? [IP: 167.99.215.164 80]
  Hashes of expected file:
   - SHA512:b8be81ee7d03458fb255d36329980623d860a9086980ddc99aa2f3d31595c61d2818c5b6fbab76ba63dececb                   3f76a5b3cf5775c40ca9ec4571fc70ddff58511a
   - SHA256:a91cb5cbd51f91e76176b2e04d2da0e59ceae2617c1f163c460103f391cf44d0
   - SHA1:7f9da7af2a41a687643c8a190c3ee954ffb287d3 [weak]
   - MD5Sum:b4f0dfbab2c2a4991e0051908a1f2b83 [weak]
   - Filesize:66148 [weak]
Err:4 http://packages.ntop.org/apt-stable/18.04 x64/ pfring 7.6.0-2963
  404  Not Found [IP: 167.99.215.164 80]
Err:5 http://packages.ntop.org/apt-stable/18.04 x64/ ndpi 3.2.0-2431
  404  Not Found [IP: 167.99.215.164 80]
E: Failed to fetch http://packages.ntop.org/apt-stable/18.04/x64/./n2disk_3.4.200506-5197_amd64.deb                     404  Not Found [IP: 167.99.215.164 80]
E: Failed to fetch http://packages.ntop.org/apt-stable/18.04/x64/./ntopng_4.0.200506-10123_amd64.deb                     404  Not Found [IP: 167.99.215.164 80]
E: Failed to fetch http://packages.ntop.org/apt-stable/18.04/all/./pfring-dkms_7.6.0_all.deb  File h                   as unexpected size (66140 != 66148). Mirror sync in progress? [IP: 167.99.215.164 80]
   Hashes of expected file:
    - SHA512:b8be81ee7d03458fb255d36329980623d860a9086980ddc99aa2f3d31595c61d2818c5b6fbab76ba63decec                   b3f76a5b3cf5775c40ca9ec4571fc70ddff58511a
    - SHA256:a91cb5cbd51f91e76176b2e04d2da0e59ceae2617c1f163c460103f391cf44d0
    - SHA1:7f9da7af2a41a687643c8a190c3ee954ffb287d3 [weak]
    - MD5Sum:b4f0dfbab2c2a4991e0051908a1f2b83 [weak]
    - Filesize:66148 [weak]
E: Failed to fetch http://packages.ntop.org/apt-stable/18.04/x64/./pfring_7.6.0-2963_amd64.deb  404                     Not Found [IP: 167.99.215.164 80]
E: Failed to fetch http://packages.ntop.org/apt-stable/18.04/x64/./ndpi_3.2.0-2431_amd64.deb  404  N                   ot Found [IP: 167.99.215.164 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
root@npm-2:/home/will#
</code>

**Comment by cardigliano** [comment]
Please try with:
apt-get clean all
apt-get update
apt-get install pfring-dkms

**Comment by CyberbreinAirw0lf** [comment]
Seems to work - thanks.
