### ISSUE TITLE
How to enable VirusTotal icon?

### ISSUE THREAD

**Issue by HWHS-Admin** [ntop/ntopng#3918]
In this page https://www.ntop.org/ndpi/trickbot-malware-analysis-using-ndpi-and-ntopng/, I saw VirusTotal icon in the Hosts page. But my ntopng couldn't see this VirusTotal icon. How to enable VirusTotal icon?

**Comment by simonemainardi** [comment]
Icon is automatically enabled for non-private ip addresses in ntopng version 4.1.
