### ISSUE TITLE
Synology Packet ntopng 

### ISSUE THREAD

**Issue by Francis89000** [ntop/ntopng#3919]
Installation was done with Synology packet.
No launch available in Synology in the menu section.
![image](https://user-images.githubusercontent.com/65024538/81558590-3c07ba80-938e-11ea-9a9f-3e90ee9bd4e5.png)

**Comment by simonemainardi** [comment]
We do not maintain nor support any synology packet. Our officially maintained packages are available at https://packages.ntop.org/. Please, use them or get in touch with the synology maintainer.
