### ISSUE TITLE
Stable repo for Debian

### ISSUE THREAD

**Issue by lzalewsk** [ntop/ntopng#392]
Is there any chance for stable repository for Debian (jesssie)?
http://packages.ntop.org/apt-stable/

For nightly builds [http://packages.ntop.org/apt/] there is.

By the way. For nightly builds (in case of debian) there is no possible to do: 
apt-get install pfring-drivers-zc-dkms
apt-get install pfring-drivers-dna-dkms

**Comment by lucaderi** [comment]
Not all drivers compile on debian. We advise you to use Ubuntu instead.
As of the stable repository I will keep this in mind.

**Comment by lucaderi** [comment]
Implemented
