### ISSUE TITLE
Timeseries menu improvements

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3923]
<img width="356" alt="Screenshot 2020-05-12 at 16 45 43" src="https://user-images.githubusercontent.com/4493366/81706201-29fe4880-9470-11ea-969c-16925118db9f.png">

- The menu is populated even when TS are not available
- Going too back in the past there is a JS error
- Begin time can be set to end time
<img width="901" alt="Screenshot 2020-05-12 at 16 48 50" src="https://user-images.githubusercontent.com/4493366/81706768-7fd2f080-9470-11ea-9320-2aaba75c5e6f.png">

**Comment by simonemainardi** [comment]
After internal review, we have seen that only the last update is used to determine whether to show or not any entry of the menu. This has the advantage of only reading RRD metadata but, on the other hand, may result in menu entries which don't have points in the selected interval.

Solution is to read RRDs to see if there are points in the selected interval. This may be expensive so complexity must be estimated before doing the activity. As an optimization, one can just start reading RRD metadata (as if they were a bloom filter) and then possibly do the actual reading.

Relevant part of the current code is in 

https://github.com/ntop/ntopng/blob/9c2af903e438ac8cdabe4bd167ee4e6b9f5f4a52/scripts/lua/modules/timeseries/drivers/rrd.lua#L768

Solution would change the method to accept both start and end time, and only return timeseries which have points between start and end. Changes must be implemented for all the supported timeseries drivers, i.e., InfluxDB and RRD.

**Comment by simonemainardi** [comment]
After internal review, we have decided to accept the use of last update as described in https://github.com/ntop/ntopng/issues/3923#issuecomment-630729132 to avoid expensive IO operations.
