### ISSUE TITLE
Export PCAP with BPF Filter causes problem

### ISSUE THREAD

**Issue by ajscam** [ntop/ntopng#3926]
Download PCAP file from if_stats.lua WITHOUT Filter (BPF).
Verify downloaded pcap file contains bidirectional data for, say, DNS.

Download PCAP file from if_stats.lua WITH Filter (BPF) of "port 53".
The downloaded PCAP file seems to only have 1 side of the traffic.

**Comment by cardigliano** [comment]
@ajscam we are not able to reproduce this, could you provide a pcap with some (bidirectional) data? Thank you.

**Comment by ajscam** [comment]
I tried emailing the 1 minute download (gzipped).  It is too large for
email.

I'd rather not attach it to the github issue...  Is there someplace else I
can email it?  ntop.org?

**Comment by simonemainardi** [comment]
send pcap download link via mail to cardigliano ntop org

**Comment by cardigliano** [comment]
@ajscam please note that your traffic is vlan tagged in one direction, BPF requires the "vlan" primitive in order to match packets with the vlan tag. In your case you should specify "(port 53) or (vlan and port 53)" as you have vlan in one direction only.

**Comment by cardigliano** [comment]
Please also note that the vlan is part of the flow key in ntopng, since you have the vlan in one direction only, this means that you see 2 different flows, one per direction. In order to avoid this you can add --ignore-vlans to the ntopng configuration.
