### ISSUE TITLE
Geomap Button is Missing on Private IPs

### ISSUE THREAD

**Issue by manjotsc** [ntop/ntopng#3927]
![Capture222](https://user-images.githubusercontent.com/51430971/81780306-50e66a00-94c4-11ea-8595-04e1b8b67974.PNG)

![Capture2222](https://user-images.githubusercontent.com/51430971/81780307-50e66a00-94c4-11ea-83cf-804c0c85b02d.PNG)

**Comment by simonemainardi** [comment]
Private IP addresses cannot be geolocated as they're private

**Comment by manjotsc** [comment]
@simonemainardi As you can see there is an option on older version, it is to see all connection coming in and going out  from that Private IP.

![Annotation 2020-05-13 043916 PNG](https://user-images.githubusercontent.com/51430971/81790915-0cfb6100-94d4-11ea-921d-25f5e433175d.jpg)
