### ISSUE TITLE
Bridge suddenly gone.

### ISSUE THREAD

**Issue by Cyndz136** [ntop/ntopng#393]
Hi Good Day,

last week i was able to bridge my two interface and then when i decided to open the ntop again (i didn't shutdown the laptop by the way since last week) and saw that the bridge was gone and when i issued the bridging command again i cannot do it. also is there a way to put it back again.

Also if possible do you have Video Tutorials on how to do the bridging and the right way of configuring the bridge (BUMP in the Wire).

![20160215_142104](https://cloud.githubusercontent.com/assets/16551561/13041263/b45790ee-d3f0-11e5-8259-0d6c6cbdbdae.jpg)
![Uploading 20160215_141456.jpg…]()

**Comment by simonemainardi** [comment]
it says `address already in use`. this means that there's another process listening on port 3000. Maybe there's another ntopng instance running? please look for running ntopng processes and kill them before doing a new bridge

**Comment by Cyndz136** [comment]
how will i kill the existing process? i tried the command sudo ufw deny 3000 but it still didn't work

**Comment by simonemainardi** [comment]
http://www.cyberciti.biz/faq/kill-process-in-linux-or-terminate-a-process-in-unix-or-linux-systems/

**Comment by Cyndz136** [comment]
thank You,
i'll try this.

**Comment by Cyndz136** [comment]
how come i can't kill the port.
i've tried the commands there on the link

**Comment by lucaderi** [comment]
Please do not bridge wifi with ethernet and be root
