### ISSUE TITLE
Enterprise L not recognized with online check

### ISSUE THREAD

**Issue by justinmaldonado** [ntop/ntopng#3930]
**License page says we have L**
<img width="1416" alt="Screen Shot 2020-05-12 at 1 44 21 PM" src="https://user-images.githubusercontent.com/38710743/81841128-f4ad3580-9517-11ea-8356-56f2ab64c58e.png">

**CLI says we have L**

Could not chdir to home directory /gpfs/commons/home/jmaldonado: No such file or directory
-bash-4.2$  sudo su -
Last login: Tue May 12 11:27:59 EDT 2020 on pts/1
[root@ntop ~]# ntopng --version
v.4.0.200505    [Enterprise/Professional build]
GIT rev:        4.0-stable:13dc2a7d30e7ff7ef28d0a09de4efa2e0a70ad40:20200505
Pro rev:        r2813
Built on:
System Id:      688F419276066B1F
Platform:       x86_64
Edition:        Enterprise L
License Type:   Permanent
Maintenance:    Until Fri May  7 11:28:19 2021 [358 days left]
License:        Z7h/WFhf97lvlbaORM6NnBGkzG+3tgrefqI/JPgpcP6CJRsBUwS67Xd9FcsqGrh0X6bn1
                vXwxWhPJthNjjCJipz3mg8gqiPaA3zTyTL6I/E562Xk6sXkSuXOHKsi+XRAsQvhAHuyT/
                0egorPikksrNjwGJFgZQ/H2NRvtJoECnYjkB8cz4Qevmetrs8el/cOpL5BQpPQBCtQXN9
                T3pyyo/IDlC2DNC7b4aNiG5TE66mD6bjon59FIbWajIJLTlH8/P6lNiUs2rGqsEjY7Ogt
                uwyGIvo6+QlS2sNsHzKjILeFbkmmRikaOZRMCCJc2+Qd9GyJ1zUJ9ayTbRUAtD+skg==
License Hash:   5FC4A40088009111134F3937211EAA1F1620401299391652FD
[root@ntop ~]# 

**License page says we have M**
<img width="1440" alt="Screen Shot 2020-05-13 at 12 48 30 PM" src="https://user-images.githubusercontent.com/38710743/81841194-127a9a80-9518-11ea-9fd2-0c318a872ec1.png">

**Comment by cardigliano** [comment]
@TheFunkyTechnician latest stable is working for me, reporting the correct edition, could you update please?

**Comment by justinmaldonado** [comment]
Still experiencing same issue. CLI reports it as Enterprise L, Gui reports it as Enterprise M

**Comment by cardigliano** [comment]
Are you using the same version I am using? Please note we just released a new update, please provide a screenshot again. Thank you.

<img width="938" alt="Screen_Shot_2020-05-15_at_16_18_50" src="https://user-images.githubusercontent.com/7548711/82060682-fcabd780-96c7-11ea-88f0-8f38c6e36e8e.png">

**Comment by justinmaldonado** [comment]
So strange. The license we see from CLI is

[root@ntop ~]# ntopng --version
v.4.0.200505    [Enterprise/Professional build]
GIT rev:        4.0-stable:13dc2a7d30e7ff7ef28d0a09de4efa2e0a70ad40:20200505
Pro rev:        r2813
Built on:
System Id:      XXXXXXXXXXX
Platform:       x86_64
Edition:        Enterprise L
License Type:   Permanent
Maintenance:    Until Fri May  7 11:28:19 2021 [357 days left]
License:        XXXXXXXXXXX /WFhf97lvlbaORM6NnBGkzG+3tgrefqI/JPgpcP6CJRsBUwS67Xd9FcsqGrh0X6bn1
                XXXXXXXXXXX /E562Xk6sXkSuXOHKsi+XRAsQvhAHuyT/
                0egorPikksrNjwGJFgZQ/H2NRvtJoECnYjkB8cz4Qevmetrs8el/cOpL5BQpPQBCtQXN9
                T3pyyo/ XXXXXXXXXXX /P6lNiUs2rGqsEjY7Ogt
                uwyGIvo6+QlS2sNsHzKjILeFbkmmRikaOZRMCCJc2+ XXXXXXXXXXX +skg==
License Hash:   XXXXXXXXXXX

And via GUI we see

[A screenshot of a social media post  Description automatically generated]

**Comment by justinmaldonado** [comment]
If I do an online check I see

[root@ntop ~]# ntopng --online-license-check
15/May/2020 10:45:59 [Ntop.cpp:2236] Setting local networks to 127.0.0.0/8
15/May/2020 10:45:59 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
15/May/2020 10:45:59 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
15/May/2020 10:45:59 [NtopPro.cpp:295] [LICENSE] Reading license from /etc/ntopng.license
15/May/2020 10:45:59 [NtopPro.cpp:188] Contacting licensing server. Please hold on...
15/May/2020 10:45:59 [NtopPro.cpp:188] Contacting licensing server. Please hold on...
15/May/2020 10:46:00 [NtopPro.cpp:425] [LICENSE] /etc/ntopng.license: found valid Enterprise M license
15/May/2020 10:46:02 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.7.6.0 interface eth0...
15/May/2020 10:46:02 [Ntop.cpp:2341] Registered interface PF_RING [id: 0]
15/May/2020 10:46:03 [PcapInterface.cpp:91] Reading packets from PF_RING [id: 1]
15/May/2020 10:46:03 [Ntop.cpp:2341] Registered interface PF_RING [id: 1]
15/May/2020 10:46:03 [main.cpp:316] PID stored in file /var/run/ntopng.pid
15/May/2020 10:46:03 [Geolocation.cpp:183] Loaded database GeoLite2-ASN.mmdb [/usr/share/ntopng/httpdocs/geoip/GeoLite2-ASN.mmdb][ip_version: 6]
15/May/2020 10:46:03 [Geolocation.cpp:183] Loaded database GeoLite2-City.mmdb [/usr/share/ntopng/httpdocs/geoip/GeoLite2-City.mmdb][ip_version: 6]
15/May/2020 10:46:03 [HTTPserver.cpp:1280] HTTP logs will be stored on /var/lib/ntopng/ntopng_access.log
15/May/2020 10:46:03 [HTTPserver.cpp:1334] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
15/May/2020 10:46:03 [HTTPserver.cpp:1337] HTTP server listening on 3000
15/May/2020 10:46:03 [Utils.cpp:739] User changed to ntopng
15/May/2020 10:46:03 [main.cpp:383] Logging onto /var/lib/ntopng/ntopng.log
15/May/2020 10:46:03 [main.cpp:386] Working directory: /var/lib/ntopng
15/May/2020 10:46:03 [main.cpp:388] Scripts/HTML pages directory: /usr/share/ntopng
15/May/2020 10:46:03 [Ntop.cpp:443] Welcome to ntopng x86_64 v.4.0.200505 - (C) 1998-20 ntop.org
15/May/2020 10:46:03 [NtopPro.cpp:692] [LICENSE] System Id:     688F419276066B1F
15/May/2020 10:46:03 [NtopPro.cpp:693] [LICENSE] Edition:       Enterprise M
15/May/2020 10:46:03 [NtopPro.cpp:694] [LICENSE] License Type:  Permanent License
15/May/2020 10:46:03 [NtopPro.cpp:703] [LICENSE] License:       Z7h/WFhf97lvlbaORM6NnBGkzG+3tgrefqI/JPgpcP6CJRsBUwS67Xd9FcsqGrh0X6bn1
15/May/2020 10:46:03 [NtopPro.cpp:704] [LICENSE]                vXwxWhPJthNjjCJipz3mg8gqiPaA3zTyTL6I/E562Xk6sXkSuXOHKsi+XRAsQvhAHuyT/
15/May/2020 10:46:03 [NtopPro.cpp:704] [LICENSE]                0egorPikksrNjwGJFgZQ/H2NRvtJoECnYjkB8cz4Qevmetrs8el/cOpL5BQpPQBCtQXN9
15/May/2020 10:46:03 [NtopPro.cpp:704] [LICENSE]                T3pyyo/IDlC2DNC7b4aNiG5TE66mD6bjon59FIbWajIJLTlH8/P6lNiUs2rGqsEjY7Ogt
15/May/2020 10:46:03 [NtopPro.cpp:704] [LICENSE]                uwyGIvo6+QlS2sNsHzKjILeFbkmmRikaOZRMCCJc2+Qd9GyJ1zUJ9ayTbRUAtD+skg==
15/May/2020 10:46:03 [NtopPro.cpp:708] [LICENSE] License Hash:  5FC4A40088009111134F3937211EAA1F1620401299391652FD
15/May/2020 10:46:03 [NtopPro.cpp:718] [LICENSE] Maintenance:   Until Fri May  7 11:28:19 2021 [357 days left]

**Comment by cardigliano** [comment]
@TheFunkyTechnician it seems this is related to the online check then, we will check it, in the meantime do not use it (it seems it is not required in this case)

**Comment by justinmaldonado** [comment]
Ok, so we have a similar issue with our nprobe license as well. It may be easier/faster to resolve all of this another way. Let me know if you are interested. I can set up a google meet if you want to see / share screens. We can probably resolve this in a few minutes.

**Comment by cardigliano** [comment]
@TheFunkyTechnician please drop an email to cardigliano at ntop org and we will schedule a call

**Comment by cardigliano** [comment]
Update: the online license check recognizes the L license as M

**Comment by cardigliano** [comment]
Fixed
