### ISSUE TITLE
News feed is out of sync with blog

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3931]
![Screen Shot 2020-05-13 at 19 08 48](https://user-images.githubusercontent.com/4493366/81844665-b3d11300-954f-11ea-84af-dcc03d52dec5.png)
![Screen Shot 2020-05-13 at 19 10 10](https://user-images.githubusercontent.com/4493366/81844669-b59ad680-954f-11ea-8e3d-78575b77ab53.png)

**Comment by gabryon99** [comment]
fixed in https://github.com/ntop/ntopng/commit/857629ccf098f40f7b03242229973ea1b8d0eb07
