### ISSUE TITLE
Disable Device Applications Alerts

### ISSUE THREAD

**Issue by RichieB2B** [ntop/ntopng#3933]
Running ntopng 4.0.200513-10203 when editing the Device Applications there is a note at the bottom:

> In this page it is possible to configure the list of acceptable applications per device type and direction (device as client or server with respect to the application). By enabling Device Applications Alerts in the Alerts configuration page under Preferences, alerts are generated when an anomalous application is detected.

The [documentation](https://www.ntop.org/guides/ntopng/advanced_features/device_protocols.html) also mentions this. However, Settings -> Preferences -> Alerts does not have a Device Applications Alerts switch.

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/1461970/81926206-ea576e00-95e1-11ea-9542-c9c241fe380e.png">

How can I disable Device Applications Alerts?

**Comment by simonemainardi** [comment]
Thanks for reporting this. Go to Settings->User Scripts->Flow User Scripts and disable "Device Application Not Allowed"

![image](https://user-images.githubusercontent.com/3397663/81938391-21834a80-95f5-11ea-8143-1da63be796d1.png)

Refreshing the docs accordingly

**Comment by RichieB2B** [comment]
Thanks. I found it at a sightly deeper location:

Settings -> User Scripts -> Flows -> Default -> Edit -> Device Application Not Allowed
