### ISSUE TITLE
New domain

### ISSUE THREAD

**Issue by CyberbreinAirw0lf** [ntop/ntopng#3935]
Team,

I had to change the domain-part of the hostname.
Meaning the ntopng system indicated by npm-2.local.net is replaced with npm-2.itv.lan.
The same applies for all hosts monitored with SNMP.

What changes do I need to make within ntopng?

Thanks - Will

**Comment by simonemainardi** [comment]
For the devices monitored with SNMP you have to delete and re-add them. Other things (such as host names) will adjust automatically. You can also clear certain hosts data by visiting the host page and clicking 'reset host data'.

**Comment by CyberbreinAirw0lf** [comment]
I did delete en re-add them. However, it looks as if under the hood, the old names are still used.
This is because a packet capture shows DNS requests coming from ntopng towards the old system/domain name for at least 2 SNMP devices.

The option 'reset host data' is something that is only available on the flow data and on a per hosts basis? Is there a way to reset the host data for all hosts in one go?

**Comment by simonemainardi** [comment]
> ntopng towards the old system/domain name for at least 2 SNMP devices.

Could be requests in progress at the time of the change. They will stop as soon as completed. In case, you can also restart ntopng.

> The option 'reset host data' is something that is only available on the flow data and on a per hosts basis? Is there a way to reset the host data for all hosts in one go?

stop ntopng
run redis-cli flushall
restart ntopng
