### ISSUE TITLE
Script LuaEngine.cpp Warning unexpected Symbol near

### ISSUE THREAD

**Issue by djmax9999** [ntop/ntopng#3936]
I am using the following ntopng Version anf getting lots of messages in syslog.

root@raspberrypi:/var/log# ntopng --version
v.4.1.200511    [Enterprise/Professional/Embedded build]
GIT rev:        dev:812afd9862bff34643c24981a6110b91b94701e4:20200511
Pro rev:        r2868
Built on:       Raspbian GNU/Linux 10 (buster)
System Id:      FD496849499602D2
Platform:       armv7l
Edition:        Enterprise Embedded
License Type:   Time-Limited [Empty license file]
Validity:       Until Fri May 15 07:03:47 2020

May 15 06:42:38 raspberrypi ntopng: [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:38 raspberrypi ntopng[465]: 15/May/2020 06:42:38 [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:39 raspberrypi ntopng: [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:39 raspberrypi ntopng[465]: 15/May/2020 06:42:39 [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:39 raspberrypi ntopng: [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/var/lib/ntopng/plugins0/alert_endpoints/nagios.lua:1: unexpected symbol near '<\135>']
May 15 06:42:39 raspberrypi ntopng[465]: 15/May/2020 06:42:39 [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/var/lib/ntopng/plugins0/alert_endpoints/nagios.lua:1: unexpected symbol near '<\135>']
May 15 06:42:40 raspberrypi ntopng: [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:40 raspberrypi ntopng[465]: 15/May/2020 06:42:40 [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:41 raspberrypi ntopng: [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:41 raspberrypi ntopng[465]: 15/May/2020 06:42:41 [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:42 raspberrypi ntopng: [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:42 raspberrypi ntopng[465]: 15/May/2020 06:42:42 [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:42 raspberrypi ntopng: [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/var/lib/ntopng/plugins0/alert_endpoints/nagios.lua:1: unexpected symbol near '<\135>']
May 15 06:42:42 raspberrypi ntopng[465]: 15/May/2020 06:42:42 [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/var/lib/ntopng/plugins0/alert_endpoints/nagios.lua:1: unexpected symbol near '<\135>']
May 15 06:42:43 raspberrypi ntopng: [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:43 raspberrypi ntopng[465]: 15/May/2020 06:42:43 [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:44 raspberrypi ntopng: [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:44 raspberrypi ntopng[465]: 15/May/2020 06:42:44 [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:45 raspberrypi ntopng: [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:45 raspberrypi ntopng[465]: 15/May/2020 06:42:45 [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:45 raspberrypi ntopng: [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/var/lib/ntopng/plugins0/alert_endpoints/nagios.lua:1: unexpected symbol near '<\135>']
May 15 06:42:45 raspberrypi ntopng[465]: 15/May/2020 06:42:45 [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/var/lib/ntopng/plugins0/alert_endpoints/nagios.lua:1: unexpected symbol near '<\135>']
May 15 06:42:46 raspberrypi ntopng: [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:46 raspberrypi ntopng[465]: 15/May/2020 06:42:46 [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:47 raspberrypi ntopng: [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:47 raspberrypi ntopng[465]: 15/May/2020 06:42:47 [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:48 raspberrypi ntopng: [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:48 raspberrypi ntopng[465]: 15/May/2020 06:42:48 [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:48 raspberrypi ntopng: [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/var/lib/ntopng/plugins0/alert_endpoints/nagios.lua:1: unexpected symbol near '<\135>']
May 15 06:42:48 raspberrypi ntopng[465]: 15/May/2020 06:42:48 [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][/var/lib/ntopng/plugins0/alert_endpoints/nagios.lua:1: unexpected symbol near '<\135>']
May 15 06:42:49 raspberrypi ntopng: [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:49 raspberrypi ntopng[465]: 15/May/2020 06:42:49 [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:50 raspberrypi ntopng: [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']
May 15 06:42:50 raspberrypi ntopng[465]: 15/May/2020 06:42:50 [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][/var/lib/ntopng/plugins0/ts_schemas/score/min.lua:1: unexpected symbol near '<\135>']

There were several issues about this topic, but it seems to be back again...

**Comment by simonemainardi** [comment]
As you're using the community edition, add option --community and report.

**Comment by djmax9999** [comment]
I am starting ntopng via systemctl, how can I add the option with systemctl ?

**Comment by djmax9999** [comment]
Just tried to startt ntopng manually in community mode:

root@raspberrypi:/# ntopng --community
15/May/2020 10:46:03 [Ntop.cpp:2255] Setting local networks to 127.0.0.0/8
15/May/2020 10:46:03 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
15/May/2020 10:46:03 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
15/May/2020 10:46:07 [PcapInterface.cpp:91] Reading packets from eth0 [id: 1]
15/May/2020 10:46:07 [Ntop.cpp:2360] Registered interface eth0 [id: 1]
15/May/2020 10:46:08 [PcapInterface.cpp:91] Reading packets from lo [id: 2]
15/May/2020 10:46:08 [Ntop.cpp:2360] Registered interface lo [id: 2]
15/May/2020 10:46:08 [main.cpp:316] PID stored in file /var/run/ntopng.pid
15/May/2020 10:46:08 [Geolocation.cpp:183] Loaded database GeoLite2-ASN.mmdb [/var/lib/GeoIP/GeoLite2-ASN.mmdb][ip_version: 6]
15/May/2020 10:46:08 [Geolocation.cpp:183] Loaded database GeoLite2-ASN.mmdb [/usr/share/GeoIP/GeoLite2-ASN.mmdb][ip_version: 6]
15/May/2020 10:46:08 [Geolocation.cpp:183] Loaded database GeoLite2-City.mmdb [/usr/share/GeoIP/GeoLite2-City.mmdb][ip_version: 6]
15/May/2020 10:46:09 [HTTPserver.cpp:1480] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
15/May/2020 10:46:09 [HTTPserver.cpp:1483] HTTP server listening on 3000
15/May/2020 10:46:09 [Utils.cpp:761] User changed to ntopng
15/May/2020 10:46:09 [main.cpp:386] Working directory: /var/lib/ntopng
15/May/2020 10:46:09 [main.cpp:388] Scripts/HTML pages directory: /usr/share/ntopng
15/May/2020 10:46:09 [Ntop.cpp:456] Welcome to ntopng armv7l v.4.1.200511 - (C) 1998-20 ntop.org
15/May/2020 10:46:09 [Ntop.cpp:466] Built on Raspbian GNU/Linux 10 (buster)
15/May/2020 10:46:09 [Ntop.cpp:857] Adding 127.0.0.1/32 as IPv4 interface address for lo
15/May/2020 10:46:09 [Ntop.cpp:866] Adding 127.0.0.0/8 as IPv4 local network for lo
15/May/2020 10:46:09 [Ntop.cpp:857] Adding 192.168.178.26/32 as IPv4 interface address for eth0
15/May/2020 10:46:09 [Ntop.cpp:866] Adding 192.168.178.0/24 as IPv4 local network for eth0
15/May/2020 10:46:09 [Ntop.cpp:888] Adding ::1/128 as IPv6 interface address for lo
15/May/2020 10:46:09 [Ntop.cpp:898] Adding ::1/128 as IPv6 local network for lo
15/May/2020 10:46:09 [Ntop.cpp:888] Adding fe80::6315:5c50:4796:b4db/128 as IPv6 interface address for eth0
15/May/2020 10:46:09 [Ntop.cpp:898] Adding fe80::6315:5c50:4796:b4db/64 as IPv6 local network for eth0
15/May/2020 10:46:09 [PeriodicActivities.cpp:105] Started periodic activities loop...
15/May/2020 10:46:14 [PeriodicActivities.cpp:165] Each periodic activity script will use 3 threads
15/May/2020 10:46:14 [NetworkInterface.cpp:2347] Started packet polling on interface eth0 [id: 1]...
15/May/2020 10:46:14 [NetworkInterface.cpp:2347] Started packet polling on interface lo [id: 2]...
15/May/2020 10:47:29 [LuaEngine.cpp:361] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.lua][cannot read /var/lib/ntopng/plugins0/alert_endpoints/email.lua: Input/output error]
15/May/2020 10:47:29 [stats_update.lua:22] [rrd.lua:435] ERROR: rrd_update_r() [/var/lib/ntopng/-1/rrd/system/cpu_ld.rrd][1589532449:1.760000] failed [opening '/var/lib/ntopng/-1/rrd/system/cpu_ld.rrd': Read-only file system]
15/May/2020 10:47:29 [second.lua:26] [rrd.lua:435] ERROR: rrd_update_r() [/var/lib/ntopng/2/rrd/traffic_rxtx.rrd][1589532442:422369:422369] failed [opening '/var/lib/ntopng/2/rrd/traffic_rxtx.rrd': Read-only file system]
 
System crashed!!! Not reachable anymore....

**Comment by simonemainardi** [comment]
Put the option inside the ntopng configuration file, then control the start/stop of ntopng as usual using systemd or initd.

It says "/var/lib/ntopng/2/rrd/traffic_rxtx.rrd': Read-only file system" so you have permission errors

**Comment by simonemainardi** [comment]
@djmax9999 did you try the suggestion given?

**Comment by djmax9999** [comment]
I have reinstalled ntopng completly and added --community to ntopng.conf. Currently there are no messages in syslog anymore. Thanks for you help...

**Comment by simonemainardi** [comment]
can you please try, remove --community, restart ntopng and see if it happens again (wait at least 10 minutes of execution)?

**Comment by djmax9999** [comment]
just removed --community and restarted ntopng. It´s running for 20 Minutes now... Stopped ntopng and startet the program manually.

No messages so far.....

So the main reason might be a corrupted SD Card which I changed also...
Thnx Simon... I appreciate your help.....

**Comment by simonemainardi** [comment]
Thanks for reporting and giving feedback. Much appreciated.
