### ISSUE TITLE
extract pcap file empty

### ISSUE THREAD

**Issue by Guymtrx** [ntop/ntopng#3939]
Hi when I tried to extract old trafic pcap file , the file downloaded empty

**Comment by emanuele-f** [comment]
Please report the output of `ntopng --version` and some screenshots

**Comment by Guymtrx** [comment]
v.4.1.200423    [Enterprise/Professional build]
GIT rev:        dev:df954828294de806cadb8c24f9014ad0e6ddc15b:20200423
Pro rev:        r2849
Built on:       Ubuntu 18.04.4 LTS
System Id:      93B243D87A08AA83
Platform:       x86_64
Edition:        Enterprise M
License Type:   Permanent
Maintenance:    Until Wed Dec  2 20:28:36 2020 [198 days left]
License:
here there is the license

**Comment by simonemainardi** [comment]
Please, attach screenshots and configuration. Are you using ntopng in combination with n2disk?

**Comment by Guymtrx** [comment]
Yes we use n2disk,
what configuration do you need? I will send you. it's worked fine in the
past.
tnx
Guy

**Comment by cardigliano** [comment]
@Guymtrx could you provide a screenshot of the information reported in under Interface -> Recording -> Status?

**Comment by Guymtrx** [comment]
[image: image.png]

**Comment by cardigliano** [comment]
Sorry I cannot see the picture

**Comment by Guymtrx** [comment]
and now?

tnx
Guy

**Comment by cardigliano** [comment]
Still no picture..

**Comment by Guymtrx** [comment]
I sent you in telegram

**Comment by Guymtrx** [comment]
Hi luca,
We need to fix it today.
I talk with alfredo here and in telegram

Please let us know how to fix the pcap issues

tnx
Guy

**Comment by Guymtrx** [comment]
Hi Luca

We have a very important customer who started to work with the system and
he is not able to download pcaps which is the whole point of this system
for him.
Please put it as a very high priority issue

Thank you,
Pavel Rogovoy
COO at monogoto

**Comment by cardigliano** [comment]
Traffic in this case contained several nested encapsulation layers, unsupported by the index.
