### ISSUE TITLE
No data on dashboard and hosts section after update 

### ISSUE THREAD

**Issue by danilaryz** [ntop/ntopng#3941]
Hi, after update ntopng from 3.8 to newest one we have some critical errors: no Top Talkers on dashboard, no data in Hosts section, script 5min.lua constantly performed and a lot of drops on nprobe interface(nFlow/sFlow), in log a lot of error like this ntop ntopng: [Error][Flow Misbehaviour][Flow][flow] Long-Lived Flow 
Ubuntu 18.0.4.3 LTS, influxdb, ntopng v.4.1.200428

**Comment by simonemainardi** [comment]
could be due to

```
18/May/2020 10:55:13 [LuaEngine.cpp:868] WARNING: Script failure [/Users/simone/code/ntopng/scripts/lua/rest/get/interface/data.lua][...mone/code/ntopng/scripts/lua/rest/get/interface/data.lua:55: attempt to concatenate a nil value (local 'ifid')]
18/May/2020 10:55:18 [LuaEngine.cpp:868] WARNING: Script failure [/Users/simone/code/ntopng/scripts/lua/rest/get/interface/data.lua][...mone/code/ntopng/scripts/lua/rest/get/interface/data.lua:55: attempt to concatenate a nil value (local 'ifid')]
18/May/2020 10:55:23 [LuaEngine.cpp:868] WARNING: Script failure [/Users/simone/code/ntopng/scripts/lua/rest/get/interface/data.lua][...mone/code/ntopng/scripts/lua/rest/get/interface/data.lua:55: attempt to concatenate a nil value (local 'ifid')]
18/May/2020 10:55:28 [LuaEngine.cpp:868] WARNING: Script failure [/Users/simone/code/ntopng/scripts/lua/rest/get/interface/data.lua][...mone/code/ntopng/scripts/lua/rest/get/interface/data.lua:55: attempt to concatenate a nil value (local 'ifid')]
18/May/2020 10:55:33 [LuaEngine.cpp:868] WARNING: Script failure [/Users/simone/code/ntopng/scripts/lua/rest/get/interface/data.lua][...mone/code/ntopng/scripts/lua/rest/get/interface/data.lua:55: attempt to concatenate a nil value (local 'ifid')]
```

in progress. please check the logs.

**Comment by simonemainardi** [comment]
please, update ntopng to the lstest version. Then check again and possibly report:

- udpated ntopng version
- nprobe version (if used)
- ntopng logs
- screenshots of the missing data
- screenshot of the interface stats home page

**Comment by danilaryz** [comment]
Hi, i updated ntopng
1. nTop v.4.1.200519
2. nProbe v.9.1.200427 
3. you need log from restart of ntopng ?
4.

![изображение](https://user-images.githubusercontent.com/19521231/82335119-8f62b400-99f1-11ea-9621-7b262e9db815.png)
![изображение](https://user-images.githubusercontent.com/19521231/82336632-81ae2e00-99f3-11ea-8f5b-54025cef4637.png)

![изображение](https://user-images.githubusercontent.com/19521231/82335900-9a6a1400-99f2-11ea-9508-626d789081a8.png)
![изображение](https://user-images.githubusercontent.com/19521231/82335953-a5bd3f80-99f2-11ea-9f1e-0c9422eed23f.png)
![изображение](https://user-images.githubusercontent.com/19521231/82336074-ce453980-99f2-11ea-9217-4ab365ff96f4.png)

But flow information exist 

![tempsnip](https://user-images.githubusercontent.com/19521231/82337094-0d27bf00-99f4-11ea-90a1-8254bf73b063.png)


5. 

![Inked82335382-e8cae300-99f1-11ea-941a-abde53350d5e_LI](https://user-images.githubusercontent.com/19521231/82337843-e1590900-99f4-11ea-8ad9-9614d8254c55.jpg)

**Comment by simonemainardi** [comment]
Thanks for attaching screenshots. What I can tell by looking at the header is that you have flows but don't have hosts. So my guess is that you have ticked option 'flows-only interface' from the interface preferences page (wheel). Make sure this is turned off:

![image](https://user-images.githubusercontent.com/3397663/82370037-30646580-9a18-11ea-9cbe-5f85e0f24bb6.png)

Please report.

**Comment by danilaryz** [comment]
Yes, this switch was turned on, I turned it off and the hosts appeared, Thank you! 
I suggest adding information about this interface behavior after updating to the FAQ section of instruction?
And the yellow triangle with message about 5min.lua script still appears frequently.

**Comment by simonemainardi** [comment]
> Yes, this switch was turned on, I turned it off and the hosts appeared, Thank you!

Thanks for reporting, I'm glad the issue is solved.

> I suggest adding information about this interface behavior after updating to the FAQ section of instruction?
And the yellow triangle with message about 5min.lua script still appears frequently.

If you click in the yellow triangle, you will be brought to a page which you can use to understand why the 5min is slow. Hover the mouse on the 5min yellow triangle and it will tell you. Very likely, you've too many local hosts and the timeseries writes are taking too long to complete. You may want to consider switching to InfluxDB.
