### ISSUE TITLE
ndpi-protocols file not fully loaded

### ISSUE THREAD

**Issue by Tamahome-M** [ntop/ntopng#3942]
When downloading the attached list, for example, sberbank.ru and some others are missing.
What am I doing wrong?
ntopng Community Edition v.4.0.200518
Num Applications 262,but there should be more
[proto.txt](https://github.com/ntop/ntopng/files/4644396/proto.txt)

**Comment by lucaderi** [comment]
The max number of protocols supported by nDPI is 512. The difference between the max number and the current (without -p) protocol number is 262. I don't see the point of your custom protocol file: in essence you want to define a custom protocol per web-site to create nDPI graphs for each defined domain? If this is what you want, the problem you want to fix is good, but not this way. A better solution is required.

Closing this ticket as everything works as expected.
