### ISSUE TITLE
Implement /lua/rest/v1/get/alert/ts.lua

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3943]
This endpoint will take as input
- begin_time: UTC epoch [mandatory]
- end_time: UTC epoch [mandatory]
- alert_type: alert type. If missing all alerts will match [optional]
- alert_severity: alert severity If missing all alerts will match [optional]

The output will return a daily timeseries (the day key will be an epoch containing an array of 24 numbers, one per hour) with number of alert matching the query.

**Comment by cardigliano** [comment]
Implemented
