### ISSUE TITLE
Implement getter for active flow protocol counts

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3947]
It is requested to implement an API getter for active flow counts, e.g., `/lua/rest/get/flow/protocol_counts.lua` which returns the number of active flows for each available L4 protocol. In other words, the information which currently populates the flows dropdown must be exposed via this API:

![image](https://user-images.githubusercontent.com/3397663/82243407-d7290300-993f-11ea-8041-ec5dfd323f33.png)

**Comment by cardigliano** [comment]
Implemented
