### ISSUE TITLE
Implement getter for alert type counts

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3948]
It is requested to implement an API getter for alert counts, e.g., `/lua/rest/get/alert/type_counts.lua` which returns the number of alerts per type. In other words, the information which currently populates the alerts dropdown must be exposed via this API:

![image](https://user-images.githubusercontent.com/3397663/82243723-5e767680-9940-11ea-9010-d3fd08d2b8c9.png)

Endpoint must take as input at least

- the type of alert: engaged / stored / flow [mandatory]
- begin_time: UTC epoch [optional]
- end_time: UTC epoch [optional]

**Comment by cardigliano** [comment]
Implemented
