### ISSUE TITLE
Implement getter for alert severity counts

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3949]
It is requested to implement an API getter for alert severity counts, e.g., `/lua/rest/get/alert/severity_counts.lua` which returns the number of alerts per severity. In other words, the information which currently populates the alerts dropdown must be exposed via this API:

![image](https://user-images.githubusercontent.com/3397663/82244030-dd6baf00-9940-11ea-99bb-046a2da8cd4f.png)

Endpoint must take as input at least

- the type of alert: engaged / stored / flow [mandatory]
- begin_time: UTC epoch [optional]
- end_time: UTC epoch [optional]

**Comment by cardigliano** [comment]
Implemented
