### ISSUE TITLE
Implement endpoint for /lua/iface_ndpi_stats.lua

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3953]
It is requested to implement an API endpoint, e.g., `get/interface/application_stats.lua`, for the information which is currently returned in `iface_ndpi_stats.lua`. Once the endpoint is implemented, the old `/lua/iface_ndpi_stats.lua` needs to be removed and replaced with the API call.

**Comment by cardigliano** [comment]
Implemented (and iface_ndpi_stats.lua migrated)
