### ISSUE TITLE
Some references in ntop-4.0 GUI doesn't use 'http-prefix' setting

### ISSUE THREAD

**Issue by andpp** [ntop/ntopng#3957]
Some references in ntopng-4.0 GUI doesn't use 'http-prefix' setting.

I am using ntopng behind nginx proxy with  **http-prefix='/ntopng'** set in configuration file. While most of the links in GUI work fine, sometimes I see links without http-prefix so I get error 404.
For example home link in the left upper corner of the page is **'/'** instead of **/ntopng/** so instead of home of ntopng I get to home of my server. Also drop-down menu for changing interface on dashboard refers to **/lua/directories.lua?ifid=0** instead of **/ntopng/lua/directories.lua?ifid=0** so I get error 404

**Comment by lucaderi** [comment]
I have made some fixes in 4.1 (dev) but have been unable to find the reference to directories.lua. Can you please be kind enough to update to the latest 4.1 (wait ~1h as packages are being built) and point me to the exact pages with defects? Thanks

**Comment by simonemainardi** [comment]
@andpp after the fixes the behavior seems OK. Also the only reference to directories.lua which I can find has the right link. Please, explain.

**Comment by simonemainardi** [comment]
both entries broken when using http-prefix:

![image](https://user-images.githubusercontent.com/3397663/82335461-a3a2b300-99e9-11ea-8e63-b448d18c97a7.png)

**Comment by andpp** [comment]
I compiled and installed from branch **4.0-stable**. 

For example  **scripts/lua/modules/page_utils.lua** creates direct link to / instead of http-prefix/
 ```
  print('<div id="n-sidebar" class="bg-'.. navbar_style ..' py-0 px-2">')

   print([[
        <h3 class='muted'>
               <a href='/'>
        ]])
```

Will it work if I just copy whole lua folder from **dev** branch to my **/usr/local/share/ntopng/scripts/lua** folder? Or it could create some other issues because of new features of **dev** branch not supported in **4.0-stable** branch?

**Comment by simonemainardi** [comment]
fixes backported to stable. @andpp you don't have to change any file. Just wait a couple of hours (builds are in progress), then update your 4.0 stable and it will be OK.

**Comment by andpp** [comment]
![ntop-bug](https://user-images.githubusercontent.com/12842195/82595722-f18af880-9b5a-11ea-8913-8d998f74fdd5.jpg)

Selecting eth0 of eth1 from these menu still redirects to /?ifid=0 or /?ifid=0 instead of http-prefix/?ifid=1
