### ISSUE TITLE
Remove InfluxDB export freqs at 10s/30s

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3958]
It is requested to remove the export frequencies in the subject and make the export behavior uniform between RRD and InfluxDB:

- Remove classes `TimeseriesRing`, `TimeseriesRingStatus`, `TimeseriesStats`, `TimeseriesPoint` etc
- Remove method `tsLua` from the `Host` and the `Interface`. Remove the `ts_lua` parameter from the `getHost` and `getInterfaceStats` calls
- `Host` will only have `HostStats` for the statistics
- This change must be non-breaking. That is, InfluxDB already configured with data must continue to function and give access to old data (even if at a higher granularity)

**Comment by emanuele-f** [comment]
Implemented in 340462ad73a0a5bde92ddbd216c212c53b497dd9 and in ec51278c2050b0ddb4a685fdb972ee2ef319af3e

**Comment by simonemainardi** [comment]
this is what happen when the resolution is changed from 5 minutes to 1 minute from the preferences (data was written @5min)

![image](https://user-images.githubusercontent.com/3397663/82573143-b2be6800-9b85-11ea-92ed-f647ee2a8580.png)

after the change

![image](https://user-images.githubusercontent.com/3397663/82573205-c538a180-9b85-11ea-9964-bc2612ab03e8.png)

**Comment by simonemainardi** [comment]
please, add a NOTE close to the toggle in the preferences which says that lowering the resolution can cause inconsistencies and suggest a possible solution to flush old data.
