### ISSUE TITLE
licencing issue (ntop user interface)

### ISSUE THREAD

**Issue by svenvogel** [ntop/ntopng#396]
when i add a licence for ntopng they will not be applied. 

[root@cloud-ntop etc]# ntopng --check-license
## Demo mode license

[root@cloud-ntop etc]# cat /etc/ntopng.license
3D9707F99E62F7001EC662DD819FAF07145725574191922F92

is there any fix for that problem? CentOS 7

thanks

Sven

**Comment by lucaderi** [comment]
Is the clock set properly on your system? Please provide a complete startup log using the latest development package.

**Comment by svenvogel** [comment]
Hi Luca,

yes clock is set correctly. i update to the following version.
nbox 2.3.0 build 472
[root@cloud-ntop ~]# ntopng --check-license
Demo mode license
[root@cloud-~]# ntopng --version
v.2.3.160215 [Professional Edition]
GIT rev:   dev:9e5c843abefb0fd57f7b9f72357a93f7f123b646:20160215
Pro rev:   r569
System Id: 689B577B76056B01
Built on:  CentOS Linux release 7.1.1503 (Core)

when i login in nbox i can start it now. but when i look to configuration i get no license.

![nolic](https://cloud.githubusercontent.com/assets/5433844/13063114/0f78a310-d445-11e5-9262-7af2ea402ca3.PNG)

i make a complete startup from ntopng

[root@cloud-ntop ~]# ntopng /etc/ntopng/ntopng.conf
16/Feb/2016 00:36:31 [Ntop.cpp:975] Setting local networks to 127.0.0.0/8
16/Feb/2016 00:36:31 [Redis.cpp:106] Successfully connected to redis 127.0.0.1:6379@0
16/Feb/2016 00:36:31 [NtopPro.cpp:119] [LICENSE] Reading license from /etc/ntopng.license
16/Feb/2016 00:36:31 [NtopPro.cpp:153] WARNING: [LICENSE] Your license will expire on Sun Mar  6 10:15:41 2016
16/Feb/2016 00:36:31 [CollectorInterface.cpp:173] ERROR: No filter can be set on a collector interface. Ignored not (net 192.168.173.0/24)
16/Feb/2016 00:36:31 [Ntop.cpp:1194] Registered interface tcp://127.0.0.1:5556 [id: 2]
16/Feb/2016 00:36:31 [Ntop.cpp:1207] Registered interface view tcp://127.0.0.1:5556 [id: 2]
16/Feb/2016 00:36:31 [Utils.cpp:305] User changed to nobody
16/Feb/2016 00:36:31 [main.cpp:252] PID stored in file /var/tmp/ntopng.pid
16/Feb/2016 00:36:31 [HTTPserver.cpp:460] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
16/Feb/2016 00:36:31 [HTTPserver.cpp:503] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
16/Feb/2016 00:36:31 [HTTPserver.cpp:506] HTTP server listening on port 3000
16/Feb/2016 00:36:31 [main.cpp:289] Working directory: /storage/ntopng
16/Feb/2016 00:36:31 [main.cpp:291] Scripts/HTML pages directory: /usr/share/ntopng
16/Feb/2016 00:36:31 [Ntop.cpp:258] Welcome to ntopng x86_64 v.2.3.160215 - (C) 1998-16 ntop.org
16/Feb/2016 00:36:31 [Ntop.cpp:263] Built on CentOS Linux release 7.1.1503 (Core)
16/Feb/2016 00:36:31 [PeriodicActivities.cpp:53] Started periodic activities loop...
16/Feb/2016 00:36:31 [RuntimePrefs.cpp:34] Dumping alerts into syslog
16/Feb/2016 00:36:31 [NtopPro.cpp:233] [LICENSE] ntopng systemId: 689B577B76056B01
16/Feb/2016 00:36:31 [NtopPro.cpp:238] [LICENSE] ntopng is starting in demo mode
16/Feb/2016 00:36:31 [NetworkInterface.cpp:1417] Started packet polling on interface tcp://127.0.0.1:5556 [id: 2]...
16/Feb/2016 00:36:31 [CollectorInterface.cpp:94] Collecting flows on tcp://127.0.0.1:5556

**Comment by ValentinaViscarelli** [comment]
Sven,
At the moment ignore it. Your license is good and this is a problem of the GUI, In fact when you run ntopng you get:

.....
WARNING: [LICENSE] Your license will expire on Sun Mar 6 10:15:41 2016
.....

We will fix the GUI asap

**Comment by svenvogel** [comment]
okay.
