### ISSUE TITLE
Implement reset logic in modal-utils.js

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3962]
The logic is currently missing (under the TODO comment). This needs to be implemented.

**Comment by gabryon99** [comment]
I have implemente reset logic for the `modalHandler`. See the Widget page for reference: https://github.com/ntop/ntopng/commit/7a532c75aa63c4f604d3012ea649fb0f938a7107

**Comment by simonemainardi** [comment]
there's a conflict with the are-you-sure.

Clicking on 'Reset Default' undoes all changes but then are you sure complains about changed data.

Moreover, 'Reset Default' behavior in 

![image](https://user-images.githubusercontent.com/3397663/85267225-45983e00-b475-11ea-8987-3948b3a2ec94.png)


Should 'reset' the fields to the ntopng default, and not undo the changes. To undo the changes, it suffices to click cancel.

**Comment by lucaderi** [comment]
I have tested the code. The are you sure problem is now solved. The Reset will be discussed in #4297
