### ISSUE TITLE
influxdb version detection broken behind HAProxy

### ISSUE THREAD

**Issue by aurrak** [ntop/ntopng#3964]
When running influxDB behind HAProxy, It automatically transforms every header from the upstream servers into lowercase (for following the HTTP/2 standard). See: https://discourse.haproxy.org/t/haproxy-2-0-0-header/3930/4

```
$ curl -sL -I https://influxdb.examplecom/ping
HTTP/1.1 204 No Content
content-type: application/json
request-id: e5035fb5-9a64-11ea-b55a-0242ac190002
x-influxdb-build: OSS
x-influxdb-version: 1.7.10
x-request-id: e5035fc4-aa94-11ea-b55a-0242ac190002
date: Wed, 20 May 2020 06:41:11 GMT
```

This breaks the influxDB version detection code (returns incompatible version error) in `scripts/lua/modules/timeseries/drivers/influxdb.lua` as it's using a case-sensitive string matching on the "X-Influxdb-Version" header.

```
  local content = res.CONTENT or ""
  return string.match(content, "\nX%-Influxdb%-Version: ([%d|%.]+)")
```

Any chance on changing it to a case-insensitive match?

**Comment by simonemainardi** [comment]
Fixed. Change applied both to sable and dev versions. New builds are in progress. Please hold on a couple of hours, update, and it will be OK.
