### ISSUE TITLE
can't access to the ntop web(localhost:3000) on macOS

### ISSUE THREAD

**Issue by khoshtip2** [ntop/ntopng#3966]
we test with:

http://ip:3000
http://localhost:3000
http://127.0.0.1:3000

**Comment by simonemainardi** [comment]
is ntopng running? please check and report the logs

**Comment by khoshtip2** [comment]
Hi Simone,
yes looks so: /Library/LaunchDaemons/org.ntop.ntopng.plist: service already loaded.
I install the last version: ntopng-4.1.200506 today.
Best Regards

**Comment by simonemainardi** [comment]
do

```
ps aux | grep ntopng
```

see if it is running. the report the logs

**Comment by khoshtip2** [comment]
result:


rep ntopng
root            19268   0,0  0,0  4276968    828 s000  S+    4:18pm   0:00.00 grep ntopng

**Comment by simonemainardi** [comment]
ntopng is not running. stop it and restart it. If you don't check and report the logs as requested, it won't be easy to understand though.

**Comment by khoshtip2** [comment]
Ok, but where ist The log folder???

**Comment by lucaderi** [comment]
Can you please open terminal and type
/usr/local/bin/ntopng /usr/local/etc/ntopng/ntopng.conf

Then when you see the error, send here the log you see on the terminal screen?

**Comment by khoshtip2** [comment]
Hi Luca:


my Terminal log:




Last login: Wed May 20 16:08:52 on ttys000
gbd:~ root# sudo launchctl unload /Library/LaunchDaemons/org.ntop.ntopng.plist
gbd:~ root# 
  [20.05.2020, 17:44:41 Wiederhergestellt]
Last login: Wed May 20 17:44:01 on console
Restored session: Mi 20 Mai 2020 17:35:39 CEST
gbd:~ root# /usr/local/etc/ntopng/ntopng.conf 
-sh: /usr/local/etc/ntopng/ntopng.conf: Permission denied
gbd:~ root# /usr/local/bin/ntopng /usr/local/etc/ntopng/ntopng.conf
20/May/2020 21:56:12 [Ntop.cpp:2255] Setting local networks to 127.0.0.0/8
20/May/2020 21:56:12 [Redis.cpp:99] ERROR: Connection error [Connection refused]
20/May/2020 21:56:13 [Redis.cpp:83] Redis has disconnected, reconnecting [remaining attempts: 14]
20/May/2020 21:56:13 [Redis.cpp:99] ERROR: Connection error [Connection refused]
20/May/2020 21:56:14 [Redis.cpp:83] Redis has disconnected, reconnecting [remaining attempts: 13]
20/May/2020 21:56:14 [Redis.cpp:99] ERROR: Connection error [Connection refused]
20/May/2020 21:56:15 [Redis.cpp:83] Redis has disconnected, reconnecting [remaining attempts: 12]
20/May/2020 21:56:15 [Redis.cpp:99] ERROR: Connection error [Connection refused]
20/May/2020 21:56:16 [Redis.cpp:83] Redis has disconnected, reconnecting [remaining attempts: 11]
20/May/2020 21:56:16 [Redis.cpp:99] ERROR: Connection error [Connection refused]
20/May/2020 21:56:17 [Redis.cpp:83] Redis has disconnected, reconnecting [remaining attempts: 10]
20/May/2020 21:56:17 [Redis.cpp:99] ERROR: Connection error [Connection refused]
20/May/2020 21:56:18 [Redis.cpp:83] Redis has disconnected, reconnecting [remaining attempts: 9]
20/May/2020 21:56:18 [Redis.cpp:99] ERROR: Connection error [Connection refused]
20/May/2020 21:56:19 [Redis.cpp:83] Redis has disconnected, reconnecting [remaining attempts: 8]
20/May/2020 21:56:19 [Redis.cpp:99] ERROR: Connection error [Connection refused]
20/May/2020 21:56:20 [Redis.cpp:83] Redis has disconnected, reconnecting [remaining attempts: 7]
20/May/2020 21:56:20 [Redis.cpp:99] ERROR: Connection error [Connection refused]
20/May/2020 21:56:21 [Redis.cpp:83] Redis has disconnected, reconnecting [remaining attempts: 6]
20/May/2020 21:56:21 [Redis.cpp:99] ERROR: Connection error [Connection refused]
20/May/2020 21:56:22 [Redis.cpp:83] Redis has disconnected, reconnecting [remaining attempts: 5]
20/May/2020 21:56:22 [Redis.cpp:99] ERROR: Connection error [Connection refused]
20/May/2020 21:56:23 [Redis.cpp:83] Redis has disconnected, reconnecting [remaining attempts: 4]
20/May/2020 21:56:23 [Redis.cpp:99] ERROR: Connection error [Connection refused]
20/May/2020 21:56:24 [Redis.cpp:83] Redis has disconnected, reconnecting [remaining attempts: 3]
20/May/2020 21:56:24 [Redis.cpp:99] ERROR: Connection error [Connection refused]
20/May/2020 21:56:25 [Redis.cpp:83] Redis has disconnected, reconnecting [remaining attempts: 2]
20/May/2020 21:56:25 [Redis.cpp:99] ERROR: Connection error [Connection refused]
20/May/2020 21:56:26 [Redis.cpp:83] Redis has disconnected, reconnecting [remaining attempts: 1]
20/May/2020 21:56:26 [Redis.cpp:99] ERROR: Connection error [Connection refused]
20/May/2020 21:56:27 [Redis.cpp:83] Redis has disconnected, reconnecting [remaining attempts: 0]
20/May/2020 21:56:27 [Redis.cpp:99] ERROR: Connection error [Connection refused]
20/May/2020 21:56:28 [Redis.cpp:148] ERROR: ntopng requires redis server to be up and running
20/May/2020 21:56:28 [Redis.cpp:149] ERROR: Please start it and try again or use -r
20/May/2020 21:56:28 [Redis.cpp:150] ERROR: to specify a redis server other than the default
gbd:~ root#

**Comment by khoshtip2** [comment]
Now ist working, redis service was not started!

Best regards
Shahram
