### ISSUE TITLE
nv_graph_utils.lua:307: attempt to call a nil value (field 'hasHighResTs')

### ISSUE THREAD

**Issue by Gelob** [ntop/ntopng#3967]
Running https://github.com/ntop/ntopng/commit/0f3616dfe5c38467801b7333d854b7148bfefff6 and getting this error when trying to go to host details and changing Traffic to Protocols on the flows page

https://ntopng.blah.net/lua/host_details.lua?ifid=0&host=1.1.1.1&page=historical&ts_schema=top%3Ahost%3Al4protos&tskey=1.1.1.1&zoom=30m

HTTP/1.1 302 Found Set-Cookie: session=dfe29a5a66d694bca7dc17d02867d4d5; path=/; HttpOnly; SameSite=lax; Secure Location: /lua/http_status_code.lua?message=internal_error&referer=ntopng.blah.net%2Flua%2Fhost_details.lua%3Fifid%3D0%26host%3D1.1.1.1%26page%3Dhistorical%26ts_schema%3Dtop%253Ahost%253Al4protos%26tskey%3D1.1.1.1%26zoom%3D30m&error_message=...%2Fshare%2Fntopng%2Fpro%2Fscripts%2Flua%2Fmodules%2Fnv_graph_utils.lua%3A307%3A%20attempt%20to%20call%20a%20nil%20value%20%28field%20%27hasHighResTs%27%29 .../share/ntopng/pro/scripts/lua/modules/nv_graph_utils.lua:307: attempt to call a nil value (field 'hasHighResTs')

**Comment by simonemainardi** [comment]
Fixed. Build in progress. Wait a couple of hours and upgrade.
