### ISSUE TITLE
Variables not properly initalized

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3969]
In https://github.com/ntop/ntopng/blob/dev/scripts/lua/hosts_stats.lua#L103 most variables are set after (and not before) this call.

**Comment by simonemainardi** [comment]
why these two variables are global? https://github.com/ntop/ntopng/commit/f7a7329741eede639da904b3953b8428b51f7657#diff-47cb6849af9751bf6332f83a8124558aR82
