### ISSUE TITLE
Save Packets in ZMQ Format

### ISSUE THREAD

**Issue by svenvogel** [ntop/ntopng#397]
Can you implement that feature.

thanks

Sven

**Comment by simonemainardi** [comment]
@svenvogel , ZMQ carries aggregated flow data, not packets. Could you please explain what do you need.

**Comment by svenvogel** [comment]
i thought that my values are persistent over time. my problem with the reset of my values #395 i thought i need the dump feature?! maybe i dont need them when #395 that is fixed?

![image](https://cloud.githubusercontent.com/assets/5433844/13094685/a1dda1ca-d50c-11e5-921b-c90ab73e4bf5.png)

**Comment by simonemainardi** [comment]
right, dump features are for packet-interfaces only and are not related with #365.
