### ISSUE TITLE
Can't complete make in ubuntu 20.04

### ISSUE THREAD

**Issue by stratfordv** [ntop/ntopng#3971]
Looks like make runs well until it gets to this point... 
/home/vserver/ntopng/src/LuaEngineNtop.cpp.inc:2610: undefined reference to `rrd_strversion'
src/LuaEngine.o: In function `reset_rrd_state()':
/home/vserver/ntopng/src/LuaEngineNtop.cpp.inc:3399: undefined reference to `rrd_clear_error'
src/LuaEngine.o: In function `ntop_rrd_get_lastupdate(char const*, long*, unsigned long*)':
/home/vserver/ntopng/src/LuaEngineNtop.cpp.inc:3411: undefined reference to `rrd_lastupdate_r'
src/LuaEngine.o: In function `ntop_rrd_create(lua_State*)':
/home/vserver/ntopng/src/LuaEngineNtop.cpp.inc:4664: undefined reference to `rrd_create_r'
/home/vserver/ntopng/src/LuaEngineNtop.cpp.inc:4668: undefined reference to `rrd_get_error'
src/LuaEngine.o: In function `ntop_rrd_update(lua_State*)':
/home/vserver/ntopng/src/LuaEngineNtop.cpp.inc:4745: undefined reference to `rrd_update_r'
/home/vserver/ntopng/src/LuaEngineNtop.cpp.inc:4752: undefined reference to `rrd_get_error'
src/LuaEngine.o: In function `ntop_rrd_tune(lua_State*)':
/home/vserver/ntopng/src/LuaEngineNtop.cpp.inc:4812: undefined reference to `rrd_tune'
/home/vserver/ntopng/src/LuaEngineNtop.cpp.inc:4815: undefined reference to `rrd_get_error'
src/LuaEngine.o: In function `__ntop_rrd_args(lua_State*, char**, char**, long*, long*)':
/home/vserver/ntopng/src/LuaEngineNtop.cpp.inc:4866: undefined reference to `rrd_parsetime'
/home/vserver/ntopng/src/LuaEngineNtop.cpp.inc:4874: undefined reference to `rrd_parsetime'
/home/vserver/ntopng/src/LuaEngineNtop.cpp.inc:4879: undefined reference to `rrd_proc_start_end'
src/LuaEngine.o: In function `__ntop_rrd_status(lua_State*, int, char*, char*)':
/home/vserver/ntopng/src/LuaEngineNtop.cpp.inc:4892: undefined reference to `rrd_get_error'
src/LuaEngine.o: In function `ntop_rrd_fetch(lua_State*)':
/home/vserver/ntopng/src/LuaEngineNtop.cpp.inc:4928: undefined reference to `rrd_fetch_r'
/home/vserver/ntopng/src/LuaEngineNtop.cpp.inc:4941: undefined reference to `rrd_freemem'
/home/vserver/ntopng/src/LuaEngineNtop.cpp.inc:4943: undefined reference to `rrd_freemem'
/home/vserver/ntopng/src/LuaEngineNtop.cpp.inc:4985: undefined reference to `rrd_set_to_DNAN'
/home/vserver/ntopng/src/LuaEngineNtop.cpp.inc:4999: undefined reference to `rrd_freemem'
src/LuaEngine.o: In function `ntop_rrd_fetch_columns(lua_State*)':
/home/vserver/ntopng/src/LuaEngineNtop.cpp.inc:5044: undefined reference to `rrd_fetch_r'
/home/vserver/ntopng/src/LuaEngineNtop.cpp.inc:5075: undefined reference to `rrd_freemem'
/home/vserver/ntopng/src/LuaEngineNtop.cpp.inc:5078: undefined reference to `rrd_freemem'
/home/vserver/ntopng/src/LuaEngineNtop.cpp.inc:5079: undefined reference to `rrd_freemem'
collect2: error: ld returned 1 exit status
Makefile:154: recipe for target 'ntopng' failed
make: *** [ntopng] Error 1

**Comment by simonemainardi** [comment]
did you check https://github.com/ntop/ntopng/blob/dev/doc/README.compilation?

**Comment by stratfordv** [comment]
My apologies, i did miss 1 of the steps.  Compiled perfect.  Another quick question.  I had it running from the .deb before and it said I'm running ntopng Community Edition v.3.2.171227 so I clicked the upgrade buttom which took me to the main ntop page where it shows how to compile from source (https://www.ntop.org/get-started/download/) which is where I compiled the ntopng from.  When I login it still shows the 3.2 version.

**Comment by simonemainardi** [comment]
> Compiled perfect.

good

> When I login it still shows the 3.2 version.

Very likely your system is still running version 3.2. Uninstall it, then do a `make install` to install 4.0. Alternatively, use debs directly also for the 4.0 following the instructions at `packages.ntop.org`
