### ISSUE TITLE
Implement alert filtering

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3974]
As of today alert filtering is implemented but a bit cumbersome.
![Screen Shot 2020-05-22 at 12 19 35](https://user-images.githubusercontent.com/4493366/82658126-c5d54480-9c26-11ea-8bd7-44a541fea0ea.png)

As alerts are being reimplemented (see #3859) we also need to implement a criteria for filtering out in a single place, all "potential" alerts before they become "confirmed". In essence today when an alert is triggered, there is no simple way to discard it before it is generated.
Examples
-  Fortinet firewalls do probing on home networks and thus they generate many "suspicious tcp syn probing" that should be ignored.
- if device X use the DNS to verify the hash of downloaded files (Zeek does) queries like 3a34edefdd2c1ad4bb71214fcb9356e575a334234265e.malware.hash.cymru.com are issued and they generate many alerts

So in essence it needs to be implemented a pre-filtering step when potential alerts can be filtered/silenced in a simple way before they become alert, or drop too many alerts produced by a single device... things like these that can help reducing noise in data analysis.

Please see also #3859.

**Comment by simonemainardi** [comment]
merged with https://github.com/ntop/ntopng/issues/4942
