### ISSUE TITLE
Invalid Alert Links

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3977]
![Screen Shot 2020-05-22 at 15 45 49](https://user-images.githubusercontent.com/4493366/82674343-705b6080-9c43-11ea-839d-9f3f1611484a.png)

In reports like the one below, HREF/anchors to remote hosts will lead to empty pages like
![Screen Shot 2020-05-22 at 15 47 44](https://user-images.githubusercontent.com/4493366/82674443-984ac400-9c43-11ea-9ff1-96313f9e1f10.png)

It is requested to add anchors only to pages that likely are not empty

**Comment by simonemainardi** [comment]
solution is to implement a lua method `get_host_link()` which is used anywhere in ntopng to generate the hyperlink of an host. This method will implement the link generation logic (e.g., by checking if the host is active, if it is remote/local). Then, the `get_host_link()` will be replaced anywhere the link `host_details.lua` is manually generated.

**Comment by simonemainardi** [comment]
Implemented

Now there's a single function across the whole code base which takes care of generating host_details.lua links.

https://github.com/ntop/ntopng/blob/9ba746bd78840b14fbff5cef21993945063a0af3/scripts/lua/modules/lua_utils.lua#L1508

This function can be instructed to check for link existence to avoid creating links that are likely empty. The whole logic to decide whether to show a link or not is contained in a single place

https://github.com/ntop/ntopng/blob/9ba746bd78840b14fbff5cef21993945063a0af3/scripts/lua/modules/lua_utils.lua#L1429

With reference to this issue, alerted hosts which don't have timeseries no longer have their hyperlinks and this saves users from unnecessary clicks

![image](https://user-images.githubusercontent.com/3397663/82927793-88075180-9f81-11ea-8127-5a63c6ee2326.png)
