### ISSUE TITLE
Invalid toggle button layout in Interface preference page (wheel)

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3978]
![Screen Shot 2020-05-23 at 11 29 07](https://user-images.githubusercontent.com/4493366/82727102-a272ce00-9ce8-11ea-9350-ca0948418147.png)

Toggle buttons must be placed in the right column and not together with the column name

**Comment by gabryon99** [comment]
<img width="735" alt="Screenshot 2020-05-25 at 09 06 44" src="https://user-images.githubusercontent.com/14114916/82787608-0fac6d80-9e67-11ea-9bd5-ab8b5f17f381.png">
Fixed

**Comment by gabryon99** [comment]
The bug is on safari browser

**Comment by gabryon99** [comment]
<img width="1085" alt="Screenshot 2020-05-28 at 10 38 10" src="https://user-images.githubusercontent.com/14114916/83118941-54d2d880-a0cf-11ea-8b0f-6402c36862f8.png">

Fixed in safari as well
