### ISSUE TITLE
Symbolic IP addresses not supported in SNMP Add Device

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3980]
![Screen Shot 2020-05-24 at 23 08 40](https://user-images.githubusercontent.com/4493366/82765025-96375f80-9e13-11ea-8e58-4d9588553d2a.png)

As of the above screenshot, symbolic IP addresses are not supported.

It is requested to support them and in that case the CIDR will be set to /32

**Comment by simonemainardi** [comment]
@gabryon99 to validate the symbolic host name use the same validation function used for the host name in alert endpoints

**Comment by gabryon99** [comment]
See the commit: https://github.com/ntop/ntopng/commit/a5c8be329a034d754c757e478fba0f5acc3b93a0

**Comment by lucaderi** [comment]
Not working. You need a server side IP address validation

**Comment by simonemainardi** [comment]
implemented using server side address validation and resolution via a REST SNMP endpoint https://www.ntop.org/guides/ntopng/api/rest/api_v1.html#SNMP

Now the 'add' modal stays open until the 'add' request has succeeded. In case of errors (e.g., resolution failed) the modal shows an error and allows the user to opportunely modify the fields.

![image](https://user-images.githubusercontent.com/3397663/85003351-62233600-b156-11ea-822a-59a26de0c685.png)

![image](https://user-images.githubusercontent.com/3397663/85003540-a44c7780-b156-11ea-9343-ffc1d25e5de6.png)
