### ISSUE TITLE
SNMP table is not standard

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3981]
![Screen Shot 2020-05-25 at 11 44 54](https://user-images.githubusercontent.com/4493366/82801220-3f667000-9e7d-11ea-8fb5-1191eb6faf5f.png)

The above table has several glitches
- the "Add device" must be converted to a '+' as in the other tables
- The "Delete all devices" but be present also in all other ntopng tables
- Missing import/export buttons

**Comment by simonemainardi** [comment]
Desirable to have the page generated using a template and with the new datatable.

**Comment by simonemainardi** [comment]
Missing import/export buttons in separate issue: https://github.com/ntop/ntopng/issues/4044
Other requests implemented.
