### ISSUE TITLE
Can't access ntopng at 3000 port

### ISSUE THREAD

**Issue by operations999** [ntop/ntopng#3983]
I have installed ntopng and nprobe. Can't access via port 3000.
config is like this
--zmq="tcp://*:5556"
-i=eno1
-n=1
--collector-port=6343
-w=3000
But your doc https://www.ntop.org/guides/ntopng/how_to_start/configuration_file.html
show different.

**Comment by emanuele-f** [comment]
Please report each individual config separately (ntopng.conf and nprobe.conf). Ensure that the ntopng service is running (`sudo systemctl status ntopng`). Check out https://www.ntop.org/nprobe/network-monitoring-101-a-beginners-guide-to-understanding-ntop-tools .

**Comment by operations999** [comment]
nprobe.conf 

 --zmq="tcp://*:5556"
-i=none
-n=none
--collector-port=2222

ntopng.conf 
--zmq="tcp://*:5556"
#-i=en01
-n=3
--collector-port=6343
-w=3000
-i="tcp://127.0.0.1:5556"
--local-networks="x.x.x.x/24"  

 sudo systemctl status ntopng
â ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/usr/lib/systemd/system/ntopng.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2020-05-25 11:26:13 EDT; 2min 3s ago
  Process: 16467 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|^[ ]*--pid.*/s/^/#/" /etc/ntopng/ntopng.conf > /run/ntopng.conf (code=exited, status=0/SUCCESS)
  Process: 16452 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exited, status=0/SUCCESS)
 Main PID: 16469 (ntopng)

**Comment by operations999** [comment]
OK was able to fix it. Now issue is ntopng not detecting the snmp device. When I add the device with ip,community and version .. it does not add.
I am running same snmp setting for other program and it works fine. 
Checked tcpdump and I see the traffic is coming from the switch.
Any pointer?
