### ISSUE TITLE
 Device SNMP walk in progress forever

### ISSUE THREAD

**Issue by operations999** [ntop/ntopng#3986]
Hello,
I have added SNMP device but when I click on device to see interfaces I am getting 

". This may take up to 5 minutes. The page will refresh periodically."
Looks like some settings issue?

**Comment by simonemainardi** [comment]
Please hold on an SNMP rework is in progress on the dev.

Track https://github.com/ntop/ntopng/issues/3686 and https://github.com/ntop/ntopng/issues/3138

**Comment by operations999** [comment]
so shall I leave it on hold or you want some more info for developer?
Thanks

**Comment by simonemainardi** [comment]
yes, please leave it on hold, we will notify you.

**Comment by operations999** [comment]
Hello,
Is this issue fixed?
Thanks

**Comment by lucaderi** [comment]
Almost, we'll close this ticket when done

**Comment by lucaderi** [comment]
We have made some fixed in SNMP. Can you please update and report?

**Comment by operations999** [comment]
Hello,
I have updated to latest versions and restarted services. But I see still same issue.
https://prnt.sc/swn12r
Thanks

**Comment by lucaderi** [comment]
What ntopng version are you using exactly?

**Comment by operations999** [comment]
Here is the output
Version | 4.0.200608 (10465) -  Enterprise M Edition
-- | --
x86_64-unknown-linux-gnu [x86_64][] - 64 bit

**Comment by lucaderi** [comment]
All changes are in the dev branch, The stable will be updated as soon as the changes has been validated as working. Please use the nightly build

**Comment by operations999** [comment]
Works now :)  Thank you
