### ISSUE TITLE
Block traffic while attack

### ISSUE THREAD

**Issue by jensmolsson** [ntop/ntopng#399]
If a host (IP) get a system alert, for example, scan attack, it would be great to block all traffic to that host/IP for example, 5 min.

Otherwise, its possible to get a request from system when an system warning has ben made? Then it would not be that hard to make this function :)

**Comment by simonemainardi** [comment]
you can get properly formatted warning JSON data by fetching endpoints

 "http://host:3000/lua/get_alerts_data.lua?status=engaged&currentPage=1&perPage=10&sortColumn=column_date&sortOrder=desc"
"http://host:3000/lua/get_alerts_data.lua?status=engaged&currentPage=1&perPage=10&sortColumn=column_date&sortOrder=desc"
"http://host:3000/lua/get_alerts_data.lua?status=historical-flows&currentPage=1&perPage=10&sortColumn=column_date&sortOrder=desc"
