### ISSUE TITLE
Ntopng + influxdb + Grafana

### ISSUE THREAD

**Issue by operations999** [ntop/ntopng#3990]
Hello,
I have configured influxdb in ntopng and its working fine.
Grafana is hosted on remote server with ip say 1.1.1.2:3000 and ntopng 2.2.2.2:30000
I enabled the ntopng module in grafana.. basic auth but it does not work.
Running latest version of  ntopng, grafana n influxb.
Anyone know how to fix or I install grafana on ntopng server?
Thanks

**Comment by simonemainardi** [comment]
ntopng grafana datasource plugin has been discontinued as explained in https://github.com/ntop/ntopng-grafana-datasource#discontinuation-notice

please use the grafana influxdb datasource plugin and connect to the ntopng influxdb database

**Comment by operations999** [comment]
This is not very well documented and pot of info is missing if you have to integrate grafana running on remote server.
