### ISSUE TITLE
nIndex support on stable package for ubuntu 20.04

### ISSUE THREAD

**Issue by zinchang** [ntop/ntopng#3999]
Request supporting flow dump by nIndex on stable package for ubuntu 20.04.

> % apt show ntopng
Package: ntopng
Version: 4.0.200525-10337
Priority: optional
Section: free
Maintainer: Luca Deri <deri@ntop.org>
Installed-Size: 71.4 MB
Depends: pfring (= 7.6.0-3000), libsqlite3-0, libexpat1, redis-server, librrd8, logrotate, libcurl4, libpcap0.8, libldap-2.4-2, libhiredis0.14, libssl1.1, libmysqlclient21, librdkafka1, lsb-release, tar, ethtool, libcap2, libzstd1, libmaxminddb0, n2n, libradcli4, libjson-c4, udev, debconf, libnuma1, libzmq5, libnetfilter-queue1
Recommends: ntopng-data
Conflicts: nedge
Replaces: ntop
Download-Size: 11.5 MB
APT-Manual-Installed: yes
APT-Sources: http://packages.ntop.org/apt-stable/20.04 x64/ Packages
Description: Web-based traffic monitoring.

> % /usr/local/bin/ntopng -V
v.4.0.200525	[Enterprise/Professional build]
GIT rev:	4.0-stable:cb880a2ecf9cdef198307d906ee0ba0374f37e4e:20200525
Pro rev:	r2814
Built on:	Ubuntu 20.04 LTS
Platform:	x86_64
Edition:	Enterprise L

>% /usr/local/bin/ntopng -F nindex
29/May/2020 04:22:25 [Prefs.cpp:1306] WARNING: Discarding -F nindex: value out of range

**Comment by simonemainardi** [comment]
Reproduced. Fix in progress.

**Comment by lucaderi** [comment]
Fixed in the latest packages build
