### ISSUE TITLE
Missing dependency on OS/X Yosemite

### ISSUE THREAD

**Issue by tsimmons** [ntop/ntopng#4]
I haven't built ntopng in a while. When trying to build it on Yosemite I get the following linker error:

`/usr/bin/clang++  src/Ntop.o  src/DnsStats.o  src/Prefs.o  src/GenericHash.o  src/Categorization.o  src/EthStats.o  src/HTTPserver.o  src/StringHost.o  src/VirtualHost.o  src/StringHash.o  src/PacketDumperTuntap.o  src/HistoricalInterface.o  src/AddressResolution.o  src/HostContacts.o  src/main.o  src/NetworkInterfaceView.o  src/Mutex.o  src/NetworkInterface.o  src/TrafficStats.o  src/ExportInterface.o  src/EppStats.o  src/Redis.o  src/Flow.o  src/Host.o  src/IpAddress.o  src/DB.o  src/RuntimePrefs.o  src/ActivityStats.o  src/PacketDumper.o  src/LocalTrafficStats.o  src/PeriodicActivities.o  src/PacketStats.o  src/HTTPBL.o  src/GenericHost.o  src/VirtualHostHash.o  src/AlertCounter.o  src/HTTPStats.o  src/FlowHash.o  src/Geolocation.o  src/NtopGlobals.o  src/PcapInterface.o  src/PF_RINGInterface.o  src/ParserInterface.o  src/Trace.o  src/CollectorInterface.o  src/Utils.o  src/HostHash.o  src/SimpleStringHost.o  src/ProtoStats.o  src/GenericHashEntry.o  src/StatsManager.o  src/Lua.o  src/NdpiStats.o  -Wall ./nDPI/src/lib/.libs/libndpi.a -lpcap ./third-party/LuaJIT-2.0.3/src/libluajit.a third-party/rrdtool-1.4.8/src/.libs/librrd_th.a -lm -lgobject-2.0 -lgmodule-2.0 -ldl -lglib-2.0 ./third-party/zeromq-4.0.5/src/.libs/libzmq.a third-party/json-c/.libs/libjson-c.a  -lsqlite3 -pagezero_size 10000 -image_base 100000000   -L/usr/local/lib -ldl -lcurl  -lm -lpthread -lstdc++.6 -o ntopng`

`ld: library not found for -lgobject-2.0`

I have glib2 installed via macports but it apparently is missing lgobject-2.0. Is there another port that contains lgobject-2.0?

**Comment by lucaderi** [comment]
I use brew and it works for me.
On brew I do
brew install redis hiredis autoconf automake libtool rrdtool wget pkg-config git

Please figure out what you need to do on macports and then send me a merge request for the README.ntopng

thanks

**Comment by simonemainardi** [comment]
macports installs libraries in `/opt/local/lib` by default.

Edit `configure.seed` and append `-L/opt/local/lib` to `LDFLAGS`:
```
LDFLAGS="${LDFLAGS} -L/usr/local/lib -L/opt/local/lib"
```
Then
```
./autogen.sh
./configure
make
```
