### ISSUE TITLE
can't stat after update

### ISSUE THREAD

**Issue by ssnex** [ntop/ntopng#400]
ntopng -V

```
v.2.3.160216 [Professional Edition]
Built on:  CentOS release 6.7 (Final)
```

================ ntopng log ====================================

16/Feb/2016 21:05:37 [Ntop.cpp:975] Setting local networks to 10.0.1.0/24
16/Feb/2016 21:05:37 [Redis.cpp:106] Successfully connected to redis 127.0.0.1:6379@0
16/Feb/2016 21:05:37 [main.cpp:183] **ERROR**: Unable to create interface eth2
16/Feb/2016 21:05:37 [PcapInterface.cpp:85] Reading packets from interface eth2...
16/Feb/2016 21:05:37 [Ntop.cpp:1194] Registered interface eth2 [id: 0]
16/Feb/2016 21:05:37 [main.cpp:183] **ERROR**: Unable to create interface eth1
16/Feb/2016 21:05:37 [PcapInterface.cpp:85] Reading packets from interface eth1...
16/Feb/2016 21:05:37 [Ntop.cpp:1194] Registered interface eth1 [id: 1]
16/Feb/2016 21:05:37 [main.cpp:183] **ERROR**: Unable to create interface eth0
16/Feb/2016 21:05:37 [PcapInterface.cpp:85] Reading packets from interface eth0...
16/Feb/2016 21:05:37 [Ntop.cpp:1194] Registered interface eth0 [id: 2]
16/Feb/2016 21:05:37 [main.cpp:183] **ERROR**: Unable to create interface ppp0
16/Feb/2016 21:05:37 [PcapInterface.cpp:85] Reading packets from interface ppp0...
16/Feb/2016 21:05:37 [Ntop.cpp:1194] Registered interface ppp0 [id: 3]
16/Feb/2016 21:05:37 [Ntop.cpp:1207] Registered interface view eth2 [id: 0]
16/Feb/2016 21:05:37 [Ntop.cpp:1207] Registered interface view eth1 [id: 1]
16/Feb/2016 21:05:37 [Ntop.cpp:1207] Registered interface view eth0 [id: 2]
16/Feb/2016 21:05:37 [Ntop.cpp:1207] Registered interface view ppp0 [id: 3]
16/Feb/2016 21:05:37 [Utils.cpp:305] User changed to ntop
16/Feb/2016 21:05:37 [main.cpp:252] PID stored in file /var/tmp/ntopng.gid
16/Feb/2016 21:05:37 [HTTPserver.cpp:460] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
16/Feb/2016 21:05:37 [HTTPserver.cpp:503] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
16/Feb/2016 21:05:37 [HTTPserver.cpp:506] HTTP server listening on port 3000
16/Feb/2016 21:05:37 [main.cpp:289] Working directory: /var/tmp/ntopng
16/Feb/2016 21:05:37 [main.cpp:291] Scripts/HTML pages directory: /usr/share/ntopng
16/Feb/2016 21:05:37 [Ntop.cpp:258] Welcome to ntopng x86_64 v.2.3.160216 - (C) 1998-16 ntop.org
16/Feb/2016 21:05:37 [Ntop.cpp:263] Built on CentOS release 6.7 (Final)
16/Feb/2016 21:05:37 [PeriodicActivities.cpp:53] Started periodic activities loop...
16/Feb/2016 21:05:37 [RuntimePrefs.cpp:34] Dumping alerts into syslog
16/Feb/2016 21:05:37 [NtopPro.cpp:233] [LICENSE] ntopng systemId: 1586A497144A2D2
16/Feb/2016 21:05:37 [NtopPro.cpp:236] [LICENSE] ntopng is starting without a valid license
16/Feb/2016 21:05:37 [Ntop.cpp:514] Adding 10.0.1.0/24 as IPv4 local network for eth2
16/Feb/2016 21:05:37 [Ntop.cpp:514] Adding 45.46.152.0/20 as IPv4 local network for eth0
16/Feb/2016 21:05:37 [Ntop.cpp:514] Adding 10.24.21.0/24 as IPv4 local network for eth1
16/Feb/2016 21:05:37 [Ntop.cpp:514] Adding 144.44.11.176/32 as IPv4 local network for ppp0
16/Feb/2016 21:05:37 [Ntop.cpp:544] Adding fe80::24c:c4ff:fe47:850d/64 as IPv6 local network for eth2
16/Feb/2016 21:05:37 [Ntop.cpp:544] Adding fe80::5054:ff:f33c:6557/64 as IPv6 local network for eth0
16/Feb/2016 21:05:37 [Ntop.cpp:544] Adding fe80::21c:c4ff:fe27:8b42/64 as IPv6 local network for eth1
16/Feb/2016 21:05:37 [NetworkInterface.cpp:1417] Started packet polling on interface eth2 [id: 0]...
16/Feb/2016 21:05:37 [NetworkInterface.cpp:1417] Started packet polling on interface eth1 [id: 1]...
16/Feb/2016 21:05:37 [NetworkInterface.cpp:1417] Started packet polling on interface eth0 [id: 2]...
16/Feb/2016 21:05:37 [NetworkInterface.cpp:1417] Started packet polling on interface ppp0 [id: 3]...

================= system logs ============================

Feb 16 21:05:37 sol-fttb root: ntopng restart
Feb 16 21:05:37 sol-fttb ntopng: [main.cpp:183] ERROR: Unable to create interface eth2
Feb 16 21:05:37 sol-fttb kernel: device eth2 entered promiscuous mode
Feb 16 21:05:37 sol-fttb ntopng: [main.cpp:183] ERROR: Unable to create interface eth1
Feb 16 21:05:37 sol-fttb kernel: device eth1 entered promiscuous mode
Feb 16 21:05:37 sol-fttb ntopng: [main.cpp:183] ERROR: Unable to create interface eth0
Feb 16 21:05:37 sol-fttb kernel: device eth0 entered promiscuous mode
Feb 16 21:05:37 sol-fttb ntopng: [main.cpp:183] ERROR: Unable to create interface ppp0
Feb 16 21:05:37 sol-fttb kernel: device ppp0 entered promiscuous mode
Feb 16 21:05:38 sol-fttb kernel: ntopng[12617]: **segfault at 7f7d44077a90 ip 0000000000447a5c sp 00007f7d621fb490 error 4 in ntopng[400000+257000]**
Feb 16 21:05:38 sol-fttb kernel: device eth2 left promiscuous mode
Feb 16 21:05:38 sol-fttb kernel: device eth1 left promiscuous mode
Feb 16 21:05:38 sol-fttb kernel: device eth0 left promiscuous mode
Feb 16 21:05:38 sol-fttb kernel: device ppp0 left promiscuous mode

**Comment by lucaderi** [comment]
@SANYA-SNEX Please post the whole command line you use to start ntopng and check if you are root

**Comment by ssnex** [comment]
service ntopng start 

/etc/ntopng/ntopng.conf

```
-G=/var/tmp/ntopng.gid
--http-port 3000
--user ntop
--local-networks 10.0.1.0/24
--interface eth0
--interface eth1
--interface eth2
--interface ppp0
--community
```

I run this from root and i try change 
_--user ntop_  to _--user root_
and problem not solve

**Comment by lucaderi** [comment]
I have made some changes that will be included in the next packages. Build. Please report.

**Comment by ssnex** [comment]
error 404 
I try after some time. Problem with the server where the package is.

# yum update

```
........
http://packages.ntop.org/centos/6/x86_64/Packages/ntopng-2.3.160218-884.x86_64.rpm: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"

http://packages.ntop.org/centos/6/noarch/Packages/ntopng-data-2.3.160218-884.noarch.rpm: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
........
```

**Comment by ssnex** [comment]
yum clean metadata
yum update
ntopng -V

## v.2.3.160218 [Professional Edition]

Try try to start 

# 

# method 1 NOT working:

**sudo ntopng --http-port 3000 --local-networks 10.0.1.0/24 --user ntop  --interface eth0 --interface eth1 --interface eth2 --community**

================ ntopng log ====================================

```
18/Feb/2016 20:16:27 [Ntop.cpp:975] Setting local networks to 10.0.1.0/24
18/Feb/2016 20:16:27 [Redis.cpp:106] Successfully connected to redis 127.0.0.1:6379@0
18/Feb/2016 20:16:27 [PcapInterface.cpp:85] Reading packets from interface eth2...
18/Feb/2016 20:16:27 [Ntop.cpp:1194] Registered interface eth2 [id: 0]
18/Feb/2016 20:16:27 [PcapInterface.cpp:85] Reading packets from interface eth1...
18/Feb/2016 20:16:27 [Ntop.cpp:1194] Registered interface eth1 [id: 1]
18/Feb/2016 20:16:27 [PcapInterface.cpp:85] Reading packets from interface eth0...
18/Feb/2016 20:16:27 [Ntop.cpp:1194] Registered interface eth0 [id: 2]
18/Feb/2016 20:16:27 [Ntop.cpp:1207] Registered interface view eth2 [id: 0]
18/Feb/2016 20:16:27 [Ntop.cpp:1207] Registered interface view eth1 [id: 1]
18/Feb/2016 20:16:27 [Ntop.cpp:1207] Registered interface view eth0 [id: 2]
18/Feb/2016 20:16:27 [Utils.cpp:305] User changed to ntop
18/Feb/2016 20:16:27 [main.cpp:258] PID stored in file /var/tmp/ntopng.pid
18/Feb/2016 20:16:27 [HTTPserver.cpp:460] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
18/Feb/2016 20:16:27 [HTTPserver.cpp:503] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
18/Feb/2016 20:16:27 [HTTPserver.cpp:506] HTTP server listening on port 3000
18/Feb/2016 20:16:27 [main.cpp:295] Working directory: /var/tmp/ntopng
18/Feb/2016 20:16:27 [main.cpp:297] Scripts/HTML pages directory: /usr/share/ntopng
18/Feb/2016 20:16:27 [Ntop.cpp:258] Welcome to ntopng x86_64 v.2.3.160218 - (C) 1998-16 ntop.org
18/Feb/2016 20:16:27 [Ntop.cpp:263] Built on CentOS release 6.7 (Final)
18/Feb/2016 20:16:27 [PeriodicActivities.cpp:53] Started periodic activities loop...
18/Feb/2016 20:16:27 [RuntimePrefs.cpp:34] Dumping alerts into syslog
18/Feb/2016 20:16:27 [NtopPro.cpp:233] [LICENSE] ntopng systemId: 123F6A597104A1D2
18/Feb/2016 20:16:27 [NtopPro.cpp:236] [LICENSE] ntopng is starting without a valid license
18/Feb/2016 20:16:27 [Ntop.cpp:514] Adding 10.0.1.0/24 as IPv4 local network for eth2
18/Feb/2016 20:16:27 [Ntop.cpp:514] Adding 45.46.152.0/20 as IPv4 local network for eth0
18/Feb/2016 20:16:27 [Ntop.cpp:514] Adding 10.24.21.0/24 as IPv4 local network for eth1
18/Feb/2016 20:16:27 [Ntop.cpp:544] Adding fe80::24c:c4ff:fe47:850d/64 as IPv6 local network for eth2
18/Feb/2016 20:16:27 [Ntop.cpp:544] Adding fe80::5054:ff:f33c:6557/64 as IPv6 local network for eth0
18/Feb/2016 20:16:27 [Ntop.cpp:544] Adding fe80::21c:c4ff:fe27:8b42/64 as IPv6 local network for eth1
18/Feb/2016 20:16:27 [NetworkInterface.cpp:1417] Started packet polling on interface eth2 [id: 0]...
18/Feb/2016 20:16:27 [NetworkInterface.cpp:1417] Started packet polling on interface eth1 [id: 1]...
18/Feb/2016 20:16:27 [NetworkInterface.cpp:1417] Started packet polling on interface eth0 [id: 2]...
```

================= system logs ============================

Feb 18 20:16:27 sol-fttb kernel: device eth2 entered promiscuous mode
Feb 18 20:16:27 sol-fttb kernel: device eth1 entered promiscuous mode
Feb 18 20:16:27 sol-fttb kernel: device eth0 entered promiscuous mode
Feb 18 20:16:29 sol-fttb kernel: ntopng[23056]: segfault at 7f5ec4094400 ip 00000000004477bc sp 00007f5ef8df9490 error 4 in ntopng[400000+256000]
Feb 18 20:16:29 sol-fttb kernel: device eth2 left promiscuous mode
Feb 18 20:16:29 sol-fttb kernel: device eth1 left promiscuous mode
Feb 18 20:16:29 sol-fttb kernel: device eth0 left promiscuous mode

# 

# method 2 working:

But now works when selecting  interface: eth1 and ppp0 not working for others: eth2 and eth0

when I run:

**sudo ntopng --http-port 3000 --local-networks 10.0.41.0/24 --user ntop  --interface eth1 --interface ppp0 --community**

**Working!!!**

ppp0 is conected via eth1

eth1, eth2, eth0 is port on one network card: 
HP Quad Port Server Adapter PCI-E NC364T

---

The problem is in the network card?
Problem in the settings of ports?
What to do next? How do I find a mistake?

**Comment by lucaderi** [comment]
Please generate a core of ntopng (in the first case) and put it somewhere so I can download it. I need to investigate this strange issue. Also attach the output of "ntopng --version". Thanks

**Comment by ssnex** [comment]
I had never done core dump so I unsure what am I doing it right.
I do it like write in this page:
http://www.ntop.org/support/need-help-2/need-help/

git clone https://github.com/ntop/ntopng.git
cd ntopng
./autogen.sh
./configure

_checking for nDPI... not found_

cd ..
git clone https://github.com/ntop/nDPI.git
cd nDPI
./autogen.sh
make
cd ../ntopng
./autogen.sh
./configure

```
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for numa_available in -lnuma... no
checking for nDPI... found in ../nDPI
checking for ../nDPI/src/lib/.libs/libndpi.a... found ../nDPI/src/lib/.libs/libndpi.a
checking for ntopng professional edition... not found
Compiling ntopng with PF_RING support
WARNING Your ntopng will compile with PF_RING support but the libnuma library is not installed
WARNING This might lead to compilation errors
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... no
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking libnetfilter_queue/libnetfilter_queue.h usability... no
checking libnetfilter_queue/libnetfilter_queue.h presence... no
checking for libnetfilter_queue/libnetfilter_queue.h... no
checking for nfq_create_queue in -lnetfilter_queue... no
checking for nfq_set_verdict2... no
checking for ldap_initialize in -lldap... no
checking for nl_handle_alloc in -lnl... no
checking for clock_gettime in -lrt... no
checking for dlopen in -ldl... no
checking for curl_easy_perform in -lcurl... no
Please install libcurl(-dev) (http://curl.haxx.se/)
```

yum list libcurl libcurl-devel

```
libcurl.x86_64                                                                 7.19.7-46.el6                                                            
libcurl-devel.x86_64                                                           7.19.7-46.el6                                                            
```

**Please tell me how to properly to make core file?**

**Comment by ssnex** [comment]
ntopng -V
v.2.3.160223 [Professional Edition]

ntopng    x86_64      2.3.160223-910 
ntopng-data   noarch   2.3.160223-910 

seems began to work. I now do not know whether to update or not

**Comment by lucaderi** [comment]
Yesterday we have fixed a crash, might be that it affected you and it's solved by now

**Comment by lucaderi** [comment]
Closed for inactivity (or more likely because the fix solved the problem)
