### ISSUE TITLE
Selecting eth0 of eth1 in navbar menu redirect to /?ifid=1 instead of http-prefix/?ifid=1

### ISSUE THREAD

**Issue by andpp** [ntop/ntopng#4001]
Browser: **Google Chrome. Version 83.0.4103.61 (Official Build) (64-bit)**
Branch: **4.0-stable**
Last commit: commit cb880a2ecf9cdef198307d906ee0ba0374f37e4e (HEAD -> 4.0-stable, origin/4.0-stable)
Author: emanuele-f <faranda@ntop.org>
Date:   Mon May 25 14:09:00 2020 +0200

Previous issue: https://github.com/ntop/ntopng/issues/3972
Commit https://github.com/ntop/ntopng/commit/c4a2cf100e129b3706a2da35f7eee5c9fa90227b doesn't help. Still redirect in navbar menu to **/?ifid=1** instead of **http-prefix/?ifid=1**

![ntop-bug](https://user-images.githubusercontent.com/12842195/82595722-f18af880-9b5a-11ea-8913-8d998f74fdd5.jpg)

Selecting **eth0** or **eth1** from this menu redirects to /?ifid=1 or /?ifid=0 instead of http-prefix/?ifid=1

**Comment by andpp** [comment]
When I use the menu to switch interface on page:
**/http-prefix/lua/if_stats.lua?ifid=0&page=historical&ts_schema=iface%3Atraffic&zoom=1h&epoch=**

it switched to /**?ifid=1&zoom=1h&epoch=&ts_schema=iface%3Atraffic&page=historical**

It looks like the menu just remove whole link and keeps only parameters in the URL. I guess that's why commit https://github.com/ntop/ntopng/commit/c4a2cf100e129b3706a2da35f7eee5c9fa90227b doesn't help

**Comment by lucaderi** [comment]
Can you please report the exact ntopng version you are using? ntopng --version

**Comment by andpp** [comment]
$ ntopng --version
v.4.0.200518	[Community build]
GIT rev:	4.0-stable:8b73b34242a393e395a901c4bf54e5dff6d6dd0c:20200518

**Comment by andpp** [comment]
$ git log
commit 66a6a440e6959f980140ac0ee4dfaded50b18a8e (HEAD -> 4.0-stable, origin/4.0-stable)
Author: Luca Deri <deri@ntop.org>
Date:   Sat May 30 17:00:00 2020 +0000

    Removed double \n

commit cb880a2ecf9cdef198307d906ee0ba0374f37e4e
Author: emanuele-f <faranda@ntop.org>
Date:   Mon May 25 14:09:00 2020 +0200

    Add checks to avoid wrapping in frame_padding

commit 7f014f9d10133db242d4256413cbb55a69dd8b48
Author: emanuele-f <faranda@ntop.org>
Date:   Mon May 25 12:13:52 2020 +0200

    Remove ethernet frame padding from l4 trusted length

commit 5dd517675dc18e8337f7d32545c6ccceb8ccbf83
Author: Luca Deri <lucaderi@users.noreply.github.com>
Date:   Fri May 22 20:02:43 2020 +0200

    Fix for switching across non-system interfaces
    
    Fix for switching across non-system interfaces with --http-prefix set

commit 522650bc13832d31bd890f5822ebcbaa78e35ede
Author: Simone Mainardi <mainardi@ntop.org>
Date:   Fri May 22 14:26:15 2020 +0200

    Fixes traffic recording linked to ZMQ interfaces

**Comment by andpp** [comment]
I am building from source code from **4.0-stable** branch

**Comment by simonemainardi** [comment]
Working as expected as of e3d078122397cd14fef0f4817778c9dbefc28263

Look at the prefix in the URL:

![switch](https://user-images.githubusercontent.com/3397663/83656384-c0c9ab00-a5bf-11ea-8c15-4a25010e553b.gif)

ntopng started as

```
$ sudo   ./ntopng -i tcp://127.0.0.1:5556c -i eno1 -i lo -m "192.168.2.0/24,91.189.0.0/16" -X 3600000 -x 3600000 --http-prefix /simone
```
