### ISSUE TITLE
Alert when unexpected IP addresses show up

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4002]
Create a plugin that triggers an alert when an unexpected (local) IP address shows up.

Requirement
- allow people to configure the list of IP addresses that are permitted in a network. They can be specified as CIDR an as IP-ranges such as in DHCP
- When the plugin is activated, and alert is triggered whenever a local IP address not belonging to the specified range is detected.

**Comment by martinscheu** [comment]
Additionally to ranges, a list with single IP addresses should be possible as well, as small setups may include 6-10 local addresses only.

**Comment by lucaderi** [comment]
This ticket depends on #4675

**Comment by lucaderi** [comment]
This is now implemented with MAC tracking
