### ISSUE TITLE
Create metric for counting the number of peers contacted

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4005]
Scanners or simply suspicious hosts (e.g. possible hosts that run malware), usually contact many hosts on the Internet to spread the infection. Having a counter of (per minute) contacted hosts, can help tracking this type of problems.

**Comment by simonemainardi** [comment]
I propose to implement an estimator such as HyperLogLog (https://en.wikipedia.org/wiki/HyperLogLog) to keep an estimate of the number of contacted hosts with a very small memory impact. Then, this estimator can be periodically reset and its values written to timeseries.

**Comment by simonemainardi** [comment]
currently,  `LocalHostStats` keeps already

```
std::map<Host*, u_int16_t> contacts_as_cli, contacts_as_srv;
```

but this is very heavy in terms of memory (all this suff is kept for each local host) and cumbersome in terms of implementation
