### ISSUE TITLE
Trigger an alert when a host contacts an unusual number of peers

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4006]
This ticket depends on #4005

Tt is requested to create a plugin that can trigger an alert when a large number of peers is contacted. As the threshold for this alert can be hard to pick, it is requested to study how to implement is and what are the possible solutions on the table. For instance
- static threshold: simple but hard to find an acceptable limit for all hosts
- delta with respect to the previous value: nice for detecting peaks but won't catch situations where the number increases slowly overtime

**Comment by simonemainardi** [comment]
implementation will be done as follows:

- create a "Contacted Peers Alert" user script similar to the host traffic user script
- Add only a metric ">" and "Hosts as "unit of measure"
- Make it enabled by default (minute) with 2048 as default value
- Use "num_contacted_hosts_as_client" and "num_host_contacts_as_server" inside the host C to evaluate the host user script. May need to expose them with two calls host.getNumContactsAsServer and host.getNumContactsAsClient. The threshold is one (2048 default) but has to be evaluated with both client and server num contacts.
- In the resulting alert message, information whether contacts as client or as server (or both) are exceeded. See `function format_utils.formatConnectionIssues` to create a similar alert message

**Comment by lucaderi** [comment]
"Trigger an alert when too many peers are contacted as both client or server" is meaningless. Please explain the algorithm used to trigger an alert, and what is the meaning of "too many" in your parlance
