### ISSUE TITLE
hooks.protocolDetected(now) triggers twice

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#4008]
when using user script "script.hooks.protocolDetected(now)" it triggers twice.
when trigger occurs, extract packet payload with flow.getnDPIMatchPacket()

example 1) iec_connect_2.pcap, second trigger show payload == nil : 
<img width="310" alt="Screenshot 2020-05-29 at 14 18 02" src="https://user-images.githubusercontent.com/38549755/83348713-41be4380-a32f-11ea-9442-e8667bb9ec8d.png">

example 2) dhcp.pcap, second trigger gives payload "DHCP Offer"

[iec_connect_2.pcap.zip](https://github.com/ntop/ntopng/files/4707400/iec_connect_2.pcap.zip)
[dhcp.pcap.zip](https://github.com/ntop/ntopng/files/4707417/dhcp.pcap.zip)

**Comment by simonemainardi** [comment]
acutally, I don't get the hook protocolDetected executed more than once...

```
simone@devel:~/ntopng$ sudo   ./ntopng -i ~/iec_connect_2.pcap -X 3600000 -x 3600000
...
01/Jun/2020 12:45:04 [NetworkInterface.cpp:2347] Started packet polling on interface /home/simone/iec_connect_2.pcap [id: 13]...
01/Jun/2020 12:45:05 [PcapInterface.cpp:341] Terminated packet polling for /home/simone/iec_connect_2.pcap
01/Jun/2020 12:45:05 [LuaEngineNtop.cpp.inc:4483] [ifid: 13] flow.lua:setup() called
01/Jun/2020 12:45:05 [LuaEngineNtop.cpp.inc:4483] [ifid: 13] protocolDetected()[START]: bitmap=0x0 predominant=0
01/Jun/2020 12:45:05 [LuaEngineNtop.cpp.inc:4483] [ifid: 13] protocolDetected() [check: tls_unsafe_ciphers]: skipping flow with proto=0/245 [wants: 91]
01/Jun/2020 12:45:05 [LuaEngineNtop.cpp.inc:4483] [ifid: 13] protocolDetected() [check: web_mining]: [IEC60870] TCP 192.168.7.50:60662 -> 192.168.7.85:2404
01/Jun/2020 12:45:05 [LuaEngineNtop.cpp.inc:4483] [ifid: 13] protocolDetected() [check: tcp_probing]: [IEC60870] TCP 192.168.7.50:60662 -> 192.168.7.85:2404
01/Jun/2020 12:45:05 [LuaEngineNtop.cpp.inc:4483] [ifid: 13] protocolDetected() [check: tls_certificate_selfsigned]: skipping flow with proto=0/245 [wants: 91]
01/Jun/2020 12:45:05 [LuaEngineNtop.cpp.inc:4483] [ifid: 13] protocolDetected() [check: tls_old_version]: skipping flow with proto=0/245 [wants: 91]
01/Jun/2020 12:45:05 [LuaEngineNtop.cpp.inc:4483] [ifid: 13] protocolDetected() [check: device_protocol_not_allowed]: [IEC60870] TCP 192.168.7.50:60662 -> 192.168.7.85:2404
01/Jun/2020 12:45:05 [LuaEngineNtop.cpp.inc:4483] [ifid: 13] protocolDetected() [check: tls_certificate_mismatch]: skipping flow with incomplete three way handshake
01/Jun/2020 12:45:05 [LuaEngineNtop.cpp.inc:4483] [ifid: 13] protocolDetected() [check: invalid_dns_query]: skipping flow with proto=0/245 [wants: 5]
01/Jun/2020 12:45:05 [LuaEngineNtop.cpp.inc:4483] [ifid: 13] protocolDetected() [check: blacklisted]: [IEC60870] TCP 192.168.7.50:60662 -> 192.168.7.85:2404
01/Jun/2020 12:45:05 [LuaEngineNtop.cpp.inc:4483] [ifid: 13] protocolDetected() [check: tls_malicious_signature]: skipping flow with incomplete three way handshake
01/Jun/2020 12:45:05 [LuaEngineNtop.cpp.inc:4483] [ifid: 13] protocolDetected() [check: remote_to_remote]: [IEC60870] TCP 192.168.7.50:60662 -> 192.168.7.85:2404
01/Jun/2020 12:45:05 [LuaEngineNtop.cpp.inc:4483] [ifid: 13] protocolDetected() [check: tls_certificate_expired]: skipping flow with incomplete three way handshake
01/Jun/2020 12:45:05 [LuaEngineNtop.cpp.inc:4483] [ifid: 13] protocolDetected() [check: flow_risks]: [IEC60870] TCP 192.168.7.50:60662 -> 192.168.7.85:2404
01/Jun/2020 12:45:05 [LuaEngineNtop.cpp.inc:4483] [ifid: 13] protocolDetected()[END]: bitmap=0x10000 predominant=16 score=-1 flow.score=0


01/Jun/2020 12:45:40 [LuaEngineNtop.cpp.inc:4483] [ifid: 13] periodicUpdate()[START]: bitmap=0x10000 predominant=16
01/Jun/2020 12:45:40 [LuaEngineNtop.cpp.inc:4483] [ifid: 13] periodicUpdate() [check: not_purged]: [IEC60870] TCP 192.168.7.50:60662 -> 192.168.7.85:2404
01/Jun/2020 12:45:40 [LuaEngineNtop.cpp.inc:4483] [ifid: 13] periodicUpdate() [check: long_lived]: [IEC60870] TCP 192.168.7.50:60662 -> 192.168.7.85:2404
01/Jun/2020 12:45:40 [LuaEngineNtop.cpp.inc:4483] [ifid: 13] periodicUpdate() [check: elephant_flows]: [IEC60870] TCP 192.168.7.50:60662 -> 192.168.7.85:2404
01/Jun/2020 12:45:40 [LuaEngineNtop.cpp.inc:4483] [ifid: 13] periodicUpdate() [check: external_alert_check]: [IEC60870] TCP 192.168.7.50:60662 -> 192.168.7.85:2404
01/Jun/2020 12:45:40 [LuaEngineNtop.cpp.inc:4483] [ifid: 13] periodicUpdate()[END]: bitmap=0x10000 predominant=16 score=-1 flow.score=0
```

Hook protocolDetected is executed just once (one time for each user script which is registered to protocolDetected) and then I get periodic updates every 30 seconds.

Can you please give me additional details or steps to reproduce? Feel free to attach the user script as well.

**Comment by martinscheu** [comment]
Thank you.

With DHCP is use "sudo ipconfig set en0 DHCP" on my mac and it triggers twice. Might be a side effect? but with the IEC protocol it can not be something else, there I get the second trigger with payload nil. The script: (formating doesnt work..)

**Comment by martinscheu** [comment]
local user_scripts = require("user_scripts") 
local flow_consts = require("flow_consts")

local script = {
  -- Script category
  category = user_scripts.script_categories.security,

  -- This module is disabled by default
  default_enabled = true,

  -- See below
  hooks = {},

  -- Allow user script configuration from the GUI
  gui = {
    i18n_title = "IEC60870 in flow",
    i18n_description = "Detects IEC60870 in data flow",
  }
}

-- #################################################################

-- Defines an hook which is executed every time a protocol of a flow is detected

function script.hooks.protocolDetected(now)

 local protoID = flow.getnDPIAppProtoId()
  --DHCP     ID 16
  --IEC60870 ID 245
  if protoID == 245 then
    local payload = flow.getnDPIMatchPacket()

  -- debug info print the line to the console
    io.write("IEC 60870 protocol triggered")
    io.write("\n")
   
  if payload == nil then

      io.write("-empty payload")
      io.write("\n")
    
    else
     
     if payload["payload_len"] == 0 then
     
      io.write("payload_len = 0")
      io.write("\n")

     else

      local file = assert(io.open("/home/ics/payload", "w"))
     
      if file then
        io.write("write data to file")
        io.write("\n")
        tprint(payload)
     
        file:write(payload["payload"])
        file:write(",")
        file:close()
       
       else
          io.write("file does not exist")
          io.write("\n")
       end
      end
   end

**Comment by martinscheu** [comment]
can confirm with the pcap file it triggers only once:
<img width="969" alt="Screenshot 2020-06-02 at 12 01 30" src="https://user-images.githubusercontent.com/38549755/83507470-e32ccd00-a4c8-11ea-9c25-db890afb05b2.png">

**Comment by martinscheu** [comment]
DHCP triggers twice
<img width="871" alt="Screenshot 2020-06-02 at 12 09 42" src="https://user-images.githubusercontent.com/38549755/83508294-0146fd00-a4ca-11ea-8f05-72d5f0c5a830.png">

**Comment by simonemainardi** [comment]
This is normal behavior. Indeed, DHCP protocol is basically composed of 4-steps DORA (Discover-Offer-Request-ACK). The discover and request are sent in broadcast whereas offer and ACK are unicast. This actually determines ntopng to create two flows:

![image](https://user-images.githubusercontent.com/3397663/83641569-02515a80-a5ae-11ea-8b59-1ba9e5079c37.png)

and, consequently, you get the callback executed on each of the two flows. If you want to differentiate, you can use for example `flow.isUnicast()`, `flow.isClientUnicast()`, `flow.isServerUnicast()` in your user script and skip the part which you are not interested into.
