### ISSUE TITLE
Maximum Displayed String Length

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#4009]
Hello,

At Preferences - Misc - Web User Interface:
Maximum Displayed String Length : 128 (only).

How can we edit unlimited characters? Because I can not read full Info from clients.

**Comment by simonemainardi** [comment]
Setting unlimited here isn't a good idea as it could worsen the look of the UI. Please, show where you are not able to see full info, because it could be that you just need to click a drill-down to see the string in full.

**Comment by ghost** [comment]
Hello,

Thank you for your quickly response.

I use ntop package from pfsense.
At info tab only display 128 characters (maximum): ocsp(dot)digicert(dot)com/*$%$(&%)@*&%*#@^#*%)&@(#@
https://imgur.com/y9cDRT8

**Comment by simonemainardi** [comment]
do you mean the rightmost column of the image?

**Comment by ghost** [comment]
Yes sir,

If the address link is more 128 characters, I can not see detail of link.
https://imgur.com/XXuhh00

Example: https://imgur.com/HVkLwtQ 
In that example: the link is only display maximum 128 characters: 
vnso-zn-15-tf-mp3-s1-m-zmp3.zadn.vn/7f62af55b6125f4c0603/27793806106737670?authen=exp=1591094343~acl=/7f62af55b6125f4c0603/*~hma...

**Comment by simonemainardi** [comment]
It's normal not to have the full string shown there as it would break the table layout.

However, you can hover the mouse on the info to see the full string.

I've also coded a quick fix as sometimes the full info was not shown in the tooltip.

Now this is what you get

![image](https://user-images.githubusercontent.com/3397663/83437786-a74e2500-a440-11ea-8df0-368e23174352.png)
