### ISSUE TITLE
Ntopng start fails / too many arguments

### ISSUE THREAD

**Issue by dersch81** [ntop/ntopng#401]
I'm facing several weeks this problem by starting the ntopng service. 

/etc/init.d/ntopng start
- Starting ntopng  
  /etc/init.d/ntopng: Zeile 64: [: Zu viele Argumente.
  /etc/init.d/ntopng: Zeile 68: [: Zu viele Argumente.
  /etc/init.d/ntopng: Zeile 64: [: Zu viele Argumente.
  /etc/init.d/ntopng: Zeile 68: [: Zu viele Argumente.
  /etc/init.d/ntopng: Zeile 64: [: Zu viele Argumente.
  /etc/init.d/ntopng: Zeile 68: [: Zu viele Argumente.
  /etc/init.d/ntopng: Zeile 64: [: Zu viele Argumente.
  /etc/init.d/ntopng: Zeile 68: [: Zu viele Argumente.
  /etc/init.d/ntopng: Zeile 64: [: Zu viele Argumente.
  /etc/init.d/ntopng: Zeile 68: [: Zu viele Argumente.
  /etc/init.d/ntopng: Zeile 64: [: Zu viele Argumente.
  /etc/init.d/ntopng: Zeile 68: [: Zu viele Argumente.
- Unable to start ntopng

By restarting the server ntopng is alive, only manual restarting / starting shows that error. 

It is on Ubuntu 14.04.03 LTS

**Comment by lucaderi** [comment]
@dersch81 I think you forgot to specify the PID file in your script. Please check and it will work, Do not forget to star ntopng!

**Comment by dersch81** [comment]
@lucaderi i never modified the script. It is installed with the repo. The issue started after some upgrade of ntopng.

**Comment by lucaderi** [comment]
please attach the script and report the version of ntopng

**Comment by dersch81** [comment]
dpkg -l | grep ntopng
ii  ntopng                                                      2.2.160216-945                                  amd64        Web-based traffic monitoring.
ii  ntopng-data                                                 2.2.160216                                      all          Data files (geoip) for ntopng.

[ntopng.txt](https://github.com/ntop/ntopng/files/135862/ntopng.txt)

**Comment by lucaderi** [comment]
you need to send /etc/ntopng/ntopng.conf

**Comment by dersch81** [comment]
ok
[ntopng.conf.txt](https://github.com/ntop/ntopng/files/135873/ntopng.conf.txt)

**Comment by dersch81** [comment]
@lucaderi it works! 

sudo /etc/init.d/ntopng restart
- Stopping ntopng
  951
- Starting ntopng
  1041
  ...done.

thanks a lot for your commit!

**Comment by lucaderi** [comment]
@dersch81 please star ntopng on github
