### ISSUE TITLE
Avoid ignoring configuration warnings

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4011]
![Screen Shot 2020-06-01 at 15 30 28](https://user-images.githubusercontent.com/4493366/83413898-e0749e00-a41c-11ea-9394-91e2c422caa6.png)

When users have too many flows or hosts, a yellow/red badge id displayed as in the picture above. This is not enough for most people as they ignore it. The result is that ntopng performs badly. This can be fixed extending the value of -X/-x.

This ticket requires to show in all pages a large warning badge (e.g. similar to the one blow but in red or yellow)
![Screen Shot 2020-06-01 at 15 35 32](https://user-images.githubusercontent.com/4493366/83414330-96d88300-a41d-11ea-9ade-0b6045847e5a.png)

So that people cannot ignore it

See also #2959

**Comment by gabryon99** [comment]
<img width="800" alt="Screenshot 2020-07-14 at 10 20 32" src="https://user-images.githubusercontent.com/14114916/87520789-b94bf600-c683-11ea-86ff-22f9eda2c68d.png">
 An alert has been added to inform the user. When the flows are above the threshold the alert will disappear.
