### ISSUE TITLE
Generate an badge alert when GeoIP is not configured

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4012]
Due to changes in GeoIP (see https://github.com/ntop/ntopng/blob/dev/doc/README.geolocation.md), ntopng can operate without this information leading to incomplete reports.

It is requested to display a large badge similar to the one below but in yellow

![Screen Shot 2020-06-01 at 15 35 32](https://user-images.githubusercontent.com/4493366/83414664-2aaa4f00-a41e-11ea-9387-3bab4a825cc5.png)

Asking people to configure GeoIP.

**Comment by gabryon99** [comment]
Create a Stub function to create simple Bootstrap Toasts

**Comment by gabryon99** [comment]
In `menu_alert_notifications.lua` (under `scripts/lua/modules`) there is a function called `load_notifications()` to create the notifications to show when a page is loaded. See also `alert_notification.lua` to get further details

**Comment by gabryon99** [comment]
<img width="1792" alt="Screenshot 2020-07-08 at 12 02 40" src="https://user-images.githubusercontent.com/14114916/86905843-f445ab00-c112-11ea-9395-f2804b3bc111.png">

This is the expected outcome
