### ISSUE TITLE
POST http_prefix/?ifid=<val> redirects to /?ifid=<val> without prefix

### ISSUE THREAD

**Issue by andpp** [ntop/ntopng#4016]
Browser: **Google Chrome. Version 83.0.4103.61 (Official Build) (64-bit)**
Branch: **4.0-stable**
$ ntopng --version
**v.4.0.200518 [Community build]
GIT rev: 4.0-stable:8b73b34242a393e395a901c4bf54e5dff6d6dd0c:20200518**
ntopng built from latest update

Using wireshark I catched packet exchange between my browser and ntopng running on localhost. No proxy server used.

After pressing button for selecting interfaces I see these data sequence:

1. GET /sys/ntopng/lua/switch_system_status.lua?system_interface=0&csrf=713b01a0d2b8a11d4090f87f5401f HTTP/1.1\r\n
2. HTTP/1.1 200 OK\r\n
        [Expert Info (Chat/Sequence): HTTP/1.1 200 OK\r\n]
        Response Version: HTTP/1.1
        Status Code: 200
        [Status Code Description: OK]
        Response Phrase: OK
    Cache-Control: max-age=0, no-cache, no-store\r\n
    Server: ntopng 4.0.200518 [Debian buster/sid [x86_64][Ubuntu 18.04.4 LTS]]\r\n
    Pragma: no-cache\r\n
    X-Frame-Options: DENY\r\n
    X-Content-Type-Options: nosniff\r\n
    Content-Type: application/json\r\n
    Last-Modified: Wed, 06 June 2020 18:11:00 GMT\r\n
    Set-Cookie: session=; max-age=3600; path=/;  HttpOnly; SameSite=lax\r\n
    \r\n
    [HTTP response 1/1]
    [Time since request: 0.074563613 seconds]
    [Request in frame: 480]
    [Request URI: http://127.0.0.1:3000/sys/ntopng/lua/switch_system_status.lua?system_interface=0&csrf=713b01a0d2b8a11d4090f87f5401f]
    File Data: 16 bytes
JavaScript Object Notation: application/json
3. POST /sys/ntopng/?ifid=1 HTTP/1.1\r\n
4. HTTP/1.1 302 Found\r\n
        [Expert Info (Chat/Sequence): HTTP/1.1 302 Found\r\n]
        Response Version: HTTP/1.1
        Status Code: 302
        [Status Code Description: Found]
        Response Phrase: Found
    **_Location: /?ifid=1\r\n_**
    \r\n
    [HTTP response 1/1]
    [Time since request: 0.001805640 seconds]
    [Request in frame: 508]
    [Request URI: http://127.0.0.1:3000/sys/ntopng/?ifid=1]
    File Data: 130 bytes
    Data (130 bytes)
        Data: 3c68746d6c3e0a3c686561643e0a3c7469746c653e4d6f76...
        [Length: 130]

Full string for redirection:
```
HTTP/1.1 302 Found
Location: /?ifid=1

<html>
<head>
<title>Moved</title>
</head>
<body>
<h1>Moved</h1>
<p>This page has moved to <a href="/">/</a>.</p>
</body>
</html>
```

5. **GET /?ifid=1 HTTP/1.1\r\n**

Using GET instead of POST returns correct redirection.

**Comment by andpp** [comment]
Fixing redirection to System

```
diff --git a/scripts/lua/inc/footer.lua b/scripts/lua/inc/footer.lua
index 9609689e8..b4be457b7 100644
--- a/scripts/lua/inc/footer.lua
+++ b/scripts/lua/inc/footer.lua
@@ -115,7 +115,7 @@ print([[
                         csrf: "]].. ntop.getRandomCSRFValue() ..[["
                  }, function(data) {
 
-                        if (data.success && $form == null) location.href = '/';
+                        if (data.success && $form == null) location.href =  http_prefix + '/';
                         if (data.success && $form != null) $form.submit();
                         if (!data.success) {
                                console.error("An error has occurred!");

```

**Comment by andpp** [comment]
While there is no more error with incorrect redirection, I can't switch to another interface :( . So POST must be used, but processing POST requests requires fixing redirection. If someone could point me where POST request are processed, I could check if I can find a root cause and fix the issue.

**Comment by andpp** [comment]
It is quite interesting. Investigating where we could lose uri I stepped with debugging through mongoose.c

```
(gdb) cond 1 uri_len < 10
(gdb) c
Continuing.
[Switching to Thread 0x7fb4f6ffd700 (LWP 18750)]

Thread 4 "ntopng" hit Breakpoint 1, handle_request (conn=0x7fb4f0000b20)
    at src/../third-party/mongoose/mongoose.c:4414
4414	  url_decode(ri->uri, uri_len, (char *) ri->uri, uri_len + 1, 0);
(gdb) p ri->uri
$5 = 0x7fb4f0001025 "/ntopng/"
(gdb) n
4415	  remove_double_dots_and_double_slashes((char *) ri->uri);
(gdb) p ri->uri
$6 = 0x7fb4f0001025 "/ntopng/"
(gdb) n
4418	  if((strncmp(conn->request_info.uri, "/plugins-src", 12) == 0)  /* Serve lua files */
(gdb) n
4425	  convert_uri_to_file_name(conn, path, sizeof(path), &file);
(gdb) p ri->uri
$7 = 0x7fb4f0001025 "/ntopng/"
(gdb) p conn
$8 = (mg_connection *) 0x7fb4f0000b20
(gdb) p ri->uri
$9 = 0x7fb4f0001025 "/ntopng/"
(gdb) n
4427					get_remote_ip(conn), ri->uri);
(gdb) p ri->uri
$10 = 0x7fb4f000102c "/"
(gdb) 

```

**Comment by andpp** [comment]
It seems that when we do **POST /ntopng/?ifid=1 HTTP/1.1\r\n**
**convert_uri_to_file_name** in **mongoose.c:1925** removes http_prefix from URL
Later it uses uri without http_prefix in LuaEngine.cpp:12425  **LuaEngine::handle_script_request** to create redirection in LuaEngine.cpp:12529   **build_redirect(request_info->uri, request_info->query_string, buf, sizeof(buf));** with incorrect request_info->uri ("/").

**Comment by andpp** [comment]
After some debugging I found a fix that works  for me:

```
diff --git a/scripts/lua/inc/footer.lua b/scripts/lua/inc/footer.lua
index 9609689e8..b4be457b7 100644
--- a/scripts/lua/inc/footer.lua
+++ b/scripts/lua/inc/footer.lua
@@ -115,7 +115,7 @@ print([[
                         csrf: "]].. ntop.getRandomCSRFValue() ..[["
                  }, function(data) {
 
-                        if (data.success && $form == null) location.href = '/';
+                        if (data.success && $form == null) location.href =  http_prefix + '/';
                         if (data.success && $form != null) $form.submit();
                         if (!data.success) {
                                console.error("An error has occurred!");
diff --git a/scripts/lua/inc/menu.lua b/scripts/lua/inc/menu.lua
index 91a9e04ea..98f10c2c3 100644
--- a/scripts/lua/inc/menu.lua
+++ b/scripts/lua/inc/menu.lua
@@ -765,7 +765,12 @@ for round = 1, 2 do
             print("<a class=\"dropdown-item active\" href=\"#\">")
          else
             -- NOTE: the actual interface switching is performed in C in LuaEngine::handle_script_request
-            local action_url = ntop.getHttpPrefix() .. '/' .. url_query
+            local action_url = ""
+            if(is_system_interface) then
+               action_url = ntop.getHttpPrefix() .. '/' .. url_query
+            else
+               action_url = url_query
+            end
 
             print[[<form id="switch_interface_form_]] print(tostring(k)) print([[" method="post" action="]].. action_url ..[[]]) print[[">]]
             print[[<input name="switch_interface" type="hidden" value="1" />]]
diff --git a/src/LuaEngine.cpp b/src/LuaEngine.cpp
index 241539c80..17b5a1913 100644
--- a/src/LuaEngine.cpp
+++ b/src/LuaEngine.cpp
@@ -12525,8 +12525,16 @@ int LuaEngine::handle_script_request(struct mg_connection *conn,
 
   if(send_redirect) {
     char buf[512];
+    char uri[512];
+    char * http_prefix = ntop->getPrefs()->get_http_prefix();
+    int http_prefix_len = strlen(ntop->getPrefs()->get_http_prefix());
 
-    build_redirect(request_info->uri, request_info->query_string, buf, sizeof(buf));
+    if (http_prefix_len > 0) {
+      snprintf(uri, 512, "%s%s", http_prefix, request_info->uri);
+      build_redirect(uri, request_info->query_string, buf, sizeof(buf));
+    } else {
+      build_redirect(request_info->uri, request_info->query_string, buf, sizeof(buf));
+    }
 
     /* Redirect the page and terminate this request */
     mg_printf(conn, "%s", buf);

```

**Comment by simonemainardi** [comment]
can you submit the patch as a pull request so we can test it?
