### ISSUE TITLE
Updated "ja.lua" 

### ISSUE THREAD

**Issue by Yoshihiro-jp** [ntop/ntopng#4017]
Hi,

I modified some words and sentences  in "ja.lua".
PATH: /usr/share/ntopng/scripts/locales/ja.lua

Please update it.

regards,
Yoshihiro
[jp.zip](https://github.com/ntop/ntopng/files/4727574/jp.zip)

**Comment by simonemainardi** [comment]
Thanks for your contribution. Please, submit the patch as a pull request and we will integrate it.
