### ISSUE TITLE
Integrate ntopng with Suricata

### ISSUE THREAD

**Issue by Yuvahai** [ntop/ntopng#4019]
ntopng and suricata are integrated, and ntopng captures packets for suricata analysis, to avoid that two capture modules simultaneously capture packets on the same network port, causing packet capture interference and affecting packet capture efficiency

**Comment by cardigliano** [comment]
@Yuvahai you can ingest flows from Suricata if you want to process packets both in ntopng and suricata as explained at https://www.ntop.org/guides/ntopng/advanced_features/suricata.html#flows-export
