### ISSUE TITLE
Develop plugin for detecting security violations

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4021]
Traditionally in every network there are a set of specified servers to be used for selected services. In particular for DNS and SMTP only the specified servers can be contacted. Any attempt (just to make an example) to use a MX other than the one configured is a misconfiguration or a security violation. 

In essence it is requested to create a plugin where for basic services, a use can specify the network configuration and threat all violations to the above policies as errors/alerts.

This ticket is somehow linked to #4003

**Comment by martinscheu** [comment]
For industrial networks I would like to add time sync service, NTP

**Comment by lucaderi** [comment]
> For industrial networks I would like to add time sync service, NTP

NTP implemented by https://github.com/ntop/ntopng/commit/4565f8af048e6c262cc6489b2f0cdfb949f21b1f

![Screen Shot 2020-10-10 at 10 53 15](https://user-images.githubusercontent.com/4493366/95650951-20444400-0ae7-11eb-8bde-d7e9858eeee5.png)
