### ISSUE TITLE
Missing dep in README.compilation for Fedora

### ISSUE THREAD

**Issue by jbriales** [ntop/ntopng#4023]
In Fedora 30,
following instructions in README.compilation I still hit this:
```
gcc -std=gnu99 -O2 -Wall -Wextra -DLUA_COMPAT_5_2 -DLUA_USE_LINUX    -c -o lua.o lua.c
lua.c:82:10: fatal error: readline/readline.h: No such file or directory
   82 | #include <readline/readline.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
which I fixed with `sudo dnf install readline-devel`.

**Comment by simonemainardi** [comment]
Package was already listed at:

https://github.com/ntop/ntopng/blob/80e5400c36c5e95d1058e8e5b68fc029564f553e/doc/README.compilation#L55

**Comment by jbriales** [comment]
I'm in Fedora 30, and I needed there. The package is NOT listed in https://github.com/ntop/ntopng/blob/80e5400c36c5e95d1058e8e5b68fc029564f553e/doc/README.compilation#L50
