### ISSUE TITLE
Trigger blackhole in case of DDOS

### ISSUE THREAD

**Issue by operations999** [ntop/ntopng#4024]
Hello,
Is it possible to trigger blackhole in case of DDOS?
Thanks

**Comment by simonemainardi** [comment]
please explain your use case, environment and what you would like to achieve

**Comment by operations999** [comment]
Hello,
In a situation where 5 locations flow is sent to Nprob > Ntopng.  There are option to trigger alerts if there is syn or any kind of DDOS. 
But is there plugin/script to trigger blackhole using community to null route the ip if there is ddos?
Thanks

**Comment by simonemainardi** [comment]
I think the easiest way is to write a plugin to 'trigger blackhole' when a certain condition is met.

How would you 'trigger blackhole'? does a post to a certain HTTPS endpoint suffice? Do you need to execute a command?

If you don't explain with details we won't be able to help.

**Comment by operations999** [comment]
We usually login to router and null router but it is manual job.
I was wondering if there is any plugin available we can ntegrate with cisco/juniper to automate the null route.
Thanks

**Comment by simonemainardi** [comment]
There is no plugin but we can (help you to) write one.

Do you know if cisco/juniper support ways other than direct login to set the blackhole? How do you do the direct login? Maybe it is possible to implement that as well.

Give as many details as possible, include examples as well.

**Comment by simonemainardi** [comment]
No feedback received. Closing. Reopen with the necessary information if necessary.

**Comment by MDSharma** [comment]
Please consider re-opening this one..  I think it can be a very worthy addition to ntopng and will compliment the features of nScrub.

In the example illustrated here:

netflow v9 emitters -> nProbe -> ntopng
---------------------------------> GoBGP running on the ntopng host
---------------------------------> GoBGP set to peer with multiple routers to announce blackholes.
---------------------------------> When ntopng detects nefarious traffic, it puts a call in to the local GoBGP instance to inject a blackhole route. This can be withdrawn when the attack stops.

FastnetMon uses this logic to trigger the BGP blackhole system as well.
