### ISSUE TITLE
Percent sign in password leads to lock-out

### ISSUE THREAD

**Issue by qdrop17** [ntop/ntopng#4031]
Hi everyone.

By random I generated a password that included a percent sign (%) and set that as the admin password.

After logging out, I'm not able to login again - being 101% sure I copy and pasted the password properly.

Resetting the password and removing the percent sign solved that issue.

For the sake of usability I suggest to add a validation to the password-form to check for ISO 8859-1 (latin1) characters.

I'm using version 4.1.200609 (10467) on a generic Ubuntu 18.04.4 LTS.

Thank you very much for considering.
ntopng is pretty damn awesome software nervertheless :-).

Best

**Comment by lucaderi** [comment]
I have set the admin password at luca2020% and everything works. Can you please report one password that causes the system to lock?

**Comment by qdrop17** [comment]
You can try it with **w%832oOgC6wt**. This ain't working on my instance.

**Comment by simonemainardi** [comment]
Thanks for reporting. HTML unescaping was performed on password changes, thus causing the % sign to be interpreted as the escape character. Issue is fixed. A new build is in progress. Wait a couple of hours and give it a try.
