### ISSUE TITLE
Ntop.cpp:201 Error: unable to open lock file

### ISSUE THREAD

**Issue by AWHubGit** [ntop/ntopng#4034]
Using ntopng v.4.0.200414 installed by brew on macOS 10.15.5 with commands on cli
ntopng -i en1
ntopng -s -i en1
it throws error "[Ntop.cpp:201] ERROR: Unable to open lock file: No such file or directory".
Also with sudo.
`which tcpdump` --version
tcpdump version tcpdump version 4.9.3 -- Apple version 90.100.1
libpcap version 1.9.1
LibreSSL 2.8.3
redis-cli --version 6.0.5

How to launch ngtopng on macOS?

**Comment by simonemainardi** [comment]
try and add option `--dont-change-user`

**Comment by AWHubGit** [comment]
I did it already. See above. According to "man ntopng" argument "-s" same as "--dont-change-user" debug only.
What is the lock file needed? Is it in ntop.cpp:201?

**Comment by simonemainardi** [comment]
you need to run with `sudo`:

```
sudo ntopng -s -i en1
```

**Comment by AWHubGit** [comment]
I did/tried already. See my first post.
Trying again with "sudo ntopng -s -i en1" same result/error:
"[Ntop.cpp:201] ERROR: Unable to open lock file: No such file or directory"

**Comment by simonemainardi** [comment]
please, use our official OS X package and report: https://packages.ntop.org/
Installation guide is at: https://www.ntop.org/guides/ntopng/what_is_ntopng.html#installing-on-macos

**Comment by lucaderi** [comment]
Please use the ntop package as Simone said. We have no control on the brew package

**Comment by samuelesabella** [comment]
I faced the same problem with stable version 4.0: `ERROR: Unable to open lock file: No such file or directory`
The problem was solved after manually creating the directory: /var/lib/ntopng
