### ISSUE TITLE
No syslog messages

### ISSUE THREAD

**Issue by CyberbreinAirw0lf** [ntop/ntopng#4035]
Team,

The following is added to the config-file (see also attached config-file:
-i=syslog://*:514@udp

After several updates of the dev-channel, this is still not working - no messages.

See also attached screenshot:
- client is host producer
- sent log-messages to udp/514 @
- just added the host producers => no difference

Kind regards - Will

[ntopng-2020may27.zip](https://github.com/ntop/ntopng/files/4761105/ntopng-2020may27.zip)

![log-producer-ntopng](https://user-images.githubusercontent.com/64280991/84317078-7ff80600-ab6c-11ea-84eb-121fb694067b.png)

**Comment by cardigliano** [comment]
@NogNeetMachinaal I think it's easier to schedule a joint session to debug this, the configuration looks good

**Comment by CyberbreinAirw0lf** [comment]
Sure - what would be a good time? Tomorrowmorning; say 11 AM?

**Comment by cardigliano** [comment]
Ok for me

**Comment by NogNeetMachinaal** [comment]
Team,

 �

Assuming this troubleshoot sessions is still happening:

Please use the link <https://teams.microsoft.com/l/meetup-join/19%3ameeting_MmUwYmE4ZWMtZDBlYy00Nzk1LWE3MTAtNTcxMThlMGU4MTk5%40thread.v2/0?context=%7b%22Tid%22%3a%22bf3ea48b-2f4b-41c4-8f08-5941fc1b23ce%22%2c%22Oid%22%3a%22410ab490-053b-468b-a2c9-f15754761289%22%7d>  below.

 �

 �

Thank you - Will

 �

 <https://teams.microsoft.com/l/meetup-join/19%3ameeting_MmUwYmE4ZWMtZDBlYy00Nzk1LWE3MTAtNTcxMThlMGU4MTk5%40thread.v2/0?context=%7b%22Tid%22%3a%22bf3ea48b-2f4b-41c4-8f08-5941fc1b23ce%22%2c%22Oid%22%3a%22410ab490-053b-468b-a2c9-f15754761289%22%7d> Join Microsoft Teams Meeting

  

 �

 �

**Comment by cardigliano** [comment]
@NogNeetMachinaal troubleshoot will happen (feel free to use direct mails for scheduling calls to avoid sending links publicly)

**Comment by CyberbreinAirw0lf** [comment]
> 
> 
> @NogNeetMachinaal troubleshoot will happen (feel free to use direct mails for scheduling calls to avoid sending links publicly)

Just removed the previous message with the links.

**Comment by cardigliano** [comment]
Fixed
