### ISSUE TITLE
 TCP-analysis

### ISSUE THREAD

**Issue by CyberbreinAirw0lf** [ntop/ntopng#4036]
Team,

See also attached image with TCP flag distribution:
In a healthy situation, I would expect SYN, SYN/ACK and FIN/ACK more-or-less equal.
If not equal, I would expect: RST < FIN/ACK < SYN/ACK < SYN.

The attached image shows the opposite:

    more FIN/ACK then SYN/ACK => more sessions ending then started?
    more SYN/ACK then SYN => more completed sessions then initiated?

Where is this described in the manual?
If not described: am I overlooking something? What would that be?

How do I make these TCP flag distributions part of a report?

Kind regards - Will

![TCP-analysis](https://user-images.githubusercontent.com/64280991/84317904-ddd91d80-ab6d-11ea-8c81-f199a604611f.png)

**Comment by simonemainardi** [comment]
> In a healthy situation, I would expect SYN, SYN/ACK and FIN/ACK more-or-less equal.

Correct.

> If not equal, I would expect: RST < FIN/ACK < SYN/ACK < SYN.

Correct - in an healthy situation. Certain scans with spoofed tcp flags can make the above inequality false.

> more FIN/ACK then SYN/ACK => more sessions ending then started?

Likely, you've started ntopng when many sessions were already open. So ntopng didn't see the SYN / SYNACK part of the tcp three way handshake because it wasn't started at that time.

> more SYN/ACK then SYN => more completed sessions then initiated?

Chances of having this are too low. I would not expect to see this in practice.

**Comment by simonemainardi** [comment]
Another reason why you can get an higher number of FINACK is when the client sends a ACK+FIN, that is, it acknowledges previous data (ACK) and simultaneously requests for session termination (FIN). Then, the server responds with ACK+FIN, and so the counter of FINACK can be greater as the FINACK is increased twice for each flow with the property above.

**Comment by CyberbreinAirw0lf** [comment]
One open question related to this topic:
How do I make these TCP flag distributions part of a report?

**Comment by simonemainardi** [comment]
- https://github.com/ntop/ntopng/issues/4042
- https://github.com/ntop/ntopng/issues/4041
