### ISSUE TITLE
Support custom ports for HTTP/HTTPS active monitoring

### ISSUE THREAD

**Issue by CyberbreinAirw0lf** [ntop/ntopng#4037]
Team,

See also attached screenshot (I also checked the manual):
It looks like http and https monitoring with a custom TCP port is not supported?
While the entered host is marked "green" (i.e. ok)?

Thank you,
- Will

![active-monitoring-custom-tcp-port](https://user-images.githubusercontent.com/64280991/84319069-b71be680-ab6f-11ea-8ec5-8c8b2f8eb9a5.png)

**Comment by lucaderi** [comment]
This ticket depends on #4677

**Comment by lucaderi** [comment]
Verified as fixed (IPv4 only)
