### ISSUE TITLE
SNMP and Arista

### ISSUE THREAD

**Issue by Hagshur** [ntop/ntopng#4038]
hi all 
on our ntop  we are using to monitor our datacenter lines, (wan+lan) 
our backbone is Arista based.
stop by default is recognising Cisco mib but not the Arista -when I run snmp query it doesn't get all information needed 
someone know how to "compile" the MIB to ntop ?

**Comment by simonemainardi** [comment]
I think we may have to adjust certain OIDs to make sure they work with vendor Arista. Do you know which parts are missing?

It would be great if you could give us access to one of your Arista so that we can see and adjust directly.

**Comment by lucaderi** [comment]
@Hagshur What is the Arista MIB missing?

**Comment by lucaderi** [comment]
@Hagshur Can you please assist to reproduce the issue you reported?

**Comment by lucaderi** [comment]
Closed for inactivity. Will reopen if input will be provided
