### ISSUE TITLE
bridging takes too long

### ISSUE THREAD

**Issue by Cyndz136** [ntop/ntopng#404]
Hi, i was able to bridge again the two network interfaces but then after i've issued the command it takes too long to finish is that normal?

ccahilig@NTOP:~$ ntopng -i bridge:em1,wlan0
18/Feb/2016 17:09:02 [Ntop.cpp:933] Setting local networks to 127.0.0.0/8
18/Feb/2016 17:09:02 [Redis.cpp:106] Successfully connected to redis 127.0.0.1:6379@0
18/Feb/2016 17:09:02 [NtopPro.cpp:119] [LICENSE] Reading license from /etc/ntopng.license
18/Feb/2016 17:09:02 [NtopPro.cpp:153] WARNING: [LICENSE] Your license will expire on Sat Mar 12 04:55:41 2016
18/Feb/2016 17:09:02 [PacketBridge.cpp:96] ERROR: Unable to open interface em1
18/Feb/2016 17:09:02 [Ntop.cpp:1152] Registered interface bridge:em1,wlan0 [id: 5]
18/Feb/2016 17:09:02 [Ntop.cpp:1165] Registered interface view bridge:em1,wlan0 [id: 5]
18/Feb/2016 17:09:02 [Utils.cpp:286] Privileges are not dropped as we're not superuser
18/Feb/2016 17:09:02 [main.cpp:240] PID stored in file /var/tmp/ntopng.pid
18/Feb/2016 17:09:02 [HTTPserver.cpp:465] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
18/Feb/2016 17:09:02 [HTTPserver.cpp:482] -->3000<--
18/Feb/2016 17:09:02 [HTTPserver.cpp:510] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
18/Feb/2016 17:09:02 [HTTPserver.cpp:513] HTTP server listening on port 3000
18/Feb/2016 17:09:02 [main.cpp:290] Working directory: /var/tmp/ntopng
18/Feb/2016 17:09:02 [main.cpp:292] Scripts/HTML pages directory: /usr/share/ntopng
18/Feb/2016 17:09:02 [Ntop.cpp:260] Welcome to ntopng x86_64 v.2.2.160216 - (C) 1998-15 ntop.org
18/Feb/2016 17:09:02 [Ntop.cpp:265] Built on Ubuntu 14.04.3 LTS
18/Feb/2016 17:09:02 [PeriodicActivities.cpp:53] Started periodic activities loop...
18/Feb/2016 17:09:02 [RuntimePrefs.cpp:32] Dumping alerts into syslog
18/Feb/2016 17:09:02 [NtopPro.cpp:233] [LICENSE] ntopng systemId: C1344D9E9206A1D8
18/Feb/2016 17:09:02 [NtopPro.cpp:238] [LICENSE] ntopng is starting in demo mode
18/Feb/2016 17:09:02 [Ntop.cpp:516] Adding 10.241.5.64/26 as IPv4 local network for bridge:em1,wlan0
18/Feb/2016 17:09:02 [Ntop.cpp:516] Adding 10.241.5.128/25 as IPv4 local network for bridge:em1,wlan0
18/Feb/2016 17:09:02 [Ntop.cpp:546] Adding fe80::f21f:afff:fe31:479c/64 as IPv6 local network for bridge:em1,wlan0
18/Feb/2016 17:09:02 [Ntop.cpp:546] Adding fe80::a64e:31ff:fe0f:c24/64 as IPv6 local network for bridge:em1,wlan0
18/Feb/2016 17:09:02 [NetworkInterface.cpp:1426] Started packet polling on interface bridge:em1,wlan0 [id: 5]...
18/Feb/2016 17:09:03 [PcapInterface.cpp:196] Terminated packet polling for bridge:em1,wlan0
**
**IT STOPPED HERE and when i try to close the terminal it says that Closing this might kill the process so i didn't closed it i'm still waiting to finish**ed.**

em1 is my LAN interface
wlan0 is my Wireless Interface

**Comment by lucaderi** [comment]
Please read the log and listen to our replies.
1. You need to be root
18/Feb/2016 17:09:02 [PacketBridge.cpp:96] ERROR: Unable to open interface em1
18/Feb/2016 17:09:02 [Ntop.cpp:1152] Registered interface bridge:em1,wlan0 [id: 5]
18/Feb/2016 17:09:02 [Ntop.cpp:1165] Registered interface view bridge:em1,wlan0 [id: 5]
18/Feb/2016 17:09:02 [Utils.cpp:286] Privileges are not dropped as we're not superuser
1. I have advises NOT to bridge a wifi with an ethernet because depending on the driver, in some systems it is not possible to inject packets on a wifi interface

**Comment by Cyndz136** [comment]
then how do you suggest i do all this because i've been going in circles with these. one day i was able to bridge then the next day the bridge is gone. when i try to bridge again not possible i tried the link given to me on killing a port it didn't work.
