### ISSUE TITLE
Invalid IP address validation in Active Monitoring

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4040]
![Screen Shot 2020-06-14 at 12 13 07](https://user-images.githubusercontent.com/4493366/84590629-8cb07e80-ae38-11ea-867c-fe1929772c60.png)

**Comment by gabryon99** [comment]
We need to add a regex to validate the host input depending on the selected Measurement

**Comment by gabryon99** [comment]
We have created a new global JavaScript variable holding some regexes we use (such as ipv4, ipv6, ...). When a new measurement is selected a new function called `get_measurement_regex` sets the right pattern for the input box.

**Comment by simonemainardi** [comment]
the following functions MUST use the new REGEXP

https://github.com/ntop/ntopng/blob/b96e6dfba81bde7589bae0ab58d8f477ac68e1a0/httpdocs/js/ntopng_utils.js#L12

https://github.com/ntop/ntopng/blob/b96e6dfba81bde7589bae0ab58d8f477ac68e1a0/httpdocs/js/ntopng_utils.js#L20

move the mac regex the the REGEXP

https://github.com/ntop/ntopng/blob/b96e6dfba81bde7589bae0ab58d8f477ac68e1a0/httpdocs/js/ntopng_utils.js#L32

**Comment by gabryon99** [comment]
See: https://github.com/ntop/ntopng/commit/c2c763c2c1353057e9613d7cba3976b59a29b053#diff-587b20c94f784ad1cd0d6242bdf300a5R13

**Comment by simonemainardi** [comment]
good to go
