### ISSUE TITLE
Unify tables add/search/dropdown look

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4043]
This is the expected layout
![image](https://user-images.githubusercontent.com/3397663/84632003-95fc2280-aeee-11ea-8221-c923a0b4fb79.png)

These pages need to be adjusted accordingly

![image](https://user-images.githubusercontent.com/3397663/84631610-f9d21b80-aeed-11ea-850b-404397b62cb6.png)

![image](https://user-images.githubusercontent.com/3397663/84631689-1706ea00-aeee-11ea-8b09-1abade095885.png)

![image](https://user-images.githubusercontent.com/3397663/84631756-34d44f00-aeee-11ea-9f71-9e67517e5a1f.png)

![image](https://user-images.githubusercontent.com/3397663/84631777-3c93f380-aeee-11ea-8559-7459531b68f0.png)

![image](https://user-images.githubusercontent.com/3397663/84631815-4c133c80-aeee-11ea-974c-71d475452905.png)

![image](https://user-images.githubusercontent.com/3397663/84631898-7107af80-aeee-11ea-83d5-3238cb6a7179.png)

![image](https://user-images.githubusercontent.com/3397663/84631929-79f88100-aeee-11ea-8d9c-64602333cecd.png)

**Comment by gabryon99** [comment]
The following pages now are conforming with the new SNMP Table format:

- Recipient Endpoint List
- Notification Endpoint List
- Widgets List
- Datasource List
- Active Monitoring

The other pages require integration with the new DataTable. See the commit: https://github.com/ntop/ntopng/commit/91507212f02795990bb1680f26fbcc757424816b

**Comment by simonemainardi** [comment]
without doing the integration with the new DataTable, please adjusts also the other pages simply by putting the plus sign next to the search box, and the dropdowns on the left.

**Comment by simonemainardi** [comment]
after internal review, we have decided to keep the look of old datatables unchanged. Those will be replaced with new datatables.
