### ISSUE TITLE
SNMP add backup/restore buttons

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4044]
Snmp implements functions `snmp_config.backup()` and `snmp_config.restore()`.

It is requested to add buttons in the GUI which perform the operations above.

Buttons must be added bottom-left in (move also the delete button to the left)

![image](https://user-images.githubusercontent.com/3397663/84639122-3a369700-aef8-11ea-9946-2380bfde601d.png)

as in 

![image](https://user-images.githubusercontent.com/3397663/84639153-46baef80-aef8-11ea-8947-2176e7a78d64.png)

**Comment by gabryon99** [comment]
<img width="940" alt="Screenshot 2020-06-16 at 09 35 07" src="https://user-images.githubusercontent.com/14114916/84745302-ac6cb180-afb4-11ea-8d50-6da3ee69119e.png">

The buttons are now implemented.
