### ISSUE TITLE
Mobile version not usable

### ISSUE THREAD

**Issue by daxrob** [ntop/ntopng#4047]
Hi,

I tried to reach the ntopng web gui with an iphone using chrome. 
The web interface is not usable as you can see int portrait only the left menu is visible. On landscape the above portion of the interface hide all the rest.
Is it possible to correct/adjust the user interface for smartphone?
![C81069F6-F230-4A7F-AFFA-75DEDB49AF5A](https://user-images.githubusercontent.com/66008204/84685372-7854aa80-af3a-11ea-8fc5-345f2f068684.png)
![04239997-7945-48A0-9A53-0E88AB575932](https://user-images.githubusercontent.com/66008204/84685381-7be83180-af3a-11ea-840a-031fe2ba92a5.png)
![DB0921DF-B48B-406A-81C5-971F3A00A7C2](https://user-images.githubusercontent.com/66008204/84685411-89052080-af3a-11ea-8597-3a910d94d542.png)

Thanks

**Comment by StewAlexander-com** [comment]
I agree, I often need this while out and about looking at our network equipment, but I can't read it from my phone

**Comment by gabryon99** [comment]
We have improved the mobile UI. Now there is a hamburger button to open the sidebar. The mobile sidebar contains all the badges shown in the navbar and the network statistics (such as download/upload rate).

Below there are some images that show the fixed mobile UI:

[_About Page_]
<img width="355" alt="Screenshot 2020-08-10 at 12 25 06" src="https://user-images.githubusercontent.com/14114916/89773601-896a0400-db04-11ea-90f5-88003d438837.png">

[_About Page with opened Sidebar_]
<img width="355" alt="Screenshot 2020-08-10 at 12 26 02" src="https://user-images.githubusercontent.com/14114916/89773665-a9012c80-db04-11ea-8f61-eaaccde4b90c.png">

The user can close the sidebar with the `X` button near the dropdown to select another interface, or it can click everywhere outside the sidebar.

[_About Page with opened Sidebar and expanded Submenu_]
<img width="355" alt="Screenshot 2020-08-10 at 12 28 04" src="https://user-images.githubusercontent.com/14114916/89773827-f2517c00-db04-11ea-8dc0-009671eddca6.png">

**Comment by lucaderi** [comment]
Looks good to me. Some pages are a bit too small for small displays but now the system is usable on modern phones and tablets
