### ISSUE TITLE
rest/v1/get/interface/address.lua returns empty addresses array

### ISSUE THREAD

**Issue by TimotheusBachinger** [ntop/ntopng#4048]
In case we execute this REST call (with a valid ifid), we receive an empty addresses array:
![image](https://user-images.githubusercontent.com/57113191/84744135-213eec00-afb3-11ea-8099-9d509678bdf9.png)

Is this the desired behavior?

**Comment by cardigliano** [comment]
@TimotheusBachinger this is working for me, do you have an IP address configured in ifconfig on the interface you are providing with ifid?

**Comment by TimotheusBachinger** [comment]
@cardigliano I was discussing the topic with one of our consultants and I'll guess I misunderstood the concept. As the ifid was - I assume - a ZMQ interface, we do not have an IP address configured there:
![image](https://user-images.githubusercontent.com/57113191/84867879-1ef49480-b07c-11ea-9dd4-32bb4846109d.png)
So we can close this ticket.

**Comment by cardigliano** [comment]
Ok thank you
