### ISSUE TITLE
rest/v1/get/host/active.lua: "attempt to concatenate a function value (local 'name')"

### ISSUE THREAD

**Issue by TimotheusBachinger** [ntop/ntopng#4049]
Hi ntop Team,

If we query rest/v1/get/host/active.lua with a valid ifid, we receive this error:

`HTTP/1.1 302 Found

Set-Cookie: session=xxxx; path=/; HttpOnly; SameSite=lax

Location: /lua/http_status_code.lua?message=internal_error&referer=ntop4.xxx.xxxx.com%3A3000%2Flua%2Frest%2Fv1%2Fget%2Fhost%2Factive.lua%3Fifid%3D2&error_message=%2Fusr%2Fshare%2Fntopng%2Fscripts%2Flua%2Frest%2Fv1%2Fget%2Fhost%2Factive.lua%3A231%3A%20attempt%20to%20concatenate%20a%20function%20value%20%28local%20%27name%27%29

/usr/share/ntopng/scripts/lua/rest/v1/get/host/active.lua:231: attempt to concatenate a function value (local 'name')`

**Comment by cardigliano** [comment]
I pushed a fix for this, available with the next build

**Comment by TimotheusBachinger** [comment]
Thanks a lot for the quick fix!
