### ISSUE TITLE
Issue on logs after morning update

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#4051]
17/Jun/2020 09:26:55 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]
17/Jun/2020 09:26:55 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]
17/Jun/2020 09:26:50 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]
17/Jun/2020 09:26:50 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]
17/Jun/2020 09:26:45 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]
17/Jun/2020 09:26:45 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]
17/Jun/2020 09:26:40 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]
17/Jun/2020 09:26:40 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]
17/Jun/2020 09:26:35 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]
17/Jun/2020 09:26:35 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]

**Comment by zimbawe998** [comment]
The problem persist since yesterday morning update.
18/Jun/2020 15:45:05 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]
18/Jun/2020 15:45:05 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]
18/Jun/2020 15:45:00 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]
18/Jun/2020 15:45:00 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]
18/Jun/2020 15:44:55 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]
18/Jun/2020 15:44:55 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]
18/Jun/2020 15:44:50 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]

**Comment by zimbawe998** [comment]
after the latest update 15 miutes ago, the problem persist.
18/Jun/2020 16:22:25 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]
18/Jun/2020 16:22:20 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]
18/Jun/2020 16:22:15 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]
18/Jun/2020 16:22:10 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]
18/Jun/2020 16:22:05 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]
18/Jun/2020 16:22:00 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/callbacks/interface/flow.lua:458: attempt to index a nil value (local 'flow_status_type')]

**Comment by simonemainardi** [comment]
Can you report the full log since the startup?

**Comment by zimbawe998** [comment]
Hi Simone,
with the last update, some minutes ago, everythings started ok without problems.

**Comment by simonemainardi** [comment]
I think it was something more related to the upgrade procedure than ntopng per se as I have never been able to reproduce. Anyway, thanks for reporting.
