### ISSUE TITLE
Ntopng don't see sent/received traffic

### ISSUE THREAD

**Issue by ShagoY** [ntop/ntopng#4054]
Hello,

Currently, I only have "total traffic" and "dropped packets", but other times, I do have "sent traffic" and "received traffic" in the statistics tab of my interface.

I have two ntopng installed in my network (1 directly on the proxmox host and the second one on a VPS which serves as a Wireguard server). Both have the same configuration but the one on the VPS shows me the inbound/outbound traffic.

so I'd like to understand what might be involved in this behavior.

Thank you :)

ntopng Community Edition v.4.0.200617 on both.
Server Proxmox: Debian 10
Ntong listens to a linux bridge for the WAN and a Bond between two physical interfaces for the LAN.
VPS: Debian 10

Proxmox:
![Image1](https://i.imgur.com/CACkNWd.jpg)

VPS:
![Image1](https://i.imgur.com/JGt6VUp.jpg)

**Comment by simonemainardi** [comment]
When only one direction is shown, it means the interface has been configured to receive "Mirrored Traffic" under the interface preferences page. In this case, the traffic is assumed to only enter the interface so only one 'side' is shown.

When both directions are charted, it means the interface has not been configured with "Mirrored Traffic". In this case, the interface is assumed to TX and RX so the chart shows you both traffic directions - entering (RX) and leaving (TX) the interface.
