### ISSUE TITLE
Implement ntopng federation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4056]
As of today, when multiple ntopng are installed, they do not speak each other. So simple operations such as searching a host and visualize its traffic, requires a manual search on all of them.

This is to request to implement a page where "companion" ntopng instances are defined (IP, and credentials) so what
- when a host is searched in the search box, remote hits are also reported
- clicking on a remote hit will redirect the GUI to the remote instance on the corresponding host page

In the future, a better integration will be added, but for the time being this is the minimum goal to be achieved. All the ntopng communications must happen via REST API

**Comment by gabryon99** [comment]
We decided to implement a new page containing a table to navigate through ntopng instances. A user can configure an instance and then add it inside the page.

**Info to show:**
- Symbolic Name, Status, Info (Download/Upload, Alerts, Num. Hosts), link to instance

**Params to configure an instance to add:**
- URL of ntopng, username and password (not showed)

**Features:**
- Ability to Import and Export data
- Add Active Monitoring Shortcut

**Comment by lucaderi** [comment]
This is a mock-up of the new page we need to implement
![Screen Shot 2020-11-04 at 17 25 40](https://user-images.githubusercontent.com/4493366/98137881-c7d44c80-1ec2-11eb-9dc4-54ebf92b15e6.png)
The user clicking on + adds a new instance specifying
- name/alias
- URL to reach the instance (e.g. https://myntop.com:3000
- the username and password used to connect to it

The dashboard will contact the remote ntopng via REST call using the credentials specified and periodically update the GUI. Adding a new instance causes also ntopng to perodically active-monitor it and thus report the status, charts etc. by leveraging on the active monitorign plugin (i.e. we just need to add a HREF to the plugin). As remote instance can be slow or unavailable, please make sure that the system won't crash or slow down the browser.

Of course as every other table, import/export should be possible (via the newely implemented facilty present in 4.2)

**Comment by simonemainardi** [comment]
This is now implemented in the infrastructure dashboard page.

**Comment by simonemainardi** [comment]
Still need to add the remote search. Reopening.
