### ISSUE TITLE
Invalid form fill when adding multiple devices 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4059]
Suppose to add a host in SNMP. After adding such host, we now add a second host. In this case the form where data has to be entered is not empty but it still contains the previous values as shown in the picture. This is a bug and it must be fixed.

![Screen Shot 2020-06-19 at 11 17 01](https://user-images.githubusercontent.com/4493366/85116990-6dda2f80-b21e-11ea-8869-061b72cf0683.png)

**Comment by gabryon99** [comment]
See the commit: https://github.com/ntop/ntopng/commit/0c71e32abf6b32680675de980583ba5c5ebb3bb0
