### ISSUE TITLE
Configuration persistence 

### ISSUE THREAD

**Issue by whoknowz** [ntop/ntopng#406]
When doing a Redis flushall we loose all host filter rules and traffic shaping rules.
Possible to have the values persistent elsewhere or maybe a way to backup the config before a flush?

For example in a situation like this, the only way to fix it is to flushall right?

18/Feb/2016 21:53:28 [Redis.cpp:357] ERROR: WRONGTYPE Operation against a key holding the wrong kind of value [HKEYS ntopng.prefs.bridge:eth0,eth1.name]

**Comment by lucaderi** [comment]
You can backup/restore as specified in http://zdk.blinkenshell.org/redis-backup-and-restore/

For the above problem you can do

redis-cli del ntopng.prefs.bridge:eth0,eth1.name

**Comment by lucaderi** [comment]
Please star ntopng on github
