### ISSUE TITLE
Rework device location code

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4061]
Create a small module where given a host, we can learn the SNMP device and port where such device is located. This will enable the implementation of #2904 and #3453 

Note that the code that implements this feature is already present in the host page: it simply needs to be moved onto a separate module that will then promote code reuse.

**Comment by simonemainardi** [comment]
implemented in https://github.com/ntop/ntopng/commit/5bb52b1793069f8573cdbcd338bdc306ca862f5c and companion pro commit
