### ISSUE TITLE
Migrate license

### ISSUE THREAD

**Issue by christianbj87** [ntop/ntopng#4062]
Hi, we changed the server and need to migrate the license files of nProbe and NFlite plugin.
I need to contact you because i have already reset the license a few months ago. 

 nprobe -v

Welcome to nProbe v.9.1.200617 (r6899) for x86_64-unknown-linux-gnu
with native PF_RING acceleration.
Copyright 2002-20 ntop.org

Build OS:      CentOS Linux release 7.7.1908 (Core)
SystemID:      689ED9C782072B16
GIT rev:       dev:5168affb357ae70e059113943ef68e5cf988fd9c:20200617
License:       Invalid license (/etc/nprobe.license) [License mismatch error]

# License Reset | 0 [ 0 / 1 ]

Thanks.

**Comment by simonemainardi** [comment]
Contact us privately for licensing issues. Note that reset is only allowed one time per license.
