### ISSUE TITLE
nEdge packet receiving modes

### ISSUE THREAD

**Issue by subhajitchatu** [ntop/ntopng#4065]
I want to run nEdge as a package in my Linux based firewall. What are the options to send packets to nEdge from Linux kernel. Is it possible to send packets to nEdge like nDPI which supports various packet receiving modes?(NFQ, iptable, DPDK etc) Also if I want to send packets from nEdge to other modules is there any interface available? (eg. nEdge to IPS/IDS) Or is it meant for a standalone box which supports various features of similar to a L7 aware UTM?

**Comment by simonemainardi** [comment]
In general, nEdge is meant for a standalone box.

nEdge uses NFQ internally to process enough traffic to take decisions (e.g., pass/drop/shape) and then leverages kernel conntrack.

nEdge uses one interface as LAN and one or more interfaces for the WAN(s). To send/receive traffic from/to it, you should use 'standard' (i.e., no tun/tap/bridge/dummy/lo) network interfaces of the system.

Feeding it with traffic from other NFQs or DPDK is something which could be doable but hasn't been explored yet.

If you have a particular use case in mind, please explain.

**Comment by simonemainardi** [comment]
Closing. Reopen with the requested information if necessary and if you want to move forward with the discussion.
