### ISSUE TITLE
SNMP table sort not preserved after refresh

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4067]
When the table with SNMP devices is refreshed (either periodically or manually by clicking refresh) the order is lost and rows change their position. This happens when the sort column doesn't guarantee per-row uniqueness (e.g, sort by community, sort by interfaces with errors).

**Comment by gabryon99** [comment]
See this commit: https://github.com/ntop/ntopng/commit/0b561c4d9a2fd2cf7af23120a5ec9b02b0656f5f

**Comment by simonemainardi** [comment]
not working

**Comment by simonemainardi** [comment]
fixed with https://github.com/ntop/ntopng/commit/2da75c8f93d6beedcf5bf6d3efab77fca4375536
