### ISSUE TITLE
[Feature Request] Mobile phone view

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#4069]
Hi all,

I can log into my instance of NTOPNG with my phone, however its essentially a carbon copy of the desktop version ...

All I see are the folder names at the right in portrait mode, in landscape mode its slightly better but things are cut off, and Its not that elegant.

I'm pretty sure I am not the only user who would like to see a mobile friendly view of ntopng

Thank you for considering this....

**Comment by simonemainardi** [comment]
Duplicate of #4047
