### ISSUE TITLE
How to Prevent Flow Drops

### ISSUE THREAD

**Issue by oliwirth** [ntop/ntopng#4072]
Hello ntop team,

I discover data amount differences between my productive ntopng version 4.0 and my testing system version 4.1.

Please see attached two pictures. The graphs are the same but the scale and thus the average traffic differs in factor 3.

![ntopng40-2](https://user-images.githubusercontent.com/47536446/85415794-07327a00-b56e-11ea-93ca-aa9388cf566b.jpg)
![ntopng41-2](https://user-images.githubusercontent.com/47536446/85415798-0863a700-b56e-11ea-8c72-af91bde17757.jpg)

I checked tcpdump and the arriving packages are the same. The only difference I could found is that my productive machine uses CPU 8 cores, my testing system ony 4 CPUs.
I allocated also 8 cores for the testing Sytem and now the data amount values are the same.

Can this be the reason?
Are you aware of such behaviour?

Didn't take a picture of the htop befor upgradeing to 8 CPU Cores, but attach an actual view here.
![ntpng_htop](https://user-images.githubusercontent.com/47536446/85418649-54641b00-b571-11ea-8503-d6256fb2df7f.jpg)

**Comment by simonemainardi** [comment]
yes, having fewer cores may lead to packet/flow drop and consequent reduction of the traffic. By the way, you should see the amount of dropped traffic if you visit the interface page.

Please check and also report ntopng configuration used

**Comment by oliwirth** [comment]
My boss now asked, me with a smile, if we can enlarge the transported data amount with increasing to 16 CPU Cores....

**Comment by oliwirth** [comment]
Ah, ok, yes the interfaces showed some dopped packets, but  remains on the same level.
I restartet ntopng and now the counters remain zero on both systems (8CPU Cores).

What do do if they are increasing?

**Comment by oliwirth** [comment]
My ntopng config:

-G=/var/run/ntopng.pid
-i tcp://127.0.0.1:2056
-i tcp://127.0.0.1:9997
-i ens3
--max-num-flows 1000000
--max-num-hosts 1000000
-m 140.181.0.0/16,10.0.0.0/8
-n 1
-p /var/lib/ntopng/custom.proto
--online-license-check

**Comment by oliwirth** [comment]
I realise that on my production system (4.0) the `dropped ZMQ messages` are increasing to 18000 within 15 min for our Internet Interface (lots of flows) but the shown data is the same than inthe testsystem (4.1)
any advice what I can do?

**Comment by simonemainardi** [comment]
Drops are the reason of the discrepancy. Losing 18k messages over 15 minutes may be negligible, though.

Each single `-i` interface uses one thread, so given your configuration, it won't matter much to go from 8 to 16 cores.

What's the configuration of nProbe? Is it collecting NetFlow? sFlow?

**Comment by oliwirth** [comment]
nprobe is collecting netflow from two cisco device (cat 6900)

here is the nprobe config:
1) LHCone is a VRF to a science network `/etc/nprobe/nprobe-LHCone.conf`
-i=none
-n=none
--collector-port 9996
--zmq tcp://127.0.0.1:9997

and
2) our Internet connection `/etc/nprobe/nprobe-MSFC.conf`
-i=none
-n=none
--collector-port 2055
--zmq tcp://127.0.0.1:2056

**Comment by oliwirth** [comment]
nprobe is collecting netflow from two cisco device (cat 6900)

here is the nprobe config:

1. LHCone is a VRF to a science network /etc/nprobe/nprobe-LHCone.conf
    -i=none
    -n=none
    --collector-port 9996
    --zmq tcp://127.0.0.1:9997

and
2. our Internet connection /etc/nprobe/nprobe-MSFC.conf
-i=none
-n=none
--collector-port 2055
--zmq tcp://127.0.0.1:2056

**Comment by oliwirth** [comment]
nprobe is collecting netflow from two cisco device (cat 6900)

here is the nprobe config:
1. LHCone is a VRF to a science network /etc/nprobe/nprobe-LHCone.conf
    -i=none
    -n=none
    --collector-port 9996
    --zmq tcp://127.0.0.1:9997

and
2. our Internet connection /etc/nprobe/nprobe-MSFC.conf
    -i=none
    -n=none
    --collector-port 2055
    --zmq tcp://127.0.0.1:2056

**Comment by oliwirth** [comment]
nprobe is collecting netflow from two cisco device (cat 6900)

here is the nprobe config:

1) LHCone is a VRF to a science network `/etc/nprobe/nprobe-LHCone.conf`:
    -i=none
    -n=none
    --collector-port 9996
    --zmq tcp://127.0.0.1:9997

and
2) our Internet connection `/etc/nprobe/nprobe-MSFC.conf`:

-i=none
-n=none
--collector-port 2055
--zmq tcp://127.0.0.1:2056

**Comment by simonemainardi** [comment]
Configurations look good. As also highlighted by you, 8 cores suffice to keep your instance running drop free. Drops are the cause of the reduced traffic and they are clearly shown (both as total volume and with an historical chart) under the interface page.
