### ISSUE TITLE
Add flow src and dst DSCP

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4073]
Add `u_int16_t` `src_dscp` and `dst_dscp` inside each flow.

DSCP is:

- IP header TOS for IPv4
- IP header Traffic Class for IPv6

DSCPs are populated as follow.

For packet interfaces:
- processPacket performs flow->setDSCP(dscp, cli_2_src /* true or false if the direction is either cli2srv or srv2cli*/)

For ZMQ interfaces:

- processFlow performs:
  - flow->setDSCP(SRC_TOS, true)
  - flow->setDSCP(DST_TOS, false)

SRC_TOS and DST_TOS are those received from nProbe.

Add a flow_utils.lua method to print src_dscp and dst_dscp in a human friendly version with the classes as listed at https://www.cisco.com/c/en/us/support/docs/quality-of-service-qos/qos-packet-marking/10103-dscpvalues.html

Consider the possibility to have multiple setDSCP for the same flow and for the same direction.

Memory: 4 bytes per flow. Worst-case (1M flows) 4Mb.

**Comment by cardigliano** [comment]
Already implemented
