### ISSUE TITLE
Implement DSCP stats

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4074]
Implement class `DSCPStats()` which counts bytes and packets, for each of the 22 codepoints listed at https://www.cisco.com/c/en/us/support/docs/quality-of-service-qos/qos-packet-marking/10103-dscpvalues.html and for each direction (cli2srv and srv2cli).

Implementation will be done with a small hash (say 5 buckets) to accomodate at most 22-items TrafficStats-array lazily initialized. Class must also expose conters to a method called from Lua for data visualization and writing of timeseries.

Add class `DSCPStats` to LocalHostStats and InterfaceStats.

In `Flow::hosts_periodic_stats_update` increase stats as follows (for hosts and interfaces):

```
DSCPStats.incStats(src_dscp, partial->get_cli2srv_packets(), partial->get_cli2srv_bytes(), true /* cli2srv */ );
DSCPStats.incStats(dst_dscp, partial->get_srv2cli_packets(), partial->get_srv2cli_bytes(), false /* srv2cli */ );
```

A tab "DSCP" will be added to the host and to the interface page with pie charts to show DSCP flags distribution.

Serialization is not done.

Memory:
- Worst case (unlikely) 5 (buckets) + 22 * 2 (directions) * 2 (bytes and packets) * 8 (counter size) = 709 Byte. (1M local hosts) 709Mb.
- Best case (no DSCP): 8 byte (DSCPStats pointer) for each host. 1M host = 8Mb

This depends on https://github.com/ntop/ntopng/issues/4073

**Comment by cardigliano** [comment]
Implemented. DSCP flags are grouped by precedence (8 groups + LE + unknown). REST endpoints have been added. Charts to host and interface details pages have been added.
