### ISSUE TITLE
Write DSCP stats timeseries

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4075]
A timeseries with sent and received bytes will be written for each local host and for each interface for every non-zero or the 22 codepoints listed at https://www.cisco.com/c/en/us/support/docs/quality-of-service-qos/qos-packet-marking/10103-dscpvalues.html 

Local host timeseries will be written with 5-minute (1 minute) granularity as Layer-7 statistics.

Interface timeseries will be written every minute.

Interface timeseries are written for each interface when the traffic toggle is on. Local host timeseries must be written only when the 'Full' preference is selected.

Timeseries will be available for browsing in the interface and local host chart page.

Even if showing a stacked chart of al the DSCP would be nice, current timeseries implementation is cumbersome so this may not be doable.

Disk:
- Worst case (unlikely) are 22 extra timeseries for each local host, yielding an additional 22M timeseries for a worst case of 1M hosts.
- Best case: no additional timeseries is written

This depends on https://github.com/ntop/ntopng/issues/4074

**Comment by cardigliano** [comment]
Implemented both for hosts and interfaces, a stacked chart has also been added.
