### ISSUE TITLE
Dump DSCP to downstream stores

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4076]
Src and dst DSCP must be dumped to nIndex and ES.

To add DSCP to ES it suffices to extend `Flow::flow2json`
To add DSCP to nIndex, extra columns need to be added to `NIndexFlowDB.cpp`

Extra columns should also be added when visualizing extracted nIndex data and DSCP should be printed in a human-friendly way using the utility in `flow_utils.lua` implemented as part of https://github.com/ntop/ntopng/issues/4073.

Adding a column to MySQL would require altering the table and this will cause troubles as it involves doubling the disk space. Given that MySQL support is no longer a priority, it would not be desirable to add the column and consequently alter the table.

This depends on https://github.com/ntop/ntopng/issues/4073

**Comment by cardigliano** [comment]
Implemented
