### ISSUE TITLE
Ntopng NoIP issue

### ISSUE THREAD

**Issue by ozoumi** [ntop/ntopng#4077]
Hey,
I installed Ntopng in Ubuntu 20.04 LTS, and i can get informations about my network traffic. but while testing the solution i noticed that most client/server flows dont contain ip addresses (NoIP).

ntopng.conf
-----------------------------------------
--pid-path=/var/tmp/ntopng.pid
--daemon
--interface=ens33
--http-port=3000
--local-networks="172.18.68.0/23"
--dns-mode=1
--data-dir=/var/tmp/ntopng
--disable-autologout
--community
-G=/var/run/ntopng.pid
------------------------------------------

What could be the issue

Thank you

**Comment by simonemainardi** [comment]
NoIP means no IP traffic. It could be DHCP for example. Check the flow application for additional information.

**Comment by ozoumi** [comment]
Actually, i tried wireshark to see if i can get that traffic, i've noticed many communications are presented with src port and destination and morr but for the ip addresses i don't get such information, however with wireshark i get the ip address.
Ps: wasn't dhcp

**Comment by simonemainardi** [comment]
What was it? Better if you attach the wireshark capture.
