### ISSUE TITLE
more traffic profiles

### ISSUE THREAD

**Issue by svenvogel** [ntop/ntopng#408]
Hi,

we can only create 16 traffic profiles but we need unlimited. is that possible to add these?

thanks

Sven

**Comment by svenvogel** [comment]
can you please add this in the new version?

**Comment by simonemainardi** [comment]
presently we have chosen to limit the maximum number of profiles even if we may increase this number in the future.

**Comment by svenvogel** [comment]
Why you close the ticket and what is may increase the number in the future?

Von: simonemainardi [mailto:notifications@github.com]
Gesendet: Dienstag, 1. März 2016 11:36
An: ntop/ntopng
Cc: Vogel, Sven
Betreff: Re: [ntopng] more traffic profiles (#408)

presently we have chosen to limit the maximum number of profiles even if we may increase this number in the future.

**Comment by lucaderi** [comment]
@svenvogel Can you please tell us what is a reasonable number of profiles?

**Comment by svenvogel** [comment]
i think 256 profiles would be a good choice. when we need more cpu we can add a vcpu. maybe its possible to add with edit field the account of traffic profiles. that would be great :)

**Comment by svenvogel** [comment]
there are any information when it will included in a actutally version?

**Comment by lucaderi** [comment]
Sometime in spring (hopefully). Can you please send us examples of the 16 filters you have so we can better the design them?

**Comment by svenvogel** [comment]
i would send you an email because of data and an screenshot?

**Comment by lucaderi** [comment]
Sure

**Comment by Uzzi** [comment]
Hi, news about this feature request?

**Comment by simonemainardi** [comment]
@Uzzi with the current design and implementation we believe that 16 is a reasonable number. We may extend this in the future. You will be notified in this issue.

**Comment by Uzzi** [comment]
@simonemainardi Thak you
Have a nice day

**Comment by svenvogel** [comment]
Okay. Thanks for info. Then we dont buy you product again.

**Comment by lucaderi** [comment]
@svenvogel As you requested the number of traffic profiles has been raised to 128 as reported in http://www.ntop.org/products/traffic-analysis/ntop/. I am sure you will like ntopng again
