### ISSUE TITLE
VLAN dynamic disaggregation issue

### ISSUE THREAD

**Issue by mroe1234** [ntop/ntopng#4084]
Here is a tcpdump of the flows received from a particular netflow generator.  This data was captured from the nprobe host.  As you can see the template provided by the generator includes the SRC_VLAN, and the two flows have vlan_id of '0' and '95'.

In the ntopng interface I select the interface (tcp://127.0.0.1:5556), then select "interface" on the left, then the gear icon (config), then select "VLAN ID" for dynamic disaggregation.  When I restart ntopng, a new interface is available in the drop down for [VLAN ID: 0], but not for [VLAN ID: 95].

The template packet:

    Frame 1170: 174 bytes on wire (1392 bits), 174 bytes captured (1392 bits)
    Ethernet II, Src: Cisco_f3:aa:42 (00:2a:6a:f3:aa:42), Dst: WistronI_03:9c:58 (08:94:ef:03:9c:58)
    Internet Protocol Version 4, Src: **********, Dst: ************
    User Datagram Protocol, Src Port: 23384, Dst Port: 2055
    Cisco NetFlow/IPFIX
        Version: 9
        Count: 3
        SysUptime: 79373.394000000 seconds
        Timestamp: Jun 25, 2020 10:14:13.000000000 EDT
        FlowSequence: 1546151
        SourceId: 257
        FlowSet 1 [id=0] (Data Template): 2885
            FlowSet Id: Data Template (V9) (0)
            FlowSet Length: 60
            Template (Id = 2885, Count = 13)
                Template Id: 2885
                Field Count: 13
                Field (1/13): BYTES
                Field (2/13): PKTS
                Field (3/13): SRC_VLAN
                Field (4/13): INPUT_SNMP
                Field (5/13): OUTPUT_SNMP
                Field (6/13): IF_NAME
                Field (7/13): IP_DST_ADDR
                Field (8/13): PROTOCOL
                Field (9/13): IP_SRC_ADDR
                Field (10/13): L4_SRC_PORT
                Field (11/13): L4_DST_PORT
                Field (12/13): FIRST_SWITCHED
                Field (13/13): LAST_SWITCHED
        FlowSet 2 [id=1] (Options Template): 2890,2891
            FlowSet Id: Options Template(V9) (1)
            FlowSet Length: 52
            Options Template (Id = 2890) (Scope Count = 2; Data Count = 5)
                Template Id: 2890
                Option Scope Length: 8
                Option Length: 20
                Field (1/2) [Scope]: Line Card
                Field (2/2) [Scope]: Template
                Field (1/5): TOTAL_PKTS_EXP
                Field (2/5): TOTAL_FLOWS_EXP
                Field (3/5): TOTAL_BYTES_EXP
                Field (4/5): SAMPLING_ALGORITHM
                Field (5/5): SAMPLING_INTERVAL
            Options Template (Id = 2891) (Scope Count = 1; Data Count = 1)
                Template Id: 2891
                Option Scope Length: 4
                Option Length: 4
                Field (1/1) [Scope]: Interface
                Field (1/1): IF_NAME

Flow 1
     Octets: 8895
     Packets: 15
     Vlan Id: 0
     InputInt: 17958400
     OutputInt: 17960960
     IfName: 1/1/x6 alias hybrid1
     DstAddr: ************
     Protocol: TCP (6)
     SrcAddr: ************
     SrcPort: 389 (389)
     DstPort: 53720 (53720)
     [Duration: 0.286000000 seconds (switched)]

Flow 2
         Octets: 1338
         Packets: 14
         Vlan Id: 95
         InputInt: 17958400
         OutputInt: 17960960
         IfName: 1/1/x6 alias hybrid1
         DstAddr: *************
         Protocol: TCP (6)
         SrcAddr: 73.52.66.114
         SrcPort: 56632 (56632)
         DstPort: 443 (443)
        [Duration: 0.366000000 seconds (switched)]

**Comment by simonemainardi** [comment]
please report ntopng and nprobe configurations used. Also it would be important to have a netflow pcap capture so we can replay it in our lab. You can send it privately to me at mainardi at ntop dot org.

**Comment by mroe1234** [comment]
nprobe.conf:
    --collector-port=2055
    --zmq=tcp://*:5556
    -T=@NTOPNG@

ntopng.conf:
    -G=/var/run/ntopng.pid
    -i tcp://127.0.0.1:5556
    -i tcp://*:1234c
    -m 10.10.0.0/16
    -F es;_doc;ntopng-%Y.%m.%d;http://elasticserver:9200/_bulk;

**Comment by simonemainardi** [comment]
Said that in the netflow pcap packet capture provided there are 4 netflow exporters and only one is actually exporting VLANs - the guy using template id 2885 - everything works as expected, both on stable and dev releases.


![image](https://user-images.githubusercontent.com/3397663/85830949-bef1a280-b78d-11ea-9db6-7122c39a59ce.png)

dev:

![image](https://user-images.githubusercontent.com/3397663/85830920-aed9c300-b78d-11ea-9cde-ce3106bdd09a.png)

stable:

![image](https://user-images.githubusercontent.com/3397663/85831187-3293af80-b78e-11ea-8137-6446015483f8.png)

----

Looking at the configuration files provided, I have the suspect that your ntopng is not connected to the right nprobe - i.e., you've another instance of nprobe running which is not listening to the right netflow exporters.

Stop all processes, then restart them. If you want to use ntopng in collector mode, i.e. `-i tcp://*:1234c`, then you have to add option `--zmq-probe-mode` to nProbe:

```
ntopng:
-i="tcp://127.0.0.1:5556c"

nprobe:
--zmq="tcp://127.0.0.1:5556"
--zmq-probe-mode
```

Also check that you are either running the lastest devs or stable releases.

**Comment by mroe1234** [comment]
There is only one nprobe instance running on the local machine.  I get the same results if I use the config file or the cli.

**Comment by simonemainardi** [comment]
everything is working as expected so it must be something with the configuration. Did you follow my suggestion? Did you change the configurations as I've indicated?

**Comment by mroe1234** [comment]
nprobe.conf:
--collector-port=2055
--zmq=tcp://127.0.0.1:5556
-T=@NTOPNG@

ntopng:
-G=/var/run/ntopng.pid
-i tcp://127.0.0.1:5556
-i tcp://*:1234c

So I took half your suggestion and instead of listening on all interface, I limited zmq to 127.0.0.1, and that seems to do the trick.  Does that mean something else was emitting into zmq screwing up the data?

**Comment by simonemainardi** [comment]
Thanks for reporting.

By the way, there's no need to limit to 127.0.0.1 but it would be desirable, security-wise, if both ntopng and nprobe are on the same machine.

Note that:

- when you use ntopng in collector mode, e.g.,  `-i tcp://*:1234c` you can send data from multiple nprobe simultaneously but each one must have the ntopng ip address and option `--zmq-probe-mode` (`--zmq="tcp://<ntopng address>:1234 --zmq-probe-mode"`)
- when ntopng is not used in collector mode, e.g., `-i tcp://127.0.0.1:5556`, then the connection occurs from ntopng to nprobe and only one nprobe instance can be connected to that particular -i. In this case, nprobe must be started without option --zmq-probe-mode.
