### ISSUE TITLE
Custom ElasticSearch template

### ISSUE THREAD

**Issue by mroe1234** [ntop/ntopng#4085]
We find ourselves needing to customize the ElasticSearch template that ships with ntopng.  I have included the diff below.  Is there a way to specify the use of a custom template?  It also seems like every time ntopng restarts, it re-uploads the template from the default location, which reverts any custom changes.

    # diff /usr/share/ntopng/httpdocs/misc/ntopng_template_elk7.json /etc/ntopng/custom-template.json 
    4c4,5
    < 	"index.refresh_interval": "5s"
    ---
    > 	"index.refresh_interval": "5s",
    > 	"index.number_of_shards": "5"

ntopng --version
    v.4.1.200624	[Enterprise/Professional build]
    GIT rev:	dev:0181e2a2e5686dd5627ae1048d648e340ebae001:20200624
    Pro rev:	r3062
    Built on:	Debian GNU/Linux 10 (buster)
    System Id:	0106A25AB206AB23
    Platform:	x86_64
    Edition:	Enterprise M
    License Type:	Permanent

**Comment by simonemainardi** [comment]
currently, this is not supported.

**Comment by mroe1234** [comment]
In case this takes a while to implement and others need something like it in the future.  We ended up using patch to fix the template and making it an ExecStartPre script in systemd.  This has the benefit being to embrace minor template chances and if ntopng's template changes dramatically and the patch can't be successfully applied, ntopng won't start and effect the ElasticSearch cluster:

     [Service]
     ExecStartPre=/usr/local/sbin/patch-ntop-template

And the script:

    #!/bin/bash -u
    output=$(/usr/bin/patch -r - -p0 --forward -s -d /usr/share/ntopng/httpdocs/misc < /etc/ntopng/template.patch)

    #patch applied successfully
    if [[ $? -eq 0 ]]
    then
        echo "Patch applied"
        exit 0
    fi

    #patch as already been applied
    if [[ $output == *"Reversed (or previously applied) patch detected!  Skipping patch."* ]]
    then
        echo "Patch already applied"
        exit 0
    fi
    echo "Couldn't apply patch: $output"
    exit 1

**Comment by simonemainardi** [comment]
Thanks for sharing this solution.
