### ISSUE TITLE
ntop ng crash with german characters

### ISSUE THREAD

**Issue by svenvogel** [ntop/ntopng#409]
Hi,

when we add traffic profiles with german characters like "ä, ö, ü" ntopng crashes.

19/Feb/2016 14:31:10 [Lua.cpp:4560] WARNING: Discarded char '<E4>' in URI [H%E4nder]

greetings
Sven

**Comment by lucaderi** [comment]
I can reproduce the warning but not the crash

**Comment by svenvogel** [comment]
hmm yes thats the only thing which i saw in log. we filled out the traffic profiles very fastly and ntopng seems to be crashed. i dont have more information.

**Comment by lucaderi** [comment]
Can you please generate a core dump and create a tar ball containing the core and the ntopng binary (just the binary)?

**Comment by svenvogel** [comment]
how i generate them?

**Comment by lucaderi** [comment]
http://www.ntop.org/support/faq/how-to-report-a-bug-on-ntop-apps/

**Comment by simonemainardi** [comment]
Can't reproduce the crash. The warning is due to the ntopng engine that strips out non-ascii characters. UTF-8 is not supported. @svenvogel any news? can you confirm that ntopng is not crashing but just raising an error? thank you
