### ISSUE TITLE
[configuration] 'Add to pool' shortcuts

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4093]
Once #4089 #4090 #4091 #4092 have been implemented, shortcuts for the addition of pool members must be added:

- Interface pools: A dropdown with the list of available interface pools must be added under the if_stats.lua->cog page
- Local network pools: A dropdown with the list of available local network pools must be added under the cog icon of the network details (http://devel:3000/lua/network_details.lua?network=1&page=config#)
- SNMP devices pools: An extra dropdown with the list of available SNMP devices pools must be shown in the SNMP add device modal so one can pick the pool straight during the addition. An snmp 'cog' page must be added as well with a dropdown of all the available snmp devices pools (http://devel:3000/lua/pro/enterprise/snmp_device_details.lua?ip=xxx)
- Active measurement pools: An extra dropdown with the list of available active monitoring pools must be shown in the add/edit active measurement modal.

**Comment by simonemainardi** [comment]
> SNMP devices pools: An extra dropdown with the list of available SNMP devices pools must be shown in the SNMP add device modal so one can pick the pool straight during the addition. An snmp 'cog' page must be added as well with a dropdown of all the available snmp devices pools (http://devel:3000/lua/pro/enterprise/snmp_device_details.lua?ip=xxx)

https://github.com/ntop/ntopng/issues/4123

> Active measurement pools: An extra dropdown with the list of available active monitoring pools must be shown in the add/edit active measurement modal.

https://github.com/ntop/ntopng/issues/3858

**Comment by simonemainardi** [comment]
need to add

- Interface pools: A dropdown with the list of available interface pools must be added under the if_stats.lua->cog page
- Local network pools: A dropdown with the list of available local network pools must be added under the cog icon of the network details (http://devel:3000/lua/network_details.lua?network=1&page=config#)

Make a general component to reuse what currently shows under the host/mac cog for pool assignment.

**Comment by simonemainardi** [comment]
also consider and add the refresh button as inside the modals

**Comment by gabryon99** [comment]
A dropdown containing the pool list has been added inside the Interface Config page and Local Network config page.

Interface:
<img width="1676" alt="Screenshot 2020-10-16 at 17 59 43" src="https://user-images.githubusercontent.com/14114916/96281266-60209500-0fd9-11eb-9a6d-9dc537cc9918.png">

Local Network:
<img width="1676" alt="Screenshot 2020-10-16 at 18 01 25" src="https://user-images.githubusercontent.com/14114916/96281440-9e1db900-0fd9-11eb-8e24-e5724595396f.png">
