### ISSUE TITLE
JSON error when accessing Hosts and Looking Glass menu

### ISSUE THREAD

**Issue by drivmont** [ntop/ntopng#4097]
ntopng Community Edition v.3.8.200529 loaded on a Netgate/Pfsense box.
When I access the Hosts menu I get this error:

SyntaxError: JSON.parse: expected ',' or '}' after property value in object at line 9 column 262 of the JSON data

When I access the Looking Glass menu I get this error:

SyntaxError: JSON.parse: expected ',' or '}' after property value in object at line 4 column 262 of the JSON data

**Comment by simonemainardi** [comment]
3.8 is no longer supported. Supported stable release is 4.0. Please upgrade.
