### ISSUE TITLE
Cannot determine n2disk timeline directory when using multiple dump directories

### ISSUE THREAD

**Issue by pbyrne-tpt** [ntop/ntopng#4102]
Hi, we're having an issue with locating the timeline directory when using a manually controlled n2disk instance and multiple dump directories. 

![image](https://user-images.githubusercontent.com/26063721/86289601-032fd900-bbba-11ea-930e-73ece5718ff0.png)

Here is the n2disk configuration:
--interface=nt:0
--dump-directory=/nvme1/n2disk/pcap/
--dump-directory=/nvme2/n2disk/pcap/
--dump-directory=/nvme3/n2disk/pcap/
--dump-directory=/nvme4/n2disk/pcap/
--timeline-dir=/capture/n2disk/timeline
--snaplen=1536
--buffer-len=16384
--chunk-len=16384
--disk-limit=90%
--max-file-len=2048
--max-file-duration=60
--unprivileged-user=ntopng
--trace-log=/var/log/n2disk/traces.log
--event-log=/var/log/n2disk/events.log
--reader-cpu-affinity=18,20,22
--writer-cpu-affinity=2,4,6,8,10
--compressor-cpu-affinity=12,14,16
--zmq=tcp://127.0.0.1:5556
--zmq-export-flows
--zmq-probe-mode
--index-on-compressor-threads
--nanoseconds
--index

**Comment by cardigliano** [comment]
@pbyrne-tpt what n2disk version are you running? (It seems I cannot reproduce this with the same conf and latest n2disk)

**Comment by cardigliano** [comment]
Please also provide cat /proc/net/pf_ring/stats/*

**Comment by pbyrne-tpt** [comment]
@cardigliano 
n2disk --version
n2disk v.3.4.200623 (r5201)

ntopng --version
v.4.0.200623    [Enterprise/Professional build]

[root@fpif-pcapl1 ~]# cat /proc/net/pf_ring/stats/88501-none.50
Duration:          0:00:01:00:016
Throughput:        2.10 Mpps    14.72 Gbps
Packets:           112788408
Filtered:          112788408
Dropped:           0
Bytes:             98505772875
DumpedBytes:       95330578929
DumpedFiles:       45
SlowStorageLoops:  0
CaptureLoops:      60148
FirstDumpedEpoch:  1594074974
LastDumpedEpoch:   1594138237
BytesOnDisk:       5607455639705
TimelinePath:      /capture/n2disk/timeline
ExportedFlows:     497984
DroppedFlows:      0

Each of the dump directories are on their own filesystems. I'm not sure if that's related.

**Comment by cardigliano** [comment]
@pbyrne-tpt having multiple dump directories should not affect this, it just looks for the TimelinePath. I am double checking with the exact version you are running.

**Comment by cardigliano** [comment]
@pbyrne-tpt ntopng/n2disk stable with the same conf is also working for me, could you update to latest stable revision and let me know?

**Comment by pbyrne-tpt** [comment]
Still having the issue with the following package versions:

cento-1.10.200704-527.x86_64
e1000e-zc-3.4.0.2.3040-dkms.noarch
i40e-zc-2.4.6.3040-dkms.noarch
igb-zc-5.3.5.18.3040-dkms.noarch
ixgbe-zc-5.5.3.3040-dkms.noarch
ixgbevf-zc-4.5.1.3040-dkms.noarch
n2disk-3.4.200704-5213.x86_64
n2n-2.6.0-250.x86_64
ndpi-3.2.0-2605.x86_64
nprobe-9.0.200704-6823.x86_64
ntopng-4.0.200704-9268.x86_64
ntopng-data-4.0.200704-9268.noarch
pfring-7.6.0-3060.x86_64
pfring-dkms-7.6.0-3060.noarch
pfring-drivers-zc-dkms-1.2-0.noarch

Are there any other logs that might help? We can also setup a screenshare if that would be easier.

**Comment by cardigliano** [comment]
@pbyrne-tpt let's schedule a call, please send an email to cardigliano at ntop.org

**Comment by cardigliano** [comment]
It seems this is due to a Permission denied on RH 7.7, the sudo configuration looks good, @pbyrne-tpt will investigate with the support.

**Comment by cardigliano** [comment]
Sine RH 7.6 the sudo utility runs the PAM modules even when NOPASSWD is configured in the policy. 
Adding ntopng to /etc/access.conf looks to have fixed this issue.
