### ISSUE TITLE
[configuration] Adding new pools

### ISSUE THREAD

**Issue by gabryon99** [ntop/ntopng#4104]
In order to implement the pools adding, it's requested to create an endpoint will manage the following `POST` request (using interfaces pool for example):
```
{
   # This is the pool name
    name: "The Pool Name",

   # This is the configuration to apply to the pool
    configset_id: 1234,

    # These are the pool's members (in this case they are interface ids)
    members: [ 0, 2, 4 ]
}
```
The request contains always the same parameters across all different pool types.

When the request succeeds then a response like this is expected:
```
{
    status: "OK|Failed",
    pool_id: "abcdeficgejx01234",
    message: "I18N_MESSAGE_ID"
}
```

**Comment by simonemainardi** [comment]
Implemented as requested in the backend exposed in the following REST endpoints:

```
scripts/lua/rest/v1/add/network/pool.lua
scripts/lua/rest/v1/add/interface/pool.lua
scripts/lua/rest/v1/add/active_monitoring/pool.lua
pro/scripts/lua/rest/v1/add/snmp/device/pool.lua
```
