### ISSUE TITLE
License save alert

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4105]
With ntopng enterprise L, the license must be saved on a text file as this is used also by nprobe and n2disk. In case the use puts the license on the web GUI (and only for the L version), ntopng mush show an alert asking the user to write the license file on disk otherwise the companion apps will be broken

**Comment by gabryon99** [comment]
For the first case we will show the following message:
"_Please be aware that you need also to create /etc/ntopng.license file as this file is used by the other companion applications. See https://www.ntop.org/support/faq/what-is-included-in-ntopng-enterprise-l/ for details_"

for the second case:
"_We advise you create as well ntopng.license file (according to the instructions you received) to avoid loosing your license in case of redis cleanup_"

**Comment by gabryon99** [comment]
Fixed in https://github.com/ntop/ntopng/commit/5b6e1c1dee74f920c8fbf24ada0cf4a1409b62a6
