### ISSUE TITLE
[configuration] Get members and config avaibles for pools

### ISSUE THREAD

**Issue by gabryon99** [ntop/ntopng#4106]
It's requested to create two Lua functions to get the available members to create a new pool and the available config sets. When a new pool it's added the GUI will disable the members and config used by the new pool.

The functions name can be like: `*_pool_list_members()` and `*_snmp_pool_list_configsets()`. Where the `*` can be SNMP, Interface, Local Network, Active Monitoring, ...

**Comment by simonemainardi** [comment]
Methods added. currently added for interfaces, will be extended for other pool types.

usage

```
package.path = dirs.installdir .. "/scripts/lua/modules/pools/?.lua;" .. package.path
local interface_pools = require "interface_pools"
interface_pools.list_available_members()
interface_pools.list_available_configset_ids()
```

**Comment by simonemainardi** [comment]
new methods use the OO-implementation and can be used as follow

```
package.path = dirs.installdir .. "/scripts/lua/modules/pools/?.lua;" .. package.path
local interface_pools = require "interface_pools"
local s = interface_pools:create()
s:get_available_members()
s:get_available_configset_ids()
```

**Comment by simonemainardi** [comment]
implemented as described above
