### ISSUE TITLE
Saving to MySQL data looks encrypted

### ISSUE THREAD

**Issue by ftraybird** [ntop/ntopng#411]
After I connect to my ntopng db in MySQL and run the following command:

mysql> select \* from flowsv4_6;

I get what looks to be encrypted data.

How can I view the data saved from ntopng in MySQL?  Do I need a tool or can I use just simple standard MySQL commands to look at the historical flow data?

Thanks!

**Comment by lucaderi** [comment]
@ftraybird It is just compressed. See http://www.w3resource.com/mysql/encryption-and-compression-functions/compress().php
