### ISSUE TITLE
SNMP versions error

### ISSUE THREAD

**Issue by Eugene-Prokhorenko** [ntop/ntopng#4110]
I added some v2c devices in ntopng and next day I noticed, that some v2c changed to v3. Plz fix this.

**Comment by simonemainardi** [comment]
please report the version you are using.

**Comment by lucaderi** [comment]
@Eugene-Prokhorenko Please report how to to reproduce the issue.

**Comment by Eugene-Prokhorenko** [comment]
I update every day.

eugene@asnet-monitoring:~$ ntopng -V
v.4.1.200705    [Enterprise/Professional build]
GIT rev:        dev:fdb486e088753871809637ba66e25dc246cb543c:20200705
Pro rev:        r3098
Built on:       Ubuntu 18.04.4 LTS
System Id:      2C1C53C100000F59
Platform:       x86_64
Edition:        Enterprise M
License Type:   Permanent
Maintenance:    Until Thu Jun 17 17:14:33 2021 [346 days left]
License:       
I7lHEO6xeTQnjHy96Tv+0cxFKwbBH+mRh4rM85QPeQymzAZ6VApYlMKQ+a2/up6DW0OkA
                3dHZZpK2G7U3U8fje/37tCsvjz9+na2xAwikp0HM5/HjKgbzOTNLoiOEnmiZtXX9q9qqK
                bnPSvbgEoLX0EZjdx/8EUhM/hCEQVi5VHLI7YTB3z7TekNWQUkmHKgtK2cPIck/hNWHhl
                d8zjhW0SzU20Y+6Ibpf5Z50Ioa7Nvxn+jhiVlyXz6ToZAsIwySL4YQPD97NI3bDXsnX91
                7fewIfyXxCYdOeIoqm6fp9rBFS3pcIv8RJvrZGlvbni7/qLmyZ+PDkyk3WWJmJRyPA==
License Hash:   D3FA7AD5E98F30E8807DE0E454CA78D7162393567317B3DC3C

**Comment by lucaderi** [comment]
Thanks but I need to know how to reproduce the problem.

**Comment by Eugene-Prokhorenko** [comment]
Just add some (13 in my case) snmp devices with v2c. Cheked that they are visible and give graphs by interfaces. Next day you can see v3 instead of v2c. but graphs are ok.

**Comment by lucaderi** [comment]
![Screen Shot 2020-07-07 at 11 07 05](https://user-images.githubusercontent.com/4493366/86755574-073c7a80-c042-11ea-9daa-f3b06ba305c2.png)
Do you mean that the above picture, without you to do anything, changed from 2c to 3 ?

**Comment by Eugene-Prokhorenko** [comment]
Yes! I did nothing with this table after creation.

**Comment by simonemainardi** [comment]
@Eugene-Prokhorenko is it working with the latest dev?

**Comment by Eugene-Prokhorenko** [comment]
there is no place for version. you change it to pool default. what is it for?

**Comment by simonemainardi** [comment]
Pools are groups of SNMP devices. You can associate each pool to a series of recipients. This allows you to send mails selectively, e.g., when SNMP device 1.2.3.4 errors, send an email to Eugene, when SNMP device 6.7.8.9 errors, send and email to Luca.

We are going to complete the documentation before the release. However, in the meanwhile, you can give it a try:
- add a notification endpoint
- add a notification recipient
- create an SNMP pool with a device and associate the recipient to it
- visit the user scripts page/SNMP and configure the alerts you want to trigger.

Then, you should see mails coming when the SNMP device has errors.

For the column community, let's close it for now as it was not reproducible and now also the column has been replaced with the Pool column.

**Comment by Eugene-Prokhorenko** [comment]
Ok, lets close.
It's interesting, that SNMP routers in ntop list now give warning: waiting
for SNMP program 16 (or other number).

E.

**Comment by simonemainardi** [comment]
can you attach a screenshot?

**Comment by Eugene-Prokhorenko** [comment]
On mikrotik router.
