### ISSUE TITLE
can Ntop import a Netflow file for analyzing the offline traffic?

### ISSUE THREAD

**Issue by garygaryyung** [ntop/ntopng#4111]
can Ntop import a Netflow file for analyzing the offline traffic?

**Comment by simonemainardi** [comment]
ntopng doesn't interpret netflow. To analyze netflow traffic, you need to use ntopng in combination with nProbe as described in https://www.ntop.org/guides/ntopng/advanced_features/sflow_collection.html?highlight=netflow#sflow-netflow-collection

In case you have a netflow packet capture that you want to replay, then you can use a tool such as `nfreplay` to send netflow to nProbe in collector mode.
