### ISSUE TITLE
IP/Mac address Stats

### ISSUE THREAD

**Issue by ChunshengZhao** [ntop/ntopng#4114]
**Example：**

Day1
MAC:XXXX:XXXX:XXXX -> DHCP -> 192.168.0.1
(Router/AccessPoint) MAC Address:AAAA:BBBB:CCCC
 Total Bytes: 1.0GB

Day2
MAC:YYYY:YYYY:YYYY -> DHCP -> 192.168.0.1
(Router/AccessPoint) MAC Address:AAAA:BBBB:CCCC
Total Bytes: ?GB

On the Day1, one host got an IP (192.168.0.1), the "Total Bytes" I saw were: 1.0G, and the Day2, another host got the same IP (192.168.0.1), Even if this host does nothing, will "Total Bytes" be 1GB? If so, how should the traffic be differentiated?

**Comment by simonemainardi** [comment]
See https://www.ntop.org/guides/ntopng/basic_concepts/local_broadcast_domain.html

In essence, ntopng is smart enough to keep stats on a per-mac-address for hosts in your local broadcast domain. You only have to set "local broadcast domain identifier" to "Mac Address" in

![image](https://user-images.githubusercontent.com/3397663/86612276-2e4a6c00-bfb0-11ea-8e60-0fe0f16c9edb.png)

You can also configure your DHCP ranges to help ntopng from:

![image](https://user-images.githubusercontent.com/3397663/86612311-3d311e80-bfb0-11ea-8dbd-1bc5b9af0c15.png)

So, back to your question:

> On the Day1, one host got an IP (192.168.0.1), the "Total Bytes" I saw were: 1.0G, and the Day2, another host got the same IP (192.168.0.1)

On Day2, 192.168.0.1 will not have 1.0G but only the volume of traffic corresponding to the new host that has received ip address 192.168.0.1 on day 2.

**Comment by ChunshengZhao** [comment]
The MAC address seen in the system is not the real MAC of the device.
It is the interface MAC of the switch.

![图片](https://user-images.githubusercontent.com/9263377/86748385-00782c80-c06f-11ea-919a-8d5a1cf9a156.png)



Also: How can I search for sensitive URLs in the search box. For example, I want to find a computer that visits Google.com.

**Comment by simonemainardi** [comment]
If the mac address seen by ntopng is the mac address of the router, then ntopng cannot reliably determine any DHCP IP address re-assignment.

Wht do you mean with Vlanif MAC?

Can you attach a pcap capture so I can do better checks?

**Comment by ChunshengZhao** [comment]
Filter Hosts: DHCP Only
Order by: IP Address

At the same time, I saw hosts with the same IP address, and one of them got the correct VLAN ID and real MAC address, but the traffic did not seem to be correct. The other one did not get the correct VLAN ID and MAC address (Vlanif1 MAC), but the traffic looks correct.

My switch has many VLANs. I deployed NTOPNG on a port in VLAN 30, and this port mirrors all the traffic on a port (Vlanif1 MAC) connected to the route.

![图片](https://user-images.githubusercontent.com/9263377/86931031-38b06580-c16a-11ea-891f-fd1a7b3ed9f4.png)

**Comment by simonemainardi** [comment]
It's normal to see two hosts. Hosts in ntopng are keyed using VLANs. In the picture above you have:

- 172.17.20.119 VLAN 20
- 172.17.20.119 without VLAN

This means ntopng is seeing both VLAN-tagged and untagged traffic for 172.17.20.119. However, tagged traffic is just a very small amount (1.98K). Telling you what is that tagged traffic is not possible without seeing a capture. It can also depend on the switch configuration. Maybe you've trunk an access ports and you are mirroring both.

**Comment by ChunshengZhao** [comment]
1. How to capture packets?  Use Wireshark?  How long does it take to capture?  2. How to provide the data package safely?  e-mail?  3. The question I asked before: how to save the URL visited and support search or trigger an alarm when accessing a specific URL.  I currently use the community version.Thanks!

**Comment by ChunshengZhao** [comment]
```
[S5730-HI]dis port-mirroring
  ----------------------------------------------------------------------
  Observe-port 1 : GigabitEthernet0/0/24
  ----------------------------------------------------------------------
  Port-mirror:
  ----------------------------------------------------------------------
       Mirror-port               Direction  Observe-port
  ----------------------------------------------------------------------
  1    GigabitEthernet0/0/1      Inbound    Observe-port 1
  2    GigabitEthernet0/0/1      Outbound   Observe-port 1
  ----------------------------------------------------------------------
[S5730-HI]dis observe-port
  ----------------------------------------------------------------------
  Index          : 1
  Untag-packet   : No
  Interface      : GigabitEthernet0/0/24
  ----------------------------------------------------------------------
[S5730-HI]interface GigabitEthernet 0/0/24
[S5730-HI-GigabitEthernet0/0/24]dis th
#
interface GigabitEthernet0/0/24
 port link-type access
 port default vlan 30
#
return
[S5730-HI-GigabitEthernet0/0/24]q
[S5730-HI]interface GigabitEthernet 0/0/1
[S5730-HI-GigabitEthernet0/0/1]dis th
#
interface GigabitEthernet0/0/1
 port link-type trunk
 port trunk allow-pass vlan 2 to 4094
 port-mirroring to observe-port 1 inbound
 port-mirroring to observe-port 1 outbound
#
return
[S5730-HI-GigabitEthernet0/0/1]
```

interface GigabitEthernet0/0/24
 port link-type access
 **port default vlan 30**

Is this configuration correct?
The ntop server is connected to 24 ports, and the IP is: xxx.xxx.30.1 . I accessed the server by http://xxx.xxx.30.1 .

**Comment by simonemainardi** [comment]
> How to capture packets?

use tool `tcpdump`

> How long does it take to capture? 

A few seconds.

> How to provide the data package safely? e-mail?

Send it to mainardi ntop org

> 3. The question I asked before: how to save the URL visited and support search or trigger an alarm when accessing a specific URL

Not supported.

> Is this configuration correct?

I am not familiar with the configuration of your switch. I can't tell you this. Anyway, again, I don't see any issue on ntopng side, just your switch which is sending both tagged and untagged traffic.
