### ISSUE TITLE
Graphing selected timeframe not showing

### ISSUE THREAD

**Issue by kg9oh** [ntop/ntopng#4115]
ntopng menu Interface > emX[nic] > chart 
the timeframe selection for the charting is not showing the current selection.
selection of the time series works just fine, but a current selection indicator would be great.

**Comment by simonemainardi** [comment]
please report a screenshot

**Comment by kg9oh** [comment]
screenshot per request.
circled area is the selectable items, however upon clicking there is no indication of the time series selection.
all data elements are working.

![ntopng](https://user-images.githubusercontent.com/67924543/86782436-aa7e9700-c024-11ea-99e8-9be931a8f36c.png)

**Comment by simonemainardi** [comment]
@gabryon99 can you please highlight the current selection in community mode

**Comment by gabryon99** [comment]
<img width="829" alt="Screenshot 2020-07-08 at 11 14 25" src="https://user-images.githubusercontent.com/14114916/86900876-30c1d880-c10c-11ea-8b87-1d297e2863e7.png">
<img width="829" alt="Screenshot 2020-07-08 at 11 15 54" src="https://user-images.githubusercontent.com/14114916/86901072-649cfe00-c10c-11ea-9fa1-f7bafe030cc0.png">

Now the timeframe is highlighted as request (in default theme and in the dark theme as well). See the commit for reference: https://github.com/ntop/ntopng/commit/2aea87d8b8980440aaaf91d5f9afb46bca5c8420
