### ISSUE TITLE
Install from package doesn't work on macOS 10.15.5 Catalina

### ISSUE THREAD

**Issue by BigGillyStyle** [ntop/ntopng#4116]
I have downloaded and attempted to install ntopng from http://packages.ntop.org/MacOS/. I've tried both http://packages.ntop.org/MacOS/ntopng-4.1.200506.pkg and http://packages.ntop.org/MacOS/ntopng-4.1.200427.pkg , but yet no web GUI is present on http://127.0.0.1:3000. I made sure to have Redis installed and running (through HomeBrew) prior to running the ntopng install.

```
$ lsof -nP -iTCP:6379 | grep LISTEN
redis-ser  457 apickler    6u  IPv4 0x678929914b86e957      0t0  TCP 127.0.0.1:6379 (LISTEN)

$ ps -aef | grep redis
  501   457     1   0  3:22PM ??         0:00.49 /usr/local/opt/redis/bin/redis-server 127.0.0.1:6379
  501  1880  1528   0  3:39PM ttys000    0:00.00 grep --color=auto redis
```

No app is running on port 3000, and there is no `ntopng` process running.

**Comment by lucaderi** [comment]
@BigGillyStyle Can you please open a shell and type /usr/local/bin/ntopng /usr/local/etc/ntopng/ntopng.conf and report the output?

**Comment by BigGillyStyle** [comment]
> @BigGillyStyle Can you please open a shell and type /usr/local/bin/ntopng /usr/local/etc/ntopng/ntopng.conf and report the output?

```
$ /usr/local/bin/ntopng /usr/local/etc/ntopng/ntopng.conf
08/Jul/2020 16:36:26 [Ntop.cpp:212] ERROR: Unable to open lock file: Permission denied
```

**Comment by lucaderi** [comment]
I apologise for the delay. Can you please first update to http://packages.ntop.org/MacOS/ntopng-4.1.200803.pkg and report if working? If not please do "sudo /usr/local/bin/ntopng /usr/local/etc/ntopng/ntopng.conf"

Note that ntopng starts as a service and thus the above command is just for debugging purpose.

**Comment by BigGillyStyle** [comment]
> I apologise for the delay. Can you please first update to http://packages.ntop.org/MacOS/ntopng-4.1.200803.pkg and report if working? If not please do "sudo /usr/local/bin/ntopng /usr/local/etc/ntopng/ntopng.conf"
> 
> Note that ntopng starts as a service and thus the above command is just for debugging purpose.

Yes...that fixed things for me.  Thanks @lucaderi
