### ISSUE TITLE
RADIUS support disappeared?

### ISSUE THREAD

**Issue by cjwbath** [ntop/ntopng#4117]
I updated to ntopng Enterprise M Edition v.4.0.200704 (and the underlying OS to Debian 10) and now I don't seem to have RADIUS authentication option available any more in preferences:

![image](https://user-images.githubusercontent.com/40788773/86886730-5987a500-c0ef-11ea-9c87-e26f8baf0b25.png)

Is there some dependency I need to install?

**Comment by simonemainardi** [comment]
debian10 release was not compiled with radius support which has now been added. Please, hold on a couple of hours for new builds to be generated, update, and try again.
