### ISSUE TITLE
NetBIOS.SMBv23 alert

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#4119]
Alert say SMVv23 on non standard port even if it's using 445.

https://docs.microsoft.com/en-us/windows-server/storage/file-server/best-practices-analyzer/smb-open-file-sharing-ports

**Comment by simonemainardi** [comment]
can you add a pcap capture and a screenshot of the alert?

**Comment by simonemainardi** [comment]
any news?

**Comment by bpersonick** [comment]
This is incredibly annoying we're spammed with thousands of these each day, when could this be resolved?  Is there a way I can removed just this somehow without removing others?

![2020-08-11 17_32_02-ntopng - Flows](https://user-images.githubusercontent.com/41927875/89951042-b566b180-dbf8-11ea-8a30-997f419c60c0.png)

**Comment by simonemainardi** [comment]
can any of you guys provide a pcap capture of this NetBIOS.SBMv23 which is causing this?

**Comment by lucaderi** [comment]
Fixed by https://github.com/ntop/nDPI/commit/9edddee0b7e63ff4fd6e5c19156e422d5712375c

New builds will be available within one hour now
