### ISSUE TITLE
Change Column of IP_SRC_ADDR and IP_DST_ADDR in MySQL?

### ISSUE THREAD

**Issue by ftraybird** [ntop/ntopng#412]
I am using ntopng to save the flows to MySQL but these Columns field type are Interger and I believe I need them changed to Text so I can see what the IP addresses are.

How can I modify the field types of these 2 columns so I can see the source and destination IPs?

Thanks!

**Comment by ftraybird** [comment]
For example, instead of 10.0.0.1 I see 167772161 in the MySQL db when I search the db.

**Comment by simonemainardi** [comment]
use MySQL `INET_NTOA` to get an ascii representation of IPv4 addresses (http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html#function_inet-ntoa)

**Comment by ftraybird** [comment]
Thank you!  exactly what I am looking for; but, I want the data to go into MySQL from ntopng and stay in the table as an IP address so I can easily export the db to create reports for the client.

Is there a way to have MySQL just store what it receives from ntopng which is an IP and not convert it to a number so I have to convert it back to an IP?

Thanks again!

**Comment by simonemainardi** [comment]
duplicate of #414
