### ISSUE TITLE
Add ability to select the SNMP pool when adding new devices

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4123]
Same as #3858 add in 
![Screen Shot 2020-07-13 at 13 04 04](https://user-images.githubusercontent.com/4493366/87297840-62221600-c509-11ea-8d43-b5b54ea1b6a0.png)

a new drop down field for selecting the SNMP pool to which new devices will be bound.

**Comment by gabryon99** [comment]
<img width="798" alt="Screenshot 2020-07-13 at 15 19 46" src="https://user-images.githubusercontent.com/14114916/87308987-4aa05880-c51c-11ea-8564-697ead4880c6.png">

The select has been added as request. Each entry contains a SNMP Pool Name

**Comment by simonemainardi** [comment]
make the dropdown genration re-usable to that it can be used also to generate the dropdown of https://github.com/ntop/ntopng/issues/3858 and to add all the shortcuts as described in https://github.com/ntop/ntopng/issues/4093

**Comment by gabryon99** [comment]
<img width="897" alt="Screenshot 2020-07-15 at 11 01 22" src="https://user-images.githubusercontent.com/14114916/87525981-86f1c700-c68a-11ea-8ecc-ecd996d6786f.png">

A Select has been added and the binding has been done as described by https://github.com/ntop/ntopng/issues/4129
