### ISSUE TITLE
ClearOS integration

### ISSUE THREAD

**Issue by Zhrebec** [ntop/ntopng#4125]
Hi!
I was able to install and make NtopNG work on ClearOS. Then I got flooded over email by failed check-update notifications. I have corrected the script to also allow "ClearOS" next to the "CentOS" keyword for distribution/package manager matching. 
Could you please make this official as ClearOS is based off of Centos for now?

**Comment by lucaderi** [comment]
Please send us a pull request with changes. At the moment we don't have plans for ClearOS but if we can incorporate the chances to support via CentOS that is something we can consider
