### ISSUE TITLE
Confirm message is not localised as it should

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4126]
![Screen Shot 2020-07-13 at 14 31 31](https://user-images.githubusercontent.com/4493366/87304755-98fe2900-c515-11ea-9eee-7318ecc805ba.png)

**Comment by gabryon99** [comment]
The alert has been removed. See the commit for further details: https://github.com/ntop/ntopng/commit/48dc7e1a93f8afaaf3e4b76d361a5a9dd30c8851
