### ISSUE TITLE
Modal dialogs are not stateless as they should

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4127]
Modal dialogs are stateful even though they should be stateless Example
SNMP -> Add Device (+)
![Screen Shot 2020-07-13 at 14 32 28](https://user-images.githubusercontent.com/4493366/87304866-cc40b800-c515-11ea-821a-6de603cedeb3.png)
the following screen is shown. Then change the drop down menu to a different value as in the example

![Screen Shot 2020-07-13 at 14 32 15](https://user-images.githubusercontent.com/4493366/87304907-debaf180-c515-11ea-93d1-29c2df390f65.png)

At this point close the dialog (top right X icon). Now check the Add Device button again and the page below

![Screen Shot 2020-07-13 at 14 32 15](https://user-images.githubusercontent.com/4493366/87304950-f85c3900-c515-11ea-827e-ce5f48ae6dd3.png)

is shown instead of

![Screen Shot 2020-07-13 at 14 32 28](https://user-images.githubusercontent.com/4493366/87304967-fdb98380-c515-11ea-9a58-82ed03371504.png)

This defect is present in ALL model dialogs (i.e. outside of SNMP) as they are not properly reset

**Comment by gabryon99** [comment]
![ezgif-2-9f11d64a4cc1](https://user-images.githubusercontent.com/14114916/87311245-4a558c80-c51f-11ea-8c7f-f1651955e7c5.gif)

Now the modals (used with the ModalHandler plugin) are stateless. I also removed the `is-valid` class when the input are valid.
