### ISSUE TITLE
Rework Import/Export UI

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4128]
Currently import/export buttons are spread across the user interface, Example
- SNMP
- Script configurations
- Pools

just to mention a few. At the same time the backup is implemented in a non consistent way

![Screen Shot 2020-07-13 at 14 36 29](https://user-images.githubusercontent.com/4493366/87305147-4c671d80-c516-11ea-9303-8d669f55762b.png)

- Export does not open a dialog but it downloads the file
- Import is not implemented but it is a link to a document pagae

This ticket requests to 
- create a page for import/export
- remove all import/button icons in pages and make them anchors to this new page
- add checks on the import/export code so that by mistake it is not possible to export most pools and import them under SNMP
- add the ability to import/export various ntopng elements as well the whole configuration as today

**Comment by simonemainardi** [comment]
> create a page for import/export

page will have a structure similar to

![image](https://user-images.githubusercontent.com/3397663/87321569-affc4580-c52c-11ea-950d-58ed13d537c3.png)


Nested structure is necessary as (SNMP pools depend on SNMP devices; Active Monitoring pool depend on Active monitoring entries. Items will be:

- [ ] User script configurations
- [ ] SNMP devices
  - [ ]  Pools
- [ ] Active monitoring
  - [ ] Pools
- [ ] Interface Pools
- [ ] Host Pools
- [ ] Local Network Pools



Exported data will be a JSON structured in sections:

```
{
  user_scripts: {...},
  snmp_devices: {
    devices: {...},
    pools: {...}
  },
  active_monitoring: {
    am_hosts: {...},
    pools: {...}
  },
  ...
}
```

A lua class `modules/import_export/base_import_export.lua` and subclasses `modules/import_export/user_scripts.lua`, `modules/import_export/snmp_devices.lua`, `active_monitoring.lua`, `host_pools.lua`, etc. will be implemented. Each subclass will have methods `:import()` and `:export()` to do the necessary sanity checks and perform the actual import/export using existing modules.

Notes on import:
1. A JS will do preliminary checks on the POSTed JSON and show the user a summary of the import process which is being performed (import XXX SNMP devices, YYY pools, etc).
2. Upon user confirmation, the import process will take place. SNMP devices and active monitoring will be imported as-is (i.e., no reachability tests), interface pooks will only be imported if existing on the target system.
3. The user will receive a confirmation message after the import procedure has terminated successfully.

Import export will be performed using two RESTful endpoints
- `import.lua`. This will receive a JSON as input
- `export.lua`. This will accept a list of 'items' to be exported

**Comment by simonemainardi** [comment]
A single page backup/restore will be implemented.

A dropdown will allow the user to chose what to export, ,e.g., SNMP devices, active monitoring, ..., All.

Two buttons will be shown at the bottom of the page, namely, "import" and "export".

**Comment by lucaderi** [comment]
In short create a new page with

a) dropdown menu with the following entries
- SNMP
- Script configurations
- Pools/Endpoints/Recipients
- Active Monitoring

b) 2 buttons
- Import
- Export

**Comment by gabryon99** [comment]
The GUI for the page has been implemented (see the screenshot below):
<img width="1692" alt="Screenshot 2020-08-19 at 15 50 49" src="https://user-images.githubusercontent.com/14114916/90643321-c3898300-e233-11ea-84b5-de4991a2351e.png">

The only thing to do is to replace the href for the export button (contained in file `import_export_config.template`)
See the commit: https://github.com/ntop/ntopng/commit/b7b17d9d1cbd1f052c37592e1bd615f841ce03d6

**Comment by simonemainardi** [comment]
this ticket depends on https://github.com/ntop/ntopng/issues/4475

**Comment by cardigliano** [comment]
REST endpoints for import/export of the user script configuration are available at:

lua/rest/v1/export/scripts/config.lua (an optional download parameter can be provided to download a file without the rest envelope)
lua/rest/v1/import/scripts/config.lua (an exported JSON should be provided, without the rest envelope)

They can already be used to test the GUI.

**Comment by gabryon99** [comment]
The new page has been implemented:

<img width="1684" alt="Screenshot 2020-10-02 at 17 00 55" src="https://user-images.githubusercontent.com/14114916/94938230-d8af2e00-04d0-11eb-96af-95e3b65f4aab.png">

JS Logic in the commit: https://github.com/ntop/ntopng/commit/b0d481a3262671cae879fb5b5f7cbe342200b500
