### ISSUE TITLE
SNMP generates periodic traffic peaks on Redis

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4130]
System with 120 SNMP devices, most of them unreachable. What happens periodically is this:

![image](https://user-images.githubusercontent.com/3397663/87403982-d7e7b980-c5bd-11ea-982c-0836297bea58.png)

Intense activity on cachedsnmp.xxx.mib. Even repeated multiple times for the same device xxx.

**Comment by lucaderi** [comment]
I have checked this issue with the current codebase and
- no duplicate SNMP devices are polled
- only a minimum amount of keys is read: those that are needed for a difference such as counters
- unresponsive devices are not redis-polled as they are discarded before the poll starts

I believe you have used an old code version.

Instead please have a look at #4271
