### ISSUE TITLE
IP_SRC_ADDR and IP_DST_ADDR stay in IP Format in MySQL while writing to db

### ISSUE THREAD

**Issue by ftraybird** [ntop/ntopng#414]
I am using ntopng to save the flows to MySQL but these Columns field type are Interger and I believe I need them changed to Text so I can see what the IP addresses are.

How can I modify the field types of these 2 columns so I can see the source and destination IPs?

For example, instead of 10.0.0.1 I see 167772161 in the MySQL db when I search the db.

I ran these commands on the table columns to try and change the field type so new data would stay in IP format but it didn't work.

ALTER TABLE flowsv4_6 MODIFY IP_SRC_ADDR VARCHAR(100) NOT NULL;
ALTER TABLE flowsv4_6 MODIFY IP_DST_ADDR VARCHAR(100) NOT NULL;

I want the data to go into MySQL from ntopng and stay in the table as an IP address so I can easily export the db to create reports for the client.

Is there a way to have MySQL just store what it receives from ntopng which is an IP and not convert it to a number so I have to convert it back to an IP?

Thanks to simonemainardi this is what I am looking for but just in the db already so I don't have to convert.
http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html#function_inet-ntoa

Thanks!

**Comment by lucaderi** [comment]
@ftraybird I think the way it is implemented is correct as it allows us to play with subnets etc. Converting it to strings takes more space and prevents us from handling it with subnets. As @simonemainardi pointed out you can use INET_NTOA() to do what you are looking for.

Don't forget to star ntopng on github. Thanks.

**Comment by ftraybird** [comment]
Makes sense and now I understand all those reasons. 

I'll just figure out a way to run INET_NTOA() on the columns so I can convert them before any kind of reporting. Or maybe I can convert outside of MySQL. 

Ntopng is starred by us and i want to thank you and everyone here for all the great work everyone puts into such an amazing netflow analysis package. 

Thanks again!

**Comment by simonemainardi** [comment]
Hi,

I don’t know why you need to store ip strings rather than integers. Integers take less space and querying them is much more efficient. String conversion it’s just a matter of using the INET_NTOA at query time.

Nevertheless, you should not change mysql column types of the tables used by ntopng. This will very likely cause unexpected behavior. If you still want ip strings in the database, you should create a MySQL VIEW over the ntopng tables of interest. So for example the VIEW will contain the INET_NTOA conversion in its definition so that you don’t even need to write it in your queries.

Simone

**Comment by ftraybird** [comment]
Thanks Luca.  Thanks Simone.  I understand now and you're exactly right on how you are storing the IP addresses.  As you stated I will just convert if I need to later for a report or just create a MySQL view.  I didn't realize at the open of this issue that storing IPs as a number has such benefits such as searching ranges, subnets, and uses less storage.  Thanks again!  Nick
