### ISSUE TITLE
Error during pid file delete

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4143]
During shutdown the following message shows up
15/Jul/2020 00:22:37 [Ntop.cpp:2475] Deleted PID /var/run/ntopng.pid: [rc: -1][Permission denied]

but the file is in good shape and it should be deleted

[root@ntopng ~]# ps auxw|grep ntopng
ntopng   20226 28.2  0.5 3487624 365524 ?      Ssl  00:30   0:03 /usr/local/bin/ntopng /run/ntopng.conf

[root@ntopng ~]# ls -l /var/run/ntopng.pid
-rw-r--r--. 1 ntopng ntopng 6 Jul 15 00:07 /var/run/ntopng.pid

**Comment by simonemainardi** [comment]
The file cannot be deleted as it is under `/var/run` which, in turn, is a symlink to `/run`, which is not writable by user `ntopng`. Privileges of the file are not enough as it is required to have also write permission on the containing directory.
