### ISSUE TITLE
Inconsistent behaviour of SNMP pool members UI

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4146]
Starting with 

![image](https://user-images.githubusercontent.com/3397663/87569280-2b91fa00-c6c7-11ea-9aa6-7053d8ccbbe3.png)

Click on Edit, this modal opens up

![image](https://user-images.githubusercontent.com/3397663/87569326-3e0c3380-c6c7-11ea-9b80-ffda157a1c31.png)

If I want to remove a device from the pool, I click on it but the click doesn't highlight the clicked device. It highlights the device below the clicked one (in the image I clicked on 192.168.2.1)

![image](https://user-images.githubusercontent.com/3397663/87569497-80357500-c6c7-11ea-8c4a-4288a13b2507.png)

Now, if I click edit, the clicked device no longer shows up in the members list 

![image](https://user-images.githubusercontent.com/3397663/87569660-c1c62000-c6c7-11ea-9199-1abe22ca6d3c.png)

However, if I open the edit again, 192.168.2.1 is still listed as member:

![image](https://user-images.githubusercontent.com/3397663/87569720-d4d8f000-c6c7-11ea-889d-bce784719a43.png)

Only a page refresh makes the modal consistent

![image](https://user-images.githubusercontent.com/3397663/87569763-e5896600-c6c7-11ea-8c7c-158377294492.png)

**Comment by simonemainardi** [comment]
this also suggests the modal are still stateful and so https://github.com/ntop/ntopng/issues/4127 is not completed

**Comment by gabryon99** [comment]
If you hold `Command` key while doing:
"_If I want to remove a device from the pool, I click on it but the click doesn't highlight the clicked device. It highlights the device below the clicked one (in the image I clicked on 192.168.2.1)_"

then the `multiselect` selects the complimentary entries. This only happens when there are already pre-selected entries.

**Comment by gabryon99** [comment]
The inconsistent behavior has been corrected. The problem was caused by a missing name field inside `all_members` object, which contains references to get a member's name.

![ezgif-2-7021b9e31f6c](https://user-images.githubusercontent.com/14114916/87652113-17e0a500-c754-11ea-9925-90c1b8a9ea69.gif)

**Comment by simonemainardi** [comment]
same behavior also for pools of other types

**Comment by simonemainardi** [comment]
Still inconsistent. If I open the edit modal, I want to see the current members highlighted in blue, not disabled in grey.

Current behavior:

![image](https://user-images.githubusercontent.com/3397663/87660713-ce965280-c75f-11ea-8d3b-c6bbeb1da6b9.png)

If I click on edit I get the two members disabled, in grey.

![image](https://user-images.githubusercontent.com/3397663/87660678-bf170980-c75f-11ea-9b46-adf5bfae3098.png)


Expected behavior is to see the current two members highlighted in blue (so I can manually de-select any of them):


![image](https://user-images.githubusercontent.com/3397663/87660828-fab1d380-c75f-11ea-8b20-be07bdfab8ed.png)

---

In addition. The same bug is still present. Empty members, pool name still appearing inside the modal

![image](https://user-images.githubusercontent.com/3397663/87661141-6eec7700-c760-11ea-88e3-870dea295618.png)

**Comment by simonemainardi** [comment]
now fixed
