### ISSUE TITLE
Raspberry stable repository

### ISSUE THREAD

**Issue by erathaowl** [ntop/ntopng#4147]
Good morning,
looking at your repositories for ntopng on raspberry platform _(buster or stretch is the same)_ I found that `http://packages.ntop.org/apt/buster_pi/armhf/` (dev repo) return the version 4.1.XXX, instead `http://packages.ntop.org/apt-stable/buster_pi/armhf/` (stable repo) doesn't contain any deb.
Is correct?

**Comment by lucaderi** [comment]
We do not maintain a stable Raspberry repository (nor for Windows and MacOS), but only for Ubuntu and CentOS
