### ISSUE TITLE
No DNS stats when collecting flows

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4148]
![Screen_Shot_2020-07-17_at_09_26_57](https://user-images.githubusercontent.com/4493366/87760669-62275c00-c810-11ea-94ea-567a2fd78406.png)

When ntopng collects flows from nProbe over ZMQ, even if the nProbe template (-T) contains @NTOPNG@ and %DNS_XXXX IEs, the above form is empty

Example
-T="@NTOPNG@ %EXPORTER_IPV4_ADDRESS %DNS_QUERY %DNS_QUERY_ID %DNS_QUERY_TYPE %DNS_RET_CODE %DNS_NUM_ANSWERS %DNS_TTL_ANSWER %DNS_RESPONSE"

**Comment by Eugene-Prokhorenko** [comment]
The same for DHCP.

**Comment by simonemainardi** [comment]
Fixed. Remember that hosts must be local to have DNS stats.

```
./ntopng -i ../dns.pcap -i tcp://127.0.0.1:5556c -m "0.0.0.0/0"
```

ZMQ (JSON format ` sudo ./nprobe -i ~/dns.pcap --zmq tcp://127.0.0.1:5556 --zmq-probe-mode -T "@NTOPNG@ %DNS_QUERY %DNS_QUERY_ID %DNS_QUERY_TYPE %DNS_RET_CODE %DNS_NUM_ANSWERS %DNS_TTL_ANSWER %DNS_RESPONSE" -D t -P /tmp/ --zmq-format j`)

![image](https://user-images.githubusercontent.com/3397663/88775471-09977d80-d185-11ea-9475-909a72543c14.png)

ZMQ (TLV format ` sudo ./nprobe -i ~/dns.pcap --zmq tcp://127.0.0.1:5556 --zmq-probe-mode -T "@NTOPNG@ %DNS_QUERY %DNS_QUERY_ID %DNS_QUERY_TYPE %DNS_RET_CODE %DNS_NUM_ANSWERS %DNS_TTL_ANSWER %DNS_RESPONSE" -D t -P /tmp/ --zmq-format t`)

![image](https://user-images.githubusercontent.com/3397663/88775498-0ef4c800-d185-11ea-8f86-2b114c70bff4.png)

Regular packet interface

![image](https://user-images.githubusercontent.com/3397663/88775780-6bf07e00-d185-11ea-947f-7ec8e8cc697b.png)

Pcap enclosed for reference 

[dns.pcap.zip](https://github.com/ntop/ntopng/files/4993588/dns.pcap.zip)
