### ISSUE TITLE
Historical Data on Windows?

### ISSUE THREAD

**Issue by ftraybird** [ntop/ntopng#415]
http://www.ntop.org/ntopng/exploring-historical-data-using-ntopng/

Im running the following command in Windows 7

ntopng /c -i tcp://127.0.0.1:5556 -F "mysql;db_ip_address;dbname;tablename;account;password"

I have no historical data showing like explained in the above article.

What am I missing?

Thanks!

**Comment by lucaderi** [comment]
You need the pro version for historical reports
