### ISSUE TITLE
nEdge Test Policy Spinner Broken

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4151]
- Search results appear top-right, far from the search box
- A blue text spins with the spinner

![image](https://user-images.githubusercontent.com/3397663/87766330-45435680-c819-11ea-8e9f-5bbb930fba22.png)

**Comment by simonemainardi** [comment]
@gabryon99 to setup nEdge, please prepare a VM with ubuntu16.

**Comment by gabryon99** [comment]
<img width="955" alt="Screenshot 2020-07-27 at 15 29 06" src="https://user-images.githubusercontent.com/14114916/88547369-ea321080-d01d-11ea-8502-f83f512248aa.png">

Spinning text fixed
