### ISSUE TITLE
No HTTP stats when collecting flows bug

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4152]
Same as #4148 but for HTTP.

-T "@NTOPNG@ %HTTP_URL %HTTP_RET_CODE %HTTP_REFERER %HTTP_UA %HTTP_MIME %HTTP_HOST %DNS_QUERY %DNS_QUERY_TYPE %DNS_RET_CODE %DNS_NUM_ANSWER" will reproduce both issues simultaneously

**Comment by simonemainardi** [comment]
Fixed.

```
./ntopng -i tcp://127.0.0.1:5556c
```

JSON (`./nprobe -i ~/ntopng/single_http.pcap --zmq tcp://127.0.0.1:5556 --zmq-probe-mode -T "@NTOPNG@ %HTTP_RET_CODE %HTTP_REFERER %HTTP_UA %HTTP_MIME" -D t -P /tmp/ --zmq-format j`):

![image](https://user-images.githubusercontent.com/3397663/88766185-e4504280-d177-11ea-8d1a-aa6cf2c3971c.png)


TLV (`sudo ./nprobe -i ~/ntopng/single_http.pcap --zmq tcp://127.0.0.1:5556 --zmq-probe-mode -T "@NTOPNG@ %HTTP_RET_CODE %HTTP_REFERER %HTTP_UA %HTTP_MIME" -D t -P /tmp/ --zmq-format t`):

![image](https://user-images.githubusercontent.com/3397663/88770933-cc2ff180-d17e-11ea-8985-64a5d1f8b32c.png)

Pcap enclosed for reference

[single_http.pcap.zip](https://github.com/ntop/ntopng/files/4993359/single_http.pcap.zip)
