### ISSUE TITLE
Intermittent 400 error from elastic search

### ISSUE THREAD

**Issue by mroe1234** [ntop/ntopng#4153]
I'm trying to track down the root cause of continuous export drops.  Running ntopng straight from the command line as:

    ntopng -G=/var/run/ntopng.pid -i tcp://127.0.0.1:5556 -m 192.168.0.0/16 -F "es;_doc;ntopng-%Y.%m.%d;http://elastic.home.local:9200/_bulk;" -X 3000000 -v 4 -x 1000000

I noticed this:

    [Utils.cpp:1286] [JSON] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The bulk request must be terminated by a newline [\\n]"}],"type":"illegal_argument_exception","reason":"The bulk request must be terminated by a newline [\\n]"},"status":400}
    [Utils.cpp:1447] Posted JSON to http://elastic.home.local:9200/_bulk
    [Utils.cpp:1384] [NAMELOOKUP_TIME 0.00][CONNECT_TIME 0.00][APPCONNECT_TIME 0.00][PRETRANSFER_TIME 0.00][REDIRECT_TIME 0.00][STARTTRANSFER_TIME 0.00][TOTAL_TIME 0.01]
    [ElasticSearch.cpp:179] Sent 1621 flow(s) to ES
    [ElasticSearch.cpp:168] ES: Buffered request with 1494 flows (961794 bytes)

We are running elastic search 7.7 for reference.

**Comment by simonemainardi** [comment]
any suggestion to reproduce?

**Comment by lucaderi** [comment]
Works for us, closed for inactivity
