### ISSUE TITLE
Implement Interface Alert Shortcuts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4157]
The way alerts have been implemented is optimal for ntopng but sub-optimal for the user. For instance for triggering an alert when interface traffic exceeds X Gbit, a user must
- configure interface pool
- configure recipient/notification endpoint
- configure the user script for triggering an alert

All this is crazy complicated. It is requested to implement a "shortcut-like" feature in the Interface page so that ntopng hides the complexity of this procedure and set the alert. Example *in one step* set an alert for sending mail to user@domain when Interface threshold X is exceeded.

**Comment by simonemainardi** [comment]
superseded by https://github.com/ntop/ntopng/issues/4659
