### ISSUE TITLE
Allow SNMP devices to be filtered by pool

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4159]
Add an extra dropdown next to the device filter in

![image](https://user-images.githubusercontent.com/3397663/87924714-8ccb1c00-ca7f-11ea-9a7b-62646cd6363d.png)

**Comment by gabryon99** [comment]
Can the pool name, for the snmp device, be returned from the request: `/lua/pro/enterprise/get_snmp_devices_list.lua`?

**Comment by cardigliano** [comment]
@gabryon99 get_snmp_devices_list.lua now returns column_pool_{id,name}

**Comment by gabryon99** [comment]
Thanks @cardigliano! The filter has been implemented: 
<img width="1306" alt="Screenshot 2020-07-22 at 17 17 13" src="https://user-images.githubusercontent.com/14114916/88194490-31478c80-cc3f-11ea-8989-7c81f3eeb32d.png">
