### ISSUE TITLE
Wrong fields name in ES with ZMQ between nProbe and ntopng

### ISSUE THREAD

**Issue by lzalewsk** [ntop/ntopng#416]
Hi,
In case of nProbe and ntopng communication via ZMQ witch node should dump data to Elasticsearch?
In case of following command:
`nprobe -i eth5 --elastic "eth5;nprobedev2-%Y.%m.%d;http://localhost:9200/_bulk;" -T "%FLOW_ID %FLOW_START_SEC %FLOW_END_SEC %FLOW_START_MILLISECONDS %FLOW_END_MILLISECONDS %FLOW_ACTIVE_TIMEOUT %FLOW_INACTIVE_TIMEOU %FLOWS %IPV4_SRC_ADDR %L4_SRC_PORT %IPV4_DST_ADDR %L4_DST_PORT %PROTOCOL %IN_BYTES %OUT_BYTES %FIRST_SWITCHED %LAST_SWITCHED %IN_PKTS %OUT_PKTS %IP_PROTOCOL_VERSION %APPLICATION_ID %L7_PROTO_NAME %ICMP_TYPE %SRC_IP_COUNTRY %DST_IP_COUNTRY %APPL_LATENCY_MS %IN_SRC_MAC %OUT_DST_MAC %SRC_VLAN %TCP_FLAGS %IPV4_NEXT_HOP %FRAME_LENGTH %HTTP_URL %HTTP_METHOD %HTTP_RET_CODE %HTTP_REFERER %HTTP_UA %HTTP_MIME %HTTP_HOST %HTTP_SITE %HTTP_FBOOK_CHAT %DNS_QUERY %DNS_QUERY_ID %DNS_QUERY_TYPE %DNS_RET_CODE %DNS_NUM_ANSWERS %DNS_TTL_ANSWER %NUM_PKTS_UP_TO_128_BYTES %NUM_PKTS_128_TO_256_BYTES %NUM_PKTS_256_TO_512_BYTES %NUM_PKTS_512_TO_1024_BYTES %NUM_PKTS_1024_TO_1514_BYTES %NUM_PKTS_OVER_1514_BYTES" --zmq "tcp://*:5556"`

In ES I received:
![fieldsinesindex](https://cloud.githubusercontent.com/assets/14045566/13202713/928f2bbc-d8a4-11e5-89e4-fa0f3c895f4e.png)

If on nProbe I use
`nprobe -i eth5 --zmq "tcp://*:5556"`
and on ntopng:
`ntopng -i tcp://localhost:5556 -F "es;eth5;nprobedev3-%Y.%m.%d;http://localhost:9200/_bulk;"`
In ES I have some json.5,json.42 etc fields
![ntopngexport](https://cloud.githubusercontent.com/assets/14045566/13202796/d66f90e4-d8a7-11e5-886e-b28014e97a87.png)

It's a little strange.
What I'm doing wrong?

**Comment by lucaderi** [comment]
nprobe should dump to ELK. Please check who is sending these jsonX fields

**Comment by lzalewsk** [comment]
The json-labels
nprobe [....] --json-labels
solves the problem.
