### ISSUE TITLE
Allow active monitoring to be filtered by pool

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4160]
Add an extra dropdown next to

![image](https://user-images.githubusercontent.com/3397663/87924785-a5d3cd00-ca7f-11ea-805e-412d69616429.png)

**Comment by gabryon99** [comment]
The filter menu has been added:
<img width="1306" alt="Screenshot 2020-07-22 at 17 18 43" src="https://user-images.githubusercontent.com/14114916/88194700-66ec7580-cc3f-11ea-9e84-880ffca6bd6f.png">

**Comment by gabryon99** [comment]
See the commit: https://github.com/ntop/ntopng/commit/5ad922c722af6ee38c1f4dbaf28cfbd8768c9eb5

**Comment by tano46** [comment]
all references to pools and active monitoring has to be hidden in edge version where pools are not present
