### ISSUE TITLE
Write 'and X other' when pool members exceed 10

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4162]
When there are more than 10 members in a pool, it is requested to modify the list of members with a text saying:

"member0, member1, member2, member2, member4, member5, member6, member7, member8, member9 and XXX other"

where XXX is total - 10.

**Comment by gabryon99** [comment]
<img width="1025" alt="Screenshot 2020-07-20 at 12 23 10" src="https://user-images.githubusercontent.com/14114916/87927627-c7cf4e80-ca83-11ea-81d7-e7f0ec0267d5.png">

**Comment by gabryon99** [comment]
If the members are more than 10 then shows the label, see the commit: https://github.com/ntop/ntopng/commit/f168f16304ca78eb86b58a06924cdf32465ddd79
