### ISSUE TITLE
Use 'User Script Configuration' In place of 'Configuration Name'

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4163]
in 

![image](https://user-images.githubusercontent.com/3397663/87925830-26df9400-ca81-11ea-99cf-6e35c845ca88.png)

**Comment by simonemainardi** [comment]
same label must be used in the table:

![image](https://user-images.githubusercontent.com/3397663/87925940-4c6c9d80-ca81-11ea-8cb2-82b847c74d4c.png)

**Comment by gabryon99** [comment]
<img width="855" alt="Screenshot 2020-07-21 at 11 15 44" src="https://user-images.githubusercontent.com/14114916/88036211-87370a00-cb43-11ea-9097-b82d205fd8a7.png">

Label renamed as requested. See the commit: https://github.com/ntop/ntopng/commit/edf11bebe163f679535f295bc957d94493c7da60
