### ISSUE TITLE
VLAN must be optional for host pool members

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4165]
currently it's not optional for networks:

![image](https://user-images.githubusercontent.com/3397663/87927407-732bd380-ca83-11ea-933e-db35f80a26a9.png)

**Comment by gabryon99** [comment]
Done, see the commit: https://github.com/ntop/ntopng/commit/0e985c4561a92e20338b414b445ad10c5a9b8283

**Comment by simonemainardi** [comment]
Now unable to add a network member with or withouth a VLAN

![image](https://user-images.githubusercontent.com/3397663/87938125-59e05280-ca96-11ea-83ee-ed88a0834750.png)

![image](https://user-images.githubusercontent.com/3397663/87938177-6d8bb900-ca96-11ea-91a8-12d8171cb94b.png)

**Comment by gabryon99** [comment]
Fixed in: https://github.com/ntop/ntopng/commit/3548d54583bc5b52eb63974adca46d686f28a99a

**Comment by simonemainardi** [comment]
next time test before marking as 'waiting for review'
