### ISSUE TITLE
Better layout and space of form fields

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4166]
Fields are huge with reference to the data they contain.

![image](https://user-images.githubusercontent.com/3397663/87927732-f816ed00-ca83-11ea-8e2e-54ccd2cc981e.png)

They must be adjusted and the layout of the modal reviewed

Better something like

![image](https://user-images.githubusercontent.com/3397663/87927617-c43bc780-ca83-11ea-8707-21c95208ab57.png)

**Comment by gabryon99** [comment]
Now the layout is more similar to the screenshot above. See the commit: https://github.com/ntop/ntopng/commit/29615f109fc9fa4622c4c8e387b6ec0c72a3485b
