### ISSUE TITLE
Broken "Add Active Monitoring Pool"

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4167]
Broken "Add Active Monitoring Pool" link in 

![image](https://user-images.githubusercontent.com/3397663/87928097-8b502280-ca84-11ea-99f7-aa4291b2ae98.png)

which brings to

![image](https://user-images.githubusercontent.com/3397663/87928140-9c992f00-ca84-11ea-9da3-d1372802073e.png)

**Comment by gabryon99** [comment]
Fixed, reload the plugins to see the new link: https://github.com/ntop/ntopng/commit/ea35d1b0a875fcd66b75b9d9c1eb5afedb91795e
