### ISSUE TITLE
Broken "Add a new SNMP Pool" link

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4168]
Link in

![image](https://user-images.githubusercontent.com/3397663/87928439-1d582b00-ca85-11ea-9a75-8c34d8b80506.png)

Brings to a broken page

![image](https://user-images.githubusercontent.com/3397663/87928406-10d3d280-ca85-11ea-8652-1fcc85dd5e86.png)

**Comment by gabryon99** [comment]
<img width="1025" alt="Screenshot 2020-07-20 at 14 16 21" src="https://user-images.githubusercontent.com/14114916/87936703-978fac00-ca93-11ea-984b-80ce2003e38e.png">

Fixed too.
