### ISSUE TITLE
Refresh (or clean) modal contents after addition of a pool

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4169]
If I click the modal, I can add a pool in another page.

![image](https://user-images.githubusercontent.com/3397663/87928664-7627c380-ca85-11ea-8ac7-b7d75f68d334.png)

Then if I press the back button, I'm back to the modal but it's contents are not refreshed. The created pool is still missing. It is requested to either clean and close the modal automatically or to refresh its contents but it must stay consistent

**Comment by gabryon99** [comment]
Done it, now there is a button near the Edit Pools Link that reload the select: https://github.com/ntop/ntopng/commit/64d7d749654039ad84e15002a77e9a8338f29ba5

**Comment by simonemainardi** [comment]
Something strange happens here:

I am here:

![image](https://user-images.githubusercontent.com/3397663/88342412-aa2e0d80-cd3f-11ea-8427-429f2823d059.png)

I select "edit pools" and go to page

![image](https://user-images.githubusercontent.com/3397663/88342490-c762dc00-cd3f-11ea-9a9f-c0e853bebd09.png)


Now, clicking on the browser "back" button, doesn't bring me back to the page with the modal open. It brings me to page without modal.

![image](https://user-images.githubusercontent.com/3397663/88342554-e3667d80-cd3f-11ea-8aca-51645ee5a97e.png)

Hence, the refresh button is useless as I have to reopen the modal and start over.

**Comment by gabryon99** [comment]
This behavior depends on the browser you are using. On `Firefox` when the back button is pressed the previous page will be reloaded. `Safari` instead hibernates the page until the user doesn't click the back button and the browser restores the previous hybrid page state.
