### ISSUE TITLE
Filtering issue by country

### ISSUE THREAD

**Issue by DigiAngel** [ntop/ntopng#417]
Topic says it....I'm unable to filter by almost all the counties on this screen:

![2016-02-22 12_17_27-welcome to ntopng - internet explorer](https://cloud.githubusercontent.com/assets/947191/13229566/e7ac0722-d95e-11e5-9af8-ede137b42cdd.jpg)

I get the below:

![2016-02-22 12_17_41-welcome to ntopng - internet explorer](https://cloud.githubusercontent.com/assets/947191/13229579/f1fb1a56-d95e-11e5-81a3-646fdc5ca7ae.jpg)

My settings:

![2016-02-22 12_16_53-welcome to ntopng - internet explorer](https://cloud.githubusercontent.com/assets/947191/13229557/db0f10a4-d95e-11e5-93f2-962150037549.jpg)

Version info:

```
v.2.3.160204 [Community Edition]
GIT rev:   dev:cb714019c7ff9436dc17644c19e01a0bae70dea3:20160204
```

Anything I can do to troubleshoot this?  Thank you.

**Comment by DigiAngel** [comment]
Thanks Luca!

**Comment by anrodriguezco** [comment]
Same issue Here, may I need to reinstall something in order to get this view working?
[here](http://prntscr.com/krha88) you'll see mi issue.

**Comment by simonemainardi** [comment]
@anrodriguezco please update ntopng to the latest 3.7 you are on 3.5
