### ISSUE TITLE
Editing an host pool name causes its members to disappear

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4170]
If I have an host pool with some members, and then I click edit to 'rename' the host pool, all its members disappear.

**Comment by gabryon99** [comment]
Fixed, the problem was in the request. Basically, because there weren't any members inside the modal an empty member list was sent to the endpoint. See the commit: https://github.com/ntop/ntopng/commit/1ecda696f98923682f076a3e2633503594c7b232
