### ISSUE TITLE
Member name inconsistent

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4171]
Member names shown in 

![image](https://user-images.githubusercontent.com/3397663/87929022-0fef7080-ca86-11ea-9b80-76703081b1a4.png)

Are not consistent. They MUST be shown equal to those shown in 

![image](https://user-images.githubusercontent.com/3397663/87929064-1f6eb980-ca86-11ea-9252-6e1d1478ba13.png)

**Comment by gabryon99** [comment]
Done, now the names are consistent between the pages. See the commit: https://github.com/ntop/ntopng/commit/691c139feff8def590aa81b5e029b009f6d49d55

**Comment by simonemainardi** [comment]
VLAN not shown, in this case there's no way to tell the vlan

![image](https://user-images.githubusercontent.com/3397663/87937842-c6a71d00-ca95-11ea-8396-7870269483b3.png)

**Comment by gabryon99** [comment]
Fixed as request, see the commit: https://github.com/ntop/ntopng/commit/f5e32bb53606df51c58c2d0c946d7567a1f25b07
