### ISSUE TITLE
Sort by pool member broken

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4172]
![image](https://user-images.githubusercontent.com/3397663/87937750-92336100-ca95-11ea-87ff-171867a240dc.png)

**Comment by simonemainardi** [comment]
don't forget that members can be also ipv6, networks and mac addresses.

**Comment by gabryon99** [comment]
The sorting has been fixed. Unfortunately, it's not possible to disable the ordering when there is no filter applied. See the commit: https://github.com/ntop/ntopng/commit/f94ce33334dc3843b5a830c3246c6c67f396ddc6
