### ISSUE TITLE
Wrong modal labels

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4173]
![image](https://user-images.githubusercontent.com/3397663/87939164-eb9c8f80-ca97-11ea-92fb-c5e5b1bb86c5.png)

- Modal title must be singular "Host"
- Name placeholder must be singulare and lowercase: "... host pool..."
- Name must be bold as mandatory field

**Comment by gabryon99** [comment]
Fixed, see commit: https://github.com/ntop/ntopng/commit/321e7ad156fb48fcf4a0ed8b050f14a6a42c39c4
