### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4175]
Broken "Edit Host Pools" in 

![image](https://user-images.githubusercontent.com/3397663/87940004-3074f600-ca99-11ea-9927-8dba1490d087.png)

Also in 

![image](https://user-images.githubusercontent.com/3397663/87940050-42ef2f80-ca99-11ea-8df9-e7f6e0dfcfa8.png)

As a side note, it must use the same symbol used to edit host pool members

**Comment by gabryon99** [comment]
The broken link has been fixed. See the commit: https://github.com/ntop/ntopng/commit/849e6b1acb9bb5e6b746cc0d7f9fdba6ec4bc745

**Comment by simonemainardi** [comment]
> As a side note, it must use the same symbol used to edit host pool members

didn't do as requested.

MUST use 

<img width="125" alt="image" src="https://user-images.githubusercontent.com/3397663/88039758-468dbf80-cb48-11ea-9ee8-2d5a868d014f.png">

In place of "+ Add new xxx" EVERYWHERE.

**Comment by gabryon99** [comment]
Rewrote: https://github.com/ntop/ntopng/commit/b83108e423863ca5902aa1efb7f46d661b52e71d
