### ISSUE TITLE
Notification Endpoints Buttons Inconsistent

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4176]
Need to change the following buttons according to the new format

![image](https://user-images.githubusercontent.com/3397663/87940621-30c1c100-ca9a-11ea-816c-42e8209e96fe.png)

**Comment by gabryon99** [comment]
<img width="1704" alt="Screenshot 2020-07-20 at 15 36 01" src="https://user-images.githubusercontent.com/14114916/87943721-b9daf700-ca9e-11ea-9ce3-0b59b8491cf3.png">

Fixed in: https://github.com/ntop/ntopng/commit/8f02fc9562c76132c3c15ce55f13b1c94b490ff1
