### ISSUE TITLE
Recipient Name missing from modal title

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4177]
![image](https://user-images.githubusercontent.com/3397663/87940861-8a29f000-ca9a-11ea-8237-0a20106c0e5f.png)

**Comment by simonemainardi** [comment]
same in the delete modal

![image](https://user-images.githubusercontent.com/3397663/87941413-69ae6580-ca9b-11ea-98ff-8362ccc1c634.png)

**Comment by gabryon99** [comment]
<img width="855" alt="Screenshot 2020-07-21 at 11 04 59" src="https://user-images.githubusercontent.com/14114916/88035172-07f50680-cb42-11ea-9334-eee67386a42f.png">

Fixed. See the commit: https://github.com/ntop/ntopng/commit/926fe778b66baf026c43f18332d9b8679f844a6a

**Comment by simonemainardi** [comment]
This is non standard. Colon is used nowhere. Must use Remove XXX recipient.

**Comment by gabryon99** [comment]
Colons are used in SNMP Page, Pools Page. See the last commit: https://github.com/ntop/ntopng/commit/b83108e423863ca5902aa1efb7f46d661b52e71d
