### ISSUE TITLE
Recipient endpoint fields not localized

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4178]
See fields are named with underscores

![image](https://user-images.githubusercontent.com/3397663/87940977-b180bd00-ca9a-11ea-8cb5-93432c55e3a9.png)

**Comment by gabryon99** [comment]
<img width="855" alt="Screenshot 2020-07-21 at 10 46 29" src="https://user-images.githubusercontent.com/14114916/88033269-71bfe100-cb3f-11ea-9005-ad6b0a8f4605.png">
Fixed, i18n has been used to translate the fields with the keys contained in `endpoint_notifications.recipients.*`. See the commit: https://github.com/ntop/ntopng/commit/290ac986e829989d6d671e2b1720b69b9874845f
