### ISSUE TITLE
Conflicting field description with validation

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4179]
![image](https://user-images.githubusercontent.com/3397663/87943550-80a28700-ca9e-11ea-9030-fc85adb6da27.png)

- Field says 1 character
- Validation complains about 4 characters
- English is wrong: it is 1 character, not 1 characters

**Comment by gabryon99** [comment]
fixed in: https://github.com/ntop/ntopng/commit/460b708c45cd282b56928c3a7bc6e8fecca68192
