### ISSUE TITLE
Difference between ntopng data and Elasticsearch

### ISSUE THREAD

**Issue by lzalewsk** [ntop/ntopng#418]
Hi
I have lanched ntopng with following parameters in ntopnng.conf
-G=/var/tmp/ntopng.pid
-w=3000
-i=vlan710
-i=vlan711
-F="es;ntopng;ntopng_proxy-%Y.%m.%d;http://10.221.1.44:9200/_bulk;"

I'm little confused for one active user which has transfered ~230 MB data via FTP I have noticed:
in ntopng
![ntopng_ftp](https://cloud.githubusercontent.com/assets/14045566/13270490/cc34ad88-da8e-11e5-909c-cbf2045a5324.png)
and in elasticsearch only
![es_ftp](https://cloud.githubusercontent.com/assets/14045566/13270502/e1526412-da8e-11e5-87db-990cf3e816a1.png)

Did you check the correctness of the data in ntopnng and in ES and MySQL

Version 2.3.160222 - Community Edition
Platform    Debian 8.2 (x86_64) - 64 bit
Built on    Debian GNU/Linux 8.2 (jessie)

**Comment by lucaderi** [comment]
In ntopng  you see a cumulative counter, in ES you seem to analyze just one flow. 
Don't forget to star ntopng on github

**Comment by lzalewsk** [comment]
Problem is that I do not see any additional flows marketd as FTP_DATA or FTP_CONTROL 
For the whole day (I have made a few checks) sum of Bytest marked as FTP_DATA is ~35MB vs. 230MB in one session. 
![ftp_problem](https://cloud.githubusercontent.com/assets/14045566/13285251/e2a8aa2c-daf9-11e5-89ab-c2f3b325285d.png)

I will double check, but please confirm that in your QA tests it pass, and all data shall be in ES.

**Comment by lucaderi** [comment]
You need to debug and reproduce the problem (if any). For us it works.
