### ISSUE TITLE
Extend pools/base_pools.lua to allow multiple recipients to be configured

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4180]
Similar to what is done for pool members, an extra `recipients` parameter must be handled in 

```
function base_pools:_persist(pool_id, name, members, configset_id)
function base_pools:add_pool(name, members, configset_id)
function base_pools:edit_pool(pool_id, new_name, new_members, new_configset_id)
```

`recipients` must be a lua array (identical to pools). To validate recipients, a method `function base_pools:get_available_recipient_ids()` must be implemented. The method queries `notification_recipients.get_recipients()` and returns the recipients.

**Comment by cardigliano** [comment]
Implemented
