### ISSUE TITLE
Extend REST APIs to edit/add pools to deal with recipients

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4181]
Utility `scripts/lua/modules/pools/pools_rest_utils.lua` must be extended for the following functions

```
function pools_rest_utils.add_pool(pools)
function pools_rest_utils.edit_pool(pools)
```

An extra `recipients` parameter must be handed an passed to functions implemented in https://github.com/ntop/ntopng/issues/4180. Similar to the `members` parameter, `recipients` will be a comma separated list of valid recipient ids.

This issue depends on https://github.com/ntop/ntopng/issues/4180

**Comment by cardigliano** [comment]
Added pool_recipients parameter
