### ISSUE TITLE
Extend pool add/edit GUI to accept recipients

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4182]
Similar to what is done with pool members, a multiselect with all available recipients must be shown inside pool add/edit modals (below the configuration name).

When there are no recipients available, the multiselect will show a message such as 'no recipient defined'.

A link to add recipient must be added.

This must use (and be implemented only after) https://github.com/ntop/ntopng/issues/4181

**Comment by cardigliano** [comment]
A new pool_recipients parameter has been added to the rest API #4181. This can be now implemented.

**Comment by simonemainardi** [comment]
- all the recipients must be shown for every pool
- every recipient can be associated to 0:N pools

**Comment by gabryon99** [comment]
The select has been added. But when an `add` request is sent with some recipients the `get` returns an empty array. See the commit: https://github.com/ntop/ntopng/commit/befc2ec82190959a35e3efa28a54839058fe5ad5

**Comment by cardigliano** [comment]
@gabryon99 I pushed a fix for the host pools (please update) and the 'recipient' parameter, however 'add' is still not working as you are providing a numeric ID (I guess the array index) instead of the recipient name (this is the real ID)

**Comment by gabryon99** [comment]
@cardigliano thanks! I was sending a numeric ID, now I'll send the recipient name

**Comment by gabryon99** [comment]
Now it seems to work but there is another problem with the edit. When I edit a pool and I send the new recipients then the pool `recipient` member it's empty. Here's an example:
```
{"pool":1,"pool_name":"TEST2","confset_id":"0","recipients":"NAME,Name2","pool_members":"3","csrf":"CSRF_TOKEN_NO_SESSION"}
```

Answer from the server: 
```
{
            "member_details": {
                "6": {
                    "name": "utun1"
                }
            },
            "members": [
                "6"
            ],
            "configset_details": {
                "name": "Default"
            },
            "configset_id": 0,
            "recipients": [],
            "name": "TEST3",
            "pool_id": 2
        }
```

**Comment by cardigliano** [comment]
@gabryon99 the recipients parameter for the edit was not updated, please update and try again.
I still see numeric IDs for the recipients: {"pool_name":"SamplePool","confset_id":"0","pool_members":"","recipients":"1","csrf":"XXX"}

**Comment by gabryon99** [comment]
@cardigliano I've committed the last edits, now there is the recipient name as id for recipients. See the commit: https://github.com/ntop/ntopng/commit/394394523f0c1ca715257197a73d3a545f63e769
