### ISSUE TITLE
The notifications in the version v.4.1.200719 cover the dropdown menu items from user profile dropdown.

### ISSUE THREAD

**Issue by tnichols1998** [ntop/ntopng#4187]
See the attached image.   The user profile drop-down and other content is now hidden by the new notification style.  Please revert notification style or place behind content.   

![ntop_notification_issue](https://user-images.githubusercontent.com/9593326/87987832-213f7980-ca94-11ea-881e-29d7d5926341.png)

**Comment by gabryon99** [comment]
<img width="516" alt="Screenshot 2020-07-21 at 10 01 33" src="https://user-images.githubusercontent.com/14114916/88028596-299dc000-cb39-11ea-8248-391ff236317b.png">
The notification has been placed behind the dropdown menu: https://github.com/ntop/ntopng/commit/01f902ff687015a1981d0e8d82b3a7ef16e6399f
