### ISSUE TITLE
Host pool members page broken when no host pool is defined

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4189]
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/3397663/88038876-1e519100-cb47-11ea-933e-70fcc4084cf2.png">

**Comment by gabryon99** [comment]
Fixed, the problem was due to a missing GET parameter. See the commit: https://github.com/ntop/ntopng/commit/cc7d923c58d92a978ebe9bf87f2477cb4ef460ba
