### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4190]
In NetworkInterface::getActiveHostsList() / NetworkInterface::getActiveHostsGroup() there is no guarantee that entries put in the retriever pointer are not freed before the function ends. Everything works well if the host is fast enough, but the issue shows up when on slow machines the guarantee to use the pointer before it is freed is not honoured.

A possible solution is to put in host_search_walker() (NetworkInterface.cpp) in
 r->elems[r->actNumEntries].hostValue = h;

a incUses to lock h until the host is consumed (so decUses) by getActiveHostsList()/getActiveHostsGroup() and before returning back to the caller.

**Comment by simonemainardi** [comment]
Proposed solution also require changes in `GenericHash::walkAllStates`. Indeed, entries ready to be purged are placed in a vector which is deleted in bulk in `GenericHash::walkAllStates`. This behavior need to be changed to only delete entries having a zero Uses value.

**Comment by simonemainardi** [comment]
Alternative solution is to use `rdlock/unlock` (in place of inc/decUses that whould still require a synchronization mechanism to avoid races on the increased value). In this way, multiple sortHost can access the host in parallel. 

Then `GenericHash::walkAllStates`, before freeing any entry ready to be purged, performs a `wrlock` to make sure no one else is working on it.

Note: Neither sortHost nor `GenericHash::walkAllStates` are performed inline.

A bit more efficient implementation, to avoid slow down, is to use `trylock` in `GenericHash::walkAllStates` and place entries that couldn't be locked into another vector which is freed periodically.
