### ISSUE TITLE
Engaged alerts tab does not list any items

### ISSUE THREAD

**Issue by lunim** [ntop/ntopng#4191]
There is an active alert, but the Engaged alerts tab is empty:
![image](https://user-images.githubusercontent.com/11578774/88115701-a0ec4780-cb6b-11ea-85a7-90909f2639ba.png)

I see the following in the Chrome web console:

```
jquery_bootstrap.min.js?1595370766:1 Datatable: error while loading data: SyntaxError: Unexpected token H in JSON at position 0
error @ jquery_bootstrap.min.js?1595370766:1
show_alerts.lua:827 Uncaught TypeError: Cannot read property 'data' of undefined
    at DataTable.tableCallback (show_alerts.lua:827)
    at DataTable.showError (jquery_bootstrap.min.js?1595370766:1)
    at Object.error (jquery_bootstrap.min.js?1595370766:1)
    at fire (jquery_bootstrap.min.js?1595370766:1)
    at Object.fireWith [as rejectWith] (jquery_bootstrap.min.js?1595370766:1)
    at done (jquery_bootstrap.min.js?1595370766:1)
    at XMLHttpRequest.<anonymous> (jquery_bootstrap.min.js?1595370766:1)
```

This is in the log trace:

`[LuaEngine.cpp:880] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_alerts_table_data.lua][/usr/share/ntopng/scripts/lua/modules/alert_consts.lua:494: attempt to index a nil value (field '?')]`

Running ntopng Community Edition v.4.1.200711.  It is a fresh install with minimal changes done.

**Comment by simonemainardi** [comment]
please update to the latest version

**Comment by lunim** [comment]
@simonemainardi  I don't see a list of releases, what is the latest version?

**Comment by simonemainardi** [comment]
if you are building from source, just pull the latest dev branch. Otherwise install the latest package.

**Comment by simonemainardi** [comment]
Solution given. No feedback received. Closing.
