### ISSUE TITLE
How to Reset Counters —— Total Bytes，Seen Since，Total Bytes Sent ？

### ISSUE THREAD

**Issue by ChunshengZhao** [ntop/ntopng#4197]
![图片](https://user-images.githubusercontent.com/9263377/88473906-8263c300-cf54-11ea-910b-3173fafa164c.png)

**Comment by simonemainardi** [comment]
just enter the host page, and click reset data. You can also enable midnight stats reset from the preferences.

**Comment by ChunshengZhao** [comment]
> just enter the host page, and click reset data. You can also enable midnight stats reset from the preferences.

Hope to provide a button to reset all hosts.
