### ISSUE TITLE
Make hint "Geolocation support is not enabled" removable

### ISSUE THREAD

**Issue by closertotheedge** [ntop/ntopng#4198]
ntopng community running on raspi4: Geolocation support ist not installed and is not needed.
I see no possibility to remove the info message: "Geo IP - Geolocation support is not enabled, please follow the instructions in the documentation to enable it."

**Comment by lucaderi** [comment]
What do you mean exactly? 
- Is geolocation NOT installed (so you need to install)
or
- geolocation is installed and not detected?

Please elaborate

**Comment by closertotheedge** [comment]
geolocation is not installed and I don't want to install it. So how can I disable that hint at the top right corner of the screen?

**Comment by lucaderi** [comment]
No you cannot disable it.
