### ISSUE TITLE
Page Pools broken in community mode

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4199]
SNMP breaks the page in community (indeed, it's not available)

![image](https://user-images.githubusercontent.com/3397663/88512243-8d673380-cfe6-11ea-8531-67be6713810a.png)

Make sure the page works in community mode, without the tab "SNMP"

**Comment by gabryon99** [comment]
Fixed. The problem was caused by loading a pro module in the community version. See the commit: https://github.com/ntop/ntopng/commit/d0303d12ee5461f891cdf1875872a910e9b99ae9
