### ISSUE TITLE
Add a column with notification recipients in pool page

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4200]
Similar to the column with the script configuration, a new column listing recipients should be added in:

![image](https://user-images.githubusercontent.com/3397663/88512848-7e34b580-cfe7-11ea-9975-ca2b6d02deff.png)

Remember to use the same format as done for the members: at most 10 recipients, then show "and XXX other" or "and XXX others"

**Comment by gabryon99** [comment]
<img width="933" alt="Screenshot 2020-07-27 at 09 15 13" src="https://user-images.githubusercontent.com/14114916/88514044-afae8080-cfe9-11ea-9d9e-bc6bcd31cf53.png">

Column added successfully, the column format is as requested. See the commit: https://github.com/ntop/ntopng/commit/aab31a3cea6760148b165a5f6c4708749d8d95b0

**Comment by simonemainardi** [comment]
broken

![image](https://user-images.githubusercontent.com/3397663/88516039-f5b91380-cfec-11ea-8462-d84b2c0f00c9.png)
