### ISSUE TITLE
[pools] Alert endpoints/recipients UI improvements

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#4201]
The UI is a bit dispersive when it comes to configure endpoints, recipients, and bind recipients to pools.
An easy yet effective way for improving this would be to create a single page (instead of two different menu entries) with the Endpoints and Recipients configuration. Once those have been configured, the UI could provide a link to the Pools configuration to guide the user through the configuration process.

**Comment by simonemainardi** [comment]
To simplify even further, I would also merge the two concepts of notification endpoints and notification recipients together. As the improvement suggests, I would use a single page to configure a single concept of 'notification recipient', which will contain the information which is currently spread between endpoints and recipients. This has also the benefit of not having empty recipients such as webhook and syslog.

**Comment by simonemainardi** [comment]
For the moment just add an extra "Notifications" menu entry under System (chose a nice icon) and add two entries:


System Menu -> Notifications -> {Endpoints | Recipients}
