### ISSUE TITLE
Operating System in reports shows id rather than label

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4203]
![image](https://user-images.githubusercontent.com/3397663/88583522-a86e8d80-d050-11ea-9a9a-2d5a4430ce4c.png)

**Comment by gabryon99** [comment]
<img width="1676" alt="Screenshot 2020-07-28 at 09 56 39" src="https://user-images.githubusercontent.com/14114916/88635979-a4765600-d0b8-11ea-8596-8fd279c00538.png">

Now the label is shown.
