### ISSUE TITLE
DHCP address range poorly styled

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4204]
![image](https://user-images.githubusercontent.com/3397663/88583683-d9e75900-d050-11ea-9550-3ced07b5a72b.png)

**Comment by gabryon99** [comment]
Now the boxes are aligned:
<img width="1271" alt="Screenshot 2020-08-17 at 10 58 44" src="https://user-images.githubusercontent.com/14114916/90377680-9fce0d80-e078-11ea-9cf0-d4c2846e5047.png">
