### ISSUE TITLE
nEdge pools

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4205]
nEdge currently hides Pools menu. It is requested to show the pool menu and only show Local Network and Active monitoring Pools. All other pools must be hidden (including the Host Pools Member)

**Comment by gabryon99** [comment]
<img width="808" alt="Screenshot 2020-07-28 at 10 13 42" src="https://user-images.githubusercontent.com/14114916/88637888-05069280-d0bb-11ea-98e3-3a5ad47c4683.png">

Done. See the commit: https://github.com/ntop/ntopng/commit/5f4b7d0c02fa8a132fd4708c618cc5d9ed8c8a86

**Comment by simonemainardi** [comment]
> All other pools must be hidden (including the Host Pools Member)

![image](https://user-images.githubusercontent.com/3397663/88642424-c1af2280-d0c0-11ea-841b-ef719846e07a.png)

**Comment by gabryon99** [comment]
Now is fixed. https://github.com/ntop/ntopng/commit/f7675eb94e2b71d9c3d92fb7c47a5e0b656bc168
