### ISSUE TITLE
Using free Geolocation Database in ntopng instead of Maxmind-Databases

### ISSUE THREAD

**Issue by closertotheedge** [ntop/ntopng#4206]
By downloading the ASN- and City-based mmdb-databases from https://db-ip.com/ to /usr/share/GeoIP/ and renaming them to GeoLite2-ASN.mmdb and GeoLite2-City.mmdb users of ntopng can avoid registering to Maxmind.com.

I ask ntopng developers to add this information in their README (https://github.com/ntop/ntopng/blob/dev/doc/README.geolocation.md).

Of course this may lead to reduced accuracy in geolocation support of ntopng.

**Comment by simonemainardi** [comment]
thanks for pointing this out. Would you like to contribute by updating the readme at https://github.com/ntop/ntopng/blob/dev/doc/README.geolocation.md? You can send a PF and we'll include that.
