### ISSUE TITLE
[pools] Add a test button to test recipients

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#4207]
Each recipient should have a "Send Test Message" button to check the recipient configuration. This will call the <plugin>.runTest function.

**Comment by cardigliano** [comment]
The lua/edit_notification_recipient.lua script now accepts a new action=test (it requires recipient_name=XXX)

**Comment by cardigliano** [comment]
The test button should be placed in the Add/Edit recipient modal. In addition to action=test and recipient_name=XXX the endpoint_conf_name and all the form fields (recipient configuration) should be also provided to the backend.

**Comment by gabryon99** [comment]
A `Test Recipient` button has been added inside the add and edit modal.

**Comment by simonemainardi** [comment]
- button must be y-aligned with add and cancel buttons

![image](https://user-images.githubusercontent.com/3397663/88935773-63ca3880-d282-11ea-925f-bb439302fb23.png)

- Add a text "Recipient is working" in place of OK and let it shown for at least two seconds

- handle response failures and notify the user, e.g., 

![image](https://user-images.githubusercontent.com/3397663/88936262-04205d00-d283-11ea-94fe-12cb075bd6dc.png)

- set a timeout to the ajax request, then kill it and notify the user with a message such as "test has timed out".

**Comment by gabryon99** [comment]
> * button must be y-aligned with add and cancel buttons
> 
> ![image](https://user-images.githubusercontent.com/3397663/88935773-63ca3880-d282-11ea-925f-bb439302fb23.png)
> 
> * Add a text "Recipient is working" in place of OK and let it shown for at least two seconds
> * handle response failures and notify the user, e.g.,
> 
> ![image](https://user-images.githubusercontent.com/3397663/88936262-04205d00-d283-11ea-94fe-12cb075bd6dc.png)
> 
> * set a timeout to the ajax request, then kill it and notify the user with a message such as "test has timed out".

The button has been moved near the cancel and the `add/edit` button. Now a timeout for the request has been set for 3 seconds. See the commit: https://github.com/ntop/ntopng/commit/16a9443bc6112412304714b9bf5daa6f9052c755

**Comment by simonemainardi** [comment]
- also move the messages, not just the button

![image](https://user-images.githubusercontent.com/3397663/88947813-61230f80-d291-11ea-9bf1-6d2787176ceb.png)

- The spinner position is not consistent. Look at how the spinner is placed inside SNMP modal and make it identical.
- The spinner color is not consistent. Look at how the spinner is colored inside SNMP and make it identical

- Message says timed out but this is not true.

![image](https://user-images.githubusercontent.com/3397663/88948013-a7786e80-d291-11ea-8f38-36f7548833dd.png)

There's an error in the response.

![image](https://user-images.githubusercontent.com/3397663/88948050-b65f2100-d291-11ea-837c-8f27726436bd.png)

**Comment by simonemainardi** [comment]
please also replace "Recipient is working" with "Test successful"
