### ISSUE TITLE
Pool pills ordering

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4208]
For pool pills

![image](https://user-images.githubusercontent.com/3397663/88698447-5a1bc600-d106-11ea-8969-1089cef206fd.png)

move "Active Monitoring" as last element and make sure the first entry (and not the second) is selected when entering the page

**Comment by gabryon99** [comment]
<img width="698" alt="Screenshot 2020-07-29 at 10 30 03" src="https://user-images.githubusercontent.com/14114916/88776593-78c1a180-d186-11ea-9974-5957eb974aca.png">

The pills have been ordered as request. See the commit: https://github.com/ntop/ntopng/commit/439ba513d74bb84190aa22417f9f0829a641093b
