### ISSUE TITLE
SNMP devices pool column

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4209]
Replace column "community" with the current SNMP device pool

![image](https://user-images.githubusercontent.com/3397663/88698725-b5e64f00-d106-11ea-9922-85a361462ed3.png)

**Comment by gabryon99** [comment]
<img width="698" alt="Screenshot 2020-07-29 at 10 29 06" src="https://user-images.githubusercontent.com/14114916/88776508-56c81f00-d186-11ea-8c30-dab5952784e8.png">

The `Community` column has been removed as requested and it was replaced by the `Pool` column.

**Comment by simonemainardi** [comment]
broken column name

![image](https://user-images.githubusercontent.com/3397663/88785377-626d1300-d191-11ea-84bf-5aa277b3e267.png)
