### ISSUE TITLE
Add recipient button does not work

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4211]
Clicking on the button + is ineffective, nothing happens

![image](https://user-images.githubusercontent.com/3397663/88699120-3c029580-d107-11ea-816a-bf2b13baa755.png)

likely, this occurs as no endpoint is defined.

**Comment by gabryon99** [comment]
Now when there are no endpoints defined an alert message (similar to the 'Host Pool Members') will be shown. See the commit: https://github.com/ntop/ntopng/commit/efd74f46f7338950be5b947f401e2858b3799457
