### ISSUE TITLE
Inconsistent empty dropdown

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4212]
![image](https://user-images.githubusercontent.com/3397663/88699381-8edc4d00-d107-11ea-9a51-77b5ef11ecaa.png)

the first available endpoint must be automatically selected

**Comment by gabryon99** [comment]
<img width="816" alt="Screenshot 2020-07-29 at 10 26 06" src="https://user-images.githubusercontent.com/14114916/88776175-ecaf7a00-d185-11ea-9a52-03c82db5afaf.png">

Now the first endpoint is selected automatically. When an endpoint doesn't have any parameters to fill then a simple message will be shown. See the commit: https://github.com/ntop/ntopng/commit/efd74f46f7338950be5b947f401e2858b3799457 for reference.
