### ISSUE TITLE
Implement edit for SNMP device

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4213]
Similar to `snmp_config.add_snmp_device`, an edit function `snmp_config.edit_snmp_device` should be implemented. The edit should allow to change everything but the device IP which is the key.

This is required to implement the UI of https://github.com/ntop/ntopng/issues/4124

**Comment by lucaderi** [comment]
Implemented 

function snmp_config.edit_snmp_device(snmp_device_ip, snmp_read_community, snmp_write_community,
                                     snmp_version, symbolic_name, description,
                                     level, username, auth_protocol, auth_passphrase,
                                     privacy_protocol, privacy_passphrase)
