### ISSUE TITLE
ntopng license

### ISSUE THREAD

**Issue by lulululuej** [ntop/ntopng#4214]
Hi,

I had asked the free education version and get the key from ntopng. I use the enterprise L license, but it has a time limit above the screen, and after the time limit it will return to community license. Does anyone have same situation? Is there any configuration wrong?

Thanks.

Best regards,
Karen

![license](https://user-images.githubusercontent.com/68433978/88750794-d656ed80-d188-11ea-97ac-691397e9ab2c.PNG)

**Comment by lucaderi** [comment]
Please report the output of "ntopng --version"

**Comment by lulululuej** [comment]
![image](https://user-images.githubusercontent.com/68433978/88768291-77579f80-d1ad-11ea-9fd7-52b3f390be45.png)

Thanks.

**Comment by lulululuej** [comment]
Hi,
is there any configuration wrong? I have retry the key they provide to me but still the same issue. The output of ntopng --version said there is a license mismatch but I don't know why.

**Comment by lucaderi** [comment]
You have generated a x64 license and installed it on a raspberry. This is your problem
