### ISSUE TITLE
Network Descriptions

### ISSUE THREAD

**Issue by seismiccollision** [ntop/ntopng#422]
It would be very cool to be able to tie network subnets back to interfaces/VLANS/SVIs

**Comment by simonemainardi** [comment]
please make a more detailed use-case of what you would like to achieve.

**Comment by seismiccollision** [comment]
@simonemainardi 
essentially i want to be able to tie subnets back to meaningful information so that ntopng can provide context without having to leave its interface

hypothetical relevant information:
I have subnet 8.8.8.0/24 defined in ntopng.conf with "-m="8.8.8.0/24"
that subnet's gateway is VLAN interface 100
VLAN interface 100 has a description of "Production Web Servers"
the sflow headers actually already include VLAN tagging 

use case 1:
I would like to be able to say "I want to know top talkers in VLAN 100" and search for VLAN100 in the header search bar either with the subnet, the VLAN#, interface name (VLAN100 again), or the interface description
use case 2:
I would like to be able to know which hosts spend most of their time talking within their broadcast domain to satisfy my curiosity
use case 3:
I would like to be able to see local-to-local traffic by subnet/VLAN to find hosts that might be better served in a common broadcast domain instead of having their traffic pinned to a router

Does that help? If you need anything else from me I am happy to help

**Comment by simonemainardi** [comment]
latest report (professional version) implement top-talkers for each vlan seen. please, update and give it a try.
