### ISSUE TITLE
Add REST Endpoint for Getting a User Session Cookie

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4220]
For avoiding multiple sign-in, it would be nice to have a REST API call that can retrieve the session cookie (or create it if not existing or expired) for a given user so that the requestor can pass it in future HTTP requests avoiding to login on ntopng

![Screen Shot 2020-07-29 at 14 07 26](https://user-images.githubusercontent.com/4493366/88801196-9b18e680-d1a9-11ea-95dc-c6dda174b98f.png)

In this new API call, it must be specified the (existing) username for which we want to retrieve the session cookie
{"username": "XXXX" }

If user YYYY requests the session cookie for username XXXX, either XXXX == YYYY, or YYYY must be an admin user already existing in ntopng.

**Comment by cardigliano** [comment]
Implemented new endpoint rest/v1/get/ntopng/session.lua
