### ISSUE TITLE
[pools] Remove the "Delete" button from default host pools

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4221]
Delete button must be removed from any of the pool pages for the "Default" pool:

![image](https://user-images.githubusercontent.com/3397663/88826780-70d72100-d1c9-11ea-9c7c-447ffd9c0577.png)

**Comment by gabryon99** [comment]
Removed the button for the default pool: https://github.com/ntop/ntopng/commit/b7e1d4bb630c7d9b34ebae30a61b6b94b0aa3df9
