### ISSUE TITLE
[pools] Make the "Default" pool name Non-Editable

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4222]
The "Default" pool name must be non-editable from any of the pools page

![image](https://user-images.githubusercontent.com/3397663/88826937-9c5a0b80-d1c9-11ea-9012-aff88040c035.png)

A greyed-out text box must be shown.

**Comment by gabryon99** [comment]
The Default pool name cannot be editable: https://github.com/ntop/ntopng/commit/48715b92fb339d54883660923e6fa4284bcf76b8
