### ISSUE TITLE
[pools] Remove the multiselect with members from the "Default" pool

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4223]
The default pool has no members associated explicitly. 

The section members with the multiselect must be removed from the "edit" of the Default pool

![image](https://user-images.githubusercontent.com/3397663/88827235-fa86ee80-d1c9-11ea-9747-d1a154684dc7.png)

The section members with link with the "Edit members" must be removed from the Default host pool

![image](https://user-images.githubusercontent.com/3397663/88827298-138f9f80-d1ca-11ea-9c47-788c8c74ffeb.png)

**Comment by gabryon99** [comment]
The multiselect members has been hidden. See the commit: https://github.com/ntop/ntopng/commit/9d151031406d31f3045abcc71cf38a719d34525d
