### ISSUE TITLE
[pools] Hide the recipients multiselect when empty

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4224]
When no recipient is defined, the empty multiselect must be hidden from edit/add pools

![image](https://user-images.githubusercontent.com/3397663/88827614-73864600-d1ca-11ea-906f-551f9697a8ce.png)

A link "edit Recipients" (with the edit icon) must be shown in place of the multiselect.

**Comment by gabryon99** [comment]
<img width="819" alt="Screenshot 2020-08-05 at 10 27 57" src="https://user-images.githubusercontent.com/14114916/89389916-568bce80-d706-11ea-9234-f06eefdc58de.png">

Done, now when there are no recipients a link will be shown as requested. https://github.com/ntop/ntopng/commit/9b8087844f0d6a695db4033046188ac5ee476122
