### ISSUE TITLE
[pools] Remove hardcoded "Default"

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4227]
Two "Default" pools now show up in the host and mac cog page

![image](https://user-images.githubusercontent.com/3397663/88893817-344a0a80-d247-11ea-82d4-fa19d0ea7976.png)

![image](https://user-images.githubusercontent.com/3397663/88893852-41ff9000-d247-11ea-9334-d2b06b433ea8.png)

It is requested to remove the "hardcoded" "Default" pool. With the current implementation, the "Default" pool is returned automatically from the lua pool classes so there's no need to handle it as an exception.

**Comment by simonemainardi** [comment]
Same here:

![image](https://user-images.githubusercontent.com/3397663/88894040-9145c080-d247-11ea-8673-070dc72d822a.png)

**Comment by gabryon99** [comment]
<img width="627" alt="Screenshot 2020-07-30 at 12 46 54" src="https://user-images.githubusercontent.com/14114916/88914334-c27fba00-d262-11ea-9d4f-4f39f0380c24.png">

it seems `host_pools_utils.getPoolsList()` returns both `Not Assigned` and `Default Pool` entries

**Comment by simonemainardi** [comment]
```
host_pools_utils.getPoolsList()
```

is no longer used apart from `scripts/lua/admin/host_pools.lua` which will be removed.

**Comment by gabryon99** [comment]
Ok, now the problem is fixed. See the commit: https://github.com/ntop/ntopng/commit/86175b2b5bb3a4d36640adfcc78b1fe988b44203

**Comment by simonemainardi** [comment]
still bugged

![image](https://user-images.githubusercontent.com/3397663/88943763-2e2a4d00-d28c-11ea-840e-7c3fc4faaf72.png)

**Comment by gabryon99** [comment]
Now the hardcoded default pool has been removed. See the commit: https://github.com/ntop/ntopng/commit/d247dbb8979a97bda813db0b916f485d76ebfea0

**Comment by simonemainardi** [comment]
still bugged

<img width="738" alt="image" src="https://user-images.githubusercontent.com/3397663/89015957-39c35580-d318-11ea-993d-0ce75e3245c0.png">

Do you mind grepping this all around the code?

**Comment by gabryon99** [comment]
I grepped all the references to the Not Assigned pool. Now there is no hardcoded default pool no more.

**Comment by simonemainardi** [comment]
you've removed the last reference 6 minutes ago, after my last comment, and now it's ok.
