### ISSUE TITLE
[pools] Remove the "Default" pool from host pool members dropdown

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4228]
This must not appear

![image](https://user-images.githubusercontent.com/3397663/88894685-8ccdd780-d248-11ea-9a50-31058ac4b34c.png)

Having only the "Default" pool must be treated as now it is currently treated having no pools

**Comment by gabryon99** [comment]
The default entry has been removed from the dropdown. See the commit: https://github.com/ntop/ntopng/commit/3a9c6306b37d9afb01658658ec2ee724fecf390e

**Comment by simonemainardi** [comment]
this is what happens when no host pool is defined:

![image](https://user-images.githubusercontent.com/3397663/88943599-f91dfa80-d28b-11ea-9b51-5a1ba90d1aab.png)

did't follow this:

> Having only the "Default" pool must be treated as now it is currently treated having no pools

**Comment by gabryon99** [comment]
The problem was caused by the guard: `pool:get_num_pools() > 0`, now the function `get_num_pools()` return almost a pool (the default one). The problem has been fixed. See the commit: https://github.com/ntop/ntopng/commit/57d988c20bd0a5acc6ec06748450eac3198a2716

**Comment by simonemainardi** [comment]
now the page is broken when there's no host pool (apart from the default)

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/3397663/89017052-084b8980-d31a-11ea-99dc-30b368b5d07a.png">

test before marking issues as waiting for review

**Comment by gabryon99** [comment]
Fixed. See the commit: https://github.com/ntop/ntopng/commit/cc35284ea22d1a473f17927bd5759115b1826559
