### ISSUE TITLE
[pools] VLAN must not be automatically populated with 0

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4229]
Adding a member sets a '0' to the VLAN

![image](https://user-images.githubusercontent.com/3397663/88894874-e1715280-d248-11ea-8aca-9b0061ba499f.png)

VLAN must be left empty. Zero is assumed implicitly when the field doesn't contain a value but this is not shown to the user.

Same for 

![image](https://user-images.githubusercontent.com/3397663/88895211-0239a800-d249-11ea-9f63-6da61a71d67c.png)

**Comment by gabryon99** [comment]
Now the VLAN input box is empty with a placeholder containing 0. See the commit: https://github.com/ntop/ntopng/commit/9039f0e260e6d7f108baf7a1c7eb43fc4e58fd08
