### ISSUE TITLE
Ntopng cannot detect IMSI's

### ISSUE THREAD

**Issue by rathnaTech** [ntop/ntopng#423]
Hi ,
  I tried with GTP based pcap file with ntopng .But ,ntopng cannot able to find IMSI ,ip etc.,While extracting the same pcap file with wireshark it shows all the files.Please provide the solution.

Thank you,

**Comment by lucaderi** [comment]
You need to use nProbe to handle GTP and forward data to ntopng via ZMQ. See https://sharkfest.wireshark.org/assets/presentations/I5.pdf

**Comment by rathnaTech** [comment]
Thank you Luca.

  Does nprobe supports 10G capacity.Is it a open source or licensed tool.

**Comment by lucaderi** [comment]
It is a commercial product: http://www.ntop.org/products/netflow/nprobe/
