### ISSUE TITLE
[pools] Rework layout host pool members of type Network

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4230]
CIDR is a complex term that should be hidden

![image](https://user-images.githubusercontent.com/3397663/88895743-2b5a3880-d249-11ea-9d95-f5c2156c385d.png)

It is requested to simplify the input as

![image](https://user-images.githubusercontent.com/3397663/88896171-bfc49b00-d249-11ea-9ccf-86995f7ebfd7.png)

**Comment by simonemainardi** [comment]
use a slash '/' to separate the network from the cidr

**Comment by gabryon99** [comment]
The layout has been reworked as requested. See the commit: https://github.com/ntop/ntopng/commit/bbbe27bd5a5c566dda926856c36214760d877203

**Comment by simonemainardi** [comment]
validation is wrong

![image](https://user-images.githubusercontent.com/3397663/88944089-9aa54c00-d28c-11ea-9471-fd96e4cba472.png)

- not turning red when the input is NaN
- Must be a number  between 1 and 127

**Comment by gabryon99** [comment]
Fixed: https://github.com/ntop/ntopng/commit/31399956981ab9b0e68d33c3b4192976004b5092

**Comment by simonemainardi** [comment]
three digits doesn't fit in the box

<img width="168" alt="image" src="https://user-images.githubusercontent.com/3397663/89016178-96bf0b80-d318-11ea-8dc8-0a466c7a75d8.png">

when the box fails validation, its contents disappear

<img width="123" alt="image" src="https://user-images.githubusercontent.com/3397663/89016211-a3dbfa80-d318-11ea-8ea5-f9cc384e511d.png">

**Comment by gabryon99** [comment]
I substituted the input box with a select containing the CIDR. If the typed address is an IPv4 address then all the CIDRs from 33 to 127 will be disabled. See the commit: https://github.com/ntop/ntopng/commit/30eb844553e263c19924a2d50202a7c2892ed6bc

**Comment by simonemainardi** [comment]
this is bugged. There's no complain about a clearly wrong input

![image](https://user-images.githubusercontent.com/3397663/89035762-c03d5e80-d33b-11ea-82a3-9fc356f7e418.png)

**Comment by gabryon99** [comment]
Now if the CIDR is not valid for an IPv4 Address the CIDR select will automatically select the default value (`24`). See the commit: https://github.com/ntop/ntopng/commit/b9df1d72e5c073031be0b37d4ff6424e87e40454

**Comment by simonemainardi** [comment]
this is not what the issue was asking. Desired layout is 

![image](https://user-images.githubusercontent.com/3397663/89057090-56ce4780-d35d-11ea-9727-dadb9b1ed021.png)

just make the input slightly larger to handle https://github.com/ntop/ntopng/issues/4230#issuecomment-667003102

**Comment by gabryon99** [comment]
Now the layout is as desired. See the commit: https://github.com/ntop/ntopng/commit/cf7ce525f59bd9b76c82d39d3b1ad395fa33bf2b

**Comment by simonemainardi** [comment]
<img width="792" alt="image" src="https://user-images.githubusercontent.com/3397663/89166324-2d3e3780-d57a-11ea-9709-d1426dd9af14.png">

**Comment by gabryon99** [comment]
The problem was in Firefox Browser. I solved it. See the commit: https://github.com/ntop/ntopng/commit/f62ec96bc7f834548c77e5229dbb9fecac2a89ec
