### ISSUE TITLE
network discovery

### ISSUE THREAD

**Issue by lulululuej** [ntop/ntopng#4231]
Hi,

I have some problems about notopng4.1. 
First is about the network discovery, I had seen the website about how to detect the network discovery from https://www.ntop.org/ntopng/network-device-discovery-part-1-active-discovery/ ,

![圖片](https://user-images.githubusercontent.com/68433978/88899718-ff5aa980-d280-11ea-880e-c083e3680cde.png)
 
It said that we will have a list via ARP, and compare it with the Devices->Layer 2, but where can I see the Devices->Layer 2. 

Thanks.

Best regards,
YiJie

**Comment by simonemainardi** [comment]
host -> mac addresses are the devices -> Layer 2 in ntopng 4.0+

![image](https://user-images.githubusercontent.com/3397663/88908132-ce1ab300-d259-11ea-98e3-8e4556975c7a.png)

**Comment by lulululuej** [comment]
Thanks for your reply, but the result of my network discovery is very weird. Most of the hosts are the ghost hosts, but I had check my host -> MAC addresses but still don't understand.
![MAC address](https://user-images.githubusercontent.com/68433978/89015693-0bf70480-d34a-11ea-9e14-c450f302e4af.PNG)
![network discovery](https://user-images.githubusercontent.com/68433978/89015697-0d283180-d34a-11ea-980e-93d0b027ecbc.PNG)

**Comment by simonemainardi** [comment]
This means that, each of the IP addresses marked with the ghost icon:

1. Has a MAC address which is known to ntopng from the traffic - indeed, you see it listed in the macs list page
2. However, the ARP scan run by ntopng didn't receive any response from that MAC address

E.g., your 192.168.1.89 has a MAC address which you can find inside the MAC addresses page, however, that MAC address didn't respond to the ARP scan run by ntopng.

If you want to extend the range of networks probed with the ARP scan, you can extend your -m. Also note that discovery only works for non-mirrored packet interfaces.
