### ISSUE TITLE
User Script Buttons Old Style

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4232]
Use the new style for the following buttons

![image](https://user-images.githubusercontent.com/3397663/88907979-94e24300-d259-11ea-8080-094c9610b245.png)

![image](https://user-images.githubusercontent.com/3397663/88908030-a9bed680-d259-11ea-9479-bdf61c334f3b.png)

**Comment by gabryon99** [comment]
The Configuration table style has been fixeed. See the commit: https://github.com/ntop/ntopng/commit/693070b1749fe851822e08bde3a5d2249e8cc740

The style has been fixed also in the scripts page: https://github.com/ntop/ntopng/commit/3b3bb87f922c7947c762bd42a568aa3fbfe988ae
