### ISSUE TITLE
Host Pool Member filter broken

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4233]
![image](https://user-images.githubusercontent.com/3397663/88908509-3d90a280-d25a-11ea-95a0-2933be3d2161.png)

Ipv6 addresses are not shown when picking the IPv4/IPv6 from the dropdown

![image](https://user-images.githubusercontent.com/3397663/88908530-471a0a80-d25a-11ea-88c5-d1504b7bce76.png)

**Comment by simonemainardi** [comment]
moreover, the /32 must not be shown for ipv6 addresses (same as for ipv4 addresses)

**Comment by gabryon99** [comment]
Now the IPv4 and the IPv6 filters are standalone from each other. See the commit: https://github.com/ntop/ntopng/commit/ec2f0f66b088808f9b3e8e43103a6fa16ea28796

**Comment by simonemainardi** [comment]
members are now disappeared

**Comment by simonemainardi** [comment]
still bugged

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/3397663/89016468-13ea8080-d319-11ea-88a4-6ec801009b53.png">

the IPv4 network disappears:

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/3397663/89016491-1cdb5200-d319-11ea-92e1-6701a1554b24.png">


the IPv6 address doesn't show up

<img width="960" alt="image" src="https://user-images.githubusercontent.com/3397663/89016526-2795e700-d319-11ea-9a04-1af15980672b.png">

**Comment by simonemainardi** [comment]
This has fixed missing IPv6: https://github.com/ntop/ntopng/issues/4252

Divide the dropdown into:

IPv4 (must show all IPv4 hosts regardless of the CIDR)
IPv6 (must show all IPv6 hosts regardless of the CIDR)
MAC Address

**Comment by simonemainardi** [comment]
@gabryon99 please handle this

**Comment by simonemainardi** [comment]
@gabryon99 is this ready for review?

**Comment by gabryon99** [comment]
Yes
