### ISSUE TITLE
Add new endpoint must have the first endpoint selected

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4235]
Rather than having the dropdown with "Select an Endpoint Type", the first endpoint must be automatically selected

![image](https://user-images.githubusercontent.com/3397663/88910049-281c7800-d25c-11ea-8acf-4af30e865e2f.png)

**Comment by gabryon99** [comment]
Now the first endpoint is selected automatically. See the commit: https://github.com/ntop/ntopng/commit/be17a6c7435dee9293f94c5b547f0ed67baaaef6
