### ISSUE TITLE
[pools] Wrong link in edit active monitoring

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4237]
![image](https://user-images.githubusercontent.com/3397663/88925337-aedd4f00-d274-11ea-8240-3386adccbfdc.png)

must be edit pools with the standard icon

**Comment by gabryon99** [comment]
Link fixed. See the commit: https://github.com/ntop/ntopng/commit/e9ec62b9d397ec99f90e61c1cff10ca11bf60d83
