### ISSUE TITLE
[pools] Pool members not sorted in modal

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4238]
Pool members are not sorted. This makes it troublesome to locate/search members. It is requested to show members as sorted in

![image](https://user-images.githubusercontent.com/3397663/88927823-498b5d00-d278-11ea-930b-1192d0204e10.png)

use IP sorting for SNMP devices, use alphabetic sorting for other pools

**Comment by gabryon99** [comment]
Now the order is fixed. See the commit: https://github.com/ntop/ntopng/commit/d4984df8aee8d87294548043c4a9007d002cc896
