### ISSUE TITLE
[pools] Host pool members not showing up

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4239]
![image](https://user-images.githubusercontent.com/3397663/88943263-90368280-d28b-11ea-80fa-6a6a220be7ee.png)

![image](https://user-images.githubusercontent.com/3397663/88943323-9d537180-d28b-11ea-83ad-826b782b01d2.png)

**Comment by gabryon99** [comment]
Fixed. The problem was caused due to the new changes to assign the default number as the first pool. See the commit: https://github.com/ntop/ntopng/commit/ba6bfeb927e7bf60678ccb8a3abd5a74eb385dd4
