### ISSUE TITLE
after install, cannot login

### ISSUE THREAD

**Issue by Maurotb** [ntop/ntopng#4240]
Hi, i have installed ntopng in debian10 with apt , after install i try to login with admin admin but not work.
v.4.1.200730

ntopng --community -v3
this is my output at login

30/Jul/2020 17:46:53 [ThreadedActivity.cpp:392] Running /usr/share/ntopng/scripts/callbacks/system/timeseries.lua (iface=0x56106016fad0)
30/Jul/2020 17:46:53 [ThreadedActivity.cpp:392] Running /usr/share/ntopng/scripts/callbacks/system/second.lua (iface=0x56106016fad0)
30/Jul/2020 17:46:54 [HTTPserver.cpp:497] [HTTP] Session  is expired
30/Jul/2020 17:46:54 [Ntop.cpp:1323] Checking Local auth
30/Jul/2020 17:46:54 [HTTPserver.cpp:650] [HTTP] redirect_to_login()
30/Jul/2020 17:46:54 [HTTPserver.cpp:497] [HTTP] Session  is expired
30/Jul/2020 17:46:54 [HTTPserver.cpp:1153] [HTTP] /lua/login.lua [/usr/share/ntopng/scripts/lua/login.lua]
30/Jul/2020 17:46:54 [HTTPserver.cpp:1195] [HTTP] Serving file /usr/share/ntopng/httpdocs/bootstrap-4.4.0-dist/css/bootstrap.min.css
30/Jul/2020 17:46:54 [HTTPserver.cpp:1195] [HTTP] Serving file /usr/share/ntopng/httpdocs/css/minified/fontawesome-custom.min.css
30/Jul/2020 17:46:54 [HTTPserver.cpp:1195] [HTTP] Serving file /usr/share/ntopng/httpdocs/css/minified/tempusdominus.min.css

I have try all to reset password
redis-cli del ntopng.user.admin.password
redis-cli set ntopng.prefs.local.auth_enabled 1
for k in `redis-cli keys ntopng.cache.failed_logins.*`; do redis-cli del $k; done
redis-cli keys "ntopng.*" | xargs redis-cli unlink
sudo rm /var/lib/ntopng/runtimeprefs.json
with restart service, but problem persist...
Can help me?
Thanks

**Comment by cardigliano** [comment]
@Maurotb please update again, a new build is available

**Comment by Maurotb** [comment]
yes, now work.
Thanks
