### ISSUE TITLE
[pools] Hide message for recipients with no params

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4241]
this must be hidden

![image](https://user-images.githubusercontent.com/3397663/88947093-561baf80-d290-11ea-88bc-6c2c9d7751fc.png)

**Comment by gabryon99** [comment]
The message has been hidden. See the commit: https://github.com/ntop/ntopng/commit/8a8a94760635ed8a20d1b4b1f0b1dd984147750b
