### ISSUE TITLE
[Pools] Unable to delete recipient

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4244]
When clicking on 
![Screen Shot 2020-07-30 at 22 23 00](https://user-images.githubusercontent.com/4493366/88970752-3fd31b00-d2b3-11ea-94cf-0afa378f823b.png)

the folvogin error is reported

30/Jul/2020 22:21:53 [LuaEngine.cpp:880] WARNING: Script failure [/Users/deri/network/ntopng/scripts/lua/edit_notification_recipient.lua][.../network/ntopng/scripts/lua/modules/pools/base_pools.lua:688: bad argument #1 to 'for iterator' (table expected, got nil)]

**Comment by gabryon99** [comment]
The problem was in the backend. @cardigliano fixed this. See the commit: https://github.com/ntop/ntopng/commit/75ba792513ef94879a78d37a99944f772248e3f0
