### ISSUE TITLE
UI is not reporting if an alert can be triggered

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4246]
In this page
![Screen Shot 2020-07-30 at 22 27 04](https://user-images.githubusercontent.com/4493366/88971175-d8699b00-d2b3-11ea-9ea5-973ad0bb7220.png)
there are a few problems:

it is not clear if an alert will be triggered in case of threshold cross.

Please add a new label well visible (not a note) where it is written something like: "An alert will be triggered in case of threshold cross". The add the edit button to jump on the poll recipient list.

**Comment by simonemainardi** [comment]
implemented
