### ISSUE TITLE
Active Monitoring: Minimum threshold should be 1 msec

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4247]
![Screen Shot 2020-07-30 at 22 31 06](https://user-images.githubusercontent.com/4493366/88971615-870ddb80-d2b4-11ea-9f7f-540aaa5ae02d.png)

**Comment by gabryon99** [comment]
Fixed, the problem was in the default value inside the edit modal. See the commit: https://github.com/ntop/ntopng/commit/0c3499b3f00c5d2755b140807ac224d98ca94f35
