### ISSUE TITLE
Application Classification

### ISSUE THREAD

**Issue by razor3g** [ntop/ntopng#425]
Hello,
Please I am using ntopng for traffic analysis in my company. My issue is: I have just limited L7 apps attached to the host IPs I am seeing. For instance, all I can see under applications are (NetBios, Unknown, DHCP, Dropbox, SSDP) any other app we are using online does not show.

Please do i go about this?
![capture](https://cloud.githubusercontent.com/assets/17588682/13455622/7cffed86-e056-11e5-88c2-823038681343.JPG)

**Comment by lucaderi** [comment]
You can type ntopng -h to see the list of supported protocols. It looks you have protocols nDPi does not support.

**Comment by razor3g** [comment]
Ok. I typed the command as instructed and I saw 221 nDPI protocals listed but how do I get them to show up?
Because I saw protocols like: skype, facebook, cnn, Yahoo etc but they do not show up in the applications.

**Comment by razor3g** [comment]
Ok. I typed the command as instructed and I saw 221 nDPI protocals listed
but how do I get them to show up?
Because I saw protocols like: skype, facebook, cnn, Yahoo etc but they do
not show up in the applications.

On Wed, Mar 2, 2016 at 11:09 PM, Luca Deri notifications@github.com wrote:

> You can type ntopng -h to see the list of supported protocols. It looks
> you have protocols nDPi does not support.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ntop/ntopng/issues/425#issuecomment-191485938.

## 

Regards,

Network Engineer | Teledata ICT
No. 10 Mensa Saba Road, Kokomlemle, Accra, Ghana
Tel: +233 (0) 307085852

**Comment by simonemainardi** [comment]
@razor3g , as discussed separately via email, all the traffic listed has broadcast/multicast destinations. Therefore I think the host that is running ntopng is not properly configured to receive all network traffic. In other words, it only receives broadcast traffic.

Please check your network / host configuration.

Can you update on this?

**Comment by lucaderi** [comment]
if you have a problem with one protocol, please capture a pcap file with such protocol (so we can reproduce the issue), file a bug under nDPI and we will look at it.
