### ISSUE TITLE
[pools] Wrong CIDR submitted for IPv6 host pool members

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4252]
When adding an IPv6 host pool member, a /128 must be submitted in place of /32

![image](https://user-images.githubusercontent.com/3397663/89018974-e7386800-d31c-11ea-963b-6cf5bb933fcc.png)

so the payload must contain `/128` not `/32`

**Comment by gabryon99** [comment]
Just fixed. See the commit: https://github.com/ntop/ntopng/commit/e3e2c8e72d705a1aad6bdebfbbfebac931ddb68d
