### ISSUE TITLE
[pools] Member sort not working

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4253]
Sort is ineffective and so should be disabled for the members column

![image](https://user-images.githubusercontent.com/3397663/89036405-eb747d80-d33c-11ea-9173-8880076a637d.png)

**Comment by gabryon99** [comment]
Sorting disabled on member column. See the commit: https://github.com/ntop/ntopng/commit/039ce65578d0722e06f56a221073e6ff10adf2eb
