### ISSUE TITLE
Double filter in dropdown

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4254]
Hitting 'delete unresponsive devices' when the dropdown has unresponsive devices selected yields this

![image](https://user-images.githubusercontent.com/3397663/89038011-d2b99700-d33f-11ea-99f1-489e460ff9dc.png)

**Comment by gabryon99** [comment]
Fixed. See the commit: https://github.com/ntop/ntopng/commit/6153774c1b0e02b6c973748801592807a0ebe794

**Comment by simonemainardi** [comment]
Still bugged. Now the filter is reset but an empty table is shown while actually there are many other devices existing. So my guess it that you just reset the filter but the table stays on 'unresponsive devices'. Test before commit.

**Comment by gabryon99** [comment]
The problem has been fixed. See the commit: https://github.com/ntop/ntopng/commit/e5a42887ee2b33d829b241f7867d765ab96505fd
