### ISSUE TITLE
[pools] Default configuration pool

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4255]
The Default user script configuration must show "No pools" as any other configuration, and not the italic "Default", when there's no pool associated to it

![image](https://user-images.githubusercontent.com/3397663/89043293-8cb50100-d348-11ea-934c-315d760c2d8c.png)

**Comment by gabryon99** [comment]
The message has been replaced: https://github.com/ntop/ntopng/commit/1ba69cca0af12cf6cfae027aed65d5a6d3987dce
