### ISSUE TITLE
Modal "Cancel" button redundant

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4256]
Many modals have both the X in the top-right corner and the Cancel button.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/3397663/89057504-099ea580-d35e-11ea-8a7d-94ea5c47b47d.png">

It is requested to check any modal in the software and remove the Cancel button - just leave the X.

**Comment by lucaderi** [comment]
I think this tickets makes no sense. Better to leave the X and leave cancel

**Comment by lucaderi** [comment]
@gabryon99 Please a) make the threshold field as large as the other field b) "Edit Pools" remove the label and make Y centred with respect to the field next to it

**Comment by simonemainardi** [comment]
> I think this tickets makes no sense. Better to leave the X and leave cancel

This is exactly what the ticket was asking

**Comment by lucaderi** [comment]
The final decision is to keep both X and cancel.
