### ISSUE TITLE
[pools] Show recipients below the Pool dropdown in SNMP and active monitoring

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4257]
For active monitoring and SNMP it is possible to pick a pool, e.g., 

<img width="682" alt="image" src="https://user-images.githubusercontent.com/3397663/89057662-56827c00-d35e-11ea-8c07-061f3f2a1b09.png">

Below this dropdown, it is requested to show a field with all the recipients associated to the selected pool. Field changes every time a pool is changed from the dropdown.

- Make the code generic so that it can be reused both in SNMP and active monitoring
- To print the recipient list, use the same function currently used to print the recipients list in the pool pages

**Comment by lucaderi** [comment]
I think the problem is broader than described. A user must be able to know if when a SNMP device fails, there is a recipient configured to be notified. In this case I want to be able to modify the recipient list and name.

**Comment by simonemainardi** [comment]
This will be re-opened if necessary after the implementation of https://github.com/ntop/ntopng/issues/4321
