### ISSUE TITLE
SNMP Chart icon is too small

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4258]
This must be enlarged

<img width="78" alt="image" src="https://user-images.githubusercontent.com/3397663/89057950-bf69f400-d35e-11ea-94ab-42ec5ad06415.png">

**Comment by gabryon99** [comment]
<img width="409" alt="Screenshot 2020-07-31 at 22 50 27" src="https://user-images.githubusercontent.com/14114916/89076268-3c599580-d380-11ea-8a42-90d0f124b39d.png">
The icon has been resized.
