### ISSUE TITLE
Change notification style

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4259]
For the top-right notifications it is requested to use the same style as in https://getbootstrap.com/docs/4.3/components/toasts/

In particular:
- severity color is just a small box
- all notifications are dismissable with the X

**Comment by gabryon99** [comment]
![photo_2020-08-01_15-32-17](https://user-images.githubusercontent.com/14114916/89102740-43c68080-d40c-11ea-83c5-e7de9107a3f3.jpg)

We simplified the toast we'are using inside ntopng, now all of them are dismissable, so in this way, a user can temporarily close a toast. The severity level is shown by the background color of the toast title (in the bootstrap documentation the `small box` is used as a placeholder for icons).
The toasts are translucent (for the browsers who support the backdrop-filter CSS attribute).

For reference see the commit: https://github.com/ntop/ntopng/commit/46b50903e99aaaaa4cad62fd719b59a941651d42
