### ISSUE TITLE
page=historical type views lose "IPv4 Flows", "IPv6 Flows" "Talkers", and "Protocols" after a while

### ISSUE THREAD

**Issue by seismiccollision** [ntop/ntopng#426]
This only happens after ntopng has been running for a while (24 hours since the last bounce)
When I hit urls such as
https://172.0.0.1:3001/lua/if_stats.lua?if_name=2&page=historical
https://172.0.0.1:3001/lua/host_details.lua?ifname=2&host=1.1.1.1&page=historical

the "IPv4 Flows" tab disappears
the "Talkers" tab won't display anything
the "Protocols" tab won't display anything

and db_explorer.lua stops working

I know very little about mysql but I don't see any logs and mysql seems to be working

and the issue resolves by restarting ntopng

**Comment by simonemainardi** [comment]
@seismiccollision: @lucaderi made a fix in 031056a 2 days ago. Are you using the latest dev build?

**Comment by seismiccollision** [comment]
Oh no, updated 5 days ago
Thanks for letting me know and sorry for the trouble!

**Comment by seismiccollision** [comment]
Updated, I'm sure that will have fixed it
