### ISSUE TITLE
Can`t add hosts

### ISSUE THREAD

**Issue by lmoralesa** [ntop/ntopng#4260]
I just installed ntopng with community license, I go to the system option, then to the pool option to add a host, interace or pool member but it does not let me add anything, for example in the pool option, and I give the sign from +, I put a name, I choose the default option in the user script, then add but it doesn't add anything, so it is the same with the other options.
I would like help to see what I am doing wrong or if it is because of the type of license I have
<img width="1101" alt="Captura de Pantalla 2020-08-01 a la(s) 15 18 12" src="https://user-images.githubusercontent.com/23003333/89110663-4de77f80-d40a-11ea-89b9-6911c87f3850.png">

**Comment by simonemainardi** [comment]
It doesn't depend on the license. You just have to use page "Host Pool Members" to add members to host pools

<img width="405" alt="image" src="https://user-images.githubusercontent.com/3397663/89161322-bea9ab80-d572-11ea-988b-6c0f15805630.png">

We've reworked it. Will will prepare all the necessary documentation before the release.

**Comment by lmoralesa** [comment]
Thanks for your answer, the reason for my question is because I do the procedure of adding a new host as it tells me, I fill in the spaces requested and when I add, it does nothing, I would like to know if that is due to permissions or something I'm not doing well.
Thank you

**Comment by simonemainardi** [comment]
Are you using the latest dev version? Please, make sure to update and report.

**Comment by lmoralesa** [comment]
Hi, I'm using ntopng Community Edition v.4.1.200731

**Comment by squad1534** [comment]
I'm having the same or a similar problem with creating Host Pools and Host Pool Members when in System and they are not showing up on the interface side or in the flows where that host should have the Host Pool label. When I click the + in Host Pool List it refreshes to a blank screen with "Version - ntop.org - and time stamps" nothing in the body.

Community Edition v4.1.200904 (11335)

**Comment by simonemainardi** [comment]
please, add screenshots of the reported behavior.

**Comment by squad1534** [comment]
Here's what my Host Pool List looks like when I was able to add them in recent earlier versions:
![image](https://user-images.githubusercontent.com/28546897/92513269-05c43580-f1de-11ea-84fa-510d95925e16.png)

And here's what it looks like when I click the + sign to add a Host from the Host Pool Membership that contains 20 Hosts Pools I've added.
![image](https://user-images.githubusercontent.com/28546897/92514302-a8c97f00-f1df-11ea-8a3f-9ba30d34af83.png)
