### ISSUE TITLE
Unify alert format

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4261]
Alerts format must be unique. The green one is the old one and it has to migrate to the new one. Please define a lua module so we can use that one instead of inlining code.

![Screen Shot 2020-08-03 at 12 01 08](https://user-images.githubusercontent.com/4493366/89171182-14855000-d581-11ea-9cf0-77f670a5082f.png)
![Screen Shot 2020-08-03 at 11 07 11](https://user-images.githubusercontent.com/4493366/89171185-15b67d00-d581-11ea-9b58-35e84cf6036f.png)

**Comment by gabryon99** [comment]
Right now I edited the style. I'm developing a module to unify the styles. See the commit: https://github.com/ntop/ntopng/commit/e5facb83d576a52bf2db5beefcba138b68b42482
