### ISSUE TITLE
[Pools] Add the "All" Poll type 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4263]
In 
![Screen Shot 2020-08-04 at 09 41 28](https://user-images.githubusercontent.com/4493366/89267438-85873f00-d637-11ea-8fe0-81598b194092.png)
it is not possible to see in one page all the pools configured. it is requested to
- add a "All" pill that shows all pools regardless of their family
- Add a new column named "Family" with the pool family

**Comment by lucaderi** [comment]
As in manage_pools.lua the RESt endpoint is 

        endpoints = {
            get_all_pools  = string.format("/lua/rest/v1/get/%s/pools.lua", pool_type),
            add_pool       = string.format("/lua/rest/v1/add/%s/pool.lua", pool_type),
            edit_pool      = string.format("/lua/rest/v1/edit/%s/pool.lua", pool_type),
            delete_pool    = string.format("/lua/rest/v1/delete/%s/pool.lua", pool_type),
        },

For polling all polls a new ...v1/get/all/pools.lua is required.

@cardigliano @simonemainardi Is this acceptable for you ?

**Comment by simonemainardi** [comment]
given the semantic we have for the rest api, `/v1/<action>/<subject>/<item>` it think it is desirable to have `scripts/lua/rest/v1/get/pools/list.lua` or `scripts/lua/rest/v1/get/pool/list.lua`

**Comment by lucaderi** [comment]
@simonemainardi Depends on #4299. Done that @gabryon99 can complete the implementation

**Comment by simonemainardi** [comment]
REST API endpoint is complete. Please, the endpoint (see https://github.com/ntop/ntopng/issues/4299 for an example) to complete the implementation.

**Comment by gabryon99** [comment]
The `All` pool has been implemented. The http_prefix has been added in all the endpoints used by the pools.

**Comment by simonemainardi** [comment]
please, move the All tab as the last element of the list.

**Comment by gabryon99** [comment]
All Pools Tab has been moved at the end of the list of the tabs

<img width="1091" alt="Screenshot 2020-09-24 at 21 43 58" src="https://user-images.githubusercontent.com/14114916/94192314-10095380-feaf-11ea-84ce-303f849a08e7.png">
