### ISSUE TITLE
Add Endpoint Column

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4264]
![Screen Shot 2020-08-04 at 10 11 32](https://user-images.githubusercontent.com/4493366/89269934-e6644680-d63a-11ea-8ed4-eee807aa11df.png)

Add a new column that represents the endpoint type associated with a recipient

**Comment by gabryon99** [comment]
The endpoint column has been added, the commit is: https://github.com/ntop/ntopng/commit/dc322144edb46b505ce8d19d207bc467223d5f13

**Comment by lucaderi** [comment]
The commit looks good. Please add a filter with endpoint type

**Comment by lucaderi** [comment]
This is an example of filtering manu correctly styled:
- only the items families (that are present) are listed with the number or items in ()
![Screen Shot 2020-08-06 at 15 03 57](https://user-images.githubusercontent.com/4493366/89534991-1277f700-d7f6-11ea-8330-a626573dfbed.png)
This is what you did:
- all families are listed
- no quantity whatsoever
![Screen Shot 2020-08-06 at 15 03 38](https://user-images.githubusercontent.com/4493366/89534997-13a92400-d7f6-11ea-830d-25e2113217e8.png)

As of today you need to modify the code and make it consistent

**Comment by gabryon99** [comment]
<img width="706" alt="Screenshot 2020-08-14 at 10 18 41" src="https://user-images.githubusercontent.com/14114916/90229033-88441a00-de17-11ea-9619-8253d1ada5c9.png">

Now there is a counter near the filter name. If there is no data inside the datatable that matches the filter then the entry will be hidden.

**Comment by lucaderi** [comment]
Still pending
