### ISSUE TITLE
Filter menu doesn't scroll

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4267]
Filtering menus in ntopng tables do not scroll preventing the user to navigate the information as expected

![Screen Shot 2020-08-04 at 16 28 27](https://user-images.githubusercontent.com/4493366/89305991-981d6a80-d66f-11ea-99a5-b18035c32bca.png)

![Screen Shot 2020-08-04 at 16 28 33](https://user-images.githubusercontent.com/4493366/89305986-96ec3d80-d66f-11ea-95fb-0d56b1e2f3ea.png)

**Comment by gabryon99** [comment]
Fixed. Now when the dropdown height is too hight then it will crop it to max 20 rem. See the commit: https://github.com/ntop/ntopng/commit/7d2b0a179250c541f5e5008adb8c47faa7759ed2
