### ISSUE TITLE
Add DHCP as Exception for Unidirectional Traffic

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4268]
![Screen Shot 2020-08-05 at 21 57 32](https://user-images.githubusercontent.com/4493366/89458074-ba45e400-d766-11ea-9068-f501a36f9be8.png)

The above flow is a DHCP response that by nature is unidirectional: it should not trigger a flow status score

**Comment by simonemainardi** [comment]
For the implementation, it is requested to re-use the exclusion list already implemented for elephant and long-lived flows

<img width="787" alt="image" src="https://user-images.githubusercontent.com/3397663/89625209-be255380-d897-11ea-82c6-878f19634004.png">

The exclusion list must be populated with DHCP set as default.

**Comment by lucaderi** [comment]
@simonemainardi Sorry this is wrong. The algorithm that detected unidirectional traffic must discard DHCP from the list. This si not a frontend issue

**Comment by simonemainardi** [comment]
True. Other exceptions are:
- NetFlow
- sFlow
