### ISSUE TITLE
Sflow not collecting MAC Address in ntopng

### ISSUE THREAD

**Issue by seismiccollision** [ntop/ntopng#427]
I opened this under nprobe but it didn't seem to get noticed (and I'm not 100% sure it is nprobe's doing though I think it is)

Collecting Sflow by running nprobe as follows:
nprobe --zmq "tcp://*:5556" -i none -n none --collector-port 6343

I am able to collect sflow and provide it to ntopng but it seems like the L2 headers containing the src/dst mac addresses in the flow record are not processed so most hosts get lumped into "00:00:00:00:00:00"

**Comment by simonemainardi** [comment]
MAC addresses are properly exported and shown in ntopng hosts. You have to explicitly provide nprobe with a template that carries MAC information. nProbe does not export MAC addresses in its default template. This will work (see the last line):

```
nprobe -ieth0 --zmq=tcp://*:5556 -T"%IPV4_SRC_ADDR %IPV4_DST_ADDR %IPV4_NEXT_HOP \
%INPUT_SNMP %OUTPUT_SNMP %IN_PKTS %IN_BYTES %FIRST_SWITCHED \
%LAST_SWITCHED %L4_SRC_PORT %L4_DST_PORT %TCP_FLAGS %PROTOCOL \
%SRC_TOS %SRC_AS %DST_AS %IPV4_SRC_MASK %IPV4_DST_MASK  \
%IN_SRC_MAC %OUT_DST_MAC"
```

As already said, MAC addresses were shown in the host details page. I have now edited the flow details page to show mac addresses there as well. See this:

![image](https://cloud.githubusercontent.com/assets/3397663/13775978/dc34a476-eaa7-11e5-8ab4-067711daade2.png)

**Comment by seismiccollision** [comment]
@simonemainardi thank you so much!
