### ISSUE TITLE
Ldap login slow

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#4270]
06/Aug/2020 12:10:55 [LdapAuthenticator.cpp:400] ERROR: Could not bind to distinguishedName/dn/sn attribute

Generated by version 
Version
4.1.200730 (11009) - Enterprise
 M Edition

**Comment by zimbawe998** [comment]
Platform
x86_64-unknown-linux-gnu [x86_64][] - 64 bit

**Comment by zimbawe998** [comment]
CentOS 7.8.2003

**Comment by simonemainardi** [comment]
how can you tell this is an ntopng issue and not a wrong LDAP parameter specified?

**Comment by NicolasPSQ** [comment]
Hi Simone,
because we can do the login, the logon process goes to success but take very time....sometimes we need to push more times the button "login".

Thanks

**Comment by simonemainardi** [comment]
Do you have evidence this is due to a particular ntopng release and to to the network/ldap server? Error "Could not bind to distinguishedName/dn/sn attribute" is detected. Please, explain.

**Comment by NicolasPSQ** [comment]
Hello Simone,
is slowly also with the local authentication... Could you tell me where to look in logs of ntop to check if i found some errors?

Thanks

**Comment by simonemainardi** [comment]
Check Redis, e.g., use `redis-cli monitor` and see if there's an high activity. This could be the cause. After the login, is the ntopng UI reactive, or slow?

**Comment by NicolasPSQ** [comment]
Ok, thanks. I will check redis. No, after the login, the ntopng UI works as usual.

**Comment by NicolasPSQ** [comment]
I'm checking redis but don't find any particular problem.Maybe, it's depend of number of snmp devices added?

**Comment by NicolasPSQ** [comment]
Hi simone,
you can close this issue, because the problema was another on pc.

Thanks
