### ISSUE TITLE
[Pool] Excessive Pressure on Redis with SNMP

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4271]
This is what happens on redis when refreshing the SNMP page

1596709001.316997 [0 127.0.0.1:55334] "SETNX" "ntopng.cache.pools.snmp_device.pool_lock" "1"
1596709001.317124 [0 127.0.0.1:55334] "EXPIRE" "ntopng.cache.pools.snmp_device.pool_lock" "5"
1596709001.317282 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709001.317500 [0 127.0.0.1:55334] "DEL" "ntopng.cache.pools.snmp_device.pool_lock"
1596709001.317632 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709001.317774 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709001.317966 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709001.343439 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709001.343637 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709001.343984 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709001.344852 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709001.345022 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709001.345269 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709001.346345 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709001.346478 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709001.346721 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709001.915633 [0 127.0.0.1:55334] "SETNX" "ntopng.cache.pools.snmp_device.pool_lock" "1"
1596709001.921025 [0 127.0.0.1:55334] "EXPIRE" "ntopng.cache.pools.snmp_device.pool_lock" "5"
1596709001.922757 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709001.924105 [0 127.0.0.1:55334] "DEL" "ntopng.cache.pools.snmp_device.pool_lock"
1596709001.990704 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709001.993046 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709001.993861 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709001.998553 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.001732 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.002812 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.005668 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.008711 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.009982 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.013018 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.035595 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.045287 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.050436 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.050983 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.051366 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.052160 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.053576 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.054226 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.056833 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.058453 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.060509 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.062363 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.063506 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.069392 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.070452 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.070668 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.071150 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.079702 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.085283 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.101739 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.102201 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.102522 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.102697 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.102938 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.104129 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.104790 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.105671 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.106419 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.106825 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.107292 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.108230 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.108504 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.109053 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.111537 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.113125 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.115482 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.117226 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.118379 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.118797 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.120622 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.120825 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.121513 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.122068 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.122426 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.122737 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.123183 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.124157 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.124609 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.127623 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.128528 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.130663 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.131792 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.132142 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.133665 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.136967 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.150872 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.151795 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.152438 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.152649 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.152890 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.154011 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.155708 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.157198 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.157792 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.158254 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.158911 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.159319 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.163014 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.166226 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.168371 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.169297 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.173121 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.176142 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.176589 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.177006 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.178078 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.178383 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.178779 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.179143 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.179549 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.180248 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.181188 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.182474 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.183094 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.187862 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.202298 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.203356 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.204199 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.204812 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.205217 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.205973 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.206419 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.207094 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.207742 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.208179 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.208723 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.209827 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.214029 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.214536 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.215490 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.215828 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.216317 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.216750 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.217236 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.217590 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.218523 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.218933 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.219528 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.220408 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.221180 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.223360 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.224355 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.224536 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.224781 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.225209 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.225426 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.225668 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.228244 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.229496 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.230603 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.231246 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.231649 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.232284 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.232993 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.249656 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.250326 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.251591 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.251954 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.252488 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.253332 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.253565 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.253821 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.254219 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.254418 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.254729 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.255079 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.255214 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.255471 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.255748 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.255890 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.256214 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.256490 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.256665 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.256885 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.257140 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.257354 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.257579 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.257892 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.258055 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.258280 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"
1596709002.258701 [0 127.0.0.1:55334] "SMEMBERS" "ntopng.pools.snmp_device_pools.pool_ids"
1596709002.258845 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_0.details"
1596709002.259085 [0 127.0.0.1:55334] "GET" "ntopng.pools.snmp_device_pools.pool_id_3.details"

**Comment by simonemainardi** [comment]
Fixed in the above commits and companion pro commits. Pools were enumerated more than one time per device.

Currently, pools are enumerated only twice, regardless of the number of SNMP devices. One time in the page, and another time in the AJAX request.

```
 string stack traceback:
	...e/simone/ntopng/scripts/lua/modules/pools/base_pools.lua:186: in function 'base_pools._get_assigned_pool_ids'
	...e/simone/ntopng/scripts/lua/modules/pools/base_pools.lua:423: in function 'base_pools.get_all_pools'
	...ntopng/scripts/lua/pro/enterprise/snmpdevices_stats.lua:109: in main chunk
 string stack traceback:
	...e/simone/ntopng/scripts/lua/modules/pools/base_pools.lua:186: in function 'base_pools._get_assigned_pool_ids'
	...e/simone/ntopng/scripts/lua/modules/pools/base_pools.lua:540: in function 'base_pools.get_assigned_members'
	...png/scripts/lua/pro/enterprise/get_snmp_devices_list.lua:37: in main chunk
```
