### ISSUE TITLE
Device is added but error "The SNMP does not respond"

### ISSUE THREAD

**Issue by operations999** [ntop/ntopng#4272]
Hello,
We are running Enterprise edition of Ntopng / nprobe . After adding the device it gives error 
under https://xxxxxx:3000/lua/pro/enterprise/snmpdevices_stats.lua
The SNMP device does not respond.
Services are running fine but no visible traffic.
Any idea what is the issue?
Thanks

**Comment by simonemainardi** [comment]
when do you get this error? During SNMP device addition? Can you post a screenshot. Likely, the SNMP device is not responding to ntopng (either not responding or too slow)

**Comment by lucaderi** [comment]
I think this bug has been fixed with the recent code push. Please try again and in case of error please reopen the ticket. New packages will be available later today or overnight.
