### ISSUE TITLE
User scripts buttons poorly styled

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4274]
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/3397663/89625307-f62c9680-d897-11ea-826f-4f4d4cbea357.png">

- A white space is present when there's no edit
- Rounded edges are not consistent

**Comment by gabryon99** [comment]
Now the style is consistent with the other tables. See the commit: https://github.com/ntop/ntopng/commit/4574c667a01b3de4c7238f4f086c09c9464a1d6b
