### ISSUE TITLE
  How to get flows details via API.

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#4276]
I need get  real-time throughput, network and application delays, round-trip time (RTT), TCP statistics (retransmissions, out-of-sequence packets, packet loss), and transmitted bytes and packets through API,but I found nothing about it after reading all  RESTful API.

**Comment by simonemainardi** [comment]
https://www.ntop.org/guides/ntopng/api/rest/index.html

**Comment by MaoPann** [comment]
I have readed the REATful API,but not found information needed.Could you please give me more guidance,such as how to get the Round-trip time via API.

**Comment by cardigliano** [comment]
@MaoPann the information you need have been added to the API, you need to add the verbose parameter as in the example below. This will be available in the dev packages with the next build later today.

curl -u admin:password "http://192.168.0.1:3000/lua/rest/v1/get/flow/active.lua?ifid=1&verbose=true"
