### ISSUE TITLE
Segmentation fault with fritzbox

### ISSUE THREAD

**Issue by ChaosEmpire** [ntop/ntopng#4277]
I started the fritzbox script 
it logged into the box
tries to start ntopng

segementation fault

./fritzdump.sh: line 51: 80113 Done                    wget --no-check-certificate -qO- $FRITZIP/cgi-bin/capture_notimeout?ifaceorminor=$IFACE\&snaplen=\&capture=Start\&sid=$SID
     80114 Segmentation fault      (core dumped) | ntopng -i -

**Comment by ChaosEmpire** [comment]
ubuntu kernel: [20794.194390] [PF_RING] bind: stdin not found
ubuntu kernel: [20794.378582] ntopng[81337]: segfault at 74 ip 00007fd6fbe42fc4 sp 00007ffe1d15e618 error 4 in libpcap.so.1.9.1[7fd6fbe37000+26000]
ubuntu kernel: [20794.378590] Code: 89 df ff 13 85 c0 74 ee eb c4 66 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa c7 47 2c 01 00 00 00 c3 0f 1f 40 00 f3 0f 1e fa <8b> 47 74 85 c0 74 05 8b 47 64 c3 90 b8 fd ff ff ff c3 66 2e 0f 1f

**Comment by ChaosEmpire** [comment]
ubuntu kernel: [20794.194390] [PF_RING] bind: stdin not found
ubuntu kernel: [20794.378582] ntopng[81337]: segfault at 74 ip 00007fd6fbe42fc4 sp 00007ffe1d15e618 error 4 in libpcap.so.1.9.1[7fd6fbe37000+26000]
ubuntu kernel: [20794.378590] Code: 89 df ff 13 85 c0 74 ee eb c4 66 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa c7 47 2c 01 00 00 00 c3 0f 1f 40 00 f3 0f 1e fa <8b> 47 74 85 c0 74 05 8b 47 64 c3 90 b8 fd ff ff ff c3 66 2e 0f 1f

**Comment by lucaderi** [comment]
Please start ntopng with debugger and provide a trace. We don't have fireboxes

**Comment by ChaosEmpire** [comment]
"Please start ntopng with debugger"

can you please explain exacty what to do?
i cant find a debugging switch fo rmore logging

and seperate debugger? i m not a developer..just a user trying to see traffic of the router

**Comment by cardigliano** [comment]
It seems there is some issue with ntopng reading from stdin, however this is working for me using latest version. 
You should first of all make sure that the data stream is working as expected, you can replace "ntopng -i -" with "tshark -i -" for instance. If that is working, you should provide a crash trace (let ntopng generate a core dump and open it with gdb).

**Comment by simonemainardi** [comment]
@ChaosEmpire any news?

**Comment by ChaosEmpire** [comment]
I was messed up, after ntopng got updated by apt but my pfring was newer than the now required one
needed to deinstall, reinstall pfring (now its an older version than installed before from the repo)
(repo of ntopng is added to ubuntu, that makes me wonder why the ntopng does not met its own requirements)

But with newer ntopng and older pfring the fritzbox script started

just one broken pipe error

15/Aug/2020 17:25:28 [NtopPro.cpp:694] [LICENSE] License Type:  Time-Limited [Empty license file] License
15/Aug/2020 17:25:28 [NtopPro.cpp:714] [LICENSE] Validity:      Until Sat Aug 15 17:35:27 2020
15/Aug/2020 17:25:29 [PeriodicActivities.cpp:105] Started periodic activities loop...
Failed to print the table: Broken pipe
[PeriodicActivities.cpp:165] Each periodic activity script will use 2 threads
[NetworkInterface.cpp:2352] Started packet polling on interface stdin [id: 3]...

**Comment by cardigliano** [comment]
Were you able to check with tshark as suggested that traffic is flowing?

**Comment by lucaderi** [comment]
Closed for inactivity. Will reopen if necessary
