### ISSUE TITLE
Creation of Policies

### ISSUE THREAD

**Issue by razor3g** [ntop/ntopng#428]
Hello,

Please can you help us in the creation of policies? For instance, user policies that filter specific contents or block user from accessing things they are not supposed to.

**Comment by kYroL01** [comment]
Maybe you need to read these:

http://www.ntop.org/ndpi/how-to-enforce-layer-7-traffic-policies-using-ntopng/

http://www.ntop.org/ndpi/using-ntopng-to-implement-a-wifi-access-point-with-layer-7-traffic-enforcement/
