### ISSUE TITLE
license problem

### ISSUE THREAD

**Issue by lulululuej** [ntop/ntopng#4283]
Hi,
I had use the key to create the license and add to /etc/ntopng.license and save it on Help->About page, but it still the community version on web, then i type ntopng --version the log is below
![image](https://user-images.githubusercontent.com/68433978/89750674-8ae4fd80-daff-11ea-94c0-4320d8e11c62.png)

![weird](https://user-images.githubusercontent.com/68433978/89750682-96d0bf80-daff-11ea-9736-acf5db7753b1.PNG)

**Comment by simonemainardi** [comment]
did you restart ntopng after saving the license in /etc/ntopng.license?

**Comment by cardigliano** [comment]
Latest 4.0 build is working for me, please try restarting it.
