### ISSUE TITLE
1.Why I got the response of "-2-INVALID _INTERFACE",when I use the API as examples.

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#4284]
Why I got the response of "-2-INVALID _INTERFACE",when I use the API as examples.

**Comment by cardigliano** [comment]
@MaoPann could you provide the rest request you are running? (e.g. the full curl command)

**Comment by MaoPann** [comment]
curl-u admin:mp1234"http://192.168.0.100:3000/lua/rest/v1/get/interface/data.lua?ifid=0"

**Comment by simonemainardi** [comment]
Is `0` a valid id of an active interface?

You can use API call https://www.ntop.org/guides/ntopng/api/rest/examples_v1.html#get-actively-monitored-interfaces to check.

**Comment by MaoPann** [comment]
I use the command curl -u admin:admin "http://localhost:3000/lua/rest/v1/get/ntopng/interfaces.lua" but didn't have any response

**Comment by cardigliano** [comment]
Please use the correct password

**Comment by MaoPann** [comment]
yes I had  use the correct password

**Comment by cardigliano** [comment]
Please provide the output of:
curl -vu admin:mp1234 "http://192.168.0.100:3000/lua/rest/v1/get/ntopng/interfaces.lua"

**Comment by MaoPann** [comment]
C:\Users\maopa>curl -v admin:mp1234 "http://192.168.0.101:3000/lua/rest/v1/get/flow/active.lua?ifid=1&verbose=true"
* Rebuilt URL to: admin:mp1234/
* Port number ended with 'm'
* Closing connection -1
curl: (3) Port number ended with 'm'
*   Trying 192.168.0.101...
* TCP_NODELAY set
* Connected to 192.168.0.101 (192.168.0.101) port 3000 (#0)
> GET /lua/rest/v1/get/flow/active.lua?ifid=1&verbose=true HTTP/1.1
> Host: 192.168.0.101:3000
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 302 Found
< Set-Cookie: session=; path=/; expires=Thu, 01-Jan-1970 00:00:01 GMT; max-age=0; HttpOnly; SameSite=lax
< Set-Cookie: user=; path=/; expires=Thu, 01-Jan-1970 00:00:01 GMT; max-age=0;
< Set-Cookie: password=; path=/; expires=Thu, 01-Jan-1970 00:00:01 GMT; max-age=0;
< Location: /lua/login.lua?referer=192.168.0.101%3A3000%2Flua%2Frest%2Fv1%2Fget%2Fflow%2Factive.lua%3Fifid%3D1%26verbose%3Dtrue
* no chunk, no close, no size. Assume close to signal end
<
* Closing connection 0

**Comment by MaoPann** [comment]
C:\Users\maopa>curl -vu admin:mp1234 "http://192.168.0.101:3000/lua/rest/v1/get/flow/active.lua?ifid=1&verbose=true"
*   Trying 192.168.0.101...
* TCP_NODELAY set
* Connected to 192.168.0.101 (192.168.0.101) port 3000 (#0)
* Server auth using Basic with user 'admin'
> GET /lua/rest/v1/get/flow/active.lua?ifid=1&verbose=true HTTP/1.1
> Host: 192.168.0.101:3000
> Authorization: Basic YWRtaW46bXAxMjM0
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Cache-Control: max-age=0, no-cache, no-store
< Server: ntopng 4.1.200609 [Win64 [x64][Windows]]
< Pragma: no-cache
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< Content-Type: application/json; charset=utf-8
< Last-Modified: Tue, 08 August 2020 09:43:16 ?D1ú±ê×?ê±??
< Set-Cookie: session=; max-age=3600; path=/;  HttpOnly; SameSite=lax
* no chunk, no close, no size. Assume close to signal end
<
{"rc":-2,"rc_str":"INVALID_INTERFACE","rsp":[]}* Closing connection 0

**Comment by cardigliano** [comment]
You are getting redirected to the login page, this is an authentication issue, please check username and password.

**Comment by MaoPann** [comment]
I Confirmed my  username and password.
Is the web gui username and password?

**Comment by cardigliano** [comment]
Please also provide 
curl -vu admin: mp1234 "http://192.168.0.100:3000/lua/rest/v1/get/ntopng/interfaces.lua"

**Comment by MaoPann** [comment]
*   Trying 192.168.0.101...
* TCP_NODELAY set
* Connected to 192.168.0.101 (192.168.0.101) port 3000 (#0)
* Server auth using Basic with user 'admin'
> GET /lua/rest/v1/get/ntopng/interfaces.lua HTTP/1.1
> Host: 192.168.0.101:3000
> Authorization: Basic YWRtaW46bXAxMjM0
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 302 Found
< Set-Cookie: session=; path=/; HttpOnly; SameSite=lax
< Location: /lua/http_status_code.lua?message=not_found&referer=192.168.0.101%3A3000%2Flua%2Frest%2Fv1%2Fget%2Fntopng%2Finterfaces.lua&error_message=
* no chunk, no close, no size. Assume close to signal end
<

* Closing connection 0

**Comment by cardigliano** [comment]
@MaoPann what ntopng version are you running?

**Comment by simonemainardi** [comment]
I can confirm APIs are working on the latest dev build. Likely, this is the commit that has fixed the issue: https://github.com/ntop/ntopng/commit/0113b367c9824aba3f4bcefa7ee15f5e7148bd23

Please, try and update.

**Comment by simonemainardi** [comment]
@MaoPann any news?

**Comment by simonemainardi** [comment]
No feedback received. Closing.
