### ISSUE TITLE
Additional free location database (libloc)

### ISSUE THREAD

**Issue by ummeegge** [ntop/ntopng#4286]
Dear developers and community,
just wanted to leave a note for a new location database where no registration or license key is needed. The project has been developed by the IPFire project and calls libloc --> https://location.ipfire.org . Am currently not sure if this a topic of interest here but i nevertheless wanted to mentioned it.

With best regards,

Erik

For some more informations:
https://man-pages.ipfire.org/libloc/location.html
https://location.ipfire.org/how-to-use
https://blog.ipfire.org/post/on-retiring-the-maxmind-geoip-database

**Comment by lucaderi** [comment]
Hi @ummeegge thanks for the comment. Do you suggest us to move to libloc?

**Comment by ummeegge** [comment]
Hello lucaderi,
thanks for opening up a discussion. Since we (some IPFire users) have integrate unofficial the [ntopng community version also into IPFire](https://gitlab.com/ummeegge/ntopng-ipfire) environment and some users did have problems with the new Maxmind policies but IPFire reacts with an own solution for his firewall components, i thought it might be worth to go for a hint for news from the free software community. I won´t call it suggestion to move to but may a look through and thinking about if it can fits other needs for other projects since it is and will be also in the future free but also open for further development.

There are some Python and Perl bindings meanwhile available, am not 100% sure what does it need more or if it fits the needs in general to use it also for Ntopng, this was the main idea behind my request.

Best,

Erik

**Comment by simonemainardi** [comment]
@ummeegge would you be interested in taking care of this extension?

**Comment by ummeegge** [comment]
@simonemainardi of course i can give it a try. It might be great if you can point me in the correct direction to give this implementation a try.

Best regards,

Erik

**Comment by simonemainardi** [comment]
@ummeegge sorry for not getting back to you earlier. 

We have currently replaced Maxmind database (which requires registration) with the free https://db-ip.com/ whose format is interoperable with Maxmind and thus can be used with the same libmaxminddb libraries. These free databases are already freely distributed via `ntopng-data` package.

> for a new location database where no registration or license key is needed

We believe this addresses the issue so we are closing.
