### ISSUE TITLE
Inconsistent graph and browser crashes 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4288]
![Screen Shot 2020-08-11 at 16 40 40](https://user-images.githubusercontent.com/4493366/89916073-7126e180-dbf7-11ea-9893-041f89057dd5.png)

The above chart crashes on some browsers (e.g. Chrome) and while the traffic rate changes correctly, the chart is flat.

**Comment by gabryon99** [comment]
The bug has been fixed. See the commit: https://github.com/ntop/ntopng/commit/8e08eca7949b9dbec4b0f5eec99b2e202abfb25d
