### ISSUE TITLE
ntopng not save data in mysql (?)

### ISSUE THREAD

**Issue by iber-mi** [ntop/ntopng#429]
Hi, I have running the ntopng conf NetFlow interface, now the only thing that I can not run is to be stored in mysql for once cut not lose that data and to load them whenever you want, I do not know what I'm doing wrong because I see refurnishing all following the manual, execute this command:

ntopng -i tcp://127.0.0.1:5556 -F "mysql;localhost;ntopng;flows;ntopng;nt1234" -w 3001

and does not keep anything in my mysql DB or after stop. The table represents that flows creates the same ntopng when I run? Repersenta that ntopng is my database I created in the table flows mysqlm s etendria to create, then I created a user named ntopng for this BBDD and fiinalmente nt1234 password, there is something wrong?

I put the final message I get when I stop:
….
03/Mar/2016 17:56:08 [DB.cpp:155] Dump Flow: { "8": "192.168.1.106", "7": 64135, "12": "239.255.255.250", "11": 3702, "4": 17, "58": 0, "59": 0, "24": 3, "23": 2052, "2": 0, "1": 0, "22": 1457024136, "21": 1457024136, "json": "{ \"15\": \"0.0.0.0\", \"10\": \"6\", \"14\": \"6\", \"5\": \"0\", \"16\": \"0\", \"17\": \"0\", \"9\": \"0\", \"13\": \"0\", \"42\": \"335\" }" }
03/Mar/2016 17:56:08 [DB.cpp:173] [DB] INSERT INTO flows VALUES (NULL, 0, '192.168.1.106', 64135, '239.255.255.250', 3702, 17, 2052, 1457024136, 1457024136, 1, '{ "8": "192.168.1.106", "7": 64135, "12": "239.255.255.250", "11": 3702, "4": 17, "58": 0, "59": 0, "24": 3, "23": 2052, "2": 0, "1": 0, "22": 1457024136, "21": 1457024136, "json": "{ \"15\": \"0.0.0.0\", \"10\": \"6\", \"14\": \"6\", \"5\": \"0\", \"16\": \"0\", \"17\": \"0\", \"9\": \"0\", \"13\": \"0\", \"42\": \"335\" }" }');
03/Mar/2016 17:56:08 [NetworkInterface.cpp:826] Cleanup interface tcp://127.0.0.1:5556
03/Mar/2016 17:56:08 [DB.cpp:173] [DB] COMMIT;
03/Mar/2016 17:56:08 [HTTPserver.cpp:405] HTTP server terminated
03/Mar/2016 17:56:08 [AddressResolution.cpp:217] Address resolution stats [0 resolved][0 failures]

regards

**Comment by simonemainardi** [comment]
please, make sure user ntopng (identified by password nt1234) has privileges to create a mysql db on loclahost.

```
$ mysql -hlocalhost -untopng -pnt1234
mysql> show databases;
mysql> create database ntopng;
```

and see if any error appear.

**Comment by iber-mi** [comment]
Hi, thanks for the advice but I work a lot on mysql with other applications and as user permissions and other works, I've done what you told me and no mistake, all right db created me. But still store data in db ...
because it is?!

**Comment by iber-mi** [comment]
It has already worked for me, it seems that was because I had version 2.2, I installed the 2.3 and has already worked for me saving data in mysql.
Now I'm not able is to load the data to see with ntopng, as I do this? I tried the same command but I start from 0, do not load mysql data, any help?

**Comment by simonemainardi** [comment]
I am not sure to understand if yours is an issue related to 1) flow dump or 2) flow retrieval. Does ntopng write flows to MySQL? Can you see new rows appearing in MySQL tables? Or not?

**Comment by iber-mi** [comment]
Now if you write and see the new rows in mysql flow, the version was apparently used, updating and works for me.
But now I want to be able to load the data from mysql web by ntopng, and see that data when I want, how this is done?

**Comment by simonemainardi** [comment]
you should go to the historical page of interfaces or hosts: if mysql is enabled you have extra tabs that allow you to browse historical flows that are retrieved from mysql

**Comment by iber-mi** [comment]
Which enabled mysql? What do you mean exactly?

**Comment by simonemainardi** [comment]
see this http://www.ntop.org/ntopng/exploring-historical-data-using-ntopng-part-2/

**Comment by iber-mi** [comment]
thanks, but again does not save me again flows in the mysql db, I returned to install everything from 0 and still the same ... I need to pay license for this to work?

**Comment by simonemainardi** [comment]
mysql export is available in community edition so you don't have to pay. Could you please post ntopng startup string and console output?

**Comment by iber-mi** [comment]
Startup: #ntopng -i tcp://127.0.0.1:5556 -F "mysql;localhost;ntopng;flows;ntopng;ntopng31;" -w 3002 -v 

I have found that the mysql user and password and let me create db works, not by mysql permits.

Console output (I can not put all poruqe would not fit me here):

# 

....
08/Mar/2016 12:15:39 [ParserInterface.cpp:651] Not handled ZMQ field 15/15
08/Mar/2016 12:15:39 [ParserInterface.cpp:651] Not handled ZMQ field 10/10
08/Mar/2016 12:15:39 [ParserInterface.cpp:651] Not handled ZMQ field 14/14
08/Mar/2016 12:15:39 [ParserInterface.cpp:651] Not handled ZMQ field 5/5
08/Mar/2016 12:15:39 [ParserInterface.cpp:651] Not handled ZMQ field 16/16
08/Mar/2016 12:15:39 [ParserInterface.cpp:651] Not handled ZMQ field 17/17
08/Mar/2016 12:15:39 [ParserInterface.cpp:651] Not handled ZMQ field 9/9
08/Mar/2016 12:15:39 [ParserInterface.cpp:651] Not handled ZMQ field 13/13
08/Mar/2016 12:15:39 [ParserInterface.cpp:651] Not handled ZMQ field 42/42
08/Mar/2016 12:15:39 [CollectorInterface.cpp:146] [196] {"8":"216.58.210.174","12":"192.168.1.55","15":"192.168.1.1","10":6,"14":6,"2":2,"1":104,"22":1457435709,"21":1457435709,"7":443,"11":32407,"6":16,"4":6,"5":0,"16":0,"17":0,"9":0,"13":0,"42":2625}
08/Mar/2016 12:15:39 [ProtoStats.cpp:35] [IPv4]  3.54 MB/7.10 K Packets
08/Mar/2016 12:15:39 [ProtoStats.cpp:35] [IPv6]  0 B/0.00 Packets
08/Mar/2016 12:15:39 [ProtoStats.cpp:35] [ARP]   0 B/0.00 Packets
08/Mar/2016 12:15:39 [ProtoStats.cpp:35] [MPLS]  0 B/0.00 Packets
08/Mar/2016 12:15:39 [ProtoStats.cpp:35] [Other] 0 B/0.00 Packets
08/Mar/2016 12:15:40 [Ntop.cpp:1238] Interface tcp://127.0.0.1:5556 [running: 0]
08/Mar/2016 12:15:40 [main.cpp:48] Deleted PID /var/tmp/ntopng.pid [rc: 0]
08/Mar/2016 12:15:40 [NetworkInterface.cpp:407] Flushing host contacts for interface tcp://127.0.0.1:5556
08/Mar/2016 12:15:40 [Flow.cpp:1326] Emitting Flow: { "8": "192.168.1.55", "7": 32764, "12": "192.168.0.254", "11": 10000, "4": 6, "57590": 161, "57591": "CiscoVPN", "6": 18, "2": 7, "1": 896, "24": 5, "23": 416, "22": 1457435706, "21": 1457435706, "json": { "15": "192.168.0.254", "10": "6", "14": "6", "5": "0", "16": "0", "17": "0", "9": "0", "13": "0", "42": "2556" }, "57595": 0.000000, "57596": 0.000000, "NTOPNG_INSTANCE_NAME": "debian8", "INTERFACE": "tcp:\/\/127.0.0.1:5556", "PASS_VERDICT": true } etc.....
08/Mar/2016 12:15:40 [NetworkInterface.cpp:1459] Cleanup interface tcp://127.0.0.1:5556
08/Mar/2016 12:15:40 [Profiles.cpp:36] Destroying Profiles
08/Mar/2016 12:15:40 [HTTPserver.cpp:518] HTTP server terminate
08/Mar/2016 12:15:40 [AddressResolution.cpp:54] Address resolution stats [3 resolved][1 failures]
#

**Comment by simonemainardi** [comment]
if your password doesn't end in `;` you should remove the last occurrence of   `;` from the -F string:

`-F "mysql;localhost;ntopng;flows;ntopng;ntopng31"`

also attach a txt file with the whole console output if the issue persists

**Comment by iber-mi** [comment]
all right, thank you very much, for one thing and see what happens ...

Now I will try to see if I can load the data into ntopng

**Comment by iber-mi** [comment]
Not to load data from MySQL to ntopng, I've read me: http://www.ntop.org/ntopng/exploring-historical-data-using-ntopng-part-2
but not clear how came to see tabs after chart: IPv4 Flows, IPv6Flows, Talkers, Protcols, Pcaps, my these tabs do not appear to me, I do not know where to access, I access the port: 3000 web that is eth0? or I access: Flow 3002 is the team that I have saved data on db? I've tried the 2 and nothing ... Help please.

**Comment by lucaderi** [comment]
@iber-mi You need the pro version of ntopng. With the community edition those tabs do not appear

**Comment by iber-mi** [comment]
Now I have the pro version and I still see those tabs. Not because the link I've been through before not teach the URL, you may find it so, you could tell that URL access those tabs? 
Example: http://127.0.0.1:3000/lua/if_stats.lua?if_name=eth0&page=historical  here I see the chart tab, but no more. This is what appears tod me down the web ntopng:

© 1998-2016 - ntop.org 
Generated by ntopng Professional v.2.3.160307
for user admin and interface eth0

**Comment by simonemainardi** [comment]
can't get the point. please post screenshots.

**Comment by iber-mi** [comment]
Send tab screen chart to see if you see something.

![chart](https://cloud.githubusercontent.com/assets/17645260/13609299/960eefc8-e558-11e5-93a2-606530fb1591.png)

**Comment by simonemainardi** [comment]
no historical tabs are present: very likely you didn't enable MySQL with -F . Check configuration.

**Comment by iber-mi** [comment]
Yes, it is true now me 2 tabs appear more with -F, Talkers and Protcols, but show me the data and still IPv4 and v6 tabs appear, because it could happen? Thanks for the help.

![cahrt2](https://cloud.githubusercontent.com/assets/17645260/13609634/190f2a54-e55a-11e5-90ba-cd585697e7de.png)

**Comment by simonemainardi** [comment]
interface is not receiving data...

**Comment by iber-mi** [comment]
but I have to receive data to load my mysql db? I can not upload data without receiving data?

**Comment by simonemainardi** [comment]
you can also retrieve old recorded data but interface name and ntopng instance name must be the same (it looks like you renamed it).

**Comment by iber-mi** [comment]
And it works great! Thank you.

Pcap'd know how could download file? Not leave me when doi to extract pacap. Unknow response tells me.

**Comment by simonemainardi** [comment]
in order to download pcap you need and nBox with n2disk enabled. issue is solved, don't forget to star ntopng!

**Comment by iber-mi** [comment]
To install this I need a license payment? or it is not necessary?

**Comment by iber-mi** [comment]
This error may be due? data do not appear on the tab Protocols:

HTTP/1.1 500 Internal server error Content-Type: text/html Connection: close   Script "/usr/share/ntopng/scripts/lua/if_stats.lua" returned an error:
.../share/ntopng/pro/scripts/lua/modules/nv_graph_utils.lua:617: bad argument #1 to 'pairs' (table expected, got userdata)

**Comment by iber-mi** [comment]
Hello! some help?

**Comment by simonemainardi** [comment]
hi, we've made some fixes. backages are being build. Update tomorrow and let us know.

**Comment by iber-mi** [comment]
ok, and install n Box and n2disk, some kind of paid license is required to run this?

**Comment by lucaderi** [comment]
You need a license for n2disk, not for the nBox.

**Comment by iber-mi** [comment]
License payment? or is there free? You buy in http://shop.ntop.org?

**Comment by lucaderi** [comment]
Yes use the shop

**Comment by simonemainardi** [comment]
Solution given. Closing.

**Comment by alwaysbegood** [comment]
hello, can you help me? i'm stuck here
"you can also retrieve old recorded data but interface name and ntopng instance name must be the same (it looks like you renamed it)." 
can you give me example?

**Comment by lucaderi** [comment]
In essence do not reset redis otherwise the association interface name/id will be lost.
