### ISSUE TITLE
Drill down protocol categories

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4290]
![Screen Shot 2020-08-11 at 17 27 32](https://user-images.githubusercontent.com/4493366/89916525-fd390900-dbf7-11ea-9b63-e634a2811501.png)

Currently it is not possible to see what protocols are listed under the categories. This ticket requests such protocols to be listed so that it is possible to see under a category what protocols traffic is observed.

The above feature is requested for all elements, such as interfaces and hosts.

**Comment by simonemainardi** [comment]
Information is already available at the following page

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/3397663/89992482-9b26e500-dc85-11ea-82bd-b87f83690578.png">

It is requested to add a link to this page with the filter already set.

**Comment by lucaderi** [comment]
@simonemainardi Not quite. In the picture above, the backend must report the amount of traffic. Depicting it is simple. Please provide some code to do that. The image you pasted is not enough

**Comment by lucaderi** [comment]
Please @simonemainardi handle this ticket as it is mostly about the backend. What is requested it to provide a breakdown per protocol/category and either
- transform the category name in a HREF that jumps on a page that shows the breakdown
- add the breakdown online (I prefer this)

**Comment by simonemainardi** [comment]
Implemented as requested:

![image](https://user-images.githubusercontent.com/3397663/90775878-acad6400-e2f9-11ea-945b-b62cb8591543.png)

![image](https://user-images.githubusercontent.com/3397663/90777193-5d683300-e2fb-11ea-8f2f-afe88f1a08df.png)
