### ISSUE TITLE
flow.lua script failure

### ISSUE THREAD

**Issue by stump-ed** [ntop/ntopng#4291]
I'm seeing a metric crap-ton of the following in the journal:

[AlertCheckLuaEngine.cpp:167] WARNING:Script failure[/usr/share/ntopng/scripts/callback/share/ntopng/scripts/callbacks/interface/flow.lua] [/usr/share/ntopng/scripts/interface/flow.lua:226: type 'function' is not supported by JSON.]

and the flow counts are continuously increasing - they never seem to age out...
I've updated ntopng to the most recent release 

Version | 4.1.200807 (11129) -  Enterprise M Edition
-- | --
Ubuntu 18.04.4 LTS
Debian buster/sid [x86_64][Ubuntu 18.04.4 LTS] - 64 bit
ntopng  --interface "tcp://127.0.0.1:5556" --http-port "3000" --local-networks  "10.0.0.0/8,172.10.0.0/24,172.16.1.0/24,172.20.1.0/24" --data-dir  "/var/lib/ntopng" --max-num-flows "6000000" --max-num-hosts "150000"
3.3.0-2661-95dfbdc6
7.58.0
4.4.0
5.11.2
1.7.0
1.3
4.0.9
3.7
Lua 5.3.5
4.2.5
1.3.1 Includes support for MaxMind  and DB-IP  Geolocation databases.
2.9.1 / 3.0

**Comment by lucaderi** [comment]
Several people reported that the issue with flows not expiring was solved with the release you are running. So there is something special in your setup. I suggest to 
- apt-get remove ntopng ntopng-data
- rm -rf /usr/share/ntopng
- apt-get install ntopng ntopng-data

Then report is something has changed.

I suggest to reduce --max-num-flows  and --max-num-hosts to more reasonable values.
