### ISSUE TITLE
ElasticSearch export:  Export queue too long  expect drops

### ISSUE THREAD

**Issue by mroe1234** [ntop/ntopng#4292]
running Version: ntopng Enterprise M Edition v.4.1.200810 
Uptime: 1 Day, 07:04:50

From Interface page:
Dropped Flows | 2,193,579 [0.21%]

From log:
Aug 10 18:17:28 schnoz ntopng: [ElasticSearch.cpp:69] WARNING: [ES] Export queue too long [32768]: expect drops
Aug 10 18:17:28 schnoz ntopng[28321]: 10/Aug/2020 18:17:28 [ElasticSearch.cpp:69] WARNING: [ES] Export queue too long [32768]: expect drops
Aug 10 18:55:06 schnoz ntopng: [ElasticSearch.cpp:69] WARNING: [ES] Export queue too long [32768]: expect drops
Aug 10 18:55:06 schnoz ntopng[28321]: 10/Aug/2020 18:55:06 [ElasticSearch.cpp:69] WARNING: [ES] Export queue too long [32768]: expect drops

/etc/ntopng/ntopng.conf
-G=/var/run/ntopng.pid
-i tcp://127.0.0.1:5556
-i tcp://*:1234c
-m 192.168.0.0/16
-F es;_doc;ntopng-%Y.%m.%d;http://elastic.haproxy.local:9200/_bulk; #haproxy load balanced 5 elasticsearch servers
-X 100000000
-x 10000000

**Comment by simonemainardi** [comment]
You ES queue gets filled, that is, there's not enough time for ntopng to export queued flows to ElasticSearch. 

However, this seems just a sporadic error (occurred at 18:17 and 18:55) and only the 0.21% of flows have been dropped, so it doesn't seems to be a bug or something structurally wrong.

**Comment by simonemainardi** [comment]
how many active hosts/flows are you processing? How much traffic are you processing?

**Comment by mroe1234** [comment]
the top bar says ~65k local and 50k remote, and flows are almost 1m

**Comment by simonemainardi** [comment]
It doesn't seems to be a bug for me. With 1M active flows, losing 0.21% sporadically is likely normal and may be due to load spikes on the machine for example. You have basically lost 2M out of 1B+ exported flows, which is expected on a loaded machine.

Feel free to reopen if this percentage becomes higher or losses are consistent.
