### ISSUE TITLE
Additional alert type "acknowledged"

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#4293]
Hello,
In actual ntopng alarms are acknowledged automatically, without user input.
In certain circumstances it is required, that the user needs to acknowledge an alarm.
To support the user, the alarm icons could be gray, when the alarm is not active anymore, but not acknowledged yet.
Thank you.

**Comment by lucaderi** [comment]
I would add also the (optional) ability to auto-acknowledge alerts after some time by marking it as auto-acknowledge.

Implementing this ticket will also require the implementation of "mass ACK" in case an administrator needs to ack several alerts of a selected type (or all alerts)

**Comment by martinscheu** [comment]
works great with current version, we are letting operators work with it, thanks for implementing
