### ISSUE TITLE
Add layer-2 view

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#43]
In the old ntop (non -ng) it was possible to show layer 2 statistics and to display mac address symbolic name (e.g. see https://code.wireshark.org/review/gitweb?p=wireshark.git;a=blob_plain;f=manuf).

**Comment by ariava** [comment]
Was addressed in 0d2eeeb, sorry.

**Comment by lucaderi** [comment]
Unfortunately the above commit addresses only the symbolic MAC display. No L2 stats (similar to L2 conversations in wireshark) is implemented yet.

**Comment by ariava** [comment]
@lucaderi sorry, will do

**Comment by lucaderi** [comment]
Already implemented.
