### ISSUE TITLE
Compilation aborted : undefined reference to `ndpi_detection_giveup' and `ndpi_strnstr'

### ISSUE THREAD

**Issue by xgerligand** [ntop/ntopng#430]
Hi,
Compilation of ntopng aborted with these errors :

src/NetworkInterface.o: In function `NetworkInterface::processPacket(timeval const*, unsigned long, ndpi_ethhdr*, unsigned short, ndpi_iphdr*, ndpi_ipv6hdr*, unsigned short, unsigned short, pcap_pkthdr const*, unsigned char const*, int*, int*, unsigned short*)':
/usr/src/ntopng/src/NetworkInterface.cpp:804: undefined reference to`ndpi_detection_giveup'
src/Flow.o: In function `Flow::dissectBittorrent(char*, unsigned short)':
/usr/src/ntopng/src/Flow.cpp:1820: undefined reference to`ndpi_strnstr'
collect2: error: ld returned 1 exit status
Makefile:134: recipe for target 'ntopng' failed
make: **\* [ntopng] Error 1

Probably since adding support for the new  ndpi_detection_giveup() nDPI call.
Regards

**Comment by kYroL01** [comment]
Did you update nDPI before ?

**Comment by xgerligand** [comment]
Yes absolutly, i ahve done a 'git pull' of nDPI.

**Comment by kYroL01** [comment]
I updated right now nDPI and ntopng and no compilation error rise-up.
nDPI -> git pull && make
ntopng -> git pull && make

**Comment by xgerligand** [comment]
I have deleted nDPI and ntopng, and 'git clone' the two.
I got the same error...Maybe depend of compiler
 /usr/src $ gcc -v
Using built-in specs.
COLLECT_GCC=/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.3/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/4.9.3/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc-4.9.3/configure --disable-libssp --enable-multilib --enable-version-specific-runtime-libs --enable-libmudflap --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.3 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.9.3 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.9.3/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.9.3/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4.9 --enable-libstdcxx-time --enable-__cxa_atexit --enable-clocale=gnu --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --with-system-zlib --enable-obsolete --disable-werror --enable-secureplt --enable-lto --without-cloog --with-bugurl=http://bugs.funtoo.org --with-pkgversion='Funtoo 4.9.3-r1' --with-mpfr-include=/var/tmp/portage/sys-devel/gcc-4.9.3-r1/work/gcc-4.9.3/mpfr/src --with-mpfr-lib=/var/tmp/portage/sys-devel/gcc-4.9.3-r1/work/objdir/mpfr/src/.libs --enable-libgomp --build=x86_64-pc-linux-gnu --enable-libgomp --enable-languages=c,c++,fortran --disable-libgcj --disable-esp --disable-libsanitizer
Thread model: posix
gcc version 4.9.3 (Funtoo 4.9.3-r1)

**Comment by simonemainardi** [comment]
the linker is complaining about  `ndpi_detection_giveup`. The function has been added 3 days ago in https://github.com/ntop/nDPI/commit/462368f959daf9ffc72fc0fd91ef62a03487354c so i guess the linker is not pointing to the latest nDPI. Check for older versions in your system and remove them.

**Comment by lucaderi** [comment]
Correct. update nDPI and it will work
