### ISSUE TITLE
Return successful message when performing REST operations

### ISSUE THREAD

**Issue by gabryon99** [ntop/ntopng#4300]
It's requested to return a successful message when performing REST operation such as 'Add SNMP Device/Edit SNMP Device/Remove SNMP Device'. The message must be neutral as possible and descriptive.

Example:
1) Add SNMP Device
2) If the add was successful then the returned body of the request may contain:
```
{
    "rc_str": "OK",
    "rsp": {
          "status": {
                "message": "Device added correctly!"
          }
    },
    "rc": 0
}
```

This ticket depends on #4279

**Comment by simonemainardi** [comment]
Implemented. Now both success and error codes are returned also in a human readable string.

To maintain compatibility, error code string is still returned in `"rc_str"`, and the human-readable, localized i18n string is returned in `"rc_str_hr"`

Example responses:

```
{"rc_str_hr":"SNMP device added successfully","rsp":{"added_devices":[{"ip":"127.0.0.1","name":"127.0.0.0"}]},"rc_str":"SNMP_DEVICE_ADDED_SUCCESSFULLY","rc":0}
{"rc_str_hr":"Success","rc_str":"OK","rsp":{"edit_devices":[{"ip":"127.0.0.1","name":"127.0.0.1"}]},"rc":0}
{"rc":0,"rsp":[],"rc_str":"SNMP_DEVICE_DELETED_SUCCESSFULLY","rc_str_hr":"SNMP device deleted successfully"}
```

Localization is supported. Language is chosen on the basis of the locale configured for the user which is performing the API call.
