### ISSUE TITLE
Package update does not work on CentOS

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4301]
![Screen Shot 2020-08-14 at 12 25 34](https://user-images.githubusercontent.com/4493366/90240357-5fc51b80-de29-11ea-8424-1a17b051b1b7.png)

This is the message that is reported when updating "ntopng Enterprise M Edition v.4.1.200807": no updates, just this message.

**Comment by cardigliano** [comment]
This has been fixed, waiting for a feedback from the user.
Also, updates failures are now reported, if any (e.g. maintenance expired, service disabled, etc.)
