### ISSUE TITLE
SNMP: Add filter to select interfaces Up with traffic detected

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4303]
![Screen Shot 2020-08-14 at 12 51 10](https://user-images.githubusercontent.com/4493366/90242226-e4fdff80-de2c-11ea-8ba2-037c091435f5.png)
![Screen Shot 2020-08-14 at 12 51 02](https://user-images.githubusercontent.com/4493366/90242231-e62f2c80-de2c-11ea-8669-6807bc52d502.png)

In addition to interfaces Up, add a new filter item for interface Up with traffic detected (i.e. those interfaces that are really in use)

**Comment by simonemainardi** [comment]
Implemented:

![image](https://user-images.githubusercontent.com/3397663/90413837-4f25d700-e0af-11ea-8077-ec640b761790.png)
