### ISSUE TITLE
SNMP Flow Ratio is broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4304]
![Screen_Shot_2020-08-14_at_13_01_53](https://user-images.githubusercontent.com/4493366/90243118-981b2880-de2e-11ea-94bc-6793cea42069.png)
![Screen_Shot_2020-08-14_at_13_02_07](https://user-images.githubusercontent.com/4493366/90243124-99e4ec00-de2e-11ea-8199-3bdd2a9c6019.png)

**Comment by simonemainardi** [comment]
I've let the instance run for a couple of hours with NetFlow and I get pretty accurate results:

![image](https://user-images.githubusercontent.com/3397663/90425224-b5b2f100-e0bf-11ea-84cc-e95b68e7bb4f.png)

Can you please explain how to reproduce? Are you using NetFlow or sFlow? Is there any *collection filter* or similar which may cause the traffic received from the flows to be much less that those received via SNMP? Can you also attach a screenshot of the SNMP interfaces traffic?

**Comment by simonemainardi** [comment]
Verified working also on the reported machine

![image](https://user-images.githubusercontent.com/3397663/90654605-d8b8de80-e240-11ea-9112-877f25a59877.png)

As both flow devices timeseries and snmp interface timeseries go back in time for 1 hour, chances are a timeseries was incomplete or missing at that time (e.g. SNMP was just enabled, flow devices timeseries were just enabled).

**Comment by lucaderi** [comment]
1h is way too much: it must be in sync with SNMP or netflow

**Comment by simonemainardi** [comment]
synced with the SNMP pool interval which is 5 minutes. Results are still consistent. Notes describe how this ratio is calculated and the time interval used.

![image](https://user-images.githubusercontent.com/3397663/90664026-bb890d80-e24a-11ea-8640-a67adc4afaef.png)
