### ISSUE TITLE
How do we add a new language/locale for ntop?

### ISSUE THREAD

**Issue by fuqiangleon** [ntop/ntopng#4306]

**Comment by simonemainardi** [comment]
Let's say you want to do french localization, you can just copy the `https://github.com/ntop/ntopng/blob/dev/scripts/locales/en.lua into` `fr.lua`, then edit `fr.lua` by localizing the strings on the right, e.g.:

from

["packets_page"] = {
    ["arp_distribution"] = "ARP Distribution",
    ["ip_version_distribution"] = "IP Version Distribution",

to

["packets_page"] = {
    ["arp_distribution"] = "Distribution ARP",
    ["ip_version_distribution"] = "Distribution IP",

It is essential that the left strings (which are the IDs) stay unchanged (e.g. "packets_page" must *not* be localized). If you want to test the localization you can add "es" to the lua table here: https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/locales_utils.lua#L17 and then create a new ntopng user with that language.

Once done, you can send us a pull request for inclusion in the dev branch
