### ISSUE TITLE
Broken Endpoint Validation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4308]
Problems
1. It is not specified what are the required fields constraints to satisfy. Example the endpoint name must be 4 chars or more (why 4?)
![Screen Shot 2020-08-17 at 14 46 18](https://user-images.githubusercontent.com/4493366/90397642-702efd80-e098-11ea-902d-a352b6cedd53.png)
2. The Server IP is not properly validated
![Screen Shot 2020-08-17 at 14 47 59](https://user-images.githubusercontent.com/4493366/90397806-aec4b800-e098-11ea-9cb1-c56889cdb57a.png)
3. Email sender address validation is broken
![Screen Shot 2020-08-17 at 14 48 55](https://user-images.githubusercontent.com/4493366/90397875-d156d100-e098-11ea-88b8-5cfd71d4bd7d.png)

**Comment by gabryon99** [comment]
Now if the user types a hostname for the SMTP Server then a DNS Resolve will be performed by the backend to check if the hostname exists. See the commit: https://github.com/ntop/ntopng/commit/5797c7c8fdc13c73d619e86077d8c9a1f775825d

**Comment by gabryon99** [comment]
I have changed the pattern used for emails. See the new commit: https://github.com/ntop/ntopng/commit/fc2275aaadaf20c6cd5e2a1055915c6ab613bc06

**Comment by lucaderi** [comment]
Seems to work
