### ISSUE TITLE
How-to configure

### ISSUE THREAD

**Issue by CyberbreinAirw0lf** [ntop/ntopng#4309]
Two questions on how-to configure within ntopng.

(1) – In some customers cases, part of the webtraffic could be is running through a proxy/loadbalancer.
In our lab, this would be the HTTP/HTTPS-traffic running over TCP port 8888
Is there a way to configure this that it can be reported on?

(2) – There are 3 host pools based on 2 subnets being 192.168.2.0/14 and 192.168.139.0/24:
- DMZ: 192.168.2.0/24
- User:192.168.139.1-127 (aka 192.168.139.1/25)
- Private-cloud: 192.168.139.129-254 (aka 192.168.139.129/25)
However, as seen by the attached chart, most traffic is assigned to the default pool.
Which seems all traffic related to 192.168.139.0/24.
What am I missing?

![image](https://user-images.githubusercontent.com/64280991/90524823-d25a3200-e16e-11ea-8c66-85c28a3e3a88.png)

Thank you - Will

**Comment by simonemainardi** [comment]
> (1) – In some customers cases, part of the webtraffic could be is running through a proxy/loadbalancer.
In our lab, this would be the HTTP/HTTPS-traffic running over TCP port 8888
Is there a way to configure this that it can be reported on?

You can configure TCP port 8888 as a custom protocol. See https://www.ntop.org/guides/ntopng/web_gui/categories.html?highlight=custom#custom-applications

> (2) – There are 3 host pools based on 2 subnets being 192.168.2.0/14 and 192.168.139.0/24:

Likely, members are not correctly assigned to pools. Visit page "Host Pool Members", then make sure members are correctly assigned. If you are using VLANs, then VLANs must be specified as well.

![image](https://user-images.githubusercontent.com/3397663/90533492-e6a32c80-e178-11ea-88f4-e104f9e29fbd.png)

**Comment by simonemainardi** [comment]
do you have any feedback so far?

**Comment by simonemainardi** [comment]
Solution given. No feedback received. Closing.
