### ISSUE TITLE
Interface Traffic Breakdown (Feature Request)

### ISSUE THREAD

**Issue by markfoodyburton** [ntop/ntopng#431]
Some way of visiting the breakdown of traffic between interfaces would be helpful. For instance if you have a combined 'view' of multiple interfaces, it would be nice to know the difference between the traffic on each one. The code for this seems to exist in drawRRD (it supports multiple data series), but I see now way of requesting this through the User Interface. 
To make this concrete, I have 2 PPP interfaces, on a router that serves a local network, I want to visualise how much traffic is passing on each ppp interface.

Cheers

Mark.

**Comment by simonemainardi** [comment]
The feature you are suggesting is already available. If you use an interface view then you can see interface traffic breakdown from the view historical page:
![image](https://cloud.githubusercontent.com/assets/3397663/13598125/792868da-e51c-11e5-819f-3c28c211b0d1.png)

**Comment by simonemainardi** [comment]
For the sake of completeness: the interface breakdown is only available in the professional version
