### ISSUE TITLE
Using ElasticSearch

### ISSUE THREAD

**Issue by CyberbreinAirw0lf** [ntop/ntopng#4310]
I’m really struggling with forwarding data to ElasticSearch.
I have set things up to the extend that Elastic accepts data from Beats.
Where Beats equals Filebeat, Packetbeat, Auditbeat and Wineventbeat.

But forwarding data from ntopng to Elastic seems to be a bridge to far.
Is there somewhere a step-by-step document?
Or at least some pointers how to start?

Thank you - Will

**Comment by simonemainardi** [comment]
https://www.ntop.org/guides/ntopng/advanced_features/flows_dump.html#flowdumpelasticsearch
