### ISSUE TITLE
Cannot get cookie for user

### ISSUE THREAD

**Issue by TimotheusBachinger** [ntop/ntopng#4312]
Hi ntop,

We currently cannot get the cookie from our ntop instance. Can you reproduce this error on your side? 
It seems also rest_utils.lua was changed yesterday. 
```
curl -u admin:password -d '{"username": "user1"}' http://xxx.abc.def.com:3000/lua/rest/v1/get/ntopng/session.lua
HTTP/1.1 302 Found
Set-Cookie: session=; path=/; HttpOnly; SameSite=lax
Location: xxxxx

/usr/share/ntopng/scripts/lua/modules/rest_utils.lua:55: attempt to index a nil value (local 'ret_const')
```
Thanks a lot
Regards
Timi

**Comment by simonemainardi** [comment]
Thanks for reporting. New builds are in progress. Please wait a couple of hours and try again.

**Comment by TimotheusBachinger** [comment]
Thanks Simone, cookies are working again.
