### ISSUE TITLE
Add SNMP port toggle 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4315]
In case SNMP is enabled it is possible to detect on which port a given host is connected. A host can be observed on multiple ports is trunk ports are considered. For the sake of this ticket, we defina a host connected to a port when the such port is an access port (i.e. untagged with no trunk set).

This ticket requires to implement two items
- in the SNMP device page, it is required to implement a toggle per port that changes the port status (up -> down or down - up) in case the write community for this device is set, or SNMPv3 is used. Note tha even in this case errors might be encountered as ports can be prevented from changing status.
- in the host page, in case it is possible to locate a host on a SNMP port, it is requested to add an anchor for toggling port status. Such anchor will redirect to the exact port on the SNMP device page (i.e. it is required to redirect to such SNMP page and not to re-implement this functionality twice in both the host and SNMP device page).

Ticket #3833 depends on this ticket.

**Comment by simonemainardi** [comment]
SNMP port toggle added. An "Actions" column has been added with a direct link to the interface "config" page.

![image](https://user-images.githubusercontent.com/3397663/90893465-5571c700-e3bf-11ea-9e3f-6d3aae30e82c.png)

The port admin status can be toggled from then "config" page as any other configuration related to the interface:

![image](https://user-images.githubusercontent.com/3397663/90893519-6d494b00-e3bf-11ea-9ff6-c9ec5a86c07c.png)

Errors are handled ad well so, upon failing changes, the user is notified.

As requested, an anchor in the host page, when the host is localized, has been added as well

![image](https://user-images.githubusercontent.com/3397663/90894430-e2695000-e3c0-11ea-878f-640044c16dff.png)
