### ISSUE TITLE
Add option for disable blocklist updates

### ISSUE THREAD

**Issue by Aikatsui** [ntop/ntopng#4317]
i dont like ntopng often connect to blocklist servers. i can manually block however it's good to have option in software then add 'Disabled' option to update frequency

Setting path
settings > category lists > a list > action > edit > update frequency

**Comment by simonemainardi** [comment]
This is already supported. You can disable lists you don't want to be fetched by ntopng.

**Comment by Aikatsui** [comment]
@simonemainardi  No. i want to keep certain lists enabled but prevent get updated often (hourly/daily)
v.4.0.200511
