### ISSUE TITLE
Backport some REST features to 4.0

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4319]
The following tickets code need to be back ported onto the 4.0 stable
- https://github.com/ntop/ntopng/issues/4217
- https://github.com/ntop/ntopng/issues/4218
- https://github.com/ntop/ntopng/issues/4219
- https://github.com/ntop/ntopng/issues/4220
- https://github.com/ntop/ntopng/issues/4281

**Comment by cardigliano** [comment]
Backported

**Comment by u238** [comment]
Hi all,

it would be great to have this PR inside too:
#4082

**Comment by cardigliano** [comment]
@u238 this has been backported today
