### ISSUE TITLE
get actually traffic from ip address (json/curl)?

### ISSUE THREAD

**Issue by svenvogel** [ntop/ntopng#432]
is there a way to get the traffic from a specific ip address with json or something so that we can use it in a monitoring system? json or curl the value?

thanks

Sven

**Comment by simonemainardi** [comment]
you can curl `host_stats.lua?ifname=0&host=192.168.2.130` where ifname and host are the interface id and host ip address of interest, respectively. It replies valid json.

note that the endpoint is only used by ntopng internals and fields may change without notice in the future.

**Comment by svenvogel** [comment]
thanks for help. is it the only way or is there also a way with nprobe?

**Comment by svenvogel** [comment]
"throughput_bps":981517.875 <- is that the actually throughput?

**Comment by svenvogel** [comment]
http://192.168.77.144:3000/lua/host_stats.lua?ifname=0&host=85.X.X.X

is it possible to add username and password to bypass the http authentication login?

**Comment by simonemainardi** [comment]
- you can't query nprobe directly via http.
- throughput is in bits per second
- in order to query host_stats.lua you should first use curl to get the session cookie, save it, and then send the cookie back every time you request host_stats.lua.

Pass user and password to authorize.html to get the cookie

```
 Request URL:http://localhost:3000/authorize.html
Request Method:POST
Status Code:302 Found
Remote Address:[::1]:3000
Response Headers
view source
Location:/
Set-Cookie:session=fdad8d3973b4a69ddf44473eccb609c1; path=/; max-age=43200; HttpOnly
Set-Cookie:user=admin; path=/; max-age=43200; HttpOnly
Request Headers
view source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8,it;q=0.6
Cache-Control:max-age=0
Connection:keep-alive
Content-Length:37
Content-Type:application/x-www-form-urlencoded
Cookie:sessionid=i9t7ygvxcua9dft8yusvrble0t2pcybw; csrftoken=A1cswOoigj0iTLJSuxh7FlzDzuR13HsY; ifname=view:en0,en4; user=admin; session=
DNT:1
Host:localhost:3000
Origin:http://localhost:3000
Referer:http://localhost:3000/lua/login.lua?referer=/
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36
Form Data
view parsed
user=admin&password=admin&referer=%2F
```

**Comment by lucaderi** [comment]
See "Accessing ntopng URLs from command line tools" in https://github.com/ntop/ntopng/blob/dev/doc/README.ntopng

**Comment by pleoeter** [comment]
The link is not working @lucaderi   https://github.com/ntop/ntopng/blob/dev/doc/README.ntopng, I want to request host stats without password /username integration

**Comment by simonemainardi** [comment]
@pleoeter you can either disable the login (`--disable-login 1`) or use curl with user/password/coocke, e.g., `curl --cookie "user=admin; password=admin" "http://127.0.0.1:3000/lua/network_load.lua?ifname=en0"`
