### ISSUE TITLE
Implement notification recipients in an OO fashion

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4321]
Similar to what has been done for pools, notification recipients must be implemented as objects. So basically there will be a `base_recipient` and then the other recipients such as `email_recipient`, `webhook_recipient`, all implemented as sub-classes of `base_recipient`.

In principle, class `base_recipient` can stay under `modules/recipients/base_recipients.lua` whereas all the sub-classes can be left implemented inside plugins as the current implementation.

Class `base_recipient` with implement at least methods:

- `id = add(...)`
- `edit(id, ...)`
- `delete(id)`
- `enqueue(id, notification)`

Recipients will be keyed with integer numbers (currently they are keyed as strings). `add` will return the key, whereas `delete` and `edit` will use the key to perform the requested operation. `enqueue` will be used to deliver a notification to a particular recipient.

**Comment by lucaderi** [comment]
The key of EVERYTHING in ntopng must be agnostic to the value it handles. It can be a UUID, a number or anything as long as it's unique and immutable when the the data it refers is modified

**Comment by simonemainardi** [comment]
notification recipients are now implemented as OO under `modules/recipients` and are keyed with integers as requested.
