### ISSUE TITLE
Implement SQLite as any other notification recipient

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4325]
Currently, notification/alerts are written into SQLite regardless of any other recipient defined. It is requested to implement SQLite as any other notification recipient. This SQLite recipient will be called `ntopng builtin` and won't be deletable from the list of recipients. However, it will be possible to disable it. This is useful to alleviate pressure on highly loaded machines.

**Comment by lucaderi** [comment]
See https://github.com/ntop/ntopng/commit/aeecbcce296780ede7561b96f4e28780b0086e2e

**Comment by simonemainardi** [comment]
SQLite is now implemented as any other notification recipient. It is coded as a plugin under `scripts/plugin/sqlite_alert_endpoint`.
