### ISSUE TITLE
Two year license typo in documentation?

### ISSUE THREAD

**Issue by oskar-fagerfjall** [ntop/ntopng#4329]
In the document "What is ntopng?" under the section Licensing, one can read the following:

> Each license is perpetual (i.e. it does not expire) and it allows to install updates for one year since purchase/license issue. This means that a license generated on 1/1/2020 will be able to activate new versions of the software until **12/31/2021**.

I read this as a full two years. Should this example really be "until 12/31/2020", or is licensing more convoluted than I thought?

**Comment by simonemainardi** [comment]
thanks for pointing this out
