### ISSUE TITLE
MAC address are not sent to ElasticSearch 

### ISSUE THREAD

**Issue by C-Duv** [ntop/ntopng#433]
I have enabled dump of flow to ElasticSearch server with the following option:

```
-F "es;flows;ntopng-%Y.%m.%d;http://127.0.0.1:9200/_bulk;"
```

It is working fine except I cannot find the MAC addresses in the ES index.
It would be useful to me so that I can analyze traffic per device over long period of time.
How can I add this field?

**Comment by simonemainardi** [comment]
MAC addresses have been added to ES-exported flows. We decided to not export MAC addresses to MySQL to prevent possible space-related issues.

**Comment by C-Duv** [comment]
Thanks: it works :+1:

**Comment by tieungao88** [comment]
How to update IN_SRC_MAC and OUT_DST_MAC on current version (2.2)?

Thanks

**Comment by simonemainardi** [comment]
@tieungao88 update at least to version 2.4

**Comment by tieungao88** [comment]
Thanks :)
