### ISSUE TITLE
Resolve local hostname from MAC address

### ISSUE THREAD

**Issue by ShagoY** [ntop/ntopng#4331]
Hi,

My ISP requires me to use a dual stack IPv4+6 for some of these devices such as Android TV box.

As we know Android does not allow DHCP, and its IPv6 changes regularly for security reasons.

Ntopng already detects the different IPs according to the MAC address (hosts_stats.lua?mac=xx:xx:xx:xx:xx).
So it would be interesting if Ntopng could use the hostname it manages to resolve and use it for other IP addresses. Like the Link-local address etc...

Thanks.

**Comment by simonemainardi** [comment]
why the hostname and not the MAC address? You can also specify the MAC address as local broadcast domain so that all the timeseries and historical data are kept on a per-MAC basis. So basically if you have IP1 and then IP2 associated to the same MAC, you'll be able to see the same data regardless of the IP change

![image](https://user-images.githubusercontent.com/3397663/91190321-bf59db80-e6f3-11ea-8140-856972068077.png)

**Comment by ShagoY** [comment]
Ok, I just enabled the "Local Broadcast Domain Hosts Identifier" option and added the associated DHCP range but it didn't change anything.

For info, with my dual stack devices managed by my DHCPv4+6 server (except for the link-local address), I have the hostname followed by the [IPv6] tag.
But for Android devices, it's another story...

![Annotation 2020-08-25 174143](https://user-images.githubusercontent.com/25367500/91196635-b15b8900-e6fa-11ea-9a1b-e28761ed93db.jpg)
![Annotation 2020-08-25 173644](https://user-images.githubusercontent.com/25367500/91196645-b3bde300-e6fa-11ea-961c-e4e00a27fc17.jpg)

**Comment by simonemainardi** [comment]
You don't see changes in the frontend. Changes are in how historical data is stored.

Example:

- at time t0 you have MAC with IP1
- at time t1 you have MAC with IP2
- at time t2 you have MAC with IP3

If at time t2 you look at IP3 historical data, you will actually see MAC stats, that is, the union of IP1, then IP2, and IP3.

Does this makes sense to you?

**Comment by simonemainardi** [comment]
by the way, the only guy in your local broadcast domain (at least from what I can see in the picture) is the IPv4 Freebox Player.

**Comment by ShagoY** [comment]
Sorry, this is a screenshot of the hosts_stats.lua page "All Hosts with Mac XX:XX:XX:XX:XX", not the "All Hosts" page. so it's a screenshot displaying the different IPv4&6 of the same host :)

The thing is that I do have a hostname for my IPv6 on dual-stack hosts being managed by the dhcpv6 (But none for the link-local) but Android hosts don't manage the dhcpv6, only the SLAAC.

So I would like that when NTOPNG resolves a hostname under IPv4, that it applies it also for IPv6 associated to the MAC address.

Also english is not my native language so sorry if I misunderstand.

**Comment by ShagoY** [comment]
Basically, if the key "ntopng.dns.cache.[IPv6]" is not resolved (=IPv6), we use either :
1- "ntopng.dns.cache.[IPv4]" if it is resolved. This is the "automatic" way.
2- "ntopng.cache.host_labels.[Mac]" if it exists. But I'll need set aliases before.
3- "ntopng.dns.cache.[ipv6-link-local]" (eg. fe80::*). But I'll need to add override dns associations on my domain server before. 

Except error and because of the way ipv6 works, ipv6 is dynamic and therefore changes regularly.
This only impacts my Android devices because I can't make them static via DHCPv6.

In fact, Pihole seems to link the hostname to the MAC address. So all my IPv6 are resolved in my dashboard.
![Annotation 2020-08-26 191754](https://user-images.githubusercontent.com/25367500/91336107-b4757880-e7d1-11ea-9dbb-351a37c8d5c6.jpg)

**Comment by ShagoY** [comment]
After I set an alias directly on the mac address again, my ipv6 (unresolved) took the right hostname in the flows page.

I don't know why it didn't work before...

Sorry for wasting your time. Thanks for your time.

**Comment by ShagoY** [comment]
Edit: I just saw that the local-link IPv6 (fe80::/10) doesn't take the alias of the mac address.

As on the WAN side, ipv6 unicast (2000::/3) is not resolved by ntopng because the mac address is the one of my Pfsense firewall. Is there a way to fix this?
