### ISSUE TITLE
Locate Host via SNMP

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4333]
As of today the function 
function snmp_location.get_host_snmp_ports(mac)                                                                                                             
...
end

locates a MAC address via SNMP reporting the list access ports and trunk ports where such MAC has been observed. The problem of this code is that this MAC is not clear where it is really located. For instance it can report more than one access port and this is wrong.

This ticket requests to implement a function, that will then be used inside the GUI that
- returns 0 (not found) or 1 (when found) port where a given MAC address is located. The function must discard eventually learned MAC address and report only those MACs that have been observed on a port
- update the current code to use that function when necessary such as in the SNMP plugin

**Comment by simonemainardi** [comment]
implemented function `get_host_access_port` as requested. Implementation available in pro commit 7b3d61d59bb72e6e932cd9a06f27a2cfb4f29aa0.
