### ISSUE TITLE
#3144 has resurfaced

### ISSUE THREAD

**Issue by fsamareanu** [ntop/ntopng#4335]
Hello,

#3144 has again resurfaced. This generates an e-mail every time it's ran by cron.

```
root@gemma:/var/log# /usr/bin/ntopng-utils-manage-updates -a check-updates-on-demand
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
root@gemma:/var/log# dpkg -l ntopng
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version          Architecture Description
+++-==============-================-============-=================================
ii  ntopng         4.1.200826-11264 amd64        Web-based traffic monitoring.
```

**Comment by cardigliano** [comment]
@fsamareanu since I am not able to reproduce the same, could you run the script with "bash -x /usr/bin/ntopng-utils-manage-updates -a check-updates-on-demand" and provide the output? Thank you.

**Comment by fsamareanu** [comment]
[bash_out.txt](https://github.com/ntop/ntopng/files/5154679/bash_out.txt)
Attached

**Comment by cardigliano** [comment]
@fsamareanu just to make sure, could you provide your /usr/bin/ntopng-utils-manage-updates ? Thank you

**Comment by fsamareanu** [comment]
[ntopng-utils-manage-updates.txt](https://github.com/ntop/ntopng/files/5217250/ntopng-utils-manage-updates.txt)

**Comment by cardigliano** [comment]
The issue you are experiencing is a bit weird. Sorry for bothering you, I pushed some change, new nightly builds will be available later today, please test it and let me know. Thank you.

**Comment by fsamareanu** [comment]
yeah it's silent now :)

root@gemma:~#  /usr/bin/ntopng-utils-manage-updates -a check-updates-on-demand
root@gemma:~#

**Comment by cardigliano** [comment]
Great
