### ISSUE TITLE
The [IPv6] suffix is not displayed.

### ISSUE THREAD

**Issue by ShagoY** [ntop/ntopng#4336]
If I add an alias to an IPv6 host, the suffix "[IPv6]" is no longer displayed in the dashboard.

It's not much but it would make the dashboard sexier! :-D

Thanks.

ntopng v.4.1.200826

**Comment by simonemainardi** [comment]
can you provide a patch for this?

**Comment by ShagoY** [comment]
Sincerely I would have liked to help you and when I tried, I had 141 results in the code... Because the search under github could not find [IPv6] because it is not "case sensitive" and ignores [] symbols.
I didn't know where to start :-/

Not to mention that I'm not a developer ^^

**Comment by ShagoY** [comment]
Some additional information that I hope will help...
It seems that the [IPv6] suffix only appears when the host is resolved automatically.
And in my case I just added a custom alias directly on the mac address. Not directly on the host.
So by logic, I guess that as soon as a key of the type "ntopng.cache.host_labels.\*" exists, we lose the suffix.
And the opposite if ntopng only finds an associated "ntopng.dns.cache.\*" key, it displays the suffix.

I guess...
