### ISSUE TITLE
Issue ntopng causing interfaces to stop breifly on linux iptables firewall router

### ISSUE THREAD

**Issue by njcwotx** [ntop/ntopng#4337]
I run ntopng in tandem with an iptables firewall router for many years now.  I have upgraded to buster about a year ago, and recently performed a full update cycle, including ntopng.

After this update, I started having packet loss on all devices behind the firewall on 2 separate ports for about a week now.  I have tracked it to ntopng.   If I stop ntopng services, the issue no longer occurs.   If I start it back up, the issue returns and I have found the following error message in my logs occurring whenever the ports drop traffic.  The drop is typically very brief, only a few seconds, but its enough to cause issues.  The ports are not bouncing themselves it seems and there seems to be no registered errors or dropson the interface.

The packet loss is several times an hour.  This message always accompanies a packet loss event, but sometimes I get the message and no loss occurrs, but it generally does.

[LuaEngineNtop.cpp.inc:37] ERROR: ntop_snmpv3_batch_get : expected string[@pos 4], got nil

I am not needing snmpv3 polling at all, I have checked the preferences and I do have debugging turned off, but no way to stop snmp polling.

Heres the specs from help about......
Version	4.1.200817 (11182) - Professional Edition
Built on	Debian GNU/Linux 10 (buster)
Platform	Debian 10.4 [x86_64][Debian GNU/Linux 10 (buster)] - 64 bit
Startup Line	ntopng --user "ntopng" --interface "eth0" --interface "eth1" --interface "eth2" --http-port "3000" --local-networks "192.168.98.0/24,192.168.97.09/24,192.168.96.0/24" --dns-mode "1" --sticky-hosts "local" --data-dir "/ntopng"
nDPI	3.3.0-2678-ebf89f46
cURL	7.64.0
 Twitter Bootstrap	4.4.0
 Font Awesome	5.11.2
RRDtool	1.7.1
nIndex	1.3
Redis Server	5.0.3
Mongoose web server	3.7
LuaJIT	Lua 5.3.5
ØMQ	4.3.1
GeoLite	1.3.2
Includes support for MaxMind  and DB-IP  Geolocation databases.
Data-Driven Documents (d3js)	2.9.1 / 3.0

**Comment by simonemainardi** [comment]
So basically ntopng is running on the router? That is, "eth0", "eth1", "eth2"  are router interfaces and devices connected to those interfaces experience drops?

Make sure to update ntopng to the latest dev version. Then:
- Make sure there's no SNMP device configured under system->SNMP (`ERROR: ntop_snmpv3_batch_get : expected string[@pos 4], got nil` seems to be related to SNMP).
- Check the system load under system (both live and historical). Are there any spikes during drops?

**Comment by simonemainardi** [comment]
No feedback received. Closing. Feel free to reopen with the requested information if necessary.
