### ISSUE TITLE
ntopng[7393]: [Trace.cpp:118] ERROR: Unable to create log /var/log/ntopng/ntopng.log

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#4341]
./ntopng status
ntopng[7393]: [Trace.cpp:118] ERROR: Unable to create log /var/log/ntopng/ntopng.log

**Comment by cardigliano** [comment]
As in #4340, please use "systemctl status ntopng"

**Comment by MaoPann** [comment]
systemctl status ntopng
 [Trace.cpp:118] ERROR: Unable to create log /var/log/ntopng/ntopng.log
