### ISSUE TITLE
systemctl status ntopng

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#4342]
systemctl status ntopng
[Trace.cpp:118] ERROR: Unable to create log /var/log/ntopng/ntopng.log

**Comment by simonemainardi** [comment]
Did you enable the creation of the log file from the preferences? In that case you need to run ntopng with `--dont-change-user`. However, you should just let systemd handle the logs for you.

**Comment by MaoPann** [comment]
I don't quite understand what you mean

**Comment by simonemainardi** [comment]
turn this off:

![image](https://user-images.githubusercontent.com/3397663/91694651-39171c80-eb6d-11ea-9d71-708044c2dfe3.png)

then restart and use `journalctl -u ntopng` to browse ntopng logs.

**Comment by MaoPann** [comment]
thanks!!!
