### ISSUE TITLE
Influxdb time-series driver automatic pre-configuration

### ISSUE THREAD

**Issue by santuari** [ntop/ntopng#4343]
I need to provision ntopng with [influxdb database for storing time-series historical data](https://www.ntop.org/guides/ntopng/basic_concepts/timeseries.html) enabled and configured by default. In particular, I would like to be able to set [the configurations](https://user-images.githubusercontent.com/6616963/91716925-d33c8c00-eb90-11ea-97b1-cc16e78ff142.png).

Can I use a config file or a rest API to configure and enable by default the influxdb to store timeseries data?

Thanks.
Michele Santuari

**Comment by simonemainardi** [comment]
Currently, influxdb configuration via API is not supported. However, you can clone file '<datadir>/ntopng/runtimeprefs.json' as the configuration is written there.

**Comment by santuari** [comment]
thanks @simonemainardi 
How can I use that file to be able to automatically enable and configure the influxdb to store history data?
Thanks!

**Comment by simonemainardi** [comment]
- do the configuration from the UI
- stop ntopng both on the source and on the destination machine
- copy file `runtimeprefs.json` from the source to the destination machine
- restart both ntopng instances

**Comment by simonemainardi** [comment]
Does this helps? Did you manage to use the file?

**Comment by santuari** [comment]
We need to also update our current installations, so in this way, we might override the existing settings.
Moreover, the settings are "hashed" so it is difficult to know if we have applied the change or not in an automatic procedure.
Does [this approch](https://github.com/ntop/ntopng/issues/4295#issuecomment-674811514) make sense also for this use case? What do you think?

**Comment by simonemainardi** [comment]
I think a more structured solution need to be designed for your use case.

**Comment by santuari** [comment]
Do you think that can be somehow implemented?

**Comment by djstarfox** [comment]
Makes more sense to have the InfluxDB configuration be part of the ntopng.conf file (i.e., command line parameters) and not part of the GUI config. Currently, you can specify Redis-Server config with "--redis", so why not InfluxDB too? 

Of course, that would be an enhancement to ntop... not currently available.

**Comment by simonemainardi** [comment]
After internal review, we have decided not to add extra command line arguments to ntopng. We are in the process of reducing the use of configuration files and CLI options, and only allow changes via REST. Eventually, we will have all the configuration pulled from a cloud or on-prem distributor, without the need to change /etc.
