### ISSUE TITLE
Home setting question

### ISSUE THREAD

**Issue by thalthoff** [ntop/ntopng#4344]
Hi all!

I'd like to know what license(s) I'd need to do the following:

Setting: Home network, some 30-50 network devices, An internet-access-router that supports IPFIX and a bored Pi3 with an external 3TB HDD.

What I want to do: I'd like to collect the IPFIX data that the main router produces with nProbe on the Pi and write all data in a mySQL/MariaDB on that same Pi. If the Pi is "strong enough" for the given setting to also analyze the data in the mySQL/MariaDB with ntopng, I'd like to run ntopng on the Pi too, otherwise I'd let an unused older Mac mini do this task.

My questions are:
1. Is this setting ok, i.e. would it work? Or is it complete nonsense? 
2. What license(s) are necessary/recommended to have a retrospective view too, i.e. "what happened yesterday/two days ago"? Standard/Pro/Embedded/...?

Thanks for all your help in advance!

-Thomas

**Comment by simonemainardi** [comment]
required setup is

- nProbe (standard Version suffices for IPFIX collection)
- ntopng Community or above

However, using MySQL/MariaDB is not really recommended in real scenarios. They will choke quickly and become too slow to be usable. So basically slow queries and slow insertions. This, mixed with a low-end PI, won't bring you far.

My recommendation is to use ntopng Pro or above with our special-purpose nIndex database, which we've designed to store flows to disk. ntopng integrates with it, so you'll be able to query and export flows, and also to correlated them with historical charts. Note that nIndex in only available on x86_64 (so no ARM).

**Comment by thalthoff** [comment]
Thank you very much for your quick answer!

So how do I have to go on? nProbe, standard edition on the Pi and ntopng pro edition or above on my Mac mini? Or would it be easier (make more sense) to implement nProbe standard and ntopng pro together on that Mac mini and let the Pi to continue to be bored? 

Edit: The Mac mini is a Mac mini Server (Late 2011) with a 2GHz Intel Core i7 and 16GB RAM plus the mentioned additional 3TB HDD.

**Comment by simonemainardi** [comment]
you can leave nProbe on the PI - and so save some $$$ as the ARM license is cheaper - and then run ntopng on the Mac. Note that with ntopng Pro there's a maximum of three days retention for flows, whereas unlimited retention comes with Enterprise version.

**Comment by thalthoff** [comment]
Ok, got that! Thank you! If I keep saving $$$ apart, which scenario would be the most recommended, most manageable, easiest to maintain? Which one would YOU implement in your home with the given ressources, if $$$ for licenses has a "lower" priority?

**Comment by simonemainardi** [comment]
I would keep everything on x86_64.

**Comment by thalthoff** [comment]
Perfect! Thank you very much for your help!

-Thomas

**Comment by simonemainardi** [comment]
Thank you!
