### ISSUE TITLE
Can ntopng be used with third-party network probes.

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#4347]
I want to install ntop in the virtual machine and use it to monitor the data of A third-party network probe. Can it be realized? If it can be implemented, do we need any special configuration?

**Comment by simonemainardi** [comment]
please give details of the third-party network probe.

**Comment by MaoPann** [comment]
Details of the third party network probe are given later.Then,I have installed ntopng monitoring on the virtual machine. Is there any problem with this? And I have multiple virtual machines installed on my server.

**Comment by simonemainardi** [comment]
ntopng can be installed on a VM without problems. Waiting for probe details.

**Comment by MaoPann** [comment]
Details of the third party network probe are given later.Then,How to import network probe data into a specific virtual machine, because we have multiple virtual machines.

**Comment by lucaderi** [comment]
This is a discussion for discord and not for github Please move to it https://www.ntop.org/community/
