### ISSUE TITLE
monitor Netflow/Sflow data that could reach up to 100 Gbps bandwith

### ISSUE THREAD

**Issue by jednoprsak** [ntop/ntopng#4348]
I was thinking about using some combination of ntopng, nprobe and cento, but I would like to know, what would you recommend for solving our problem. We want to monitor Netflow/Sflow data that could reach up to 100 Gbps bandwith. We will export these data from our Cisco switch interface. Please could you suggest some solution for our issue?

**Comment by simonemainardi** [comment]
Challenge here is not  bandwidth per-se but  the number of Netflow flows / sFlow samples generated per second.

The combination of software to be used is nProbe (for the collection) + ntopng (for the visualization and analysis).

As a ballpark, consider that nProbe+ntopng can handle approx. 100k flows per second when nProbe is used in `--collector-passthrough`.

So the first thing to do here is to try and do an estimate of how many flows per second your 100Gbps is going to generate. Then, with this data, we can start moving forward. There are several strategies to reduce the cardinality of the problem, if necessary. For example, we can discard probing flows, or flows smaller than a given size.

To do the estimation, you can run nProbe with option `-b=1` and look at the numbers reported periodically to standard out. They will tell you the number of flows per second collected. I think we can start from there.

**Comment by jednoprsak** [comment]
Thank you for your response. I will deploy it inside our environment and let you know about the results.

**Comment by simonemainardi** [comment]
Thanks. I'm closing this as it's been inactive for 4 months. Please, if you have feedback, feel free to comment or reopen.
