### ISSUE TITLE
Historical Flows API: get all records

### ISSUE THREAD

**Issue by junaid-soomro-ivolve** [ntop/ntopng#4349]
What i am confused with is i am using API to check for historical flows now by default flow limit is 10 per request and if i provide the limit parameter in the API then i can get more flows. i am asking is there a way to pull all flows in one request via API call? or any work around for this task would be deemed useful thank you.

i have seen this parameter called max_hits=10 which only gets 10 records of flows.Is there a way to get all records
something like max_hits=infinite or all

**Comment by simonemainardi** [comment]
Currently, this is not supported with REST API. The maximum number of flows exported in one single request is 10k. 

I think we would have to implement a 'cursor'/'pagination' mechanism to allow all flows to be retrieved. It's not practical to send all of them in a single response as this can become HUGE.

**Comment by junaid-soomro-ivolve** [comment]
Thanks Mr. Simone. Good to know.

**Comment by simonemainardi** [comment]
Implemented in the latest dev and soon available in version 5.0
