### ISSUE TITLE
Can ntopng directly monitor data from SPAN or TAP？

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#4350]
Can ntopng directly monitor data from SPAN or TAB？

**Comment by MaoPann** [comment]
Or use nprobe and ntopng to monitor?

**Comment by simonemainardi** [comment]
See https://www.ntop.org/guides/ntopng/use_cases/mirror_tap_monitoring.html

Before flooding GitHub with questions, make sure you've gone through all the available documentation https://www.ntop.org/guides/ntopng/ and blog https://www.ntop.org/blog/
