### ISSUE TITLE
After Enabling Flow Dump,Where is the stream data stored?

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#4351]

**Comment by simonemainardi** [comment]
Which option did you use to enable flows dump?

**Comment by MaoPann** [comment]
I want to enable Flow Dump with -F nindex or  Data Retention,But I don't know the difference between the two methods. Where do the two methods save flows.

**Comment by lucaderi** [comment]
please ask these questions on discord leaving github for tickets
