### ISSUE TITLE
Email test button logs on console with no visual feedback

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4355]
![Screen Shot 2020-09-02 at 12 47 43](https://user-images.githubusercontent.com/4493366/91972187-97cdc900-ed1a-11ea-8cd2-434aaeb579dd.png)

02/Sep/2020 12:47:35 [Utils.cpp:1703] WARNING: Unable to send email to (smtp://mail.ntop.org/ntop.org): Login denied. Run ntopng with -v6 for more details.
02/Sep/2020 12:47:38 [Utils.cpp:1703] WARNING: Unable to send email to (smtp://mail.ntop.org/ntop.org): Login denied. Run ntopng with -v6 for more details.
02/Sep/2020 12:47:39 [Utils.cpp:1703] WARNING: Unable to send email to (smtp://mail.ntop.org/ntop.org): Login denied. Run ntopng with -v6 for more details.
02/Sep/2020 12:47:39 [Utils.cpp:1703] WARNING: Unable to send email to (smtp://mail.ntop.org/ntop.org): Login denied. Run ntopng with -v6 for more details.
02/Sep/2020 12:47:39 [Utils.cpp:1703] WARNING: Unable to send email to (smtp://mail.ntop.org/ntop.org): Login denied. Run ntopng with -v6 for more details.
02/Sep/2020 12:47:40 [Utils.cpp:1703] WARNING: Unable to send email to (smtp://mail.ntop.org/ntop.org): Login denied. Run ntopng with -v6 for more details.
02/Sep/2020 12:47:40 [Utils.cpp:1703] WARNING: Unable to send email to (smtp://mail.ntop.org/ntop.org): Login denied. Run ntopng with -v6 for more details.
02/Sep/2020 12:47:42 [Utils.cpp:1703] WARNING: Unable to send email to (smtp://mail.ntop.org/ntop.org): Login denied. Run ntopng with -v6 for more details.
02/Sep/2020 12:47:43 [Utils.cpp:1703] WARNING: Unable to send email to (smtp://mail.ntop.org/ntop.org): Couldn't connect to server. Run ntopng with -v6 for more details.
02/Sep/2020 12:47:46 [Utils.cpp:1703] WARNING: Unable to send email to (smtp://mail.ntop.org/ntop.org): Couldn't connect to server. Run ntopng with -v6 for more details.
02/Sep/2020 12:47:49 [Utils.cpp:1703] WARNING: Unable to send email to (smtp://mail.ntop.org/ntop.org): Couldn't connect to server. Run ntopng with -v6 for more details.
02/Sep/2020 12:47:50 [Utils.cpp:1703] WARNING: Unable to send email to (smtp://mail.ntop.org/ntop.org): Couldn't connect to server. Run ntopng with -v6 for more details.
02/Sep/2020 12:47:50 [Utils.cpp:1703] WARNING: Unable to send email to (smtp://mail.ntop.org/ntop.org): Couldn't connect to server. Run ntopng with -v6 for more details.

Note that adding (as suggested) -v6 is helpless as it prints a lot of data confusing the reader

02/Sep/2020 12:52:22 [LuaEngineNtop.cpp.inc:3863] ntop_get_redis() called
02/Sep/2020 12:52:22 [LuaEngineInterface.cpp.inc:158] ntop_get_interface_id() called
02/Sep/2020 12:52:22 [LuaEngineInterface.cpp.inc:44] getCurrentInterface() called
02/Sep/2020 12:52:22 [LuaEngineInterface.cpp.inc:90] ntop_get_interface_names() called
02/Sep/2020 12:52:22 [LuaEngineInterface.cpp.inc:105] Returning name [0][en3]
02/Sep/2020 12:52:22 [LuaEngineInterface.cpp.inc:137] ntop_select_interface() called
02/Sep/2020 12:52:22 [LuaEngineInterface.cpp.inc:44] getCurrentInterface() called
02/Sep/2020 12:52:22 [LuaEngineInterface.cpp.inc:137] ntop_select_interface() called
02/Sep/2020 12:52:22 [Ntop.cpp:1169] No allowed interface found for en3
02/Sep/2020 12:52:22 [LuaEngineInterface.cpp.inc:44] getCurrentInterface() called
02/Sep/2020 12:52:22 [LuaEngineInterface.cpp.inc:137] ntop_select_interface() called
02/Sep/2020 12:52:22 [LuaEngineNtop.cpp.inc:3863] ntop_get_redis() called
02/Sep/2020 12:52:22 [LuaEngineNtop.cpp.inc:2207] ntop_is_pro() called
02/Sep/2020 12:52:22 [LuaEngineNtop.cpp.inc:2597] ntop_get_info() called
02/Sep/2020 12:52:22 [LuaEngineNtop.cpp.inc:2527] ntop_system_host_stat() called
02/Sep/2020 12:52:22 [LuaEngineNtop.cpp.inc:3863] ntop_get_redis() called
02/Sep/2020 12:52:22 [LuaEngineNtop.cpp.inc:1612] ntop_is_administrator() called
02/Sep/2020 12:52:22 [LuaEngineNtop.cpp.inc:2231] ntop_is_nedge() called
02/Sep/2020 12:52:22 [LuaEngineNtop.cpp.inc:1612] ntop_is_administrator() called
02/Sep/2020 12:52:22 [LuaEngineNtop.cpp.inc:3863] ntop_get_redis() called

**Comment by simonemainardi** [comment]
Status is now propagated to the end user in the UI:

![image](https://user-images.githubusercontent.com/3397663/92126397-6a5b4b00-ee00-11ea-9527-333b09f5e91c.png)

![image](https://user-images.githubusercontent.com/3397663/92126426-7515e000-ee00-11ea-9115-88d0feb7b13a.png)
