### ISSUE TITLE
Import/Export configuration in Active Monitoring not working

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4356]
Button has a strange look and opens a non-existing page

<img width="527" alt="image" src="https://user-images.githubusercontent.com/3397663/91990151-ad022200-ed31-11ea-861f-573a82772e68.png">

**Comment by gabryon99** [comment]
There was a problem inside the href attribute. See the commit: https://github.com/ntop/ntopng/commit/9e508a73820733832aaa5079d1052ae665ba2665

**Comment by simonemainardi** [comment]
This now points to a WIP page and eventually ends up in a not found error:

![image](https://user-images.githubusercontent.com/3397663/92391526-24162c80-f11d-11ea-865a-e99cd3a9763a.png)


Can you just leave the old import/export behavior for now?

**Comment by gabryon99** [comment]
Depends on: https://github.com/ntop/ntopng/issues/4128
