### ISSUE TITLE
Stateful alerts are not persistent 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4357]
Suppose I actively monitor host X and alert is triggered as X is down. If I restart ntopng another alert for X is sent even though the previous alert was already delivered to the expected recipient. This needs to be fixed by introducing some for of (redis?) persistency to avoid alarm storms to be generated whenever ntopng is restarted

**Comment by simonemainardi** [comment]
Proposed solution is:

- set the a `ntopng.cache.<fields_that_create_an_alert_key>` during `alerts_api.trigger()`
- delete the key during `alerts_api.release()`

At this point, a new notification is only dispatched during `alerts_api.trigger()` if the key doesn't exists.

**Comment by lucaderi** [comment]
Ok but
- the key must be short in length (MD5 could help instead of using fields)
- remember to cleanup redis when alerts are delivered etc
