### ISSUE TITLE
Split plugins apart

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4358]
The plugins folder contains heterogeneous components such as alerts, syslog extensions ....

it doesn't make any sense to mix them up but they must be stored in different folders, one per type and not all in the same place

**Comment by simonemainardi** [comment]
A plugin can actually perform heterogeneous things, so choice was to add action-dependent plugin subfolders: see https://www.ntop.org/guides/ntopng/plugins/structure.html#plugin-structure

For example, the active monitoring plugin:
- Periodically executes monitoring probes
- Adds UI pages for configuration
- Generate alerts
