### ISSUE TITLE
Plugins are not self-contained

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4359]
Plugins must be self-contained meaning that when a new plugin folder is added, no other folder, file etc of ntopng has to be modified. As of today at least localisation breaks this principle that instead it must be honoured

For instace a new plugin must be listed in en.lua on

  ["types"] = {
      ["email"] = "Email",
      ["slack"] = "Slack",
      ["syslog"] = "Syslog",
      ["webhook"] = "Webhook",
    },

that is not a good practice

**Comment by simonemainardi** [comment]
Distributing localization files in individual, plugin-specific files, is absolutely good from the point of view of the design as you've said. However, this will also be painful for the translations. Currently, translators are only given the single "locales/en.lua" file to translate. If we split the locales into multiple files, then we would also have to give translators multiple files or create an automated tool to join/split them. Given this evidence, please give directions.

**Comment by lucaderi** [comment]
You need to glue locales during plugin load

**Comment by simonemainardi** [comment]
Per-plugin locales are already supported and glued during load: https://www.ntop.org/guides/ntopng/plugins/localization.html

My comment only involves the act of doing the translation.

**Comment by lucaderi** [comment]
The "types" key need to be edited. Please remove cross dependencies
