### ISSUE TITLE
ntopng not showing historical data

### ISSUE THREAD

**Issue by fi-ro** [ntop/ntopng#436]
Hi,
I've talked to Simone on the mailing list and was asked to open an issue here.

The problem is that don't see historical data in the ntop frontend.

In the ntopng.log it says it successfully connected to the DB:

```
[MySQLDB.cpp:273] Succesfully connected to MySQL [ip-mysql-server:root]
for interface tcp://127.0.0.1:5556
```

In the DB itself I can see entries coming in.

However in the interface historical page on the bottom I see a red bar
with

> No Results Found

Same applies if I check a host's historical page.

I've started ntop with the following arguments:
`ntopng -i tcp://127.0.0.1:5556 -q -F "mysql;ip-sql-cluster;flowdb;ntopdb;dbuser;dbuserpw"`

Nprobe on the same host is started with:
`nprobe --zmq tcp://*:5556 -V 9 -i none --collector-port 2055 -n none -G`

For completeness here my system specs (collector):

```
Ubuntu 14.04.3 LTS
nProbe Pro v.7.2.160308 (r4471) for x86_64-unknown-linux-gnu

ntopng --version
v.2.2.160308 [Professional Edition]
GIT rev:   2.2-stable:06306079a9f31f95143756e855b99ac968415763:20160308
Pro rev:   r524
```

ntopng and nprobe installed via apt-get.

If more informations are needed I'm happy to provide them.

Cheers
Robert
![no_results](https://cloud.githubusercontent.com/assets/17490762/13609117/ee5afb1e-e557-11e5-945d-163bbf4e4aaa.png)

**Comment by simonemainardi** [comment]
I've noticed that you are using version 2.2 stable .Could you please update and use the latest dev version? We've done a lot of improvements there.

**Comment by fi-ro** [comment]
I was using the stable build because this is a test setup for later production use and would like to continue on stable when in production.

I've updated now to these version:

```
nProbe v.7.3.160309 (r4930)
nTop v.2.3.160309 [Professional Edition] (r589)
```

Changes I've noticed:
- table names changed from `ntopngv4_2` to `ntopngv4`
- entries in the tables are increasing (with current timestamp)
- syslog entry:
  `[MySQLDB.cpp:477] ERROR: MySQL error: [Table 'flowdb.flowsv4' doesn't exist][1146]`

My guess is that it want's to read from a different table than it's writing to.

**Comment by simonemainardi** [comment]
changes are expected. mysql table names and columns were slightly changed. ntopng migrates tables to the new format automatically.

if you still can't see flows, try to rename the interface and use a string without slashes or wait until tomorrow and update the packages. We have introduced some minor fixes to deal with names with slashes.

**Comment by fi-ro** [comment]
I just did a update to this version:

```
# ntopng --version
v.2.3.160311 [Professional Edition]
GIT rev:   dev:5450ae7f98b9234245153ba5ffa9b2e802752da2:20160311
Pro rev:   r592
Built on:  Ubuntu 14.04.3 LTS
```

As you said, the schema was updated to:

```
[flowdb]> show tables;
+------------------+
| Tables_in_flowdb |
+------------------+
| ntopngv4         |
| ntopngv6         |
+------------------+
2 rows in set (0.00 sec)


[flowdb]> show columns from ntopngv4;
+----------------------+----------------------+------+-----+---------+----------------+
| Field                | Type                 | Null | Key | Default | Extra          |
+----------------------+----------------------+------+-----+---------+----------------+
| idx                  | int(11)              | NO   | MUL | NULL    | auto_increment |
| VLAN_ID              | smallint(5) unsigned | YES  |     | NULL    |                |
| L7_PROTO             | smallint(5) unsigned | YES  |     | NULL    |                |
| IP_SRC_ADDR          | int(10) unsigned     | YES  |     | NULL    |                |
| L4_SRC_PORT          | smallint(5) unsigned | YES  |     | NULL    |                |
| IP_DST_ADDR          | int(10) unsigned     | YES  |     | NULL    |                |
| L4_DST_PORT          | smallint(5) unsigned | YES  |     | NULL    |                |
| PROTOCOL             | tinyint(3) unsigned  | YES  |     | NULL    |                |
| BYTES                | int(10) unsigned     | YES  |     | NULL    |                |
| PACKETS              | int(10) unsigned     | YES  |     | NULL    |                |
| FIRST_SWITCHED       | int(10) unsigned     | YES  | MUL | NULL    |                |
| LAST_SWITCHED        | int(10) unsigned     | YES  |     | NULL    |                |
| INFO                 | varchar(255)         | YES  |     | NULL    |                |
| JSON                 | blob                 | YES  |     | NULL    |                |
| PROFILE              | varchar(255)         | YES  | MUL | NULL    |                |
| NTOPNG_INSTANCE_NAME | varchar(256)         | YES  | MUL | NULL    |                |
| INTERFACE            | varchar(64)          | YES  | MUL | NULL    |                |
+----------------------+----------------------+------+-----+---------+----------------+
17 rows in set (0.00 sec)
```

However, ntopng.log still show's the table not found error:

```
11/Mar/2016 08:32:44 [MySQLDB.cpp:477] ERROR: MySQL error: [Table 'flowdb.flowsv4' doesn't exist][1146]
11/Mar/2016 08:32:44 [MySQLDB.cpp:362] Attempting to connect to MySQL for interface tcp://127.0.0.1:5556...
11/Mar/2016 08:32:44 [MySQLDB.cpp:402] Succesfully connected to MySQL [10.10.10.10:root] for interface tcp://127.0.0.1:5556
```

I've found a workaround:
Previously I ran ntopng with
`ntopng -i tcp://127.0.0.1:5556 -q -F "mysql;ip-sql-cluster;flowdb;ntopdb;dbuser;dbuserpw"`
When I start it insead with:
`ntopng -i tcp://127.0.0.1:5556 -q -F "mysql;ip-sql-cluster;flowdb;flows;dbuser;dbuserpw"`
it works.
Seems to be that the table _flows_ is hard encoded.

Grep-ing through the source folder it shows that these file contain the string "flows":

```
# grep -nrw ntopng/ -e "flowsv4"
ntopng/scripts/lua/db_query.lua:22:   sql = "select * from flowsv4 order by LAST_SWITCHED desc limit 10"
ntopng/scripts/lua/modules/db_utils.lua:288:      sql = sql.."FROM flowsv4 "
ntopng/scripts/lua/modules/db_utils.lua:436:      sql = sql.."FROM flowsv4 "
ntopng/scripts/callbacks/daily.lua:29:   sql = "DELETE FROM flowsv4 where FIRST_SWITCHED < "..mysql_retention

# grep -nrw ntopng/ -e "flowsv6"
ntopng/scripts/lua/modules/db_utils.lua:284:      sql = sql.."FROM flowsv6 "
ntopng/scripts/lua/modules/db_utils.lua:432:      sql = sql.."FROM flowsv6 "
ntopng/scripts/callbacks/daily.lua:35:   sql = "DELETE FROM flowsv6 where FIRST_SWITCHED < "..mysql_retention
```

**Comment by fi-ro** [comment]
Some addition:
With the above workaround all data is there and is displayed correctly in the web ui.
But in the database everything seems to be stored in **one** entry:

```
[flowdb]> select count(*) flowsv4;
+---------+
| flowsv4 |
+---------+
|       1 |
+---------+
1 row in set (0.00 sec)

```

Displaying this entry I see lot's of binary data. So I'm guessing that all data is stored in this single entry.
Is this assumption correct?

**Comment by simonemainardi** [comment]
FROM clause is missing in your query:

```
mysql> select count(*) from flowsv4;
```
