### ISSUE TITLE
User interface is not stateless

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4361]
![Screen Shot 2020-09-02 at 21 45 04](https://user-images.githubusercontent.com/4493366/92030191-fb7de380-ed66-11ea-9c94-6c55c709e18c.png)

Suppose you do in a sequence
- on + and the endpoint name is empty
- click on edit on endpoint s, then click on +, in the endpoint name (of the newly open dialog)you will see s
- click on edit on endpoint web, then click on +, in the endpoint name (of the newly open dialog)you will see web

This is not a consistent behaviour as the endpoint name must be empty all times.

Please fix this bug and make sure all other forms similar to this are also fixed

**Comment by gabryon99** [comment]
There was a bug during the modal closing filling the inputs in the wrong way due to selectors. See the commit: https://github.com/ntop/ntopng/commit/c59133ef72f88da97220b8580a07b9ea262e900c
