### ISSUE TITLE
Table layout is not responsive

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4362]
![Screen Shot 2020-09-02 at 21 59 36](https://user-images.githubusercontent.com/4493366/92030664-ab535100-ed67-11ea-9e43-72f43dffaed9.png)
![Screen Shot 2020-09-02 at 21 59 21](https://user-images.githubusercontent.com/4493366/92030670-ac847e00-ed67-11ea-8e2c-d42ed75bc93f.png)
![Screen Shot 2020-09-02 at 21 59 06](https://user-images.githubusercontent.com/4493366/92030673-ad1d1480-ed67-11ea-9910-8574106e9658.png)

**Comment by simonemainardi** [comment]
same for the SNMP page

**Comment by gabryon99** [comment]
Added a responsive table wrapper for each table. See the commit: https://github.com/ntop/ntopng/commit/ccaf1f7b285884e0d8446f4cb2b7cc2049d98f2a

**Comment by simonemainardi** [comment]
SNMP table still bugged.

**Comment by simonemainardi** [comment]
Fixed in the latest build.
