### ISSUE TITLE
Ignore vlans does not work with RSS

### ISSUE THREAD

**Issue by hoangtnk** [ntop/ntopng#4367]
Due to limitation of our device's mirroring capability, we need to enable `--ignore-vlans` (#1870) for ntop to categorize flows correctly. Our network has roughly 2 - 3 Gbps traffic on average, thus we also use RSS to reduce packet drops. Unfortunately, these two features cannot work together. Anytime we use RSS, `--ignore-vlans` simply does not have any effect. As soon as I disable RSS, `--ignore-vlans` starts to work again.

Is there any workaround for this? Thank you very much for your help.

**Comment by hoangtnk** [comment]
We've just migrated ntop to run on a much more powerful server, and observe no packet drops without using RSS (`--ignore-vlans` still enabled for the reason mentioned). My question is, what is the maximum traffic that ntop can handle without RSS? Can it reach up to 10 Gbps? If so, I think that's good enough for our environment and we don't need to tweak anything.

**Comment by cardigliano** [comment]
@hoangtnk I assume that your problem here is that you have the same flow which is going to different RSS queues as there is a different VLAN per direction, could you confirm? I need to check whether VLAN can be excluded by the adapter in the hash computation, what is your adapter model?
As of the performance, it depends on a few factors including CPU and avg packet size (i.e. pps), you should be able to handle a few Gbps without RSS.

**Comment by hoangtnk** [comment]
@cardigliano Yes. I have different VLAN per direction. You can see in the packet capture that we have a weird vlan 4095 in one direction and no vlan in the other.

[youtube_captured_on_ntop.pcap.gz](https://github.com/ntop/ntopng/files/5181770/youtube_captured_on_ntop.pcap.gz)

This is the limitation of our device's mirroring feature, as described [here](https://www.juniper.net/documentation/en_US/junos/topics/task/configuration/port-mirroring-limitations-qfx-series.html):

_True egress mirroring is defined as mirroring the exact number of copies and the exact packet modifications that went out the egress switched port. Because the processor on QFX5xxx (including QFX5100, QFX5110, QFX5120, QFX5200, and QFX5210) and EX4600 (including EX4600 and EX4650) switches implements egress mirroring in the ingress pipeline, those switches do not provide accurate egress packet modifications, so egress mirrored traffic can carry incorrect VLAN tags that differ from the tags in the original traffic._

My adapter model is `i40e: Intel(R) 40-10 Gigabit Ethernet Connection Network Driver - version 2.4.6`

**Comment by lucaderi** [comment]
@hoangtnk Your attached pcap can't be downloaded. Please try again

**Comment by lucaderi** [comment]
I don't think this issue is related to ntopng. With RSS if you have one direction with VLAN and now without, packets are sent to different RSS queues and thus your ntopng instance sees only one direction, in particular with XL710 where RSS is asymmetric.

**Comment by hoangtnk** [comment]
@lucaderi Yes, I'm now aware that `--ignore-vlans` does not work with RSS because traffic goes to different RSS queues. But @cardigliano mentioned that there's still a possibility (depends on adapter model) to exclude vlan in hash computation. Or do we have other solutions (besides RSS) that can work with `--ignore-vlans`?

P/S: Please reopen this thread for further discussion, or pointing me to the correct place to open it. Thank you.
