### ISSUE TITLE
Policy implementation

### ISSUE THREAD

**Issue by razor3g** [ntop/ntopng#437]
Hello,

My colleague misrepresented the case of policy issues we were having with ntopng.
There is no section on the page to apply policies.
Please assist

**Comment by razor3g** [comment]
Hello

**Comment by simonemainardi** [comment]
how did you configure ntopng? please post startup string

**Comment by razor3g** [comment]
Hello,

I followed instructions in the link below
http://packages.ntop.org/centos/

**Comment by razor3g** [comment]
Hello, 

Was it a wrong procedure..?

**Comment by simonemainardi** [comment]
see the manual, page 55: https://github.com/ntop/ntopng/blob/dev/doc/UserGuide.pdf
