### ISSUE TITLE
Why is the real-time traffic dashboard not real-time.

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#4370]
![image](https://user-images.githubusercontent.com/44804599/92347380-8150b480-f102-11ea-96ba-04215c5e8f06.png)

**Comment by simonemainardi** [comment]
Please use discord for questions: https://www.ntop.org/community/

You can control the refresh rate from

![image](https://user-images.githubusercontent.com/3397663/92390800-dfd65c80-f11b-11ea-8429-898c5a83c9fa.png)

That chart shows realtime data over the most recent 10 minutes.
