### ISSUE TITLE
Geomap not Populating

### ISSUE THREAD

**Issue by manjotsc** [ntop/ntopng#4371]
I updated geoipupdate and run it , but still data is not populating.

 
![Annotation 2020-09-07 062259](https://user-images.githubusercontent.com/51430971/92377754-a3cad980-f0d2-11ea-91b7-75c7537ee1a5.png)

**Comment by simonemainardi** [comment]
Please show the output of ntopng. It will tell you if the geoip databases are loaded successfully.

**Comment by manjotsc** [comment]
07/Sep/2020 20:48:28 [Ntop.cpp:2295] Setting local networks to 127.0.0.0/8,fe80::/10
07/Sep/2020 20:48:28 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
07/Sep/2020 20:48:28 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
07/Sep/2020 20:48:28 [NtopPro.cpp:297] [LICENSE] Reading license from Redis
07/Sep/2020 20:48:28 [NtopPro.cpp:425] [LICENSE] Unable to validate license [Empty license file]
07/Sep/2020 20:48:28 [NtopPro.cpp:493] WARNING: [LICENSE] Invalid license [Empty license file]
07/Sep/2020 20:48:28 [NtopPro.cpp:510] WARNING: [LICENSE] ntopng will now run in Enterprise L edition for 10 minutes
07/Sep/2020 20:48:28 [NtopPro.cpp:512] WARNING: [LICENSE] before returning to community mode
07/Sep/2020 20:48:28 [NtopPro.cpp:514] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
07/Sep/2020 20:48:28 [NtopPro.cpp:516] WARNING: [LICENSE] or run ntopng in community mode starting
07/Sep/2020 20:48:28 [NtopPro.cpp:517] WARNING: [LICENSE] ntopng --community
07/Sep/2020 20:48:28 [PcapInterface.cpp:93] Reading packets from  [id: 1]
07/Sep/2020 20:48:28 [Ntop.cpp:2400] Registered interface lo [id: 1]
07/Sep/2020 20:48:28 [PcapInterface.cpp:93] Reading packets from  [id: 2]
07/Sep/2020 20:48:28 [Ntop.cpp:2400] Registered interface eth1 [id: 2]
07/Sep/2020 20:48:28 [PcapInterface.cpp:93] Reading packets from  [id: 3]
07/Sep/2020 20:48:28 [Ntop.cpp:2400] Registered interface eth3 [id: 3]
07/Sep/2020 20:48:29 [PcapInterface.cpp:93] Reading packets from  [id: 4]
07/Sep/2020 20:48:29 [Ntop.cpp:2400] Registered interface eth4 [id: 4]
07/Sep/2020 20:48:29 [PcapInterface.cpp:93] Reading packets from  [id: 5]
07/Sep/2020 20:48:29 [Ntop.cpp:2400] Registered interface eth5 [id: 5]
07/Sep/2020 20:48:29 [main.cpp:312] PID stored in file /var/run/ntopng.pid
07/Sep/2020 20:48:29 [Geolocation.cpp:140] Loaded database dbip-asn-lite.mmdb [/usr/share/ntopng/httpdocs/geoip/dbip-asn-lite.mmdb][ip_version: 6]
07/Sep/2020 20:48:29 [Geolocation.cpp:140] Loaded database dbip-country-lite.mmdb [/usr/share/ntopng/httpdocs/geoip/dbip-country-lite.mmdb][ip_version: 6]
07/Sep/2020 20:48:29 [Geolocation.cpp:91] Using geolocation provided by DB-IP (https://db-ip.com)
07/Sep/2020 20:48:29 [HTTPserver.cpp:1529] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
07/Sep/2020 20:48:29 [HTTPserver.cpp:1532] HTTP server listening on 3000
07/Sep/2020 20:48:29 [Utils.cpp:764] User changed to ntopng
07/Sep/2020 20:48:29 [main.cpp:382] Working directory: /var/lib/ntopng
07/Sep/2020 20:48:29 [main.cpp:384] Scripts/HTML pages directory: /usr/share/ntopng
07/Sep/2020 20:48:29 [Ntop.cpp:433] Welcome to ntopng x86_64 v.4.1.200907 - (C) 1998-20 ntop.org
07/Sep/2020 20:48:29 [Ntop.cpp:443] Built on Ubuntu 20.04.1 LTS
07/Sep/2020 20:48:29 [NtopPro.cpp:699] [LICENSE] System Id:     6DA5629B7104A212
07/Sep/2020 20:48:29 [NtopPro.cpp:700] [LICENSE] Edition:       Enterprise L
07/Sep/2020 20:48:29 [NtopPro.cpp:701] [LICENSE] License Type:  Time-Limited [Empty license file] License
07/Sep/2020 20:48:29 [NtopPro.cpp:721] [LICENSE] Validity:      Until Mon Sep  7 20:58:28 2020
07/Sep/2020 20:48:29 [Ntop.cpp:834] Adding 127.0.0.1/32 as IPv4 interface address for lo
07/Sep/2020 20:48:29 [Ntop.cpp:843] Adding 127.0.0.0/8 as IPv4 local network for lo
07/Sep/2020 20:48:29 [Ntop.cpp:834] Adding 192.168.40.6/32 as IPv4 interface address for eth3
07/Sep/2020 20:48:29 [Ntop.cpp:843] Adding 192.168.40.0/24 as IPv4 local network for eth3
07/Sep/2020 20:48:29 [Ntop.cpp:834] Adding 192.168.39.6/32 as IPv4 interface address for eth4
07/Sep/2020 20:48:29 [Ntop.cpp:843] Adding 192.168.39.0/24 as IPv4 local network for eth4
07/Sep/2020 20:48:29 [Ntop.cpp:834] Adding 192.168.80.6/32 as IPv4 interface address for eth5
07/Sep/2020 20:48:29 [Ntop.cpp:843] Adding 192.168.80.0/24 as IPv4 local network for eth5
07/Sep/2020 20:48:29 [Ntop.cpp:865] Adding ::1/128 as IPv6 interface address for lo
07/Sep/2020 20:48:29 [Ntop.cpp:875] Adding ::1/128 as IPv6 local network for lo
07/Sep/2020 20:48:29 [Ntop.cpp:865] Adding fe80::c4b0:5bff:fea2:5c99/128 as IPv6 interface address for eth1
07/Sep/2020 20:48:29 [Ntop.cpp:875] Adding fe80::c4b0:5bff:fea2:5c99/64 as IPv6 local network for eth1
07/Sep/2020 20:48:29 [Ntop.cpp:865] Adding fe80::b0a4:bbff:fe0f:a6a2/128 as IPv6 interface address for eth3
07/Sep/2020 20:48:29 [Ntop.cpp:875] Adding fe80::b0a4:bbff:fe0f:a6a2/64 as IPv6 local network for eth3
07/Sep/2020 20:48:29 [Ntop.cpp:865] Adding fe80::e016:60ff:fe53:e84f/128 as IPv6 interface address for eth4
07/Sep/2020 20:48:29 [Ntop.cpp:875] Adding fe80::e016:60ff:fe53:e84f/64 as IPv6 local network for eth4
07/Sep/2020 20:48:29 [Ntop.cpp:865] Adding fe80::e8da:4eff:fede:cd80/128 as IPv6 interface address for eth5
07/Sep/2020 20:48:29 [Ntop.cpp:875] Adding fe80::e8da:4eff:fede:cd80/64 as IPv6 local network for eth5
07/Sep/2020 20:48:29 [PeriodicActivities.cpp:106] Started periodic activities loop...
07/Sep/2020 20:48:30 [startup.lua:49] Processing startup.lua: please hold on...
Failed to print the table: Broken pipe
Failed to print the table: Broken pipe
07/Sep/2020 20:48:32 [startup.lua:247] Startup completed
07/Sep/2020 20:48:32 [PeriodicActivities.cpp:168] Each periodic activity script will use 6 threads
07/Sep/2020 20:48:32 [NetworkInterface.cpp:2299] Started packet polling on interface lo [id: 1]...
07/Sep/2020 20:48:32 [NetworkInterface.cpp:2299] Started packet polling on interface eth1 [id: 2]...
07/Sep/2020 20:48:32 [NetworkInterface.cpp:2299] Started packet polling on interface eth3 [id: 3]...
07/Sep/2020 20:48:32 [NetworkInterface.cpp:2299] Started packet polling on interface eth4 [id: 4]...
07/Sep/2020 20:48:32 [NetworkInterface.cpp:2299] Started packet polling on interface eth5 [id: 5]...

**Comment by simonemainardi** [comment]
It seems everything has been loaded correctly:

```
Loaded database dbip-asn-lite.mmdb [/usr/share/ntopng/httpdocs/geoip/dbip-asn-lite.mmdb][ip_version: 6]
Loaded database dbip-country-lite.mmdb [/usr/share/ntopng/httpdocs/geoip/dbip-country-lite.mmdb][ip_version: 6]
```

Please, visit page Hosts->Countries and see if you have results there. Perhaps you've only private addresses.

**Comment by manjotsc** [comment]
Under Countries, it says "No Results Found", I have ntopng 3.0. Just running fine on same subnet, geo map also working, But ntopng 4.0 not showing any data.

**Comment by manjotsc** [comment]
@simonemainardi I think you are right, ntopng is detecting network activity, but it's detecting local activity only. It is not able to see public connections for some reasons. Under Flows I able to see local connection only.

**Comment by ShagoY** [comment]
Hello,

After reading that it worked at your place (and still not at mine), I decided to reinstall Ntopng.
And finally, I noticed that it didn't work with your ntopng-data package but works perfectly with MaxMind geolocation.

During my test with your package, I had : 
```
[Geolocation.cpp:141] Loaded database dbip-asn-lite.mmdb [/usr/share/ntopng/httpdocs/geoip/dbip-asn-lite.mmdb][ip_version: 6] [/usr/share/ntopng/httpdocs/geoip/dbip-asn-lite.mmdb] [ip_version: 6]
[Geolocation.cpp:141] Loaded database dbip-country-lite.mmdb [/usr/share/ntopng/httpdocs/geoip/dbip-country-lite.mmdb][ip_version: 6]
```
With Maxmind:
```
[Geolocation.cpp:141] Loaded database GeoLite2-ASN.mmdb [/var/lib/GeoIP/GeoLite2-ASN.mmdb][ip_version: 6] [ip_version: 6]
[Geolocation.cpp:141] Loaded database GeoLite2-City.mmdb [/var/lib/GeoIP/GeoLite2-City.mmdb][ip_version: 6] [ip_version: 6]
```
Moreover, ntopng automatically installs ntopng-data and that it is taken in priority over Maxmind.
It might be interesting to do the opposite?
This would avoid to install ntopng-data manually after a "clean" installation.

ntopng v.4.2.201111

**Comment by simonemainardi** [comment]
@cardigliano can you please check this reported behavior?
