### ISSUE TITLE
Historical flows API(query aggregated flows or total sum) as provided in the UI of ntopng.

### ISSUE THREAD

**Issue by junaid-soomro-ivolve** [ntop/ntopng#4372]
I have seen this explorer tab which lets me query aggregated flows and RAW flows. How can i query the same in API call? there is no documentation or parameters list provided in the official website. I am trying to sum total src2dst bytes where ipv4_src_addr = ipaddress and flow_clause = aggregated within a specific timeframe.

Thank you.

**Comment by junaid-soomro-ivolve** [comment]
also if you guys could add difference between aggregated and RAW flows.

**Comment by simonemainardi** [comment]
aggregate flows are no longer present - they were experimental code which has now been removed for performance.

**Comment by junaid-soomro-ivolve** [comment]
then is there a query available that i can use to sum src2dst_bytes of a specific src_ipv4_addr acting as client within the specified timeframe?

**Comment by simonemainardi** [comment]
This is not supported via API

**Comment by junaid-soomro-ivolve** [comment]
so what i can do is list flows via the historical API passing where_clause as source ip and then accumulate the sum of src2dst bytes myself.

**Comment by simonemainardi** [comment]
As said aggregated flows are no longer part of ntopng. You'll be able to extract all flows once FR https://github.com/ntop/ntopng/issues/4349 will be implemented.
