### ISSUE TITLE
Show recipients bound to a pool

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4374]
In pages such as active monitoring, SNMP... you see a page such as
![Screen Shot 2020-09-08 at 10 55 33](https://user-images.githubusercontent.com/4493366/92457060-094ac300-f1c4-11ea-9b7c-d43849cdf74a.png)

It is requested to
- the edit link should allow the selected pool (and not all pools as today) to be edited by opening a page such as 
![Screen Shot 2020-09-08 at 10 56 11](https://user-images.githubusercontent.com/4493366/92457227-41ea9c80-f1c4-11ea-8834-46a07bb180c3.png) without any further click. In this case saving the dialog value should bounce back to the original page (e.g. the active monitoring element being edited) or at least have a shortcut somewhere to return there.
- add a small label under the drop down pool menu that contains a string like
"No recipients configured for the above pool" or "Luca, Jim and 3 other recipients configured for the above pool. This label will change when a new recipient is selected from the list

**Comment by gabryon99** [comment]
A little label with a recipients list has been added for SNMP Devices and Active Monitoring Records, see the commit: https://github.com/ntop/ntopng/commit/1fc31fa6abe8cf80ac1d257b086ac1d673ec96a7
