### ISSUE TITLE
Extend the recipients page with usage information

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4375]
Currently nowhere in ntopng is specified where recipients are used, but only the opposite (who uses a recipient). It is requested to extend the recipients page and 
- add a new column "Users" with the number of configured users for such recipient
- inside the recipient edit add a way to edit the "users" of such recipient by adding for instance direct hyperlinks to the user

**Comment by gabryon99** [comment]
To implement this enhancement we require a way to get the users about a recipient. Having this resource we can insert a new column called 'Users' that shows a brief list of the recipient's user. When clicking on the list a modal with the complete Users List will be shown.

<img width="568" alt="Screenshot 2020-09-10 at 08 09 26" src="https://user-images.githubusercontent.com/14114916/92688064-f3acd900-f33c-11ea-80c0-473dc3d940e5.png">

Each entry of the list brings to the edit pool modal so a user can unbind a recipient from that pool. On the finish editing the user will be brought back to the recipients list.

**Comment by simonemainardi** [comment]
implemented REST endpoint:

example:

```
curl -s -u admin:admin1  -H "Content-Type: application/json" -d '{"recipient_id": 2}'  http://localhost:3000/lua/rest/v1/get/recipient/pools.lua
{"rc_str":"OK","rc_str_hr":"Success","rc":0,"rsp":[{"members":[],"configset_id":0,"key":"system","name":"Default","recipients":[{"recipient_id":2},{"recipient_id":3},{"recipient_id":4}],"member_details":[],"pool_id":0,"configset_details":{"name":"Default"}},{"recipients":[{"recipient_id":2},{"recipient_id":3},{"recipient_id":4}],"configset_id":0,"key":"mac","name":"Default","members":[],"member_details":[],"pool_id":0,"configset_details":{"name":"Default"}},{"members":[],"configset_id":0,"key":"flow","name":"Default","recipients":[{"recipient_id":2},{"recipient_id":3},{"recipient_id":4}],"member_details":[],"pool_id":0,"configset_details":{"name":"Default"}},{"members":[],"configset_id":0,"key":"local_network","name":"Default","recipients":[{"recipient_id":2},{"recipient_id":3},{"recipient_id":4}],"member_details":[],"pool_id":0,"configset_details":{"name":"Default"}},{"members":["icmp@one.one.one.one"],"configset_id":0,"key":"active_monitoring","name":"my_am_pool","recipients":[{"recipient_id":2},{"recipient_id":3}],"member_details":{"icmp@one.one.one.one":{"name":"icmp://one.one.one.one"}},"pool_id":2,"configset_details":{"name":"Default"}},{"recipients":[{"recipient_id":2},{"recipient_id":3},{"recipient_id":4}],"configset_id":0,"key":"host_pool","name":"Default","members":[],"member_details":[],"pool_id":0,"configset_details":{"name":"Default"}}]}
```

**Comment by simonemainardi** [comment]
Can you please replace anywhere the word `user` in the commit with `pool`? Users in ntopng are another thing and this can create a mess. This is also in conflict with the column `Uses` which represents the number of times the recipient has been used and not the number of `users`.

**Comment by lucaderi** [comment]
I propose to change

Recipient Users: XXXX

with 
Recipient XXX used by:

**Comment by simonemainardi** [comment]
For the frontend, I agree.

For the backend, I would do the replace as suggested to keep things in order.

**Comment by simonemainardi** [comment]
please handle https://github.com/ntop/ntopng/issues/4375#issuecomment-705365497

**Comment by lucaderi** [comment]
This is a somehow overlapping with #4574 that is now fixed.
