### ISSUE TITLE
[pools] Show `builtin` endpoints but make them uneditable and undeletable

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4377]
Currently, `builtin` endpoints are hidden from 

![image](https://user-images.githubusercontent.com/3397663/92621515-2f578c80-f2c4-11ea-8695-c2813301943c.png)

Actual hiding is done in `get_notification_configs.lua` using a boolean flag `builtin` shipped with the endpoint configuration. 

It is requested to show these builtin endpoints in the UI but *prevent* users from deleting / editing them.

**Comment by gabryon99** [comment]
Done it. See the commit: https://github.com/ntop/ntopng/commit/2e0b7015fc81559d4219911f8598c94267d9d4ca
