### ISSUE TITLE
[pools] Show `builtin` recipients but make them non-editable and non-deletable

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4378]
Builtin recipients are currently hidden from

![image](https://user-images.githubusercontent.com/3397663/92622188-113e5c00-f2c5-11ea-9b7d-3e715f8f92d2.png)

Actual hiding is done in `get_recipients_endpoint.lua` using boolean flag `builtin`. It is requested to use this flag to show `builtin` recipients but they must be non-editable and non-deletable.

**Comment by gabryon99** [comment]
Done it. See the commit: https://github.com/ntop/ntopng/commit/2048db187fa6c2223ed71b176375d482979f5a8e
