### ISSUE TITLE
[pools] Show `builtin` recipients in pool modals

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4379]
Builtin recipients are currently hidden from pool modals, e.g., 

![image](https://user-images.githubusercontent.com/3397663/92622926-eb658700-f2c5-11ea-9e37-b11333ae0f65.png)

It is requested to show `builtin` recipients in add/edit pool modals. The add modal must have `builtin` recipients selected by default in the multiselect.

**Comment by gabryon99** [comment]
Now the builtin recipients are always shown in the multi-select and always selected for the add modal. See the commit: https://github.com/ntop/ntopng/commit/9a2fea3a6b579f5276774e345c799d90882f60f2
