### ISSUE TITLE
Problem With Historical View

### ISSUE THREAD

**Issue by ValeDC** [ntop/ntopng#438]
Hallo,
i've just update my previous pro version to 2.2.160308 (the current stable), acquiring a new licence "ntopng Pro Small Business Linux/Win (x64)", but i can't see the tabs of the historical interface.

my enviroment:
Version 2.2.160308 - Professional Edition
Platform    x86_64-unknown-linux-gnu (x86_64) - 64 bit
Built on    CentOS Linux release 7.1.1503 (Core)

nDPI    1.7.0-1.7-stable-180-a121161

content of conf file that i use to launch the ntopng:
-G=/var/tmp/ntopng.pid
-i=tcp://127.0.0.1:5550
-i=tcp://127.0.0.1:5551
-i=tcp://127.0.0.1:5552,tcp://127.0.0.1:5553
-i=tcp://127.0.0.1:5554
-m="192.168.0.0/24,192.168.1.0/24,192.168.2.0/24,192.168.3.0/24,192.168.5.0/24,192.168.8.0/24,192.168.9.0/24,192.168.10.0/24,192.168.14.0/24,192.168.12.0/24,192.168.30.0/24,192.168.216.128/25,192.168.240.0/24,192.168.0.0/16,172.16.0.0/16,172.31.0.0/16,172.18.0.0/16,172.17.4.0/24,10.0.0.0/8"
-p=/etc/ntopng/protos.txt
-F=mysql;127.0.0.1;ntopng;flows;ntop;ntop

the db was correctly configured and the ntopng can connect to it (it creates and is still populating the tables):
09/Mar/2016 14:47:49 [MySQLDB.cpp:273] Succesfully connected to MySQL [127.0.0.1:ntop]

reading a previous mailing list, i've tried to debug the query made when i choose the historical interface page, changing the following line in scripts/lua/modules/db_utils.lua
if(1) then io.write(sql.."\n") end

the query was:
select INET_NTOA(IP_SRC_ADDR) AS IP_SRC_ADDR,INET_NTOA(IP_DST_ADDR) AS IP_DST_ADDR ,L4_SRC_PORT,L4_DST_PORT,VLAN_ID,PROTOCOL,FIRST_SWITCHED,LAST_SWITCHED,PACKETS,BYTES,idx,L7_PROTO,INFO,PROFILE from flowsv4_1 where FIRST_SWITCHED <= 1457533661 and FIRST_SWITCHED >= 1457530061 order by BYTES desc limit 5 OFFSET 0
select IP_SRC_ADDR, IP_DST_ADDR ,L4_SRC_PORT,L4_DST_PORT,VLAN_ID,PROTOCOL,FIRST_SWITCHED,LAST_SWITCHED,PACKETS,BYTES,idx,L7_PROTO,INFO,PROFILE from flowsv6_1 where FIRST_SWITCHED <= 1457533661 and FIRST_SWITCHED >= 1457530061 order by BYTES desc limit 5 OFFSET 0

only the first query gaves a result (i have no ipv6 traffic), trying it directly in the db:
+-------------+----------------+-------------+-------------+---------+----------+----------------+---------------+---------+----------+-------+----------+------+---------+
| IP_SRC_ADDR | IP_DST_ADDR    | L4_SRC_PORT | L4_DST_PORT | VLAN_ID | PROTOCOL | FIRST_SWITCHED | LAST_SWITCHED | PACKETS | BYTES    | idx   | L7_PROTO | INFO | PROFILE |
+-------------+----------------+-------------+-------------+---------+----------+----------------+---------------+---------+----------+-------+----------+------+---------+
| 172.17.4.27 | 172.16.130.126 |       57968 |        1521 |       0 |        6 |     1457531157 |    1457531276 |   34789 | 11039797 | 42820 |      167 |      |         |
| 172.17.4.27 | 172.16.130.126 |       58082 |        1521 |       0 |        6 |     1457532975 |    1457533094 |   28181 |  9655106 | 58454 |      167 |      |         |
| 172.17.4.27 | 172.16.130.126 |       58014 |        1521 |       0 |        6 |     1457531508 |    1457531627 |   29439 |  9164617 | 46102 |      167 |      |         |
| 172.17.4.27 | 172.16.130.126 |       58102 |        1521 |       0 |        6 |     1457533114 |    1457533224 |   25072 |  8514434 | 59674 |      167 |      |         |
| 172.17.4.27 | 172.16.130.126 |       57998 |        1521 |       0 |        6 |     1457531299 |    1457531418 |   23649 |  7724765 | 44071 |      167 |      |         |
+-------------+----------------+-------------+-------------+---------+----------+----------------+---------------+---------+----------+-------+----------+------+---------+

i can see the historical interface page (with the charts view), but i can't see the tabs:
charts
ipv4flows
ipv6flows
talkers
protocols
pcaps

as you can see in this screenshot:

![ntopng-historical](https://cloud.githubusercontent.com/assets/17746808/13640962/0a5027b2-e617-11e5-801b-f2f559fe3787.jpg)

am I missing something?

thanks in advance,
Best Regards.
Valerio Dalla Casa

**Comment by lucaderi** [comment]
@ValeDC You need to install the development version (non-stable) to see those features that will be integrated in the next stable.
