### ISSUE TITLE
[pools] Show additional pools in the UI

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4382]
Once https://github.com/ntop/ntopng/issues/4381 is completed, it is requested to add extra pills in 

![image](https://user-images.githubusercontent.com/3397663/92624585-f91c0c00-f2c7-11ea-8903-9d76f695fa05.png)

For "Host Pools", "Flows", "Devices" and "System" pools.

The pages will only show the "Default" pool, without any recipient and the "Default" config.

- The "Default" pool will not be deletable
- No "plus" sign will be shown as no addition of pools will be permitted.
- The only action which can be performed is the edit to only assign/unassign recipients to the "Default" pool using the REST API implemented in  https://github.com/ntop/ntopng/issues/4381

**Comment by simonemainardi** [comment]
@gabryon99 please start doing this implementation.

**Comment by gabryon99** [comment]
The new pools have been added as requested. See the commit: https://github.com/ntop/ntopng/commit/3b071dd0462e6022d7642bef977ceb3cbebce2cc
