### ISSUE TITLE
[pools] Missing Endpoint/Recipient Dependency Check

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4389]
As of today it is possible to delete an endpoint while having a recipient for such endpoint defined. The result is this error

10/Sep/2020 12:02:17 [LuaEngine.cpp:909] WARNING: Script failure [/Users/deri/network/ntopng/scripts/lua/get_recipients_endpoint.lua][...i/network/ntopng/scripts/lua/get_recipients_endpoint.lua:28: attempt to index a nil value (field 'endpoint_conf')]

and inability to use the GUI.

Some possible fixes:
- prevent deletion of endpoints with recipients configured
- when deleting the endpoint add a warning telling that "X recipients for endpoint Y will be deleted: do you want to continue?". I prefer this

**Comment by simonemainardi** [comment]
Lua exception is fixed.

I've extended the getter to return, along with available configs, all the recipients associated. So `get_notification_configs.lua` returns, for each config, the list of available `recipients`. @gabryon99 please use this information to:

- Add an extra column Used by with information such as "recipient1, recipient2, and X more."
- Add a warning shown when deleting an configuration which tells "X recipients for endpoint Y will be deleted" as suggested.

**Comment by gabryon99** [comment]
The extra column has been added. Now when an endpoint is about to be removed then the modal will show how many recipients will be deleted as well. See the commit: https://github.com/ntop/ntopng/commit/7c60d03e0378e25a28c464ffe5fbebae2ff0d892

**Comment by simonemainardi** [comment]
broken. 

adding many recipients for the same endpoint breaks the page:

![image](https://user-images.githubusercontent.com/3397663/92940607-9786a980-f44f-11ea-91ed-427c562526c7.png)

requested NOT to break the page and show "and X more"

**Comment by gabryon99** [comment]
Fixed. See the commit: https://github.com/ntop/ntopng/commit/4eb22f261a836fedd631999d264232e315173398

**Comment by simonemainardi** [comment]
request was to use work 'more' not 'other' so you don't have to handle plural/singular.

**Comment by gabryon99** [comment]
<img width="583" alt="Screenshot 2020-09-14 at 15 43 49" src="https://user-images.githubusercontent.com/14114916/93093538-17578280-f6a1-11ea-8097-ffe7ec255028.png">

Thanks for the suggestion. I replaced other/others with `and X more`, you can see the screenshot above. Check the commit: https://github.com/ntop/ntopng/commit/7a76cbf880ce71ac863520ad357ee23fe30456dc
