### ISSUE TITLE
Tune or disable goodput for Sflow

### ISSUE THREAD

**Issue by seismiccollision** [ntop/ntopng#439]
Because Sflow does not capture enough unique data I am seeing lots of alerts for goodput in the latest version. Is there a way to disable or tune that alert?

**Comment by lucaderi** [comment]
We need to tune the code you are right. I have disabled goodput computation for ZMQ interfaces. Please resync the code or overnight a new build will include it.

**Comment by lucaderi** [comment]
https://github.com/ntop/ntopng/commit/ec572f6084ad9fe22fe75bca98cfa6fcd78920d3

**Comment by seismiccollision** [comment]
@lucaderi no worries, thanks for your support!
