### ISSUE TITLE
Unable to delete recipients 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4390]
![Screen Shot 2020-09-10 at 12 15 37](https://user-images.githubusercontent.com/4493366/92716652-62029300-f35f-11ea-92a4-8daac4834c00.png)

Clicking on the delete button has no effect

**Comment by gabryon99** [comment]
The problem was on handling the server response that changed. Now the problem has been fixed. See the commit: https://github.com/ntop/ntopng/commit/2e0b7015fc81559d4219911f8598c94267d9d4ca
