### ISSUE TITLE
[pools] Implement Endpoint/Recipient Factory Reset Button

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4391]
Add a new button in Endpoint+Recipient that allows to restore (ONLY for Endpoint+Recipient) to factory deleting all defined endpoint/recipient and adding the default ones (if any)

**Comment by simonemainardi** [comment]
REST API endpoints implemented. Please add the buttons in the UI using the following endpoints:

- RECIPIENTS: `curl -s -u admin:admin1  -H "Content-Type: application/json"  http://localhost:3000/lua/rest/v1/delete/recipients.lua`
- ENDPOINTS: ` curl -s -u admin:admin1  -H "Content-Type: application/json"  http://localhost:3000/lua/rest/v1/delete/endpoints.lua`
