### ISSUE TITLE
[pools] Missing pool recipients multiselect

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4393]
When there's only the default recipient, the Recipient multiselect in edit/add pool is missing

![image](https://user-images.githubusercontent.com/3397663/92729871-41dccf00-f373-11ea-9bfe-51f6fd3cdacb.png)

Recipient multiselect must always be present as there will always be at least the builtin recipient. See https://github.com/ntop/ntopng/issues/4379

**Comment by gabryon99** [comment]
Now there is always the multiselect. See the commit: https://github.com/ntop/ntopng/commit/8617c045ef8a8ed499ccc52cc7bff25172e62dcf
