### ISSUE TITLE
[pools] No recipient shown when there's only the builtin

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4394]
When there's only the builtin endpoint+recipient, the recipient page is shown as empty

![image](https://user-images.githubusercontent.com/3397663/92764853-19fe6300-f395-11ea-9b00-26e53d921db6.png)

![image](https://user-images.githubusercontent.com/3397663/92764877-1ec31700-f395-11ea-952d-da4dafaa3c15.png)

**Comment by gabryon99** [comment]
Fixed, now the recipients list is always shown even there are only the built-in endpoints/recipients. See the commit: https://github.com/ntop/ntopng/commit/f8ef59e19da0dce81dc1086cd5eda03e77136ae9

**Comment by simonemainardi** [comment]
broken.

There's a plus sign which is highlighted but clicking on it is ineffective: nothing happens.

![image](https://user-images.githubusercontent.com/3397663/92940777-cf8dec80-f44f-11ea-8aa3-6e23625e74e3.png)

**Comment by gabryon99** [comment]
Disabled the button when there are no endpoints. See the commit: https://github.com/ntop/ntopng/commit/37ed43f74f2218f7123ee9880730f636980a2019

**Comment by simonemainardi** [comment]
Still bugged:

now the plus sign always stays greyed-out and it's impossible to add recipients even where there are non-builtin endpoints:

![image](https://user-images.githubusercontent.com/3397663/93086664-c0997b00-f697-11ea-8872-b17b1c2fd505.png)


![image](https://user-images.githubusercontent.com/3397663/93086604-aa8bba80-f697-11ea-8317-f3f1022be0d0.png)

**Comment by gabryon99** [comment]
This has been fixed. If there are only recipients that are builtin then the button will be greyed out, otherwise, it will be enabled. See the commit: https://github.com/ntop/ntopng/commit/024f8b4572947389dfee6c660bcb723e48b11713
