### ISSUE TITLE
Ntopng crashes every time (v.4.1.200911)

### ISSUE THREAD

**Issue by cfrancis2b** [ntop/ntopng#4396]
Ntopng crashes every time I try to login after the last update.

v.4.1.200911

Regards.

**Comment by simonemainardi** [comment]
Are you using the packaged version? Building from source?

**Comment by cfrancis2b** [comment]
Packaged version

**Comment by cfrancis2b** [comment]
Sep 11 06:23:22 Installed: ntopng-4.1.200911-10878.x86_64
Sep 11 06:27:46 Installed: ntopng-data-4.1.200911-10878.noarch
Sep 11 06:27:46 Installed: ndpi-3.3.0-2810.x86_64
Sep 11 06:27:47 Installed: pfring-7.7.0-3169.x86_64
Sep 11 06:27:49 Installed: nprobe-9.1.200911-6951.x86_64
Sep 11 06:27:53 Installed: ntopng-4.1.200911-10878.x86_64
Sep 11 06:27:54 Installed: cento-1.11.200911-581.x86_64

**Comment by cfrancis2b** [comment]
Fixed with today's update

**Comment by cfrancis2b** [comment]
Sep 11 21:31:21 Updated: pfring-7.7.0-3170.x86_64
Sep 11 21:31:23 Updated: ntopng-data-4.1.200912-10893.noarch
Sep 11 21:31:25 Updated: nprobe-9.1.200912-6951.x86_64
Sep 11 21:31:29 Updated: ntopng-4.1.200912-10893.x86_64
Sep 11 21:31:29 Updated: cento-1.11.200912-581.x86_64
