### ISSUE TITLE
Theme preference per-user

### ISSUE THREAD

**Issue by santuari** [ntop/ntopng#4397]
Our customer can select a preference of the theme type (dark and light) within our product. We would like to align the customer theme preference also in ntopng.  

The theme preference in our product are per-user, so we would like that the theme preference (dark and light) in ntopng is per-user. In the past, ntopng had the sidebar preference per-user (https://github.com/ntop/ntopng/issues/3344), but now with the new theme is configurable only for all the user.

Moreover, we need a way to automatically configure this theme preference as for the rest of the User preference. I think that a REST API to configure this theme preference per-user would be the best. Similar to what we have for the creation/edit of the user (https://github.com/ntop/ntopng/issues/3344 and https://github.com/ntop/ntopng/issues/4218).

What do you think?
Thanks!
Michele

**Comment by simonemainardi** [comment]
We believe that for now having a global per-ntopng theme style suffices so we cannot accomodate this request.
