### ISSUE TITLE
Implement plugin for generating alerts based on flow risk

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4398]
nDPI implements flow risk that is used to detect per-flow issues. In addition to increasing the score based on the risk, this plugin should trigger alert when specific risks (identified by nDPI) are found.

**Comment by simonemainardi** [comment]
see https://github.com/ntop/ntopng/tree/dev/scripts/plugins/flow_risks

**Comment by lucaderi** [comment]
Il is requested to implement the edit button in the flow risk plugin and specify what risks are considered for alert generation
<img width="1262" alt="Screenshot 2020-09-30 at 12 37 51" src="https://user-images.githubusercontent.com/4493366/94675465-1027aa00-031a-11eb-9834-8144293a9140.png">

**Comment by simonemainardi** [comment]
disable alert generation (only leave flow status and score increase) for the default handler in flow_risks.lua
