### ISSUE TITLE
Date format preference

### ISSUE THREAD

**Issue by bakerds** [ntop/ntopng#4399]
(Feature request)
It would be nice if the web UI could be configured to display dates in big-endian (ISO 8601, 2020-09-11), little-endian (most of the world, 11/09/2020), or middle-endian (USA, 09/11/2020) format according to the user's preference or system settings.

**Comment by MatteoBiscosi** [comment]
Implemented as requested. To choose the date format you have to go 'Settings->Preferences->User Interface' and change the Date Format preference.
