### ISSUE TITLE
GeoMap: No show the hosts or their flows.

### ISSUE THREAD

**Issue by cfrancis2b** [ntop/ntopng#4400]
Geo Map, shows the map but does not graph the position of the hosts or their flows.

Regards.

**Comment by simonemainardi** [comment]
Checkout this and report: https://github.com/ntop/ntopng/issues/4371

**Comment by ShagoY** [comment]
Same here, I have the information of the countries in "Hosts > Countries", the flags in the flows but nothing in the geomaps.

ntopng Community v.4.1.200911

**Comment by ShagoY** [comment]
On my ELK stack, ntopng returns the value 0,0 for *_IP_LOCATION

**Comment by cfrancis2b** [comment]
The database is updated without news.

lrwxrwxrwx    1 root root       17 sep 17  2019 GeoIP.dat -> GeoIP-initial.dat
-rw-r--r--    1 root root       19 sep 17  2019 GeoIP.dat.test
-rw-r--r--    1 root root  1242574 ago  8  2019 GeoIP-initial.dat
-rw-------    1 root root        0 sep 24  2019 .geoipupdate.lock
lrwxrwxrwx    1 root root       19 sep 17  2019 GeoIPv6.dat -> GeoIPv6-initial.dat
-rw-r--r--    1 root root  2322773 ago  8  2019 GeoIPv6-initial.dat
-rw-rw-r--    1 root root  6573048 feb 11  2020 GeoLite2-ASN.mmdb
-rw-rw-r--    1 root root 64301319 sep 17 00:27 GeoLite2-City.mmdb
-rw-rw-r--    1 root root  3883637 sep 17 00:27 GeoLite2-Country.mmdb
-rw-r--r--    1 root root 17156526 mar 13  2018 GeoLiteCity.dat
-rw-r--r--    1 root root  1068268 mar 13  2018 GeoLiteCountry.dat

I don't understand why it doesn't work.

**Comment by lucaderi** [comment]
This ticket is no longer relevan as GeoIP has been reworked since you opened it and it works for us
