### ISSUE TITLE
Unable to compile: [Makefile:148: src/Flow.o] Error 1

### ISSUE THREAD

**Issue by dragonxtek** [ntop/ntopng#4401]
Hi,
I have nDPI 3.3.0-2755-ad8318e2, and recently I tried to compile ntopng but yet I have the same issue in #3440 

> src/Flow.cpp: In member function ‘void Flow::fillZmqFlowCategory(const ParsedFlow*, ndpi_protocol*) const’:
> src/Flow.cpp:3916:83: error: cannot convert ‘long unsigned int*’ to ‘ndpi_protocol_category_t*’
> if(ndpi_match_custom_category(ndpi_struct, (char*)dst_name, strlen(dst_name), &id) == 0)
> ^~~
> In file included from /usr/local/include/ndpi/ndpi_main.h:31,
> from /home/dragonxtek/Downloads/ntopng-4.0/include/ntop_includes.h:118,
> from src/Flow.cpp:22:
> /usr/local/include/ndpi/ndpi_api.h:831:60: note: initializing argument 4 of ‘int ndpi_match_custom_category(ndpi_detection_module_struct*, char*, u_int, ndpi_protocol_category_t*)’
> char *name, u_int name_len, ndpi_protocol_category_t *id);
> make: *** [Makefile:148: src/Flow.o] Error 1

**Comment by simonemainardi** [comment]
make sure your ntopng and nDPI sources are aligned. Either:
- development: both ad the tip of `dev`
- stable ntopng at the tip of 4.0-stable branch and nDPI at the tip of 3.2-stable branch
