### ISSUE TITLE
FR:  Remove Geolocation popup

### ISSUE THREAD

**Issue by DigiAngel** [ntop/ntopng#4403]
This shows up on every screen, all the time:
![Screenshot from 2020-09-14 07-18-07](https://user-images.githubusercontent.com/947191/93090855-96759800-f65a-11ea-8a6a-6a4bdc579820.png)

I have no interest in the Geolocation feature currently...any way to disable this?  Thanks.

**Comment by simonemainardi** [comment]
duplicate of https://github.com/ntop/ntopng/issues/4198

**Comment by DigiAngel** [comment]
Well...that certainly sucks.
