### ISSUE TITLE
unable to log into web interface after logging out

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#4404]
I'm running ntopng on opnsense and i can't log into my ntopng web gui anymore.
it's a fresh install i changed the password and i was able to login and use the gui.
after logging off, i tried logging back in but it wouldn't take my username and password anymore.
I reinstalled the ntopng and redis package and even reinstalled opnsense completely and started from scratch.
am i doing something wrong?
Please assist.
Thank you.

**Comment by simonemainardi** [comment]
try:

- stop ntopng
- rm -rf /var/lib/ntopng/runtimeprefs.json (the file inside ntopng data directory)
- redis-cli flushall
- restart ntopng

**Comment by simonemainardi** [comment]
the you will have to re-enter the default password again

**Comment by simonemainardi** [comment]
did you follow the suggestion?

**Comment by simonemainardi** [comment]
No feedback received. Closing.
