### ISSUE TITLE
Daily Index name change

### ISSUE THREAD

**Issue by olg33** [ntop/ntopng#4408]
I'm exporting data  to ElasticSearch (ES) where ntopng creates a daily index automatically using the following command in /etc/ntopng/ntopng.conf:

`-F "es;flows;ntopng-%Y.%m.%d;http://localhost:9200/_bulk;"`

It creates daily indexes named, for instance:

ntopng-2020.09.14

I would like to change the name structure, so that daily indexes are named like this:

ntopng-0001
ntopng-0002

and so on,

Could you tell me how can I replace the %Y.%m.%d part in the command to accomplish this objective?

Thank you.

**Comment by simonemainardi** [comment]
This is not supported. Daily indices cannot be named with an incremental number. However, you can safely use the day number `%d`  or the month number `%m` or any combination of them to create daily indices as of today.

**Comment by olg33** [comment]
Ok I just removed the dots in between and that works for me

Thanks.
