### ISSUE TITLE
Error when specifing Httpdocs, scripts or callback directory

### ISSUE THREAD

**Issue by alberk8** [ntop/ntopng#441]
Hi,

I have compiled ntopng from source on Ubuntu 15.10 X64.  It works when installed in it's default directory.   To simulate the problem I just "sudo mv /usr/local/share/ntopng   /usr/local/share/ntopngx.

I get the following error
$ sudo ./ntopng ntopng.conf
12/Mar/2016 17:31:34 [Prefs.cpp:634] All HTTP user login disabled
12/Mar/2016 17:31:34 [Prefs.cpp:820] Logging into /var/tmp/ntopng/ntopng.log
12/Mar/2016 17:31:34 [Ntop.cpp:196] ERROR: Invalid directory  specified

ntopng version
v.2.3.160312 [Community Edition]
GIT rev:   dev:4295e7621b2a77d4c2787d0a6149f1f43035aaf6:20160312

ntopng.conf
-d=/var/tmp/ntopng
-1=/usr/local/share/ntopngx/httpdocs
-2=/usr/local/share/ntopngx/scripts
-3=/usr/local/share/ntopngx/scripts/callbacks
-i=eth0
-l=1
-e=
-G=/var/run/ntopng.pid
-m="192.168.0.0/16,172.16.0.0/16"  

syslog
Mar 12 17:26:10 PC kernel: [2240750.765646] device eth0 left promiscuous mode
Mar 12 17:27:06 PC ntopng: [Ntop.cpp:196] ERROR: Invalid directory  specified
Mar 12 17:29:41 PC ntopng: [Ntop.cpp:196] ERROR: Invalid directory  specified
Mar 12 17:31:34 PC ntopng: [Ntop.cpp:196] ERROR: Invalid directory  specified

**Comment by simonemainardi** [comment]
confirmed, fixing

**Comment by simonemainardi** [comment]
@alberk8, you also need to specify the install path when using custom installation directories (option -t):

```
-d=/var/tmp/ntopng
-1=/usr/local/share/ntopngx/httpdocs
-2=/usr/local/share/ntopngx/scripts
-3=/usr/local/share/ntopngx/scripts/callbacks
-t=/usr/local/share/ntopngx
-i=eth0
-l=1
-e=
-G=/var/run/ntopng.pid
-m="192.168.0.0/16,172.16.0.0/16"

```
