### ISSUE TITLE
Unable to set a Category on Applications

### ISSUE THREAD

**Issue by djstarfox** [ntop/ntopng#4410]
BUG.  Unable to change/set a category on any application (l7proto) in nTopNG  4.1.200816-11161 armhf.

Behavior:
1) Applications / Categories will not permit me to save a category assignment to any protocol.  All custom protocols defined in protos.txt file are listed as "Unspecified" and cannot be changed in the GUI.
/lua/admin/edit_categories.lua?category=cat_0&tab=protocols

2)  Alerts for this custom protocol cannot be configured:
E.g., "Client application 'HSTP' is not allowed by the configured Video application policy..."
Editing the "Video application policy" does not let me save either column "Device as Client" nor "Device as server".
/lua/admin/edit_device_protocols.lua?device_type=2&l7proto=255

**Comment by simonemainardi** [comment]
show the errors you get

**Comment by djstarfox** [comment]
There is no error displayed.  The webpage simply does not save the changes.  Try it yourself:
http://ntop/lua/admin/edit_categories.lua

**Comment by simonemainardi** [comment]
check the ntopng logs. My guess is that the applications file is not writable by user `ntopng`. Do a chown `ntopng:ntopng` on that file.

**Comment by djstarfox** [comment]
Are you referring to the protos.txt file?  No, the file permissions look fine to me, and I don't see anything in the logs, even with v=6 setting.  
```
root@pie3:/etc/ntopng# ls -al
drwxr-xr-x  2 root   root   4096 Sep 18 12:21 .
drwxr-xr-x 87 root   root   4096 Sep 19 10:36 ..
-rw-r--r--  1 ntopng ntopng 3917 Sep 18 12:10 ntopng.conf
-rw-r--r--  1 ntopng ntopng 1472 Aug 15 21:06 ntopng.conf.nprobe.sample
-rw-rw-r--  1 ntopng ntopng  140 Sep 27 17:01 protos.txt
```

And the web GUI is able to make changes to the file....  The problem is that it cannot change a category assignment to any application (custom or otherwise).  Appears to be a logic bug in the code.

**Comment by djstarfox** [comment]
I'm happy to report that the latest update has fixed this issue for me.

nTopNG 4.1.200816-11161 armhf --> 4.1.200930-11619

**Comment by simonemainardi** [comment]
thanks for reporting
