### ISSUE TITLE
[pools] Depict host score composition

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4414]
Once https://github.com/ntop/ntopng/issues/4413 is implemented, a pie chart with host score will be shown. Add a new tab "Score" under the host page with the pie chart. Add an hyperlink to the overall host score shown in the home page to the "Score" tab.

**Comment by lucaderi** [comment]
Not quite. Show a thermometer instead of a donut/pie chart that takes too much space
![Screen Shot 2020-09-15 at 23 49 05](https://user-images.githubusercontent.com/4493366/93268764-119b9300-f7ae-11ea-97c0-11caaaf5750c.png)

**Comment by simonemainardi** [comment]
@gabryon99 please use the implementation of https://github.com/ntop/ntopng/issues/4413
