### ISSUE TITLE
nIndex support broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4417]
In the latest dev version, nIndex support is broken.

When lucky no result is found
![Screen Shot 2020-09-15 at 23 33 10](https://user-images.githubusercontent.com/4493366/93267344-d7c98d00-f7ab-11ea-9994-07c8d8bf5ef0.png)

when unlucky a crash happens

15/Sep/2020 23:28:07 [NetworkInterface.cpp:2438] Started packet polling on interface en3 [id: 0]...
Assertion failed: (false), function container_get_cardinality, file /Users/deri/network/nIndex/CRoaring/include/roaring/containers/containers.h, line 228.
Abort

**Comment by cardigliano** [comment]
It seems this is working after latest dump changes
