### ISSUE TITLE
Syslog endpoint export

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4419]
Add the ability to specify (today is localhost) the IP address of a remote syslog server without having to modify the local syslog configuration file, an action that cannot be performed from he ntopng GUI

**Comment by cardigliano** [comment]
A syslog client should be implemented in ntopng, supporting UDP/TCP.

**Comment by cardigliano** [comment]
Added ability to specify host, port, protocol (udp/tcp)
