### ISSUE TITLE
help with "Category RRDs For Local Hosts and Networks"

### ISSUE THREAD

**Issue by dfariazo** [ntop/ntopng#442]
this options not work can you help me please

-k flashstart:<user>:<password>.

![ntop](https://cloud.githubusercontent.com/assets/17800992/13724149/9968317c-e849-11e5-9621-5ffdad54a426.jpg)

**Comment by lucaderi** [comment]
Please see https://github.com/ntop/ntopng/blob/dev/doc/README.flashstart
