### ISSUE TITLE
List hosts according to retransmissions

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4420]
In the host view, it is requested to add retransmissions as criteria to identify hosts with retransmission issues

![Screen Shot 2020-09-15 at 23 38 43](https://user-images.githubusercontent.com/4493366/93267949-b6b56c00-f7ac-11ea-8617-c91bd4c6fbff.png)

**Comment by simonemainardi** [comment]
![Uploading image.png…]()
