### ISSUE TITLE
Add DNS top queries

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4422]
In the DNS tab, similar to the HTTP tab, it would be nice to have a list of most requested domain names that have been queried. In order to keep the list compact, it is enough to omit the hostname, and just limit to the domain. Note that in order to  you need to use techniques such as https://publicsuffix.org/list/ to know what is the domain name and TLD portion

**Comment by MatteoBiscosi** [comment]
Added top domain names to the host/interface Top Sites page. Currently the full name is added and not only the domain.
