### ISSUE TITLE
Enhance DNS Data Exfiltration

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4426]
Add the ability to whitelist some domain names that are not considered by the DNS exfiltration plugin

**Comment by MatteoBiscosi** [comment]
Depends on #4942

**Comment by simonemainardi** [comment]
This is implemented. An `info=` field is supported as part of the user script configuration

![image](https://user-images.githubusercontent.com/3397663/109690041-35993800-7b86-11eb-92e2-a0fdbc2d3c12.png)
