### ISSUE TITLE
Add support for ECS

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4427]
Ad of today both ntopng (and nProbe) do not fully support ECS (Elastic Common Schema). Is is requested to add support for them. See https://www.elastic.co/guide/en/ecs/current/index.html for more information

**Comment by simonemainardi** [comment]
Please also update the documented format at the following page: https://www.ntop.org/guides/ntopng/alerts/available_recipients.html?highlight=elasticsearch#elasticsearch
