### ISSUE TITLE
Add the ability to edit/add/delete category lists

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4428]
![Screen Shot 2020-09-15 at 23 55 26](https://user-images.githubusercontent.com/4493366/93269283-f9784380-f7ae-11ea-9a87-14507d787ea5.png)

**Comment by gabryon99** [comment]
Add the ability to filter the enabled/disabled categories. And fix the modal layout style (i.e. modal title)

**Comment by lucaderi** [comment]
Add the ability via an extra lua file to extend the category list

**Comment by lucaderi** [comment]
Implemented by https://github.com/ntop/ntopng/commit/5e8769b1b5c55899c4ed03c7599f3cef7bb010e3
