### ISSUE TITLE
Enhance Recipients filtering

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4429]
it is requested to add the ability to select recipients based on the following criteria
- family of the script that triggered the alert (e.g. security, system,....)
- the severity of the alert to be delivered to the remote recipient

This allows recipients to be finely selected according to the alert that needs to be delivered

**Comment by lucaderi** [comment]
Furthermore in the current implementation
![Screenshot 2020-09-16 at 08 22 35](https://user-images.githubusercontent.com/4493366/93311438-4b988380-f806-11ea-8a0a-346969cbb3dc.png)

1. Add a better label for "Categories"
2. A use must select 1+ elements (zero is not allowed)
3. Consider collapsing some Categories together (e.g. Internals and others) or render them in a way that is easy to understand
4. Sort them alphabetically

**Comment by simonemainardi** [comment]
Implemented

![image](https://user-images.githubusercontent.com/3397663/93446949-1bb6b200-f8d2-11ea-931c-3153d15d0d6f.png)
