### ISSUE TITLE
Historical tab shows graph but no flow info in tabular data

### ISSUE THREAD

**Issue by djha983** [ntop/ntopng#443]
I have installed and running Ntopng 2.2.I have enabled storing data to mysql using -F option.Flow is being stored in mysql.But when i go to historical tab of interface,it shows me graph but there is not flow information in IPv4 tabular view.It says
![test](https://cloud.githubusercontent.com/assets/17782428/13728176/815dafa2-e935-11e5-8283-015f593cc78d.png)
 no result found.

**Comment by simonemainardi** [comment]
please, move the the latest dev version. We have made fixes and improvements.

**Comment by djha983** [comment]
I have installed 2.3 and now i can do analysis on historical data.I have enabled -F option to store flow data in mysql db as well as elastic search.data is stored in MySQL but not sent to elastic search.

Is it possible to store flow data in MySQL as well as elasticsearch same time?

**Comment by simonemainardi** [comment]
no, not at the same time. you need two ntopng instances.
