### ISSUE TITLE
Report license failure in the web GUI

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4431]
When ntopng does nop accept a license (or a license file is not present) an exact error is returned when executing "ntopng --version" that lists the exact license error

it is requested to report this information in the web GUI so that users can detect the root cause of these issues without using the shell

**Comment by cardigliano** [comment]
Added in https://github.com/ntop/ntopng/commit/e2f87a26b940242d1a2e4c6cc417f31086ee28d7
