### ISSUE TITLE
nDPI Risk Factor out of sync with ntopng 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4432]
Currently, ntopng doesn't handle all flow risks supported by ntopng: this needs to be addressed

**Comment by simonemainardi** [comment]
do you mean to extend the user script https://github.com/ntop/ntopng/tree/dev/scripts/plugins/alerts/security/flow_risks?

In that case, given that we only have 64 flow statuses available (bitmap limit) I think we should only create a subset of flow statuses and map there multiple risks.
