### ISSUE TITLE
Implement consistent data reset

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4433]
Similar to backup/restore https://github.com/ntop/ntopng/issues/4128 reset must be implemented in a consistent way on a separate page, by modifying the buttons already present to use it. Meaning that for entities such as
- SNMP
- Active Monitoring
- Recipients + Endpoints
....

Add the ability to
- delete all configured entries
- reset to factory default

Note that when resetting to factory default means that all stats have to be reset. For instance in endpoint/recipient the last usage time

**Comment by cardigliano** [comment]
Implemented

**Comment by gabryon99** [comment]
See the ticket: https://github.com/ntop/ntopng/issues/4128
