### ISSUE TITLE
Remove unnecessary space

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4435]
![Screenshot 2020-09-16 at 08 07 20](https://user-images.githubusercontent.com/4493366/93310713-6caca480-f805-11ea-87ed-2a6d7658092b.png)

**Comment by gabryon99** [comment]
Unnecessary space has been removed. See the commit: https://github.com/ntop/ntopng/commit/2331baa1fd64f7d36650ea1a57114490635a189a
