### ISSUE TITLE
Implement plugin unload

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4438]
It is requested to implement a hook that is triggered whenever a plugin is loaded (or reloaded). Something like hook.onload() that is partially existing in the current codebase

**Comment by simonemainardi** [comment]
Implemented. Now you can define:

- `script.onLoad` to have the method called when the plugin is loaded/unloaded, that is, when ntopng starts, when a license expires, or when you click reload plugins
- `script.setup` to have the method called before other user script hooks are executed, e.g., every time before the min.lua executes host hooks. This method was already existing.
