### ISSUE TITLE
Enhance recipient name

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4439]
![Screenshot 2020-09-16 at 08 36 41](https://user-images.githubusercontent.com/4493366/93311764-b1850b00-f806-11ea-92b5-b731d6b955fd.png)

The current list is styled poorly. Add at least the endpoint family and (better) some extra info. For instance for email it would be nice to see the recipient name

**Comment by gabryon99** [comment]
Right now we have improved the UI adding the recipient type on the new multi-selects.

<img width="1792" alt="Screenshot 2020-09-17 at 10 57 21" src="https://user-images.githubusercontent.com/14114916/93449053-91238200-f8d4-11ea-9fd6-5b0300e93b65.png">

It's requested to create a function to that returns the most important field of a recipient so we can add extra information, like the example below:

<img width="781" alt="Screenshot 2020-09-17 at 10 58 52" src="https://user-images.githubusercontent.com/14114916/93449223-c8922e80-f8d4-11ea-94a5-1746720cbbb3.png">

**Comment by gabryon99** [comment]
The details for the recipient have been added. See the referenced commit.
