### ISSUE TITLE
Alert style must be consistent

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4441]
![Screen_Shot_2020-09-16_at_17 13 13](https://user-images.githubusercontent.com/4493366/93357693-e6ae4f00-f840-11ea-8f22-d4495325ea53.png)
![Screen Shot 2020-09-16 at 17 14 57](https://user-images.githubusercontent.com/4493366/93357696-e7df7c00-f840-11ea-99bc-1e7ec498f3f5.png)

**Comment by gabryon99** [comment]
The alert style has been fixed. The commit is on the pro vcs.
