### ISSUE TITLE
After renewal ntopng thinks license is invalid

### ISSUE THREAD

**Issue by fsamareanu** [ntop/ntopng#4443]
During startup ntopng says this:

ep 17 11:00:04 gemma ntopng[30811]: 17/Sep/2020 11:00:04 [NtopPro.cpp:699] [LICENSE] System Id:#REDACTED
Sep 17 11:00:04 gemma ntopng[30811]: 17/Sep/2020 11:00:04 [NtopPro.cpp:700] [LICENSE] Edition:#011Enterprise M
Sep 17 11:00:04 gemma ntopng[30811]: 17/Sep/2020 11:00:04 [NtopPro.cpp:701] [LICENSE] License Type:#011Permanent License
Sep 17 11:00:04 gemma ntopng[30811]: 17/Sep/2020 11:00:04 [NtopPro.cpp:710] [LICENSE] License:#REDACTED
Sep 17 11:00:04 gemma ntopng[30811]: 17/Sep/2020 11:00:04 [NtopPro.cpp:715] [LICENSE] License Hash:#REDACTED
Sep 17 11:00:04 gemma ntopng[30811]: 17/Sep/2020 11:00:04 [NtopPro.cpp:725] [LICENSE] Maintenance:#011Until Thu Aug 26 13:01:03 2021 [343 days left]

However, from command line it says this:

root@gemma:~#  /usr/local/bin/ntopng --check-maintenance
Invalid license

**Comment by fsamareanu** [comment]
It seems that ntopng only checks if /etc/ntopng.license exists. In this case I believe it's stored in redis.

root@gemma:~# ntopng --version
v.4.1.200917    [Enterprise/Professional build]
GIT rev:        dev:8db941c31e7a4fbaaa73a3cf948c49fe8c80deff:20200917
Pro rev:        r3234
Built on:       Debian GNU/Linux 10 (buster)
System Id:      43047DC49206AB0A
Platform:       x86_64
Edition:        Enterprise L
License Type:   Time-Limited [Missing license file]
Validity:       Until Thu Sep 17 11:27:11 2020

After adding the license file:

root@gemma:~# ntopng --version
v.4.1.200917    [Enterprise/Professional build]
GIT rev:        dev:8db941c31e7a4fbaaa73a3cf948c49fe8c80deff:20200917
Pro rev:        r3234
Built on:       Debian GNU/Linux 10 (buster)
System Id:      43047DC49206AB0A
Platform:       x86_64
Edition:        Enterprise M
License Type:   Permanent
Maintenance:    Until Thu Aug 26 13:01:03 2021 [343 days left]

**Comment by simonemainardi** [comment]
License is correctly read both from /etc/ntopng.license and also from Redis if you do `ntopng --version` (tested with v.4.1.200918).

Reading license from Redis may fail if Redis need authentication (e.g., user/password) and you fail to provide them to the CLI.
