### ISSUE TITLE
Script Failure in AlertCheckLuaEngine

### ISSUE THREAD

**Issue by andiyk** [ntop/ntopng#4444]
17/Sep/2020 09:04:07 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:44: attempt to compare nil with number]
17/Sep/2020 09:04:07 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:44: attempt to compare nil with number]
17/Sep/2020 09:04:06 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:44: attempt to compare nil with number]
17/Sep/2020 09:04:06 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:44: attempt to compare nil with number]
17/Sep/2020 09:04:06 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:44: attempt to compare nil with number]
17/Sep/2020 09:04:05 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:44: attempt to compare nil with number]

v.4.1.200917    [Enterprise/Professional build]
GIT rev:        dev:8db941c31e7a4fbaaa73a3cf948c49fe8c80deff:20200917
Pro rev:        r3234
Built on:       Ubuntu 20.04.1 LTS
System Id:      *
Platform:       x86_64
Edition:        Professional
License Type:   Permanent
Maintenance:    Until Tue Nov 10 13:18:07 2020 [54 days left]

Configuration:
2 Interfaces (ZMQ from external nprobe Node + Syslog IF - Suricata on the same Node as nprobe)

**Comment by andiyk** [comment]
Perhaps its going in the same Direction:
Syslog Mesages from Suricata (5.0.0) don´t produce any Alert.

Example Message from Suricata:

Msg: Sep 17 09:58:55 [suricata_node] suricata[19863]: {"timestamp": "2020-09-17T09:58:55.031557+0200", "flow_id": 923592279978533, "in_iface": "br0", "event_type": "alert", "src_ip": "139.7.*", "src_port": 500, "dest_ip": "192.168.*", "dest_port": 500, "proto": "UDP", "tx_id": 4, "alert": {"action": "allowed", "gid": 1, "signature_id": 2224003, "rev": 1, "signature": "SURICATA IKEv2 weak cryptographic parameters (PRF)", "category": "Generic Protocol Command Decode", "severity": 3}, "app_proto": "ikev2", "flow": {"pkts_toserver": 3, "pkts_toclient": 3, "bytes_toserver": 1422, "bytes_toclient": 1374, "start": "2020-09-17T09:52:35.520741+0200"}}



Total Traffic | 3.8 GB [14,757,946 Pkts] | Dropped Packets | 0 Pkts

Suricata Statistics
Dropped Packets              1,490,968             (Flow Data dropped, because only Alerts wanted - Syslog IF Config)
Captured Packets              201,627,866
Signatures Failed              0
Signatures Loaded           21,084


the syslog IF is as Companion Device to the nprobe Device (tcp://ntopng:5556) activated and in the  nprobe Device its Dynamic Traffic Disaggregation to VlanId active.

**Comment by simonemainardi** [comment]
@please try and update to the latest 4.1 version; then go to settings->user scripts and hit reset configuration. Then report.

**Comment by andiyk** [comment]
it should be the newest Version : v.4.1.200917     Now i reset the Configuration under user scripts and restart ntopng, but same Result:


17/Sep/2020 10:33:06 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:44: attempt to compare nil with number]
17/Sep/2020 10:33:06 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:44: attempt to compare nil with number]
17/Sep/2020 10:33:05 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:44: attempt to compare nil with number]
17/Sep/2020 10:33:05 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:44: attempt to compare nil with number]
17/Sep/2020 10:33:05 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:44: attempt to compare nil with number]
17/Sep/2020 10:33:05 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:44: attempt to compare nil with number]
17/Sep/2020 10:32:06 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:44: attempt to compare nil with number]
17/Sep/2020 10:32:06 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:44: attempt to compare nil with number]
17/Sep/2020 10:32:05 [AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/interface.lua] [/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:44: attempt to compare nil with number]

**Comment by simonemainardi** [comment]
check settings->user script they try and disable host user scripts one by one and tell me if you find the issue is due to a particular script.

**Comment by andiyk** [comment]
I´m wondering. I try to disable the Suricata User script first, then restart ntopng, then reactivated the suricata Script and restart ntopng again. The Error in Log go away. But always no Alerts reported from Suricata again. 
Question: Wich Value was used from the suricata Logs to compare with the Threshold? I guess this Value is the reason, why it not show in the Interface. Could it be, or i´m going completely in the wrong Direction?

**Comment by andiyk** [comment]
and how can i change theThreshold for the Suricata Alerts? Only the "Host Log" Threshold i can change. For Suricata its grayed out in the "User Scripts/Syslog/Config Default".

**Comment by andiyk** [comment]
the Issue can closed. The Error is gone. The other Problem, that the Alerts from Suricata not shown: It should it be an new Thread/Issue.
