### ISSUE TITLE
Large scale network monitoring.

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#4445]
I want to use ntop software with other devices, such as tap, to monitor all devices in a large network, but I don't know how to deploy it. Can you provide an actual case.

**Comment by simonemainardi** [comment]
see:

- https://www.ntop.org/nprobe/network-monitoring-101-a-beginners-guide-to-understanding-ntop-tools/
- Use cases: https://www.ntop.org/guides/ntopng/using_with_other_tools/index.html

then come back with precise data and questions
