### ISSUE TITLE
Failure in SyslogLuaEngine

### ISSUE THREAD

**Issue by andiyk** [ntop/ntopng#4446]
17/Sep/2020 09:03:34 [SyslogLuaEngine.cpp:76] WARNING: Script failure [...lib/ntopng/plugins0/callbacks/system/syslog/suricata.lua:94: attempt to index a nil value (local 'event_http')]

v.4.1.200917 [Enterprise/Professional build]
GIT rev: dev:8db941c31e7a4fbaaa73a3cf948c49fe8c80deff:20200917
Pro rev: r3234
Built on: Ubuntu 20.04.1 LTS
System Id: *
Platform: x86_64
Edition: Professional
License Type: Permanent
Maintenance: Until Tue Nov 10 13:18:07 2020 [54 days left]

Configuration:
2 Interfaces (ZMQ from external nprobe Node + Syslog IF - Suricata on the same Node as nprobe)

**Comment by andiyk** [comment]
same root cause as in #4444. The Error goes away  - close Issue

**Comment by andiyk** [comment]
Bad News: The Error is back:
30min. since fresh start

Sep 17 11:33:05 nas ntopng: [SyslogLuaEngine.cpp:76] WARNING: Script failure [...lib/ntopng/plugins0/callbacks/system/syslog/suricata.lua:94: attempt to index a nil value (local 'event_http')]
Sep 17 11:33:05 nas ntopng[28879]: 17/Sep/2020 11:33:05 [SyslogLuaEngine.cpp:76] WARNING: Script failure [...lib/ntopng/plugins0/callbacks/system/syslog/suricata.lua:94: attempt to index a nil value (local 'event_http')]

**Comment by cardigliano** [comment]
@andiyk it seems ntopng is received logs from suricata with unexpected syntax, I added some check to avoid errors (next build), but I need to check why you have "malformed" logs. Are you able to provide some logs from suricata?

**Comment by andiyk** [comment]
sure, did you need a single line or more?

one of the Original Syslog Message on the Suricata host (lokal IP is Masked):

Sep 17 14:59:20 shaper suricata[19805]: {"timestamp": "2020-09-17T14:59:20.001942+0200", "flow_id": 1887001891253593, "in_iface": "br0", "event_type": "alert", "src_ip": "***********", "src_port": 41364, "dest_ip": "157.55.194.109", "dest_port": 443, "proto": "TCP", "tx_id": 0, "alert": {"action": "allowed", "gid": 1, "signature_id": 2028383, "rev": 2, "signature": "ET JA3 Hash - Possible Malware - Neutrino", "category": "Unknown Traffic", "severity": 3, "metadata": {"updated_at": ["2019_10_29"], "former_category": ["JA3"], "created_at": ["2019_09_10"]}}, "tls": {"sni": "otnprd11.samsungcloudsolution.net", "version": "UNDETERMINED", "ja3": {"hash": "fd6bbdf835788b3c7d33372127470a06", "string": "769,57-56-53-22-19-10-51-50-47-7-5-4-21-18-9-20-17-8-6-3-255,0-35,,"}, "ja3s": {}}, "app_proto": "tls", "flow": {"pkts_toserver": 3, "pkts_toclient": 2, "bytes_toserver": 320, "bytes_toclient": 120, "start": "2020-09-17T14:58:19.666969+0200"}}




the configuration of the suricata.yaml is default, only change the Output from file to syslog and now the last stable Version 5.0.3 (updated from 5.0.0 before but same log Output)

**Comment by cardigliano** [comment]
I need some log with "event_type": "http"

**Comment by andiyk** [comment]
sorry, next try:

Sep 17 15:14:22 shaper suricata[19805]: {"timestamp": "2020-09-17T15:14:22.430290+0200", "flow_id": 75535072723571, "in_iface": "br0", "event_type": "http", "src_ip": "192.168.**", "src_port": 55887, "dest_ip": "103.5.198.219", "dest_port": 80, "proto": "TCP", "tx_id": 0, "http": {"hostname": "webres5.pand.ctmail.com", "url": "/SpamResolverNG/SpamResolverNG.dll?DoNewRequest", "http_content_type": "text/html", "http_method": "POST", "protocol": "HTTP/1.0", "status": 200, "length": 15}}

**Comment by andiyk** [comment]
Problem solved. The Error goes away.
