### ISSUE TITLE
Error when activate "P2P Traffic Alert"

### ISSUE THREAD

**Issue by andiyk** [ntop/ntopng#4447]
when activate P2P Traffic Alert Trigger  (in my Example > 512000bytes / min) then ntopng gives me an Error:

[AlertCheckLuaEngine.cpp:168] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/host.lua] [attempt to index a number value]

**Comment by simonemainardi** [comment]
Thanks for reporting. Issue is fixes. New builds in progress. Wait one hour, update, and report.
