### ISSUE TITLE
The Alerts from Suricata not shown

### ISSUE THREAD

**Issue by andiyk** [ntop/ntopng#4448]
The Alerts from Suricata (v5.0.3 last stable) not shown in ntopng somewhere.  The Suricata Alerts was received over rsyslog from an remote Node over an dedicated LAN Connection . The Remote Node is running only nprobe+suricata. The Data from nprobe was received over ZMQ and the Data from Suricata over syslog to the ntopng Host. The Suricata (syslog IF) is configured as Companion Device to the ZMQ IF and the ZMQ IF is configured to Dynamic Disaggregation in to VLAN ID. The Duplicate Disaggregation is activated, to see the whole Traffic seperatly in the ZMQ Device. The Messages from Suricata looks good and was received from ntopng correctly, but no Alerts was attached somwhere.  It looks, the Alerts doesnt processed. The Builtin alerts (Threshold Cross/Flow Alerts) are shown correctly but no Suricata Alerts.

On the Interface Tab (syslog Device - Suricata) i see many captured Packets, but also many Dropped Packets:

Suricata Statistics:

Dropped Packets      1,482,792
Captured Packets      197,622,396
Signatures Failed      0
Signatures Loaded    21,113

I´m running on the last Night Build:

v.4.1.200918    [Enterprise/Professional build]
GIT rev:        dev:33f3f0990ebb3753066582f95f2ad2832d83b46e:20200918
Pro rev:        r3237
Built on:       Ubuntu 20.04.1 LTS
System Id:      *
Platform:       x86_64
Edition:        Professional
License Type:   Permanent
Maintenance:    Until Tue Nov 10 13:18:07 2020 [53 days left]

**Comment by andiyk** [comment]
![image](https://user-images.githubusercontent.com/23166953/93618064-17c08800-f9d7-11ea-913a-4cb4e4560c4c.png)

the Suricata Events was interpreted as Traffic, not as Events. In this Screenshot shows me >2GBit on a 1Gbit Interface

**Comment by cardigliano** [comment]
Please update to the next build as I pushed some safety check for the log parser. I ran the tests in our lab right now and it seems alerts are generated. Please check it with the new packages and let me know.

**Comment by andiyk** [comment]
same Problem:

the following Alert:

Sep 18 19:32:05 shaper suricata[9417]: {"timestamp": "2020-09-18T19:32:05.002464+0200", "flow_id": 1783381802551091, "in_iface": "enp2s0", "event_type": "alert", "src_ip": "52.216.30.4", "src_port": 80, "dest_ip": "192.168.55.70", "dest_port": 35352, "proto": "TCP", "metadata": {"flowbits": ["FB180732_0"], "flowints": {"http.anomaly.count": 1}}, "tx_id": 1, "alert": {"action": "allowed", "gid": 1, "signature_id": 2221010, "rev": 1, "signature": "SURICATA HTTP unable to match response to request", "category": "Generic Protocol Command Decode", "severity": 3}, "http": {"http_port": 0, "url": "/libhtp::request_uri_not_seen", "length": 417}, "app_proto": "http", "flow": {"pkts_toserver": 7, "pkts_toclient": 7, "bytes_toserver": 698, "bytes_toclient": 1267, "start": "2020-09-18T19:31:03.984883+0200"}}

produced one Flow in the Dashboard from the suricata(syslog) Interface:

![image](https://user-images.githubusercontent.com/23166953/93627934-06cb4300-f9e6-11ea-8014-dc84da48b3e4.png)


but no Alert somewhere

**Comment by andiyk** [comment]
![image](https://user-images.githubusercontent.com/23166953/93628407-cd470780-f9e6-11ea-9f73-8ec15b94c4f7.png)

**Comment by andiyk** [comment]
![image](https://user-images.githubusercontent.com/23166953/93628513-f798c500-f9e6-11ea-87e2-d999c92afb01.png)

**Comment by andiyk** [comment]
![image](https://user-images.githubusercontent.com/23166953/93628617-1eef9200-f9e7-11ea-9974-847b3fd8ed54.png)

**Comment by cardigliano** [comment]
@andiyk I pushed another fix for this today, please update to the next build and let me know. Thank you.

**Comment by andiyk** [comment]
no. the same Problem.
the following Alert from Suricata:

        Facility local5 (21), Severity error (3)
        Msg: Sep 22 07:53:01 shaper suricata[13803]: {"timestamp": "2020-09-22T07:53:01.158583+0200", "flow_id": 594374370838263, "in_iface": "enp2s0", "event_type": "alert", "src_ip": "192.168.xxx.xxx", "src_port": 60621, "dest_ip": "123.206.51.22", "dest_port": 9000, "proto": "TCP", "metadata": {"flowbits": ["FB180732_0"], "flowints": {"tls.anomaly.count": 4}}, "tls": {"version": "UNDETERMINED", "ja3": {}, "ja3s": {}}, "app_proto": "tls", "flow": {"pkts_toserver": 4, "pkts_toclient": 3, "bytes_toserver": 569, "bytes_toclient": 249, "start": "2020-09-22T07:53:00.444151+0200"}, "tx_id": 0, "alert": {"action": "allowed", "gid": 1, "signature_id": 2230010, "rev": 1, "signature": "SURICATA TLS invalid record/traffic", "category": "Generic Protocol Command Decode", "severity": 3}}

would parse correctly:

![image](https://user-images.githubusercontent.com/23166953/93848163-1b8b2d80-fca9-11ea-99e1-5f5d7a7d6fa3.png)

but not produce any alert

on the Info at this Flow, it shows me:

![image](https://user-images.githubusercontent.com/23166953/93848352-a2400a80-fca9-11ea-8804-350c28e4247c.png)

The Bulitin Alerts working correctly:

![image](https://user-images.githubusercontent.com/23166953/93848429-d4516c80-fca9-11ea-9a2f-1a37038e1b31.png)

**Comment by cardigliano** [comment]
@andiyk are you available for a joint debug session? (video call or ssh) Please write to cardigliano at ntop.org

**Comment by cardigliano** [comment]
Fixed in 7bda229e8f1ccda336fcbc377004837d92a1ba95
