### ISSUE TITLE
Implement additional plugin hooks

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4451]
Currently, plugins are not notified when
- plugin enabled
- plugin disabled
- plugin configuration is changed

It is requested to implement these three new hooks

**Comment by simonemainardi** [comment]
- Configuration must be passed as parameter of these hooks.
- In the configuration changed, pass the new configuration or both

**Comment by simonemainardi** [comment]
during startup, configuration should be accessed.

**Comment by simonemainardi** [comment]
Implemented method `script.onUpdateConfig(confid, config)`.

For an example see `https://github.com/ntop/ntopng/commit/304c5404f21f7a77a5e1bfe2ba1bc2e45cfdd126#diff-4439637b09f3bf416f195bf3faa4b975`.

Method `script.onUpdateConfig(confid, config)` is necessary as:
- Multiple configurations can be defined (e.g., default configuration applied to pool X, additional configuration applied to pool Y and Z, etc)
- For each configuration, a user script can be enabled for certain hooks (e.g., MINUTE threshold cross) and disabled for other hooks (e.g., 5MINUTE threshold cross).

For this reason, when there's a change in the configuration, `script.onUpdateConfig(confid, config)`  is called with the configuration id which as changed, and with the newly changed configuration. When the plugins are reloaded or ntopng is restarted, `script.onUpdateConfig(confid, config)`  is called on all the existing configurations. 

Example of changing "host" Default configuration for user script `host_score`:

```
 string on update:host_score confid: 0
 table
min table
min.script_conf table
min.script_conf.operator string gt
min.script_conf.threshold number 1001
min.enabled boolean true
```

Example of changing "host" configuration 1 for user script `host_score`:

```
 string on update:host_score confid: 1
 table
min table
min.enabled boolean false
min.script_conf table
min.script_conf.threshold number 1001
min.script_conf.operator string gt
```

Example of changing "flow" default configuration for user script `blacklisted`:

```
 string on update:blacklisted confid: 0
 table
all table
all.enabled boolean false
all.script_conf table
```

**Comment by lucaderi** [comment]
Verified: working as expected.
