### ISSUE TITLE
Error when compiling last version

### ISSUE THREAD

**Issue by jppo** [ntop/ntopng#4452]
Hello,

I want to compile the latest version from githud on my Sebian 10 system and I get an error : 
----------------------------------------------------------------------------------------------------------------------------------------------
src/NetworkInterface.cpp: In member function ‘virtual void NetworkInterface::lua(lua_State*)’:
src/NetworkInterface.cpp:5166:54: error: ‘sub_interfaces’ was not declared in this scope
   lua_push_bool_table_entry(vm, "hasSubInterfaces", (sub_interfaces && sub_interfaces->getNumSubInterfaces()) || (flowHashingMode != flowhashing_none));
                                                      ^~~~~~~~~~~~~~
src/NetworkInterface.cpp:5166:54: note: suggested alternative: ‘isSubInterface’
   lua_push_bool_table_entry(vm, "hasSubInterfaces", (sub_interfaces && sub_interfaces->getNumSubInterfaces()) || (flowHashingMode != flowhashing_none));
                                                      ^~~~~~~~~~~~~~
                                                      isSubInterface
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-address-of-packed-member’
make: *** [Makefile:146: src/NetworkInterface.o] Error 1
-----------------------------------------------------------------------------------------------------------------------
I hope that the messages are OK for you. If you miss something feel free to ask ...

Regards

JP Pozzi

**Comment by cardigliano** [comment]
Fixed bd76fad52afdaa1ad1f57ab96b250fefb6f954a6
