### ISSUE TITLE
Need to improve script.onUpdateConfig implementation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4453]
This hook https://github.com/ntop/ntopng/commit/304c5404f21f7a77a5e1bfe2ba1bc2e45cfdd126 lacks a parameter that specifies the reason why this hook is called that can be
- plugin enable
- plugin value change
- plugin disable

Note that this hook is also called for plugin that are disabled and this is an invalid behaviour that must be addressed.

This ticket and #4454 are cross-related

**Comment by simonemainardi** [comment]
A user script can have some hooks enabled, and some other hooks disabled. `script.onUpdateConfig` receives the configuration as input which says which one of them are enabled/disabled, and individual configurations.

For, example, given the threshold cross user script:
- minute threshold can be enabled at 1000 Bps
- 5 minute threshold can be disabled

Enabled/disabled can be read from the configuration passed to  `script.onUpdateConfig`. Look at examples in https://github.com/ntop/ntopng/issues/4451#issuecomment-695776186: to know which hooks are disabled and which one are enabled you have boolean `enabled` in the config.

This is for the same user script. Plugins cannot be enabled/disabled. Given this, please comment on the behavior you want to be implemented.

**Comment by lucaderi** [comment]
Verified: working as expected.
