### ISSUE TITLE
Hook script.onLoad() is called for both enabled and disabled plugins

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4455]
The above hook is called for both enabled (expected) and disabled (unexpected) plugins. While this practice is not pleasant, it is acceptable is a paramerer is passed to the hook that allows the hook to execute actions based on the fact if the plugin is enabled or disabled.

Hence
- either you call the onLoad() hook only for enabled plugins
- or add a parameter to disambiguate this behaviour

**Comment by simonemainardi** [comment]
For user scripts - user scripts, not other plugin components - we can replace the onLoad method with the newly implemented `script.onUpdateConfig`. This is called when ntopng starts or when the configuration of a user script changes and it has the configuration passed as input. From the configuration you can read which hooks are enableld/disabled, and their configuration. Please comment.

**Comment by lucaderi** [comment]
Verified: working as expected.
