### ISSUE TITLE
Missing script.onResetConfig() handler

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4457]
Currently, there is no handler called when the GUI reset button is called (red button)

![Screen Shot 2020-09-20 at 19 27 59](https://user-images.githubusercontent.com/4493366/93744129-9b55c100-fbf1-11ea-85dd-5d659728fb4c.png)
 
It is requested to implement such a handler that is called when the reset button is called. Otherwise, modify the behavior of script.onUpdateConfig() and pass on a specific parameter the fact that we're resetting the configuration. In fact in some plugins the configuration needs to be propagated to the backend and it is not a simple change in configuration, hence it is required to know if we're setting a value or not.

Please note that in case a reset handler is implemented, such handler has to be called when effective (i.e. when a value is saved) as even if the reset button is called, the user could later click on the cancel button and thus invalidate the reset,

**Comment by simonemainardi** [comment]
I think the best way to implement this behavior is to make the "Reset Default" button open a modal, asking the user to reset the script to the default value. Then, if the user clicks on yes, the configuration is reset and the hook called.

With the current implementation, the described behavior cannot be implemented as
1. Reset Default populate the UI with default values
2. Then the user can change default values to other values

**Comment by lucaderi** [comment]
I don't think it's a good idea to implement a modal on top of a modal. The point here is that the default value needs to be stored somewhere and not always is a static value as the one you put in the plugin code.
Anyway if too complex just leave it as is, but change "Reset Default" to "Reset to Factory Values" or something like that as this is the correct label
