### ISSUE TITLE
no results

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#4462]
Why there is no resualts ?

![image](https://user-images.githubusercontent.com/44804599/93847914-df70c080-fcda-11ea-8cd9-003160c0f40b.png)
![image](https://user-images.githubusercontent.com/44804599/93849496-da157500-fcde-11ea-9a12-75b45706f5fa.png)

**Comment by simonemainardi** [comment]
Selected timeframes don't match. Align them.

**Comment by MaoPann** [comment]
I don't understand what you mean.
