### ISSUE TITLE
Modify disabled script behaviour

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4464]
![Screen Shot 2020-09-22 at 10 01 58](https://user-images.githubusercontent.com/4493366/93857319-b3454780-fcba-11ea-8d04-21b758bbba37.png)

In disabled scripts, the edit button should not be visualized as disabled scripts configuration should not be changed. Instead the toggle enable/disable must be always enabled and it should redirect to the current "edit" button so people can toggle the enable button (even though all the other fields should be disabled as people should not change any value)

Note that this is a quick workaround and a clean solution must be identified post 4.2 release.

Please disable the "show script" gray button for disabled plugins as when you have a disabled plugin the only thing you should do is to enable the plugin. Any other change in the disabled button pane should not be allowed.

**Comment by gabryon99** [comment]
Currently, we have decided to shows all the three buttons in the action column.
When a script is disabled then the source code button and the `edit` button are disabled, only the `toggle on` button is enabled. 

**Disabled Section:**
For the scripts who don't have parameters to configure then clicking on the `toggle on` button it enables the script normally, instead, for those who have parameters to configure then a modal will open asking for the new params.
