### ISSUE TITLE
Unable to show CPU load - JS error

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4466]
![image](https://user-images.githubusercontent.com/3397663/93861991-b2fc7a80-fcc1-11ea-94ad-478a066ac2c2.png)

**Comment by gabryon99** [comment]
The problem has been fixed. Before the migration to NtopUtils has been made the Object containing the *formatter* functions was the global `window` object, the migration caused the errors showed above in the screenshot.
