### ISSUE TITLE
Invalid button state in user scripts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4467]
After a full ntopng reset (stop ntopng; rm /var/lib/ntopng/runtimeprefs.json ; redis-cli flushall; start ntopng again) I have:

![Screen Shot 2020-09-22 at 11 05 10](https://user-images.githubusercontent.com/4493366/93863236-9103f780-fcc3-11ea-86b6-e591b3afa8ee.png)

Bugs
- Rename is enabled for the default configuration: this happens for all tabs
![Screen Shot 2020-09-22 at 11 05 26](https://user-images.githubusercontent.com/4493366/93863384-b85ac480-fcc3-11ea-9cfc-90e0e0c6979e.png)
- Clone is disabled for Flows making impossible to create new configurations

**Comment by gabryon99** [comment]
It seems that inside `scripts_config.lua` the `default_config_only` flag is set to false because `user_scripts.getScriptType(subdir).default_config_only` where `subdir=flows` returns nil. 

See the code:
```
local default_config_only = user_scripts.getScriptType(subdir).default_config_only

if default_config_only == nil then
    default_config_only = false
end
```

**Comment by gabryon99** [comment]
The bug for the renaming default config has been solved. Now on the tabs who have only the default config, only the edit button is shown.

**Comment by simonemainardi** [comment]
This is inconsistent behavior.

As you've hidden the 'rename' for the default config in flows Default config

![image](https://user-images.githubusercontent.com/3397663/94114976-5fb53400-fe49-11ea-829d-20178985cd78.png)

you must hide it everywhere for every Default config. For example, for hosts, the button is just disabled

![image](https://user-images.githubusercontent.com/3397663/94115065-81162000-fe49-11ea-89e9-15548462df81.png)

**Comment by gabryon99** [comment]
Now the buttons are shown in the tabs where there is only the default configuration only because if we hide the button we get the Christmas tree button.
