### ISSUE TITLE
Clicking restore host causes ntopng to crash

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4468]
When trying to restore an host from the search

![image](https://user-images.githubusercontent.com/3397663/93864025-944bb300-fcc4-11ea-8668-7ec199cabf4e.png)

ntopng hangs for a while with "restoring host..." and then eventually crashes

**Comment by lucaderi** [comment]
Fixed by https://github.com/ntop/ntopng/commit/255496dcacbfea79798200a2e62e58ee777942cc
