### ISSUE TITLE
Local hosts

### ISSUE THREAD

**Issue by maskcv** [ntop/ntopng#447]
Hi Luca
I need help. I cannot put my local networks working

Please see my main files

regards

```
I    ntopng.conf                                                                               Row 6    Col 1    8:52  Ctrl-K H for help
```

-G=/var/tmp/ntopng.pid
-i=tcp://127.0.0.1:5556
-w=3000
-m=41.223.152.0/22,41.77.128.0/21,195.140.248.0/22,165.90.64.0/19
-d=/var/tmp/ntopng

[4]+  Exit 255                ntopng -i tcp://127.0.0.1:5556 -d /var/tmp -w 3000 -v >> /dev/null
root@ntop16:/etc/ntopng# ntopng -i tcp://127.0.0.1:5556 -d /var/tmp -w 3000 -v >> /dev/null &
[4] 8600
root@ntop16:/etc/ntopng# nprobe -i eth0 --collector-port 6343 --zmq tcp://127.0.0.1:5556 >> /dev/null &
[5] 8611
[4]   Exit 255                ntopng -i tcp://127.0.0.1:5556 -d /var/tmp -w 3000 -v >> /dev/null

**Comment by simonemainardi** [comment]
Please,  do not redirect the output to dev/null: see the console logs and report any error.

Also note that according to the ntopng commands shown, the configuration file ntopng.conf is not used. if you want to use it you have to launch

./ntopng /path/to/the/ntopng.conf

best,
simone

**Comment by maskcv** [comment]
Hi Simone

Can you please tell me how to configure properly my networks?

Thank you

**Comment by simonemainardi** [comment]
```
root@ntop16:/etc/ntopng# ntopng /path/to/ntopng.conf
```

where `/path/to/ntopng.conf` is the file system path to the config file you have shown above, e.g., `/etc/ntopng/ntopng.conf`
