### ISSUE TITLE
Outdated DHCP Alert Messages

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4470]
![Screen Shot 2020-09-22 at 11 57 40](https://user-images.githubusercontent.com/4493366/93868525-d7108980-fcca-11ea-9d42-5e2055776d34.png)
![Screen Shot 2020-09-22 at 11 57 28](https://user-images.githubusercontent.com/4493366/93868526-d7a92000-fcca-11ea-8dd7-ca5ea95a27e8.png)

The above messages have not yet been migrated to the new style

![image](https://user-images.githubusercontent.com/4493366/93868616-f90a0c00-fcca-11ea-8f5a-612dce8cebf2.png)

It is required
- to migrate such alerts
- walk through the ntopng code and see if there are messages to be migrated

**Comment by gabryon99** [comment]
The alerts have been migrated to the new notification system
