### ISSUE TITLE
Unify Tab Styles

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4471]
Correct Tab style

![Screen Shot 2020-09-22 at 12 01 19](https://user-images.githubusercontent.com/4493366/93868872-5dc56680-fccb-11ea-8b7c-1f41d5710a99.png)

invalid Tab style (hard to distinguish a button with the same color with a tab) 
![Screen Shot 2020-09-22 at 12 00 53](https://user-images.githubusercontent.com/4493366/93868875-5e5dfd00-fccb-11ea-8243-6e28c3915d14.png)

The whole ntopng UI must me uniform in terms of tab style.

**Comment by gabryon99** [comment]
<img width="1792" alt="Screenshot 2020-09-23 at 21 52 01" src="https://user-images.githubusercontent.com/14114916/94062474-04525a00-fde7-11ea-939d-0b4451a60b1e.png">

Now the tabs on the page have the same look. See the referenced commit in the ticket

**Comment by simonemainardi** [comment]
Tabs still unchanged (and broken) in

![image](https://user-images.githubusercontent.com/3397663/94114599-dbfb4780-fe48-11ea-9840-0d56c9f83587.png)


![image](https://user-images.githubusercontent.com/3397663/94114700-fdf4ca00-fe48-11ea-9cd2-9e2926e1245f.png)
