### ISSUE TITLE
Christmas Tree Button Layout

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4473]
This is a regression that has been broken in one of the latest commits.
![Screen_Shot_2020-09-22_at_12_10_21](https://user-images.githubusercontent.com/4493366/93870034-ef81a380-fccc-11ea-896e-27e46150e6d4.png)

The two vertical lines MUST be aligned as it sued to be until some days ago

**Comment by simonemainardi** [comment]
Christmas tree also in category lists 

![image](https://user-images.githubusercontent.com/3397663/93885602-9e7da980-fce4-11ea-8a7e-c91207778847.png)


Plus, the button upload is wrong as the action is a refresh.

**Comment by gabryon99** [comment]
The buttons layout has been fixed within the referenced commits.
