### ISSUE TITLE
Implement OO import/export and REST API

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4475]
A new OO module for import export must be implemented: `modules/import_export/import_export.lua`.

Multiple items must be contained in the module, e.g., `modules/import_export/items/{snmp, pools, notifications, etc}`, each one implementing `:import()` and `:export()` functions, producing and reading a JSON, respectively.

- SNMP devices, active monitoring, user scripts are exported as-is without dependencies.
- Pools carry with them endpoints+recipients+user-scripts+active monitoring+SNMP devices+everything else which doesn't break pool configurations

Implementation will be then made available via REST and used by issue https://github.com/ntop/ntopng/issues/4128.

**Comment by cardigliano** [comment]
Implemented
