### ISSUE TITLE
Button style must be consistent 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4476]
SNMP/Pools
![Screen Shot 2020-09-22 at 17 08 47](https://user-images.githubusercontent.com/4493366/93900984-51a2ce80-fcf6-11ea-9027-f7ccc250cc23.png)

Active Monitoring
![Screen Shot 2020-09-22 at 17 08 41](https://user-images.githubusercontent.com/4493366/93900991-549dbf00-fcf6-11ea-8334-892c708e7946.png)

**Comment by gabryon99** [comment]
The button style has been uniformed across the pages. Now we only need to implement the Manage Config page to bound a link to the button Import/Export Configuration.

**Comment by simonemainardi** [comment]
The pages indicated have still very same look as already highlighted. Nothing has changed.

![image](https://user-images.githubusercontent.com/3397663/94114321-7c04a100-fe48-11ea-987f-12b66048cfb4.png)

![image](https://user-images.githubusercontent.com/3397663/94114340-832baf00-fe48-11ea-8856-cb574a92f176.png)

**Comment by simonemainardi** [comment]
Fixed. Issue was just due to browser caching.
