### ISSUE TITLE
.fail() arrow functions have wrong parameters

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4478]
All `.fail` arrow functions in `cripts-list-utils.js` (need to check other files as well) have a wrong set of parameters:

```
({ status, statusText })
```

should be

```
( jqXHR, textStatus, errorThrown ) 
```

It is requested to fix all this calls.

**Comment by gabryon99** [comment]
The set of parameters is right. The problem was caused by an exception thrown when a user script didn't have a template to use. Now thanks to the edits done for the ticket #4479 this doesn't happen anymore.
