### ISSUE TITLE
Unable to toggle on user scripts without templates

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4479]
User scripts without a template cause an exception to be thrown

![image](https://user-images.githubusercontent.com/3397663/93914879-72275480-fd07-11ea-93a0-772c8786c78b.png)

An consequently it is impossible to enable them with the following

![image](https://user-images.githubusercontent.com/3397663/93914936-8ff4b980-fd07-11ea-8841-6cadea712f1c.png)

**Comment by gabryon99** [comment]
Commit reference: https://github.com/ntop/ntopng/commit/fc70eaa37799ae064a6a93414bc9d7e68d94af95

**Comment by lucaderi** [comment]
In order to reproduce you need to follow these steps
- disable the flow risk plugin
- enable the flow risk plugin and the problem will show up

**Comment by simonemainardi** [comment]
@gabryon99 please explain how you've handled missing templates. What happens when now when the template doesn't exist? Is the exception still thrown?

**Comment by gabryon99** [comment]
Now when there isn't a template for a User Script an alert message will be shown inside the edit modal. The edit modal of a plugin that doesn't have a template it has only the 'Cancel' button.
