### ISSUE TITLE
http://packages.ntop.org/apt/ fails for Debian/sid

### ISSUE THREAD

**Issue by grinapo** [ntop/ntopng#448]
apt-ntop.deb seems to try to generate repo url by the release, but it will fail for everything which is not wheezy or jessie (obviously). Either you generate symlinks for others (like my sid) or fixup the script. 
Unfortunately neither would really help us since jessie depends on   libhiredis0.10  which is not in sid anymore, and   libhiredis0.13   have a different name, so recompilation is necessary.

**Comment by lucaderi** [comment]
@grinapo Please attach log of the issue

**Comment by grinapo** [comment]
Um, there is no log, I try to describe the steps.
1) install apt-ntop.deb on a Debian/sid
2) check the generated /etc/apt/sources.list.d/ntopng.list
3) it will contain 'sid' as a distribution (which is also the directory name in repo)
4) repo only contains 'jessie' and 'wheezy' directories, not 'sid'
5) thus the update, install and everything else fails with 404

+1) replacing 'sid' with 'jessie' manually will fix the ap repository url and successfully find the files in the repo and will inform you that ntopng is not installable because it depends on  libhiredis0.10 which is not in sid anymore, since it's been replaced by  libhiredis0.13. So, technically fixing the apt-ntop.deb alone would not make ntopng installable under sid.

**Comment by lucaderi** [comment]
The problem is that we do not support anything but Debian 8, sorry. If you want to send me a pull request for packages build https://github.com/ntop/ntopng/tree/dev/packages feel free to do that, but we have no time to support anything but Debian 8. If you want you can compile from source.
