### ISSUE TITLE
Timeseries infixdb setup failed.

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#4480]
When I set influxdb and saved it, the settings seem to fail. After setting, it is still RRD.
![image](https://user-images.githubusercontent.com/44804599/93955175-be16df80-fd81-11ea-95c2-ff6d0a8c791e.png)

**Comment by MaoPann** [comment]
How to check whether infixdb is set successfully and the storage space occupied by infixdb

**Comment by lucaderi** [comment]
You can check it on the preferences page. The RRD storage is used because you have old RRD files. Does this help?

**Comment by MaoPann** [comment]
of no avail. I have delete all rrd files in /var/lib/ntopng. what should I do?I set influxdb, click Save settings, it will automatically jump to RRD.I'm in a hurry. How to solve it,

**Comment by simonemainardi** [comment]
What does the settings page say after you set influx? A message OK/ERROR should appear at the top of the settings page.

**Comment by MaoPann** [comment]
nothing  at the top of the settings page.


![image](https://user-images.githubusercontent.com/44804599/94046354-28239900-fe03-11ea-8855-8620631c2f6b.png)

**Comment by simonemainardi** [comment]
Click InfluxDB, set the params, Click save, and look at the top of the page. A message will appear. Either Success or an Error will tell you what is happening.

**Comment by MaoPann** [comment]
Yes,I have done,the results as follow.
![image](https://user-images.githubusercontent.com/44804599/94124784-07515700-fe88-11ea-92a7-7ec66cc3c13e.png)

**Comment by simonemainardi** [comment]
you should either see

![image](https://user-images.githubusercontent.com/3397663/94140141-1a096300-fe6b-11ea-816f-52a746f1d0cf.png)


or an error with the motivation:

![image](https://user-images.githubusercontent.com/3397663/94140181-22619e00-fe6b-11ea-8260-77a65e671ec5.png)

**Comment by MaoPann** [comment]
this is my operating the recording screen,You can see there's no hint.
![influxdb](https://user-images.githubusercontent.com/44804599/94224513-28b45080-ff25-11ea-9a03-e0873eeb48c8.gif)

**Comment by MaoPann** [comment]
hello,

**Comment by simonemainardi** [comment]
Do you have browser extensions or similar? I've just tried to reproduce on stable but it works OK.

![image](https://user-images.githubusercontent.com/3397663/94426104-5bf91880-018d-11eb-8f39-778ece8eac81.png)

Right-click, then inspect element, open the network tab and see if a POST request is emitted when you click SAVE. Also try and disable all browser extensions.

**Comment by MaoPann** [comment]
there are a post.but set failed.
![image](https://user-images.githubusercontent.com/44804599/94500253-6f5dbf80-0231-11eb-9c3c-9dfba9dd2b2e.png)

**Comment by MaoPann** [comment]
I need a available way to comfirm the setting is completed.Where is the influxDB data store.May i check the file.

**Comment by simonemainardi** [comment]
Can you provide remote access so I can check?

**Comment by MaoPann** [comment]
OK，Use the ntopng n2n remote assistance function? Or use remote control software?You can choose a time, but be aware of our time difference, I'm in China.

**Comment by simonemainardi** [comment]
drop me an email at mainardi ntop ord

**Comment by MaoPann** [comment]
I'm sorry, I don't know what you mean.

**Comment by simonemainardi** [comment]
i mean that you should write me an email so we can exchange connection details
