### ISSUE TITLE
No not show ZERO in column

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4481]
As discussed:

Zero values are never reported by ntopng, remove them

![image](https://user-images.githubusercontent.com/3397663/94003500-95034880-fd9b-11ea-8116-f64e56952704.png)

Also remove column Number of Usage as only Time Since Last Use is desired (Number of Usage can become a huge number, meaningless for the end user)

**Comment by gabryon99** [comment]
Column removed as requested.
