### ISSUE TITLE
"Top application Protocols" on Dashboard is empty

### ISSUE THREAD

**Issue by Kptainflintt** [ntop/ntopng#4485]
Hello,

I try to make working my installation but on dashboard, "Top Application" and "Top hosts" are not functionning, circle is grayed out, no error message or "No data" message.

At the other side, when I go to "Interface section", I can see used application charts...

v.4.1.200923    [Enterprise/Professional build]
GIT rev:        dev:c7b7f2ee1b65701bbd22842a8fe90c13b2798e66:20200923
Pro rev:        r3247
Built on:       Debian GNU/Linux 10 (buster)
System Id:      3BE6750676076A80
Platform:       x86_64
Edition:        Enterprise L
License Type:   Time-Limited [Empty license file]
Validity:       Until Thu Sep 24 09:27:47 2020

**Comment by simonemainardi** [comment]
please, report the ntopng configuration used, and a screenshot of the ntopng header bar.

**Comment by jonaskluger** [comment]
I tried to query data today via the flows REST API and get to an error page.
This worked fine just yesterday. We are using the daily build version.

Could this be related to this issue?

![image](https://user-images.githubusercontent.com/39433953/94123150-b58ed980-fe53-11ea-8ab6-006b4dc00152.png)

**Comment by simonemainardi** [comment]
please, show the endpoint you've contacted

**Comment by jonaskluger** [comment]
http://my-ntopng-url:3000/lua/rest/v1/get/flow/active.lua?ifid=2&currentPage=1&perPage=2000&sortColumn=column_bytes&sortOrder=asc

ntopng Enterprise M v.4.1.200924

**Comment by simonemainardi** [comment]
@jonaskluger please update as the issue you've pointed out has been solved.

**Comment by simonemainardi** [comment]
@Kptainflintt please reopen with the requested information - if still necessary.
