### ISSUE TITLE
License mismatch error

### ISSUE THREAD

**Issue by clebig** [ntop/ntopng#4486]
Hi,

I have tried to get my ntopng 4.0 activated with a license key for Enterprise L x86_64 but it doesn't work. I get a message saying "License mismatch error" when I run ntopng --version.

I have sent an email to Maria who checked everything, she confirmed the "system" tells  "it's a permanent license". She invited me to open a ticket here.

Below the ntopng --version output. For obvious reasons, I replaced some characters by XXX.

root@gateway:# ntopng --version
v.4.0.200923    [Enterprise/Professional build]
GIT rev:        4.0-stable:17bc5c0b2e233be3351888435b2e598dd4a87296:20200923
Pro rev:        r2816
Built on:       Debian GNU/Linux 10 (buster)
System Id:      1286FDACXXXXXXXX
Platform:       x86_64
Edition:        Enterprise L
License Type:   Time-Limited [License mismatch error]
Validity:       Until Wed Sep 23 18:01:36 2020
License:        RhopRJn1XrEpoX85QMMdIVXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXsXIaGC8JfLPPCg==
License Hash:   CB9AB6594941E18751B6F5A7E1DFCB2D1632387246891F734F

**Comment by lucaderi** [comment]
I have checked your orderId and you have generated by mistake the license for your orderId and not for your systemId. I have invalidated it; please generate it again and it will work.
