### ISSUE TITLE
Rework ELK EndPoint/Recipient

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4487]
In ntopng 4.1.x endpoint/recipients are used to deliver events to consumers. Alerts fall into this category. Currently, persistent alert storage is implemented by the SQLite component that is good for small sites but not for large ones. As of today ntopng has the ability to store alerts in ELK but this is hidden in the interface, mixed with -F and preferences.

This ticket requests to create an ELK endpoint for delivering events (i.e. in this ticket we are NOT talking about flows) via a recipient, so that ELK can be handled as any other recipient.

**Comment by simonemainardi** [comment]
ES endpoint recipient reworked. Documentation updated accordingly. Now they are completely independent from any configuration specified with -F, and are handled as any other endpoint/recipient.

![image](https://user-images.githubusercontent.com/3397663/94439518-d0898280-01a0-11eb-851d-8c61c8869e1a.png)

![image](https://user-images.githubusercontent.com/3397663/94439580-e39c5280-01a0-11eb-8bcb-2dbf9d89b1b9.png)
