### ISSUE TITLE
Suricata integration - Stop output to console

### ISSUE THREAD

**Issue by JeWe-HS** [ntop/ntopng#4488]
Hi, 

i followed these instructions to integrate Suricata with NTOPNG:
https://www.ntop.org/guides/ntopng/advanced_features/suricata.html

Now I got two problems:

- All Suricata output goes to console, so I can't use it anymore. Suricata is already started with option -D. In Suricata config I set this option:
outputs:
  - console:
      enabled: no

- Where can I see the Suricata data in NTOPNG?

Regards

**Comment by cardigliano** [comment]
@JeWe-HS please note that it could be syslog itself is logging on the console (look for ForwardToWall=no in https://www.ntop.org/guides/ntopng/advanced_features/syslog.html#syslog-relay-configuration-optional), ask to the suricata support for suppressing the console output if it's suricata itself.
If you follow the guide, you should be able to see traffic processed by suricata (check the Flows menu) and alerts (check the Alerts menu)
