### ISSUE TITLE
Limit Edit Privileges to Non-Admin Users

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4489]
Non-Admin users shouldn't be able to edit/view
- pools
- notifications
- SNMP
- active monitoring
- settings
- developer
- recipients/endpoints

**Comment by simonemainardi** [comment]
implement as:
- add a user bitmap of DOs and DONTs.
- bitmap only applies to unprivileged users

For the time being, a new lua module should be implemented which returns, given the user, the actions he/she can do or not.

This must be true both for the menu entries (to hide them) and for individual pages.

**Comment by simonemainardi** [comment]
Implemented as requested. Now there's a bitmap of capabilities (currently is all 1s for admins and all 0s for non-admins). Code has been changed anywhere to enforce such privileges. The UI will need to be extended to change values of such bitmap.
