### ISSUE TITLE
Active monitoring template must stay in the plugin templates folder

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4494]
Commit https://github.com/ntop/ntopng/commit/7fab77bf4a6d4c128b4f9d5a7cdf9416afa3cffa introduced a template which is not placed in the right place. Template must stay under `scripts/plugins/monitors/network/active_monitoring/templates/`. Please, move it.

**Comment by gabryon99** [comment]
The file has been moved into the folder wrote on the ticket. See the referenced commit.
