### ISSUE TITLE
top L7 contact no results found. 

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#4496]
I turned on ntopng yesterday and then turned it off. Today, I reopened ntopng. I went back to yesterday's flows data and found that there was always no result.
![image](https://user-images.githubusercontent.com/44804599/94505852-940c6400-023e-11eb-934d-8a4d2538e718.png)

**Comment by simonemainardi** [comment]
Check the ntopng log and report it here.

**Comment by simonemainardi** [comment]
need to upgrade to 4.1 first

**Comment by MaoPann** [comment]
I'm using 18.04 apt-ntop-stable. no 4.1 version

**Comment by simonemainardi** [comment]
You need to upgrade to version 4.1 as nIndex contains fixes there.
