### ISSUE TITLE
Raw flows table is not responsive

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4497]
I'm unable to scroll it to access the rightmost column

![image](https://user-images.githubusercontent.com/3397663/94660584-2297e880-0306-11eb-8d4f-3f523bf01c21.png)

Also check other tables.

**Comment by cardigliano** [comment]
The same applies to the tables in the flows Explorer that you can access from the menu on the table top-right

**Comment by gabryon99** [comment]
I've added a responsive class for the table. Check the pro repository, please.
