### ISSUE TITLE
Webhook Discord not working

### ISSUE THREAD

**Issue by Zathiel** [ntop/ntopng#4499]
Hello Team,

Webhook Notification for discord is not working on my side

I field all the information and send a test notif

Notification is sent but is not received on discord side.

Regards

**Comment by Zathiel** [comment]
http://prntscr.com/uqirpn

**Comment by lucaderi** [comment]
You need to upgrade to the latest 4.1 release

**Comment by Zathiel** [comment]
Even in 4.1 release version still not working @lucaderi

**Comment by simonemainardi** [comment]
You're confusing web hook with discord. Use endpoint "Discord" for discord notifications.

**Comment by Zathiel** [comment]
@simonemainardi @lucaderi  I just update to 4.1.201011 (11750) - Community Edition

please guide me to create endpoint for discord

**Comment by simonemainardi** [comment]
go to discord, server settings, integrations, web hook and copy the URL (copy webhook URL)

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/3397663/95673319-af189580-0ba7-11eb-85d9-168773446f31.png">

<img width="724" alt="image" src="https://user-images.githubusercontent.com/3397663/95673323-b63fa380-0ba7-11eb-8b8a-d1df72cd1e74.png">

Then go to ntopng, system interface Notifications->Endpoints and create a "Discord" endpoint: PASTE the copied URL here.
Finally, go to Notifications->Recipients, and create a recipient bound to the created "Discord" endpoint. Click test, and it will work.
