### ISSUE TITLE
error while loading shared libraries: libzmq.so.4

### ISSUE THREAD

**Issue by rewwade** [ntop/ntopng#450]
I've just updated ntopng on my Centos 6.7 box and it will not start because of the following error:

> Starting ntopng: /usr/bin/ntopng: error while loading shared libraries: libzmq.so.4: cannot open shared object file: No such file or directory

Issue #137 provides some nebulous information relating to zmq on the ntop yum repos, but I can't find any concrete information. Similarly, the ntopng man page contains the following:

> ntopng includes LuaJIT, mongoose, rrdtool and **zeromq** in the third-party/  directory.   Users  of ntopng should not need to specifically install such libraries.

However the `third-party/` directory does not appear to be distributed with the rpm version.

As best as I can tell the current Centos6 rpm depends on simply `zeromq` but the application itself explicitly expects `libzmq.so.4`, a dependency that is _not_ satisfied by the package available from epel, which provides only `libzmq.so.1`, or any other Centos6 repo that I can find.

edit: I'm getting the impression that the Centos6 package was built with the same, or similar, specfile as the Centos7 package as EPEL has 0MQ v4 as the `zeromq` package for Centos7.

**Comment by ValentinaViscarelli** [comment]
@rewwade 
Try to install libzmq as described here: http://packages.ntop.org/centos/

In particular:

cd /etc/yum.repos.d/
wget https://copr.fedoraproject.org/coprs/saltstack/zeromq4/repo/epel-X/saltstack-zeromq4-epel-X.repo

Note: replace X with 6 (for CentOS 6) or 7 (for CentOS 7) then do:

```
yum erase zeromq3 (Do this once to make sure zeromq3 is not installed)
yum clean all
yum update
yum install pfring n2disk nprobe ntopng ntopng-data nbox 
```
