### ISSUE TITLE
Unable to add Network pool members

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4507]
Add button stays disabled

![image](https://user-images.githubusercontent.com/3397663/94839331-25363300-0417-11eb-853b-cf080edc3d89.png)

**Comment by simonemainardi** [comment]
After several refreshes, it has started working. Will reopen if it happens again.

**Comment by simonemainardi** [comment]
This has resurfaced.  It happens sporadically but happens:

![image](https://user-images.githubusercontent.com/3397663/94940227-81f72380-04d3-11eb-8708-2ed18a05194b.png)

The Add button should be enabled

**Comment by lucaderi** [comment]
![Screen Shot 2020-10-08 at 00 10 54](https://user-images.githubusercontent.com/4493366/95393373-c2eb9f80-08fa-11eb-9286-e8ca4a8261f2.png)
Still bugged

**Comment by simonemainardi** [comment]
To reproduce:

- pick one member type and fill a field with invalid data
- pick another member type and fill the fields with valid data: the Add button won't enable

**Comment by simonemainardi** [comment]
fixed now
