### ISSUE TITLE
fails to build: src/Flow.cpp:266:42: error: ‘struct ndpi_flow_struct’ has no member named ‘bittorent_hash’

### ISSUE THREAD

**Issue by grinapo** [ntop/ntopng#451]
Tried to compile on Debian/sid (to resolve the redis lib clashing) and got this:
src/Flow.cpp: In member function ‘void Flow::processDetectedProtocol()’:
src/Flow.cpp:266:42: error: ‘struct ndpi_flow_struct’ has no member named ‘bittorent_hash’
       setBittorrentHash((char*)ndpiFlow->bittorent_hash);
                                          ^
Makefile:129: recipe for target 'src/Flow.o' failed

(both ntopng and nDPI is pulled up to the branch 'dev')

**Comment by grinapo** [comment]
Also ntop_includes.h seem to missing 'ndpi_api.h' (educated guess), making other parts of the compile to fail.

**Comment by lucaderi** [comment]
You need to update nDPI and it will work

**Comment by grinapo** [comment]
Both were pulled before compilaton... but I'll try again...
