### ISSUE TITLE
Fix package warning

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4519]
# dpkg -i apt-ntop.deb 
Selecting previously unselected package apt-ntop.
(Reading database ... 107428 files and directories currently installed.)
Preparing to unpack apt-ntop.deb ...
Unpacking apt-ntop (2.8-3) ...
Setting up apt-ntop (2.8-3) ...
Adding ntop key to apt keyring
Warning: apt-key should not be used in scripts (called from postinst maintainerscript of the package apt-ntop)
OK

**Comment by cardigliano** [comment]
It is a common practice to let the user manually add key (from a keyserver) and repository,
this means replacing the apt-ntop.deb installation with instructions like the below:

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 111AF5ED8DABFE9F9D6BB6F46F13614FD1EB60BE
echo "deb http://packages.ntop.org/apt/$(lsb_release -sr)/ x64/" | sudo tee /etc/apt/sources.list.d/ntop.list
echo "deb http://packages.ntop.org/apt/$(lsb_release -sr)/ all/" | sudo tee -a /etc/apt/sources.list.d/ntop.list

Or we can just let the user download the key from packages.ntop.org:

curl -fsSL https://packages.ntop.org/../gpg | sudo apt-key add -
echo "deb http://packages.ntop.org/apt/$(lsb_release -sr)/ x64/" | sudo tee /etc/apt/sources.list.d/ntop.list
echo "deb http://packages.ntop.org/apt/$(lsb_release -sr)/ all/" | sudo tee -a /etc/apt/sources.list.d/ntop.list

**Comment by lucaderi** [comment]
Ok let's leave it as for the time being
