### ISSUE TITLE
ntop export pcap

### ISSUE THREAD

**Issue by iber-mi** [ntop/ntopng#452]
There any way to export ntop Netflows connections of different interfaces to a pcap file?

**Comment by simonemainardi** [comment]
I am not sure what you want to achieve. Netflow ships flow data only not packet contents, why do you want pcaps? Why don't you just use option -F to dump flows to MySQL? please explain

**Comment by iber-mi** [comment]
I -F option does not work, I want a file with all connections with the plugin rrd captured several remote computers with NetFlow, and then load that file into wireshark, is that possible?

**Comment by iber-mi** [comment]
Could you tell me because it does not work?

The server cannot find the requested page (page expired or ntop configuration ?).
Received request:

"GET /historicalTalkers.html HTTP/1.1"
This feature is not YET available on your platform: we're working for you

**Comment by simonemainardi** [comment]
pcap dump is not available for collector interfaces.

Also note that:
- ntopng does not directly talk netflow, it talks to the nprobes via ZMQ
- nprobe, on turn, may talk netflow

So if you want to capture ZMQ between nprobes and ntopng you can quickly use wireshark on your own, e.g., 
if you have the following configuration:

```
ntopng -itcp://192.168.2.129:5556
nprobe --zmq tcp://*:5556
```

you can just use a quick wireshark filter like the following:

```
ip.src == 192.168.2.129 and tcp and tcp.port==5556
```

same is true for netflow data you just need to know the port etc.

---

Your latest post doesn't seem to be related to the conversation so you should open a new issue.

**Comment by iber-mi** [comment]
Ntopng not talk about, talk about ntop, is the title of the topic.

**Comment by simonemainardi** [comment]
you already know that ntop is no longer supported: #446
