### ISSUE TITLE
Extend Flow Direction

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4521]
![Screen Shot 2020-10-03 at 13 14 08](https://user-images.githubusercontent.com/4493366/94990195-7448a900-057a-11eb-9610-fb88c4d261cf.png)

Add the ability to filter
- Remote -> Local
- Local -> Local
- Local -> Remote

flows

**Comment by simonemainardi** [comment]
Already available under the "Hosts" dropdown:

![image](https://user-images.githubusercontent.com/3397663/95187488-82413880-07cb-11eb-8416-b140631181b7.png)
