### ISSUE TITLE
Active Monitoring alerts are not reported in the status bar

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4522]
![Screen_Shot_2020-10-03_at_13_35_18](https://user-images.githubusercontent.com/4493366/94990576-73654680-057d-11eb-9f82-5470da409346.png)

**Comment by simonemainardi** [comment]
Implemented 

![image](https://user-images.githubusercontent.com/3397663/95182360-c8df6480-07c4-11eb-950a-5439bd0134c8.png)
