### ISSUE TITLE
Invalid graph unit

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4525]
![Screen_Shot_2020-10-03_at_16_40_52](https://user-images.githubusercontent.com/4493366/94994370-710fe600-0597-11eb-9c4d-8755722499f8.png)
In community edition, going under active monitoring and picking a host 
- the unit is bit/s but here we're talkign about latency so it has to be msec
- top talkers must be removed from charts in the system interface

Please correct these two bugs

**Comment by simonemainardi** [comment]
all system-interface charts must hide "Minute Interface Top Talkers"

**Comment by gabryon99** [comment]
As discussed with @lucaderi we have decided to not show a label inside the graph.

**Comment by lucaderi** [comment]
![Screen Shot 2020-10-08 at 00 07 19](https://user-images.githubusercontent.com/4493366/95393095-45c02a80-08fa-11eb-8d73-daccfed64c55.png)
Please round decimals 0.033611111111111
