### ISSUE TITLE
Invalid throughput calculation 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4529]
With ZMQ the upper throuhgput chart is broken as the number (0 bps) is not the corresponding to the chart value

![Screen Shot 2020-10-05 at 18 25 35](https://user-images.githubusercontent.com/4493366/95106147-6ccefe80-0738-11eb-8c82-a49b25d1c61e.png)

**Comment by simonemainardi** [comment]
Throughput is now fixed.

Charts in the top bar show local ntopng traffic as for any other interface. This, in case of ZMQ, represent the throughput obtained by summing flow data.

Probe throughput, that is, the actual traffic experienced on the remote probe, is shown and dynamically refreshed under the interface stats page.

![image](https://user-images.githubusercontent.com/3397663/95325493-90618880-08a1-11eb-9c55-eaead6998f9f.png)
