### ISSUE TITLE
ntopng Dropped Packets is hign

### ISSUE THREAD

**Issue by tinycolds** [ntop/ntopng#453]
we are capturing the flow from **em4,** it's nearly **1100Mbps**. however, the Dropped Packets is nearly **25%** and we found that the process runs on a single core(we have 24 cores), we just want the capture process runs on multi cores and it will improve the performance, is that possible?

**Comment by tinycolds** [comment]
`Setting affinity of interface em4 to core 1`
can we set the interface to multi cores?
btw, the version of the code we use is the latest **dev** **branch**.
hmmm, can someone give me some suggestions how to decrease the **Dropped Packets**, thanks !

**Comment by lucaderi** [comment]
You need to
1. increase -x/-X
2. use RSS to create at least 2 queues
3. start ntopng over the two queues

**Comment by tinycolds** [comment]
Hi, lucaderi, i tried to decrease and increase -x/-X and strangely found that **when decreasing the option, the Dropped Packets is nearly 2.83%**, very confused about the result.

**Comment by lucaderi** [comment]
please post more stats about the drop/hosts/traffic rate etc

**Comment by tinycolds** [comment]
Dear lucaderi, so sorry for the late reply ! I dont't have access to the ntopng server these days.

Our previous ntopng.conf is`-G=/var/tmp/ntopng.pid -n=1 -P -i=em4 -m 10.0.0.0/8 -H -e daemon` 

The data shown on the website is **Active Flows 89131, All hosts 25561, Dropped Packets 18%**
![4 pic](https://cloud.githubusercontent.com/assets/11733909/13909937/b0b089b6-ef55-11e5-8884-03f3e7ae7389.jpg)

We add `-x 2000 -X 8000` to the ntopng.conf and we found the data changed,
**Active Flows 5408, All hosts 1823, Dropped Packets 2%**
![1 pic](https://cloud.githubusercontent.com/assets/11733909/13909969/1deb30da-ef56-11e5-9b57-d55d7b3c74db.jpg)

So, when i decrease -x/-X, the Dropped Packets also decreases, does that increase the server performance ? Sincerely waiting for ur reply.

**Comment by lucaderi** [comment]
You need to set -X/-x to at least double the value you have. In essence I would start with -x 512000 -X 512000 and see what happens. The larger is x/X the better is the performance but slightly more memory is used/

**Comment by tinycolds** [comment]
Dear lucaderi, following ur instruction, i start the server with `-x 512000 -X 512000.`
However, the Dropped Packets is so high and **All Hosts is 205507 Active Flows is 401260.**
So why Dropped Packets so high ? 
![8 pic](https://cloud.githubusercontent.com/assets/11733909/13914866/3144f0f4-ef8c-11e5-96dc-a89528c4ffbb.jpg)

**Comment by simonemainardi** [comment]
512k hosts and flows are fully occupied. Try to increase these thresholds even more.

In addition, as @lucaderi suggested, you should also use RSS to create more than one queue and then possibly bind each queue to a different cpu

**Comment by tinycolds** [comment]
Sincerely thanks !

**Comment by lucaderi** [comment]
I think you are monitoring a large network using a default configuration. You need to do something more than simply starting ntopng. Please follow @simonemainardi advices.
