### ISSUE TITLE
main.cpp:235] ERROR: An exception occurred during all interface creation[19]: No such device

### ISSUE THREAD

**Issue by AWHubGit** [ntop/ntopng#4530]
[main.cpp:293] ERROR: Startup error: missing super-user privileges ?
--
PRIORITY | 3
SYSLOG_FACILITY | 1
SYSLOG_IDENTIFIER | ntopng
SYSLOG_TIMESTAMP | Oct  6 08:31:03
_AUDIT_LOGINUID | 1000
_AUDIT_SESSION | 4
_BOOT_ID | 64c254a30a61459cb
_CAP_EFFECTIVE | ffffffffff
_CMDLINE | /usr/bin/ntopng -i all

Executing command line "sudo /usr/bin/ntopng -i all" in a Gnome-terminal throws:

[Ntop.cpp:2229] Setting local networks to 127.0.0.0/8
06/Oct/2020 08:39:10 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
06/Oct/2020 08:39:10 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
06/Oct/2020 08:39:11 [main.cpp:235] ERROR: An exception occurred during all interface creation[19]: No such device
06/Oct/2020 08:39:11 [main.cpp:293] ERROR: Startup error: missing super-user privileges ?

command line "sudo /usr/bin/ntopng -i eno1":
.....................................
......................................
06/Oct/2020 08:41:47 [Ntop.cpp:437] Welcome to ntopng x86_64 v.4.0.201003 - (C) 1998-20 ntop.org
06/Oct/2020 08:41:47 [Ntop.cpp:832] Adding 192.168.177.104/32 as IPv4 interface address for eno1
...................................
..................................
ntopng is up and running

What is "all"? Where is "all" defined? man page ntopng doesn't know "all".

cat /etc/systemd/system/multi-user.target.wants/ntopng@all.service
[Unit]
Description=ntopng network traffic monitor
[Service]
ExecStart=/usr/bin/ntopng -i %I
[Install]
WantedBy=multi-user.target

What is "%I"? Where is "%I" defined and piped to the command?

Calling ntopng --help properly lists all interfaces available at the end.

**Comment by simonemainardi** [comment]
`/etc/systemd/system/multi-user.target.wants/ntopng@all.service` is not stuff created/configured by ntopng sources / ntopng packages. Likely, someone has created a custom service file for ntopng.

`all` doesn't exist. If you want to run ntopng on all the available interfaces, just omit `-i`.
