### ISSUE TITLE
TalosIntelligence.com block list.

### ISSUE THREAD

**Issue by finchy** [ntop/ntopng#4534]
The block list on TalosIntelligence.com is no longer correct, it has moved to Snort.org. https://snort.org/downloads/ip-block-list

However, that is not the major issue.  The Major issue is that each IP of the NTOP installation attempts to download the Block List from talosintelligence.com approximately 289,000+ times a day.  (about 13,000 times an hour).

I have currently blocked ALL NTOP installations from downloading the block list on both sites until this timing issue can be corrected.

**Comment by simonemainardi** [comment]
Both urls work, however, I'm getting 403 unauthorized responses from cloudflare. this is why downloading fails. However, I'm unable to reproduce the behavior that ntopng is trying to download 13k per hour.

**Comment by finchy** [comment]
Understood. Not sure what to tell you. This is the behavior I am seeing to our server.  You are getting 403 because the traffic is blocked. 

The old link works because of a 301 redirect I have in place. Unless the timing issue is figured out, I will have to leave it blocked. A single IP downloading the file 13k an hour Is putting quite a load on the server when you multiply that load times all the ntop
Installations.

**Comment by simonemainardi** [comment]
are you on 4.1 or 4.0?

**Comment by finchy** [comment]
I run Talosintelligence.com <http://talosintelligence.com/> and Snort.org <http://snort.org/>.

**Comment by simonemainardi** [comment]
I mean, ntopng version.

**Comment by finchy** [comment]
I am not using it at all.  I am seeing the traffic pointed at our sites.

**Comment by simonemainardi** [comment]
OK, I see.

**Comment by lucaderi** [comment]
@finchy As of #4554 I confirm we have a bug to fix.

**Comment by finchy** [comment]
Hey Luca, Joel Esler here. Good to hear from you. 

Thanks.

**Comment by lucaderi** [comment]
@finchy I believe I have found and fixed the culprit. But
- You are still blocking ntopng based on the user-agent. Our format is ntopng 4.1.200902/x86_64/MacOSX 10.13.6
- This fix applies only to ntopng versions older than today so let's say ntopng 4.1.201016 and older

How do you want to handle the unlock? I don't think it is safe for you to unlock versions up to 4.1.201015, but I would like to see newer version to operate normally.

Last resort is to mirror the blacklist file on our servers and point to it, but you will loose the download/popularity counter.

What do you suggest me to do?

**Comment by finchy** [comment]
What is the version that this will ship in, I can allow that, and we can test.

**Comment by lucaderi** [comment]
Tonight we'll build new version with 4.1.201016 (this is the date as you can guess). That one you can enable for testing, but not older ones

**Comment by finchy** [comment]
Okay, should be good now.

**Comment by lucaderi** [comment]
Everythign seems to work. Thank you
