### ISSUE TITLE
Software update is broken in community mode

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4536]
When ntopng (installed from packages.ntop.org) and run in community mode (--community on the CLI) automatic and top-right menu update check is not working

![Screen Shot 2020-10-06 at 22 11 30](https://user-images.githubusercontent.com/4493366/95254923-ee9a5700-0820-11eb-9338-d4941c17f437.png)

**Comment by cardigliano** [comment]
Fixed with e744b57f733e5be2953e63c67b41bbafce22b636 and 3998ad91380b44a3ca71b2770ebdbdaf1650bef8 (testing)

**Comment by cardigliano** [comment]
Community is now supported
