### ISSUE TITLE
email address validation for alarm endpoint recipient fails using hyphen

### ISSUE THREAD

**Issue by aleex1848** [ntop/ntopng#4538]
Version used 4.1.200929 (11606) - Professional Edition

If using a hyphen in email address domain like @e-mail.de the validation fails and the mail address can't be used:
![image](https://user-images.githubusercontent.com/17452861/95446117-278d1580-0960-11eb-8dae-a7d596720912.png)

**Comment by gabryon99** [comment]
We have replaced the old regex to check the mail address validity. @simonemainardi can you confirm? The referenced commit is: https://github.com/ntop/ntopng/commit/ca0be5f478136ad107a30b65b492d93e5ff4af6c

**Comment by simonemainardi** [comment]
I don't like the new regex - you're basically allowing every possible character but spaces - including `<` `>`. This is a possible source for XSS vulnerabilities. Why don't you just slightly extend the existing regex to allow hyphens?

**Comment by gabryon99** [comment]
@simonemainardi you are right! I corrected the regex as you suggested. Check the last commit.
