### ISSUE TITLE
Feature Request:  Alert on duration

### ISSUE THREAD

**Issue by DigiAngel** [ntop/ntopng#454]
I'd love to have an "alert on duration" feature in ntop-ng.  The use case would be to catch tcp/udp/icmp sessions/flows that may have say a trickle of data.  I'd like to be able to set a time like, say 30 minutes, to alert on in the case of a long session that may be small bits of data...this could hopefully assist with catching bad guys trying to exfiltrate data out of a network.  Thank you.

**Comment by simonemainardi** [comment]
alerts are now stateful: they become engaged when the problem starts, and they become closed when the problem ends. Closed alerts show a duration.

Please, check that out and let us know, thank you.

**Comment by DigiAngel** [comment]
Thank you!
