### ISSUE TITLE
Submenu don't scroll so last items are not shown

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4540]
<img width="347" alt="Screenshot 2020-10-08 at 13 19 37" src="https://user-images.githubusercontent.com/4493366/95452148-1e547680-0969-11eb-9f4b-d9b59fa054f1.png">

**Comment by simonemainardi** [comment]
there are additional menu entries under "Interface", but I'm unable to reach them with this browser height

![image](https://user-images.githubusercontent.com/3397663/95469028-6aaab100-097f-11eb-82e5-1579c987d0bf.png)

**Comment by lucaderi** [comment]
We discussed about the issue you reported and putting a scrollbar on the sidebar doesn't look a good idea. So we'll leave as is for the time being as other (e.g. grafana) do.
