### ISSUE TITLE
Missing debugging information in syslog collection

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4544]
<img width="1297" alt="Screenshot 2020-10-08 at 16 16 22" src="https://user-images.githubusercontent.com/4493366/95473168-1e15a480-0984-11eb-9e4c-aced5063736b.png">

In ntopng it is not clear if ntopng is receiving messages, parsing them, discarding them. All is zero. This has to be fixed and complemented with syslog stats

**Comment by cardigliano** [comment]
Implemented in fc8357ce6fed58696bd095a78a7c0f206edb806b bafccf2c060edac9d8a609fca5c99a633dc88b46 a64095f244667d88eeb54b29242875c734ca430f
