### ISSUE TITLE
Invalid host pool switch URL

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4546]
<img width="1296" alt="Screenshot 2020-10-08 at 16 50 39" src="https://user-images.githubusercontent.com/4493366/95475494-8ebdc080-0986-11eb-830c-99ce93cd6a9c.png">

clicking on the wheel sends to

http://XXXXX:3000/lua/if_stats.lua?page=pools&pool=1

that is an empty page

<img width="1312" alt="Screenshot 2020-10-08 at 16 50 51" src="https://user-images.githubusercontent.com/4493366/95475489-8d8c9380-0986-11eb-9c0e-32b3a58adc5f.png">

Instead of http://XXXX:3000/lua/admin/manage_host_members.lua with the selected pool

**Comment by gabryon99** [comment]
I changed the link to: `/lua/admin/manage_host_members.lua?pool={pooliD}`

**Comment by simonemainardi** [comment]
must hide the pool wheel for the default pool id:

![image](https://user-images.githubusercontent.com/3397663/95477883-1f959b80-0989-11eb-80cb-72c8a48b357b.png)


otherwise you'll end up in an empty page. Use `DEFAULT_POOL_ID` constant to hide the wheel.
