### ISSUE TITLE
Unable to use i18n in manifest.lua of plugins

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4547]
This works

return {
  title = "Flow Flood detector",
  description = "Detects flow flood attacks and triggers alerts",
  author = "ntop",
  dependencies = {},
}

this does not work

return {
  title = **i18n("flow_flood.title")**,
  description = "Detects flow flood attacks and triggers alerts",
  author = "ntop",
  dependencies = {},
}

Same for all other fields (e.g. description)

**Comment by simonemainardi** [comment]
Plugin `manifest.lua` is a backend file, read when the plugin is loaded in the backed. This manifest file contains basic plugin info, including plugin dependencies. For this reason, as `manifest.lua` is loaded in the backend, there's no concept of user language and localization, i.e., even with i18n(), it will only be chosen the English language.

As `manifest.lua` contents are not meant to be shown to the language-aware end used, this file should not be localization-aware (think to an Android manifest for example).

Localization is (and must) be available in plugin components, such as user scripts, which require end user interaction via UI - e.g., user script name, description, toggles, preferences. For these components, localization is available as described in https://www.ntop.org/guides/ntopng/plugins/localization.html
