### ISSUE TITLE
ntopng restart automatically after packages upgrade even if is disabled on systemd

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#4551]
In my environment, during some tests, I need to run ntopng only in a manually way (with `systemctl start ntopng.service` or running `ntopng` directly).

This is not possible when I upgrade the packages. :-(

Even if I disable ntopng to auto-start (with `systemctl disable ntopng.service`), this configuration is overwritten during the upgrade.
If I remember well this configuration should not be overwritten by a simple upgrade...

I tried also to mask it  without success:
```
# systemctl mask ntopng.service
Failed to execute operation: Invalid argument
```

Is there a way to prevent the auto-start of the ntopng process also during packages upgrade?

Thanks :-)

**Comment by cardigliano** [comment]
@gianogli please check latest package, service is now enabled on first installation only

**Comment by gianogli** [comment]
I've just upgrade (today at 16:07) the ntopng package to 4.1.201014-11829 but during the upgrade process I saw this message:
```
[...]
(Re)Starting ntopng...
[...]
```
On systemctl logs:
```
# systemctl status ntopng.service 
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/etc/systemd/system/ntopng.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

Oct 14 16:07:01 nasone systemd[1]: ntopng.service: Service hold-off time over, scheduling restart.
Oct 14 16:07:01 nasone systemd[1]: Stopped ntopng high-speed web-based traffic monitoring and analysis tool.
Oct 14 16:07:01 nasone systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
Oct 14 16:07:01 nasone sh[24147]: /bin/cat: /etc/ntopng/ntopng.conf: No such file or directory
Oct 14 16:07:01 nasone systemd[1]: ntopng.service: Control process exited, code=exited status=1
Oct 14 16:07:01 nasone systemd[1]: Failed to start ntopng high-speed web-based traffic monitoring and analysis tool.
Oct 14 16:07:01 nasone systemd[1]: ntopng.service: Unit entered failed state.
Oct 14 16:07:01 nasone systemd[1]: ntopng.service: Failed with result 'exit-code'.
Oct 14 16:07:01 nasone systemd[1]: Stopped ntopng high-speed web-based traffic monitoring and analysis tool.
```
I think I tried to restart again even it was stopped.
It didn't start only because I've renamed /etc/ntopng/ntopng.conf

What do you think?

Thanks :-)

**Comment by cardigliano** [comment]
@gianogli a few questions, just to make sure:
- was the service stopped before the upgrade?
- was the service enabled before the upgrade?
- is the service enabled after the upgrade?

**Comment by gianogli** [comment]
Yes, the ntopng.service was stopped and no ntopng instances was running.
Yes, the ntopng.service was disabled before upgrade:
```
 Loaded: loaded (/etc/systemd/system/ntopng.service; disabled; vendor preset: enabled)
```
No, the service was disabled after the upgrade:
```
 Loaded: loaded (/etc/systemd/system/ntopng.service; disabled; vendor preset: enabled)
```

**Comment by cardigliano** [comment]
What OS version are you running?

**Comment by lucaderi** [comment]
Today I have updated using the top right menu. Unfortunately after the upgrade this was the state

root@ntopng:/home/deri# service ntopng status
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/etc/systemd/system/ntopng.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

Oct 14 14:56:16 ntopng.estra.it ntopng[9656]: 14/Oct/2020 14:56:16 [ProtoStats.cpp:35] [IPv4]  344 B/4.00 Packets
Oct 14 14:56:16 ntopng.estra.it ntopng[9656]: 14/Oct/2020 14:56:16 [ProtoStats.cpp:35] [IPv6]  0 B/0.00 Packets
Oct 14 14:56:16 ntopng.estra.it ntopng[9656]: 14/Oct/2020 14:56:16 [ProtoStats.cpp:35] [ARP]   0 B/0.00 Packets
Oct 14 14:56:16 ntopng.estra.it ntopng[9656]: 14/Oct/2020 14:56:16 [ProtoStats.cpp:35] [MPLS]  0 B/0.00 Packets
Oct 14 14:56:16 ntopng.estra.it ntopng[9656]: 14/Oct/2020 14:56:16 [ProtoStats.cpp:35] [Other] 0 B/0.00 Packets
Oct 14 14:57:41 ntopng.estra.it systemd[1]: ntopng.service: State 'stop-sigterm' timed out. Killing.
Oct 14 14:57:41 ntopng.estra.it systemd[1]: ntopng.service: Killing process 9656 (ntopng) with signal SIGKILL.
Oct 14 14:57:41 ntopng.estra.it systemd[1]: ntopng.service: Main process exited, code=killed, status=9/KILL
Oct 14 14:57:41 ntopng.estra.it systemd[1]: ntopng.service: Failed with result 'timeout'.
Oct 14 14:57:41 ntopng.estra.it systemd[1]: Stopped ntopng high-speed web-based traffic monitoring and analysis tool.

Namely ntopng was not restarted. Starting it from shell fixed the problem.

**Comment by gianogli** [comment]
> What OS version are you running?

```
# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by cardigliano** [comment]
The service was disabled before the upgrade (prerm), and never enabled after the upgrade (postinst) because it was detected as disabled. I pushed a fix for this.

**Comment by gianogli** [comment]
I've just tried again to update ntopng with aptitude from  4.1.201014-11834 to 4.1.201014-11829 and now it works as expected.
When ntopng is disabled in systemd it doesn't start automatically anymore during an upgrade.
Thanks. :-)
