### ISSUE TITLE
SNMP preferences are not shown in simple view

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4552]
Clicking on this link

![Screen Shot 2020-10-09 at 12 17 57](https://user-images.githubusercontent.com/4493366/95571953-89fe1880-0a29-11eb-8e2c-d1e4e2a7786b.png)

sends to http:/XXXXXX:3000/lua/admin/prefs.lua?tab=snmp

![Screen Shot 2020-10-09 at 12 18 13](https://user-images.githubusercontent.com/4493366/95571997-9a15f800-0a29-11eb-9d71-804a6a1354ff.png)

where the SNMP tab is hidden as simple view is set. 

The fix is to BOTH switch to expert view AND go to the SNMP page

**Comment by simonemainardi** [comment]
You've introduced a huge complexity and also a security vulnerability as you toggle the status simple->expert with a GET.

Fix is to pass parameter `show_advanced_prefs` in the GET and, when present, show the expert view without doing the actual toggle to expert.

**Comment by gabryon99** [comment]
Done as requested.
