### ISSUE TITLE
Flow exporter statistics are misleading

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4553]
Suppose to enable nprobe to export flows towards ntopng. For some minutes (with constant flow export) this is what is displayed

![Screen Shot 2020-10-09 at 12 21 32](https://user-images.githubusercontent.com/4493366/95572523-5d96cc00-0a2a-11eb-8b30-4cae9c4582d1.png)

after some more minutes

![Screen_Shot_2020-10-09_at_12_23_23](https://user-images.githubusercontent.com/4493366/95572722-a77fb200-0a2a-11eb-837e-5de50899fe5a.png)

This is misleading for the user who has no clue what is happening and thinks that there is a bug in the configuration event though this is not the case

**Comment by simonemainardi** [comment]
My guess is that the first flow hit ntopng AFTER time 05:04 (look at the first header, it was empty without the flows counter). Hence, no exporter was known at 05:04. I think we should add a notice, or a badge in the header, which says: no flow collected yet.

**Comment by lucaderi** [comment]
The issue happens with virtual interfaces. On the main collector interface there are no hosts

![Screen Shot 2020-10-11 at 12 05 28](https://user-images.githubusercontent.com/4493366/95675814-222b0780-0bba-11eb-8f97-b7f3ba069ff8.png)

but switching to the virtual itnerface (disaggregation) statistics are present

![Screen Shot 2020-10-11 at 12 05 39](https://user-images.githubusercontent.com/4493366/95675820-3111ba00-0bba-11eb-9bad-f336babc2c1a.png)

BUT the sidebar does not have the exporters menu. This is the bug

**Comment by lucaderi** [comment]
Verified as fixed
