### ISSUE TITLE
Category file download frequency is broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4554]
As shown in
![Screen_Shot_2020-10-09_at_12_31_14](https://user-images.githubusercontent.com/4493366/95573440-bdda3d80-0a2b-11eb-8a4f-19da5a2758cd.png)
ntopng MUST download ONCE a day the above file but apparently this is not what is happening
![Screen_Shot_2020-10-09_at_12_31_47](https://user-images.githubusercontent.com/4493366/95573446-bfa40100-0a2b-11eb-9428-b5f45b1237d9.png)

that causes the bug #4534

**Comment by simonemainardi** [comment]
Do these download attempts occur when ntopng is restarted?

**Comment by simonemainardi** [comment]
I've added an info-severity level also when lists are downloaded successfully. Please, update and check whether talos retries occur only after startup.

![image](https://user-images.githubusercontent.com/3397663/95993062-eea4e300-0e2e-11eb-8a64-264756109956.png)

**Comment by lucaderi** [comment]
https://github.com/ntop/ntopng/commit/77ab1e3a8abd4e291d57322852af3772f7729e5d changed download to at most once in case of failure and logging on console for downloads that will help understanding slow starts as downloads are in progress
