### ISSUE TITLE
SNMP Interface Alias are not used in reports

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4557]
![Screen_Shot_2020-10-09_at_17_30_07](https://user-images.githubusercontent.com/4493366/95607993-d31b9000-0a5c-11eb-80f1-81bf69b40843.png)
![Screen_Shot_2020-10-09_at_17_30_14](https://user-images.githubusercontent.com/4493366/95607994-d44cbd00-0a5c-11eb-9336-cbf36e59d33a.png)

**Comment by simonemainardi** [comment]
fixed in https://github.com/ntop/ntopng/commit/4bbf020a58a43f9e6648ee09fe98e45b9a199416
