### ISSUE TITLE
Invalid symbolic name used for 0.0.0.0

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4558]
![Screen_Shot_2020-10-09_at_17 37 52](https://user-images.githubusercontent.com/4493366/95608159-03632e80-0a5d-11eb-8339-b1542fdb80b2.png)

**Comment by simonemainardi** [comment]
NoIP is due to ntopng forcefully setting this resolved name: `setResolvedAddress((char)"0.0.0.0", (char)"NoIP");`. Please explain if this is correct behavior.

There's no trace of string N/A in the code.

**Comment by lucaderi** [comment]
Fine so we leave unfixed until we can reproduce it
