### ISSUE TITLE
'Script "crsf" returned an error' when saving license file

### ISSUE THREAD

**Issue by skendric** [ntop/ntopng#456]
Generating an ntopng Pro version license appears to succeed.  But saving that license produces the error message:
     Script "crsf" returned an error

Manually creating the license and restarting ntopng produces the following messages:

Mar 22 05:48:07 ganesh logger: ntopng start
Mar 22 05:48:07 ganesh ntopng: [NtopPro.cpp:158] ERROR: [LICENSE] Invalid or mis
sing ntopng License [License mismatch error]
Mar 22 05:48:07 ganesh ntopng: [NtopPro.cpp:171] WARNING: [LICENSE] ntopng will 
now run in pro mode for 10 minutes
Mar 22 05:48:07 ganesh ntopng: [NtopPro.cpp:173] WARNING: [LICENSE] before retur
ning to community mode
Mar 22 05:48:07 ganesh ntopng: [NtopPro.cpp:174] WARNING: [LICENSE] You can buy 
a permanent license at http://shop.ntop.org
Mar 22 05:48:07 ganesh ntopng: [NtopPro.cpp:175] WARNING: [LICENSE] or run ntopn
g in community mode starting
Mar 22 05:48:07 ganesh ntopng: [NtopPro.cpp:176] WARNING: [LICENSE] ntopng --com
munity
Mar 22 05:48:08 ganesh ntopng: Starting ntopng: [  OK  ]

I attach a PDF illustrating what I see.

[ntopng-license-generation-issue.pdf](https://github.com/ntop/ntopng/files/184111/ntopng-license-generation-issue.pdf)

**Comment by lucaderi** [comment]
@skendric This happens when the crsf-protected page has been open for a while. Example you open the page with the form, do something else, then click on the page after 5/10 mins. This is a protection mechanism. In order to avoid it, please reload the page, try again an it will work.

**Comment by skendric** [comment]
OK, I quit my browser, open it again, return to About ntopng, and see my license key displayed prominently.  I click Save License and indeed, no error message.

However.

I don't see an /etc/ntopng.license file and reloading ntopng leads to the same 'Invalid or missing ntopng license' message in syslog.

Running "strace ntopng --check-license", I see:
stat("/etc/ntopng.license", 0x7ffcc2401e70) = -1 ENOENT (No such file or directo
ry)
write(5, "*2\r\n$3\r\nGET\r\n$14\r\nntopng.license"..., 34) = 34
read(5, "$50\r\n31AA49967C5FF2826CB08941142"..., 16384) = 57
open("31AA49967C5FF2826CB089411422EE6B1490015319F4F43C99", O_RDONLY) = -1 ENOENT
 (No such file or directory)
[...]
write(1, "Demo mode license\n", 18)     = 18
exit_group(0)  

Creating /etc/ntopng.license by hand and then running "ntopng --check-license", I see:
[...]
stat("/etc/ntopng.license", {st_mode=S_IFREG|0644, st_size=51, ...}) = 0
open("/etc/ntopng.license", O_RDONLY)   = 6
[...]
read(6, "31AA49967C5FF2826CB089411422EE6B"..., 4096) = 51
[...]
write(5, "*2\r\n$3\r\nGET\r\n$14\r\nntopng.license"..., 34) = 34
read(5, "$50\r\n31AA49967C5FF2826CB08941142"..., 16384) = 57
open("31AA49967C5FF2826CB089411422EE6B1490015319F4F43C99", O_RDONLY) = -1 ENOENT
 (No such file or directory)
[...]
write(1, "Demo mode license\n", 18)     = 18
exit_group(0) 

Does the strace output offer any additional insights into what might be happening?

--sk

**Comment by lucaderi** [comment]
ntopng.license is created only by command line. The license you add via GUI is just put on redis (so make sure you do not reset it or you will loose your license).

**Comment by skendric** [comment]
I see, so there are (2) places to store the license:
- /etc/ntopng
- redis

Examining the strace output I posted, I would suggest that I have stored the license in *both* places.

I remain puzzled, though, as to why "ntopng --check-license" continues to return "Demo mode license" rather than "Professional" or similar.  And why ntopng's start-up routines log "Invalid or missing ntopng license file", when in fact the license exists in /etc/ntopng.license.

What scenarios can you imagine that would result in these behaviors?

Here are my uneducated guesses:
(a) The license generation code generated an invalid license string.
(b) The version I am running (v2.2.160323) contains a bug in it which interferes with correctly checking the license string.

--sk

**Comment by skendric** [comment]
Or
(c) I have fumbled installing the license in redis or in /etc/ntopng.license in some fashion

**Comment by skendric** [comment]
I see, so there are (2) places to store the license:

```
/etc/ntopng
redis
```

Examining the strace output I posted, I would suggest that I have stored the license in both places.

I remain puzzled, though, as to why "ntopng --check-license" continues to return "Demo mode license" rather than "Professional" or similar. And why ntopng's start-up routines log "Invalid or missing ntopng license file", when in fact the license exists in /etc/ntopng.license.

What scenarios can you imagine that would result in these behaviors?

Here are my uneducated guesses:
(a) The license generation code generated an invalid license string.
(b) The version I am running (v2.2.160323) contains a bug in it which interferes with correctly checking the license string.
(c) I have fumbled the procedure for registering the license string with redis _and_ with creating the license file:  /etc/ntopng.license

--sk

**Comment by lucaderi** [comment]
@skendric Can you please post your ntopng's systemId and license you use?

**Comment by skendric** [comment]
System ID:  B6B0840C000207D0
License:  31AA49967C5FF2826CB089411422EE6B1490015319F4F43C99

**Comment by lucaderi** [comment]
I see the problem. You have generated the license for an invalid systemId and thus it does not work. Please use 512ED18FAAEEC0AFFE0D9DD0BB9229C71490361474996BD94A and it will work.
