### ISSUE TITLE
Missing required field 'alert_key' 

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#4561]
Missing required field 'alert_key' in status_malicious_signature from /usr/share/ntopng/scripts/lua/modules/flow_status_definitions

**Comment by MaoPann** [comment]
![image](https://user-images.githubusercontent.com/44804599/95656424-f3247f80-0b40-11eb-8276-a9b8a584f1bc.png)

**Comment by lucaderi** [comment]
Duplicate of #4560

**Comment by MaoPann** [comment]
Does the presence of this report affect the proper functioning of ntopng. Can it only be resolved by rebooting？
