### ISSUE TITLE
Rework System Sidebar

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4565]
It is requested to
- move Redis under Menu Health
- Put SNMP and Active Monitoring under a new menu item named Polling (or a better name)

**Comment by simonemainardi** [comment]
reworked as requested

<img width="347" alt="image" src="https://user-images.githubusercontent.com/3397663/95682118-dbea9e00-0be3-11eb-8120-f5dc3f73b7f3.png">

<img width="364" alt="image" src="https://user-images.githubusercontent.com/3397663/95682121-e147e880-0be3-11eb-86bf-5609f30ce25f.png">
