### ISSUE TITLE
Exporter information is still partially broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4568]
When using flow-based interfaces, the interface Id

![Screen_Shot_2020-10-12_at_09_19_21](https://user-images.githubusercontent.com/4493366/95717197-e2712800-0c6c-11eb-9303-326ae8a74843.png)

are still shown as numeric even though they can be resolved to human friendly names

![Screen_Shot_2020-10-12_at_09_21_23](https://user-images.githubusercontent.com/4493366/95717187-df763780-0c6c-11eb-9abd-1a82e7ebb6ca.png)

This has to be fixed and changed in interface name (interface Id).

Furthermore the SNMP ratio is empty

![Screen_Shot_2020-10-12_at_09_19_33](https://user-images.githubusercontent.com/4493366/95717193-e13ffb00-0c6c-11eb-8e5a-08bb2575c140.png)

even though SNMP information is available.

This ticket is somehow related to #4553

**Comment by simonemainardi** [comment]
@lucaderi I see empty column chart for the flow device.

As the note says:

![image](https://user-images.githubusercontent.com/3397663/95724171-5106b380-0c76-11eb-9f0a-7cd4296f6764.png)


Please check and report.

**Comment by simonemainardi** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/3397663/95729357-12c0c280-0c7d-11eb-9c92-64b232d1b9c3.png)

Please report about my other question

**Comment by lucaderi** [comment]
As almost nobody read notes. If not all the ingredients are present you should remove the column as having an empty column is not a good idea.

**Comment by simonemainardi** [comment]
done as requested. Now the column is hidden when unavailable, and instructions to enable the ratio are printed.
