### ISSUE TITLE
Deleting an endpoint does not delete its corresponding recipients

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4569]
When an endpoint is deleted  its corresponding endpoist must also be deleted.
A warning message is (correctly) displayed to warn about this. Clicking on OK the endpoint deletion works (an email endpoint has been deleted) but the recipient is not deleted and it is hanging on a semi-deleted state

![Screen Shot 2020-10-12 at 11 50 49](https://user-images.githubusercontent.com/4493366/95732562-338b1700-0c81-11eb-9760-62e33e08e596.png)

**Comment by simonemainardi** [comment]
Possibly fixes with https://github.com/ntop/ntopng/commit/22bc7ad57c9fb295407c36dd0911d09c44e3e9ba
