### ISSUE TITLE
Can I send CFLOW directly to ntopng?

### ISSUE THREAD

**Issue by ileshenko** [ntop/ntopng#457]
Hi,
My project is - router's DPI with L7 recognition. Router's software  #determines L7 protocol (number and name) and sends CFLOW packets. I want to display results using nTopng.

The problem, that if I pass CFLOW traffic through nprobe, nprobe ignores received L7 fields and sends to ntopng L7_PROTO:0 L7_PROTO_NAME:Unknown.

I use nprobe only for translation from udp CFLOW to tcp nropng  protocol.

Question, is it possible to send CFLOW or another udp reports directly to ntopng?

**Comment by lucaderi** [comment]
This is not possible as we have decided not to support NetFlow natively in ntopng (yet). Please see http://www.ntop.org/nprobe/advanced-flow-collection-with-ntopng-and-nprobe/

**Comment by ileshenko** [comment]
Ok!
Is it possible to display report from my own DPI tool? I have no problems to use nprobe, in case it forwards received application ID&Name.

**Comment by lucaderi** [comment]
nProbe or ntopng can do that of course.

**Comment by ileshenko** [comment]
Thanks!
What field should I use in my report, in order to inform nprobe, that application is, for example "dropbox"?

**Comment by lucaderi** [comment]
in nProbe you need to use %L7_PROTO
