### ISSUE TITLE
Endpoints and Recipients Factory Reset is Broken 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4570]
As of #4569 I have clicked on factory reset

![Screen Shot 2020-10-12 at 11 52 04](https://user-images.githubusercontent.com/4493366/95732703-66350f80-0c81-11eb-9294-c8544b45ec28.png)

but the inconsistency reported in  #4569 is still present and no reset is applied. Namely
- I do not see any endpoint
- I still see the sqlite and email recipient defined

Of couse also reset everything is broken too

![Screen Shot 2020-10-12 at 11 54 26](https://user-images.githubusercontent.com/4493366/95732980-c461f280-0c81-11eb-9179-f244c183ff86.png)

**Comment by simonemainardi** [comment]
possibly fixed with https://github.com/ntop/ntopng/commit/22bc7ad57c9fb295407c36dd0911d09c44e3e9ba

The only recipient which should be left is the sqlite one which is builtin

**Comment by lucaderi** [comment]
Fix is working but the label Everything is misleading and it must be changed to somethinbg line SNMP / Alctive Monitoring / ..

**Comment by simonemainardi** [comment]
Label has been changed to "All". Everything means not only SNMP / Active Monitoring / etc but "Everything", that is, any ntopng key stored in Redis.
