### ISSUE TITLE
Extend labels length as space is available

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4571]
![Screen Shot 2020-10-12 at 12 03 34](https://user-images.githubusercontent.com/4493366/95733947-25d69100-0c83-11eb-99dc-e31feb8e3dd2.png)

**Comment by simonemainardi** [comment]
The issue asks to adaptively fill the available space, not just to change a number 

https://github.com/ntop/ntopng/blob/23aa34904dc36c255e7a5251d14b3ccc58b6c2d8/httpdocs/js/config_callbacks/scripts-list-utils.js#L1520

**Comment by gabryon99** [comment]
As @lucaderi said I expanded the limit to 120 characters.

**Comment by simonemainardi** [comment]
on my MBP 13" now every line wraps:

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/3397663/95766360-736af200-0cb3-11eb-9736-a764154473e9.png">

**Comment by lucaderi** [comment]
Understood but ay least you most messages are now no longer cut.
