### ISSUE TITLE
Invalid value in recipient usage

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4574]
![Screen_Shot_2020-10-12_at_17_38_45](https://user-images.githubusercontent.com/4493366/95765284-ec694a00-0cb1-11eb-8065-154726bff53b.png)

The above picture is hard to read
- all labels are "Default"
- there is an undefined value that makes hard to understand to what this setting is applied

**Comment by simonemainardi** [comment]
Don't forget about https://github.com/ntop/ntopng/issues/4375#issuecomment-705365497

**Comment by simonemainardi** [comment]
Please follow Luca's suggestion:

This page is unclear: It's filled with word Default and it is unclear that word refer to pool as pool is written nowhere

![image](https://user-images.githubusercontent.com/3397663/95894375-4983ff00-0d89-11eb-8745-75c49643131d.png)

**Comment by lucaderi** [comment]
@gabryon99 I believe the suggestions from @simonemainardi make sense. Tiny changes such as changing the title to "Pools using Recipient XXXX" can help

**Comment by lucaderi** [comment]
Fixed
