### ISSUE TITLE
ndpi_http_method2str and ndpi_http_method2str

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#4579]
`g++ -std=c++0x -g -O2 -I/home/mikhail/ntopng/ntopng -I/home/mikhail/ntopng/ntopng/include -I/usr/local/include -Wall -D_FILE_OFFSET_BITS=64 -I/usr/include/hiredis -I/usr/include/hiredis -I/home/mikhail/ntopng/ntopng/third-party/mongoose -I/usr/local/include -I/usr/local/include/json-c   -I/usr/local/include/ndpi -I/home/mikhail/ntopng/ntopng/third-party/lua-5.3.5/src  -isystem /usr/include/mit-krb5 -I/usr/include/pgm-5.2 -I/usr/include/mysql  -Wno-address-of-packed-member -Wno-unused-function -I/home/mikhail/ntopng/ntopng -I/home/mikhail/ntopng/ntopng/include -I/usr/local/include -I/home/mikhail/ntopng/ntopng/third-party/http-client-c/src/  -I/usr/include/openssl  -DDATA_DIR='"/usr/local/share"' -I/home/mikhail/ntopng/ntopng/third-party/libgeohash -I/home/mikhail/ntopng/ntopng/third-party/patricia   -c src/PacketDumperTuntap.cpp -o src/PacketDumperTuntap.o
In file included from /home/mikhail/ntopng/ntopng/include/ntop_includes.h:389,
                 from src/PacketDumperTuntap.cpp:22:
/home/mikhail/ntopng/ntopng/include/Flow.h: In member function ‘const char* Flow::getHTTPMethod() const’:
/home/mikhail/ntopng/ntopng/include/Flow.h:608:65: error: ‘ndpi_http_method2str’ was not declared in this scope; did you mean ‘ndpi_http_method’?
  608 |   inline const char* getHTTPMethod()  const { return isHTTP() ? ndpi_http_method2str(protos.http.last_method) : (char*)"";        };
      |                                                                 ^~~~~~~~~~~~~~~~~~~~
      |                                                                 ndpi_http_method
make: *** [Makefile:146: src/PacketDumperTuntap.o] Ошибка 1
`

**Comment by simonemainardi** [comment]
Your nDPI sources are outdated. Update nDPI sources.
