### ISSUE TITLE
ntopng build failure on windows

### ISSUE THREAD

**Issue by sdkjain** [ntop/ntopng#458]
Hi,

I tried to build ntoNg code and Ndpi code on Windows 10. I am getting below error respectively:

NtopNG build faiilure is below:
_$ ./autogen.sh
Wait please...
Can't locate Autom4te/ChannelDefs.pm in @INC (you may need to install the Autom4                                                                                                    te::ChannelDefs module) (@INC contains: C:/PROGRA~2/GnuWin32/autoconf/share/auto                                                                                                    conf /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_p                                                                                                    erl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_                                                                                                    perl .) at /c/Program Files (x86)/GnuWin32/bin/autoreconf line 42.
BEGIN failed--compilation aborted at /c/Program Files (x86)/GnuWin32/bin/autorec                                                                                                    onf line 42.
_

Ndpi build faiilure is below:
_$ ./autogen.sh
./autogen.sh: line 12: test: too many arguments
./autogen.sh: line 17: test: too many arguments
./autogen.sh: line 22: test: too many arguments
./autogen.sh: line 27: test: too many arguments
Can't locate Autom4te/ChannelDefs.pm in @INC (you may need to install the Autom4te::ChannelDefs module) (@INC contains: C:/PROGRA~2/GnuWin32/autoconf/share/autoconf /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at /c/Program Files (x86)/GnuWin32/bin/autoreconf line 42.
BEGIN failed--compilation aborted at /c/Program Files (x86)/GnuWin32/bin/autoreconf line 42.
./autogen.sh: line 33: ./configure: No such file or directory
_

Please help is solving this issue.

Thanks,
Sourabh

**Comment by lucaderi** [comment]
I have never compiled ntopng using the GNU tools for Windows. I use .NET and it works for me. If you happen to make it work with GNU tools and you want to share a patch I would be glad to evaluate it.

**Comment by sdkjain** [comment]
Hi Luca,

Thanks for the update on the issue. Could you please let me know the build steps using .Net as I didnt found that anywhere?

Thanks,
Sourabh.

**Comment by lucaderi** [comment]
@sdkjain You need to create a .net project on your PC, add all the dependencies (nDPI etc) and compile it. it's time consuming so you better use our binary packages unless you know how to do it.

**Comment by sdkjain** [comment]
I am interested in contributing to the project so I want to understand the windows code and build stuffs.
It would be great help if u can share me the steps for the same.
I will be preparing a doc/readme and contribute here as well.

**Comment by lucaderi** [comment]
Please move to Linux/OSX, contribute and then we'll periodically port it to windows. Doing it natively on Windows is time consuming for us.

**Comment by ShanonDaniel** [comment]
Hi Luca!
Where can I find the build method to compile ntopng on windows 10?
![Uploading 1.jpg…]()
