### ISSUE TITLE
Misleading username and password specified

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4581]
This is a screenshot taken from Chrome (other browsers apply)

![Screen Shot 2020-10-14 at 11 31 10](https://user-images.githubusercontent.com/4493366/95970925-d1611c00-0e10-11eb-8958-6e370ddc8c2c.png)

I this case the endpoint has been configured WITHOUT username and password. Opening the edit window it autofills the form with ntopng's username and password. Beside the fact that this is misleading, the main problem is that clicking on the Edit button it saves this information jeoparizing the configuration. This behaviour needs to be fixed.

**Comment by gabryon99** [comment]
@lucaderi can you check if the autocomplete is still enabled?

**Comment by lucaderi** [comment]
Fixed
