### ISSUE TITLE
Info in flows/hosts is misleading

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4582]
![image](https://user-images.githubusercontent.com/4493366/96009823-67149f80-0e41-11eb-831c-a964f279b1ea.png)

In ntopng badges are used in alerts and not as drill down button. It is requested to changed the "Info" badge used in
- Hosts (hosts_stats.lua)
- Active Flows  (flows_stats.lua)
(please check if there are other locations that need to be adapted) 

wtih the magnify lens icon also used in alert dashboard. This will make ntopng more readeable and easy to use.

**Comment by gabryon99** [comment]
I've updated the info button style, see also the commit: https://github.com/ntop/ntopng/commit/3a90817f1d6ef111ff5d39a11561d3e5a2b1cfeb

**Comment by lucaderi** [comment]
Verified as fixed
