### ISSUE TITLE
Host pools configuration is not flexible

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4584]
In large companies configuring host in pools is too time consuming. Everybody has a list of hosts coming from the device inventory.

![Screen Shot 2020-10-14 at 17 27 50](https://user-images.githubusercontent.com/4493366/96010963-ae4f6000-0e42-11eb-8350-e97aa738a535.png)

It is requested to add the ability to import a list of networks in the above page that is loaded in the selected pool

**Comment by lucaderi** [comment]
@simonemainardi You need to improve the import API and make it faster. All the rest is done

**Comment by simonemainardi** [comment]
Implemented in e7a6682aba69e93f6db5ddf04d0b134adf404d65
