### ISSUE TITLE
Extend Flow Status Drilldown

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4588]
![Screen Shot 2020-10-14 at 17 51 17](https://user-images.githubusercontent.com/4493366/96013740-e1472300-0e45-11eb-87d2-f11d4ef86958.png)

The difference between an alerted and a misbehaving flow is sometime hard to understand for users. It is requested to add a new entry that sounds like "Anything but Normal" that displays both Alerted and Misbehaving flows.

**Comment by simonemainardi** [comment]
Alerted and misbehaving flows have now been merged together into just "Alerted Flows" (https://github.com/ntop/ntopng/issues/4596).

Now you can obtain the "Anything but Normal" behavior just by selecting "Alerted" in the flow status dropdown:

![image](https://user-images.githubusercontent.com/3397663/96721723-d55ee200-13ac-11eb-8a13-0267b00d0781.png)

Moreover, to further understand alerted flows, an additional alerted severity has been added.

![image](https://user-images.githubusercontent.com/3397663/96721886-063f1700-13ad-11eb-8a34-18dd22a91cee.png)

Severity will help you in understanding warnings, errors, or just notices among all alerted flows.
