### ISSUE TITLE
Add a bitmap to prevent specific hosts to trigger specific alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4589]
Some devices cannot be reconfigured or upgraded. So they keep generating alerts such as "Old TLS version" or "HTTP Numeric host". This creates a lot of alerts that are useless and that prevent from understanding exactly what is happening.

It is requested to implement the ability to specify what risks have to be ignored (i.e. they are blanked out). This is a general setup valid for all hosts
![Screen Shot 2020-10-14 at 17 57 39](https://user-images.githubusercontent.com/4493366/96014534-ca550080-0e46-11eb-95a3-5197ce56c63d.png)

This will allow via host pools to specify different setups based on the host type and behaviour.

**Comment by simonemainardi** [comment]
This is implemented. Flow risks can be selectively enabled/disabled from the user script configuration modal

![image](https://user-images.githubusercontent.com/3397663/96846325-08a77c80-1452-11eb-84d2-2cf2b4fa043a.png)
