### ISSUE TITLE
Periodic activities are broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4590]
![Screen Shot 2020-10-14 at 18 01 34](https://user-images.githubusercontent.com/4493366/96015707-28ceae80-0e48-11eb-9883-dbc03f8336f2.png)

This is a new bug introduced with/after https://github.com/ntop/ntopng/commit/d1f974857cee3c045df647f80772182cb68d2f3d

It can reproduced on a mac starting ntopng (no -i) on all interfaces. With one interface it does not show up

**Comment by simonemainardi** [comment]
This is unrelated to d1f9748.

A pool of 2 threads is reserved for the execution of these activities. See

```
    periodic_user_scripts_pool = new ThreadPool(false, 2);
    { PERIODIC_USER_SCRIPTS_PATH,            5,    60, periodic_user_scripts_pool, false, false, true,  true  },
```

With a high number of interfaces, those two threads may not be enough to execute `periodic_user_scripts.lua` for  all interfaces in time so you end up in having these errors.

Would you increase the number of threads? Please comment.

**Comment by lucaderi** [comment]
Verified as fixed
