### ISSUE TITLE
SYN probing plugin is too picky

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4591]
![Screen Shot 2020-10-14 at 18 11 48](https://user-images.githubusercontent.com/4493366/96016207-c629e280-0e48-11eb-8e1f-cf400ecb6141.png)

As you see from the alert this is an invalid alert generated when connecting to the ntopng web GUI. Issues
- this can be a warning (at most) but not an error
-  I propose to create an host alert when too many conenctions are not happening but not an alert when a connection fails

**Comment by simonemainardi** [comment]
Severity has been lowered to info for this kind of flow alerts. Suspicious TCP SYN probings can still be seen, in an aggregated way, on a per-host basis. This is done with user scripts:

![image](https://user-images.githubusercontent.com/3397663/96846139-c5e5a480-1451-11eb-988a-377369a97d99.png)
