### ISSUE TITLE
Device connection disconnection must be tuned

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4593]
![Screen_Shot_2020-10-14_at_15_21_32](https://user-images.githubusercontent.com/4493366/96017196-fe7df080-0e49-11eb-9d87-665e73da2930.png)

As you can see from the picture a different timeout must be used for alerts about connection/disconnection as it generates too many alerts

**Comment by simonemainardi** [comment]
will be solved as part of https://github.com/ntop/ntopng/issues/4614

**Comment by simonemainardi** [comment]
As discussed, device disconnecion/connection has now been moved into a per-interface user script:

![image](https://user-images.githubusercontent.com/3397663/96890069-918cdb00-1487-11eb-80c6-4ae39a984415.png)


Same for host pools.

Note that remote/local hosts timeouts are used to generated device connection/disconnection alerts:

![image](https://user-images.githubusercontent.com/3397663/96890175-af5a4000-1487-11eb-88e9-e08b504138b6.png)


In IOT/industrial networks, where devices seldomly send packets, timeouts above may need to be increased to avoid the behavior highlighted in the issue. This is the correct way to avoid the generation of too many alerts.
