### ISSUE TITLE
Flow counter wrap bug (?)

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4597]
The above pictue has two issues
1. no timeseries displayed
2. possible counter wrap bug

![ntop](https://user-images.githubusercontent.com/4493366/96104506-384a0800-0ed9-11eb-9e47-d3d426f41ad6.png)

**Comment by cardigliano** [comment]
This looks like an issue when computing counters delta somewhere in the code. A few safety checks have been put in place to identify the issue, but no luck yet as it seems this is not easily reproducible.

**Comment by simonemainardi** [comment]
No longer reproducible. Will reopen if necessary.

**Comment by junaid-soomro-ivolve** [comment]
I would like to bring a bug in to your attention folks. Consider a host 172.16.16.12. We query time-series database to fetch bytes for last week. The result you get will be aggregated of course but when you calculate you will notice that ntop misses the current day. Which means it gives you data for 6 days aggregated and then you have to separately pull that 7th day(current day) data. Your welcome.
