### ISSUE TITLE
Rework exporters page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4598]
The flow exporters page needs to be improved (/lua/pro/enterprise/flow_device_info.lua?ip=XXXX). Main problems
- bottom description is too long: almost nobody will read it
- it is not integrated with SNMP
- the rightmost column appears/disappears based on the configuration that takes a few steps (read it is all but user friendly)
- the ratio description is not intuitive
- even if data is enabled and the column is shown, it is not populated as it should be

![Screen_Shot_2020-10-15_at_18_09_28](https://user-images.githubusercontent.com/4493366/96157710-ef16aa00-0f12-11eb-81ef-18a4871e1258.png)

Things to change
- the rightmost ratio column is empty even though everything is enabled (this is why the column is shown). As you can see we have waited enough to see data polled
- the table must be sortable as all other ntopng tables
- the first column (index) must become a HREF and bring the user to the SNMP page for such interface (i.e. http://XXXXX:3000/lua/pro/enterprise/snmp_interface_details.lua?host=YYYYY&snmp_port_idx=ZZ)
- ratio must be printed in black when >= 0.8, red otherwise (as we do with goodput)
- he rightmost ratio column must be enabled all the time. In case preferences are not set properly for displaying it, an alert window similar (but not alike) to
![Screen Shot 2020-10-15 at 18 24 02](https://user-images.githubusercontent.com/4493366/96158281-a7445280-0f13-11eb-9376-de0a48611547.png) must appear with a configure button on it that will set all required preferences in one shot without the user to go to preferences and click a few times
- the bottom note can be removed or at least dramatically reduced in size.

**Comment by simonemainardi** [comment]
Additional things to do:
- REST API responses.

Endpoints:

```
-rw-rw-r-- 1 simone simone 2.7K Oct 20 17:31 pro/scripts/lua/rest/v1/get/flowdevice/stats.lua
-rw-rw-r-- 1 simone simone 2.2K Oct 20 17:28 pro/scripts/lua/rest/v1/get/flowdevices/stats.lua
-rw-rw-r-- 1 simone simone 3.9K Oct 20 18:30 pro/scripts/lua/rest/v1/get/sflowdevice/stats.lua
-rw-rw-r-- 1 simone simone 2.2K Oct 20 18:13 pro/scripts/lua/rest/v1/get/sflowdevices/stats.lua
```

Must return a standard API response, ending with `rest_utils.answer(rc, data)`: `data` must go inside the rest API response and not directly printed as json.encode(data).

- Check columns alignment (numbers aligned to right, chart to center, etch), sort and formatting for pages

```
-rw-rw-r-- 1 simone simone 2.2K Oct 20 17:28 pro/scripts/lua/enterprise/flowdevice_details.lua
-rw-rw-r-- 1 simone simone 2.4K Oct 20 16:52 pro/scripts/lua/enterprise/flowdevices_stats.lua
-rw-rw-r-- 1 simone simone 2.4K Oct 20 18:33 pro/scripts/lua/enterprise/sflowdevice_details.lua
-rw-rw-r-- 1 simone simone 2.4K Oct 20 16:11 pro/scripts/lua/enterprise/sflowdevices_stats.lua
```

- Make a single button to do all the necessary operations to enable the ratio

**Comment by simonemainardi** [comment]
Also note that ratio column must be shown/hidden depending on the boolean flag `is_ratio_available`

**Comment by simonemainardi** [comment]
Also hide Zero errors:

![image](https://user-images.githubusercontent.com/3397663/96839992-2f61b500-144a-11eb-8409-3ff97f7becb0.png)

**Comment by lucaderi** [comment]
Verified
