### ISSUE TITLE
How to divide the equipment.

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#4601]
Is there any quick way to partition devices, using IP or mac partition is too slow, we have over 1000 hosts.

**Comment by simonemainardi** [comment]
Please, explain. What is the criterion you would like to use to divide hosts in pools? Did you know you can use CIDR-prefixes to do the partition?

Give as many details as possible.

**Comment by MaoPann** [comment]
Ok.I already knew that.Thanks|
