### ISSUE TITLE
File Uploads blocking with NEdge

### ISSUE THREAD

**Issue by vijaytejak** [ntop/ntopng#4602]
Hi people,

I am using the NEdge Enterprise version, which is awesome.

I would like to know if there is any method to block file uploads into the internet (well known and generic websites).

Example:- If a user tries to upload any file (Media, txt, pdf, png, etc..) into any websites like dropbox, google drive, generic file uploads websites (easyupload.io, etc..), the NEdge should not allow file uploads, can anyone help me how to do this with NEdge?

@simonemainardi can you look into this request.
TIA.

**Comment by simonemainardi** [comment]
Consider that now, with encryption increasingly used, file uploads are likely to take place over TLS.

nEdge/ntopng don't decrypt TLS. They are able to reliably determine the layer-7 application of the encrypted traffic, but they won't tell you the contents of the encrypted connection.

Given that being able to reliably block a file upload would require access to the unencrypted connection, you won't be able to do that with nEdge/ntopng. In addition, we believe it doesn't robust/consistent approach to do this. Even if you would have a tool to decipher TLS, an attacker could use its own encryption protocol or obfuscate the data in a way that you wouldn't be able to see it.

Said that, there exists certain heuristics that may be used and can be effective in doing what you are looking for.

For example, just by looking at the amount of data transferred from the client to the server, you can an do an educated guess whether a large volume of data (file upload?) was moved from the client to the server. This is effective unless the attacker split the data into multiple smaller chunks. In this case you should look at the number of connections.

To addess this, ntopng/nEdge provide you a way to receive notification when a large transfer is detected using the concept of "Elephant Flows":

![image](https://user-images.githubusercontent.com/3397663/96422705-a6077400-11f8-11eb-971e-77755e87f0b4.png)

Using nEdge/ntopng, you can also block certain protocols from being performed, either as a server or as a client:

For example, you can block Dropbox client connections for "Computer"

![image](https://user-images.githubusercontent.com/3397663/96422870-df3fe400-11f8-11eb-8a2e-8806c6c71bbe.png)

Blocking "Dropbox" would block everything but if you want to prevent file uploads, blocking Dropbox may still be good.

So in essence, you won't find a tool to block file uploads but you can still use ntopng/nEdge to implement heuristics:
- use elephant flows
- block application protocols - e.g., block dropbox, google drive, easyupload.io (cloud applications)

![image](https://user-images.githubusercontent.com/3397663/96423275-668d5780-11f9-11eb-9f0b-97361353f56b.png)
