### ISSUE TITLE
Restart modal should be standardized

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4608]
Currently, restart confirmation is shown as 

![image](https://user-images.githubusercontent.com/3397663/96693247-48edf880-1387-11eb-9e15-d0540e46de61.png)

This should be shown as any other modal used inside ntopng.

**Comment by gabryon99** [comment]
I've tested the code inside a VM containing Ubuntu 20.04

**Comment by simonemainardi** [comment]
This is what I get:

![image](https://user-images.githubusercontent.com/3397663/96719212-67fd8200-13a9-11eb-9bd4-dfbc6c9d1718.png)


- product name is missing from modal title
- modal body should be red
- modal button has no text
- else?

**Comment by gabryon99** [comment]
<img width="503" alt="Screenshot 2020-10-21 at 14 37 05" src="https://user-images.githubusercontent.com/14114916/96720327-e6a6ef00-13aa-11eb-8adb-f575deac3d5a.png">

- Added product name inside the title
- Now the body is red
- The button has the text
- Nothing else 

Commit: https://github.com/ntop/ntopng/commit/3632494dba8774fae2b8f407abf5092971e143da

**Comment by simonemainardi** [comment]
next time open the modal at least one time rather than blindly committing code
