### ISSUE TITLE
Almost invisible button (restart ntopng)

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4610]
![Screen Shot 2020-10-21 at 14 50 49](https://user-images.githubusercontent.com/4493366/96722051-3b4b6980-13ad-11eb-8849-a3435e879289.png)

**Comment by gabryon99** [comment]
The issue was fixed in: https://github.com/ntop/ntopng/issues/4608

**Comment by simonemainardi** [comment]
already reported and solved in https://github.com/ntop/ntopng/issues/4608#issuecomment-713532609
