### ISSUE TITLE
Zoom flows being detected as bittorrent

### ISSUE THREAD

**Issue by tuarego** [ntop/ntopng#4616]
Hi,
Just to report that some zoom flows are being detected as bittorrent flows. Same flow appears twice matching both protocols.
Version: 4.1.200603 (10451) - Enterprise M Edition
nDPI: 3.3.0-2446-16ca697
Best regards,
Pedro.

**Comment by lucaderi** [comment]
This is an old nDPI. Please update with the latest version and if nor working please file a ticket on nDPI (not ntopng) where yo attach a pcap file
