### ISSUE TITLE
A pair of TAP interfaces (RX only + TX only) are all considered as RX

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#4617]
I read into the [documentation](https://www.ntop.org/guides/ntopng/cli_options.html) that when two directions (TX+RX) of a network TAP need to be merged together we can use directly the 2 interfaces, in instance, in this way:  `-i eth0,eth1`
In my environment I have 8 tap pairs (rx/tx) configured in this way:
```
--interface zc:101@0,zc:201@0
--interface zc:102@0,zc:202@0
--interface zc:103@0,zc:203@0
--interface zc:104@0,zc:204@0
--interface zc:105@0,zc:205@0
--interface zc:106@0,zc:206@0
--interface zc:107@0,zc:207@0
--interface zc:108@0,zc:208@0
```
Where:
-)  `zc:10X@0` are the TAP interfaces with rx traffic
-)  `zc:20X@0` are the TAP interfaces with tx traffic

What I aspect is that the 2 traffic flows are considered accordingly. What I see in ntopng is that all the traffic is considered as RX traffic as you can see here (point 1 and 2):
![Screenshot_20201022_143040](https://user-images.githubusercontent.com/14093378/96875765-e9234a80-1477-11eb-9865-65333036f258.png)

I tried all possible combinations but I have only RX traffic into the ntopng statistics :-(

Is this the corrected behavior or I've made a mistake into the configuration?
What do you think?

Thanks :-)

P.S.: If this behaviour is correct I think should be useful have the possibility to configure TAP interface as:
```
--interface zc:RX_traffic@N,zc:TX_traffic@N
```
and consider the traffic direction accordingly. Is this possible?

**Comment by cardigliano** [comment]
Please check the next build

**Comment by gianogli** [comment]
It works in the last build I tested.

Thanks! :-)
