### ISSUE TITLE
Request for system_interfaces_stats.lua web page

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#4618]
As you can see into this image
![Screenshot_20201022_153636](https://user-images.githubusercontent.com/14093378/96879833-cc3d4600-147c-11eb-8bed-b0a7213966ce.png)
is not easy to understand the correct percentage on "Dropped Packets" column when are very low.

Could you modify this behavior?

Could be also useful have the possibility here to reset all the counters ("All Counters" and "Drops Only") for all interfaces at once (with 2 button as into if_stats.lua web page).

What do you think?

Thanks... :-)

**Comment by simonemainardi** [comment]
Style is invalid, e.g., buttons must be red (do the same style as in the alerts page)

![image](https://user-images.githubusercontent.com/3397663/109953558-82912180-7ce0-11eb-958c-778e2ed1ea50.png)

A modal asking confirmation must be open.

Use isAdministrator() here: https://github.com/ntop/ntopng/commit/c925cfaf18f405f4c4562b8697a5c04f3403acb6#diff-7b6880f2b90b92b10326c33e560cf7cfe514a133af1cb19cb1987a88e28aed64R24
