### ISSUE TITLE
Lost all packets after a while when a core reach 100%

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#4620]
Our ntopng is configured to manage 8 interfaces.
It worked well for about 7/8 hours until a core steadily reached 100% (before was 40-60%). At this point only the interface bound to this core started to lose all packets. 
In the last 6 hours we lost all the packets from this interface. The other 7 interfaces are working like a charm.

No error messages in the console. We have only some alerts in the interface window as:
![Screenshot_20201023_095107](https://user-images.githubusercontent.com/14093378/96971371-4de0b280-1515-11eb-9b61-84e3b0f6fe23.png)
and:
![Screenshot_20201023_095249](https://user-images.githubusercontent.com/14093378/96971540-8aaca980-1515-11eb-9af8-4bf2dcf179ad.png)

Do you need other information?

Thanks... :-)

PS: ntopng Enterprise M v.4.1.201022

**Comment by cardigliano** [comment]
@gianogli any chance we can ssh to this box?

**Comment by gianogli** [comment]
Yes, sure, I already have your e-mail. I'll write you in the next minutes...
Thanks... :-)

**Comment by gianogli** [comment]
Update: now the interfaces with the same issue are 2
(Now we  have 2 cores at 100% and no packets on the interfaces bound to these cores)

**Comment by cardigliano** [comment]
@gianogli I am taking a look at your box right now

**Comment by gianogli** [comment]
@cardigliano ok, thanks...

**Comment by lucaderi** [comment]
Any news?

**Comment by cardigliano** [comment]
The loop has not been reproduced yet using a binary with debug symbols (even with -O2), however @gianogli also reported a crash. now ntopng is running with gdb, waiting for a loop/crash.

**Comment by cardigliano** [comment]
Reproduced and fixed. Please confirm.

**Comment by gianogli** [comment]
Yes, now ntopng (last dev binary) is up and running without issues. No crashes or loops in the last 3 hours.
@cardigliano thanks for your great support... ;-)
