### ISSUE TITLE
ntopng 4.0 compile error

### ISSUE THREAD

**Issue by PHCSJC** [ntop/ntopng#4624]
My Env: debian 9+ntopng 4.0 stable+nDPI 3.4 stable, compile error, help, thanks!

g++ -g -Wall -I/usr/src/ntopng-4.0 -I/usr/src/ntopng-4.0/include -I/usr/local/include -I /usr/src/ntopng-4.0/third-party/hiredis -I/usr/src/ntopng-4.0/third-party/mongoose -I/usr/include/json-c  -I../nDPI/src/include -I../nDPI/src/lib/third_party/include -I/usr/src/ntopng-4.0/third-party/lua-5.3.5/src   -I/usr/include/mysql  -I/usr/src/ntopng-4.0 -I/usr/src/ntopng-4.0/include -I/usr/local/include -I/usr/src/ntopng-4.0/third-party/http-client-c/src/  -I/usr/include/openssl  -DDATA_DIR='"/usr/local/share"' -I/usr/src/ntopng-4.0/third-party/libgeohash -I/usr/src/ntopng-4.0/third-party/patricia   -c src/ContainerStats.cpp -o src/ContainerStats.o
src/Flow.cpp: In member function ‘void Flow::processDetectedProtocol()’:
src/Flow.cpp:373:25: error: ‘union ndpi_flow_struct::<anonymous>’ has no member named ‘mdns’; did you mean ‘dns’?
     if(ndpiFlow->protos.mdns.answer[0] != '\0' && !protos.mdns.answer)
                         ^~~~
src/Flow.cpp:374:52: error: ‘union ndpi_flow_struct::<anonymous>’ has no member named ‘mdns’; did you mean ‘dns’?
       protos.mdns.answer = strdup(ndpiFlow->protos.mdns.answer);
                                                    ^~~~
src/Flow.cpp: In member function ‘void Flow::fillZmqFlowCategory(const ParsedFlow*, ndpi_protocol*) const’:
src/Flow.cpp:3916:86: error: cannot convert ‘long unsigned int*’ to ‘ndpi_protocol_category_t*’ for argument ‘4’ to ‘int ndpi_match_custom_category(ndpi_detection_module_struct*, char*, u_int, ndpi_protocol_category_t*)’
     if(ndpi_match_custom_category(ndpi_struct, (char*)dst_name, strlen(dst_name), &id) == 0)
                                                                                      ^
Makefile:148: recipe for target 'src/Flow.o' failed
make: *** [src/Flow.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by simonemainardi** [comment]
Your nDPI version is outdated. Please, update it. Go into the nDPI source folder and type `git pull`

**Comment by ioxera** [comment]
I encountered the same problem. I can complete the compilation with ntopng v4.2 + NDPI v3.4 without any errors, but the same error was reported with ntopng v4.2 + NDPI v3.4. When I try to use other versions of NDPI（dev\v3.2\v3.0), I will make different errors, so I don't think that the version of NDPI is too old, I have no solution to this problem.
