### ISSUE TITLE
How look host everyday total bytes?

### ISSUE THREAD

**Issue by PHCSJC** [ntop/ntopng#4625]
I want to look host everyday toal bytes, for instance host 192.168.1.10 yesterday toal bytes, Not all days total byes?
How look? thanks!
ntopng version is v3.8.1

**Comment by simonemainardi** [comment]
- Make sure your host is `local` (see option `-m`)
- Enable local host timeseries from 
![image](https://user-images.githubusercontent.com/3397663/97146902-ec188680-1768-11eb-91a6-8335dd43b82e.png)

- Use the chart page and specify an interval of interest with begin/end dates.
![image](https://user-images.githubusercontent.com/3397663/97146835-d3a86c00-1768-11eb-828d-b2ff75221617.png)

**Comment by PHCSJC** [comment]
Hi, I can't see Begin and End time, this function is just in version 4.0?

**Comment by simonemainardi** [comment]
Yes. Pro.
