### ISSUE TITLE
ERROR: InfluxDB setup failed

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#4627]
26/Oct/2020 17:11:23 [timeseries.lua:14] [influxdb.lua:1938] ERROR: InfluxDB setup failed
26/Oct/2020 17:11:23 [timeseries.lua:14] [influxdb.lua:456] ERROR: Unexpected query error: not executed, in query #22: CREATE CONTINUOUS QUERY "iface:alerted_flows__1d" ON ntopng BEGIN SELECT (SUM(num_flows) / 86400) as num_flows INTO "1d"."iface:alerted_flows" FROM ( SELECT NON_NEGATIVE_DIFFERENCE(num_flows) as num_flows FROM "autogen"."iface:alerted_flows" ) GROUP BY time(1d),ifid END

**Comment by simonemainardi** [comment]
Already fixed in https://github.com/ntop/ntopng/commit/58eb081b3ac124a80f0dcb562e25eeeee805610f

Update and it will work.
