### ISSUE TITLE
Add ELK flow drops

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#463]
Please add traces for flow drops when importing them in ELK, similar to what happens on nProbe

**Comment by lucaderi** [comment]
@ValentinaViscarelli Please note that if you parse the HTTP response (from ELK) you have a report about flows now imported for various errors. Instead for ELK export, we need to back port the code from nprobe where we keep a linked list of messages instead of using redis. When the list is too long we count flow export drops (actually we could to be smarter and avoid exporting flows at all to ELK if the list is already too long).

**Comment by simonemainardi** [comment]
Implemented in 8a367fa
