### ISSUE TITLE
Hosts and Applications Tabs not working

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4632]
In the community dashaboard the following pages are broken
![Screen Shot 2020-10-27 at 15 27 03](https://user-images.githubusercontent.com/4493366/97315370-f326be00-1868-11eb-8ee7-db4e04fc1454.png)
![Screen Shot 2020-10-27 at 15 26 54](https://user-images.githubusercontent.com/4493366/97315373-f3bf5480-1868-11eb-9033-fb6a4db4024e.png)

**Comment by simonemainardi** [comment]
All files were moved to the REST API in https://github.com/ntop/ntopng/commit/192a043ae51739a194485161b329fc802405cb23.

Please motivate why you have re-introduced them, actually causing identical files to exist two times in the code-base.

```
git diff -- scripts/lua/if_stats_ndpi.lua scripts/lua/rest/v1/get/interface/l7/stats.lua
```

**Comment by gabryon99** [comment]
I replaced the endpoint to get data for the TopApplication chart and removed `if_stats_ndpi.lua`
