### ISSUE TITLE
Inconsistent license status reported

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4636]
![Screen_Shot_2020-10-27_at_21 09 11](https://user-images.githubusercontent.com/4493366/97365751-79152a00-18a6-11eb-835e-f5c395fe6130.png)

When a licensed copy of ntopng is started with --community the output on the GUI is inconsistent and it must be reported correctly to the user.

**Comment by simonemainardi** [comment]
Fixed. Now a notification is also shown to inform the user that, in order to apply licenses, --community must be removed

![image](https://user-images.githubusercontent.com/3397663/97411483-9d9df000-1900-11eb-9cdf-774e93c05887.png)
