### ISSUE TITLE
Space should be ignored in the search field

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4638]
![Screen Shot 2020-10-27 at 23 14 25](https://user-images.githubusercontent.com/4493366/97367882-30f80680-18aa-11eb-8406-4649a7047a26.png)
![Screen Shot 2020-10-27 at 23 14 18](https://user-images.githubusercontent.com/4493366/97367886-32293380-18aa-11eb-8fab-bc0e5327aaf2.png)

**Comment by simonemainardi** [comment]
broken

![image](https://user-images.githubusercontent.com/3397663/97431983-8ae4e480-191b-11eb-8abb-763b8c315de3.png)


also note that if you need the trim function, use the already existing `trimSpace`

**Comment by simonemainardi** [comment]
This is still not fixed:

![image](https://user-images.githubusercontent.com/3397663/97482323-4d517d00-1956-11eb-9dc6-053e63914df7.png)


Moreover, you've patched a third-party file without a single comment

```
/* =============================================================
 * bootstrap3-typeahead.js v4.0.2
 * https://github.com/bassjobsen/Bootstrap-3-Typeahead
 * =============================================================
 * Original written by @mdo and @fat
 * =============================================================
```

Hence, chances are your changes will be lost as soon as the third-party file is updated. Please, motivate your choice and fix for the correct behavior.

**Comment by simonemainardi** [comment]
Comments added in https://github.com/ntop/ntopng/commit/c34a2fe7350c76fac5f1ef0b78f3237690629447
