### ISSUE TITLE
[Regression] Overlapping text inside graphs

### ISSUE THREAD

**Issue by MatteoBiscosi** [ntop/ntopng#4641]
![photo5821343650628613656](https://user-images.githubusercontent.com/49585191/97417265-bf4ea580-1907-11eb-8975-1c3ce5288190.jpg)
In some graphs the text is overlapping, like the screenshot shows.

**Comment by lucaderi** [comment]
As the chart call
http://XXXX:3000/lua/rest/v1/get/host/dscp/stats.lua?direction=sent&ifid=YYY&host=ZZZZZZ

The fix needs to modify this call and make sure that if there are multiple slices <= 1% they are all collapsed into Other.

**Comment by gabryon99** [comment]
@lucaderi I've created a function that collapses multiple slices into Other.

**Comment by lucaderi** [comment]
Looks good now

**Comment by lucaderi** [comment]
![image](https://user-images.githubusercontent.com/4493366/100443593-45e2d800-30aa-11eb-97dd-26a6bf5dc89d.png)
![image](https://user-images.githubusercontent.com/4493366/100443600-4aa78c00-30aa-11eb-89a7-6c00aa917787.png)

@gabryon99 More broken charts
