### ISSUE TITLE
New windows build 3kb .iss file?

### ISSUE THREAD

**Issue by DrToxo** [ntop/ntopng#4642]
Hi, ive just been to grab the new windows build and its a 4kb file ntopng-4.1.201027-x64.iss?
https://packages.ntop.org/

Was expecting typical installer, or have I jumped the gun and its not quite ready yet?

Cheers

**Comment by lucaderi** [comment]
Fixed. Please update sorry for the trouble

**Comment by DrToxo** [comment]
No trouble at all!!!  Thanks!
