### ISSUE TITLE
Invalid IP address reported in SNMP Interface Table

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4647]
![Screen_Shot_2020-10-29_at_08_59_57](https://user-images.githubusercontent.com/4493366/97541301-38f89900-19c5-11eb-8b7f-2f177617056a.png)

If the MAC address is the one of a router the IP address, you must indicate that in the table and avoid putting one of the addresses as this is wrong

**Comment by simonemainardi** [comment]
fixed
