### ISSUE TITLE
ntopng warning and no traffic is seen on ntop web ui

### ISSUE THREAD

**Issue by chigurupati** [ntop/ntopng#465]
Hello,

I am running my nprobe and ntopng on 2 different terminals of my raspberry pi 2.

**my commands:**
on terminal 1: nprobe --zmq "tcp://127.0.0.1:5556" -i eth0 -n none -b 1
on terminal 2: ntopng -i tcp://127.0.0.1:5556

On ntopng side, I get the following warning and no traffic captured on ntop web ui.
WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?

Please help me resolve this issue.

Thanks
Amarnath.

**Comment by chigurupati** [comment]
My nprobe logs:

nprobe --zmq "tcp://127.0.0.1:5556" -i eth0 -n none -b 1
31/Mar/2016 12:42:06 [nprobe.c:3263] ERROR: Invalid nProbe license (/etc/nprobe.license) [Missing license file]
31/Mar/2016 12:42:06 [nprobe.c:3270] ERROR: *****************************************************
31/Mar/2016 12:42:06 [nprobe.c:3271] ERROR: *\*                                                 **
31/Mar/2016 12:42:06 [nprobe.c:3272] ERROR: *\*  Switching to DEMO MODE (missing valid license) **
31/Mar/2016 12:42:06 [nprobe.c:3273] ERROR: *\*                                                 **
31/Mar/2016 12:42:06 [nprobe.c:3274] ERROR: *\*  Purchase your nProbe license at                **
31/Mar/2016 12:42:06 [nprobe.c:3275] ERROR: *\*       https://shop.ntop.org/                    **
31/Mar/2016 12:42:06 [nprobe.c:3276] ERROR: *\*                                                 **
31/Mar/2016 12:42:06 [nprobe.c:3277] ERROR: *****************************************************
31/Mar/2016 12:42:06 [nprobe.c:6964] ERROR: ***************************************************************
31/Mar/2016 12:42:06 [nprobe.c:6965] ERROR: \* NOTE: This is a DEMO version limited to 25000 flows export.  *
31/Mar/2016 12:42:06 [nprobe.c:6966] ERROR: ***************************************************************
31/Mar/2016 12:42:06 [plugin.c:168] No plugins found in ./plugins
31/Mar/2016 12:42:06 [plugin.c:176] Loading 24 plugins [.so] from /usr/local/lib/nprobe/plugins
31/Mar/2016 12:42:06 [nprobe.c:4679] WARNING: The output interfaceId is set to 0: did you forget to use -Q perhaps ?
31/Mar/2016 12:42:06 [nprobe.c:4682] WARNING: The input interfaceId is set to 0: did you forget to use -u perhaps ?
31/Mar/2016 12:42:06 [nprobe.c:4776] Welcome to nProbe Pro v.7.3.160316 ($Revision: 4958 $) for armv7l-unknown-linux-gnueabihf 
31/Mar/2016 12:42:06 [nprobe.c:4786] Running on Raspbian GNU/Linux 8.0 (jessie)
31/Mar/2016 12:42:06 [nprobe.c:4797] [LICENSE] nProbe SystemId: FD0457A2499602D2
31/Mar/2016 12:42:06 [nprobe.c:6982] Welcome to nProbe v.7.3.160316 for armv7l-unknown-linux-gnueabihf
31/Mar/2016 12:42:06 [plugin.c:1022] 0 plugin(s) enabled
31/Mar/2016 12:42:06 [nprobe.c:6566] Non IPv4/v6 traffic is discarded according to the template
31/Mar/2016 12:42:06 [util.c:432] GeoIP: loaded AS config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNum.dat
31/Mar/2016 12:42:06 [util.c:443] GeoIP: loaded AS IPv6 config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNumv6.dat
31/Mar/2016 12:42:06 [nprobe.c:5348] Using packet capture length 128
31/Mar/2016 12:42:06 [nprobe.c:7155] IPv6 traffic will NOT be exported/accounted by this probe
31/Mar/2016 12:42:06 [nprobe.c:7156] due to configuration options (e.g. use NetFlow v9)
31/Mar/2016 12:42:06 [nprobe.c:7286] Capturing packets from interface eth0 [snaplen: 128 bytes]
31/Mar/2016 12:42:06 [util.c:4022] Initializing ZMQ as server
31/Mar/2016 12:42:06 [util.c:4065] Succesfully created ZMQ endpoint tcp://127.0.0.1:5556
31/Mar/2016 12:42:06 [util.c:3115] nProbe changed user to 'nobody'
31/Mar/2016 12:42:06 [nprobe.c:7501] nProbe started successfully
31/Mar/2016 12:42:07 [nprobe.c:2725] ---------------------------------
31/Mar/2016 12:42:07 [nprobe.c:2726] Average traffic: [102.00 pps][98.35 Kb/sec]
31/Mar/2016 12:42:07 [nprobe.c:2733] Current traffic: [102.00 pps][98.35 Kb/sec]
31/Mar/2016 12:42:07 [nprobe.c:2739] Current flow export rate: [0.0 flows/sec]
31/Mar/2016 12:42:07 [nprobe.c:2742] Flow drops: [export queue too long=0][too many flows=0]
31/Mar/2016 12:42:07 [nprobe.c:2746] Export Queue: 0/512000 [0.0 %]
31/Mar/2016 12:42:07 [nprobe.c:2751] Flow Buckets: [active=38][allocated=38][toBeExported=0]
31/Mar/2016 12:42:07 [cache.c:1224] Redis Cache [0 total/0.0 get/sec][0 total/0.0 set/sec]
31/Mar/2016 12:42:07 [nprobe.c:2593] Processed packets: 102 (max bucket search: 0)
31/Mar/2016 12:42:07 [nprobe.c:2576] Fragment queue length: 0
31/Mar/2016 12:42:07 [nprobe.c:2602] Flow export stats: [0 bytes/0 pkts][0 flows/0 pkts sent]
31/Mar/2016 12:42:07 [nprobe.c:2612] Flow drop stats:   [0 bytes/0 pkts][0 flows]
31/Mar/2016 12:42:07 [nprobe.c:2617] Total flow stats:  [0 bytes/0 pkts][0 flows/0 pkts sent]
31/Mar/2016 12:42:07 [nprobe.c:363] Packet stats (IN/OUT): 110/0 pkts rcvd/dropped [0.0%] [Last 110/0 pkts rcvd/dropped]
x31/Mar/2016 12:42:08 [nprobe.c:363] Packet stats (IN/OUT): 204/0 pkts rcvd/dropped [0.0%] [Last 94/0 pkts rcvd/dropped]
31/Mar/2016 12:42:09 [nprobe.c:363] Packet stats (IN/OUT): 299/0 pkts rcvd/dropped [0.0%] [Last 95/0 pkts rcvd/dropped]
31/Mar/2016 12:42:10 [nprobe.c:363] Packet stats (IN/OUT): 391/0 pkts rcvd/dropped [0.0%] [Last 92/0 pkts rcvd/dropped]
31/Mar/2016 12:42:11 [nprobe.c:363] Packet stats (IN/OUT): 481/0 pkts rcvd/dropped [0.0%] [Last 90/0 pkts rcvd/dropped]
31/Mar/2016 12:42:12 [nprobe.c:363] Packet stats (IN/OUT): 677/0 pkts rcvd/dropped [0.0%] [Last 196/0 pkts rcvd/dropped]
31/Mar/2016 12:42:13 [nprobe.c:363] Packet stats (IN/OUT): 723/0 pkts rcvd/dropped [0.0%] [Last 46/0 pkts rcvd/dropped]
31/Mar/2016 12:42:14 [nprobe.c:363] Packet stats (IN/OUT): 789/0 pkts rcvd/dropped [0.0%] [Last 66/0 pkts rcvd/dropped]
31/Mar/2016 12:42:15 [nprobe.c:363] Packet stats (IN/OUT): 847/0 pkts rcvd/dropped [0.0%] [Last 58/0 pkts rcvd/dropped]
31/Mar/2016 12:42:16 [nprobe.c:363] Packet stats (IN/OUT): 901/0 pkts rcvd/dropped [0.0%] [Last 54/0 pkts rcvd/dropped]
31/Mar/2016 12:42:17 [nprobe.c:363] Packet stats (IN/OUT): 1011/0 pkts rcvd/dropped [0.0%] [Last 110/0 pkts rcvd/dropped]
31/Mar/2016 12:42:18 [nprobe.c:363] Packet stats (IN/OUT): 1059/0 pkts rcvd/dropped [0.0%] [Last 48/0 pkts rcvd/dropped]
31/Mar/2016 12:42:19 [nprobe.c:363] Packet stats (IN/OUT): 1134/0 pkts rcvd/dropped [0.0%] [Last 75/0 pkts rcvd/dropped]
31/Mar/2016 12:42:20 [nprobe.c:363] Packet stats (IN/OUT): 1256/0 pkts rcvd/dropped [0.0%] [Last 122/0 pkts rcvd/dropped]
31/Mar/2016 12:42:21 [nprobe.c:363] Packet stats (IN/OUT): 1302/0 pkts rcvd/dropped [0.0%] [Last 46/0 pkts rcvd/dropped]
31/Mar/2016 12:42:22 [nprobe.c:363] Packet stats (IN/OUT): 1375/0 pkts rcvd/dropped [0.0%] [Last 73/0 pkts rcvd/dropped]
31/Mar/2016 12:42:23 [nprobe.c:363] Packet stats (IN/OUT): 1459/0 pkts rcvd/dropped [0.0%] [Last 84/0 pkts rcvd/dropped]
31/Mar/2016 12:42:24 [nprobe.c:363] Packet stats (IN/OUT): 1513/0 pkts rcvd/dropped [0.0%] [Last 54/0 pkts rcvd/dropped]
31/Mar/2016 12:42:25 [nprobe.c:363] Packet stats (IN/OUT): 1550/0 pkts rcvd/dropped [0.0%] [Last 37/0 pkts rcvd/dropped]
31/Mar/2016 12:42:26 [nprobe.c:363] Packet stats (IN/OUT): 1647/0 pkts rcvd/dropped [0.0%] [Last 97/0 pkts rcvd/dropped]
31/Mar/2016 12:42:27 [nprobe.c:363] Packet stats (IN/OUT): 1691/0 pkts rcvd/dropped [0.0%] [Last 44/0 pkts rcvd/dropped]
31/Mar/2016 12:42:28 [nprobe.c:363] Packet stats (IN/OUT): 1779/0 pkts rcvd/dropped [0.0%] [Last 88/0 pkts rcvd/dropped]
31/Mar/2016 12:42:29 [nprobe.c:363] Packet stats (IN/OUT): 1860/0 pkts rcvd/dropped [0.0%] [Last 81/0 pkts rcvd/dropped]
31/Mar/2016 12:42:30 [nprobe.c:363] Packet stats (IN/OUT): 1948/0 pkts rcvd/dropped [0.0%] [Last 88/0 pkts rcvd/dropped]

Ntop logs:

ntopng -i tcp://127.0.0.1:5556 
31/Mar/2016 12:49:00 [Ntop.cpp:980] Setting local networks to 127.0.0.0/8
31/Mar/2016 12:49:00 [Redis.cpp:106] Successfully connected to redis 127.0.0.1:6379@0
31/Mar/2016 12:49:00 [NtopPro.cpp:116] [LICENSE] Read license from Redis []
31/Mar/2016 12:49:00 [NtopPro.cpp:158] ERROR: [LICENSE] Invalid or missing ntopng License [Empty license file]
31/Mar/2016 12:49:00 [NtopPro.cpp:171] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
31/Mar/2016 12:49:00 [NtopPro.cpp:173] WARNING: [LICENSE] before returning to community mode
31/Mar/2016 12:49:00 [NtopPro.cpp:174] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
31/Mar/2016 12:49:00 [NtopPro.cpp:175] WARNING: [LICENSE] or run ntopng in community mode starting
31/Mar/2016 12:49:00 [NtopPro.cpp:176] WARNING: [LICENSE] ntopng --community
31/Mar/2016 12:49:00 [Ntop.cpp:1199] Registered interface tcp://127.0.0.1:5556 [id: 6]
31/Mar/2016 12:49:00 [Ntop.cpp:1212] Registered interface view tcp://127.0.0.1:5556 [id: 6]
31/Mar/2016 12:49:00 [Utils.cpp:305] User changed to nobody
31/Mar/2016 12:49:01 [main.cpp:258] PID stored in file /var/tmp/ntopng.pid
31/Mar/2016 12:49:01 [HTTPserver.cpp:458] HTTPS Disabled: missing SSL certificate /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem
31/Mar/2016 12:49:01 [HTTPserver.cpp:460] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
31/Mar/2016 12:49:01 [HTTPserver.cpp:503] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
31/Mar/2016 12:49:01 [HTTPserver.cpp:506] HTTP server listening on port 3000
31/Mar/2016 12:49:01 [main.cpp:295] Working directory: /var/tmp/ntopng
31/Mar/2016 12:49:01 [main.cpp:297] Scripts/HTML pages directory: /usr/share/ntopng
31/Mar/2016 12:49:01 [Ntop.cpp:258] Welcome to ntopng armv7l v.2.3.160306 - (C) 1998-16 ntop.org
31/Mar/2016 12:49:01 [Ntop.cpp:263] Built on Raspbian GNU/Linux 8.0 (jessie)
31/Mar/2016 12:49:01 [PeriodicActivities.cpp:53] Started periodic activities loop...
31/Mar/2016 12:49:01 [RuntimePrefs.cpp:34] Dumping alerts into syslog
31/Mar/2016 12:49:01 [NtopPro.cpp:233] [LICENSE] ntopng systemId: FD0457A2499602D2
31/Mar/2016 12:49:01 [NtopPro.cpp:238] [LICENSE] ntopng is starting in demo mode
31/Mar/2016 12:49:01 [NetworkInterface.cpp:1434] Started packet polling on interface tcp://127.0.0.1:5556 [id: 6]...
31/Mar/2016 12:49:02 [CollectorInterface.cpp:104] Collecting flows on tcp://127.0.0.1:5556 [ntopng->nprobe]
31/Mar/2016 12:49:02 [ParserInterface.cpp:671] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
31/Mar/2016 12:49:02 [ParserInterface.cpp:673] WARNING: [112] 
31/Mar/2016 12:49:02 [ParserInterface.cpp:671] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
31/Mar/2016 12:49:02 [ParserInterface.cpp:673] WARNING: [111] 
31/Mar/2016 12:49:02 [ParserInterface.cpp:671] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
31/Mar/2016 12:49:02 [ParserInterface.cpp:673] WARNING: [112] 
31/Mar/2016 12:49:02 [ParserInterface.cpp:671] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
31/Mar/2016 12:49:02 [ParserInterface.cpp:673] WARNING: [111] 
31/Mar/2016 12:49:02 [ParserInterface.cpp:671] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
31/Mar/2016 12:49:02 [ParserInterface.cpp:673] WARNING: [111] 
31/Mar/2016 12:49:02 [ParserInterface.cpp:671] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
31/Mar/2016 12:49:02 [ParserInterface.cpp:673] WARNING: [111] 
31/Mar/2016 12:49:02 [ParserInterface.cpp:671] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
31/Mar/2016 12:49:02 [ParserInterface.cpp:673] WARNING: [111] 
31/Mar/2016 12:49:02 [ParserInterface.cpp:671] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
31/Mar/2016 12:49:02 [ParserInterface.cpp:673] WARNING: [112] 
31/Mar/2016 12:49:02 [ParserInterface.cpp:671] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
31/Mar/2016 12:49:02 [ParserInterface.cpp:673] WARNING: [107] 
31/Mar/2016 12:49:02 [ParserInterface.cpp:671] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
31/Mar/2016 12:49:02 [ParserInterface.cpp:673] WARNING: [111] 
31/Mar/2016 12:49:02 [ParserInterface.cpp:671] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
31/Mar/2016 12:49:02 [ParserInterface.cpp:673] WARNING: [110] 
31/Mar/2016 12:49:02 [ParserInterface.cpp:671] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
31/Mar/2016 12:49:02 [ParserInterface.cpp:673] WARNING: [112] 
31/Mar/2016 12:49:02 [ParserInterface.cpp:671] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
31/Mar/2016 12:49:02 [ParserInterface.cpp:673] WARNING: [112] 
31/Mar/2016 12:49:02 [ParserInterface.cpp:671] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
31/Mar/2016 12:49:02 [ParserInterface.cpp:673] WARNING: [112] 
31/Mar/2016 12:49:02 [ParserInterface.cpp:671] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
31/Mar/2016 12:49:02 [ParserInterface.cpp:673] WARNING: [112] 
31/Mar/2016 12:49:02 [ParserInterface.cpp:671] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
31/Mar/2016 12:49:02 [ParserInterface.cpp:673] WARNING: [115] 
31/Mar/2016 12:49:02 [ParserInterface.cpp:671] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
31/Mar/2016 12:49:02 [ParserInterface.cpp:673] WARNING: [115] 
31/Mar/2016 12:49:02 [ParserInterface.cpp:671] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
31/Mar/2016 12:49:02 [ParserInterface.cpp:673] WARNING: [112] 
31/Mar/2016 12:49:02 [ParserInterface.cpp:671] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
31/Mar/2016 12:49:02 [ParserInterface.cpp:673] WARNING: [112] 
31/Mar/2016 12:49:02 [ParserInterface.cpp:671] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?

goes on and on.....

**Comment by simonemainardi** [comment]
issue is reproducible with

```
deri@raspberrypi 91> /usr/local/bin/ntopng ntopng --version
v.2.3.160306 [Professional/Embedded Edition]
GIT rev:   dev:a949d76a025e9e53788cddbafa61fa9c5692dc6e:20160306
Pro rev:   r589
System Id: FD2BC9D6499602D2
Built on:  Raspbian GNU/Linux 8.0 (jessie)
```

but everything works smoothly if flows are collected with

```
Simones-MBP:ntopng simone$ ./ntopng --version
v.2.3.160331 [Professional Edition]
GIT rev:   dev:480634565bafe4624018fd9cdad6d016d672aeef:20160331
Pro rev:   r603
System Id:
Built on:  MacOSX 10.11.3
```

@lucaderi should we first make a new RPI build before deepening the inspection?

**Comment by lucaderi** [comment]
@simonemainardi Ok will do

**Comment by simonemainardi** [comment]
thank you

**Comment by lucaderi** [comment]
New packages have been uploaded. @chigurupati Please check

**Comment by simonemainardi** [comment]
thanks @lucaderi , I confirm the latest RPI build is no longer affected by the bug.

**Comment by chigurupati** [comment]
@simonemainardi and @lucaderi , I can see the latest package but then I try to install, there are some unmet dependencies. check the below logs.

apt-get install ntopng

---

Reading package lists... Done
Building dependency tree  
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 console-setup : Depends: keyboard-configuration (= 1.140) but 1.123 is to be installed
 console-setup-linux : Depends: keyboard-configuration (= 1.140) but 1.123 is to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

---

apt-get -f install

---

Reading package lists... Done
Building dependency tree  
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  g++-4.9 libboost-atomic-dev libboost-atomic1.58.0 libboost-chrono-dev libboost-context-dev libboost-coroutine-dev libboost-dev libboost-exception-dev libboost-filesystem1.58.0 libboost-graph-dev
  libboost-graph-parallel-dev libboost-iostreams-dev libboost-locale-dev libboost-math-dev libboost-mpi-dev libboost-mpi-python-dev libboost-python-dev libboost-random-dev libboost-regex-dev
  libboost-regex1.58.0 libboost-serialization-dev libboost-signals-dev libboost-test-dev libboost-thread1.58.0 libboost-timer-dev libboost-tools-dev libglew1.10 liborcus-0.8-0 libpython3.4
  libpython3.4-dev libpython3.4-minimal libpython3.4-stdlib libwps-0.3-3 python3.4 python3.4-dev python3.4-minimal
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  keyboard-configuration
The following packages will be upgraded:
  keyboard-configuration
1 upgraded, 0 newly installed, 0 to remove and 859 not upgraded.
9 not fully installed or removed.
Need to get 0 B/655 kB of archives.
After this operation, 20.5 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
WARNING: The following packages cannot be authenticated!
  keyboard-configuration
Install these packages without verification? [y/N] y
Preconfiguring packages ...
(Reading database ... 140349 files and directories currently installed.)
Preparing to unpack .../keyboard-configuration_1.140_all.deb ...
insserv: warning: script 'K01smx-service' missing LSB tags and overrides
insserv: warning: script 'S65nifi' missing LSB tags and overrides
insserv: warning: script 'nifi' missing LSB tags and overrides
insserv: warning: script 'smx-service' missing LSB tags and overrides
insserv: Starting nifi depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting nifi depends on rc.local and therefore on system facility`$all' which can not be true!
insserv: There is a loop between service nifi and rc.local if started
insserv:  loop involving service rc.local at depth 6
insserv:  loop involving service nifi at depth 1
insserv: Starting nifi depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: exiting now without changing boot order!
update-rc.d: error: insserv rejected the script header
dpkg: error processing archive /var/cache/apt/archives/keyboard-configuration_1.140_all.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
Errors were encountered while processing:
 /var/cache/apt/archives/keyboard-configuration_1.140_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

---

Here, there are problems installing the latest version of keyboard-configuration dependency. Also I tried to install console-setup (which has keyboard-configuration as a dependency, by changing K-C version to 1.14)  from from source but there are so many warnings, and it fails with some fonts error.

Please, check this and help to install ntopng.

Regards,
Amar.

**Comment by simonemainardi** [comment]
did you run apt-get update first?

**Comment by chigurupati** [comment]
Hello, 

Yes I did:
1: apt-get update 
2: apt-get upgrade

**Comment by chigurupati** [comment]
Hello,

The issue is solved. I had to completely uninstall previous version with all its dependencies. and freshly install the latest package.
Thanks
Amar.
