### ISSUE TITLE
Alerts Dashboard Draws the Pie-Chart with white Background in Dark Mode

### ISSUE THREAD

**Issue by andiyk** [ntop/ntopng#4654]
![image](https://user-images.githubusercontent.com/23166953/97700521-46d51980-1aac-11eb-9f84-25d6794f1d28.png)

the Problem is the pie-chart.css line 13

background-color was set to #ffffff always in "Dark Mode"

**Comment by gabryon99** [comment]
Hi @andiyk! Thanks for the reporting, I've replaced the white background. If you have any other issues with the dark theme tell us. Thanks!
