### ISSUE TITLE
Misleading message reported when adding license with --community

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4657]
Below you can find examples of misleading behaviour when installing a license on ntopng started with --community that must be correct so people are aware of the configuration they are using.

![image](https://user-images.githubusercontent.com/4493366/97742694-eb734d80-1ae4-11eb-92cb-125a4b49fd4f.png)

![licenza ntop](https://user-images.githubusercontent.com/4493366/97742756-05149500-1ae5-11eb-9fca-9dcfd4873e0c.PNG)

**Comment by simonemainardi** [comment]
Behavior is different. Please, make sure to use the latest version as a badge is shown and the message is different:

![image](https://user-images.githubusercontent.com/3397663/97842898-b2a3c600-1ce8-11eb-8737-1e379598b6fa.png)


please report
