### ISSUE TITLE
Add wizard-like messages for Endpoint / Recipient / Pool creation/definition

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4658]
In ntopng is is possible to create endpoint/recipients for deliver alerts to users and bind them to pools. As written in the documentation (https://www.ntop.org/guides/ntopng/web_gui/alerts.html?highlight=endpoints) they can be creted by used but ntopng by default does not create them as it lacks the user input for configuration.
It is requested to implement wizard-like messages (max 1 per page) to invite users to create them if undefined.

**Comment by simonemainardi** [comment]
This introduced https://github.com/ntop/ntopng/issues/4662

**Comment by simonemainardi** [comment]
I am not sure this is needed: please clean it https://github.com/ntop/ntopng/commit/ee3bb1db2961a145992e8be9cb8e67c756d3b1c1#diff-d7835b04428b541d1fd770da7ff46ed5a09d47f70045fcebc5afe69c5d752246R271
