### ISSUE TITLE
Per VLAN traffic graph

### ISSUE THREAD

**Issue by simone-unipi** [ntop/ntopng#466]
In a multi-VLAN environment would be nice to have a report that shows aggregated traffic per VLAN. 
Something like the "application" report (with all the VLANs displayed), but also per single VLAN.

**Comment by lucaderi** [comment]
@simonemainardi In essence we need to implement RRDs per VLAN.

**Comment by simonemainardi** [comment]
Implemented in https://github.com/ntop/ntopng/commit/0ca318ac4dd32ba891fa5d725e0fef4f18d562b4 please give it a try, code is in the latest nightly build.
