### ISSUE TITLE
Colors are unreadable

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4668]
![Screen Shot 2020-11-03 at 17 09 21](https://user-images.githubusercontent.com/4493366/98010806-727f3900-1df7-11eb-9652-59899f36a9b0.png)

![Screen Shot 2020-11-03 at 17 13 39](https://user-images.githubusercontent.com/4493366/98011308-f802e900-1df7-11eb-9555-da9bc8fccdeb.png)

No clue what is inside the white button

Fix it an backport the fix to stable

Note that toggling twice the color, seems to fix the issue
![Screen Shot 2020-11-03 at 17 26 05](https://user-images.githubusercontent.com/4493366/98012761-c25eff80-1df9-11eb-8062-5813cc8b44c1.png)

**Comment by gabryon99** [comment]
This problem has been fixed with the commit: 93a426dfca2dd0a6ca0055f4a43f446cd21bfe35
