### ISSUE TITLE
NtopNG - bridge mode [Help wanted]

### ISSUE THREAD

**Issue by vijaytejak** [ntop/ntopng#4670]
Hi,

I have setup ntopng in a dedicated Linux machine, haven't activated the license yet.

Earlier I used in pfsense due to limited features I am moving to a standalone version,
 as the traffic passes through pfsense it can detect all the interfaces traffic, but with standalone deployment how can ntopng detect all the network traffic like multiple subnets and VLANs.

In nEdge i have seen bridge mode, where traffic passes through the nEdge appliance, how it can be done for ntopng.

Please guide me in architecture wise deployment, I have to use this for my entire organization with 700 active devices.

With the current deployment I have done, I am unable to see the complete traffic usage, I am a bit confused about how ntopng can detect all the information if the traffic is not passing through its appliance.

**Comment by simonemainardi** [comment]
in your standalone version, is there an interface (e.g,. connected to a mirror port) which is receiving all network traffic? By the way, see https://www.ntop.org/nprobe/network-monitoring-101-a-beginners-guide-to-understanding-ntop-tools/

**Comment by vijaytejak** [comment]
No, no traffic is being received from any mirror port, we don't have one configured, thanks for the article will read it, by the way, I want to see the full layer 7 application traffic as well, like how ntopng in pfsense works (want the solution like how it works in pfsense real-time traffic view).

**Comment by simonemainardi** [comment]
Yes. Please, follow the article as you need a way (either a TAP, a mirror, or your standalone version being the router) to get all the network packets so ntopng can analyze them

**Comment by vijaytejak** [comment]
Thanks for the article,it is working now.

And the following is observed.
When I download and upload a file, it is recording into individual flows, if I select my laptop it is showing only uploaded data, downloaded info is stored in another flow.

How can I see all the info in single page.

![image](https://user-images.githubusercontent.com/14872281/98124029-a716f180-1ed8-11eb-807f-2e9bdaaac50d.png)

---------------------------------------------------------------

![image](https://user-images.githubusercontent.com/14872281/98124132-c57ced00-1ed8-11eb-91ae-b8aa0fc5889a.png)

**Comment by vijaytejak** [comment]
Also the traffic dashboard is changing randomly.

to the following as shown in the below images.
![image](https://user-images.githubusercontent.com/14872281/98124380-20aedf80-1ed9-11eb-99ec-123d9c2742cf.png)
![image](https://user-images.githubusercontent.com/14872281/98124439-33291900-1ed9-11eb-8d12-d8c19d0db2fb.png)

**Comment by simonemainardi** [comment]
> Thanks for the article,it is working now.

thanks for reporting

> downloaded info is stored in another flow.

The flow is only one. You'll see two endpoints for that flow. The client (doing mostly RCVD traffic) and the server (doing mostly SENT traffic)
