### ISSUE TITLE
Unable to serve requests at this time, possibly starting up or shutting down.

### ISSUE THREAD

**Issue by zakioo** [ntop/ntopng#4671]
Hi

We are unable to access ntopng web interface since last upgrade from 4.0 to 4.2

Error message : 
`Unable to serve requests at this time, possibly starting up or shutting down.`

Below ntopng config file 
BDW: without checking the license online, we are unable to start ntopng service correctly !

`--online-license-check 
--https-port=3001

-i="tcp://127.0.0.1:5556"
--local-networks="X.X.X.X"
-p="/var/lib/ntopng/ndpiProtos.txt"

-i="tcp://127.0.0.1:5557"
--local-networks="X.X.X.X"
-p="/var/lib/ntopng/ndpiProtos.txt"

-i="tcp://127.0.0.1:5558"
--local-networks="X.X.X.X"
-p="/var/lib/ntopng/ndpiProtos.txt"

-i="tcp://127.0.0.1:5559"
--local-networks="X.X.X.X"
-p="/var/lib/ntopng/ndpiProtos.txt"

-i="tcp://127.0.0.1:5560"
--local-networks="X.X.X.X"
-p="/var/lib/ntopng/ndpiProtos.txt"`

systemctl output : 

>nov. 04 11:19:30 SRV001 systemd[1]: Stopped ntopng high-speed web-based traffic monitoring and analysis tool.
nov. 04 11:19:30 SRV001 systemd[1]: Unit ntopng.service entered failed state.
nov. 04 11:19:30 SRV001 systemd[1]: ntopng.service failed.
nov. 04 11:19:37 SRV001 systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
nov. 04 11:19:37 SRV001 systemd[1]: Started ntopng high-speed web-based traffic monitoring and analysis tool.
nov. 04 11:19:37 SRV001 ntopng[6008]: 04/Nov/2020 11:19:37 [Ntop.cpp:2336] Setting local networks to X.X.X.X
nov. 04 11:19:37 SRV001 ntopng[6008]: 04/Nov/2020 11:19:37 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
nov. 04 11:19:37 SRV001 ntopng[6008]: 04/Nov/2020 11:19:37 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
nov. 04 11:19:37 SRV001 ntopng[6008]: 04/Nov/2020 11:19:37 [NtopPro.cpp:299] [LICENSE] Reading license from /etc/ntopng.license
nov. 04 11:19:37 SRV001 ntopng[6008]: 04/Nov/2020 11:19:37 [NtopPro.cpp:192] Contacting licensing server. Please hold on...
nov. 04 11:19:38 SRV001 ntopng[6008]: 04/Nov/2020 11:19:38 [NtopPro.cpp:192] Contacting licensing server. Please hold on...
nov. 04 11:19:40 SRV001 ntopng[6008]: 04/Nov/2020 11:19:40 [NtopPro.cpp:192] Contacting licensing server. Please hold on...
nov. 04 11:19:40 SRV001 ntopng[6008]: 04/Nov/2020 11:19:40 [NtopPro.cpp:429] [LICENSE] /etc/ntopng.license: found valid Professional license
nov. 04 11:19:40 SRV001 ntopng[6008]: 04/Nov/2020 11:19:40 [Ntop.cpp:2441] Registered interface tcp://127.0.0.1:5556 [id: 0]
nov. 04 11:19:40 SRV001 ntopng[6008]: 04/Nov/2020 11:19:40 [Ntop.cpp:2441] Registered interface tcp://127.0.0.1:5557 [id: 2]
nov. 04 11:19:40 SRV001 ntopng[6008]: 04/Nov/2020 11:19:40 [Ntop.cpp:2441] Registered interface tcp://127.0.0.1:5558 [id: 5]
nov. 04 11:19:40 SRV001 ntopng[6008]: 04/Nov/2020 11:19:40 [Ntop.cpp:2441] Registered interface tcp://127.0.0.1:5559 [id: 6]
nov. 04 11:19:40 SRV001 ntopng[6008]: 04/Nov/2020 11:19:40 [Ntop.cpp:2441] Registered interface tcp://127.0.0.1:5560 [id: 7]
nov. 04 11:19:40 SRV001 ntopng[6008]: 04/Nov/2020 11:19:40 [main.cpp:312] PID stored in file /var/run/ntopng.pid
nov. 04 11:19:40 SRV001 ntopng[6008]: 04/Nov/2020 11:19:40 [Geolocation.cpp:140] Loaded database dbip-asn-lite.mmdb [/usr/share/ntopng/httpdocs/geoip/dbip-asn-lite.mmdb][ip_version: 6]
nov. 04 11:19:40 SRV001 ntopng[6008]: 04/Nov/2020 11:19:40 [Geolocation.cpp:140] Loaded database dbip-country-lite.mmdb [/usr/share/ntopng/httpdocs/geoip/dbip-country-lite.mmdb][ip_version:
nov. 04 11:19:40 SRV001 ntopng[6008]: 04/Nov/2020 11:19:40 [Geolocation.cpp:91] Using geolocation provided by DB-IP (https://db-ip.com)
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [HTTPserver.cpp:1529] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [HTTPserver.cpp:1532] HTTP server listening on 3000
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [HTTPserver.cpp:1538] HTTPS server listening on 3001
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [Utils.cpp:764] User changed to ntopng
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [NetworkInterface.cpp:2593] Started flow user script hooks loop on interface tcp://127.0.0.1:5556 [id: 0]...
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [NetworkInterface.cpp:2593] Started flow user script hooks loop on interface tcp://127.0.0.1:5557 [id: 2]...
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [NetworkInterface.cpp:2593] Started flow user script hooks loop on interface tcp://127.0.0.1:5558 [id: 5]...
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [NetworkInterface.cpp:2593] Started flow user script hooks loop on interface tcp://127.0.0.1:5559 [id: 6]...
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [NetworkInterface.cpp:2593] Started flow user script hooks loop on interface tcp://127.0.0.1:5560 [id: 7]...
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [main.cpp:382] Working directory: /var/lib/ntopng
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [main.cpp:384] Scripts/HTML pages directory: /usr/share/ntopng
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [Ntop.cpp:440] Welcome to ntopng x86_64 v.4.2.201103 - (C) 1998-20 ntop.org
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [NtopPro.cpp:701] [LICENSE] System Id:        XXXXXXXXXXX
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [NtopPro.cpp:702] [LICENSE] Edition:        Professional
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [NtopPro.cpp:703] [LICENSE] License Type:        Permanent License
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [NtopPro.cpp:712] [LICENSE] License:        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [NtopPro.cpp:713] [LICENSE]                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [NtopPro.cpp:713] [LICENSE]                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [NtopPro.cpp:713] [LICENSE]                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [NtopPro.cpp:713] [LICENSE]                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [NtopPro.cpp:717] [LICENSE] License Hash:        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [NtopPro.cpp:727] [LICENSE] Maintenance:        Until Sun Mar 21 22:42:24 2021 [137 days left]
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [PeriodicActivities.cpp:109] Started periodic activities loop...
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [startup.lua:50] Processing startup.lua: please hold on...
nov. 04 11:19:41 SRV001 ntopng[6008]: 04/Nov/2020 11:19:41 [startup.lua:144] [lists_utils.lua:758] Refreshing category lists...

**Comment by simonemainardi** [comment]
is the system able to reach the internet? It seems it is just downloading (black-)lists. I would expect this to take ~1 min.

**Comment by zakioo** [comment]
yes it does reach internet.

FYI 

It works when starting ntopng using command line ntopng with parameter --online-license-check
but it doesn't work when using systemctl with config file above.

Below how I start nprobe & ntopng services : 

in /usr/lib/systemd/system/nprobe-2055 : 
ExecStart=/usr/bin/nprobe --zmq "tcp://*:5556" --zmq-format j -i none -n none --collector-port 2055 -T "@NTOPNG@" --flow-version 9 --tunnel --ipsec-auth-data-len --no-promisc

in /usr/lib/systemd/system/ntopng : 
ExecStart=/usr/bin/ntopng --online-license-check --https-port=3001 -i="tcp://127.0.0.1:5556" --local-networks="X.X.X.X" -p="/var/lib/ntopng/ndpiProtos.txt" /run/ntopng.conf


I can see also : 
 [ZMQCollectorInterface.cpp:133] ERROR: Unable to connect to ZMQ endpoint ="tcp://*:5556" [probe]: Protocol not supported (93)

**Comment by simonemainardi** [comment]
I think you are not using the right configuration file. Likely, your ntopng is using another config file. Indeed:

1. You are showing a log of ntopng complaining with `"tcp://*:5556"` but `"tcp://*:5556"` is not listed in the configuration file.
2. There are backticks ` in the file shown above. Make sure they are NOT present in the file.

In short:
- stop ntopng
- make sure no ntopng instance is running
- do the necessary edits to the configuration file
- restart ntopng

**Comment by zakioo** [comment]
I stopped ntop service and tried to start it as follow ( getting same error ) :  

ntopng --online-license-check --https-port=3001 -i="tcp://127.0.0.1:5556" --local-networks="X.X.X." -p="/var/lib/ntopng/ndpiProtos.txt"

> 04/Nov/2020 19:05:19 [Ntop.cpp:2336] Setting local networks to X.X.X.X
04/Nov/2020 19:05:19 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
04/Nov/2020 19:05:19 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
04/Nov/2020 19:05:19 [NtopPro.cpp:299] [LICENSE] Reading license from /etc/ntopng.license
04/Nov/2020 19:05:19 [NtopPro.cpp:192] Contacting licensing server. Please hold on...
04/Nov/2020 19:05:20 [NtopPro.cpp:192] Contacting licensing server. Please hold on...
04/Nov/2020 19:05:21 [NtopPro.cpp:192] Contacting licensing server. Please hold on...
04/Nov/2020 19:05:22 [NtopPro.cpp:429] [LICENSE] /etc/ntopng.license: found valid Professional license
04/Nov/2020 19:05:22 [ZMQCollectorInterface.cpp:133] ERROR: Unable to connect to ZMQ endpoint =tcp://127.0.0.1:5556 [probe]: Protocol not supported (93)
04/Nov/2020 19:05:22 [main.cpp:236] ERROR: An exception occurred during =tcp://127.0.0.1:5556 interface creation[19]: No such device
04/Nov/2020 19:05:22 [main.cpp:294] ERROR: Startup error: missing super-user privileges ?

FYI : I'm runing this with user root.

**Comment by simonemainardi** [comment]
remove the `=`

do `-i "tcp://127.0.0.1:5556"`

**Comment by zakioo** [comment]
Indeed this solved the issue.

Regarding the --online-license-check, I was able to retire old licence and generate a new one using https://shop.ntop.org/recover_licenses.php

Thank you.
