### ISSUE TITLE
Clicking on Recipient in  ntopng Enterprise M v.4.2.201103  Alerts Doesn't Open Popup to Add a Recipient

### ISSUE THREAD

**Issue by grstitt** [ntop/ntopng#4672]
I've created a slack endpoint and then go to add a recipient, but when I click on the plus sign to add one nothing comes up.  I've tried in the latest Chrome and Firefox.

**Comment by simonemainardi** [comment]
Thanks for reporting and sorry for this glitch. Issue fixed in sable and dev. Please, hold on a couple of hours, then update, and it will be OK.
