### ISSUE TITLE
Implement Host create hook

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4675]
It is required to implement a new host hook that is called when a host is created in memory. For performance reason we can define a filter for calling the hook on all hosts, local only or remote only.

**Comment by lucaderi** [comment]
In order to avoid peroformance penalties, we could possibly modify the minute hook and pass a new parameter when this is the first time a host is called (to avoid the script having to mess up with time)

**Comment by simonemainardi** [comment]
After internal review, we have determined this kind of hooks to be no longer necessary.
