### ISSUE TITLE
Add the reload button to all DataTable-based tables

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4676]
![Screen Shot 2020-11-04 at 18 50 52](https://user-images.githubusercontent.com/4493366/98155624-d593cd00-1ed6-11eb-837a-e4fd3b1232eb.png)

**Comment by lucaderi** [comment]
![Screen Shot 2020-11-06 at 15 30 24](https://user-images.githubusercontent.com/4493366/98377475-2295b180-2045-11eb-856b-db5ad45bfa83.png)

In recipients the reload button is present but disabled. In endpoint instead is working. This needs to be fixed

To ease the testing can you please list the tables that you have modified?

**Comment by gabryon99** [comment]
Now the reload button is always enabled and a tooltip has been added to the plus button when there are no endpoints.

**Comment by lucaderi** [comment]
Ok even though it is unclear to me why for specific entries such as Pool / Flows, reload is disabled
