### ISSUE TITLE
Segfaults 4.2 / Debian

### ISSUE THREAD

**Issue by mwmdc** [ntop/ntopng#4678]
Good Morning!

Since 4.2 we have a lot of segfaults in ntopng. This is the log from last night:

[Wed Nov  4 19:44:26 2020] flowdump ifid 4[32199]: segfault at c ip 000055bd404937df sp 00007fbd11e0e5e0 error 4 in ntopng[55bd403b7000+231000]
[Wed Nov  4 19:44:26 2020] Code: df e8 85 fb f4 ff 8d 50 ff 81 fa fe 1f 00 00 0f 87 d6 00 00 00 01 45 10 29 45 0c 83 45 08 01 83 83 58 0a 00 00 01 49 8b 55 00 <81> 7a 0c 00 20 00 00 77 20 4c 89 fe 48 89 df e8 8d fe ff ff 49 c7
[Wed Nov  4 21:28:45 2020] flowdump ifid 4[7866]: segfault at c ip 0000560dd565e7df sp 00007f92c88f35e0 error 4 in ntopng[560dd5582000+231000]
[Wed Nov  4 21:28:45 2020] Code: df e8 85 fb f4 ff 8d 50 ff 81 fa fe 1f 00 00 0f 87 d6 00 00 00 01 45 10 29 45 0c 83 45 08 01 83 83 58 0a 00 00 01 49 8b 55 00 <81> 7a 0c 00 20 00 00 77 20 4c 89 fe 48 89 df e8 8d fe ff ff 49 c7
[Wed Nov  4 21:51:21 2020] flowdump ifid 4[10971]: segfault at c ip 000055cf1d9797df sp 00007f01d5e0e5e0 error 4 in ntopng[55cf1d89d000+231000]
[Wed Nov  4 21:51:21 2020] Code: df e8 85 fb f4 ff 8d 50 ff 81 fa fe 1f 00 00 0f 87 d6 00 00 00 01 45 10 29 45 0c 83 45 08 01 83 83 58 0a 00 00 01 49 8b 55 00 <81> 7a 0c 00 20 00 00 77 20 4c 89 fe 48 89 df e8 8d fe ff ff 49 c7
[Thu Nov  5 00:12:12 2020] flowdump ifid 4[16736]: segfault at c ip 000056448399a7df sp 00007f5362ffc5e0 error 4 in ntopng[5644838be000+231000]
[Thu Nov  5 00:12:12 2020] Code: df e8 85 fb f4 ff 8d 50 ff 81 fa fe 1f 00 00 0f 87 d6 00 00 00 01 45 10 29 45 0c 83 45 08 01 83 83 58 0a 00 00 01 49 8b 55 00 <81> 7a 0c 00 20 00 00 77 20 4c 89 fe 48 89 df e8 8d fe ff ff 49 c7
[Thu Nov  5 01:59:05 2020] flowdump ifid 4[1805]: segfault at c ip 0000562df5bc97df sp 00007fb38560d5e0 error 4 in ntopng[562df5aed000+231000]
[Thu Nov  5 01:59:05 2020] Code: df e8 85 fb f4 ff 8d 50 ff 81 fa fe 1f 00 00 0f 87 d6 00 00 00 01 45 10 29 45 0c 83 45 08 01 83 83 58 0a 00 00 01 49 8b 55 00 <81> 7a 0c 00 20 00 00 77 20 4c 89 fe 48 89 df e8 8d fe ff ff 49 c7
[Thu Nov  5 03:46:35 2020] flowdump ifid 4[497]: segfault at c ip 000055c6c5cd47df sp 00007fbe1a7fb5e0 error 4 in ntopng[55c6c5bf8000+231000]
[Thu Nov  5 03:46:35 2020] Code: df e8 85 fb f4 ff 8d 50 ff 81 fa fe 1f 00 00 0f 87 d6 00 00 00 01 45 10 29 45 0c 83 45 08 01 83 83 58 0a 00 00 01 49 8b 55 00 <81> 7a 0c 00 20 00 00 77 20 4c 89 fe 48 89 df e8 8d fe ff ff 49 c7

Seems to be the same code part each time.

Version | 4.2.201104 (12084) - Enterprise L Edition
OS: Debian GNU/Linux 10 (buster)
Platform: Debian 10.6 [x86_64][Debian GNU/Linux 10 (buster)] - 64 bit
Startup: ntopng --dump-flows "[hidden]" --interface "tcp://127.0.0.1:5556" --interface "ens192" --http-port "192.168.0.1:3000" --local-networks "x.x.0.0/16,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16" --dns-mode "1" --max-num-flows "2097152" --ignore-vlans

Best regards,
Michael

**Comment by lucaderi** [comment]
Hi can I give you a binary ntopng build with debug simbols (stripped) by the package for inspection? Would you contact me on telegram (@lucaderi) or email deri@ntop.org so we can continue from there?

**Comment by lucaderi** [comment]
This is the crash trace

Thread 12 (Thread 0x7fd456e11700 (LWP 8423)):
#0  0x0000558835b51028 in BatchedMySQLDBEntry::checkLen() (this=0x0) at /home/deri/ntopng/pro/BatchedMySQLDBEntry.h:51
#1  0x0000558835b50adc in BatchedMySQLDB::checkBufferQueue(SPSCQueue<void*>*, BatchedMySQLDBEntry*) (this=0x55883a8fca90, q=0x558837858d20, entry=0x0) at pro/BatchedMySQLDB.cpp:145
#2  0x0000558835b50d97 in BatchedMySQLDB::dumpFlow(long, Flow*, char*) (this=0x55883a8fca90, when=1604605026, f=
    0x7fd39be47fd0, json=0x7fd44400e390 "{ \"8\": ...) at pro/BatchedMySQLDB.cpp:283
#3  0x0000558835b16f13 in NetworkInterface::dequeueFlowsForDump(unsigned int, unsigned int) (this=0x5588378a30b0, idle_flows_budget=0, active_flows_budget=131072) at src/NetworkInterface.cpp:2521
#4  0x0000558835b172ab in NetworkInterface::dumpFlowLoop() (this=0x5588378a30b0) at src/NetworkInterface.cpp:2639
#5  0x0000558835b17362 in flowDumper(void*) (ptr=0x5588378a30b0) at src/NetworkInterface.cpp:2666
#6  0x00007fd47de9dfa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#7  0x00007fd47daab4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by mwmdc** [comment]
Hi Simone!

This seems to be fixed in 4.2.201109. I didn't see a crash for past 12 hours. Thanks a lot!

**Comment by simonemainardi** [comment]
thanks for reporting.
