### ISSUE TITLE
Informative alerts must be dismissible 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4680]
<img width="374" alt="Screenshot 2020-11-05 at 14 25 39" src="https://user-images.githubusercontent.com/4493366/98246888-340e8900-1f73-11eb-9b82-7981040a0d99.png">

<img width="357" alt="Screenshot 2020-11-05 at 18 04 48" src="https://user-images.githubusercontent.com/4493366/98272689-a4c49e00-1f91-11eb-9f1f-a1db4bb8d529.png">

All notifications that are not alerts (so non red/yellow badge) must have a dismiss button. The X icon is used to temporarily close and this has to stay.

The above picture is an example of an informative dialog with no dismiss button.

**Comment by gabryon99** [comment]
Now the `Update` notification is dismissable, and the others INFO notifications are dismissable (except for the contribution). The notification `Forced Community` has been improved by changing its style (Info to Warning) and it's not dismissable.

**Comment by lucaderi** [comment]
Verified as fixed
