### ISSUE TITLE
Datatable broken and out of the screen boundaries

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4681]
<img width="1410" alt="Screenshot 2020-11-05 at 14 38 03" src="https://user-images.githubusercontent.com/4493366/98247959-99af4500-1f74-11eb-8cf7-70ae8203538f.png">

How to reproduce it
- download https://mega.nz/file/iA0CVJiR#WZHqAOMpM6xiZ_dlEIwklo42CqIye6WuNUarhIXrKcs
- start ntopng as ntopng -i Sample.pcapng -m "10.0.0.0/8" --community
- wait a few minutes 
- go to http://XXXXXX:3000/lua/show_alerts.lua#tab-table-flow-alerts-history

the above window will appear

**Comment by lucaderi** [comment]
The above fix doesn't solve the issue. Please revert it.
All you need to do is to make sure that the desctiption cell is cut to a max lenght (let's say 100 chars, *configurable*) and that whatever past the limit is cut and ... are added.
It would be desirable to have a howver in case of lenghty cells, but this is a desiderata. Let's now focus on the main issue

**Comment by gabryon99** [comment]
As discussed, this is the best solution we have right now.

**Comment by lucaderi** [comment]
As apparently available options won't fix the problem, the best is to doa  workaround to at least avoid the problem

**Comment by simonemainardi** [comment]
Unfortunately the 82250ce9263d4cd9dc7b10c364ad8abaf6c7ae7a breaking all URLs at the arbitrary length of 64 and introduces new issues such as https://github.com/ntop/ntopng/issues/4761.
