### ISSUE TITLE
Add Network Configuration Support

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4682]
Extend ntopng to run on a device such as a RaspberryPI and being able to

- [x] configure Ethernet IP
- [x] configure WiFi: enable/disable/set SSID/set security
- [x] enable bridging (relevant https://www.raspberrypi.org/documentation/configuration/wireless/access-point-bridged.md)

The home router will take care of the DHCP. This ticket is currently limited to Raspberry, then later to other devices/firmware eventually.

**Comment by simonemainardi** [comment]
After internal discussion, we've decided to migrate the system/network configuration already implemented in nEdge to the opensource ntopng.

**Comment by cardigliano** [comment]
Implemented in this patchset:
fdd4305e5a19fbbd9d70ff0e83d6c90f542b6970 4be7f67d35d887f6c828145b021e3506c834b961 973e38587b6d1dfeeef8e635dc328bb29f8e6ca9 d19db6b678e1f4a3bc074bbe91abd9d7a8a6921b 159564bd95cb7f610e1f6fd9e32e5c153968a5ef 9a37185c798983fb2aa8a645ef6e413c3100a97c cb69a60b409d972497ec3309689ffd087a5d9156 9a26717a71fca60c43268a7e4bb918e7de7c4596 67fd78e66ce44baacebcf7c26263c314084081a0
