### ISSUE TITLE
Display ntopng in iframe (x-frame-Option DENY)

### ISSUE THREAD

**Issue by Sen5ation** [ntop/ntopng#4691]
Hi,

I'm using ntopng to monitoring my private LAN. I want to open ntopng in an iframe to display it besides other informations on a dashboard. Unfortunately I always see a x-frame-Option DENY. SO the iframe cannot be displayed.
Is there any way to disable this option? As far as I understand this ntopng launches its own webserver and the only conf file is the ntopng.conf, right?
Do you guys have a solution for my problem?

Thanks!

**Comment by simonemainardi** [comment]
Unfortunately, we cannot allow ntopng to be included in an iframe. We've seen abuses in the past. Feel free to fork it and do the necessary changes if you want.
