### ISSUE TITLE
Flows table is not reponsive

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4692]
I am unable to scroll right to see the Info column in full

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/3397663/98443220-525abd00-210a-11eb-9542-24252c321305.png">

**Comment by simonemainardi** [comment]
same for the service map table

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/3397663/98446725-c05daf00-211f-11eb-9479-33c1d6f5053c.png">

**Comment by yananet** [comment]
Hello, thank you for all the contributions to this nice project.
This issue is critical for me in smartphone, 
what I can see is very limited.
![IMG_4C53E9A413C3-1](https://user-images.githubusercontent.com/5201503/98454228-8e8f2b80-21a5-11eb-932b-9cd60926194a.jpeg)

**Comment by simonemainardi** [comment]
this is how it looks on mobiles:

<img width="315" alt="image" src="https://user-images.githubusercontent.com/3397663/98570025-43633e80-22b3-11eb-99fe-6847a7cb2107.png">

- title is cut in the middle
- dropdowns are not accessible nor scrollable
