### ISSUE TITLE
Issues when installing ntop on Raspbian

### ISSUE THREAD

**Issue by kintarowonders** [ntop/ntopng#4695]
I am running Raspbian buster on a Raspberry Pi 4 8GB, and I am having trouble installing ntop on my system. In the post-install phase it throws an error just after trying to start the process. I did have the ntopng version from Debian's repo and these issues occured after using the ntop upstream repo (packages.ntop.org).

I have tried removing the old ntop and also deleted /var/lib/ntop before install ntop from the upstream, but this has not worked. 

Here is what happens when I try to install...

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ntopng is already the newest version (4.3.201108-12134).
The following packages were automatically installed and are no longer required:
  fonts-font-awesome fonts-glyphicons-halflings libbrotli1 libc-ares2 libcurl3-gnutls libjs-bootstrap libjs-d3 libjs-jquery-form
  libjs-jquery-metadata libjs-jquery-tablesorter libjs-jquery-ui libjs-rickshaw liblua5.3-0 libndpi2.6 libnode64 libuv1
  libwireshark-data node-html5shiv nodejs nodejs-doc
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] 
Setting up ntopng (4.3.201108-12134) ...
Rebuilding ld cache...
(Re)Starting ntopng...
/var/lib/dpkg/info/ntopng.postinst: 81: printf: 8+dfsg1-2: not completely converted
dpkg: error processing package ntopng (--configure):
 installed ntopng package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 ntopng
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by lucaderi** [comment]
@kintarowonders Can you please see what is wrong at line 81 of /var/lib/dpkg/info/ntopng.postinst ?

Or something like

bash -x  /var/lib/dpkg/info/ntopng.postinst 

As you can see below everything works for me and I am wondering what is differnt on your setup from ours

===================

# dpkg -i ntopng_4.3.201108-12134_armhf.deb 
Selezionato il pacchetto ntopng non precedentemente selezionato.
(Lettura del database... 172866 file e directory attualmente installati.)
Preparativi per estrarre .../ntopng_4.3.201108-12134_armhf.deb...
Estrazione di ntopng (4.3.201108-12134)...
Configurazione di ntopng (4.3.201108-12134)...
Rebuilding ld cache...
(Re)Starting ntopng...
Created symlink /etc/systemd/system/multi-user.target.wants/ntopng.service → /etc/systemd/system/ntopng.service.

NOTE

ntopng Community does not require a license.
ntopng Pro/Enterprise licenses are perpetual and include 1 year maintenance/updates:
you can use the software even after maintenance is expired, however updating it after
1 year would prevent ntopng from running. If you have automatic updates enabled, and
maintenance is expired, it is recommended to put the package updates on hold with:

apt-mark hold ntopng

Automatic updates can be enabled again with:

apt-mark unhold ntopng

Elaborazione dei trigger per man-db (2.8.5-2)...
root@pi3:/storage/home/deri/ntopng/packages/ubuntu/debian.ntopng# lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster


======


# dpkg -i ntopng_4.3.201108-12134_armhf.deb 
Selecting previously unselected package ntopng.
(Reading database ... 150075 files and directories currently installed.)
Preparing to unpack .../ntopng_4.3.201108-12134_armhf.deb ...
Unpacking ntopng (4.3.201108-12134) ...
Setting up ntopng (4.3.201108-12134) ...
Rebuilding ld cache...
(Re)Starting ntopng...

NOTE

ntopng Community does not require a license.
ntopng Pro/Enterprise licenses are perpetual and include 1 year maintenance/updates:
you can use the software even after maintenance is expired, however updating it after
1 year would prevent ntopng from running. If you have automatic updates enabled, and
maintenance is expired, it is recommended to put the package updates on hold with:

apt-mark hold ntopng

Automatic updates can be enabled again with:

apt-mark unhold ntopng

Processing triggers for man-db (2.7.6.1-2) ...
root@raspberrypi:/storage/home/deri# lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.1 (stretch)
Release:	9.1
Codename:	stretch

**Comment by lucaderi** [comment]
Seems to work as expected. Will reopen if necessary

**Comment by kintarowonders** [comment]
At line 81 there was this block and I have commented on line 81 with the message LINE 81...

```
`    else
        # Check previous version as up to 4.1.201014
        # service was disabled in prerm during an upgrade
        # This check will be removed at some point
        VERS_DATE=$(echo $PREV_VERSION|cut -d"." -f3|cut -d"-" -f1)
        VERS_MAJ=$(echo $PREV_VERSION|cut -d "." -f 1)
        VERS_MIN=$(echo $PREV_VERSION|cut -d "." -f 2)
        VERS_MAJ=$(printf "%02d" $VERS_MAJ)
        VERS_MIN=$(printf "%02d" $VERS_MIN) #LINE 81
        if [ "$VERS_MAJ$VERS_MIN$VERS_DATE" -lt "0401201015" ]; then
            if hash deb-systemd-invoke 2>/dev/null; then
                deb-systemd-invoke enable ntopng
            else
                systemctl enable ntopng
            fi
        fi
    fi

`
```

**Comment by DerAlSem** [comment]
I'm having the same issue on Ubuntu 20.04

if i echo VERS_MIN and VERS_MAJ
8+dfsg1-2
3

So the problem itself is at line 79. I'm not sure what you want to have there.

**Comment by simonemainardi** [comment]
@cardigliano can you please check this?

**Comment by cardigliano** [comment]
@DerAlSem I am pushing a fix for this. Just to make sure, could you echo $PREV_VERSION ?

**Comment by DerAlSem** [comment]
@cardigliano weird thing here. I've commented almost all the block, only leaving the line with enabling system service

```
        # service was disabled in prerm during an upgrade
        # This check will be removed at some point
        #VERS_DATE=$(echo $PREV_VERSION|cut -d"." -f3|cut -d"-" -f1)
        #VERS_MAJ=$(echo $PREV_VERSION|cut -d "." -f 1)
        #VERS_MIN=$(echo $PREV_VERSION|cut -d "." -f 2)
        #VERS_MAJ=$(printf "%02d" $VERS_MAJ)
        #VERS_MIN=$(printf "%02d" $VERS_MIN) #LINE 81
        #if [ "$VERS_MAJ$VERS_MIN$VERS_DATE" -lt "0401201015" ]; then
            #if hash deb-systemd-invoke 2>/dev/null; then
              #  deb-systemd-invoke enable ntopng
            #else
                systemctl enable ntopng
            #fi
        #fi
```

Installation went flawlessly.

Now i'm trying to replicate the issue - and it's gone... echo PREV_VERSION gives nothing as far as i can tell...

**Comment by cardigliano** [comment]
Uhm, PREV_VERSION should be set on package upgrade..

**Comment by cardigliano** [comment]
Anyway, I pushed a safety check, please let us know if it happens again or you are able to print the PREV_VERSION

**Comment by DerAlSem** [comment]
This makes sense.

I had some 3.x version installed manually ages ago. Yesterday i've noticed "please upgrade" message in the web ui.

I've added ntop repo and tried to upgrade. It's actually upgraded, despite the fact having "dpkg exited with error". But still every time i tried to APT UPGRADE it throwed me dpg error.

Then i googled this issue.

Reported to you, REMOVED ntopng, installed it, had the same issue, left only one line in SERVICE INSTALL block and it installed. 

Will watch it and report if it appears again.

Thanks!
