### ISSUE TITLE
Feature request - exporter/user

### ISSUE THREAD

**Issue by arnovdveen** [ntop/ntopng#4699]
Now interface or network can be used as selector to view data under a user.
would be good to have the option for exporter(s) to be selected under users.

**Comment by simonemainardi** [comment]
Please comment

- Did you know you can pick the exporter from the active flows dropdown?
- Did you consider using Interface disaggregation with Probe IP?

Explain why your use case doesn't fall in any of the above

**Comment by simonemainardi** [comment]
No feedback received. Closing.
