### ISSUE TITLE
No ZMQ interface speed detected

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#470]
MikroTik is sending netflow to nprobe port 2055

```
nprobe --zmq "tcp://*:5556" -i none -n none --collector-port 2055

cat /etc/ntopng/ntopng.conf
-d=/var/tmp
-i=tcp://127.0.0.1:5556
-G=/var/tmp/ntopng.pid
-w=3000

2.3.160331 - Professional Edition
```

host + flows + protocols data is shown but not interface aggregated traffic:

![image](https://cloud.githubusercontent.com/assets/3397663/14213028/054e0226-f836-11e5-9abf-e299546c9518.png)

![image](https://cloud.githubusercontent.com/assets/3397663/14213034/11353ac8-f836-11e5-9b89-7f1f70bd2c15.png)

![image](https://cloud.githubusercontent.com/assets/3397663/14213048/29d9a78a-f836-11e5-81b6-a895fc4723f8.png)

**Comment by inetactief** [comment]
We update our versions: 
nprobe 7.3.160405-4999
ntopng 2.3.160405-1037
And do sudo systemctl restart ntopng and start again : nprobe --zmq "tcp://*:5556" -i none -n none --collector-port 2055 
But same problem!

**Comment by simonemainardi** [comment]
@inetactief can you bind your nProbe to a public address so I can use a remote ntopng to debug?

thank you

**Comment by inetactief** [comment]
Yes, let me know what i must do..

**Comment by simonemainardi** [comment]
just make sure
- the nProbe host is reachable from a public IP address
- the nProbe process is bound to that public IP address

say for example public ip is x.y.z.w, you can do `nprobe --zmq "tcp://*:5556" -i none -n none --collector-port 2055` and from remote I can do 

```
cat /etc/ntopng/ntopng.conf
-d=/var/tmp
-i=tcp://x.y.z.w:5556
-G=/var/tmp/ntopng.pid
-w=3000
```

**Comment by lucaderi** [comment]
Sorry @simonemainardi the answer is not correct. The speed cannot be detected as nprobe is NOT capturing from a physical device but ti is used as collector (i.e. the mikrotik does not advertise the speed). So this is not a bug but a limitation of the sender

**Comment by simonemainardi** [comment]
please, navigate to the interface statistics page and check the historical interface speed chart.

**Comment by inetactief** [comment]
Hi Simone,

I check it, its empty, see the sreenshot.

Best regards,

Michel

**Comment by simonemainardi** [comment]
@inetactief sorry about that, the message was meant to be addressed to #488

**Comment by inetactief** [comment]
Mikrotik support ask me? can you specify what you exactly are not receiving:
*) interface speed (data tx/rx)
*) interface speed (maximum transferable amount)
Can somebody help me? It wil be nice to view al functions from the mikrotik see in ntopng :+1:

**Comment by simonemainardi** [comment]
@inetactief we made some enhancements to the latest dev versions in order to capture the interface speed even when the nprobe is used as a collector of netflow devices.

please, make sure to upgrade both ntopng and nprobe.
