### ISSUE TITLE
More granular RBAC

### ISSUE THREAD

**Issue by arnovdveen** [ntop/ntopng#4700]
Roles:
Technical administrator - Change technical settings, create interfaces ,etc 
Security manager - Can change all, but technical settings 
Analyst - Can only read 
Auditor - can only view logs (audit log/user log etc)

Groups:
self defined groups where networks/interfaces/exporters can be selected users of a group can only see information under those selected networks/interfaces/exporters.

**Comment by simonemainardi** [comment]
This concept of roles will be implemented using the bitmap of auth privileges implemented in https://github.com/ntop/ntopng/issues/4489

What is missing is the UI part to allow this bitmap to be configured.

**Comment by cardigliano** [comment]
User roles can be currently defined when creating/editing the user and include a capability bitmap and additional settings (e.g. visible networks)
