### ISSUE TITLE
Issues Docker Hub command error

### ISSUE THREAD

**Issue by magicansk** [ntop/ntopng#4701]
In the official docker hub the command below had two error: 
`docker run -it -p 3000:3000 --v $(pwd)/ntopng.license:/etc/ntopng.license:ro -net=host ntop/ntopng:stable -i eth0`
![image](https://user-images.githubusercontent.com/30593595/98651711-74f9fb00-22ef-11eb-97e0-4b20e15c241b.png)

1.  `--v` won't work. It should be `-v` (short option)
2. `-net`=host should be `--net`=host (long option)

**Comment by cardigliano** [comment]
Fixed thank you
