### ISSUE TITLE
public scope datasources are not working

### ISSUE THREAD

**Issue by RicterZ** [ntop/ntopng#4703]
https://github.com/ntop/ntopng/blob/dev/src/HTTPserver.cpp#L969-L979
Record the code, a public scope datasource can be accessed by a anonymous user. But in fact it doesn't work.

Because of the datasource URI `/datasources/*ds_hash*` is not a `static resource url`. 
https://github.com/ntop/ntopng/blob/dev/src/HTTPserver.cpp#L1050

**Comment by simonemainardi** [comment]
can you provide a PR with the fix?

**Comment by RicterZ** [comment]
I'll try.

Simone Mainardi <notifications@github.com> 于 2020年11月11日周三 下午10:04写道：
