### ISSUE TITLE
Changing an application category

### ISSUE THREAD

**Issue by bonald** [ntop/ntopng#4704]
nEdge v.4.3.201109
When assigning an application to a different category and restarting nEdge, the category is still the old one when looking at flows and traffic is still being shaped as old category shaper.

![image](https://user-images.githubusercontent.com/12394874/98689741-9801ca80-2342-11eb-87fd-ed5fc3cf5da2.png)
![image](https://user-images.githubusercontent.com/12394874/98689854-b5cf2f80-2342-11eb-9950-b694f32a7eb3.png)

**Comment by simonemainardi** [comment]
Fixed in the latest nEdge 5.0+.
