### ISSUE TITLE
Annoying message about the community license in ntopng 4.3

### ISSUE THREAD

**Issue by daxrob** [ntop/ntopng#4708]
Hi,

I just installed the latest 4.3 version of ntopng. Now I am receiving this annoying message all the time I refresh a page:
Community edition forced with --community. Remove this option to make license changes effective.
Is it possible to avoid that?

Thanks
Rob

**Comment by simonemainardi** [comment]
@gabryon99 has this already been addressed as discussed?

**Comment by lucaderi** [comment]
@darox This message appears only if you have a ntopng.license and user --community. Is this your case?

**Comment by darox** [comment]
It's not me @dariox it's @daxrob ;)

**Comment by lucaderi** [comment]
Sorry @darox

**Comment by daxrob** [comment]
Hi don’t have any license, so I use the community option
