### ISSUE TITLE
Refactor Backend System Configuration to Opensource

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4713]
Currently, nEdge allows backend system and netfilter configuration in module `nf_config.lua`.

It is requested to refactor `nf_config.lua` into:
- `appliance_config.lua` handling only system configuration (i.e., setup of network interfaces, names, addresses, DHCP)
- `nf_config.lua` handling nEdge-related netfilter and routing configuration

I would move from `nf_config.lua` to `applicance_config.lua` the following functions:
1. Facilities to read and guess initial system configuration
2. Facilities to write/read/apply new configurations
3. Facilities to setup network interfaces, bridge, addresses, DHCP, security, date and time, misc

Then i would change `nf_config.lua` to inherit from `applicance_config.lua` and implement the rest of nEdge-specific configurations.

Place `applicance_config.lua` in the opensource part of ntopng and keep `nf_config.lua` in the code of nEdge.

**Comment by cardigliano** [comment]
This has been implemented in ba9c501c4dd65d3e836bfed1fae72c3f80e7967a, system_config.lua implements a "superclass", nf_config.lua inherits from system_config.lua all teh methods which are in common with applicance_config.lua. The appliance_config implementation is in progress (please see https://github.com/ntop/ntopng/issues/4714)
