### ISSUE TITLE
Add --appliance Option to Allow System Configuration

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4715]
It is requested to add a (currently hidden) `--appliance` option to ntopng which shows and allows system configuration a-la nEdge in

![image](https://user-images.githubusercontent.com/3397663/99057473-1c9b5580-259c-11eb-9cd0-9dcdcf3231ac.png)

This depends on https://github.com/ntop/ntopng/issues/4713 and  https://github.com/ntop/ntopng/issues/4714

The only configuration shown with this mode would involve system setup as described in https://github.com/ntop/ntopng/issues/4682

**Comment by cardigliano** [comment]
The --appliance option has been implemented, more work has to be done on the backend (see https://github.com/ntop/ntopng/issues/4714)
