### ISSUE TITLE
Instantiate nf_config or appliance_config depending on the operating mode

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4716]
Once https://github.com/ntop/ntopng/issues/4713 is implemented, it is requested to change the frontend code https://github.com/ntop/ntopng/issues/4714 to either instantiate `nf_config.lua` or `applicance_config.lua` depending on the operating mode, that is if nEdge is in use or if `--appliance` is in use.

**Comment by cardigliano** [comment]
This conditional instantiation has been implemented (the appliance implementation is in progress, see https://github.com/ntop/ntopng/issues/4714)
