### ISSUE TITLE
The Name for Local hosts was Change to the Name where ntopng sees on DHCP Traffic first and not DNS Names

### ISSUE THREAD

**Issue by andiyk** [ntop/ntopng#4717]
ntopng Enterprise M v.4.2.201112 

Problem:
the Name for Local hosts was Change to the Name where ntopng sees on DHCP Traffic:

![image](https://user-images.githubusercontent.com/23166953/99068110-317fe500-25ac-11eb-9c10-d868bd993e2f.png)

but the right DNS Name still exist:

![image](https://user-images.githubusercontent.com/23166953/99068201-51afa400-25ac-11eb-8c32-c27ebb324a28.png)

**Comment by andiyk** [comment]
![ntopng_Name_Problem](https://user-images.githubusercontent.com/23166953/99069748-427e2580-25af-11eb-9fa1-d13d09d1f64d.jpg)


All this Hosts a really FritzBoxes, but different IP´s and (correctly Resolved) Hostnames

**Comment by simonemainardi** [comment]
we believe for hosts in the broadcast domain, the DHCP name should be favoured over the DHCP one as in 

https://github.com/ntop/ntopng/blob/d59c9b9e7d6756c6e9823ea1db4a04a3bccd31d7/src/Host.cpp#L698

You still have all the dissected names available in the host details.

**Comment by andiyk** [comment]
Ok. Is it possible to implement the Priority of the Name Resolution in the Settings? I believe the Name Resolution to DHCP Names is great for small (Home Networks), but for midsize/big Networks (with working lokal DNS Server), it should be resolved to the DNS Name.
The problem was noticed as i see the "Top Local Talkers" on the Dashboard. All Entries there was unusable.

**Comment by simonemainardi** [comment]
@lucaderi what do you think about giving priority to DNS over DHCP when chosing the name?

**Comment by simonemainardi** [comment]
Implemented as requested. A new build is in progress and will be ready in the next couple of hours.
