### ISSUE TITLE
Add user token in user settings

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4721]
In user settings

![Screen Shot 2020-11-13 at 19 34 00](https://user-images.githubusercontent.com/4493366/99108140-36ae5580-25e7-11eb-9a7c-7c2725486c89.png)

add a new tab named token with a button to generate a user token to be used by the REST API. Such token must be stored persistently. Next to the token field a "copy" button must be added so that the generated token (if not empty) can be copied to the dashboard

**Comment by simonemainardi** [comment]
Backend implemented. REST API to generate tokens available at `http://localhost:3000/lua/rest/v1/create/ntopng/api_token.lua`
