### ISSUE TITLE
Using ntopng and edgeOS

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#4724]
Hi i have an Ubiquiti EdgeRouter-X and a ntopng server and i was wondering. Could someone please help me to capture data from the router (edgerouter) and send it to my ntopng server. This would also be useful for anyone with a Ubiquiti router as they all run edgeOS.

thanks,
daniel2029

**Comment by lucaderi** [comment]
We did thate exercise years ago when ported our nprobe to it. Unfortunately Uniquity is now using most of the available space and adding an extra package (at least on EdgeRouter-X) is a problem. On larger products you can run our tools as described here https://github.com/tusc/ntopng-udm

**Comment by ghost** [comment]
i see thanks Luca

**Comment by blumberg-git** [comment]
Agree with you regarding free space on ER-X. What about ER4 or ER8-XG with plenty of free space. Will ntop work?

**Comment by simonemainardi** [comment]
@lucaderi
