### ISSUE TITLE
DGA alarms do not report the domain name

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4725]
![Screen Shot 2020-11-14 at 19 21 58](https://user-images.githubusercontent.com/4493366/99154276-dc78c780-26ae-11eb-96fc-1f9e273ac355.png)

This is a more generic problem that should be addressed for all alerts generated usign the score: they should report what and not just why, went wrong so security/network analysts can analize the issue.

**Comment by triple-it** [comment]
Yes please!
Because all those DGA alarms are now useless. Is there a suggested work-around/patch to retrieve the alarming DGA domain names anyway?

**Comment by triple-it** [comment]
I don't see much scripts putting in any extra information into the alerts on
./scripts/plugins/alerts/security/flow_risks/modules/*

The only module doing something extra is "ndpi_known_protocol_on_non_standard_port_handler.lua"

```
  -- Set the flow status and trigger an alert when a known protocol is found to use a non-standard port
   local alert = alert_consts.alert_types.alert_known_proto_on_non_std_port.new(
      flow.getInfo()
   )

```

So how to get the extra 'triggered' domain data into the alert?


BTW from the nDPI library I found the dga_evaluate:
```
"
./dga/dga_evaluate dga/domain_test_file -h
     [DGA]      0024c6f216c3.koalabox.net
     [DGA]      0131923v.index-education.net
     [DGA]      0132325g.index-education.net
     [DGA]      018ba44e69d325073fd54265b5afd0a5.safeframe.googlesyndication.com
...


```

The file that is generating the DGA alerts is: ndpi_suspicious_dga_domain_handler.lua

```
# grep -Hrin dga *
ndpi_suspicious_dga_domain_handler.lua:19:   local alert = alert_consts.alert_types.alert_ndpi_suspicious_dga_domain.new()
#
```

Maybe we can add something to alert_ndpi_suspicious_dga_domain.new(....) ?
