### ISSUE TITLE
10GB interface seen as 1GB using zbalance pfring

### ISSUE THREAD

**Issue by narankhetani** [ntop/ntopng#473]
noticed that ntopng see’s the interface as a 1gb and not 10gb see attached below:
set to 10GB
![screen shot 2016-04-04 at 11 14 15 am](https://cloud.githubusercontent.com/assets/5029683/14248615/6b0ce490-fa6d-11e5-9d01-425a19de0dfc.JPG)

and as you can see its seen as a 1GB interface which messes with the graphing and not sure if it causes any limitations?:
![screen shot 2016-04-04 at 11 13 59 am](https://cloud.githubusercontent.com/assets/5029683/14248639/8871ad72-fa6d-11e5-8b1c-99d486ce6c51.JPG)

I am using the following with zbalance:
`
zbalance_ipc -i zc:eth0 -c 99 -n 1,1,1 -m 1 -S 14 -g 1 -d -g 15 -P /var/tmp/zbalance_ipc-eth0.pid
`

**Comment by lucaderi** [comment]
@narankhetani At the moment tehere is no way for us to know the interface speed via ZC.
