### ISSUE TITLE
Reset list of learnt MAC addresses

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4730]
![Screen Shot 2020-11-16 at 12 53 22](https://user-images.githubusercontent.com/4493366/99249648-bb2cee00-280a-11eb-8fd6-e10fd8885545.png)

Add a button to reset the list of learnt MAC addresses

**Comment by simonemainardi** [comment]
Can't see the button. Is this still a WIP?

**Comment by gabryon99** [comment]
A button has been implemented, see the file:
`scripts/plugins/alerts/security/unexpected_new_device/user_scripts/interface/unexpected_new_device.lua`.

Here's a list of parameters used by the button:
 * `input_action_i18n`: `string` = Is the label title show in the button;
 * `input_action_url`: `string` = Is the endpoint for the AJAX request performed by the button;
 * `input_action_confirm`: `boolean` = Indicates if the action requires a further confirm by the user;
 * `input_action_i18n_confirm`: `string` = The text shown inside the confirm modal.
