### ISSUE TITLE
No error reported

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4732]
![Screen Shot 2020-11-16 at 16 52 39](https://user-images.githubusercontent.com/4493366/99275952-6ac68800-282c-11eb-949f-054a52d5085a.png)

**Comment by lucaderi** [comment]
Workign but remove the limit of 4 letters host (symbolic)

**Comment by lucaderi** [comment]
![Screen Shot 2020-11-19 at 17 58 12](https://user-images.githubusercontent.com/4493366/99698219-d0b34980-2a90-11eb-8cb6-a86c67d9a5ae.png)

Please use short URLs

**Comment by simonemainardi** [comment]
URLs for infrastructure monitoring shortened.
