### ISSUE TITLE
Default ntopng index name not accepted

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4734]
![Screen Shot 2020-11-16 at 18 39 27](https://user-images.githubusercontent.com/4493366/99287887-1f67a600-283b-11eb-80c9-d25e6ada3d57.png)

**Comment by simonemainardi** [comment]
Now hyphens are allowed in index names. It is ok NOT to allow % to specify date format as the date format is decided by ntopng. Indeed as documented also in the note,  the <index> specified is suffixed with date information by ntopng.

Use `data-pattern="singleword` to validate your forms.

**Comment by simonemainardi** [comment]
Fixed in https://github.com/ntop/ntopng/commit/25d49486731235daaff28d196dda1a6ed707e056
