### ISSUE TITLE
Periodic activity 'periodic_user_scripts.lua' is queued but has not been executed

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4736]
The number of threads that execute periodic activities is too little when network interfaces are high as the number of available threads is not enough to serve all interfaces causing periodic activities to hang indinitively, This in particular with dynamic interfaces that are create when disaggregative data.

**Comment by simonemainardi** [comment]
User reported the issue is solved and the software has been running smoothly for 4+ days. Fix backported to stable as well.
