### ISSUE TITLE
Where do I modify the -x/y values?

### ISSUE THREAD

**Issue by DrToxo** [ntop/ntopng#4739]
Obviously going to be in the one place I haven't looked, but Ive gone through all of the menus/options and cant find this value to tune.  Dropping  a lot of flows but cpu only about 50%, so hoping tuning the values will fix this issue.

_**_Too many flows for ntopng leading to packet drops and high CPU load. Please tune -x/-X and restart ntopng_**_

Cheers

**Comment by simonemainardi** [comment]
You need to modify the ntopng configuration file and add

```
-X="<value>"
-x="<value>"
```

See https://www.ntop.org/guides/ntopng/how_to_start/configuration_file.html

**Comment by DrToxo** [comment]
Cheers

Sorry but I cant find this file in Windows and no mention of where it should be in the docs...

**Comment by DrToxo** [comment]
Ah, ok, so I have to create the file manually then start from cli...

**Comment by simonemainardi** [comment]
on windows you can follow the instructions at: https://www.ntop.org/guides/ntopng/how_to_start/running_on_windows.html

so basically you would

```
c:\Program Files\ntopng>ntopng /r
c:\Program Files\ntopng>ntopng /i -X <value> -x <value>
ntopng installed.
c:\Program Files\ntopng>
```
