### ISSUE TITLE
Propose setting interface speed with ntopng command-line parameter

### ISSUE THREAD

**Issue by skendric** [ntop/ntopng#474]
BACKGROUND
Interface speed is chosen by querying the ntopng host's NIC.  However, this is not necessarily accurate when ntopng is pulling flow traffic from an nProbe via zmq.  As a work-around, we can set interface speed by clicking on the traffic gauge and typing into the "Interface Speed (Mbit)" box.

For a large number of interfaces, this manual approach becomes tedious & error-prone.

PROPOSE
I propose optionally setting this parameter via a command-line argument, a modification to the '--interface' parameter.  This feature might look as follows:

ntopng ... --interface tcp://10.1.2.3:5556/10000

In the above example, the "/10000" would indicate that the speed of the remote sender is 10GigE 

EXTRA CREDIT
To make the feature even easier to use, permit several syntaxes, including:
10Mbs
100Mbs
1Gbps
10Gbps
...
ntopng ... --interface tcp://10.1.2.3:5556/10Gbps

I suggest this because the human process of visually counting zeros (10000) is another error-prone process.

**Comment by simonemainardi** [comment]
We believe setting the interface speed manually using the gauge is the best approach as adding an extra item to the command line interface name would unnecessarily complicate the syntax. In addition, recent version of the nProbe communicate the right interface speed over ZMQ.
