### ISSUE TITLE
Show an informative message when the token is not present

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4740]
Rather than showing an empty form, show a message telling no token generated yet

![image](https://user-images.githubusercontent.com/3397663/99428182-99b12c80-2906-11eb-86a4-fb4bb046f440.png)

**Comment by gabryon99** [comment]
<img width="805" alt="Screenshot 2020-11-17 at 19 04 36" src="https://user-images.githubusercontent.com/14114916/99429051-c0239780-2907-11eb-8e74-c8ca9abeef41.png">

Inserted a message when no token has been generated.
