### ISSUE TITLE
Add alert when there are too many export drops

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4742]
When ntopng is configured with -F and the flow dump endsystem (e.g MySQL) is slow there are drops (see the image below)
![Screen Shot 2020-11-18 at 09 48 17](https://user-images.githubusercontent.com/4493366/99507077-387b6e80-2983-11eb-8e04-a20f125b8710.png)
ntopng should open a warning window (this is an info just as example)

![](https://user-images.githubusercontent.com/4493366/99413305-ee987700-28f5-11eb-8de3-0b0ad254a9dc.png)

where ntopng explains the problem and proposes either remove -F or use a faster storage. The window must stay visible (unless dismissed) as long as there are export drops.

**Comment by simonemainardi** [comment]
I would also make export drop color and severity variable. That is, info and not shown in the header if < 10%, then yellow if < 20%, then red.

**Comment by simonemainardi** [comment]
Dump is enabled from the preferences if `is_dump_flows_enabled` is set to true

**Comment by simonemainardi** [comment]
example

```
ntop.getPrefs()["is_dump_flows_enabled"]
```
