### ISSUE TITLE
Invalid behavior of manage user

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4744]
When clicking on the user

![image](https://user-images.githubusercontent.com/3397663/99523206-070c9e00-2997-11eb-982a-0fba7e83ad73.png)

- modal is open on the second tab but it should be open on the first tab

![image](https://user-images.githubusercontent.com/3397663/99523249-168be700-2997-11eb-80e7-47d547e15d58.png)

- changing the password re-opens the modal, whereas changing preferences (language) closes the modal. Expected behavior is always to close the modal.

![image](https://user-images.githubusercontent.com/3397663/99523311-2efc0180-2997-11eb-82cd-43b175cc9061.png)

- user name is missing from the modal title for non-admin users

![image](https://user-images.githubusercontent.com/3397663/99523388-4f2bc080-2997-11eb-8ce3-929ef73e82d1.png)

**Comment by gabryon99** [comment]
I changed the tabs order because there is a tick that requested a shortcut to change the selected language (#4583). I improved the button looking inside the user menu and fixed the reload as you suggested.

**Comment by simonemainardi** [comment]
confirmed as working.
