### ISSUE TITLE
The name of the instance cannot be empty

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4745]
![image](https://user-images.githubusercontent.com/3397663/99525500-31ac2600-299a-11eb-8cb1-e70d82f11718.png)

- The name is not empty
- An invalid name should disable the "Add" button

**Comment by gabryon99** [comment]
The problem was with the validation inside http_lint, fixed in the latest commit inside the pro repository.

**Comment by simonemainardi** [comment]
The name of the instance is still invalid:

![image](https://user-images.githubusercontent.com/3397663/99643404-ea32a200-2a4c-11eb-9e98-ad0c2c10d944.png)

**Comment by simonemainardi** [comment]
still invalid

![image](https://user-images.githubusercontent.com/3397663/99701281-892ebc80-2a94-11eb-9d2a-4d57bceb8279.png)

**Comment by simonemainardi** [comment]
Fixed in the latest build
