### ISSUE TITLE
Invalid URL validation

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4746]
No errors, no complains, and the data is submitted properly

![image](https://user-images.githubusercontent.com/3397663/99534778-3f68a800-29a8-11eb-866a-f9aaf57d4bf3.png)

**Comment by simonemainardi** [comment]
this also breaks the dashboard page once submitted

**Comment by gabryon99** [comment]
The input validation for the URL has been added, check the latest commit in the pro repository.

**Comment by simonemainardi** [comment]
URL validation still invalid:

I'm unable to submit this

![image](https://user-images.githubusercontent.com/3397663/99643128-9c1d9e80-2a4c-11eb-96c2-813ca13a1f78.png)
