### ISSUE TITLE
Invalid TOKEN validation

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4747]
Token is not validated and invalid tokens can be submitted, resulting an a broken page.

I can submit this stuff
![image](https://user-images.githubusercontent.com/3397663/99535034-a1c1a880-29a8-11eb-982b-af88ae3c9d10.png)

And then I end up in a broken dashboard hanging like this

![image](https://user-images.githubusercontent.com/3397663/99535091-b4d47880-29a8-11eb-8af5-1a1871993a5c.png)

Token MUST be validated as a 32-chars hex string

**Comment by gabryon99** [comment]
The input validation has been added, check the latest commit in the pro repository.

**Comment by simonemainardi** [comment]
Validation of the TOKEN is still invalid.

> Token MUST be validated as a 32-chars hex string

Here you allow any 32-chars string as valid https://github.com/ntop/ntopng/commit/f2037d45f8d496f70ec0385481db8bfecf2c3ed7#diff-f5b7a9604d8342d8ecd38943100033332207ec705becb45e69a9586d8b0b09b2R1157

In addition, no traceError should be used inside validation functions
