### ISSUE TITLE
Custom interface name doesn't save

### ISSUE THREAD

**Issue by DrToxo** [ntop/ntopng#4750]
ntopng Enterprise L v.4.3.201103 

Trying to rename the interface using the Custom Name field, but when I click save, it simply reverts back to the default interface card name.

**Comment by simonemainardi** [comment]
Are you using this?

![image](https://user-images.githubusercontent.com/3397663/99702635-57b6f080-2a96-11eb-96a4-bf46ea940436.png)

It seems it correctly assigns the name. Are you on Win correct?

**Comment by DrToxo** [comment]
Yep, when I enter it and select save, it reverts back to the default "Intel(R) PRO/1000 PT Quad Port LP Server Adapter"  Ive tried various names and avoided spaces and other special characters.  So as far as the names go, both interfaces have exactly the same name.

**Comment by DrToxo** [comment]
Anything I can try to resolve this?

**Comment by DrToxo** [comment]
Seems that I cant even save a traffic profile.. so must be a write/permission type issue... but Ive just installed it on a windows domain pc using my AD account that has admin privileges.
