### ISSUE TITLE
TLS certificate validity dissection possibly not valid

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4751]
End date seems to be less than begin date

![image](https://user-images.githubusercontent.com/3397663/99656226-ec046180-2a5c-11eb-8f71-acfc720219ce.png)

Using the browser certificate inspector, seems the start date has been correctly dissected but not the end date:

![image](https://user-images.githubusercontent.com/3397663/99656389-19510f80-2a5d-11eb-88c9-9b1618ffef26.png)

![image](https://user-images.githubusercontent.com/3397663/99656373-148c5b80-2a5d-11eb-8126-1d04cb6ee2ab.png)

**Comment by lucaderi** [comment]
![Screen Shot 2020-12-11 at 19 02 47](https://user-images.githubusercontent.com/4493366/101938395-8c285300-3be3-11eb-9024-567841e0c392.png)
![Screen Shot 2020-12-11 at 19 02 42](https://user-images.githubusercontent.com/4493366/101938404-8f234380-3be3-11eb-84d2-2dcd7f8bba65.png)

Works for me. Any URL you want me to test?

**Comment by lucaderi** [comment]
verified as working with the current nDPI+ntopng
