### ISSUE TITLE
Strange interface performance 

### ISSUE THREAD

**Issue by DrToxo** [ntop/ntopng#4752]
Ive notice a strange pattern when looking at any interface charts and cant figure out the cause.  

Every 5-10m the flow drops right down to about 30%, despite the fact that if I look at the physical interface performance in Windows, its a constant flat line at around 800mbps on a gig interface.  

![image](https://user-images.githubusercontent.com/16386651/99655857-1a317380-2a54-11eb-9ce0-29d10a9fe9cf.png)

![image](https://user-images.githubusercontent.com/16386651/99656443-ca9f7780-2a54-11eb-89c5-7135177ba234.png)

This is a new build on W10 with a 4 port nic of which 2 interfaces are span ports that mirror our 2 internet links.  We don't use nprobe (I don't think this is required for our use case).  

Still getting my bearings with ntopng, its certainly a beast of an app with a bit of a learning curve!  Such an awesome product!

4.3.201103 (10489) - Enterprise L Edition
--

**Comment by DrToxo** [comment]
Also found lots of these errors:

9/Nov/2020 11:02:17 [LuaEngineNtop.cpp.inc:5175] ERROR Error 'fetching cdp from rra' while calling rrd_fetch_r(C:\Windows\ServiceProfiles\ntopng\Documents\ntopng\4\rrd\\bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
19/Nov/2020 11:02:17 [LuaEngineNtop.cpp.inc:5175] ERROR Error 'fetching cdp from rra' while calling rrd_fetch_r(C:\Windows\ServiceProfiles\ntopng\Documents\ntopng\3\rrd\\bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
19/Nov/2020 11:02:17 [LuaEngineNtop.cpp.inc:5175] ERROR Error 'fetching cdp from rra' while calling

The build we have is pretty much out of the box, so Im reading through the docs for best practices.

**Comment by DrToxo** [comment]
Dont think the rrd error has antyhing to do with original post, but I did just notice this:

20/Nov/2020 15:28:28 [LuaEngineNtop.cpp.inc:5175] ERROR Error 'fetching cdp from rra' while calling rrd_fetch_r(C:\Windows\ServiceProfiles\ntopng\Documents\ntopng\5\rrd**\\**bytes.rrd, AVERAGE): is the RRD corrupted perhaps?

Is this  "\\" an issue, but I didn't notice it for any of the above but they were for g\3\rrd\bytes.rrd and g\4\rrd\bytes.rrd not 5.

**Comment by lucaderi** [comment]
I suggest to look at the packet drops and see what are the reported values. You have a lot of traffic for WInpcap so this can also be part of the equation.

**Comment by lucaderi** [comment]
We have tested the latest release (late Dec) and not seen the behaviour you are reporting. Please update and let us know if it works. Closing for the time being, please reopen if necessary
