### ISSUE TITLE
GRE Detunneling not working as expected

### ISSUE THREAD

**Issue by ThePoshArchitect** [ntop/ntopng#4754]
gre packets arriving at the ntopng listening interface arnt being displayed in the ntopng web console.

When running "tcpdump -i ens192 proto gre" from the ntop server cli I can see the gre packets

is there a limitation in ntopng where it cant extract the data form the gre packet?

If I generate the PCAP file and open it in wireshark I can see the gre packet and the contents

**Comment by simonemainardi** [comment]
GRE traffic is detunnelled automatically so I would expect to see the contents of the GRE packets inside ntopng. If this is not the behavior you are experiencing, please attach a pcap so I can check.

**Comment by ThePoshArchitect** [comment]
Hi Simone,

Please see attached , it seems like the protocol in the tunnel is unknown which is odd.

[ens192_live.zip](https://github.com/ntop/ntopng/files/5589331/ens192_live.zip)

**Comment by simonemainardi** [comment]
There are only three packets with GRE in the pcap. All the rest are untunnelled packets with data that cannot be decoded also by Wireshark.

**Comment by simonemainardi** [comment]
Closing as there's nothing odd in the ntopng behavior using the submitted file which contains only three GRE-tunneled packets. Reopen as submit a pcap with which the issue can be reproduced if necessary
