### ISSUE TITLE
Ntop stops with message demo time elapsed get a valid license but license is installed

### ISSUE THREAD

**Issue by hhs-itservices** [ntop/ntopng#4755]
below is   the output

n2disk@enp1s0f1.service: Succeeded.
19/Nov/2020 16:23:18 [n2disk.c:7486] Compression thread #1 terminated
19/Nov/2020 16:23:18 [n2disk.c:7486] Compression thread #0 terminated
19/Nov/2020 16:23:18 [n2disk.c:7476] Writer thread #0 terminated
19/Nov/2020 16:23:18 [n2disk.c:7456] Reader thread terminated
19/Nov/2020 16:23:18 [n2disk.c:5604] Packet capture thread terminated
error unlink'ing /dev/hugepages/enp1s0f1@0-rx: Permission denied
19/Nov/2020 16:23:16 [n2disk.c:1193] Average Capture Throughput: 0.00 Gbit / 0.00 Mpps
19/Nov/2020 16:23:16 [n2disk.c:1191] Capture Duration: 0:00:07:12:300
19/Nov/2020 16:23:16 [n2disk.c:1187] [n2disk] Processed 147721 pkts
19/Nov/2020 16:23:16 [n2disk.c:1174] [PF_RING] Total stats: 147721 pkts rcvd/147721 pkts filtered/0 pkts dropped [0.0%]
19/Nov/2020 16:23:16 [n2disk.c:1335] Caught termination signal 15...
#########################################################################
Demo time elapsed please get a valid license
#########################################################################

**Comment by cardigliano** [comment]
@hhs-itservices please note that the right place for this issue is https://github.com/ntop/n2disk/issues
Could you provide n2disk -V? Your order id would also be useful (please send it to cardigliano at ntop.org)

**Comment by cardigliano** [comment]
@hhs-itservices could you provide your n2disk configuration file?

**Comment by hhs-itservices** [comment]
Hi @cardigliano,
Here is the n2disk configuration file for each interface
/etc/n2disk$ cat n2disk-enp1s0f0.conf 
```
--interface=zc:enp1s0f0
--dump-directory=/var/lib/ntopng/zc/enp1s0f0/pcap
--timeline-dir=/var/lib/ntopng/zc/enp1s0f0/timeline
--disk-limit=614400
--max-file-len=1000
--buffer-len=4000
--max-file-duration=60
--index
--snaplen=1536
--writer-cpu-affinity=0
--reader-cpu-affinity=1
--compressor-cpu-affinity=2,3
--index-on-compressor-threads
-u=ntopng
--zmq=tcp://127.0.0.1:5556
--zmq-probe-mode
--zmq-export-flows
```
/etc/n2disk$ cat n2disk-enp1s0f1.conf 
```
--interface=zc:enp1s0f1
--dump-directory=/var/lib/ntopng/zc/enp1s0f1/pcap
--timeline-dir=/var/lib/ntopng/zc/enp1s0f1/timeline
--disk-limit=614400
--max-file-len=1000
--buffer-len=4000
--max-file-duration=60
--index
--snaplen=1536
--writer-cpu-affinity=0
--reader-cpu-affinity=1
--compressor-cpu-affinity=2,3
--index-on-compressor-threads
-u=ntopng
--zmq=tcp://127.0.0.1:5557
--zmq-probe-mode
--zmq-export-flows
```

**Comment by cardigliano** [comment]
Could you check your ZC license for enp1s0f0 and enp1s0f1 ? (Please take a look at pfcount -L -v 1)
Btw I improved the warning to clearly identify the issue next time.

**Comment by hhs-itservices** [comment]
$ pfcount -L -v 1
Name	SystemName	Module	MAC	BusID	NumaNode	Status	License	Expiration
lo	lo	pf_ring	00:00:00:00:00:00	0000:00:00.0	-1	Up	NotFound	0
enp9s0	enp9s0	pf_ring	84:B8:02:8B:BA:62	0000:09:00.0	0	Up	NotFound	0
enp10s0	enp10s0	pf_ring	84:B8:02:8B:BA:63	0000:0A:00.0	-1	Up	NotFound	0
enp19s0	enp19s0	pf_ring	84:B8:02:5B:B7:EB	0000:13:00.0	0	Up	NotFound	0
enp20s0	enp20s0	pf_ring	84:B8:02:5B:B7:EC	0000:14:00.0	0	Up	NotFound	0
zc:enp1s0f0	enp1s0f0	pf_ring-zc	F4:CF:E2:11:84:44	0000:01:00.0	0	Up	NotFound	0
zc:enp1s0f1	enp1s0f1	pf_ring-zc	F4:CF:E2:11:84:45	0000:01:00.1	0	Up	NotFound	0

Using enp1s0f0 and enp1s0f1 for packet captures.

Where should the ZC license be located? 
We currently have ntop Enterprise L and n2disk10/40 license installed.

**Comment by cardigliano** [comment]
You need ZC licenses, they should be installed under /etc/pf_ring/MAC

**Comment by hhs-itservices** [comment]
Thank you, so we need the following license, 1 Gbit PF_RING ZC Intel [Linux]. Is it one license per 1 Gbit/s NIC?

**Comment by cardigliano** [comment]
Yes, that for 1 Gbit Intel interfaces, you need one for each interface

**Comment by hhs-itservices** [comment]
Adding ZC license for 1 Gbit/s NIC (1 Gbit PF_RING ZF Intel [Linux]) for each interface/MAC solved the problem.
Thank you for the assistance with this.
