### ISSUE TITLE
Hostname lookup for internal devices seen on span port

### ISSUE THREAD

**Issue by DrToxo** [ntop/ntopng#4757]
We use ntopng for monitoring 2 internet links using a span port and would like to be able to resolve all internal devices from IP to their hostnames.  Although I consider these internal devices to be local, they are considered as remote due to them not being on the local network that ntopng is connected to.

Can I specify ranges of IP to be treated as local and to perform a reverse lookup to show hostnames?

Thanks

**Comment by lucaderi** [comment]
Sure you can use the -m CLI option to specify the list of local networks. 

[--local-networks|-m] <local nets>  | Local nets list (default: 192.168.1.0/24)
                                    | (e.g. -m "192.168.0.0/24,172.16.0.0/16")
