### ISSUE TITLE
Test always failing with valid infrastructure ntopng

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4758]
Instance correctly reachable

```
simone@devel:~/ntopng$ curl -k -H "Content-Type: application/json" -H "Authorization: Token fb6fdf01551dda9b45fdd8abf11d8f66" "https://develv5:443/lua/rest/v1/get/system/data.lua"
{"rsp":{"throughput":{"download":1000,"upload":1000},"version":1,"num_alerts":3,"num_hosts":1,"num_flows":2,"epoch":0},"rc":0,"rc_str":"OK","rc_str_hr":"Success"}
simone@devel:~/ntopng$ curl -k -H "Content-Type: application/json" -H "Authorization: Token fb6fdf01551dda9b45fdd8abf11d8f66" "https://192.168.2.225:443/lua/rest/v1/get/system/data.lua"
{"rsp":{"throughput":{"upload":1000,"download":1000},"num_hosts":1,"version":1,"epoch":0,"num_alerts":3,"num_flows":2},"rc":0,"rc_str":"OK","rc_str_hr":"Success"}
simone@devel:~/ntopng$ curl -k -H "Content-Type: application/json" -H "Authorization: Token fb6fdf01551dda9b45fdd8abf11d8f66" "https://192.168.2.225/lua/rest/v1/get/system/data.lua"
{"rc":0,"rc_str":"OK","rsp":{"epoch":0,"throughput":{"upload":1000,"download":1000},"num_hosts":1,"version":1,"num_alerts":3,"num_flows":2},"rc_str_hr":"Success"}
simone@devel:~/ntopng$ curl -k -H "Content-Type: application/json" -H "Authorization: Token fb6fdf01551dda9b45fdd8abf11d8f66" "https://develv5/lua/rest/v1/get/system/data.lua"
{"rsp":{"num_flows":2,"throughput":{"download":1000,"upload":1000},"num_alerts":3,"version":1,"epoch":0,"num_hosts":1},"rc_str":"OK","rc_str_hr":"Success","rc":0}
```

However, it's impossible to test it successfully

![image](https://user-images.githubusercontent.com/3397663/99700853-03127600-2a94-11eb-9d32-f81c20c7a443.png)

![image](https://user-images.githubusercontent.com/3397663/99700883-0b6ab100-2a94-11eb-9b6b-3554c140c3c3.png)

![image](https://user-images.githubusercontent.com/3397663/99700907-1291bf00-2a94-11eb-97dc-0ef96ba043c3.png)

![image](https://user-images.githubusercontent.com/3397663/99700930-19203680-2a94-11eb-8043-618686e0fc04.png)

Same for a valid HTTP host

![image](https://user-images.githubusercontent.com/3397663/99701547-e296eb80-2a94-11eb-91b1-646febda6299.png)

**Comment by gabryon99** [comment]
This issue was caused by the server and the browser. Thanks to @lucaderi we've fixed the problem. See the pro repository, please.

**Comment by simonemainardi** [comment]
Fixed with https://github.com/ntop/ntopng/commit/494513181df766259a36b158d50c15c7e4a89ed1
