### ISSUE TITLE
Invalid THRESHOLD validation

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4759]
![image](https://user-images.githubusercontent.com/3397663/99701846-4ae5cd00-2a95-11eb-9b49-5d843a6b50bc.png)

![image](https://user-images.githubusercontent.com/3397663/99701883-5a651600-2a95-11eb-84df-96a7bf5ea53b.png)

**Comment by gabryon99** [comment]
Set a max to 1 hour, see the pro repository

**Comment by simonemainardi** [comment]
One hour is pointless. Make it maximum 10 seconds, 10000 ms, and make the same maximum value also honored for active monitoring in 

<img width="577" alt="image" src="https://user-images.githubusercontent.com/3397663/99882332-edca5280-2c1f-11eb-82e7-a19a16c0ee55.png">

**Comment by gabryon99** [comment]
I set the limit to 10 seconds. For the infrastructure page see the pro repository.

**Comment by simonemainardi** [comment]
still not working

![image](https://user-images.githubusercontent.com/3397663/99998041-56e7cc80-2dbe-11eb-9450-d0197cbf4cce.png)
