### ISSUE TITLE
Error 'fetching cdp from rra' double backslash in dir path

### ISSUE THREAD

**Issue by DrToxo** [ntop/ntopng#4762]
I noticed these errors in my logs, and looking closely at it, Ive noticed a double backslash in the `directory\5\rrd\\bytes.rrd` patch and wondered if this could be the cause of the error, or just a gui glitch?

`20/Nov/2020 15:28:28 [LuaEngineNtop.cpp.inc:5175] ERROR Error 'fetching cdp from rra' while calling rrd_fetch_r(C:\Windows\ServiceProfiles\ntopng\Documents\ntopng\5\rrd\\bytes.rrd, AVERAGE): is the RRD corrupted perhaps?`

**Comment by simonemainardi** [comment]
This is a old and known issue on windows. It is due to the `rrd_fetch_r` which behaves differently on win. By the way, this seems not to cause issues on the ntopng operation. Can you confirm? That is, RRD, and historical data access work properly.

**Comment by DrToxo** [comment]
Not knowing what rrd is/does I can only confirm that historical data is working.  However, we have not been able to view anything on the Network Interfaces: Realtime Traffic window which has all interfaces listed, but not showing any graph.

Thanks

**Comment by simonemainardi** [comment]
can you please attach a screenshot?

**Comment by DrToxo** [comment]
Here you go...  Thanks

![image](https://user-images.githubusercontent.com/16386651/100610612-f7cb1000-3307-11eb-8470-0459cd0e1c41.png)

**Comment by simonemainardi** [comment]
what's the ntopng version you are using?

**Comment by DrToxo** [comment]
4.3.20103

Also unable to save custom name for interfaces or even traffic profiles....
I enter them and select save and they just revert back.

Cheers

**Comment by lucaderi** [comment]
This is a corrupted RRD, so the only solution is to delete the RRD and start over
