### ISSUE TITLE
Issues with Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by VPK-personal** [ntop/ntopng#4768]
I'm trying to install ntopng community version. I documented my setup in the attachment. Any guidance would be much appreciated! 

 
[ntopng setup issues.pdf](https://github.com/ntop/ntopng/files/5576723/ntopng.setup.issues.pdf)

**Comment by simonemainardi** [comment]
Issues are:

0. Make sure no other ntopng instance is running: `systemctl stop ntopng`
1. You are running ntopng without enough privileges. Do `sudo ntopng --community` (note the `sudo`). This will start ntopng as root and eventually drop privileges to user `ntopng`
2. You have way too many interfaces on your system. You need to either use a professional version of ntopng to handle all of them, or limit ntopng to a subset of interfaces. For example, to limit to `enp1s0`, you can do `sudo ntopng -i enp1s0 --community`

That should be pretty much all.

**Comment by VPK-personal** [comment]
Thanks for super fast reply! Will try those.

**Comment by VPK-personal** [comment]
I got it working, thank you @simonemainardi The last one was to use HTTP, not HTTPS with the browser. 

I noticed that when I reset all counters at the "Interface" home, it does not reset "Applications" graphs and data. Is there another way to reset the Application statistics?

**Comment by simonemainardi** [comment]
Thanks for reporting.

Please, check this out for the deletion of interface data, including applications and graphs: https://github.com/ntop/ntopng/issues/4775
