### ISSUE TITLE
[Enhancement] Export past alert to file

### ISSUE THREAD

**Issue by Zathiel** [ntop/ntopng#4769]
Hello

Can you add the possibility to export past detected alerts to a file (txt.json)

Regards

**Comment by Zathiel** [comment]
@simonemainardi @lucaderi Hello Team, 

Can you please take in charge it will be really helpfull for my daily work

Thanks in advance 

Regards

**Comment by simonemainardi** [comment]
Please, explain. Explain the use case.

Would you like a sort of download-button to download past alerts matching certain criteria?

**Comment by Zathiel** [comment]
I would like a download button of the past alert matching criteria and protocol

**Comment by simonemainardi** [comment]
Implemented. A download button has now been added. It will send you a json file containing all the alerts matching selection criteria.

![image](https://user-images.githubusercontent.com/3397663/103411551-ed9f6a00-4b70-11eb-9f0e-36fdb429c079.png)

New build is in progress.
