### ISSUE TITLE
After update > Dashboard is not accessible anymore

### ISSUE THREAD

**Issue by airtwist1** [ntop/ntopng#477]
Hi,

we updated our Server with apt-get update & upgrade, after that, the fancy Dashboard of ntop is not starting anymore. Only the old Dashboard with the "Top Talkers Flow" is accessible and we are always redirected to that Dashboard by that link http://192.168.XX.XX:3000/lua/index.lua

Also the Reports are not shown under the Home folder. 

The Machine is a VM:
Ubuntu 14.04.3 LTS \n \l

root@fn-ntop:~# uname -a
Linux fn-ntop 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thue April 05 09:00:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
root@fn-ntop:~#

When we restart ntopng the Dashboard is accessible again. But only for a while. than the new fancy Dashboard disappear and only the old one is accessible....

**Comment by simonemainardi** [comment]
Check ntopng log output. If it complains about an invalid license, it means that the hardware seen has changed (VM updates?). If this is the case try to execute ntopng with `--online-license-check`

**Comment by airtwist1** [comment]
Well, the license is valid, but in nbox it says, that the license cannot be found .....
also my nprobe license cannot be found. 

here is the ntop log:

04/Apr/2016 16:52:52    Setting affinity of interface tcp://127.0.0.1:5556 to core 1
04/Apr/2016 16:52:52    Started packet polling on interface tcp://127.0.0.1:5556 [id: 3]...
04/Apr/2016 16:52:53    Collecting flows on tcp://127.0.0.1:5556 [ntopng->nprobe]
05/Apr/2016 08:37:17    WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/dashboard.lua][/usr/share/ntopng/scripts/lua/pro/dashboard.lua:1: '=' expected]
05/Apr/2016 12:36:50    Shutting down...
05/Apr/2016 12:36:51    Ok I am leaving now

![bildschirmfoto 2016-04-05 um 12 38 39](https://cloud.githubusercontent.com/assets/16499817/14279121/c3264f4a-fb2b-11e5-8b32-8d8f57df16df.png)
![bildschirmfoto 2016-04-05 um 12 38 57](https://cloud.githubusercontent.com/assets/16499817/14279125/c68411ea-fb2b-11e5-81f8-247e668ac122.png)

**Comment by ValentinaViscarelli** [comment]
Please contact me by email (valentina@ntop.org) and send me the output of following commands:
- ntopng --version
- ntopng --check-license
- cat /etc/ntopng.license
- echo "get ntopng.license" | redis-cli

**Comment by ValentinaViscarelli** [comment]
Resolved using --online-license-check

**Comment by airtwist1** [comment]
Hi Valentina,

sorry for reopening this  ticket, but we recognised that we run into more problem´s by starting ntopng from cli instead from nbox.

The Problem is, that we loose all our configuration that we set up in ntopng when we start ntopng through cli.

How can we manage this ?

Mit freundlichen Grüßen  / Best regards

Jean Ora

CEO

forcenet-logo_signatur

Force Net GmbH
Borsigstrasse 3-5
D-93092 Barbing
Tel:  (+49) 9401 - 53989 – 102

Fax.: (+49) 9401 – 53989 - 101
e-mail:  ora@forcenet.de
web:     www.forcenet.de
Amtsgericht Regensburg, HRB 13009
E.USt.Nr.: DE 282 293 041
Geschäftsführer: Jean Ora 
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. 
Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Von: ValentinaViscarelli [mailto:notifications@github.com] 
Gesendet: Donnerstag, 7. April 2016 23:06
An: ntop/ntopng
Cc: FN Jean Ora
Betreff: Re: [ntop/ntopng] After update > Dashboard is not accessible anymore (#477)

Resolved using --online-license-check

**Comment by ValentinaViscarelli** [comment]
@airtwist1 
I didn't understand well the problem.
Maybe is your problem is why nbox doesn't manage --online-license-check parameter?

**Comment by airtwist1** [comment]
Well, our Problem is, that we´re not able to start ntopng throu the nbox Gui. Because in nBox it says, that our license is not valid, which is not true.

So Valentina told us un workaround to start nbox trough the cli direct on the console to get the license verification. Now, we start ntopng like this through cli

Ntopng –I “tcp://127.0.0.1:5556” –online-license-check

Our Problem now is that when we start ntopng through cli   >  Ntopng –I “tcp://127.0.0.1:5556” –online-license-check

It starts just with no configuration that we have done in nbox.

For example:

In the Dashboard it is not showing us, the local Networks. It just show´s everything as foreign 

How we can tell ntopng that this networks are local networks and not remote!  213.95.255.224/27 and 213.95.82.32/28     > see pictures below 

Also it still shows in nbox that we do not have a valid license, which is not true

Mit freundlichen Grüßen  / Best regards

Jean Ora

CEO

forcenet-logo_signatur

Force Net GmbH
Borsigstrasse 3-5
D-93092 Barbing
Tel:  (+49) 9401 - 53989 – 102

Fax.: (+49) 9401 – 53989 - 101
e-mail:  ora@forcenet.de
web:     www.forcenet.de
Amtsgericht Regensburg, HRB 13009
E.USt.Nr.: DE 282 293 041
Geschäftsführer: Jean Ora 
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. 
Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Von: ValentinaViscarelli [mailto:notifications@github.com] 
Gesendet: Donnerstag, 21. April 2016 13:21
An: ntop/ntopng
Cc: FN Jean Ora; Mention
Betreff: Re: [ntop/ntopng] After update > Dashboard is not accessible anymore (#477)

@airtwist1 https://github.com/airtwist1  
I didn't understand well the problem.
Maybe is your problem is why nbox doesn't manage --online-license-check parameter?

**Comment by ValentinaViscarelli** [comment]
Hi,
I made a change. Now ntopng manages --online-license-check parameter (in ntopng configuration go to last parameter of general section). In this way you want run ntopng by GUI.

Ignore if GUI says that you don't have a valid license. ntopng will work anyway.
In order to update use:

apt-get update
apt-get upgrade

**Comment by airtwist1** [comment]
Ciao Valentina,

sorry, but after apt-get update and upgrade we´re running in the same Problem, that the new Dashboard disapeard and we only see the old Dashboard. The same Problem which we solved before with the parameter –online-license-check …

Mit freundlichen Grüßen  / Best regards

Jean Ora

CEO

forcenet-logo_signatur

Force Net GmbH
Borsigstrasse 3-5
D-93092 Barbing
Tel:  (+49) 9401 - 53989 – 102

Fax.: (+49) 9401 – 53989 - 101
e-mail:  ora@forcenet.de
web:     www.forcenet.de
Amtsgericht Regensburg, HRB 13009
E.USt.Nr.: DE 282 293 041
Geschäftsführer: Jean Ora 
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. 
Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Von: ValentinaViscarelli [mailto:notifications@github.com] 
Gesendet: Donnerstag, 21. April 2016 16:19
An: ntop/ntopng
Cc: FN Jean Ora; Mention
Betreff: Re: [ntop/ntopng] After update > Dashboard is not accessible anymore (#477)

Hi,
I made a change. Now ntopng manages --online-license-check parameter (in ntopng configuration go to last parameter of general section). In this way you want run ntopng by GUI.

Ignore if GUI says that you don't have a valid license. ntopng will work anyway.
In order to update use:

apt-get update
apt-get upgrade

**Comment by ValentinaViscarelli** [comment]
But after the update.... 
Do you have the problem also if you use cli or just with you run with GUI?

**Comment by airtwist1** [comment]
Yes, after I made apt-get update , apt-get ugrade, then restart OS 

Just when i run it in GUI nbox 

Mit freundlichen Grüßen  / Best regards

Jean Ora

CEO

forcenet-logo_signatur

Force Net GmbH
Borsigstrasse 3-5
D-93092 Barbing
Tel:  (+49) 9401 - 53989 – 102

Fax.: (+49) 9401 – 53989 - 101
e-mail:  ora@forcenet.de
web:     www.forcenet.de
Amtsgericht Regensburg, HRB 13009
E.USt.Nr.: DE 282 293 041
Geschäftsführer: Jean Ora 
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. 
Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Von: ValentinaViscarelli [mailto:notifications@github.com] 
Gesendet: Donnerstag, 21. April 2016 19:37
An: ntop/ntopng
Cc: FN Jean Ora; Mention
Betreff: Re: [ntop/ntopng] After update > Dashboard is not accessible anymore (#477)

But after the update.... 
Do you have the problem also if you use cli or just with you run with GUI?

**Comment by ValentinaViscarelli** [comment]
but do you set the "Online License Check" flag in ntopng configuration like the screen shot attached below?
Could you post the output of this command "cat /etc/ntopng/ntopng.conf"?

![ntopng](https://cloud.githubusercontent.com/assets/13115771/14720996/5b547d34-0804-11e6-9ba8-0b83a7bc8888.png)

**Comment by airtwist1** [comment]
There is no Option to set the flag ….

Mit freundlichen Grüßen  / Best regards

Jean Ora

CEO

forcenet-logo_signatur

Force Net GmbH
Borsigstrasse 3-5
D-93092 Barbing
Tel:  (+49) 9401 - 53989 – 102

Fax.: (+49) 9401 – 53989 - 101
e-mail:  ora@forcenet.de
web:     www.forcenet.de
Amtsgericht Regensburg, HRB 13009
E.USt.Nr.: DE 282 293 041
Geschäftsführer: Jean Ora 
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. 
Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Von: ValentinaViscarelli [mailto:notifications@github.com] 
Gesendet: Donnerstag, 21. April 2016 21:04
An: ntop/ntopng
Cc: FN Jean Ora; Mention
Betreff: Re: [ntop/ntopng] After update > Dashboard is not accessible anymore (#477)

but do you set the "Online License Check" flag in ntopng configuration like the screen shot attached below?
Could you post the output of this command "cat /etc/ntopng/ntopng.conf"?

 https://cloud.githubusercontent.com/assets/13115771/14720996/5b547d34-0804-11e6-9ba8-0b83a7bc8888.png ntopng

**Comment by ValentinaViscarelli** [comment]
I don't think you have the correct version of nbox. Try to do a clean:

apt-get clean all
apt-get update
apt-get upgrade

If you don't still have the flags, please post the output of this command:

dpkg -s nbox

**Comment by airtwist1** [comment]
The flag still not appear.

ora@fn-ntop:~$ sudo dpkg -s nbox

[sudo] password for ora: 

Package: nbox

Status: install ok installed

Priority: optional

Section: free

Installed-Size: 4815

Maintainer: Luca Deri deri@ntop.org

Architecture: all

Version: 2.3-449

Depends: apache2, perl, libtemplate-perl, libcgi-pm-perl, libxml-parser-perl, libhtml-template-perl, libjson-perl, ethtool, tshark, dmidecode, xfsprogs, htop, ifenslave-2.6, hwloc, ntp, lsscsi, apache2-utils, wireless-tools, iw, hostapd, rfkill, snmpd

Description: Web management interface for ntop apps.

Mit freundlichen Grüßen  / Best regards

Jean Ora

CEO

forcenet-logo_signatur

Force Net GmbH
Borsigstrasse 3-5
D-93092 Barbing
Tel:  (+49) 9401 - 53989 – 102

Fax.: (+49) 9401 – 53989 - 101
e-mail:  ora@forcenet.de
web:     www.forcenet.de
Amtsgericht Regensburg, HRB 13009
E.USt.Nr.: DE 282 293 041
Geschäftsführer: Jean Ora 
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. 
Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

Von: ValentinaViscarelli [mailto:notifications@github.com] 
Gesendet: Donnerstag, 21. April 2016 23:12
An: ntop/ntopng
Cc: FN Jean Ora; Mention
Betreff: Re: [ntop/ntopng] After update > Dashboard is not accessible anymore (#477)

I don't think you have the correct version of nbox. Try to do a clean:

apt-get clean all
apt-get update
apt-get upgrade

If you don't still have the flags, please post the output of this command:

dpkg -s nbox

**Comment by ValentinaViscarelli** [comment]
Your version is old. I think the nbox package  is in kept-back when you do the upgrade.
Try to remove and install again nbox.

sudo apt-get remove nbox
sudo apt-get install nbox

**Comment by airtwist1** [comment]
Ciao Valentina,

Grazie, now IT works!

Best regards
Jean

Am 22.04.2016 um 10:02 schrieb ValentinaViscarelli <notifications@github.com<mailto:notifications@github.com>>:

Your version is old. I think the nbox package is in kept-back when you do the upgrade.
Try to remove and install again nbox.

sudo apt-get remove nbox
sudo apt-get install nbox
