### ISSUE TITLE
Geolocation map doesn't display in Dark theme

### ISSUE THREAD

**Issue by rreiner** [ntop/ntopng#4770]
Geolocation is working correctly with standard (light) display theme; **but** with Dark theme enabled the map is not displayed (although host location indicators are still shown, on a solid grey background)

(ntopng Community v.4.3.201119 )
![image](https://user-images.githubusercontent.com/12399329/99884698-353fe700-2bfe-11eb-9104-3aba67bed7f2.png)

**Comment by Zathiel** [comment]
Hello @gabryon99 

That's the issue that i have talk to you on discord

I confirm that this is working in standard (light) display but not in dark theme

Regards

**Comment by gabryon99** [comment]
It seems that the tiles provider for the map request a registration to use their tilesets. I think the best solution, right now, it's to replace the dark map with the default one offered by OpenStreetsMap.

**Comment by Zathiel** [comment]
as you prefer :) if its work for me its not a problem

Regards
