### ISSUE TITLE
Auto-add recipient when defined 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4772]
As of today when a new recipient is defined, it must be added by hand to all pools. While sometimes a recipient should be added only to some of them, usually people want to add it to all of them without having to make a cumbersome click sequence.

This is to request the implementation of "add to all pools" dialog when a new recipient is created, so that the user can (in one click) selecting "yes" to automatically add it to all pools, or (as of today) clicking "no" don't do any action

**Comment by simonemainardi** [comment]
Implemented. Backend implemented in https://github.com/ntop/ntopng/commit/93ef5c08d8fb20b5f4770a036f64984609f5472b
