### ISSUE TITLE
Network Discovery question

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#4777]
Hi guys, i was wondering if someone could help me understand how NTOPNG gets the names of devices on my network using "DHCP" as seen in the screen shot below. NTOPNG even gets names from "DHCP" for devices with static assignments.

Please help

I have tried looking at https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/discover_utils.lua but it doesnt make much sense to me

thanks

**Comment by simonemainardi** [comment]
there's no screenshot attached. Please, check.

**Comment by ghost** [comment]
sorry. here it is https://m.imgur.com/a/MNogHNJ

**Comment by simonemainardi** [comment]
ntopng has seen DHCP traffic for that host and has dissected the name, this is why you see the name.

Maybe for static assignments you mean assignments configured on the router so that it always assigns the same IP to the same Mac? If this is the case, consider that DHCP still kicks in.

**Comment by ghost** [comment]
ok thank you for clarifying this. i appreciate it!
