### ISSUE TITLE
Alert type menu (alert page) must be alphabetically sorted

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4778]
The alert page is sub optimal as 
- many queries are performed (all tabs insted of just the one displayed)
- there is no reload button
- there is this inconveniente sort issue that needs to be addressed

![Screen Shot 2020-11-25 at 15 46 41](https://user-images.githubusercontent.com/4493366/100242967-aa305b00-2f35-11eb-8e4f-d2b2b2a549ea.png)

**Comment by simonemainardi** [comment]
issue is partial as flow statuses - shown in the figure - have not been sorted
