### ISSUE TITLE
Script Failure (Alerts)

### ISSUE THREAD

**Issue by djstarfox** [ntop/ntopng#4779]
[AlertCheckLuaEngine.cpp:168] WARNING Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [...opng/plugins0/callbacks/interface/flow/country_check.lua:75: attempt to index a nil value (field 'srv')]
[AlertCheckLuaEngine.cpp:168] WARNING Script failure[/usr/share/ntopng/scripts/callbacks/interface/flow.lua] [...png/plugins0/callbacks/interface/flow/unexpected_ntp.lua:75: attempt to index a nil value (global 'flow_info')]

ntopng log is filling up with these constantly after upgrading to the latest version (4.3.201122-12310).  Restarting ntopng doesn't seem to help.

**Comment by MatteoBiscosi** [comment]
The problem should be fixed into the latest version of the software, try to upgrade ntopng and let me know if you still have it

**Comment by simonemainardi** [comment]
@djstarfox did you have a chance to try?

**Comment by djstarfox** [comment]
No, because the repos for armhf architecture have not been updated with the newest release yet. 
ntopng/unknown,now 4.3.201122-12310 armhf

**Comment by simonemainardi** [comment]
new ARM builds in progress. Please, hold 2-3 hours from now and then update.

**Comment by simonemainardi** [comment]
ARM packages are out. Please check them out.

**Comment by djstarfox** [comment]
Wow, that really messed things up.  This new version is now filling the logs faster at about 50x second, with various IP ranges for each host: 
[Utils.cpp:3142] ERROR Bad radix tree lookup for 192.168.40.4/32 (prefix len = 32, tree max len = 32)

Also, alerts are piling up because the binary is ignoring my --local-networks setting in the config file.
And, the "Active Flows" page shows "No results found", but there is plenty of mixed traffic going on.

**Comment by simonemainardi** [comment]
@MatteoBiscosi can you please check this out?

**Comment by lucaderi** [comment]
@simonemainardi What about this https://github.com/ntop/ntopng/commit/e683509dec0e4fd7575fff60ff5d04415affd0e8  instead? @cardigliano What's your opinion?

**Comment by cardigliano** [comment]
It seems that this build for ARM has been made right in the middle of some change, a new build should solve the issue.

**Comment by lucaderi** [comment]
@djstarfox Packages are being built. Please try again in one hour.

**Comment by djstarfox** [comment]
Just deployed 4.3.201201 (12380) and have a good mix of 2-3 Mbps flowing.  Looking much better in the logs.  I'll review again at COB today, and let you know how things look.

**Comment by simonemainardi** [comment]
thanks for reporting

**Comment by djstarfox** [comment]
Looks like everything is fixed.  Thanks for the help.
