### ISSUE TITLE
ERROR: ntop_snmpv3_batch_get

### ISSUE THREAD

**Issue by HNJBB** [ntop/ntopng#4782]
Updated to ntopng x86_64 v.4.3.201126.   Log showing this error several times per second.

- 27/Nov/2020 11:39:35 [startup.lua:239] Startup completed: ntopng is now operational
- Nov 27 11:39:35 ntop ntopng[4674]: 27/Nov/2020 11:39:35 [PeriodicActivities.cpp:168] Each periodic activity script will use 2 threads
- Nov 27 11:39:35 ntop ntopng[4674]: 27/Nov/2020 11:39:35 [NetworkInterface.cpp:2738] Started packet polling on interface tcp://127.0.0.1:5556 [id: 3]...
- Nov 27 11:39:36 ntop ntopng[4674]: 27/Nov/2020 11:39:36 [ZMQCollectorInterface.cpp:256] Collecting flows on tcp://127.0.0.1:5556
- Nov 27 11:40:01 ntop ntopng[4674]: [LuaEngineNtop.cpp:47] ERROR: ntop_snmpv3_batch_get : expected string[@pos 4], got nil
- Nov 27 11:40:01 ntop ntopng[4674]: 27/Nov/2020 11:40:01 [LuaEngineNtop.cpp:47] ERROR: ntop_snmpv3_batch_get : expected string[@pos 4], got nil
- Nov 27 11:40:01 ntop ntopng[4674]: [LuaEngineNtop.cpp:47] ERROR: ntop_snmpv3_batch_get : expected string[@pos 4], got nil
- Nov 27 11:40:01 ntop ntopng[4674]: 27/Nov/2020 11:40:01 [LuaEngineNtop.cpp:47] ERROR: ntop_snmpv3_batch_get : expected string[@pos 4], got nil
- Nov 27 11:40:01 ntop ntopng[4674]: [LuaEngineNtop.cpp:47] ERROR: ntop_snmpv3_batch_get : expected string[@pos 4], got nil
- Nov 27 11:40:01 ntop ntopng[4674]: 27/Nov/2020 11:40:01 [LuaEngineNtop.cpp:47] ERROR: ntop_snmpv3_batch_get : expected string[@pos 4], got nil

**Comment by simonemainardi** [comment]
- remove configured SNMP devices
- re-add them

report

**Comment by HNJBB** [comment]
Problem resolved with removing and re-adding as suggested

**Comment by simonemainardi** [comment]
thank you
