### ISSUE TITLE
Periodicity should be disabled/hidden with continuous monitoring

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4784]
![activemon](https://user-images.githubusercontent.com/4493366/100523273-93953880-31af-11eb-8a4c-7abe7d94ed6a.png)

Continuous monitoring by defininition is continuous, or if you wish periodic free. Hence the periodicity menu should be disabled/hidden

**Comment by simonemainardi** [comment]
make sure NOT to hardcode an `if-speedtest-then-` condition.

Correct way to implement is to:
- Check active monitoring `granularities`, e.g., ` scripts/plugins/monitors/network/active_monitoring/measurements/cicmp.lua`, e.g., 

```
      -- The granularities allowed for the probe. See supported_granularities in active_monitoring.lua
      granularities = {"min"},
```

If the length of `granularities` is ONE, then the periodicity dropdown must be hidden from the ui and the value must be submitted automatically.

**Comment by gabryon99** [comment]
Implemented as suggested by @simonemainardi .
