### ISSUE TITLE
nProbe Time Drift

### ISSUE THREAD

**Issue by ukunk** [ntop/ntopng#4786]
I'm running Ntopng (Pro licence) and Nprobe on the same device - Raspberry Pi. Time of RPi is sync with Mikrotik router where I collect Netflow data and also run NTP server. I check right sync time with command: timedatectl timesync-status. Time zone is the same on both machines.
I experience very high nProbe time drift which eventually stop collecting the flows and it only helps if I restart nprobe.service, till next time drift.
My config:
Ntopng
-G=/var/tmp/ntopng.pid
-d=/opt/ntopng-data
-e=
-i="tcp://127.0.0.1:5556"
-w=3000
-m="xx,xx"
-n=1

NProbe
--zmq="tcp://*:5556"
-T="@NTOPNG@"
-i=none
-n=none
-V=10
--collector-port=2055

What would be the reason for such time drift and what can I do to correct the issue?

**Comment by simonemainardi** [comment]
when you see the drift message, go to the active flows page, pick one of the newest flows, and then check its first/last seen. Are those times close to the actual ntopng time?

**Comment by ukunk** [comment]
I restarted ntopng and nprobe and checked few flows. In general there're between 1 minute and 2 minute drift between value first/last seen. When I get pop-up "You must synchronize the clock of ntopng and remote probe hosts as the clock drift is too large and this will affect collected flow data", I have to restart nprobe.service in order to get service working again.

**Comment by simonemainardi** [comment]
Can you add option --disable-cache to nProbe and report the behavior?

**Comment by ukunk** [comment]
Problem is solved. The issue was missing nprobe licence which manifested as high time drift and eventually stop collecting flows. @simonemainardi thank you for help.

**Comment by simonemainardi** [comment]
Thank you for reporting.

**Comment by RomelSan** [comment]
> 
> 
> Problem is solved. The issue was missing nprobe licence which manifested as high time drift and eventually stop collecting flows. @simonemainardi thank you for help.

I have the same problem...
How do you fix it?
Is there a --community flag for nprobe?

**Comment by simonemainardi** [comment]
@RomelSan nProbe requires a license to operate, no --community flag.
