### ISSUE TITLE
Add New Recipient Broken

### ISSUE THREAD

**Issue by simon-rear** [ntop/ntopng#4787]
Hi, When clicking on the Add button after creating a recipient as per screen shot the button greys out for a few seconds and the form remains without any recipient been added. I'm unable to create alert recipients as a result.

![Screenshot 2020-11-29 163043](https://user-images.githubusercontent.com/75215499/100547747-48872e00-3260-11eb-8a99-cdbad40156a8.png)

**Comment by simonemainardi** [comment]
I am unable to reproduce the experienced behavior.

Please, refresh browser caches, then report.

- Browser used
- ntopng version
- Right-click on the page, select inspect element, then also report any JS error or network error the inspector should highlight

**Comment by simon-rear** [comment]
Hi Simon, thanks for getting back to me. I have refreshed cache and retried issue persists. I am using Microsoft Edge Version 87.0.664.47 (Official build) (64-bit) and ntopng Community v.4.3.201129, (running on raspbian).  Tried inspecting page but no JS or network errors were highlighted.
![Screenshot 2020-11-30 102537](https://user-images.githubusercontent.com/75215499/100599948-9485b180-32f8-11eb-8cad-f8f8e2ca3230.png)

**Comment by simonemainardi** [comment]
please:

- try and use a different browser
- also check the Network tab of the inspector. You'll see a POST request when you click on ADD. Please, send screenshots for that POST as well, both request and response.

**Comment by simon-rear** [comment]
Hi, have tried chrome on a another machine and edge from mobile phone and neither work. Did also check Network tab and tried submitting form however no POST, REQUEST, RESPONSE as per attached.
![Screenshot 2020-11-30 120313](https://user-images.githubusercontent.com/75215499/100608269-0d3e3b00-3304-11eb-8658-bb2f0a42784d.png)

**Comment by simon-rear** [comment]
Hi Simon I've been digging around and found quite a few errors, (extract attached), which appear to be related to notifications.
[SysLog Extract.txt](https://github.com/ntop/ntopng/files/5616219/SysLog.Extract.txt)

**Comment by simon-rear** [comment]
Hi I have reinstalled ntopng and this appears to be working must have been something wrong with original install. Thanks for your support though.
