### ISSUE TITLE
ntopng not able to list linux machines (VMs)

### ISSUE THREAD

**Issue by eliassal** [ntop/ntopng#4789]
I have a fresh ntopng is on windows 10, it discovers all devices (windows servers and VMs, routers, switches) except the linux machines/Vms (Centos, ubuntu hosts), any idea?
Thanks

**Comment by simonemainardi** [comment]
Discovery works on the layer 2.

Are the linux VMs layer-2-reachable by the ntopng instance? My guess is that they're run on a part of the network which is not in the same broadcast domain.

**Comment by eliassal** [comment]
They are in the same broadcast domain, ntopng is 192.16.1.19 and linux machines are 192.168.1.11, 192.168.1.51 and so on

**Comment by eliassal** [comment]
Here is a ifconfig of one of them

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet **192.168.1.54**  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 2a01:e0a:322:14d1:215:5dff:fe01:1d22  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::215:5dff:fe01:1d22  prefixlen 64  scopeid 0x20<link>
        ether 00:15:5d:01:1d:22  txqueuelen 1000  (Ethernet)
        RX packets 2011666  bytes 1651035814 (1.5 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 466360  bytes 62091983 (59.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by eliassal** [comment]
I did a refresh, and can see the linux but it sees the device type as NAS
![ntopngLinuxNas](https://user-images.githubusercontent.com/8447864/100610640-6613d080-3310-11eb-9d63-d038c664857a.jpg)

**Comment by simonemainardi** [comment]
it's marked as NAS if at least one of the following holds:

- one of the following MDNS services are available: https://github.com/ntop/ntopng/blob/e683509dec0e4fd7575fff60ff5d04415affd0e8/scripts/lua/modules/discover_utils.lua#L331
- if the manufacturer is Synology
- if the hostname contains word 'capsule'
- if the hostname ends with -NAS

Clearly, this is an heuristic. If you feel it requires extension, please, explain or send a pull request.

**Comment by eliassal** [comment]
Non of these 4 conditions are true in my environment

**Comment by simonemainardi** [comment]
attach a pcap of the mac address while the discovery is being run

**Comment by eliassal** [comment]
Simon, is this what you are asking for? if not can you please tell me the steps to get the PCAP
![NasNotComp](https://user-images.githubusercontent.com/8447864/100742710-852b6480-33db-11eb-9387-6857ff96f60e.jpg)

**Comment by eliassal** [comment]
I try to download the Pcap files but it never ends, please notice that down on the lefthand side that download gets stcu on 24kb and it keeps like this and never ends
![PcapDownNever](https://user-images.githubusercontent.com/8447864/100743495-a476c180-33dc-11eb-9b99-ee80ac9591b7.jpg)

**Comment by simonemainardi** [comment]
1. go on the linux machine, then `sudo tcpdump -i <inteface name> -s0 -w capture.pcap`
2. go on ntopng and run a discovery
3. go on the linux machine, stop the command at step 1. and send me the resulting capture.pcap

**Comment by eliassal** [comment]
Here you go

[capture.zip](https://github.com/ntop/ntopng/files/5622843/capture.zip)
