### ISSUE TITLE
Flows Flood 

### ISSUE THREAD

**Issue by eliassal** [ntop/ntopng#4790]
I am getting alerts every 5 seconds as follows
`28/11/2020 17:00:18    00:50    1    Error     Flows Flood         Host 192.168.1.19 [winForDockerupdated.salam.net] is a flow flooder [1081 > 256 flows sent]`
What is this? is it a risk?
Just discovered that I have 2176 rows in "Alerts" with Severity "Notice", warning, some of them are "Remote to Remote", what all those alerts signification, any urls where I can see details about those alerts?

**Comment by simonemainardi** [comment]
Host `192.168.1.19` is creating too many connections and thus you receive the alarm. You can turn the alarm off or set an higher threshold from the user scripts page

![image](https://user-images.githubusercontent.com/3397663/100613785-61055000-3315-11eb-9df6-16a324f0a3a5.png)

Remote-to-remote means "Triggers an alert when a flow has remote hosts as client and server ". You can configure from this page

![image](https://user-images.githubusercontent.com/3397663/100613870-81cda580-3315-11eb-91ea-ec8efd9f8c35.png)

**Comment by eliassal** [comment]
Again, I have a notification indicating "Too many Floods for ntopng...
![floodflows](https://user-images.githubusercontent.com/8447864/100614567-9e1e1200-3316-11eb-9bf8-c8abb11fe229.jpg)

**Comment by eliassal** [comment]
OK, just saw your response
