### ISSUE TITLE
Remote IPs no name only IPs

### ISSUE THREAD

**Issue by eliassal** [ntop/ntopng#4791]
In all Hosts, all Remote IPs are not resolved to names, no one has a name in fornt of it, id this normal or am I missing a config param?

![ntopngRemote](https://user-images.githubusercontent.com/8447864/100611162-2bf6fe80-3311-11eb-8a7c-f57dd2662577.jpg)

**Comment by simonemainardi** [comment]
see

```
[--dns-mode|-n] <mode>              | DNS address resolution mode
                                    | 0 - Decode DNS responses and resolve
                                    |     local numeric IPs only (default)
                                    | 1 - Decode DNS responses and resolve all
                                    |     numeric IPs
                                    | 2 - Decode DNS responses and don't
                                    |     resolve numeric IPs
                                    | 3 - Don't decode DNS responses and don't
                                    |     resolve numeric IPs
```

**Comment by eliassal** [comment]
Is this something to run in the web gui or command line, in command line I type 
ntopng --dns-mode (any number )
I get
Unrecogniuzed option --dns-mode
"Available options ....

**Comment by simonemainardi** [comment]
Check the docs please https://www.ntop.org/guides/ntopng/how_to_start/index.html
