### ISSUE TITLE
NIC flagged as wireless in all hosts

### ISSUE THREAD

**Issue by eliassal** [ntop/ntopng#4792]
I have a desktop which has no wireless card, in All hosts it displayed as wireless
![NicWireless](https://user-images.githubusercontent.com/8447864/100611409-960fa380-3311-11eb-9002-0246b11bdbef.jpg)

**Comment by simonemainardi** [comment]
Similar to https://github.com/ntop/ntopng/issues/4789#issuecomment-735773738

An host is marked as wifi if the discovery process finds:
- and MDNS service `_airport._tcp.local`
- TP-LINK as manufacturer
- word "airport" in the symbolic host name

Clearly, this is an heuristic. If you feel it requires extension, please, explain or send a pull request.

**Comment by eliassal** [comment]
Yes it is a TP link NIC, but why?

**Comment by simonemainardi** [comment]
It's an heuristics. You know, TP-LINK builds wireless devices and NICs, so the device is assumed as Wifi. You can change the device type from the host page.
