### ISSUE TITLE
first login in and change password is invaild

### ISSUE THREAD

**Issue by muse117** [ntop/ntopng#4794]
Hi, I compile ntopng and first login, But change password is invaild. Couldn't login in. I see print log info.

Script failure [/opt/ntopng/scripts/callbacks/system/housekeeping.lua][.../ntopng/scripts/lua/modules/notifications/recipients.lua:647: attempt to call a nil value (field 'recipient_enqueue')]

**Comment by simonemainardi** [comment]
Likely, you are not running the compiled version. Please, report  the exact steps you've done to compile and run ntopng.

**Comment by muse117** [comment]
> Likely, you are not running the compiled version. Please, report the exact steps you've done to compile and run ntopng.

The problem is probably because I didn't install uglify-es, Now I can log in normally. Sorry, it's my fault
