### ISSUE TITLE
nprobe fails to start after upgrade

### ISSUE THREAD

**Issue by mwmdc** [ntop/ntopng#4795]
Hi!

Since 4.2.201125 the nprobe service does not properly start after upgrading the packages with apt on Debian 10. The following appears in the logs:

Dec  1 05:33:06 sl--------- systemd[1]: Starting nprobe extensible NetFlow v5/v9/IPFIX probe/collector for IPv4/v6...
Dec  1 05:33:06 sl--------- systemd[1]: nprobe.service: Current command vanished from the unit file, execution of the command list won't be resumed.
Dec  1 05:33:06 sl--------- systemd[1]: Started nprobe extensible NetFlow v5/v9/IPFIX probe/collector for IPv4/v6.
Dec  1 05:33:06 sl--------- nprobe[25520]: 01/Dec/2020 05:33:06 [nprobe.c:5083] ERROR: Unable to read config. file /run/nprobe.conf
Dec  1 05:33:06 sl--------- systemd[1]: nprobe.service: Main process exited, code=exited, status=255/EXCEPTION
Dec  1 05:33:06 sl--------- systemd[1]: nprobe.service: Failed with result 'exit-code'.

This does not affect ntopng.

Regards,
Michael

**Comment by lucaderi** [comment]
Sorry for delay. Can you please report what nprobe services haev you installed and if nprobe /etc/nprobe/nprobe.conf starts with no errors?
If you want timely responses please contact us on discord https://www.ntop.org/community/

**Comment by mwmdc** [comment]
Hi Luca,

I'm not in a hurry. ;) We only run one instance as netflow/sflow collector. The service can be started manually after the upgrade (i.e. service nprobe restart / systemctl restart nprobe). Only the restart during the update is affected.

Regards,
Michael

**Comment by mwmdc** [comment]
Hi Luca,

with the 201210-package everything worked fine this morning. Did you already fix it?

Regards,
Michael

**Comment by lucaderi** [comment]
Good to know it works
