### ISSUE TITLE
[Regression] Long Dropdowns are hidden

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4798]
![image](https://user-images.githubusercontent.com/3397663/100904495-5db1c600-34c7-11eb-8af1-cadca566df88.png)

**Comment by simonemainardi** [comment]
still not fixed

![image](https://user-images.githubusercontent.com/3397663/100911549-ae2d2180-34cf-11eb-8bcc-899e53282a82.png)

**Comment by simonemainardi** [comment]
behavior is awkward.

When dropdown is closed everything is OK

![image](https://user-images.githubusercontent.com/3397663/101144037-0a9b5880-3618-11eb-969c-dbbb7910a394.png)

When the dropdown opens:
1. the footer moves down
2. a lot of empty space is left between the footer and the no results found
3. dropdown titles are all hidden

![image](https://user-images.githubusercontent.com/3397663/101144167-33bbe900-3618-11eb-8db0-94f81de60a82.png)

Why do you think this is fixed?

**Comment by simonemainardi** [comment]
@gabryon99 please comment this. If it is unfixable, write and explanation, and then close.

**Comment by gabryon99** [comment]
At the moment we decided to remove the table-responsive wrapper and use the responsive flag provided by the new datatables.

**Comment by simonemainardi** [comment]
Please comment what's the behavior with reference to past closed issues:

- https://github.com/ntop/ntopng/issues/4497
- https://github.com/ntop/ntopng/issues/4362

**Comment by simonemainardi** [comment]
Check closed issues above. For example, the interface stats page no longer scrolls horizontally and this prevents the UI from being used.

**Comment by gabryon99** [comment]
I add the responsive wrapper for the interface page. If a table page is too large for the page we can *simply* add a wrapper.
