### ISSUE TITLE
New licence not recogised

### ISSUE THREAD

**Issue by swilkey** [ntop/ntopng#4799]
Hi,

We've just obtained a licence and generated the licence code and stored it as instructed in linux.  The file has permissions 644 which seems reasonable.  We're running ntopng with a docker image with the following command.

docker run -it -p 3000:3000 -v $(pwd)/ntopng.license:/etc/ntopng.license:ro --net=host ntop/ntopng:stable -i eth0 –network=host

Tried the following diagnostic steps (as recommended here: https://www.ntop.org/support/faq/my-license-does-not-work-what-can-i-do/)

# /usr/bin/ntopng --check-license
Invalid license [Empty license file]
# /usr/bin/ntopng --check-maintenance
/usr/biInvalid license
# /usr/bin/ntopng --version
v.4.2.201105    [Enterprise/Professional build]
GIT rev:        4.2-stable:97cccbb62db5b735a5a97cf6a3b76bc64d7bcbb4:20201105
Pro rev:        r3327
Built on:       Ubuntu 20.04.1 LTS
System Id:      C9F0C12C7A07AB20
Platform:       x86_64
Edition:        Enterprise L
License Type:   Time-Limited [Empty license file]
Validity:       Until Wed Dec  2 18:08:23 2020

Output log when starting ntopng docker image is as follows:
WARNING: Published ports are discarded when using host network mode
Starting redis-server: redis-server.
02/Dec/2020 15:47:24 [Ntop.cpp:2336] Setting local networks to 127.0.0.0/8,fe80::/10
02/Dec/2020 15:47:24 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
02/Dec/2020 15:47:24 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
02/Dec/2020 15:47:24 [NtopPro.cpp:299] [LICENSE] Reading license from /etc/ntopng.license
02/Dec/2020 15:47:24 [NtopPro.cpp:422] [LICENSE] /etc/ntopng.license: unable to validate license [Empty license file]
02/Dec/2020 15:47:24 [NtopPro.cpp:297] [LICENSE] Reading license from Redis
02/Dec/2020 15:47:24 [NtopPro.cpp:425] [LICENSE] Unable to validate license [Empty license file]
02/Dec/2020 15:47:24 [NtopPro.cpp:493] WARNING: [LICENSE] Invalid license [Empty license file]
02/Dec/2020 15:47:24 [NtopPro.cpp:510] WARNING: [LICENSE] ntopng will now run in Enterprise L edition for 10 minutes
02/Dec/2020 15:47:24 [NtopPro.cpp:512] WARNING: [LICENSE] before returning to community mode
02/Dec/2020 15:47:24 [NtopPro.cpp:514] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
02/Dec/2020 15:47:24 [NtopPro.cpp:516] WARNING: [LICENSE] or run ntopng in community mode starting
02/Dec/2020 15:47:24 [NtopPro.cpp:517] WARNING: [LICENSE] ntopng --community
02/Dec/2020 15:47:26 [PcapInterface.cpp:93] Reading packets from eth0 [id: 0]
02/Dec/2020 15:47:26 [Ntop.cpp:2441] Registered interface eth0 [id: 0]
02/Dec/2020 15:47:26 [main.cpp:312] PID stored in file /var/run/ntopng.pid
02/Dec/2020 15:47:26 [Geolocation.cpp:140] Loaded database dbip-asn-lite.mmdb [/usr/share/ntopng/httpdocs/geoip/dbip-asn-lite.mmdb][ip_version: 6]
02/Dec/2020 15:47:26 [Geolocation.cpp:140] Loaded database dbip-country-lite.mmdb [/usr/share/ntopng/httpdocs/geoip/dbip-country-lite.mmdb][ip_version: 6]
02/Dec/2020 15:47:26 [Geolocation.cpp:91] Using geolocation provided by DB-IP (https://db-ip.com)
02/Dec/2020 15:47:26 [HTTPserver.cpp:1529] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
02/Dec/2020 15:47:26 [HTTPserver.cpp:1532] HTTP server listening on 3000
02/Dec/2020 15:47:26 [Utils.cpp:720] WARNING: Unable to retain privileges for privileged file writing
02/Dec/2020 15:47:26 [Utils.cpp:764] User changed to ntopng
02/Dec/2020 15:47:26 [NetworkInterface.cpp:2593] Started flow user script hooks loop on interface eth0 [id: 0]...
02/Dec/2020 15:47:26 [main.cpp:382] Working directory: /var/lib/ntopng
02/Dec/2020 15:47:26 [main.cpp:384] Scripts/HTML pages directory: /usr/share/ntopng
02/Dec/2020 15:47:26 [Ntop.cpp:440] Welcome to ntopng x86_64 v.4.2.201105 - (C) 1998-20 ntop.org
02/Dec/2020 15:47:26 [Ntop.cpp:450] Built on Ubuntu 20.04.1 LTS
02/Dec/2020 15:47:26 [NtopPro.cpp:701] [LICENSE] System Id:     C9F0C12C7A07AB20
02/Dec/2020 15:47:26 [NtopPro.cpp:702] [LICENSE] Edition:       Enterprise L
02/Dec/2020 15:47:26 [NtopPro.cpp:703] [LICENSE] License Type:  Time-Limited [Empty license file] License
02/Dec/2020 15:47:26 [NtopPro.cpp:723] [LICENSE] Validity:      Until Wed Dec  2 15:57:24 2020
02/Dec/2020 15:47:26 [Ntop.cpp:841] Adding 172.30.0.173/32 as IPv4 interface address for eth0
02/Dec/2020 15:47:26 [Ntop.cpp:850] Adding 172.30.0.0/24 as IPv4 local network for eth0
02/Dec/2020 15:47:26 [Ntop.cpp:872] Adding fe80::c81:b7ff:feed:bb2a/128 as IPv6 interface address for eth0
02/Dec/2020 15:47:26 [Ntop.cpp:882] Adding fe80::c81:b7ff:feed:bb2a/64 as IPv6 local network for eth0
02/Dec/2020 15:47:27 [PeriodicActivities.cpp:109] Started periodic activities loop...
02/Dec/2020 15:47:27 [startup.lua:50] Processing startup.lua: please hold on...
02/Dec/2020 15:47:27 [startup.lua:144] [lists_utils.lua:758] Refreshing category lists...
02/Dec/2020 15:47:28 [startup.lua:144] [lists_utils.lua:411] Updating list 'Emerging Threats' [https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt]... OK
02/Dec/2020 15:47:28 [startup.lua:144] [lists_utils.lua:411] Updating list 'Feodo Tracker Botnet C2 IP Blocklist' [https://feodotracker.abuse.ch/downloads/ipblocklist.txt]... OK
02/Dec/2020 15:47:28 [startup.lua:144] [lists_utils.lua:411] Updating list 'NoCoin Filter List' [https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt]... OK
02/Dec/2020 15:47:28 [startup.lua:144] [lists_utils.lua:411] Updating list 'SSLBL Botnet C2 IP Blacklist' [https://sslbl.abuse.ch/blacklist/sslipblacklist.txt]... OK
02/Dec/2020 15:47:28 [startup.lua:144] [lists_utils.lua:411] Updating list 'SSLBL JA3' [https://sslbl.abuse.ch/blacklist/ja3_fingerprints.csv]... OK
02/Dec/2020 15:47:28 [startup.lua:144] [lists_utils.lua:411] Updating list 'Snort IP Blacklist' [https://snort.org/documents/ip-blacklist]... OK
02/Dec/2020 15:47:28 [startup.lua:144] [lists_utils.lua:696] Category Lists (694 hosts, 4794 IPs, 98 JA3) loaded in 0 sec
02/Dec/2020 15:47:28 [startup.lua:218] Startup completed: ntopng is now operational
02/Dec/2020 15:47:28 [PeriodicActivities.cpp:172] Each periodic activity script will use 2 threads
02/Dec/2020 15:47:28 [NetworkInterface.cpp:2735] Started packet polling on interface eth0 [id: 0]...
02/Dec/2020 15:47:29 [NetworkInterface.cpp:1699] Invalid packet received [len: 11650][max len: 9019].
02/Dec/2020 15:47:29 [NetworkInterface.cpp:1701] WARNING: If you have TSO/GRO enabled, please disable it
02/Dec/2020 15:47:29 [NetworkInterface.cpp:1703] WARNING: Use sudo ethtool -K eth0 gro off gso off tso off

Also tried running it with online licence check, though I now read that you are discouraging this as it will be removed soon.
docker run -it -p 3000:3000 -v $(pwd)/ntopng.license:/etc/ntopng.license:ro --net=host ntop/ntopng:stable -i eth0 --online-license-check
With this output:
WARNING: Published ports are discarded when using host network mode
Starting redis-server: redis-server.
02/Dec/2020 18:05:52 [Ntop.cpp:2336] Setting local networks to 127.0.0.0/8,fe80::/10
02/Dec/2020 18:05:52 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
02/Dec/2020 18:05:52 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
02/Dec/2020 18:05:52 [NtopPro.cpp:299] [LICENSE] Reading license from /etc/ntopng.license
02/Dec/2020 18:05:52 [NtopPro.cpp:192] Contacting licensing server. Please hold on...
Error reading license file
02/Dec/2020 18:05:52 [NtopPro.cpp:192] Contacting licensing server. Please hold on...
Error reading license file
02/Dec/2020 18:05:52 [NtopPro.cpp:192] Contacting licensing server. Please hold on...
Error reading license file
02/Dec/2020 18:05:52 [NtopPro.cpp:422] [LICENSE] /etc/ntopng.license: unable to validate license [Missing license file]
02/Dec/2020 18:05:52 [NtopPro.cpp:297] [LICENSE] Reading license from Redis
02/Dec/2020 18:05:52 [NtopPro.cpp:425] [LICENSE] Unable to validate license [Empty license file]
02/Dec/2020 18:05:52 [NtopPro.cpp:493] WARNING: [LICENSE] Invalid license [Missing license file]
02/Dec/2020 18:05:52 [NtopPro.cpp:510] WARNING: [LICENSE] ntopng will now run in Enterprise L edition for 10 minutes
02/Dec/2020 18:05:52 [NtopPro.cpp:512] WARNING: [LICENSE] before returning to community mode
02/Dec/2020 18:05:52 [NtopPro.cpp:514] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
02/Dec/2020 18:05:52 [NtopPro.cpp:516] WARNING: [LICENSE] or run ntopng in community mode starting
02/Dec/2020 18:05:52 [NtopPro.cpp:517] WARNING: [LICENSE] ntopng --community
02/Dec/2020 18:05:54 [PcapInterface.cpp:93] Reading packets from eth0 [id: 0]
02/Dec/2020 18:05:54 [Ntop.cpp:2441] Registered interface eth0 [id: 0]
02/Dec/2020 18:05:54 [main.cpp:312] PID stored in file /var/run/ntopng.pid
02/Dec/2020 18:05:54 [Geolocation.cpp:140] Loaded database dbip-asn-lite.mmdb [/usr/share/ntopng/httpdocs/geoip/dbip-asn-lite.mmdb][ip_version: 6]
02/Dec/2020 18:05:54 [Geolocation.cpp:140] Loaded database dbip-country-lite.mmdb [/usr/share/ntopng/httpdocs/geoip/dbip-country-lite.mmdb][ip_version: 6]
02/Dec/2020 18:05:54 [Geolocation.cpp:91] Using geolocation provided by DB-IP (https://db-ip.com)
02/Dec/2020 18:05:55 [HTTPserver.cpp:1529] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
02/Dec/2020 18:05:55 [HTTPserver.cpp:1532] HTTP server listening on 3000
02/Dec/2020 18:05:55 [Utils.cpp:720] WARNING: Unable to retain privileges for privileged file writing
02/Dec/2020 18:05:55 [Utils.cpp:764] User changed to ntopng
02/Dec/2020 18:05:55 [NetworkInterface.cpp:2593] Started flow user script hooks loop on interface eth0 [id: 0]...
02/Dec/2020 18:05:55 [main.cpp:382] Working directory: /var/lib/ntopng
02/Dec/2020 18:05:55 [main.cpp:384] Scripts/HTML pages directory: /usr/share/ntopng
02/Dec/2020 18:05:55 [Ntop.cpp:440] Welcome to ntopng x86_64 v.4.2.201105 - (C) 1998-20 ntop.org
02/Dec/2020 18:05:55 [Ntop.cpp:450] Built on Ubuntu 20.04.1 LTS
02/Dec/2020 18:05:55 [NtopPro.cpp:701] [LICENSE] System Id:     C9F0C12C7A07AB20
02/Dec/2020 18:05:55 [NtopPro.cpp:702] [LICENSE] Edition:       Enterprise L
02/Dec/2020 18:05:55 [NtopPro.cpp:703] [LICENSE] License Type:  Time-Limited [Missing license file] License
02/Dec/2020 18:05:55 [NtopPro.cpp:723] [LICENSE] Validity:      Until Wed Dec  2 18:15:52 2020
02/Dec/2020 18:05:55 [Ntop.cpp:841] Adding 172.30.0.173/32 as IPv4 interface address for eth0
02/Dec/2020 18:05:55 [Ntop.cpp:850] Adding 172.30.0.0/24 as IPv4 local network for eth0
02/Dec/2020 18:05:55 [Ntop.cpp:872] Adding fe80::c81:b7ff:feed:bb2a/128 as IPv6 interface address for eth0
02/Dec/2020 18:05:55 [Ntop.cpp:882] Adding fe80::c81:b7ff:feed:bb2a/64 as IPv6 local network for eth0
02/Dec/2020 18:05:55 [PeriodicActivities.cpp:109] Started periodic activities loop...
02/Dec/2020 18:05:56 [startup.lua:50] Processing startup.lua: please hold on...
02/Dec/2020 18:05:56 [startup.lua:144] [lists_utils.lua:758] Refreshing category lists...
02/Dec/2020 18:05:56 [startup.lua:144] [lists_utils.lua:411] Updating list 'Emerging Threats' [https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt]... OK
02/Dec/2020 18:05:56 [startup.lua:144] [lists_utils.lua:411] Updating list 'Feodo Tracker Botnet C2 IP Blocklist' [https://feodotracker.abuse.ch/downloads/ipblocklist.txt]... OK
02/Dec/2020 18:05:56 [startup.lua:144] [lists_utils.lua:411] Updating list 'NoCoin Filter List' [https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt]... OK
02/Dec/2020 18:05:56 [startup.lua:144] [lists_utils.lua:411] Updating list 'SSLBL Botnet C2 IP Blacklist' [https://sslbl.abuse.ch/blacklist/sslipblacklist.txt]... OK
02/Dec/2020 18:05:56 [startup.lua:144] [lists_utils.lua:411] Updating list 'SSLBL JA3' [https://sslbl.abuse.ch/blacklist/ja3_fingerprints.csv]... OK
02/Dec/2020 18:05:57 [startup.lua:144] [lists_utils.lua:411] Updating list 'Snort IP Blacklist' [https://snort.org/documents/ip-blacklist]... OK
02/Dec/2020 18:05:57 [startup.lua:144] [lists_utils.lua:696] Category Lists (694 hosts, 4794 IPs, 98 JA3) loaded in 0 sec
02/Dec/2020 18:05:57 [startup.lua:218] Startup completed: ntopng is now operational
02/Dec/2020 18:05:57 [PeriodicActivities.cpp:172] Each periodic activity script will use 2 threads
02/Dec/2020 18:05:57 [NetworkInterface.cpp:2735] Started packet polling on interface eth0 [id: 0]...
02/Dec/2020 18:05:58 [NetworkInterface.cpp:1699] Invalid packet received [len: 15994][max len: 9019].
02/Dec/2020 18:05:58 [NetworkInterface.cpp:1701] WARNING: If you have TSO/GRO enabled, please disable it
02/Dec/2020 18:05:58 [NetworkInterface.cpp:1703] WARNING: Use sudo ethtool -K eth0 gro off gso off tso off

Can you advise how I can get it to recognise the licence that is in /etc/ntopng.license on the host server?

Thanks,
Stephen

**Comment by cardigliano** [comment]
@swilkey please make sure that ntopng.license is present in the same folder where you are running ntopng (otherwise copy it from /etc/ntopng.license or use /etc in place of $(pwd)). Please also note you are adding –network=host as ntopng parameter (I guess you wanted to add it as docker parameter, before ntop/ntopng:stable.
In short, please try with:

rmdir ntopng.license # this cleanup folders eventually created by docker
cp /etc/ntopng.license .
sudo docker run -it -p 3000:3000 -v $(pwd)/ntopng.license:/etc/ntopng.license:ro --net=host ntop/ntopng:stable -i eth0

**Comment by swilkey** [comment]
thank you!  changing $(pwd) to /etc fixed the problem.  Thanks very much for your help!
