### ISSUE TITLE
Nprobe usage

### ISSUE THREAD

**Issue by AliAAbadi** [ntop/ntopng#48]
I have installed ntopng on Ubuntu machine to work as a collector for IPFIX traffic. I would like to know if nprobe should be installed to monitor the IPFIX traffic or it's possible to do that only using ntopng.
Please advise.

**Comment by lucaderi** [comment]
@AliAAbadi Yes you need to install and start nProbe as explained in http://www.ntop.org/nprobe/why-nprobejsonzmq-instead-of-native-sflownetflow-support-in-ntopng/
