### ISSUE TITLE
ntop - Top talkers Historical

### ISSUE THREAD

**Issue by iber-mi** [ntop/ntopng#480]
Hi, I am using ntop because ntopng can not use it for debian 7 and can not upgrade to 8 drop other services. I would like to know how to activate the Top Talkers> Historical, because right now does not work when I select this option, that way you can do? Deputy image.

![top talkers-historcal](https://cloud.githubusercontent.com/assets/17645260/14381825/97d784ca-fd89-11e5-894b-61ff58070f23.png)

**Comment by simonemainardi** [comment]
ntop is no longer supported.

https://github.com/ntop/ntopng/issues/452
https://github.com/ntop/ntopng/issues/446
https://github.com/ntop/ntopng/issues/144

**Comment by iber-mi** [comment]
And explain why I can not use ntopng, if you did nProbe for Debian 7 x64 would not have these problems ... the only thing I ask is if you could show me this option by adding some kind of quick parameter, I ask nothing more, maybe it's something easy that I you know that answer without giving rodeos that is no longer supported, thanks.

**Comment by simonemainardi** [comment]
explanation was given here: https://github.com/ntop/ntopng/issues/144

**Comment by iber-mi** [comment]
Explanation? That ?, I'm asking to see the Top Talkers> Historical and there is no explanation for this, as indicated by the title of the issue, I do not understand your answer.

**Comment by simonemainardi** [comment]
you said '_And explain why I can not use ntopng_': @lucaderi gave you the explanation in #144

**Comment by iber-mi** [comment]
I can not use nprobe, so I do not use ntopng, now I just need the Top Talkers> Historical functioning me, it is not difficult to understand.

**Comment by simonemainardi** [comment]
This is community support. As already discussed, we have limited resources and we are unable to support ntop. It is not difficult to understand.

We believe we should focus our efforts on ntopng as many more community members will have a benefit. 

If you want support for ntop that has been discontinued 2 years ago, then you are not asking for community support as you will be the only one who benefits. You are looking for customer support. So please try and contact a developer directly and ask for a quote, rather than flooding the ntopng issue tracker with ntop questions.

**Comment by iber-mi** [comment]
As I said at the time, would be in the community ntopng if compatible with Debian 7 nprobe not work with this ... I do not think it's that hard to do because it is not an old system, but I do not you can help Debian install this system in July so I have to rely NTOP ... it is not so hard to understand.

**Comment by simonemainardi** [comment]
If you don't think it's that hard, why don't you start working on that? Please submit pull request when done and we will be happy to evaluate that. Thank you.

**Comment by iber-mi** [comment]
I think and say it is not so difficult for a reason, ntopong think if it works on Debian 7 what works is not nprobe because it is only 8 (jessie) but I see that if there is a functioning nprobe-debian7 but mips: http://packages.ntop.org/apt/wheezy/mips/nprobe_7.3.160217-4844_mips.deb

so I say I do not think it is so difficult then to do the same but for x86 or x64. Then there is the nprobes binary file that does not support ZMQ ... no good to me then, my big problem is NPROBE, you could do this help request? It is so difficult to do?

**Comment by iber-mi** [comment]
Any response to this?

**Comment by lucaderi** [comment]
@iber-mi We're preparing Debian 7 x64 packages. nprobes is a small, binary, self-contained build and it does not include ZMQ for avoiding dependencies.

**Comment by iber-mi** [comment]
Prepare packages for Debian 7? :O but you mean nprobe too? Ntopng because as I said I think with 8 Debian repositories can install it and it works, the problem is nprobe for x64, you can prepare this package?

**Comment by iber-mi** [comment]
Any response to this?

**Comment by iber-mi** [comment]
Hello???

**Comment by lucaderi** [comment]
@iber-mi Packages will be release by the end of this week. Please monitor http://packages.ntop.org
