### ISSUE TITLE
Option to sort within categories and subcategories the ProbeID's

### ISSUE THREAD

**Issue by astalush** [ntop/ntopng#4800]
Could you create categories and subcategories for example I have 200 switchs to supervise and they are sorted with the postal code (37XXX,45XXX,80XXX, etc) and under each code there are others code like 37100, 37200 , 45100,45160, etc. Now I have them like this https://whatis.x264.xyz/images/2fb5d4f426e781468da16de6516900f5.png . And 200 lines are a lot that's why it's easier with categories. And I cannot scroll down to see other ProbeID's, like in the photos attached 👍 https://whatis.x264.xyz/images/4de52adb4615e48b98e2248a1ff6b0d6.png versus https://whatis.x264.xyz/images/e5ead94db1fc8d286f81ee964d395738.png . I cannot zoom into browser to see all the 200 switchs. Not possible to scroll.

**Comment by simonemainardi** [comment]
![](https://whatis.x264.xyz/images/2fb5d4f426e781468da16de6516900f5.png)



![](https://whatis.x264.xyz/images/4de52adb4615e48b98e2248a1ff6b0d6.png)



![](https://whatis.x264.xyz/images/e5ead94db1fc8d286f81ee964d395738.png)

**Comment by simonemainardi** [comment]
please, report a screenshot of the full "About" page, footer included

**Comment by astalush** [comment]
https://whatis.x264.xyz/images/0279df45aa42748cc4f69e6e98c97aed.png

**Comment by astalush** [comment]
Any chance with an update? Thanks.

**Comment by lucaderi** [comment]
In essence your request is to sort the menu after split into categories? How do you define a category

Why do you keep all traffic split per switch? Do you really need that?

**Comment by astalush** [comment]
Where I work I need to supervise all switchs. The firm has agencies all around France and we are in charge of supervising the network. In each agency there is a DELL switch with sFlow activated that I want to add into ntopng. There are 150-160 agencies so 150-160 switchs connected to routers and into an MPLS VPN. We are at the datacenter and we supervise all network so if I add all the switchs I cannot see all of them so I would like to sort them out with their region code. Group them by their region code so I can browse them more simple. When we have a problem I need to watch only the switch in question in the agency that has the problem. But with InfluxDB I wanna also have a DB with infos in the past for the agencies.

**Comment by lucaderi** [comment]
Would you be willing to sponsor this development?

**Comment by astalush** [comment]
We would like to buy ntopng and nprobe licenses, I already talked to your colleague who already gave me 7 days licences to test the apps.

**Comment by lucaderi** [comment]
Sure but this development has some challenges
- currently we support 32 interfaces and not 200 (in other words we have set an artificial limit to avoid ntopng so be inefficient)
- we need to cluster the GUI

Is your need only realtime or do you need historical data? With 200 switches and hundred of ports the workload is a lot. That is why I am asking you what you really need.

**Comment by astalush** [comment]
The sFlow that I've activated sends to nprobe the flows, so you're telling me that nprobe only works with maximum 32 connections? We need both, realtime and historical. When I say historical it's like 'hey, we had a network problem last week, can you look into it? yes, I will check out the data from last week for your switch." But if the switch wasn't added for last week I cannot look into it. Ressources are not a problem, we have hundreds of VM who can take workloads.

**Comment by lucaderi** [comment]
How many nprobe have in your network? We need to cluster data in some way to make a plan

**Comment by astalush** [comment]
We have 15 regions, if we make 15 VM for each region, and each region with his own nprobe and ntopng, do we need 15 licenses, no?

**Comment by astalush** [comment]
Now we have one NPROBE and one NTOPNG for testing purposes, with 29 switchs sending sFlow datas to this one NPROBE.

**Comment by astalush** [comment]
> How many nprobe have in your network? We need to cluster data in some way to make a plan

OK, can we talk in private? Via email? Discord?

**Comment by simonemainardi** [comment]
For now, we've added a searchbox in the interfaces menu to ease lookup and find them

![image](https://user-images.githubusercontent.com/3397663/104041613-9edd7a00-51d9-11eb-9e6c-d3f6b9fa7619.png)
