### ISSUE TITLE
Historical Flow view.

### ISSUE THREAD

**Issue by vijaytejak** [ntop/ntopng#4801]
Hi,
I am using NtopNG M enterprise version.

Can I search and view the historical flows of a device, 
Ex:- A device uploaded 10GB of data to 2 IPs, a few days back, I want to view those flows. where can I and what settings do I need to enable.

**Comment by simonemainardi** [comment]
Sure. enable nIndex.  See https://www.ntop.org/guides/ntopng/historical_flows.html#

**Comment by vijaytejak** [comment]
Thanks a lot, saved my day, now I will first go through the complete documentation.

**Comment by vijaytejak** [comment]
Does Flow dump requires Enterprise Large license?

**Comment by simonemainardi** [comment]
Pro license or above is needed.
