### ISSUE TITLE
L7 contacts not showing?

### ISSUE THREAD

**Issue by vijaytejak** [ntop/ntopng#4802]
I am running ntopng as
ntopng -F --dump-flows, but i am unable to see the flow in historic charts as explained in this Link.

what am I missing?
https://www.ntop.org/guides/ntopng/historical_flows.html#

**Comment by vijaytejak** [comment]
I am unable to see Flow dump settings on the runtime preferences page, as shown in this link.
https://www.ntop.org/guides/ntopng/advanced_features/flows_dump.html

**Comment by simonemainardi** [comment]
show the full configuration used and a screenshot of this page

![image](https://user-images.githubusercontent.com/3397663/101148644-2b66ac80-361e-11eb-9925-07df1cc86efa.png)

**Comment by simonemainardi** [comment]
And also the About page.

**Comment by vijaytejak** [comment]
got it now, sorry wrong config, thanks for the response.

**Comment by vijaytejak** [comment]
pls close this now.
