### ISSUE TITLE
Mime information of Historical flow ?

### ISSUE THREAD

**Issue by vijaytejak** [ntop/ntopng#4803]
Can we see MIME data of a flow?

Ex:- If someone downloads a file I need to know about the file type whether it is pdf, exe, mp4, etc.

I am sending all the traffic to ntopng 2nd interface using a port mirror from the switch, is the above possible with this scenario?

**Comment by vijaytejak** [comment]
if i use nprobe, can i get the MIME details ?

**Comment by simonemainardi** [comment]
Correct. nProbe with the HTTP plugin and use IE `HTTP_MIME`

`[NFv9 57656][IPFIX 35632.184][Len 256 varlen] %HTTP_MIME                        HTTP Mime Type`
