### ISSUE TITLE
ntopng - memory leak

### ISSUE THREAD

**Issue by DimaOsoianu** [ntop/ntopng#4804]
Hi 

I recently acquired ntopng and I faced issue with memory leak:
I installed on my machine Ubuntu 4 GB Ram and after 4 days, memory usage got 93% and ntopng process was consuming 2.6 G ram.
After that I installed 8 GB RAM in the Ubuntu and started again NTOP and I have enabled Monitoring.
Below is screenshot of Free Memory from Ubuntu. 
![NTOP_4 12](https://user-images.githubusercontent.com/36902487/101210004-110bed80-3675-11eb-8437-33f2d8b3f16e.jpg)
In 2 days system run out of Memory.
![process_manager](https://user-images.githubusercontent.com/36902487/101210150-516b6b80-3675-11eb-8959-2217e9a0fbab.jpg)
As you can see, ntopng process is consuming 6GB of RAM !
My licence  and version output:
```
v.4.2.201125	[Enterprise/Professional build]
GIT rev:	4.2-stable:97c2c7537b7808baf0a22aed19d4eb20924eae61:20201125
Pro rev:	r3332
Built on:	Ubuntu 20.04.1 LTS
System Id:	39BB177500870F20
Platform:	x86_64
Edition:	Enterprise L
License Type:	Permanent
Maintenance:	Until Wed Nov 24 20:26:02 2021 [354 days left]
```
Startup commands:
```
sudo ntopng -i tcp://127.0.0.1:5556 -F nindex -X 1000000
nprobe --zmq "tcp://*:5556" -i none -n none --collector-port 1234 -T "@NTOPNG@" -P /home/dima/Desktop
```

Can you please help? 
I don't think its normal that program is consuming all system memory in 4 days. 
I have restarted the ntopng process on 1st of December.

Amount of flows on my System:
Collected Flows max 2.5 KFlow/ s

Thanks in Advance for Help
Best Regards
Dumitru

**Comment by cardigliano** [comment]
Update: I suggested @DimaOsoianu to try disabling nIndex as he has the impression it depends on that component, to isolate the issue.

**Comment by DimaOsoianu** [comment]
Hi

I have disabled nIndex on another system with same version  and memory leaking is not observed. 
Below is graph of memory usage of ntong with nIndex enabled: ( I have restarted ntopng process to prevent system crash)
![Memory_Usage_with_nIndex](https://user-images.githubusercontent.com/36902487/101541754-226d3680-39a2-11eb-8e93-13cccfb15013.jpg)
Below is graph of usage of ntopng with nIndex disabled:
![Memory_Usage_no_nIndex](https://user-images.githubusercontent.com/36902487/101541809-331dac80-39a2-11eb-8bae-fad502f618cf.jpg)
With nIndex disabled there is no memory leak observed. 
Graph presented is for last 24 hours.

Both systems are having same amount of RAM and receiving same flows from routers. 
```
dima@dima:~$ ntopng --version
v.4.2.201125    [Enterprise/Professional build]
GIT rev:        4.2-stable:97c2c7537b7808baf0a22aed19d4eb20924eae61:20201125
Pro rev:        r3332
Built on:       Ubuntu 20.04.1 LTS
System Id:      395B553D00870F20
Platform:       x86_64
Edition:        Enterprise L
License Type:   Time-Limited [License Ok]
```

**Comment by cardigliano** [comment]
@DimaOsoianu just to make sure, did you try enabling nindex on the second system, to check that you are able to reproduce the leak there, and exclude any other factor? Thank you for the details.

**Comment by DimaOsoianu** [comment]
@cardigliano  Doing it now.

**Comment by DimaOsoianu** [comment]
@cardigliano 
I have monitored ntop with nIndex enabled for 24 hours.

I enabled the nIdex with string:
```
sudo ntopng -i tcp://127.0.0.1:5556 -F nindex -X 1000000
```
Graph says everything I believe....
yellow arrow means stopping ntopng and restarting it with nIndex enabled.
![Memory_Ntop_nIndex](https://user-images.githubusercontent.com/36902487/101677596-0bd7e580-3a5d-11eb-9952-89d250a4231f.jpg)
Please let me know what will be next steps to debug this issue.



Thanks

**Comment by cardigliano** [comment]
Update: it seems the leak almost disappeared from the same ntopng instance in the last days. In the meanwhile I pushed (minor) memory leak fixes, and running the sanitizer for 1+ day is reporting *no* leaks. Still monitoring the system..

**Comment by lucaderi** [comment]
The issue seemes to be fied on our end. Will reopen if necessary
