### ISSUE TITLE
Ho remove SMB Insecure Version from nDPI alert

### ISSUE THREAD

**Issue by eliassal** [ntop/ntopng#4806]
Hi, I am getting floes alerts for NetBios.SMBV1. I have an old NAS which I need to access it with SMB V1 so I need to disable this alert. clicking on the gear o modify/disable, it is part of nDPI Flow risks
How can I remove it from the group of risks

![ndpiRisks](https://user-images.githubusercontent.com/8447864/101239869-5bc84c80-36eb-11eb-9f4a-1f046dd4fe79.jpg)

**Comment by eliassal** [comment]
Also, for another flow, I see 
`Malformed packet [score:50] (gear)`

Is there somewhere wher we can see what is the malformed packet? It is mDNS protocol so why it is malformed!!!

Clicking on the gear I go back to the same nDPI alert parameters dialog
![mdnsntop](https://user-images.githubusercontent.com/8447864/101239980-61726200-36ec-11eb-8436-de01f9ecaf29.jpg)

**Comment by simonemainardi** [comment]
Hold the CTRL key and click the items in a list to choose them. Click all the items you want to select. They don't have to be next to each other. Click any item again to deselect it

**Comment by eliassal** [comment]
OK thanks, I did for my 1st query, can you please respond to my 2nd query

Malformed packet [score:50] (gear)

Is there somewhere wher we can see what is the malformed packet? It is mDNS protocol so why it is malformed!!!

**Comment by simonemainardi** [comment]
attach a pcap of the MDNS traffic triggering the malformed alert and we'll look into it

**Comment by eliassal** [comment]
The message is not there anymore as I restarted the service yesterday.
Here are 2  new mdns PCAP file, one flagged with yellow triangle flagged , small pcap file. 
The 2nd one was in red flows and flagged  flagged red triangle triangle but the pcpa is 80Mega, I was able to download it when I hit back button it disappeared from the list and I don't see the red flows icon anymore



[NPF_{1CF6F05B-8257-4458-84EC-4A0FD242FBD9}_192.168.1.19_live.zip](https://github.com/ntop/ntopng/files/5651909/NPF_.1CF6F05B-8257-4458-84EC-4A0FD242FBD9._192.168.1.19_live.zip)
[NPF_{1CF6F05B-8257-4458-84EC-4A0FD242FBD9}_192.168.1.16_live.zip](https://github.com/ntop/ntopng/files/5651913/NPF_.1CF6F05B-8257-4458-84EC-4A0FD242FBD9._192.168.1.16_live.zip)

![mDNS](https://user-images.githubusercontent.com/8447864/101336999-6fa2b880-387b-11eb-9669-34c96f0eaed9.jpg)

**Comment by eliassal** [comment]
Just went back again to the interface , I have 8 red alerts in icon red flows and what is strange it is all coming from the machine where btopng is running. The 2nd pcap of 80Mega was for the same VM file I sent earlier will give you I think  the details
![mdns_002](https://user-images.githubusercontent.com/8447864/101337409-e8097980-387b-11eb-97bb-c72d5b1cffd1.jpg)

**Comment by eliassal** [comment]
So I am completely confused now, 1 minutes we have mdns in yellow flows, 2 minutes later more mdns flows but in red

**Comment by eliassal** [comment]
Here is again the pcap for one of the red flows which is 114Mega
[NPF_{1CF6F05B-8257-4458-84EC-4A0FD242FBD9}_192.168.1.19_live (2).zip](https://github.com/ntop/ntopng/files/5651971/NPF_.1CF6F05B-8257-4458-84EC-4A0FD242FBD9._192.168.1.19_live.2.zip)

**Comment by eliassal** [comment]
Even though I upddated the nDPI by not chosing SMB1, ntopng still alerts on mdns as you can notice in the snapshot
when I click on the Netbios.SMBv1 in the application column, I get a list of all hosts using smbv1 (3rd snapshot)

![nDPI-Conf](https://user-images.githubusercontent.com/8447864/101340947-ad561000-3880-11eb-8de5-44d2b6256b3a.jpg)

![nDPI-alert_002](https://user-images.githubusercontent.com/8447864/101340964-b47d1e00-3880-11eb-8f6c-498f0a7b7575.jpg)

![nDPI-alert_003](https://user-images.githubusercontent.com/8447864/101340977-ba72ff00-3880-11eb-9526-d5c487f048b5.jpg)

**Comment by eliassal** [comment]
more and more smbv1 alerts just now  in spite of the fact that it is disabled

![nDPI-alert_004](https://user-images.githubusercontent.com/8447864/101341632-ab408100-3881-11eb-89de-c147d7f18e9e.jpg)
