### ISSUE TITLE
Vlan2 is not discovered/listed - How to add it?

### ISSUE THREAD

**Issue by eliassal** [ntop/ntopng#4807]
Hi, ntopng (installed on a win 10 machine on subnet 192.168.1.0/24). Network is managed by a router where I have this 1st network and 2nd vlan2 on 192.168.2.0/24 and it works fine and I can access machines on this 2nd vlan, however, ntopng does not list this 2nd vlan in the networks list, it only lists the 1st one and the IPV6 one of the rounter.
How can I add this vlan2?
Thanks

**Comment by simonemainardi** [comment]
Vlan2 is physically separated from vlan1 at layer 2. So it is normal that the discovery run on vlan1 does not discover devices in vlan2. Being able to reach vlan2 hosts is definitely something which is happening at layer 3.

**Comment by eliassal** [comment]
OK thanks, so there is no way of monitring both in this case
