### ISSUE TITLE
Too many hosts for ntopng leading to packet drops and high CPU load. Please tune -x/-X and restart ntopng

### ISSUE THREAD

**Issue by eliassal** [ntop/ntopng#4809]
After a while of running ntopng on a win10 VM (3 CPUs, 6G of Ram allocated), I get Red and yellow alerts as follows
`Too many hosts for ntopng leading to packet drops and high CPU load. Please tune -x/-X and restart ntopng`
I am googling but not able to find how to do this for the ntopng service in windows
I have a small homeoffice network with 3 physical servers, 1 VMs, couple of NAS and 3 smartphones. So what is meant by too many hosts?
Thanks
![ToomanyHosts](https://user-images.githubusercontent.com/8447864/101277086-13c02d00-37b2-11eb-9682-3c4fe3950a07.jpg)

**Comment by simonemainardi** [comment]
attach a screenshot of the whole about page, make sure to include header and footer

**Comment by eliassal** [comment]
Hi Simon, here a full screenshot as it happened again this morning
![ToomanyHosts2](https://user-images.githubusercontent.com/8447864/101892416-a3dfe700-3ba3-11eb-8241-b53c644006c7.jpg)

**Comment by eliassal** [comment]
This is really annoying, now whenever I click on any thing I get 2 alerts one above the other, need to click on the x to close, click on another link I get the same thing 2 alerts and continues like this, I am not able to concentrate on trying understanding when I try to follow an alert

![annoyingAlert](https://user-images.githubusercontent.com/8447864/101895422-cbd14980-3ba7-11eb-980d-0689abce573b.jpg)

**Comment by lucaderi** [comment]
These messages are designed to be annoying as you need to fix the issue because this is a critical problem you need to address

**Comment by 315xiaoyao** [comment]
我也遇到这个问题，有找到解决方法的大神吗？
