### ISSUE TITLE
Network slown down once ntopng is run

### ISSUE THREAD

**Issue by eliassal** [ntop/ntopng#4810]
I have noticed that as soon as I start ntopng service and it starts gathering details, on all my laptops and servers network slows down, browsing to a google.com takes 1 minute, as soon I stop ntopng, browsing even doesn't take 1 second. Can you please le me know what is the impact of ntopng on network performance and why this happens?

**Comment by simonemainardi** [comment]
This is unlikely as ntopng is passive. Attach a network diagram and show details of the network

**Comment by eliassal** [comment]
I have a Draytek router connected to my ISP. Behind the router, I have 2 vlans (managed by the router). The router is connected to 2 switches everyone serving 1 subnet (broadcast domain). I generated the map for the network (pdf file), can you please tell me how I can share it with you as I don't want to make it public, thanks

**Comment by simonemainardi** [comment]
use our Discord channels and send it privately as message

**Comment by eliassal** [comment]
Done sent through discord right now

**Comment by lucaderi** [comment]
I have run tests on Windows and this is normal when network discovery is running as it pings the nextworks and scans devices. I suggest you to disable network discovery in Runtime Preferences
![Screen Shot 2020-12-17 at 16 09 21](https://user-images.githubusercontent.com/4493366/102505434-44417a00-4082-11eb-9042-b0d6728c4764.png)

**Comment by lucaderi** [comment]
Closing the ticket:will reopen if necessary

**Comment by eliassal** [comment]
OK, thanks
