### ISSUE TITLE
All Unknown Hosts - listing discovered hosts/devices

### ISSUE THREAD

**Issue by eliassal** [ntop/ntopng#4811]
Can you please tell me why my discovered hosts appear in the list of unknown hosts and we see it as local and I can see it in the devices list? Please note that 192.168.1.19 is the VM running ntopng and 192.168.1.3 is one of my desktops.

![AllUnknownHosts](https://user-images.githubusercontent.com/8447864/101280422-33168480-37c9-11eb-9844-27c05e0a2c42.jpg)

**Comment by simonemainardi** [comment]
"Unknown" means hosts that have performed "Unknown" traffic. That is, traffic not recognized by any of the nDPI supported protocols.
