### ISSUE TITLE
Speedtest displays incorrect measurments

### ISSUE THREAD

**Issue by eliassal** [ntop/ntopng#4812]
In ntopng, speedtest does not display real/good measurements. It is running on a win10 VM it says 81 Mb/second, whereas when I run speedtest from my dektop, I get 600Mb/sec

![speedtest](https://user-images.githubusercontent.com/8447864/101281058-517e7f00-37cd-11eb-916d-05525dd59e25.jpg)

**Comment by simonemainardi** [comment]
Your claims are too strong and not enough evidence is given to support them.

How can you tell it’s not the VM which is experiencing a slower speed? Why are you blaming ntopng.

Be careful in opening issues and add enough evidence to prove them.

**Comment by eliassal** [comment]
Simon, I am not blaming, I am very new to ntopng and find it has wonderful features, as I said in one thread, as soon as I start ntopng service on the VM even with 3 CPU dedicated, the nachine slows down and I requested you on the t post to let me know how I can share the network map. Anyway, just done a speedtest directly in browser on the VM itself, almost same results as the desktop with huge difference with ntopng alert, please see snapshot

![speedtest_002](https://user-images.githubusercontent.com/8447864/101281752-3281ec00-37d1-11eb-8f62-a1d55ff80026.jpg)

**Comment by eliassal** [comment]
In fact it seems that the alert was stuck, after restarting the service, it is reporting gor the time being correctly

**Comment by simonemainardi** [comment]
> In fact it seems that the alert was stuck, after restarting the service, it is reporting gor the time being correctly

please try to rephrase as I am not sure to understand

**Comment by eliassal** [comment]
The alert was stuck and was geting executed every 10 minutes. I stoped/restarted the ntopng server and started to work again correctly and execute every 10 minutes

**Comment by simonemainardi** [comment]
This ticket is "Speedtest displays incorrect measurments". Are you getting correct measurements?

**Comment by eliassal** [comment]
In fact NO, it seems it is not working since last restart, it seems that it worked once on December 7, then nothing as you can see in the snapshots, for 1 hour, 1 day, 1 week, 1 month
![speedTestNowork](https://user-images.githubusercontent.com/8447864/102077092-0d146400-3e09-11eb-8f6d-2fdd001d439b.jpg)

![speedTestNowork_30M](https://user-images.githubusercontent.com/8447864/102077116-169dcc00-3e09-11eb-87b7-5fd9d790d1f3.jpg)

![speedTestNowork_30M_002](https://user-images.githubusercontent.com/8447864/102077126-1bfb1680-3e09-11eb-8e47-89be98e0f3b8.jpg)

![speedTestNowork_30M_003](https://user-images.githubusercontent.com/8447864/102077150-24535180-3e09-11eb-87e3-0771c4eec430.jpg)

![speedTestNowork_30M_004](https://user-images.githubusercontent.com/8447864/102077169-2a493280-3e09-11eb-83ff-1bfbad94ed6a.jpg)

**Comment by eliassal** [comment]
Even though it was run on December 7, the table near chart in the last snapshot (1 months) displays no data!

**Comment by eliassal** [comment]
And please notice this snapshot, the speedtest should run every 5 minutes, is ther anything wrong in the config?
![speedTestNowork_Config](https://user-images.githubusercontent.com/8447864/102077499-afcce280-3e09-11eb-8915-ca58a6b224ad.jpg)

**Comment by simonemainardi** [comment]
delete an re-add speediest among active monitoring

**Comment by eliassal** [comment]
I have done it twice before December 7

**Comment by lucaderi** [comment]
Speedtest results are reported by speediest itself. ntopng just reports the value. Comparing it with charts makes no sense as I am not sure speedtest runs the test filling up the pipe

**Comment by eliassal** [comment]
OK, but the alert is stuck again, It works only once after restarting the service then it gets stuck
