### ISSUE TITLE
Traffic report disappears

### ISSUE THREAD

**Issue by eliassal** [ntop/ntopng#4814]
When I restart ntopng and log to web, I get 3 items in the "Dasboard" as you can notice in the 1st snapshot.  After hiting other links and coming back and click on Dasboard, the "Traffic report" item disappears" and not able to find it back (2nd snapshot)
How can I access it again?

![trafficReport](https://user-images.githubusercontent.com/8447864/101342244-944e5e80-3882-11eb-8bab-27bcaf4dc11a.jpg)

![trafficReport_002](https://user-images.githubusercontent.com/8447864/101342282-9f08f380-3882-11eb-81af-66d810653c0f.jpg)

**Comment by simonemainardi** [comment]
Traffic report is a pro-only feature, when the demo expires, access is no longer possible.

This information was available in the online documentation, as many of the other questions you've posted opening a ton of issues https://github.com/ntop/ntopng/issues?q=author%3Aeliassal+

Do not abuse Github Issues. Issues are issues. For these simple questions, you'd better look online first or ask on discord.

**Comment by eliassal** [comment]
OK Sir
