### ISSUE TITLE
NTOPNG new installation issue connecting NPROBE

### ISSUE THREAD

**Issue by swilkey** [ntop/ntopng#4815]
Hi,

I've installed NTOPNG using docker this week.  It is working well detecting all the traffic on the server's network port.  However, I now want to receive traffic from an nprobe running on an edge router.  I am assuming that you can receive traffic from a version 7.3 nprobe on a version 9.3 ntopng - but if this is not the case that is probably where the problem is.  I have submitted a separate ticket a few days back stating my willingness to help with building newer versions of nprobe on the edge router if it is technically possible to go beyond version 7.3 and you would like my help to do so as I have multiple edge routers available to use.

So assuming that the version mismatch isn't the problem the next thing to know is this.  My docker ntopng is running behind a reverse proxy on a server in the amazon cloud with a public IP address, and my nprobe is running with a dynamic private IP address on the other side of the internet.

So I'm starting nprobe like this:
sudo /usr/local/bin/nprobe --zmq-probe-mode --zmq "tcp://myserverfqdnremoved:5556" -i eth0 -n none ntopng

And it is giving this output on the console:
07/Dec/2020 15:25:48 [nprobe.c:3368] ERROR: Invalid nProbe license (/etc/nprobe.license) [Missing license file]
07/Dec/2020 15:25:48 [nprobe.c:3375] ERROR: *****************************************************
07/Dec/2020 15:25:48 [nprobe.c:3376] ERROR: **                                                 **
07/Dec/2020 15:25:48 [nprobe.c:3377] ERROR: **  Switching to DEMO MODE (missing valid license) **
07/Dec/2020 15:25:48 [nprobe.c:3378] ERROR: **                                                 **
07/Dec/2020 15:25:48 [nprobe.c:3379] ERROR: **  Purchase your nProbe license at                **
07/Dec/2020 15:25:48 [nprobe.c:3380] ERROR: **       https://shop.ntop.org/                    **
07/Dec/2020 15:25:48 [nprobe.c:3381] ERROR: **                                                 **
07/Dec/2020 15:25:48 [nprobe.c:3382] ERROR: *****************************************************
07/Dec/2020 15:25:48 [nprobe.c:7192] ERROR: ***************************************************************
07/Dec/2020 15:25:48 [nprobe.c:7193] ERROR: * NOTE: This is a DEMO version limited to 25000 flows export.  *
07/Dec/2020 15:25:48 [nprobe.c:7194] ERROR: ***************************************************************
07/Dec/2020 15:25:48 [nprobe.c:4806] WARNING: The output interfaceId is set to 0: did you forget to use -Q perhaps ?
07/Dec/2020 15:25:48 [nprobe.c:4809] WARNING: The input interfaceId is set to 0: did you forget to use -u perhaps ?
07/Dec/2020 15:25:48 [nprobe.c:4909] Welcome to nProbe Pro v.7.3.160505 ($Revision: 5103 $) for x86_64-unknown-linux-gnu
07/Dec/2020 15:25:48 [nprobe.c:4919] Running on Ubuntu 14.04.4 LTS
07/Dec/2020 15:25:48 [nprobe.c:4930] [LICENSE] nProbe SystemId: D46ACA86499602D2
07/Dec/2020 15:25:48 [nprobe.c:7210] Welcome to nProbe v.7.3.160505 for x86_64-unknown-linux-gnu
07/Dec/2020 15:25:48 [plugin.c:1029] 0 plugin(s) enabled
07/Dec/2020 15:25:48 [nprobe.c:6766] Non IPv4/v6 traffic is discarded according to the template
07/Dec/2020 15:25:48 [nprobe.c:5419] Using packet capture length 128
07/Dec/2020 15:25:48 [nprobe.c:7383] IPv6 traffic will NOT be exported/accounted by this probe
07/Dec/2020 15:25:48 [nprobe.c:7384] due to configuration options (e.g. use NetFlow v9)
07/Dec/2020 15:25:48 [nprobe.c:7429] Flows ASs will not be computed (missing GeoIP support)
07/Dec/2020 15:25:48 [nprobe.c:7514] Capturing packets from interface eth0 [snaplen: 128 bytes]
07/Dec/2020 15:25:48 [util.c:4030] Initializing ZMQ as client
07/Dec/2020 15:25:48 [util.c:4049] Exporting flows towards ZMQ endpoint tcp://myserverfqdnremoved:5556
07/Dec/2020 15:25:48 [util.c:3123] nProbe changed user to 'nobody'
07/Dec/2020 15:25:48 [nprobe.c:7737] nProbe started successfully

If I run it with --verbose 2 I can see that it is collecting flows.  However, none of these ever arrive at the server (at least ntopng doesn't report on them).  My suspicion is therefore that ntopng is not "hearing" them from the router even though the router is theoretically sending them.

ntopng docker does not appear to be listening on port 5556.  I don't know how to make it listen on that port.  But then again it also doesn't appear to be listening on port 3000, yet it is serving the web interface through that port, so maybe it is actually listening on 5556 as well, and maybe it is just that we need to set the reverse proxy to handle it?
docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                                                NAMES
f56110abcbab        ntop/ntopng:stable        "/run.sh -i eth0"        20 hours ago        Up 20 hours                                                                              practical_jones

In the ports column for other docker containers running on this server it clearly lists the ports that are being monitored.

I'm running ntopng docker with this command:
sudo docker run -d -it -v /etc/ntopng.license:/etc/ntopng.license:ro --net=host ntop/ntopng:stable -i eth0

And the reverse proxy is configured like this using nginx:
# Upstream to Ntop frontend
proxy_next_upstream error timeout;
upstream ntop_web_interface {
    server localhost:3000 fail_timeout=0;
}

# Redirect everything to https
server {
    listen 80;
    server_name myserverfqdnremoved;
    return 301 https://myserverfqdnremoved$request_uri;
}

server {
    listen 443 ssl;
    server_name myserverfqdnremoved;

    # SSL certificate
  ssl_certificate     /etc/letsencrypt/live/mydomainremoved/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/mydomainremoved/privkey.pem;

    location / {
        proxy_pass_header Date;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host:$server_port;
        proxy_redirect off;
        proxy_set_header X_FORWARDED_PROTO $scheme;
        chunked_transfer_encoding off;
        proxy_pass http://ntop_web_interface;
    }
}

As you can see, there is no mention in the reverse proxy settings (that I found by googling setting up reverse proxy for ntopng) of anything for port 5556.  Do I need to setup a reverse proxy for port 5556?  Do you even encourage the use of docker or is your preferred installation for it to be directly installed on the server itself?

I'd appreciate any guidance you can give me as to where the problem might be.

Thanks,
Stephen

**Comment by simonemainardi** [comment]
1. Version difference is definitely a no-go. You won't get any result using an nprobe 7.3 in combination with an ntopng 4.0+.
2. Assuming you have aligned versions, you need to specify a ZMQ endpoint in ntopng `-i`, not eth0, e.g., `ntopng -i "tcp://myserverfqdnremoved:5556"`

**Comment by swilkey** [comment]
Thanks for the reply, sorry I don't understand your version comment as nprobe 7.3 IS greater than 4.0+, but I was talking about ntopng 9.3 (the current version).  My question about nprobe (in the other ticket) was is there a technical reason you've stopped providing nprobe at 7.3 or is it still possible to build a 9.3 nprobe for the edge router?

Thanks for the parameters to use.

**Comment by swilkey** [comment]
I thought about this more and I think you were saying that for any version higher than 3 we must always match the probe and the server, regardless of the version we are running all components must be at the same version.

With regard to the parameters though,  I want to clarify.  The documentation says:
nprobe --zmq-probe-mode --zmq "tcp://46.101.x.y:5556" -i eth1 -n none
ntopng -i "tcp://*:5556c"

When I first read this I thought, since it was talking about the probe, that it meant this:
nprobe --zmq-probe-mode --zmq "tcp://46.101.x.y:5556" -i eth1 -n none ntopng -i "tcp://*:5556c"
but that the formatting of the document had pushed ntopng -i "tcp://*:5556c" to the next line.

Now, in the light of your response, I believe although it was talking about nprobe it was actually telling you the instruction for ntopng as well.  With that conclusion I'm now puzzled because the documentation says that behind a firewall ("nProbe on a private network/IP, ntopng on a public network/IP protected by a firewall" - which is my situation) you have to run it with the "c" on the end, however, in your instruction you've recommended not running it with the c on the end.  So I'm confused whether I should have the c or not.  When I try without a c I can see that ntopng has an entry for eth0 and and entry for the remote network, but if I do it with a c there is no entry for the remote network, but the instructions tell me I'm supposed to use a c.  I'd appreciate your clarification.

Thanks again!

**Comment by simonemainardi** [comment]
1. if you use the `c`, ntopng acts as a `c`ollector, i.e., it listens for one - or multiple - connections from nProbe instances.
2. if you don't use the `c` it's the nProbe that listens for one - and only one - connection from an ntopng instance.

You can either use 1., or 2., they are equivalent in terms of having nProbe data inside ntopng. Choice between 1. or 2. may be determined by the presence of a firewall. Indeed, in 1., it is the nProbe that initiates the connection, whereas in 2., it is the ntopng.

If you have multiple nProbe that have IP-reachability of ntopng, you can do `ntopng -i tcp://*:5556` and then use the ntopng IP addresses on the nProbe as `nprobe --zmq tcp://<ntop ip address>:5556 --zmq-probe-mode`.

**Comment by swilkey** [comment]
Thanks very much Simone, that is a really helpful explanation. Have a great
day!
