### ISSUE TITLE
InfluxDB 2.0 support

### ISSUE THREAD

**Issue by mroe1234** [ntop/ntopng#4818]
As an experiment, I tried installing InfluxDB 2.0, the GUI reports the following error:

Incompatible InfluxDB version: required "1.5.1", found "nil". Please install an updated version from the official site.

Which is not all that surprising, I was wondering if this was on anyone's radar yet?

**Comment by simonemainardi** [comment]
As said in the preferences, influxdb 1.x is supported

![image](https://user-images.githubusercontent.com/3397663/101622882-e8d71280-3a17-11eb-948e-ed000b393eb3.png)


We are considering support for 2.x but this is still in progress 

https://github.com/ntop/ntopng/issues/3764
