### ISSUE TITLE
Collecting netflows

### ISSUE THREAD

**Issue by DrToxo** [ntop/ntopng#4820]
Can a server running ntopng receive netflows directly from routers, or is it not recommended to run nprobe and ntopng on the same box?  

Can netflows be received by ntopng without nprobe?

Cheers

**Comment by simonemainardi** [comment]
ntopng does not directly understands NetFlow. You need to go through nProbe. See https://www.ntop.org/nprobe/network-monitoring-101-a-beginners-guide-to-understanding-ntop-tools/
