### ISSUE TITLE
Issues sending flows to elasticsearch

### ISSUE THREAD

**Issue by NetworkSeb** [ntop/ntopng#4821]
Hi,

Thanks for the great product.

I'm trying to send flows from ntopng to elasticsearch (7.10) using the inbuilt Elasticsearch Endpoint (System > Endpoints)

I've configured the Endpoint to use authentication and set the URL, username and password.

Under Recipients I configure the Name and select the 'Elastic' endpoint. When I click 'Test recipient' I get the following error:

```
Cannot connect to Elasticsearch. [Response code: 401][Response: {"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}].
```

Which suggests to me that ntopng isn't using the credentials I specified in the Endpoint configuration.

I can access the elastic search via curl via the command line from the host the ntop box is installed on:

```
# curl -u xxx:xxx http://elastic:9200
{
  "name" : "196790a1ce1c",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "rzIh3pF_TdyXgwkVIDa6mA",
  "version" : {
    "number" : "7.10.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "51e9d6f22758d0374a0f3f5c6e8f3a7997850f96",
    "build_date" : "2020-11-09T21:30:33.964949Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

When I try to access elastic without using credentials, I get the same error as I do when pressing the 'Test Recipient' button in ntop:

```
# curl http://elastic:9200
{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}

```

At the moment, I'm working around the issue by setting the -F option in /etc/ntopng/ntopng.conf but it would be ace to have this all working in the GUI.

Thanks,

NWS

**Comment by simonemainardi** [comment]
-F is independent from the Elasticsearch endpoint. If you use -F you get Flows into elasticsearch. If you use the endpoint, you get alerts.

My guess is that there could be issues with an authenticated Elasticsearch when used as endpoint.

@MatteoBiscosi Can you please verify this? You should dnable Elasticsearch authentication (x-pack probably) and then configure an Endpoint.

**Comment by simonemainardi** [comment]
I've fixed an issue causing this issue to occur.

I've also tested against an authenticated ES and it works OK now.

New builds are in progress. Please, hold on a couple of hours, then update, and try again.

**Comment by NetworkSeb** [comment]
Thanks all working as expected now.

Thanks for the speedy response and fix!
