### ISSUE TITLE
Implement bandwidth monitoring

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4822]
ntopng with ctive monitorign supervises the latency. It is requested to add the ability to monitor the available bandwidth.

**Comment by simonemainardi** [comment]
Activity should be performed as follow:

1. Add a new `http_bandwidth.lua` measurement under scripts/plugins/monitors/network/active_monitoring/measurements. Look at how speedtest is implemented as the threshold for this bandwidth will be expressed in Mbps. Then look at how http is implemented as you'll have to divide the size of the fetched data by `total_time` to calculate the actual value in Mbps.
2. When adding/deleting an Infrastructure host, an http:// measure is added. Make sure to also add another a newly created http_bandwidth.lua. Comment the code until @lucaderi will give you the exact endpoint to use.
3. Add the measured bandwidth in the infrastructure table
