### ISSUE TITLE
Timeseries queries for top local talkers and top remote destinations

### ISSUE THREAD

**Issue by TimotheusBachinger** [ntop/ntopng#4823]
Hi ntopng!

This is a feature request regarding timeseries calls for retrieving top local talkers and top remote destinations as they are displayed on the traffic dashboard of ntopng (professional edition).

We would expect to behave similar to `lua/rest/v1/get/timeseries/ts.lua?ts_schema=top:iface:ndpi&ts_query=ifid:2&extended=1`, where we're receiving a topk list containing the top talkers and remote destinations ordered by their traffic. 

Best regards
Timi

**Comment by simonemainardi** [comment]
Issue can be done as follow:

- Look at how dashboard top local talkers and top remote destinations are currently populated
- Create two REST API endopoints `pro/scripts/lua/rest/v1/get/host/top/local/talkers.lua` and  `pro/scripts/lua/rest/v1/get/host/top/remote/talkers.lua` to implement a response that can be used to populate top local talkers and top remote destinations
- Slightly modify the current dashboard file to use the newly created REST API endpoints
- Update documentation at: `doc/src/api/rest/rest-api-v1.json`

**Comment by TimotheusBachinger** [comment]
Hi Simone, 

thanks for the proposal. Just a question as I am curious. We're fetching the top ndpi's via a call to ts.lua
lua/rest/v1/get/timeseries/ts.lua?ts_schema=top:iface:ndpi&ts_query=ifid:X
So I would have assumed, the query for the top talkers would also work via the timeseries API? Or is this needed as it will be pro-only feature?

Regards
Timi

**Comment by simonemainardi** [comment]
@TimotheusBachinger 

- This gives you LIVE top-talkers data, i.e., it's a picture of what's happening now
- ts.lua gives you historical TOP., i.e., it's a picture of the past

> So I would have assumed, the query for the top talkers would also work via the timeseries API? Or is this needed as it will be pro-only feature?

Yes, but for the past, e.g.,:

- rest/v1/get/timeseries/ts.lua?ts_compare=30m&epoch_begin=1607939100&ts_schema=top:local_receivers&ts_query=ifid:0&epoch_end=1607940900&initial_point=true&zoom=30m&limit=6

**Comment by TimotheusBachinger** [comment]
@simonemainardi: Ok sounds good, thanks for the clarification!

**Comment by simonemainardi** [comment]
Please, unify the code which is almost a 100% cut-and-paste. You should not commit 2 identical 100-line files that only differ in ONE line. Make this common code.


```
(base) Simones-MacBook-Pro:ntopng simone$
(base) Simones-MacBook-Pro:ntopng simone$ diff pro/scripts/lua/rest/v1/get/host/top/local/talkers.lua pro/scripts/lua/rest/v1/get/host/top/remote/talkers.lua
16c16
< -- Example: curl -u admin:admin -H "Content-Type: application/json" http://localhost:3000/lua/pro/rest/v1/get/host/top/local/talkers.lua
---
> -- Example: curl -u admin:admin -H "Content-Type: application/json" http://localhost:3000/lua/pro/rest/v1/get/host/top/remote/talkers.lua
45c45
< local hosts_retrv_function = interface.getLocalHostsInfo
---
> local hosts_retrv_function = interface.getRemoteHostsInfo
(base) Simones-MacBook-Pro:ntopng simone$ wc -l pro/scripts/lua/rest/v1/get/host/top/local/talkers.lua pro/scripts/lua/rest/v1/get/host/top/remote/talkers.lua
     100 pro/scripts/lua/rest/v1/get/host/top/local/talkers.lua
     100 pro/scripts/lua/rest/v1/get/host/top/remote/talkers.lua
     200 total
```

Moreover, I do not think all this boilerplate is needed

```

if((sortColumn == nil) or (sortColumn == "column_"))then
   sortColumn = getDefaultTableSort(sortPrefs)
else
   if((sortColumn ~= "column_")
      and (sortColumn ~= "")) then
      tablePreferences("sort_"..sortPrefs,sortColumn)
   end
end

if(sortOrder == nil) then
   sortOrder = getDefaultTableSortOrder(sortPrefs)
else
   if((sortColumn ~= "column_")
      and (sortColumn ~= "")) then
      tablePreferences("sort_order_"..sortPrefs,sortOrder)
   end
end
```

**Comment by simonemainardi** [comment]
OK. Now this makes sense. Please, backport (and test) changes to stable.

**Comment by simonemainardi** [comment]
This is implemented both in dev and stable.

See:

- lua/pro/rest/v1/get/host/top/local/talkers.lua
- lua/pro/rest/v1/get/host/top/remote/talkers.lua

And the docs available at https://www.ntop.org/guides/ntopng/api/rest/api_v1.html

A new stable build is in progress. Will be ready in ~1h.

**Comment by TimotheusBachinger** [comment]
Hi Simone,

just one question, shouldn't the call also have an `ifid` parameter as the top talkers dashbord in the ntopng UI looks like that the data will be different on multiple interfaces.

Regards

**Comment by simonemainardi** [comment]
@TimotheusBachinger thanks for pointing this out.

@MatteoBiscosi please add mandatory `ifid` param as well and make sure interface selection is performed.

**Comment by simonemainardi** [comment]
@TimotheusBachinger ifid has been added as mandatory param and doc has been updated accordingly. Changes available in the latest stable and dev. Thanks for pointing this out.
