### ISSUE TITLE
Need help - Ghost network detected

### ISSUE THREAD

**Issue by eliassal** [ntop/ntopng#4826]
I am getting an alert Ghost network detected, 192.168.0.0. (client is the machine running ntopng), I am not sure how to use this information to start investigation my network is 192.168.1.0. What is the tool to investigate if this is true?  I never use 192.168.0.0
![GostNetwork](https://user-images.githubusercontent.com/8447864/101897261-9417d100-3baa-11eb-811d-b4e25caf70ed.jpg)

**Comment by eliassal** [comment]
Clicking on the interface link, I see ipd addresse 192.168.1.19/32 , domain broadcast 192.168.0.0/20 !!! how come?
![GostNetworkNotLogic](https://user-images.githubusercontent.com/8447864/101897628-215b2580-3bab-11eb-87b9-7d270371704c.jpg)

clicking on the subnet 192.168.0.0/20 I get all hosts in this network whcih are 192.168.1.xxxxx, strange no?

![GostNetworkNotLogic1_002](https://user-images.githubusercontent.com/8447864/101897808-6b440b80-3bab-11eb-8876-1fbb3afe1d93.jpg)

**Comment by lucaderi** [comment]
Please check the IP address of your network intnerface and make sure its netmask is correct. As far as I can see this is the problem

**Comment by eliassal** [comment]
Where do you see this? THis is not true, please see snapshot from ntopng

![Networks](https://user-images.githubusercontent.com/8447864/102064754-003b4480-3df8-11eb-8918-39f6c61520cd.jpg)

**Comment by eliassal** [comment]
it is correct /24

**Comment by eliassal** [comment]
Why did you close it?
