### ISSUE TITLE
Unify ICMP and Continuous ICMP as you did with HTTP

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4827]
![Screen Shot 2020-12-11 at 18 10 15](https://user-images.githubusercontent.com/4493366/101933223-2f756a00-3bdc-11eb-8bc1-823f78eb6e45.png)

**Comment by simonemainardi** [comment]
I am not sure this should be done.

In ICMP and ICMPv6, you have the ability to specify a symbolic host name. If we unify those two guys, we no longer know if the symbolic name should be resolved as v4 or v6, unless we add an extra option/flag inside the add/edit modal.

This is why I did not unify them.

**Comment by lucaderi** [comment]
As agreed
- in case of numeric IPv4 or IPv6 addresses we'll use the corresponding protocol version
- in case of a symbolic address it will be resolved and used the available address. In case of ambiguity (IPv4 and IPv6) is the user that will specify the numeric IP

**Comment by simonemainardi** [comment]
done as requested in the referenced commits

![image](https://user-images.githubusercontent.com/3397663/103368271-6ea22700-4ac7-11eb-8043-acb461e8147f.png)
