### ISSUE TITLE
multipel interface issue

### ISSUE THREAD

**Issue by hemskgren** [ntop/ntopng#483]
Hi

I have the following in ntopng.conf running 2.3.160408 - Community Edition.
# 

--interface=tcp://127.0.0.1:5556(shared),
--interface=tcp://127.0.0.1:55005(1-px-pe01-wan),
--interface=tcp://127.0.0.1:55006(2-px-pe02-wan),
--interface=tcp://127.0.0.1:55007(1-p0-pe01),
--interface=tcp://127.0.0.1:55008(2-p0-pe02),
--interface=tcp://127.0.0.1:55009(1-p1-pe01),
--interface=tcp://127.0.0.1:55010(2-p1-pe02),
--interface=tcp://127.0.0.1:55011(1-p3-pe01),
--interface=tcp://127.0.0.1:55012(2-p3-pe02),
--interface=tcp://127.0.0.1:55013(tox1-px-pe01),
--interface=tcp://127.0.0.1:55014(tox2-px-pe02),
--interface=tcp://127.0.0.1:55015(del1-px-pe01),
--interface=tcp://127.0.0.1:55016(del2-px-pe02),
--interface=tcp://127.0.0.1:55017(kn5-px-pe01),
--interface=tcp://127.0.0.1:55018(kn7-px-pe01),
--interface=tcp://127.0.0.1:55023(dev1-px-pe01),
--interface=tcp://127.0.0.1:55024(dev1-px-pe02)
# 

And after selecting interface I get "The selected interface tcp://127.0.0.1:55013(tom1-px-pe01), [id: 9] is now active"  and later it change to "No packet has been received yet on interface tcp://127.0.0.1:55013(tox1-px-pe01),.
Please wait 2 seconds until this page reloads."  

issues
1, no traffic in dashbord (example above)
2, no interface historical traffic graf but "top talker" works. (/lua/if_stats.lua?id=9&page=historical)
3, no interface traffic breakdown or Received Traffic. (/lua/if_stats.lua?id=9&page=overview)

Regards
Christer

**Comment by simonemainardi** [comment]
make sure there is an nProbe exporting flows (`nprobe --zmq tcp://127.0.0.1:55013`) on localhost port 55013

**Comment by hemskgren** [comment]
Hi

The flow tab works and show the traffic.
The reported stuff do not work for me with multiple interface with , after each.

Regards 
Christer

**Comment by hemskgren** [comment]
update

This morning it looks better (uptime 16h). It is only  the following have the same issue.
2, no interface historical traffic graf but "top talker" works. (/lua/if_stats.lua?id=9&page=historical)

after a fist reload of ntopng it was the same, only 2 did not work as well (uptime 5-10 min).
after second reload of ntopng it was issue with 1, 2, and 3 above (uptime 5min).

Regards
Christer

**Comment by simonemainardi** [comment]
I am not sure to understand your issue. Please enclose screenshots.

**Comment by simonemainardi** [comment]
@hemskgren any news?

**Comment by hemskgren** [comment]
Hi

First i have now updated to ntopng x86_64 v.2.3.160419  and removed my "comment" > (ix-pe01) behind the interface in the configuration.

This is still the same on all pages.
![image](https://cloud.githubusercontent.com/assets/10794918/14631875/dbc3fb16-0615-11e6-9f32-4862fdcc8488.png)

and this is still the same on interface -> history page. a traffic spike can sometime show. but no graf. 
![image](https://cloud.githubusercontent.com/assets/10794918/14632001/8af2ceb4-0616-11e6-958a-f713fe21d3aa.png)

As i have use only one interface earlier i try to disable all interface in configuration except one. 
And it is the same issue as above but get a more stable feeling.

regards
Christer

**Comment by simonemainardi** [comment]
please make sure to specify local networks with ntopng command `-m`

**Comment by hemskgren** [comment]
changing from --local-networks=" net xx"  to -m "net xx" didn't do any differences..

**Comment by simonemainardi** [comment]
`--local-networks` accepts CIDR notation not BPF, e.g., `-m"192.168.1.0/24"`

**Comment by hemskgren** [comment]
yes 

-m "192.168.0.0/16,10.0.0.0/8,10.32.0.0/16,10.34.0.0/16,10.36.0.0/14,10.40.0.0/15,10.46.0.0/16,10.52.0.0/16,10.53.0.0/16,10.53.100.0/22,10.58.0.0/16,10.127.0.0/16,10.163.0.0/16,172.16.0.0/12"

**Comment by simonemainardi** [comment]
I think this may be the same limitation as discussed in https://github.com/ntop/ntopng/issues/470 

can you comment on this @lucaderi ? Thank you.

**Comment by lucaderi** [comment]
@hemskgren Are you using the latest nprobe? If not please do. Using so many interfaces isn't a good practice: please read http://www.ntop.org/nprobe/advanced-flow-collection-with-ntopng-and-nprobe/
@simonemainardi I don't see what -m and #470 have to do with this issue.

**Comment by hemskgren** [comment]
Hi

can be thru but this is a excellent setup for my network.

I deleted all statistics. 
rm -rf /var/tmp/ntopng/
redis-cli
FLUSHALL
FLUSHB

started nprobe with -I  on one nprobe reciving ipfix.
restarted ntopng and the both issue was temporary gone!!! on that "interface"

after some time i did the same on next nprobe with -I  and restarted ntopng and the statistics problem was back.

**Comment by hemskgren** [comment]
[root@ix-netflow01-px ~]# nprobe -v

Welcome to nProbe v.7.3.160419 (r5042) for x86_64-unknown-linux-gnu
with native PF_RING acceleration.
Copyright 2002-16 ntop.org

Build OS:      CentOS Linux release 7.1.1503 (Core)
SystemID:      689677AB82072B1

**Comment by simonemainardi** [comment]
the latest dev versions of nprobe and ntopng contains enhancements that address your issue

Commits are:
- https://github.com/ntop/ntopng/commit/8a69147ddacba5e715e026d1af6401b990345727
- https://github.com/ntop/ntopng/commit/89ea597be36075ffcbbd52ecfd2e89fd8f7efad0

Please upgrade software to the latest nightly builds.
