### ISSUE TITLE
Errors no erros strange messages

### ISSUE THREAD

**Issue by eliassal** [ntop/ntopng#4831]
Can ypu please let me know what those messages mean and why are they generated. I am a little bit confused, saying sending error the no error, also no details of the error

![errorNoerror](https://user-images.githubusercontent.com/8447864/102079782-93cb4000-3e0d-11eb-8c96-28e6b8778540.jpg)

**Comment by eliassal** [comment]
After clicking on the triangle with exclamation symbol I landed on the following page which seems it is a bug
![errorNoerror_Bug](https://user-images.githubusercontent.com/8447864/102079935-de4cbc80-3e0d-11eb-97b5-410ce87c7f0c.jpg)

**Comment by lucaderi** [comment]
Log fixed by f8e12264f0991ec5e71066b522967c275033df67

**Comment by eliassal** [comment]
Thanks Luca, what should I do now to fix it in my environment? should download a file or wait for a new version? Thanks again
