### ISSUE TITLE
NTOP flows to Elasticsearch

### ISSUE THREAD

**Issue by NetworkSeb** [ntop/ntopng#4833]
Hi,

More of a question than an issue, I hope this is the right place for this.

I have ntopng sending flows to elasticsearch using the -F option:

-F="es;flows;ntopng-%Y.%m.%d;http://elastic:9200/_bulk;username:password"

I am seeing lots of flows into elasticsearch however I am seeing lots of 'Export drops' and I get the following errors in ntop:

[ElasticSearch.cpp:175] ERROR ES: POST request for 1418 flows (1048689 bytes) failed

![image](https://user-images.githubusercontent.com/4477783/102102101-5671ad00-3e23-11eb-9932-066459037ba6.png)

and the following in elasticsearch:

```
{"type": "server", "timestamp": "2020-12-14T08:51:27,906Z", "level": "INFO", "component": "o.e.a.b.TransportShardBulkAction", "cluster.name": "docker-cluster", "node.name": "196790a1ce1c", "message": "[ntopng-2020.12.14][0] mapping update rejected by primary", "cluster.uuid": "rzIh3pF_TdyXgwkVIDa6mA", "node.id": "-w3lZ4v8Si2CaAo3Oh034Q" , 
"stacktrace": ["java.lang.IllegalArgumentException: Mapper for [OUT_DST_MAC] conflicts with existing mapper:",
"Cannot update parameter [norms] from [false] to [true]",
"at org.elasticsearch.index.mapper.ParametrizedFieldMapper$Conflicts.check(ParametrizedFieldMapper.java:496) ~[elasticsearch-7.10.0.jar:7.10.0]",
"at org.elasticsearch.index.mapper.ParametrizedFieldMapper.merge(ParametrizedFieldMapper.java:103) ~[elasticsearch-7.10.0.jar:7.10.0]",
"at org.elasticsearch.index.mapper.ParametrizedFieldMapper.merge(ParametrizedFieldMapper.java:61) ~[elasticsearch-7.10.0.jar:7.10.0]",
"at org.elasticsearch.index.mapper.ObjectMapper.doMerge(ObjectMapper.java:535) ~[elasticsearch-7.10.0.jar:7.10.0]",
"at org.elasticsearch.index.mapper.RootObjectMapper.doMerge(RootObjectMapper.java:298) ~[elasticsearch-7.10.0.jar:7.10.0]",
"at org.elasticsearch.index.mapper.ObjectMapper.merge(ObjectMapper.java:495) ~[elasticsearch-7.10.0.jar:7.10.0]",
"at org.elasticsearch.index.mapper.RootObjectMapper.merge(RootObjectMapper.java:293) ~[elasticsearch-7.10.0.jar:7.10.0]",
"at org.elasticsearch.index.mapper.Mapping.merge(Mapping.java:110) ~[elasticsearch-7.10.0.jar:7.10.0]",
"at org.elasticsearch.index.mapper.DocumentMapper.merge(DocumentMapper.java:281) ~[elasticsearch-7.10.0.jar:7.10.0]",
"at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:470) ~[elasticsearch-7.10.0.jar:7.10.0]",
"at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:421) ~[elasticsearch-7.10.0.jar:7.10.0]",
"at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:361) ~[elasticsearch-7.10.0.jar:7.10.0]",
"at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:292) [elasticsearch-7.10.0.jar:7.10.0]",
"at org.elasticsearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:175) [elasticsearch-7.10.0.jar:7.10.0]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.10.0.jar:7.10.0]",
"at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:220) [elasticsearch-7.10.0.jar:7.10.0]",
"at org.elasticsearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:126) [elasticsearch-7.10.0.jar:7.10.0]",
"at org.elasticsearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:85) [elasticsearch-7.10.0.jar:7.10.0]",
"at org.elasticsearch.action.support.replication.TransportWriteAction$1.doRun(TransportWriteAction.java:179) [elasticsearch-7.10.0.jar:7.10.0]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:737) [elasticsearch-7.10.0.jar:7.10.0]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.10.0.jar:7.10.0]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]",
"at java.lang.Thread.run(Thread.java:832) [?:?]"] }
```
Is there anything I have to do interms of index mapping in elasticsearch to get this to work? Apologies for the question here, unsure if the issue is in attribute mapping in elastic or in the flows being passed from ntopng!

**Comment by simonemainardi** [comment]
- You have 97k flow drops, you should compare them with the total number of exported flows. It seems you're in an high-speed environment (half Gbps) so a small fraction of drops may be normal (elasticsearch could not have been able to receive a bulk fro example)
- As per `Mapper for [OUT_DST_MAC] conflicts with existing mapper`, We do not define any mapper for `OUT_DST_MAC`, so my guess is: did you play with mappings manually? ntopng pushes a mapping automatically for its indices.

**Comment by NetworkSeb** [comment]
Hi Simone,

Thanks for the pointers, I've not edited the mappings manually, to make sure I've deleted the index template and index and restarted ntopng (so it pushed the template again).

I've checked under Exported vs Dropped flows and this is the graph it gives me:

![image](https://user-images.githubusercontent.com/4477783/102502583-b744f380-4076-11eb-84fd-956948cf5ee9.png)

I restated ntopng @ 14:36.

Do you think it would be worth trying to export the flows from ntop into elk via Logstash as per your YouTube video instead?

**Comment by NetworkSeb** [comment]
Just for information, I've taken some further steps in my debugging:

I've completely rebuilt my elastic stack to see if that was causing any issues.
I've also tried to get the information into elasticsearch via logstash by following the README.logstash in the docs, which was also unsuccessful.

The ELK stack I'm using is currently running 7.10 of the ELK stack - could this be the issue?

**Comment by NetworkSeb** [comment]
I've taken to loading NTOP in the foreground to get more information:

After removing the ntopng_template index template in elastic and restarting Ntopng  I get the following:

`22/Dec/2020 20:28:04 [ElasticSearch.cpp:315] ERROR: Unable to send ntopng template (/usr/share/ntopng/httpdocs/misc/ntopng_template_elk.json) to ES`

Even though the error is produced, checking in Elastic afterwards, there is a indices template called ntopng_template

**Comment by simonemainardi** [comment]
I am using an authenticated 7.10 too and it is working properly with ntopng 4.3:


```
simone@devel:~/ntopng$ curl -u elastic:elastic -XGET 'http://localhost:9200'
{
  "name" : "devel",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "9x561L1iTz6GPnCFON-rrQ",
  "version" : {
    "number" : "7.10.0",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "51e9d6f22758d0374a0f3f5c6e8f3a7997850f96",
    "build_date" : "2020-11-09T21:30:33.964949Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

I can reproduce if I deliberately set a wrong username/password pair, so maybe this is the issue. Can you please check this? Maybe I can see if I can print an error.

**Comment by saberph** [comment]
We have the same issue. 

Dec 27 21:26:55 ntopng[1347170]: 27/Dec/2020 21:26:55 [ElasticSearch.cpp:175] ERROR: ES: POST request for 2138 flows (1048616 bytes) failed
Dec 27 21:26:56 ntopng[1347170]: [ElasticSearch.cpp:175] ERROR: ES: POST request for 2144 flows (1048599 bytes) failed
Dec 27 21:26:56 ntopng[1347170]: 27/Dec/2020 21:26:56 [ElasticSearch.cpp:175] ERROR: ES: POST request for 2144 flows (1048599 bytes) failed
Dec 27 21:26:57 ntopng[1347170]: [ElasticSearch.cpp:175] ERROR: ES: POST request for 2128 flows (1048610 bytes) failed
Dec 27 21:26:57 ntopng[1347170]: 27/Dec/2020 21:26:57 [ElasticSearch.cpp:175] ERROR: ES: POST request for 2128 flows (1048610 bytes) failed
Dec 27 21:26:58 ntopng[1347170]: [ElasticSearch.cpp:175] ERROR: ES: POST request for 2129 flows (1048986 bytes) failed
Dec 27 21:26:58 ntopng[1347170]: 27/Dec/2020 21:26:58 [ElasticSearch.cpp:175] ERROR: ES: POST request for 2129 flows (1048986 bytes) failed
Dec 27 21:26:59 ntopng[1347170]: [ElasticSearch.cpp:175] ERROR: ES: POST request for 2121 flows (1048963 bytes) failed
Dec 27 21:26:59 ntopng[1347170]: 27/Dec/2020 21:26:59 [ElasticSearch.cpp:175] ERROR: ES: POST request for 2121 flows (1048963 bytes) failed
Dec 27 21:27:00 ntopng[1347170]: [ElasticSearch.cpp:175] ERROR: ES: POST request for 2120 flows (1048905 bytes) failed
Dec 27 21:27:00 ntopng[1347170]: 27/Dec/2020 21:27:00 [ElasticSearch.cpp:175] ERROR: ES: POST request for 2120 flows (1048905 bytes) failed
Dec 27 21:27:01 ntopng[1347170]: [ElasticSearch.cpp:69] WARNING: [ES] Export queue too long [32768]: expect drops
Dec 27 21:27:01 ntopng[1347170]: 27/Dec/2020 21:27:01 [ElasticSearch.cpp:69] WARNING: [ES] Export queue too long [32768]: expect drops
Dec 27 21:27:01 ntopng[1347170]: [ElasticSearch.cpp:175] ERROR: ES: POST request for 2113 flows (1048819 bytes) failed
Dec 27 21:27:01 ntopng[1347170]: 27/Dec/2020 21:27:01 [ElasticSearch.cpp:175] ERROR: ES: POST request for 2113 flows (1048819 bytes) failed
Dec 27 21:27:02 ntopng[1347170]: [ElasticSearch.cpp:175] ERROR: ES: POST request for 2118 flows (1048725 bytes) failed
Dec 27 21:27:02 ntopng[1347170]: 27/Dec/2020 21:27:02 [ElasticSearch.cpp:175] ERROR: ES: POST request for 2118 flows (1048725 bytes) failed
Dec 27 21:27:03 ntopng[1347170]: [ElasticSearch.cpp:175] ERROR: ES: POST request for 2116 flows (1048909 bytes) failed
Dec 27 21:27:03 ntopng[1347170]: 27/Dec/2020 21:27:03 [ElasticSearch.cpp:175] ERROR: ES: POST request for 2116 flows (1048909 bytes) failed

We hit the following errors at around 1 Gbps. 

elasticsearch-7.10.1-1.x86_64
ntopng-4.2.201222-11580.x86_64

**Comment by lucaderi** [comment]
@saberph Can you please report the error message triggered by https://github.com/ntop/ntopng/blob/dev/src/Utils.cpp#L1593 and eventually start ntopng on shell to better see what is going on

**Comment by saberph** [comment]
@lucaderi Tried to the verbose level 6 (debug), I got no trace regarding ES post errors. Weird.

Same on /lua/system_stats.lua (Last log trace).

**Comment by lucaderi** [comment]
@saberph I have added new traces (they are in the dev version, no stable) in the code: new packages will be built in one hour. Before answering you I need to nail down the problem. Please update and let us know

**Comment by saberph** [comment]
@lucaderi  Thanks for the prompt answer. Unfortunately it's a production server, I can't simply run a dev package on it.

I will try to setup a test server to try it out soon.

**Comment by NetworkSeb** [comment]
HI All,

After much fiddling I think I might have found the issue (for me at least).

I was calling ntopng (whilst debugging) as follows:

`ntopng -F "es;ntopng;ntopng-%Y.%m.%d;http://elastic:9200/_bulk;user:pass" -v 6`

This was generating errors such as:

`30/Dec/2020 14:22:34 [Utils.cpp:1289] [JSON] ,"_type":"ntopng","_id":"bewHtHYBz4oKDFqrUkSX","status":400,"error":{"type":"illegal_argument_exception","reason":"Rejecting mapping update to [ntopng-2020.12.30] as the final mapping would have more than 1 type: [_doc, ntopng]"}}}`

It appears this was also causing the mapping errors I was seeing.

changing ntopng under 'type' to _doc seems to resolved my issues:

I'm now calling ntopng with the -F option as follows:

`ntopng -F "es;_doc;ntopng-%Y.%m.%d;http://elastic:9200/_bulk;user:pass"`

Thanks for your time and help with this one!

**Comment by simonemainardi** [comment]
@NetworkSeb I may have solved

```
22/Dec/2020 20:28:04 [ElasticSearch.cpp:315] ERROR: Unable to send ntopng template (/usr/share/ntopng/httpdocs/misc/ntopng_template_elk.json) to ES
```

Due to a wrong ES version initialization

**Comment by NetworkSeb** [comment]
Thanks @simonemainardi is that live in the packages? If so I can let you know if I get the same results.

I also noted that only get the previous errors with the bulk export when calling ntopng with -X/-x without the export to ES works perfectly, so I've just removed options in the ntopng.conf and everything is working as it should!

**Comment by simonemainardi** [comment]
> Thanks @simonemainardi is that live in the packages? If so I can let you know if I get the same results.

correct
