### ISSUE TITLE
MSVCP120.dll not found quando installo l'ultima versione di ntopng ntopng-4.3.201103-x64

### ISSUE THREAD

**Issue by daxrob** [ntop/ntopng#4834]
Ciao,

sto provando ad installare ntopng 4.3.2 appena scaricata su un PC Win 10 Pro.
Ho seguito l'installazione e installato Win10Pcap,  Visual C++ e Redis.
Quando conclude l'installazione, compare una finestra nera e un messaggio di errore:
ntopng.exe - System error: The code execution cannot proceed because MSVCP120.dll was not found
Ho già provato a disinstallare tutto, riavviare e installare Win10Pcap prima, ma non cambia nulla.
Qualche idea?

Grazie.
Roberto

**Comment by lucaderi** [comment]
Can you please download https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads and see if it fixes the problem

**Comment by daxrob** [comment]
Hi,

which version? 2015, 2017 and 2019, 2013, 2012 ...
I now installed 2103, 2008 and 2015-2019 and it seems to work fine.

Regards
Roberto
