### ISSUE TITLE
ntopng installed from official macOS package: multiple "dyld: Library not loaded: ..."

### ISSUE THREAD

**Issue by vollkommenheit** [ntop/ntopng#4837]
1)
`# ntopng`
> dyld: Library not loaded: /usr/local/Cellar/glib/2.66.1/lib/libgmodule-2.0.0.dylib
  Referenced from: /usr/local/opt/ntopng//libgio-2.0.0.dylib
  Reason: image not found
/usr/local/bin/ntopng: line 6: 48642 Trace/BPT trap: 5       /usr/local/bin/ntopng-bin $@

`# otool -L /usr/local/opt/ntopng//libgio-2.0.0.dylib`
> /usr/local/opt/ntopng//libgio-2.0.0.dylib:
	/usr/local/opt/glib/lib/libgio-2.0.0.dylib (compatibility version 6601.0.0, current version 6601.1.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1455.122.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1455.122.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1561.61.100)
	/usr/local/Cellar/glib/2.66.1/lib/libglib-2.0.0.dylib (compatibility version 6601.0.0, current version 6601.1.0)
	/usr/local/Cellar/glib/2.66.1/lib/libgobject-2.0.0.dylib (compatibility version 6601.0.0, current version 6601.1.0)
	/usr/local/Cellar/glib/2.66.1/lib/libgmodule-2.0.0.dylib (compatibility version 6601.0.0, current version 6601.1.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 11.0.0, current version 11.0.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 822.37.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)

`# find /usr/local -iname glib`

`# brew info glib`
> glib: stable 2.66.2
Core application library for C
https://developer.gnome.org/glib/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/glib.rb
License: LGPL-2.1-or-later
==> Dependencies
Build: meson 饪?, ninja 饪?, pkg-config 饪?
Required: gettext 饪?, libffi 饪?, pcre 饪?, python@3.9 饪?

2)
`# /usr/local/bin/ntopng-bin`
> dyld: Library not loaded: /usr/local/opt/rrdtool/lib/librrd.8.dylib
  Referenced from: /usr/local/bin/ntopng-bin
  Reason: image not found
Trace/BPT trap: 5

`# otool -L $(which ntopng-bin)`
> /usr/local/bin/ntopng-bin:
	/usr/lib/libpcap.A.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/rrdtool/lib/librrd.8.dylib (compatibility version 11.0.0, current version 11.1.0)
	/usr/local/opt/json-c/lib/libjson-c.4.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/local/opt/libmaxminddb/lib/libmaxminddb.0.dylib (compatibility version 1.0.0, current version 1.7.0)
	/usr/local/opt/libsodium/lib/libsodium.23.dylib (compatibility version 27.0.0, current version 27.0.0)
	/usr/lib/libsqlite3.dylib (compatibility version 9.0.0, current version 274.8.1)
	/usr/local/opt/mysql/lib/libmysqlclient.21.dylib (compatibility version 21.0.0, current version 21.0.0)
	/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libexpat.1.dylib (compatibility version 7.0.0, current version 8.0.0)
	/usr/local/opt/libgcrypt/lib/libgcrypt.20.dylib (compatibility version 23.0.0, current version 23.5.0)
	/System/Library/Frameworks/LDAP.framework/Versions/A/LDAP (compatibility version 1.0.0, current version 2.4.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 9.0.0)
	/usr/local/opt/zstd/lib/libzstd.1.dylib (compatibility version 1.0.0, current version 1.4.4)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)

**Comment by vollkommenheit** [comment]
In /usr/local/bin/ntopng, replacing the default
`export DYLD_LIBRARY_PATH=/usr/local/opt/ntopng/:$DYLD_LIBRARY_PATH`
with either:
`export LDFLAGS="-L/usr/local/opt/ntopng/"`
or
`export LD_LIBRARY_PATH=/usr/local/opt/ntopng/:$LD_LIBRARY_PATH`
gets past the
> dyld: Library not loaded: /usr/local/Cellar/glib/2.66.1/lib/libgmodule-2.0.0.dylib 
> 
issue.

However, now $ ntopng directly goes to the 2nd error above: 
> dyld: Library not loaded: /usr/local/opt/rrdtool/lib/librrd.8.dylib
  Referenced from: /usr/local/bin/ntopng-bin
  Reason: image not found
/usr/local/bin/ntopng: line 8: 53306 Trace/BPT trap: 5       /usr/local/bin/ntopng-bin $@

`# ls -al /usr/local/opt/rrdtool/lib/librrd.8.dylib`
> ls: /usr/local/opt/rrdtool/lib/librrd.8.dylib: No such file or directory

`ls -al /usr/local/opt/ntopng/`
> total 40456
drwxr-xr-x  29 root            wheel      986 Dec 16 18:34 .
drwxr-xr-x  48 myuid  admin     1632 Dec 16 16:05 ..
-rw-r--r--   1 root            wheel   888344 Nov  4 18:13 libcairo.2.dylib
-r--r--r--   1 root            wheel  2425716 Nov  4 18:13 libcrypto.1.1.dylib
-r--r--r--   1 root            wheel    34180 Nov  4 18:13 libffi.7.dylib
-r--r--r--   1 root            wheel   242892 Nov  4 18:13 libfontconfig.1.dylib
-r--r--r--   1 root            wheel   626748 Nov  4 18:13 libfreetype.6.dylib
-r--r--r--   1 root            wheel   111524 Nov  4 18:13 libfribidi.0.dylib
-rw-r--r--   1 root            wheel   717972 Nov  4 18:13 libgcrypt.20.dylib
-r--r--r--   1 root            wheel  1809204 Nov  4 18:13 libgio-2.0.0.dylib
-rw-r--r--   1 root            wheel  1211392 Nov  4 18:13 libglib-2.0.0.dylib
-r--r--r--   1 root            wheel   319624 Nov  4 18:13 libgobject-2.0.0.dylib
-r--r--r--   1 root            wheel   116092 Nov  4 18:13 libgpg-error.0.dylib
-rw-r--r--   1 root            wheel   120388 Nov  4 18:13 libgraphite2.3.dylib
-rw-r--r--   1 root            wheel  1040764 Nov  4 18:13 libharfbuzz.0.dylib
-r--r--r--   1 root            wheel    55000 Nov  4 18:13 libintl.8.dylib
-r--r--r--   1 root            wheel    48892 Nov  4 18:13 libjson-c.4.dylib
-rw-r--r--   1 root            wheel    23252 Nov  4 18:13 libmaxminddb.0.dylib
-rw-r--r--   1 root            wheel  7298404 Nov  4 18:13 libmysqlclient.21.dylib
-rw-r--r--   1 root            wheel   329076 Nov  4 18:13 libpango-1.0.0.dylib
-r--r--r--   1 root            wheel   107160 Nov  4 18:13 libpangocairo-1.0.0.dylib
-rw-r--r--   1 root            wheel    96180 Nov  4 18:13 libpangoft2-1.0.0.dylib
-rw-r--r--   1 root            wheel   452592 Nov  4 18:13 libpcre.1.dylib
-rw-r--r--   1 root            wheel   593920 Nov  4 18:13 libpixman-1.0.dylib
-rw-r--r--   1 root            wheel   173244 Nov  4 18:13 libpng16.16.dylib
-r--r--r--   1 root            wheel   317388 Nov  4 18:13 librrd.8.dylib
-r--r--r--   1 root            wheel   323556 Nov  4 18:13 libsodium.23.dylib
-r--r--r--   1 root            wheel   490796 Nov  4 18:13 libssl.1.1.dylib
-rw-r--r--   1 root            wheel   681120 Nov  4 18:13 libzstd.1.dylib

**Comment by simonemainardi** [comment]
can you please check out official mac package at https://packages.ntop.org/

**Comment by vollkommenheit** [comment]
> can you please check out official mac package at https://packages.ntop.org/

I was running the official macOS package from ntop.org. 

Just in case, I have re-downloaded the latest package (https://packages.ntop.org/MacOS/ntopng-4.3.201102.pkg) and re-installed it again, with the same results:

`# ntopng`
> dyld: Library not loaded: /usr/local/Cellar/glib/2.66.1/lib/libgmodule-2.0.0.dylib
  Referenced from: /usr/local/opt/ntopng//libgio-2.0.0.dylib
  Reason: image not found
/usr/local/bin/ntopng: line 6: 94680 Trace/BPT trap: 5       /usr/local/bin/ntopng-bin $@

**Comment by cardigliano** [comment]
@vollkommenheit latest official build seems to be working on my Mac, what macOS version are you running?

% ntopng -V
v.4.3.201102	[Enterprise/Professional build]
GIT rev:	dev:f4495ed1262a3864b794bbb464227015646785f8:20201102
Pro rev:	r3324
Built on:	MacOSX 10.13.6
Platform:	x86_64

% brew info glib
glib: stable 2.66.2 (bottled)
Core application library for C
https://developer.gnome.org/glib/
/usr/local/Cellar/glib/2.66.2_1 (436 files, 15.5MB) *
  Poured from bottle on 2020-10-30 at 12:43:34
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/glib.rb
License: LGPL-2.1-or-later
==> Dependencies
Build: meson ✔, ninja ✔, pkg-config ✔
Required: gettext ✔, libffi ✔, pcre ✔, python@3.9 ✔
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Analytics
install: 275,595 (30 days), 1,030,635 (90 days), 3,849,490 (365 days)
install-on-request: 57,745 (30 days), 228,257 (90 days), 537,249 (365 days)
build-error: 0 (30 days)

% otool -L $(which ntopng-bin)
/usr/local/bin/ntopng-bin:
	/usr/lib/libpcap.A.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/rrdtool/lib/librrd.8.dylib (compatibility version 11.0.0, current version 11.1.0)
	/usr/local/opt/json-c/lib/libjson-c.4.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/local/opt/libmaxminddb/lib/libmaxminddb.0.dylib (compatibility version 1.0.0, current version 1.7.0)
	/usr/local/opt/libsodium/lib/libsodium.23.dylib (compatibility version 27.0.0, current version 27.0.0)
	/usr/lib/libsqlite3.dylib (compatibility version 9.0.0, current version 274.8.1)
	/usr/local/opt/mysql/lib/libmysqlclient.21.dylib (compatibility version 21.0.0, current version 21.0.0)
	/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libexpat.1.dylib (compatibility version 7.0.0, current version 8.0.0)
	/usr/local/opt/libgcrypt/lib/libgcrypt.20.dylib (compatibility version 23.0.0, current version 23.5.0)
	/System/Library/Frameworks/LDAP.framework/Versions/A/LDAP (compatibility version 1.0.0, current version 2.4.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 9.0.0)
	/usr/local/opt/zstd/lib/libzstd.1.dylib (compatibility version 1.0.0, current version 1.4.4)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)

**Comment by vollkommenheit** [comment]
@cardigliano, I'm on 10.11. Since ntopng comes with all the dylibs it needs (glib, librrd, etc.), in /usr/local/opt/ntopng/, it seems just a matter of pointing it to look in that directory. For some reason, it doesn't work on 10.11 using "export DYLD_LIBRARY_PATH=/usr/local/opt/ntopng/:$DYLD_LIBRARY_PATH" in ntopng (a Bash script) and whatever the ntopng-bin binary has though.

**Comment by cardigliano** [comment]
@vollkommenheit weird this is not working for you, it works like a charm for me. Could you check what happens with DYLD_FALLBACK_LIBRARY_PATH in place of DYLD_LIBRARY_PATH ?

**Comment by vollkommenheit** [comment]
@cardigliano I get the same outcome with `DYLD_FALLBACK_LIBRARY_PATH` as `DYLD_LIBRARY_PATH.`  As noted in my second post above, on my 10.11 installation, using either `LDFLAGS="-L/usr/local/opt/ntopng/"` or `export LD_LIBRARY_PATH="/usr/local/opt/ntopng/"` gets ntopng (the Bash script) to look in the correct place: `/usr/local/opt/ntopng/` although the underlying ntopng-bin still does not.

Given the apparent difference in how 10.11 El Capitan (and likely 10.12 Sierra) versus 10.13 High Sierra deals with DYLD_LIBRARY_PATH, I put the following in ntopng, but how do I modify  ntopbin-bin?

`OSX_VER=$(/usr/bin/defaults read "$3/System/Library/CoreServices/SystemVersion" ProductVersion)`
`OSX_VER_MINOR=$(echo ${OSX_VER} | awk -F'.' '{print $2}')`

`if [[ ${OSX_VER_MINOR} -ge 13 ]]; then`
        `export DYLD_LIBRARY_PATH=/usr/local/opt/ntopng/:$DYLD_LIBRARY_PATH`
`else`
        `export LD_LIBRARY_PATH=/usr/local/opt/ntopng/:$LD_LIBRARY_PATH`
`fi`

**Comment by cardigliano** [comment]
@vollkommenheit how do you want to modify ntopng-bin? The loader should handle those env variables, not ntopng itself.. if you think they are just ignored by the loader, we should figure out why

**Comment by vollkommenheit** [comment]
@cardigliano, so how to diagnose this? The following two threads seem to be concerning the same issue, but I'm not seeing an obvious solution or workaround, other than sym-linking to `/usr/local/opt/ntopng/` which is a band aid:

https://stackoverflow.com/questions/3146274/is-it-ok-to-use-dyld-library-path-on-mac-os-x-and-whats-the-dynamic-library-s

https://github.com/nteract/nteract/issues/1523

For ntopng-bin, is the following bit from https://medium.com/macos-is-not-linux-and-other-nix-reflections/d-o-y-ou-ld-library-path-you-6ab0a6135a33 relevant concerning this 10.11 snag?

"(Note the -L flag in compiler commands will add new library search paths during the linking stage of a compiler command)"

And, this later bit might be why 10.13 behaves differently from (more securely than?) 10.11?
"What is ironic that at some point time (around 2017), Apple played a studious security company role and disabled these environment variables via SIP. Maybe it broke too much existing software where the shoddy software of the many outweighed the solid software of the few?"

**Comment by vollkommenheit** [comment]
`export RPATH=/usr/local/opt/ntopng/:$RPATH` also gets ntopng (but not ntopng-bin) to look inside /usr/local/opt/ntopng/ on 10.11, so maybe this is more desirable than using "LD_LIBRARY_PAHT" or "LDFLAGS" or "DYLD_LIBRARY_PATH"?

**Comment by vollkommenheit** [comment]
Maybe this will do, for ntopng-bin?
https://github.com/BVLC/caffe/issues/3227#issuecomment-167540070

**Comment by swingdancer** [comment]
similar issue happening here with  https://packages.ntop.org/MacOS/ntopng-4.3.201102.pkg

```
$ /usr/local/bin/ntopng /usr/local/etc/ntopng/ntopng.conf
dyld: Library not loaded: /usr/local/Cellar/glib/2.66.1/lib/libgmodule-2.0.0.dylib
  Referenced from: /usr/local/opt/ntopng//libgio-2.0.0.dylib
  Reason: Incompatible library version: libgio-2.0.0.dylib requires version 6601.0.0 or later, but libgmodule-2.0.0.dylib provides version 3601.0.0
/usr/local/bin/ntopng: line 6: 34178 Abort trap: 6           /usr/local/bin/ntopng-bin $@
```

running 

![image](https://user-images.githubusercontent.com/36482442/104516783-2cafcf80-55f5-11eb-87a8-4fff4ed77312.png)

```
$ brew info glib
glib: stable 2.66.4 (bottled)
Core application library for C
https://developer.gnome.org/glib/
/usr/local/Cellar/glib/2.36.3 (415 files, 15.2MB)
  Built from source on 2013-07-14 at 03:47:43
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/glib.rb
```

**Comment by cardigliano** [comment]
@vollkommenheit what do you mean with "gets ntopng (but not ntopng-bin) to look inside", is it working for you when running the ntopng binary? (vs ntopng-bin not working when running it directly, which is expected)

**Comment by vollkommenheit** [comment]
@cardigliano I mean I think the `ntopng-bin` bundled with the official macOS installer  (such as https://packages.ntop.org/MacOS/ntopng-4.3.201102.pkg) should be [re-]compiled with the  flag `RPATH=/usr/local/opt/ntopng` (apparently a feature of ld.so/linker) rather than `LD_LIBRARY_PATH` or `LDFLAGS` or `DYLD_LIBRARY_PATH`, much like the change I made to the `/usr/local/bin/ntopng` shell script wrapper in order to get it to look inside /usr/local/opt/ntopng on macOS 11 El Capitan. From my rudimentary understanding after reading the arious discussions I linked to earlier in this thread, I also think RPATH seems the far safer choice over `LDFLAGS="-L/usr/local/opt/ntopng"` or `LD_LIBRARY_PATH=/usr/local/opt/ntopng` for compiling `ntopng-bin`, even though the latter two (LDFLAGS and LD_LIBRARY_PATH) might also resolve my issue on macOS 11. Currently we already know `DYLD_LIBRARY_PATH` does not work for me on macOS 11 for both `ntopng` and `ntopng-bin`, nor for @swingpatrol on macOS 10.14 Mojave.

I knew I could install ntopng from Homebrew, but I much rather not waste CPU cycles building (and rebuilding) all the lib dependencies (each time I upgrade ntopng), if the official macOS packages from ntop.org already have all the libs built and bundled within. It seems it's just a matter of getting ntopng (by changing an export path) and ntopng-bin (change a compiler flag, most likely) to look inside the right lib location.

**Comment by adamsj182** [comment]
You guys are on a whole other level than me and so I don't have anything to add except that I started running into the exact same error:

 "dyld: Library not loaded: /usr/local/Cellar/glib/2.66.1/lib/libgmodule-2.0.0.dylib
  Referenced from: /usr/local/opt/ntopng//libgio-2.0.0.dylib
  Reason: Incompatible library version: libgio-2.0.0.dylib requires version 6601.0.0 or later, but libgmodule-2.0.0.dylib provides version 3601.0.0
/usr/local/bin/ntopng: line 6: 34178 Abort trap: 6           /usr/local/bin/ntopng-bin $@"

Except with the "libglib-2.0.0.dylib" file. I noticed the modification date for the "libgmodule-2.0.0.dylib" file corresponded with the same day I ran "brew update && brew upgrade." Ntopng was working just fine before that. It seems that maybe homebrew is rolling back dylib files in order to update other programs.....if that makes any sense. Tonight, I installed the binary ntopng-4.3.201102.pkg and changed the install location to an external drive. Then I replaced the dylib file in question with the freshly installed file. Since the new and the old both had identical file modification dates (11/4/20, 3:13 AM), I didn't think anything would come of it. And I was correct, it did not fix the problem.

Lately, homebrew has been messing everything up with ntopng, netdata, bettercap, i2p, metasploit, nmap, and a handful of other apps to the point that I nearly wiped everything having to do with homebrew off my computer. I'm spending WAY too much time fixing all the messes it leaves behind and I'm starting to think using docker and port and just about any other packaging software is a better bet than brew. Or even just going the hard way and building from source through git cloning seems to be less of a headache than a the bad brews.

**Comment by itboffin71** [comment]
Whilst not a fix for the official package you can still get it working by installing using homebrew package tool

brew install ntopng

**Comment by xeen3d** [comment]
I have purchased a License the Brew is not a Pro version and I have same Problem now like others above but I have pay money
for get a running program !! So it would be Time fix that issue !!!
Andre

**Comment by mrx3000** [comment]
After installing from the official package (https://packages.ntop.org/MacOS/ntopng-4.3.201102.pkg) I do not see the "libgmodule-2.0.0.dylib" in the "/usr/local/opt/ntopng". Other libraries are there. As such, modifying "LD/DYLD_LIBRARY_PATH" does not help - library not there, can't be loaded.

Could someone please check the package contents?

**Comment by cardigliano** [comment]
Sorry for the delay, it took some time to rebuild a new OSX package. Please check the new package available at https://packages.ntop.org . Thank you.

**Comment by vollkommenheit** [comment]
> Sorry for the delay, it took some time to rebuild a new OSX package. Please check the new package available at https://packages.ntop.org . Thank you.

Nice, thanks. Now, on 10.14 Mojave I'm getting :

`#ntopng`
>03/May/2021 08:55:26 [Ntop.cpp:2411] Setting local networks to 127.0.0.0/8,fe80::/10
03/May/2021 08:55:26 [Redis.cpp:99] ERROR: Connection error [Connection refused]
03/May/2021 08:55:27 [Redis.cpp:83] Redis has disconnected, reconnecting [remaining attempts: 14]
03/May/2021 08:55:27 [Redis.cpp:99] ERROR: Connection error [Connection refused]

`#ntopng -r`
>ntopng-bin: option requires an argument -- r
03/May/2021 08:55:49 [Ntop.cpp:2411] Setting local networks to 127.0.0.0/8,fe80::/10
03/May/2021 08:55:49 [Redis.cpp:99] ERROR: Connection error [Connection refused]
03/May/2021 08:55:50 [Redis.cpp:83] Redis has disconnected, reconnecting [remaining attempts: 14]
03/May/2021 08:55:50 [Redis.cpp:99] ERROR: Connection error [Connection refused]
...

`#ntopng-bin -r`
>dyld: Library not loaded: /usr/local/opt/rrdtool/lib/librrd.8.dylib
  Referenced from: /usr/local/bin/ntopng-bin
  Reason: image not found
Abort trap: 6

`#ls -al /usr/local/opt/rrdtool/lib/librrd.8.dylib`
>ls: /usr/local/opt/rrdtool/lib/librrd.8.dylib: No such file or directory

`#find /usr/local -iname librrd*`
>/usr/local/opt/ntopng/librrd.8.dylib

**Comment by cardigliano** [comment]
It seems redis is not running, please try running in another shell "redis-server", then run "ntopng"

**Comment by vollkommenheit** [comment]
> It seems redis is not running, please try running in another shell "redis-server", then run "ntopng"

Thanks. I end up starting redis-server manually by executing "sudo /usr/local/bin/ntopng-redis-server", even though /Library/LaunchDaemons/io.redis.redis-server.plist is supposedly already loaded by launchd but apparently didn't kick off redis-server for some reason.

The one remaining question is: I have ntopng seemingly up and running, according to a look-see at http://my-ip:3030 , but should I still be concerned about the "librrd.8.dylib" error from ntopng-bin mentioned above?

`#ntopng-bin`
>dyld: Library not loaded: /usr/local/opt/rrdtool/lib/librrd.8.dylib
  Referenced from: /usr/local/bin/ntopng-bin
  Reason: image not found

**Comment by cardigliano** [comment]
@vollkommenheit please try using the "ntopng" command to run the application and let us know

**Comment by vollkommenheit** [comment]
> @vollkommenheit please try using the "ntopng" command to run the application and let us know

I have "ntopng" in one terminal, and "sudo /usr/local/bin/ntopng-redis-server" in another, both as foreground process. Things look fine at http://[my-ip]:3030 (though http://127.0.0.1:3030 says it's shut down). I'm just concerned about ntopng-bin seemingly trying to reference /usr/local/opt/rrdtool/lib/librrd.8.dylib when it's at /usr/local/opt/ntopng/librrd.8.dylib, which might mean some graphing function relying on rrdtool is not quite working.

**Comment by cardigliano** [comment]
@vollkommenheit the ntopng script takes care of fixing linking by setting DYLD_LIBRARY_PATH, if everything is working you can just ignore the ntopng-bin output.
