### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by fi-ro** [ntop/ntopng#484]
Hi,

My ntopng process just crashed with a segfault:

`nprobe1 kernel: [278184.943142] ntopng[9241]: segfault at 7f8f00000000 ip 00007f901aaf1aea sp 00007f8ff7ffe5d8 error 4 in libc-2.19.so[7f901aa69000+1bb000]`

```
v.2.3.160408 [Professional Edition]
GIT rev:   dev:46f69860c596ba6fa2441b05b2d035a03d561b91:20160408
Pro rev:   r610
System Id: 4AB8F5599205A1D6
Built on:  Ubuntu 14.04.3 LTS
```

If there are any more information needed, just let me know.

**Comment by lucaderi** [comment]
Please send us a tar file containing both the core dump and the ntopng binary

**Comment by fi-ro** [comment]
Here you go
Tar is not allowed by github :/ 
[ntopng_segfault.zip](https://github.com/ntop/ntopng/files/213280/ntopng_segfault.zip)

**Comment by lucaderi** [comment]
@fi-ro Sorry I need a code dump (a core file I mean not a text trace). Please try again and reopen this bug once available

**Comment by fi-ro** [comment]
Hi Luca,

could you please give instruction on how to produce the information needed?
I'm not that familiar in the linux dev world.

**Comment by simonemainardi** [comment]
execute `ulimit -c unlimited` and the run ntopng. A core file is produced upon crash. Send both the ntopng executable and the core file. Please not that the core file may be very large. So you may find it useful to send a download link rather than the whole file

**Comment by fi-ro** [comment]
I've managed to get a core file (logout/login was the trick).

The corefile is downloadable here:
https://bwsyncandshare.kit.edu/dl/fi6jfUa4PE66X8DncfV29chR/core.7z

The ntopng binary is the one I've posted earlier.

**Comment by lucaderi** [comment]
@fi-ro It doesn't look like a core dump the file you sent.

deri@pc-deri 214> m core.7z 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"> 
<html>
<head>
<meta name="title" content="bwSync&Share" />
<meta name="description" content="Share, sync and backup your files online" />
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<title>bwSync&Share</title>

<script type="text/javascript">
    var t_working = "Working...";
    var t_required = "This field is required.";
    var t_fix_this = "Please fix this field.";
