### ISSUE TITLE
Applications and Categories - Email/SMTP

### ISSUE THREAD

**Issue by eliassal** [ntop/ntopng#4840]
In the Applications and Categories, we have Email in the categories, clicking on it lands us on a page for the different protocols for Emails.
On the Active flows page, I try to find all local host using smtp/smtps/pop......no Email category  in the categories dropbox, nor SMTP or POP in the application box. Is this normal (2 snapshots hereunder).

I have my internal email server on a specific IP, I can see it in the host list, is it possible to add/update a Category/rule/application so I can see in the flows only smtp or POP on this server.

Thanks in advance

![CategoriesApp](https://user-images.githubusercontent.com/8447864/102247135-d66d4500-3eff-11eb-8d5c-1d2017c9b91c.jpg)
![CategoriesApp_002](https://user-images.githubusercontent.com/8447864/102247146-da996280-3eff-11eb-9a88-fbe520bd9d32.jpg)

**Comment by simonemainardi** [comment]
Described behavior is normal. 

To add custom categories see https://www.ntop.org/guides/ntopng/web_gui/categories.html?highlight=categories

Again stop abusing GitHub without going through the docs.

**Comment by eliassal** [comment]
Simon, you did not respond to the 1st problem. Yes I read the doc, and added a custom rule to the email (entered my email domain and the IP) but it is not working and still can't see it in the Active flows dropboxes

**Comment by eliassal** [comment]
Simon, as beginners, we will sometimes ask good questions, report which we think is a bug because of our limited knowledge or just maybe docs are not very clear as missing examples, and of course sometimes ask stupid questions which can happen to every one. Please respond to the 1st question before ssaying I am abusing, I provided you the snapshots

**Comment by eliassal** [comment]
Also, I would like to bring to your attention that one issue I raised was flagged as bug. 3 issues I raised for which I did not see any solution, especially the annoying "Too many flows" displayed with each click, with each click, with each click, see snapshot in spite of the fact that I provided all details, pcaps, my internal network plan

![ToomanyHosts3](https://user-images.githubusercontent.com/8447864/102248964-1f25fd80-3f02-11eb-9261-5b2af1380e5f.jpg)

**Comment by eliassal** [comment]
So it is not me who is abusing, it is you who did not respond to the main issue
