### ISSUE TITLE
JSON alerts are cryptic

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4843]
This is an example of an alert logger via syslog recipient. No clue what fields are about.
{"alert_subtype":"67_D8:9E:F3:D9:A8:08_80.81.192.76_FF:FF:FF:FF:FF:FF_1.2.3.0","ifid":3,"alert_entity":5,"alert_json":"{\"spa\":\"5.6.7.8\",\"src_mac\":\"D8:9E:F3:D9:A8:08\",\"vlan_id\":67,\"dst_mac\":\"FF:FF:FF:FF:FF:FF\",\"tpa\":\"1.2.3.4\"}","alert_granularity":0,"alert_severity":4,"pool_id":0,"action":"store","alert_tstamp_end":1608143642,"alert_tstamp":1608143642,"alert_entity_val":"D8:9E:F3:D9:A8:08","alert_type":2}

It is requested to log information in a format that users can understand or at least to document the content. Endpoint can select the output type and setting from JSON (that should be renamed to JSON raw or something to tell that this is fast albeit non human readeable) to ECS it does not help

![Screen Shot 2020-12-16 at 19 39 51](https://user-images.githubusercontent.com/4493366/102391888-9d53d400-3fd6-11eb-8e84-0133a6a4bf94.png)

**Comment by simonemainardi** [comment]
As discussed internally, extra references to the documentation and code have been added 

![image](https://user-images.githubusercontent.com/3397663/102522630-c89df800-4096-11eb-9b47-6d7f80c5bedc.png)
