### ISSUE TITLE
Context error

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4844]
16/Dec/2020 22:17:44 [LuaEngineHost.cpp:145] WARNING Could not set context for host 144.92.92.74@0
16/Dec/2020 22:14:11 [LuaEngineHost.cpp:145] WARNING Could not set context for host 103.203.138.185@0
16/Dec/2020 22:10:53 [LuaEngineHost.cpp:145] WARNING Could not set context for host 144.92.92.241@0

**Comment by simonemainardi** [comment]
Seems to be due to syslog trying to set alerts for hosts that are not in memory. Solution is to create a syslog-specific alert entity.

**Comment by cardigliano** [comment]
It is likely this was due to host alerts generated by syslog events, the alert store was checking the host, which is not always present/active in case of syslog events. A patch has been pushed to fix a similar issue, this should have been addressed as well.

**Comment by simonemainardi** [comment]
https://github.com/ntop/ntopng/commit/da62df2b73a02b78bfa519a91de34b90c55412ff

**Comment by simonemainardi** [comment]
This should be fixed in the latest build with referenced commit.
