### ISSUE TITLE
FreeBSD - ntopng 4.0 - Cannot switch to influxDB

### ISSUE THREAD

**Issue by TLINDEN** [ntop/ntopng#4848]
Howdy,

I am new to ntopng and want to use it with grafana, therefore I tried to switch to InfluxDB for timeseries storage. When I switch to influxdb, I always get this message:
```
Could not perform the requested action because the page expired. Please reload the page and perform the action again.
```

It doesn't matter wether I enable auth in InfluxDB or not.

The DB is running, I can connect to it via commandline `influx`. There are no errors rerported to syslog by ntopng.

Versions:

* OS: FreeBSD 12.2-RELEASE-p1 (running inside a jail)
* ntopng: ntopng-4.0.d20200710,1 (GUI about says: 4.0.201215 (0) - Community Edition)
* InfluxDB: influxdb-1.8.0

All packets are installed via `pkg` today (that is, latest ports).

ntopng is otherwise running as it should, I can watch network traffix, flows, etc. The browser (chrome) has no filters running (ghostery and umatrix are disabled).

**Comment by simonemainardi** [comment]
hello:

- FreeBSD is not among the distros we officially support
- Latest ntopngs stable is 4.2 not 4.0 and 4.0 is no longer mantained

You should consider contacting the package maintainer

**Comment by TLINDEN** [comment]
k, submitted [252014](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=252014).

Thanks,
Tom
