### ISSUE TITLE
Add switch states button in service map 

### ISSUE THREAD

**Issue by gabryon99** [ntop/ntopng#4849]
Inside the Service Map page, we are gonna add a new column with action buttons to switch the state of a service.
An Unknown service can be Accepted or Rejected. An Accepted/Rejected service cannot be toggled to the Unknown state but can change only to Rejected/Accepted.

<img width="1687" alt="Screenshot 2020-12-21 at 16 45 07" src="https://user-images.githubusercontent.com/14114916/102794581-e37caf00-43ab-11eb-9edc-3a9297b28558.png">

**Comment by gabryon99** [comment]
The buttons have been added to the pro repository.

**Comment by lucaderi** [comment]
![Screen Shot 2020-12-28 at 09 57 32](https://user-images.githubusercontent.com/4493366/103202602-23cfb600-48f3-11eb-9c56-91d42378cfd5.png)
The batch state change does not work (set button disabled) during learning

**Comment by gabryon99** [comment]
The set button has been re-enabled in learning status as well. Check the pro repository.

**Comment by lucaderi** [comment]
Works as expected
