### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by sirvulcan** [ntop/ntopng#485]
Ive just decided to give the 2.x series a go but im getting a segmentation fault. This happens on both the 2.2 latest release and the latest 2.3 git revision. We are running Debian 7 currently (upgrading to 8 is not an option at this point in time). We are running 1.9 at the same time but the issue also occurs if we stop the 1.9 version and just run 2.x.

Ive tarred up the binary and the core dump - http://sirvulcan.co.nz/ntop_bin_core.tgz . This is based on the latest git revision.

v.2.3.160407 [Community Edition]
GIT rev:   dev:46f69860c596ba6fa2441b05b2d035a03d561b91:20160407

`
Starting program: /usr/local/ntop/bin/ntopng -i eth0 -w 30001 --dont-change-user
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/i686/cmov/libthread_db.so.1".
12/Apr/2016 08:44:32 [Ntop.cpp:989] Setting local networks to 127.0.0.0/8
12/Apr/2016 08:44:32 [Redis.cpp:106] Successfully connected to redis 127.0.0.1:6379@0
12/Apr/2016 08:44:32 [PcapInterface.cpp:85] Reading packets from interface eth0...
12/Apr/2016 08:44:32 [Ntop.cpp:1209] Registered interface eth0 [id: 0]
12/Apr/2016 08:44:32 [Ntop.cpp:1221] Registered interface view eth0 [id: 0]
12/Apr/2016 08:44:32 [main.cpp:258] PID stored in file /var/tmp/ntopng.pid
12/Apr/2016 08:44:32 [HTTPserver.cpp:466] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
[New Thread 0xb6d9ab70 (LWP 6042)]
[New Thread 0xb6599b70 (LWP 6043)]
[New Thread 0xb5d98b70 (LWP 6044)]
[New Thread 0xb5597b70 (LWP 6045)]
[New Thread 0xb4d96b70 (LWP 6046)]
[New Thread 0xb4595b70 (LWP 6047)]
12/Apr/2016 08:44:32 [HTTPserver.cpp:509] Web server dirs [/usr/local/ntop/share/ntopng/httpdocs][/usr/local/ntop/share/ntopng/scripts]
12/Apr/2016 08:44:32 [HTTPserver.cpp:512] HTTP server listening on port 30001
12/Apr/2016 08:44:32 [main.cpp:295] Working directory: /var/tmp/ntopng
12/Apr/2016 08:44:32 [main.cpp:297] Scripts/HTML pages directory: /usr/local/ntop/share/ntopng
12/Apr/2016 08:44:32 [Ntop.cpp:259] Welcome to ntopng i686 v.2.3.160407 - (C) 1998-16 ntop.org
12/Apr/2016 08:44:32 [PeriodicActivities.cpp:53] Started periodic activities loop...
[New Thread 0xb3d94b70 (LWP 6048)]
[New Thread 0xb3593b70 (LWP 6049)]
[New Thread 0xb2d51b70 (LWP 6050)]
[New Thread 0xb2550b70 (LWP 6051)]
12/Apr/2016 08:44:32 [RuntimePrefs.cpp:34] Dumping alerts into syslog
12/Apr/2016 08:44:32 [Ntop.cpp:515] Adding 10.2.0.0/16 as IPv4 local network for eth0

Program received signal SIGSEGV, Segmentation fault.
0x080a15b7 in Ntop::loadLocalInterfaceAddress (this=0x8236290) at src/Ntop.cpp:541
541               s6->sin6_addr.s6_addr[j] &= i >= 8 ? 0xff : (u_int32_t)(( 0xffU << ( 8 - i ) ) & 0xffU );

(gdb) bt
#0  0x080a15b7 in Ntop::loadLocalInterfaceAddress (this=0x8236290) at src/Ntop.cpp:541
#1  0x080a105f in Ntop::start (this=0x8236290) at src/Ntop.cpp:282
#2  0x08092b15 in main (argc=6, argv=0xbffffce4) at src/main.cpp:311

`

**Comment by lucaderi** [comment]
@sirvulcan I think I have fixed the bug. Please rebuild the code and try again. Thanks for reporting the issue. In case the bug isn't fixes please reopen it.
