### ISSUE TITLE
crash: double free or corruption

### ISSUE THREAD

**Issue by kamalyang** [ntop/ntopng#4851]
I use zc mode and RSS to analysis traffic flow. Also I integrate Suricata with ntopng, but got crash everyday.
The crash log is here.
[ntopcrash.log](https://github.com/ntop/ntopng/files/5728569/ntopcrash.log)

**Comment by simonemainardi** [comment]
you are on version 4.0 which is no longer supported. Please, upgrade to 4.2+.
