### ISSUE TITLE
Implement MAC Address Based Traffic Directions

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4852]
With mirror or pcap-based systems with no traffic directions, it is not possible to know the traffic direction (ingress or egress). As in nProbe it is requested to specify a list of MAC addresses that are used to identify traffic directions. Example if you specify in the MAC address list the MAC of the router, you can have automatically the traffic direction (TX when sending to the router, RX from receiving traffic with the MAC of the router).

**Comment by cardigliano** [comment]
Traffic from the configured MAC addresses will be RX, towards the MAC addresses will be TX.
The direction of traffic which is *not* matching any src/dst mac is RX (default).
