### ISSUE TITLE
libatomic required when installing on minimal CentOS 8

### ISSUE THREAD

**Issue by lallori** [ntop/ntopng#4859]
This is not really an issue but took me a while to discover while ntopng was not running and maybe this could be useful to others.

I installed ntopng on CentOS8 following the steps on here:
https://packages.ntop.org/centos/

This is the generic error I got:
Process: 152858 ExecStart=/usr/bin/ntopng /run/ntopng.conf (code=exited, status=1/FAILURE)

So I runned ntopng alone and I did see that libatomic was required.

I had a minimal install of CentOS8 so that might be the case.

**Comment by simonemainardi** [comment]
> So I runned ntopng alone and I did see that libatomic was required.

Can you please post a log? How did you find this? Did you see an exception?

**Comment by lallori** [comment]
The generic error above was generated when I was trying to start ntopng as a service.
To get that the library was missing I just run the ntopng -v from cmd line and the system just said to me that I needed that library. 
After installing it with dnf everything was fine.

**Comment by simonemainardi** [comment]
Thanks for pointing this out. Fixed.
