### ISSUE TITLE
Configuring standard/non-standard ports for known applications

### ISSUE THREAD

**Issue by lallori** [ntop/ntopng#4860]
I installed nprobe on OPNsense and delivering alerts on ntopng installed on another host. Everything is working fine but I am receiving unwanted alerts such as: Known application HTTP detected on non-standard port. Is there a way to configure the ports numbers? I would like to add 8080 and 3000 to the list.

**Comment by simonemainardi** [comment]
Application well-known ports are coded in nDPI and are standard so they cannot be configured.

If you are planning to run applications on non-well-known ports, you should either add them as custom applications https://www.ntop.org/guides/ntopng/web_gui/categories.html#custom-applications or disable the risk "Known application HTTP detected on non-standard port" from the flow user scripts "Flow Risk" configuration.
