### ISSUE TITLE
ntopng causing packet loss: option to rate limit Network Discovery

### ISSUE THREAD

**Issue by kdkavanagh** [ntop/ntopng#4861]
Network Discovery enters a tight loop sending ARP/MDNS requests for every possible IP in the address space.  On large networks (/16), this can cause broadcast storms which result in packet loss for users on the network.  Suggested fix would be to rate limit the requests, either with a simple sleep in between requests, or possible only iterating over a subset of the address space on each invocation of Network Discovery.  It may also be more efficient to only send requests for IPs not already known to ntopng

This took a while for me to track down in my network: First I realized that I was seeing packet loss across most clients on a predictable cadence (15min), then from a pcap on my router I found the sequence of ARP requests preceded by a blank DHCP request during every period of packet loss.  The DHCP request and ARP request had a src MAC of 00:00:00:00:00:00, which I found odd.  

Wasn't able to find anything online to help here, but it became very obvious that it was ntopng issuing the requests after reading the source code here: https://github.com/ntop/ntopng/blob/dev/src/NetworkDiscovery.cpp#L380.  Still unsure if/why the MAC needs to be zeroed out, rather than using the MAC of the interface discovery will use, similar to how the src IP is set on the ARP request itself.

**Comment by r1bnc** [comment]
I think I may have this issue as well. I kept loosing the ethernet connection every 15 mins (exact) and notice some mDNS/ARP requests in wireshark as well as journalctl log: `ntop-utils-manage-updates -a handle-upgrade-requests`. I have uninstalled ntopng (for the meantime) and the issue appears to be fixed.

**Comment by lucaderi** [comment]
> I think I may have this issue as well. I kept loosing the ethernet connection every 15 mins (exact) and notice some mDNS/ARP requests in wireshark as well as journalctl log: `ntop-utils-manage-updates -a handle-upgrade-requests`. I have uninstalled ntopng (for the meantime) and the issue appears to be fixed.

Better to disable periodic discovery from preferences rather than uninstall the tool isn't it?

**Comment by lucaderi** [comment]
> Network Discovery enters a tight loop sending ARP/MDNS requests for every possible IP in the address space. On large networks (/16), this can cause broadcast storms which result in packet loss for users on the network. Suggested fix would be to rate limit the requests, either with a simple sleep in between requests, or possible only iterating over a subset of the address space on each invocation of Network Discovery. It may also be more efficient to only send requests for IPs not already known to ntopng
> 
> This took a while for me to track down in my network: First I realized that I was seeing packet loss across most clients on a predictable cadence (15min), then from a pcap on my router I found the sequence of ARP requests preceded by a blank DHCP request during every period of packet loss. The DHCP request and ARP request had a src MAC of 00:00:00:00:00:00, which I found odd.
> 
> Wasn't able to find anything online to help here, but it became very obvious that it was ntopng issuing the requests after reading the source code here: https://github.com/ntop/ntopng/blob/dev/src/NetworkDiscovery.cpp#L380. Still unsure if/why the MAC needs to be zeroed out, rather than using the MAC of the interface discovery will use, similar to how the src IP is set on the ARP request itself.

We already limit the number of requets by adding h a 1 ms sleep (https://github.com/ntop/ntopng/blob/dev/src/NetworkDiscovery.cpp#L278), that I have increased to 1.5 ms. The fact that you have a /16 flat network is not a good news: I have added a limit to /23 to avoid long scans. The blank request is correct and the MAC is not blank as you said.
![Screen Shot 2020-12-28 at 11 18 17](https://user-images.githubusercontent.com/4493366/103207460-aa3dc500-48fe-11eb-84ac-9abf645c82cd.png)

 I have pushed some fixes https://github.com/ntop/ntopng/commit/2d30d543eebd28c4235703885c356bdfef415e69 that will be included in the next overnight build. Please let me know if they help.

**Comment by lucaderi** [comment]
Closing as it works for us. if not please reopen and ad details

**Comment by kdkavanagh** [comment]
This will certainly help.  Curious if it is feasible to either limit the discovery to only one network or perhaps offer the option to run discovery on-demand (e.g I'd be fine running it once a day overnight to minimize impacts to users)?
