### ISSUE TITLE
New ntopng-4.3.201224-x64 install after trial expire error

### ISSUE THREAD

**Issue by TheMichMan** [ntop/ntopng#4865]
After trial license expires get this error:

HTTP/1.1 302 Found Set-Cookie: session=20015bf9525f84e0e566a42861114b7b; path=/; HttpOnly; SameSite=lax Location: /lua/http_status_code.lua?message=internal_error&referer=localhost%3A3000%2F%3Fifid%3D1%26page%3Dinternals%26tab%3Dperiodic_activities&error_message=...scripts%2Flua%2Fmodules%2Ftoasts%2Fpredicates_defined_toasts.lua%3A279%3A%20attempt%20to%20call%20a%20nil%20value%20%28global%20%27create_DHCP_range_missing_toast%27%29 ...scripts/lua/modules/toasts/predicates_defined_toasts.lua:279: attempt to call a nil value (global 'create_DHCP_range_missing_toast')

**Comment by simonemainardi** [comment]
Thanks for reporting. Issue is fixed and will be available in the next dev build, out in less than 24h.
