### ISSUE TITLE
Geo map has pins and info but no map

### ISSUE THREAD

**Issue by amastelek** [ntop/ntopng#4866]
Have installed stable 4.2
Followed process for maxmind incl. account

Map has pins but no actual map image?  Just white.

**Comment by amastelek** [comment]
> 
> 
> Have installed stable 4.2
> Followed process for maxmind incl. account
> 
> Map has pins but no actual map image? Just white.

Map disappears when dark theme is used as above!

**Comment by simonemainardi** [comment]
@gabryon99 can you please check this? Another discord user was reporting this behavior but if I remember correctly it should already have been solved.

**Comment by gabryon99** [comment]
Hello, we solved this issue in dev stable. This ticket is a duplicated of #4770

**Comment by simonemainardi** [comment]
@gabryon99 can you please backport (and test) the fix to stable?

**Comment by gabryon99** [comment]
Sure!

**Comment by gabryon99** [comment]
Ok, I backported the fixing commit to the 4.2-stable branch. @amastelek In the next hours, a new updated will be available!

<img width="1769" alt="Screenshot 2020-12-28 at 09 30 49" src="https://user-images.githubusercontent.com/14114916/103201114-61cadb00-48ef-11eb-9b5e-efd1ad05bf62.png">
