### ISSUE TITLE
Unexpected DNS/DHCP/NTP/SMTP with FQDN and IP

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#4869]
This feature is cool, but We need FQDN also, because for Cloud Email Services, or public NTP it is difficult to track every single IP provides have.

**Comment by lucaderi** [comment]
![Screen Shot 2021-10-11 at 15 55 01](https://user-images.githubusercontent.com/4493366/136802266-3a4f00e8-ce8f-429f-8a59-63cbb8cf6235.png)
It doesn't seem to work
