### ISSUE TITLE
error when viewing host details

### ISSUE THREAD

**Issue by elim99** [ntop/ntopng#487]
I get the following error when I attempt to view a host:

```
 Script "/usr/share/ntopng/scripts/lua/host_details.lua" returned an error:

/usr/share/ntopng/scripts/lua/host_details.lua:67: attempt to call field 'isLocalPacketdumpEnabled' (a nil value)
```

This error appears after ntopng has been running for a while - in this case for about 30 hours. A restart of ntopng promptly fixes the issue. The log file basically has the exact same error. I was not able to catch this error in verbose mode.

**Comment by simonemainardi** [comment]
I think I have fixed the issue. Packages are being built and will be available tomorrow.
