### ISSUE TITLE
TCP RST Flags

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#4871]
How can i know the live and hystorical RST flags behavior?
In order to do assurance and verifiy if the firewall is blocking or not, how can i export who is creating RST Flags on flows?

**Comment by simonemainardi** [comment]
Please, explain further. Give an example at least.

**Comment by zimbawe998** [comment]
On interface packets menu i have that 30% ot all packet are on RST. How can i reduce this percentage?
Is there an export that allow me to understand which protocols/IP SRC/IP DST generate this traffic?

**Comment by simonemainardi** [comment]
You can use the active flows page:

![image](https://user-images.githubusercontent.com/3397663/103216985-b97d3c80-4917-11eb-9831-7e5fe779c5ad.png)

You can pick (any combination of):
- TCP as protocol
- Then you can choose the connection state (e.g., established, ReSeT, connecting, etc).
- And eventually the Application

Why does this don't suffice?

**Comment by simonemainardi** [comment]
any news?

**Comment by simonemainardi** [comment]
No feedback received. Closing.
