### ISSUE TITLE
Exclusion/inclusion filters

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#4872]
Hi Customer is asking the possibility to have Exclusions/Inclusions filters on:
- Flow view
- Hystorical view
- Host Flow View

**Comment by simonemainardi** [comment]
Did you consider using (a combination of):

- BPF-filters (option `-B`)
- Dynamic disaggregated interfaces
- Historical flows explorer
- nIndex historical flows explorer

Explain, in detail, why any of the above does not suffice to solve your use case, and, if necessary, what we should do to extend.

**Comment by simonemainardi** [comment]
can you comment?

**Comment by simonemainardi** [comment]
No feedback received. Closing.
