### ISSUE TITLE
Alarm bases on flow (include or exclude)

### ISSUE THREAD

**Issue by AlekseiSaff** [ntop/ntopng#4874]
Hi, we would like to have an alarm option based on:

 unwanted flow (let's say to the specific IP: port) (i.e. send an alarm if we see a traffic to 192.168.12.35:50001)
 flow that we don't see, but that must be during work hours (let's say specific multicast flow) (i.e. send an alarm if no multicast traffic in las X minutes).

it's also good to have an option to limit it during specific working hours

**Comment by martinscheu** [comment]
Hi, @AlekseiSaff
If I understand it correctly, you need alerts when

1. we see a traffic to/from 192.168.12.35:50001
2. a flow should be present within a time frame, but isn't
3. limit a flow within a time frame

For 1. and 2. could be a nice project for doing a user plugin.
Thanks

**Comment by AlekseiSaff** [comment]
Do you mean it's not possible to add as a standart functionality?

Alex

**Comment by simonemainardi** [comment]
Correct. Doing a user plugin should be the way. Actually, I believe we need a couple of plugins, one for 1. and one for 2. If you guys are interested in doing the development, I can support you.

**Comment by MatteoBiscosi** [comment]
Hi @AlekseiSaff please follow up the issue #6117 . We are currently working on it
