### ISSUE TITLE
Table reload does not refresh menu items

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4875]
![Screen Shot 2020-12-29 at 14 50 29](https://user-images.githubusercontent.com/4493366/103288504-493cec80-49e5-11eb-9832-3794239f39aa.png)

**Comment by simonemainardi** [comment]
Still bugged

![image](https://user-images.githubusercontent.com/3397663/103356315-e022ab00-4ab0-11eb-923d-53f9ebc809c3.png)
