### ISSUE TITLE
ntopng bandwidth consumption

### ISSUE THREAD

**Issue by eliassal** [ntop/ntopng#4876]
Hi, I have a question about ntopng consumption which seems to me very high. I use solarwinds bandwidth monitor, have setup  monitors for 8 NICs (wifi & ethernet) as you can notice in the 1st snapshot, 3 on the left for 3 NICS on a physcial server, in the middle Wand and Lan interfaces of my router, in the right 3, 1st one on top is the monitor for the VM where ntop runs, the other 2 monitors are for wifi and ethernet on my laptop. As you can notice that the 1 for ntopng has no figures as VM is not started yet, my consumption Wan/Lan consumption never goes beyond 40/50Mbs.
![BandwidthBeforeNtopng](https://user-images.githubusercontent.com/8447864/103297810-58c63080-49f9-11eb-919a-244357c6ab32.jpg)

As soon as I start the ntopng VM, it shoots always 140/160 Mbs and continues like this all the time as you can notice in the 2nd snapshot, the question is why this high consumption?
![BandwidthAfterNtopng](https://user-images.githubusercontent.com/8447864/103297839-62e82f00-49f9-11eb-8880-6a10ae8262aa.jpg)

**Comment by simonemainardi** [comment]
There is no high consumption. If you look at average or 95percentile of WAN/LAN traffic, you'll see the they are unchanged.

Those short high-speed notches may signify one of the following things:
- ntopng web UI is being accessed and thus serving its contents
- ntopng may be downloading category lists from authorized sites
- the VM is doing network activities that are not related with ntopng

You may be able to spot this by looking at ntopng active flows - assuming ntopng is monitoring all the host traffic.

**Comment by eliassal** [comment]
Thanks, yes, it is monitoring all hosts, I don't see huge traffic in webui and I access it 2 or 3 times a day.
By "downloading category lists from authorized sites.....", which sites ? Can IU find them somewhere in the configuration and authorized by ntopng?  
As you can notice in the following snapshot of ntopng, no huge flows (this is the standard daily figures)
![details](https://user-images.githubusercontent.com/8447864/103404671-c6d33a80-4b54-11eb-91c0-d352285c417e.jpg)

**Comment by simonemainardi** [comment]
> By "downloading category lists from authorized sites.....", which sites ? Can IU find them somewhere in the configuration and authorized by ntopng?

https://www.ntop.org/guides/ntopng/advanced_features/category_lists.html?highlight=lists

> As you can notice in the following snapshot of ntopng, no huge flows (this is the standard daily figures)

Look at the header when you have the spike in solar winds.

**Comment by eliassal** [comment]
Great, so many thanks, I checked, by default in ntopng there is 6 enabled lists. I visited all, update seems should be done one list by one list, is there a way to update them all at one time?

**Comment by simonemainardi** [comment]
They are updated periodically together, depending on the specified frequency.
