### ISSUE TITLE
Service Map issues

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4878]
- As soon as I try to zoom out the service map, it gets stuck in an unusable state:

![image](https://user-images.githubusercontent.com/3397663/103355682-1eb76600-4aaf-11eb-93c0-74eabd003771.png)

- There's no "reload table button" as said in the message

- buttons are not equally-spaced

![image](https://user-images.githubusercontent.com/3397663/103355798-7fdf3980-4aaf-11eb-9ca5-7c7238027d3c.png)

**Comment by simonemainardi** [comment]
note says "During the learning, a service status cannot be changed." but I can change the status of services using the rightmost column

During the learning, a service status cannot be changed.

![image](https://user-images.githubusercontent.com/3397663/103356121-596dce00-4ab0-11eb-9036-2e13101f8487.png)


![image](https://user-images.githubusercontent.com/3397663/103356129-612d7280-4ab0-11eb-800c-985eef5c1008.png)

**Comment by simonemainardi** [comment]
There are two yellow edges in the graph, but no yellow service is present in the table

![image](https://user-images.githubusercontent.com/3397663/103356185-85894f00-4ab0-11eb-9b08-b1dcd261e513.png)

**Comment by simonemainardi** [comment]
What is the meaning of "Undefined" status

![image](https://user-images.githubusercontent.com/3397663/103356238-b2d5fd00-4ab0-11eb-9781-30670f69ceb5.png)

**Comment by simonemainardi** [comment]
I have a denied service

![image](https://user-images.githubusercontent.com/3397663/103356555-6fc85980-4ab1-11eb-8a56-820a3b122a0e.png)

But if I pick Denied from the dropdown, it returns no results

![image](https://user-images.githubusercontent.com/3397663/103356577-7ce54880-4ab1-11eb-9923-bd29d72acae4.png)

**Comment by simonemainardi** [comment]
last seen must be aligned to the center

![Uploading image.png…]()

**Comment by gabryon99** [comment]
I'll try to do a brief summary:
* fixed the zoom for the graph view
* improved the displayed message
* between the buttons there was a separator (like other similar pages), now is gone and the button are equally spaced
* removed old note
* fixed unknown flows in the map
* **Undefined** means that a service is not **allowed** either **denied** and user interaction is requested
* when a service change now there is a reload to prevent this issue
* Last Seen is now aligned to the center.

All these edits are inside the pro repository.

**Comment by simonemainardi** [comment]
This is still bugged: https://github.com/ntop/ntopng/issues/4878#issuecomment-752635919
Please rename Undefined to Undecided
