### ISSUE TITLE
Interface statistics not working properly

### ISSUE THREAD

**Issue by presianbg** [ntop/ntopng#488]
Dear All,

Thank you for the great work!

I have some problems with my nbox setup (latest centos nightly builds). Here is my config:

cat /etc/nprobe/nprobe-none.conf 

```
-n=none
-i=none
-t=60
-d=60
-a=0
-e=1
-B=10
-w=128000
-z=0
-S=@10:1
-E=0:0
-g=/var/run/nprobe-none.pid
-3=3683
--zmq=tcp://*:5556
--vlanid-as-iface-idx=none
-V=5
--dump-stats=/var/log/nprobe/none-0_flows_stats.txt
```

cat /etc/ntopng/ntopng.conf

```
-w=3000
-W=0
-g=-1
-m="xxx.xxx.xxx.xxx/xx, yyy.yyy.yyy.yyy/yy"
-X=999999
-x=999999
-d=/var/storage/ntopng
-G=/var/tmp/ntopng.pid
-i=tcp://127.0.0.1:5556

```

[screenshot](http://imgur.com/8LmvtZL) - meter and graphs are working sometimes, but most of the time they do nothing.

I'm using nprobe as proxy :

NetFlow Router V5 ->flow -> nprobe -> ZMQ -> ntopng

Could you look into this issue?

Best Regards,

**Comment by simonemainardi** [comment]
please paste the screenshot directly here. I cannot access imgur.

**Comment by presianbg** [comment]
![selection_003](https://cloud.githubusercontent.com/assets/2163486/14491596/79ad2fc0-0182-11e6-989e-e5cf214e8d97.png)

**Comment by simonemainardi** [comment]
https://github.com/ntop/ntopng/issues/470 :

> The speed cannot be detected as nprobe is NOT capturing from a physical device but ti is used as collector [...]. So this is not a bug but a limitation of the sender

**Comment by presianbg** [comment]
But sometimes when I restart ntopng and nprobe it's working for a munite or two... how that comes ?

**Comment by simonemainardi** [comment]
please, navigate to the interface page and check the historical interface speed chart.

**Comment by presianbg** [comment]
![selection_004](https://cloud.githubusercontent.com/assets/2163486/14491954/a59b3ca6-0184-11e6-830e-296179abd433.png)

**Comment by simonemainardi** [comment]
that's correct. The chart on the left is empty for the reasons described in #470

**Comment by presianbg** [comment]
Ok. Thank you.
