### ISSUE TITLE
Goodput Ratio Alert adjustable

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#4887]
Hello,
Goodput ratio with IEC 60870 is low, as e.g. the protocol payload of TESTFR (standby link check) is 36byte, compared to 54 bytes of the Ethernet / IP / TCP part.
Could the goodput be adjustable, e.g. by protocol ? 
Or disable goodput check for selectable protocols.
Thanks

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu unfortunatly currently it is not possible to adjust the goodput ratio based on the protocol however we recently implemented alert filters, so it is possible to disable the goodput ratio alert by adding the specific protocol to the "Filter List"
