### ISSUE TITLE
Flow Alerts page - alert in own column

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#4888]
Hello,
When I click on the red Flow alert button, it filters to the flows with errors.
To hoover over the red triangle in the protocol field is not intuitive.
Could the alert be displayed in a additional column?
<img width="249" alt="Screenshot 2021-01-05 at 18 55 00" src="https://user-images.githubusercontent.com/38549755/103681454-c806cc00-4f87-11eb-9b83-ca2a8a2327ec.png">
Thanks

**Comment by lucaderi** [comment]
What if the Info column is populated with this info in case of alert? Adding a new column can make the table too large

**Comment by martinscheu** [comment]
can, although I am not convinced, as I would like to filter. how about having a flow alert page instead of setting a filter on the flow list when pressing the alarm button?
The info column I like to quick display additional information to a flow out of user scripts, where the operators are not familiar with scripting or command line interface

**Comment by lucaderi** [comment]
![Screen Shot 2021-01-18 at 15 08 59](https://user-images.githubusercontent.com/4493366/104925442-2166f600-599f-11eb-923f-98422d5b06c8.png)
We already have flow alerts: please explain how we should modify it

**Comment by martinscheu** [comment]
I think is just a different approach of how to drill down. I like the flow page because I can filter by application and then I would like to see the errors. Therefore if on the flow page a additional column might lead to too much information, I would like a copy of the flow page with the alert in a separate column, so I can filter. Also nice on the flow page to get details for the flow (e.g. iec104)

**Comment by simonemainardi** [comment]
I think this is what your are looking for https://github.com/ntop/ntopng/issues/4941

**Comment by martinscheu** [comment]
yes can work with #4941 .
thank you.
