### ISSUE TITLE
Exported Flows output nothing by dump flows: syslog

### ISSUE THREAD

**Issue by Daniel6651** [ntop/ntopng#4890]
Hi all,

I'm using ntopng 4.3, and confused about exporting flows to fluentd. But report showed that nothing exported and dropped flows are extremely high in portion.

![report](https://user-images.githubusercontent.com/77033747/103719533-2b364400-5004-11eb-9b6a-ed4ac7ee61e9.PNG)

Here are my configuration.
![config_LI](https://user-images.githubusercontent.com/77033747/103719863-f37bcc00-5004-11eb-939b-03214cae422e.jpg)

And logs are only these things
![log_LI](https://user-images.githubusercontent.com/77033747/103724210-c3392b00-500e-11eb-8e71-3822cff7ca40.jpg)

Did someone suffer the same thing?

**Comment by simonemainardi** [comment]
Reported error should already be fixed. Please, update to version at least 4.3.210106 and report if you are still getting errors. Then we'll investigate the export.

**Comment by Daniel6651** [comment]
I've updated to v4.3.210106 and found that dropped flows become 0%. But exported flows still remain unchanged, so I couldn't get traffic logs from my file path: /var/log/ntopng/traffic.log. 

![report](https://user-images.githubusercontent.com/77033747/103840800-3b662600-50cd-11eb-8409-e463e658ba2d.PNG)

**Comment by simonemainardi** [comment]
Issue is fixed. A bug was preventing from counting exported flows.

Note that exported flows go into `/var/log/ntopng.log` and not `/var/log/ntopng/traffic.log`.

See the updated documentation as you may need to restart `syslogd`: https://www.ntop.org/guides/ntopng/advanced_features/flows_dump.html#syslog
