### ISSUE TITLE
How to list remote hosts which were active more than 1 day ago

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#4891]
Ubuntu 20.10
ndpi 3.5.0-2847-328ff246
ntopng 4.3.201112 (12182) - Community Edition

Considering that:
- [sticky hosts feature has been removed](https://github.com/ntop/ntopng/issues/2907)
- remote hosts can only be cached for 24 hours max (**Remote Host Idle Timeout**)

How can we access the details/statistics of remote hosts which **were active more than 24 hours ago** without knowing their IP address?

**Comment by simonemainardi** [comment]
> sticky hosts feature has been removed
> remote hosts can only be cached for 24 hours max (Remote Host Idle Timeout)

Both are meaningful conservative approaches to use RAM. As you said "remote hosts which were active more than 24 hours ago" are actually past hosts. It's not desirable to have them in memory as this can be a waste of resources.

To access such past hosts, ou need to use and access a database. You can choose MySQL for example (if the number of flows is limited) or nIndex.

Using MySQL for example you can query all flows and talkers within a certain time range:

![image](https://user-images.githubusercontent.com/3397663/106171772-4246fc80-6192-11eb-9241-50ff9f6d5568.png)


You can do the same using nIndex. See option -F and related documentation for additional information.

**Comment by jean-christophe-manciot** [comment]
@simonemainardi 
Since the "Flow search criteria"  does not exist in ntopng **community-edition** (up to 6a88d0774 2021/01/25 at least), I suppose it won't be possible with that edition even with mysql with -F (which I've been using for a long time).

**Comment by simonemainardi** [comment]
correct

**Comment by sergentum** [comment]
so there is no way now to find out who (ip address) is top consumer of the last month (for example), is that correct?
I thought that was one of the most important features of that software, isn't it?
I'm looking for software that can count traffic by local ips, but no luck, any advice?
