### ISSUE TITLE
ntopng vm resource calculator

### ISSUE THREAD

**Issue by djha983** [ntop/ntopng#4892]
Hi,

I want to calcualate the resource requirement for 10g thoughput network monitoring using ntop ng.Is there any calculator/document available for same so that i can better allocate the resource upfront to ntopng vm.

Like how much disk,how much RAM as well as how many core CPU is required by ntopng to monitor 10gb throughput network traffic.

**Comment by simonemainardi** [comment]
ntopng: https://www.ntop.org/guides/ntopng/faq.html#hardware-sizing
nProbe: https://www.ntop.org/guides/nprobe/hardware_sizing.html
