### ISSUE TITLE
Historical interface

### ISSUE THREAD

**Issue by overload08** [ntop/ntopng#49]
I use last SVN version of ntopng.
When I try to load files via historical interface, my ntopng crash...

Known issue ?

**Comment by ariava** [comment]
@overload08 could you please use the latest code from this git repo instead of the old SVN repo? Also, there a known issue with the historical interface we are looking into right now.

**Comment by ariava** [comment]
@overload08 could you please try the latest git code from the dev branch or the nightly that will be cooked today? d1ef8f3 should fix the crash.
