### ISSUE TITLE
TOR Exit nodes Category

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#4900]
Hi Guys,
is it possible to inser TOR Exit node IPLIST like a Anonymizer  Category on ntopng?
This is the official exit node list.
https://check.torproject.org/exit-addresses

**Comment by lucaderi** [comment]
nDPI detects Tor via DPI and complements this with Tor nodes. This is the code https://github.com/ntop/nDPI/blob/dev/src/lib/ndpi_content_match.c.inc#L1358

As they have changed very 30 mins, this will be a constant reload as some of our uses do
