### ISSUE TITLE
TOR nodes Category

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#4901]
Hi Guys,
is possible to insert this tor nodes list like a Category in order to increment visbility for Anonymizer sources/destination?
link 1 https://www.dan.me.uk/tornodes
link 2 (This contains IPv6 also): https://unlockforus.com/blocking-tor-with-pfblockerng-in-pfsense/

**Comment by lucaderi** [comment]
This is an nDPI request not ntop. nDPi already includes Tor nodes and can block it.https://github.com/ntop/nDPI/blob/dev/src/lib/ndpi_content_match.c.inc#L1358
