### ISSUE TITLE
HTTP/1.1 302 Found after upgrade to 201224

### ISSUE THREAD

**Issue by daxrob** [ntop/ntopng#4902]
Hi,

I just upgraded from 4.3.201103 to 4.3.201224 on Windows 10. The previous version worked fine.
After the upgrade I see the login webpage but the I receive the following error:

HTTP/1.1 302 Found Set-Cookie: session=cac2cc7cf69e8ef5c005b3d2b745bfb1; path=/; HttpOnly; SameSite=lax Location: /lua/http_status_code.lua?message=internal_error&referer=127.0.0.1%3A3000%2Flua%2Fhttp_status_code.lua%3Fmessage%3Dinternal_error%26referer%3D127.0.0.1%253A3000%252Flua%252Fflows_stats.lua%26error_message%3D...rogram%2520Files%255Cntopng%252Fscripts%252Flua%252Fmodules%252Falert_consts.lua%253A402%253A%2520attempt%2520to%2520index%2520a%2520nil%2520value%2520%2528fi&error_message=...rogram%20Files%5Cntopng%2Fscripts%2Flua%2Fmodules%2Falert_consts.lua%3A402%3A%20attempt%20to%20index%20a%20nil%20value%20%28field%20%27meta%27%29 ...rogram Files\ntopng/scripts/lua/modules/alert_consts.lua:402: attempt to index a nil value (field 'meta')

I also tried from different PCs. Same result.

Can you help me?
Thanks

**Comment by simonemainardi** [comment]
Update to the latest version. You are running a version from December.

**Comment by daxrob** [comment]
Hi, I already installed the latest version 4.3.201224 available for Windows from your website. Is this version that has the problem.
https://packages.ntop.org/Windows/ntopng-4.3.201224-x64.zip

**Comment by simonemainardi** [comment]
a new windows build will be released in the next 24hours

**Comment by simonemainardi** [comment]
You can update. Windows package is ready.

**Comment by daxrob** [comment]
I updated the version to the ntopng-4.3.210112-x64 version.
But I still receive the following error message:
HTTP/1.1 302 Found Server: ntopng 4.3.210112 (x64) Set-Cookie: session=d568a97d9e40b9c6f7d109f77ff95217; path=/; HttpOnly; SameSite=lax Location: /lua/http_status_code.lua?message=internal_error&referer=127.0.0.1%3A3000%2Flua%2Fhttp_status_code.lua%3Fmessage%3Dinternal_error%26referer%3D127.0.0.1%253A3000%252Flua%252Fflows_stats.lua%26error_message%3D...rogram%2520Files%255Cntopng%252Fscripts%252Flua%252Fmodules%252Falert_consts.lua%253A402%253A%2520attempt%2520to%2520index%2520a%2520nil%2520value%2520%2528fi&error_message=...rogram%20Files%5Cntopng%2Fscripts%2Flua%2Fmodules%2Falert_consts.lua%3A402%3A%20attempt%20to%20index%20a%20nil%20value%20%28field%20%27meta%27%29 ...rogram Files\ntopng/scripts/lua/modules/alert_consts.lua:402: attempt to index a nil value (field 'meta')

**Comment by simonemainardi** [comment]
try not to refresh the page. Close the browser and then point to the ntopng site.

**Comment by daxrob** [comment]
Already tried with many browsers and cleaning the cache. Nothing helped so far.

**Comment by lucaderi** [comment]
new Windows build is out. Please upgrade and reopen this ticket is necessary.

**Comment by patoberli** [comment]
Hi, I updated today also to this build ntopng-4.3.210112-x64 (which is still the current download offered) and I'm now also facing the same error (or very similar).
Error message I get:
Internal server error
__.rogram Files\ntopng/scripts/lua/modules/alert_consts.lua:402: attempt to index a nil value (field 'meta')
And the URL is:
http://127.0.0.1:3000/lua/http_status_code.lua?message=internal_error&referer=127.0.0.1%3A3000%2Flua%2Fpro%2Freport.lua%3Fnum_minutes%3D10080&error_message=...rogram%20Files%5Cntopng%2Fscripts%2Flua%2Fmodules%2Falert_consts.lua%3A402%3A%20attempt%20to%20index%20a%20nil%20value%20%28field%20%27meta%27%29

I upgraded from ntopng-4.3.201103-x64.

**Comment by simonemainardi** [comment]
A new windows build is out. Please, upgrade now.

**Comment by patoberli** [comment]
It sadly didn't work. I've uninstalled ntopng now and reinstalled it and now it's working again.
