### ISSUE TITLE
Question regarding lua/rest/v1/get/host/active.lua

### ISSUE THREAD

**Issue by TimotheusBachinger** [ntop/ntopng#4904]
Hi ntop Team,

we are currently wondering what is meant with "active hosts", which are delivered from lua/rest/v1/get/host/active.lua.
The list of hosts differs to the hosts we're seeing in ntopng under lua/hosts_stats.lua.

What we would actually need, is a list of hosts, which is known by ntopng.
Is this data already delivered by the REST API?

Regards
Timi

**Comment by simonemainardi** [comment]
Data returned should be identical as they call the same Lua functions.

1. Are you properly passing pagination options? See perPage and currentPage.
2. Give additional details on the differences. Again make sure you fetch all the data using params above.

**Comment by TimotheusBachinger** [comment]
regarding 1. we didn't use pagination as we want to query all know hosts in ntop. I've tried using the `all` bool and `mode=all` but I didn't received all hosts. only if I set perPage to e.g 10.000 I will receive all hosts. If i query after using perPage=10000 with no parameters, I will again receive all hosts, which is imo not expected.

**Comment by simonemainardi** [comment]
You should consider using pagination. Fetching all hosts in a single call may end up in slowing everything down, and creating huge HTTP responses.

In the api response, you have the total number of records. You should use it, along with the aforementioned parameters, to fetch everything, one chunk at time.

**Comment by TimotheusBachinger** [comment]
Pagination is not really an option for our use-case. We really need *all* currently known hosts in ntop in order to map checkmk hosts to ntop hosts. we will cache this data, so a "huge" response is no problem.

We are also seeing strange behaviour with active.lua. From time to time we cannot access the data at all:
`https://host:3000/lua/http_status_code.lua?message=not_foundreferer=ntop4.lan.tribe29.com%3A3000%2Flua%2Frest%2Fv1%2Fget%2Fhost%2Factive.lua%26ifid%3D2&error_message= `

We're on version 4.2.210112 (12754)

**Comment by TimotheusBachinger** [comment]
Another approach would be to have another REST call (or a query parameter) which returns **only** the currently known hosts and their IP addresses. 
`active.lua` has a lot of overhead, we are not needing for this purpose:
![image](https://user-images.githubusercontent.com/57113191/106429987-81639f00-646b-11eb-93b9-ef72a1db2374.png)
What do you think?

**Comment by simonemainardi** [comment]
Sure. We have an endpoint for that. You can ask just for the IP address and name as follow (and get all the records).

Example:

```
$ curl -s -u admin:admin1 -H "Content-Type: application/json"  -H "Content-Type: application/json" -d '{"ifid":"0", "field_alias":"ip,name"}' http://127.0.0.1:3000/lua/rest/v1/get/host/custom_data.lua
```

Response

```
{
	"rc_str": "OK",
	"rc_str_hr": "Success",
	"rc": 0,
	"rsp": [{
		"ip": "192.168.2.225",
		"name": "develv5"
	}, {
		"ip": "224.0.0.251",
		"name": ""
	}, {
		"ip": "fe80::142f:b346:f0f6:3bce",
		"name": "fe80::142f:b346:f0f6:3bce"
	}, {
		"ip": "192.168.2.131",
		"name": ""
	}, {
		"ip": "0.0.0.0",
		"name": "NoIP"
	}, {
		"ip": "fe80::ae1f:6bff:fead:6a2c",
		"name": "fe80::ae1f:6bff:fead:6a2c"
	}, {
		"ip": "192.168.2.153",
		"name": ""
	}, {
		"ip": "fe80::ec4:7aff:fecc:c44a",
		"name": "fe80::ec4:7aff:fecc:c44a"
	}, {
		"ip": "192.168.2.222",
		"name": "devel"
	}, {
		"ip": "224.0.0.2",
		"name": ""
	}, {
		"ip": "192.168.2.141",
		"name": ""
	}, {
		"ip": "192.168.2.140",
		"name": "MacBookPro"
	}, {
		"ip": "192.168.4.255",
		"name": ""
	}, {
		"ip": "239.255.255.250",
		"name": ""
	}, {
		"ip": "ff02::1:2",
		"name": "ff02::1:2"
	}, {
		"ip": "192.168.2.1",
		"name": "ubnt"
	}, {
		"ip": "192.168.2.255",
		"name": ""
	}, {
		"ip": "fe80::c15:e3f4:5b2d:cc41",
		"name": "Simones-MacBook-Pro [IPv6]"
	}, {
		"ip": "224.0.0.68",
		"name": ""
	}, {
		"ip": "142.250.180.131",
		"name": ""
	}, {
		"ip": "192.168.2.43",
		"name": ""
	}, {
		"ip": "ff02::fb",
		"name": "ff02::fb"
	}, {
		"ip": "192.168.6.7",
		"name": ""
	}, {
		"ip": "192.168.4.33",
		"name": "Simones-MacBook-Pro"
	}, {
		"ip": "192.168.2.146",
		"name": ""
	}, {
		"ip": "fe80::cb9:a3f6:ff65:5b21",
		"name": "fe80::cb9:a3f6:ff65:5b21"
	}, {
		"ip": "ff02::16",
		"name": "ff02::16"
	}, {
		"ip": "fe80::ffa2:e6be:847f:86f7",
		"name": "fe80::ffa2:e6be:847f:86f7"
	}, {
		"ip": "fe80::5054:ff:fe31:4156",
		"name": "fe80::5054:ff:fe31:4156"
	}, {
		"ip": "fe80::1c6e:ed0e:32a4:6045",
		"name": "mastromac [IPv6]"
	}, {
		"ip": "fe80::ec4:7aff:fecc:bd40",
		"name": "fe80::ec4:7aff:fecc:bd40"
	}, {
		"ip": "fe80::ec4:7aff:fecc:4c53",
		"name": "fe80::ec4:7aff:fecc:4c53"
	}, {
		"ip": "192.168.3.34",
		"name": ""
	}, {
		"ip": "fe80::225:90ff:fed4:c88c",
		"name": "fe80::225:90ff:fed4:c88c"
	}, {
		"ip": "255.255.255.255",
		"name": "Broadcast"
	}, {
		"ip": "fe80::20d:b9ff:fe59:3445",
		"name": "fe80::20d:b9ff:fe59:3445"
	}, {
		"ip": "192.168.2.44",
		"name": ""
	}, {
		"ip": "85.199.214.99",
		"name": ""
	}, {
		"ip": "192.168.2.169",
		"name": ""
	}, {
		"ip": "1.1.1.1",
		"name": ""
	}, {
		"ip": "192.168.2.142",
		"name": "mastromac"
	}]
}
```

**Comment by TimotheusBachinger** [comment]
That's what I was looking for! Great! Thanks!
