### ISSUE TITLE
New device connection alert reset

### ISSUE THREAD

**Issue by djha983** [ntop/ntopng#4905]
Hi,

I have enabled New device connection alert and is working fine.I want to know how it works.Is it considering the time since ntopng started monitoring interface to decide whether this device is new and on what basis it says new device? is it MAC address or other property of device.When does this learning is reset and how.Consider if we want to reset the learning of existing device how do i do?

**Comment by MatteoBiscosi** [comment]
Hello,
If you are talking about the "Unexpected device connected" alert, it decides if a device is a new one using MAC Addresses. It is possible to reset the learned MAC Addresses by going into Settings->User Scripts->Interfaces and search for the alert, then click the modify action and click the button "Reset Learned Devices". The learned devices are considered from the last reset of them, so even if you restart ntopng they won't reset.
