### ISSUE TITLE
ServicePeriodicity Map button must be shown all the time

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4906]
![Screen Shot 2021-01-13 at 16 35 31](https://user-images.githubusercontent.com/4493366/104473563-6533b700-55bd-11eb-831b-c880c5d4c9b3.png)

**Comment by gabryon99** [comment]
Now the dropdown button is always shown as requested. Check the pro repository

**Comment by lucaderi** [comment]
<img width="1090" alt="Screenshot 2021-01-14 at 09 22 05" src="https://user-images.githubusercontent.com/4493366/104563488-01a39b00-564a-11eb-9295-13405ca9c5ee.png">
Not quite. They must be shown all time and you should resize the internal map, not hide them.

**Comment by lucaderi** [comment]
Verified as fixed
