### ISSUE TITLE
Add service/periodicity map to VLANs and Host Pools

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4907]
VLAN and Host Pools pages must have (if defined) an icon that points to the corresponding service/periodicity map for such VLAN/pool

**Comment by lucaderi** [comment]
From a host pool clicking on the service map brings here, but as you can see the menu is not populated with pools. 

![Screen Shot 2021-01-15 at 11 57 35](https://user-images.githubusercontent.com/4493366/104716939-e22f6f80-5728-11eb-9cd8-d2afadd0f41b.png)

See also #4908

**Comment by simonemainardi** [comment]
VLAN links are not correct - VLAN is missing

![image](https://user-images.githubusercontent.com/3397663/107960853-6cc3f280-6fa5-11eb-9ead-9d94d72eebdb.png)

![image](https://user-images.githubusercontent.com/3397663/107961125-c2000400-6fa5-11eb-8197-522cd209ec0e.png)

**Comment by simonemainardi** [comment]
Host Pool link is greyed out even though valid and with existing services

![image](https://user-images.githubusercontent.com/3397663/107962465-469f5200-6fa7-11eb-9577-ad87f50bb3d7.png)

**Comment by simonemainardi** [comment]
This is still broken:

![image](https://user-images.githubusercontent.com/3397663/108087827-170c4a80-7078-11eb-8463-999905436adb.png)

Clicking on "Client"  brings to an invalid, empty page (note that the breadcrumb is different as well)

![image](https://user-images.githubusercontent.com/3397663/108087922-32775580-7078-11eb-91d7-e4aa3f4a15dc.png)

Moreover, breadcrumb url is still bugged

![image](https://user-images.githubusercontent.com/3397663/108088139-6c485c00-7078-11eb-8ab5-00be22c32739.png)

**Comment by lucaderi** [comment]
The breadcrumb does not update with VLAN, but the VLAN is shown in the filtering menu so I believe this ticket is fixed
