### ISSUE TITLE
Add service/periodicity map dropdown menu

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4908]
In order to simplify and reduce rendering, maps must have in the upper side a dropdown menu that shows
- all hosts (default as today)
- unicast hosts only
- In case there are VLAN defined, individual entries one per VLAN
-  In case there are host pools defines, the individual host pools menu

**Comment by gabryon99** [comment]
Done. Check the pro repository, please.

**Comment by lucaderi** [comment]
This issue depends on https://github.com/ntop/ntopng/issues/4911

Furthermore I don't see the link to the service map for this 
<img width="1188" alt="Screenshot 2021-01-14 at 09 16 41" src="https://user-images.githubusercontent.com/4493366/104563127-8fcb5180-5649-11eb-9db5-6dbc54d7a6ac.png">

**Comment by lucaderi** [comment]
![Screen Shot 2021-01-15 at 11 52 43](https://user-images.githubusercontent.com/4493366/104716442-3b4ad380-5728-11eb-94d3-e4c8c644d650.png)

VLAN filtering is present but pool filtering is not. Can you please add it so we can close this ticket?

**Comment by gabryon99** [comment]
Now the host pool entries are visibile as well. If a service/periodicity map of an host pool has length equals to 0 then the menu entry won't be selectable.
