### ISSUE TITLE
ntopng setup for windows

### ISSUE THREAD

**Issue by J101** [ntop/ntopng#491]
hi may you please guide me on how to setup ntopng on my windows?

i cant understand on where will i input the commands below.
![adfasfdsaf](https://cloud.githubusercontent.com/assets/18482239/14559287/2cae76c0-033a-11e6-8873-a361ebf010fb.PNG)

**Comment by simonemainardi** [comment]
I have extended the UserGuide with windows docs. Please refer to the following pdf: https://github.com/ntop/ntopng/blob/dev/doc/UserGuide.pdf
