### ISSUE TITLE
Add edit button to host pools

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4916]
![Screen Shot 2021-01-15 at 11 55 52](https://user-images.githubusercontent.com/4493366/104717076-130fa480-5729-11eb-995d-b30e49ad356f.png)

**Comment by MatteoBiscosi** [comment]
@VasilisTako please check the edit button disabled when editing and after been fixed please close the ticket

**Comment by lucaderi** [comment]
Verified as fixed
