### ISSUE TITLE
Documentation  ntopng/doc/README.SSL is not clear

### ISSUE THREAD

**Issue by harmonicus** [ntop/ntopng#4917]
In documentation states 

```
1.2 Create your SSL certificate

		inside the ntopng folder execute the command: make cert
		and follow the instruction

```

first, i suppose it should point where is ntopng directory, which is described further
`/usr/share/ntopng` or at `/usr/local/share/ntopng`

second, command : `make cert` does not work
it does not work neither, within `openssl` program in terminal,

```
OpenSSL> make cert
Invalid command 'make'; type "help" for a list.
error in make
```

what is missing?

**Comment by lucaderi** [comment]
You need to execute "make cert" where is the ntopng source code. This applies only to ntopng from GIT. Certificates go here https://github.com/ntop/ntopng/tree/dev/httpdocs/ssl
