### ISSUE TITLE
Custom alert severity

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#4919]
Hi 
Depending the use case of ntopng, the alarm severity of alerts may vary.
E.g. for a detected MAC / IP address change I would like to have it as an alarm, not debug:
![2021-01-16 14 49 09](https://user-images.githubusercontent.com/38549755/104813548-1b8bdc00-580a-11eb-99bf-6392022ee02b.png)

**Comment by simonemainardi** [comment]
For your use case, you can edit the script and and use `set_severity` to choose the severity you want to set

**Comment by lucaderi** [comment]
@MatteoBiscosi Please take care of the ticket by specifying the severity in the plugin so users can change it as needed

**Comment by simonemainardi** [comment]
Implementation needs to be done as follow:

- User scripts that generate alerts have a flag in their metadata: `is_alert = true`. For all those scripts, add an extra `severity` inside metadata `default_value` table.
- `default_value` field `severity` must be populated with what is currently called as `set_severity` parameter. For example, if  the script has `alert:set_severity(alert_severities.error)`, default value will be `default_value.severity = alert_severities.error`
- Call to `set_severity` must be replaced with the config value that is the union of the default value and a possible UI-configured value (done later). E.g., in a `function script.hooks.min(params)`, the new severity will be available as  `params.user_script_config.severity`. Use this to call set_severity, e.g., `alert:set_severity(params.user_script_config.severity)`.
- Also flow user scripts have their default value, e.g., see `flow_risks.lua`. Configuration is the second parameter passed to hook, e.g., see `function script.hooks.protocolDetected(now, conf)`.

This concludes the backend part. For the frontend:

- Add a dropdown populated using `alert_severities` for all the user scripts that have a `is_alert = true`. 
- Dropdown default value is read from `default_value.severity` implemented above
- Changing the default value will properly set the new severity to the user script, severity which will be passed in `params.user_script_config.severity`

**Comment by simonemainardi** [comment]
This is partial, severity cannot be edited/changed for any of the following guys.


Local Networks
SNMP Devices
Flows
System
Syslog



![image](https://user-images.githubusercontent.com/3397663/106025862-786c7980-60c9-11eb-809e-8cd2b7983b90.png)


make sure severity is editable for ANY of the user script that say "is_alert=true"

**Comment by simonemainardi** [comment]
Layout is broken

![image](https://user-images.githubusercontent.com/3397663/106129943-0cd5eb00-6161-11eb-821d-7c4f9a2c83da.png)


Impossible to edit the severity for disabled scripts (this forces the user to enable a script, and then to go to the enabled scripts page and change the severity)

![image](https://user-images.githubusercontent.com/3397663/106130115-49094b80-6161-11eb-93dd-f56e074ed550.png)

I think desired behavior, for all disabled scripts, is NOT to have the edit button and only have the enable button. Clicking on enable, the toast opens and one can configure the severity or other params.

**Comment by gabryon99** [comment]
Fixed the layout of the Elephant Flows user script

**Comment by simonemainardi** [comment]
broken

![image](https://user-images.githubusercontent.com/3397663/106141971-28e18880-6171-11eb-83ba-39dc1081d254.png)

missing

![image](https://user-images.githubusercontent.com/3397663/106141987-30089680-6171-11eb-9c48-f50cebc012d4.png)

please let me know if you can do an exhaustive check across all scripts or if you need me to add a screenshot for every single script that is broken.

**Comment by gabryon99** [comment]
Checked each single template and fixed the broken layout.

**Comment by simonemainardi** [comment]
not really.


Missing

![image](https://user-images.githubusercontent.com/3397663/106148261-22efa580-6179-11eb-9e53-a88d38004664.png)

Missing

![image](https://user-images.githubusercontent.com/3397663/106148336-3995fc80-6179-11eb-885c-30d7b966660d.png)

Moreover:

error is reported two times

![image](https://user-images.githubusercontent.com/3397663/106148440-55999e00-6179-11eb-9880-b688268131a1.png)

> I think desired behavior, for all disabled scripts, is NOT to have the edit button and only have the enable button. Clicking on enable, the toast opens and one can configure the severity or other params.

what about this?

**Comment by simonemainardi** [comment]
now the layout is fixed for all user scripts.

> I think desired behavior, for all disabled scripts, is NOT to have the edit button and only have the enable button. Clicking on enable, the toast opens and one can configure the severity or other params.

This will be handled separately
