### ISSUE TITLE
ELK integration

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#4920]
Hi
Using ELK as an alarm recipient, I see event.severity 4 and 5, but not less. Choosing "debug" as minimum severity, shouldn't I see event.severity 1-5?
<img width="572" alt="Screenshot 2021-01-16 at 14 53 13" src="https://user-images.githubusercontent.com/38549755/104813619-96ed8d80-580a-11eb-9db8-05f571dfcdd3.png">

**Comment by simonemainardi** [comment]
Correct. You should see everything.

**Comment by martinscheu** [comment]
ok, thanks Simone. Any idea why its like that?

**Comment by simonemainardi** [comment]
@MatteoBiscosi please try and reproduce.

**Comment by simonemainardi** [comment]
I am getting correct severities with my ES datasource (see severity = 2)

![image](https://user-images.githubusercontent.com/3397663/105049053-8c323300-5a6c-11eb-89c0-672e9f197962.png)

![image](https://user-images.githubusercontent.com/3397663/105048965-77559f80-5a6c-11eb-82ac-4073a7f3cbe2.png)

**Comment by simonemainardi** [comment]
I get proper severities also if I use Discord

![image](https://user-images.githubusercontent.com/3397663/105049552-0f538900-5a6d-11eb-900f-0b648e19378b.png)

**Comment by MatteoBiscosi** [comment]
Tried even on Telegram and still no issue.
![Screenshot from 2021-01-19 15-59-32](https://user-images.githubusercontent.com/49585191/105051874-7d994b00-5a6f-11eb-8d66-c88a8b5a1eba.png)

**Comment by martinscheu** [comment]
@simonemainardi , @MatteoBiscosi thanks for checking. what confuses me, is that I had different use numbers:
<img width="271" alt="Screenshot 2021-01-19 at 16 57 13" src="https://user-images.githubusercontent.com/38549755/105061270-9f97cb00-5a79-11eb-8e65-02cdd323240f.png">
with that I check configuration in e.g. in flow Pools all recipients checked, but now rechecking it was only the build in selected.
Could it be that additional to default values (the recipient selection) got lost?
<img width="870" alt="Screenshot 2021-01-19 at 17 09 05" src="https://user-images.githubusercontent.com/38549755/105061027-4fb90400-5a79-11eb-8a6f-01f38d02b774.png">
thanks. After selecting in all Pools I get all alarm severity items.
