### ISSUE TITLE
fill width of page geomap

### ISSUE THREAD

**Issue by travisboss** [ntop/ntopng#4922]
![ntopng](https://user-images.githubusercontent.com/16948721/104829717-ffa12e00-583b-11eb-996a-d15fc5495e14.jpeg)

Included photo, not sure if I can do this myself, will if needed but noticed if the width is changed to `width: 100%` we can get a full width on the map inside of that tiny box.  This is on the `#map-canvas` id, I am using this within pfsense which I know is an older version, and not sure if they have there own version?

**Comment by simonemainardi** [comment]
Version installed is no longer supported.  Please, update to version 4.2.
