### ISSUE TITLE
No data available in App Breakdown (Traffic reports)

### ISSUE THREAD

**Issue by amastelek** [ntop/ntopng#4923]
Using nprobe IPFIX -> NTOPNG
The graph in Traffic reports labelled Application Breakdown reports No Data Available

Using 4.2 stable

**Comment by amastelek** [comment]
Also Top Application Traffic Last Day View in the main dashboard has no data???

**Comment by simonemainardi** [comment]
Do you have this enabled?

![image](https://user-images.githubusercontent.com/3397663/104909592-5e73be00-5988-11eb-81dc-1a76d702f481.png)

**Comment by amastelek** [comment]
No, because it said in general it is not needed?

I have enabled it.  Will check in a while to see if it has pulled through.

**Comment by simonemainardi** [comment]
To have top-applications, you must have them written by ntopng.
