### ISSUE TITLE
Disaggregation interrupts dump-flow to Elasticsearch

### ISSUE THREAD

**Issue by AlexDF2017** [ntop/ntopng#4924]
hi all, we have the following chain:  network_devices<-(netflow)->nprobe<-(zmq)->ntopng<-(dump-flows)->Elasticsearch. All is ok (included Elasticsearch flow dumps) until in ntopng we set Dynamic Traffic Disaggregation from none to Probe IP, after this change in ntopng we can find the correct subinterfaces, but no flows are dumped to Elasticsearch anymore. What's happening? 

We are using
- ntopng v.4.2.210115 (Professional license)
- nprobe v.9.2.210115 (Pro license)
- Elasticsearch v7.10.2

Alex

**Comment by simonemainardi** [comment]
- Make sure to update to the latest stable version.
- Make sure to restart ntopng once you have set up Probe IP disaggregation

Elasticsearch export works properly

![image](https://user-images.githubusercontent.com/3397663/105031099-166e9d00-5a55-11eb-8b60-82779890e895.png)

Exported flows increase. And they end up in ES

![image](https://user-images.githubusercontent.com/3397663/105031354-7feeab80-5a55-11eb-915b-926a02975881.png)
