### ISSUE TITLE
Custom Application conflicting with built in Application

### ISSUE THREAD

**Issue by morefigs** [ntop/ntopng#4925]
I'm running ntopng with a custom application (via protos.txt). Detection of my custom application seems to work well with the exception that it can get confused with built in applications. This obviously has something to do with the host defined for the  built in applications overlapping with the custom application.

For example, given this custom protos.txt:

```
# My protos.txt
host:"google.com",host:"www.google.com"@_TestingGoogleComByHostname
```

then I would hope _all_ relevant Google traffic would be recognised under the `_TestingGoogleComByHostname` application. However, sometimes it is flagged under the built in application `Google`, see pic:

![image](https://user-images.githubusercontent.com/2002487/104859640-e357db00-597a-11eb-9d1a-b6e87ebd6281.png)

Is there a way around this? Is there a way to disable the built in applications altogether?

PS. The deeper reason for this is that I want to enable fine grained whitelisting of specific subdomains, e.g. whitelist sub1.google.com but not www.google.com. I don't want these specific subdomains to be confused with the wider scope of the built in `Google` application.

**Comment by lucaderi** [comment]
This is a ticket for nDPI not for ntopng and as Google is already natively detected at https://github.com/ntop/nDPI/blob/dev/src/lib/ndpi_content_match.c.inc#L8814 all you are asking is not possible.
