### ISSUE TITLE
Problem Networks View

### ISSUE THREAD

**Issue by NicolasPSQ** [ntop/ntopng#4926]
Hi,
when i'm on "Network" views, with filter of 10 records, and i select on "next page" i view only 1 record, despite i have more than 11 records (networks).

Regards

ntopng Enterprise M v.4.3.210118 (Ubuntu 20.04.1 LTS)

**Comment by simonemainardi** [comment]
@MatteoBiscosi please, try and reproduce. Add 15+ networks in `-m` and see.

**Comment by NicolasPSQ** [comment]
Hi, update done, but the problem is still present.

**Comment by simonemainardi** [comment]
new builds are being generated. Please wait a couple of hours and then update.
