### ISSUE TITLE
No ports in graph on any hosts

### ISSUE THREAD

**Issue by amastelek** [ntop/ntopng#4928]
![ports](https://user-images.githubusercontent.com/61453908/104949805-386e0e00-59c8-11eb-9147-b1175f35e85e.jpg)
None of the hosts display any port information?

**Comment by simonemainardi** [comment]
Please, attach a screenshot of the flows page and the configuration of ntopng

**Comment by amastelek** [comment]
![ntopngflows](https://user-images.githubusercontent.com/61453908/104995239-a51bf380-5a2e-11eb-96dc-b3462c9475cb.jpg)

Config is attached.
[configuration.zip](https://github.com/ntop/ntopng/files/5833989/configuration.zip)

**Comment by simonemainardi** [comment]
There are no flows, so having all-zero ports is normal - they are not populated. I am mot sure you are getting traffic for this interface. Check the non-disaggregated one.

**Comment by amastelek** [comment]
Yes, my disaggregation configuration was incorrect.  Tx
