### ISSUE TITLE
multiple nprobe-none.conf files

### ISSUE THREAD

**Issue by amastelek** [ntop/ntopng#4930]
Is it possible to have multiple nprobe-none.conf files so that I can have each collector port associated with a different ZMQ instead of having to start multiple nprobes from the command line?

**Comment by simonemainardi** [comment]
See https://www.ntop.org/guides/nprobe/how_to_start.html

Please check the documentation before posting issues.

**Comment by amastelek** [comment]
Thanks I created nprobe-none1.conf, nprobe-none2.conf, and nprobe-none3.conf.
