### ISSUE TITLE
Problem between SNMP and Nprobe NTOPNG

### ISSUE THREAD

**Issue by astalush** [ntop/ntopng#4931]
Hy. I have a problem/question : we had a problem with a ethernet interface that sent iperf traffic at full 1 gbit. On snmp when we looked over that interface we had seen that big traffic on that switch (interface Gi1/35) but when we looked through the nprobe that traffic was not there. Can you please see what can be the problem? The sflow is activated on that interface (Gi1/35) but nprobe didn't see that traffic.

![traffic via nprobe ntopng](https://user-images.githubusercontent.com/8401863/105043768-39557d00-5a66-11eb-89b6-b17b3dadb111.png)
![snmp S-3048](https://user-images.githubusercontent.com/8401863/105043781-3b1f4080-5a66-11eb-8471-ac0bb3be2668.png)

Also via select nprobe and select sflow exporter I can see that traffic but like I said I don't see in real time via nprobe.
![sflow device](https://user-images.githubusercontent.com/8401863/105049016-83416180-5a6c-11eb-9152-f5d2b89149a5.png)

**Comment by simonemainardi** [comment]
Likely, your sFlow is not properly configured to send sFlow packet samples. Indeed, counter samples looks good as they show data.

- Check sFlow configuration
- Attach full page screenshots (including page headers) as screenshots

**Comment by astalush** [comment]
Sflow configuration on the Dell switch or the nprobe conf? 
On the Dell I have :
sflow 1 destination IP PORT
sflow 1 destination owner SSTR notimeout 
sflow 1 polling gi1/0/1-24 30
sflow 1 sampling gi1/0/1-24 1024

nprobe conf  : 
-W
--collector-passthrough
--zmq="tcp://*:5580"
--collector-port=2080
-n=none
-i=none
-V 9
-g=/var/run/nprobe-91.pid
--tunnel
-T="%TCP_FLAGS %IPV4_NEXT_HOP %OUT_BYTES %LAST_SWITCHED %IN_PKTS %IN_BYTES %FIRST_SWITCHED %OUT_PKTS %IPV4_SRC_ADDR %SRC_VLAN %DST_VLAN %IPV4_DST_ADDR %IPV4_SRC_MASK %IPV4_DST_MASK %L4_SRC_PORT %L4_DST_PORT %IPV6_SRC_ADDR %IPV6_DST_ADDR %IPV6_SRC_MASK %IPV6_DST_MASK %IP_PROTOCOL_VERSION %SRC_TOS %PROTOCOL %ICMP_TYPE %INPUT_SNMP %SRC_AS %DST_AS %IPV4_N %EXPORTER_IPV4_ADDRESS %FLOW_ID %TOTAL_BYTES_EXP %TOTAL_PKTS_EXP %TOTAL_FLOWS_EXP %IN_SRC_MAC %OUT_DST_MAC %IN_DST_MAC %OUT_SRC_MAC %INTERFACE_NAME %DOT1Q_SRC_VLAN %DOT1Q_DST_VLAN %POST_NAT_SRC_IPV4_ADDR %POST_NAT_DST_IPV4_ADDR %POST_NAPT_SRC_TRANSPORT_PORT %POST_NAPT_DST_TRANSPORT_PORT$
--event-log /var/log/nprobe/nprobe-91_log.log
-b 2


![sflow 1 not showing all traffic](https://user-images.githubusercontent.com/8401863/105053564-5f344f00-5a71-11eb-8385-83b13b435ad6.png)
![sflow via sflow exporters](https://user-images.githubusercontent.com/8401863/105053567-60657c00-5a71-11eb-8c0f-5918aedb51ef.png)
![via snmp](https://user-images.githubusercontent.com/8401863/105053570-60fe1280-5a71-11eb-8e0d-46f8f55fa5f0.png)

**Comment by astalush** [comment]
Any ideas? When you look the sFlow Device the data sent by the dell switch is there, so why ntopng didn't capture it into the traffic dashboard?

**Comment by astalush** [comment]
And there is a problem, look at this : the connection between the wikiii machine (where this speedtest is located) and the PVLT370901 machine (from where I launched the speedtest) doesn't show the real speed, it only shows 2mbps (First SS). When I look into the dashboard when I see this wikii machine (the speedtest machine) top local talkers it's the same, not showin g the good speeds. (second SS°

![not showing the speed](https://user-images.githubusercontent.com/8401863/105155533-044f3600-5b0b-11eb-80d2-9edf67a3ab57.png)
![dashboard not showing good speed](https://user-images.githubusercontent.com/8401863/105156178-c6064680-5b0b-11eb-9c22-5ef62922926d.png)

**Comment by simonemainardi** [comment]
I am not familiar with the sFlow configuration indicated. However, my guess is that the sFlow flow samples are not properly sent to nProbe. Can you please check this.

Also remove `-V 9 --tunnel` as they may not be needed.

**Comment by astalush** [comment]
The -- tunnel option is there because we have Aerohive Wi-Fi Hotspots and if I delete this option all traffic from those Wi-Fi Hotspot is encrypted and I can only see traffic from there but not who's making that traffic. 

The sflow configuration is the one taken from the Dell site.

Into the last photo you can see the traffic but the speeds are not the same. It says the source and the destination (so the sFlow setup must be good) but the speed isn't the same. You can see that.

**Comment by astalush** [comment]
And how can I capture the sFlow to see how they are transmitted? Thanks.

**Comment by simonemainardi** [comment]
So, basically, you are looking at sampled sFlow traffic. There's a delay + upscaling. 

Let's have a look at the total first. Is the total flow traffic comparable to the total traffic generated by the speedtest? I'm telling comparable as sFlow is sampled by nature so cannot be exact.

**Comment by simonemainardi** [comment]
any news?

**Comment by astalush** [comment]
I've created another CentOS machine and I will test, maybe it was something with the old one.  I know that sFlow isn't instant but the speedtest lasts more than one minute (I've set it up like that) so I can see the flow. And like I said the speeds are very different. I will keep you posted. Thanks.

**Comment by cardigliano** [comment]
Closing for the time being, please reopen in case you are still able to reproduce it. Thank you.
