### ISSUE TITLE
Possibility to filter out flows with a certain DSCP value in ntopng

### ISSUE THREAD

**Issue by Niklasr69** [ntop/ntopng#4933]
New feature request to ntopng:
From the flow view, it is possible today to filter out flows with different characteristics, examples protocol, application etc.
Lacks the ability to filter out flows with a certain DSCP value.
Would be great if it could be introduced, even in the history part it would be very valuable.

**Comment by simonemainardi** [comment]
To implement:

- extend lua function `getFlowsFilter()` with another `GET["dscp"]` accepting an integer. A new `pageinfo["dscpFilter"]` will be returned.
- Edit `src/Paginator.cpp` to parse the the `pageinfo["dscpFilter"]`. Note that dscp is an `u_int8_t` that needs to be initialized to `(u_int8_t)-1` and only set when `dscpFilter` is present.
- Extend `static bool flow_matches` to keep into account the new dscp filter
- Add an extra dropdown DSCP in the active flows page. Populate the dropdown with only existing DSCP values among active flows. Use `dscp_consts.dscp_descr` to print human-readable names for integer DSCP values
- Final dropdown will contain available DSCP values and their counts between parentheses as for example in 

![image](https://user-images.githubusercontent.com/3397663/105984764-e0579b80-609a-11eb-934c-1d09dde2078f.png)

**Comment by simonemainardi** [comment]
please, check as counters seem to be doubled

**Comment by simonemainardi** [comment]
implemented as requested

![image](https://user-images.githubusercontent.com/3397663/106177658-12e7be00-6199-11eb-85f6-fb2ad421dbc9.png)
