### ISSUE TITLE
Compare non time-based data with pie/donut and bar chart

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4934]
It is requested to implement the ability to create a widget where one or MORE (let's say up to 10) datasource are specified and data is compared.

Caveat
- the number of slices and their order MUST be identical
- Implement the concept of "other" for too-may slices
- The "Other" must be ALIKE in the datasources so that it is possible to compare data
- Colors must be static and should NOT change ACROSS reloads

**Comment by simonemainardi** [comment]
This is implemented. Will be documented when widgets implementation is completed.
