### ISSUE TITLE
Unable to activate "community mode" on v4.3.210120 / opnsense (box is unchecked every time)

### ISSUE THREAD

**Issue by meepmeep** [ntop/ntopng#4935]
I just upgraded my opnsense installation to OPNsense 20.7.8, and the ntopng package have been upgraded to "4.3.210120".
In this version, the "community mode" must be activated on the web page : https://host/ui/ntopng/license, 
Except  is doesn't work:

**If I check the box, and refresh the page, the box is shown empty.** 
I try to "check / save / refresh", or even "stop ntop / save / check the box / save / start ntopng". Still unchecked and ntopng is started without the community mode.

On version 4.3.210118 (from opnsense 20.7.7), the "community box" is on page https://host/ui/ntopng/general/index, and it works normally.

(and btw you should really create a licence for advanced but not professsionel user -without support, only additionnal features-, i'll gladly get one.)

**Comment by cardigliano** [comment]
@meepmeep could you try updating the plugin to today's version and let us know?

**Comment by meepmeep** [comment]
It works with the version 4.3.210121 (except that you still don't show the expanded menu on the left, but it's not really important).

Thanks :)
