### ISSUE TITLE
Add missing button hover on flow alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4938]
![Screen Shot 2021-01-21 at 10 40 28](https://user-images.githubusercontent.com/4493366/105348604-dd673180-5be8-11eb-817b-e458cebd5085.png)

**Comment by lucaderi** [comment]
Ok for explorer, still missing for the delete button. Better to add the hover to all buttons (include past alerts) then close this ticket

**Comment by simonemainardi** [comment]
Verified as implemented.
