### ISSUE TITLE
Flow Alerts: Add L7 Column and Filter Menu

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4941]
In the flow alerts it is requested to add a new column with the L7 protocol, and a new filtering menu for selecting only those events of the selected L7 protocol. By default the  L7 protocol menu is set to All

**Comment by simonemainardi** [comment]
To implement:

- Contents of column "Drilldown" will become, when available, an extra button with the magnifier lens (`fa-search-plus`) under the "Actions" column. This holds for all alerts, including flow alerts. e.g.

![image](https://user-images.githubusercontent.com/3397663/105983663-58bd5d00-6099-11eb-8485-97ea14a56dff.png)

- Remove column "Drilldown" in non-flow-alert tables
- Replace column "Drilldown" with `column_ndpi` (use this name) in the "Flow Alerts" table. The column will contain the same identical information of what is currently shown in the "Application" column of the active flows page.


![image](https://user-images.githubusercontent.com/3397663/105974293-0cb8eb00-608e-11eb-9a25-7b263f1a58e3.png)

- Use the same function currently used in the active flows page to format/color/add icons to the application
- Adding the extra colum can cause the "delete" button to no longer work. Make the necessary adjustments
- Note that the Flow Alerts table appears also under the host alerts page. Check and make sure this also works.
- For the dropdown filter, only show applications that have a count >= 1, sorted alphabetically, and show the count between parentheses. Basically, look at the code and do the same identical thing as what is currently done for the types

![image](https://user-images.githubusercontent.com/3397663/105974606-5d304880-608e-11eb-9843-928fd37746c7.png)

**Comment by simonemainardi** [comment]
for the protocol, let's reproduce the behavior currently used for flows dumped to database:

- use only `f->get_detected_protocol().app_protocol` that you should have in `l7_proto`
- use `interface.getnDPIProtoName(<protocol id>)` to get the protocol string

**Comment by lucaderi** [comment]
Verified as implemented
