### ISSUE TITLE
Add label to local networks

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4945]
As of today networks added vi -m are unlabelled.

It i requested to add an (optional) label as
-m "192.168.1.0/24=home network,172.16.0.0/16,10.0.0.0/8=legacy network"

Labels will be used in the /lua/network_stats.lua page

**Comment by simonemainardi** [comment]
Implementation will be as follows:

- Check the parsing of local networks and edit `Ntop::addLocalNetwork` to check if there is a `=<label>`
- Add a map in class `Ntop` that you can use as `local_network_names[id] = strdup(<label>)`. Populate this map in `Ntop::addLocalNetwork`, only for local networks that have a `=<label>`.
- extend `function getLocalNetworkAlias(network)` to first try and retrieve the alias stored `local_network_names`. Only look at the redis-stored alias if there is no alias stored in C
- Prevent networks with aliases set with  `=<label>` to have their alias changed. Basically, for those networks, the input field with the alias will be disabled and uneditable in this page. A note will explain the alias is configured in `-m`.

![image](https://user-images.githubusercontent.com/3397663/106168749-ee86e400-618e-11eb-8705-c65c7b1fb929.png)

- extend the ntopng help to explain how to set labels under `-m`

**Comment by lucaderi** [comment]
Verified as fixed

**Comment by simonemainardi** [comment]
- Not saving non-CLI aliases
- Show the foot note only when the alias is set from CLI. Otherwise hide it.
