### ISSUE TITLE
INPUT_SNMP and OUTPUT_SNMP ID

### ISSUE THREAD

**Issue by bogikornel** [ntop/ntopng#4946]
The snmp_input and snmp_output IDs are currently 16 bits. I want it to be 32-bit.

**Comment by cardigliano** [comment]
Fix provided in https://github.com/ntop/ntopng/commit/f2e64bb9eff939d9ad8568991f5b7c5cc42e1c87 a new package will be available later today

**Comment by bogikornel** [comment]
Will this be included in stable branch 4.2 or beta 4.3?

**Comment by cardigliano** [comment]
Both
