### ISSUE TITLE
save flows permanently in time series database.

### ISSUE THREAD

**Issue by junaid-soomro-ivolve** [ntop/ntopng#4947]
I have seen that there is an option in settings for timeseries. Which shows number of days before NTOP overwrites or removes the data from DB. How can i save this data permanently instead letting NTOP overwrite or remove it after N amount of days?

**Comment by simonemainardi** [comment]
You configure it from

![image](https://user-images.githubusercontent.com/3397663/105497327-f6421680-5cbe-11eb-9efb-1f63c3d47c64.png)

**Comment by junaid-soomro-ivolve** [comment]
i know that. That section says "by default it will store it for 30 days". I want to store data permanently. There is no option for that. That is my question. Should i leave it blank?

**Comment by simonemainardi** [comment]
Add a large value.
