### ISSUE TITLE
Add additional filter possibilities to maps

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#4948]
Hello,
In networks with 500 hosts or more, it would be helpful to have additional filter possibilities in the maps view.
Currently is "all" or "unicast" or "pool entry".
To handle lots of host it would be nice to have filter groups:
group 1 "all or unicast" 
group 2 "pool entries"
group 3 "Layer7"
Filter example: unicast of s7comm in the PLC pool
Thanks. 

Related to https://github.com/ntop/ntopng/issues/4940

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu this functionality is implemented by #4940
