### ISSUE TITLE
Resizing of maps window frame

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#4949]
Hello,
Currently it looks like the maps window frame has a max size:

<img width="2921" alt="Screenshot 2021-01-22 at 22 09 30" src="https://user-images.githubusercontent.com/38549755/105557161-d127c500-5d0b-11eb-844d-2772a04d31ff.png">

The frame containing the license info and uptime could be smaller, giving more space for the map itself.
Thank you

**Comment by gabryon99** [comment]
Add the possibility to change the height of the map container

https://user-images.githubusercontent.com/14114916/107929197-9e26c900-6f79-11eb-9590-cc34fea470ee.mov
