### ISSUE TITLE
Pool filter or selection on the flow page

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#4950]
Hello
Beside the interface selection it would be helpful to have a pool selection, in order to see only flows belonging to a pool.
Thanks.

**Comment by simonemainardi** [comment]
@MatteoBiscosi please add a dropdown with pools under the flows page

**Comment by simonemainardi** [comment]
bugged (at least with view interfaces):

![image](https://user-images.githubusercontent.com/3397663/109952937-b750a900-7cdf-11eb-87fc-97f5e8c1c074.png)

![image](https://user-images.githubusercontent.com/3397663/109952955-bcadf380-7cdf-11eb-9dc3-38b27f320983.png)

![image](https://user-images.githubusercontent.com/3397663/109952983-c3d50180-7cdf-11eb-9675-00dd5d10dcb9.png)

**Comment by simonemainardi** [comment]
bugged also with non-view-interfaces

![image](https://user-images.githubusercontent.com/3397663/109953143-f3840980-7cdf-11eb-8031-7180d7640d1a.png)

**Comment by simonemainardi** [comment]
Still bugged. When a filter is selected, all host pool counters in the dropdown are messed up and wrong. It's not true there is (1) flow for test pool


![image](https://user-images.githubusercontent.com/3397663/111273344-f9f57800-8633-11eb-89f6-8f5ce2e06784.png)

**Comment by MatteoBiscosi** [comment]
@simonemainardi  I was not able to reproduce this behaviour, could you please tell me how the pools are configured?

**Comment by simonemainardi** [comment]
![image](https://user-images.githubusercontent.com/3397663/111299837-b52c0a00-8650-11eb-99df-9e75d7693e61.png)

then ping 8.8.8.8
