### ISSUE TITLE
Not filter on flow page

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#4951]
Hello
It would be helpful to have a Filter != value possibility on the flow page.
I want to filter out DNS or availability / redundancy flows like CPHA or infrastructure flows like CAPWAP.
Thank you.

**Comment by lucaderi** [comment]
We'll implement as http://localhost:3000/lua/pro/enterprise/service_map.lua?page=graph&l7_proto=dns,ftp

**Comment by simonemainardi** [comment]
@MatteoBiscosi is this implemented?

**Comment by martinscheu** [comment]
Hello ntop - Team!
I think it is not implemented, but it would help a lot :-).
Thanks, Martin

**Comment by martinscheu** [comment]
is working great now, thanks for implementing!
