### ISSUE TITLE
[InfluxDB] "no data" issue in Grafana graphs if measurement fields are not initialized with 0

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#4952]
We are using Grafana to create some useful graphs with influxdb ntopng data.
On our ntopng configuration we have 8 interfaces and our goal is create some graphs where plot the data rate for some specific ndpi protocols (Teams, Dropbox, Microsoft365, ...).

Here one of these graphs:

![Screenshot_20210123_163103](https://user-images.githubusercontent.com/14093378/105606341-180fcc00-5d99-11eb-9620-9874328e6440.png)

Sometimes happens that a specific protocol is not used by the PCs connected to one of our monitored interfaces. In these cases I think that ntopng doesn't create any entry/field into the DB and the result is that Grafana print into the graphs "no data" or simply skip the query.

What we obtain is something like that:

![Screenshot_20210123_165248](https://user-images.githubusercontent.com/14093378/105606769-881f5180-5d9b-11eb-8f65-679356865bae.png)

We tried to use "fill(0)" in Grafana but when the entry is not saved into the DB this workaround is not useful.

Our big problem is that when we have a lot of graphs in the same page and some interfaces data are skipped for this "no data issue" the colors of the graphs become not coherent:

![Screenshot_20210123_170411](https://user-images.githubusercontent.com/14093378/105607100-3c6da780-5d9d-11eb-921f-6144309ca862.png)

As you can see in the Legend in the first graph we haven't the field that end with "om 2" ("no data") and all the colors after this field are not coherent with the second graph.

When in a page we have 10 or 15 graphs with this issue is very difficult to understand what happen in our networks... :-(
I red the documentation of Grafana but I haven't found any solution to this problem.

In my opinion the best solution would be check the DB when ntopng starts and verify that all the timeseries are created. If some timeseries are missing, ntopng should create them setting a value of 0...
This behavior  could be useful also into the ntopng graphs: sometime in the drop down menu near the graph we don't see some protocols and it's not clear if this is a bug/issue or not:

![Screenshot_20210123_173229](https://user-images.githubusercontent.com/14093378/105607758-0a5e4480-5da1-11eb-8c16-5ad03d82e038.png)
(As you can see... no "Dropbox" field)

By initializing all the timeseries into the DB I think that we could always see all the fields into the drop down menu...

What do you think?
If you are not agree with this type of solution, do you have any idea to solve easily our issue?
Can we initialize the missing timeseries we need manually? (Also if I think that this is not a good solution...)

Thanks... :-)

**Comment by simonemainardi** [comment]
Why don't you just set an explicit color in grafana to any of the timeseries? E.g., "om 2" is "pink", and that's it. You should not and cannot rely on ordering or on asking to fill a database with ZERO points for any possible timeseries. This will not scale and just make things very inefficient.

**Comment by gianogli** [comment]
Yes, this is a possible solution but I've about 30 graphs with 8 interfaces each one... so I've to set manually (O_o) 240 colors!
I don't know how influxdb works... I thought it was enough to fill with one "0" all the not defined timeseries during the ntopng start.
If it's not possible I think that the only solution could be to set the colors in grafana using some script...
Thanks...

**Comment by simonemainardi** [comment]
It seems this is an open issue in Grafana:

- https://github.com/grafana/grafana/issues/221
- https://github.com/grafana/grafana/issues/3250

Definitely something you should do on the UI. You cannot ask the backend to generate ZEROes for every possible timeseries, just because you want to have nice colors in the frontend. You will end up in using a database in a very inefficient way only because it is easier for you to color the timeseries.

**Comment by gianogli** [comment]
@simonemainardi yes, you are right.
Thanks for the links to the grafana open issues... ;-)
