### ISSUE TITLE
Add option to disable auto update blocklists and perform manually

### ISSUE THREAD

**Issue by neotrak** [ntop/ntopng#4953]
v.4.2.201105 

**Problem:** Enabled blocklists auto update daily or hourly. Can you add manual option to set? In action column, it's already possible to tap for check update each blocklists whenever necessary one by one then only that thing still missing.

![image](https://user-images.githubusercontent.com/73976062/105630709-4bc42200-5e7d-11eb-8cf8-b63bbd736277.png)

**Comment by simonemainardi** [comment]
Implementation is as follows:

- Add an entry "Manual" to the "Update Frequency" dropdown
- Check the backend  (e.g., `function shouldUpdate(list_name, list, now)`) and make sure entries market with "Manual" are never updated
- The only way to update "Manual" entries is via the UI, clicking on the refresh:

![image](https://user-images.githubusercontent.com/3397663/106173140-e7aea000-6193-11eb-9055-6d7ab3c20f1a.png)

**Comment by simonemainardi** [comment]
implementation will go into 4.3 dev and subsequent 4.4 stable

**Comment by simonemainardi** [comment]
Unfortunately this doesn't work.

**Comment by simonemainardi** [comment]
Verified as fixed.
