### ISSUE TITLE
Traffic Flow from LAN interfaces to WAN interface

### ISSUE THREAD

**Issue by Azhdar1990** [ntop/ntopng#4955]
Hello
I need to monitor traffic flow from hosts in my network (lan interface) to the internet .
There is NAS storage in local network.
I see my hosts and get info about throughput per host.
I created alert (also created endpoints and recipients from web interface of ntopng):
When host throughput reachs 20 mb alert will be triggered.
But if his host start to download or upload from NAS storage i also see this throughput and alert is triggered
Please tell me.
How to monitor traffic only between local hosts and internet?
Thank's in advance

**Comment by simonemainardi** [comment]
I am assuming you have all your hosts in a local network (e.g, the network of the lan interface)

You can create a local-network alert and set the 20Mbps threshold for ingress and egress traffic. This will only take into account the traffic exiting or entering the network (not within the network itself)

![image](https://user-images.githubusercontent.com/3397663/106165629-93072700-618b-11eb-8185-ad6799574ffb.png)
