### ISSUE TITLE
Add binding interface in ICMP active tests

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4957]
It is requested to add a new dropdown menu named "Test Interface" in ICMP and Continuous ICMP only
![Screen Shot 2021-01-25 at 16 39 30](https://user-images.githubusercontent.com/4493366/105728075-07dc2600-5f2c-11eb-817b-61a40c693aab.png)

that has the following values
- System default (this is the default, that means that the system will choose the interface, basically as today)
- a list of the network interfaces of the system using ntop.listInterfaces() with an IP (doesn't matter if IPv4 or IPv6) defined, thus omitting all interfaces without an IP address defined.

Once the GUI is implemented, the active monitoring code will use the interface name (or an empty value if selected "System default") to bind the Ping code to the specified interface.

This ticket depends on #3871 and #4956

**Comment by lucaderi** [comment]
The selected interface in the active monitoring page is not saved, or the GUI does not select the last selected interface. This is the selected interface all the time set to default

![Screen Shot 2021-01-31 at 22 45 47](https://user-images.githubusercontent.com/4493366/106398934-150a8080-6416-11eb-9a4c-d6d5c4953205.png)

**Comment by MatteoBiscosi** [comment]
This issue will be closed when #5001 is implemented

**Comment by simonemainardi** [comment]
#5001 is now implemented.
