### ISSUE TITLE
Some columns wrap, others are empty

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4958]
![Screen Shot 2021-01-25 at 17 32 37](https://user-images.githubusercontent.com/4493366/105734852-5d680100-5f33-11eb-8e76-74218ed92248.png)

**Comment by gabryon99** [comment]
Increased the 'Last Seen' column width so the row doesn't wrap, check the pro repository.

**Comment by lucaderi** [comment]
Not quite

![Screen Shot 2021-01-26 at 19 07 16](https://user-images.githubusercontent.com/4493366/105885689-bb671800-6009-11eb-981e-b6ff58e21be5.png)

**Comment by gabryon99** [comment]
Add `.no-wrap` class to avoid wrapping for specific columns

**Comment by lucaderi** [comment]
![Screen Shot 2021-01-27 at 19 42 52](https://user-images.githubusercontent.com/4493366/106038173-df912a80-60d7-11eb-810e-fb82ff1846e4.png)

the above issue is fixed but a new problem is present on Safari. See if you can do something or close this ticket

**Comment by gabryon99** [comment]
I tried it on Safari 14.0.2 and it works.
