### ISSUE TITLE
Cannot access ntopng web page - Error

### ISSUE THREAD

**Issue by mamema** [ntop/ntopng#4960]
Hi,

i have this:

HTTP/1.1 302 Found Server: ntopng 4.3.210125 (amd64) Set-Cookie: session=; path=/; HttpOnly; SameSite=lax; Secure Location: /lua/http_status_code.lua?message=internal_error&referer=192.168.0.2%3A3000%2F&error_message=...%2Flocal%2Fshare%2Fntopng%2Fscripts%2Flua%2Fmodules%2Falert_consts.lua%3A402%3A%20attempt%20to%20index%20a%20nil%20value%20%28field%20%27meta%27%29 .../local/share/ntopng/scripts/lua/modules/alert_consts.lua:402: attempt to index a nil value (field 'meta')

accessing (http/https)://ip:port

on pfsense (freebsd 11.3Stable)

and the ntopng log is full with:

25/Jan/2021 18:05:05 [notifications.lua:12] [alert_consts.lua:411] ERROR: Invalid alert key specified Unexpected alert key type. in alert_threshold_cross from /usr/local/share/ntopng/scripts/lua/modules/alert_definitions
25/Jan/2021 18:05:05 [notifications.lua:12] [alert_consts.lua:411] ERROR: Invalid alert key specified Unexpected alert key type. in alert_unexpected_dns from /usr/local/share/ntopng/scripts/lua/modules/alert_definitions
25/Jan/2021 18:05:05 [notifications.lua:12] [alert_consts.lua:411] ERROR: Invalid alert key specified Unexpected alert key type. in alert_process_notification from /usr/local/share/ntopng/scripts/lua/modules/alert_definitions
25/Jan/2021 18:05:05 [notifications.lua:12] [alert_consts.lua:411] ERROR: Invalid alert key specified Unexpected alert key type. in alert_unexpected_dhcp from /usr/local/share/ntopng/scripts/lua/modules/alert_definitions
25/Jan/2021 18:05:05 [LuaEngine.cpp:571] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/system/notifications.lua][.../local/share/ntopng/scripts/lua/modules/alert_consts.lua:402: attempt to index a nil value (field 'meta')]
25/Jan/2021 18:05:05 [LuaEngine.cpp:571] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/interface/periodic_user_scripts.lua][.../local/share/ntopng/scripts/lua/modules/alert_consts.lua:402: attempt to index a nil value (field 'meta')]
25/Jan/2021 18:05:05 [LuaEngine.cpp:571] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/system/stats_update.lua][.../local/share/ntopng/scripts/lua/modules/alert_consts.lua:402: attempt to index a nil value (field 'meta'

With disabled notification a login is possible, but the web page looks like this

![image](https://user-images.githubusercontent.com/18702616/105743132-a2446580-5f3c-11eb-8c5d-92bf4f21ed57.png)

Regards

**Comment by simonemainardi** [comment]
Please, show how you have installed ntopng. My guess is that you have two versions installed, or an older version installed which is causing a clash.

Try and remove all installation first. Then, install according to https://packages.ntop.org/FreeBSD/

**Comment by mamema** [comment]
Thank you, even though i've uninstalled everything as of documentation from you and/or pfsense, the find command found some leftovers. After removing those and reinstalling latest ntopng everything is up and running
