### ISSUE TITLE
OPNsense - disinstalling ntopng does not stop the service

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4962]
ntopng process keeps running when ntopng is uninstalled (same when uninstalling ntopng as dependency of the os-ntopng-enterprise plugin).

Expected behavior is to stop the process during disinstallation.

**Comment by cardigliano** [comment]
This seems to be expected. On FreeBSD the system administrator is supposed to decide and take action on package update or uninstallation, the system should (just) update or uninstall the package.
