### ISSUE TITLE
Allow editing local users when LDAP auth is used with fallback enabled

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#4964]

**Comment by cardigliano** [comment]
This works for me, waiting for debug info from the user

**Comment by AlekseiSaff** [comment]
all info was provided. do you still need something additional?

**Comment by cardigliano** [comment]
@AlekseiSaff we are testing a patch on the dev branch, it will be backported to stable after that, and let you check it

**Comment by cardigliano** [comment]
Fixed
