### ISSUE TITLE
Application protocol filtering is not working in service map

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4965]
![Screen Shot 2021-01-25 at 20 43 41](https://user-images.githubusercontent.com/4493366/105757318-1e937480-5f4e-11eb-8dd2-73abf0156b45.png)

**Comment by lucaderi** [comment]
With cache clean it works as workaround: you need to version files IMHO for long term solution

**Comment by lucaderi** [comment]
I have implemented ntop.getStaticFileEpoch() and modified the call to graph-map.js. @gabryon99 You now need to check all other files that include ntop's .js files and call the above method

**Comment by gabryon99** [comment]
Add the call to `ntop.getStaticFileEpoch()` for the all js files
