### ISSUE TITLE
host map filter shows "Alerted Flows" twice

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#4966]
Hello
The host map filter drop down shows "Alerted Flows" twice:
<img width="295" alt="Screenshot 2021-01-25 at 21 41 59" src="https://user-images.githubusercontent.com/38549755/105765552-e47ba000-5f58-11eb-90ac-95410957b544.png">
First link: /lua/hosts_map.lua?bubble_mode=2
Second link: /lua/hosts_map.lua?bubble_mode=9
Thanks

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu , the bug is fixed, builds are in progress, bear with it for at most 2 hours.
