### ISSUE TITLE
Elasticsearch geopoint - latitude and longitude values inverted

### ISSUE THREAD

**Issue by lallori** [ntop/ntopng#4967]
Hi again @MatteoBiscosi,
sorry for bothering but I may found another issue. 

It seems that Longitude and Latitude values indexed in so-notpng template are inverted.

This is Helsinki when putting it on a visualization map:
 
![maps_wrong](https://user-images.githubusercontent.com/16099406/105770796-f876d000-5f5f-11eb-9b43-4e41aeb63078.png)

This is its values in the index pattern:
![es_alerts-ntop_index_dest_ip](https://user-images.githubusercontent.com/16099406/105771007-3d9b0200-5f60-11eb-81c5-77c307ae7ad3.PNG)

![image](https://user-images.githubusercontent.com/16099406/105771522-f6614100-5f60-11eb-88f1-37c9e1c1c0b4.png)

Locations from the ntop_template are indexed correctly and the numbers are inverted indeed:
![es_ntop_index_dest_ip](https://user-images.githubusercontent.com/16099406/105771070-50153b80-5f60-11eb-90be-65d25c1005a3.PNG)

![image](https://user-images.githubusercontent.com/16099406/105771638-26104900-5f61-11eb-831e-26d789e14c74.png)

**Comment by MatteoBiscosi** [comment]
Hi @lallori , when the builds for Windows are done, update ntopng and the bug should be fixed.

**Comment by lallori** [comment]
@MatteoBiscosi updated to v.4.3.210126 but I am having the same problem.

Thanks

**Comment by simonemainardi** [comment]
@MatteoBiscosi please assist

**Comment by lallori** [comment]
@MatteoBiscosi @simonemainardi pls remember me ;)
Thanks

**Comment by MatteoBiscosi** [comment]
Hi @lallori i fixed this issue and now the format kibana shows me is the same as the one requested by ECS (like the screenshot shows). Please bear with it and wait until the next build for Windows.

https://www.elastic.co/guide/en/ecs/current/ecs-geo.html

![Screenshot from 2021-01-28 11-20-03](https://user-images.githubusercontent.com/49585191/106126016-237a4300-615d-11eb-870e-2e0e4849b29b.png)

**Comment by MatteoBiscosi** [comment]
Hi @lallori builds for Windows are done, so update ntopng and let me know if you still have some problem.

**Comment by lallori** [comment]
@MatteoBiscosi thank you very much!

Everyting is working fine now.

![image](https://user-images.githubusercontent.com/16099406/106497488-653d1d80-64be-11eb-8770-bf6d3963057f.png)
