### ISSUE TITLE
Security analyst mode

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#4968]
Hello 
When detecting malicious network data, the analyst should not be able to directly open the extracted link, e.g. out of the TLS certificate:
<img width="332" alt="Screenshot 2021-01-25 at 23 56 27" src="https://user-images.githubusercontent.com/38549755/105776510-00873d80-5f69-11eb-8fe8-6b9a95115a66.png">
which opens http://www.amajai-technologies.world/ and this could lead to unwanted connection to malicious server.
or a remote host:
<img width="594" alt="Screenshot 2021-01-26 at 11 44 40" src="https://user-images.githubusercontent.com/38549755/105835363-fd716900-5fcb-11eb-957d-6213e8b0767c.png">

Proposal: add security analyst mode which disable direct links and de-fanges urls:

- Top level domain: http://www.amajai-technologies[.]world/  
- tt to XX: hXXps://www.amajai-technologies.world/

Thanks.

**Comment by MatteoBiscosi** [comment]
Hi martin, in the latest ntopng versions we added a dialog when clicking to the malicious url in order to not lead to unwanted connection, in this way the problem should be resolved please reopen the issue if you think that this is not enough
