### ISSUE TITLE
OPNsense - updating plugin does not restart the service

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#4969]
Used the Firmware -> Plugins page to update the ntopng os-ntopng-enterprise plugin.

Update was successful but the service was not restarted

08:28:23 +0000 | Uptime: 14:53:18

Pressing multiple times on the "Check for updates" prints suspicious output, as if the update was not performed

![image](https://user-images.githubusercontent.com/3397663/105820076-5c79b280-5fb9-11eb-8016-223068d99d14.png)

**Comment by cardigliano** [comment]
This seems to be expected. On FreeBSD the system administrator is supposed to decide and take action on package update or uninstallation, the system should (just) update or uninstall the package.
