### ISSUE TITLE
callbacks/minute.lua script failure each 5 minutes

### ISSUE THREAD

**Issue by garrymar** [ntop/ntopng#497]
Dear developers,

callbacks/minute.lua script generates warning message in ntopng.log every 5 minutes:

15/Apr/2016 23:50:02 [Lua.cpp:4512] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:1984: bad argument #2 to 'format' (number expected, got nil)]
15/Apr/2016 23:55:01 [Lua.cpp:4512] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:1984: bad argument #2 to 'format' (number expected, got nil)]
16/Apr/2016 00:00:01 [Lua.cpp:4512] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:1984: bad argument #2 to 'format' (number expected, got nil)]
16/Apr/2016 00:05:02 [Lua.cpp:4512] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:1984: bad argument #2 to 'format' (number expected, got nil)]
16/Apr/2016 00:10:02 [Lua.cpp:4512] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:1984: bad argument #2 to 'format' (number expected, got nil)]
16/Apr/2016 00:15:01 [Lua.cpp:4512] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:1984: bad argument #2 to 'format' (number expected, got nil)]
16/Apr/2016 00:20:01 [Lua.cpp:4512] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:1984: bad argument #2 to 'format' (number expected, got nil)]

v.2.3.160415 [Professional Edition]
GIT rev:   dev:13e49130392b656aa6ffd6944e7c6b720eb10f5b:20160415
Pro rev:   r620
System Id: 70DFE73909B0B922
Built on:  CentOS release 6.7 (Final)

Many thanks in advance!

Kind Regards,
Garri

**Comment by lucaderi** [comment]
Said that I cannot reproduce it, I have added some extra checks to prevent it. We need to investigate it more in details if we'll be able to reproduce it. Overnight new packages will be built that include the fix

**Comment by garrymar** [comment]
Updated to v.2.3.160420. The problem solved. Thanks!

**Comment by lemmy04** [comment]
Having the same problem, running ntopng 2.4.0 built on openSUSE Leap 42.2... any advice?

**Comment by emanuele-f** [comment]
@lemmy04 what's the exact error you get?

**Comment by lemmy04** [comment]
it's ok now, starting ntopng 2.4 when 2.2 is still running does not work well.
I'll open a related issue to the effect that the rc script is not working well on openSUSE. Should have a proper systemd unit in any case.

**Comment by simonemainardi** [comment]
@lemmy04 if you have properly patched the rc script for opensuse please send us a pull request with it. Thank you.
