### ISSUE TITLE
Flows Throughput/Total bytes

### ISSUE THREAD

**Issue by PaoloCmb** [ntop/ntopng#4970]
Hi.
It would be great to be able to filter the active flows using the top menus (Application, Category,Traffic profiles, ecc) and have (at the top or at the bottom) the total Throughput and Total bytes of the filtered flows.
This would help very much for realtime troubleshooting.

Also, would it be possible to select more than one entry in the top filters? (multi selection for single menu, ie. Applications--> Teams + Skype)

Thanks in advance

Bye

**Comment by MatteoBiscosi** [comment]
Hi @PaoloCmb total throughput/bytes for the filtered flows has been implemented. Regarding the multi selection currently it is not possible to select more than one entry.
