### ISSUE TITLE
Upper Left drop down menu - not working on all browsers

### ISSUE THREAD

**Issue by mamema** [ntop/ntopng#4972]
Hi,

latest ntopng (from yesterday) running on freebsd (pfsense) has the following issue:

if one select the drop down menu in the upper left corner to select System or available interfaces, then:

chrome windows/osx - doesn't change view accordingly
chrome ios - change view accordingly
edge windows - change view accordingly 
safari osx - doesn't change accordingly
Firefox osx -  change view accordingly
Firefox windows - doesn't change view accordingly

of course i've cleared browser cache before

**Comment by simonemainardi** [comment]
please, right-click, inspect element, then check for console errors and report them. Thanks.

**Comment by mamema** [comment]
![image](https://user-images.githubusercontent.com/18702616/106030361-64774680-60ce-11eb-995c-21b7044d1795.png)

**Comment by simonemainardi** [comment]
@gabryon99 can you please help?

**Comment by gabryon99** [comment]
Fixed the error in the console. I tested the code with:
* Safari
* Chrome
* Firefox
* Microsoft Edge for MacOS

All the browser are updated to the last version.
