### ISSUE TITLE
ntopng crashes when too many ZMQ interfaces are used

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4975]
it should not crash but just report a limit was hit

#7  0x000000000040e79a in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:194
(gdb) f 3
#3  0x00007ffff794af28 in zmq::epoll_t::epoll_t(zmq::ctx_t const&) () from /lib64/libzmq.so.5
(gdb) f
#3  0x00007ffff794af28 in zmq::epoll_t::epoll_t(zmq::ctx_t const&) () from /lib64/libzmq.so.5
(gdb) f 6
#6  0x0000000000471462 in ZMQCollectorInterface::ZMQCollectorInterface (this=0x62275b0, _endpoint=<optimized out>) at src/ZMQCollectorInterface.cpp:54
54        subscriber[num_subscribers].socket = zmq_socket(context, ZMQ_SUB);
(gdb) q
A debugging session is active.

**Comment by simonemainardi** [comment]
Crash was happening with 100 ZMQ intefaces.

After internal review, maximum number of ntopng interfaces has been reduced and the crash no longer occur (https://github.com/ntop/ntopng/commit/3159f49b2d9c3797dc6c3e922128df25bb79d66c). This is also documented in https://www.ntop.org/guides/ntopng/faq.html#maximum-number-of-interfaces

Specifying more than the maximum number of interfaces causes exceeding interfaces to be ignored.
