### ISSUE TITLE
Web interface access list

### ISSUE THREAD

**Issue by amastelek** [ntop/ntopng#4977]
The access list for the web interface on NTOPNG seems limited to only 4 subnets?
Is this correct?   Seems low?
Using 4.2 stable

**Comment by simonemainardi** [comment]
@MatteoBiscosi please increase the ACL list length from 64 to 512:

![image](https://user-images.githubusercontent.com/3397663/105971922-58b66080-608b-11eb-91d6-0ad9033858d9.png)

Fix it to both stable and dev.

**Comment by MatteoBiscosi** [comment]
Hi @amastelek builds are in progress, in a few hours a new update with a fix is going to be available
