### ISSUE TITLE
Question about function/usage scenario

### ISSUE THREAD

**Issue by kotso** [ntop/ntopng#4981]
I need to achieve following scenario with ntopng and any idea/help will be appreciated:

Goal is to get information about PPS per local IP and trigger some script that will handle it (I want to use it to implement auto RTBH feature "route to blackhole") on edge device.

Currently I already have ntopng enterprise setup with nprobe and flows been delivered and I have visualisation.

If ntopng can't provide PPS information, then anything like flow per ip, or traffic per ip. 

Evaluation of this preferred to be done in shortest time period as possible, 1 sec would be best, or 5 or 10 secs. 1 min will also work but smaller interval much appreciated.

**Comment by simonemainardi** [comment]
We are discussing this issue here: https://github.com/ntop/ntopng/issues/4863

Please, follow up that discussion.
