### ISSUE TITLE
Implement flexible flow navigation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4985]
The flow page (hosts page has the same problem) is not simple to use for hunting problems. For instance it lacks things like
hide specific flows (e.g. those of protocol DNS). It is requested to implement a Kibana-like filtering facility that allows people to narrow down searches until only specific/selected flows are selected.

**Comment by MatteoBiscosi** [comment]
now it should be a lot more flexible, it is still not possible to filter flows based on the "not" property but it should be flexible enough
