### ISSUE TITLE
Automate alerts tests

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4989]
It is requested to automated alert generation scripts as follows
- create an empty ntopng configuration
- enable all scripts
- flush all data in sqlite
- instruct ntopng to read various pcaps from a testing folder
- once the processing is over check that the generated alerts as those of the previous run

This facility needs to be automated to that it is executed very day (or at every commit even though it will probably not be the first choice)

This ticket depends on #4988

**Comment by cardigliano** [comment]
Proposal - a script will run all tests contained in a folder, each test consists of:
  - definition of the input (list of pcap files)
  - a pre script (e.g. to configure SNMP devices, enable all user scripts)
  - a post script (to check the output from the REST API), this should be executed after the second minute (or configurable)

A new call will be created to enable all scripts (a default should be provided for all of them)

**Comment by cardigliano** [comment]
Implemented with this patchset: 47bfe8dc5fc6cc2615666434ed3d03e7c75409bb c76198f79d677247e8c218f3d9c2d8c9a0a00e09 f5532815f40bfa24106d17ed6a1100832f22af3a 9acd6553ede7c5d2c992561d903f8c52ea343ef2 2a08a4a5aee25dc25ae5604896efe1dd3889ff0b ab7c490731daf3798ad3e99bf614502fa3d31dd5
