### ISSUE TITLE
MySQL Tables / Format

### ISSUE THREAD

**Issue by arrmo** [ntop/ntopng#499]
Hi,

I really like that ntopng is storing data to MySQL - to allow offline processing / customization. But ... is information available anywhere explaining the format of the data? I see multiple v4 tables (i.e. IPv4), not sure what is in which tables.

And does ntopng handle the data consolidation? What I mean is - for longer periods of time the data is compiled, to wider time slices ... is this being done offline by ntopng?

Thanks!

**Comment by simonemainardi** [comment]
MySQL table names in ntopng 2.2.x have the following naming convention: 

`flowsv<IPversion>_<interface_id>`

In 2.3.x version only two tables are used, namely `flowsv4` and `flowsv6`

Table column names should be self-explanatory. If you have specific questions, please ask them here.

Presently, consolidation is not carried out. However, ntopng run a daily activity that cleans up MySQL flows older than a configurable number of days.

**Comment by arrmo** [comment]
Thanks for the quick reply - much appreciated! Yes, the columns make sense, no issues there ... it was more about the tables themselves, to understand what they implied.

Need to look at the data further - not sure if there is an output every second (looking at the first few rows), or what happens when connections are maintained longer.

Thanks again.

**Comment by simonemainardi** [comment]
expired/closed flows flows are continuously dumped to mysql in an asynchronous way with an independent thread. So the dump frequency is not a constant. A flow is not dumped unless it's expired/closed.

p.s. don't forget to star ntopng if you like it ;)

**Comment by arrmo** [comment]
OK, one quick question ... I see tables 0 through 5, but "ip link show" shows 1 through 7 => confused.

Any thoughts?

**Comment by simonemainardi** [comment]
ids are not the same and thus not comparable. ids shown in table names have a business meaning that is limited to ntopng internals.

**Comment by arrmo** [comment]
OK, that makes sense - but then how to find traffic for a specific interface? Do I need to search all tables each time?

Thanks.

**Comment by simonemainardi** [comment]
visit page `http://localhost:3000/lua/if_stats.lua` interface id is shown in the table

**Comment by arrmo** [comment]
That works, thanks for the info!

**Comment by arrmo** [comment]
Just an FYI - I'm running the following version, but seem to have the longer list of tables (not just 2 of them)?

v.2.3.160415 [Community Edition]
GIT rev:   :2.3.160415

Or am I missing something?

Thanks!

**Comment by simonemainardi** [comment]
version should use only one table and migration should occur automatically. If this is not your case, try and delete the mysql db (dump it before deleting if you don't want to lose old data). A new mysql db will be recreated automatically.

**Comment by arrmo** [comment]
Hi,

Dumped (deleted) the table - and then had to restart the service (no problem). Did that, database was recreated ... with all the tables (flowsv4_0 to flowsv4_5, for example).

Thanks!

**Comment by simonemainardi** [comment]
so you are using an ntopng that is not the one shown above. Double check: perhaps you have another ntopng installation

**Comment by arrmo** [comment]
That's what I was thinking as well! And it's possible, but here is what I just did (to check),
ps -elF | grep ntop
=> only result is /usr/sbin/ntopng /etc/ntopng.conf

So then, 
/usr/sbin/ntopng -V
v.2.3.160415 [Community Edition]
GIT rev:   :2.3.160415

Thoughts?

**Comment by arrmo** [comment]
Perhaps this syntax (in /etc/ntopng.conf) is the issue?
-F="mysql;localhost;ntopng;flows;user;password"

Thanks!

**Comment by simonemainardi** [comment]
Here is the piece of code that creates the database as said. It is available in the latest build: https://github.com/ntop/ntopng/blob/dev/src/MySQLDB.cpp#L86

**Comment by arrmo** [comment]
Makes sense, and I agree - I wonder if this is something messed up with the Ubuntu package (I installed using apt). While executing the program says v2.3, if I look at Ubuntu packages I see ... Package: ntopng (2.2+dfsg1-1build1) [universe]

I admit, not sure what dfsg1 implies.

**Comment by arrmo** [comment]
FYI, working fine with manual build - don't believe the version Ubuntu says it is ... ;).

Thanks!
