### ISSUE TITLE
Automate memory leak test

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4990]
Implement test for memory leak using addresssanitizer.

See #4989

**Comment by cardigliano** [comment]
A flag in the regression tests script has been added to enable the leak detection using the sanitizer, however this is currently disabled as there are minor leaks that would add noise. They need to be fixed before enabling the leak detection.

**Comment by cardigliano** [comment]
The sanitizer is now enabled when running regression tests.

**Comment by cardigliano** [comment]
Please see https://github.com/ntop/ntopng/blob/dev/CONTRIBUTING.md#memory-leak-detection
