### ISSUE TITLE
Implement in-container tests for FreeBSD

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4991]
Similar to what happens for Linux, implement continuous integration tests for FreeBSD

**Comment by simonemainardi** [comment]
Implemented using jails in https://github.com/ntop/packager/tree/master/freebsd

Actively running tests. Will wait before closing.

**Comment by simonemainardi** [comment]
Adds common functions to be re-used between linux and osx tests: https://github.com/ntop/packager/commit/99da3d3166fab4a008f75dab8de921fbd5ad7763

**Comment by simonemainardi** [comment]
Adds alert functions for FreeBSD: https://github.com/ntop/packager/commit/3884c88439f4e4729a6dcbb77abae60f687b6de9

**Comment by simonemainardi** [comment]
Implemented as requested.
