### ISSUE TITLE
Alert Filter/Whitelist

### ISSUE THREAD

**Issue by netsolv** [ntop/ntopng#4992]
I was curious to see if there was a way to globally "ignore" alerts to/from specific domains? We're consistently receiving "suspicious file transfer" alerts from "known/trusted" domain url's. Was wondering if best way is through specific hosts configuration or if there was a way to "whitelist/exclude" certain domains from triggering alerts. Thank you.

**Comment by simonemainardi** [comment]
This issue is work in progress and discussed in https://github.com/ntop/ntopng/issues/4942. Please, joint the discussion there.
