### ISSUE TITLE
Empty service map must be reported

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4998]
http://xxxx:3000/lua/pro/enterprise/service_map.lua?host=224.0.0.251&page=graph&l7proto=DNS

![Screen Shot 2021-01-31 at 22 52 08](https://user-images.githubusercontent.com/4493366/106399105-f953aa00-6416-11eb-8f5c-f5170f60555d.png)

In the above example the filter produces an empty map: this should be reported to the user that otherwise might think this is a bug

**Comment by gabryon99** [comment]
Add a message when there aren't nodes inside the map

<img width="1686" alt="Screenshot 2021-02-15 at 10 36 49" src="https://user-images.githubusercontent.com/14114916/107929285-b860a700-6f79-11eb-9f35-9404b132818b.png">
