### ISSUE TITLE
In Hosts table on neflow the Throughput becomes zero after a few seconds

### ISSUE THREAD

**Issue by amastelek** [ntop/ntopng#4999]
I have some neflow interfaces.  The ones with a high traffic load always have a throughput listed.  The others with a low traffic load list throughput for a few seconds and then go to zero even when the interface still reports traffic.
I tried increasing the real-time refresh rate in interfaces but it still does it. 
![za](https://user-images.githubusercontent.com/61453908/106427530-4021be00-6470-11eb-8618-e3a10606b1ff.jpg)
![downunder](https://user-images.githubusercontent.com/61453908/106427557-4748cc00-6470-11eb-9ca4-30ca2165bc99.jpg)

**Comment by simonemainardi** [comment]
Reported behavior is normal.

First interface, which I assume is the one with low traffic, has currently no active flows. You can see this if you click on the flows page or if you just look at the header which is missing the flow counter badge:

![image](https://user-images.githubusercontent.com/3397663/106479455-a592a080-64aa-11eb-9bae-230270e4f7cf.png)

No active flows means the current throughput must be zero, i.e., no traffic no throughput for all active hosts. You will get throughput updated with values > 0 as soon as new flows arrive.
