### ISSUE TITLE
sFlow Interface Gauge Showing sFlow Throughput Data

### ISSUE THREAD

**Issue by seismiccollision** [ntop/ntopng#500]
At some point it looks like the interface gauge for our sFlow collection stopped displaying the throughput as provided by the sFlow data and began what seems to be the physical interface's data rates. I think it started after an update but I don't know which one

**Comment by simonemainardi** [comment]
@seismiccollision please provide more quantitative information. attach screenshots / data of what you think it is relevant to the issue. Thank you

**Comment by seismiccollision** [comment]
@simonemainardi see attached, thanks!
![image](https://cloud.githubusercontent.com/assets/9156430/14654617/6c21d7ba-0633-11e6-858a-1712974427e0.png)

**Comment by seismiccollision** [comment]
Also relevant
![image](https://cloud.githubusercontent.com/assets/9156430/14654644/93536e5c-0633-11e6-9c3a-fad5ffc779d4.png)

the sparklines aren't registering anything and the interface gauge doesn't match the application traffic

**Comment by simonemainardi** [comment]
can you attach nProbe and ntopng configurations as well

**Comment by seismiccollision** [comment]
@simonemainardi 
I've been using this for nprobe:
`nprobe --zmq=tcp://*:5556 -i none -n none --collector-port 6343 -T"%IPV4_SRC_ADDR %IPV4_DST_ADDR %IPV4_NEXT_HOP \%INPUT_SNMP %OUTPUT_SNMP %IN_PKTS %IN_BYTES %FIRST_SWITCHED \%LAST_SWITCHED %L4_SRC_PORT %L4_DST_PORT %TCP_FLAGS %PROTOCOL \%SRC_TOS %SRC_AS %DST_AS %IPV4_SRC_MASK %IPV4_DST_MASK  \%IN_SRC_MAC %OUT_DST_MAC \%SRC_VLAN %DST_VLAN" >> /dev/null &`

and here is the ntopng:

```
# to disable logins -l=1
-G=/var/tmp/ntopng.pid
-i=tcp://127.0.0.1:5556 
-d=/var/tmp 
-w=3000 
-m="<removed>"
-F="mysql;<removed>" 
-e=
-A=2 
-C= 
-D=all 
-E=all 
-S=all 
-W=3001
-x=3000000
-X=131072
-S=local
-p=/etc/ntopng/custom.protos
```

**Comment by seismiccollision** [comment]
@simonemainardi 
FWIW I updated to the latest version and the issue improved until I adjusted the 'interface speed' parameter in the webui

now i am seeing the following
![image](https://cloud.githubusercontent.com/assets/9156430/14792541/97d70290-0acf-11e6-9836-1aa62cb9adfd.png)

i had the interface speed set to 10000Mbps but once things started working it was showing >20Gbps so I adjusted it to 70000Mbps and then it stopped working and didn't clear up by returning the value to its previous and bouncing ntopng
