### ISSUE TITLE
Alert on Unexpected DNS even when it is in the exclude list

### ISSUE THREAD

**Issue by amastelek** [ntop/ntopng#5000]
The alerts are still be listed even when they are in the exclude list in settings.
![UDNS2](https://user-images.githubusercontent.com/61453908/106430705-dce65a80-6474-11eb-9506-5b5899e46538.jpg)
![UDNS1](https://user-images.githubusercontent.com/61453908/106430724-e1ab0e80-6474-11eb-836c-57d1eac936ed.jpg)

**Comment by simonemainardi** [comment]
Symbolic names shown in the alert don't allow us to verify.

Please, attach a pcap capture of the DNS traffic or, if you are over ZMQ, the ntopng configuration used.

By the way, looking at the traffic, it seems you have clients and servers inverted. You should check your network or netflow configuration.

**Comment by amastelek** [comment]
> 
> 
> Symbolic names shown in the alert don't allow us to verify.
> 
> Please, attach a pcap capture of the DNS traffic or, if you are over ZMQ, the ntopng configuration used.
> 
> By the way, looking at the traffic, it seems you have clients and servers inverted. You should check your network or netflow configuration.

The configuration is edge using pmacct -> netflow -> nprobe -> ZMQ -> NTOPNG

The problem seems to be not on the DNS servers on the internet but the caching DNS server on the local LAN coming through on the alerts even though its in the exclude list.

Capture files are too large.  About 40MB.  (any other way to get them to you?)

**Comment by simonemainardi** [comment]
send a download link to mainardi ntop org

**Comment by simonemainardi** [comment]
Thanks for sending the pcap. Issue is solved. A new 4.3 dev build is in progress and will be ready in a couple of hours.

**Comment by amastelek** [comment]
Thanks.  I’m on 4.2 stable but now that I know I can wait a few days for it
to filter through.



Awesome work.



*From:* Simone Mainardi <notifications@github.com>
*Sent:* Tuesday, 02 February 2021 15:32
*To:* ntop/ntopng <ntopng@noreply.github.com>
*Cc:* amastelek <ronald@amastelek.com>; Author <author@noreply.github.com>
*Subject:* Re: [ntop/ntopng] Alert on Unexpected DNS even when it is in the
exclude list (#5000)



Thanks for sending the pcap. Issue is solved. A new 4.3 dev build is in
progress and will be ready in a couple of hours.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ntop/ntopng/issues/5000#issuecomment-771635826>, or
unsubscribe

**Comment by simonemainardi** [comment]
As you have port 53 listed as client port, It is likely that your NetFlow exporter is configured ingress-only on the port that gets the DNS responses. I think you should enable this heuristic to have things looking better

![image](https://user-images.githubusercontent.com/3397663/106715562-82c4d100-65fd-11eb-9ef4-81994895c4f1.png)
