### ISSUE TITLE
Enable active monitoring interface only on selected platforms

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5004]
With ntop.isPingIfaceAvailable() it is possible to know if active monitoring with interface support is available on the platform. Where not available the interface menu entry should be avoided

![Screen Shot 2021-02-02 at 21 09 21](https://user-images.githubusercontent.com/4493366/106656820-7b6cdb80-659b-11eb-9bb0-ef3fc1bb57cd.png)

**Comment by simonemainardi** [comment]
Verified. Menu is hidden in FreeBSD and shown elsewhere.
