### ISSUE TITLE
how to get remote senders timeseries

### ISSUE THREAD

**Issue by rmorandell-pgum** [ntop/ntopng#5005]
Hi ntop team,

I use the timeseries API to filter out the historical data via the topk query. Currently I am able to do this for networktraffic (ts_schema = top: subnet: traffic), for asn (ts_schema = top: asn: traffic), for country (top: country: traffic) for the local sender (ts_schema = top: local_senders) and local receiver (ts_schema = top: local_receivers). What I have not found out is the scheme for the remote_sender and remote_receiver. 

For example:

`{{URL}} / timeseries / ts.lua? Ts_compare = 30m & epoch_end = 1611788399 & initial_point = true & epoch_begin = 1611702000 & ts_schema = top: remote_senders & ts_query = ifid: {{InterfacId}} & limit = 10 & extended = 10`

I'm getting back 404 not found.

is there a scheme for the remote transmitter and receiver?

thanks for your help

**Comment by simonemainardi** [comment]
By definition, remote hosts are not stored in timeseries because they are *remote*. This is to only store timeseries for hosts you care, i.e,  those specified in -m, and prevent ntopng from writing timeseries for potentially the whole Internet.

**Comment by rmorandell-pgum** [comment]
Thanks for response.

in traffic report for a month back i can see some remote hosts

lua/pro/report.lua?num_minutes=44640

![image](https://user-images.githubusercontent.com/46994680/106739968-1efcd100-661a-11eb-93f7-b6cdd1a32bf3.png)

how can i get this traffic data for this top remote hosts ?

**Comment by simonemainardi** [comment]
See pro/get_from_top_talkers_db.lua?ifid=0&epoch=1612778400&num_minutes=60

**Comment by rmorandell-pgum** [comment]
Hello Simone. Thanks for the answer. I have already fished this call out of the network protocol :). Since it doesn't go through the / rest / api, I wasn't sure whether to use it.
Can I also use this for the future or will this finish in a REST call for some time or later? Like the local sender (ts_schema = top: local_senders) and local receiver (ts_schema = top: local_receivers) in timeseries API.

Thanks for help

**Comment by rmorandell-pgum** [comment]
And another question .. Maybe I don't fully understand the timeseries API. If I compare the host in the timeseries API over the same period, I get different data than in the call pro/get_from_top_talkers_db.lua?ifid=0&epoch=1612778400&num_minutes=60

![image](https://user-images.githubusercontent.com/46994680/107217441-74682200-6a0e-11eb-94ef-6c60af571a11.png)


![image](https://user-images.githubusercontent.com/46994680/107217375-5f8b8e80-6a0e-11eb-8199-0bdbcccbb1ff.png)

so timeseries call same period:

{{URL}}/timeseries/ts.lua?ts_compare=30m&initial_point=true&epoch_begin=1612778400&epoch_end=1612782000&ts_schema=top:local_receivers&ts_query=ifid:{{InterfacId}}&limit=10&extended=true

![image](https://user-images.githubusercontent.com/46994680/107217267-39fe8500-6a0e-11eb-96c7-f6b2a38b26bb.png)

Am I misinterpreting this data? Shouldn't they match?
