### ISSUE TITLE
Cannot add new users to ntopng

### ISSUE THREAD

**Issue by swilkey** [ntop/ntopng#5006]
Cannot create accounts in ntopng

Initially the add new user button was a light colour and I realised that it doesn't like any symbols except _ in the username.  But then it was a dark blue button because I didn't use any symbols except _ however even then, clicking the dark blue add new user button doesn't do anything, the button never goes away and the account is never created.  What am I doing wrong?

![image](https://user-images.githubusercontent.com/8080332/106734771-0815a900-6631-11eb-9696-2d86abc88480.png)

Simone, [03.02.21 14:39]
click X and close. refresh the page. Re-open the add. Retry.

Stephen Wilkey, [03.02.21 14:40]
I had opened the page in a completely new browser before to test it, but testing that now for you
Still no change Simone

Startup line: 
ntopng --interface "tcp://192.168.100.50:5556" --interface "tcp://192.168.100.55:5556" --interface "tcp://192.168.100.60:5556" --interface "tcp://192.168.100.65:5556" --interface "tcp://192.168.100.10:5556" --interface "tcp://*:5556c" --interface "tcp://192.168.100.70:5556"

v.4.2.210201    [Enterprise/Professional build]
GIT rev:        4.2-stable:4a3484203a5e68243e93205d2d53bb69e105e545:20210201
Pro rev:        r3341
Built on:       Ubuntu 18.04.5 LTS
System Id:      C9F0C12C7A07AB20
Platform:       x86_64
Edition:        Enterprise M
License Type:   Permanent
Maintenance:    Until Wed Dec  1 14:48:52 2021 [301 days left]
License:        Af/tTnPqsI+h5A5kmkw8hUUsP5fiojMGUjMZO1q0srPzvIAxQlvDuEZj82iebmHslSK5L
                maf5toZeWGkl/Dz6Xy0TInYefj/593V96wN2dmWBWJIkkDJdUBgRafA61855Uif3ebCrZ
                dxSFnu5vr0efrx03RHvWHXoGeRzn0yGu58v84m1KEKSwSSXeGOvWhrpqDTDyzDlL0pqzY
                33TjsrhAPUDuu2Vcoxusfxz1YvqLRCEaoJzWEg8FRSjALBC/duhwGW45J+OlPSBe3v5CP
                szwZWu9MXhVahutSduvgE2sBFAK+AWHmQKkHq9ITEWEtv/GBq0geIt46HzYiXsz68g==
License Hash:   F2201E620D2A4C4D908DB9388ECE323B16383701320855BC17

**Comment by MatteoBiscosi** [comment]
Hi @swilkey, 
I'm sorry but I'm unable to reproduce the error, already tested on Ubuntu 18 with ntopng version v.4.2.210204
Could you please right click on the page and do 'Inspect Element' (or 'Inspect', depends on your browser) before submitting 'Add New User' and check if there is some error (you are able to see them on the left upper side of the screen).
![Screenshot from 2021-02-04 10-36-04](https://user-images.githubusercontent.com/49585191/106873579-e66dfd80-66d4-11eb-854b-da5dc5f62945.png)

**Comment by swilkey** [comment]
Hi Matteo,

Thanks for your message.  I was unable to see anyything in the upper 
left of my screen, however, here are the errors from inspect - I'm using 
Chrome.


I hope that helps.
Regards,
Stephen
------ Original Message ------

**Comment by MatteoBiscosi** [comment]
I'm sorry @swilkey but i'm unable to see the errors, could you send the errors in an other format?

**Comment by swilkey** [comment]
Hi Matteo,

Thanks for your email.  It turns out you don't need that picture anyway. 
  Every time till now, I've tested using the same password that my 
password manager generated for me the first time I tried it.  This time 
I was in a hurry so I let it generate me a new one and it worked.  So 
here is the problem with this add web user dialog box:
1. usernames can't contain any character except letters, numbers and _ 
(at least from my testing) but it never says that, it just refuses to 
make the button dark blue
2. passwords also can't contain certain characters and if you try, it 
will let you press the button, but the button won't do anything, it 
never tells you you have a problem.  So please test with this password - 
there is some character(s) in that password that your code doesn't like 
but it isn't telling the user: BC/{)'A!mzX94k8

I think this dialog just needs better warnings to the user that there 
are characters in either the username or password field that are 
unnacceptable and then it will fix the problem.

I hope that helps!

Thanks so much.
Stephen

------ Original Message ------

**Comment by simonemainardi** [comment]
@MatteoBiscosi please make the password accept any character, leave only the limit on the length. The backend already handles this, it is just a matter of fixing the HTML `pattern` regex associated to the password. Fix and check:

- user addition
- password change

And make sure to try it with both administrator and non-administrator users

**Comment by swilkey** [comment]
thanks for your work on this guys

**Comment by MatteoBiscosi** [comment]
Hi @swilkey, I fixed the issue right now, from now on passwords should accept every character. Builds are in progress, bear with it for a few hours and update ntopng.
Let me know if you still have some problem.

**Comment by swilkey** [comment]
Thanks so much Matteo
