### ISSUE TITLE
Request Port filter for an interface for top host or top applications

### ISSUE THREAD

**Issue by rmorandell-pgum** [ntop/ntopng#5007]
Hi ntop team,

I use the timeseries API to export historical traffic from flows.

I can get that out cleanly via device and port using 

`ts_query=ifid:{{InterfacId}},device:xxx.xxx.xxx.xxx,port:512&ts_schema=flowdev_port:traffic`

Does the device and port parameters work in any way with data such as top host or top application?
I have generated a custom sub-interface for my exporter (switch). Works wonderfully but it would also be useful if I could also filter the top_sender  (ts_schema=top:local_senders&ts_query=ifid:{{InterfacId}}&limit=10&extended=10) on the port.
In ntopng there is also this filter for the historical flows.

is there a possibility in the API?

thanks for your help

**Comment by simonemainardi** [comment]
This information is not stored per-exporter-port. You should consider using ProbeIP+interface disaggregation to create a sub interface for each switch port.
