### ISSUE TITLE
ERSPAN decode does not work on NTOPNG

### ISSUE THREAD

**Issue by ciscozine** [ntop/ntopng#5008]
Hi,
I have a virtual ubuntu 20.04 and on one nic (ens192) I receive a ERSPAN flow from a Cisco 9500.
On ntopng (community version) I can see only gre flow and not the inner flow.
![image](https://user-images.githubusercontent.com/46693480/106736686-10acb600-6616-11eb-8515-6faaa2b26154.png)

How can I fix? Is there a particolar configuration to do it?
thanks
Fabio

**Comment by simonemainardi** [comment]
Do you have GRE-over-ERSPAN? Please attach a pcap file so we can reproduce.

**Comment by ciscozine** [comment]
Yes, I have a GRE-over-ERSPAN on a Cisco 9500.
In the attach file the pcap file [erspan.zip](https://github.com/ntop/ntopng/files/5921272/erspan.zip)

thanks
fabio

**Comment by simonemainardi** [comment]
Hi, thanks for providing the pcap. Issue is fixed. A new 4.3 dev build is in progress. Hold on a couple of hours, then upgrade.

**Comment by ciscozine** [comment]
Thank you so much!
Fabio

**Comment by ciscozine** [comment]
Hi @simonemainardi 
I have patched the ntopng but it does not work.
I notice two things:
first one, the throughput is not updated

![image](https://user-images.githubusercontent.com/46693480/107244953-e81a2700-6a2e-11eb-8288-d8bca137ad8b.png)

Second one, if I download the pcap file the erspan header is removed only in one direction.

thanks
fabio

**Comment by simonemainardi** [comment]
Detunneling is properly done if you try the pcap you have enclosed.

So basically:
1. You have not properly patched ntopng
2. The traffic in the pcap doesn't resemble the actual traffic

For 2. you can try and attach another pcap. Throughput is updated periodically.

**Comment by ciscozine** [comment]
Hi,
I confirm that I have last patch.
No flow are detected by ntopng. The only flow that I can see is between my client and ntop server. Moreover in the pcap file I can see only one way flow.

In the attach the pcap file
[dump.zip](https://github.com/ntop/ntopng/files/5957133/dump.zip)

Thanks
Fabio

**Comment by simonemainardi** [comment]
This is what is found inside ntopng using the enclosed PCAP (erspan.pcap). As you can see everything matches the encapsulated, detunneled traffic:

![image](https://user-images.githubusercontent.com/3397663/107629527-86da9980-6c62-11eb-98c3-29a0a0f3b3fb.png)

---

dump.pcap doesn't contain GRE-over-ERSPAN but still data is decoded properly

![image](https://user-images.githubusercontent.com/3397663/107629652-b8ebfb80-6c62-11eb-94f2-a628a4c3ccc7.png)

---

> You have not properly patched ntopng

Likely is this one. Make sure to use the latest ntopng packaged or from source.

**Comment by ciscozine** [comment]
Hi,
I confirm that I use the lastest ntop package:

_v.4.2.210211    [Enterprise/Professional build]
GIT rev:        4.2-stable:8ae29ed8452df0918c47f93c63262a12c2f3dcd2:20210211
Pro rev:        r3344
Built on:       Ubuntu 20.04.1 LTS
System Id:      689C1EBA76076B27
Platform:       x86_64
Edition:        Enterprise L (Bundle)
License Type:   Time-Limited [Empty license file]
Validity:       Until Thu Feb 11 20:54:48 2021_

Moreover with ntop GUI, I see ONLY traffic between my client and my ntop server. No other flows are seen. The interface that I monitor is ens192.
![image](https://user-images.githubusercontent.com/46693480/107690693-bca37080-6caa-11eb-853a-36f700158216.png)


If I check with wireshark (same interface, ens192), I see ALL flows (obviously with erspan header).

![image](https://user-images.githubusercontent.com/46693480/107690441-69312280-6caa-11eb-95b8-6f6454cd7505.png)

Thanks
Fabio

**Comment by simonemainardi** [comment]
> A new 4.3 dev build is in progress

As I mentioned, fix was in 4.3 and you are using 4.2. Anyway, now I have back ported to the fix to 4.2 as well. New builds are in progress.

**Comment by ciscozine** [comment]
Thanks. It works.

Fabio
