### ISSUE TITLE
All hosts page add MAC address 

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5014]
Hello
On the All hosts page it would be helpful to show the mac address as well:
<img width="1457" alt="Screenshot 2021-02-03 at 14 06 55" src="https://user-images.githubusercontent.com/38549755/106819762-8d717b80-667a-11eb-963a-e794a49315ee.png">
thanks.

**Comment by simonemainardi** [comment]
this can be added in the 'variable' column

**Comment by simonemainardi** [comment]
Added MAC address as variable column:

![image](https://user-images.githubusercontent.com/3397663/106868763-7ad56180-66cf-11eb-813b-869fd30f4aba.png)
