### ISSUE TITLE
Access the MAC address vendor info from user script

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5015]
Hello,
In order to build custom user scripts it would be helpful to have the vendor information out of the MAC address available in user scripts:
<img width="115" alt="Screenshot 2021-02-03 at 14 02 03 copy" src="https://user-images.githubusercontent.com/38549755/106820198-36b87180-667b-11eb-917b-4409adf2b49e.png">
use case:
create an alarm on every telnet flow towards a Siemens device.
Thanks

**Comment by simonemainardi** [comment]
Implemented

You can access Mac address info as follow:
- host user scripts: `host.getMac`
- flow user scripts: `flow.getClientMac` and `flow.getServerMac`
