### ISSUE TITLE
Problems with more than 4 host pools

### ISSUE THREAD

**Issue by holger-si** [ntop/ntopng#5016]
If I define more than 4 host pools, the newly appended pools will not be functional.
All members of the 5th and more pools remain in the default pool.
In my example I defined host pool "Bielefeld" with member 192.168.122.0/24 as 5th host pool.
All host, that should be in pool "Bielefeld" now, remain in Pool default.

ntopng Professional v.4.3.210205 on Centos

<img width="832" alt="bielefeld" src="https://user-images.githubusercontent.com/78600172/107036888-9e290b00-67ba-11eb-9695-b917fc7b7a5b.PNG">
<img width="815" alt="hostpools" src="https://user-images.githubusercontent.com/78600172/107036906-a5501900-67ba-11eb-8145-a3ce1346bbd7.PNG">
<img width="692" alt="pools" src="https://user-images.githubusercontent.com/78600172/107036907-a5501900-67ba-11eb-8cbb-aca3e1f40c3b.PNG">

**Comment by simonemainardi** [comment]
This is normal. You've hit the professional version limit.

> †† The Enterprise version allows the creation of up to 128 different host pools with an unlimited number of pool members. Professional and Community versions allow the creation of up to 3 different host pools with a maximum of 8 members per pool.

See https://www.ntop.org/products/traffic-analysis/ntop/
