### ISSUE TITLE
302 error (alert_consts.lua:402: attempt to index a nil value)

### ISSUE THREAD

**Issue by DigiAngel** [ntop/ntopng#5018]
And on the heels of upgrading both nDPI and ntopng, I'm now greeted with:
~~~
HTTP/1.1 302 Found Server: ntopng 4.3.210205 (x86_64) Set-Cookie: session=; path=/; HttpOnly; SameSite=lax Location: /lua/http_status_code.lua?message=internal_error&referer=192.168.1.253%3A3000%2F&error_message=...ntopng%2Fshare%2Fntopng%2Fscripts%2Flua%2Fmodules%2Falert_consts.lua%3A402%3A%20attempt%20to%20index%20a%20nil%20value%20%28field%20%27meta%27%29 ...ntopng/share/ntopng/scripts/lua/modules/alert_consts.lua:402: attempt to index a nil value (field 'meta')
~~~
Timestamp on alert_consts.lua:
~~~
-rw-r--r-- 1 root root 20248 Feb  5 10:02 alert_consts.lua
~~~

**Comment by simonemainardi** [comment]
You're somehow using old lua files. Check. meta is always present. Uninstall and reinstall and make sure not to have old files around.

**Comment by DigiAngel** [comment]
alert_consts.lua in the tarball and in the install is:  589c61b914ec8ba66ce24cce4e3a235644a441fc8718207b665f09f22416fa5a.  I ended up just rm -rf /opt/ntopng and installing.

**Comment by simonemainardi** [comment]
None of our packages installs under `/opt/ntopng` so likely the system was messed up with custom files / installations.

**Comment by DigiAngel** [comment]
Well...I configure it with --prefix=/opt/ntopng ...so yes..yes they do.
