### ISSUE TITLE
Opnsense Version

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#5021]
Remove 'there is an update' message on the opnsense version as updating is performed by opnsense update repository.

**Comment by simonemainardi** [comment]
Please, attach a screenshot of the message and where you find it.

Note that official OPNsense packages are available at https://packages.ntop.org/FreeBSD/ and you should not get any 'update' message if you are using our official repos

**Comment by ghost** [comment]
Hi

On the first page after logging in, top right corner.

I appreciate your answer re downloading freebsd packages, however opnsense have their own repository to ensure
a strict upgrade policy, essential for an Internet facing product.
To install alternatives upsets the auditing procedure.
I am sure you will understand the reasoning behind their policy, as do thousands of opnsense users.

Attached is a screen shot of the message.

Regards

Aimee

**Comment by simonemainardi** [comment]
> I appreciate your answer re downloading freebsd packages, however opnsense have their own repository to ensure
a strict upgrade policy, essential for an Internet facing product.

Sure. I agree with you that extreme care must be taken when dealing with any internet facing software. However, As you now, the stricter the policy, the older the software versions or a repo. So my guess is that the official stable version is lagging behind with reference to the ntop official version of package ntopng.

I believe you should ask the opnsense ntopng community package maintainer to patch the code to actually hide the update message. It is not something we can do for two reasons:

1. Even if we patch the code, you won't see it distributed in the opnsense package at least until the package manager wants to update the code
2. We won't be able to notify our users about new versions

If you can get in touch with the package maintainer, I can tell how to patch the code. It's just a line, not hard to do.

> To install alternatives upsets the auditing procedure.

Totally

> Attached is a screenshot of the message.

There is no screenshot attached, actually. Please check.

**Comment by ghost** [comment]
Hi

Maintainer: ranz.fabian.94@gmail.com

The email bounces, contacting them was the first thing I tried, then I put it up as enhancement request.
To be fair it is rather distracting and takes the edge off a good product. 
The option to display/not display update messages is good gui practice.

I used the email to send the screen shot, obviously it didnt work!!

Hopefully this will work.



![Screenshot 2021-02-08 at 10 52 28](https://user-images.githubusercontent.com/12509092/107213865-f94c3f00-6a00-11eb-9840-532e0c30c1cd.png)

**Comment by simonemainardi** [comment]
Yes, now I can see the image. What's the actual running version?

**Comment by ghost** [comment]
Hi
3.4.0 (0) - Community Edition

**Comment by lucaderi** [comment]
Hi the solution to this problem is to use our packages available at  https://packages.ntop.org/FreeBSD

**Comment by ghost** [comment]
Hi

1. no , will stick with opnsense for security/audit reasons.
2. remove ntopng as after the last opnsense upgrade, ntopng > 95% cpu, cpu temperatures > 55C.
3, will wait until opnsense update the version.
