### ISSUE TITLE
Too many hosts for ntopng leading to packet drops and high CPU load. Please tune -x/-X and restart ntopng

### ISSUE THREAD

**Issue by infinitynet2011** [ntop/ntopng#5022]
Hello guys,

We are ISP, we have around 20k our own IPv4  and around 1000 active clients.

ntopng.conf ====
-X=**919428800**
-F="nindex"

Disk Speed =====
dd if=/dev/zero of=/tmp/test2.img bs=4k count=10k oflag=dsync
10240+0 records in
10240+0 records out
41943040 bytes (42 MB) copied, 2.47138 s, **17.0 MB/s**

CPU =====
top - 17:19:54 up 17 days, 15:27,  2 users,  load average: 1.72, 1.99, 2.75
Tasks: 313 total,   1 running, 311 sleeping,   1 stopped,   0 zombie
%Cpu(s):  0.9 us,  3.3 sy,  0.0 ni, 95.3 id,  0.5 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 32736148 total,   299592 free, 32140300 used,   296256 buff/cache
KiB Swap: 13421772+total, 12151871+free, 12699012 used.   248940 avail Mem 

 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                 
13546 ntopng    20   0   37.7g  28.3g   3028 S  63.2 90.5   1:07.15 ntopng                                                                                                                                                  
190 root      20   0       0      0      0 S  11.6  0.0  86:12.61 kswapd1                                                                                                                                                 
35382 influxdb  20   0   59.0g 706644   3116 S   7.9  2.2  10085:49 influxd                                                                                                                                                 
 

If I go higher with -X value, I have another problem:

"You must synchronize the clock of ntopng and remote probe hosts as the clock drift is too large and this will affect collected flow data."

--
Thanks,
GV

**Comment by simonemainardi** [comment]
You have used almost 1B for ntopng maximum number of hosts with -X, this is approximately one fourth of the whole IPv4 Internet. It is an unreasonable value.

-X and -x depend on the actual number of active hosts and flows you have in the traffic. If you have 20k hosts, set -X to 300/400k to allow the hash table to distribute hosts in several buckets and reduce collisions.

Then attach a screenshot. You see the number of hosts and flows inside badges in the top status bar.

**Comment by simonemainardi** [comment]
And note that you have only tuned -X. You have to tune -x as well.

**Comment by infinitynet2011** [comment]
Thank you for reply!
I understand the -X role can you please explain -x role too ?

--
Thanks,
GV

**Comment by simonemainardi** [comment]
straight from `ntopng --help`:

```
 [--max-num-flows|-X] <num>          | Max number of active flows
                                    | (default: 131072)
[--max-num-hosts|-x] <num>          | Max number of active hosts
                                    | (default: 131072)
```
