### ISSUE TITLE
ERROR: [LuaEngineInterface.cpp:829] - storeFlowAlert failed

### ISSUE THREAD

**Issue by mihakralj** [ntop/ntopng#5024]
ntopng is repeatedly throwing an error as seen in the image below.
Version: ntopng Professional v.4.3.210205 (FreeBSD 12.2)

![image](https://user-images.githubusercontent.com/31756078/107134022-284c9e80-68a3-11eb-9987-abf6808d2bae.png)

**Comment by simonemainardi** [comment]
Can be an issue with permissions:

- do a ps aux and check the `<user>` who is currently running ntopng
- stop ntopng
- chown -R `<user>:<user>` /var/db/ntopng
- restart ntopng

**Comment by mihakralj** [comment]
yes, that solved it. Thanks!

**Comment by mihakralj** [comment]
I applied the chown change (and also upgraded to the latest ntopng) - and now my Professional ntopng license claims it is not valid. the SystemID is the same, the data in /usr/local/etc/ntopng.license is the same as before.
License page in ntopng claims the not-valid status and ntopng reverts to community version after 10 mins.

![image](https://user-images.githubusercontent.com/31756078/107162133-09f3ab00-6956-11eb-8ecc-60cd1de2cc25.png)

**Comment by mihakralj** [comment]
from the log:

07/Feb/2021 15:38:19 [Ntop.cpp:2341] Setting local networks to 127.0.0.0/8,fe80::/10
07/Feb/2021 15:38:19 [Redis.cpp:162] Successfully connected to redis 127.0.0.1@0
07/Feb/2021 15:38:19 [Redis.cpp:162] Successfully connected to redis 127.0.0.1@0
07/Feb/2021 15:38:19 [NtopPro.cpp:307] [LICENSE] Reading license from /usr/local/etc/ntopng.license
07/Feb/2021 15:38:19 [NtopPro.cpp:449] [LICENSE] /usr/local/etc/ntopng.license: unable to validate license [License mismatch error]
07/Feb/2021 15:38:19 [NtopPro.cpp:303] [LICENSE] No license file found /usr/local/etc/ntopng.license: reading license from redis
07/Feb/2021 15:38:19 [NtopPro.cpp:449] [LICENSE] FbHnfl6d7M<redacted>rW99n9E/eTSCScZGZjLQUmu9oaUvJQ==: unable to validate license [License mismatch error]
07/Feb/2021 15:38:19 [NtopPro.cpp:521] WARNING: [LICENSE] Invalid license [License mismatch error]
07/Feb/2021 15:38:19 [NtopPro.cpp:538] WARNING: [LICENSE] ntopng will now run in Enterprise L edition for 10 minutes

**Comment by simonemainardi** [comment]
send me the output of ntopng --version privately: mainardi ntop org
