### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by PaoloCmb** [ntop/ntopng#5026]
Hi.
Ntopng often crashes with the following error:
![image](https://user-images.githubusercontent.com/77983398/107233984-77214200-6a23-11eb-9b3b-9bed84d87cea.png)

The problem started after enabling the Traffic Behaviour Analysis.
I also created 19 sub interfaces. I don't know if it could be related to the issue.

LOGS from Journalctl:

ntopng@srvitbsntop01:~$ journalctl -f
-- Logs begin at Wed 2021-02-03 02:00:55 CET. --
Feb 04 14:24:45 srvitbsntop01 ntopng[4932]: [LuaEngine.cpp:572] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/interface/periodic_user_scripts.lua][/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:691: attempt to call a nil value (field 'len')]
Feb 04 14:24:45 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:45 [LuaEngine.cpp:572] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/interface/periodic_user_scripts.lua][/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:691: attempt to call a nil value (field 'len')]
Feb 04 14:24:45 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:45 [LuaEngine.cpp:538] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/interface/periodic_user_scripts.lua][cannot open /usr/share/ntopng/scripts/callbacks/interface/periodic_user_scripts.lua: Too many open files]
Feb 04 14:24:45 srvitbsntop01 ntopng[4932]: [LuaEngine.cpp:538] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/interface/periodic_user_scripts.lua][cannot open /usr/share/ntopng/scripts/callbacks/interface/periodic_user_scripts.lua: Too many open files]
Feb 04 14:24:45 srvitbsntop01 ntopng[4932]: [ThreadedActivity.cpp:399] ERROR: Unable to load the Lua vm [tcp://*:5558c][vm: periodic_user_scripts.lua]
Feb 04 14:24:45 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:45 [ThreadedActivity.cpp:399] ERROR: Unable to load the Lua vm [tcp://*:5558c][vm: periodic_user_scripts.lua]
Feb 04 14:24:45 srvitbsntop01 ntopng[4932]: [LuaEngine.cpp:538] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/interface/periodic_user_scripts.lua][cannot open /usr/share/ntopng/scripts/callbacks/interface/periodic_user_scripts.lua: Too many open files]
Feb 04 14:24:45 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:45 [LuaEngine.cpp:538] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/interface/periodic_user_scripts.lua][cannot open /usr/share/ntopng/scripts/callbacks/interface/periodic_user_scripts.lua: Too many open files]
Feb 04 14:24:45 srvitbsntop01 ntopng[4932]: [ThreadedActivity.cpp:399] ERROR: Unable to load the Lua vm [syslog://*:514][vm: periodic_user_scripts.lua]
Feb 04 14:24:45 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:45 [ThreadedActivity.cpp:399] ERROR: Unable to load the Lua vm [syslog://*:514][vm: periodic_user_scripts.lua]
Feb 04 14:24:45 srvitbsntop01 ntopng[4932]: [LuaEngine.cpp:538] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/stats_update.lua][cannot open /usr/share/ntopng/scripts/callbacks/system/stats_update.lua: Too many open files]
Feb 04 14:24:45 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:45 [LuaEngine.cpp:538] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/stats_update.lua][cannot open /usr/share/ntopng/scripts/callbacks/system/stats_update.lua: Too many open files]
Feb 04 14:24:45 srvitbsntop01 ntopng[4932]: [ThreadedActivity.cpp:399] ERROR: Unable to load the Lua vm [__system__][vm: stats_update.lua]
Feb 04 14:24:45 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:45 [ThreadedActivity.cpp:399] ERROR: Unable to load the Lua vm [__system__][vm: stats_update.lua]
Feb 04 14:24:46 srvitbsntop01 ntopng[4932]: [LuaEngine.cpp:572] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][...opng/scripts/lua/modules/timeseries/drivers/influxdb.lua:917: attempt to index a number value (local 'ret')]
Feb 04 14:24:46 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:46 [LuaEngine.cpp:572] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][...opng/scripts/lua/modules/timeseries/drivers/influxdb.lua:917: attempt to index a number value (local 'ret')]
Feb 04 14:24:47 srvitbsntop01 ntopng[4932]: [LuaEngine.cpp:572] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][...opng/scripts/lua/modules/timeseries/drivers/influxdb.lua:917: attempt to index a number value (local 'ret')]
Feb 04 14:24:47 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:47 [LuaEngine.cpp:572] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][...opng/scripts/lua/modules/timeseries/drivers/influxdb.lua:917: attempt to index a number value (local 'ret')]
Feb 04 14:24:48 srvitbsntop01 ntopng[4932]: [LuaEngine.cpp:572] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][...opng/scripts/lua/modules/timeseries/drivers/influxdb.lua:917: attempt to index a number value (local 'ret')]
Feb 04 14:24:48 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:48 [LuaEngine.cpp:572] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][...opng/scripts/lua/modules/timeseries/drivers/influxdb.lua:917: attempt to index a number value (local 'ret')]
Feb 04 14:24:49 srvitbsntop01 ntopng[4932]: [LuaEngine.cpp:572] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][...opng/scripts/lua/modules/timeseries/drivers/influxdb.lua:917: attempt to index a number value (local 'ret')]
Feb 04 14:24:49 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:49 [LuaEngine.cpp:572] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][...opng/scripts/lua/modules/timeseries/drivers/influxdb.lua:917: attempt to index a number value (local 'ret')]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-7)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-7)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [StoreManager.cpp:120] ERROR: SQL Error: [14][unable to open database file (14)]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngineInterface.cpp:829] ERROR: storeFlowAlert failed (-1)
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngine.cpp:572] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][...opng/scripts/lua/modules/timeseries/drivers/influxdb.lua:917: attempt to index a number value (local 'ret')]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngine.cpp:572] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/timeseries.lua][...opng/scripts/lua/modules/timeseries/drivers/influxdb.lua:917: attempt to index a number value (local 'ret')]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngine.cpp:538] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/interface/periodic_user_scripts.lua][cannot open /usr/share/ntopng/scripts/callbacks/interface/periodic_user_scripts.lua: Too many open files]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngine.cpp:538] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/interface/periodic_user_scripts.lua][cannot open /usr/share/ntopng/scripts/callbacks/interface/periodic_user_scripts.lua: Too many open files]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [ThreadedActivity.cpp:399] ERROR: Unable to load the Lua vm [tcp://*:5558c][vm: periodic_user_scripts.lua]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [ThreadedActivity.cpp:399] ERROR: Unable to load the Lua vm [tcp://*:5558c][vm: periodic_user_scripts.lua]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngine.cpp:572] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/interface/periodic_user_scripts.lua][/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:691: attempt to call a nil value (field 'len')]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngine.cpp:572] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/interface/periodic_user_scripts.lua][/usr/share/ntopng/scripts/lua/modules/user_scripts.lua:691: attempt to call a nil value (field 'len')]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [LuaEngine.cpp:538] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/interface/periodic_user_scripts.lua][cannot open /usr/share/ntopng/scripts/callbacks/interface/periodic_user_scripts.lua: Too many open files]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [LuaEngine.cpp:538] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/interface/periodic_user_scripts.lua][cannot open /usr/share/ntopng/scripts/callbacks/interface/periodic_user_scripts.lua: Too many open files]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: [ThreadedActivity.cpp:399] ERROR: Unable to load the Lua vm [syslog://*:514][vm: periodic_user_scripts.lua]
Feb 04 14:24:50 srvitbsntop01 ntopng[4932]: 04/Feb/2021 14:24:50 [ThreadedActivity.cpp:399] ERROR: Unable to load the Lua vm [syslog://*:514][vm: periodic_user_scripts.lua]

**Comment by simonemainardi** [comment]
Please, report the ntopng configuration file.

**Comment by PaoloCmb** [comment]
-G=/var/run/ntopng.pid
-i=ens192
-m="172.19.0.0/22,172.20.0.0/21,172.21.0.0/24,172.21.1.0/24,192.168.0.0/20,192.168.16.0/20,192.168.32.0/20,192.168.48.0/20,192.168.64.0/20,192.168.80.0/20,192.168.100.0/24,192.168.101.0/24,192.168.102.0/24,192.168.103.0/24,192.168.104.0/24,192.168.105.0/24,192.168.106.0/24,192.168.108.0/24,10.15.0.0/16,172.31.0.0/16,192.168.199.0/24,192.168.250.0/24,192.168.254.0/24,192.168.151.0/24,192.168.152.0/24"
-F="nindex"
-p=/var/lib/ntopng/proto.txt
# nprobe
-i=tcp://*:5558c
# suricata
#-i=syslog://*:9999
# syslog x vpn users
#-i=syslog://*:514@udp
-i=syslog://*:514

**Comment by cardigliano** [comment]
@PaoloCmb it seems that your configuration is leading ntopng to open too many file descriptors, this mainly depends on nindex and timeseries in addition to other features you can enable in ntopng, and scales with the number of interfaces (the fact that you "created 19 sub interfaces" is definitely what triggered this). We will probably try to optimize/reduce the number of file descriptors used, in the meanwhile I suggest you to:
1. disable "Dump Flows" (from the Interface -> "Gear icon" menu) for interfaces where this is not really required (this is limited to 16 interfaces anyway)
2. if you are using RRD, you can also reduce the "level of details" from Settings -> Preferences -> Timeseries (e.g. by setting Host Timeseries to Light or Off, and Layer-7 to None)
