### ISSUE TITLE
ntopng Version

### ISSUE THREAD

**Issue by webparent** [ntop/ntopng#5029]
How do I know the ntop version when generating my license

**Comment by simonemainardi** [comment]
from the CLI you can type ntopng --version

![image](https://user-images.githubusercontent.com/3397663/107334922-9f5a8080-6ab7-11eb-8c09-ddffc514e196.png)

from the UI you can read it from Help -> About

![image](https://user-images.githubusercontent.com/3397663/107335130-da5cb400-6ab7-11eb-996d-92f048d14fd0.png)
