### ISSUE TITLE
ntopng crashed when filter hosts in flows when using view interface.

### ISSUE THREAD

**Issue by comeonbabyzy** [ntop/ntopng#5030]
I need to use a view interface to aggregate physical interfaces. But I met some problems when I use view interface:

1. When I filter hosts in Flows menu, ntopng will crash with a segmentation fault.
2. I cannot see any mac address in hosts. The mac address menu of Hosts disapear.

ntop version: 4.3.210207 
OS: CentOS 7.9.2009
command line: ntopng -i eno1 -i eno2 -view:all

**Comment by simonemainardi** [comment]
Thanks for reporting. The crash is fixed and new builds are in progress.

As per the Mac address, this is not currently supported with view interfaces as indicated in the list of data not available in view interfaces: https://github.com/ntop/ntopng/issues/3383#issue-560509417
