### ISSUE TITLE
How to I add my Device to NTOPNG

### ISSUE THREAD

**Issue by webparent** [ntop/ntopng#5032]
Hello,

I have my ntopng instance hosted in AWS and my router in my office, so how do i cannot the ntopng to collect traffic from my router in a remote site, am only getting network flow from my AWS instance since its where the NTOPNG was hosted.

How to i get the ntopng to get traffic from my mikrotik router.

Thank you

**Comment by simonemainardi** [comment]
See https://www.ntop.org/guides/ntopng/use_cases/mikrotik.html
