### ISSUE TITLE
Users with non admin privileges can not select 2nd interface

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5033]
Hello
In our setup we have non admin users and two monitoring interfaces.
When the non admin user selects the 2nd interface and then wants to open the flow overview, the GUI switches the interface back to the 1st interface.

https://user-images.githubusercontent.com/38549755/107519188-3dca0d00-6bb0-11eb-9bbf-11010e137754.mov

thanks

**Comment by simonemainardi** [comment]
is the non-admin user only assigned to an allowed interface?

**Comment by martinscheu** [comment]
as far as I understand the non-admin user is not restricted. If I remember correctly I only change the "Allow the user to download live traffic and pacp's" to true
<img width="767" alt="Screenshot 2021-02-10 at 21 54 34" src="https://user-images.githubusercontent.com/38549755/107571117-c4034500-6bea-11eb-987d-98fc61ad829b.png">
