### ISSUE TITLE
Double Max Flows from webinterface not working

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5035]
Hello
Running ntopng on a pcap, I get the "Too many flows" warning:
<img width="348" alt="Screenshot 2021-02-10 at 22 56 38" src="https://user-images.githubusercontent.com/38549755/107578347-e9488100-6bf3-11eb-8c89-1c40da3dc48d.png">
Clicking on the "Double Max Flows" opens another pop up:
<img width="488" alt="Screenshot 2021-02-10 at 22 56 49" src="https://user-images.githubusercontent.com/38549755/107578402-fb2a2400-6bf3-11eb-859e-063097405441.png">
I click again on "Too many flows" but nothing happens.
Thank you.

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu , now the problem should be fixed, builds will start soon, bear with it for a few hours and you should be able to update.
Let me know if you still have some problem after the update

**Comment by martinscheu** [comment]
Hi @MatteoBiscosi thanks for the fix. In my case after pressing double max flow I get the new pop up with correct information, that I should change -X value. (out of curiosity: is there a case where an actual value gets changed inside ntopng?)

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu when you press onto the button to double the value, ntopng tries to modify the file with the configuration of ntopng by executing the ntopng-config script with the appropriate parameters, so with enough privileges it should be able to correctly tune -x and -X parameters inside the ntopng configuration file
