### ISSUE TITLE
segfault when accessing /lua/flows_stats.lua?flowhosts_type=local_origin_remote_target

### ISSUE THREAD

**Issue by sezuan** [ntop/ntopng#5036]
Hi,

I'm testing the latest raspberry binary from https://packages.ntop.org (4.3.210207-13074). It always segfaults when I access `/lua/flows_stats.lua?flowhosts_type=local_origin_remote_target`. Unfortunately the stacktrace isn't very helpful:

    Core was generated by `/usr/bin/ntopng /run/ntopng.conf'.
    Program terminated with signal SIGSEGV, Segmentation fault.
    #0  0x000d3038 in ?? ()
    [Current thread is 1 (Thread 0xad8feca0 (LWP 5568))]
    (gdb) bt
    #0  0x000d3038 in ?? ()
    #1  0x000c771c in ?? ()
    #2  0x000b7bc4 in ?? ()
    #3  0x000bf7c4 in ?? ()
    #4  0x000c76f4 in ?? ()
    #5  0x000404dc in ?? ()
    #6  0x0015648c in ?? ()
    Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Are there debug symbols for ntopng?

**Comment by simonemainardi** [comment]
Fixed already. Please upgrade to the latest 2.3.

**Comment by sezuan** [comment]
Thanks, I'll update as soon as the new packages arrive. In the meanwhile I remove '-i view:all'  which seems to mitigate the issue.
