### ISSUE TITLE
Cleanup IP reassignment code

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5038]
- prefs.lua contains row_toggle_ip_reassignment_alerts that is no longer used
- The IP Reassignment script should be migrated under Interfaces
![unknown](https://user-images.githubusercontent.com/4493366/107705259-bdde9880-6cbe-11eb-93b3-af6ee801905a.png)

**Comment by simonemainardi** [comment]
highlighted scripts set a global redis preference that is then read in C to generate alerts.

It is requested to move such scripts under the interface user scripts, and change them to set a per interface redis key, i.e., ntopng.prefs.ifid_%i.XXXX and change the C part to read this per-interface setting.

To do this, I believe you should leverage method onLoad, onUnload, onConfigChange, etc, and read, given an interface pool, all the interfaces associated and do the preference change.

**Comment by simonemainardi** [comment]
where is the lua part that actually sets the flag?
