### ISSUE TITLE
The name of the computer is not good

### ISSUE THREAD

**Issue by tocks53** [ntop/ntopng#504]
Hello,
I have install ntopng 4 days. It's a very good program.

But if i seach the ip of my compter in the texbox a the top of the page. The name is not the good name.

It's a name of a another computer. all my computers are on DHCP.

When i can configure ntopng for take the good translation name and computer ip with DHCP.

This puts the mess in historical. because the IP used by a PC today is not the same as tomorrow.

In these circumstances it is not possible to use ntopng in production.

Thanks for your help

**Comment by lucaderi** [comment]
@tocks53 Is moving to MAC address an option for you? Don't forget to star ntopng if you like it

**Comment by tocks53** [comment]
Thanks for your reply

This is better, but how do laptops? they have 2 MAC address ? wifi and ethernet

ntopng it can resolve the name with the MAC?

Yes, i star ntopng

**Comment by lucaderi** [comment]
Each MAC is a different PC. Would you like to bundle them into a single PC?

All this is NOT available today but we can add it to the roadmap. If interested, please open _individual_ issues for each feature and we'll consider their implementation.

**Comment by tocks53** [comment]
ntopng how to set to work with MAC and not IP?

waiting for update ntopng
