### ISSUE TITLE
Flow alerts page - missing mouse over info

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5040]
Hello
Thinny issue, the mouse over information is missing for the yellow button.
<img width="209" alt="Screenshot 2021-02-14 at 07 47 14" src="https://user-images.githubusercontent.com/38549755/107870598-1453fe80-6e9a-11eb-871e-5baed3d47346.png">
thanks

**Comment by simonemainardi** [comment]
![image](https://user-images.githubusercontent.com/3397663/107966477-3473e280-6fac-11eb-9fa0-d437ae92fe63.png)
