### ISSUE TITLE
Problem installing license

### ISSUE THREAD

**Issue by lgnihlman** [ntop/ntopng#5041]
My installation will not accept my license.
ntopng is running as a service in Windows server 2019

This is shown in the log:
unable to validate license [License mismatch error]
 [NtopPro.cpp:505] WARNING [LICENSE] Invalid license [License mismatch error]

I need help with this.

**Comment by simonemainardi** [comment]
This will be handled privately.

Please, send order id and email associated with the license. Also send a screenshot of page About in ntopng. Send everything to mainardi at ntop dot org
