### ISSUE TITLE
ntopng service not starting,it remains in activating mode

### ISSUE THREAD

**Issue by djha983** [ntop/ntopng#5043]
Hi,

I have installed ntopng on ubuntu 20 and when i try to start the ntopng service using command "sudo systemctl start ntopng" it remains in activating mode.Please let me know what is the issue and how can i solve it,i tried reinstalling ntopng but that did not help.Below is the output of service status command.

systemctl status ntopng
● ntopng.service - ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool
     Loaded: loaded (/lib/systemd/system/ntopng.service; enabled; vendor preset: enabled)
     Active: activating (start) since Tue 2021-02-16 06:12:17 UTC; 33s ago
       Docs: man:ntopng(8)
             file:/usr/share/doc/ntopng/README.Debian
             file:/usr/share/doc/ntopng/UserGuide.pdf.gz
Cntrl PID: 405431 (ntopng)
      Tasks: 24 (limit: 9451)
     Memory: 110.1M
     CGroup: /system.slice/ntopng.service
             └─405431 /usr/sbin/ntopng /etc/ntopng.conf

Feb 16 06:12:17 etvas9r4-test ntopng[405431]: 16/Feb/2021 06:12:17 [Ntop.cpp:744] Adding fe80::20c:29ff:fe5f:7b4b/128 as IPv6 interface address for ens160
Feb 16 06:12:17 etvas9r4-test ntopng[405431]: 16/Feb/2021 06:12:17 [Ntop.cpp:753] Adding fe80::20c:29ff:fe5f:7b4b/64 as IPv6 local network for ens160
Feb 16 06:12:17 etvas9r4-test ntopng[405431]: 16/Feb/2021 06:12:17 [PeriodicActivities.cpp:72] Started periodic activities loop...
Feb 16 06:12:17 etvas9r4-test ntopng[405431]: 16/Feb/2021 06:12:17 [PeriodicActivities.cpp:113] Each periodic activity script will use 2 threads
Feb 16 06:12:17 etvas9r4-test ntopng[405431]: 16/Feb/2021 06:12:17 [NetworkInterface.cpp:2577] Started packet polling on interface ens160 [id: 1]...
Feb 16 06:12:18 etvas9r4-test ntopng[405431]: 16/Feb/2021 06:12:18 [NetworkInterface.cpp:2007] Invalid packet received [len: 1963][max len: 1518].
Feb 16 06:12:18 etvas9r4-test ntopng[405431]: 16/Feb/2021 06:12:18 [NetworkInterface.cpp:2008] WARNING: If you have TSO/GRO enabled, please disable it
Feb 16 06:12:18 etvas9r4-test ntopng[405431]: 16/Feb/2021 06:12:18 [NetworkInterface.cpp:2010] WARNING: Use sudo ethtool -K ens160 gro off gso off tso off
Feb 16 06:12:18 etvas9r4-test ntopng[405431]: [NetworkInterface.cpp:2008] WARNING: If you have TSO/GRO enabled, please disable it
Feb 16 06:12:18 etvas9r4-test ntopng[405431]: [NetworkInterface.cpp:2010] WARNING: Use sudo ethtool -K ens160 gro off gso off tso off

Regards,
Deepak Jha

**Comment by simonemainardi** [comment]
Try to run it manually first:
1. stop
2. Launch with /usr/sbin/ntopng /etc/ntopng.conf

**Comment by simonemainardi** [comment]
No feedback received. Reopen with the requested information if necessary.
