### ISSUE TITLE
Moing from stable to dev

### ISSUE THREAD

**Issue by amastelek** [ntop/ntopng#5044]
The documentation states that to move from stable to dev involves uninstalling and reinstalling.  The docs does not state anything about migrating existing configuration or existing data?

**Comment by simonemainardi** [comment]
please, tell the OS version you are using and I'll add a doc

**Comment by amastelek** [comment]
> 
> 
> please, tell the OS version you are using and I'll add a doc

debian buster

**Comment by simonemainardi** [comment]
See https://www.ntop.org/support/faq/how-can-i-switch-from-stable-to-dev-branch-or-vice-versa/
