### ISSUE TITLE
High CPU usage when minute scripts run

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5048]
![Screen Shot 2021-02-18 at 15 02 07](https://user-images.githubusercontent.com/4493366/108368358-a2ade480-71fa-11eb-8a27-f2f02a98e923.png)
![Screen Shot 2021-02-18 at 14 59 22](https://user-images.githubusercontent.com/4493366/108368365-a5103e80-71fa-11eb-8eeb-ffa42c9a6682.png)
This behaviour is more evident on Windows when activating ntopng on all interfaces

**Comment by simonemainardi** [comment]
Solved in ntopng 5.0+ where host checks are executed in C++.
