### ISSUE TITLE
Can't see client details

### ISSUE THREAD

**Issue by manjotsc** [ntop/ntopng#5049]
Hi,
I am not able access the client pages. See the attached video please.
Thanks,

**PfSense 2.5.0
Version | 4.2.210205 (0) - Community Edition**

You're not supposed to be here!
Internal server error
__.local/share/ntopng/scripts/lua/modules/plugins_utils.lua:997: module 'active_monitoring.am_utils' not found:__no field package.preload['active_monitoring.am_utils']__no file '/var/db/ntopng/plugins0/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/var/db/ntopng/plugins0/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/var/db/ntopng/plugins0/status_definitions/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/flow_status_definitions/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/recipients/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/notifications/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/recipients/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/var/db/ntopng/plugins0/alert_definitions/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/alert_definitions/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/recipients/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/recipients/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/var/db/ntopng/plugins0/ts_schemas/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/timeseries/custom/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/timeseries/schemas/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/timeseries/drivers/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/var/db/ntopng/plugins0/http_lint/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/recipients/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/flow_dbms/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/timeseries/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/i18n/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/lua/5.3/active_monitoring/am_utils.lua'__no file '/usr/local/share/lua/5.3/active_monitoring/am_utils/init.lua'__no file '/usr/local/lib/lua/5.3/active_monitoring/am_utils.lua'__no file '/usr/local/lib/lua/5.3/active_monitoring/am_utils/init.lua'__no file './active_monitoring/am_utils.lua'__no file './active_monitoring/am_utils/init.lua'__no file '/usr/local/lib/lua/5.3/active_monitoring/am_utils.so'__no file '/usr/local/lib/lua/5.3/loadall.so'__no file './active_monitoring/am_utils.so'__no file '/usr/local/lib/lua/5.3/active_monitoring.so'__no file '/usr/local/lib/lua/5.3/loadall.so'__no file './active_monitoring.so'

https://user-images.githubusercontent.com/51430971/108436041-ac464500-7218-11eb-9d14-c2a4f273bbdb.mp4

**Comment by NoireB** [comment]
I'm getting the same error.  I came here to see if there's a fix.

**Comment by simonemainardi** [comment]
@NoireB are you using the latest dev 4.3 or stable 4.2? Check and, in case, update.

**Comment by simonemainardi** [comment]
@manjotsc please tell the installation instructions you have used.

**Comment by manjotsc** [comment]
@simonemainardi I just installed thru the pfsense package manager.

**Comment by simonemainardi** [comment]
Follow the instructions at: https://www.ntop.org/guides/ntopng/third_party_integrations/pfsense.html

**Comment by NoireB** [comment]
@simonemainardi I have the stable 4.2 
![image](https://user-images.githubusercontent.com/79295171/108505166-f82ed380-7284-11eb-8a28-04cbb165d478.png)

**Comment by simonemainardi** [comment]
@NoireB did you follow https://www.ntop.org/guides/ntopng/third_party_integrations/pfsense.html to install?

**Comment by NoireB** [comment]
@simonemainardi I tried but got "No address record" however doing a reinstall via package manager solved the issue.

**Comment by dragoangel** [comment]
@NoireB actually reinstall doesn't helps, @simonemainardi you provide link to Pro version, while people use Community edition which installed via package manager, in any case I don't think this change anything - Community\Pro works same at core. I use external InfluxDB(1.8.3) for Timeseries and issue also reproduce on ntopng Community v.4.2.210205. In lua/system_stats.lua I don't see Redis and InfluxDB tabs at all, many screens in Ui display errors, etc.

For me to solve issue I was need to change setting of Timeseries Host to any and back to previously used one and restart ntopng service. Don't know what this changed under the hood for ntopng - rewrited local settings to correct new format maybe? Before I had 3.8 version of ntopng. In any case after restart ntopng started to see InfluxDB and Redis correctly again and issue solved.

**Comment by simonemainardi** [comment]
@dragoangel we are not the maintainers of the packaged community version. This is the reason why I encouraged to install packages from our repository. Those packages are under our direct control, are tested by us, and we can fix possible issues. Note that also using our repo allows you to run in community mode and you are not forced to use a license.

**Comment by dragoangel** [comment]
Hi @simonemainardi thanks for the tip

**Comment by blefev** [comment]
Also having this issue with the pfsense package.

**Comment by manjotsc** [comment]
@blefev In my case it does this behavior after 15 to 16 hours of runtime. Need to restart ntopng after that.

**Comment by dragoangel** [comment]
@manjotsc this comes with update from 3.8 to 4.2 I think.

@blefev try please change time series settings to influxdb as example, save them, even wrong, and then back to your correct settings.

**Comment by manjotsc** [comment]
@dragoangel Setting timeseries to influxdb doesn't work with incorrect information. It reverts back automatically. Any other solution?

**Comment by dragoangel** [comment]
@manjotsc maybe that was solution to me, but will not help to who not have influxdb. @blefev does reinstall with purge ntong data help you?

**Comment by blefev** [comment]
Deleting data and reinstalling made it work for about a day, but the issue came back.

**Comment by looterz** [comment]
Have had this issue for awhile, deleting data and reinstalling does let it work for a bit but it always comes back.

**Comment by shabsta** [comment]
Same issues here, I have removed the package and reinstalled and the issue still exists immediately after reinstalling via package manager - which should be the correct / preferred method to manage packages.

**Comment by aaali22** [comment]
Hi, just a quick note what fixed the issue for me (NTOPNG-0.8.13_10  on PFSense 2.5.1-RELEASE):
under "Developer - Plugins" an error message showed up instead of the list of installed plugins (HTTP/1.1 302 Found Set-Cookie: [] bad argument #1 to 'for iterator' (table expected, got nil))
After clicking "Reload Plugins" the plugins showed up and the internal server errors disappeared (at least for now ;-) )

**Comment by dragoangel** [comment]
@aaali22 yeah, same for me. Figure it out just yesterday, but not had a chance to leave feedback here. Issue will be back after time unfortunately.

**Comment by manjotsc** [comment]
@aaali22  Thanks, It does make it work, but after some time it strikes back.

**Comment by simonemainardi** [comment]
> but after some time it strikes back

please give further details

**Comment by dragoangel** [comment]
@simonemainardi all same as in description

**Comment by simonemainardi** [comment]
> but after some time it strikes back

after how much time?

**Comment by dragoangel** [comment]
> after how much time?
Sorry, hard to say, will try to figure out.

**Comment by manjotsc** [comment]
It happens between 27 to 32 hours, about day and half.

**Comment by simonemainardi** [comment]
It seems you are using the community edition that is not packaged nor maintained by us.

As commented  https://github.com/ntop/ntopng/issues/5085#issuecomment-790649993 :

> We are not the maintainers of the package in the pfsense repository. Please, install according to these instructions and it will work https://packages.ntop.org/FreeBSD/

Please install the packaged version we distribute or get in touch with the package maintainers.

**Comment by ghost** [comment]
> @NoireB actually reinstall doesn't helps, @simonemainardi you provide link to Pro version, while people use Community edition which installed via package manager, in any case I don't think this change anything - Community\Pro works same at core. I use external InfluxDB(1.8.3) for Timeseries and issue also reproduce on ntopng Community v.4.2.210205. In lua/system_stats.lua I don't see Redis and InfluxDB tabs at all, many screens in Ui display errors, etc.
> 
> For me to solve issue I was need to change setting of Timeseries Host to any and back to previously used one and restart ntopng service. Don't know what this changed under the hood for ntopng - rewrited local settings to correct new format maybe? Before I had 3.8 version of ntopng. In any case after restart ntopng started to see InfluxDB and Redis correctly again and issue solved.

Thank you! This solution works for me
`need to change setting of Timeseries Host to any and back to previously used one and restart ntopng service.`

**Comment by dragoangel** [comment]
@sergeysj unfortunately there no perm fix, easier is to reload plugins, no restart needed
