### ISSUE TITLE
Unify user interface buttons

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5050]
![Screen Shot 2021-02-19 at 11 13 24](https://user-images.githubusercontent.com/4493366/108490866-81550300-72a3-11eb-9daa-d36f53f19e89.png)
![Screen Shot 2021-02-19 at 11 13 19](https://user-images.githubusercontent.com/4493366/108490869-82863000-72a3-11eb-87cb-e63524f9448f.png)

Either the button group is used or to used. Colors must be identical. I want to see consistency in pages

**Comment by simonemainardi** [comment]
please resolve once-for-all the issue with Christmas trees as well

**Comment by lucaderi** [comment]
verified as fixed
