### ISSUE TITLE
What is the difference between "ntopng Enterprise L" and "ntopng Enterprise L Boundle Linux"?

### ISSUE THREAD

**Issue by pwchi** [ntop/ntopng#5051]
I am can't find any about "ntopng Enterprise L Boundle Linux" License Information.

What is the difference between "**ntopng Enterprise L (x64)**" and "**ntopng Enterprise L Boundle Linux (x64)**"?

![image](https://user-images.githubusercontent.com/780551/108518201-41256d00-7303-11eb-936e-dbbcc505c3bc.png)

Thank you very much.

**Comment by cardigliano** [comment]
The Bundle includes n2disk 1g and nProbe Pro as described
