### ISSUE TITLE
Complie error

### ISSUE THREAD

**Issue by geekgao** [ntop/ntopng#5053]
Make and showed messages like this (a piece of output):

`src/Flow.cpp:490:61: error: ‘struct ndpi_flow_struct::<unnamed union>::<unnamed>’ has no member named ‘detected_os’
    cli_host->inlineSetOSDetail((char*)ndpiFlow->protos.http.detected_os);`

I missing somgthing ?

**Comment by MatteoBiscosi** [comment]
Hi @geekgao , do you have nDPI up-to-date?

**Comment by geekgao** [comment]
> Hi @geekgao , do you have nDPI up-to-date?

Yes. I follow the document https://github.com/ntop/ntopng/blob/dev/doc/README.compilation 
Run git clone https://github.com/ntop/nDPI.git 

It is wrong branch ?  @MatteoBiscosi

**Comment by simonemainardi** [comment]
your ntopng is outdated as the issue was fixed in 

commit aeabe2a9a79539887ac76075347ced2e396f8c53
Author: Simone Mainardi <mainardi@ntop.org>
Date:   Wed Feb 3 12:58:08 2021 +0100

    Compilation fix after nDPI HTTP: fix user-agent parsing

    Fix after https://github.com/ntop/nDPI/pull/1124/commits/80ad2e245495fa7dfd35b6a56995dfe94723feae

Update ntopng to the tip of its dev branch. Run `git pull` inside ntopng sources.
