### ISSUE TITLE
Documentation feature

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5054]
Hello,
When I analyze network data with ntopng, findings I need to report for the operators of the network. Therefore I would be helpful to have export / documentation functionality: 
- lists, e.g. flow list or host list: export as cvs
- map overviews, e.g. service map: export as pdf or picture format
- detail pages, e.g. flow details: export as pdf or picture format
nice would be as well a "capture of the moment", a whole pdf report of flow-, warning- and alarm list.

Thank you.

**Comment by lucaderi** [comment]
@martinscheu Can you please get in touch with @JudyyHopps so that you can tell her what you exactly want to be documented?
