### ISSUE TITLE
Show filter settings in lists

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5055]
Hello
Currently filtered items are shown with the filter sign.
It would be helpful if the filtered item is shown as well, e.g.:
<img width="1239" alt="Screenshot 2021-02-21 at 07 41 24" src="https://user-images.githubusercontent.com/38549755/108618808-555f8c00-7421-11eb-83cf-ff270caf3aab.png">

Thank you

**Comment by simonemainardi** [comment]
Applied filters are shown in the page title (to save space on dropdowns)

See 
![image](https://user-images.githubusercontent.com/3397663/108717908-1ebb6b80-751e-11eb-83e1-724b0b988a75.png)

Moreover, we are likely to change all the dropdowns using a more general filtering syntax.

There was an issue preventing certain fields to be added to the title. Issue is now fixed.
