### ISSUE TITLE
Telemetry email regex is too strict

### ISSUE THREAD

**Issue by Cxarli** [ntop/ntopng#5056]
The following regex is used by the Telemetry Email field:

`^(([A-Za-z0-9._%+-]|\s)+<)?[A-Za-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,6}>?$`

This requires the TLD to be between 2 and 6 alpha characters. However, this does not cover a lot of newer TLDs, one of which is [travelersinsurance](https://nic.travelersinsurance/) at 18 characters. It also excludes non-latin TLDs such as [ファッション](http://nic.ファッション) (though these may be written in Punycode like `xn--bck1b9a5dre4c`, in which case the `-` should be added to the regex).

My proposed solution would be to just use `<input type="email">` and let the browser handle the validation.

**Comment by simonemainardi** [comment]
@gabryon99 please change this using the same validation we have used for the email endpoint

**Comment by gabryon99** [comment]
Updated the email regex for the telemetry prefs page, I've tested it with the TLD proposed above.
