### ISSUE TITLE
Implement client/server heuristic

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5058]
For TCP flows for which the 3WH has not been observed, in case one of the ports (client or server) is < 1024, the server will be identified as the one with the lower port.

This has to be implemented in Flow::processDetectedProtocol(). Doing this will enable other protocols (e.g. SMTP/SMTPS) to be cleaned up.

For UDP flows, a similar solution could be implemented, but it needs to be better analysed.

Please make sure that this implementation takes care of ZMQ interfaces and of the code below 
![image](https://user-images.githubusercontent.com/4493366/108689000-d76eb400-74f8-11eb-9677-cb3b81633719.png)

![Screen Shot 2021-02-22 at 10 28 40](https://user-images.githubusercontent.com/4493366/108688944-c4f47a80-74f8-11eb-93e4-01d1dcc8f6d5.png)

**Comment by simonemainardi** [comment]
I would like to have this implemented earlier in the packet processing chain, to also fix the in-memory flow with guessed client and server.

Currently, for packet interfaces, when we have a packet we retrieve the in-memory flow as

```
   /* Updating Flow */
  flow = getFlow(srcMac, dstMac, vlan_id, 0, 0, 0,
                 l4_proto == IPPROTO_ICMP ? &icmp_info : NULL,
                 &src_ip, &dst_ip, src_port, dst_port,
                 l4_proto, &src2dst_direction, last_pkt_rcvd, last_pkt_rcvd, len_on_wire, &new_flow, true);
```

Note that the function above returns a boolean `new_flow`. Given this, We can try and implement @lucaderi heuristics

> For TCP flows for which the 3WH has not been observed

in pseudo code as follows:

```
if(new_flow
   && isTCP()
   && !flags->SYN /* cannot be 1st or 2nd part of the TWHS */
   && src_port < dst_port
   && src_port < 1024 /* Can be removed to have the heuristic applied also to non-well-known-ports */) {
  /* Throw the newly allocated flow */
  delete flow;

   /* Swap */
  <swap srcMac with dstMac>;
  <swap src_ip with dst_ip>;
  <swap src_port with dst_port>;

  goto <getFlow() function above that will now allocate an actually swapped flow>
}

```

Here we pay the cost of two allocations and two lookups but only for the first packet of a flow and only when the condition on ports hold so I believe this is affordable.

NOTE that this will not solve the issue for non-TCP flows (e.g., DNS). However, we can try and slightly modify the code above to also handle this case.

I also think this logic can co-exist with the one implemented for ZMQ interfaces.

**Comment by lucaderi** [comment]
@simonemainardi This is not correct as already discussed. Swap can't happen for unidirectional flows

**Comment by simonemainardi** [comment]
we can add extra checks to see if the ip address is broadcast or multicast

**Comment by simonemainardi** [comment]
Implemented in referenced commits. Tests `peers_swap_heuristic_01.yaml` and `peers_swap_heuristic_02.yaml` implemented to verify the implementation.
