### ISSUE TITLE
Timeseries: Alerts & Flows per Host

### ISSUE THREAD

**Issue by TimotheusBachinger** [ntop/ntopng#5061]
Hi ntop,

we want to query the number of alerts and flows of one host in a specific time interval.
We would have assumed to achieve this by using something like:
`http://<URL>:3000/lua/rest/get/timeseries/ts.lua?ts_schema=host:total_alerts&ts_query=ifid:2,host:<IP>&limit=1000&epoch_begin=1607000000&epoch_end=1614086841`
or by using `host:total_flows`. The corresponding host had flows and alerts in the given time range.
However we only receive data for `host:traffic`.

Is there anything we need to configure to get this data?

Regards
Timi

**Comment by simonemainardi** [comment]
Hi.

Please use:
- http://<URL>:3000/lua/rest/v1/get/timeseries/ts.lua for timeseries, e.g., host:traffic
- http://<URL>:3000/lua/rest/v1/get/alert/ts.lua for timeseries of alerts

Also note the `v1` in the URLs. You should use it to make sure your API is always at the same version

**Comment by TimotheusBachinger** [comment]
Hi,

when using rest/v1, I am receiving INTERNAL_ERROR (-6):
`http://:3000/lua/rest/v1/get/timeseries/ts.lua?ts_schema=host:total_alerts&ts_query=ifid:2,host:<IP>&limit=1000&epoch_begin=1607000000&epoch_end=1614086841`

`{"rc_str":"INTERNAL_ERROR","rc_str_hr":"Internal error","rsp":[],"rc":-6}`

**Comment by simonemainardi** [comment]
Hi,

Issue was just that no-data-points was wrongly interpreted as 'internal error'. 

I have fixed this behavior to make it consistent with non-v1 REST API. No data is now returned as an empty array


```
## DATA
simone@devel:~/ntopng$ curl -uadmin:admin1 "http://localhost:3000/lua/rest/v1/get/timeseries/ts.lua?ts_schema=host:traffic&ts_query=ifid:0,host:192.168.2.222"
{"rsp":{"count":12,"step":300,"query":{"host":"192.168.2.222","ifid":"0"},"max_points":60,"schema":"host:traffic","start":1614591000,"additional_series":[],"statistics":{"max_val_idx":11,"max_val":18116.276666667,"by_serie":[{"average":1831.9877777778,"95th_percentile":0,"total":6595156.0},{"average":334.51138888889,"95th_percentile":0,"total":1204241.0}],"95th_percentile":0,"min_val_idx":0,"average":2166.4991666667,"min_val":0,"total":7799397.0},"series":[{"tags":{"ifid":"0","host":"192.168.2.222"},"data":[0,0,0,0,0,0,0,0,0,0,6249.9566666667,15733.896666667],"label":"bytes_sent"},{"tags":{"ifid":"0","host":"192.168.2.222"},"data":[0,0,0,0,0,0,0,0,0,0,1631.7566666667,2382.38],"label":"bytes_rcvd"}]},"rc":0,"rc_str_hr":"Success","rc_str":"OK"}

# NO DATA
simone@devel:~/ntopng$ curl -uadmin:admin1 "http://localhost:3000/lua/rest/v1/get/timeseries/ts.lua?ts_schema=host:traffic&ts_query=ifid:0,host:192.168.2.229"
{"rc_str_hr":"Success","rc":0,"rsp":[],"rc_str":"OK"}
```

New stable builds in progress. They will be ready in a couple of hours.
