### ISSUE TITLE
docs: pfSense install

### ISSUE THREAD

**Issue by tigattack** [ntop/ntopng#5062]
The docs for installing ntopng on pfSense appear to be incorrect.

I believe the [section for adding the repo to pfSense CE](https://www.ntop.org/guides/ntopng/third_party_integrations/pfsense.html#pfsense-ce) should also be FreeBSD 12, perhaps with a note that this applies only to pfSense CE 2.5 and higher.

As per the [pfSense 2.5 release announcement](https://www.netgate.com/blog/pfsense-plus-21-02-release-and-pfsense-ce-2-5-0-release-now-available.html?utm_content=154610918&utm_medium=social&utm_source=twitter&hss_channel=tw-80797684), both pfSense CE and pfSense Plus are now based on FreeBSD 12.2.

**Comment by cardigliano** [comment]
@tigattack thank you for pointing this out, the doc was realted to 2.4.x and needs to be updated

**Comment by tigattack** [comment]
Happy to help 🙂

**Comment by cardigliano** [comment]
Fixed (it will be updated overnight)
