### ISSUE TITLE
Too many flows warning after upgrading to v.4.2.2 

### ISSUE THREAD

**Issue by olg33** [ntop/ntopng#5067]
We have been using ntopng to monitor traffic flow at remote hub locations. So far all have been working smoothly, but the system started prompting to upgrade to the latest stable release (4.2) we currently have installed (rel. 4.0.200609 (10480))

After upgrading one location,the following  pop-up warning keeps appearing everywhere:

![Capture](https://user-images.githubusercontent.com/61751672/109046898-3ff99480-76a3-11eb-90cf-83cb7aa8f8ec.JPG)

Indeed, the VM shows high CPU usage (100%) but from a networking perspective, all interfaces (Networking equipment and Virtual Machine) show no packet drops, that is only reported by Ntopng 

Traffic in other locations is higher than the one where ver.4.2.2 was installed but no pop-up warnings, high CPU usage or packet loss is reported by Ntopng there.

That's why we do believe some tweaking needs to be done for ver.4.2.2 to work properly.

The warning message asks to "tune -x/-X and restart" but we haven't been able to find any document that details this operation.

We are running ntopng community edition in an Ubuntu 20.04 VM with 4 CPUs and 32G of RAM.

 Any clue to fix this issue would be appreciated.

Thank you

Thank you.

**Comment by simonemainardi** [comment]
Please, follow what is said in the yellow toast and report. Also explain the installation procedure you have used and if you are using packages at packages.ntop.org

**Comment by olg33** [comment]
Thanks.

That's the first thing we tried to do but I haven't found a reference to "tune -x/-X". How can I do it? Is there any document that describes that procedure?

For the upgrade we followed instructions from https://packages.ntop.org/apt-stable/ , downloaded binary for Ubuntu 20.04.

 The whole process was easy and error-free.

**Comment by simonemainardi** [comment]
yes, just add them to the configuration file. See `ntopng -h`. Version 4.3 adds them automatically but as you are with 4.2 you have to do it manually. Then restart ntopng.

**Comment by simonemainardi** [comment]
Did you have a chance to try?

**Comment by olg33** [comment]
Sorry for the delay. We are restoring the 4.0.2 VM and from there we'll proceed to upgrade to 4.2.2 again. This time we want go step-by-step documenting everything until we get to were we got stuck before. I'll let you know how it goes.

**Comment by olg33** [comment]
We have re-created the problem from scratch and here are the steps taken:

- A new VM was re-loaded with Ntopng Rel. 4.0.200609 (10480). Upon installation, we applied live traffic and we could verifiy that like the rest of the VMs running Rel. 4.02, no issue whatsoever was detected, even under high traffic load no alarm or warning was displayed.

- Upgraded to Rel v.4.2.210301. Like in the first upgrade, no issues were reported during the process.

- In order to increase the number of flows and hosts, added the following lines to the /etc/ntopng/ntopng.conf file:
    
    -X=130000
    -x=130000

- After saving and rebooting the VM, the issue was still present as shown in the following snapshot: 

![Capture2](https://user-images.githubusercontent.com/61751672/109567448-5a70ab00-7ab3-11eb-852f-9024a9d87a6b.JPG)

Please advise if the X/x parameters are correct.

Now I'd like to provide more more details about our setup:

Our Hypervisor is VMware ESXi 6.7 and the VM runs Ubuntu 20.04.2 LTS. The vnic cards are 10GB using Adapter type VMXNET 3

Mentioning this because besides the excessive number of flows, the other issue mentioned in the alarm is high packet drops.

Looking at the packet drops count, it's massive:

![Capture](https://user-images.githubusercontent.com/61751672/109568933-a02e7300-7ab5-11eb-9760-4cfa29286f6d.JPG)

That prompted us to look at the network drivers because as shown in the above picture, , Rel.4.2 it uses PF_RING instead of pcap for packet capture. 

During the upgrade we made sure that ZC drivers were installed:

apt-get install pfring-drivers-zc-dkms 

The upgrade notes mention that using PF_RING ZC user-space libraries require a license. In our case, we are using the community edition, so could it be part of the problem? Is there a way to force it to use pcap instead?

Thanks.

**Comment by simonemainardi** [comment]
> Please advise if the X/x parameters are correct.

You have approx. 95k active flows (see the top badge), so you are almost hitting the 130k limit you have set. This limit must be much larger than the actual value. Try and set it to 500k. Same for hosts. So

```
-X="500000"
-x="500000"
```

Note that you are monitoring a `br0` interface, I am not sur PF_RING ZC can be run here, @cardigliano can give further recommendations. Keep in mind that you'll be able to make approx 1Gbps without drops or you'll have to use RSS as explained in https://www.ntop.org/ntopng/best-practices-for-running-ntopng/

**Comment by cardigliano** [comment]
Let me add that br0 is a software interface attached to the linux bridge, which is not supported by RSS and ZC drivers. For best performance it is recommended to move to a physical interface if possible (Intel if you want to use ZC)

**Comment by olg33** [comment]
@simonemainardi I have made the suggested changes and the flows warning has cleared. Thanks! 
Initially I set the limit to 130K because ntopng -h states that the maximum number of flows/hosts is 131K
![Capture](https://user-images.githubusercontent.com/61751672/109722861-48f2d600-7b7b-11eb-9675-d581d34f7249.JPG)

So what's the real limit?

@cardigliano I'll change the br0 interface but please note that in our servers running Rel. 4.0.200609 (10480) they work fine with br0 and haven't seen any issue until we upgraded to V.4.2  That's why I'd like to know if we can set pcap to capture traffic instead of PF_RING on V.4.2 


Thank you.

**Comment by simonemainardi** [comment]
> I have made the suggested changes and the flows warning has cleared. 

Thanks for reporting. Note that likely the issue was still present also on the older installation, but  there was no warning.

We don't enforce a maximum here as it depends on the installation. Practical maximum values however are in the order of millions. 

>  I set the limit to 130K because ntopng -h states that the maximum number of flows/hosts is 131K

You set the value to the default value so this had no effect.

**Comment by cardigliano** [comment]
> @cardigliano I'll change the br0 interface but please note that in our servers running Rel. 4.0.200609 (10480) they work fine with br0 and haven't seen any issue until we upgraded to V.4.2 That's why I'd like to know if we can set pcap to capture traffic instead of PF_RING on V.4.2

As my colleague said, it is likely you had the same issue before, but the warning was not implemented in that version. Switching to pcap would even make it worse as it has lower performance.

**Comment by cardigliano** [comment]
In short, it seems this just requires the -x/-X tuning, please add the below to the configuration file and restart ntopng, and the warning should disappear. Please reopen in case.

-X="524288"
-x="524288"
