### ISSUE TITLE
Noisy low goodput alert

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5068]
The way low goodput is implemented is not optimal as many (by nature) low goodput protocols create a lot of useless noise that increases the host score and hides the real problems.

![Screen_Shot_2021-02-24_at_19_44_51](https://user-images.githubusercontent.com/4493366/109049789-f2981a00-76d8-11eb-8362-338e67c6d864.png)

By default alerts for protocols such as those indicated in the picture must be suppressed.

This ticket depends on  #5066.

**Comment by simonemainardi** [comment]
Some low goodput alerts also show up a 0% goodput that is suspicious. These must be checked.

**Comment by simonemainardi** [comment]
Fixed in

https://github.com/ntop/ntopng/blob/9ae7f01ccc7dbe0280b56b19ae483ccf42b0832e/scripts/plugins/alerts/network/low_goodput/user_scripts/flow/low_goodput.lua#L32
