### ISSUE TITLE
netflow vs ipfix behavior

### ISSUE THREAD

**Issue by hemskgren** [ntop/ntopng#507]
Hi

If i change my cisco asr1000 router from sending netflow to ipfix towards nprobe.

I still see traffic but in the flow tab change behavior to look like this.

![image](https://cloud.githubusercontent.com/assets/10794918/14646466/d5effc1e-0659-11e6-8c6d-e59e27eae34c.png)

and the "info" for each flow say "This flow cannot be found (expired ?)"
If i change back to netflow on the router the flow tab look good again and the flow info works.

Regards
Christer

**Comment by ValentinaViscarelli** [comment]
@hemskgren 
Could you send me a pcap file that you can capture with tcpdump from the socket where nprobe receive the data?
Obviously you have to set your router in order to send ipfix data.

**Comment by hemskgren** [comment]
[ipfix-ntop.zip](https://github.com/ntop/ntopng/files/232211/ipfix-ntop.zip)

**Comment by hemskgren** [comment]
Hi

starting nprobe v.7.3.160425 (r5052) with the following. "-b 2"

# /usr/local/bin/nprobe --zmq tcp://127.0.0.1:5556 -b 2 -i none -n none --collector-port 2001

log discard reciving ipfix.

25/Apr/2016 09:46:40 [collect.c:368] Received flow with invalid count [sentPkts: 0][sentOctets: 0]: discarded [num_flows: 2027]
25/Apr/2016 09:46:40 [collect.c:368] Received flow with invalid count [sentPkts: 0][sentOctets: 0]: discarded [num_flows: 2027]
25/Apr/2016 09:46:40 [collect.c:368] Received flow with invalid count [sentPkts: 0][sentOctets: 0]: discarded [num_flows: 2027]
25/Apr/2016 09:46:40 [collect.c:368] Received flow with invalid count [sentPkts: 0][sentOctets: 0]: discarded [num_flows: 2027]
25/Apr/2016 09:46:40 [collect.c:368] Received flow with invalid count [sentPkts: 0][sentOctets: 0]: discarded [num_flows: 2027]
25/Apr/2016 09:46:40 [collect.c:368] Received flow with invalid count [sentPkts: 0][sentOctets: 0]: discarded [num_flows: 2027]
25/Apr/2016 09:46:40 [collect.c:368] Received flow with invalid count [sentPkts: 0][sentOctets: 0]: discarded [num_flows: 2027]
^C25/Apr/2016 09:46:40 [cache.c:1224] Redis Cache [0 total/0.0 get/sec][0 total/0.0 set/sec]
25/Apr/2016 09:46:40 [nprobe.c:487] Received shutdown request... [signal: 2]
25/Apr/2016 09:46:41 [nprobe.c:5076] nProbe is shutting down...
25/Apr/2016 09:46:41 [nprobe.c:5103] Exporting pending buckets...
25/Apr/2016 09:46:41 [nprobe.c:5124] Pending buckets have been exported...
25/Apr/2016 09:46:43 [engine.c:3224] Export thread terminated [exportQueue=0]
25/Apr/2016 09:46:43 [nprobe.c:5183] Flushing queued flows...
25/Apr/2016 09:46:43 [nprobe.c:5186] Freeing memory...
25/Apr/2016 09:46:43 [plugin.c:279] Terminating plugins.
25/Apr/2016 09:46:43 [cache.c:1224] Redis Cache [0 total/0.0 get/sec][0 total/0.0 set/sec]
25/Apr/2016 09:46:43 [nprobe.c:5291] Still allocated 0 hash buckets
25/Apr/2016 09:46:43 [nprobe.c:2693] Processed packets: 0 (max bucket search: 0)
25/Apr/2016 09:46:43 [nprobe.c:2676] Fragment queue length: 0
25/Apr/2016 09:46:43 [nprobe.c:2702] Flow export stats: [0 bytes/0 pkts][0 flows/0 pkts sent]
25/Apr/2016 09:46:43 [nprobe.c:2709] Flow collection: [collected pkts: 2027][processed flows: 11175]
25/Apr/2016 09:46:43 [nprobe.c:2712] Flow drop stats:   [0 bytes/0 pkts][0 flows]
25/Apr/2016 09:46:43 [nprobe.c:2717] Total flow stats:  [0 bytes/0 pkts][0 flows/0 pkts sent]
25/Apr/2016 09:46:43 [nprobe.c:5304] Cleaning globals
25/Apr/2016 09:46:43 [nprobe.c:5323] nProbe terminated.

**Comment by lucaderi** [comment]
![screen shot 2016-04-25 at 09 54 11](https://cloud.githubusercontent.com/assets/4493366/14777167/b15a7d0e-0acb-11e6-8eab-534ee4d24c59.png)

As you can see the flows do not contain bytes+packets as expected, Please make sure your flow source exports them. Due to this, nprobe complains.

**Comment by simonemainardi** [comment]
Solution given. No feedback received. Closing.
