### ISSUE TITLE
Alerts: Timeseries vs Data Timestamp

### ISSUE THREAD

**Issue by TimotheusBachinger** [ntop/ntopng#5072]
Hi ntop Team,

we're currently seeing a discrepancy in the timestamp between the timeseries and data of alerts.

`lua/rest/v1/get/alert/data.lua?ifid=0&epoch_begin=1614211200&epoch_end=1614297500&status=historical `
returns:
`{
  "rsp": {
    "1614211200": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ]
  },
  "rc": 0,
  "rc_str": "OK",
  "rc_str_hr": "Success"
}`

and
`lua/rest/v1/get/alert/data.lua?ifid=0&epoch_begin=1614211200&epoch_end=1614297500&status=historical`
returns:
```
{
  "rc": 0,
  "rsp": [
    {
      "count": 1,
      "entity": "Host",
      "type": "alert_threshold_cross",
      "drilldown": "<REMOVED>",
      "date": "1614256626",
      "severity": "error",
      "msg": "<REMOVED>",
      "entity_val": "<REMOVED>",
      "duration": 240
    },
    {
      "count": 1,
      "entity": "Host",
      "type": "alert_threshold_cross",
      "drilldown": "<REMOVED>",
      "date": "1614268206",
      "severity": "error",
      "msg": "<REMOVED>",
      "entity_val": "<REMOVED>",
      "duration": 60
    }
  ],
  "rc_str_hr": "Success",
  "rc_str": "OK"
}
```

So -according to the timeseries call -  we would expect two alerts on this day:
11h: 1
14h: 1

But the alerts data call tells me:
```
date -u -d @1614256626
Do 25. Feb 12:37:06 UTC 2021
```
and
```
date -u -d @1614268206
Do 25. Feb 15:50:06 UTC 2021
```
So there is a difference of one hour - which we cannot explain, as we would assume the epoch timestamps is always in UTC.

Regards
Timi

**Comment by simonemainardi** [comment]
Thanks for reporting. Issue was due to the encoding `json.encode` which was not behaving nicely with tables having integer numbers starting from zero as keys. It was assuming they were arrays and ignoring element indexed at 0, causing the timeseries to be shifted by 1 hour.

New stable builds are in progress.
