### ISSUE TITLE
When listing raw flows UI fails to scale correctly.

### ISSUE THREAD

**Issue by Syl4r-v** [ntop/ntopng#5073]
When listing "raw flows" the table fails to scale correctly. It doesn't happen straight away but when I change the amount of rows shows from 10 to something else. 
<img width="1575" alt="Screenshot 2021-02-26 at 13 37 47" src="https://user-images.githubusercontent.com/77612587/109303347-576f8380-7843-11eb-87b7-88eaccd5136a.png">
<img width="1603" alt="Screenshot 2021-02-26 at 13 45 53" src="https://user-images.githubusercontent.com/77612587/109303354-59d1dd80-7843-11eb-918e-32f5e4f70770.png">

version: 4.2.210222 (13271)

**Comment by Syl4r-v** [comment]
There was actually 2 different tables that were scaling wrong. I think your fix only affected the first one that is shown with the data graph. The other one is the raw flows querying table, that is mostly unusable because it cant fit into the browser and even with max zoom outs, it is too big

**Comment by lucaderi** [comment]
We're reworking the table, more news will follow

**Comment by MatteoBiscosi** [comment]
Fixed. Currently raw flows are can be found under 'Dashboard->Historical Flow Explorer' and the previous 'Raw Flows' button is going to redirect into that page
