### ISSUE TITLE
Add time navigation in alerts page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5075]
With many alerts, it is hard to find the correct one in case a problem is reported. It is required to add a time navigation facility that allows to drill down alerts by time. Something similar to Kibana
![Screen Shot 2021-02-26 at 14 09 34](https://user-images.githubusercontent.com/4493366/109304997-618e8380-783d-11eb-8f75-cd66186d7bef.png)

**Comment by simonemainardi** [comment]
implemented
