### ISSUE TITLE
nIndex invalid SQL

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5076]
26/Feb/2021 16:20:28 [NIndexFlowDB.cpp:622] select(time: 1614350640/1614352560[1920 sec], select: [IPV4_SRC_ADDR,IPV4_DST_ADDR,IP_DST_PORT,IP_SRC_PORT,VLAN_ID,TOTAL_BYTES,PACKETS,FIRST_SEEN,LAST_SEEN,INFO,STATUS,L7_PROTO,PROTOCOL,PROFILE,SRC2DST_DSCP], where: [((IPV4_SRC_ADDR=192.168.1.178 OR IPV4_DST_ADDR=192.168.1.178) AND (VLAN_ID=0) AND (IPV4_SRC_ADDR=5.200.6.157 OR IPV4_DST_ADDR=5.200.6.157) AND (L7_PROTO=78) AND (IP_PROTOCOL_VERSION=4)) AND (FIRST_SEEN >= 1614350700) AND (LAST_SEEN <= 1614352500) AND (FLOW_TIME BETWEEN 1614350640 AND 1614352560)], records=0:100)
26/Feb/2021 16:20:28 [NIndexFlowDB.cpp:682] [nIndex] Found 7 hits in 26.93 msec
26/Feb/2021 16:20:37 [NIndexFlowDB.cpp:622] select(time: 1614351451/1614351571[120 sec], select: [*], where: [((IPV4_SRC_ADDR=192.168.1.178) AND (VLAN_ID=0) AND (IPV4_DST_ADDR=5.200.6.157) AND (IP_SRC_PORT=63491) AND (IP_DST_PORT=50001) AND (IP_PROTOCOL_VERSION=4)) AND (FIRST_SEEN = 1614351511) AND (LAST_SEEN = 1614351511) AND (FLOW_TIME BETWEEN 1614351451 AND 1614351571)], records=0:9999)
26/Feb/2021 17:15:01 [NIndexFlowDB.cpp:868] ERROR: [nIndex] Error Invalid where specified
26/Feb/2021 17:15:01 [get_nindex_flows.lua:314] [get_nindex_flows.lua:118] ERROR: Invalid where specified
26/Feb/2021 17:15:09 [NIndexFlowDB.cpp:868] ERROR: [nIndex] Error Invalid where specified
26/Feb/2021 17:15:09 [get_nindex_flows.lua:314] [get_nindex_flows.lua:118] ERROR: Invalid where specified
26/Feb/2021 17:15:28 [NIndexFlowDB.cpp:868] ERROR: [nIndex] Error Invalid where specified
26/Feb/2021 17:15:28 [get_nindex_flows.lua:314] [get_nindex_flows.lua:118] ERROR: Invalid where specified
26/Feb/2021 17:16:24 [NIndexFlowDB.cpp:868] ERROR: [nIndex] Error Invalid where specified
26/Feb/2021 17:16:24 [get_nindex_flows.lua:314] [get_nindex_flows.lua:118] ERROR: Invalid where specified
26/Feb/2021 17:17:30 [NIndexFlowDB.cpp:868] ERROR: [nIndex] Error Invalid where specified
26/Feb/2021 17:17:30 [get_nindex_flows.lua:314] [get_nindex_flows.lua:118] ERROR: Invalid where specified

**Comment by cardigliano** [comment]
It seems this is no longer reproducible. Please reopen in case.
