### ISSUE TITLE
WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/network.lua] [.../ntopng/scripts/lua/modules/notifications/recipients.lua:576: attempt to index a nil value]

### ISSUE THREAD

**Issue by ajaufura** [ntop/ntopng#5077]
I am having this issue here. Any idea how to resolve this? Thanks.

Error :
27/Feb/2021 20:09:06 [AlertCheckLuaEngine.cpp:81] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/network.lua] [.../ntopng/scripts/lua/modules/notifications/recipients.lua:576: attempt to index a nil value]

27/Feb/2021 20:09:07 [AlertCheckLuaEngine.cpp:81] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/interface/host.lua] [.../ntopng/scripts/lua/modules/notifications/recipients.lua:576: attempt to index a nil value]

Ntopng Version :
Version: 4.3.210226 [Enterprise/Professional/Embedded build]
GIT rev: dev:9b6c9b7c602aaac0d10f33a49e01cdf4262d66eb:20210226
Pro rev: r3610
Built on: Raspbian GNU/Linux 10 (buster)
Platform: armv7l
Edition: Enterprise Embedded
License Type: Time-Limited [Empty license file]
Validity: Until Sat Feb 27 20:16:35 2021

**Comment by simonemainardi** [comment]
Thanks for reporting. Issue is fixed. New builds are in progress and will be ready in a couple of hours.
