### ISSUE TITLE
Error after plugin changes

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5079]
Feb 28 05:31:29 pc-deri ntopng[5435]: [LuaEngine.cpp:572] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/startup.lua][...png/plugins0/callbacks/interface/flow/iec60870_5_104.lua:48: bad argument #1 to 'concat' (table expected, got nil)]
Feb 28 05:31:29 pc-deri ntopng[5435]: 28/Feb/2021 05:31:29 [LuaEngine.cpp:572] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/startup.lua][...png/plugins0/callbacks/interface/flow/iec60870_5_104.lua:48: bad argument #1 to 'concat' (table expected, got ni

**Comment by MatteoBiscosi** [comment]
Not able to reproduce again the error
