### ISSUE TITLE
how to add devices to be monitored in ntopng

### ISSUE THREAD

**Issue by J101** [ntop/ntopng#508]
Hi please help me on how to add devices to be monitored in ntopng. Thank you.

How to add interfaces
How to add devices (routers,servers etc)

NOTE: i already installed ntopng in my desktop and as of the moment the only device in interfaces is my pc.

**Comment by simonemainardi** [comment]
you need to make sure ntopng is monitoring an interface that receives all the network traffic you are interested into. If you run ntopng locally on your PC it will very likely show you only the PC traffic and some broadcast.

Here it is explained in detail how to properly feed ntopng with network traffic: http://www.ntop.org/pf_ring/port-mirror-vs-network-tap/
