### ISSUE TITLE
Rework hosts map

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5080]
The hosts map page is very primitive: it must be changed in a more modern implementation with
- bubble widget
- REST-based drill down to avoid generating data in the page

**Comment by lucaderi** [comment]
@gabryon99 You still need to
- use the bubble widget
- Avoid page reload when changing value from the filtering menu

Please complete this ticket ASAP so we can validate the widgets

**Comment by gabryon99** [comment]
I've add the Bubble Widget inside the page. Now I have to avoid the page reloading when clicking the dropdown menu

**Comment by gabryon99** [comment]
Added `destroyAndUpdate` to force the reload of widget's data in order to avoid the page reloading.

**Comment by lucaderi** [comment]
![Screen Shot 2021-03-08 at 16 05 03](https://user-images.githubusercontent.com/4493366/110339285-4a634900-8028-11eb-90bb-7efb8be758be.png)
![Screen Shot 2021-03-08 at 16 04 56](https://user-images.githubusercontent.com/4493366/110339288-4b947600-8028-11eb-808e-013de86c3bfa.png)

Last two fixes before closing the issue
- on Safari the host click no longer works
- Add a "Filter:" label before the dropdown menu and enlarge it (X axis) as some labels are cut

**Comment by lucaderi** [comment]
verified as fixed
