### ISSUE TITLE
flow dump to es 7 failed.

### ISSUE THREAD

**Issue by zcy382725** [ntop/ntopng#5082]
what i run:
ntopng -F "es;ntopng;ntopng-%Y.%m.%d;es_url;user:password" -v 4

what i got:

03/Mar/2021 06:35:46 [ElasticSearch.cpp:214] {
  "name" : "ed534a44b6a8",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "3dccBjplTyq5i65JECGVmg",
  "version" : {
    "number" : "7.10.1",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "1c34507e66d7db1211f66f3513706fdf548736aa",
    "build_date" : "2020-12-05T01:00:33.671820Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
 [http return code: 200]

and

03/Mar/2021 06:35:58 [ElasticSearch.cpp:169] ES: Buffered request with 1 flows (799 bytes)
03/Mar/2021 06:35:58 [Utils.cpp:1359] [JSON] {"error":"Incorrect HTTP method for uri [/] and method [POST], allowed: [GET, HEAD, DELETE]","status":405}
03/Mar/2021 06:35:58 [Utils.cpp:1519] Posted JSON to 25.25.206.109:9200
03/Mar/2021 06:35:58 [Utils.cpp:1457] [NAMELOOKUP_TIME 0.00][CONNECT_TIME 0.00][APPCONNECT_TIME 0.00][PRETRANSFER_TIME 0.00][REDIRECT_TIME 0.00][STARTTRANSFER_TIME 0.00][TOTAL_TIME 0.00]
03/Mar/2021 06:35:58 [ElasticSearch.cpp:176] ERROR: ES: POST request for 1 flows (799 bytes) failed

just want to know if the -F "es;..." support elasticsearch version 7.x.x?

**Comment by simonemainardi** [comment]
It does support elasticsearch 7.

Check this https://github.com/elastic/elasticsearch-php/issues/1014

Also report the ntopng version used.

**Comment by zcy382725** [comment]
my bad, forget the "/_bulk"
