### ISSUE TITLE
Alerts do not include the interface

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5084]
In ELK (please check also other formats) alerts do not include the interface name/id, thus they are all mixed in case ntopng monitors multiple network interfaces.

This information needs to be added.

**Comment by lallori** [comment]
@simonemainardi in the alert-* index it would also be good to have a copy of the source.ip and destination.ip values in two new fields called in the same way of the ntopng--* index (IPV4_SRC_ADDR and IPV4_DST_ADDR)  so that it would be possible to create mixed dashboards with the two indexes and filter using ips.

**Comment by lucaderi** [comment]
Or better, the alert includes the interfaceId but that on an external system such as ELK is meaningless as the interface name should be used.

**Comment by simonemainardi** [comment]
There is a single function `alert_utils.formatAlertNotification` that should be used to format the alert and that adds the interface name, given the interface id

```
scripts/plugins/endpoints/telegram_alert_endpoint/alert_endpoints/telegram.lua:   local msg = alert_utils.formatAlertNotification(alert, {nohtml=true, add_cr=false, no_bracket_around_date=true, emoji=true, nodate=true})
scripts/plugins/endpoints/discord_alert_endpoint/alert_endpoints/discord.lua:   local msg = alert_utils.formatAlertNotification(alert, {nohtml=true, add_cr=true, no_bracket_around_date=true, emoji=true})
scripts/plugins/endpoints/slack_alert_endpoint/alert_endpoints/slack.lua:        local msg = alert_utils.formatAlertNotification(notif, {nohtml=true, show_severity=false})
scripts/plugins/endpoints/syslog_alert_endpoint/alert_endpoints/syslog.lua:      msg = alert_utils.formatAlertNotification(json.decode(notif), {
scripts/plugins/endpoints/email_alert_endpoint/alert_endpoints/email.lua:      message_body[#message_body + 1] = alert_utils.formatAlertNotification(notif, {nohtml=true})
```

Please, check and make sure it is used everywhere, apart from special cases such as ECS.

**Comment by lallori** [comment]
I would be good to have the interface name as a separate field in the alerts index since the interfaceId value inside the message field is a subfield in a json which cannot be filtered inside ELK.

**Comment by MatteoBiscosi** [comment]
Hi @lallori i added the id and the name of the observer interface as ecs format suggest https://www.elastic.co/guide/en/ecs/current/ecs-observer.html.
Builds are in progress, bear with it for a few hours and let me know.
However in ecs schema there cannot be two identical fields so your suggest on having two ip copies it is not possible. Unfortunately the same goes for having the interface Id value as a separate field. The message follows the ecs format so I cannot add an external field

**Comment by lallori** [comment]
@MatteoBiscosi thank you very much!

Is there a way to make the two indexes (alerts and ntopng) communicate? I would like to filter for ip address so that if I have an alert it would be possible to filter for the traffic which generated that alert. I tried to use scripted fields and aliases with no success.

**Comment by simonemainardi** [comment]
You execute the first query on the alerts index, and then, you execute a second query on the flows index using fields and search criteria of interest.

Do not think in terms of JOINs but in terms of separate queries. Elasticsearch is NoSQL and JOINs would be tremendously expensive.
