### ISSUE TITLE
Flow- Individual Flow - Error Seen "You're not supposed to be here!"

### ISSUE THREAD

**Issue by piscisaustrinus** [ntop/ntopng#5085]
Click on Flow Icon in left panel, it shows overview of active flows.
Click on individual active flow, the error pasted below is seen. Post upgrade I am not able to see individual flow details.

Version - 4.2.210205 (0) - Community Edition
Platform amd64-unknown-freebsd12.2 [amd64][] - 64 bit
Error- Text..

You're not supposed to be here!
Internal server error
__.local/share/ntopng/scripts/lua/modules/plugins_utils.lua:997: module 'active_monitoring.am_utils' not found:__no field package.preload['active_monitoring.am_utils']__no file '/var/db/ntopng/plugins0/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/var/db/ntopng/plugins0/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/var/db/ntopng/plugins0/status_definitions/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/flow_status_definitions/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/recipients/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/notifications/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/recipients/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/var/db/ntopng/plugins0/alert_definitions/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/alert_definitions/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/recipients/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/recipients/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/var/db/ntopng/plugins0/ts_schemas/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/timeseries/custom/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/timeseries/schemas/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/timeseries/drivers/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/var/db/ntopng/plugins0/http_lint/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/recipients/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/flow_dbms/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/timeseries/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/i18n/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/lua/5.3/active_monitoring/am_utils.lua'__no file '/usr/local/share/lua/5.3/active_monitoring/am_utils/init.lua'__no file '/usr/local/lib/lua/5.3/active_monitoring/am_utils.lua'__no file '/usr/local/lib/lua/5.3/active_monitoring/am_utils/init.lua'__no file './active_monitoring/am_utils.lua'__no file './active_monitoring/am_utils/init.lua'__no file '/usr/local/lib/lua/5.3/active_monitoring/am_utils.so'__no file '/usr/local/lib/lua/5.3/loadall.so'__no file './active_monitoring/am_utils.so'__no file '/usr/local/lib/lua/5.3/active_monitoring.so'__no file '/usr/local/lib/lua/5.3/loadall.so'__no file './active_monitoring.so'

**Comment by simonemainardi** [comment]
how did you install ntopng? are you using our official packages at https://packages.ntop.org/ ?

**Comment by piscisaustrinus** [comment]
Pulled it form the pfsense repository.
Earlier version of ntopng was working with pfsense release 2.4.x.
Post pfsense update to 2.5.0-RELEASE (amd64) and Ntop install from its package manager to version 4.2.210205, I am facing the issue.
--

**Comment by simonemainardi** [comment]
We are not the maintainers of the package in the pfsense repository. Please, install according to these instructions and it will work https://packages.ntop.org/FreeBSD/

Otherwise you should get in touch with the pfsense package manager and ask him to update.
