### ISSUE TITLE
No MAC, LLDP on some interfaces

### ISSUE THREAD

**Issue by olmanolsztyn** [ntop/ntopng#5087]
I added SNMP devices (Juniper MX) and see no MACs and LLDP neighbors on random interfaces.
I turned on SNMP debug and saw logs ERROR: Item limit reached in mac addresse discovery .

**Comment by lucaderi** [comment]
After troubleshooting it seems that the problem is that we limit our discovery to some specific portTypes. We'll remove this restriction in the next build.

**Comment by simonemainardi** [comment]
@olmanolsztyn can you confirm this is solved? Do they appear?

By the way, I have feedback that now speed is missing from certain interfaces:

![image](https://user-images.githubusercontent.com/3397663/111275553-8f920700-8636-11eb-88a5-ecc91fae321f.png)

Can you please do an anmpwalk on OID `1.3.6.1.2.1.2.2.1.5` and see if the speed is shown for interfaces that are seemingly not showing their speed inside ntopng.

Thank you.

**Comment by olmanolsztyn** [comment]
Interfaces with null speed are xe- (10gbps interface) and lt- (logical tunnel interface)
Sample from snmpwalk both for xe- and lt- :
IF-MIB::ifSpeed.543 = Gauge32: 4294967295

Another things is even now lldp neighbors are present but ntopng doesnt drawing maps with these interfaces.

**Comment by simonemainardi** [comment]
Can you please repeat the walk `1.3.6.1.2.1.2.2.1.5` on interfaces 513 and 512?

----

By the way

> IF-MIB::ifSpeed.543 = Gauge32: 4294967295

Seems you are hitting this with 10Gbps interfaces (https://cric.grenoble.cnrs.fr/Administrateurs/Outils/MIBS/?oid=1.3.6.1.2.1.2.2.1.5)

> If the bandwidth of the interface is greater than the maximum value reportable by this object then this object should report its maximum value (4,294,967,295) and ifHighSpeed must be used to report the interace's speed. For a sub-layer which has no concept of bandwidth, this object should be zero.

Can you try and snmpwalk on:

1.3.6.1.2.1.31.1.1.1.15 (ifHighSpeed)

**Comment by olmanolsztyn** [comment]
Snmpwalk response:

IF-MIB::ifHighSpeed.512 = Gauge32: 10000
IF-MIB::ifHighSpeed.513 = Gauge32: 10000
IF-MIB::ifHighSpeed.514 = Gauge32: 10000
IF-MIB::ifHighSpeed.515 = Gauge32: 10000

**Comment by simonemainardi** [comment]
Thanks, please, check this as well

> Can you please repeat the walk 1.3.6.1.2.1.2.2.1.5 on interfaces 513 and 512

**Comment by olmanolsztyn** [comment]
IF-MIB::ifSpeed.512 = Gauge32: 4294967295
IF-MIB::ifSpeed.513 = Gauge32: 4294967295
IF-MIB::ifSpeed.514 = Gauge32: 4294967295
IF-MIB::ifSpeed.515 = Gauge32: 4294967295

**Comment by simonemainardi** [comment]
I've added support for `ifHighSpeed` to support the 10Gbit interfaces as highlighted. A new build will be ready overnight. Thanks for supporting this.
