### ISSUE TITLE
Can not enable user scripts

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5089]
Hello
In the actual dev build I can not enable own user scripts. System internal scripts I can enable.

https://user-images.githubusercontent.com/38549755/110102699-64412980-7da5-11eb-9010-bcf8afe504b6.mov

**Comment by gabryon99** [comment]
Hello @martinscheu, can you try to open the Developer Tools of your browser, select the Network/Requests tab and take a screenshot of the response to the request with the URL `edit_user_script_config`?

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu, builds are in progress, wait for a few hours and the issue should be solved. After updating ntopng let me know if everything works fine or if you still have some problem.

**Comment by simonemainardi** [comment]
@martinscheu can you confirm this issue is solved?

**Comment by MatteoBiscosi** [comment]
Closed for inactivity, if needed please reopen the issue.
