### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by arrmo** [ntop/ntopng#509]
First off, my apologies - these are just some questions, as I try to use the data in MySQL ... not issues at all! But not sure how else to ask, so sorry if this makes your "issues" list look longer. That all said, I really like ntopng, and the MySQL data - thanks!

And, the questions .. ;).
1) the end goal, I want to plot the top (some number ... say 3, 5, or 10) clients on the subnet. Historical data, such as for an interface (Timeseries), line chart with the items on top of each other - the top clients over time. Is this already existing somewhere? Assuming not, more below ... :)
2) the information in INFO doesn't seem to match the source or destination, so what exactly is it?
3) PROTOCOL seems to be L4, matching to http://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml, right? But do you have more information on L7_PROTO (i.e. how to turn the numbers into applications)?
4) Is there a way to generate a report ... basically a snapshot of a particular page / plot?
5) LAST_SWITCHED - FIRST_SWITCHED is never really longer than ~ 300 seconds. Is this because flows are not allowed to run longer than this, before being dumped out? If so, makes sense, but also ... is this value configurable (i.e. can I set it shorter?)?
6) Ubuntu (even xenial) is running ntopng v2.2 (at the newest), I'd like to use some of what you have noted in v2.3. Is there a respository I can add, so apt will keep me up to date?

Thanks again for all the help, and a great program!

**Comment by simonemainardi** [comment]
> 1) the end goal, I want to plot the top (some number ... say 3, 5, or 10) clients on the subnet. Historical data, such as for an interface (Timeseries), line chart with the items on top of each other - the top clients over time. Is this already existing somewhere? Assuming not, more below ... :)

Presently it is not available but we will introduce this feature at some point. Please feel free to post a feature request.

> 2) the information in INFO doesn't seem to match the source or destination, so what exactly is it?

It contains extra information,. .e.g., ssl certificates, HTTP URLS, etc.

> 3) PROTOCOL seems to be L4, matching to http://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml, right? 

right

> But do you have more information on L7_PROTO (i.e. how to turn the numbers into applications)?

`ntopng --help`

> 4) Is there a way to generate a report ... basically a snapshot of a particular page / plot?

yes, in the Pro version there is a whole section for the reports.

> 5) LAST_SWITCHED - FIRST_SWITCHED is never really longer than ~ 300 seconds. Is this because flows are not allowed to run longer than this, before being dumped out? If so, makes sense, but also ... is this value configurable (i.e. can I set it shorter?)?

It's hard coded but it can be configured: just change line https://github.com/ntop/ntopng/blob/dev/include/ntop_defines.h#L168 and recompile

> 6) Ubuntu (even xenial) is running ntopng v2.2 (at the newest), I'd like to use some of what you have noted in v2.3. Is there a respository I can add, so apt will keep me up to date?

http://packages.ntop.org/ and go for the nightly builds

**Comment by arrmo** [comment]
Thanks so much! A few minor thoughts, below.
1) Will do! I'd be happy to try to help out if I can - but I admit, a bit overwhelmed by Lua and the structure of the pages ... :(. I can get the SQL queries working, but getting it on a page will be a challenge ... but willing to try!
5) Will do. BTW, after make ... does make install put things in the right places? If so, I'll remove the Ubuntu version, and build myself.
6) Agreed ... odd that it's reporting v2.3. I think they broke something. In any case ... no apt repository, rather debs, right? As above, I'll build my own if it will install.

Thanks again!
