### ISSUE TITLE
Crash on Flows View.

### ISSUE THREAD

**Issue by ListenNjoy** [ntop/ntopng#5090]
Hello,

When i click on flows on left side in ntopng, ntopng chrashes with error bellow.

ntopng[37969]: segfault at 190000012f ip 00000000004a1dbe sp 00007f050192c570 error 4 in ntopng[400000+392000]
Mar  5 07:55:52 Ntop-NtopNG kernel: Code: 00 0f b7 ea 48 8b 04 eb 48 85 c0 75 18 bf 01 00 00 00 be 30 00 00 00 e8 e0 a2 f6 ff 48 85 c0 48 89 04 eb 74 67 48 8b 4c 24 40 <f3> 0f 6f 00 66 49 0f 6e cc 66 49 0f 6e d5 66 0f 6c d1 66 0f d4 d0
Mar  5 07:55:53 Ntop-NtopNG systemd: ntopng.service: main process exited, code=killed, status=11/SEGV

Version:        4.3.210305 [Enterprise/Professional build]
GIT rev:        dev:9df8afc6cb10df94d16bdb26b7f1ebc4342e4ccc:20210305

Flow are written to influxdb, 

InfluxDB shell version: 1.8.4

Anybody else experiencing the same.?

**Comment by ListenNjoy** [comment]
I removed ntopng and installed it again, the same error when i press the flow button on the left.

Now i see this in logs after crash/restart.

Mar  8 13:44:27 Ntop-NtopNG ntopng: 08/Mar/2021 13:44:27 [startup.lua:16] [user_scripts.lua:1092] Script 'suspicious_tcp_probing' configuration is missing from subdir 'flow'. New user script?
Mar  8 13:44:27 Ntop-NtopNG ntopng: 08/Mar/2021 13:44:27 [startup.lua:16] [user_scripts.lua:1092] Script 'suspicious_tcp_syn_probing' configuration is missing from subdir 'flow'. New user script?
Mar  8 13:44:27 Ntop-NtopNG ntopng: 08/Mar/2021 13:44:27 [startup.lua:16] [user_scripts.lua:1092] Script 'tcp_connection_refused' configuration is missing from subdir 'flow'. New user script?

Version:        4.3.210308 [Enterprise/Professional build]
GIT rev:        dev:58ca238e0834e4cd8e74d7434134e9d97e1044c1:20210308
Pro rev:        r3625

**Comment by ListenNjoy** [comment]
I did a reset of ntopng and all is back to normal,

**Comment by simonemainardi** [comment]
> ntopng[37969]: segfault at 190000012f ip 00000000004a1dbe sp 00007f050192c570 error 4 in ntopng[400000+392000]
Mar 5 07:55:52 Ntop-NtopNG kernel: Code: 00 0f b7 ea 48 8b 04 eb 48 85 c0 75 18 bf 01 00 00 00 be 30 00 00 00 e8 e0 a2 f6 ff 48 85 c0 48 89 04 eb 74 67 48 8b 4c 24 40 0f 6f 00 66 49 0f 6e cc 66 49 0f 6e d5 66 0f 6c d1 66 0f d4 d0
Mar 5 07:55:53 Ntop-NtopNG systemd: ntopng.service: main process exited, code=killed, status=11/SEGV

This was resolved and already available in the latest dev/stable
