### ISSUE TITLE
Interfaces list size depends on screen resolution

### ISSUE THREAD

**Issue by ottorei** [ntop/ntopng#5091]
When multiple interfaces are configured as subinterfaces with dynamic traffic disaggregation (Probe IP + Ingress Interface) the list can not show all available interfaces if the screen resolution is not high enough or the browser window is not maximized. The list should probably have it's own scrollbar when items can not fit into the screen.

The issue exists on the following version:
v.4.2.210304    [Enterprise/Professional build]
GIT rev:        4.2-stable:e647f518e28f68fb370c908dc12b909caafa1294:20210304
Pro rev:        r3345
Built on:       Ubuntu 20.04.1 LTS
Platform:       x86_64
Edition:        Enterprise M

**Comment by lucaderi** [comment]
In order to avoid exceeding the max capacity, ntopng limits the number of interfaces up to a max to 16 in the enterprise M (see https://www.ntop.org/products/traffic-analysis/ntop/).

**Comment by ottorei** [comment]
> 
> 
> In order to avoid exceeding the max capacity, ntopng limits the number of interfaces up to a max to 16 in the enterprise M (see https://www.ntop.org/products/traffic-analysis/ntop/).

Does this really apply to dynamically created disaggregated interfaces? I see that I have 22 interfaces total where 19 of them are just disaggregated interfaces from one nprobe instance.

**Comment by simonemainardi** [comment]
> Does this really apply to dynamically created disaggregated interfaces?

Yes. It also applies to dynamically created interfaces.

**Comment by cardigliano** [comment]
@ottorei please note this has been improved in the new dev version with a scrollable dropdown, it will be available with the next stable release.
