### ISSUE TITLE
apt-get install ntopng got error while updating 

### ISSUE THREAD

**Issue by kopigreenx** [ntop/ntopng#5098]
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

`Unpacking ntopng (4.2.210309-13524) ...
dpkg: error processing archive /var/cache/apt/archives/ntopng_4.2.210309-13524_amd64.deb (--unpack):
 trying to overwrite '/usr/share/ntopng/httpdocs/css/bootstrap-nav-wizard.css', which is also in package ntopng-data 3.2+dfsg1-1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/ntopng_4.2.210309-13524_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)`

how to fix this error ?
thank

**Comment by cardigliano** [comment]
@kopigreenx did you install the ntopng version distributed by Ubuntu before perhaps? It seems you have ntopng-data 3.2+dfsg1-1 installed, which conflict with our package. To fix this please uninstall it (apt-get remove ntopng ntopng-data) and install form our repo.

**Comment by kopigreenx** [comment]
thanks @cardigliano ,,,
