### ISSUE TITLE
MySQL error: The total number of locks exceeds the lock table size

### ISSUE THREAD

**Issue by lucadistefano** [ntop/ntopng#510]
After 3 days of traffic tracked the following error occours.
To let it work again I restarted mysql and ntopng.
No error appears on mysql log.

19/Apr/2016 05:49:02 [MySQLDB.cpp:439] Attempting to connect to MySQL for interface tcp://10.62.5.111:5553...
19/Apr/2016 05:49:02 [MySQLDB.cpp:479] Succesfully connected to MySQL [127.0.0.1:ntopng] for interface tcp://10.62.5.111:5553
19/Apr/2016 05:49:02 [MySQLDB.cpp:45] ERROR: MySQL error: The total number of locks exceeds the lock table size
19/Apr/2016 05:49:02 [MySQLDB.cpp:46] ERROR: INSERT INTO `flowsv4` (VLAN_ID,L7_PROTO,IP_SRC_ADDR,L4_SRC_PORT,IP_DST_ADDR,L4_DST_PORT,PROTOCOL,BYTES,PACKETS,FIRST_SWITCHED,LAST_SWITCHED,INFO,JSON,NTOPNG_INSTANCE_NAME,INTERFACE_ID,PROFILE) VALUES ('0','81','171836787','0','171835841','0','1','504','12','1461037679','1461037714','',COMPRESS('{ "8": "10.62.5.115", "7": 0, "12": "10.62.1.193", "11": 0, "4": 1, "57590": 81, "57591": "ICMP", "2": 6, "1": 504, "24": 6, "23": 0, "22": 1461037679, "21": 1461037714, "json": { "58500": "icmp", "5": "0", "9": "0", "10": "65535", "58508": "0", "13": "0", "14": "65535", "15": "0.0.0.0", "16": "0", "17": "0", "32": "2048", "36": "60", "37": "60", "38": "0", "39": "0", "52": "62", "53": "62", "55": "0", "60": "4", "95": "0", "148": "22558518", "150": "1461037678", "151": "1461037713", "152": "1461037678245", "153": "1461037713231", "57552": "0", "57595": "0.000000", "57596": "0.000000", "57597": "0.000000", "57570": "256", "57577": "0", "57581": "0", "57582": "0", "57583": "0", "57584": "0", "57591": "ICMP", "57863": "34986", "57864": "34985", "42": "22558518" }, "PROFILE": "isp", "NTOPNG_INSTANCE_NAME": "nbox-demo.wp.lan", "INTERFACE": "tcp:\/\/10.62.5.111:5553", "PASS_VERDICT": true }'), 'nbox-demo.wp.lan', '5','isp')

**Comment by simonemainardi** [comment]
Please, post mysql server version and mysql configuration file used. Thank you

**Comment by simonemainardi** [comment]
any news?

**Comment by lucadistefano** [comment]
mysql  Ver 14.14 Distrib 5.5.49, for debian-linux-gnu (x86_64) using readline 6.3

#

# The MySQL database server configuration file.

#

# You can copy this to one of:

# \- "/etc/mysql/my.cnf" to set global options,

# \- "~/.my.cnf" to set user-specific options.

# 

# One can use all long options that the program supports.

# Run program with --help to get a list of available options and with

# --print-defaults to see which it would actually understand and use.

#

# For explanations see

# http://dev.mysql.com/doc/mysql/en/server-system-variables.html

# This will be passed to all mysql clients

# It has been reported that passwords should be enclosed with ticks/quotes

# escpecially if they contain "#" chars...

# Remember to edit /etc/mysql/debian.cnf when changing the socket location.

[client]
port        = 3306
socket      = /var/run/mysqld/mysqld.sock

# Here is entries for some specific programs

# The following values assume you have at least 32M ram

# This was formally known as [safe_mysqld]. Both versions are currently parsed.

[mysqld_safe]
socket      = /var/run/mysqld/mysqld.sock
nice        = 0

[mysqld]
#

# \* Basic Settings

#
user        = mysql
pid-file    = /var/run/mysqld/mysqld.pid
socket      = /var/run/mysqld/mysqld.sock
port        = 3306
basedir     = /usr
#datadir        = /var/lib/mysql
datadir                = /storage/mysql
tmpdir      = /tmp
lc-messages-dir = /usr/share/mysql
skip-external-locking
#

# Instead of skip-networking the default is now to listen only on

# localhost which is more compatible and is not less secure.

bind-address        = 0.0.0.0
#

# \* Fine Tuning

#
key_buffer      = 16M
max_allowed_packet  = 16M
thread_stack        = 192K
thread_cache_size       = 8

# This replaces the startup script and checks MyISAM tables if needed

# the first time they are touched

myisam-recover         = BACKUP
#max_connections        = 100
#table_cache            = 64
#thread_concurrency     = 10
#

# \* Query Cache Configuration

#
query_cache_limit   = 1M
query_cache_size        = 16M
#

# \* Logging and Replication

#

# Both location gets rotated by the cronjob.

# Be aware that this log type is a performance killer.

# As of 5.1 you can enable the log at runtime!

#general_log_file        = /var/log/mysql/mysql.log
#general_log             = 1
#

# Error log - should be very few entries.

#
log_error = /var/log/mysql/error.log
#

# Here you can see queries with especially long durationA

slow_query_log=1
slow_query_log_file = /var/log/mysql/mysql-slow.log
long_query_time = 2
log_queries_not_using_indexes

#

# The following can be used as easy to replay backup logs or for replication.

# note: if you are setting up a replication slave, see README.Debian about

# other settings you may need to change.

#server-id      = 1
#log_bin            = /var/log/mysql/mysql-bin.log
expire_logs_days    = 10
max_binlog_size         = 100M
#binlog_do_db       = include_database_name
#binlog_ignore_db   = include_database_name
#

# \* InnoDB

#

# InnoDB is enabled by default with a 10MB datafile in /var/lib/mysql/.

# Read the manual for more InnoDB related options. There are many!

#

# \* Security Features

#

# Read the manual, too, if you want chroot!

# chroot = /var/lib/mysql/

#

# For generating SSL certificates I recommend the OpenSSL GUI "tinyca".

#

# ssl-ca=/etc/mysql/cacert.pem

# ssl-cert=/etc/mysql/server-cert.pem

# ssl-key=/etc/mysql/server-key.pem

net_read_timeout=120
net_write_timeout=120
max_allowed_packet=64M

[mysqldump]
quick
quote-names

[mysql]
#no-auto-rehash # faster start of mysql but no tab completition

[isamchk]
key_buffer      = 16M

#

# \* IMPORTANT: Additional settings that can override those from this file!

# The files must end with '.cnf', otherwise they'll be ignored.

#
!includedir /etc/mysql/conf.d/

[mysqld]
datadir=/storage/mysql
log-error=/storage/mysql/mysqld.log

innodb_purge_threads=1
innodb_doublewrite=false
innodb_checksums=false
innodb_file_per_table=1
innodb_file_format=Barracuda
innodb_buffer_pool_size=4G
innodb_log_file_size=1G

innodb-flush-log-at-trx-commit=2
innodb_flush_method=O_DIRECT
innodb_use_sys_malloc=0

innodb_log_buffer_size=20M
innodb_buffer_pool_size=80M

transaction-isolation=READ-COMMITTED

key_buffer      = 16M
max_allowed_packet  = 16M
thread_stack        = 192K
thread_cache_size       = 8
myisam-recover         = BACKUP
query_cache_limit   = 1M
query_cache_size        = 16M

net_read_timeout=120
net_write_timeout=120
max_allowed_packet=64M

slow_query_log=1
slow_query_log_file = /storage/mysql/mysql-slow.log
long_query_time = 2
log_queries_not_using_indexes

expire_logs_days    = 10
max_binlog_size         = 100M

**Comment by simonemainardi** [comment]
Very likely your `innodb_buffer_pool_size` is too small. It looks like you have declared `innodb_buffer_pool_size` twice in your config.

I guess the MySQL server takes the second value that is just 80M.

Make sure to raise it to 1G at least and check it via

```
mysql> SELECT @@innodb_buffer_pool_size/1024/1024/1024
```

---

You also said you don't care about transactions so I am not sure why you keep the bin logs for 10 days. Also the transaction isolation can be READ-UNCOMMITTED in your case. Maybe, even better, why don't you totally disable binary logs?

**Comment by simonemainardi** [comment]
I think it is safe to close this issue as it appears to be related to the MySQL configuration.
