### ISSUE TITLE
Timeseries charts for local hosts are all the same on NetFlow-Interfaces

### ISSUE THREAD

**Issue by thalthoff** [ntop/ntopng#5100]
Hi all,

just want to get sure that I am not overseeing something:

I use ntopng with to interfaces: eth1 listening to a SPAN-Port on my Router and nprobe, listening to a NetFlow collector on the same router. What I mainly want to see is, which host uses what bandwidth on his way out into the world. nprobe and NetFlow are at the moment only for testing purposes (7day license), although I love the concept of "digested" information!

But here I have the following problem:

When I choose to use the the nprobe/NetFlow-Interface and let me show the traffic-graph of any local host, the graph is always the same! No matter if "traffic", "number of active flows" or whatever is chosen. The respective graph is always the same. This does not happen when I choose the packet sniffing port connected to the routers monitor port. Any graph is correct, regarding to the assumed traffic, active flows, whatever.

Do I do anything wrong?

Thanks for any help in advance!

-Thomas

**Comment by simonemainardi** [comment]
Please, show ntopng version used, configuration used, and attach screenshots.

**Comment by MatteoBiscosi** [comment]
Hi @thalthoff do you still have this issue? If yes please send the info simone asked above

**Comment by MatteoBiscosi** [comment]
Closed for inactivity, please reopen the issue if the problem reappear
