### ISSUE TITLE
Throughput column shows all zeros in Hosts display

### ISSUE THREAD

**Issue by rreiner** [ntop/ntopng#5106]
The Throughput column shows all zeros on the page http://myhost:3000/lua/hosts_stats.lua, regardless of what filters are set.

The Total Bytes column on that page is normal (shows correct data, and increments dynamically). 

On the MAC Addresses page (http://myhost:3000/lua/macs_stats.lua) the Throughput column is normal, i.e. correct.

And on the Flows page (http://myhost:3000/lua/flows_stats.lua) the "Actual Thpt" column is also normal.

Seems to be happening since the latest update.

# ntopng --version
Version:        4.3.210314 [Enterprise/Professional/Embedded build]
GIT rev:        dev:8915a98a8a2ba436cd8d71b3fd456fb7ef5a8977:20210314
Pro rev:        r3630
Built on:       Raspbian GNU/Linux 10 (buster)
System Id:      130FA343499602D2
Platform:       armv7l
Edition:        Enterprise Embedded
License Type:   Time-Limited [Empty license file]
Validity:       Until Sun Mar 14 17:55:04 2021

**Comment by simonemainardi** [comment]
@MatteoBiscosi please explain why the commit fixes the issue. Why it was working, what has caused the issue, and why the line you added fixes it. Add comments in the code.

**Comment by MatteoBiscosi** [comment]
The reason is simple, the super method (the one inside GenericTrafficElement) is the one who's going to update the throughput and it wasn't called before, so the host throughput in reality was never updated, with the fix instead the super method is called and the throughput is now periodically updated

**Comment by simonemainardi** [comment]
> Seems to be happening since the latest update.

You say it wasn't called before, but actually the host throughput was calculated in earlier versions of ntopng. So please explain what has changed and why you say it wan't called before.

**Comment by MatteoBiscosi** [comment]
The periodic update method of HostStats override the GenericTrafficElement periodic update but the super periodic update was not called by HostStats so all the periodic updates done by GenericTrafficElement weren't done and this mean that the throughput update wasn't done

**Comment by simonemainardi** [comment]
issue was caused here with the override of this virtual method which was not calling the overridden method in the parent

```
26af27d6a9 (Matteo Biscosi  2021-03-13 00:30:40 +0100 138)   void updateStats(const struct timeval *tv);
```
