### ISSUE TITLE
Failing loadModule silenced

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5107]
Please see https://github.com/ntop/ntopng/commit/885cc595ed7c0d7bca7f576907e6aec9b39b62b8

**Comment by MatteoBiscosi** [comment]
Silencing removed, the error was caused by an incorrect rest test

**Comment by simonemainardi** [comment]
please, cleanup `tprint` leftovers and then close: https://github.com/ntop/ntopng/commit/ab559470173a4a59ec0c40d1b3c276fd5a78b3f1#diff-951facdf8262ca5e08b77698f817e252aaa6a8316a33239f7b15f981f877f6aaR1203

**Comment by MatteoBiscosi** [comment]
already cleaned up, see commit: e71dfaaa0b3e9cbe0d517c2f67ad4cb7c2cb9bc0
