### ISSUE TITLE
Feature request - traffic report for host pools

### ISSUE THREAD

**Issue by ottorei** [ntop/ntopng#5108]
At the moment there does not seem to be a straightforward way to report top remote ASNs and have a combined peer-reports for host pools. Peers-tab only exist on host-page. I would like a way to combine these peers from multiple hosts and show the aggregated stats on host pools. 

Another possibility could be to have a similar dashboard as Traffic Report but with the ability to filter hosts based on host pools for the report.

**Comment by MatteoBiscosi** [comment]
Half implemented, this just need to add the host pool filters

**Comment by MatteoBiscosi** [comment]
Implemented as requested
