### ISSUE TITLE
Export all the IPs that contacted an host in a specific time interval

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#5109]
I need to export all the IP Address that contact a host in a specific time interval.
This function it's required also if i have nprobe mapped to ntopng in order to track all the ip calling a nprobe host based

**Comment by MatteoBiscosi** [comment]
Hi @zimbawe998 right now this feature is available using the 'Historical Flow Explorer'. By selecting the period of time you need and adding the host filter you need, it is possible then to export all this data by CSV format
