### ISSUE TITLE
ntopng 4.3.210315 stops processing netflow data which is coming from nprobe 9.5.210315 through ZMQ

### ISSUE THREAD

**Issue by antonakv** [ntop/ntopng#5110]
I have problem with ntopng 4.3.210315. It stops processing netflow data which is coming from nprobe 9.5.210315 through ZMQ. And nprobe receives netflow stream from Mikrotik. OS: Raspbian GNU/Linux 10 (buster). 

tcpdump on zero mq port shows that data is comming to ntopng but ZMQ Statistics stays without any change and flow is not accounted. 

When I restart ntopng it starts working again for a while and then stops after 20-40 minutes. There aren't any errors in logs of ntopng and nprobe. Licenses are correct and recognised.

As I see from open issues it can be related to BPF L7 processing issues when ntopng crashes.

**Comment by simonemainardi** [comment]
- is your nProbe licensed?
- Look under the interface stats page. Do you see ZMQ messages counters increasing?
- Why to you think it is related to BPF L7?

**Comment by antonakv** [comment]
Hi @simonemainardi 
- Yes, nProbe is licensed. And license is recognised correctly as I see in a logs.
- ZMQ messages counters aren't increasing. When I do restart it's increasing and then stops again.
- I think it's related to BPF L7 as I have checked recent issues and in one of them was said that ntopng stops crashing when L7 analysis is disabled. It's my guess.

**Comment by simonemainardi** [comment]
please report the output of `ntopng --version` and `nprobe --version`

**Comment by antonakv** [comment]
Here you are @simonemainardi 
$ ntopng --version
Version:	4.3.210315 [Enterprise/Professional/Embedded build]
GIT rev:	dev:4cb53e4508a354865b18213b24b5c96cf267ccbd:20210315
Pro rev:	r3633
Built on:	Raspbian GNU/Linux 10 (buster)
System Id:	4419597B499602D2
Platform:	armv7l
Edition:	Enterprise Embedded
License Type:	Permanent
Maintenance:	Until Wed Mar 16 18:38:46 2022 [364 days left]
License:	Wh47atSntcK5Uu91NHpieuuIvKYJLCwjvQ7b+i9n3WFwyuLwOBQZX1qoxo3tWk1CVBIOL
        	lrpw3WZBOWP47tSQYf/rxQ/Gz3qAkptFcbuAZNoOzJnNN7ZjftwlUr5+Bbklzkn9zCPB6
        	aH1JT9znuQcmRpZxmyDp9sAPQpb0iDZRUEo0jrU8aji/rdft6xY9XoN63LK7lALkA4bAL
        	pVa0ubSvkFwFvlmCMZN/lfn+Y2gKP7bD2j4t9+TkTZKRKtfdsj7X67ZdOF1aFodcF78GA
        	/TUJ1IrCckGN9EJ4ctIyV2a2NqNl+LyR3JyjwbGCyKa3T2CfYG7zbDV8vq8L8Ughgw==
License Hash:	E54DFF01089DFF10C81643A6974F22091647452326B94617DB

$ nprobe --version

Welcome to nProbe v.9.5.210315 for armv7l-unknown-linux-gnueabihf
Built with nDPI 3.5.0-3039-b22cb70a

Copyright 2002-21 ntop.org

Version:       9.5.210315
Build OS:      Raspbian GNU/Linux 10 (buster)
SystemID:      4419597B5E6BA0A5
GIT rev:       dev:69f8e0809f9955b17ca55dd7afaf9269c4f12412:20210315
Edition:       nProbe Embedded
License:       gs42HV8kYAbAd60bry3EVLdBCxn0PnordEGRX0zN4wF0UiRyMSt3X8RkJA3sdyiNxUizK
               80nd0CNGkCUAKU0ErBo5p2jktciR41iZedLEOVeldsHNiTd8L0Ux/bQaHCQvrx0sMqacr
               iFYK/eCgIulhHqRwa8wJ/Ymvbb36FeskoD81iW5U4oscx7JGOiOz3l55Utny1vlgskjWo
               flm1ct1FlVbfBbgVoJZFDK2l5fTKl18Xth5M+hUNF42mIBcuVplSEXl3/cT+2A6x0IKyu
               CXaEUK9owxVuRSwQ3jh8anRo04PV9+FsTub24oBXMocx0Iz9rsRf40wYKez7lcOrlw==
License Hash:  1BB4FC65A66DBBB210024AF9A5A780AA164745245730AC3CEE [valid license]
License Type:  Permanent License 
Maintenance:   Until Wed Mar 16 18:40:57 2022 [364 days left]

nProbe is subject to the terms and conditions defined in
the LICENSE and EULA files that are part of this package.

nProbe also contains third party code:
Radix tree code - (C) The Regents of the University of Michigan
                      ("The Regents") and Merit Network, Inc.
sFlow collector - (C) InMon Inc.

**Comment by lucaderi** [comment]
After some tests we realised the bug is in the ntopng side as nProbe is continuously sending out flows

**Comment by antonakv** [comment]
@lucaderi Thank you very much!

**Comment by antonakv** [comment]
There is strace output when it has stuck
```
rpi4:~ $ sudo strace -p 11390
strace: Process 11390 attached
_newselect(27, [26], NULL, NULL, {tv_sec=2, tv_usec=54486}) = 0 (Timeout)
gettimeofday({tv_sec=1616071338, tv_usec=661182}, NULL) = 0
gettimeofday({tv_sec=1616071338, tv_usec=661319}, NULL) = 0
gettimeofday({tv_sec=1616071338, tv_usec=661426}, NULL) = 0
gettimeofday({tv_sec=1616071338, tv_usec=661551}, NULL) = 0
gettimeofday({tv_sec=1616071338, tv_usec=661656}, NULL) = 0
_newselect(27, [26], NULL, NULL, {tv_sec=0, tv_usec=4999663}) = 0 (Timeout)
gettimeofday({tv_sec=1616071343, tv_usec=666732}, NULL) = 0
gettimeofday({tv_sec=1616071343, tv_usec=666882}, NULL) = 0
gettimeofday({tv_sec=1616071343, tv_usec=666992}, NULL) = 0
gettimeofday({tv_sec=1616071343, tv_usec=667095}, NULL) = 0
gettimeofday({tv_sec=1616071343, tv_usec=667211}, NULL) = 0
_newselect(27, [26], NULL, NULL, {tv_sec=0, tv_usec=4999671}) = 0 (Timeout)
gettimeofday({tv_sec=1616071348, tv_usec=670670}, NULL) = 0
gettimeofday({tv_sec=1616071348, tv_usec=670800}, NULL) = 0
gettimeofday({tv_sec=1616071348, tv_usec=670900}, NULL) = 0
gettimeofday({tv_sec=1616071348, tv_usec=670996}, NULL) = 0
gettimeofday({tv_sec=1616071348, tv_usec=671093}, NULL) = 0
_newselect(27, [26], NULL, NULL, {tv_sec=0, tv_usec=4999707}^Cstrace: Process 11390 detached
 <detached ...>
```

**Comment by lucaderi** [comment]
The issue is solved: the device was put on pause

**Comment by antonakv** [comment]
I'm not sure if "The issue is solved: the device was put on pause" is straight solution as ntopng puts on pause itself when it was not on pause. Maybe because of slow IO, or peak high cpu load or licensing check issue. Something like that. It was not op pause on purpose. Moreover, in a while after restart ntopng will put netflow comming from nprobe on pause again.
