### ISSUE TITLE
Alert Christmas Tree again

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5111]
<img width="1423" alt="Screenshot_2021-03-17_at_09_00_46" src="https://user-images.githubusercontent.com/4493366/111434340-b9fbc700-86ff-11eb-9288-36e67d889afb.png">

**Comment by gabryon99** [comment]
I scaled up the maximum width of the 'Action' column:
https://github.com/ntop/ntopng/commit/a948cbea0f261ba149333ad0af7f5f659b7dbcb1

See the file: `scripts/lua/modules/alert_utils.lua`

**Comment by lucaderi** [comment]
Seems to work now, will reopen if necessary
