### ISSUE TITLE
Influx DB error ntopng and flow button crash

### ISSUE THREAD

**Issue by ListenNjoy** [ntop/ntopng#5114]
Hello i get this error when recieving zmg from cento. 

[timeseries.lua:14] [influxdb.lua:456] ERROR: Unexpected query error: not executed, in query #18:  CREATE CONTINUOUS QUERY "iface:score__1d" ON ntopng BEGIN SELECT mean(cli_score) as cli_score,mean(srv_score) as srv_score INTO "1d"."iface:score" FROM ( SELECT mean(cli_score) as cli_score,mean(srv_score) as srv_score FROM "autogen"."iface:score" GROUP BY time(60s),ifid FILL(0) ) GROUP BY time(1d),ifid END

And the ntopng crash when pressing flow button on the left side is back, no reset ntopng solved this

Code: 00 0f b7 ea 48 8b 04 eb 48 85 c0 75 18 bf 01 00 00 00 be 30 00 00 00 e8 f0 95 f6 ff 48 85 c0 48 89 04 eb 74 67 48 8b 4c 24 40 <f3> 0f 6f 00 66 49 0f 6e cc 66 49 0f 6e d5 66 0f 6c d1 66 0f d4 d0
--
Today 08:50:55 | KERN | INFO | Ntop-NtopNG | kernel: |   | Syslog | ntopng[28745]: segfault at 7f9f148866f0 ip 00000000004a2a4e sp 00007f9e23536560 error 4 in ntopng[400000+394000]

Ntopng -V
 4.3.210318 [Enterprise/Professional build]
GIT rev:        dev:c6ad5566400153c685a3d3e10e28eaecacb3e872:20210318

cento -V
cento v.1.13.210318

**Comment by gianogli** [comment]
I've a very similar issue: I've just upgraded ntopng from 4.3.210212 to 4.3.210319 (Enterprise M) and now my logs are filled by these error messages:
```
Mar 19 11:01:35 myserver ntopng[27439]: [timeseries.lua:14] [influxdb.lua:1941] ERROR: InfluxDB setup failed
Mar 19 11:01:36 myserver ntopng[27439]: [timeseries.lua:14] [influxdb.lua:456] ERROR: Unexpected query error: not executed, in query #19:  CREATE CONTINUOUS QUERY "iface:score__1d" ON ntopng BEGIN SELECT mean(cli_score) as cli_score,mean(srv_score) as srv_score INTO "1d"."iface:score" FROM ( SELECT mean(cli_score) as cli_score,mean(srv_score) as srv_score FROM "autogen"."iface:score" GROUP BY time(60s),ifid FILL(0) ) GROUP BY time(1d),ifid END
Mar 19 11:01:36 myserver ntopng[27439]: [timeseries.lua:14] [influxdb.lua:1941] ERROR: InfluxDB setup failed
Mar 19 11:01:37 myserver ntopng[27439]: [timeseries.lua:14] [influxdb.lua:456] ERROR: Unexpected query error: not executed, in query #19:  CREATE CONTINUOUS QUERY "iface:score__1d" ON ntopng BEGIN SELECT mean(cli_score) as cli_score,mean(srv_score) as srv_score INTO "1d"."iface:score" FROM ( SELECT mean(cli_score) as cli_score,mean(srv_score) as srv_score FROM "autogen"."iface:score" GROUP BY time(60s),ifid FILL(0) ) GROUP BY time(1d),ifid END
Mar 19 11:01:37 myserver ntopng[27439]: [timeseries.lua:14] [influxdb.lua:1941] ERROR: InfluxDB setup failed
```
I think there is some problem into influxdb related to the new "score" feature...

**Comment by simonemainardi** [comment]
@MatteoBiscosi please check lua method `getPossiblyChangedSchemas`.

If there has been changes in the score timeseries, this can potentially be the source for reported errors.

It should be necessary to update `getPossiblyChangedSchemas`

**Comment by MatteoBiscosi** [comment]
Hi @ListenNjoy i should have fixed the issue, builds are in progress wait for a few hours and update ntopng. Let me know if the problem persists or not

**Comment by gianogli** [comment]
Hi @MatteoBiscosi, I've just update the ntopng package and the error messages are disappeared.
The "Score" column on "Active Flows" windows is always empty for now... but I don't know if I've to wait some hours to see if the new feature is working as expected.
Thanks for your support... ;-)
