### ISSUE TITLE
[nedge] Wrongly classified flow

### ISSUE THREAD

**Issue by Paolo5466** [ntop/ntopng#5115]
website "www.confindustriabrescia.it" gets identified as "tor" traffic and gets blocked.
Using the ip address instead works.
I tried to add both the IP and the FQDN in the "User custom category 1" with "Allow" policy but it doesn't solve the issue.
The website is still unreachable.
Is it any way to "trust" a public IP or FQDN to avoid it being blocked?

Thanks

![image](https://user-images.githubusercontent.com/53659380/111593848-b1bc8e00-87ca-11eb-975d-e006629daf53.png)

**Comment by lucaderi** [comment]
Fixed by https://github.com/ntop/nDPI/commit/627299e4ddd7d39fcc7ce8cd703be0ed8f92da4a in dev. Do you use stable or dev?

**Comment by Paolo5466** [comment]
Sorry for not detailing the request.
Dev.

Il sab 20 mar 2021, 17:57 Luca Deri ***@***.***> ha scritto:

**Comment by lucaderi** [comment]
So overnight the new build with the fix will be available. Thanks for reporting the issue

**Comment by Paolo5466** [comment]
Thank you.

Il sab 20 mar 2021, 19:32 Luca Deri ***@***.***> ha scritto:
