### ISSUE TITLE
Score counter wrap

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5119]
![Screen Shot 2021-03-22 at 23 15 41](https://user-images.githubusercontent.com/4493366/112065260-a53a8b80-8b64-11eb-9581-a11bca16d6be.png)

**Comment by simonemainardi** [comment]
This is due to Flow::updateAlertsStats not being called when preference don't emit flow alerts is set. Fix in progress.

**Comment by simonemainardi** [comment]
Fixed in https://github.com/ntop/ntopng/commit/8c31b700735e7654cf6c81bc1f8cd6ac18993885
