### ISSUE TITLE
Local to remote and remote to local info are always 0

### ISSUE THREAD

**Issue by lucadistefano** [ntop/ntopng#512]
Local to remote and remote to local are always 0
I suspect it not works with zmq interfaces.

![image](https://cloud.githubusercontent.com/assets/1080723/14666111/d54ddf0a-06d7-11e6-9e0f-a9182dcd4628.png)

configuration:
-n=1
-w=3000
-W=0
-m="10.62.4.0/22,10.62.1.0/25"
-X=320000
-x=132768
-F=mysql;127.0.0.1;ntopng;flows;ntopng;ntopng
-d=/storage/ntopng
-C
-l=1
-G=/var/tmp/ntopng.pid
-i=tcp://10.62.5.111:5552
-i=tcp://10.62.5.111:5553

**Comment by lucadistefano** [comment]
today I restarted the system from scratch and for a while the info on loc-rem-loc was shown for each  zmq interface.
Then I readded the view -i=view:tcp://10.62.5.111:5552,tcp://10.62.5.111:5553 and the info is disappeared again, even if I select the single interface.

**Comment by simonemainardi** [comment]
Thank, this is helpful. 

If you remove the view once again, will the single ZMQ interfaces show the info?

**Comment by lucadistefano** [comment]
when I remove the view, still not working

**Comment by lucaderi** [comment]
note that both nprobe and ntopng must be in sync to recent versions,

**Comment by lucadistefano** [comment]
ntopng and nprobe are both aligned on the same build day

I upgraded to the build of today  but the problem is still present

**Comment by simonemainardi** [comment]
fixed in https://github.com/ntop/ntopng/commit/8a69147ddacba5e715e026d1af6401b990345727
