### ISSUE TITLE
Engaged alerts lost past shutdown

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5123]
Engaged alerts are not written to the alert database if ntopng is stopped or restarted. Two options
- serialise the alerts so that when ntopng starts up again they are still engaged
- at shutdown put the engaged alerts in the alert database before shutdown completes (perhaps this is the best solution)

**Comment by simonemainardi** [comment]
> at shutdown put the engaged alerts in the alert database before shutdown completes (perhaps this is the best solution)

This is the way chosen.
