### ISSUE TITLE
Invalid engaged alerts transition

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5124]
When engaged alerts return to normal state (e.g the problem disappears) they should move to the "Past Alerts" section of alerts. Unfortunately this works from time to time and formar engaged alerts disappear instead of being moved to the "Past Alerts" section. This behaviour is wrong for most alerts such as "Unexpected Host Behaviour" or "Ghost Networks". Example this engaged alerts is open for some time
![Screen Shot 2021-03-23 at 08 30 54](https://user-images.githubusercontent.com/4493366/112109986-8ebb2100-8bb2-11eb-8293-8891e957ad48.png)
then it disappears but it is not moved to the past alerts page
![Screen Shot 2021-03-23 at 08 34 41](https://user-images.githubusercontent.com/4493366/112110041-a72b3b80-8bb2-11eb-8076-723683d9cf59.png)

Also note that in the above picture the alert aggregation is suboptimal (yet another issue to address)

**Comment by MatteoBiscosi** [comment]
This behavior should be fixed, if the problem reappear please reopen the ticket
