### ISSUE TITLE
WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/daily.lua]: attempt to call a nil value

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#5125]
I find this warning into my logs:
```
23/Mar/2021 00:01:36 [LuaEngine.cpp:572] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/daily.lua][/usr/share/ntopng/scripts/callbacks/system/daily.lua:25: attempt to call a nil value (field 'midnightStatsResetEnabled')]
```
I have one warning a day after midnight.
Could you resolve?

Thanks... :-)

**Comment by MatteoBiscosi** [comment]
Hi @gianogli the issue should be fixed, let me know if everything works fine from now on

**Comment by gianogli** [comment]
Hi @MatteoBiscosi, I've just updated my installation to v.4.3.210324 but I've to wait midnight to verify if the issue is solved (as I beleave ;-) ).

For now... thanks for your support! :-)
