### ISSUE TITLE
Alert aggregation is flawed

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5130]
![Screen_Shot_2021-03-24_at_16_33_25](https://user-images.githubusercontent.com/4493366/112338110-cf07c580-8cbe-11eb-9da2-fe9c06fd8024.png)

**Comment by simonemainardi** [comment]
Alert aggregation no longer exists in the latest implementation. This decision has been made to favor speed and simplicity as the former implementation was cumbersome. So this issue cannot be fixes but a possible new implementation will be discussed in the future.
