### ISSUE TITLE
Raspberry Pi OS (not) 64bit nor (Debian) anymore...

### ISSUE THREAD

**Issue by stockybuild** [ntop/ntopng#5139]
Raspberry Pi OS isn't available in 64bit anymore (or just now?) which means a build from source (and broken packages) is pretty much on the cards for most debian fans if the latest version of ntop software is sought after. ... (maybe a good learning experience...)

**Comment by lucaderi** [comment]
To date PiOS 64 bit has not been officially released AFIK (https://www.raspberrypi.org/software/operating-systems/), so we decided to stay to 32 bit. Are we missing something?

**Comment by lucaderi** [comment]
Closing we'll reopen if necessary
