### ISSUE TITLE
Disabled alerts are not saved in the exclusion list

### ISSUE THREAD

**Issue by tomkolp** [ntop/ntopng#5140]
After disabling an alert for a specific address, it does not appear in the exclusion list. It was working normally a few days ago. I currently have version v. 4.3.210330
![image](https://user-images.githubusercontent.com/39633242/112946737-2c27cf00-9136-11eb-99f6-ea08ddfa47d7.png)
![image](https://user-images.githubusercontent.com/39633242/112946762-31851980-9136-11eb-86cf-e643a030b50c.png)

**Comment by simonemainardi** [comment]
we are in the process of implementing a page with all disabled alerts.

**Comment by cardigliano** [comment]
Disabled hosts are now in the user script exclusion list
