### ISSUE TITLE
Implement REST endpoints for the new Traffic Dashboard

### ISSUE THREAD

**Issue by gabryon99** [ntop/ntopng#5141]
As discussed today, we have to implement the new traffic dashboard that will replace the current one. The new dashboard will have (at the moment) five widgets listed below:
1. **Top L7 Protocols**, displayed as a Bar Chart (or Word Cloud chart?);
2. **Interface Score**, displayed as a big number with a label representing the increase/decrease percentage compared to a selected time period;
3. The **alerts** number, displayed as a Radar Chart;
4. The **Top Talkers (Remote + Local)**, displayed as a Bar Chart;
5. At last, the **Real-time Traffic** (the same used in the current dashboard);

Here is a summary image for the new dashboard:
![image](https://user-images.githubusercontent.com/14114916/113204089-1f59c700-926d-11eb-83d1-6316700ec96d.png)

Here is an image for the World Cloud:
![image](https://user-images.githubusercontent.com/14114916/113204222-56c87380-926d-11eb-8200-4fc7ed06c5ba.png)

And here is an image for the Score widget:
![image](https://user-images.githubusercontent.com/14114916/113204152-3a2c3b80-926d-11eb-9de6-267a736e90af.png)

**Comment by MatteoBiscosi** [comment]
At the moment no new dashboard is going to be released and the ticket is going to be put on standby. In the near future the discussion about the new dashboard is going to be reviewed here.

**Comment by MatteoBiscosi** [comment]
The discussion regarding the new dashboard is going to be done in ticket #1670
