### ISSUE TITLE
(Dashboard-#0) Implement REST Endpoint for Interface's Score 

### ISSUE THREAD

**Issue by gabryon99** [ntop/ntopng#5142]
As discussed in the ticket #5141, we have to implement a REST endpoint to get the interface score that will be displayed in the new dashboard. The GET request will contain only 1 parameter: `ifid` (the interface ID).
The response will contain the score of the interface shown as below:
```
{
    "rc": "....",
    "rsp": {
        "score": 100
    }
}
```

The endpoint will be located under `scripts/lua/rest/v1/charts/interface/...`

**Comment by MatteoBiscosi** [comment]
There are two types of score, the score as a client and the score as a server, so the answer is going to have 2 values: 
`
'score_as_cli': 5,
'score_as_srv': 10
`
In this way we are going to resolve the issue about the "excessive unused space" too

**Comment by MatteoBiscosi** [comment]
Currently the dashboard is not going to be reworked in this way. The dashboard rework is going to be discussed into #5141
