### ISSUE TITLE
(Dashboard-#1) Implement REST Endpoint for Top L7 Protocols

### ISSUE THREAD

**Issue by gabryon99** [ntop/ntopng#5143]
As discussed in the ticket #5141, we have to implement a REST endpoint to get the top list of L7 protocols that will be displayed in the new dashboard. The GET request will contain only 1 parameter: `ifid` (the interface ID).

We should(?) implement 2 version for this endpoint:
* The first one will contain a response formatted for a **vertical bar chart** (the same used by chart.js: https://www.chartjs.org/docs/latest/charts/bar.html)
* Instead, the second one will contain a response formatted for **word cloud** (see the link: https://www.npmjs.com/package/chartjs-chart-wordcloud, the only field that must be returned is `data` with the `labels` and the `dataset`).

The endpoint will be located under `scripts/lua/rest/v1/charts/interface/...`

**Comment by MatteoBiscosi** [comment]
Currently the dashboard is not going to be reworked in this way. The dashboard rework is going to be discussed into #5141
