### ISSUE TITLE
(Dashboard-#2) Implement REST Endpoint for Top Talkers (Remote + Local)

### ISSUE THREAD

**Issue by gabryon99** [ntop/ntopng#5144]
As discussed in the previous tickets, we have to implement a new REST endpoint for the Top Talkers (Remote and Local).
The GET request will contain 2 parameters:
* `ifid`
* `type=remote|local`

The data will be displayed with a horizontal bar chart (see chart.js documentation: https://www.chartjs.org/docs/latest/charts/bar.html)

**Comment by MatteoBiscosi** [comment]
Currently the dashboard is not going to be reworked in this way. The dashboard rework is going to be discussed into #5141
