### ISSUE TITLE
(Dashboard-#3) Implement REST Endpoint for Alert Chart

### ISSUE THREAD

**Issue by gabryon99** [ntop/ntopng#5145]
Finally, we have to implement a REST endpoint to display the alerts count in the new Dashboard. The request will contain only the interface ID parameter.
The data returned must be formatted for a radar chart (see chart.js documentation: https://www.chartjs.org/docs/latest/charts/radar.html)

**Comment by MatteoBiscosi** [comment]
Personally I think that inside the alert chart would be nice to have a single dataset representing the quantity of alerts of an interface. As edges I think it's a good idea to put the alerts with the most "number" (obviously from a specific severity on, for example the most numerous warning and error alerts) or the most severity (for example a critical alert should be there), in this way it's possible to understand which are the "popular" alerts of the specific interface and if there are some really serious alert that the user should check.
Any suggestion on the topic is really appreciated

**Comment by MatteoBiscosi** [comment]
Currently the dashboard is not going to be reworked in this way. The dashboard rework is going to be discussed into #5141
