### ISSUE TITLE
Memory Issue?

### ISSUE THREAD

**Issue by netsolv** [ntop/ntopng#5146]
Is it normal for 20 enabled user scripts to utilize 33 command instances in htop /usr/bin/ntopng /run/ntopng.conf each consuming 41.7 in memory allocation?

![image](https://user-images.githubusercontent.com/76790187/113415864-1ca2c300-938e-11eb-82cf-7511a2b91b26.png)

**Comment by netsolv** [comment]
useless support

**Comment by mihakralj** [comment]
This is not a support channel for ntopng... 😊

**Comment by lucaderi** [comment]
@netsolv Why did you close this ticket across Easter break?

Please report the output " top -H -p `pidof ntopng`" 
Thanks

**Comment by netsolv** [comment]
top - 17:27:25 up 8 days, 53 min,  3 users,  load average: 1.24, 1.18, 1.19
Threads:  34 total,   0 running,  34 sleeping,   0 stopped,   0 zombie
%Cpu(s): 21.6 us,  4.2 sy,  0.0 ni, 72.9 id,  0.0 wa,  0.0 hi,  1.4 si,  0.0 st
MiB Mem :   3827.6 total,    254.0 free,   1571.7 used,   2002.0 buff/cache
MiB Swap:   1024.0 total,   1024.0 free,      0.0 used.   1895.3 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
20139 ntopng    20   0 1681648   1.2g  77516 S  71.1  33.1 617:37.88 ntopng
20423 ntopng    20   0 1681648   1.2g  77516 S   0.7  33.1  12:26.11 notifications.l
20427 ntopng    20   0 1681648   1.2g  77516 S   0.7  33.1  51:27.91 inline ifid 3
20085 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1   0:09.31 ntopng
20136 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1   0:37.50 ntopng
20137 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1 603:20.49 ntopng
20138 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1 610:45.66 ntopng
20140 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1 626:44.55 ntopng
20141 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1 623:49.75 ntopng
20142 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1   0:16.98 hooks ifid 3
20143 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1   0:07.97 hooks ifid 3
20144 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1   3:23.52 resolveLoop
20405 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1   3:22.34 stats_update.lu
20406 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1   4:31.76 stats_update.lu
20407 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1  15:39.90 5min.lua
20408 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1  13:59.44 5min.lua
20409 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1   0:00.00 TrPoolWorker
20410 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1   0:00.00 TrPoolWorker
20411 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1  69:09.63 periodic_user_s
20412 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1   4:21.62 periodic_user_s
20413 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1   8:00.10 discover.lua
20414 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1   1:16.08 housekeeping.lu
20415 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1 102:23.28 minute.lua
20416 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1  15:48.65 second.lua
20417 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1   0:10.78 stats_update.lu
20418 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1   0:08.67 periodic_user_s
20419 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1   0:10.83 housekeeping.lu
20420 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1   0:06.41 minute.lua
20421 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1   0:06.05 daily.lua
20422 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1   8:27.04 timeseries.lua
20424 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1   0:06.30 5min.lua
20425 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1   0:06.08 hourly.lua
20426 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1   0:08.72 discover.lua
20428 ntopng    20   0 1681648   1.2g  77516 S   0.0  33.1   1:24.01 ntopng

**Comment by netsolv** [comment]
after latest update, still showing
 ntopng[3237]: [FlowCallbacksLoader.cpp:204] WARNING: Unable to find flow callback  iec60870_5_104
on the status of ntopng.service

**Comment by netsolv** [comment]
After systemctl restart ntopng.service

top - 17:31:24 up 8 days, 57 min,  3 users,  load average: 0.98, 1.16, 1.18
Threads:  34 total,   0 running,  34 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.8 us,  2.6 sy,  0.0 ni, 96.2 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
MiB Mem :   3827.6 total,   1258.5 free,    561.1 used,   2008.0 buff/cache
MiB Swap:   1024.0 total,   1024.0 free,      0.0 used.   2905.9 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 3959 ntopng    20   0  602964 224548  34556 S   1.3   5.7   0:01.33 inline ifid 3
 3960 ntopng    20   0  602964 224548  34556 S   0.7   5.7   0:00.03 ntopng
 3674 ntopng    20   0  602964 224548  34556 S   0.3   5.7   0:00.40 resolveLoop
 3237 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:05.06 ntopng
 3666 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:00.02 ntopng
 3667 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:04.26 ntopng
 3668 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:04.24 ntopng
 3669 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:04.25 ntopng
 3670 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:04.63 ntopng
 3671 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:04.42 ntopng
 3672 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:00.02 hooks ifid 3
 3673 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:00.02 hooks ifid 3
 3937 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:00.44 stats_update.lu
 3938 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:00.02 stats_update.lu
 3939 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:00.48 5min.lua
 3940 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:01.24 5min.lua
 3941 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:00.00 TrPoolWorker
 3942 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:00.00 TrPoolWorker
 3943 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:01.10 periodic_user_s
 3944 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:02.22 periodic_user_s
 3945 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:00.47 discover.lua
 3946 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:00.01 housekeeping.lu
 3947 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:02.60 minute.lua
 3948 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:00.48 second.lua
 3949 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:00.00 stats_update.lu
 3950 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:00.00 periodic_user_s
 3951 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:00.00 housekeeping.lu
 3952 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:00.00 minute.lua
 3953 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:00.00 daily.lua
 3954 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:00.31 timeseries.lua
 3955 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:00.47 notifications.l
 3956 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:00.00 5min.lua
 3957 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:00.00 hourly.lua
 3958 ntopng    20   0  602964 224548  34556 S   0.0   5.7   0:00.00 discover.lua

**Comment by cardigliano** [comment]
> ntopng[3237]: [FlowCallbacksLoader.cpp:204] WARNING: Unable to find flow callback iec60870_5_104

This has been fixed, an update should address it.

> Is it normal for 20 enabled user scripts to utilize 33 command instances in htop /usr/bin/ntopng /run/ntopng.conf each consuming 41.7 in memory allocation?

Please note those are threads, not commands or processes. 41.7 is related to the whole (single) process.

**Comment by netsolv** [comment]
sudo /usr/bin/ntopng --version
Version:        4.3.210404 [Enterprise/Professional/Embedded build]
GIT rev:        dev:baf0bb0dafc295bede03b0c86e728caa0c03c8ad:20210404
Pro rev:        r3688
Built on:       Raspbian GNU/Linux 10 (buster)

Just ran sudo systemctl restart ntopng.service
Still showing after restart and running sudo systemct status ntopng.service
[FlowCallbacksLoader.cpp:204] WARNING: Unable to find flow callback  iec60870_5_104

**Comment by simonemainardi** [comment]
> [FlowCallbacksLoader.cpp:204] WARNING: Unable to find flow callback iec60870_5_104

Reported issue should be fixed. New raspberry builds are in progress and will be ready in a coupe of hours.
