### ISSUE TITLE
[host_details.lua:2148] [ts_schema.lua:139] ERROR missing tag 'protocol' in schema host:ndpi

### ISSUE THREAD

**Issue by handude** [ntop/ntopng#5147]
Getting the error above in the log file while using ntopng /Embedded v.4.3.210328 (Raspbian GNU/Linux 10 (buster)) 

When going to host detail - apps - and then click on any app , the web interface shows "No data found" (url /lua/host_details.lua?host=x.x.x.x
The error can be reproduced

This always worked, so I assume an update broke this. I completely reinstalled ntopng, but the error remains.

**Comment by MatteoBiscosi** [comment]
Hi @handude I'm sorry but I'm unable to reproduce the bug. However I have a guess about the issue, the url you shared is the entire url?

**Comment by handude** [comment]
Thank you,

I did not include the hostname part, the full url is

https://my.domain.org:3001/lua/host_details.lua?host=x.x.x.x&page=historical&protocol=Amazon&ts_schema=host:ndpi

Where x.x.x.x is the ip address of the host I am looking at. (In this case
looking at Amazon traffic)

Thanks again

**Comment by MatteoBiscosi** [comment]
Thank you,
Please download [this file](https://www.dropbox.com/s/rtwpd926jf36r9v/ts.lua?dl=0) and replace the file inside '/usr/share/ntopng/scripts/lua/rest/v1/get/timeseries/ts.lua' with the one downloaded. It's a debug file. It's going to print some debug info into the log, so please check the log file and report me back the info. Note that some of these info are Ip Addresses so be sure to remove them before sending the log.

**Comment by handude** [comment]
Thank you, Matteo.

There is not a whole lot of more info in the log : (I did restart ntopng, not sure if that was needed), I did not see any ip addresses in the log.


Apr  2 18:24:52 ntopng ntopng[7943]: 02/Apr/2021 18:24:52 [startup.lua:37] Processing startup.lua: please hold on...
Apr  2 18:24:54 ntopng ntopng[7943]: 02/Apr/2021 18:24:54 [startup.lua:176] [lists_utils.lua:782] Refreshing category lists...
Apr  2 18:24:54 ntopng ntopng[7943]: 02/Apr/2021 18:24:54 [startup.lua:176] [lists_utils.lua:720] Category Lists (2045 hosts, 2837 IPs, 98 JA3) loaded in 0 sec
Apr  2 18:24:54 ntopng ntopng[7943]: 02/Apr/2021 18:24:54 [startup.lua:250] Completed startup.lua
Apr  2 18:24:54 ntopng ntopng[7943]: 02/Apr/2021 18:24:54 [PeriodicActivities.cpp:168] Each periodic activity script will use 2 threads
Apr  2 18:24:54 ntopng ntopng[7943]: 02/Apr/2021 18:24:54 [AlertExclusions.cpp:108] Reloading alert exclusions
Apr  2 18:24:54 ntopng ntopng[7943]: 02/Apr/2021 18:24:54 [NetworkInterface.cpp:2734] Started packet polling on interface eth0 [id: 1]...
Apr  2 18:25:28 ntopng ntopng: [host_details.lua:2148] [ts_schema.lua:139] ERROR: missing tag 'protocol' in schema host:ndpi
Apr  2 18:25:28 ntopng ntopng[7943]: 02/Apr/2021 18:25:28 [host_details.lua:2148] [ts_schema.lua:139] ERROR: missing tag 'protocol' in schema host:ndpi

Thanks again

**Comment by handude** [comment]
Just as an FYI. I was going to buy a license anyway, which I did to see what would happen. I do not have issues anymore now while ntopng is licensed.

**Comment by MatteoBiscosi** [comment]
Thanks @handude if the issue will show up again please reopen the ticket. Meanwhile I'll try to check the why you had no debug print (that's really strange) and try to fix the issue without the license. Thank you again for your collaboration.
