### ISSUE TITLE
Rework Alert Page (Global)

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5151]
It is requested to rework current alert page:

![image](https://user-images.githubusercontent.com/3397663/113741052-8fe76480-9701-11eb-8c0a-dd735e2baa2a.png)

The result will be a similar page (create an `alerts_stats.lua`) with a breadcrumb identical to what is currently implemented for user scripts

![image](https://user-images.githubusercontent.com/3397663/113741251-bd341280-9701-11eb-900f-8586455546b1.png)

In essence:
- A breadcrumb will list all alert entities with alerts (entities with no alerts won't appear in the breadcrumb)
- Tabs below the breadcrumb will only show alerts related to the entity selected in the breadcrumb
  - For example, clicking on "Interface" breadcrumb entry will only load interface alerts in the tabs
  - All non-flow entities will have two tabs, namely "engaged" and "Past"
  - Flows will only have a tab "Past"

For the implementation, the following rest endpoints will be used:

- `scripts/lua/rest/v1/get/{host,network,snmp_device,mac,host_pool,process,user,influx_db,category_lists,am_host,periodic_activity,other}/alert/data.lua`
- `scripts/lua/rest/v1/get/flow/alert/data.lua`

Paginated data MUST be supported (https://datatables.net/examples/data_sources/server_side). Pass to the REST endpoints above information for the pagination so that they can return data sliced server-side.

For the buttons (i.e,. the bell to disable, and the bin to delete) reuse existing endpoints. Same for the action buttons currently present at the bottom of the table.

Make just one REST endpoint request example as soon as possible so that https://github.com/ntop/ntopng/issues/5153 can be implemented. Also write a dummy, hardcoded response example that can be used as reference to implement the REST endpoints.

Make the code modular (use javascript files and templates) so that it can be re-used for https://github.com/ntop/ntopng/issues/5152

**Comment by simonemainardi** [comment]
Please, use this reference REST endpoint to implement: https://github.com/ntop/ntopng/commit/a0a4843dc73a7c478acfea1b860b2cfe7a6f526f

Edit (mockup) `record` entries and params for the pagination so I can see them and implement the backend.

**Comment by lucaderi** [comment]
> * scripts

@simonemainardi I believe these alert categories are far too many. What is the point of having 12 categories on a page? I believe it is hard to use it should be divided differently (e.g. with a drop-down menu)

**Comment by simonemainardi** [comment]
Categories

- host,network,snmp_device,mac,host_pool,process,user,influx_db,category_lists,am_host,periodic_activity,other

Will have a common subset of columns

- Date/Time, Duration, Severity, Count, Alert Type, Alert Description, Actions

Then, for each category there will be the following column(s) to indicate the entity/subject/source/origin or whatever other name we can use to nicely indicate 'this-alert-is-related-to'. Specifically:

- host: IP, Name
- network: The network name
- snmp_device: IP of the device, Port (if present)
- mac: MAC, Device type
- host_pool: Name
- process: process name
- user: User name
- influx_db: <Not relevant>
- category_lists: The URL of the category
- am_host: IP, Name
- periodic_activity: Periodic activity name
- other: <Not relevant>

Note: names stored are those detected at the time when the alert was generated.

Note: to ease the implementation, a single formatted column entity/subject/source/origin can be used for every of the above.

An additional column will indicate whether the entity/subject/source/origin is:
- The source of the trouble (we can call it attacker or better origin as attacker seems to be only security-related whether we also have network-related alerts)
- The destination of the trouble (we can call it victim or better target)

A common subset of columns will be present for each category:

Flows can have the same columns, but I would add an extra symbol to the client and to the server to indicate who is the attacker/origin and the victim/target.

**Comment by simonemainardi** [comment]
In terms of mere SQLite schemas, I would make a single schema identical across each category. This is to ease queries and will save a lot of IFs. So basically, apart from the common columns, category-specific columns will become:

- Entity (or another nice name)
  - Will hold the IP for hosts and snmp devices, the network for networks, the Mac for mac, and so on
-  Entity Name
   - Will hold a symbolic name for the entity. Eg., the host name for hosts, the name of the SNMP device for snmp devices, and so on
- Port. It will store the port this alert is coming from. For SNMP devices, it will store the port (if present). Then we can use this for hosts as part of https://github.com/ntop/ntopng/issues/5155
- Exporter: in case of ZMQ, it will store the exporter this alert is coming from

**Comment by simonemainardi** [comment]
I would be desirable to add input/output port and exporter also to flows

**Comment by simonemainardi** [comment]
A possible schema is 

XXX is the new word that will replace the current word entity.

```
           "CREATE TABLE IF NOT EXISTS %s ("
           "rowid             INTEGER PRIMARY KEY AUTOINCREMENT, " /* Must tell it is AUTOINCREMENT */
           "alert_type        INTEGER NOT NULL, "
           "alert_subtype     TEXT NOT NULL, "         // Compatibility, eventually will disappear
           "alert_granularity INTEGER NOT NULL, "     //
           "alert_XXX_val  TEXT NOT NULL,    "     // e.g., the IP for an host, the MAC for a Mac, the IP for an SNMP device
           "alert_XXX_name TEXT  NULL,    "     // A symbolic name (e.g., host alias)
           "alert_snmp_port   INTEGER  NULL,    "   // e.g, the SNMP port of an SNMP-device-related alert
           "alert_exporter    TEXT  NULL,    "      // e.g, the exporter as received via ZMQ (if any)
           "alert_is_origin    INTEGER  DEFAULT 0,    "      // 1 if the XXX is origin/attacker
           "alert_is_target    INTEGER DEFAULT 0,    "      // 1 if the XXX is target/victim
           "alert_severity    INTEGER NOT NULL,  "
           "alert_tstamp      INTEGER NOT NULL,  "
           "alert_tstamp_end  INTEGER DEFAULT NULL, "
           "alert_counter     INTEGER NOT NULL DEFAULT 1, "
           "alert_json        JSON DEFAULT NULL, "
           ");"
           "CREATE INDEX IF NOT EXISTS t2i_type     ON %s(alert_type); "
           "CREATE INDEX IF NOT EXISTS t2i_subtype  ON %s(alert_subtype); "
           "CREATE INDEX IF NOT EXISTS t2i_granularity ON %s(alert_granularity); "
           "CREATE INDEX IF NOT EXISTS t2i_alert_XXX ON %s(alert_XXX_val); "
           "CREATE INDEX IF NOT EXISTS t2i_alert_name ON %s(alert_XXX_name); "
           "CREATE INDEX IF NOT EXISTS t2i_alert_snmp_port ON %s(alert_snmp_port); "
           "CREATE INDEX IF NOT EXISTS t2i_alert_exporter ON %s(alert_exporter); "
           "CREATE INDEX IF NOT EXISTS t2i_severity ON %s(alert_severity); "
           "CREATE INDEX IF NOT EXISTS t2i_tstamp   ON %s(alert_tstamp); "
           "CREATE INDEX IF NOT EXISTS t2i_tstamp_e ON %s(alert_tstamp_end); "
           "CREATE INDEX IF NOT EXISTS t2i_engaged  ON %s(alert_granularity); ",
```

I am well aware that for IP addresses it is not ideal to use TEXT. Choice is due to:

0. Sqlite does not natively support IPs so queries will require casts
1. Simplicity of implementation (won't need to differentiate between host- queries vs. mac-queries, vs. other XXX queries)
3. Cardinality of the tables is small

A separate table will exist for every XXX but they all have the same schema. Names are: host_alerts, mac_alerts, snmp_device_alerts, etc.

**Comment by simonemainardi** [comment]
This issue can be closed as, after internal review, we have decided to create a completely new page and database structure.
