### ISSUE TITLE
Alert Error

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5158]
06/Apr/2021 21:01:06 [AlertCheckLuaEngine.cpp:170] WARNING: Script failure[/Users/deri/network/ntopng/scripts/callbacks/system/system.lua] [...s/deri/network/ntopng/scripts/lua/modules/alerts_api.lua:418: attempt to index a string value (local 'triggered')]
06/Apr/2021 21:02:04 [AlertCheckLuaEngine.cpp:170] WARNING: Script failure[/Users/deri/network/ntopng/scripts/callbacks/system/system.lua] [...s/deri/network/ntopng/scripts/lua/modules/alerts_api.lua:418: attempt to index a string value (local 'triggered')]

**Comment by simonemainardi** [comment]
Likely due to alerted active monitoring devices. Fix in progress.
