### ISSUE TITLE
Entity is a meaningless term and it needs to be removed

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5161]
The term "entity" is meaningless and the code is full of this word. It needs to be removed and replace with a term that fits better.

Example

function host_alert_flow_anomaly.format(ifid, alert, alert_type_params)
  local alert_consts = require("alert_consts")
  local entity = alert_consts.formatAlertEntity(ifid, alert_consts.alertEntityRaw(alert["alert_entity"]), alert["alert_entity_val"])
  local value = alert_type_params.value
  local i18n_key
...
end

**Comment by simonemainardi** [comment]
After the latest rework, we have left entity only as an internal term that is also used by home assistant https://developers.home-assistant.io/docs/core/entity/
