### ISSUE TITLE
Script hooks obsolete albeit required

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5164]
In some user_scripts there are some comments such as

function script.hooks.min(params)
   -- TODO: remove, implemented in C++
end

However removing them introduces a side effect

11/Apr/2021 18:45:51 [startup.lua:16] [user_scripts.lua:709] WARNING: No 'hooks' defined in user script 'XXXX', skipping

This has to be fixed

**Comment by simonemainardi** [comment]
Host hooks removed in `c0ad0ff162b955527d98f3c532d6b352ae835c08`, default is now 1 min.

Flow hooks removed as no longer needed.
