### ISSUE TITLE
Invalid column wrap in Alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5166]
From the screenshots below you can see that the rightmost column is far too wide instead of being as large as necessary. This means that it pushes other columns to wrap even when not necessary 

![Screen Shot 2021-04-11 at 18 00 07](https://user-images.githubusercontent.com/4493366/114349879-bde90080-9b68-11eb-86cc-73f81d30b376.png)
![Screen Shot 2021-04-11 at 18 00 00](https://user-images.githubusercontent.com/4493366/114349883-c04b5a80-9b68-11eb-809a-7a3b10772896.png)

**Comment by simonemainardi** [comment]
Pages are being rewritten from scratch so this issue can be closed.
