### ISSUE TITLE
Clicking 'Reset Counters' Drops only button does not work when using view

### ISSUE THREAD

**Issue by colinlegendre** [ntop/ntopng#5168]
I have 4 nprobe threads feeding into a view.

When i click the 'drops only' button to reset counters it does not work, either under the view to reset dropped exported zmq flows, or under the actual interface to reset the dropped alerts.

Worked fine when not using view and nprobe threads.

**Comment by MatteoBiscosi** [comment]
hi @colinlegendre , can you please report ntopng version?

**Comment by colinlegendre** [comment]
Enterprise L 4.2.210401

**Comment by MatteoBiscosi** [comment]
hi @colinlegendre soon an update is going to be available, could you please update and let me know if both of reset counters are fixed?

**Comment by colinlegendre** [comment]
Will do.

**Comment by simonemainardi** [comment]
any news?

**Comment by colinlegendre** [comment]
I've not had any drops yet.. so the counters are still at 0.  Can't test
until there is something to reset :)

---
Colin Legendre
President and CTO

Coextro - Unlimited. Fast. Reliable.
w: www.coextro.com
e: ***@***.***

p: 647-693-7686 ext.101
m: 416-560-8502
f: 647-812-4132

**Comment by colinlegendre** [comment]
Unfortunately the issue still persists.  Just tested today.

**Comment by simonemainardi** [comment]
@MatteoBiscosi please check. Note that version is 4.2.

**Comment by MatteoBiscosi** [comment]
Hi @colinlegendre I'm sorry to hear that the problem isn't solved. Could you please report your current ntopng version?

**Comment by cardigliano** [comment]
@colinlegendre please provide the output of "ntopng -V" to make sure we are using the same version

**Comment by MatteoBiscosi** [comment]
I ran some test but everything seems working right now. Please reopen if needed.
Closed for inactivity.
