### ISSUE TITLE
mysql grows seems without limits

### ISSUE THREAD

**Issue by lucadistefano** [ntop/ntopng#517]
mysql retention is 2 days.
the system is up since 1 week but the space used by mysql grows each day.
I expected after 3 days older data will be dropped .

root@nbox-demo:~# du -sh /storage/*
54G /storage/mysql
11G /storage/ntopng

I tried to reduce the retention at 1d but data still not dropped.

**Comment by simonemainardi** [comment]
MySQL InnoDB does not release `ibdata1` disk space after deleting data rows from table: http://dev.mysql.com/doc/refman/5.7/en/innodb-file-space.html

Make sure to configure MySQL to use `innodb_file_per_table`. In this way the disk space is released after an optimize table: http://dev.mysql.com/doc/refman/5.7/en/optimize-table.html

**Comment by lucadistefano** [comment]
the option is already activated:
innodb_file_per_table=1

as you see the ibdata1 is not big:
root@nbox-demo:~# ll -h /storage/mysql/
total 2,9G
drwx------ 5 mysql mysql 4,0K apr 19 08:59 ./
drwxr-xr-x 4 root  root  4,0K apr  1 11:49 ../
-rw-rw---- 1 mysql mysql **866M** apr 20 11:58 ibdata1
-rw-rw---- 1 mysql mysql 1,0G apr 20 11:58 ib_logfile0
-rw-rw---- 1 mysql mysql 1,0G apr 20 10:42 ib_logfile1
drwx------ 2 mysql root  4,0K apr 11 14:22 mysql/
-rw-r----- 1 root  root  8,4K apr 15 15:56 mysqld.log
-rw-rw---- 1 mysql mysql  45K apr 20 09:20 mysql-slow.log
-rw------- 1 root  root     6 apr 11 14:22 mysql_upgrade_info
drwx------ 2 mysql mysql 4,0K apr 11 14:43 ntopng/
drwx------ 2 mysql mysql 4,0K apr 11 14:22 performance_schema/

and the file per table is correctly used:

root@nbox-demo:~# ll -h /storage/mysql/ntopng/
total 54G
drwx------ 2 mysql mysql 4,0K apr 11 14:43 ./
drwx------ 5 mysql mysql 4,0K apr 19 08:59 ../
-rw-rw---- 1 mysql mysql   65 apr 11 14:41 db.opt
-rw-rw---- 1 mysql mysql 9,0K apr 11 14:43 flowsv4.frm
-rw-rw---- 1 mysql mysql  168 apr 11 14:43 flowsv4.par
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p0.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p10.ibd
-rw-rw---- 1 mysql mysql 1,8G apr 20 11:58 flowsv4#P#p11.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p12.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p13.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p14.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p15.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p16.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p17.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p18.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p19.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p1.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p20.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p21.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p22.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p23.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p24.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p25.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p26.ibd
-rw-rw---- 1 mysql mysql 1,8G apr 20 11:58 flowsv4#P#p27.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p28.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p29.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p2.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p30.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p31.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p3.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p4.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p5.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p6.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p7.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p8.ibd
-rw-rw---- 1 mysql mysql 1,7G apr 20 11:58 flowsv4#P#p9.ibd
-rw-rw---- 1 mysql mysql  13K apr 11 14:43 flowsv6.frm
-rw-rw---- 1 mysql mysql  168 apr 11 14:43 flowsv6.par
-rw-rw---- 1 mysql mysql  20M apr 20 11:58 flowsv6#P#p0.ibd
-rw-rw---- 1 mysql mysql  20M apr 20 11:58 flowsv6#P#p10.ibd
-rw-rw---- 1 mysql mysql  20M apr 20 11:58 flowsv6#P#p11.ibd
-rw-rw---- 1 mysql mysql  23M apr 20 11:58 flowsv6#P#p12.ibd
-rw-rw---- 1 mysql mysql  21M apr 20 11:58 flowsv6#P#p13.ibd
-rw-rw---- 1 mysql mysql  20M apr 20 11:58 flowsv6#P#p14.ibd
-rw-rw---- 1 mysql mysql  19M apr 20 11:58 flowsv6#P#p15.ibd
-rw-rw---- 1 mysql mysql  20M apr 20 11:58 flowsv6#P#p16.ibd
-rw-rw---- 1 mysql mysql  20M apr 20 11:58 flowsv6#P#p17.ibd
-rw-rw---- 1 mysql mysql  19M apr 20 11:58 flowsv6#P#p18.ibd
-rw-rw---- 1 mysql mysql  19M apr 20 11:58 flowsv6#P#p19.ibd
-rw-rw---- 1 mysql mysql  20M apr 20 11:58 flowsv6#P#p1.ibd
-rw-rw---- 1 mysql mysql  19M apr 20 11:58 flowsv6#P#p20.ibd
-rw-rw---- 1 mysql mysql  19M apr 20 11:58 flowsv6#P#p21.ibd
-rw-rw---- 1 mysql mysql  20M apr 20 11:58 flowsv6#P#p22.ibd
-rw-rw---- 1 mysql mysql  20M apr 20 11:58 flowsv6#P#p23.ibd
-rw-rw---- 1 mysql mysql  20M apr 20 11:58 flowsv6#P#p24.ibd
-rw-rw---- 1 mysql mysql  20M apr 20 11:58 flowsv6#P#p25.ibd
-rw-rw---- 1 mysql mysql  20M apr 20 11:58 flowsv6#P#p26.ibd
-rw-rw---- 1 mysql mysql  20M apr 20 11:58 flowsv6#P#p27.ibd
-rw-rw---- 1 mysql mysql  20M apr 20 11:58 flowsv6#P#p28.ibd
-rw-rw---- 1 mysql mysql  19M apr 20 11:58 flowsv6#P#p29.ibd
-rw-rw---- 1 mysql mysql  20M apr 20 11:58 flowsv6#P#p2.ibd
-rw-rw---- 1 mysql mysql  20M apr 20 11:58 flowsv6#P#p30.ibd
-rw-rw---- 1 mysql mysql  19M apr 20 11:58 flowsv6#P#p31.ibd
-rw-rw---- 1 mysql mysql  20M apr 20 11:58 flowsv6#P#p3.ibd
-rw-rw---- 1 mysql mysql  20M apr 20 11:58 flowsv6#P#p4.ibd
-rw-rw---- 1 mysql mysql  19M apr 20 11:58 flowsv6#P#p5.ibd
-rw-rw---- 1 mysql mysql  19M apr 20 11:58 flowsv6#P#p6.ibd
-rw-rw---- 1 mysql mysql  19M apr 20 11:58 flowsv6#P#p7.ibd
-rw-rw---- 1 mysql mysql  19M apr 20 11:58 flowsv6#P#p8.ibd
-rw-rw---- 1 mysql mysql  20M apr 20 11:58 flowsv6#P#p9.ibd

**Comment by simonemainardi** [comment]
you need to `OPTIMIZE TABLE` to reclaim disk space

**Comment by lucadistefano** [comment]
if optimize table is needed for reclaim space, it should be executed after the drop of the data but
anyway there is another problem: innodb optimize recreates the whole table, if your db has 50 G of data the optimization takes hours and the twice of the space.

Therefore the solution is to use a partitioning at application layer. you can create a table per day and when the table expires you simply drop that table and the space can be reclaimed from os.

**Comment by simonemainardi** [comment]
Creating a separate table for each day as you are suggesting will cause big headaches when querying. How would you deal with queries that span more than one day? You will be forced to use MySQL Views or `UNION`s or some other aggregation mechanism. I don't think this suggestion is viable.

---

I think a viable solution is to prevent the MySQL database to become bigger than what you can actually handle. 

If you start with a clean database and immediately set the data retention to a number of days that you can reasonably handle, then you won't even need to `OPTIMIZE TABLE`. New records will take the place of the old ones and the size should settle.

If, as in your case, you let the MySQL database grow before changing the data retention, then you'll have to use optimize table to reclaim space.

**Comment by lucadistefano** [comment]
I agree, but the question is that the system was reconfigured from scratch 8 days ago with a retention of 2 days but the database has grown constantly.
Now I updated ntopng and wiped all data from ntopng and mysql. I configured a check on fs and mysql for to graph the size of the db in the time.

About 'manual' :-) partitioning, yes we use unions on a very large data : db of ~200GB with unions that works on 6-10 tables and the queries are fast enough. We use myisam tables that are faster on insert and reading because we don't need to use transactions. Deletion of rows is time consuming and causes db fragmentation and causes reorganization of indexes. I found is faster to drop tables.

Anyway the solution is up to you, what is important is that the size of db can be under control.

**Comment by lucadistefano** [comment]
when I should expect the deletion of rows, it is triggered at defined time or constantly ? I have setted retention 1d.

thanks

**Comment by lucadistefano** [comment]
after 1d and 6 hours I don't see row deletions:
| Innodb_rows_deleted                      | 0            |
| Innodb_rows_inserted                     | 7151365      |

can I force the cleanup?

**Comment by simonemainardi** [comment]
cleanup should start at midnight local time provided that ntopng is running. Script is daily.lua
