### ISSUE TITLE
Error while browsing alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5170]
![Screen Shot 2021-04-12 at 21 39 20](https://user-images.githubusercontent.com/4493366/114451477-954c1f80-9bd7-11eb-8544-434b34a809f2.png)

Apr 12 21:37:46 ntop ntopng[5320]:  string stack traceback:
Apr 12 21:37:46 ntop ntopng[5320]:         /usr/share/ntopng/scripts/lua/modules/alert_consts.lua:533: in function 'alert_consts.alertEngine'
Apr 12 21:37:46 ntop ntopng[5320]:         .../lua/modules/alert_definitions/host/host_alert_score.lua:55: in function 'host_alert_score.format'
Apr 12 21:37:46 ntop ntopng[5320]:         /usr/share/ntopng/scripts/lua/modules/alert_utils.lua:2106: in function 'alert_utils.formatAlertMessage'
Apr 12 21:37:46 ntop ntopng[5320]:         /usr/share/ntopng/scripts/lua/get_alerts_table_data.lua:129: in main chunk
Apr 12 21:37:46 ntop ntopng[5320]: 12/Apr/2021 21:37:46 [LuaEngine.cpp:1148] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_alerts_table_data.lua][/usr/share/ntopng/scripts/lua/modules/alert_consts.lua:536: attempt to index a nil value (field '?')]
Apr 12 21:37:46 ntop ntopng[5320]: [LuaEngine.cpp:1148] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_alerts_table_data.lua][/usr/share/ntopng/scripts/lua/modules/alert_consts.lua:536: attempt to index a nil value (field '?')]

**Comment by MatteoBiscosi** [comment]
This issue should be fixed thanks to the fix to the issue #5169
