### ISSUE TITLE
Interface disaggregation does not support aggregated view

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5173]
When enabling interface disaggregation (e.g. based on Ingress Interface Id) several interfaces are created. Adding view:all or view:<interface name> is compulsory to see all the traffic of the router put together regardless of the aggregation. Unfortunately the above techniques do not working and replicating traffic on all interfaces is not an option

**Comment by simonemainardi** [comment]
This can be done by dynamically adding interfaces to the existing `view:all` interface. It is necessary to slightly modify `ViewInterface.cpp` to handle the dinamic addition but it is doable.

From an UI/user perspective:
- An extra flag will be added under the interface 'cog' page when disaggregation is turned on. The flag will say "Consider this interface part of the view:all (a restart of ntopng with -i view:all is required)"
- This existing flag can be kept or merged
![image](https://user-images.githubusercontent.com/3397663/120660294-7a838200-c487-11eb-8533-f9c9344bf8bf.png)
- Then, at runtime, new subinterfaces will be added to the view:all (if present).

Limitations:
- Restart of ntopng required after changing the option
- Current maximum number of interfaces belonging to a view: 8 (`MAX_NUM_VIEW_INTERFACES`)

**Comment by lucaderi** [comment]
I don't think that your proposal addresses the problem as it's complicated for the user and not automatic. I expect vice:all to work with not difference with respect to what it is today.

**Comment by MatteoBiscosi** [comment]
It has been decided that the full implementation is very complex so for the time being it is required to enable the duplicate disaggregated traffic as suggested by @simonemainardi
