### ISSUE TITLE
Alert for Daily throughput does not work correctly

### ISSUE THREAD

**Issue by colinlegendre** [ntop/ntopng#5175]
I have alerts setup for Daily throughput and hourly throughput via the user scripts.

The hourly one seems to work correctly as set alerting when the hourly throughput of a host is above 75 Mbps.

The daily one does not.. i have it set to 50mbps daily.. but it seems to alert even when that is not the case.. i looked at all the hosts with the alert and none had an avg of 50Mbps over the 25 hours prior to the alert.. not even close.

**Comment by MatteoBiscosi** [comment]
Hi @colinlegendre can you please send the screenshot of the traffic timeserie of the last 24 h of an host that triggered the alert (you can find the host timeserie by clicking onto a chart icon of the host menu 
![Screenshot from 2021-04-16 16-57-23](https://user-images.githubusercontent.com/49585191/115043618-fd02b300-9ed4-11eb-8cad-caaf425dce7e.png)
 and selecting the traffic timeserie into the menu)?

**Comment by simonemainardi** [comment]
Daily throughput interface alerts are no longer supported with the current implementation. Need rediscuss and rework the way we generate throughput-based alerts.
