### ISSUE TITLE
traffic profile not tagging

### ISSUE THREAD

**Issue by narankhetani** [ntop/ntopng#518]
Hi Luca/Simone,

We have changed to just use 1 traffic profile “pat_SecureVPN=net 10.255.16.0/20 or net 10.10.106.0/23 or net 10.10.108.0/23”

Sometime flow matches the profile but doesn’t get tagged – this would cause the query base on profile name to miss the packet:
| 2016-04-18 18:50:44           | pat_SecureVPN |       0 | 10.255.18.196          | 10.78.128.49           |       52165 |          22 |        6 |
| 2016-04-18 20:38:56           |               |       0 | 10.255.16.186          | 10.78.15.10            |       56829 |          22 |        6 |   <<< should be matched with “pat_SecureVPN” profile
…snip….
 2016-04-18 13:58:58           | pat_SecureVPN |       0 | 10.255.29.175          | 10.251.78.190          |       63774 |         443 |        6 |
| 2016-04-18 15:13:36           |               |       0 | 10.255.20.170          | 10.78.128.10           |       55680 |         443 |        6 |  <<< should be matched with “pat_SecureVPN” profile
| 2016-04-18 15:11:28           |               |       0 | 10.255.20.170          | 10.78.128.18           |       54880 |         443 |        6 | <<< should be matched with “pat_SecureVPN” profile
| 2016-04-18 17:31:47           | pat_SecureVPN |       0 | 10.255.18.162          | 10.78.15.26            |       49153 |         443 |        6 |

**Comment by simonemainardi** [comment]
Flow profile assignment was done only _after_ nDPI L7 protocol detection. This required a minimum of `NDPI_MIN_NUM_PACKETS` (hardcoded at 10). Flows with a number of packets less that 10 (e.g., pings) were not assigned to profiles. 

Fix has been introduced. Packages are being build and will be available starting from tomorrow.
