### ISSUE TITLE
Host Map: Reload button is not consistent 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5184]
The reload button of the host map

![Screen Shot 2021-04-18 at 19 20 09](https://user-images.githubusercontent.com/4493366/115154436-26f5da00-a07b-11eb-82fb-a797eaf33878.png)

should be consistent with the ntopng GUI

![Screen Shot 2021-04-18 at 19 20 22](https://user-images.githubusercontent.com/4493366/115154432-25c4ad00-a07b-11eb-8a65-555f538fee77.png)

It is requested to make it consistent with the ntopng GUI also by placing it in the top right corner next to the dropdown menu

**Comment by gabryon99** [comment]
Thanks to @MatteoBiscosi the button is now placed in the right position as shown in the image below (next to the filter dropdown).

<img width="1699" alt="Screenshot 2021-04-21 at 11 24 05" src="https://user-images.githubusercontent.com/14114916/115530479-17051280-a294-11eb-8442-e16725a546f2.png">
