### ISSUE TITLE
Inability to filter on Flow Status values

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5189]
![Screen Shot 2021-04-20 at 10 19 12](https://user-images.githubusercontent.com/4493366/115362502-e48ae500-a1c1-11eb-8035-2c3959a13840.png)

**Comment by lucaderi** [comment]
![Screen Shot 2021-04-20 at 17 11 12](https://user-images.githubusercontent.com/4493366/115420460-719e6000-a1fb-11eb-8bfa-e6cdda087a37.png)
Still bugged: filtering seems to work but the label is not correct

**Comment by MatteoBiscosi** [comment]
fixed under the pro repository

**Comment by lucaderi** [comment]
Verified as fixed
