### ISSUE TITLE
ICMP Traffic doesn't match traffic profile at all

### ISSUE THREAD

**Issue by narankhetani** [ntop/ntopng#519]
ICMP traffic doesn’t seem to match with traffic profile at all.  Is this intentional? If yes, is there any other protocol wouldn’t match the traffic profile? 
| 2016-04-18 20:38:54           |               |       0 | 10.255.16.186          | 10.78.15.10            |           0 |           0 |        1 |
| 2016-04-14 16:20:52           |               |       0 | 10.255.29.167          | 10.78.15.23            |           0 |           0 |        1 |
| 2016-04-13 19:46:41           |               |       0 | 10.255.19.168          | 10.78.160.33           |           0 |           0 |        1 |
| 2016-04-18 17:11:39           |               |       0 | 10.255.19.191          | 10.78.160.33           |           0 |           0 |        1 |

**Comment by simonemainardi** [comment]
6fa077c fixes the issue. The root cause is the same as #518
