### ISSUE TITLE
Disabled User Scripts continue to generate Alerts

### ISSUE THREAD

**Issue by netsolv** [ntop/ntopng#5191]
On latest version, disabled ALL user scripts, yet I continue to show alerts on scripts that are DISABLED.

**Comment by netsolv** [comment]
I have restart ntopng.service multiple times to try and "flush" out the settings. Ex: tls_old_proto_version whether enabled or disabled still is posting alerts. For some reason or another ntopng is NOT updating which user scripts are enabled or disabled and generating alerts accordingly.

**Comment by simonemainardi** [comment]
Please, visit system -> settings -> manage configurations and do a reset of the "User Scripts".

**Comment by netsolv** [comment]
Performed actions as requested, same result... after the reset "re-enabled" all the scripts.. I disabled all except the blacklist and the alerts are still being generated from scripts that are not enabled... aka " Obsolete TLS Version" "Possibly Client Malicious JA3 Signature" the primary one I need to disable is the "Obsolete TLS Version" the site uses to many 1.1 and 1.2 types.

**Comment by simonemainardi** [comment]
please, report the version used.

**Comment by simonemainardi** [comment]
Confirmed working in the latest dev. Please, hold on until https://github.com/ntop/ntopng/issues/5196 is solved, and then update.
