### ISSUE TITLE
New Alerts Explorer - Idea and UI

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5194]
Current alert explorer, although non-optimal, can be made useful with some changes.

For Flows this is the present explorer:

![image](https://user-images.githubusercontent.com/3397663/115426782-20916a80-a201-11eb-95ea-64de1e4044f8.png)

The following changes must be applied (work only on past alerts for now):

---

Poor layout of filter criteria:

![image](https://user-images.githubusercontent.com/3397663/115427074-6a7a5080-a201-11eb-9cd9-59ea9e729f3e.png)

- All criteria (including the filter textbox and the apply button) must stay on one line.

- 30m, 1h, 1d, 1w become a dropdown like the one in the current explorer:

![image](https://user-images.githubusercontent.com/3397663/115427274-9eee0c80-a201-11eb-98aa-88b53e909243.png)

![image](https://user-images.githubusercontent.com/3397663/115427296-a4e3ed80-a201-11eb-9259-a5cb84b04412.png)

Selection will automatically reflect on the datetimepicker.

---

No additional button must appear in the histogram

![image](https://user-images.githubusercontent.com/3397663/115427605-e5dc0200-a201-11eb-883b-ad950af2c247.png)

---

client and server columns must be adjacent, e.g., 

![image](https://user-images.githubusercontent.com/3397663/115427866-1f147200-a202-11eb-8c48-0e003b24f3ae.png)

same for their names

---

Filters must have the same names of the column., not like "Client IP" vs "Client"

![image](https://user-images.githubusercontent.com/3397663/115427996-3e130400-a202-11eb-8173-fa5e8cbd4d2d.png)

---

Filters must be validated against their type

![image](https://user-images.githubusercontent.com/3397663/115428129-5edb5980-a202-11eb-8ec8-50b21604499e.png)

---

Addition of invalid filters should be prevented

![image](https://user-images.githubusercontent.com/3397663/115428186-6f8bcf80-a202-11eb-9229-6870fb9a7c62.png)

---

Autocompletion should be present, i.e., typing applic should show "Application"

![image](https://user-images.githubusercontent.com/3397663/115428288-88948080-a202-11eb-99ae-35d389ce53bd.png)

---

Severity and alert type should be add filters too

![image](https://user-images.githubusercontent.com/3397663/115428426-ad88f380-a202-11eb-8a33-c4525de36a9c.png)

---

Severity filter must support also >= and <=

---

actions is poorly styled

![image](https://user-images.githubusercontent.com/3397663/115428600-d90bde00-a202-11eb-9609-b2250b780cdb.png)

---

Hyperlinks must be in italic to signify they point to historical data

---

Mouseover doesn't tell the exact timestamp

![image](https://user-images.githubusercontent.com/3397663/115428929-2c7e2c00-a203-11eb-9bf6-214eee543bf3.png)

---

An exotic timeseries name is reported

![image](https://user-images.githubusercontent.com/3397663/115428971-3738c100-a203-11eb-9681-9b333cd671b3.png)

---

we would like to color each bar of the histogram with multiple colors, depending on the severity. Please, comment if the histogram can to this thing and we will update the backend accordingly. In case this is doable, attach an example of response you would like to receive.

---

**Comment by lucaderi** [comment]
Please open individual tickets
