### ISSUE TITLE
Flow Status Dropdown - Invalid Chart

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5195]
This is what happens when we select an entry from the flow status dropdown

![image](https://user-images.githubusercontent.com/3397663/115509285-8b34bb80-a27e-11eb-9487-3ef0c4c33548.png)

The chart must not be visible.

**Comment by simonemainardi** [comment]
The idea was to show a chart with aggregated information across flows matching the various filters.

However, this design is flawed under many aspects:

1. A ton of whitespace is wasted. Just report the overall total bytes and throughput. Remove the charts. Consider using a table header to write this information on the same line of the dropdown to avoid wasting space
2. Throughput doesn't work.
3. Chart is extremely expensive to be computed. Every 5 seconds a whole walk on the flows is prohibitive.
4. Reuse `local flowstats = interface.getActiveFlowsStats(host, flows_filter)` and clear the currently used function (data is already calculated so there's no extra work to do)

**Comment by lucaderi** [comment]
IMHO
1. This problem is now fixed
2. I have just tested and it works for me. Please show the bug
3. What are the other options on the table?
4. Your function collects more info than necessary with respect to the current implementation, addressing above comment 3.

**Comment by simonemainardi** [comment]
2.

![image](https://user-images.githubusercontent.com/3397663/115571139-028a3f80-a2bf-11eb-9f9e-f7f13bd15d1d.png)

3.

a) Limit the throughput to Layer-7 applications and show the chart only when a Layer-7 application is selected from the dropdown. Keep throughput straight into the interface Layer-7 nDPIStats and read them without walking the whole hash table
b) Add a refresh button next to the chart

My experience has shown that waking the full flows hash table every 5 seconds when the UI is open causes:
- CPU spikes especially on low end devices
- Slowdowns in the flows lifecycle, causing and increase in the overall used RAM

4. Correct, but just a bunch of additional counters, a negligible cost when compared to the cost of a full hash table scan.

**Comment by simonemainardi** [comment]
This is how it looks like when the page opens

![image](https://user-images.githubusercontent.com/3397663/115680253-b3421e80-a353-11eb-81b4-b93afde463be.png)

This is how it looks like when it refreshes

![image](https://user-images.githubusercontent.com/3397663/115680415-d2d94700-a353-11eb-91f9-d6dd0fd19447.png)

**Comment by lucaderi** [comment]
It was decided to leave the chart only for L7 protocols

**Comment by MatteoBiscosi** [comment]
Removed flow filtered charts, except for L7 protocols filter as requested. Please reopen if something needs to be added/changed
