### ISSUE TITLE
Actions button breaks user scripts layout

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5196]
![image](https://user-images.githubusercontent.com/3397663/115536459-1b342e80-a29a-11eb-8aab-ead3dd29cd4c.png)

**Comment by gabryon99** [comment]
I reverted the original code for the 'Action' column inside the `alerts-store` branch. In the future I will integrate the new context menu for the actions in order to save space for the columns and avoid hidden buttons.
