### ISSUE TITLE
Invalid flow status in flow explorer

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5197]
![Screen Shot 2021-04-21 at 15 28 18](https://user-images.githubusercontent.com/4493366/115561835-3b71e680-a2b6-11eb-975a-7972b902d012.png)

Unknown value is not acceptable for the flow status: I believe there is a mapping issue

**Comment by MatteoBiscosi** [comment]
Implemented into the pro repository

**Comment by lucaderi** [comment]
Verified as fixed even though i prefer to see an empty field instead of "no status"
