### ISSUE TITLE
Flow Explorer: actions button does not execute any action 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5198]
![Screen Shot 2021-04-21 at 15 29 47](https://user-images.githubusercontent.com/4493366/115562068-6e1bdf00-a2b6-11eb-83ad-49ca89ade697.png)

**Comment by MatteoBiscosi** [comment]
Fixed into pro repo

**Comment by lucaderi** [comment]
![Screen Shot 2021-04-23 at 18 17 53](https://user-images.githubusercontent.com/4493366/115900437-41a3c680-a460-11eb-9046-eaf9b8b93eb8.png)
The action button is working now but a new bug popped up

**Comment by lucaderi** [comment]
Verified as fixed
