### ISSUE TITLE
New Alerts Explorer - Poor Filters Layout

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5199]
Poor layout of filter criteria:

![image](https://user-images.githubusercontent.com/3397663/115427074-6a7a5080-a201-11eb-9cd9-59ea9e729f3e.png)

- All criteria (including the filter textbox and the apply button) must stay on one line.

- 30m, 1h, 1d, 1w become a dropdown like the one in the current explorer:

![image](https://user-images.githubusercontent.com/3397663/115427274-9eee0c80-a201-11eb-98aa-88b53e909243.png)

![image](https://user-images.githubusercontent.com/3397663/115427296-a4e3ed80-a201-11eb-9259-a5cb84b04412.png)

Selection will automatically reflect on the datetimepicker.

---

source https://github.com/ntop/ntopng/issues/5194

**Comment by gabryon99** [comment]
As said in #5200 in [this comment](https://github.com/ntop/ntopng/issues/5200#issuecomment-825595535), these edits will change the nindex page because the range picker is a template used in both pages.

**Comment by cardigliano** [comment]
It should be clear to the user that 1d is a shortcut for "Last" 1d that will change the time range in the date picker, and this is not relative to the current time interval. What about adding at least the word "Last" before the selection?

**Comment by gabryon99** [comment]
@cardigliano it's fine for me.

The range picker layout on Firefox is visually broken, I'll fix it.

**Comment by gabryon99** [comment]
<img width="1792" alt="Screenshot 2021-04-23 at 15 03 46" src="https://user-images.githubusercontent.com/14114916/115875038-1b246200-a445-11eb-911d-ccb827d4681d.png">

Layout fixed in Firefox. Remember to **reload the cache** to see the new changes.
