### ISSUE TITLE
bandwidth graph at bottom reports local-local traffic also

### ISSUE THREAD

**Issue by snapsnapsnap** [ntop/ntopng#52]
in the past, the graph only reported local-external and external-local traffic. now it seems to report all traffic, which is of no use to me.

**Comment by lucaderi** [comment]
@snapsnapsnap Please paste the URL and a picture of the graph you are talking about

**Comment by snapsnapsnap** [comment]
​our external BW is only 12Mbps, and that is the one I am worried about,

I have defined all our local networks.


On Fri, Jun 12, 2015 at 4:59 PM, Luca Deri <notifications@github.com> wrote:

> @snapsnapsnap <https://github.com/snapsnapsnap> Please paste the URL and
> a picture of the graph you are talking about
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ntop/ntopng/issues/52#issuecomment-111434433>.
>



-- 

.............................__o
.............................\<,
..........................( )/ ( )
................................
. Sverre Rakkenes
. www.rakkenes.org
. sverre@rakkenes.org
................................

**Comment by lucaderi** [comment]
@snapsnapsnap Picture please

**Comment by snapsnapsnap** [comment]
![selection_534](https://cloud.githubusercontent.com/assets/3761022/8128336/19c9d1bc-1128-11e5-92c0-c2d63e22e484.png)
sorry, I added it to email, but that did not seem to work, hope this work better.

**Comment by JuergenWeber** [comment]
You may need to add a filter statement ( -B=... ) to your ntopng.conf in additional to the local networks definition.

**Comment by lucaderi** [comment]
@snapsnapsnap Can you please update ntopng and see if it works better now?

**Comment by snapsnapsnap** [comment]
ok, will try when I get to office

On Wed, Jul 15, 2015 at 11:44 PM, Luca Deri <notifications@github.com>
wrote:

> @snapsnapsnap <https://github.com/snapsnapsnap> Can you please update
> ntopng and see if it works better now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ntop/ntopng/issues/52#issuecomment-121674747>.
>



-- 

.............................__o
.............................\<,
..........................( )/ ( )
................................
. Sverre Rakkenes
. www.rakkenes.org
. sverre@rakkenes.org
................................

**Comment by lucaderi** [comment]
The current code in git has a new updated version of the bottom report that should address your request
