### ISSUE TITLE
Highlight During Select / Zoom

### ISSUE THREAD

**Issue by arrmo** [ntop/ntopng#520]
Hi,

When dragging to select, to zoom in on a (historical) plot, it would be nice if the selected area were highlighted (to make selection easier).

Thanks!

**Comment by simonemainardi** [comment]
We are reworking timeseries handling and also evaluating new js charting libraries that provide more advanced filtering of displayed charts. We can't add the zoom selection to the current library so I am closing this issue temporarily. However, we will keep this suggestion into account and make sure the new charting library will provide it.
