### ISSUE TITLE
New Alerts Explorer - No additional button must appear in the histogram

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5200]
No additional button must appear in the histogram

![image](https://user-images.githubusercontent.com/3397663/115427605-e5dc0200-a201-11eb-883b-ad950af2c247.png)

---

Source https://github.com/ntop/ntopng/issues/5194

**Comment by gabryon99** [comment]
I think we should leave these additional buttons:
1. The "Zoom" button is shown when the histogram `zoom` functionality is enabled (https://apexcharts.com/docs/options/chart/zoom/), thus disabling the button implies disabling the zoom functionality;
2. The Hamburger Button (the three lines) is useful to download a snapshot of the chart in a PNG image file, or in an SVG image file.

**Comment by simonemainardi** [comment]
1. So remove the Zoom/+ Zoom/- buttons from the search filters and leave it.
2. OK

**Comment by gabryon99** [comment]
Removing the Zoom/+ and Zoom/- implies the removing of the buttons contained inside the new nindex page.

**Comment by cardigliano** [comment]
@gabryon99 I think we should have a single Zoom +/- button to avoid duplicated controls (and confusion for the user)

**Comment by gabryon99** [comment]
<img width="244" alt="Screenshot 2021-04-23 at 14 53 56" src="https://user-images.githubusercontent.com/14114916/115873842-bcaab400-a443-11eb-8932-f0480fba50eb.png">

Hidden the "zoom" icon as requested. The hamburger button will remain as I said [here](https://github.com/ntop/ntopng/issues/5200#issuecomment-824623783).
