### ISSUE TITLE
New Alerts Explorer - Filters for Severity and Type

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5206]
Severity and alert type should be add filters too

![image](https://user-images.githubusercontent.com/3397663/115428426-ad88f380-a202-11eb-8a33-c4525de36a9c.png)

They must support also >= and <=

---

Source https://github.com/ntop/ntopng/issues/5194

**Comment by cardigliano** [comment]
By clicking on the histogram colors implemented in #5210 should also apply a filter on severity

**Comment by cardigliano** [comment]
By clicking on the alert name (part of the description) it is possible to filter by alert type now

**Comment by simonemainardi** [comment]
They are both implemented now.
