### ISSUE TITLE
New Alerts Explorer - Mouseover doesn't tell the exact timestamp

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5208]
Mouseover doesn't tell the exact timestamp

![image](https://user-images.githubusercontent.com/3397663/115428929-2c7e2c00-a203-11eb-9bf6-214eee543bf3.png)

---

Source https://github.com/ntop/ntopng/issues/5194

**Comment by gabryon99** [comment]
Issue moved on ticket https://github.com/ntop/ntopng/issues/5282.
