### ISSUE TITLE
New Alerts Explorer - Meaningless timeseries name reported

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5209]
An exotic timeseries name is reported

![image](https://user-images.githubusercontent.com/3397663/115428971-3738c100-a203-11eb-9681-9b333cd671b3.png)

---

Source https://github.com/ntop/ntopng/issues/5194

**Comment by gabryon99** [comment]
To give a meaningful name the REST endpoint that provides the timeseries must be edited. You have to set the field `name` of the `serie` inside the `series` array given as answer.

**Comment by simonemainardi** [comment]
Thanks for the hint. Fixed in 69cd80a4725a37ac86c69968077c1d56426b85ca.
