### ISSUE TITLE
Plugins exclusion lists are not honoured

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5212]
![Screenshot_2021-04-22_at_10 30 45](https://user-images.githubusercontent.com/4493366/115711101-6b32f400-a373-11eb-82ae-ad374242adf9.png)

Walk through all plugins and make sure the explosion list is honoured. As example this plugin does not honour it

**Comment by simonemainardi** [comment]
Fixed in the referenced commits.
