### ISSUE TITLE
Error while setting IP exception in unexpected DNS plugin

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5213]
![Screenshot_2021-04-22_at_10 30 14](https://user-images.githubusercontent.com/4493366/115711319-a9301800-a373-11eb-9278-1ead10be4529.png)

This ticket depends on #5212

**Comment by cardigliano** [comment]
The ip=X.X.X.X format is currently supported in the Exclusion List. This should be simplified as it is not user friendly.
