### ISSUE TITLE
Notification error

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5214]
22/Apr/2021 17:17:41 [LuaEngine.cpp:560] WARNING Script failure [/usr/share/ntopng/scripts/callbacks/system/notifications.lua][/usr/share/ntopng/scripts/lua/modules/pools/host_pools.lua:387: attempt to index a nil value (global 'host')]
22/Apr/2021 17:17:08 [LuaEngine.cpp:560] WARNING Script failure [/usr/share/ntopng/scripts/callbacks/system/notifications.lua][/usr/share/ntopng/scripts/lua/modules/pools/host_pools.lua:387: attempt to index a nil value (global 'host')]
22/Apr/2021 17:17:05 [LuaEngine.cpp:560] WARNING Script failure [/usr/share/ntopng/scripts/callbacks/system/notifications.lua][/usr/share/ntopng/scripts/lua/modules/pools/host_pools.lua:387: attempt to index a nil value (global 'host')]
22/Apr/2021 17:16:50 [LuaEngine.cpp:560] WARNING Script failure [/usr/share/ntopng/scripts/callbacks/system/notifications.lua][/usr/share/ntopng/scripts/lua/modules/pools/host_pools.lua:387: attempt to index a nil value (global 'host')]
22/Apr/2021 17:16:44 [LuaEngine.cpp:560] WARNING Script failure [/usr/share/ntopng/scripts/callbacks/system/notifications.lua][/usr/share/ntopng/scripts/lua/modules/pools/host_pools.lua:387: attempt to index a nil value (global 'host')]

**Comment by simonemainardi** [comment]
This is fixed as reported by the user. Moreover, `host.` pointer to active hosts is no longer existing in the codebase.
