### ISSUE TITLE
Factory Reset - Clicking on button is ineffective

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5215]
Clicking on this button is ineffective (branch alerts-store)

![image](https://user-images.githubusercontent.com/3397663/115755593-cb3e9000-a39d-11eb-90f8-2d259d1b2e1d.png)

**Comment by gabryon99** [comment]
Fixed. The problem was with a missing space. Next time can you attach a screenshot of the console to see if there are any errors? Thanks.
