### ISSUE TITLE
"Eth0 is dropping alerts" - using only builtin sqlite recipient

### ISSUE THREAD

**Issue by rreiner** [ntop/ntopng#5217]
Seeing an alert "Interface eth0 is dropping alerts. Likely it is generating too many of them, or recipients are slow."

But the only alert recipient is is the builtin_config_sqlite, and the alert rate is low.

Screenshots attached.  In the screenshots the redacted IP addresses are those of internal hosts -- all different ones.

![image](https://user-images.githubusercontent.com/12399329/115761713-a54ec680-a370-11eb-8e10-041cbecc1894.png)

![image](https://user-images.githubusercontent.com/12399329/115761748-ae3f9800-a370-11eb-9a57-cf4dbfe6b944.png)

Using ntopng current on Raspbian current:
Version:        4.3.210419 [Enterprise/Professional/Embedded build]
GIT rev:        dev:c46634d3ea424a81e569c5c97293906ef99021e3:20210419
Pro rev:        r3725
Built on:       Raspbian GNU/Linux 10 (buster)
System Id:      130FA343499602D2
Platform:       armv7l
Edition:        Enterprise Embedded
License Type:   Time-Limited [Empty license file]
Validity:       Until Thu Apr 22 13:58:40 2021

**Comment by simonemainardi** [comment]
This functionality is being reworked and will be merged into dev shortly. Thanks for reporting.

**Comment by cardigliano** [comment]
Fixed with the branch merge two days ago. 2278926da4a90a7b2098383b06a31371b6d8dced
