### ISSUE TITLE
Topology map related to 10G interfaces is non proper created

### ISSUE THREAD

**Issue by olmanolsztyn** [ntop/ntopng#5219]
I have 10G interfaces that detects neighbors using LLDP but topology map is not properly created related to 10G interfaces.

**Comment by olmanolsztyn** [comment]
Any news about it. LLDP Neighbors are present in interfaces but topology map i blank.

**Comment by simonemainardi** [comment]
Unfortunately I can't reproduce this issue on my lab. Do you think it is possible to arrange a remote session?

**Comment by olmanolsztyn** [comment]
Yes we can try.

**Comment by simonemainardi** [comment]
Ok. Let me gather some info first. Please, tell me the manufacturer and model of the devices for which you are not getting the LLDP topology on 10G interface.

**Comment by olmanolsztyn** [comment]
I get lldp neighbors but graphical topology map is empty (blank). As i remember graphical topology map started to be blank after you added support for 10gig interfaces.

**Comment by simonemainardi** [comment]
> Please, tell me the manufacturer and model of the devices

**Comment by simonemainardi** [comment]
also please check if related to https://github.com/ntop/ntopng/issues/5779

**Comment by olmanolsztyn** [comment]
I have juniper (MX80 and MX 480), cisco catalyst 6500 at this moment.

**Comment by simonemainardi** [comment]
all with 10G interfaces not working?

**Comment by olmanolsztyn** [comment]
I requested problems with 10g interfaces. You have made updates and 10g interfaces started to show up with lldp neighbors but graphical topology map is blank after this update.

**Comment by olmanolsztyn** [comment]
![graphical_topology](https://user-images.githubusercontent.com/22956491/130069103-61939735-84f1-4e22-b81d-09cd60ddfd2f.png)
![topology](https://user-images.githubusercontent.com/22956491/130069106-fe0a6be9-ceec-40f7-b93a-e9df6aa6841f.png)

**Comment by olmanolsztyn** [comment]
Looks like graphical topology is not created using lldp neighbors from devices.

**Comment by simonemainardi** [comment]
look for this exception in the browser console:

![image](https://user-images.githubusercontent.com/3397663/130071691-e06eaffb-c029-488d-8bd7-e618d4a178fc.png)

this may be the cause of the missing topology and is fixed. New builds are in progress. Anyway, if I remember correctly, you were still having issues with missing links at 10G.

Please tell me:
1. Are only Cisco devices exhibiting missing links?

A cause could be that Cisco only support CDP and not LLDP. Need to understand this first.

**Comment by olmanolsztyn** [comment]
Cisco i tested didnt have snmp oid related to LLDP. 
Juniper MXes after update started to show up 10g interfaces and lldp on them properly.
I have the same error. So i need to wait for fix yes?

**Comment by simonemainardi** [comment]
>  Juniper MXes after update started to show up 10g interfaces and lldp on them properly.

OK, this is good.

> I have the same error. So i need to wait for fix yes?

Yes, a couple of hours.

**Comment by olmanolsztyn** [comment]
Ok thanks for the info.
Let me know when you fix it.

**Comment by simonemainardi** [comment]
Fixed after an interaction with @olmanolsztyn which I would like to thank for the help in troubleshooting this.
