### ISSUE TITLE
JSON Parse error

### ISSUE THREAD

**Issue by lucadistefano** [ntop/ntopng#522]
Sometimes in log appears the following message:
20/Apr/2016 17:30:48 [Flow.cpp:1545] WARNING: JSON Parse error: 
20/Apr/2016 19:22:35 [Flow.cpp:1545] WARNING: JSON Parse error: ��{'�
20/Apr/2016 21:17:13 [Flow.cpp:1545] WARNING: JSON Parse error: p~8 �
20/Apr/2016 21:44:02 [Flow.cpp:1545] WARNING: JSON Parse error: ��%&�
20/Apr/2016 23:06:27 [Flow.cpp:1545] WARNING: JSON Parse error: ��!&�

data comes from nbprobe via zmq, maybe they are utf-8 chars?

**Comment by simonemainardi** [comment]
@lucadistefano can you please make sure to use the latest dev versions of both nprobe and ntopng? We have made some changes on the ZMQ compression. Please, let us know if you still experience the issue. Thank you.

**Comment by lucaderi** [comment]
We have made a few changes to ZMQ and you need to have both ntopng and nprobe in sync. I believe if you do that the problem will disappear

**Comment by lucadistefano** [comment]
the error is still present with the build of yesterday and they are not utf8 chars:

06/Jun/2016 15:28:40 [Flow.cpp:1592] WARNING: JSON Parse error: { "58500": "tcp", "5": "0", "58503": "tcp_other", "9": "0", "10": "0", "58508": "443", "13": "0", "14": "0", "15": "0.0.0.0", "16": "0", "17": "0", "29": "0", "30": "0", "32": "0", "35": "1", "36": "120", "37": "30", "52": "127", "53": "127", "55": "0", "60": "4", "95": "0", "130": "0.0.0.0", "148": "87467268", "150": "1465219689", "151": "1465219689", "152": "1465219689089", "153": "1465219689094", "239": "1", "57552": "0", "57595": "0.049000", "57596": "0.355000", "57597": "0.910000", "57570": "0", "57577": "443", "57578": "0", "57579": "1500", "57580": "40", "57599": "0", "57581": "0", "57600": "0", "57582": "0", "57583": "0", "57584": "0", "57585": "0", "57586": "", "57587": "0", "57588": "", "57589": "0", "57591": "SSL", "57592": "0", "57593": "", "57594": "", "57598": "", "57821": "", "57822": "", "57863": "4", "57864": "4", "57887": "65535", "57888": "65535", "57889": "1460", "57890": "8", "57891": "8192", "57892": "8192", "57893": "1460", "57894": "8", "42": "87467268" }
06/Jun/2016 15:37:06 [Flow.cpp:1592] WARNING: JSON Parse error: { "58500": "tcp", "5": "0", "58503": "tcp_other", "9": "0", "10": "0", "58508": "443", "13": "0", "14": "0", "15": "0.0.0.0", "16": "0", "17": "0", "29": "0", "30": "0", "32": "426", "35": "1", "36": "120", "37": "30", "52": "126", "53": "126", "55": "0", "60": "4", "95": "0", "130": "0.0.0.0", "148": "87865826", "150": "1465220195", "151": "1465220195", "152": "1465220195740", "153": "1465220195744", "239": "1", "57552": "0", "57595": "0.202000", "57596": "0.028000", "57597": "0.185000", "57570": "229", "57577": "443", "57578": "0", "57579": "283", "57580": "40", "57599": "426", "57581": "2", "57600": "229", "57582": "1", "57583": "0", "57584": "0", "57585": "0", "57586": "", "57587": "0", "57588": "", "57589": "0", "57591": "SSL", "57592": "0", "57593": "", "57594": "", "57598": "", "57821": "", "57822": "", "57863": "3", "57864": "3", "57887": "8192", "57888": "8192", "57889": "1460", "57890": "8", "57891": "8192", "57892": "8192", "57893": "1460", "57894": "8", "42": "87865826" }
06/Jun/2016 15:40:16 [Flow.cpp:1592] WARNING: JSON Parse error: { "58500": "tcp", "5": "0", "58503": "tcp_other", "9": "0", "10": "0", "58508": "443", "13": "0", "14": "0", "15": "0.0.0.0", "16": "0", "17": "0", "29": "0", "30": "0", "32": "0", "35": "1", "36": "120", "37": "30", "52": "127", "53": "127", "55": "0", "60": "4", "95": "0", "130": "0.0.0.0", "148": "88015282", "150": "1465220385", "151": "1465220385", "152": "1465220385274", "153": "1465220385282", "239": "1", "57552": "0", "57595": "0.181000", "57596": "0.295000", "57597": "0.950000", "57570": "0", "57577": "443", "57578": "0", "57579": "1500", "57580": "40", "57599": "0", "57581": "0", "57600": "0", "57582": "0", "57583": "0", "57584": "0", "57585": "0", "57586": "", "57587": "0", "57588": "", "57589": "0", "57591": "SSL", "57592": "0", "57593": "", "57594": "", "57598": "", "57821": "", "57822": "", "57863": "8", "57864": "7", "57887": "65535", "57888": "65535", "57889": "1460", "57890": "8", "57891": "8192", "57892": "8192", "57893": "1460", "57894": "8", "42": "88015282" }
06/Jun/2016 15:47:32 [Flow.cpp:1592] WARNING: JSON Parse error: { "58500": "tcp", "5": "0", "58503": "tcp_other", "9": "0", "10": "0", "58508": "443", "13": "0", "14": "0", "15": "0.0.0.0", "16": "0", "17": "0", "29": "0", "30": "0", "32": "0", "35": "1", "36": "120", "37": "30", "52": "127", "53": "127", "55": "0", "60": "4", "95": "0", "130": "0.0.0.0", "148": "88359376", "150": "1465220821", "151": "1465220821", "152": "1465220821191", "153": "1465220821196", "239": "1", "57552": "0", "57595": "0.043000", "57596": "0.423000", "57597": "0.941000", "57570": "0", "57577": "443", "57578": "0", "57579": "1500", "57580": "40", "57599": "0", "57581": "0", "57600": "0", "57582": "0", "57583": "0", "57584": "0", "57585": "0", "57586": "", "57587": "0", "57588": "", "57589": "0", "57591": "SSL", "57592": "0", "57593": "", "57594": "", "57598": "", "57821": "", "57822": "", "57863": "5", "57864": "4", "57887": "65535", "57888": "65535", "57889": "1460", "57890": "8", "57891": "8192", "57892": "8192", "57893": "1460", "57894": "8", "42": "88359376" }

**Comment by simonemainardi** [comment]
@lucadistefano I've tried to re-parse the json strings you reported but actually I don't get any Parse error. Anyway, I've added JSON parse error descriptions to the code. So next time you should also see the reason that led to the failure. Please, follow up upon any news.

**Comment by Niko78** [comment]
on my side I still have few lines like that
ntopng: [Flow.cpp:1592] WARNING: JSON Parse error: { "15": "192.168.6.241", "10": "6", "14": "2", "5": "0", "16": "0", "17": "0", "9": "24", "13": "20", "42": "46771563" }
ntopng: [Flow.cpp:1596] WARNING: JSON Parse error [quoted object property name expected]: { "15": "172.29.44.205", "10": "48", "14": "2", "5": "0", "16": "0", "17": "0", "9": "28", "13": "20", "42": "1095526" }
 ntopng: [Flow.cpp:1596] WARNING: JSON Parse error [object value separator ',' expected]: { "15": "62.160.204.102", "10": "5", "14": "7", "5": "0", "16": "2200", "17": "0", "9": "0", "13": "27", "42": "1073432" }
ntopng: [Flow.cpp:1596] WARNING: JSON Parse error [quoted object property name expected]: { "15": "192.168.130.211", "10": "2", "14": "1", "5": "0", "16": "0", "17": "8075", "9": "24", "13": "0", "42": "16117369" }

ntopng v.2.3.160609 [Professional Edition]

Nico

**Comment by simonemainardi** [comment]
I'm getting a big headache: `Flow.cpp:1596` parses a string into a JSON object and raises the errors. 

However, the string parsed was a former json object converted into string by `json_object_to_json_string` at `NetworkInterface.cpp:633`. How is it possible that json-c first converts json to a string and then it is not able to parse that string?

**Comment by lucadistefano** [comment]
here my errors with the cause:
13/Jun/2016 10:00:21 [Flow.cpp:1596] WARNING: JSON Parse error [object value separator ',' expected]: { "58500": "tcp", "5": "0", "58503": "tcp_other", "9": "0", "10": "0", "58508": "443", "13": "0", "14": "0", "15": "0.0.0.0", "16": "0", "17": "0", "32": "0", "52": "127", "53": "127", "55": "0", "60": "4", "95": "0", "130": "0.0.0.0", "148": "54609731", "150": "1465804790", "151": "1465804790", "152": "1465804790545", "153": "1465804790556", "239": "1", "57552": "0", "57595": "0.165000", "57596": "0.300000", "57597": "2.206000", "57570": "0", "57577": "443", "57578": "0", "57579": "1500", "57580": "40", "57599": "0", "57581": "0", "57600": "0", "57582": "0", "57583": "0", "57584": "0", "57585": "0", "57586": "", "57587": "0", "57588": "", "57589": "0", "57592": "0", "57593": "", "57598": "", "57821": "", "57822": "", "57863": "11", "57864": "10", "57887": "65535", "57888": "65535", "57889": "1460", "57890": "8", "57891": "8192", "57892": "8192", "57893": "1460", "57894": "8", "42": "54609731" }
13/Jun/2016 10:02:43 [Flow.cpp:1596] WARNING: JSON Parse error [object value separator ',' expected]: { "58500": "tcp", "5": "0", "58503": "tcp_other", "9": "0", "10": "0", "58508": "443", "13": "0", "14": "0", "15": "0.0.0.0", "16": "0", "17": "0", "32": "0", "52": "127", "53": "127", "55": "0", "60": "4", "95": "0", "130": "0.0.0.0", "148": "54747382", "150": "1465804919", "151": "1465804919", "152": "1465804919304", "153": "1465804919316", "239": "1", "57552": "0", "57595": "0.551000", "57596": "0.506000", "57597": "0.850000", "57570": "0", "57577": "443", "57578": "0", "57579": "283", "57580": "40", "57599": "0", "57581": "0", "57600": "0", "57582": "0", "57583": "0", "57584": "0", "57585": "0", "57586": "", "57587": "0", "57588": "", "57589": "0", "57592": "0", "57593": "", "57598": "", "57821": "", "57822": "", "57863": "11", "57864": "10", "57887": "8192", "57888": "8192", "57889": "1460", "57890": "8", "57891": "8192", "57892": "8192", "57893": "1460", "57894": "8", "42": "54747382" }
13/Jun/2016 10:08:35 [Flow.cpp:1596] WARNING: JSON Parse error [quoted object property name expected]: { "58500": "tcp", "5": "0", "58503": "tcp_other", "9": "0", "10": "0", "58508": "443", "13": "0", "14": "0", "15": "0.0.0.0", "16": "0", "17": "0", "32": "0", "52": "127", "53": "127", "55": "0", "60": "4", "95": "0", "130": "0.0.0.0", "148": "55113231", "150": "1465805243", "151": "1465805243", "152": "1465805243535", "153": "1465805243542", "239": "1", "57552": "0", "57595": "0.127000", "57596": "0.422000", "57597": "1.349000", "57570": "0", "57577": "443", "57578": "0", "57579": "1500", "57580": "40", "57599": "0", "57581": "0", "57600": "0", "57582": "0", "57583": "0", "57584": "0", "57585": "0", "57586": "", "57587": "0", "57588": "", "57589": "0", "57592": "0", "57593": "", "57598": "", "57821": "", "57822": "", "57863": "6", "57864": "6", "57887": "65535", "57888": "65535", "57889": "1460", "57890": "8", "57891": "8192", "57892": "8192", "57893": "1460", "57894": "8", "42": "55113231" }
13/Jun/2016 11:23:19 [Flow.cpp:1596] WARNING: JSON Parse error [object value separator ',' expected]: { "58500": "tcp", "5": "0", "58503": "tcp_other", "9": "0", "10": "0", "58508": "443", "13": "0", "14": "0", "15": "0.0.0.0", "16": "0", "17": "0", "32": "0", "52": "127", "53": "127", "55": "0", "60": "4", "95": "0", "130": "0.0.0.0", "148": "59833233", "150": "1465809676", "151": "1465809676", "152": "1465809676655", "153": "1465809676665", "239": "1", "57552": "0", "57595": "0.132000", "57596": "0.492000", "57597": "1.883000", "57570": "0", "57577": "443", "57578": "0", "57579": "1500", "57580": "40", "57599": "0", "57581": "0", "57600": "0", "57582": "0", "57583": "0", "57584": "0", "57585": "0", "57586": "", "57587": "0", "57588": "", "57589": "0", "57592": "0", "57593": "", "57598": "", "57821": "", "57822": "", "57863": "9", "57864": "9", "57887": "65535", "57888": "65535", "57889": "1460", "57890": "8", "57891": "8192", "57892": "8192", "57893": "1460", "57894": "8", "42": "59833233" }
13/Jun/2016 12:04:39 [Flow.cpp:1596] WARNING: JSON Parse error [quoted object property name expected]: { "58500": "tcp", "5": "0", "58503": "tcp_other", "9": "0", "10": "0", "58508": "443", "13": "0", "14": "0", "15": "0.0.0.0", "16": "0", "17": "0", "32": "0", "52": "127", "53": "127", "55": "0", "60": "4", "95": "0", "130": "0.0.0.0", "148": "62445699", "150": "1465812085", "151": "1465812085", "152": "1465812085835", "153": "1465812085841", "239": "1", "57552": "0", "57595": "0.358000", "57596": "0.513000", "57597": "0.875000", "57570": "0", "57577": "443", "57578": "0", "57579": "1500", "57580": "40", "57599": "0", "57581": "0", "57600": "0", "57582": "0", "57583": "0", "57584": "0", "57585": "0", "57586": "", "57587": "0", "57588": "", "57589": "0", "57592": "0", "57593": "", "57598": "", "57821": "", "57822": "", "57863": "5", "57864": "5", "57887": "65535", "57888": "65535", "57889": "1460", "57890": "8", "57891": "8192", "57892": "8192", "57893": "1460", "57894": "8", "42": "62445699" }
13/Jun/2016 12:50:20 [Flow.cpp:1596] WARNING: JSON Parse error [object value separator ',' expected]: { "58500": "tcp", "5": "0", "58503": "tcp_other", "9": "0", "10": "0", "58508": "443", "13": "0", "14": "0", "15": "0.0.0.0", "16": "0", "17": "0", "32": "0", "52": "127", "53": "127", "55": "0", "60": "4", "95": "0", "130": "0.0.0.0", "148": "65360946", "150": "1465814695", "151": "1465814695", "152": "1465814695023", "153": "1465814695033", "239": "1", "57552": "0", "57595": "0.077000", "57596": "0.377000", "57597": "1.336000", "57570": "0", "57577": "443", "57578": "0", "57579": "1500", "57580": "40", "57599": "0", "57581": "0", "57600": "0", "57582": "0", "57583": "0", "57584": "0", "57585": "0", "57586": "", "57587": "0", "57588": "", "57589": "0", "57592": "0", "57593": "", "57598": "", "57821": "", "57822": "", "57863": "8", "57864": "9", "57887": "65535", "57888": "65535", "57889": "1460", "57890": "8", "57891": "8192", "57892": "8192", "57893": "1460", "57894": "8", "42": "65360946" }

**Comment by lucaderi** [comment]
@Niko78 @lucadistefano Please refresh the code from github and report if it works now

**Comment by Niko78** [comment]
I upgraded with lasr build yesterday morning (v.2.3.160614)
seems to be fixed but now I have new error which I never got before

Jun 15 01:00:02 ntop-racine ntopng: [MySQLDB.cpp:593] ERROR: MySQL error: [MySQL server has gone away][2006]
...
Jun 15 01:17:44 ntop-racine ntopng: [MySQLDB.cpp:50] ERROR: MySQL error: Lock wait timeout exceeded; try restarting transaction

mysql is still UP and running

**Comment by simonemainardi** [comment]
Restart MySQL and ntopng

On Wednesday, 15 June 2016, Niko78 notifications@github.com wrote:

> I upgraded with lasr build yesterday morning
> seemsto be fixed but now I have new error which I never got before
> 
> Jun 15 01:00:02 ntop-racine ntopng: [MySQLDB.cpp:593] ERROR: MySQL error:
> [MySQL server has gone away][2006]
> ...
> Jun 15 01:17:44 ntop-racine ntopng: [MySQLDB.cpp:50] ERROR: MySQL error:
> Lock wait timeout exceeded; try restarting transaction
> 
> mysql is still UP and running
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/ntop/ntopng/issues/522#issuecomment-226112750, or mute
> the thread
> https://github.com/notifications/unsubscribe/ADPYHzAkgaKE1VcczDCcyVZnrFsPGioVks5qL61zgaJpZM4IMfaN
> .

## 

Sent from my iPad. Sorry for typos.

**Comment by lucadistefano** [comment]
I can confirm the errors are disappeared after the update
