### ISSUE TITLE
New Alerts Explorer - SNMP Alerts page JS failure

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#5220]
There is a jquery failure in the new SNMP alerts page (the endpoint seems to be called correctly).

<img width="998" alt="Screen Shot 2021-04-23 at 17 55 07" src="https://user-images.githubusercontent.com/7548711/115897753-0c49a980-a45d-11eb-9d42-80ac67113a06.png">

**Comment by gabryon99** [comment]
Verified as fixed.
