### ISSUE TITLE
ntopng 4.2 crashes as soon as I enable timeseries to influxdb

### ISSUE THREAD

**Issue by lemmy04** [ntop/ntopng#5223]
I have an influxdb up and running that I feed with telegraf from a dozen pcs. As soon as I switch the timeseries driver to influxdb and point it at my database, ntopng crashes. If i restart it, it crashes again, the only way to get it to work again is to delete the redi key that stores the timeseries driver...

**Comment by MatteoBiscosi** [comment]
Hi @lemmy04 , sorry but I'm unable to reproduce the bug, could you please tell me your ntopng version and if you have some errors (you can check the errors by doing `service ntopng status`)?

**Comment by lemmy04** [comment]
I am running ntopng 4.2 built as RPM for openSUSE from the tar file on https://github.com/ntop/ntopng/releases/tag/4.2, the spec file used to package it is here: https://build.opensuse.org/package/show/server:monitoring/ntopng

I didn't see any errors in my logs - and I actually got it to work now, by setting the database as the IP address instead of hostname. My guess is that ntopng can't deal with IPv6 at this point, the hostname of my grafana server resolves to IPv4 and v6...

**Comment by simonemainardi** [comment]
OpenSUSE is not a distribution we support.

Anyway, checkout the latest sources from https://github.com/ntop/ntopng/tree/4.2-stable and retry.

In case you still experience the crash, consider switching to a supported distribution or provide a stack trace we can use to debug.
