### ISSUE TITLE
New Alerts Explorer - Add tabs for new alert endpoints

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#5224]
New endpoints have been added for "interface", "network" and "user". It is required to add a tab for each of them in the alerts page.

**Comment by gabryon99** [comment]
I've added the new links inside the navbar and added the necessary templates, but there are few problems with the new endpoints.

### Interface Endpoint

For the `list.lua` endpoint I receive this error:
<img width="1562" alt="Screenshot 2021-04-24 at 09 57 00" src="https://user-images.githubusercontent.com/14114916/115951896-6c832e80-a4e3-11eb-9f71-d877064acb5e.png">

### User Endpoint

The same error goes with the `user` endpoint ...
<img width="1562" alt="Screenshot 2021-04-24 at 10 00 08" src="https://user-images.githubusercontent.com/14114916/115951961-dbf91e00-a4e3-11eb-8df5-4e4049b744c6.png">

### Network Endpoint

... and with the `network` endpoint:
<img width="1562" alt="Screenshot 2021-04-24 at 10 01 44" src="https://user-images.githubusercontent.com/14114916/115952010-1662bb00-a4e4-11eb-96de-e8469b3c14fd.png">

---

Am I missing something? I tried to recompile the source code as well.

**Comment by gabryon99** [comment]
> I've added the new links inside the navbar and added the necessary templates, but there are few problems with the new endpoints.
> 
> ### Interface Endpoint
> For the `list.lua` endpoint I receive this error:
> <img alt="Screenshot 2021-04-24 at 09 57 00" width="1562" src="https://user-images.githubusercontent.com/14114916/115951896-6c832e80-a4e3-11eb-9f71-d877064acb5e.png">
> 
> ### User Endpoint
> The same error goes with the `user` endpoint ...
> <img alt="Screenshot 2021-04-24 at 10 00 08" width="1562" src="https://user-images.githubusercontent.com/14114916/115951961-dbf91e00-a4e3-11eb-8df5-4e4049b744c6.png">
> 
> ### Network Endpoint
> ... and with the `network` endpoint:
> <img alt="Screenshot 2021-04-24 at 10 01 44" width="1562" src="https://user-images.githubusercontent.com/14114916/115952010-1662bb00-a4e4-11eb-96de-e8469b3c14fd.png">
> 
> Am I missing something? I tried to recompile the source code as well.

### System Endpoint

Also, the `system` endpoint has the same problem:

<img width="1579" alt="Screenshot 2021-04-24 at 10 28 45" src="https://user-images.githubusercontent.com/14114916/115952708-dac9f000-a4e7-11eb-9d84-9c2612823239.png">

**Comment by cardigliano** [comment]
The alert_entity related failure has been addressed in 81ed0f7e9d4c2b827756f11cf157c2f9cd617476.
@simonemainardi please review the current value in system_alert_store

**Comment by simonemainardi** [comment]
@cardigliano everything reviewed. Some alert entities merged into system - see referenced commits.

@gabryon99 let us know if everything is OK.

**Comment by gabryon99** [comment]
Fixed and implemented.
