### ISSUE TITLE
ntopng.conf --collection-filter

### ISSUE THREAD

**Issue by netsolv** [ntop/ntopng#5225]
It appears ntopng.service is no longer applying the --collection-filter=!xxx.xxx.xxx.xxx/xx portion of the .conf file. nprobe -h | grep -- --collection-filter still shows the variable is correct, however we are seeing an abundant of traffic from a probe server via broadcast. We need to remove 2 specific hosts from all data collection.

**Comment by simonemainardi** [comment]
this is an nprobe option, please apply to nprobe. ntopng supports -B for BPF filters on packet-interfaces.
