### ISSUE TITLE
error when releasing an alert

### ISSUE THREAD

**Issue by rreiner** [ntop/ntopng#5227]
When releasing an alert of type "Flow Anomaly", a screen full of raw HTTP headers is displayed in the GUI, ending with the error message ` alerts_api.lua:472: attempt to index a nil value (global 'host')`

Screenshots attached.

![image](https://user-images.githubusercontent.com/12399329/115964433-80825c80-a4f2-11eb-95d6-ef93d766798c.png)

Then after clicking Release icon on the second flow and confirming:

![image](https://user-images.githubusercontent.com/12399329/115964448-9001a580-a4f2-11eb-90e0-6b5aaff8e221.png)

Other flows do not behave this way.,

$ ntopng --version
Version:        4.3.210424 [Enterprise/Professional/Embedded build]
GIT rev:        dev:89d5d64c5ed32443086f8f385c4aa6413062d072:20210424
Pro rev:        r3737
Built on:       Raspbian GNU/Linux 10 (buster)
System Id:      130FA343499602D2
Platform:       armv7l
Edition:        Enterprise Embedded
License Type:   Time-Limited [Empty license file]
Validity:       Until Sat Apr 24 11:54:12 2021

**Comment by simonemainardi** [comment]
This functionality is being reworked and will be merged into dev shortly. Thanks for reporting.

**Comment by cardigliano** [comment]
The new UI is now available, this no longer applies as the Release button has been removed/replaced with the disable functionality.
