### ISSUE TITLE
New Alerts Explorer - Update Links

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5228]
The following links should be updated:

1. Alerts page under host_details should point to the new alerts page, tab "host", with the host IP selected. NOTE that the selection must support VLAN, when it is not zero. Filters will look like 1.2.3.4 for hosts without VLAN, and 1.2.3.4@XX for any VLAN XX > 0.
2. Alerts page under if_stats should point to the new alerts page, tab "interface". In this case, there's no need to preset a filter as we are already under the interface page.
3. Alerts page under local network, should point to the new alerts page, tab "networks", with the network id already set as filter.

**Comment by gabryon99** [comment]
Links updated.
