### ISSUE TITLE
Local VLans showing up as remote traffic.

### ISSUE THREAD

**Issue by Artapel** [ntop/ntopng#523]
Hi Guys

My Local Vlan`s are showing up as remote traffic.

Any idea as to why this is.
To recreate the issue, just have your Ntop machine between your router a n layer 3 switch with multiple vlans.

Ntop details are as follows.
n2disk.x86_64 0:2.5.160421-4617  
nbox.noarch 0:2.3.0-487  
nprobe.x86_64 0:7.3.160421-5044
ntopng.x86_64 0:2.3.160421-1100  
ntopng-data.noarch 0:2.3.160421-1100   

Linux CentOS 7.2
3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Regards
Corne

**Comment by simonemainardi** [comment]
not sure what you mean with local VLANs. With ntopng you can define local networks, not local VLANs. Please explain.

**Comment by Artapel** [comment]
Thats correct. Its a local network. Where do i set that?

Regards
[Corne Kruger]

**Comment by Artapel** [comment]
Here is my config file btw

-G=/var/tmp/ntopng.pid
-q=
-F mysql;localhost;ntopng;flows;ntopng;
--verbose
--disable-autologout
--dns-mode 1
--local-networks -m "192.168.0.0/24,192.168.1.0/24,192.168.6.0/24,192.168.62.0/24,192.168.63.0/24,192.168.66.0/24,192.168.65.0/24,192.168.62.0/24,192.168.60.0/24,192.168.21.0/24,192.168.13.0/24,192.168.4.0/24,192.168.5.0/24,192.168.1.0/24,192.168.66.0/24,172.18.0.0/24,192.168.19.0/24,192.168.70.0/24,192.168.80.0/24,192.168.55.0/24,192.168.62.0/24,192.168.75.0/24,192.168.30.0/24,192.168.10.0/24"

Regards
[Corne Kruger]

**Comment by simonemainardi** [comment]
you config file line is wrong, you have to use the = sign and not twice `--local-networks` and `-m` on the same line:

```
--local-networks="192.168.0.0/24,192.168.1.0/24" 
```

If you had looked at the ntopng log you would have found it.

**Comment by Artapel** [comment]
Not all the Vlans are showing up as expected

Any ideas why?

[cid:image001.png@01D19C88.D58F7910]

Regards
[Corne Kruger]

**Comment by simonemainardi** [comment]
too generic. give exact configuration used and what you think it is not showing up. Include screenshots as well if you think this can help.

**Comment by Artapel** [comment]
Here is my exact config

vim /etc/ntopng/ntopng.conf
-G=/var/tmp/ntopng.pid
-q=
-F mysql;localhost;ntopng;flows;ntopng;
--verbose
--disable-autologout
--dns-mode 1
-m=192.168.0.0/24,192.168.1.0/24,192.168.6.0/24,192.168.62.0/24,192.168.63.0/24,192.168.66.0/24,192.168.65.0/24,192.168.62.0/24,192.168.60.0/24,192.168.21.0/24,192.168.13.0/24,192.168.4.0/24,192.168.5.0/24,192.168.1.0/24,192.168.66.0/24,172.18.0.0/24,192.168.19.0/24,192.168.70.0/24,192.168.80.0/24,192.168.55.0/24,192.168.62.0/24,192.168.75.0/24,192.168.30.0/24,192.168.10.0/24,196.29.140.222/24

I am expecting the following Vlans

0,1,2,13,65,70,55,66

I can see the network here when i click on the “hosts>networks” But not under Vlans

[cid:image003.png@01D19C8A.14CF87E0]

Regards
[Corne Kruger]

**Comment by simonemainardi** [comment]
a VLAN shows up only where there's some traffic tagged with it
