### ISSUE TITLE
Alert: too much space wasted

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5230]
![1](https://user-images.githubusercontent.com/4493366/116193901-60d87780-a730-11eb-99b5-b3e7bf9c3b89.png)
The above picture shows how the page renders on my laptop. A lot of space wasted, only two alerts that instead are the core of this page.

You can string the picture using something like
![image001](https://user-images.githubusercontent.com/4493366/116194024-8cf3f880-a730-11eb-9d00-42a485c30e4e.png)
and try to save other space to fit data in page

**Comment by cardigliano** [comment]
The page layout has been reworked, a new chart is used now
