### ISSUE TITLE
Alert: Invalid formatting

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5231]
![2](https://user-images.githubusercontent.com/4493366/116194101-a8f79a00-a730-11eb-8754-e49198797418.png)

As you can see on this picture you waste a lot of space. Suggestions
- merge client and client name in a single column
- severity should be much shorter
- Description should not wrap
- String labels such as Application
- Missing L4 protocol

**Comment by simonemainardi** [comment]
All the items in the bullet list have been addressed. We now have to better manage the layout and space used but there are separate issues for this.
