### ISSUE TITLE
Alert: Missing Hyperlinks

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5232]
![3](https://user-images.githubusercontent.com/4493366/116194253-e5c39100-a730-11eb-9611-e3119f240427.png)
With the new table it is no loner available a hyperlink to jump to the host page (if present) but only to stay on alerts (correct). Please add an icon or something along that line to enable jumping to the host page as in the old alert page

**Comment by simonemainardi** [comment]
@gabryon99 as requested you now have extra fields telling you the url:

- For flow alerts: check for `cli_url` and `srv_url` in the response
- For host alerts: check for `ip_url` in the response

URLs are populated for active hosts, otherwise they are just plain strings when hosts are inactive.
