### ISSUE TITLE
Alert Drill down icons do not execute any action

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5236]
![Screen Shot 2021-04-27 at 12 00 06](https://user-images.githubusercontent.com/4493366/116223750-254da580-a750-11eb-80f6-198d17ff382c.png)

Example URL http:/xxxx:3000/lua/alert_stats.lua?begin_epoch=1619516455&end_epoch=1619516699

**Comment by MatteoBiscosi** [comment]
Verified as fixed, please reopen if needed
