### ISSUE TITLE
Alert: Add badge when there are engaged alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5239]
![Screen Shot 2021-04-27 at 12 02 18](https://user-images.githubusercontent.com/4493366/116224041-752c6c80-a750-11eb-9410-a8ca490aa3e3.png)

In the upper menubar, add a red badge similar to the picture below
![Screen Shot 2021-04-27 at 10 57 10](https://user-images.githubusercontent.com/4493366/116230748-5205bb00-a758-11eb-8ec5-4f6ca1cbb8d9.png)
for those entries that have engaged alerts

**Comment by simonemainardi** [comment]
Implemented 

![image](https://user-images.githubusercontent.com/3397663/117627214-3814a100-b178-11eb-9106-a98d189b082c.png)
