### ISSUE TITLE
remove template list limitation

### ISSUE THREAD

**Issue by lucadistefano** [ntop/ntopng#524]
in nprobe you can configure a limited number of template fields:
1) the limitation of line length in conf file (usually 2048 chars)
2) the size of packet that carries the value

using zmq (so going beyond the netflow protocol limitation) it would be nice to be able to enable how many fields are needed.
one probe can handle mysql, sip rtp , dns traffic and if you try to enable it all (plus the standard ones) you reach the limitation

**Comment by simonemainardi** [comment]
please give an example and a use case

**Comment by lucadistefano** [comment]
try to put this template in the nprobe configuration file on a linux machine:
-T=%IN_BYTES %IN_PKTS %PROTOCOL %PROTOCOL_MAP %SRC_TOS %TCP_FLAGS %L4_SRC_PORT %L4_SRC_PORT_MAP %IPV4_SRC_ADDR %IPV4_SRC_MASK %INPUT_SNMP %L4_DST_PORT %L4_DST_PORT_MAP %L4_SRV_PORT %L4_SRV_PORT_MAP %IPV4_DST_ADDR %IPV4_DST_MASK %OUTPUT_SNMP %IPV4_NEXT_HOP %SRC_AS %DST_AS %LAST_SWITCHED %FIRST_SWITCHED %OUT_BYTES %OUT_PKTS %IPV6_SRC_ADDR %IPV6_DST_ADDR %IPV6_SRC_MASK %IPV6_DST_MASK %ICMP_TYPE %SAMPLING_INTERVAL %SAMPLING_ALGORITHM %FLOW_ACTIVE_TIMEOUT %FLOW_INACTIVE_TIMEOUT %ENGINE_TYPE %ENGINE_ID %MIN_TTL %MAX_TTL %DST_TOS %IN_SRC_MAC %SRC_VLAN %DST_VLAN %IP_PROTOCOL_VERSION %DIRECTION %IPV6_NEXT_HOP %MPLS_LABEL_1 %MPLS_LABEL_2 %OUT_DST_MAC %APPLICATION_ID %EXPORTER_IPV4_ADDRESS %EXPORTER_IPV6_ADDRESS %FLOW_ID %FLOW_START_SEC %FLOW_END_SEC %FLOW_START_MILLISECONDS %FLOW_END_MILLISECONDS %BIFLOW_DIRECTION %FRAME_LENGTH %APPLICATION_NAME %USER_NAME %FRAGMENTS %CLIENT_NW_LATENCY_MS %SERVER_NW_LATENCY_MS %APPL_LATENCY_MS %CUMULATIVE_ICMP_TYPE %SRC_IP_COUNTRY %SRC_IP_CITY %DST_IP_COUNTRY %DST_IP_CITY %FLOW_PROTO_PORT %UPSTREAM_TUNNEL_ID %LONGEST_FLOW_PKT %SHORTEST_FLOW_PKT %RETRANSMITTED_IN_BYTES %RETRANSMITTED_IN_PKTS %RETRANSMITTED_OUT_BYTES %RETRANSMITTED_OUT_PKTS %OOORDER_IN_PKTS %OOORDER_OUT_PKTS %UNTUNNELED_PROTOCOL %UNTUNNELED_IPV4_SRC_ADDR %UNTUNNELED_L4_SRC_PORT %UNTUNNELED_IPV4_DST_ADDR %UNTUNNELED_L4_DST_PORT %L7_PROTO %L7_PROTO_NAME %DOWNSTREAM_TUNNEL_ID %FLOW_USER_NAME %FLOW_SERVER_NAME %UNTUNNELED_IPV6_SRC_ADDR %UNTUNNELED_IPV6_DST_ADDR %SRC_IP_LONG %SRC_IP_LAT %DST_IP_LONG %DST_IP_LAT %IN_SRC_OSI_SAP %OUT_DST_OSI_SAP %DURATION_IN %DURATION_OUT %TCP_WIN_MIN_IN %TCP_WIN_MAX_IN %TCP_WIN_MSS_IN %TCP_WIN_SCALE_IN %TCP_WIN_MIN_OUT %TCP_WIN_MAX_OUT %TCP_WIN_MSS_OUT %TCP_WIN_SCALE_OUT %PAYLOAD_HASH %SRC_AS_MAP %DST_AS_MAP %DNS_QUERY %DNS_QUERY_ID %DNS_QUERY_TYPE %DNS_RET_CODE %DNS_TTL_ANSWER %DNS_RESPONSE %HTTP_URL %HTTP_METHOD %HTTP_RET_CODE %HTTP_REFERER %HTTP_UA %HTTP_MIME %HTTP_HOST %HTTP_SITE %DHCP_CLIENT_MAC %DHCP_CLIENT_IP %DHCP_CLIENT_NAME %DHCP_REMOTE_ID %DHCP_SUBSCRIBER_ID %DHCP_MESSAGE_TYPE %RTP_FIRST_SEQ %RTP_FIRST_TS %RTP_LAST_SEQ %RTP_LAST_TS %RTP_IN_JITTER %RTP_OUT_JITTER %RTP_IN_PKT_LOST %RTP_OUT_PKT_LOST %RTP_IN_PKT_DROP %RTP_OUT_PKT_DROP %RTP_IN_PAYLOAD_TYPE %RTP_OUT_PAYLOAD_TYPE %RTP_IN_MAX_DELTA %RTP_OUT_MAX_DELTA %RTP_SIP_CALL_ID %RTP_MOS %RTP_IN_MOS %RTP_OUT_MOS %RTP_R_FACTOR %RTP_IN_R_FACTOR %RTP_OUT_R_FACTOR %RTP_IN_TRANSIT %RTP_OUT_TRANSIT %RTP_RTT %RTP_DTMF_TONES %SIP_CALLING_PARTY %SIP_CALLED_PARTY %SIP_RTP_CODECS %SIP_INVITE_TIME %SIP_TRYING_TIME %SIP_RINGING_TIME %SIP_INVITE_OK_TIME %SIP_INVITE_FAILURE_TIME %SIP_BYE_TIME %SIP_BYE_OK_TIME %SIP_CANCEL_TIME %SIP_CANCEL_OK_TIME %SIP_RTP_IPV4_SRC_ADDR %SIP_RTP_L4_SRC_PORT %SIP_RTP_IPV4_DST_ADDR %SIP_RTP_L4_DST_PORT %SIP_RESPONSE_CODE %SIP_REASON_CAUSE %SIP_C_IP %SIP_CALL_STATE %NETBIOS_QUERY_NAME %NETBIOS_QUERY_TYPE %NETBIOS_QUERY_RSP %ORACLE_USERNAME %ORACLE_QUERY %ORACLE_RSP_CODE %ORACLE_RSP_STRING %ORACLE_QUERY_DURATION 

when you start nprobe you can check that the template will be truncated

**Comment by simonemainardi** [comment]
this is an nProbe limitation, you should refer to: https://github.com/ntop/nProbe/issues
