### ISSUE TITLE
Alerts: Column size in uneven

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5242]
![Screenshot 2021-04-28 at 08 34 19](https://user-images.githubusercontent.com/4493366/116357746-1ffa6480-a7fd-11eb-8124-49358b67df5c.png)

Action column is too wide, problem already discussed in  #5232

**Comment by cardigliano** [comment]
Currently columns can change in the same page navigating alerts through pagination, as they are moved to the "+" (expanded information) according to the content. Please see the pictures. This IMHO should be avoided as it is confusing for the user.

<img width="1025" alt="Screen Shot 2021-04-29 at 12 59 16" src="https://user-images.githubusercontent.com/7548711/116540884-0a636880-a8eb-11eb-802f-1fc9060d3968.png">
<img width="1018" alt="Screen Shot 2021-04-29 at 12 59 07" src="https://user-images.githubusercontent.com/7548711/116540888-0b949580-a8eb-11eb-9835-039350a9e271.png">

**Comment by lucaderi** [comment]
The initial issue is solved for me. Now this new one from @cardigliano needs to be handled (I would open a separate ticket)
