### ISSUE TITLE
Alerts: Do not enable breadcrumb hyperlink for entries with no alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5245]
Example:
![Screenshot 2021-04-28 at 08 55 37](https://user-images.githubusercontent.com/4493366/116359832-8da79000-a7ff-11eb-9514-b280878bb689.png)

Note that when #5239 will be implemented and this ticket will also be implemented, refresh needs to update the breadcrumb in case new alerts have been reported in the meantime and thus the menu link need to be enabled

**Comment by simonemainardi** [comment]
Ticket is implemented. Now:

- Breadcrumb links are enabled to always allow historical alerts access
- When engaged alerts are present, badges are shown on top of the breadcrumb items (#5239)

Example

![image](https://user-images.githubusercontent.com/3397663/120291057-35165780-c2c3-11eb-9cd5-a5cd915d0577.png)

Dynamically refreshing breadcrumb counters is left for the future as it creates a series of side effects not easily manageable with the current template structure:

- All the breadcrumbs with badges need to be updated, e.g., 
![image](https://user-images.githubusercontent.com/3397663/120291407-90e0e080-c2c3-11eb-8939-a66eee21b2cd.png)
- Updating breadcrumbs requires AJAX and JS stricly coupled with the template structure
