### ISSUE TITLE
Implement alert dashboard

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5246]
In the current alert implementation, a bird eye view of the current alert status is missing. This needs to be implemented as landing page. Something like (or better) this below is the bare minimum we can expect. Better if some charts are used.

![Screenshot 2021-04-28 at 09 01 25](https://user-images.githubusercontent.com/4493366/116360588-600f1680-a800-11eb-8614-bed1e3555cb9.png)

**Comment by cardigliano** [comment]
An "All" landing page has been implemented. This is also looks like a duplicate of https://github.com/ntop/ntopng/issues/5291
