### ISSUE TITLE
Alert breadcrumb needs to be reworked 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5247]
In all the ntopng entries such as the host
![Screenshot 2021-04-28 at 09 03 54](https://user-images.githubusercontent.com/4493366/116360910-b2e8ce00-a800-11eb-8ab1-4d21c019748e.png)

it is clean what is the title, and what are the entries. In the alerts, the first entry (Alerts) it is not clear if it is a disabled hyperlink, a bug or the title. Adding an icon to implement #5246 or a"Alert:" can help

![Screenshot 2021-04-28 at 09 03 45](https://user-images.githubusercontent.com/4493366/116360913-b3816480-a800-11eb-99b9-cdb02051a039.png)

**Comment by gabryon99** [comment]
<img width="1698" alt="Screenshot 2021-04-28 at 12 19 26" src="https://user-images.githubusercontent.com/14114916/116388309-fb61b500-a81b-11eb-89a4-3cbd807b0845.png">

Added a small icon to the left and a separator, similar to the User Script's navbar.

**Comment by simonemainardi** [comment]
Please, maintain the same style across all the UI. See the breadcrumb attached in this issue. It has icons on the right, and no separator. Kindly unify the style across all the breadcrumbs.

**Comment by simonemainardi** [comment]
also, alerts use the `fa-triangle` as icon

**Comment by gabryon99** [comment]
@simonemainardi now the navbar use the main section's icon if it's available. The navbar is a template, so the style is unified across the pages.

**Comment by lucaderi** [comment]
Verified as fixed.
