### ISSUE TITLE
Nil values in Past Host Alerts

### ISSUE THREAD

**Issue by gabryon99** [ntop/ntopng#5248]
<img width="1698" alt="Screenshot 2021-04-28 at 12 40 48" src="https://user-images.githubusercontent.com/14114916/116391040-f8b48f00-a81e-11eb-8c95-3268925c8259.png">

**Comment by cardigliano** [comment]
This seems to be working for me

**Comment by simonemainardi** [comment]
Ffor me too, seems more an issue with an old database or schema. Closing for now. @gabryon99 please wipe the old database as we have seen.
