### ISSUE TITLE
Error in updating

### ISSUE THREAD

**Issue by kfra71** [ntop/ntopng#5249]
is there anyone that is getting this dependency error?

Any idea on how to solve it?  Already did yum clean all

Resolving Dependencies
--> Running transaction check
---> Package cento.x86_64 0:1.13.210426-667 will be updated
---> Package cento.x86_64 0:1.13.210428-667 will be an update
---> Package n2disk.x86_64 0:3.7.210426-5310 will be updated
---> Package n2disk.x86_64 0:3.7.210428-5310 will be an update
---> Package ndpi.x86_64 0:3.5.0-3145 will be updated
--> Processing Dependency: ndpi = 3.5.0-3145 for package: pfring-7.9.0-3406.x86_64
---> Package ndpi.x86_64 0:3.5.0-3150 will be an update
---> Package nprobe.x86_64 0:9.5.210426-7248 will be updated
---> Package nprobe.x86_64 0:9.5.210428-7250 will be an update
---> Package ntopng.x86_64 0:4.3.210428-13294 will be updated
---> Package ntopng.x86_64 0:4.3.210428-13301 will be an update
---> Package ntopng-data.noarch 0:4.3.210426-13262 will be updated
---> Package ntopng-data.noarch 0:4.3.210428-13301 will be an update
--> Finished Dependency Resolution
Error: Package: pfring-7.9.0-3406.x86_64 (@ntop)
           Requires: ndpi = 3.5.0-3145
           Removing: ndpi-3.5.0-3145.x86_64 (@ntop)
               ndpi = 3.5.0-3145
           Updated By: ndpi-3.5.0-3150.x86_64 (ntop)
               ndpi = 3.5.0-3150
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by cardigliano** [comment]
@kfra71 what OS are you running? Could you try with another clean all and update as we rebuilt the repo in the meantime? Thank you.

**Comment by kfra71** [comment]
I did yum clean all few seconds ago and nothing changed.

I am using CentOS Linux release 7.9.2009 (Core).

**Comment by cardigliano** [comment]
Sorry for the delay, it took some time to rebuild the OSX package. Please check the new package available at https://packages.ntop.org . Thank you.

**Comment by cardigliano** [comment]
@kfra71 I pushed a new package, please try updating again and let me know. Thank you.

**Comment by kfra71** [comment]
Now it works like a charm!
