### ISSUE TITLE
nIndex Drilldown - Clicking download on nIndex - JS errors

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5253]
![image](https://user-images.githubusercontent.com/3397663/116536196-ea30ab00-a8e4-11eb-879c-03ddcd2bfeb7.png)

![image](https://user-images.githubusercontent.com/3397663/116536173-e3a23380-a8e4-11eb-98dd-2e4ecf2765c8.png)

**Comment by MatteoBiscosi** [comment]
The issue is fixed, please reopen the ticket if needed
