### ISSUE TITLE
Alert: Invalid score/alert calculation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5255]
![Screen_Shot_2021-04-29_at_14_09_33](https://user-images.githubusercontent.com/4493366/116548547-ad6cb000-a8f4-11eb-92c4-056ec2d979bf.png)

All the above flows are alike: the client is trying to connect to a port that is closed. Unfortunately
- only one flow is alerted
- this alert is reported as TCP probing but it cannot be this case, as the client is talking always with the same destination IP+port and (see below) the port is closed.

![Screen Shot 2021-04-29 at 14 12 49](https://user-images.githubusercontent.com/4493366/116548812-0c322980-a8f5-11eb-8d5e-3aaf510409dd.png)

**Comment by cardigliano** [comment]
The 2 alerted flows, unlike the others, have a single SYN packet which is triggering the TCP probing alert. This is leading to false positives and IMHO it should be removed (note we already have a SYN scan check on the host as attacker)
