### ISSUE TITLE
Flow Alerts Lack Tuple information

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5256]
![Screen Shot 2021-04-29 at 14 14 04](https://user-images.githubusercontent.com/4493366/116548969-384daa80-a8f5-11eb-90a7-a7857d558350.png)

From this alert it is not possible to know the 5-tuple that originated the alert

**Comment by lucaderi** [comment]
Implementation ok but please merge IP:port columns as it doesn't;t make sense to waste space with ports column is they are not sortable. This way you can leave more space to other columns that need space such as the description

**Comment by simonemainardi** [comment]
please for client and server make the same as the active flows page:

![image](https://user-images.githubusercontent.com/3397663/116853602-a1376a00-abf6-11eb-90ca-1760e15bd370.png)

re-use the same function that also attaches badges, flags, etc

**Comment by MatteoBiscosi** [comment]
Removed badges because they waste a lot of space #5276
