### ISSUE TITLE
Merge Flow Alerts with nIndex

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5258]
![Screen Shot 2021-04-29 at 14 15 16](https://user-images.githubusercontent.com/4493366/116549079-5c10f080-a8f5-11eb-95aa-47224957482e.png)

It is requested for the above flow alerts, to to have the ability (if -F nIndex is enabled) to jump onto nIndex and visualize the flow. A simple way would be to glue the up using communityId but probably it's better to use the 5-tuple as this allows nIndex filtering and drill down to better operate.

**Comment by MatteoBiscosi** [comment]
Implemented by @cardigliano (see #5256), the jump is done by clicking the icon into the description

**Comment by cardigliano** [comment]
The current implementation adds 2 icons: 1. the "stream" icon which is present when the flow is active (with a link to the flow details), 2. the "lens" icon which is present then nIndex is enabled (with a link to the Historical flow explorer). See the picture below.

<img width="354" alt="Screen Shot 2021-04-30 at 18 22 05" src="https://user-images.githubusercontent.com/7548711/116724500-06b20d80-a9e1-11eb-88b0-e0e09fc5cb1b.png">

**Comment by lucaderi** [comment]
![Screen Shot 2021-05-01 at 19 08 22](https://user-images.githubusercontent.com/4493366/116789737-a4284280-aab0-11eb-8953-6b0ecf55f9d1.png)

The implementation is ok but The icons you added are in the description instead in the actions column where it is its natural place. I suggest to move it over there.
