### ISSUE TITLE
nEdge Apply button does not apply

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5259]
button is disabled and nothing happens

![image](https://user-images.githubusercontent.com/3397663/116580517-bc168f80-a913-11eb-8e36-4ee0b53b83ca.png)

**Comment by simonemainardi** [comment]
![image](https://user-images.githubusercontent.com/3397663/116582552-c9347e00-a915-11eb-81a0-8d160df30467.png)

**Comment by gabryon99** [comment]
Fix done. See also the commit: https://github.com/ntop/ntopng/commit/690b60319949142cd8d4bb1fc08c38e907c2cffc
