### ISSUE TITLE
Client History (Multiple Clients)

### ISSUE THREAD

**Issue by arrmo** [ntop/ntopng#526]
Hopefully this makes sense ... :). A feature request (that I'd like to help with if possible!)

I would like to be able to plot the top (some number ... say 3, 5, or 10) clients on the subnet. Historical data, such as for an interface (Timeseries), a line chart with the items on top of each other - the top clients over the time period.

Thanks!

**Comment by emanuele-f** [comment]
With the current implementation, ntopng (pro version) is able to generate top senders and top receivers graphs for a given network interface.

![screenshot at 2017-05-05 11-37-59](https://cloud.githubusercontent.com/assets/5488003/25740672/c6d2eb7e-3187-11e7-931b-8500d58cc0b0.png)
