### ISSUE TITLE
Alert download button broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5260]
In the alert window there are two main problems with the bottom download button:

![Screen Shot 2021-04-30 at 08 28 21](https://user-images.githubusercontent.com/4493366/116657057-10f6ec00-a98e-11eb-813e-83e49418e463.png)

- Change the label from "Download Records" -> "Download X Alerts" where X is the number of alerts currently shown. If too complicated omit X but change the label
- The download button does not work

**Comment by lucaderi** [comment]
Some comments:
- the output is JSON, whereas with nIndex it is text. We need to be consistent and use a single format
- fields as msg":"<a class='btn-sx' href='/lua/flow_details.lua?flow_key=3533815125&flow_hash_id=66'><i class='fas fa-stream'></i></a> <a class='btn-sx' href='/lua/pro/nindex_query.lua?begin_epoch=1619888693&end_epoch=1619888701&cli_ip=192.168.1.178,eq&srv_ip=17.248.145.208,eq&cli_port=52334,eq&srv_port=443,eq&l4proto=TCP,eq' are useless

@simonemainardi What is your view on this?

**Comment by simonemainardi** [comment]
@MatteoBiscosi please use the already defined `noHtml` and dispose the duplicate function added with the commit
