### ISSUE TITLE
Score anomaly lacks client/server information 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5263]
![Screen_Shot_2021-04-30_at_18_33_50](https://user-images.githubusercontent.com/4493366/116725807-bc319080-a9e2-11eb-8b90-d6be5f224788.png)

**Comment by MatteoBiscosi** [comment]
Client and Server information should be into the description of the alert, please check it and let me know, because at the moment I'm unable to reproduce this alert

**Comment by cardigliano** [comment]
I confirm the alert description now reports the client/server info for this alert 
<img width="561" alt="Screen Shot 2021-05-10 at 16 06 43" src="https://user-images.githubusercontent.com/7548711/117672495-2fd55980-b1aa-11eb-95a4-78b94c0f4d15.png">
