### ISSUE TITLE
Improve GeoIP documentation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5264]
I've installed ntopng on Raspberrian but I can't get GeoIp to work and therefore the map stays empty. I've followed all instructions Max Mind ( https://github.com/ntop/ntopng/blob/dev/doc/README.geolocation.md) but they are a bit fuzzy. Can you please update the instructions for raspberry pi useres. 

II have installed ntopng-data but I can’t find geoipupdate on my raspberry. Is that still correct? Not knowing the version of geoipupdate I downloaded both versions of GeoIP.conf to /etc/ but in vain. I even tried to download the GeoLite2-Country GeoLite2-ASN Databases manually but in vain. 

In what directory do you have to place GeoIP.conf file: Schould it be in the new or the old format? Wow can I trigger the download ? (Or wow do I install geoipupdate on Raspberrian). Are there any special setting that I might have foregotten?

**Comment by cardigliano** [comment]
Instructions for Raspberry Pi OS have been added in  https://github.com/ntop/ntopng/commit/53ffe5c9e679299c4f4cceda91718cf79ab056c5
