### ISSUE TITLE
Lateral movement detection does not seem to honour DHCP

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5265]
![image](https://user-images.githubusercontent.com/4493366/116740764-bbeec080-a9f5-11eb-9106-e48d98f07332.png)

This is the image of my home network where DHCP is active and host change IP continuously. It looks MAC addresses are not used as keys in lateral movement and periodicity detection.

**Comment by MatteoBiscosi** [comment]
Fixed for both, Periodicity and Service Map (pro rep)
