### ISSUE TITLE
IPv4 LInk-Local Addresses are marked (wrongly) as Remote

### ISSUE THREAD

**Issue by aidanharris** [ntop/ntopng#5266]
The same as #4339 but for IPv4.

[RFC 3927](https://tools.ietf.org/html/rfc3927) addresses in the `169.254/16` prefix are flagged as "Remote" when they should show as "Local".

**Comment by simonemainardi** [comment]
Fixed. Thanks for reporting. IPs in that range are now reported as private, indeed, they are meant for link-local communication. Note that "Local" in the ntopng parlance means addresses specified with `-m=""` and this is a bit different concept.

**Comment by simonemainardi** [comment]
also see referenced commit https://github.com/ntop/ntopng/commit/5fab173ba221fb885b304a80977e34e1238d73a3
