### ISSUE TITLE
Alert: Missing button to flush all alerts

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#5268]
A button to delete all alerts is missing - support for this is implemented by the backend

**Comment by simonemainardi** [comment]
use the following endpoints to delete

```
 simone@devel:~/ntopng$ find scripts/lua/rest/ -name "alerts.lua" | grep delete
scripts/lua/rest/v1/delete/host/alerts.lua
scripts/lua/rest/v1/delete/network/alerts.lua
scripts/lua/rest/v1/delete/interface/alerts.lua
scripts/lua/rest/v1/delete/mac/alerts.lua
scripts/lua/rest/v1/delete/user/alerts.lua
scripts/lua/rest/v1/delete/flow/alerts.lua
scripts/lua/rest/v1/delete/system/alerts.lua
scripts/lua/rest/v1/delete/active_monitoring/alerts.lua
```

- open a modal
- write timestamps and other filters in the modal
- ask for confirmation

**Comment by simonemainardi** [comment]
delete doesn't work


![image](https://user-images.githubusercontent.com/3397663/117144100-d3d99200-adb1-11eb-8fbb-569037fee271.png)


clicking on the button opens a modal

![image](https://user-images.githubusercontent.com/3397663/117144138-dfc55400-adb1-11eb-8e6c-ac364af0fd2d.png)


but then I can see no POST in the requests and data is not always deleted. Sometimes it is deleted, some other times not.

**Comment by simonemainardi** [comment]
Moreover, once the page refreshes after a submit, the filters are broken:

![image](https://user-images.githubusercontent.com/3397663/117144607-68dc8b00-adb2-11eb-9dda-d41d5b12738e.png)

**Comment by simonemainardi** [comment]
Layout is awkward. Dates and times can be clicked and change values of the underlying page.

![image](https://user-images.githubusercontent.com/3397663/117628211-30093100-b179-11eb-8199-908b075ddc7d.png)
