### ISSUE TITLE
CheckMK Integration - Migration of alert endpoints

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5269]
@TimotheusBachinger in the latest 4.3 dev we have significantly reworked the internal ntopng alerts engine to:

- keep entities in separate database tables
- improve the database structure
- improve the way data are stored and presented to the user

Alerts, which were previously mixed together, are not kept separated on a per-entity basis. That is, we have host alerts, interface alerts and so on. This has also impacted the way REST API are structured. For example, to get alert timeseries, now there's an entity that should be added as part of the REST API URL, e.g.:

the former endpoint 

```
scripts/lua/rest/v1/get/alert/ts.lua
```

is now:

```
scripts/lua/rest/v1/get/host/alert/ts.lua
scripts/lua/rest/v1/get/network/alert/ts.lua
scripts/lua/rest/v1/get/interface/alert/ts.lua
scripts/lua/rest/v1/get/mac/alert/ts.lua
scripts/lua/rest/v1/get/user/alert/ts.lua
scripts/lua/rest/v1/get/flow/alert/ts.lua
scripts/lua/rest/v1/get/system/alert/ts.lua
scripts/lua/rest/v1/get/timeseries/ts.lua
scripts/lua/rest/v1/get/active_monitoring/alert/ts.lua
```

As the check MK integration uses this alert endpoints, it would be desirable to start discussing how to adjust the integration to the new REST API. Note that version 4.2 is unchanged and the integration will continue working, however, after the release of version ntopng version 4.4, such REST API will need to be adjusted.

AFAIK, these are the endpoints that have been impacted from the changes and that should be migrated are:

```
/lua/rest/v1/get/alert/data.lua
/lua/rest/v1/get/alert/severity/counters.lua
/lua/rest/v1/get/alert/ts.lua
/lua/rest/v1/get/alert/type/counters.lua
/lua/rest/v1/get/host/alert/data.lua
```

@TimotheusBachinger It would be good if you could check and give us (@lucaderi) your comments. Thanks.

**Comment by TimotheusBachinger** [comment]
Hi @lucaderi ,

thanks for the heads-up.

My first thoughts:

- We would need to continue to support the integration with v4.2. Therefore we would need to be able to query the ntop REST API version and then decide on checkmk side which endpoints/REST API (v1 or v2) to be used. Would this be possible (or maybe already is possible)?
- I did not had a deeper look into the data format of the new endpoints, but I would assume it stays "similar" to the old ones. In this case, the migration should be straight forward.
- Do you have a rough timeline, when v4.4 (using REST API v2) will be released? This would give us a better planing when we need to do the migration.

Best Regards
Timi

**Comment by simonemainardi** [comment]
@TimotheusBachinger 

> We would need to continue to support the integration with v4.2. Therefore we would need to be able to query the ntop REST API version and then decide on checkmk side which endpoints/REST API (v1 or v2) to be used. Would this be possible (or maybe already is possible)?

There will be some changes in the API as well. Changes are due to the rework of the backend alert engine. We will bump the version from v1 to v2 but still there will be changes.

> I did not had a deeper look into the data format of the new endpoints, but I would assume it stays "similar" to the old ones. In this case, the migration should be straight forward.

It's similar, but yes there will be some changes to take into account.

> Do you have a rough timeline, when v4.4 (using REST API v2) will be released? This would give us a better planing when we need to do the migration.

End of June, mid-july.

To discuss changes in greater detail, please allow us some extra time so we can complete the implementation and documentation.

**Comment by lucaderi** [comment]
@TimotheusBachinger The v1 REST is now part of the current dev. So all functionalities of 4.2 are available in the dev version and in the next stable. As we have made quite some improvenments to the v1, we have created a v2 API version that will replace v1. So in the next stable release we'll support both v1 and v2, but the v1 will be deprecated in a future stable release so please plan moving to v2 when possible.
Please make sure you do NOT interact with ntopng directly (e.g. using custom lua scripts we use in out GUI) but only using the REST API we support, as this is the only stable API we support.

**Comment by TimotheusBachinger** [comment]
Hi Luca,

finally, I am able to start the migration to the new API v2. 
I already have some questions, you might be able to answer.

Till now, we were using this endpoint: `/lua/rest/v1/get/alert/data.lua`

- I am not really sure whats the corresponding endpoint in v2. `/lua/rest/v2/get/all/alert/list.lua ` was my first guess but it seems this is more a statistically overview of alerts. `lua/rest/v2/get/system/alert/list.lua` looks better but I am not sure what the term "system" should imply here.
- I've seen, this endpoint vanished also in 5.0-stable under v1, which creates a diff for us between v1 under 4.2 versus v1 under 5.x
- `GET /lua/rest/v2/get/alert/data.lua` is also listed in the API documentation - I'll guess this is not up-to-date at the moment?

What is the corresponding endpoint to the old endpoint `lua/rest/v1/get/alert/ts.lua`? When comparing the respononse with `lua/rest/v2/get/all/alert/ts.lua`, I can see that:
- now somehow sorted by "names", e.g. "notice"
- previously, the time steps were always hours, so like 24 values per day:
`{"1632960000":[52,65,37,62,55,58,164,159,160,146,154,82,0,0,0,0,0,0,0,0,0,0,0,0]}`
- with the new endpoint, the steps seems to adapt to the timerange, e.g.:
`"series":[{"data":[[1632993344000,1],[1632993376000,0],[1632993408000,0]`
--> Is this correct?

best regards
timi

**Comment by simonemainardi** [comment]
Hi Timi,

> Till now, we were using this endpoint: /lua/rest/v1/get/alert/data.lua

They are now divided into families:

simone@devel:~/ntopng$ find scripts/lua/rest/v2/ -name list.lua
scripts/lua/rest/v2/get/host/alert/list.lua
scripts/lua/rest/v2/get/network/alert/list.lua
scripts/lua/rest/v2/get/interface/alert/list.lua
scripts/lua/rest/v2/get/mac/alert/list.lua
scripts/lua/rest/v2/get/all/alert/list.lua
scripts/lua/rest/v2/get/user/alert/list.lua
scripts/lua/rest/v2/get/flow/alert/list.lua
scripts/lua/rest/v2/get/system/alert/list.lua
scripts/lua/rest/v2/get/am_host/alert/list.lua

So for example to get the list of host alerts, you do `scripts/lua/rest/v2/get/host/alert/list.lua`. To get the list of flow alerts you do `scripts/lua/rest/v2/get/flow/alert/list.lua` and so on.

To have an idea of how many alerts there are per family, within the desired time range, you can query `scripts/lua/rest/v2/get/all/alert/list.lua`.

> with the new endpoint, the steps seems to adapt to the timerange, e.g.:
"series":[{"data":[[1632993344000,1],[1632993376000,0],[1632993408000,0]
--> Is this correct?

Yes, this is correct.

**Comment by TimotheusBachinger** [comment]
Hi Simone,

OK thanks for the clarification.

Regarding the new timeseries format:

>     with the new endpoint, the steps seems to adapt to the timerange, e.g.:
>     "series":[{"data":[[1632993344000,1],[1632993376000,0],[1632993408000,0]
>     --> Is this correct?
> 
> Yes, this is correct.

Actually, the old format (counts per hour) is needed for our histogram plots. Is there a way to get this format back? Otherwise we would need to calculate this on our side.

Regards
Timi

**Comment by simonemainardi** [comment]
@MatteoBiscosi is taking care of this.

**Comment by simonemainardi** [comment]
ts.lua is now able to return data into the old 24-h format. Use ts.lua as usual, just add parameter `by_24h=true` to have the desired behavior.

Example, for flows:

```
http://devel:3000/lua/rest/v2/get/flow/alert/ts.lua?status=historical&epoch_begin=1633996800&ifid=0&epoch_end=1634639172&by_24h=true
```

![image](https://user-images.githubusercontent.com/3397663/137895001-f8f01253-1b4a-4467-928a-8286b47b48bf.png)


Example, for hosts (historical):

```
http://devel:3000/lua/rest/v2/get/host/alert/ts.lua?epoch_begin=1634076060&ifid=0&status=historical&epoch_end=1634162340&by_24h=true
```

![image](https://user-images.githubusercontent.com/3397663/137895187-78ffa1e0-bfa3-4c74-8208-e8ec2779a30b.png)


Example, for hosts (engaged):

```
http://devel:3000/lua/rest/v2/get/host/alert/ts.lua?epoch_begin=1634076060&ifid=0&status=engaged&epoch_end=1634162340&by_24h=true
```

![image](https://user-images.githubusercontent.com/3397663/137895258-dcbd3c69-b766-489d-9e62-a274112aa715.png)
