### ISSUE TITLE
.deb build failure on Ubuntu (16.04 LTS) (?)

### ISSUE THREAD

**Issue by arrmo** [ntop/ntopng#527]
Hi,

OK, trying to get to v2.3 on Ubuntu (16.04 LTS). I cloned ntopng and nDPI (as it tells me to do, this was very helpful!). Installed the required dependencies, and it all built fine (to the make stage), but ... make install worked, but only to be able to run it => not as a service, and no /etc/ntopng.conf (for example). so then I tried to build the .deb (inside packages/ubuntu), as it recommends, but this fails (info below). Thoughts?

dh_clean: Compatibility levels before 4 are no longer supported (level 1 requested)
debian/rules:22: recipe for target 'clean' failed
make: **\* [clean] Error 25
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2
Makefile:10: recipe for target 'ntopng' failed
make: **\* [ntopng] Error 2

Thanks!

**Comment by simonemainardi** [comment]
Said that 16.04 is not officially supported, you can try the following

```
$ pwd
/Users/simone/code/ntopng/packages/ubuntu/debian.ntopng
$ echo 4 > compat
```

same for `debian.ntopng-data`

**Comment by arrmo** [comment]
No luck, but I understand - no Ubuntu 16.04 yet.

Thanks!

**Comment by lucaderi** [comment]
@arrmo I am working at it. Stay tuned

**Comment by arrmo** [comment]
Thanks! Yell if you want me to test something out - happy to help if I can!

**Comment by lucaderi** [comment]
Fixed by https://github.com/ntop/ntopng/commit/a4d527ff9ee17374b9596ae799053fa2af74964b

**Comment by arrmo** [comment]
FYI, I updated git (git fetch), and tried to recompile - same error. Do I need to do something special?

Thanks!

**Comment by lucaderi** [comment]
Please post a log

**Comment by arrmo** [comment]
It's all working to this point (and ntopng itself builds fine),

cp -r ../etc/ ./usr/ ./debian/tmp
cp: target './debian/tmp' is not a directory
debian/rules:38: recipe for target 'binary-arch' failed
make: **\* [binary-arch] Error 1
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
Makefile:10: recipe for target 'ntopng' failed
make: **\* [ntopng] Error 2

Thanks!

**Comment by lucaderi** [comment]
You are using old code or the stable release

**Comment by arrmo** [comment]
Ahhh ... that's very possible. Are you on the dev branch? If so, no issues - and sorry for the confusion.

Thanks!

**Comment by lucaderi** [comment]
Sure I am on dev branch

**Comment by dscdtc** [comment]
I got this error too how can I fix it ,THX.
dh_clean: Compatibility levels before 5 are no longer supported (level 4 requested)

**Comment by simonemainardi** [comment]
@dscdtc use the code in the dev branch I guess you are using old code

**Comment by dscdtc** [comment]
@simonemainardi Thank you , but I am sure I am using dev branch ... it still error on Kali 
make: [clean] Error 2 (ignored)
cp -f /usr/share/misc/config.sub config.sub
cp -f /usr/share/misc/config.guess config.guess
dh_clean 
dh_clean: Compatibility levels before 5 are no longer supported (level 4 requested)
debian/rules:55: recipe for target 'clean' failed
make: *** [clean] Error 25
dpkg-buildpackage: error: debian/rules clean gave error exit status 2
ERROR: command failed!
# ERROR: command failed!

**Comment by simonemainardi** [comment]
@dscdtc please report the exact version of ntopng you are trying to install on Kali
