### ISSUE TITLE
Alerts: broken layout when resizing the screen

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5271]
![Screen Shot 2021-05-03 at 21 59 28](https://user-images.githubusercontent.com/4493366/116926633-de354800-ac5a-11eb-883c-85ef76ccca57.png)
![Screen Shot 2021-05-03 at 21 59 08](https://user-images.githubusercontent.com/4493366/116926638-decdde80-ac5a-11eb-80cb-b50e5fe0de67.png)

**Comment by cardigliano** [comment]
This layout has been reworked, however this should be further improved imho adding at least some padding and the same alignment on the left side when wrapping. 

<img width="728" alt="Screen Shot 2021-05-10 at 11 33 31" src="https://user-images.githubusercontent.com/7548711/117638868-96934c80-b183-11eb-9985-036cde4c81b1.png">
