### ISSUE TITLE
Missing Alarms Breakdown

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5272]
In the new alerts implementation the previous breakdown is gone and thus it is hard to understand what is happening. it would be nice to have
- top attacker/victim breakdown 
- alert type breakdown
- etc.

as otherwise it is hard to understand what is happening on a system 

![Screen Shot 2021-05-03 at 22 01 21](https://user-images.githubusercontent.com/4493366/116926799-1f2d5c80-ac5b-11eb-966d-ba438ea6b0af.png)

**Comment by MatteoBiscosi** [comment]
Implemented as Requested
