### ISSUE TITLE
Alerts: Inactive buttons

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5273]
![Screen_Shot_2021-05-03_at_22_01_21](https://user-images.githubusercontent.com/4493366/116927246-b2ff2880-ac5b-11eb-9333-4ba36561e21b.png)

In the alerts view (with -f nindex), the flow icon is disabled, the magnifier lens is active but it executes no action.

**Comment by cardigliano** [comment]
The flow icon is a link to the active flow, it seems the flow is no longer active in this case (we should probably add a title or tooltip).
The magnifier should redirect to the Historical Flow Explorer, this link is working for me, could you inspect the element and provide the href?

**Comment by cardigliano** [comment]
Inactive buttons are no longer present, active buttons have been moved to the flow columns
