### ISSUE TITLE
VLAN Feature is gone after Upgrade

### ISSUE THREAD

**Issue by olg33** [ntop/ntopng#5274]
Hi,

We've been working with ntopng Community Edition v.4.0.200609 and got used to the VLAN feature under Hosts, it was very useful in our network analysis.

![Capture](https://user-images.githubusercontent.com/61751672/116927904-520b2c80-ac2a-11eb-9705-ba45a8c1b533.JPG)

We recently upgraded to ntopng Community v.4.2.210427 but just noted that the VLAN section is gone. Is any reason why it's no longer there? and most important, is there any way to get it back? 

Thank you.

**Comment by simonemainardi** [comment]
@MatteoBiscosi please try and reproduce. To simulate VLANs you can use option `--simulate-vlans`

**Comment by olg33** [comment]
Thanks. I just added the option provided and the VLAN feature is back. However it doesn't seem to be providing accurate information. For instance I can see VLAN IDs from 1 to 256 all with ath least one host, I don't have that many IDs configured in my network. I have IDs such as 300 and 800 but those are not being displayed. Also, if I look at the hosts on Vlan 1, I expect to see hosts in a single private subnet as that is a native vlan, instead I see all kind of public subnets that I know for sure they aren't there.  Any thoughts?

**Comment by simonemainardi** [comment]
It's a debug flag and I've suggested @MatteoBiscosi to check it. It's not a flag to be used in production.

**Comment by MatteoBiscosi** [comment]
Hi @olg33 I'm sorry but I'm unable to reproduce your problem. Note that the VLANs feature is being displayed only if you have VLANs in your network. Could you please tell me if you find an host with a VLAN different from the 0 (without using the debug flag that simone suggested)?

**Comment by olg33** [comment]
Hello @MatteoBiscosi Let me provide you more details of the problem.
I have a virtual machine with ntopng connected to a switch port that is mirroring traffic from a trunk with the following VLANS:
 
`       vlan 1-3,6,7,17,21,36,46,56,66,76,86,96,106,116,126
        vlan add 127,137,140,146,160,301-303,333,408,421,446
        vlan add 546,660,706,716,736,801,833,921,946`

After starting ntopng with the --simulate-vlans parameter (no debug), I get the following Vlans in the system:

CHART 1
![vlan_s1](https://user-images.githubusercontent.com/61751672/117321105-d9d77d80-ae5a-11eb-8917-c7080b27354e.JPG)

 CHART 2 
![vlan_s2](https://user-images.githubusercontent.com/61751672/117321151-e22fb880-ae5a-11eb-8523-b292638d8a0c.JPG)

 CHART 3
![vlan_s3](https://user-images.githubusercontent.com/61751672/117321174-e8be3000-ae5a-11eb-9ece-ab7fc6934c2a.JPG)

I would expect to see the same vlan IDs from the switch displayed in ntopng. Instead I see Vlan IDs from 1 to 254 but most of those Vlans (even though they have hosts) don't exist in my network and Vlans with ID higher than 254, like 301 or 446 (which are the busiest in my network) aren't being recognized by ntopng. That's the main issue right now.

**Comment by simonemainardi** [comment]
> After starting ntopng with the --simulate-vlans ....

This parameter is DEBUG-ONLY, it FAKES VLANs for the purpose of testing. So it is normal that  

> those Vlans (even though they have hosts) don't exist in my network

**Comment by simonemainardi** [comment]
It seems you have disaggregation enabled.  Please, report that configuration.

**Comment by olg33** [comment]
> It seems you have disaggregation enabled. Please, report that configuration.

The only parameters that aren't commented on /etc/ntopng.conf file are :

`-G=/var/run/ntopng.pid`
`--community`
`--simulate-vlans`
`  -i=ens192`
` -w=3000`

The rest are disabled.

> This parameter is DEBUG-ONLY, it FAKES VLANs for the purpose of testing. So it is normal that

In that case, can we say that the VLAN feature is no longer supported for production networks on version 4.2.2? 

VLAN simulations don't help on our day-to-day operations.

**Comment by simonemainardi** [comment]
> VLAN simulations don't help on our day-to-day operations.

Sure. I didn't ask you to use VLAN simulation and I don't know why you wanted to use it. I just asked @MatteoBiscosi to use that option to try and reproduce. @MatteoBiscosi do you have any news?

**Comment by simonemainardi** [comment]
> It seems you have disaggregation enabled. Please, report that configuration.

You did not report on this. You need to visit the interface page -> tab with a branch icon, and check for disaggregation. Report. I can see from

![image](https://user-images.githubusercontent.com/3397663/117408046-ac98d700-af0f-11eb-952f-4ed145060f3f.png)


That you have disaggregation enabled.

**Comment by olg33** [comment]
> You did not report on this. You need to visit the interface page -> tab with a branch icon, and check for disaggregation. Report. I can see from

Ah ok, got it. Here you are:

![Capture](https://user-images.githubusercontent.com/61751672/117474584-0f4a9c80-af29-11eb-8a00-5ee9b6cde119.JPG)

**Comment by olg33** [comment]
I just went ahead and enabled it:
![Capture](https://user-images.githubusercontent.com/61751672/117475649-4ec5b880-af2a-11eb-8594-4182df15536c.JPG)

But after that nothing happened. Unless I'm missing something.

**Comment by simonemainardi** [comment]
@MatteoBiscosi please give a feedback on this.

**Comment by MatteoBiscosi** [comment]
Hi @olg33 how many disaggregated interfaces do you have?

**Comment by simonemainardi** [comment]
Also attach a pcap capture of ens192. You can send it privately to biscosi at ntop dot org

Note that initially you were attaching a screenshot on a `br0` interface, then on `ens192` so you should make sure to be running tests on the same conditions.

**Comment by olg33** [comment]
> Hi @olg33 how many disaggregated interfaces do you have?

Only one: ens192

> Also attach a pcap capture of ens192. You can send it privately to biscosi at ntop dot org

Already sent. Please let me know if not received yet.

> Note that initially you were attaching a screenshot on a br0 interface, then on ens192 so you should make sure to be running tests on the same conditions

The snapshot with br0 is just a demonstration of how the VLAN feature worked when on Rel.4.0.2, that's a different VM. All the VMs upgraded to 4.2.2 and under test have interface ens192. br0 is no longer used on 4.2.2.

**Comment by MatteoBiscosi** [comment]
Hi @olg33  Thanks for the pcap. The problem is that you only have one VLAN (the 0) so the VLAN option won't appear, it's going to appear when you have more than one VLAN.
This is the reason why you don't see that option.
In fact when you use the DEBUG simbol '--simulate-vlans' that feature is going to show up.
An other thing that shows the fact that you only have one VLAN is the number of interfaces, because you enabled the disaggregation by VLAN id, so if u have more than one VLAN you are going to have an interface dropdown like this, one interface per VLAN id:
![Screenshot from 2021-05-10 17-24-42](https://user-images.githubusercontent.com/49585191/117683789-b2fbad00-b1b4-11eb-8d45-5de5e18c6638.png)

**Comment by olg33** [comment]
Thanks @MatteoBiscosi 

That makes sense, however I do have VLANs in this network. As previously mentioned, interface ens192 is connected to an interface that mirrors traffic (We have enabled the Mirrored Traffic option on Interface -> Gear Icon --> Mirrored Traffic) coming from a switch trunk that has enabled the following VLANs:

` switchport trunk allowed vlan 1-3,6,7,17,21,36,46,56,66,76,86,96,106,116,126
 switchport trunk allowed vlan add 127,137,140,146,160,301-303,333,408,421,446
 switchport trunk allowed vlan add 546,660,706,716,736,801,833,921,946`

   If the VLAN id is not showing after disaggregation was enabled may not be because traffic comes from a single VLAN but because something else.

**Comment by olg33** [comment]
Also, packet captures in pcap all have a VLAN id assigned (I know them) but can't understand why they aren't being recognized by the capture.

**Comment by simonemainardi** [comment]
There is no 802.1q VLAN-tagged packet inside the pcap you've provided

![image](https://user-images.githubusercontent.com/3397663/117694843-e5f76e00-b1bf-11eb-93ec-597f2ec4e461.png)

So it is completely normal not to see VLANs. Likely, your mirror is just mirroring packets without their VLAN-tags. Definitely nothing on the ntopng side which works normally. Check your mirror configuration and make sure VLAN headers are sent in the traffic.
