### ISSUE TITLE
Flow Alerts: Minimum viable implementation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5277]
<img width="1118" alt="Screenshot 2021-05-04 at 08 50 29" src="https://user-images.githubusercontent.com/4493366/116969000-d48cfe00-acb5-11eb-9980-b1b7070a0dd6.png">
Flow alerts *must* report all the time the following fields
- time
- alert type
- client and server
- alert description

Everything else can be enabled/disable but not these information above listed

**Comment by cardigliano** [comment]
Columns have been reworked after this, moving the severity, the alert type in the description, merging client/server in a single Flow column
