### ISSUE TITLE
Flow Explorer Filter Input is broken (GUI)

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#5278]
When adding multiple chips into the filter input, they are not properly rendered. This happens for instance when digging into a flow alert, by clicking on the "Historical Flow" button, which creates a filter with a few items.
Furthermore, the filter label does not match the column name.

<img width="1475" alt="Screen Shot 2021-05-04 at 09 28 47" src="https://user-images.githubusercontent.com/7548711/116972420-44ea4e00-acbb-11eb-93af-9d0aa6043865.png">

**Comment by gabryon99** [comment]
<img width="1904" alt="Screenshot 2021-05-04 at 09 41 27" src="https://user-images.githubusercontent.com/14114916/116973475-e8882e00-acbc-11eb-8bdc-819d6f22e252.png">
I think the best solution is to move the Filters Input Box below the range picker, like shown in the screenshot above.

**Comment by simonemainardi** [comment]
Verified. Working.
