### ISSUE TITLE
Can't make ntopng due to error in NetworkInterface.cpp:862: undefined reference to ndpi_detection_giveup

### ISSUE THREAD

**Issue by EAnsy** [ntop/ntopng#528]
Fresh source (today)
**_git clone https://github.com/ntop/ntopng.git
git clone https://github.com/ntop/nDPI.git_**

Then **_cd nDPI_**
Done **_./autogen.sh_**
Done all commands 1..5 as described in **INSTALL** file there, **OK**.

Then **_cd ../ntopng_**
Done **_./autogen.sh_** OK
Done **_./configure_** OK

Then **_make_** issuing an error below:

`I/root/ntopng/third-party/http-client-c/src/  -DDATA_DIR='"/usr/local/share"' -I/root/ntopng/third-party/libgeohash -I/root/ntopng/third-party/patricia   -c src/Ntop.cpp -o src/Ntop.o
src/Ntop.cpp:705:26: warning: unused variable 'val_group' [-Wunused-variable]
  char key[64], val[64], val_group[64], password_hash[33];
                         ^
1 warning generated.
/usr/bin/clang++ -O0  src/GenericHashEntry.o  src/GenericHost.o  src/AddressTree.o  src/MySQLDB.o  src/CollectorInterface.o  src/ParserInterface.o  src/Prefs.o  src/nDPIStats.o  src/StatsManager.o  src/Utils.o  src/NtopGlobals.o  src/ElasticSearch.o  src/DummyInterface.o  src/Geolocation.o  src/Flow.o  src/ZCCollectorInterface.o  src/HTTPBL.o  src/PeriodicActivities.o  src/Trace.o  src/HostHash.o  src/LocalTrafficStats.o  src/PacketDumper.o  src/FlowHash.o  src/EthStats.o  src/Profiles.o  src/PcapInterface.o  src/GenericHash.o  src/DB.o  src/PacketStats.o  src/IpAddress.o  src/Grouper.o  src/Host.o  src/Profile.o  src/AlertCounter.o  src/ExportInterface.o  src/HTTPstats.o  src/TrafficStats.o  src/GrouperEntry.o  src/NetworkInterface.o  src/Mutex.o  src/PacketDumperTuntap.o  src/VirtualHostHash.o  src/PF_RINGInterface.o  src/NetworkStats.o  src/HTTPserver.o  src/Lua.o  src/RuntimePrefs.o  src/AddressResolution.o  src/CategoryStats.o  src/ActivityStats.o  src/Flashstart.o  src/DivertInterface.o  src/main.o  src/Redis.o  src/VirtualHost.o  src/NetworkInterfaceView.o  src/ProtoStats.o  src/DnsStats.o  src/Ntop.o  -Wall -L/usr/local/lib -lndpi   -lpcap /root/ntopng/third-party/LuaJIT-2.0.3/src/libluajit.a -lrrd   /root/ntopng/third-party/zeromq-4.1.3/.libs/libzmq.a /root/ntopng/third-party/json-c/.libs/libjson-c.a  -lsqlite3 -L/usr/lib -lmysqlclient -lpthread -lz -lm -lrt -lssl -lcrypto -ldl    -L/usr/local/lib -lldap -llber -lnl -lrt -lz -ldl -lcurl  -lm -lpthread -o ntopng
src/Flow.o: In function 'Flow::dissectBittorrent(char*, unsigned short)':
/root/ntopng/src/Flow.cpp:1984: undefined reference to 'ndpi_strnstr'
src/NetworkInterface.o: In function``NetworkInterface::processPacket(timeval const*, unsigned long long, ndpi_ethhdr*, unsigned short, ndpi_iphdr*, ndpi_ipv6hdr*, unsigned short, unsigned short, pcap_pkthdr const*, unsigned char const*, bool*, unsigned short*)':
/root/ntopng/src/NetworkInterface.cpp:862: undefined reference to 'ndpi_detection_giveup'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ntopng] Error 1
root@vsms:~/ntopng#
`

Fresh upgraded [SMS server](http://sms.it-ccs.com) (Slackware based)

`
root@vsms:~/nDPI# uname -a
Linux vsms 3.10.41-smp #2 SMP Sun Jun 1 01:38:11 EEST 2014 i686 Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz GenuineIntel GNU/Linux
`
Previous stable ntopng 2.2 compiled OK there.

**Comment by simonemainardi** [comment]
ntopng configure script looks for nDPI in its directory and in its parent directory (https://github.com/ntop/ntopng/blob/dev/configure.seed#L49). However, I can't see these directories listed in `-I`. 

ndpi installation is not needed, compilation suffices.

Please, re-run ntopng ./autogen and ./configure and post their output. Also, it looks like you are compiling everything as root.

**Comment by EAnsy** [comment]
Well, without nDPI' **_make install_** all ntopng **_make_** process finished OK!
But I would be glad to see this note in documentation.
