### ISSUE TITLE
Alerts: Missing time in hover

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5282]
<img width="951" alt="Screenshot 2021-05-04 at 11 41 21" src="https://user-images.githubusercontent.com/4493366/116986151-b92ded00-accd-11eb-8ccd-c798661f9e64.png">

In case the time window is short, the hover window must also report the time

**Comment by gabryon99** [comment]
Add missing date as requested.

**Comment by lucaderi** [comment]
![Screen Shot 2021-05-06 at 16 44 10](https://user-images.githubusercontent.com/4493366/117318044-5cc3fc80-ae8a-11eb-81f7-bfc0da1d05f0.png)
Time is now present but it's wrong

**Comment by gabryon99** [comment]
Hour fixed to 24H format.

**Comment by lucaderi** [comment]
![Screen Shot 2021-05-06 at 17 35 42](https://user-images.githubusercontent.com/4493366/117325994-87fe1a00-ae91-11eb-8369-b32ebb4d8021.png)
Closer but not fixed. As you can see I do not expect to see a time < 17:20:00 in the hover for 17:20:00

**Comment by simonemainardi** [comment]
note also that there's a 'popper'-like toast permanently hidden in the background

![image](https://user-images.githubusercontent.com/3397663/120291907-182e5400-c2c4-11eb-8cf2-3161cb185666.png)

**Comment by MatteoBiscosi** [comment]
Verified as Fixes, please reopen if the problem reappears
