### ISSUE TITLE
Alerts: Restore the wheel icon

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5283]
In the previous alerts implementation the wheel icon was present. In the current one is gone. Possible options
- Restore the icon button
- In the "bell" icon add the ability to disable the alert for all

**Comment by simonemainardi** [comment]
Implemented with the addition of an extra "All" entry under the disable alerts action button

![image](https://user-images.githubusercontent.com/3397663/117132351-092ab380-ada3-11eb-9dcf-72bdb5fdd437.png)
