### ISSUE TITLE
Error in Luaengine 

### ISSUE THREAD

**Issue by ListenNjoy** [ntop/ntopng#5286]
we get this errors after update

ntopng Enterprise M v.4.3.210506 () | 

06/May/2021 08:47:17 [LuaEngineNtop.cpp:47] ERROR ntop_map_score_to_severity : expected number[@pos 1], got nil
06/May/2021 08:47:14 [LuaEngine.cpp:560] WARNING Script failure [/usr/share/ntopng/scripts/callbacks/system/notifications.lua][/usr/share/ntopng/scripts/lua/modules/alert_consts.lua:488: attempt to index a nil value (field '?')]

**Comment by cardigliano** [comment]
Fixed on 8d1edf226e1268c3cfef7273ebbd0ca67b307307, a new package will be available soon
