### ISSUE TITLE
Alert: Reorder columns

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5287]
As described in #5277 there are some columns that must appear all the time Now we define the order
- When
- Alert Type
- Subject (e.g. flow peers for flow alerts)
- all the rest

<img width="1109" alt="Screenshot 2021-05-06 at 10 30 13" src="https://user-images.githubusercontent.com/4493366/117267111-3ab08700-ae56-11eb-8142-f8bbeaa51548.png">

**Comment by simonemainardi** [comment]
order changed as described
