### ISSUE TITLE
Alerts: Graph

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5289]
<img width="1220" alt="Screenshot 2021-05-06 at 10 37 31" src="https://user-images.githubusercontent.com/4493366/117267942-14d7b200-ae57-11eb-82fc-42b82152880f.png">

In case of no data, the alert bar is empty and this is not easy to read. Better to have a chart working this way
- for the reported time see what os the top value (eg. at 10AM you have 4 alerts in total)
- for the time slots where there are no alerts reported, create a light grey bar with value 'top value' that reports "no alert"

**Comment by simonemainardi** [comment]
Barchart has been replaced with a staked area chart
