### ISSUE TITLE
json data non visible on flow read from db

### ISSUE THREAD

**Issue by lucadistefano** [ntop/ntopng#529]
perform a query with historical data explorer and select a flow.
If you try to display the info of the flow you get:

![image](https://cloud.githubusercontent.com/assets/1080723/14743943/a32d61ca-08a4-11e6-8970-904909ffccbb.png)

and you don't see any json data

**Comment by simonemainardi** [comment]
Thanks for reporting. Now lua tables are rendered as strings. Update will be available in the forthcoming nightly build.
