### ISSUE TITLE
Alerts: Add Alerts Report

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5291]
In the upper menu
<img width="964" alt="Screenshot 2021-05-06 at 10 41 30" src="https://user-images.githubusercontent.com/4493366/117268525-a3e4ca00-ae57-11eb-927f-7af7119d274f.png">
add as first item a new entry called "All" (or similar) that regardless of the alert family, shows what is happening on this system. This will be the new default tab

In order not to change the layout it is enough to create a graph with entries based on the family rather than on the severity, nd in the table below common entries such as time, alert type, score... This to show what is happening no all details must be reported and the action menu can be probably removed to simplify things, but adding a HREF for a given alert that jumps you to the right tab. Example if you have a SNMP alert, the HREF will send you to the SNMP tab on the same time period

**Comment by simonemainardi** [comment]
implemented
