### ISSUE TITLE
Alerts: Rework filters

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5292]
The current filter implementation is complex and needs to be simplified. Proposal
- keep using the current approach that when you click on a HREF a new filter entry is added
<img width="190" alt="Screenshot 2021-05-06 at 10 46 50" src="https://user-images.githubusercontent.com/4493366/117269219-62a0ea00-ae58-11eb-9a75-a36ac01151c3.png">
- Add a + icon next to the filter bar for adding a custom filter
- The filter entries will be represented as today or as HTML chips https://mdbootstrap.com/docs/b4/jquery/javascript/tags/
- filter entries cannot be edited inline as today by they can removed (click on the X icon) or edited. The happens with a click on the filter that opens the same page of the "Add Filter"

**Comment by cardigliano** [comment]
Implemented in 2be1108ed03c4d251967e8d3b482d4226a1f3f79 f8cca18ed09b32e976495481cdf0ef6afe6b762b 064c20db29277682d45fd5d4e3a19fac57704c2d f1c343ed832f7c5c1669521c04ff64da630e0acf 30e0bd8675d6047422eac905defd2ae7db8ae9c9 206f1bb6081cbd0a36618d38f1d90ae8e49dcfe6 c8731f5bfac9fd0d423730752d2ad0e9c99db5d2 a635f3677857d3f762174e40d0e9d89fb8f88acc c3dfe67eb517c91470657f03d546d1a2c5dc0cd7
