### ISSUE TITLE
traffic report : VLAN problem

### ISSUE THREAD

**Issue by Rico29** [ntop/ntopng#5294]
Hello
on report.lua page, I only see stuff about one of my vlans. I have no information about other vlans traffic.

I have vlans 50->53 defined
![Sélection_159](https://user-images.githubusercontent.com/12935571/117421222-9f371900-af1e-11eb-8457-9cd2cdd10c42.png)

got flows /hosts for these vlans : 
![Sélection_158](https://user-images.githubusercontent.com/12935571/117421312-b8d86080-af1e-11eb-857c-945af505899a.png)

but I only have detzails for vlan 52 in report.lua page
![Sélection_157](https://user-images.githubusercontent.com/12935571/117421103-80d11d80-af1e-11eb-965a-216035a7e3bd.png)

ntopng version 4.3.210506-14033

Regards
Cédric
(Discord : Rico29)

**Comment by MatteoBiscosi** [comment]
Hi @Rico29 could you please report the screeshot of the data?
You have to right click on the page, click 'Inspect', go into the 'Network' tab and please report the data contained inside the 'get_from_top_talkers_db' preview tab (like the screenshot below).
![Screenshot from 2021-05-07 11-24-12](https://user-images.githubusercontent.com/49585191/117428929-d01b4c00-af26-11eb-95c5-8b2171f8c248.png)
I'm interested into the data contained inside the 'vlan' value, so please send me those data

**Comment by Rico29** [comment]
Hello

Here it is. only vlan 52 :

![Sélection_160](https://user-images.githubusercontent.com/12935571/117430290-466c7e00-af28-11eb-929d-a28c6570c5ac.png)

Regards

Le ven. 7 mai 2021 à 11:25, Matteo Biscosi ***@***.***> a
écrit :

**Comment by Rico29** [comment]
URL is : http://smokeping.adm.celya.fr:3000/lua/pro/get_from_top_talkers_db.lua?ifid=9&epoch=1620380100&num_minutes=60

**Comment by simonemainardi** [comment]
Thanks for reporting. Issue is fixed and will be distributed in the next dev build available tomorrow. Don't forget to let ntopng run for a while as new stats need to be generated.
