### ISSUE TITLE
Strange vlans i Top L7 Contacts

### ISSUE THREAD

**Issue by ListenNjoy** [ntop/ntopng#5296]
Hello

In interface -> graph -> and choosing top L7 contacts there is no client and server data.

And it show a lot of strange VLAN under VLAN tab.

Under Top Client / Top Servers it show the vlans and no hostname

Ntopng Version: ntopng Enterprise M v.4.3.210507 ()

Best Regards

Martin

**Comment by simonemainardi** [comment]
please attach screenshots and the configuration file

**Comment by ListenNjoy** [comment]
![NtopngL7](https://user-images.githubusercontent.com/43986547/117449453-4aa49580-af40-11eb-9609-0ae2adf209fe.jpg)

This is what is change from original ntopng.conf

--local-networks="List of local Network"
 -i=eno1,eno2
 -n=1
 -p=/etc/ntopng/protos.txt
-F nindex

**Comment by ListenNjoy** [comment]
![NtopngTopClients](https://user-images.githubusercontent.com/43986547/117450109-1d0c1c00-af41-11eb-8418-bcc3e9aff060.jpg)

**Comment by MatteoBiscosi** [comment]
Hi @ListenNjoy the issue now is fixed, thanks for you report, builds are in progress wait for a few hours and update, everything should be alright now. Note that soon these page is going to be removed and put into the page 'Dashboard->Historical Flow Explorer'. Reopen the ticket if you seem to find something strange inside the current page.

**Comment by ListenNjoy** [comment]
Thanks
