### ISSUE TITLE
Update error on CentOS come back again

### ISSUE THREAD

**Issue by kfra71** [ntop/ntopng#5297]
We are still facing yum update error while updating on CentOS Linux release 7.9.2009 (Core):

Resolving Dependencies
--> Running transaction check
---> Package cento.x86_64 0:1.13.210506-667 will be updated
---> Package cento.x86_64 0:1.13.210507-668 will be an update
---> Package n2disk.x86_64 0:3.7.210506-5311 will be updated
---> Package n2disk.x86_64 0:3.7.210507-5311 will be an update
---> Package ndpi.x86_64 0:3.5.0-3151 will be updated
--> Processing Dependency: ndpi = 3.5.0-3151 for package: pfring-7.9.0-3409.x86_64
---> Package ndpi.x86_64 0:3.5.0-3154 will be an update
---> Package nprobe.x86_64 0:9.5.210506-7271 will be updated
---> Package nprobe.x86_64 0:9.5.210507-7271 will be an update
---> Package ntopng-data.noarch 0:4.3.210503-13349 will be updated
---> Package ntopng-data.noarch 0:4.3.210507-13446 will be an update
--> Finished Dependency Resolution
Error: Package: pfring-7.9.0-3409.x86_64 (@ntop)
           Requires: ndpi = 3.5.0-3151
           Removing: ndpi-3.5.0-3151.x86_64 (@ntop)
               ndpi = 3.5.0-3151
           Updated By: ndpi-3.5.0-3154.x86_64 (ntop)
               ndpi = 3.5.0-3154
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by cardigliano** [comment]
In order to fix this once and for all we need to make the pfring version change on ndpi version change (or add the date to the version), as the installed pfring version depends on an older ndpi version. As workaround a pfring updated should be forced (removing and reinstalling it).

**Comment by cardigliano** [comment]
@kfra71 this has been addressed, it should no longer happen, please update
