### ISSUE TITLE
Request: provide SSL cipher information while exporting flows  

### ISSUE THREAD

**Issue by James-LA** [ntop/ntopng#530]
Currently, nprobe is unable to tell us which ciphers the user is utilizing when utilizing ssl, nprobe would have a great value added feature by adding the ability to provide which ciphers the client is using at the time.  this would allow admins to be able to force upgrades or even lock down weak ciphers or just for reporting purposes and security purposes which ciphers are being used.

**Comment by lucaderi** [comment]
Please move this request to nDPI.
