### ISSUE TITLE
Alerts: Missing Victim and Attacker Columns

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5302]
The alert subsystem stores in the DB the IP address of the victims and attackers. They MUST be reported in the user interface in both the flow and the host pages. If unknown these two columns must be left empty

**Comment by simonemainardi** [comment]
Just by looking at the code, it is very likely that this implementation hasn't been tested. Simply look at the data types. Please, test and resubmit.

**Comment by MatteoBiscosi** [comment]
Unified attacker and victim columns into host alerts as requested but maintained them separated into flow alerts due to readability issues

**Comment by lucaderi** [comment]
Columns are not sortable, please implement it

**Comment by lucaderi** [comment]
Reopen as of #5337

**Comment by simonemainardi** [comment]
With the new filters it may be beneficial for the sake of layout and space to remove the two columns and have them available as filters as discussed with @cardigliano. Please, consider this.

**Comment by lucaderi** [comment]
![Screen Shot 2021-05-17 at 22 49 36](https://user-images.githubusercontent.com/4493366/118554791-2e83ce00-b762-11eb-92a3-fcbe592f6a26.png)
This ticket is still open

**Comment by lucaderi** [comment]
<img width="865" alt="Screenshot 2021-05-25 at 10 18 53" src="https://user-images.githubusercontent.com/4493366/119464058-ae053480-bd42-11eb-8f99-8ad4618042fc.png">


It is requested to change the filter is
- Has attacker
- Has Victim
- No attacker nor victim

**Comment by lucaderi** [comment]
The attacker/victim columns can be removed
