### ISSUE TITLE
Alerts documentation is out of sync

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5303]
The alert documentation has not been updated wince the Lua to C++ migration

**Comment by simonemainardi** [comment]
@MatteoBiscosi please document the dangerous host and the host ban.

**Comment by simonemainardi** [comment]
Documentation updated in https://github.com/ntop/ntopng/commit/0bc1eb97d02d0c91655e02485daf3a325ef3e27c and subsequent commits
