### ISSUE TITLE
nTop (4.2-stable) installed on a VM and nProbe (9.2-stable) installed on a different VM

### ISSUE THREAD

**Issue by sercopi135** [ntop/ntopng#5305]
Hi all,

I writing you to try to solve a problem related to not receiving traffic on nTop, sended by a nProbe in production with the option 
--collector-port.

nTop and nProbe are installed on two different Virtual Machines.

With tcpdump on nProbe, I can receive netflow sended by a switch.

From the nProbe I can telnet the tcp/5556 port, related to nTop where it listen, but if I open the nTop WEB GUI I cannot see any data coming to nTop, as if a do a tcpdump on nTop searching packet from the nProbe machine o direct to port 5556.

The port tcp/5556 from netstat -an, is correctly UP on my nTop machine.

### ntopng.conf

G=/var/run/ntopng.pid
-i=tcp://*:5556c
-w=3001
-n=1

### nprobe.conf

-i=none
--collector-port=6363
--zmq=tcp://10.161.74.10:5556
--zmq-probe-mode
-n=none
-T=@NTOPNG@
-G=/var/run/nprobe.pid

Can you help me?

Best Regards

**Comment by simonemainardi** [comment]
visit the ntopng stats page, and check for received ZMQ messages. Do you see them increasing?

**Comment by simonemainardi** [comment]
No feedback received, closing. Reopen with the requested information if necessary.
