### ISSUE TITLE
Alert badges not supporting multitenancy

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5306]
Multitenancy support is partially broken with alarm badges. As you can see in the picture below, there are some alerts reported that instead should be hidden to the selected user.

![Screen Shot 2021-05-10 at 19 12 46](https://user-images.githubusercontent.com/4493366/117698232-c95d3500-b1c3-11eb-85b8-0a5800e1fb63.png)

This is a regression of #3210

**Comment by simonemainardi** [comment]
Resolved as described https://github.com/ntop/ntopng/issues/5324#issuecomment-848020044

The alerts page (and the top red-badge with the engaged alerts counter) are now accessible (and with consistent values) for admins and local unprivileged users that don't have allowed networks.
