### ISSUE TITLE
Non privileged users should not be able to delete alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5307]
Unprivileged users should not be able to delete alerts nor the delete alert button should be shown on the web interface

**Comment by simonemainardi** [comment]
This is broken. Delete has disappeared also for admins


![image](https://user-images.githubusercontent.com/3397663/117857700-57e9b900-b28d-11eb-835e-59a12973ee4d.png)

**Comment by lucaderi** [comment]
Verified as fixed
