### ISSUE TITLE
Alert report does not support multi tenancy 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5309]
![Screen Shot 2021-05-10 at 19 18 38](https://user-images.githubusercontent.com/4493366/117698951-8fd8f980-b1c4-11eb-8fee-4155c8b6d2b6.png)

A user who is restricted to selected hosts (in the user preferences page) is able to see alerts he's not supposed to see.

This is a regression of #3210. I believe the REST API is also bugged.

**Comment by simonemainardi** [comment]
Implemented in https://github.com/ntop/ntopng/commit/0855f627a045decf22d2f8b5687f289816999774

Implementation described in https://github.com/ntop/ntopng/issues/5324#issuecomment-848020044
