### ISSUE TITLE
Latest version?

### ISSUE THREAD

**Issue by yurivict** [ntop/ntopng#531]
I would like to create/update the FreeBSD port. However it isn't obvious (to me) what the latest version is.

The latest FreeBSD port version is ntop-5.0.1 from sourceforge. Arch takes ntopng-2.2 from sourceforge.

Could you please add the note to the README what the latest recommended version is (or just make a release)?

**Comment by lucaderi** [comment]
@yurivict Thanks for contacting us. Please note that there is a similar ongoing activity https://github.com/ntop/ntopng/issues/297 @madpilot78

ntop is EOL. Please use the latest development code you find here on github (dev branch).
