### ISSUE TITLE
Attacker/Victims are not Working as Expected

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5310]
Attacker and victims fields don't seem to be populated properly. As you can see in the picture below they are all empty. See for instance

![image](https://user-images.githubusercontent.com/4493366/117699684-6a002480-b1c5-11eb-9864-1eb6ca88c3f7.png)

and compare it with

![Screen Shot 2021-05-10 at 19 26 42](https://user-images.githubusercontent.com/4493366/117699953-b6e3fb00-b1c5-11eb-99f7-87ed986906c5.png)

This ticket depends on #5302

**Comment by lucaderi** [comment]
Said that it is necessary to have some automatic regression tests, the implementation seems to have problems. You can check with the enclosed file. Fruthermore column names take too much space. 
[Petya_Failed_SMB_Auth_ETERNALBLUE_attempt.pcap.gz](https://github.com/ntop/ntopng/files/6462034/Petya_Failed_SMB_Auth_ETERNALBLUE_attempt.pcap.gz)

**Comment by simonemainardi** [comment]
Attacker/victim has been reworked and completed, also using the pcap provided. See, for example:

![image](https://user-images.githubusercontent.com/3397663/120004541-2edc5e80-bfd7-11eb-97e7-203978a9c80b.png)

Can also filter by attacker / victim as:

![image](https://user-images.githubusercontent.com/3397663/120004621-47e50f80-bfd7-11eb-8086-bddca60444b7.png)

![image](https://user-images.githubusercontent.com/3397663/120004657-50d5e100-bfd7-11eb-8c1f-9cdd5ce7a3c0.png)
