### ISSUE TITLE
Alerts do not report the exact problem detected

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5316]
Alert description is way to short and it does not explains many things. Example see this alert
![Screen Shot 2021-05-11 at 09 50 04](https://user-images.githubusercontent.com/4493366/117780923-61006900-b240-11eb-8320-14dfaf3ae092.png)

this is not an alert just about a suspicious file transfer as it also has various other problems to report as shown in the flow breakdown.

![Screen Shot 2021-05-11 at 09 49 39](https://user-images.githubusercontent.com/4493366/117780928-62ca2c80-b240-11eb-8470-e90aadd22bad.png)

Without creating long descriptions hard to fit on a small screen, it is request to at least specify the score breakdown. Possible solutions:
- Suspicious File Transfer[... file]  (score 256) and additional issues (score 300)
- Suspicious File Transfer [... file], HTTP Numeric IP Host,.....

**Comment by ListenNjoy** [comment]
Is it possible to allow ex. windowsupdate domain name to allow sending suspicious traffic, i can only set IP-Address in actions and Windows update uses a lot of different IP-adresses   .

**Comment by simonemainardi** [comment]
Implemented. Now all alerts carry not only the predominant alert, but all the issues detected for the flow. All those issues are shown in a spillover column

![image](https://user-images.githubusercontent.com/3397663/118135352-3579ac00-b403-11eb-9203-4f927c63b52f.png)
