### ISSUE TITLE
Sort alert by desription / Type

### ISSUE THREAD

**Issue by ListenNjoy** [ntop/ntopng#5319]
I miss sorting out alert by choosing to click type and ex. threshold cross to view only those alerts.

Ntopn version: ntopng Enterprise M v.4.3.210511

Picture of old version
![NtopngAlertType](https://user-images.githubusercontent.com/43986547/117835894-85783780-b278-11eb-92ae-c4cd7c198886.jpg)

**Comment by simonemainardi** [comment]
duplicate of https://github.com/ntop/ntopng/issues/5206
