### ISSUE TITLE
Use alert endpoint validation for email fields part two

### ISSUE THREAD

**Issue by KFDCompiled** [ntop/ntopng#5321]
Similar to #3910 , email validation fails if there is a numeral in the domain name:

![recipient](https://user-images.githubusercontent.com/13281971/117876156-43db9280-b260-11eb-9f83-ffe31549a320.png)
![endpoint](https://user-images.githubusercontent.com/13281971/117876165-45a55600-b260-11eb-9977-159bb5f8596c.PNG)

**Comment by MatteoBiscosi** [comment]
Hi @KFDCompiled could you please report your ntopng version?

**Comment by KFDCompiled** [comment]
4.2.d20210309

**Comment by lucaderi** [comment]
This ticket is already fixed on the stable branch. Please update and reopen the ticket if necessary
