### ISSUE TITLE
How to display host Sites?

### ISSUE THREAD

**Issue by OzSpots-Wireless** [ntop/ntopng#5323]
![image](https://user-images.githubusercontent.com/5474756/117894430-a637a000-b2ff-11eb-8748-a5b2869f9670.png)

Sites is missing on 4.3 (running on pfsense KVM virtio interface )

If I click on the JSON, it does show sites visited.

**Comment by OzSpots-Wireless** [comment]
I just installed another with the 10minute full version and it shows Sites. When I add the --community flag, sites is no longer visable...

**Comment by simonemainardi** [comment]
sites is a pro-only feature

**Comment by OzSpots-Wireless** [comment]
thanks, I figured that but can't find it stated anywhere

and the version comparison states this is included:
`Visualize the top HTTP sites contacted by an host
`
Which we can't do with only the Top hosts page.

**Comment by simonemainardi** [comment]
HTTP is available in community, too. It's a different feature.
