### ISSUE TITLE
Implement multi-tenancy for alerts

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5324]
ntopng supports user-capabilities a la linux, see `auth.lua`

Basically, each non-admin user has a bitmap of do-s and dont-s. 

Currently, the bitmap is an all do-s with all 1s. However, the code already supports it, e.g.,:

```
scripts/lua/rest/v1/reset/notifications/config.lua:if not auth.has_capability(auth.capabilities.notifications) then
scripts/lua/rest/v1/reset/pool/config.lua:if not auth.has_capability(auth.capabilities.pools) then
scripts/lua/rest/v1/reset/scripts/config.lua:if not auth.has_capability(auth.capabilities.user_scripts) then
scripts/lua/rest/v1/reset/snmp/config.lua:if not auth.has_capability(auth.capabilities.snmp) then
scripts/lua/rest/v1/reset/active_monitoring/config.lua:if not auth.has_capability(auth.capabilities.active_monitoring) then
```

I would add an 'alerts' capability for-admin users, conditionally allowing them to browse alerts. This approach is simple and easier to maintain if compared to other approaches that would alter the alerts database structure. However, it will be binary, in the sense that a user will be able to see all or any of the alerts.

Implementing finer-grained approaches today can be done with recipients, e.g., send alerts of pool X to recipient Y. This can also be extended with the already discussed concept of per-flow-pool.

For the UI configuration, a toggle can be added to the users configuration and creation page that sets this capability. The same can be done for historical nindex flows.

**Comment by simonemainardi** [comment]
@cardigliano @lucaderi please review the following possible solutions

![image](https://user-images.githubusercontent.com/3397663/118304350-dbeaad80-b4e6-11eb-85b4-444bd213813a.png)

**Comment by lucaderi** [comment]
The first thing to fix is to avoid non-admin users to see alerts they should not care about. Better not to see anything than all

**Comment by lucaderi** [comment]
We decided that further developments will be scheduled when supporting this feature will be required. For the time being non-local administrator users will not be able to see alerts and flows.

**Comment by simonemainardi** [comment]
Implementation has been done using capabilities. The `alerts` capability bit is set for admins and local unprivileged users that don't have allowed networks.

This approach allows local unprivileged users that don't have restrictions on networks to access alerts.

As no assumption can be done on remote (e.g., Radius, LDAP) unprivileged users, for them alerts are always non-visible.

**Comment by simonemainardi** [comment]
As agreed on discord (message https://discord.com/channels/726054161547919440/726060121905561671/846794949738365037)  capabilities have been used also for historical flows and this issue can be closed.
