### ISSUE TITLE
HTTP/1.1 302 Found Server: ntopng 4.3.210514

### ISSUE THREAD

**Issue by tomkolp** [ntop/ntopng#5327]
![image](https://user-images.githubusercontent.com/39633242/118233851-cea3d380-b492-11eb-94a4-66f80fd2e858.png)

**Comment by lucaderi** [comment]
What platform/distribution are you using?

**Comment by tomkolp** [comment]
> What platform/distribution are you using?

Opnsense

**Comment by cardigliano** [comment]
@tomkolp this has been fixed already, a package update will be available later today
