### ISSUE TITLE
Adding a title in the main dashboard

### ISSUE THREAD

**Issue by olg33** [ntop/ntopng#5328]
This is just a question.

When opening ntopng main page, we are presented with the dashboard and a graph with the Top Flow Talkers. I'd like to know if there is a way to add a title with the name of the location or the node being monitored. It could be useful for technical reports or to avoid confusion when several locations are opened in the same monitor. 

Thank you.

**Comment by simonemainardi** [comment]
Can you please articulate more and add screenshots? Why do the interface name isn't enough?

**Comment by olg33** [comment]
Sure, 
The main dashboard normally looks like this:

![Capture2](https://user-images.githubusercontent.com/61751672/118307406-a5963980-b4b8-11eb-8ff0-686687eeb687.JPG)

We have a Network Operations Center (NOC) where charts from different sites are displayed in several monitors. If those charts don't have a title or description it's hard to tell for an operator where is the chart for a specific node or location.

If the chart had a description anywhere in the screen  like this:

![Capture](https://user-images.githubusercontent.com/61751672/118307813-3240f780-b4b9-11eb-9791-60ca3f770c64.JPG)
 
Things could be easier for everyone. That's why I was looking for a command that could add a customized description of the main dashboard.

**Comment by simonemainardi** [comment]
why don't you assign an alias to the disaggregated interface to specify the site name? I believe this will do what you are looking for without adding extra items on the UI.

**Comment by olg33** [comment]
Sure, there are alternative ways to tackle this request. I just wanted to know whether there is an option to add that title to the dashboard. If not, then I can think about a "Plan B"
