### ISSUE TITLE
Flow alert score is cryptic

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5331]
![Screen Shot 2021-05-15 at 09 33 13](https://user-images.githubusercontent.com/4493366/118352241-a4b8e280-b560-11eb-8ac4-bcead5908202.png)

As shown in the example below, the alert score is the sum of the individual issues but this is not clear from the GUI. It is requested to show the value of the individual issues so that it is clear how the total score is calculated

**Comment by simonemainardi** [comment]
This is not just an UI-related issue. This involves reworking the alerts engine as currently the flow score is maintained as follows:

- the total flow score
- the score for the 'main flow alert'
- a score breakdown per category (e.g., security, network, etc).

Indeed, the original agreed project was to keep the score breakdown not for individual issues but for categories (e.g, security, network, etc). This to avoid using too much memory. @lucaderi, confirm you want the score kept on a per-issue basis so we can prepare and share a project for approval.

**Comment by lucaderi** [comment]
This ticket depends on #5402

**Comment by lucaderi** [comment]
Comments
- harmonise terms: risk, issue....
- there is no main and other alert. This is an alert
- (if possible) make the alert an hyperlink so we can jump onto the alert page
- (if possible) explain how the flow score is computed (breakdown)

**Comment by simonemainardi** [comment]
> harmonise terms: risk, issue....
> there is no main and other alert. This is an alert

- Terms harmonized
- Alert is just one
- Other alerts are just referred to as issues

![image](https://user-images.githubusercontent.com/3397663/119665777-01f04600-be35-11eb-9aa6-b180b3f5c91f.png)

> (if possible) make the alert an hyperlink so we can jump onto the alert page

No additional value comes from adding an hyperlink to the alert page. This page is a superset of the alert, all the information is here

> (if possible) explain how the flow score is computed (breakdown)

As explained in https://github.com/ntop/ntopng/issues/5331#issuecomment-841871828 we can't show the score contributions of individual issues to the overall score. However, now the flow alert has a "Score contribution" indication that shows its contribution to the score.
