### ISSUE TITLE
When a computer is shut down, ntop cannot track the computer's past traffic usage

### ISSUE THREAD

**Issue by Iamyourbaba** [ntop/ntopng#5332]
When a computer is shut down, ntop cannot track the computer's past traffic usage

**Comment by simonemainardi** [comment]
Please articulate this. What do you mean with past traffic usage?

**Comment by Iamyourbaba** [comment]
I have two computers, each of which is connected to a different ip network. When one of my computers connects to the server I need to monitor and shuts down after a period of time, my other computer cannot view the server traffic used by the shut down computer in the background.

**Comment by simonemainardi** [comment]
Historical traffic data is available (even when a computer is off and no longer generating traffic):

- Via traffic Report (https://www.ntop.org/guides/ntopng/web_gui/report.html)
- Activity Report (https://www.ntop.org/guides/ntopng/web_gui/report.html#activity-report)
- Historical flows with nIndex (https://www.ntop.org/guides/ntopng/advanced_features/flows_dump.html#nindex)

You can also configure timeouts to keep hosts active inside ntopng for more when they go offline. You can tune this with:

![image](https://user-images.githubusercontent.com/3397663/120161880-1ac37780-c1f8-11eb-844a-182f0293b6ee.png)
