### ISSUE TITLE
Score Anomaly Alert is Incomplete 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5333]
![image](https://user-images.githubusercontent.com/4493366/118357466-a55e7280-b57a-11eb-879a-b37e58c6e140.png)

The above alert must report if the issue is in the client or in the server score. As it is today it is useless

**Comment by simonemainardi** [comment]
This is not going to work when localization is used https://github.com/ntop/ntopng/commit/fdf8fbadb8e77f7da060dc4e66c56774d3ebaec3#diff-776ded5a544d774d9ae5a2377a842c592f735acc9de4a8b4bec29d6b415abf12R56

**Comment by MatteoBiscosi** [comment]
Added string localization as requested, please reopen if the problem persists
