### ISSUE TITLE
Enhance Alert Hyperlinks

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5334]
![Screen Shot 2021-05-15 at 12 41 17](https://user-images.githubusercontent.com/4493366/118357517-dccd1f00-b57a-11eb-8c70-03d969da7df0.png)

In the table above, add a hyperlink on the coloured numbers so we can jump immediately (in one click) to the filtered alerts. Example in the above picture to the error or warnign host alerts.

**Comment by simonemainardi** [comment]
Before implementing this, we should change/extend filters to also include > and <, not just the =.

**Comment by lucaderi** [comment]
If there is a dependency open a ticket and reference it. Just replace the yellow warning number with a hyperlink, and so on for all the others

**Comment by cardigliano** [comment]
Implemented
