### ISSUE TITLE
Enhance Score Anomaly Alert

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5339]
![image](https://user-images.githubusercontent.com/4493366/118358383-d17bf280-b57e-11eb-8c1d-b74e920155e3.png)

In the above picture, we see that there is an anomaly for the score of a given host. Going inside the host detail page it is possible to observe the score breakdown that enables us to understand what is the nature of the problem

![Screen Shot 2021-05-15 at 13 09 07](https://user-images.githubusercontent.com/4493366/118358390-d771d380-b57e-11eb-83d0-4cd4af299a1a.png)

It is requested to report the host score breakdown (client score for client score anomaly, server score for server score anomaly) so that we can understand the nature of the problem.

**Comment by simonemainardi** [comment]
Please elaborate more your request.

Note that the score in the alert (50) is the only score relative to the "Score anomaly issue", whereas the host score breakdown shown in the other screenshot is the overall host score, which includes:

- all engaged host alerts
- all flow alerts involving the host either as client or server

**Comment by lucaderi** [comment]
Not sure what has been fixed. See the picture below
![Screen Shot 2021-05-17 at 22 51 38](https://user-images.githubusercontent.com/4493366/118555062-815d8580-b762-11eb-98e1-cda2daa69907.png)
![Screen Shot 2021-05-17 at 22 49 36](https://user-images.githubusercontent.com/4493366/118555064-81f61c00-b762-11eb-96bb-979dd1999528.png)

You can reproduce it with ntopng -i ~/network/nDPI/tests/pcap/exe_download_as_png.pcap

**Comment by simonemainardi** [comment]
Both peers are now recognized as attackers (one is fetching an the other is serving a suspicious file)

![image](https://user-images.githubusercontent.com/3397663/120005078-c5108480-bfd7-11eb-846c-e9736a54662a.png)

Inside the flow details page you now get the 'Alert' with its contribution towards the total score (along with the other issues)

![image](https://user-images.githubusercontent.com/3397663/120005171-e2455300-bfd7-11eb-9e4e-3d121df47001.png)

The meaning of the various fields and why it has been decided to implement them as shown in the picture is discussed and explained at https://github.com/ntop/ntopng/issues/5331#issuecomment-848762960
