### ISSUE TITLE
Incompatibilità apache 2.4.6 e nbox

### ISSUE THREAD

**Issue by steste640** [ntop/ntopng#534]
After an apache 2 update from version 2.2 to 2.4 NBOX on port 80 he has stopped responding.
While on port 3000 ntopng meets regularly if you try to start the apache server that responds:
NameVirtualHost has no effect and will be removed in the next release
/etc/httpd/conf.d/nbox.conf

Dopo un'aggiornamento di apahce 2 dalla versione 2.2 alla 2.4 nbox sulla porta 80 ha cessato di rispondere.
Mentre sulla porta 3000 ntopng risponde regolarmente se si tenta di avviare il server apache questo risponde:
NameVirtualHost has no effect and will be removed in the next release
/etc/httpd/conf.d/nbox.conf

**Comment by ValentinaViscarelli** [comment]
Please after updating of httpd to 2.4 version please remove and install again nbox.
So run these commands:
- yum remove nbox
- yum install nbox

If you have problem with gpg keys add --nogpgcheck
yum install --nogpgcheck nbox

This should fix your problem. Let us know.

**Comment by steste640** [comment]
After reinstalling NBOX now the apache server start. On port 80 no the NBOX screen appears. At the start the httpd server by this error but is started.
systemd: Starting the Apache httpd server .....
httpd: AH00548: namevirtualHosts has no effect and will be removed in the next release /etc/httpd/conf.d/nbox.conf:1
Started the apache http server

**Comment by ValentinaViscarelli** [comment]
The error you reported isn't an error, but it is just a warning. I also have this warning but it works for me.
Said that, please send me  the output output these commands:
- ls /ect/httpd/conf.d
- systemctl status httpd

**Comment by steste640** [comment]
1
[root@ntop conf.d]# ls
autoindex.conf  manual.conf  nbox.conf.rpmsave  nbox.ssl.conf.rpmsave  README            userdir.conf
fcgid.conf      nbox.conf    nbox.ssl.conf      phpMyAdmin.conf        ssl.conf.disable  welcome.conf.disable

2
[root@ntop conf.d]# systemctl status httpd.service
● httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
   Active: active (running) since sab 2016-04-30 14:46:14 CEST; 6s ago
     Docs: man:httpd(8)
           man:apachectl(8)
  Process: 5434 ExecStop=/bin/kill -WINCH ${MAINPID} (code=exited, status=0/SUCCESS)
 Main PID: 5444 (httpd)
   Status: "Processing requests..."
   CGroup: /system.slice/httpd.service
           ├─5444 /usr/sbin/httpd -DFOREGROUND
           ├─5445 /usr/sbin/httpd -DFOREGROUND
           ├─5446 /usr/sbin/httpd -DFOREGROUND
           ├─5447 /usr/sbin/httpd -DFOREGROUND
           ├─5448 /usr/sbin/httpd -DFOREGROUND
           ├─5449 /usr/sbin/httpd -DFOREGROUND
           └─5450 /usr/sbin/httpd -DFOREGROUND

apr 30 14:46:13 ntop.lunilicei.it systemd[1]: Starting The Apache HTTP Server...
apr 30 14:46:13 ntop.lunilicei.it httpd[5444]: AH00548: NameVirtualHost has no effect and will be removed in the next release /etc/http....conf:4
apr 30 14:46:14 ntop.lunilicei.it systemd[1]: Started The Apache HTTP Server.
Hint: Some lines were ellipsized, use -l to show in full.
[root@ntop conf.d]# 

3 port 80 ipv4 not listen
[root@ntop conf.d]# netstat -anp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name  
tcp        0      0 127.0.0.1:6379          0.0.0.0:\*               LISTEN      893/redis-server 12 
tcp        0      0 127.0.0.1:5556          0.0.0.0:\*               LISTEN      2190/nprobe  
tcp        0      0 0.0.0.0:22              0.0.0.0:\*               LISTEN      892/sshd  
tcp        0      0 0.0.0.0:3000            0.0.0.0:\*               LISTEN      948/ntopng  
tcp        0      0 127.0.0.1:25            0.0.0.0:\*               LISTEN      1571/master  
tcp        0      0 0.0.0.0:3001            0.0.0.0:\*               LISTEN      948/ntopng  
tcp        0      0 127.0.0.1:199           0.0.0.0:\*               LISTEN      881/snmpd  
tcp        0      0 127.0.0.1:36504         127.0.0.1:6379          ESTABLISHED 948/ntopng  
tcp        0      0 172.30.0.230:56698      8.8.8.8:53              ESTABLISHED 948/ntopng  
tcp        0      0 172.30.0.230:22         172.30.0.248:39048      ESTABLISHED 5338/sshd: root@pts 
tcp        0      0 172.30.0.230:56691      8.8.8.8:53              ESTABLISHED 948/ntopng  
tcp        0      0 127.0.0.1:45417         127.0.0.1:5556          ESTABLISHED 948/ntopng  
tcp        0      0 127.0.0.1:6379          127.0.0.1:36504         ESTABLISHED 893/redis-server 12 
tcp        0      0 172.30.0.230:41057      172.30.0.240:3306       ESTABLISHED 948/ntopng  
tcp        0      0 127.0.0.1:5556          127.0.0.1:45417         ESTABLISHED 2190/nprobe  
tcp6       0      0 :::80                   :::\*                    LISTEN      5444/httpd  
tcp6       0      0 :::22                   :::\*                    LISTEN      892/sshd  
tcp6       0      0 ::1:25                  :::\*                    LISTEN      1571/master  
tcp6       0      0 :::443                  :::\*                    LISTEN      5444/httpd  
udp        0      0 0.0.0.0:53237           0.0.0.0:\*                           2190/nprobe  
udp        0      0 0.0.0.0:161             0.0.0.0:\*                           881/snmpd  
udp        0      0 0.0.0.0:6343            0.0.0.0:\*                           2190/nprobe  
udp        0      0 127.0.0.1:323           0.0.0.0:\*                           600/chronyd  
udp6       0      0 :::6343                 :::\*                                2190/nprobe  
udp6       0      0 ::1:323                 :::\*                                600/chronyd

**Comment by ValentinaViscarelli** [comment]
I see that apache is running properly but I also see you have other .conf file that could be in conflict with nbox on http (port 80) for example (please read README file in /etc/httpd/conf.d folder to understand how apache load the configuration file):

manual.conf
fcgid.conf
phpMyAdmin.conf

When you install apache configuration you should check for conflict.
Anyway you can try to use https (in fact http is just a redirection on https). So try to use https://localhost (if you are in the same machine). If doesn't work try to do rename .conf file in order to disable them and restart apache:

sudo mv manual.conf manual.conf.disable
sudo mv fcgid.conf fcgid.conf.disable
sudo mv phpMyAdmin.conf phpMyAdmin.conf.disable
sudo systemctl restart httpd

**Comment by ValentinaViscarelli** [comment]
@steste640 
Sorry but I didn't understand if nbox properly works on port 80.
Does it work?

**Comment by steste640** [comment]
No, the door 80 does not reach any page. Instead the 3000 ntop works.

**Comment by steste640** [comment]
The problem was that httpd worked default in ipv6.
I modified nbox.conf
Listen 80
in
Listen 0.0.0.0:80

and nbox.ssl.conf
Listen 443
in
Listen 0.0.0.0:443
Now the server listens on ports but does not reach any page.
In that say the web pages NBOX located?

**Comment by steste640** [comment]
[Sat Apr 30 18:27:47.742001 2016] [ssl:warn] [pid 13762] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]

**Comment by ValentinaViscarelli** [comment]
@steste640 
I see you have other .conf file that could be in conflict with nbox on http (port 80) for example:

manual.conf
fcgid.conf
phpMyAdmin.conf

We configure port 80 just to do a redirection on 443 port. Actually the real nbox site goes on https protocol. So first of all try to access directly with https (for example https://locahost if you are in the same machine).

If this doesn't  work please run these command and try again:

cd /etc/httpd/conf.d
sudo mv manual.conf manual.conf.disable
sudo mv fcgid.conf fcgid.conf.disable
sudo mv phpMyAdmin.conf phpMyAdmin.conf.disable
sudo systemctl restart httpd

**Comment by steste640** [comment]
All .conf disable.
Not work. No conflict in port 80. No page send from port 80. No page send from port 443

**Comment by steste640** [comment]
Ok Ok work!!!! Modify the file ntop.conf in /etc/httpd/conf.d/ntop.conf

COMMENT NameVirtualHost *:80
#NameVirtualHost *:80
<VirtualHost *:80>
        ServerAdmin webmaster@localhost

```
    DocumentRoot /var/ntop/www

    # This will enable the Rewrite capabilities
    RewriteEngine On

    # This checks to make sure the connection is not already HTTPS
    RewriteCond %{HTTPS} !=on

    # This rule will redirect users from their original location, to the same location but using HTTPS.
    RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R=301,L]

    ErrorLog logs/error.log

    # Possible values include: debug, info, notice, warn, error, crit,
    # alert, emerg.
    LogLevel warn

    CustomLog logs/access.log combined
```

</VirtualHost>

**Comment by ValentinaViscarelli** [comment]
Resolved.
