### ISSUE TITLE
Multicast/Broadcast and Remote

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5340]
![Screen Shot 2021-05-15 at 17 17 49](https://user-images.githubusercontent.com/4493366/118368069-86270b80-b5a1-11eb-8f11-10b519369fda.png)

![Screen Shot 2021-05-15 at 17 23 49](https://user-images.githubusercontent.com/4493366/118368399-56c4ce80-b5a2-11eb-9230-34b53b386044.png)

By definition, only unicast address can be remote. all others (broad and multicast, including NoIP/0.0.0.0) are always local

**Comment by simonemainardi** [comment]
Default local and private networks are defined in the following constants:

```
#define CONST_DEFAULT_PRIVATE_NETS     "192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,127.0.0.0/8,169.254.0.0/16"
#define CONST_DEFAULT_LOCAL_NETS       "127.0.0.0/8,fe80::/10"
#define CONST_DEFAULT_ALL_NETS         "0.0.0.0/0,::/0"
```

Please, update them accordingly as indicated by @lucaderi
