### ISSUE TITLE
Table Views and Icons/Signs

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5341]
In host breakdown, we can show all the icons/signs that are available including broadcast domain, or private vs local IP.

In tables such as alerts, hosts, flows (see the picture below) only relevant icons must be displayed to avoid confusing the user. In this case leave only: country flag, local/remote/multicast

![Screen Shot 2021-05-15 at 17 19 59](https://user-images.githubusercontent.com/4493366/118368139-d2724b80-b5a1-11eb-91c6-ee9734577b38.png)

**Comment by simonemainardi** [comment]
@MatteoBiscosi you have already implemented a format function for flow alerts that already hides most of the icons. I believe you should use that function across the whole UI as explained by @lucaderi.

**Comment by lucaderi** [comment]
Seems to work
