### ISSUE TITLE
Aggregate results on top talkers within date interval

### ISSUE THREAD

**Issue by dimkar121** [ntop/ntopng#5344]
Hallo,

I am wondering if there exists any way to receive aggregate results on top talkers within a certain date interval (as the alerts).

thanks in advance,
Dimitrios

**Comment by simonemainardi** [comment]
yes, this is available in the traffic report (pro version).

You select the time range of interest

![image](https://user-images.githubusercontent.com/3397663/119635284-d315a800-be13-11eb-805d-a5749b807783.png)

Then talkers become available as part of the report

![image](https://user-images.githubusercontent.com/3397663/119635578-1ec85180-be14-11eb-84f2-ea1240b878df.png)


You also have top- apps, senders and receivers under any chart for the time interval of interest

 
![image](https://user-images.githubusercontent.com/3397663/119635478-05bfa080-be14-11eb-8908-457fa24d4b08.png)
