### ISSUE TITLE
BT5: Time preset dropdown not working

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5345]
![Screen Shot 2021-05-17 at 13 13 37](https://user-images.githubusercontent.com/4493366/118479873-d329ef80-b711-11eb-8d80-f60f267624e4.png)

**Comment by gabryon99** [comment]
Verified as fixed. See the image below:
<img width="951" alt="Screenshot 2021-05-19 at 12 20 07" src="https://user-images.githubusercontent.com/14114916/118797133-8e7e8f80-b89c-11eb-98d5-e469cabd626d.png">
