### ISSUE TITLE
SQL Alert Error

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5349]
17/May/2021 13:51:02 [AlertStore.cpp:131] ERROR: SQL Error: CHECK constraint failed: interface_alerts
INSERT INTO interface_alerts (alert_id, tstamp, tstamp_end, severity, score, ifid, name, alias, granularity, json) VALUES (4128, 1621252201, 1621252261, 5, 100, -1, '', '', 60, '{"alert_generation":{"script_key":"slow_periodic_activity","subdir":"system"},"ps_name":"second.lua","max_duration_ms":2000}');

**Comment by cardigliano** [comment]
This looks like an issue we fixed a few days ago (ifid = -1 was out of range in the DB schema definition)

**Comment by lucaderi** [comment]
The code is updated so there is still something wrong happening

**Comment by simonemainardi** [comment]
![image](https://user-images.githubusercontent.com/3397663/118622828-f616db00-b7c7-11eb-8a94-e0ed242135ba.png)
