### ISSUE TITLE
Hide encryption key from the user interface

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5350]
![Screen Shot 2021-05-17 at 15 12 45](https://user-images.githubusercontent.com/4493366/118546843-cf6d8b80-b758-11eb-9a27-614bcdb988b9.png)

For privacy reasons, it is requested to hide the encryption key and add a button that allows the key to be copied in the clipboard.

**Comment by MatteoBiscosi** [comment]
Verified as fixed

**Comment by simonemainardi** [comment]
- Non-admins must not be able to copy the encryption key - the encryption key must not be rendered at all for non-admins
- This is not a string to be localized https://github.com/ntop/ntopng/commit/151a5d2a18d1ecc8fb7150fad24bb555ecedbdc1#diff-1013beffca0e3b562dbb8d3f329f89aa78b46a546d8ca9beda2f7343ffbbc721R3036
- The hidden key says `ifstats.encryption.public_key` but by definition a `public_key` is public so I am not sure why it needs to be hidden.

**Comment by MatteoBiscosi** [comment]
As requested encryption key is not rendered for non Admin user. Added localization for a string not localized. However the string you mentioned has to be localized, cause it was expressively requested to localize it and the same goes for hiding the key. Please ask to @lucaderi for more info about it

**Comment by simonemainardi** [comment]
I am not sure why an all-stars string needs localization.

By the way, there's a JS exception. I believe this is due to non-ZMQ interfaces.

![image](https://user-images.githubusercontent.com/3397663/120658040-63439500-c485-11eb-9a4d-a691e09b21f9.png)

**Comment by MatteoBiscosi** [comment]
Thanks for reporting this error, I didn't get it before. Fixed with the latest update.
