### ISSUE TITLE
BT5: Table alignment in the Interface 'historical' page

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#5351]
<img width="1548" alt="Screen Shot 2021-05-18 at 09 54 42" src="https://user-images.githubusercontent.com/7548711/118613641-3aea4400-b7bf-11eb-97d4-8fd6b82e666e.png">

**Comment by simonemainardi** [comment]
same here

![image](https://user-images.githubusercontent.com/3397663/118616542-16439b80-b7c2-11eb-93fc-6ea715259b3e.png)
