### ISSUE TITLE
BT5: Overflowing search

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5352]
search goes beyond the limits of the browser and results are unreadable 

![image](https://user-images.githubusercontent.com/3397663/118615774-59e9d580-b7c1-11eb-862a-6366cc3a4a77.png)

**Comment by MatteoBiscosi** [comment]
It's seems that this problem is currently solved, the search is now right alligned.
![Screenshot from 2021-05-26 10-59-07](https://user-images.githubusercontent.com/49585191/119632909-84ffa500-be11-11eb-9c58-9121171667c6.png)
Please reopen if needed.

**Comment by simonemainardi** [comment]
fix confirmed

![image](https://user-images.githubusercontent.com/3397663/119660095-25b08d80-be2f-11eb-9e6d-518db080989a.png)
