### ISSUE TITLE
BT5: Apps Dropdown

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5353]
Dropdown must be styled correctly and aligned to the right

![image](https://user-images.githubusercontent.com/3397663/118616114-afbe7d80-b7c1-11eb-8f14-eb946c0b9588.png)

**Comment by simonemainardi** [comment]
still bugged

![image](https://user-images.githubusercontent.com/3397663/118844532-50e52b00-b8cb-11eb-9831-71cba4ddb22f.png)

**Comment by MatteoBiscosi** [comment]
sorry but I cannot understand where it is bugged, the style seems correct to me, the "filtering" is done correctly and the text is left aligned like all the other dropdowns left aligned in ntopng

**Comment by simonemainardi** [comment]
![image](https://user-images.githubusercontent.com/3397663/118846158-b980d780-b8cc-11eb-98bf-7072c75f7933.png)
