### ISSUE TITLE
No data for Network Interfaces: realtime and Last Day view

### ISSUE THREAD

**Issue by filemoon** [ntop/ntopng#536]
Hi.

ntopng is connected to nprobe (over ZMQ).

Network Interfaces: Realtime Traffic is empty
Network Interfaces: Last Day View empty too
Status from bottom of the screen has no data too (other data/information is visible and working well).

![screen shot 2016-04-25 at 09 44 51](https://cloud.githubusercontent.com/assets/14888287/14778366/70e35026-0aca-11e6-9ca5-2e643d91e94a.jpg)

![screen shot 2016-04-25 at 09 44 55](https://cloud.githubusercontent.com/assets/14888287/14778431/ccd7c074-0aca-11e6-8e9d-b60f8be37dba.jpg)

Regards Chris

**Comment by lucaderi** [comment]
Please update first ntopng and nProbe and if not working, please report your configuration

**Comment by filemoon** [comment]
Updated to very latest available version (from your repository: deb http://packages.ntop.org/apt/jessie_pi/ armhf/, deb http://packages.ntop.org/apt/jessie_pi/ all/).

![screen shot 2016-04-25 at 10 02 33](https://cloud.githubusercontent.com/assets/14888287/14778794/e6065fa4-0acc-11e6-9ae1-0972a4820ed5.jpg)

ntopng config:
-G=/var/run/ntopng.pid
-d=/mnt/pqi/ntopng
-i=tcp://127.0.0.1:5556
--local-networks="10.0.1.0/24,10.0.2.0/24,10.0.0.0/24"

nprobe config:
--daemon-mode=/var/run/nprobe.pid
--collector-port=2055 
--flow-version=9 
--zmq=tcp://*:5556 
--interface none 
--collector none

I will still recommend to sort repository config:
![screen shot 2016-04-25 at 10 02 27](https://cloud.githubusercontent.com/assets/14888287/14778803/ee582d7c-0acc-11e6-8dbb-2bd55b53c301.jpg)

**Comment by simonemainardi** [comment]
@filemoon introduced some enhancements to properly show interface speed even when nprobe is used as collector of some other device.

We just have to rebuild embedded packages.

@lucaderi could you please fire a package rebuild for http://packages.ntop.org/apt/jessie_pi/armhf/

thank you.

**Comment by filemoon** [comment]
Thank you ;)

I will test it as soon as it will be available.

**Comment by filemoon** [comment]
v.2.3.160426 - small difference.

Network Interfaces: Realtime Traffic - no data
Network Interfaces: Last Day View - no data
- data for interface - green colour
- no data for gauge interface - red colour

![screen shot 2016-04-26 at 22 27 43](https://cloud.githubusercontent.com/assets/14888287/14834965/2cfcf8c2-0bff-11e6-8631-98b9d52d5424.jpg)

**Comment by filemoon** [comment]
Today after box was restarted is working very same was as before - no traffic is present including (green box).

Just for clarification:
Realtime Top Application Traffic - ok
Top Application Traffic Last Day View - ok
Top Local Talkers + Actual Traffic - ok
Top Remote Destinations+ Actual Traffic -ok

Network Interfaces: Realtime Traffic - no data
Network Interfaces: Last Day View - no data
+
no data on bottom bar

https://cloud.githubusercontent.com/assets/14888287/14778431/ccd7c074-0aca-11e6-8e9d-b60f8be37dba.jpg
- this is very new (no information about uptime, hosts and flows in the bottom of the screen)

![screen shot 2016-04-27 at 13 51 32](https://cloud.githubusercontent.com/assets/14888287/14852586/33480f34-0c7f-11e6-81b0-3ef1c203c11d.jpg)

**Comment by filemoon** [comment]
And another warnings from recent build.

Apr 28 07:10:17 Odroid-C2 ntopng[691]: [Lua.cpp:4598] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:217: '/var/lib/ntopng/0/rrd/10/0/1/110/DNS.rrd' is too small (should be 154744 bytes)]
Apr 28 07:15:18 Odroid-C2 ntopng[691]: [Lua.cpp:4598] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:217: '/var/lib/ntopng/0/rrd/10/0/1/110/DNS.rrd' is too small (should be 154744 bytes)]
Apr 28 07:20:18 Odroid-C2 ntopng[691]: [Lua.cpp:4598] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:217: '/var/lib/ntopng/0/rrd/10/0/1/110/DNS.rrd' is too small (should be 154744 bytes)]
Apr 28 07:25:20 Odroid-C2 ntopng[691]: [Lua.cpp:4598] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:217: '/var/lib/ntopng/0/rrd/10/0/1/110/DNS.rrd' is too small (should be 154744 bytes)]
Apr 28 07:30:21 Odroid-C2 ntopng[691]: [Lua.cpp:4598] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:217: '/var/lib/ntopng/0/rrd/10/0/1/110/DNS.rrd' is too small (should be 154744 bytes)]
Apr 28 07:35:21 Odroid-C2 ntopng[691]: [Lua.cpp:4598] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:217: '/var/lib/ntopng/0/rrd/10/0/1/110/DNS.rrd' is too small (should be 154744 bytes)]
Apr 28 07:40:23 Odroid-C2 ntopng[691]: [Lua.cpp:4598] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:217: '/var/lib/ntopng/0/rrd/10/0/1/110/DNS.rrd' is too small (should be 154744 bytes)]
Apr 28 07:45:24 Odroid-C2 ntopng[691]: [Lua.cpp:4598] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:217: '/var/lib/ntopng/0/rrd/10/0/1/110/DNS.rrd' is too small (should be 154744 bytes)]
Apr 28 07:50:25 Odroid-C2 ntopng[691]: [Lua.cpp:4598] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:217: '/var/lib/ntopng/0/rrd/10/0/1/110/DNS.rrd' is too small (should be 154744 bytes)]
Apr 28 07:55:27 Odroid-C2 ntopng[691]: [Lua.cpp:4598] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:217: '/var/lib/ntopng/0/rrd/10/0/1/110/DNS.rrd' is too small (should be 154744 bytes)]

**Comment by colorlessprism** [comment]
Chiming in to say I have this issue as well. CentOS 7. If I 'systemctl restart ntopng' enough times I can get the uptime to appear. Eventually I removed the ntopng service, rebooted, re-added the ntopng service, and rebooted. Then the gauge, traffic readout, and up time were displayed until I closed the browser and opened a new browser on a second computer on a different subnet. Then I was back to square one.

Later I found that turning on the extra reporting rrd's would kill the stats at the bottom of the page. Turning them back off would not bring the stats back. I would have to restart ntopng several times before I got everything to appear, except for the gauge.

Ive also noticed the Local Host page does not display the DNS, HTTP, or Geography tab. The Remove Hosts page does not display the DNS or HTTP tabs, but it does display the Geography tab.

Commands used to start everything up:

ntopng start as a service:
contents of /etc/ntopng/ntopng.conf
-G=/var/tmp/ntopng.pid
-i="tcp://127.0.0.1:5556"
-m="10.X.X.0/23"
--use-syslog=local3  # <--Never get any output to file

nprobe is started via /etc/rc.d/rc.local using command: nprobe /etc/nprobe/nprobe.conf
contents of nprobe.conf
--zmq tcp://*:5556
--interface none
--collector none
--collector-port 2055
-g=/var/tmp/nprobe.pid

nprobe version: 7.3.160428 (r5067)
ntopng version: 2.3.160428 (professional)
CentOS version: 7.1.1503 (core)

**Comment by filemoon** [comment]
![screen shot 2016-04-28 at 21 35 32](https://cloud.githubusercontent.com/assets/14888287/14900700/db4e52e6-0d89-11e6-9859-c6ab01f15850.jpg)

Interface home screen for reference - received traffic is also 0 (but traffic breakdown graph is alive)

![screen shot 2016-04-28 at 21 48 05](https://cloud.githubusercontent.com/assets/14888287/14900933/e91736e4-0d8a-11e6-9f2c-629e46d2c480.jpg)

**Comment by filemoon** [comment]
v.2.3.160426 - still same.

**Comment by Niko78** [comment]
still the same issue on my side with last nightly (small amount of hosts and flows when adding "-m")
ntopng v.2.3.160530 [Professional Edition]
nProbe v.7.3.160530 (r5227)

**Comment by Niko78** [comment]
without "-m" when I check in verbose mode, I have ton of 
30/May/2016 20:12:30 [CollectorInterface.cpp:183] [216] P▒z
30/May/2016 20:12:30 [ParserInterface.cpp:684] Not handled ZMQ field 15/15
30/May/2016 20:12:30 [ParserInterface.cpp:684] Not handled ZMQ field 10/10
30/May/2016 20:12:30 [ParserInterface.cpp:684] Not handled ZMQ field 14/14
30/May/2016 20:12:30 [ParserInterface.cpp:684] Not handled ZMQ field 5/5
30/May/2016 20:12:30 [ParserInterface.cpp:684] Not handled ZMQ field 16/16
30/May/2016 20:12:30 [ParserInterface.cpp:684] Not handled ZMQ field 17/17
30/May/2016 20:12:30 [ParserInterface.cpp:684] Not handled ZMQ field 9/9
30/May/2016 20:12:30 [ParserInterface.cpp:684] Not handled ZMQ field 13/13
30/May/2016 20:12:30 [ParserInterface.cpp:684] Not handled ZMQ field 42/42

with "-m", never got these lines

**Comment by filemoon** [comment]
And I'm still waiting for Debian arm build (v.2.3.160426 is the latest one).

👎

**Comment by Niko78** [comment]
I fixed a little bit my problem, I think it was a misunderstanding of  "-m"
I added a "-m" with all networks I managed (rfc1918 + pub network), now it's OK
but still issue to detect vpn ssl anyconnect (detected as quic) and netflow (detected as RX)

I have a second server in rfc1918 ip which manage all my vpn (distributed rfc1918), so "-m" has list of rfc1918"

**Comment by lucaderi** [comment]
Please file two different issues under ndpi and attach two pcap files, one for quic and one for rx.

**Comment by Niko78** [comment]
already done 
https://github.com/ntop/nDPI/issues/194

**Comment by Niko78** [comment]
but this "-m" is not clear
right now with my list of network, the only thing that changes is now I have a graph and a top list

I also detected that in flows tab, I have nothing in info column
if I start ntopng with only "-m" without network list, I have this time info... and protocols (netflow) are well detected and info column has info but not the right amount of hosts/flows
something is strange

**Comment by simonemainardi** [comment]
@Niko78 this issue is closed. Please open a new issue with all the screenshots and configurations used in order to enable us to reproduce. Thank you.
