### ISSUE TITLE
BT5: Dark theme changes the alignment of items in the header

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5361]
This is what happens when switching to the dark theme

![image](https://user-images.githubusercontent.com/3397663/118646646-c1fbe400-b7e0-11eb-88da-11be075c220f.png)

This indicates there's code duplication that must be removed and made independent from the theme colors

**Comment by simonemainardi** [comment]
Please, add a README file under doc, that explains:

- how the dark theme is handled
- how the csses can be kept updated
- from this commit https://github.com/ntop/ntopng/commit/b7c769b2e37eb8f9a5a5c78ee05fa3cada8fe96b it seems there's `bootstrap-5.0.1-ntopng.min.css` popping out from nowhere. Explain:

  - How is this file generated
  - Why does it carry a version if you have chosen to remove versions from all the other files, e.g., `/bootstrap/js/bootstrap.min.js`

**Comment by gabryon99** [comment]
The dark theme is a CSS (`dark-mode.css`) file that override the bootstrap's colors. Both the themes inside ntopng share the same bootstrap file.
