### ISSUE TITLE
ntop rpm key

### ISSUE THREAD

**Issue by hemskgren** [ntop/ntopng#537]
Have you change rpm key or is it some issue?

warning: /var/cache/yum/x86_64/7/ntop/packages/nprobe-7.3.160426-5062.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID d1eb60be: NOKEY                      ]  0.0 B/s | 474 kB  --:--:-- ETA
Public key for nprobe-7.3.160426-5062.x86_64.rpm is not installed

Retrieving key from http://www.nmon.net/centos/RPM-GPG-KEY-deri

The GPG keys listed for the "ntop packages" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.

 Failing package is: nprobe-7.3.160426-5062.x86_64
 GPG Keys are configured as: http://www.nmon.net/centos/RPM-GPG-KEY-deri

**Comment by lucaderi** [comment]
please go to http://packages.ntop.org/centos/ and re-follow the instructions for setting up packages. We have updated the GPG key and moved to new site packages.ntop.org.
