### ISSUE TITLE
BT5: Broken recipients selection

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5374]
Backend data seems to be good so it could be an issue with the selectpicker

![image](https://user-images.githubusercontent.com/3397663/118692886-d1902280-b80a-11eb-8830-fc4bba390c19.png)

**Comment by gabryon99** [comment]
I removed the `optgroup` tags because there is a bug with our version of the SelectPicker library (https://github.com/snapappointments/bootstrap-select/issues/2607)

**Comment by simonemainardi** [comment]
partial fix that didn't fix optgroup around the code. Finish with https://github.com/ntop/ntopng/issues/5381

**Comment by simonemainardi** [comment]
seems fixed as of https://github.com/snapappointments/bootstrap-select/issues/2607#issuecomment-847349214

**Comment by simonemainardi** [comment]
> I removed the optgroup tags because there is a bug with our version of the SelectPicker library (snapappointments/bootstrap-select#2607)

seems fixed as of https://github.com/snapappointments/bootstrap-select/issues/2607#issuecomment-847349214
