### ISSUE TITLE
BT5: Plus button to open datatables is disappeared

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5377]
There was a plus shown to open spillover columns in datatables. This is disappeared

![image](https://user-images.githubusercontent.com/3397663/118800087-cdfaab00-b89f-11eb-95d9-73da8abe5f59.png)

The line opens with a click, but there is no button

![image](https://user-images.githubusercontent.com/3397663/118800169-e7035c00-b89f-11eb-8c7c-8d381d36bef2.png)

Also the layout seems to be broken with a bullet list and missing column names

**Comment by simonemainardi** [comment]
how can you do a fix in just a minified .min file?

**Comment by simonemainardi** [comment]
Fixed in a minified file as reported in https://github.com/ntop/ntopng/issues/5391
This must be changed.

**Comment by gabryon99** [comment]
The current datatable's theme misses some styles to display the buttons inside the rows, therefore a temporary fix has been applied and when SpryMedia will release the new theme then we will apply it.

https://github.com/ntop/ntopng/commit/ebc76da1b64a2c291894841caf176337a4eb8bcc
