### ISSUE TITLE
Add a probe ID to disaggregate traffic

### ISSUE THREAD

**Issue by fanciulli** [ntop/ntopng#5383]
In order to better disaggregate traffic through a "Custom Traffic Disaggregation" it would be great if nProbe/ntopng support a user defined identifier to be associated to the flow. This would allow to split traffic coming from networks which may share the same private addressing space (e.g. 10.0.0.x).

Here an example:

Suppose to have multiple locations to track with the same ntopng instance. We want to split traffic on ntopng via disaggregation. Unfortunately those locations share the same addressing space (e.g. 192.168.0.x) so current logic cannot work. Moreover we don't want to use any traffic specific parameter to filter traffic (this may break thing later on).
The proposed solution is to allow nProbe to specify a custom id that is being added to the flow data being sent to ntopng. Let's say that:

LOCATION 1 --> Custom id = 100
LOCATION 2 --> Custom id = 200
LOCATION 3 --> Custom id = 300

On ntopng the user can create a "Custom Traffic Disaggregation" specifiying the custom id. As an example the configuration for location #2 would be:

Interface Name: My location #2
Traffic filter: CUSTOM_ID 200

**Comment by cardigliano** [comment]
@fanciulli what about using the exporter IP address currently available?

**Comment by fanciulli** [comment]
@cardigliano The exporter IP may collide with another exporter IP. Unfortunately locations may be built up using the same exact schema (e.g. a franchising store) and thus network addresses may collide.

**Comment by lucaderi** [comment]
Implemented via observation points https://www.ntop.org/nprobe/collecting-flows-from-hundred-of-routers-using-observation-points/
