### ISSUE TITLE
Implement native traffic blocking for attackers

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5387]
ntopng can block traffic leveraging alerts that define attackers/victims. Currently, the fail2ban plugin supports it. This ticket requests to
- implement the blocking capabilities similar to fail2ban in a new recipient/endpoint
- once the new recipient/endpoint is enabled a new host pool (if not already present) named (as an example) "blocked_hosts" is created
- attacker hosts with a score major than X for Y time, will be blocked
- we need to decide if hosts are blocked forever or only for some time as fail2ban

**Comment by MatteoBiscosi** [comment]
Blocking implemented with the help of nProbe, it is possible to configure the score threshold and the time of the ban. to permanently ban an host the user just need to add that ip/host to the Jailed Host Pool, the one used by this system in collaboration with nProbe to block users
