### ISSUE TITLE
ntopng GUI show all flows

### ISSUE THREAD

**Issue by alovinaX** [ntop/ntopng#5388]
hello,

I have two server that running ntopng build from source and configure to save flows in mysql using `-F "mysql;localhost;ntopng;flows;ntopng;ntopng"`, I'm exporting the database from server1 and importing it into server2 and when I'm launching ntopng on server2 I can't see all flows in my database, also I can't see the inactive flows.
How we can show all flows saved in mysql database in ntopng gui?
and it's a true way to get data from server1 to server2 by exporting mysql tables (flowsv4,flowsv6) and import them into server2 database ?

**Comment by simonemainardi** [comment]
Likely, interface ids are not matching. That is, you are saving flows from an interface with id X, and trying to read them with id Y.

**Comment by alovinaX** [comment]
I update interface_id field in mysql to the new one but the data still not showing.
also ntopng active flows show only the active flows and I need to show all the flows

**Comment by simonemainardi** [comment]
> I update interface_id field in mysql to the new one but the data still not showing.

Update the interface id and the instance name and make sure they match


> also ntopng active flows show only the active flows and I need to show all the flows

Historical flows are available under the "historical data explorer" (pro feature). Active flows are 'active' only, by definition.
