### ISSUE TITLE
UI issue - User settings menu misplaced

### ISSUE THREAD

**Issue by rreiner** [ntop/ntopng#5389]
On a good-sized browser window (anything less than 1500px wide on my system), the current build misrenders the user settings menu so that is clipped by the right edge of the screen.
Happens on both Chrome and Firefox, on Windows 10.

Screenshot attached.
![image](https://user-images.githubusercontent.com/12399329/119015511-f6011180-b966-11eb-92d8-e42523421404.png)

$ ntopng --version
Version:        4.3.210518 [Enterprise/Professional/Embedded build]
GIT rev:        dev:3039ec1e3fdb37d91e8370d4ced6c68b31af88d4:20210518
Pro rev:        r3782
Built on:       Raspbian GNU/Linux 10 (buster)
System Id:      130FA343499602D2
Platform:       armv7l
Edition:        Enterprise Embedded
License Type:   Time-Limited [Empty license file]
Validity:       Until Thu May 20 12:39:22 2021

**Comment by simonemainardi** [comment]
can you please check with the white theme to see if there is the same issue?

**Comment by rreiner** [comment]
White theme does *not* have the problem

**Comment by simonemainardi** [comment]
Fixed in the latest dev

![image](https://user-images.githubusercontent.com/3397663/119360852-58ca1400-bcab-11eb-93a6-8477cb8d5bb1.png)

Fix will be distributed in the next rpi build.
