### ISSUE TITLE
Can't login, after restart drops all configuration changes, DEFAULT admin password

### ISSUE THREAD

**Issue by EAnsy** [ntop/ntopng#539]
Fresh compiled ntopng:
`v.2.3.160425 [Community Edition]
GIT rev:   dev:766ea9840ac76aeb9441e7fbf25696fa29d104d9:20160425`
Redis has been upgraded too (redis-cli 3.0.7)
`Linux berms 3.4.67-smp #2 SMP Sat Oct 26 22:36:46 EEST 2013 i686 Intel(R) Celeron(R) CPU 2.66GHz GenuineIntel GNU/Linux`
Updated Slackware-based server (32-bit) SMS (http://sms.it-ccs.com)

After some time working can't login anymore with ANY login/password.
After ntopng restart can't see ANY SAVED parameters (eth renaming, new users accounts, changed passwords), and can login as _admin_ with **DEFAULT password** _admin_ (that's security hole).

**Comment by simonemainardi** [comment]
hi, thanks for reporting. It looks like your redis cache has been flushed and so ntopng started using default settings. However, ntopng _never_ flushes redis on its own. For this reason it is likely that some operation on your system has flushed redis. You should check, maybe it is something related to the redis upgrade.

**Comment by Queeq** [comment]
Wouldn't it be more reliable to store this data somewhere else?

**Comment by simonemainardi** [comment]
We use redis as it's the fastest persistent cache around.

On our side we may add authentication to redis. On your side you should make sure redis is accessible only from localhost and avoid executing scripts/updates that automatically clear redis data.
