### ISSUE TITLE
Timestamp column in flow tables

### ISSUE THREAD

**Issue by fanciulli** [ntop/ntopng#5392]
In flow tables it may be useful to add a timestamp column where the last seen time is reported. It would allo the user to sort flows by time

**Comment by MatteoBiscosi** [comment]
As requested I added the Last Seen orderable column (screen below). To be able to sort flows by time you need to run ntopng using MySql or nIndex db and you can sort flows by going into `Dashboard->Historical Flow Explorer`. Available only in Pro\Enterprise Version.
![Screenshot from 2021-06-01 17-50-38](https://user-images.githubusercontent.com/49585191/120354179-87c33400-c302-11eb-8a98-5176a37d1c9a.png)

**Comment by simonemainardi** [comment]
I don't think last_seen is really meaningful here. The page shows active flows, so basically their last seen are all within at most 1 minute from the current datetime. It also uses space in a page that is already pretty rich with columns.

I believe using the historical explorer is better as suggested by @MatteoBiscosi.

The only use case where this could be meaningful is when looking at pcap files but I am not sure the benefit can offset the cost of having so many columns in the page.

**Comment by MatteoBiscosi** [comment]
After a discussion, like you suggested, the space taken by the last seen column is too much, however we decided to not discard this option and by changing a preference (into `Misc`) it is now possible to decide if a user want to show the `Duration` column or the `Last Seen` column (however not both of them together).

**Comment by simonemainardi** [comment]
OK. Consider using the 'jolly' column as already implemented for hosts, in case new columns will be added:

![image](https://user-images.githubusercontent.com/3397663/120831449-d588a800-c55f-11eb-924e-2e40a4a7e86f.png)
