### ISSUE TITLE
BT5: Historical Flows Explorer Broken

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5396]
- layout is broken
- functionality is broken
 

![image](https://user-images.githubusercontent.com/3397663/119148833-2f13b180-ba4d-11eb-846a-214323b54ebf.png)

**Comment by simonemainardi** [comment]
above is for MySQL. Same for nindex (datetime pickers don't work)

![image](https://user-images.githubusercontent.com/3397663/119149400-c547d780-ba4d-11eb-80ab-c946acb01230.png)

**Comment by lucaderi** [comment]
Verified as fixed

**Comment by simonemainardi** [comment]
Still broken at least for MySQL:

![image](https://user-images.githubusercontent.com/3397663/119307482-0ae1eb80-bc6c-11eb-9a07-1e7662f088c6.png)

- datetimepickers don't work
- layout is broken
- hyperlinks on the results are broken and open invalid tabs

**Comment by simonemainardi** [comment]
fixed under pro
