### ISSUE TITLE
Invalid Flow Score Calculation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5402]
![telegram-cloud-photo-size-4-5863792311358567357-y](https://user-images.githubusercontent.com/4493366/119397634-b58ef400-bcd6-11eb-8b8b-821d483ab845.jpg)

This is the current version of ntopng: the flow score is not computer properly according to the nDPI risk values.

**Comment by lucaderi** [comment]
The bug is Flow::setAlertsBitmap() 
...
cli_inc = min_val(cli_inc, SCORE_MAX_VALUE);
srv_inc = min_val(srv_inc, SCORE_MAX_VALUE);
flow_inc = cli_inc + srv_inc;
...

The flow score is computed as the sum of client and server score. Per se, this is ok as long as the cli+srv value is set to the value specified by " u_int16_t ndpi_risk2score(ndpi_risk risk);"

Furthermore, the way FlowRisk subclasses (e.g. FlowRiskTLSSuspiciousESNIUsage) are implemented, it creates issues as it needs to be constantly in sync with nDPI, not to mention that flow risks that do not have an equivalent C++ class are ignored but possibly displayed on the GUI.

**Comment by cardigliano** [comment]
This depends on https://github.com/ntop/nDPI/issues/1190

**Comment by cardigliano** [comment]
Implemented in 94dd271814a02b0f40c8e0708f06e3dd55179efc - the flow score is computed based on client/server score provided by nDPI

**Comment by lucaderi** [comment]
![Screen Shot 2021-06-07 at 14 08 23](https://user-images.githubusercontent.com/4493366/121014060-d9a00a00-c799-11eb-8794-80fb3fc84a8c.png)
![Screen Shot 2021-06-07 at 14 07 21](https://user-images.githubusercontent.com/4493366/121014065-dad13700-c799-11eb-88f3-bc8ba19a4a19.png)
The GUI still does not report how the score is computed based on all issues detected

**Comment by lucaderi** [comment]
![Screen Shot 2021-06-07 at 14 25 26](https://user-images.githubusercontent.com/4493366/121016320-44eadb80-c79c-11eb-9b22-cbfb9c2a6994.png)
Where 51 is coming from? Is not a value I would expect

**Comment by cardigliano** [comment]
> ![Screen Shot 2021-06-07 at 14 25 26](https://user-images.githubusercontent.com/4493366/121016320-44eadb80-c79c-11eb-9b22-cbfb9c2a6994.png)
> Where 51 is coming from? Is not a value I would expect

This is triggered by the "PotentiallyDangerous" callback, which is no longer required as the same is also triggered by "FlowRiskUnsafeProtocol". I will cleanup PotentiallyDangerous.

**Comment by simonemainardi** [comment]
Handled. Breakdown is kept for at most 8 alerts per flow, then it falls under 'Other'.

Examples:

![image](https://user-images.githubusercontent.com/3397663/121524304-77dcdb80-c9f7-11eb-8b87-3d2f21e49578.png)

![image](https://user-images.githubusercontent.com/3397663/121524458-a22e9900-c9f7-11eb-83b2-65f5292cbe3e.png)

![image](https://user-images.githubusercontent.com/3397663/121524557-b7a3c300-c9f7-11eb-90ec-253b0f2cb7da.png)

**Comment by simonemainardi** [comment]
This is what is shown with the current implementation

![image](https://user-images.githubusercontent.com/3397663/121695767-a926db80-cacb-11eb-8943-2bc7c3dc77ac.png)

**Comment by simonemainardi** [comment]
This is for the historical alerts

![image](https://user-images.githubusercontent.com/3397663/121701139-e346ac00-cad0-11eb-85ba-aaf83b7a29ea.png)

**Comment by simonemainardi** [comment]
Now unhandled risks are shown as part of the issues

![image](https://user-images.githubusercontent.com/3397663/121716006-d1b8d080-cadf-11eb-9878-c34dfbea74e2.png)
