### ISSUE TITLE
Download Alert Format is Inconsistent

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5404]
Clicking on Delete alert in the page below

<img width="666" alt="Screenshot 2021-05-25 at 08 22 14" src="https://user-images.githubusercontent.com/4493366/119448982-54950980-bd32-11eb-84e1-6216432894e6.png">

the following content is returned

{"rc":0,"recordsTotal":1,"rc_str_hr":"Success","rc_str":"OK","rsp":{"records":[{"ip":{"value":"192.168.2.140","shown_label":"MacBookPro","label":"MacBookPro"},"is_attacker":"","score":{"value":20,"color":"#70db70","label":"20"},"family":"host","script_key":"remote_connection","alert_id":{"label":"Remote Connection","value":12},"count":1,"alert_name":"Remote Connection","vlan_id":0,"tstamp":{"value":1621923573,"highlight":"#70db70","label":"08:19:33"},"duration":27,"is_victim":"","msg":{"value":12,"name":"Remote Connection","description":"Host 192.168.2.140 has 1 active flows using a remote access protocol","configset_ref":" <a href=\"/lua/admin/edit_configset.lua?subdir=host&user_script=remote_connection#all\"><i class=\"fas fa-cog\" title=\"Edit Configuration\"></i></a>"},"severity":{"value":3,"color":"#70db70","label":"alerts_dashboard.notice"}}]},"recordsFiltered":1}

The are are several issues
- the file is in JSON and not in text/CSV format as in nIndex. This needs to be fixed
- it contains several HTML tags that are not supposed to stay in a log file but rather on a GUI. This makes the output unfit for any usage

It is request to export data in CSV format as in nIndex, adding a heading column and formatting the column properly so that they can be processed by an automatic tool

**Comment by simonemainardi** [comment]
Implement as follows:

- Convert method `<class>:format_record` into `<class>:format_json_record` everywhere
- remove any "no_html" reference to the methods above
- Convert method `format_record_commom` into `format_json_record_common`
- Adjusts calls everywhere with the new method names
- Implement methods `<class>:format_txt_record`. Those methods will call `<class>:format_json_record` and then will join the returned table JSON table into a text line using a separator specified in the class, e.g., ```

```
jr = format_json_record(...)
jr["new_filed] = "my new txt field"
res = table.concat({jr["alert_type"], jr["alert_name"], ...}, table.text_separator)
```

- Call `<class>:format_txt_record` when the alerts download is requested

**Comment by simonemainardi** [comment]
Implemented in the referenced merged PR.
