### ISSUE TITLE
Dangerous Host Callback Glitches

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5405]
The "Dangerous Host" need to take care of the following requirements
- when blocking a host, it must be added immediately into the blocked hosts pool list without using a recipient/endpoint
- in case it is blocked a host belonging to a DHCP range or with MAC-identified hosts, a MAC must be added, an IP otherwise
<img width="602" alt="Screenshot 2021-05-25 at 08 27 40" src="https://user-images.githubusercontent.com/4493366/119449590-1fd58200-bd33-11eb-9ece-83f5c87332e1.png">

- past some time (e.g. 15 mins) hosts blocked automatically must be unblocked.
- While a host is blocked an engaged host alert must be triggered. When the host is unblocked such alert will be closed.

**Comment by MatteoBiscosi** [comment]
Implemented as requested, `Dangerous Host` host alert
