### ISSUE TITLE
historical flow exporter and subnet search issue

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#5406]
hi,
I use ntopng Enterprise M v.4.3.210522 on ubuntu and I enabled mysql to keep trafic.
When I go in historical flow exporter and in "client/server host" I put a subnet instead of just a host IP, I get results.
BUT in bottom, when I click on "talker" then after "ipv4" button to download flows, it does nothing.
It works OK when the search is a simple host

Nico

**Comment by simonemainardi** [comment]
Thanks for reporting, this has been fixed and will be available in the next build.

Specifically:
- Download was broken when searching for subnets and this has been fixe
- Talkers have never been available when searching for subnets
