### ISSUE TITLE
The whole work of ntopng

### ISSUE THREAD

**Issue by tianzhishuizhu** [ntop/ntopng#541]
I can only see that ntopng does the work of analysing how much traffic the specific application on the specific host produces.Is it the main purpose of ntopng and even the whole purpose?

**Comment by lucaderi** [comment]
This is just one of the many things that ntopng does, but it is not the only one. ntopng is traffic monitor application you can use to analyse QoS and QoE as well to troubleshoot network problems

**Comment by tianzhishuizhu** [comment]
@lucaderi  Thanks! Have the functionality mentioned above accomplished in the current version of ntopng?

**Comment by lucaderi** [comment]
Sure. Time for you to run ntopng
