### ISSUE TITLE
ZMQ Exporter in Multiple Classes

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5410]
ntopng supports a ZMQ exporter both in class `ExportInterface` and in class `ZMQPublisher`. The former is enabled with option `-I` that however is legacy and I believe it can be removed. Please check if these two classes can be merged together.

**Comment by lucaderi** [comment]
Implement ZMQ encryption that is missing from ZMQ Exporter.

**Comment by lucaderi** [comment]
Implemented
