### ISSUE TITLE
Unable to parse sflow

### ISSUE THREAD

**Issue by alweiler** [ntop/ntopng#5411]
Version:	4.3.210525 [Enterprise/Professional build]
GIT rev:	dev:ba67279074d7aa71b04beefe379ad3b5b1526559:20210525
Pro rev:	r3827
Built on:	Ubuntu 18.04.5 LTS

nprobe
Version:       9.5.210525
Build OS:      Ubuntu 18.04.5 LTS

nprobe-none.conf
--zmq="tcp://6343"
--collector-port=2055
-n=none
-i=ens192

nprobe.conf
-i=ens192
-n=127.0.0.1:2055
-3=6343

ens192 ip address 10.11.1.179

I see only 10.11.1.0/24 hosts

in juniper switch 

collector 10.11.1.179 {
    udp-port 6343;
}
interfaces xe-0/1/1.0;
interfaces xe-0/1/4.0;
interfaces xe-0/1/5.0;
interfaces xe-0/1/6.0 {
    polling-interval 10;
    sample-rate egress 1000;
}

when I look pcap, I see that there are all traffic

**Comment by simonemainardi** [comment]
ntopng configuration?

**Comment by alweiler** [comment]
ntopng.conf

-G=/var/run/ntopng.pid
-i=ens192
-w=3000
-m=10.11.0.0/255.0.0.0
-d=/data/ntop

**Comment by simonemainardi** [comment]
- ntopng is not connected with nProbe. You need to connect it with nProbe to see sFlow. See https://www.ntop.org/guides/ntopng/using_with_other_tools/nprobe.html

- `-m=10.11.0.0/255.0.0.0` is not correct change it to `-m=10.11.0.0/8`

**Comment by alweiler** [comment]
@simonemainardi thanks. now works
