### ISSUE TITLE
REST API via cookie is broken in dev

### ISSUE THREAD

**Issue by TimotheusBachinger** [ntop/ntopng#5413]
Hi ntop team,

it seems the REST API access via session cookie is broken (assuming since https://github.com/ntop/ntopng/commit/1dce9e584282aa410e757b849af3f57b0809e76b)

Steps to reproduce:

`curl --cookie "user=A_NTOP_USER; session=HIS_COOKIE" "http://NTOP_URL:NTOP_PORT/lua/rest/get/interface/data.lua"`

Best regards
Timi

**Comment by cardigliano** [comment]
This has been fixed
