### ISSUE TITLE
Invalid check when adding 127.0.0.1

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5414]
![Screen Shot 2021-05-26 at 22 45 41](https://user-images.githubusercontent.com/4493366/119728794-261f4780-be74-11eb-8c17-b791139cba91.png)

**Comment by simonemainardi** [comment]
It seems 127.0.0.1 has already been added so now you get 'already exists'.

![image](https://user-images.githubusercontent.com/3397663/119805359-78e31880-bee1-11eb-8b16-60bd44fed25c.png)

Please explain what is the invalid check you are referring to in the title

**Comment by lucaderi** [comment]
This problem was fixed with the fix on the infrastructure monitoring.
Note that you should write a different error message such as "Measurement ICMP is already defined for host 127.0.0.1"
