### ISSUE TITLE
invalid active monitoring alerts reported

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5415]
![image](https://user-images.githubusercontent.com/4493366/119728919-4cdd7e00-be74-11eb-8e16-ec2243a69276.png)

In the above picture
- the link with an arrow does not bring anywhere
- the measurement type (e.g. CICMP) is not reported so it is not clear what is going on, nor the measurement and the threshold that triggered the alert

**Comment by simonemainardi** [comment]
fixed

![image](https://user-images.githubusercontent.com/3397663/119831760-df762f80-befd-11eb-9ee6-43ae3539451d.png)

![image](https://user-images.githubusercontent.com/3397663/119831793-e8670100-befd-11eb-9c95-e18ce17d9f0c.png)

> the link with an arrow does not bring anywhere

solved

> the measurement type (e.g. CICMP) is not reported so it is not clear what is going on, nor the measurement and the threshold that triggered the alert

solved. Using the very same labels also used in the active monitoring dropdown

---

NOTES: It would be desirable to have threshold, value, and measurement columns orderable but, given the current implementation of the engaged-alerts this is a no-go without significant backend changes.
