### ISSUE TITLE
Infrastructure not working

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5417]
![image](https://user-images.githubusercontent.com/4493366/119896059-c9d52a00-bf3e-11eb-890e-0045ca4a76bf.png)

In the above picture, I have added a new infrastructure entry with respect to an existing (version from Jan 2021) infrastructure. As you can see the new infrastructure is not polled at all

**Comment by simonemainardi** [comment]
Fixed under pro.  Issue was due to `am_utils.addHost` calls not updated with the extra parameter to specify the interface.

**Comment by simonemainardi** [comment]
![image](https://user-images.githubusercontent.com/3397663/119946744-40057b00-bf97-11eb-99ae-62c40be043fb.png)
