### ISSUE TITLE
Fix gray login with dark theme

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5423]
<img width="716" alt="Screenshot 2021-05-28 at 12 24 05" src="https://user-images.githubusercontent.com/4493366/119970125-a4cccf80-bfaf-11eb-8608-edb29c992aff.png">

**Comment by gabryon99** [comment]
Fixed in the commit: https://github.com/ntop/ntopng/commit/cc87b69dd40371dc40e54b81a681065b55ad936e.

<img width="1904" alt="Screenshot 2021-05-28 at 12 31 48" src="https://user-images.githubusercontent.com/14114916/119970973-acd93f00-bfb0-11eb-8621-49d1bcc01c42.png">
