### ISSUE TITLE
No data available

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5426]
![Screen Shot 2021-05-31 at 12 45 18](https://user-images.githubusercontent.com/4493366/120182029-20c45300-c20e-11eb-83fd-d462bc839fb6.png)

For this host I see data for April 2021, but not for May 2021. Something broken in the latest releases

**Comment by simonemainardi** [comment]
Please, attach the april and may charts obtained from 

![image](https://user-images.githubusercontent.com/3397663/120287686-c4ba0700-c2bf-11eb-82d6-4aae1b4bb133.png)

**Comment by lucaderi** [comment]
![Screen Shot 2021-06-07 at 13 48 31](https://user-images.githubusercontent.com/4493366/121011590-11f21900-c797-11eb-9786-1cd315309841.png)
![Screen Shot 2021-06-07 at 13 48 20](https://user-images.githubusercontent.com/4493366/121011592-13234600-c797-11eb-9d77-ba80610f6d56.png)

**Comment by simonemainardi** [comment]
I wanted to verify if there is data for the month of may for the selected host. Please, provide a screenshot with the chart, or attach the RRD directly.

**Comment by lucaderi** [comment]
![Screen Shot 2021-06-07 at 15 09 46](https://user-images.githubusercontent.com/4493366/121022242-72d31e80-c7a2-11eb-980a-7058d2b1f2d0.png)

**Comment by simonemainardi** [comment]
Issue was due to the traffic report not handling hosts serialized by MAC.

Fixed. In addition, the `traffic_report.lua` has been refactored and implemented as a standard lua module.
