### ISSUE TITLE
TCP port 5556 is not listening

### ISSUE THREAD

**Issue by scdit46** [ntop/ntopng#5427]
I want integreate nprobe (netflow) with ntopng

The configuration in ntopng is
-i=tcp://127.0.0.1:5556

The last message os journal is 
ZMQCollectorInterface:cpp:256] Collecting flows on tcp:127.0.0.1:5556

But the tcp port 5556 is not listening!!!!

ntopng is working

**Comment by cardigliano** [comment]
Please note you are configuring ntopng as client, thus it should connect, not listen. Please use tcp://127.0.0.1:5556c or tcp://*:5556c (notice the c suffix) to listen (you need to configure nprobe in probe/client mode in that case)

**Comment by scdit46** [comment]
OK 
I want configure this:
device  export netflow data ===> nprobe:2055 ==> ntopng:5556

**Comment by scdit46** [comment]
configuration ntopng 
-i=tcp://127.0.0.1:5556
the tcp port is listening

configuration nprobe

--zmq "tcp://127.0.0.1:5556" -i none -n none --collector-port 2055 -T "@NTOPNG@"

but the message is:
 ERROR unable to bind ZMQ endpoint tcp://127.0.0.1:5556: addres already in use

**Comment by simonemainardi** [comment]
> ERROR unable to bind ZMQ endpoint tcp://127.0.0.1:5556: addres already in use

There's another process running and bound to port 5556.

You can find with:

```
netstat -polentau | grep 5556
```

Kill the process and it will work.

**Comment by scdit46** [comment]
Not! 

I want configure this:
device export netflow data ===> nprobe:2055 ==> ntopng:5556
======================
configuration ntopng
-i=tcp://127.0.0.1:5556c

systemctl start ntopng

netstat -nltp

127.0.0.1:5556  0.0.0.0:*   LISTEN 79983/ntopng
0.0.0.0:3000    0.0.0.0:*   LISTEN 79983/ntopng
=============


configuration nprobe
--zmq=tcp://127.0.0.1:5556 -i=none -n=none --collector-port=2055

systemctl start ntopng

the service not starts socket

and the message is
ERROR unable to bind ZMQ endpoint tcp://127.0.0.1:5556: addres already in use

===========

what is the problem?

The documentation is a bit confused.

**Comment by simonemainardi** [comment]
> ERROR unable to bind ZMQ endpoint tcp://127.0.0.1:5556: addres already in use

There's a process running and bound to port 5556.

Stop all ntopng and nprobe instances. Make sure no one is running, i.e., `netstat -polentau | grep 5556` should give no output, then restart ntopng and nprobe with the new config.

By the way, nprobe is missing option `--zmq-probe-mode` as you are using ntopng in collector mode.

**Comment by scdit46** [comment]
I don´t know how to configure for that nprobe send netflow to ntopng

the message is 
ERROR unable to bind ZMQ endpoint tcp://127.0.0.1:5556: addres already in use

**Comment by simonemainardi** [comment]
>the message is ERROR unable to bind ZMQ endpoint tcp://127.0.0.1:5556: addres already in use

See above for explanation

> I don´t know how to configure for that nprobe send netflow to ntopng

See https://www.ntop.org/guides/ntopng/using_with_other_tools/nprobe.html#using-behind-a-firewall
