### ISSUE TITLE
Custom Geolocation

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#5429]
Maxmind's GeoIP database is not accurate enough. Can I add my own GeoIP database?  I have a more accurate MMDB file

**Comment by simonemainardi** [comment]
Sure, GeoIP is interoperable with libmaxminddb libraries. You can use your more accurate MMDB file as a drop in replacement.

You can drop the files here:

[/var/lib/GeoIP/GeoLite2-ASN.mmdb]
 [/var/lib/GeoIP/GeoLite2-City.mmdb]

By the way, what's your more accurate MMDB file? Can you contribute it to the community?

**Comment by MaoPann** [comment]
I need to test if it's available, and if it's available, I can contribute.

**Comment by MaoPann** [comment]
I will send the mmdb to you via email
.
