### ISSUE TITLE
new release yum report error key

### ISSUE THREAD

**Issue by steste640** [ntop/ntopng#543]
last upgrade problem

[root@ntop conf.d]# yum update
Plugin abilitati:fastestmirror, langpacks
Loading mirror speeds from cached hostfile
- base: mirrors.prometeus.net
- epel: mirror.23media.de
- extras: mirrors.prometeus.net
- updates: mirrors.prometeus.net
  Risoluzione dipendenze
  There are unfinished transactions remaining. You might consider running yum-complete-transaction, or "yum-complete-transaction --cleanup-only" and "yum history redo last", first to finish them. If those don't work you'll have to try removing/installing packages by hand (maybe package-cleanup can help).
  --> Esecuzione del controllo di transazione
  ---> Pacchetto e1000e-dna.noarch 0:3.2.4.2.529-1dkms settato per essere aggiornato
  ---> Pacchetto e1000e-dna.noarch 0:3.2.4.2.545-1dkms settato per essere un aggiornamento
  ---> Pacchetto e1000e-zc.noarch 0:3.2.7.1.529-1dkms settato per essere aggiornato
  ---> Pacchetto e1000e-zc.noarch 0:3.2.7.1.545-1dkms settato per essere un aggiornamento
  ---> Pacchetto i40e-zc.noarch 0:1.3.49.529-1dkms settato per essere aggiornato
  ---> Pacchetto i40e-zc.noarch 0:1.5.18.545-1dkms settato per essere un aggiornamento
  ---> Pacchetto igb-dna.noarch 0:5.3.2.2.529-1dkms settato per essere aggiornato
  ---> Pacchetto igb-dna.noarch 0:5.3.2.2.545-1dkms settato per essere un aggiornamento
  ---> Pacchetto igb-zc.noarch 0:5.3.3.5.529-1dkms settato per essere aggiornato
  ---> Pacchetto igb-zc.noarch 0:5.3.3.5.545-1dkms settato per essere un aggiornamento
  ---> Pacchetto ixgbe-dna.noarch 0:4.1.2.529-1dkms settato per essere aggiornato
  ---> Pacchetto ixgbe-dna.noarch 0:4.1.2.545-1dkms settato per essere un aggiornamento
  ---> Pacchetto ixgbe-zc.noarch 0:4.1.5.529-1dkms settato per essere aggiornato
  ---> Pacchetto ixgbe-zc.noarch 0:4.1.5.545-1dkms settato per essere un aggiornamento
  ---> Pacchetto n2disk.x86_64 0:2.5.160424-4620 settato per essere aggiornato
  ---> Pacchetto n2disk.x86_64 0:2.5.160430-4627 settato per essere un aggiornamento
  ---> Pacchetto nprobe.x86_64 0:7.3.160424-5051 settato per essere aggiornato
  ---> Pacchetto nprobe.x86_64 0:7.3.160430-5070 settato per essere un aggiornamento
  ---> Pacchetto nspr.x86_64 0:4.10.8-2.el7_1 settato per essere aggiornato
  ---> Pacchetto nspr.x86_64 0:4.11.0-1.el7_2 settato per essere un aggiornamento
  ---> Pacchetto nss.x86_64 0:3.19.1-19.el7_2 settato per essere aggiornato
  ---> Pacchetto nss.x86_64 0:3.21.0-9.el7_2 settato per essere un aggiornamento
  ---> Pacchetto nss-softokn.x86_64 0:3.16.2.3-13.el7_1 settato per essere aggiornato
  ---> Pacchetto nss-softokn.x86_64 0:3.16.2.3-14.2.el7_2 settato per essere un aggiornamento
  ---> Pacchetto nss-softokn-freebl.x86_64 0:3.16.2.3-13.el7_1 settato per essere aggiornato
  ---> Pacchetto nss-softokn-freebl.x86_64 0:3.16.2.3-14.2.el7_2 settato per essere un aggiornamento
  ---> Pacchetto nss-sysinit.x86_64 0:3.19.1-19.el7_2 settato per essere aggiornato
  ---> Pacchetto nss-sysinit.x86_64 0:3.21.0-9.el7_2 settato per essere un aggiornamento
  ---> Pacchetto nss-tools.x86_64 0:3.19.1-19.el7_2 settato per essere aggiornato
  ---> Pacchetto nss-tools.x86_64 0:3.21.0-9.el7_2 settato per essere un aggiornamento
  ---> Pacchetto nss-util.x86_64 0:3.19.1-9.el7_2 settato per essere aggiornato
  ---> Pacchetto nss-util.x86_64 0:3.21.0-2.2.el7_2 settato per essere un aggiornamento
  ---> Pacchetto ntopng.x86_64 0:2.3.160424-1113 settato per essere aggiornato
  ---> Pacchetto ntopng.x86_64 0:2.3.160430-1133 settato per essere un aggiornamento
  ---> Pacchetto ntopng-data.noarch 0:2.3.160424-1113 settato per essere aggiornato
  ---> Pacchetto ntopng-data.noarch 0:2.3.160430-1133 settato per essere un aggiornamento
  ---> Pacchetto pfring.x86_64 0:6.3.0-529 settato per essere aggiornato
  ---> Pacchetto pfring.x86_64 0:6.3.0-545 settato per essere un aggiornamento
  ---> Pacchetto pfring-dkms.noarch 0:6.3.0-529 settato per essere aggiornato
  ---> Pacchetto pfring-dkms.noarch 0:6.3.0-545 settato per essere un aggiornamento
  --> Risoluzione delle dipendenze completata

Dipendenze risolte
# 
#  Package               Arch      Versione                  Repository      Dim.

Aggiornamento:
 e1000e-dna            noarch    3.2.4.2.545-1dkms         ntop-noarch    239 k
 e1000e-zc             noarch    3.2.7.1.545-1dkms         ntop-noarch    239 k
 i40e-zc               noarch    1.5.18.545-1dkms          ntop-noarch    375 k
 igb-dna               noarch    5.3.2.2.545-1dkms         ntop-noarch    269 k
 igb-zc                noarch    5.3.3.5.545-1dkms         ntop-noarch    266 k
 ixgbe-dna             noarch    4.1.2.545-1dkms           ntop-noarch    347 k
 ixgbe-zc              noarch    4.1.5.545-1dkms           ntop-noarch    346 k
 n2disk                x86_64    2.5.160430-4627           ntop           852 k
 nprobe                x86_64    7.3.160430-5070           ntop           1.9 M
 nspr                  x86_64    4.11.0-1.el7_2            updates        126 k
 nss                   x86_64    3.21.0-9.el7_2            updates        850 k
 nss-softokn           x86_64    3.16.2.3-14.2.el7_2       updates        305 k
 nss-softokn-freebl    x86_64    3.16.2.3-14.2.el7_2       updates        204 k
 nss-sysinit           x86_64    3.21.0-9.el7_2            updates         55 k
 nss-tools             x86_64    3.21.0-9.el7_2            updates        487 k
 nss-util              x86_64    3.21.0-2.2.el7_2          updates         72 k
 ntopng                x86_64    2.3.160430-1133           ntop            27 M
 ntopng-data           noarch    2.3.160430-1133           ntop-noarch     23 M
 pfring                x86_64    6.3.0-545                 ntop           1.5 M
 pfring-dkms           noarch    6.3.0-545                 ntop-noarch     79 k
# Riepilogo della transazione

Upgrade  20 Pacchetto

Dimensione totale: 58 M
Is this ok [y/d/N]: y
Downloading packages:
avvertimento: /var/cache/yum/x86_64/7/ntop-noarch/packages/e1000e-zc-3.2.7.1.545-1dkms.noarch.rpm: Header V4 RSA/SHA1 Signature, ID chiave d1eb60be: NOKEY
Recupero chiave da http://packages.ntop.org/centos/RPM-GPG-KEY-deri
Importazione della chiave GPG 0xD1EB60BE:
 Userid     : "Luca Deri (Luca Deri's key.) deri@ntop.org"
 Fingerprint: 111a f5ed 8dab fe9f 9d6b b6f4 6f13 614f d1eb 60be
 Da         : http://packages.ntop.org/centos/RPM-GPG-KEY-deri
Procedere [s/N]: s

La chiave pubblica per e1000e-zc-3.2.7.1.545-1dkms.noarch.rpm non è installata

 Il pacchetto fallito è: e1000e-zc-3.2.7.1.545-1dkms.noarch
 Chiavi GPG configurate come: http://packages.ntop.org/centos/RPM-GPG-KEY-deri

[root@ntop conf.d]#

**Comment by lucaderi** [comment]
Please remove all packages and install them again. @ValentinaViscarelli Do you have suggestions?

**Comment by ValentinaViscarelli** [comment]
@lucaderi 
remove all packages and install them again doesn't resolve the problem.
It seems there is something of wrong in the packets (missing key???). If I download a rpm package (for example nprobe) and I run these commands:

rpm -K nprobe-7.3.160501-5071.x86_64.rpm 
nprobe-7.3.160501-5071.x86_64.rpm: RSA sha1 ((MD5) PGP) md5 NOT OK (MISSING KEYS: (MD5) PGP#d1eb60be)

and then:

rpm -Kv nprobe-7.3.160501-5071.x86_64.rpm 
nprobe-7.3.160501-5071.x86_64.rpm:
    Header V4 RSA/SHA1 Signature, key ID d1eb60be: NOKEY
    Header SHA1 digest: OK (905ad4022f55ed5cbbfb0f67944567ce84c7277a)
    V4 RSA/SHA1 Signature, key ID d1eb60be: NOKEY
    MD5 digest: OK (28f78c2ea8d9052d5202110df71805ab)

What do you think?

@steste640 
At the moment you can bypass the problem using --nogpgcheck parameter, for example:

sudo yum update --nogpgcheck

**Comment by lucaderi** [comment]
@ValentinaViscarelli The key http://packages.ntop.org/centos/RPM-GPG-KEY-deri corresponds to 

pub   4096R/D1EB60BE 2016-04-25
uid                  Luca Deri (Luca Deri's key.) deri@ntop.org
sub   4096R/EFAB838B 2016-04-25

And thus to d1eb60be. Check "rpm --import ..." and "gpg --list-keys" to debug the issue.

**Comment by ValentinaViscarelli** [comment]
@lucaderi 
Luca the file http://packages.ntop.org/centos/RPM-GPG-KEY-deri seems to be having two key. In fact if I download it and I run "gpg RPM-GPG-KEY-deri" I get:

pub  1024D/7921DF34 2003-06-27 Luca Deri (Luca Deri's key.) deri@ntop.org
sub  1024g/0FC9E456 2003-06-27
pub  4096R/D1EB60BE 2016-04-25 Luca Deri (Luca Deri's key.) deri@ntop.org
sub  4096R/EFAB838B 2016-04-25

When I try to update/install the ntop packages it uses the fist one (the old one) and this is wrong:
Importing GPG key 0x7921DF34:
 Userid     : "Luca Deri (Luca Deri's key.) deri@ntop.org"
 Fingerprint: 3f20 f5a3 b875 7e3f 1969 4413 98c8 43c6 7921 df34
 From       : /etc/yum.repos.d/RPM-GPG-KEY-deri
Is this ok [y/N]: y

Public key for pfring-dkms-6.3.0-545.noarch.rpm is not installed

Could the two keys create this problem?

**NOTE if I install the ntop repository from scratch installing centos I habe the same problem**

**Comment by lucaderi** [comment]
@ValentinaViscarelli  What about
gpg --keyserver keyserver.ubuntu.com --recv-keys  6F13614FD1EB60BE

**Comment by ValentinaViscarelli** [comment]
@lucaderi 
gpg --keyserver keyserver.ubuntu.com --recv-keys 6F13614FD1EB60BE
gpg: requesting key D1EB60BE from hkp server keyserver.ubuntu.com
gpg: key D1EB60BE: "Luca Deri (Luca Deri's key.) deri@ntop.org" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

**Comment by simonemainardi** [comment]
@ValentinaViscarelli now you can try again with yum install and it won't complain.

**Comment by ValentinaViscarelli** [comment]
@lucaderi 
Ok now it works.

**Comment by micoots** [comment]
Hi. This is still an issue. I'm not sure why the key isn't being made available, it's been reported a number of times from what I can see in web searches.

I ended up find the key here:

http://linuxsoft.cern.ch/mirror/packages.ntop.org/

or moreso:

http://linuxsoft.cern.ch/mirror/packages.ntop.org/RPM-GPG-KEY-deri

Please add this key to your repo so your ntop.repo file actually works and installs the software needed for CentOS 7.

Without the key it's impossible to automatically install this via yum, it has to be manual which defeats the purpose of providing a yum repo.

I realise you can tell yum to ignore checking of keys, but this is a security risk in case your repo is hacked.

**Comment by amin-tayebi** [comment]
@micoots
I have the same problem but with your solution are you sure it is safe? that website is not the main repo website!!!
