### ISSUE TITLE
Wrong timestamps in exported .txt flows

### ISSUE THREAD

**Issue by Syl4r-v** [ntop/ntopng#5431]
When using the export as text function (the button on the upper right corner of the traffic graph) the timestamps are UTC 0, even thought the time stamps are correct when browsnig flows from the NTOP itself. (UTC +2 (+1 summer time))

**Comment by simonemainardi** [comment]
Please, attach an example

**Comment by Syl4r-v** [comment]
Heres a pic. When you convert those epoch timestamps they are UTC0
<img width="2078" alt="Screenshot 2021-06-02 at 11 56 28" src="https://user-images.githubusercontent.com/77612587/120453350-a1fd2080-c39b-11eb-855a-4e129a9bfd04.png">

**Comment by simonemainardi** [comment]
This is normal. You are getting epochs in the exported results. Epochs are always timezone-independent as, by construction:

> "epoch is the number of seconds that have elapsed since the Unix epoch, minus leap seconds; the Unix epoch is 00:00:00 UTC on 1 January 1970."

We believe exported files should contain epochs and not pretty-printed timezone-adjusted formatted time strings as:

- Exported txt files are used as archives or for automatic processing and should not 'alter' timestamps according to the timezone of the user that was browsing the ntopng UI at that point it time. They must contain constant, reliable data, that is safe to be accessed also in the future without doing assumptions on the timezone of the user that has exported it.
- Multiple users on different timezones would get different data exported for the same actual data recorded thus creating confusion and inconsistencies
