### ISSUE TITLE
WIN32 support is non-existant

### ISSUE THREAD

**Issue by gvanem** [ntop/ntopng#5438]
The README at the front-page claims NtopNG can be built on Windows:
```
We build binary packages for the following platforms:
...
Windows x64
```

A claim I question since when building it, I get error on simple things like:
```c 
Prefs.cpp(1722): error C2664: 'int getopt_long(int,char *const *,const char *,const option *,int *)': 
cannot convert argument 1 from 'int *(__cdecl *)(void)' to 'int'
Prefs.cpp(1724): note: There is no context in which this conversion is possible
```
I mean it should be:
```c
  while((c = getopt_long(argc, argv,
			 "k:eg:hi:w:r:sg:m:n:p:qd:t:x:y:1:2:3:4:5:l:uv:A:B:CD:E:F:N:G:I:O:Q:S:TU:X:W:VZ:",
			 long_options, NULL)) != '?') {
```

for *all* targets. This code has been in there for 3 years. And there is even no `getopt*.h` file anywhere. Except for
`third-party/rrdtool-1.4.8/src/rrd_tool.h`.

 So it seems Windows is not an option to build the community-edition with currently.

**Comment by lucaderi** [comment]
Not quite. getopt_long is not ntop code but it third party code (see for instance https://github.com/libevent/libevent/blob/master/WIN32-Code/getopt_long.c). 

I accept that building on Windows is not as straightforward as on Unix, but your above statement is not correct. You can build (as we do) Win packages. Just make sure you satisfy all the non-ntop dependencies
