### ISSUE TITLE
nTOPng / shows wrong "total Bytes"

### ISSUE THREAD

**Issue by airtwist1** [ntop/ntopng#544]
Hi,

we recognized that ntopng is showing wrong "total Bytes"

For example, when we download a iso File from foreign Server with 4 GB of size. We can see the flow, but after it ends, ntopng is showing that 8GB where downloaded. It always shows double of "total Bytes" sends and receives ...

Which configuration could adjust this behavior ?

Many Thanks for your support 
Jean

Sflow settings on the port

polling 10 Seconds
sampling 1024
10GBit Port

**Comment by simonemainardi** [comment]
hi, could you please post the ntopng configuration used and the exact page that apparently gives you wrong information. Thank you

**Comment by airtwist1** [comment]
Hi,

please find attached the ntopn configuration. 

In the Flow section it shows the wrong information.

<img width="1577" alt="bildschirmfoto 2016-05-01 um 15 51 11" src="https://cloud.githubusercontent.com/assets/16499817/14942653/943bcd20-0fc3-11e6-8813-5bb7cb4ac492.png">

<img width="491" alt="bildschirmfoto 2016-04-21 um 22 38 10" src="https://cloud.githubusercontent.com/assets/16499817/14942658/db96691e-0fc3-11e6-80f9-2c99fb7d1570.png">

Jean

**Comment by simonemainardi** [comment]
Jean I need to see nProbe configuration as well. Thank you.

**Comment by airtwist1** [comment]
Hi,

sorry.

root@fn-ntop:~# cat /etc/nprobe/nprobe-none.conf 
-n=none
-i=none
-t=15
-d=5
-a=0
-e=1
-B=10
-w=128000
-z=0
-S=1:1
-E=0:0
-g=/var/run/nprobe-none.pid
-3=6343
--zmq=tcp://*:5556
--vlanid-as-iface-idx=none
-V=5
--dump-stats=/var/log/nprobe/none-0_flows_stats.txt

**Comment by simonemainardi** [comment]
you said that you are collecting 1:1024 sampled data so it is unlikely that you will be able to have precise information, isn't it?

**Comment by airtwist1** [comment]
so you mean i've to der the Option -S=1:1
to 1:1024?

**Comment by airtwist1** [comment]
so you mean i've to set the Option -S=1:1
to 1:1024?

**Comment by simonemainardi** [comment]
I mean this

> polling 10 Seconds
> sampling 1024
> 10GBit Port

**Comment by airtwist1** [comment]
yes, we have force 10 switches and the smallest amount to adjust ist 256 as sampling. 

Anyway, when we download a 4 GB iso. i would accept if ntop is showing 4.3 or 4.5 GB. But showing 8 GB is much to far. So, what do you recommend to setup ?

regarding to the 10Gbit port, it is a 10Gbit ethernet port, but has a speed of 1 Gbit because it´s plugged to a 1Gbit Switch.

**Comment by lucaderi** [comment]
@airtwist1 Please see on nprobe
[--collector-sample-rate] <value>   | Specify the bytes/pkts collection sample rate.

**Comment by airtwist1** [comment]
we setup on our switch to poll every 10 Seconds 1 packet of 1024. 

There are two options in the nprobe config to setup. Please, just let me know, which configuration would be the best for this type of setting.

What do you recommend for 

Sampling Rate ? 1:1 or 1:2 or 1: what do you prefer 
![bildschirmfoto 2016-05-02 um 15 05 21](https://cloud.githubusercontent.com/assets/16499817/14955141/14a45c0c-1078-11e6-9383-39af836b56d5.png)

Collector Sambaing Rate   1 Bytes/Pkts    is this setting right or what do you think i should setup here.
![bildschirmfoto 2016-05-02 um 15 05 48](https://cloud.githubusercontent.com/assets/16499817/14955148/1acb158a-1078-11e6-8e62-028783cbfb7b.png)

**Comment by lucaderi** [comment]
Sampling rate is the egress rate and should be 1:1, collector sampling rate should be 256

**Comment by airtwist1** [comment]
thanks
