### ISSUE TITLE
Don't use 0 ports for non TCP/UDP protocols

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5447]
In the example below (nIndex, but you should check the GUI as whole) please remove 0 port (leave it blank) for protocols other than TCP/UDP

![Screen Shot 2021-06-05 at 11 14 38](https://user-images.githubusercontent.com/4493366/120886637-3f03c780-c5ef-11eb-89fc-0df6f4d32019.png)

**Comment by MatteoBiscosi** [comment]
Removed ports for non TCP/UDP protocols in nIndex Flow Explorer
