### ISSUE TITLE
Wrong unit in icmp/cicmp charts

### ISSUE THREAD

**Issue by sezuan** [ntop/ntopng#5448]
Hello,

my icmp/cicmp charts in active monitoring look like this:

![chart](https://user-images.githubusercontent.com/202755/120887633-5d1ff680-c5f4-11eb-8cea-2a01f629dd31.png)

I would have expected that the unit is ms not bit/s.  I think I've seen screenshots where it is ms. The respective table looks like this:

![table](https://user-images.githubusercontent.com/202755/120887639-61e4aa80-c5f4-11eb-918a-983c48dda39c.png)

Tested with version 9.5.210604-7308 on Raspberry.

EDIT: The measured values are 'converted' like this: 30 ms => 8 x 30 bits/s = 240 bits/s

**Comment by simonemainardi** [comment]
Thanks for reporting. New raspberry builds are being generated and will be ready in the next few hours
