### ISSUE TITLE
compilation errors (‘struct ndpi_flow_struct’ has no member named ‘bittorent_hash’)

### ISSUE THREAD

**Issue by ambassador90** [ntop/ntopng#545]
Debian 8.4
git clone https://github.com/ntop/ntopng.git
git clone https://github.com/ntop/nDPI.git
cd nDPI
./autogen.sh
./configure (also tried --with-pic)
make
cd ../ntopng
./autogen.sh
./configure
make geoip
make > following errors:

src/Flow.cpp: In member function ‘void Flow::processDetectedProtocol()’:
src/Flow.cpp:272:42: error: ‘struct ndpi_flow_struct’ has no member named ‘bittorent_hash’
       setBittorrentHash((char_)ndpiFlow->bittorent_hash);
                                          ^
In file included from /root/ntopng/include/ntop_includes.h:141:0,
                 from src/Flow.cpp:22:
src/Flow.cpp: In member function ‘void Flow::update_hosts_stats(timeval_)’:
/root/ntopng/include/ntop_defines.h:158:40: warning: comparison with string literal results in unspecified behaviour [-Waddress]
 #define CONST_INTERFACE_TYPE_ZMQ       "zmq"
                                        ^
src/Flow.cpp:917:27: note: in expansion of macro ‘CONST_INTERFACE_TYPE_ZMQ’
  if((iface->get_type() != CONST_INTERFACE_TYPE_ZMQ)
                           ^
src/Flow.cpp: In member function ‘bool Flow::isIdleFlow(time_t)’:
/root/ntopng/include/ntop_defines.h:158:40: warning: comparison with string literal results in unspecified behaviour [-Waddress]
 #define CONST_INTERFACE_TYPE_ZMQ       "zmq"
                                        ^
src/Flow.cpp:1642:31: note: in expansion of macro ‘CONST_INTERFACE_TYPE_ZMQ’
      && (iface->get_type() != CONST_INTERFACE_TYPE_ZMQ)) {
                               ^
src/Flow.cpp:1663:46: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if((getCli2SrvCurrentInterArrivalTime(now) > threshold_ms)
                                              ^
src/Flow.cpp:1664:75: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
      || ((srv2cli_packets > 0) && (getSrv2CliCurrentInterArrivalTime(now) > threshold_ms)))
                                                                           ^
Makefile:129: recipe for target 'src/Flow.o' failed
make: **\* [src/Flow.o] Error 1

**Comment by lucaderi** [comment]
Please updated nDPI too and it will work.

**Comment by simonemainardi** [comment]
duplicate of https://github.com/ntop/ntopng/issues/451
