### ISSUE TITLE
unexpected device connected (Interface)

### ISSUE THREAD

**Issue by kadamik** [ntop/ntopng#5450]
I have all of my active MAC address connected, but I am still getting alerts on them.
example [06/06/2021 09:25:05] [eth0] [Warning] [Unexpected Device Connected] [ Unexpected MAC EA:0D:54:XX:XX:XX connected to the network. 
The Mac address is in the allow list.

Let me know what info you need.  This is happening on 8 - 10 mac address daily.

**Comment by simonemainardi** [comment]
please report platform and version used

**Comment by simonemainardi** [comment]
Confirmed. Fixed.
