### ISSUE TITLE
Unify Filter buttons: Add + in Historical Flow Report as in Alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5453]
![Screen Shot 2021-06-07 at 14 28 50](https://user-images.githubusercontent.com/4493366/121016703-be82c980-c79c-11eb-91f5-5bede32aaa70.png)
![Screen Shot 2021-06-07 at 14 28 24](https://user-images.githubusercontent.com/4493366/121016707-bfb3f680-c79c-11eb-95aa-f51f210fbb3c.png)

**Comment by cardigliano** [comment]
Implemented
