### ISSUE TITLE
Cleanup the script configuration key

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5456]
When a plugin is activated/deactivated a large JSON is stored saving a lot of unnecessary data such as

severity\":{\"icon\":\"fas fa-fw fa-info-circle text-info\",\"severity_id\":2,\"emoji\":\"\xe2\x84\xb9\",

Example:
1623070817.138966 [0 127.0.0.1:50961] "SET" "ntopng.prefs.user_scripts.configset_v3" "{\"filters\":{\"host\":{\"ntp_contacts\":[]},\"flow\":{\"long_lived\":[{\"l7_cat\":\"Database\"}],\"elephant_flows\":[{\"l7_cat\":\"DataTransfer\"},{\"l7_cat\":\"Cloud\"},{\"l7_cat\":\"SoftwareUpdate\"},{\"l7_cat\":\"Streaming\"},{\"l7_cat\":\"VPN\"}],\"low_goodput\":[{\"l7_proto\":8},{\"l7_proto\":26},{\"l7_proto\":39},{\"l7_proto\":48},{\"l7_proto\":65},{\"l7_proto\":77},{\"l7_proto\":92},{\"l7_proto\":142},{\"l7_proto\":185},{\"l7_proto\":193},{\"l7_proto\":197}]}},\"config\":{\"interface\":{\"periodic_activity_not_executed\":{\"min\":{\"script_conf\":[],\"enabled\":true}},\"lateral_movement\":{\"min\":{\"script_conf\":[],\"enabled\":true}},\"slow_periodic_activity\":{\"min\":{\"script_conf\":[],\"enabled\":true}},\"ghost_networks\":{\"min\":{\"script_conf\":[],\"enabled\":true}},\"unexpected_new_device\":{\"min\":{\"script_conf\":{\"items\":[]},\"enabled\":false}},\"too_many_drops\":{\"min\":{\"script_conf\":{\"operator\":\"gt\",\"threshold\":5},\"enabled\":true}},\"no_if_activity\":{\"min\":{\"script_conf\":[],\"enabled\":true}},\"slow_purge\":{\"min\":{\"script_conf\":{\"operator\":\"gt\",\"threshold\":50},\"enabled\":true}},\"dropped_alerts\":{\"min\":{\"script_conf\":[],\"enabled\":true}},\"pool_quota_exceeded\":{\"min\":{\"script_conf\":{\"severity\":{\"icon\":\"fas fa-fw fa-exclamation-triangle text-warning\",\"severity_id\":4,\"emoji\":\"\xe2\x9a\xa0\",\"syslog_severity\":4,\"color\":\"#ffc007\",\"used_by_alerts\":true,\"label\.....

**Comment by simonemainardi** [comment]
Thanks for pointing this out. Size has been shrunk by a factor 3x.

```
127.0.0.1:6379> strlen ntopng.prefs.user_scripts.configset_v3
(integer) 23572
127.0.0.1:6379> strlen ntopng.prefs.user_scripts.configset_v3
(integer) 8344
```

Note that you should delete the old key to have it re-generated without extra unnecessary items. Delete operations have not been done automatically to avoid extra lines of code as having those  data is harmless.
