### ISSUE TITLE
Service map does not honour MAC addresses

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5457]
![Screen Shot 2021-06-07 at 16 28 37](https://user-images.githubusercontent.com/4493366/121035933-a451e700-c7ae-11eb-89a3-fa54535a556c.png)
![Screen Shot 2021-06-07 at 16 27 49](https://user-images.githubusercontent.com/4493366/121035948-a6b44100-c7ae-11eb-8b4d-aa9f0f3bbade.png)

**Comment by MatteoBiscosi** [comment]
It seems that it is working correctly now, please reopen if needed
