### ISSUE TITLE
libmysqlclient18 unavailable on Ubuntu 16.04

### ISSUE THREAD

**Issue by pdf** [ntop/ntopng#546]
Appears the current client is `libmysqlclient20`.

**Comment by lucaderi** [comment]
@pdf In fact we use the libmysqlclient20 dependency

dpkg -I nprobe_7.3.160503-5072_amd64.deb  
 new debian package, version 2.0.
 size 1218100 bytes: control archive=2448 bytes.
     394 bytes,    11 lines      control  
    3136 bytes,    39 lines      md5sums  
     581 bytes,    34 lines   \*  postinst             #!/bin/sh
     187 bytes,    13 lines   \*  postrm               #!/bin/sh
     664 bytes,    35 lines   \*  preinst              #!/bin/sh
     314 bytes,    13 lines   \*  prerm                #!/bin/sh
 Package: nprobe
 Version: 7.3.160503-5072
 Architecture: amd64
 Maintainer: Luca Deri deri@ntop.org
 Installed-Size: 8719
 Depends: pfring (= 6.3.0-549), libsqlite3-0, libhiredis0.13, **libmysqlclient20**, libgeoip1, libcurl3, redis-server, libnuma1, libnl-3-200, libnetfilter-queue1, libzmq5
 Recommends: ntopng-data
 Replaces: nProbe
 Section: non-free
 Priority: optional
 Description: A network probe

**Comment by pdf** [comment]
I should have specified I suppose, but not for the ntopng package:

```
ntopng:
  Installed: (none)
  Candidate: 2.3.160503-1210
  Version table:
     2.3.160503-1210 500
        500 http://packages.ntop.org/apt/16.04 x64/ Packages
     2.2+dfsg1-1build1 500
        500 http://mirror.internode.on.net/pub/ubuntu/ubuntu xenial/universe amd64 Packages
```

```
Package: ntopng
Priority: optional
Section: free
Installed-Size: 18246
Maintainer: Luca Deri <deri@ntop.org>
Architecture: amd64
Version: 2.3.160503-1210
Depends: pfring (= 6.3.0-549), libsqlite3-0, libgeoip1, redis-server, librrd4, logrotate, libcurl3, libpcap0.8, libldap-2.4-2, libhiredis0.13, libmysqlclient18, libnuma1, libzmq5, libnetfilter-queue1
Recommends: ntopng-data, pfring-dkms
Filename: x64/./ntopng_2.3.160503-1210_amd64.deb
Size: 4172536
MD5sum: 818221761069b9df98bd79460bdbbc06
SHA1: 37c1099036dd50388b25b76793fefaff4cca2912
SHA256: 945e3ebe1a4c7f8a1e0e0f521234c1e2308cc70dd6d380add1d3a86eba3ce6bb
SHA512: 23b757cdaa002e4073a107c4bb754fda55077fedce76d198ec098e4a171ad0c7a80591776f2c7a9f19235af3da632c349a05eceb25fc8adeda0aa131d2e86c74
Description: Web-based traffic monitoring.
Description-md5: 59c1e802c8c4538ac78f99e8b8e58c28
```

**Comment by lucaderi** [comment]
@pdf Sorry now I understand. I have fixed it and binary packages are being rebuilt

**Comment by pdf** [comment]
Thanks for the rapid turn-around!
