### ISSUE TITLE
Inconsistent alert information

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5464]
![image](https://user-images.githubusercontent.com/4493366/121150297-ae71f500-c843-11eb-80cb-9ced1370e55e.png)
This alert is inconsistent
- the direction are wrong (the client is the server)
- the score is low and green (so not too bad)
- there is a attacker/victim icon (so very bad)
- there is red down thumb (so bad)

The idea is to decide whether this alert is severe or not and this make it consistent

**Comment by simonemainardi** [comment]
Issue is now fixed:


>  The direction are wrong (the client is the server)

Fixed with https://github.com/ntop/ntopng/commit/117e29a903f3fee52388cba59143dab86ff68957

> the score is low and green (so not too bad)

Fixed with 38b31bdb

> there is a attacker/victim icon (so very bad)

This is correct. Remote to local insecure means a possible attacker is reaching a local host 

> there is red down thumb (so bad)

Now consistent with score and color.
