### ISSUE TITLE
Ability to specify the folder/path to save n2disk data

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#5469]
ability to specify the folder/path to save n2disk data

**Comment by cardigliano** [comment]
This is already available with --pcap-dir|-5 <path>

**Comment by zimbawe998** [comment]
Not i GUI?

Il mar 8 giu 2021, 16:02 Alfredo Cardigliano ***@***.***> ha
scritto:

**Comment by cardigliano** [comment]
This can be set in the configuration file ntopng.conf

**Comment by zimbawe998** [comment]
Not in GUI?
Thanks

Il mar 8 giu 2021, 22:04 Alfredo Cardigliano ***@***.***> ha
scritto:
