### ISSUE TITLE
Missing Traffic Direction with sFlow/NetFlow

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5470]
When ntopng is collecting traffic via sFlow/NetFlow all the traffic si considered in ingress and not in RX/TX as it should. Said that sometimes adding directions might be complicated depending on the setup, in many other cases this is possible and so it should be implemented. For instance, in sFlow this is definitively possible and also with NetFlow playing with interfaceIDs

**Comment by brunobcestari** [comment]
Hello!
I managed to fix it here by adding my local network range in both **nprobe.conf** and **ntopng.conf** files with 

`--local-networks=<local-ip range>`

After adding this parameter in both files I started to see separate traffic for RX and TX coming from Traffic Flow.

**Comment by lucaderi** [comment]
Implemented also in ntopng
