### ISSUE TITLE
Implement L7 Traffic Behavioural Counters

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5474]
Similar to what happens with hosts, it is requested to implement L7 protocol behavioural counters for network interface protocols. Ideally, it should be possible to specify for what protocol to trigger alerts, or to silence them.

**Comment by MatteoBiscosi** [comment]
Implemented as requested. As discussed the behavior analysis starts as the alert is enabled and a restart of ntopng is required to start it.
