### ISSUE TITLE
Non responding from browser after a while

### ISSUE THREAD

**Issue by sunshiros** [ntop/ntopng#5477]
![server](https://user-images.githubusercontent.com/2570633/121358649-7352ed00-c93b-11eb-9723-899203ec810c.jpg)
Hi,
Running ntopng Pro Embedded (Raspberry] on a Raspberry Pi 4 with the latest version of Raspbian but i after a while i cannot use the GUI interface from the browser. Of course i tried different browsers, empty cache and etc but it still does not load the page with eventually showing the message that it cannot be reached. 

I can only bring it back to life by issue restart command from terminal : sudo systemctl restart ntopng

**Comment by sunshiros** [comment]
Added a screenshot

**Comment by MatteoBiscosi** [comment]
Hi @geotony could you please check the status of ntopng after the restart?
From terminal: `sudo systemctl status ntopng` and check if it's going to show some problem

**Comment by sunshiros** [comment]
This is the output:

● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-06-09 19:07:45 EEST; 14min ago
  Process: 3760 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exited, status=0/SUCCESS)
  Process: 3774 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
  Process: 3776 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (code=exited, status=0/SUCCESS)
  Process: 3778 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /run/ntopng.conf (code=exited, status=0/SUCCESS)
 Main PID: 3780 (ntopng)
    Tasks: 43 (limit: 4915)
   CGroup: /system.slice/ntopng.service
           └─3780 /usr/bin/ntopng /run/ntopng.conf

Jun 09 19:14:34 RaspberryPi ntopng[3780]: [Utils.cpp:1793] WARNING: Unable to send email to (smtp://smtp.gmail.com/gmail.com): Couldn't connect to server. Run ntopng with -v6 for more detai
Jun 09 19:14:34 RaspberryPi ntopng[3780]: 09/Jun/2021 19:14:34 [Utils.cpp:1793] WARNING: Unable to send email to (smtp://smtp.gmail.com/gmail.com): Couldn't connect to server. Run ntopng wi
Jun 09 19:16:47 RaspberryPi ntopng[3780]: [Utils.cpp:1793] WARNING: Unable to send email to (smtp://smtp.gmail.com/gmail.com): Couldn't connect to server. Run ntopng with -v6 for more detai
Jun 09 19:16:47 RaspberryPi ntopng[3780]: 09/Jun/2021 19:16:47 [Utils.cpp:1793] WARNING: Unable to send email to (smtp://smtp.gmail.com/gmail.com): Couldn't connect to server. Run ntopng wi
Jun 09 19:19:00 RaspberryPi ntopng[3780]: [Utils.cpp:1793] WARNING: Unable to send email to (smtp://smtp.gmail.com/gmail.com): Couldn't connect to server. Run ntopng with -v6 for more detai
Jun 09 19:19:00 RaspberryPi ntopng[3780]: 09/Jun/2021 19:19:00 [Utils.cpp:1793] WARNING: Unable to send email to (smtp://smtp.gmail.com/gmail.com): Couldn't connect to server. Run ntopng wi
Jun 09 19:21:13 RaspberryPi ntopng[3780]: [Utils.cpp:1793] WARNING: Unable to send email to (smtp://smtp.gmail.com/gmail.com): Couldn't connect to server. Run ntopng with -v6 for more detai
Jun 09 19:21:13 RaspberryPi ntopng[3780]: 09/Jun/2021 19:21:13 [Utils.cpp:1793] WARNING: Unable to send email to (smtp://smtp.gmail.com/gmail.com): Couldn't connect to server. Run ntopng wi
Jun 09 19:21:13 RaspberryPi ntopng[3780]: [notifications.lua:30] [recipients.lua:707] ERROR: Error while sending notifications via Email Alerts Unable to send mails
Jun 09 19:21:13 RaspberryPi ntopng[3780]: 09/Jun/2021 19:21:13 [notifications.lua:30] [recipients.lua:707] ERROR: Error while sending notifications via Email Alerts Unable to send mails
lines 1-22/22 (END)

**Comment by sunshiros** [comment]
And this is during the browser freeze : 

● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-06-09 19:48:21 EEST; 3h 22min ago
  Process: 20102 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exi
  Process: 20116 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
  Process: 20118 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (code=exited, status=0/SUCCESS)
  Process: 20120 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /run/ntopng.conf (code=exit
 Main PID: 20122 (ntopng)
    Tasks: 43 (limit: 4915)
   CGroup: /system.slice/ntopng.service
           └─20122 /usr/bin/ntopng /run/ntopng.conf

Jun 09 21:26:05 RaspberryPi ntopng[20122]: 09/Jun/2021 21:26:05 [HostStats.cpp:101] [ANOMALY] 10.0.0.215 [eth0][client score] [value: 0]
Jun 09 21:33:49 RaspberryPi ntopng[20122]: 09/Jun/2021 21:33:49 [HostStats.cpp:113] [ANOMALY] 10.0.0.1 [eth0][server score] [value: 30]
Jun 09 21:38:51 RaspberryPi ntopng[20122]: 09/Jun/2021 21:38:51 [HostStats.cpp:113] [ANOMALY] 10.0.0.1 [eth0][server score] [value: 0]
Jun 09 22:09:06 RaspberryPi ntopng[20122]: 09/Jun/2021 22:09:06 [HostStats.cpp:101] [ANOMALY] 10.0.0.152 [eth0][client score] [value: 40]
Jun 09 22:44:54 RaspberryPi ntopng[20122]: **[LuaEngineNtop.cpp:47] ERROR: ntop_get_ndpi_protocol_name : expected number[@pos 1], got nil**
Jun 09 22:44:54 RaspberryPi ntopng[20122]: 09/Jun/2021 22:44:54 [LuaEngineNtop.cpp:47] ERROR: ntop_get_ndpi_protocol_name : expected number[@pos 1], got nil
Jun 09 22:44:55 RaspberryPi ntopng[20122]: [LuaEngine.cpp:1180] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/get_ts_table.lua][/usr/share/ntopng/pro/sc
Jun 09 22:44:55 RaspberryPi ntopng[20122]: 09/Jun/2021 22:44:55 [LuaEngine.cpp:1180] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/get_ts_table.lua][/us
Jun 09 22:59:10 RaspberryPi ntopng[20122]: 09/Jun/2021 22:59:10 [HostStats.cpp:77] [ANOMALY] 127.0.0.1 [lo][client flows] [value: 119]
Jun 09 22:59:10 RaspberryPi ntopng[20122]: 09/Jun/2021 22:59:10 [HostStats.cpp:89] [ANOMALY] 127.0.0.1 [lo][server flows] [value: 117]
lines 1-22/22 (END)

**Comment by simonemainardi** [comment]
I have been running the service for 2+ hours without issues.

Please, report:

- Output of `ntopng --version`
- A couple of screenshots (need to see how many active/hosts flows you have)
- ntopng configuration file

**Comment by sunshiros** [comment]
Hello,

The report as requested :

1.
$  ntopng --version
Version:        4.3.210609 [Enterprise/Professional/Embedded build]
GIT rev:        dev:fc2db1513ba47da533c95933792dc225d6b6674c:20210609
Pro rev:        r3871
Built on:       Raspbian GNU/Linux 10 (buster)
Platform:       armv7l
Edition:        Professional Embedded
License Type:   Permanent
Maintenance:    Until Wed Jun  8 01:40:18 2022 [362 days left]


2.
 I have 78 active Flows and 44 hosts (please let me know what do you need on the screenshot so i can blackout the privacy sensitive informations)


3.
The 	ntopng configuration file found here : /etc/ntopng/ntopng.conf

(the only uncomment line is : -G=/var/run/ntopng.pid )

The 	ntopng configuration file found here : /run/ntopng.conf

(no uncomment lines)

#         The  configuration  file is similar to the command line, with the exception that an equal
#        sign '=' must be used between key and value. Example:  -i=p1p2  or  --interface=p1p2  For
#        options with no value (e.g. -v) the equal is also necessary. Example: "-v=" must be used.
#
#
##       -G|--pid-path
#        Specifies the path where the PID (process ID) is saved. This option is ignored when
#        ntopng is controlled with systemd (e.g., service ntopng start).
#
#-G=/var/run/ntopng.pid
#
#       -e|--daemon
#        This  parameter  causes ntop to become a daemon, i.e. a task which runs in the background
#        without connection to a specific terminal. To use ntop other than as a casual  monitoring
#        tool, you probably will want to use this option. This option is ignored when ntopng is
#        controlled with systemd (e.g., service ntopng start)
#
# -e=
#
#       -i|--interface
#        Specifies  the  network  interface or collector endpoint to be used by ntopng for network
#        monitoring. On Unix you can specify both the interface name  (e.g.  lo)  or  the  numeric
#        interface id as shown by ntopng -h. On Windows you must use the interface number instead.
#        Note that you can specify -i multiple times in order to instruct ntopng to create  multi-
#        ple interfaces.
#
# -i=eth1
# -i=eth2
#
#       -w|--http-port
#        Sets the HTTP port of the embedded web server.
#
# -w=3000
#
#       -m|--local-networks
#        ntopng determines the ip addresses and netmasks for each active interface. Any traffic on
#        those  networks  is considered local. This parameter allows the user to define additional
#        networks and subnetworks whose traffic is also considered local in  ntopng  reports.  All
#        other hosts are considered remote. If not specified the default is set to 192.168.1.0/24.
#
#        Commas  separate  multiple  network  values.  Both netmask and CIDR notation may be used,
#        even mixed together, for instance "131.114.21.0/24,10.0.0.0/255.0.0.0".
#
# -m=10.10.123.0/24
# -m=10.10.124.0/24
#
#       -n|--dns-mode
#        Sets the DNS address resolution mode: 0 - Decode DNS responses  and  resolve  only  local
#        (-m)  numeric  IPs  1  -  Decode DNS responses and resolve all numeric IPs 2 - Decode DNS
#        responses and don't resolve numeric IPs 3 - Don't decode DNS responses and don't  resolve
#
# -n=1
#
#       -S|--sticky-hosts
#        ntopng  periodically purges idle hosts. With this option you can modify this behaviour by
#        telling ntopng not to purge the hosts specified by -S. This parameter requires  an  argu-
#        ment  that  can  be  "all"  (Keep  all hosts in memory), "local" (Keep only local hosts),
#        "remote" (Keep only remote hosts), "none" (Flush hosts when idle).
#
# -S=
#
#       -d|--data-dir
#        Specifies the data directory (it must be writable by the user that is executing ntopng).
#
# -d=/var/lib/ntopng
#
#       -q|--disable-autologout
#        Disable web interface logout for inactivity.
#
# -q=


I have checked the cpu usage and disk usage when its stuck and the use is minimal as always 

I notice also when restarting the ntopng service when its stucj it takes quite some time in the terminal. Restarting the service when not stuck it works instantly

**Comment by simonemainardi** [comment]
Let's do this. Restart it, let it run until it blocks (do not restart it). Then I can connect and to a remote teamviewer session to check. Just drop me when it is blocked.

**Comment by simonemainardi** [comment]
@geotony any news about this? still not blocked?

**Comment by sunshiros** [comment]
Hello. Still blocked. Let do the teamviewer session if thats ok with you as well.

**Comment by simonemainardi** [comment]
ok

**Comment by geotony** [comment]
SImone,

Teamviewer : 197 593 377
pass : Y#*Cuihxeh


Cheers,

Tony

**Comment by simonemainardi** [comment]
After a remote session, we found out ntopng was running on a pihole. Pihole is not a distro which is officially supported. For some reason, ntopng was left with several stale connections

Solution is to run ntopng on one of the officially supported distros.

**Comment by sunshiros** [comment]
I've added a cron job to restart the ntopng service every 15 minutes and it seems to be working ok. Do you think that i will have any problems using it like that? I've activated all the cache options in cache settings so i wont loose any data

**Comment by simonemainardi** [comment]
> I've added a cron job to restart the ntopng service every 15 minutes

Why?

Are you running on a vanilla raspbian rather than on a pihole?
