### ISSUE TITLE
JA3 Client fingerprint - applicaion name is empty

### ISSUE THREAD

**Issue by scdit46** [ntop/ntopng#5479]
The field "Application Name" of JA3 Client fingerprint in TLS is always empty

I use curl, wget, firewfox, IE,...

**Comment by simonemainardi** [comment]
As it says the footnote in bold, "Application name is set only if ntopng is configured to receive a eBPF feed via ZMQ".

See https://www.ntop.org/products/netflow/nprobe-agent/
