### ISSUE TITLE
ntopng / elasticsearch template IP field

### ISSUE THREAD

**Issue by shamsway** [ntop/ntopng#548]
Please let me know if this is the wrong spot to put this - I was not sure where else to ask.

I am using the elasticsearch template from https://github.com/ntop/ntopng/wiki/02-Elasticsearch-FAQ.  The geoip type matching works as expected, but IPV4_DST_ADDR and IPV4_SRC_ADDR are being indexed as a string.  I am pretty novice when it comes to elasticsearch, but I've tried several variations in the template (i.e. delete old template, post new template, delete and recreate index), and it always gets matched as a string.  Hoping someone else has a simple fix for this.

I am running elasticsearch 4.5.0 build 9889.  

Template:

```
curl -XPUT localhost:9200/_template/ntopng_template -d '
{
  "template" : "ntopng-*",
  "settings" : {
    "index.refresh_interval" : "5s"
  },
  "mappings" : {
    "_default_" : {
       "_all" : {"enabled" : true, "omit_norms" : true},
       "dynamic_templates" : [ {
             "string_fields" : {
               "match" : "*",
               "match_mapping_type" : "string",
               "mapping" : {
                 "type" : "string", "index" : "analyzed", "omit_norms" : true,
                   "fields" : {
                     "raw" : {"type": "string", "index" : "not_analyzed", "ignore_above" : 256}
                   }
               }
             }
       }, {
             "geo_fields" : {
               "match" : "*_IP_LOCATION",
               "mapping": {
                      "type": "geo_point"
                }
             }
       }, {
             "ip_fields" : {
               "match" : "IPV4_*",
               "match_mapping_type" : "string",
               "mapping": {
                      "type": "ip"
                }
             }
       } ],
       "properties" : {
         "@version": { "type": "string", "index": "not_analyzed" }
       }
    }
  }
}
'
```

I tried adjusting properties to add the mappings statically, but I had no luck with that either.  I also tried changing "match_mapping_type" to "*".

**Comment by simonemainardi** [comment]
did you try to completely remove `match_mapping_type`  from

```
             "ip_fields" : {
               "match" : "IPV4_*",
               "match_mapping_type" : "string",
               "mapping": {
                      "type": "ip"
                }
             }
```

please, let me know if it works.

**Comment by shamsway** [comment]
Yes, I did try that, sorry for not mentioning it.  It was the first thing I tried on a hunch :)

**Comment by simonemainardi** [comment]
solved, new packages are being rebuilt and will be available tomorrow.

**Comment by h8h** [comment]
Hi

This breaks the IPv6 support.

The ES `ip` field does not support IPv6 Addresses, see https://www.elastic.co/guide/en/elasticsearch/reference/2.3/ip.html

It got tons of IPv6 bulk inserts which could not be mapped. 

Before that "fix" everything works.

Is it possible to revert the PR?

**Comment by C-Duv** [comment]
Using [`ntopng_template_elk.json` template](https://github.com/ntop/ntopng/blob/dev/httpdocs/misc/ntopng_template_elk.json) I am still having `IPV4_DST_ADDR` and `IPV4_SRC_ADDR` being indexed as strings.

**Steps:**
- Stop `ntopng`
- Delete Kibana Index Pattern
- Delete ES index
- Apply template `curl -s https://raw.githubusercontent.com/ntop/ntopng/dev/httpdocs/misc/ntopng_template_elk.json | curl -XPUT http://127.0.0.1:9200/_template/ntopng_template -d @-`
- Start `ntopng`
- Wait for some trafic

**Expected result:**
Both `IPV4_DST_ADDR` `IPV4_SRC_ADDR` field should be considered of `ip` type.

**Actual result:**
Both `IPV4_DST_ADDR` `IPV4_SRC_ADDR` are of `string` type.

``` Shell
curl -s http://127.0.0.1:9200/_all/_mapping/flows/field/IPV4_DST_ADDR,IPV4_SRC_ADDR
```

``` JSON
{"ntopng.2016.07.19":{"mappings":{"flows":{"IPV4_SRC_ADDR":{"full_name":"IPV4_SRC_ADDR","mapping":{"IPV4_SRC_ADDR":{"type":"string"}}},"IPV4_DST_ADDR":{"full_name":"IPV4_DST_ADDR","mapping":{"IPV4_DST_ADDR":{"type":"string"}}}}}}}
```

**Using:**
- ntopng v2.5.160719-1445
- Elasticsearch v2.3.3
- Kibana v4.5.2

**Comment by simonemainardi** [comment]
Hi, thanks for the deep details given. I've just tried to reproduce the issue but IPV4 fields are indexed properly with type `ip`

![image](https://cloud.githubusercontent.com/assets/3397663/16960080/3298919e-4de8-11e6-83dc-ba1dc99432df.png)

```
Simones-MacBook-Pro:ntopng simone$ ./ntopng --version
v.2.5.160719 [Enterprise/Professional Edition]

Simones-MacBook-Pro:ntopng simone$ curl -XGET '192.168.2.129:9200'
{
  "name" : "node-1",
  "cluster_name" : "ntop",
  "version" : {
    "number" : "2.3.1",
    "build_hash" : "bd980929010aef404e7cb0843e61d0665269fc39",
    "build_timestamp" : "2016-04-04T12:25:05Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}

Kibana
Version 4.4.2
Build   9732
Commit SHA  b0ef773
```

**Comment by C-Duv** [comment]
:(
I'll try on fresh Kibana and ElasticSearch installations.

To prevent me from testing unrelated stuff, can you confirm that this is (to fair extent) an ES mapping issue only? Nothing could be misconfigured on ntopng or Kibana side: no settings to enable nor third-party module needed?

**Comment by simonemainardi** [comment]
I confirm the test above has been carried out on a zero-conf ES and Kibana. I cannot see any othe possible issue apart from the mapping. I would also like to tell you that you don't have to push the template manually. ntopng does it automatically.

**Comment by C-Duv** [comment]
Not pushing the template did the trick: thanks :)
I was still following [the FAQ](https://github.com/ntop/ntopng/wiki/02-Elasticsearch-FAQ) which suggest to push it.

**Comment by simonemainardi** [comment]
thanks for reporting. I updated the FAQ
