### ISSUE TITLE
Unable to send email + telegram

### ISSUE THREAD

**Issue by sunshiros** [ntop/ntopng#5480]
Hi,
Running ntopng Pro Embedded (Raspberry] on a Raspberry Pi 4 with the latest version of Raspbian and i get this error : Unable to send email

![email3](https://user-images.githubusercontent.com/2570633/121359244-f411e900-c93b-11eb-9d29-65d68be7a2cd.jpg)
![email1](https://user-images.githubusercontent.com/2570633/121359249-f5431600-c93b-11eb-8b09-dec0cd15f5b2.jpg)
![email2](https://user-images.githubusercontent.com/2570633/121359251-f6744300-c93b-11eb-9d31-1bb477ad6b54.jpg)

**Comment by simonemainardi** [comment]
Please, follow these instructions:

> The SMTP server to deliver the email. As an example, if you are using GMail you need to specify smtps://smtp.gmail.com:465. Please note that GMail also requires the <a href='https://myaccount.google.com/lesssecureapps'>Access for less secure apps</a> to be enabled.

I've also added them as notes straight into the email endpoint

![image](https://user-images.githubusercontent.com/3397663/121483353-5e736980-c9ce-11eb-9ce0-2f8d58ef3438.png)

**Comment by sunshiros** [comment]
I get this error. Also i do not see the notes. Did an update on ntopng but no updates.

![1](https://user-images.githubusercontent.com/2570633/121485685-186fd300-c9d9-11eb-8bde-b65a12e0d834.jpg)

**Comment by sunshiros** [comment]
![1](https://user-images.githubusercontent.com/2570633/121963947-7bfc5680-cd73-11eb-91f7-8758f625ffe3.jpg)

**Comment by sunshiros** [comment]
Same for telegram

![1](https://user-images.githubusercontent.com/2570633/122049600-48f5a980-cdeb-11eb-9566-6522ffe56683.jpg)
![2](https://user-images.githubusercontent.com/2570633/122049615-4bf09a00-cdeb-11eb-81a3-2a6041263e18.jpg)
[notifications.lua:30] [recipients.lua:707] ERROR: Error while sending notifications via Telegram Recipient - unable to send alerts to the telegram
ERROR: rrd_update_r() [/var/lib/ntopng/2/rrd/bytes.rrd][1623758463:21635] failed [/var/lib/ntopng/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623758463]

**Comment by cardigliano** [comment]
This has been fixed in 4ca5eb238e7e145857fbaf4e20dc2d96e4e86542 and fdd9a8f3990dac589d8508e3b71d025086154c4e
As of Telegram, please note it is now required to open the conversation with the bot in Telegram, before adding the ID in ntopng, otherwise the bot "can't initiate conversation with a user".
