### ISSUE TITLE
Alerts: Disable Empty Menu 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5486]
In ntopng, menu items are NOT reported when empty. For instance, a host with no TLS traffic does not show the TLS menu.

Alerts are not following this principle and this needs to be fixed as there are very annoying empty pages that need to be removed or at least disabled.

NOTE that if the landing tab of a page is empty, the default tab should move to the first populated tab, or if all empty report the issue.

![Screen Shot 2021-06-10 at 11 11 24](https://user-images.githubusercontent.com/4493366/121498366-a600f200-c9dc-11eb-9070-c298b94d3b5e.png)

**Comment by simonemainardi** [comment]
Implemented in the referenced commits.
