### ISSUE TITLE
Unable to double host number

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5487]
![Screen Shot 2021-06-10 at 12 17 45](https://user-images.githubusercontent.com/4493366/121508440-e31db200-c9e5-11eb-9319-cbd68d17b40d.png)
/etc/ntopng# ls -l ntopng.conf
-rw------- 1 ntopng ntopng 0 Jun 10 10:16 ntopng.conf

/etc/ntopng# ntopng-config  -X x2
/usr/bin/ntopng-config: line 79: /tmp/ntopng.conf: Permission denied
/usr/bin/ntopng-config: line 80: /tmp/ntopng.conf: Permission denied
-X option value succesfully changed. Now set to 262144.
root@ntopdev:/etc/ntopng# ntopng-config  -x x2
-x option value succesfully changed. Now set to 262144.

**Comment by simonemainardi** [comment]
Fixed. Now modals to change the config and/or restart ntopng are only shown on supported systems, i.e., linux systems running packaged versions of ntopng.
