### ISSUE TITLE
ntopng memory leak

### ISSUE THREAD

**Issue by tman24** [ntop/ntopng#549]
I probably update my ntopng pro install once a month, but following a recent update (and a number of rapid other updates to try and resolve the issue), I'm now seeing the ntopng process consume all available system memory within 24 hours of starting. Previous versions ran for months without any problems.

It's obviously a memory leak, but I haven't changed the config settings for a long time now. I'm not doing any flow capture - just basic promiscuous ring capture off 4 interfaces. Currently, I'm having to script kill/restart the process at 3am to keep things running.

Here's my (anonymized) config file;

--dns-mode 1
--interface eth0
--interface eth1
--interface eth2
--interface eth3
--local-networks "<5 local subnets>"
--http-port 3000
--data-dir /data/ntopng
--packet-filter="ip and not proto ipv6 and not ether host ff:ff:ff:ff:ff:ff and not net (224.0.0.0/8 or 239.0.0.0/8)"
--sticky-hosts local
--disable-autologout
--user ntop
--pid /data/ntopng/ntopng.pid
--daemon
# --verbose

The ntopng.log file is clean apart from one entry logged about 1 hour after the process restarts @ 3am

05/May/2016 04:00:01 [Lua.cpp:4598] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/hourly.lua][...ng/pro/scripts/lua/modules/top_scripts/top_aggregate.lua:110: attempt to index a nil value]

I don't know if this has any relevance to the problem though. Right now, the process has been running 7 hours and is consuming ~2GB RAM and increasing. Normally, it doesn't go above 300-350MB.

Host O/S is CentOS 6.7 (quad core, 16GB RAM). ntopng Pro is currently v.2.3.160422.

Advice appreciated.

**Comment by simonemainardi** [comment]
thanks for reporting. An inspection with valgrind highlighted some issues. They are fixed now. New packages will be available tomorrow.

**Comment by tman24** [comment]
Thanks for the quick reply and proposed fix. I'll update when the new packages are available and test.
