### ISSUE TITLE
Rework Behavior Code

### ISSUE THREAD

**Issue by MatteoBiscosi** [ntop/ntopng#5492]
There is a lot of duplicated code regarding the behavior analysis and this must be recoded by implementing a class and using it (currently used into score, traffic tx/rx of local hosts, interfaces, ases, networks).

**Comment by simonemainardi** [comment]
Referenced commit: https://github.com/ntop/ntopng/commit/f12934ef9eb67522974fa6c0add892b11f51891a

**Comment by simonemainardi** [comment]
Implementation is definitely better, thank you. However, I would have chosen to implement everything using class inheritance. That is, make AutonomousSystem, Network, subclasses of `AnalysisBehavior`. This would have make the cleaner. Did you consider using this approach?
