### ISSUE TITLE
Question about the version of the maxmind database.

### ISSUE THREAD

**Issue by vel21ripn** [ntop/ntopng#5494]
What version of the maxmind database is used for testing?
If possible, add to the repository the maxmind base files with which you ran the tests.

**Comment by vel21ripn** [comment]
When running tests, several lists are updated:
[startup.lua: 169] [lists_utils.lua: 420] Updating list 'Abuse.ch URLhaus' [https://urlhaus.abuse.ch/downloads/hostfile/]
[startup.lua: 169] [lists_utils.lua: 420] Updating list 'Emerging Threats' [https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt]
[startup.lua: 169] [lists_utils.lua: 420] Updating list 'Feodo Tracker Botnet C2 IP Blocklist' [https://feodotracker.abuse.ch/downloads/ipblocklist.txt]
[startup.lua: 169] [lists_utils.lua: 420] Updating list 'NoCoin Filter List' [https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt]
[startup.lua: 169] [lists_utils.lua: 420] Updating list 'SSLBL Botnet C2 IP Blacklist' [https://sslbl.abuse.ch/blacklist/sslipblacklist.txt]
[startup.lua: 169] [lists_utils.lua: 420] Updating list 'SSLBL JA3' [https://sslbl.abuse.ch/blacklist/ja3_fingerprints.csv]

Could this be the reason for testing errors?

**Comment by simonemainardi** [comment]
This is the database: https://db-ip.com/

It's distributed automatically inside package `ntopng-data`

Updating lists doesn't imply testing errors. It's normal.
