### ISSUE TITLE
Manage Data: InfluxDB

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5495]
it is requested to cleanup the data on InfluxDB as ntopng does with interfaces

**Comment by simonemainardi** [comment]
Currently, InfluxDB data is cleaned up when the interface data is deleted. We may decide to expose only the InfluxDB cleanup functionality.

**Comment by MatteoBiscosi** [comment]
Working in the latest ntopng version. Please reopen it's no more working
