### ISSUE TITLE
Not clear difference between alert and issue

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5498]
This is what ntopng reports in flows

![](https://cdn.discordapp.com/attachments/726060121905561671/852963134577967124/Screen_Shot_2021-06-11_at_19.30.40.png)

What's needed is
- Remove the word other
- Add a red triangle next to the most important issue of this flow indicating that an alert will eventually (if the configuration allows it) will be generated on it

Explain that the total flow score is the sum of the individual scores

**Comment by simonemainardi** [comment]
Implemented.

![image](https://user-images.githubusercontent.com/3397663/122070620-6aa85e00-cdf6-11eb-931c-26ee4a186618.png)
