### ISSUE TITLE
Implement L7 Protocol Behavioural Alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5499]
Add the ability to generate alerts when specific ASN have invalid traffic behaviour.

The script should take as input a list of protocols on which alerts can be generated ignoring all others.

This ticket depends on #5474

**Comment by MatteoBiscosi** [comment]
Implemented as requested. As discussed the behavior analysis starts as the alert is enabled and a restart of ntopng is required to start it.
