### ISSUE TITLE
pfring-dkms dependency

### ISSUE THREAD

**Issue by fanciulli** [ntop/ntopng#5502]
I have an ntopng host with auto upgrade option turned on. From command line I see the following:

$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 pfring-dkms : Depends: pfring (= 7.9.0-6618) but 7.9.0-6629 is installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

Executing apt --fix-broken install seems not to help

**Comment by cardigliano** [comment]
@fanciulli what Ubuntu/Debian version are you running?

**Comment by cardigliano** [comment]
This seems related to https://github.com/ntop/PF_RING/issues/724 which has been fixed today (new packages will be available for all OS later today)
