### ISSUE TITLE
Improve Flow Issues Formatting

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5509]
In the picture below yo have evidence of the problem
- one issue is duplicated
- bells and icons are not aligned: better to use a table or similar 

![Screenshot 2021-06-16 at 11 50 49](https://user-images.githubusercontent.com/4493366/122198101-228e4780-ce99-11eb-99d1-bef5d15a219c.png)

**Comment by simonemainardi** [comment]
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/3397663/122401161-a5d49980-cf7c-11eb-9f6f-310c32f524f9.png">
