### ISSUE TITLE
Inaccurate bandwidth usage and interface setting problems

### ISSUE THREAD

**Issue by retalieight** [ntop/ntopng#551]
Is ntopng not supposed to show traffic in real-time? I'm using nprobe but the traffic that's reported is all over the place and it doesn't seem like it lines up with my routers traffic. I have a Mikrotik router and I'm using traffic flow to send v9 netflow data to my Linux VM that runs nprobe. Do I need to tweak the sample rate? I also never see any remote to local traffic.. so I'm not sure that my interfaces are configured correctly. Can someone help me with this? :(

root@dev:/etc/nprobe# cat nprobe-eth0.conf
--collector-port=2055
-i=none
-n=none
--flow-version=9
--zmq=tcp://127.0.0.1:5556
--in-iface-idx=113
--out-iface-idx=110
--if-networks=00:E8:4C:68:12:C7@110,00:E8:4C:68:12:C8@113
--sample-rate=1:1

WAN interface is 00:E8:4C:68:12:C7
Bridge interface is 00:E8:4C:68:12:C8

I found the SNMP id's when I enabled the temporary ntopng pro and viewed my routers SNMP data but it still doesn't work. Do I need to include my WAN IP as a local address? Because it's showing up as a remote address?

![ntopng](https://cloud.githubusercontent.com/assets/10072572/15066893/3b7c8982-1332-11e6-85fe-f4d977af218c.png)

**Comment by simonemainardi** [comment]
make sure to update to the latest ntopng dev version and check again.

If you still experience the issue, then post also the ntopng configuration used.

You don't have to tune sample rate parameters, unless your mikrotik is sending flows of sampled data.

**Comment by chownsauce** [comment]
Thanks for the response!

Now I'm getting..

06/May/2016 12:46:34 [CollectorInterface.cpp:161] ERROR: Unable to uncompress ZMQ traffic: ntopng compiled without zlib

I don't see a configure flag for zlib or anything like that so I'm confused.

**Comment by retalieight** [comment]
Ok I'm stuck at configuring the dev release..

checking for curl_easy_perform in -lcurl... no
Please install libcurl(-dev) (http://curl.haxx.se/)

This is on Debian 7.10 (Wheezy) and I have libcurl and libcurl-dev installed which has curl_easy_perform. I tried using https://raw.githubusercontent.com/simonemainardi/ntopng/b71dd158f88c695d4c39745b02bf946c912c19e1/configure.seed which worked but it's missing Zlib compression support and other things. I then tried to compare both configure.seed files and can't figure out why this one works but not the one in the dev branch of the git repo.

**Comment by retalieight** [comment]
I was able to get it to compile after making some changes to pfring section of the configure.seed and it's working now but when I perform a speedtest on my 1Gbps connection it's still showing inaccurate bursts. I removed the sample rate stuff I had configured from my configs too.

![speedtest](https://cloud.githubusercontent.com/assets/10072572/15084491/6a6352aa-1399-11e6-995a-35d85d99c9d7.png)

**Comment by simonemainardi** [comment]
please post interface historical traffic.

I guess the mikrotik is reporting flows to nprobe with a frequency that is far to low to have a meaningful indication of the bursts.

For example, if you have a fully-utilized 1Gbps line that is reported every 10 seconds by the mikrotik, then you will see a 10Gbps spike every ten seconds as this is the information the nProbe gets.

Please, check out mikrotik configuration.
