### ISSUE TITLE
Upload a temporary pcap file

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#5510]
is it possible to create a Software interface in GUI in order to allow user to upload a temporary pcap file for offline pcap analysis with ntopng intelligence?

It could be right also for testing and trigger rules.

We know that there is an option to do it via CLI, but, GUI could be the solution for everyone.

**Comment by simonemainardi** [comment]
@cardigliano is this already doable using nBox?

**Comment by cardigliano** [comment]
Implemented in ntopng
