### ISSUE TITLE
Massive packet loss

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#5512]
When I use ntopng and continuous traffic recording, there are a lot of packet loss, and ntopng is slow, and takes up a lot of CPU
![image](https://user-images.githubusercontent.com/44804599/122345335-51c8b580-cf7a-11eb-9036-ce8db7a9f805.png)
![image](https://user-images.githubusercontent.com/44804599/122345495-80df2700-cf7a-11eb-9a6b-122f827a8eca.png)

**Comment by cardigliano** [comment]
Please also provide:
- cat /proc/cpuinfo
- top pressing 1 to get all core stats

**Comment by MaoPann** [comment]
I have 8 CPUs, need to handle 10 span interfaces, and 7gnprobe streams
![image](https://user-images.githubusercontent.com/44804599/122349625-ffd65e80-cf7e-11eb-88a8-fb90659dd306.png)

**Comment by MaoPann** [comment]
I have 8 CPUs, need to handle 10 span interfaces, and 7 nprobe flow port 
![image](https://user-images.githubusercontent.com/44804599/122349886-43c96380-cf7f-11eb-8dda-3acab206cc0e.png)

**Comment by MaoPann** [comment]
![image](https://user-images.githubusercontent.com/44804599/122354911-06b3a000-cf84-11eb-9bb7-07635b3487ab.png)

**Comment by MaoPann** [comment]
![image](https://user-images.githubusercontent.com/44804599/122358586-5b0c4f00-cf87-11eb-86f0-c70b07df908e.png)

**Comment by MaoPann** [comment]
![image](https://user-images.githubusercontent.com/44804599/122360561-0d90e180-cf89-11eb-9dac-5db4a4eb6036.png)

**Comment by cardigliano** [comment]
@MaoPann please provide *all* the information I requiested in order to dig into this issues and help you:
- top pressing 1 to get all core stats
- ntopng configuration file
My impression is that you are writing to a disk which is not adequate, affecting also the performance due to IO slowdowns.

**Comment by MaoPann** [comment]
OK, I will provide that information as soon as possible.

**Comment by MaoPann** [comment]
--max-num-flows=200000
--max-num-hosts=20000
-i tcp://127.0.0.1:5556
-i tcp://127.0.0.1:5557
-i tcp://127.0.0.1:5558
-i tcp://127.0.0.1:5560
-i tcp://127.0.0.1:5565
-i tcp://127.0.0.1:5570
-i tcp://127.0.0.1:5590
-i tcp://127.0.0.1:5600

-i=eth1
-i=eth2
-i=eth3
-i=eth4
-i=eth5
-i=eth6
-i=eth7
-i=eth8
-m=172.*.0/12,10.*.0/24
-F=mysql;172.30.81.107;ntopng;flows;*;*
-G=/var/run/ntopng.pid
![image](https://user-images.githubusercontent.com/44804599/122869789-5668e180-d35f-11eb-9687-b9fa05e4e3f4.png)

**Comment by MaoPann** [comment]
@cardigliano

**Comment by cardigliano** [comment]
@MaoPann I think you have too much pressure on the disk, n2disk is using the disk affecting the ntopng performance for IO operations, what disk model (or raid configuration) are you using?
