### ISSUE TITLE
Invalid score report

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5516]
![Screen Shot 2021-06-17 at 21 39 58](https://user-images.githubusercontent.com/4493366/122462294-b6086b00-cfb4-11eb-9869-ede119954ac1.png)

As you can see from the picture
- there is a score set to 1 (not possible as this is below the minimum score)
- when set to 1, the number is unreadeable

**Comment by simonemainardi** [comment]
Fixed in the latest build.
