### ISSUE TITLE
Interface alerts should not be cut in length

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5520]
![Screen Shot 2021-06-18 at 10 02 10](https://user-images.githubusercontent.com/4493366/122528720-f1d71b00-d01c-11eb-9ec3-e86a041ca4e0.png)

**Comment by simonemainardi** [comment]
Now interface alerts, as any other alert, have a searchable, sortable column 'subject', that gives additional information on who's causing the matter.

After the latest rework, the table columns are organized as follow:

First, we show WHEN the issue has occurred. Second, we show WHAT is the issue about.  Third, we show WHO is causing the issue. Finally, hidden in a spillover column, we show the full issue description.

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/3397663/123622101-23659880-d80c-11eb-8ad6-71b1181c5f62.png">
