### ISSUE TITLE
Score Anomaly poorly formatted

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5522]
![Screen Shot 2021-06-18 at 09 50 47](https://user-images.githubusercontent.com/4493366/122529551-e59f8d80-d01d-11eb-8c28-49dad786980d.png)

**Comment by martinscheu** [comment]
Hi @MatteoBiscosi 
I checked on ntopng Enterprise L v.4.3.210612 (Ubuntu 20.04.2 LTS) and I would say somehow still info missing?
Or what do the 3 dots at the end mean?
<img width="1395" alt="Screenshot 2021-06-21 at 14 48 01" src="https://user-images.githubusercontent.com/38549755/122764367-b304c780-d29f-11eb-9ae9-fe8c2b12acde.png">
and if no file is listed?
<img width="1428" alt="Screenshot 2021-06-21 at 14 48 41" src="https://user-images.githubusercontent.com/38549755/122764496-d29bf000-d29f-11eb-8d97-ab4a2260bb1e.png">

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu sorry for the late response but i didn't see the question. The 3 dots means that the file num has been cut because too long. @VasilisTako however added a question mark to be able to check the entire name.
