### ISSUE TITLE
Lateral Movement Alerts are Poorly Formatted

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5524]
![Screen Shot 2021-06-17 at 21 42 48](https://user-images.githubusercontent.com/4493366/122529745-197ab300-d01e-11eb-83ab-ef12b40ad93b.png)

**Comment by simonemainardi** [comment]
![image](https://user-images.githubusercontent.com/3397663/122904694-dcc9f700-d350-11eb-9a83-4cfb1124ca7e.png)
