### ISSUE TITLE
[Regression] GeoMap is empty

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5526]
![image](https://user-images.githubusercontent.com/4493366/122536128-8002cf80-d024-11eb-96cb-76d852092616.png)
![image](https://user-images.githubusercontent.com/4493366/122536184-8db85500-d024-11eb-9d7d-e449c224b135.png)

**Comment by lucaderi** [comment]
![Screen Shot 2021-06-23 at 14 45 52](https://user-images.githubusercontent.com/4493366/123098821-d3fd2200-d431-11eb-9676-56f18ccf0253.png)

![Screen Shot 2021-06-23 at 14 47 50](https://user-images.githubusercontent.com/4493366/123098967-01e26680-d432-11eb-979c-d50caedb59fe.png)

Still bugged. As you can see there are plenty of hosts, GeoIP is configured good and country flags are reported.

**Comment by simonemainardi** [comment]
please check the AJAX request performed and post the response.

**Comment by lucaderi** [comment]
Nothing changed, same result.
<img width="752" alt="Screenshot 2021-06-29 at 21 53 25" src="https://user-images.githubusercontent.com/4493366/123859022-7599dd00-d924-11eb-8643-a8cf0d41396f.png">

**Comment by lucaderi** [comment]
Verified as fixed
