### ISSUE TITLE
Symbolic VLAN names are not supported in all pages

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5527]
As the user can not set a symbolic VLAN name, this feature must be propagated in all pages. Examples of issues

![image](https://user-images.githubusercontent.com/4493366/122537870-4c28a980-d026-11eb-9f58-2694e72832fc.png)

![image](https://user-images.githubusercontent.com/4493366/122537907-577bd500-d026-11eb-9cd5-5d3065d5eb7c.png)

![image](https://user-images.githubusercontent.com/4493366/122537942-606ca680-d026-11eb-9f7d-2a241792b786.png)

![image](https://user-images.githubusercontent.com/4493366/122538004-6bbfd200-d026-11eb-873b-d2ca96f0a551.png)

![image](https://user-images.githubusercontent.com/4493366/122610090-5c20a780-d07f-11eb-90d4-c5e91890479d.png)

**Comment by lucaderi** [comment]
@VasilisTako @MatteoBiscosi Still bugged
![Screen Shot 2021-06-18 at 22 02 19](https://user-images.githubusercontent.com/4493366/122611022-e74e6d00-d080-11eb-9328-20e5be27fe0b.png)
![Screen Shot 2021-06-18 at 22 02 12](https://user-images.githubusercontent.com/4493366/122611028-e9183080-d080-11eb-9897-5d1e0123abc1.png)
![Screen Shot 2021-06-18 at 22 02 05](https://user-images.githubusercontent.com/4493366/122611029-e9b0c700-d080-11eb-9be4-ba75c59c0208.png)

**Comment by MatteoBiscosi** [comment]
This ticket should be implemented as requested, please reopen if you find some vlan without the alias
