### ISSUE TITLE
ASN Traffic Behaviour Charts must be alike (filled)

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5528]
![Screen Shot 2021-06-18 at 11 23 48](https://user-images.githubusercontent.com/4493366/122539243-ad9d4800-d027-11eb-94fc-755b395b0708.png)
![Screen Shot 2021-06-18 at 11 23 39](https://user-images.githubusercontent.com/4493366/122539250-ae35de80-d027-11eb-84cb-c4ba7726d0cd.png)

**Comment by MatteoBiscosi** [comment]
Verified as Fixed with the last update
