### ISSUE TITLE
Invalid AS Behavioural Counters

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5529]
![Screen Shot 2021-06-18 at 11 23 48](https://user-images.githubusercontent.com/4493366/122539410-df161380-d027-11eb-8cf4-9ec25b9f661f.png)

It seems there is a bug in the implementation as the value range , as the prediction is far from being correct. probably due to 64 bit values?

**Comment by MatteoBiscosi** [comment]
Verified as Fixed with the last update
