### ISSUE TITLE
[Regression] Broken interface alerts page

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5534]
![image](https://user-images.githubusercontent.com/3397663/122739972-d1f56080-d283-11eb-8ca7-b6ca9f27cfee.png)

**Comment by simonemainardi** [comment]
introduced with d0b0f34091e9cb0d2c33d89122404b042f6ce278

**Comment by MatteoBiscosi** [comment]
The problem with the column name should be fixed now for both the interface and local network alerts
