### ISSUE TITLE
[Regression] Broken alert formatting

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5536]
Host location (see L) is now back, unformatted, in the alerts page even though in a previous (closed resolved) issue it was asked to remove labels and positions to hosts in the alerts page

![image](https://user-images.githubusercontent.com/3397663/122741582-60b6ad00-d285-11eb-9d81-ae18922b55cc.png)

**Comment by MatteoBiscosi** [comment]
With @cardigliano, we decided to remove the host category (local host, remote host, ...) from all the alert descriptions, in fact the description is "purified" from the html tags and this causes the bug above.
