### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#5538]
I built ntopng 4.2-1 on Arch Linux, gcc 11.1.0 and i get an "Assertion failed" moments after startup completes.
The web interface shows one or two outgoing packets but then it crashes immediately.
The error:
`/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/bits/stl_vector.h:1045: std::vector::reference std::vector<Flow *>::operator[](std::vector::size_type) [_Tp = Flow *, _Alloc = std::allocator<Flow *>]: Assertion '__n < this->size()' failed.`
Tried on two different machines.

**Comment by simonemainardi** [comment]
please run it within gdb and provide a stack trace

**Comment by ghost** [comment]
Sorry for not including it right away. Trace: https://pastebin.com/2J4rftBc

**Comment by ghost** [comment]
I should add that the crash only occurs when ntopng is active on an interface with traffic.
When my laptop is on wifi and i specify `ntopng -i eth0`, which is unplugged, i don't get the crash.

**Comment by simonemainardi** [comment]
Please, build the latest dev (tip of branch `dev` and report)

**Comment by ghost** [comment]
No crash with the current `dev` :+1:  ! As far as i can tell, everything is working as expected. CPU usage is at 100% though, i will build `dev` with -O2 now and see what happens.

**Comment by simonemainardi** [comment]
Thanks for reporting.

**Comment by ghost** [comment]
CPU usage is still pretty crazy, is this normal? It spikes 90-110%. Other Arch users have the same problem apparently: https://aur.archlinux.org/packages/ntopng/

**Comment by simonemainardi** [comment]
It's definitely not normal. Are you able to troubleshoot/profile this? Unfortunately, arch linux is not among the distros we officially support and cannot play with it now.

**Comment by ghost** [comment]
Sure, i'll take a look and open a new issue. I understand Arch is not supported, thanks for your help anyway.
