### ISSUE TITLE
nprobe configuration

### ISSUE THREAD

**Issue by jjirasek** [ntop/ntopng#554]
Hi, I have mikrotik router with cca 1gbit traffic. Router has several internal interfaces and several
external interfaces. On internal interfaces I have some users, external interfaces is peers to internet providers with BGP. Router also makes NAT for local users.

I want to see historical traffic of users in charts and I want to check who visited some host in internet in specific time. I want to store several months back.

I'm trying nprobe+ntopng

Mikrotik has this setting:
/ip traffic-flow
set active-flow-timeout=5m enabled=yes interfaces=vlan520@sfp5,vlan521@sfp5,vlan522@sfp5,vlan523@sfp5
/ip traffic-flow target
add dst-address=x.x.x.x port=8888

interface vlan520@sfp5 has snmp index 13, vlan521@sfp5 14, ...

ntopng settings:
--dns-mode 3
--interface tcp://127.0.0.1:5556
--data-dir /var/tmp/ntopng
--http-port 8080
--redis 127.0.0.1:6379
--local-networks 192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,x.x.x.0/20
--mysql=localhost:ntop::root:xxxxxx

nprobe settings:
--collector-port 8888
--interface none
--collector none
--local-networks 192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,176.12.112.0/20
--zmq tcp://127.0.0.1:5556
--mysql=localhost:ntop::root:xxxxxx

Instalation works, nprobe is version v.7.2.160414, ntopng is v.2.2.160414

I have questions:
1. I want to see four local mikrotik in ntopng separately. I can run I can run several instances of
nprobe. I want to say to every instance of nprobe that it resends only INPUT_SNMP or OUTPUT_SNMP number 14 (next instance 15...).I played with parameteter --in-iface-idx
and  --out-iface-idx but in dumped flows (--dump-path /tmp/ntop) I still see all interfaces.
1. how several instances of nprobe will work with the same mysql setting? May I distinguish interfaces in mysql parameter ? (like  --mysql=localhost:ntop:ins1:root:xxxxxx --mysql=localhost:ntop:ins2:root:xxxxxx)
2. how ntopng is connected with historical flows stored by nprobe?  Is this parameter enough (--mysql=localhost:ntop::root:xxxxxx) ?
3. When I look in mysql table, I see  INPUT_SNMP and OUTPUT_SNMP empty, but in dump files
   is filled with snmp indexes from mikrotik
4. I try download 4GB DVD, download started from 21.55 and finished at 22:25. Download speed
   was 20mbit. When I look on chart, I see 12mbit for 10 minutes, so if I count it, chart
   say to me I downloaded 900MB. (I look on chart next day)
5. Can I now zoom chart for this one day? I find only possibility to click 1w.
6. I try dump data to sqlite database with nprobe. It works, but is there possibility split files after some time? Can nprobe add indexes to database?

Thank you, Jaroslav Jirasek

**Comment by simonemainardi** [comment]
> how several instances of nprobe will work with the same mysql setting? May I distinguish interfaces in mysql parameter ? (like --mysql=localhost:ntop:ins1:root:xxxxxx --mysql=localhost:ntop:ins2:root:xxxxxx)

if you use mysql on ntopng, then you don't need to use it also in nProbe. Let the ntopng dump flows to the database. there is a column interface id that can be used to distinguish interfaces.

> how ntopng is connected with historical flows stored by nprobe? Is this parameter enough (--mysql=localhost:ntop::root:xxxxxx) ?

ntopng doesn't read nprobe stored flows. ntopng reads the flows it has previously dumped.

> I try download 4GB DVD, download started from 21.55 and finished at 22:25. Download speed
> was 20mbit. When I look on chart, I see 12mbit for 10 minutes, so if I count it, chart
> say to me I downloaded 900MB. (I look on chart next day)

check if the exported data is sampled.

> Can I now zoom chart for this one day? I find only possibility to click 1w.

yes, you can adjust the zoom level by clicking on the chart around the intervals you are interested to.

> I try dump data to sqlite database with nprobe. It works, but is there possibility split files after some time? Can nprobe add indexes to database?

you can add custom indices to the database. You don't need nprobe for that
