### ISSUE TITLE
Suspicious file transfer - false positive

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5540]
Hi ntop team
The Suspicious File Transfer alert is triggered often.
E.g. from anti virus scanners or internal windows update servers.
<img width="1038" alt="Screenshot 2021-06-21 at 14 53 53" src="https://user-images.githubusercontent.com/38549755/122765173-856c4e00-d2a0-11eb-8681-f2c65d629234.png">
<img width="1206" alt="Screenshot 2021-06-21 at 14 56 44" src="https://user-images.githubusercontent.com/38549755/122765553-ea27a880-d2a0-11eb-874a-36d34df4cecf.png">

**Comment by lucaderi** [comment]
Depends on https://github.com/ntop/nDPI/issues/1231

**Comment by martinscheu** [comment]
not sure if algorithm can be improved, but with the now available option to fast filter / filter out alerts and then acknowledge them or allow / deny list them, we could sort out the false positives in a easy way.
Only for not so experienced user it might be confusing, as he might not know what WSUS is or AV scanners are, so having an exlusion / allow list would be helpful.
Thank you

**Comment by lucaderi** [comment]
This issue should be solved by noe
