### ISSUE TITLE
[Regression] Dangerous hosts not ending up in the jailed hosts pool

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5543]
Even with dangerous hosts alerts

![image](https://user-images.githubusercontent.com/3397663/122779188-efd7bb00-d2ad-11eb-8d43-1545004d6d42.png)

The jailed hosts pool is empty

![image](https://user-images.githubusercontent.com/3397663/122779290-054ce500-d2ae-11eb-9d0f-dea011205f1b.png)

**Comment by MatteoBiscosi** [comment]
The jailed host pool is working fine, infact as you can see the hosts are correctly added to the pool.
![Screenshot from 2021-06-22 10-49-52](https://user-images.githubusercontent.com/49585191/122894811-d420f300-d347-11eb-8da7-18efbc64b70b.png)
![Screenshot from 2021-06-22 10-50-01](https://user-images.githubusercontent.com/49585191/122894813-d4b98980-d347-11eb-833b-2faf50d103d8.png)
In your case i just saw that the alert was triggered for more then 15 min. The correct behavior of this Pool is to ban them for at most 15 minutes, so probably, in your case, they were banned and after 15 minutes of ban they were released and this triggered your case, but this is it's natural workflow.
However 15 minutes is probably too few so I extended the period to 30 minutes.
