### ISSUE TITLE
Alerts Filtering - show only items which are present

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5545]
Hi ntop team

In previous versions of ntopng the filter drop down only showed items which have entries in the lists.
Example:
<img width="794" alt="Screenshot 2021-06-21 at 17 30 32" src="https://user-images.githubusercontent.com/38549755/122788261-709ab500-d2b6-11eb-8dd2-8bc87a17388c.png">
means possible XSS error was present.

This helped a lot to fast filter alerts.

In current setup I never know if an entry is in the list or not.

thanks

**Comment by cardigliano** [comment]
@martinscheu we decided to show all alert types to allow filtering also on those not present/displayes in the selected interval (e.g. when setting the alert type and then changing the interval), this also improves db queries. Please note that the top alerts are diaplayed to give an hint about those actually present, and we should probably add a full list somewhere in future.

**Comment by martinscheu** [comment]
@cardigliano thanks for the explanation. Our workflow is to search for anomalies, i.e. we don't know what we are looking for. We start with biggest time frame and then look for unexpected applications, therefore the ancient pre-filter of only showing applications present in the events, helped a lot. The top alerts helps, but often what we are looking for is at the end of the top list, like one odd flow. Performance is an issue, but I would be happy to wait 2 seconds for an application list only showing present applications. Thanks
