### ISSUE TITLE
Invalid Value Formatter

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5550]
![image](https://user-images.githubusercontent.com/4493366/122894664-afc51680-d347-11eb-93bf-a351c237aa59.png)

The value in green is definitively wrong, as wrong is the formatted value in the alert generated on this graph

![image](https://user-images.githubusercontent.com/4493366/122894919-eb5fe080-d347-11eb-8584-7fda9f6efcfc.png)

**Comment by MatteoBiscosi** [comment]
Fixed into pro repo, please reopen if needed
