### ISSUE TITLE
Alert Filter Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5551]
![Screen Shot 2021-06-22 at 10 53 34](https://user-images.githubusercontent.com/4493366/122895166-23672380-d348-11eb-90a3-ca1e3eb8a1ca.png)
![Screen Shot 2021-06-22 at 10 54 20](https://user-images.githubusercontent.com/4493366/122895241-3843b700-d348-11eb-9289-68be8d011160.png)

**Comment by cardigliano** [comment]
Fixed in https://github.com/ntop/ntopng/commit/5319933cf17783f72a8c3b50d4e02996fc78b740
Also, the alert type filter has been added for the 'other' families in 279ed66deb7583336a9bba34619b5db3f13cc5be
