### ISSUE TITLE
Behavior: Invalid Aggregated Metrics (Average, Maximum)

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5552]
![image](https://user-images.githubusercontent.com/3397663/122895730-adaf8780-d348-11eb-8acb-854913970124.png)

- The maximum is wrong, it seems to be computed as the sum of the value + lower bound + upper bound whereas it should just be the value
- The average is wrong, it cannot be 221.
- Value should be called "Score", not value

**Comment by MatteoBiscosi** [comment]
Implemented as discussed with @lucaderi
