### ISSUE TITLE
Current physical interface utilization(flow exporter) and ntopng logical interface utilization does not match for Netstream flow traffic(Huawei) 

### ISSUE THREAD

**Issue by ankan1979** [ntop/ntopng#5553]
Hi,

Real traffic utilization of physical port(flow exporter ports)and ntopng logical interface showing different bandwidth utilization. I have increased the sampler a lot but still, traffic is showing the same. A few days ago I have sent the same flow to the Kentik flow analyzer and it was working perfectly fine there. 
[NTOP_interfaces.txt](https://github.com/ntop/ntopng/files/6695092/NTOP_interfaces.txt)
[ntopmg.txt](https://github.com/ntop/ntopng/files/6695093/ntopmg.txt)
![ntopng](https://user-images.githubusercontent.com/86306689/122942404-d14bef80-d393-11eb-80c6-ea5f80bdfedc.png)
[ntopmg.txt](https://github.com/ntop/ntopng/files/6695100/ntopmg.txt)
![ntopng](https://user-images.githubusercontent.com/86306689/122942493-e1fc6580-d393-11eb-817f-166f87b1f694.png)
 Please find the attachment for logs.

**Comment by lucaderi** [comment]
How did you configure nProbe? Have you configured [--sample-rate|-S] <pkt rate>:<flow collection rate>:<flow export rate>
in nprobe? If not this is the problem

**Comment by ankan1979** [comment]
Hi Luca,

Thanks for your reply. No, I can't see any entry as mentioned above. I have
created total of seven logical interfaces and receiving multiple types of
flows like netflow,sflow etc from multiple devices and those are showing
accurate results.  The issue is happening only with Netstream. Can you
help me by giving documentation or send what the exact line I need to put
and in which location.

Regards,

Ankan

**Comment by simonemainardi** [comment]
@ankan1979 sorry for the late reply. Do you have / can you generate a Netstream pcap that we can use to reproduce the issue in our lab?

**Comment by ankan1979** [comment]
Hi  Simone,

Please find the PCAP file.

Regards,

Ankan

**Comment by simonemainardi** [comment]
There's no pcap attached. Please check.

**Comment by ankan1979** [comment]
Hi Simone,

Please find the attachment.

**Comment by simonemainardi** [comment]
There is no pcap attached. Please, don't respond to the email. Visit the GitHub issue page and attach the file from there.

**Comment by ankan1979** [comment]
Hi Simone,

I am trying to attach  but the file format is not supporting it. Can I send it to your telegram chat?

Regards,

Ankan

**Comment by simonemainardi** [comment]
zip it and it will work

**Comment by ankan1979** [comment]
Hi Simone,

Yes, I missed sorry.
[netstream.zip](https://github.com/ntop/ntopng/files/6884533/netstream.zip)

**Comment by simonemainardi** [comment]
Attached pcap doesn't contain enough information. Templates are missing:

![image](https://user-images.githubusercontent.com/3397663/127140167-6a250e91-08b6-4b01-ae71-ce5c2f4f4e71.png)


Let the capture running for longer, make sure there are templates inside, and re attach. Thank you.

**Comment by ankan1979** [comment]
Hi Simone,

Please check this one.
[netstream1.zip](https://github.com/ntop/ntopng/files/6886415/netstream1.zip)

**Comment by simonemainardi** [comment]
I did an investigation using the file provided. I have done a replay of the netstream and fed it to nProbe and, in turn, ntopng.

I see there's a perfect match between the traffic seen under the exporters section (now renamed to probes) and the traffic measured in the interface. See

![image](https://user-images.githubusercontent.com/3397663/127986398-ae465f64-885e-4489-aa81-c7cfe5c19ec1.png)

So I am not sure about the meaning of 

> Real traffic utilization of physical port(flow exporter ports)and ntopng logical interface showing different bandwidth utilization. 

Can you please be more specific and attach examples?

**Comment by MaoPann** [comment]
@simonemainardi Hi, I have encountered a similar problem. Please check the netstream pacp file below.
[netstream.zip](https://github.com/ntop/ntopng/files/6935736/netstream.zip)

**Comment by simonemainardi** [comment]
> Can you please be more specific and attach examples?

@MaoPann

**Comment by ankan1979** [comment]
Hi Simone,

Please find the attachment. The snaps are taken for both Netstream and sFlow enabled devices with a sample rate of 
![interface_real_traffic_utilization_sflow_enabled](https://user-images.githubusercontent.com/86306689/128306017-b8a078e7-24cb-4bd2-a9da-cb9399c331bd.png)
![sflow_int_real_traffic_show_accurate](https://user-images.githubusercontent.com/86306689/128306025-92be7264-80de-4abc-84c7-b409d8755cd2.png)
![interface_real_traffic_utilization_netstream_enabled](https://user-images.githubusercontent.com/86306689/128306027-3f5744f4-f8a1-42c6-9d94-3346f2575d73.png)
![netstream_int_real_traffic_show_less](https://user-images.githubusercontent.com/86306689/128306028-d752dc45-24a1-46f1-a226-b12194743541.png)
15k for Netstream for a single interface and 55k per interface for sFlow 4x10G LACP bundle.

**Comment by MaoPann** [comment]
> > Can you please be more specific and attach examples?


@simonemainardi  Hi,The situation I encountered is the same as ankan1979 above. I recorded a detailed test video and provide detailed information to help you solve the problem. The test information is not convenient to post on github. I will send it to you via email, please check it.

**Comment by MaoPann** [comment]
@simonemainardi Hi， Did you get my email?

**Comment by lucaderi** [comment]
After checking the data you sent me, the result of the investigation is that netstream or the way it has been configured is the source of the problem, not ntopng
