### ISSUE TITLE
Severe Alert Drops

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5558]
![Screen Shot 2021-06-23 at 14 50 06](https://user-images.githubusercontent.com/4493366/123099283-5685e180-d432-11eb-8f3a-4d3f3f5c91cf.png)
![Screen Shot 2021-06-23 at 14 49 56](https://user-images.githubusercontent.com/4493366/123099290-571e7800-d432-11eb-8acc-279bc12338ac.png)
![Screen Shot 2021-06-23 at 14 49 43](https://user-images.githubusercontent.com/4493366/123099291-57b70e80-d432-11eb-8986-85b98f5339b5.png)
![Screen Shot 2021-06-23 at 14 49 29](https://user-images.githubusercontent.com/4493366/123099292-57b70e80-d432-11eb-92a2-a6259681bd00.png)
![Screen Shot 2021-06-23 at 14 51 08](https://user-images.githubusercontent.com/4493366/123099440-7ae1be00-d432-11eb-9516-dcb13cc5e1e3.png)

No errors on the console

Jun 23 12:42:24 ntopdev ntopng[3585535]: 23/Jun/2021 12:42:24 [Utils.cpp:766] User changed to ntopng
Jun 23 12:42:24 ntopdev ntopng[3585535]: 23/Jun/2021 12:42:24 [NetworkInterface.cpp:2723] Started flow user script hooks loop on interface ens3f0 [id: 8]...
Jun 23 12:42:24 ntopdev ntopng[3585535]: 23/Jun/2021 12:42:24 [NetworkInterface.cpp:2754] Started host user script hooks loop on interface ens3f0 [id: 8]...
Jun 23 12:42:24 ntopdev ntopng[3585535]: 23/Jun/2021 12:42:24 [NetworkInterface.cpp:2723] Started flow user script hooks loop on interface tcp://127.0.0.1:1234 [id: 9]...
Jun 23 12:42:24 ntopdev ntopng[3585535]: 23/Jun/2021 12:42:24 [NetworkInterface.cpp:2754] Started host user script hooks loop on interface tcp://127.0.0.1:1234 [id: 9]...
Jun 23 12:42:24 ntopdev ntopng[3585535]: 23/Jun/2021 12:42:24 [main.cpp:401] Working directory: /var/lib/ntopng
Jun 23 12:42:24 ntopdev ntopng[3585535]: 23/Jun/2021 12:42:24 [main.cpp:403] Scripts/HTML pages directory: /usr/share/ntopng
Jun 23 12:42:24 ntopdev ntopng[3585535]: 23/Jun/2021 12:42:24 [Ntop.cpp:476] Welcome to ntopng x86_64 v.4.3.210623 - (C) 1998-21 ntop.org
Jun 23 12:42:24 ntopdev ntopng[3585535]: 23/Jun/2021 12:42:24 [Ntop.cpp:486] Built on Ubuntu 20.04.2 LTS

...
Jun 23 12:42:24 ntopdev ntopng[3585535]: 23/Jun/2021 12:42:24 [PeriodicActivities.cpp:107] Started periodic activities loop...
Jun 23 12:42:25 ntopdev ntopng[3585535]: 23/Jun/2021 12:42:25 [startup.lua:37] Processing startup.lua: please hold on...
Jun 23 12:42:29 ntopdev ntopng[3585535]: 23/Jun/2021 12:42:29 [startup.lua:169] [lists_utils.lua:783] Refreshing category lists...
Jun 23 12:42:29 ntopdev ntopng[3585535]: 23/Jun/2021 12:42:29 [startup.lua:169] [lists_utils.lua:721] Category Lists (1860 hosts, 4792 IPs, 99 JA3) loaded in 0 sec
Jun 23 12:42:29 ntopdev ntopng[3585535]: 23/Jun/2021 12:42:29 [startup.lua:288] Completed startup.lua
Jun 23 12:42:29 ntopdev ntopng[3585535]: 23/Jun/2021 12:42:29 [PeriodicActivities.cpp:168] Each periodic activity script will use 3 threads
Jun 23 12:42:29 ntopdev ntopng[3585535]: 23/Jun/2021 12:42:29 [NetworkInterface.cpp:2905] Started packet polling on interface ens3f0 [id: 8]...
Jun 23 12:42:29 ntopdev ntopng[3585535]: 23/Jun/2021 12:42:29 [NetworkInterface.cpp:2905] Started packet polling on interface tcp://127.0.0.1:1234 [id: 9]...
Jun 23 12:42:30 ntopdev ntopng[3585535]: 23/Jun/2021 12:42:30 [ZMQCollectorInterface.cpp:256] Collecting flows on tcp://127.0.0.1:1234

Note that
- this is a beefy system with fast storage
- the number of alerts dropped is not formatted with a comma

**Comment by simonemainardi** [comment]
After internal review, using added traces, we have seen the issue is due to a slow SQLite. For the time being, we decided not to replace the internal database. To mitigate drops, it is currently possible to disable those user scripts or flows that are responsible for most alerts.
