### ISSUE TITLE
OOM when ntopng webui left open for 30+ hours

### ISSUE THREAD

**Issue by nate-byrnes** [ntop/ntopng#556]
I'm running ntopng (licensed) on a server with 40GB RAM.  (I started out with 8GB, and was getting OOM's then too, but figured I was retaining too much data, so upgraded the server to 40). If I do not leave a browser open watching the web UI continuously, It seems that the server process of ntopng can continue running (see attached screen crop, this shows the longest ntopng has continued running so far).  As of the screenshot, the process is only consuming 2.6GB of RAM. I have used the webUI intermittently while this instance of the process is running, but I cannot leave it open (I'd like to leave UI on screen in my NOC 24x7...)

![ntop](https://cloud.githubusercontent.com/assets/19349744/15254173/7b66b3d4-1903-11e6-8140-1eee8850b54f.png)

Please let me know what additional information would be helpful.

**Comment by simonemainardi** [comment]
we have made some fixes recently. Please, upgrade ntopng to the latest nightly build and report back again. thank you.

**Comment by Queeq** [comment]
I experience this problem too, as I describe it in #486. With ntopng v.2.3.160516 it's still there (UI became unresponsive after it's been running for less than 5 minutes). I keep Autonomous Systems page open.

**Comment by nate-byrnes** [comment]
I've been running now for 7 days with v.2.3.160513... not sure what happened to Queeq
