### ISSUE TITLE
[Regression] Per-Application Charts exception

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5560]
Opening an interface application chart as

![image](https://user-images.githubusercontent.com/3397663/123135167-c6579480-d451-11eb-8b4e-7bae7f7f5f15.png)

triggers 

23/Jun/2021 18:33:44 [LuaEngineNtop.cpp:47] ERROR: ntop_get_ndpi_protocol_name : expected number[@pos 1], got nil

and the page does not fully renders

**Comment by MatteoBiscosi** [comment]
Fixed pro repo
