### ISSUE TITLE
Dark Theme Hides Severity Color

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5562]
![Screen Shot 2021-06-24 at 10 41 50](https://user-images.githubusercontent.com/4493366/123234042-e4b5a280-d4da-11eb-99da-b029cc7649c9.png)
![Screen Shot 2021-06-24 at 10 41 59](https://user-images.githubusercontent.com/4493366/123234153-fd25bd00-d4da-11eb-908e-0fed1841ed36.png)

**Comment by simonemainardi** [comment]
Verified fixed in the latest build.

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/3397663/123617396-7d179400-d807-11eb-864c-90dc7b9219f3.png">
