### ISSUE TITLE
Duplicate Alert Label/Description Content

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5563]
This is an example of inconsistency. Each alert page must contain a subject, a problem and an optional description. This is an example

![Screen Shot 2021-06-24 at 10 59 12](https://user-images.githubusercontent.com/4493366/123234446-3d853b00-d4db-11eb-9e75-72c1459e24f2.png)

For hosts alerts are kinda ok for content, with the subject (the host), the problem (e.g. score anomaly) and the description. The problem is that host alerts, as interface alerts are all mixed.

![Screen Shot 2021-06-24 at 11 02 50](https://user-images.githubusercontent.com/4493366/123235067-d320ca80-d4db-11eb-97eb-9b84a17b230c.png)

This ticket is to request to
- add individual columns for subject, alert and description
- Subject is the host IP (hosts, and this is ok), the subnet, the ASN, the interface name in interfaces (this is not ok)
- the alert column contains a short string that describes the problem. Example "Ghost Network Detected"
- the description contains a human-readable string with (optional) URL etc

All columns must be sortable (today they are not).

**Comment by simonemainardi** [comment]
subject column added 

![image](https://user-images.githubusercontent.com/3397663/123283427-ac7a8800-d50b-11eb-8bed-167d538f23a4.png)

ability to filter by subject added as well

![image](https://user-images.githubusercontent.com/3397663/123283481-b8664a00-d50b-11eb-94c3-1548bd989f90.png)

**Comment by simonemainardi** [comment]
Implemented.

> add individual columns for subject, alert and description

Subject column is now available. Filters can be created on that column as well.

![image](https://user-images.githubusercontent.com/3397663/123433331-a21fc300-d5cb-11eb-825d-b1838b871701.png)


> the alert column contains a short string that describes the problem. Example "Ghost Network Detected"

Several optimizations have been done to:
- Display nicely on most screen resolutions
- Show the problem first, and then the subject
- Avoid showing duplicate data and columns

Everything is in the referenced commits.
