### ISSUE TITLE
Missing back icon and invalid host alerts focus

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5566]
When in a host a user clicks on the chart icon

![image](https://user-images.githubusercontent.com/4493366/123236209-e54f3880-d4dc-11eb-8fb7-f13b4581e807.png)

jumps into the alerts page landing on the page below

![Screen Shot 2021-06-24 at 11 11 30](https://user-images.githubusercontent.com/4493366/123236261-f304be00-d4dc-11eb-8e02-50a50a523699.png)

Two issues have to be fixed
- As we're arriving from a host I expect to go into the host page with the filter selected to the host I am coming from
- There is no back icon in the menubar that allows me to return to the host

**Comment by simonemainardi** [comment]
Implemented.

> As we're arriving from a host I expect to go into the host page with the filter selected to the host I am coming from

Supported. Specifically, you are brought to the host alerts page, filtered with the selected host, as follow:
- If the host has alerts engaged, the engaged alerts tab is selected
- If the host has only past alerts, the past alerts tab is selected

> There is no back icon in the menubar that allows me to return to the host

Supported. For consistency, a back button has been added to all the navbars across ntopng. Position is `pull-right` to indicate it is something related to the navigation and not to the menu items.

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/3397663/123612812-2f992800-d803-11eb-92cb-a63219723cb4.png">
