### ISSUE TITLE
Invalid messages reported on console

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5567]
24/Jun/2021 11:15:52 [AnalysisBehavior.cpp:40] [ANOMALY] en3 [?????] [value: 100]
24/Jun/2021 14:04:45 [AnalysisBehavior.cpp:40] [ANOMALY] en3 [?
] [value: 239184082]
24/Jun/2021 14:04:46 [AnalysisBehavior.cpp:40] [ANOMALY] en3 [ASN 0 | traffic tx] [value: 227822213]

Note that ASN 0 does not exist as a VLAN 0. Putting it on screen, log etc is an error per se and it should be avoided.

**Comment by MatteoBiscosi** [comment]
Removed ASN 0 from both anomaly logs and alert description
