### ISSUE TITLE
[notifications.lua:12] [alert_consts.lua:416]

### ISSUE THREAD

**Issue by chicamaxi** [ntop/ntopng#5570]
Hello,

I constantly get these alert in my log:
[notifications.lua:12] [alert_consts.lua:416] ...
Alert key 64 redefined, skipping in alert_unexpected_smtp...
Alert key 66 redefined, skipping in alert_unexpected_ntp...
Alert key 63 redefined, skipping in alert_unexpected_dns_server
Alert key 80 redefined, skipping in alert_tls_old_version
Alert key 65 redefined, skipping in alert_unexpected_dhcp_server
from
c:\Program Files\ntopng\scripts\lua\modules\alert_definitions

any clues?

**Comment by simonemainardi** [comment]
ntopng version?

**Comment by chicamaxi** [comment]
ntopng Professional v.4.3.210218 (Windows) |

**Comment by simonemainardi** [comment]
Please, update to the latest version from https://packages.ntop.org/ and it will work.
