### ISSUE TITLE
NoIP flow

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#5573]
When I use the latest stable version of ntopng, there are a lot of noip flows.It's very strange.

![image](https://user-images.githubusercontent.com/44804599/123572444-d3340980-d7fe-11eb-8cfe-340d5897fb05.png)

**Comment by simonemainardi** [comment]
Please, attach ntopng configuration. Are you looking at tunneled traffic? Can you attach a pcap?

**Comment by MaoPann** [comment]
I fixed it, because i set this option
![image](https://user-images.githubusercontent.com/44804599/123605927-f2e32600-d82e-11eb-8e97-241885ef96e4.png)
