### ISSUE TITLE
Duplicated column data in alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5575]
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/4493366/123663433-ae5b8880-d836-11eb-9943-10a4040634ac.png">

The column alert must contain only the problem, avoid data duplication/redundancy and move everything else to the description column.

Furthermore the column is not sortable and this needs to be fixed too

**Comment by simonemainardi** [comment]
Implemented in the referenced commits.
