### ISSUE TITLE
FR: add info about from where flow comes from

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#558]
hi,
I use ntopng (ntopng Professional v.2.2.160512) in a big IPSEC VPN and it appears that sometimes it would be interesting to know from what device the flow comes from... more easy to identify an issue.
Si I ask as a feature request to get this information as a plus in flow details

regards

Nico

**Comment by simonemainardi** [comment]
the interface used gives you the source of the flow. The interface can be a physical device or a remote probe this doesn't matter. Look at the top-right menu "interface"

**Comment by Niko78** [comment]
I meant I would like to know the device that send netflow stream
I have ton of routers which send netflow data to my server... I just wanted to know from what device this particular flow comes from
maybe it's not possible, no problem
regards
nico

**Comment by simonemainardi** [comment]
this is totally possible: start one nProbe instance per router. Then start ntopng with as many -i as the nProbe instances.

You would have found it on your own with a quick issue search: for example: https://github.com/ntop/ntopng/issues/327
