### ISSUE TITLE
Invalid table layout in ZMQ Interfaces

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5584]
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/4493366/123863865-6158de80-d92a-11eb-8d3a-d8fb7f05c70a.png">

As you can see the table is not properly formatted

**Comment by simonemainardi** [comment]
now normal interfaces are broken

![image](https://user-images.githubusercontent.com/3397663/123960944-26998980-d9b0-11eb-84a7-1aa6b9752402.png)
