### ISSUE TITLE
Behavior Preferences should be set from the Checks

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5587]
It is requested to remove those preferences 

![image](https://user-images.githubusercontent.com/3397663/123980203-a54af280-d9c1-11eb-8570-b3f7b520362f.png)

![image](https://user-images.githubusercontent.com/3397663/123980243-abd96a00-d9c1-11eb-8a2a-5c7a447bf1cd.png)

And let the corresponding "Checks" handle the on / off.

Example, toggling this check on automatically toggles the ASN behavior analysis

![image](https://user-images.githubusercontent.com/3397663/123980409-cd3a5600-d9c1-11eb-9a11-1c33d7b6523e.png)

Same for all other checks. Recommended to use

```
+function script.onLoad(hook, hook_config)
+end
+
+-- #################################################################
+
+function script.onUnload(hook, hook_config)
+end
+
+-- #################################################################
+
+function script.onEnable(hook, hook_config)
+end
+
+-- #################################################################
+
+function script.onDisable(hook, hook_config)
+end
+
```

See for example what you have done to enable/disable the traffic map: scripts/pro_plugins/alerts/security/excessive_traffic/checks/interface/excessive_traffic.lua

**Comment by simonemainardi** [comment]
AS timeseries generation must be controlled by the already existing preference

![image](https://user-images.githubusercontent.com/3397663/124004616-7ab86400-d9d8-11eb-8ef1-51be8c8f9222.png)

So, behavior timeseries are written if the check is enabled and if the AS timeseries are enabled.

**Comment by MatteoBiscosi** [comment]
Implemented as requested. However due to the fact that those timeseries are not "lightweight" and considering that there are a lot of those (e.g. each l7 proto per interface should have this type of timeseries) I decided to just enabling them if the alert is enabled. If it is disabled then no behavior timeseries is "crafted" in this way we are not going to use the necessary resources for those who are not interested in these types of timeseries.

**Comment by simonemainardi** [comment]
Doing Redis accesses every time an nDPI instance is created is detrimental for performance. Same for other instances. These MUST be removed:
- https://github.com/ntop/ntopng/commit/17cd2efb00a7757345b6498f509f0c7cfd0f148e#diff-f13797533f698ba448d23ac85e413bcdf76e7038466f8c28ba49aac794059892R60
- https://github.com/ntop/ntopng/commit/17cd2efb00a7757345b6498f509f0c7cfd0f148e#diff-f13797533f698ba448d23ac85e413bcdf76e7038466f8c28ba49aac794059892R37
- https://github.com/ntop/ntopng/commit/17cd2efb00a7757345b6498f509f0c7cfd0f148e#diff-ecbc55158fa64fc3903e9d430ada4957a7def08a1f926db2463a612f7086191bR40

Those preferences must stay inside class `Prefs`, refreshed only when a change occur, and accessed using `Prefs` inline methods such as `prefs->get_xyz()`.

Preferences are already refreshed automatically when changed, see `ntop.reloadPreferences()` for the implementation.

As you are forcing the user to restart ntopng, I believe that reading preferences can be avoided at all at runtime.

----

Leave this as parameter: https://github.com/ntop/ntopng/commit/17cd2efb00a7757345b6498f509f0c7cfd0f148e#diff-f13797533f698ba448d23ac85e413bcdf76e7038466f8c28ba49aac794059892L27

----

> However due to the fact that those timeseries are not "lightweight" and considering that there are a lot of those (e.g. each l7 proto per interface should have this type of timeseries) I decided to just enabling them if the alert is enabled. If it is disabled then no behavior timeseries is "crafted" in this way we are not going to use the necessary resources for those who are not interested in these types of timeseries.

?
