### ISSUE TITLE
ERROR: Unknown user script: l7_behavior

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5588]
Modal is broken

![image](https://user-images.githubusercontent.com/3397663/123982514-63bb4700-d9c3-11eb-9c5d-b699dc2ebb79.png)

Toggle yields

```
30/Jun/2021 16:51:10 [get_check_config.lua:44] ERROR: Unknown user script: l7_behavior
```

**Comment by MatteoBiscosi** [comment]
This is fixed under the pro repo with the last updates
