### ISSUE TITLE
nDPIStats copy constructor inconsistent

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5589]
`nDPIStats::nDPIStats(const nDPIStats &stats)` creates an instances of AnalysisBehavior with an hardcoded parameter 0.5 and then calls updateBehavior on the instances.

This does not cause any copy to be created. 

If necessary, `AnalysisBehavior` copy constructor must be implemended and called from `nDPIStats::nDPIStats(const nDPIStats &stats)` -- see for example what has been done for `ThroughputStats`.

If not necessary, do not copy `AnalysisBehavior` at all and let it initialized to NULL.

**Comment by simonemainardi** [comment]
The commit doesn't fix. In the commit, you are assuming to know how the class instance is instantiated as you are using hardcoded parameters. This does not create a copy. Please, follow the description above.

**Comment by simonemainardi** [comment]
and by the way the compilation is broken

```
src/nDPIStats.cpp:281:55: error: no matching constructor for initialization of 'AnalysisBehavior'
        behavior_bytes_traffic[i] = new (std::nothrow)AnalysisBehavior(0.5 /* Alpha parameter */, 0.1 /* Beta parameter */, 0.05 /* Significance */, true /* Counter */);
                                                      ^                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/simone/ntopng/pro/AnalysisBehavior.h:38:3: note: candidate constructor not viable: requires at most 3 arguments, but 4 were provided
  AnalysisBehavior(double alpha = 0.9, double beta = 0.035, float significance = 0.05);
  ^
/home/simone/ntopng/pro/AnalysisBehavior.h:25:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 4 were provided
class AnalysisBehavior {
      ^
2 warnings and 1 error generated.
Makefile:151: recipe for target 'src/nDPIStat
```

**Comment by MatteoBiscosi** [comment]
I removed the copy constructor of the AnalysisBehavior because currently it is not possible to implement it, if you check better, the "hardcoded" parameters are not added into the copy constructor but into the updateStats and it is normal. For the second problem update the pro repository
