### ISSUE TITLE
UI frozen when asking for history/top

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#559]
hi,

I use ntopng Professional v.2.2.160512 and when I ask for graph about traffic with ipv4 top flow under, more often this last info are broken (no result found) and ntopng webUI is loading...
if I try to select an other option in menu, nothing cause it's still loading
I use mysql-server to save all data with purge after 7 days.

Do I need to switch to 2.3 ? if yes how to without breaking all ?

thanks

Nico
<img width="609" alt="ntop" src="https://cloud.githubusercontent.com/assets/17108017/15275392/b82bbaa8-1aca-11e6-8b5b-63cebcd51fd8.PNG">

**Comment by simonemainardi** [comment]
right, you have to update to the latest dev version. It contains fixes and automatic database reconnections.

**Comment by Niko78** [comment]
hi,
thanks for info
is there something special to switch from stable to dev build ? just change the apt ?
I use ubuntu 14.04

nico

**Comment by simonemainardi** [comment]
uninstall the `apt-ntop-stable.deb` package and then follow instructions at : http://packages.ntop.org/apt/
