### ISSUE TITLE
attempt to index a nil value (field 'score_behavior')

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5592]
30/Jun/2021 17:45:15 [AlertCheckLuaEngine.cpp:170] WARNING: Script failure[/home/simone/ntopng/scripts/callbacks/interface/interface.lua] [.../plugins0/callbacks/interface/interface/asn_behavior.lua:76: attempt to index a nil value (field 'score_behavior')]

**Comment by MatteoBiscosi** [comment]
Fixed, pro repo
