### ISSUE TITLE
convert CLI in conf file

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#560]
hi,
I use ntopng Professional v.2.2.160512 but to launch it I do it in CLI
=> ntopng -F "mysql;localhost;ntopng;flows;root;xxx" -i tcp://192.168.6.35:5556 -d /storage/tmp -w 3000 -v >> /dev/null &

I tried to convert this line inside ntopng.conf file but it doesn't work
if you have an idea how to do it ?

thanks

Nico

**Comment by simonemainardi** [comment]
post the `ntopng.conf` file you have created. Also note that if you start ntopng as a daemon you don't need redirection to dev null.

**Comment by Niko78** [comment]
ok, right now I don't use ntopng.conf cause I can't get the same result as cli command
ntopng.conf 
-w=3000
-W=0
-g=-1
-d=/storage/ntopng/storage/ntopng
-G=/var/tmp/ntopng.pid
-i=tcp://192.168.6.35:5556

nico

**Comment by simonemainardi** [comment]
what do you mean with "I can't get the same result as cli command" please be specific and explain what you can't get

**Comment by Niko78** [comment]
ok so I just upgraded to dev version and now something is broken
as I said, before I used my own script to start ntopng and nprobe 
ntopng -F "mysql;localhost;ntopng;flows;root;xxxx" -i tcp://192.168.6.35:5556 -d /storage/tmp -w 3000 -v >> /dev/null &
/usr/local/bin/nprobe --collector-port 7002 --zmq tcp://192.168.6.35:5556 >> /dev/null &

after upgrading, see my ntopng.conf
-w=3000
-W=0
-g=-1
-d=/storage/ntopng/storage/ntopng
-G=/var/run/ntopng.pid
-i=tcp://192.168.6.35:5556

and nprobe-eth0.conf
-n=udp://192.168.6.35:7002
-i=eth0
-s=128
-t=60
-d=60
-a=0
-e=1
-B=10
-w=128000
-z=0
-S=1:1
-E=0:0
-g=/var/run/nprobe-eth0.pid
--zmq=tcp://192.168.6.35:5556
--vlanid-as-iface-idx=none
-V=5
--dump-stats=/var/log/nprobe/eth0-0_flows_stats.txt

... when I try to start nprobe from nbox, it fails :-(

any idea how to adapt conf files with my own script ?
thanks

nico

**Comment by simonemainardi** [comment]
if you manage ntopng and nprobe using the nbox, then you don't need your "script". Just let the nbox do the work. 

So now please clear the configurations files shown that may be wrong (for example the `-d=/storage/ntopng/storage/ntopng` looks awkward to me) and restart the nbox. Then use the nbox to reconfigure both ntopng and nprobe and don't touch the configuration files by hand.

If then the nprobe still fails, look at the logs.

**Comment by Niko78** [comment]
well... now still broken and it doesn't recognize my licenses :-(

**Comment by simonemainardi** [comment]
dear @Niko78 please be proactive and provide information that can help us in understanding what is not not working. 

enclose screenshots, logs, debug messages, etc everything that can help us in guiding you through a proper configuration.

ntopng and nprobe always look for licenses in the default places /etc/nprobe/ and /etc/ntopng/ so if licenses are there, they will be found. If you say they are not found, then enclose the logs.

**Comment by Niko78** [comment]
well... see screenshots... I don't know what to do now
can I contact you in private ?

<img width="898" alt="lic1" src="https://cloud.githubusercontent.com/assets/17108017/15286783/3793bd88-1b5f-11e6-85b7-026ac6c02d1b.PNG">
<img width="531" alt="lic2" src="https://cloud.githubusercontent.com/assets/17108017/15286785/382bbb42-1b5f-11e6-9839-d070115364f5.PNG">
<img width="541" alt="lic3" src="https://cloud.githubusercontent.com/assets/17108017/15286784/38299998-1b5f-11e6-80b4-cacff4e87481.PNG">
<img width="582" alt="nprobe" src="https://cloud.githubusercontent.com/assets/17108017/15286796/3e21c4ec-1b5f-11e6-89f7-6e2b7dbb77f5.PNG">
<img width="542" alt="ntopng" src="https://cloud.githubusercontent.com/assets/17108017/15286786/382e3192-1b5f-11e6-9601-384b2a99227e.PNG">
<img width="761" alt="ui" src="https://cloud.githubusercontent.com/assets/17108017/15286788/39224606-1b5f-11e6-9af2-6a2ee2f1bbf3.PNG">

**Comment by simonemainardi** [comment]
- try to run ntopng from the command line and see if it recognizes the license
- when did you buy the licenses?
- check system time and date
- check license files permissions

**Comment by Niko78** [comment]
- from command line, same problem
- got them last week and all worked fine until I switch in dev build (I got them for free as I'm in a non profit department)
- date is ok (+ ntp updates)
- permissions 
  -rw-r--r-- 1 root root 51 mai   16 11:34 /etc/ntopng.license

I downgraded to stable and same issue with licenses (ntopng and nprobe) :-(

**Comment by Niko78** [comment]
in verifying license, it appears that systemID changed after upgrading to dev :-(
now : 68B5DD5E76046AD1
before : 68B5DD5E550461D1

any idea why ? and now what can I do ?

**Comment by simonemainardi** [comment]
contact me privately at mainardi at ntop dot org and I will give you instructions
