### ISSUE TITLE
Acknowledge instead of disable Alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5600]
The "bell" concept is nice but it hides a lot of information that is necessary for troubleshooting.

This is to request to implement
- instead of deleting alerts, just acknowledge them from screen
- When hiding alerts add the ability to put a string to be used as human-readeable comment that says why this alert has been hidden (e.g. it is now fixed). Add the date/time of acknowledge
- add the ability to show acknowledged alerts

The idea is that for security audit, alerts should not be deleted but put aside. When you put an alert aside, it means that you have acknowledged meaning that you are aware that such issues are no longer important, but deleting them is not a good idea as they disappear forever.

In essence 
- open alerts (what we have today in ntopng) are "unacknowledged"
- disabled alerts (with the bell) become "acknowledged". They are hidden from the default window but they can be displayed if necessary
- a network operator will focus only on unacknowledged alerts, as those that have been acknowledged are issues he has already handled.

**Comment by simonemainardi** [comment]
- Implemented the ability to acknowledge past alerts, both individually and as groups.
- Acknowledged alerts are kept separate from past alerts and can be seen using the filters toggle

![image](https://user-images.githubusercontent.com/3397663/124628438-c0fe3f00-de80-11eb-832b-547a23ade667.png)

- An optional comment can be added when acknowledging alerts. The comment is then shown when visualizing acknowledged alerts

![image](https://user-images.githubusercontent.com/3397663/124628679-015dbd00-de81-11eb-839c-8204537240a1.png)
