### ISSUE TITLE
Improve Invalid Host Behaviour (Score Anomaly)

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5603]
When a "Invalid Host Behaviour" alert is reported for a score (e.g. invalid client score). it is very cumbersome from the current GUI to find all flows that contributed to this problem as jumping from a alert tab to another the selection is lost.

This is to require the implementation of a HREF or similar mechanism to allow alerted flows for a give host to be shown in a click starting from a host alert (and not just for "Invalid Host Behaviour" alerts).

**Comment by simonemainardi** [comment]
An extra "Flows" action has been added to jump straight to the flow alerts involving the selected host, withing the timeframe of the alert.

![image](https://user-images.githubusercontent.com/3397663/124113897-3d051b00-da6c-11eb-9fd2-82eccc6225ac.png)
