### ISSUE TITLE
Hide/Discard Alerts based on SNI or hostname

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5604]
In case of alerts for a SNI or hostname for cloud hosts, the name of the host is not meaningful as it can change all the time. So instead of disabling alerts host sdasdas.amazon.com, then hgdsjhadgajs.amazon.com..... it would be nice do hide/skip alerts for alert type/*.amazon.com. Example ignore all alerts "Expired certificate" for *.amazon.com hosts

**Comment by simonemainardi** [comment]
Likely, we can handle this using risk exclusions as discussed in https://github.com/ntop/ntopng/issues/5799#issuecomment-905358715

**Comment by lucaderi** [comment]
Implemented with https://github.com/ntop/nDPI/commit/6679453d8601b7116534558097aaffc2bda14963
