### ISSUE TITLE
Implement recent filter history

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5605]
Similar to Wireshark
<img width="775" alt="Screenshot 2021-07-01 at 10 07 50" src="https://user-images.githubusercontent.com/4493366/124089530-42566b80-da54-11eb-84b9-f6593e39c524.png">

it is requested to implement a recent filter history in alert and historical flows to quickly recall the latest filters selected

**Comment by MatteoBiscosi** [comment]
Implemented by using the snapshot features. Please reopen the ticket if it is not enough
