### ISSUE TITLE
Add Alert Anchor in Flow Window

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5606]
When a flow has triggered an alert, the flow information window displays the alert type. Unfortunately if you want to find this alert in the alert window, it is necessary to do several clicks, remember the host names...

This ticket is to require you to add a HREF anchor (see picture) in the flow window, that send the network operator straight to the alert window, with the correct tab, time, engaged/not engaged, and filter selection, to see quickly the alert that was generated for such flow.

<img width="999" alt="image" src="https://user-images.githubusercontent.com/4493366/124092296-feb13100-da56-11eb-8ae0-a65762e62ac0.png">

**Comment by simonemainardi** [comment]
![image](https://user-images.githubusercontent.com/3397663/124139009-7c8d3080-da87-11eb-966b-e90a573cbeeb.png)

**Comment by simonemainardi** [comment]
Also added a cog to jump to the check configuration

![image](https://user-images.githubusercontent.com/3397663/124150504-ead6f080-da91-11eb-8eee-a39cd1fd90b1.png)
