### ISSUE TITLE
[Regression] Alert VLAN filtering bug

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5607]
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/4493366/124092119-cf022900-da56-11eb-95f7-ff0543b632f5.png">

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/4493366/124091933-9febb780-da56-11eb-854d-b0ce87473ee2.png">

When filtering hosts with a VLAN tag, filtering won't work.

**Comment by cardigliano** [comment]
Fixed in 6827241e13c7da497aabe654fdfbdf6e60a32b3c

**Comment by lucaderi** [comment]
Still bugged

**Comment by cardigliano** [comment]
Fixed for flow alerts in 49a180355533fd87befc815dbdb475332de90814

**Comment by lucaderi** [comment]
Verified as fixed
