### ISSUE TITLE
Check search is cumbersome

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5610]
When a user wants to set a check for a host, he needs to check under the Interface and Host tabs. For ASs under the Interface.... This is all complicated.

It is requested to design way to show the user the list of possible checks for entity type. Example: show me all the checks for MAC addresses, for hosts, for ASs.... regardless of their location in the tag and regardless of their status (enabled or disabled).

**Comment by lucaderi** [comment]
The goal of this ticket is to make sure people can find what they are looking, see what options are available, regardless of the place where checks are implemented (as today).

**Comment by simonemainardi** [comment]
Implemented the 'All' tab with the ability to toggle and configure checks for any family

![image](https://user-images.githubusercontent.com/3397663/134189661-ece8d4d4-e1b4-476e-ab41-901ee05ccf6e.png)

**Comment by lucaderi** [comment]
Verified as fixed but the family is missing. Please add a column for reporting this information

**Comment by simonemainardi** [comment]
Family added. Choice has been to add the family as first column without title

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/3397663/134344043-7cef7bcc-ff02-48f1-8d29-76e89c985bb6.png">

This to be consistent with the alerts page.

**Comment by lucaderi** [comment]
Column is gone in the current code version

**Comment by lucaderi** [comment]
Verified as fixed
