### ISSUE TITLE
Rework the "Restart required" modal

### ISSUE THREAD

**Issue by MatteoBiscosi** [ntop/ntopng#5614]
The restart required modal is a usefull modal, however, whenever is used it modify the current page and due to this behavior it is not possible to use it in context like the one shown with the screenshot
![Screenshot from 2021-07-01 14-06-52](https://user-images.githubusercontent.com/49585191/124121825-a76e8900-da75-11eb-9add-d41a0207ff6b.png)

**Comment by MatteoBiscosi** [comment]
Born from #5587

**Comment by simonemainardi** [comment]
This is normal, you cannot open a modal on top of another modal. However, if necessary, you can edit the `action` button of the current modal to trigger a 'restart'.
