### ISSUE TITLE
SMTP failed 

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#5615]
I am using SMTP  as endpoint,but it failed,details as follow,

ntopng Enterprise L v.4.3.210701

sending SSL error

![image](https://user-images.githubusercontent.com/44804599/124242461-5a5ee580-db4f-11eb-9750-12635e02c49d.png)

receipients drops a lot

![image](https://user-images.githubusercontent.com/44804599/124242634-8712fd00-db4f-11eb-9caa-7cf17e792db4.png)

log warning
![image](https://user-images.githubusercontent.com/44804599/124243137-115b6100-db50-11eb-9791-a4987d496617.png)

**Comment by MaoPann** [comment]
I restart to test receipient, Something went wrong ,tay later

![image](https://user-images.githubusercontent.com/44804599/124244159-39978f80-db51-11eb-8752-f52860dbac81.png)

**Comment by MaoPann** [comment]
this is log detail
![image](https://user-images.githubusercontent.com/44804599/124248441-6fd70e00-db55-11eb-87c6-d530a12979eb.png)

**Comment by MaoPann** [comment]
hello , any one help me.

**Comment by cardigliano** [comment]
@MaoPann does the server support TLS? I do not see a 250-STARTTLS message coming from the server in your logs..

**Comment by MaoPann** [comment]
don‘t surport

**Comment by cardigliano** [comment]
Can I see your Endpoint configuration?

**Comment by MaoPann** [comment]
![image](https://user-images.githubusercontent.com/44804599/124740716-9fb75480-df4d-11eb-9da5-0c185a838c63.png)
![image](https://user-images.githubusercontent.com/44804599/124740771-af369d80-df4d-11eb-8124-2b84dfeeaf77.png)
![image](https://user-images.githubusercontent.com/44804599/124740836-ba89c900-df4d-11eb-83fc-fe4e9b3bdcb3.png)

**Comment by cardigliano** [comment]
I was asking for the "Endpoint" configuration, not the "Recipient"

**Comment by cardigliano** [comment]
@MaoPann please update to latest package (4.3.210707-14888), and try setting smtp://<host> as SMTP Server (note the smtp:// scheme/prefix). Let me know if it works or provide the verbose log again. Thank you.

**Comment by MaoPann** [comment]
i update the latest package ,it works
![image](https://user-images.githubusercontent.com/44804599/124877784-fed4a200-dffd-11eb-841a-1a87f788f702.png)

**Comment by MaoPann** [comment]
but the Ubuntu There doesn't seem to be a new version available yet

**Comment by cardigliano** [comment]
> i update the latest package ,it works

Great! Let's close this then.

Packages for Ubuntu seems to be updated, what Ubuntu version are you running?
