### ISSUE TITLE
Unprivileged user can manipulate alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5616]
An unprivileged user is not supposed to manipulate alerts. So for instance the yellow bell should not be displayed or any other action should be forbidden
<img width="1250" alt="Screenshot 2021-07-02 at 11 04 02" src="https://user-images.githubusercontent.com/4493366/124250555-47372000-db25-11eb-9057-272992d64cc2.png">

**Comment by lucaderi** [comment]
This fix introduces a new problem as an unprivileged user cannot see alerts at all.
![Screen Shot 2021-07-05 at 17 17 27](https://user-images.githubusercontent.com/4493366/124492533-e32a8b00-ddb4-11eb-8c49-58178b738641.png)

**Comment by cardigliano** [comment]
The Alerts menu has not been changed in this fix, in fact it is available in my system. Did you configure allowed-networks for the user perhaps?

**Comment by simonemainardi** [comment]
This happens because the unprivileged user has allowed networks. Alerts are now visible to:

- Administrators
- Unprivileged users without allowed networks

Remote unprivileged users and users with allowed networks are not entitled to see alerts.
