### ISSUE TITLE
Add a modal to open external links

### ISSUE THREAD

**Issue by MatteoBiscosi** [ntop/ntopng#5618]
It is requested to create a new modal that's going to be used when a user clicks on an external link.
For example if a user clicks on a href like the one shown below it would be great to open a modal to check if the user wants to open the url or just missclicked.
![Screenshot from 2021-07-02 10-37-43](https://user-images.githubusercontent.com/49585191/124251254-fffd5f00-db25-11eb-8c0e-1fb4c802fad3.png)

**Comment by MatteoBiscosi** [comment]
Implemented as requested

**Comment by simonemainardi** [comment]
If you have decided to open a modal dialog before following an external link, then this behavior must be applied across all external links opened by ntopng, not just one. So please either open if for every modal, or don't open it at all.

```
simone@devel:~/ntopng$ egrep -r "external-link" scripts/ | wc -l
80
```

**Comment by simonemainardi** [comment]
any news?

**Comment by MatteoBiscosi** [comment]
Verified as fixed
