### ISSUE TITLE
tcp port 3000 is not listening after the license expired

### ISSUE THREAD

**Issue by scdit46** [ntop/ntopng#5620]
**After that the license expired happens this problem:**

Jul 02 12:36:38 ubuntu ntopng[5989]: [NtopPro.cpp:548] WARNING: [LICENSE] Invalid license [License expired]
Jul 02 12:36:38 ubuntu ntopng[5989]: 02/Jul/2021 12:36:38 [NtopPro.cpp:548] WARNING: [LICENSE] Invalid license [License expired]
Jul 02 12:36:38 ubuntu ntopng[5989]: [NtopPro.cpp:554] WARNING: [LICENSE] Your license is expired on Wed Jun 16 13:22:08 2021
Jul 02 12:36:38 ubuntu ntopng[5989]: 02/Jul/2021 12:36:38 [NtopPro.cpp:554] WARNING: [LICENSE] Your license is expired on Wed Jun 16 13:22:08 2021
Jul 02 12:36:38 ubuntu ntopng[5989]: 02/Jul/2021 12:36:38 [NtopPro.cpp:565] WARNING: [LICENSE] ntopng will now run in Enterprise L edition for 10 minutes
Jul 02 12:36:38 ubuntu ntopng[5989]: 02/Jul/2021 12:36:38 [NtopPro.cpp:567] WARNING: [LICENSE] before returning to community mode
Jul 02 12:36:38 ubuntu ntopng[5989]: [NtopPro.cpp:565] WARNING: [LICENSE] ntopng will now run in Enterprise L edition for 10 minutes
Jul 02 12:36:38 ubuntu ntopng[5989]: [NtopPro.cpp:567] WARNING: [LICENSE] before returning to community mode
Jul 02 12:36:38 ubuntu ntopng[5989]: [NtopPro.cpp:569] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
Jul 02 12:36:38 ubuntu ntopng[5989]: 02/Jul/2021 12:36:38 [NtopPro.cpp:569] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
Jul 02 12:36:38 ubuntu ntopng[5989]: [NtopPro.cpp:571] WARNING: [LICENSE] or run ntopng in community mode starting
Jul 02 12:36:38 ubuntu ntopng[5989]: 02/Jul/2021 12:36:38 [NtopPro.cpp:571] WARNING: [LICENSE] or run ntopng in community mode starting
Jul 02 12:36:38 ubuntu ntopng[5989]: [NtopPro.cpp:572] WARNING: [LICENSE] ntopng --community
Jul 02 12:36:38 ubuntu ntopng[5989]: 02/Jul/2021 12:36:38 [NtopPro.cpp:572] WARNING: [LICENSE] ntopng --community
Jul 02 12:36:38 ubuntu ntopng[5989]: 02/Jul/2021 12:36:38 [PF_RINGInterface.cpp:69] Reading packets from PF_RING v.7.9.0 interface ens38...
Jul 02 12:36:38 ubuntu ntopng[5989]: 02/Jul/2021 12:36:38 [Ntop.cpp:2598] Registered interface ens38 [id: 3]
Jul 02 12:36:38 ubuntu ntopng[5989]: 02/Jul/2021 12:36:38 [Ntop.cpp:2598] Registered interface tcp://127.0.0.1:5556c [id: 7]
Jul 02 12:36:38 ubuntu ntopng[5989]: 02/Jul/2021 12:36:38 [main.cpp:331] PID stored in file /var/run/ntopng.pid
Jul 02 12:36:38 ubuntu ntopng[5989]: 02/Jul/2021 12:36:38 [Geolocation.cpp:149] Loaded database dbip-asn-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip-a>
Jul 02 12:36:38 ubuntu ntopng[5989]: 02/Jul/2021 12:36:38 [Geolocation.cpp:149] Loaded database dbip-city-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip->
Jul 02 12:36:38 ubuntu ntopng[5989]: 02/Jul/2021 12:36:38 [Geolocation.cpp:97] Using geolocation provided by DB-IP (https://db-ip.com)
Jul 02 12:36:38 ubuntu ntopng[5989]: 02/Jul/2021 12:36:38 [HTTPserver.cpp:1692] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
Jul 02 12:36:38 ubuntu ntopng[5989]: 02/Jul/2021 12:36:38 [HTTPserver.cpp:1695] HTTP server listening on 3000

**But the tcp port is not listening**

**Comment by simonemainardi** [comment]
Logs seem to be OK. How can you say 

> But the tcp port is not listening

?

**Comment by scdit46** [comment]
root@ubuntu:~#  **systemctl status ntopng**
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
     Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Fri 2021-07-02 17:57:28 CEST; 39s ago
    Process: 62803 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (>
    Process: 62817 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
    Process: 62819 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (code=exited, status=0/SUCC>
    Process: 62821 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /run/ntopng.conf (c>
    Process: 62823 ExecStart=/usr/bin/ntopng /run/ntopng.conf (code=killed, signal=TERM)
    Process: 62897 ExecStopPost=/bin/rm -rf /run/ntopng.conf /run/ntopng.conf.raw /run/ntopng.pid (code=exited, status=0/SUCCESS)
   Main PID: 62823 (code=killed, signal=TERM)

Jul 02 17:57:28 ubuntu ntopng[62823]: 02/Jul/2021 17:57:28 [PF_RINGInterface.cpp:69] Reading packets from PF_RING v.7.9.0 interface ens38...
Jul 02 17:57:28 ubuntu ntopng[62823]: 02/Jul/2021 17:57:28 [Ntop.cpp:2598] Registered interface ens38 [id: 3]
Jul 02 17:57:28 ubuntu ntopng[62823]: 02/Jul/2021 17:57:28 [Ntop.cpp:2598] Registered interface tcp://127.0.0.1:5556c [id: 7]
Jul 02 17:57:28 ubuntu ntopng[62823]: 02/Jul/2021 17:57:28 [main.cpp:331] PID stored in file /var/run/ntopng.pid
Jul 02 17:57:28 ubuntu ntopng[62823]: 02/Jul/2021 17:57:28 [Geolocation.cpp:149] Loaded database dbip-asn-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip->
Jul 02 17:57:28 ubuntu ntopng[62823]: 02/Jul/2021 17:57:28 [Geolocation.cpp:149] Loaded database dbip-city-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip>
Jul 02 17:57:28 ubuntu ntopng[62823]: 02/Jul/2021 17:57:28 [Geolocation.cpp:97] Using geolocation provided by DB-IP (https://db-ip.com)
Jul 02 17:57:28 ubuntu ntopng[62823]: 02/Jul/2021 17:57:28 [HTTPserver.cpp:1692] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
Jul 02 17:57:28 ubuntu ntopng[62823]: 02/Jul/2021 17:57:28 [HTTPserver.cpp:1695] HTTP server listening on 3000
Jul 02 17:57:28 ubuntu systemd[1]: ntopng.service: Succeeded.

**also netstat -nltp is not show the tcp port 3000  listening**

**Comment by simonemainardi** [comment]
> Active: inactive (dead)

it 's not running

**Comment by scdit46** [comment]
I know!!!

I know if I set the trial license the ntopng starts sucesfull
But with the expired license ntopng does not start?
I think that ntopng should starts with community license
what is happening?

**Comment by scdit46** [comment]
also the log displays:

Jul 02 17:57:28 ubuntu ntopng[62823]: 02/Jul/2021 17:57:28 [HTTPserver.cpp:1695] **HTTP server listening on 3000**
Jul 02 17:57:28 ubuntu systemd[1]: **ntopng.service: Succeeded.**

when ntopng does not start
why?

**Comment by simonemainardi** [comment]
report os version used, ntopng version, ntopng configuration file, and the full log since the very beginning

**Comment by scdit46** [comment]
root@ubuntu:~# ntopng --version
Version:        4.3.210702 [Enterprise/Professional build]
GIT rev:        dev:6a3d7f0af469ef8cd379752e994c03b20a9f0d0d:20210702
Pro rev:        r3951
Built on:       Ubuntu 20.04.2 LTS
System Id:      3BD8966F760B6B24
Platform:       x86_64
Edition:        Enterprise L (Bundle)
License Type:   Time-Limited [License expired]
Validity:       Until Sat Jul  3 11:11:02 2021
License:        s3q8tjO7/3lLdpG/AnbNpWehASDWS0LuDb3sWVhBhBheuEMm0Yk/kIpSFu9t7A3SkuNrs
                bNMXp+jzKt08J40gYuzTIzspC4Yb12zurxowZYTdo8IgflXTmMRbUK+xNyJ1phQ1CSo9o
                AlHROElcqRyd4skPsqk33U/BDgLyu7o6alk+INRATs8HT6SuN/cIHl+zIyWcMu4/3Xpbe
                ZNmh85NDtz9/SjIY7rq4otAdxtMJrX81XsKcOKpjHFjRIoVLwPC2gsl792Xs2fyyi/4xc
                3z60KuW4EOpA6e1cl3JkgiUVQNGO5cJVea+v5m71c9MK9vT7Kc54lXIe4VP8kOjwSg==
License Hash:   F6FF69128B609FFAC73C515769EDDAC91623842528F3E7247F

**Comment by scdit46** [comment]
[ntopng.log](https://github.com/ntop/ntopng/files/6758127/ntopng.log)

The full log

**Comment by scdit46** [comment]
the conf files
[integracion-nprobe.conf.log](https://github.com/ntop/ntopng/files/6758141/integracion-nprobe.conf.log)
[ntopng.conf.log](https://github.com/ntop/ntopng/files/6758143/ntopng.conf.log)

**Comment by scdit46** [comment]
what is the problem?

**Comment by simonemainardi** [comment]
remove expired license file /etc/ntopng.license and report

**Comment by scdit46** [comment]
I remove **/etc/ntopng.license**  but ntop does not start

the log is:

Jul 05 12:00:42 ubuntu systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
Jul 05 12:00:42 ubuntu systemd[1]: Started ntopng high-speed web-based traffic monitoring and analysis tool.
Jul 05 12:00:42 ubuntu ntopng[7162]: 05/Jul/2021 12:00:42 [Ntop.cpp:2490] Setting local networks to 127.0.0.0/8,fe80::/10
Jul 05 12:00:42 ubuntu ntopng[7162]: 05/Jul/2021 12:00:42 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
Jul 05 12:00:42 ubuntu ntopng[7162]: 05/Jul/2021 12:00:42 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
Jul 05 12:00:42 ubuntu ntopng[7162]: 05/Jul/2021 12:00:42 [NtopPro.cpp:330] [LICENSE] **No license file found** /etc/ntopng.license: reading license from redis
Jul 05 12:00:42 ubuntu ntopng[7162]: 05/Jul/2021 12:00:42 [NtopPro.cpp:476] [LICENSE] KrEnYyh5ewjG34UsutGSRdZXziXEMGFppz7+39+3d1voou7DJVCq4w5UiiU9DduSrHKF8Q>
Jul 05 12:00:42 ubuntu ntopng[7162]: [NtopPro.cpp:548] WARNING: [LICENSE] **Invalid license [License expired]**
Jul 05 12:00:42 ubuntu ntopng[7162]: 05/Jul/2021 12:00:42 [NtopPro.cpp:548] WARNING: [LICENSE] Invalid license [License expired]
Jul 05 12:00:42 ubuntu ntopng[7162]: [NtopPro.cpp:554] WARNING: [LICENSE] Your license is expired on Mon Jun  7 11:01:43 2021
Jul 05 12:00:42 ubuntu ntopng[7162]: 05/Jul/2021 12:00:42 [NtopPro.cpp:554] WARNING: [LICENSE] Your license is expired on Mon Jun  7 11:01:43 2021
Jul 05 12:00:42 ubuntu ntopng[7162]: 05/Jul/2021 12:00:42 [NtopPro.cpp:565] WARNING: [LICENSE] ntopng will now run in Enterprise L edition for 10 minutes
Jul 05 12:00:42 ubuntu ntopng[7162]: [NtopPro.cpp:565] WARNING: [LICENSE] ntopng will now run in Enterprise L edition for 10 minutes
Jul 05 12:00:42 ubuntu ntopng[7162]: 05/Jul/2021 12:00:42 [NtopPro.cpp:567] WARNING: [LICENSE] before returning to community mode
Jul 05 12:00:42 ubuntu ntopng[7162]: 05/Jul/2021 12:00:42 [NtopPro.cpp:569] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
Jul 05 12:00:42 ubuntu ntopng[7162]: [NtopPro.cpp:567] WARNING: [LICENSE] before returning to community mode
Jul 05 12:00:42 ubuntu ntopng[7162]: [NtopPro.cpp:569] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
Jul 05 12:00:42 ubuntu ntopng[7162]: [NtopPro.cpp:571] WARNING: [LICENSE] or run ntopng in community mode starting
Jul 05 12:00:42 ubuntu ntopng[7162]: 05/Jul/2021 12:00:42 [NtopPro.cpp:571] WARNING: [LICENSE] or run ntopng in community mode starting
Jul 05 12:00:42 ubuntu ntopng[7162]: [NtopPro.cpp:572] WARNING: [LICENSE] ntopng --community
Jul 05 12:00:42 ubuntu ntopng[7162]: 05/Jul/2021 12:00:42 [NtopPro.cpp:572] WARNING: [LICENSE] ntopng --community
Jul 05 12:00:42 ubuntu ntopng[7162]: 05/Jul/2021 12:00:42 [NetworkInterface.cpp:2948] Cleanup interface ens38
Jul 05 12:00:42 ubuntu ntopng[7162]: 05/Jul/2021 12:00:42 [main.cpp:234] Unable to open interface ens38 [97]: PF_RING not loaded. Falling back to pcap.
Jul 05 12:00:43 ubuntu ntopng[7162]: 05/Jul/2021 12:00:43 [PcapInterface.cpp:93] Reading packets from ens38 [id: 3]
Jul 05 12:00:43 ubuntu ntopng[7162]: 05/Jul/2021 12:00:43 [Ntop.cpp:2598] Registered interface ens38 [id: 3]
Jul 05 12:00:43 ubuntu ntopng[7162]: 05/Jul/2021 12:00:43 [Ntop.cpp:2598] Registered interface tcp://127.0.0.1:5556c [id: 7]
Jul 05 12:00:43 ubuntu ntopng[7162]: 05/Jul/2021 12:00:43 [main.cpp:331] PID stored in file /var/run/ntopng.pid
Jul 05 12:00:43 ubuntu ntopng[7162]: 05/Jul/2021 12:00:43 [Geolocation.cpp:149] Loaded database dbip-asn-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip-a>
Jul 05 12:00:43 ubuntu ntopng[7162]: 05/Jul/2021 12:00:43 [Geolocation.cpp:149] Loaded database dbip-city-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip->
Jul 05 12:00:43 ubuntu ntopng[7162]: 05/Jul/2021 12:00:43 [Geolocation.cpp:97] Using geolocation provided by DB-IP (https://db-ip.com)
Jul 05 12:00:43 ubuntu ntopng[7162]: 05/Jul/2021 12:00:43 [HTTPserver.cpp:1692] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
Jul 05 12:00:43 ubuntu ntopng[7162]: 05/Jul/2021 12:00:43 [HTTPserver.cpp:1695] HTTP server listening on 3000
Jul 05 12:00:43 ubuntu systemd[1]: ntopng.service: Succeeded.

**Comment by simonemainardi** [comment]
also remove the key added from the ntopng web UI under License

**Comment by scdit46** [comment]
The web UI is not starts.
The tcp port 3000 is not listening
The process ntopng is not started.

**Comment by simonemainardi** [comment]
run

```
redis-cli del ntopng.license
```

then restart

**Comment by scdit46** [comment]
now It´s works!!!!!

What it was happened?

**Comment by simonemainardi** [comment]
trial licenses expired cause ntopng to exit
