### ISSUE TITLE
Failed to download the config when using the Google Chrome but Firefox would be no problem.

### ISSUE THREAD

**Issue by Yoshihiro-jp** [ntop/ntopng#5621]
Hi,

I noticed this problem when I tested the latest ntopng version.

[ntopng version]
ntopng Enterprise L v.4.2.210629 

In the ntopng menu if I try to export the config file I would be failed with Google Chrome but if I used the Firefox it could be succeeded.

Kindly refer to the attached file.

The difference is the file name to download.
The Google chrome is "all_config.json".
The Firefox is "configuration.json".

regards,
Yoshihiro

![firefox is okay](https://user-images.githubusercontent.com/58843707/124425650-d18cb780-dda3-11eb-8e52-b8ba02778db5.PNG)
![Chrome network error](https://user-images.githubusercontent.com/58843707/124425659-d5203e80-dda3-11eb-8c7c-9acc348c8948.PNG)

**Comment by simonemainardi** [comment]
This is fixed in the latest dev version of ntopng. Will be pushed in the stable within a few days in the next stable release.
