### ISSUE TITLE
Unable to serve requests at this time, possibly starting up or shutting down

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#5622]
some times i can't open the webGUI
![image](https://user-images.githubusercontent.com/44804599/124433825-be7ae700-dda5-11eb-9744-078a8566988d.png)

**Comment by simonemainardi** [comment]
this happens during "start up or shut down" of ntopng. It's just a transient of at most a bunch of seconds when the webserver comes up.

**Comment by MaoPann** [comment]
@simonemainardi 
This may also happen when I switch pages

**Comment by simonemainardi** [comment]
Check the uptime. Is the process crashing/restarting?
