### ISSUE TITLE
Some flow risks are ignored

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5627]
Running nDPI with the enclosed pcap we obtain
	1	TCP 192.168.1.178:58233 <-> 31.11.32.73:80 [proto: 7/HTTP][cat: Web/5][203 pkts/13525 bytes <-> 297 pkts/444709 bytes][Goodput ratio: 1/96][0.22 sec][Host: www.giuseppeservidio.net][bytes ratio: -0.941 (Download)][IAT c2s/s2c min/avg/max/stddev: 0/0 1/0 25/25 3/2][Pkt Len c2s/s2c min/avg/max/stddev: 66/74 67/1497 181/1506 8/106][URL: www.giuseppeservidio.net/03download/450sp1dongle.exe][StatusCode: 200][User-Agent: curl/7.54.0][Risk: ** Binary application transfer **][Risk Score: 250][PLAIN TEXT (GET /03)][Plen Bins: 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,0,0]

[exe.pcap.gz](https://github.com/ntop/ntopng/files/6765273/exe.pcap.gz)

whereas
- in ntopng no problem is reported (see #5596)
- no alert is generated
![Screen Shot 2021-07-05 at 17 38 49](https://user-images.githubusercontent.com/4493366/124495061-ea9f6380-ddb7-11eb-9d9e-9d194110a972.png)

**Comment by simonemainardi** [comment]
Alert is generated using the latest build. Tested both on Linux and OS X.


![image](https://user-images.githubusercontent.com/3397663/124768499-0120f880-df39-11eb-8389-813d809b605c.png)


Look at the checks configuration page. Is the "Suspicious File Transfer" enabled? Also look under check exclusions, you may have excluded that check.
