### ISSUE TITLE
nIndex warning

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5628]
05/Jul/2021 17:38:22 [LuaEngine.cpp:1204] WARNING: Script failure [/ntopng/scripts/lua/pro/get_nindex_flows.lua][.../scripts/lua/pro/get_nindex_flows.lua:28: attempt to index a boolean value (local 'nindex_flows')]

**Comment by simonemainardi** [comment]
Fix is invalid. It does not solve the problem, it just hides it. Rather than understanding why `nindex_flows` is a boolean (this is the fix), you have hidden the bug in an empty response.

![image](https://user-images.githubusercontent.com/3397663/124634181-52bc7b00-de86-11eb-841c-2be60e06b6c5.png)

**Comment by simonemainardi** [comment]
Verified fixed in the pro part.
