### ISSUE TITLE
Flows anomalies do not report VLANId

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5629]
![image](https://user-images.githubusercontent.com/4493366/124496215-6cdc5780-ddb9-11eb-847f-2d428ebe8c74.png)

![image](https://user-images.githubusercontent.com/4493366/124496265-7e256400-ddb9-11eb-9ab2-191d69e2204b.png)

**Comment by lucaderi** [comment]
![image](https://user-images.githubusercontent.com/4493366/124603389-2bf04b80-de6a-11eb-8520-c156d92418c3.png)
Better but still bugged (missing symbolic VLAN mapping)

**Comment by MatteoBiscosi** [comment]
Fixed both into pro and community repo
