### ISSUE TITLE
historical data in nightly builds

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#563]
hi,
Just upgraded to nightly builds
I read that http://www.ntop.org/ntopng/exploring-historical-data-using-ntopng-part-2/ to explore datas but I can't find it in my UI, some titles in the menu are not there

<img width="639" alt="top" src="https://cloud.githubusercontent.com/assets/17108017/15294759/d30050a0-1b8d-11e6-89c1-81d7ce695351.PNG">

**Comment by simonemainardi** [comment]
post ntopng configuration or startup string

**Comment by Niko78** [comment]
still the same ;-)
=> ntopng "mysql;localhost;ntopng;flows;root;azer" -i tcp://192.168.6.35:5556 -d /storage/tmp -w 3000 -v

**Comment by simonemainardi** [comment]
Seriously? The string is just invalid. You would have figured it out on your own if you just had read the ntopng output.

You took the -F off but left the MySQL configuration parameters. 

Seriously, read the manual and go through the examples before opening another issue. You have reported three questions today that were just invalid https://github.com/ntop/ntopng/blob/dev/doc/UserGuide.pdf
