### ISSUE TITLE
Filter items limited to 5

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5630]
![Screen Shot 2021-07-05 at 17 52 11](https://user-images.githubusercontent.com/4493366/124496482-c2186900-ddb9-11eb-8f21-c69763576592.png)

The limit of 5 items per filter type (e.g. Alert Type in this case) is not enough to enable any reasonable analysis. Remove the limitation or raise it to 20+

**Comment by simonemainardi** [comment]
Likely this was due to a failing ajax request. Unable to reproduce. Can you please check again and, if still occurring, explain how to trigger this behavior.

**Comment by cardigliano** [comment]
It is likely this was due to a failure in the ajax request due to 471e56a9efc42459c2bc3d966f7eae8385ab66c0

**Comment by lucaderi** [comment]
Verified as fixed
