### ISSUE TITLE
Connection TLS does not display the icon forbidden by fingerprintng JA3 blacklist.

### ISSUE THREAD

**Issue by scdit46** [ntop/ntopng#5634]
Before when a JA3 is in the blacklist https://sslbl.abuse.ch/ja3-fingerprints/ displays from ntopng web UI (host->TLS) a **forbidden icon**  (see picture)
<img width="306" alt="ntop" src="https://user-images.githubusercontent.com/63736962/124558064-7fe33c00-de3a-11eb-8e92-7a4a13cf758a.png">

Now the forbidden icon is not displayed from the ntopng web UI when a connecion TLS is in https://sslbl.abuse.ch/ja3-fingerprints/

What is happening?

**Comment by scdit46** [comment]
When I restart ntopng service the fingerprint JA3 is reset (connections TLS disappears)
Is there any way to avoid this?

**Comment by simonemainardi** [comment]
Malicious signatures are shown both under the flows:

![image](https://user-images.githubusercontent.com/3397663/125438363-5069b354-f5b2-43d9-b979-dbaf59eff618.png)

![image](https://user-images.githubusercontent.com/3397663/125438392-43874317-9888-4fed-95a8-eb9d2d0b5c30.png)

and host page

![image](https://user-images.githubusercontent.com/3397663/125438439-a7a49df0-2a37-4489-914b-a5affa3d3189.png)

**Comment by simonemainardi** [comment]
we will consider serialization of JA3 in a future release
