### ISSUE TITLE
Implement max string lenght in alert page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5636]
If you can implement the max column size by adding a max string lenght, you can pass from this
![Screen Shot 2021-07-06 at 14 57 26](https://user-images.githubusercontent.com/4493366/124603704-7ffb3000-de6a-11eb-9271-444f866fc32e.png)
to this
![Screen Shot 2021-07-06 at 14 57 20](https://user-images.githubusercontent.com/4493366/124603705-8093c680-de6a-11eb-8b2a-5ebb7722156b.png)

**Comment by simonemainardi** [comment]
Implemented in the latest dev.

![image](https://user-images.githubusercontent.com/3397663/125053176-17e45e00-e0a5-11eb-9f4e-5d5693c134ef.png)


As discussed, although not ideal, shortening is done on the backend.
