### ISSUE TITLE
Find a better word for Subject

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5637]
![Screen Shot 2021-07-06 at 15 02 42](https://user-images.githubusercontent.com/4493366/124604444-3ced8c80-de6b-11eb-870c-d5a478b8a5d0.png)

The word subject is not a networking term and it needs to be replaced with something more meaningful. In this case, is this an interface, with Interface Name for instance.

Note that there is also a mapping problem as once is referenced as tcp:// and once as sFlow

**Comment by simonemainardi** [comment]
Alternatives:
- item
- object
- unit
- element
- entity

Note that also entity is used also by Home Assistant to manage devices (https://www.home-assistant.io/docs/configuration/customizing-devices/) so I am not sure this term is meaningless (https://github.com/ntop/ntopng/issues/5161).

Please, pick one and report.

**Comment by lucaderi** [comment]
Choose and close this ticket
