### ISSUE TITLE
View interfaces do not honour traffic directions

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5638]
![Screen Shot 2021-07-06 at 15 46 09](https://user-images.githubusercontent.com/4493366/124611065-627d9480-de71-11eb-9d19-d05f2b3bb0e1.png)
![Screen Shot 2021-07-06 at 15 45 55](https://user-images.githubusercontent.com/4493366/124611070-64475800-de71-11eb-9408-5c4f919bdc5f.png)

**Comment by simonemainardi** [comment]
Support added

![image](https://user-images.githubusercontent.com/3397663/125067572-bd52fe00-e0b4-11eb-843f-26b501378663.png)
