### ISSUE TITLE
Ntop setting PF_RING_ZC_DEVICE_CAPTURE_TX=0 - how to override?

### ISSUE THREAD

**Issue by hdbonnett** [ntop/ntopng#564]
I'm in the process of bringing up a new firewall for a client using IPTables and ntopng on Centos 7. The firewall is masquerading traffic, hosting ntopng and collecting network flows on the local interfaces. PF_RING dev (6.3.0) is installed on the firewall. From what I can see in /proc/net/pf_ring/info both of my interfaces are being found and I have enabled TX_Capture (so I can get both sides of the conversations flowing through the firewall).
When I cat the process files that are created when Ntop connects to the devices I see that the Capture Direction is being set back to RX Only in src/PF_RINGInterface.cpp:60 -  `pfring_set_direction(pfring_handle,` rx_only_direction);`

Is there a way to override this via the config file or command line? I am aware of the grave danger to my soul by doing so and accept all risk ;-) If not, I'll build my own version and put the changes back up for review.

**Comment by simonemainardi** [comment]
feature requested was already implemented in https://github.com/ntop/ntopng/commit/ae22da5136a84a8a2d0636409ee7bf89f23bed93 and reported in #265 

have a look at https://github.com/ntop/ntopng/blob/ae22da5136a84a8a2d0636409ee7bf89f23bed93/src/PF_RINGInterface.cpp#L64
