### ISSUE TITLE
Alerts are not triggered

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5640]
![Screen Shot 2021-07-06 at 15 52 50](https://user-images.githubusercontent.com/4493366/124612004-43333700-de72-11eb-8e29-c2f985f0c999.png)

When using this configuration 
-i=tcp://127.0.0.1:17900c
-i=tcp://127.0.0.1:17901c
-i=view:tcp://127.0.0.1:17900c,tcp://127.0.0.1:17901c

alerts are shown in the GUI (top menu) but not in the alert page

**Comment by simonemainardi** [comment]
Fixed as of https://github.com/ntop/ntopng/issues/5639
