### ISSUE TITLE
Elephant flows do not report URL (when present)

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5646]
![image](https://user-images.githubusercontent.com/4493366/124762961-be105680-df33-11eb-936a-6d0c7f0ca001.png)

Without a URL, troubleshooting the above problem is not possible

**Comment by simonemainardi** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/3397663/125062802-1455d480-e0af-11eb-899f-1c24b5b04953.png)
