### ISSUE TITLE
VLAN Tag is cut when shortening Host Names

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5647]
![image](https://user-images.githubusercontent.com/4493366/124765334-24967400-df36-11eb-9b7d-f88edc988847.png)

When a hostname is too long, its name is shortened and this is ok. The problem is that this should not be applied to the VLAN but only to the hostname. As of today, the VLAN tag is removed. Please shorten the host but not the VLAN tag.

**Comment by simonemainardi** [comment]
@MatteoBiscosi what about using the shortenString function straigh inside the hostVisualization? In this way, you can control the lenght of both names and VLANs.

**Comment by lucaderi** [comment]
![image](https://user-images.githubusercontent.com/4493366/124971197-3278f180-e029-11eb-8f23-918327b1d315.png)
Still bugged in alerts

**Comment by simonemainardi** [comment]
Fixed in the latest dev

![image](https://user-images.githubusercontent.com/3397663/125052544-604f4c00-e0a4-11eb-9d9a-87bce4a59491.png)
