### ISSUE TITLE
Protocol Filter not working as expected

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5656]
![Screen Shot 2021-07-09 at 20 15 42](https://user-images.githubusercontent.com/4493366/125120229-7a178000-e0f2-11eb-92a8-a50885fb2f90.png)

In the flow explorer, the protocol filtering is not working as expected: when clicking on it the drop-down menu is not selecting the correct entry

**Comment by cardigliano** [comment]
Fixed

**Comment by lucaderi** [comment]
Verified as fixed
