### ISSUE TITLE
Add Threshold to Client/Server Score Anomaly

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5657]
The score anomaly alert detects changes in behaviour but it does not enforce a high value. So if a host has a very high score value (e.g. above 1000) that is steady, no alert is produced.

This is to require the implementation of a max score threshold value (configurable) that an alert is triggered until the score is above the specified threshold.

**Comment by lucaderi** [comment]
No default value (1000) is set
![Screen Shot 2021-07-12 at 19 23 53](https://user-images.githubusercontent.com/4493366/125330214-bf33f000-e346-11eb-8a2f-32a07031a705.png)

**Comment by MatteoBiscosi** [comment]
The threshold empty is due to the fact that the alert was already enabled before the update. In fact if you click `Reset to Factory Value` below the score is going to be added correctly.

**Comment by lucaderi** [comment]
Verified as fixed
