### ISSUE TITLE
ntopng fresh install(as module) on pfsense | host_details.lua internal server error

### ISSUE THREAD

**Issue by develop-cloud** [ntop/ntopng#5658]
Hi,

I'm using a (trough pfsense) a 'fresh' install of ntopng that finalises successfully.

When using(inside the ntopng webinterface-dashboard) the links for a IP address(more details) or client(more details) I end up with this content with this url. The url is different than the original pointer of the link-url.

original: http://xxx.xxx.xxx.xxx:3000/lua/host_details.lua?host=xxx.xxx.xxx.xxx
ends-up: http://xxx.xxx.xxx.xxx:3000/lua/http_status_code.lua?message=internal_error&referer=xxx.xxx.xxx.xxx%3A3000%2Flua%2Fhost_details.lua%3Fhost%3Dxxx.xxx.xxx.xxx&error_message=...local%2Fshare%2Fntopng%2Fscrip(etc.etc.etc.etc.)

**With the following errors on the page:**
You're not supposed to be here!
Internal server error
__.local/share/ntopng/scripts/lua/modules/plugins_utils.lua:997: module 'active_monitoring.am_utils' not found:__no field package.preload['active_monitoring.am_utils']__no file '/var/db/ntopng/plugins0/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/var/db/ntopng/plugins0/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/var/db/ntopng/plugins0/status_definitions/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/flow_status_definitions/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/recipients/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/notifications/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/recipients/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/var/db/ntopng/plugins0/alert_definitions/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/alert_definitions/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/recipients/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/recipients/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/var/db/ntopng/plugins0/ts_schemas/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/timeseries/custom/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/timeseries/schemas/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/timeseries/drivers/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/var/db/ntopng/plugins0/http_lint/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/recipients/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/flow_dbms/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/timeseries/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/i18n/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/lua/5.3/active_monitoring/am_utils.lua'__no file '/usr/local/share/lua/5.3/active_monitoring/am_utils/init.lua'__no file '/usr/local/lib/lua/5.3/active_monitoring/am_utils.lua'__no file '/usr/local/lib/lua/5.3/active_monitoring/am_utils/init.lua'__no file './active_monitoring/am_utils.lua'__no file './active_monitoring/am_utils/init.lua'__no file '/usr/local/lib/lua/5.3/active_monitoring/am_utils.so'__no file '/usr/local/lib/lua/5.3/loadall.so'__no file './active_monitoring/am_utils.so'__no file '/usr/local/lib/lua/5.3/active_monitoring.so'__no file '/usr/local/lib/lua/5.3/loadall.so'__no file './active_monitoring.so'

*additionally*
Also the module/app(ntopng trough pfsense) creates a error with the pfsense-dashboard(https) connection after reboot of the firewall-computer. HTTPS does not replay after reboot and config of pfsense needs to be changed to http to keep the pfsense dashboard working after a reboot.

please advice
thank you

**Comment by simonemainardi** [comment]
please, report ntopng version used

**Comment by simonemainardi** [comment]
No feedback received. Make sure to install using the instructions at https://www.ntop.org/guides/ntopng/third_party_integrations/pfsense.html

Feel free to reopen with the requested information if necessary.

**Comment by develop-cloud** [comment]
Hi,

Thank you for the replays. The versions were the latest on the moment of creating the topic.

I can confirm that i did not use the provided manual (given above), but the plugin repository installation/add feature of pfsense.

The errors look related of what is described in the manual, given in the link above.

I can not rebuild the situation of wich this ticket is based on due to hardware replacement.

Thank you for the replay that looks like the possible solution to get it proper working.

I'm looking forward to using this software again in the future.

Kind regards
