### ISSUE TITLE
Pre-build package for Debian bullseye?

### ISSUE THREAD

**Issue by ShagoY** [ntop/ntopng#5659]
Hi,
The last update of Proxmox is based on Debian GNU/Linux 11 (bullseye) which makes your packages unusable.

I wonder if you have planned a pre-build package for this version in the future?

**Comment by lucaderi** [comment]
We will provide Debian 11 packages once it ill be officiall released

**Comment by ShagoY** [comment]
Hi :)

I guess you have already seen it : https://www.debian.org/releases/bullseye/

**Comment by Ryananana** [comment]
Hi

I would like to know about the progress of Bullseye support

**Comment by simonemainardi** [comment]
bullseye packages now available, both stable and dev.
