### ISSUE TITLE
nightly builds for armhf packages

### ISSUE THREAD

**Issue by filemoon** [ntop/ntopng#566]
Currently Debian repository is not updated frequently (for some architectures update is more frequent as for others).
For example armhf - last build is dated 26-04-2016 when for X64 is 18-05-2016.

Can you arrange minimum update frame (for example one for week or once for two weeks) - many already solved issues are still present because new build is not available.

Regards Chris

**Comment by simonemainardi** [comment]
actually we support and release x64 nightly builds for both jessie and wheezy

Do you need nightly builds for the 32-bit hard-float armhf architecture?

**Comment by filemoon** [comment]
Yes please :) - armhf will be recommended and arm64 too if possible ;)

Regards Chris

**Comment by simonemainardi** [comment]
armhf nightly builds are now available at: http://packages.ntop.org/RaspberryPI/jessie_pi/armhf/ntopng/
