### ISSUE TITLE
No domain name dumped in flow database (nIndex)

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5660]
The historical flow database does not report the domain name

![Screen Shot 2021-07-12 at 11 14 44](https://user-images.githubusercontent.com/4493366/125262610-9d187e80-e302-11eb-8562-9ed34661732a.png)

whereas this info is shown in the in the flow

![Screen Shot 2021-07-12 at 11 18 41](https://user-images.githubusercontent.com/4493366/125263123-0d270480-e303-11eb-8c64-e5b0ce49cd8e.png)

This needs to be fixed

**Comment by MatteoBiscosi** [comment]
Fixed under the pro repo

**Comment by lucaderi** [comment]
![Screen Shot 2021-07-12 at 19 25 44](https://user-images.githubusercontent.com/4493366/125330385-fd311400-e346-11eb-8ec1-e7092f90439c.png)
Where should the name be set ? Info is empty

**Comment by MatteoBiscosi** [comment]
It should be fixed now, pro repo.

**Comment by lucaderi** [comment]
Verified as fixed
