### ISSUE TITLE
Symbolic host names are missing from top Interface hosts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5661]
![Screen Shot 2021-07-12 at 11 22 15](https://user-images.githubusercontent.com/4493366/125263661-8161a800-e303-11eb-9b4f-534231777acc.png)

**Comment by MatteoBiscosi** [comment]
Fixed in all the "Top" views (Top l7 contacts, Top server, Top client)

**Comment by lucaderi** [comment]
Verified as fixed
