### ISSUE TITLE
Invalid Suspicious Device Protocol Reported

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5664]
The client is not a printer so this alert should not be reported

![Screen Shot 2021-07-12 at 19 18 32](https://user-images.githubusercontent.com/4493366/125329667-11284600-e346-11eb-9fdf-2e81b5a78cf1.png)
![Screen Shot 2021-07-12 at 19 18 59](https://user-images.githubusercontent.com/4493366/125329681-138aa000-e346-11eb-8506-fce5feef49f6.png)

**Comment by simonemainardi** [comment]
Alert has been triggered for the server, which seems to be a printer. Indeed, see "Server application....".

Please explain.

**Comment by simonemainardi** [comment]
Fixed:

- Server application alerts are only triggered if the server has responded
- Messages explain the issue more clearly

![image](https://user-images.githubusercontent.com/3397663/125661138-17d25020-d54c-4a5d-834d-96924317ebd3.png)
