### ISSUE TITLE
Raise an alert when a host contacts an abnormal number of countries/ASN

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5665]
In every local host keep track of the number of different countries and ASN contacted (if GeoIP is disabled this check won't apply) by incrementing a counter (e.g. based on HLL) when a new flow is created. Implement a threshold in the host that checks when a host contacts a high number of countries/ASN (this can be set by implementing a high threshold e.g. with default value 100), as well when its behaviour changes (for this a DES data structure can be used). This ticket will be implemented with a host (not flow) check.

**Comment by tanobar** [comment]
Me and my colleague @D0kken took in charge the issue and we have thought of a solution:
Two objects Cardinality will be added in LocalHostStats.h to count respectively the number of different ASN and different Countries contacted. In LocalHostStats.h will be defined the methods for counters management. In Flow.cpp whenever a new flow will be detected and the associated counter increased by incNumFlows, ASN/Countries counters will be increased too.
Following the guidelines at https://www.ntop.org/guides/ntopng/developing_alerts/index.html, a new check with its alert will be implemented, which examines the value of the counters every 5 minutes and rise an alert whenever the value exceeds the threshold of 100. Counters will be reset at each check.

**Comment by MatteoBiscosi** [comment]
Hi @tanobar and @D0kken the solution you thought about is right. However like luca suggested, instead of using normal counters it should be better using HLL counters and every 5 minutes add the results to a DES structure. In this way we are going to have both a static and a dynamic threshold, like it is currently implemented for the contacted hosts (check hll_contacted_hosts into LocalHostStats class)

**Comment by simonemainardi** [comment]
@tanobar please let us know if the suggestion given works for you. You can also go with the cardinality counters if you reset them periodically.

**Comment by tanobar** [comment]
> @tanobar please let us know if the suggestion given works for you. You can also go with the cardinality counters if you reset them periodically.

Yes, we followed the suggestions. We're almost done. We have to review some things but if you want we can do the Pull Request to show the status of the job.
