### ISSUE TITLE
Inconsistent naming

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5668]
![image](https://user-images.githubusercontent.com/4493366/125431450-c785d4eb-078e-489d-a3a0-47796505403c.png)

In the above page there are 4 different words to identify the same thing
- Flow device
- Flow Exporter
- Probe
- Collector
This needs to be fixed

**Comment by simonemainardi** [comment]
not to say that the documentation carries the old name 'exporters'

**Comment by MatteoBiscosi** [comment]
The only "exporter" name I left are the ones that could compromise the compatibility with the current version (like timeseries or C stats)

**Comment by simonemainardi** [comment]
![image](https://user-images.githubusercontent.com/3397663/126180376-2428ec1b-6cbc-49f6-9976-0c81752590c2.png)

**Comment by lucaderi** [comment]
Verified as fixed (even though via ZMQ we have only nProbes)
