### ISSUE TITLE
Add ability to edit ObservationPoint Name

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5669]
![Screen Shot 2021-07-13 at 11 55 43](https://user-images.githubusercontent.com/4493366/125432111-243fa823-2400-4ddf-8410-8d383ea1ee37.png)

This is similar to what happens for instance with VLANs

**Comment by simonemainardi** [comment]
implement with a REST API endpoint `./scripts/lua/rest/v2/set/obsservation_point/alias.lua` similar to what we have for host `./scripts/lua/rest/v2/set/host/alias.lua`.

The UI should do REST API requests to set the alias.

Extend the REST API swagger doc with documentation when implemented.

**Comment by simonemainardi** [comment]
add http prefix when requesting REST API paths

**Comment by lucaderi** [comment]
In case an observation Point has a custom name set, the text box must contain the value preciously set ("Test" in the example below) and not an empty box

![image](https://user-images.githubusercontent.com/4493366/125906608-a1d9f3e6-9e53-4424-9e6a-3bb01ff679b1.png)

Also please remove debug messages on the console

 table
alias string Test
observation_point string 3333
 table
alias string Test
observation_point string 3333

**Comment by lucaderi** [comment]
1. First problem: the bracket is no longer squared
![Screen Shot 2021-07-19 at 22 21 43](https://user-images.githubusercontent.com/4493366/126222222-42974a3c-5fd8-4c56-961f-108da6f04358.png)

2. Error
![Screen Shot 2021-07-19 at 22 21 21](https://user-images.githubusercontent.com/4493366/126222320-30ea10e5-9932-4655-8bc5-4914ea89f5f2.png)

**Comment by lucaderi** [comment]
Verified as fixed
