### ISSUE TITLE
Missing Infrastructure documentation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5671]
Please document the infrastructure feature, as well write a blog post

**Comment by simonemainardi** [comment]
- Documentation added in the referenced commit
- Blog post available at: https://www.ntop.org/ntopng/infrastructure-monitoring-observing-the-health-and-status-of-multiple-ntopng-instances/
- Youtube video available at: https://www.youtube.com/watch?v=7yWaN3yRErI
