### ISSUE TITLE
Not able to create 

### ISSUE THREAD

**Issue by thomasbruchet** [ntop/ntopng#5673]
Hello.

I want to manage my host into "Host Pool" but the button " + " is grey.
![image](https://user-images.githubusercontent.com/86605223/125462506-2213c92b-9af6-4f97-bc1a-b8d46605e7e3.png)

I've already add some Host
![image](https://user-images.githubusercontent.com/86605223/125463338-0c77b938-732c-422c-9d1c-aa9b6ce90d36.png)

Is there some config to change in ntopng.conf or something that I miss ?

**Comment by simonemainardi** [comment]
Number of pools is limited by the license. What's the license you're running?

**Comment by thomasbruchet** [comment]
> 
> 
> Number of pools is limited by the license. What's the license you're running?

I'm runnin a ntopng Enterprise M v.4.3.210712 (Debian GNU/Linux 10 (buster)) | 

> :~$ ntopng --version
Version:        4.3.210712 [Enterprise/Professional build]
GIT rev:        dev:d94034735289abd07087d7fc7cddd8f7bcf9cd91:20210712
Pro rev:        r3991
Built on:       Debian GNU/Linux 10 (buster)
System Id:      5404F99DB206AB13
Platform:       x86_64
Edition:        Enterprise M
License Type:   Permanent
Maintenance:    Until Sat May 14 16:07:24 2022 [304 days left]

**Comment by simonemainardi** [comment]
how many pools have you defined so far?

**Comment by thomasbruchet** [comment]
I've created no pools, the only one that exist is the default one (screenshot on first message).
<html><body>


Name | Members
-- | --
Default | All unbound


</body>
</html>

**Comment by simonemainardi** [comment]
Sorry, I think it is a bit misleading. To create host pools, go under tab "Host", not "Host Pool". Tab "Host Pool" is to create pools of host pools. Currently not useful.

**Comment by thomasbruchet** [comment]
> To create host pools, go under tab "Host"

OK, that is what I do for now. but this group of host are not usable in Flow filter.
There are not "Hosts" filter nor "Host Pool" in Active Flows, is that a normal situation ?
I've some "Host" already created with IP attached to this host. and I don't understand the point to attach an IP to Host if we can not use it for filter ? Maybe I missed something ?

![image](https://user-images.githubusercontent.com/86605223/125478018-80ab717b-c658-4ca8-8143-41074e65196f.png)
![image](https://user-images.githubusercontent.com/86605223/125478094-d480eacd-0f15-4877-925b-1adc3dd6b744.png)

**Comment by simonemainardi** [comment]
Host pool filter is available under the active flows page

![image](https://user-images.githubusercontent.com/3397663/126668466-fe00a8fe-64ae-4189-bbfa-d820737c7165.png)

You will see all hosts grouped by pool there.

**Comment by thomasbruchet** [comment]
Hello,
There is no Host pool Filter available under the active flows page
Here is my host pool list for all the interfaces, the 2 that I mark are active on the selected interface.
![image](https://user-images.githubusercontent.com/86605223/126780947-4f82c1a0-9e5b-49c4-8829-1cc95a9ca5fa.png)

On the Active Flows of this interface there are no filter in "Host Pool"
![image](https://user-images.githubusercontent.com/86605223/126781025-f5261bf6-2788-4a77-90d8-5c0225a7c908.png)

For the 2 others interface that I manage, that seems to be OK but not for this one.
The only thing that change between them is that I make 3 "Custom Traffic Disaggregation" on this interface but that is not explain why filter are not working on the main interface nor on the 3 disaggregated sub interface; (Disaggregation is done on network and VLAN ID)
