### ISSUE TITLE
Unable to Add Recipient

### ISSUE THREAD

**Issue by lkjom** [ntop/ntopng#5674]
Pretty much identical to https://github.com/ntop/ntopng/issues/4787 (Ntop reinstall didn't resolve)

Cookies / Cache cleared , Various Browsers, Chome, Firefox . Reinstalled NTOPNG from scratch, Attempted with account Authorized by Radius and by builtin Admin

Was possible in the Past perhaps around November but since when you click on add the element becomes disabled  and the edit_notification_recipient.lua returns a result of status: failed

![image](https://user-images.githubusercontent.com/87376849/125462952-d5823d5f-49da-4792-a3ef-6816bef694dc.png)

![image](https://user-images.githubusercontent.com/87376849/125463071-b9c2cdc7-0862-496f-8906-61699c268a69.png)

**Comment by cardigliano** [comment]
The lua endpoint has been improved to provide more info (not just 'failed') in case of failures. A new update will be available later today. Please check it and let us know. Thank you.

**Comment by simonemainardi** [comment]
No feedback received in 6 days, reopen with feedback if necessary.

**Comment by lkjom** [comment]
Apologies I was running on Stable branch instead of Nightly whilst waiting for the update . I have now updated from 4.2->4.3
![image](https://user-images.githubusercontent.com/87376849/126328954-fc08842e-326f-4609-82ac-d0d30d31fd0c.png)

**Comment by simonemainardi** [comment]
remove the recipient and try to re-add it.

**Comment by lkjom** [comment]
Removed all endpoints starting from Scratch
![image](https://user-images.githubusercontent.com/87376849/126329365-c86d4eef-4a0c-4471-a5c9-497ef752c4b2.png)
Added test with IP of basic syslog server
![image](https://user-images.githubusercontent.com/87376849/126329443-5bf0a6f5-d2da-42dd-bba1-f1be21d39b81.png)
![image](https://user-images.githubusercontent.com/87376849/126329494-238ffd36-916c-48d9-a0b4-a9e291276adb.png)
Empty Recipients creating new
![image](https://user-images.githubusercontent.com/87376849/126329606-d4f885ba-7807-45f2-87c2-d2327a45d26b.png)
LUA Error 
![image](https://user-images.githubusercontent.com/87376849/126329911-ee865ae6-a83c-4b79-8682-0815b0117bfd.png)
I tried with binding to all pools checked and unchecked

Cheers

**Comment by cardigliano** [comment]
@lkjom it seems there is something messed up with your endpoints, I suggest to reset the configuration from Settings -> Manage Configurations and reset Endpoints and Recipients

**Comment by lkjom** [comment]
As above Settings->Manage Configurations and reset endpoints and Recipients

Same outcome im afraid , the Command did wipe existing test endpoints (was no recipients anyways)

"Internal_error"

**Comment by cardigliano** [comment]
Any chance we can take a look a this together in a call (or providing ssh)?

**Comment by lkjom** [comment]
Sure We can do a call and have a remote session sure let me know when suits , im 9-5 London time

**Comment by cardigliano** [comment]
@lkjom please send a direct email to cardigliano at ntop.org

**Comment by cardigliano** [comment]
This was caused by a "corrupted" redis db. There was a lock key in a bad state (even the TTL did not remove the key), cleaning up it fixed the issue.
