### ISSUE TITLE
arm64v8 version 4.x for Raspberry Pi 4

### ISSUE THREAD

**Issue by phantomski77** [ntop/ntopng#5675]
Any chance the ntopng versions `4.2` and above will be available for `arm64v8` architecture?

I have managed to modify the Dockerfile that would build an image and run the container on Raspberry Pi 4 (Debian Buster) - [see pull request here](https://github.com/ntop/docker-ntop/pull/4).

The latest available version is only `3.8.190204` however.

Strangely enough `ntopng-data` is available in `4.2`, just not `ntopng`.

Thanks.

**Comment by simonemainardi** [comment]
Did you check nightly raspbian packages available at https://packages.ntop.org?

The ntopng-data you are referring to is not distributed by us. Currently, we are not distributing ntopng-data for the raspberry. That was due to issues with libmaxminddb geolocation. I believe that now we can reconsider this.

**Comment by simonemainardi** [comment]
Sorry, actually we have started distributing also ntopng-data https://packages.ntop.org/RaspberryPI/buster_pi/all/ntopng-data/

I believe you have all the ingredients.

**Comment by phantomski77** [comment]
I've looked at all the repositories and their package contents, and where `all` is available as an architecture, the `ntopng` is actually missing in the packages (it is available only in `x64` architecture).

The only place where there's at least `armhf` version available is the [Raspberry Pi repository](https://packages.ntop.org/RaspberryPI/).

`arm64` architecture is only available in official Debian Buster repo (not ntop.org), but they're old versions.

So to combine best of both worlds, I've modified the `arm64` `Dockerfile` to use latest `armhf` where available, relying on the arm64 devices to run the code.

[Here's the PR](https://github.com/ntop/docker-ntop/pull/5)

Which works, but native arm64 builds would be obviously preferable.

**Comment by simonemainardi** [comment]
Thank you. For the time being, we are not able to also build and maintain for `arm64` as we believe `armhf` is enough for now to support raspberry and other embedded devices.

By using the Dockerfile you've kindly provided, `arm64` can still benefit from ntopng or such architectures.

Thank you.
