### ISSUE TITLE
Multple .lua files not found, 3000 port alredy in use so cant start https and config export gives network error

### ISSUE THREAD

**Issue by jaiinfant** [ntop/ntopng#5676]
fresh install of pfsense verson: 2.5.2-RELEASE (amd64)
absolutely on default configuration
followed by fresh install of ntopng Community v.4.2.210624 by inbuild package manager.
after enabling ntopng and only monitoring lan nterface, i can access ntopng webui. no errors shown. but when i try to export current configuration i get network error.
 all browsers gave same network issue error .
![Capture](https://user-images.githubusercontent.com/87410298/125573301-0065a3c2-8b32-46d6-9c87-63e74ff89278.PNG)

 so i restarted pfsense. now i get error log in ntopng webgui showing port 3000 already in use so https cant be used. additionally active monitoring tab completely disappeared.  now i unplugged lan and wan and restarted again. few min later connected lan and checked, now i got following error in ntopng webgui.

14/Jul/2021 05:44:43 [system_stats.lua:110] [ts_utils_core.lua:582] ERROR Schema not found: process:num_alerts
14/Jul/2021 05:44:42 [AlertCheckLuaEngine.cpp:168] WARNING Script failure[/usr/local/share/ntopng/scripts/callbacks/interface/flow.lua] [...local/share/ntopng/scripts/lua/modules/plugins_utils.lua:997: module 'flow_risks.risk_handler' not found: no field package.preload['flow_risks.risk_handler'] no file '/var/db/ntopng/plugins0/modules/flow_risks/risk_handler.lua' no file '/var/db/ntopng/plugins0/modules/flow_risks/risk_handler.lua' no file '/var/db/ntopng/plugins0/modules/flow_risks/risk_handler.lua' no file '/var/db/ntopng/plugins0/modules/flow_risks/risk_handler.lua' no file

i checked above location and plugins folder was not there. 
i reinstalled everything from scratch and got same issue.
i tried to install opnsense and ntopng in same machine and everthing works fine. but with pfsense its causing problem.

**Comment by simonemainardi** [comment]
To install, please use official instructions at https://www.ntop.org/guides/ntopng/third_party_integrations/pfsense.html

**Comment by jaiinfant** [comment]
ok ill try this and update here

**Comment by jaiinfant** [comment]
> To install, please use official instructions at https://www.ntop.org/guides/ntopng/third_party_integrations/pfsense.html



> To install, please use official instructions at https://www.ntop.org/guides/ntopng/third_party_integrations/pfsense.html

I installed using official method as you said and got latest ntopng Community v.4.3.210714 (FreeBSD 12.2). now everything works fine. seems like pfsense inbuild package manager ntopng version is currently broken. Thankyou

**Comment by simonemainardi** [comment]
Thank you for reporting.
