### ISSUE TITLE
Jailed Host Pool and Host Pool Maximums

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5677]
The addition of a new builtin host pool seems to have reduced the maximum number of pools by one.

This ticket to to increase maximum pools limits according to what is specified in https://www.ntop.org/products/traffic-analysis/ntop/

**Comment by derekslenk** [comment]
I updated to the newest version on OPNsense and the issue persists

[HostPools.cpp:394] WARNING: Ignoring pool [pool id: 5]. Maximum number of host pools for this license is 5, inclusive of the Not Assigned pool.

![image](https://user-images.githubusercontent.com/42957/125824109-082134c5-34aa-4a54-8de3-437576abfb13.png)


 - edit: just realized that it might be tomorrow's nightly that contains it yet

**Comment by simonemainardi** [comment]
Correct. Fix will be available from tomorrow.
