### ISSUE TITLE
Missing option for doubling automatically -X/-x

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5679]
![Screen Shot 2021-07-14 at 17 02 50](https://user-images.githubusercontent.com/4493366/125645371-c3fc043e-4456-47af-9c7f-6837178e5ad6.png)

This used to work some time ago for applications started from systemd. It can be reproduced with ntopng Enterprise L v.4.2.210629 

Regression of #5136 ?

**Comment by simonemainardi** [comment]
Are you getting this behavior also with version 4.3? According to the tests I've run 4.3 seems not to be affected.

Please, also report the OS / distro and keep in mind that the the functionality only works on packaged versions.

**Comment by simonemainardi** [comment]
Feature is supported as of 4.3. Version 4.2 does not support in-place changes.
