### ISSUE TITLE
Support REST API Versions in Infrastructure Monitoring

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5680]
Infrastructure monitoring doesn't support REST API versions. Indeed, the version is hardcoded inside the infrastructure key.

![image](https://user-images.githubusercontent.com/3397663/125646383-c26eb4b3-0d5d-49dc-9157-a5b38273d316.png)

This must be removed. Also, infrastructure implementation should be cleaned and implemented as a regular active monitoring measure.

**Comment by lucaderi** [comment]
Moved to v2
