### ISSUE TITLE
Rework Column Key in Probes List

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5684]
![image](https://user-images.githubusercontent.com/4493366/125946952-b95f6f06-af19-4f03-aed9-f7aa0bd829b5.png)

The current probe key is the nProbe IP and not the interface name used by the probe. Note that multiple probes can run on the same host hence in the future this will be extended with other info such engineId or similar.

**Comment by simonemainardi** [comment]
This has already been reworked. Please, review.

**Comment by lucaderi** [comment]
Verified as fixed
