### ISSUE TITLE
Unable to edit value for ObservationPointID

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5686]
![Screen Shot 2021-07-16 at 15 10 42](https://user-images.githubusercontent.com/4493366/125953750-009b3708-8dee-4d06-9378-27ac63ff5dc2.png)

this is contrary to all other fields 
![Screen Shot 2021-07-16 at 15 16 03](https://user-images.githubusercontent.com/4493366/125953917-6e30c5f6-d2ca-42f6-ba9f-0cdc8f6b976f.png)

**Comment by MatteoBiscosi** [comment]
Fixed, pro repo

**Comment by lucaderi** [comment]
Verified as fixed
