### ISSUE TITLE
Historical Flow Navigation Bug

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5687]
When disabling begin/end time
![Screen Shot 2021-07-16 at 15 49 22](https://user-images.githubusercontent.com/4493366/125958452-ba927a55-f153-40e8-a009-387582fdcfe0.png)

the following error shows up when clicking on actions

![Screen Shot 2021-07-16 at 15 49 30](https://user-images.githubusercontent.com/4493366/125958431-0850ed5e-bba6-4d22-a56f-438666796d61.png)

**Comment by MatteoBiscosi** [comment]
Fixed Pro repo

**Comment by lucaderi** [comment]
Verified as fixed
