### ISSUE TITLE
Misleading Time Pickers

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5689]
ntopng's time pickers are misleading. 
![Screen Shot 2021-07-16 at 22 44 11](https://user-images.githubusercontent.com/4493366/126006543-b0462339-3850-4ea8-a5b9-bbc1f519059f.png)
![Screen Shot 2021-07-16 at 22 45 06](https://user-images.githubusercontent.com/4493366/126006632-97a0029d-7988-439c-8cfe-aba31c708295.png)

First of all their style is not homogeneous, but the main problem is that the time presets are mispleading. For example in grafana

![Screen Shot 2021-07-16 at 22 47 41](https://user-images.githubusercontent.com/4493366/126006878-e24ea5b8-f6a6-4ef2-914a-faed998b891e.png)

When you read "Last hour" it is really 1h from now: as the window stays open, the time refreshes according to the menu below
![Screen Shot 2021-07-16 at 22 48 58](https://user-images.githubusercontent.com/4493366/126007057-f181f2ab-34be-42e1-9c4b-f21ed827549a.png)

I see two options
- either when "30 min" is set, the time is set, and the drop-down menu changes to "Custom"
- or a menu as the one above is implemented and the menu stays as today set to "Last 30 min"

**Comment by VasilisTako** [comment]
Updated under Pro version. Waiting for review about "Custom" field behavior when changing date.

**Comment by lucaderi** [comment]
There is still a flaw. Click on Interface -> Chart icon you get 
![Screen Shot 2021-07-22 at 19 06 11](https://user-images.githubusercontent.com/4493366/126679759-a5597104-c18c-46c0-9f24-41dd7e441f03.png)
as in hosts
![Screen Shot 2021-07-22 at 19 06 44](https://user-images.githubusercontent.com/4493366/126679848-65c77e54-a9fb-49e0-a7c7-f82d47c010a7.png)
and alerts
![Screen Shot 2021-07-22 at 19 13 14](https://user-images.githubusercontent.com/4493366/126680621-1c86d081-5414-47b6-81bd-ce423d764f0a.png)

**Comment by simonemainardi** [comment]
yes, this has already been reported @VasilisTako is dealing with it

**Comment by MatteoBiscosi** [comment]
Fixed partially in the latest version. Follow issue #6301 regarding multiple time pickers used
