### ISSUE TITLE
Continuous check update slows down operations

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5690]
ntopng calls check_update.lua every 10 seconds

![image](https://user-images.githubusercontent.com/4493366/126009744-6448b6a3-b145-46fa-8bd5-92baf5b6d902.png)

Said that this is not a good practice, in case the check update is slow, the GUI is slow when rendering the menu

You can reproduce this bug on 194.242....

**Comment by simonemainardi** [comment]
Moreover, the new offline mode should be used to completely avoid checks when ntopng is offline

**Comment by cardigliano** [comment]
Optimized in 717c73d6498a75de4fb4a0358300c13dc62a518a

**Comment by cardigliano** [comment]
Offline mode is also disabling updates check with 56d63ae507f1f5dc5079bf7941f455b25b0be292

**Comment by lucaderi** [comment]
![Screen Shot 2021-07-19 at 23 08 48](https://user-images.githubusercontent.com/4493366/126227754-04540960-2b57-449d-a48d-ff7c54de6bc6.png)
I still see it called often

Furthermore, the menu is still hanging, maybe for a different issue, but it needs to be investigated. You can reproduce it on 194... hosts you have access to

**Comment by cardigliano** [comment]
TIming fixed/improved in fce7511388df0bf58bbc69c46b0d5c3677b802e2

**Comment by lucaderi** [comment]
Problem mitigated but still hanging
![image](https://user-images.githubusercontent.com/4493366/126678495-e0da1b13-5d28-4cb5-b6df-e3be039de24f.png)
![image](https://user-images.githubusercontent.com/4493366/126678554-0f34627b-1157-4a4c-b047-2605db5ccbda.png)

**Comment by cardigliano** [comment]
The check update call is now async, I already updated the box (today) and it seems the page is loading smoothly, please confirm (actually I was not able to reproduce the issue even before).

**Comment by lucaderi** [comment]
Seems to work now
