### ISSUE TITLE
Unable to see TOP sender data under interface 

### ISSUE THREAD

**Issue by adipadalwar** [ntop/ntopng#5693]
![image](https://user-images.githubusercontent.com/87663746/126194052-1402afd7-9afc-4812-8148-80aecb773419.png)

**Comment by simonemainardi** [comment]
Likely the interval is too tiny (see you have 5 minutes).

Try to enlarge a bit.

**Comment by simonemainardi** [comment]
Duplicate of https://github.com/ntop/ntopng/issues/5691. Likely addressed in the pro part. Hold on a couple of hours, update to the latest 4.3 stable, and it will work.
