### ISSUE TITLE
Score alerts are not generated for all hosts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5694]
Score is enabled with a top value of 5000
![Screen Shot 2021-07-19 at 22 39 38](https://user-images.githubusercontent.com/4493366/126224420-adf85500-e680-49d5-8060-f6c73ba848f5.png)

Several hosts have high score
![image](https://user-images.githubusercontent.com/4493366/126224482-1e665461-22d7-4bcb-955a-9bcd85082c96.png)

Only 4 hosts have alerts
![image](https://user-images.githubusercontent.com/4493366/126224647-0119c472-e0e1-46b9-840c-14dd1a817b1c.png)

instead of many more hosts.

**Comment by simonemainardi** [comment]
Issue is potentially fixed in the referenced commit and companion pro commit.

It was likely due to the use of the DES-smoothed score value rather that the actual score value when comparing it with the threshold.

Builds are in progress, please check and report.

**Comment by lucaderi** [comment]
The bug was not DES related but static threshold related. It seems to be fixed now.
