### ISSUE TITLE
Engaged alerts are lost across restarts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5695]
When a ntopng Instance with engaged alerts is restarted, engaged alerts are lost (not nice but ok) and they do not appear in past alerts. They need at least to be stored in past alerts

**Comment by simonemainardi** [comment]
I have verified that a clean shutdown causes engaged alerts to be released for:

- interfaces
- hosts
- local networks

Missing alerts can therefore be to to an unclean shutdown.

**Comment by lucaderi** [comment]
Verified as fixed (they appear on the past page).

Please add the commit fixing this issue and close this ticket.

**Comment by simonemainardi** [comment]
No commit has fixed it, likely, as explained above, missing alerts were due to an unclean shutdown.
