### ISSUE TITLE
Upgrade Tests [Centos 8]

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5697]
It is requested to test the upgrade between 4.2 and 4.3 (which soon will become 5.0 stable) on Centos 8 using packaged versions of ntopng:

- Install stable packages
- Run version 4.2
- Install dev packages
- Check ntopng data and make sure no error is occurring

Tests must be done using:

- [ ] RRD
- [ ] InfluxDB
- [ ] nIndex
- [ ] With host pools defined
- [ ] With endpoints and recipients defined

**Comment by cardigliano** [comment]
Verified
