### ISSUE TITLE
Realtime traffic calculation when using nProbe

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#57]
When ntopng is used as flow collector, the traffic graphs are not accurate as ntopng computes the bytes/packets from flows. This is not correct, as flows contain average value and are sent to ntop periodically thus invalidating the realtime view of traffic.

**Comment by shadow974** [comment]
Any news here? The only way to get accurate readings is to let ntopng capture by itself on the interface?

**Comment by lmangani** [comment]
Milestone is ntopng 2.1

**Comment by simonemainardi** [comment]
implemented in the latest nProbe/ntopng through ZMQ events.
