### ISSUE TITLE
Getting a cookie for a LDAP username 

### ISSUE THREAD

**Issue by TimotheusBachinger** [ntop/ntopng#5703]
Hi Ntop Team,

We have the use case where ntop and checkmk is connected to the same LDAP. 

Usally we're retriving a cookie for a ntop user via a ntop admin account:

```
>>> requests.post("http://XXX.com:3000/lua/rest/v1/create/ntopng/session.lua", json={"username": "hansdampf"}, auth=("admin", "XXX")).json()
{'rc': 0, 'rc_str': 'OK', 'rsp': {'session': 'f4653c482e108f50d8d3109ab66725de'}, 'rc_str_hr': 'Success'}
```

But when using the LDAP user name, we cannot get a cookie for this user:
```
>>> requests.post("http://XXX.com:3000/lua/rest/v1/create/ntopng/session.lua", json={"username": "hans.dampf"}, auth=("admin", "XXX")).json()
{'rsp': [], 'rc_str_hr': 'Invalid arguments', 'rc_str': 'INVALID_ARGUMENTS', 'rc': -5}
```

Can you reproduce this on your side and maybe fix this?

Best regards
Timi

**Comment by cardigliano** [comment]
This is supported for Local users only at the moment. This needs to be extended to also LDAP users.

**Comment by TimotheusBachinger** [comment]
Thanks for the information. Can you estimate a time frame when this will be possible?

**Comment by cardigliano** [comment]
@TimotheusBachinger this ticket requires some considerations. When the (authenticated) LDAP user itself requires the creation of a new session, there should be no major issues in implementing this. However, when the admin user requires the creation of a session for an LDAP user, the LDAP authentication is required in order to verify that the user is valid. Is it fine to require also the user password in that case (with the requestor acting as a "proxy")? Does this work for your use case, of do you have any other idea?

**Comment by TimotheusBachinger** [comment]
@cardigliano would this mean that for getting a session cookie for a LDAP user, we would need to sent the user password as well in the API request? 
If yes, this would break our concept of "only storing NTOP admin credentials" on our side.

**Comment by cardigliano** [comment]
@TimotheusBachinger that was just a possible option, but I understand it works on specific use cases only. Another solution should be used then.

**Comment by simonemainardi** [comment]
The point is that if you want to generate a session cookie for an LDAP user, and you are "only storing NTOP admin credentials" then the NTOP admin should act as a proxy for the LDAP user.

So a possible solution can be:

1. The LDAP user tells check_mk `ldap_username` and `ldap_password`
2. check_mk uses the "NTOP admin credentials" to proxy `ldap_username` and `ldap_password` credentials to `v1/create/ntopng/session.lua`
3. ntopng generates a session cookie for `ldap_username` and tell it back to check_mk as part of the REST response
4. From this point on the `ldap_username` can use the cookie to log in (for the configured amount of time)

**Comment by simonemainardi** [comment]
@TimotheusBachinger do you have any feedback on this.

**Comment by TimotheusBachinger** [comment]
@simonemainardi  unfortunately, i couldn't look into this the last weeks... I will be on holiday for the next 3 weeks, so we could also close it for now.

**Comment by simonemainardi** [comment]
We can leave it open until we decide. Will wait until you're back. Thanks!
