### ISSUE TITLE
Interface REST API endpoints not reading ifid

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5704]
There are several REST API endpoints that don't read the interface id. It is requested to:

- always pass `ifid` when the UI needs to call the endpoints
- throw an `INVALID_INTERFACE` error when `ifid` is not submitted

Endpoints are:

- [x] /lua/rest/v2/charts/host/map.lua 
- [x] /lua/pro/rest/v2/get/maps/periodicity_map.lua
- [x] /lua/pro/rest/v2/get/maps/service_map.lua
- [x]  /lua/pro/rest/v2/get/interface/top/l7_stats.lua
- [x] /lua/pro/rest/v2/get/interface/top/score.lua
- [x] /lua/pro/rest/v2/get/interface/top/realtime_traffic.lua
- [x] /lua/pro/rest/v2/get/interface/top/remote/talkers_ng.lua
- [x] /lua/pro/rest/v2/get/observation_points/stats.lua
- [x] /lua/pro/rest/v2/get/host/flows/flows_info.lua

Fix must be done both for v1/ and v2/ REST APIs.

**Comment by simonemainardi** [comment]
moreover, to clean the tree, only for v2/, do the following moves

/lua/pro/rest/v2/get/maps/periodicity_map.lua -> /lua/pro/rest/v2/get/interface/map/periodicity.lua
/lua/pro/rest/v2/get/maps/service_map.lua -> /lua/pro/rest/v2/get/interface/map/service.lua
/lua/pro/rest/v2/get/observation_points/stats.lua -> /lua/pro/rest/v2/get/interface/observation_points/stats.lua
/lua/rest/v2/charts/host/map.lua -> /lua/rest/v2/get/host/map.lua

**Comment by cardigliano** [comment]
Fixed on 1540d46e7a5434619996c95bfc8803128a0be4cc and 55e1d38e086df287c8a37b9befb07659baf77c74 (and the pro branch)
