### ISSUE TITLE
Empty Networks/Hosts report with View Interfaces

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5705]
![Screen Shot 2021-07-22 at 18 55 00](https://user-images.githubusercontent.com/4493366/126678191-e416c8b0-f62a-4d4b-93cb-bbce4ed49db4.png)

**Comment by simonemainardi** [comment]
Addressed in the pro part

![image](https://user-images.githubusercontent.com/3397663/126972254-e8daf261-6843-4bb0-8373-a6459eeb9abb.png)

**Comment by lucaderi** [comment]
Verified as fixed
