### ISSUE TITLE
Timepickers need to be Harmonised

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5707]
![Screen Shot 2021-07-22 at 19 05 21](https://user-images.githubusercontent.com/4493366/126679915-278c5e74-fe40-424d-b605-8127cfdb9174.png)
![Screen Shot 2021-07-22 at 19 06 44](https://user-images.githubusercontent.com/4493366/126679922-ee96e4a8-a08d-4686-aa39-7786a9c36d73.png)

**Comment by simonemainardi** [comment]
part of https://github.com/ntop/ntopng/issues/5689
