### ISSUE TITLE
Historical Flow Explorer

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#5709]
1、I export the history stream to elasticsearch. Can I view and export the history flows on ntopng? Just like Historical Flow Explorer?
2、Can we export the history flows to ES and MySQL at the same time?

**Comment by simonemainardi** [comment]
> 1、I export the history stream to elasticsearch. Can I view and export the history flows on ntopng? Just like Historical Flow Explorer?

Historical explorer is available when using nIndex or MySQL, not Elasticsearch

> 2、Can we export the history flows to ES and MySQL at the same time?

Only one downstream recipient is supported at time.
