### ISSUE TITLE
Broadcast traffic computation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#571]
As with -m we have the list of networks, so that we can compute the broadcast addresses (in addition to the usual 255.255.255.255 and 0.0.0.0) so that we can tag each flow for "broadcast" and thus compute this in RRDs (and also in GUIs)

**Comment by simonemainardi** [comment]
implemented:

- broadcast addresses are now computed using defined local networks

- flows can be searched using new criteria that include broadcast 

![image](https://user-images.githubusercontent.com/3397663/28788191-c7987ac4-761f-11e7-9058-c2cb5143a042.png)

- timeseries of broadcast traffic are saved per network

![image](https://user-images.githubusercontent.com/3397663/28788243-095ba0a8-7620-11e7-914c-a25f393079f8.png)
