### ISSUE TITLE
Link Error - You are not supposed to be here.

### ISSUE THREAD

**Issue by thomasbruchet** [ntop/ntopng#5711]
Hello.

I've a webpage error when I try to go into the "Check settings" of a "warning" alert for a device.
```
You're not supposed to be here!
The requested page cannot be found
```

I select my [interface] then [Alert]>[Device]
![image](https://user-images.githubusercontent.com/86605223/126779057-ccbd6a3e-8f2b-4a5e-a4fc-1cfdf52fd229.png)

On the new page, I'm going to clic on the settings icon for an alert ![image](https://user-images.githubusercontent.com/86605223/126779227-44e153a8-5969-498d-92c4-2aea93982e2d.png)
Then I have this webpage error and the "<-Go back" link is about https://ntop:3000/lua/undefined
![image](https://user-images.githubusercontent.com/86605223/126779298-29746b88-f325-46f7-a975-b1376359f8b0.png)

Thoses alerts are for "Broadcast domain (100.0%)" and the link of the settings icon is: https://ntop:3000/lua/alert_stats.lua?status=historical&page=mac#check_settings

**Comment by simonemainardi** [comment]
It is not clear how to trigger this behavior.

Please attach additional examples, and where you click, including the whole alert line with the type.

**Comment by thomasbruchet** [comment]
I'm on vacation for a week and can't do anything on the system.  Please consider my issue as hold for a week.

**Comment by thomasbruchet** [comment]
Hello I'm back.
Here are the followings step to proceed.
> Select an interface 
![image](https://user-images.githubusercontent.com/86605223/127833983-804c2ed3-6128-456f-8554-31338f8fd0ad.png)

> Clic on the "Alert" icon.
![image](https://user-images.githubusercontent.com/86605223/127834065-be3ca3cd-5f4e-4c76-bb94-a9f143abe1d7.png)

> Clic on the number on "Device" line and "Warning" column, here is 141 (URL::  https://ntop:3000/lua/alert_stats.lua?page=mac&epoch_begin=1627892901&epoch_end=1627894701&status=historical&severity=4;eq )
![image](https://user-images.githubusercontent.com/86605223/127834126-ae27deae-09cc-457b-a0ab-29bc0c13d241.png)

> The next window is for alet on device and all are for "Broadcast domain (100.0%)"
![image](https://user-images.githubusercontent.com/86605223/127834930-b54e040a-bf11-4f2a-8316-942a7a8365d5.png)

> When I clic on the setting icon (URL: https://ntop:3000/lua/alert_stats.lua?page=mac&epoch_begin=1627892901&epoch_end=1627894701&status=historical&severity=4;eq#check_settings ) I've the following error.
![image](https://user-images.githubusercontent.com/86605223/127835234-bd6e9392-23b0-4de4-9b4c-7487418283b8.png)

**Comment by lucaderi** [comment]
Works for us, will reopen if necessary
