### ISSUE TITLE
Host pool filter is not available on one interface.

### ISSUE THREAD

**Issue by thomasbruchet** [ntop/ntopng#5712]
Hello,
There is no Host pool Filter available under the active flows page
Here is my host pool list for all the interfaces, the 2 that I mark are active on the selected interface.
![image](https://user-images.githubusercontent.com/86605223/126780947-4f82c1a0-9e5b-49c4-8829-1cc95a9ca5fa.png)

On the Active Flows of this interface there are no filter in "Host Pool"
![image](https://user-images.githubusercontent.com/86605223/126781025-f5261bf6-2788-4a77-90d8-5c0225a7c908.png)

For the 2 others interface that I manage, that seems to be OK but not for this one.
The only thing that change between them is that I make 3 "Custom Traffic Disaggregation" on this interface but that is not explain why filter are not working on the main interface nor on the 3 disaggregated sub interface; (Disaggregation is done on network and VLAN ID)

**Comment by simonemainardi** [comment]
> "Custom Traffic Disaggregation" 

Please, try and disable disaggregation, restart ntopng, and report.

**Comment by thomasbruchet** [comment]
I'm on vacation for a week and can't do anything on the system.  Please consider my issue as hold for a week.

**Comment by thomasbruchet** [comment]
I've worked on this problem and find why there is no option to filter.
Filters only work on current view, not for the entire interface. In my case there was no flow in warning for the host pool that I've created.
So no flow for those host pools = no filter available.

I've looked for other flow with error linked to my host pool definition and the filter is OK.

The issue can be closed.

**Comment by thomasbruchet** [comment]
Wrong understanding of how flow filters work
