### ISSUE TITLE
Raise an alert when a host contacts an abnormal number of host names

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5716]
Same as #5665 but counting domain names contacted by a host. In essence in every localHost instantiate a HLL data structure with a few bytes (4 can be enough) and for every flow do
-  char *name = ndpiFlow ? ndpi_get_flow_name(ndpiFlow) : NULL;
- increment the HLL member used to count the number of contacted host names 
- Raise an alert when a high number of names is contacted every 1 (or 5) minutes.
- A default threshold can be 250 (minute) or 1000 (5 minutes)

**Comment by D0kken** [comment]
My colleague @tanobar and I are working for this Issue. Anyway, is the use of a DES data structure still required ?

**Comment by MatteoBiscosi** [comment]
Implemented as requested
