### ISSUE TITLE
Wrong traffic statistics

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#5719]
version : ntopng 4.2 bundle stable ,
os : centos7

I use nprobe to receive NetFlow and then use ntopng to monitor, but I encounter an incorrect traffic statistics. Ntopng shows that there is 3TB of DNS traffic,but we checked that the host traffic is actually only tens of KB

![image](https://user-images.githubusercontent.com/44804599/127272826-920cd3fe-d06e-45a3-b379-5e80e730ac3c.png)

**Comment by MaoPann** [comment]
Similar error

![image](https://user-images.githubusercontent.com/44804599/127278456-5866a3de-e3f0-4510-83bc-e957ed19ad1c.png)
![image](https://user-images.githubusercontent.com/44804599/127278501-d2043689-0c66-4f6f-b232-c7d64aee0eaf.png)

**Comment by simonemainardi** [comment]
You have sampled NetFlow traffic (see https://github.com/ntop/nProbe/issues/499), so collected traffic is upscaled according to the sampling factor.

If you don't want to upscale the traffic, you can tune nProbe option `--sample-rate`. You can also tune the upscaling behavior by changing this:

![image](https://user-images.githubusercontent.com/3397663/127320777-03493c75-48c7-4dba-91d5-e1a8542221ce.png)

Alternatively, if as already described in https://github.com/ntop/nProbe/issues/499 you cannot tolerate sampling approximations, then you should consider disabling it.

**Comment by MaoPann** [comment]
@simonemainardi 
The sampling I'm talking about is set when the switch generates NetFlow. Nprobe did not sample NetFlow，in other words，--sample-rate=1 and lngress Packets Sampling Rate =1.
If it is only an approximate value, I can accept it, but some flows are thousands of times different from the actual flow.
Ntopng shows that there is 3TB of DNS traffic,but we checked that the host traffic is actually only tens of KB
![image](https://user-images.githubusercontent.com/44804599/127416102-41047a91-32f8-44ab-9c19-ab9fd95b7fcb.png)

**Comment by simonemainardi** [comment]
- Attach a pcap capture of the NetFlow yielding those values (make sure it contains data and templates)
- Report the nProbe configuration used
- Report the ntopng configuration used
