### ISSUE TITLE
Export/Display nProbe Flow configuration options

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#572]
It would be desirable to export/visualize nprobe configuration (e.g. the flow duration...) in the interface view

**Comment by simonemainardi** [comment]
![image](https://user-images.githubusercontent.com/3397663/28998218-c3945e66-7a25-11e7-9c57-96826832982a.png)

Implemented along with a refactor of NetworkInterface and ParserInterface to make sure nProbe data is not instantiated for non-parser interfaces
