### ISSUE TITLE
Errors during alert navigation 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5722]
![Screen Shot 2021-07-28 at 22 03 05](https://user-images.githubusercontent.com/4493366/127388194-2c3e0545-5514-42e9-bd4c-9f77e3753451.png)
![Screen Shot 2021-07-28 at 22 02 54](https://user-images.githubusercontent.com/4493366/127388198-08c01258-7bfe-42a8-b5e6-96a9c9afc384.png)

**Comment by simonemainardi** [comment]
Thanks for reporting. It was part of a WIP that will be completed in the next few hours. I've temporarily disabled this.
