### ISSUE TITLE
Statistical report

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#5724]
Can I set the number of top IPS for the reports generated by ntopng？
For example, I want to set top 150 IP addresses
![image](https://user-images.githubusercontent.com/44804599/127627563-1039a325-c1ce-4e4f-8670-5de74c0fe521.png)

**Comment by simonemainardi** [comment]
No. There are heuristics that estimate the number of top-talkers to keep in the report.

If you need arbitrary precision, use nIndex and store all flows. Using this you'll be able to extract any number of talkers, at the expense of more disk space used.
