### ISSUE TITLE
Reduce number of periodic checks

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5726]
If possible theseminute checks must be avoided

Aug  2 10:40:01 ntop2 CRON[8421]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a check-updates-on-demand)
Aug  2 10:40:01 ntop2 CRON[8422]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-upgrade-requests)
Aug  2 10:41:01 ntop2 CRON[8849]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a check-updates-on-demand)
Aug  2 10:41:01 ntop2 CRON[8850]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-upgrade-requests)
Aug  2 10:42:01 ntop2 CRON[9128]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-upgrade-requests)
Aug  2 10:42:01 ntop2 CRON[9129]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a check-updates-on-demand)
Aug  2 10:43:01 ntop2 CRON[9405]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a check-updates-on-demand)
Aug  2 10:43:01 ntop2 CRON[9406]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-upgrade-requests)
Aug  2 10:44:01 ntop2 CRON[9687]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a check-updates-on-demand)
Aug  2 10:44:01 ntop2 CRON[9688]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-upgrade-requests)
Aug  2 10:45:01 ntop2 CRON[9960]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a check-updates-on-demand)
Aug  2 10:45:01 ntop2 CRON[9961]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-upgrade-requests)

**Comment by cardigliano** [comment]
Currently there is a cron task polling for requests from the GUI to check (on demand) if a new update is available through apt/yum, or install the update. In order to avoid this ntopng should run a script directly, with privileges for using apt, and other implications on the update mechanism (e.g. for upgrading and restarting ntopng)

**Comment by cardigliano** [comment]
ad726155a9a206df3c6ac3de52d345815fb1326a halves the number of cron script executions

**Comment by lucaderi** [comment]
Aug 17 09:58:01 ntop2 CRON[6619]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 09:59:01 ntop2 CRON[6794]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:00:01 ntop2 CRON[6989]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:01:01 ntop2 CRON[7181]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:02:01 ntop2 CRON[7371]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:03:01 ntop2 CRON[7551]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:04:01 ntop2 CRON[7726]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:05:01 ntop2 CRON[7898]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:06:01 ntop2 CRON[8085]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:07:01 ntop2 CRON[8265]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:08:01 ntop2 CRON[8455]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:09:01 ntop2 CRON[8631]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:10:01 ntop2 CRON[8798]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:11:01 ntop2 CRON[9017]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:12:01 ntop2 CRON[9207]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:13:01 ntop2 CRON[9402]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:14:01 ntop2 CRON[9598]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:15:01 ntop2 CRON[9765]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:16:01 ntop2 CRON[9964]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:17:02 ntop2 CRON[10141]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:18:01 ntop2 CRON[10316]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:19:01 ntop2 CRON[10491]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:20:01 ntop2 CRON[10661]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:21:01 ntop2 CRON[10868]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:22:01 ntop2 CRON[11077]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:23:01 ntop2 CRON[11280]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:24:01 ntop2 CRON[11462]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:25:01 ntop2 CRON[11652]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:26:01 ntop2 CRON[11844]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:27:01 ntop2 CRON[12014]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:28:01 ntop2 CRON[12214]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:29:01 ntop2 CRON[12397]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:30:01 ntop2 CRON[12573]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:31:01 ntop2 CRON[12777]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:32:01 ntop2 CRON[12937]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:33:01 ntop2 CRON[13118]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:34:01 ntop2 CRON[13275]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:35:01 ntop2 CRON[13488]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:36:00 ntop2 CRON[14625]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:37:01 ntop2 CRON[14948]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:38:01 ntop2 CRON[15146]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:39:01 ntop2 CRON[15328]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Aug 17 10:40:01 ntop2 CRON[15511]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-reque

You have reduced the number of double checks but the problem stays
