### ISSUE TITLE
Names are not supposed to be shortened

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5727]
![Screen Shot 2021-08-03 at 18 49 28](https://user-images.githubusercontent.com/4493366/128054821-e512b1b6-0244-4a58-bda4-43eafbd556a6.png)
While on the GUI, names need to be cut in size, they must be kept as they have been received for troubleshooting purposes. 

Furthermore are already discussed, the tooltip must include the full hostname (unshortened) as well its numeric IP

**Comment by simonemainardi** [comment]
![image](https://user-images.githubusercontent.com/3397663/128060902-52a04f5d-876c-4ca9-a487-5af86f25c9bc.png)

**Comment by simonemainardi** [comment]
Implemented the same behavior when drilling down nIndex flows under the pro

![image](https://user-images.githubusercontent.com/3397663/128154012-7af32d7f-bd6c-4985-85d3-e90e8dac992e.png)

**Comment by lucaderi** [comment]
Verified as fixed
