### ISSUE TITLE
Wrong pcap file format

### ISSUE THREAD

**Issue by chris-ruddy** [ntop/ntopng#5728]
Pcap files with nanosecond timestamps are exported by ntopng (v.4.2.210729) in microsecond format instead of nanosecond format. This causes Wireshark to display the timestamps as negative numbers.

![image (1)](https://user-images.githubusercontent.com/87386616/128090003-47ea863e-8956-447c-a989-68e6b73f7e8a.png)

Nanosecond format pcap files have different magic numbers:

```
$ file *.pcap 
micro.pcap: pcap capture file, microsecond ts (little-endian) - version 2.4 (Ethernet, capture length 1544)
nano.pcap:  pcap capture file, nanosecond ts (little-endian) - version 50098.212 (Ethernet, capture length 1544)
```

If you change the magic numbers of a pcap exported by ntopng with a hex editor, then Wireshark displays the timestamps correctly.

Here are some links with more information:

- https://www.wireshark.org/lists/wireshark-users/200908/msg00224.html
- https://stackoverflow.com/questions/17928319/whats-the-difference-between-a-pcap-file-with-a-magic-number-of-0x4d3cb2a1-an
- https://www.tcpdump.org/manpages/pcap-savefile.5.txt

Please fix the magic numbers on nanosecond pcap files exported by ntopng. Thanks.

**Comment by cardigliano** [comment]
@chris-ruddy how are you exporting the file? Could you provide more details about your configuration and operation? Thank you.

**Comment by chris-ruddy** [comment]
@cardigliano we're exporting the file from the ntopng GUI:

<img width="1533" alt="Screen Shot 2021-08-04 at 12 59 40" src="https://user-images.githubusercontent.com/87386616/128223119-95b87154-c75e-4fc6-81f7-0cab67a1c46d.png">

Our setup is four n2disk instances write data to disk (with nanosecond timestamps), which is sent to ntopng with zmq.

Here is one n2disk config (the others are the same other than interface name, output dir, cpu affinity, pid, and zmq port)

`--interface=nt:0
--dump-directory=/opt/data/capture/ntopng/15/pcap
--index
--timeline-dir=/opt/data/capture/ntopng/15/timeline
--buffer-len=2048
--chunk-len=4096
--active-wait
--pcap-compression
--max-file-len=256
--max-file-duration=60
--disk-limit=23%
--snaplen=9100
--writer-cpu-affinity=3
--reader-cpu-affinity=2
--compressor-cpu-affinity=5,7
--index-on-compressor-threads
-u=ntopng
--capture-direction=0
--daemon
-P=/var/run/n2disk-nt:0.pid
--nanoseconds
--zmq=tcp://127.0.0.1:5556
--zmq-probe-mode
--zmq-export-flows`

Here is our ntopng config:

`-G=/var/run/ntopng.pid
-i=lo
-i=tcp://*:5556c
-i=tcp://*:5557c
-i=tcp://*:5558c
-i=tcp://*:5559c
-m=#redacted
-d=/opt/data/capture/ntopng
-F nindex
-p=/var/lib/ntopng/protos.txt
`

**Comment by cardigliano** [comment]
@chris-ruddy got it, thank you for the details

**Comment by cardigliano** [comment]
This has been fixed. A new dev package is already available. A new stable will be available soon.

**Comment by chris-ruddy** [comment]
As of today, running the latest nightly build (ntopng-4.3.210816-14683.x86_64), the ntopng GUI still returns .pcap files in microsecond format:

```1629136800-1629138600.pcap: pcap capture file, microsecond ts (little-endian) - version 2.4 (Ethernet, capture length 1544)```

```
Name        : ntopng
Version     : 4.3.210816
Release     : 14683
Architecture: x86_64
Install Date: Mon 16 Aug 2021 05:48:08 PM UTC
Group       : Networking/Utilities
Size        : 51115495
License     : GPL
Signature   : RSA/SHA256, Mon 16 Aug 2021 02:04:05 PM UTC, Key ID 6f13614fd1eb60be
Source RPM  : ntopng-4.3.210816-14683.src.rpm
Build Date  : Mon 16 Aug 2021 02:03:57 PM UTC
Build Host  : centos8
Relocations : (not relocatable)
Packager    : Luca Deri <deri@ntop.org>
URL         : http://www.ntop.org/
Summary     : Web-based network traffic monitoring
Description :
ntopng high-speed web-based traffic monitoring and analysis tool (libpcap)
Web-based traffic monitoring

%setup -q
```

**Comment by cardigliano** [comment]
@chris-ruddy yes, the pcap format returned from ntopng is expected to be always usec now, please note the timestamp has been fixed (converted from nsec to usec). This is because in theory ntopng can extract from multiple files with different timestamps (e.g. when changing the n2disk configuration). If you want the nsec precision also when running extractions from ntopng, we need to implement that.

**Comment by chris-ruddy** [comment]
@cardigliano, we require ntopng to be able to extract pcap files with nanosecond timestamps; that's why I wrote this ticket. We use ntopng for operations and need to be able to extract pcaps that work in Wireshark without having to modify them in a hex editor first. How do we get this feature added? Thanks.
