### ISSUE TITLE
Option to configure the traffic report

### ISSUE THREAD

**Issue by thomasbruchet** [ntop/ntopng#5729]
Hello,

I would like export or use recipients/endpoints to send a mail with a daily/weekly/monthly traffic report and some options to configure thoses report like remove some information like in exemple;
- Top Networks [] [Average Traffic/sec]
- Top Countries [] [Average Traffic/sec]
- Top ASN [] [Average Traffic/sec]
- Top Local OS [] [Average Traffic/sec]
- Top Non-Local OS [] [Average Traffic/sec]

I'm on a network with more than 200 VLAN and a full report give me more than 1885 pages.
That is not releveant to have all thoses information dedicated by VLAN on each interface for me and I don't find an option to manage the reporting exept in the Filter report with [Network interface] or [Application]
The best for me as I use "Custom Traffic Disaggregation" should be to disable all VLAN reporting and just report information that I need about the interface or Sub Interface.

Is there a way to improve this part of NTOPNG ?

**Comment by MatteoBiscosi** [comment]
It is now possible with the customisable report page.
