### ISSUE TITLE
Service and periodicity maps broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5732]
![Screen Shot 2021-08-04 at 17 11 51](https://user-images.githubusercontent.com/4493366/128222955-719a25e0-55fe-4d9e-8111-746c1c6c7ae4.png)

**Comment by lucaderi** [comment]
@MatteoBiscosi Please note that the interface alias is not taken into account and still view://... is used

**Comment by simonemainardi** [comment]
See now.

![image](https://user-images.githubusercontent.com/3397663/128303106-b4f83951-da92-422f-9fa3-2dfe42357d38.png)

**Comment by lucaderi** [comment]
This is what I get on 194.....

![Screen Shot 2021-08-06 at 14 21 15](https://user-images.githubusercontent.com/4493366/128509580-456edc7c-d586-434e-beaf-129f30943559.png)

and this is what happens when (with the service map selected) I switch interface

![Screen Shot 2021-08-06 at 14 21 45](https://user-images.githubusercontent.com/4493366/128509673-39095fcc-77a1-4eca-9db0-8032eadb5264.png)

**Comment by MatteoBiscosi** [comment]
Fixed, pro repo, the issue was just with the views

**Comment by lucaderi** [comment]
Map is now loading as expected
