### ISSUE TITLE
Exclude Checks: Suspicious Device Protocol - Invalid arguments

### ISSUE THREAD

**Issue by thomasbruchet** [ntop/ntopng#5736]
Hello,

I wanted to exclude an IP from a check and when I do, I get an error of Invalid arguments.
There are no arguments besides what is displayed that I can act on.

![image](https://user-images.githubusercontent.com/86605223/128491087-8d5d4f6a-98c4-4bc2-9404-a08711083793.png)

![image](https://user-images.githubusercontent.com/86605223/128490715-8ccd6963-56d8-4182-afdd-b2895c6223cf.png)

**Comment by simonemainardi** [comment]
Thanks for reporting. Issue is fixed and will be available in the next build within 24h.
