### ISSUE TITLE
DB Explorer IP Host Enhancements

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#574]
1. Add JSON completion in IP field
2. Add ability to specify src/dst/both in IP field
3. Add ability to add wildcard "broadcast" as IP
4. Add ability to specify CIDS (IP/mask) in IP

**Comment by simonemainardi** [comment]
DB explorer already supports the search on CIDR subnets.

Due to the introduction of the new flows database nIndex, we won't be able to accomodate this request in the DB explorer. Such features are under development and will be available in the nIndex explorer.
