### ISSUE TITLE
Alerts show column selection with empty field

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5741]
Hi ntop team
On the alerts page, the "show column" selection has an empty field:
<img width="2114" alt="Screenshot 2021-08-06 at 17 44 14" src="https://user-images.githubusercontent.com/38549755/128536912-8e6aa9ba-d0a6-47c8-894b-f08ae3eb2296.png">
thanks, Martin

**Comment by simonemainardi** [comment]
![image](https://user-images.githubusercontent.com/3397663/129337890-9d6f4fb5-9fa8-4bad-9c4a-b872f36cf408.png)
