### ISSUE TITLE
Local vs. Remote alert filter

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5742]
Hi ntop team
First the new GUI of the alerts page is awesome, thank you!

I would like to request additional filters for filtering local only, local - remote, remote - local, remote only. Local I define in the config file with the -m parameter in the ntopng.conf.

Thanks, Martin

**Comment by simonemainardi** [comment]
Implemented with filters "Client Location" and "Server Location"

![image](https://user-images.githubusercontent.com/3397663/147363021-c1a6b0fb-4feb-436c-a0a1-6dbb4ae02f2a.png)
