### ISSUE TITLE
Hardcoded Flow Risks ?

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5743]
![Screen Shot 2021-08-07 at 19 48 10](https://user-images.githubusercontent.com/4493366/128609512-addf5625-4c85-482e-a100-6f3394cd1def.png)

This is this pcap https://github.com/ntop/nDPI/blob/dev/tests/pcap/tls_alert.pcap and only one flow risk is reported although nDPi reports two. This makes me think that flow risks are hardcoded and this is not what I would expect as nDPI can add new risks independently of ntopng.

**Comment by cardigliano** [comment]
ntopng reports both issues on my installation, which are the same reported by ndpiReader. Was it linking an older ndpi library perhaps?

Risk stats [found 1 (100.0 %) flows with risks]:
	Obsolete TLS version (< 1.1)                 1 [50.0 %]
	TLS fatal alert                              1 [50.0 %]

<img width="1090" alt="Screen Shot 2021-08-09 at 11 54 15" src="https://user-images.githubusercontent.com/7548711/128689039-884218ba-f627-4d4f-9ff0-cfaf0e3a3a7f.png">

**Comment by lucaderi** [comment]
Why score is not accounted id nDPI reports you the score?

**Comment by cardigliano** [comment]
Score is not accounted for risks which are not fully supported by ntopng (when a specific Check / handler for the risk is not present)

**Comment by lucaderi** [comment]
This is a problem that needs to be fixed.

**Comment by lucaderi** [comment]
Verified as fixed
