### ISSUE TITLE
Flow Swap Does not seem to work the same way for all flows

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5745]
I would have expected to see these flows from XXX -> 8080, for all of them. Instead, this is not the case. Not sure this is the correct behaviour. Below you can find some screenshots (note that one one direction of traffic is monitored)

![image](https://user-images.githubusercontent.com/4493366/128628918-9071701c-27be-43ab-b342-6162e53590ce.png)

![image](https://user-images.githubusercontent.com/4493366/128628931-9e8e8196-736e-40e0-9694-169b841966f5.png)

![image](https://user-images.githubusercontent.com/4493366/128628943-df9fdd61-65b0-45b4-be6d-aa96f87b1b31.png)

**Comment by simonemainardi** [comment]
As you've commented when discussing the implementation of the 'swap', no assumption on the direction can be made when only a direction of the traffic is seen.

So when only one direction of a _swap-candidate_ flow is seen, nothing is swapped. The swap takes place only when (and if) a packet in the opposite direction is seen.

For example, for the flow 8080<->53774 highlighted above, no swap is done as only 8080-to-53774 packets are seen.

---

For TCP flows, also the TCP flags are used, but the only ACK flag seen above, doesn't suffice alone to reliably determine the flow direction.

**Comment by simonemainardi** [comment]
Anyway, in the referenced commit I have relaxed a bit the condition used to decide on the swap, to also keep into account non-well-known-ports > 1024. This should cover the 8080 http-alt as well.

**Comment by lucaderi** [comment]
Cannot reproduce it as I am unable to connect to the system where the problem was reported. Closing the ticket for now hoping it works as expected.
