### ISSUE TITLE
Too much data submitted with the form

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5746]
The following alarm messages have been found on the ntopng console on an installation that was not in use.

09/Aug/2021 14:51:59 [LuaEngine.cpp:928] WARNING Too much data submitted with the form. [data len: 260908][max len: 131072]
09/Aug/2021 14:49:18 [LuaEngine.cpp:928] WARNING Too much data submitted with the form. [data len: 261247][max len: 131072]
09/Aug/2021 14:46:21 [LuaEngine.cpp:928] WARNING Too much data submitted with the form. [data len: 848104][max len: 131072]
09/Aug/2021 14:45:33 [LuaEngine.cpp:928] WARNING Too much data submitted with the form. [data len: 848091][max len: 131072]
09/Aug/2021 00:00:37 [housekeeping.lua:33] [lists_utils.lua:717] Category Lists (2213 hosts, 2978 IPs, 100 JA3) loaded in 1 sec
09/Aug/2021 00:00:36 [housekeeping.lua:33] [lists_utils.lua:420] Updating list 'Snort IP Block List' [https://snort.org/downloads/ip-block-list]... OK

**Comment by simonemainardi** [comment]
I have seen this error in the past an it should've been already resolved. Do you have the version?

**Comment by lucaderi** [comment]
What is the commit that fixes it? Please reference it in this ticket.
It was updated to 08.08.21 due to #5747

**Comment by simonemainardi** [comment]
This commit adds URI information that can help in troubeshooting in case it will appear again: 1f43ed6a6b126912a8e159878a34f5d4c810c5f0

Please, reopen with the new trace with the URI in case it will occur again.
