### ISSUE TITLE
[Regression] Automatic and manual updates are broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5747]
This problem can be reproduced on 194...

![Screen Shot 2021-08-09 at 15 14 55](https://user-images.githubusercontent.com/4493366/128712132-eade4530-d31e-48f6-a805-4381f0b91330.png)

Manually everything seems to work

root@ntop2:/# apt-get install ntopng
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
I seguenti pacchetti aggiuntivi saranno inoltre installati:
  ndpi nprobe ntopng-data pfring pfring-dkms
Pacchetti raccomandati:
  pfring-dkms
I seguenti pacchetti saranno aggiornati:
  ndpi nprobe ntopng ntopng-data pfring pfring-dkms
6 aggiornati, 0 installati, 0 da rimuovere e 32 non aggiornati.
È necessario scaricare 48,2 MB di archivi.
Dopo quest'operazione, verranno occupati 8.192 B di spazio su disco.
Continuare? [S/n] 

and

root@ntop2:/# /usr/bin/ntopng-utils-manage-updates -a check-updates-on-demand
root@ntop2:/# echo $?
0

**Comment by cardigliano** [comment]
I tried to reproduce this on the same box but it's working now.. I will keep an eye on that, please let me know if it happens again (before running a manual update)

<img width="1055" alt="Screen Shot 2021-08-09 at 16 06 52" src="https://user-images.githubusercontent.com/7548711/128721012-fa3d9c35-6cd1-48a6-9607-c89775eb6d7d.png">
<img width="1065" alt="Screen Shot 2021-08-09 at 16 15 27" src="https://user-images.githubusercontent.com/7548711/128721003-e099b45f-4bd4-4b55-941a-ee429076a537.png">

**Comment by lucaderi** [comment]
This problem is pending since many months unfortunately.

**Comment by lucaderi** [comment]
Even today broken on 194...

**Comment by cardigliano** [comment]
Please note that the system is already up to date, this looks like a repo issue which has the yesterday's packages

<img width="897" alt="Screen Shot 2021-08-10 at 09 35 36" src="https://user-images.githubusercontent.com/7548711/128827206-bf3e9aad-d8b0-4b84-aafb-a5fe0eb75572.png">
<img width="487" alt="Screen Shot 2021-08-10 at 09 35 42" src="https://user-images.githubusercontent.com/7548711/128827223-195146c9-231e-4914-a353-1fe5701402a7.png">

**Comment by cardigliano** [comment]
It seems ntopng was (correctly) not detecting an update when the revision was unchanged, even with a new version date, however this creates headaches thus we decided to add the date to the check. Fixed in 58a74d3b0c6fe3af97f7e8c24c09c5fd9ebbbbe2

**Comment by lucaderi** [comment]
Hope it works. Closing for now will reopen if necessary
