### ISSUE TITLE
Service Map Colors are not Correct

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5749]
![image](https://user-images.githubusercontent.com/4493366/128724062-34250a85-62f5-4529-8df2-d01c440c5c37.png)

**Comment by lucaderi** [comment]
Verified as fixed

**Comment by lucaderi** [comment]
![image](https://user-images.githubusercontent.com/4493366/129217504-06db837a-6748-45a5-8dee-08419457d839.png)
sorry still broken

**Comment by simonemainardi** [comment]
I believe this is a MAC

**Comment by lucaderi** [comment]
Verified as fixed
