### ISSUE TITLE
Add Visualisation Preference for L7 Protocols

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#575]
In pages like /lua/host_details.lua?ifname=4&host=192.168.9.88&page=ndpi all protocols are displayed and thus the use might be confused for protocols received but not sent. Example an Internet host receives a lot of probing packets for protocols it does not have (e.g. probing on the telnet port) so we display tenth of protocols unnecessary.

it would be desirable to add the ability to hide (as a preference) these application protocols

**Comment by emanuele-f** [comment]
Implemented in # f420dd6
