### ISSUE TITLE
How to create a lot of host pool

### ISSUE THREAD

**Issue by thomasbruchet** [ntop/ntopng#5755]
Hello;

I've just added the **144** networks of my company into the ntopng.conf with the -m=
OK, they appears into "Hosts>Networks" of the interface.
But I can not use that to filter the "Active Flows" view, the only option is to filter with "Hosts pool" so I want to create as many "host pools" as there are networks.

But the only way to do that is a non friendly way to do it
I've to: 
> Go on the manage_pools interface
> Click on + to create a new "Host Pool"
> Give a name and click on add
> Edit the new host pool
> Click on Edit Members
> Click on + to  Add Host Pool Member 
> Add the network that I want
> Return to the Host pool Interface
> Edit the "Host Pool"
> Add the special "Recipients" that I need

I will have to do that for all the 149 Host Pool that I need. 
This really, really a hard and long work, so is it possible to make this process easier ?
I've tried to look in the json that we get when we go into "Manage Configurations" to make a backup of Pools (includes SNMP, active monitoring, checks, endpoints and recipients) but there are a ton of items in and this is not easy to handle.

Is exist a database that I can work with to edit those information without have to handle all the menu ?

**Comment by simonemainardi** [comment]
You can use the REST API , endpoint `rest/v2/add/host/pool.lua`.

Example, to create pool named `maina` with member networks `192.168.2.0/24` and `192.168.3.0/24` without VLAN, you can do:

```
simone@devel:~$ curl -u "admin:admin1"   -H "Content-Type: application/json" -d '{"pool_name":"maina","pool_members":"192.168.2.0/24@0,192.168.3.0/24@0","recipients":"0"}'  "http://localhost:3000/lua/rest/v2/add/host/pool.lua"
{"rsp":{"pool_id":1},"rc":0,"rc_str_hr":"Pool added successfully","rc_str":"POOL_ADDED_SUCCESSFULLY"}
```

Documentation at https://www.ntop.org/guides/ntopng/api/rest/api_v2.html

**Comment by simonemainardi** [comment]
You can check for other examples at https://www.ntop.org/guides/ntopng/api/rest/examples_v2.html

Let me know if it helps.

**Comment by thomasbruchet** [comment]
Thank you. 
That work perfectly with all those example. (I've to debug why the HTTPS return an error but that is with curl not with ntopng)

**Comment by simonemainardi** [comment]
Thanks for reporting. And not that you don't necessarily have to have a 1:1 mapping between host pools and local networks. You can merge multiple local networks into one host pool, for example.
