### ISSUE TITLE
Score.rrd Failing /var/lib/ntopng/2/rrd/score.rrd: expected 2 data source readings (got 1)

### ISSUE THREAD

**Issue by bboymega** [ntop/ntopng#5757]
12/Aug/2021 21:55:07 [timeseries.lua:14] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/2/rrd/score.rrd][1628776506:8666] failed [/var/lib/ntopng/2/rrd/score.rrd: expected 2 data source readings (got 1) from 1628776506]

v.4.2.210810	[Enterprise/Professional build]
GIT rev:	4.2-stable:025e96e6cbb61e0f7320acf1d4038fafbbf836fa:20210810
Pro rev:	r3350
Built on:	Ubuntu 20.04.2 LTS
Platform:	x86_64
Edition:	Enterprise M

**Comment by simonemainardi** [comment]
This is fixed in the lastest dev and in the new 5.0 stable release which we are releasing. Please, hold on a couple of days, update, and it will work.
