### ISSUE TITLE
ntopng crashes when launched with --shutdown-when-done flag

### ISSUE THREAD

**Issue by lestat80** [ntop/ntopng#5761]
**Defect**

If I run ntopng with flag `--shutdown-when-done`, or stopping ntopng with `ctrl+c`, makes ntopng to crash

**Version of ntopng:**
ntopng-4.2.210811-11638

**OS environment:**
CentOS Linux release 7.9.2009 (Core)

**Steps to reproduce the issue**

- launch ntopng as follows
  `ntopng -v 2 -u root --dont-change-user --shutdown-when-done -i <(echo) -r "127.0.0.1" --http-port 31826`

**Expected result:**
I expect that the command exits successfully, as it was with `ntopng-4.2.201118-11562`

**Actual result:**
ntopng crashes with the following output:

> [root@5ad8882d56c7 ~]# ntopng -v 2 -u root --dont-change-user --shutdown-when-done -i <(echo) -r "redis.neteyelocal" --http-port 31826
13/Aug/2021 12:19:22 [Prefs.cpp:1134] ntopng will use redis redis.neteyelocal@0
13/Aug/2021 12:19:22 [Ntop.cpp:2347] Setting local networks to 127.0.0.0/8,fe80::/10
13/Aug/2021 12:19:22 [Redis.cpp:157] Successfully connected to redis redis.neteyelocal:6379@0
13/Aug/2021 12:19:22 [Redis.cpp:157] Successfully connected to redis redis.neteyelocal:6379@0
13/Aug/2021 12:19:22 [NtopPro.cpp:312] [LICENSE] Reading license from Redis
13/Aug/2021 12:19:22 [NtopPro.cpp:456] [LICENSE] Unable to validate license [Empty license file]
13/Aug/2021 12:19:22 [NtopPro.cpp:525] WARNING: [LICENSE] Invalid license [Empty license file]
13/Aug/2021 12:19:22 [NtopPro.cpp:542] WARNING: [LICENSE] ntopng will now run in Enterprise L edition for 10 minutes
13/Aug/2021 12:19:22 [NtopPro.cpp:544] WARNING: [LICENSE] before returning to community mode
13/Aug/2021 12:19:22 [NtopPro.cpp:546] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
13/Aug/2021 12:19:22 [NtopPro.cpp:548] WARNING: [LICENSE] or run ntopng in community mode starting
13/Aug/2021 12:19:22 [NtopPro.cpp:549] WARNING: [LICENSE] ntopng --community
13/Aug/2021 12:19:22 [boot.lua:31] [delete_data_utils.lua:425] Deleting data [delete_if_ids][OK]
13/Aug/2021 12:19:22 [boot.lua:31] [delete_data_utils.lua:425] Deleting data [delete_if_db][OK]
13/Aug/2021 12:19:22 [boot.lua:31] [delete_data_utils.lua:425] Deleting data [delete_if_redis_keys][OK]
13/Aug/2021 12:19:22 [boot.lua:31] [delete_data_utils.lua:425] Deleting data [delete_if_data][OK]
13/Aug/2021 12:19:22 [Ntop.cpp:2452] Registered interface /dev/fd/63 [id: 0]
13/Aug/2021 12:19:22 [main.cpp:312] PID stored in file /var/run/ntopng.pid
13/Aug/2021 12:19:22 [Geolocation.cpp:140] Loaded database dbip-asn-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip-asn-lite.mmdb][ip_version: 6]
13/Aug/2021 12:19:22 [Geolocation.cpp:140] Loaded database dbip-country-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip-country-lite.mmdb][ip_version: 6]
13/Aug/2021 12:19:22 [Geolocation.cpp:91] Using geolocation provided by DB-IP (https://db-ip.com)
13/Aug/2021 12:19:23 [HTTPserver.cpp:1554] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
13/Aug/2021 12:19:23 [HTTPserver.cpp:1557] HTTP server listening on 31826
13/Aug/2021 12:19:23 [NetworkInterface.cpp:2607] Started flow user script hooks loop on interface /dev/fd/63 [id: 0]...
13/Aug/2021 12:19:23 [main.cpp:382] Working directory: /var/lib/ntopng
13/Aug/2021 12:19:23 [main.cpp:384] Scripts/HTML pages directory: /usr/share/ntopng
13/Aug/2021 12:19:23 [Ntop.cpp:440] Welcome to ntopng x86_64 v.4.2.210811 - (C) 1998-20 ntop.org
13/Aug/2021 12:19:23 [NtopPro.cpp:733] [LICENSE] System Id:	LBE140605920BAB22--UBE140605CDFF64DD--OL
13/Aug/2021 12:19:23 [NtopPro.cpp:734] [LICENSE] Edition:	Enterprise L (Bundle)
13/Aug/2021 12:19:23 [NtopPro.cpp:735] [LICENSE] License Type:	Time-Limited [Empty license file] License
13/Aug/2021 12:19:23 [NtopPro.cpp:755] [LICENSE] Validity:	Until Fri Aug 13 12:29:22 2021
13/Aug/2021 12:19:23 [PeriodicActivities.cpp:107] Started periodic activities loop...
13/Aug/2021 12:19:23 [startup.lua:50] Processing startup.lua: please hold on...
13/Aug/2021 12:19:24 [startup.lua:144] [lists_utils.lua:758] Refreshing category lists...
13/Aug/2021 12:19:24 [startup.lua:144] [lists_utils.lua:696] Category Lists (695 hosts, 3014 IPs, 100 JA3) loaded in 0 sec
13/Aug/2021 12:19:24 [startup.lua:151] [presets_utils.lua:54] WARNING: Unknown device protocol: Skype
13/Aug/2021 12:19:24 [startup.lua:203] Loading category lists...
13/Aug/2021 12:19:24 [startup.lua:205] Loading category lists done
13/Aug/2021 12:19:24 [startup.lua:214] Running /usr/share/ntopng/local/scripts/callbacks/system/startup.lua
13/Aug/2021 12:19:24 [startup.lua:218] Startup completed: ntopng is now operational
13/Aug/2021 12:19:24 [PeriodicActivities.cpp:168] Each periodic activity script will use 2 threads
13/Aug/2021 12:19:24 [NetworkInterface.cpp:2749] Started packet polling on interface /dev/fd/63 [id: 0]...
13/Aug/2021 12:19:25 [PcapInterface.cpp:226] No more pcap files to read
13/Aug/2021 12:19:25 [PcapInterface.cpp:336] Terminated packet polling for /dev/fd/63
13/Aug/2021 12:19:25 [NetworkInterface.cpp:2635] Flow dump thread completed for /dev/fd/63
13/Aug/2021 12:19:29 [Ntop.cpp:2551] Terminating periodic activities
13/Aug/2021 12:19:30 [Ntop.cpp:2557] Executing shutdown script
13/Aug/2021 12:19:31 [ProtoStats.cpp:35] [IPv4]  0 B/0.00 Packets
13/Aug/2021 12:19:31 [ProtoStats.cpp:35] [IPv6]  0 B/0.00 Packets
13/Aug/2021 12:19:31 [ProtoStats.cpp:35] [ARP]   0 B/0.00 Packets
13/Aug/2021 12:19:31 [ProtoStats.cpp:35] [MPLS]  0 B/0.00 Packets
13/Aug/2021 12:19:31 [ProtoStats.cpp:35] [Other] 0 B/0.00 Packets
13/Aug/2021 12:19:31 [Ntop.cpp:2539] Polling shut down [interface: /dev/fd/63]
13/Aug/2021 12:19:32 [HTTPserver.cpp:1580] HTTP server terminated
*** Error in `ntopng': free(): invalid size: 0x00007fffcd964e70 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81329)[0x7fc483f18329]
ntopng[0x52aec4]
ntopng[0x52af33]
ntopng[0x52bb60]
ntopng[0x52c507]
ntopng[0x4601f3]
ntopng[0x4ae178]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fc483eb9555]
ntopng[0x41089f]

**Comment by cardigliano** [comment]
@lestat80 could you check if you are able to reproduce the same with the latest dev version (4.3) please? (note we are going to release a new stable this month)

**Comment by lestat80** [comment]
@cardigliano I tried with version 4.3.210813-14676 and I cannot reproduce it

**Comment by cardigliano** [comment]
I assume it has been fixed in the latest dev, a new stable will be released in a few days based on the current dev, thus we can consider this as fixed.

**Comment by simonemainardi** [comment]
Confirm, fixed as of 5.0 stable and 5.1.
