### ISSUE TITLE
ntopng keeps restarting, after being killed  by bus signal 

### ISSUE THREAD

**Issue by hvanthoor** [ntop/ntopng#5762]
Version:        4.3.210808 [Enterprise/Professional/Embedded build]
Pro rev:        r4131
Built on:       Raspbian GNU/Linux 10 (buster)

root@ntopng:/var/log# systemctl status ntopng
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: signal) since Fri 2021-08-13 14:21:08 IST; 615ms ago
  Process: 2307 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-m
  Process: 2321 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/S
  Process: 2323 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null ||
  Process: 2325 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntop
  Process: 2327 ExecStart=/usr/bin/ntopng /run/ntopng.conf (code=killed, signal=BUS)
  Process: 2470 ExecStopPost=/bin/rm -rf /run/ntopng.conf /run/ntopng.conf.raw /run/ntopng.pid (code=exited, status=0/SU
 Main PID: 2327 (code=killed, signal=BUS)

ntopng.conf:

-W=3001
-i=eth0
-m=192.168.0.0/24,192.168.10.0/24,192.168.100.0/24,192.168.50.0/24,192.168.60.0/24
-n=1
-F mysql;localhost;ntopng;flows;######;#######

**Comment by simonemainardi** [comment]
Pleease, explain how you've installed ntopng and how you are running it. (e.g.,  how you're controlling the start/stop)

BTW, are you on a dockerized environment?

**Comment by hvanthoor** [comment]
Installed via regular installation instructions (packages.ntopng.org) , not running in Docker or any other container,  use systemctl to start/stop

 Thank you

**Comment by simonemainardi** [comment]
Comment out the -F configuration line and report

**Comment by hvanthoor** [comment]
Thank you
I tried that earlier and just now again
No effect, unfortunately.

**Comment by simonemainardi** [comment]
Can you try and remove also the other parameters, one by one, to see if a specific parameter is causing the crash?

**Comment by hvanthoor** [comment]
Thank you, but even with everything disabled, the issue remains

**Comment by simonemainardi** [comment]
tried to reproduce on my pi but there's no issue

```
mainardi@pi3:~$ cat /etc/ntopng.conf
cat: /etc/ntopng.conf: File o directory non esistente
mainardi@pi3:~$ cat /etc/ntopng/ntopng.conf
-W=3001
-i=eth0
-m=192.168.0.0/24,192.168.10.0/24,192.168.100.0/24,192.168.50.0/24,192.168.60.0/24
-n=1
#-F mysql;localhost;ntopng;flows;######;#######
mainardi@pi3:~$ sudo /usr/local/bin/ntopng /etc/ntopng/ntopng.conf
13/Aug/2021 17:14:49 [Ntop.cpp:2493] Setting local networks to 192.168.0.0/24,192.168.10.0/24,192.168.100.0/24,192.168.50.0/24,192.168.60.0/24
13/Aug/2021 17:14:49 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
13/Aug/2021 17:14:49 [Redis.cpp:157] Successfully connected to redis 127.0.0.1:6379@0
13/Aug/2021 17:14:49 [NtopPro.cpp:324] [LICENSE] Reading license from /etc/ntopng.license
13/Aug/2021 17:14:49 [NtopPro.cpp:472] [LICENSE] /etc/ntopng.license: found valid Professional Embedded license
13/Aug/2021 17:14:51 [PcapInterface.cpp:93] Reading packets from eth0 [id: 1]
13/Aug/2021 17:14:51 [Ntop.cpp:2601] Registered interface eth0 [id: 1]
13/Aug/2021 17:14:51 [main.cpp:331] PID stored in file /var/run/ntopng.pid
13/Aug/2021 17:14:51 [Geolocation.cpp:149] Loaded database GeoLite2-ASN.mmdb [/var/lib/GeoIP/GeoLite2-ASN.mmdb][ip_version: 6]
13/Aug/2021 17:14:51 [Geolocation.cpp:149] Loaded database GeoLite2-City.mmdb [/var/lib/GeoIP/GeoLite2-City.mmdb][ip_version: 6]
13/Aug/2021 17:14:51 [Geolocation.cpp:64] Using geolocation provided by MaxMind (https://maxmind.com)
13/Aug/2021 17:14:52 [HTTPserver.cpp:1691] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
13/Aug/2021 17:14:52 [HTTPserver.cpp:1694] HTTP server listening on 3000
13/Aug/2021 17:14:52 [HTTPserver.cpp:1700] HTTPS server listening on 3001
13/Aug/2021 17:14:52 [Utils.cpp:781] User changed to ntopng
13/Aug/2021 17:14:52 [NetworkInterface.cpp:2762] Started flow user script hooks loop on interface eth0 [id: 1]...
13/Aug/2021 17:14:52 [NetworkInterface.cpp:2793] Started host user script hooks loop on interface eth0 [id: 1]...
13/Aug/2021 17:14:52 [main.cpp:401] Working directory: /var/lib/ntopng
13/Aug/2021 17:14:52 [main.cpp:403] Scripts/HTML pages directory: /usr/share/ntopng
13/Aug/2021 17:14:52 [Ntop.cpp:479] Welcome to ntopng armv7l v.4.3.210808 - (C) 1998-21 ntop.org
13/Aug/2021 17:14:52 [Ntop.cpp:489] Built on Raspbian GNU/Linux 10 (buster)
13/Aug/2021 17:14:52 [NtopPro.cpp:763] [LICENSE] System Id:	LFD504ACA499602D2--OL
13/Aug/2021 17:14:52 [NtopPro.cpp:764] [LICENSE] Edition:	Professional Embedded
13/Aug/2021 17:14:52 [NtopPro.cpp:765] [LICENSE] License Type:	Permanent License
13/Aug/2021 17:14:52 [NtopPro.cpp:774] [LICENSE] License:	SYzu7fA0nUKUJJbAB4D8cts8NXhOqJ+X7dTaCDCwn2I13rOFDxYp6I1vxsvNm1fCsC8bg
13/Aug/2021 17:14:52 [NtopPro.cpp:775] [LICENSE]         	yyi6iVSwjDsXDiSk5VHyNSDf2wrsHSr+pS1Vl1lb1SkWDNAXJ0bACadQKt3wilQAAZRG1
13/Aug/2021 17:14:52 [NtopPro.cpp:775] [LICENSE]         	H+Ob9VDNguYaa/1qFY+ZAt7I9rPLsKZHst/EJca2Fav6IaXwpjVK3y1UIDfvwaOXYMmca
13/Aug/2021 17:14:52 [NtopPro.cpp:775] [LICENSE]         	r6JUY0j1RnFV1KO/JfLQVSBoUCMRMS0FpwRprTRtkEZkvD+/Uhj4drIeJ9QOFe3PNrWlU
13/Aug/2021 17:14:52 [NtopPro.cpp:775] [LICENSE]         	PcLzss2xnpwr5Gb5U1eW+d7HL73yiZlnBN6PJDcxfszq6RN02L2QV0iEZl1Mr2NCWg==
13/Aug/2021 17:14:52 [NtopPro.cpp:779] [LICENSE] License Hash:	0BCAD47898B3669579C15E6A4BB610B01659086888DD0D5D89
13/Aug/2021 17:14:52 [NtopPro.cpp:790] [LICENSE] Maintenance:	Until Fri Jul 29 11:28:08 2022 [349 days left]
13/Aug/2021 17:14:52 [Ntop.cpp:914] Adding 192.168.2.153/32 as IPv4 interface address for eth0
13/Aug/2021 17:14:52 [Ntop.cpp:923] Adding 192.168.2.0/24 as IPv4 local network for eth0
13/Aug/2021 17:14:52 [PeriodicActivities.cpp:107] Started periodic activities loop...
```

Can you try and isssue a `redis-cli flushall` (if you can afford losing the configuration)

**Comment by hvanthoor** [comment]
Thank you.
I just tried that without avail unfortunately.

**Comment by simonemainardi** [comment]
Unfortunately, we can't do anything on that packages are we are not the maintainers. However, we maintain our official packages. See the link above. I would like to suggest you to use them to also get newest features.

**Comment by lucaderi** [comment]
The crash should be fixed with https://github.com/ntop/nDPI/commit/677b513f70ade895ef28be744245803238100489

**Comment by hvanthoor** [comment]
I can confim all is working now thanks to the fix.
