### ISSUE TITLE
Plugins page error when there are no plugins

### ISSUE THREAD

**Issue by nobless** [ntop/ntopng#5765]
> HTTP/1.1 302 Found Set-Cookie: session=****************************; path=/; HttpOnly; SameSite=lax Location: /lua/http_status_code.lua?message=internal_error&referer=192.168.1.1%3A3000%2Flua%2Fplugins_overview.lua&error_message=%2Fusr%2Flocal%2Fshare%2Fntopng%2Fscripts%2Flua%2Fmodules%2Fntop_utils.lua%3A199%3A%20bad%20argument%20%231%20to%20%27for%20iterator%27%20%28table%20expected%2C%20got%20nil%29 /usr/local/share/ntopng/scripts/lua/modules/ntop_utils.lua:199: bad argument #1 to 'for iterator' (table expected, got nil)

Installed as aPFSENSE package:

ntopng | net | 0.8.13_10 |
Dependencies:  webfonts-0.30_14    ntopng-4.2.d20210615,1    libmaxminddb-1.6.0    graphviz-2.44.1_13    redis-6.0.15    gdbm-1.20

**Comment by nobless** [comment]
14/Aug/2021 17:18:23 [LuaEngine.cpp:926] WARNING Script failure [/usr/local/share/ntopng/scripts/lua/plugins_overview.lua][/usr/local/share/ntopng/scripts/lua/modules/ntop_utils.lua:199: bad argument #1 to 'for iterator' (table expected, got nil)]
14/Aug/2021 17:18:23 [plugins_overview.lua:99] [plugins_utils.lua:813] ERROR Could not load plugins metadata file 'plugins_metadata'

**Comment by simonemainardi** [comment]
We are not the maintainer of the installed package. Please install following official instructions at https://packages.ntop.org/FreeBSD/ or follow up with the maintainers.
