### ISSUE TITLE
Update popup and version missmatch?

### ISSUE THREAD

**Issue by nobless** [ntop/ntopng#5766]
- Always showing popup in the corner about the available update, every refreshed page, no setting to disable it?

> A new ntopng stable version (v.4.2.0) is available for download: please upgrade.

- Don't know if this should be addressed in this repository or directly to PFSense but noting this too:
In the bottom of the corner it shows as installed:
----------
> ntopng Community v.3.4.0 

While the package is ntopng-4.2.d20210615,1

Maybe version identify mechanism could be improved also for plugins?

----------
----------
Installed as aPFSENSE package:

ntopng | net | 0.8.13_10 |
Dependencies:  webfonts-0.30_14    ntopng-4.2.d20210615,1    libmaxminddb-1.6.0    graphviz-2.44.1_13    redis-6.0.15    gdbm-1.20

**Comment by simonemainardi** [comment]
We are not the maintainer of the installed package. Please install following official instructions at https://packages.ntop.org/FreeBSD/ or follow up with the maintainers.

**Comment by nobless** [comment]
Thanks, uploaded this bug to the maintener redmine:
https://redmine.pfsense.org/issues/12260

**Comment by simonemainardi** [comment]
Ok. Thanks. May I also suggest you to consider using our packages to have the latest features.
