### ISSUE TITLE
ntopng - Harmonize Table Header and Data alignment

### ISSUE THREAD

**Issue by Kike-F** [ntop/ntopng#5774]
Some table views in ntopng have different Header alignment than the Data under that table. 
So far I have detected this in two pages:
1.- Host details: in the Apps, Traffic and DNS tabs
2.- Interface: in the Apps tab

This is more a cosmetic issue than a bug but, in some cases, this formatting is misleading and makes information difficult to read.

**Comment by MatteoBiscosi** [comment]
Hi @Kike-F , thanks for the suggestion i missed those and i didn't see that they had different alignments, now they should be fixed, please re-open this ticket if you see other table with misleading alignment
