### ISSUE TITLE
ntopng edge - does not work after replacing/adding the new network card

### ISSUE THREAD

**Issue by algebur** [ntop/ntopng#5775]
Temporary for the test I had installed the ntopng edge on the pc with 1 internal ethernet card and 1 external USB/ethernet card, because the ntopng edge requires minimum 2 network interfaces for work. That system worked fine. Then I installed Intel NIC PCI-Ex with 2 ethernet ports, changed the network settings, the OS is working (network/internet), but the ntopng edge is not working. The problem is that the ntopng edge still sees the old network interfaces 

Ubuntu 18.04.05 LTS
nedge version - v.4.2.210811

my netplan configuration file /etc/netplan/01-netcfg.yaml

##################################

network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0f0:
      dhcp4: no
    enp1s0f1:
      dhcp4: no
  bridges:
    br0:
      dhcp4: yes
      interfaces: [enp1s0f0,enp1s0f1]

##################################

the ntopng edge had created in beginning the similar netplan file and disabled the original, I have changed the both.

Here is what I see in syslog:

##################################

Cannot find device "enxe8fcafc7a8e1"
nedge[8466]: message repeated 10 times: [ Cannot find device "enxe8fcafc7a8e1"]
nedge[8466]: 18/Aug/2021 09:40:32 [NetfilterInterface.cpp:678] Succesfully connected to NF_QUEUE 1
nedge[8466]: 18/Aug/2021 09:40:32 [NetfilterInterface.cpp:700] WARNING: Disabling user change as otherwise netfilter won't work
nedge: [NetfilterInterface.cpp:700] WARNING: Disabling user change as otherwise netfilter won't work
nedge: [NetworkDiscovery.cpp:52] ERROR: Unable to create pcap socket on enp2s0 [95/Operation not supported]
nedge[8466]: 18/Aug/2021 09:40:32 [NetworkDiscovery.cpp:52] ERROR: Unable to create pcap socket on enp2s0 [95/Operation not supported]
nedge[8466]: 18/Aug/2021 09:40:32 [Ntop.cpp:2452] Registered interface nf:1 [id: 6]
nedge[8466]: 18/Aug/2021 09:40:32 [main.cpp:312] PID stored in file /var/run/ntopng.pid

##################################

the enxe8fcafc7a8e1 was my USB/ethernet NIC - it is unplugged now from the USB

the enp2s0 is the internal NIC (on the motherboard)

the enp1s0f0 and enp1s0f1 are 2 interfaces on the new Intel NIC PCI-Ex

The ntopng edge GUI (via web) in system settings shows me the old interfaces for LAN and WAN: enxe8fcafc7a8e1 and enp2s0

I even reinstalled the ntopng edge - still not working, same problem
I do not see any way to adjust the file /etc/ntopng/ntopng.conf - there is no network settings.
I have not installed any license yet. This is 10 minutes demo work

How to change completely the Network settings? Where the ntopng edge stored it?

**Comment by simonemainardi** [comment]
When changing the interfaces, it is recommended to start clean.

Note that nEdge system configuration is stored under (`/var/lib/ntopng/system.config`) - netplan is only changed upon nEdge system setup changes.

So basically:

- uninstall nEdge
- `redis-cli flushall` to clean settings
- `/var/lib/ntopng/` to clean data
- restart the system
- reinstall nEdge and redo the first setup procedure

**Comment by simonemainardi** [comment]
Feedback given. Reopen if necessary after having attempted the suggested solution.
