### ISSUE TITLE
Alert filter - can not change between = and !=

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5777]
Hi ntop team
When a alert filter is set, I can not change it from e.g. = to != (or the other way around)
I can select it, press apply, but is not taken over.
<img width="951" alt="Screenshot 2021-08-19 at 10 42 03" src="https://user-images.githubusercontent.com/38549755/130037781-be4c4975-d911-4efd-b661-ae8fcbb07712.png">
Thanks
Martin

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu, the issue should be fixed for both, dev and stable version, please when new builds are available update and let me know if everything works fine

**Comment by simonemainardi** [comment]
Confirm. Fixed.
