### ISSUE TITLE
Add Graph in Profiles

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#578]
In /lua/if_stats.lua?id=0&page=trafficprofiles add at the top of the page a stacked graph with all defined profiles

**Comment by simonemainardi** [comment]
the stacked graph has been made available in the "historical page" in a new entry "Top Profiles"

![image](https://cloud.githubusercontent.com/assets/3397663/21521904/3de11484-cd01-11e6-8270-4f50096672d0.png)
