### ISSUE TITLE
Automatic configuration backup

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5780]
Hi ntop Team
Would it be possible to have an automatic backup function when the automatic update is turned on?
(we lost Checks configuration with todays update :-) )
Thanks, Martin

**Comment by lucaderi** [comment]
Implement the ticket as follows
- add an automatic backup preference
- if enabled create a callback/daily that dumps the configuration in redis with a specific key containing the date
- if the current configuration is the same as the old configuration nothing should be saved
- add somewhere in the GUI a page that allows you to download the past configurations that you can use to restore them
- make sure that no more that X configurations are saved

**Comment by NicoMaio** [comment]
To restore the last configurations backup: what about a new "Restore Last Backup" button on the Manage Configurations page?

**Comment by MatteoBiscosi** [comment]
Implemented as requested
