### ISSUE TITLE
Map layout is not saved as it should

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5781]
Service/Periodicity maps layouts are saved persistently to avoid re-wiring. Unfortunately, when selecting a filter a new map is drawn that overwrites the current layout. This is a bug as the original layout is lost. A fix could be to dump the layout with a key that also contains the filter selection in order to avoid overwriting existing layouts.

This should be fixed both in stable and dev versions.

**Comment by MatteoBiscosi** [comment]
Verified as fixed, pro repo too.
