### ISSUE TITLE
license doesn't work

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#5783]
Our license says invalid:

![image](https://user-images.githubusercontent.com/48565067/130247707-d767b498-1d47-4ba4-a133-d19cdd63e599.png)

Who do we speak to?

**Comment by simonemainardi** [comment]
is it expired? you can check with

```
ntopng --version
```

If you send me the order id and systemid (please paste it as text) I can check. Send to mainardi at ntop dot org

**Comment by simonemainardi** [comment]
@StewAlexander-com any news?

**Comment by StewAlexander-com** [comment]
I sent an email to ```education@ntopng.com``` and I haven't heard anything back yet

```
support@ntopng ~> sudo ntopng --version
[sudo] password for support:
Sorry, try again.
[sudo] password for support:
Version:        5.1.210822 [Enterprise/Professional build]
GIT rev:        dev:52392fa7629dc1b9a9543bf45b2cae47ffdb4a35:20210822
Pro rev:        r4195
Built on:       Ubuntu 18.04.5 LTS
Platform:       x86_64
Edition:        Enterprise L (Bundle)
License Type:   Time-Limited [Unable to unlock this version (maintenance expired)]
Validity:       Until Mon Aug 23 09:29:59 2021

````

I'll send you the full text output via email, thank you

**Comment by StewAlexander-com** [comment]
I sent you the email (from **```ssalexander494@alamancecc.edu```**), thank you

**Comment by simonemainardi** [comment]
License has expired maintenance. Maintenance expired on 2021-04-03.

See the output you have sent me says maintenance expired, too.

<img width="720" alt="image" src="https://user-images.githubusercontent.com/3397663/130473453-3aa1fb5f-5a7c-48ee-a716-c316bde053a9.png">


Please, renew the maintenance https://www.ntop.org/support/faq/how-can-i-renew-maintenance-for-commercial-products/

**Comment by StewAlexander-com** [comment]
Hi Simone,

We are education, we got the previous one for free, is something we can
still do?

**Comment by simonemainardi** [comment]
if you think you qualify for EDU licenses, send an inquiry to mallegro at ntop dot org
