### ISSUE TITLE
GeoMap under Host Page Not working

### ISSUE THREAD

**Issue by bre75** [ntop/ntopng#5784]
Hello,

Sorry to open a new issue about a subject already talked in a previous and closed one (#3693 )

I had post the following comment [https://github.com/ntop/ntopng/issues/3693#issuecomment-856760504](url) as it's not working on my side.

Any idea ?

Thanks a lot for any help.

Regards,

**Comment by simonemainardi** [comment]
Are you using a packaged version installed at packages.ntop.org? Do you have package `ntopng-data` installed as well?

**Comment by bre75** [comment]
Yes. Community Edition

Yes it's installed : version 4.3.210629

I don't know if it's important. On the same Raspberry i have pi-hole installed.

**Comment by simonemainardi** [comment]
You may be running ntopng on a distro that is not supported (pi-hole).

Anyway, check ntopng logs. You should see something as these two lines if the geolocation database is loaded

![image](https://user-images.githubusercontent.com/3397663/130420989-4b33b348-a406-4076-b308-2e6489c8b38f.png)

Otherwise, ntopng will complain about not being able to find the geolocation database.

Please, check and post the logs here.

**Comment by bre75** [comment]
I'm feeling ashame to ask but .... Where are the ntopng logs ?

**Comment by bre75** [comment]
Here it is 

Aug 23 15:41:02 myserver ntopng[11823]: 23/Aug/2021 15:41:02 [Geolocation.cpp:149] Loaded database GeoLite2-ASN.mmdb [/usr/share/ntopng/httpdocs/geoip//GeoLite2-ASN.mmdb][ip_version: 6]
Aug 23 15:41:02 myserver ntopng[11823]: 23/Aug/2021 15:41:02 [Geolocation.cpp:149] Loaded database GeoLite2-City.mmdb [/usr/share/ntopng/httpdocs/geoip//GeoLite2-City.mmdb][ip_version: 6]
Aug 23 15:41:02 myserver ntopng[11823]: 23/Aug/2021 15:41:02 [Geolocation.cpp:64] Using geolocation provided by MaxMind (https://maxmind.com)

**Comment by bre75** [comment]
![ntopng-1](https://user-images.githubusercontent.com/20688640/130460497-a3389229-0531-452f-88c5-5f2f50f81080.png)

I notice something strange.
ntopng is displaying the "offline" plane icon. Even thought I'm really well online.

**Comment by simonemainardi** [comment]
Geolocation is correctly enabled.

However, you only have 4 hosts, out of which only 1 is remote. So my guess is that you don't have hosts with public IP addresses that can be geolocated. You can check if you visit Hosts->Countries.

As per the offline issue, we have resolved an issue that could cause it. Please, wait a couple of hours, the update, and it will work.

**Comment by bre75** [comment]
<img width="909" alt="ntopng-2" src="https://user-images.githubusercontent.com/20688640/130470769-2d2f5811-7af9-4e54-b28e-1ec28aa71282.png">

I have only one, which is Quad9 DNS.

Is it why I don't see flows ? Because all my requests are sent to Quad9 ?

Thx I'll update later !

**Comment by simonemainardi** [comment]
You are seeing partial traffic, it is unlikely that an host has only 3 hosts (see the top badge with number 3).

Geolocation is working as you can see: you have 1 host in the United States.

Are you running ntopng with a filter (-B) or something similar?

**Comment by bre75** [comment]
<img width="614" alt="ntopng-about" src="https://user-images.githubusercontent.com/20688640/130486217-2159d756-8444-4865-ba5a-004819d82fa7.png">

AFAIK I did nothing special about ntopng startup.

Maybe it needs to be point that I'm in France.
In France we're having "internet box" from our provider.
It's acting as DNS server except in my case i switch off this option to delegate it to Pi-Hole.

**Comment by simonemainardi** [comment]
Everything is normal:

- You have filter on port 53 (`--packet-filter "port 53"`), likely you want to capture only standard DNS traffic. 
- Geomap works, as you can see you have an US host detected

**Comment by bre75** [comment]
Is it "best practice" to filter on port 53 ?

Anyway thanks for all the support/answers you gave me !

**Comment by simonemainardi** [comment]
I would not filter on port 53 unless you have very special requirements. You will lose all the other traffic, including DNS that someone may run on a port different than 53.

So my suggestion is to remove the filter.

**Comment by bre75** [comment]
Thx a lot.

I followed your advice :)
