### ISSUE TITLE
broken SNMP topology map with no hostname shown next to the nodes

### ISSUE THREAD

**Issue by 612wong** [ntop/ntopng#5786]
Description of the issue
- got the new version 5.1.210820 (Enterprise M) running last night
- enabled SNMP device monitoring with devices running LLDP
- about 6 hours later, the SNMP topology map shows me many nodes interconnected but without hostnames
<img width="2559" alt="Screen Shot 2021-08-21 at 9 22 41 am" src="https://user-images.githubusercontent.com/58540705/130302428-4282fe26-c282-45b9-9b2c-1edaef25867a.png">

Please advise if you need more information for the troubleshooting!

Thanks in advance.

**Comment by simonemainardi** [comment]
I am unable to reproduce. Can you send me privately you Redis dump.rdb so I can re-create the very same conditions in my Lab? Make sure to stop ntopng and Redis services first


root@devel:/home/simone/ntopng/pro# systemctl stop ntopng redis-server

then, send me file  `/var/lib/redis/dump.rdb` to mainardi at ntop dot org

**Comment by simonemainardi** [comment]
Instructions to export the rdb file are at https://stackoverflow.com/a/22024286

**Comment by simonemainardi** [comment]
Thanks for kindly providing data.

I believe I have solved the issue. This is what it looks like your topology

![image](https://user-images.githubusercontent.com/3397663/130460238-a4a16f3d-3883-4cb8-92d8-9e7b3d04be0c.png)


A new build is in progress. Please, wait a couple of hours, update, and it will work.

**Comment by 612wong** [comment]
Thanks for your update on the issue.

**Comment by simonemainardi** [comment]
so can you confirm it is working as expected now?

**Comment by 612wong** [comment]
Have updated ntopng to ntopng Enterprise M v.5.1.210824 (CentOS Linux release 7.9.2009 (Core)).
It's still not reporting the hostname.
<img width="867" alt="Screen Shot 2021-08-24 at 11 41 37 pm" src="https://user-images.githubusercontent.com/58540705/130627287-b5710a1f-4fd5-427e-911d-bdd6d8b9c25f.png">

update log
`-bash-4.2$ sudo yum update ntopng
... skipped ...
Resolving Dependencies
--> Running transaction check
---> Package ntopng.x86_64 0:5.1.210823-14725 will be updated
---> Package ntopng.x86_64 0:5.1.210824-14733 will be an update
--> Processing Dependency: pfring = 8.1.0-6835 for package: ntopng-5.1.210824-14733.x86_64
--> Running transaction check
---> Package pfring.x86_64 0:8.1.0-6831 will be updated
--> Processing Dependency: pfring = 8.1.0-6831 for package: nprobe-9.7.210823-7436.x86_64
--> Processing Dependency: pfring = 8.1.0-6831 for package: cento-1.15.210823-696.x86_64
--> Processing Dependency: pfring = 8.1.0-6831 for package: n2disk-3.7.210823-5323.x86_64
---> Package pfring.x86_64 0:8.1.0-6835 will be an update
--> Running transaction check
---> Package cento.x86_64 0:1.15.210823-696 will be updated
---> Package cento.x86_64 0:1.15.210824-696 will be an update
---> Package n2disk.x86_64 0:3.7.210823-5323 will be updated
---> Package n2disk.x86_64 0:3.7.210824-5324 will be an update
---> Package nprobe.x86_64 0:9.7.210823-7436 will be updated
---> Package nprobe.x86_64 0:9.7.210824-7437 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

============================================================================================================================================================================================================================================================================================================================================================================
 Package                                                                                Arch                                                                                   Version                                                                                           Repository                                                                            Size
============================================================================================================================================================================================================================================================================================================================================================================
Updating:
 ntopng                                                                                 x86_64                                                                                 5.1.210824-14733                                                                                  ntop                                                                                 9.7 M
Updating for dependencies:
 cento                                                                                  x86_64                                                                                 1.15.210824-696                                                                                   ntop                                                                                 1.2 M
 n2disk                                                                                 x86_64                                                                                 3.7.210824-5324                                                                                   ntop                                                                                 1.2 M
 nprobe                                                                                 x86_64                                                                                 9.7.210824-7437                                                                                   ntop                                                                                 9.2 M
 pfring                                                                                 x86_64                                                                                 8.1.0-6835                                                                                        ntop                                                                                 2.4 M

Transaction Summary
============================================================================================================================================================================================================================================================================================================================================================================
Upgrade  1 Package (+4 Dependent packages)

Total download size: 24 M
Is this ok [y/d/N]: y
Downloading packages:
No Presto metadata available for ntop
(1/5): n2disk-3.7.210824-5324.x86_64.rpm                                                                                                                                                                                                                                                                                                             | 1.2 MB  00:00:03
(2/5): cento-1.15.210824-696.x86_64.rpm                                                                                                                                                                                                                                                                                                              | 1.2 MB  00:00:04
(3/5): ntopng-5.1.210824-14733.x86_64.rpm                                                                                                                                                                                                                                                                                                            | 9.7 MB  00:00:17
(4/5): nprobe-9.7.210824-7437.x86_64.rpm                                                                                                                                                                                                                                                                                                             | 9.2 MB  00:00:20
(5/5): pfring-8.1.0-6835.x86_64.rpm                                                                                                                                                                                                                                                                                                                  | 2.4 MB  00:00:05
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                                                                                                                                                                                       902 kB/s |  24 MB  00:00:26
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : pfring-8.1.0-6835.x86_64                                                                                                                                                                                                                                                                                                                                1/10
  Updating   : nprobe-9.7.210824-7437.x86_64                                                                                                                                                                                                                                                                                                                           2/10
  Updating   : ntopng-5.1.210824-14733.x86_64                                                                                                                                                                                                                                                                                                                          3/10
  Updating   : cento-1.15.210824-696.x86_64                                                                                                                                                                                                                                                                                                                            4/10
  Updating   : n2disk-3.7.210824-5324.x86_64                                                                                                                                                                                                                                                                                                                           5/10
  Cleanup    : n2disk-3.7.210823-5323.x86_64                                                                                                                                                                                                                                                                                                                           6/10
  Cleanup    : cento-1.15.210823-696.x86_64                                                                                                                                                                                                                                                                                                                            7/10
  Cleanup    : ntopng-5.1.210823-14725.x86_64                                                                                                                                                                                                                                                                                                                          8/10
  Cleanup    : nprobe-9.7.210823-7436.x86_64                                                                                                                                                                                                                                                                                                                           9/10
  Cleanup    : pfring-8.1.0-6831.x86_64                                                                                                                                                                                                                                                                                                                               10/10
  Verifying  : nprobe-9.7.210824-7437.x86_64                                                                                                                                                                                                                                                                                                                           1/10
  Verifying  : ntopng-5.1.210824-14733.x86_64                                                                                                                                                                                                                                                                                                                          2/10
  Verifying  : pfring-8.1.0-6835.x86_64                                                                                                                                                                                                                                                                                                                                3/10
  Verifying  : cento-1.15.210824-696.x86_64                                                                                                                                                                                                                                                                                                                            4/10
  Verifying  : n2disk-3.7.210824-5324.x86_64                                                                                                                                                                                                                                                                                                                           5/10
  Verifying  : n2disk-3.7.210823-5323.x86_64                                                                                                                                                                                                                                                                                                                           6/10
  Verifying  : nprobe-9.7.210823-7436.x86_64                                                                                                                                                                                                                                                                                                                           7/10
  Verifying  : ntopng-5.1.210823-14725.x86_64                                                                                                                                                                                                                                                                                                                          8/10
  Verifying  : pfring-8.1.0-6831.x86_64                                                                                                                                                                                                                                                                                                                                9/10
  Verifying  : cento-1.15.210823-696.x86_64                                                                                                                                                                                                                                                                                                                           10/10

Updated:
  ntopng.x86_64 0:5.1.210824-14733

Dependency Updated:
  cento.x86_64 0:1.15.210824-696                                                             n2disk.x86_64 0:3.7.210824-5324                                                             nprobe.x86_64 0:9.7.210824-7437                                                             pfring.x86_64 0:8.1.0-6835

Complete!
-bash-4.2$ sudo service ntopng restart
Redirecting to /bin/systemctl restart ntopng.service
-bash-4.2$`

**Comment by simonemainardi** [comment]
please, try and refresh browser and javascript caches. I have proper layout with names in my instance. Also tell me the browser you are using.

**Comment by 612wong** [comment]
Yes. The layer 1 layout is now working after clearing the browser caches (everything). Thank you.
