### ISSUE TITLE
Missing historical charts for retransmissions/OOO/lost

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#579]
The above chart is computed for packet interfaces (e.g -i eth0) but it is not populated via ZMQ. ntopng must interpret retransmissions/OOO/lost received via ZMQ and use them for creating charts

**Comment by emanuele-f** [comment]
Partially implemented in bc14efd. Lost packets require two new nProbe template entries, one for "in", one for "out".

**Comment by emanuele-f** [comment]
@lucaderi do you wish to add support for the lost packets or we can close the issue?

**Comment by simonemainardi** [comment]
support is satisfactory at the moment. thank you.
