### ISSUE TITLE
iface:traffic_rx_behavior_v2 is suspected to report accummulated value

### ISSUE THREAD

**Issue by 612wong** [ntop/ntopng#5792]
Hi there,

The MAC address based traffic direction is useful for me and I hope to graph it in Grafana where I have other dashboards for different part of the infrastructure. However, the influx data looks strange to me.

The following ntopng interface traffic graph showed a graph of 10-second average resolution.
<img width="1273" alt="Screen Shot 2021-08-23 at 11 19 25 pm" src="https://user-images.githubusercontent.com/58540705/130455545-c04f6dc0-dacf-4487-8aa7-0e15811f606c.png">

The following grafana interface traffic graph showed a graph of 1-min average resolution which looks like 5-min average.
<img width="1196" alt="Screen Shot 2021-08-23 at 11 25 38 pm" src="https://user-images.githubusercontent.com/58540705/130455623-ccb32773-af28-406a-86a4-23cae5fdcf52.png">

The following influx query showed the interface traffic was updated with the same value every 5 minutes.
<img width="651" alt="Screen Shot 2021-08-23 at 11 20 20 pm" src="https://user-images.githubusercontent.com/58540705/130455689-12a55441-ebf3-4300-b749-dac731f227ad.png">

I wonder if the issue is within the ntopng.

**Comment by MatteoBiscosi** [comment]
Hi @612wong, sorry but I don't seem to understand what you mean. The traffic TX/RX graph is the graph showing the traffic of the interface and it is updated every second, instead the traffic_rx_behavior (both, rx and tx) is the traffic of the interface calculated using the DES algoritm and it is updated every 5 minutes, with the "current value" at the 5th minute; the real value of the traffic is inside the column "value", the lower/upper bounds instead are the lower and upper bounds from the DES algorithm that nDPI calculates (more info here: https://www.ntop.org/guides/ntopng/basic_concepts/alerts.html, 'Behavior Alert' section). Please if you still think that the values aren't correct please underline which value I should be carefull about

**Comment by 612wong** [comment]
Thanks MatteoBiscosi.
I misunderstood that the tx and rx traffic is separated into two series now but I should use the old one. Thanks for the explanation and the URL.
