### ISSUE TITLE
Invalid 95th percentile for multi series

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5793]
![Screen Shot 2021-08-23 at 17 07 54](https://user-images.githubusercontent.com/4493366/130471428-61af167a-d6c5-450f-969b-38233268449a.png)

95th percentile is broken
- it is shown twice on graphs with a single timeseries
![Screen Shot 2021-08-23 at 17 10 30](https://user-images.githubusercontent.com/4493366/130471733-4d7d5654-f315-404f-aff2-313e80914405.png)

- it is shown correctly on multi-timeseries, not reported in the graph (acceptable), but average instead is reported and it is not clear to what timeseries it refers

**Comment by MatteoBiscosi** [comment]
Verified as fixed
