### ISSUE TITLE
Behavior Analysis not available on ntopng Enterprise M v.5.1.210822 (Raspbian GNU)

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5794]
Hello ntop team
I cant get the behavior analysis running on my raspberry pi. (rp os light, current version):
<img width="585" alt="Screenshot 2021-08-24 at 00 18 58" src="https://user-images.githubusercontent.com/38549755/130526682-78f0f1fc-7eb9-4c61-8c91-d18f5b294663.png">
thank you

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu , unfortunatly the behavior analysis is available only with ntopng Enterprise L license. Sorry for the trouble, I'm going to specify this requirement better in the documentation.

**Comment by martinscheu** [comment]
Hi @MatteoBiscosi , ok thank you. but this means on a raspberry pi the feature is not available (anymore) ?

**Comment by simonemainardi** [comment]
Enterprise L embedded is available upon request by mailing mallegro at ntop dot org
