### ISSUE TITLE
Service map question - how can I enable this feature?

### ISSUE THREAD

**Issue by 612wong** [ntop/ntopng#5795]
Hi there,

I'm running the latest stable version 5.1.210823 but I couldn't find where I can turn on the service map and have the map like most the others?

Thank you.

**Comment by martinscheu** [comment]
Hello
See https://www.ntop.org/products/traffic-analysis/ntop/, you need Enterprise M or L licence:
Feature | Community | Pro | Enterprise M | Enterprise L
-- | -- | -- | -- | --
Service / Periodicity Maps | ✗ | ✗ | ✓ | ✓


Then Settings, Preferences change to Expert View and there you find the item Behavior Analysis:
<img width="507" alt="Screenshot 2021-08-24 at 08 53 54" src="https://user-images.githubusercontent.com/38549755/130570647-bad12655-f43a-4e71-ab14-17ad953a45cc.png">

**Comment by 612wong** [comment]
I renewed my maintenance a few days ago with my Enterprise M license already.
<img width="1037" alt="Enterprise M license" src="https://user-images.githubusercontent.com/58540705/130611863-56da5959-8147-4e0e-baca-c1361008ee95.png">

Under the setting, I don't see the "Behavior Analysis" option.
<img width="693" alt="Setting" src="https://user-images.githubusercontent.com/58540705/130612175-b0dd5523-9011-424f-a584-761f443b72e1.png">

I hope to explore most of the new features before advising my peers to consider the renewal and upgrade from Enterprise M to L for additional benefits.

**Comment by simonemainardi** [comment]
you can request an unlimited Enterprise L trial license to fully evaluate. Just drop an email to mallegro at ntop dot org

**Comment by 612wong** [comment]
Thanks for your advice. Will write it :)
