### ISSUE TITLE
Some dependency issues in bullseye

### ISSUE THREAD

**Issue by Ryananana** [ntop/ntopng#5796]
Hi

I noticed that bullseye has been supported, but after I tried to install it, the following dependency problems appeared.
![Snipaste_2021-08-24_09-43-21](https://user-images.githubusercontent.com/36809659/130542191-3445e70f-e4da-4e4f-bfb9-3c3e35c36248.png)
![Snipaste_2021-08-24_09-43-31](https://user-images.githubusercontent.com/36809659/130542211-09ad279a-a613-4ad1-96cc-230aebde3d24.png)

It seems that ntopng is still using libsnmp30 and libzmq3. The two packages have been updated to libsnmp40 and libzmq5 in bullseye.
![Snipaste_2021-08-24_09-44-19](https://user-images.githubusercontent.com/36809659/130543181-9de874ca-9520-44e8-87eb-aa6030e875a2.png)
[https://packages.debian.org/search?keywords=libsnmp&searchon=names&suite=bullseye&section=all](url)
[https://packages.debian.org/search?suite=bullseye&section=all&arch=any&searchon=names&keywords=libzmq](url)

The same situation occurred in n2disk, and libcurl3 has been upgraded to libcurl4 in bullseye.
![Snipaste_2021-08-24_09-44-32](https://user-images.githubusercontent.com/36809659/130543200-32ad820f-eb1b-40a1-a323-b273dc8b2c27.png)
[https://packages.debian.org/search?suite=bullseye&section=all&arch=any&searchon=names&keywords=libcurl](url)

I've added "contrib" at the end of each line that begins with deb and deb-src
![Snipaste_2021-08-24_09-52-08](https://user-images.githubusercontent.com/36809659/130543147-97c43a9d-44cd-4589-9ea9-1f7e62ea60d1.png)

**Comment by lucaderi** [comment]
Dev packages have been fixed. Please report if they are working

**Comment by Ryananana** [comment]
I can confirm ntopng 5.1.210825 and n2disk 3.7.210825 both working well in debian bullseye.

**Comment by simonemainardi** [comment]
Thanks for reporting. We are now finalizing stable bullseye releases and do the announcement.
