### ISSUE TITLE
Suspicious DGA Domain Alert - not showing domain name

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5799]
Dear ntop Team

I still have Suspicious DGA Domain alerts, but without the domain name in the details:
<img width="1145" alt="Screenshot 2021-08-24 at 21 10 52" src="https://user-images.githubusercontent.com/38549755/130676046-54b5bf01-a787-4a44-b327-5cd94e2d8816.png">

DGA Alerts false positve rate is high, an exlusion / allow list would be helpful. E.g. I can enter the tld like _e5.sk_ from _7q3laqg6wohunnvj4jkor6kawqbqeaqbaeaq.a.e.e5.sk_

Thank you

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu , if possible could you drop a pcap to me with the right traffic to be able to reproduce the same issue (biscosi@ntop.org)? Because i did some tests but the suspicious dga domain alert were all showing correctly the domain name

**Comment by simonemainardi** [comment]
@cardigliano do you think your work on FQDN exclusions can be extended to this?

**Comment by cardigliano** [comment]
The Check definition can be configured to handle domain whitelists reusing my work. 
In order to implement this in the backend, nDPI (ndpi_check_dga_name specifically) should be extended to handle a whitelist. @lucaderi please confirm this is not already supported.

**Comment by cardigliano** [comment]
I guess ndpi_add_host_risk_mask() is supposed to be used for this.

**Comment by simonemainardi** [comment]
I believe we can add the reload where we already reload custom protocols and categories, i.e., ` ndpi_detection_module_struct* Ntop::initnDPIStruct`.

**Comment by martinscheu** [comment]
@MatteoBiscosi a bit difficult for a pcap, alerts without the domain do not come regularly. But I observed that within one day all alerts without domain info had the Unidirectional UDP traffic issue, as you can see in the screenshot above. Maybe the alert is generated to early?

**Comment by martinscheu** [comment]
@MatteoBiscosi how can I help you?
The issue is still there:
<img width="940" alt="Screenshot 2021-09-30 at 22 28 36" src="https://user-images.githubusercontent.com/38549755/135525837-1d52ae51-3b44-4235-94d0-457e2bfc7599.png">

**Comment by lucaderi** [comment]
@MatteoBiscosi You can reproduce it with ntopng -i ~/nDPI/tests/pcap/weibo.pcap 
@martinscheu This seems to work too
![Screen Shot 2021-10-01 at 12 07 13](https://user-images.githubusercontent.com/4493366/135602891-daa40f5d-54f1-45ea-9dfa-b9d8a70f0143.png)

**Comment by MatteoBiscosi** [comment]
Please open a ticket in nDPI if the problem persists

**Comment by simonemainardi** [comment]
This is solved in the latest dev build.
