### ISSUE TITLE
Aggregated view graph

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#58]
In ntopng when two interfaces are aggregated through a view the traffic is merged. It would be nice on 
http://localhost:3000/lua/if_stats.lua?if_name=en0,lo0&page=historical not to see the sum of traffic directions but rather a stacked chart (of different colours) for each interface

**Comment by lucaderi** [comment]
@simonemainardi Any update?

**Comment by simonemainardi** [comment]
Enhancement is implemented. Currently, it is available only in the pro version. Please check it and suggest further changes.

![image](https://cloud.githubusercontent.com/assets/3397663/10717085/111d8122-7b4e-11e5-851b-5dba8e09956f.png)

**Comment by lucaderi** [comment]
Thank you
