### ISSUE TITLE
Implement per-flow Lua script execution

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#580]
Add the ability to evaluate a Lua script when a flow is created/purged.

The script can be reloaded during the ntopng execution.

**Comment by simonemainardi** [comment]
@emanuele-f is this part of your flow acrivity contribution? can we consider it implemented?

**Comment by emanuele-f** [comment]
This feature should be enabled separately from flow activity stuff

**Comment by simonemainardi** [comment]
@emanuele-f your contribution should have addressed this feature so please check and close it if it is completed.

**Comment by emanuele-f** [comment]
Correct, the flow activity code has been removed and API reorganized. See https://github.com/ntop/ntopng/blob/dev/doc/README.user_scripts for details.
