### ISSUE TITLE
n2disk failed to run as part of Enterprise L bundle

### ISSUE THREAD

**Issue by 612wong** [ntop/ntopng#5800]
I generated the trial license and enabled the 'continuous traffic recording' and found it's not running.
<img width="1077" alt="Screen Shot 2021-08-25 at 14 32 37" src="https://user-images.githubusercontent.com/58540705/130727232-b8640726-2d17-43bb-88c4-5c0ab8d31b0f.png">

Under /local/ntopng, I tailed the log whilst 'resetting' the 'continuous traffic recording' and obtained the following lines.
`25/Aug/2021 12:56:05 [LuaEngineNtop.cpp:467] ntop_get_file_dir_exists(/local/ntopng/plugins0/templates/disk_monitor/check_template.lua) called
25/Aug/2021 12:56:06 [LuaEngineNtop.cpp:4291] Trying to created directory /local/ntopng/n2disk`

Under /local/ntopng/n2disk, I found the config file as follows.
`--interface=et1
--dump-directory=/local/ntopng/4/pcap
--index
--timeline-dir=/local/ntopng/4/timeline
--buffer-len=128
--max-file-len=64
--max-file-duration=60
--disk-limit=1024
--snaplen=1536
--writer-cpu-affinity=0
--reader-cpu-affinity=1
--compressor-cpu-affinity=0
--index-on-compressor-threads
-u=ntopng
--capture-direction=0
--daemon
-P=/var/run/n2disk-et1.pid`

If I manually ran n2disk in the command line prompt, I got the message in the screenshot saying it's running in DEMO mode due to license error.
<img width="1009" alt="Screen Shot 2021-08-25 at 15 06 42" src="https://user-images.githubusercontent.com/58540705/130729969-7b1af4f9-6542-47cb-87eb-a59f4b1603a4.png">

In the sub-directory, I could ran tcpdump -r to read the captured file.

**Comment by cardigliano** [comment]
@612wong please cut&paste the output of n2disk1g -V

**Comment by 612wong** [comment]
Here you are.

`-bash-4.2$ n2disk1g -V
n2disk1g v.3.7.210824 (r5324)
Copyright 2009-21 ntop.org
SystemID:      L1212EDB5000207D0--U1212EDB52F9665C7--OL
Edition:       1G [ntopng Enterprise L License]
License:       qj8B+W+RkGs/z3IV+oc1khkifhxrnKlRDesI8AaarD1DQrarBVoOdgnika/tZ1L3
               B2OEGfXT/RcjrUfmBIpeqPBifKmOaYk3d2JE7YhN1qaehk/fcq7Gc1e79uV+fBBn
               dhhznZwICp8lqUK0CWc5qsjUK5V2rGQjz3Q9OyvuHoqjuiMVqsbpwGCifa+H9aCs
               +HRG65UldbkwtWlpK4EjOOiNzs+zI1JjHOB9pEQFhUeWo90hsizYQmNNHi2T2jcC
               cqeZ/aC7TUlfbzjAyrMWK/fkMF8dpfqBB8+iAW2/NSoR7c04V5aX+kobn2pJt3Kh
               t2ZzxEHyewjU6KDG5WGD5g==
License Hash:  01E6F6F774568CBDB379A2B36FD91D0816304598807517222A [valid license]
License Type:  Time-limited License
Lic. Duration: Until Wed Sep  1 09:31:20 2021 [6 days left]
-bash-4.2$`

**Comment by cardigliano** [comment]
Please provide the output of:
systemctl status n2disk-ntopng@et1

**Comment by 612wong** [comment]
-bash-4.2$ sudo systemctl status n2disk-ntopng@et1
● n2disk-ntopng@et1.service - n2disk ultra-high-speed traffic recorder with realtime indexing on et1
   Loaded: loaded (/usr/lib/systemd/system/n2disk-ntopng@.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
-bash-4.2$

Just noticed the following output difference of the license between n2disk and n2disk1g.

-bash-4.2$ n2disk --check-license
Invalid license


-bash-4.2$ n2disk1g --check-license
Time-Limited license
-bash-4.2$

Do I have to configure ntopng to use n2disk1g?

**Comment by cardigliano** [comment]
Could you try stopping and restarting traffic recording from the Traffic Recording -> Settings page, and provide "systemctl status n2disk-ntopng@et1" again?

**Comment by 612wong** [comment]
Just found the traffic recording was turned off. Turned it on now and following is the output.

-bash-4.2$ n2disk1g --check-license
Time-Limited license
-bash-4.2$ sudo systemctl status n2disk-ntopng@et1
[sudo] password for swong:
● n2disk-ntopng@et1.service - n2disk ultra-high-speed traffic recorder with realtime indexing on et1
   Loaded: loaded (/usr/lib/systemd/system/n2disk-ntopng@.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
-bash-4.2$

I could ran the n2disk1g for capturing without any problems.

-bash-4.2$ sudo n2disk1g -i et1 -o /tmp/hk.pcap
[sudo] password for swong:
###################################################
# You do not seem to have a permanent n2disk1g license.
# We're now in demo mode limited to 6 day(s) 14:56:17
###################################################
25/Aug/2021 18:35:03 [n2disk.c:6897] Welcome to n2disk1g v.3.7.210824 (r5324) [SandyBridge]
25/Aug/2021 18:35:03 [n2disk.c:6931] Running on 1 node(s) system with 2 core(s). NUMA affinity set to node -1.
25/Aug/2021 18:35:03 [n2disk.c:6991] Using PF_RING for packet capture
25/Aug/2021 18:35:03 [n2disk.c:7161] Storage /tmp/hk.pcap: 0.00 GB in use, 5.46 GB available (auto-limit set to 4.37 GB)
25/Aug/2021 18:35:03 [n2disk.c:7211] Storage /tmp/hk.pcap limit set to 4.37 GB, total volume size is 11.71 GB
25/Aug/2021 18:35:03 [n2disk.c:7258] Dump files max size is set to 1024 MB
25/Aug/2021 18:35:03 [n2disk.c:7281] Buffer memory is set to 2 GB (x 2 pcap files)
25/Aug/2021 18:35:03 [n2disk.c:7315] Storage #0 directory: /tmp/hk.pcap
25/Aug/2021 18:35:03 [n2disk.c:7333] Up to 100 files will be written per folder
25/Aug/2021 18:35:03 [n2disk.c:7371] Dumping data in 0.1 MB chunks
25/Aug/2021 18:35:05 [n2disk.c:4652] Using packet timestamps from pf_ring
25/Aug/2021 18:35:05 [n2disk.c:4726] Using PF_RING v.8.1.0
25/Aug/2021 18:35:05 [n2disk.c:4734] Dumping traffic statistics on /proc/net/pf_ring/stats/62709-et1.31
25/Aug/2021 18:35:05 [n2disk.c:4746] Started PF_RING packet reader thread for device et1
25/Aug/2021 18:35:05 [n2disk.c:5726] [reader] Packet capture started
25/Aug/2021 18:35:05 [n2disk.c:649] n2disk1g changed user to n2disk
25/Aug/2021 18:35:05 [n2disk.c:3027] Storage /tmp/hk.pcap: 0.00 GB in use

**Comment by cardigliano** [comment]
@612wong any chance I can connect (e.g. ssh) to this system?

**Comment by 612wong** [comment]
Sorry. It's a server in the company and I could only share the screen with you if we can have a google meet.
remark: I clicked on the wrong button and closed the issue. Can I message you separately with the google meet link?

**Comment by 612wong** [comment]
-bash-4.2$ n2disk1g -V
n2disk1g v.3.7.210824 (r5324)
Copyright 2009-21 ntop.org
SystemID:      L1212EDB5000207D0--U1212EDB52F9665C7--OL
Edition:       1G [ntopng Enterprise L License]
License:       qj8B+W+RkGs/z3IV+oc1khkifhxrnKlRDesI8AaarD1DQrarBVoOdgnika/tZ1L3
               B2OEGfXT/RcjrUfmBIpeqPBifKmOaYk3d2JE7YhN1qaehk/fcq7Gc1e79uV+fBBn
               dhhznZwICp8lqUK0CWc5qsjUK5V2rGQjz3Q9OyvuHoqjuiMVqsbpwGCifa+H9aCs
               +HRG65UldbkwtWlpK4EjOOiNzs+zI1JjHOB9pEQFhUeWo90hsizYQmNNHi2T2jcC
               cqeZ/aC7TUlfbzjAyrMWK/fkMF8dpfqBB8+iAW2/NSoR7c04V5aX+kobn2pJt3Kh
               t2ZzxEHyewjU6KDG5WGD5g==
License Hash:  01E6F6F774568CBDB379A2B36FD91D0816304598807517222A [valid license]
License Type:  Time-limited License
Lic. Duration: Until Wed Sep  1 09:31:20 2021 [6 days left]
-bash-4.2$

**Comment by cardigliano** [comment]
@612wong please drop an email to cardigliano at ntop.org

**Comment by 612wong** [comment]
Last night. I cleaned up the stable version and moved back to dev version.
My colleague found the same situation that n2disk1g reported trial license okay but n2disk not.
Then he had a look at the system service and figured out n2disk-ntopng@et1 was referring to default directory for the configuration. He helped changed the service setting and map it to my custom directory. Now I can see it's recording but I found no way to extract the files. Wondering if his 'trick' has broken the setup.

<img width="1920" alt="traffic recording settings" src="https://user-images.githubusercontent.com/58540705/130934436-5daf9099-7fc2-40b8-8bf9-212e41839c6f.png">

<img width="1920" alt="traffic recording status" src="https://user-images.githubusercontent.com/58540705/130934479-3b671ff3-3bfd-4db8-b389-9917f3e0d076.png">

<img width="1920" alt="traffic extraction job" src="https://user-images.githubusercontent.com/58540705/130934510-d2c47bed-025f-4b05-825c-0be1e035f694.png">

<img width="1920" alt="interface home" src="https://user-images.githubusercontent.com/58540705/130934552-6eb42f56-2683-4754-8ba4-7d0685be08d6.png">

interface setup indicated it's working (n2disk icon in blue) when provider is ntopng.
<img width="1920" alt="traffic recording provider - ntopng" src="https://user-images.githubusercontent.com/58540705/130934579-382739f6-3c6f-40d1-a791-58c2734c0dff.png">

interface setup indicated it's not working (n2disk icon in red) once I switched provider from ntopng to n2disk@et1.
<img width="1920" alt="traffic recording provider - n2disk" src="https://user-images.githubusercontent.com/58540705/130934706-58863f63-0071-4cbf-8100-72dbd087b8ed.png">

on the command line, i can read the pcap files under /local/ntopng/n2disk/4

**Comment by cardigliano** [comment]
What do you mean with "n2disk-ntopng@et1 was referring to default directory for the configuration"?
What did you change exactly?
Anyway, I sent you an email to setup a call or ssh as that's probably easier for debugging this issue.

**Comment by 612wong** [comment]
Thanks and it is late night in Sydney. I will reply you and see if we can have a call / ssh sometimes next week.

**Comment by 612wong** [comment]
In fact, he found n2disk reported invalid license whilst n2disk1g reported trial license properly. Then he did ‘link’ the n2disk to n2disk1g.
Furthermore, he found the following services were running but failed.
***@***.***
***@***.***

He told me the service was referring to a directory where the configuration didn’t exist and ‘fixed’ it.

When I was back to the traffic recording setting. I could turne it on and then the traffic recording provider was ntopng.
I clicked it down and there were options with the above two services.
If I changed the provider from ntopng to them, the recording failed. If I changed it back to ntopng as provider, it started working again.

Today I stopped the traffic recording and cleaned up some space and then restarted the service.
It’s no longer working for me. I will leave it as it is instead of getting my colleague doing the trick for me again.

Please advise what time is good for you to have the call whilst I usually have team meeting on Tuesday and Thursday (London time) but I am based in Sydney.

The trial license will expire in 4 days 21h and I may need to ask for the extension because traffic recording is the most important part for me.

**Comment by cardigliano** [comment]
Please note that it is normal that "n2disk reported invalid license whilst n2disk1g reported trial license properly" as the license included in the bundle is for n2disk1g. The service automatically detect which binary should be used based on the license.

**Comment by 612wong** [comment]
Thanks and I confirmed the pcap data is stored into the expected file system. However the extraction doesn't work for me. When I browsed the Interface traffic and clicked the button to download the pcap but it gave me nothing.

<img width="1920" alt="Screen Shot 2021-08-30 at 16 21 01" src="https://user-images.githubusercontent.com/58540705/131294366-71575aaf-704f-49c1-afac-6e3b1ccb1df5.png">

**Comment by cardigliano** [comment]
@612wong I just sent you an email to schedule a call and debug this

**Comment by 612wong** [comment]
Sorry but I need to close this one now and will find alternatives to this feature.
