### ISSUE TITLE
Enhance GeoMap Tooltip

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5802]
I would find it very useful if you add some information to the IP address and VLAN information you show as a tooltip when placing the mouse cursor over a host in the Geo Map view. This might also apply to the small window that appears when clicking on the host in the Geo Map.

In my particular case, I'd love to see the ASN name (not the number) along with the IP address. That would easily allow me to discriminate between friends and potentials foes on the map. My memory is not good enough to remember those IP address ranges, but ASN are self-explanatory in most of the cases (especially when they point to a well-known corporation).

An even better solution would be to allow the admin to select what information is shown in that tooltip : Host name, vlan, ASN, number of flows, total rx/tx data, blacklisted status ... I am sure each user might need different information depending on their use case.

**Comment by MatteoBiscosi** [comment]
Implemented as requested. The Geo Map customization is available only for users with at least Pro License and it is possible to enable/disable main host data by the preferences.
![Screenshot from 2021-08-27 16-45-02](https://user-images.githubusercontent.com/49585191/131145683-406b8cf8-a879-411e-8e24-262ca7844f0f.png)
![Screenshot from 2021-08-27 16-47-47](https://user-images.githubusercontent.com/49585191/131146158-9994498c-f690-4f24-b766-d735b97e58fb.png)

**Comment by lucaderi** [comment]
@MatteoBiscosi The preference was not really necessary but it is nice to have. Please set the default to set (currently is not set) and close this ticket. Good work.
