### ISSUE TITLE
Alerts page - fixed column width

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5804]
Dear ntop team
Would it be possible to have fixed column width in the Alerts page?
As when I have long DGA domains, like 
Suspicious DGA Domain [d23iz4esrwkib6.cloudfront.net:80/lu/depot/cdbu/logioptions/update_check/full/8.54/files.latest/logioptions_logitech.exe.manifest.sig?/logitech/controldevices/logioptions/8.34/logioptions/8.34.82/w10/64/logioptions.exe.manifest.sig%3fdlu.uv=7.00.99999&dlu.han=logioptions&dlu.hav=8.34&dlu.hpn=logioptions&dlu.hpv=8.34.82&dlu.hpe=exe&dlu.uos=w10&dlu.ubi=64&dlu.uid=0000a73ecb000000266a462a0000000556&hcd1=6b015&hcd2=6b019]
it doesen't show the description and other issue column, only when I zoom down in the browser I can see it.
Thank you.

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu, like the suspicious file transfer alert, now the dga domain alert has a maximum length to the domain, in this way the string is not going overboard; if the string is too long then a question mark is going to show up and you just need to move the mouse above it to show the entire domain. If you need to copy-paste it, click on the external link and you can copy the entire url from there (in the near future a copy button is going to be implemented).
![Screenshot from 2021-08-26 12-13-54](https://user-images.githubusercontent.com/49585191/130946029-c1193e71-a88f-4bba-be4e-91e1cfcfd102.png)
![Screenshot from 2021-08-26 12-19-43](https://user-images.githubusercontent.com/49585191/130946177-02a21fc4-f857-428a-ac05-48ae0dd43693.png)
