### ISSUE TITLE
Suspicious File Transfer - not showing file name

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5805]
Hello ntop team
With the suspicious file transfer alert I have alerts without showing further context:
<img width="2689" alt="Screenshot 2021-08-25 at 23 16 18" src="https://user-images.githubusercontent.com/38549755/130866002-ff3303b4-b2e5-49d7-a5ec-1fa97077c7c0.png">

Would it be possible to add some information?
Thanks, Martin

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu this issue is pretty strange, could you please capture a pcap and drop it to my mail? Because it shouldn't be possible to detect a suspicious file transfer without HTTP protocol

**Comment by martinscheu** [comment]
@MatteoBiscosi please check your email, thanks

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu, I was trying to fix this but unfortunately the pcaps you provided only triggers other alerts (like Remote Access and so on...) if you have the possibility, could you try to capture an other pcap and send it again?

**Comment by martinscheu** [comment]
@MatteoBiscosi yes can try.

**Comment by lucaderi** [comment]
@MatteoBiscosi This alert is misleading. It should be a binary application transfer as written in the source code
   gui = {
      i18n_title = "flow_risk.ndpi_binary_application_transfer",
      i18n_description = "flow_risk.ndpi_binary_application_transfer",
   }
}

Furthermore, you can reproduce it with ntopng -i nDPI/tests/pcap/waze.pcap
that produces
![Screen Shot 2021-10-01 at 12 04 21](https://user-images.githubusercontent.com/4493366/135602577-a50d1159-e462-4af3-bcc6-d7fe3c854845.png)

@martinscheu This seems to work for me.

**Comment by simonemainardi** [comment]
if you relabel make sure to update tests as well

**Comment by MatteoBiscosi** [comment]
Implemented as requested. Please open a ticket in nDPI if the problem persists.
