### ISSUE TITLE
Alert description - link button

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5806]
Hello ntop team
When descriptions have a link, some they have a blue link button:
<img width="982" alt="Screenshot 2021-08-25 at 23 31 43" src="https://user-images.githubusercontent.com/38549755/130867463-8a60efd0-f8ee-4b97-a383-7c0fc61ef2a1.png">
This is very helpful, but with long links, the button only appears when zooming down the page.
Could you move the link button to the start of the url?
And if you could add it to other alert descriptions too?
(e.g. Suspicious DGA Domain)
Thank you, Martin

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu, as requested the link button is now before the url and I added the redirect to the alerts with an external url/link.
