### ISSUE TITLE
Implement Websocket for AJAX refresh

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#581]
ntopng must start using web sockets at least for the page footer to reduce the load on the browser

**Comment by tomlabaude** [comment]
+1
Client opens 1 socket per second simply for network_load.lua, a wireshark trace is full of TCP handshakes.
Reusing the same socket will save files opened on the client, reduce load on the network, on the server and will more ... pretty!

<img width="1088" alt="screenshot" src="https://cloud.githubusercontent.com/assets/15690818/19184474/9a8d4e74-8c7d-11e6-9feb-06f32b109d4a.png">

**Comment by lucaderi** [comment]
@tomlabaude Would you like to lead this development ?

**Comment by tomlabaude** [comment]
Unfortunately, I'm not able to do that dev and am also looking for a dev to work on the frontend of another project.
I have mixed feelings of only being able to report problems without being able to help...

**Comment by lucaderi** [comment]
For the time being we decided that websocket support can create issues to the HTTP server and thus we postpone its implementation.
