### ISSUE TITLE
Service map

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#5811]
Where can I see the service map
![image](https://user-images.githubusercontent.com/44804599/131066747-2e43101b-871a-433d-9ee5-c30e5cf18f31.png)

**Comment by martinscheu** [comment]
please check https://github.com/ntop/ntopng/issues/5795

**Comment by MaoPann** [comment]
What is the difference between  Periodicity map and service map? I only see the  Periodicity Map
![image](https://user-images.githubusercontent.com/44804599/131103578-a364220b-b44a-48b8-8c40-0e2d0027135e.png)

**Comment by MatteoBiscosi** [comment]
Hi @MaoPann if you need other info, you can find them here, https://www.ntop.org/guides/ntopng/advanced_features/behavior_analysis.html
