### ISSUE TITLE
Change colour for enabled action control

### ISSUE THREAD

**Issue by tomukasteris** [ntop/ntopng#5812]
Hello,

Could you please change colour for enabled and disabled action controls.

At this moment when action is enabled button is in red colour and slide button is on left, but in reality should be reversed.

If enabled, action button should be green and slide on right.

![image](https://user-images.githubusercontent.com/11430578/131185569-67c1585a-6672-4464-8350-fcc374380379.png)

**Comment by VasilisTako** [comment]
Hi @tomukasteris, thank you for your advice. I've changed the colour and the direction of the slider in the button. Furthermore I added a hover tooltip in order to show a short description for each of them.
