### ISSUE TITLE
Add extra space in throughput

### ISSUE THREAD

**Issue by tomukasteris** [ntop/ntopng#5813]
Could you please add extra space as throughput doesn't fit and jumps up.

![image](https://user-images.githubusercontent.com/11430578/131192481-7b7606b0-b3aa-4220-814a-3299ad496792.png)

**Comment by MatteoBiscosi** [comment]
Hi @tomukasteris , thanks a lot for your suggestion, I missed this unexpected behavior, resolved with this last commit. Builds are in progress, wait for a few hours, upgrade and the issue should be gone.
