### ISSUE TITLE
Defining IPv6 networks with option -m in ntopng.conf is effectless after upgrade to ntopng-5.0-stable 

### ISSUE THREAD

**Issue by GrumpyOldNetworkGuy** [ntop/ntopng#5815]
```::::::::::::::
ntopng-V
::::::::::::::
root@schnuffel:~# ntopng -V
Version:	5.0.210826 [Enterprise/Professional build]
GIT rev:	5.0-stable:40ce980b98ab688215ba59fc428aab5c442eee35:20210826
Pro rev:	r4192
Built on:	Debian GNU/Linux 10 (buster)
System Id:	LB35D5FF69105A1EF--UB35D5FF675690F7F--OL
Platform:	x86_64
Edition:	Enterprise L (Bundle)
License Type:	Permanent
Maintenance:	Until Mon Jun 27 17:26:24 2022 [302 days left]
License:	pYuniYz5fNuiapjAU8Wexiy7xi2fuGdcGQSzfKblTvll6EE7sn5zpWf/ShirN/Dhcq82N
        	POYVIxoy8edXZG34yV8dAJAQO+w6LBsV+qdpwj8xgVOXRtG5n6RsScTi52hK3xU5djn8a
        	GcxG3EqKenYM+dDYkPmD+7niVJ7LIwvOOm2MJpfPAz/AK+sdlCXMtQBKlcsKfmU6jFSOi
        	QfPyB2KSv/PKGk/jm/Y1WYwmFa1K4MIqeDB4SIRw4fGsO06dzv+lS1ZZia321ISoSx8CI
        	/2Z4N2bSRMcLDM5zseoRN4ylenuQ8Nkw5SGMJg9UTAKh8H7FI8DcH0PeoM0/G5vNHg==
License Hash:	B6EC589054054FA09DE3A214834990C11656343584E0979A97
root@schnuffel:~#
::::::::::::::
nprobe-dc.conf
::::::::::::::
-i=none
-n=none
--collector-port=9996
--zmq-probe-mode
--zmq tcp://127.0.0.1:5558
-T=@NTOPNG@
--disable-startup-checks
#--collector-passthrough
::::::::::::::
nprobe-lan.conf
::::::::::::::
-i=none
-n=none
--collector-port=2055
--collection-filter=!141.35.40.0/24
--zmq-probe-mode
--zmq tcp://127.0.0.1:5556
-T=@NTOPNG@
--disable-startup-checks
#--collector-passthrough
::::::::::::::
nprobe-xwin.conf
::::::::::::::
-i=zc:ens2f0
-n=none
--zmq-probe-mode
--zmq tcp://127.0.0.1:5557
-T=@NTOPNG@
--disable-startup-checks
#--collector-passthrough
::::::::::::::
ntopng.conf
::::::::::::::
-i=br980
-i=tcp://*:5556c
-i=tcp://*:5557c
-i=tcp://*:5558c
--http-port=0
--https-port=3443
-m="141.35.0.0/16,10.0.0.0/8,2001:638:1558::/48,2001:638:909::/48,fd01:638:1558::/48"
-n=1
-q
--max-num-hosts=4000000
--max-num-flows=20000000
-F=nindex;direct
::::::::::::::
ntopng.log
::::::::::::::
Aug 28 17:49:16 schnuffel ntopng[26408]: 28/Aug/2021 17:49:16 [Ntop.cpp:2493] Setting local networks to 141.35.0.0/16,10.0.0.0/8,2001:638:1558::/48,2001:638:909::/48,fd01:638:1558::/48
![LAN-Networks](https://user-images.githubusercontent.com/86432254/131226243-96c136a1-366f-4400-957f-1bea1b9a66ce.png)
![LAN-LocalIPv6Hosts](https://user-images.githubusercontent.com/86432254/131226272-e7fc801b-9a13-48e3-a097-2bb7647a4888.png)

```

**Comment by cardigliano** [comment]
@GrumpyOldNetworkGuy it seems this is working for me, could you provide a small pcap to reproduce this? Thank you.

**Comment by GrumpyOldNetworkGuy** [comment]
Hello Alfredo,

When starting ntopng with the parameter '-m="141.35.0.0/16,10.0.0.0/8,2001:638:1558::/48,2001:638:909::/48,fd01:638:1558::/48"' in ntopng.conf this is logged correctly:

"Aug 28 17:49:16 schnuffel ntopng[26408]: 28/Aug/2021 17:49:16 [Ntop.cpp:2493] Setting local networks to 141.35.0.0/16,10.0.0.0/8,2001:638:1558::/48,2001:638:909::/48,fd01:638:1558::/48"

Please correct me if I'm wrong. This five lines should now appear in ntopng hosts-> networks:
- 141.35.0.0/16
- 10.0.0.0/8
- 2001:638:1558::/48
- 2001:638:909::/48
- fd01:638:1558::/48.

Traffic at the nprobe sensors should not be necessary for this.

In our ntopng-5.0-stable installation it looks like this in contrast:
![LAN-Networks](https://user-images.githubusercontent.com/86432254/131467792-cab3758d-ba67-4a76-8260-4c451043e34e.png)

With traffic at the nprobe sensors, IPv6 hosts from the networks 2001:638:1558::/48, 2001:638:909::/48 and fd01:638:1558::/48 should be marked as local [L]. Unicast Hosts that do not belong to these IPv6 networks should be classified as remote [R]. In our ntopng-5.0-stable installation, for example, hosts belonging to network 2a06: 98c1:: /32 [CLOUDFLARENET-EU] are marked as local. Remote IPv6 hosts are not registered:
![LAN-LocalIPv6Hosts](https://user-images.githubusercontent.com/86432254/131468474-12ea144f-11a9-42c6-b728-adb76c547434.png)

I have attached a pcap file with ZMQ traffic from "tcp://127.0.0.1: 5557".

[nprobe-lan.pcap.zip](https://github.com/ntop/ntopng/files/7082746/nprobe-lan.pcap.zip)

Best regards,
Gerd

**Comment by cardigliano** [comment]
@GrumpyOldNetworkGuy I was asking for a pcap with the original traffic (raw packets) to reproduce this actually, as I cannot use encoded zmq traffic. Anyway, we are trying to reproduce this in other ways in the meantime. 
Could you provide the full ntopng trace when you start the application please? (the one including the logs you already provided). Thank you.

**Comment by GrumpyOldNetworkGuy** [comment]
@cardigliano Unfortunately the nprobe-xwin interface is in zc mode (zc:ens2f0). The nprobe-lan interface receives netflow data from 30 Cisco IOS switches / routers and the nprobe-dc interface receives sFlow data from 12 Cisco NX-OS switches. Would the Netflow / sFlow data be useful to you? The start protocol of ntopng is attached.

[ntopng-start.log](https://github.com/ntop/ntopng/files/7094195/ntopng-start.log)

In addition, I installed an ntopng in the lab, which works directly on the WiFi interface:
```
/etc/ntopng/ntopng.conf
-i=wls1
--http-port=3000
-m="141.35.0.0/16,10.0.0.0/8,2001:638:1558::/48,2001:638:909::/48,fd01:638:1558::/48"
-n=1
-q
-v=6
```
After the start, the directly connected network is displayed. After pinging targets in the networks added with -m, these networks will be displayed correctly. IPv6 hosts outside the networks defined with -m are correctly marked as remote [R] and the IPv6 host dns.google is no longer in my data center. ;-) In the lab all is fine.

Tomorrow I could connect zc:ens2f0 of the production machine directly to ntopng. Let's see if the problem goes away.

**Comment by GrumpyOldNetworkGuy** [comment]
@cardigliano I attached zc:ens2f0 directly to ntopng:
```
-i=zc:ens2f0
--http-port=0
--https-port=3443
-m="141.35.0.0/16,10.0.0.0/8,2001:638:1558::/48,2001:638:909::/48,fd01:638:1558::/48"
-n=1
-q
--max-num-hosts=4000000
--max-num-flows=20000000
-F=nindex;direct
```
All five networks are displayed correctly. Local IPv6 hosts are marked with [L], remote ones with [R]:

![zc-ens2f0-networks](https://user-images.githubusercontent.com/86432254/131790204-f7de4c61-24c9-4801-8002-86d489ca00e8.png)

Now I connect the Netflow nprobe@lan again:
```
/etc/ntopng/ntopng.conf
-i=zc:ens2f0
-i=tcp://*:5556c
--http-port=0
--https-port=3443
-m="141.35.0.0/16,10.0.0.0/8,2001:638:1558::/48,2001:638:909::/48,fd01:638:1558::/48"
-n=1
-q
--max-num-hosts=4000000
--max-num-flows=20000000
-F=nindex;direct
```
The nprobe@lan interface only shows the two IPv4 networks: 
![LAN-networks](https://user-images.githubusercontent.com/86432254/131794454-2737d452-8203-4543-87ce-e30fc0c60606.png)

And the Google IPv6 resolver lives in my data center again. 
![LAN-dns google](https://user-images.githubusercontent.com/86432254/131794667-a3770ad6-538e-450a-84f2-8c20e1ca19b0.png)

Is the nprobe the problem? I'm running out of ideas .

**Comment by cardigliano** [comment]
@GrumpyOldNetworkGuy this was helpful, it seems the issue comes up when collecting from ZMQ. Thank you.

**Comment by cardigliano** [comment]
@GrumpyOldNetworkGuy I was able to identify the issue, I pushed a fix for this, a new update will be available soon (later today).

**Comment by GrumpyOldNetworkGuy** [comment]
@cardigliano Much better. The IPv6 networks are now correctly recognized: 
![LAN-networks](https://user-images.githubusercontent.com/86432254/131845095-03c6bf16-1b13-41b3-9010-54b3b6f24c13.png)

I'm not sure, but shouldn't the IPv6 link-local addresses be marked as local as well? 

![Remote-IPv6-Hosts](https://user-images.githubusercontent.com/86432254/131845595-7dd6b2e0-2555-435b-81b1-2639741f581a.png)

**Comment by cardigliano** [comment]
Great. Thank you.

**Comment by GrumpyOldNetworkGuy** [comment]
@cardigliano I looked again in the lab installation. There IPv6 link-local addresses are marked as local [L]. Can you adjust that, please? Link-local addresses marked as remote are very confusing. 
![LAB-Local-IPv6-Hosts](https://user-images.githubusercontent.com/86432254/131865631-f0d6b38b-969e-4b8d-be8a-8d1f55831416.png)
