### ISSUE TITLE
Question about support of MAC address based traffic direction over disaggregated interface

### ISSUE THREAD

**Issue by 612wong** [ntop/ntopng#5816]
My peer's setup is using tap aggregation switches for multiple WAN links. In this case, can I still use "MAC address based traffic direction" feature to separate the RX and TX rate? Is this feature only available in 5.0 release? Thanks.

**Comment by cardigliano** [comment]
@612wong are you processing traffic with ntopng directly, or using nProbe?

**Comment by 612wong** [comment]
@cardigliano In my peer's setup, he is using ntopng directly.

**Comment by 612wong** [comment]
I forgot I would be able to simulate this at my site where I'm running the latest version. This could be closed by now. Thanks.
