### ISSUE TITLE
Local HTTP Servers No data

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#5817]
We use sFlow  、neftlow
![image](https://user-images.githubusercontent.com/44804599/131315084-17d7bc9e-b3ae-4ddb-ad75-76f68fe0eaf8.png)

**Comment by MatteoBiscosi** [comment]
Hi @MaoPann, now the issue should be solved, please wait for a few hours, update and let me know. Note that only local http servers are shown here (https://www.ntop.org/guides/ntopng/web_gui/hosts.html#http-servers-local).
![Screenshot from 2021-08-30 13-01-35](https://user-images.githubusercontent.com/49585191/131329867-c4edd5c2-1ac7-4ed5-b0c6-9e1dde188b99.png)

**Comment by MatteoBiscosi** [comment]
Please reopen the issue if a problem arise
