### ISSUE TITLE
No host history data visible (storing in elastic search...)

### ISSUE THREAD

**Issue by nate-byrnes** [ntop/ntopng#582]
Perhaps this is not an issue, but, I cannot see any per host traffic history. Instead I get the graph like below. I could not find any documentation detailing the correct storage set up so this would work...

![ntopng_host_hist](https://cloud.githubusercontent.com/assets/19349744/15438923/7785e21e-1e9c-11e6-867a-e1a21a171e7a.png)

**Comment by nate-byrnes** [comment]
This host definitely has had traffic in the past hour. So this graph should be populated. My configuration is:

--interface=eth1
--interface=eth2
--interface=eth4
--interface=eth5 
--daemon=
--dns-mode=1 
--local-networks=" ---- removed from post ----- " 
--redis=localhost 
--dump-flows="es;ntopng;ntopng-%Y.%m.%d;http://lb.elmdc.com:9200/_bulk" 
#--dump-flows=
--packet-filter="not host 10.88.29.18"
--dump-hosts=local
--dump-aggregations=local
--sticky-hosts=local
--communities=/etc/ntopng/communities.list

I've also tried just --dump-flows= (assuming that would dump to sqlite in the data directory...?) but that also seems not to produce any graphs either.

**Comment by simonemainardi** [comment]
@nate-byrnes 
- make sure to upgrade to the latest nightly build
- check permissions 1: is the user who runs ntopng privileges to monitor `--interface`s?
- check permissions 2: Empty charts can be the symptom that ntopng is not able to write data points to disk. Make sure `/var/tmp/ntopng` is writeable by the user who runs ntopng.

**Comment by nate-byrnes** [comment]
I've upgraded to v.2.3.160523 (I am using packages.ntop.org as my apt repo). The user is 'nobody' and able to capture the data off of the interfaces. I have verified that /var/tmp/ntopng is owned by nobody.  Is the data I'm looking for just the bytes.rrd files in the subdirectory `/var/tmp/ntopng/<interface num>/rrd/<octet 1>/<octet 2>/<octet 3>/<octet 4>@<vlan>/`   ?

**Comment by simonemainardi** [comment]
@nate-byrnes yes, the subdirectory is right. Note that the host must be local.

`--communities` is not a valid option, same for `--dump-aggregations`.  Check the help.

Post contents of the Traffic tab for the local host considered. I guess the interfaces simply don't receive it's traffic.Have a look at: http://www.ntop.org/pf_ring/port-mirror-vs-network-tap/

**Comment by nate-byrnes** [comment]
Thanks, the hosts are local. Just to clarify, I have no history for any local hosts. I've taken out the communities and dump-aggregations lines from my config file. I cleaned out /var/tmp/ntopng and restarted. 

(side note: It seems that ntopng creates the child directories before it changes users. It re-created all the subdirectories, which were owned as root, but when I looked at the process, it was running as nobody.)

I am running in a port-mirrored setup on a gigabit switch, but my traffic is no-where near the half gigabit bandwidth consumption yet. 

Here is a local host's traffic page. As you can see it is receiving traffic, the RRD file `/var/tmp/ntopng/5/rrd/173/225/53/28@13/bytes.rrd` exists, along with its protocol named sibling files. 

![ntopng-localhost-traffic](https://cloud.githubusercontent.com/assets/19349744/15504631/ebeb1fea-218d-11e6-83a8-2181d7ec2a15.png)

**Comment by simonemainardi** [comment]
I noticed the host has VLAN 13. You verified that file permissions are OK. Can you please check if historical charts are properly shown for local hosts that don't belong to any vlan?

**Comment by nate-byrnes** [comment]
I do not have any hosts which do not  belong to any vlan. 

File permissions (sampled... look like):

```
root@kvm1:/var/tmp/ntopng# ls -altr 5/
total 36
drwxrwxrwx  5 nobody nogroup 4096 May 24 08:52 subnetstats
drwxrwxrwx  3 nobody nogroup 4096 May 24 08:52 profilestats
drwxrwxrwx 10 nobody nogroup 4096 May 24 08:55 vlanstats
drwxrwxrwx  5 nobody nogroup 4096 May 24 09:00 json
drwxrwxrwx  3 nobody nogroup 4096 May 24 09:51 activities
drwxrwxrwx  9 nobody nogroup 4096 May 24 09:51 .
drwxrwxrwx  7 nobody nogroup 4096 May 24 10:08 ..
drwxrwxrwx  2 nobody nogroup 4096 May 24 10:40 top_talkers
drwxrwxrwx  6 nobody nogroup 4096 May 24 10:40 rrd
root@kvm1:/var/tmp/ntopng# ls -altr 5/rrd/
total 16248
drwxrwxrwx 2 nobody nogroup    4096 May 24 08:55 localstats
drwxrwxrwx 3 nobody nogroup    4096 May 24 08:55 208
drwxrwxrwx 4 nobody nogroup    4096 May 24 08:55 10
drwxrwxrwx 3 nobody nogroup    4096 May 24 08:55 173
-rw-rw-rw- 1 nobody nogroup   80720 May 24 09:50 Webex.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 09:50 RX.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 09:50 LotusNotes.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 09:50 LDAP.rrd
drwxrwxrwx 9 nobody nogroup    4096 May 24 09:51 ..
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:05 TeamSpeak.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:05 PcAnywhere.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:05 MDNS.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 Yahoo.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 WindowsUpdate.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 Wikipedia.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 Whois-DAS.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 WhatsAppVoice.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 WhatsApp.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 Weibo.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 VRRP.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 Vevo.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 UPnP.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 Unknown.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 UbuntuONE.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 Twitter.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 Tor.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 Teredo.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 Telnet.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 TeamViewer.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 Syslog.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 STUN.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 Steam.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 Starcraft.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 SSL.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 SSL_No_Cert.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 SSH.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 SSDP.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 Spotify.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 SNMP.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 Snapchat.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 SMTPS.rrd
-rw-rw-rw- 1 nobody nogroup   80720 May 24 10:40 SMTP.rrd


....


root@kvm1:/var/tmp/ntopng# ls -altr 5/rrd/10/
total 16
drwxrwxrwx 4 nobody nogroup 4096 May 24 08:55 .
drwxrwxrwx 5 nobody nogroup 4096 May 24 08:55 88
drwxrwxrwx 4 nobody nogroup 4096 May 24 08:55 254
drwxrwxrwx 6 nobody nogroup 4096 May 24 10:40 ..
root@kvm1:/var/tmp/ntopng# ls -altr 5/rrd/10/88/
total 20
drwxrwxrwx  4 nobody nogroup 4096 May 24 08:55 ..
drwxrwxrwx  3 nobody nogroup 4096 May 24 08:55 0
drwxrwxrwx  5 nobody nogroup 4096 May 24 08:55 .
drwxrwxrwx  7 nobody nogroup 4096 May 24 09:00 29
drwxrwxrwx 13 nobody nogroup 4096 May 24 10:30 28
root@kvm1:/var/tmp/ntopng# ls -altr 5/rrd/10/88/28/
total 52
drwxrwxrwx  3 nobody nogroup 4096 May 24 08:55 255@5
drwxrwxrwx  3 nobody nogroup 4096 May 24 08:55 253@5
drwxrwxrwx  3 nobody nogroup 4096 May 24 08:55 61@5
drwxrwxrwx  3 nobody nogroup 4096 May 24 08:55 22@5
drwxrwxrwx  3 nobody nogroup 4096 May 24 08:55 41@5
drwxrwxrwx  3 nobody nogroup 4096 May 24 08:55 47@5
drwxrwxrwx  5 nobody nogroup 4096 May 24 08:55 ..
drwxrwxrwx  3 nobody nogroup 4096 May 24 09:50 29@5
drwxrwxrwx  3 nobody nogroup 4096 May 24 09:50 68@5
drwxrwxrwx  3 nobody nogroup 4096 May 24 10:25 30@5
drwxrwxrwx  3 nobody nogroup 4096 May 24 10:30 69@5
drwxrwxrwx 13 nobody nogroup 4096 May 24 10:30 .
drwxrwxrwx  3 nobody nogroup 4096 May 24 10:35 26@5
root@kvm1:/var/tmp/ntopng# ls -altr 5/rrd/10/88/28/253@5/
total 772
drwxrwxrwx  3 nobody nogroup   4096 May 24 08:55 .
drwxrwxrwx  4 nobody nogroup   4096 May 24 08:55 dns
drwxrwxrwx 13 nobody nogroup   4096 May 24 10:30 ..
-rw-rw-rw-  1 nobody nogroup 154784 May 24 10:40 Unknown.rrd
-rw-rw-rw-  1 nobody nogroup 154784 May 24 10:40 udp.rrd
-rw-rw-rw-  1 nobody nogroup 154784 May 24 10:40 tcp.rrd
-rw-rw-rw-  1 nobody nogroup 154784 May 24 10:40 icmp.rrd
-rw-rw-rw-  1 nobody nogroup 154784 May 24 10:40 bytes.rrd

```

**Comment by simonemainardi** [comment]
any chance you can give me access to the ntopng ui? If affirmative then please contact me privately at mainardi ntop org and send access details. thank you

**Comment by nate-byrnes** [comment]
Yes, sending details now.

**Comment by nate-byrnes** [comment]
Did you receive the details I sent?

**Comment by simonemainardi** [comment]
Hi. Yes. Sorry we are out of office at the ripe meeting in Copenhagen. We have limited resources. We will look at your issue during the weekend.

**Comment by simonemainardi** [comment]
@nate-byrnes we have made some fixes. could you please try and update to the latest dev version. Thank you.

**Comment by nate-byrnes** [comment]
I'm now on 2.3.160531, the historic data icon does not appear for any of the hosts (all local) that I've looked at so far (10+). Most of the hosts I've looked at were listed as top talkers.

**Comment by nate-byrnes** [comment]
When I run with "--dump-flows=" rather than my ES config in "--dump-flows=es;...." I get the historical chart icon for hosts again. But, there is still no data rendered in the chart. When I am looking at my current top talker (presently a system getting a microsoft update) I can see that it's rrd files haven't been updated since the 24th.

**Comment by simonemainardi** [comment]
@nate-byrnes we are trying to sort out your issue. Please check the email: we are asking you some extra details.
