### ISSUE TITLE
Grey Alerted Flows

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#5820]
![image](https://user-images.githubusercontent.com/44804599/131486344-d22c0035-01f3-4359-8007-e7213484ec85.png)

**Comment by MatteoBiscosi** [comment]
Hi @MaoPann , 'Alerted Flows' is just a title (separator). However to make it more understandable i moved it to the left, like the other titles.
![Screenshot from 2021-08-31 12-48-27](https://user-images.githubusercontent.com/49585191/131489641-0e9e82d6-d035-40be-86bc-26f123810f6b.png)
