### ISSUE TITLE
Observation IDs in nProbe causing ntopng not to display any flows

### ISSUE THREAD

**Issue by dkrey** [ntop/ntopng#5821]
Hi there,
I'm currently experimenting with nProbe(pro, licensed) and observation IDs.

I wonder if this is a bug in ntopng. When I use an observation ID in nProbe, no flows are shown in ntopng. But as soon as I comment out "-E=0:11" in nprobe, the flows are displayed correctly. 

![image](https://user-images.githubusercontent.com/11175831/131507937-ba59952d-204f-4b99-be13-71eafaf5b707.png)

Ntopng startup:
ntopng -v 2 --no-promisc -i tcp://127.0.0.1:5511c -w 3000

nProbe config
```
-i=none
-n=none
-3=2055
-V=9
-T=@NTOPNG@
--zmq=tcp://127.0.0.1:5511
--zmq-probe-mode
-L="lots of networks"
-E="0:11"
--discard-tcp-probing-flows
--enable-ipv4-deduplication
```

**Comment by lucaderi** [comment]
If you remove -E on nProbe, do flows show up on ntopng?

**Comment by dkrey** [comment]
Exactly. That's how it's currently running.

**Comment by MatteoBiscosi** [comment]
Hi @dkrey , a fix is up now, wait for the builds to be ready, update and the issue should be gone.

**Comment by dkrey** [comment]
I've just updated to v.5.0.210831 rev.15433. But once I added "-E=0:11" back in (nprobe.conf), the flow view in ntopng went back to "no results found" (ntopng).
The collected flow counter in the ZMQ statistics is still moving upwards.

**Comment by cardigliano** [comment]
@dkrey please check v.5.0.210901 which is now available and let us know. Thank you.

**Comment by dkrey** [comment]
Yeah, I can confirm that it is fixed with this version: v.5.0.210901 rev.15435

Thanks!

**Comment by cardigliano** [comment]
Great, thank you!
