### ISSUE TITLE
No response from request for assistance with getting the enterprise version

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#5822]
Email sent to Maria Allegro has gone unanswered ....

@simonemainardi 

Please let us know if there is something we can do on our end, thank you

Stewart Alexander
Network Admin @ Alamance Community College

**Comment by cardigliano** [comment]
@StewAlexander-com please add me (cardigliano at ntop.org) in copy to the request you sent to Maria. Please note Simone is out of office for holidays.

**Comment by StewAlexander-com** [comment]
@cardigliano email sent with you on copy, thank you
