### ISSUE TITLE
ZMQ Collector Interface Compression Errors

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#5823]
We are seeing near-constant ZMQCollectorInterface.cpp:398 Error: Uncompressed errors in ntopng.log.  Attached is the ntopng status, log excerpt and server performance stats.  

Version:        4.3.210818 [Enterprise/Professional build]
GIT rev:        dev:3d8def4136832d1f98c40d25e0764986d2da30ed:20210818
Pro rev:        r4187
Built on:       CentOS Linux release 7.9.2009 (Core)
System Id:      L896504CBB207AB27--U896504CBA6817F83--OL
Platform:       x86_64
Edition:        Enterprise L

[ntopng.log(excerpt).txt](https://github.com/ntop/ntopng/files/7085122/ntopng.log.excerpt.txt)
![ntopng-status](https://user-images.githubusercontent.com/46939729/131527097-7d6b0280-7689-4567-a356-a5119e33f38f.JPG)
[server-stats-8-20-21.txt](https://github.com/ntop/ntopng/files/7084943/server-stats-8-20-21.txt)

**Comment by lucaderi** [comment]
https://github.com/ntop/ntopng/commit/cd720076783fbdeafb8072578be2fb026557f342 should fix this issue
