### ISSUE TITLE
Host packet page is blank

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#5824]
The host packet page is blank.  Every other host page contains data.

Version: 4.3.210818 [Enterprise/Professional build]
GIT rev: dev:3d8def4136832d1f98c40d25e0764986d2da30ed:20210818
Pro rev: r4187
Built on: CentOS Linux release 7.9.2009 (Core)
System Id: L896504CBB207AB27--U896504CBA6817F83--OL
Platform: x86_64
Edition: Enterprise L

**Comment by ghost** [comment]
![ntopng-host(packet)](https://user-images.githubusercontent.com/46939729/131589815-d2ee1300-b014-48f6-b06d-01fbf95209a0.jpg)

**Comment by cardigliano** [comment]
@jhhaskins are you able to move to 5.1 and check if you still experience the same? Thank you.

**Comment by simonemainardi** [comment]
I can reproduce this behavior on the latest 5.1 using a view. Working on the fix.

**Comment by MatteoBiscosi** [comment]
Fixes are requested, now if no data is available it is going to be shown an empty table
![Screenshot from 2021-09-21 15-55-34](https://user-images.githubusercontent.com/49585191/134184365-d6871e21-63bc-4af1-af14-17ba22983fdd.png)
