### ISSUE TITLE
ntopng Enterprise M v.5.0.210831 with interface view:all will keep restarting service

### ISSUE THREAD

**Issue by LAKEQIQI** [ntop/ntopng#5828]
after upgrade to ntopng Enterprise M v.5.0.210831 today, the ntopng service will keep restarting with no error log.

after comment my .conf file with the line. 'view:all', it can start normally.

-i tcp://127.0.0.1:5555
#-i tcp://127.0.0.1:5556
#-i tcp://127.0.0.1:5557
#-i tcp://127.0.0.1:5558
#-i view:all

if it no longer supports this ?

**Comment by cardigliano** [comment]
Fixed, an update will be available later today
