### ISSUE TITLE
Top Senders as MAC addresses

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5829]
When using MAC addresses as local host identifiers
![Screen Shot 2021-09-01 at 18 02 21](https://user-images.githubusercontent.com/4493366/131704933-14c5bd45-ef59-4eda-8f3f-9596059b828c.png)

the top sender page contains only MAC (only one and this is odd)  and not IPs even if there is an IP bound to this MAC

![Screen Shot 2021-09-01 at 18 02 12](https://user-images.githubusercontent.com/4493366/131704939-e62036c3-8bd7-497b-96aa-66d67f65a7a7.png)

**Comment by MatteoBiscosi** [comment]
Should be fixed, pro repo

**Comment by lucaderi** [comment]
Still bugged
![Screen Shot 2021-09-02 at 19 36 18](https://user-images.githubusercontent.com/4493366/131890842-2f88fd06-2517-4cf3-bfeb-feb85a289936.png)

**Comment by MatteoBiscosi** [comment]
Now should be fixed, pro repo

**Comment by lucaderi** [comment]
![Screen Shot 2021-09-22 at 10 17 48](https://user-images.githubusercontent.com/4493366/134307876-f5aa5ac4-7136-4322-9a01-01e9a4c16b31.png)
Not quite

**Comment by MatteoBiscosi** [comment]
Unable to reproduce this behavior, please try to take a look at `pro/scripts/lua/get_ts_table.lua` line 247 and print the resolution.
The resolution is done by `getFirstIpFromMac` (screenshot below)
![Screenshot from 2021-10-05 15-58-27](https://user-images.githubusercontent.com/49585191/136038196-b0b43e11-27bf-475b-aa42-d7ff5ea891ee.png)

**Comment by MatteoBiscosi** [comment]
Changed the only thing that could rollback the ip address resolved into the mac address again, please update and let me know if now works correctly (pro rep.)

**Comment by lucaderi** [comment]
Finally fixed :-)
