### ISSUE TITLE
Enhancement:  Message for SQL Schema Change

### ISSUE THREAD

**Issue by alberk8** [ntop/ntopng#583]
Hi,

When upgrading to a new ntopng and if there is a SQL schema change in new version of ntopng, particularly when there is already an existing large DB  it would take sometime to complete.  In the meantime the web interface of ntopng would not appear and this would give an illusion that something is wrong with ntopng.  There is not message (/var/tmp./ntopng/ntopng.log) that DB schema is being changed.

I would be a great help if you can log the message in ntopng.log as well as on the console. Please do logn the start of the SQL schema change process as well as the end of the process.  Thank you.

**Comment by simonemainardi** [comment]
Thanks, also related to #567

**Comment by simonemainardi** [comment]
ntopng will output a notification when performing the latest mysql schema update (see https://github.com/ntop/ntopng/commit/9953cc2328d653cda7b138dd933a539abb7b9179#diff-6c69828bd2ad4b659c217ed525196f27R297). This behavior will be kept consistent for any possible new schema update.
