### ISSUE TITLE
There was an error while sending timeseries data to "http://localhost:8086": An unknown error occurred. [503]

### ISSUE THREAD

**Issue by AlekseiSaff** [ntop/ntopng#5831]
This error occur after updating to ntopng-5.0.210901-14731.x86_64

**Comment by cardigliano** [comment]
@AlekseiSaff could you provide more details about the configuration and steps to reproduce this? What is the page reporting this error?

**Comment by AlekseiSaff** [comment]
Hi after I changed 
http://localhost:8086 to http://hostname.domin:8086 it works.
http://localhost:8086 - doesn't work (worked all the time before in 4.x)
http://hostname:8086 - doesn't work
http://hostname.domin:8086 - works

**Comment by MatteoBiscosi** [comment]
Hi @AlekseiSaff could you provide more info? I'm not understanding what you are referring to. What did you change? How did you reproduce this behavior?

**Comment by AlekseiSaff** [comment]
I changed the address of the influxDB in ntopng interface. 
originally it was http://localhost:8086  and worked well in 4.x 

now I changed it to HTTP://ntopng.my.domain:8086 and it works

**Comment by cardigliano** [comment]
It seems "http://localhost:8086" is still working for me with the latest ntopng, I guess there is some misconfiguration somewhere else

**Comment by simonemainardi** [comment]
> http://localhost:8086 - doesn't work (worked all the time before in 4.x)

check under /etc/hosts and make sure string `localhost` is correctly mapped to the machine IP (127.0.0.1).

**Comment by simonemainardi** [comment]
Solution given. Reopen with the requested feedback if necessary.
