### ISSUE TITLE
Accept symbols in username

### ISSUE THREAD

**Issue by gianlucapiccolo** [ntop/ntopng#5835]
**Use case:**
We implemented an SSO system to login from a portal to ntopng. The user is created as it is on ntopng using the /lua/rest/v1/add/ntopng/user.lua REST API endpoint. A lot of our users have a username that contains dots  "." or other symbols, for example "user.name@company". Those users must access to ntopng by the SSO system as all the others.

**Request**
On ntopng, accept also username with dots "." or other symbols: .,@,-,etc....

**Context**
Currently, the ntopng application doesn't allow this kind of characters in the username. This is a similar request to [this closed issue](https://github.com/ntop/ntopng/issues/2495).

**How to reproduce**
```
curl -vvv -X POST -L 'http://localhost:3001/lua/rest/v1/add/ntopng/user.lua' -H 'Content-Type: application/json' -H 'Authorization: Basic <TOKEN>' -d '{"username":"mario@rossi.com","user_role":"administrator","allowed_interface":"","allowed_networks":"0.0.0.0\/0,::\/0","allow_pcap_download":"1","user_language":"en","full_name":"mario rossi","password":"<PASSWORD>","confirm_password":"<PASSWORD>"}'

* About to connect() to localhost port 3001 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3001 (#0)
> POST /lua/rest/v1/add/ntopng/user.lua HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:3001
> Accept: */*
> Content-Type: application/json
> Authorization: Basic <TOKEN>
> Content-Length: ...
> 
* upload completely sent off: 294 out of 294 bytes
< HTTP/1.1 400 Bad Request
< Cache-Control: max-age=0, no-cache, no-store
< Server: ntopng 4.2.210811 [x86_64-unknown-linux-gnu [x86_64][]]
< Pragma: no-cache
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< Content-Type: application/json
< Last-Modified: Thu, 09 September 2021 15:07:04 GMT
< Set-Cookie: session=; max-age=3600; path=/;  HttpOnly; SameSite=lax
* no chunk, no close, no size. Assume close to signal end
< 
* Closing connection 0
{"rsp":[],"rc_str_hr":"Invalid arguments","rc":-5,"rc_str":"INVALID_ARGUMENTS"}
```

**Comment by MatteoBiscosi** [comment]
Hi @gianlucapiccolo , as requested now some special characters are accepted (`_ , - , ! , ? , @`) and the max length of the username is 30 characters (no more 20) however i cannot give more freedom for security reasons. Wait for the new builds and update, the change should be available in some hours

**Comment by MatteoBiscosi** [comment]
Hi @gianlucapiccolo as requested this feature is added to the stable version, please wait for the builds to be ready (in a few hours) and update.
