### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#5836]
Flow - > local host only
![image](https://user-images.githubusercontent.com/44804599/131945102-91c7b17b-eebf-4217-b82f-56c574f52eae.png)

**Comment by cardigliano** [comment]
@MaoPann I assume you verified you have local <-> local flows, please confirm. (this seems to be working for me)

**Comment by MaoPann** [comment]
I confirm i have local flows.

**Comment by MaoPann** [comment]
I can see many local host,Does this refer to the flow from local host to local host?

**Comment by cardigliano** [comment]
Correct, that's from a local host to a local host

**Comment by MaoPann** [comment]
OK, I think it's normal

**Comment by cardigliano** [comment]
Let's close this then. Thank you.
