### ISSUE TITLE
The function list given on the official website is not satisfied

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#5837]
，I use the enterprise M version, but I don't have the function of service map，This function is introduced on the official website
![image](https://user-images.githubusercontent.com/44804599/131987726-40cada7c-1cd4-4a1d-b1e9-8ac67d0e8604.png)

**Comment by cardigliano** [comment]
@MaoPann sorry, the documentation is reporting L, but the website was not in sync, we just fixed this. Sorry for the misunderstanding.
