### ISSUE TITLE
licsense not recognized in docker

### ISSUE THREAD

**Issue by mamema** [ntop/ntopng#5839]
Hi,

i've sucessfully migrated my license to a first docker host. Then i was trying to migrate a second time to another host. This fails constantly. I've change the docker run command from -v $(pwd)/ntopng.license to /etc/ntopng.license. But this doesn't help.

My log:

Starting redis-server: redis-server.
04/Sep/2021 08:03:29 [Prefs.cpp:1232] All HTTP user login disabled
04/Sep/2021 08:03:29 [Prefs.cpp:1191] ntopng will use redis 192.168.0.30@0
04/Sep/2021 08:03:29 [Prefs.cpp:1195] redis connection is password-protected
04/Sep/2021 08:03:29 [Ntop.cpp:2493] Setting local networks to 192.168.0.0/24,172.16.0.0/16,192.168.188.0/18
04/Sep/2021 08:03:29 [Redis.cpp:157] Successfully connected to redis 192.168.0.30:6379@0
04/Sep/2021 08:03:29 [Redis.cpp:157] Successfully connected to redis 192.168.0.30:6379@0
04/Sep/2021 08:03:29 [NtopPro.cpp:324] [LICENSE] Reading license from /etc/ntopng.license
04/Sep/2021 08:03:29 [NtopPro.cpp:217] Contacting licensing server. Please hold on...
04/Sep/2021 08:03:30 [NtopPro.cpp:217] Contacting licensing server. Please hold on...
04/Sep/2021 08:03:30 [NtopPro.cpp:217] Contacting licensing server. Please hold on...
04/Sep/2021 08:03:30 [NtopPro.cpp:217] Contacting licensing server. Please hold on...
04/Sep/2021 08:03:30 [NtopPro.cpp:466] [LICENSE] /etc/ntopng.license: unable to validate license [Invalid response received: data tampered (by HTTP proxy?)]
04/Sep/2021 08:03:30 [NtopPro.cpp:320] [LICENSE] No license file found /etc/ntopng.license: reading license from redis
04/Sep/2021 08:03:30 [NtopPro.cpp:469] [LICENSE] Unable to validate license [Empty license file]
04/Sep/2021 08:03:30 [NtopPro.cpp:538] WARNING: [LICENSE] Invalid license [Invalid response received: data tampered (by HTTP proxy?)]
04/Sep/2021 08:03:30 [NtopPro.cpp:555] WARNING: [LICENSE] ntopng will now run in Enterprise L edition for 10 minutes
04/Sep/2021 08:03:30 [NtopPro.cpp:557] WARNING: [LICENSE] before returning to community mode
04/Sep/2021 08:03:30 [NtopPro.cpp:559] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
04/Sep/2021 08:03:30 [NtopPro.cpp:561] WARNING: [LICENSE] or run ntopng in community mode starting
04/Sep/2021 08:03:30 [NtopPro.cpp:562] WARNING: [LICENSE] ntopng --community
04/Sep/2021 08:03:31 [NetworkInterface.cpp:2986] Cleanup interface eno2
04/Sep/2021 08:03:31 [main.cpp:234] Unable to open interface eno2 [97]: PF_RING not loaded. Falling back to pcap.
04/Sep/2021 08:03:31 [PcapInterface.cpp:93] Reading packets from eno2 [id: 2]
04/Sep/2021 08:03:31 [Ntop.cpp:2601] Registered interface eno2 [id: 2]
04/Sep/2021 08:03:31 [main.cpp:331] PID stored in file /var/run/ntopng.pid
04/Sep/2021 08:03:31 [Geolocation.cpp:149] Loaded database dbip-city-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip-city-lite.mmdb][ip_version: 6]
04/Sep/2021 08:03:31 [Geolocation.cpp:149] Loaded database dbip-asn-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip-asn-lite.mmdb][ip_version: 6]
04/Sep/2021 08:03:31 [Geolocation.cpp:95] Using geolocation provided by DB-IP (https://db-ip.com)
04/Sep/2021 08:03:31 [HTTPserver.cpp:1691] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
04/Sep/2021 08:03:31 [HTTPserver.cpp:1700] HTTPS server listening on 192.168.0.30:3000
04/Sep/2021 08:03:31 [Utils.cpp:737] WARNING: Unable to retain privileges for privileged file writing
04/Sep/2021 08:03:31 [Utils.cpp:781] User changed to ntopng
04/Sep/2021 08:03:31 [NetworkInterface.cpp:2771] Started flow user script hooks loop on interface eno2 [id: 2]...
04/Sep/2021 08:03:31 [NetworkInterface.cpp:2802] Started host user script hooks loop on interface eno2 [id: 2]...
04/Sep/2021 08:03:31 [main.cpp:401] Working directory: /var/lib/ntopng
04/Sep/2021 08:03:31 [main.cpp:403] Scripts/HTML pages directory: /usr/share/ntopng
04/Sep/2021 08:03:31 [Ntop.cpp:479] Welcome to ntopng x86_64 v.5.0.210902 - (C) 1998-21 ntop.org
04/Sep/2021 08:03:31 [Ntop.cpp:489] Built on Ubuntu 20.04.2 LTS
04/Sep/2021 08:03:31 [NtopPro.cpp:763] [LICENSE] System Id:	L89692E869206AB23--U89692E86A6E20B83--OL
04/Sep/2021 08:03:31 [NtopPro.cpp:764] [LICENSE] Edition:	Enterprise L (Bundle)
04/Sep/2021 08:03:31 [NtopPro.cpp:765] [LICENSE] License Type:	Time-Limited [Invalid response received: data tampered (by HTTP proxy?)] License
04/Sep/2021 08:03:31 [NtopPro.cpp:785] [LICENSE] Validity:	Until Sat Sep  4 08:13:30 2021
04/Sep/2021 08:03:31 [Ntop.cpp:914] Adding 10.1.1.1/32 as IPv4 interface address for eno2
04/Sep/2021 08:03:31 [Ntop.cpp:923] Adding 10.0.0.0/8 as IPv4 local network for eno2
04/Sep/2021 08:03:31 [PeriodicActivities.cpp:107] Started periodic activities loop...
04/Sep/2021 08:03:32 [startup.lua:37] Processing startup.lua: please hold on...
04/Sep/2021 08:03:32 [startup.lua:169] [lists_utils.lua:784] Refreshing category lists...
04/Sep/2021 08:03:32 [startup.lua:169] [lists_utils.lua:420] Updating list 'Abuse.ch URLhaus' [https://urlhaus.abuse.ch/downloads/hostfile/]... OK
04/Sep/2021 08:03:33 [startup.lua:169] [lists_utils.lua:420] Updating list 'Emerging Threats' [https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt]... OK
04/Sep/2021 08:03:33 [startup.lua:169] [lists_utils.lua:420] Updating list 'Feodo Tracker Botnet C2 IP Blocklist' [https://feodotracker.abuse.ch/downloads/ipblocklist.txt]... OK
04/Sep/2021 08:03:33 [startup.lua:169] [lists_utils.lua:420] Updating list 'NoCoin Filter List' [https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt]... OK
04/Sep/2021 08:03:33 [startup.lua:169] [lists_utils.lua:420] Updating list 'SSLBL Botnet C2 IP Blacklist' [https://sslbl.abuse.ch/blacklist/sslipblacklist.txt]... OK
04/Sep/2021 08:03:33 [startup.lua:169] [lists_utils.lua:420] Updating list 'SSLBL JA3' [https://sslbl.abuse.ch/blacklist/ja3_fingerprints.csv]... OK
04/Sep/2021 08:03:34 [startup.lua:169] [lists_utils.lua:420] Updating list 'Snort IP Block List' [https://snort.org/downloads/ip-block-list]... OK
04/Sep/2021 08:03:35 [startup.lua:169] [lists_utils.lua:717] Category Lists (1600 hosts, 3052 IPs, 100 JA3) loaded in 1 sec
04/Sep/2021 08:03:35 [startup.lua:288] Completed startup.lua
04/Sep/2021 08:03:35 [PeriodicActivities.cpp:168] Each periodic activity script will use 2 threads
04/Sep/2021 08:03:35 [NetworkInterface.cpp:2953] Started packet polling on interface eno2 [id: 2]...
04/Sep/2021 08:03:36 [NetworkInterface.cpp:1883] Packets exceeding the expected max size have been received [len: 1975][max len: 1518].
04/Sep/2021 08:03:36 [NetworkInterface.cpp:1886] WARNING: If TSO/GRO is enabled, please disable it for best accuracy
04/Sep/2021 08:03:36 [NetworkInterface.cpp:1888] WARNING: using: sudo ethtool -K eno2 gro off gso off tso off

      
My compose file:

version: "3"
services:
  ntopng:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - AUDIT_CONTROL
      - BLOCK_SUSPEND
      - DAC_READ_SEARCH
      - IPC_LOCK
      - IPC_OWNER
      - LEASE
      - LINUX_IMMUTABLE
      - MAC_ADMIN
      - MAC_OVERRIDE
      - NET_ADMIN
      - NET_BROADCAST
      - SYSLOG
      - SYS_ADMIN
      - SYS_BOOT
      - SYS_MODULE
      - SYS_NICE
      - SYS_PACCT
      - SYS_PTRACE
      - SYS_RAWIO
      - SYS_RESOURCE
      - SYS_TIME
      - SYS_TTY_CONFIG
      - WAKE_ALARM
    command:
      - '-i eno2 -w 192.168.0.30:0 -W 192.168.0.30:3000 --disable-login 1 --redis
        192.168.0.30:6379:password -m 192.168.0.0/24,172.16.0.0/16,192.168.188.0/18
        --online-license-check'
    container_name: ntopng
    entrypoint:
      - /run.sh
    environment:
      - TZ=Europe/Berlin
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    expose:
      - 3000/tcp
    hostname: hostname
    image: ntop/ntopng:latest
    ipc: private
    logging:
      driver: json-file
      options: {}
    networks:
      - host
    security_opt:
      - label=disable
    volumes:
      - /mnt/docker/ntopng/config/ntopng.license:/etc/ntopng.license:ro
      - /mnt/docker/ntopng/config/redis:/var/lib/redis
      - /mnt/docker/ntopng/config/data:/var/lib/ntopng
networks:
  host:
    external: true

**Comment by cardigliano** [comment]
@mamema how much time elapsed between migrations? 
Did you migrate the license through the show, or just setting the online mode in the application?
Could you provide the order id in a direct email? (cardigliano at ntop.org)

**Comment by cardigliano** [comment]
Fixed
