### ISSUE TITLE
ntopng stable: Ntopng installation is suddenly broken. Incorrect PFring version. Incorrect ndpi version.

### ISSUE THREAD

**Issue by sysop11** [ntop/ntopng#5840]
I've researched this heavily and see this has been an issue several times in the past, yet there is no actual solution that worked for me.

 ntopng : Depends: pfring (= 8.0.0-6874) but it is not going to be installed

When installing pfring, I get version 8.1 which apparently is incompatible. I can't find a way to specifically download pfring 8.0. I removed Ntopng and pfring but now things are worse.  I can't even install pfring anymore. When trying to install pfring again, I get this

 pfring : Depends: ndpi (= 4.0.0-3308) but 4.1.0-3295 is to be installed

So now everything seems to be all messed up. It's weird because my 2 other servers are identical to this one, and neither one of them is doing this. Any help would be greatly appreciated.

OS: Debian 10 Buster

**Comment by sysop11** [comment]
Persistence paid off. I will post my solution for anyone else who happens to stumble upon this topic.

Even though I thought I had removed/purged all Ntopng related things, it seems the old version of ndpi was the culprit. I removed/purged ndpi. After doing this, I was able to follow the normal installation instructions without all the version mismatch craziness.

**Comment by cardigliano** [comment]
@sysop11 this seems to be related to some misconfiguration with the repository, you probably moved from dev to stable without purging all packages. Please note there is a script for that at https://www.ntop.org/support/faq/how-can-i-switch-from-stable-to-dev-branch-or-vice-versa/
