### ISSUE TITLE
DNS request info in DNS Query info

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5841]
Dear ntop Team
Would it be possible to get the request type e.g. A, AAAA or HTTPS together with the requested domain. Now a _ping google.com -c1_ gives two flows, but information nDPI is DNS or DNS.Google, which I think is not related to A or AAAA query.
Would it be possible to have the A or AAAA info in the flow info, e.g. in front of the Domain:
<img width="831" alt="Screenshot 2021-09-06 at 09 54 47" src="https://user-images.githubusercontent.com/38549755/132180974-bd3875f0-4af7-4424-9795-b5006c8a85f1.png">

Also if you could move the square/arrow link sign in front of the link.?

Thank you, Martin

**Comment by simonemainardi** [comment]
Implemented as requested.

![image](https://user-images.githubusercontent.com/3397663/132190589-04573780-07b9-46b4-9e0d-dfff310f2dde.png)

> Also if you could move the square/arrow link sign in front of the link.?

This cannot be moved for consistency. Indeed, the symbol is always right to the element.

**Comment by martinscheu** [comment]
Hi Simone,
Thanks for picking it up and implementing it.
you are right, it should be consistent throughout ntopng.
Issue with having the link button on the right are very long urls, then the link is not shown. (I have a 3840 x 2160  screen and need to zoom down in firefox to 30% to get the whole link)
Having the link button on the left would eliminate the need to zoom down.
Thank you.
(can send you an example if needed)
