### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#5842]
I execute the following command and report an error

![image](https://user-images.githubusercontent.com/44804599/132190655-948c7c4e-1b35-4a3a-8a9a-cfd0f16709a0.png)

**rpm -ivh http://rpms.remirepo.net/enterprise/remi-release-8.rpm**
Retrieving http://rpms.remirepo.net/enterprise/remi-release-8.rpm
warning: /var/tmp/rpm-tmp.cW6NOi: Header V4 RSA/SHA256 Signature, key ID 5f11735a: NOKEY
error: Failed dependencies:
        redhat-release >= 8.4 is needed by remi-release-8.4-1.el8.remi.noarch

**Comment by simonemainardi** [comment]
Your Centos 8 is outdated. You need version 8.4. Check with:

```
[simone@freeipa ~]$ cat /etc/redhat-release
CentOS Linux release 8.4.2105
```


Make sure to upgrade everything - full instructions at (https://phoenixnap.com/kb/how-to-update-upgrade-centos):

```
sudo yum update
sudo yum check-update
```

Then, install regularly following instructions:

```
[simone@freeipa yum.repos.d]$ sudo rpm -ivh http://rpms.remirepo.net/enterprise/remi-release-8.rpm
Retrieving http://rpms.remirepo.net/enterprise/remi-release-8.rpm
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:remi-release-8.4-1.el8.remi      ################################# [100%]
[simone@freeipa yum.repos.d]$ cat /etc/redhat-release
CentOS Linux release 8.4.2105
```
