### ISSUE TITLE
Monitor mirror traffic

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#5843]
I use ntopng to directly monitor the traffic from the image port, but I can't distinguish between up and down traffic. What should I do?

**Comment by simonemainardi** [comment]
Tick mirrored traffic under the interface cog, then specify the MAC address of the gateway

![image](https://user-images.githubusercontent.com/3397663/132192676-0e0c6d01-cf94-4039-9fce-631aa0cb03e7.png)

Then restart ntopng, and you'll have traffic directions.

**Comment by MaoPann** [comment]
@simonemainardi I don't really understand what interface mac address I should set

**Comment by simonemainardi** [comment]
you should set the MAC address of the gateway. For example, let's say your hosts use router 192.168.2.1 as gateway to reach the internet. If you specify 192.168.2.1 MAC address, then you'll have upload and download properly populated.

**Comment by MaoPann** [comment]
What if I am using the TAP method? How should I configure it?
![image](https://user-images.githubusercontent.com/44804599/132199181-03ff0f4c-9ef2-4eda-ba5a-ec51ff7896e4.png)

**Comment by simonemainardi** [comment]
Set the "Router" MAC address in the field I've highlighted above with the red arrow.
