### ISSUE TITLE
Invalid score usage in anomaly plugin

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5845]
Score anomaly plugin
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/4493366/132203663-44ddb29e-5ce2-4aee-b7e3-8b1676e62cf6.png">

reports a 50 score that is wrong, It must be a high value or the original host value

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/4493366/132203559-320154d4-d5f9-44f3-bdcf-26207d5879bb.png">

It is required to create two different alarms, one for score anomaly and one for high score. Both alarms are stateful.

**Comment by MatteoBiscosi** [comment]
Currently the alert has been divided in two alerts: `Score Anomaly` (The one calculated using DES algorithm) and `Score Threshold Exceeded` (A threshold check, based on the score). This is done to differentiate the two scores, infact regarding the first one it add only 50 score (Warning) regarding the second one it add 250 score (Current Maximum score, Sever Error), infact the Threshold exceeded usually is an indicator of severe errors

**Comment by lucaderi** [comment]
Verified as fixed
