### ISSUE TITLE
Custom application

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#5846]
Can I add a custom applicationin the following way（CIDR）

![image](https://user-images.githubusercontent.com/44804599/132317342-57725dbd-4b88-4b12-aed8-d58e8b60b7e2.png)

**Comment by MaoPann** [comment]
In addition, can IPv6 be supported (e.g. 2620:1ec:: / 64)?

**Comment by simonemainardi** [comment]
> Can I add a custom applicationin the following way（CIDR）

Yes.

> In addition, can IPv6 be supported (e.g. 2620:1ec:: / 64)?

No. Only IPv4 rules.
