### ISSUE TITLE
Feature Request: Add "exporter_ipv4_address" to Dump in ElasticSearch database

### ISSUE THREAD

**Issue by npacket** [ntop/ntopng#5849]
Hi

We need to use "exporter_ipv4_address" information when we export the dump data to ElasticSearch.
Can you add "exporter_ipv4_address" in the fixed template ?

**Comment by lucaderi** [comment]
Can you please instruct nprobe to dump into ELK that is already able to export the  "exporter_ipv4_address" ?

**Comment by npacket** [comment]
Unfortuneately, they have to use ntopng to dump into ELK because of their environment. 
Their customer required ntopng should collect the several nprobe data and ntopng send to dump into ELK as a single instance. 
This is the reason why they’re asking to dump the "exporter_ipv4_address" from ntopng.
Can you able to export the "exporter_ipv4_address" field when ntopng send the dump data to ELK ?

BR,
HyungWon.

**Comment by MatteoBiscosi** [comment]
Implemented as requested (screenshot below represent a flow dumped to ELK and as you can see the EXPORTER_IPV4_ADDRESS is now available)
![Screenshot from 2021-09-28 11-18-22](https://user-images.githubusercontent.com/49585191/135060745-2656a405-6202-4de5-bd3a-a029f90d3872.png)

Please reopen if some issue arise
