### ISSUE TITLE
ntopng mysqlDB grows up... limit usage

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#585]
hi,
I use ntopng to save data in mysql database.
I configured it to limit data retention at 7 days but my DB is growing up too much
So can you confirm me my configuration is OK ?
thanks

Nico
<img width="927" alt="ntop-1" src="https://cloud.githubusercontent.com/assets/17108017/15492707/7cb9757c-217e-11e6-9812-13ff05a96474.PNG">
<img width="920" alt="ntop-2" src="https://cloud.githubusercontent.com/assets/17108017/15492708/7e730626-217e-11e6-8a74-05bed410d9a2.PNG">
<img width="910" alt="ntop-3" src="https://cloud.githubusercontent.com/assets/17108017/15492714/8d5c9d14-217e-11e6-8827-e5d1f4d1c68a.PNG">

**Comment by Niko78** [comment]
it would be interesting to have an option to limit disk usage from database because even in putting only seting in days... 
I can get few datas for one week but a biggest streams an other week, so in 7 days I can't get the same space each time

so if it's possible maybe an option to tell that database can't exceed 80% of disk space by example

nico

**Comment by Niko78** [comment]
my disk is full and now I have error in syslog... I configured ntop to catch data only 7 days but it grows with no limit it seems
is there something to do overwrite old data instead of warning me it is full ?

**Comment by simonemainardi** [comment]
as this is a pretty relevant topic we have prepared a blog post that explains how to optimize MySQL disk space usage: http://www.ntop.org/ntopng/tweaking-mysql-to-improve-ntopng-flows-storage-space-usage/
