### ISSUE TITLE
Flow verdict is not mapped

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5854]
![image](https://user-images.githubusercontent.com/4493366/132584653-3958e3a4-4fc8-406a-a690-b06163764f12.png)

As show in the picture below
- the verdict 1 and 2 must have additional labels and be mapped to "1 (Pass)" and 2 (Drop)" better with icons
- the verdict must be moved before the additional flow elements

**Comment by MatteoBiscosi** [comment]
Implemented as requested
