### ISSUE TITLE
Missing HREF and Description in Alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5857]
![image](https://user-images.githubusercontent.com/4493366/132670112-19bd9f7f-079f-4fe0-93a1-ea1450c66552.png)

It is required to add an HREF to flow risks that will jump to the documentation and explains exactly what is this problem about and what are the remedies to apply.

Make sure the description is also added in alerts

![image](https://user-images.githubusercontent.com/4493366/132703151-8961dd01-02a7-45fc-a3a5-8d843380bfe0.png)

**Comment by lucaderi** [comment]
This ticket depends on https://github.com/ntop/nDPI/issues/1307

**Comment by lucaderi** [comment]
Now you can implement it. Online documentation it is available at https://www.ntop.org/guides/nDPI/flow_risks.html

**Comment by simonemainardi** [comment]
Implemented

![image](https://user-images.githubusercontent.com/3397663/135636786-33a9f354-0733-4f61-9be6-198ac9588bb8.png)

![image](https://user-images.githubusercontent.com/3397663/135636845-9bbac052-ff7c-45c8-9a64-fc8e0c8fd94c.png)

**Comment by lucaderi** [comment]
Verified as fixed
