### ISSUE TITLE
Add Score Filtering Feature

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5858]
![image](https://user-images.githubusercontent.com/4493366/132670897-726d03c4-18cc-47de-9530-e9218cc0316d.png)

It is required to add slider/text-field/selector something that allows reporting only those alerts whose score is >= to the specified value.

**Comment by simonemainardi** [comment]
This ticket depends on https://github.com/ntop/ntopng/issues/5859

**Comment by simonemainardi** [comment]
TLS version is missing over ZMQ as it not exported as part of the "@NTOPNG@" template and it is not inside the "L7_INFO" as well.

**Comment by lucaderi** [comment]
![image](https://user-images.githubusercontent.com/4493366/134317800-f4688ca4-fe08-41be-b072-1b6d4edfd61e.png)

Still not working and unclear to use. Please avoid partial commits

**Comment by MatteoBiscosi** [comment]
Unfortunately, currently, it is not possible to add the score filter to the `all` alert page because due to previous implementations if added to the all alert page, the Historical Flow Explorer and other pages that are using the `range-picker.template` are going to break down. To add it to the `all` page a lot of work is needed.

**Comment by lucaderi** [comment]
I went into hosts and added 50 as score. Then moved to Interface and 
- the field size shrinked
- the value is "50;gte"
-
![Screen Shot 2021-10-11 at 15 20 12](https://user-images.githubusercontent.com/4493366/136797210-92681938-df7a-4e2a-88e5-94bc335307d9.png)

**Comment by lucaderi** [comment]
![image](https://user-images.githubusercontent.com/4493366/136799847-a4834ab6-91ca-4b1f-9795-8bec70e0a6b9.png)

**Comment by lucaderi** [comment]
Verified as fixed
