### ISSUE TITLE
No historical talkers/protocols

### ISSUE THREAD

**Issue by kyoshi-maru** [ntop/ntopng#586]
Hi guys!
I just bought nProbe and ntopng small business (v2.3.160519). I have a problem with the historic data in the interface and single hosts view: It says 'No result found' in the talkers and protocols tab. The chart tab works fine. I found someone with the same issue and it was supposely fixed. The Client/Server Host search box doesn't work either, I tested with a known IP. Everything is stored in a MariaDB instance, no errors in the logs there. I fetched historical statistics using SQL so I guess its not a DB issue.

nprobe string:
nprobe -b 1 --zmq "tcp://*:5556" -i none -n none --collector-port 2055 -G

ntopng string:
ntopng -i tcp://127.0.0.1:5556 -m "10.0.0.0/8" -F "mysql;localhost;ntopng;flows;root;" -e

Screenshot:
![talkers](https://cloud.githubusercontent.com/assets/19554316/15508103/735e475a-21ce-11e6-84c2-81a5e266b982.png)

Do you have any hint how to fix that? Many thanks!

**Comment by simonemainardi** [comment]
Hi, If I understand correctly you checked the MariaDB logs. Can you please also inspect ntopng logs and post any possible error. Thank you.

OT: the number of flows you have is approaching the maximum. Try and increase the value. See `-X`

**Comment by kyoshi-maru** [comment]
Hi! A while after posting the issue here I though about checking for new release in the repo so I updated and restarted, now everything works with v.2.3.160524.

Thanks for the tip with the max flows didn't notice that one :-)
