### ISSUE TITLE
Obsolete SSH: Missing Role from Description (Client or Server)

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5861]
![image](https://user-images.githubusercontent.com/4493366/132702803-84145ecb-1b4b-43aa-afba-c46162475fe4.png)

"Server" present in one message of two

**Comment by simonemainardi** [comment]
Implemented as requested. Verified both with ZMQ and packet interfaces.

**Comment by simonemainardi** [comment]
![image](https://user-images.githubusercontent.com/3397663/132841438-e8472851-1374-49f3-a9f9-c144bc9a6419.png)

**Comment by lucaderi** [comment]
Verified as fixed
