### ISSUE TITLE
GPG key retrieval failed: 

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#5865]
Cento 7 install ntopng 5.0

![image](https://user-images.githubusercontent.com/44804599/133038201-ce95a54d-5c7f-485d-83f8-b8060fc69368.png)

**Comment by cardigliano** [comment]
@MaoPann did you follow the instructions at https://packages.ntop.org/centos-stable/ ?
Please try with:
yum remove epel-release
yum clean all
yum update
yum install epel-release

**Comment by MaoPann** [comment]
Fixed

**Comment by cardigliano** [comment]
Thank you. We will update the installation instructions.
