### ISSUE TITLE
Failed to add custom app

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#5866]
I added a custom application and it didn't take effect after restarting. I've tried many times. I think there may be a bug here. I use CentOS 7 to install ntopng stable version 5.0.

**Comment by simonemainardi** [comment]
Without extra information and steps to reproduce it is impossible to troubleshoot. 

Provide data, configuration, a pcap file, and steps you've done.

**Comment by MaoPann** [comment]
step-1: I add a  custom application 

![image](https://user-images.githubusercontent.com/44804599/133182530-c11bcc06-1428-4e57-9a2f-4ec91eafe4fe.png)



![image](https://user-images.githubusercontent.com/44804599/133182494-6538d41b-d053-4b15-a064-d9e46bdfa955.png)

step-2: restart ntopng and I can't find the  custom application,

![image](https://user-images.githubusercontent.com/44804599/133182657-a9d8e683-0a3f-45b3-9f04-7616271a7e01.png)


step-3: cat /var/lib/ntopng/protos.txt ，The protos.txt file was generated correctly, but the application test could not be found in ntopng.

![image](https://user-images.githubusercontent.com/44804599/133182774-524961dd-7649-4efa-8ec2-6e8e094f0383.png)


Conclusion: the custom application didn't succeed and I couldn't find it

**Comment by MaoPann** [comment]
@simonemainardi

**Comment by simonemainardi** [comment]
```
$ touch /tmp/custom
$ sudo chown ntopng:ntopng /tmp/custom
$ sudo gdb --args ./ntopng -i eno1 -i tcp://*:5556c   -i ../nDPI/tests/pcap/tls_invalid_reads.pcap --disable-login 1 -p /tmp/custom
```

![image](https://user-images.githubusercontent.com/3397663/133214175-197a85fd-e70c-4785-bea4-f7478edc3ae9.png)

![image](https://user-images.githubusercontent.com/3397663/133214190-3678e769-c0a3-48b2-be33-cd055a4536c2.png)

Then, after a restart

![image](https://user-images.githubusercontent.com/3397663/133214291-aadbb2fd-e511-4677-8c3c-3f2db7d410b7.png)


I am no 5.1. Make sure your protos.txt is not deleted and ownership is `ntopng:ntopng`.

**Comment by MaoPann** [comment]
@simonemainardi  I update to 5.1 ,same problem

![image](https://user-images.githubusercontent.com/44804599/133217241-e3ee9fe7-8e10-4a1f-b8c1-813beb077c13.png)
![image](https://user-images.githubusercontent.com/44804599/133217439-867a4d90-1c3b-45b1-9c68-7419e2799d9e.png)
![image](https://user-images.githubusercontent.com/44804599/133217507-45ae64a9-eef4-4cf0-ab9e-ec291544fd31.png)
![image](https://user-images.githubusercontent.com/44804599/133217566-0f72b0cc-0a9f-4cf7-898b-a4a3068281cc.png)

**Comment by simonemainardi** [comment]
are you sure the file is correctly fed to ntopng using `-p`?

**Comment by MaoPann** [comment]
@simonemainardi  I confirm,

![image](https://user-images.githubusercontent.com/44804599/133354751-7e267b64-17b5-4b76-a732-d75bd77549aa.png)

**Comment by simonemainardi** [comment]
Che the ntopng log for errors occurring when loading the file. Please report.
