### ISSUE TITLE
Top L7 Contacts all the same despite different protocol

### ISSUE THREAD

**Issue by dkrey** [ntop/ntopng#5868]
Hi there,
I've recently activated the nIndex functionality and historical flows are now visible in the dashboard and also the drilldown "spy glasses" are visible when selecting an interface and its graph.

When clicking on the spyglass, the graphs and the calculated totals seem to be valid, but the list with the servers below is exactly the same, no matter what protocol is being chosen.

I would expect that these aggregated flows change with the selected protocol. 

![ntop_topapp](https://user-images.githubusercontent.com/11175831/133237046-dca99fca-b994-42df-8223-5e6f70fac3c5.png)

```
https://NTOPHOST/lua/if_stats.lua?detail_view=top_l7_contacts&epoch_end=1631611680&ifid=6&ts_schema=iface:ndpi&epoch_begin=1631609880&page=historical&protocol=TLS
```
![ntop_tls](https://user-images.githubusercontent.com/11175831/133236630-679dc222-f99b-4a93-83b2-deee83e80181.png)

```
https://NTOPHOST/lua/if_stats.lua?detail_view=top_l7_contacts&epoch_end=1631611680&ifid=6&ts_schema=iface:ndpi&epoch_begin=1631609880&page=historical&protocol=MsSQL-TDS
```
![ntop_mssql](https://user-images.githubusercontent.com/11175831/133236662-207d78bf-5ea6-4391-b16c-f8a2e002d08b.png)

**Comment by MatteoBiscosi** [comment]
Hi @dkrey the issue should be solved, a new build is going to be released at most tomorrow morning. Please when the new update is up, let me know if the problem persists or not
