### ISSUE TITLE
 HTTP/1.1 500 Internal server error Content-Type: text/html

### ISSUE THREAD

**Issue by smezei** [ntop/ntopng#587]
HTTP/1.1 500 Internal server error Content-Type: text/html Connection: close Script "/usr/local/shar /ntopng/scripts/lua/index.lua" returned an error:
/usr/local/share/ntopng/scripts/lua/inc/menu.lua:22: attempt to index a userdata value

What is the problem?

Thank you!

**Comment by simonemainardi** [comment]
Hi, please make sure you are using the latest dev build

**Comment by smezei** [comment]
Hi,  it is  ntopng 2.2.0 (in CHANGELOG.md)

**Comment by simonemainardi** [comment]
You should update and use the latest dev build which is 2.3.xx see packages.ntop.org

**Comment by smezei** [comment]
Thank you very much!
I have question!
How can i update and use the lastest build?

**Comment by simonemainardi** [comment]
instructions are at: http://packages.ntop.org/ look for nightly builds

**Comment by smezei** [comment]
Thank you!
But my OS is i686 not x64

**Comment by simonemainardi** [comment]
Presently we are unable to maintain 32-bit packages. Please consider upgrading your system.
