### ISSUE TITLE
Rsyslog in official ntopng docker image

### ISSUE THREAD

**Issue by bmansvk** [ntop/ntopng#5872]
Please add rsyslog package to official docker ntopng image. I am using syslog flow export from ntopng and there must be local syslog server available for ntopng (maybe there is remote syslog config option in ntopng, but I didn't find configuration for it).

**Comment by simonemainardi** [comment]
Remote syslog are supported when adding the endpoint. Just add the Host and Port when adding the syslog endpoint:

![image](https://user-images.githubusercontent.com/3397663/133389680-97d5c20a-5d59-465c-bb6c-6810cc06dd4d.png)

So there is no need to add a local rsyslog to the docker image. It would also break the logic of containerization.

**Comment by bmansvk** [comment]
It seems according to documentation, this is only works for alerts delivered via syslog.

I am trying to log all flows to syslog (using -F syslog cmdline parameter). If I configure endpoint according to your screenshot, I cannot see any flows forwarded to remote syslog server.

**Comment by simonemainardi** [comment]
> It seems according to documentation, this is only works for alerts delivered via syslog.

Correct.

Flows are only supported to the local syslog.

**Comment by bmansvk** [comment]
so, please add rsyslog package to docker image :-)

For me it is sufficient to have rsyslog installed, image doesn't need to start it via entrypoint docker script. One more package doesn't matter I think.

**Comment by simonemainardi** [comment]
Unfortunately, we can't pollute the container with ryslog, it's not the way containers work.

Kindly open a feature request to have ntopng sending flows to remote syslog.

**Comment by bmansvk** [comment]
OK, I understand you.
