### ISSUE TITLE
error: ‘NDPI_CLEAR_TEXT_CREDENTIALS’ was not declared

### ISSUE THREAD

**Issue by wulei-student** [ntop/ntopng#5875]
src/FlowRiskAlerts.cpp:172:4: error: ‘NDPI_CLEAR_TEXT_CREDENTIALS’ was not declared in this scope
   [NDPI_CLEAR_TEXT_CREDENTIALS] = {
    ^
src/FlowRiskAlerts.cpp:176:1: error: too many initializers for ‘const FlowAlertTypeExtended [36]’
 };
 ^
cc1plus: warning: unrecognized command line option "-Wno-address-of-packed-member" [enabled by default]
make: *** [src/FlowRiskAlerts.o] Error 1

**Comment by simonemainardi** [comment]
You nDPI is not aligned. Update nDPI to the latest version.

**Comment by wulei-student** [comment]
I use 5.0-stable succeed（at first I use “dev” branch）

**Comment by simonemainardi** [comment]
You can use dev, but you have to have both nDPI and ntopng at the tip of their respective branches.
