### ISSUE TITLE
Implement minified presets in graphs

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5877]
It is useful to see trends in timeseries that can be also used as presets: clicking on them can mode you to the selected time period similar to what happens today with the dropdown menu. See the enclosed example as baseline
![Screenshot 2021-09-16 at 10 23 44](https://user-images.githubusercontent.com/4493366/133577790-513cf73e-33b4-4bfb-98b8-4d2d0bc66fe2.png)

**Comment by MatteoBiscosi** [comment]
This is already possible with the new timeseries chart component
