### ISSUE TITLE
syslog / cron

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#588]
hi
in checking my logs I detected a cron entry each minute in syslog
CRON[25108]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)

is it normal ?
because my syslog file has ton of these lines

ntopng v.2.3.160528 [Professional Edition]

thanks

Nico

**Comment by lucaderi** [comment]
This is a file part of nbox used to check if there are extractions to do. It is fine like that.
