### ISSUE TITLE
Color inconsistency

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5881]
In this example, there is only one alert with score 50 (yellow) and the icon in the menubar is red instead of yellow

![Screenshot 2021-09-16 at 10 38 18](https://user-images.githubusercontent.com/4493366/133579772-de6042d1-754e-4bb1-a2c6-9ec1a2178959.png)

**Comment by simonemainardi** [comment]
Implemented as requested:

![image](https://user-images.githubusercontent.com/3397663/134700293-f5e44ad7-b6f2-4060-a563-8e56d8cc9305.png)

![image](https://user-images.githubusercontent.com/3397663/134700340-3d0fcf8a-890d-46c1-90be-446ef23ad982.png)

![image](https://user-images.githubusercontent.com/3397663/134700396-21677c93-6759-4e49-86be-19fd251b9b62.png)

**Comment by lucaderi** [comment]
Trusting screenshots it is fixed
