### ISSUE TITLE
SNMP Non-Trunk Port Alarm

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5893]
This is to request the implementation of a new alarm that is triggered (so it has to be stateful) as long as a non-trunk port has a high number of MAC addresses.

**Comment by simonemainardi** [comment]
What makes the effort high is having the alert as stateful as SNMP port alerts are currently stateless.

**Comment by simonemainardi** [comment]
Implemented as stateful alert as requested

![image](https://user-images.githubusercontent.com/3397663/138075339-2f4cb5e2-6562-4bad-b323-a8f8357f38c7.png)

![image](https://user-images.githubusercontent.com/3397663/138075391-4160b686-843f-4217-bb1c-73493d4e6fd1.png)

Configurable under the SNMP device checks

![image](https://user-images.githubusercontent.com/3397663/138075440-e3ef9316-bbf7-4e61-8353-681c53376b4d.png)

Implementation available in the referenced commit and companion pro commit.

**Comment by lucaderi** [comment]
Verified as fixed
