### ISSUE TITLE
Segmentation Fault for enabling the Dynamic Traffic Disaggregation 

### ISSUE THREAD

**Issue by npacket** [ntop/ntopng#5894]
Hi, 

They’re using the blow version of ntopng and they’re using the collector mode.
They’re collecting the 4 x the external nprobe. 
In the ntopng menu, they tried to set “Interface > Dynamic Traffic Disaggregation > Probe IP” and they got the segmentation fault. 
They can’t get the full log messages because of the security issue. 
Please check this issue and let me advice. 

[Version Information]
Version: 5.1.210823 [Enterprise/Professional build]
GIT rev: dev:036ac73dc94aad4649f945c05507b85a4aef6929:20210823
Pro rev: r4195
Built on: Ubuntu 20.04.2 LTS

[Error message]
LuaEngineInterface.cpp @63 index: 11 Name ...
LuaEngineInterface.cpp @3875 Warning : Bad context for interface 11
OtherAlerttableEntity.cpp @64 Error: setEntityValue() not called or empty entity_val
Segmentation fault (core dump)

BR,
HyungWon.

**Comment by cardigliano** [comment]
@npacket is the customer using a single ZMQ interface to collect from all the probes? Is the customer using view interfaces? Could you provide the ntopng configuration file? Thank you.

**Comment by simonemainardi** [comment]
any news?

**Comment by npacket** [comment]
HI Simone, 

They told me that they solved this issue. We can close this ticket. 
When they changed the option of ntopng such as “-x”, this issues was disappeared. 
Thanks for your support.

BR,
HyungWon.
