### ISSUE TITLE
Missing IPS mode documentation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5897]
The ntopng manual does not contain a section (referred in the index) that describes the IPS mode and its integration with nProbe.

This section is way too short and enough to use this feature: https://www.ntop.org/guides/ntopng/web_gui/pools.html#traffic-policies

**Comment by simonemainardi** [comment]
Added and referenced in the section containing all other ntop products

![image](https://user-images.githubusercontent.com/3397663/134541413-6fc5a8ae-8ea3-4add-bb69-2845b3081527.png)

**Comment by lucaderi** [comment]
Verified as fixed
