### ISSUE TITLE
Add checks Factory Reset

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5898]
This is to require a new button (next to "disable all") in the checks page to reset checks to factory settings. 
![Screen Shot 2021-09-20 at 09 09 11](https://user-images.githubusercontent.com/4493366/133967003-6a7543c5-a923-43cc-ab8c-632fa7b0bbea.png)
This button will basically perform the same action of Manage Configurations -> Checks -> Factory reset

**Comment by simonemainardi** [comment]
Added

![image](https://user-images.githubusercontent.com/3397663/134197781-da0e0d5e-c961-4b21-80c4-683f821bd9f6.png)

**Comment by lucaderi** [comment]
The message says "Factory reset all checks for the current configuration"

![Screen Shot 2021-09-22 at 10 14 52](https://user-images.githubusercontent.com/4493366/134307440-f2e4061c-79e4-4443-bc88-80be9beeb944.png)

I don't understand what is the "current configuration". I believe it needs to be removed and renamed to "Do you want to reset the checks configuration to the default"?

**Comment by lucaderi** [comment]
Verified as fixed
