### ISSUE TITLE
Further Checks Classification

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5899]
Checks are currently divided in families but they are not easy to find in particular in IPS mode for understanding which check will cause a host to be jailed. It is requested to add a way to filter checks (or at least initially just mark) to see which checks cause a host to be jailed and filter term in a separate category.

**Comment by simonemainardi** [comment]
- Added a new IPS/IDS category with ability to filter and search

![image](https://user-images.githubusercontent.com/3397663/133984136-d7446204-2c41-4d12-9802-336b990bce9c.png)

- Categorized the Dangerous Host check into the IPS/IDS category
- Improved the description of the Dangerous Host check

![image](https://user-images.githubusercontent.com/3397663/133984243-a72b92ef-1e6d-4daf-ab74-70ad7ac85e33.png)

**Comment by lucaderi** [comment]
In the All tab it is not clear where the checks are coming from (e.g. host or SNMP). Please add a column that shows where the check is coming from

**Comment by simonemainardi** [comment]
Added as part of https://github.com/ntop/ntopng/issues/5610#issuecomment-924886123

**Comment by lucaderi** [comment]
Verified as fixed but #5610 is still bugged
