### ISSUE TITLE
Broken Layout when adding SNMP device

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5901]
![image](https://user-images.githubusercontent.com/4493366/133977164-9f28cfcf-e936-41da-82ef-79a519bee5e7.png)

**Comment by simonemainardi** [comment]
![image](https://user-images.githubusercontent.com/3397663/134677643-68bb8968-37ea-4d61-a999-f5363cc8c3a2.png)

**Comment by lucaderi** [comment]
Verified as fixed but you need to reference the commit.

**Comment by MatteoBiscosi** [comment]
Fixed by 70e32fd566f00ca642cfd4ec433e2ac54672c08c and 1e08ca85263beeff5fbc36720592370c1db18a2b
