### ISSUE TITLE
Implement ICMP Flooding Check

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5904]
Similar to the SYN scan check already present, implement ICMP flooding (e.g. > 100 pkts/sec can be a reasonable default)

**Comment by lucaderi** [comment]
How did you test it?

**Comment by simonemainardi** [comment]
also make sure to update tests accordingly.

**Comment by lucaderi** [comment]
@MatteoBiscosi Asking again: how did you test it?

**Comment by MatteoBiscosi** [comment]
To test it i run `for i in {1..100}; do ping -c 2 1.1.1.$i; done;` in my terminal with ntopng up and set up ntopng ICMP Flood Flows/sec threshold to 1 Flow per second and in a few seconds the alert is going to show up.
![Screenshot from 2021-11-03 16-39-23](https://user-images.githubusercontent.com/49585191/140093217-45238a5b-3dc2-4054-900a-ed1b9ec4517d.png)

**Comment by lucaderi** [comment]
Verified as fixed
