### ISSUE TITLE
Packet size checks

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5906]
Similar to other checks, implement a new check for spotting hosts that misbehave. Possible thresholds could be

0-128 byte > 30000 pkt/s
129-256 byte > 10000 pkt/s

or just have a single threshold (10000 pkt/s)

**Comment by lucaderi** [comment]
Marco Tranchida <m.tranchida1@studenti.unipi.it> is working to implement this check

**Comment by MatteoBiscosi** [comment]
Implemented as requested
