### ISSUE TITLE
ntopng dies / Ubuntu 14.04

### ISSUE THREAD

**Issue by hatclub** [ntop/ntopng#591]
Hi

I did a "DIY" nBox on Ubuntu 14.04 LTS and initially installed from the apt-stable repo. ntopng was crashing without logging anything after 6-18 hours.

At Luca's suggestion I switched to the development repo and did an apt-get update / dist-upgrade and relaunched ntopng, but the issue remains.

No entries appear to be turning up in the ntopng.log or in syslog that would explain the issue.

Any tips on how I can debug this?

Thanks

Phil

**Comment by lucaderi** [comment]
@hatclub Please generate a core dump and share both the core dump and the ntopng binary, so we can debug it.

**Comment by hatclub** [comment]
Hi @lucaderi, I have set /etc/security/limits.conf to permit unlimited cores, rebooted, and will update this once things go wrong again.

**Comment by hatclub** [comment]
Now I actually have a new problem; the nbox interface thinks ntopng isn't running (it is) and ntopng's dashboard claims that I only have 2 or 3 local talkers and 2-5 remote destinations that amount to a few kbits of traffic (whilst also claiming it sees 105k hosts and 56k flows, 30-400mbps total depending on when the netflow gets exported).

![ntopng](https://cloud.githubusercontent.com/assets/5437917/15677264/70ec6fec-2741-11e6-83e5-9182f783b9f1.png)

nprobe-none.conf:
`-n=none
-i=none
-t=60
-d=60
-a=0
-e=1
-B=10
-w=128000
-z=0
-S=1:1
-E=0:0
-g=/var/run/nprobe-none.pid
-3=2055
--zmq=tcp://127.0.0.1:5556
--vlanid-as-iface-idx=none
-V=5
--dump-stats=/var/log/nprobe/none-0_flows_stats.txt
`

ntopng.conf:
`-n=1
-w=3000
-W=0
-g=-1
-m="213.230.192.0/18"
-d=/storage/ntopng
-G=/var/tmp/ntopng.pid
-i=tcp://127.0.0.1:5556`

**Comment by simonemainardi** [comment]
@hatclub this issue is related to the core dump, let's use it just to investigate the dump to make things easier to follow.

Use other issues to track different problems. However, the latest version is v.2.3.160531 so please update to this one before posting. Also, you may want and use ntopng without nbox initially.

**Comment by hatclub** [comment]
Ah, yeah, sorry. Anyway, at least the above served some purpose to get the configs. I actually did an update before rebooting but neglected to actually _upgrade_. Have done, now on 160531, ntopng dashboard looks normal now after /etc/init.d/ntopng restart. Will wait for it to crash.

**Comment by simonemainardi** [comment]
thanks for reporting. let's wait and see

**Comment by hatclub** [comment]
Either one of the builds between stable and 160531 fixes the issue, or installing the licence for nprobe & ntopng fixed the issue - it's stayed up 25h so far which is the longest to date. I guess I'll let you know in a week if it stays up that this can be closed(!)

**Comment by simonemainardi** [comment]
thanks for the feedback
