### ISSUE TITLE
ntopng 5.0-stable repeately drops all packets on interface

### ISSUE THREAD

**Issue by dario-pilori** [ntop/ntopng#5910]
Hello

after upgrading to ntopng 5.0-stable, after few hours, all packets are dropped on one interface (1 Gbit/s, with PF_RING):

![image](https://user-images.githubusercontent.com/16277218/134159591-5cfb6f46-8da3-4208-8c02-43eda909429e.png)

Restarting ntopng resumes the reception, but after few hours all packets are dropped again. At the same time, the activity "minute.lua" hangs:
![image](https://user-images.githubusercontent.com/16277218/134159864-b8c10450-1b5c-44f6-9cda-0da826e25af4.png)

This issue is quite similar to #5867, but here I'm not using ZMQ.

**Comment by simonemainardi** [comment]
Yes. Likely the same issue. I am in touch with the author of #5867 to arrange a remote session but still waiting for the issue to occur. Feel free to send me connection details so that I can do a remote session and check. You can use mainardi at ntop dot org

**Comment by simonemainardi** [comment]
I've fixed an issue possibly causing this behavior. New dev and stable builds are in progress, please hold on a couple of hours, update, and let me know.

**Comment by dario-pilori** [comment]
I confirm that the latest stable build (v5.0.210923) fixes the issue.
