### ISSUE TITLE
Purged hosts in the Service/Periodicity Map

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5913]
![image](https://user-images.githubusercontent.com/4493366/134314335-f5d03cca-7699-4b3e-bc89-c17bd597b0ed.png)

Hosts that are idle and thus not in memory, should not have a valid hyperlink enabled. The hyperlink has to be present only for those hosts in memory and thus accessible.

**Comment by MatteoBiscosi** [comment]
Fixed, pro repo

**Comment by lucaderi** [comment]
Verified as fixed
