### ISSUE TITLE
Invalid Checks Filter

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5914]
Suppose I am on the enabled tab and I filter cybersecurity. This is what I see

![Screen Shot 2021-09-22 at 11 01 32](https://user-images.githubusercontent.com/4493366/134314742-1e49cdd7-45bf-4700-9ece-6f38d8b911c1.png)

Then I click on the All tab I see

![image](https://user-images.githubusercontent.com/4493366/134314899-1d37e6c6-f026-41a4-9b74-a3f240af361f.png)

So in essence the filter is still set on cybersecurirty but the content is unfiltered.

Solutions
- reset the filter
or
- keep the cybersecurity filter but display only the filtered items

**Comment by lucaderi** [comment]
Still bugged

**Comment by simonemainardi** [comment]
Please, check and make sure to have the cache cleared.

> reset the filter

This is the implemented behavior.

![image](https://user-images.githubusercontent.com/3397663/136180737-c092fc79-c3c2-4afb-98f2-4959bb2da0fe.png)

Then clicking on "All" yields

![image](https://user-images.githubusercontent.com/3397663/136180777-31fd6173-fc15-41d5-ad84-9f6b2f1ce431.png)

**Comment by lucaderi** [comment]
Cache cleaned up, tested on Chrome, stlll bugged

**Comment by lucaderi** [comment]
Verified as fixed
