### ISSUE TITLE
nprobe problems

### ISSUE THREAD

**Issue by gengzhi1024** [ntop/ntopng#592]
The license works, however, when load the nprobe, core dump happened.

(gdb) bt
#0  0x00007fc5303a7a03 in _IO_vfprintf_internal (s=s@entry=0x7ffc9a273490,

```
format=<optimized out>,
format@entry=0x7fc530f36240 "Unable to enable plugin %s [%s]: %s",
ap=ap@entry=0x7ffc9a273638) at vfprintf.c:1661
```
#1  0x00007fc5303ce579 in _IO_vsnprintf (

```
string=0x7ffc9a2738f0 "Unable to enable plugin DHCP Protocol [/etc/nprobe.license.dhcp]: ", maxlen=<optimized out>,
format=0x7fc530f36240 "Unable to enable plugin %s [%s]: %s",
args=0x7ffc9a273638) at vsnprintf.c:119
```
#2  0x00007fc530e353a0 in traceEvent ()

   from /usr/local/lib/libnprobe-7.3.160522.so
#3  0x00007fc530e25426 in ?? () from /usr/local/lib/libnprobe-7.3.160522.so
#4  0x00007fc530e23af3 in loadPlugins ()

   from /usr/local/lib/libnprobe-7.3.160522.so
#5  0x000000000040fb6e in ?? ()
#6  0x0000000000418190 in ?? ()
#7  0x00007fc53037dec5 in __libc_start_main (main=0x417be5, argc=1,

```
argv=0x7ffc9a275648, init=<optimized out>, fini=<optimized out>,
rtld_fini=<optimized out>, stack_end=0x7ffc9a275638) at libc-start.c:287
```
#8  0x00000000004051a9 in ?? ()

**Comment by lucaderi** [comment]
We fixed this bug days ago. Please use a more recent probe version. In case of bug. please file it under nprobe not ntopng
