### ISSUE TITLE
Report MAC address Traffic Information

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5920]
When the interface is set based on MAC addresses

![Screenshot 2021-09-23 at 11 50 24](https://user-images.githubusercontent.com/4493366/134487410-e2864e5d-cceb-4095-88fc-6a051f68859b.png)

the icon on the MAC menubar is missing

![Screenshot 2021-09-23 at 11 50 15](https://user-images.githubusercontent.com/4493366/134487415-81c24903-258e-4058-a816-9c4254d1f727.png)

and it can be retrieved clicking on Host associated to the Mac.

This ticket is to request the implementation of chart in the Mac menubar to avoid clicking into several links
****

**Comment by lucaderi** [comment]
Still bugged

**Comment by lucaderi** [comment]
Clicking on the char icon I receive this error
30/Sep/2021 12:13:29 [LuaEngine.cpp:1219] WARNING: Script failure [/Users/deri/network/ntopng/scripts/lua/rest/v2/get/timeseries/ts.lua][...network/ntopng/scripts/lua/rest/v2/get/timeseries/ts.lua:155: attempt to index a nil value (local 'res')]

**Comment by MatteoBiscosi** [comment]
I was able to reproduce this behavior and fix it. Note that more then 15 min are required to create the traffic timeseries, so if `No Data Available` is present in the page then maybe you need to wait a bit more of time.

**Comment by lucaderi** [comment]
Verified as fixed
