### ISSUE TITLE
Dashboard data view uncleared 

### ISSUE THREAD

**Issue by Niklasr69** [ntop/ntopng#5921]
In the dashboard you have the following view, se attachment
I would interpret it as that interface 5557 and OP 1235  have a throughput 733M / 1.5 G with number of flows 1.9k etc.
![dashboard_1](https://user-images.githubusercontent.com/26242302/134618972-66d54ac8-3dd4-40cd-b644-a964d8656122.PNG)

But this is really all traffic on interface 5557
I would also like to be able to see the throughput and number of flows etc only for an OP in the dashboard

**Comment by MatteoBiscosi** [comment]
We decided to remove the observation point from the traffic dashboard and keep them only for the flows page in order to avoid these types of misurunderstanding
