### ISSUE TITLE
All probes can be selected when filtering,even if they belong to another OP in flows view

### ISSUE THREAD

**Issue by Niklasr69** [ntop/ntopng#5923]
In an OP only the probes that belongs to this OP should show up when filtering.

**Comment by NicoMaio** [comment]
Hi @Niklasr69,

What page are you referring to?

**Comment by Niklasr69** [comment]
Hi Nico,

If many flow exporters have been configured, it can be good to divided into in a number of OPs
Example:
In Flows=>live page:
Choose OP1

![image](https://github.com/ntop/ntopng/assets/26242302/6923c5d9-af7f-4528-bb98-9a86c9bc547f)

Then filter out a flow-exporter

![image](https://github.com/ntop/ntopng/assets/26242302/a8df28e0-e379-4a1c-97a7-8913fdfd0a2b)

In this filter list, all exporters shows, even if they belong to another OP.
So it should be good if the list only have the exporters from the OP you have chosen.

**Comment by NicoMaio** [comment]
Hi @Niklasr69,

What is the version of your ntopng?

**Comment by Niklasr69** [comment]
Hi Nico,
It seems to work with version v.5.7.230601.
The issue can be closed.

**Comment by NicoMaio** [comment]
Verified the implementation.
