### ISSUE TITLE
nothing displayed in "Top Application Traffic Last Day View" on Dashboard

### ISSUE THREAD

**Issue by MarcoPamio** [ntop/ntopng#593]
Nothing is displayed,
![image](https://cloud.githubusercontent.com/assets/17720114/15672592/d90e15a4-2731-11e6-8004-39494176db32.png)

**Comment by simonemainardi** [comment]
It take some time to show the first data points. Note that application stats are collected every 5 minutes. So please allow ntopng enough time.

**Comment by simonemainardi** [comment]
@MarcoPamio any news?

**Comment by simonemainardi** [comment]
solution given. no feedback received. closing.
