### ISSUE TITLE
Add country information to alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5934]
Similar to what happens in all ntopng pages, it is requested to add the country flag next to host IPs. In the future, a world host map would be also desirable.

**Comment by MatteoBiscosi** [comment]
for both, host and flow alerts have been added the country flag like in the flow page.
![Screenshot from 2021-11-17 16-37-12](https://user-images.githubusercontent.com/49585191/142231732-ef4ed42d-07ce-4712-b71b-17766833c759.png)

**Comment by simonemainardi** [comment]
This change is causing all tests to fail. Please, check an update tests accordingly.

**Comment by lucaderi** [comment]
![image](https://user-images.githubusercontent.com/4493366/144027296-377781fd-ca13-4fc8-8d56-aebb98ac345a.png)
Not yet working

**Comment by lucaderi** [comment]
verified as fixed
