### ISSUE TITLE
Script failure

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5936]
29/Sep/2021 17:33:01 [LuaEngine.cpp:560] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/second.lua][attempt to index a function value]
29/Sep/2021 19:14:00 [LuaEngine.cpp:560] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/notifications.lua][/var/lib/ntopng/plugins0/alert_endpoints/sqlite.lua:94: attempt to index a nil value (local 'alert')]
29/Sep/2021 19:17:01 [LuaEngine.cpp:560] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/second.lua][/usr/share/ntopng/scripts/lua/modules/locales_utils.lua:45: attempt to call a string value (local 'chunk')]
29/Sep/2021 19:48:01 [LuaEngine.cpp:560] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/second.lua][attempt to index a function value]

Issue reported with version of Sept 29th

**Comment by simonemainardi** [comment]
Should be fixed in the latest dev.

**Comment by lucaderi** [comment]
Not able to reproduce it, closing for now
