### ISSUE TITLE
System Endpoints Don't Work

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5937]
Define an endpoint as follows
![Screen Shot 2021-09-29 at 18 07 28](https://user-images.githubusercontent.com/4493366/135306947-4a20739a-6c00-4a19-9fcf-371d3c543cee.png)

Add it to the system pool, then trigger an event (e.g. reload a list)
![Screen Shot 2021-09-29 at 18 13 29](https://user-images.githubusercontent.com/4493366/135307935-3b355585-919f-4654-bcdd-93642db186ba.png)

No message is delivered to the endpoint despite the fact an alert is generated

**Comment by simonemainardi** [comment]
notification categories were missing

![image](https://user-images.githubusercontent.com/3397663/135309502-b89cbb93-25b4-407f-b39c-e4a90c370b9f.png)

**Comment by lucaderi** [comment]
Still not working when setting the category system

**Comment by lucaderi** [comment]
Unable to test due to #5968

**Comment by lucaderi** [comment]
I have manually reloaded an element on 194.... to which you have access. I see no alert triggered even though I have moved the severity for the recipient/endpoint to info. However, I see alert drops so I cannot guarantee the behaviour is the one I see (no alert) due to alert drop.
So @simonemainardi if you are confident this bug is fixed, please close this ticket. The #5968 issue is still open, however.
