### ISSUE TITLE
Add Poll User Number

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5938]
In the image below
![Screen Shot 2021-09-29 at 18 15 09](https://user-images.githubusercontent.com/4493366/135308218-9ef81c88-cc75-45ff-af86-4741a40205d1.png)
nowhere is indicate the number of users for a recipient/endpoint.

This is to request to add a small badge indicating the number of users. When such a number is zero the badge has to be red to notify the problem.

**Comment by MatteoBiscosi** [comment]
To clarify the usage of endpoints/recipients I added an alert red badge if an endpoint has no recipients.
![Screenshot from 2021-10-05 14-06-25](https://user-images.githubusercontent.com/49585191/136019800-5c877693-13a2-44ef-bc14-fcc4942c54b7.png)

At the same time, I added some extra information to the recipients page, in this way a user is going to understand if the recipients is being used, for which severity alert and if it is bound to some pools, if not a red alert badge is going to appear
![Screenshot from 2021-10-05 13-10-10](https://user-images.githubusercontent.com/49585191/136020038-4d69fad9-cbf9-434a-a615-7a79d9b2d5f5.png)

Other then this information, unfortunately it is not possible to know which user is using the recipient and how many users are using them

**Comment by lucaderi** [comment]
Verified as fixed
