### ISSUE TITLE
Reverse DNS lookups unreliable

### ISSUE THREAD

**Issue by hatclub** [ntop/ntopng#594]
ntopng seems to be very poor at completing reverse dns lookups; even if I open a host detail page which appears to attempt to run the reverse lookup again based on the pinwheel that appears, the IP is not replaced with the hostname. 

![reverse](https://cloud.githubusercontent.com/assets/5437917/15679454/d14738ec-2749-11e6-8a6a-46ebc1c53344.png)

There doesn't appear to be any rhyme or reason to what it will and won't succeed at looking up; it's not even reliable with resolving local hosts.

I've checked that /etc/resolv.conf has our resolvers (it does) and that both are working (they are) and that if I do (using the IP in the above screenshot as an example) "dig PTR 115.209.230.213.in-addr.arpa @<our resolver IPs>" it works (it does).

Is there anything else to check/twiddle to improve this?

**Comment by simonemainardi** [comment]
I've just tried to reproduce the issue. I am able to get the proper name either by command line or from within ntopng.

![image](https://cloud.githubusercontent.com/assets/3397663/16335412/b5d1a262-3a06-11e6-9af7-e8b1b45a91d0.png)

Resolution is immediate, no delays.

For the sake of completeness, I also enclose the recorded PTR ip to name resolution for the ip mentioned as a pcap file: [pcap-dns-PTR-req-reply.pcapng.zip](https://github.com/ntop/ntopng/files/331608/pcap-dns-PTR-req-reply.pcapng.zip)

So you should double check that your resolvers are actually able to get you to the proper name. I noticed you specified an @ in the dig command. This suggests me you were asking to a 'custom' resolver that you removed before pasting the command.

**Comment by hatclub** [comment]
I was using @ and copied it by accident here, but I was only specifying each of the resolvers configured in /etc/resolv.conf to prove to myself that they were both responding.

root@ntop:~# dig PTR 10.218.230.213.in-addr.arpa @213.230.211.71

; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> PTR 10.218.230.213.in-addr.arpa @213.230.211.71
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59309
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;10.218.230.213.in-addr.arpa.   IN      PTR

;; ANSWER SECTION:
10.218.230.213.in-addr.arpa. 86400 IN   PTR     wan.office.netcalibre.net.

;; Query time: 2 msec
;; SERVER: 213.230.211.71#53(213.230.211.71)
;; WHEN: Fri Jun 24 15:07:50 BST 2016
;; MSG SIZE  rcvd: 95

root@ntop:~# dig PTR 10.218.230.213.in-addr.arpa @213.230.211.70

; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> PTR 10.218.230.213.in-addr.arpa @213.230.211.70
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23724
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;10.218.230.213.in-addr.arpa.   IN      PTR

;; ANSWER SECTION:
10.218.230.213.in-addr.arpa. 70902 IN   PTR     wan.office.netcalibre.net.

;; Query time: 1 msec
;; SERVER: 213.230.211.70#53(213.230.211.70)
;; WHEN: Fri Jun 24 15:07:54 BST 2016
;; MSG SIZE  rcvd: 95

root@ntop:~# cat /etc/resolv.conf
nameserver 213.230.211.70
nameserver 213.230.211.71

Is this perhaps a problem of scale? I have 60k hosts after 30s - 480k after 10min.

I'm looking at ngrep and requests aren't going out all that quickly - is DNS resolution single-threaded?

EDIT: Have repeatedly tried to get markdown to treat my cut and paste as code rather than a comment but it seems it's not going to happen.

**Comment by lucaderi** [comment]
Yes it's definitively a scaling issue. Please consider -b 2

[--dns-mode|-n] <mode>              | DNS address resolution mode
                                    | 0 - Decode DNS responses and resolve
                                    |     local numeric IPs only (default)
                                    | 1 - Decode DNS responses and resolve all
                                    |     numeric IPs
                                    | 2 - Decode DNS responses and don't
                                    |     resolve numeric IPs
                                    | 3 - Don't decode DNS responses and don't
                                    |     resolve numeric IPs

**Comment by hatclub** [comment]
Can't you plan to make DNS resolution multi-threaded?

If we turn it to -b 2 we presumably won't have any DNS at all in the interface (undesirable, frankly) as we're not using port mirroring (which is presumably required for -b 2 to see any DNS responses to decode), we're using netflow.

**Comment by lucaderi** [comment]
If you have 30k addresses to resolve, the three with make the situation even worse as it might create a waterfall effect if not a DoS on your DNS. For the time being I would like to leave everything as is. This said the DNS resolution is multithreaded and we currently use 2 thread. If you are willing to try go to https://github.com/ntop/ntopng/blob/dev/include/ntop_defines.h and redefine CONST_NUM_RESOLVERS

**Comment by hatclub** [comment]
Okay; any chance that UI-prompted resolves could use a separate thread so that if someone drills down on a host in the UI that will always work even if the main resolver processes are busy?

I'll have to set some time aside for building it by hand - any chance the CONST_NUM_RESOLVERS could be brought out to a config option to allow for runtime changes? It can have a caveat attached about exercising caution.
