### ISSUE TITLE
SNMP Polling stuck

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5942]
<img width="1344" alt="Screenshot 2021-09-30 at 13 03 05" src="https://user-images.githubusercontent.com/4493366/135443840-09595f6f-8729-4552-b315-f42725f1e73b.png">

This can be reproduced with SNMPv1 in our lab

**Comment by simonemainardi** [comment]
Seems to work as expected.

![image](https://user-images.githubusercontent.com/3397663/136180045-d4a35162-62cc-469d-802b-5c4ab907a2e3.png)

Can you provide extra details?

**Comment by lucaderi** [comment]
Seems to work now will reopen if necessary
