### ISSUE TITLE
Dashboard - network interfaces last day view all the time zero

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5943]
Hello ntop Team!
The last day view graph on the dashboard is all the time zero:
<img width="378" alt="Screenshot 2021-09-30 at 14 19 35" src="https://user-images.githubusercontent.com/38549755/135454663-8161833e-1bc0-4173-82c6-c72e693335fb.png">
Thanks

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu, can you please tell me your ntopng --version and ntopng configuration? in this way I'll try to reproduce this behavior

**Comment by martinscheu** [comment]
Hi @MatteoBiscosi yes sure. the version: 
Version:	5.1.210929 [Enterprise/Professional build]
GIT rev:	dev:d0fbfa8e1253e15d00541100526852431dd0e322:20210929
Pro rev:	r4251
Built on:	Ubuntu 20.04.3 LTS

what do you mean by configuration?
on that host we have 3 NICs, one management and 2 mirror ports

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu could you please check the interface traffic timeseries (they should be the same)?
![Screenshot from 2021-09-30 16-01-06](https://user-images.githubusercontent.com/49585191/135470930-9316af13-96d0-45c7-8ed1-49bb0b2af2b3.png)

**Comment by martinscheu** [comment]
Hi @MatteoBiscosi, that might be the problem, I get an error:
<img width="520" alt="Screenshot 2021-09-30 at 21 11 49" src="https://user-images.githubusercontent.com/38549755/135516549-31aeacfa-7fd4-4e42-8fe6-aae2e58c7f38.png">

**Comment by martinscheu** [comment]
ist that a performance issue of the box we are running ntopng on it?

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu is the problem fixed after the fixed issue of the last week?

**Comment by martinscheu** [comment]
in my instances it is fixed @MatteoBiscosi, I close the issue
