### ISSUE TITLE
Script Failure

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5945]
2021-09-30 22:00:00.197823+0200 ntopng[17680:269330] [LuaEngine.cpp:560] WARNING: Script failure [/Users/deri/network/ntopng/scripts/callbacks/system/hourly.lua][...finitions/flow/alert_ndpi_tls_cert_validity_too_long.lua:8: attempt to index a nil value (global 'dirs')]
30/Sep/2021 22:00:00 [LuaEngine.cpp:560] WARNING: Script failure [/Users/deri/network/ntopng/scripts/callbacks/system/hourly.lua][...finitions/flow/alert_ndpi_tls_cert_validity_too_long.lua:8: attempt to index a nil value (global 'dirs')]
30/Sep/2021 21:55:02 [LuaEngine.cpp:560] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/notifications.lua][/var/lib/ntopng/plugins0/alert_endpoints/sqli\
te.lua:94: attempt to index a nil value (local 'alert')]
30/Sep/2021 21:56:01 [LuaEngine.cpp:560] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/notifications.lua][/var/lib/ntopng/plugins0/alert_endpoints/sqli\
te.lua:80: attempt to index a number value (local 'notification')]
30/Sep/2021 22:00:00 [LuaEngine.cpp:560] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/hourly.lua][...s/lua/modules/alert_definitions/flow/alert_flow_r\
isk.lua:8: attempt to index a nil value (global 'dirs')]
30/Sep/2021 22:25:03 [LuaEngine.cpp:560] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/notifications.lua][/var/lib/ntopng/plugins0/alert_endpoints/sqli\
te.lua:94: attempt to index a nil value (local 'alert')]

**Comment by MatteoBiscosi** [comment]
duplicated of #5936
