### ISSUE TITLE
Auto alert pcap recorder

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5946]
Hi ntop Team!
For detail analysis it would be very helpful if ntopng would save a pcap around the alert, e.g. alert -5s and alert + 5s of the corresponding interface. This if a specified Alert is triggered like clear text password.
If possible to integrate with n2disk, like reserving disk space for this function. Save pcap with e.g. AlertTime+Alert+Application+FlowInfo so it can easy be correlated with alerts in ntopng.

**Comment by simonemainardi** [comment]
see https://www.ntop.org/guides/ntopng/using_with_other_tools/n2disk.html
