### ISSUE TITLE
Checks - exclude network range

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5948]
Hello ntop Team!
It would be helpful if in Checks where now I can exclude hosts by IP address from the check, also have ranges excluded, like /24.
Thank you

**Comment by ListenNjoy** [comment]
It would be very helpfull.

**Comment by fastfire** [comment]
+1

**Comment by NicoMaio** [comment]
Feature already implemented, tested with nmap on both hosts and flows alerts. Seems to be ready to test.

![Network Range Exclusion](https://user-images.githubusercontent.com/55502486/217290964-b2a2af86-0dbb-4371-9440-41ad46cca149.png)
