### ISSUE TITLE
License Issue for Educational Use

### ISSUE THREAD

**Issue by gilinuxIT** [ntop/ntopng#5949]
We are in the process of deploying 20+ instances of NTOPNG at school locations (Same School District). We had initially been given four licenses to use, however when we try and apply the license to the third server, it is not taking.  Can you assist? Thank you.

**Comment by simonemainardi** [comment]
You need to provide evidence, including an official letter from the school manager, that 20+ instances of ntopng are required. Then, my colleague Maria will check if you are eligible to get free licenses for education. Follow up with her: mallegro at ntop dot org

See https://www.ntop.org/support/faq/do-you-charge-universities-no-profit-and-research/
