### ISSUE TITLE
Disabled alerts persist in host detail page / 160531 / Ubuntu 14.04

### ISSUE THREAD

**Issue by hatclub** [ntop/ntopng#595]
I have a customer on net who does security scans which trigger the ntop flow-based alerts due to the high rate of new flows (and high number of flows) created.

I cleared all alerts from the alerts page, and told ntop not to alert for the source IP in question, but the host still shows the alert symbol in dashboard view and the host detail page still show that 80 alerts were generated.

I can understand the alert counter being kept after deleting alerts, but once I told ntop not to generate alerts for a given host, one perhaps might expect ntop to discard the "in alert" state flag and counter.

**Comment by hatclub** [comment]
Persists in 160606 (latest build on apt)

After unchecking "Host Alerts" under the cog menu item on host detail, Host Alert icon persists on dashboard and alert counter persists on Host Detail page.

Might be worth clearing all existing alerts events for a host that has alerting turned off, as well.

**Comment by simonemainardi** [comment]
@hatclub alert counters you see are those occurred before disabling the alert. Please, check that after unchecking "Host Alerts" no _new_ alerts are triggered.

**Comment by hatclub** [comment]
New alerts being triggered are #598 ; this is about the alert flag staying lit and existing alert counters persisting on a host I have told ntopng I don't want alerts for.

**Comment by hatclub** [comment]
![flag-still-lit](https://cloud.githubusercontent.com/assets/5437917/15824574/b9fb1a0c-2bf7-11e6-852a-6717654122b5.png)

Here's a screenshot of the dashboard flag I'm talking about.

**Comment by simonemainardi** [comment]
please check with the latest fix

**Comment by hatclub** [comment]
Will do as soon as it's packaged. Should I not be using packages, or do I need to wait n minutes after commit for rebuild?

**Comment by simonemainardi** [comment]
you can use the package that will be built tonight
