### ISSUE TITLE
Ntopng - Host Page Broken - hosts_stats.lua

### ISSUE THREAD

**Issue by Olokz** [ntop/ntopng#5950]
I have a problem with the NTOPNG Hosts page, it doesn't load any information.
![image](https://user-images.githubusercontent.com/23363910/135677340-ff1755cc-5136-41dd-acf3-32e2ed8b0629.png)

when restarting the service, it works again for 9 minutes, corresponding to the test period.
![image](https://user-images.githubusercontent.com/23363910/135677608-b1e42887-4762-4154-bfda-7193f32b71df.png)

ntopng Community v.5.1.211001 (Ubuntu 20.04.3 LTS)

**Comment by MatteoBiscosi** [comment]
Hi @Olokz I'm sorry for the trouble, I was able to reproduce the issue and now should be fixed. Builds are going to be ready in some hours, please update in 3/4 hours. Reopen the issue if the problem persists.

**Comment by umarnet** [comment]
Hi MatteoBiscosi,

I have the same issue as Olokz, the hosts page is broken. I've also attached a LogTrace, I'm using the below system:

ntopng Community v.4.1.0 rev.15674 (Ubuntu 20.04.3 LTS)
ntopng Community v.4.1.0 rev.15674 (FreeBSD 12.2) - pfsense 2.5.4 plus

[LogTrace.txt](https://github.com/ntop/ntopng/files/7319862/LogTrace.txt)
