### ISSUE TITLE
Alerts list - add description text filter

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5955]
Hello ntop Team!
It would be helpful to have a text filter possibility in the alerts list.
E.g. I can filter alerts k.p-n.io:
<img width="831" alt="Screenshot 2021-10-05 at 08 55 10" src="https://user-images.githubusercontent.com/38549755/135981306-94c5e901-7ff3-4ee2-8e40-245c0d783d97.png">
thank you

**Comment by simonemainardi** [comment]
Superseded by https://github.com/ntop/ntopng/issues/5961
