### ISSUE TITLE
5.1.211006 the service stops after a while

### ISSUE THREAD

**Issue by tomkolp** [ntop/ntopng#5958]
After upgrading to 5.1.211006, the Ntopng service stops after a while. OPNsense 21.7.3_3-amd64 no logs from this event. I do the update every day, yesterday there was no problem.

**Comment by martinscheu** [comment]
same here on Ubuntu 20.04, it starts, but gives errors and then doesn't run:
`06/Oct/2021 08:54:28 [NtopPro.cpp:501] [LICENSE] /etc/ntopng.license: found valid Enterprise L (Bundle) license
Failed to print the table: Broken pipe
06/Oct/2021 08:54:31 [second.lua:27] [rrd.lua:337] ERROR: rrd_update_r() [/var/lib/ntopng/2/rrd/bytes.rrd][1633503271:34872467] failed [/var/lib/ntopng/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1633503271]`

**Comment by MatteoBiscosi** [comment]
Hi @tomkolp try to upgrade and let me know if it still crashes, an important fix was done to nDPI, possibly causing your crash, currently only available for ntopng dev version.

**Comment by tomkolp** [comment]
v.5.1.211008 everything works @MatteoBiscosi

**Comment by MatteoBiscosi** [comment]
Great! I'll close the ticket, please reopen it if the issue arise again.
