### ISSUE TITLE
Hostnames unnecessarily truncated in certain views

### ISSUE THREAD

**Issue by hatclub** [ntop/ntopng#596]
Is it possible to configure the number of characters before hostnames are considered for truncation, or disable truncation (perhaps in combination with a CSS change for overflow hidden), or make truncation "smarter" (eg client side rendered) to take account of cell widths?

See the below screenshot where truncation was unnecessarily aggressive resulting in partial hostnames despite large amounts of available space (ignoring the white areas where I have redacted content, of course)

![truncation](https://cloud.githubusercontent.com/assets/5437917/15740182/a36a14cc-28ab-11e6-9a81-3186de6d0a42.png)

**Comment by hatclub** [comment]
Seeing full hostnames in an on:hover would be a bonus here too, allowing the full hostname to be seen even in views/on screens that are spaced constrained.

**Comment by basicmonkey** [comment]
This is also relevant in historical data explorer.
<img width="430" alt="Screenshot 2019-03-26 at 12 45 17" src="https://user-images.githubusercontent.com/392058/54998080-23d7af00-4fc5-11e9-9855-ce2d0c1df200.png">

**Comment by simonemainardi** [comment]
you can control this string length from the preferences

**Comment by basicmonkey** [comment]
You can indeed! Thanks for the pointer.
