### ISSUE TITLE
Implement alert search in Description

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5961]
![Screen Shot 2021-10-07 at 12 34 32](https://user-images.githubusercontent.com/4493366/136370647-735159c0-779a-40bf-86c3-cf6c4dbc710a.png)

in the above example it should be possible to filter "hello.ntop.org" os a substring (e.g. hello) in the description field

**Comment by simonemainardi** [comment]
Alert description is built ad query time from a JSON stored in the database.

To search we can:
1. Use SQLite JSON support to query straight into a JSON field of the alert (as we are considering ClickHouse support, we should verify if this will be supported)
2. Query straight into the JSON as if it was a string

Please comment on the desired solution.

**Comment by lucaderi** [comment]
Implement 2. with LIKE %XXX%

**Comment by MatteoBiscosi** [comment]
Each data in description is now searchable, because description is an aggregation of all the information
