### ISSUE TITLE
Script failures when ntopng Enterprise embedded time-limited license expires

### ISSUE THREAD

**Issue by phantomski77** [ntop/ntopng#5965]
Last two new weekly `5.1.x` versions of ntopng (`5.1.211003` and `5.1.211010`) run well in Docker when first started, defaulting to time-limited *Enterprise embedded* version. When that expires after 10 minutes and ntopng instance degrades to free license, these script failure errors are produced repeatedly:
```
10/Oct/2021 19:05:00 [AlertCheckLuaEngine.cpp:75] WARNING: Script failure[/usr/share/ntopng/scripts/callbacks/system/system.lua] [error loading module 'fail2ban_alert_endpoint' from file '/var/lib/ntopng/plugins0/http_lint/fail2ban_alert_endpoint.lua':
	...ib/ntopng/plugins0/http_lint/fail2ban_alert_endpoint.lua:1: unexpected symbol near '<\135>']
10/Oct/2021 19:05:00 [LuaEngine.cpp:560] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/minute.lua][error loading module 'fail2ban_alert_endpoint' from file '/var/lib/ntopng/plugins0/http_lint/fail2ban_alert_endpoint.lua':
	...ib/ntopng/plugins0/http_lint/fail2ban_alert_endpoint.lua:1: unexpected symbol near '<\135>']
10/Oct/2021 19:05:00 [LuaEngine.cpp:560] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/interface/5min.lua][error loading module 'fail2ban_alert_endpoint' from file '/var/lib/ntopng/plugins0/http_lint/fail2ban_alert_endpoint.lua':
	...ib/ntopng/plugins0/http_lint/fail2ban_alert_endpoint.lua:1: unexpected symbol near '<\135>']
10/Oct/2021 19:05:00 [LuaEngine.cpp:560] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/interface/minute.lua][error loading module 'fail2ban_alert_endpoint' from file '/var/lib/ntopng/plugins0/http_lint/fail2ban_alert_endpoint.lua':
	...ib/ntopng/plugins0/http_lint/fail2ban_alert_endpoint.lua:1: unexpected symbol near '<\135>']
10/Oct/2021 19:05:26 [LuaEngine.cpp:1219] WARNING: Script failure [/usr/share/ntopng/scripts/lua/http_status_code.lua][error loading module 'elasticsearch_alert_endpoint' from file '/var/lib/ntopng/plugins0/http_lint/elasticsearch_alert_endpoint.lua':
	...opng/plugins0/http_lint/elasticsearch_alert_endpoint.lua:1: unexpected symbol near '<\135>']
10/Oct/2021 19:05:27 [LuaEngine.cpp:1219] WARNING: Script failure [/usr/share/ntopng/scripts/lua/http_status_code.lua][error loading module 'fail2ban_alert_endpoint' from file '/var/lib/ntopng/plugins0/http_lint/fail2ban_alert_endpoint.lua':
	...ib/ntopng/plugins0/http_lint/fail2ban_alert_endpoint.lua:1: unexpected symbol near '<\135>']
```

These errors were not produced by any previous `5.1.x` versions, since `5.1` was released and ntopng was running well without any issues. When I restart the container, it runs well again, until the license expires.

**HW**: Raspberry Pi 4 Model B Rev 1.4 (8GB)
**CPU**: Broadcom [BCM2711](https://datasheets.raspberrypi.org/bcm2711/bcm2711-peripherals.pdf) (ARM Cortex-A72 - arm64v8A)
**Kernel**: Linux 5.11.0-1019-raspi
**OS**: Ubuntu 21.04 aarch64
**Docker**: 20.10.9 CE linux/arm64

**Comment by MatteoBiscosi** [comment]
Hi @phantomski77  please currently if you don't have a license, run ntopng using `--community` option, in the meantime I'll fix the issue

**Comment by phantomski77** [comment]
> Hi @phantomski77 please currently if you don't have a license, run ntopng using `--community` option, in the meantime I'll fix the issue

Thanks, that helped.

**Comment by simonemainardi** [comment]
This issue has been fixes in the latest build. Please, update and reopen if necessary.

**Comment by phantomski77** [comment]
I can confirm this has been fixed in `211024`. Tested and behaves well as the previous versions.
Thank you!
