### ISSUE TITLE
Hosts page not loading

### ISSUE THREAD

**Issue by rmancuso40** [ntop/ntopng#5967]
My Hosts page stopped loading (just blank page), I am assuming after a recent update, on my Raspberry PI OS installation. It was working fine for several months. The contributing error in the log looks like:

11/Oct/2021 07:44:48 [LuaEngine.cpp:1219] WARNING Script failure [/usr/share/ntopng/scripts/lua/hosts_stats.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:621: module 'snmp_cached_dev' not found: no field package.preload['snmp_cached_dev'] no file ....

The only snmp_cached_dev.lua on my system is in /usr/share/ntopng/pro/scripts/lua/modules but I have the --community option set for community edition. Any suggestions?

**Comment by rmancuso40** [comment]
Looks like this change "Fixes nil snmp_cached_dev value" in lua_utils committed on Oct 5 is the issue. I commented out the new line from that change (local snmp_cached_dev = require "snmp_cached_dev") and my Hosts page is now working.

**Comment by MatteoBiscosi** [comment]
Hi @rmancuso40 I was able to reproduce this issue and fix it, soon a new build is going to be ready with this fix, thanks for your report and help

**Comment by lucaderi** [comment]
Working for me
