### ISSUE TITLE
List reload broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5968]
I manually triggered a reload

![Screen Shot 2021-10-11 at 15 16 37](https://user-images.githubusercontent.com/4493366/136796727-dc553662-edf9-4c04-a079-051166b3b26d.png)

but the reload is not happening 
![Screen Shot 2021-10-11 at 15 17 41](https://user-images.githubusercontent.com/4493366/136796721-837a6167-264c-4e99-87f5-5e574fac12ba.png)

**Comment by simonemainardi** [comment]
Do you see any errors in the console? I am unable to reproduce this behavior.

**Comment by lucaderi** [comment]
Yes this behaviour is still broken in MacOS but it works on Linux.

**Comment by simonemainardi** [comment]
I get proper updates using the latest build.

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/3397663/139212523-5d226a30-4335-471a-94c3-e2968e5e7605.png">

Report the following:
- Are you running the packaged version?
- Are you running ntopng as root (e.g., --dont-change-user) or as unprivileged user?
- If running as unprivileged user, give details about how you've created the user

**Comment by lucaderi** [comment]
Verified as fixed
