### ISSUE TITLE
Invalid view menu switch

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5969]
Start ntopng as
- ntopng -i tcp://127.0.0.1:1234 -i view:all
and nProbe as
- nprobe -i eth1 -t 3 -d 3 --zmq tcp://127.0.0.1:1234
Then go to the dashboard page. This is what you see (correct). 

![Screen Shot 2021-10-11 at 15 47 27](https://user-images.githubusercontent.com/4493366/136801175-fa372851-5362-4194-ba87-15fa11cca483.png)

Then go to Hosts
![Screen Shot 2021-10-11 at 15 47 37](https://user-images.githubusercontent.com/4493366/136801189-c02e7b9c-b0b8-4e1d-82bb-39d316ea6141.png)
and as you can see the interface name switched. This is a bug

**Comment by MatteoBiscosi** [comment]
Hi @lucaderi, I'm sorry but I'm unable to reproduce the problem, please check the console tab on the web developers tools and let me know if some problems are reported there when you are able to reproduce this issue

**Comment by lucaderi** [comment]
After cache cleanup, it seems to work. Closing for now but I have the feeling it will appear again
