### ISSUE TITLE
Hosts dashboard is blank

### ISSUE THREAD

**Issue by tomukasteris** [ntop/ntopng#5975]
Hello,

In some reason dashboard for All Hosts, Local Hosts and Remote Hosts doesn't display any entries.

Everything was working fine before. I can see all active flows but not hosts.

ntopng version: ntopng Community v.5.1.211011 rev.15683 (Ubuntu 20.04.3 LTS)

![ntopng_1](https://user-images.githubusercontent.com/11430578/136839418-c4f3c703-d2c5-402c-971b-5bced10debd7.png)
![ntopng_2](https://user-images.githubusercontent.com/11430578/136839524-c367c054-9493-4274-ba28-0fa9ce6cc7a0.png)

**Comment by MatteoBiscosi** [comment]
Hi @tomukasteris I did a fix yesterday evening, please update and let me know if everything works fine. For more info see #5967
