### ISSUE TITLE
Base URL ignored

### ISSUE THREAD

**Issue by gianlucapiccolo** [ntop/ntopng#5976]
Hi, I'm experiencing some problems related to the base URL after the upgrade to ntopng 5.
It seems that in the following cases the base URL "/ntopng" that I set with the http-prefix param in the configuration is not working:

1. SNMP loading forever (https://172.18.0.2/ntopng/lua/pro/enterprise/snmpdevices_stats.lua): the list is always showing the loading text, if we check the console, there is a resource "/lua/pro/enterprise/get_snmp_devices_list.lua" that is called without prepending the base URL. 
![snmp](https://user-images.githubusercontent.com/2795394/136915980-72758ae4-6c8c-41a4-a87b-6276361eb40d.png)
2. Historical flow exporter loading forever (https://172.18.0.2/ntopng/lua/pro/nindex_query.lua): the table is showing the loading forever, there is a resource "/lua/pro/rest/v2/get/host/flows/flows_info.lua" that is called without prepending the base URL.
![Screenshot from 2021-10-12 10-10-51](https://user-images.githubusercontent.com/2795394/136917897-f15e8315-d072-493f-82f3-738db16ceefe.png)
3. Alerts loading forever (https://172.18.0.2/ntopng/lua/alert_stats.lua): the table is showing the loading forever, there is a resource "https://172.18.0.2/lua/rest/v2/get/all/alert/list.lua" hat is called without prepending the base URL.
![Screenshot from 2021-10-12 10-38-18](https://user-images.githubusercontent.com/2795394/136922184-b7323c3c-363d-4b90-8976-663511ff776e.png)
4. Probes Observation points dropdown menu linking to the page without base URL (/?ifid=0&observationPointId=1235). 
![obs-points](https://user-images.githubusercontent.com/2795394/136924458-a4e0009b-333b-4e53-8dea-65a9d9a558f4.png)

Please tell me if something is not clear or if you have problems to reproduce it.

**Comment by MatteoBiscosi** [comment]
Hi @gianlucapiccolo thanks for your report a new build is going to start soon and in a few hours a new update with the fixes is going to be available. Regarding the switch between endpoints the issue should be already fixed. Please in a few hours update and let me know

**Comment by gianlucapiccolo** [comment]
@MatteoBiscosi thanks @MatteoBiscosi for the fast answer, which kind of build? nightly or stable?

**Comment by lucaderi** [comment]
Verified as fixed
