### ISSUE TITLE
incoming / outgoing interface as columns (same as on real time flows) in historical flow explorer” page

### ISSUE THREAD

**Issue by Niklasr69** [ntop/ntopng#5978]
When using nIndex for “historical flow explorer” page, it should be very good if incoming / outgoing interface where available as a selectable columns. i.e for each flow you can also see the interface

**Comment by Niklasr69** [comment]
Any roadmap when this feature can be impl in clickhouse?

**Comment by cardigliano** [comment]
Input/output SNMP interface (ID) added to the historical flows (pro 8798824b0a1d81144128a867cd3ff5c4ed288748)

**Comment by Niklasr69** [comment]
The output/interface SNMP ID works for history.
Unfortunately, it is difficult to know the real interface name when using SNMP ID.
It would be much more manageable if you had the real interface names.
[https://github.com/ntop/ntopng/issues/5953](url)

**Comment by Niklasr69** [comment]
Looks very good know ([ntopng Enterprise L v.5.3.220318]).
Something that can be removed is the exporter IP addresses in SNMP interface column.
The exporter is already in an own column.
Marked with red in the picture.

![image](https://user-images.githubusercontent.com/26242302/158940577-505603ff-51ba-4889-b716-5135c772c25b.png)

**Comment by Niklasr69** [comment]
Is it possible to add the real interface also in the filter part?
I.E after the SNMP ID the real interface name is showed (same as in table).

![image](https://user-images.githubusercontent.com/26242302/159224812-8da5df44-4913-45e6-8f02-43d27c3d75fc.png)

**Comment by Niklasr69** [comment]
Any updates?

**Comment by cardigliano** [comment]
This has been implemented (testing)
<img width="1191" alt="Screen Shot 2022-04-08 at 17 53 40" src="https://user-images.githubusercontent.com/7548711/162478340-0bcdf304-8f6c-4070-bfa5-0f58d686834b.png">

**Comment by Niklasr69** [comment]
If you have a lot of exporters, it should work better if you first must choose an exporter in a drop down (#6534).
When chose interface filter, only the interface for the specific export should be in the drop down.

**Comment by cardigliano** [comment]
@Niklasr69 this requires quite some changes to the filter dialog as we do not have a component for a double selection at the moment, we will consider implementing this in future

**Comment by Niklasr69** [comment]
@cardigliano
okay, so you mean that is not possible today to only get the interfaces from the filtered exporter?

**Comment by lucaderi** [comment]
@cardigliano Can you please update the ticket status?

**Comment by cardigliano** [comment]
Using a single dropdown or a 2-step selection is equivalent. Since the latter cannot be implemented with the current component I would keep using the single dropdown to avoid wasting time for a new component, if it's not really required.

**Comment by Niklasr69** [comment]
Hi,
@cardigliano
CC: @lucaderi  
As we soon will have over 100 exporters and more will be added, it is very hard do find a specific interface.
I think it can work with the existing implementation if exporters IP address could be replaced by hostname.
Then it's easy to roll down to right exporter.

![image](https://user-images.githubusercontent.com/26242302/170919090-806320e9-f4fb-416a-ab4d-2a21b0a7df35.png)

**Comment by MatteoBiscosi** [comment]
Hi, in the latest ntopng version the dropdown has a search, in this way even if there are a lot of entries, users (if they know what to search) are able to find fast the in/out SNMP interfaces.
Implemented as requested.
Please reopen if this search is not enough
