### ISSUE TITLE
See ip-probe names as well, not just IP in historical flow explorer page

### ISSUE THREAD

**Issue by Niklasr69** [ntop/ntopng#5979]
The "historical flow explorer" page ip-probe column should also show hostname.

**Comment by MatteoBiscosi** [comment]
Hi @Niklasr69 feature implemented as requested, as you can see in the screenshot below. To know the flow exporter IP (like for all the other ips into the Historical Flow Explorer page, just stay on the name and the ip is going to show up as a tooltip.
![Screenshot from 2021-10-14 10-56-53](https://user-images.githubusercontent.com/49585191/137285512-5a23f96a-2d7f-4b3f-897c-c093160bb9dc.png)
Please when the new builds are ready update and let me know if everything works fine.

**Comment by Niklasr69** [comment]
Hi, 
Is working perfect
//Niklas

**Comment by MatteoBiscosi** [comment]
Great! thanks for your report.
