### ISSUE TITLE
ntopng is still generating alerts for a host that has alerts disabled

### ISSUE THREAD

**Issue by hatclub** [ntop/ntopng#598]
As per #595 I disabled alerts in the host view for a given IP for a host that is known to generate flooder alerts

When I looked at the dashboard today I saw fresh alerts for the IP that had alerting disabled (the total number of alerts has now climbed from 80 to 156).

I double checked the host details - alerting is still disabled (unchecked) for this host.

**Comment by lucaderi** [comment]
What ntopng version are you using? Did you try the latest 2.3.160602 version?

**Comment by hatclub** [comment]
Now upgraded to 160603; sorry, I'm not used to a branch that shifts this frequently, so I'll make sure we upgrade more aggressively - I did have a look in the recent changelog and nothing stuck out as relevant though.

We might not know if this is fixed until next week, though - I don't think they're actively scanning at the moment. Will let you know what happens.

**Comment by simonemainardi** [comment]
please update to the latest dev build. We have made a fix.

**Comment by hatclub** [comment]
Hi @simonemainardi - thanks - as soon as it's packaged I'll give it a whirl. 160603 is still the newest on apt.

**Comment by lucaderi** [comment]
@hatclub just updated (160603)
