### ISSUE TITLE
Possibility to customize the order of the columns in the history page

### ISSUE THREAD

**Issue by Niklasr69** [ntop/ntopng#5981]
Possibility to customize the order of the columns in the history page when using nIndex

**Comment by MatteoBiscosi** [comment]
Hi @Niklasr69 I already tried to implement your suggestion some times ago, however with the current javascript library we are using (we do not plan to change it in the following time if no problem arise) it's not possible to implement your request.
I'm going to close the issue, if we are going to change the js library then I'm going to reopen the ticket.
Thanks a lot for your suggestion

**Comment by MatteoBiscosi** [comment]
The suggestion i give you is to just select the column you are interested about by selecting/deselecting the columns here
![Screenshot from 2021-10-14 10-32-18](https://user-images.githubusercontent.com/49585191/137281172-9f3cad06-82fa-4d03-a08d-894388cb34bb.png)
Thanks again for your suggestion.

**Comment by Niklasr69** [comment]
Hi Matteo,
Thanks for the information, is not so important.
Q:
Is it possible to the rest of the columns that is not on the screen?

BR Niklas
