### ISSUE TITLE
Implement All Preset in Alerts Page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5991]
![Screen Shot 2021-10-16 at 11 08 48](https://user-images.githubusercontent.com/4493366/137581754-d5d427ee-54bb-4a2d-926e-55abb0b4baf5.png)

The time preset is helpful with live traffic, but with pcap traces (often captured years ago) it is not. This is to request to add a new entry "All" (or call it as you like) that includes all alerts recorded in ntopng

**Comment by simonemainardi** [comment]
When processing a pcap, alerts are timestamped with the current time even if they preserve the real flow first / last seen. Adding an "All" will basically equal the "Last 30 mins".

What we can do, in case of pcaps, is to query the timestamp of the oldest alert inserted and forcefully set the begin time to this timestamp, while leaving the end time to the current time.

Please, explain if this solution is satisfactory.

**Comment by lucaderi** [comment]
Verified as fixed
