### ISSUE TITLE
RDP-streams source-destination interchanged for RDP 7.1

### ISSUE THREAD

**Issue by StrilGit** [ntop/ntopng#5992]
Hi!

Setup: SFlow-Switch -> nProbe 9.7.211006 > ntopng 5.1.211006 (all Enterprise L)

For RDP sessions with windows-clients for RDP <v8, I am seeing a strange issue.
While for RDP >=8, I am seeing flows:
Client -> Server:3389 (up and download)
RDP <8 shows:
Server:3389 -> Client (up and download)

Example with RDP 7.1:
![image](https://user-images.githubusercontent.com/42024990/137680601-0b0bc686-e312-490b-98a3-c0bf548193f1.png)

Is there anything, I can do to solve this?
Thank you and best wishes
Stril

**Comment by lucaderi** [comment]
sFlow is a sampled technology so we see a packet in X, meaning that we do not see the beginning of the connection. What you are asking is to manually revert the connection direction as we do with DNS. @simonemainardi Can you implement this?

**Comment by martinscheu** [comment]
we see same behavior in NTP, server is marked as Client, Client as server:

<img width="1041" alt="Screenshot 2021-10-19 at 09 35 54" src="https://user-images.githubusercontent.com/38549755/137864357-86b2f84c-e109-4858-b7ea-a00f36d25ea7.png">
:

**Comment by simonemainardi** [comment]
@StrilGit please provide an sFlow pcap with which I can reproduce the behavior. Swap should have already been implemented so there may be something with your sFlow that hasn't been handled. Please, send privately at mainardi at ntop dot org

**Comment by simonemainardi** [comment]
No feedback received. Reopen with the requested information if necessary.
