### ISSUE TITLE
Email notifications not working

### ISSUE THREAD

**Issue by deanfourie1** [ntop/ntopng#5995]
I have an issue with email notifications. When testing a recipient the test throws a error, however the email sends. The real problem lies in the fact that the notifications once triggered are not being delivered to the recipient.

I've tried 2x new fresh installs of ntopng
running latest version on Raspbian on a raspberrypi.

Any ideas? Screenshot attached below

Thanks in advance.

![InkedScreenshot 2021-10-20 233252](https://user-images.githubusercontent.com/71812804/138077965-9ca88e27-7485-469c-883a-1cd8c0cffa01.jpg)rypi.

**Comment by deanfourie1** [comment]
Ok ive narrowed it down to this.

systemctl stop ntopng
rm -rf /var/lib/ntopng/category_lists
systemctl start ntopng

https://github.com/ntop/ntopng/issues/2456

Must be running as root. Is there any way to prevent ntopng as running as root on boot?

Thanks

**Comment by deanfourie1** [comment]
Also am still not receiving active host monitoring notifications

**Comment by simonemainardi** [comment]
ntopng doesn't need to run as root. By default, it runs using unprivileged user `ntopng`

Assuming you have installed it from the standard site `packages.ntop.org` you can:
- stop ntopng
-  `chown -R ntopng:ntopng /var/lib/ntopng`
- restart ntopng

**Comment by deanfourie1** [comment]
I have tried the above, however im still getting the same issue? Any other ideas? Thanks

**Comment by deanfourie1** [comment]
Upon another fresh install, the exact same behavior. I'm sure this is nothing I am doing wrong.

**Comment by farosch** [comment]
Having the exact same issue running ntopng on pfsense 2.5.2:

Version:        5.1.211126 [Enterprise/Professional build]
GIT rev:        dev:a2d079a97c8b7d1742cfbfb6d2f58b2b09d37452:20211126
Pro rev:        r4491
Built on:       FreeBSD 12.2
Platform:       amd64
Edition:        Enterprise M
License Type:   Permanent

**Comment by simonemainardi** [comment]
Running the latest version of ntopng on a raspberry pi3:

```
16/Dec/2021 14:34:41 [main.cpp:403] Scripts/HTML pages directory: /usr/share/ntopng
16/Dec/2021 14:34:41 [Ntop.cpp:469] Welcome to ntopng armv7l v.5.1.211212 - (C) 1998-21 ntop.org
16/Dec/2021 14:34:41 [Ntop.cpp:479] Built on Raspbian GNU/Linux 10 (buster)
```

Configured as

<img width="807" alt="image" src="https://user-images.githubusercontent.com/3397663/146382238-fa69721d-4def-4a7f-885c-dc8944af1416.png">

Is getting emails without root privileges

<img width="362" alt="image" src="https://user-images.githubusercontent.com/3397663/146382335-52021f34-b2fe-4c61-8b20-e6cdc95b9e73.png">


My guess is that there's an error in the SMTP configuration. Can you please try and run ntopng in the foreground as

```
$ sudo /usr/local/bin/ntopng /etc/ntopng/ntopng.conf
```

Then do the "Check" and look for errors in the console.

**Comment by deanfourie1** [comment]
I am still getting this issue. Running via official install on ntopng website alongside pfSense.

I cannot send emails for some reason. Exact same error as post #1

any ideas?

**Comment by deanfourie1** [comment]
Sorry you can now close this.

I tried server:465 but in fact the correct syntax is smtps://server

Thanks anyway.
