### ISSUE TITLE
Add context for host anomaly alert

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#5996]
Dear ntop team
Currently the Score Anomaly Alert triggers when the score is outside of the expected range. That is ok, the smoothing / interpolation too. But for figuring out what is the issue with the host, we miss context, like how the host score is put together.
As with the information as is I can not go further or drill down to explore what caused the score to increase or which issues where summed up in the score: <img width="1219" alt="Screenshot 2021-10-20 at 17 50 02" src="https://user-images.githubusercontent.com/38549755/138127992-b6459be9-a935-4474-8907-e7eb1407b22a.png">
Is just a number and I get an alert, but I dont know why.

Something like with the flow score would be helpful:
<img width="1484" alt="Screenshot 2021-10-20 at 17 49 35" src="https://user-images.githubusercontent.com/38549755/138128115-a92fce86-ec27-4fd5-aae4-06306d619a7c.png">

Thank you.

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu unfortunately it's not possible to get specific information on what generated that score, so this is the best I can do. If it could be helpful I could add some reference to the host timeseries and flow alerts filtered on that host.

**Comment by martinscheu** [comment]
Hi @MatteoBiscosi any information in the first step would be helpful. How it is now I would need to investigate what the issues are and that takes too much time, so I would disable this check. Thank you.

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu unfortunately this is all i can do for now, I added a reference to the flow alerts, ecc. in fact that score is calculated from the sum of the various score alerts so it is possible to check which was the cause of the sudden change by taking a look at the various alerts (more info here https://www.ntop.org/guides/ntopng/basic_concepts/alerts.html#behavior-alerts).
![Screenshot from 2021-11-02 16-19-52](https://user-images.githubusercontent.com/49585191/139876932-bfdbbd6b-a784-4f6c-abbb-ef030c673ea4.png)

If more useful info are going to be available in the future I'm going to add them, right now however it's not possible to have more specific information.
