### ISSUE TITLE
Wrong attacker alert

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5997]
This host has only incoming flows (i.e. is the server) and this score
![image](https://user-images.githubusercontent.com/4493366/138157060-b5aa54ac-9c8a-439c-a5db-04d16bb2b150.png)

These are the flows of the host

![image](https://user-images.githubusercontent.com/4493366/138157037-86d5f051-3570-4314-a371-a21f99c36505.png)
and its role is marked as an attacker but it is the victim
![image](https://user-images.githubusercontent.com/4493366/138157134-adcc6340-76a3-4685-b370-303fa1c5ea54.png)
because (bug in the bug) alerts are wrong (they are swapped)

![image](https://user-images.githubusercontent.com/4493366/138157562-dc938275-7ba1-4615-9177-13365a6abbba.png)

with respect to the flow view

![image](https://user-images.githubusercontent.com/4493366/138157978-5b48369e-16de-41f6-8500-6c732e21e257.png)

I  expect to see an alert of this host being under attack

**Comment by simonemainardi** [comment]
I have relaxed the condition to also consider the server an attacker. Ideally, we should at least keep into account the application or the category to consider the server as attacker.

Note that alerts are not swapped. You are getting those alerts as 'Application on Non-Standard Port' so it is OK to see seemingly ephemeral ports as server ports. If you look at the flows, they are all on the standard `ftp` port so likely there were not carrying risk 'Application on Non-Standard Port' as the port was standard.

**Comment by lucaderi** [comment]
Still bugged. Just tested and this is what I see: no one is marked. I expect the host making FTP requests (the client) to be the attacker and the other one to be the victim.

![image](https://user-images.githubusercontent.com/4493366/140282417-f4416505-0027-44cd-b480-b8b1421d42a6.png)

**Comment by simonemainardi** [comment]
Said that the original issue and the corresponding fix were about "Application On Non-Standard Port" and now you are discussing another risk.

Attackers and victims were chosen for "Remote to Local Insecure Protocol" only when the category was MALWARE or BANNED_SITE to keep the implementation less aggressive (attackers and victims are used to block):

```
FlowAlert *RemoteToLocalInsecureProto::buildAlert(Flow *f) {
  RemoteToLocalInsecureProtoAlert *alert = new RemoteToLocalInsecureProtoAlert(this, f);

  /* The remote client is considered the attacker. The victim is the local server */
  switch(f->get_protocol_category()) {
  case CUSTOM_CATEGORY_MALWARE:
  case CUSTOM_CATEGORY_BANNED_SITE:
    alert->setCliAttacker(), alert->setSrvVictim();
    break;
  default:
    break;
  }

  return alert;
}
```

According to your comment, the latest implementation changes the behavior above to always consider attackers and victims as you have asked.

**Comment by lucaderi** [comment]
Hard to check until #6100 is fixed

**Comment by lucaderi** [comment]
![image](https://user-images.githubusercontent.com/4493366/146739681-d7143f84-f271-40fc-901e-04216eb103cc.png)
This host is a victim but
- there is no icon that reports it as a victim
- the score does not indicates whether it is a server or client score: please fix it

**Comment by lucaderi** [comment]
Verified as fixed
