### ISSUE TITLE
NTOPNG: Hosts shows me more than 1400 entries, almost all IPv6 

### ISSUE THREAD

**Issue by LarsMde** [ntop/ntopng#5999]
I have a problem since ntopng 5.x.
I have about 30 physical hosts in my network, but instead of these 30 local hosts, about 1400 are now counted, because all IPv6 multicast addresses (ff02::) are also counted as local hosts (under flows also because IPv6 Neighbor Solicitation). Ntopng even made DNS requests for all these hosts, which my external DNS server could not resolve, of course. I was able to solve the problem with the DNS queries with the option "-n 2", but this only solves a consequence - not the cause. I use STDIN from the Fritzbox (https://www.ntop.org/ntopng/how-to-use-ntopng-for-realtime-traffic-analysis-on-fritzbox-routers/) as the interface.

Now running ntopng v.5.0.211019 on Debian 11. Is there a solution for this?

![ntopng_hosts](https://user-images.githubusercontent.com/47632487/138440330-209fca85-e9ec-452d-94ce-8b8941f4b39a.PNG)

**Comment by simonemainardi** [comment]
Hi, thanks for pointing this out. Issue is fixed and will be available in the next 5.1 build within the next 24 hours.
