### ISSUE TITLE
Not possible to change DSCP value in the client DSCP filter

### ISSUE THREAD

**Issue by Niklasr69** [ntop/ntopng#6000]
After creating a DSCP filter in "historical flow explorer" page, is not possible to change the DSCP value.

![image](https://user-images.githubusercontent.com/26242302/138544279-f9acd9b0-bba2-4a02-a859-b1a7a2813ccb.png)

![image](https://user-images.githubusercontent.com/26242302/138544290-aab7393a-33ab-44d3-bd52-adddd01cdca8.png)

The Client DSCP filter is also missing when clicking on filter add

![image](https://user-images.githubusercontent.com/26242302/138544334-14f7bef1-97ba-49f7-bcc1-45767ad72cc7.png)

**Comment by Niklasr69** [comment]
The fix and new function works fine.
The issue can be closed.

**Comment by simonemainardi** [comment]
Thanks for reporting
