### ISSUE TITLE
Feature Request - Timeseries export by lat/long

### ISSUE THREAD

**Issue by bojangles9** [ntop/ntopng#6002]
I'd like to reproduce the "geomap" in the ntop-ng GUI, in Grafana.

This would be a modification to the Country:traffic export stat, but would export lat/long instead.

**Comment by MatteoBiscosi** [comment]
Hi @renoir789 what do you mean by a `modification to the Country:traffic export stat`? I'm going to create a new endpoint from which even the geomap is going to ask for the data and it's going to send back info like now, a list containing the relative hosts info, ip, lat and long and info like that
![Screenshot from 2021-11-02 12-41-58](https://user-images.githubusercontent.com/49585191/139839949-810651c0-0d67-450a-a88f-6194cba5ed91.png)

**Comment by bojangles9** [comment]
> 
> 
> Hi @renoir789 what do you mean by a `modification to the Country:traffic export stat`? I'm going to create a new endpoint from which even the geomap is going to ask for the data and it's going to send back info like now, a list containing the relative hosts info, ip, lat and long and info like that ![Screenshot from 2021-11-02 12-41-58](https://user-images.githubusercontent.com/49585191/139839949-810651c0-0d67-450a-a88f-6194cba5ed91.png)

That's perfect! Lat/long and amount of traffic flowing to that IP would be great!

**Comment by MatteoBiscosi** [comment]
Hi @renoir789 implemented as requested. You can find a new endpoint available `/lua/pro/rest/v2/get/geo_map/hosts.lua` (check the documentation for more info (https://www.ntop.org/guides/ntopng/api/rest/api_v2.html). It is going to return the list of all the hosts available with the various information, like latitude, longitude ecc. to add extra info a Pro license is needed (like bytes, flows ecc.) and you need to enable them from the preferences (Geo Map->RX/TX data).
![Screenshot from 2021-11-24 17-25-56](https://user-images.githubusercontent.com/49585191/143277610-3ba371d0-dfbc-4d1a-9ef9-a210bf7ea117.png)

If you don't have a pro license and you need only bytes as extra information please tell me and i'll try to find a way.

**Comment by bojangles9** [comment]
That's really awesome, thanks for doing that!

I run the community version on my pfsense box. Just to confirm that that hosts/lat/long will be available in the community version, while the extra info requires the pro license? 
Is there a "pro" license for home users that is a bit lower in price?


> Hi @renoir789 implemented as requested. You can find a new endpoint available `/lua/pro/rest/v2/get/geo_map/hosts.lua` (check the documentation for more info (https://www.ntop.org/guides/ntopng/api/rest/api_v2.html). It is going to return the list of all the hosts available with the various information, like latitude, longitude ecc. to add extra info a Pro license is needed (like bytes, flows ecc.) and you need to enable them from the preferences (Geo Map->RX/TX data). ![Screenshot from 2021-11-24 17-25-56](https://user-images.githubusercontent.com/49585191/143277610-3ba371d0-dfbc-4d1a-9ef9-a210bf7ea117.png)
> 
> If you don't have a pro license and you need only bytes as extra information please tell me and i'll try to find a way.

**Comment by simonemainardi** [comment]
@MatteoBiscosi can you please check.

**Comment by lucaderi** [comment]
Seems to work
