### ISSUE TITLE
snmp polling delayed/timeout

### ISSUE THREAD

**Issue by Niklasr69** [ntop/ntopng#6003]
The SNMP polling doeas not work as it should when number of flow exporters increasing.
In our setup, 40 flow exporters sending flows.
Will be more soon.
The CPU is not high.
snmp walk from OS works fine.

The number of devices with problem are more, only an example.
![image](https://user-images.githubusercontent.com/26242302/138662738-cd218efa-1f94-46bc-accc-0254b2122be3.png)

**Comment by simonemainardi** [comment]
This ticket depends on https://github.com/ntop/ntopng/issues/6003

**Comment by Niklasr69** [comment]
The SNMP polling works fine from v.5.1.211125
Tested with 65 exporters

**Comment by simonemainardi** [comment]
Thanks for reporting.
