### ISSUE TITLE
Flow pagination is not implemented

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6005]
Flow pagination is not implemented. This is what I see
![Screen Shot 2021-10-25 at 16 02 24](https://user-images.githubusercontent.com/4493366/138710033-5e2b9540-e7b7-4bf3-8725-b87367915f92.png)
and this is what I would expect
![Screen Shot 2021-10-25 at 16 04 57](https://user-images.githubusercontent.com/4493366/138710480-fecfe343-af10-4938-9c58-e799d9421484.png)

**Comment by MatteoBiscosi** [comment]
Should be fixed now. In Clickhouse I remind that this function is available, instead it's not available in nIndex (caching problem).

**Comment by lucaderi** [comment]
Working now
