### ISSUE TITLE
Flow entries pagination is not working

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6006]
![Screen Shot 2021-10-25 at 16 06 00](https://user-images.githubusercontent.com/4493366/138710615-73700d41-27d7-452c-b90b-67990dc1b020.png)

Actually it is working only if a new query is performed and not when then menu value is changed

**Comment by MatteoBiscosi** [comment]
Please try again after updating, probably it was due to #6015

**Comment by lucaderi** [comment]
Working now
