### ISSUE TITLE
Record download is not working

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6008]
Clicking on this button 
![Screen Shot 2021-10-25 at 16 09 57](https://user-images.githubusercontent.com/4493366/138711238-cd8a8b25-4909-4843-a737-fc1177218bfd.png)
triggers this output

HTTP/1.1 302 Found
Server: ntopng 5.1.211021 (x86_64)
Set-Cookie: session=ff0ba6128503967960b70cb1e1c204f0; path=/; HttpOnly; SameSite=lax
Location: /lua/http_status_code.lua?message=internal_error&referer=192.168.1.187%3A3000%2Flua%2Fenterprise%2Flive_flows_extraction.lua%3Fifid%3D0%26version%3D4%26length%3D10%26ts_schema%3Dhost%253Atraffic%26ts_query%3Difid%253A0%26epoch_end%3D1635170162%26epoch_begin%3D1632578162%26detail_view%3Dflows%26observation_point_id%3D7%253Beq%26visible_columns%3Dcli_ip%252Csrv_ip%252C&error_message=...png%2Fscripts%2Flua%2Fpro%2Fmodules%2Fflow_db%2Fclickhouse_utils.lua%3A450%3A%20bad%20argument%20%238%20to%20%27format%27%20%28number%20expected%2C%20got%20boolean%29

...png/scripts/lua/pro/modules/flow_db/clickhouse_utils.lua:450: bad argument #8 to 'format' (number expected, got boolean)

**Comment by MatteoBiscosi** [comment]
The CSV download should now be working correctly. In my labs I was able to download 70k values without problems in a few seconds (pro repo)

**Comment by lucaderi** [comment]
Not quite
27/Oct/2021 10:07:00 [MySQLDB.cpp:1016] ERROR: MySQL error: [Code: 62. DB::Exception: Syntax error: failed at position 545 ('nil'): nil LIMIT 10 OFFSET 0. Expected one of: UNION, LIMIT, DoubleColon, LIKE, GLOBAL NOT IN, end of query, AS, DIV, IS, UUID, INTO OUTFILE, EXCEPT, OR, QuestionMark, BETWEEN, OFFSET, NOT LIKE, MOD, AND, Comma, alias, SETTINGS, IN, ILIKE, INTERSECT, FORMAT, Dot, NOT ILIKE, NOT, Arrow, token, NOT IN, GLOBAL IN. (SYNTAX_ERROR) (version 21.10.2.15 (official build))][62][SELECT IPv4NumToString(IPV4_SRC_ADDR) IPV4_SRC_ADDR,SRC_LABEL,IPv4NumToString(IPV4_DST_ADDR) IPV4_DST_ADDR,DST_LABEL,IP_SRC_PORT,IP_DST_PORT,VLAN_ID,IP_PROTOCOL_VERSION, IPv6NumToString(IPV6_SRC_ADDR) IPV6_SRC_ADDR, IPv6NumToString(IPV6_DST_ADDR) IPV6_DST_ADDR, toInt32(FIRST_SEEN) FIRST_SEEN, toInt32(LAST_SEEN) LAST_SEEN, (LAST_SEEN - FIRST_SEEN) as TIME_DELTA, (TOTAL_BYTES / (TIME_DELTA + 1)) * 8 as THROUGHPUT, IP_PROTOCOL_VERSION FROM flows WHERE (INTERFACE_ID=0) AND (FIRST_SEEN >= 1635319461) AND (LAST_SEEN <= 1635321261) ORDER BY nil nil LIMIT 10 OFFSET 0]

**Comment by lucaderi** [comment]
The problem above appears from time to time, not always. Please check parameters value

**Comment by MatteoBiscosi** [comment]
Should be fixed, pro repo

**Comment by lucaderi** [comment]
Still bugged with a new error
![Screen Shot 2021-11-04 at 09 29 56](https://user-images.githubusercontent.com/4493366/140281906-2814c637-deb9-4b0b-a6d3-4f2e6aa09669.png)

**Comment by MatteoBiscosi** [comment]
Fixed pro repo, tested right now with over 66k flows and it's working correctly

**Comment by lucaderi** [comment]
Verified as fixed
