### ISSUE TITLE
Is it possible to have resolved IPs in active flows API response?

### ISSUE THREAD

**Issue by vadchen** [ntop/ntopng#6009]
We do see resolved IPs in the UI and in some API responses (lua/pro/rest/v1/get/db/flows.lua?ifid=0), 
but in active flows API (lua/rest/v1/get/flow/active.lua) we get only IP:

`
"server": {

    "is_broadcast": true,
    "ip": "151.101.1.44",
    "is_blacklisted": false,
    "name": "151.101.1.44",
    "is_dhcp": false,
    "port": 443

}
`

![image](https://user-images.githubusercontent.com/6987701/138710366-8c9b117b-cb28-4250-a384-97a311615d80.png)

**Comment by simonemainardi** [comment]
> lua/pro/rest/v1/get/db/flows.lua

Tells you the historical name, i.e., the name resolved at the time when the historical flow was seen

> Is it possible to have resolved IPs in active flows API response?

Sure, see REST endpoint `rest/v2/get/dns/resolve.lua`
