### ISSUE TITLE
FR: graph superposition

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#601]
hi,

it's just a feature request
I think that would be interesting to have possibility to active graph superposition

I mean by example, when we have bandwidth graph (or other kind of graph) we could have an option to add to this graph the same graph from the day before
It could be interesting to detect something not normal or just compare values, it's a kind of proactive information and we could compare in live bandwidth usage
All that with a define time range (hour, day...)

thanks

Nico

**Comment by simonemainardi** [comment]
yes, this is an interesting feature. we were already discussing the implementation.

**Comment by emanuele-f** [comment]
This is now implemented in the latest dev version. For example, when selecting a day timeframe, an additional "1day ago" line is shown in the graph.
