### ISSUE TITLE
Client DSCP is not properly populated

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6012]
![Screen Shot 2021-10-25 at 16 13 46](https://user-images.githubusercontent.com/4493366/138711942-cedf2b90-d05c-4c24-bb6b-12fed579c570.png)

**Comment by MatteoBiscosi** [comment]
Removed Unknown label (pro repo)

**Comment by lucaderi** [comment]
![Screen Shot 2021-10-25 at 20 22 07](https://user-images.githubusercontent.com/4493366/138749308-e2740521-0c7f-40dc-843c-150c248f3fc8.png)
Empty now: not working yet

**Comment by lucaderi** [comment]
Actually sometimes is populated as shown in https://github.com/ntop/ntopng/issues/6004
There is something wrong either when writing to the DB or when reading it

**Comment by MatteoBiscosi** [comment]
The problem should be fixed now (pro repo). The insert into the DB was wrong, in fact instead of getting the DSCP info from the flow it got the TCP flags, for this reason the values were not correct.

**Comment by lucaderi** [comment]
Verified as fixed
