### ISSUE TITLE
IP filtering is not working as expected 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6014]
![Screen Shot 2021-10-25 at 16 21 19](https://user-images.githubusercontent.com/4493366/138713298-c39da243-f537-4e22-b61c-8807d8a26502.png)
![Screen Shot 2021-10-25 at 16 22 12](https://user-images.githubusercontent.com/4493366/138713517-9ce2b90c-475e-4b16-a805-b2ef9a34a96b.png)
![Screen Shot 2021-10-25 at 16 22 39](https://user-images.githubusercontent.com/4493366/138713587-6e1d34fb-067c-4bd2-ba96-4a52738a7735.png)

**Comment by MatteoBiscosi** [comment]
should be fixed, same as #6015 (pro repo)

**Comment by lucaderi** [comment]
![Screen Shot 2021-10-25 at 19 23 19](https://user-images.githubusercontent.com/4493366/138741600-a9c8e895-5fa0-4500-a7a9-c6e9704afd0c.png)
IPv4 seems to work now, IPv6 still bugged

**Comment by lucaderi** [comment]
Verified as fixed
