### ISSUE TITLE
REST Error during ClickHouse Flow Query

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6015]
25/Oct/2021 16:23:10 [LuaEngine.cpp:1253] WARNING: Script failure [/home/deri/ntopng/scripts/lua/pro/rest/v2/get/host/flows/flows_info.lua][...png/scripts/lua/pro/modules/flow_db/clickhouse_utils.lua:451: bad argument #4 to 'format' (number expected, got nil)]

**Comment by MatteoBiscosi** [comment]
Should be fixed, please update and let me know (pro repo)

**Comment by lucaderi** [comment]
A new bug arose
25/Oct/2021 17:39:42 [MySQLDB.cpp:1016] ERROR: MySQL error: [Code: 53. DB::Exception: Cannot convert string 90.147.160.70 to type UInt32: while executing 'FUNCTION equals(IPV4_DST_ADDR : 6, '90.147.160.70' : 7) -> equals(IPV4_DST_ADDR, '90.147.160.70') UInt8 : 9'. (TYPE_MISMATCH) (version 21.10.2.15 (official build))][53][SELECT COUNT(*) AS totalRows FROM flows WHERE (( (IPV4_DST_ADDR='90.147.160.70' OR IPV4_SRC_ADDR='90.147.160.70') )) AND (FIRST_SEEN >= 1634571578) AND (LAST_SEEN <= 1635176378)]
25/Oct/2021 17:39:42 [LuaEngine.cpp:1253] WARNING: Script failure [/home/deri/ntopng/scripts/lua/pro/rest/v2/get/host/flows/flows_info.lua][/home/deri/ntopng/scripts/lua/modules/ntop_utils.lua:114: bad argument #1 to 'for iterator' (table expected, got string)]

**Comment by MatteoBiscosi** [comment]
this bug was due to the fact that the ip was not converted into the numeric version, please update pro repo, the problem should be fixed

**Comment by lucaderi** [comment]
Seems to work now
