### ISSUE TITLE
Invalid Mix of IPv4 and IPv6

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6016]
![Screen Shot 2021-10-25 at 19 25 45](https://user-images.githubusercontent.com/4493366/138741935-3690ff6f-f578-4161-8d4f-35c9bc6f237e.png)

This screenshot shows two bugs
- The code does not seem to check the protocol version so you mix IPv4 with IPv6 results. With IPv6 the IPv4 address is set to 0.0.0.0 and thus is selected. With an IP-based filter, once you know the family (v4 or v6) you need to add to the query the protocol version
- the same 0.0.0.0 is resolved once to "1 piano" and one to "noip"

**Comment by MatteoBiscosi** [comment]
Fixed, pro repo. The problem was that when filtering no ip version was added into the where

**Comment by lucaderi** [comment]
Seems to be fixed
