### ISSUE TITLE
top talkers in history flow explorers page

### ISSUE THREAD

**Issue by Niklasr69** [ntop/ntopng#6017]
Missing the function to be able to get top talkers from the "history flows explorer" page.
After filtering out flow exporter (optional in / out interface) :
show that a Source or Destination is occupying the percentage of a BW available so that we can have idea as who is the most polluted IP(Source/Dest) to be worked upon. It should show all the flows associated to that particular IP also. It should have conversation/protocol and application detail.
The BW for an interface should be polled with SNMP.

Picture from our legacy system:

![image](https://user-images.githubusercontent.com/26242302/138815688-00ea7282-f150-44d4-9bec-efe71e6ee70b.png)

More picture from legacy system can be shared if needed.

**Comment by simonemainardi** [comment]
It's unclear what you are saying. Enclosed pic doesn't come from ntopng.

Please, explain with details and examples.

**Comment by Niklasr69** [comment]
The idea with the image from our legacy system was to explain what we need.

We need to be able to filter out top talker clients from a certain exporter and interface for a certain history time.
I.E add together all the flows that a client has created so you get a total throughput consumption. Preferably percent rate of the available BW for the interface

**Comment by simonemainardi** [comment]
We are now adding clickhouse support that will allow you to perform this kind of queries. Please stay tuned.

**Comment by Niklasr69** [comment]
All features are there now with clickhouse.
Can be closed.
