### ISSUE TITLE
nprobe init script doesn't wait long enough for nprobe to stop when restarting

### ISSUE THREAD

**Issue by hatclub** [ntop/ntopng#602]
When nprobe is busy as a netflow collector, "/etc/init.d/nprobe restart" does not wait until nprobe is completely stopped before attempting to restart nprobe, leading to a port collision and eventually, no copies of nprobe running when the original (slowly shutting down) thread finally terminates.

07/Jun/2016 15:50:20 [cache.c:1224] Redis Cache [0 total/0.0 get/sec][0 total/0.0 set/sec]
07/Jun/2016 15:50:20 [nprobe.c:491] Received shutdown request... [signal: 15]
07/Jun/2016 15:50:21 [engine.c:2824] About to flush hash (threadId 0)
07/Jun/2016 15:50:21 [engine.c:2826] Completed hash walk (thread 0)
07/Jun/2016 15:50:22 [nprobe.c:5152] Still 165434 queued buckets to be exported...
07/Jun/2016 15:50:23 [nprobe.c:5152] Still 158382 queued buckets to be exported...
07/Jun/2016 15:50:24 [nprobe.c:5152] Still 149825 queued buckets to be exported...
07/Jun/2016 15:50:25 [nprobe.c:5152] Still 140948 queued buckets to be exported...
07/Jun/2016 15:50:25 [nprobe.c:3392] Valid nProbe license found
07/Jun/2016 15:50:25 [nprobe.c:4153] WARNING: If you want to preserve the -M value, please specify -w before -M
07/Jun/2016 15:50:25 [nprobe.c:4843] WARNING: The output interfaceId is set to 0: did you forget to use -Q perhaps ?
07/Jun/2016 15:50:25 [nprobe.c:4846] WARNING: The input interfaceId is set to 0: did you forget to use -u perhaps ?
07/Jun/2016 15:50:25 [nprobe.c:4946] Welcome to nProbe v.7.3.160607 ($Revision: 5253 $) for x86_64-unknown-linux-gnu with native PF_RING acceleration
07/Jun/2016 15:50:25 [nprobe.c:4956] Running on Ubuntu 14.04.4 LTS
07/Jun/2016 15:50:25 [nprobe.c:4967] [LICENSE] nProbe SystemId: 
07/Jun/2016 15:50:25 [nprobe.c:7237] Welcome to nProbe v.7.3.160607 for x86_64-unknown-linux-gnu
07/Jun/2016 15:50:25 [plugin.c:1030] 0 plugin(s) enabled
07/Jun/2016 15:50:25 [nprobe.c:6802] Non IPv4/v6 traffic is discarded according to the template
07/Jun/2016 15:50:25 [util.c:434] GeoIP: loaded AS config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNum.dat
07/Jun/2016 15:50:25 [util.c:445] GeoIP: loaded AS IPv6 config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNumv6.dat
07/Jun/2016 15:50:25 [nprobe.c:5461] Using packet capture length 128
07/Jun/2016 15:50:25 [nprobe.c:7410] IPv6 traffic will NOT be exported/accounted by this probe
07/Jun/2016 15:50:25 [nprobe.c:7411] due to configuration options (e.g. use NetFlow v9)
07/Jun/2016 15:50:26 [nprobe.c:5152] Still 132839 queued buckets to be exported...
07/Jun/2016 15:50:27 [nprobe.c:5152] Still 126508 queued buckets to be exported...
07/Jun/2016 15:50:28 [nprobe.c:5152] Still 118026 queued buckets to be exported...
07/Jun/2016 15:50:28 [nprobe.c:7557] Not capturing packet from interface (collector mode)
07/Jun/2016 15:50:28 [util.c:4036] Initializing ZMQ as server
07/Jun/2016 15:50:28 [util.c:4077] ERROR: Unable to bind ZMQ endpoint tcp://127.0.0.1:5556: Address already in use
07/Jun/2016 15:50:28 [collect.c:123] ERROR: Flow collector UDP port 2055 already in use ? [Address already in use/98]
07/Jun/2016 15:50:29 [nprobe.c:5152] Still 108918 queued buckets to be exported...
07/Jun/2016 15:50:30 [nprobe.c:5152] Still 99708 queued buckets to be exported...
07/Jun/2016 15:50:31 [nprobe.c:5152] Still 88592 queued buckets to be exported...
07/Jun/2016 15:50:32 [nprobe.c:5152] Still 75931 queued buckets to be exported...
07/Jun/2016 15:50:33 [nprobe.c:5152] Still 66700 queued buckets to be exported...
07/Jun/2016 15:50:34 [nprobe.c:5152] Still 54356 queued buckets to be exported...
07/Jun/2016 15:50:35 [nprobe.c:5152] Still 45896 queued buckets to be exported...
07/Jun/2016 15:50:36 [nprobe.c:5152] Still 37070 queued buckets to be exported...
07/Jun/2016 15:50:37 [nprobe.c:3392] Valid nProbe license found
07/Jun/2016 15:50:37 [nprobe.c:4153] WARNING: If you want to preserve the -M value, please specify -w before -M
07/Jun/2016 15:50:37 [nprobe.c:4843] WARNING: The output interfaceId is set to 0: did you forget to use -Q perhaps ?
07/Jun/2016 15:50:37 [nprobe.c:4846] WARNING: The input interfaceId is set to 0: did you forget to use -u perhaps ?
07/Jun/2016 15:50:37 [nprobe.c:4946] Welcome to nProbe v.7.3.160607 ($Revision: 5253 $) for x86_64-unknown-linux-gnu with native PF_RING acceleration
07/Jun/2016 15:50:37 [nprobe.c:4956] Running on Ubuntu 14.04.4 LTS
07/Jun/2016 15:50:37 [nprobe.c:4967] [LICENSE] nProbe SystemId: 
07/Jun/2016 15:50:37 [nprobe.c:7237] Welcome to nProbe v.7.3.160607 for x86_64-unknown-linux-gnu
07/Jun/2016 15:50:37 [plugin.c:1030] 0 plugin(s) enabled
07/Jun/2016 15:50:37 [nprobe.c:6802] Non IPv4/v6 traffic is discarded according to the template
07/Jun/2016 15:50:37 [util.c:434] GeoIP: loaded AS config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNum.dat
07/Jun/2016 15:50:37 [util.c:445] GeoIP: loaded AS IPv6 config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNumv6.dat
07/Jun/2016 15:50:37 [nprobe.c:5461] Using packet capture length 128
07/Jun/2016 15:50:37 [nprobe.c:7410] IPv6 traffic will NOT be exported/accounted by this probe
07/Jun/2016 15:50:37 [nprobe.c:7411] due to configuration options (e.g. use NetFlow v9)
07/Jun/2016 15:50:37 [nprobe.c:5152] Still 25712 queued buckets to be exported...
07/Jun/2016 15:50:38 [nprobe.c:5152] Still 14669 queued buckets to be exported...
07/Jun/2016 15:50:38 [nprobe.c:7557] Not capturing packet from interface (collector mode)
07/Jun/2016 15:50:38 [util.c:4036] Initializing ZMQ as server
07/Jun/2016 15:50:38 [util.c:4077] ERROR: Unable to bind ZMQ endpoint tcp://127.0.0.1:5556: Address already in use
07/Jun/2016 15:50:38 [collect.c:123] ERROR: Flow collector UDP port 2055 already in use ? [Address already in use/98]
07/Jun/2016 15:50:39 [nprobe.c:5152] Still 3889 queued buckets to be exported...
07/Jun/2016 15:50:42 [cache.c:1224] Redis Cache [0 total/0.0 get/sec][0 total/0.0 set/sec]
07/Jun/2016 15:50:42 [nprobe.c:2698] Processed packets: 0 (max bucket search: 34)
07/Jun/2016 15:50:42 [nprobe.c:2681] Fragment queue length: 0
07/Jun/2016 15:50:42 [nprobe.c:2704] WARNING: Your bucket search is too slow (34): expect drops
07/Jun/2016 15:50:42 [nprobe.c:2707] Flow export stats: [0 bytes/0 pkts][0 flows/0 pkts sent]
07/Jun/2016 15:50:42 [nprobe.c:2714] Flow collection: [collected pkts: 10091606][processed flows: 314962935]
07/Jun/2016 15:50:42 [nprobe.c:2717] Flow drop stats:   [0 bytes/0 pkts][0 flows]
07/Jun/2016 15:50:42 [nprobe.c:2722] Total flow stats:  [0 bytes/0 pkts][0 flows/0 pkts sent]

**Comment by lucaderi** [comment]
@ValentinaViscarelli Can you please look at this when you have time send that you are already modifying the other init scripts for Ubuntu 16?

**Comment by ValentinaViscarelli** [comment]
@hatclub 
I have made some changes. Now it should be fine.
Overnight a new nprobe release (containing the changes) will be built.
Please update nprobe and give it a try.
Thanks

**Comment by hatclub** [comment]
@ValentinaViscarelli works perfectly (tested on 160609)
