### ISSUE TITLE
Invalid flow drill down with ClickHouse

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6021]
![image](https://user-images.githubusercontent.com/4493366/139027515-d9893cbb-1d5b-4079-a36c-d4467d954e9d.png)
Clicking on the + icon leads to
![Screen Shot 2021-10-27 at 10 18 13](https://user-images.githubusercontent.com/4493366/139027581-50eef518-01dc-4c50-9589-be6a0b034b1e.png)

**Comment by simonemainardi** [comment]
Link should be changed as follow:
- Show the link only when clickhouse support is enabled
- The link should point to the clickhouse explorer with a filter set on the host

**Comment by simonemainardi** [comment]
Addressed as requested.

**Comment by lucaderi** [comment]
Verified as fixed
