### ISSUE TITLE
Not all the flow IEs are reported in the GUI

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6028]
Start nProbe as follows
- nprobe -i XXX --zmq tcp://127.0.0.1:1234 -T "@NTOPNG@ %TLS_CIPHER %TLS_VERSION %SRC_TO_DST_MAX_THROUGHPUT %JA3C_HASH %JA3S_HASH" 
and ntopng as
- ntopng -i tcp://127.0.0.1:1234

As you can see JA3 information is missing but the throughout is instead reported.

![Screen Shot 2021-10-29 at 22 29 43](https://user-images.githubusercontent.com/4493366/139498029-8c9989d9-ea67-4dc4-82f5-d694c2587303.png)

**Comment by simonemainardi** [comment]
A general approach has been implemented to show IE descriptions arriving from nProbe.

There's no need to add code to ntopng. New IEs added to nProbe will be propagated (when part of the template) automatically and shown in ntopng.

Example

![image](https://user-images.githubusercontent.com/3397663/140930272-639063cc-7cae-4d2a-8d22-df0df118d05b.png)

**Comment by simonemainardi** [comment]
All fields are now shown. Missing IEs are due to https://github.com/ntop/nProbe/issues/515.

**Comment by lucaderi** [comment]
Seems to work. Closing for now.
