### ISSUE TITLE
Rework light mode timeseries

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6029]
This is to request the rework of host timeseries preferences

![Screen Shot 2021-10-30 at 09 54 44](https://user-images.githubusercontent.com/4493366/139525097-71ac308b-c9c4-4d05-8d0e-2b66b2a78b34.png)

In light mode please 
- remove all DSCP charts that will go to full
![Screen Shot 2021-10-30 at 09 52 48](https://user-images.githubusercontent.com/4493366/139525060-0c9d5ae1-d686-49a8-89df-684008f19a58.png)
- add in light mode the number of flows and alerts

**Comment by MatteoBiscosi** [comment]
As requested now in light mode no DSCP ts is going to show up, instead flows and alerts ts have been added
![Screenshot from 2021-11-02 11-52-13](https://user-images.githubusercontent.com/49585191/139833616-4b584ee2-0695-450f-a26f-c57127c6b9cd.png)

**Comment by lucaderi** [comment]
Verified as fixed
