### ISSUE TITLE
160607 / Invalid session does not appear to log user out (Was: Can't toggle Host Alerts on or off)

### ISSUE THREAD

**Issue by hatclub** [ntop/ntopng#603]
When viewing the "Cog" menu on the host_detail page, unticking or ticking the Host Alerts checkbox results in the page reloading with the tickbox still set however it was to begin with.

**Comment by simonemainardi** [comment]
I assume "Cog" is `page=config`. That said, alert toggle works properly here. Please try and post additional information.

Try and flush/inspect redis key (`ntopng.prefs.alerts`) before and after host alert toggle. When alerts are off you should be able to see something like

```
127.0.0.1:6379> hgetall ntopng.prefs.alerts
1) "192.168.2.130"
2) "false"
```

**Comment by hatclub** [comment]
Hrm. Works okay in Chrome 50.0.2661.102 m (Windows), but not in Opera 37.0.2178.32 (Windows) - could, possibly, be a cache problem as I was using Opera with 160606 and just refreshed the page after restarting to 160607.

Closing out all my opera windows (I have a _LOT_ of browser windows/tabs/etc) and will let you know if I can clear this behaviour or if it persists.

**Comment by hatclub** [comment]
Restarted Opera to upgrade to 37.0.2178.54, cleared all "Cached files and images", behaviour persists.

Cleared all cookies as well, logged back in, works fine. 

So presumably some cookie session ID thing that only gets checked when changes are requested, given I could browse around pages in ntop just fine?

Not sure if this is something that can be improved so that a session is completely invalidated and the user ends up completely logged out rather than what appeared to happen which is I ended up half-invalidated and I could browse but not change things?

**Comment by simonemainardi** [comment]
I am not sure why you say invalid session. If you were able to browse ntopng the session was valid: your browser and ntopng were bouncing valid session cookies or you would have been kicked out. Toggling host alerts requires an additional nonce to prevent cross site requests forgery. Again, this was valid otherwise ntopng would have raised a invalid CSRF token error.

Very likely this is an opera issue -- caching maybe? --

**Comment by hatclub** [comment]
Well, the issue didn't clear when I restarted the browser completely (after having closed all ntop tabs) and clearing all cached files; it only went away when clearing cookies (forcing me to log in again).

I've also seen the CSRF error before, and it wasn't that - the page was just reloading with the toggle set back how it was. I'll try to reproduce next time I upgrade.
