### ISSUE TITLE
Implement ClickHouse retention

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6030]
Currently -F clickhouse does not yet implements retention: this needs to be fixed

See https://fastnetmon.com/docs-fnm-advanced/data-retention-for-clickhouse-persistent-data-storage/

**Comment by lucaderi** [comment]
This script has no effect on alerts. Please complete this work

**Comment by simonemainardi** [comment]
There was another commit. Please check it. Sorry for not having referenced it. https://github.com/ntop/ntopng/commit/a014ce46a6abeca9a2fd7444ea8135a7174df524

**Comment by lucaderi** [comment]
You need to unify retention for all clickhouse tables as discussed

**Comment by lucaderi** [comment]
![Screen Shot 2021-11-11 at 18 33 30](https://user-images.githubusercontent.com/4493366/141343064-11b547d9-0c87-4408-83a1-669b87155952.png)

From this label it is unclear that it also applies to alerts:please fix it

**Comment by lucaderi** [comment]
![Screen Shot 2021-11-30 at 11 09 35](https://user-images.githubusercontent.com/4493366/144027639-c579d253-b014-422e-b2e7-e290fb44dca0.png)
![Screen Shot 2021-11-30 at 11 09 20](https://user-images.githubusercontent.com/4493366/144027646-7ddb24c4-e523-4016-bd84-dad7cc178027.png)

As you can see is not working as there are records older than 5 days. You can test it on HS

**Comment by simonemainardi** [comment]
Something is preventing the daily script to run in the installation. So old data isn't recycled:


```
nov 30 00:00:01 ntop2 ntopng[7972]: [LuaEngine.cpp:598] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/daily.lua][attempt to index a nil value]
```

**Comment by lucaderi** [comment]
Verified as fixed
