### ISSUE TITLE
NTOPNG +NPROBE Base functions not working -- HELP needed.

### ISSUE THREAD

**Issue by SARBLA** [ntop/ntopng#6032]
Good day, team after 5 days of reading and dealing with docs and internet search, reainstalling i need your help with ofiicilay bought product. 

- Issues that to my undertanding should work. but they dont for me.
- NTOPNG not guessing protocols from Netflow flows. 
- Netflow flows not dumped to MySQL  
- Application always unknown despite... 

This all prevent me from Using NTOPNG + NProbe as even at basic level 

I am not sure what is wrong my build but whatever i made or read not working... Need a session with YOU to start finally use product as no it is not working from.

![Flows issue - Ntopng ](https://user-images.githubusercontent.com/93220610/139531933-94977bf5-5c2c-496b-9332-1592c3afd365.PNG)

Collecting from NX-OS switch netflow only. 
##################SWICTH CONFIG####################
feature netflow

flow exporter DC-NETFLOW-EXPORTER
  destination 10.150.2.52
  transport udp 6363
  source loopback0
  version 9
flow record DC_V9
  match ipv4 source address
  match ipv4 destination address
  match ip tos

  match transport source-port
  match transport destination-port
  collect counter bytes
  collect counter bytes long
  collect counter packets
  collect counter packets long
  collect timestamp sys-uptime first
  collect timestamp sys-uptime last
  collect ip version
flow monitor DC
  record DC_V9
  exporter DC-NETFLOW-EXPORTER

interface Ethernet1/24
  ip flow monitor DC input

##################NPROBE config###################

Probe config as collector-mode
[root@localhost ~]# grep -v '#' /etc/nprobe/nprobe-sflow.conf
-i=none
--collector-port=6363
 --zmq=tcp://*:5556
-n=none
-T=@NTOPNG@ %L7_PROTO %FLOW_PROTO_PORT %L7_PROTO_CATEGORY %FLOW_PROTO_PORT %L7_INFO %L7_PROTO_NAME %TOTAL_FLOWS_EXP
-G=/var/run/nprobe.pid
  --verbose=2
-P=/home/nprobe
-b=3
-E=0:1235
--dont-nest-dump-dirs

#####NTOPNG####CONFIG
[root@localhost ~]# grep -v '#' /etc/ntopng/ntopng.conf
-G=/var/run/ntopng.pid
  -i='tcp://127.0.0.1:5556'
 -w=3000
 -n=3
-F=mysql;localhost;FLOW-DB;ntopng-01;ntopng;Connect1984!

################NPROBE################FLOWS
390][firstSeen=1635594413/-428][direction: RX][probe: 10.162.57.34]
Oct 30 13:39:45 localhost nprobe: 30/Oct/2021 13:39:45 [engine.c:3501] New Flow: [ip] 10.106.10.70:445 -> 10.106.32.37:9880 [00:00:00:00:00:00 -> 00:00:00:00:00:00][VLAN 0/0][tos 2][ifIdx: 436219392 -> 0][subflowId: 0/0x0000][idx=28638][firstSeen=1635594414/-429][direction: RX][probe: 10.162.57.34]
Oct 30 13:39:45 localhost nprobe: 30/Oct/2021 13:39:45 [engine.c:3704] Emitting Flow: [<->][ip] 10.106.10.41:64327 -> 10.106.36.140:34456 [33554432/0 pkt][4026531840/0 bytes][ifIdx 436219392<->0][0.0 sec][Unknown/0][init Unknown][AS: 0 -> 0]
Oct 30 13:39:45 localhost nprobe: 30/Oct/2021 13:39:45 [engine.c:3704] Emitting Flow: [<->][ip] 10.106.10.40:64327 -> 10.106.36.140:34450 [33554432/0 pkt][4026531840/0 bytes][ifIdx 436219392<->0][0.0 sec][Unknown/0][init Unknown][AS: 0 -> 0]
Oct 30 13:39:45 localhost nprobe: 30/Oct/2021 13:39:45 [engine.c:3704] Emitting Flow: [<->][ip] 10.106.10.69:445 -> 10.106.32.37:9875 [67108864/0 pkt][4227989504/0 bytes][ifIdx 436219392<->0][0.0 sec][Unknown/0][init Unknown][AS: 0 -> 0]
Oct 30 13:39:45 localhost nprobe: 30/Oct/2021 13:39:45 [engine.c:3704] Emitting Flow: [<->][ip] 10.106.10.70:445 -> 10.106.32.37:9878 [67108864/0 pkt][4227989504/0 bytes][ifIdx 436219392<->0][0.0 sec][Unknown/0][init Unknown][AS: 0 -> 0]
Oct 30 13:39:45 localhost nprobe: 30/Oct/2021 13:39:45 [engine.c:3704] Emitting Flow: [<->][ip] 10.106.10.6

**Comment by lucaderi** [comment]
Please mail me (deri@ntop.org) so we can have an interactive troubleshoot session. FLows do not carry DPI and DPI (as well plugin) need 'P' namely packets. I hope this explains you why for instance the application name is unknown for soem of your flows.

**Comment by SARBLA** [comment]
Good day, Luca. Missed your reply.
Still have the same issue and a lot of others jus cannot get it.
MY WEBEX:
https://kyndryl.webex.com/join/sergii.koval

I can just now to discuss all of these things.

All applications have unknown, ports are not guessed and labels on graphs
are not represent correct values.


I can just now. . All thisngs i have installation adn devices and
possibility to configure them but access only local on my side as I am
enterprise.





wt., 2 lis 2021 o 17:37 Luca Deri ***@***.***> napisał(a):
