### ISSUE TITLE
Exclude Checks - add between hosts possibility

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6033]
Hello ntop Team

It would be helpful to have the possibility only to mute alert between the two hosts:
 ![Screenshot 2021-10-29 at 10 00 34](https://user-images.githubusercontent.com/38549755/139810744-95b8158d-9a1d-4357-91a5-511f335b6b26.png)
as I dont want to mute all remote alerts for one of the host

**Comment by simonemainardi** [comment]
Duplicate of https://github.com/ntop/ntopng/issues/5602
