### ISSUE TITLE
Service map - host IP address

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6034]
Hello ntop Team!

In the Hosts Stats Window it would be helpful to have the IP address displayed:
![Screenshot 2021-10-29 at 10 55 58](https://user-images.githubusercontent.com/38549755/139811338-ae1dc753-196a-46e1-829f-2e51e30b1065.png)
thank you

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu , as requested now the host ip/mac is going to be shown in the host stats window. When the new build is going to be released please update and let me know if everything works fine for you too.
![Screenshot from 2021-11-02 10-00-34](https://user-images.githubusercontent.com/49585191/139816799-8490c758-2dbb-40c6-99f7-ff67488d84cf.png)

**Comment by martinscheu** [comment]
it is working fine, thanks @MatteoBiscosi !
