### ISSUE TITLE
DNS packet larger than 512 bytes - falsely alerting on packet size

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6036]
Hello ntop Team

The DNS packet larger than 512 bytes - Alert is alerting when packet size is over 512 bytes instead of DNS payload size is over 512 bytes.

Thank you.

**Comment by lucaderi** [comment]
If you talk about the flow risk as you can see in https://github.com/ntop/nDPI/blob/dev/src/lib/protocols/dns.c#L540 we consider the UDP payload that should be as you expect. Please explain the problem you reported more in detail.

**Comment by martinscheu** [comment]
yes you are right. Issue is, that we have lots of false positives. I have standard query responses over 1096, lots from Microsoft. Is the alert checking the request or response?
And when alerted, we have no context, would be nice to have the url:
<img width="1091" alt="Screenshot 2021-11-03 at 22 08 45" src="https://user-images.githubusercontent.com/38549755/140193107-8a874898-4d10-4d60-bcf7-57c932e3e7a0.png">

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu as requested I added some context to DNS alerts (like for HTTP)

![Screenshot from 2021-11-05 12-41-17](https://user-images.githubusercontent.com/49585191/140505332-a2348ca5-9540-49c8-bcae-c17a7f1e2f82.png)

**Comment by solarexpedition** [comment]
I think, detection of the EDNS0 extension in DNS UDP packets should be implemented. The 512 bytes limit is the legacy method and should only trigger an alarm if EDNS0 is not used.

EDNS0 supports a UDP query response larger than 512 bytes. Using the legacy method, UDP was used only as long as the DNS query was under 512 bytes. Over 512bytes, it changed it to TCP. With EDNS0, it allows UPD responses up to the full 1500 bytes bypassing the extra process step required to change to TCP, hence increasing efficiency.

**Comment by lucaderi** [comment]
EDNS0 is now supported in nDPI so we can close it
