### ISSUE TITLE
Implement Historical Flow Explorer

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6037]
The current implementation of the historical flow explorer is a simple Excel-like reporting tool. What is missing is a way to simplify data exploration by implementing:
- a set of pre-defined queries
- a framework to add new queries in a simple fashion

The configuration should be implemented in JSON or similar but not on Lua or using a programming language; this is to ease the addition of new queries also for non developers. Examples of predefined queries that need to be support include 
- https://documentation.solarwinds.com/en/success_center/nta/content/nta-historical-netflow-reports-sw1722.htm
- https://www.logicmonitor.com/support/monitoring/network-traffic-flow/viewing-filtering-and-reporting-on-netflow-data

**Comment by cardigliano** [comment]
An initial working implementation is available now. 
Query templates in JSON format should be placed in https://github.com/ntop/ntopng/tree/dev/scripts/query (a few simple examples are available, check the README instructions).
A dropdown for selecting the query is available in the Historical Flow Explorer.

**Comment by lucaderi** [comment]
Besides adding a dropdown menu divider to divide queries (minor comment) it works
