### ISSUE TITLE
HTTP suspicious content alert

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6038]
Hello @MatteoBiscosi 
I checked the HTTP suspicious content alert and have noticed two things:
1) could you please move the link icon (the square with arrow) to the left of the URL? is with long URLs is difficult to find it.
2) I got the alert but without any additional information:
<img width="1740" alt="Screenshot 2021-11-03 at 22 27 53" src="https://user-images.githubusercontent.com/38549755/140195606-6f4d36a3-d410-4d27-87e4-fccbfd218737.png">
Thank you

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu regarding the link icon, no problem about that however you just need to click the url, you don't need to click the link icon to open the redirect modal. What do you mean with your second point? which additional information are you referring to?

**Comment by martinscheu** [comment]
Hi @MatteoBiscosi
Thanks for picking up. For 1. I don't want to click on the link, it might be malicious, I want to copy it. And we kind of started for other information like that, link button is on the left. 
For 2. I dont see HTTP Info, but maybe is not available. And it doesn't generate the link button, means I have to select the URL manually, if I want to copy it.

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu, copy button has been added.
![Screenshot from 2021-11-17 12-45-21](https://user-images.githubusercontent.com/49585191/142194817-f0dbab11-9c0e-4da2-9075-5c5cb7ae7334.png)
Regarding 2. which HTTP info are you missing? However yes, If they are not available they are not going to be shown up.

**Comment by lucaderi** [comment]
Verified as fixed
