### ISSUE TITLE
MaxMind geolocation in ntopng (No ntopng-data package to install?)

### ISSUE THREAD

**Issue by schuc** [ntop/ntopng#6039]
I am trying to get GEO-IP working in ntopng in OpnSense and the instructions at https://github.com/ntop/ntopng/blob/dev/doc/README.geolocation.md say it's more accurate to use MaxMind. So, the very first step says to install ntopng-data package... However, there is no package of that name in the package list in OpnSense.

My package list for ntop has: os-ntopng and ntopng.

I must be missing something here but I would appreciate any suggestions as to why I do not have that package as an option to install. Thanks all.

**Comment by cardigliano** [comment]
On FreeBSD (including OPNsense) the ntopng-data is not available, however a free GeoIP database is installed with the ntopng package under /usr/local/share/ntopng/httpdocs/geoip . Please check that *.mmdb files are present in your installation.
