### ISSUE TITLE
L4 protocol list ?

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#604]
I would like to know what's the L4 protocol list you use ?
cause in flows, I have a line with only a number (see screenshot)
maybe you could update this list with 
http://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml

![2016-06-08_150115](https://cloud.githubusercontent.com/assets/17108017/15895213/60987cc2-2d8a-11e6-9ce4-94f8adb2b672.png)

Nicolas

**Comment by simonemainardi** [comment]
https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/template.lua#L374

**Comment by Niko78** [comment]
well it seems it doesn't work well
I use ntopng 2.3.160608 / ndpi 1.8.0-dev-449-0b7a392 / nprobe  v.7.3.160608

see new screenshot
![proto](https://cloud.githubusercontent.com/assets/17108017/15924029/6f0b2fec-2e30-11e6-87df-4abfa50c755a.png)

**Comment by simonemainardi** [comment]
on the C++ side, here are the protos converted to labels: https://github.com/ntop/ntopng/blob/dev/src/Utils.cpp#L99

**Comment by Niko78** [comment]
... and is it possible to extend this list ?

**Comment by simonemainardi** [comment]
definitely, please to extend the list with what you need and submit a pull request. Thank you!

**Comment by Niko78** [comment]
done with 3 new entries
thanks
