### ISSUE TITLE
IP address name resolution is working randomly

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6041]
![Screen Shot 2021-11-04 at 09 12 47](https://user-images.githubusercontent.com/4493366/140279498-e969ee79-80f6-47e9-adfc-9282dde476e4.png)

In this example sometimes 255.255.255.255 is converted to symbolic name, sometimes it is not.

**Comment by MatteoBiscosi** [comment]
Fixed, pro repo. The problem came from the fact that the client didn't have a name and the server instead had; a wrong check brought to not assigning the name to the server

**Comment by lucaderi** [comment]
Verified as fixed
