### ISSUE TITLE
Flow risk filtering is not working as it should

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6042]
Flow risk is a bitmap and thus it cannot be filtered as today. For instance the filter below means "find flows that have exactly risk set to Malformed Packet" (so =) whereas the filter should be "find flows that have risk containing Malformed Packet" (so ||)

![Screen Shot 2021-11-04 at 09 18 45](https://user-images.githubusercontent.com/4493366/140280248-9e951cc5-4ab9-431e-a19d-7247d825cfe3.png)

See also #6011

**Comment by cardigliano** [comment]
Fix provided (pro branch d938483f259c19f479995772f8b3d4961eefced7), please verify

**Comment by lucaderi** [comment]
![Screen Shot 2021-11-11 at 11 29 41](https://user-images.githubusercontent.com/4493366/141282657-e14cf127-f0cf-449c-b821-b37d15bf7422.png)
![Screen Shot 2021-11-11 at 11 29 32](https://user-images.githubusercontent.com/4493366/141282675-a5a1c594-d5d4-4d60-a8a1-9caf0b8ab4cc.png)
![Screen Shot 2021-11-11 at 11 29 23](https://user-images.githubusercontent.com/4493366/141282676-f8adc018-d3d3-4fe3-bbea-0068e8838eb4.png)
![Screen Shot 2021-11-11 at 11 29 06](https://user-images.githubusercontent.com/4493366/141282677-0c75e2c1-a92b-4224-9e7e-a30ec7cd39ea.png)

**Comment by cardigliano** [comment]
The No risk filter has been addressed (the C code and the database were containing bad flow risk bitmaps)

**Comment by lucaderi** [comment]
![image](https://user-images.githubusercontent.com/4493366/141342682-42e0dcb3-063a-4a32-afa5-50d1aced14ab.png)
![Screen Shot 2021-11-11 at 18 31 55](https://user-images.githubusercontent.com/4493366/141342892-c0b39a96-86ff-4771-8219-21d8db4572ec.png)
![Screen Shot 2021-11-11 at 18 31 43](https://user-images.githubusercontent.com/4493366/141342897-5f98b662-dcf4-400a-b5d9-5acb5f8f87de.png)
![image](https://user-images.githubusercontent.com/4493366/141342936-49d7ce3a-da1a-489e-9abc-3ae1751fd5ca.png)

**Comment by cardigliano** [comment]
Flow risk is not initialized to No Risk in fcfd9a3442e8f4a3605194eac2ed68b3ba1e027d , this should address the last issue

**Comment by lucaderi** [comment]
Verified as fixed
