### ISSUE TITLE
Can't delete a sub-interface

### ISSUE THREAD

**Issue by thomasbruchet** [ntop/ntopng#6045]
Hello,

I've a problem on some Interfaces created with Custom Traffic Disaggregation, I can not delete them. 
I had created several new interface and named them like that: VLAN_name(VLAN_ID)
I've deleted all the old interface that was just named like "VLAN_name" withtout the "(xxx)" withtout any problem.

The problem occur when I create a Custom Traffic Disaggregation with "( )" in the name and try to delete it.

Here is the list of all sub-interface that still exist for one physical interface, I've the problem on 2 differents physical interface.
![image](https://user-images.githubusercontent.com/86605223/140286739-0aa7a6b2-b32e-4ad5-853b-b82b9e7a3115.png)

---

When I create and then delete an interface whose name does not contain "( )", the pop-up window that appears contains a text message in a yellow highlighting. 
![image](https://user-images.githubusercontent.com/86605223/140285654-cb32442f-f2f8-4133-9105-687a78d285cc.png)

When I create and then delete an interface whose name does contain "( )", the pop-up window that appears do not contains a text message and no yellow highlighting. 
![image](https://user-images.githubusercontent.com/86605223/140285814-3c1192e7-7782-405d-bac4-711d0a273fc2.png)
And I have this message in logs
`04/Nov/2021 09:48:31 [LuaEngine.cpp:1253] WARNING Script failure [/usr/share/ntopng/scripts/lua/pro/enterprise/delete_sub_interface.lua][...opng/scripts/lua/pro/enterprise/delete_sub_interface.lua:22: Missing interface index]`

When I try to delete an interface without brackets, cancel the popup then try to cancel an interface with brackets, the popup that appear is the same than the one with brackets and if I click on [Delete], the interface that is deleted is the one without brackets as mentionned in the popup but not the one that I've asked for. 
![image](https://user-images.githubusercontent.com/86605223/140286112-fd0e3cb6-ddaa-4b94-87c2-928452eed9a5.png)

---------------

I've tried to change the "Custom Name" of those interfaces but that just create an alias, the name of the sub-interface did'nt change and I can not delete them too. 

I've tried to find any configuration files where thoses interface can be writed in without success. I'd reboot the server too in case of ghost entry in a database without success.
If it is necessary, a purge all the ntopng settings and interfaces created can be done, I will redo them but I need that problem solved.

Is someone can help me on this please ?

**Comment by MatteoBiscosi** [comment]
Hi @thomasbruchet Thanks to your help I was finally able to reproduce this behavior. in my lab i was able to fix it and now everything works fine, please wait for a few hours and a new update should be available. Are you using Dev or Stable version (5.1 or 5.0)? currently it's fixed only for Dev, if you are using the Stable let me know and I'll fix there too.

**Comment by thomasbruchet** [comment]
Hello;

I'm running the stable version I guess, I don't know where to find this information. 
When I do an apt update:
```
Réception de :3 https://packages.ntop.org/apt/buster x64/ InRelease [2 153 B]  
Réception de :4 https://packages.ntop.org/apt/buster all/ InRelease [2 153 B]  
Réception de :5 https://packages.ntop.org/apt/buster x64/ Packages [3 869 B]  
Réception de :6 https://packages.ntop.org/apt/buster all/ Packages [2 797 B]  
```
My version is ntopng Enterprise M v.5.1.211102

**Comment by MatteoBiscosi** [comment]
Hi @thomasbruchet , you have the dev version, the dev version is ntopng 5.1 instead the stable one is ntopng 5.0.
A new update should be ready soon

**Comment by thomasbruchet** [comment]
Hello,
After the update, I was able to delete the lines without any problem. 
Thank you for your support.
