### ISSUE TITLE
Invalid SQL Code

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6046]
Alert code is full of invalid SQL code that is tolerated by SQLite but that is wrong and thus errored with other DBs such as ClickHouse.

Examples:

- Column `vlan_id` is not under aggregate function and not in GROUP BY: While processing srv_ip, vlan_id, srv_name, count() AS count. (NOT_AN_AGGREGATE) (version 21.10.2.15 (official build))][215][SELECT srv_ip, vlan_id, srv_name, count(*) count FROM flow_alerts WHERE (tstamp >= 1636046064 AND tstamp <= 1636047864) AND ( alert_status = 0 ) AND ((cli_ip = '192.168.1.187' OR srv_ip = '192.168.1.187')) GROUP BY srv_ip ORDER BY count DESC LIMIT 10]
- Column `tstamp_end` is not under aggregate function and not in GROUP BY: While processing 4 AS entity_id, tstamp_end - tstamp AS duration, count() AS count. (NOT_AN_AGGREGATE) (version 21.10.2.15 (official build))][215][ SELECT 4 entity_id, (tstamp_end - tstamp) duration, count(*) as count FROM `flow_alerts` WHERE ( alert_status = 0 ) AND (tstamp >= 1636046636 AND tstamp <= 1636048436)    ]
 - Column `tstamp_end` is not under aggregate function and not in GROUP BY: While processing 4 AS entity_id, tstamp_end - tstamp AS duration, count() AS count. (NOT_AN_AGGREGATE) (version 21.10.2.15 (official build))][215][ SELECT 4 entity_id, (tstamp_end - tstamp) duration, count(*) as count FROM `flow_alerts` WHERE ( alert_status = 0 ) AND (tstamp >= 1636046636 AND tstamp <= 1636048436)    ]

Such errors cause other errors
04/Nov/2021 18:54:01 [LuaEngine.cpp:1253] WARNING: Script failure [/home/deri/ntopng/scripts/lua/pro/rest/v2/get/flow/alert/general_stats.lua][...i/ntopng/scripts/lua/modules/alert_store/alert_store.lua:755: attempt to index a nil value (field 'integer index')]
04/Nov/2021 18:58:46 [LuaEngine.cpp:1253] WARNING: Script failure [/home/deri/ntopng/scripts/lua/rest/v2/get/all/alert/ts.lua][...i/ntopng/scripts/lua/modules/alert_store/alert_store.lua:938: attempt to compare number with nil]

The need to be fixed to make them work both in SQLite and ClickHouse

**Comment by cardigliano** [comment]
It seems all the queries and deletes are working now. More tests will follow to check all the cases.

**Comment by lucaderi** [comment]
Something is not working yet

11/Nov/2021 10:37:10 [MySQLDB.cpp:867] Successfully connected to MySQL [default@127.0.0.1:9004] for interface enp0s31f6
11/Nov/2021 10:37:10 [MySQLDB.cpp:1015] ERROR: MySQL error: [Code: 215. DB::Exception: Column `FIRST_SEEN` is not under aggregate function and not in GROUP BY: While processing FIRST_SEEN DESC. (NOT_AN_AGGREGATE) (version 21.10.2.15 (official build))][215][SELECT IPv4NumToString(IPV4_SRC_ADDR) IPV4_SRC_ADDR,IPv4NumToString(IPV4_DST_ADDR) IPV4_DST_ADDR,VLAN_ID,L7_PROTO,SUM(TOTAL_BYTES) AS bytes FROM flows WHERE (INTERFACE_ID=0) AND (FIRST_SEEN >= 1636621626) AND (LAST_SEEN <= 1636623426) GROUP BY IPV4_SRC_ADDR,IPV4_DST_ADDR,VLAN_ID,L7_PROTO ORDER BY FIRST_SEEN DESC LIMIT 10 ]
11/Nov/2021 10:37:10 [LuaEngine.cpp:1253] WARNING: Script failure [/home/deri/ntopng/scripts/lua/pro/rest/v2/get/db/historical_db_search.lua][...png/scripts/lua/pro/modules/flow_db/clickhouse_utils.lua:579: bad argument #1 to 'for iterator' (table expected, got nil)]

**Comment by lucaderi** [comment]
Verified as fixed
