### ISSUE TITLE
Add interface_id in Alert Queries

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6047]
As in ClickHouse alerts are global to all interfaces, a new interface_id column has been added. This is to request to modify all the alert-related queries adding interface_id in all select queries to avoid mixing alerts coming from different interfaces

**Comment by MatteoBiscosi** [comment]
Added interface id into the where clause of Clickhouse queries as requested. e.g. `SELECT 4 entity_id, (tstamp_end - tstamp) duration, count(*) as count FROM `flow_alerts` WHERE (tstamp >= 1636108670 AND tstamp <= 1636110470) AND ( alert_status = 0 ) AND (interface_id = 1) `

**Comment by lucaderi** [comment]
Verified as fixed
