### ISSUE TITLE
Protocol Filtering is Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6048]
![Screen Shot 2021-11-04 at 19 10 58](https://user-images.githubusercontent.com/4493366/140395878-af26c83f-f9ee-436b-9acb-6aa1f5e5c7a7.png)

As you can see filtering is not working and there is this error on the console
04/Nov/2021 19:10:51 [LuaEngine.cpp:1253] WARNING: Script failure [/home/deri/ntopng/scripts/lua/pro/rest/v2/get/db/historical_db_search.lua][...png/scripts/lua/pro/modules/flow_db/clickhouse_utils.lua:189: attempt to concatenate a nil value]

**Comment by cardigliano** [comment]
This has been addressed, please verify

**Comment by lucaderi** [comment]
![image](https://user-images.githubusercontent.com/4493366/141281868-5e1e2fdd-d6d8-46e6-ab31-6d5559d4d1f2.png)

Filter is inconsistent

**Comment by MatteoBiscosi** [comment]
Now should be fixed correctly with clickhouse but cannot be fixed right now with nIndex.

**Comment by lucaderi** [comment]
Verified as fixed
