### ISSUE TITLE
"Traffic Recording Provider" menu doesn't show when it was through n2disk. 

### ISSUE THREAD

**Issue by Yoshihiro-jp** [ntop/ntopng#6049]
Hello,

I think that this is really a bug.

Like attached ntopng.conf I set two interfaces(-i=tcp://*:5556c and -i=enp3s0f1).
The "-i=tcp://*:5556c" doesn't show the "Traffic Recording Provider" menu like the "001.png" but The "-i=enp3s0f1" shows it like "002.png". I think that this is strange and wrong.
The ntopng should show the "Traffic Recording Provider" menu when I chose the  "-i=tcp://*:5556c".

This problem happens when I set the ntopng via n2disk like attached config files.

Version:        5.0.211026 [Enterprise/Professional build]
GIT rev:        5.0-stable:2c37b2a1233e3c494d09f478653bf36fba9b3fee:20211026
Pro rev:        r4204
Built on:       Ubuntu 20.04.3 LTS

regards,
Yoshihiro
[Traffic Recording Provider menu.zip](https://github.com/ntop/ntopng/files/7480143/Traffic.Recording.Provider.menu.zip)

**Comment by cardigliano** [comment]
@Yoshihiro-jp please note that there are a few conditions for enabling the traffic recording on each interface, it is likely one of those conditions is not satisfied, any chance we can debug this together in a call (or even better provide ssh access)?

**Comment by Yoshihiro-jp** [comment]
> @Yoshihiro-jp please note that there are a few conditions for enabling the traffic recording on each interface, it is likely one of those conditions is not satisfied, any chance we can debug this together in a call (or even better provide ssh access)?

Hi, I already sent the information to access our server through e-mail.
Kindly check it.

regards,
Yoshihiro

**Comment by cardigliano** [comment]
@Yoshihiro-jp please check this now, you should be able to use the "Traffic Recording Provider" now

**Comment by Yoshihiro-jp** [comment]
@cardigliano thank you for your action I could see the "traffic recording provider menu" now but the traffic hadn't shown. Since I changed from "--interface=zc:enp3s0f0" to --interface=enp3s0f0 it starts to show the traffic I think that this is another problem.
![zc](https://user-images.githubusercontent.com/58843707/140848022-54ee497d-050c-4691-b659-29524b0a14af.png)

I would verify it again and If I noticed something I would report it.

regards,
Yoshihiro

**Comment by cardigliano** [comment]
@Yoshihiro-jp it seems I am no longer able to access this system. Do you have n2disk running on zc:enp3s0f0 and exporting flows through ZMQ to ntopng?

**Comment by Yoshihiro-jp** [comment]
> @Yoshihiro-jp it seems I am no longer able to access this system. Do you have n2disk running on zc:enp3s0f0 and exporting flows through ZMQ to ntopng?

Dear @cardigliano , Thank you for your answer.
Yes you are right. I run the n2disk running on zc:enp3s0f0 and exporting flows through ZMQ to ntopng.

I don't know the reason but now it works fine like attached file.
I could not find when it was fixed...

![okayn2disk](https://user-images.githubusercontent.com/58843707/141421696-a290eb53-f097-49b6-bc19-0a5500d37618.png)


regards,
Yoshihiro

**Comment by cardigliano** [comment]
Ok find, thank you for the update
