### ISSUE TITLE
Custom applications,

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#6050]
Can I specify a specific port to add an IP address as an application? For example, I define TCP: 8045 of 192.168.0.100 as our custom a protocol?

**Comment by simonemainardi** [comment]
Yes, see

https://github.com/ntop/nDPI/blob/9abf528c8ed2256c7a091d9f69c506987c8c756a/example/protos.txt#L39

For examples and limitations

**Comment by MaoPann** [comment]
What if I want UDP for an IP? It seems that UDP or TCP cannot be specified here.
