### ISSUE TITLE
Degraded Performance - notifications.lua

### ISSUE THREAD

**Issue by thomasbruchet** [ntop/ntopng#6051]
Hello,

I've an issue about Degraded Performance.
The notifications.lua seems to be stuck and a reboot don't solve the problem. 
If I understand correctly, the process restart each 3 secondes and since the reboot all of those have running slow.
37min 41s= 2261.000s
2261/716=3.15sec
![image](https://user-images.githubusercontent.com/86605223/140486582-99a0e198-dd7e-4c1f-92b7-a762e7e8b67a.png)

I don't know if this is relevant but I've also that informatons in recipients
The fill is full and "Drops" grow more and faster than "Uses"
![image](https://user-images.githubusercontent.com/86605223/140487518-58d1e58c-4bd0-4eba-9b27-b6f443d487b0.png)

What informations could be relevant to looking for to solve this issue ?
How can I debug it ?

**Comment by lucaderi** [comment]
I believe SQLite is unable to write alerts as fast as possible. Possible workarounds
- silence sole alerts that are not relevant
- check if the disk is slow or if SQLite has too many records

Long term solution: we are adding clickhouse support to speed up all this. Next week a first version should be available for testing
