### ISSUE TITLE
Broken Observation Point Menu

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6053]
The observation menu works with flows
![Screen Shot 2021-11-05 at 20 49 33](https://user-images.githubusercontent.com/4493366/140570215-736bf426-7588-4975-a720-e964e0013494.png)
but it disappears when displaying host flows
![Screen Shot 2021-11-05 at 20 50 56](https://user-images.githubusercontent.com/4493366/140570317-74925429-8846-466f-9dc4-fc6163d89097.png)

**Comment by simonemainardi** [comment]
Addressed

![image](https://user-images.githubusercontent.com/3397663/147271978-5842b2b8-d0cc-4af2-a108-b0d09247bf76.png)
