### ISSUE TITLE
Logstash Flow Export Issue

### ISSUE THREAD

**Issue by 3po4** [ntop/ntopng#6054]
I'm running the latest NTOPNG Docker instance and am attempting to export flows to a remote Logstash. However, I do not see the data in stdout nor do I see ntopng attempting to communicate with Logstash (netstat connections). Is there a log I can review to troubleshoot the flow export? 

This is the command I'm using for running ntopng in docker:

sudo docker run -d -it -p 3000:3000 -v $(pwd)/ntopng.license:/etc/ntopng.license:ro --net=host ntop/ntopng:latest -i en0 -F "logstash;192.168.10.250;tcp;5510"

This is my Logstash config:

input {
    tcp {
        host => "192.168.10.250"
       port => 5510
       codec => json
       type => "ntopng-ls"
      }
   }
   
   filter {
      if [type] == "ntopng-ls" {
       date {
                 match => ["ntop_timestamp" , "yyyy-MM-dd'T'HH:mm:ss.SSSZ"]
                   target => "@timestamp"
       }
      # Clear redundant field value
       mutate { 
          remove_field => ["ntop_timestamp"] 
       }
      if "" not in [IPV4_SRC_ADDR] and "" not in [IPV6_SRC_ADDR] {
          drop {}
       }
     }
   }
   
   output {
     if [type] == "ntopng-ls" {
    stdout { codec => rubydebug }
      }
    }

I've tested the Logstash socket by doing a telnet to port 5510 and and dumps to stdout so I know it's listening. 

Thanks

**Comment by simonemainardi** [comment]
logstash support has been dropped in https://github.com/ntop/ntopng/commit/e1158fb855a1ec3f9e88380c9264a15734b4de6e in favor of syslog. See commit description.
