### ISSUE TITLE
Description/Other issues fields "Destroy" alert page table

### ISSUE THREAD

**Issue by MatteoBiscosi** [ntop/ntopng#6055]
As you can see from the screenshot below, if description or other issues fields are too long then they are going to break out from the table layout and cause this aesthetic bug, it is requested to find a solution to this issue.
![Screenshot from 2021-11-08 10-19-21](https://user-images.githubusercontent.com/49585191/140716194-d9bd81f7-f395-4efe-a2e6-b241d43ee1de.png)

**Comment by lucaderi** [comment]
Another bug is that the same information (e.g the URL) is repeated over and over instead of once. Please consider using bullets in order to have a list instead of a long string.

**Comment by MatteoBiscosi** [comment]
the bug having the same string repeated over and over should be fixed, working on a way to fix the description too long

**Comment by MatteoBiscosi** [comment]
The issue now should be fixed. I added a max length to description and other issues string and if exceeded then a tooltip is going to be shown up.

**Comment by MatteoBiscosi** [comment]
Verified as fixed
