### ISSUE TITLE
Add Latency Information in Flow Database

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6059]
Both ntopng and nProbe report the latency
- CLIENT_NW_LATENCY_MS
- SERVER_NW_LATENCY_MS

This is to request to add to the DB latency information to enable the creation of latency-based reports.

**Comment by simonemainardi** [comment]
Implemented in referenced and companion pro commit. Implementation tested both using packet interfaces and via ZMQ.

Example:

```
devel :) select * from flows where SERVER_NW_LATENCY_MS > 0 limit 1 \G

SELECT *
FROM flows
WHERE SERVER_NW_LATENCY_MS > 0
LIMIT 1

Query id: 811c91eb-c422-40db-ac93-b85fb0452f4e

Row 1:
──────
IP_PROTOCOL_VERSION:  4
FLOW_TIME:            2021-11-10 11:52:08
FIRST_SEEN:           2021-11-10 11:51:36
LAST_SEEN:            2021-11-10 11:52:08
VLAN_ID:              0
PACKETS:              104
TOTAL_BYTES:          42816
SRC2DST_BYTES:        3296
DST2SRC_BYTES:        39520
SRC2DST_DSCP:         4
DST2SRC_DSCP:         4
PROTOCOL:             6
IPV4_SRC_ADDR:        3232236185
IPV6_SRC_ADDR:        ::
IP_SRC_PORT:          54194
IPV4_DST_ADDR:        3232236254
IPV6_DST_ADDR:        ::
IP_DST_PORT:          22
L7_PROTO:             92
L7_CATEGORY:          12
FLOW_RISK:            0
INFO:
PROFILE:
NTOPNG_INSTANCE_NAME: devel
INTERFACE_ID:         1
STATUS:               57
SRC_COUNTRY_CODE:     0
DST_COUNTRY_CODE:     0
SRC_LABEL:
DST_LABEL:
SRC_MAC:              220195690588088
DST_MAC:              274658134861056
COMMUNITY_ID:         1:LbsJTBjTbx9eplc+Oxn4peGL5JM=
SRC_ASN:              0
DST_ASN:              0
PROBE_IP:             3232236254
OBSERVATION_POINT_ID: 0
SRC2DST_TCP_FLAGS:    24
DST2SRC_TCP_FLAGS:    24
SCORE:                10
L7_PROTO_MASTER:      0
CLIENT_NW_LATENCY_MS: 0
SERVER_NW_LATENCY_MS: 18

1 rows in set. Elapsed: 0.004 sec.
```

**Comment by lucaderi** [comment]
This ticket is incomplete as the GUI does not report any laten
![Screen Shot 2021-11-11 at 11 22 07](https://user-images.githubusercontent.com/4493366/141281564-5d30069a-8e48-493f-a11f-786320d6869c.png)
ce

**Comment by simonemainardi** [comment]
Said that the original issue was asking to add latency information to the flow database for the generation of latency-based reports - not to the UI, additional request is now implemented.

![image](https://user-images.githubusercontent.com/3397663/141329566-1fa3a955-7a39-40c5-80e9-b1d1f917ba40.png)

**Comment by lucaderi** [comment]
![Screen Shot 2021-11-11 at 18 26 26](https://user-images.githubusercontent.com/4493366/141342076-608cc827-7390-4e4e-8894-4a4fb6af0118.png)
Something odd is that (see your screenshot) you have only one latency (either two or none if the TWH was not observed). In addition there is no way to filter data

**Comment by simonemainardi** [comment]
- There is only one latency as you know that latency is calculated with reference to the observation point that in this case is the client so it becomes zero.
- With @cardigliano we have decided that sorting is enough and not to add filters on latency as this would over-complicate the code.

**Comment by lucaderi** [comment]
![Screen Shot 2021-11-11 at 18 37 47](https://user-images.githubusercontent.com/4493366/141343754-34b4f126-0644-40a6-81b3-4418acf7081d.png)
Sub msec latency is not reported and this is another problem

**Comment by simonemainardi** [comment]
After internal review we need to
- use microseconds or floats
- allow searches and filters

**Comment by simonemainardi** [comment]
Check Now.

![image](https://user-images.githubusercontent.com/3397663/141497732-e678b124-310c-4309-9ec2-ef541207edf9.png)


Notes:
- Latencies are stored in the database as microseconds. Conversions are applied to show milliseconds
- Must show three decimal digits or the approximation will fail to find records in the database
- Clicking multiple times on a latency keeps adding filters. This is not an issue with latencies, this is the current behavior of all filters and need to be fixed but is not part of this issue.

**Comment by lucaderi** [comment]
Verified as fixed

**Comment by mahaveer3** [comment]
bro can you explain what is L7_PROTO  ?

**Comment by cardigliano** [comment]
That's the Application protocol ID detected by nDPI

**Comment by mahaveer3** [comment]
> nDPI

which nDPI protocol should i use to find Application protocol ID ?
