### ISSUE TITLE
ntopng closes by itself ???

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#606]
ntopng was started normaly and worked OK then I detected that it was down (tcp 3000)
so I checked server and ntop was not started

in checking logs, I have these lines when it failed 
Jun  9 13:47:06 ntop-ia kernel: [184026.132698] show_signal_msg: 39 callbacks suppressed
Jun  9 13:47:06 ntop-ia kernel: [184026.132711] ntopng[11881]: segfault at 7f00c7227050 ip 00007f00c7227050 sp 00007f00fe3d2bd8 error 15

ntopng 2.3.160608

Nicolas

**Comment by simonemainardi** [comment]
please, generate a core dump and post both the code dump and the ntopng binary used

**Comment by Niko78** [comment]
v.2.3.160609 [Professional Edition]
GIT rev:   dev:63879f9635448a83cfc58a5fe1add673aff7c597:20160609
Pro rev:   r636
Built on:  Ubuntu 14.04.4 LTS

[dump.zip](https://github.com/ntop/ntopng/files/307494/dump.zip)

let me know if it's ok

Nico

**Comment by simonemainardi** [comment]
no:

```
$ file dump.log
dump.log: ASCII text
```

Follow: http://www.ntop.org/support/faq/how-to-report-a-bug-on-ntop-apps/

Also paste full configuration used to startup ntopng

**Comment by simonemainardi** [comment]
@Niko78 did you figured out how to produce a core dump? Or actually what was the cause behind the supposed crash?

**Comment by Niko78** [comment]
no crash yet

**Comment by simonemainardi** [comment]
recent nDPI commits may have fixed the issue. Please, re-open a new issue and enclose the core dump as explained if you experience the crash.
