### ISSUE TITLE
Service / Periodicity Map - show first and last entry

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6062]
Dear ntop Team
In the service and periodicity map one filter is "All Time". Would it be possible to show date & time of oldest and newest entry showed in the map? As now with filter "All Time" I dont know how much past my data series is going.
Thank you.

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu as you can see, now it is possible to check the first and the last entry of the map. Obviously filtering (protocols for example) is going to change the first and last entry (depending on the filters currently selected).
![Screenshot from 2021-12-01 13-34-59](https://user-images.githubusercontent.com/49585191/144235427-5cdeb947-f30c-4571-a1de-9824b506222b.png)
![Screenshot from 2021-12-01 13-35-15](https://user-images.githubusercontent.com/49585191/144235429-84382028-ab6e-407f-9375-7c59fc8e19ae.png)

**Comment by martinscheu** [comment]
Thanks @MatteoBiscosi, great work.
