### ISSUE TITLE
Unexpected DHCP server found - false positives

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6063]
Dear ntop Team
The alert "Unexpected DHCP server found" is alerting falsely DHCP servers which are in the DHCP server list of the Check.
Thank you.
Martin

**Comment by simonemainardi** [comment]
Do you specify an IPv4 address or a symbolic name?

Please, check the alert. Are you seeing the whitelisted server as client or as server?

**Comment by martinscheu** [comment]
I specify IP addresses and I see them as server
But I also see this: Unexpected DHCP server found: 255.255.255.255 [Score: 100] [Predominant Traffic: Cli Srv]

**Comment by simonemainardi** [comment]
I am getting the expected behavior using the latest build. Can you please check and report.

**Comment by martinscheu** [comment]
yes, seems to work now. thank you.
