### ISSUE TITLE
Actual Traffic - Abnormal bandwich

### ISSUE THREAD

**Issue by thomasbruchet** [ntop/ntopng#6067]
Hello

I've a bug on the Traffic Dashboard after Custom Traffic Disaggregation.
After I used the Custom Traffic Disaggregation to create new sub-interface, those sub-interface have abnormal bandwidth

Here is an exemple just ater the restart of ntopng to validate the creation of the subinterface. According to ntopng, I use a link in Tbit/s on top  local Talkers (The best I saw was 158Tbit/s) 👍 But that is not relevant according to the Network Interfaces Realtime Traffic

![image](https://user-images.githubusercontent.com/86605223/141142302-da86c7df-185c-4902-aaae-d1d0c78c2b15.png)

Is someone have an idea about that ?

**Comment by simonemainardi** [comment]
It may just be that it takes a while for stats to generate. Can you please let it run for 5~10 minutes and see if you keep getting those values?

**Comment by thomasbruchet** [comment]
Hello;
The last restart was 6:30 hours ago and I think I break the japaneese  world record ! ;)
![image](https://user-images.githubusercontent.com/86605223/141482645-aecf5656-7df7-4ff5-b367-95ae15f6c00f.png)

**Comment by simonemainardi** [comment]
Show the disaggregation configuration used.

**Comment by thomasbruchet** [comment]
Hello,

Here is the traffic disaggregation that I use.
![image](https://user-images.githubusercontent.com/86605223/142862461-01a59674-d2b1-4f51-baf2-0fb2c626bc10.png)

**Comment by simonemainardi** [comment]
I can confirm the bug. Something wrong with totals and thus throughputs in disaggregated interfaces.

![image](https://user-images.githubusercontent.com/3397663/143026923-4e0d68c4-be20-4552-8e88-a65c5dce85d0.png)


Debugging.

**Comment by simonemainardi** [comment]
Resolved. Pro commit for sub interface. New build is in progress. Please, hold on a couple of hours, update, and it will work. Thanks for reporting.

**Comment by thomasbruchet** [comment]
Hello,

The update has resolved the problem but also create a new one.
I've some disaggregated interfaces that show 0 usage now.
For exemple with this is an important VLAN with all the admin teams and the disaggregation is done on the Internet Interface. I should have data.
![image](https://user-images.githubusercontent.com/86605223/143246040-ce9748ef-67fa-417f-9063-86b85c199653.png)

Here is the log system after the service had restarted
`24/Nov/2021 14:15:27 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:15:27 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 9.8868042889663e+18
24/Nov/2021 14:15:27 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:15:27 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.3755446657596e+19
24/Nov/2021 14:15:27 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:15:27 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.673486327207e+19
24/Nov/2021 14:15:27 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:15:27 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.100578618357e+19
24/Nov/2021 14:15:27 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:15:27 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.184667268452e+19
24/Nov/2021 14:11:19 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:11:19 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 9.8868042859568e+18
24/Nov/2021 14:11:19 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:11:19 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.375544665736e+19
24/Nov/2021 14:11:19 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:11:19 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.6734863268787e+19
24/Nov/2021 14:11:19 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:11:19 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.1005786183334e+19
24/Nov/2021 14:11:19 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:11:19 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.184667268138e+19
24/Nov/2021 14:06:15 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:06:15 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 9.8868042837464e+18
24/Nov/2021 14:06:15 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:06:15 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.3755446656741e+19
24/Nov/2021 14:06:15 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:06:15 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.6734863266297e+19
24/Nov/2021 14:06:15 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:06:15 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.1005786182714e+19
24/Nov/2021 14:06:12 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:06:12 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.1846672678705e+19
24/Nov/2021 14:01:58 [housekeeping.lua:38] [lists_utils.lua:717] Category Lists (22538 hosts, 78158 IPs, 0 JA3) loaded in 4 sec
24/Nov/2021 14:01:58 [NetworkInterface.cpp:437] ERROR Internal error: nested nDPI category reload`
