### ISSUE TITLE
Cant add recipient with Telegram endpoint

### ISSUE THREAD

**Issue by playday3008** [ntop/ntopng#6068]
'Add' button inactive after click, and nothing happened
I am used docker-compose for ntop

**Comment by MatteoBiscosi** [comment]
Hi @playday3008 what do you mean by button inactive after click? could you please share some screenshot?
In the browser developing tools is there some error? (to check it please right click on the browser, and click 'inspect' or 'developer tools', or as a short cut you can click f12, depends on the browser; then check into the console tab if there is some error).

**Comment by playday3008** [comment]
Well, IDK how, but after reinstall it works, but still have a little problem with regex
![obraz](https://user-images.githubusercontent.com/18056374/142879040-e047d97c-99fa-42c8-a82c-4772f365cd96.png)
![obraz](https://user-images.githubusercontent.com/18056374/142878823-a9e182d5-bab3-4ff4-9457-45c5b2915af9.png)
REGEXES doesn't have 'telegram_channel' property

**Comment by MatteoBiscosi** [comment]
Hi @playday3008 thanks a lot for your help, I was able to fix the problem, in the next release everything should be alright.
However which ntopng version are you using, dev or stable? the fix right now is in the dev version.

**Comment by playday3008** [comment]
stable (v4.2....)

**Comment by MatteoBiscosi** [comment]
sorry but the 4.2 version is no more supported, could you migrate to the stable v 5.0? i can fix there too

**Comment by playday3008** [comment]
Docker stable version is v4.2, and I can't migrate to V5 (latest on docker) bcoz it use too much CPU

**Comment by MatteoBiscosi** [comment]
I'm really sorry then but like i said the v4.2 is no more supported and i cannot release fix there. I fixed it for the v 5.0, if in the future you are able to migrate to v5 then the issue there is fixed

**Comment by MatteoBiscosi** [comment]
Hi @playday3008 after some changes we reduced the usage of resources (see #6091) so if you want to try updating to ntopng 5.1 version, you can try.

**Comment by playday3008** [comment]
> Hi @playday3008 after some changes we reduced the usage of resources (see #6091) so if you want to try updating to ntopng 5.1 version, you can try.

I am using docker version

**Comment by playday3008** [comment]
@MatteoBiscosi  Since the docker version has already been updated, I tried to run ntopng on my server
Guess when I start and stop ntopng :)

![image](https://user-images.githubusercontent.com/18056374/144894998-9cea7a1a-be0b-455e-bc2e-fc610af249ad.png)
