### ISSUE TITLE
Suspicious DNS Traffic Alert is poor

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6069]
Suspicious DNS traffic alert does not report any context (in particular the DNS record requested) and this needs to be added. nDPI changes are required in addition to ntopng support

**Comment by MatteoBiscosi** [comment]
Many changes were done during this period of time and now nDPI is able to report info like "why this alert was triggered" and this should be enough information. Please reopen the ticket if the information shown is not enough
