### ISSUE TITLE
ntop sends mails ?

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#607]
with ntop 2.3.160608
it seems to try to send mails

in my logs I have ton of lines like that
Jun  9 13:34:01 ntop-ia CRON[3097]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Jun  9 13:34:13 ntop-ia postfix/sendmail[3187]: fatal: open /etc/postfix/main.cf: No such file or directory
Jun  9 13:35:01 ntop-ia CRON[3359]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Jun  9 13:35:13 ntop-ia postfix/sendmail[3449]: fatal: open /etc/postfix/main.cf: No such file or directory
Jun  9 13:36:01 ntop-ia CRON[3620]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Jun  9 13:36:13 ntop-ia postfix/sendmail[3710]: fatal: open /etc/postfix/main.cf: No such file or directory
Jun  9 13:37:01 ntop-ia CRON[3881]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Jun  9 13:37:13 ntop-ia postfix/sendmail[3971]: fatal: open /etc/postfix/main.cf: No such file or directory
Jun  9 13:38:01 ntop-ia CRON[4142]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Jun  9 13:38:13 ntop-ia postfix/sendmail[4232]: fatal: open /etc/postfix/main.cf: No such file or directory
Jun  9 13:39:01 ntop-ia CRON[4404]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Jun  9 13:39:13 ntop-ia postfix/sendmail[4494]: fatal: open /etc/postfix/main.cf: No such file or directory

why ? 

Nico

**Comment by ValentinaViscarelli** [comment]
@Niko78 
How can you be sure it's ntop?
If I see the logs I cannot understand who has printed sendmail logs.

**Comment by Niko78** [comment]
well it's at the same rythm than ntop cron...
I will recheck tomorrow if I can get more details

**Comment by hatclub** [comment]
I can't think of a circumstance where having a completely broken local mail system is a great idea, so it might be worth fixing your MTA (or switching for another basic one that just forwards local mail to a remote destination) and then you'll be able to see exactly what the emails are!

**Comment by Niko78** [comment]
well I configured postfix with main.cf available and no more log
