### ISSUE TITLE
Improve 'All' Time in Alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6070]
![Screen Shot 2021-11-11 at 10 50 44](https://user-images.githubusercontent.com/4493366/141281099-cf24c366-6ba1-42d2-8c15-18efe1943124.png)

Instead of using epoch 0, please start from the first record time present in the database.

This fix needs to be implemented for both flows and alerts.

**Comment by simonemainardi** [comment]
All time is now calculated (and cached) using the earliest alert/flow available.

**Comment by lucaderi** [comment]
Verified as fixed
