### ISSUE TITLE
Old code breaks Interface Layout using ClickHouse

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6072]
![image](https://user-images.githubusercontent.com/4493366/141293426-bccfd886-a425-46e9-b454-50d39897b7fc.png)

Issues
- clicking on the highlighted icon causes this error

11/Nov/2021 12:50:11 [MySQLDB.cpp:1015] ERROR: MySQL error: [Code: 60. DB::Exception: Table ntopng.flowsv6 doesn't exist. (UNKNOWN_TABLE) (version 21.10.2.15 (official build))][60][select COUNT(*) AS TOT_FLOWS, SUM(IN_BYTES + OUT_BYTES) AS TOT_BYTES, SUM(PACKETS) AS TOT_PACKETS FROM flowsv6 where FIRST_SWITCHED <= 1636631401 and FIRST_SWITCHED >= 1636631101 AND (NTOPNG_INSTANCE_NAME='ubuntu18'OR NTOPNG_INSTANCE_NAME IS NULL OR NTOPNG_INSTANCE_NAME='') AND (INTERFACE_ID='0') AND VLAN_ID=0]

- the "Chart" tab has to be removed

**Comment by simonemainardi** [comment]
Addressed both for the interface and the host page. Commits are under pro.

**Comment by lucaderi** [comment]
Verified as fixed
