### ISSUE TITLE
Report certificate validity duration in alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6073]
<img width="1547" alt="image" src="https://user-images.githubusercontent.com/4493366/141310699-6c6b6f3f-1358-46ac-941c-54b9e3cf0617.png">

**Comment by simonemainardi** [comment]
Does this happen via ZMQ? Packet interfaces should support it so my guess is that the one shown is a ZMQ interface with reduced information.

**Comment by MatteoBiscosi** [comment]
Implemented as requested, now TLS alerts are going to have additional information like tls certificate validity and tls version; if more info are needed please feel free to comment

**Comment by simonemainardi** [comment]
This fix is invalid and causes duplicated code. TLS info was already serialized, for TLS-based alerts, in `src/flow_alerts/FlowRiskTLSAlert.cpp`. Issue was, as already commented, to understand why this was not read in Lua.

**Comment by MatteoBiscosi** [comment]
This information should be added to all tls alerts, like for http, dns and icmp to have a better context in the alert not just to the ones with flow risk. So I'll remove the info serialized by FlowRiskTLSAlert.cpp. Other then that the info was read from Lua but not added to the Description.

**Comment by simonemainardi** [comment]
> This information should be added to all tls alerts, like http, dns and icmp

Certificate validity is only for TLS. It is pointless to add it to HTTP, DNS, or ICMP. This is why it was added to the TLS subclass.

**Comment by MatteoBiscosi** [comment]
I meant to add all the TLS information to all TLS alerts, like for HTTP alerts, recently all HTTP information were added to all HTTP alerts, not to add the tls info even to the http alerts. With the last update all TLS info were removed from just the Flow Risk TLS Alerts, in this way there is no duplicate code and all TLS alerts now have a better context.

**Comment by simonemainardi** [comment]
Clean solution is to have a TLS subclass for all TLS-based alerts, that is, what `FlowRiskTLSAlert` does. If you have TLS-based alerts that are not associated with flow risks (do you have them?) then a class `TLSAlert` should be used.

Using `if(flow->isTLS())` in the base class breaks OO and inheritance logic.

**Comment by lucaderi** [comment]
Verified as fixed using nDPI/tests/pcap/tls_certificate_too_long.pcap
