### ISSUE TITLE
Rename SQLite EndPoint/Recipient

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6076]
With the addition of ClickHouse it is required to rename builtin_recipient_sqlite and builtin_endpoint_sqlite to a neutral name as it serves both ClickHouse and SQLite

**Comment by simonemainardi** [comment]
![image](https://user-images.githubusercontent.com/3397663/143277565-f5dd4adb-7a0f-431f-b803-c1182e7adae4.png)

**Comment by lucaderi** [comment]
Verified as fixed
