### ISSUE TITLE
Question on NAT

### ISSUE THREAD

**Issue by Spectre5** [ntop/ntopng#6077]
I'm using OPNSense and I have a DNAT rule to force DNS queries to my pihole.  The pihole filters and then uses unbound on the OPNSense box as upstream.  When looking at ntopng, I see traffic to and from 8.8.8.8 and 8.8.4.4 by some IOT devices (presumably with hard-coded DNS).  I'm confident that the DNAT rule is working as if I set an override in Unbound and `dig @8.8.8.8 test.com` it from my desktop, I get the IP as per the override.

However, when using ntopng, I see the traffic as if it is to and from 8.8.8.8/8.8.4.4.  So ntopng must be getting the address before the DNAT takes place.  Is there any way to change this?  I want to be able to verify and see zero traffic to 8.8.8.8, 8.8.4.4, and other DNS servers.  Or at least know in ntopng that a redirect happened.

**Comment by lucaderi** [comment]
ntopng takes this info from packets so I believe you have configured ntopng on a network interface that is not the correct one. You can use tools like tcpdump to verify what ntopng observes (note that from inside ntopng you can also capture traffic under the Interface page for instance) and thus select the correct interface

**Comment by Spectre5** [comment]
Right, I can see the packets from a tcpdump too (on the LAN interface).  So ntopng shows what was requested there.  On the WAN I don't see a connection to 8.8.8.8, which makes sense since those requests get redirected.  I was wondering if there was a way to show those redirects in ntopng, but perhaps the answer then is no since it probably "sees" the data before the redirect happens.
