### ISSUE TITLE
Invalid license installation check

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6078]
On an Ubuntu 18.04 I have this ntopng installed

Version:	5.1.211102 [Enterprise/Professional build]
GIT rev:	dev:c07a90e919aa4b47c6fcee31a5f1c34dbdb2efd7:20211102
Pro rev:	r4350
Built on:	Ubuntu 18.04.6 LTS
System Id:	L21F9FCE2B208AA8C--U21F9FCE2A6887E83--OL
Platform:	x86_64
Edition:	Enterprise L
License Type:	Permanent
Maintenance:	Until Sat May 28 11:09:52 2022 [197 days left]
License:	YU5eIpD7Qhp8aVC1i4cmeMLnk5+q13lqc9DoOWGN9c2tJOMoUtIuFejTwz1zpVvZdkEa7
        	DMy2o4h1fbhm5388JgZIS3L5IwjNoneyXLfooCmmj2yojWGx/cOXrqVmEX6XbMxlBKgO9
        	YwCA4g7MQ7aFZgldBJVinH4mf5hK3py4Y9f1pzc4QwHGJ1hNngk6qJGJfgCo3omdf3mqz
        	xTIfcKbYrCVb9VY9goW9kK5HvTjaEAs9DVjkH8OSQphrxHjbwbEXGr96RowlfB7IWnxkg
        	DZxBGtu6FiGRzTNnSBvgJa8udjp6cb/yrU918lqRwLCP/0y+WVnYBmNf9HFdEiwseQ==
License Hash:	FB06A3EA78746CD1BE65F055121EF14C1653728992EC1D3DB5

today I tried to update and got
![Screen Shot 2021-11-12 at 08 44 47](https://user-images.githubusercontent.com/4493366/141429452-1b7f843f-40dd-4743-9773-5d9ff0e556f5.png)

I have declined and obtained

WARNING: Maintenance expired. Upgrade declined by the user.

The result is an inconsistent setup

root@ntop2:/home/luca# dpkg -l|grep ntopng
ii  ntopng                                 5.1.211102-15824                                amd64        Web-based traffic monitoring.
iU  ntopng-data                            5.1.211112                                      all          Geolocation databases for ntopng and other ntop software packaged from https://db-ip.com

with a version mix.

**Comment by lucaderi** [comment]
Forcing the installation this is what was obtained
root@ntop2:/home/luca# ntopng --check-maintenance
1653728992 Sat May 28 11:09:52 2022

root@ntop2:/home/luca# ntopng --version
Version:	5.1.211112 [Enterprise/Professional build]
GIT rev:	dev:80d5c096467c217c32529d116e7773dc2e9dd926:20211112
Pro rev:	r4415
Built on:	Ubuntu 18.04.6 LTS
System Id:	L21F9FCE2B208AA8C--U21F9FCE2A6887E83--OL
Platform:	x86_64
Edition:	Enterprise L
License Type:	Permanent
Maintenance:	Until Sat May 28 11:09:52 2022 [197 days left]
License:	YU5eIpD7Qhp8aVC1i4cmeMLnk5+q13lqc9DoOWGN9c2tJOMoUtIuFejTwz1zpVvZdkEa7
        	DMy2o4h1fbhm5388JgZIS3L5IwjNoneyXLfooCmmj2yojWGx/cOXrqVmEX6XbMxlBKgO9
        	YwCA4g7MQ7aFZgldBJVinH4mf5hK3py4Y9f1pzc4QwHGJ1hNngk6qJGJfgCo3omdf3mqz
        	xTIfcKbYrCVb9VY9goW9kK5HvTjaEAs9DVjkH8OSQphrxHjbwbEXGr96RowlfB7IWnxkg
        	DZxBGtu6FiGRzTNnSBvgJa8udjp6cb/yrU918lqRwLCP/0y+WVnYBmNf9HFdEiwseQ==
License Hash:	FB06A3EA78746CD1BE65F055121EF14C1653728992EC1D3DB5

**Comment by cardigliano** [comment]
This was due to a bug in the previous ntopng version reporting a bad maintenance, which seems to be solved now.
