### ISSUE TITLE
no active flows with limited user/network

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#608]
I created a user in ntop with limited access and with visibility only for 192.168.115.0/24
in the dashboard page, I can see in top local talkers the right machines (inside 192.168.115 network)... but when I click on the "Flows" menu, it tells me : No Results Found

if I'm connected in admin, no problem to see all streams from this network

I missed something ?

Thanks

Nico

**Comment by Niko78** [comment]
... or "flows" display only stream where both src and dst are THIS network ?
I think "flows" should show me all streams where 192.168.115.0/24 appears (src or dst)

**Comment by simonemainardi** [comment]
Limiting user UI visibility to one or more networks will show that user only flows and hosts belonging to the specified networks. As -- an administrator -- you explicitly specify the list of networks in the configuration, you expect that no other networks except than those specified is shown to the user.

**Comment by Niko78** [comment]
hmm I'm sure I understand
if I restrict user to see 192.168.115.0/24, can this user see flows with this subnet when they go to internet by exemple ? ie 192.168.115.1 <=> 8.8.8.8 ?
it should be because I don't see restriction utility if I have to open 0.0.0.0/0 for that
thanks
nico
