### ISSUE TITLE
License type

### ISSUE THREAD

**Issue by Scheppers-wetteren** [ntop/ntopng#6081]
Hello,

Our school is looking into using ntopng. We are not sure which license to get. Can someone help use choose? This is our current scenario:

- Our school has about 2000 users.
- We have a internet fiber connection (1Gbit up/down) running through a pfsense router.
- We currently tested the community edition of ntopng in our network. It is running on a ubuntu server (virtual machine)
- We would like to monitor web/network traffic and if possible keep a history of the clients for 30 days.
- If possible, we would also like to monitor any bad behavior in our network.

**Comment by simonemainardi** [comment]
- Check https://www.ntop.org/products/traffic-analysis/ntop/ for the differences between versions
- as a school, you may qualify for EDU licenses. See https://www.ntop.org/support/faq/do-you-charge-universities-no-profit-and-research/
