### ISSUE TITLE
No GeoMap under hosts

### ISSUE THREAD

**Issue by MDanihy** [ntop/ntopng#6084]
Running licensed Pro version on Raspberry Pi, we do not even see the button to view the GeoMap.  

Nov 17 10:20:28 ntop ntopng[709]: 17/Nov/2021 10:20:28 [Geolocation.cpp:116] Running without geolocation support.
Nov 17 10:20:28 ntop ntopng[709]: 17/Nov/2021 10:20:28 [Geolocation.cpp:117] To enable geolocation follow the instructions at
Nov 17 10:20:28 ntop ntopng[709]: 17/Nov/2021 10:20:28 [Geolocation.cpp:118] https://github.com/ntop/ntopng/blob/dev/doc/README.geolocation.md
Nov 17 10:44:55 ntop ntopng[708]: 17/Nov/2021 10:44:55 [Geolocation.cpp:149] Loaded database dbip-asn-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip-asn-lite.mmdb][ip_version: 6]

Followed all instructions, was able to install the databases in the correct location.  Restarted the device but we do not see the option to view a geomap.

Any assistance would be appreciated.

**Comment by simonemainardi** [comment]
Kindly try, place the files at the following paths and restart:

/usr/share/ntopng/httpdocs/geoip//dbip-city-lite.mmdb
/usr/share/ntopng/httpdocs/geoip//dbip-asn-lite.mmdb

**Comment by MDanihy** [comment]
That did the trick, the city file was missing.  I do have geoipipdate working, shouldn't it be using those database files instead of the dbip databases?  Ran GeoIPUpdate and it downloaded the correct database.  Using dbip I assume I have to manually download them every time I need an update.

**Comment by simonemainardi** [comment]
To use MaxMind, make sure files are named as https://github.com/ntop/ntopng/blob/dev/src/Geolocation.cpp#L60 and located under https://github.com/ntop/ntopng/blob/dev/src/Geolocation.cpp#L38


>  Using dbip I assume I have to manually download them every time I need an update.

Correct, unless installed via ntopng-data for supported platforms
