### ISSUE TITLE
Observation Point Timeseries

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6085]
In the current implementation, there are no time-series for observation points nor statistics (e.g. how much traffic and nDPI traffic stats).
This is to request the implementation of
- real-time traffic volume and nDPI stats per observation point to be reported in the GUI
- above time-series for historical analysis

**Comment by simonemainardi** [comment]
To implement this:
1. Create classes ObervationPointHash inheriting from GenericHash and ObservationPoint inheriting from GenericHashEntry.
2. Add nDPI stats to each of the observation points
3. Periodically update throughputs
4. Expose methods to Lua to dump timeseries.

Make sure to only instantiate the hash table when oservation points are used.

**Comment by lucaderi** [comment]
Verified as fixed
