### ISSUE TITLE
Missing reload feedback in Historical Flow Explorer

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6087]
![Screen Shot 2021-11-18 at 18 08 49](https://user-images.githubusercontent.com/4493366/142463046-68a0de70-d666-4c43-ba93-aa1bd3133f66.png)

The load feedback icon is present only in the first page, and whenever queries are made there is no load icon whatsoever.

This ticket is to request to show the icon while the page is being rendered this to tell people that the result in the page top is not in sync with the table content.

**Comment by MatteoBiscosi** [comment]
Should be fixed, pro repo

**Comment by lucaderi** [comment]
Verified as fixed
