### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#609]
in going on graph interface, I get an error
see screenshot

<img width="935" alt="ntop error" src="https://cloud.githubusercontent.com/assets/17108017/15959435/1b6073ae-2efb-11e6-91ad-21639759f348.PNG">

Nico

**Comment by simonemainardi** [comment]
Even though I can't reproduce, I added extra checks to prevent the error. Please post full ntopng configuration used.

**Comment by simonemainardi** [comment]
why did you edit the original version?

![image](https://cloud.githubusercontent.com/assets/3397663/15962498/d39f8742-2f0b-11e6-8e05-fd59938a1505.png)

**Comment by Niko78** [comment]
cause it's not limited to user with limited rights, I checked that after sorry

ntop config
ntopng -F "mysql;localhost;ntopng;flows;root;azer" -m "161.48.0.0/19,100.64.0.0/16,100.65.0.0/16,100.66.0.0/16,100.77.0.0/16,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16" -i tcp://172.31.1.245:5556 --online-license-check -d /storage/tmp -w 3000

**Comment by simonemainardi** [comment]
can't reproduce, try to patch the code with the commit      5d8fbae

**Comment by Niko78** [comment]
Ok just confirmed it's ok now
thanks
