### ISSUE TITLE
No data on disaggregated interface.

### ISSUE THREAD

**Issue by thomasbruchet** [ntop/ntopng#6094]
Hello,

This issue is following the #6067 

The update has resolved the problem but also create a new one.
I've some disaggregated interfaces that show 0 usage now.
For exemple this is an important VLAN with all the admin teams and the disaggregation is done on the Internet Interface. I should have data.
![image](https://user-images.githubusercontent.com/86605223/143246040-ce9748ef-67fa-417f-9063-86b85c199653.png)

Here is the log system after the service had restarted
`24/Nov/2021 14:15:27 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:15:27 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 9.8868042889663e+18
24/Nov/2021 14:15:27 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:15:27 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.3755446657596e+19
24/Nov/2021 14:15:27 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:15:27 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.673486327207e+19
24/Nov/2021 14:15:27 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:15:27 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.100578618357e+19
24/Nov/2021 14:15:27 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:15:27 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.184667268452e+19
24/Nov/2021 14:11:19 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:11:19 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 9.8868042859568e+18
24/Nov/2021 14:11:19 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:11:19 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.375544665736e+19
24/Nov/2021 14:11:19 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:11:19 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.6734863268787e+19
24/Nov/2021 14:11:19 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:11:19 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.1005786183334e+19
24/Nov/2021 14:11:19 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:11:19 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.184667268138e+19
24/Nov/2021 14:06:15 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:06:15 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 9.8868042837464e+18
24/Nov/2021 14:06:15 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:06:15 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.3755446656741e+19
24/Nov/2021 14:06:15 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:06:15 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.6734863266297e+19
24/Nov/2021 14:06:15 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:06:15 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.1005786182714e+19
24/Nov/2021 14:06:12 [timeseries.lua:18] [rrd.lua:291] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:291: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1159: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
24/Nov/2021 14:06:12 [timeseries.lua:18] [rrd.lua:290] ERROR Number out of integers range: 1.1846672678705e+19
24/Nov/2021 14:01:58 [housekeeping.lua:38] [lists_utils.lua:717] Category Lists (22538 hosts, 78158 IPs, 0 JA3) loaded in 4 sec
24/Nov/2021 14:01:58 [NetworkInterface.cpp:437] ERROR Internal error: nested nDPI category reload`

**Comment by simonemainardi** [comment]
I have the suspect there's some old invalid data dangling around (due to the previous bug).

Now i've added extra logging so we will be able to spot it.

A new build is in progress. Please, wait a couple of hours, update, re-run, and report the new log.

**Comment by thomasbruchet** [comment]
Here is the log after update and restart this morning.
---
25/Nov/2021 09:10:29 [timeseries.lua:18] [rrd.lua:298] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:298: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1127: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
25/Nov/2021 09:10:29 [timeseries.lua:18] [rrd.lua:297] ERROR Number out of integers range: 9.8868044571873e+18 [host_pool:ndpi]
25/Nov/2021 09:10:29 [timeseries.lua:18] [rrd.lua:298] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:298: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1127: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
25/Nov/2021 09:10:29 [timeseries.lua:18] [rrd.lua:297] ERROR Number out of integers range: 1.3755446721023e+19 [host_pool:traffic]
25/Nov/2021 09:10:29 [timeseries.lua:18] [rrd.lua:298] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:298: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1127: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
25/Nov/2021 09:10:29 [timeseries.lua:18] [rrd.lua:297] ERROR Number out of integers range: 1.6734863511746e+19 [vlan:traffic]
25/Nov/2021 09:10:29 [timeseries.lua:18] [rrd.lua:298] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:298: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1127: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
25/Nov/2021 09:10:29 [timeseries.lua:18] [rrd.lua:297] ERROR Number out of integers range: 1.1005786246997e+19 [vlan:traffic]
25/Nov/2021 09:10:29 [timeseries.lua:18] [rrd.lua:298] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:298: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1127: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
25/Nov/2021 09:10:29 [timeseries.lua:18] [rrd.lua:297] ERROR Number out of integers range: 1.1846672881354e+19 [mac:ndpi_categories]
25/Nov/2021 09:05:48 [timeseries.lua:18] [rrd.lua:298] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:298: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1127: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
25/Nov/2021 09:05:48 [timeseries.lua:18] [rrd.lua:297] ERROR Number out of integers range: 9.886804456246e+18 [host_pool:ndpi]
25/Nov/2021 09:05:48 [timeseries.lua:18] [rrd.lua:298] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:298: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1127: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
25/Nov/2021 09:05:48 [timeseries.lua:18] [rrd.lua:297] ERROR Number out of integers range: 1.3755446720843e+19 [host_pool:traffic]
25/Nov/2021 09:05:48 [timeseries.lua:18] [rrd.lua:298] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:298: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1127: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
25/Nov/2021 09:05:48 [timeseries.lua:18] [rrd.lua:297] ERROR Number out of integers range: 1.673486351043e+19 [vlan:traffic]
25/Nov/2021 09:05:48 [timeseries.lua:18] [rrd.lua:298] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:298: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1127: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
25/Nov/2021 09:05:48 [timeseries.lua:18] [rrd.lua:297] ERROR Number out of integers range: 1.1005786246817e+19 [vlan:traffic]
25/Nov/2021 09:05:46 [timeseries.lua:18] [rrd.lua:298] ERROR stack traceback: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:298: in upvalue 'number_to_rrd_string' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:326: in upvalue 'update_rrd' ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:1127: in function 'rrd.export' /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:271: in function 'callback_utils.uploadTSdata' /usr/share/ntopng/scripts/callbacks/system/timeseries.lua:18: in main chunk
25/Nov/2021 09:05:46 [timeseries.lua:18] [rrd.lua:297] ERROR Number out of integers range: 1.1846672880387e+19 [mac:ndpi_categories]
25/Nov/2021 09:03:21 [Ntop.cpp:1681] WARNING Radius Authentication rejected for user "admin"
25/Nov/2021 09:03:14 [housekeeping.lua:38] [lists_utils.lua:717] Category Lists (22424 hosts, 77568 IPs, 0 JA3) loaded in 5 sec
25/Nov/2021 09:03:14 [NetworkInterface.cpp:437] ERROR Internal error: nested nDPI category reload
25/Nov/2021 09:03:14 [NetworkInterface.cpp:437] ERROR Internal error: nested nDPI category reload
25/Nov/2021 09:03:14 [NetworkInterface.cpp:437] ERROR Internal error: nested nDPI category reload
25/Nov/2021 09:03:13 [Ntop.cpp:1681] WARNING Radius Authentication rejected for user "admin"
25/Nov/2021 09:03:10 [NetworkInterface.cpp:3049] Started host user script hooks loop on interface OPEN_TOURS_INFRA_DMZ-139 [id: 43]...
25/Nov/2021 09:03:10 [NetworkInterface.cpp:3200] Started packet polling on interface OPEN_TOURS_INFRA_DMZ-139 [id: 43]...
25/Nov/2021 09:03:10 [NetworkInterface.cpp:3018] Started flow user script hooks loop on interface OPEN_TOURS_INFRA_DMZ-139 [id: 43]...
25/Nov/2021 09:03:10 [housekeeping.lua:38] [lists_utils.lua:643] WARNING List 'SSLBL JA3' has 0 rules. Please report this to https://github.com/ntop/ntopng
25/Nov/2021 09:03:10 [Ntop.cpp:2574] Registered interface OPEN_TOURS_INFRA_DMZ-139 [id: 43]
25/Nov/2021 09:03:10 [NetworkInterface.cpp:3049] Started host user script hooks loop on interface reseau_admin [id: 50]...

**Comment by simonemainardi** [comment]
I am unable to reproduce this behavior in my lab. Can we organize a remote support session?

**Comment by thomasbruchet** [comment]
Hello.

Yes, we can arrange that. I don't have an appointment scheduled, when are you available this week ?

**Comment by simonemainardi** [comment]
Sure. Drop me an email to mainardi at ntop dot org so we can arrange a session

**Comment by thomasbruchet** [comment]
Mail sent.

**Comment by simonemainardi** [comment]
After a joint support session we have determined that sub-interfaces were defined on the basis of VLAN-tags. However, receiving interface was not getting traffic with VLAN tags.
