### ISSUE TITLE
Ntopng and probe clock out of sync with custom traffic disaggregation

### ISSUE THREAD

**Issue by Gpf86** [ntop/ntopng#6096]
Hi, we're using Ntopng with Nprobe as collector on the same virtual machine, receving data in Netflow format from a FortiGate 200E.
Since adding 38 filters in extended nBPF format in custom traffic disaggregation, we have an alert saying that Ntopng and probe clock are out of sync and the consequence is Ntopng does not receive data.
How can we solve this problem? Is there another way to filter the traffic in order to aggregate it by sub-net IP classes?
Thanks in advance

![error-ntopng](https://user-images.githubusercontent.com/94901737/143416344-30b66e86-1bca-4a28-a572-3dc0f2072493.png)

**Comment by simonemainardi** [comment]
I tried to reproduce using NetFlow and disaggregation but without success. I am unable to get any clock drift error.

To ease the troubleshoot I've added indication of both local and remote probe timestamps. This will help us understanding what is happening.

![image](https://user-images.githubusercontent.com/3397663/147460322-88539c7f-6d46-4563-a39c-57ff1873fed5.png)

Please, wait 24h for a new build to be generated, then update and report the new error. Specifically, see how the local and remote probe times look like.

**Comment by lucaderi** [comment]
No further activity, closing ticket
