### ISSUE TITLE
Wrong time/timezone in forwarded syslog messages

### ISSUE THREAD

**Issue by solarexpedition** [ntop/ntopng#6097]
When sending syslog messages to a remote syslog server, ntopng sets not the correct time in the syslog message. “Z” means UTC+0. Like this, events will be interpreted in the future or in the past on the remote syslog server, depending in which time zone the ntopng server is configured. We can see this behavior on our Checkmk-Monitoring in the Event-Console. Every event is one hour in the future.

Instead of "Z", ntopng should set here the difference from local timezone to UTC.

Syslog message: LOGALERT.ERR: 1 2021-11-26T10:59:19**Z** 172.23.64.20 ntopng 3533050 - - [26/11/2021 10:59:17]  [enp8s0f0] [Error]

Ntop-Version:        5.1.211125 [Enterprise/Professional build]

**Comment by simonemainardi** [comment]
Thanks for reporting. Timestamps have now been adjusted to the current timezone. Format is ISO 8601 so you'll get them in UTC to make sure the time reference is standard and constant.

Example (before):

```
[21/12/2021 16:41:57]  [eno1] [Notice] [Remote Access][Flow][192.168.2.46:61215   devel:22]  Remote access ended [duration: < 1 sec]
```

After
```
[2021-12-21T15:41:57Z]  [eno1] [Notice] [Remote Access][Flow][192.168.2.46:61215   devel:22]  Remote access ended [duration: < 1 sec]
```

As I am CET, i.e., UTC+1, timestamp was wrongly reported with localtime and now is correctly reported in UTC using ISO 8601.
