### ISSUE TITLE
Periodic SNMP Errors in 5 mins Script

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6098]
29/Nov/2021 11:20:06 [LuaEngine.cpp:598] WARNING: Script failure [/Users/deri/network/ntopng/scripts/callbacks/system/5min.lua][...eri/network/ntopng/pro/scripts/lua/modules/snmp_poll.lua:206: attempt to index a nil value (field '?')]
29/Nov/2021 11:20:07 [LuaEngine.cpp:598] WARNING: Script failure [/Users/deri/network/ntopng/pro/scripts/callbacks/system/snmp.lua][...eri/network/ntopng/pro/scripts/lua/modules/snmp_poll.lua:206: attempt to index a nil value (field '?')]

**Comment by simonemainardi** [comment]
Solved in the latest release. Was due to a wrong counter on platforms without net-snmp available.
