### ISSUE TITLE
Alerts internal server error in lua - ntop_utils.lua

### ISSUE THREAD

**Issue by IPP-AS-CR** [ntop/ntopng#6099]
Hello,

I am getting Internal server error after collecting data fron second flow exporter when i try to view or when i redirected to alerts web page.

In log i have just: 29/Nov/2021 16:06:10 [LuaEngine.cpp:1253] WARNING Script failure [/usr/share/ntopng/scripts/lua/alert_stats.lua][/usr/share/ntopng/scripts/lua/modules/ntop_utils.lua:272: attempt to compare two nil values]

it runs on KVM (libvirt) 4CPU vhost, 4GB RAM for now 
- ntopng Enterprise L v.5.1.211118 (Debian GNU/Linux 11 (bullseye))

ntop listens on one interface nad 2 VLANs, and zmq:127.0.0.1 for nprobe + nprobe collecting from 2 mikrotiks (IPFLOW)

when i start sending flows from second exporter (mikrotik), then alerts page starts trowing errors

Thank you

Dalibor J

**Comment by simonemainardi** [comment]
Can you please explain what is the exact action (or exact page visited) that triggers this behavior. Feel free to attach screenshots.

**Comment by IPP-AS-CR** [comment]
When i wrote this it was triggered by:
configuration : one nprobe process colecting from 2 mikrotiks and sendig to ntopng throught zmq: 127.0.0.1:1234
- after login - selected interface tcp://127.0.0.1:1234 ( or any time ) and click on Alerts in left vertical menu (http://netwatcher.pals.ufp:3000/lua/alert_stats.lua)
- in flows slected interface tcp://127.0.0.1:1234 clck on flows alerts  (http://netwatcher.pals.ufp:3000/lua/flows_stats.lua?alert_type_severity=error_or_higher)
- in flows slected interface tcp://127.0.0.1:1234 click on alerts (http://netwatcher.pals.ufp:3000/lua/alert_stats.lua?ifid=26&status=engaged)
- after selecting System in interfaces and click on alerts - 
![image](https://user-images.githubusercontent.com/95037928/144815625-00ff595d-85c8-40b0-91bc-ecca6944468e.png)

- it started after i start sending to one nprobe process more exporters than 1. so i suppose, that is something with parsing data from nprobe with different exporters.

now i just get error in System - alerts. i reconfigured ntop a nprobes for better data managing and it is better suited for out needs - to using observation points and nprobe proces per exporter, swtched from rrd to influxDB and added clickhouse for historical flows explorer
for now i collecting to ntopng on 127.0.0.1 in collector mode from 4 nprobes - 2 mikrotics and 2 cisco switches. and i found only one  internal server error in script, as i mentioned above - with selected interface system and click to alerts (or anything related to that script - alert_stats.lua)

**Comment by simonemainardi** [comment]
this has likely been solved in bbd54707. Please, update to the latest ntopng and report.

**Comment by IPP-AS-CR** [comment]
My debian don't see any update and i have now> ntopng Enterprise L v.5.1.211118 (Debian GNU/Linux 11 (bullseye)) 
with apt pointing at: 

deb https://packages.ntop.org/apt-stable/bullseye/ x64/
deb https://packages.ntop.org/apt-stable/bullseye/ all/

so i did patch by hand in ntop_utils.lua by provided info in bbd5470, but propably there must be some other changes in regular update. minimaly in alert_stats.lua

after my "patch" i got: 

![image](https://user-images.githubusercontent.com/95037928/145355362-eee1cb24-3a51-4f36-acbb-945c9cf60f29.png)

**Comment by simonemainardi** [comment]
You are using the stable build. I've cherry-picked the commit to stable. New builds are in progress. Please, wait a couple of hours and upgrade.

**Comment by simonemainardi** [comment]
Issue fixed both on stable and dev. Reopen if necessary.
