### ISSUE TITLE
ntopng pro: "Error 'fetching cdp from rra' while calling rrd_fetch_r"

### ISSUE THREAD

**Issue by HRomie** [ntop/ntopng#610]
I have tested the pre-compiled version of ntopng pro for windows x64 (v.2.3.160530) . ntopng's log, report this error every once in a while when visiting the dashboard:

> 10/Jun/2016 16:50:16 [Lua.cpp:2204] ERROR: Error 'fetching cdp from rra' while calling rrd_fetch_r(C:\Users\TheUser\Documents\0\rrd\bytes.rrd, AVERAGE): is the RRD corrupted perhaps?

I could not reproduce this running in community mode.

**Comment by simonemainardi** [comment]
this has already been discussed in https://github.com/ntop/nProbe/issues/51#issuecomment-208186143
please follow the instructions there

**Comment by simonemainardi** [comment]
@HRomie any updates?

**Comment by HRomie** [comment]
@simonemainardi
Oh, sorry. i thought since you immediately acknowledged the error and directed me to another thread, you were already familiar with the bug and knew how to solve it.

I did what you suggested. I disabled the "RRDs For Local Hosts" in the web interface, stopped ntopng, and removed all the ntopng report folders in 'My Documents' (just to be sure) and started ntopng again. i also confirmed that "RRDs For Local Hosts" is indeed still turned off. However, I'm still getting that error regardless.

Edit: there was by the way to folder named '1' . there was '0' and another one

**Comment by simonemainardi** [comment]
@HRomie can you try and install our latest windows package http://packages.ntop.org/Windows/
please report if errors are still appearing.

thank you

**Comment by HRomie** [comment]
@simonemainardi 
The latest build (ntopng-2.4.160627_1-x64.exe) , is completely broken to the point that it can not be reliably tested for this bug. testing on windows 10 x64, i constantly get these in the console:

> 04/Sep/2016 23:16:10 [ActivityStats.cpp:88] WARNING: Error writing dump C:\Users\TestUser\Documents\0\activities\16\09\04\00:51:BC:21:C7:22

If i had to guess, it would be that it's not doing a proper job of reformatting file names to windows acceptable ones ( windows does not allow ":" in the file name ).

**Comment by simonemainardi** [comment]
@HRomie thanks for reporting. We have fixed the issue with file names. You will be notified when a new windows build will be available. This will likely be during the next few days.
