### ISSUE TITLE
Invalid alert filtering

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6100]
From this screen
![image](https://user-images.githubusercontent.com/4493366/144028615-681f5559-7748-4dfe-a3e2-d78feb5cb182.png)

I click on the server host where there is the arrow and I get

![image](https://user-images.githubusercontent.com/4493366/144028502-acb0f964-95f9-40f8-98df-f79550eba66a.png)

**Comment by MatteoBiscosi** [comment]
Hi, the issue should be solved, at least in my case, please let me know if everything works fine now

**Comment by lucaderi** [comment]
Verified as fixed
