### ISSUE TITLE
Rework Historical Flow Information Layout 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6101]
This is to request a rework of historical flows similar to the alerts and ntopng flows. Namely, as flow fields are constantly increasing it is unfeasible to list all fields clicking on
![Screen Shot 2021-11-30 at 11 22 01](https://user-images.githubusercontent.com/4493366/144029586-68b508bb-d2ee-4f16-b93c-7ef1a52386ad.png)

This is to request you to add a new column named actions where a new button for opening a new page/panel containing all the flow fields similar to that happens with ntopng flows. This way we have enough space for all fields without cutting field names 9e.g hostnames) that make the tool not too helpful in case of troubleshooting

**Comment by cardigliano** [comment]
The historical flow table now contains by default a subset of the whole information available in the database (additional info can be added using the 'eye' menu). A Historical Flow Details page has been added to display all the available flow details.

**Comment by lucaderi** [comment]
Verified as fixed
