### ISSUE TITLE
Rework Alert Flow Information Layout 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6102]
Same as #6101 but for flow alerts

**Comment by cardigliano** [comment]
Initial implementation added with 6bbe815b576cec8f6b7e1f299d0de4c297905270 b242ec29757b5abb057753a5d00c4b8482080845 342064446dbbd1bdbe25c1cc95317a15ae33b4e6

**Comment by lucaderi** [comment]
Verified as fixed
