### ISSUE TITLE
Enhance Historical Flow Explorer Chart

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6103]
![Screen Shot 2021-11-30 at 11 25 53](https://user-images.githubusercontent.com/4493366/144030166-12184b04-595d-4abe-959f-bb2f1c8a8105.png)

The above chart lists the number of flows. It would be helpful to add another timeseries (as line) that displays the flow bytes (use log scale?).

**Comment by MatteoBiscosi** [comment]
Implemented in the latest ntopng version
