### ISSUE TITLE
Invalid active monitoring alert

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6104]
30/Nov/2021 11:22:06 [MySQLDB.cpp:1048] ERROR: MySQL error: [Code: 15. DB::Exception: Column interface_id specified more than once. (DUPLICATE_COLUMN) (version 21.11.3.6 (official build))][15][INSERT INTO active_monitoring_alerts (alert_id, interface_id, tstamp, tstamp_end, severity, score, interface_id, resolved_ip, resolved_name, measurement, measure_threshold, measure_value, json) VALUES (4119, 18446744073709551615, 1638267663, 1638267723, 4, 50, -1, '127.0.0.1', '127.0.0.1', '', 0, 0.000000, '{"unit":"active_monitoring_stats.msec","alert_generation":{"subdir":"system","script_key":"active_monitoring"},"threshold":0,"ip":"127.0.0.1","host":{"is_infrastructure":false,"host":"127.0.0.1","label":"127.0.0.1","measurement":"icmp"},"value":0,"operator":"gt"}'); ]

**Comment by simonemainardi** [comment]
Verified as fixed.
