### ISSUE TITLE
Category Lists - add support for json or cvs as file type

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6107]
Dear ntop - team
Only IP address based block list, e.g. feodotracker.abuse.ch, create false positives, as the destination port number is important if a malicious C2 server is contacted or not.
Abuse.ch provide cvs lists with port numbers, or with even more context, json formated files with all relevant information.
Would it be possible you add the destination port in the Checks?
Thanks!

**Comment by lucaderi** [comment]
Implemented by https://github.com/ntop/ntopng/commit/5e8769b1b5c55899c4ed03c7599f3cef7bb010e3
