### ISSUE TITLE
Missing traffic profiles historical data

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#6108]
For certain traffic profiles, historical data is missing although there's traffic

![image](https://user-images.githubusercontent.com/3397663/144408276-40aaba15-5b2e-4dbe-8c31-744e87891c13.png)

![image](https://user-images.githubusercontent.com/3397663/144408557-18ae74e6-c7c2-4897-9dc2-2e490c5d0714.png)

When clicking on the historical chart for Polen this is the result

![image](https://user-images.githubusercontent.com/3397663/144408749-8275201e-1a27-4c1a-9073-1a68164c83c9.png)

**Comment by simonemainardi** [comment]
Issue should be fixed now in the latest 5.1. Profiles were not reloaded upon ntopng restart.

**Comment by lucaderi** [comment]
Assuming it fixed
