### ISSUE TITLE
ntopng pro: extended interface report generation causes the footer gauge and bandwidth dynamic graph to stop working

### ISSUE THREAD

**Issue by HRomie** [ntop/ntopng#611]
Testing the provided pre-compiled win x64 binary (v.2.3.160530) . going to Home-> Report , the interfaces extended report, does not seem to be showing up by itself ( Only 'Network Interfaces' graph is available. even after running for more than hour), however, if i re-select the active interface ( by going to Interfaces->NIC_Name ), the full report suddenly shows up, but it causes the footer graphs (gauge as well as real-time bandwidth monitor), to stop working. the only way that i could make them work again was by resetting the Redis databse. restarting ntopng or removing its data files, did not do the trick.

**Comment by simonemainardi** [comment]
I have made fixes and tested on win10 x86_64. Fix will be available in the next Windows build.
