### ISSUE TITLE
Dumping Flows to Clickhouse stops after some hours

### ISSUE THREAD

**Issue by solarexpedition** [ntop/ntopng#6115]
We have two network interfaces which receive mirrored traffic directly into ntopng and one which receives sFlow-traffic with nprobe. 

Dumping the flows from nprobe (eno1) is working good, but from the two mirrored interfaces (enp8s0f0, enp8s0f1), it stops dumping flows after a short time. Only after a restart of ntopng it starts again to dump the flows from these two interfaces. In the picture below you can see the two waves, second wave is after I restarted ntopng.

![image](https://user-images.githubusercontent.com/92759235/144570843-aa496ac4-7a66-4dd7-afcc-bfab0ea76356.png)

![image](https://user-images.githubusercontent.com/92759235/144573778-07a91454-a4a0-44cf-859b-b4540448083b.png)

I can't find any hint in syslog or in clickhouse-server.err.log.

Mirrored interfaces are configured with pf_ring.
`pf_ringcfg --list-interfaces
Name: enp8s0f0             Driver: ixgbe      RSS:     1    [Running ZC]
Name: eno2                 Driver: tg3        RSS:     1
Name: eno1                 Driver: tg3        RSS:     1
Name: enp8s0f1             Driver: ixgbe      RSS:     1    [Running ZC]`

Ntopng-Version:        5.1.211201 [Enterprise/Professional build]

**Comment by simonemainardi** [comment]
Error handling was not properly supported. A new build is in progress. Now, in case of export errors, you will see them in the UI and logs.

**Comment by solarexpedition** [comment]
Submitted bug is not a statistics problem. But I can confirm, that these drops are now showed in the GUI.

![image](https://user-images.githubusercontent.com/92759235/145004519-248274d9-1534-4383-9b9a-22a1c64dd804.png)

I/O on disk doesn't seem to be problem. I/O is under 1MB/s, with some peaks up to 10MB/s.

It looks like the process of dumping to clickhouse is dying for these two mirrored interfaces, some minutes after a restart of ntopng. This happens only on the two mirrored interfaces. With nprobe as a sFlow-collector, I don't have any drops.

![image](https://user-images.githubusercontent.com/92759235/145008303-653eb995-69ba-4070-9d83-7a9a67eb11b0.png)

Last Log Trace
`07/Dec/2021 10:53:54 [ClickHouseFlowDB.cpp:273] WARNING Unable to execute 'cat /var/tmp/clickhouse-11-16-4264.1638869917.csv | /usr/bin/clickhouse-client --host "127.0.0.1" --user "ntopng" --password "*****" -d "ntopng" --format_csv_delimiter="|" --query="INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR,IPV6_SRC_ADDR,IP_SRC_PORT,IPV4_DST_ADDR,IPV6_DST_ADDR,IP_DST_PORT,L7_PROTO,L7_CATEGORY,FLOW_RISK,INFO,PROFILE,NTOPNG_INSTANCE_NAME,INTERFACE_ID,STATUS,SRC_COUNTRY_CODE,DST_COUNTRY_CODE,SRC_LABEL,DST_LABEL,SRC_MAC,DST_MAC,COMMUNITY_ID,SRC_ASN,DST_ASN,PROBE_IP,OBSERVATION_POINT_ID,SRC2DST_TCP_FLAGS,DST2SRC_TCP_FLAGS,SCORE,L7_PROTO_MASTER,CLIENT_NW_LATENCY_US,SERVER_NW_LATENCY_US,CLIENT_LOCATION,SERVER_LOCATION) FORMAT CSV"' [0/Success]
07/Dec/2021 10:53:54 [ClickHouseFlowDB.cpp:252] WARNING Child process exited with an error [return value: 27]
07/Dec/2021 10:53:54 [ClickHouseFlowDB.cpp:273] WARNING Unable to execute 'cat /var/tmp/clickhouse-11-17-3269.1638869974.csv | /usr/bin/clickhouse-client --host "127.0.0.1" --user "ntopng" --password "*****" -d "ntopng" --format_csv_delimiter="|" --query="INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR,IPV6_SRC_ADDR,IP_SRC_PORT,IPV4_DST_ADDR,IPV6_DST_ADDR,IP_DST_PORT,L7_PROTO,L7_CATEGORY,FLOW_RISK,INFO,PROFILE,NTOPNG_INSTANCE_NAME,INTERFACE_ID,STATUS,SRC_COUNTRY_CODE,DST_COUNTRY_CODE,SRC_LABEL,DST_LABEL,SRC_MAC,DST_MAC,COMMUNITY_ID,SRC_ASN,DST_ASN,PROBE_IP,OBSERVATION_POINT_ID,SRC2DST_TCP_FLAGS,DST2SRC_TCP_FLAGS,SCORE,L7_PROTO_MASTER,CLIENT_NW_LATENCY_US,SERVER_NW_LATENCY_US,CLIENT_LOCATION,SERVER_LOCATION) FORMAT CSV"' [0/Success]
07/Dec/2021 10:53:54 [ClickHouseFlowDB.cpp:252] WARNING Child process exited with an error [return value: 27]
07/Dec/2021 10:53:54 [ClickHouseFlowDB.cpp:273] WARNING Unable to execute 'cat /var/tmp/clickhouse-11-26-3578.1638870530.csv | /usr/bin/clickhouse-client --host "127.0.0.1" --user "ntopng" --password "*****" -d "ntopng" --format_csv_delimiter="|" --query="INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR,IPV6_SRC_ADDR,IP_SRC_PORT,IPV4_DST_ADDR,IPV6_DST_ADDR,IP_DST_PORT,L7_PROTO,L7_CATEGORY,FLOW_RISK,INFO,PROFILE,NTOPNG_INSTANCE_NAME,INTERFACE_ID,STATUS,SRC_COUNTRY_CODE,DST_COUNTRY_CODE,SRC_LABEL,DST_LABEL,SRC_MAC,DST_MAC,COMMUNITY_ID,SRC_ASN,DST_ASN,PROBE_IP,OBSERVATION_POINT_ID,SRC2DST_TCP_FLAGS,DST2SRC_TCP_FLAGS,SCORE,L7_PROTO_MASTER,CLIENT_NW_LATENCY_US,SERVER_NW_LATENCY_US,CLIENT_LOCATION,SERVER_LOCATION) FORMAT CSV"' [0/Success]
07/Dec/2021 10:53:54 [ClickHouseFlowDB.cpp:252] WARNING Child process exited with an error [return value: 27]
07/Dec/2021 10:53:54 [ClickHouseFlowDB.cpp:273] WARNING Unable to execute 'cat /var/tmp/clickhouse-11-14-3736.1638869783.csv | /usr/bin/clickhouse-client --host "127.0.0.1" --user "ntopng" --password "*****" -d "ntopng" --format_csv_delimiter="|" --query="INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR,IPV6_SRC_ADDR,IP_SRC_PORT,IPV4_DST_ADDR,IPV6_DST_ADDR,IP_DST_PORT,L7_PROTO,L7_CATEGORY,FLOW_RISK,INFO,PROFILE,NTOPNG_INSTANCE_NAME,INTERFACE_ID,STATUS,SRC_COUNTRY_CODE,DST_COUNTRY_CODE,SRC_LABEL,DST_LABEL,SRC_MAC,DST_MAC,COMMUNITY_ID,SRC_ASN,DST_ASN,PROBE_IP,OBSERVATION_POINT_ID,SRC2DST_TCP_FLAGS,DST2SRC_TCP_FLAGS,SCORE,L7_PROTO_MASTER,CLIENT_NW_LATENCY_US,SERVER_NW_LATENCY_US,CLIENT_LOCATION,SERVER_LOCATION) FORMAT CSV"' [0/Success]
07/Dec/2021 10:53:54 [ClickHouseFlowDB.cpp:252] WARNING Child process exited with an error [return value: 27]
07/Dec/2021 10:53:54 [ClickHouseFlowDB.cpp:273] WARNING Unable to execute 'cat /var/tmp/clickhouse-11-30-3227.1638870780.csv | /usr/bin/clickhouse-client --host "127.0.0.1" --user "ntopng" --password "*****" -d "ntopng" --format_csv_delimiter="|" --query="INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR,IPV6_SRC_ADDR,IP_SRC_PORT,IPV4_DST_ADDR,IPV6_DST_ADDR,IP_DST_PORT,L7_PROTO,L7_CATEGORY,FLOW_RISK,INFO,PROFILE,NTOPNG_INSTANCE_NAME,INTERFACE_ID,STATUS,SRC_COUNTRY_CODE,DST_COUNTRY_CODE,SRC_LABEL,DST_LABEL,SRC_MAC,DST_MAC,COMMUNITY_ID,SRC_ASN,DST_ASN,PROBE_IP,OBSERVATION_POINT_ID,SRC2DST_TCP_FLAGS,DST2SRC_TCP_FLAGS,SCORE,L7_PROTO_MASTER,CLIENT_NW_LATENCY_US,SERVER_NW_LATENCY_US,CLIENT_LOCATION,SERVER_LOCATION) FORMAT CSV"' [0/Success]
07/Dec/2021 10:53:54 [ClickHouseFlowDB.cpp:252] WARNING Child process exited with an error [return value: 27]
07/Dec/2021 10:53:54 [ClickHouseFlowDB.cpp:273] WARNING Unable to execute 'cat /var/tmp/clickhouse-11-29-3514.1638870715.csv | /usr/bin/clickhouse-client --host "127.0.0.1" --user "ntopng" --password "*****" -d "ntopng" --format_csv_delimiter="|" --query="INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR,IPV6_SRC_ADDR,IP_SRC_PORT,IPV4_DST_ADDR,IPV6_DST_ADDR,IP_DST_PORT,L7_PROTO,L7_CATEGORY,FLOW_RISK,INFO,PROFILE,NTOPNG_INSTANCE_NAME,INTERFACE_ID,STATUS,SRC_COUNTRY_CODE,DST_COUNTRY_CODE,SRC_LABEL,DST_LABEL,SRC_MAC,DST_MAC,COMMUNITY_ID,SRC_ASN,DST_ASN,PROBE_IP,OBSERVATION_POINT_ID,SRC2DST_TCP_FLAGS,DST2SRC_TCP_FLAGS,SCORE,L7_PROTO_MASTER,CLIENT_NW_LATENCY_US,SERVER_NW_LATENCY_US,CLIENT_LOCATION,SERVER_LOCATION) FORMAT CSV"' [0/Success]
07/Dec/2021 10:53:54 [ClickHouseFlowDB.cpp:252] WARNING Child process exited with an error [return value: 27]
07/Dec/2021 10:53:54 [ClickHouseFlowDB.cpp:273] WARNING Unable to execute 'cat /var/tmp/clickhouse-11-25-3480.1638870467.csv | /usr/bin/clickhouse-client --host "127.0.0.1" --user "ntopng" --password "*****" -d "ntopng" --format_csv_delimiter="|" --query="INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR,IPV6_SRC_ADDR,IP_SRC_PORT,IPV4_DST_ADDR,IPV6_DST_ADDR,IP_DST_PORT,L7_PROTO,L7_CATEGORY,FLOW_RISK,INFO,PROFILE,NTOPNG_INSTANCE_NAME,INTERFACE_ID,STATUS,SRC_COUNTRY_CODE,DST_COUNTRY_CODE,SRC_LABEL,DST_LABEL,SRC_MAC,DST_MAC,COMMUNITY_ID,SRC_ASN,DST_ASN,PROBE_IP,OBSERVATION_POINT_ID,SRC2DST_TCP_FLAGS,DST2SRC_TCP_FLAGS,SCORE,L7_PROTO_MASTER,CLIENT_NW_LATENCY_US,SERVER_NW_LATENCY_US,CLIENT_LOCATION,SERVER_LOCATION) FORMAT CSV"' [0/Success]
07/Dec/2021 10:53:54 [ClickHouseFlowDB.cpp:252] WARNING Child process exited with an error [return value: 27]
07/Dec/2021 10:53:53 [ClickHouseFlowDB.cpp:273] WARNING Unable to execute 'cat /var/tmp/clickhouse-11-24-3891.1638870407.csv | /usr/bin/clickhouse-client --host "127.0.0.1" --user "ntopng" --password "*****" -d "ntopng" --format_csv_delimiter="|" --query="INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR,IPV6_SRC_ADDR,IP_SRC_PORT,IPV4_DST_ADDR,IPV6_DST_ADDR,IP_DST_PORT,L7_PROTO,L7_CATEGORY,FLOW_RISK,INFO,PROFILE,NTOPNG_INSTANCE_NAME,INTERFACE_ID,STATUS,SRC_COUNTRY_CODE,DST_COUNTRY_CODE,SRC_LABEL,DST_LABEL,SRC_MAC,DST_MAC,COMMUNITY_ID,SRC_ASN,DST_ASN,PROBE_IP,OBSERVATION_POINT_ID,SRC2DST_TCP_FLAGS,DST2SRC_TCP_FLAGS,SCORE,L7_PROTO_MASTER,CLIENT_NW_LATENCY_US,SERVER_NW_LATENCY_US,CLIENT_LOCATION,SERVER_LOCATION) FORMAT CSV"' [0/Success]
07/Dec/2021 10:53:53 [ClickHouseFlowDB.cpp:252] WARNING Child process exited with an error [return value: 27]
07/Dec/2021 10:53:53 [ClickHouseFlowDB.cpp:273] WARNING Unable to execute 'cat /var/tmp/clickhouse-11-19-4187.1638870092.csv | /usr/bin/clickhouse-client --host "127.0.0.1" --user "ntopng" --password "*****" -d "ntopng" --format_csv_delimiter="|" --query="INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR,IPV6_SRC_ADDR,IP_SRC_PORT,IPV4_DST_ADDR,IPV6_DST_ADDR,IP_DST_PORT,L7_PROTO,L7_CATEGORY,FLOW_RISK,INFO,PROFILE,NTOPNG_INSTANCE_NAME,INTERFACE_ID,STATUS,SRC_COUNTRY_CODE,DST_COUNTRY_CODE,SRC_LABEL,DST_LABEL,SRC_MAC,DST_MAC,COMMUNITY_ID,SRC_ASN,DST_ASN,PROBE_IP,OBSERVATION_POINT_ID,SRC2DST_TCP_FLAGS,DST2SRC_TCP_FLAGS,SCORE,L7_PROTO_MASTER,CLIENT_NW_LATENCY_US,SERVER_NW_LATENCY_US,CLIENT_LOCATION,SERVER_LOCATION) FORMAT CSV"' [0/Success]
07/Dec/2021 10:53:53 [ClickHouseFlowDB.cpp:252] WARNING Child process exited with an error [return value: 27]
07/Dec/2021 10:53:53 [ClickHouseFlowDB.cpp:273] WARNING Unable to execute 'cat /var/tmp/clickhouse-11-21-3070.1638870217.csv | /usr/bin/clickhouse-client --host "127.0.0.1" --user "ntopng" --password "*****" -d "ntopng" --format_csv_delimiter="|" --query="INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR,IPV6_SRC_ADDR,IP_SRC_PORT,IPV4_DST_ADDR,IPV6_DST_ADDR,IP_DST_PORT,L7_PROTO,L7_CATEGORY,FLOW_RISK,INFO,PROFILE,NTOPNG_INSTANCE_NAME,INTERFACE_ID,STATUS,SRC_COUNTRY_CODE,DST_COUNTRY_CODE,SRC_LABEL,DST_LABEL,SRC_MAC,DST_MAC,COMMUNITY_ID,SRC_ASN,DST_ASN,PROBE_IP,OBSERVATION_POINT_ID,SRC2DST_TCP_FLAGS,DST2SRC_TCP_FLAGS,SCORE,L7_PROTO_MASTER,CLIENT_NW_LATENCY_US,SERVER_NW_LATENCY_US,CLIENT_LOCATION,SERVER_LOCATION) FORMAT CSV"' [0/Success]
07/Dec/2021 10:53:53 [ClickHouseFlowDB.cpp:252] WARNING Child process exited with an error [return value: 27]
07/Dec/2021 10:53:53 [ClickHouseFlowDB.cpp:273] WARNING Unable to execute 'cat /var/tmp/clickhouse-15-23-3760.1638870356.csv | /usr/bin/clickhouse-client --host "127.0.0.1" --user "ntopng" --password "*****" -d "ntopng" --format_csv_delimiter="|" --query="INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR,IPV6_SRC_ADDR,IP_SRC_PORT,IPV4_DST_ADDR,IPV6_DST_ADDR,IP_DST_PORT,L7_PROTO,L7_CATEGORY,FLOW_RISK,INFO,PROFILE,NTOPNG_INSTANCE_NAME,INTERFACE_ID,STATUS,SRC_COUNTRY_CODE,DST_COUNTRY_CODE,SRC_LABEL,DST_LABEL,SRC_MAC,DST_MAC,COMMUNITY_ID,SRC_ASN,DST_ASN,PROBE_IP,OBSERVATION_POINT_ID,SRC2DST_TCP_FLAGS,DST2SRC_TCP_FLAGS,SCORE,L7_PROTO_MASTER,CLIENT_NW_LATENCY_US,SERVER_NW_LATENCY_US,CLIENT_LOCATION,SERVER_LOCATION) FORMAT CSV"' [0/Success]
07/Dec/2021 10:53:53 [ClickHouseFlowDB.cpp:252] WARNING Child process exited with an error [return value: 27]
07/Dec/2021 10:53:53 [ClickHouseFlowDB.cpp:273] WARNING Unable to execute 'cat /var/tmp/clickhouse-15-22-2426.1638870289.csv | /usr/bin/clickhouse-client --host "127.0.0.1" --user "ntopng" --password "*****" -d "ntopng" --format_csv_delimiter="|" --query="INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR,IPV6_SRC_ADDR,IP_SRC_PORT,IPV4_DST_ADDR,IPV6_DST_ADDR,IP_DST_PORT,L7_PROTO,L7_CATEGORY,FLOW_RISK,INFO,PROFILE,NTOPNG_INSTANCE_NAME,INTERFACE_ID,STATUS,SRC_COUNTRY_CODE,DST_COUNTRY_CODE,SRC_LABEL,DST_LABEL,SRC_MAC,DST_MAC,COMMUNITY_ID,SRC_ASN,DST_ASN,PROBE_IP,OBSERVATION_POINT_ID,SRC2DST_TCP_FLAGS,DST2SRC_TCP_FLAGS,SCORE,L7_PROTO_MASTER,CLIENT_NW_LATENCY_US,SERVER_NW_LATENCY_US,CLIENT_LOCATION,SERVER_LOCATION) FORMAT CSV"' [0/Success]
07/Dec/2021 10:53:53 [ClickHouseFlowDB.cpp:252] WARNING Child process exited with an error [return value: 27]
07/Dec/2021 10:53:52 [ClickHouseFlowDB.cpp:273] WARNING Unable to execute 'cat /var/tmp/clickhouse-15-13-2213.1638869722.csv | /usr/bin/clickhouse-client --host "127.0.0.1" --user "ntopng" --password "*****" -d "ntopng" --format_csv_delimiter="|" --query="INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR,IPV6_SRC_ADDR,IP_SRC_PORT,IPV4_DST_ADDR,IPV6_DST_ADDR,IP_DST_PORT,L7_PROTO,L7_CATEGORY,FLOW_RISK,INFO,PROFILE,NTOPNG_INSTANCE_NAME,INTERFACE_ID,STATUS,SRC_COUNTRY_CODE,DST_COUNTRY_CODE,SRC_LABEL,DST_LABEL,SRC_MAC,DST_MAC,COMMUNITY_ID,SRC_ASN,DST_ASN,PROBE_IP,OBSERVATION_POINT_ID,SRC2DST_TCP_FLAGS,DST2SRC_TCP_FLAGS,SCORE,L7_PROTO_MASTER,CLIENT_NW_LATENCY_US,SERVER_NW_LATENCY_US,CLIENT_LOCATION,SERVER_LOCATION) FORMAT CSV"' [0/Success]
07/Dec/2021 10:53:52 [ClickHouseFlowDB.cpp:252] WARNING Child process exited with an error [return value: 27]
07/Dec/2021 10:53:52 [ClickHouseFlowDB.cpp:273] WARNING Unable to execute 'cat /var/tmp/clickhouse-15-1119.1638868672.csv | /usr/bin/clickhouse-client --host "127.0.0.1" --user "ntopng" --password "*****" -d "ntopng" --format_csv_delimiter="|" --query="INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR,IPV6_SRC_ADDR,IP_SRC_PORT,IPV4_DST_ADDR,IPV6_DST_ADDR,IP_DST_PORT,L7_PROTO,L7_CATEGORY,FLOW_RISK,INFO,PROFILE,NTOPNG_INSTANCE_NAME,INTERFACE_ID,STATUS,SRC_COUNTRY_CODE,DST_COUNTRY_CODE,SRC_LABEL,DST_LABEL,SRC_MAC,DST_MAC,COMMUNITY_ID,SRC_ASN,DST_ASN,PROBE_IP,OBSERVATION_POINT_ID,SRC2DST_TCP_FLAGS,DST2SRC_TCP_FLAGS,SCORE,L7_PROTO_MASTER,CLIENT_NW_LATENCY_US,SERVER_NW_LATENCY_US,CLIENT_LOCATION,SERVER_LOCATION) FORMAT CSV"' [0/Success]`

**Comment by simonemainardi** [comment]
Thanks for reporting.

It seems there is some issue with the insert. It could be an issue with the data (e.g., an unescaped char?) but need to verify.

Let's try the following.

1. Stop ntopng
2. Clean up possibly old data not exported (`sudo rm -rf /var/tmp/clickhouse-*`)
3. Start ntopng in the foreground (`sudo ntopng /etc/ntopng/ntopng.conf`)

Look for errors printed to the console. Do you see any SQL-related error (e.g., invalid query?). If you see them, please paste them here.

Alternatively, you can try and manually execute one of the commands. Cut and paste an error and execute it, e.g., 

```
cat /var/tmp/clickhouse-15-22-2426.1638870289.csv | /usr/bin/clickhouse-client --host "127.0.0.1" --user "ntopng" --password "*****" -d "ntopng" --format_csv_delimiter="|" --query="INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR,IPV6_SRC_ADDR,IP_SRC_PORT,IPV4_DST_ADDR,IPV6_DST_ADDR,IP_DST_PORT,L7_PROTO,L7_CATEGORY,FLOW_RISK,INFO,PROFILE,NTOPNG_INSTANCE_NAME,INTERFACE_ID,STATUS,SRC_COUNTRY_CODE,DST_COUNTRY_CODE,SRC_LABEL,DST_LABEL,SRC_MAC,DST_MAC,COMMUNITY_ID,SRC_ASN,DST_ASN,PROBE_IP,OBSERVATION_POINT_ID,SRC2DST_TCP_FLAGS,DST2SRC_TCP_FLAGS,SCORE,L7_PROTO_MASTER,CLIENT_NW_LATENCY_US,SERVER_NW_LATENCY_US,CLIENT_LOCATION,SERVER_LOCATION) FORMAT CSV"
```
In any case, if you see that there's a SQL error, then please send the csv file to me (e.g., `/var/tmp/clickhouse-15-22-2426.1638870289.csv`) using address mainardi at ntop dot org

**Comment by simonemainardi** [comment]
Looking at ClickHouse error codes, it can be that 27 is actually an invalid input file

![image](https://user-images.githubusercontent.com/3397663/145040816-b708aaf3-4640-4bcc-84ca-c827c55c4685.png)

In case, having the offending CSV delivered privately to mainardi at ntop dot org, will help in doing the fix.

**Comment by solarexpedition** [comment]
I have sent you a csv file. It looks like there is a wrong value in the MAC-address field, hostname instead of a MAC-address on line 215. Please tell me, if you need more csv files.

**Comment by solarexpedition** [comment]
First fix has not fixed the issue completely and needs more work.
I have again a lot of csv files and also sql files in /var/tmp, which could not be imported because of invalid csv files (clickhouse error 27) and sql files with a syntax error (Code: 62. DB::Exception: Cannot parse expression of type String here).

**Comment by simonemainardi** [comment]
The latest build will print extra information and detailed error information. Please, wait a couple of hours, update, and report.

**Comment by solarexpedition** [comment]
Here is the output of Last Errors from the Clickhouse Health Tab. I have installed the update yesterday morning.

Line one looks like a relevant line concerning a dump problem.
Line two has something to do with the veeam backup client. I don't why it wants to read this file.

`23/Dec/2021 00:02:03 Cannot parse input: expected ',' before: '-1, \'housekeeping.lua\', \'\', \'\', 60, \'{"max_duration_ms":65000,"ps_name":"housekeeping.lua","alert_generation":{"script_key":"slow_periodic_activity","subdir":"s' [169924698,170279693,336728946,336725635,335321557,335320474,335450019,335403038,335398505,335397752,335392292,323828883,332847962,332834192,384705455,384714753,385824137,385813632,140335083849225,140335082959507]
22/Dec/2021 16:06:52 Cannot read from file /sys/block/veeamimage2/stat, errno: 19, strerror: No such device [169924698,169929802,170248496,314741169,314700841,314738318,314757712,170190519,170205373,140335083849225,140335082959507]
22/Dec/2021 08:16:43 Cannot open certificate file: /etc/clickhouse-server/server.crt. [169924698,332818922,332815879,170569438,170414810,170481093,384795974,170418324,170410535,169901258,140335081930931,168411630]`

`24/Dec/2021 00:02:01 Cannot parse input: expected ',' before: '-1, \'housekeeping.lua\', \'\', \'\', 60, \'{"max_duration_ms":65000,"alert_generation":{"subdir":"system","script_key":"slow_periodic_activity"},"ps_name":"housekeepi' [169924698,170279693,336728946,336725635,335321557,335320474,335450019,335403038,335398505,335397752,335392292,323828883,332847962,332834192,384705455,384714753,385824137,385813632,140335083849225,140335082959507]
23/Dec/2021 11:12:48 Cannot convert string 172.20.8.129 to type UInt32 [169924698,205694334,323706121,323697653,252132091,252017175,207406766,308305662,308307240,315786661,315791170,318193538,321073574,321043210,321021530,321015572,321380994,321374864,320614486,323812237,323826716,332847962,332834192,384705455,384714753,385824137,385813632,140335083849225,140335082959507]
23/Dec/2021 11:12:48 Unexpected data '.20.8.129' after parsed Number value '172' [169924698,312635955,312635521,168840913,323701618,323697653,252132091,252017175,207406766,308305662,308307240,315786661,315791170,318193538,321073574,321043210,321021530,321015572,321380994,321374864,320614486,323812237,323826716,332847962,332834192,384705455,384714753,385824137,385813632,140335083849225,140335082959507]`

**Comment by simonemainardi** [comment]
Thanks for reporting. `Cannot parse input` issues should be fixed now. A new build will be available within 24 hours.

This `/sys/block/veeamimage2/stat` is not related to ntopng.

**Comment by solarexpedition** [comment]
Looks good now. I don't have any dump issues since several days. I think we can close this issue.

**Comment by lucaderi** [comment]
Verified as fixed

**Comment by solarexpedition** [comment]
I was to early with the confirmation, sorry. Today, I have again a lot clickhouse problems.

I will send the error-log directly by email, as there are to many private network informations and passwords in it.
