### ISSUE TITLE
No Exported Flows statistics when using Clickhouse

### ISSUE THREAD

**Issue by solarexpedition** [ntop/ntopng#6116]
When using Clickhouse for dumping flows, there are no statistics available on all interfaces pages in the Ntopng-Gui. Exported Flows and Dropped Flows stay at 0 forever.

![image](https://user-images.githubusercontent.com/92759235/144577535-e66026ff-eebf-4bd0-9223-e85d03d03fa5.png)

**Comment by simonemainardi** [comment]
Export stats are now added. A new build is in progress. It will be ready in ~2 hours.

**Comment by solarexpedition** [comment]
Which ntopng version should contain the change? Version: 5.1.211206 has the same behavior.

**Comment by solarexpedition** [comment]
Just installed version: 5.1.211207
Statistics are now available.
![image](https://user-images.githubusercontent.com/92759235/145003489-1a6d055f-ab9a-4611-a70c-94bbfffaa087.png)
