### ISSUE TITLE
Add Check for traffic matching a configured BPF (e.g. flow UDP/137)

### ISSUE THREAD

**Issue by TheMichMan** [ntop/ntopng#6117]
ntopng to report an alarm whenever you see a flow using UDP/137

**Comment by simonemainardi** [comment]
To implement this with maximum flexibility @lucaderi proposed to add one or more checks which interpret a BPF filter.

**Comment by AlekseiSaff** [comment]
amazing. stil l waiting for that feature. great to have both options include (if we see unwanted traffic) and exclude (if we don't see needed traffic for a period of time)

**Comment by lucaderi** [comment]
Just committed https://github.com/ntop/nDPI/commit/1d0bc7c3506ea08fd84bb0781098193924ad1308 that will enable the implementation of this ticket

**Comment by lucaderi** [comment]
Implemented as follows
- in nDPI proto.txt configure the new protocol
- In Hosts -> Local Hosts Traffic Rules define a rule that triggers an alert when traffic for such protocol Is detected
