### ISSUE TITLE
Alert List - number of filters limited or not working

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6118]
Hello ntop Team
Using several filters in the alert list, in this example the last server name filter I can not put to NOT (!=). 
Maybe there is a limit in the number of filters I can use?
Thanks, Martin
<img width="1404" alt="Screenshot 2021-12-07 at 15 56 04" src="https://user-images.githubusercontent.com/38549755/145052276-2f0ff356-84b9-4eb0-ae4e-44a949c24426.png">

**Comment by cardigliano** [comment]
@martinscheu I am trying to reproduce this, what do you mean exactly by "I can not put to NOT"? What is the effect?
Please click on the "SQL" badge in the footer to copy the generated SQL and provide it. Thank you.

<img width="305" alt="Screen Shot 2021-12-27 at 10 08 23" src="https://user-images.githubusercontent.com/7548711/147455583-4f1f7652-5162-413d-b068-9dc01a7c8e49.png">

**Comment by cardigliano** [comment]
It is likely this was related to the maximum length accepted by the name validator. This has been extended now.

**Comment by lucaderi** [comment]
Verified as fixed
