### ISSUE TITLE
ClickHouse Stats Not Working

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6120]
![Screen Shot 2021-12-07 at 20 22 02](https://user-images.githubusercontent.com/4493366/145092780-9ab17021-f06a-42f3-894f-9b9500adebd7.png)

For some reasons the stats are empty

**Comment by simonemainardi** [comment]
Issue was limited to view interfaces. Fixed in the referenced commit (and companion pro commit).

**Comment by lucaderi** [comment]
Verified as fied
