### ISSUE TITLE
Substring Host/Info Search

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6122]
Add the ability to search subtrings (e.g. hostname) using LIKE %...% statements and not just = and != as today

**Comment by cardigliano** [comment]
Implemented in 43bef2767e2c211283135f1d057536be5280e6a5 (and pro ea1586913dbf5ea22cc31b7fbe16781a378906a3)

**Comment by lucaderi** [comment]
Verified as fixed
