### ISSUE TITLE
Instructions on how to properly uninstall ntopng instance on pfsense NOT preformed via package manager

### ISSUE THREAD

**Issue by Spacey67** [ntop/ntopng#6123]
Wondering why there isn't any documentation on how to uninstall after preforming the installation outside of the traditional package manager route for pfsense? advise

**Comment by simonemainardi** [comment]
Documentation has been added. It will be deployed automatically at https://www.ntop.org/guides/ntopng/third_party_integrations/pfsense.html within the next few hours.
