### ISSUE TITLE
Unable to send alert via SMTP endpoint

### ISSUE THREAD

**Issue by farosch** [ntop/ntopng#6125]
Hi there,

I am running ntopng on pfSense v2.5.2.

```
Version:        5.1.211126 [Enterprise/Professional build]
GIT rev:        dev:a2d079a97c8b7d1742cfbfb6d2f58b2b09d37452:20211126
Pro rev:        r4491
Built on:       FreeBSD 12.2
System Id:      L017313389208AA99--U01731338CE3870EF--OB
Platform:       amd64
Edition:        Enterprise M
License Type:   Permanent
Maintenance:    Until Sat Nov 26 10:23:17 2022 [352 days left]
```

Unfortunately, I am unable to send mails via SNMP endpoint.
These are my endpoint settings:

![image](https://user-images.githubusercontent.com/22905106/145190145-f668b69e-983d-496b-aafa-599e48ce7882.png)

The check just fails with the message `Something went wrong. Try again later.`: 

![ApplicationFrameHost_NRXSer65tG](https://user-images.githubusercontent.com/22905106/145196926-d3691645-b656-4ad3-9e19-3e9a8eb389b3.png)

I can see the following lines in the logfile under `/var/db/log/ntopng/ntopng.log`

```
08/Dec/2021 14:47:10 [Utils.cpp:1803] WARNING Unable to send email to (smtp://10.32.0.160/XXX.de): Timeout was reached. Run ntopng with -v6 for more details.
```

There are no error messages when the service is started:

```
[2.5.2-RELEASE][admin@fw1]/root: service ntopng restart
Stopping ntopng.
Waiting for PIDS: 943.
Starting ntopng.
08/Dec/2021 10:10:52 [Ntop.cpp:3297] Added Local Network 10.0.0.0/8
08/Dec/2021 10:10:52 [Redis.cpp:162] Successfully connected to redis 127.0.0.1@0
08/Dec/2021 10:10:52 [Redis.cpp:162] Successfully connected to redis 127.0.0.1@0
08/Dec/2021 10:10:52 [NtopPro.cpp:330] [LICENSE] Reading license from /usr/local/etc/ntopng.license
08/Dec/2021 10:10:52 [NtopPro.cpp:501] [LICENSE] /usr/local/etc/ntopng.license: found valid Enterprise M license
08/Dec/2021 10:10:52 [Ntop.cpp:2407] Parent process is exiting (this is normal)
```

When I try to send a mail using telnet and the command line everything worked out fine, though:
![image](https://user-images.githubusercontent.com/22905106/145196399-79f718da-c60a-4a37-b3ff-c2f95474cbb5.png)

Has anyone an idea where this error could come from, or maybe knows some more things I need to check out?

**Comment by simonemainardi** [comment]
See. Errors say "Login denied.". Likely you have to specify a username/password pair in 

![image](https://user-images.githubusercontent.com/3397663/145555541-6723065b-bff8-4353-b722-de4a9ae080d1.png)

as your server only supports authenticated sessions.

**Comment by farosch** [comment]
I definitively do not need SMTP authentication:
![image](https://user-images.githubusercontent.com/22905106/145561546-c78833a5-69f3-4730-b8da-6ed9fea23853.png)

But even if I do provide correct login data, it still does not work.
Also, I do not understand why ntopng tries to authenticate with the server when neither username nor password are provided?

**Comment by simonemainardi** [comment]
Checked now with freebsd12, working smoothly

```
16/Dec/2021 15:27:46 [Ntop.cpp:469] Welcome to ntopng amd64 v.5.1.211216 - (C) 1998-21 ntop.org
16/Dec/2021 15:27:46 [Ntop.cpp:479] Built on FreeBSD 12.2
16/Dec/2021 15:27:46 [NtopPro.cpp:793] [LICENSE] System Id:	L12BD67B3000307F0--U12BD67B3C38354F1--OB
```

To this please.

1. Stop ntopng
2. Run ntopng in the foreground (execute /usr/local/bin/ntopng)
check for errors
