### ISSUE TITLE
Add the ability to read local networks from file

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6127]
Currently local network (-m) are read from the config file. However when the list is long it should be read from a file.

This is to request to extend -m with
-m=XXXXXX

where if XXXXXX is a filename then the list of local networks is read from there. They can be specified *both* in comma-separated value (as today) and in multiple lines

**Comment by simonemainardi** [comment]
Implemented. As requested, file supports multiple lines and commas (and combinations of both). Example file format (also documented in the source comments):

```
        192.168.2.0/24=office,192.168.2.1/32,8.8.8.8/32
        9.9.9.9/32
        10.0.0.0/8
```

**Comment by lucaderi** [comment]
Verified as fixed
