### ISSUE TITLE
Batch network import

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6128]
Currently, networks (and their name) are defined from the ntopng GUI that can be pretty tedious in particular if it has to be iterated over multiple hosts. This is to request to add the ability to import in batch mode network from a file. Its format will be
<name> <networks>

in multiple lines

**Comment by simonemainardi** [comment]
This should be implemented by https://github.com/ntop/ntopng/issues/6127.
Note that batch import of aliases is supported using `=`.

**Comment by lucaderi** [comment]
Verified as fixed
