### ISSUE TITLE
List Network Flows

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6130]
![Screen Shot 2021-12-09 at 14 17 50](https://user-images.githubusercontent.com/4493366/145403553-c2ca5ea7-a02f-48fc-ae06-269ff58db159.png)

In case there are some specified networks, this is to request the above menu to be populated also with the network names (note the list can be long) so that it is possible to list only flows that belong to the given network

**Comment by simonemainardi** [comment]
A dropdown has been added. Network are shown sorted by CIDR and aliase (when present).

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/3397663/146536816-107bab5b-7c31-4b61-97b5-9a36d08137b0.png">

**Comment by lucaderi** [comment]
![image](https://user-images.githubusercontent.com/4493366/146738560-8fab90b7-cd53-410c-9e53-d361ce4c847f.png)
Not working as it should

**Comment by simonemainardi** [comment]
Issue was occurring only on view interfaces and is now fixed.

**Comment by lucaderi** [comment]
Still bugged: you can try on HS

**Comment by simonemainardi** [comment]
Should be fixed now.

**Comment by lucaderi** [comment]
Verified as fixed
