### ISSUE TITLE
Invalid ASN Reported in Historical Reports

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6131]
In some cases (not always) in the historical flow explorer, the symbolic AS Name does not contain the correct value but rather the 
![image](https://user-images.githubusercontent.com/4493366/145411201-50291092-5427-47ae-a129-931efe4e078d.png)

**Comment by cardigliano** [comment]
I pushed a fix (pro 118cf4e8028187eefca3d9929d4651bc635f35ab) that probably fixes this

**Comment by lucaderi** [comment]
Verified as fixed
