### ISSUE TITLE
Add MySQL and nIndex Deprecate Warning

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6132]
As we're moving to ClickHouse, MySQL and nIndex have to be deprecated and
- a constant warning has to be added on the top of the screed (dev version only) asking to migrate now

Sometime in January MySQL and nIndex support will be removed and the above warning will show up in case they have been specified (and ignored) from the CLI

**Comment by cardigliano** [comment]
Added toasts in cc6014a2206eed2e804daaa757b12f5ac1264703 2b643ab7c4bf227a59a4c3b44ef70ebade2c4668

**Comment by lucaderi** [comment]
Verified as fixed
