### ISSUE TITLE
Rework SNMP host stats

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6134]
<img width="638" alt="Screenshot 2021-12-11 at 13 23 09" src="https://user-images.githubusercontent.com/4493366/145676404-7a82144b-ef31-46f5-8de2-f8e14040b9de.png">

In the above page it would be nice to have a gauge indicating the usage in % rather than only with absolute numbers

**Comment by MatteoBiscosi** [comment]
Implemented like the following. Added a progress bar even to CPU usage in order to let the user visualize better the state of the device. 
![Screenshot from 2022-01-17 17-13-49](https://user-images.githubusercontent.com/49585191/149804518-2776fc33-d724-4ad5-8b17-cb0a17b85a8e.png)

**Comment by lucaderi** [comment]
Verified as fixed
