### ISSUE TITLE
Broken System Alerts Report

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6136]
![Screen Shot 2021-12-14 at 08 13 14](https://user-images.githubusercontent.com/4493366/145950445-210957e5-533a-4f69-a168-a1e8622b960a.png)

**Comment by solarexpedition** [comment]
Maybe you can merge this issue with https://github.com/ntop/ntopng/issues/6124. At the moment the alert page is unusable.

**Comment by MatteoBiscosi** [comment]
Now the system alert is working correctly. Please update and let me know.
![Screenshot from 2021-12-15 15-43-11](https://user-images.githubusercontent.com/49585191/146207226-9f87dc12-9d0e-48b6-9359-18b01d94c3dd.png)

**Comment by ListenNjoy** [comment]
tested Ok, thanks

**Comment by solarexpedition** [comment]
It works again, thanks

**Comment by lucaderi** [comment]
Verified as fixed
