### ISSUE TITLE
apt update fails with "File has unexpected size (3264 != 2460)" - InRelease file wrong?

### ISSUE THREAD

**Issue by thr27** [ntop/ntopng#6137]
SInce today, we have an issue to run apt update on Ubuntu 20.04.3 LTS

Our ntop.list contains the following entries ...

deb https://packages.ntop.org/apt-stable/20.04/ x64/
deb https://packages.ntop.org/apt-stable/20.04/ all/

When I check the InRelease from https://packages.ntop.org/apt-stable/20.04/all/InRelease
It lists Packages.gz with a size of 2460 

MD5Sum:
 af6c76cf6e9f0be6e1dd3edd8eb1f565             5903 Packages
 54390825ce7a7d2d3b8ae802c14d211a             2460 Packages.gz

But Packages.gz  is in reality 3.264 Bytes big.

Can you please check the InRelease file?

https://packages.ntop.org/apt-stable/20.04/all/Release is correct, but Ubuntu uses InRelease file

**Comment by simonemainardi** [comment]
`Packages.gz` is now the same (` c7ba1a0a994da486bfd46f7eb9168ef2             3263 Packages.gz`) on both

- https://packages.ntop.org/apt-stable/20.04/all/InRelease
- https://packages.ntop.org/apt-stable/20.04/all/Release

Chances are you have performed the update exactly while we were deploying new builds.
