### ISSUE TITLE
Some Checks can not be disabled

### ISSUE THREAD

**Issue by aleex1848** [ntop/ntopng#6138]
Using ntopng Professional v.5.1.211214 the two checks "Malicious JA3 Signature" and "Potentially Dangerous Protocol" can not be disabled. The Enable/Disable Switch inside the action column doesn't react. The three buttons on the "exit check options modal" are also without any function. Besides this one button is labeled with {{action}} which doesn't seem to be intended.

![image](https://user-images.githubusercontent.com/17452861/145982794-94b9800e-36b3-4611-bd59-13cb9f96c5e0.png)

![image](https://user-images.githubusercontent.com/17452861/145982913-59eabd90-072b-4fb0-b68c-c20ca10ff293.png)

**Comment by MatteoBiscosi** [comment]
Hi Alex, I'm sorry but I'm unable to reproduce this behavior. Which distro are you running ntopng on? Do you have errors in `systemctl status ntopng` or `journalctl -u ntopng -e`? GUI side, if you right click, inspect, console tab, is there some error shown?
Sorry to bother you but I'm not able to reproduce this in 3 distro, so I cannot debug myself.

**Comment by aleex1848** [comment]
Hi @MatteoBiscosi 
thx for reply!

ntopng is running on Debian GNU/Linux 10

i see errors/warning in systemctl when pressing the buttons:
` [toggle_check.lua:52] [checks.lua:720] WARNING: Module 'tls_malicious_signature' is not associated to any known flow risk alert`
` 15/Dec/2021 10:51:24 [toggle_check.lua:52] [checks.lua:720] WARNING: Module 'tls_malicious_signature' is not associated to any known flow risk alert`
`[LuaEngine.cpp:1259] WARNING: Script failure [/usr/share/ntopng/scripts/lua/toggle_check.lua][/usr/share/ntopng/scripts/lua/modules/checks.lua:724: attempt to index a nil value (local 'flow_risk_alert')]`
`10:51:24 [LuaEngine.cpp:1259] WARNING: Script failure [/usr/share/ntopng/scripts/lua/toggle_check.lua][/usr/share/ntopng/scripts/lua/modules/checks.lua:724: attempt to index a nil value (local 'flow_risk_alert')]`

**Comment by aleex1848** [comment]
@MatteoBiscosi 

i forgot to mention: the errors started to occur after updating ntopng from v4 to v5!

**Comment by MatteoBiscosi** [comment]
Hi @aleex1848 I think that you got a problem while changing from ntopng v. 4 to ntopng v. 5.1. Is it possible to redo a clean installation, by removing ntop packages and repositories and re-adding them?  Please let me know.

**Comment by simonemainardi** [comment]
You can also perform a factory reset check:

![image](https://user-images.githubusercontent.com/3397663/146783141-84670f50-ac06-43b4-9375-44675b56ec14.png)

**Comment by aleex1848** [comment]
@simonemainardi 
unfortunately this doesn't help. same behavious.

@MatteoBiscosi 
I didn't do a reinstall until now but will try it during holidays.

**Comment by aleex1848** [comment]
@MatteoBiscosi 
did a clean reinstall and everything is working now. thx!
