### ISSUE TITLE
no_proxy is not effective

### ISSUE THREAD

**Issue by naosone** [ntop/ntopng#6140]
ntopng can not connect influxdb(http://localhost:8086) when environment http_proxy is set.
no_proxy=localhost is not effective, ntopng connect to influxdb via proxy server.

**Comment by simonemainardi** [comment]
Did you check the instructions at? https://github.com/ntop/ntopng/tree/dev/doc#using-ntopng-with-a-https-proxy

basically `HTTP_PROXY` env var must be set within systemd if you are starting ntopng as a service.

**Comment by naosone** [comment]
Our ntopng is running on private network.

We use HTTP_PROXY and HTTPS_PROXY.

[Service]
Environment="HTTP_PROXY=http://xxxx:8080/;HTTPS_PROXY=http://xxxx:8080/"

We can connect the internet.

However, our system  running ntopng and influxdb on same server.
Therefore, we are using http://localhost:8086 as the URL for connect to influxdb.
but when HTTP_PROXY is set, communication to influxdb is also sento to the proxy.

I tried to set NO_PROXY, but no effect.

**Comment by simonemainardi** [comment]
Thanks for reporting. Proxy exclusions are now enforced.

For example, to exclude `localhost` as in your case, you can do

```
HTTP_PROXY=http://proxy.naruto-u.ac.jp:8080/ no_proxy=localhost  ntopng -i eno1  --disable-login 1 
```
