### ISSUE TITLE
Unknown system event

### ISSUE THREAD

**Issue by MatteoBiscosi** [ntop/ntopng#6141]
As you can see from the screenshot an unknown event is present, if possible show at least a brief description.
![Screenshot from 2021-12-15 15-46-00](https://user-images.githubusercontent.com/49585191/146207914-a3b927fc-e148-4d2a-88e8-2ed05d593e5c.png)

**Comment by MatteoBiscosi** [comment]
The issue is fixed but this fix is working only for the new alert of Process type. Unfortunately it's not possible to save the old ones due to a corruption of the json message.
![Screenshot from 2021-12-15 16-21-07](https://user-images.githubusercontent.com/49585191/146213864-c2b51037-720d-45f2-b155-7d5c5e29bcbf.png)

**Comment by MatteoBiscosi** [comment]
Verified as Fixed

**Comment by lucaderi** [comment]
Verified as fixed
