### ISSUE TITLE
Improve ClickHouse Error reporting

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6142]
![Screen Shot 2021-12-16 at 11 54 32](https://user-images.githubusercontent.com/4493366/146358812-bcd6446e-579c-46d7-9172-df80547ea535.png)

The above problem was caused by an update to clickhouse-server (not restarted by the clickhouse package) that required a restart. This ticket is to request to report the exact error you see executing the command from CLI

$ cat /var/tmp/clickhouse-2-162-50001.1639651734.csv | /usr/bin/clickhouse-client --host "127.0.0.1" --user "default" --password "" -d "ntopng" --format_csv_delimiter="|" --format_csv_allow_double_quotes true --query="INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR,IPV6_SRC_ADDR,IP_SRC_PORT,IPV4_DST_ADDR,IPV6_DST_ADDR,IP_DST_PORT,L7_PROTO,L7_CATEGORY,FLOW_RISK,INFO,PROFILE,NTOPNG_INSTANCE_NAME,INTERFACE_ID,STATUS,SRC_COUNTRY_CODE,DST_COUNTRY_CODE,SRC_LABEL,DST_LABEL,SRC_MAC,DST_MAC,COMMUNITY_ID,SRC_ASN,DST_ASN,PROBE_IP,OBSERVATION_POINT_ID,SRC2DST_TCP_FLAGS,DST2SRC_TCP_FLAGS,SCORE,L7_PROTO_MASTER,CLIENT_NW_LATENCY_US,SERVER_NW_LATENCY_US,CLIENT_LOCATION,SERVER_LOCATION,SRC_NETWORK_ID,DST_NETWORK_ID) FORMAT CSV"
cat: /var/tmp/clickhouse-2-162-50001.1639651734.csv: Permission denied
Code: 108. DB::Exception: No data to insert: (in query: INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR,IPV6_SRC_ADDR,IP_SRC_PORT,IPV4_DST_ADDR,IPV6_DST_ADDR,IP_DST_PORT,L7_PROTO,L7_CATEGORY,FLOW_RISK,INFO,PROFILE,NTOPNG_INSTANCE_NAME,INTERFACE_ID,STATUS,SRC_COUNTRY_CODE,DST_COUNTRY_CODE,SRC_LABEL,DST_LABEL,SRC_MAC,DST_MAC,COMMUNITY_ID,SRC_ASN,DST_ASN,PROBE_IP,OBSERVATION_POINT_ID,SRC2DST_TCP_FLAGS,DST2SRC_TCP_FLAGS,SCORE,L7_PROTO_MASTER,CLIENT_NW_LATENCY_US,SERVER_NW_LATENCY_US,CLIENT_LOCATION,SERVER_LOCATION,SRC_NETWORK_ID,DST_NETWORK_ID) FORMAT CSV). (NO_DATA_TO_INSERT)

**Comment by simonemainardi** [comment]
Should be resolved as part of https://github.com/ntop/ntopng/issues/6121

**Comment by lucaderi** [comment]
Verified as fixed
