### ISSUE TITLE
The selected interface is lost when navigating between pages

### ISSUE THREAD

**Issue by mcodato** [ntop/ntopng#6143]
Hi, we are experiencing the loss of interface selection when navigating between pages.

The steps to reproduce:

1. Select an interface (not the first one)
![before](https://user-images.githubusercontent.com/64135571/146380892-69cf203d-3656-4281-9a0f-a8a0a0bb4570.png)
2. Navigate to another page
3. The `ifid` parameter is not forwarded to the new page and the interface selection is lost
![after](https://user-images.githubusercontent.com/64135571/146380932-b2cdefc7-81e6-475f-be30-120501347dbf.png)

Other information:
- ntopng-5.0.211015-14751.x86_64
- CentOS Linux release 7.9.2009 (Core)

Please tell me if more information is needed or if you have problems reproducing it.
Thanks to all in advance

**Comment by MatteoBiscosi** [comment]
Hi, from which page to which page did you go?

**Comment by mcodato** [comment]
Hi @MatteoBiscosi, from `Flows` to `Traffic Dashboard`
but also
from `Traffic Dashboard` to `Interface`
from `Interface` to `Alerts`
from `Alerts` to `Maps / Hosts` 
from `Hosts / Hosts` to `Hosts / Networks`
from `Hosts / Networks` to `Hosts / Host Pools`
from `Hosts / Host Pools` to `Hosts / Autonomous Systems`
from `Hosts / Autonomous Systems` to `Hosts / Countries `
from `Hosts / Countries ` to `Hosts / Operating System`
from `Hosts / Operating System` to `Hosts / HTTP Servers`
from `Hosts / HTTP Servers` to `Hosts / Top Hosts`
from `Maps / Geo Map` to `Flows`
and vice versa

**Comment by mcodato** [comment]
The problem was on our side: we generate the session token by calling the API and then set it in cookies via the `session` key.
Looking at the code ([here](https://github.com/ntop/ntopng/blob/ed9bb187cf0119523e81178fd8112a9b5bf79535/src/HTTPserver.cpp#L226)) we saw that the `session_<http_port>_<https_port> cookie is also needed. 
By setting it the problem was solved.
At this point, I think it can be closed.
Thanks

**Comment by MatteoBiscosi** [comment]
Alright, @mcodato, yeah, we use a special cookie for security.
Thanks a lot for your help.
