### ISSUE TITLE
Create SNMP Interface Traffic Alert

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6144]
This is to request the implementation of a new check for detecting situations such as 
![image](https://user-images.githubusercontent.com/4493366/146517029-3d0c2c06-3950-471a-b880-6260bb9bae1f.png)

In essence 
- the interface is up
- the interface made traffic in the past
- the interface is not making traffic for some time (e.g. 10 mins)

then implement the opposite check for detecting interfaces up with no traffic, that at some point start exchange traffic. 

These checks are important in particular for high availability, as the system continues to work but we're in emergency and this needs to be detected.

**Comment by MatteoBiscosi** [comment]
Checks implemented as requested
![Screenshot from 2022-07-20 12-44-57](https://user-images.githubusercontent.com/49585191/179963739-2508d58a-63cd-4508-ae6a-90f0d909cd72.png)

**Comment by MatteoBiscosi** [comment]
Implemented as requested, available only from Enterprise M
