### ISSUE TITLE
Alerts filter not working

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6153]
Dear ntop team,
It seems the GUI filter in e.g. flows, past 30min, is not working. I can set one filter, that is ok, but when I add a second one is not working anymore, result is "no data available". I set filter "Application on non standard port" the list get filtered, I select a host out of that filtered list and it shows no data.
Thank you.

**Comment by cardigliano** [comment]
@martinscheu I pushed a fix for filtering on hosts with the IP address only (no host name), was this the case? A new package will be available in ~1h from now

**Comment by martinscheu** [comment]
@cardigliano thanks, it seems to work now.
Maybe could change the shown text from "no data available in the table" to "no data available in the selected time frame" ?
otherwise can close this ticket.

**Comment by cardigliano** [comment]
That's a generic message from the js datatable library, I will check if we can set it
