### ISSUE TITLE
ntopng not getting flows from nprobe 

### ISSUE THREAD

**Issue by ginobyte** [ntop/ntopng#6154]
Hi,
I have a virtual machine with both ntopng and nprobe installed, I followed the steps outlined in the ntop.org packages site.
I start the Ntopng service : 
ntopng -i tcp://127.0.0.1:5556
I start the Nprobe as :
nprobe --zmq "tcp://127.0.0.1:5556" --zqm-disable-buffering -i none -n none --collector-port 9995 --collector-passthrough -T "@NTOPNG@"
There are Cisco Routers and Switchs thant send netflow packet using udp 9995 port periodycally....but I don't see nothing in NTOP .
Netflow traffic arrive on the virtual interface verified with TCPdump.
I'm running NProbe-NTOPng on a fresh Centos8 installation.
Thank in advance for any idea or suggest

**Comment by simonemainardi** [comment]
- make sure Centos8 is not firewalling the traffic (even if you see it with tcpdump the firewall can still block it)
- check ntopng under the interface page. Are interface updates increasing?

**Comment by ginobyte** [comment]
Hi Simone, Yes I had to disable firewalld to see some flow from the interface 127.0.0.1:5556, but now I see like exporters the IP of real interface of Nprobe/NTOP system and not the Routers IP's that sending flow....I see the routers in snmp devices polled....then, I think for license scope, the probe collect only 5028 flow...It's possible to use a community license ??

8/Dec/2021 10:32:09 [collect.c:2993] ERROR: ***************************************************************************
28/Dec/2021 10:32:09 [collect.c:2994] ERROR: * NOTE: You have reached the max demo 5028 flows export: no more exports *
28/Dec/2021 10:32:09 [collect.c:2996] ERROR: * NOTE: no additional flows will be exported by this nProbe instance      *
28/Dec/2021 10:32:09 [collect.c:2997] ERROR: ***************************************************************************

![image](https://user-images.githubusercontent.com/18533043/147556030-b6130f4e-7dff-49e3-afda-11b29a9db52b.png)

**Comment by lucaderi** [comment]
No you need an nProbe license for doing this permanently
