### ISSUE TITLE
Aggregate flow according to IP_ADDRESS instead of VLAN ID.

### ISSUE THREAD

**Issue by thomasbruchet** [ntop/ntopng#6158]
Hello,

On my infrastructure I've many vlan and many FW. 
I've mirrored a switch port going to a FW to an ntop interface. 
The problem is that the flow are separated with vlan ID instead of aggregate all traffic to a unique IP address
Here is an example of my laptop connected as 10.200.205.22 in VLAN42 connected on FW2
![image](https://user-images.githubusercontent.com/86605223/147471791-5561d4bf-fc43-46ac-b985-abce39ff5a4c.png)

According the NTOP server is mirrored from a switch port and according to the Ethernet Frame VLAN tagged, the flow is decoded with VLAN ID that is not relevant to my orginial VLAN but with the VLAN that I use to travel or to access data. 
![image](https://user-images.githubusercontent.com/86605223/147471865-d9f2ccfc-ac93-44b0-9b20-839a70f905e7.png)

An other kind of issue is that the Traffic Dashboard is not relevant as you can see here with 3 IP in double with same speed
![image](https://user-images.githubusercontent.com/86605223/147475244-7449f51e-2db6-40b7-9c1c-836660bb076b.png)

This "problem" occur on each flow send to ntop so is there an way to manage host and flow with only the IP_ADDRESS without take care of the VLAN ID from the Ethernet Frame ?

**Comment by cardigliano** [comment]
Did you check the --ignore-vlans option in ntopng?

**Comment by thomasbruchet** [comment]
Hello,

I'd search the option in configuration and I'ven't seen it exist in the command lines options.
That work.

You can close the case. 
Thank you.
