### ISSUE TITLE
[Detected Alerts] - Links to the alert list are invalid

### ISSUE THREAD

**Issue by thomasbruchet** [ntop/ntopng#6159]
Hello,

The links to alerts in "Detected Alerts" are invalid. ( /lua/alert_stats.lua?ifid=5&status=engaged )

When I click on the top of screen on the alert button (1), the links on (2) are invalid
![image](https://user-images.githubusercontent.com/86605223/147474707-9f8fce1d-23ce-4e8a-8f9e-2b82acbe226e.png)
/lua/alert_stats.lua?page=host&epoch_begin=1640003230&epoch_end=1640608030&status=engaged&severity=5;gte
/lua/alert_stats.lua?page=interface&epoch_begin=1640003883&epoch_end=1640608683&status=engaged&severity=4;eq
![image](https://user-images.githubusercontent.com/86605223/147474532-65d9cf6f-4757-4874-98e3-143e494db84b.png)

If I click on (3) there are no problem.
/lua/alert_stats.lua?page=host&epoch_begin=1640003883&epoch_end=1640608683&status=engaged
/lua/alert_stats.lua?page=interface&epoch_begin=1640003883&epoch_end=1640608683&status=engaged

I've tried to debug it without success.
When I'm on this page, all is OK.
/lua/alert_stats.lua?page=host&epoch_begin=1640004322&epoch_end=1640609122&status=engaged

If I add a filter like severity=ERROR
The **filter is not applied** as we can see on my screen; Filter severity set to Error and warning are still displayed and the URL change to /lua/alert_stats.lua?severity=5%3Beq&epoch_begin=1640005096&epoch_end=1640609896&status=engaged&page=interface

If I refresh this new URL with the "severity=5%3Beq" I've the error
![image](https://user-images.githubusercontent.com/86605223/147474451-cf83d643-b399-47d9-8901-b9ce8f25c243.png)
Refresh page ==>
![image](https://user-images.githubusercontent.com/86605223/147474483-3c41a27a-8da0-489d-a782-cb5818cd07ac.png)

**Comment by cardigliano** [comment]
@thomasbruchet could you try updating ntopng to the latest revision? It is likely that some (or all) the issues you reported have been already addressed. Thank you.

**Comment by thomasbruchet** [comment]
Hello.

I will update this night on a time slot.

**Comment by thomasbruchet** [comment]
Hello

That work fine now. 

Thank you.
