### ISSUE TITLE
[nEdge] Chart LAN vs WAN traffic

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#6160]
In https://github.com/ntop/ntopng/issues/2915 we have added the support to count the number of userspace packets vs the total number of packets.

This issue requires to chart, in router mode, a chart with two timeseries for each WAN, namely:

- LAN traffic
- Traffic going through the WAN

Resulting chart will be like

![image](https://user-images.githubusercontent.com/3397663/147491844-11f7ad33-384e-4b36-acd5-7899ff580b8c.png)

and will be accessible from the same page of the chart above.

This is useful for the administrator to understand how the LAN traffic flows through the various WANs.

To read the traffic going through the WANs use the same facilities already implemented for the generation of charts in https://github.com/ntop/ntopng/issues/2915.

**Comment by lucaderi** [comment]
This wil be implemented via SNMP by deploying the snmpd package on the host where nEdge is installed/
@cardigliano will check SNMP support in nEdge

**Comment by cardigliano** [comment]
SNMP is currently enabled in nEdge Enterprise and can be used to display interface charts
