### ISSUE TITLE
Flow flapping

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6161]
![Screen Shot 2021-12-28 at 18 57 45](https://user-images.githubusercontent.com/4493366/147593875-d62f8053-3e12-43ac-8dd1-217efb672e82.png)

The above example is an idle SSH connection causing many flows/alerts to be generated instead of just one. Possible solutions
- generate the alert when the flow has a SYN set (i.e. the first of these subflows)
- change something in flow duration timeouts

**Comment by MatteoBiscosi** [comment]
Implemented as requested
