### ISSUE TITLE
interface flow export counter

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6163]
Dear ntop team
With the added option of flow / alert export to clickhouse the counters on the interface overview page do not count up the exported flows.
thank you
![IMAGE 2021-12-30 14:36:50](https://user-images.githubusercontent.com/38549755/147756811-0071c5c3-725c-46b9-b51e-fb1dd7da8345.jpg)

**Comment by lucaderi** [comment]
This has been fixed already
