### ISSUE TITLE
filter input verification

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6164]
Dear ntop Team
Filtering for alerts it seems is not verified:
<img width="830" alt="Screenshot 2021-12-27 at 16 09 25" src="https://user-images.githubusercontent.com/38549755/147758610-89cfabd0-6bf5-4cb3-845e-0325ed441682.png">
Further clearing filters seems not to work neither and reloading pages adds the selected filter again.
thanks.

**Comment by cardigliano** [comment]
@martinscheu could you specify the exact steps you follow to add and clear the filters? Clearing them seems to be always working for me..

**Comment by cardigliano** [comment]
As of the filter verification, it has been fixed in de6e79b7f82d016278516a2f25157cc7aa001ab0 to avoid the same value to be set even with different operators

**Comment by martinscheu** [comment]
@cardigliano ok thanks, yes verification is fixed. 
but now when I have set a filter and later would like to negate it, it doesn't work.
clearing filters visually works, but I am not sure if it does clear the filter, as it get stuck, new filters are not taken into account. To work I need to leave the page and go back to the alerts page.
Also a page refresh doubles the set filters.
thank you!

**Comment by martinscheu** [comment]
also I realized, when setting e.g. the time selection to "one week" first time it works, but if then I want to change it to something else, it doesn't work.
I works when changing from 1 Day to 1 Week, but not the other way around.

**Comment by cardigliano** [comment]
@martinscheu I am not able to reproduce what you reported, could you please check the browser console for javascript errors and report them in case? Thank you.

**Comment by cardigliano** [comment]
Fix provided in e8eebd574023c86aaffd3f44c85eda7830eacd20 (new packages in 1h)

**Comment by martinscheu** [comment]
thanks for the fix, @cardigliano.
it is working now
