### ISSUE TITLE
Segmentation fault/Ntopng - When dumping expired flow to mysql 

### ISSUE THREAD

**Issue by ganz67** [ntop/ntopng#6167]
On Mac Mojave 10.14.4 Intel Core-i5
$ mysql -V
mysql  Ver 14.14 Distrib 5.6.15, for osx10.6 (i386) using  EditLine wrapper
$ mysqld -V
mysqld  Ver 5.6.15 for osx10.6 on i386 (MySQL Community Server (GPL))

Pulled the latest dev branch from Github, compiled and when starting ntop with -dump-expired-flow to MySql enabled, I get a segmentation fault when ntop tries to close the the db connection. Attached are the ntopng.conf file and the output of the debugger. Luca needed the log trace (from discord interactions) but was not sure which file to send.  Will provided more details if you point me in the right direction.

My end goal  is to  add mac address info to the expired flow dump.
Thanks!

[ntopng_conf.txt](https://github.com/ntop/ntopng/files/7799803/ntopng_conf.txt)
[gdb-output.txt](https://github.com/ntop/ntopng/files/7799804/gdb-output.txt)

**Comment by lucaderi** [comment]
You code is not in sync with github

**Comment by ganz67** [comment]
Good news Luca. I wiped out the old MySql install and upgraded to MySql 8 and things are working now! 
Thank you for all your help. I am closing this ticket now.
