### ISSUE TITLE
Changing the ntopng default interface

### ISSUE THREAD

**Issue by wwazzi** [ntop/ntopng#6168]
Hello,
I have ntopng installed with Endian Firewall Community; however when i open ntopng on browser it only shows the br0 interface, how can I change the interface to be able to check the internet interface?
I cant update ntopng since the Ebdian  Firewall in installed on a device with :
Linux 4.4.145.e6.4 #1 SMP PREEMPT Fri Aug 13 17:36:19 UTC 2021 x86_64 GNU/Linux

I tried using ntopng -i eth1 but it gave me an error:  ERROR: Unable to locate docs dir

**Comment by lucaderi** [comment]
You need to contact the Endian team or check where the ntopng config file is located (probably under /etc/ntopng) and change there the interface name as I believe the config file contains the path of the ntopng data files

**Comment by wwazzi** [comment]
Thank you,
I was able to find the ntopng.conf file i updated the interface; but when restarted the device it was reset to br0 interface.
is there any other file that needs to be modified as well. or what would be affecting this please.
Appreciate your help.
