### ISSUE TITLE
Document ZMQ exchange to set up data collection

### ISSUE THREAD

**Issue by masaeedu** [ntop/ntopng#617]
I need to use ntopng to visualize network flows, but need to do so in an environment which cannot accept the nprobe license terms. Since ntopng is ostensibly decoupled from nprobe, it should be able to communicate with a simple remote ZMQ socket that implements a subset of the functionality of nprobe. Is there any documentation available that details the required ZMQ exchange between a probe and the ntopng collector to set up collection of network data?

**Comment by lucaderi** [comment]
What are the license terms that you cannot accept? Did you see this http://www.ntop.org/ntopng/creating-a-hierarchical-cluster-of-ntopng-instances/ ?

**Comment by masaeedu** [comment]
Per-system licenses are difficult because we need to be able to setup/teardown our entire deployment and report data from an indeterminate number of dynamically created VLANs, plus I'm not sure I could convince management to purchase a license since this is not business-essential.

I read through that article but don't quite see what you mean. Are you suggesting that I should use ntopng instances local to each LAN as a substitute for nprobe?

**Comment by lucaderi** [comment]
So in essence as long as everything is free, the management is happy. Sure but this way open source will die.

Yes you can use ntopng instead of nprobe if that's enough,

**Comment by masaeedu** [comment]
> So in essence as long as everything is free, the management is happy. Sure but this way open source will die.

Well I also told you about why your licensing model doesn't work for our use case, and nProbe isn't open source so I'm not sure how this is relevant. It's clear however that this is not an avenue you're interested in exploring.
