### ISSUE TITLE
Change Alerts Chart

### ISSUE THREAD

**Issue by MatteoBiscosi** [ntop/ntopng#6170]
The chart reporting the number of alerts is meaningless into the alerts page. It should be better to add more cards (like Top Hosts and Top Alerts) to give more information to the user and possibly add the ability to create one or two custom cards.
![Screenshot from 2022-01-03 11-36-03](https://user-images.githubusercontent.com/49585191/147921326-5af98daf-bef8-4139-b223-b3c3912ba33c.png)

**Comment by lucaderi** [comment]
Reworked alerts
