### ISSUE TITLE
Add Get Permanent Filters

### ISSUE THREAD

**Issue by MatteoBiscosi** [ntop/ntopng#6172]
It is requested to add a way to save the current filters of the Alerts/Historical Flow Explorer page and re-add them in the future. In this way if a user wants to search a specific alert, he can save the filters and when he needs it, he just need to paste those filters to get back the filtered alerts he wants.

**Comment by lucaderi** [comment]
There are two options on the table
- create a dialog where you can save/retrieve the current filters
- do something as wireshark does that keeps track of the latest X filters. See example below
![Screen Shot 2022-06-27 at 14 21 14](https://user-images.githubusercontent.com/4493366/175940108-74949e6b-325e-445a-bd9b-2d38d733c610.png)

**Comment by uccidibuti** [comment]
Snapshots icon is now available and it allow to save / select / delete a filter. You must have ntop Enterprise license.
![image](https://user-images.githubusercontent.com/12447209/178725284-5f1b1f8f-211d-4fff-8a6e-52f3de548a92.png)

**Comment by MatteoBiscosi** [comment]
Implemented as requested
