### ISSUE TITLE
System Notifications - New Endpoint Form Field Validation

### ISSUE THREAD

**Issue by TomSchober** [ntop/ntopng#6175]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04.3 LTS
* Architecture: x86
* ntopng version/revision: ntopng Community v.4.2.210729

**What happened**:
Form validation for a new "Email" Notification Endpoint is not allowed with certain valid form data.

**What did you expect to happen?**
Form validation should allow submission.

**How did you reproduce it?**
1. Navigate to System > Notifications > Endpoints
2. Add New Endpoint
3. Enter a valid 21 char SMTP Username
4. Enter a valid SMTP Server with a digit-only domain name

**Debug Information**:
![Screenshot from 2022-01-03 12-13-10](https://user-images.githubusercontent.com/1459967/147960027-c161a38f-bdd7-4fa4-a111-77dfc13ecdad.png)

**Comment by TomSchober** [comment]
Further context.  The form source is located here:
https://github.com/ntop/ntopng/blob/4.2-stable/scripts/plugins/endpoints/email_alert_endpoint/templates/email_endpoint.template

**Comment by TomSchober** [comment]
It appears the regex for email validation on the client is defined here:
https://github.com/ntop/ntopng/blob/4.2-stable/httpdocs/js/ntop_utils.js#L45

**Comment by cardigliano** [comment]
@TomSchober any chance you can update to the latest stable (5.0) or dev (5.1)?

**Comment by TomSchober** [comment]
Unfortunately this is not possible.  This is version-locked into a plugin configuration for another system.  The dependency uses4.2-stable.

**Comment by TomSchober** [comment]
This is an easy fix as a regex update, and when I get the time I will PR this myself.  When it comes to email and RFC5322 there is no "rule;" just good advice for the context of the application.  I'd follow:
https://stackoverflow.com/questions/201323/how-can-i-validate-an-email-address-using-a-regular-expression/201378#201378

**Comment by cardigliano** [comment]
@TomSchober it seems that your email (admin@111.net) is recognized by the current regexp (ntopng 5.0 and 5.1). Please note 4.2 is no longer supported.
