### ISSUE TITLE
The "Service Map" with "Host Pool"  always returns "No services were found."

### ISSUE THREAD

**Issue by Yoshihiro-jp** [ntop/ntopng#6176]
**Environment**:
* OS name: [e.g. Ubuntu] Ubuntu
* OS version: [e.g. 18.04] 20.04.3 LTS
* Architecture: [e.g. amd64]  x86_64
* ntopng version/revision: [e.g. 5.1.211223]  5.0.211220 [Enterprise/Professional build] 

**What happened**:
The "Service Map" with "Host Pool"  always returns "No services were found.". Kindly refer to the attached file.

**What did you expect to happen?**
It should show the service map with specific "Host Pool".

**How did you reproduce it?**
In the "Service Map" menu I choose one of the "Host Pool".
Actually even if I choose other ones it is the same. It always returns "No services were found.".

**Debug Information**:
Kindly refer to the attached file.
[service map bug.zip](https://github.com/ntop/ntopng/files/7804862/service.map.bug.zip)

**Comment by Yoshihiro-jp** [comment]
I did "Factory Reset" in the "Manage Configurations" then created "Host Pool" again.
Now the problem what I reported was gone...
I would report it if I encountered the same problem.

regards,
Yoshihiro

**Comment by MatteoBiscosi** [comment]
Hi Yoshihiro, could you please tell me which entry are you using into the `Local Broadcast Domain Hosts Identifier` interface preference (in my case for example is `IP address`)?
![Screenshot from 2022-01-04 11-44-16](https://user-images.githubusercontent.com/49585191/148047560-cfe7dd53-4425-4b80-b371-82310935329a.png)

**Comment by Yoshihiro-jp** [comment]
@MatteoBiscosi 
I remember that I set  the "MAC Address" when the problem happened.
By the way I can't reproduce the problem after "Factory Reset" even if I set it with "MAC Address"...

So I think that I should close this ticket then if I did reproduce it I would make the new ticket.
Is it okay?

regards,
Yoshihiro

**Comment by MatteoBiscosi** [comment]
Alright @Yoshihiro-jp , if the issue arise again please open a ticket and i'll take a look at it

**Comment by Yoshihiro-jp** [comment]
> Alright @Yoshihiro-jp , if the issue arise again please open a ticket and i'll take a look at it

Dear @MatteoBiscosi,
 
The problem happened again.
I got the screenshot and don't do "Factory Reset" now.
If you are okay I could provide the access to my server.
Kindly think about it.


[service map problem_20220114.zip](https://github.com/ntop/ntopng/files/7868457/service.map.problem_20220114.zip)

regards,
Yoshihiro

**Comment by Yoshihiro-jp** [comment]
Dear @MatteoBiscosi ,

Could you re-open this ticket?
I think that this is really problem.

regards,
Yoshihiro
