### ISSUE TITLE
hosts/flows counters colors in the right side of the footer ?

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#618]
On my ntop I can see that flows link changes sometimes of color : orange/red
it seems to me orange when flows > 75k and red >110k something like these values

my question is why these steps ? is it something to warn that server is limit for these values ?

thanks

Nico

**Comment by simonemainardi** [comment]
see https://github.com/ntop/ntopng/blob/dev/scripts/lua/inc/footer.lua#L330
between 60 and 90% of the maximum value the color becomes orange, above 90% becomes red

**Comment by Niko78** [comment]
ok but what's the maximum value ?

**Comment by simonemainardi** [comment]
did you know ntopng has a `--help` option? (https://github.com/ntop/ntopng/issues/563#issuecomment-219467007)

```
[--max-num-flows|-X] <num>          | Max number of active flows
                                    | (default: 131072)
[--max-num-hosts|-x] <num>          | Max number of active hosts
                                    | (default: 65536)
```
