### ISSUE TITLE
Add POST NAT support when collecting from routers via nProbe

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#6182]
ntopng receives Post NAT information when collecting flows from routers via nProbe. When this information is available, ntopng should show the actual source IP (and port if remapped) as provided in the Post NAT information, instead of the router's IP.

<img width="544" alt="post_nat_example" src="https://user-images.githubusercontent.com/7548711/148525264-290feaab-5127-45c4-b8d5-3f6737aaa2e2.png">

**Comment by cardigliano** [comment]
There is already a setting to overwrite the Destination or Source address for collected flows with Port-Nat addresses. This is available under Settings -> Preferences -> Network Interfaces -> Use Post-Nat Destination IPv4 Addresses and Ports / Use Post-Nat Source IPv4 Addresses and Ports

**Comment by jult** [comment]
Does this also apply to local network addresses? So, not external ones (WAN), but LAN source and destination IPs?
