### ISSUE TITLE
Extend alerts filter possibilities

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6184]
**What would you like to add or change?**:
Extend the alert filter to search also for any alert listed under "Other Issues":

![image](https://user-images.githubusercontent.com/38549755/148795134-f1ed1235-dc10-4d63-be4d-e65b463aa5a6.png)

Possibility to search for string data, e.g. called URL. Could be with applied Application filter, e.g. http.

**Why do you and others need this?**:
When knowing what to look for, this additional filter possibilities would make the search much faster.

thanks

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu most of the "Other issues" fields are currently searchable (not directly on Other Issues filter, but using other filters, e.g. the URL, using the info field)
