### ISSUE TITLE
Cannot find HTTP Servers in Historical Flows

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#6186]
**Environment**:
* OS name: Ubuntu
* OS version: 18
* Architecture: Intel
* ntopng version/revision: 5.1.220110

**What happened**:

There are some hostnames under the Hosts -> Server HTTP which are not present in the Historical Flows page, or at least a filter on Server Name with the same hostname does not provide results.
Also, the 'timeseries' chart at the top of the same page, shows matching records, while the table is empty.

**Comment by lucaderi** [comment]
![Screen Shot 2022-01-10 at 21 31 54 1](https://user-images.githubusercontent.com/4493366/148835049-1490de71-eaea-462a-b2dd-4d82d896508a.png)
Also note that the chart reports results that cannot be displayed in the table

**Comment by cardigliano** [comment]
For TLS traffic, the server name is stored in the info field. It is required to add the ability to filter on that field as first step.

**Comment by cardigliano** [comment]
Implemented in a3bce393cad65a9986a1e025f41c6600f06ddf5e (and pro 2823524ecd59a50cb6a009ef8026fcf26562ecfe)

**Comment by cardigliano** [comment]
Chart fixed in pro 5b9f13ab618aa6e46d8c2517d52909b599cefe1a

**Comment by lucaderi** [comment]
Verified as fixed
