### ISSUE TITLE
PB when install ntopng

### ISSUE THREAD

**Issue by AnhTuanNguyenn** [ntop/ntopng#6187]
**Environment**:
* OS name: pfsesne
* OS version: 12.2-STABLE
* Architecture: amd64
* ntopng version/revision: 

hi, when i install ntopng, i cant start ntop via cmd line, someone help me pls
when i start with "service ntopng start "
/usr/local/etc/rc.d/ntopng: WARNING: /usr/local/etc/ntopng.conf is not readable.
/usr/local/etc/rc.d/ntopng: WARNING: failed precmd routine for ntopng

thank for your helps

**Comment by lucaderi** [comment]
Please use a recent version (5.x) and either compile it from the source or use a binary package available from packages.ntop.org. Version 2.5 is outdated and unsupported

**Comment by AnhTuanNguyenn** [comment]
hello, i try install follow this link but it not work too 
https://packages.ntop.org/FreeBSD/
and i have same pb 
/usr/local/etc/rc.d/ntopng: WARNING: /usr/local/etc/ntopng.conf is not readable.
/usr/local/etc/rc.d/ntopng: WARNING: failed precmd routine for ntopng
