### ISSUE TITLE
can't start ntopng [Ntop.cpp:2387] Parent process is exiting (this is normal)

### ISSUE THREAD

**Issue by AnhTuanNguyenn** [ntop/ntopng#6189]
**Environment**:
* OS name: pfsense 
* OS version: 12 stable
* Architecture:  amd64
* ntopng version/revision: 5.1

when i try to install ntopng via command 
https://www.ntop.org/guides/ntopng/third_party_integrations/pfsense.html#pfsense-ce-2-5-pfsense-plus

i cant started ntopng and i have error 

`11/Jan/2022 15:09:59 [Ntop.cpp:3416] Created pinger for vmx0
11/Jan/2022 15:09:59 [Ntop.cpp:3416] Created pinger for enc0
11/Jan/2022 15:09:59 [Ntop.cpp:3416] Created pinger for ovpns1
11/Jan/2022 15:09:59 [Ntop.cpp:3416] Created pinger for ovpns2
11/Jan/2022 15:09:59 [Ntop.cpp:3416] Created pinger for lo0
11/Jan/2022 15:09:59 [Ntop.cpp:3416] Created pinger for vmx1
11/Jan/2022 15:09:59 [Ntop.cpp:3416] Created pinger for vmx2
11/Jan/2022 15:09:59 [Ntop.cpp:3416] Created pinger for vmx3
11/Jan/2022 15:09:59 [Ntop.cpp:2387] Parent process is exiting (this is normal)
`
thank for your help !!

**Comment by cardigliano** [comment]
(debugging this via mail)

**Comment by AnhTuanNguyenn** [comment]
thank you, 
waitng your news :)

**Comment by AnhTuanNguyenn** [comment]
Now, I can access ntop with 10min, it’s so good, Now I just wanna how to save log flows if I use version Pro please ? 

I can’t find out option to enable dump the log in preferences

**Comment by MatteoBiscosi** [comment]
Hi @AnhTuanNguyenn check out the documentation to dump flows https://www.ntop.org/guides/ntopng/advanced_features/flows_dump.html?highlight=dump, here you can find a detailed guide to do it

**Comment by MatteoBiscosi** [comment]
The bug should be fixed, please reopen if needed
