### ISSUE TITLE
alert or not alert ?

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#619]
in ntop I have a host which is scanning network
I thought ntop could detect it as alert but it doesn't appear like that
do I need to change thresholds ? I let all the defaults

![scan](https://cloud.githubusercontent.com/assets/17108017/16195393/b0cb9436-36f9-11e6-808c-575b9e0baf1b.png)

Nico

**Comment by lucaderi** [comment]
In this ntopng version to avoid false positives we have set the threshold to 
#define CONST_MAX_NUM_HOST_ACTIVE_FLOWS 65536
but in post 2.3 ntopng version we will expand this detection and thus make alerts more flexible

**Comment by Niko78** [comment]
any ETA for this new version ?
