### ISSUE TITLE
Unknown MAC detected

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6192]
Implement a check that stores in redis (subject to a preference for retention set to default to 90 days, and a preference fr the learning period similar to the service map) known MAC addresses. Whenever a MAC is observed past the learning period, we need to check if the MAC is unknown and in this case trigger an alert.

**Comment by martinscheu** [comment]
What is the difference to the Check "Unexpected Device Connected" ?

**Comment by martinscheu** [comment]
How can we manage devices past the learning period? Alerting new devices is good, but then if it is a new device I add on purpose, I need to be able to add it to the allow list. Further if I remove a device, I should remove it from the list as well. Some sort of GUI to manage allowed MAC addresses would be helpful, for both removing and adding devices.

**Comment by dpetzer** [comment]
> How can we manage devices past the learning period? Alerting new devices is good, but then if it is a new device I add on purpose, I need to be able to add it to the allow list. Further if I remove a device, I should remove it from the list as well. Some sort of GUI to manage allowed MAC addresses would be helpful, for both removing and adding devices.

Correct would require a GUI to manage, perhaps some states, "investigating", "authorized" or if you reject it then it will generate another alert the next time it is seen. 

There could also be some configurations about removing MAC/IP combinations that are known if they are not seen for some time.
So if an item is decommissioned the users do not need to manually remove it, after some months it will be removed.

**Comment by MatteoBiscosi** [comment]
Depends on #6800 #6801

After internal review we decided to change the check in the following way:
The alert is going to be an engaged alert, until the MAC disappears from the network or it's put as "allowed" MAC.
A new GUI is going to be implemented, adding the possibility to manage the allow / disallow / white list thing.
Other then that no learning period is going to be put in this alert

**Comment by lucaderi** [comment]
Already implemented

**Comment by wasya2020** [comment]
Hi Luca. Is it possible to have an alarm triggering when a new IP is detected on the network ? Many thanks.
