### ISSUE TITLE
Implement BPF Filter Validation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6198]
![Screen Shot 2022-01-12 at 21 12 33](https://user-images.githubusercontent.com/4493366/149214549-3faebe3f-cf29-4c3e-85a3-1b657d70e7df.png)

In the above field (a similar one can be found under a host) there is no BPF filter validation, so anything can be written in the field without the user to be notified that the filter is wrong and then that is ignored.

**Comment by cardigliano** [comment]
Implemented in dbc00c715511de4a666d61169b7be08ab7e0ead1 c51f779bc9bb64ff7ac010358dd564f4cfd9e2ef

**Comment by lucaderi** [comment]
Verified as fixed
