### ISSUE TITLE
Implement ClickHouse Number of Records

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6199]
In the following window add
- number of flow records (alerts and flows)

![Screen Shot 2022-01-12 at 21 14 47](https://user-images.githubusercontent.com/4493366/149214931-d4210ac3-cdd1-4727-9d22-35dc178ed979.png)

**Comment by MatteoBiscosi** [comment]
Added like the following.
![Screenshot from 2022-01-13 12-53-26](https://user-images.githubusercontent.com/49585191/149325653-391dfa1b-0981-426c-95a1-22c2c56f79ea.png)

**Comment by lucaderi** [comment]
Verified as fixed
