### ISSUE TITLE
99% dropped packets after update to ntopng Community v.2.0.150619 

### ISSUE THREAD

**Issue by AlexWolf54** [ntop/ntopng#62]
Hey guys, I’ve got 99% dropped packets after update to NtopNG Community v.2.0.150619.
Only in the first 2 minutes the flow information are shown after reset the NtopNG settings via Nbox .
Could you please help? BR Alex

**Comment by ariava** [comment]
@AlexWolf54 could you please provide details on your system setup and ntopng configuration?

**Comment by AlexWolf54** [comment]
I´ve got Ubuntu 12.04 LTS x64 running and my ntopng.conf contains following parameters:
-n=1
-W=0
-g=-1
-m="10.82.0.0/16,10.0.0.0/8"
-C
-P
-G=/var/tmp/ntopng.pid
-i=eth0

The ntopng instance does not update the bps in the footer and shows 99% dropped packets.
Same problem description I found here:
https://github.com/ntop/ntopng/issues/63
Also the CPU is loaded up to 100% with the ntopng instance.
It was working fine before update I´ve done the update to v.2.0.150622

**Comment by philoo9999** [comment]
same problem here

**Comment by lucaderi** [comment]
Hi all, I cannot reproduce the bug and I need to debug it on your host if possible. Can you please contact me in private and let me know how to do this debug session?

**Comment by lucaderi** [comment]
Please note that we have fixed a loop bug about 10 days ago, so I believe you are affected by this issue. Please update first to the latest version (any July version would work) and report.

**Comment by ariava** [comment]
@AlexWolf54 @philoo9999 any news about the fix @lucaderi added?

**Comment by AlexWolf54** [comment]
I´ve reinstalled server and ntopng. after that it was working fine!

**Comment by lucaderi** [comment]
Good so the bug on nDPI was the reason
