### ISSUE TITLE
Incorrect timezone on alerts and historical flow explorer tab

### ISSUE THREAD

**Issue by tierry** [ntop/ntopng#6201]
Hi, my ntop alerts and historical flow explorer is using UTC instead of UTC-4. Im using influx and clickhouse to dump flows.
Im trying to fix it to use UTC-4 but i cant find a solution.
![image](https://user-images.githubusercontent.com/7729974/149343087-1950b114-d760-4f3c-927d-cc421e0accde.png)

**Comment by MatteoBiscosi** [comment]
Hi @tierry Unfortunately we are using the standard HTML input tag and as you can see from the official documentation https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time it's not possible to change the Timezone; it's based on the browser settings. If you know a way to fix this problem please let us know.

**Comment by MatteoBiscosi** [comment]
Like I said, input time and input date formatting depends on local browser time (written in the official doc above). The only way to fix it is changing the web browser local time

**Comment by tierry** [comment]
Ok, thx!

**Comment by MatteoBiscosi** [comment]
Hi @tierry please follow issue #6210, I got an idea on how to use local time instead of UTC

**Comment by tierry** [comment]
Hi @MatteoBiscosi thank you!
It worked on flow explorer correctly, but on alerts im still getting some UTC time
![alerts](https://user-images.githubusercontent.com/7729974/150583620-eeccb1f1-9c5a-4ef2-9e26-1e8125bd7639.png)
.
