### ISSUE TITLE
Historical Flow Explorer: Add ability to filter Interface IDs

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6202]
In the historical flow explorer, it is requested to add the ability to filter flows based on the interfaceId.

Note that such interfaces should be resolved (for easier mapping) to symbolic names in case SNMP is present.

**Comment by cardigliano** [comment]
Filter on in/out interface has been implemented, using the interface number for the time being.

**Comment by lucaderi** [comment]
Verified as fixed
