### ISSUE TITLE
Ignored Filter Selection

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6204]
![Screen Shot 2022-01-13 at 17 54 00](https://user-images.githubusercontent.com/4493366/149373911-e85a2d3c-8ef6-41f6-b98e-0e9592719b20.png)

On the above page, DNS is filtered and charts are not using the filter as they should. This needs to be fixed not only on this page but also on all pages of the analysis section as also other pages (under Analysis) seem to be affected by the same bug.

**Comment by cardigliano** [comment]
Fixed in b396a8585e67bc7567a52c048d0da6deba65c46f

**Comment by lucaderi** [comment]
Verified as fixed
