### ISSUE TITLE
Missing filters on bytes/packets in the Historical Flow Explorer

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6206]
Currently, it is not possible to search flows using bytes and packets as criteria. Example all the flows with > 10 MB or flows with < 20 packets. This should be implemented,

**Comment by cardigliano** [comment]
Implemented in pro ec735b0146ac3c5d6fd65cb075050d4b479c1506

**Comment by cardigliano** [comment]
Note: the bytes selector component can still be improved to let select the unit (not sure it is worth adding it at this point)

**Comment by lucaderi** [comment]
Verified as fixed
