### ISSUE TITLE
Create a FreeBSD 13 binary / OPNsense

### ISSUE THREAD

**Issue by derekslenk** [ntop/ntopng#6208]
**What would you like to add or change?**:
I would like the repository for OPNsense to have a FreeBSD 13 build or provide a binary of a FreeBSD 13  build.

**Why do you and others need this?**:
The upcoming major release of OPNsense, OPNsense v22, is based on FreeBSD 13.

**Comment by lucaderi** [comment]
Please test https://packages.ntop.org/FreeBSD/ and report.

**Comment by derekslenk** [comment]
I was going to say - it installs in OPNsense, but with no integration into OPNsense itself at all. Still attempting to launch from cli properly
