### ISSUE TITLE
FR:  Alert display filters

### ISSUE THREAD

**Issue by DigiAngel** [ntop/ntopng#621]
Process:  Get to hosts_stats.lua, then filter by Local.  Several Alert icons show up.  At this point it would be nice to be able to click on the Alert icon and see Alerts related only to that IP address.

From there, I select an IP address that has alerts.  From host_details.lua it would be nice to click on the Alerts and go to that IP addresses alerts.

Currently both of the above go to show_alerts.lua which shows all alerts.  From show_alerts.lua I am unable to filter.  Thanks so much.

**Comment by simonemainardi** [comment]
the new page with host alerts has been added in the host_details. thank you

**Comment by DigiAngel** [comment]
Thank you!
