### ISSUE TITLE
在使用lua vm时，ntop会报出问题

### ISSUE THREAD

**Issue by hdsjahuen** [ntop/ntopng#6211]
![企业微信截图_1642468529359](https://user-images.githubusercontent.com/97928016/149859805-d818c8a0-0c75-4906-ae81-0f25a85bdca4.png)
当我打开ntop时会出现这个界面，后台的错误信息是这样的
![0df3674d-4b15-4161-8b54-4567ed16ef1b(1)](https://user-images.githubusercontent.com/97928016/149859880-2126ed2a-7745-4246-9fa1-c0d128f203c4.jpg)
报告我的lua vm无法加载，不知道这两个之间是否会相互有什么影响

**Comment by lucaderi** [comment]
English please

**Comment by hdsjahuen** [comment]
When I open the Ntop web interface, it is displayed when it is not currently supported, and then the error message displayed in the background is as shown in the second image, and then the lua vm also shows that it cannot be loaded, I want to ask if there will be anything related between the two
