### ISSUE TITLE
Using ntopng with nProbe for netflow traffic collection 

### ISSUE THREAD

**Issue by assegid14** [ntop/ntopng#6216]
Environment

- Window 10
- ntopng version 5. 
- ntopng license = Enterprise L

Question
How I configure nprobe to collect netflow and forward to ntopng.

thank you!

**Comment by lucaderi** [comment]
Please see https://www.ntop.org/guides/ntopng/using_with_other_tools/nprobe.html#usingntopngwithnprobe

The only difference is that on Windows you have services, so  please also see https://www.ntop.org/guides/ntopng/what_is_ntopng.html#installing-on-windows

**Comment by assegid14** [comment]
Dear Lucaderi. Thank you for the help.
I have an issue of licensing.
1. ntopng is licensed with Enterprise L.
2. Then, I installed nprobe on the same windows host.

However, the nprobe is running in demo mode. The documentation says  ntopng Enterprise L includes nProbe Pro (Flow Collection) licenses.
How can I get the nprobe Pro license from ntopng license.

Thank you!
![photo_2022-01-21_11-27-40](https://user-images.githubusercontent.com/82800059/150494207-bbd13ba0-e8b4-42fb-9381-5b2f5f3576c0.jpg)

**Comment by cardigliano** [comment]
@assegid14 Enterprise L does not include nProbe Pro, that applies to the Bundle only.

**Comment by assegid14** [comment]
@cardigliano According to an official documentation https://www.ntop.org/guides/ntopng/what_is_ntopng.html#ntopng-enterprise-l 

This version also unlocks n2disk 1 Gbit (Continuous Recording) and nProbe Pro (Flow Collection) with no need for additional licenses.
So, what is the solution in order to collect netflow with my current licensing?

Thank you!

**Comment by cardigliano** [comment]
@assegid14 it contains a mistake, I am asking my collleagues to fix it. Please refer to the comparison table at 
https://www.ntop.org/products/traffic-analysis/ntop/ . Sorry for the misunderstanding.
