### ISSUE TITLE
problem ntop 5.1 vs pfsense 2.5.2

### ISSUE THREAD

**Issue by AnhTuanNguyenn** [ntop/ntopng#6220]
**Environment**:
* OS name: pfsense 2.5.2
* OS version: 12 
* Architecture: amd64
* ntopng version/revision: 5.1

Hello
Can i have an tutorial for install ntopng on pfsense correctly pls

I followed the link on ntop site official but my ntopng doesn’t work correctly
I started service ntop but i can’t access web by https or https

On pfsense webgui i can’t see service ntopng working too. Port 3000 is opened

**Comment by AnhTuanNguyenn** [comment]
update
![1642604792043-inkederror-1_li](https://user-images.githubusercontent.com/24913199/150166936-3ae7901f-fc9f-4cdc-9a26-e502a15d1784.jpg)
i check in service i got this 
![1642604682408-error-2](https://user-images.githubusercontent.com/24913199/150167037-b42282fa-1def-46db-b13b-75aa01e2c497.png)

**Comment by lucaderi** [comment]
The issue we see is probably related to the end of the demo mode as I see you use the community edition. Please edit /usr/local/etc/ntopng.conf and add a new line

--community=

then restart ntopng. You can find the user's guide here https://www.ntop.org/guides/ntopng/

**Comment by AnhTuanNguyenn** [comment]
THank Luca for your answer ! but it's seems doen't work
![ntoppp](https://user-images.githubusercontent.com/24913199/150181242-d47f6b8d-b8d0-4e92-a352-90882f900f48.PNG)
and when i go to website the problem is return 
![1642604792043-inkederror-1_li](https://user-images.githubusercontent.com/24913199/150181354-85c4ba14-6b59-4662-8775-ce2092a453cf.jpg)
i was add new line as you said:


![community](https://user-images.githubusercontent.com/24913199/150181747-63214425-f092-4d7c-9506-55ebd0b08871.PNG)

**Comment by AnhTuanNguyenn** [comment]
Hope you can give me a good solution, because I got too much time to debug this problem and i was sent mail to you but i didn't have your return, thanks for advance

**Comment by lucaderi** [comment]
this is a login issue. Can you go you http://yourhost:3000 and sew what happens? 
Can you please any error you see on the ntopng console?

**Comment by AnhTuanNguyenn** [comment]
you can see the log when i started ntopng in terminal 
![150181242-d47f6b8d-b8d0-4e92-a352-90882f900f48](https://user-images.githubusercontent.com/24913199/150232688-572c404b-fff4-451d-8b80-cf8c9769e5fa.png)

![150181354-85c4ba14-6b59-4662-8775-ce2092a453cf](https://user-images.githubusercontent.com/24913199/150232699-db27d617-ed3e-4741-9a34-830f76761092.jpg)

**Comment by lucaderi** [comment]
I have fixed the issue that was related to an old ntopng install that was already present on the machine. Please do
- pkg remove ntopng
- rm -rf /usr/local/share/ntopng/ (in case you have something old)
- pkg clean
- redis-cli flushall
- pkg install ntopng

and it should work. Note that the ntopng config file is at /usr/local/etc/ntopng/ntopng.conf

**Comment by AnhTuanNguyenn** [comment]
Hello, i tried as you told but that's nothing changed, i have same pb
waiting your new

Vào Th 5, 20 thg 1, 2022 vào lúc 15:13 Luca Deri ***@***.***>
đã viết:
