### ISSUE TITLE
[QUESTION] Ntopng Entreprise M vs ClickHouse

### ISSUE THREAD

**Issue by AnhTuanNguyenn** [ntop/ntopng#6227]
Sorry for this question if this question not for this sector !!!

I bought ntopng version entreprise M, i would use it with Clickhosue for save log everydays, it this possible ? i have readed guide and  but i see in the setting a something as n2disk, so i need n2disk for save log ? 

i would know where i can find setting logs as : max day of log [1 weeks or 1 month] 

thank for your help

**Comment by MatteoBiscosi** [comment]
Hi @AnhTuanNguyenn here you can find all the documentation regarding ClickHouse. In ClickHouse we dump only flows and alerts; it uses very few memory for a lot of data.
![Screenshot from 2022-01-20 18-47-28](https://user-images.githubusercontent.com/49585191/150393549-14e83928-8e78-490b-bbd5-52a19984cf9e.png)
Just to give you an idea this is a screenshot from our testing machine.

Using ClickHouse you are gonna be able to navigate throw the Historical Flow Analysis page (here you have the documentation https://www.ntop.org/guides/ntopng/clickhouse/historical_flow_explorer.html).

n2disk is a software used to dump pcap and save raw traffic.

You can find all the settings regarding the logs into Settings->Preferences (Flow Dump Settings for flows, Alerts for alerts and so on)
