### ISSUE TITLE
New Install, NTOPNG reports "Invalid message received: your nProbe sender is outdated or invalid JSON?"

### ISSUE THREAD

**Issue by m00tpoint** [ntop/ntopng#623]
I have 3 Arista switches sending SFLOW data to the server on port 6323.

[root@servername username]# ntopng --version
v.2.2.160623 [Professional Edition]
GIT rev:   2.2-stable:c681e193ad0b8b346e1dddb56fd35707a71097cc:20160623
Pro rev:   r525
System Id: 68B8BF9E76056206
Built on:  CentOS Linux release 7.2.1511 (Core)
[root@servername username]#
[root@servername username]#
[root@servername username]# /usr/local/bin/nprobe --version

Welcome to nProbe v.7.4.160623 (r5328) for x86_64-unknown-linux-gnu
with native PF_RING acceleration.
Copyright 2002-16 ntop.org

Build OS:      CentOS Linux release 7.2.1511 (Core)
SystemID:      68B8BF9E76056206
GIT rev:       7.4-stable:f14cbc322c33cac54ba1e8a3733500423ac9dbf3:20160623
License:       Invalid nProbe license (/etc/nprobe.license) [Missing license file]

nProbe is subject to the terms and conditions defined in
the LICENSE and EULA files that are part of this package.

nProbe also contains third party code:
Radix tree code - (C) The Regents of the University of Michigan
                      ("The Regents") and Merit Network, Inc.
sFlow collector - (C) InMon Inc.
[root@servername username]#
[root@servername username]# /usr/local/bin/nprobe -n none --zmq "tcp://127.0.0.1:1234" &
[8] 1736
[root@servername username]# 23/Jun/2016 17:34:33 [nprobe.c:3383] ERROR: Invalid nProbe license (/etc/nprobe.license) [Missing license file]
23/Jun/2016 17:34:33 [nprobe.c:3390] ERROR: *****************************************************
23/Jun/2016 17:34:33 [nprobe.c:3391] ERROR: *\*                                                 **
23/Jun/2016 17:34:33 [nprobe.c:3392] ERROR: *\*  Switching to DEMO MODE (missing valid license) **
23/Jun/2016 17:34:33 [nprobe.c:3393] ERROR: *\*                                                 **
23/Jun/2016 17:34:33 [nprobe.c:3394] ERROR: *\*  Purchase your nProbe license at                **
23/Jun/2016 17:34:33 [nprobe.c:3395] ERROR: *\*       https://shop.ntop.org/                    **
23/Jun/2016 17:34:33 [nprobe.c:3396] ERROR: *\*                                                 **
23/Jun/2016 17:34:33 [nprobe.c:3397] ERROR: *****************************************************
23/Jun/2016 17:34:33 [nprobe.c:7282] ERROR: ***************************************************************
23/Jun/2016 17:34:33 [nprobe.c:7283] ERROR: \* NOTE: This is a DEMO version limited to 25000 flows export.  *
23/Jun/2016 17:34:33 [nprobe.c:7284] ERROR: ***************************************************************
23/Jun/2016 17:34:33 [plugin.c:168] No plugins found in ./plugins
23/Jun/2016 17:34:33 [plugin.c:176] Loading 24 plugins [.so] from /usr/local/lib/nprobe/plugins
23/Jun/2016 17:34:33 [nprobe.c:4864] WARNING: The output interfaceId is set to 0: did you forget to use -Q perhaps ?
23/Jun/2016 17:34:33 [nprobe.c:4867] WARNING: The input interfaceId is set to 0: did you forget to use -u perhaps ?
23/Jun/2016 17:34:33 [nprobe.c:4967] Welcome to nProbe Pro v.7.4.160623 ($Revision: 5328 $) for x86_64-unknown-linux-gnu with native PF_RING acceleration
23/Jun/2016 17:34:33 [nprobe.c:4977] Running on CentOS Linux release 7.2.1511 (Core)
23/Jun/2016 17:34:33 [nprobe.c:4988] [LICENSE] nProbe SystemId: 68B8BF9E76056206
23/Jun/2016 17:34:33 [nprobe.c:7300] Welcome to nProbe v.7.4.160623 for x86_64-unknown-linux-gnu
23/Jun/2016 17:34:33 [plugin.c:1030] 0 plugin(s) enabled
23/Jun/2016 17:34:33 [nprobe.c:6828] Non IPv4/v6 traffic is discarded according to the template
23/Jun/2016 17:34:33 [util.c:434] GeoIP: loaded AS config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNum.dat
23/Jun/2016 17:34:33 [util.c:445] GeoIP: loaded AS IPv6 config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNumv6.dat
23/Jun/2016 17:34:33 [nprobe.c:5487] Using packet capture length 128
23/Jun/2016 17:34:33 [pro/pf_ring.c:377] Initializing PF_RING socket on device ens160..
23/Jun/2016 17:34:33 [nprobe.c:7476] IPv6 traffic will NOT be exported/accounted by this probe
23/Jun/2016 17:34:33 [nprobe.c:7477] due to configuration options (e.g. use NetFlow v9)
23/Jun/2016 17:34:34 [nprobe.c:7625] Capturing packets from interface ens160 [snaplen: 128 bytes]
23/Jun/2016 17:34:34 [util.c:4036] Initializing ZMQ as server
23/Jun/2016 17:34:34 [util.c:4079] Succesfully created ZMQ endpoint tcp://127.0.0.1:1234
23/Jun/2016 17:34:34 [util.c:3129] nProbe changed user to 'nobody'
23/Jun/2016 17:34:34 [nprobe.c:7848] nProbe started successfully

[root@servername username]# ntopng -i "tcp://127.0.0.1:1234" &
[9] 1767
[root@servername username]# 23/Jun/2016 17:35:35 [Ntop.cpp:933] Setting local networks to 127.0.0.0/8
23/Jun/2016 17:35:35 [Redis.cpp:106] Successfully connected to redis 127.0.0.1:6379@0
23/Jun/2016 17:35:35 [NtopPro.cpp:116] [LICENSE] Read license from Redis []
23/Jun/2016 17:35:35 [NtopPro.cpp:158] ERROR: [LICENSE] Invalid or missing ntopng License [Empty license file]
23/Jun/2016 17:35:35 [NtopPro.cpp:171] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
23/Jun/2016 17:35:35 [NtopPro.cpp:173] WARNING: [LICENSE] before returning to community mode
23/Jun/2016 17:35:35 [NtopPro.cpp:174] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
23/Jun/2016 17:35:35 [NtopPro.cpp:175] WARNING: [LICENSE] or run ntopng in community mode starting
23/Jun/2016 17:35:35 [NtopPro.cpp:176] WARNING: [LICENSE] ntopng --community
23/Jun/2016 17:35:35 [Ntop.cpp:1152] Registered interface tcp://127.0.0.1:1234 [id: 9]
23/Jun/2016 17:35:35 [Ntop.cpp:1165] Registered interface view tcp://127.0.0.1:1234 [id: 9]
23/Jun/2016 17:35:35 [Utils.cpp:304] User changed to nobody
23/Jun/2016 17:35:35 [main.cpp:240] PID stored in file /var/tmp/ntopng.pid
23/Jun/2016 17:35:35 [HTTPserver.cpp:465] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
23/Jun/2016 17:35:35 [HTTPserver.cpp:508] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
23/Jun/2016 17:35:35 [HTTPserver.cpp:511] HTTP server listening on port 3000
23/Jun/2016 17:35:35 [main.cpp:290] Working directory: /var/tmp/ntopng
23/Jun/2016 17:35:35 [main.cpp:292] Scripts/HTML pages directory: /usr/share/ntopng
23/Jun/2016 17:35:35 [Ntop.cpp:260] Welcome to ntopng x86_64 v.2.2.160623 - (C) 1998-15 ntop.org
23/Jun/2016 17:35:35 [Ntop.cpp:265] Built on CentOS Linux release 7.2.1511 (Core)
23/Jun/2016 17:35:35 [PeriodicActivities.cpp:53] Started periodic activities loop...
23/Jun/2016 17:35:35 [RuntimePrefs.cpp:32] Dumping alerts into syslog
23/Jun/2016 17:35:35 [NtopPro.cpp:233] [LICENSE] ntopng systemId: 68B8BF9E76056206
23/Jun/2016 17:35:35 [NtopPro.cpp:238] [LICENSE] ntopng is starting in demo mode
23/Jun/2016 17:35:35 [NetworkInterface.cpp:1427] Started packet polling on interface tcp://127.0.0.1:1234 [id: 9]...
23/Jun/2016 17:35:35 [CollectorInterface.cpp:94] Collecting flows on tcp://127.0.0.1:1234

23/Jun/2016 17:35:45 [ParserInterface.cpp:232] WARNING: [8192]
23/Jun/2016 17:35:45 [ParserInterface.cpp:230] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
23/Jun/2016 17:35:45 [ParserInterface.cpp:232] WARNING: [8192]
23/Jun/2016 17:35:45 [ParserInterface.cpp:230] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
23/Jun/2016 17:35:45 [ParserInterface.cpp:232] WARNING: [8192]
23/Jun/2016 17:35:45 [ParserInterface.cpp:230] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
23/Jun/2016 17:35:45 [ParserInterface.cpp:232] WARNING: [8192]
23/Jun/2016 17:35:45 [ParserInterface.cpp:230] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
23/Jun/2016 17:35:45 [ParserInterface.cpp:232] WARNING: [8192]
23/Jun/2016 17:35:45 [ParserInterface.cpp:230] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
23/Jun/2016 17:35:45 [ParserInterface.cpp:232] WARNING: [8192]
23/Jun/2016 17:35:45 [ParserInterface.cpp:230] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?
23/Jun/2016 17:35:45 [ParserInterface.cpp:232] WARNING: [8192]
23/Jun/2016 17:35:45 [ParserInterface.cpp:230] WARNING: Invalid message received: your nProbe sender is outdated or invalid JSON?

etc. etc. etc.

**Comment by simonemainardi** [comment]
Please, update ntopng to the latest dev version (2.3.xx) and it will work. The dev version is fairly stable as we are already working on moving it to the stable release.
