### ISSUE TITLE
nEdge bridge does not come up after reboot

### ISSUE THREAD

**Issue by sciolto** [ntop/ntopng#6230]
**Environment**:
* OS name: Ubuntu
* OS version:  18.04
* Architecture: amd64
* ntopng version/revision: [e.g. 5.0.220111]

**What happened**:
nEdge was found offline after reboot, because the bridge br0 does not come up after reboot, only executing `netplan apply`  5-10 minutes after reboot restores the connectivity 

**What did you expect to happen?**
nEdge would be in online mode after reboot

**How did you reproduce it?**
reboot

**Debug Information**:

```
Jan 18 10:35:42 nbox systemd-networkd[3793]: br0: netdev exists, using existing without changing its parameters
Jan 18 10:35:42 nbox systemd-networkd[3793]: br0: IPv6 successfully enabled
Jan 18 10:35:42 nbox systemd-networkd[3793]: lo: Link is not managed by us
Jan 18 10:35:42 nbox systemd-networkd[3793]: eno2: Link is not managed by us
Jan 18 10:35:42 nbox systemd-networkd[3793]: eno1: Link is not managed by us
Jan 18 10:35:42 nbox systemd-networkd[3793]: enp1s0f2: Link is not managed by us
Jan 18 10:35:42 nbox systemd-networkd[3793]: enp1s0f3: Link is not managed by us
Jan 18 10:35:42 nbox systemd-networkd[3793]: enp1s0f1: Link is not managed by us
Jan 18 10:35:42 nbox systemd-networkd[3793]: enp1s0f0: Link is not managed by us
Jan 18 10:35:43 nbox systemd-networkd[3793]: eno1: Link DOWN
Jan 18 10:35:43 nbox systemd-networkd[3793]: eno1: Lost carrier
Jan 18 10:35:43 nbox systemd-networkd[3793]: enp1s0f0: Link DOWN
Jan 18 10:35:43 nbox systemd-networkd[3793]: enp1s0f0: Lost carrier
Jan 18 10:35:43 nbox systemd-networkd[3793]: br0: Configured
Jan 18 10:35:43 nbox systemd-networkd[3793]: eno1: Link UP
Jan 18 10:35:43 nbox systemd-networkd[3793]: enp1s0f0: Link UP
Jan 18 10:35:43 nbox systemd-networkd[3793]: enp1s0f0: Gained carrier
Jan 18 10:35:43 nbox systemd-networkd[3793]: enp1s0f0: Configured
Jan 18 10:35:43 nbox systemd-networkd[3793]: enp1s0f0: Lost carrier
Jan 18 10:35:43 nbox systemd-networkd[3793]: br0: Lost carrier
Jan 18 10:35:45 nbox systemd-networkd[3793]: enp1s0f0: Gained carrier
Jan 18 10:35:45 nbox systemd-networkd[3793]: enp1s0f0: Configured
Jan 18 10:35:45 nbox systemd-networkd[3793]: br0: Gained carrier
Jan 18 10:35:45 nbox systemd-networkd[3793]: br0: Configured
Jan 18 10:35:46 nbox systemd-networkd[3793]: eno1: Gained carrier
Jan 18 10:35:46 nbox systemd-networkd[3793]: eno1: Configured
```

**Comment by sciolto** [comment]
As a workaround I configured a cronjob `@reboot` which calls the  following script:
```
#!/bin/bash
ip_to_ping=<GATEWAY TO PING>
i=0
while [ "$i" -ne 255 ]
do
        /bin/ping -c 1 $ip_to_ping >/dev/null 2>&1
        if [ "$?" = "0" ]; then
                #echo -n "internet is up "
                exit 0
        else
                #echo -n "down"
                sleep 5
                /usr/sbin/netplan apply > /dev/null
        fi
        i=$(( $i + 1))
done

```

**Comment by cardigliano** [comment]
@sciolto could you provide /etc/netplan/*.yaml ? 
This is strange as once the netplan configuration has been generated by nedge, either this is valid or not, and it should be applied after reboot. Could you check that netplan is properly configured as service in networkd?

**Comment by sciolto** [comment]
Hi @cardigliano, here's the only file under `/etc/netplan/`:

```
network:
  version: 2
  ethernets:
    eno1:
      addresses: []
    enp1s0f0:
      addresses: []
  bridges:
    br0:
      addresses: [192.168.58.35/24]
      gateway4: 192.168.58.254
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
      interfaces: [eno1, enp1s0f0]
      parameters:
        stp: false
        forward-delay: 0
  bridges:
    br0:
      addresses: [192.168.160.10/24]
```
And here's a list of all systemd units, does this help ?
[systemctl.txt](https://github.com/ntop/ntopng/files/7959099/systemctl.txt)

**Comment by cardigliano** [comment]
@sciolto it seems the yaml configuration is not correct (please note 2 bridges entries), this has been addressed a few days ago, there are 2 options:
1. let nedge generate the configuration again, from the system page
2. manually fixing the configuration as below:

bridges:
    br0:
      addresses: [192.168.58.35/24,192.168.160.10/24]
      gateway4: 192.168.58.254
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
      interfaces: [eno1, enp1s0f0]
      parameters:
        stp: false
        forward-delay: 0

**Comment by sciolto** [comment]
Thanks @cardigliano we will test the new configuration file and let you know.

**Comment by sciolto** [comment]
Hi @cardigliano updating to the latest version fixed the issue, thanks !
