### ISSUE TITLE
Cleanup plugins code

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6231]
After the plugins have been removed there is some leftover to remove
- /var/lib.ntopng/pluginX is no longer necessary
- Preferences -> Plugins should be reworked
- scripts/lua/modules/plugins_utils.lua should disappear

**Comment by MatteoBiscosi** [comment]
Fixed with f1e8091928e7384f9a09c305edb365edff35df7c 57a85de50e574198050295e7880778d2c52b880c f7db2e1974ca9aa29a2f94c9c013fe3f745c7700

**Comment by lucaderi** [comment]
Verified as fixed
