### ISSUE TITLE
Alerts: Missing number of Records as with Flows

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6234]
![Screen Shot 2022-01-24 at 16 07 43](https://user-images.githubusercontent.com/4493366/150808889-3da16ac8-f19d-4c1e-bf8f-b7128de3a982.png)

**Comment by cardigliano** [comment]
Fixed for sqlite in e9d79d9e1a12d63bb4fc02546a1e296e3b08cc33 (CH is working for me)

**Comment by lucaderi** [comment]
Verified as fixed
