### ISSUE TITLE
Edit Host Pool does not work properly

### ISSUE THREAD

**Issue by mzac** [ntop/ntopng#6235]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04
* Architecture: AMD64
* ntopng version/revision: 5.1.220124

**What happened**:
When trying to edit a host pool name from the list of host pool pages using the edit button under actions, the Name of the host pool is empty and cannot be changed.  However if you navigate into the host pool and then click the pencil edit next to the name it works.

https://ntop/lua/admin/manage_pools.lua

![image](https://user-images.githubusercontent.com/10270879/150818123-5e01f0bf-4747-4bf1-92f8-8717780f2c1a.png)

**What did you expect to happen?**
You should be able to edit the host pool name from this page

**How did you reproduce it?**
Click on edit under the actions dropdown

**Comment by MatteoBiscosi** [comment]
Thanks a lot for your report @mzac. The issue should now be fixed, please wait some hours, update and let me know.

**Comment by mzac** [comment]
Wow thanks for the quick fix!  I'll let you know when I pull the next release.

**Comment by mzac** [comment]
@MatteoBiscosi  Looks good!
