### ISSUE TITLE
Redis SNMP VPN Data flush

### ISSUE THREAD

**Issue by Paolo5466** [ntop/ntopng#6236]
Hi
In the past I activated the SNMP data collecting from the VPN appliance, resulting in the user showing up instead of the IP addresses in the flows page.
I don't use this snmp feature anymore, but I still see cached (stale) users in the flows.

Is there a way to flush the redis entries for the vpn users and restore the standard visualization of the IP addresses?

Thanks in advance

Have a nice day

**Comment by lucaderi** [comment]
Can you please report the output of
redis-cli keys "ntopng.cache.host_labels.*"

**Comment by Paolo5466** [comment]
Sure

  1) "ntopng.cache.host_labels.192.168.199.24"
  2) "ntopng.cache.host_labels.192.168.199.12"
  3) "ntopng.cache.host_labels.192.168.199.111"
  4) "ntopng.cache.host_labels.10.15.68.155"
  5) "ntopng.cache.host_labels.192.168.199.16"
  6) "ntopng.cache.host_labels.192.168.199.137"
  7) "ntopng.cache.host_labels.192.168.199.17"
  8) "ntopng.cache.host_labels.192.168.199.138"
  9) "ntopng.cache.host_labels.192.168.199.100"
 10) "ntopng.cache.host_labels.192.168.199.102"
 11) "ntopng.cache.host_labels.192.168.199.29"
 12) "ntopng.cache.host_labels.192.168.199.57"
 13) "ntopng.cache.host_labels.192.168.199.134"
 14) "ntopng.cache.host_labels.192.168.199.1"
 15) "ntopng.cache.host_labels.192.168.199.147"
 16) "ntopng.cache.host_labels.172.20.0.49"
 17) "ntopng.cache.host_labels.192.168.199.26"
 18) "ntopng.cache.host_labels.192.168.199.133"
 19) "ntopng.cache.host_labels.192.168.199.41"
 20) "ntopng.cache.host_labels.192.168.199.49"
 21) "ntopng.cache.host_labels.192.168.199.121"
 22) "ntopng.cache.host_labels.192.168.199.136"
 23) "ntopng.cache.host_labels.192.168.199.54"
 24) "ntopng.cache.host_labels.192.168.199.95"
 25) "ntopng.cache.host_labels.10.15.68.157"
 26) "ntopng.cache.host_labels.192.168.199.21"
 27) "ntopng.cache.host_labels.192.168.199.10"
 28) "ntopng.cache.host_labels.192.168.199.96"
 29) "ntopng.cache.host_labels.192.168.199.97"
 30) "ntopng.cache.host_labels.192.168.199.90"
 31) "ntopng.cache.host_labels.10.15.68.154"
 32) "ntopng.cache.host_labels.10.15.68.153"
 33) "ntopng.cache.host_labels.10.15.68.152"
 34) "ntopng.cache.host_labels.192.168.199.145"
 35) "ntopng.cache.host_labels.192.168.199.14"
 36) "ntopng.cache.host_labels.192.168.199.127"
 37) "ntopng.cache.host_labels.192.168.199.50"
 38) "ntopng.cache.host_labels.192.168.199.115"
 39) "ntopng.cache.host_labels.192.168.199.104"
 40) "ntopng.cache.host_labels.192.168.199.31"
 41) "ntopng.cache.host_labels.192.168.199.32"
 42) "ntopng.cache.host_labels.192.168.199.22"
 43) "ntopng.cache.host_labels.192.168.199.148"
 44) "ntopng.cache.host_labels.192.168.199.122"
 45) "ntopng.cache.host_labels.192.168.199.135"
 46) "ntopng.cache.host_labels.192.168.199.139"
 47) "ntopng.cache.host_labels.192.168.199.110"
 48) "ntopng.cache.host_labels.192.168.199.43"
 49) "ntopng.cache.host_labels.192.168.199.55"
 50) "ntopng.cache.host_labels.192.168.199.91"
 51) "ntopng.cache.host_labels.192.168.199.58"
 52) "ntopng.cache.host_labels.192.168.199.25"
 53) "ntopng.cache.host_labels.192.168.199.30"
 54) "ntopng.cache.host_labels.192.168.199.33"
 55) "ntopng.cache.host_labels.192.168.199.11"
 56) "ntopng.cache.host_labels.0.0.0.0"
 57) "ntopng.cache.host_labels.192.168.199.98"
 58) "ntopng.cache.host_labels.192.168.199.51"
 59) "ntopng.cache.host_labels.192.168.199.23"
 60) "ntopng.cache.host_labels.192.168.199.37"
 61) "ntopng.cache.host_labels.192.168.199.132"
 62) "ntopng.cache.host_labels.192.168.199.123"
 63) "ntopng.cache.host_labels.192.168.199.105"
 64) "ntopng.cache.host_labels.192.168.199.150"
 65) "ntopng.cache.host_labels.192.168.199.129"
 66) "ntopng.cache.host_labels.192.168.199.109"
 67) "ntopng.cache.host_labels.192.168.199.13"
 68) "ntopng.cache.host_labels.192.168.199.101"
 69) "ntopng.cache.host_labels.192.168.199.119"
 70) "ntopng.cache.host_labels.192.168.199.15"
 71) "ntopng.cache.host_labels.192.168.199.28"
 72) "ntopng.cache.host_labels.192.168.106.254"
 73) "ntopng.cache.host_labels.192.168.199.92"
 74) "ntopng.cache.host_labels.192.168.199.47"
 75) "ntopng.cache.host_labels.192.168.199.94"
 76) "ntopng.cache.host_labels.192.168.199.52"
 77) "ntopng.cache.host_labels.192.168.199.108"
 78) "ntopng.cache.host_labels.192.168.199.38"
 79) "ntopng.cache.host_labels.192.168.199.18"
 80) "ntopng.cache.host_labels.192.168.199.19"
 81) "ntopng.cache.host_labels.192.168.199.27"
 82) "ntopng.cache.host_labels.192.168.199.116"
 83) "ntopng.cache.host_labels.192.168.199.42"
 84) "ntopng.cache.host_labels.192.168.199.120"
 85) "ntopng.cache.host_labels.192.168.199.39"
 86) "ntopng.cache.host_labels.192.168.199.53"
 87) "ntopng.cache.host_labels.192.168.199.99"
 88) "ntopng.cache.host_labels.192.168.199.34"
 89) "ntopng.cache.host_labels.192.168.199.141"
 90) "ntopng.cache.host_labels.192.168.199.40"
 91) "ntopng.cache.host_labels.192.168.199.131"
 92) "ntopng.cache.host_labels.192.168.199.36"
 93) "ntopng.cache.host_labels.192.168.199.46"
 94) "ntopng.cache.host_labels.192.168.199.114"
 95) "ntopng.cache.host_labels.192.168.199.128"
 96) "ntopng.cache.host_labels.192.168.199.113"
 97) "ntopng.cache.host_labels.192.168.199.125"
 98) "ntopng.cache.host_labels.192.168.199.44"
 99) "ntopng.cache.host_labels.192.168.199.130"
100) "ntopng.cache.host_labels.192.168.199.56"
101) "ntopng.cache.host_labels.192.168.199.143"
102) "ntopng.cache.host_labels.192.168.199.151"
103) "ntopng.cache.host_labels.192.168.199.117"
104) "ntopng.cache.host_labels.192.168.199.112"
105) "ntopng.cache.host_labels.192.168.199.144"
106) "ntopng.cache.host_labels.192.168.199.126"
107) "ntopng.cache.host_labels.192.168.199.118"
108) "ntopng.cache.host_labels.192.168.199.20"
109) "ntopng.cache.host_labels.192.168.199.142"
110) "ntopng.cache.host_labels.192.168.199.103"
111) "ntopng.cache.host_labels.192.168.199.146"
112) "ntopng.cache.host_labels.192.168.199.45"
113) "ntopng.cache.host_labels.192.168.199.107"
114) "ntopng.cache.host_labels.192.168.199.106"
115) "ntopng.cache.host_labels.192.168.199.140"
116) "ntopng.cache.host_labels.192.168.199.93"
117) "ntopng.cache.host_labels.192.168.199.48"
118) "ntopng.cache.host_labels.192.168.199.149"
119) "ntopng.cache.host_labels.192.168.199.35"
120) "ntopng.cache.host_labels.192.168.199.124"

**Comment by lucaderi** [comment]
In order to flush them do
- redis-cli --scan --pattern ntopng.cache.host_labels* | xargs redis-cli del
- sudo service ntopng restart
