### ISSUE TITLE
"Flow Exporter" Filter in Historical Flow Explorer does not work

### ISSUE THREAD

**Issue by Niklasr69** [ntop/ntopng#6237]
**Environment**:
* OS name: Rocky Linux
* OS version: 8.5
* Architecture: 
* ntopng version/revision: Enterprise L v.5.1.220125

**What happened**:
Filtering "Flow Exporter" has no affect in Historical Flow Explorer

**What did you expect to happen?**
When using "Flow Exporter" as filter only flows from this exporter should be display

**How did you reproduce it?**

Using "flow Exporter" filter

**Debug Information**:

**Comment by cardigliano** [comment]
@Niklasr69 what do you mean by using Flow Exporter as filter? Could you provide an example? (a screenshot would help). Thank you.

**Comment by Niklasr69** [comment]
Hi,
Nothing is filtered out 
Flows from other exporters is still in the flow session.
If you need more detailed view I can send a screen shoot via mail direct to you.
See below:
![image](https://user-images.githubusercontent.com/26242302/150989475-f4b34ca1-71b8-470e-9753-b2d2dcfcb86f.png)

**Comment by cardigliano** [comment]
Fixed, a new packages will be available later today (pro 7899b85c73a24fb441edd0f66bdb5dc3f01e2499)

**Comment by Niklasr69** [comment]
Tried with "ntopng Enterprise L v.5.1.220127", no change.
Maybe I need to wait for a newer?

**Comment by cardigliano** [comment]
Please update again to 5.1.220128 or later to make sure it includes the fix. Otherwise please click on SQL at the bottom of the page to copy the query and paste it here. Thank you.

**Comment by Niklasr69** [comment]
The filter function works fine now.

**Comment by lucaderi** [comment]
Verified as fixed
