### ISSUE TITLE
Historical flow explorer - number of packets doubled

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6238]
**Environment**:
* OS name:  Ubuntu 
* OS version: 20.04.3 LTS
* Architecture:  Intel 64bit
* ntopng version/revision: ntopng Enterprise L v.5.1.220125

**What happened**:
Historical flow explorer is showing double the number of packets compared to the pcap download. 
![image](https://user-images.githubusercontent.com/38549755/151135775-770df199-e6a1-47dc-b859-1cd23da6f13b.png)
[](url)

Maybe not all packets are in the pcap? (number of bytes does also not match)

Thanks

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by martinscheu** [comment]
[1643186432-1643186463.pcap.zip](https://github.com/ntop/ntopng/files/7940396/1643186432-1643186463.pcap.zip)

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu , no you are right, packets are doubled, i can reproduce with the pcap, I'm working on it
