### ISSUE TITLE
provide tar.gz packages

### ISSUE THREAD

**Issue by deathtrip** [ntop/ntopng#624]
right now http://packages.ntop.org doesn't have any source packages, and the sourceforge repo one is outdated, so non deb/rpm distros are left out.
why aren't there any releases here on github anyway?

**Comment by lucaderi** [comment]
![image](https://cloud.githubusercontent.com/assets/4493366/16382251/673e7aa4-3c80-11e6-98bb-dd5e89ad0f66.png)
