### ISSUE TITLE
Implement per Recipient Alert Retention

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6240]
Sometimes the same alert is repeated various times. Example if host X has an expired certificate, such flow alert is emitted for all flows. This is good for storage in the database but it is not good when the alert is delivered many times to the same recipient.

This is to request the implementation of a retention policy (e.g. 1 hour) that prevents the same alert to be delivered to the same recipient more than 1 during the retention time

**Comment by MatteoBiscosi** [comment]
Already Implemented, the recipients config needs to be changed in order to achive that and enable the Silence Duplicated Alerts:
![image](https://github.com/ntop/ntopng/assets/49585191/fdf5def4-f4e2-4fcc-935d-94f247fd1e53)
