### ISSUE TITLE
lua/rest/v2/get/alert/type/counters.lua returns "attempt to index a nil value"

### ISSUE THREAD

**Issue by TimotheusBachinger** [ntop/ntopng#6241]
**Environment**:
* OS name: Ubuntu 16.04.7 LTS
* ntopng version/revision: v.5.1.220126 rev. 16575

**What happened**:
When calling lua/rest/v2/get/alert/type/counters.lua?ifid=2, we see:
Internal server error
attempt to index a nil value

**What did you expect to happen?**
Retrieving the counters under this ifid

**How did you reproduce it?**
By calling the REST endpoint

**Comment by MatteoBiscosi** [comment]
Hi @TimotheusBachinger it seems that you miss some argument. In my case by calling `curl -v -u admin:admin1 "http://localhost:3000/lua/rest/v2/get/alert/type/counters.lua?ifid=8"` I get all the right data

**Comment by TimotheusBachinger** [comment]
Hi Matteo,

we definitely had an ifid as query parameter in the URL. I saw it at a customer's installation, so at the moment I cannot get more information about that. But if it is no obvious error on your side, I think i need to dig deeper.

**Comment by MatteoBiscosi** [comment]
Hi @TimotheusBachinger maybe wrong ifid, i get that error if I try to get info from an interface not existent

**Comment by MatteoBiscosi** [comment]
Hi @TimotheusBachinger I added a patch to control that a valid interface is given, if not the rest is going to return the invalid interface rsp.
`curl -v -u admin:admin1 "http://192.168.2.225:3000/lua/rest/v2/get/alert/type/counters.lua?ifid=1"`
`{"rc_str_hr":"Invalid interface","rc_str":"INVALID_INTERFACE","rc":-2,"rsp":[]}`
Please, wait for the next dev build and update

**Comment by TimotheusBachinger** [comment]
Ok thanks - will try that out on customer's side.
