### ISSUE TITLE
Need A Help- NTOPNG vs PFSENSE

### ISSUE THREAD

**Issue by AnhTuanNguyenn** [ntop/ntopng#6242]
pfsense 2.5
ntopng 5.1

hello, 
i posted here because i sent much mail to team support but i didn't receive their return, 

https://github.com/ntop/ntopng/issues/6220

what happen when i use command: service ntopng start - and i go to <IP>:3000 i have a problem as tell me delete cockies 

but i go with command : ntopng -F i go to web too and that work ?

thank you

**Comment by lucaderi** [comment]
I have told you what to do in #6220: did you do it? If so show me all the steps as I cannot reproduce your issue after having done what instructed

**Comment by AnhTuanNguyenn** [comment]
Hello Lucas.

I have do as you told. And problem aren’t resolved.

I got error as ERR_TOO_MANY_REDIRECT same
I don’t know why.
But i start ntop without starting service ntopng by :’ ntopng -F’ that work
!

Do you have another solution?


Le jeu. 27 janv. 2022 à 08:55, Luca Deri ***@***.***> a
écrit :

**Comment by lucaderi** [comment]
-F is used to dump flows so it has nothing to do with this problem.

If this is the case the ntopng.conf file contains invalid values that you need to remove

**Comment by AnhTuanNguyenn** [comment]
i think as you, but i was started with ntopng.conf by default, you can see
picture bellow
[image: image.png]


Vào Th 5, 27 thg 1, 2022 vào lúc 09:50 Luca Deri ***@***.***>
đã viết:

**Comment by AnhTuanNguyenn** [comment]
![Capture 1](https://user-images.githubusercontent.com/24913199/151325439-92c375a7-1b6b-4e9d-8e8d-c0e56d2e37eb.PNG)

**Comment by lucaderi** [comment]
this is a part of it. Just put all you need and restart ntopng *making sure ntopng reads this file and not a different one*

**Comment by AnhTuanNguyenn** [comment]
i check in netstat and i see 
tcp4       0      0 XX.XX.XXxx.3000     82-64-135-61.sub.62920 TIME_WAIT
tcp4       0      0 xx.xx.xx.XX.3000     82-64-135-61.sub.35890 TIME_WAIT
p4       0      0 xx.xx.xx.xx.3000     82-64-135-61.sub.37027 TIME_WAIT
tcp4       0      0 xx.xx.xx.XX.3000     82-64-135-61.sub.1984  TIME_WAIT
tcp4       0      0 xx.Xx.xx.xx.6161     fra02s18-in-f4.1.443   TIME_WAIT

do you have any ideal for this ? how can i can trace, i think problem is this

**Comment by AnhTuanNguyenn** [comment]
and in the log you can see error 
`27/Jan/2022 11:05:49 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/housekeeping.lua][...local/share/ntopng/scripts/lua/modules/plu
gins_utils.lua:668: attempt to call a nil value (global 'deleteCachePattern')]
27/Jan/2022 11:05:50 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/housekeeping.lua][...local/share/ntopng/scripts/lua/modules/plu
gins_utils.lua:668: attempt to call a nil value (global 'deleteCachePattern')]
27/Jan/2022 11:05:56 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/housekeeping.lua][...local/share/ntopng/scripts/lua/modules/plu
gins_utils.lua:668: attempt to call a nil value (global 'deleteCachePattern')]
27/Jan/2022 11:10:00 [LuaEngine.cpp:562] WARNING: Script failure [/usr/local/share/ntopng/pro/scripts/callbacks/5minute/system/snmp_polling.lua][...ng/pro/scripts/callbacks/5minute/syste
m/snmp_polling.lua:1: unexpected symbol near '<\135>']
27/Jan/2022 11:10:00 [LuaEngine.cpp:562] WARNING: Script failure [/usr/local/share/ntopng/pro/scripts/callbacks/5minute/interface/top_sites.lua][...ng/pro/scripts/callbacks/5minute/inter
face/top_sites.lua:1: unexpected symbol near '<\135>']
27/Jan/2022 11:10:00 [LuaEngine.cpp:562] WARNING: Script failure [/usr/local/share/ntopng/pro/scripts/callbacks/5minute/interface/top_sites.lua][...ng/pro/scripts/callbacks/5minute/inter
face/top_sites.lua:1: unexpected symbol near '<\135>']
27/Jan/2022 11:10:00 [LuaEngine.cpp:562] WARNING: Script failure [/usr/local/share/ntopng/pro/scripts/callbacks/5minute/interface/top_sites.lua][...ng/pro/scripts/callbacks/5minute/inter
face/top_sites.lua:1: unexpected symbol near '<\135>']
27/Jan/2022 11:10:00 [LuaEngine.cpp:562] WARNING: Script failure [/usr/local/share/ntopng/pro/scripts/callbacks/5minute/interface/top_sites.lua][...ng/pro/scripts/callbacks/5minute/inter
face/top_sites.lua:1: unexpected symbol near '<\135>']
27/Jan/2022 11:10:00 [LuaEngine.cpp:562] WARNING: Script failure [/usr/local/share/ntopng/pro/scripts/callbacks/5minute/interface/top_sites.lua][...ng/pro/scripts/callbacks/5minute/inter
face/top_sites.lua:1: unexpected symbol near '<\135>']
27/Jan/2022 11:10:00 [ThreadedActivity.cpp:292] ERROR: Unable to load the Lua vm [__system__][vm: 5minute]
27/Jan/2022 11:10:00 [LuaEngine.cpp:562] WARNING: Script failure [/usr/local/share/ntopng/pro/scripts/callbacks/5minute/interface/top_sites.lua][...ng/pro/scripts/callbacks/5minute/inter
face/top_sites.lua:1: unexpected symbol near '<\135>']
27/Jan/2022 11:10:00 [ThreadedActivity.cpp:292] ERROR: Unable to load the Lua vm [lo0][vm: 5minute]
27/Jan/2022 11:10:00 [LuaEngine.cpp:562] WARNING: Script failure [/usr/local/share/ntopng/pro/scripts/callbacks/5minute/interface/top_sites.lua][...ng/pro/scripts/callbacks/5minute/inter
face/top_sites.lua:1: unexpected symbol near '<\135>']
27/Jan/2022 11:10:01 [ThreadedActivity.cpp:292] ERROR: Unable to load the Lua vm [vmx1][vm: 5minute]
27/Jan/2022 11:10:01 [LuaEngine.cpp:562] WARNING: Script failure [/usr/local/share/ntopng/pro/scripts/callbacks/5minute/interface/top_sites.lua][...ng/pro/scripts/callbacks/5minute/inter
face/top_sites.lua:1: unexpected symbol near '<\135>']
27/Jan/2022 11:10:01 [ThreadedActivity.cpp:292] ERROR: Unable to load the Lua vm [vmx2][vm: 5minute]
27/Jan/2022 11:10:01 [ThreadedActivity.cpp:292] ERROR: Unable to load the Lua vm [ovpns1][vm: 5minute]
27/Jan/2022 11:10:01 [ThreadedActivity.cpp:292] ERROR: Unable to load the Lua vm [vmx3][vm: 5minute]
27/Jan/2022 11:10:01 [ThreadedActivity.cpp:292] ERROR: Unable to load the Lua vm [vmx0][vm: 5minute]
27/Jan/2022 11:10:01 [ThreadedActivity.cpp:292] ERROR: Unable to load the Lua vm [enc0][vm: 5minute]
27/Jan/2022 11:10:01 [ThreadedActivity.cpp:292] ERROR: Unable to load the Lua vm [ovpns2][vm: 5minute]`

**Comment by lucaderi** [comment]
You do not have a license so add

--community=

in nttopng.conf

**Comment by AnhTuanNguyenn** [comment]
i added --community = in file ntopng.conf that not resolved pb in the picture 
`
27/Jan/2022 15:10:17 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/minute-delayed/interface/local_network_checks.lua][.../ntopng/scripts/lua/mod
les/notifications/recipients.lua:649: attempt to index a nil value (local 'alert_store_db_recipient')]
27/Jan/2022 15:10:22 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/minute-delayed/interface/local_network_checks.lua][.../ntopng/scripts/lua/mod
les/notifications/recipients.lua:649: attempt to index a nil value (local 'alert_store_db_recipient')]
27/Jan/2022 15:11:05 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/minute-delayed/interface/local_network_checks.lua][.../ntopng/scripts/lua/mod
les/notifications/recipients.lua:649: attempt to index a nil value (local 'alert_store_db_recipient')]
rface/top_sites.lua:1: unexpected symbol near '<\135>']
27/Jan/2022 15:10:01 [ThreadedActivity.cpp:292] ERROR: Unable to load the Lua vm [ovpns1][vm: 5minute]
27/Jan/2022 15:10:01 [LuaEngine.cpp:562] WARNING: Script failure [/usr/local/share/ntopng/pro/scripts/callbacks/5minute/interface/top_sites.lua][...ng/pro/scripts/callbacks/5minute/inte
rface/top_sites.lua:1: unexpected symbol near '<\135>']
`

![Inkederr_too_many_redirects 1_LI](https://user-images.githubusercontent.com/24913199/151375295-4ac1efb6-a4b2-4a00-95ee-045921a1a9a4.jpg)

**Comment by AnhTuanNguyenn** [comment]
UPDATE !!!!
Applied licensed but always **err_too_many_redirect**
ps: in the log ntop 
`[LuaEngine.cpp:595]WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/minute/system/drop_host_pool.lua][.../ntopng/scripts/lua/modules/notification
s/recipients.lua:649: attempt to index a nil value (local 'alert_store_db_recipient')]`

**Comment by lucaderi** [comment]
What ntopng version are you running?

**Comment by lucaderi** [comment]
This error
'alert_store_db_recipient')] 27/Jan/2022 15:11:05 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/minute-delayed/interface/local_network_checks.lua][.../ntopng/scripts/lua/mod les/notifications/recipients.lua:649: attempt to index a nil value (local 'alert_store_db_recipient')] rface/top_sites.lua:1: unexpected symbol near '<\135>'
means that --community was not used

**Comment by AnhTuanNguyenn** [comment]
Pfsense 2.5.2
Ntopng 5.1

I removed ntop and reinstall. That’s changed anything.

Le jeu. 27 janv. 2022 à 18:36, Luca Deri ***@***.***> a
écrit :

**Comment by AnhTuanNguyenn** [comment]
I was applying license test 7days to ntopng. So i don’t think this resolved
pb

Le jeu. 27 janv. 2022 à 18:37, Luca Deri ***@***.***> a
écrit :

**Comment by giorgiozoppi** [comment]
The discussion is confused. Please state all steps in a list to reproduce this issue. 
1. Which version do you use it?
2.  Which OS are you using?
3. Please set the list of actions you did to show the problem:
     1. I have done action 1.
     2. I have done action 2.

Like a recipe. In this way we might be able to put the effort to help you.

**Comment by AnhTuanNguyenn** [comment]
I will try to explain it best to you.  currently i am using pfsense v.2.5.2
and i want to install ntop on it.

https://www.ntop.org/guides/ntopng/third_party_integrations/pfsense.html
This is the link I installed under it.

 i deleted the old version of ntop, even removed all the related folders,
everything was fine until i started ntopng with : “ ntopng service start”.
I go to <ip>:3000 and I get err_too_many_redirect error as I said.  You can
see in picture

note ntopng i added 7 days licenses and his version 5.1.xxx

Le jeu. 27 janv. 2022 à 21:19, Giorgio Zoppi ***@***.***> a
écrit :

**Comment by MatteoBiscosi** [comment]
Hi @AnhTuanNguyenn could you please check "ntopng service status" and let me know if there is some error in the console log?

**Comment by AnhTuanNguyenn** [comment]
> Hi @AnhTuanNguyenn could you please check "ntopng service status" and let me know if there is some error in the console log?
hi @MatteoBiscosi 
I'm currently debugging with your colleague, he has seen the problem and working on fixing it, I will update the information here

**Comment by MatteoBiscosi** [comment]
Verified as Fixed
