### ISSUE TITLE
Support for Modern C++ concurrency

### ISSUE THREAD

**Issue by giorgiozoppi** [ntop/ntopng#6243]
**What would you like to add or change?**:
Most of your concurrency in ntopng is still based wrapping pthread library. 

**Why do you and others need this?**:
While the code is excellent,
this code is not portable. Since C++11 we've in the standard, it would nice to have that support also.
This will lead to code reduction.

As reference about modern concurrency : https://github.com/giorgiozoppi/cppconcurrency
https://github.com/barcelona-c-c-users/meetup/blob/master/20170901/GiorgioZoppi_CPP11Concurrency.pdf

**Comment by giorgiozoppi** [comment]
This will lead to code reduction since the workpool will be no longer needed and also the windows compatibility layer for threads.

**Comment by lucaderi** [comment]
Not a priority
