### ISSUE TITLE
Introduce CMake build system.

### ISSUE THREAD

**Issue by giorgiozoppi** [ntop/ntopng#6245]
**What would you like to add or change?**:
The build system is deprecated. A more complete system might be based on CMake to autoadapt the code to different platform,

**Why do you and others need this?**:
CMake is defacto standard for C++ projects.

**Comment by giorgiozoppi** [comment]
I am just doing this. So moving from the old autoconf to the new CMake build system for enable a better testing. The old way of building will remain until we'll decide to remove it. This is WIP in the branch moderncpp_ntop

**Comment by lucaderi** [comment]
Good idea but for the time being we stay with makefile that is integrated in our pipeline and that we know well, contrary to cmake
