### ISSUE TITLE
Missing nDPI HREF

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6248]
![Screen Shot 2022-01-27 at 10 47 48](https://user-images.githubusercontent.com/4493366/151334347-af84a031-2d7d-4503-b21c-86ef7df97756.png)
![Screen Shot 2022-01-27 at 10 20 54](https://user-images.githubusercontent.com/4493366/151334358-d76698f1-e484-4b2a-8109-9923ed8a4079.png)

Flow flow risks in flows, alerts and historical flow explorer there should be an icon pointing to this page https://www.ntop.org/guides/nDPI/flow_risks.html

This used to work (at least in flows) but it is now broken

**Comment by cardigliano** [comment]
Fixed in 5c3a838086d875e296bed519273df2c3ef15bf4f

**Comment by lucaderi** [comment]
Verified as fixed
