### ISSUE TITLE
Missing time formatter in flow alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6249]
![image](https://user-images.githubusercontent.com/4493366/151335102-603f7489-5407-4016-99b1-c52cca7cc4e1.png)

**Comment by MatteoBiscosi** [comment]
Formatted using the standard time formatter
![Screenshot from 2022-01-27 13-09-06](https://user-images.githubusercontent.com/49585191/151356141-2ad3dcbb-a7ed-4ca8-8243-12184baf795f.png)

**Comment by lucaderi** [comment]
Verified as fixed
