### ISSUE TITLE
Remove all warning while compiling on Ubuntu

### ISSUE THREAD

**Issue by giorgiozoppi** [ntop/ntopng#6255]
**What would you like to add or change?**:

Below warning should be checked. A better option may be std::copy since we're compiling in c++. 

In function ‘char* strncpy(char*, const char*, size_t)’,
    inlined from ‘static void Utils::readMac(char*, u_int8_t*)’ at src/Utils.cpp:2557:10:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:34: warning: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ output may be truncated copying 15 bytes from a string of length 31 [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘char* strncpy(char*, const char*, size_t)’,
    inlined from ‘static u_int32_t Utils::getMaxIfSpeed(const char*)’ at src/Utils.cpp:2734:10:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:34: warning: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ output may be truncated copying 15 bytes from a string of length 31 [-Wstringop-truncation]

**Why do you and others need this?**:

Warning are a synthom of not so clean code. Better check them and remove them.

**Comment by lucaderi** [comment]
Fixed
