### ISSUE TITLE
UI: when you click about there's wrong noising message.

### ISSUE THREAD

**Issue by giorgiozoppi** [ntop/ntopng#6256]
![image](https://user-images.githubusercontent.com/27227826/151444862-99d8e64f-ade6-41f0-b6bf-717bfc08c2af.png)

**Environment**:
* OS name:  Ubuntu
* OS version: 20
* Architecture:  amd64
* ntopng version/revision: trunk

**What happened**:

If you put about you've this.

**Comment by cardigliano** [comment]
Fixed in ea7676c40aa79b972b36e747a44ca7f4396c6185

**Comment by lucaderi** [comment]
Verified as fixed
