### ISSUE TITLE
Remove dependency on uthash.

### ISSUE THREAD

**Issue by giorgiozoppi** [ntop/ntopng#6257]
**What would you like to add or change?**:

attic/FrequentNumericItems.h uses uthash, this is bring on board a dependency that it's not needed, since as
hash table we've in modern c++ unordered_map.
This is the only place where it's used.

**Why do you and others need this?**:
This is might be part of the code cleanup. The code to be compiled needs too many dependencies. I detected this while 
i was doing the cmake port.

**Comment by cardigliano** [comment]
@giorgiozoppi please note that "attic" contains unused/old code

**Comment by giorgiozoppi** [comment]
Ok, @cardigliano. Thanks for the clarification. I exclude from my build system.
