### ISSUE TITLE
Ntopng export to elasticsearch netflow data show zero values for IN_BYTES, IN_PKTS, OUT_BYTES and OUT_PKTS

### ISSUE THREAD

**Issue by assegid14** [ntop/ntopng#6259]
I have configured NtopNg to export netflow data to Elasticsearch using the following command.
 **ntopng /i ntopng -i "tcp://127.0.0.1:5556" --dump-flows “es;flows;ntopng-%Y.%m.%d;http://localhost:9200/_bulk;”**

After a moment, the flows exported to Elasticsearch and also I able to view the flows through Kibana dashboard.
However, the values of IN_BYTES, IN_PKTS, OUT_BYTES and OUT_PKTS are zero.
What shall I do?
![Kibana interface](https://user-images.githubusercontent.com/82800059/151505296-73cf54c7-ea99-49f5-bbb1-582ebbaa76f8.JPG)

**Comment by MatteoBiscosi** [comment]
Hi @assegid14 please update to the latest version and let me know, in my tests i receive everything correctly (see below)
![Screenshot from 2022-01-31 11-41-20](https://user-images.githubusercontent.com/49585191/151779652-d92f507a-572e-4958-9035-2e8422714027.png)
(I'm running ntopng with `./ntopng -i tcp://127.0.0.1:5556 --dont-change-user -F "es;ntopng;ntopng-%Y.%m.%d;http://localhost:9200/_bulk;" -N "test" -m "192.168.2.0/24=test"`).
Which ntopng --version are you using?

**Comment by assegid14** [comment]
> 

Dear @MatteoBiscosi 

Thank you for the response.
I configured as you suggested. But, the result is the same. No values for those attributes.

FYI. My NtopNg is = 9.7.220106
             Windows based.

**Comment by MatteoBiscosi** [comment]
Hi @assegid14 please, firstly update to the latest ntopng version, then could you please check if in the message field, the data are correct? if not, please check the data from ntopng flows page, if you are able to see in bytes, out bytes and packets correctly

**Comment by assegid14** [comment]
@MatteoBiscosi I upgraded to the latest version of NtopNg to ntopng Enterprise L v.5.1.210907. 
but, the problem still exist.

**Comment by MatteoBiscosi** [comment]
Hi @assegid14 please update and let me know. Now the latest version is ntopng 5.3.
Then let me know nprobe configuration and if you are able to see the data instead in ntopng web gui

**Comment by assegid14** [comment]
Dear @MatteoBiscosi, 
Sorry for not updating the status in time. The issue were resolved after doing the following.

1.    Migrated from Windows to Linux
2.    Replaced Elasticsearch by Clickhouse DB.

Now, everything is working perfectly.

Thank you!

**Comment by MatteoBiscosi** [comment]
Glad to know!
