### ISSUE TITLE
ntop http access unknown protocol

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#626]
hi

I can see that access to the ntop webpage (http port 3000) is detected as unknown protocol instead of http
<img width="393" alt="ntop 3000 not as http" src="https://cloud.githubusercontent.com/assets/17108017/16404572/7fe4fb16-3d00-11e6-8f5c-dea93f98bf73.PNG">

ntopng 2.5.160627
ndpi 1.8.0-dev-457-ff6b193

nico

**Comment by simonemainardi** [comment]
you need to allow a minimum amount of traffic to go through the flow in order to be detected as http:

![image](https://cloud.githubusercontent.com/assets/3397663/16570154/7628150a-4240-11e6-86fe-47640b1d27d3.png)
