### ISSUE TITLE
Adding new hostpool breaks clickhouse connectivity

### ISSUE THREAD

**Issue by notyourcommy** [ntop/ntopng#6263]
Adding new hostpool breaks clickhouse connectivity and also hostpool was not created. 

**Environment**:
* OS name: Centos 8 (stream)
* OS version:  Centos 8 stream
* Architecture:  amd64
* ntopng version/revision: 5.1.220130

**What happened**:
With clickhouse as backend I'm trying to add hostpool and nothing happens (I click add and window is stuck/frozen)
Then, when I go to ua/pro/db_search.lua (dashboard > historical flow explorer) I see that there is no new records* (something is broken)
In ntop logs I see 

[MySQLDB.cpp:1007] ERROR: MySQL error: [Code: 47. DB::Exception: Missing columns: 'DST_HOST_POOL_ID' while processing query: 'SELECT PROTOCOL, L7_PROTO, L7_PROTO_MASTER, SCORE, PACKETS, TOTAL_BYTES, toInt32(FIRST_SEEN) AS FIRST_SEEN, toInt32(LAST_SEEN) AS LAST_SEEN, SRC_ASN, DST_ASN, L7_CATEGORY, STATUS, FLOW_RISK, SRC2DST_TCP_FLAGS, DST2SRC_TCP_FLAGS, CLIENT_NW_LATENCY_US, SERVER_NW_LATENCY_US, INFO, OBSERVATION_POINT_ID, IPv4NumToString(PROBE_IP) AS PROBE_IP_FORMATTED, SRC_NETWORK_ID, DST_NETWORK_ID, SRC_HOST_POOL_ID, DST_HOST_POOL_ID, FLOW_ID][47][SELECT PROTOCOL, L7_PROTO, L7_PROTO_MASTER, SCORE, PACKETS, TOTAL_BYTES, toInt32(FIRST_SEEN) FIRST_SEEN, toInt32(LAST_SEEN) LAST_SEEN, SRC_ASN, DST_ASN, L7_CATEGORY, STATUS, FLOW_RISK, SRC2DST_TCP_FLAGS, DST2SRC_TCP_FLAGS, CLIENT_NW_LATENCY_US, SERVER_NW_LATENCY_US, INFO, OBSERVATION_POINT_ID, IPv4NumToString(PROBE_IP) PROBE_IP_FORMATTED, SRC_NETWORK_ID, DST_NETWORK_ID, SRC_HOST_POOL_ID, DST_HOST_POOL_ID, FLOW_ID, VLAN_ID, IP_PROTOCOL_VERSION, IPv4NumToString(IPV4_SRC_ADDR) IPV4_SRC_ADDR_FORMATTED, IPv4NumToString(IPV4_DST_ADDR) IPV4_DST_ADDR_FORMATTED, IPv6NumToString(IPV6_SRC_ADDR) IPV6_SRC_ADDR_FORMATTED, IPv6NumToString(IPV6_DST_ADDR) IPV6_DST_ADDR_FORMATTED, IP_SRC_PORT, IP_DST_PORT, SRC_LABEL, DST_LABEL, CLIENT_LOCATION, SERVER_LOCATION, COMMUNITY_ID, (LAST_SEEN - FIRST_SEEN) as TIME_DELTA, (TOTAL_BYTES / (TIME_DELTA + 1)) * 8 as THROUGHPUT FROM flows WHERE (INTERFACE_ID=4) AND (FIRST_SEEN >= 1643534976) AND (LAST_SEEN <= 1643536776)  ORDER BY FIRST_SEEN desc LIMIT 10 ]

=30/Jan/2022 12:59:36 [MySQLDB.cpp:1007] ERROR: MySQL error: [Code: 47. DB::Exception: Missing columns: 'DST_HOST_POOL_ID' while processing query: 'SELECT PROTOCOL, L7_PROTO, L7_PROTO_MASTER, SCORE, PACKETS, TOTAL_BYTES, toInt32(FIRST_SEEN) AS FIRST_SEEN, toInt32(LAST_SEEN) AS LAST_SEEN, SRC_ASN, DST_ASN, L7_CATEGORY, STATUS, FLOW_RISK, SRC2DST_TCP_FLAGS, DST2SRC_TCP_FLAGS, CLIENT_NW_LATENCY_US, SERVER_NW_LATENCY_US, INFO, OBSERVATION_POINT_ID, IPv4NumToString(PROBE_IP) AS PROBE_IP_FORMATTED, SRC_NETWORK_ID, DST_NETWORK_ID, SRC_HOST_POOL_ID, DST_HOST_POOL_ID, FLOW_ID][47][SELECT PROTOCOL, L7_PROTO, L7_PROTO_MASTER, SCORE, PACKETS, TOTAL_BYTES, toInt32(FIRST_SEEN) FIRST_SEEN, toInt32(LAST_SEEN) LAST_SEEN, SRC_ASN, DST_ASN, L7_CATEGORY, STATUS, FLOW_RISK, SRC2DST_TCP_FLAGS, DST2SRC_TCP_FLAGS, CLIENT_NW_LATENCY_US, SERVER_NW_LATENCY_US, INFO, OBSERVATION_POINT_ID, IPv4NumToString(PROBE_IP) PROBE_IP_FORMATTED, SRC_NETWORK_ID, DST_NETWORK_ID, SRC_HOST_POOL_ID, DST_HOST_POOL_ID, FLOW_ID, VLAN_ID, IP_PROTOCOL_VERSION, IPv4NumToString(IPV4_SRC_ADDR) IPV4_SRC_ADDR_FORMATTED, IPv4NumToString(IPV4_DST_ADDR) IPV4_DST_ADDR_FORMATTED, IPv6NumToString(IPV6_SRC_ADDR) IPV6_SRC_ADDR_FORMATTED, IPv6NumToString(IPV6_DST_ADDR) IPV6_DST_ADDR_FORMATTED, IP_SRC_PORT, IP_DST_PORT, SRC_LABEL, DST_LABEL, CLIENT_LOCATION, SERVER_LOCATION, COMMUNITY_ID, (LAST_SEEN - FIRST_SEEN) as TIME_DELTA, (TOTAL_BYTES / (TIME_DELTA + 1)) * 8 as THROUGHPUT FROM flows WHERE (INTERFACE_ID=4) AND (FIRST_SEEN >= 1643534976) AND (LAST_SEEN <= 1643536776)  ORDER BY FIRST_SEEN desc LIMIT 10 ]
jan 30 12:59:36 [855334]: 30/Jan/2022 12:59:36 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/historical_db_search.lua][...png/scripts/lua/pro/modules/flow_db/clickhouse_utils.lua:785: bad argument #1 to 'for iterator' (table expected, got nil)]

**What did you expect to happen?**

**How did you reproduce it?**
add clickhouse as backend then try to create new host pool

**Debug Information**:

an 30 13:00:15 Code: 16. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: No such column DST_HOST_POOL_ID in table ntopng.flows (3d03edff-06ae-4e89-a876-7b7f8e238020). (NO_SUCH_COLUMN_>
jan 30 13:00:15 novalocal ntopng[855334]: (query: INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR>
jan 30 13:00:15 novalocal ntopng[859386]: cat: write error: Broken pipe
jan 30 13:00:15novalocal ntopng[855334]: [ClickHouseImport.cpp:88] WARNING: Unable to execute 'cat /var/lib/ntopng/tmp/clickhouse/clickhouse-4-35-860.1643536797.csv | /usr/bin/clickhouse-client --host "127.0.0.1" --user ">
jan 30 13:00:15 novalocal ntopng[855334]: [ClickHouseImport.cpp:89] WARNING: Received exception from server (version 22.1.3):
                                                       Code: 16. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: No such column DST_HOST_POOL_ID in table ntopng.flows (3d03edff-06ae-4e89-a876-7b7f8e238020). (NO_SUCH_COLUMN_>
                                                       (query: INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR>
jan 30 13:00:15 novalocal ntopng[855334]: 30/Jan/2022 13:00:15 [ClickHouseImport.cpp:88] WARNING: Unable to execute 'cat /var/lib/ntopng/tmp/clickhouse/clickhouse-4-35-860.1643536797.csv | /usr/bin/clickhouse-client --host>
jan 30 13:00:15novalocal ntopng[855334]: 30/Jan/2022 13:00:15 [ClickHouseImport.cpp:89] WARNING: Received exception from server (version 22.1.3):
jan 30 13:00:15 novalocal ntopng[855334]: Code: 16. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: No such column DST_HOST_POOL_ID in table ntopng.flows (3d03edff-06ae-4e89-a876-7b7f8e238020). (NO_SUCH_COLUMN_>
jan 30 13:00:15 novalocal ntopng[855334]: (query: INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR>

**Comment by MatteoBiscosi** [comment]
Hi @alexiff I'm sorry for the trouble, a new update is going to be released soon, in a couple of hours at max it should be fixed

**Comment by notyourcommy** [comment]
Thank you. I think I fixed it on our installation with "  ALTER TABLE flows add column DST_HOST_POOL_ID UInt16; "
I'm not sure if this is the correct way but still it helped.

**Comment by notyourcommy** [comment]
@MatteoBiscosi should I open another issue regarding problem with unable to create new host pool? I'm pressing Add and nothing happens
