### ISSUE TITLE
Failed to migrate from nIndex to Clickhouse 

### ISSUE THREAD

**Issue by Yoshihiro-jp** [ntop/ntopng#6264]
**Environment**:
* OS name: [e.g. Ubuntu] Ubuntu
* OS version: [e.g. 18.04] "20.04.3 LTS (Focal Fossa)"
* Architecture: [e.g. amd64] 86_64
* ntopng version/revision: [e.g. 5.1.211223] 5.1.220127

**What happened**:
When executing the "nindex_export_to_ch.sh" I got the below errors.

ntop@ntopng:~$ sudo ./nindex_export_to_ch.sh -d /var/lib/ntopng/
・
・
～snip～

Error while exporting directory:
/var/lib/ntopng//2/flows | Return code n. 27: nIndex DB data corrupted.
/var/lib/ntopng//3/flows | Return code n. 27: nIndex DB data corrupted.
～end～

**What did you expect to happen?**

The  "nindex_export_to_ch.sh" should be finished without any errors and I could see the past raw flows.

**How did you reproduce it?**

Just execute the "nindex_export_to_ch.sh"

**Debug Information**:

ex_export_to_ch.sh -d /var/lib/ntopng/
1
Exporting directory: /var/lib/ntopng//0/flows
Exporting from row: 0 to row: 100000
Exporting from row: 100000 to row: 200000
Code: 108. DB::Exception: No data to insert: (in query: INSERT INTO flows (COMMUNITY_ID,DST2SRC_DSCP,DST2SRC_TCP_FLAGS,DST_ASN,DST_COUNTRY_CODE,DST_LABEL,DST_MAC,INFO,INTERFACE_ID,IPV4_DST_ADDR,IPV4_SRC_ADDR,IPV6_DST_ADDR,IPV6_SRC_ADDR,IP_DST_PORT,IP_PROTOCOL_VERSION,L7_CATEGORY,L7_PROTO,L7_PROTO_MASTER,FIRST_SEEN,LAST_SEEN,PACKETS,PROFILE,PROTOCOL,SCORE,SRC2DST_DSCP,SRC2DST_TCP_FLAGS,SRC_ASN,SRC_COUNTRY_CODE,SRC_MAC,TOTAL_BYTES,VLAN_ID) FORMAT CSV). (NO_DATA_TO_INSERT)

Done exporting directory: /var/lib/ntopng//0/flows
Exporting directory: /var/lib/ntopng//-1/flows
Done exporting directory: /var/lib/ntopng//-1/flows
Exporting directory: /var/lib/ntopng//1/flows
Exporting from row: 0 to row: 100000

Exporting from row: 6800000 to row: 6900000
Exporting from row: 6900000 to row: 7000000
Exporting from row: 7000000 to row: 7100000
Exporting from row: 7100000 to row: 7200000
Exporting from row: 7200000 to row: 7300000
Code: 108. DB::Exception: No data to insert: (in query: INSERT INTO flows (COMMUNITY_ID,DST2SRC_DSCP,DST2SRC_TCP_FLAGS,DST_ASN,DST_COUNTRY_CODE,DST_LABEL,DST_MAC,INFO,INTERFACE_ID,IPV4_DST_ADDR,IPV4_SRC_ADDR,IPV6_DST_ADDR,IPV6_SRC_ADDR,IP_DST_PORT,IP_PROTOCOL_VERSION,L7_CATEGORY,L7_PROTO,L7_PROTO_MASTER,FIRST_SEEN,LAST_SEEN,PACKETS,PROFILE,PROTOCOL,SCORE,SRC2DST_DSCP,SRC2DST_TCP_FLAGS,SRC_ASN,SRC_COUNTRY_CODE,SRC_MAC,TOTAL_BYTES,VLAN_ID) FORMAT CSV). (NO_DATA_TO_INSERT)

Done exporting directory: /var/lib/ntopng//9/flows
Exporting directory: /var/lib/ntopng//category_lists/flows
Done exporting directory: /var/lib/ntopng//category_lists/flows
Exporting directory: /var/lib/ntopng//n2disk/flows
Done exporting directory: /var/lib/ntopng//n2disk/flows
Exporting directory: /var/lib/ntopng//plugins0/flows
Done exporting directory: /var/lib/ntopng//plugins0/flows
Exporting directory: /var/lib/ntopng//tmp/flows
Done exporting directory: /var/lib/ntopng//tmp/flows
Error while exporting directory:
/var/lib/ntopng//2/flows | Return code n. 27: nIndex DB data corrupted.
/var/lib/ntopng//3/flows | Return code n. 27: nIndex DB data corrupted.

**Comment by MatteoBiscosi** [comment]
Hi @Yoshihiro-jp that's not a problem, in fact the code still run, probably it just get an empty CSV file, the database launch a "NO DATA TO INSERT", so it receive an empty file as CSV. Don't worry, I'm gonna fix the nindex_export_to_ch just not to show the error but don't worry.

**Comment by Yoshihiro-jp** [comment]
Hello @MatteoBiscosi , thank you for your reply however flows haven't migrated after the completion of the "ex_export_to_ch.sh".
Kindly refer to the attached file and below stdout.

![nodata_interface_no2](https://user-images.githubusercontent.com/58843707/151764603-c29bf5d4-f49e-486a-af84-a493e038fb20.png)

root@ntopng:/var/lib/ntopng/2/flows/2022/01/17# ll
total 296
drwx------ 26 ntopng ntopng  4096 Jan 17 23:00 ./
drwx------ 29 ntopng ntopng  4096 Jan 27 00:00 ../
drwx------  2 ntopng ntopng 12288 Jan 17 01:00 00/
drwx------  2 ntopng ntopng 12288 Jan 17 02:00 01/
drwx------  2 ntopng ntopng 12288 Jan 17 03:00 02/
drwx------  2 ntopng ntopng 12288 Jan 17 04:00 03/
drwx------  2 ntopng ntopng 12288 Jan 17 05:00 04/
drwx------  2 ntopng ntopng 12288 Jan 17 06:00 05/
drwx------  2 ntopng ntopng 12288 Jan 17 07:00 06/
drwx------  2 ntopng ntopng 12288 Jan 17 08:00 07/
drwx------  2 ntopng ntopng 12288 Jan 17 09:00 08/
drwx------  2 ntopng ntopng 12288 Jan 17 10:00 09/
drwx------  2 ntopng ntopng 12288 Jan 17 11:00 10/
drwx------  2 ntopng ntopng 12288 Jan 17 12:00 11/
drwx------  2 ntopng ntopng 12288 Jan 17 13:00 12/
drwx------  2 ntopng ntopng 12288 Jan 17 14:00 13/
drwx------  2 ntopng ntopng 12288 Jan 17 15:00 14/
drwx------  2 ntopng ntopng 12288 Jan 17 16:00 15/
drwx------  2 ntopng ntopng 12288 Jan 17 17:00 16/
drwx------  2 ntopng ntopng 12288 Jan 17 18:00 17/
drwx------  2 ntopng ntopng 12288 Jan 17 19:00 18/
drwx------  2 ntopng ntopng 12288 Jan 17 20:00 19/
drwx------  2 ntopng ntopng 12288 Jan 17 21:00 20/
drwx------  2 ntopng ntopng 12288 Jan 17 22:00 21/
drwx------  2 ntopng ntopng 12288 Jan 17 23:00 22/
drwx------  2 ntopng ntopng 12288 Jan 18 00:00 23/
root@ntopng:/var/lib/ntopng/2/flows/2022/01/17# ll 00/
total 8012
drwx------  2 ntopng ntopng   12288 Jan 17 01:00 ./
drwx------ 26 ntopng ntopng    4096 Jan 17 23:00 ../
-rw-------  1 ntopng ntopng 1506601 Jan 17 01:00 COMMUNITY_ID.dat
-rw-------  1 ntopng ntopng     308 Jan 17 01:00 COMMUNITY_ID.dff
-rw-------  1 ntopng ntopng  221538 Jan 17 01:00 DST2SRC_BYTES.bdx
-rw-------  1 ntopng ntopng      28 Jan 17 01:00 DST2SRC_BYTES.bff
-rw-------  1 ntopng ntopng    4756 Jan 17 01:00 DST2SRC_DSCP.bdx

**Comment by MatteoBiscosi** [comment]
Hi @Yoshihiro-jp, could you please check the presence of the flows by selecting the "All Time" preset? 
![Screenshot from 2022-01-31 16-37-22](https://user-images.githubusercontent.com/49585191/151823532-86c4da18-a9de-4780-b6f1-b24ea4f3a688.png)
(maybe some time shift happened during the migration, don't worry the old nIndex data are not removed from the system).
If no data are available, could you please do the following?

Run clickhouse-client by typing `clickhouse-client` in the terminal.
`use ntopng`
`show tables`

And you should have something like this below.
┌─name─────────────────────┐
│ active_monitoring_alerts │
│ all_alerts               │
│ flow_alerts              │
│ flows                    │
│ host_alerts              │
│ interface_alerts         │
│ mac_alerts               │
│ network_alerts           │
│ snmp_alerts              │
│ system_alerts            │
│ user_alerts              │
└──────────────────────────┘

**Comment by Yoshihiro-jp** [comment]
Dear @MatteoBiscosi ,
Kindly refer to the attached file.
Even if I set the "All time" there are no data.

![alltime](https://user-images.githubusercontent.com/58843707/151893210-8952befa-4ffc-4a5a-84ab-934701fa9322.png)


I executed the clickhouse-client.

ntop@ntopng:~$ clickhouse-client --password default
ClickHouse client version 22.1.3.7 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.11.4 revision 54450.

ClickHouse server version is older than ClickHouse client. It may indicate that the server is out of date and can be upgraded.

ntopng :) use ntopng

USE ntopng

Query id: f9591a40-7c2f-4e84-bcc9-5d2800806812

Ok.

0 rows in set. Elapsed: 0.001 sec.

ntopng :) show tables

SHOW TABLES

Query id: 5013a9e7-aedf-4d9b-af26-a82838876a84

lqnameqqqqqqqqqqqqqqqqqqqqqk
x active_monitoring_alerts x
x all_alerts               x
x flow_alerts              x
x flows                    x
x host_alerts              x
x interface_alerts         x
x mac_alerts               x
x network_alerts           x
x snmp_alerts              x
x system_alerts            x
x user_alerts              x
mqqqqqqqqqqqqqqqqqqqqqqqqqqj

11 rows in set. Elapsed: 0.001 sec.

ntopng :)

regards,
Yoshihiro

**Comment by MatteoBiscosi** [comment]
Hi @Yoshihiro-jp , could you please connect to clickhouse-client and do:
`use ntopng`
`select * from flows order by FIRST_SEEN asc limit 1`
and send me the first_seen and last_seen result?
![Screenshot from 2022-02-01 09-55-41](https://user-images.githubusercontent.com/49585191/151939025-0cab8f74-1162-4659-8f92-d0d67eaebff4.png)
(to understand when it was the first record)

**Comment by Yoshihiro-jp** [comment]
Dear @MatteoBiscosi ,

Thank you for your comments.
Kindly refer to the attached.

![sqlresult](https://user-images.githubusercontent.com/58843707/151944630-41e596a1-d392-454d-a42c-0fe4f7aea001.png)

The current problem is about Interface ID#2. The FIRT_SEEN and LAST_SEEN are made by other Interface IDs.

Could you tell me the query to define the Interface ID#2?

Because I have some interfaces like below.

`root@ntopng:/var/lib/ntopng# ls
0  -1  1  10  11  16  17  18  19  2  22  23  3  4  5  6  7  8  9  category_lists  n2disk  plugins0  tmp  ts_export`

regards,
Yoshihiro

**Comment by MatteoBiscosi** [comment]
Hi @Yoshihiro-jp , to filter out by interface, just use the following query
`select * from flows where INTERFACE_ID = 2 order by FIRST_SEEN asc limit 1`

**Comment by MatteoBiscosi** [comment]
If no rows can be found for the interface 2 please run the following command:
`nindex -d /var/lib/ntopng//2/flows -f /tmp/export_tmp.csv -L 0 -l 100000 -c -s "COMMUNITY_ID,DST2SRC_DSCP,DST2SRC_TCP_FLAGS,DST_ASN,DST_COUNTRY_CODE,DST_LABEL,DST_MAC,INFO,INTERFACE_ID,IPV4_DST_ADDR,IPV4_SRC_ADDR,IPV6_DST_ADDR,IPV6_SRC_ADDR,IP_DST_PORT,IP_PROTOCOL_VERSION,L7_CATEGORY,L7_PROTO,L7_PROTO_MASTER,FIRST_SEEN,LAST_SEEN,PACKETS,PROFILE,PROTOCOL,SCORE,SRC2DST_DSCP,SRC2DST_TCP_FLAGS,SRC_ASN,SRC_COUNTRY_CODE,SRC_MAC,TOTAL_BYTES,VLAN_ID"
`

The first 100k flows are going to be exported as CSV in the /tmp/export_tmp.csv, so check it out the values inside the files using
`cat /tmp/export_tmp.csv`

**Comment by Yoshihiro-jp** [comment]
Dear @MatteoBiscosi ,

Thank you for your advice. I would check some data for verification.
I would tell you after finishing it.

regards,
Yoshihiro

**Comment by Yoshihiro-jp** [comment]
Dear @MatteoBiscosi ,

I used the "-s 1640962800 " option to check the last flow data in the "/var/lib/ntopng/2/flows".
The "1640962800" is from the 2022/01/01".

$sudo nindex -d /var/lib/ntopng//2/flows -f /tmp/export_tmp.csv -s 1640962800 -c -s "COMMUNITY_ID,DST2SRC_DSCP,DST2SRC_TCP_FLAGS,DST_ASN,DST_COUNTRY_CODE,DST_LABEL,DST_MAC,INFO,INTERFACE_ID,IPV4_DST_ADDR,IPV4_SRC_ADDR,IPV6_DST_ADDR,IPV6_SRC_ADDR,IP_DST_PORT,IP_PROTOCOL_VERSION,L7_CATEGORY,L7_PROTO,L7_PROTO_MASTER,FIRST_SEEN,LAST_SEEN,PACKETS,PROFILE,PROTOCOL,SCORE,SRC2DST_DSCP,SRC2DST_TCP_FLAGS,SRC_ASN,SRC_COUNTRY_CODE,SRC_MAC,TOTAL_BYTES,VLAN_ID"

Then I checked the last 3 lines.

$ sudo tail -n 3  export_tmp.csv
[sudo] password for ntop:
1:TVkbiiBTJ1S6faRBVaaUpuEiIvQ=|0|27|0|0||12852||2|3232259820|3232259387|::|::|443|4|5|91|0|1643269568|1643269570|270||6|50|0|27|0|0|0|261830|0
1:cdDagq2mj4qfuScIkzswWUxrkz4=|0|0|0|0|brother dcp-l2550dw series|12852||2|3232259339|3232259365|::|::|161|4|14|14|0|1643269525|1643269525|8||17|0|0|0|0|0|0|454|0
1:uOOgKedr3/4AxAAD5id0R1roz7I=|0|0|0|0||12852||2|3232259340|3232259056|::|::|161|4|14|14|0|1643269525|1643269525|4||17|0|0|0|0|0|0|348|0
ntop@ntopng:/tmp$

It looks that there is the flow data until "2022/1/27".
So I think that the migration is really failed.

Should I try to execute the "ex_export_to_ch.sh" again?
At that time don't you have some debug options to find the problem?

regards,
Yoshihiro
![20220101](https://user-images.githubusercontent.com/58843707/152307059-8291c385-a65a-46c5-9f61-695b5f7265a0.png)

**Comment by MatteoBiscosi** [comment]
Hi @Yoshihiro-jp, the other data were exported correctly, just the ones from the interface 2 were not exported, probably due to some problem. Don't execute again "ex_export_to_ch.sh" because it's going to export all the data again (risking on creating duplicates).
To try to solve the problem export the data manually in the following way:

`sudo nindex -d /var/lib/ntopng//2/flows -f /tmp/export_tmp.csv -c -s "COMMUNITY_ID,DST2SRC_DSCP,DST2SRC_TCP_FLAGS,DST_ASN,DST_COUNTRY_CODE,DST_LABEL,DST_MAC,INFO,INTERFACE_ID,IPV4_DST_ADDR,IPV4_SRC_ADDR,IPV6_DST_ADDR,IPV6_SRC_ADDR,IP_DST_PORT,IP_PROTOCOL_VERSION,L7_CATEGORY,L7_PROTO,L7_PROTO_MASTER,FIRST_SEEN,LAST_SEEN,PACKETS,PROFILE,PROTOCOL,SCORE,SRC2DST_DSCP,SRC2DST_TCP_FLAGS,SRC_ASN,SRC_COUNTRY_CODE,SRC_MAC,TOTAL_BYTES,VLAN_ID"`

`tail -n +2 cat /tmp/export_tmp.csv | /usr/bin/clickhouse-client --host "127.0.0.1" --user "default" --password "" -d "ntopng" --format_csv_delimiter="|" --query="INSERT INTO flows (COMMUNITY_ID,DST2SRC_DSCP,DST2SRC_TCP_FLAGS,DST_ASN,DST_COUNTRY_CODE,DST_LABEL,DST_MAC,INFO,INTERFACE_ID,IPV4_DST_ADDR,IPV4_SRC_ADDR,IPV6_DST_ADDR,IPV6_SRC_ADDR,IP_DST_PORT,IP_PROTOCOL_VERSION,L7_CATEGORY,L7_PROTO,L7_PROTO_MASTER,FIRST_SEEN,LAST_SEEN,PACKETS,PROFILE,PROTOCOL,SCORE,SRC2DST_DSCP,SRC2DST_TCP_FLAGS,SRC_ASN,SRC_COUNTRY_CODE,SRC_MAC,TOTAL_BYTES,VLAN_ID) FORMAT CSV"`

In this way you are going to manually do the things that the script was doing, extract the data from nindex as CSV and then import them into clickhouse. Remember to change the host, user, password accordingly.
Remember to close ntopng while exporting data.

**Comment by Yoshihiro-jp** [comment]
Dear @MatteoBiscosi ,

I followed above commands and then I got the error below:

I think that the format of exported CSV is something wrong.
Could you check below errors?

～～～
Code: 27. DB::ParsingException: Cannot parse input: expected '|' before: '0|25438|0\n1:zjOcLuumbdDBM8P9daRWDAhIH+0=|0|0|0|0||0||2|323225
8863|3232259392|::|::|161|4|14|14|0|1640735950|2||17|10|0|0|0|0|0|109|0\n1:N0/FVUoFlU1tpT9nDuqududNx':
Row 1:
Column 0,   name: COMMUNITY_ID,        type: String,   parsed text: "1:qn3zi9rB1U8fWeCPpVFktHPl42A="
Column 1,   name: DST2SRC_DSCP,        type: UInt8,    parsed text: "0"
Column 2,   name: DST2SRC_TCP_FLAGS,   type: UInt8,    parsed text: "26"
Column 3,   name: DST_ASN,             type: UInt32,   parsed text: "14618"
Column 4,   name: DST_COUNTRY_CODE,    type: UInt16,   parsed text: "21843"
Column 5,   name: DST_LABEL,           type: String,   parsed text: "agent-api.obkio.com"
Column 6,   name: DST_MAC,             type: UInt64,   parsed text: "0"
Column 7,   name: INFO,                type: String,   parsed text: "ws.obkio.com"
Column 8,   name: INTERFACE_ID,        type: UInt16,   parsed text: "2"
Column 9,   name: IPV4_DST_ADDR,       type: UInt32,   parsed text: "920668784"
Column 10,  name: IPV4_SRC_ADDR,       type: UInt32,   parsed text: "3232259366"
Column 11,  name: IPV6_DST_ADDR,       type: IPv6,     parsed text: "::"
Column 12,  name: IPV6_SRC_ADDR,       type: IPv6,     parsed text: "::"
Column 13,  name: IP_DST_PORT,         type: UInt16,   parsed text: "443"
Column 14,  name: IP_PROTOCOL_VERSION, type: UInt8,    parsed text: "4"
Column 15,  name: L7_CATEGORY,         type: UInt16,   parsed text: "5"
Column 16,  name: L7_PROTO,            type: UInt16,   parsed text: "178"
Column 17,  name: L7_PROTO_MASTER,     type: UInt16,   parsed text: "91"
Column 18,  name: FIRST_SEEN,          type: DateTime, parsed text: "1640735711"
Column 19,  name: LAST_SEEN,           type: DateTime, parsed text: "289||6|80|0|26|0|0|"
ERROR: garbage after DateTime: "0|25438|0<LINE FEED>"
ERROR: DateTime must be in YYYY-MM-DD hh:mm:ss or NNNNNNNNNN (unix timestamp, exactly 10 digits) format.

: While executing ParallelParsingBlockInputFormat: data for INSERT was parsed from stdin: (in query: INSERT INTO flows (COMMUNITY_ID,DST
2SRC_DSCP,DST2SRC_TCP_FLAGS,DST_ASN,DST_COUNTRY_CODE,DST_LABEL,DST_MAC,INFO,INTERFACE_ID,IPV4_DST_ADDR,IPV4_SRC_ADDR,IPV6_DST_ADDR,IPV6_
SRC_ADDR,IP_DST_PORT,IP_PROTOCOL_VERSION,L7_CATEGORY,L7_PROTO,L7_PROTO_MASTER,FIRST_SEEN,LAST_SEEN,PACKETS,PROFILE,PROTOCOL,SCORE,SRC2DS
T_DSCP,SRC2DST_TCP_FLAGS,SRC_ASN,SRC_COUNTRY_CODE,SRC_MAC,TOTAL_BYTES,VLAN_ID) FORMAT CSV): (at row 1)
. (CANNOT_PARSE_INPUT_ASSERTION_FAILED)
～～

regards,
Yoshihiro

**Comment by MatteoBiscosi** [comment]
Hi yoshiro, could you please send me your exported file (/tmp/export_tmp.csv)? Drop an email at `biscosi at ntop.org`, in this way I'll be able to directly try to parse it and solve the issue.

**Comment by Yoshihiro-jp** [comment]
Dear @MatteoBiscosi,

I just update this thread for other users.

The nIndex data for the Interface 2 seems corrupted, take the below data,
 
COMMUNITY_ID,DST2SRC_DSCP,DST2SRC_TCP_FLAGS,DST_ASN,DST_COUNTRY_CODE,DST_LABEL,DST_MAC,INFO,INTERFACE_ID,IPV4_DST_ADDR,IPV4_SRC_ADDR,IPV6_DST_ADDR,IPV6_SRC_ADDR,IP_DST_PORT,
IP_PROTOCOL_VERSION,L7_CATEGORY,L7_PROTO,L7_PROTO_MASTER,FIRST_SEEN,LAST_SEEN,PACKETS,PROFILE,PROTOCOL,SCORE,SRC2DST_DSCP,SRC2DST_TCP_FLAGS,SRC_ASN,SRC_COUNTRY_CODE,SRC_MAC,TOTAL_BYTES,VLAN_ID
1:JZ+vPMEMxg+/UQRpYs/imt8lWlw=|0|0|0|0||0||2|3232258863|3232259392|::|::|161|4|14|14|0|1640822356|2||17|10|0|0|0|0|0|109|0 
1:bL87kzWEGvKmGFs24iAipjwSWMA=|0|4725|19024|www.mydns.jp|0|[www.mydns.jp/login.html|2|3536145107|3232259366|::|::|80|4|5|7|7|1640822401|1640822401|13||6|0|0|27|0|0|0|2473|0](http://www.mydns.jp/login.html%7C2%7C3536145107%7C3232259366%7C::%7C::%7C80%7C4%7C5%7C7%7C7%7C1640822401%7C1640822401%7C13%7C%7C6%7C0%7C0%7C27%7C0%7C0%7C0%7C2473%7C0) 

`1640822356` and `1640822401` are the FIRST_SEEN column, instead, the second row has a LAST_SEEN, but the first row not.

Additionally the nIndex data from interface 2 were a lot corrupted (they just don't miss the LAST_SEEN, but sometimes even the DST2SRC_TCP_FLAGS, other times the DST_ASN),  he was trying to save some of them but  doesn't know how far he can go (just analyzed the first 1m row of 25m and already got these problems).
PS: This problem is one of the reasons we decided to switch to ClickHouse

regards,
Yoshihiro

**Comment by Yoshihiro-jp** [comment]
Dear @MatteoBiscosi ,

I followed your suggestion(omit some fields to export) then it is succeeded to import finally!

#nindex -d /var/lib/ntopng//2/flows -f /tmp/export_tmp.csv -c -s "COMMUNITY_ID,DST_LABEL,DST_MAC,INTERFACE_ID,IPV4_DST_ADDR,IPV4_SRC_ADDR,IPV6_DST_ADDR,IPV6_SRC_ADDR,IP_DST_PORT,IP_PROTOCOL_VERSION,L7_CATEGORY,L7_PROTO,L7_PROTO_MASTER,FIRST_SEEN,LAST_SEEN,PACKETS,PROTOCOL,SRC_MAC,TOTAL_BYTES,VLAN_ID"
17/Feb/2022 14:00:08 [nindex.cpp:518] Up to 100000 records will be returned (-l)
17/Feb/2022 14:00:22 [nindex.cpp:555] Query completed in 14291.0 msec, with 0 hits returned

#tail +2 export_tmp.csv > tail2_export_tmp.csv
#cat /tmp/tail2_export_tmp.csv | /usr/bin/clickhouse-client --host "127.0.0.1" --user "default" --password "default" -d "ntopng" --format_csv_delimiter="|" --query="INSERT INTO flows (COMMUNITY_ID,DST_LABEL,DST_MAC,INTERFACE_ID,IPV4_DST_ADDR,IPV4_SRC_ADDR,IPV6_DST_ADDR,IPV6_SRC_ADDR,IP_DST_PORT,IP_PROTOCOL_VERSION,L7_CATEGORY,L7_PROTO,L7_PROTO_MASTER,FIRST_SEEN,LAST_SEEN,PACKETS,PROTOCOL,SRC_MAC,TOTAL_BYTES,VLAN_ID) FORMAT CSV"

Thank you very much!

regards,
Yoshihiro

**Comment by MatteoBiscosi** [comment]
Glad to here it Yoshihiro!
