### ISSUE TITLE
Possibility to also use hostname when adding an "export filter" in Historical Flow Explorer

### ISSUE THREAD

**Issue by Niklasr69** [ntop/ntopng#6265]
Today a exporters hostname must be lookup to find the IP before it can be added as a filter.
To simplify/avoid it should be very good if it was possible to write hostname direct when adding the "exporter filter" 

<img width="595" alt="image" src="https://user-images.githubusercontent.com/26242302/151746429-1f626d79-db8c-4965-b9e0-6b04c887a252.png">

**Comment by Niklasr69** [comment]
any date for this feature?

**Comment by cardigliano** [comment]
We can probably add a dropdown here to select the exporter out of those available. In that case it is easier to select one, and we can display the hostname when available.

**Comment by MatteoBiscosi** [comment]
Implemented as requested
