### ISSUE TITLE
When sorting after heights Thpt, 0 bit/s comes first

### ISSUE THREAD

**Issue by Niklasr69** [ntop/ntopng#6266]
**Environment**:
* OS name: Rocky Linux
* OS version: 8.5 
* Architecture: 
* ntopng version/revision: ntopng Enterprise L v.5.1.220128

**What happened**:
When sorting after heights bit/s in history page the 0bit/s comes first 

**What did you expect to happen?**
The 0/bits should not come first.

**How did you reproduce it?**

**Debug Information**:

![image](https://user-images.githubusercontent.com/26242302/151783706-b2ad764c-19d1-44db-860c-7e94958824f3.png)

**Comment by MatteoBiscosi** [comment]
Hi @Niklasr69 , thx for the report, a new build soon is going to be released, in a couple of hours should be available, update and let me know if the problem is fixed

**Comment by Niklasr69** [comment]
Problem solved in ntopng  v.5.1.220201
