### ISSUE TITLE
FR : direct link in host detail to history

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#627]
hi

when we select a host to get details, it would be interesting to have a link to history directly here to ovoid to click on "home", "historical data...", then enter host...

nico

nico

**Comment by simonemainardi** [comment]
The link is already there, look ad the clock icon that goes backward:

![image](https://cloud.githubusercontent.com/assets/3397663/16553966/1ff70f7a-41cc-11e6-96a0-31df9eee7451.png)
