### ISSUE TITLE
Acknowledging one unexpected device alert updates all of them and updates user_label on all mac_alerts in Clickhouse

### ISSUE THREAD

**Issue by dpetzer** [ntop/ntopng#6272]
**Environment**:
Ubuntu 20

* ntopng version/revision: [e.g. 5.1.211223]
ntopng Enterprise L v.5.1.220127

**What happened**:
Enabled Unexpected Device Connected check.

View alerts in GUI using severity 4 filter
[http://<ntop_ip>:3000/lua/alert_stats.lua?severity=4%3Beq&epoch_begin=1643768830&epoch_end=1643773133&page=mac#11] 

View 9 alerts in table.

Retrieve clickhouse query from browser tools -> network
[http://<ntop_ip>:3000/lua/rest/v2/get/mac/alert/list.lua?page=mac&score=&status=historical&epoch_end=1643773133&severity=4;eq&ifid=2&epoch_begin=1643768830&draw=1&order=asc&start=0&length=10&sort=tstamp&visible_columns=tstamp%2Cscore%2Cmsg%2Caddress%2Cdevice_type%2Cname%2Cdescription&_=1643774090422]

`SELECT 5 entity_id, (toUnixTimestamp(tstamp_end) - toUnixTimestamp(tstamp)) duration, * FROM `mac_alerts` 
WHERE ( alert_status = 0 ) AND (interface_id = 2)  ORDER BY tstamp asc LIMIT 200 OFFSET 0 `

Observe 9 entries in Clickhouse
user_label column is empty.

Select drop down on one of the 9

 alerts, receive popup and enter "This is a cisco device" in the comment then click Acknowledge.
![Screen Shot 2022-02-02 at 3 17 14 pm](https://user-images.githubusercontent.com/8804266/152092323-a67dd962-8f91-4359-abdc-a0b2288ce873.png)
All alerts are gone from menu.

Refresh Clickhosue query, no results, change alert_status in where clause to 1 and all alerts appear. All alerts have "This is a cisco device" in the user_label.

![Screen Shot 2022-02-02 at 3 14 22 pm](https://user-images.githubusercontent.com/8804266/152092156-5917c37f-6269-46ce-87e8-f211545884e1.png)

**What did you expect to happen?**

Only one alert should be processed, the one I selected. It should be updated so that it is removed from the list.
The DB should only change one entry to status = 1 and update the user_label on only that entry.

**How did you reproduce it?**
Wait till there is an additional Unexpected Device Connected alert and repeat.

**Debug Information**:

New to this project so I am unable to help much further.

**Comment by MatteoBiscosi** [comment]
Hi @dpetzer, this is not a bug, they are not gone. You acknowledged them so now they are in the "Ack" tab, not in the "Past" tab.
Click here and you'll see them again.
![Screenshot from 2022-02-02 11-23-44](https://user-images.githubusercontent.com/49585191/152136176-18b86698-a18f-438b-afd8-ef689523b802.png)

**Comment by dpetzer** [comment]
I see, I would have expected the button in red to only acknowledge the alert for the MAC address ending in 93:5E.
I would have expected the button highlighted in blue to acknowledge all of them.

![Screen Shot 2022-02-03 at 8 22 22 am](https://user-images.githubusercontent.com/8804266/152240417-cb6a0757-2c31-4057-88aa-bee692e03dce.png)

**Comment by MatteoBiscosi** [comment]
Hi @dpetzer, yes the red button acknowledge one of them and the blue button all the ones in the time frame selected and with the filters selected. But after acknowledging them they are going to disappear from the past tab and appear in the ack tab

**Comment by dpetzer** [comment]
> Hi @dpetzer, yes the red button acknowledge one of them and the blue button all the ones in the time frame selected and with the filters selected. But after acknowledging them they are going to disappear from the past tab and appear in the ack tab

It seems to me like the red button is acknowledging all of them. But I expected it to do what you said, "acknowledge one of them", only that one should move to the ack tab, the others should stay. But they all move to the ack tab.

I captured the POST with wire shark when I click the red button. I can see the JSON data being sent. Looks like the row-id is set to all zeros?

![Screen Shot 2022-02-04 at 9 07 10 pm](https://user-images.githubusercontent.com/8804266/152512217-1f557466-fae9-45eb-b780-ee016600db7a.png)

Then I go and look in the clickhouse database and they are all zeros. 

I can see that the csrf is being sent (is that redis reference or a javascript helper for ui I don't know?).

I search for mention of csrf in the code in the following places but can't find any:
scrips/lua/rest/v2/acknowledge/mac/alerts.lua
scripts/lua/modules/alert_store/alert_store.lua
scripts/lua/modules/alert_store/mac_alert_store.lua

So row_id should be unique then? But they are all zeros.
Anyway, I hope this helps.

![Screen Shot 2022-02-04 at 9 40 49 pm](https://user-images.githubusercontent.com/8804266/152515467-eb71c870-edfe-4bcc-b965-68895883004c.png)
