### ISSUE TITLE
Attempt to Reset Learned Devices appears to delete 0 devices 

### ISSUE THREAD

**Issue by dpetzer** [ntop/ntopng#6273]
**Environment**:
* OS name: Ubunt
* OS version: 20.04
* Architecture: amd64
* ntopng version/revision: ntopng Enterprise L v.5.1.220127 (Ubuntu 20.04.3 LTS)

**What happened**:
Configuring alerts for "Unexpected Device Connected". I want to Reset Learned Devices to trigger alerts again when they are again seen.

Navigate to the Check [http://<ntop>:3000/lua/admin/edit_configset.lua?subdir=all#enabled]
Search for unexpected device connected and select Edit Check Options
![Screen Shot 2022-02-02 at 4 00 05 pm](https://user-images.githubusercontent.com/8804266/152095817-c387e1e8-6fb4-41c0-a537-349ed1b74e02.png)

Click Reset Learned Devices button.
![Screen Shot 2022-02-02 at 4 02 00 pm](https://user-images.githubusercontent.com/8804266/152095925-0e3724ac-fd54-4f0f-a873-6b061847f294.png)

Receive popup saying Success.

Wait for many alerts to be generated as devices are re-discovered.

No alerts generated.

**What did you expect to happen?**
Expected to see a few hundred Unexpected Device Connected Alerts.

**How did you reproduce it?**
Observe POST in wireshark to find the API url.
[http://<ntop>:3000/lua/rest/v2/delete/host/new_devices.lua]

![image](https://user-images.githubusercontent.com/8804266/152095997-855774cc-7d55-462c-a30b-328b7506c212.png)

Edit the /rest/v2/delete/host/new_devices.lua file so that instead of deleting devices it counts the number of devices that it would delete and returns that.

Before:
` 
 function new_devices.reset_macs() 

    local getIfNames = interface.getIfNames()
    for key, value in pairs(getIfNames) do
        -- Retrieving the if id 
        --local ifid = value.getId()

        local seen_devices_hash = getFirstSeenDevicesHashKey(key)
        -- Retrieving the list of the addresses already seen
        local seen_devices = ntop.getHashAllCache(seen_devices_hash) or {}

        for key, value in pairs(seen_devices) do
            ntop.delHashCache(seen_devices_hash, key)
            ntop.delCache(redis_key .. "." .. key)
        end
    end    

    rest_utils.answer(rest_utils.consts.success.ok)
end`

After (My comments have four hyphens in front):
`function new_devices.reset_macs()

    ----
    ---- Added a string to output the count of deleted devices
    ---- Added a number to count the deleted devices

    local output_string = "Output String || "
    local counter = 0

    local getIfNames = interface.getIfNames()
    for key, value in pairs(getIfNames) do
        -- Retrieving the if id
        --local ifid = value.getId()

        local seen_devices_hash = getFirstSeenDevicesHashKey(key)
        -- Retrieving the list of the addresses already seen
        local seen_devices = ntop.getHashAllCache(seen_devices_hash) or {}

        ---- Add the seen_devices_hash to the info_string for fault finding
        output_string = string.format("%s Interface %s seen_devices_hash:%s || ", output_string, value, seen_devices_hash )
        for key, value in pairs(seen_devices) do
            ---- Commented out the lines that do the deletion
            -- ntop.delHashCache(seen_devices_hash, key)
            -- ntop.delCache(redis_key .. "." .. key)
            ---- Increment the counter instead
            counter = counter + 1
        end
    end

    ---- Added a payload to the answer
    rest_utils.answer(rest_utils.consts.success.ok,string.format("%s Count of seen devices is %d ||", output_string, counter))
    end`
**Debug Information**:

Output from the above shows the seen_device_hash for each interface and shows that the returned tables are empty.

`{"rsp":"Output String ||  Interface tcp://localhost:5556 seen_devices_hash:ntopng.seen_devices.ifid_4 ||  Interface enp0s25 seen_devices_hash:ntopng.seen_devices.ifid_2 ||  Count of seen devices is 0 ||","rc_str_hr":"Success","rc_str":"OK","rc":0}`

It is possible that the learned devices are being stored in a different hash.

**Comment by MatteoBiscosi** [comment]
Hi @dpetzer, yeah the hash changed during the time but it was not changed when resetting the devices, now it correctly works. a new build is in progress, when it's ready update and let me know if it works fine for you too

**Comment by dpetzer** [comment]
Thanks Matteo, 
The code you have updated is the function where the alert is stored. 

I will add some comments on the commit about needing to clean up where they were maybe duplicates being stored.

**Comment by MatteoBiscosi** [comment]
Hi @dpetzer , with the last commit I removed some no more useful code and now the alert seems working well and no unused code is stored in redis

**Comment by dpetzer** [comment]
I had a look, I am not familiar with this project or lua or redis but I can see that it looks like all the pieces are there now.
