### ISSUE TITLE
Invalid TLV error

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6274]
/Feb/2022 13:12:49 [ZMQParserInterface.cpp:1497] WARNING: Unsupported TLV key type 0: please update both ntopng and the probe to the same version
02/Feb/2022 13:12:49 [ZMQParserInterface.cpp:1497] WARNING: Unsupported TLV key type 0: please update both ntopng and the probe to the same version

the following error is reported when cento (dev) sends flows to ntopng

- ntopng -i tcp://127.0.0.1:1234c
- cento -i test.pcap -D 2 --json-labels -d 5 --zmq tcp://127.0.0.1:1234

**Comment by cardigliano** [comment]
Fixed (boolean and lists are not supported by ntopng in TLV format)

**Comment by lucaderi** [comment]
Verified as fixed
