### ISSUE TITLE
Missing definition for l4/flow counter id == '88'

### ISSUE THREAD

**Issue by TimotheusBachinger** [ntop/ntopng#6275]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]

**What happened**:
When getting flow counters via /get/flow/l4/counters.lua, we receive an ID of **88** but we do not find a human readable correspondence under /get/l4/protocol/consts.lua
In the UI, this is also visible:
![image](https://user-images.githubusercontent.com/57113191/152177327-81320e27-30bf-454a-ad63-0f8447340840.png)

**What did you expect to happen?**
id 88 can be translated to a human readable protocol.

**How did you reproduce it?**

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @TimotheusBachinger, pleas update to the latest ntopng version. How did you reproduce it? Probably the one you are getting is not the l4/counters but the l7, in fact `88 RDP                    TCP      Acceptable   RemoteAccess`

**Comment by TimotheusBachinger** [comment]
Hi Matteo, 

I used the calll /lua/rest/v2/get/flow/l4/counters.lua?ifid=4 and received:
![image](https://user-images.githubusercontent.com/57113191/152188694-467b087c-06c8-4ae2-b656-2fb7916a32e3.png)

So we were working with the l4 counters...

**Comment by MatteoBiscosi** [comment]
Hi @TimotheusBachinger i tried reproducing it but it seems everything works fine in my case, and l4 proto with id 88 it seems it does not exists in both ntopng and nDPI. Could you please send me a pcap with a traffic with that l4 proto? drop an email at `biscosi at ntop.org`

**Comment by TimotheusBachinger** [comment]
Hi Matteo,

unfortunately my customer cannot create a pcap on that system but here again the confirmation that it was the l4 proto:
![image](https://user-images.githubusercontent.com/57113191/152558704-a8947330-d355-44d2-b986-b2805b67786b.png)

**Comment by MatteoBiscosi** [comment]
Hi @TimotheusBachinger yeah, the problem is there, but we have no mapping for l4 protocol 88, I took a look at the code and the l4 proto is taken from the packets, so with no pcap to reproduce we cannot understand which protocol does it use.

**Comment by MatteoBiscosi** [comment]
Hi @TimotheusBachinger we switched to ntopng 5.3 (dev) or ntopng 5.2 (stable), so please update to one of those two versions

**Comment by TimotheusBachinger** [comment]
Hi @MatteoBiscosi ,

> so with no pcap to reproduce we cannot understand which protocol does it use

ok - got it. maybe my customer has a possibility in the future to capture it. for now we implement a workaround in our integration.
Will close the issue then.

Thanks for the clarification!
Timi

**Comment by TimotheusBachinger** [comment]
Hi Matteo,

I have now a pcap from the customer  - I will sent you the file via email, as it cannot be attached here.

Regards
Timi

**Comment by MatteoBiscosi** [comment]
Hi @TimotheusBachinger thanks a lot, I was able to reproduce and add the mapping in ntopng. A new version should be available tomorrow morning for both dev and stable version.

**Comment by TimotheusBachinger** [comment]
Hi @MatteoBiscosi,

Thanks for the fast actions from your side! I'll let the customer know about the builds/fixes.

Regards
Timi
