### ISSUE TITLE
Historical Data - Missing Raw Flows

### ISSUE THREAD

**Issue by olmanolsztyn** [ntop/ntopng#6279]
**Environment**:
* OS name: FreeBSD
* OS version: 12.2
* Architecture: amd64
* ntopng version/revision: ntopng Enterprise M v.5.1.220103

**What happened**:
Raw Flows is missing in Historical Data
![obraz](https://user-images.githubusercontent.com/22956491/152523907-3aa0ddd4-9a22-4520-9321-aee569d0db7d.png)
![obraz](https://user-images.githubusercontent.com/22956491/152533051-91aba4f2-08cc-4df8-bb31-31bdc4690de4.png)

**Comment by lucaderi** [comment]
They have been moved to clickhouse

**Comment by olmanolsztyn** [comment]
Does in 5.1 version is mandatory to migrate to clickhouse?

**Comment by MatteoBiscosi** [comment]
Hi @olmanolsztyn, yes we removed the support from nIndex, so please move to ClickHouse (it has both better space management and better performances)
