### ISSUE TITLE
FR: historical data from network

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#628]
hi
that would be interesting to have a history from a network and not only a host
sometimes I would like to get traffic from a network and not just a host

Nico

**Comment by simonemainardi** [comment]
![image](https://cloud.githubusercontent.com/assets/3397663/16414728/ac24de38-3d39-11e6-9cc3-53e255c71947.png)

![image](https://cloud.githubusercontent.com/assets/3397663/16414758/de552516-3d39-11e6-9556-9bcf7e31661d.png)

**Comment by Niko78** [comment]
it's not so easy in my case
I use all the the 192.168.0.0/16
... and I would like to see only 192.168.174.0/24 by exemple, do I need to change my ntop command in putting a biggest list in "--local-networks" ?

nico

**Comment by simonemainardi** [comment]
correct. Every network of interest has to be declared in the `local-networks` list. Clearly, if you wrap everything in a big `/16` you get the aggregate and not the breakdown.

**Comment by Niko78** [comment]
is it planned to improve that to have the possibility to sort and get only what we want instead of all ?
I ask that cause we use all the rfc1918 (around 500 networks) on my side and as you can imagine, I can't do that ... I would prefer a possibility to sort in history
thanks

**Comment by lucaderi** [comment]
An IP address has a meaning, is it not just a 32 bit number. I Agree with @simonemainardi that you need to define your networks. If they are 500, you will defined 500 networks, but delegate this (lazyness) to ntopng isn't the way to address this issue

**Comment by Niko78** [comment]
it's a not a "lazyness"... for sure I can add all these 500 networks in starting ntop
I will see how it reacts with all these lines...
