### ISSUE TITLE
ERROR: Missing required field 'alert_key'

### ISSUE THREAD

**Issue by olmanolsztyn** [ntop/ntopng#6280]
**Environment**:
   * OS name: FreeBSD
   * OS version: 12.2
   * Architecture: amd64
   * ntopng version/revision: ntopng Enterprise M v.5.1.220103

**What happened**:
Got many error "04/Feb/2022 13:58:45 [data.lua:10] [alert_consts.lua:411] ERROR: Missing required field 'alert_key' in alert_network_discovery_executed from /usr/local/share/ntopng/scripts/lua/modules/alert_definitions/other"

**What did you expect to happen?**
No errors in logs

**Comment by lucaderi** [comment]
I beige we have fixed this bug in the recent 5.3. Please update and report

**Comment by olmanolsztyn** [comment]
update fixed an issue.
