### ISSUE TITLE
LUA errors in Log for 5-minute rollup

### ISSUE THREAD

**Issue by Taralas** [ntop/ntopng#6284]
**Environment**:
* OS name: FreeBSD/OPNsense
* OS version: 12.1-RELEASE-p21-HBSD
* Architecture: amd64
* ntopng version/revision: 5.3.220207 [Enterprise/Professional build]
* Configuration file:
-i=igb0
-i=igb1
-w=0
-W=3000
-n=1
--community
-d=/var/db/ntopng-enterprise

**What happened**:
Generated the following log errors on a 5 minute cycle:
07/Feb/2022 09:55:00 [LuaEngine.cpp:562] WARNING: Script failure [/usr/local/share/ntopng/pro/scripts/callbacks/5minute/interface/top_sites.lua][...ng/pro/scripts/callbacks/5minute/interface/top_sites.lua:1: unexpected symbol near '<\135>']
07/Feb/2022 09:55:00 [ThreadedActivity.cpp:292] ERROR: Unable to load the Lua vm [igb1][vm: 5minute]

**What did you expect to happen?**
Not produce errors in normal operation.

**How did you reproduce it?**
Update to most recent version. Restart ntopng service

**Debug Information**:

**Comment by lucaderi** [comment]
- Please change it to "--community="
- what is the configuration file path ?

**Comment by Taralas** [comment]
Changed to --community= with the same result. Configuration is generated via the OPNsense UI integration based on the pkg.
Configuration is located at  /usr/local/etc/ntopng.conf

**Comment by lucaderi** [comment]
the config file is in /usr/local/etc/ntopng/ntopng.conf

**Comment by Taralas** [comment]
There is a generated version that is called by the service config integration at the above location. There is also a default located at /usr/local/etc/ntopng/ntopng.conf but it is not used.

**Comment by Taralas** [comment]
Followed the instructions at[ this location](https://www.ntop.org/guides/ntopng/third_party_integrations/opnsense.html#opnsenseintegration)

**Comment by Taralas** [comment]
Also seems like an error is being generated daily:
`01/Feb/2022 22:00:17 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/network_discovery.lua][attempt to ]`

This looks similar to the errors reported for pfSense, #5929

**Comment by lucaderi** [comment]
It should be fixed. Please wait 1 hour and update the packages. I will close the ticket: please reopen it if necessary

**Comment by Taralas** [comment]
Doesn't look like the packages ever flowed to the repo. Also, this problem seems to be in more than just the 5-minute roll-up. So far, the hourly is affected.
