### ISSUE TITLE
Multiple script issues with metrics roll-ups

### ISSUE THREAD

**Issue by Taralas** [ntop/ntopng#6285]
**Environment**:
* OS name: FreeBSD/OPNsense
* OS version: 12.1-RELEASE-p21-HBSD
* Architecture: amd64
* ntopng version/revision: 5.3.220207 [Enterprise/Professional build]
* Configuration file:
-i=igb0
-i=igb1
-w=0
-W=3000
-n=1
--community
-d=/var/db/ntopng-enterprise

**What happened**:
Please reference #6284. Problem was marked closed with no change in reported behavior.

Generated the following log errors on a 5 minute & hourly cycle:
```
07/Feb/2022 09:55:00 [LuaEngine.cpp:562] WARNING: Script failure [/usr/local/share/ntopng/pro/scripts/callbacks/5minute/interface/top_sites.lua][...ng/pro/scripts/callbacks/5minute/interface/top_sites.lua:1: unexpected symbol near '<\135>']
07/Feb/2022 09:55:00 [ThreadedActivity.cpp:292] ERROR: Unable to load the Lua vm [igb1][vm: 5minute]
```
```
07/Feb/2022 13:00:01 [LuaEngine.cpp:562] WARNING: Script failure [/usr/local/share/ntopng/pro/scripts/callbacks/hourly/interface/top_stats.lua][...png/pro/scripts/callbacks/hourly/interface/top_stats.lua:1: unexpected symbol near '<\135>']
07/Feb/2022 13:00:01 [ThreadedActivity.cpp:292] ERROR: Unable to load the Lua vm [igb1][vm: hourly]
```

Also, receiving the following error, and the ntopng process terminates.
```01/Feb/2022 22:00:17 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/network_discovery.lua][attempt to ]```

**What did you expect to happen?**
Would expect normal operation to not terminate on a LUA error, or generate logs.

**How did you reproduce it?**

**Debug Information**:

**Comment by lucaderi** [comment]
I have just tested on opnsense after the update and everything works as instructed. I believe you have not updated the package as requested. As of the errors above, they are here because you have not started ntopng in community mode. Please check if you config file looks like

root@opnsense:~ # cat /usr/local/etc/ntopng/ntopng.conf
-i=igb1
-m=192.168.3.0/24
-i=tcp://*:5556c
--zmq-publish-events=tcp://*:5557
-w=0
-W=3000
--community
-d=/var/db/ntopng-enterprise

**Comment by lucaderi** [comment]
The above warnings are already referenced in https://github.com/ntop/ntopng/issues/6286

**Comment by Taralas** [comment]
After updating to the nightly build, 5.3.220208, the problem is still occurring. Please reopen and address.

**Comment by Taralas** [comment]
After updating to the new nightly build, 5.3.220209, with https://github.com/ntop/ntopng/commit/de1c807f996be1810e5dcefb2c1ef7da8e78e558 included to fix, no change. Please reopen to address.
