### ISSUE TITLE
"Flow Drilldown" doesn't work after the migration to the Clickhouse

### ISSUE THREAD

**Issue by Yoshihiro-jp** [ntop/ntopng#6287]
**Environment**:
* OS name: [e.g. Ubuntu] Ubuntu
* OS version: [e.g. 18.04] 20.04.3 LTS
* Architecture: [e.g. amd64] x86_64
* ntopng version/revision: [e.g. 5.1.211223] 5.3.220207

**What happened**:
After migrating from the nIndex to the Clickhouse  the button of "Flow Drilldown" doesn't work.
![flowdrilldown_problem](https://user-images.githubusercontent.com/58843707/152907185-11c0e4ec-086c-4484-a5c7-59c667159c98.png)

**What did you expect to happen?**
After clicking the button of "Flow Drilldown" the screen should show the flow information about the application.

**How did you reproduce it?**
Just click the button of "Flow Drilldown".

regards,
Yoshihiro

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @Yoshihiro-jp a new build soon is going to be released with the right behavior, now when clicking the flow drilldown, you are going to be redirected to the ClickHouse page

**Comment by Yoshihiro-jp** [comment]
Dear @MatteoBiscosi 

I confirmed that it was fixed with below version.

Version:        5.3.220209 [Enterprise/Professional build]
GIT rev:        dev:d54fb4b3f09a886c97540d638a3450abafaaae5e:20220209
Pro rev:        r4750

Thank you very much.

regards,
Yoshihiro

**Comment by MatteoBiscosi** [comment]
Verified as Fixed
