### ISSUE TITLE
Error when compiling version 2.4 stable

### ISSUE THREAD

**Issue by jppo** [ntop/ntopng#629]
Hello,
## I try to compile the 2.4 version and I get an error compiling, here is the end of trace 

src/CollectorInterface.cpp: In constructor ‘CollectorInterface::CollectorInterface(const char_)’:
src/CollectorInterface.cpp:32:25: error: ‘zmq_ctx_new’ was not declared in this scope
   context = zmq_ctx_new();
                         ^
src/CollectorInterface.cpp:50:25: error: ‘zmq_ctx_destroy’ was not declared in this scope
  zmq_ctx_destroy(context);
                         ^
src/CollectorInterface.cpp:58:25: error: ‘zmq_ctx_destroy’ was not declared in this scope
  zmq_ctx_destroy(context);
                         ^
src/CollectorInterface.cpp:68:25: error: ‘zmq_ctx_destroy’ was not declared in this scope
  zmq_ctx_destroy(context);
                         ^
src/CollectorInterface.cpp: In destructor ‘virtual CollectorInterface::~CollectorInterface()’:
src/CollectorInterface.cpp:92:26: error: ‘zmq_ctx_destroy’ was not declared in this scope
   zmq_ctx_destroy(context);
                          ^
src/CollectorInterface.cpp: In member function ‘void CollectorInterface::collect_flows()’:
src/CollectorInterface.cpp:127:59: error: cannot convert ‘zmq_msg_hdr_’ to ‘zmq_msg_t_’ for argument ‘2’ to ‘int zmq_recv(void_, zmq_msg_t_, int)’
  size = zmq_recv(items[source_id].socket, &h, sizeof(h), 0);
                                                           ^
src/CollectorInterface.cpp:136:66: error: cannot convert ‘char_’ to ‘zmq_msg_t_’ for argument ‘2’ to ‘int zmq_recv(void_, zmq_msg_t*, int)’
  size = zmq_recv(items[source_id].socket, payload, payload_len, 0);
                                                                  ^
Makefile:129: recipe for target 'src/CollectorInterface.o' failed
## make: **\* [src/CollectorInterface.o] Error 1

I enclose the complete listing.

Regards

JP P
[LOG.MAKE.txt](https://github.com/ntop/ntopng/files/336876/LOG.MAKE.txt)

**Comment by lucaderi** [comment]
Please check https://github.com/ntop/ntopng/blob/dev/doc/README.compilation about ZMQ dependencies

**Comment by jppo** [comment]
Hello Luca, 

I read carefully the compilation doc and verify that all packages are well installed with "dpkg-query -l ", 
all the packages in the doc where OK. 
After a little search I get the trick, the doc is not OK and the dev package to install for libzmq is : 
libzmq3-dev 
which supersede (and remove) libzmq-dev 

After that little tuning the compilation goes to end. 

Regards 

JP Pozzi
