### ISSUE TITLE
Implemenent MAC Addresses on View Interfaces

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6290]
View interfaces do not support MAC addresses even if they are present in the original interfaces. This needs to be implemented.

it can be reproduced with ntopng -i ethX -i view:all

**Comment by MatteoBiscosi** [comment]
Implemented as requested, now mac address is shown on both host and flows info
![Screenshot from 2022-02-09 19-33-10](https://user-images.githubusercontent.com/49585191/153266978-6e405dac-8fce-4c11-bae4-9dd7cc95809e.png)
![Screenshot from 2022-02-09 19-33-53](https://user-images.githubusercontent.com/49585191/153266984-4915fd2b-d38f-48a8-b8d9-f8268737ade2.png)
