### ISSUE TITLE
MINING "NOT" DETECTED

### ISSUE THREAD

**Issue by gilinuxIT** [ntop/ntopng#6293]
I just found two miners on a customers network. NTOPNG  did "not" flag this traffic as being mining traffic. The only reason it caught my attention was because the destination traffic going to China. Can you please flag this IP as mining traffic?
![20220208_102820](https://user-images.githubusercontent.com/54428336/153058928-d69d1ef7-e14e-4c2d-8386-bfa528b410f3.jpg)
![20220208_102825](https://user-images.githubusercontent.com/54428336/153058932-9aa433dd-2a2c-4d38-ada7-d0c626d09fb9.jpg)
![miner](https://user-images.githubusercontent.com/54428336/153058935-abf438bd-c9e0-4101-bcc7-e5b34b373fec.png)
![destination](https://user-images.githubusercontent.com/54428336/153058936-61fdf929-4e66-4f69-abd6-ff8169ea8b0f.png)
![gui](https://user-images.githubusercontent.com/54428336/153058938-1d54ddb4-3a19-4bcf-8754-22f292481289.png)

**Comment by lucaderi** [comment]
We do not detect dogecoin traffic in nDPI as we have no pcap trace. Please attach or send me via email (deri at ntop.org) a trace I can use for development.

**Comment by gilinuxIT** [comment]
The mining rig was taken offline, not able to do PCAP. If I come across another one I will run a PCAP and send it your way.  Thank you.
