### ISSUE TITLE
Allow download of PCAP in Historical Flows Explorer (using the actual time interval and filters)

### ISSUE THREAD

**Issue by mikulov** [ntop/ntopng#6294]
Hello.

1. I've selected specific host by IP. We can see "First / Last Seen" and "Traffic Sent / Received":

![image](https://user-images.githubusercontent.com/26163961/153121960-04251e99-2b44-41fb-a1a2-d313e0e185b7.png)

2. When I press on icon "Historical Data" on the same host i've selected recently - and set filter for last week - i have no data at all, where i can see the actual sent/rcvd usage and download pcap:

![image](https://user-images.githubusercontent.com/26163961/153122677-dc63d57b-70c2-4e6c-8ef8-336e768ac8c1.png)

3. When I go to "Historical Flow Exporter" Dashboard, filter by the IP of the same specific host and last week range, i can see the flows. But it's useless, because i can't see usage or download pcap for selected range (not single flows):

![image](https://user-images.githubusercontent.com/26163961/153123226-f3563800-383b-4700-b7fa-467092ee6fbc.png)

**Comment by MatteoBiscosi** [comment]
Hi @mikulov could you please try to reduce the window of the timeseries to a close date seen from the historical flow explorer?

**Comment by mikulov** [comment]
> Hi @mikulov could you please try to reduce the window of the timeseries to a close date seen from the historical flow explorer?

If I understand you right, you asked to reduce the time range. Here instead of 1 week - 1 day:

**Historical Flow Explorer**

![image](https://user-images.githubusercontent.com/26163961/153171614-a2fc7a99-fb94-470f-9923-c91090b912a1.png)

**Historical Data**

![image](https://user-images.githubusercontent.com/26163961/153172227-4bb9e13b-9161-4d4d-b4cf-58bcbaaf5324.png)

**Comment by mikulov** [comment]
And this is a configuration file, may be there is an issue:

```ubuntu@ntop:~$ cat /etc/ntopng/ntopng.conf
-G=/var/run/ntopng.pid
-i=eth0
-i=syslog://127.0.0.1:9999
--local-networks="10.110.0.0/16,10.120.0.0/16,10.130.0.0/16"

-X=400000
-F="clickhouse;127.0.0.1;ntopng;flows;default;"

**Comment by cardigliano** [comment]
If I understand correctly, what you need is the ability to download a PCAP with traffic matching the selected time interval and the selected filter. This is not available, but it looks like a useful feature.

**Comment by mikulov** [comment]
> If I understand correctly, what you need is the ability to download a PCAP with traffic matching the selected time interval and the selected filter. This is not available, but it looks like a useful feature.

Thank you for answer, Alfredo.

Well, we actually first thing - want to get such graphic instead of empty screen with error "no results found", when they are present (you can see screenshots above). And here an example of what we want to see (we had it before upgrading):

![image](https://user-images.githubusercontent.com/26163961/153210740-b1620cdc-0c19-48fc-b907-521ba0abf292.png)

And the second, we want to download pcap file via rest API for analyzing in wireshark but for specific host. I think it's in documentation:
https://www.ntop.org/guides/ntopng/advanced_features/live_pcap_download.html

What is the difference between this:

`http://<ntopng IP>:3000/lua/rest/v2/get/pcap/live_traffic.lua?ifid=<interface index>&host=<host IP>`

and this:

`https://dpi.monogoto.io/lua/rest/get/pcap/live_extraction.lua?ifid=1&epoch_begin=1643729695&epoch_end=1643731495`

Is it possible to get pcap, with time interval and specific host?

Thank you in advance.

**Comment by mikulov** [comment]
@cardigliano 

I don't see the data on that graph, and I am not sure it's a feature request...

![image](https://user-images.githubusercontent.com/26163961/153745078-128a05a3-79b7-4e99-83f9-86c4e1025815.png)

**Comment by cardigliano** [comment]
> And the second, we want to download pcap file via rest API for analyzing in wireshark but for specific host. I think it's in documentation: https://www.ntop.org/guides/ntopng/advanced_features/live_pcap_download.html
> 
> What is the difference between this:
> 
> `http://<ntopng IP>:3000/lua/rest/v2/get/pcap/live_traffic.lua?ifid=<interface index>&host=<host IP>`
> 
> and this:
> 
> `https://dpi.monogoto.io/lua/rest/get/pcap/live_extraction.lua?ifid=1&epoch_begin=1643729695&epoch_end=1643731495`
> 
> Is it possible to get pcap, with time interval and specific host?
> 
> Thank you in advance.

live_traffic.lua captures traffic from the interface directly, this should be used to get a small pcap from the live traffic on the interface.

live_extraction.lua extracts traffic from the recorded pcaps, this can be used with a time interval (epoch_begin/epoch_end parameters) and a BPF filter (bpf_filter parameter) like "host 10.0.0.1"

**Comment by cardigliano** [comment]
> I don't see the data on that graph, and I am not sure it's a feature request...

It may take a while (few minutes) to get charts for an host if you just started ntopng, otherwise there is some issue

**Comment by cardigliano** [comment]
PCAP download (direct or scheduled) from Historical Flows Explorer, honouring the selected filters,  has been implemented and tested
