### ISSUE TITLE
Is that possible to record and download traffic (pcap) within a range from "now" and 10 minutes ahead using API?

### ISSUE THREAD

**Issue by mikulov** [ntop/ntopng#6296]
And please, how can I add specific host to it, using bpf_filter?
Can I use the same live_extraction.lua or for future traffic recording it's another script?

`lua/rest/get/pcap/live_extraction.lua?ifid=1&epoch_begin=1643729695&epoch_end=1643731495`

Thank you in advance.

**Comment by cardigliano** [comment]
PCAP traffic is recorded on disk and available after a few minutes. Only data which is already on disk can be extracted. Thus in order to download traffic for the next 10 minutes, you should wait 10+ minutes and extract the traffic.

**Comment by cardigliano** [comment]
As of the filter, that endpoint accepts a time interval (epoch_begin/epoch_end parameters) and a BPF filter (bpf_filter parameter), to filter for a specific host bpf_filter should be set to something like "host 10.0.0.1"
