### ISSUE TITLE
Checks script errors

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6297]
When going to add DHCP, DNS, and other services as part of the setup (page is /lua/admin/edit_configset.lua?subdir=flow&search_script=unexpected#disabled) getting the following errors:

![image](https://user-images.githubusercontent.com/4493366/153247966-bfba028e-ff5b-40f1-ad9f-cf14ef813542.png)

You can reproduce it with the community edition

**Comment by MatteoBiscosi** [comment]
Fixed with 57a85de50e574198050295e7880778d2c52b880c

**Comment by lucaderi** [comment]
Verified as fixed
