### ISSUE TITLE
Top Clients/Servers with filter per exporter device and interface in Historical Flow Explorer page

### ISSUE THREAD

**Issue by Niklasr69** [ntop/ntopng#6299]
**What would you like to add or change?**:
The possibility to add exporter and interface filters when choosing Top Client/Server in the Historical Flow Explorer page.

**Why do you and others need this?**:
In order to easily find top talkers for a particular exporter, it is necessary to be able to filter out.
Top talkers for the whole network are not so interesting when you have large networks.

**Comment by Niklasr69** [comment]
looks very nice.
Need to check a bit more before closing the issue.

**Comment by lucaderi** [comment]
Verified as fixed
