### ISSUE TITLE
footer line is not updated when looking a collector interface

### ISSUE THREAD

**Issue by sclark46** [ntop/ntopng#63]
ntopng Community v.2.0.150619
I have two ntopng instances on separate systems - with one acting as collector. The collector does not
update the bps in the footer. 
0 bps [0 pps]
Uptime: 10 min, 52 sec
800 Hosts  4,206 Flows
also I don't see top talker graph.
If I do a tcpdump on port 3456 - the port I am using send the data on - I see a lot of traffic bewteen the
two ntopng systems.

on the sender I see
18.67 Mbps [6,521 pps]
Uptime: 29 min, 46 sec
1,501 Hosts 1,368 Aggregations 6,748 Flows
So there is plenty of data - 

but the collector show very little
Name	tcp://10.0.133.87:3456	
  Save Name
Family	zmq
Bytes	
6.00 KB

**Comment by lucaderi** [comment]
@sclark46 Can you please send the command line you used to start all apps?

**Comment by sclark46** [comment]
Welcome to ntopng x86_64 v.2.0.150619
sudo /usr/local/bin/ntopng -U ntop -ip4p1 -D all -E all -A 2 -H -n 1 -F"es;flows;ntopng2-%Y.%m.%d;http://localhost:9200/_bulk" -d/var/lib/ntop -w 3000 -n 1 -m 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12 -B "not host 10.0.133.88 or not host 192.168.198.46" -i tcp://10.0.133.87:3456 --community

Welcome to ntopng i686 v.2.0.150619
sudo /usr/local/bin/ntopng -U ntop -ieth0 -ip4p4 -D all -E all -A 2 -H -n 1 -F"es;flows;testntopng2-%Y.%m.%d;http://localhost:9200/_bulk" -d/var/lib/ntop -1/usr/share/ntopng/httpdocs -w 3000 -n 1 -m 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12 -I "tcp://*:3456"

Also I am seeing these errors on the collector:
19/Jun/2015 12:22:54 [src/CollectorInterface.cpp:92] Collecting flows on tcp://10.0.133.87:3456
19/Jun/2015 12:23:42 [src/Lua.cpp:4762] WARNING: Script failure [/usr/share/ntopng/scripts/lua/iface_flows_sankey.lua][/usr/share/ntopng/scripts/lua/iface_flows_sankey.lua:115: attempt to compare number with nil]
19/Jun/2015 12:23:47 [src/Lua.cpp:4762] WARNING: Script failure [/usr/share/ntopng/scripts/lua/iface_flows_sankey.lua][/usr/share/ntopng/scripts/lua/iface_flows_sankey.lua:115: attempt to compare number with nil]

**Comment by lucaderi** [comment]
@sclark46 I am unable to reproduce it but I have done this https://github.com/ntop/ntopng/commit/3d8f3ac92712448317810998555765e58aa1f5dd in case it helps

**Comment by sclark46** [comment]
Don't see any change from latest update. But I did determine that if I don't write flows to Elasticsearch on the sender - I get data on the collector.

© 1998-2015 - ntop.org 
Generated by ntopng Community v.2.0.150622 
for user admin and interface tcp://10.0.133.87:3456
Upgrade to Professional version
0 bps [0 pps]
Uptime: 1 min, 20 sec
445 Hosts  2,367 Flows

**Comment by sclark46** [comment]
Are there plans to allow using ntopng to send data to another ntopng as well as Elasticsearch at the same time?

**Comment by ariava** [comment]
@sclark46 ntopng-to-ntopng interaction is planned but not available yet. Have you tried 8a300cd which @lucaderi pushed some time ago?

**Comment by lucaderi** [comment]
@ariava @sclark46 I think you should read this: http://www.ntop.org/ntopng/creating-a-hierarchical-cluster-of-ntopng-instances/

**Comment by sclark46** [comment]
Again - ntopng -> ntopng works OK as long as I don't have the sending ntopng also sending flows to elasticsearch. Let me add I haven't had a chance to test this with any recent versions. If it still is a problem I will open a new issue.
