### ISSUE TITLE
Use the same range picker component in all pages

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#6301]
The Interface -> Historical chart and other pages are using an old-style range picker component. It is requested to use the same component implemented for the Historical Flows and Alerts page

<img width="1140" alt="Screen Shot 2022-02-11 at 13 00 14" src="https://user-images.githubusercontent.com/7548711/153587896-85c1e403-cc70-4123-a2f0-25d4ee81ee81.png">

**Comment by NicoMaio** [comment]
Verified as fixed.
