### ISSUE TITLE
Script Error on Startup: epoch_begin

### ISSUE THREAD

**Issue by Taralas** [ntop/ntopng#6302]
**Environment**:
* OS name: OPNsense/FreeBSD
* OS version: 21.10.3
* Architecture: amd64
* ntopng version/revision: 5.3.220210 [Enterprise/Professional build]

**What happened**:
On start of ntopng, following is recorded in ntopng.log:
```10/Feb/2022 07:21:01 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][.../local/share/ntopng/scripts/lua/modules/format_utils.lua:250: attempt to perform arithmetic on a nil value (local 'epoch_begin')]
10/Feb/2022 07:22:02 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][.../local/share/ntopng/scripts/lua/modules/format_utils.lua:250: attempt to perform arithmetic on a nil value (local 'epoch_begin')]
```

**What did you expect to happen?**
Would not expect errors on normal startup

**How did you reproduce it?**
Fresh install of ntopng from pkg repo, with following config:
```-i=igb0
-i=igb1
-m=192.168.1.0/24
-w=0
-W=3000
-n=1
--community=
-d=/var/db/ntopng-enterprise
```

Login to the console, or via ssh.

tail -f /var/db/ntopng-enterprise/ntopng.log

Restart ntopng.

**Debug Information**:
N/A

**Comment by MatteoBiscosi** [comment]
Hi @Taralas, you don't have to put the = after the `--community` option.
Other than that, do you open the web gui, navigate somewhere or does it just pop up when you start ntopng?

**Comment by Taralas** [comment]
Also tried with 5.3.220211 with same result.

**Comment by Taralas** [comment]
Check the Discord conversation from lucaderi:

***@***.***

That is now generated via the UI, per his request. Pull for that was incorporated Monday, I believe.

On the error, that is being logged to /var/db/ntopng-enterprise/ntopng.log

**Comment by MatteoBiscosi** [comment]
Hi @Taralas yes, but from where does it appear, I mean, does it appear after clicking Alert? or Interface? How can I reproduce it?

**Comment by Taralas** [comment]
Login to the console, or via ssh.

tail -f /var/db/ntopng-enterprise/ntopng.log

Restart ntopng.

**Comment by MatteoBiscosi** [comment]
Hi @Taralas unfortunately i was not able to reproduce your behavior. However I added a security check (it was missing) to fix the date. In a few hours a new build should be available, please update and let me know if it still persists.

**Comment by Taralas** [comment]
Looks good. Please feel free to close the ticket.

**Comment by MatteoBiscosi** [comment]
Verified as Fixed
