### ISSUE TITLE
Script Error: blog_utils.lua attempt to call a nil value (field 'empty')

### ISSUE THREAD

**Issue by Taralas** [ntop/ntopng#6303]
**Environment**:
* OS name: OPNsense/FreeBSD
* OS version: 21.10.3
* Architecture: amd64
* ntopng version/revision: 5.3.220210 [Enterprise/Professional build]

**What happened**:
At local midnight, following is recorded in ntopng.log:
```11/Feb/2022 00:01:44 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/daily-delayed/system/fetch_blog_feed.lua][/usr/local/share/ntopng/scripts/lua/modules/blog_utils.lua:136: attempt to call a nil value (field 'empty')]
```

**What did you expect to happen?**
Would not expect errors on normal midnight rollover

**How did you reproduce it?**
Fresh install of ntopng from pkg repo, with following config:
```-i=igb0
-i=igb1
-m=192.168.1.0/24
-w=0
-W=3000
-n=1
--community=
-d=/var/db/ntopng-enterprise
```
Clear current blog entries from alert, allow to run periodic daily scripts.

**Debug Information**:
N/A

**Comment by Taralas** [comment]
Also checked with 5.3.220211, same result.

**Comment by MatteoBiscosi** [comment]
Hi @Taralas the problem should be fixed now, please let me know.

**Comment by Taralas** [comment]
Will check once the nightly build is released. Thank you for taking a look at this!

**Comment by MatteoBiscosi** [comment]
Verified as Fixed
