### ISSUE TITLE
Missing HTTP URL from Alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6311]
![image](https://user-images.githubusercontent.com/4493366/153945019-3b10e5a9-6555-48de-a805-37e9d96aab87.png)
In the case of alerts based on HTTP, the URL should be reported. For TLS, the SNI should be reported.

**Comment by MatteoBiscosi** [comment]
Fixed in the latest version
![Screenshot from 2022-04-12 11-53-50](https://user-images.githubusercontent.com/49585191/162933718-2100b8ba-f437-4ae5-a9c2-16e73687e709.png)

**Comment by lucaderi** [comment]
Verified as fixed
