### ISSUE TITLE
Alert not visible for http basic auth flow

### ISSUE THREAD

**Issue by fastfire** [ntop/ntopng#6314]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04
* Architecture: amd64
* ntopng version/revision: 5.2.220211-16846

**What happened**:
We tried a simulation of access to an http basic authentication. The flow is visible from the NTOP interface. The "Clear-Text Credentials" check is active without any exception. No alert has been generated regarding this action.

**What did you expect to happen?**
An alert should be generated.

**How did you reproduce it?**
Connect to http://93.230.52.168/cgi-bin/guestimage.html

**Debug Information**:
pcap file attached [93.230.52.168.pcap.txt](https://github.com/ntop/ntopng/files/8067953/93.230.52.168.pcap.txt)
On February 15, 2021, from 9 to 11, in the Telegram channel ntop_community, @martin_scheu was provided with various information on this issue.

**Comment by martinscheu** [comment]
the pcap:
[93.230.52.168.pcap.zip](https://github.com/ntop/ntopng/files/8069069/93.230.52.168.pcap.zip)
it works on my test VM, Version, [ntopng Community v.5.3.220215 (Ubuntu 20.04.3 LTS)]
<img width="1597" alt="Screenshot 2022-02-15 at 10 48 46" src="https://user-images.githubusercontent.com/38549755/154063037-0dfa870a-dcdc-4e5d-a41c-a9ea705bf227.png">
<img width="1588" alt="Screenshot 2022-02-15 at 09 45 20" src="https://user-images.githubusercontent.com/38549755/154063090-2f572d32-bff4-409d-86f3-43639cee67db.png">

**Comment by lucaderi** [comment]
![Screen Shot 2022-04-25 at 09 18 56](https://user-images.githubusercontent.com/4493366/165039387-60f6b392-6026-4ab1-8659-f1da286fd66d.png)

It works with the current version. Please remember that as the pcap file is dated 02/15/2022 to mke sure your GUI displays  such date
