### ISSUE TITLE
[Range Picker Component] Filters are not sticky

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6316]
Inside a host clicking on the blue button
![Screen Shot 2022-02-15 at 14 59 36](https://user-images.githubusercontent.com/4493366/154077536-fc091dfb-17f2-4e51-80c9-91c566b3d77e.png)
ntopng jumps to (that's correct)
![image](https://user-images.githubusercontent.com/4493366/154077612-5bab2e85-5001-4147-bec3-759937cc9d2b.png)
that can be used to investigate for instance who has talked with this host
![Screen Shot 2022-02-15 at 15 00 07](https://user-images.githubusercontent.com/4493366/154077674-5925ac7c-b297-4377-8841-aeb6cfcb0b13.png)
Unfortunately changing the dropdown menu (for instance to conversations) the filter selection is lost pushing to start over. This needs to be fixed and the filter has to be sticky

**Comment by cardigliano** [comment]
Fixed, this seems to be working after moving to the new range picker component
