### ISSUE TITLE
Graphs - The query is taking a long time to complete

### ISSUE THREAD

**Issue by MirekVlach** [ntop/ntopng#6317]
Raspbian GNU/Linux 10 (buster)
ntopng armv7l v.5.3.220213

Unable to display any graphs now.

![image](https://user-images.githubusercontent.com/99751855/154140509-336c41ec-00c4-43ea-99fb-8e4eb10735db.png)

Following error is shown in the console

![image](https://user-images.githubusercontent.com/99751855/154140331-e693207c-a092-442b-bd2e-95d1c674e76b.png)

Please advise

**Comment by MatteoBiscosi** [comment]
Hi @MirekVlach this issue was fixed with the 220214 version, please update and let me know

**Comment by MatteoBiscosi** [comment]
Verified as Fixed
