### ISSUE TITLE
ntopng exits (crashes?) after loading historical data page (Ubuntu 12.04 from repo)

### ISSUE THREAD

**Issue by beveradb** [ntop/ntopng#632]
Hi,

Whenever I load the historical data page for an interface, it loads but then seems to crash ntopng and I have to restart it:

```
root@fwws:~# service ntopng status
ntopng running as 20541

(load http://localhost:3000/lua/if_stats.lua?id=0&page=historical#historical-top-talkers in web browser)

root@fwws:~# service ntopng status
ntopng is not running
```

I've attached the last 2 seconds of the verbose log file, which I believe covers from me clicking the historical reports / graph tab to it exiting.
No more log entries are added to the log file after the last line in the attached log file until I restart the ntopng daemon.

[ntop-verbose-log-crash.txt](https://github.com/ntop/ntopng/files/339215/ntop-verbose-log-crash.txt)

Any suggestions would be greatly appreciated - viewing historical data is the most important thing for our use case!

Thanks a lot,
Andrew

**Comment by simonemainardi** [comment]
@andrewthecoder please enclose the full ntopng startup line. In addition, are you able to generate a core dump and upload it along with ntopng binary?

**Comment by beveradb** [comment]
Never mind, I've upgraded to the latest nightly rather than the stable build and this no longer occurs.

Thanks anyway!
