### ISSUE TITLE
Owner-writable permissions are expected for `/share` directory

### ISSUE THREAD

**Issue by abbradar** [ntop/ntopng#6321]
**Environment**:
* OS name: NixOS
* OS version: Unstable
* Architecture: amd64
* ntopng version/revision: 5.2.1

**What happened**:
Ntopng crashes during startup with this error log (two out-of-place lines are my added `printf`s, will be explained later):
```
setting data_dir to /var/lib/ntopng
16/Feb/2022 17:09:24 [Prefs.cpp:1249] ntopng will use redis /run/redis-ntopng/redis.sock@0
changing data_dir to /nix/store/140zx9kh4dr9jsr5d1bizp0igz60l0yg-ntopng-5.2.1/share/ntopng
16/Feb/2022 17:09:24 [Ntop.cpp:345] ERROR: Invalid directory /nix/store/140zx9kh4dr9jsr5d1bizp0igz60l0yg-ntopng-5.2.1/share/ntopng specified
```

Looking at [`Ntop.cpp:345`](https://github.com/ntop/ntopng/blob/3bf9ac9e147e9384eea110f75c4c0808fc723c02/src/Ntop.cpp#L345), `prefs->data_dir` directory is checked to have owner writable bit set.

Looking at `Prefs.cpp`, there are two lines where `data_dir` is set:

* [The first one](https://github.com/ntop/ntopng/blob/3bf9ac9e147e9384eea110f75c4c0808fc723c02/src/Prefs.cpp#L53), where it's set to default data directory. It's defined in [ntop_defines.h](https://github.com/ntop/ntopng/blob/3bf9ac9e147e9384eea110f75c4c0808fc723c02/include/ntop_defines.h#L531) to be `"/var/lib/ntopng"` -- so far so good;
* [The second](https://github.com/ntop/ntopng/blob/3bf9ac9e147e9384eea110f75c4c0808fc723c02/src/Prefs.cpp#L1801), where `data_dir` is made equal to `install_dir`. `install_dir` is determined [here](https://github.com/ntop/ntopng/blob/3bf9ac9e147e9384eea110f75c4c0808fc723c02/src/Ntop.cpp#L157) from `dirs`. Looking at `dirs` [here](https://github.com/ntop/ntopng/blob/3bf9ac9e147e9384eea110f75c4c0808fc723c02/src/Ntop.cpp#L39), its default value is taken from `--prefix` `./configure` option.

To check that my understanding is correct, I added `printf`s to log new values of `data_dir` and indeed, at some point it's set to Ntopng installation dir, which is not supposed to be writable.

**What did you expect to happen?**
Ntopng doesn't expect `/share` directory to have owner writable bit set. On other distributions this bit is usually set, but the directory is owned by `root` -- that's why Ntopng usually works correctly. On NixOS, however, all application directories have 444 permissions, and Ntopng crashes.

If my understanding is correct, the fix is to just drop check at [`Ntop.cpp:345`](https://github.com/ntop/ntopng/blob/3bf9ac9e147e9384eea110f75c4c0808fc723c02/src/Ntop.cpp#L345).

**How did you reproduce it?**
Start Ntopng when `/share` directory doesn't have owner writable bit set.

**Comment by lucaderi** [comment]
Thank you !
