### ISSUE TITLE
Alert filters are not working

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6324]
![Screen Shot 2022-02-16 at 23 18 54](https://user-images.githubusercontent.com/4493366/154366979-f12463a5-848b-45c8-aee8-52acca3a056e.png)

This bug has been reproduced with ClickHouse that produced this SQL query

 SELECT 4 entity_id, (toUnixTimestamp(tstamp_end) - toUnixTimestamp(tstamp)) duration, * FROM `flow_alerts` WHERE ( alert_status = 0 ) AND (tstamp >= 1645048173 AND tstamp <= 1645049973) AND ((l7_proto = 7 OR l7_master_proto = 7) OR (l7_proto = 7 OR l7_master_proto = 7)) AND (interface_id = 2)  ORDER BY tstamp asc LIMIT 10 OFFSET 0

**Comment by cardigliano** [comment]
@uccidibuti I was able to reproduce this by adding 2 filters with the same field (then removing one), I thnk this will be fixed as soon as you fix the "multiple fields" case

**Comment by cardigliano** [comment]
The double l7_proto filter in SQL has been fixed in d527b8834788bcc328001c6f545aff970d7c4de0
