### ISSUE TITLE
Implement portscan detector check

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6327]
Implement portscan detection alert. Use https://github.com/markofu/pcaps/blob/master/PracticalPacketAnalysis/ppa-capture-files/portscan.pcap as example

**Comment by lucaderi** [comment]
Depends on https://github.com/ntop/ntopng/issues/6684

**Comment by lucaferret** [comment]
Using nmap to perform a port scan, for either tcp or udp, triggers a "Scan Detected" alert.

TCP port scan command -> 'nmap -p80,90-400,443-3000,3080 -A -T4 {host}'

UDP port scan command -> 'sudo nmap -sU -p U:53,111,137,12000-1280 -T4 {host}'
