### ISSUE TITLE
Clickhouse Database Missing Flow Table

### ISSUE THREAD

**Issue by kerrymilestone** [ntop/ntopng#6329]
**Environment**:
* OS name: Ubuntu
* OS version: Focal LTS 20.04.3 (current)
* Architecture: amd64
* ntopng version/revision: ntopng Enterprise M v.5.2.220217 

**What happened**:
I see
` [ClickHouseImport.cpp:91] WARNING Received exception from server (version 22.1.3): Code: 60. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Table ntopng.flows doesn't exist.`
 
for most things.

**What did you expect to happen?**
That there is a table created the first time ntop is started with -F clickhouse

**How did you reproduce it?**
Reinstall of purged clickhouse server (not ntopng).  ntopng was previously running with nindex.  provided migration script fails, due to missing flows table.

more or less default install, with a different data location in clickhouse xml set 

    
    <path>/***/clickhouse/</path>

ntopng also has data logging to non default location.  Alerts are being written and read to clickhouse database.

USE ntopng
Query id: 3b9ef00f-9172-*-9434-
Ok.
0 rows in set. Elapsed: 0.001 sec.
*** :) show tables;
SHOW TABLES
Query id: bac15600-*-45d2-9b07
┌─name─────────────────────┐
│ active_monitoring_alerts │
│ all_alerts               │
│ flow_alerts              │
│ host_alerts              │
│ interface_alerts         │
│ mac_alerts               │
│ network_alerts           │
│ snmp_alerts              │
│ system_alerts            │
│ user_alerts              │
└──────────────────────────┘
10 rows in set. Elapsed: 0.005 sec.

**Comment by MatteoBiscosi** [comment]
Hi @kerrymilestone could you please share your ntopng --version output?
