### ISSUE TITLE
Non-admin users authetificated through RADIUS can't access Historical Flow Explorer

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#6330]
**Environment**:
* OS name: CentOS Linux release
* OS version: 8.5.2111
* Architecture: amd64
* ntopng version/revision: ntopng Enterprise L v.5.2.220215

**What happened**:
Non-admin users authetificated through RADIUS can't access Historical Flow Explorer, no this item in the menu.
Bul internal non-admin users created inside ntopng can access it.

**What did you expect to happen?**
Non-admin users authetificated through RADIUS can access Historical Flow Explorer

**How did you reproduce it?**
Login by non-admin user authetificated through RADIUS server

**Debug Information**:
RADIUS non-admin 
![image](https://user-images.githubusercontent.com/67421019/154620180-d5105d7c-aac0-4922-b4c6-d2e532440cad.png)

Internal non-admin
![image](https://user-images.githubusercontent.com/67421019/154620422-aa51b559-21e2-41ce-a036-e18dff5eaaa9.png)

**Comment by lucaderi** [comment]
Can you please report how your radius non-admin users are configured?

**Comment by atemix** [comment]
Hi, Luca

Radius users configured through Cisco ISE

ISE policy for ntopng
![image](https://user-images.githubusercontent.com/67421019/154645953-ac2d581e-7768-46c1-b1d6-da3abc37fc64.png)

User profile
![image](https://user-images.githubusercontent.com/67421019/154646221-0d72af53-0966-46bc-a28e-5d33336d82b6.png)

Admin profile
![image](https://user-images.githubusercontent.com/67421019/154646155-18e71153-1cfc-4906-a09c-811d126680ff.png)

Ntopng config
![image](https://user-images.githubusercontent.com/67421019/154646338-2d334abd-c5a1-405c-a57b-758babc331ec.png)

**Comment by MatteoBiscosi** [comment]
Hi @atemix currently non-admin users cannot access historical flow explorer, only admins can. This was a wanted situation, in fact users are going to manipulate data on the database and we decided to just add the possibility to check this data by admins in order to avoid non-wanted situations.

**Comment by atemix** [comment]
But why non-admin local users can access historical flow eplorer?
Second screenshot in first message.

Non-admin local user and authenticated through raduis non-admin user are not equal?

**Comment by MatteoBiscosi** [comment]
@atemix Could you please tell me how you configured your non-admin user? I tried right now to configure a non admin user and it cannot access historical flow explorer page

**Comment by atemix** [comment]
@MatteoBiscosi Just created non priviledged user.

![image](https://user-images.githubusercontent.com/67421019/154657493-4ddbe978-3272-406e-a2fc-51db563b132b.png)
![image](https://user-images.githubusercontent.com/67421019/154657794-30e323a3-759c-4e6f-8e38-9f3c8f411c75.png)

**Comment by MatteoBiscosi** [comment]
Hi @atemix, try to update now. I added a check and now non admin users shouldn't access clickhouse, please let me know if everything works fine

**Comment by atemix** [comment]
@MatteoBiscosi Is it possible to add configurable parameter to preferences in menu or config file to allow users access to historical flow explorer? In our case we need users can access hoistorical flows by themselves.

**Comment by MatteoBiscosi** [comment]
Added the ability to create and edit non admin user with the ability to check historical flow page 
![Screenshot from 2022-04-07 12-43-01](https://user-images.githubusercontent.com/49585191/162181806-c2de4853-40d3-41e8-a6b9-f14d82184635.png)
