### ISSUE TITLE
Broken/Unpleasant Flow Layout

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6331]
![Screen Shot 2022-02-18 at 12 38 25](https://user-images.githubusercontent.com/4493366/154675746-439e5a59-70de-4b3e-87bd-abea566e093d.png)
![Screen Shot 2022-02-18 at 12 38 13](https://user-images.githubusercontent.com/4493366/154675795-0d28e822-9d3c-48d8-b0e4-6e219cc0f9f8.png)

**Comment by MatteoBiscosi** [comment]
It Should be fixed with the latest release and update to latest datatables.net module

**Comment by lucaderi** [comment]
Verified as fixed
