### ISSUE TITLE
ECS fields mapping

### ISSUE THREAD

**Issue by AlessioPaternoster** [ntop/ntopng#6337]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04.3 LTS
* Architecture: x86_64
* ntopng version/revision: v.5.2.220215 rev.16878
* ELK version: 7.15.0
  
**What happened**:
As a security team, we are trying to map ntopng alerts into Elasticsearch to be compliant to ECS schema.   
Currently, only a small subset of ntopng alerts fields are in ECS format. Examples are `source.ip`, `network.protocol`, `event.type`, ecc..   
Other ntopng alerts properties are not in ECS format. All these properties are nested under the `message` field.
The `message` field, also, does not seem to be a valid JSON object and cannot be parsed directly by Elasticsearch.
Moreover, some fields are not always consistent. Sometimes these fields are qualified (es. `cli_ip`, `srv_ip`) other times not (`ip`).
In some events, the qualifications is specified as value in other fields (`is_client`).
To temporarily solve these problems we set up some grok filters to parse and map these fields, but it doesn't seem a very elegant solution.
We hope you can solve these problems with an ECS output enhancement.

Related issue: https://github.com/ntop/ntopng/issues/6221 (closed, but not resolved)

**What did you expect to happen?**
Configuring the ntopng alerts output format as ECS, we expected all alerts information to be ECS compliant.
  
**How did you reproduce it?**
Set ntopng output to ECS format as described here: https://www.ntop.org/guides/ntopng/alerts/available_recipients.html#elasticsearch.
Set ntpong alerts output to Elasticsearch (or to logstash with some custom filters for json parsing).
  
**Debug Information**:

- Ingested raw event 

```
{"source":{"port":61135},"ecs":{"version":"1.6.0"},"message":"{\"srv2cli_packets\":1012,\"cli_os\":\"\",\"action\":\"store\",\"first_seen\":1645448695,\"entity_val\":\"flow\",\"cli_blacklisted\":false,\"l7_cat\":6,\"srv_country_name\":\"\",\"entity_id\":4,\"observation_point_id\":0,\"srv_continent_name\":\"\",\"cli_ip\":\"Y.Y.Y.Y\",\"srv_city_name\":\"\",\"pool_id\":0,\"cli_asn\":0,\"cli_city_name\":\"\",\"json\":\"{\"ntopng.key\":123456789,\"hash_entry_id\":4471957,\"alert_generation\": {\"script_key\":\"known_proto_on_non_std_port\",\"subdir\":\"flow\"},\"info\":\"\",\"proto\": {},\"cli.ip\":\"Y.Y.Y.Y\",\"srv.ip\":\"X.X.X.X\",\"cli.port\":61135,\"srv.port\":3128,\"cli.localhost\":true,\"srv.localhost\":true,\"duration\":8,\"proto.l4\":\"TCP\",\"proto.ndpi\":\"HTTP_Connect.Facebook\",\"proto.ndpi_app\":\"Facebook\",\"proto.ndpi_cat\":\"SocialNetwork\",\"proto.ndpi_cat_id\":6,\"proto.ndpi_breed\":\"Fun\",\"cli2srv.bytes\":40529,\"srv2cli.bytes\":1436835,\"cli2srv.packets\":648,\"srv2cli.packets\":1012,\"info\":\"\"}\",\"community_id\":\"1:0EdfYOBMpeKCp0lt+ChKoMZX5QI=\",\"srv_asn\":0,\"is_flow_alert\":true,\"srv_blacklisted\":false,\"flow_risk_bitmap\":32,\"l7_master_proto\":130,\"vlan_id\":0,\"srv_localhost\":true,\"cli_name\":\"\",\"cli2srv_bytes\":40529,\"cli_localhost\":true,\"srv_os\":\"\",\"srv_name\":\"server.domain.example\",\"srv_port\":3128,\"srv_ip\":\"X.X.X.X\",\"proto.ndpi\":\"HTTP_Connect.Facebook\",\"ip_version\":4,\"alert_id\":30,\"is_cli_victim\":false,\"cli2srv_packets\":648,\"cli_country_name\":\"\",\"is_srv_victim\":false,\"cli_port\":61135,\"tstamp\":1645448728,\"ifid\":31,\"l7_proto\":119,\"alerts_map\":\"40000000\",\"cli_continent_name\":\"\",\"is_cli_attacker\":true,\"proto\":6,\"score\":50,\"is_srv_attacker\":false,\"srv2cli_bytes\":1436835}","organization":{"name":"ntop"},"rule":{"name":"Unknown"},"network":{"protocol":"http_connect.facebook","transport":"tcp","community_id":"1:0EdfYOBMpeKCp0lt+ChKoMZX5QI="},"destination":{"port":3128},"event":{"risk_score":50,"category":"network","module":"ntopng","severity_label":"low","kind":"alert","severity":0,"created":"2022-02-21T13:05:30.0Z","dataset":"alerts"},"observer":{"ingress":{"interface":{"name":"interface-123","id":31}}},"@timestamp":"2022-02-21T13:05:30.0Z"}
```
-------
- `message` examples
```
{"srv2cli_packets":848,"tstamp":1645449308,"action":"store","srv_location_lon":12.3456,"cli_city_name":"XXXXX","l7_proto":206,"proto.ndpi":"WireGuard","cli_port":54747,"alert_id":30,"first_seen":1645449245,"cli_os":"","cli_localhost":false,"srv_name":"host-YY-YY-YY-YY.infracom.it","is_cli_attacker":true,"flow_risk_bitmap":32,"srv2cli_bytes":998140,"srv_localhost":true,"vlan_id":0,"cli_ip":"ZZ.ZZZ.ZZ.ZZZ","json":"{"ntopng.key":123456789,"hash_entry_id":135935684,"alert_generation": {"script_key":"known_proto_on_non_std_port","subdir":"flow"},"info":"","proto": {},"cli.ip":"ZZ.ZZZ.ZZ.ZZZ","srv.ip":"HH.HHH.HH.HHH","srv.protocol_server":true,"cli.port":54747,"srv.port":41999,"cli.localhost":false,"srv.localhost":true,"duration":59,"proto.l4":"UDP","proto.ndpi":"WireGuard","proto.ndpi_app":"WireGuard","proto.ndpi_cat":"VPN","proto.ndpi_cat_id":2,"proto.ndpi_breed":"Acceptable","cli2srv.bytes":99296,"srv2cli.bytes":998140,"cli2srv.packets":544,"srv2cli.packets":848,"info":""}","proto":17,"community_id":"1:K7+tM0urky4cwTKpz4UPIOzHGZA=","l7_cat":2,"cli_location_lat":12.3456,"observation_point_id":0,"srv_asn":1234,"srv_os":"","srv_location_lat":12.3456,"cli_blacklisted":false,"cli_country_name":"NN","is_srv_attacker":false,"ip_version":4,"entity_val":"flow","cli_name":"","pool_id":0,"is_flow_alert":true,"srv_city_name":"XXXXX","ifid":1,"cli2srv_bytes":99296,"srv_blacklisted":false,"l7_master_proto":0,"srv_continent_name":"EU","cli_asn":1234,"srv_ip":"HH.HHH.HH.HHH","alerts_map":"0200000040000000","cli_continent_name":"EU","entity_id":4,"score":60,"is_srv_victim":false,"srv_country_name":"NN","srv_port":41999,"is_cli_victim":false,"cli2srv_packets":544,"cli_location_lon":12.3456}
```
```
{"granularity":60,"alert_id":5,"subtype":"","score":50,"ip":"YY.YYY.YY.YYY","action":"release","observation_point_id":0,"is_server":false,"tstamp":1645449441,"json":"{"alert_generation": {"script_key":"syn_scan","subdir":"host","host_info": {"name":"","localhost":false,"systemhost":false,"privatehost":false,"broadcast_domain_host":false,"dhcpHost":false,"is_blacklisted":true,"is_broadcast":false,"is_multicast":false}},"is_attacker":true,"value":311,"threshold":256}","ip_version":4,"tstamp_end":1645449552,"is_attacker":true,"pool_id":0,"is_victim":false,"is_client":true,"entity_id":1,"name":"","vlan_id":0,"entity_val":"YY.YYY.YY.YYY","ifid":1}
```
-------
- JSON error on `message` 
  
![image](https://user-images.githubusercontent.com/28502784/154964243-1fe5cc33-44cf-4129-b110-4bce8e7fdc72.png)

**Comment by lucaderi** [comment]
@AlessioPaternoster Can you please advise how such field names should be named, and what are the fields to rename?

**Comment by AlessioPaternoster** [comment]
Hi @lucaderi. Thank you for taking in charge this issue.
  
Currently we are using the ECS schema version 1.12 (https://www.elastic.co/guide/en/ecs/1.12/ecs-field-reference.html). All fields should be renamed as described in the documentation above. There could be some ntopng fields which not have the corresponding ECS fields but they can be added to the Elastic event following the guidelines described in these chapters https://www.elastic.co/guide/en/ecs/1.12/ecs-using-ecs.html. 
  
When all ntopng fields are mapped correcly, we should have an Elastic event without the `message` field. Moreover, all fields should be ECS compliant and each one should have a meaning when we inspecting the Elastic event (es. `ip` must be qualified, `alert_id` must have also a description, ecc..).

As an example, we post here our mapping. It is a working in progress and currently no all fields are mapped. We tried to map ntopng fields to ECS fields as best as possible. 
```
hostname -> rename to host.hostname
event.severity_label -> rename to log.level
syslog.facility -> rename to log.syslog.facility.code
syslog.facility_label -> rename to log.syslog.facility.name
syslog.priority -> rename to log.syslog.priority
syslog.severity_label -> rename to log.syslog.severity.name
log.syslog.severity.code -> copy from event.severity
observer.product -> ntopng
observer.vendor -> copy from organization.name
srv2cli_bytes -> move to server.bytes
cli2srv_bytes -> move to client.bytes
srv2cli_packets -> move to server.packets
cli2srv_packets -> move to client.packets
cli_addr | cli_ip -> move to client.ip
srv_addr | srv_ip -> move to server.ip
srv_port -> move to server.port
cli_port -> move to client.port
score -> move to network.flow.score
first_seen -> move to network.flow.first_seen (convert to timestamp)
srv_country | srv_country_name -> move to server.geo.country_iso_code
cli_country | cli_country_name -> move to client.geo.country_iso_code
cli_continent_name -> move to client.geo.continent_code
srv_continent_name -> move to server.geo.continent_code
cli_city_name -> move to client.geo.city_name
srv_city_name -> move to server.geo.city_name
srv_location_lat -> move to server.geo.location.lat
srv_location_lon -> move to server.geo.location.lon
cli_location_lat -> move to client.geo.location.lat
cli_location_lon -> move to client.geo.location.lon
srv_asn -> move to server.as.number
cli_asn -> move to client.as.number
srv_name -> move to server.domain
cli_name -> move to client.domain
action -> move to event.action
is_srv_victim -> move to server.victim
is_cli_victim -> move to client.victim
is_srv_attacker -> move to server.attacker
is_cli_attacker -> move to client.attacker
srv_blacklisted -> move to server.blacklisted 
cli_blacklisted -> move to client.blacklisted 
alert_id -> move to event.code
script_key -> move to event.reason
proto -> move to network.iana_number
proto.ndpi_cat -> move to network.category.name
proto.ndpi_cat_id -> move to network.category.id
proto.ndpi_app > move to network.application
ip_version -> move to network.type (convert 4 in ipv4 and 6 in ivp6, ecc..)
```

The mapping above is based mainly on flow alerts. Other alert could have other fields that must be mapped.

Furthermore, some ntopng fields need some other fields to better explain the ntopng field meaning. For example: for each  `alert_id` we need also an alert description to better explain what kind of alert was triggered. Some ntopng fields should be added to better manage alerts themselfs. For example: an alert type should be added to know if it is a flow alert, if it is an host alert, ecc... 

We hope we have provided all the necessary information in order to solve this issue.

**Comment by MatteoBiscosi** [comment]
Hi @AlessioPaternoster updated ECS format for both dev and stable version, it follows the ECS 8.0 standard, changed the message field with the formatted message that should appear in ntopng recipients.
Added DNS, TLS and HTTP protocol fields with the proper mapping.
Thanks a lot for your pointers
![Screenshot from 2022-02-24 15-50-19](https://user-images.githubusercontent.com/49585191/155547737-1973b96c-d4f1-458b-94e1-3ec7cb0d6755.png)
![Screenshot from 2022-02-24 15-52-48](https://user-images.githubusercontent.com/49585191/155548003-1e8ff001-e82d-4afc-b435-85e7cbf8bab9.png)
