### ISSUE TITLE
Poor Alert Formatting

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6340]
![image](https://user-images.githubusercontent.com/4493366/155037204-ece4eafa-6b12-4cc4-ae48-beedd0a0fcfc.png)

In the alert info page there are two entries that are not properly handled. Furthermore, empty lines must be avoided instead of representing them with empty lines.

**Comment by MatteoBiscosi** [comment]
Implemented as requested, removed the empty lines. The only ones that could be empty are the 'Other Issues' row and 'Protocol Info' row

**Comment by lucaderi** [comment]
Verified as fixed
