### ISSUE TITLE
Invalid VLAN Filtering

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6342]
![Screen Shot 2022-02-23 at 13 25 16](https://user-images.githubusercontent.com/4493366/155319954-80b1c1ef-523d-47ce-a751-0b6f2d00b148.png)

From the host page, clicking on the drill-down icon, leads to the historical flow explorer that does not seem to handle VLAN tags nicely with no records returned.

**Comment by MatteoBiscosi** [comment]
Verified as fixed, please reopen if needed
