### ISSUE TITLE
Invalid DNS Alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6345]
![image](https://user-images.githubusercontent.com/4493366/155330934-e1226ed0-a1b2-4ecc-a2ae-15b2e23695fc.png)
This alert has several issues
- Not sure what is the return code for DNS
- The flow direction is reverted
- Query type 0 looks wrong
- There is no indication of number of packets or bytes
- Clicking on the protocol it leads to the flow page with no DNS filter set

**Comment by MatteoBiscosi** [comment]
This issue is fixed in the latest ntopng version, please reopen if needed
