### ISSUE TITLE
Manual control for limits used by n2disk traffic recording controlled by ntopng

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#6347]
Hello, it it possible to add manual control for limits used by n2disk traffic recording which controlled by ntopng?
75% is very big limit, expecially for systems with a lot of space.
16Tb system for ntopng, only 12Tb allowed for traffic recording, but ntopng by itself doesn't need 4Tb...

![image](https://user-images.githubusercontent.com/67421019/155499440-d9ab3044-e491-41ae-b403-51240e71e026.png)

**Comment by cardigliano** [comment]
@atemix please note that n2disk also builds an index requiring some space, it can be 10+ % at the worst case, which is not accounted in the disk space you configure, that's why we leave 20% of free space

**Comment by atemix** [comment]
@cardigliano I think its okay for small systems, but the more we have space for dumps, the more space will be unused in this case. Maybe differentiated limits?

**Comment by cardigliano** [comment]
@atemix please note the space used by the index is in percentage, regardless of the "absolute" disk size. We can relax the limit, but that may lead to filling the disk, blocking traffic recording as a consequence.

**Comment by atemix** [comment]
@cardigliano Maybe allow admins to control this percentage and did not force it?

**Comment by cardigliano** [comment]
@atemix what we can do is to reduce the room for the index in the computation of the max space to be used, but still leave some room to avoid misconfigurations leading to blocking the recording due to a filled disk
