### ISSUE TITLE
Wrong flowsv4.FIRST/LAST_SWITCHED unix time

### ISSUE THREAD

**Issue by kyoshi-maru** [ntop/ntopng#635]
Hi!
I have a really weird problem: The timestamps in flowsv4.FIRST_SWITCHED and flowsv4.LAST_SWITCHED are off by around 40 days. I tripple checked the dates of all servers and the routers (ASA) generating the traffic and they're all fine. Data keeps coming in and is being stored to the DB but these timestamps are wrong.

`select from_unixtime(FIRST_SWITCHED), from_unixtime(LAST_SWITCHED) from flowsv4 order by LAST_SWITCHED desc limit 50`

Even more weird:
After dropping/recreating the DB I see the data coming in, its been running for 60mins now and I got ~160000 records but doing a distinct on the last_switched only shows me 4 records?
1463859060
1463859062
1463859061
1463859063

Versions:
mariadb-5.5.47-1.el7_2.x86_64
ntopng-2.5.160701-1296.x86_64
mariadb-server-5.5.47-1.el7_2.x86_64
nprobe-7.5.160701-5336.x86_64
ntopng-data-2.5.160701-1296.noarch
mariadb-libs-5.5.47-1.el7_2.x86_64

Did you ever experience something like that?

Many thanks!

**Comment by simonemainardi** [comment]
if you browse ntopng, Flows page, do you get proper timestamps or not?

**Comment by kyoshi-maru** [comment]
The timestamps are wrong as well in the flows page.

**Comment by simonemainardi** [comment]
OK, so timestamps received by ntopng are not valid.

Please, capture flow traffic between the ASA and the nprobe, and then inspect it. Look at the timestamps contained in the captured packets (wireshark can help you) and see if they match with those shown in ntopng. If this is the case, then it may be something related to the timestamp export in the ASA.

**Comment by kyoshi-maru** [comment]
The timestamps from the ASAs seem correct. There are two timestamps using the wireshark CFLOW decoder with fieldnames  'Observation Time Millliseconds' and 'StartTime' and both reflect the correct timestamp. I tried with logstash as well and everything is correct there. All new data gets the 21. May 2016 as FIRST_SWITCHED/LAST_SWITCHED. Another distinct(LAST_SWITCHED) on the >3M rows only gives me 27. Do you have any other hint on how to debug this?

**Comment by simonemainardi** [comment]
please enclose the pcap with the CFLOW I would like to look at that

**Comment by kyoshi-maru** [comment]
Hi! I sent an email to your main company address asking for a place to put/send the pcap as it contains semi-confidential data.

**Comment by simonemainardi** [comment]
please send it to mainardi ntop org

**Comment by kyoshi-maru** [comment]
Works with the latest release, many thanks for the quick fix.
