### ISSUE TITLE
[Range Picker Component] CSS for select2 dropdown is broken

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#6350]
<img width="841" alt="Screen Shot 2022-02-25 at 10 09 19" src="https://user-images.githubusercontent.com/7548711/155687673-774e79b2-6677-4363-8f9d-a075e0b55d34.png">

**Comment by MatteoBiscosi** [comment]
Added bootstrap5 style to the dropdown
![Screenshot from 2022-02-28 11-34-53](https://user-images.githubusercontent.com/49585191/155968356-f840a396-3abf-450c-9ac4-11531716f7a1.png)
