### ISSUE TITLE
Actions drop down not fully visible

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6353]
**What happened**:
In Alert list or Historical flow list when having few items, e.g. one item only, the Actions drop down is not visible:

<img width="216" alt="Screenshot 2022-03-02 at 01 48 20" src="https://user-images.githubusercontent.com/38549755/156273536-510a126e-a3a2-414b-944c-73354564f178.png">

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu , with the latest release the bug is fixed, however i had to revert to the previous table format, because due to a bug of the library this is currently non-solvable in the current table format.

**Comment by martinscheu** [comment]
Hi @MatteoBiscosi ok thanks for the roll back. Could the actions column be on the left? Otherwise is ok and we can close the ticket.

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu after internal review we decided to put the action column to the right side, in the near future however i'm planning on changing che table format and then the put the action button back on the left
