### ISSUE TITLE
Traffic recording show data of oldest entry

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6354]
**What would you like to add or change?**:
On the interface traffic recording page I see how data on disk is already used.
It would be helpful to know the date and time of the oldest entry in order to check if disk space is enough for required retention time

**Why do you and others need this?**:
Calculate or verify used disk space

**Comment by cardigliano** [comment]
Hi @martinscheu , the next tab reports the recording Window, which is date and time of the oldest and latest files, is this what you are looking for?

**Comment by martinscheu** [comment]
Hi @cardigliano 
In the traffic report I see what the daily traffic was, but I dont see the latest available data in the stored pcap dataset. Because many times I want to download a pcap, I get the "no recorded data" available. And to have an idea how much extractable data is in the n2disk storage, it would be helpfull to have a indicator, like "oldest pcap entry" 
of course the value will change with time, so maybe an update every 30min would be enough

**Comment by martinscheu** [comment]
I would place the information here:
![image](https://user-images.githubusercontent.com/38549755/156356796-18e63d22-6d68-448e-b7b5-90e8f6ebede7.png)
