### ISSUE TITLE
Poor Dropdown Formatting

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6360]
![image](https://user-images.githubusercontent.com/4493366/156847649-d58a4fe7-3f47-4ef2-b63b-cf39a8ded49b.png)
The menubar is too short in width and there is no icon at the top as in the previous version
![Screen Shot 2022-03-04 at 23 00 17](https://user-images.githubusercontent.com/4493366/156847836-79df808c-2c4d-4b84-9b4d-bc05e80ebbb1.png)

**Comment by MatteoBiscosi** [comment]
Increased width of the dropdown and added the icon if the interface is selected
![Screenshot from 2022-03-07 10-44-35](https://user-images.githubusercontent.com/49585191/157007499-a778830e-61fc-49d0-b9a1-7e6d26dc6548.png)

**Comment by lucaderi** [comment]
Verified as fixed
