### ISSUE TITLE
Poor Time Formatting in Alert Information

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6361]
![Screen Shot 2022-03-04 at 23 04 49](https://user-images.githubusercontent.com/4493366/156848191-1ce382a8-b46c-4de9-b642-fe6d68f10f97.png)

**Comment by MatteoBiscosi** [comment]
Fixed TLS certificate date/time format
![Screenshot from 2022-03-07 11-00-21](https://user-images.githubusercontent.com/49585191/157009452-67764dc9-8a1b-4496-be63-fc5fedfc7e36.png)

**Comment by lucaderi** [comment]
Verified as fixed
