### ISSUE TITLE
Invalid Table Pagination

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6362]
![Screen Shot 2022-03-04 at 16 47 13](https://user-images.githubusercontent.com/4493366/156848255-6ce77e2c-a179-41cc-aa94-72e8856e11f7.png)

**Comment by MatteoBiscosi** [comment]
Fixed string not formatted
![Screenshot from 2022-03-07 11-18-44](https://user-images.githubusercontent.com/49585191/157012461-81c062e0-8eb1-413a-a26c-b6238b849b61.png)

**Comment by lucaderi** [comment]
Verified as fixed
