### ISSUE TITLE
Don't Trigger NTP/DNS/MAIL alerts for Servers

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6365]
![image](https://user-images.githubusercontent.com/4493366/157228237-3cd4d010-e974-4c1e-8f29-94dfadaaae6f.png)

In the image above, this is a DNS server that by nature contacts several DNSs. The same for NTP, SMTP... Please modify the check so that these alerts are not triggered for servers.

**Comment by lucaderi** [comment]
Seems to work

**Comment by umlaeute** [comment]
it seems there's a typo when checking for DNS-servers (which really checks for NTP-servers), see https://github.com/ntop/ntopng/commit/e705ddac185b44b8c1c023a37b6f00d748568037#r93019192 and https://github.com/ntop/ntopng/blob/4519940b9dc36c729402be66bafde4392e9931b5/include/host_checks/DNSServerContacts.h#L32
