### ISSUE TITLE
Implement Score Check For Networks

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6366]
![image](https://user-images.githubusercontent.com/4493366/157230133-dbddfc9d-ef42-443f-a05e-dbaf818f1900.png)

Similar to "Score Threshold Exceeded" a stateful check for networks needs to be implemented. As networks can be of various sizes, an algorithm for triggering the alert should be implemented such as <network score> / <number of hosts of the network> exceeds a given threshold.

**Comment by MatteoBiscosi** [comment]
Implemented like the following:
- Available from Pro version on.
- The user is going to configure the "Per Host" score (Max score)
- If the network score exceeds the "Per Host" score an alert is going to be triggered (e.g. a user configure 200 score per host, meaning that with 30 hosts, the network score has not to be above 30 * 200, 6000 score)

![Screenshot from 2022-04-20 12-28-48](https://user-images.githubusercontent.com/49585191/164211768-deb1e08c-2ae8-44b1-ae30-d0f41a74ed60.png)

**Comment by lucaderi** [comment]
![Screen Shot 2022-04-26 at 21 20 30](https://user-images.githubusercontent.com/4493366/165376101-d7a8d478-2b84-4b9c-838e-28d9952c0e4f.png)

The threshold is set to 100 but the alert reports 700.

Furthermore since this change the host score and network score is no longer correct, and consistent across pages as you can see with host .178 below

![Screen Shot 2022-04-26 at 21 19 27](https://user-images.githubusercontent.com/4493366/165376240-81618c4b-0693-498e-8aa4-84c18257836b.png)
![Screen Shot 2022-04-26 at 21 19 18](https://user-images.githubusercontent.com/4493366/165376247-40f42af2-2b59-453e-b8e8-acda0d7bcfdb.png)

**Comment by MatteoBiscosi** [comment]
Changed Network alert name and implementation. Now it seems working correctly.
![Screenshot from 2022-05-17 11-22-28](https://user-images.githubusercontent.com/49585191/168778871-c362c448-855e-4e4b-99c3-ae673f72da2f.png)
![Screenshot from 2022-05-17 11-22-56](https://user-images.githubusercontent.com/49585191/168778895-72d38908-4de1-4c17-8d80-4da4626becd1.png)

**Comment by MatteoBiscosi** [comment]
Verified as implemented
