### ISSUE TITLE
Ntopng Website to slow - take time to load anything

### ISSUE THREAD

**Issue by cde0** [ntop/ntopng#6373]
**Environment**:
* Version:        5.3.220309 [Enterprise/Professional build]
* GIT rev:        dev:d245c2d4375ee20bbe670505a5fc405538b02c9b:20220309
* Pro rev:        r4820
* Built on:       Ubuntu 20.04.4 LTS
* Architecture: [e.g. amd64]

**What happened**:
Not sure what happening it take to much time to load anything on the website. 
We use nprobe to send traffic to ntopng and suricata to syslog.

We stop nprobe and suricata but the issue is still there. Sometimes it take 1-2 minutes to load the dashboard. 

I am not sure how i can debug this i try to disable some 
![image](https://user-images.githubusercontent.com/49035763/157463574-963735fe-02d4-4a96-91f2-cd98ad92e615.png)
![image](https://user-images.githubusercontent.com/49035763/157463753-4db83ff5-a148-4f81-92e9-8fc0e0b132ea.png)

logs:
```
09/Mar/2022 14:07:23 [MySQLDB.cpp:827] Successfully connected to ClickHouse [ntopng@172.20.12.12:9004][dname: ] for interface __system__
09/Mar/2022 14:07:23 [ClickHouseFlowDB.cpp:20] Successfully connected to ClickHouse [__system__]
09/Mar/2022 14:07:23 [ClickHouseAlertStore.cpp:125] [ClickHouse] Creating Alert DB Schema
09/Mar/2022 14:07:23 [PeriodicActivities.cpp:109] Started periodic activities loop...
09/Mar/2022 14:07:33 [startup.lua:35] Processing startup.lua: please hold on...
09/Mar/2022 14:08:14 [startup.lua:120] [lists_utils.lua:802] Refreshing category lists...
09/Mar/2022 14:08:14 [startup.lua:120] [lists_utils.lua:730] Category Lists (2492 hosts, 2534 IPs, 0 JA3) loaded in 0 sec
09/Mar/2022 14:08:14 [startup.lua:124] Initializing device polices...
09/Mar/2022 14:08:14 [startup.lua:140] Initializing alerts...
09/Mar/2022 14:08:14 [startup.lua:149] Initializing timeseries...
09/Mar/2022 14:08:14 [startup.lua:207] Importing ClickHouse dumps...
09/Mar/2022 14:08:14 [startup.lua:212] Fetching latest ntop blog posts...
09/Mar/2022 14:08:14 [startup.lua:216] Completed startup.lua
09/Mar/2022 14:08:14 [PeriodicActivities.cpp:167] Found 10 activities
09/Mar/2022 14:08:14 [NetworkInterface.cpp:3220] Started packet polling on interface tcp://127.0.0.1:5556 [id: 3]...
09/Mar/2022 14:08:15 [ZMQCollectorInterface.cpp:266] Collecting flows on tcp://127.0.0.1:5556
09/Mar/2022 14:37:02 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flows_data.lua][/usr/share/ntopng/scripts/lua/get_flows_data.lua:48: attempt to index a nil value (local 'flows_stats')]
```

**Comment by cde0** [comment]
I downgrade ntop to 5.2 and is faster.

**Comment by basicmonkey** [comment]
I'm having this same issue.

ntopng Enterprise M v.5.3.220318 (Ubuntu 20.04.4 LTS)

Initial load after login is very slow and AJAX requests take 10-20 seconds.

I've check IO requests and nothing crazy. I've tried disabling ClickHouse/MySQL and the same.
