### ISSUE TITLE
Elasticsearch add recipient not working

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6374]
**Environment**:
* OS name: [Ubuntu]
* OS version: [20.04]
* Architecture: [amd64]
* ntopng version/revision: [ntopng Enterprise L v.5.3.220308]

**What happened**:
Trying to add a elasticsearch recipient, I get:
![image](https://user-images.githubusercontent.com/38549755/157558342-1ab48194-8141-45f9-98c4-2e4dae80edfe.png)

and I can not add the recipient.
(curl http://ServerIP:9200/ works on the ntopng host)

Also without pressing "Check", I can not add the recipient.

Thanks,
Martin

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu I'm going to start new builds now, in a couple of hours please update and the issue should be fixed

**Comment by martinscheu** [comment]
@MatteoBiscosi Thanks Matteo, is working now!
