### ISSUE TITLE
Historical flow filter not working

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6375]
**Environment**:
* OS name: [Ubuntu]
* OS version: [20.04]
* Architecture: [amd64]
* ntopng version/revision: [ntopng Enterprise L v.5.3.220308]
* 
**What happened**:
I filter for a client name, but it doesn't filter correctly, see last line: (it does filter out something little though..)

![image](https://user-images.githubusercontent.com/38549755/157616536-3430b285-e759-44e1-8365-6d95dae0ac91.png)

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by cardigliano** [comment]
Could you click on the SQL badge at the bottom of the table and provide the query please?

**Comment by martinscheu** [comment]
sure: 
SELECT PROTOCOL, L7_PROTO, L7_PROTO_MASTER, SCORE, TOTAL_BYTES, toInt32(FIRST_SEEN) FIRST_SEEN, toInt32(LAST_SEEN) LAST_SEEN, L7_CATEGORY, STATUS, FLOW_RISK, INFO, FLOW_ID, VLAN_ID, IP_PROTOCOL_VERSION, IPv4NumToString(IPV4_SRC_ADDR) IPV4_SRC_ADDR_FORMATTED, IPv4NumToString(IPV4_DST_ADDR) IPV4_DST_ADDR_FORMATTED, IPv6NumToString(IPV6_SRC_ADDR) IPV6_SRC_ADDR_FORMATTED, IPv6NumToString(IPV6_DST_ADDR) IPV6_DST_ADDR_FORMATTED, IP_SRC_PORT, IP_DST_PORT, SRC_LABEL, DST_LABEL, CLIENT_LOCATION, SERVER_LOCATION, COMMUNITY_ID, ABS(LAST_SEEN - FIRST_SEEN) as TIME_DELTA, (TOTAL_BYTES / (TIME_DELTA + 1)) * 8 as THROUGHPUT FROM flows WHERE ((INTERFACE_ID=2) AND (SRC_LABEL>=('ctrlx AND SRC_LABEL<=core'))) AND (FIRST_SEEN >= 1646926198) AND (LAST_SEEN <= 1646927998)  ORDER BY FIRST_SEEN desc LIMIT 10 OFFSET 10

**Comment by cardigliano** [comment]
This has been fixed

**Comment by martinscheu** [comment]
great, thanks Alfredo!
