### ISSUE TITLE
Historical Flow Filters Broken with Host Names with Dash

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6379]
Example

![image](https://user-images.githubusercontent.com/4493366/157820609-43465167-a642-4002-a5ca-959d0e0d02d6.png)

![image](https://user-images.githubusercontent.com/4493366/157820690-6d0a23a0-3339-4a50-acf4-9477d4b23394.png)

The generated SQL is

SELECT PROTOCOL, L7_PROTO, L7_PROTO_MASTER, SCORE, TOTAL_BYTES, toInt32(FIRST_SEEN) FIRST_SEEN, toInt32(LAST_SEEN) LAST_SEEN, L7_CATEGORY, STATUS, FLOW_RISK, INFO, FLOW_ID, VLAN_ID, IP_PROTOCOL_VERSION, IPv4NumToString(IPV4_SRC_ADDR) IPV4_SRC_ADDR_FORMATTED, IPv4NumToString(IPV4_DST_ADDR) IPV4_DST_ADDR_FORMATTED, IPv6NumToString(IPV6_SRC_ADDR) IPV6_SRC_ADDR_FORMATTED, IPv6NumToString(IPV6_DST_ADDR) IPV6_DST_ADDR_FORMATTED, IP_SRC_PORT, IP_DST_PORT, SRC_LABEL, DST_LABEL, CLIENT_LOCATION, SERVER_LOCATION, COMMUNITY_ID, ABS(LAST_SEEN - FIRST_SEEN) as TIME_DELTA, (TOTAL_BYTES / (TIME_DELTA + 1)) * 8 as THROUGHPUT FROM flows WHERE ((INTERFACE_ID=3) AND (SRC_LABEL>=('imac AND SRC_LABEL<=dXXXX'))) AND (FIRST_SEEN >= 1646981011) AND (LAST_SEEN <= 1646982811)  ORDER BY FIRST_SEEN desc LIMIT 10 

In essence, if the host name is hello-world.it the SQL will be ..ND (SRC_LABEL>=('hello AND SRC_LABEL<=world.it')))... that is the bug

**Comment by cardigliano** [comment]
This has been already fixed in another issue yesterday

**Comment by cardigliano** [comment]
#6375
