### ISSUE TITLE
Redundant Buttons That Carry the Same Action

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6381]
![image](https://user-images.githubusercontent.com/4493366/157822366-ec7fb2b6-b47d-48a2-9671-d1bd39d6391e.png)

These two buttons are duplicates and one has to be removed

**Comment by lucaderi** [comment]
This is another example of redundancy that needs to be removed
![image](https://user-images.githubusercontent.com/4493366/157823418-e2cec711-cf48-4aa5-b9f6-f0b8ae42b343.png)

**Comment by MatteoBiscosi** [comment]
Removed all the redundant flow links, the only one left is the one on the navbar
![Screenshot from 2022-03-11 11-44-39](https://user-images.githubusercontent.com/49585191/157852517-252307d0-523d-4078-85ef-0cf26d2402c2.png)
![Screenshot from 2022-03-11 11-44-46](https://user-images.githubusercontent.com/49585191/157852521-2f5653fb-c20b-4b0f-8f4b-e71789807ee2.png)

**Comment by lucaderi** [comment]
Verified as fixed
