### ISSUE TITLE
Invalid Host Flow Filtering

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6382]
Inside a host with a VLAN tag, this is what I see, namely no historical data. This is already a bug as flows are present in the DB, but the SQL query is wrong.

![Screen Shot 2022-03-11 at 08 46 48](https://user-images.githubusercontent.com/4493366/157824572-76fa7c8f-5c1a-4826-8403-9f9d3534568b.png)

If I click on the "Raw Flows" menu, we jump to 

![image](https://user-images.githubusercontent.com/4493366/157824759-c2908fb3-f46e-406b-a3e2-8f547c4d38fc.png)

that return no results, instead to the correct one

![image](https://user-images.githubusercontent.com/4493366/157824909-a6286d42-2534-4139-91eb-08e25baa7842.png)

**Comment by MatteoBiscosi** [comment]
As decided before, the raw flows tab has been removed from the chart dropdown and if users want to jump to the historical flows then they have to click like usual the lens on the host navbar 
![Screenshot from 2022-03-11 11-28-39](https://user-images.githubusercontent.com/49585191/157850004-fb26458f-b001-48c6-84f8-90c0fc4e89fb.png)

**Comment by lucaderi** [comment]
Verified as fixed
