### ISSUE TITLE
Invalid Error Message With VLANs

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6385]
![Screen Shot 2022-03-11 at 16 58 58](https://user-images.githubusercontent.com/4493366/157902895-a0a88343-da9b-497e-a639-2f64c63d8024.png)

**Comment by cardigliano** [comment]
There was yet a case of IP filter including the @ generated when clicking on an IP in the flow alerts. This has also been fixed now.

**Comment by lucaderi** [comment]
This has been fixed but in the current implementation, the VLAN is no longer present and only the filter on the IP is set (see #6419).
