### ISSUE TITLE
Windows Memory Leak - v5.3.220202

### ISSUE THREAD

**Issue by awbl00** [ntop/ntopng#6388]
**Environment**:
* OS name: Windows
* OS version: 10
* Architecture: Intel x64
* ntopng version/revision: 5.3.220202

**What happened**:
Within 24 hours of starting ntopng, the machine's RAM usage is nearly 100%. This was not observed with v5.1.21907, both prior to upgrading and after downgrading. The configuration is fairly basic and uses the following options: -n 1 -i "tcp://x.x.x.x:xxxx" -m "x.x.x.x/xx" --community

**Comment by lucaderi** [comment]
We have updated a new package that contains various leak fixes should address your problem. Please update

**Comment by awbl00** [comment]
Unfortunately memory usage is still an issue with the latest release. CPU usage is greatly improved over previous versions, but process memory usage slowly climbs from ~500MB to over 2GB while total used memory slowly climbs to max from < 4GB usage prior to starting the noting service.
