### ISSUE TITLE
Hosts Geo Map Never Loads

### ISSUE THREAD

**Issue by rmancuso40** [ntop/ntopng#6390]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04.4
* Architecture: amd64
* ntopng version/revision: v.5.3.220312 rev.17181

**What happened**:
I just installed a ntopng on a new system and when I select Geo Map from the Hosts page, I just get a spinning circle and the map never loads. I have the Maxmind Geo database loaded in /var/lib/GeoIP.

**What did you expect to happen?**
I expected the Geo map to load. The Maps -> Geo Map works fine. I tried with Chrome, Edge & Firefox and tried incognito mode to ensure it wasn't a browser cache issue.

**How did you reproduce it?**
Always happens no matter what I try.

**Debug Information**:
No errors reported in ntopng.log

Paste debug information below:
- Grab a screenshot from the GUI demonstrating the issue.
![image](https://user-images.githubusercontent.com/59264078/158033851-81c9150e-20f0-4535-8edb-8c799db07692.png)

**Comment by MatteoBiscosi** [comment]
Hi @rmancuso40 could you please right click the GUI, go to inspect and check the console tab if any error is displayed there?
![Screenshot from 2022-03-14 11-54-29](https://user-images.githubusercontent.com/49585191/158158373-e14fde12-8b99-433f-adde-7e88c07173f3.png)

**Comment by MatteoBiscosi** [comment]
To have Geomap available remember that you need to add the geolocation and geolocation has to be enabled
https://github.com/ntop/ntopng/blob/dev/doc/README.geolocation.md

**Comment by rmancuso40** [comment]
Here is a screenshot of the inspect info. There is one issue but no console messages. I have the geolocation files in place and also have a cron job for geoipupdate.
![image](https://user-images.githubusercontent.com/59264078/158168026-ee39911b-9fac-4e70-99be-5b21c7997641.png)

**Comment by rmancuso40** [comment]
I was digging into this more and was checking the host_details.lua for the code when geo map is clicked on the menu. From what I can tell, with my limited knowledge, it doesn't look like it is set to do anything which would explain why it just sits with the loading spinning arrow. Here is the code section:

```
elseif page == "geomap" then

  print ([[
        <div class="row">
          <div class='col-md-12 col-lg-12 col-xs-12 mb-4'>
           <div id='geomap-alert' style="display: none" role="alert" class='alert alert-danger alert-dismissible'>
              <span id='error-message'></span>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            <div class="d-flex justify-content-center align-items-center" style="height: 720px" id="map-canvas">
              <div class="spinner-border text-primary" role="status">
                  <span class="sr-only">Loading...</span>
               </div>
           </div> 
          </div>
        </div>
     <script type='text/javascript'>
        const zoomIP = "ifid=]]..ifId..[[&]].. hostinfo2url(host_info) ..[[";
         
        const display_localized_error = (error_code) => {
            $('#geomap-alert #error-message').html(`<b>]].. i18n("geo_map.geolocation_warning") ..[[</b>: ]].. # i18n("geo_map.using_default_location") ..[[`);
            $('#geomap-alert').removeClass('alert-danger').addClass('alert-warning').show();
         }
        const display_localized_no_geolocation_msg = () => {
            $('#geomap-alert p').html(`]].. i18n("geo_map.unavailable_geolocation") .. ' ' .. i18n("geo_map.using_default_location") ..[[`);
            $('#geomap-alert').addClass('alert-info').removeClass('alert-danger').show();
        }
      </script>
   ]])

```

**Comment by MatteoBiscosi** [comment]
Hi @rmancuso40 thanks a lot for your help, I don't know how but a js include was removed and the page did not show the geomap, now it's fixed, thanks a lot

**Comment by rmancuso40** [comment]
You're welcome. Thank you for addressing it so quickly.

**Comment by lucaderi** [comment]
Verified as fixed
