### ISSUE TITLE
Invalid Host Alert Formatting

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6391]
The formatting code should be unique and used in various contexts without exceptions. This is an alert entry

![image](https://user-images.githubusercontent.com/4493366/158056388-9e589d0b-b9dd-4343-af41-05dc460aa145.png)

and this is a historical flow entry for the above alert

![image](https://user-images.githubusercontent.com/4493366/158056428-2a78ca5a-d683-4735-99ce-d136e04ebf36.png)

As you can see the formatting is different and the host icon (for jumping to the host in memory) is missing. This needs to be fixed and unified.

**Comment by MatteoBiscosi** [comment]
The issue should be fixed now. The function used is the same, the problem was that no vlan was given to the function when formatting the host in the alert table

**Comment by lucaderi** [comment]
Verified as fixed
