### ISSUE TITLE
Implement ICMP Data Exfiltration

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6394]
Similar to DNS, ICMP (see https://github.com/seladb/PcapPlusPlus/tree/master/Examples/IcmpFileTransfer) can also be used to implement data exfiltration.
This is to request a new nDPI/ntopng check to be developed.

**Comment by MatteoBiscosi** [comment]
Available in the latest ntopng version
![Screenshot from 2022-05-06 11-15-15](https://user-images.githubusercontent.com/49585191/167103512-c169cb90-7166-41d3-aacf-55825d7513fc.png)
