### ISSUE TITLE
ClickHouse support: Security considerations and Ukraine

### ISSUE THREAD

**Issue by cr0ws7** [ntop/ntopng#6395]
Hi there. I am using the ntopng Enterprise M embedded version and thought about using ClickHouse as part of my ntopng installation.
Due to the current war of Russia (Putin) against Ukraine (cyber war against western countries started already centuries before) i have no good feeling to use the software. Even it is open source how trustful is Yandex and how much influence does the Russian government / agencies have on this?

The other thing is, that i do not want to support / use Russian software in such a terrible situation.

Do you have any alternatives to use or plans here?
What are your thoughts about that?

Thanks for an answer.

**Comment by lucaderi** [comment]
At the moment ClickHouse is the best compromise. It originated from Yandex (I started to use any years ago when the C++ code had comments in Russian) but it is now a US company with an EU headquarter in Amsterdam (see https://clickhouse.com/company/). If you have suggestions please let us know.

So at the moment, I think it's safe to use it, but I do share your concerns about the war against Ukraine (and Europe) and all the affected people.

**Comment by cr0ws7** [comment]
Ok, thank you for the answer.
