### ISSUE TITLE
Data Retention Behaviour Needs Rework

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6397]
In preferences, the data retention is not specified properly as it is not clear to what data it applies.

This ticket is to ask to
- Specify the ClickHouse data retention and RRD/InfluxDB data retention in two different preferences fields.
- Specify that the RRD retention (due to the RRD nature) is taken from preferences when the RRD file is created and contrary to Influx it cannot changed afterwards
- Specify that no retention is honoured for other exports (e.g. Elastic)
- Check how the MySQL retention is implemented

**Comment by MatteoBiscosi** [comment]
Splitted CH and influx/RRD data retention, updated descriptions

**Comment by lucaderi** [comment]
Verified as fixed.
