### ISSUE TITLE
Lost Cache Check Mechanism

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6402]
Up to some time ago, ntop had an epoch-based mechanism for detecting changes in css, js....

Apparently, this mechanism is partially lost with more recent versions and it needs to be restored.

---
```
 <html>
   <head>
    <title>ntopng - Historical</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link href="/dist/third-party.css" rel="stylesheet">
    <link href="/dist/ntopng.css" rel="stylesheet">  <<<--- ERROR
    <link href="/dist/white-mode.css" rel="stylesheet"><link href="/dist/dark-mode.css?1647276154" rel="stylesheet"><link href="/favicon.ico" rel="icon">    <style>
      .flag {
        width: 16px;
        height: 11px;
        margin-top: -5px;
        background:url(/dist/images/flags.png) no-repeat
      }
    </style>

        <link href="/dist/custom-theme.css?1647276154" rel="stylesheet">
    <script type="text/javascript" src="/lua/locale.lua?user_language=en&epoch=1647271690"> </script> <<<--- OK
    <script type="text/javascript" src="/dist/third-party.js"></script>  <<<--- ERROR
    <script type="text/javascript" src="/dist/ntopng.js"></script> <<<--- ERROR
```

**Comment by lucaderi** [comment]
Why the style is not uniform? In some cases is epoch=XXX in other ?XXXX. Please unify it

    <link href="/dist/third-party.css?1647330139" rel="stylesheet">
    <link href="/dist/ntopng.css?1647330139" rel="stylesheet">
    <link href="/dist/white-mode.css?1647330139" rel="stylesheet"><link href="/favicon.ico" rel="icon">    <style>
      .flag {
        width: 16px;
        height: 11px;
        margin-top: -5px;
        background:url(/dist/images/flags.png) no-repeat
      }
    </style>

        <link href="/dist/custom-theme.css?1647330139" rel="stylesheet">
    <script type="text/javascript" src="/lua/locale.lua?user_language=en&epoch=1647313039"> </script>
    <script type="text/javascript" src="/dist/third-party.js?1647330139"></script>
    <script type="text/javascript" src="/dist/ntopng.js?1647330139"></script>

**Comment by MatteoBiscosi** [comment]
Unified the caching using the usual standard, no epoch added. e.g. `third-party.js?1647330139`

**Comment by lucaderi** [comment]
Verified as fixed
