### ISSUE TITLE
Missing Filters Mappings

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6403]
In historical flows some mappings are not implemented
![Screen Shot 2022-03-14 at 18 15 53](https://user-images.githubusercontent.com/4493366/158225484-ae7e95f4-1d79-452d-9ddc-07d866207049.png)
![Screen Shot 2022-03-14 at 18 15 41](https://user-images.githubusercontent.com/4493366/158225486-a19ac8a8-f856-4299-9454-a3a1ee4c8a28.png)
![Screen Shot 2022-03-14 at 18 16 44](https://user-images.githubusercontent.com/4493366/158225641-6d133700-f6c6-4734-92ca-e9c3c2e395b7.png)
![Screen Shot 2022-03-14 at 18 16 36](https://user-images.githubusercontent.com/4493366/158225647-e50a5ce1-e580-4fe6-88e4-c2f6df15c60d.png)
![Screen Shot 2022-03-14 at 18 18 22](https://user-images.githubusercontent.com/4493366/158225832-9f10289a-8b2a-4301-92ab-cdc51c24233a.png)

**Comment by cardigliano** [comment]
All filters requiring mapping have been ported to the new vue component

**Comment by lucaderi** [comment]
Some issues are still present

Not working yet, albeit present in URL (example &status=0%3Bneq)
- Status (no filter box present but present in URL)

Filter added but not working (i.e. filter is not effective)
- Client Pool
- Server Network
![Screen Shot 2022-03-15 at 23 30 47](https://user-images.githubusercontent.com/4493366/158483086-2f671cba-3367-46ad-9fc6-12e865ae61b0.png)
It seems that reloading the page fixes the problem.

etc.

Please check the implementation one more time

**Comment by cardigliano** [comment]
@uccidibuti please check why a page reload is required when adding some filters as reported in the last comment
