### ISSUE TITLE
Add Ability to Use Symbolic Hostnames in Active Monitoring

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6405]
In active monitoring, we currently support only numeric hostnames. This is to request to add support for symbolic hostnames that will be resolved before running the test (and not when the host is configured). For symbolic hosts with multiple corresponding numeric hosts, the first one of the list will be picked.

**Comment by cardigliano** [comment]
This is no longer required as support for Active Monitoring selection has been added in recipients b277be68f29666154f9f698b9c155f4c47201026
