### ISSUE TITLE
Add Ability to Specify Symbolic Hostnames in Host Pools

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6406]
Currently, host pools can contain MAC or numeric IPs. This is to request the ability to add symbolic hostnames to the pool. In the case of multiple numeric IPs matching a symbolic host name, the first numeric IP will be picked.

**Comment by cardigliano** [comment]
This is no longer required as support for Active Monitoring selection has been added in recipients b277be68f29666154f9f698b9c155f4c47201026
