### ISSUE TITLE
Invalid sFlow Exporter Link

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6407]
Clicking on the link below
![image](https://user-images.githubusercontent.com/4493366/158361632-277dedde-d1ee-4762-a201-18849b1977e1.png)

will send back to the list of sFlow explorers instead of going to the SNMP interface selected. If the interface has not been SNMP polled the interface Id should not have a HREF

**Comment by MatteoBiscosi** [comment]
Fixed pro repo

**Comment by lucaderi** [comment]
Verified as fixed
