### ISSUE TITLE
Implement Historical Filter for SNMP Interface

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6409]
It is not possible to select flows from/to interface Id X in the historical flow explorer, as the above expression is interpreted in AND instead here we need a OR. 

![Screen Shot 2022-03-15 at 12 24 05](https://user-images.githubusercontent.com/4493366/158367654-a5909baf-78ef-4cd4-b4c0-758e8acceb2e.png)

This is to request to implement a new field named SNMP Interface (add the 'SNMP' word to the existing Input/Output Interface) that similar to the "IP" filter implements the above logic.

**Comment by cardigliano** [comment]
Implemented in c5baed08e619fa25b955e0e23ed3017da2a69bed and pro 7815c63b5ae8c162ab0049158e6b202e188742fd

**Comment by lucaderi** [comment]
Verified as fixed
