### ISSUE TITLE
Problema con identificazione protocollo e applicazione

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#641]
Buongiorno,
ho riscontrato un problema nell'identificazione dei protocolli e delle applicazioni nel traffico analizzato.
La buona parte dei flussi infatti rimane definita come "Unknow".
Attualmente sto usando la versione Pro di nTop, accompagnata da nProbe.
Spero riusciate a fornirmi qualche informazione riguardo a questo problema e vi ringrazio anticipatamente, 
Giacomo.

**Comment by lucaderi** [comment]
English please
