### ISSUE TITLE
Implement Top Talkers in SNMP

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6410]
This is to request to extend this SNMP page by adding (in case ClickHouse is enabled with -F) a new HTML anchor
![image](https://user-images.githubusercontent.com/4493366/158366152-184b18e8-a5af-40e5-b919-ef644c116efd.png)

that will send to the historical flows with the interface filter set to the selected interfaceId

![Screen Shot 2022-03-15 at 12 28 05](https://user-images.githubusercontent.com/4493366/158368302-99f6b177-9779-4787-a561-3abfa2a7ccf9.png)

This ticket depends on #6409 and the filter should be set for both input/output interface Id.

**Comment by MatteoBiscosi** [comment]
Implemented, pro repo
