### ISSUE TITLE
NTOPNG 5.3.220303 After Update Can't Connected ClickHouse

### ISSUE THREAD

**Issue by AnhTuanNguyenn** [ntop/ntopng#6412]
Hello

Actually, i have issue with new ntopng package, 

There were 2 months i Luca was helped me to resolved problem connection with pfsense on my ntopng version 5.1.220201, i worked so far ! but last week i installed on my official server ntopng version 5.3.220303 it doesn't work anymore.

and then i remove version ntopng: 5.1.220201 and reinstall ntopng on server test, we are going to version 5.3.220303 too after that I can’t execute ntopng with clickhouse anymore. 

i got this error: `« WARNING: -F clickhouse is not available (ClickHouse client not found) »` when i try to start service ntop on 2 servers too.

ps: the server test and server office is same as config
Thankd for review this problem,

**Comment by MatteoBiscosi** [comment]
Hi @AnhTuanNguyenn is ClickHouse installed in the new server? because that message is usually displayed when ntopng cannot find ClickHouse. Could you please check it out? to do it, you just need to run `clickhouse-client`.
e.g. in my test lab:

matteo@matteo-Precision-3541:~/ntopng_front_end$ clickhouse-client 
ClickHouse client version 21.12.3.32 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 21.12.3 revision 54452.

matteo-Precision-3541 :)

**Comment by AnhTuanNguyenn** [comment]
hello Metteo, 
yes, clickhouse installed on 2 servers, when i check i have same output as you (clickhouse connected localhost:9000)

**Comment by lucaderi** [comment]
- What is the platform you are using?
- What is the absolute path of clickhouse-client?
- What is the version of clickhouse you have installed?

**Comment by AnhTuanNguyenn** [comment]
as i said i using ntopng on my pfsense (you was help me resolved problem connection between ntopng and pfsense)
What is the absolute path of clickhouse-client? that a good question too, before i just install click house on server and i just connect it via file config ntopng that work tho, but when i remove and reinstall new version ntopng it's doesn't work anymore

What is the version of clickhouse you have installed? i  test newest version clickhouse on the tutorial link: [<html>
<body>


curl -O 'https://builds.clickhouse.com/master/freebsd/clickhouse' && chmod a+x ./clickhouse
--


<br class="Apple-interchange-newline">
</body>
</html>](url)

**Comment by AnhTuanNguyenn** [comment]
UPDATE: 
i try with newest ntopng and i got error same too, when i start service: 

[Prefs.cpp:1406] WARNING: -F clickhouse is not available (ClickHouse client not found)

**Comment by AnhTuanNguyenn** [comment]
@lucaderi you can help me check pls

**Comment by lucaderi** [comment]
I believe the client app is not installed where it is expected. I have updated the code so in case of error in a addition to the string you reported, there is also the binary path of clickhouse-client that cannot be found. Please update and report.

**Comment by AnhTuanNguyenn** [comment]
hello @lucaderi, thank for your return, 

i removed ntopng and re-install new update, i got this error: 

22/Mar/2022 10:44:49 [Prefs.cpp:1406] WARNING: -F clickhouse is not available (ClickHouse client not found)
22/Mar/2022 10:44:49 [Prefs.cpp:1407] WARNING: Expected /usr/local/bin/clickhouse-client

hope that can help you resolved this problem :)

**Comment by lucaderi** [comment]
type ls -l /usr/local/bin/clickhouse-client
and report

**Comment by AnhTuanNguyenn** [comment]
ls -l /usr/local/bin/clickhouse-client
ls: /usr/local/bin/clickhouse-client: No such file or directory

i check in /usr/local/bin/ i got this :
[2.6.0-RELEASE][admin@pfSense01]/root: cd /usr/local/bin/
[2.6.0-RELEASE][admin@pfSense01]/usr/local/bin: click
clickhouse                     clickhouse-extract-from-config clickhouse-local
clickhouse-benchmark           clickhouse-format              clickhouse-obfuscator
clickhouse-client              clickhouse-git-import          clickhouse-server
clickhouse-compressor          clickhouse-keeper              clickhouse.old
clickhouse-copier              clickhouse-keeper-converter

**Comment by lucaderi** [comment]
So this is your problem. Unless  /usr/local/bin/clickhouse-client is present with this ***exact*** path, ClickHouse won't work
