### ISSUE TITLE
Improve search field

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6413]
![Screen Shot 2022-03-15 at 22 15 02](https://user-images.githubusercontent.com/4493366/158474175-72deb350-add6-48c3-9339-1d79573a6d2c.png)

When you search a host that is not in memory ntopng reports no results found. In case ntopng is started with Clickhous and in case the searched entry looks like a host, instead of "No results Found" a new entry for searching this host in historical flows/alerts should be added.

**Comment by cardigliano** [comment]
Implemented in 1a69ca984b318b74f09a1c8b5e8bca9f72e198ab d6365a5c2f15e3c96dee1affc82dba60e2883684 11ed60cafb8cee04ad2f76479cc783336ff9bb70 ca15d234fdece6ce786895dd8a413b0c62770651

**Comment by lucaderi** [comment]
![Screen Shot 2022-03-22 at 22 57 04](https://user-images.githubusercontent.com/4493366/159583094-afb8dc97-6033-4b32-872d-bcca0da548c4.png)

After the last changes no suggestion is reported. Please check one more time.

**Comment by lucaderi** [comment]
Verified as fixed
