### ISSUE TITLE
Flow Alerts: Invalid IPv6 Validator

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6419]
In flow alerts when clicking on a host
![image](https://user-images.githubusercontent.com/4493366/158478314-6454b3cc-d5f9-4614-9e75-355be561578f.png)

the following window opens

![Screen Shot 2022-03-15 at 22 48 30](https://user-images.githubusercontent.com/4493366/158478409-755d963b-bb26-4a4e-a0bb-68260909a663.png)

And an error is reported (invalid value) as this is not detected as IPv6. This is the first problem.

The second problem is that the filter should have a host+VLAN filter instead of just a host, that could have been observed on various VLANs.

**Comment by cardigliano** [comment]
@uccidibuti please check the validator

**Comment by cardigliano** [comment]
The Client Name is selected here when clicking on an IPv6, this should no longer happen now

**Comment by lucaderi** [comment]
Verified as fixed
