### ISSUE TITLE
Problem with the application identification 

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#642]
Goodmorning,
I'm having trouble with the identification of application using nTop Pro. For the most of the flows nTop report "Unknow" or "(Too Early)" in the Application field. I attach in this report a screenshot of the problem. I'm using nProbe as collector for nTop.
I hope to receive your reply soon,
Giacomo.

![aaaaaa](https://cloud.githubusercontent.com/assets/17161338/16555808/c87fe662-41d6-11e6-9444-70a7cfab2881.png)

**Comment by lucaderi** [comment]
What ntopng version are you using? With zmq we can probably optimize this as too early don't apply here

**Comment by simonemainardi** [comment]
if it says 'too early' it means that not enough traffic has been seen on that flow. Please, post exact ntopng and nprobe startup commands. Also enclose a screenshot like the one above but with the whole table not only the first three columns

**Comment by ghost** [comment]
I'm currently using the "2.2.160616 - Professional Edition" version, with an educational licence.
These are the commands that I use to start ntopng and nProbe:
     nprobe -G --zmq "tcp://serverip:5556" -i ens32
     ntopng -i tcp://serverip:5556
I attach the screenshot of the whole table that you request (I removed the clients and servers ip for privacy reasons).
![fsrgaesdgf](https://cloud.githubusercontent.com/assets/17161338/16579855/fed3d586-42a1-11e6-8aa6-2044d93cadda.png)

I have also another question for you: if I redirect a NetFlow traffic from some access point to the server where ntopng is installed, ntop will find the application used by a client or it will identify it only as a NetFlow traffic? 
Sorry but I'm a student and I'm new in the NetFlow world.

**Comment by simonemainardi** [comment]
I would suggest you to upgrade to the latest versions of ntopng and nprobe.

Anyway, as regards your issue: traffic volumes shown in the screenshot are too low (that is, few tens of bytes) to allow protocol detection. This is the reason why you get too-early or unknow. You have to wait until updated flow information is polled from the nprobe.

If you use netflow, you have to use nprobe to collect it as ntopng doesn't directly talk netflow. Then, you can use zmq to deliver flows to ntopng as you have already done above. Protocol detection is still carried out but it is less accurate as nProbe cannot inspect packets.

**Comment by ghost** [comment]
Thanks, finally I've understood what "Unknow" and "Too early" means!

Okay, thanks for the explanation.

**Comment by simonemainardi** [comment]
you're welcome.

see http://packages.ntop.org/

**Comment by lucaderi** [comment]
@como00 Please confirm that with the latest app version, you see only unknown (not 'too early anymore')

**Comment by ghost** [comment]
@lucaderi no, now I see more ("too early") than before, the number of unknow and too early has increased.

**Comment by simonemainardi** [comment]
@como00 please post ntopng and nprobe versions used

**Comment by ghost** [comment]
nTopng: v.2.4.160705 - Pro Small Business Edition
nProbe:  v.7.4.160705
