### ISSUE TITLE
Alerts Contain Duplicated Information

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6425]
![image](https://user-images.githubusercontent.com/4493366/158561224-efb19a2c-b323-46d7-a7a4-194be809d818.png)
The above image shows just an example. Most fields are replicated and should appear only once.

**Comment by MatteoBiscosi** [comment]
Moved the flow info into a new column in order to avoid duplicate information
![Screenshot from 2022-03-17 15-47-55](https://user-images.githubusercontent.com/49585191/158830473-80d6ea94-e70b-4221-86a2-9a816d4634d2.png)

**Comment by lucaderi** [comment]
Verified as fixed
