### ISSUE TITLE
Inconsistent Icons

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6427]
![image](https://user-images.githubusercontent.com/4493366/158562463-13c859ca-6f5d-4b55-a697-07370b170b18.png)
This is inconsistent. Either the "bug" icon is reverted, or all triangles are replaced with the bug. In this case:
- the bug should be red/yellow and not blue
- all the documentation must be updated in case of images with triangles

**Comment by MatteoBiscosi** [comment]
Fixed, the issue was due to a change to the severity label
