### ISSUE TITLE
Bugged label in check configuration dialog

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#6428]
<img width="825" alt="Screen Shot 2022-03-16 at 11 28 23" src="https://user-images.githubusercontent.com/7548711/158570053-6c02afd6-1bee-42ab-8424-02e6aee090ee.png">

**Comment by lucaderi** [comment]
Same here in host checks
![Screen Shot 2022-03-16 at 12 16 01](https://user-images.githubusercontent.com/4493366/158578145-e18d2ce1-fbc7-4f47-aadd-41641cf6f71d.png)

**Comment by MatteoBiscosi** [comment]
Fixed

**Comment by lucaderi** [comment]
Verified as fixed
