### ISSUE TITLE
ntop ntopng: [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/historical_db_search.

### ISSUE THREAD

**Issue by sysongyi** [ntop/ntopng#6431]
**Environment**:
* OS name: [CentOS Linux release]
* OS version: [ 7.9.2009]
* Architecture: [amd64]
* ntopng version/revision: [ntopng Enterprise M v.5.3.22031]

**What happened**:

I got an error after updating ntopng today.
ntopng.x86_64                                                  5.3.220315-17225                                          @ntop                   
ntopng-data.noarch                                             5.3.220315-17225                                          @ntop-noarch  

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

Mar 16 19:01:13 ntop ntopng: [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/historical_db_search.
lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:5025: attempt to index a nil value (local 'cached_dev')]
Mar 16 19:01:13 ntop ntopng: 16/Mar/2022 19:01:13 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/
historical_db_search.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:5025: attempt to index a nil value (local 'cached_dev')]
Mar 16 19:01:17 ntop ntopng: [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/historical_db_search.
lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:5025: attempt to index a nil value (local 'cached_dev')]
Mar 16 19:01:17 ntop ntopng: 16/Mar/2022 19:01:17 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/
historical_db_search.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:5025: attempt to index a nil value (local 'cached_dev')]
Mar 16 19:01:20 ntop ntopng: [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/historical_db_search.
lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:5025: attempt to index a nil value (local 'cached_dev')]
Mar 16 19:01:20 ntop ntopng: 16/Mar/2022 19:01:20 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/
historical_db_search.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:5025: attempt to index a nil value (local 'cached_dev')]
Mar 16 19:01:29 ntop ntopng: [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/historical_db_search.
lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:5025: attempt to index a nil value (local 'cached_dev')]
Mar 16 19:01:29 ntop ntopng: 16/Mar/2022 19:01:29 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/
historical_db_search.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:5025: attempt to index a nil value (local 'cached_dev')]

**Comment by MatteoBiscosi** [comment]
Hi @sysongyi the issue should be fixed, a new build is running, please wait a couple of hours and update.

**Comment by sysongyi** [comment]
Thank you very much for the quick solution.

**Comment by lucaderi** [comment]
Verified as fixed

**Comment by infinitynet2011** [comment]
Hello!


[root@ntopng nx2]# systemctl status ntopng
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
     Loaded: loaded (/usr/lib/systemd/system/ntopng.service; enabled; preset: disabled)
     Active: active (running) since Sat 2024-06-29 14:56:39 EEST; 6h ago
    Process: 599102 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exited, status=0/SUCCESS)
    Process: 599123 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
    Process: 599126 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (code=exited, status=0/SUCCESS)
    Process: 599128 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /run/ntopng.conf (code=exited, status=0/SUCCESS)
   Main PID: 599130 (ntopng-main)
      Tasks: 43 (limit: 821188)
     Memory: 3.2G
        CPU: 3h 16min 38.189s
     CGroup: /system.slice/ntopng.service
             ├─599130 /usr/bin/ntopng /run/ntopng.conf
             └─647268 /usr/bin/nmap 188.208.128.94

Jun 29 21:07:09 ntopng ntopng[647268]: RTTVAR has grown to over 2.3 seconds, decreasing to 2.0
Jun 29 21:07:09 ntopng ntopng[647268]: RTTVAR has grown to over 2.3 seconds, decreasing to 2.0
Jun 29 21:07:11 ntopng ntopng[647268]: RTTVAR has grown to over 2.3 seconds, decreasing to 2.0
Jun 29 21:07:11 ntopng ntopng[647268]: RTTVAR has grown to over 2.3 seconds, decreasing to 2.0
Jun 29 21:07:16 ntopng ntopng[647268]: RTTVAR has grown to over 2.3 seconds, decreasing to 2.0
Jun 29 21:07:16 ntopng ntopng[647268]: RTTVAR has grown to over 2.3 seconds, decreasing to 2.0
Jun 29 21:07:17 ntopng ntopng[647268]: RTTVAR has grown to over 2.3 seconds, decreasing to 2.0
Jun 29 21:07:17 ntopng ntopng[647268]: RTTVAR has grown to over 2.3 seconds, decreasing to 2.0
**Jun 29 21:07:49 ntopng ntopng[599130]: 29/Jun/2024 21:07:49 [LuaEngine.cpp:1499] WARNING: Script failure [/usr/share/ntopng/scripts/lua/rest/v2/get/flow/flow_filters.lua][/usr/share/ntopng/scripts/lua/modules/ntop_utils.lua:232: att>
Jun 29 21:07:49 ntopng ntopng[599130]: 29/Jun/2024 21:07:49 [LuaEngine.cpp:1499] WARNING: Script failure [/usr/share/ntopng/scripts/lua/rest/v2/get/flow/flow_filters.lua][/usr/share/ntopng/scripts/lua/modules/ntop_utils.lua:232: att>
lines 1-25/25 (END)**

[root@ntopng nx2]# ntopng -V
Version:        6.1.240629 [Enterprise/Professional build]
GIT rev:        dev:2fa03ec6793c9e70a5165c7a899d02b14fceca01:20240629
Pro rev:        r6615
Built on:       Rocky Linux release 9.3
System Id:      LE2505A72B206AB13--UE2505A7210030875--OL
Platform:       x86_64
Edition:        Enterprise M
License Type:   Permanent


Thanks,
Gabriel
