### ISSUE TITLE
Duplicated Icon Used In The Same Menu

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6432]
![Screen Shot 2022-03-16 at 13 31 41](https://user-images.githubusercontent.com/4493366/158590654-75405f7f-9aa7-4922-b1ee-2063f3719a21.png)

This is a bad practice as users are confused.

**Comment by cardigliano** [comment]
This has been fixed already

**Comment by lucaderi** [comment]
Verified as fixed
