### ISSUE TITLE
Issue with Ntop historical flows

### ISSUE THREAD

**Issue by H0neyBeer** [ntop/ntopng#6433]
**Environment**:
* OS name: [Debian11 (bullseye)]
* OS version: [5.10.103]
* Architecture: [x86_64]
* ntopng version/revision:  [ntopng Enterprise M v.5.3.220316] 
* nprobe version : nProbe Enterprise M 

**What happened**:
Hello, 
 
Yetserday I tried your Ntop license and installed clickhouse to keep my flows and it works ! But I can't see the flows in the "Flows" section but I can see it in the "Top customers", "Top conversations", "Top L7 Contacts", ... 

In attachments the issue on my Ntop and the  and the result I would like (from your website).

**What did you expect to happen?**

See screenshot 3 (takes on your website)

**Debug Information**:

![1](https://user-images.githubusercontent.com/55504935/158594982-9e0bf412-fad9-4d9f-bd05-0e8929daf77e.png)
![2](https://user-images.githubusercontent.com/55504935/158594988-78b39831-c469-440a-820a-9c7d0c7a399d.png)
![3](https://user-images.githubusercontent.com/55504935/158594991-00778753-71ee-4376-9f69-2d4be5017762.png)

**Comment by MatteoBiscosi** [comment]
Hi @H0neyBeer a new build soon is going to be available and the issue should be fixed, please bear with it a little

**Comment by H0neyBeer** [comment]
Thanks for your speed of action, have a great day!

**Comment by MatteoBiscosi** [comment]
Hi, the new update should be available, and now it's working correctly, sorry for the trouble
![Screenshot from 2022-03-16 16-59-58](https://user-images.githubusercontent.com/49585191/158633616-5824e654-b91c-401d-bba3-acd18bcc0654.png)

**Comment by lucaderi** [comment]
Verified as fixed
