### ISSUE TITLE
Can't send message to Telegram channel.

### ISSUE THREAD

**Issue by paulbrown4** [ntop/ntopng#6434]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04.4
* Architecture: amd64
* ntopng version/revision: v.5.3.220316 rev.17225

**What happened**:
When setting the Telegram endpoint channel ID to a group ID I recieve an error stating that the format is incorrect.

**What did you expect to happen?**
I expected the channel ID to be set to a group ID value that contains a dash at the beginning.

**How did you reproduce it?**
Entering the group ID with the dash at the beginning e.g. '-000000000'

Groups contain a dash in the ID and individual chats do not.

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @paulbrown4 sorry for the trouble, the issue now should be fixed. Wait for the nightly builds and tomorrow morning, update ntopng.
![Screenshot from 2022-03-16 17-05-04](https://user-images.githubusercontent.com/49585191/158634958-8df942f1-16a4-43a1-84a0-f2dd59e5160a.png)

and the check is working too.
![Screenshot from 2022-03-16 17-08-10](https://user-images.githubusercontent.com/49585191/158635107-8bfbd813-ca14-49bb-9fec-156afa098fce.png)

**Comment by paulbrown4** [comment]
Problem resolved. Using a negative channel Id works.
