### ISSUE TITLE
Invalid search text color in checks with dark theme

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6435]
![image](https://user-images.githubusercontent.com/4493366/158612342-1602f94f-93ba-46f0-b289-31270cc7c750.png)

**Comment by MatteoBiscosi** [comment]
Fixed in the latest release
![Screenshot from 2022-03-17 12-03-59](https://user-images.githubusercontent.com/49585191/158795953-17eacbef-0316-4185-a34e-a92a48494121.png)

**Comment by lucaderi** [comment]
Verified as fixed
