### ISSUE TITLE
Historical Flows Broken Again

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6436]
![image](https://user-images.githubusercontent.com/4493366/158614245-ccd2130c-0142-4978-9d6a-2e5f9cc664da.png)
![Screen Shot 2022-03-16 at 15 34 41](https://user-images.githubusercontent.com/4493366/158614336-23d4822f-845f-40c4-9505-24221e7c0d61.png)

**Comment by MatteoBiscosi** [comment]
issue fixed (duplicate of #6433)

**Comment by lucaderi** [comment]
Verified as fixed
