### ISSUE TITLE
Partial Alert Link

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6437]
In this alert the alert URL is partial as it does not contain the host address but just the second part of the URL

![image](https://user-images.githubusercontent.com/4493366/158884106-00ae1f43-1d65-43d3-8539-3315e7054375.png)

**Comment by MatteoBiscosi** [comment]
This problem seems to be related to nprobe, in fact for the packetInterface, ntopng already concat the server host name; instead for ZMQInterfaces ntopng have not the info required (host server name) and so it cannot add the server name

**Comment by lucaderi** [comment]
Unable to reproduce with the current version. Will reopen if necessary
