### ISSUE TITLE
Historical flows search does only take AS number up to 5 digits long

### ISSUE THREAD

**Issue by Syl4r-v** [ntop/ntopng#6438]
**Environment**:
* OS name: RHEL 
* OS version: 8.5
* Architecture: x86
* ntopng version/revision: v.5.2.220315

**What happened**:
When searching flows through the historical flows expolorer with ASN, you can only use up to 5 digits long ASN.

**What did you expect to happen?**
Lots of ASNs that are above 99999 that you cant search right now.

**How did you reproduce it?**

**Debug Information**:

<img width="603" alt="Screenshot 2022-03-18 at 10 38 59" src="https://user-images.githubusercontent.com/77612587/158966166-006c0579-8763-430c-88a4-9a2c1e568c7c.png">

**Comment by MatteoBiscosi** [comment]
Hi @Syl4r-v a new build is running, please wait for a couple of hours, update and let me know if now it's working

**Comment by lucaderi** [comment]
Verified as fixed
