### ISSUE TITLE
Missing Anchors from View-aggregated Interfaces

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6444]
View-aggregated interfaces lack of HTML anchors present in view interfaces.

Example:
View interface (all good)
![Screen Shot 2022-03-18 at 15 40 54](https://user-images.githubusercontent.com/4493366/159024103-35588c81-2e6d-4512-a5d9-784db9c59224.png)

Original interface (no anchors, flags etc)
![Screen Shot 2022-03-18 at 15 40 45](https://user-images.githubusercontent.com/4493366/159024115-42b4f209-bd2b-491f-983e-a85994b7b55a.png)

This ticket is to request original sub-view interfaces to be enriched with flags and anchors.

**Comment by NicoMaio** [comment]
At the moment it's possible to fix the anchors just on the Application column.

**Comment by lucaderi** [comment]
Verified as fixed
