### ISSUE TITLE
Pivoting from Alerts to historical flows not working

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6448]
**Environment**:
* OS name: [e.g. Ubuntu] Ubuntu
* OS version: [e.g. 18.04] 20.04
* Architecture: [e.g. amd64] x86_64
* ntopng version/revision: [e.g. 5.1.211223] ntopng Enterprise L v.5.3.220318 (Ubuntu 20.04.4 LTS) |

**What happened**:
When trying to pivot from an alert to the historical flow explorer, not entry is shown.
System time set to CET

See attached pdf for details.
[2022-03-19_alert-pivoting.pdf](https://github.com/ntop/ntopng/files/8309281/2022-03-19_alert-pivoting.pdf)

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by martinscheu** [comment]
[2022-03-19_alert-pivoting.pdf](https://github.com/ntop/ntopng/files/8309287/2022-03-19_alert-pivoting.pdf)

**Comment by martinscheu** [comment]
historical flow URLs
last day: http://192.168.88.238:3000/lua/pro/db_search.lua?epoch_begin=1647608102&epoch_end=1647694502&ifid=2&query_preset=&cli_ip=192.168.88.238%3Beq&srv_ip=192.168.88.250%3Beq&cli_port=38664%3Beq&srv_port=22%3Beq
last 30min: http://192.168.88.238:3000/lua/pro/db_search.lua?epoch_begin=1647693734&epoch_end=1647695534&ifid=2&query_preset=&cli_ip=192.168.88.238%3Beq&srv_ip=192.168.88.250%3Beq&cli_port=38664%3Beq&srv_port=22%3Beq
last hour: http://192.168.88.238:3000/lua/pro/db_search.lua?epoch_begin=1647691961&epoch_end=1647695561&ifid=2&query_preset=&cli_ip=192.168.88.238%3Beq&srv_ip=192.168.88.250%3Beq&cli_port=38664%3Beq&srv_port=22%3Beq

**Comment by martinscheu** [comment]
config file, interfaces
-i=eno1
-i=syslog://*:5514
-i=usb-eth0

**Comment by martinscheu** [comment]
SQL query alert page:  SELECT 4 entity_id, (toUnixTimestamp(tstamp_end) - toUnixTimestamp(tstamp)) duration, * FROM `flow_alerts` WHERE (first_seen >= 1647691985 AND first_seen <= 1647693785) AND ( alert_status = 0 ) AND (interface_id = 2) AND (severity >= 5)  ORDER BY tstamp desc LIMIT 200 OFFSET 0

SQL query historical flow, when pivoting: SELECT PROTOCOL, L7_PROTO, L7_PROTO_MASTER, SCORE, PACKETS, TOTAL_BYTES, toInt32(FIRST_SEEN) FIRST_SEEN, toInt32(LAST_SEEN) LAST_SEEN, SRC_ASN, DST_ASN, L7_CATEGORY, STATUS, FLOW_RISK, SRC2DST_TCP_FLAGS, DST2SRC_TCP_FLAGS, CLIENT_NW_LATENCY_US, SERVER_NW_LATENCY_US, INFO, OBSERVATION_POINT_ID, IPv4NumToString(PROBE_IP) PROBE_IP_FORMATTED, SRC_NETWORK_ID, DST_NETWORK_ID, SRC_HOST_POOL_ID, DST_HOST_POOL_ID, INPUT_SNMP, OUTPUT_SNMP, FLOW_ID, VLAN_ID, IP_PROTOCOL_VERSION, IPv4NumToString(IPV4_SRC_ADDR) IPV4_SRC_ADDR_FORMATTED, IPv4NumToString(IPV4_DST_ADDR) IPV4_DST_ADDR_FORMATTED, IPv6NumToString(IPV6_SRC_ADDR) IPV6_SRC_ADDR_FORMATTED, IPv6NumToString(IPV6_DST_ADDR) IPV6_DST_ADDR_FORMATTED, IP_SRC_PORT, IP_DST_PORT, SRC_LABEL, DST_LABEL, CLIENT_LOCATION, SERVER_LOCATION, COMMUNITY_ID, ABS(LAST_SEEN - FIRST_SEEN) as TIME_DELTA, (TOTAL_BYTES / (TIME_DELTA + 1)) * 8 as THROUGHPUT FROM flows WHERE ((INTERFACE_ID=2) AND (IP_DST_PORT=22) AND (IP_SRC_PORT=38024) AND ((IP_PROTOCOL_VERSION = 4) AND( (IPV4_DST_ADDR=IPv4StringToNum('192.168.88.250')) OR (DST_LABEL=('192.168.88.250')) )) AND ((IP_PROTOCOL_VERSION = 4) AND( (IPV4_SRC_ADDR=IPv4StringToNum('192.168.88.238')) OR (SRC_LABEL=('192.168.88.238')) )) AND (PROTOCOL=6)) AND (FIRST_SEEN >= 1647689109) AND (LAST_SEEN <= 1647689715)  ORDER BY FIRST_SEEN desc LIMIT 200 

SQL last hour: SELECT PROTOCOL, L7_PROTO, L7_PROTO_MASTER, SCORE, TOTAL_BYTES, toInt32(FIRST_SEEN) FIRST_SEEN, toInt32(LAST_SEEN) LAST_SEEN, L7_CATEGORY, STATUS, FLOW_RISK, INFO, INPUT_SNMP, OUTPUT_SNMP, FLOW_ID, VLAN_ID, IP_PROTOCOL_VERSION, IPv4NumToString(IPV4_SRC_ADDR) IPV4_SRC_ADDR_FORMATTED, IPv4NumToString(IPV4_DST_ADDR) IPV4_DST_ADDR_FORMATTED, IPv6NumToString(IPV6_SRC_ADDR) IPV6_SRC_ADDR_FORMATTED, IPv6NumToString(IPV6_DST_ADDR) IPV6_DST_ADDR_FORMATTED, IP_SRC_PORT, IP_DST_PORT, SRC_LABEL, DST_LABEL, CLIENT_LOCATION, SERVER_LOCATION, COMMUNITY_ID, ABS(LAST_SEEN - FIRST_SEEN) as TIME_DELTA, (TOTAL_BYTES / (TIME_DELTA + 1)) * 8 as THROUGHPUT FROM flows WHERE ((INTERFACE_ID=2) AND (IP_DST_PORT=22) AND ((IP_PROTOCOL_VERSION = 4) AND( (IPV4_DST_ADDR=IPv4StringToNum('192.168.88.250')) OR (DST_LABEL=('192.168.88.250')) )) AND ((IP_PROTOCOL_VERSION = 4) AND( (IPV4_SRC_ADDR=IPv4StringToNum('192.168.88.238')) OR (SRC_LABEL=('192.168.88.238')) )) AND (IP_SRC_PORT=38024)) AND (FIRST_SEEN >= 1647692355) AND (LAST_SEEN <= 1647695955)  ORDER BY FIRST_SEEN desc LIMIT 200

**Comment by cardigliano** [comment]
It is likely be5bf4e479d99f86dd40590dc8a95fb42850ad0c will fix this (however I was not able to reproduce the same issue on my installation)

**Comment by lucaderi** [comment]
Verified as fixed
