### ISSUE TITLE
Alerts page details of warnings or notices are not displayed

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6449]
**Environment**:
* OS name: [e.g. Ubuntu] Ubuntu
* OS version: [e.g. 18.04] 20.04
* Architecture: [e.g. amd64] x86_64
* ntopng version/revision: [e.g. 5.1.211223] ntopng Enterprise L v.5.3.220318 (Ubuntu 20.04.4 LTS) |

**What happened**:
When trying to view infos of an Warning or Notice an error is diplayed:
<img width="1598" alt="Screenshot 2022-03-19 at 16 37 58" src="https://user-images.githubusercontent.com/38549755/159127836-990e4911-1ab9-48a0-8951-28152d034d59.png">

![image](https://user-images.githubusercontent.com/38549755/159127818-a1b7557a-bc28-45c3-834d-51c35d496e25.png)

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by cardigliano** [comment]
This is related to #6448 (timestamp issue)

**Comment by cardigliano** [comment]
It is likely be5bf4e479d99f86dd40590dc8a95fb42850ad0c will fix this (however I was not able to reproduce the same issue on my installation)

**Comment by lucaderi** [comment]
Verified as fixed
