### ISSUE TITLE
ES Dropped Messages

### ISSUE THREAD

**Issue by joval-sv** [ntop/ntopng#645]
I have upgraded from v2.3 to latest v2.5 and now cannot save flows to Elasticsearch. I keep getting the following error:

Jul  5 14:25:14 collector1 ntopng: [ElasticSearch.cpp:64] WARNING: [ES] Message dropped. Total messages dropped: 961145
Jul  5 14:25:14 collector1 ntopng: [ElasticSearch.cpp:64] WARNING: [ES] Message dropped. Total messages dropped: 961146

After looking at the code from GIT, this happens when the queue is full. I am wondering what else has changed, because now I don't have the information I need. I am currently running with the following options:

cat ntopng.conf
-d=/opt/ntopng
-G=/var/tmp/ntopng.pid
-n=3
-i=p1p1
-i=p1p2
-m=10.50.0.0/16,10.51.0.0/20,10.51.16.0/20,10.39.0.0/16
-F="es;flows;ntopng-%Y.%m.%d;http://172.16.2.250:9200/_bulk;"

I need the flow data to feed to a custom app, and right now this is missing...

**Comment by simonemainardi** [comment]
are you sure the issue started occurring only when switching between 2.3 and 2.5? I'm asking because ElasticSearch.cpp hasn't been changed for more than 3 months so it is unlikely that a bug popped out in the switch.

Can you please try and setup another empty ES test instance and see what happens?

**Comment by joval-sv** [comment]
I restarted Elasticsearch with an empty instance, and the same results 
occurred, as seen in the logs:

Jul  6 09:25:15 collector1 kernel: device p1p1 entered promiscuous mode
Jul  6 09:25:15 collector1 kernel: device p1p2 entered promiscuous mode
Jul  6 09:25:35 collector1 ntopng: [ElasticSearch.cpp:58] WARNING: [ES] 
Export queue too long [32768]: expect drops
Jul  6 09:25:35 collector1 ntopng: [ElasticSearch.cpp:64] WARNING: [ES] 
Message dropped. Total messages dropped: 1
Jul  6 09:25:35 collector1 ntopng: [ElasticSearch.cpp:64] WARNING: [ES] 
Message dropped. Total messages dropped: 2
...

On 06/07/2016 04:46, simonemainardi wrote:

> are you sure the issue started occurring only when switching between 
> 2.3 and 2.5? I'm asking because ElasticSearch.cpp hasn't been changed 
> for more than 3 months so it is unlikely that a bug popped out in the 
> switch.
> 
> Can you please try and setup another empty ES test instance and see 
> what happens?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/ntop/ntopng/issues/645#issuecomment-230739298, or 
> mute the thread 
> https://github.com/notifications/unsubscribe/APG0VZBf7bLeL47SxS5NuKq2C3u9z3_9ks5qS4dpgaJpZM4JFfzR.

## 

Jorge

**Comment by lucaderi** [comment]
It looks ELK is too slow and not all flows are dumped into ELK. Can you please check if this is the case? So export seems to work, just drops occur

**Comment by h8h** [comment]
I have the same messages.

I applied the ES settings in version 2.5, therefore I don't have a clue if this happens earlier. 

`[ElasticSearch.cpp:64] WARNING: [ES] Message dropped. Total messages dropped: 32134`

@lucaderi  is it possible to threshold the message? My logs file size grows up to 2GB per day!

My configuration

`
-H --dns-mode 3 -W 3001 -m 192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,127.0.0.0/8,0.0.0.0/32,224.0.0.0/8,239.0.0.0/8,255.255.255.255/32,127.0.0.0/8 -Z /ntopng/ng001 -l 1 -F es;ntopng;ntopng-%Y.%m.%d;https://xxxx:9200/_bulk;user:password
`

The message disappeared with the  the parameter `-X 12000`

Is ES too slow for flows over 12000?

I also tried to adjust the bulk threadpool in elasticsearch: `
threadpool.bulk.queue_size: 3000` [see Tipp 9](https://www.loggly.com/blog/nine-tips-configuring-elasticsearch-for-high-performance/)

But it seems it doesn't matter.

**Comment by lucaderi** [comment]
The message should have been fixed in the current development builds. The -X is an internal ntopng setting that should not affect ELK unless it is low (such as in your case). In this case ELK drops will disappear as is ntopng that will drop data. My suggestion is that ELK can be used for small businesses, but if you have quite some traffic you need a powerful ELK cluster to keep up with traffic

**Comment by joval-sv** [comment]
Hi,

I moved the ES data folder to a SSD, and my problems went away. I am 
currently storing flows at a peak of~4M/hr without issues. I guess that 
in order to capture a very large number of flows, ES needs a more 
responsive disk subsystem.

BTW, I modified my INDEX as follows:

-F es;ntopng;ntopng-%Y.%m.%d-%H;http://xxxx:9200/_bulk;

I do not use a user/password, only restrict access via IPTABLES to the 
couple of hosts that need it, and use http in order to eliminate the SSL 
overhead. With this change, my indices get created every hour, and vary 
from 500M to 4GB every hour depending on traffic.

# du -sh *

513M    ntopng-2016.07.14-09
533M    ntopng-2016.07.14-10
710M    ntopng-2016.07.14-11
948M    ntopng-2016.07.14-12
1.2G    ntopng-2016.07.14-13
1.4G    ntopng-2016.07.14-14

Since I cannot afford to save this traffic forever due to the space 
available, I get to keep ~6 hours worth of traffic and delete the last 
index every hour via CRON. This is enough for me, but if you need to 
hold more data, just increase the size of the disk. The indices shown 
are for my smallest capture window, and to grow to 3.8G during peak traffic.

On 13/07/2016 14:56, Chris Sy wrote:

> I have the same messages.
> 
> I applied the ES settings in version 2.5, therefore I don't have a 
> clue if this happens earlier.
> 
> |[ElasticSearch.cpp:64] WARNING: [ES] Message dropped. Total messages 
> dropped: 32134|
> 
> @lucaderi https://github.com/lucaderi is it possible to threshold 
> the message? My logs file size grows up to 2GB per day!
> 
> My configuration
> 
> |
> |
> 
> 192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,127.0.0.0/8,0.0.0.0/32,224.0.0.0/8,239.0.0.0/8,255.255.255.255/32,127.0.0.0/8 
> -Z /ntopng/ng001 -l 1 -F 
> es;ntopng;ntopng-%Y.%m.%d;https://xxxx:9200/_bulk;user:password
> |
> 
> The message disappeared with the the parameter |-X 12000|
> 
> Is ES too slow for flows over 12000?
> 
> I also tried to adjust the bulk threadpool in elasticsearch: |
> threadpool.bulk.queue_size: 3000| see Tipp 9 
> https://www.loggly.com/blog/nine-tips-configuring-elasticsearch-for-high-performance/
> 
> But it seems it doesn't matter.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/ntop/ntopng/issues/645#issuecomment-232484017, or 
> mute the thread 
> https://github.com/notifications/unsubscribe/APG0VZ0JORLcF7ChzXFxF0yL9Axg_Ymlks5qVVDygaJpZM4JFfzR.

## 

Jorge Valdes

**Comment by simonemainardi** [comment]
thanks for giving the feedback. I think it is safe now to close this.
