### ISSUE TITLE
Downloaded pcap file is empty

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6450]
**Environment**:
* OS name: [e.g. Ubuntu] Ubuntu
* OS version: [e.g. 18.04] 20.04
* Architecture: [e.g. amd64] x86_64
* ntopng version/revision: [e.g. 5.1.211223] ntopng Enterprise L v.5.3.220318 (Ubuntu 20.04.4 LTS) |

**What happened**:
In historical flow explorer:

![image](https://user-images.githubusercontent.com/38549755/159127979-4be348bd-c920-4db3-bc00-a9f11a1ab12c.png)

SELECT PROTOCOL, L7_PROTO, L7_PROTO_MASTER, SCORE, TOTAL_BYTES, toInt32(FIRST_SEEN) FIRST_SEEN, toInt32(LAST_SEEN) LAST_SEEN, L7_CATEGORY, STATUS, FLOW_RISK, INFO, INPUT_SNMP, OUTPUT_SNMP, FLOW_ID, VLAN_ID, IP_PROTOCOL_VERSION, IPv4NumToString(IPV4_SRC_ADDR) IPV4_SRC_ADDR_FORMATTED, IPv4NumToString(IPV4_DST_ADDR) IPV4_DST_ADDR_FORMATTED, IPv6NumToString(IPV6_SRC_ADDR) IPV6_SRC_ADDR_FORMATTED, IPv6NumToString(IPV6_DST_ADDR) IPV6_DST_ADDR_FORMATTED, IP_SRC_PORT, IP_DST_PORT, SRC_LABEL, DST_LABEL, CLIENT_LOCATION, SERVER_LOCATION, COMMUNITY_ID, ABS(LAST_SEEN - FIRST_SEEN) as TIME_DELTA, (TOTAL_BYTES / (TIME_DELTA + 1)) * 8 as THROUGHPUT FROM flows WHERE ((INTERFACE_ID=2) AND ((IP_PROTOCOL_VERSION = 4) AND( (IPV4_DST_ADDR=IPv4StringToNum('139.15.98.150')) OR (DST_LABEL=('139.15.98.150')) )) AND (IP_SRC_PORT=47620) AND (IP_DST_PORT=443) AND ((IP_PROTOCOL_VERSION = 4) AND( (IPV4_SRC_ADDR=IPv4StringToNum('192.168.88.245')) OR (SRC_LABEL=('192.168.88.245')) ))) AND (FIRST_SEEN >= 1647099701) AND (LAST_SEEN <= 1647704501)  ORDER BY FIRST_SEEN desc LIMIT 200 

[1647703073-1647703074.pcap.zip](https://github.com/ntop/ntopng/files/8309557/1647703073-1647703074.pcap.zip)

same happens in the alerts page.

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by cardigliano** [comment]
Seems to be related to #6448 It is likely https://github.com/ntop/ntopng/commit/be5bf4e479d99f86dd40590dc8a95fb42850ad0c will fix this (however I was not able to reproduce the same issue on my installation)

**Comment by lucaderi** [comment]
Works for me
