### ISSUE TITLE
Discovered devices ability to edit information

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6452]
**What would you like to add or change?**:
The discovered devices page might not show all data. It would be helpful that the page could be edited to add missing information:
![image](https://user-images.githubusercontent.com/38549755/159129223-f26c48ca-cd70-49ee-a634-9f2cfb0fe0e6.png)

**Why do you and others need this?**:

**Comment by NicoMaio** [comment]
Hi @martinscheu 

It's already possible to edit the pieces of information of the device in /lua/host_details.lua?host=xxx.xxx.xxx.xxx&page=config (by clicking on the IP in the IP Address), and it's already possible to set the host alias in /lua/mac_details.lua?host=XX:XX:XX:XX:XX:XX&page=config

So I'm closing the issue. Please open it again if these two pages didn't make the necessary edit actions.
