### ISSUE TITLE
Missing nProbe Information When Using Views

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6457]
When collecting flows with views you get

![Screen Shot 2022-03-21 at 18 17 56](https://user-images.githubusercontent.com/4493366/159328375-152ac415-ea8c-4a9d-8ed2-b47a756058ff.png)

instead of 
![Screen Shot 2022-03-21 at 18 20 24](https://user-images.githubusercontent.com/4493366/159328816-f50e87a9-c9f5-40d4-93d5-5c6eb3713731.png)

when views are not used.

You can reproduce this issue on 194...

**Comment by MatteoBiscosi** [comment]
Removed from the view interface like discussed

**Comment by lucaderi** [comment]
Verified as fixed
