### ISSUE TITLE
Invalid VLAN 0

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6459]
In service map please modify the label "VLAN 0" to "Untagged" or "No VLAN" as VLAN 0 does not exist
![Screen Shot 2022-03-22 at 09 32 31](https://user-images.githubusercontent.com/4493366/159439704-0e3da22a-8967-4ee0-b705-c3924a0d928e.png)

**Comment by MatteoBiscosi** [comment]
Fixed, pro repo

**Comment by lucaderi** [comment]
Verified as fixed
