### ISSUE TITLE
Add a Networks Menu in Service and Periodicity Maps

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6460]
![image](https://user-images.githubusercontent.com/4493366/159439820-9da4a0da-ab26-4dca-88b5-08f704538b74.png)

On large installations, navigating networks can be difficult: please add a new menu for filtering hosts based on their network (i.e. cluster hosts similar to what happens on Hosts -> Networks

**Comment by MatteoBiscosi** [comment]
Implemented as requested
