### ISSUE TITLE
Missing Host IP Address

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6463]
![Screen Shot 2022-03-22 at 22 03 32](https://user-images.githubusercontent.com/4493366/159575687-a07c8ef8-202b-4d91-847e-e9735a13e756.png)

This format does not show the real hostname under xvideos.com but only his symbolic name. This prevents the analyzer to find out what is the IP address and thus searching it in DBs.

This is to request the real IP to be shown along with the name (if present). Both Ip and names must have HTML anchors for searching based on the two criteria.

**Comment by MatteoBiscosi** [comment]
Added Cli/Srv ip using the standard format
![Screenshot from 2022-03-23 16-16-00](https://user-images.githubusercontent.com/49585191/159732960-a5793cf9-eb99-4691-a4be-c07c6a0f5897.png)

**Comment by lucaderi** [comment]
Verified as fixed
