### ISSUE TITLE
ntopng switches itself off every day

### ISSUE THREAD

**Issue by mydzen** [ntop/ntopng#647]
Hi, we faced with a problem with ntopng.
Service ntopng switches itself off every day. And every morning we reboot the system manually and it runs correctly. It lasts about a month.
We use 2.5.160706 - Pro Small Business Edition on Ubuntu 14.04.4 LTS.
How can we solve this problem?

**Comment by lucaderi** [comment]
You need to crash ntopng, generate a core, then send me a tar file containing both ntopng and the core

**Comment by mydzen** [comment]
Hi, Luca, can you send/write some instruction for generating this tar-file with necessary information.
I have Ubuntu and ntopng intstalled by default.

**Comment by lucaderi** [comment]
http://www.ntop.org/support/faq/how-to-report-a-bug-on-ntop-apps/

**Comment by bryantsev1980** [comment]
Hi, Luca. mydzen vacation. When restarted Service ntopng frequently changing SystemID and detecting License mismatch error. How fix it?

Successful boot: 
12/Jul/2016 07:41:32 [Redis.cpp:92] Successfully connected to redis 127.0.0.1:6379@0
12/Jul/2016 07:41:32 [NtopPro.cpp:123] [LICENSE] Reading license from /etc/ntopng.license
12/Jul/2016 07:41:32 [Ntop.cpp:1095] Parent process is exiting (this is normal)
12/Jul/2016 07:41:32 [Ntop.cpp:1267] Registered interface bridge:p1p1,p2p1 [id: 0]
12/Jul/2016 07:41:32 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.6.5.0 interface p2p2...
12/Jul/2016 07:41:32 [Ntop.cpp:1267] Registered interface p2p2 [id: 5]
12/Jul/2016 07:41:32 [Ntop.cpp:1279] Registered interface view bridge:p1p1,p2p1 [id: 0]
12/Jul/2016 07:41:32 [Ntop.cpp:1279] Registered interface view p2p2 [id: 5]
12/Jul/2016 07:41:32 [main.cpp:255] PID stored in file /var/tmp/ntopng.pid
12/Jul/2016 07:41:32 [HTTPserver.cpp:501] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
12/Jul/2016 07:41:32 [Utils.cpp:342] User changed to nobody
12/Jul/2016 07:41:32 [HTTPserver.cpp:544] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
12/Jul/2016 07:41:32 [HTTPserver.cpp:547] HTTP server listening on port 3000
12/Jul/2016 07:41:32 [main.cpp:316] Working directory: /var/tmp/ntopng
12/Jul/2016 07:41:32 [main.cpp:318] Scripts/HTML pages directory: /usr/share/ntopng
12/Jul/2016 07:41:32 [Ntop.cpp:271] Welcome to ntopng x86_64 v.2.5.160712 - (C) 1998-2016 ntop.org
12/Jul/2016 07:41:32 [Ntop.cpp:276] Built on Ubuntu 14.04.4 LTS
12/Jul/2016 07:41:32 [PeriodicActivities.cpp:53] Started periodic activities loop...
12/Jul/2016 07:41:32 [NtopPro.cpp:256] [LICENSE] ntopng systemId: 6B945E179206AAF2
12/Jul/2016 07:41:32 [NtopPro.cpp:267] [LICENSE] ntopng license: D6D7EAC7E9EFF6675C115C81E53E967414764448462BD98BC8
12/Jul/2016 07:41:32 [NtopPro.cpp:288] [LICENSE] Maintenance is available until Fri Oct 14 11:34:06 2016 [94 days left]

ifconfig
em1       Link encap:Ethernet  HWaddr f0:79:59:91:58:15
          inet addr:10.10.5.10  Bcast:10.10.5.255  Mask:255.255.255.0
          inet6 addr: fe80::f279:59ff:fe91:5815/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:27308 errors:0 dropped:0 overruns:0 frame:0
          TX packets:31974 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:4065205 (4.0 MB)  TX bytes:15122026 (15.1 MB)
          Interrupt:20 Memory:f7e00000-f7e20000

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:180861 errors:0 dropped:0 overruns:0 frame:0
          TX packets:180861 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:19078983 (19.0 MB)  TX bytes:19078983 (19.0 MB)

p1p1      Link encap:Ethernet  HWaddr 68:05:ca:0c:40:de
          inet6 addr: fe80::6a05:caff:fe0c:40de/64 Scope:Link
          UP BROADCAST RUNNING PROMISC MULTICAST  MTU:1500  Metric:1
          RX packets:818491 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1242501 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:254382910 (254.3 MB)  TX bytes:1327559385 (1.3 GB)

p1p2      Link encap:Ethernet  HWaddr 68:05:ca:0c:40:df
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

p2p1      Link encap:Ethernet  HWaddr a0:36:9f:a1:3a:74
          inet6 addr: fe80::a236:9fff:fea1:3a74/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1243047 errors:0 dropped:0 overruns:0 frame:0
          TX packets:818445 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1327831691 (1.3 GB)  TX bytes:254352003 (254.3 MB)
          Memory:df600000-df6fffff

p2p2      Link encap:Ethernet  HWaddr a0:36:9f:a1:3a:75
          inet6 addr: fe80::a236:9fff:fea1:3a75/64 Scope:Link
          UP BROADCAST RUNNING PROMISC MULTICAST  MTU:1500  Metric:1
          RX packets:2360115 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:2193317332 (2.1 GB)  TX bytes:648 (648.0 B)
          Memory:df700000-df7fffff

After reboot:
12/Jul/2016 07:54:37 [Redis.cpp:92] Successfully connected to redis 127.0.0.1:6379@0
12/Jul/2016 07:54:37 [NtopPro.cpp:123] [LICENSE] Reading license from /etc/ntopng.license
12/Jul/2016 07:54:37 [NtopPro.cpp:121] [LICENSE] Read license from Redis [D6D7EAC7E9EFF6675C115C81E53E967414764448462BD98BC8]
12/Jul/2016 07:54:37 [NtopPro.cpp:179] ERROR: [LICENSE] Invalid or missing ntopng License [License mismatch error]
12/Jul/2016 07:54:37 [NtopPro.cpp:192] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
12/Jul/2016 07:54:37 [NtopPro.cpp:194] WARNING: [LICENSE] before returning to community mode
12/Jul/2016 07:54:37 [NtopPro.cpp:195] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
12/Jul/2016 07:54:37 [NtopPro.cpp:196] WARNING: [LICENSE] or run ntopng in community mode starting
12/Jul/2016 07:54:37 [NtopPro.cpp:197] WARNING: [LICENSE] ntopng --community
12/Jul/2016 07:54:37 [Ntop.cpp:1095] Parent process is exiting (this is normal)
12/Jul/2016 07:54:38 [Ntop.cpp:1267] Registered interface bridge:p1p1,p2p1 [id: 0]
12/Jul/2016 07:54:38 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.6.5.0 interface p2p2...
12/Jul/2016 07:54:38 [Ntop.cpp:1267] Registered interface p2p2 [id: 5]
12/Jul/2016 07:54:38 [Ntop.cpp:1279] Registered interface view bridge:p1p1,p2p1 [id: 0]
12/Jul/2016 07:54:38 [Ntop.cpp:1279] Registered interface view p2p2 [id: 5]
12/Jul/2016 07:54:38 [main.cpp:255] PID stored in file /var/tmp/ntopng.pid
12/Jul/2016 07:54:38 [HTTPserver.cpp:501] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
12/Jul/2016 07:54:38 [Utils.cpp:342] User changed to nobody
12/Jul/2016 07:54:38 [HTTPserver.cpp:544] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
12/Jul/2016 07:54:38 [HTTPserver.cpp:547] HTTP server listening on port 3000
12/Jul/2016 07:54:38 [main.cpp:316] Working directory: /var/tmp/ntopng
12/Jul/2016 07:54:38 [main.cpp:318] Scripts/HTML pages directory: /usr/share/ntopng
12/Jul/2016 07:54:38 [Ntop.cpp:271] Welcome to ntopng x86_64 v.2.5.160712 - (C) 1998-2016 ntop.org
12/Jul/2016 07:54:38 [Ntop.cpp:276] Built on Ubuntu 14.04.4 LTS
12/Jul/2016 07:54:38 [PeriodicActivities.cpp:53] Started periodic activities loop...
12/Jul/2016 07:54:38 [NtopPro.cpp:256] [LICENSE] ntopng systemId: DC0F46E09206AAF2
12/Jul/2016 07:54:38 [NtopPro.cpp:261] [LICENSE] ntopng is starting in demo mode

**Comment by simonemainardi** [comment]
Hi Brian, I guess you are running ntopng on a VM that changes some hardware
upon reboot (MAC address for example) and this, in turn, causes the system
id to change.

Please, start ntopng with option --online-license-check and report back.

Thank you,
Simone

**Comment by bryantsev1980** [comment]
Hi, Luca. It's a physical server, not a VM.

**Comment by simonemainardi** [comment]
Let's try with --online-license-check and report back, thank you

**Comment by lucaderi** [comment]
Do you keep em1 as management interface or it changes across boots?

**Comment by bryantsev1980** [comment]
No, we don't change management interface across boots, how it check?

after adding --online-license-check it works:

12/Jul/2016 15:25:50 [Redis.cpp:92] Successfully connected to redis 127.0.0.1:6379@0
12/Jul/2016 15:25:50 [NtopPro.cpp:123] [LICENSE] Reading license from /etc/ntopng.license
12/Jul/2016 15:25:50 [NtopPro.cpp:136] Contacting licensing server. Please hold on...
12/Jul/2016 15:25:50 [NtopPro.cpp:136] Contacting licensing server. Please hold on...
12/Jul/2016 15:25:50 [Ntop.cpp:1095] Parent process is exiting (this is normal)
12/Jul/2016 15:25:51 [Ntop.cpp:1267] Registered interface bridge:p1p1,p2p1 [id: 0]
12/Jul/2016 15:25:51 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.6.5.0 interface p2p2...
12/Jul/2016 15:25:51 [Ntop.cpp:1267] Registered interface p2p2 [id: 5]
12/Jul/2016 15:25:51 [Ntop.cpp:1279] Registered interface view bridge:p1p1,p2p1 [id: 0]
12/Jul/2016 15:25:51 [Ntop.cpp:1279] Registered interface view p2p2 [id: 5]
12/Jul/2016 15:25:51 [main.cpp:255] PID stored in file /var/tmp/ntopng.pid
12/Jul/2016 15:25:51 [HTTPserver.cpp:501] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
12/Jul/2016 15:25:51 [Utils.cpp:342] User changed to nobody
12/Jul/2016 15:25:51 [HTTPserver.cpp:544] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
12/Jul/2016 15:25:51 [HTTPserver.cpp:547] HTTP server listening on port 3000
12/Jul/2016 15:25:51 [main.cpp:316] Working directory: /var/tmp/ntopng
12/Jul/2016 15:25:51 [main.cpp:318] Scripts/HTML pages directory: /usr/share/ntopng
12/Jul/2016 15:25:51 [Ntop.cpp:271] Welcome to ntopng x86_64 v.2.5.160712 - (C) 1998-2016 ntop.org
12/Jul/2016 15:25:51 [Ntop.cpp:276] Built on Ubuntu 14.04.4 LTS
12/Jul/2016 15:25:51 [PeriodicActivities.cpp:53] Started periodic activities loop...
12/Jul/2016 15:25:51 [NtopPro.cpp:256] [LICENSE] ntopng systemId: DC0F46E09206AAF2
12/Jul/2016 15:25:51 [NtopPro.cpp:267] [LICENSE] ntopng license: D6D7EAC7E9EFF6675C115C81E53E967414764448462BD98BC8
12/Jul/2016 15:25:51 [NtopPro.cpp:288] [LICENSE] Maintenance is available until Fri Oct 14 11:34:06 2016 [93 days left]

**Comment by lucaderi** [comment]
So you have got a solution now.

**Comment by bryantsev1980** [comment]
Yes, the problem was in line "/bridge" in file  /etc/rc.local
the problem disappeared after it was commented out
Thank you
