### ISSUE TITLE
Enhance SNMP Layout

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6477]
![Screenshot 2022-03-28 at 10 20 40](https://user-images.githubusercontent.com/4493366/160356508-b16697a0-a8c6-4040-9180-27913d3491f4.png)

1. Columns Device IP and Interface Id are not clickable

2. Message "Seen on Device...." is wrong

3. Shorten  "SNMP Interface MAC Changed" to "MAC Port Changed"

**Comment by cardigliano** [comment]
4. Shorten "Interface Id" to "If Id"
5. Add SNMP and AM alerts to all interfaces

**Comment by cardigliano** [comment]
1, 2, 4 has been implemented

**Comment by cardigliano** [comment]
5 has been implemented

**Comment by cardigliano** [comment]
As of 2, it seems alert_type_params.prev_seen_device and alert_type_params.prev_seen_port are set to a bad value when generating the alert in pro/scripts/lua/modules/check_definitions/snmp_device/snmp_device_interface_mac_changed.lua

**Comment by lucaderi** [comment]
Verified as fixed
