### ISSUE TITLE
The customer purchased a license for ntopng and was informed that the license was not available. 

### ISSUE THREAD

**Issue by hdsjahuen** [ntop/ntopng#6479]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]

**What happened**:

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

The customer purchased a license for ntopng and was informed that the license was not available. Exclusions have been made as per this blog:https://www.ntop.org/support/faq/my-license-does-not-work-what-can-i-do/
The system time is normal and the system ID has not changed.

[root@CN07-LNTOPNG01 ~]# ntopng
29/Mar/2022 10:32:12 [Ntop.cpp:237] ERROR: Another ntopng instance is running...

[root@CN07-LNTOPNG01 ~]# ntopng --version
Version:        5.2.220326 [Enterprise/Professional build]
GIT rev:        5.2-stable:105b301435a52a78e43c3b19c8d85a44dc103298:20220326
Pro rev:        r4750
Built on:       CentOS Linux release 7.9.2009 (Core)
System Id:      L68BDE39476066B23--U68BDE394E52E04D0--OL
Platform:       x86_64
Edition:        Enterprise L (Bundle)
License Type:   Time-Limited [License mismatch (check systemId or product version)]
Validity:       Until Tue Mar 29 10:39:19 2022

[root@CN07-LNTOPNG01 ~]# ntopng --check-license
Invalid license [License mismatch (check systemId or product version)]

[root@CN07-LNTOPNG01 ~]# ntopng
29/Mar/2022 10:32:12 [Ntop.cpp:237] ERROR: Another ntopng instance is running...

For this, we have stopped ntopng and restarted ntopng, but it still doesn't work.

**Comment by lucaderi** [comment]
Your license does not match the systemId
License Type: Time-Limited [License mismatch (check systemId or product version)]

and L68BDE39476066B23--U68BDE394E52E04D0--OL is not in our DB. So there is something wrong happening. Please see https://www.ntop.org/support/kb/how-can-i-move-a-license-to-a-new-server/ in case you are moving the license from another host
