### ISSUE TITLE
ntopng dashboard dose not display graph

### ISSUE THREAD

**Issue by kzhang201** [ntop/ntopng#648]
ntopng dashboard and report dose not display graph on Professional version.

![dashboardcapture](https://cloud.githubusercontent.com/assets/20341664/16659871/f1738e74-4439-11e6-83ac-755403746867.JPG)
![reportcapture](https://cloud.githubusercontent.com/assets/20341664/16659872/f1790b38-4439-11e6-844a-b861ce41e057.JPG)

**Comment by simonemainardi** [comment]
please, paste also ntopng output log and startup string.

**Comment by kzhang201** [comment]
can you let me know where log location under CentOS 7?

**Comment by kzhang201** [comment]
[root@njsniffer ntopng]# more ntopng.conf
-G=/var/tmp/ntopng.pid
-i=em2
-i=p1p1
-i=p1p2
-i=p1p3
-i=p1p4
-i=view:p1p2,p1p3
-m=74.201.176.0/24,10.201.10.0/24,10.201.11.0/24

# Dump flows to MYSql

--dump-flows=mysql;localhost;ntopng;flows;ntopng;ntopng

**Comment by kzhang201** [comment]
the current log file is empty.

[root@njsniffer ntopng]# ls -l
total 192
-rwxrwxrwx. 1 root root      0 Jul  7 03:19 ntopng.log
-rwxrwxrwx. 1 root root      0 Jul  4 03:28 ntopng.log-20160704
-rwxrwxrwx. 1 root root      0 Jul  5 03:40 ntopng.log-20160705
-rwxrwxrwx. 1 root root   8707 Jul  6 03:09 ntopng.log-20160706
-rwxrwxrwx. 1 root root 180498 Jul  7 03:19 ntopng.log-20160707

**Comment by simonemainardi** [comment]
you can either look in `/var/log/ntopng/ntopng.log` or run ntopng in foreground or browse ntopng menu entry "Runtime Status"

**Comment by simonemainardi** [comment]
![image](https://cloud.githubusercontent.com/assets/3397663/16661930/8fe06042-4475-11e6-919e-38dea324d8b9.png)

**Comment by kzhang201** [comment]
ntopng Runtime Status
System Id   59844ABA9206AAF2
Version 2.4.160705 - Pro Small Business Edition
Platform    x86_64-unknown-linux-gnu [x86_64][CentOS Linux release 7.2.1511 (Core) ] - 64 bit
Startup Line    ntopng --pid "/var/tmp/ntopng.pid" --interface "em2" --interface "p1p1" --interface "p1p2" --interface "p1p3" --interface "p1p4" --interface "view:p1p2,p1p3" --local-networks "74.201.176.0/24,10.201.10.0/24,10.201.11.0/24" --dump-flows "mysql;localhost;ntopng;flows;ntopng;ntopng"
Last Log Trace  06/Jul/2016 21:09:20 [NetworkInterface.cpp:1536] Started packet polling on interface p1p3 [id: 4]...
06/Jul/2016 21:09:20 [NetworkInterface.cpp:1536] Started packet polling on interface p1p2 [id: 3]...
06/Jul/2016 21:09:20 [NetworkInterface.cpp:1536] Started packet polling on interface em2 [id: 2]...
06/Jul/2016 21:09:20 [NetworkInterface.cpp:1536] Started packet polling on interface p1p1 [id: 1]...
06/Jul/2016 21:09:20 [Ntop.cpp:561] Adding fe80::a236:9fff:fe83:75df/64 as IPv6 local network for p1p4
06/Jul/2016 21:09:20 [Ntop.cpp:561] Adding fe80::a236:9fff:fe83:75de/64 as IPv6 local network for p1p3
06/Jul/2016 21:09:20 [Ntop.cpp:561] Adding fe80::a236:9fff:fe83:75dd/64 as IPv6 local network for p1p2
06/Jul/2016 21:09:20 [Ntop.cpp:561] Adding fe80::a236:9fff:fe83:75dc/64 as IPv6 local network for p1p1
06/Jul/2016 21:09:20 [Ntop.cpp:561] Adding fe80::2247:47ff:fe81:44ba/64 as IPv6 local network for em2
06/Jul/2016 21:09:20 [MySQLDB.cpp:535] Succesfully connected to MySQL [localhost:ntopng] for interface p1p4
06/Jul/2016 21:09:20 [NtopPro.cpp:281] [LICENSE] Maintenance is available until Wed Jul 5 22:43:35 2017 [364 days left]
06/Jul/2016 21:09:20 [NtopPro.cpp:260] [LICENSE] ntopng license: A394FBB784F8BFC7B6FA4F63C4FE5B3314993090152F0A6391
06/Jul/2016 21:09:20 [NtopPro.cpp:249] [LICENSE] ntopng systemId: 59844ABA9206AAF2
06/Jul/2016 21:09:20 [RuntimePrefs.cpp:34] Dumping alerts into syslog
06/Jul/2016 21:09:20 [PeriodicActivities.cpp:53] Started periodic activities loop...
06/Jul/2016 21:09:20 [Ntop.cpp:276] Built on CentOS Linux release 7.2.1511 (Core)
06/Jul/2016 21:09:20 [Ntop.cpp:271] Welcome to ntopng x86_64 v.2.4.160705 - (C) 1998-2016 ntop.org
06/Jul/2016 21:09:20 [main.cpp:297] Scripts/HTML pages directory: /usr/share/ntopng
06/Jul/2016 21:09:20 [main.cpp:295] Working directory: /var/tmp/ntopng
06/Jul/2016 21:09:20 [HTTPserver.cpp:512] HTTP server listening on port 3000
06/Jul/2016 21:09:20 [HTTPserver.cpp:509] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
06/Jul/2016 21:09:20 [HTTPserver.cpp:466] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
06/Jul/2016 21:09:20 [Utils.cpp:341] User changed to nobody
06/Jul/2016 21:09:20 [main.cpp:255] PID stored in file /var/tmp/ntopng.pid
06/Jul/2016 21:09:20 [Ntop.cpp:1279] Registered interface view view:p1p2,p1p3 [id: 9]
06/Jul/2016 21:09:20 [Ntop.cpp:1279] Registered interface view p1p4 [id: 5]
06/Jul/2016 21:09:20 [Ntop.cpp:1279] Registered interface view p1p3 [id: 4]
06/Jul/2016 21:09:20 [Ntop.cpp:1279] Registered interface view p1p2 [id: 3]
06/Jul/2016 21:09:20 [Ntop.cpp:1279] Registered interface view em2 [id: 2]
06/Jul/2016 21:09:20 [Ntop.cpp:1279] Registered interface view p1p1 [id: 1]
06/Jul/2016 21:09:20 [MySQLDB.cpp:495] Attempting to connect to MySQL for interface p1p4...
06/Jul/2016 21:09:20 [Ntop.cpp:1267] Registered interface p1p4 [id: 5]

**Comment by kzhang201** [comment]
Problem was cause due to firefox browser version 47.0.  it's running OK with Google chrome.

![capture](https://cloud.githubusercontent.com/assets/20341664/16663303/9df2154e-4449-11e6-88df-51bf6b07e64b.JPG)

**Comment by simonemainardi** [comment]
can you please try and force the reload of javascript files that have been loaded in the browser?

it should be something like `ctrl + shift + r` or `ctrl + F5` not sure.

**Comment by simonemainardi** [comment]
with FF 45 on ubuntu works as expected. Please try and do what we suggested above

![image](https://cloud.githubusercontent.com/assets/3397663/16691527/443db528-452d-11e6-9077-04513810ad62.png)

**Comment by kzhang201** [comment]
Ctrl-Shift-r did resovled the problem in firefox
