### ISSUE TITLE
Advanced data analytics

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6480]
**What would you like to add or change?**:
Certain Checks give high level information to the analyst, e.g. scan detected:
![image](https://user-images.githubusercontent.com/38549755/160581042-8830f668-8991-4125-a659-d9f0d02a3a10.png)

To further investigate what / who scanned the host, it would be very helpful to have the search query for historical flow automatically generated.
I click on "Action/Historical" and I see all flows which triggered above alerts.

thanks.

**Why do you and others need this?**:

**Comment by lucaderi** [comment]
This has been implemented
