### ISSUE TITLE
Live Flow is not working

### ISSUE THREAD

**Issue by robertogalvanuni** [ntop/ntopng#6481]
**Environment**:
* OS name: [(CentOS Linux release  
* OS version: 7.9.2009 (Core)
* Architecture: x86_64
* ntopng version/revision: ntopng Community v.5.3.220329

**What happened**:

When I press on Flows - Live, the screen doesn't show it:

![image](https://user-images.githubusercontent.com/102580047/160605539-5145ec77-a6b5-4272-b823-8bc5b821e1cf.png)

**What did you expect to happen?**

Show Flows in real time

**How did you reproduce it?**

Press on Flows - Live

**Debug Information**:

Mar 29 13:49:32 GJCOMLOG ntopng: 29/Mar/2022 13:49:32 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flows_data.lua][/usr/share/ntopng/scripts/lua/get_flows_data.lua:16: module 'snmp_cached_dev' not found:
Mar 29 13:49:32 GJCOMLOG ntopng: no field package.preload['snmp_cached_dev']
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/pools/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/toasts/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/recipients/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/notifications/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/notifications/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/pools/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/pools/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/notifications/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/pools/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/pools/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/notifications/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/pools/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/pools/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/alert_definitions/other/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/pools/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/alert_definitions/host/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/alert_definitions/flow/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/pools/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/alert_keys/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/var/lib/ntopng/scripts/ts_schemas/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/timeseries/custom/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/timeseries/schemas/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/timeseries/drivers/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/pools/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/var/lib/ntopng/scripts/http_lint/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/notifications/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/i18n/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/pools/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/flow_dbms/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/timeseries/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/i18n/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/share/ntopng/scripts/lua/modules/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/local/share/lua/5.4/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/local/share/lua/5.4/snmp_cached_dev/init.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/local/lib/lua/5.4/snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/local/lib/lua/5.4/snmp_cached_dev/init.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file './snmp_cached_dev.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file './snmp_cached_dev/init.lua'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/local/lib/lua/5.4/snmp_cached_dev.so'
Mar 29 13:49:32 GJCOMLOG ntopng: no file '/usr/local/lib/lua/5.4/loadall.so'
Mar 29 13:49:32 GJCOMLOG ntopng: no file './snmp_cached_dev.so']

**Comment by samcrang** [comment]
I had this problem too but it looks as though updating to the latest package available fixed this (I am on Debian though):

```
$ sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  ntopng ntopng-data pfring pfring-dkms
4 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 47.7 MB of archives.
After this operation, 669 kB disk space will be freed.
Do you want to continue? [Y/n]
Get:1 https://packages.ntop.org/apt/bullseye x64/ ntopng 5.3.220329-17352 [8,406 kB]
Get:2 https://packages.ntop.org/apt/bullseye all/ ntopng-data 5.3.220329 [35.1 MB]
Get:3 https://packages.ntop.org/apt/bullseye all/ pfring-dkms 8.1.0.7346 [67.8 kB]
Get:4 https://packages.ntop.org/apt/bullseye x64/ pfring 8.1.0-7346 [4,198 kB]
Fetched 47.7 MB in 9s (5,443 kB/s)
Reading changelogs... Done
Preconfiguring packages ...
(Reading database ... 84463 files and directories currently installed.)
Preparing to unpack .../ntopng_5.3.220329-17352_amd64.deb ...
Stopping ntopng services...
Unpacking ntopng (5.3.220329-17352) over (5.3.220328-17343) ...
Preparing to unpack .../ntopng-data_5.3.220329_all.deb ...
Unpacking ntopng-data (5.3.220329) over (5.3.220328) ...
Preparing to unpack .../pfring-dkms_8.1.0.7346_all.deb ...
```

**Comment by robertogalvanuni** [comment]
Hello Samcrang,

Thanks for your reply. 

I tried to update, uninstall, delete folders,.... but I finally fixed it commenting the line 16 in the file /usr/share/ntopng/scripts/lua/get_flows_data.lua

I put:

--local snmp_cached_dev = require "snmp_cached_dev"

Now is working properly.

Thanks for your help!

**Comment by robertogalvanuni** [comment]
> I had this problem too but it looks as though updating to the latest package available fixed this (I am on Debian though):
> 
> ```
> $ sudo apt upgrade
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Calculating upgrade... Done
> The following packages will be upgraded:
>   ntopng ntopng-data pfring pfring-dkms
> 4 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Need to get 47.7 MB of archives.
> After this operation, 669 kB disk space will be freed.
> Do you want to continue? [Y/n]
> Get:1 https://packages.ntop.org/apt/bullseye x64/ ntopng 5.3.220329-17352 [8,406 kB]
> Get:2 https://packages.ntop.org/apt/bullseye all/ ntopng-data 5.3.220329 [35.1 MB]
> Get:3 https://packages.ntop.org/apt/bullseye all/ pfring-dkms 8.1.0.7346 [67.8 kB]
> Get:4 https://packages.ntop.org/apt/bullseye x64/ pfring 8.1.0-7346 [4,198 kB]
> Fetched 47.7 MB in 9s (5,443 kB/s)
> Reading changelogs... Done
> Preconfiguring packages ...
> (Reading database ... 84463 files and directories currently installed.)
> Preparing to unpack .../ntopng_5.3.220329-17352_amd64.deb ...
> Stopping ntopng services...
> Unpacking ntopng (5.3.220329-17352) over (5.3.220328-17343) ...
> Preparing to unpack .../ntopng-data_5.3.220329_all.deb ...
> Unpacking ntopng-data (5.3.220329) over (5.3.220328) ...
> Preparing to unpack .../pfring-dkms_8.1.0.7346_all.deb ...
> ```

**Comment by MatteoBiscosi** [comment]
Hi @robertogalvanuni sorry for the trouble, I pushed a fix right now, in a couple of hours a new build is going to be available
