### ISSUE TITLE
Errors during startup with sanitiser 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6482]
29/Mar/2022 20:32:16 [LuaEngineInterface.cpp:3862] WARNING: Bad context for interface 1
29/Mar/2022 20:32:16 [OtherAlertableEntity.cpp:64] ERROR: setEntityValue() not called or empty entity_val

**Comment by cardigliano** [comment]
I added more info to the message to debug this

**Comment by cardigliano** [comment]
Reopen if still able to reproduce, providing more info
