### ISSUE TITLE
Service/Periodicity Maps are Slow

### ISSUE THREAD

**Issue by MatteoBiscosi** [ntop/ntopng#6487]
In huge networks, service/periodicity maps are slow; the problem is related to the huge quantity of data given from the back end to the front end, slowing the representation of the map in the browser.
This problem is both for the table and for the chart format

**Comment by lucaderi** [comment]
This is to require
- il there are too many entries (e.g. 1000+) limit the map/table to an upper bound and add a warning to notify the user
-in the table view of the maps, numerical values don't have commas

**Comment by lucaderi** [comment]
Verified as fixed
