### ISSUE TITLE
layer7 api doesn't get all

### ISSUE THREAD

**Issue by OzSpots-Wireless** [ntop/ntopng#6494]
**Environment**:
* OS name: [pFsense]
* ntopng version: [e.g. 5.3]

**What happened**:
this endpoint doesn't list all interface stats only around 5
/lua/rest/v2/get/interface/l7/stats.lua?ifid=3&ndpistats_mode=count"

`{"rc_str":"OK","rc":0,"rsp":[{"value":64,"url":"/lua/flows_stats.lua?application=DNS","label":"DNS"},{"value":48,"url":"/lua/flows_stats.lua?application=LLMNR","label":"LLMNR"},{"value":44,"url":"/lua/flows_stats.lua?application=SNMP","label":"SNMP"},{"value":30,"url":"/lua/flows_stats.lua?application=TLS","label":"TLS"},{"value":29,"url":"/lua/flows_stats.lua?application=ntop","label":"ntop"},{"value":107,"label":"Other"}],"rc_str_hr":"Success"}`

**What did you expect to happen?**

list all dpi like /lua/if_stats.lua?ifid=3&page=ndpi

**Comment by MatteoBiscosi** [comment]
Hi @ozrouter thanks for your report i fixed the issue by adding some parameters like can be found in the doc.
Use `get_all_values=true` the get all the values (or `max_values={NUM_VALUES}` to get at most {NUM_VALUES}) and `collapse_stats` to not get the values with a value < 3% (bytes or flows) collapsed in the `Other` returned value.

In a couple of hours the new version with these fixes is going to be released.

"127.0.0.1:3000/lua/rest/v2/get/interface/l7/stats.lua?ndpistats_mode=sinceStartup&ifid=3&get_all_values=true&collapse_stats=false"

`{"rc_str_hr":"Success","rsp":[{"label":"QUIC","url":"/lua/flows_stats.lua?application=QUIC","value":92494152},{"label":"YouTube","url":"/lua/flows_stats.lua?application=YouTube","value":24977395},{"label":"Google","url":"/lua/flows_stats.lua?application=Google","value":20943554},{"label":"ntop","url":"/lua/flows_stats.lua?application=ntop","value":3170047},{"label":"Telegram","url":"/lua/flows_stats.lua?application=Telegram","value":1242414},{"label":"HTTP","url":"/lua/flows_stats.lua?application=HTTP","value":1168047},{"label":"Microsoft","url":"/lua/flows_stats.lua?application=Microsoft","value":997546},{"label":"SNMP","url":"/lua/flows_stats.lua?application=SNMP","value":716906},{"label":"TLS","url":"/lua/flows_stats.lua?application=TLS","value":273876},{"label":"Unknown","url":"/lua/flows_stats.lua?application=Unknown","value":254884},{"label":"DNS","url":"/lua/flows_stats.lua?application=DNS","value":162367},{"label":"ICMP","url":"/lua/flows_stats.lua?application=ICMP","value":121873},{"label":"Github","url":"/lua/flows_stats.lua?application=Github","value":69304},{"label":"GoogleServices","url":"/lua/flows_stats.lua?application=GoogleServices","value":36838},{"label":"AmazonAWS","url":"/lua/flows_stats.lua?application=AmazonAWS","value":16401},{"label":"Cloudflare","url":"/lua/flows_stats.lua?application=Cloudflare","value":16343},{"label":"MDNS","url":"/lua/flows_stats.lua?application=MDNS","value":14919},{"label":"SSDP","url":"/lua/flows_stats.lua?application=SSDP","value":13034},{"label":"WireGuard","url":"/lua/flows_stats.lua?application=WireGuard","value":11492},{"label":"ICMPV6","url":"/lua/flows_stats.lua?application=ICMPV6","value":9690},{"label":"Discord","url":"/lua/flows_stats.lua?application=Discord","value":8174},{"label":"UbuntuONE","url":"/lua/flows_stats.lua?application=UbuntuONE","value":5277},{"label":"ARP","value":4752},{"label":"Microsoft365","url":"/lua/flows_stats.lua?application=Microsoft365","value":3681},{"label":"IGMP","url":"/lua/flows_stats.lua?application=IGMP","value":1794},{"l* Closing connection 0
abel":"IMAPS","url":"/lua/flows_stats.lua?application=IMAPS","value":1252},{"label":"WhatsApp","url":"/lua/flows_stats.lua?application=WhatsApp","value":954},{"label":"SMBv1","url":"/lua/flows_stats.lua?application=SMBv1","value":486},{"label":"NetBIOS","url":"/lua/flows_stats.lua?application=NetBIOS","value":184},{"label":"NTP","url":"/lua/flows_stats.lua?application=NTP","value":180}],"rc":0,"rc_str":"OK"}`

"127.0.0.1:3000/lua/rest/v2/get/interface/l7/stats.lua?ndpistats_mode=sinceStartup&ifid=3&get_all_values=true&collapse_stats=true"

`{"rsp":[{"url":"/lua/flows_stats.lua?application=QUIC","value":103677403,"label":"QUIC"},{"url":"/lua/flows_stats.lua?application=YouTube","value":25000504,"label":"YouTube"},{"url":"/lua/flows_stats.lua?application=Google","value":20969954,"label":"Google"},{"value":8785985,"label":"Other"}],"rc_str_hr":"Success","rc":0,"rc_str":"OK"}`

**Comment by OzSpots-Wireless** [comment]
whoa that was quick thanks!
I upgraded pfsense to v.5.3.220406 with `pkg install ntopng` but the files didn't change.

how can I get the latest? - edit: should I downgrade to the 5.2 shown on release page?

**Comment by MatteoBiscosi** [comment]
Hi @ozrouter try to update and let me know. No downgrade is needed, ntopng 5.3 version is the dev one instead the 5.2 is the stable one and my fix is currently only for the dev one so the 5.3 version is right

**Comment by OzSpots-Wireless** [comment]
Ok, reinstall fixed it, thanks very much.
