### ISSUE TITLE
ClickHouse Data Retention not applied

### ISSUE THREAD

**Issue by lucafwp** [ntop/ntopng#6496]
**Environment**:
* OS name: CentOS Linux
* OS version: 7.9.2009
* Architecture: amd64
* ntopng version/revision: 5.2.220217.220217

**What happened**:
Clickhouse data on disk are not deleted, once retention period, set in Data Retention option, is expired

**What did you expect to happen?**
Data should be delete to keep only the amount of days set in configuration.

**Comment by lucaderi** [comment]
Can you please report the output of (inside clickhouse-client) 

SELECT DISTINCT database, table, toUInt32(partition) drop_part FROM system.parts WHERE active AND database='ntopng';

**Comment by lucafwp** [comment]
Hi @lucaderi , here is the output:

SELECT DISTINCT
    database,
    table,
    toUInt32(partition) AS drop_part
FROM system.parts
WHERE active AND (database = 'ntopng')

Query id: 7efdaeb1-6668-4f66-9dda-addde30c9dec

┌─database─┬─table─┬─drop_part─┐
│ ntopng   │ flows │  20220405 │
│ ntopng   │ flows │  20220406 │
│ ntopng   │ flows │  20220407 │
│ ntopng   │ flows │  20220408 │
│ ntopng   │ flows │  20220409 │
│ ntopng   │ flows │  20220410 │
│ ntopng   │ flows │  20220411 │
└──────────┴───────┴───────────┘

7 rows in set. Elapsed: 0.003 sec.

**Comment by lucaderi** [comment]
So the retention is 7 days, looks good to me.

**Comment by sfedu-admin** [comment]
Same issue here.
Ntopng 5.6.230321
ClickHouse server version 23.2.4 revision 54461
Settings →Runtime Preferences →Data Retention
1 day (two check box).

ntop :) SELECT DISTINCT database, table, toUInt32(partition) drop_part FROM system.parts WHERE active AND database='ntopng';

SELECT DISTINCT
    database,
    table,
    toUInt32(partition) AS drop_part
FROM system.parts
WHERE active AND (database = 'ntopng')

Query id: a7eb744c-f4b7-451c-b478-7abaad14253b

┌─database─┬─table────────────┬─drop_part─┐
│ ntopng   │ flows            │  20230213 │
│ ntopng   │ flows            │  20230214 │
│ ntopng   │ flows            │  20230215 │
│ ntopng   │ flows            │  20230216 │
│ ntopng   │ flows            │  20230217 │
│ ntopng   │ flows            │  20230218 │
│ ntopng   │ flows            │  20230219 │
│ ntopng   │ flows            │  20230220 │
│ ntopng   │ flows            │  20230221 │
│ ntopng   │ flows            │  20230222 │
│ ntopng   │ flows            │  20230223 │
│ ntopng   │ flows            │  20230224 │
│ ntopng   │ flows            │  20230225 │
│ ntopng   │ flows            │  20230226 │
│ ntopng   │ flows            │  20230227 │
│ ntopng   │ flows            │  20230228 │
│ ntopng   │ flows            │  20230301 │
│ ntopng   │ flows            │  20230302 │
│ ntopng   │ flows            │  20230303 │
│ ntopng   │ flows            │  20230304 │
│ ntopng   │ flows            │  20230305 │
│ ntopng   │ flows            │  20230306 │
│ ntopng   │ flows            │  20230307 │
│ ntopng   │ flows            │  20230308 │
│ ntopng   │ flows            │  20230309 │
│ ntopng   │ flows            │  20230310 │
│ ntopng   │ flows            │  20230311 │
│ ntopng   │ flows            │  20230312 │
│ ntopng   │ flows            │  20230313 │
│ ntopng   │ flows            │  20230314 │
│ ntopng   │ flows            │  20230315 │
│ ntopng   │ flows            │  20230316 │
│ ntopng   │ flows            │  20230317 │
│ ntopng   │ flows            │  20230321 │
│ ntopng   │ host_alerts      │  20230213 │
│ ntopng   │ host_alerts      │  20230214 │
│ ntopng   │ host_alerts      │  20230215 │
│ ntopng   │ host_alerts      │  20230216 │
│ ntopng   │ host_alerts      │  20230217 │
│ ntopng   │ host_alerts      │  20230218 │
│ ntopng   │ host_alerts      │  20230219 │
│ ntopng   │ host_alerts      │  20230220 │
│ ntopng   │ host_alerts      │  20230221 │
│ ntopng   │ host_alerts      │  20230222 │
│ ntopng   │ host_alerts      │  20230223 │
│ ntopng   │ host_alerts      │  20230224 │
│ ntopng   │ host_alerts      │  20230225 │
│ ntopng   │ host_alerts      │  20230226 │
│ ntopng   │ host_alerts      │  20230227 │
│ ntopng   │ host_alerts      │  20230228 │
│ ntopng   │ host_alerts      │  20230301 │
│ ntopng   │ host_alerts      │  20230302 │
│ ntopng   │ host_alerts      │  20230303 │
│ ntopng   │ host_alerts      │  20230304 │
│ ntopng   │ host_alerts      │  20230305 │
│ ntopng   │ host_alerts      │  20230306 │
│ ntopng   │ host_alerts      │  20230307 │
│ ntopng   │ host_alerts      │  20230308 │
│ ntopng   │ host_alerts      │  20230309 │
│ ntopng   │ host_alerts      │  20230310 │
│ ntopng   │ host_alerts      │  20230311 │
│ ntopng   │ host_alerts      │  20230312 │
│ ntopng   │ host_alerts      │  20230313 │
│ ntopng   │ host_alerts      │  20230314 │
│ ntopng   │ host_alerts      │  20230315 │
│ ntopng   │ host_alerts      │  20230316 │
│ ntopng   │ host_alerts      │  20230317 │
│ ntopng   │ host_alerts      │  20230321 │
│ ntopng   │ interface_alerts │  20230213 │
│ ntopng   │ interface_alerts │  20230214 │
│ ntopng   │ interface_alerts │  20230215 │
│ ntopng   │ interface_alerts │  20230216 │
│ ntopng   │ interface_alerts │  20230217 │
│ ntopng   │ interface_alerts │  20230218 │
│ ntopng   │ interface_alerts │  20230219 │
│ ntopng   │ interface_alerts │  20230220 │
│ ntopng   │ interface_alerts │  20230221 │
│ ntopng   │ interface_alerts │  20230222 │
│ ntopng   │ interface_alerts │  20230223 │
│ ntopng   │ interface_alerts │  20230224 │
│ ntopng   │ interface_alerts │  20230225 │
│ ntopng   │ interface_alerts │  20230226 │
│ ntopng   │ interface_alerts │  20230227 │
│ ntopng   │ interface_alerts │  20230228 │
│ ntopng   │ interface_alerts │  20230301 │
│ ntopng   │ interface_alerts │  20230302 │
│ ntopng   │ interface_alerts │  20230303 │
│ ntopng   │ interface_alerts │  20230304 │
│ ntopng   │ interface_alerts │  20230305 │
│ ntopng   │ interface_alerts │  20230306 │
│ ntopng   │ interface_alerts │  20230307 │
│ ntopng   │ interface_alerts │  20230308 │
│ ntopng   │ interface_alerts │  20230309 │
│ ntopng   │ interface_alerts │  20230310 │
│ ntopng   │ interface_alerts │  20230311 │
│ ntopng   │ interface_alerts │  20230312 │
│ ntopng   │ interface_alerts │  20230313 │
│ ntopng   │ interface_alerts │  20230314 │
│ ntopng   │ interface_alerts │  20230315 │
│ ntopng   │ interface_alerts │  20230316 │
│ ntopng   │ interface_alerts │  20230317 │
│ ntopng   │ system_alerts    │  20230213 │
│ ntopng   │ system_alerts    │  20230214 │
│ ntopng   │ system_alerts    │  20230215 │
│ ntopng   │ system_alerts    │  20230216 │
│ ntopng   │ system_alerts    │  20230217 │
│ ntopng   │ system_alerts    │  20230218 │
│ ntopng   │ system_alerts    │  20230219 │
│ ntopng   │ system_alerts    │  20230220 │
│ ntopng   │ system_alerts    │  20230221 │
│ ntopng   │ system_alerts    │  20230222 │
│ ntopng   │ system_alerts    │  20230223 │
│ ntopng   │ system_alerts    │  20230224 │
│ ntopng   │ system_alerts    │  20230225 │
│ ntopng   │ system_alerts    │  20230226 │
│ ntopng   │ system_alerts    │  20230227 │
│ ntopng   │ system_alerts    │  20230228 │
│ ntopng   │ system_alerts    │  20230301 │
│ ntopng   │ system_alerts    │  20230302 │
│ ntopng   │ system_alerts    │  20230303 │
│ ntopng   │ system_alerts    │  20230304 │
│ ntopng   │ system_alerts    │  20230305 │
│ ntopng   │ system_alerts    │  20230306 │
│ ntopng   │ system_alerts    │  20230307 │
│ ntopng   │ system_alerts    │  20230308 │
│ ntopng   │ system_alerts    │  20230309 │
│ ntopng   │ system_alerts    │  20230310 │
│ ntopng   │ system_alerts    │  20230311 │
│ ntopng   │ system_alerts    │  20230312 │
│ ntopng   │ system_alerts    │  20230313 │
│ ntopng   │ system_alerts    │  20230314 │
│ ntopng   │ system_alerts    │  20230315 │
│ ntopng   │ system_alerts    │  20230316 │
│ ntopng   │ system_alerts    │  20230317 │
│ ntopng   │ system_alerts    │  20230321 │
│ ntopng   │ user_alerts      │  20230215 │
│ ntopng   │ user_alerts      │  20230216 │
│ ntopng   │ user_alerts      │  20230227 │
│ ntopng   │ user_alerts      │  20230316 │
│ ntopng   │ user_alerts      │  20230317 │
│ ntopng   │ user_alerts      │  20230321 │
└──────────┴──────────────────┴───────────┘

141 rows in set. Elapsed: 0.008 sec.

**Comment by not-known** [comment]
Same issue here. Retention period 30 days, actual count per table 78.  I was already in doubt why the used disk space kept growing and growing...

**Comment by MatteoBiscosi** [comment]
Hi @not-known the issue is fixed in the latest both stable and dev version, see #7337
