### ISSUE TITLE
Append System Alerts Links on the Interface Alert Page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6498]
System
![Screen Shot 2022-04-09 at 11 18 45](https://user-images.githubusercontent.com/4493366/162565244-dbc9d974-8036-4391-a61f-ea1bbd61c3f0.png)

Interface 
![Screen Shot 2022-04-09 at 11 18 30](https://user-images.githubusercontent.com/4493366/162565246-ff4e4d4d-527a-46f0-826c-752d87975e18.png)

**Comment by cardigliano** [comment]
Implemented a few days ago
<img width="814" alt="Screen Shot 2022-04-13 at 15 10 07" src="https://user-images.githubusercontent.com/7548711/163187411-8233564f-2158-432b-9abe-2e3fa67c6715.png">

**Comment by lucaderi** [comment]
Working with ClickHouse not working with SQLite
