### ISSUE TITLE
Missing Search Field from System Interface

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6499]
This is to restore the search field in the system interface as it is helpful to find MAC addresses across all the SNMP pages.

**Comment by lucaderi** [comment]
In case of no match the usual "No match found" message is not shown
![image](https://user-images.githubusercontent.com/4493366/163030358-b6471185-6902-40c5-8f47-d24562003c2b.png)

**Comment by cardigliano** [comment]
@uccidibuti please check this, the search box is reporting "No results found" for 'x' but not for '$'

<img width="1013" alt="Screen Shot 2022-04-13 at 11 25 33" src="https://user-images.githubusercontent.com/7548711/163145180-42a971b6-c993-478c-91d8-23dab62e69f3.png">
<img width="1008" alt="Screen Shot 2022-04-13 at 11 25 18" src="https://user-images.githubusercontent.com/7548711/163145213-e3e20337-611e-4b5a-9677-fd9dcac8fad1.png">

**Comment by MatteoBiscosi** [comment]
Both working correctly in the latest ntopng version. Please reopen the ticket if needed
![Screenshot from 2022-05-17 10-22-22](https://user-images.githubusercontent.com/49585191/168765233-06980616-6ea2-4f89-bd09-ef128e4b90a2.png)
![Screenshot from 2022-05-17 10-22-27](https://user-images.githubusercontent.com/49585191/168765242-2a7f556f-3936-4f22-ab40-2cc8f9c08929.png)
