### ISSUE TITLE
Continuously duplicated data when outputting to ElasticSearch

### ISSUE THREAD

**Issue by acs5369** [ntop/ntopng#65]
When running the following command:
`ntopng -n 3 -i [path to pcap] -F "es;flows;ntopng-%Y.%m.%d;http:/;locahost:9200/_bulk;" -v`
I notice that the program sends some data to ES, then loops for 5 seconds or longer (once each second, 5+ times) and outputs to the screen:
> 29/Jun/2015 12:31:17 [src/PeriodicActivities.cpp:91] Starting script /usr/share/ntopng/scripts/callbacks/second.lua
29/Jun/2015 12:31:17 [src/Lua.cpp:2555] ntop_get_dirs() called
29/Jun/2015 12:31:17 [src/Lua.cpp:2515] ntop_is_pro() called
29/Jun/2015 12:31:17 [src/Lua.cpp:2515] ntop_is_pro() called
29/Jun/2015 12:31:17 [pro/LuaHandler.cpp:60] About to decompress 3434 bytes
29/Jun/2015 12:31:17 [pro/LuaHandler.cpp:69] Decompressed 5540 bytes
29/Jun/2015 12:31:17 [pro/LuaHandler.cpp:60] About to decompress 3656 bytes
29/Jun/2015 12:31:17 [pro/LuaHandler.cpp:69] Decompressed 5540 bytes
29/Jun/2015 12:31:17 [pro/LuaHandler.cpp:60] About to decompress 3662 bytes
29/Jun/2015 12:31:17 [pro/LuaHandler.cpp:69] Decompressed 5540 bytes
29/Jun/2015 12:31:17 [pro/LuaHandler.cpp:60] About to decompress 3105 bytes
29/Jun/2015 12:31:17 [pro/LuaHandler.cpp:69] Decompressed 5540 bytes
29/Jun/2015 12:31:17 [pro/LuaHandler.cpp:60] About to decompress 1671 bytes
29/Jun/2015 12:31:17 [pro/LuaHandler.cpp:69] Decompressed 2292 bytes
29/Jun/2015 12:31:17 [src/Lua.cpp:216] ntop_get_interface_names() called

The command will run continuously until it is manually terminated (^C) even on a single packet pcap file. After running the command on the single packet PCAP file for a minute, minute it generated 24 entries in ES before I ended the process.

Environment specs:

Ubuntu 14.04 x64 desktop VM
ntopng -V: 2.0.150531
ES version: 1.4.5

**Comment by ariava** [comment]
@acs5369 how long is the pcap? Would you be able to provide a pcap to reproduce the issue? (only for debugging purposes)

**Comment by acs5369** [comment]
The PCAP contains one ping request packet, nothing else in it. I created the PCAP from a Wireshark capture on a Win7 machine. I believe that the problem may be more due to the setup that I have (processing the PCAP in a separate VM than the capture was done on and no internet connection).

**Comment by lucaderi** [comment]
You misspelled the option name  "es;flows;ntopng-%Y.%m.%d;http://localhost:9200/_bulk;"

This said see https://github.com/ntop/ntopng/commit/1d604d1902bbe703a51e522a0af1c466637dd540
