### ISSUE TITLE
Script failure [/usr/local/share/ntopng/scripts/callbacks/system/discover.lua][attempt to attempt to  a index a string value value a string value]

### ISSUE THREAD

**Issue by jackyaz** [ntop/ntopng#6502]
**Environment**:
* OS name: pfSense
* OS version: CE 2.6.0 (FreeBSD 12.3)
* Architecture: amd64
* ntopng version/revision: v.5.0.220112

**What happened**:
ntopng appears to coredump when running network discovery. System log catches the below error
```
Apr 11 18:00:31 | kernel |   | pid 15828 (ntopng), jid 0, uid 0: exited on signal 11 (core dumped)
```
ntopng log shows this as the last action timestamped the same
```
11/Apr/2022 18:00:31 [LuaEngine.cpp:560] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/system/discover.lua][attempt to attempt to  a index a string value value a string value]
```

**Comment by jackyaz** [comment]
Looks like the pfSense package is a bit older, which might be the problem

**Comment by cardigliano** [comment]
Please try updating to the latest version (5.3) which is available at https://packages.ntop.org/FreeBSD/FreeBSD:12:amd64/latest/
following the instructions at https://www.ntop.org/guides/ntopng/third_party_integrations/pfsense.html
