### ISSUE TITLE
Topology MACs must be hyperlink if present, strings otherwise

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6504]
![Screen Shot 2022-04-12 at 12 08 50](https://user-images.githubusercontent.com/4493366/162936874-ff9afa08-fa3a-467b-9dc2-abf777393047.png)

**Comment by MatteoBiscosi** [comment]
It seems working in my case, please report back
![Screenshot from 2022-05-10 17-30-21](https://user-images.githubusercontent.com/49585191/167666091-fa5da086-c195-4db9-9fcb-618a882fb395.png)
![Screenshot from 2022-05-10 17-30-31](https://user-images.githubusercontent.com/49585191/167666095-9a5d9edb-5f97-46f6-9f08-e56dc8fc6d2a.png)

**Comment by lucaderi** [comment]
Verified as fixed
