### ISSUE TITLE
Unable to add fail2ban endpoint

### ISSUE THREAD

**Issue by yarik2720** [ntop/ntopng#6505]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04.4
* Architecture: amd64
* ntopng version/revision: Community v.5.3.220412

**What happened**:
Tried to add fail2ban endpoint as it was shown on guide. Fail2ban is successfully installed and used in system

**What did you expect to happen?**
In endpoint types there is no fail2ban type to add

**How did you reproduce it?**

**Debug Information**:
![Снимок экрана 2022-04-12 в 16 58 47](https://user-images.githubusercontent.com/1839978/162979317-69b3ab57-6b2f-43c6-b895-147e53d4165a.png)

**Comment by MatteoBiscosi** [comment]
Hi @yarik2720 as written here you can use the f2b endpoint just from the pro version https://www.ntop.org/guides/ntopng/alerts/available_recipients.html
