### ISSUE TITLE
NTOPNG can't connect CLICKHOUSE through command line in file config

### ISSUE THREAD

**Issue by AnhTuanNguyenn** [ntop/ntopng#6506]
hello, i just installed ntopng ( 5.3.220325) on and i want to connect with an Clickhouse VM with command line in : _/usr/local/etc/ntopng/ntopng.conf_

as simple line : -F="clickhouse;IP@9004;ntopng;default;MyPassword"

that seem all work but when i check system on interface ntopng i got this error: 
![Capture](https://user-images.githubusercontent.com/24913199/163011101-bc9fbbee-079c-474f-945e-d6747d9367bf.PNG)
i dont understant why i got this error as a port 9000 can't connected  instead 9004 i was configed.

after that i checked my pfsense and all the flow/alerts was save into pfsense instead Cickhouse vm.

**Comment by lucaderi** [comment]
Can you please execute on shell the above command "cat ...." and report ?

clickhouse-client uses port 9000, 9004 is used for queries. So port 9000 and 9004 must be open.

**Comment by AnhTuanNguyenn** [comment]
Hello Luca,

Before starting ntop i tried connect clickhouse manual with port 9000.
That’s was working.

And then i started ntopng with :
service ntopng start
 i see it connected but i even know the logs has save into pfsense until i
check system and i see the errors

So you want me execute command:
cat */usr/local/etc/ntopng/ntopng.conf ? *

*In the file conf i only added command: -F…. *

*I will send you output tomorrow morning *

**Comment by AnhTuanNguyenn** [comment]
hello @lucaderi ,
this is output de command: cat /usr/local/etc/ntopng/ntopng.conf
![image](https://user-images.githubusercontent.com/24913199/163129710-eaab842a-02be-4d1e-b051-4e22b033ffe5.png)

**Comment by AnhTuanNguyenn** [comment]
> 

yes, i checked port 9000 and 9004 has opened on clickhouse server remote. @lucaderi

**Comment by lucaderi** [comment]
> Can you please execute on shell the above command "cat ...." and report ?
> 
> clickhouse-client uses port 9000, 9004 is used for queries. So port 9000 and 9004 must be open.

Can you please report the execution of the above command?

**Comment by AnhTuanNguyenn** [comment]
> 

hello Luca, which command you want, i don't understand much your question

**Comment by AnhTuanNguyenn** [comment]
if you want execution  cat /usr/local/etc/ntopng/ntopng.conf

```
# The configuration file is similar to the command line, with the exception that an equal
# sign '=' must be used between key and value. Example: -i=p1p2 or --interface=p1p2 For
# options with no value (e.g. -v) the equal is also necessary. Example: "-v=" must be used.
#
#
# -G|--pid-path
# Specifies the path where the PID (process ID) is saved. This option is ignored when
# ntopng is controlled with systemd (e.g., service ntopng start).
#
-G=/var/run/ntopng.pid
#
# -e|--daemon
# This parameter causes ntop to become a daemon, i.e. a task which runs in the background
# without connection to a specific terminal. To use ntop other than as a casual monitoring
# tool, you probably will want to use this option. This option is ignored when ntopng is
# controlled with systemd (e.g., service ntopng start)
#
# -e=
#
# -i|--interface
# Specifies the network interface or collector endpoint to be used by ntopng for network
# monitoring. On Unix you can specify both the interface name (e.g. lo) or the numeric
# interface id as shown by ntopng -h. On Windows you must use the interface number instead.
# Note that you can specify -i multiple times in order to instruct ntopng to create multi-
# ple interfaces.
#
# -i=eth1
# -i=eth2
#
# -w|--http-port
# Sets the HTTP port of the embedded web server.
#
# -w=3000
#
# -m|--local-networks
# ntopng determines the ip addresses and netmasks for each active interface. Any traffic on
# those networks is considered local. This parameter allows the user to define additional
# networks and subnetworks whose traffic is also considered local in ntopng reports. All
# other hosts are considered remote. If not specified the default is set to 192.168.1.0/24.
#
# Commas separate multiple network values. Both netmask and CIDR notation may be used,
# even mixed together, for instance "131.114.21.0/24,10.0.0.0/255.0.0.0".
#
# -m=10.10.123.0/24
# -m=10.10.124.0/24
#
# -n|--dns-mode
# Sets the DNS address resolution mode: 0 - Decode DNS responses and resolve only local
# (-m) numeric IPs 1 - Decode DNS responses and resolve all numeric IPs 2 - Decode DNS
# responses and don't resolve numeric IPs 3 - Don't decode DNS responses and don't resolve
#
# -n=1
#
# -S|--sticky-hosts
# ntopng periodically purges idle hosts. With this option you can modify this behaviour by
# telling ntopng not to purge the hosts specified by -S. This parameter requires an argu-
# ment that can be "all" (Keep all hosts in memory), "local" (Keep only local hosts),
# "remote" (Keep only remote hosts), "none" (Flush hosts when idle).
#
# -S=
#
# -d|--data-dir
# Specifies the data directory (it must be writable by the user that is executing ntopng).
#
# -d=/var/lib/ntopng
#
# -q|--disable-autologout
# Disable web interface logout for inactivity.
#
# -q=
-F="clickhouse;IP@9004;ntopng;default;MyPassWord"
```

i check port 9000 and 9004 is opened:
```

VMs-root@VMs:~# netstat -apn | grep 9000
tcp6 0 0 :::9000 :::* LISTEN 4506/clickhouse-ser
VMs-root@VMs:~# netstat -apn | grep 9004
tcp6 0 0 :::9004 :::* LISTEN 4506/clickhouse-ser
```

**Comment by AnhTuanNguyenn** [comment]
hello @lucaderi 
as i see in the log there are a line cat, so i was tried as 
cat /var/db/ntopng/tmp/clickhouse/clickhouse-6-0-1.1650012602.csv
`2|4|1650012491|1650012493|0|928|75021|47877|27144|0|0|6|2130706433|::|60327|2130706433|::|6379|182|0|11|1|""pfSense01.xxx|6|0|0|0|"localhost"|"localhost"|0|0|1:Ik5bCGbZS6SDUl7NFfYOOEkdvWM=|0|0|0|0|24|24|0|0|0|1|1|12|12|0|0|0|0||`

**Comment by cardigliano** [comment]
@AnhTuanNguyenn please try executing one of the commands reported in the Log Trace similar to the below:

cat /var/db/ntopng/tmp/[...] | /usr/local/bin/clickhouse-client [...] -d "ntopng"

Or please paste here the log in text format and I will give you the exact line to execute

**Comment by AnhTuanNguyenn** [comment]
hello @cardigliano 
thank for your reply
as you told i was execute command and i got this: 
![165723236-ff33d659-7c26-4112-b80c-5ca27ab1af47](https://user-images.githubusercontent.com/24913199/166208680-76672eb2-1f29-4255-b11c-b9fa5153cec2.jpg)


when i check file in /var/db/ntonpg/temp/clickhouse all file has rename .dsc i supposed: 
![165718748-00c19459-5706-40c8-bcd6-c60c2044cc7d](https://user-images.githubusercontent.com/24913199/166208703-88998054-890f-435f-b20b-5cce8c28ae4f.png)



you can find all log System complete in this file text and in sector Clickhouse also

[error clickhouse .txt](https://github.com/ntop/ntopng/files/8581368/error.clickhouse.txt)
[log clickhouse .txt](https://github.com/ntop/ntopng/files/8581372/log.clickhouse.txt)


thanks you advance

**Comment by lucaderi** [comment]
Please repeat the above command with a file that exists out of the clickhouse tmp directory so we can see what is the problem. Please *before* doing that make sure you have updated to the latest ntopng version

**Comment by AnhTuanNguyenn** [comment]
hello Luca, i has installed newest version   5.3.220429 on server test, it's seem better old version but i have alway error 
![test](https://user-images.githubusercontent.com/24913199/165968624-e1b8008c-1a42-43f8-b19a-d98524edcb2d.PNG)

i was find out a file existy in /var/db/ntopng/tmp/clickhouse: 
```
[2.6.0-RELEASE][admin@pfSense01.css.fr]/var/db/ntopng/tmp/clickhouse: ls -la
total 376
drwx------  2 ntopng  ntopng   1536 Apr 29 16:43 .
drwx------  3 ntopng  ntopng    512 Apr 29 16:33 ..
-rw-r--r--  1 root    ntopng     79 Apr 29 16:43 1
-rw-rw-rw-  1 ntopng  ntopng  57125 Apr 29 16:34 clickhouse-1-0-64.1651242869.csv.dsc
-rw-rw-rw-  1 ntopng  ntopng  34892 Apr 29 16:35 clickhouse-1-1-45.1651242933.csv.dsc
-rw-rw-rw-  1 ntopng  ntopng  59500 Apr 29 16:36 clickhouse-1-2-65.1651242996.csv.dsc
-rw-rw-rw-  1 ntopng  ntopng  26057 Apr 29 16:37 clickhouse-1-3-36.1651243058.csv.dsc
-rw-rw-rw-  1 ntopng  ntopng  32154 Apr 29 16:38 clickhouse-1-4-49.1651243121.csv.dsc
-rw-rw-rw-  1 ntopng  ntopng  29754 Apr 29 16:39 clickhouse-1-5-40.1651243186.csv.dsc
-rw-rw-rw-  1 ntopng  ntopng  20026 Apr 29 16:40 clickhouse-1-6-28.1651243246.csv.dsc
-rw-rw-rw-  1 ntopng  ntopng  23421 Apr 29 16:41 clickhouse-1-7-34.1651243311.csv
-rw-rw-rw-  1 ntopng  ntopng  17830 Apr 29 16:42 clickhouse-1-8-25.1651243375.csv
-rw-rw-rw-  1 ntopng  ntopng      0 Apr 29 16:42 clickhouse-1-9.1651243375.csv.tmp
-rw-rw-rw-  1 ntopng  ntopng   4055 Apr 29 16:35 clickhouse-5-0-9.1651242922.csv.dsc
-rw-rw-rw-  1 ntopng  ntopng   2696 Apr 29 16:36 clickhouse-5-1-10.1651242985.csv.dsc
-rw-rw-rw-  1 ntopng  ntopng   4255 Apr 29 16:37 clickhouse-5-2-14.1651243052.csv.dsc
-rw-rw-rw-  1 ntopng  ntopng   1071 Apr 29 16:38 clickhouse-5-3-4.1651243123.csv.dsc
-rw-rw-rw-  1 ntopng  ntopng    806 Apr 29 16:39 clickhouse-5-4-3.1651243195.csv.dsc
-rw-rw-rw-  1 ntopng  ntopng   1341 Apr 29 16:41 clickhouse-5-5-5.1651243313.csv
-rw-rw-rw-  1 ntopng  ntopng    718 Apr 29 16:42 clickhouse-5-6-2.1651243375.csv
-rw-rw-rw-  1 ntopng  ntopng      0 Apr 29 16:42 clickhouse-5-7.1651243375.csv.tmp
-rw-rw-rw-  1 ntopng  ntopng    515 Apr 29 16:35 clickhouse-6-0-2.1651242922.csv.dsc
-rw-rw-rw-  1 ntopng  ntopng    512 Apr 29 16:36 clickhouse-6-1-2.1651242997.csv.dsc
-rw-rw-rw-  1 ntopng  ntopng   1026 Apr 29 16:38 clickhouse-6-2-4.1651243090.csv.dsc
-rw-rw-rw-  1 ntopng  ntopng    786 Apr 29 16:39 clickhouse-6-3-3.1651243196.csv.dsc
-rw-rw-rw-  1 ntopng  ntopng   1026 Apr 29 16:41 clickhouse-6-4-4.1651243313.csv
-rw-rw-rw-  1 ntopng  ntopng    512 Apr 29 16:43 clickhouse-6-5-2.1651243386.csv
-rw-rw-rw-  1 ntopng  ntopng      0 Apr 29 16:43 clickhouse-6-6.1651243386.csv.tmp
```
i chose one of file exist and excuted it : 
`[2.6.0-RELEASE][admin@pfSense01.css.fr]/var/db/ntopng/tmp/clickhouse: cat /var/db/ntopng/tmp/clickhouse/clickhouse-5-6-2.1651243375.csv | /usr/local/bin/clickhouse-client --port 9000 --host "192.168.75.26" --user "default" --password "mypassword" -d "ntopng" --format_csv_delimiter="|" --format_csv_allow_double_quotes true --query="INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR,IPV6_SRC_ADDR,IP_SRC_PORT,IPV4_DST_ADDR,IPV6_DST_ADDR,IP_DST_PORT,L7_PROTO,L7_PROTO_MASTER,L7_CATEGORY,FLOW_RISK,INFO,PROFILE,NTOPNG_INSTANCE_NAME,INTERFACE_ID,STATUS,SRC_COUNTRY_CODE,DST_COUNTRY_CODE,SRC_LABEL,DST_LABEL,SRC_MAC,DST_MAC,COMMUNITY_ID,SRC_ASN,DST_ASN,PROBE_IP,OBSERVATION_POINT_ID,SRC2DST_TCP_FLAGS,DST2SRC_TCP_FLAGS,SCORE,CLIENT_NW_LATENCY_US,SERVER_NW_LATENCY_US,CLIENT_LOCATION,SERVER_LOCATION,SRC_NETWORK_ID,DST_NETWORK_ID,INPUT_SNMP,OUTPUT_SNMP,SRC_HOST_POOL_ID,DST_HOST_POOL_ID,SRC_PROC_NAME,DST_PROC_NAME,SRC_PROC_USER_NAME,DST_PROC_USER_NAME,ALERTS_MAP,SEVERITY,IS_CLI_ATTACKER,IS_CLI_VICTIM,IS_CLI_BLACKLISTED,IS_SRV_ATTACKER,IS_SRV_VICTIM,IS_SRV_BLACKLISTED,ALERT_JSON) FORMAT CSV" 2>&1`
there are no error on this manual execution.

**Comment by AnhTuanNguyenn** [comment]
hello @lucaderi , @cardigliano :)
any news ? :)

**Comment by lucaderi** [comment]
This problem happens only when ntopng is started as a service. We're trying to find a solution. In the meantime please avoid starting ti as a service even though we are on this ticket so we plan to fix it ASAP.

**Comment by AnhTuanNguyenn** [comment]
Thank you and your team, 
waiting your news :)

**Comment by AnhTuanNguyenn** [comment]
Testing on server test, feedback within 7 days, thank Luca :)

**Comment by AnhTuanNguyenn** [comment]
i will update here my daily test: 
after 2h start ntop, they working well but i i got this error you can tell me how to resolve that: 
when i click to button it's not happening, 

![Capture d’écran 2022-05-12 155855](https://user-images.githubusercontent.com/24913199/168093635-a2c6a37b-29bd-4f58-8404-10d99100aaca.png)

**Comment by MatteoBiscosi** [comment]
Hi @AnhTuanNguyenn please tune the -X option manually from the configuration file. Unfortunately ntopng is not able to modify the configuration file in pfSense.
To know which is the error please check https://www.ntop.org/guides/ntopng/cli_options/cli_options.html

**Comment by AnhTuanNguyenn** [comment]
hello @MatteoBiscosi 
day 4 of test: 
thank you, i was tune it, so good so far with ntopng, it working smoothly
but how can i prevent the alerts of ntopng save on my pfsense disk ? can i disable it in setting ? 
i see also in clickhouse there are much alerts was transfered, i love it 
![image](https://user-images.githubusercontent.com/24913199/168612215-16adb077-bc61-498f-a7bc-49e8932f775a.png)

**Comment by MatteoBiscosi** [comment]
Hi @AnhTuanNguyenn yes sure, you can disable alerts from the preferences. However with the latest ntopng version, alerts should take a lot less space, we optimized them a week ago or so. Otherwise you can store alerts in a remote Host with clickhouse installed in. In fact as explained in the documentation https://www.ntop.org/guides/ntopng/clickhouse/clickhouse.html you can have a remote ClickHouse where you can store flows and alerts.
![Screenshot from 2022-05-17 10-16-25](https://user-images.githubusercontent.com/49585191/168763891-d7b8f370-b4c7-4821-9bc6-606c14b9114e.png)
 Closing the issue, Thanks a lot for your reports :)
