### ISSUE TITLE
VLAN Tags are not fully Supported in Historical Alerts and Flows 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6508]
VLAN tags are not properly handled in historical flows and alerts.

**Comment by cardigliano** [comment]
Implemented in da88d0ca8f4203ef0e5485de4d0dc4c8fbfb5e74 0863dc7d8cbfd0ec8d55085bae63f55e189e11e6 and pro 0e9a184edb7450139499a8de4c45e104a7faa97d 618f3b570aa2b3e6983388f3dc23f6cd77f6b410
TODO: missing rendering js function

**Comment by cardigliano** [comment]
Hostname@vlan filter in engaged alerts supported in ea29fc817607af693aa6bf717647ae2d975d09d4
JS rendering implemented in d8165eb738d35b4b0bfea376661a7d299d0528b4
This should be fully implemented now.

**Comment by lucaderi** [comment]
Verified as fixed.
