### ISSUE TITLE
NetBIOS Names should not be used for hostnames

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6509]
The NetBIOS name can be shared by multiple hosts (e.g. wpad). In this cause this name should not be used as label for hosts as you do with DNS names. It can be optionally used as "1.2.3.4 (netbios)" or just "1.2.3.4" and use the netbios name on the tooltip

**Comment by MatteoBiscosi** [comment]
Now NetBIOS names are no more used for hostnames. Still reported however in the host page.

![Screenshot from 2022-04-20 16-30-33](https://user-images.githubusercontent.com/49585191/164254247-71c5754b-acd1-4941-9c1e-a2b7754afdc8.png)

**Comment by MatteoBiscosi** [comment]
Verified as fixed, please reopen if needed
