### ISSUE TITLE
Check Exceptions Do Not Support VLAN Tags

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6510]
In check exceptions, VLAN tags are ignored and thus the exception is applied only to untagged traffic. This ticket is to request the support of VLAN tags in exceptions.

**Comment by cardigliano** [comment]
Backend implemented in da88d0ca8f4203ef0e5485de4d0dc4c8fbfb5e74 and pro 0e9a184edb7450139499a8de4c45e104a7faa97d 618f3b570aa2b3e6983388f3dc23f6cd77f6b410
Frontend implemented in 0863dc7d8cbfd0ec8d55085bae63f55e189e11e6
TODO: IP rendering with vlan in a single link

**Comment by MatteoBiscosi** [comment]
Implemented as requested
