### ISSUE TITLE
Implement Content Exception Filtering

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6511]
Certain alerts that contain domain names (e.g. Suspicious DGA domain) or URLs (e.g. Suspicious SQL Injection) should be used to set exceptions. In this case, the panel below will also include the domain name or URL portion that can be used to ignore the exception. When this is implemented, the user should be able to edit the proposed information (e.g. use only a subset of the domain name).

![image](https://user-images.githubusercontent.com/4493366/163219510-88479a46-4d44-44b9-809d-d06e3b3f18ea.png)

**Comment by MatteoBiscosi** [comment]
Implemented as requested in the latest version
