### ISSUE TITLE
Rework Protocols Menu

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6515]
The tables menu implementation is suboptimal: when an optimal as when an entry is selected all other options disappear as you can see

Service Map
![Screen Shot 2022-04-17 at 18 59 28](https://user-images.githubusercontent.com/4493366/163724755-fd54fc23-77ef-4f96-938a-df4ec801988a.png)

Flows
![Screen Shot 2022-04-17 at 19 00 46](https://user-images.githubusercontent.com/4493366/163724780-397b1b4d-95a4-40b0-a875-e56863155332.png)

In operating systems instead, it does not work like that, as only the selected item has a marker (or is highlighted) but the other options are still available, so when you switch from an option to another you do not have to deselected and selected again (so two steps instead of one) the menu item.
![Screen Shot 2022-04-17 at 19 02 06](https://user-images.githubusercontent.com/4493366/163724828-ab5c22c5-144c-4cc8-88ad-002a2ab0ceea.png)

**Comment by MatteoBiscosi** [comment]
Issue fixed in the latest version
![image](https://user-images.githubusercontent.com/49585191/210347883-3287cf11-ee6a-4cd0-82d3-cebd47c18dc0.png)
