### ISSUE TITLE
Some broken link when using the proxy mode

### ISSUE THREAD

**Issue by gmourani** [ntop/ntopng#652]
Hello,

When using the --http-prefix /ntopng option to run ntopng behind a proxy, I've noticed the following pages having some broken link.

top_hosts.lua - Link at the right of the page doesn't work (missing /ntopng/ in front of the link)
show_alerts.lua - Link into the Description column doesn't work (missing /ntopng/ in front of the link)

Gerhard,

**Comment by gmourani** [comment]
Simone,

Patches worked well for the "top_hosts.lua" page but no for the “show_alerts.lua" page.

Gerhard,

**Comment by simonemainardi** [comment]
Note that Patches will affect newely generated alerts only
Il 08/lug/2016 19:01, "gmourani" notifications@github.com ha scritto:

**Comment by gmourani** [comment]
I’ve purged all alerts but still not working. Also, I’ve found that purging all alerts globally doesn’t reset the alert counter for individual host even if all removed!

**Comment by simonemainardi** [comment]
so please post a screenshot of the alerts for which hyperlinks till don't have the http prefix. I need to see the type of alerts.

**Comment by gmourani** [comment]
Hello,

Attached is a screenshot.

Gerhard,

**Comment by simonemainardi** [comment]
can't see the attchement.

**Comment by gmourani** [comment]
OK, here in a zip format.

**Comment by simonemainardi** [comment]
no, there is no attachment. please go to the github issue page and upload the screenshot from there
