### ISSUE TITLE
Wrong tab switching from Host Alerts Engaged to Flow Alerts (Past)

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#6524]
Switching from Host Alerts Engaged to Flow Alerts leads to an empty page as Flow Alerts does not have the Engage page, it should go to Past.

**Comment by cardigliano** [comment]
<img width="537" alt="Screen Shot 2022-04-20 at 09 17 37" src="https://user-images.githubusercontent.com/7548711/164172383-cc8d6dbf-0823-465b-a9e4-df3ac38f84ca.png">
<img width="548" alt="Screen Shot 2022-04-20 at 09 17 53" src="https://user-images.githubusercontent.com/7548711/164172430-4aea15c7-3ec5-41db-8a33-4da0769aec3b.png">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
