### ISSUE TITLE
can't see any flows in the  "Historical Flow Explorer".

### ISSUE THREAD

**Issue by Yoshihiro-jp** [ntop/ntopng#6525]
**Environment**:
* OS name: [e.g. Ubuntu] Ubuntu 
* OS version: [e.g. 18.04] 20.04.4 LTS
* Architecture: [e.g. amd64] x86_64
* ntopng version/revision: [e.g. 5.1.211223]  5.2.220408

**What happened**:

Problems procedure: 
"Interface" menu in the ntopng → "Historical Data" → Push the "Actions" button with any application → Choose "Raw Flows"
Result:  I can't see any flows in the  "Historical Flow Explorer".

No problem procedure:
"Interface" menu in the ntopng → "Historical Data" → Choose "Raw Flows" → filter an application
Result: I  can see  the flow in the  "Historical Flow Explorer".

**What did you expect to happen?**
Even if I clicked the "Actions" button then go to the "Historical Flow Explorer" it should show flows in the screen.

**How did you reproduce it?**
"Interface" menu in the ntopng → "Historical Data" → Push the "Actions" button with any application → Choose "Raw Flows"

**Debug Information**:
Kindly refer to the attached file.
[no raw flows.zip](https://github.com/ntop/ntopng/files/8519736/no.raw.flows.zip)

**Comment by MatteoBiscosi** [comment]
Hi @Yoshihiro-jp thanks again for your reports.
Now the issue should be fixed, as you can see, I filtered for tls and then jumped to raw flows and it's working.
A new build is going to start soon please wait for 2/3 hours and the new update should be available.
Waiting for your feedback.

![Screenshot from 2022-04-20 12-50-21](https://user-images.githubusercontent.com/49585191/164215280-38599c66-3262-4559-bac5-f297d77df517.png)
![Screenshot from 2022-04-20 12-50-07](https://user-images.githubusercontent.com/49585191/164215301-75121ac0-6fc9-4245-a897-3b689a729de3.png)

**Comment by Yoshihiro-jp** [comment]
Dear @MatteoBiscosi ,

Using the version 5.2.220420 I confirmed it to be fixed.
Thank you for your quick modification.

regards,
Yoshihiro
