### ISSUE TITLE
Historical Flows: Invalid drill down 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6527]
Inside a flow clicking on the drill-down icon

![Screen Shot 2022-04-20 at 18 03 27](https://user-images.githubusercontent.com/4493366/164274060-987099d4-3e3a-430e-91ed-2d269d0f1999.png)

we go to

![Screen Shot 2022-04-20 at 18 04 02](https://user-images.githubusercontent.com/4493366/164274118-939e19f5-2d92-4e4d-8a94-0451a7c09ecf.png)

that is wrong as there is no filter selected.

This needs to be fixed with a different filter such as info = resercom.nautas-tech.com and Application = XXX where XXX is the L7 protocol of the flow

**Comment by MatteoBiscosi** [comment]
Fixed.
Consider the possibility that the flow the user select could be the first of a kind and so no flows can be found in the historical view (flows are going to be put inside the historical view after being removed from the live view)

![Screenshot from 2022-04-21 10-24-08](https://user-images.githubusercontent.com/49585191/164412747-96b28f2a-13dc-4ffa-bb19-354edbd90c48.png)
![Screenshot from 2022-04-21 10-23-53](https://user-images.githubusercontent.com/49585191/164412756-bed7829f-d3ae-4180-acc6-a6c0c6d19b32.png)

**Comment by lucaderi** [comment]
Verified as fixed.
