### ISSUE TITLE
Improve Historical Flows Drill Down

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6528]
As with  #6527 add a drill-down icon for all flows that have info, such as HTTP and DNS that have for instance the resolved domain name.

Example add the drill-down icon here:
![image](https://user-images.githubusercontent.com/4493366/164276011-c6b309b5-346f-4dbd-be71-24c0f97a32ed.png)

**Comment by MatteoBiscosi** [comment]
Feature implemented

![Screenshot from 2022-04-21 10-38-23](https://user-images.githubusercontent.com/49585191/164415482-1e0fc3b9-6b9e-4b72-9218-798831c15f73.png)
![Screenshot from 2022-04-21 10-38-33](https://user-images.githubusercontent.com/49585191/164415488-638273e8-a1ff-49f5-917b-63ec8a21963f.png)

**Comment by lucaderi** [comment]
Verified as fixed
