### ISSUE TITLE
Errors in ntopng.service File

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6529]
Apr 20 20:54:23 ntopint systemd[1]: /etc/systemd/system/ntopng.service:7: Unknown key name 'Required-Start' in section 'Unit', ignoring.
Apr 20 20:54:23 ntopint systemd[1]: /etc/systemd/system/ntopng.service:8: Unknown key name 'Required-Stop' in section 'Unit', ignoring.

This on ubuntu 20.04

**Comment by cardigliano** [comment]
Removed in e428151d06d12bfeb4b951e61f59f0a7bff4b14b
