### ISSUE TITLE
[Lua.cpp:5134] WARNING: Script failure [/usr/share/ntopng/scripts/lua/host_details_ndpi.lua][table index is nil]

### ISSUE THREAD

**Issue by surajit26** [ntop/ntopng#653]
Hi,
I am new on this and I have installed ntopng 2.4.160705 in centos 7. However, I am getting following error message while selecting host>click on any host>protocol.
/usr/share/ntopng/scripts/lua/host details ndpi.lua

Run time status also showing same following error.
09/Jul/2016 21:37:48 [Lua.cpp:5134] WARNING: Script failure [/usr/share/ntopng/scripts/lua/host_details_ndpi.lua][table index is nil]

I am attaching error message and run time status for your reference.

Thanks a ton in advance for your reference.
![ntopng error](https://cloud.githubusercontent.com/assets/20370958/16708865/6ea60c10-461e-11e6-8e6b-bcf0d320c6d6.jpg)

**Comment by simonemainardi** [comment]
already fixed and discussed in #638, please update your 2.4 package.

**Comment by surajit26** [comment]
![ntopng error 1](https://cloud.githubusercontent.com/assets/20370958/16758180/dbd6a090-482d-11e6-9515-82981a24213d.jpg)
I am already running it in version 2.4 however, issue till exists. Please help.

**Comment by simonemainardi** [comment]
I am not sure that build include the fix. Please, let me check. I'll report back today.
