### ISSUE TITLE
Info Field is Not Necessary on the Periodicity Map

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6538]
The Info field is necessary only in the service map and it has to be removed from the periodicity map as it is always empty

![image](https://user-images.githubusercontent.com/4493366/164625513-6a93a5d4-7db0-40d2-aabc-79b3f460de96.png)

**Comment by MatteoBiscosi** [comment]
Fixed pro version

**Comment by lucaderi** [comment]
Verified as fixed.
