### ISSUE TITLE
Internal Error while viewing Localhost

### ISSUE THREAD

**Issue by Artapel** [ntop/ntopng#654]
Good day.

We are having an issue while trying to view data for local Hosts

When ever i click on a local host i get the following error

HTTP/1.1 500 Internal server error Content-Type: text/html Connection: close   Script "/usr/share/ntopng/scripts/lua/host_details.lua" returned an error:

Any Ideas?

**Comment by simonemainardi** [comment]
please, report both the error that you get from the web browser and any error that appears in the log (console or log file). Also, post the version you are using.

**Comment by Artapel** [comment]
Hi Here are the Program Versions

n2disk.x86_64 0:2.7.160711-4663
nbox.noarch 0:2.5.0-508
nprobe.x86_64 0:7.5.160711-5345
ntopng.x86_64 0:2.5.160711-1322
ntopng-data.noarch 0:2.5.160711-1322
pfring.x86_64 0:6.5.0-713
pfring-dkms.noarch 0:6.5.0-713

Here are the Host details

Linux monitor 3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Here are the browser error output
HTTP/1.1 500 Internal server error Content-Type: text/html Connection: close [http://192.168.0.18:3000/img/warning.png]  Script "/usr/share/ntopng/scripts/lua/host_details.lua" returned an error:
/usr/share/ntopng/scripts/lua/host_details.lua:379: attempt to concatenate field 'deviceIfIdx' (a nil value)

Here are the log output

@monitor ~]# tail -f /var/log/ntopng/ntopng.log | grep 196.29.140.222
11/Jul/2016 11:50:14 [Lua.cpp:2267] ntop_rrd_update(/var/tmp/ntopng/6/rrd/196/29/140/222/24/bytes.rrd) N:615943132:222312648
11/Jul/2016 11:50:14 [Lua.cpp:2267] ntop_rrd_update(/var/tmp/ntopng/6/rrd/196/29/140/222/24/SSL.rrd) N:11772989:1830157
11/Jul/2016 11:50:14 [Lua.cpp:2267] ntop_rrd_update(/var/tmp/ntopng/6/rrd/196/29/140/222/24/HTTP.rrd) N:1142786:191629
11/Jul/2016 11:50:14 [Lua.cpp:2267] ntop_rrd_update(/var/tmp/ntopng/6/rrd/196/29/140/222/24/H323.rrd) N:14097782:6050299
11/Jul/2016 11:50:14 [Lua.cpp:2267] ntop_rrd_update(/var/tmp/ntopng/6/rrd/196/29/140/222/24/Unknown.rrd) N:31246:582002
11/Jul/2016 11:50:14 [Lua.cpp:2267] ntop_rrd_update(/var/tmp/ntopng/6/rrd/196/29/140/222/24/RDP.rrd) N:588898329:213650917
11/Jul/2016 11:50:18 [Flow.cpp:1516] Emitting Flow: { "8": "192.168.0.122", "7": 49936, "12": "196.29.140.222", "11": 3389, "4": 6, "57590": 88, "57591": "RDP", "6": 26, "2": 1, "1": 60, "24": 1, "23": 60, "22": 1468230102, "21": 1468230614, "57595": 0.369000, "57596": 35.938000, "DST_IP_COUNTRY": "ZA", "DST_IP_LOCATION": [ 28.137800, -25.963600 ], "NTOPNG_INSTANCE_NAME": "monitor.local.domain", "INTERFACE": "enp1s0f1", "PASS_VERDICT": true }
11/Jul/2016 11:50:23 [Flow.cpp:1516] Emitting Flow: { "8": "192.168.1.101", "7": 49241, "12": "196.29.140.222", "11": 3389, "4": 6, "57590": 88, "57591": "RDP", "6": 26, "2": 3163, "1": 231716, "24": 0, "23": 0, "22": 1468230320, "21": 1468230623, "57595": 0.000000, "57596": 0.000000, "DST_IP_COUNTRY": "ZA", "DST_IP_LOCATION": [ 28.137800, -25.963600 ], "NTOPNG_INSTANCE_NAME": "monitor.local.domain", "INTERFACE": "enp1s0f1", "PASS_VERDICT": true }
11/Jul/2016 11:50:23 [Flow.cpp:1516] Emitting Flow: { "8": "196.29.140.222", "7": 3389, "12": "192.168.1.101", "11": 49241, "4": 6, "57590": 88, "57591": "RDP", "6": 26, "2": 2880, "1": 993845, "24": 0, "23": 0, "22": 1468230320, "21": 1468230623, "58": 2, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "ZA", "SRC_IP_LOCATION": [ 28.137800, -25.963600 ], "NTOPNG_INSTANCE_NAME": "monitor.local.domain", "INTERFACE": "enp1s0f1", "PASS_VERDICT": true }
11/Jul/2016 11:50:28 [Flow.cpp:1516] Emitting Flow: { "8": "192.168.70.54", "7": 50051, "12": "196.29.140.222", "11": 3389, "4": 6, "57590": 88, "57591": "RDP", "6": 26, "2": 1, "1": 60, "24": 0, "23": 0, "22": 1468230116, "21": 1468230628, "57595": 0.000000, "57596": 0.000000, "DST_IP_COUNTRY": "ZA", "DST_IP_LOCATION": [ 28.137800, -25.963600 ], "NTOPNG_INSTANCE_NAME": "monitor.local.domain", "INTERFACE": "enp1s0f1", "PASS_VERDICT": true }
11/Jul/2016 11:50:28 [Flow.cpp:1516] Emitting Flow: { "8": "196.29.140.222", "7": 3389, "12": "192.168.70.54", "11": 50051, "4": 6, "57590": 88, "57591": "RDP", "6": 26, "2": 1, "1": 64, "24": 0, "23": 0, "22": 1468230116, "21": 1468230628, "58": 13, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "ZA", "SRC_IP_LOCATION": [ 28.137800, -25.963600 ], "NTOPNG_INSTANCE_NAME": "monitor.local.domain", "INTERFACE": "enp1s0f1", "PASS_VERDICT": true }
11/Jul/2016 11:50:36 [Lua.cpp:2298] ntop_rrd_fetch(/var/tmp/ntopng/6/rrd/196/29/140/222/bytes.rrd)
11/Jul/2016 11:50:36 [Lua.cpp:2298] ntop_rrd_fetch(/var/tmp/ntopng/6/rrd/196/29/140/222/H323.rrd)
11/Jul/2016 11:50:36 [Lua.cpp:2298] ntop_rrd_fetch(/var/tmp/ntopng/6/rrd/196/29/140/222/ICMP.rrd)
11/Jul/2016 11:50:36 [Lua.cpp:2298] ntop_rrd_fetch(/var/tmp/ntopng/6/rrd/196/29/140/222/NetBIOS.rrd)
11/Jul/2016 11:50:36 [Lua.cpp:2298] ntop_rrd_fetch(/var/tmp/ntopng/6/rrd/196/29/140/222/RDP.rrd)
11/Jul/2016 11:50:36 [Lua.cpp:2298] ntop_rrd_fetch(/var/tmp/ntopng/6/rrd/196/29/140/222/RTMP.rrd)
11/Jul/2016 11:50:36 [Lua.cpp:2298] ntop_rrd_fetch(/var/tmp/ntopng/6/rrd/196/29/140/222/SSL.rrd)
11/Jul/2016 11:50:36 [Lua.cpp:2298] ntop_rrd_fetch(/var/tmp/ntopng/6/rrd/196/29/140/222/Unknown.rrd)
11/Jul/2016 11:50:36 [Lua.cpp:2298] ntop_rrd_fetch(/var/tmp/ntopng/6/rrd/196/29/140/222/bytes.rrd)
11/Jul/2016 11:50:36 [Lua.cpp:2298] ntop_rrd_fetch(/var/tmp/ntopng/6/rrd/196/29/140/222/icmp.rrd)
11/Jul/2016 11:50:36 [Lua.cpp:2298] ntop_rrd_fetch(/var/tmp/ntopng/6/rrd/196/29/140/222/tcp.rrd)
11/Jul/2016 11:50:36 [Lua.cpp:2298] ntop_rrd_fetch(/var/tmp/ntopng/6/rrd/196/29/140/222/udp.rrd)
11/Jul/2016 11:50:36 [Lua.cpp:2298] ntop_rrd_fetch(/var/tmp/ntopng/6/rrd/196/29/140/222/bytes.rrd)
11/Jul/2016 11:50:39 [Flow.cpp:1516] Emitting Flow: { "8": "192.168.1.231", "7": 49537, "12": "196.29.140.222", "11": 3389, "4": 6, "57590": 88, "57591": "RDP", "6": 26, "2": 1, "1": 60, "24": 0, "23": 0, "22": 1468230126, "21": 1468230638, "57595": 0.000000, "57596": 0.000000, "DST_IP_COUNTRY": "ZA", "DST_IP_LOCATION": [ 28.137800, -25.963600 ], "NTOPNG_INSTANCE_NAME": "monitor.local.domain", "INTERFACE": "enp1s0f1", "PASS_VERDICT": true }
11/Jul/2016 11:50:39 [Flow.cpp:1516] Emitting Flow: { "8": "196.29.140.222", "7": 3389, "12": "192.168.1.231", "11": 49537, "4": 6, "57590": 88, "57591": "RDP", "6": 26, "2": 1, "1": 64, "24": 0, "23": 0, "22": 1468230126, "21": 1468230638, "58": 2, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "ZA", "SRC_IP_LOCATION": [ 28.137800, -25.963600 ], "NTOPNG_INSTANCE_NAME": "monitor.local.domain", "INTERFACE": "enp1s0f1", "PASS_VERDICT": true }
11/Jul/2016 11:50:39 [Flow.cpp:1516] Emitting Flow: { "8": "192.168.65.56", "7": 56158, "12": "196.29.140.222", "11": 3389, "4": 6, "57590": 88, "57591": "RDP", "6": 26, "2": 7, "1": 564, "24": 0, "23": 0, "22": 1468230334, "21": 1468230467, "57595": 0.000000, "57596": 0.000000, "DST_IP_COUNTRY": "ZA", "DST_IP_LOCATION": [ 28.137800, -25.963600 ], "NTOPNG_INSTANCE_NAME": "monitor.local.domain", "INTERFACE": "enp1s0f1", "PASS_VERDICT": true }
11/Jul/2016 11:50:39 [Flow.cpp:1516] Emitting Flow: { "8": "196.29.140.222", "7": 3389, "12": "192.168.65.56", "11": 56158, "4": 6, "57590": 88, "57591": "RDP", "6": 26, "2": 5, "1": 734, "24": 0, "23": 0, "22": 1468230334, "21": 1468230467, "58": 65, "57595": 0.000000, "57596": 0.000000, "SRC_IP_COUNTRY": "ZA", "SRC_IP_LOCATION": [ 28.137800, -25.963600 ], "NTOPNG_INSTANCE_NAME": "monitor.local.domain", "INTERFACE": "enp1s0f1", "PASS_VERDICT": true }

Regards
[Corne Kruger]

**Comment by simonemainardi** [comment]
said that I can't reproduce, I've added an extra check to prevent the error.
