### ISSUE TITLE
Alerts not displayed

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6544]
**Environment**:
* OS name: [e.g. Ubuntu] Ubuntu
* OS version: [e.g. 18.04] 20.04
* Architecture: [e.g. amd64] x86_64
* ntopng version/revision: [e.g. 5.1.211223] ntopng Enterprise L v.5.3.220424 (Ubuntu 20.04.4 LTS) |

**What happened**:
Alerts are not displayed anymore

<img width="1652" alt="Screenshot 2022-04-24 at 09 21 35" src="https://user-images.githubusercontent.com/38549755/164965933-6baf2463-412b-47cc-8fbe-53c92735d103.png">

before update
<img width="1631" alt="Screenshot 2022-04-24 at 09 09 26" src="https://user-images.githubusercontent.com/38549755/164965944-e6d1b276-955b-4469-bbeb-346ef69343b4.png">

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu, could you please tell me, by opening the web browser developer tool (f12 or right click and then click inspect), if there are any errors and tell me the request and the answer done?
![Screenshot from 2022-04-27 10-17-35](https://user-images.githubusercontent.com/49585191/165473721-d9df1875-6525-4947-af7a-decb67bd9205.png)

**Comment by martinscheu** [comment]
Hi @MatteoBiscosi 
Like this?
<img width="2024" alt="Screenshot 2022-04-29 at 13 32 57" src="https://user-images.githubusercontent.com/38549755/165936756-0cdf52cb-4cc4-45cd-9fba-7e437209e54a.png">
Otherwise I can give you access to the system

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu yes exactly as you did.
@uccidibuti took care of it. Please update and let him know

**Comment by uccidibuti** [comment]
Hi Martin, this bug should be fixed with commits 0b9f5cf4f6156df31276812baf44213aaeb0fd58 and 91b67b2941506d32fc537f990d0a0e620be33df3 . Let me know if is still present.

**Comment by martinscheu** [comment]
yes, I can see the alerts previously shown under "unknown"
Thanks Lorenzo @uccidibuti
