### ISSUE TITLE
Problems installing clickhouse

### ISSUE THREAD

**Issue by hdsjahuen** [ntop/ntopng#6546]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]

**What happened**:

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

The installation of clickhouse was carried out according to the steps in the documentation above, executing the statement
yum install -y yum-utils
yum-config-manager --add-repo https://packages.clickhouse.com/rpm/clickhouse.repo
yum install -y clickhouse-server clickhouse-client
sudo /etc/init.d/clickhouse-server start
When this statement *clickhouse-client -h 127.0.0.1*is executed, the following

ClickHouse client version 22.4.2.1 (official build).
Connected to 127.0.0.1:9000 as user default. 
Connected to ClickHouse server version 22.4.2 revision 54455.

Warnings:
* Linux transparent hugepape are set to "always".

CNSDPWTOP01 :)

However, when I open the ntopng Web UI, the following statement appears on the page：
The database architecture migration is in progress and is waiting for the database ntopng to start. Once the database is ready, you will be redirected. Depending on the size database of the existing database, this operation may take a long time. Migration is performed only once and only during major version upgrades.

We waited a whole day, but still no response.
What should I do in this case?

**Comment by hdsjahuen** [comment]
ntopng version: 5.3.220419[Enterprise/Professional buld]

**Comment by lucaderi** [comment]
Please upgrade to the latest ntopng release where the problem is fixed
