### ISSUE TITLE
Active monitoring speed test on raspbian os not working

### ISSUE THREAD

**Issue by 4ULAB** [ntop/ntopng#6547]
**Environment**:
* OS name: [Raspbian GNU/Linux ]
* OS version: [10 buster]
* Architecture: [32 bit]
* ntopng version/revision: [ntopng Professional v.5.3.220425 rev.17530]

**What happened**:

If I set an active monitoring on the speedtest, the result is always red and never green, even though the connection is faster than the value set in the monitoring.

**What did you expect to happen?**

I expected to be able to monitor the speed of the connection at various times of the day

**How did you reproduce it?**

just add an active monitoring with the speedtest and then check if the ntop data is congruent with a simple speedtest

**Debug Information**:

![PXL_20220426_084127068 MP](https://user-images.githubusercontent.com/66877818/165263297-6e9c0964-4699-4350-8084-51157fcebaf6.jpg)
![Screenshot (20)](https://user-images.githubusercontent.com/66877818/165263314-02c24214-bae7-49b7-8574-6f923fdf54e3.png)

**Comment by MatteoBiscosi** [comment]
Hi @Mirco980 we are currently working on that problem, it seems there is some problem with the speedtest library

**Comment by lucaderi** [comment]
Verified as fixed. New RPi packages will be built later today
