### ISSUE TITLE
Alerts still generated for allowed hosts

### ISSUE THREAD

**Issue by rusqq** [ntop/ntopng#6549]
**Environment**:
* OS name: [e.g. Ubuntu] Ubuntu
* OS version: [e.g. 18.04] 20.04
* Architecture: [e.g. amd64] x86_64
* ntopng version/revision: [e.g. 5.1.211223]  Enterprise L v.5.1.220124 rev.16555 

**What happened**:

Alerts are still generated for allowed hosts: 
![image](https://user-images.githubusercontent.com/96235374/165290250-5769ae12-a1a9-4c9a-b21d-1432006f279e.png)

**What did you expect to happen?**
n/a

**How did you reproduce it?**
n/a

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @rusqq please update to the latest ntopng version, we no more support the 5.1 version.
Update to the latest stable version (5.2) or dev version (5.3) and let me know.

**Comment by MatteoBiscosi** [comment]
Hi @rusqq as you can see, the exclude in the latest ntopng version (5.3.220427) it's working correctly, infact no alert was triggered for this flow
![Screenshot from 2022-04-27 11-33-28](https://user-images.githubusercontent.com/49585191/165489584-6092ba5f-a912-4c9c-9efa-e900452cfc4e.png)
![Screenshot from 2022-04-27 11-32-53](https://user-images.githubusercontent.com/49585191/165489594-ddbd0ba2-7879-4d3d-9cff-6d47d6c652d0.png)
