### ISSUE TITLE
--data-dir option missing in Ntopng Windows x64 v.2.4.270616 ?

### ISSUE THREAD

**Issue by jmunty** [ntop/ntopng#655]
Hi
Has the --data-dir option been deprecated?

It appears in the Version 2.4 User Manual for NtopNG for Version for June 2016.
But it doesn't appear in the list of commands when i do a  ntopng /c -h
And if i actually use the option from the command line, it doesn't do anything.
I also checked with procmon on Windows and can't see ntopng attempting to access the directory i specify in --data-dir,.... so looks like it's not in use any more?

Thanks

**Comment by lucaderi** [comment]
Do not change this setting on Windows
