### ISSUE TITLE
How to view the history browser in a single interface in ntopng

### ISSUE THREAD

**Issue by hdsjahuen** [ntop/ntopng#6550]
**What would you like to add or change?**:

**Why do you and others need this?**:

After I installed clickhouse, I found that I could do a historical browser view, but since I have two interfaces, one for ens33 and one for ens37, I also view them both view:all.
When I want to view the history browser, I find that I can only view the view:all interface, but not the individual interface to view the history data, is there something I haven't configured yet? Or is there something I'm doing wrong there?
I would like to be able to view historical data either as a single interface or as a combination of both interfaces

**Comment by hdsjahuen** [comment]
Please tell me how to view the historical data of a single interface

**Comment by MatteoBiscosi** [comment]
Hi @hdsjahuen this is a wanted behaviour.
To check the flows from a specific interface, you have to go to the historical flow page and add a filter; there should be a filter for the interface, select that and select the interface you want
