### ISSUE TITLE
Elasticsearch 8 support for flow dumps

### ISSUE THREAD

**Issue by stuartjk1606** [ntop/ntopng#6552]
NTOPNG requires support for Elasticsearch 8.

The current version of Elasticsearch (8.1) does not support the field _type. This was depricated in elasticsearch 7 and is removed altogether in 8. Also the current templates avaialble in the current Canonical release of NTOPNG 5.2.220420 does not have a valid elasticsearch v8 version which also fails.

Configuring NTOPNG to connect to Elasticsearch 8 returns the following error when trying to update the template:

```
28/Apr/2022 16:54:58 [Utils.cpp:1531] Posted JSON to http://10.20.2.10:9200/_template/ntopng_template
28/Apr/2022 16:54:58 [Utils.cpp:1344] [JSON] {"error":{"root_cause":[{"type":"parse_exception","reason":"unknown key [template] in the template "}],"type":"parse_exception","reason":"unknown key [template] in the template "},"status":400}
28/Apr/2022 16:54:58 [Utils.cpp:1539] WARNING: Unexpected HTTP response code received 400
28/Apr/2022 16:55:00 [ElasticSearch.cpp:316] ERROR: Unable to send ntopng template (/usr/share/ntopng/httpdocs/misc/ntopng_template_elk.json) to ES
```

and the following error when trying to send flow dumps:

```
28/Apr/2022 16:55:13 [Utils.cpp:1531] Posted JSON to http://10.20.2.10:9200/_bulk
28/Apr/2022 16:55:13 [Utils.cpp:1344] [JSON] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"},"status":400}
28/Apr/2022 16:55:13 [Utils.cpp:1539] WARNING: Unexpected HTTP response code received 400
28/Apr/2022 16:55:13 [ElasticSearch.cpp:176] ERROR: ES: POST request for 4 flows (5226 bytes) failed
```

**Comment by MatteoBiscosi** [comment]
Hi @stuartjk1606 for the ntopng stable version (5.2), ntopng template follows the 7.1 version. I'm going to update the dev version with the latest ECS format available (8.1)

**Comment by MatteoBiscosi** [comment]
Hi @stuartjk1606 added ECS 8.1 support to ntopng flow dumps.
This support is going to be available only from ntopng 5.3 version on.
The support for ECS 8.1 was added following https://www.elastic.co/guide/en/ecs/current/index.html

![Screenshot from 2022-04-29 17-46-17](https://user-images.githubusercontent.com/49585191/165979045-0cb6a183-3eb7-4fa6-ad5a-fe9f38b1c6ef.png)

**Comment by stuartjk1606** [comment]
Thanks for the work there @MatteoBiscosi , unfortunately I will not be able to test it yet as I have hit the next hurdle on my upgrade list, Ubuntu 22. I was hoping the Jammy binaries would be available by now but may have to fire up my old ubuntu 20 gateway if they do not come through soon.

**Comment by stuartjk1606** [comment]
Quick question though, is it specific to Elasticsearch 8.1 or covering any version of Elasricsearch 8.x? Elastic is currently pushing out 8.2.

**Comment by MatteoBiscosi** [comment]
Hi @stuartjk1606 . I'm trying to stay tuned with the latest Elasticsearch version. Unfortunately for each version I have to check it. If you are able to check and give me a feedback that would be wonderful. However between 8.1 and 8.2 shouldn't change that much, so it should be working with it to, but it still need to be tested.
Closing the ticket. Please reopen if a problem arise or a new Elasticsearch version is released and it's no more working with ntopng :)

**Comment by MichaelKirgus** [comment]
Hi @MatteoBiscosi,
I recently upgraded from Elasticsearch 7.14 to Elasticsearch 8.2.1.
With ntopng version v.5.3.220529 and Elasticsearch 8.2.1 the flow export to Elasticsearch seems not working anymore:
`May 29 23:48:26 netflow01 ntopng[14453]: 29/May/2022 23:48:26 [ElasticSearch.cpp:189] ES: Buffered request with 9 flows (11024 bytes)
May 29 23:48:26 netflow01 ntopng[14453]: 29/May/2022 23:48:26 [Utils.cpp:1346] [JSON] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"},"status":400}
May 29 23:48:26 netflow01 ntopng[14453]: 29/May/2022 23:48:26 [Utils.cpp:1533] Posted JSON to elasticsearch06:9200/_bulk
May 29 23:48:26 netflow01 ntopng[14453]: 29/May/2022 23:48:26 [Utils.cpp:1444] [NAMELOOKUP_TIME 0.01][CONNECT_TIME 0.01][APPCONNECT_TIME 0.00][PRETRANSFER_TIME 0.01][REDIRECT_TIME 0.00][STARTTRANSFER_TIME 0.01][TOTAL_TIME 0.01]
May 29 23:48:26 netflow01 ntopng: [Utils.cpp:1541] WARNING: Unexpected HTTP response code received 400
May 29 23:48:26 netflow01 ntopng[14453]: 29/May/2022 23:48:26 [Utils.cpp:1541] WARNING: Unexpected HTTP response code received 400
May 29 23:48:26 netflow01 ntopng: [ElasticSearch.cpp:196] ERROR: ES: POST request for 9 flows (11024 bytes) failed
`

It seems that _type is not valid anymore in 8.2.1...
