### ISSUE TITLE
IEC 60870 analysis is not working

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6554]
OS name: [e.g. Ubuntu] Ubuntu
    OS version: [e.g. 18.04] 20.04
    Architecture: [e.g. amd64] x86_64
    ntopng version/revision: [e.g. 5.1.211223] ntopng Enterprise L v.5.3.220405 rev.17390 (Ubuntu 20.04.4 LTS) |

**What happened**:
The IEC 60870-5-104 flow analysis in active flow is not working:
<img width="1628" alt="Screenshot 2022-04-28 at 22 35 53" src="https://user-images.githubusercontent.com/38549755/165842745-839d490c-af1f-4acd-ab99-60205780896f.png">

or not displayed at all:
<img width="1441" alt="Screenshot 2022-04-28 at 22 37 06" src="https://user-images.githubusercontent.com/38549755/165842567-c757034d-021e-46de-aa8f-4562e0a75318.png">

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu I pushed an update and now it seems working. Please update in a couple of hours and let me know
![Screenshot from 2022-04-29 16-10-27](https://user-images.githubusercontent.com/49585191/165961595-5ffb7d4c-dfa8-4fa9-93d3-294759a5762b.png)

**Comment by martinscheu** [comment]
Hi Matteo, 
On the production system it doesn't work.
Let me know if we need to check on that system.
I get only this:
<img width="1796" alt="Screenshot 2022-05-02 at 06 50 11" src="https://user-images.githubusercontent.com/38549755/166186769-865435f8-7081-46dc-a391-1e7877cc7707.png">

but the system has more than one TypeID

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu as you can see from your screenshot, the flow has no transition, for this reason no chart is displayed. The chart is displayed if there is at least one transition (see my screenshot above)

**Comment by lucaderi** [comment]
Fixed in cf516f7411feba3a4d11d4acc30138446d16b8e1

**Comment by martinscheu** [comment]
works fine now, thanks @lucaderi !
