### ISSUE TITLE
nprobe will not install on raspberry pi 4

### ISSUE THREAD

**Issue by lukepenick** [ntop/ntopng#6558]
When I try to do the install from the instructions : 
wget https://packages.ntop.org/RaspberryPI/apt-ntop_1.0.190416-469_all.deb
sudo dpkg -i apt-ntop_1.0.190416-469_all.deb
sudo apt-get update

sudo apt-get install ntopng nprobe n2n

Nothing will install. When I do the packages individually, everything installs but nprobe.

I get the following error:

sudo apt-get install nprobe
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nprobe:armhf : Depends: libevent-2.1:armhf but it is not installable
                Recommends: ntopng-data:armhf but it is not installable
E: Unable to correct problems, you have held broken packages.

I have tried using the -f flag in install but still come up empty handed.

OS is:  PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"

I do have ntopng-data installed as well as libevent-2.1-7. 

(Shown through "apt list --installed")
libevent-2.1-7/stable,now 2.1.12-stable-1 arm64 [installed,automatic]
ntopng-data/unknown,now 5.3.220501 all [installed]
ntopng/unknown,now 5.3.220501-17586 armhf [installed]

**Comment by lucaderi** [comment]
Package updated, please report.

**Comment by lukepenick** [comment]
Works! Thank you!

**Comment by odhiambo** [comment]
pi@hass:~ $ wget https://packages.ntop.org/RaspberryPI/apt-ntop.deb
--2023-03-30 18:46:04--  https://packages.ntop.org/RaspberryPI/apt-ntop.deb
Resolving packages.ntop.org (packages.ntop.org)... 167.99.215.164, 2a03:b0c0:2:d0::d27:3001
Connecting to packages.ntop.org (packages.ntop.org)|167.99.215.164|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3226 (3.2K) [application/vnd.debian.binary-package]
Saving to: ‘apt-ntop.deb.1’

apt-ntop.deb.1                                              100%[========================================================================================================================================>]   3.15K  --.-KB/s    in 0s

2023-03-30 18:46:05 (41.3 MB/s) - ‘apt-ntop.deb.1’ saved [3226/3226]

pi@hass:~ $ sudo dpkg -i  apt-ntop.deb
Selecting previously unselected package apt-ntop.
(Reading database ... 126922 files and directories currently installed.)
Preparing to unpack apt-ntop.deb ...
Unpacking apt-ntop (2.9-16) ...
Setting up apt-ntop (2.9-16) ...
Installing ntop GPG key. Please wait...
gpg: key 3D84C955924F7599: "Luca Deri <deri@ntop.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
pi@hass:~ $ sudo apt-get install ntopng nprobe n2n
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package nprobe
pi@hass:~ $

**Comment by odhiambo** [comment]
pi@hass:~ $ wget https://packages.ntop.org/RaspberryPI/apt-ntop.deb
--2023-03-30 18:46:04--  https://packages.ntop.org/RaspberryPI/apt-ntop.deb
Resolving packages.ntop.org (packages.ntop.org)... 167.99.215.164, 2a03:b0c0:2:d0::d27:3001
Connecting to packages.ntop.org (packages.ntop.org)|167.99.215.164|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3226 (3.2K) [application/vnd.debian.binary-package]
Saving to: ‘apt-ntop.deb.1’

apt-ntop.deb.1                                              100%[========================================================================================================================================>]   3.15K  --.-KB/s    in 0s

2023-03-30 18:46:05 (41.3 MB/s) - ‘apt-ntop.deb.1’ saved [3226/3226]

pi@hass:~ $ sudo dpkg -i  apt-ntop.deb.1
Selecting previously unselected package apt-ntop.
(Reading database ... 126922 files and directories currently installed.)
Preparing to unpack apt-ntop.deb ...
Unpacking apt-ntop (2.9-16) ...
Setting up apt-ntop (2.9-16) ...
Installing ntop GPG key. Please wait...
gpg: key 3D84C955924F7599: "Luca Deri <deri@ntop.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
pi@hass:~ $ sudo apt-get install ntopng nprobe n2n
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package nprobe
