### ISSUE TITLE
Missing ICMP Type/Code Mapping To Symbolic Values

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6560]
![Screen Shot 2022-05-02 at 21 13 33](https://user-images.githubusercontent.com/4493366/166310360-999eeded-045a-44e5-bf75-fc99da84d6cb.png)

**Comment by MatteoBiscosi** [comment]
Mapped like following. Used the IANA https://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml and the relatives RFC
![Screenshot from 2022-05-03 11-03-57](https://user-images.githubusercontent.com/49585191/166428488-ff5ea7d3-9e41-463b-8267-c36914817e72.png)

**Comment by lucaderi** [comment]
Verified as fixed. Please note that this ticket might have originated this issue #6563
