### ISSUE TITLE
Make Dropdown Style Uniform in Recipients/EndPoints

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6562]
![image](https://user-images.githubusercontent.com/4493366/166441326-6a82ef2e-150d-4b46-917f-eb9f703baaa6.png)

**Comment by MatteoBiscosi** [comment]
Closing the ticket. This feature currently cannot be implemented. When the whole page is going to be changed to vuejs, it's going to be automatically fixed.
