### ISSUE TITLE
Unmapped nDPI Alerts Trigger Errors

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6563]
How to reproduce it
- Open a shell and do ping -s 1024 192.168.1.1

Then open the page with your flow

![image](https://user-images.githubusercontent.com/4493366/166461465-8557285d-7eef-473d-9d46-98ddca337d0a.png)

and on the screen appears

03/May/2022 15:26:24 [LuaEngineNtop.cpp:45] ERROR: ntop_map_score_to_severity : expected number[@pos 1], got nil

**Comment by lucaderi** [comment]
Also, note that the type is wrong in the flow list and not the same as the one I see in the flow details

![image](https://user-images.githubusercontent.com/4493366/166461818-34badc96-8c7e-4e57-87e7-4f70b2769724.png)

**Comment by MatteoBiscosi** [comment]
Now it's working correctly. Regarding the note above, please follow issue #6571
![Screenshot from 2022-05-06 10-44-35](https://user-images.githubusercontent.com/49585191/167098594-df8fb533-24a7-4668-9864-aa32d0ecc4a8.png)

**Comment by lucaderi** [comment]
Verified as fixed
