### ISSUE TITLE
Info field is ignored in alerts on ClickHouse

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6564]
![Screen Shot 2022-05-03 at 22 31 01](https://user-images.githubusercontent.com/4493366/166560982-8217b0f4-36b3-4223-81ef-bcad600700ec.png)

 SELECT 4 entity_id, (toUnixTimestamp(tstamp_end) - toUnixTimestamp(tstamp)) duration, toUnixTimestamp(tstamp) as tstamp_epoch, toUnixTimestamp(tstamp_end) as tstamp_end_epoch, * FROM `flow_alerts_view` WHERE (first_seen >= 1651607980 AND first_seen <= 1651609780) AND ( alert_status = 0 ) AND (alert_id != 0) AND (interface_id = 1)  ORDER BY score desc LIMIT 10 OFFSET 0

**Comment by MatteoBiscosi** [comment]
Verified as fixed, tested on HSol
