### ISSUE TITLE
Inconsistent ClickHouse Flow/Alert Format

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6565]
The same record on ClickHouse is formatted differently if accessed as Alert or as Flow. Example

- Searched as Flow
![Screen Shot 2022-05-03 at 22 36 39](https://user-images.githubusercontent.com/4493366/166561911-1b12d3fe-e406-4ccf-a95f-88a419d0f1a9.png)

- Searched as Alert
![Screen Shot 2022-05-03 at 22 35 35](https://user-images.githubusercontent.com/4493366/166561914-1fb312fe-19e2-4b69-a3c8-4c4587044783.png)

The alert view has all the HTTP information that is missing from the flow part. This is to request to unify the views or add to flow view all the info (e.g. HTTP in this case) that is stored in the database

**Comment by MatteoBiscosi** [comment]
Implemented as requested and tested on HSol
