### ISSUE TITLE
CSS Inconsistency Across Browsers

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6566]
- Chrome
![Screen Shot 2022-05-04 at 13 12 33](https://user-images.githubusercontent.com/4493366/166671292-afeac232-9562-4821-82d2-52fd059367cb.png)
- Safari
![Screen Shot 2022-05-04 at 13 10 14](https://user-images.githubusercontent.com/4493366/166671297-2bb951bf-a278-420c-8472-436d316bf722.png)

This used to work and after the webpack changes it is now broken

**Comment by MatteoBiscosi** [comment]
Verified as fixed, as explained before, the bs5 select is not supported by each browser, for this reason I'm changing them to the select2 component
