### ISSUE TITLE
Error deleting alerts

### ISSUE THREAD

**Issue by zynex-mbrunner** [ntop/ntopng#6567]
When trying to delete alerts (single or range), I get the following error message on the endpoint  "/lua/http_status_code.lua"
__.png/scripts/lua/modules/alert_store/flow_alert_store.lua:89: attempt to index a nil value (field 'integer index')

**Environment**:
* OS name: Ubuntu
* OS version: 20.04.4
* Architecture: amd64
* ntopng version/revision: 5.3.220504

**What happened**: Deleting alerts (single or range) does not work. It generates a 500er error.

**Debug Information**:

May 04 16:32:22 ntopng ntopng[557679]: [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/rest/v2/delete/flow/alerts.lua][...png/scripts/lua/modules/alert_store/flow_alert_store.lua:89: attempt to index a nil value (field 'integer index')]
May 04 16:32:22 ntopng ntopng[557679]: 04/May/2022 16:32:22 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/rest/v2/delete/flow/alerts.lua][...png/scripts/lua/modules/alert_store/flow_alert_store.lua:89: attempt to index a nil value (field 'integer index')]
May 04 16:32:57 ntopng ntopng[557679]: [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/rest/v2/delete/flow/alerts.lua][...png/scripts/lua/modules/alert_store/flow_alert_store.lua:89: attempt to index a nil value (field 'integer index')]
May 04 16:32:57 ntopng ntopng[557679]: 04/May/2022 16:32:57 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/rest/v2/delete/flow/alerts.lua][...png/scripts/lua/modules/alert_store/flow_alert_store.lua:89: attempt to index a nil value (field 'integer index')]
May 04 16:36:00 ntopng ntopng[557679]: [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/rest/v2/delete/flow/alerts.lua][...png/scripts/lua/modules/alert_store/flow_alert_store.lua:89: attempt to index a nil value (field 'integer index')]
May 04 16:36:00 ntopng ntopng[557679]: 04/May/2022 16:36:00 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/rest/v2/delete/flow/alerts.lua][...png/scripts/lua/modules/alert_store/flow_alert_store.lua:89: attempt to index a nil value (field 'integer index')]
May 04 16:36:39 ntopng ntopng[557679]: [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/rest/v2/delete/flow/alerts.lua][...png/scripts/lua/modules/alert_store/flow_alert_store.lua:89: attempt to index a nil value (field 'integer index')]
May 04 16:36:39 ntopng ntopng[557679]: 04/May/2022 16:36:39 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/rest/v2/delete/flow/alerts.lua][...png/scripts/lua/modules/alert_store/flow_alert_store.lua:89: attempt to index a nil value (field 'integer index')]

**Comment by cardigliano** [comment]
@uccidibuti please check the "Remove" action, it actually removes the single alert now, but it does not refresh the datatable (you have to reload the page to see the alerts disappear)

<img width="229" alt="Screen Shot 2022-05-06 at 12 15 42" src="https://user-images.githubusercontent.com/7548711/167113256-a358a98e-c769-470c-b065-f9d1fa620744.png">

**Comment by MatteoBiscosi** [comment]
Hi @mbrunner77 please update to the latest ntopng version and the issue should be fixed (tried in 3 labs and it's working on them all).
Reopen if needed
