### ISSUE TITLE
Implement Filters on Empty fields

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6569]
The goal is to have something like INFO <> ''

![Screen Shot 2022-05-04 at 19 09 25](https://user-images.githubusercontent.com/4493366/166742042-abde9c0e-df44-40b6-995f-0292bf4023f6.png)
![Screen Shot 2022-05-04 at 19 10 52](https://user-images.githubusercontent.com/4493366/166742121-57993531-32a1-4b1c-a5d7-ed2fe28853e9.png)

**Comment by cardigliano** [comment]
It seems the backend actually supports "" (empty value), @uccidibuti please fix the validator to allow empty strings

**Comment by lucaderi** [comment]
Verified as fixed
