### ISSUE TITLE
Ntopng does not come back up after restart

### ISSUE THREAD

**Issue by Artapel** [ntop/ntopng#657]
I ran a systemctl restart ntopng but Ntopng never became available again

Here are the last and only entried that was written to the ntopng.log file

tail -f /var/log/ntopng/ntopng.log
"
11/Jul/2016 15:49:55 [main.cpp:37] Shutting down...
11/Jul/2016 15:49:56 [main.cpp:34] Ok I am leaving now
"

When i check the "systemctl status ntopng"i get the following

>  systemctl status ntopng
> ● ntopng.service - Start/stop ntopng program
>    Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: disabled)
>    Active: activating (start) since Tue 2016-07-12 10:03:51 SAST; 2s ago
>   Process: 12887 ExecStop=/etc/systemd/scripts/ntopng stop (code=exited, status=0/SUCCESS)
>   Control: 12896 (ntopng)
>    CGroup: /system.slice/ntopng.service
>            ├─12896 /bin/bash /etc/systemd/scripts/ntopng start
>            └─12930 sleep 1
> 
> Jul 12 10:03:51 monitor.cbc-ct.co.za systemd[1]: Starting Start/stop ntopng program...
> Jul 12 10:03:51 monitor.cbc-ct.co.za ntopng[12896]: Starting ntopng: /usr/bin/ntopng: error while loading shared libraries: libzmq.so.4: cannot open shared object file: No such file or directory

I have tried the following guides and finished them successfully.

http://packages.ntop.org/centos/
https://github.com/ntop/ntopng/issues/450

Here are my Setup
Linux monitor.cbc-ct.co.za 3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
yup up

zeromq-debuginfo.x86_64                                                                                     4.0.5-1.el7.centos                                                                                              saltstack-zeromq4
zeromq-devel.x86_64                                                                                         4.1.4-5.el7                                                                                                     epel
zeromq3.x86_64                                                                                              3.2.5-1.el7                                                                                                     epel
zeromq3-devel.x86_64                                                                                        3.2.5-1.el7                                                                                                     epel

I did a yum update aswell so im on the latest Ntopng version aswell

**Comment by malinkinsa** [comment]
So, i have a this trouble too.
My issues https://github.com/ntop/ntopng/issues/656

**Comment by simonemainardi** [comment]
duplicate, please follow up on the other thread
