### ISSUE TITLE
You are attemping to generate a license for a product 737 days old

### ISSUE THREAD

**Issue by bipin-stcs** [ntop/ntopng#6573]
Hello,

I am getting the below error while generating a license for ntopng

**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 16.04]
* Architecture: [e.g. x86_64]
* ntopng version/revision: [e.g. 4.1.200427]

**What happened**:
Not able to generate license. You are attemping to generate a license for a product 737 days old: please update first to a newever version and then generate your license.

**What did you expect to happen?**

License generation

**How did you reproduce it?**
https://shop.ntop.org/mkntopng/
Provide Details and click generate license

Regards

**Comment by cardigliano** [comment]
@bipin-stcs as reported by the message, the license generator expects a fairly recent version of the software, as we do not support versions which are too old and cannot provide maintenance for those. I suggest to update the software and try again generating the license. Thank you.

**Comment by bipin-stcs** [comment]
Thank you @cardigliano
