### ISSUE TITLE
Undocumented User Authentication via Token

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6576]
ntopng users can be authenticated using user tokens. Unfortunately, this feature is not documented.

**Comment by cardigliano** [comment]
Instructions for creating a session cookie and using it are available at:
https://www.ntop.org/guides/ntopng/api/rest/api_v2.html (see POST lua/rest/v2/create/ntopng/session.lua)
https://www.ntop.org/guides/ntopng/api/rest/examples_v2.html#create-a-session-cookie
