### ISSUE TITLE
When using ntopng, individual IP addresses cannot be viewed

### ISSUE THREAD

**Issue by hdsjahuen** [ntop/ntopng#6577]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]

**What happened**:

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

When I use ntopng, all the other individual IP addresses can be viewed for statistics, but I found that one IP address could not be viewed for statistics and it showed up as not found

**Comment by MatteoBiscosi** [comment]
Hi @hdsjahuen could you please put more information regarding the issue? like ntopng version and some screenshot, cause I'm not understanding which is the problem, if you could add more info it would be better.

**Comment by hdsjahuen** [comment]
![image](https://github.com/hdsjahuen/hk/blob/main/1.png)

This is the display when I want to view this single IP

**Comment by MatteoBiscosi** [comment]
Hi @hdsjahuen consider that timeseries are available only for Local Hosts, like written in the documentation. If you are referring to flows, check if you have some active flows from the live flows page

**Comment by hdsjahuen** [comment]
Thanks, I have one more question, when I do the view, it shows vlan 4095, what does this mean?
![image2](https://github.com/hdsjahuen/hk/blob/main/2.png)

**Comment by MatteoBiscosi** [comment]
It means that there is a VLAN on the network you are currently capturing traffic from and the vlan id is the 4095. So those traffic are currently seen on the vlan 4095

**Comment by hdsjahuen** [comment]
But vlan id 4095 is not available to users, and I did not create this ID

**Comment by MatteoBiscosi** [comment]
Could you please capture some traffic from your interface and send me via e-mail (biscosi at ntop.org) ?
We get the vlan information from the packets, so if we see it we add to the flows information. If you send me an email with a pcap i can try to figure it out if those information are really inside the packets or it's some ntopng bug.

**Comment by hdsjahuen** [comment]
Can you send it to me via jason file? I don't have access to the data server, so I can't capture the packets.

**Comment by MatteoBiscosi** [comment]
Try to check if you have this possibility in ntopng GUI interface page. If you are capturing from a Packet interface, you are a superuser and you have a pro license at least you should be able to capture a pcap directly from ntopng GUI, by clicking that `PCAP Download`
![Screenshot from 2022-05-11 16-24-18](https://user-images.githubusercontent.com/49585191/167873262-aa2f375a-187b-49b6-9f00-ba62d5db361c.png)

**Comment by hdsjahuen** [comment]
Hello, my side is connected to ntopng via TCP, I can't capture packets at this interface, my side is showing no
[image1](https://github.com/hdsjahuen/hk/blob/main/3.png)

Is there any other way to get the data on ntopng?

**Comment by MatteoBiscosi** [comment]
Hi, there is no other way, the only remaining way currently is to capture traffic using tcpdump or something like that in the server side

**Comment by MatteoBiscosi** [comment]
Impossible to understand if it is a bug or not, without a pcap. Closing the issue, please reopen if you are able to get a pcap in order to check it.
