### ISSUE TITLE
LuaEngine Script Failures on Startup (network_discovery.lua)

### ISSUE THREAD

**Issue by Taralas** [ntop/ntopng#6578]
**Environment**:
* OS name: OPNsense Business Edition
* OS version: 22.4, Based on FreeBSD 13.0-STABLE
* Architecture: amd64
* ntopng version/revision: v.5.3.220509

**What happened**:
At startup, ntopng process throws the following errors:

```09/May/2022 07:59:11 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #21 to 'format' (number expected, got nil)]
09/May/2022 07:59:18 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/network_discovery.lua][attempt to index a string value]
```

**What did you expect to happen?**
Startup with no script errors

**How did you reproduce it?**
Clean install of ntopng on OPNsense, restart process

**Debug Information**:

**Comment by Taralas** [comment]
This seems to have been occurring since release v.5.3.220426

**Comment by MatteoBiscosi** [comment]
Please update to the latest version and let me know

**Comment by Taralas** [comment]
Ran through the weekend with the v.5.3.220514 update, Still getting errors, but did not restart

**Comment by Taralas** [comment]
Updated to v.5.3.220516. Got the following:

```16/May/2022 11:49:02 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #21 to 'format' (number expected, got nil)]```

**Comment by Taralas** [comment]
Updated to v.5.3.220517. Got the following:

```17/May/2022 10:07:26 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #21 to 'format' (number expected, got nil)]
17/May/2022 10:09:49 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #21 to 'format' (number expected, got nil)]```

**Comment by MatteoBiscosi** [comment]
Hi @Taralas are you running ntopng with clickhouse or not? Because i'm trying to reproduce it but still no success.
Could you please share your ntopng configuration file?

**Comment by Taralas** [comment]
I do not believe I have moved to clickhouse.

/usr/local/etc/ntopng/ntopng.conf
```-i=ax0
-i=igb1
-i=igb2
-i=igb0
-w=0
-W=3000
-n=1
--community=
-d=/var/db/ntopng-enterprise
```

After updating to 5.3.220520

```20/May/2022 08:37:06 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #21 to 'format' (number expected, got nil)]```

**Comment by MatteoBiscosi** [comment]
Hi @Taralas , gonna check that, however the `--community=` option is wrong, change it to `--community` and the restart ntopng, let me know

**Comment by MatteoBiscosi** [comment]
Which Host checks have you enabled?

**Comment by Taralas** [comment]
The ```--community=``` is generated by the OPNsense configuration agent. Take a look at https://discordapp.com/channels/726054161547919440/801351993560924181/940279273632194592 where @lucaderi asked for it to be added, and it was incorporated as part of a patch back in Feburary 2022.

For hosts checks, not sure what you are looking for.

**Comment by MatteoBiscosi** [comment]
Hi @Taralas please tell me which host checks you enabled.
![Screenshot from 2022-05-23 09-56-19](https://user-images.githubusercontent.com/49585191/169771317-1eaf4018-c4d0-426d-9987-987da5198dda.png)
If it's still not working, could you try unistalling and reinstalling ntopng? because i did a fresh install and i have no error.
When do you get this error? by just starting ntopng or by going in a specific ntopng page?

**Comment by Taralas** [comment]
I get that error whether logged in or not.

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/173816/169902223-5418f39a-d571-40cb-b685-efc007d1c308.png">

I have never put any checks in place, so I would assume they are the default settings. After removing the packages via the OPNsense UI, and removing the /var/db directory, I am still getting an error. Also, the performance seems to be poor, taking 5-15 seconds to go from page to page via the interface.

**Comment by Taralas** [comment]
After purging ntopng and redis from the machine, removing the configuration files, removing the database files, and reinstalling, the performance has returned to normal.

However, still getting the following errors:
```23/May/2022 16:34:31 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #21 to 'format' (number expected, got nil)]```

**Comment by lucaderi** [comment]
I think I have fixed the above problem. Please test it (packages will be available in 1h) and reopen this ticket if necessary

**Comment by Taralas** [comment]
Just updated to 5.3.220524, no change on reporting.

```24/May/2022 10:14:57 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #22 to 'format' (number expected, got nil)]
24/May/2022 10:15:16 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #22 to 'format' (number expected, got nil)]```

Interestingly, their are alerts around the same time for "Periodic Activity Not Executed".

**Comment by cardigliano** [comment]
Latest reported failure message in #6629

`24/May/2022 16:00:34 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/network_discovery.lua][index a stringstring value]`

**Comment by lucaderi** [comment]
> Just updated to 5.3.220524, no change on reporting.
> 
> ```
> 24/May/2022 10:15:16 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #22 to 'format' (number expected, got nil)]```
> 
> Interestingly, their are alerts around the same time for "Periodic Activity Not Executed".
> ```

Your statement is not correct. You used to have issue with parameter 21, and not with 22 (as I fixed 21)

**Comment by Taralas** [comment]
Understood. Sorry about the miss on my part. Also, the process is still terminating unexpectedly without writing to the logs. Last entry was as follows:

```
25/May/2022 17:45:21 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #22 to 'format' (number expected, got nil)]
25/May/2022 17:45:51 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/network_discovery.lua][attempt to index a string value]
```

**Comment by Taralas** [comment]
After updating to v.5.3.220526, getting the following errors:
```
26/May/2022 08:37:10 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #22 to 'format' (number expected, got nil)]
```

**Comment by lucaderi** [comment]
Builds will be created overnight, you are still using the unpatched version

**Comment by Taralas** [comment]
After updating to v.5.3.220527:
```
27/May/2022 08:17:48 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #22 to 'format' (number expected, got string)]
```

**Comment by Taralas** [comment]
After updating to v.5.3.220528:
```
28/May/2022 11:35:25 [shutdown.lua:40] [checks.lua:1009] Script 'connection_failed' configuration is missing from subdir 'flow'. New user script?
.
.
.
28/May/2022 11:36:14 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #22 to 'format' (number expected, got string)]
```

**Comment by Taralas** [comment]
After updating to v.5.3.220530:
```
30/May/2022 12:33:35 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #22 to 'format' (number expected, got string)]
```

**Comment by Taralas** [comment]
Since ticket #6629 was closed already (in regards to process termination during network_discovery.lua run), I will add this here:
```
02/Jun/2022 04:30:15 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/network_discovery.lua][attempt to concatenate a table value]
```
Last log entry before ntopng terminated unexpectedly on v.5.3.220601

**Comment by MatteoBiscosi** [comment]
Hi @Taralas I'm running a vm with opnsense and ntopng latest version. The error seems to be fixed. Please reopen the ticket if this is going to pop up again in your case
