### ISSUE TITLE
Engaged Alerts: Table out of Sync with Chart

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6579]
![Screenshot 2022-05-09 at 17 35 27](https://user-images.githubusercontent.com/4493366/167445601-372276c7-9c1d-436d-9d88-57ac741c8b7d.png)

**Comment by martinscheu** [comment]
Hi @uccidibuti is working on v.5.3.220516

**Comment by MatteoBiscosi** [comment]
Thanks @martinscheu. Verified as fixed
