### ISSUE TITLE
Invalid Alert URL

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6583]
In alerts if you click on the names below

![Screen Shot 2022-05-10 at 12 49 23](https://user-images.githubusercontent.com/4493366/167612175-28406bc9-fea4-4455-af14-1585bd2f2a85.png)

you obtain

![image](https://user-images.githubusercontent.com/4493366/167612275-42cd07e2-451e-41d0-9f7b-ac89c8d7ce06.png)

Note that there are also duplicated info to remove 

![image](https://user-images.githubusercontent.com/4493366/167612459-8b13dd19-42de-498c-83ca-4bfb40f1392e.png)

**Comment by lucaderi** [comment]
Just tested on HS and it seems to be broken

**Comment by MatteoBiscosi** [comment]
Tested with the latest ntopng version on HS and it seems working now.
![Screenshot from 2022-05-11 21-57-21](https://user-images.githubusercontent.com/49585191/167935257-7bfaf062-c8fa-4470-8a47-66a468a8d67d.png)

**Comment by martinscheu** [comment]
Hi @MatteoBiscosi can confirm it is working on  v.5.3.220516
Requested Server Name: a83af62d74a244baf459f2ceba4a94f5.clo.footprintdns.com ] [ Server to Client Traffic: 7.01 KB | Client to Server Traffic: 1.81 KB ]

**Comment by MatteoBiscosi** [comment]
Thanks @martinscheu. Please reopen if needed
