### ISSUE TITLE
Flow Alerts cannot be deleted

### ISSUE THREAD

**Issue by DerRealKeyser** [ntop/ntopng#6584]
**Environment**:
* OS name: pfSense 22.01
* OS version: FreeBSD 12.3
* Architecture: AMD64
* ntopng version/revision: [e.g. 5.3.220510]

**What happened**:
When attemting to delete past flow alerts, nothing happens - the flow Alerts remains in DB

**What did you expect to happen?**
They should be deleted

**How did you reproduce it?**
Tried restarts, reboots but nothing helps. Cannot delete the flow Alerts

**Debug Information**:

10/May/2022 13:51:53 [SQLiteAlertStore.cpp:151] ERROR SQL Error: no such column: STATUS DELETE FROM `flow_alerts` WHERE (tstamp >= 1652181693 AND tstamp <= 1652183493) AND (STATUS != 0)
10/May/2022 13:51:05 [LuaEngine.cpp:595] WARNING Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #21 to 'format' (number expected, got nil)]
10/May/2022 13:50:11 [LuaEngine.cpp:595] WARNING Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #21 to 'format' (number expected, got nil)]
10/May/2022 13:48:06 [LuaEngine.cpp:595] WARNING Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #21 to 'format' (number expected, got nil)]
10/May/2022 13:44:53 [LuaEngine.cpp:595] WARNING Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #21 to 'format' (number expected, got nil)]
10/May/2022 13:44:50 [LuaEngine.cpp:595] WARNING Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #21 to 'format' (number expected, got nil)]
10/May/2022 13:42:48 [LuaEngine.cpp:595] WARNING Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #21 to 'format' (number expected, got nil)]
10/May/2022 13:42:40 [LuaEngine.cpp:595] WARNING Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #21 to 'format' (number expected, got nil)]
10/May/2022 13:42:35 [LuaEngine.cpp:595] WARNING Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #21 to 'format' (number expected, got nil)]
10/May/2022 13:39:49 [SQLiteAlertStore.cpp:151] ERROR SQL Error: no such column: STATUS DELETE FROM `flow_alerts` WHERE (tstamp >= 1652180967 AND tstamp <= 1652182767) AND (STATUS != 0)
10/May/2022 13:36:08 [SQLiteAlertStore.cpp:151] ERROR SQL Error: no such column: STATUS DELETE FROM `flow_alerts` WHERE (tstamp >= 1652180759 AND tstamp <= 1652182559) AND (STATUS != 0)
10/May/2022 13:34:12 [SQLiteAlertStore.cpp:151] ERROR SQL Error: no such column: STATUS DELETE FROM `flow_alerts` WHERE (STATUS != 0) AND ( ALERT_STATUS = 0 ) AND (FLOW_ID = 3234)
10/May/2022 13:30:32 [SQLiteAlertStore.cpp:151] ERROR SQL Error: no such column: STATUS DELETE FROM `flow_alerts` WHERE (STATUS != 0) AND (tstamp >= 1620646191 AND tstamp <= 1652182191)
10/May/2022 13:27:04 [SQLiteAlertStore.cpp:151] ERROR SQL Error: no such column: STATUS DELETE FROM `flow_alerts` WHERE (tstamp >= 1652180201 AND tstamp <= 1652182001) AND (STATUS != 0)
10/May/2022 13:23:24 [SQLiteAlertStore.cpp:151] ERROR SQL Error: no such column: STATUS DELETE FROM `flow_alerts` WHERE (tstamp >= 1652179987 AND tstamp <= 1652181787) AND (STATUS != 0) AND (severity = 5)
10/May/2022 13:22:11 [SQLiteAlertStore.cpp:151] ERROR SQL Error: no such column: STATUS DELETE FROM `flow_alerts` WHERE (tstamp >= 1652179910 AND tstamp <= 1652181710) AND (STATUS != 0)

**Comment by cardigliano** [comment]
This has been fixed in a patch set today (d248d2a158961f5c48115bcdb967bf5303d50212 7025b3dd5b71458d70a234ea21c19dcec359a918 86899d42f757328b6aa62b7be28dfb089646e524), a new software update will be available later today

**Comment by DerRealKeyser** [comment]
Dang, that was fast :-) Looking forward to update my build tomorrow.
