### ISSUE TITLE
OPNsense: Unable to find timezone

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6585]
10/May/2022 11:35:37 [Ntop.cpp:3570] WARNING: Unable to find timezone: using UTC

root@opnsense:~ # ls /var/db/zoneinfo 
ls: /var/db/zoneinfo: No such file or directory

On FreeBSD everything works as usual

root@freebsd13 203> ls -l /var/db/zoneinfo
1 -rw-r--r--  1 root  wheel  12 Jan 18 21:58 /var/db/zoneinfo

**Comment by Taralas** [comment]
You can set the timezone on OPNsense to get rid of that error with tzsetup.

**Comment by lucaderi** [comment]
Unfortunately, OPNsense does not create a symbolic link to the timezone so I had to implement a workaround.

**Comment by Caligo82** [comment]
Since this hasn't been fixed years later... could you be so kind to share your implemented workaround?

I tried creating a symbolic link to my timezone to no avail unfortunatly...
