### ISSUE TITLE
Problems with clickhouse

### ISSUE THREAD

**Issue by hdsjahuen** [ntop/ntopng#6588]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]

**What happened**:

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

Every time the server is shut down or restarted, clickhouse shows that it cannot connect
[image1](https://github.com/hdsjahuen/hk/blob/main/CentOS%207%2064%20%E4%BD%8D-2022-05-11-16-38-20.png)

Then I go to the ntopng screen and it also shows no data
[image2](https://github.com/hdsjahuen/hk/blob/main/CentOS%207%2064%20%E4%BD%8D-2022-05-11-16-36-54.png)

Then I need to re-execute these two commands

[root@localhost hk]# **sudo /etc/init.d/clickhouse-server start**
 chown -R clickhouse: '/var/run/clickhouse-server/'
Will run su -s /bin/sh 'clickhouse' -c '/usr/bin/clickhouse-server --config-file /etc/clickhouse-server/config.xml --pid-file /var/run/clickhouse-server/clickhouse-server.pid --daemon'
Waiting for server to start
Waiting for server to start
Server started
sed：Unable to read /etc/cron.d/clickhouse-server：No that file or directory
[root@localhost hk]# **sudo /etc/init.d/clickhouse-server start**
/var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 7464.
The process with pid = 7464 is already running.
[root@localhost hk]# clickhouse-client -h 127.0.0.1
ClickHouse client version 22.4.5.9 (official build).
Connecting to 127.0.0.1:9000 as user default.
Connected to ClickHouse server version 22.4.5 revision 54455.

Warnings:
 * Linux transparent hugepage are set to "always".
 * Linux threads max count is too low.
 * Available memory at server startup is too low (2GiB).
 * Maximum number of threads is lower than 30000. There could be problems with handling a lot of simultaneous queries.

localhost :) exit
Bye.

Restart ntopng again before i can get in

I would like to ask clickhouse if it is possible to do a boot-up self-start? I don't need to run those two commands, just do it directly as I did before with nindex and you can see the history of ntopng

[root@localhost hk]# ntopng --version
Version:	5.2.220504 [Enterprise/Professional build]
GIT rev:	5.2-stable:df2ab44db34f31be4edaa8a6411e0a41f6555948:20220504
Pro rev:	r4753
Built on:	CentOS Linux release 7.9.2009 (Core)
System Id:	L3B90782E76066B0A--U3B90782E3DFFDD60--OL
Platform:	x86_64
Edition:	Enterprise L (Bundle)
License Type:	Time-Limited [Empty license file]
Validity:	Until Wed May 11 17:00:51 2022

**Comment by MatteoBiscosi** [comment]
Hi @hdsjahuen are your ClickHouse credential right? I mean, when adding the -F option in ntopng to start it, are the values right? for example I use 
`-F "clickhouse;127.0.0.1;ntopng;default;"`
because I have default user with no password

**Comment by hdsjahuen** [comment]
This is my ntopng.conf file
[image](https://github.com/hdsjahuen/hk/blob/main/ntopng.png)

Whenever I restart the server, I check the status of ntopng and it shows the following

[root@localhost hk]# systemctl status ntopng
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/usr/lib/systemd/system/ntopng.service; enabled; vendor preset: disabled)
   Active: active (running) since 四 2022-05-12 10:23:16 CST; 5min ago
  Process: 2401 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /run/ntopng.conf (code=exited, status=0/SUCCESS)
  Process: 2398 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (code=exited, status=0/SUCCESS)
  Process: 2391 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
  Process: 2377 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exited, status=0/SUCCESS)
 Main PID: 2405 (3/flow_checks)
    Tasks: 38
   CGroup: /system.slice/ntopng.service
           └─2405 /usr/bin/ntopng /run/ntopng.conf

5月 12 10:27:26 localhost.localdomain ntopng[2405]: [ClickHouseImport.cpp:91] WARNING: Code: 210. DB::NetException: Connection refused (127.0.0.1:9000). (NETWORK_ERROR)
5月 12 10:27:26 localhost.localdomain ntopng[2405]: 12/May/2022 10:27:26 [ClickHouseImport.cpp:91] WARNING: Code: 210. DB::NetException: Connection refused (127.0.0.1:9000). (NETWORK_ERROR)
5月 12 10:27:26 localhost.localdomain ntopng[2405]: [ClickHouseImport.cpp:90] WARNING: Unable to execute 'cat /var/lib/ntopng/tmp/clickhouse/clickhouse-4-alert-2.1652322368.sql | /usr/bin/clickhouse-client --port ... "ntopng" 2>&1'
5月 12 10:27:26 localhost.localdomain ntopng[2405]: 12/May/2022 10:27:26 [ClickHouseImport.cpp:90] WARNING: Unable to execute 'cat /var/lib/ntopng/tmp/clickhouse/clickhouse-4-alert-2.1652322368.sql | /usr/bin/clic... "ntopng" 2>&1'
5月 12 10:27:26 localhost.localdomain ntopng[2405]: 12/May/2022 10:27:26 [ClickHouseImport.cpp:91] WARNING: Code: 210. DB::NetException: Connection refused (127.0.0.1:9000). (NETWORK_ERROR)
5月 12 10:27:26 localhost.localdomain ntopng[2405]: [ClickHouseImport.cpp:91] WARNING: Code: 210. DB::NetException: Connection refused (127.0.0.1:9000). (NETWORK_ERROR)
5月 12 10:28:05 localhost.localdomain ntopng[2405]: [ClickHouseImport.cpp:90] WARNING: Unable to execute 'cat /var/lib/ntopng/tmp/clickhouse/clickhouse-4-2-115.1652322471.csv | /usr/bin/clickhouse-client --port 90..._double_quotes 
5月 12 10:28:05 localhost.localdomain ntopng[2405]: 12/May/2022 10:28:05 [ClickHouseImport.cpp:90] WARNING: Unable to execute 'cat /var/lib/ntopng/tmp/clickhouse/clickhouse-4-2-115.1652322471.csv | /usr/bin/clickh...|" --format_csv
5月 12 10:28:05 localhost.localdomain ntopng[2405]: 12/May/2022 10:28:05 [ClickHouseImport.cpp:91] WARNING: Code: 210. DB::NetException: Connection refused (127.0.0.1:9000). (NETWORK_ERROR)
5月 12 10:28:05 localhost.localdomain ntopng[2405]: [ClickHouseImport.cpp:91] WARNING: Code: 210. DB::NetException: Connection refused (127.0.0.1:9000). (NETWORK_ERROR)
Hint: Some lines were ellipsized, use -l to show in full.
[root@localhost hk]# 



At this point I need to execute this statement：
sudo /etc/init.d/clickhouse-server start

But the first time this statement is executed it shows no directory for that file, and then when I execute it a second time it shows that the process is already running

When first run the display shows：
[root@localhost hk]# sudo /etc/init.d/clickhouse-server start
 chown -R clickhouse: '/var/run/clickhouse-server/'
Will run su -s /bin/sh 'clickhouse' -c '/usr/bin/clickhouse-server --config-file /etc/clickhouse-server/config.xml --pid-file /var/run/clickhouse-server/clickhouse-server.pid --daemon'
Waiting for server to start
Waiting for server to start
Server started
sed：Unreadable /etc/cron.d/clickhouse-server：Not having that file or directory

When the second run shows：
[root@localhost hk]# sudo /etc/init.d/clickhouse-server start
/var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 6007.
The process with pid = 6007 is already running.

If you check the ntopng status at this point, you will see that it is normal.
[root@localhost hk]# systemctl status ntopng
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/usr/lib/systemd/system/ntopng.service; enabled; vendor preset: disabled)
   Active: active (running) since 四 2022-05-12 10:46:46 CST; 2s ago
  Process: 9949 ExecStopPost=/bin/rm -rf /run/ntopng.conf /run/ntopng.conf.raw /run/ntopng.pid (code=exited, status=0/SUCCESS)
  Process: 9974 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /run/ntopng.conf (code=exited, status=0/SUCCESS)
  Process: 9969 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (code=exited, status=0/SUCCESS)
  Process: 9965 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
  Process: 9951 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exited, status=0/SUCCESS)
 Main PID: 9977 (ntopng)
    Tasks: 7
   CGroup: /system.slice/ntopng.service
           └─9977 /usr/bin/ntopng /run/ntopng.conf

5月 12 10:46:47 localhost.localdomain ntopng[9977]: 12/May/2022 10:46:47 [NtopPro.cpp:574] WARNING: [LICENSE] ntopng will now run in Enterprise L edition for 10 minutes
5月 12 10:46:47 localhost.localdomain ntopng[9977]: 12/May/2022 10:46:47 [NtopPro.cpp:576] WARNING: [LICENSE] before returning to community mode
5月 12 10:46:47 localhost.localdomain ntopng[9977]: [NtopPro.cpp:574] WARNING: [LICENSE] ntopng will now run in Enterprise L edition for 10 minutes
5月 12 10:46:47 localhost.localdomain ntopng[9977]: 12/May/2022 10:46:47 [NtopPro.cpp:578] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
5月 12 10:46:47 localhost.localdomain ntopng[9977]: 12/May/2022 10:46:47 [NtopPro.cpp:580] WARNING: [LICENSE] or run ntopng in community mode starting
5月 12 10:46:47 localhost.localdomain ntopng[9977]: 12/May/2022 10:46:47 [NtopPro.cpp:581] WARNING: [LICENSE] ntopng --community
5月 12 10:46:47 localhost.localdomain ntopng[9977]: [NtopPro.cpp:576] WARNING: [LICENSE] before returning to community mode
5月 12 10:46:47 localhost.localdomain ntopng[9977]: [NtopPro.cpp:578] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
5月 12 10:46:47 localhost.localdomain ntopng[9977]: [NtopPro.cpp:580] WARNING: [LICENSE] or run ntopng in community mode starting
5月 12 10:46:47 localhost.localdomain ntopng[9977]: [NtopPro.cpp:581] WARNING: [LICENSE] ntopng --community
[root@localhost hk]# 


I don't know if there is something wrong with my settings, I need to restart clickhouse after every reboot

**Comment by hdsjahuen** [comment]
Hi, I re-installed and deployed ntopng on my side and also re-installed cilckhouse, but I still have the problem I mentioned above, I don't know if I had a problem installing clickhouse, here are the steps of my installation

yum install -y yum-utils
yum-config-manager --add-repo https://packages.clickhouse.com/rpm/clickhouse.repo
yum install -y clickhouse-server clickhouse-client
sudo /etc/init.d/clickhouse-server start
clickhouse-client

Then I add the phrase -F "clickhouse;127.0.0.1;ntopng;default;" inside the /etc/ntopng/ntopng.conf file


I wonder what's wrong with this step-by-step approach?

**Comment by lucaderi** [comment]
Type
sudo systemctl enable clickhouse-server
then reboot and it should work

**Comment by hdsjahuen** [comment]
thanks
