### ISSUE TITLE
You're not supposed to be here!

### ISSUE THREAD

**Issue by uber99** [ntop/ntopng#6590]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04] 
* Architecture: [e.g. amd64]
* ntopng version/revision: [4.2.210624 (0)]

**What happened**:
When going to view by ip in flow i am getting error message 

**What did you expect to happen?**
view connections to ip 

**How did you reproduce it?**
click on ip and get that error message 

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @uber99 are you getting the error when you jump to this page?
![Screenshot from 2022-05-12 10-04-31](https://user-images.githubusercontent.com/49585191/168022475-ca2de498-8d04-4919-b80d-323fa416c7df.png)

**Comment by uber99** [comment]
Hi 

When i go to hosts or any part of the system and you click on ip to drill down you get this.

You're not supposed to be here!
Internal server error
__.local/share/ntopng/scripts/lua/modules/plugins_utils.lua:997: module 'active_monitoring.am_utils' not found:__no field package.preload['active_monitoring.am_utils']__no file '/var/db/ntopng/plugins0/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/var/db/ntopng/plugins0/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/var/db/ntopng/plugins0/status_definitions/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/flow_status_definitions/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/recipients/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/notifications/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/recipients/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/var/db/ntopng/plugins0/alert_definitions/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/alert_definitions/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/recipients/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/recipients/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/var/db/ntopng/plugins0/ts_schemas/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/timeseries/custom/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/timeseries/schemas/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/timeseries/drivers/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/var/db/ntopng/plugins0/http_lint/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/recipients/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/flow_dbms/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/timeseries/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/i18n/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/pools/active_monitoring/am_utils.lua'__no file '/usr/local/share/ntopng/scripts/lua/modules/active_monitoring/am_utils.lua'__no file '/usr/local/share/lua/5.3/active_monitoring/am_utils.lua'__no file '/usr/local/share/lua/5.3/active_monitoring/am_utils/init.lua'__no file '/usr/local/lib/lua/5.3/active_monitoring/am_utils.lua'__no file '/usr/local/lib/lua/5.3/active_monitoring/am_utils/init.lua'__no file './active_monitoring/am_utils.lua'__no file './active_monitoring/am_utils/init.lua'__no file '/usr/local/lib/lua/5.3/active_monitoring/am_utils.so'__no file '/usr/local/lib/lua/5.3/loadall.so'__no file './active_monitoring/am_utils.so'__no file '/usr/local/lib/lua/5.3/active_monitoring.so'__no file '/usr/local/lib/lua/5.3/loadall.so'__no file './active_monitoring.so'

**Comment by MatteoBiscosi** [comment]
Hi @uber99 sorry but i'm not understanding how to reproduce your error, could you please send me a screenshot on where to click to reproduce it? Also, could you please send me your ntopng.conf file?

**Comment by uber99** [comment]
![1](https://user-images.githubusercontent.com/85244223/168044504-01e71dba-2137-48dd-b542-221a90b5edb1.PNG)
![2](https://user-images.githubusercontent.com/85244223/168044785-16fa363a-73f3-4672-a349-c7fd59efb0b0.PNG)

If you click on any of these ip address you get that error above

**Comment by MatteoBiscosi** [comment]
Hi @uber99 please update to the latest ntopng version. We currently support only 5.3 (dev) and 5.2 (stable) version

**Comment by uber99** [comment]
Thanks, I have had look around but cant seem to find the updater in the software. 
Pfsence package manager is also saying this is upto date. 

Thanks

**Comment by MatteoBiscosi** [comment]
Hi @uber99 please follow up the installation of the ntopng documentation https://www.ntop.org/guides/ntopng/third_party_integrations/pfsense.html?highlight=pfsense
Like pointed out in #6589 you need to install our ntopng not the one shipped with pfSense because it's version it's totally different and unfortunately we do not support it
