### ISSUE TITLE
Explain offline mode in ntopng documentation

### ISSUE THREAD

**Issue by uccidibuti** [ntop/ntopng#6593]
To avoid all ntopng external request (that could slow down the ntopng execution if a firewall is present) there is a possibility to start ntopng with ```--offline``` flag. All the possibility external requests made by ntopng are explained at: https://www.ntop.org/support/faq/to-what-ip-domain-names-ntopng-connects-to/ . 
It needs to add this information to the Ntong documentation.

**Comment by MatteoBiscosi** [comment]
Implemented as requested, the documentation can be found here https://www.ntop.org/guides/ntopng/cli_options/cli_options.html?highlight=offline
