### ISSUE TITLE
Why big data stream warnings and maximum traffic don't match

### ISSUE THREAD

**Issue by hdsjahuen** [ntop/ntopng#6594]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]

**What happened**:

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

When using ntopng, I found that there is a large data stream in the warning message, which is defined as 1GB, but if I check it, the maximum data inside the whole data is only 30Mbit/s. It is reasonable to say that if there is a large data stream warning, then the whole received or sent data should be more than 1GB, so why is it only 30Mbit/s in this one?

[image1](https://github.com/hdsjahuen/hk/blob/main/7.png)
[image2](https://github.com/hdsjahuen/hk/blob/main/8.png)

**Comment by MatteoBiscosi** [comment]
Hi @hdsjahuen this behavior is normal.
The elephant flow alert is going to be triggered when a flow surpasses a total of X bytes; these bytes are configured in the elephant flow alert
![Screenshot from 2022-05-13 10-09-11](https://user-images.githubusercontent.com/49585191/168240290-c4a9f796-0dfb-4699-9b2a-5f15fa628c01.png)
 It means that when a flow create more then 1GB of traffic from local to remote or viceversa, this alert is going to be triggered.
This traffic could be created over the time, for instance if the traffic lasted for 1 day and the alert is triggered then it means that until the triggered alert, the flow created a TOTAL of more then 1 GB and this traffic could be even a total of 2 days of traffic.
So in your case it's probably a flow that's living for a lot of time and little by little it got to a total traffic of more then 1 GB
