### ISSUE TITLE
ntopng access over https broken

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6595]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223] : ntopng Enterprise L v.5.3.220512 (Ubuntu 20.04.4 LTS) 

**What happened**:
Access of ntopng GUI over https is not working.
Doesn't matter -W:3001 or --https-port:3001

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by lucaderi** [comment]
Please use -W=3001 or --https-port=3001 and report

**Comment by martinscheu** [comment]
sorry, typo
I meant it doesn't matter if I use
--https-port=3001
or
-W=3001

**Comment by Batnun** [comment]
So it's not only me...
https://github.com/ntop/ntopng/issues/6591

**Comment by lucaderi** [comment]
Just tested on a clean host 
- removed everything
- clean installed ntopng
- started as root@office:/home/deri# ntopng -w 0 -W 3000

This is the log

root@office:/home/deri# ntopng -w 0 -W 3000
13/May/2022 14:40:20 [Redis.cpp:151] Successfully connected to redis 127.0.0.1:6379@0
13/May/2022 14:40:20 [Redis.cpp:151] Successfully connected to redis 127.0.0.1:6379@0
13/May/2022 14:40:20 [NtopPro.cpp:315] [LICENSE] Reading license from /etc/ntopng.license
13/May/2022 14:40:20 [NtopPro.cpp:486] [LICENSE] /etc/ntopng.license: found valid Enterprise L (Bundle) license
13/May/2022 14:40:20 [NetworkInterface.cpp:3267] Cleanup interface dummy
13/May/2022 14:40:20 [PF_RINGInterface.cpp:69] Reading packets from PF_RING v.8.1.0 interface eno1...
13/May/2022 14:40:20 [Ntop.cpp:2581] Registered interface eno1 [id: 0]
13/May/2022 14:40:20 [PF_RINGInterface.cpp:69] Reading packets from PF_RING v.8.1.0 interface lo...
13/May/2022 14:40:20 [Ntop.cpp:2581] Registered interface lo [id: 3]
13/May/2022 14:40:20 [PF_RINGInterface.cpp:69] Reading packets from PF_RING v.8.1.0 interface eno2...
13/May/2022 14:40:20 [Ntop.cpp:2581] Registered interface eno2 [id: 4]
13/May/2022 14:40:20 [PF_RINGInterface.cpp:69] Reading packets from PF_RING v.8.1.0 interface docker0...
13/May/2022 14:40:20 [Ntop.cpp:2581] Registered interface docker0 [id: 7]
13/May/2022 14:40:20 [PF_RINGInterface.cpp:69] Reading packets from PF_RING v.8.1.0 interface enp2s0f0...
13/May/2022 14:40:20 [Ntop.cpp:2581] Registered interface enp2s0f0 [id: 14]
13/May/2022 14:40:21 [PF_RINGInterface.cpp:69] Reading packets from PF_RING v.8.1.0 interface enp2s0f1...
13/May/2022 14:40:21 [Ntop.cpp:2581] Registered interface enp2s0f1 [id: 15]
13/May/2022 14:40:21 [main.cpp:337] PID stored in file /var/run/ntopng.pid
13/May/2022 14:40:21 [Geolocation.cpp:149] Loaded database dbip-asn-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip-asn-lite.mmdb][ip_version: 6]
13/May/2022 14:40:21 [Geolocation.cpp:149] Loaded database dbip-city-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip-city-lite.mmdb][ip_version: 6]
13/May/2022 14:40:21 [Geolocation.cpp:95] Using geolocation provided by DB-IP (https://db-ip.com)
13/May/2022 14:40:21 [HTTPserver.cpp:1673] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
13/May/2022 14:40:21 [HTTPserver.cpp:1682] HTTPS server listening on 3000

opened the browser and it works. Please do the same test and report the log

**Comment by martinscheu** [comment]
I use config file

 Sets the HTTP port of the embedded web server.
--http-port=3000
--https-port=3001

and when I start ntopng as service (systemctl start ntopng) it looks it does not read the config .
when I run from command line "ntopng /etc/ntopng/ntopng.conf" it does work and ntopng is listening on the correct port.

**Comment by martinscheu** [comment]
with latest update it is working not.
Thanks @lucaderi !

**Comment by anust** [comment]
@lucaderi , i am unable to install ntopng 5.2 release and always getting the following error

```
rc/NetworkInterface.cpp: In member function ‘void NetworkInterface::init()’:
src/NetworkInterface.cpp:338:3: error: ‘dhcp_last_sec_pkts’ was not declared in this scope
  338 |   dhcp_last_sec_pkts = 0, last_sec_epoch = 0;
      |   ^~~~~~~~~~~~~~~~~~
src/NetworkInterface.cpp:338:27: error: ‘last_sec_epoch’ was not declared in this scope
  338 |   dhcp_last_sec_pkts = 0, last_sec_epoch = 0;
      |                           ^~~~~~~~~~~~~~
make: *** [Makefile:130: src/NetworkInterface.o] Error 1
```
