### ISSUE TITLE
IEC104 Invalid Transition with threshold

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6598]
**What would you like to add or change?**:
Add a threshold for the "IEC104 Invalid Transition" alert:
| Transitions | normal operations traffic | malware |
| --- | --- | --- |
| M_ to M_ | \> 1000 | 0   |
| M_ to C_ or C_ to M_ | \> 0 && < 10 | 0   |
| C_ to C_ | 0   | \> 10 |

**Why do you and others need this?**:
reduce false positive alerts, it would be helpful to have user adjustable thresholds for M to C or C to M transitions as well as C to C . Otherwise I would set alert thresholds like following:
|   transition  |   threshold  |
| --- | --- |
| M_ to M_ | no alert   |
| M_ to C_ or C_ to M_ | \> 20   |
| C_ to C_ |  \> 5 |

**Comment by lucaderi** [comment]
![Screen Shot 2022-05-15 at 16 57 30](https://user-images.githubusercontent.com/4493366/168479397-84a21f0c-03fb-4beb-ba86-fb802fbaa163.png)

Tested with https://www.netresec.com/?page=Blog&month=2022-04&post=Industroyer2-IEC-104-Analysis
