### ISSUE TITLE
Historical Flows and Views

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6599]
In the case of a view interface, historical flows are dumped only in the view interface. This means that doing into the physical interface, historical flows are not saved and thus the table is empty.
 
![Screen Shot 2022-05-14 at 12 25 26](https://user-images.githubusercontent.com/4493366/168421857-d14dde21-c4bb-46b2-ac16-ae5bde375c03.png)

This ticket is to request for all interfaces that are part of a view, to
- (either) remove the Flows -> Historical Flows submenu
- (or, but better) to leave such menu but switch to the view interface under which such physical interface is aggregated

**Comment by MatteoBiscosi** [comment]
in the latest ntopng version, the historical flow submenu is already unavailable in a viewed interface. Other then that I added to datatable.template page the ifid, showing the view interface id instead of the viewed one.

**Comment by MatteoBiscosi** [comment]
Verified as fixed
