### ISSUE TITLE
ntopng license inside file

### ISSUE THREAD

**Issue by ValentinaViscarelli** [ntop/ntopng#66]
Adding ntopng license in /etc/ntopng.license

**Comment by ariava** [comment]
@ValentinaViscarelli could you please clarify the issue you are encountering?

**Comment by lucaderi** [comment]
@ValentinaViscarelli  In essence the license should be checked as follows
1. Check for license in /etc/ntopng.license
2. If not found search on redis for the license.

It this what you want?

**Comment by lmangani** [comment]
+1 for the dual license location option, file-system is more reliable for
this role



Lorenzo Mangani

HOMER / PCAPTURE DEV TEAM
Desk: +31 20 8080468 / +1 202-632-7227
Mobile: +31 6 4603-2730

QXIP BV - Capture Engineering
Amsterdam, The Netherlands
get@pcapture.com
