### ISSUE TITLE
Mirror Traffic and Interfaces

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6600]
![Screen Shot 2022-05-14 at 12 28 01](https://user-images.githubusercontent.com/4493366/168421936-874d8ff0-bdb7-4df0-9f8a-906b271b7835.png)

When the traffic reported is shown as above (all traffic is in RX and this is kind of impossible for most networks) this usually means that the user has not clicked under Interface in the above item. 
![Screen Shot 2022-05-14 at 12 29 33](https://user-images.githubusercontent.com/4493366/168421983-3c57155d-c8c0-49c0-ae09-c2422613b3e7.png)

In fact when such an item has been selected the traffic will flow as follows

![Screen Shot 2022-05-14 at 12 30 40](https://user-images.githubusercontent.com/4493366/168422007-1dd5cc41-3eff-49ef-8cfc-dd255f79a4ff.png)

This said this ticket is to request to detect the RX-only case and open a [alert](https://getbootstrap.com/docs/4.0/components/alerts/) (or similar) to report this misconfiguration and ask the user to enable mirroring. Note that in some rare cases the traffic os RX only even when not using a mirror, so you should give users the option to dismiss the alert without changing the setup.

@JudyyHopps Please document all this once @MatteoBiscosi has implemented it.

**Comment by MatteoBiscosi** [comment]
Added toast liker suggested. It is going to show only if the user has RX-only traffic (TX traffic is 0 and RX is greater then 0).
It's a dismissable toast (if you click dismiss, it's not going to pop-up again) and you can jump to the interface configuration by clicking the link in the toast.
Note that only Packet Interfaces have this configurable option (https://www.ntop.org/guides/ntopng/interfaces/packet_vs_zmq.html).
![Screenshot from 2022-05-16 12-32-31](https://user-images.githubusercontent.com/49585191/168574450-e4a6b0c1-cb67-4e2c-b292-15ea7ab403d9.png)

**Comment by lucaderi** [comment]
@MatteoBiscosi Is this ticket ready to test?

**Comment by MatteoBiscosi** [comment]
Documentation updated by @JudyyHopps in commit 4bfda4ceec0466e717dcbd52a65325337f0d7573

**Comment by MatteoBiscosi** [comment]
Implemented as requested.
The documentation can be found here https://www.ntop.org/guides/ntopng/web_gui/interfaces.html?highlight=mirrored at the end of the page
