### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6601]
![image](https://user-images.githubusercontent.com/4493366/168422317-150d03b7-5c2e-4d47-b467-7821fbfbf833.png)

- In this alert copying the URL I get https:///raw.php (the host is missing)
- Remove "Main Direction" that is obsolete as we now have bytes per direction

**Comment by MatteoBiscosi** [comment]
The issue now should be fixed, however this problem is going to arise again if the flow does not have a server name

**Comment by martinscheu** [comment]
Hi @MatteoBiscosi, it is working on v.5.3.220516: URL:[ 192.168.88.248:8080/WebVisuV3.bin](https://192.168.88.248:8080/WebVisuV3.bin) ] [ Server to Client Traffic: 1.06 MB | Client to Server Traffic: 187.74 KB ]

**Comment by MatteoBiscosi** [comment]
Thanks for your report @martinscheu. Please reopen the issue if needed
