### ISSUE TITLE
Attempt to perform arithmetic on a nil value in db_flow_details.lua

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#6609]
HTTP/1.1 302 Found Server: ntopng 5.3.220510 (x86_64) Set-Cookie: session=ec26e36699b46fd9b83e38a985c85de0; path=/; HttpOnly; SameSite=lax Location: /lua/http_status_code.lua?message=internal_error&referer=1.2.3.4%2Flua%2Fpro%2Fdb_flow_details.lua%3Frow_id%3D282019172%26tstamp%3D1652879070%26ifid%3D6&error_message=%2Fusr%2Fshare%2Fntopng%2Fscripts%2Flua%2Fpro%2Fdb_flow_details.lua%3A100%3A%20attempt%20to%20perform%20arithmetic%20on%20a%20nil%20value%20%28field%20%27SRC2DST_BYTES%27%29 /usr/share/ntopng/scripts/lua/pro/db_flow_details.lua:100: attempt to perform arithmetic on a nil value (field 'SRC2DST_BYTES')

**Comment by MatteoBiscosi** [comment]
Verified as fixed
