### ISSUE TITLE
Cannot Dump Traffic on mirror trunk port

### ISSUE THREAD

**Issue by thecowinheat** [ntop/ntopng#661]
Running NTOPNG on a mirror port of my firewall.  Firewall port has about 20 Vlans coming into it.  When viewing an individual host i click dump traffic and then get forwarded to a cannot find host page.  This is consistent on any device from this port.  If i push an access port to it the Vlans no longer come through but i can dump traffic.  i.e. if it shows up as 10.14.120.10@14 it does not work but 10.14.120.10 does work.

**Comment by simonemainardi** [comment]
it should be fixed now, please hold on and reinstall the package tomorrow.
