### ISSUE TITLE
Warning about mining inside ntopng

### ISSUE THREAD

**Issue by hdsjahuen** [ntop/ntopng#6613]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]

**What happened**:

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

Trying to identify mining in ntopng, I found a problem when I was looking at
Both ends of the warning activity stream are from China, with only IPs and no domains, and we also went to the client machines to check and found that no mining activity was taking place.This is unlikely in my opinion
[image1](https://github.com/hdsjahuen/hk/blob/main/156.jpg)

So is there something wrong here? And I would also like to understand the identification of your mining, what is the basis of the identification? Can you elaborate on the principle of discovery mining, the working mechanism and the discovery mechanism?

**Comment by hdsjahuen** [comment]
Can you identify which coins are mined?

**Comment by lucaderi** [comment]
yes we can identify throught DPI: see https://github.com/ntop/nDPI/blob/dev/src/lib/protocols/mining.c

Please note that you have millions of drops and thousand of flow alerts you need to analyze (see your screenshot)

**Comment by hdsjahuen** [comment]
Both ends of the warning activity stream are from China, with only IPs and no domains, and we also went to the client machines to check and found that no mining activity was taking place.
So if this is the case is it normal?

**Comment by hdsjahuen** [comment]
And I would like to ask what are the coins it can recognize? Besides Bitcoin, these

**Comment by hdsjahuen** [comment]
Hello, can you please solve my problem?

**Comment by lucaderi** [comment]
First of all please update to the current ntopng version that includes the most recent nDPI. Then if you believe you have misclassified traffic, please create a pcap file that we can use to reproduce the problem (you can test it with ntopng -i <pcap file>) and attach it to a new ticket. With the info you sent there is not much we can do.

**Comment by hdsjahuen** [comment]
How do I send you the original packet? Can you give me an email address?
