### ISSUE TITLE
ntopng licence not found message when updating

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6616]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]: ntopng Enterprise L v.5.3.220523 (Ubuntu 20.04.4 LTS)

**What happened**:
when updating over command line, the following message is displayed:
<img width="986" alt="Screenshot 2022-05-23 at 09 32 07" src="https://user-images.githubusercontent.com/38549755/169769523-a98550bb-80ba-4613-ae26-6876c753f17b.png">

but I do have valid Enterprise L license on that host.

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by cardigliano** [comment]
@martinscheu it seems this is due to a bad check in the maintenance, which has been already fixed, please go ahead with the installation

**Comment by recalmer** [comment]
I received the same message,  with the update for debian and a valid Enterprise L-lic. 
https://packages.ntop.org/apt/bullseye x64/ ntopng 5.3.220523-17696 
I have change last week the new "Enterprise L"-lic with a valid maintenance.

**Comment by recalmer** [comment]
After the update, the ntopng-service run with a valid license. It looks like it only affects the update process.

**Comment by cardigliano** [comment]
@recalmer yes it has been fixed as you noticed with the update
