### ISSUE TITLE
Historical Alert Download is Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6618]
![image](https://user-images.githubusercontent.com/4493366/169835135-b5f50a9c-a47e-4d85-a51a-ae11ad8d8176.png)

is broken as it reports

alert_id|alert_status|interface_id|tstamp|tstamp_end|severity|score|json|ip_version|cli_ip|srv_ip|cli_port|srv_port|vlan_id|is_cli_attacker|is_cli_victim|is_srv_attacker|is_srv_victim|proto|l7_proto|l7_master_proto|l7_cat|cli_name|srv_name|cli_country|srv_country|cli_blacklisted|srv_blacklisted|cli2srv_bytes|srv2cli_bytes|cli2srv_pkts|srv2cli_pkts|first_seen|community_id|alerts_map|flow_risk_bitmap|user_label
Received exception from server (version 22.2.2):
Code: 47. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Missing columns: 'l7_proto_master' while processing query: 'SELECT alert_id, alert_status, interface_id, tstamp, tstamp_end, severity, score, json, ip_version, cli_ip, srv_ip, cli_port, srv_port, vlan_id, is_cli_attacker, is_cli_victim, is_srv_attacker, is_srv_victim, proto, l7_proto, l7_master_proto, l7_cat, cli_name, srv_name, cli_country, srv_country, cli_blacklisted, srv_blacklisted, cli2srv_bytes, srv2cli_bytes, cli2srv_pkts, srv2cli_pkts, first_seen, community_id, alerts_map, flow_risk_bitmap, user_label FROM flow_alerts WHERE ((interface_id = 2) AND (severity >= 5) AND ((l7_proto = 163) OR (l7_proto_master = 163))) AND (tstamp >= 1653312106) AND (tstamp_end <= 1653313906)', required columns: 'l7_master_proto' 'first_seen' 'score' 'interface_id' 'ip_version' 'community_id' 'cli_port' 'cli2srv_pkts' 'json' 'is_srv_victim' 'alert_id' 'cli_blacklisted' 'tstamp_end' 'cli_name' 'srv_blacklisted' 'vlan_id' 'alert_status' 'cli_ip' 'srv_ip' 'tstamp' 'srv_port' 'is_srv_attacker' 'l7_proto' 'is_cli_attacker' 'severity' 'flow_risk_bitmap' 'proto' 'l7_cat' 'srv_country' 'l7_proto_master' 'alerts_map' 'cli2srv_bytes' 'srv_name' 'cli_country' 'srv2cli_bytes' 'is_cli_victim' 'srv2cli_pkts' 'user_label', maybe you meant: ['l7_master_proto','first_seen','score','interface_id','ip_version','community_id','cli_port','cli2srv_pkts','json','is_srv_victim','alert_id','cli_blacklisted','tstamp_end','cli_name','srv_blacklisted','vlan_id','alert_status','cli_ip','srv_ip','tstamp','srv_port','is_srv_attacker','l7_proto','is_cli_attacker','severity','flow_risk_bitmap','proto','l7_cat','srv_country','alerts_map','cli2srv_bytes','srv_name','cli_country','srv2cli_bytes','is_cli_victim','srv2cli_pkts','user_label']. (UNKNOWN_IDENTIFIER)
(query: SELECT alert_id,alert_status,interface_id,tstamp,tstamp_end,severity,score,json,ip_version,cli_ip,srv_ip,cli_port,srv_port,vlan_id,is_cli_attacker,is_cli_victim,is_srv_attacker,is_srv_victim,proto,l7_proto,l7_master_proto,l7_cat,cli_name,srv_name,cli_country,srv_country,cli_blacklisted,srv_blacklisted,cli2srv_bytes,srv2cli_bytes,cli2srv_pkts,srv2cli_pkts,first_seen,community_id,alerts_map,flow_risk_bitmap,user_label FROM flow_alerts WHERE ((interface_id=2) and (severity>=5) and ( (l7_proto=163 or l7_proto_master=163) )) and (tstamp >= 1653312106) and (tstamp_end <= 1653313906)     FORMAT CSV)

**Comment by MatteoBiscosi** [comment]
Fixed and tested on HSol
