### ISSUE TITLE
ntopng Web GUI password reset to default after update to v2.4

### ISSUE THREAD

**Issue by faisalusuf** [ntop/ntopng#662]
Hi,
I have upgraded my existing ntopng deployment to v2.4. After upgrade the web gui password reset to default "admin". Also observing that the web gui response time (navigating b/w different tabs) is increased after the upgrade.

Thanks
Faisal.

**Comment by simonemainardi** [comment]
this is far too generic to be considered an issue.

ntopng updates don't touch redis so no password is ever changed during an update. Make sure you didn't upgrade the system and that caused redis to be cleared.

Also saying response time increased is too generic. Did you apply other changes / updates to the system apart from ntopng? Also you should report system load, architecture, OS, ntopng configuration, # of active hosts and flows, etc.

**Comment by faisalusuf** [comment]
Ah, My bad I have verified the events on the deployment its was a system update actually which caused the password reset. 
Thanks for your expert advice.
