### ISSUE TITLE
Check Exclusions Are Useless for Specific Alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6620]
![image](https://user-images.githubusercontent.com/4493366/169973597-3b5fc44e-a079-47c3-a7e3-690976acb93d.png)

Specific alerts such as
- Suspicious DGA Domain
- Known protocol on non-standard port
- Suspicious User Agent

cannot be handled with standard exclusions but they need to be handled with nDPI exceptions. This requires the web interface to be modified by
- giving use the ability to whitelist (e.g. for DGA) a specific domain name
- use the alert subject (the domain that triggered the alert in the case of DGA) in the exception window and allow the user to modify it (e.g. to remove portions of it, in order to make the check more effective and general. Example xxxxxxx.mydomain.microsoft.com -> microsoft.com)
- instruct nDPI to reload the list of domains

**Comment by cardigliano** [comment]
- a list of supported "subjects" to be excluded should be added to the check configuration (e.g. src host, dst host, domain, certificate issuer) according to those supported by nDPI
- when clicking on the "disable" action for a specific alert, the above subjects should be provided in the dialog before applying the filter. Note that the certificate issuer should be provided only for TLS versions where this is available, and only on packet interface
- note that there is already an "Excluded Domains" configuration for selected checks (e.g. Invalid DNS Query), those should be replaced by this new implementation: cleanup Excluded Domains and Excluded Hosts from the checks configuration, and the standard alert exclusion mechanism will be used
- the "Check Exclusions" page should also list exclusions on domains and certificate issuers (in separate tabs, based on the subject type)
- all the exclusions can be stored in redis (for consistency with the other configurations, and to easy the listing, removal, etc.), but a configuration file should be generated to be provided to nDPI
- the "Manage Configurations" page should allow export and import of the exclusions
- when excluding a domain, it applies to all alert types
- available in Enterprise

**Comment by lucaderi** [comment]
In the nDPI API it is possible to exclude domain names with the call ndpi_add_host_risk_mask().

Example:
ndpi_add_host_risk_mask(ndpi_str,".xxxxxxxxxxxxx.org", 0 /* mask all */); 

You can also specify this mask in the protocols file "-p protos.txt" with the following line

host_risk_mask:".xxxxxxxxxxxxx.org"=0 

See https://www.ntop.org/ndpi/how-to-configure-flow-risk-exclusions-in-ndpi-and-ntopng/ for more information about the above configuration files.

**Comment by cardigliano** [comment]
A new method ndpi_reset_host_risk_mask is required to reset and reload the configuration when deleting rules

**Comment by lucaderi** [comment]
See #6634 for GUI design changes

**Comment by cardigliano** [comment]
The REST API has been updated to handle this, reworking/moving the old endpoints:

lua/pro/rest/v2/add/alert/exclusion.lua
lua/pro/rest/v2/get/alert/exclusions.lua
lua/pro/rest/v2/delete/alert/exclusion.lua

**Comment by martinscheu** [comment]
@uccidibuti where can I find the GUI for the domain name exclusion? thanks

**Comment by cardigliano** [comment]
Settings -> Behavioural Check Exclusions -> Domain Names

**Comment by lucaderi** [comment]
![image](https://user-images.githubusercontent.com/4493366/176114321-ac34f670-6d36-4152-90ae-337516e839a1.png)

When disabling alerts per content (e.g. domain name) even if "Delete Alerts" is flagged, nothing is deleted. If too difficult to implement, please disable the  "Delete Alerts" for non IP-based

**Comment by lucaderi** [comment]
Verified as fixed
