### ISSUE TITLE
Engaged Host Alert Filters Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6621]
![image](https://user-images.githubusercontent.com/4493366/170042104-6472f82c-496e-4c05-a3b1-06467c51d992.png)

Also note that at the bottom of the page the SQL button is missing.

**Comment by cardigliano** [comment]
Fixed in 5b0e59b50c4589fe74a4916b2c0699e55ecd2ca1

**Comment by MatteoBiscosi** [comment]
Verified as fixed
![Screenshot from 2022-05-25 12-29-07](https://user-images.githubusercontent.com/49585191/170242306-91533f72-1dcb-4f77-a169-2aeada0bfe78.png)
