### ISSUE TITLE
Invalid host naming in flows and alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6623]
![image](https://user-images.githubusercontent.com/4493366/170070058-a1ed46ae-5d72-463d-9de0-d538ca730aad.png)

There are several issues to fix in this image
- the pink squared names must be replaced with the blue squared names when available. If not available data will be as today. Note that this issue is also present when displaying historical flows in the flow record view.
- The orange fields must be omitted when with default values as in the example
- The top bar "Historical Flow: ...." should have only numerical IP addresses, whereas in the "Flow Peers" line numerical IPs will be replaced with symbolic ones if present.

**Comment by MatteoBiscosi** [comment]
Verified as Fixed
