### ISSUE TITLE
Remove Empty/Default Fields in Historical Flows/Alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6624]
![image](https://user-images.githubusercontent.com/4493366/170076564-a933f906-1b46-4889-8b4c-0fc1ce32f716.png)

In the image above the fields with empty or default values need to be removed to make everything smaller.

**Comment by MatteoBiscosi** [comment]
This is currently impossible with the datables.net version we are using (the library itself cannot do this work)
