### ISSUE TITLE
Clickhouse import shows erros 

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6625]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]: ntopng Enterprise L v.5.3.220520 (Ubuntu 20.04.4 LTS)

**What happened**:
On ntopng / System / Health / ClickHouse is showing:
24/May/2022 15:39:26 Cannot parse input: expected '\'' before: 'generateUUIDv4(), 4139, 65535, 1653406766, 1653406766, 3, 10, \'tisch\', 0, \'{"scope":"login","status":"authorized"}\'); ' [191873786,192226413,361550500,361389376,387748826,387745619,386089141,386088282,386221256,386169662,386165313,386164440,386158916,373488371,383450605,383436271,457092591,457101889,458964105,458952672,140378805593609,140378804695347]

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by bash0ra** [comment]
~~Similar Errors happen to me too.....~~

Moved to #6627

**Comment by lucaderi** [comment]
Can you please report the Clickhouse version? From ntopng system interface -> Health ClickHouse?

**Comment by lucaderi** [comment]
@bash0ra I have moved your issue to  #6627 as this is different from the one reported by @martinscheu. Please also repor on #6627 your clickhouse version

**Comment by martinscheu** [comment]
Thanks @lucaderi 
We have Clickhouse version: 22.4.5.9

**Comment by cardigliano** [comment]
@martinscheu are you still able to reproduce this?

**Comment by AnhTuanNguyenn** [comment]
i have same pb too on version ntopng [ntopng Enterprise M v.5.5.220727 (FreeBSD 12.2)]
clickhouse version 22.4.5.9
and once more too: 
```
17/Aug/2022 04:05:38 Cannot check modification time for file: /var/lib/clickhouse/store/a51/a510fd92-8871-466f-8ff3-9d42d4d8685b/tmp_insert_202208_413687_413687_0/, errno: 2, strerror: No such file or directory [191873786,191879114,192168294,362492404,379689781,377520324,377345393,191714021,191713261,192587642,192595812,192576423,192591325,140672311938979,140672311090943]
07/Jul/2022 17:41:47 Syntax error: failed at position 306 ('vlan_id'): vlan_id AND = 12)) GROUP BY severity, slot ORDER BY severity, slot ASC. Expected one of: token, DoubleColon, MOD, DIV, NOT, BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, IS, AND, OR, QuestionMark, alias, AS, Comma [191873786,391705439,373463311,373486183,383450605,383436271,457092591,457101889,458964105,458952672,140672311938979,140672311090943]
```

**Comment by lucaderi** [comment]
This problem has been fixed and we're no longer able to reproduce it

**Comment by lucaderi** [comment]
This problem has been fixed and we're no longer able to reproduce it
