### ISSUE TITLE
Protocol is not Honoured on External Links

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6626]
![image](https://user-images.githubusercontent.com/4493366/170120939-99b645a5-64b1-466f-9a46-00447304f297.png)

External links must use http or https according to the flow. In the example above clicking on the link the URL has https insteaad of http. Please fix this discrepancy.

**Comment by lucaderi** [comment]
![image](https://user-images.githubusercontent.com/4493366/170585937-373dba05-d266-428c-a61c-ca37ba12d891.png)

The same issue is still present in flows.

**Comment by MatteoBiscosi** [comment]
Verified as fixed
