### ISSUE TITLE
ClickHouse No Such Column in View Interface

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6627]
@bash0ra Reported
Similar Errors happen to me too.

Environment:

OS name: Ubuntu
OS version: 20.04
Architecture: amd64
ntopng version/revision: ntopng Enterprise M v.5.3.220523 (Ubuntu 20.04.4 LTS) |

What happened:

On ntopng / System / Health / ClickHouse is showing:

24/May/2022 20:18:10 No such column cli2srv_pkts in table ntopng.flow_alerts_view (d4130e74-8493-4c54-b878-98381d814f7b) [183233818,348368605,348366656,348373940,351177337,351167989,362738746,362820633,409369103,409378401,411149641,411139136,140670490289673,140670489391459]

What did you expect to happen?
To show no errors

How did you reproduce it?
Dropped Database completely

Debug Information:

**Comment by lucaderi** [comment]
I have done this
$ clickhouse-client 
ClickHouse client version 22.2.2.1.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.2.2 revision 54455.

dell.ntop.org :) drop database ntopng;

DROP DATABASE ntopng

Query id: 4a11c8ad-cd20-4524-81fb-ba8c117e537b

Ok.

0 rows in set. Elapsed: 0.009 sec. 

dell.ntop.org :) create database ntopng;

CREATE DATABASE ntopng

Query id: 1612855b-2224-4499-a0a3-d6fd5bf6c5c6

Ok.

0 rows in set. Elapsed: 0.003 sec. 

dell.ntop.org :) 

and then started ntopng and seen no errors. This was how you said you reproduced it, correct?

Please report the exact clickhouse-server version you are using

**Comment by bash0ra** [comment]
Clickhouse Version is 22.2.2.1

**Comment by cardigliano** [comment]
b5934b802d350745ec6e0ed0b416b24e072c41de should fix the "No such column cli2srv_pkts" failure

**Comment by lucaderi** [comment]
Works for me after the fix

**Comment by bash0ra** [comment]
This error stopped happening. Thank you.
