### ISSUE TITLE
Historical Flows broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6632]
HTTP/1.1 302 Found Server: ntopng 5.3.220526 (x86_64) Set-Cookie: session=0c1debd8833a3c04c5a31a1243b5af1e; path=/; HttpOnly; SameSite=lax Location: /lua/http_status_code.lua?message=internal_error&referer=194.242.61.8%3A3000%2Flua%2Fpro%2Fdb_flow_details.lua%3Fpage%3Dflow%26status%3Dhistorical%26row_id%3D22864155588%26tstamp%3D1653547875&error_message=...are%2Fntopng%2Fscripts%2Flua%2Fmodules%2Fhistorical_flow_utils.lua%3A1881%3A%20attempt%20to%20add%20a%20%27string%27%20with%20a%20%27string%27 ...are/ntopng/scripts/lua/modules/historical_flow_utils.lua:1881: attempt to add a 'string' with a 'string'

Can be reproduced with http://194.XXX:3000/lua/pro/db_flow_details.lua?page=flow&status=historical&row_id=22864155588&tstamp=1653547875

On Hsol

**Comment by cardigliano** [comment]
Fixed in 48aee7d88fd6a482aaba8101284629e3d471617d

**Comment by lucaderi** [comment]
Verified as fixed
