### ISSUE TITLE
Info Column is Duplicated in Historical Flow Alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6633]
![Screen Shot 2022-05-26 at 09 44 55](https://user-images.githubusercontent.com/4493366/170442492-e6f4c1e1-aa56-4721-91f6-fd7693bb99a2.png)

**Comment by MatteoBiscosi** [comment]
Bugged only by using safari
![Screenshot from 2022-05-26 09-49-51](https://user-images.githubusercontent.com/49585191/170443299-45f1e8c9-f3d7-45b7-8874-e5f1247941b8.png)

**Comment by lucaderi** [comment]
Any fix for Safari or close this ticket

**Comment by uccidibuti** [comment]
'Info' and 'Flow Related Info' aren't represent the same information so I can't delete of any of them.
![image](https://user-images.githubusercontent.com/12447209/175511356-fed97c6f-7712-4146-a3a9-dffc7f796c13.png)
