### ISSUE TITLE
Rework Checks GUI

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6634]
![image](https://user-images.githubusercontent.com/4493366/170464305-99d3748f-90d7-42fe-a778-09f08f0b51c4.png)

In the Settings -> Check Exclusions page do
- in the above box add 3 entries: Hosts (that contains the current page content), Domain Names, and TLS Certificate. These two additional entries will be implemented only in the Enterprise M and up, and hidden in the other versions.
- the new entries will contain a table similar to the one for the host containing only one column name Name (in 'Domain Names') and IssuerDN (in 'TLS Certificate Issuer')
- The new entries will have a + (add) and modify/delete button. 
- When clicking on add/modify a new dialog is open with a one (long) text field. The only check on the field include exclusion of invalid chars such as {} () * & <> 
- New backend REST APIs will be defined to handle add/remove/modify.

When adding check exclusions in alerts (left menubar alerts -> flow Alerts -> Action Disable)

![Screen Shot 2022-05-26 at 11 59 23](https://user-images.githubusercontent.com/4493366/170465586-3caba67d-f1e1-4495-8237-6a6e4ee0574a.png)

the following dialog needs to be extended adding a new field **only for selected alerts** (see below) as follows

![image](https://user-images.githubusercontent.com/4493366/170465750-7e5f4607-0817-4a7d-8565-6d15cf46b100.png)

In essence, for the following alerts a new entry is added (so third radio button only for Enterprise Editions) Domain "XXX" or TLS Certificate Issuer "XXX" .

The  Domain "XXX" must be added **only** whenever the alert contains something that can populate XXX as the Info field or "Requested Server Name". In essence whenever in the alert there is the copy button present

![image](https://user-images.githubusercontent.com/4493366/170467873-2c676d67-19af-404e-a4c4-f657cec23481.png)

The TLS Certificate "XXX" entry must be added **only** for alert type "TLS Certificate Self-Signed" whenever the value in the box is present. In the example below, the message will be TLS Certificate Issuer "C=US, O=Let's Encrypt, CN=Let's Encrypt Authority X3

![image](https://user-images.githubusercontent.com/4493366/170467136-1ebce12d-692f-495c-9c91-27d8d97557be.png)

**Comment by cardigliano** [comment]
Note: when clicking on the Disable Alert button in the Flow alerts, the dialog should have as options:
- client and server as already available now, but the client should be reported as first, and it should be explicitly marked as "Client" or "Server"
- the domain when available as described above
- the certificate when available as described above

**Comment by cardigliano** [comment]
Update:
Both the Check Exclusion page and the Disable Alert action from the alerts page have been implemented.
Alerts can be currently excluded, disabled (in case of any host) and deleted (when requested).

What needs to be fixed is the domain name provided as option when disabling alerts: it often includes the full URL, or a list of domains, a clean domain should be provided instead, otherwise nDPI cannot match the traffic correctly

**Comment by cardigliano** [comment]
To be fixed:
- domain name provided as option when disabling alerts often includes the full URL
- issuerDN is sometimes within '[' ']'
- add vlan, domain, certificate when adding filters from an active flow (see flow_details.lua:1510)

**Comment by gacpac** [comment]
is this available in the community edition ?
