### ISSUE TITLE
Fix for Alert Checks Exclusions

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6635]
1. right alignment not working
![image](https://user-images.githubusercontent.com/4493366/170475397-4daf57e4-fe30-423c-a478-e55d24c36954.png)

2. extend the field size
![image](https://user-images.githubusercontent.com/4493366/170475606-a1fcda04-3b62-4635-928c-b83d5e7f41ea.png)

**Comment by MatteoBiscosi** [comment]
Verified as Fixed
