### ISSUE TITLE
License Problem

### ISSUE THREAD

**Issue by rickguise** [ntop/ntopng#664]
Hello. 

I upgraded ntopng to version 2.4.270616 and nprobe to version 7.4.160623 but I am having troubles with the license number for ntopng.

If I enter my permanent license (E3...) in ntopng then I get the "licence expires in x minutes" on my dashboard. 

If I try to generate a new one I get the error:  "License 32.. for systemId 4042441195-7104a212 has been already generated: please go back and specify a different one."

The nprobe -v output is as follows:

C:\Program Files\nProbe>nprobe.exe /c -v Running nProbe for Windows.

Welcome to nProbe v.7.4.160623 (r4597) for Windows

Copyright 2002-16 ntop.org

Build OS:      Windows
SystemID:      4042441195-7104a212
Edition:       nProbe Standard
License:       E3... [valid license]
License Type:  Permanent License
Maintenance:   Until Fri May 12 10:39:57 2017 [310 days left]

Thank you

**Comment by lucaderi** [comment]
Rick can you please check the license? It should be 32C80.... instead of E3... Please recover it at https://shop.ntop.org/recover_licenses.html

**Comment by rickguise** [comment]
I also tried with 32C80... but I keep getting "license expires in x minutes". 

The recover license page tells me the following:
rguise@ubi.pt 
1   License and installation support (one year) of ntopng Pro (Small Business Edition) Linux/Win (x64)
1   ntopng       4042441195-7104a212         2.3.160306  2016-05-12 00:00:00     32C80...

Thank you.

**Comment by simonemainardi** [comment]
@rickguise Look for file `ntopng` under C:\Windows\Temp : this is a log file. Please share it.

**Comment by rickguise** [comment]
20/Jul/2016 09:27:04 [Ntop.cpp:1121] Setting local networks to 127.0.0.0/8
20/Jul/2016 09:27:04 [Redis.cpp:92] Successfully connected to redis 127.0.0.1:6379@0
20/Jul/2016 09:27:04 [NtopPro.cpp:120] [LICENSE] Read license from Redis [32C80...]
20/Jul/2016 09:27:04 [NtopPro.cpp:172] ERROR: [LICENSE] Invalid or missing ntopng License [License expired]
20/Jul/2016 09:27:04 [NtopPro.cpp:185] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
20/Jul/2016 09:27:04 [NtopPro.cpp:187] WARNING: [LICENSE] before returning to community mode
20/Jul/2016 09:27:04 [NtopPro.cpp:188] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
20/Jul/2016 09:27:04 [NtopPro.cpp:189] WARNING: [LICENSE] or run ntopng in community mode starting
20/Jul/2016 09:27:04 [NtopPro.cpp:190] WARNING: [LICENSE] ntopng --community
20/Jul/2016 09:27:04 [Ntop.cpp:1267] Registered interface tcp://127.0.0.1:5556 [id: 0]
20/Jul/2016 09:27:04 [Ntop.cpp:1279] Registered interface view tcp://127.0.0.1:5556 [id: 0]
20/Jul/2016 09:27:04 [HTTPserver.cpp:466] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
20/Jul/2016 09:27:04 [HTTPserver.cpp:509] Web server dirs [C:\Program Files\ntopng\httpdocs][C:\Program Files\ntopng\scripts]
20/Jul/2016 09:27:04 [HTTPserver.cpp:512] HTTP server listening on port 3000
20/Jul/2016 09:27:04 [main.cpp:295] Working directory: C:\Windows\Temp
20/Jul/2016 09:27:04 [main.cpp:297] Scripts/HTML pages directory: C:\Program Files\ntopng
20/Jul/2016 09:27:04 [Ntop.cpp:271] Welcome to ntopng x64 v.2.4.270616 - (C) 1998-2016 ntop.org
20/Jul/2016 09:27:04 [Ntop.cpp:276] Built on Windows
20/Jul/2016 09:27:04 [PeriodicActivities.cpp:53] Started periodic activities loop...
20/Jul/2016 09:27:04 [RuntimePrefs.cpp:34] Dumping alerts into syslog
20/Jul/2016 09:27:04 [NtopPro.cpp:249] [LICENSE] ntopng systemId: 4042441195-7104a212
20/Jul/2016 09:27:04 [NtopPro.cpp:254] [LICENSE] ntopng is starting in demo mode
20/Jul/2016 09:27:04 [NetworkInterface.cpp:1536] Started packet polling on interface tcp://127.0.0.1:5556 [id: 0]...
20/Jul/2016 09:27:05 [CollectorInterface.cpp:104] Collecting flows on tcp://127.0.0.1:5556 [ntopng->nprobe]

**Comment by lucaderi** [comment]
Please remove the license from redis as follows (from cmd.exe)

# redis-cli del ntopng.license

so that the license file with the correct license can be read. Then restart ntopng

**Comment by rickguise** [comment]
OK, just did that and restarted the service:

20/Jul/2016 10:48:21 [Ntop.cpp:1121] Setting local networks to 127.0.0.0/8
20/Jul/2016 10:48:21 [Redis.cpp:92] Successfully connected to redis 127.0.0.1:6379@0
20/Jul/2016 10:48:21 [NtopPro.cpp:120] [LICENSE] Read license from Redis []
20/Jul/2016 10:48:21 [NtopPro.cpp:172] ERROR: [LICENSE] Invalid or missing ntopng License [Empty license file]
20/Jul/2016 10:48:21 [NtopPro.cpp:185] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
20/Jul/2016 10:48:21 [NtopPro.cpp:187] WARNING: [LICENSE] before returning to community mode
20/Jul/2016 10:48:21 [NtopPro.cpp:188] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
20/Jul/2016 10:48:21 [NtopPro.cpp:189] WARNING: [LICENSE] or run ntopng in community mode starting
20/Jul/2016 10:48:21 [NtopPro.cpp:190] WARNING: [LICENSE] ntopng --community
20/Jul/2016 10:48:21 [Ntop.cpp:1267] Registered interface tcp://127.0.0.1:5556 [id: 0]
20/Jul/2016 10:48:21 [Ntop.cpp:1279] Registered interface view tcp://127.0.0.1:5556 [id: 0]
20/Jul/2016 10:48:21 [HTTPserver.cpp:466] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
20/Jul/2016 10:48:21 [HTTPserver.cpp:509] Web server dirs [C:\Program Files\ntopng\httpdocs][C:\Program Files\ntopng\scripts]
20/Jul/2016 10:48:21 [HTTPserver.cpp:512] HTTP server listening on port 3000
20/Jul/2016 10:48:21 [main.cpp:295] Working directory: C:\Windows\Temp
20/Jul/2016 10:48:21 [main.cpp:297] Scripts/HTML pages directory: C:\Program Files\ntopng
20/Jul/2016 10:48:21 [Ntop.cpp:271] Welcome to ntopng x64 v.2.4.270616 - (C) 1998-2016 ntop.org
20/Jul/2016 10:48:21 [Ntop.cpp:276] Built on Windows
20/Jul/2016 10:48:21 [PeriodicActivities.cpp:53] Started periodic activities loop...
20/Jul/2016 10:48:21 [RuntimePrefs.cpp:34] Dumping alerts into syslog
20/Jul/2016 10:48:21 [NtopPro.cpp:249] [LICENSE] ntopng systemId: 4042441195-7104a212
20/Jul/2016 10:48:21 [NtopPro.cpp:254] [LICENSE] ntopng is starting in demo mode
20/Jul/2016 10:48:21 [NetworkInterface.cpp:1536] Started packet polling on interface tcp://127.0.0.1:5556 [id: 0]...
20/Jul/2016 10:48:22 [CollectorInterface.cpp:104] Collecting flows on tcp://127.0.0.1:5556 [ntopng->nprobe]
20/Jul/2016 10:48:26 [Lua.cpp:2266] ERROR: Error 'fetching cdp from rra' while calling rrd_fetch_r(C:\Windows\Temp\0\rrd\bytes.rrd, AVERAGE): is the RRD corrupted perhaps?

Then I copied the license from the web page and restarted again to update the log file and I got the same error.

20/Jul/2016 10:52:05 [Ntop.cpp:1121] Setting local networks to 127.0.0.0/8
20/Jul/2016 10:52:05 [Redis.cpp:92] Successfully connected to redis 127.0.0.1:6379@0
20/Jul/2016 10:52:05 [NtopPro.cpp:120] [LICENSE] Read license from Redis [32C80...]
20/Jul/2016 10:52:05 [NtopPro.cpp:172] ERROR: [LICENSE] Invalid or missing ntopng License [License expired]
20/Jul/2016 10:52:05 [NtopPro.cpp:185] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
20/Jul/2016 10:52:05 [NtopPro.cpp:187] WARNING: [LICENSE] before returning to community mode
20/Jul/2016 10:52:05 [NtopPro.cpp:188] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
20/Jul/2016 10:52:05 [NtopPro.cpp:189] WARNING: [LICENSE] or run ntopng in community mode starting
20/Jul/2016 10:52:05 [NtopPro.cpp:190] WARNING: [LICENSE] ntopng --community
20/Jul/2016 10:52:05 [Ntop.cpp:1267] Registered interface tcp://127.0.0.1:5556 [id: 0]
20/Jul/2016 10:52:05 [Ntop.cpp:1279] Registered interface view tcp://127.0.0.1:5556 [id: 0]
20/Jul/2016 10:52:05 [HTTPserver.cpp:466] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
20/Jul/2016 10:52:05 [HTTPserver.cpp:509] Web server dirs [C:\Program Files\ntopng\httpdocs][C:\Program Files\ntopng\scripts]
20/Jul/2016 10:52:05 [HTTPserver.cpp:512] HTTP server listening on port 3000
20/Jul/2016 10:52:05 [main.cpp:295] Working directory: C:\Windows\Temp
20/Jul/2016 10:52:05 [main.cpp:297] Scripts/HTML pages directory: C:\Program Files\ntopng
20/Jul/2016 10:52:05 [Ntop.cpp:271] Welcome to ntopng x64 v.2.4.270616 - (C) 1998-2016 ntop.org
20/Jul/2016 10:52:05 [Ntop.cpp:276] Built on Windows
20/Jul/2016 10:52:05 [PeriodicActivities.cpp:53] Started periodic activities loop...
20/Jul/2016 10:52:05 [RuntimePrefs.cpp:34] Dumping alerts into syslog
20/Jul/2016 10:52:05 [NtopPro.cpp:249] [LICENSE] ntopng systemId: 4042441195-7104a212
20/Jul/2016 10:52:05 [NtopPro.cpp:254] [LICENSE] ntopng is starting in demo mode
20/Jul/2016 10:52:05 [NetworkInterface.cpp:1536] Started packet polling on interface tcp://127.0.0.1:5556 [id: 0]...
20/Jul/2016 10:52:06 [CollectorInterface.cpp:104] Collecting flows on tcp://127.0.0.1:5556 [ntopng->nprobe]

**Comment by lucaderi** [comment]
What is the exact license file name and path?

**Comment by rickguise** [comment]
[LICENSE] Read license from Redis [32C8035F368CD3DA5EDF3FA640249F51149458272247543A42]

What path are you referring to? I insert the license in ntopng about web page.

**Comment by lucaderi** [comment]
Bug found. Later today we'll provide the fix

**Comment by lucaderi** [comment]
Can you please check if http://packages.ntop.org/Windows/ntopng-2.4.160627_1-x64.zip works for you?

**Comment by rickguise** [comment]
Yes! The fix solved it. Thank you very much and keep up the good work!
