### ISSUE TITLE
ntopng not starting after command line update

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6644]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]: ntopng Enterprise L v.5.3.220520 (Ubuntu 20.04.4 LTS) |

**What happened**:
when doing apt update / upgrade, ntopng is not started automatically.
a systemctl restart ntopng is needed

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by lucaderi** [comment]
Can you please report the output of "systemctl is-enabled ntopng" ?

**Comment by martinscheu** [comment]
it is enabled. I install ntopng with a script:
```
# sichere-industrie.ch
# version 1.0, martin scheu

echo 'install ntopng on ubuntu 20.04 LTS'

 sudo apt-get install software-properties-common wget
 sudo add-apt-repository universe
 sudo wget https://packages.ntop.org/apt/20.04/all/apt-ntop.deb
 sudo apt install ./apt-ntop.deb
 sudo apt-get clean all
 sudo apt-get update
 sudo apt-get install ntopng n2disk

echo 'install completed'
echo 'enable auto start'

sudo systemctl enable ntopng
sudo systemctl start ntopng
```

**Comment by lucaderi** [comment]
Ok but how do you update it?

apt-get update
apt-get install ntopng


I assume. So before running such commands do
- systemctl is-enabled ntopng

and report.

if ntopng was started *before* starting the upgrade, *and* the service is enabled, *after* the upgrade ntopng is restarted. Please check and report.

**Comment by martinscheu** [comment]
normally like that
#!/bin/bash
sudo apt update
sudo apt upgrade -y

systemctl is-enabled ntopng
enabled

after install I never disable it manually.
running above commands manually,

with todays version ntopng keept running. I will close the ticket and report if otherwise
