### ISSUE TITLE
[nEdge] dhcp server not running on startup

### ISSUE THREAD

**Issue by tano46** [ntop/ntopng#6646]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04 LTS
* Architecture: amd64
* nedge version/revision: 5.2.220520

**What happened**:
- nedge processe starts with lan cable disconnected 
- user conncects LAN cable
- dhcp server service shold be running but it is not available until a ndege service restart

**Comment by MatteoBiscosi** [comment]
Possibly fixed with the last commit

**Comment by cardigliano** [comment]
The periodic check in nedge seems to have fixed this, @tano46 please confirm

**Comment by tano46** [comment]
Problem still there from our side

**Comment by cardigliano** [comment]
@tano46 please note the service check is implemented by using a periodic check at the moment, this takes up to 1 minute to bring up the dhcp server. Could you check if it is just a matter of waiting this 1-min delay, or the check is not working at all in your case? Thank you.

**Comment by tano46** [comment]
You are right, waiting up to 1 minute solve the issue

Problem solved for us ;-)
