### ISSUE TITLE
ntopng/clickhouse again shows Errors 

### ISSUE THREAD

**Issue by bash0ra** [ntop/ntopng#6648]
We still have Clickhous and Ntop raleted errors in the logs:

Environment:

OS name: Ubuntu
OS version: 20.04
Architecture: amd64
ntopng version/revision: [ntopng Enterprise M v.5.3.220530 (Ubuntu 20.04.4 LTS) |
Clickhouse Version: 22.2.2.1

What happened:

On ntopng / System / Health / ClickHouse is showing the two errors below.

30/May/2022 10:21:11 Cannot parse input: expected '\'' before: 'generateUUIDv4(), 4112, 2, 1653898871, 1653898871, 5, 100, \'XX:XX:XX:2E:8B:10\', 0, \'\', 0, 0, \'{"ip":"XX.YY.ZZ.AA","new_mac":"FA:B3:E1:2E:8B:10","device":"","ol' [183233818,183573389,340144228,340056096,364662522,364659363,363072981,363071898,363203747,363154302,363150811,363149080,363143748,351192723,360578306,360564527,409369103,409378401,411149641,411139136,140670490289673,140670489391459]
30/May/2022 09:13:05 Method write is not supported by storage View [183233818,332859220,365384348,348369835,348379124,351177337,351167989,362738746,362820633,409369103,409378401,411149641,411139136,140670490289673,140670489391459]
27/May/2022 09:51:38 Cannot read all data. Bytes read: 0. Bytes expected: 3. [183233818,183601876,343084766,360563454,409369103,409378401,411149641,411139136,140670490289673,140670489391459]

**Comment by cardigliano** [comment]
As of the "Method write is not supported by storage View" message, I pushed a patch set with a few fixes related to that. Let's see after the next software update if it happens again.

**Comment by lucaderi** [comment]
@bash0ra Did you try the latest version that includes the patch?

**Comment by bash0ra** [comment]
Sorry, I haven’t had the time up to now. 
But I think it should be fixed.
