### ISSUE TITLE
No graph for Network Interfaces: Realtime Traffic and Last Day View

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#665]
I am running ntopng Professional 2.4.160627_1 with a demo license. However, there is no data for the two far-right dashboard panes (Network Interfaces: Realtime Traffic and Network Interfaces: Last Day View). Can you please assist?

![screen shot 2016-07-21 at 1 28 15 pm](https://cloud.githubusercontent.com/assets/6529032/17037865/c62258d6-4f47-11e6-9a3f-84bebc7ea57f.png)

[ntopng.log.zip](https://github.com/ntop/ntopng/files/376916/ntopng.log.zip)

**Comment by simonemainardi** [comment]
hi David, let's arrange a teamviewer session, please send login credential privately.

**Comment by ghost** [comment]
There also seems to be an issue with the graphs for Mirror: Realtime Top Application Traffic and Realtime Top Application Traffic Last Day View being resized after a couple of minutes in Firefox under OS X and Ubuntu. The issue is not present in Chrome.

![screen shot 2016-07-22 at 1 58 39 pm](https://cloud.githubusercontent.com/assets/6529032/17071178/d217bdac-5014-11e6-8855-5f26c1f2b355.png)

**Comment by simonemainardi** [comment]
hi, did you see this closed issue? FF may be affected https://github.com/ntop/ntopng/issues/648

**Comment by ghost** [comment]
Yes, the issue with the graph resize in Firefox was not resolved with reload. The missing graph is missing for all browsers, including Chrome.

## 

DAVID LUU
Help Desk Specialist | 408-933-3735 | dluu@datastax.com

**Comment by simonemainardi** [comment]
we have made some fixes. you will be notified one the new windows build is ready

**Comment by simonemainardi** [comment]
this should have been fixed on windows. @david-luu can you confirm?

**Comment by ghost** [comment]
I'll check.

--MikeM

**Comment by simonemainardi** [comment]
Solution given. No feedback received. The user that posted the issue no longer exists. Closing.
