### ISSUE TITLE
Flows export failed - Elasticsearch 8.2.1

### ISSUE THREAD

**Issue by MichaelKirgus** [ntop/ntopng#6651]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04.4 LTS
* Architecture: amd64
* ntopng version/revision: 5.3.220531

**What happened**:
I recently upgraded from Elasticsearch 7.14 to Elasticsearch 8.2.1.
With ntopng version v.5.3.220529 and Elasticsearch 8.2.1 the flow export to Elasticsearch seems not working anymore:
`May 29 23:48:26 netflow01 ntopng[14453]: 29/May/2022 23:48:26 [ElasticSearch.cpp:189] ES: Buffered request with 9 flows (11024 bytes) May 29 23:48:26 netflow01 ntopng[14453]: 29/May/2022 23:48:26 [Utils.cpp:1346] [JSON] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"},"status":400} May 29 23:48:26 netflow01 ntopng[14453]: 29/May/2022 23:48:26 [Utils.cpp:1533] Posted JSON to elasticsearch06:9200/_bulk May 29 23:48:26 netflow01 ntopng[14453]: 29/May/2022 23:48:26 [Utils.cpp:1444] [NAMELOOKUP_TIME 0.01][CONNECT_TIME 0.01][APPCONNECT_TIME 0.00][PRETRANSFER_TIME 0.01][REDIRECT_TIME 0.00][STARTTRANSFER_TIME 0.01][TOTAL_TIME 0.01] May 29 23:48:26 netflow01 ntopng: [Utils.cpp:1541] WARNING: Unexpected HTTP response code received 400 May 29 23:48:26 netflow01 ntopng[14453]: 29/May/2022 23:48:26 [Utils.cpp:1541] WARNING: Unexpected HTTP response code received 400 May 29 23:48:26 netflow01 ntopng: [ElasticSearch.cpp:196] ERROR: ES: POST request for 9 flows (11024 bytes) failed`

It seems that _type is not valid anymore in 8.2.1...

**What did you expect to happen?**
The flows should be exported to Elasticsearch.

**How did you reproduce it?**
Install an ELK-Stack with version 8.2.1 and try to export flows in it.
Use the export option, in my setup "-F "es;ntopng;ntopng-%Y.%m.%d;elasticsearch06:9200/_bulk;"".

**Comment by MichaelKirgus** [comment]
For everyone who hast the same problem there is an workaround to export to Elasticsearch **if you only use Netflow** (sadly not with ntopng, but better than nothing):
Stop ntopng and nprobe and use the Filebeat Netflow-Integration to send the flows to Elasticsearch. But the template/fields are not the same, so the dashboards in Elasticsearch needs to customized and a few data is missing that ntopng provides (because ntopng is better 😄). It is customizable, you can reuse the ntopng-template and remap the fields in the Filebeat config, but its very complex and not an solution for this problem at all...i created an new template and an new index pattern for now so i have the opportunity to go back if the export works again via ntopng.
Thanks @MatteoBiscosi for analyzing and troubleshooting the issue, an solution is appreciated!

**Comment by MatteoBiscosi** [comment]
Hi @MichaelKirgus ntopng didn't support ELK version 8 but stopped at 7. With this latest patch the support to ELK 8 has been added so you can dump again flows and alerts using our elasticsearch support :)
(PS: they changed some index between version 7 and version 8).
Currently this support is only for ntopng dev version, however in a half a month more or less a new stable version is going to be released and this support will be in that version too.
![Screenshot from 2022-06-28 14-55-29](https://user-images.githubusercontent.com/49585191/176184025-38277d0d-ccd0-47a9-bc34-f6785df9d43c.png)
![Screenshot from 2022-06-28 14-56-43](https://user-images.githubusercontent.com/49585191/176184035-8fb8d436-6877-4980-92ae-f597abc18445.png)
![Screenshot from 2022-06-28 14-58-37](https://user-images.githubusercontent.com/49585191/176184423-bb22cb6c-b846-412c-afb4-9d022be41a31.png)
