### ISSUE TITLE
Process Unexpectedly Terminated after Network Discovery

### ISSUE THREAD

**Issue by Taralas** [ntop/ntopng#6652]
**Environment**:
* OS name: OPNsense Business Edition
* OS version: 22.4, Based on FreeBSD 13.0-STABLE
* Architecture: amd64
* ntopng version/revision: v.5.3.220530

**What happened**:
After completing periodic execution of network_discovery.lua, process terminated unexpectedly

```
31/May/2022 02:30:01 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/network_discovery.lua][attempt to index a string value]
```

**What did you expect to happen?**
Process to not terminate without a logged event, or unexpectedly in normal operation

**How did you reproduce it?**
Clean install of ntopng on OPNsense, start process.

**Debug Information**:
more /usr/local/etc/ntopng/ntopng.conf
-i=ax0
-i=igb1
-i=igb2
-i=igb0
-m=192.168.1.1/24,2603:6000::/64
-w=0
-W=3000
-n=1
--community
-d=/var/db/ntopng-enterprise

**Comment by Taralas** [comment]
After 2 1/2 hours of operation, process terminated unexpectedly with the following recorded to the error log:
```
31/May/2022 14:15:49 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share][attempt to index a string value]
```

**Comment by Taralas** [comment]
Still receiving this error on version v5.3.220606:
```
07/Jun/2022 18:45:49 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/network_discovery.lua][ a string valuestring value]
```

**Comment by Taralas** [comment]
Well, this one is new. Using version v.5.3.220608
```
09/Jun/2022 00:45:18 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/network_discovery.lua][192.168.1.1_oculusal_sp._tcp.local;Sardra::Oba._oculusal_sp._tcp.localattempt to index value]
```

**Comment by cardigliano** [comment]
@Taralas are you still able to reproduce this with the latest version?

**Comment by cardigliano** [comment]
This seems related to https://github.com/ntop/ntopng/issues/6578 (closing as duplicate)
