### ISSUE TITLE
ERSPAN to ntopng shows no traffic after

### ISSUE THREAD

**Issue by hdsjahuen** [ntop/ntopng#6653]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]

**What happened**:

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

This is my version of ERSPAN
[image1](https://github.com/hdsjahuen/hk/blob/main/3.png)

This is my configuration for ntopng
[image2](https://github.com/hdsjahuen/hk/blob/main/2.png)

On which interface can I use tcpdump to catch the packets, but I can't open ntopng to show that there is traffic
[image3](https://github.com/hdsjahuen/hk/blob/main/1.png)

I would like to know if all versions of ntopng support ERSPAN.
Or maybe there is something wrong with my configuration

**Comment by lucaderi** [comment]
We support ESSPAN Type 2, you have type 1. Please attach a pcap file

**Comment by lucaderi** [comment]
Closed for inactivity. Will reopen when you will provide a pcap
