### ISSUE TITLE
error while loading shared libraries: libcap.so.2

### ISSUE THREAD

**Issue by md1440** [ntop/ntopng#6654]
Hi,

I've been trying to run ntopng on my Pi 4 but keep running into `ntopng: error while loading shared libraries: libcap.so.2: cannot open shared object file: No such file or directory`. I am not sure what to make of it, as far as I can tell the libcap2 package is installed and updated and everything should run.

I am running the latest version of ntopng using Raspberry Pi OS Lite 64-bitKernel version: 5.15

I have followed the installation guidelines from ntopng docs, nothing special here. 

Any help appreciated.

Best

Marc

**Comment by lucaderi** [comment]
please report
- lsb_release -a
- the ntopng package version you have installed

**Comment by md1440** [comment]
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

apt-ntop_1.0.190416-469_all.deb as per https://packages.ntop.org/

**Comment by Aetherus** [comment]
The error persists.

Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy

firejail version: 0.9.74-1~0ubuntu22.04.0
