### ISSUE TITLE
Fritzbox Login not working

### ISSUE THREAD

**Issue by stevechilds** [ntop/ntopng#6658]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04
* Architecture: amd64
* ntopng version/revision: v.3.8.190813	[Community build]
* Fritzbox 7530, version 07.29 (13/11/2021)

**What happened**:
Login to fritzbox using the fritzdump script fails with the "Login Failed" message, even though user (dslf-config) and password is correct (password copy & pasted from Chrome when logging into the box)

**What did you expect to happen?**
Login to work :)

**How did you reproduce it?**
Run the script.

**Debug Information**:
If you need any extra info, please let me know. I did check the extraction of the challenge & the generated hash, both appear to work, I don't know if a new version of the Fritzbox software has changed the hashing algorithm?

TIA

Steve.

**Comment by stevechilds** [comment]
Ah, fixed it myself! You don't use the dslf-config username, you use the default user as setup in the FritzBox - e.g. the user fritz6253. You can tell which one it is in the Fritz Box UI.

Sorry, I could have sworn I tried that before posting, I must have mistyped the username - it's worth updating the docs though.

**Comment by stevechilds** [comment]
Right after fixing that, now when I try and use it (I had to disable the service as it was automatically enabled when I installed it via apt), I run the script, it sets up the ntopng instance, but when I try to connect, I get a "page "/" was not found" error?

The fritzdump output is as below..

> sudo fritzdump.sh fritz1111 redacted
> Trying to login into http://fritz.box as user fritz1111
> Capturing traffic on Fritz!Box interface 2-0 ...
> 05/Jun/2022 12:05:53 [Ntop.cpp:1902] Setting local networks to 127.0.0.0/8
> 05/Jun/2022 12:05:53 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
> 05/Jun/2022 12:05:53 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
> 05/Jun/2022 12:05:54 [Ntop.cpp:1996] Registered interface stdin [id: 4]
> 05/Jun/2022 12:05:54 [main.cpp:308] PID stored in file /var/run/ntopng.pid
> 05/Jun/2022 12:05:54 [HTTPserver.cpp:1029] HTTPS Disabled: missing SSL certificate /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem
> 05/Jun/2022 12:05:54 [HTTPserver.cpp:1031] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
> 05/Jun/2022 12:05:54 [Utils.cpp:592] User changed to ntopng
> 05/Jun/2022 12:05:54 [HTTPserver.cpp:1198] Web server dirs [/usr/share/ntopng/httpdocs][/home/steve/scripts]
> 05/Jun/2022 12:05:54 [HTTPserver.cpp:1201] HTTP server listening on 3000
> 05/Jun/2022 12:05:54 [main.cpp:390] Working directory: /var/lib/ntopng
> 05/Jun/2022 12:05:54 [main.cpp:392] Scripts/HTML pages directory: /usr/share/ntopng
> 05/Jun/2022 12:05:54 [Ntop.cpp:403] Welcome to ntopng x86_64 v.3.8.190813 - (C) 1998-18 ntop.org
> 05/Jun/2022 12:05:54 [PeriodicActivities.cpp:72] Started periodic activities loop...
> 05/Jun/2022 12:05:54 [PeriodicActivities.cpp:113] Each periodic activity script will use 2 threads
> 05/Jun/2022 12:05:54 [NetworkInterface.cpp:2577] Started packet polling on interface stdin [id: 4]...

When I open up http://127.0.0.1:3000 it redirects to http://127.0.0.1:3000/lua/login.lua, but I get the error below..
![image](https://user-images.githubusercontent.com/22450968/172047737-cea0176e-7f19-4501-9bf5-f7989b843214.png)

Note, it works fine when run via the service, but not when run via the fritzdump script.

**Comment by stevechilds** [comment]
Ah, fixed it again! - Never mind, hopefully this thread may help someone else :)

You need to edit the fritzscript and manually set the httpd docs & script folders

change

`
wget --no-check-certificate -qO- $FRITZIP/cgi-bin/capture_notimeout?ifaceorminor=$IFACE\&snaplen=\&capture=Start\&sid=$SID | ntopng -i -
`

to 
`
wget --no-check-certificate -qO- $FRITZIP/cgi-bin/capture_notimeout?ifaceorminor=$IFACE\&snaplen=\&capture=Start\&sid=$SID | ntopng -1 /usr/share/ntopng/httpdocs/ -2 /usr/share/ntopng/scripts/ -i -
`

This is where they were located for me, but for some reason I think it was using the folder the fritzdump script was in.

Oh, and for the output to make any sense at all, you'll want do edit the script and comment out the IFACE="2-0" line and uncomment the IFACE="1-lan" line. btw, the 2-0 line actually corresponded to the Routing interface on my box, 2-1 was the Internet, along with 3-17. If none of these match yours, simply go to the capture page in your browser (http://fritz.box/html/capture.html) and (in chrome at least) press F12 to get the console up, switch to the networking tab & click one of the start buttons. It'll log the request to capture and this url will contain the info you need.

**Comment by lucaderi** [comment]
Please send a pull request with the final script so we can incorporate it in our tools
