### ISSUE TITLE
Is it OK if OS is 14.04.1 LTS instead Linux Server x64 for running ntopng

### ISSUE THREAD

**Issue by tianzhishuizhu** [ntop/ntopng#666]
I have read the file README.md:

> We build binary packages for the following platforms:
> - Ubuntu Linux Server x64             /\* here */
> - CentOS/RedHat Linux x64
> - Windows x64
> - BeagleBoard ARM (based on Ubuntu Linux)
> - Ubiquity Networks EdgeRouter (MIPS)

My computer OS is Ubuntu 14.04.1 LTS instead of Ubuntu Linux Server x64. Is it OK?

**Comment by simonemainardi** [comment]
we do support 14.04 64bit. Here are the packages for that distribution: http://packages.ntop.org/ubuntu/14.04/x64/

**Comment by tianzhishuizhu** [comment]
@simonemainardi  I download ntopng_2.5.160725-1456_amd64.deb on the web you give. But it shows `Dependency is not satisfiable : pfring(=6.5.0-741` when installing in Ubuntu Software Center. How can solve this problem?

**Comment by lucaderi** [comment]
@tianzhishuizhu You need to install packages with apt as explained in apt.ntop.org and not with dpkg

**Comment by simonemainardi** [comment]
@tianzhishuizhu follow the instructions at http://packages.ntop.org/apt/

**Comment by tianzhishuizhu** [comment]
@lucaderi In direcotry /ntopng/doc/README.compilation, I find:

> On Ubuntu/Debian
> - apt-get install build-essential git libglib2.0 libxml2-dev libpcap-dev libtool libtool-bin rrdtool librrd-dev autoconf automake autogen redis-server wget libsqlite3-dev libhiredis    -dev libgeoip-dev libcurl4-openssl-dev libpango1.0-dev libcairo2-dev libpng12-dev libmysqlclient-dev libnetfilter-queue-dev libmysqlclient-dev zlib1g-dev

When I run command above, shell outputs:

> Package libtool-bin is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> However the following packages replace it:
>   libtool:i386 libtool
> 
> E: Package 'libtool-bin' has no installation candidate

Can you tell me how to fix this? I have run `sudo apt-get update`.

**Comment by lucaderi** [comment]
https://github.com/ntop/ntopng/commit/30ba6ab43ea94c7728861e04444e02aff2aa6686

**Comment by tianzhishuizhu** [comment]
@lucaderi I install ntopng successfully. But find

> A new ntopng (v.2.4.0) is available for download: please upgrade.
> 
> Generated by ntopng Community v.2.3.160727
> for user admin and interface eth0

Does this mean code on github is not the latest. Thanks for your work and time!

**Comment by simonemainardi** [comment]
you are using version 2.3.. did you run an apt-get update before installing? the latest version is 2.5...

**Comment by tianzhishuizhu** [comment]
@simonemainardi  I install it by downloading the source code of ntopng on github. As /ntopng/doc/README.compilation:

>  Once you have installed all the prerequisites do
> 
>  cd <compilation directory>
>  git clone https://github.com/ntop/nDPI.git
>  cd nDPI; ./autogen.sh; ./configure; make; cd ..
>  git clone https://github.com/ntop/ntopng.git
>  cd ntopng
>  ./autogen.sh
>  ./configure
>  make

Because I install ntopng from source code, I think the version may be latest if the code is newest.But it shows version is **v.2.3.160727**. How can I solve this? Thanks.

**Comment by simonemainardi** [comment]
major and minor releases look correct in the main branch: https://github.com/ntop/ntopng/blob/dev/autogen.sh#L5

so I am not sure you have actually checked out the `dev` branch of ntopng

**Comment by tianzhishuizhu** [comment]
@simonemainardi  I just use command `git clone git@github...` to download the code of ntopng and nDPI, and then install ntopng according to the `/ntopng/doc/README.compilation`. It says: 

> cd <compilation directory>
> git clone https://github.com/ntop/nDPI.git
> cd nDPI; ./autogen.sh; ./configure; make; cd ..
> git clone https://github.com/ntop/ntopng.git
> cd ntopng
> ./autogen.sh
> ./configure
> make

Can I install latest ntopng by this way?

**Comment by simonemainardi** [comment]
yes you can build and install from sources. However, I guess you have also a packaged binary 2.3 version installed on your system and this may be the source of conflict. Check with apt to see if there is an ntopng already installed

**Comment by lucaderi** [comment]
@tianzhishuizhu Use https://github.com/ntop/ntopng/blob/dev/.travis.yml as reference that shows how to build ntopng (even though you are following the right steps)

**Comment by tianzhishuizhu** [comment]
@lucaderi  I tried the method you give. That is:

> install: 
> - sudo apt-get update || true
> - sudo apt-get install build-essential
> - sudo apt-get install subversion libglib2.0 libxml2-dev libpcap-dev libtool rrdtool librrd-dev autoconf automake autogen redis-server wget libsqlite3-dev libhiredis-dev libgeoip-dev libcurl4-openssl-dev libpango1.0-dev libcairo2-dev libpng12-dev git.  
> 
> Then the process of compiling and making.

But the ntopng version is still v.2.3., not changed. Then I download source code from [Download ntopng-2.4-stable.tar.gz (134.1 MB)](https://sourceforge.net/projects/ntop/files/ntopng/). Then version is changed to v.2.4.

I want to install v.2.5 from source code. How can this be done? I have installed v.2.3 and v.2.4 on my ubuntu. Do they affect each other? Is it OK? 

With v.2.4, I find /nDPI/src/lib/protocols/qq.c. That is: ntopng can discover qq traffic. But I open `web qq` , there are no flows about `web qq`. Thank you!

**Comment by lucaderi** [comment]
Please avoid mixing request onto a single github issue. I suggest to install binary packages from http://packages.ntop.org so you avoid compilation headaches. Make sure to deinstall all ntopng binaries prior to install a new one. If you have issues with qq, please file on issues on nDPI and provide a pcap for reproducing it.
