### ISSUE TITLE
Clickhouse's directory causes disk space to be full and prevents ntopng from starting

### ISSUE THREAD

**Issue by hdsjahuen** [ntop/ntopng#6660]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]

**What happened**:

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

Today I found ntopng exception, after checking the disk space is full, it is caused by the directory of clickhouse, how to clean up the historical data?Now ntopng won't start
[image](https://github.com/hdsjahuen/hk/blob/main/a1323598-4922-4112-8a59-6eb54dc86130.png)

But after I did the directory deletion myself, I can open ntopng, but it still shows an [error](https://github.com/hdsjahuen/hk/blob/main/8b07ba72-b58f-41a4-a25b-11aa4037f3bb.png) on the status
But before, after normal ntopng start, status is no problem, please ask what can be done to solve it

**Comment by lucaderi** [comment]
Fixed in the most recent version

**Comment by hdsjahuen** [comment]
But I can't update using yum update
This is my current [version](https://github.com/hdsjahuen/hk/blob/main/2.png)
And what is the reason for this[ logo](https://github.com/hdsjahuen/hk/blob/main/1.png) displayed on my interface
And I went to the web ui interface to update there is no [way](https://github.com/hdsjahuen/hk/blob/main/3.png)
I know, the current version should have 5.3, but why I can not update it
We've had 2 people have problems updating, and both yum update didn't work and the web interface didn't work either

**Comment by hdsjahuen** [comment]
hello,I'd like to ask why it can't be updated, there are already two such issues that can't be updated
