### ISSUE TITLE
Implementing Directions In Historical Flows

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6665]
As specified in #6664, Historical Flows filters must be simplified/extended/reworked with traffic directions

**Comment by MatteoBiscosi** [comment]
Implemented as requested
![Screenshot from 2022-06-08 13-46-47](https://user-images.githubusercontent.com/49585191/172608789-db058765-91b0-4480-a3f9-d412a1096d32.png)

**Comment by MatteoBiscosi** [comment]
Verified as implemented
