### ISSUE TITLE
Host detail problem

### ISSUE THREAD

**Issue by battalo** [ntop/ntopng#667]
Hello,
Every host detail gives this problem. And all of my local host has a red warning icon on the hosts screen.
![host](https://cloud.githubusercontent.com/assets/16060297/17056277/13e0ab30-501b-11e6-9612-f12ee0c44167.JPG)
![version](https://cloud.githubusercontent.com/assets/16060297/17056278/16484a7c-501b-11e6-8e5f-d3e184584235.JPG)

**Comment by simonemainardi** [comment]
hi, we've made a fix. Please hold on, new packages are being rebuilt and will be available tomorrow.
