### ISSUE TITLE
Unable to see all sub-interfaces under (All network interface under realtime / yesterday) in traffic dashboard

### ISSUE THREAD

**Issue by 612wong** [ntop/ntopng#6671]
**Environment**:
* OS name: RHEL
* OS version: 7.9
* Architecture: x86_64
* ntopng version/revision: 5.3.220310

**What happened**:
My license is Enterprise M which supports up to 16 interfaces.
In my monitoring list, I have: 1x physical interface, 2x Netflow interfaces, 2x sFlow interfaces and 11x sub-interface disaggregated by custom filter.

In traffic dashboard, there are two graphs for 'all network interface', one for realtime and one for yesterday. I can only see up to 8 interfaces.

**What did you expect to happen?**

I expect to see all 16 network interfaces as my license is able to support maximum 16 interfaces.

**How did you reproduce it?**

**Debug Information**:

**Comment by lucaderi** [comment]
Implemented in d263d533
