### ISSUE TITLE
Fix Historical Alert Layout

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6675]
![image](https://user-images.githubusercontent.com/4493366/172782397-c85159e8-d60e-4a93-adcf-3725fcaa463e.png)

The following issues must be addressed
1. Replace the label "Main Issue" (that is a duplicate of the column "Alert") with "Information"
2. In the Main issue field remove the score and description (pink)
3. The URL is ok (green) but it must be shorter

**Comment by MatteoBiscosi** [comment]
Please update the dist too

**Comment by MatteoBiscosi** [comment]
Verified as fixed
