### ISSUE TITLE
Unify Date Format in Historical Records

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6676]
This is the date/hour format in Alerts
![Screen Shot 2022-06-09 at 08 53 23](https://user-images.githubusercontent.com/4493366/172783652-f329af77-5765-445f-bd3b-f0ccfcd9e30e.png)

that hides the date if the displayed record is for the current day.

This is what happens in historical flows

![image](https://user-images.githubusercontent.com/4493366/172783795-c36dfb3e-3df6-42dd-aba0-ffc2ebffce14.png)

where 
- the date format is not produced by the same function (duplicate code that is bad per se)
- the data is displayed and not just the time (we're on the same day) thus using more space than needed

This ticket is to request the code unification and display as in alerts

**Comment by MatteoBiscosi** [comment]
Verified as Fixed
