### ISSUE TITLE
TCP Connection Inconsistencies

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6678]
![Screen Shot 2022-06-09 at 10 06 38](https://user-images.githubusercontent.com/4493366/172797442-792154b0-6390-4d5a-a8af-0157158a423d.png)
![Screen Shot 2022-06-09 at 10 06 13](https://user-images.githubusercontent.com/4493366/172797445-b6412136-d50e-4881-b185-0f0b51f7510a.png)
![Screen Shot 2022-06-09 at 09 59 01](https://user-images.githubusercontent.com/4493366/172797457-bd79ef29-ed7e-456f-9925-7d4e7bd8bd98.png)

**Comment by MatteoBiscosi** [comment]
Verified as fixed
