### ISSUE TITLE
Implement Network Traffic Matrix

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6679]
Currently, we keep timeseries per known networks (-m), but no traffic matrix. This is to request the implementation of the traffic matrix (network-to-network) for all known networks

**Comment by MatteoBiscosi** [comment]
Implemented as requested.
A new preference is going to be available into ntopng preferences and if enabled a new set of timeseries is going to be available.
![Screenshot from 2022-06-30 10-52-02](https://user-images.githubusercontent.com/49585191/176636441-b58a60aa-85c0-4c8b-a306-bf66cdbcfa15.png)
![Screenshot from 2022-06-30 10-48-03](https://user-images.githubusercontent.com/49585191/176636553-faac02f5-880d-41c5-ac4c-165c9cc49f5f.png)
