### ISSUE TITLE
Host Pools Members - import csv file

### ISSUE THREAD

**Issue by lvalero** [ntop/ntopng#6680]
Hello,

In the documentation : 
https://www.ntop.org/guides/ntopng/web_gui/pools.html

what is the format of the csv file to provide ?

Regards

**Comment by MatteoBiscosi** [comment]
You can Import/export host pools from the configuration page
![image](https://github.com/ntop/ntopng/assets/49585191/2c3f331a-73ab-412d-9fb7-3814c24ca1f3)
