### ISSUE TITLE
Initial alerts not shown in alert page

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6681]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223] ntopng Enterprise L v.5.3.220610 (Ubuntu 20.04.4 LTS)

**What happened**:
When oppening the Alerts page, no alert is shown:

<img width="1426" alt="Screenshot 2022-06-10 at 09 17 09" src="https://user-images.githubusercontent.com/38549755/173011551-b939ca2c-1d96-4108-82f7-66eba6ad04d6.png">

after a filter is selected, alerts are shown

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu could you please tell me if some error is reported in `systemctl status ntopng`?

**Comment by martinscheu** [comment]
Hi @MatteoBiscosi there is nothing in status. Also when I check system in the ntopng GUI, all looks good

**Comment by cardigliano** [comment]
@martinscheu could you check if you have js failures in your browser console?

**Comment by martinscheu** [comment]
yes there is one error:
Uncaught (in promise) 
Object { readyState: 0, getResponseHeader: getResponseHeader(t), getAllResponseHeaders: getAllResponseHeaders(), setRequestHeader: setRequestHeader(t, e), overrideMimeType: overrideMimeType(t), statusCode: statusCode(t), abort: abort(t), state: state(), always: always(), catch: catch(t)
, … }

​

**Comment by martinscheu** [comment]
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. [alert_stats.lua](https://localhost:8443/lua/alert_stats.lua?ifid=5&score=)
Source map error: Error: request failed with status 404
Resource URL: https://localhost:8443/dist/white-mode.css?1654863500
Source Map URL: white-mode.css.map

Source map error: Error: request failed with status 404
Resource URL: https://localhost:8443/dist/third-party.css?1654863500
Source Map URL: third-party.css.map

**Comment by uccidibuti** [comment]
Hi @martinscheu , could you try with the latest version of ntopng and tell me if this problem is still present?

**Comment by martinscheu** [comment]
it does work now, thank you @uccidibuti !
