### ISSUE TITLE
IEC104 invalid command transition is alerting even when check is disabled

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6682]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223] ntopng Enterprise L v.5.3.220610 (Ubuntu 20.04.4 LTS) |

**What happened**:
see 0 transitions:
<img width="1842" alt="Screenshot 2022-06-10 at 09 21 59" src="https://user-images.githubusercontent.com/38549755/173012419-e31eb00b-fc80-46f7-8929-ef1db638ee84.png">

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by martinscheu** [comment]
10/Jun/2022 07:20:14 [LuaEngine.cpp:1254] WARNING Script failure [/usr/share/ntopng/scripts/lua/rest/v2/get/flow/alert/list.lua][.../alert_definitions/flow/alert_iec_invalid_transition.lua:46: attempt to concatenate a nil value]

**Comment by martinscheu** [comment]
@cardigliano problem still exists.
Also description of the Check is 
`flow_checks.iec104_command)description `

**Comment by martinscheu** [comment]
Hi @MatteoBiscosi
Unfortunately the alert is still getting triggered, even the Check is disabled.
Also the description is kind of faulty:
![image](https://user-images.githubusercontent.com/38549755/179535532-0b932d88-9b59-4fc3-9df4-e901f0fb42c0.png)

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu, the description is fixed and now the alert should be triggered only when the alert is enabled. Please disable and re-enable / disable the IEC alerts you are interested in, in order for the latest patch to be effective. A new build is going to be available in a couple of hours

**Comment by martinscheu** [comment]
yes, it is ok now, when disabled it does not issue alerts anymore.
if you please could update the Check description to:
Trigger an alert when a high rate of command to command IEC transitions are detected 
And then close the ticket :)
Thanks @MatteoBiscosi !

**Comment by MatteoBiscosi** [comment]
Thanks @martinscheu , the description is updated like you suggested and will be available in the next update
