### ISSUE TITLE
Traffic direction filter

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6689]
**What would you like to add or change?**:
It would be helpful to have filters for "local", "local-to-remote" or "remote-to-local" flow direction for Alerts, Historical Flows and Service Map.
Thank you.

**Why do you and others need this?**:

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu they available in the latest ntopng version for alerts and historical, please check issues #6666 and #6665. Regarding Service map, consider that in the service map you only have local traffic. Instead for the Periodicity map please follow issue #6668
