### ISSUE TITLE
Can't input telegram group ID inside the textbox

### ISSUE THREAD

**Issue by joonasak** [ntop/ntopng#6692]
**Environment**:
* OS name: OS name: Ubuntu
* OS version: 20.04 LTS
* Architecture: amd64
* ntopng version/revision: 5.2.220520

**What happened**:
I can't input telegram group ID with minus (-) inside the box.

![image](https://user-images.githubusercontent.com/85352105/173320063-95690e72-d712-426d-bf4b-6298f31fa5b0.png)

**Comment by MatteoBiscosi** [comment]
Hi @joonasak the issue should be fixed, please update in a couple of hours and let me know

**Comment by joonasak** [comment]
Hi @MatteoBiscosi , I will test it, anything will let you know. Thank you.

**Comment by joonasak** [comment]
Hi @MatteoBiscosi , It's working now. Thank you so much.

**Comment by MatteoBiscosi** [comment]
Verified as fixed.
@joonasak you are welcome :)
