### ISSUE TITLE
Implement Kibana Dashboard

### ISSUE THREAD

**Issue by MatteoBiscosi** [ntop/ntopng#6694]
In ntopng we can export both, flows and alerts information to Elasticsearch (Using -F option and endpoint/recipient in ntopng).
It is requested to create a dashboard displaying some information ntopng is able to display, mainly the alerts information.
First of all create a dashboard talking about the interface information:
- the status of the interface (a chart of the traffic)
- how many alerts you have in the interface
- which are the most frequent ones
- which are the top alerted hosts
- which are the top alerted protocols
- the total current score of the interface (using a chart if possible)
- which are the top alerted countries
- which are the top alerted categories
- Add some information from the historical flows (like number of flows, top used server/client ports, ecc.)

Then create a specific dashboard per host, displaying the information related to that specific host (to be updated).

**Comment by DGabri** [comment]
Task Completed, ready for testing
