### ISSUE TITLE
Invalid link with copy when multiple names in TLS are reported

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6696]
![Screen Shot 2022-06-13 at 16 44 33](https://user-images.githubusercontent.com/4493366/173380267-7b2f4222-a491-4dbc-8447-68cb6bce2b8e.png)

**Comment by MatteoBiscosi** [comment]
Currently working correctly. Please not that the url starting with `*.` must not have an external link. Please reopen if needed
![Screenshot from 2022-06-14 16-25-27](https://user-images.githubusercontent.com/49585191/173603150-ef6da646-efc1-41c8-8a8f-e87b9b313d60.png)
