### ISSUE TITLE
PIM is classified as unknown category but it should be of 'network' by default.

### ISSUE THREAD

**Issue by 612wong** [ntop/ntopng#6697]
**Environment**:
* OS name: RHEL
* OS version: 7.9
* Architecture: x86_64
* ntopng version/revision: ntopng Enterprise M v.5.3.220612 (CentOS Linux release 7.9.2009 (Core))

**What happened**:
PIM flow is found in 'unknown' category.

**What did you expect to happen?**
PIM is expected to be in 'network' category.

**How did you reproduce it?**
Anytime. I tried to create an application with ip:224.0.0.13 (PIM advertisement) and put it under 'network' category but it doesn't work for me after ntopng is restarted.

**Debug Information**:

**Comment by lucaderi** [comment]
Please open this ticket under nDPI and attach a pcap file for reproducing the issue

**Comment by 612wong** [comment]
Will open a ticket under nDPI with the pcap file.
