### ISSUE TITLE
Unable to edit category name of 'user custom category x'

### ISSUE THREAD

**Issue by 612wong** [ntop/ntopng#6698]
**Environment**:
* OS name: RHEL
* OS version: 7.9
* Architecture: x86_86
* ntopng version/revision: ntopng Enterprise M v.5.3.220612 (CentOS Linux release 7.9.2009 (Core))

**What happened**:
I grouped 10 custom applications under 'user custom category 1'. I clicked 'edit' button and change the 'category name' and then click 'edit' to save the changes. The screen was halt there. I refreshed the page and no changes was made to the category name.

**What did you expect to happen?**
I expected the category name can be edited.

**How did you reproduce it?**
Click 'edit' of 'user custom category x', change the category name and then click 'edit' to save the changes.

**Debug Information**:

**Comment by 612wong** [comment]
Have upgraded ntopng to v.5.3.220615 (CentOS Linux release 7.9.2009 (Core)) and still observed the same issue.

When I 'edit' the custom category and add a rule, then click 'edit'. The screen was stuck there although I tried to click 'x' to close it.

<img width="385" alt="Screen Shot 2022-06-15 at 22 06 14" src="https://user-images.githubusercontent.com/58540705/173823461-ef117f42-4549-44b9-978b-b20ba4530d3b.png">

**Comment by uccidibuti** [comment]
We are checking on our side.

**Comment by uccidibuti** [comment]
Please check the next update later today

**Comment by lucaderi** [comment]
Verified as fixed
