### ISSUE TITLE
Unresponsive script

### ISSUE THREAD

**Issue by IT-W** [ntop/ntopng#67]
We use our NTOP installation as part of our NOC. While running the main page (Top Talkers with actual traffic and the graphs corresponding those) we get this message after a few hours: 
![image](https://cloud.githubusercontent.com/assets/13116221/8428068/335dbd08-1f1c-11e5-90cf-f6206cdea11a.png)
We use Firefox version 37.0.2. Also, if we run this page in IE, after a while the screen freezes without any error.

Anyone else that had this issue?

**Comment by lucaderi** [comment]
@IT-W What version of ntopng are you using?

**Comment by IT-W** [comment]
2.0.150531 - Professional Edition

**Comment by lucaderi** [comment]
Please try the latest dev- build that works for me

**Comment by lucaderi** [comment]
No answer. I close it for the time being and perhaps re-open it if you are able to reproduce it
