### ISSUE TITLE
CORS Issue with REST API calls

### ISSUE THREAD

**Issue by aaminahassan** [ntop/ntopng#6700]
**Environment**:
* OS name: [Ubuntu]
* OS version: 20
* Agent: CHROME
* ntopng version/revision: [e.g. 5.3]

**I am trying to access rest api via react app, curl rest works fine, but rest api call gave CORS error, **: Please tell the way out to allow CROSS origins in ntopng.

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @aaminahassan could you please tell me which errors do you have? Probably it's because you miss the authentication parameters (username and password)

**Comment by MatteoBiscosi** [comment]
Hi @aaminahassan, please try following these instructions https://www.ntop.org/guides/ntopng/advanced_features/authentication.html?highlight=token 
Your problem is most likely due to the auth.

**Comment by aaminahassan** [comment]
No, when I remove security from web browser, the API works, Please tell me the ntopng side changings for CORS allowed. 

`curl -u admin:admin"http://192.168.0.1:3000/lua/get_oses_data.lua?currentPage=1&perPage=10&sortColumn=column_&sortOrder=desc" `

the above curl works from remote host, but the same converted to in react app shows cors.

**Comment by lucaderi** [comment]
@aaminahassan Can you please troubleshoot the issue (e.g. using curl -v) and report what you would like us to change?

**Comment by lucaderi** [comment]
We decided to implement this issue only for REST APIs and not for GUI requests as you are doing
