### ISSUE TITLE
ntopng "You're not supposed to be here" pfSense package install

### ISSUE THREAD

**Issue by ltkojak** [ntop/ntopng#6701]
**Environment**:
* OS name: [e.g. Ubuntu] pfSense
* OS version: [e.g. 18.04] pfSense 22.01
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223] ntopng Community v.4.0.0 rev.0 (FreeBSD 12.3)

**What happened**:

Since I've upgraded to 22.01 of pfSense Plus, all of my active monitoring section has now turned to: "You're not supposed to be here!".  I've done some searching and have found that many others have had this same issue.  Also, I've noticed that it clears out all of my endpoints that I had set up prior.
![ActiveMonitoringScreen](https://user-images.githubusercontent.com/76446244/173604994-14ac5acc-50ff-4878-93e4-829c671f8912.png)
![ntopng-endpoints](https://user-images.githubusercontent.com/76446244/173604997-abbdbef4-19b2-4b2c-8a4c-823be3340a03.png)

**What did you expect to happen?**

To see Active Monitoring

**How did you reproduce it?**

I have attempted to reinstall package, uninstall/reinstall package, delete all data uninstall/reinstall package.  Upon the deletion of data and reinstallation everything did work, however within 24 hours this began again.

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @ltkojak consider that ntopng current version is 5.3.
Probably you installed the one shipped from FreeBSD itself (many times people have problems with it and we cannot help them), please install ours for the full support.
Follow these instructions https://www.ntop.org/guides/ntopng/third_party_integrations/pfsense.html#pfsenseintegration
and you should be able to install it without problems.
Please reopen if the ticket if after installing our ntopng version you still have problems.
![Screenshot from 2022-06-14 16-59-10](https://user-images.githubusercontent.com/49585191/173610197-f8011759-0861-4666-a73e-c5cb08d72c18.png)
