### ISSUE TITLE
Fix traffic directions in the top chart with disaggregation

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#6704]
When disaggregating traffic from ZMQ based on probe IP, only one direction of the traffic is reported in the chart in the top menu. 
This also applies when disaggregating live traffic (packets) by VLAN.
Note: something related to this has been implemented requiring "mirrored" traffic to be enabled.

**Comment by MatteoBiscosi** [comment]
The issue should now be fixed (tested on both vlan and probe ip). Please reopen if needed.
![Screenshot from 2022-07-27 16-17-11](https://user-images.githubusercontent.com/49585191/181271189-42bd96f0-682e-41f7-8788-c77178295942.png)
