### ISSUE TITLE
The new CMake build system does not create config.h file

### ISSUE THREAD

**Issue by pengxingwei** [ntop/ntopng#6707]
**Environment**:
* OS name: fedora
* OS version: 36
* Architecture: amd64
* ntopng version/revision: ntopcpp20

**What happened**:
I downloaded the ntopcpp20-branch, and run cmake and make, then I got this error message:
ntop_include.h :25:10  fatal error: config.h: No such file or directory #include "config.h"

**Debug Information**:

**Comment by lucaderi** [comment]
This is an unmaintained branch please ignore it
