### ISSUE TITLE
Invalid Check Exception Entry

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6708]
Adding this exception
![Screen Shot 2022-06-17 at 19 24 50](https://user-images.githubusercontent.com/4493366/174348301-4389c42a-b8a8-45a7-baa4-0e239c87e221.png)

produces
![Screen Shot 2022-06-17 at 19 25 10](https://user-images.githubusercontent.com/4493366/174348337-0c41bee3-ece4-43ae-ad43-60fda9abf178.png)

**Comment by cardigliano** [comment]
Fixed in 9f6d55425f3451918d081e9703aefef34daf7497
