### ISSUE TITLE
Unable to add TLS exclusion

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6709]
Adding C=US, O=Let's Encrypt, CN=Let's Encrypt Authority X3
![Screen Shot 2022-06-17 at 19 42 53](https://user-images.githubusercontent.com/4493366/174350638-2720cf25-20a8-4000-b3a9-b4ca025bd788.png)

is not working
![Screen Shot 2022-06-17 at 19 43 14](https://user-images.githubusercontent.com/4493366/174350666-f8bb0bbc-39bd-40c6-af60-5974932719c3.png)

Note that exceptions added via https://github.com/ntop/ntopng/issues/6708 cannot be deleted and the only way to remove it, is with a reset "Delete Check Exclusions"

**Comment by cardigliano** [comment]
Fixed in e1ac8e29edfd174ac5a5ffdd120c9ecf35b5b8db
