### ISSUE TITLE
[RHEL/CentOS 7] HTTPS server problem with libraries

### ISSUE THREAD

**Issue by mhercek** [ntop/ntopng#671]
I've installed ntopng v2.5.160802-1389 from repo.
It complained about not being able to start HTTPS server:
`[mongoose.c:4673] ERROR: load_dll: cannot load libssl.so`
`[mongoose.c:4673] ERROR: load_dll: cannot load libcrypto.so`

Solved by creating symlinks.

**Comment by simonemainardi** [comment]
hi, thans for reporting. We already have a branch that aims at resolving that issue: https://github.com/ntop/ntopng/compare/no-ssl-dl?expand=1

in the meanwhile, if you are on centos7, you should be able to hot fix that by manually symlinking lobssl.so to the actual libssl version:

```
272K -rwxr-xr-x 1 root root 271K Apr 25 16:34 /lib64/libssl3.so*
   0 lrwxrwxrwx 1 root root   16 Jun 22 10:03 /lib64/libssl.so -> libssl.so.1.0.1e*
   0 lrwxrwxrwx 1 root root   16 Jun 22 09:58 /lib64/libssl.so.10 -> libssl.so.1.0.1e*
440K -rwxr-xr-x 1 root root 440K May  9 10:10 /lib64/libssl.so.1.0.1e*
```

same for libcrypto

**Comment by simonemainardi** [comment]
also, did you read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL

**Comment by simonemainardi** [comment]
addressed by

https://github.com/ntop/ntopng/commit/26625a11219260ddf72de153d13cb7c567c9ed99
https://github.com/ntop/ntopng/commit/83fef09467a6be64f4a1f63a1e21c8af65bf35ef
https://github.com/ntop/ntopng/commit/dd56a20e0dd662a639a951b687886f082e3578f1
