### ISSUE TITLE
Missing format validation in domain name

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6710]
In check Exclusions, domain validation is missing. Example the following domain is accepted
![Screen Shot 2022-06-17 at 23 12 18](https://user-images.githubusercontent.com/4493366/174401816-5f0a5f6a-5afd-4b68-b543-14775967ccae.png)

**Comment by lucaderi** [comment]
Still bugged
![Screen Shot 2022-06-28 at 08 48 20](https://user-images.githubusercontent.com/4493366/176112091-92f4aea0-0a36-40f0-b73f-b462885efa0e.png)

In domain names you can have letters numbers, dot, hyphen, minus sign

**Comment by MatteoBiscosi** [comment]
Verified as fixed
