### ISSUE TITLE
Inconsistent TLS Exclusion

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6712]
![image](https://user-images.githubusercontent.com/4493366/174402167-c7f959de-bfbc-4c68-b701-a05b5ae36e17.png)

The correct works is TLS Certificate Issuer, and it must be used everywhere for consistency

**Comment by cardigliano** [comment]
Confirmed as fixed 
<img width="1188" alt="Screen Shot 2022-06-20 at 11 42 52" src="https://user-images.githubusercontent.com/7548711/174574245-d974b7ef-d5f8-45b3-9cbe-2ef8c26c407f.png">
