### ISSUE TITLE
Consistent nameing throughout ntopng

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6716]
**What would you like to add or change?**:
Hello
Current version of ntopng has one exception for "Suspicious":

<img width="410" alt="Screenshot 2022-06-18 at 09 42 55" src="https://user-images.githubusercontent.com/38549755/174441387-a27d2f17-2312-4108-a409-d9459d608dd2.png">

I personally do not like abbreviation, as then one need a table explaining the abbreviation.

**Why do you and others need this?**:

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu I updated all the alerts naming and removed abbreviations, so everything should be consistent
