### ISSUE TITLE
Disabling flow alerts also disables historical flows

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#6719]
Please check that disabling flow alerts on the preference page does not disables also the historical flows (reported by a user)

**Comment by imrane2e** [comment]
I can confirm the bug 

`ntopng --version
Version:	5.3.220621 [Enterprise/Professional build]
GIT rev:	dev:61cfe7b50ec02aac818d097b2b86b0843278f288:20220621
Pro rev:	r5104`

Disabled Emit Host Alerts, and Emit Flow Alerts and I am not able to browse any data on historical flows before this 

re-enabling doesn't help either. 

I am using click house to dump flows and I don't see any significant changes in data there. So I am assuming the data is there but is somehow not picked up by top

Please let me know if any further information is required for troubleshooting this

**Comment by cardigliano** [comment]
Works for me, waiting for a debug session with the user to verify the issue

**Comment by cardigliano** [comment]
This was related to a change to the interface, we can close this.
