### ISSUE TITLE
The meaning of  log field in elasticsearch

### ISSUE THREAD

**Issue by CindyStudyEveryday** [ntop/ntopng#6722]
After outputting ntopng to elasticsearch, does the meaning of each log field in elasticsearch have a corresponding description? I know some, but I'm not sure about all. Thank you！
![image](https://user-images.githubusercontent.com/87004981/175002954-1dab7560-888c-4239-8878-12fb2156e5c6.png)

**Comment by MatteoBiscosi** [comment]
Hi @CindyStudyEveryday you probably have an old version of ntopng. Please update to the latest ntopng dev version (5.3), in fact in our latest version we migrated to the ECS formatting
https://www.elastic.co/guide/en/ecs/current/ecs-field-reference.html
![Screenshot from 2022-06-22 12-14-25](https://user-images.githubusercontent.com/49585191/175004991-6a27ea75-eecb-41f7-9ed3-ecf024b9bc3b.png)
