### ISSUE TITLE
Plugins option not showing

### ISSUE THREAD

**Issue by deanfourie1** [ntop/ntopng#6723]
So I have a few issues I need to address. These are strange issues and have no idea what is going on. People keep telling me its due to a network misconfiguration but its not.

I have 

1) No plugins option at all in the menu. It simply does not exist.
2) LAN hosts often show as ghost hosts, and these ghost hosts move around between the hosts, its completely random as to who will be ghost hosts next.

Any ideas?

Thanks

**Comment by MatteoBiscosi** [comment]
Hi @deanfourie1 please share your ntopng --version and ntopng configuration. Could you please send a couple of screenshot to understand better your case?

**Comment by miguelhernandez-work** [comment]
Not to high-jack someone elses issue, but I also have no menu for plugins, and thus can't get influxdb-monitor plugin which the help docs say i should be able to use to look at my timeseries health.
```
# ntopng --version
Version:        5.3.220628 [Enterprise/Professional build]
GIT rev:        dev:98571202fd06c1b2ea8699ced0b6c3ef4858a9b6:20220628
Pro rev:        r5106
Built on:       Ubuntu 20.04.4 LTS

Platform:       x86_64
Edition:        Enterprise L (Bundle)
License Type:   Time-Limited [Empty license file]
Validity:       Until Tue Jun 28 22:26:26 2022
```
```
# cat /etc/ntopng/ntopng.conf | grep -v "#"
-G=/var/run/ntopng.pid
-i=bond0
-m=<omitted>
-X=1000000
--ignore-vlans=2900
-S=
```

**Comment by MatteoBiscosi** [comment]
Hi guys, please update to the latest ntopng version and let me know if everything is working fine. Otherwise please send me a couple of screenshots of your GUI

**Comment by MatteoBiscosi** [comment]
Hi guys, Plugins entry was removed in the latest ntopng versions. We renamed them "Checks" (for alerts) and "Notifications" (for endpoints and recipients). So please tell me what you are searching for and where did you find the Plugins option, maybe I forgot to remove it from the doc

**Comment by MatteoBiscosi** [comment]
Hi @miguelhernandez-work the issue should be fixed in the latest ntopng dev version. please update in a couple of hours and everything should work correctly. You do not need to enable plugins to monitor influxdb, when you enable influxdb a new Health page should appear reporting influxdb status.

**Comment by miguelhernandez-work** [comment]
Looks good, it's working. Thanks! If anyone is wondering, the "Health" left-menu option is only visible once you select "System" from the dropdown, if you have an interface selected from that dropdown you won't see the Health menu option.
