### ISSUE TITLE
two questions about ntopng -elasticsearch

### ISSUE THREAD

**Issue by CindyStudyEveryday** [ntop/ntopng#6725]
I would like to ask two questions.

1、When -f is used to write data to elasticsearch, the time field will see UNIX format in elasticsearch. Is there any method to add configuration to make it into normal time format?
2、How often is the data written into elasticsearch? End of a full session? Or how many seconds? I observed the same source IP, destination IP, source port and destination port, and found no obvious time correlation. Can you give me some guidance? thank you

**Comment by MatteoBiscosi** [comment]
Hi @CindyStudyEveryday in a few hours a new update should be available and with it you are able to change elastic dump frequency from the ntopng settings (Settings -> Advanced Options -> Flow Dump Settings -> Flow Dump Frequency).
With the new update, the dump frequency by default it's a 2 minute dump.
Note that flows are dumped when they end or when no more packets of that flow are no more seen for some minutes.
Regarding the timestamp, it should be in a human readable timestamp (see image below)
![Screenshot from 2022-06-27 16-54-25](https://user-images.githubusercontent.com/49585191/175971046-43833ddd-30ac-448a-b357-6b513a42944f.png)
