### ISSUE TITLE
Slow alert table loading due to errors

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6726]
<img width="678" alt="image" src="https://user-images.githubusercontent.com/4493366/175488384-cc30b424-ddd6-44f3-afc9-f1837ad17678.png">

**Comment by uccidibuti** [comment]
Could you try to get the last version of ntopng/dist?
These files are present in https://github.com/ntop/ntopng-dist  ( [518b8c59f15bff8fad43.png](https://github.com/ntop/ntopng-dist/blob/dev/518b8c59f15bff8fad43.png) , [b2160eb121c76bb72cb1.png](https://github.com/ntop/ntopng-dist/blob/dev/b2160eb121c76bb72cb1.png) ). I have the last version of ntopng and all png are get in right way.
I need more info to reproduce this bug.
