### ISSUE TITLE
When will you release a new version for RaspberryPi-Devices with fixed Bug #6713 ?

### ISSUE THREAD

**Issue by closertotheedge** [ntop/ntopng#6729]
Issue"Attempt to index a nil value in lua_utils.lua #6713" is still not fixed for RaspberryPi Devices. 

I would appreciate if you could release a bugfixed version for that kind of devices.

**Comment by lucaderi** [comment]
Every week-end new builds are availble, such as yesterday https://packages.ntop.org/apt/buster_pi/armhf/
