### ISSUE TITLE
Unif - BitTorrent 

### ISSUE THREAD

**Issue by marcocamza** [ntop/ntopng#673]
Communication between Access points and controller are detected as BitTorrent

**Comment by kYroL01** [comment]
@marcocamza I think this is a possible nDPI issue. Please open this issue on nDPI and provide us a pcap to verify the problem.
Thank you

**Comment by marcocamza** [comment]
Ok but ntopng is installed on pfsense so I can't provide the requested.

**Comment by lucaderi** [comment]
You need to do a tcpdump and generate a pcap file. Without it we cannot help unfortunately.

**Comment by lucaderi** [comment]
Closed for inactivity. Will reopen if necessary
