### ISSUE TITLE
Misleading header time in collector mode

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6732]
When starting nprobe and ntopng as follows
- ntopng -i tcp://127.0.0.1:1234
- nprobe -i none -n none -3 2055  --zmq tcp://127.0.0.1:1234

This box is displayed

![Screen Shot 2022-06-27 at 19 49 18](https://user-images.githubusercontent.com/4493366/176004198-02fc9b7e-3568-44d8-b42d-9e930f943316.png)

The time is static and it does not go back until zero when the page should refresh. This can be misleading for people. This ticket is to request to update the time and refresh the page until the time disappears.

**Comment by MatteoBiscosi** [comment]
Verified as fixed
