### ISSUE TITLE
Create new custom feed under Category Lists

### ISSUE THREAD

**Issue by jacoporusso-css** [ntop/ntopng#6736]
**What would you like to add or change?**:
Please add the capability to create a new Category List via web UI (e.g.: adding a "+" sign to let users define their own feeds).

**Why do you and others need this?**:
Enhance checks with custom data.

**Comment by lucaderi** [comment]
Implemented by https://github.com/ntop/ntopng/commit/5e8769b1b5c55899c4ed03c7599f3cef7bb010e3
