### ISSUE TITLE
Cannot create users containing "." character

### ISSUE THREAD

**Issue by jacoporusso-css** [ntop/ntopng#6737]
**Environment**:
* ntopng version/revision: 5.2.220520

**What happened**:
If I try to create a user containing "." character inside its username, nothing happens.

**Comment by MatteoBiscosi** [comment]
Hi @jacoporusso-css as you can see from the screenshot, it's now possible to add '.' character to usernames.
Please wait for a couple of hours and a new stable version should be available, update and the issue should be fixed.
![Screenshot from 2022-06-28 15-17-55](https://user-images.githubusercontent.com/49585191/176188491-935207a8-7646-4c07-88fa-bed542ad41d4.png)
