### ISSUE TITLE
Unable to find my custom categories

### ISSUE THREAD

**Issue by 612wong** [ntop/ntopng#6738]
**Environment**:
* OS name: RHEL
* OS version: 7.9
* Architecture: x86_64
* ntopng version/revision: v.5.3.220628

**What happened**:
I had about 21 applications under 'custom user category 1'.
I changed the name of 'custom user category 1' to 'new app' as an example.
Under the application tab, the 21 applications are still showing 'custom user category 1'.
I changed the 21 applications from 'custom user category 1' to 'unspecified' and save it.
I wanted to move them from 'unspecified' category to 'new app' category but I couldn't find 'new app' in the category list.
Restarting ntopng didn't help.

**What did you expect to happen?**
I expected the new name for 'custom user category 1' will be updated in the system such that:
- applications under 'custom user category 1' will be under the new name.
- the new name is shown in the filter list under the application tab.
- the new name is shown in the dropdown list for applications

**How did you reproduce it?**
1. change the name of 'custom user category 1'.
2. under the application tab, the category filter doesn't show the new name of 'custom user category 1' or 'custom user category 1'.
3. under the application tab, the dropdown list for application category doesn't the new name of 'custom user category 1' but the old name, i.e. 'custom user category 1'.

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @612wong , thanks a lot for your report, now it should work, i edited a custom category and as you can see i can find it in the dropdown. please wait for tomorrow update, update and let me know.
![Screenshot from 2022-07-01 11-49-57](https://user-images.githubusercontent.com/49585191/176871567-0dec9020-0f96-4817-9c65-982f9d930b66.png)
![Screenshot from 2022-07-01 11-49-44](https://user-images.githubusercontent.com/49585191/176871569-858ea60a-cd27-415c-9b95-6ec5ab7fc7a2.png)

**Comment by 61swong** [comment]
Hi @MatteoBiscosi , I confirmed the patch fixed the issue. Thanks!
