### ISSUE TITLE
MAC Address Search Points to Wrong URL

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6739]
![Screen Shot 2022-06-29 at 11 51 56](https://user-images.githubusercontent.com/4493366/176408007-e5bebe80-47ef-41f1-9902-f12620f0c3a5.png)

Searching a MAC address and clicking on it (2nd line) will redirect to

http://localhost:3000/lua/host_details.lua?ifid=2&host=B8%3A27%3AEB%3A4D%3A44%3AC8&mode=restore
![Screen Shot 2022-06-29 at 11 54 00](https://user-images.githubusercontent.com/4493366/176408264-3e546396-a1cb-4f24-8689-fd3edef15c44.png)

that will run forever (i.e. the restore is stuck) instead of going to

http://localhost:3000/lua/mac_details.lua?host=B8:27:EB:4D:44:C8

that instead works

![Screen Shot 2022-06-29 at 11 55 08](https://user-images.githubusercontent.com/4493366/176408542-52fe277e-1626-47e0-ba3d-bd3153a8d94c.png)

**Comment by cardigliano** [comment]
The mac type is correctly set now from the backend, but the gui should also be fixed to handle that. Example:
<img width="628" alt="Screen Shot 2022-06-29 at 15 30 59" src="https://user-images.githubusercontent.com/7548711/176450241-0504a056-8035-496d-ac19-d9d0ee6f8fbb.png">
<img width="343" alt="Screen Shot 2022-06-29 at 15 31 13" src="https://user-images.githubusercontent.com/7548711/176450259-1158219e-c6ca-412a-8720-4499f87d72ba.png">
