### ISSUE TITLE
ntopng pro license not working

### ISSUE THREAD

**Issue by arthurvmdantas** [ntop/ntopng#674]
Hi all,

I work for an educational institution on Brazil and recently we were given nProbe and ntopng pro licenses. The nProbe license works as expected but not the ntopng license.

I've used my system id and order id to generate the code license but when I put it on the license input box and click the "Save license" button.. nothing happens!
It still says "Community Edition" and shows an yellow/orange warning: "Upgrade to Professional version".

Here is a screenshot (hosted in OneDrive):
https://1drv.ms/i/s!Am7J0kdJ6qEuilCH46-yt4dmCmUf

Thanks!

p.s: I've sent this issue to an ntopng representative (by email) and she asked me to get help here.

**Comment by lucaderi** [comment]
I have invalidated the license for your orderId 1468590713. You can solve this problem downloading http://packages.ntop.org/Windows/ntopng-2.4.160627_1-x64.zip and re-generating the license.

**Comment by arthurvmdantas** [comment]
Hello lucaderi, thanks for your response. Unfortunately, it's still not working. Are you certain that my order id is for a Pro edition?

I've downloaded and installed the file you linked. After that, I had the Pro [Small Business Edition] that expires after 10 minutes. Then, I generated a new license (through "About ntopng" option) and saved it. Afterwards, the license label says "Community Edittion".

Is there another way to save the license? I mean, maybe putting it on a file like we did with nProbe.

I'm running ntopng as a service on Windows Server 2012.

Thanks!

**Comment by lucaderi** [comment]
@arthurvmdantas @simonemainardi  Simone can assist you if necessary. However the problem is that the version you have entered during license creation is wrong. Please install the latest ntopng and generate the license passing all the correct values in the license form that will also tell you how to save the license on a file.

**Comment by arthurvmdantas** [comment]
I did all the steps again and now it's working as Pro Small Business [338 days left]. =) 

Thank you very much for your support, lucaderi.
