### ISSUE TITLE
Hosts View: Add the score column

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6741]
In the past years the score is an important value for all ntopng components but unfortunately in the hosts page the score is on an optional column as shown below
![Screen Shot 2022-06-29 at 18 53 01](https://user-images.githubusercontent.com/4493366/176492721-854eabbb-8ca2-44d5-9ecd-e4e70b6a2da3.png)

This ticket is to request to add permanently the score column in the above table and remove it from this dropdown menu.

**Comment by MatteoBiscosi** [comment]
Implemented as requested
