### ISSUE TITLE
DNS Server Logic is Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6742]
ntopng is able to detect DNS servers and mark them as such. Unfortunately, this logic is broken. Below is an example of this bug.

![image](https://user-images.githubusercontent.com/4493366/176493954-8470ecec-fb2a-4873-8b8d-fb4acf8873c0.png)

![image](https://user-images.githubusercontent.com/4493366/176493861-23523547-7bc8-47d9-90cb-06e9c8f153d9.png)

**Comment by MatteoBiscosi** [comment]
Verified as fixed, the problem was with view interfaces
