### ISSUE TITLE
gpg: error reading key: public key not found

### ISSUE THREAD

**Issue by skore-onclave** [ntop/ntopng#6743]
I'm building Debian package using `deb - do 'cd packages/ubuntu;./configure; make` during this process, it triggered `gpg: error reading key: public key not found error`, to resolve this issue I generated a new gpg key but I'm not sure where to place the outcome of the `gpg --gen-key` so that it can read it and process the build.

**Comment by cardigliano** [comment]
Please check the "dpkg-sig --sign" command in ntopng/packages/ubuntu/Makefile.in
