### ISSUE TITLE
ntopng give an errors during upgrade after upgrade crush

### ISSUE THREAD

**Issue by Eugene-Prokhorenko** [ntop/ntopng#6744]
Unpacking uidmap (1:4.5-1ubuntu2.3) over (1:4.5-1ubuntu2.2) ...
Setting up ubuntu-advantage-tools (27.9~18.04.1) ...
Installing new version of config file /etc/ubuntu-advantage/uaclient.conf ...
Created symlink /etc/systemd/system/multi-user.target.wants/ubuntu-advantage.service → /lib/systemd/system/ubuntu-advantage.service.
Setting up libcurl4:amd64 (7.58.0-2ubuntu3.19) ...
Setting up uidmap (1:4.5-1ubuntu2.3) ...
Setting up snapd (2.55.5+18.04) ...
Installing new version of config file /etc/apparmor.d/usr.lib.snapd.snap-confine.real ...
snapd.failure.service is a disabled or a static unit not running, not starting it.
snapd.snap-repair.service is a disabled or a static unit not running, not starting it.
Setting up ndpi (4.3.0-3777) ...
Rebuilding ld cache...
Setting up ntopng-data (5.3.220630) ...
Setting up rsyslog (8.32.0-1ubuntu4.2) ...
The user `syslog' is already a member of `adm'.
Unsafe symlinks encountered in /var/spool/rsyslog, refusing.
Unsafe symlinks encountered in /var/log, refusing.
Unsafe symlinks encountered in /var/log/auth.log, refusing.
Unsafe symlinks encountered in /var/log/mail.log, refusing.
Unsafe symlinks encountered in /var/log/kern.log, refusing.
Unsafe symlinks encountered in /var/log/syslog, refusing.
dpkg: error processing package rsyslog (--configure):
 installed rsyslog package post-installation script subprocess returned error exit status 1
Setting up curl (7.58.0-2ubuntu3.19) ...
Setting up pfring (8.1.0-7564) ...
Setting up n2disk (3.7.220630-5372) ...
Rebuilding ld cache...
(Re)Starting n2disk...
Setting up ntopng (5.3.220630-18000) ...
Rebuilding ld cache...
(Re)Starting ntopng...

NOTE

ntopng Community does not require a license.
ntopng Pro/Enterprise licenses are perpetual and include 1 year maintenance/updates:
you can use the software even after maintenance is expired, however updating it after
1 year would prevent ntopng from running. If you have automatic updates enabled, and
maintenance is expired, it is recommended to put the package updates on hold with:

apt-mark hold ntopng

Automatic updates can be enabled again with:

apt-mark unhold ntopng

Setting up nprobe (9.7.220630-7847) ...
Rebuilding ld cache...
Making the /var/log/nprobe directory...
(Re)Starting nprobe services...
Setting up cento (1.17.220630-753) ...
Making the /var/log/cento directory...
(Re)Starting cento...
cento@* is a disabled or a static unit not running, not starting it.
Processing triggers for libc-bin (2.27-3ubuntu1.6) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for dbus (1.12.2-1ubuntu1.3) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Errors were encountered while processing:
 rsyslog
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@asnet-monitoring:~# 

**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]

**What happened**:

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by cardigliano** [comment]
@Eugene-Prokhorenko it seems the installation of rsyslog is failing, this is not directly related to ntopng..
