### ISSUE TITLE
No installation package problem when installing ntopng in debian

### ISSUE THREAD

**Issue by hdsjahuen** [ntop/ntopng#6745]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]

**What happened**:

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

debian version：11
When I install ntopng in debian, I have a problem that there is no installation package
As this picture shows, what is the reason? What should I do?
[image](https://github.com/hdsjahuen/hk/blob/main/1.jpg)

**Comment by hdsjahuen** [comment]
I followed your installation guide exactly

**Comment by cardigliano** [comment]
@hdsjahuen this seems to be working for me, please try running the below commands and providing the output:

apt-get update && apt-get upgrade
apt install pfring
apt list --installed | grep pfring
apt install ntopng
