### ISSUE TITLE
Remove Telemetry Collection 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6749]
Telemetry collection is not a very popular feature and the idea is to remove it and eventually migrate to the service (https://northernlightlabs.se/2014-07-05/systemd-status-mail-on-unit-failure.html)

**Comment by martinscheu** [comment]
good decision!

**Comment by MatteoBiscosi** [comment]
Telemetry was removed in the commit 8dad513a4e1abdfba256d887d5fc6e37c7082129

**Comment by lucaderi** [comment]
Already implemented

**Comment by lucaderi** [comment]
Already implemented
