### ISSUE TITLE
application searchin 'App tab' doesn't work under "Setting>Application and Categories"

### ISSUE THREAD

**Issue by 61swong** [ntop/ntopng#6753]
**Environment**:
* OS name: RHEL
* OS version: 7.9
* Architecture: x86_86
* ntopng version/revision: v5.3.220703

**What happened**:
I cannot search application in the app tab under "Setting>Application and Categories"
Restart of the ntopng service doesn't help.
![searchapp](https://user-images.githubusercontent.com/50309519/177094685-e33fe07b-83a3-4526-90a2-f4227d84b946.PNG)

However I can search category in the category tab.
![searchcategory](https://user-images.githubusercontent.com/50309519/177094705-8930bf7d-8479-49ea-b847-88eff934176d.PNG)

**What did you expect to happen?**
I am able to search app by typing the app's full or partial name

**How did you reproduce it?**
Anytime.

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @61swong the issue should be fixed with the latest version, please update tomorrow and let me know

**Comment by 61swong** [comment]
Hi @MatteoBiscosi , thanks for the fix. It's working now.
