### ISSUE TITLE
Poor Vue.js performance in Historical Flows

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6754]
Despite fast ClickHouse lookups, the user interface is sluggish

[ntopng Enterprise L v.5.3.220704 (Rocky Linux release 8.5 (Green Obsidian)) | ](https://www.ntop.org/products/traffic-analysis/ntop/)
 
Query performed in 0.12 seconds. SQL
 
GUI 34 sec

**Comment by uccidibuti** [comment]
The problem doesn't seem to be related to interface and vue js but by server GET slowness. To fix it we must profiling lua codes.
![image](https://user-images.githubusercontent.com/12447209/177161971-4348bd2d-c07d-4020-bd57-ac2e147a685c.png)
![image](https://user-images.githubusercontent.com/12447209/177162163-dda98443-a604-4567-9a54-d270ca77e09d.png)

**Comment by lucaderi** [comment]
Fixed with SNMP polling optimizations
