### ISSUE TITLE
Search bug

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6755]
On 192.168.2.49 search 
![Screenshot 2022-07-04 at 09 35 21](https://user-images.githubusercontent.com/4493366/177105149-62aa1691-ec78-4865-8b7f-0e12f43936e8.png)

click on 3Com will lead you to

http://192.168.2.49:3000/lua/pro/enterprise/snmp_interface_details.lua?ifid=5&host=&snmp_port_idx=16

![Screenshot 2022-07-04 at 09 37 04](https://user-images.githubusercontent.com/4493366/177105460-4914616c-7fbb-4d9c-8f8e-981b31e7e28f.png)

**Comment by cardigliano** [comment]
27c31ac4a07c58b97d519311b8be31bc8705186a should address this (building new packages to test this)

**Comment by lucaderi** [comment]
Verified as fixed
