### ISSUE TITLE
Unexpected NTP server found - NTP server in exclude list not working

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6757]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]: ntopng Enterprise L v.5.3.220623 (Ubuntu 20.04.4 LTS) | 

**What happened**:
When having an internal NTP server, 3.238, which is allowed to contact any external NTP server and therefore is added to the excluded hosts is still generating unexpected NTP server found alerts:

<img width="767" alt="Screenshot 2022-07-04 at 09 50 50" src="https://user-images.githubusercontent.com/38549755/177107923-f0b6e51d-842b-42c9-9c13-1cce7461d225.png">

<img width="1201" alt="Screenshot 2022-07-04 at 09 52 17" src="https://user-images.githubusercontent.com/38549755/177108035-a5f9625d-3865-4927-868c-aaab3445f46f.png">

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by cardigliano** [comment]
@martinscheu what about using Settings -> Behavioural Check Exclusions to add host exceptions instead?
This setting from the check should be removed as we now have the new Behavioural Check Exclusions and this looks duplicated/deprecated.

**Comment by cardigliano** [comment]
Excluded Hosts removed from check config bebb1e92193b39ada54f878417417fbc85803a04, please use Settings -> Behavioural Check Exclusions to add exceptions
