### ISSUE TITLE
Historical flow explorer - drop down top applications and alerts is not working

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6758]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]: ntopng Enterprise L v.5.3.220704 (Ubuntu 20.04.4 LTS) |

**What happened**:

<img width="2088" alt="Screenshot 2022-07-04 at 10 02 50" src="https://user-images.githubusercontent.com/38549755/177110059-8f7272ab-f7e7-4107-82d2-bb6797333578.png">

https://user-images.githubusercontent.com/38549755/177110079-a969668e-0f1f-49f2-a221-17eafd760bc2.mov

**What did you expect to happen?**

**How did you reproduce it?**

**Debug Information**:

**Comment by cardigliano** [comment]
@martinscheu this is working for me, could you run the below steps to provide more info?
1. Open the web inspector to see "Network" requests
2. Click on Top Applications
3. Check the request to top.lua (there can be many, check the latest one, triggered when clicking on the Top Applications), and provide a screenshot of the response content
Thank you

**Comment by martinscheu** [comment]
thanks @cardigliano 
I closed the browser, deleted the cache and now it is working too :)
sorry

**Comment by cardigliano** [comment]
Ok, @uccidibuti pushed a fix for this, not sure if it was that, but it seems we can close this
