### ISSUE TITLE
Category filter shows original name of 'custom category' in 'app' tab under Setting>Applications and Categories

### ISSUE THREAD

**Issue by 61swong** [ntop/ntopng#6761]
**Environment**:
* OS name: RHEL
* OS version: 7.9
* Architecture: x86_64
* ntopng version/revision: 5.3.220705

**What happened**:
In the 'app' tab under Setting>Applications and Categories, the 'Category' filter still shows the original name of the user custom category.

![categoryFilter](https://user-images.githubusercontent.com/50309519/177259532-6674082d-f9ed-45b3-b456-1de5fc943701.PNG)

**What did you expect to happen?**
I expect the 'Category' filter to show the new name 'i.e. corp cloud' instead of the original name.

**How did you reproduce it?**
Anytime and restart of ntopng doesn't help.

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @61swong thanks again for your report, the issue should now be fixed, please wait for a couple of hours and a new update should be available
![Screenshot from 2022-07-05 16-42-31](https://user-images.githubusercontent.com/49585191/177354686-9c33e6e4-ca79-4ef1-9e1f-402f8561f19b.png)

**Comment by 61swong** [comment]
Hi @MatteoBiscosi thanks for the fix. I confirmed it's working now.
