### ISSUE TITLE
Errors while exporting ELK alerts to a an ELK instance that is down

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6764]
05/Jul/2022 11:38:03 [Utils.cpp:1527] WARNING: Unable to post data to (http://localhost:9200/_template/so-ntopng): Couldn't connect to server
05/Jul/2022 11:38:03 [notifications.lua:25] [elasticsearch.lua:103] ERROR: Unable to configure the Elasticsearch alerts-ntopng- index http://localhost:9200
05/Jul/2022 11:38:03 [notifications.lua:25] [elasticsearch.lua:131] ERROR: Unable to fetch Elasticsearch version
05/Jul/2022 11:38:03 [notifications.lua:25] [elasticsearch.lua:133] ERROR: 
05/Jul/2022 11:38:03 [notifications.lua:25] [recipients.lua:829] ERROR: Error while sending notifications via ElasticAlerts Unsupported Elasticsearch version 0. Need at least version 7.
05/Jul/2022 11:38:06 [notifications.lua:25] [recipients.lua:829] ERROR: Error while sending notifications via ElasticAlerts Unsupported Elasticsearch version 0. Need at least version 7.
05/Jul/2022 11:38:09 [notifications.lua:25] [recipients.lua:829] ERROR: Error while sending notifications via ElasticAlerts Unsupported Elasticsearch version 0. Need at least version 7.

These version errors are misleading: the problem is that ELK is down and errors should be silenced after a while in order not to fil the disk

**Comment by MatteoBiscosi** [comment]
Now the check, in case a recipient crashes, is done every 2 minutes instead of 3 seconds, in this way it's able to check if perhaps the service goes up again but at the same time those errors do not fill the disk

**Comment by MatteoBiscosi** [comment]
Verified as fixed
