### ISSUE TITLE
Original name of 'user custom category...' is shown in other areas.

### ISSUE THREAD

**Issue by 61swong** [ntop/ntopng#6767]
**Environment**:
* OS name: RHEL
* OS version: 7.9
* Architecture: x86_86
* ntopng version/revision: 5.5.220707

**What happened**:
The original name of 'user custom category...' is shown in:
- interface > app > category tab
![interface_app_categorytab](https://user-images.githubusercontent.com/50309519/177690842-bd921a5c-36db-4734-bd0c-93072927d990.PNG)

- heading of the application list (setting > applications and categories) with my custom category
![headline](https://user-images.githubusercontent.com/50309519/177690855-664c4650-9b62-4db3-adf5-375ba2ed11f0.PNG)

Restart doesn't help.

**What did you expect to happen?**
I expect to see the updated name of 'user custom category ...'

**How did you reproduce it?**
Change the name of the 'user custom category ...' and try to show the steps in 'what happened'.

**Debug Information**:

**Comment by 612wong** [comment]
Hi @MatteoBiscosi , thanks for your update but I still can reproduce it in v5.5.220708.

<img width="1272" alt="Screen Shot 2022-07-08 at 15 32 15" src="https://user-images.githubusercontent.com/58540705/177924797-b07c8e5d-412e-429d-ac37-07f240d7a975.png">

<img width="1263" alt="Screen Shot 2022-07-08 at 15 38 00" src="https://user-images.githubusercontent.com/58540705/177924842-102b8c7d-5426-4d01-8642-3dc55d86e022.png">

Besides, I found similar bug in v5.5.220708 under Interface > historical data where the original name of the 'uesr custom category ...' is shown.

<img width="611" alt="Screen Shot 2022-07-08 at 15 44 52" src="https://user-images.githubusercontent.com/58540705/177925144-3a8564a2-4ed4-4f68-b460-4ab4fe891791.png">

<img width="1265" alt="Screen Shot 2022-07-08 at 15 45 29" src="https://user-images.githubusercontent.com/58540705/177925160-10ddef4a-5f80-451a-9787-7a0bd6058990.png">

**Comment by MatteoBiscosi** [comment]
Hi @61swong thanks again for your reports, i should have fixed this category name issue in all the pages, please let me know in the following days if you perhaps find some issue

**Comment by 61swong** [comment]
Hi @MatteoBiscosi , thanks for the fix. I confirmed the issue's fixed. Cheers.
