### ISSUE TITLE
Make NtopNG local network definition a "per-interface" feature

### ISSUE THREAD

**Issue by jacoporusso-css** [ntop/ntopng#6774]
**What would you like to add or change?**:
It would be greatly helpful to switch the local network definition in NtopNG (and so the Hosts->Networks section in the UI) from global feature to interface local.

**Why do you and others need this?**:
Oftentimes distributed environments have overlapping/double local network ranges (e.g.: multiple stores, each one with a WLAN range equal to 192.168.1.0/24 OR 192.168.1.0/23, hidden behind a SNAT). Assigning each one to a nprobe talking to a different interface on NtopNG would require such an implementation to avoid chosing between one of the overlapping networks, losing accuracy on the other one.

**Comment by MatteoBiscosi** [comment]
After internal discussion we decided to not do it, because most of the times (for our customers) those networks are the same
