### ISSUE TITLE
Cannot change password

### ISSUE THREAD

**Issue by jacoporusso-css** [ntop/ntopng#6775]
* ntopng version/revision: [v 5.4.220707 ]

**What happened**:
When a user change his password (even if changed from an admin account), even if a success messaged is displayed, upon new login the new credentials appear invalid. Using the old one works. So, password doesn't get updated.

**Comment by MatteoBiscosi** [comment]
Hi @jacoporusso-css I'm unable to reproduce your issue, I tried to create a new user, login with that user and change the password and everything seems working.
Could you please tell me more details? like your exact way from creating the user to changing the password? Is there some error reported in the journalctl (journactl -e -u ntopng)?

**Comment by jacoporusso-css** [comment]
Hi Matteo,
 thank you for your suggestion. Unfortunately nothing related to this problem can be found in journalctl.
Anyway we did some further research, here's the exact condition triggering the issue:
If a user is created in a version of NtopNG prior 5.4.220707, the issue (not being able to change password) appears after upgrading.
Moreover these users are affected by another related problem: if they're deleted and created again with the same username, they won't be accessible with any password at all, so they become unusable.

Just to be clear: none of these issues appear for users created after upgrading to 5.4.220707

**Comment by MatteoBiscosi** [comment]
Hi @jacoporusso-css it seems that with the latest changes the issue (at least for the last version) is fixed. Please reopen the issue if it's going to appear again the same problem in the upcoming versions.
