### ISSUE TITLE
After upgrading ntopng traffic on interface is no more collected

### ISSUE THREAD

**Issue by lvalero** [ntop/ntopng#6776]
Hello,

GUI showed an upgrade for ntopng, i issued an "apt-get update" and "apt-get upgrade" and reboot, after reboot, services are up and running : 

root@ntopng:~# systemctl status clickhouse-server.service
â— clickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
     Loaded: loaded (/lib/systemd/system/clickhouse-server.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-07-11 06:52:20 EDT; 21s ago
   Main PID: 584 (clckhouse-watch)
      Tasks: 206 (limit: 9506)
     Memory: 690.2M
        CPU: 2.666s
     CGroup: /system.slice/clickhouse-server.service
             â”œâ”€584 clickhouse-watchdog        --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid
             â””â”€689 /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid

Jul 11 06:52:20 ntopng systemd[1]: Started ClickHouse Server (analytic DBMS for big data).
Jul 11 06:52:22 ntopng clickhouse-server[584]: Processing configuration file '/etc/clickhouse-server/config.xml'.
Jul 11 06:52:22 ntopng clickhouse-server[584]: Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Jul 11 06:52:22 ntopng clickhouse-server[584]: Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Jul 11 06:52:26 ntopng clickhouse-server[689]: Processing configuration file '/etc/clickhouse-server/config.xml'.
Jul 11 06:52:26 ntopng clickhouse-server[689]: Saved preprocessed configuration to '/var/lib/clickhouse/preprocessed_configs/config.xml'.
Jul 11 06:52:26 ntopng clickhouse-server[689]: Processing configuration file '/etc/clickhouse-server/users.xml'.
Jul 11 06:52:26 ntopng clickhouse-server[689]: Merging configuration file '/etc/clickhouse-server/users.d/default-password.xml'.
Jul 11 06:52:26 ntopng clickhouse-server[689]: Saved preprocessed configuration to '/var/lib/clickhouse/preprocessed_configs/users.xml'.
root@ntopng:~# systemctl status nprobe
â— nprobe.service - nprobe extensible NetFlow v5/v9/IPFIX probe/collector
     Loaded: loaded (/etc/systemd/system/nprobe.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-07-11 06:52:24 EDT; 24s ago
    Process: 723 ExecStartPre=/bin/sh -c /bin/echo "$(/bin/date) nprobe StartPre" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
    Process: 732 ExecStartPre=/bin/sh -c /bin/sed "/^-g.*$\|^-G.*\|^--daemon-mode.*\|^--pid-file.*/s/^/#/" /etc/nprobe/nprobe.conf > /run/nprobe.conf (code=exited, status=0/SUCCESS)
    Process: 739 ExecStartPost=/bin/sh -c /bin/echo "$(/bin/date) nprobe StartPost" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
   Main PID: 737 (nprobe@2055)
      Tasks: 7 (limit: 9506)
     Memory: 44.1M
        CPU: 245ms
     CGroup: /system.slice/nprobe.service
             â””â”€737 /usr/bin/nprobe /run/nprobe.conf

Jul 11 06:52:26 ntopng nprobe[737]: 11/Jul/2022 06:52:26 [nprobe.c:11380] Not capturing packet from interface (collector mode)
Jul 11 06:52:26 ntopng nprobe[737]: 11/Jul/2022 06:52:26 [util.c:5036] Enlarged socket buffer [echo 8388608 > /proc/sys/net/core/rmem_max]
Jul 11 06:52:26 ntopng nprobe[737]: 11/Jul/2022 06:52:26 [util.c:5091] nProbe changed user to 'nprobe'
Jul 11 06:52:26 ntopng nprobe[737]: 11/Jul/2022 06:52:26 [collect.c:246] Flow collector listening on port 2055 (IPv4/v6)
Jul 11 06:52:26 ntopng nprobe[737]: 11/Jul/2022 06:52:26 [export.c:559] Using TLV as serialization format
Jul 11 06:52:26 ntopng nprobe[737]: 11/Jul/2022 06:52:26 [nprobe.c:11672] nProbe started successfully
Jul 11 06:52:26 ntopng nprobe[737]: 11/Jul/2022 06:52:26 [collect.c:3288] Collecting flows from 172.17.0.1 [total: 1/128]
Jul 11 06:52:27 ntopng nprobe[737]: 11/Jul/2022 06:52:27 [collect.c:3288] Collecting flows from 172.17.1.1 [total: 2/128]
Jul 11 06:52:46 ntopng nprobe[737]: 11/Jul/2022 06:52:46 [collect.c:1782] Added new flow template definition [id=259][flow_version=9][netflow_device=172.17.0.1:0][observation_domain_id=0][total=1]
Jul 11 06:52:46 ntopng nprobe[737]: 11/Jul/2022 06:52:46 [collect.c:1782] Added new flow template definition [id=257][flow_version=9][netflow_device=172.17.0.1:0][observation_domain_id=0][total=2]
root@ntopng:~# systemctl status ntopng
â— ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
     Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-07-11 06:52:31 EDT; 22s ago
    Process: 1070 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exited, status=0/SUCCESS)
    Process: 1084 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
    Process: 1086 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (code=exited, status=0/SUCCESS)
    Process: 1088 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /run/ntopng.conf (code=exited, status=0/SUCCESS)
   Main PID: 1090 (6/flow_checks)
      Tasks: 23 (limit: 9506)
     Memory: 298.2M
        CPU: 4.647s
     CGroup: /system.slice/ntopng.service
             â””â”€1090 /usr/bin/ntopng /run/ntopng.conf

Jul 11 06:52:38 ntopng ntopng[1090]: 11/Jul/2022 06:52:38 [startup.lua:120] [lists_utils.lua:739] Category Lists (4133 hosts, 2434 IPs, 0 JA3) loaded in 0 sec
Jul 11 06:52:38 ntopng ntopng[1090]: 11/Jul/2022 06:52:38 [startup.lua:124] Initializing device polices...
Jul 11 06:52:38 ntopng ntopng[1090]: 11/Jul/2022 06:52:38 [startup.lua:140] Initializing alerts...
Jul 11 06:52:38 ntopng ntopng[1090]: 11/Jul/2022 06:52:38 [startup.lua:149] Initializing timeseries...
Jul 11 06:52:38 ntopng ntopng[1090]: 11/Jul/2022 06:52:38 [startup.lua:207] Importing ClickHouse dumps...
Jul 11 06:52:38 ntopng ntopng[1090]: 11/Jul/2022 06:52:38 [startup.lua:212] Fetching latest ntop blog posts...
Jul 11 06:52:38 ntopng ntopng[1090]: 11/Jul/2022 06:52:38 [startup.lua:216] Completed startup.lua
Jul 11 06:52:38 ntopng ntopng[1090]: 11/Jul/2022 06:52:38 [PeriodicActivities.cpp:167] Found 10 activities
Jul 11 06:52:38 ntopng ntopng[1090]: 11/Jul/2022 06:52:38 [NetworkInterface.cpp:3242] Started packet polling on interface tcp://*:5556c [id: 6]...
Jul 11 06:52:39 ntopng ntopng[1090]: 11/Jul/2022 06:52:39 [ZMQCollectorInterface.cpp:268] Collecting flows on tcp://*:5556c
root@ntopng:~# 

But on the GUI no traffic seem to be processed, on "Traffic Dashboard" view the "tcp://*:5556c: Top Applications (Realtime)" shows "No Data Available".

Here is the versions that are running : 

Version	ntopng Enterprise L v.5.4.220711 rev.18063 (Debian GNU/Linux 11 (bullseye)) |
Platform	Debian 11.0 [x86_64][Debian GNU/Linux 11 (bullseye)] - 64 bit
Local Timezone	America/New_York
nDPI 	4.4.0-3739-2c5258b1
cURL 	7.74.0
Twitter Bootstrap 	5.0
Font Awesome 	5.11.2
RRDtool 	1.7.2
Redis Server 	6.0.16
Mongoose web server 	3.7
Lua 	Lua 5.4.3
ØMQ 	4.3.4
GeoLite 	1.5.2
Includes support for MaxMind and DB-IP Geolocation databases.
Data-Driven Documents (d3js) 	2.9.1 / 3.0

Regards

**Comment by lvalero** [comment]
![nprobe_1](https://user-images.githubusercontent.com/9340748/178255859-c6cb8c16-2ccf-4a16-922f-ac6d2f19173e.JPG)
![nprobe_2](https://user-images.githubusercontent.com/9340748/178255863-3b8e071d-45b3-4ee1-a6ef-fada4aee4620.JPG)

**Comment by MatteoBiscosi** [comment]
Hi @lvalero could you please run both ntopng and nprobe in foreground and report the output? 
to run them in foreground please stop both services and then run 
`sudo nprobe /etc/nprobe/nprobe.conf`
`sudo ntopng /etc/ntopng/ntopng.conf`
or whatever conf file you have and then send me the output (to understand if there is some problem)

**Comment by lvalero** [comment]
1/ stop processe
root@ntopng:/etc/ntopng# systemctl stop nprobe
root@ntopng:/etc/ntopng# systemctl stop ntopng

2/ run in foreground

root@ntopng:~# nprobe /etc/nprobe/nprobe.conf
11/Jul/2022 08:23:13 [nprobe.c:5476] Reading configuration file /etc/nprobe/nprobe.conf
11/Jul/2022 08:23:13 [plugin.c:178] No plugins found in ./plugins
11/Jul/2022 08:23:13 [plugin.c:186] Loading 23 plugins [.so] from /usr/lib/nprobe/plugins
11/Jul/2022 08:23:13 [nprobe.c:5245] Valid nProbe Enterprise L license found
11/Jul/2022 08:23:13 [nprobe.c:5793] Disabling flow cache during collection
11/Jul/2022 08:23:13 [nprobe.c:7445] WARNING: The output interfaceId is set to 0: did you forget to use -Q perhaps ?
11/Jul/2022 08:23:13 [nprobe.c:7448] WARNING: The input interfaceId is set to 0: did you forget to use -u perhaps ?
11/Jul/2022 08:23:13 [nprobe.c:7469] Using ZMQ sourceId 349270551
11/Jul/2022 08:23:13 [nprobe.c:7537] Flow cache is disabled in flow collection mode
11/Jul/2022 08:23:13 [nprobe.c:7540] Welcome to nProbe v.10.0.220711 for x86_64-pc-linux-gnu with native PF_RING acceleration
11/Jul/2022 08:23:13 [nprobe.c:7558] Enterprise L Edition running on Debian GNU/Linux 11 (bullseye)
11/Jul/2022 08:23:13 [nprobe.c:7559] Current limits [32 ZMQ exporters][128 collector devices]
11/Jul/2022 08:23:13 [nprobe.c:7570] SystemId: L68.......24--OL
11/Jul/2022 08:23:13 [nprobe.c:7643] Sample rate [packet: 1][flow collection/export: 1/1]
11/Jul/2022 08:23:13 [nprobe.c:9619] Using template @NTOPNG@
11/Jul/2022 08:23:13 [nprobe.c:9621] Using NetFlow Packet Payload Len: 1472
11/Jul/2022 08:23:13 [nprobe.c:9510] @NTOPNG@ expanded to " %IN_SRC_MAC %OUT_DST_MAC %INPUT_SNMP %OUTPUT_SNMP %SRC_VLAN %IPV4_SRC_ADDR %IPV4_DST_ADDR %L4_SRC_PORT %L4_DST_PORT %IPV6_SRC_ADDR %IPV6_DST_ADDR %IP_PROTOCOL_VERSION %PROTOCOL %L7_PROTO %L7_CONFIDENCE %IN_BYTES %IN_PKTS %OUT_BYTES %OUT_PKTS %FIRST_SWITCHED %LAST_SWITCHED %CLIENT_TCP_FLAGS %SERVER_TCP_FLAGS %L7_PROTO_RISK %L7_RISK_SCORE %EXPORTER_IPV4_ADDRESS %DIRECTION %SAMPLING_INTERVAL %TOTAL_FLOWS_EXP %NPROBE_IPV4_ADDRESS %POST_NAT_SRC_IPV4_ADDR %POST_NAT_DST_IPV4_ADDR %POST_NAPT_SRC_TRANSPORT_PORT %POST_NAPT_DST_TRANSPORT_PORT "
11/Jul/2022 08:23:13 [template.c:3491] WARNING: Unable to locate template 'NPROBE_IPV6_ADDRESS'. Discarded.
11/Jul/2022 08:23:13 [template.c:3491] WARNING: Unable to locate template 'NPROBE_IPV6_ADDRESS'. Discarded.
11/Jul/2022 08:23:13 [plugin.c:1196] 0 plugin(s) enabled
11/Jul/2022 08:23:13 [nprobe.c:10154] Each flow is 132 bytes long
11/Jul/2022 08:23:13 [nprobe.c:10155] The # flows per packet has been set to 10
11/Jul/2022 08:23:13 [nprobe.c:10158] IP TOS is ignored
11/Jul/2022 08:23:13 [nprobe.c:10926] Flow export type (-T): bidirectional flows
11/Jul/2022 08:23:13 [nprobe.c:10972] Collecting flows in ZMQ pass-through mode
11/Jul/2022 08:23:13 [nprobe.c:11131] Flows ASs will not be computed (no GeoDB files loaded with --as-list)
11/Jul/2022 08:23:13 [nprobe.c:11163] Flows will be exported in NetFlow 9 format
11/Jul/2022 08:23:13 [nprobe.c:11206] Learning the public IP address.. Disable it with --disable-startup-checks
11/Jul/2022 08:23:13 [nprobe.c:11380] Not capturing packet from interface (collector mode)
11/Jul/2022 08:23:13 [util.c:6196] Initializing ZMQ as client
11/Jul/2022 08:23:13 [util.c:6269] Exporting flows towards ZMQ endpoint tcp://127.0.0.1:5556

root@ntopng:~# ntopng /etc/ntopng/ntopng.conf
11/Jul/2022 08:23:32 [Redis.cpp:151] Successfully connected to redis 127.0.0.1:6379@0
11/Jul/2022 08:23:32 [Redis.cpp:151] Successfully connected to redis 127.0.0.1:6379@0
11/Jul/2022 08:23:32 [NtopPro.cpp:315] [LICENSE] Reading license from /etc/ntopng.license
11/Jul/2022 08:23:32 [NtopPro.cpp:486] [LICENSE] /etc/ntopng.license: found valid Enterprise L license
11/Jul/2022 08:23:33 [Ntop.cpp:2589] Registered interface tcp://*:5556c [id: 6]
11/Jul/2022 08:23:33 [main.cpp:337] PID stored in file /var/run/ntopng.pid
11/Jul/2022 08:23:33 [Geolocation.cpp:149] Loaded database dbip-city-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip-city-lite.mmdb][ip_version: 6]
11/Jul/2022 08:23:33 [Geolocation.cpp:149] Loaded database dbip-asn-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip-asn-lite.mmdb][ip_version: 6]
11/Jul/2022 08:23:33 [Geolocation.cpp:95] Using geolocation provided by DB-IP (https://db-ip.com)
11/Jul/2022 08:23:33 [HTTPserver.cpp:1408] Found TLS certificate /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem
11/Jul/2022 08:23:33 [HTTPserver.cpp:1683] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
11/Jul/2022 08:23:33 [HTTPserver.cpp:1686] HTTP server listening on 3000
11/Jul/2022 08:23:33 [Utils.cpp:784] User changed to ntopng
11/Jul/2022 08:23:33 [NetworkInterface.cpp:3126] Started flow dump loop on interface tcp://*:5556c [id: 6]...
11/Jul/2022 08:23:33 [MySQLDB.cpp:832] Successfully connected to ClickHouse [default@127.0.0.1:9004][dbname: ] for interface tcp://*:5556c
11/Jul/2022 08:23:33 [ClickHouseFlowDB.cpp:65] [ClickHouse] Creating Flow DB
11/Jul/2022 08:23:33 [ClickHouseFlowDB.cpp:38] ClickHouse will dump into /var/lib/ntopng/tmp/clickhouse
11/Jul/2022 08:23:33 [NetworkInterface.cpp:3052] Started flow user script hooks loop on interface tcp://*:5556c [id: 6]...
11/Jul/2022 08:23:33 [NetworkInterface.cpp:3089] Started host user script hooks loop on interface tcp://*:5556c [id: 6]...
11/Jul/2022 08:23:33 [main.cpp:407] Working directory: /var/lib/ntopng
11/Jul/2022 08:23:33 [main.cpp:409] Scripts/HTML pages directory: /usr/share/ntopng
11/Jul/2022 08:23:33 [Ntop.cpp:466] Welcome to ntopng x86_64 v.5.4.220711 - (C) 1998-22 ntop.org
11/Jul/2022 08:23:33 [Ntop.cpp:476] Built on Debian GNU/Linux 11 (bullseye)
11/Jul/2022 08:23:33 [NtopPro.cpp:776] [LICENSE] System Id:     L68A2C6E176086A8F--U68A2C6E16CDD7324--OL
11/Jul/2022 08:23:33 [NtopPro.cpp:777] [LICENSE] Edition:       Enterprise L
11/Jul/2022 08:23:33 [NtopPro.cpp:778] [LICENSE] License Type:  Permanent License
11/Jul/2022 08:23:33 [NtopPro.cpp:787] [LICENSE] License:       ZLaeLUZjXdlO81ORvogeM28LAy7uJPGVgG5aDf2Y7wIFFK4GzLKw1FbBElzximOKeGhfj
.....
11/Jul/2022 08:23:33 [NtopPro.cpp:792] [LICENSE] License Hash:  E58280EBA62........
11/Jul/2022 08:23:33 [NtopPro.cpp:803] [LICENSE] Maintenance:   Until Fri Apr 21 09:21:17 2023 [284 days left]
11/Jul/2022 08:23:33 [MySQLDB.cpp:832] Successfully connected to ClickHouse [default@127.0.0.1:9004][dbname: ] for interface __system__
11/Jul/2022 08:23:34 [PeriodicActivities.cpp:109] Started periodic activities loop...
11/Jul/2022 08:23:34 [startup.lua:35] Processing startup.lua: please hold on...
11/Jul/2022 08:23:37 [startup.lua:120] [lists_utils.lua:811] Refreshing category lists...
11/Jul/2022 08:23:38 [startup.lua:120] [lists_utils.lua:739] Category Lists (4133 hosts, 2437 IPs, 0 JA3) loaded in 1 sec
11/Jul/2022 08:23:38 [startup.lua:124] Initializing device polices...
11/Jul/2022 08:23:38 [startup.lua:140] Initializing alerts...
11/Jul/2022 08:23:38 [startup.lua:149] Initializing timeseries...
11/Jul/2022 08:23:38 [startup.lua:207] Importing ClickHouse dumps...
11/Jul/2022 08:23:38 [startup.lua:212] Fetching latest ntop blog posts...
11/Jul/2022 08:23:38 [startup.lua:216] Completed startup.lua
11/Jul/2022 08:23:38 [PeriodicActivities.cpp:167] Found 10 activities
11/Jul/2022 08:23:38 [NetworkInterface.cpp:3242] Started packet polling on interface tcp://*:5556c [id: 6]...
11/Jul/2022 08:23:39 [ZMQCollectorInterface.cpp:268] Collecting flows on tcp://*:5556c

**Comment by MatteoBiscosi** [comment]
Hi @lvalero a new version of ntopng / nprobe stables should be available soon, please update them and see if the issue persists (check a couple of minutes after starting both services). if it persists please drop an email at `biscosi at ntop.org` with your configuration files. Sorry to trouble you but in my case everything seems working correctly

**Comment by lvalero** [comment]
Here is a message after the upgrade (new messages seen today July 11) : 

root@ntopng:/home/zeta# head /var/log/syslog
Jul 10 00:00:10 ntopng systemd[1]: logrotate.service: Succeeded.
Jul 10 00:00:10 ntopng systemd[1]: Finished Rotate log files.
Jul 10 00:00:10 ntopng systemd[1]: man-db.service: Succeeded.
Jul 10 00:00:10 ntopng systemd[1]: Finished Daily man-db regeneration.
Jul 10 00:01:01 ntopng CRON[572659]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)
Jul 10 00:02:01 ntopng CRON[572740]: (root) CMD (/usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests)

root@ntopng:/home/zeta# fgrep 'Drops queue too' /var/log/syslog | more
Jul 11 06:28:24 ntopng cento[725386]: 11/Jul/2022 06:28:24 [FlowExporter.cpp:132] [lo] Flow Export Queue Len [0 tot queued][0/0 IPv4/v6][Drops queue too long 0/0 IPv4/v6][0/0 tot exporte
d/dropped flows][0/0 exported/dropped fps]
Jul 11 06:28:25 ntopng cento[725386]: 11/Jul/2022 06:28:25 [FlowExporter.cpp:132] [lo] Flow Export Queue Len [0 tot queued][0/0 IPv4/v6][Drops queue too long 0/0 IPv4/v6][0/0 tot exporte
d/dropped flows][0/0 exported/dropped fps]
Jul 11 06:28:26 ntopng cento[725386]: 11/Jul/2022 06:28:26 [FlowExporter.cpp:132] [lo] Flow Export Queue Len [0 tot queued][0/0 IPv4/v6][Drops queue too long 0/0 IPv4/v6][0/0 tot exporte
d/dropped flows][0/0 exported/dropped fps]
Jul 11 06:28:27 ntopng cento[725386]: 11/Jul/2022 06:28:27 [FlowExporter.cpp:132] [lo] Flow Export Queue Len [0 tot queued][0/0 IPv4/v6][Drops queue too long 0/0 IPv4/v6][0/0 tot exporte
d/dropped flows][0/0 exported/dropped fps]
Jul 11 06:28:28 ntopng cento[725386]: 11/Jul/2022 06:28:28 [FlowExporter.cpp:132] [lo] Flow Export Queue Len [0 tot queued][0/0 IPv4/v6][Drops queue too long 0/0 IPv4/v6][0/0 tot exporte
d/dropped flows][0/0 exported/dropped fps]

**Comment by MatteoBiscosi** [comment]
Hi @lvalero, I think the problem is the configuration.
You are capturing by ntopng interface `127.0.0.1:5556c` (the `c` is used for Observation Points) but you are not sending from nProbe to ntopng using Observation Points (if you look at your nProbe config file, no `-E` option is configured); so please try to collect from interface `127.0.0.1:5556` instead of the `127.0.0.1:5556c` (or add an Observation Point to nProbe config file) and let me know.
(you can find doc regarding Observation Points here https://www.ntop.org/guides/ntopng/using_with_other_tools/nprobe.html)

**Comment by lvalero** [comment]
Hello Matteo,

Here is my new working config (now it is working)  :

***@***.***:/etc/nprobe# cat /etc/ntopng/ntopng.conf | grep -v '#'
-i=tcp://127.0.0.1:5556
-m="10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,132.207.0.0/16"
-G=/var/run/ntopng.pid
-F="clickhouse;127.0.0.1;ntopng;default;<MYPWD>"
-x=524288
-X=2097152

***@***.***:/etc/nprobe# cat nprobe.conf | fgrep -v '#'
-i=none
--collector-port=2055
--zmq=tcp://*:5556
-n=none
***@***.***@
-G=/var/run/nprobe.pid

I do not know why it worked with the config before the upgrade.

Regards,
Lionel.

**Comment by MatteoBiscosi** [comment]
Hi @lvalero glad to know that now is working correctly. Please reopen the issue if the same problem is going to appear again
