### ISSUE TITLE
Ntop not start after autoupdate.

### ISSUE THREAD

**Issue by Eugene-Prokhorenko** [ntop/ntopng#6777]
**Environment**:
* OS name: [e.g. Ubuntu] Ubuntu
* OS version: [e.g. 18.04] 18.04.6
* Architecture: [e.g. amd64] AMD64
* ntopng version/revision: [e.g. 5.1.211223] 5.5.220708

**What happened**:
site become stuck:

No internetThere is something wrong with the proxy server, or the address is incorrect.
Try:

Contacting the system admin
[Checking the proxy address](chrome-error://chromewebdata/#buttons)
ERR_PROXY_CONNECTION_FAILED
**What did you expect to happen?**

**How did you reproduce it?**

all the time the same error message

**Debug Information**:

   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
   Active: activating (start-pre) since Mon 2022-07-11 16:00:55 +04; 12ms ago
  Process: 2354 ExecStopPost=/bin/rm -rf /run/ntopng.conf /run/ntopng.conf.raw /run/ntopng.pid (code=exited, status=0/SUCCESS)
  Process: 2198 ExecStart=/usr/bin/ntopng /run/ntopng.conf (code=exited, status=1/FAILURE)
  Process: 2195 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /run/ntopng.conf 
(code=exited, status=0/SUCCESS)
  Process: 2193 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (code=exited, status=0/SU
CCESS)
  Process: 2188 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
 Main PID: 2198 (code=exited, status=1/FAILURE); Control PID: 3159 (sh)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/ntopng.service
           ├─3159 /bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true
           └─3166 bash /usr/bin/ntopng-utils-manage-config -a check-restore

Jul 11 16:00:55 asnet-monitoring systemd[1]: ntopng.service: Scheduled restart job, restart counter is at 404.
Jul 11 16:00:55 asnet-monitoring systemd[1]: Stopped ntopng high-speed web-based traffic monitoring and analysis tool.
Jul 11 16:00:55 asnet-monitoring systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...

**Comment by cardigliano** [comment]
@Eugene-Prokhorenko please provide the output of:
- systemctl is-enabled ntopng
- systemctl status ntopng
- journalctl -u ntopng (in a log file)

**Comment by Eugene-Prokhorenko** [comment]
I inserted needed data into initial part of the list of needed info

**Comment by Eugene-Prokhorenko** [comment]
July 11, 2022 5:27 PM, "Alfredo Cardigliano" ***@***.***> wrote:

> @Eugene-Prokhorenko please provide the output of:
> 
> * systemctl is-enabled ntopng
> * systemctl status ntopng
> * journalctl -u ntopng (in a log file)
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>

systemctl is-enabled ntopng 
enabled
systemctl status ntopng
enabled
journalctl -u ntopng 
[jour.txt](https://github.com/ntop/ntopng/files/9086903/jour.txt)

This one?

**Comment by lucaderi** [comment]
This is your problem

Jul 11 21:10:12 asnet-monitoring ntopng[7228]: [Redis.cpp:93] ERROR: Connection error [Connection refused]
Jul 11 21:10:12 asnet-monitoring ntopng[7228]: 11/Jul/2022 21:10:12 [Redis.cpp:93] ERROR: Connection error [Connection refused]
Jul 11 21:10:13 asnet-monitoring ntopng[7228]: 11/Jul/2022 21:10:13 [Redis.cpp:77] Redis has disconnected, reconnecting [remaining attempts: 14]
Jul 11 21:10:13 asnet-monitoring ntopng[7228]: [Redis.cpp:93] ERROR: Connection error [Connection refused]

Please fix it and then repeat your tests

**Comment by lucaderi** [comment]
@Eugene-Prokhorenko Did you fix this redis issue?

**Comment by Eugene-Prokhorenko** [comment]
no way. I tried install, remove, do manual editing, comparing two installation. Now I'm writing to authors. Will inform you.

**Comment by cardigliano** [comment]
@Eugene-Prokhorenko since this seems to be a redis related issue, I am closing this, please reopen in case some action is required on our side. Thank you.
