### ISSUE TITLE
cp: cannot stat '/root/dat_files/dbip-city-lite-*.mmdb': No such file or directory

### ISSUE THREAD

**Issue by skore-onclave** [ntop/ntopng#6778]
**Environment**:
* OS name: [Ubuntu]
* OS version: [18.04]
* Architecture: [amd64]
* ntopng version/revision: [5.5.220712]

**What happened**:
Debian package compilation from source fails with error  `cp: cannot stat '/root/dat_files/dbip-city-lite-*.mmdb': No such file or directory` at `[ntopng-data]` step of make

**What did you expect to happen?**
Build for a core package of Ntopng succeeds but `[ntopng-data]`  which I beleive should not

**How did you reproduce it?**
Install all the Prerequisites for Compilation from this link https://github.com/ntop/ntopng/blob/dev/doc/README.compilation and then follow the below steps for compiling  the Debian package from the source,
```
git clone https://github.com/ntop/nDPI.git
cd nDPI
./autogen.sh
./configure
make
cd ..
git clone https://github.com/ntop/ntopng.git
cd ntopng
./autogen.sh
./configure
make

```
**Debug Information**:
```
if test -e "./debian"; then  /bin/rm -f debian; fi
ln -s ./debian.ntopng-data ./debian
\rm -rf ./usr ./etc/ ./debian/ntopng-data
\mkdir -p /codebuild/output/src273072618/src/github.com/OnclaveNetworks/distributed-control-plane/ntopng/ntopng/packages/ubuntu/../../packages/ubuntu/usr/share/ntopng/httpdocs/geoip ./debian/ntopng-data
cp /root/dat_files/dbip-city-lite-*.mmdb /codebuild/output/src273072618/src/github.com/OnclaveNetworks/distributed-control-plane/ntopng/ntopng/packages/ubuntu/../../packages/ubuntu/usr/share/ntopng/httpdocs/geoip/dbip-city-lite.mmdb
cp: cannot stat '/root/dat_files/dbip-city-lite-*.mmdb': No such file or directory
Makefile:86: recipe for target 'ntopng-data' failed
make: *** [ntopng-data] Error 1
```

**Comment by cardigliano** [comment]
@skore-onclave please note that the ntopng-data package is supposed to contain MMDB database files used for Geo Localization, please download them and place under /root/dat_files/dbip-city-lite-*.mmdb (note that you can download the Lite version of the database which is free from https://db-ip.com/db/)

**Comment by skore-onclave** [comment]
@cardigliano Thanks for quick reply. I downloaded all the three lite versions of DB files, my question is do I need to create `dat_files` in root explicitly put the files under it? Or just i need to put DB files under `ntopng` root directory and build process takes care of creating `dat_files` folder and moving the files to `dat_files` from `ntpong` base directory.

**Comment by cardigliano** [comment]
You need to manually create the dat_files/ folder in your home, and place the mmdb files inside, example
ls dat_files
dbip-asn-lite-2022-07.mmdb  dbip-city-lite-2022-07.mmdb  dbip-country-lite-2022-07.mmdb
