### ISSUE TITLE
How to apply mysql mysql patch during build process

### ISSUE THREAD

**Issue by skore-onclave** [ntop/ntopng#6780]
**Environment**:
* OS name: [Ubuntu]
* OS version: [18.04]
* Architecture: [amd64]
* ntopng version/revision: [5.4]

**What happened**:
I'm building ntopng Debian package from source and during this process I want to apply some custom MySQL patch. 
I thought of using **patch -p1 < patchfile** but I'm not sure at what step of the build process I need to execute this command. Or I need to apply this patch to the running state of the Ntopng?

**Comment by cardigliano** [comment]
@skore-onclave not sure about what patch you need to apply, but I would do that on the source code before running the build process
