### ISSUE TITLE
[Error] Config file not found Starting redis-server: redis-server.

### ISSUE THREAD

**Issue by mariushosting** [ntop/ntopng#6784]
Stable ntopng Docker Version I get this error in the log and ntopng won't start

15/Jul/2022 13:31:05 [Prefs.cpp:1880] WARNING: Config file  not found
Starting redis-server: redis-server.

This is what I use and perfectly works since yesterday:

docker run -d --name=ntop \
-p 3000:3000 \
-v /volume1/docker/ntop:/etc/ntopng.license:ro \
--net=host \
--restart always \
ntop/ntopng:stable

**Comment by cardigliano** [comment]
@mariushosting please provide a configuration file or options via command line

**Comment by mariushosting** [comment]
is there any config default file somewhere?

**Comment by cardigliano** [comment]
ntopng installs some sample files under /etc/ntopng/, or you can just create an empty text file, and add one or multiple interfaces to monitor. Example:

-i=eno1
-i=eno2
