### ISSUE TITLE
ntop-ng does not detect a USB-C interface 

### ISSUE THREAD

**Issue by sergico** [ntop/ntopng#6787]
**Environment**:
* OS name: Ubuntu 
* OS version: 22.04 64b
* Architecture: amd64
* ntopng version/revision: ntopng Community v.5.4.220714

**What happened**:
I'm experimenting with ntop on my laptop. Today I connected the laptop to the docking station I have in the office
The docking station is connected to the laptop via USB-C; the docking station is connected to the switch that give me access to the company network.
Please see below the output of the ip link command
```
1: lo: <LOOPBACK,PROMISC,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp2s0: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 00:2b:67:e9:6a:54 brd ff:ff:ff:ff:ff:ff
3: enx64c901ea6876: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 64:c9:01:ea:68:76 brd ff:ff:ff:ff:ff:ff
4: wlp3s0: <NO-CARRIER,BROADCAST,MULTICAST,PROMISC,UP> mtu 1500 qdisc noqueue state DOWN mode DORMANT group default qlen 1000
    link/ether d6:b6:e9:bb:4f:cc brd ff:ff:ff:ff:ff:ff permaddr c8:b2:9b:fc:44:dc
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,PROMISC,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default 
    link/ether 02:42:7d:5b:e3:06 brd ff:ff:ff:ff:ff:ff
6: vboxnet0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 0a:00:27:00:00:00 brd ff:ff:ff:ff:ff:ff
7: vboxnet1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 0a:00:27:00:00:01 brd ff:ff:ff:ff:ff:ff
8: vboxnet2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 0a:00:27:00:00:02 brd ff:ff:ff:ff:ff:ff
9: vboxnet3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 0a:00:27:00:00:03 brd ff:ff:ff:ff:ff:ff
10: vboxnet4: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 0a:00:27:00:00:04 brd ff:ff:ff:ff:ff:ff
```

actually the interface `enx64c901ea6876` that is the one exposed by the docking station, is not listed into the interface dropdown menu.

![image](https://user-images.githubusercontent.com/16519520/179552923-9a55dbcc-9691-4d0b-bbea-05d774609f55.png)

Please let me know if you need further details

Best Regards
Sergio Borghese

**Comment by martinscheu** [comment]
@sergico I had similar problem in the past, interface name too long. I renamed the interface and added it in the config file. Maybe you can try it?

**Comment by cardigliano** [comment]
I pushed a fix to handle long interface names like the one reported. Please wait for the next package update later today and check it.

**Comment by martinscheu** [comment]
great, thanks @cardigliano !

**Comment by sergico** [comment]
> @sergico I had similar problem in the past, interface name too long. I renamed the interface and added it in the config file. Maybe you can try it?

Hi, thanks for the suggestion. Will try it and let you know asap

**Comment by sergico** [comment]
I confirm that renaming the interface solved the issue
here the new `ip link` output

```
1: lo: <LOOPBACK,PROMISC,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp2s0: <NO-CARRIER,BROADCAST,MULTICAST,PROMISC,UP> mtu 1500 qdisc fq_codel state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:2b:67:e9:6a:54 brd ff:ff:ff:ff:ff:ff
3: usbc0: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 64:c9:01:ea:68:76 brd ff:ff:ff:ff:ff:ff
4: wlp3s0: <NO-CARRIER,BROADCAST,MULTICAST,PROMISC,UP> mtu 1500 qdisc noqueue state DOWN mode DORMANT group default qlen 1000
    link/ether ce:cb:aa:6b:f5:f6 brd ff:ff:ff:ff:ff:ff permaddr c8:b2:9b:fc:44:dc
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,PROMISC,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default 
    link/ether 02:42:67:80:3e:f2 brd ff:ff:ff:ff:ff:ff
```

I renamed the iface `enx64c901ea6876` to `usbc0` and now it is corretly displayed into the interface list drop-down menu
thanks for the support

**Comment by cardigliano** [comment]
If you update the software, also the old interface name enx64c901ea6876 should be recognized. Thank you.
