### ISSUE TITLE
'flow exporter' column is missing in historical flows

### ISSUE THREAD

**Issue by 61swong** [ntop/ntopng#6788]
**Environment**:
* OS name: RHEL
* OS version: 7.9
* Architecture: x86_64
* ntopng version/revision: v5.5.220718

**What happened**:
'flow exporter' column is missing in historical flows when 'flow exporter' is selected in 'show column' list.

**What did you expect to happen?**
I expect the 'flow exporter' column is shown in historical flows when 'flow exporter' is selected in 'show column' list.

**How did you reproduce it?**
Any time.

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @61swong thanks for your report, the issue should now be fixed. A new build should be available in 4/5 hours at most

**Comment by 61swong** [comment]
Hi @MatteoBiscosi thanks for the fix but I found the column disappeared when I clicked on the column header to sort the rows. The column disappeared too if I set a filter with one of the exporter's IP address.

**Comment by MatteoBiscosi** [comment]
Hi @61swong unfortunately i don't think it's going to disappear both jump on the "+" section.
![Screenshot from 2022-07-21 11-02-55](https://user-images.githubusercontent.com/49585191/180175157-2c355abb-b6c8-4c12-8e67-b62a77979f52.png)
I suggest on taking a look at it. We are not able to fix this issue at the current time (it's a problem of a library we use).
Please let me know

**Comment by 61swong** [comment]
Hi @MatteoBiscosi thanks for your update. I figured out my screen isn't wide enough to show the selected columns and therefore the 'flow exporter' column seemed to be hidden. I zoom-out and found it now and be able to sort it by clicking the column header 'flow exporter' or filter with the flow exporter ip. Sorry for misleading you by my last test result.
