### ISSUE TITLE
Error during search

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6789]
Searching a MAC (e.g. D2:39:EA:2D:90:F9) with the current version produces a bug
![Screen Shot 2022-07-20 at 22 54 09](https://user-images.githubusercontent.com/4493366/180080271-a2aa98fe-28b5-42f9-ba7e-8e8caa84ad29.png)

This happens when you enter a MAC that was not found and you type enter

**Comment by MatteoBiscosi** [comment]
Fixed pro repo

**Comment by lucaderi** [comment]
Ummmm
![Screen Shot 2022-07-21 at 23 09 08](https://user-images.githubusercontent.com/4493366/180315651-9b9af49a-f695-4e93-9c96-8e5bce49c7c7.png)
The error has been fixed but this result displays a message whose meaning is hard to understand. What do you wanna say that this MAC is not found or that there is a SNMP problem with it?

**Comment by lucaderi** [comment]
Verified as fixed
