### ISSUE TITLE
/usr/share/ntopng/scripts/lua/inc/menu.lua:25: attempt to index a nil value

### ISSUE THREAD

**Issue by Nosskirneh** [ntop/ntopng#679]
Hi!

I'm using Arch Linux. Just downloaded ntopng and started it with these parameters `sudo /usr/bin/ntopng -G /var/tmp/ntopng.pid -i 1 -w 3000 -n 1 -m 192.168.0.1/24 -S none -d /var/tmp/ntopng -q`

localhost:3000 starts and I login with the default settings. However, as soon as I'm logged in I'm greeted with `HTTP/1.1 500 Internal server error Content-Type: text/html Connection: close *warning symbol* Script "/usr/share/ntopng/scripts/lua/index.lua" returned an error:
/usr/share/ntopng/scripts/lua/inc/menu.lua:25: attempt to index a nil value`

The only thing I can find about this issue is [this](http://www.gossamer-threads.com/lists/ntop/users/41675), but the guy doesn't respond when someone tries to help.

The console output can be seen [here](http://pastebin.com/prcdmzU3).

Thankful for answers,
Nosskirneh

Edit: using version 2.4-7

**Comment by simonemainardi** [comment]
hi, are you sure that `1` is a valid interface name? Use `ntopng --help` to see all the valid interface names. Use those names with `-i`

Indeed, the code at `menu.lua:25` suggests me the interface name is not valid... menu should work insofar as the interface is valid

**Comment by Nosskirneh** [comment]
Yes, thank you, this was the issue. I thought the 'i' parameter was supposed to be given the number corresponding to the interface which can be seen by launching ntopng with -h (which, in my case 1 = enp0s25).

Thank you again!

**Comment by simonemainardi** [comment]
that's the way it works on windows. On linux you need the interface name! thanks for the feedback.
