### ISSUE TITLE
Invalid protocol page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6790]
starting ntopng -i dns.pcap

[dns.pcap.gz](https://github.com/ntop/ntopng/files/9162782/dns.pcap.gz)

and clicking on

![image](https://user-images.githubusercontent.com/4493366/180315288-fd2859ed-1ef7-4582-bbca-ac1a451c8d24.png)

we jump into an invalid page
![Screen Shot 2022-07-21 at 23 07 42](https://user-images.githubusercontent.com/4493366/180315435-5b265faf-0665-4c2f-950b-e38bdcd5a367.png)

**Comment by MatteoBiscosi** [comment]
Verified as fixed
