### ISSUE TITLE
Error message when searching for ip 

### ISSUE THREAD

**Issue by uber99** [ntop/ntopng#6791]
Security Issues:
- Please disclose security related issues privately to https://www.ntop.org/support/need-help-2/contact-us/

Pre-Submit Checklist: (check applicable sources for existing issues)
  - [Github Issues](https://github.com/ntop/ntopng/issues?q=is%3Aissue+label%3Abug+)
  - [FAQs](https://www.ntop.org/support/documentation/faq/)
-->
![Screenshot 2022-07-22 145147](https://user-images.githubusercontent.com/85244223/180453650-587058ae-b061-4b7c-bd01-cf3dc40ed314.jpg)

**Environment**:
* OS name: [e.g. Ubuntu]/root: /usr/local/bin/ntopng -V

Version:        5.0.220112 [Community build]

GIT rev:        :5.0.220112

* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]

**What happened**:

**How did you reproduce it?**

**Debug Information**:

**Comment by cardigliano** [comment]
@uber99 ntopng 5.0 is no longer supported, please update to 5.4 and reopen this issue if you are still able to reproduce it. Thank you.

**Comment by uber99** [comment]
> @uber99 ntopng 5.0 is no longer supported, please update to 5.4 and reopen this issue if you are still able to reproduce it. Thank you.

Thanks, I have ran this command up still wont update 
pkg add https://packages.ntop.org/FreeBSD/FreeBSD:11:amd64/latest/ntop-1.0.txz

is there command for updating versions ?

**Comment by cardigliano** [comment]
@uber99 FreeBSD 11 is no longer supported, please move to 12 or 13

https://packages.ntop.org/FreeBSD/
