### ISSUE TITLE
ntopng hangs on host_sites_update.dailyUpdateRedisHostSites

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#6792]
ntopng hangs during the startup for 10+ minutes while running pro/scripts/callbacks/system/startup.lua
which is calling host_sites_update.dailyUpdateRedisHostSites()
It is requested to check what is actually taking all this time.

**Comment by MatteoBiscosi** [comment]
Currently verified as fixed, please reopen if needed
