### ISSUE TITLE
Live Flows no longer functioning after update

### ISSUE THREAD

**Issue by ltkojak** [ntop/ntopng#6793]
**Environment**:
* OS name: FreeBSD
* OS version: 12.3
* Architecture: amd64
* ntopng version/revision: 5.5.220725

**What happened**:

After updating to new version - live flows no longer display.

**How did you reproduce it?**

Anytime I choose a specific host and go to LiveFlow it shows as blank.

When I navigate to Flows -> Live Flows the live flows do display.

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @ltkojak i tried on a FreeBSD 12 but everything seems working fine, which ntopng version do you have, community or not? and do you have some errors in the ntopng logs?

**Comment by ltkojak** [comment]
Hi @MatteoBiscosi 

My apologies for not including that in my initial post.

ntopng version/revision: 5.5.220726 CE (Installed new version today and problem still persists.)

The error I did see in the ntopng.log when attempting to go to a specific host's live flow:

26/Jul/2022 08:55:45 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/local/share/ntopng/scripts/lua/get_flows_data.lua][/usr/local/share/ntopng/scripts/lua/get_flows_data.lua:288: attempt to concatenate a nil value (local 'ifid')]
26/Jul/2022 08:55:45 [HTTPserver.cpp:717] [HTTP] redirect_to_error_page(b453c09ff96084777e3b1cc8b30564e9)

**Comment by MatteoBiscosi** [comment]
Hi @ltkojak a new build should be available in a couple of hours, please update after that and let me know

**Comment by ltkojak** [comment]
@MatteoBiscosi 

The new build 5.5.220727 appears to have resolved it.

Thanks!!!
