### ISSUE TITLE
Implement MAC appear/disappear check based on SNMP

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6797]
Similar to  "Unexpected Device Connected" that is based on network traffic and "MAC Detection" on SNMP, implement a similar check for SNMP only that
- uses the same MAC list used by https://github.com/ntop/ntopng/issues/6192
- the check is bound to ALL SNMP devices (i.e. the check is not per device but global)
- for all active MACs (found with the bridge MIB) an alert is triggered is a MAC that is NOT present in the whitelist is detected
- for a MAC that was previously detected as active in the bridge MIB, an alert is triggered when such MAC disappears.

**Comment by MatteoBiscosi** [comment]
Already implemented
