### ISSUE TITLE
Get name's device connected VPN in flows/history flows

### ISSUE THREAD

**Issue by AnhTuanNguyenn** [ntop/ntopng#6802]
**What would you like to add or change?**:
If not my mistake, can you please add feature for next version pls ?  

**Why do you and others need this?**:

I have someone remote working, they connected by VPN and when i check in live flows or history flows i can't see their device name, i can only see their ip now.

Hope you can go this point for next version :) 

regard,

**Comment by lucaderi** [comment]
This is implemented only with Fortinet VPN log integration
