### ISSUE TITLE
bad argument #4 to 'format' (number expected, got nil)

### ISSUE THREAD

**Issue by PaoGRodrigues** [ntop/ntopng#6806]
**Environment**:
* OS name: Raspbian
* OS version: GNU/Linux 10
* Architecture: armv7l
* ntopng version/revision: 5.3.220306

**What happened**:
I am trying to get the list of alerts via the Rest API. I followed [this documentation](https://www.ntop.org/guides/ntopng/api/rest/api_v2.html#request-format): 

<img width="656" alt="imagen" src="https://user-images.githubusercontent.com/22753936/182060422-b6a6251a-e4a9-4940-a2d3-cc4fd3d4008a.png">

When I run 
**curl -u admin:admin -H "Content-Type: application/json" -v http://xxx.xxx.xxx.xxx:port/lua/rest/v2/get/all/alerts/list.lua?ifid=2**

I get
**31/Jul/2022 23:05:46 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/rest/v2/get/all/alert/list.lua][...opng/scripts/lua/modules/alert_store/all_alert_store.lua:291: bad argument #4 to 'format' (number expected, got nil)]**

**Comment by MatteoBiscosi** [comment]
Hi @PaoGRodrigues, sorry the rest is right, but you miss the begin_epoch and end_epoch parameters. It's not reported in the documentation, I'm gonna fix that.
This is an example of the request you need:
`curl -u admin:admin -H "Content-Type: application/json" -v 'http://localhost:3000/lua/rest/v2/get/all/alert/list.lua?ifid=1&epoch_begin=1659336692&epoch_end=1659338492'`

**Comment by MatteoBiscosi** [comment]
A new version of the documentation should be updated and available soon 
![Screenshot from 2022-08-01 09-35-48](https://user-images.githubusercontent.com/49585191/182097677-32b9613e-322d-46fa-a62d-50f82be7a6ae.png)

**Comment by PaoGRodrigues** [comment]
Thanks for your answer @MatteoBiscosi.
