### ISSUE TITLE
Incorrect traffic values

### ISSUE THREAD

**Issue by dan2716430** [ntop/ntopng#681]
Using sflow data from 3 switches, the traffic is incorrect: it reports ~2Tbit/s while the real traffic is ~3Gbps down / ~2Gbps up.

Let me know what additional data you need.

![2016-08-08 17_42_57-graphs](https://cloud.githubusercontent.com/assets/20684284/17484575/42c8236c-5d93-11e6-9cc5-595073a9c6b4.png)

![2016-08-08 17_41_49-ntopng](https://cloud.githubusercontent.com/assets/20684284/17484579/485e0bac-5d93-11e6-8031-832cbacc18ba.png)

**Comment by simonemainardi** [comment]
please, enclose nprobe and ntopng configurations. Also, does the collector perform sampling of the traffic?

**Comment by dan2716430** [comment]
nProbe v.7.4.160719 (r5331)
nProbe is the collector, started like this:
nprobe --collector-port 6343 --zmq tcp://127.0.0.1:5556 >> /dev/null &

ntopng 2.4.160719 - Pro Small Business Edition, started like this:
ntopng -i tcp://127.0.0.1:5556 -d /var/tmp -w 3000 -v -m 10.0.10.0/16 >> /dev/null &

**Comment by simonemainardi** [comment]
Don't redirect the output to null to see if there are warnings or notifications.

Anyway, do you know if the collector performs sampling of the traffic? That might be the issue. Nprobe has an option for that

```
[--collector-sample-rate] <value>   | Specify the bytes/pkts collection sample rate.
```

**Comment by dan2716430** [comment]
No errors on nprobe:

nprobe --collector-port 6343 --zmq tcp://127.0.0.1:5556
08/Aug/2016 18:27:02 [nprobe.c:3399] Valid nProbe license found
08/Aug/2016 18:27:02 [nprobe.c:4864] WARNING: The output interfaceId is set to 0: did you forget to use -Q perhaps ?
08/Aug/2016 18:27:02 [nprobe.c:4867] WARNING: The input interfaceId is set to 0: did you forget to use -u perhaps ?
08/Aug/2016 18:27:02 [nprobe.c:4908] -i is ignored as --collector-port|-3 has been used: using '-i none'
08/Aug/2016 18:27:02 [nprobe.c:4967] Welcome to nProbe v.7.4.160719 ($Revision: 5331 $) for x86_64-unknown-linux-gnu with native PF_RING acceleration
08/Aug/2016 18:27:02 [nprobe.c:4977] Running on Debian GNU/Linux 7.10 (wheezy)
08/Aug/2016 18:27:02 [nprobe.c:4988] [LICENSE] nProbe SystemId:
08/Aug/2016 18:27:02 [nprobe.c:5077] WARNING: -n parameter is missing. 127.0.0.1:2055 will be used.
08/Aug/2016 18:27:02 [nprobe.c:7300] Welcome to nProbe v.7.4.160719 for x86_64-unknown-linux-gnu
08/Aug/2016 18:27:02 [plugin.c:1030] 0 plugin(s) enabled
08/Aug/2016 18:27:02 [nprobe.c:6828] Non IPv4/v6 traffic is discarded according to the template
08/Aug/2016 18:27:02 [util.c:434] GeoIP: loaded AS config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNum.dat
08/Aug/2016 18:27:02 [util.c:445] GeoIP: loaded AS IPv6 config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNumv6.dat
08/Aug/2016 18:27:02 [nprobe.c:5487] Using packet capture length 128
08/Aug/2016 18:27:02 [nprobe.c:7476] IPv6 traffic will NOT be exported/accounted by this probe
08/Aug/2016 18:27:02 [nprobe.c:7477] due to configuration options (e.g. use NetFlow v9)
08/Aug/2016 18:27:04 [nprobe.c:7623] Not capturing packet from interface (collector mode)
08/Aug/2016 18:27:04 [util.c:4036] Initializing ZMQ as server
08/Aug/2016 18:27:04 [util.c:4079] Succesfully created ZMQ endpoint tcp://127.0.0.1:5556
08/Aug/2016 18:27:04 [collect.c:147] Flow collector listening on port 6343 (IPv4/v6)
08/Aug/2016 18:27:04 [nprobe.c:7848] nProbe started successfully

**Comment by dan2716430** [comment]
Isn't nProbe the collector? 

If you ask if the switches are doing sampling, they shouldn't. I used sflowtrend before and it reported correct data.

**Comment by lucaderi** [comment]
@dan2716430 With sFlow sampling rate is dynamic and it's part of the sFlow packet. If the traffic rate is not correct there are some discrepancies between the flows being collected by nProbe. In order to fix this issue I need a pcap containing sflow flows so I can check what is going on.

**Comment by dan2716430** [comment]
How can I send you the pcap file privately?

**Comment by lucaderi** [comment]
Email deri@ntop.org

**Comment by dan2716430** [comment]
Email sent

**Comment by lucaderi** [comment]
Fixed in nProbe. Apparently the sFlow switch does not always report correct values for the samplePool: added an extra check and now it works.
