### ISSUE TITLE
how do I add my translation ?

### ISSUE THREAD

**Issue by susl16c** [ntop/ntopng#6812]
Can you create a file for Russian ?

**Comment by cardigliano** [comment]
Please take a look at https://github.com/ntop/ntopng/tree/dev/scripts/locales
Adding a translation is as easy as creating a new file ru.lua

**Comment by susl16c** [comment]
I create a file there, but it doesn't appear, can you help me with that, so that it appears there and I can gradually translate it?

**Comment by cardigliano** [comment]
@susl16c in order to test a new language file, please add it to the list at the beginning of scripts/lua/modules/locales_utils.lua
