### ISSUE TITLE
Flows not written to ClickHouse

### ISSUE THREAD

**Issue by gianlucapiccolo** [ntop/ntopng#6814]
**Environment**:
* OS name: RHEL
* OS version: 8.6
* ntopng version/revision: 5.4.220804-18199

**What happened**:
I configured ClickHouse flows dump but the table flows remains empty. Only alerts tables are populated. 

**How did you reproduce it?**
1. Install and configure nprobe to send flows to ntopng
2. Install and configure ClickHouse
3. Follow the procedure https://www.ntop.org/guides/ntopng/clickhouse/clickhouse.html#connect-to-clickhouse
4. Enable Flows Dump setting in ntopng settings
5. Start to send flows to ntopng. I used the https://github.com/nerdalert/nflow-generator. nProbe listens on the 6363 port: `nflow-generator -t 127.0.0.1 -p 6363`
6. The ClickHouse ntopng is created, the alerts are written in the alerts tables, flows table remains empty.

**Comment by lucaderi** [comment]
Can you please attach a short pcap (template+flows) captured on port 6363 for inspection?

**Comment by gianlucapiccolo** [comment]
@lucaderi Here's the PCAP, please let me know if it is enough or if it is not as you expected. Many thanks.
[test-flow-pcap.zip](https://github.com/ntop/ntopng/files/9371900/test-flow-pcap.zip)

**Comment by lucaderi** [comment]
Sorry for the delay, but I missed your reply. I have been able to reproduce the issue only in specific cases (e.g. resending a pcap). So I have made a patch that I hope addresses all corner cases. Fix will be both for dev and stable. Thanks for reporting the issue.

**Comment by lucaderi** [comment]
Please wait until packages are available and in case the problem persists, reopen this ticket
