### ISSUE TITLE
Custom CSS file does not load

### ISSUE THREAD

**Issue by dontqwerty** [ntop/ntopng#6815]
**Environment**:
* OS name: RHEL
* OS version: 8.6
*  Architecture: x86_64
* ntopng version/revision: 5.4.220812-18220

**What happened**:
The custom CSS file does not load.

**How did you reproduce it?**
1. Place the custom CSS file under `/etc/ntopng/custom_theme.css` as documented [here](https://www.ntop.org/guides/ntopng/advanced_features/oem.html#oem-customizations)
2. Restart ntopng with `systemctl restart ntopng.service`
3. Visit the Web GUI

**Debug Information**:

##### Screenshot of non-working custom CSS file
![image](https://user-images.githubusercontent.com/45130241/184345925-edb84c16-75be-4ec9-9994-38d1d72707c9.png)

##### Screenshot of working custom CSS file
![image](https://user-images.githubusercontent.com/45130241/184356217-5ca7c4ac-a789-4b94-8c40-f91eee148166.png)

##### Custom CSS file used
[custom-theme.zip](https://github.com/ntop/ntopng/files/9316351/custom-theme.zip)

##### Other (hopefully) useful information
I noticed that the DOM tries to load the custom CSS file from `<http_prefix>/dist/custom-theme.css` as defined [here](https://github.com/ntop/ntopng/blob/5.4-stable/scripts/lua/modules/page_utils.lua#L353).
But ntopng copies the custom CSS file from `/etc/ntopng/custom_theme.css` to `<http_prefix>/css/custom_theme.css` whenever it restarts.

**Comment by MatteoBiscosi** [comment]
Hi @dontqwerty a new build should be available in a couple of hours, please update and let me know. Yes, the error was simply because, instead of loading custom-theme from css folder, ntopng was trying to load from the dist folder; after the update, ntopng is going to load it from the css folder

**Comment by skyones-0** [comment]
I’m facing the same issue. How can I fix it?
