### ISSUE TITLE
No health status indicator in influxdb monitor

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#6816]
CentOS Stream release 8
ntopng Enterprise L v.5.4.220812

No health indicator on status page:

![image](https://user-images.githubusercontent.com/67421019/184584044-21cf1eda-0ac1-42b7-9976-4b43c6a5158a.png)

**Comment by MatteoBiscosi** [comment]
Hi @atemix, in the latest ntopng all the stats should be right, please update in a couple of hours and let me know

**Comment by atemix** [comment]
@MatteoBiscosi Thx, it works.
