### ISSUE TITLE
Using Hostnames in SNMP Filters in Historical Flows

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6817]
![image](https://user-images.githubusercontent.com/4493366/184606597-10e3ad41-23a1-4695-a8b9-0c3e30cde2d3.png)

Please map the host IP to the host name as it happens in the historical flows

**Comment by cardigliano** [comment]
<img width="710" alt="Screen Shot 2022-08-16 at 13 17 14" src="https://user-images.githubusercontent.com/7548711/184867411-279ed4fa-150b-46a5-a082-94e2a9d47d68.png">

**Comment by Niklasr69** [comment]
It works fine
