### ISSUE TITLE
SNMP Information Missing from Historical Flows

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6819]
![Screen Shot 2022-08-16 at 15 33 36](https://user-images.githubusercontent.com/4493366/184892585-fa10f620-2890-46d5-8060-d044ea368b35.png)

![Screen Shot 2022-08-16 at 15 33 27](https://user-images.githubusercontent.com/4493366/184892601-ff57ff41-52c6-4207-83cd-f1bb21f04352.png)

In the historical flows, under 'info' ntopng MUST display all the available information.

See also #6820

**Comment by MatteoBiscosi** [comment]
Verified as Fixed
