### ISSUE TITLE
The historical graph display has problem

### ISSUE THREAD

**Issue by lhxhanson** [ntop/ntopng#682]
I have installed the ntopng with community license and the version is v.2.5.160805.
As you can see the historical graph has no x-axis and the y-axis is begin with 'n/a'. I have tried Chrome, Firefox and IE, it looks same.
![qq 20160810141908](https://cloud.githubusercontent.com/assets/5568373/17543831/01ca9754-5f06-11e6-9dd5-56124f1eb0f5.png)

**Comment by lhxhanson** [comment]
@simonemainardi 
@lucaderi 
Can someone give any replies?

**Comment by lhxhanson** [comment]
Looks like the community license is the reason why the graph has no x-axis.

**Comment by simonemainardi** [comment]
hi, I removed the `n/a` that, you're right, it is not nice to see. For the x-axis labels, they are not available but you can still get that information from the table on the right if you hover the mouse on the point of interest. See the row 'Selection Time'

![image](https://cloud.githubusercontent.com/assets/3397663/17584855/1def946c-5fb9-11e6-8594-d93ae63eb543.png)

**Comment by lhxhanson** [comment]
It's a little pity to get the x-axis, so that the graph will looks nice, but thanks for the y-axis.
