### ISSUE TITLE
SNMP Information Missing from Live Flows 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6820]
Flow list (interface is present)
![Screen Shot 2022-08-16 at 15 47 52](https://user-images.githubusercontent.com/4493366/184895766-24f34191-8317-49ca-aad4-04cc872cef12.png)

Flow info (interface is missing)
![Screen Shot 2022-08-16 at 15 46 57](https://user-images.githubusercontent.com/4493366/184895610-e59a1dc1-1f81-4671-9ded-95d2ac085a79.png)

See also #6819

**Comment by MatteoBiscosi** [comment]
Verified as Fixed
