### ISSUE TITLE
The following packages have unmet dependencies:  ntopng : Depends: libhiredis0.13 but it is not installable

### ISSUE THREAD

**Issue by skore-onclave** [ntop/ntopng#6821]
Environment:

OS name: [Ubuntu]
OS version: [Amazon EC2] and Ubuntu 20.04
AMI name: [debian-10-amd64-20220328-962]
Architecture: [amd64]
ntopng version/revision: [5.2]
What happened:

Installation log:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ntopng : Depends: libhiredis0.13 but it is not installable

```

**Comment by cardigliano** [comment]
Please move to latest ntopng 5.4 (5.2 is no longer supported)

$ apt-cache depends ntopng | grep redis
  Depends: redis-server
  Depends: libhiredis0.14

**Comment by skore-onclave** [comment]
@cardigliano Understood, but is there any workaround to resolve this issue? as we have some dependencies with 5.2
