### ISSUE TITLE
High CPU Usage on Raspberry PI4

### ISSUE THREAD

**Issue by dandare100** [ntop/ntopng#6823]
**Environment**:
* OS name: Linux raspberrypi 5.15.56-v8+ 1575 SMP PREEMPT Fri Jul 22 20:31:26 BST 2022 aarch64 GNU/Linux
* OS version: 5.15.56
* Architecture: arm64
* ntopng version/revision: ntopng_5.5.220815-18228

**What happened**
I use ntopng to process NetFlows sent from a pFSense router.
Everything worked perfectly for many months.
It is a RPI4 with 8GB ram and nothing else running on it.
ntopng does not monitor the interfaces, it only collects netflow messages on a zmq interface.
I upgraded to ntopng_5.5.220815-18228 and now when I start ntopng it uses 197% cpu and the process name is 

2/flow_checks

`    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND `

`  3762 ntopng    20   0 2326544 231196  25856 S 197.3   2.9   7:19.57 2/flow_checks`

**How did you reproduce it?**
Install ntopng, and start it.

There does not have to be flows published to zmq for this to happen.
It happens on start up on both interface collection or zmq message collection

I have tried all the versions here : https://packages.ntop.org/RaspberryPI/bullseye_pi/arm64/ntopng/

I don't know where to get older versions from to see where it started.

**Debug Information**:

ntopng    | Starting redis-server: redis-server.
ntopng    | 18/Aug/2022 17:58:31 [Redis.cpp:151] Successfully connected to redis 127.0.0.1:6379@0
ntopng    | 18/Aug/2022 17:58:31 [Redis.cpp:151] Successfully connected to redis 127.0.0.1:6379@0
ntopng    | 18/Aug/2022 17:58:33 [Ntop.cpp:2592] Registered interface tcp://goflow:5556 [id: 0]
ntopng    | 18/Aug/2022 17:58:33 [main.cpp:344] PID stored in file /var/run/ntopng.pid
ntopng    | 18/Aug/2022 17:58:33 [Geolocation.cpp:116] Running without geolocation support.
ntopng    | 18/Aug/2022 17:58:33 [Geolocation.cpp:117] To enable geolocation follow the instructions at
ntopng    | 18/Aug/2022 17:58:33 [Geolocation.cpp:118] https://github.com/ntop/ntopng/blob/dev/doc/README.geolocation.md
ntopng    | 18/Aug/2022 17:58:34 [HTTPserver.cpp:1408] Found TLS certificate /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem
ntopng    | 18/Aug/2022 17:58:34 [HTTPserver.cpp:1683] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
ntopng    | 18/Aug/2022 17:58:34 [HTTPserver.cpp:1686] HTTP server listening on 3000
ntopng    | 18/Aug/2022 17:58:34 [Utils.cpp:3701] WARNING: Capabilities cap_set_proc error: Operation not permitted
ntopng    | 18/Aug/2022 17:58:34 [Utils.cpp:754] WARNING: Unable to retain privileges for privileged file writing
ntopng    | 18/Aug/2022 17:58:34 [Utils.cpp:800] User changed to ntopng
ntopng    | 18/Aug/2022 17:58:34 [NetworkInterface.cpp:3059] Started flow user script hooks loop on interface tcp://goflow:5556 [id: 0]...
ntopng    | 18/Aug/2022 17:58:34 [NetworkInterface.cpp:3096] Started host user script hooks loop on interface tcp://goflow:5556 [id: 0]...
ntopng    | 18/Aug/2022 17:58:34 [main.cpp:414] Working directory: /var/lib/ntopng
ntopng    | 18/Aug/2022 17:58:34 [main.cpp:416] Scripts/HTML pages directory: /usr/share/ntopng
ntopng    | 18/Aug/2022 17:58:34 [Ntop.cpp:466] Welcome to ntopng aarch64 v.5.5.220815 - (C) 1998-22 ntop.org
ntopng    | 18/Aug/2022 17:58:34 [Ntop.cpp:476] Built on Debian GNU/Linux 11 (bullseye)
ntopng    | 18/Aug/2022 17:58:34 [FlowRiskAlerts.cpp:199] [!] nDPI risk 26/Risky ASN has not been defined in ntopng
ntopng    | 18/Aug/2022 17:58:34 [FlowRiskAlerts.cpp:199] [!] nDPI risk 27/Risky Domain Name has not been defined in ntopng
ntopng    | 18/Aug/2022 17:58:34 [Ntop.cpp:882] Adding 127.0.0.1/32 as IPv4 interface address for tcp://goflow:5556
ntopng    | 18/Aug/2022 17:58:34 [Ntop.cpp:891] Adding 127.0.0.0/8 as IPv4 local network for tcp://goflow:5556
ntopng    | 18/Aug/2022 17:58:34 [PeriodicActivities.cpp:109] Started periodic activities loop...
ntopng    | 18/Aug/2022 17:58:35 [startup.lua:35] Processing startup.lua: please hold on...
ntopng    | 18/Aug/2022 17:58:37 [startup.lua:120] [lists_utils.lua:790] Refreshing category lists...
ntopng    | 18/Aug/2022 17:58:38 [startup.lua:120] [lists_utils.lua:410] Updating list 'Abuse.ch URLhaus' [https://urlhaus.abuse.ch/downloads/hostfile/]... OK
ntopng    | 18/Aug/2022 17:58:39 [startup.lua:120] [lists_utils.lua:410] Updating list 'Emerging Threats' [https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt]... OK
ntopng    | 18/Aug/2022 17:58:40 [startup.lua:120] [lists_utils.lua:410] Updating list 'Feodo' [https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt]... OK
ntopng    | 18/Aug/2022 17:58:40 [startup.lua:120] [lists_utils.lua:410] Updating list 'Feodo Tracker Botnet C2 IP Blocklist' [https://feodotracker.abuse.ch/downloads/ipblocklist.txt]... OK
ntopng    | 18/Aug/2022 17:58:41 [startup.lua:120] [lists_utils.lua:410] Updating list 'NoCoin Filter List' [https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt]... OK
ntopng    | 18/Aug/2022 17:58:42 [startup.lua:120] [lists_utils.lua:410] Updating list 'SSLBL Botnet C2 IP Blacklist' [https://sslbl.abuse.ch/blacklist/sslipblacklist.txt]... OK
ntopng    | 18/Aug/2022 17:58:42 [startup.lua:120] [lists_utils.lua:410] Updating list 'ThreatFox' [https://threatfox.abuse.ch/downloads/hostfile/]... OK
ntopng    | 18/Aug/2022 17:58:42 [startup.lua:120] [lists_utils.lua:410] Updating list 'URLhaus' [https://urlhaus.abuse.ch/downloads/hostfile/]... OK
ntopng    | 18/Aug/2022 17:58:43 [startup.lua:120] [lists_utils.lua:410] Updating list 'dshield 7 days' [https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/dshield_7d.netset]... OK
ntopng    | 18/Aug/2022 17:58:43 [startup.lua:120] [lists_utils.lua:714] Category Lists (3413 hosts, 1776 IPs, 0 JA3) loaded in 0 sec
ntopng    | 18/Aug/2022 17:58:43 [startup.lua:124] Initializing device polices...
ntopng    | 18/Aug/2022 17:58:43 [startup.lua:140] Initializing alerts...
ntopng    | 18/Aug/2022 17:58:43 [startup.lua:149] Initializing timeseries...
ntopng    | 18/Aug/2022 17:58:43 [startup.lua:212] Fetching latest ntop blog posts...
ntopng    | 18/Aug/2022 17:58:45 [startup.lua:216] Completed startup.lua
ntopng    | 18/Aug/2022 17:58:45 [PeriodicActivities.cpp:167] Found 10 activities
ntopng    | 18/Aug/2022 17:58:45 [NetworkInterface.cpp:3249] Started packet polling on interface tcp://flowhost:5556 [id: 0]...
ntopng    | 18/Aug/2022 17:58:46 [ZMQCollectorInterface.cpp:268] Collecting flows on tcp://flowhost:5556

**Comment by lucaderi** [comment]
it seems ntopng is busy with behavioural checks. Have a look at flow alerts and see what is happening there.

**Comment by dandare100** [comment]
Ok cool, thanks.
No alerts yet.
I tried disabling the behavioral checks and got this error
ntopng    | 18/Aug/2022 19:22:53 [toggle_all_checks.lua:54] [checks.lua:726] WARNING: Module 'tcp_issues_generic' is not associated to any known flow risk alert
ntopng    | 18/Aug/2022 19:22:53 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/toggle_all_checks.lua][/usr/share/ntopng/scripts/lua/modules/checks.lua:730: attempt to index a nil value (local 'flow_risk_alert')]

ntopng    | 18/Aug/2022 19:24:48 [toggle_all_checks.lua:54] [checks.lua:726] WARNING: Module 'iec_invalid_transition' is not associated to any known flow risk alert
ntopng    | 18/Aug/2022 19:24:48 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/toggle_all_checks.lua][/usr/share/ntopng/scripts/lua/modules/checks.lua:730: attempt to index a nil value (local 'flow_risk_alert')]

It seems the TCP ones all give the same issue when trying to disable them.

**Comment by cardigliano** [comment]
@dandare100 I tried clicking on Disable All or disabling individual tcp-related checks but I was unable to reproduce the same, where did you click exactly to get the above errors? Thank you.

**Comment by dandare100** [comment]
@cardigliano 

Hello

From 

https://packages.ntop.org/RaspberryPI/bullseye_pi/arm64/ntopng/ntopng_5.5.220815-18228_arm64.deb

Fresh install with following config :   
![image](https://user-images.githubusercontent.com/5639208/185762715-4035e9ab-4627-43ec-8c6d-4de76baece44.png)

I click here
Settings, Behavioural Checks

![Capture4](https://user-images.githubusercontent.com/5639208/185762785-b5a88ac0-5579-4cc5-93dc-c1b6035c5ecf.PNG)

Click disable all

![Capture5](https://user-images.githubusercontent.com/5639208/185762805-a83e2b86-207c-42ee-a08d-c6f4695a65be.PNG)

Results in 

![Capture7](https://user-images.githubusercontent.com/5639208/185762817-a06d3ced-c101-4d0d-90fa-646e7e521744.PNG)

**Comment by cardigliano** [comment]
@dandare100 I tried reproducing this with ntopng_5.5.220821-18259_arm64.deb but I was not able to get the same, please try updating and let me know. What license are you running?

**Comment by dandare100** [comment]
I installed ntopng_5.5.220821-18259_arm64.deb

If I start it with the following config

-i="tcp://goflow:5556"
--local-networks="192.168.8.0/24,192.168.50.0/24,192.168.60.0/24,192.168.70.0/24,192.168.80.0/24,10.201.0.0/24"
--community
-n=3

the error happens

If I start ntopng with no config specified (defaults) the error does not happen. (while it's running in enterprise mode)

Could it have something to do with the fact that I am only using a netflow collector interface and some of the behavioural checks are not compatible ? 

The high CPU usage still happens on both scenarios. (between 150% and 200%) and after a while the PI throttles the cpu because of the temperature.

**Comment by cardigliano** [comment]
@dandare100 please update to today's package, you should be able to disable the checks now

**Comment by dandare100** [comment]
@cardigliano Thank you, I appreciate the work. 

That package (ntopng_5.5.220823-18283_arm64.deb) has solved the disable problem. I can now disable all the behavioural checks.

I am trying to get to the bottom of the high CPU usage. It persists with all the checks disabled.


![Capture6](https://user-images.githubusercontent.com/5639208/186384638-26af8580-bbd4-4a0e-aa4f-498fc13a796c.PNG)

Things I have tried :

1. I have enabled verbosity of 6 and I can see nothing obvious in the logs. (attached)
[ntopng.log](https://github.com/ntop/ntopng/files/9414932/ntopng.log)

2. Attached to the 0/flow_checks process with strace to look for a tight loop or anything similar. There is just to much noise in this, I need to add the correct filters for it to make sense.

3. At this point I am trying to setup a virtual environment for an ARM64 architecture to test the same RaspberryPI image to verify if the behaviour is the same or if it is isolated to my PI only.

I am not sure how else to check and I will provide feedback if I pick anything up.

Thank you

Jeff

**Comment by cardigliano** [comment]
@dandare100 in the initial post you stated "There does not have to be flows published to zmq for this to happen.", does this mean ntopng will use 150% of cpu with no flow received at all? (i.e. nprobe not even running)

**Comment by dandare100** [comment]
@cardigliano Yes, that is correct. I stopped the netflow feed on the pfSense and verified with the below

![image](https://user-images.githubusercontent.com/5639208/186500309-bd63db63-eb4f-4af0-aa39-d848667e9332.png)

**Comment by cardigliano** [comment]
@dandare100 I was able to reproduce this with your configuration, thank you for the info, I will keep you posted

**Comment by dandare100** [comment]
Cool, no problem. Thanks for the update

**Comment by cardigliano** [comment]
@dandare100 I pushed a fix for this, a new update should be available later today, please let me know

**Comment by dandare100** [comment]
Yeeeehaaaaa !!!!

Thank you @cardigliano 

It is now fixed. Thank you for solving this.
