### ISSUE TITLE
JSON syntax error in hosts_stats.lua

### ISSUE THREAD

**Issue by Hedders** [ntop/ntopng#6824]
**Environment**:
* OS name: Ubuntu
* OS version: 22.04
* Architecture: amd64
* ntopng version/revision: ntopng Community v.5.5.220818

**What happened**:
"SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data" when trying to view Hosts list from Menu -> Hosts -> Hosts

**How did you reproduce it?**
Menu -> Hosts -> Hosts

**Debug Information**:

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by cardigliano** [comment]
@Hedders do you see any error in the service log? Please check "systemctl status ntopng" or "journalctl -u ntopng"

**Comment by Hedders** [comment]
> @Hedders do you see any error in the service log? Please check "systemctl status ntopng" or "journalctl -u ntopng"

Hi, yes I do:

Aug 19 16:48:37 ubuntu-lenovo ntopng[1630600]: [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_hosts_data.lua][/usr/share/ntopng/scripts/lua/get_hosts_data.lua:49: attempt to index a string value (local 'h')]
Aug 19 16:48:37 ubuntu-lenovo ntopng[1630600]: 19/Aug/2022 16:48:37 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_hosts_data.lua][/usr/share/ntopng/scripts/lua/get_hosts_data.lua:49: attempt to index a string value (local 'h')]

**Comment by cardigliano** [comment]
I pushed some tracing to debug this, please update to tomorrow's build and provide the log again. Thank you.

**Comment by Hedders** [comment]
Thanks, I will do so once the build is out and will report back.

**Comment by Hedders** [comment]
Oddly this seem to have resolved itself in build v.5.5.220819 rev.18257. The Hosts list is now working normally.

**Comment by cardigliano** [comment]
Ok great, however it is likely you have messages in your service log reporting some failures which are now handled, please report them in case.

**Comment by cardigliano** [comment]
Nevermind, I was able to reproduce, debug and fix this

**Comment by Hedders** [comment]
Thank you and sorry for the slow response - work got in the way!
