### ISSUE TITLE
error in dmesg traps: ntopng-5-pkt[581524]

### ISSUE THREAD

**Issue by leegitlee** [ntop/ntopng#6830]
hello

It's my first post , sorry if i don't respect rules

**Environment**:
*ntopng Community v.5.5.220826 (Debian GNU/Linux 11 (bullseye)) | 

**What happened**:
In dmesg i have error on a NIC but not if i put on startup --no-promisc in file ntopng.conf

[26217.651524] device enx00133b8b249b entered promiscuous mode
[26246.522600] traps: ntopng-5-pkt[581524] trap invalid opcode ip:55f23b1691c5 sp:7fdb9cff7ef8 error:0 in ntopng[55f23afdc000+226000]
[26246.547617] device enx00133b8b249b left promiscuous mode

**How did you reproduce it?**
Ntopng it's ok before the upgrade

**Debug Information**:

<!--
Paste debug information below:
root:/etc/ntopng #:> service ntopng status
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
     Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: signal) since Fri 2022-08-26 23:45:32 +04; 1s ago
    Process: 588897 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-c>
    Process: 588918 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
    Process: 588920 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (>
    Process: 588922 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf>
    Process: 588924 ExecStart=/usr/bin/ntopng /run/ntopng.conf (code=killed, signal=ILL)
    Process: 589275 ExecStopPost=/bin/rm -rf /run/ntopng.conf /run/ntopng.conf.raw /run/ntopng.pid (code=exited, status=0/SUCCESS)
   Main PID: 588924 (code=killed, signal=ILL)
        CPU: 3.654s

thanks for help

**Comment by cardigliano** [comment]
@leegitlee we fixed a similar issue a few days ago, please update and let us know. Thank you.

**Comment by leegitlee** [comment]
It's OK 
i can see now all traffic on the dashboard

Thanks
