### ISSUE TITLE
new metrics metadata api for timeseries restyle 

### ISSUE THREAD

**Issue by uccidibuti** [ntop/ntopng#6831]
**What would you like to add or change?**:
pro/scripts/lua/rest/v2/get/timeseries/type/consts.lua 

**Why do you and others need this?**:
The api must provides all interfaces metrics. The format of the api is explained in  pro/scripts/lua/rest/v2/get/timeseries/type/consts.lua .

**Comment by MatteoBiscosi** [comment]
Implemented as requested
