### ISSUE TITLE
For ntopng not show Host Historical Application in real features

### ISSUE THREAD

**Issue by joonasak** [ntop/ntopng#6834]
**Environment**:
* OS name: Ubuntu
* OS version: 18.04
* Architecture: amd64
* ntopng version/revision: 5.4.220829

**What happened**:
In the website https://www.ntop.org/products/traffic-analysis/ntop/ we saw in the screenshot of the features Host Historical Application but in real production features we don't see it. Please kindly check it.

**In Website**

![image](https://user-images.githubusercontent.com/85352105/188059575-66f85cf3-a830-4e26-8414-cbfc18941a9c.png)

**In Real Production**

![Screen Shot 2022-09-02 at 11 34 18 AM](https://user-images.githubusercontent.com/85352105/188059724-1e0f0719-27ce-4e11-b047-2622690023f5.png)

**Comment by cardigliano** [comment]
Please go to Settings -> Preferences -> Timeseries and set Host Timeseries to Full (please note this will use more resources including disk space)
