### ISSUE TITLE
Unable to add web user

### ISSUE THREAD

**Issue by PrimeIntellectLevel** [ntop/ntopng#6837]
I tried adding web user but having problem with the error prompting me. I tried different name still getting same error. See below.

![image](https://user-images.githubusercontent.com/112744466/188257621-cad1add1-b168-4b46-850c-4d27b1c21437.png)
![image](https://user-images.githubusercontent.com/112744466/188257634-202e62b8-0a82-43cf-966a-67523af3b57d.png)

I'm thinking it is a some kind of miss leading error message.

**Comment by dandare100** [comment]
Hello. You are correct. It was a typo on a field name.

The validation is actually failing on Full Name

PR 6839 created to fix https://github.com/ntop/ntopng/pull/6839

**Comment by cardigliano** [comment]
Fix merged, thank you

**Comment by PrimeIntellectLevel** [comment]
Can I suggest? to mark the field that is mandatory that way user will know which one to fill up properly. Thanks!
