### ISSUE TITLE
UI background bug in Dark Theme at TLS and SSL tab

### ISSUE THREAD

**Issue by PrimeIntellectLevel** [ntop/ntopng#6838]
The background color at TLS and SSL tab is wrong during Dark Theme. See my screenshot below.

![image](https://user-images.githubusercontent.com/112744466/188257798-a3d69c11-b837-4b78-96b9-98a929fc8c9c.png)

![image](https://user-images.githubusercontent.com/112744466/188257807-d0dc1a14-ecf1-4b02-aaab-9ddae0a0125c.png)

**Comment by MatteoBiscosi** [comment]
Verified as fixed
