### ISSUE TITLE
Bug with redis config option format @db-id only

### ISSUE THREAD

**Issue by dandare100** [ntop/ntopng#6840]
**Environment**:
* OS name: Rocky Linux 8
* OS version: 8
* Architecture:  x86_64 x86_64 x86_64 GNU/Linux
* ntopng version/revision: dev branch

**What happened**:

It looks like commit ac3d3cc38ff83aab9a86de53fcf2295e7249e058 causes the unit tests to fail. 
The test config specifies the redis option as `-r=@2`
The change for that commit increments r to check the number range for the specified db-id.
Unfortunately further down in the code there is existing logic that adds a \0 (at *r) to terminate the string for the remainder of the parsing logic.
`(*r) = '\0';`
The new increment causes the @ to now be included in the string and causes a double "@@" as can be seen in the logs below.

Unit tests failed with error
```
[i] Connectivity ok
[>] Running test 'v2/alert_dns_data_exfiltration_01' (1/54)
[!] ntopng Error: ntopng generated errors or warnings running 'v2/alert_dns_data_exfiltration_01'
04/Sep/2022 15:56:07 [Redis.cpp:93] ERROR: Connection error [Name or service not known]
04/Sep/2022 15:56:08 [Redis.cpp:93] ERROR: Connection error [Name or service not known]
04/Sep/2022 15:56:09 [Redis.cpp:93] ERROR: Connection error [Name or service not known]
```

**How did you reproduce it?**
Run the unit tests on the dev branch 
`./run.sh -D 1`

**Debug Information**:
```
04/Sep/2022 15:56:07 [Prefs.cpp:1291] **_ntopng will use redis @@2_**
04/Sep/2022 15:56:07 [Prefs.cpp:1332] All HTTP user login disabled
04/Sep/2022 15:56:07 [Redis.cpp:93] ERROR: Connection error [Name or service not known]
04/Sep/2022 15:56:08 [Redis.cpp:77] Redis has disconnected, reconnecting [remaining attempts: 14]
04/Sep/2022 15:56:08 [Redis.cpp:93] ERROR: Connection error [Name or service not known]
04/Sep/2022 15:56:09 [Redis.cpp:77] Redis has disconnected, reconnecting [remaining attempts: 13]
04/Sep/2022 15:56:09 [Redis.cpp:93] ERROR: Connection error [Name or service not known]
04/Sep/2022 15:56:10 [Redis.cpp:77] Redis has disconnected, reconnecting [remaining attempts: 12]
04/Sep/2022 15:56:10 [Redis.cpp:93] ERROR: Connection error [Name or service not known]
04/Sep/2022 15:56:11 [Redis.cpp:77] Redis has disconnected, reconnecting [remaining attempts: 11]
```

**Comment by cardigliano** [comment]
Fixed in e2519fff56e23ab82c0ca92f92f967d815c91965. Thank you!
