### ISSUE TITLE
UI bug on timeframe selection

### ISSUE THREAD

**Issue by lazyandproud** [ntop/ntopng#6843]
**Environment**:
* OS name: Debian
* OS version: 11
* Architecture: amd64
* ntopng version/revision: v.5.4.220902 rev.18359

**What happened**:
On historic flows (/lua/pro/db_search.lua) the select-box for timeframe has no description (last hour, last day, last week...)

**How did you reproduce it?**

**Debug Information**:
![image](https://user-images.githubusercontent.com/58183116/188452901-d233f241-ab18-4be6-a467-8c3e36d2bfac.png)
-->

**Comment by MatteoBiscosi** [comment]
Hi @lazyandproud please in a couple of hours update to the latest ntopng version and let me know. The issue should now be fixed; if not please right click on the page and select 'inspect' after that let me know if there are some errors in the console
![image](https://user-images.githubusercontent.com/49585191/189086183-e18e5e9e-d2a3-46f7-8bf2-af70eb778a42.png)

**Comment by lazyandproud** [comment]
Hi @MatteoBiscosi, same on v.5.4.220908 rev.18414. The errors also show up when directly connected to :3000, to exclude any issue with the reverse-proxy.
![image](https://user-images.githubusercontent.com/58183116/189303665-89b86466-2358-42ce-8124-6606b5288c5e.png)

**Comment by MatteoBiscosi** [comment]
Verified as fixed, reopen if needed

**Comment by lazyandproud** [comment]
persists on ntopng Enterprise L v.5.5.220919 rev.18494
![image](https://user-images.githubusercontent.com/58183116/192642137-b9f90f64-31cd-4b5b-86d1-0a180b74a160.png)

**Comment by lazyandproud** [comment]
still got this problem on v.5.6.230214 rev.19546

![image](https://user-images.githubusercontent.com/58183116/219216827-6cfdea3a-67f9-48e0-a6e3-9a701c096e34.png)

**Comment by MatteoBiscosi** [comment]
Hi @lazyandproud which browser are you using? In case you are using safari, please try out with chrome or firefox and let me know if the problem persists. Meanwhile I'll investigate further the issue

**Comment by MatteoBiscosi** [comment]
Hi @lazyandproud the issue should be fixed, in a couple of hours please update and let me know.
The issue was with the de language, please let me know if you find other bugs of that kind.

**Comment by lazyandproud** [comment]
looks good, thanks!
![image](https://user-images.githubusercontent.com/58183116/222153202-52f640cc-2915-4ff9-8334-36ed92402674.png)
