### ISSUE TITLE
ntopng multiple -u options in documentation

### ISSUE THREAD

**Issue by cutaway** [ntop/ntopng#6848]
**Environment**:
N/A as this is about the ntopng documentation at https://www.ntop.org/guides/ntopng/cli_options.html

**What happened**:
Two options in the ntopng 'Command Line Options' documentation have the `-u` designation. 

**How did you reproduce it?**
Review the ntopng documentation at https://www.ntop.org/guides/ntopng/cli_options.html, search for `-u`, and review each instance.

You can also run the ntopng help command, which returns the same results:

```
┌──CUTSEC - 22-09-07 9:58:41
└─$ docker run --rm ntop/ntopng:stable --help | grep -- -u
[--no-promisc|-u]                   | Don't set the interface in promisc mode.
[--user|-U] <sys user>              | Run ntopng with the specified user
[--dont-change-user|-s]             | Do not change user (debug only)
[--users-file|-u] <path>            | Users configuration file path
                                    | Default: ntopng-users.conf
```

**Debug Information**:
For example:

```
[--no-promisc|-u]                   | Don't set the interface in promisc mode.
```

and 

```
[--users-file|-u] <path>            | Users configuration file path
                                    | Default: ntopng-users.conf
```

**Comment by MatteoBiscosi** [comment]
Thanks a lot for your report @cutaway , I fixed for both, stable and dev version.
A new version is going to be available in a couple of hours

**Comment by cutaway** [comment]
I'm running from Docker. I'm not sure with these updates will hit the Docker versions. Someone else will have to test to confirm and close

**Comment by MatteoBiscosi** [comment]
verified as fixed
