### ISSUE TITLE
Web UI Flows Icon No Tooltip

### ISSUE THREAD

**Issue by cutaway** [ntop/ntopng#6849]
**Environment**:
```
┌──CUTSEC - 22-09-06 13:01:00
└─$ sudo docker run --rm -it -p 3000:3000 --net=host ntop/ntopng:stable -u -V
WARNING: Published ports are discarded when using host network mode
Starting redis-server: redis-server.
Version:	5.4.220902 [Enterprise/Professional build]
GIT rev:	5.4-stable:b472d2669d472dd119eaf8feaf0ccb9f6425939d:20220902
Pro rev:	r5122
Built on:	Ubuntu 20.04.4 LTS
System Id:	L12030603760B6B21--U12030603EE6DD189--OL
Platform:	x86_64
Edition:	Enterprise L (Bundle)
License Type:	Time-Limited [Empty license file]
Validity:	Until Tue Sep  6 18:11:03 2022
```

**What happened**:
The Flows icon has no tooltip. The following image shows the tooltip for the Devices icon.

![image](https://user-images.githubusercontent.com/1958439/188995303-4989913b-b235-42b8-a6a5-5011a05b5bd2.png)

**How did you reproduce it?**

- Log into web UI
- Hover the mouse of the icons at the top of the page to see all of the tooltips.
- Hover over the Flows icon and wait for a tooltip. 
- No tooltip is displayed.

![image](https://user-images.githubusercontent.com/1958439/188995639-e8448a8f-2095-4f96-b785-30c5f9fee222.png)

**Debug Information**:

None

**Comment by MatteoBiscosi** [comment]
Thanks @cutaway , the issue should be fixed now, wait for a couple of hours and a new build should be available

**Comment by cutaway** [comment]
I'm running from Docker. I'm not sure with these updates will hit the Docker versions. Someone else will have to test to confirm and close

**Comment by MatteoBiscosi** [comment]
verified as fixed
