### ISSUE TITLE
ntopng auth to redis

### ISSUE THREAD

**Issue by siweizhang** [ntop/ntopng#685]
Hi,
I just installed ntopng and ntopng-data on our centos 7.
But failed to start it because of the errors as shown below.
Could you help?
Regards,
Kevin SZ

**Comment by simonemainardi** [comment]
Kevin,

the issue you reported via email is the following

`[Redis.cpp:69] ERROR: NOAUTH Authentication required.`

as already discussed via mail:

> "Presently ntopng does not support Redis authentication. The error shown suggests me you have set a redis password using directive requirepass inside redis configuration file. Please disable that directive and restart redis. If you feel it is strictly necessary to have Redis authentication, please file an issue on github. In the meanwhile, you can secure it by binding it only on localhost."

so for the moment this is a feature request.

**Comment by siweizhang** [comment]
Yes.

**Comment by simonemainardi** [comment]
hi, we've added redis authentication. new dev builds are under generation. Please wait an hour and then try the newest dev package. See instructions with ntopng --help and look for option -r

**Comment by simonemainardi** [comment]
@siweizhang did you have a chance to try that feature out?

**Comment by siweizhang** [comment]
Hi,

Sorry that I become busy now.

Regards,

Siwei

Sent from my iPhone

On Aug 13, 2016, at 2:26 AM, simonemainardi <notifications@github.com<mailto:notifications@github.com>> wrote:

@siweizhanghttps://github.com/siweizhang did you have a chance to try that feature out?

##

**Comment by simonemainardi** [comment]
I close the issue as I have successfully tested the implementation provided.
