### ISSUE TITLE
Invalid Alert Type

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6853]
![image](https://user-images.githubusercontent.com/4493366/189172825-3f287438-db74-4506-b736-265c95c412f6.png)

As shown above there are two problems
- Status (column) is mapped to Alert Type (filter)
- The values are not in user-friendly mode but in numerical

Note that the bug is present in historical flows but not in alerts

**Comment by MatteoBiscosi** [comment]
verified as fixed
