### ISSUE TITLE
Detect Network Interface Bandwidth Peaks

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6855]
Add a new check that triggers an alert whenever the interface traffic is more/less than X times the previous observation period (not less than 5 minutes).

For example: in the last 10 minutes the traffic is double the traffic of the previous period (20 mins ago)

**Comment by lucaderi** [comment]
Howto implement it
- step 1
Enhance the following table
![Screen Shot 2023-02-14 at 16 54 48](https://user-images.githubusercontent.com/4493366/218789674-21333ae2-3b89-4e37-9f5e-c945b37f29f9.png)
adding in addition to the current metrics based on thresholds a new field (in addition to KB, MB, GB) named '%' ) find better names) whose value means X: if you have 5 min/+20 means that if traffic in the last 5 minutes is 20% greater of the previous 5 mins (so from -10 min to -5 min) an alert needs to be triggered
if you have 5 min/-20 means that if traffic in the last 5 minutes is 20% less of the previous 5 mins (so from -10 min to -5 min) an alert needs to be triggered

- step 2
Add interface in the same table (see if you want to make a different tab) with the same logic and check where to place this page, OR, clone the above page and create one for the interface with the same logic of the hosts

**Comment by MatteoBiscosi** [comment]
Implemented as requested
