### ISSUE TITLE
Enhance Device/MAC Address Tracking

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6856]
Add a learning period to the existing Device/MAC Address Tracking in order to avoid adding MAC addresses by hand, and letting ntopng create the MAC address list automatically.

**Comment by MatteoBiscosi** [comment]
Verified as fixed, new option added for the learning period
![image](https://user-images.githubusercontent.com/49585191/191452108-223a4635-7f63-4aae-bbcf-eebdf50b1d61.png)
