### ISSUE TITLE
Show system timezone next to system time

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6859]
**What would you like to add or change?**:
It would be helpful to show the system / server time zone as e.g. Etc/UTC (cat /etc/timezone)
<img width="333" alt="Screenshot 2022-09-09 at 16 56 36" src="https://user-images.githubusercontent.com/38549755/189381098-26fdefb3-1d65-43e1-88ea-107502a57130.png">

**Why do you and others need this?**:

**Comment by lucaderi** [comment]
![Screen Shot 2022-09-10 at 15 35 42](https://user-images.githubusercontent.com/4493366/189485837-52aa4dc7-78d1-4f8b-ad31-7fa8b539a300.png)
