### ISSUE TITLE
Timeseries Names are not Sorted

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6862]
![Screen Shot 2022-09-10 at 15 09 44](https://user-images.githubusercontent.com/4493366/189484845-4036ec6b-18b9-4f59-9e2b-1cc76ee41a4d.png)

Note that when L7 timeseries will be added the menu must be sorted in blocks
- sorted generic series (e.g. live flows)
- end of block
- sorted list of L7 protocols

**Comment by MatteoBiscosi** [comment]
Verified as fixed
