### ISSUE TITLE
Chart and Table Must Be in Sync

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6864]
![Screen Shot 2022-09-10 at 15 12 37](https://user-images.githubusercontent.com/4493366/189484931-a2019806-d95d-4782-829c-66ee94336139.png)

Clicking on a L7 protocol on the table must switch series to the same protocol. Example clicking on Discord in the table, must display Discord as timeseries.

**Comment by MatteoBiscosi** [comment]
Verified as fixed
