### ISSUE TITLE
RX/TX Traffic Colours are not uniform

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6865]
![image](https://user-images.githubusercontent.com/4493366/189485028-9d85f07d-f416-4961-89ba-b9ba8293678d.png)

The colour and style should be similar. The two greens look different. Ideally, in the mail chart, there should be a darker line at the edge of the timeseries as in the above peity chart

**Comment by MatteoBiscosi** [comment]
Verified as fixed
