### ISSUE TITLE
Invalid Behavioural Chart Style

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6866]
![Screen Shot 2022-09-10 at 15 18 40](https://user-images.githubusercontent.com/4493366/189485158-9d3053f6-f383-46fa-81b3-fd8dfb45971c.png)

In behavioural charts, it is ok that the main series is an area. What is wrong is that upper and lower bounds should be represented as lines (same as average and 95th percentile)

**Comment by MatteoBiscosi** [comment]
Verified as fixed
