### ISSUE TITLE
Missing Chart Labels

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6868]
![image](https://user-images.githubusercontent.com/4493366/189485438-cc28fd75-8985-47b1-af56-d79b83d94ad2.png)

In case a chart has no data the chart element is totally empty with no label whatsoever leading the user to think that probably there is a bug. It is requested that when there are no series points at least a label is shown in order to instruct the user that the chart is as such due to no data (similar to what happened with the table below). Other solutions are welcome as long as the issue is addressed.

**Comment by MatteoBiscosi** [comment]
Verified as fixed
![image](https://user-images.githubusercontent.com/49585191/195551156-042803ad-4e07-4fc2-b801-40220c060545.png)
