### ISSUE TITLE
ERROR: Unable to create interface myri:A2P0

### ISSUE THREAD

**Issue by pnash01** [ntop/ntopng#687]
Hi - 
 Just updated to latest nightly build, ntopng-2.5.160811-1434.x86_64.rpm, and dependencies (ntopng-data, pf_ring, pf_ring-dkms) and the software is unable to create the myricom interface:

11/Aug/2016 16:51:41 [main.cpp:196] ERROR: Unable to create interface myri:A2P0
11/Aug/2016 16:51:41 [main.cpp:229] ERROR: Startup error: missing super-user privileges ?

Software was started with the following command, as root:

SNF_APP_ID=2 /usr/local/bin/ntopng /etc/ntopng/ntopng.conf

Myricom support was working with the latest stable build (8-05-16 release).

**Comment by cardigliano** [comment]
@pnash01 what is the myricom SNF library you are using? Please note we provide v4 with the packages, which is installed under /usr/local/lib/libsnf.so.0. If your card supports v3, please try removing it and checking that ntopng is linking the one under /opt/snf/lib

**Comment by pnash01** [comment]
Couldn't find libsnf\* in /usr/local/lib and ldd shows that it isn't linking against any snf library.  Can you check to see that myricom support is enabled in the daily builds?

**Comment by cardigliano** [comment]
@pnash01 what if your OS/version?
Please also provide ldd `which pfcount`

**Comment by lucaderi** [comment]
@pnash01 Actually on CentOS libs should go under /lib64
I have just checked both CentOS's and ntopng
deri@centos7 214> ldd ntopng|grep snf
    libsnf.so.0 => /lib64/libsnf.so.0 (0x00007f4511cb2000)
deri@centos6 202> ldd ntopng|grep snf
    libsnf.so.0 => /lib64/libsnf.so.0 (0x00007f525dac4000)

Can you please check if it's really so on your system? Note that we expect you to have installed the Myricom drivers prior to install our packages

**Comment by pnash01** [comment]
Thanks - I just downloaded the Aug15 nightly build and things are working again. ldd output shows that it myricom support is enabled and it is linking to the right library.  I'm going to close out this issue.
