### ISSUE TITLE
Cannot whitelist complex domains

### ISSUE THREAD

**Issue by jacoporusso-css** [ntop/ntopng#6874]
**Environment**:
* ntopng version/revision: 5.4.220818

**What happened**:
Trying to whitelist some alerts (e.g.: Suspicious DNS Traffic) triggered by a complex internal domain string (e.g.: .ldap..tcp.pdc..msdcs.example.com) using the domain choice, the "exclude" button is grayed out. 

![screen1](https://user-images.githubusercontent.com/108343272/189694843-0f992ff3-b2e6-4d5b-af56-2d9d1222e0ad.jpg)
![screen2](https://user-images.githubusercontent.com/108343272/189694868-a726af14-8464-44f0-9f5c-ad8633136df1.jpg)

The problem can be reproduced using a url containing multiple dots in a sequence.

We tried to bypass this issue by using a wildcard notation or by whitelisting the 2nd level domain (example.com) with no luck.

**Comment by MatteoBiscosi** [comment]
Soon new builds are going to be available with the fix

**Comment by MatteoBiscosi** [comment]
Verified as fixed, reopen if needed
