### ISSUE TITLE
Replace black / white list

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6878]
**What would you like to add or change?**:
In order to not casually assigning positive connotations to ```white``` while assigning negative connotations to ```black```
If you please could consider to replace:

- Whitelist becomes allowlist.
- Blacklist becomes denylist.
- Master/slave becomes leader/follower, primary/replica or primary/standby.
- Man hours becomes person hours or engineer hours.
- Sanity check becomes quick check, confidence check or coherence check.
- Dummy value becomes placeholder value or sample value.

Thank you!
**Why do you and others need this?**:

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu, most of the connotations you suggested to change are (unfortunately) standards in networking, like blacklists/whitelists, master/slaves so we cannot change them otherwise customers may not understand it's meaning.
For the other connotations instead i'll change them.

**Comment by MatteoBiscosi** [comment]
Implemented as requested
