### ISSUE TITLE
ntopng pro license not working [mismatch error]

### ISSUE THREAD

**Issue by sos-jh-cz** [ntop/ntopng#688]
hello,

i have recently obtained license for nprobe + ntopng.
after i applied them, nprobe works but ntopng does not. it's output says:

`09/Aug/2016 12:48:59 [NtopPro.cpp:122] [LICENSE] Reading license from /etc/ntopng.license
09/Aug/2016 12:48:59 [NtopPro.cpp:120] [LICENSE] Read license from Redis [**correct license hash here**]
09/Aug/2016 12:48:59 [NtopPro.cpp:172] ERROR: [LICENSE] Invalid or missing ntopng License [License mismatch error]`

the license hash is correct (pasted from your generator).

perhaps i chose wrong edition in the generator (did not know it exactly at the generation time, so i picked some).

can you please invalidate this license, so i can generate it again? my order id is **1470685989**

i was pointed here by Maria Teresa Allegro.

ntopng is running on ubuntu server 16.04 x64

thank you.

martin.koranda@sos-jh.cz

**Comment by andressalesa** [comment]
Hi, 

I have an similar error. I asked a trial license for ntopng and nprobe and it follows in Community version.

I tested  to introduce license in interface/about but it did not work 
Then I  tried  to create the  license file in folder “etc/”  

I answered the email to Maria Teresa Allegro but I don't have a answer.

Regards

**Comment by simonemainardi** [comment]
the issue @andressalesa is different from this one, we are already following up privately. However:
- @andressalesa I noticed you are using `--community` option 

![image](https://cloud.githubusercontent.com/assets/3397663/17628734/25001ac0-60b7-11e6-995c-8cfbfc82ccdf.png)

so it is natural that ntopng starts in community mode. please remove that and it will work.
- @sos-jh-cz please send `ntopng --version`, the whole ntopng startup line and, in the meanwhile, try to start ntopng with option `--online-license-check`

**Comment by sos-jh-cz** [comment]
@simonemainardi 

version output:

```
v.2.4.160805 [Professional Edition]
GIT rev:   2.4-stable:d786da67470dd879c5bbe13d38a7f95f2b598626:20160805
Pro rev:   r641
System Id: 6F08B7B800600F2D
Built on:  Ubuntu 16.04.1 LTS
```

notably, it is autoupdated via apt.

startup config:

```
-G=/var/run/ntopng.pid
-e=
-i=tcp://127.0.0.1:1234
-w=8080
-m=192.168.0.0/16,172.16.0.0/12,10.0.0.0/8
-n=1
-S=none
-d=/var/tmp/ntopng
-q=
```

startup output:

```
12/Aug/2016 18:36:12 [Prefs.cpp:919] Logging into /var/tmp/ntopng/ntopng.log
12/Aug/2016 18:36:12 [Ntop.cpp:1121] Setting local networks to 192.168.0.0/16,172.16.0.0/16,1.0.0.0/21
12/Aug/2016 18:36:12 [Redis.cpp:92] Successfully connected to redis 127.0.0.1:6379@0
12/Aug/2016 18:36:12 [NtopPro.cpp:122] [LICENSE] Reading license from /etc/ntopng.license
12/Aug/2016 18:36:12 [NtopPro.cpp:120] [LICENSE] Read license from Redis [**license**]
12/Aug/2016 18:36:12 [NtopPro.cpp:172] ERROR: [LICENSE] Invalid or missing ntopng License [License mismatch error]
12/Aug/2016 18:36:12 [NtopPro.cpp:185] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
12/Aug/2016 18:36:12 [NtopPro.cpp:187] WARNING: [LICENSE] before returning to community mode
12/Aug/2016 18:36:12 [NtopPro.cpp:188] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
12/Aug/2016 18:36:12 [NtopPro.cpp:189] WARNING: [LICENSE] or run ntopng in community mode starting
12/Aug/2016 18:36:12 [NtopPro.cpp:190] WARNING: [LICENSE] ntopng --community
12/Aug/2016 18:36:12 [Ntop.cpp:1095] Parent process is exiting (this is normal)
```

startup with --online-license-check:

```
12/Aug/2016 18:52:49 [Prefs.cpp:919] Logging into /var/tmp/ntopng/ntopng.log
12/Aug/2016 18:52:49 [Ntop.cpp:1121] Setting local networks to 192.168.0.0/16,172.16.0.0/16,1.0.0.0/21
12/Aug/2016 18:52:49 [Redis.cpp:92] Successfully connected to redis 127.0.0.1:6379@0
12/Aug/2016 18:52:49 [NtopPro.cpp:122] [LICENSE] Reading license from /etc/ntopng.license
12/Aug/2016 18:52:49 [NtopPro.cpp:133] Contacting licensing server. Please hold on...
12/Aug/2016 18:52:50 [NtopPro.cpp:120] [LICENSE] Read license from Redis [**license**]
12/Aug/2016 18:52:50 [NtopPro.cpp:133] Contacting licensing server. Please hold on...
12/Aug/2016 18:52:50 [NtopPro.cpp:172] ERROR: [LICENSE] Invalid or missing ntopng License [License mismatch error]
12/Aug/2016 18:52:50 [NtopPro.cpp:185] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
12/Aug/2016 18:52:50 [NtopPro.cpp:187] WARNING: [LICENSE] before returning to community mode
12/Aug/2016 18:52:50 [NtopPro.cpp:188] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
12/Aug/2016 18:52:50 [NtopPro.cpp:189] WARNING: [LICENSE] or run ntopng in community mode starting
12/Aug/2016 18:52:50 [NtopPro.cpp:190] WARNING: [LICENSE] ntopng --community
12/Aug/2016 18:52:50 [Ntop.cpp:1095] Parent process is exiting (this is normal)
```

**Comment by simonemainardi** [comment]
did you try also by echoing the license directly into ntopng.license file?

e.g.,

```
echo "XXXX" > /etc/ntopng.license
```

replace XXXX with your license

**Comment by sos-jh-cz** [comment]
@simonemainardi 

yes, i created it that way and tried it again now to be sure, but nothing changed.

**Comment by lucaderi** [comment]
Hi all both licenses are invalid as they have not been generated properly. Please contact me via email (deri@ntop.org) and I will provide a new one. Sorry for the inconvenience.
