### ISSUE TITLE
Interface icons inconsistent

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6884]
**Environment**:
* OS name: [e.g. Ubuntu] Ubuntu
* OS version: [e.g. 18.04] 20.04
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223] ntopng Enterprise L v.5.5.220915

**What happened**:
Interface icons are not shown in same manner:
![image](https://user-images.githubusercontent.com/38549755/190371415-6d6f53b1-ae54-4549-89fa-367b59dc6d5e.png)

note that n2disk is running for ntap0 and ens20
all interfaces are set to mirrored and MAC address identification

**How did you reproduce it?**

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Verified as Fixed
