### ISSUE TITLE
System storage utilisation display issue

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6885]
**Environment**:
* OS name: [e.g. Ubuntu] Ubuntu
* OS version: [e.g. 18.04] 20.04
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223] ntopng Enterprise L v.5.5.220915

**What happened**:
Storage utilization seems not to be displayed correctly:
n2disk is running for ntap0 and ens20 on /mnt/n2disk/6/pcap and /mnt/n2disk/7/pcap

But system storage shows ens20 and ntap0 as well:
![image](https://user-images.githubusercontent.com/38549755/190372618-f6192390-2fe3-47f5-8c74-a0b539fcfbcd.png)

**How did you reproduce it?**

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Verified as fixed

**Comment by infinitynet2011** [comment]
I have the same problem.


![image](https://github.com/ntop/ntopng/assets/42605037/4407736e-5234-4dbf-84e1-41dd2960270a)

[root@ntopng ~]# df -h
Filesystem                  Size  Used Avail Use% Mounted on
devtmpfs                    4.0M     0  4.0M   0% /dev
tmpfs                        63G     0   63G   0% /dev/shm
tmpfs                        26G   95M   25G   1% /run
/dev/mapper/almalinux-root   70G   70G  223M **100%** /
/dev/sda2                   958M  314M  645M  33% /boot
/dev/mapper/almalinux-home  3.5T   26G  3.4T   **1%** /home
tmpfs                        13G     0   13G   0% /run/user/0
tmpfs                        13G     0   13G   0% /run/user/1001
[root@ntopng ~]# 


Everything is used from the root partition.

[root@ntopng ~]# hostnamectl
 Static hostname: ntopng
       Icon name: computer
Operating System: AlmaLinux 9.4 (Seafoam Ocelot)      
     CPE OS Name: cpe:/o:almalinux:almalinux:9::baseos
          Kernel: Linux 5.14.0-427.20.1.el9_4.x86_64
    Architecture: x86-64
 Hardware Vendor: HP
  Hardware Model: ProLiant DL360p Gen8
Firmware Version: P71
[root@ntopng ~]# 


Thanks,
Gabriel

**Comment by infinitynet2011** [comment]
..  In my case, i dont have enough room to run ntopng :)
