### ISSUE TITLE
Refresh Sankey Chart support in the Host Page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6890]
In http://ntop_host:3000/lua/host_details.lua?host=@0&page=flows_sankey it is required to
- update sankey to the latest version
- add support for https://observablehq.com/@d3/sankey
- add in the page a dropdown menu with three values: local traffic only, traffic to the host, traffic from the host
- upon dropdown value change, a REST call will be issues and the sanky chart updated

**Comment by uccidibuti** [comment]
some examples with new version of d3-sankey / d3: https://codesandbox.io/examples/package/d3-sankey

**Comment by lucaderi** [comment]
Implemented
