### ISSUE TITLE
License page is blank, won't produce system id for license creation

### ISSUE THREAD

**Issue by ropelletier** [ntop/ntopng#6893]
**Environment**:
* OS name: pfsense
* OS version: 2.6.0-RELEASE (amd64)
* Architecture: amd64
* ntopng version/revision: 5.0.220112 [Community build]

**What happened**: I need to install the license but I am unable to produce a systemid either from the license page or command line.

```
/usr/local/bin/ntopng -V
Version:	5.0.220112 [Community build]
GIT rev:	:5.0.220112

```

**Comment by MatteoBiscosi** [comment]
Hi @ropelletier please update to the latest ntopng version. We have 2 different builds: stable (5.4) and dev (5.5); we do not support previous versions

**Comment by ropelletier** [comment]
For anyone coming across this later, I needed to update to pfsense+, then I was able to upgrade the ntopng package which did solve the issue.
