### ISSUE TITLE
Double Data Load when Opening Asset Map

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6897]
![Screen Shot 2022-09-25 at 19 44 14](https://user-images.githubusercontent.com/4493366/192157511-4f7857f1-90ac-479a-b571-42f8b5c1219c.png)

When the asset map is loaded (clicking on the left sidebar) the backend is polled twice instead of once as it should be

**Comment by MatteoBiscosi** [comment]
Verified as fixed
