### ISSUE TITLE
Bullseye (Pi) Cant resolve host address packages.ntop.org

### ISSUE THREAD

**Issue by marcusobrien** [ntop/ntopng#6898]
**Environment**:
* OS name:  Debian GNU/Linux 11 (bullseye)
* OS version: 11
* Architecture: Pi 4 - ARM 
* ntopng version/revision: NONE - CANT INSTALL

**What happened**:
Try to install by following install guide, but wget reports 

unable to resolve host address 'packages.ntop.org'

**How did you reproduce it?**
Follow this page instructions 

https://packages.ntop.org/

Select Pi download - Raspberry Raspbian / Pi OS

Follow and run these commands from command line
wget https://packages.ntop.org/RaspberryPI/apt-ntop.deb

Error is 

wget https://packages.ntop.org/RaspberryPI/apt-ntop.deb
--2022-09-26 19:07:34--  https://packages.ntop.org/RaspberryPI/apt-ntop.deb
Resolving packages.ntop.org (packages.ntop.org)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘packages.ntop.org’

**Debug Information**:
- Grab a screenshot from the GUI demonstrating the issue.
![image](https://user-images.githubusercontent.com/3989070/192419372-60b8a2e7-d464-4564-93df-d0177b083baf.png)

**Comment by cardigliano** [comment]
packages.ntop.org is actually reachable, please retry and reopen this in case
