### ISSUE TITLE
Compiling from source Debian 7 - PF_RINGInterface

### ISSUE THREAD

**Issue by pcmerc** [ntop/ntopng#69]
I've updated the libnetfilter-queue packages & have moved past that error on my production machine.
I am seeing this error now. I already have a previous built of PF_RING on this machine.
Ariava does this point to an outdated PF_RING library ?
My test build environment that completed with no errors after the libnetfilter-queue packages update didn't have PF_RING on it.

src/PF_RINGInterface.cpp: In constructor ‘PF_RINGInterface::PF_RINGInterface(const char*)’:
src/PF_RINGInterface.cpp:44:14: error: ‘PF_RING_VSS_APCON_TIMESTAMP’ was not declared in this scope
make: *** [src/PF_RINGInterface.o] Error 1

**Comment by pcmerc** [comment]
It appears that was the issue. I've updated PF_RING to the latest git version. Compiled complete.

**Comment by big-muha** [comment]
How did you update the PF_RING?

**Comment by lucaderi** [comment]
perhaps you have an old PF_RING installed? Please check and if so, do remove it first.

**Comment by big-muha** [comment]
How can I remove it?
By applying clean command, then reinstalling the whole thing

**Comment by lucaderi** [comment]
If you have installed a packaged deinstall it, if installed with make install, you need to search include and lib files by hand and remove them
