### ISSUE TITLE
Interface Aliases Not Honoured in Charts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6901]
![image](https://user-images.githubusercontent.com/4493366/192797249-a86b4de5-a173-4196-a7c7-2fc3c051feda.png)

**Comment by MatteoBiscosi** [comment]
With the latest version, the issue should be fixed
![image](https://user-images.githubusercontent.com/49585191/194522855-c3485aff-f0e3-4c27-9313-e8d18a40959d.png)

**Comment by MatteoBiscosi** [comment]
Verified as fixed
