### ISSUE TITLE
Flow Exporters filter is not persistent in flow live page 

### ISSUE THREAD

**Issue by Niklasr69** [ntop/ntopng#6903]
**Environment**:
* OS name: Rocky Linux 
* OS version: 8.5
* Architecture: x86_64
* ntopng version/revision: 5.5.220829 [Enterprise/Professional build]

**What happened**:

When Flows live page doing automatic refresh after 10-15 second, other exporters is displayed even what has been filtered in the Flow Export column.

**How did you reproduce it?**
Go to Flow live page.
Add an Export filter
Wait 30 second.
Extra exporters will be displayed

**Comment by MatteoBiscosi** [comment]
Hi @Niklasr69, we fixed this issue last week, please update to the latest ntopng version and everything should work fine

**Comment by Niklasr69** [comment]
Hi,
Tested and fault solved, can be closed.
