### ISSUE TITLE
Notifications Recipients link is broken

### ISSUE THREAD

**Issue by ValeDaRold** [ntop/ntopng#6906]
**Environment**:
* ntopng version/revision: 5.4.220920-18498

**What happened**:
The Recipients link in the Notifications navbar is broken.
![captures_chrome-capture-2022-8-30](https://user-images.githubusercontent.com/36924916/193209768-a4bef968-71aa-46b8-a5e4-1fc6100a7b37.png)

**How did you reproduce it?**
In ntopNg, switch to `System` and click on `Notifications` in the left bar menu.
If you then click on the `Recipients` link, you will get the `Not Found` error.
```
The requested URL was not found on this server.
```

The URL the link is pointing to is:
```
/lua/admin/endpoint_notifications_list.lua?subdir=recipient
```

**Debug Information**:
![image](https://user-images.githubusercontent.com/36924916/193210396-b0a60d12-a0a1-4701-80bb-e9d896aafa7c.png)

**Comment by cardigliano** [comment]
@ValeDaRold the same is working for me, running ntopng Enterprise L v.5.4.220930, please update to the latest revision and let us know

**Comment by MatteoBiscosi** [comment]
Hi @ValeDaRold an fix should be available in a couple of hours, please update and let me know

**Comment by ValeDaRold** [comment]
Hi @MatteoBiscosi, 
I've just tested the new release and the link has been fixed. 

Thanks
