### ISSUE TITLE
Flows Dump to Clickhouse is broken in stable

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#6907]
**Environment**:
CentOS Stream release 8
amd64
ntopng Enterprise L v.5.4.220929

**What happened**:
After upgrading ro 5.4.220929 dumping to clickhouse was broken.
No changes in config (configured --dump-flows="clickhouse;X.X.X.X;yyy;yyy;zzz").
No errors or attempts to connect at all in logs.

**Debug Information**:

30/Sep/2022 12:50:59 [ZMQCollectorInterface.cpp:268] Collecting flows on tcp://127.0.0.1:5556c
30/Sep/2022 12:50:58 [NetworkInterface.cpp:3245] Started packet polling on interface tcp://127.0.0.1:5556c [id: 17]...
30/Sep/2022 12:50:58 [NetworkInterface.cpp:3245] Started packet polling on interface ens192,ens224 [id: 7]...
30/Sep/2022 12:50:58 [PeriodicActivities.cpp:167] Found 10 activities
30/Sep/2022 12:50:58 [startup.lua:216] Completed startup.lua
30/Sep/2022 12:50:58 [startup.lua:212] Fetching latest ntop blog posts...
30/Sep/2022 12:50:58 [startup.lua:149] Initializing timeseries...
30/Sep/2022 12:50:58 [startup.lua:140] Initializing alerts...
30/Sep/2022 12:50:58 [startup.lua:124] Initializing device polices...
30/Sep/2022 12:50:58 [startup.lua:120] [lists_utils.lua:807] Category lists not loaded (offline)
30/Sep/2022 12:50:57 [startup.lua:35] Processing startup.lua: please hold on...
30/Sep/2022 12:50:57 [PeriodicActivities.cpp:109] Started periodic activities loop...
30/Sep/2022 12:50:57 [NetworkInterface.cpp:7321] Found Observation Point: 1; Stats deserialization complete.
###
30/Sep/2022 12:50:55 [NtopPro.cpp:778] [LICENSE] License Type: Permanent License
30/Sep/2022 12:50:55 [NtopPro.cpp:777] [LICENSE] Edition: Enterprise L (Bundle)
###
30/Sep/2022 12:50:55 [Ntop.cpp:476] Built on Rocky Linux release 8.5 (Green Obsidian)
30/Sep/2022 12:50:55 [Ntop.cpp:466] Welcome to ntopng x86_64 v.5.4.220929 (5.4-stable:ce77db22e632545c66c9864390a860234cfadceb:20220929) - (C) 1998-22 ntop.org
30/Sep/2022 12:50:55 [main.cpp:409] Scripts/HTML pages directory: /usr/share/ntopng
30/Sep/2022 12:50:55 [main.cpp:407] Working directory: /home/ntopng-datadir
30/Sep/2022 12:50:55 [NetworkInterface.cpp:3092] Started host user script hooks loop on interface tcp://127.0.0.1:5556c [id: 17]...
30/Sep/2022 12:50:55 [NetworkInterface.cpp:3055] Started flow user script hooks loop on interface tcp://127.0.0.1:5556c [id: 17]...
30/Sep/2022 12:50:55 [NetworkInterface.cpp:3092] Started host user script hooks loop on interface ens192,ens224 [id: 7]...
30/Sep/2022 12:50:55 [NetworkInterface.cpp:3055] Started flow user script hooks loop on interface ens192,ens224 [id: 7]...
30/Sep/2022 12:50:55 [Utils.cpp:784] User changed to ntopng

**Comment by cardigliano** [comment]
@atemix we are building new stable packages that should fix this, a new update should be available soon (in 1h)

**Comment by atemix** [comment]
After upgrading to 5.4.220930 works fine, thx
