### ISSUE TITLE
Does ntopng clear the dropped packet counter? 

### ISSUE THREAD

**Issue by pnash01** [ntop/ntopng#691]
Hi,
  I'm running the aug15 nightly build (2.5.160815 - Small Business Pro) and noticed that upon startup, it is reporting that it dropped 99.26% of the packets.  As it continues to run, this number declines.  Is it possible that it is calculating these statistics based off of data that is stored in the mysql database from previous sessions?

**Comment by lucaderi** [comment]
The number is absolute, so if you have drops at the beginning the drops is reported all the time. Please see http://www.ntop.org/ntopng/best-practices-for-running-ntopng/
