### ISSUE TITLE
PCAP download from Historical flow

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6910]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]
ntopng Enterprise L v.5.5.220927 (Ubuntu 20.04.4 LTS) 
**What happened**:
PCAP download on historical flow page seems not working correctly.
I select time span:
<img width="1952" alt="Screenshot 2022-10-02 at 10 21 58" src="https://user-images.githubusercontent.com/38549755/193445241-8a1b2a11-1188-42f2-85f8-0c116962b235.png">

then if I set a filter e.g. for a host or without filter, I download the pcap, not all data shown in the explorer is available in the pcap
last entry from selected time frame:
![image](https://user-images.githubusercontent.com/38549755/193446593-52a1fc7c-f191-4788-90af-354b06124c1b.png)

pcap search for port:
<img width="227" alt="Screenshot 2022-10-02 at 11 03 36" src="https://user-images.githubusercontent.com/38549755/193446634-eecee598-c632-434d-be0a-08e6db399891.png">

**How did you reproduce it?**

**Debug Information**:

**Comment by cardigliano** [comment]
@martinscheu please note the flow on port 48772 is UDP, the filter you are using in wireshark is tcp.port

**Comment by martinscheu** [comment]
:D thanks @cardigliano my bad, sorry about it
