### ISSUE TITLE
ntopng can not enable Top Visited Sites in preferences

### ISSUE THREAD

**Issue by joonasak** [ntop/ntopng#6911]
**Environment**:
* OS name: Ubuntu
* OS version: 22.04.1 LTS
* Architecture: amd64
* ntopng version/revision: 5.5.220915

**What happened**:
In Settings -> Preferences -> Applications -> Top Visited Sites can not enable this features after click on Save. In the previous version, it's fine. It's happened after I upgraded to this version 5.5.220915.

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/85352105/193487498-0d9d4186-c179-46e7-9566-be2c59db6fc8.png">

**Comment by lucaderi** [comment]
I have just tested and it works for me. 
![Screen Shot 2022-10-03 at 09 55 14](https://user-images.githubusercontent.com/4493366/193527450-52728343-673a-4bde-9d2f-975382b66175.png)

Can you please explain what isn't working exactly?

**Comment by joonasak** [comment]
My problem is after click enable on that and click Save it return back to disable the same.

**Comment by MatteoBiscosi** [comment]
Hi @joonasak just like issue #6913, update to the latest version and let me know :)

**Comment by joonasak** [comment]
I have updated the ntopng to the latest version and it's worked. Thank you.

**Comment by MatteoBiscosi** [comment]
Verified as fixed
