### ISSUE TITLE
ntopng can not enable Traffic Behavior Analysis in preferences

### ISSUE THREAD

**Issue by joonasak** [ntop/ntopng#6912]
**Environment**:
* OS name: Ubuntu
* OS version: 22.04.1 LTS
* Architecture: amd64
* ntopng version/revision: 5.5.220915

**What happened**:
In Settings -> Preferences -> Behavior Analysis -> Enable Traffic Behaviour Analysis can not enable this features after click on Save. In the previous version, it's fine. It's happened after I upgraded to this version 5.5.220915.

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/85352105/193487724-81670694-c13b-4a41-a40d-fd0ac5fdd106.png">

**Comment by lucaderi** [comment]
You are using an old version: this preference has been removed. Please upgrade

**Comment by joonasak** [comment]
Okay let me try to upgrade
