### ISSUE TITLE
ntopng can not enable Active Network Discovery in preferences

### ISSUE THREAD

**Issue by joonasak** [ntop/ntopng#6913]
**Environment**:
* OS name: Ubuntu
* OS version: 22.04.1 LTS
* Architecture: amd64
* ntopng version/revision: 5.5.220915

**What happened**:
In Settings -> Preferences -> Network Discovery -> Active Network Discovery can not enable this features after click on Save. In the previous version, it's fine. It's happened after I upgraded to this version 5.5.220915.

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/85352105/193488030-90c93094-7e36-4739-84e1-48d04aa9d3a8.png">

**Comment by MatteoBiscosi** [comment]
Hi @joonasak we had this issue a couple of weeks ago, please update to the latest ntopng version and let me know if it still persists :)

**Comment by joonasak** [comment]
I have updated the ntopng to the latest version and it's worked. Thank you.

**Comment by MatteoBiscosi** [comment]
Verified as fixed
