### ISSUE TITLE
ntopng can't change the custom name interface

### ISSUE THREAD

**Issue by joonasak** [ntop/ntopng#6914]
**Environment**:
* OS name: Ubuntu
* OS version: 22.04.1 LTS
* Architecture: amd64
* ntopng version/revision: 5.5.220915

**What happened**:
On Interface -> Settings -> Custom Name not edit or change after make change and Save.

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/85352105/193488363-49cb1148-1719-4186-9200-c73152624a2b.png">

**Comment by lucaderi** [comment]
Just tested: it works for me. Can you please explain what you did exactly? My feeling is that you have many similar problems whose root cause might be similar (for instance redis).

**Comment by joonasak** [comment]
My problem is when I edit or change the custom name to something like e.g. eno1 - LAN and click Save but it return the refresh page and not save the name that I have changed.

**Comment by cardigliano** [comment]
@joonasak please:
1. update ntopng to the latest version
2. reproduce the issue
3. provide the ntopng log just after reproducing it

**Comment by joonasak** [comment]
I have updated the ntopng to the latest version and it's worked.

**Comment by joonasak** [comment]
Thank you.

**Comment by MatteoBiscosi** [comment]
Verified as fixed
