### ISSUE TITLE
Internal Error when editing mac_details

### ISSUE THREAD

**Issue by grlee** [ntop/ntopng#6916]
**Environment**:
* OS name: Raspbian
* OS version: 10 (buster)
* Architecture: armv7l
* ntopng version/revision: 5.5.220925

**What happened**:

When I click on the mac_details page for a device to update its device type or host pool.

**How did you reproduce it?**

**Debug Information**:

`
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-09-29 12:13:51 EDT; 3 days ago
  Process: 31336 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exited, status=0/SUCCESS)
  Process: 31350 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
  Process: 31352 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (code=exited, status=0/SUCCESS)
  Process: 31354 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /run/ntopng.conf (code=exited, status=0/SUCCESS)
 Main PID: 31356 (ntopng-main)
    Tasks: 39 (limit: 4915)
   CGroup: /system.slice/ntopng.service
           └─31356 /usr/bin/ntopng /run/ntopng.conf

Oct 03 00:01:41 ntop ntopng[31356]: 03/Oct/2022 00:01:41 [housekeeping.lua:37] [lists_utils.lua:411] Updating list 'SSLBL Botnet C2 IP Blacklist' [https://sslbl.abuse.ch/blacklist/sslipblacklist.txt]... OK
Oct 03 00:01:43 ntop ntopng[31356]: 03/Oct/2022 00:01:43 [housekeeping.lua:37] [lists_utils.lua:411] Updating list 'Stratosphere Lab' [https://mcfp.felk.cvut.cz/publicDatasets/CTU-AIPP-BlackList/Todays-Blackli
Oct 03 00:01:46 ntop ntopng[31356]: 03/Oct/2022 00:01:46 [housekeeping.lua:37] [lists_utils.lua:411] Updating list 'ThreatFox' [https://threatfox.abuse.ch/downloads/hostfile/]... OK
Oct 03 00:01:46 ntop ntopng[31356]: 03/Oct/2022 00:01:46 [housekeeping.lua:37] [lists_utils.lua:411] Updating list 'URLhaus' [https://urlhaus.abuse.ch/downloads/hostfile/]... OK
Oct 03 00:01:46 ntop ntopng[31356]: 03/Oct/2022 00:01:46 [housekeeping.lua:37] [lists_utils.lua:411] Updating list 'dshield 7 days' [https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/dshield_7d
Oct 03 00:01:48 ntop ntopng[31356]: 03/Oct/2022 00:01:48 [housekeeping.lua:37] [lists_utils.lua:746] Category Lists (7657 hosts, 20360 IPs, 0 JA3) loaded in 2 sec
Oct 03 07:06:07 ntop ntopng[31356]: [LuaEngine.cpp:1317] WARNING: Script failure [/usr/share/ntopng/scripts/lua/mac_details.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:1458: global 'getCustomDevic
Oct 03 07:06:07 ntop ntopng[31356]: 03/Oct/2022 07:06:07 [LuaEngine.cpp:1317] WARNING: Script failure [/usr/share/ntopng/scripts/lua/mac_details.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:1458: g
Oct 03 07:11:24 ntop ntopng[31356]: [LuaEngine.cpp:1317] WARNING: Script failure [/usr/share/ntopng/scripts/lua/mac_details.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:1458: global 'getCustomDevic
Oct 03 07:11:24 ntop ntopng[31356]: 03/Oct/2022 07:11:24 [LuaEngine.cpp:1317] WARNING: Script failure [/usr/share/ntopng/scripts/lua/mac_details.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils.lua:1458: g
`

<img width="898" alt="Screen Shot 2022-10-03 at 8 11 44 AM" src="https://user-images.githubusercontent.com/1092908/193573753-084f4f76-98ad-4607-b1d0-035bf842953e.png">

**Comment by MatteoBiscosi** [comment]
Hi @grlee the issue should be fixed, in a couple of hours (at most tomorrow morning) an other build should be available, please update and let me know.

**Comment by MatteoBiscosi** [comment]
Verified as fixed
