### ISSUE TITLE
License management for ntopng pod in Kubernetes

### ISSUE THREAD

**Issue by OCrylic** [ntop/ntopng#6917]
Hi,

**What would you like to add or change?**:
Add the possibility to use a unique license for a ntopng pod in Kubernetes

**Why do you and others need this?**:
A pod in Kubernetes may change IP address, MAC address or host (worker node) very quickly. Therefore, the license cannot be bound to those.

I did not find any information about this case so I am writing you this issue and maybe you can help me to deal wih ntopng into Kubernetes.

Best regards.

**Comment by cardigliano** [comment]
@OCrylic I guess the workaround we use with Docker (please read https://www.ntop.org/support/faq/license-inside-a-container/) does not work for you, as that assumes you can provide visibility on the host network interfaces (using –network=host)

**Comment by OCrylic** [comment]
Hi Alfredo,

Thank you for you tip.
I already saw this workaround. technically it can be done with the option hostNetwork: true in Kubernetes but in my case this is not possible for two reasons:
- It "breaks" the network for this pod/container as it gets the IP address of the worker node and not the IP address of Kubernetes pod dedicated subnet. Plus, Kubernetes does not advice to use this.
- If the pod move to an other worker node for several reason (fist node is unreachable, ...), it will get the information of this new host and will not work

**Comment by midoelhawy** [comment]
Hi @cardigliano 
I have the same problem with Docker swarm, so I think if we can find another method to validate license into docker containers without "MODE:host" it will be a great helper.

For example, by mounting device file or something like that

**Comment by midoelhawy** [comment]
Hi @cardigliano 
any news about this issue?

**Comment by cardigliano** [comment]
@midoelhawy this is in our todo list, it will be added to the roadmap asap

**Comment by midoelhawy** [comment]
Great, thank you

**Comment by midoelhawy** [comment]
@lucaderi @cardigliano any news about this issue ?

**Comment by cardigliano** [comment]
@midoelhawy we are currently working on new cloud/service licenses that should also address your use case

**Comment by iPenguin** [comment]
Here for the upvote on this issue.

**Comment by cardigliano** [comment]
The ntop cloud (beta) has been announced in https://www.ntop.org/ntop/ntop-spring-webinar-ntop-cloud-llm-ai-smartnic-april-30th-3pm-cet-9-am-est/
It includes (beta) support for cloud licenses in ntopng and nprobe, which address the container licensing issues.

**Comment by MatteoBiscosi** [comment]
As @cardigliano already told, by using the ntop cloud this issue can be addressed. In case you have troubles please re-open this ticket
