### ISSUE TITLE
Add Score/Ratio Column

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6919]
In networks/AS reports, we have columns with the number of hosts and score. 

![image](https://user-images.githubusercontent.com/4493366/194002361-6f8ea996-04e3-472a-b98f-a4eb82e5b8f0.png)

This ticket is to request to add a new column with Score Ratio computed as score / number of hosts.

**Comment by MatteoBiscosi** [comment]
Implemented as requested
