### ISSUE TITLE
Filter for 2nd and lower flow risks not working

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#6922]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]
ntopng Enterprise L v.5.5.221006 (Ubuntu 22.04.1 LTS) |

**What happened**:
When filtering in the alert list, the filter takes only into account the alert with the highest risk.
E.g. my flow has following issues:

- Clear-text credentials
- App. on Non-Std Port
- Unsafe Protocol

This flow is only shown when filtering after "Clear-text credentials". Filtering for Non-Std Port or Unsafe Protocol it will not show up

**How did you reproduce it?**

**Debug Information**:
PCAP (record time 25.08.2022 -> set time selection to "Last Year"
[CERT-SE_CTF2022.zip](https://github.com/ntop/ntopng/files/9728802/CERT-SE_CTF2022.zip)

**Comment by cardigliano** [comment]
This is expected (it never worked as it is not implemented), however I agree that this behavior should be changed to match also the secondary alerts/risks (not just the main one). We will discuss this internally and plan this change.
