### ISSUE TITLE
Clickhouse table size not shown when database name is different from "ntopng"

### ISSUE THREAD

**Issue by sbettid** [ntop/ntopng#6923]
**Environment**:
* OS name: RHEL
* OS version: 8.6
* Architecture: x86_64
* ntopng version/revision: 5.4.220920-18498

**What happened**:

When setting, in the ntopng configuration file, the dump of the flows on clickhouse, using a database with a name different from `ntopng`, the flows are correctly written in the DB but the tables size is not shown in the UI. 

**How did you reproduce it?**

1. Install clickhouse as reported in the [official documentation](https://clickhouse.com/docs/en/quick-start)
2. Set up clickhouse, in the ntopng configuration, with the following option
`-F=clickhouse;localhost;ntopng_historical_flows;default;`
3. Start to send flows to ntopng. I used the https://github.com/nerdalert/nflow-generator. 
nProbe listens on the 6363 port: 
`nflow-generator -t 127.0.0.1 -p 6363`

**Debug Information**:

We can observe how, in the UI, the flows are marked as correctly dumped but the tables sizes are not updated accordingly. 

![image](https://user-images.githubusercontent.com/18742157/194553210-232e1249-5a33-490b-866f-d6e8472cb1fb.png)

By looking at the DB tables, we can see how the flows are correctly written. Executing the query `SELECT * FROM ntopng_historical_flows\G` returns, at the bottom (flows omitted for simplicity): 

`262 rows in set. Elapsed: 0.005 sec.`

**Comment by MatteoBiscosi** [comment]
Hi @sbettid a new build should be available in a couple of hours, please later on update and let me know

**Comment by sbettid** [comment]
> Hi @sbettid a new build should be available in a couple of hours, please later on update and let me know

Hi @MatteoBiscosi, we can confirm that the new version fixed the issue, thank you for the prompt response!
