### ISSUE TITLE
Save flow confidence into DB

### ISSUE THREAD

**Issue by midoelhawy** [ntop/ntopng#6925]
**What would you like to add or change?**:
It's possible to save flow confidence as status into CLICKHOUSE DB ?

**Comment by MatteoBiscosi** [comment]
Hi @midoelhawy what do you mean by flow confidence?

**Comment by midoelhawy** [comment]
If the flow is `Guess` or `DPI`
![Screenshot from 2022-10-11 14-43-16](https://user-images.githubusercontent.com/27738027/195093934-d204a9a3-e8fd-487f-877a-5a6b691edf00.png)

**Comment by MatteoBiscosi** [comment]
Hi @midoelhawy the flow confidence is already saved
![image](https://user-images.githubusercontent.com/49585191/195800166-6dc5b2fc-9e36-41c1-a74a-bc7be828333c.png)

**Comment by midoelhawy** [comment]
@MatteoBiscosi  
Yes, i know that confidence is visible in the UI 
but I need to fetch it directly from CLICKHOUSE DB

**Comment by midoelhawy** [comment]
Hi @MatteoBiscosi 
Any news ?
