### ISSUE TITLE
VACUUM no longer in use for ClickHouse DB

### ISSUE THREAD

**Issue by zepingouin** [ntop/ntopng#6926]
**Environment**:
* OS name: Debian
* OS version: 11
* Architecture: amd64
* ntopng version/revision: 5.4.221006 rev.18605

**What happened**:

Nothing, just looking Health System

**How did you reproduce it?**

No manual action, just running

**Debug Information**:

From log :
`07/Oct/2022 18:00:05 [MySQLDB.cpp:1046] ERROR MySQL error: [Code: 62. DB::Exception: Syntax error: failed at position 1 ('VACUUM'): VACUUM. Expected one of: Query, Query with output, EXPLAIN, SELECT query, possibly with UNION, list of union elements, SELECT query, subquery, possibly with UNION, SELECT subquery, SELECT query, WITH, SELECT, SHOW CREATE QUOTA query, SHOW CREATE, SHOW [TEMPORARY] TABLES|DATABASES|CLUSTERS|CLUSTER 'name' [[NOT] [I]LIKE 'str'] [LIMIT expr], SHOW, EXISTS or SHOW CREATE query, EXISTS, DESCRIBE CACHE query, DESCRIBE, DESC, DESCRIBE query, S][1][VACUUM]`

**Comment by MatteoBiscosi** [comment]
Hi @zepingouin, please update to the latest version and let  me know if the problem persists

**Comment by zepingouin** [comment]
Updated to 5.4.221010 rev.18613

From log :
`10/Oct/2022 19:00:11 [MySQLDB.cpp:1046] ERROR MySQL error: [Code: 62. DB::Exception: Syntax error: failed at position 1 ('VACUUM'): VACUUM. Expected one of: Query, Query with output, EXPLAIN, SELECT query, possibly with UNION, list of union elements, SELECT query, subquery, possibly with UNION, SELECT subquery, SELECT query, WITH, SELECT, SHOW CREATE QUOTA query, SHOW CREATE, SHOW [TEMPORARY] TABLES|DATABASES|CLUSTERS|CLUSTER 'name' [[NOT] [I]LIKE 'str'] [LIMIT expr], SHOW, EXISTS or SHOW CREATE query, EXISTS, DESCRIBE CACHE query, DESCRIBE, DESC, DESCRIBE query, S][1][VACUUM]`

**Comment by cardigliano** [comment]
@zepingouin we pushed an update the should fix that, please update and let us know. 
Btw, what license are you running?

**Comment by zepingouin** [comment]
That's right, last update fixed the issue.
I'm using Community license.
