### ISSUE TITLE
Range picker is broken

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#6927]
Changing the time interval selection in the alerts page does not update the chart and datatable.
It seems there is some js failure (see inspector screenshot)

<img width="1352" alt="Screen Shot 2022-10-10 at 10 32 40" src="https://user-images.githubusercontent.com/7548711/194826524-63eb5f09-e3fb-4469-9c04-36a85d182007.png">

**Comment by MatteoBiscosi** [comment]
Verify as fixed
