### ISSUE TITLE
Need to have an PDF export tab button on the top talker report

### ISSUE THREAD

**Issue by AmanBisaria** [ntop/ntopng#6928]
**What would you like to add or change?**:
Create a new page where we can have top talker with top 100 applications, top 100 conversations, top 100 domains, top 100 protocols and top 100 endpoints in a single page for a node interface and we should have the pdf export button to be added in that page.

**Why do you and others need this?**:
For simplification of the report and enhancement of top talker report.

**Comment by MatteoBiscosi** [comment]
Hi @AmanBisaria so you would like to add top conversations, top servers and top domains to the top talker page, am I right?
Currently you can already download the top talkers (even if it's not really beautiful pdf) by clicking the printer icon on the top of the page.
![image](https://user-images.githubusercontent.com/49585191/196130189-6e8d16c8-0619-43a0-a252-d0447882cd48.png)

**Comment by AmanBisaria** [comment]
Thats fine, but i want all the stuff mentioned in braces to be added on the same page. (top 100 applications, top 100 conversations, top 100 domains, top 100 protocols and top 100 endpoints)

**Comment by MatteoBiscosi** [comment]
Currently working in the dev version (last version)
