### ISSUE TITLE
Add Return Code in Info Column

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6931]
In the flow below 
![image](https://user-images.githubusercontent.com/4493366/195204130-8fc5e5d3-3625-40d2-a50b-255d4a7431c8.png)

it would be nice to add the record type and error code that is reported in the info column
![Screen Shot 2022-10-11 at 23 45 50](https://user-images.githubusercontent.com/4493366/195204288-19443514-99f5-4921-b642-6d019582cd05.png)

This ticket is to request to add it for HTTP/DNS protocols (if not other).

**Comment by MatteoBiscosi** [comment]
Implemented as requested
