### ISSUE TITLE
ntopng -ndpi-protocols -p /var/lib/ntopng/protos.txt not working

### ISSUE THREAD

**Issue by LennyV95** [ntop/ntopng#6935]
Operating System: Rocky Linux 8.5
ntopng version is 5.4.221014
nDPI: 4.4.0-3744

I am looking to add custom ports:applications to the list. Documentation states creating the protos.txt aand adding the -ndpi-protocols line when starting will provide an edit option in the GUI. There seems to be an issue running the command to enable custom application list. I created the protos.txt file, stop ntopng service and run the command:

sudo systemctl start ntopng -ndpi-protocols -p /var/lib/ntopng/protos.txt

I get the ‘failed to parse lines dpi-protocols. The ntopng log file has nothing and /var/log/messages has nothing

the file has these two lines only:
tcp:9002@Elasticsearch
tcp:5601@Kibana

Also, I am told this can be put into the ntop.conf file but no reference in sample or online can I find how to add the starup command with the -ndpi-protocols added?

Thanks

**Comment by lucaderi** [comment]
You need to edit /etc/ntopng/ntopng.conf and add a new line
-p /var/lib/ntopng/protos.txt

Then 
sudo systemctl start ntopng 

and it should work

**Comment by LennyV95** [comment]
I made the changes and it is now working.

Thank you for your assistance and have a great day.

________________________________
Leonard Villa
Solutions Engineer
***@***.******@***.***>
(631)786-4632 Direct Cell

Support: ***@***.******@***.***>



[http://utility2012.apcon.com/signature/logo.png]
APCON, Inc.
9255 SW Pioneer Court
Wilsonville, OR 97070
www.apcon.com<http://www.apcon.com/>

**Comment by MatteoBiscosi** [comment]
Verified as working
