### ISSUE TITLE
Ntopng no longer starting after 5.5.221020 on PFSENSE 2.6 

### ISSUE THREAD

**Issue by danananda1** [ntop/ntopng#6936]
**Environment**:
* OS name: pfSense 
* OS version: 2.6
* Architecture: amd64
* ntopng version/revision: 5.5.221020

**What happened**:

ld-elf.so.1: Shared object "librdkafka.so.1" not found, required by "ntopng"

/usr/local/etc/rc.d/ntopng: WARNING: failed to start ntopng

However, librdkafka is not available on FreeBSD

**How did you reproduce it?**

upgrade to the latest ntopng available on the package repository and start it.

**Debug Information**:

![image](https://user-images.githubusercontent.com/116262246/196898175-bd2032d0-1512-4293-8679-85b2d988d12d.png)

**Comment by cardigliano** [comment]
@danananda1 we are currently adding kafka support to ntopng, please try updating to the next build later today

**Comment by danananda1** [comment]
However it may seem that FreeBSD and pfSense does not have kafka, will ntopng integrate support within their packages? Or do we have to add dependencies?

**Comment by cardigliano** [comment]
FreeBSD provides a librdkafka package actually, which is not a dependency of ntopng

**Comment by cardigliano** [comment]
@danananda1 please check latest package and let us know. Thank you.

**Comment by danananda1** [comment]
Hello @cardigliano,

Still the same issue after upgrading.  "librdkafka.so.1" not found, required by "ntopng"

![image](https://user-images.githubusercontent.com/116262246/197081288-f3a64027-7741-45e0-9166-42cb2fc8db1b.png)


![image](https://user-images.githubusercontent.com/116262246/197081150-fbc86bf1-b4fe-49f6-8010-b1897d232d6f.png)

**Comment by lucaderi** [comment]
@danananda1 Can you please update ntopng and report?

**Comment by danananda1** [comment]
Will update tomorrow, ntop packages server has been excruciatingly slow recently. My download speed to packages.ntop.org has been averaging 16 kb/s. Will continue to retry.

**Comment by cardigliano** [comment]
@danananda1 please try using a different connection, it seems to be fairly fast for me

**Comment by danananda1** [comment]
Issue fixed after successfully updating ntopng to 5.5.221102
