### ISSUE TITLE
ntopng installer packages not available

### ISSUE THREAD

**Issue by g3tmypi** [ntop/ntopng#6937]
**Environment**:
* OS name: Raspbian GNU/Linux 11 (bullseye)
* OS version: [e.g. 18.04]
* Architecture:  ARMv7 Processor rev 4 (v7l)
    Raspberry Pi 3 Model B Rev 1.2

**What happened**:
tried to install ntopng an used instructions from ntop.org:
(did it in the past months few times without issues)

Raspberry Raspbian Instructions
Type the following commands in your shell:

wget https://packages.ntop.org/RaspberryPI/apt-ntop.deb
sudo dpkg -i apt-ntop.deb
sudo apt-get update

sudo apt-get install ntopng nprobe n2n

**RESULT:**
Package ntopng is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package nprobe is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  nprobe

E: Package 'ntopng' has no installation candidate
E: Package 'nprobe' has no installation candidate

**How did you reproduce it?**
pi@RASP01:~ $ wget https://packages.ntop.org/RaspberryPI/apt-ntop.deb
https://packages.ntop.org/RaspberryPI/apt-ntop.deb
Resolving packages.ntop.org (packages.ntop.org)... 167.99.215.164, 2a03:b0c0:2:d0::d27:3001
Connecting to packages.ntop.org (packages.ntop.org)|167.99.215.164|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3226 (3.2K) [application/x-debian-package]
Saving to: ‘apt-ntop.deb.3’

apt-ntop.deb.3      100%[===================>]   3.15K  --.-KB/s    in 0.001s

(4.66 MB/s) - ‘apt-ntop.deb.3’ saved [3226/3226]

pi@RASP01:~ $ sudo dpkg -i apt-ntop.deb
(Reading database ... 45358 files and directories currently installed.)
Preparing to unpack apt-ntop.deb ...
Unpacking apt-ntop (2.9-16) over (2.9-16) ...
upgrade
Setting up apt-ntop (2.9-16) ...
Installing ntop GPG key. Please wait...
gpg: key 3D84C955924F7599: "Luca Deri <deri@ntop.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

pi@RASP01:~ $ sudo apt-get update
Hit:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:3 https://packages.ntop.org/apt/bullseye_pi armhf/ InRelease
Hit:4 https://packages.ntop.org/apt/bullseye_pi all/ InRelease
Reading package lists... Done

pi@RASP01:~ $ sudo apt-get install ntopng nprobe n2n
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package ntopng is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package nprobe is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  nprobe

E: Package 'ntopng' has no installation candidate
E: Package 'nprobe' has no installation candidate

**Comment by cardigliano** [comment]
The arm64 version of bullseye_pi is supported, it seems you have armhf

**Comment by g3tmypi** [comment]
Thanks for that hint. I had a working instance of ntopng months ago on this pi.

**Comment by g3tmypi** [comment]
additional question: I need to get back to buster on my pi for getting ntopng installed?

**Comment by cardigliano** [comment]
Yes, we support buster for armhf and bullseye for arm64
