### ISSUE TITLE
Missing Risk Definition

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6939]
20/Oct/2022 18:47:05 [FlowRiskAlerts.cpp:201] [!] nDPI risk 26/Risky ASN has not been defined in ntopng
20/Oct/2022 18:47:05 [FlowRiskAlerts.cpp:201] [!] nDPI risk 27/Risky Domain Name has not been defined in ntopng

**Comment by MatteoBiscosi** [comment]
Verified as fixed
