### ISSUE TITLE
Invalid Score Calculation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6941]
![Screen Shot 2022-10-22 at 15 13 52](https://user-images.githubusercontent.com/4493366/197341012-2fc3738d-6fbe-4926-83c3-98581db3cbf3.png)

Score 20 != 270 (150 + 100 + 10 + 10)

[bug.pcap.zip](https://github.com/ntop/ntopng/files/9844438/bug.pcap.zip)

**Comment by MatteoBiscosi** [comment]
Verified as fixed
