### ISSUE TITLE
 Invalid ClickHouse Alerts Calculation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6942]
![Screen Shot 2022-10-24 at 09 17 52](https://user-images.githubusercontent.com/4493366/197469289-6a80cb08-1620-441a-9b2c-0918be12fd03.png)

While the flow stats are correct, alert starts are definitively wrong and need to be fixed.

**Comment by MatteoBiscosi** [comment]
Verified as fixed with the latest version
