### ISSUE TITLE
Invalid Alert Score Handling

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6943]
![image](https://user-images.githubusercontent.com/4493366/197469693-fbaa3b9b-5bb7-4944-8588-448a04875e79.png)

After the recent severity changes, alerts are broken
1. values are hard to read when written in light green
2. errors produce low score due to a bug in the calculation. Example this alert has a score of 40 instead of 100+100+100+50+100+10+50
![Screen Shot 2022-10-24 at 09 22 39](https://user-images.githubusercontent.com/4493366/197469950-88653d15-a51d-428f-85dc-d718a03ee384.png)

This ticket might have the same root cause of #6941

**Comment by MatteoBiscosi** [comment]
Verified as fixed
