### ISSUE TITLE
Infrastructure Monitoring broken

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#6944]
OS name: CentOS Stream release 8
Architecture: amd64
* ntopng version/revision: ntopng Enterprise L v.5.4.221021

**What happened**:
Infrastrucrure Monitoring configuration actions doesn't working. Neither during configuration, nor after. Nothing happend on Edit click.
Wrong status shown.

![image](https://user-images.githubusercontent.com/67421019/197746049-ac3a748e-a33b-4d0a-8eba-a042a17833a0.png)

**Comment by MatteoBiscosi** [comment]
Hi @atemix the issue should be fixed with the latest version, thx for the report

**Comment by MatteoBiscosi** [comment]
Verified as fixed. Please reopen if needed
