### ISSUE TITLE
Traffic recording stopping in Enterprise L

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#6949]
OS name: CentOS Stream release 8
Architecture: amd64
ntopng version/revision: ntopng Enterprise L v.5.4.221026

What happened:

In Traffic Recording Settings:
Continuous traffic recording requires a n2disk license, purchase one at [e-shop](http://shop.ntop.org/). If you are no-profit, research or an education institution please read [this](http://www.ntop.org/support/faq/do-you-charge-universities-no-profit-and-research/). **ntopng Enterprise L already unlocks n2disk 1G, thus no additional license is required in that case**.
n2disk version: v.3.6.221026
SystemID: #####

But traffic recording stopping after 5 minutes, due to demo mode.

**Comment by cardigliano** [comment]
Please provide the output of n2disk1g --version

**Comment by atemix** [comment]
n2disk1g --version
27/Oct/2022 13:37:52 [n2disk.c:6112] WARNING: Invalid license found for LE######086A8F--UE######0D499E--OL
27/Oct/2022 13:37:52 [n2disk.c:6113] WARNING: Please check /etc/n2disk*.license file [License mismatch (check systemId or product version)]
n2disk1g v.3.6.221026 (r5273)
Copyright 2009-2019 ntop.org
SystemID:      LE######086A8F--UE######0D499E--OL
License:       Invalid license [License mismatch (check systemId or product version)]

ntopng --version
Version:        5.4.221026 [Enterprise/Professional build]
GIT rev:        5.4-stable:4e665c142c82df251ed4c7997e09751d25bfe29f:20221026
Pro rev:        r5134
Built on:       Rocky Linux release 8.5 (Green Obsidian)
System Id:      LE######086A8F--UE######0D499E--OL
Platform:       x86_64
Edition:        Enterprise L
License Type:   Permanent
Maintenance:    Until Thu Oct 19 11:55:37 2023 [356 days left]
License:        XusIrj######32EC31
License Hash:   2E5D24######32EC31

**Comment by cardigliano** [comment]
How are you running n2disk? Please provide the command line and configuration

**Comment by atemix** [comment]
Configured from ntopng interface.

![image](https://user-images.githubusercontent.com/67421019/198269412-debe9f1b-abc8-42c3-a82c-02316543b2ef.png)

Automatically generated n2disk config:
--interface=ens192,ens224
--dump-directory=/home/n2disk-datadir/7/pcap
--index
--timeline-dir=/home/n2disk-datadir/7/timeline
--buffer-len=4096
--max-file-len=1024
--max-file-duration=60
--disk-limit=14680064
--snaplen=1536
--writer-cpu-affinity=0
--reader-cpu-affinity=1
--compressor-cpu-affinity=2,3
--index-on-compressor-threads
-u=ntopng
--capture-direction=0
--index-tunnel-content=1
--daemon
-P=/var/run/n2disk-ens192,ens224.pid

**Comment by atemix** [comment]
We didn't change anything in ntopng or n2disk configuration for a long time
n2disk stopped after upgrade to the latest stable 5.4.221026

**Comment by cardigliano** [comment]
@atemix please drop an email to cardigliano at ntop.org with your orderid

**Comment by cardigliano** [comment]
@atemix it seems you have an ntopng Enterprise L license, you need the Enterprise L *Bundle* to also unlock n2disk1g

**Comment by atemix** [comment]
"ntopng Enterprise L already unlocks n2disk 1G, thus no additional license is required in that case" - that's wrong?

**Comment by cardigliano** [comment]
Where did you read that exactly? It seems there is a mistake somewhere in the manual

**Comment by atemix** [comment]
It's from ntopng settings.

![image](https://user-images.githubusercontent.com/67421019/198343005-48dbeaac-172c-4d74-8ea1-60bebd36c373.png)

**Comment by cardigliano** [comment]
There was a mistake in the description, I fixed that. Enterprise L *Bundle* unlocks n2disk. Curious that it was working before the upgrade..

**Comment by atemix** [comment]
Previously it was Bundle license... @cardigliano thx for help

**Comment by atemix** [comment]
By the way, in ntopng license generator missed comment for bundle too

![image](https://user-images.githubusercontent.com/67421019/198512549-0b858d1d-85fe-4078-afb5-1d09f7c5a6f4.png)

**Comment by cardigliano** [comment]
Closing this as this was due to the license. The descriptions have been fixed. Discussing this in a separate thread.
