### ISSUE TITLE
how can two or more applications use PF_RING ZC cluster? 

### ISSUE THREAD

**Issue by rezaeimh7** [ntop/ntopng#695]
Hi.

The following Picture indicates that many applications could use PF_RING clusters. 
![pf ring](https://cloud.githubusercontent.com/assets/15108703/17692989/01e1444e-63b2-11e6-9b52-f88ed82fb919.jpg)
I have tested this by the following commands.
./zount -i eth0 -c 55            ---- ok
./zcount1 -i eth0 -c 99       ----- ok

Suppose i want to use pf_ring zc. As far as i know If you open a device using a PF_RING-aware driver in zero copy (e.g. pfcount -i zc:eth1) the device becomes unavailable to standard networking as it is accessed in zero-copy through kernel bypass, as happened with the predecessor DNA. Once the application accessing the device is closed, standard networking activities can take place again.
I have 2 questions:
Question 1-  as long as the application connected to the NIC via ZC (e.g. pfcount -i zc:eth1), the NIC is inaccessible to other applications .in such a situations no one could use zero copy.
$pfcount2 -i zc:eth1            -------- error .

if i am wrong ,is it possible to use PF_RING ZC like PF_RING? the following pic show what i am trying to say.
![pf ring zc](https://cloud.githubusercontent.com/assets/15108703/17693360/b5bda90c-63b3-11e6-82fd-076a3b9a79e8.jpg)

Question 2: is it possible to use PFRing_zc as follow? if the answer is YES, how ? is there any API?
![help](https://cloud.githubusercontent.com/assets/15108703/17692023/f833674c-63ac-11e6-8019-71f217756a4c.jpg)

Thanks in Advance.

**Comment by cardigliano** [comment]
Hi Mohsen
yes you can do both with zbalance:
1. zbalance_ipc -i zc:ethX -c 99 -m 0 -n <application instance>
2. zbalance_ipc -i zc:ethX -c 99 -m 0 -n <application 1 instances>,<application 2 instances>
Please take a look at zbalance_ipc -h for more options and at the zbalance_ipc output to see how to attach consumers to the cluster. There is also a README.examples with a few examples.

Alfredo
