### ISSUE TITLE
Flow Export "WARNING JSON type not supported"

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#6950]
OS name: CentOS Stream release 8
Architecture: amd64
ntopng version/revision: ntopng Enterprise L v.5.4.221026

What happened:

After confuguring flows export between ntopng instances, errors in central ntopng:
27/Oct/2022 13:28:46 [ZMQParserInterface.cpp:1572] WARNING JSON type 1 not supported [key: 57992]
27/Oct/2022 13:28:46 [ZMQParserInterface.cpp:1572] WARNING JSON type 1 not supported [key: 57992]
27/Oct/2022 13:28:46 [ZMQParserInterface.cpp:1572] WARNING JSON type 1 not supported [key: 57991]
27/Oct/2022 13:28:46 [ZMQParserInterface.cpp:1572] WARNING JSON type 1 not supported [key: 57991]
27/Oct/2022 13:28:46 [ZMQParserInterface.cpp:1572] WARNING JSON type 1 not supported [key: 57989]
27/Oct/2022 13:28:46 [ZMQParserInterface.cpp:1572] WARNING JSON type 1 not supported [key: 57989]
27/Oct/2022 13:28:46 [ZMQParserInterface.cpp:1572] WARNING JSON type 1 not supported [key: 57988]
27/Oct/2022 13:28:46 [ZMQParserInterface.cpp:1572] WARNING JSON type 1 not supported [key: 57988]
27/Oct/2022 13:28:46 [ZMQParserInterface.cpp:1572] WARNING JSON type 1 not supported [key: 57988]
27/Oct/2022 13:28:46 [ZMQParserInterface.cpp:1572] WARNING JSON type 1 not supported [key: 57988]
27/Oct/2022 13:28:46 [ZMQParserInterface.cpp:1572] WARNING JSON type 5 not supported [key: DST_IP_LOCATION]
27/Oct/2022 13:28:46 [ZMQParserInterface.cpp:1572] WARNING JSON type 5 not supported [key: DST_IP_LOCATION]
27/Oct/2022 13:28:46 [ZMQParserInterface.cpp:1572] WARNING JSON type 5 not supported [key: DST_IP_LOCATION]
27/Oct/2022 13:28:46 [ZMQParserInterface.cpp:1572] WARNING JSON type 5 not supported [key: SRC_IP_LOCATION]
27/Oct/2022 13:28:46 [ZMQParserInterface.cpp:1572] WARNING JSON type 5 not supported [key: SRC_IP_LOCATION]
27/Oct/2022 13:28:46 [ZMQParserInterface.cpp:1572] WARNING JSON type 5 not supported [key: SRC_IP_LOCATION]
27/Oct/2022 13:28:46 [ZMQParserInterface.cpp:1572] WARNING JSON type 5 not supported [key: SRC_IP_LOCATION]

**Comment by MatteoBiscosi** [comment]
Hi @atemix please send me your ntopng.conf and nprobe.conf files directly to me `biscosi at ntop.org`

**Comment by atemix** [comment]
Hi @MatteoBiscosi, problem between ntopng instances, not between ntopng and nprobe.
Send conf directly.

**Comment by atemix** [comment]
@MatteoBiscosi Any updates?

**Comment by MatteoBiscosi** [comment]
Hi @atemix the issue should be fixed in the latest dev version. Currently backporting to the stable version

**Comment by MatteoBiscosi** [comment]
Backport done, builds are in progress, in a couple of hours a new build should be available
