### ISSUE TITLE
Infrastructure monitoring via https

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#6951]
OS name: CentOS Stream release 8
Architecture: amd64
ntopng version/revision: ntopng Enterprise L v.5.4.221026

What happened:
After #6944 configuring works fine.
But monitoring doens't work via https (http is ok). 
Even check status during https configuration is ok.
Servers certificates from corporate CA, root CA added to servers trusted store.

![image](https://user-images.githubusercontent.com/67421019/198262234-138509ef-9497-4317-b345-14b1a62e1859.png)

**Comment by MatteoBiscosi** [comment]
Hi @atemix to be able to poll from a remote ntopng using https, you need a correct set up for an SSL tunnel. You can find a blog post here describing how to do that https://www.ntop.org/ntopng/securing-ntopng-with-ssl-and-lets-encrypt/
To be sure that the SSL tunnel is working correctly, you can check it by clicking the `Check` button on the left 
![image](https://user-images.githubusercontent.com/49585191/200306923-2ff59c07-6cec-452f-969a-dfdd32210635.png)
If the same error i got pops up, it means that the SSL tunnel is not working correctly (not configured correctly most of the times).
Please re-open the issue even if after configuring everything correctly it does not work.

**Comment by atemix** [comment]
Configured correctly, check is OK. 
Remote ntopng instance (ntopng-dc) is available to central.

![1](https://user-images.githubusercontent.com/67421019/200310502-df063feb-3c00-497c-895f-44e38087f9a8.jpg)
![2](https://user-images.githubusercontent.com/67421019/200310510-b099fd1f-b495-42f4-8265-3727c68b8b11.jpg)
![3](https://user-images.githubusercontent.com/67421019/200310526-2be57968-8470-4e5e-a4d9-b2b23243a630.jpg)
