### ISSUE TITLE
Binary Application Transfer vs Windows Updates

### ISSUE THREAD

**Issue by jacoporusso-css** [ntop/ntopng#6952]
**Environment**:
* ntopng version/revision: 5.4.221019

**What happened**:
Windows updates constantly triggers Binary Application Transfer checks, making monitoring and investigation overwhelming. Since it cannot be excluded by conventional means (IP address related to updates are always changing - https://learn.microsoft.com/en-us/answers/questions/457840/what-are-the-ip-ranges-for-microsofty-windows-upda.html) is there any way to nerf this alert (since they usually are made in plain HTTP I guess there could be a pattern to recognize them)?

Thanks,
Jacopo

**Comment by lucaderi** [comment]
Already implemented https://github.com/ntop/nDPI/blob/dev/src/lib/ndpi_content_match.c.inc#L1312
