### ISSUE TITLE
Maps layout 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6954]
Since physics has been removed maps the layout is now unusable, and auto layout does not help as you can see

![Screen Shot 2022-10-29 at 11 18 49](https://user-images.githubusercontent.com/4493366/198823790-da8422c8-0051-427b-aec8-87c6d4e17d36.png)

Can you please check if you can do something including
- restore physics for a little time in order to have a better layout
- leave as is but improve auto-layout
- use a different type of map

**Comment by MatteoBiscosi** [comment]
Verified as fixed, please reopen the issue if needed
