### ISSUE TITLE
Loose configuration after reboot.

### ISSUE THREAD

**Issue by thomasbruchet** [ntop/ntopng#6955]
**Environment**:
* OS name: Debian
* OS version: 10
* ntopng version/revision: ntopng Enterprise M v.5.3.220401

**What happened**:
When I reboot my system, all the change made on "Custom Traffic Disaggregation" (at least) are lost and backed up to previous configuration.
I can modify configuration, stop the ntopng.service and restart I did'nt lost anything, all configuration are OK change made are OK, new interfaces and logs are OK. But when I reboot, all are lost and ntopng came back to previous configuration.

**How did you reproduce it?**
I delete all configuration in Custom Traffic Disaggregation then reboot the system

Can you explain how are stored the information of ntopng ? 
I think they are stored in a DB but didn't find anything yet and if it is, I don't understand why they are not saved in the DB and the old configuration are restored.

Regards
Thomas

**Comment by MatteoBiscosi** [comment]
Hi @thomasbruchet unfortunatly we do not provide support for older ntopng versions. Please update to the latest ntopng version (5.5 or 5.4) otherwise i cannot help you

**Comment by MatteoBiscosi** [comment]
The configurations are stored in Redis and everything should be saved correctly after rebooting

**Comment by thomasbruchet** [comment]
OK, I will try to have a look on redis, thank for the information.

**Comment by thomasbruchet** [comment]
I'd requested help of an sysadmin and he found that redis conf was commented for snapshotting:
Those lines was commented in /etc/redis/redis.conf, so he uncommented them and now I can reboot without loose anything
```
save 900 1
save 300 10
save 60 10000
```

He talked about persistence but not remember what he changed. I will ask him on wednesday.

**Comment by MatteoBiscosi** [comment]
Alright, thanks @thomasbruchet , please let me know out of curiosity, it was a redis configuration then.
