### ISSUE TITLE
updating 'custom traffic disaggregation' ends up with a new rule

### ISSUE THREAD

**Issue by 61swong** [ntop/ntopng#6957]
**Environment**:
* OS name: RHEL 
* OS version: 7.9
* Architecture: x86_64
* ntopng version/revision: 5.4.221021

**What happened**:
After I edited an existing 'custom traffic disaggregation' rule, the system saved it as a new rule.

**How did you reproduce it?**
Anytime when I edit an existing rule and save.

**Debug Information**:
I edited 'xxxxxx' rule, appended '_test' to the rule name and saved it. The system saved it as a new entry instead of updating the existing one.
![image](https://user-images.githubusercontent.com/50309519/199166730-53ea7d40-ab64-436b-9ea2-14bc834142c7.png)

**Comment by cardigliano** [comment]
I am not able to reproduce this with the latest stable (5.4.221102), could you please update and check again?

**Comment by 61swong** [comment]
Hi @cardigliano , I upgraded my ntopng instance to v5.4.221103 and updated the name for one of existing rules "wap_nl" to "wan_nl" and it still created a new entry "wan_nl".
![image](https://user-images.githubusercontent.com/50309519/199888526-21d80ad6-d253-4312-904f-5d962a2b69a4.png)
On another ntopng instance, I ran the upgrade and got it up to the same version, the same change also caused the system to create a new rule for me.

**Comment by MatteoBiscosi** [comment]
Hi @61swong the issue should now be fixed, please updated in 3h and let me know

**Comment by MatteoBiscosi** [comment]
Verified as fixed, please reopen the issue if needed

**Comment by 61swong** [comment]
Thanks. I confirmed it's fixed.
