### ISSUE TITLE
Unable to delete local ntopng user with username equal to an email address

### ISSUE THREAD

**Issue by netravnen** [ntop/ntopng#6958]
**Environment**:
* OS name: Ubuntu
* OS version: 22.04 LTS
* Architecture: AMD64
* ntopng version/revision: v.5.4.220721

**What happened**:

Unable to delete local ntopng user account if username is user@example.com

**How did you reproduce it?**

1. Go to path `{{ FQDN }}/lua/admin/users.lua`
2. Add user with password, full name, and username as `user@example.com`
3. Set role to `Administrator`
4. Hit 'add new user'

Next

1. Go to path `/lua/admin/users.lua`
2. Try to hit the delete button.
3. The prompt shows up _without_ any user information present.

![image](https://user-images.githubusercontent.com/1938389/199309733-4b03cede-f920-4da3-a9a6-8187f1e7c54f.png)

![image](https://user-images.githubusercontent.com/1938389/199310101-5d79fac9-3c54-4e27-8570-83205ff0fa60.png)

**Debug Information**:

Not available.

**Comment by netravnen** [comment]
![image](https://user-images.githubusercontent.com/1938389/199310978-8738833d-041f-496e-8b4c-108d8d19363c.png)

Fails to delete :(

**Comment by MatteoBiscosi** [comment]
Verified as fixed, please reopen the issue if needed
