### ISSUE TITLE
Disabling Alerts not working

### ISSUE THREAD

**Issue by grlee** [ntop/ntopng#6959]
NTOP bug

**Environment**:
* OS name: Raspbian
* OS version: 10 (buster)
* Architecture: armv7l
* ntopng version/revision: 5.5.221025

**What happened**:

When I look over alerts on the “alert_stats” page and want to disable certain ones (like “Suspicious DNS Traffic” to a specific DNS server), I find that none of the alerts I select to disable are disabled, nor any alerts deleted if I choose that option.

**How did you reproduce it?**

1.  Go to Alert Stats page and view a list of alerts
2. Use the right menu on one of the alert rows and select “Disable”
3. Choose Any options you want for disabling the alert (including deleting current alerts that match.)

**Debug Information**:

   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2022-10-29 22:05:59 EDT; 2 days ago
  Process: 8481 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore ||
  Process: 8495 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
  Process: 8497 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (code=exited, status
  Process: 8499 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /run/ntopng.
 Main PID: 8501 (ntopng-main)
    Tasks: 37 (limit: 4915)
   CGroup: /system.slice/ntopng.service
           └─8501 /usr/bin/ntopng /run/ntopng.conf

Nov 01 17:21:30 ntop ntopng[8501]: [notifications.lua:25] [recipients.lua:900] ERROR: Error while sending notifications via REDACTED Un
Nov 01 17:21:30 ntop ntopng[8501]: 01/Nov/2022 17:21:30 [notifications.lua:25] [recipients.lua:900] ERROR: Error while sending notifications via REDACTED
Nov 01 17:23:43 ntop ntopng[8501]: [Utils.cpp:1846] WARNING: Unable to send email to (REDACTED): Couldn't connect to ser
Nov 01 17:23:43 ntop ntopng[8501]: 01/Nov/2022 17:23:43 [Utils.cpp:1846] WARNING: Unable to send email to (REDACTED): Co
Nov 01 17:26:07 ntop ntopng[8501]: [Utils.cpp:1846] WARNING: Unable to send email to (REDACTED): Couldn't connect to ser
Nov 01 17:26:07 ntop ntopng[8501]: 01/Nov/2022 17:26:07 [Utils.cpp:1846] WARNING: Unable to send email to (REDACTED): Co
Nov 01 17:28:40 ntop ntopng[8501]: [Utils.cpp:1846] WARNING: Unable to send email to (REDACTED): Couldn't connect to ser
Nov 01 17:28:40 ntop ntopng[8501]: 01/Nov/2022 17:28:40 [Utils.cpp:1846] WARNING: Unable to send email to (REDACTED): Co
Nov 01 17:31:04 ntop ntopng[8501]: [Utils.cpp:1846] WARNING: Unable to send email to (REDACTED): Couldn't connect to ser
Nov 01 17:31:04 ntop ntopng[8501]: 01/Nov/2022 17:31:04 [Utils.cpp:1846] WARNING: Unable to send email to (REDACTED):
![Screenshot 2022-10-31 at 11 17 36 AM](https://user-images.githubusercontent.com/1092908/199346554-c457af41-f6bd-4846-888b-8a3c45808ae7.png)

**Comment by cardigliano** [comment]
@grlee this seems to be working for me, please check:
1. if ntopng created new entries under Settings -> Behavioural Check Exclusions  for the alerts you tried to delete
2. if your browser logs failures or there is some failing request in your browser inspector when you click on the Exclude button

**Comment by grlee** [comment]
There's a Settings -> "Behavioural Check" menu option, but no "Behavioural Check Exclusions" menu option.
<img width="1025" alt="Screenshot 2022-11-02 at 11 45 23 AM" src="https://user-images.githubusercontent.com/1092908/199535498-77e7679f-f973-44c6-b4e7-11e698d055f3.png">

**Comment by cardigliano** [comment]
@grlee what license model are you running?

**Comment by grlee** [comment]
ntopng Professional

**Comment by cardigliano** [comment]
@grlee please note Check Exclusions are available with Enterprise M/L/XL, the "Exclude Check" action/dialog was shown by mistake, but it actually does not work on your version as you see. I fixed it.

**Comment by grlee** [comment]
Thanks
