### ISSUE TITLE
Restore Add button in Check Exclusions

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#6960]
The Check Exclusions page used to have the option to create entries. Please restore the button.

<img width="1263" alt="Screen Shot 2022-11-02 at 16 43 19" src="https://user-images.githubusercontent.com/7548711/199534897-66266642-c288-4969-8dd1-8df455f863dc.png">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
