### ISSUE TITLE
Ntopng service does not respond when service restart command is given - pfSense

### ISSUE THREAD

**Issue by danananda1** [ntop/ntopng#6961]
**Environment**:
* OS name: pfSense
* OS version: 2.6
* Architecture: amd64
* ntopng version/revision: 5.1.221102

**What happened**:

Trying to restart the ntopng service in pfsense using the ssh command "service ntopng restart" results in a hang whereby the computer waits for the PID. Nothing happens until you do a Control+C command in the terminal. 

Running the command again afterwards will successfully restart ntopng. 

However, the cycle repeats when you try to restart the service at a later time.

**How did you reproduce it?**

When ntopng is running, command service ntopng restart

**Debug Information**:

![image](https://user-images.githubusercontent.com/116262246/199638005-ac2d96aa-49d5-41c9-a737-c9d7509ae66b.png)

**Comment by lucaderi** [comment]
This works in ntopng 5.5.xxxxx and above. Please update
