### ISSUE TITLE
Host Traffic Analysis not working still loading

### ISSUE THREAD

**Issue by joonasak** [ntop/ntopng#6962]
**Environment**:
* OS name: Ubuntu
* OS version: 22.04
* Architecture: amd64
* ntopng version/revision: 5.5.221103

**What happened**:
I tried to open the new features of Host Traffic Analysis but it's still keep loading not show anything.

**How did you reproduce it?**
It should be show like you have published on your website.

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/85352105/199663720-0cf8d7bf-ac77-4bf2-8499-7ae3079d4e0d.png">

**Comment by joonasak** [comment]
### Traffic Tab Also have problem

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/85352105/199665758-17a178a9-65db-4455-a89a-8215a83cb054.png">

**Comment by MatteoBiscosi** [comment]
Hi @joonasak could you please right click the page and send me the output of the console?
I tried to reproduce your case but everything seems working fine for both local and remote hosts.
![image](https://user-images.githubusercontent.com/49585191/199697490-794ee998-8522-4875-99e8-f23e281826e4.png)

**Comment by MatteoBiscosi** [comment]
Other then that, could you please check if maybe there is some error in the `journalctl -e -u ntopng` after loading the page?

**Comment by MatteoBiscosi** [comment]
Verified as fixed, please reopen the issue if needed
