### ISSUE TITLE
Hide Top Applications Table

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6963]
The table with top applications should be hidden when L7 timeseries are not enabled for local hosts.

<img width="970" alt="image" src="https://user-images.githubusercontent.com/4493366/199663801-03f8d0e1-602f-4926-b932-621635aac86c.png">

**Comment by uccidibuti** [comment]
This is the ticket to fix the problem: Set active timeseries and active top timeseries #7013
