### ISSUE TITLE
Filter for portname in ts_query 

### ISSUE THREAD

**Issue by rmorandell-pgum** [ntop/ntopng#6964]
Hi,

We have the requirement to search in the timeseries not only on a port index of a switch (exporter) but also by port name (interface name).

Example of a actual request via port-index:

http://devele:3000/lua/rest/v2/get/timeseries/ts.lua?ts_query=port:0,device:192.168.2.134,ifid:3&epoch_end=1667468100&ts_schema=flowdev_port:traffic&ts_compare=30m&zoom=30m&epoch_begin=1667466300&initial_point=true&limit=6

This is usefull because we are working always with the interface names.  For example: UpLink or Eth1

Thanks for help

**Comment by cardigliano** [comment]
The API is now accepting also interface names as provided by snmp or nprobe with mapping
