### ISSUE TITLE
Can't access pcap analysis feature

### ISSUE THREAD

**Issue by jacoporusso-css** [ntop/ntopng#6966]
**Environment**:
* OS name: Centos
* OS version: 7 (CentOS Linux release 7.9.2009 (Core))
* Architecture: x86
* ntopng version/revision: v.5.4.221102

**What happened**:
I'm trying to access the feature mentioned [here](https://www.ntop.org/ntopng/howto-use-ntopng-for-pcap-analysis/) and [here](https://www.ntop.org/guides/ntopng/web_gui/pcap_analysis.html) to analyze traffic using pcap files. Anyway, looking in the UI I have no "Analyse Pcap File" voice under Developer menu. Is there any requirement that has to be fullfilled to make it appear?

![immagine](https://user-images.githubusercontent.com/108343272/199953135-8fa6aa63-ec7c-4db0-a77c-3a30d9b79119.png)

**Comment by cardigliano** [comment]
This is available on dev branch only until we release a new stable
