### ISSUE TITLE
Infrastructure monitoring via https

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#6967]
#6951

Configured correctly, check is OK.
Remote ntopng instance (ntopng-dc) is available to central.

![1](https://user-images.githubusercontent.com/67421019/200320421-e6363101-c571-46b0-b9a1-2f4678841368.jpg)
![2](https://user-images.githubusercontent.com/67421019/200320426-88b60e2a-965e-434d-8a50-72d50da0e704.jpg)
![3](https://user-images.githubusercontent.com/67421019/200320428-e0e93c50-7505-445c-8385-2bd059d28bbb.jpg)

**Comment by MatteoBiscosi** [comment]
Hi @atemix , try curling by adding the -u option to the curl (username:password) and let me know if in your case works

**Comment by MatteoBiscosi** [comment]
Hi @atemix, i added a debug print on the host that is doing https traffic, in couple of hours update and let me know the output on `journalctl -e -u ntopng` after pinging to the remote ntopng instance.
Sorry for all these questions, but in my instance https monitoring is working correctly

**Comment by atemix** [comment]
@MatteoBiscosi curling works fine

![image](https://user-images.githubusercontent.com/67421019/202626934-e3592373-c18b-4e57-bba2-f17f9875e5dc.png)

**Comment by atemix** [comment]
@MatteoBiscosi Nothing in logs

Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [Redis.cpp:151] Successfully connected to redis 127.0.0.1:6379@0
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [Redis.cpp:151] Successfully connected to redis 127.0.0.1:6379@0
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [NtopPro.cpp:315] [LICENSE] Reading license from /etc/ntopng.license
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [NtopPro.cpp:486] [LICENSE] /etc/ntopng.license: found valid Enterprise L license
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [PF_RINGInterface.cpp:69] Reading packets from PF_RING v.8.2.0 interface ens192...
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [Ntop.cpp:2589] Registered interface ens192 [id: 1]
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [main.cpp:337] PID stored in file /var/run/ntopng.pid
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [Geolocation.cpp:149] Loaded database GeoLite2-City.mmdb [/usr/share/GeoIP/GeoLite2-City.mmdb][ip_version: 6]
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [Geolocation.cpp:149] Loaded database dbip-asn-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip-asn-lite.mmdb]>
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [Geolocation.cpp:95] Using geolocation provided by DB-IP (https://db-ip.com)
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [HTTPserver.cpp:1408] Found TLS certificate /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [HTTPserver.cpp:1629] HTTP logs will be stored on /home/ntopng-datadir/ntopng_access.log
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [HTTPserver.cpp:1683] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [HTTPserver.cpp:1692] HTTPS server listening on 443
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [Utils.cpp:784] User changed to ntopng
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [NetworkInterface.cpp:3055] Started flow user script hooks loop on interface ens192 [id: 1]...
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [NetworkInterface.cpp:3092] Started host user script hooks loop on interface ens192 [id: 1]...
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [main.cpp:407] Working directory: /home/ntopng-datadir
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [main.cpp:409] Scripts/HTML pages directory: /usr/share/ntopng
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [Ntop.cpp:466] Welcome to ntopng x86_64 v.5.4.221117 (5.4-stable:dd9078bf8c8735a7dba0d376b8a12b63ba684c87:20221>
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [Ntop.cpp:476] Built on Rocky Linux release 8.5 (Green Obsidian)
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [NtopPro.cpp:788] [LICENSE] #####
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [Ntop.cpp:879] Adding 10.99.0.23/32 as IPv4 interface address for ens192
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [Ntop.cpp:888] Adding 10.99.0.0/24 as IPv4 local network for ens192
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [Ntop.cpp:910] Adding fe80::250:56ff:fea3:f67f/128 as IPv6 interface address for ens192
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [Ntop.cpp:920] Adding fe80::250:56ff:fea3:f67f/64 as IPv6 local network for ens192
Nov 18 08:28:02 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:02 [PeriodicActivities.cpp:109] Started periodic activities loop...
Nov 18 08:28:03 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:03 [startup.lua:35] Processing startup.lua: please hold on...
Nov 18 08:28:07 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:07 [startup.lua:120] [lists_utils.lua:807] Category lists not loaded (offline)
Nov 18 08:28:07 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:07 [startup.lua:124] Initializing device polices...
Nov 18 08:28:07 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:07 [startup.lua:140] Initializing alerts...
Nov 18 08:28:07 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:07 [startup.lua:149] Initializing timeseries...
Nov 18 08:28:07 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:07 [startup.lua:212] Fetching latest ntop blog posts...
Nov 18 08:28:07 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:07 [startup.lua:216] Completed startup.lua
Nov 18 08:28:07 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:07 [PeriodicActivities.cpp:167] Found 10 activities
Nov 18 08:28:07 stal-ntopng ntopng[1935212]: 18/Nov/2022 08:28:07 [NetworkInterface.cpp:3245] Started packet polling on interface ens192 [id: 1]...

![image](https://user-images.githubusercontent.com/67421019/202628630-57bc5eec-daad-4638-9a16-c35e39ce85eb.png)

![image](https://user-images.githubusercontent.com/67421019/202628657-90d6dd4b-08c9-4106-805e-76c882fb4349.png)

**Comment by MatteoBiscosi** [comment]
Hi @atemix sorry, i didn't explain well. Whenever a new curl is done a log should popup in your `journalctl -e -u ntopng`, something like
`[ActiveMonitoring] GET google.com`
 `[ActiveMonitoring] Response: `
could you please check it out and report here or send me the print by email `biscosi at ntop.org` if it contains private information

**Comment by atemix** [comment]
Hi @MatteoBiscosi, sent you an email.

**Comment by MatteoBiscosi** [comment]
Hi @atemix sorry for the wait but i was working on the issue. Now on our test site it works again, please in a couple of hours update to the latest version and let me know if it works again or not

**Comment by atemix** [comment]
Hi @MatteoBiscosi, no change =(
Now its failing on resolve host name error, even direct IP specified.

![image](https://user-images.githubusercontent.com/67421019/204031869-7fdcf2e9-aacf-473d-9b97-1ffea5a75b50.png)

**Comment by MatteoBiscosi** [comment]
Hi @atemix sorry it was my bad, i totally didn't see that i had to change even an other file. New builds should be available in a couple of hours
Let me know if the check now works and if the active monitoring and infrastructure monitoring works.
You should have two active monitoring instances in this page after adding a new infrastructure
![image](https://user-images.githubusercontent.com/49585191/204269291-53cf46a2-4526-4536-b342-b53989357e76.png)

**Comment by atemix** [comment]
Hi @MatteoBiscosi, It works, thx for help.
But now there is a bug in active monitoring page, sent you an email.

**Comment by atemix** [comment]
@MatteoBiscosi After upgrading to 5.4.221129 everything works perfect.
Thx for help.

**Comment by megam19** [comment]
> Hi @atemix sorry for the wait but i was working on the issue. Now on our test site it works again, please in a couple of hours update to the latest version and let me know if it works again or not

08/Jan/2023 18:08:59 [startup.lua:124] Initializing device polices...
08/Jan/2023 18:08:59 [startup.lua:140] Initializing alerts...
08/Jan/2023 18:08:59 [startup.lua:149] Initializing timeseries...
08/Jan/2023 18:08:59 [startup.lua:212] Fetching latest ntop blog posts...
08/Jan/2023 18:09:00 [startup.lua:216] Completed startup.lua
08/Jan/2023 18:09:00 [PeriodicActivities.cpp:167] Found 10 activities
08/Jan/2023 18:09:00 [NetworkInterface.cpp:3245] Started packet polling on interface enp2s1 [id: 0]...

it doesn't work

VMware Workstation Pro 16.2.4
Ubuntu 22.04.1 LTS
docker run -it -p 3000:3000 -v $(pwd)/ntopng.license:/etc/ntopng.license:ro --net=host ntop/ntopng:latest -i enp2s1
