### ISSUE TITLE
information how many exporters per observation point

### ISSUE THREAD

**Issue by Niklasr69** [ntop/ntopng#6968]
A new column in page "Flow Exp.=>Observation Points" with number of Exporters per Observation Points

When using more than one Observation Points, it is difficult to know how many every one has.

![image](https://user-images.githubusercontent.com/26242302/200329155-cfec58fe-b75a-4d4b-8764-a63cfd0e7971.png)

**Comment by Niklasr69** [comment]
Status?

**Comment by MatteoBiscosi** [comment]
Implemented as requested
