### ISSUE TITLE
[Documentation] Info about alerts by api rest

### ISSUE THREAD

**Issue by PaoGRodrigues** [ntop/ntopng#6969]
Hi!

I am trying to make a report based on alerts. I need to get all alerts related with a specific host via rest api, but there are some parameters in documentation that are missed.

I tried the enpoints in the docs but they're not clear.

Ej.
My request:
curl -u ****:**** -H "Content-Type: application/json" 'http://ip:port/lua/rest/v2/get/host/alert/list.lua?ifid=2&epoch_begin=1667260800&epoch_end=1667779200'

Reponse:
{"recordsTotal":0,"rc_str":"OK","recordsFiltered":0,"rsp":{"records":[],"stats":{"num_records_processed":"Processed 0 records [0 records/sec]","query_duration_msec":0.36406517028809,"query":" SELECT 1 entity_id, (tstamp_end - tstamp) duration, * FROM `host_alerts` WHERE (tstamp >= 1667260800 AND tstamp <= 1667779200)    "}},"rc_str_hr":"Success","rc":0}

I tried putting the host's IP as a parameter too, but it doesn't work.

Thanks!

**Comment by MatteoBiscosi** [comment]
Hi @PaoGRodrigues to return the number and type of an host alert you have to run this rest
`curl -s -v -u admin:admin "http://localhost:3000/lua/rest/v2/get/all/alert/list.lua?ifid=1&epoch_begin=1636631115&epoch_end=1667779200&host=192.168.1.1"`

To get then a specific type of alerts (e.g. flow alerts), run
`curl -s -v -u admin:admin "http://localhost:3000/lua/rest/v2/get/flow/alert/list.lua?ifid=1&epoch_begin=1636631115&epoch_end=1667779200&host=192.168.1.1"`

ecc.
Note: you can get only 1 alert type per request.
Change the -u option of curl correctly, with username:password

**Comment by PaoGRodrigues** [comment]
Thanks Matteo!
