### ISSUE TITLE
ntopng interface no longer listening, myricom packet capture clobbered

### ISSUE THREAD

**Issue by pnash01** [ntop/ntopng#697]
Hi all,
  Ntopng became unresponsive and took out the myricom interface along the way (e.g. every other packet sniffing application is now broken).   Here is the 'ps' output:

`nobody    1939     1  1939  9   15 Aug15 ?        04:39:12 /usr/local/bin/ntopng /etc/ntopng/ntopng.conf
nobody    1939     1  1953  7   15 Aug15 ?        03:55:19 /usr/local/bin/ntopng /etc/ntopng/ntopng.conf
nobody    1939     1  1954  0   15 Aug15 ?        00:00:05 /usr/local/bin/ntopng /etc/ntopng/ntopng.conf
nobody    1939     1  1955  0   15 Aug15 ?        00:09:37 /usr/local/bin/ntopng /etc/ntopng/ntopng.conf
nobody    1939     1  1956  0   15 Aug15 ?        00:09:34 /usr/local/bin/ntopng /etc/ntopng/ntopng.conf
nobody    1939     1  1957  0   15 Aug15 ?        00:09:25 /usr/local/bin/ntopng /etc/ntopng/ntopng.conf
nobody    1939     1  1958  0   15 Aug15 ?        00:09:47 /usr/local/bin/ntopng /etc/ntopng/ntopng.conf
nobody    1939     1  1959  0   15 Aug15 ?        00:09:33 /usr/local/bin/ntopng /etc/ntopng/ntopng.conf
nobody    1939     1  2222  1   15 Aug15 ?        00:34:35 /usr/local/bin/ntopng /etc/ntopng/ntopng.conf
nobody    1939     1  2223 50   15 Aug15 ?        1-01:12:54 /usr/local/bin/ntopng /etc/ntopng/ntopng.conf
nobody    1939     1  2224  0   15 Aug15 ?        00:00:11 /usr/local/bin/ntopng /etc/ntopng/ntopng.conf
nobody    1939     1  2225  0   15 Aug15 ?        00:00:07 /usr/local/bin/ntopng /etc/ntopng/ntopng.conf
nobody    1939     1  2226 42   15 Aug15 ?        21:10:03 /usr/local/bin/ntopng /etc/ntopng/ntopng.conf
nobody    1939     1  2228  0   15 Aug15 ?        00:00:18 /usr/local/bin/ntopng /etc/ntopng/ntopng.conf
nobody    1939     1  2229  0   15 Aug15 ?        00:00:18 /usr/local/bin/ntopng /etc/ntopng/ntopng.conf`

the ntopng.log contains the following:
`16/Aug/2016 09:00:01 [Lua.cpp:5041] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/hourly.lua][...ng/pro/scripts/lua/modules/top_scripts/top_aggregate.lua:110: attempt to index a nil value]
16/Aug/2016 09:18:40 [Lua.cpp:5420] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/get_from_top_talkers_db.lua][...ng/pro/scripts/lua/modules/top_scripts/top_aggregate.lua:110: attempt to index a nil value]
16/Aug/2016 10:00:00 [Lua.cpp:5041] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/hourly.lua][...ng/pro/scripts/lua/modules/top_scripts/top_aggregate.lua:110: attempt to index a nil value]
16/Aug/2016 10:07:21 [Lua.cpp:5041] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:114: mmaping file '/logstash/ntop-data/9/rrd/ShoutCast.rrd': Invalid argument]
16/Aug/2016 10:42:44 [Lua.cpp:5041] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:114: mmaping file '/logstash/ntop-data/9/rrd/ShoutCast.rrd': Invalid argument]
16/Aug/2016 10:57:07 [Lua.cpp:5041] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:114: mmaping file '/logstash/ntop-data/9/rrd/ShoutCast.rrd': Invalid argument]
16/Aug/2016 11:00:00 [Lua.cpp:5041] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/hourly.lua][...ng/pro/scripts/lua/modules/top_scripts/top_aggregate.lua:110: attempt to index a nil value]
16/Aug/2016 11:47:31 [Lua.cpp:5041] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:114: mmaping file '/logstash/ntop-data/9/rrd/ShoutCast.rrd': Invalid argument]
16/Aug/2016 12:00:01 [Lua.cpp:5041] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/hourly.lua][...ng/pro/scripts/lua/modules/top_scripts/top_aggregate.lua:110: attempt to index a nil value]
16/Aug/2016 12:37:00 [Lua.cpp:5041] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:114: mmaping file '/logstash/ntop-data/9/rrd/ShoutCast.rrd': Invalid argument]
16/Aug/2016 13:00:00 [Lua.cpp:5041] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/hourly.lua][...ng/pro/scripts/lua/modules/top_scripts/top_aggregate.lua:110: attempt to index a nil value]
16/Aug/2016 13:34:08 [Redis.cpp:937] ERROR: ERR command not allowed when used memory > 'maxmemory'
16/Aug/2016 14:00:00 [Lua.cpp:5041] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/hourly.lua][...ng/pro/scripts/lua/modules/top_scripts/top_aggregate.lua:110: attempt to index a nil value]`

**Comment by simonemainardi** [comment]
it looks like that the redis maxmemory limit has been reached.

```
16/Aug/2016 13:34:08 [Redis.cpp:937] ERROR: ERR command not allowed when used memory > 'maxmemory'
```

You should either raise the maximum redis memory from its configuration file, or be more conservative with memory usage from within ntopng (e.g., disable hosts dump and resolve only local ip addresses).

**Comment by lucaderi** [comment]
@simonemainardi This bug is the consequence of #712. No need to raise the memory, we need to play with valgrind.

**Comment by simonemainardi** [comment]
it is safe to close as #712 is fixed
