### ISSUE TITLE
new ifid is generated for the 'sub-interface' whose cusotm traffic disaggregation filter was edited successfully

### ISSUE THREAD

**Issue by 61swong** [ntop/ntopng#6971]
**Environment**:
* OS name: RHEL
* OS version: 7.9
* Architecture: x86_64
* ntopng version/revision: 5.4.221107

**What happened**:
I have Grafana dashboards for all the sub-interfaces.
After I successfully edited the custom traffic disaggregation filter for a sub-interface, the system generated a new ifid '4' when it was '5'.
I don't see any impacts yet on the ntopng web GUI but it broke my Grafana WAN link dashboards which depends on the ifid in the query. Workaround for me is to put an OR condition for the Influx query in the dashboard.

**How did you reproduce it?**
Edit another custom traffic disaggregation filter.

**Debug Information**:

**Comment by cardigliano** [comment]
@61swong did you change the filter only or also renamed the interface?

**Comment by 61swong** [comment]
@cardigliano I just renamed the interface.

**Comment by cardigliano** [comment]
@61swong the interface ID is tied to the interface name, as workaround I suggest to rename the interface to the previous name

**Comment by 61swong** [comment]
Thanks for your suggestion. I will keep it as it is with ifid=4 because the name rollback would not get my data back from ifid=4 to ifid=5 in the InfluxDB.

**Comment by MatteoBiscosi** [comment]
Hi @61swong it's an architectural problem this and it was designed in a way that whenever you change the name of the disaggregated interface, you create a new interface, so it's "unfixable" due the idea when it was created.
The thing I suggest is changing the interface settings and change the displayed name
![image](https://user-images.githubusercontent.com/49585191/202242627-79ee0776-d503-4b20-9c1a-e9f15b342fe0.png)

**Comment by 61swong** [comment]
Thanks for your confirmation. This would be a pity for people relying on the query to the InfluxDB.
