### ISSUE TITLE
Unable to ignore interfaces local to the nprobe host in collector mode

### ISSUE THREAD

**Issue by netravnen** [ntop/ntopng#6979]
**Environment**:
* OS name: Ubuntu
* OS version: 22.04.1 LTS
* Architecture: amd64
* ntopng version/revision: ntopng Professional v.5.5.221114

**Request**:

Be able to ignore local interfaces from the nprobe instance. (in the screenshot, `lo` and `eth0`)

**What happened**:

Using [Dynamic Disaggregation][0] results in a number of virtual interfaces being created. ✓

The resulting virtual interfaces counts against the total number of interfaces included in the license terms. (was a bit surprised, as I did not fully read this 'between the lines' from the license terms 😮 that virtual interfaces counted against the number of interfaces included in the license)

And being unable to ignore the local interfaces (`lo`, `ethX`) when using disaggregated interfaces in nprobe (collector mode) + ntopng is a bummer, as it "takes away" two "slots" that we want to use for virtual interfaces instead! 😮

![image](https://user-images.githubusercontent.com/1938389/201660849-2292a310-1ab5-4b01-bc09-971ebeca6e71.png)

Today, ntopng only allows for ignoring interfaces by SNMP ifIndex. Which is not useful in this instance, as the interfaces to be ignore are local to the host nprobe is installed on. :(

[0]: https://www.ntop.org/guides/ntopng/advanced_features/dynamic_interfaces_disaggregation.html#dynamic-disaggregation

**Comment by cardigliano** [comment]
@netravnen could you just remove "lo" and all the unneeded interfaces from ntopng.conf? I guess they are listed there

**Comment by netravnen** [comment]
🤬🤬🤬 I see your point!

(indeed the interfaces was listed in `/etc/ntopng/ntopng.conf` 🤦)

My mistake. 😊
