### ISSUE TITLE
ntopng / myricom  - MTU 

### ISSUE THREAD

**Issue by pnash01** [ntop/ntopng#698]
Hi all -
  I noticed that ntopng is claiming that the MTU for the myricom interface is 1514 bytes.  From what I've heard, the SNF enabled interfaces default to 9000 MTU.  Using ethtool on the 'ethX' representation of this interface (as opposed to the myri:A#P# interface) shows that it is set to 9000. 

Thanks,
 -Paul

**Comment by simonemainardi** [comment]
I guess we should go through the pf_ring settings in that case. This should fix the issue: https://github.com/simonemainardi/ntopng/commit/6b1948849d5a81bc307bb92440a43473768e8873

@cardigliano what do you think?

**Comment by cardigliano** [comment]
I added support for get_card_settings in the myricom module, it should work now.

Alfredo

**Comment by simonemainardi** [comment]
@pnash01 have you tried @cardigliano's contribution? can you please report on that. Thank you.

**Comment by lucaderi** [comment]
Closed for inactivity. Will reopen if necessary
