### ISSUE TITLE
Recipient Notification by Host Pools not working

### ISSUE THREAD

**Issue by joonasak** [ntop/ntopng#6980]
**Environment**:
* OS name: Ubuntu
* OS version: 22.04
* Architecture: amd64
* ntopng version/revision: 5.5.221114

**What happened**:
I configured the notification on recipient and selected only Host Pools that I wants to get notification from but it's not working.

**How did you reproduce it?**
When I choose Host Pools in recipient notification, it should get notification only from the Host Pools that I have chosen.

<img width="599" alt="image" src="https://user-images.githubusercontent.com/85352105/202394013-32b27fd1-7bc5-4bff-a375-573e1d8c661c.png">

**Comment by cardigliano** [comment]
@joonasak what is the alert type you are testing with the host pool filtering?

**Comment by joonasak** [comment]
@cardigliano I only select host pool which I created and it's still get all the alerts flow from other flow which not related to that host pool.

**Comment by cardigliano** [comment]
@joonasak this seems to be working in our lab, please drop an email to cardigliano at ntop.org to schedule a debug session

**Comment by cardigliano** [comment]
@joonasak any chance we can schedule a call and take a look to address this?

**Comment by joonasak** [comment]
Hi,

It's working now and maybe working after I reinstalled. Thank you.

Best regards,
Chansakada CHHEM

**Comment by cardigliano** [comment]
Thank you
