### ISSUE TITLE
Dropdown menus unusable with empty tables

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6981]
![Screen Shot 2022-11-17 at 18 40 00](https://user-images.githubusercontent.com/4493366/202518667-23aadcfd-5d0d-4066-933b-32830820f4a4.png)

**Comment by MatteoBiscosi** [comment]
The same thing happens in the new datatable

![image](https://user-images.githubusercontent.com/49585191/203578355-b4bed6af-49cd-4b15-bf32-3775235c868a.png)

**Comment by MatteoBiscosi** [comment]
Fixed in the latest version
![image](https://user-images.githubusercontent.com/49585191/210347569-ec591cf2-42a4-476c-bfb8-a9fb7e93e5db.png)
![image](https://user-images.githubusercontent.com/49585191/210347627-247bef52-85d6-4a70-a01b-1c821e4e9fa9.png)
