### ISSUE TITLE
Invalid ports percentage

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6983]
![Screen Shot 2022-11-19 at 10 35 55](https://user-images.githubusercontent.com/4493366/202844596-3a0b700f-7707-442e-bd3a-8dc41d1efbc0.png)

http://194.x.x.x.:3000/lua/host_details.lua?host=194.242.61.66&page=packets

**Comment by MatteoBiscosi** [comment]
Verified as Fixed
