### ISSUE TITLE
custom traffic disaggregation doesn't work for MAC address filter

### ISSUE THREAD

**Issue by 61swong** [ntop/ntopng#6985]
**Environment**:
* OS name: RHEL
* OS version: 7.9
* Architecture: x86_64
* ntopng version/revision: v5.5.221013

**What happened**:
I am using MAC address for custom traffic disaggregation and it doesn't work for me.
Below is the filter I'm using.
ether host 64:f6:9d:23:d0:ff or ether host a4:4c:11:6c:ac:3f

**How did you reproduce it?**
Deleted the filter, restarted ntopng, created the same filter, restarted ntopng.

**Debug Information**:
Filter for custom traffic disaggregation
![image](https://user-images.githubusercontent.com/50309519/203465356-89f325ab-bf07-4c93-bc20-791ce8a24728.png)

Interface home page for the sub-interface
![image](https://user-images.githubusercontent.com/50309519/203465487-176f06e3-f39d-4d2e-bdb8-975e35ab4613.png)

tcpdump on the ntopng host returned me the traffic with the MAC address  in the filter.
```
-bash-4.2$ sudo tcpdump -i et1 -nn ether host 64:f6:9d:23:d0:ff or ether host a4:4c:11:6c:ac:3f -x -c 1
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on et1, link-type EN10MB (Ethernet), snapshot length 262144 bytes
11:48:52.313738 IP 10.65.22.57.55620 > 10.244.20.31.2868: Flags [.], ack 1773933037, win 1022, length 0
        0x0000:  4500 0028 bb8b 4000 7f06 00b8 0a41 1639
        0x0010:  0af4 141f d944 0b34 1d1e d40e 69bc 11ed
        0x0020:  5010 03fe 1afb 0000 0000 0000 0000
1 packet captured
1 packet received by filter
0 packets dropped by kernel
```

**Comment by cardigliano** [comment]
Fixed, this will be available with the next nightly build
