### ISSUE TITLE
Browser freezes after 1 day on Dashboard

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#6988]
Browser freezes and stops responding if you leave a tab on the Dashboard for 1 day, it seems the chart library is exhausting the resources. Killing the browser is required to restore it (unable to close the tab). Reproduced on Firefox.

**Comment by uccidibuti** [comment]
The only thing that i can do it's replace the chart library with new Apex Chart but this requires a lot of time.

**Comment by lucaderi** [comment]
We decided to wait until the new dashboard
