### ISSUE TITLE
There are no some of networks that listed in -m=" " in conf file

### ISSUE THREAD

**Issue by ekbfh** [ntop/ntopng#699]
For ex:
m="net1,net2,net3,net4"
but in menu networks i can see only net1,net2,net4 and remote nets.

What can be wrong? It is write correctly.

ntopng Pro [Small Business Edition] v.2.5.160817

P.S. where i can ask why nbox web didn't working?

**Comment by lucaderi** [comment]
Can you please send me the exact networks so I can try to reproduce the issue?
What is the problem with the nBox?

**Comment by ekbfh** [comment]
I write a letter to your mail deri@
Thank you!

**Comment by ekbfh** [comment]
Any update?
The problem is still there in /ntopng_2.5.160826-1590_amd64.deb

**Comment by simonemainardi** [comment]
@ekbfh a network pops out in the network page only when some of its traffic is seen. So make sure  `net3` traffic is flowing through ntopng.

btw, what's wrong with the nbox?

**Comment by ekbfh** [comment]
@simonemainardi hosts from this network are in top local and even in alerts. Maybe some bug in network.lua? 
What cpu/memory i need to handle 100k hosts and 100k flows? Now it consumes about 3Gb RAM and ~33% of CPU(6 cores).

P.S. nbox didn't see ntopng, nprobe installations. Debian, all updates from packages.ntop.org

**Comment by ekbfh** [comment]
**Update**
I didn't see some of networks in list, but i can use links like http://url:3000/lua/hosts_stats.lua?network=3, where is 3 is number of the net.

**Comment by simonemainardi** [comment]
@ekbfh post the full ntopng configuration used or if you can't publish the addresses send it privately at mainardi ntop org

**Comment by lucaderi** [comment]
Closed for inactivity. Will reopen if necessary.
