### ISSUE TITLE
Invalid Link and Name for Chart Images

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6990]
In recent ntopng versions there is a new option that allows the chart to be downloaded as image

![image](https://user-images.githubusercontent.com/4493366/204220881-0a77b61f-decd-4835-b51b-ede6c604ec07.png)

There are a few issues to fix
- There is a typo in "Downlod"
![image](https://user-images.githubusercontent.com/4493366/204221023-c9af9419-163d-49fd-91bf-10e6dde55725.png)
- The file name should not have spaces or other forbidden chars such as / \, $, " ....
- The URL for downloading the chart offline (e.g. via curl) is not available and it must be implemented

**Comment by lucaderi** [comment]
The fix is suboptimal because you should replace spaces (or similar charts) with _ or - as zapping space makes rhe filename unreadeable
![Screen Shot 2022-12-18 at 10 03 35](https://user-images.githubusercontent.com/4493366/208289803-41c3d019-3457-45f4-a853-fe57d27c5a21.png)

**Comment by uccidibuti** [comment]
I replaced all space and '-' with _ and all others special characters with empty char.

**Comment by lucaderi** [comment]
Verified as fixed
