### ISSUE TITLE
unable to locate nprobe

### ISSUE THREAD

**Issue by Ogenkii** [ntop/ntopng#6991]
pi@NetworkPi:/opt $ sudo wget https://packages.ntop.org/RaspberryPI/apt-ntop.deb
--2022-11-29 05:17:33--  https://packages.ntop.org/RaspberryPI/apt-ntop.deb
Resolving packages.ntop.org (packages.ntop.org)... 167.99.215.164, 2a03:b0c0:2:d0::d27:3001
Connecting to packages.ntop.org (packages.ntop.org)|167.99.215.164|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3226 (3.2K) [application/x-debian-package]
Saving to: ‘apt-ntop.deb.2’

apt-ntop.deb.2                 100%[==================================================>]   3.15K  --.-KB/s    in 0s

2022-11-29 05:17:35 (7.09 MB/s) - ‘apt-ntop.deb.2’ saved [3226/3226]

pi@NetworkPi:/opt $ sudo dpkg -i apt-ntop.deb.2
dpkg: warning: downgrading apt-ntop from 2.9-24 to 2.9-16
(Reading database ... 51897 files and directories currently installed.)
Preparing to unpack apt-ntop.deb.2 ...
Unpacking apt-ntop (2.9-16) over (2.9-24) ...
upgrade
Setting up apt-ntop (2.9-16) ...
Installing ntop GPG key. Please wait...
gpg: key 3D84C955924F7599: "Luca Deri <deri@ntop.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
pi@NetworkPi:/opt $ sudo apt-get update
Hit:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:3 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:4 http://archive.raspbian.org/raspbian stretch InRelease
Hit:5 https://packages.ntop.org/apt/bullseye_pi armhf/ InRelease
Hit:6 https://packages.ntop.org/apt/bullseye_pi all/ InRelease
Hit:1 https://dl.ubnt.com/unifi/debian stable InRelease
Reading package lists... Done
pi@NetworkPi:/opt $ sudo apt-get install ntopng nprobe n2n
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package nprobe
pi@NetworkPi:/opt $

**Comment by cardigliano** [comment]
@Ogenkii please note we provide packages for the 64-bit (arm64) version of raspbian based on bullseye only
