### ISSUE TITLE
Sankey Flow Chart Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6993]
The flow snaky chart is broken as you can see in the image below

![Screen Shot 2022-11-30 at 08 44 24](https://user-images.githubusercontent.com/4493366/204736970-69ace2be-592a-45f6-9902-85d436d07c75.png)

Open issues
- add a dropdown menu (similar to host maps) where are listed a few options such as "All Flows", "Incoming Flows", "Outgoing Flows"
- if there are no flows to report, the page cannot be empty (as it can appear as a bug) but a message has to report this
- nodes/edges of the chart mus be clickable (where it makes sense) to enable data navigation

**Comment by lucaderi** [comment]
Not yet working (e.g. on Safari)

**Comment by MatteoBiscosi** [comment]
Fixed

**Comment by lucaderi** [comment]
Verified as fixed
