### ISSUE TITLE
User Add Form not Empty

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6996]
When clicking on "Add User" the form is not empty as it should but it has some old values. This needs to be fixed.

![Screen Shot 2022-12-01 at 21 37 04](https://user-images.githubusercontent.com/4493366/205154593-8387299e-5d99-4623-a3b8-799b01d42bdf.png)

**Comment by MatteoBiscosi** [comment]
Fixes, dev version

**Comment by MatteoBiscosi** [comment]
Verified as fixed
