### ISSUE TITLE
ERROR: Unable to start HTTP server (ntopng version v.1.99.150505)

### ISSUE THREAD

**Issue by atin001** [ntop/ntopng#7]
Reopening issue #2 

Pulled latest code from git and tried to start ntopng. However it still fails to start

[root@ucf2b-docs-psr0427-ms1 paasusr]# /usr/local/bin/ntopng --version
v.1.99.150505

[root@ucf2b-docs-psr0427-ms1 paasusr]# /usr/local/bin/ntopng
05/May/2015 08:44:23 [src/Ntop.cpp:779] Setting local networks to 192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,127.0.0.0/8,0.0.0.0/32,224.0.0.0/8,239.0.0.0/8,255.255.255.255/32,127.0.0.0/8
05/May/2015 08:44:23 [src/Redis.cpp:93] Successfully connected to Redis 127.0.0.1:6379@0
05/May/2015 08:44:23 [src/main.cpp:201] ERROR: Startup error: missing super-user privileges ?

[root@ucf2b-docs-psr0427-ms1 paasusr]# /usr/local/bin/ntopng -i eth0
05/May/2015 08:44:43 [src/Ntop.cpp:779] Setting local networks to 192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,127.0.0.0/8,0.0.0.0/32,224.0.0.0/8,239.0.0.0/8,255.255.255.255/32,127.0.0.0/8
05/May/2015 08:44:43 [src/Redis.cpp:93] Successfully connected to Redis 127.0.0.1:6379@0
05/May/2015 08:44:43 [src/PcapInterface.cpp:81] Reading packets from interface eth0...
05/May/2015 08:44:43 [src/Ntop.cpp:1027] Registered interface view eth0 [id: 0]
05/May/2015 08:44:43 [src/Ntop.cpp:997] Registered interface eth0 [id: 0]
05/May/2015 08:44:43 [src/Utils.cpp:277] User changed to nobody
05/May/2015 08:44:43 [src/main.cpp:227] PID stored in file /var/tmp/ntopng.pid
05/May/2015 08:44:43 [src/HTTPserver.cpp:449] HTTPS Disabled: missing SSL certificate /usr/local/share/ntopng/httpdocs/ssl/ntopng-cert.pem
05/May/2015 08:44:43 [src/HTTPserver.cpp:451] Please read https://svn.ntop.org/svn/ntop/trunk/ntopng/README.SSL if you want to enable SSL.
05/May/2015 08:44:43 [src/HTTPserver.cpp:486] ERROR: Unable to start HTTP server (IPv4) on ports 3000

[root@ucf2b-docs-psr0427-ms1 paasusr]# /usr/local/bin/ntopng -i eth0 -w 3060
05/May/2015 08:44:49 [src/Ntop.cpp:779] Setting local networks to 192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,127.0.0.0/8,0.0.0.0/32,224.0.0.0/8,239.0.0.0/8,255.255.255.255/32,127.0.0.0/8
05/May/2015 08:44:49 [src/Redis.cpp:93] Successfully connected to Redis 127.0.0.1:6379@0
05/May/2015 08:44:49 [src/PcapInterface.cpp:81] Reading packets from interface eth0...
05/May/2015 08:44:49 [src/Ntop.cpp:1027] Registered interface view eth0 [id: 0]
05/May/2015 08:44:49 [src/Ntop.cpp:997] Registered interface eth0 [id: 0]
05/May/2015 08:44:49 [src/Utils.cpp:277] User changed to nobody
05/May/2015 08:44:49 [src/main.cpp:227] PID stored in file /var/tmp/ntopng.pid
05/May/2015 08:44:49 [src/HTTPserver.cpp:449] HTTPS Disabled: missing SSL certificate /usr/local/share/ntopng/httpdocs/ssl/ntopng-cert.pem
05/May/2015 08:44:49 [src/HTTPserver.cpp:451] Please read https://svn.ntop.org/svn/ntop/trunk/ntopng/README.SSL if you want to enable SSL.
05/May/2015 08:44:49 [src/HTTPserver.cpp:486] ERROR: Unable to start HTTP server (IPv4) on ports 3060

OS version is 2.6.39-400.109.6.el6uek.x86_64

[root@ucf2b-docs-psr0427-ms1 paasusr]# ifconfig
eth0      Link encap:Ethernet  HWaddr C6:B0:3D:21:E4:CA
          inet addr:10.241.239.42  Bcast:10.241.239.43  Mask:255.255.255.252
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:47709210 errors:0 dropped:4 overruns:0 frame:0
          TX packets:45548955 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:42809387833 (39.8 GiB)  TX bytes:42008874445 (39.1 GiB)
          Interrupt:80

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:2132 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2132 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:178372 (174.1 KiB)  TX bytes:178372 (174.1 KiB)

**Comment by chris4269** [comment]
or you can find the log

**Comment by ariava** [comment]
Commit b72bba5 should work around this issue. @atin001 could you please verify whether it now works with the latest GitHub code?

**Comment by atin001** [comment]
@ariava Tried to build from source and install again but facing issues. Here are the steps I followed
1)  git clone https://github.com/ntop/ntopng.git
2) cd ntopng/
3) ./autogen.sh
4) ./configure
5) cd ..; git clone https://github.com/ntop/nDPI.git; cd nDPI; ./autogen.sh; make; cd ../ntopng
6) ./configure
7) /usr/bin/gmake

Here are the errors in make step
Making all in tests
gmake[3]: Entering directory `/home/paasusr/ntopng/third-party/json-c/tests'
gmake[3]: Nothing to be done for `all'.
gmake[3]: Leaving directory `/home/paasusr/ntopng/third-party/json-c/tests'
gmake[2]: Leaving directory `/home/paasusr/ntopng/third-party/json-c'
gmake[1]: Leaving directory `/home/paasusr/ntopng/third-party/json-c'
g++ -g -Wall  -I/usr/local/include -I /home/paasusr/ntopng/third-party/hiredis -I/home/paasusr/ntopng/third-party/mongoose -I/home/paasusr/ntopng/third-party/json-c -I../nDPI/src/include -I/home/paasusr/ntopng/third-party/LuaJIT-2.0.3/src -I/home/paasusr/ntopng/third-party/rrdtool-1.4.8/src/ -I/home/paasusr/ntopng/third-party/zeromq-4.0.5/include  -I/usr/local/include -I/home/paasusr/ntopng/third-party/http-client-c/src/ -I/home/paasusr/ntopng/third-party/EWAHBoolArray/headers  -DDATA_DIR='"/usr/local/share"'    -c src/ActivityStats.cpp -o src/ActivityStats.o
src/ActivityStats.cpp:22:27: error: ntop_includes.h: No such file or directory
src/ActivityStats.cpp:27: error: âActivityStatsâ has not been declared
src/ActivityStats.cpp:27: error: expected constructor, destructor, or type conversion before â(â token
src/ActivityStats.cpp:44: error: expected constructor, destructor, or type conversion before â::â token
src/ActivityStats.cpp:50: error: âActivityStatsâ has not been declared
src/ActivityStats.cpp: In function âvoid reset()â:
src/ActivityStats.cpp:51: error: âmâ was not declared in this scope
src/ActivityStats.cpp:52: error: âbitsetâ was not declared in this scope
src/ActivityStats.cpp:53: error: âlast_set_timeâ was not declared in this scope
src/ActivityStats.cpp: At global scope:
src/ActivityStats.cpp:60: error: âActivityStatsâ has not been declared
src/ActivityStats.cpp:60: error: variable or field âsetâ declared void
src/ActivityStats.cpp:60: error: âtime_tâ was not declared in this scope
gmake: *** [src/ActivityStats.o] Error 1

**Comment by lucaderi** [comment]
try again now

**Comment by atin001** [comment]
Yup. Working now!
Thanks @lucaderi @ariava
