### ISSUE TITLE
Depreciated message Kernel module error in /var/log/messages when starting service

### ISSUE THREAD

**Issue by crwdawg** [ntop/ntopng#70]
Scientific Linux (RHEL clone)
Jul  3 06:54:55 lnx-br01-s1 kernel: Loading kernel module for a network device with CAP_SYS_MODULE (deprecated).  Use CAP_NET_ADMIN and alias netdev-. instead.

**Comment by lucaderi** [comment]
@crwdawg Why are you asking this to us? This does not look a ntopng issue
