### ISSUE TITLE
Alerts: Honour Custom VLAN Names

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7000]
If a VLAN (Hosts -> VLANs) have symbolic names, they must be honoured in alerts and historical flows

![image](https://user-images.githubusercontent.com/4493366/205284191-7fb76dbd-33c1-4cda-9771-9975b99285c7.png)

**Comment by MatteoBiscosi** [comment]
The issue should be fixed for both alerts and historical
![image](https://user-images.githubusercontent.com/49585191/210254068-5f5cd83b-7395-4972-9228-7896bb205201.png)
![image](https://user-images.githubusercontent.com/49585191/210254116-89fb7455-4f56-4cd9-814d-5df3b36e2b65.png)

**Comment by lucaderi** [comment]
Verified as fixed
