### ISSUE TITLE
Invalid custom traffic disaggregation filter with 'ether host xx:xx:xx:xx:xx:xx'

### ISSUE THREAD

**Issue by 61swong** [ntop/ntopng#7001]
**Environment**:
* OS name: RHEL
* OS version: 7.9
* Architecture: x86_86
* ntopng version/revision: v5.4.221129

**What happened**:
I tried to create a custom traffic disaggregation filter with 'ether host ac:4a:67:7b:f3:7c' with Sub-Interface Name 'test'.
The system returned 'Invalid filter'.

**How did you reproduce it?**
I restarted ntopng and did the same changes.

**Debug Information**:
![image](https://user-images.githubusercontent.com/50309519/205547344-5091fcb4-1e30-4397-923d-c9caf22c9143.png)

**Comment by cardigliano** [comment]
This is supported on ntopng 5.5 dev

**Comment by 61swong** [comment]
Thanks for your confirmation.
