### ISSUE TITLE
Too many authentication attempts does not expire

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#7002]
It seems that the "Too many authentication attempts" message does not expire after a few minutes as expected and persists for days preventing the user from logging in. Please verify.

<img width="497" alt="Screen Shot 2022-12-05 at 11 24 47" src="https://user-images.githubusercontent.com/7548711/205614087-3c641313-7507-42bc-bfef-a31df7bf033b.png">

**Comment by MatteoBiscosi** [comment]
In the latest ntopng dev version this issue is fixed
