### ISSUE TITLE
Hide Non-Existing Timeseries

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7010]
In the host dropdown menu must of the timeseries do not exist

![Screen Shot 2022-12-06 at 12 35 22](https://user-images.githubusercontent.com/4493366/205901209-e9a2159a-8752-4db9-ade6-d5a635e46b9e.png)

For users it is frustrating to access a long menu where most of the entries do not exist. Possible solutions
- hide timeseries that do not exist
- if the above is a problem, hide at least timeseries not compatible with the configuration. For instance if you have set timeseries to "Light" in preferences, do not display timeseries fo nDPI that will not exist for sure

**Comment by uccidibuti** [comment]
The list of metrics available is provided by REST api ntopng/scripts/lua/rest/v2/get/timeseries/type/consts.lua.

**Comment by MatteoBiscosi** [comment]
Fixed as requested

**Comment by lucaderi** [comment]
Verified as fixed
