### ISSUE TITLE
Add fixed sorting for traffic profiles page in interface

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#7014]
ntopng Enterprise L v.5.4.221129

**What happened**:
Is it possible to add fixed A-Z sorting for traffic profiles page in interface.
On each refresh the table is populated randomly.

![image](https://user-images.githubusercontent.com/67421019/205922501-e1f76383-2382-410e-9d83-4256d04933fe.png)

**How did you reproduce it?**
Refresh a couple of times traffic profiles page:
https://###ntopng###/lua/if_stats.lua?ifid=###if_id###&page=trafficprofiles

**Comment by MatteoBiscosi** [comment]
Hi @atemix a new build should be available soon, the issue should be fixed in the next build

**Comment by atemix** [comment]
@MatteoBiscosi After upgrading to 5.4.230112 still random order in traffic profiles page (.../lua/if_stats.lua?ifid=0&page=trafficprofiles)

**Comment by lucaderi** [comment]
This has been implemented in the dev branch and not on the stable one you are using. Next week we'll release a new stable that includes the fix
