### ISSUE TITLE
Missing top SNMP for Top Table

### ISSUE THREAD

**Issue by uccidibuti** [ntop/ntopng#7018]
The rest API  /lua/pro/rest/v2/get/snmp/top/ts_stats.lua must be implemented in the same way of /lua/pro/rest/v2/get/interface/top/ts_stats.lua .

**Comment by MatteoBiscosi** [comment]
Fixed, pro repo

**Comment by lucaderi** [comment]
@MatteoBiscosi Interface name is missing

**Comment by NicoMaio** [comment]
Verified the implementation.
