### ISSUE TITLE
How to display current configurations for ntopng?

### ISSUE THREAD

**Issue by webernetz** [ntop/ntopng#702]
Hey guys,
how can I display the current running (default) configurations for ntopng?
I am getting the following alert: "Interface eth1 has too many hosts. Please extend the --max-num-hosts/-x command line option." But before I am fine-tuning this options, I would like to know what the default values are.

I am searching for something like "postconf" that shows all settings for postfix, or the like. Does something similar exists for ntopng?

Thanks!

**Comment by Niko78** [comment]
hi
in user guide

[--max-num-hosts|-x] <num> | Max number of active hosts
| (default: 65536)

nico

**Comment by lucaderi** [comment]
@webernetz We do not have this capability. All we can offer you is to see with ntopng -h the defaults values, and at runtime from the home menu the command line option you have sent on CLI
