### ISSUE TITLE
Action Button Disappearing from Notifications

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7020]
In the notifications window, the action button disappears (e.g. on tablets) unless the screen is large.

While other statistical columns can be omitted, the Action button must show all the time. This needs to be fixed. Please also check if other windows have the same problem.

![Screen Shot 2022-12-07 at 10 09 38](https://user-images.githubusercontent.com/4493366/206136732-fafeb8dd-54b5-49ef-81a8-8114a5dd5ead.png)
![Screen Shot 2022-12-07 at 10 09 29](https://user-images.githubusercontent.com/4493366/206136742-b503a7f6-6813-43dd-8c1b-934fb9f599b4.png)

**Comment by MatteoBiscosi** [comment]
The issue should be fixed now
![image](https://user-images.githubusercontent.com/49585191/206139085-41fc0423-21c4-4022-ae2d-24759cac7cbe.png)

**Comment by lucaderi** [comment]
This problem is fixed in notifications but not on the peer page Notifications.

**Comment by MatteoBiscosi** [comment]
Fixed in the endpoint page too. Please report if any other cases are found.
![image](https://user-images.githubusercontent.com/49585191/208473254-687d0285-6dea-4560-8c3d-c08e34bf0509.png)

**Comment by lucaderi** [comment]
Verified as fixed
