### ISSUE TITLE
issues with assigning application to category under Setting > 'Applications and Categories'

### ISSUE THREAD

**Issue by 61swong** [ntop/ntopng#7024]
**Environment**:
* OS name: RHEL
* OS version: 7.9
* Architecture: x86_64
* ntopng version/revision: 5.5.221206

**What happened**:
I have 15 applications defined in the protocols.txt.
Under settings > applications and categories, I assigned them to different custom categories.
When I clicked 'save settings' button, the screen showed nothing in the table.
I clicked 'Apps' for a refresh and found only one application is saved correctly. One was put in a wrong category 'Network' and reest of them unchanged.
I did my change once again and I got:
* one more application into the correct custom category (i.e. 2 in total)
* the application previously put into the wrong category 'Network' is again put into 'Network' category.
I did my change another time and I got:
* one more application into the correct custom category (i.e. 3 in total)
* the application previuosly put into the wrong category 'Network' is still into 'Network' category.

**How did you reproduce it?**
Just do the change again.

**Debug Information**:
screenshots can be provided by email if needed.

**Comment by MatteoBiscosi** [comment]
Hi @61swong the issue should be fixed, a new build should be available in a couple of hours, please update and let me know

**Comment by 61swong** [comment]
Thanks @MatteoBiscosi for the fix. I can't test the fix because of the change freeze in my company. I closed this issue first.
