### ISSUE TITLE
pfSense - No connectivity detected, ntopng will run in offline mode

### ISSUE THREAD

**Issue by thealphabonanza** [ntop/ntopng#7025]
Environment
* OS name: pfSense
* OS version: 22.05-RELEASE
* Architecture: amd64
* ntopng version/revision: ntopng Community v.5.2.221116 rev.0 (FreeBSD 12.3)

What happened:
Using the package manager, installed ntopng on a Netgate 4100 running running pfSense.
If I choose the WAN interface ntopng works as expected.
If I choose either LAN or WAN and LAN interfaces, the ntopng does not start.
If I then choose just the WAN interface again, it runs as expected again.

**How did you reproduce it?**
In GUI, go to 
Diagnostics: ntopng Settings
Change the interface setting to either LAN, WAN or WAN and LAN.

**Debug Information**:
Paste debug information below:
Logs taken from pfSense System/General
2022-12-08 21:51:16.172044+11:00 	ntopng 	62113 	[boot.lua:23] WARNING: No connectivity detected, ntopng will run in offline mode
2022-12-08 21:51:18.255155+11:00 	kernel 	- 	pid 62312 (ntopng), jid 0, uid 0: exited on signal 6 (core dumped)

**Comment by cardigliano** [comment]
@thealphabonanza are you getting a "No connectivity detected" only when running on LAN (or WAN+LAN), or also when running on WAN only? 
Please note that ntopng does an HTTP GET https://github.com by default to check connectivity (the URL can be changed from settings), this should not depend on the capture interface, which is strange.

**Comment by thealphabonanza** [comment]
HiAs mentioned, WAN by itself works correctly. The problem is when you choose LAN by itself or both LAN and WAN together, the page times out. Martin 
-------- Original message --------From: "Alfredo Cardigliano - notifications at github.com" ***@***.***> Date: 9/12/22  19:39  (GMT+10:00) To: "ntop/ntopng - ntopng at noreply.github.com" ***@***.***> Cc: thealphabonanza ***@***.***>, "Mention - mention at noreply.github.com" ***@***.***> Subject: Re: [ntop/ntopng] pfSense - No connectivity detected, ntopng will run in offline mode (Issue #7025) 
@thealphabonanza are you getting a "No connectivity detected" only when running on LAN (or WAN+LAN), or also when running on WAN only?
Please note that ntopng does an HTTP GET https://github.com by default to check connectivity (the URL can be changed from settings), this should not depend on the capture interface, which is strange.

**Comment by cardigliano** [comment]
I was trying to understand if the core dump depends on the offline mode or not in practice

**Comment by MatteoBiscosi** [comment]
Hi @thealphabonanza please update to the latest ntopng version, you are currently running the ntopng 5.2 version.
Please update to the 5.4 (stable) or 5.5 (dev)

**Comment by thealphabonanza** [comment]
Hi,I was running the version that the Netgate package manager installs. I have since found a post in their forum explaining how to install the latest version. I have done that and now it works. The package that netgate installs needs to be updated, not sure who does that. ThanksMartin 
-------- Original message --------From: "Matteo Biscosi - notifications at github.com" ***@***.***> Date: 12/12/22  20:49  (GMT+10:00) To: "ntop/ntopng - ntopng at noreply.github.com" ***@***.***> Cc: thealphabonanza ***@***.***>, "Mention - mention at noreply.github.com" ***@***.***> Subject: Re: [ntop/ntopng] pfSense - No connectivity detected, ntopng will run in offline mode (Issue #7025) 
Hi @thealphabonanza please update to the latest ntopng version, you are currently running the ntopng 5.2 version.
Please update to the 5.4 (stable) or 5.5 (dev)
