### ISSUE TITLE
Raspberry Pi 3B: using Raspi OS 32-bit the binaries are missing. Please add.

### ISSUE THREAD

**Issue by adb336** [ntop/ntopng#7028]
Fill 32-bit repository for Raspberry Pi 3B with binaries:

Actually when I follow install procedures mentioned on the Download web-page I only get

`#  grep ^Package packages.ntop.org_apt_bullseye%5fpi_a*`
packages.ntop.org_apt_bullseye%5fpi_all_Packages:Package: ntopng-data

So all other binaries are missing.

I use Raspberry Pi in order to help my community:

Based on a project "raspion" = rasp-spy suggested from Heise Verlag in Germany I am helping my community to find out about IoT devices blurping to much data somewhere into the internet. Based upon the test results we agree then to use appropriate steps like establishing pihole and other tools.

This is not a commercial service!

**Comment by lucaderi** [comment]
We are migrating towards 64 bit PiOS so the only 32 bit packages we build are available on packages.ntop.org. If you need additional packages please compile ntopng from source
