### ISSUE TITLE
Top hosts missing on short time periods

### ISSUE THREAD

**Issue by dan2716430** [ntop/ntopng#703]
When generating reports, only Network Interfaces, Local/Remote, Applications and Application Breakdown are displayed. Missing Top Local and Remote Hosts.
This is valid for reports for last hour and last day. Last week seems to be fine.

Ntopng Pro 2.5.160821, running  on Debian 8.

ntopng --pid "/var/run/ntopng.pid" --interface "tcp://127.0.0.1:5556" --data-dir "/var/tmp" --http-port "3000" --local-networks "1.2.3.0/16"

nprobe --collector-port 6343 --zmq tcp://127.0.0.1:5556 -T "%IPV4_SRC_ADDR %IPV4_DST_ADDR %INPUT_SNMP %OUTPUT_SNMP %IN_PKTS %IN_BYTES %FIRST_SWITCHED %LAST_SWITCHED %L4_SRC_PORT %L4_DST_PORT %TCP_FLAGS %PROTOCOL %EXPORTER_IPV4_ADDRESS" >> /dev/null &

![2016-08-21 21_50_52-welcome to ntopng](https://cloud.githubusercontent.com/assets/20684284/17839221/32575780-67ea-11e6-9e51-948f1cc9d123.png)

**Comment by dan2716430** [comment]
Switched to stable (2.4.160818), deleted all history.

Same problem.

**Comment by pnash01** [comment]
I'm curious - when you look at the runtime stats, do you see any Lua errors? I posted a similar bug, and I think it is based on some aggregation scripts that are receiving null values when they expect to find something.

**Comment by lucaderi** [comment]
Hi all, Simone will look at this problem once back from holidays (later this week). Be patient.

**Comment by pnash01** [comment]
No worries – I stop/re-start the service throughout the day and is remains stable.

-Paul

**Comment by dan2716430** [comment]
Yes, there were some errors logged every 5 minutes:
24/Aug/2016 03:30:02 [Lua.cpp:4755] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:195: '/var/tmp/0/rrd/1/2/3/4/bytes.rrd' is not an RRD file]

From the stable branch of a professional version, when I get a report of network issues I expect to:
- ideally: get a list of top talkers
- at least: get a line saying: could not display top hosts because of the following error

Having the useful half of the report simply disappear is annoying at least.

**Comment by simonemainardi** [comment]
@dan2716430 we have reworked some parts of the code, including the aggregation scripts. The new build is in progress. Please, wait at least an hour for its completion and try that out.

However, from the screenshot you posted, it looks like data collection stopped at around 21:18. As that kind of data is updated every 5 minutes, the error you reported:

```
24/Aug/2016 03:30:02 [Lua.cpp:4755] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:195: '/var/tmp/0/rrd/1/2/3/4/bytes.rrd' is not an RRD file]
```

may be related.

Apparently, the file bytes.rrd is corrupted as it is not recognized as being an RRD file. I would recommend starting over using a different directory (e.g.g, /var/tmp/ntopng). If the error still comes out, please, share the file that is claimed as not being an RRD.

**Comment by dan2716430** [comment]
I've sent you an email with the latest RRD.

**Comment by simonemainardi** [comment]
the file you sent me is clearly corrupted:

```
Simones-MacBook-Pro:Downloads simone$ file bytes.rrd
bytes.rrd: data
Simones-MacBook-Pro:Downloads simone$ hexdump bytes.rrd
0000000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
0001000 00 00 00 00 00 00 f8 ff 00 00 00 00 00 00 f8 ff
*
0008000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
0009000 00 00 00 00 00 00 f8 ff 00 00 00 00 00 00 f8 ff
*
0025ca0
```

however, by looking at the path sent along with the RRD, it looks like you didn't start over on a different directory. please do as suggested.

**Comment by simonemainardi** [comment]
after logging and working on @dan2716430 machine I can confirm that the issue is solved now. Reports are properly shown for any time interval.

**Comment by dan2716430** [comment]
Can you please login again? The problem is back.

The log is filled with this:
02/Sep/2016 14:45:04 [Lua.cpp:5041] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:186: '/var/tmp/ntopng/0/rrd/Megaco.rrd' is not an RRD file]
02/Sep/2016 14:40:04 [Lua.cpp:5041] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:186: '/var/tmp/ntopng/0/rrd/Megaco.rrd' is not an RRD file]
02/Sep/2016 14:35:03 [Lua.cpp:5041] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:186: '/var/tmp/ntopng/0/rrd/Megaco.rrd' is not an RRD file]
02/Sep/2016 14:30:04 [Lua.cpp:5041] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:186: '/var/tmp/ntopng/0/rrd/Megaco.rrd' is not an RRD file]
02/Sep/2016 14:25:04 [Lua.cpp:5041] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:186: '/var/tmp/ntopng/0/rrd/Megaco.rrd' is not an RRD file]
02/Sep/2016 14:20:04 [Lua.cpp:5041] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/callbacks/minute.lua:186: '/var/tmp/ntopng/0/rrd/Megaco.rrd' is not an RRD file]

**Comment by dan2716430** [comment]
Still the same problem. No errors now in the log.
![2016-09-05 16_19_44-welcome to ntopng](https://cloud.githubusercontent.com/assets/20684284/18249061/b29f4664-7384-11e6-807a-86020107108b.png)

**Comment by simonemainardi** [comment]
@dan2716430 I'm working on that I'm on your machine

**Comment by simonemainardi** [comment]
@dan2716430 please check now.
