### ISSUE TITLE
Extend Historical Flow Filtering

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7032]
There are several fields saved in the Historical Flows JSON field, that need to be searched in particular during investigations. Example
- search http.last_server = XXXXX
- search protos.tls.issuerDN = YYYY

As those fields are not individual columns, the search might take longer but they are useful for many people.

**Comment by cardigliano** [comment]
Notes:
1. The data type for the current json column is a String, which prevents using the transparent clickhouse notation for accessing JSON properties. visitParam* functions should still work, but they are not convenient.
2. An optional/additional "ndpi json" column should be added (with JSON data type) containing the json generated by nDPI to allow queries on the full data. A preference should be added for this (disabled by default).

**Comment by lucaderi** [comment]
Unable to find the requested field listed in the ticket (e.g. issuer)

<img width="828" alt="Screenshot 2023-08-03 at 12 45 06" src="https://github.com/ntop/ntopng/assets/4493366/c1c9ebab-55a6-4e99-ad8f-d3f84e201046">

**Comment by NicoMaio** [comment]
Implemented in the PRO repo with f310625f7d00d5bb7f68d7c181239c11b8b3c0d6
