### ISSUE TITLE
Ntopng KO with clickhouse export

### ISSUE THREAD

**Issue by Danifilth89** [ntop/ntopng#7037]
Hi,

I actually have a Ntopng with those parameters which works fine :
- Distribution on Ubuntu 20.04
- Ntopng version 5.5.221129
- Licence Entreprise M 

To have to some historical flow, I installed clickhouse and activated it in ntop configuration file : 

root@NTOP:~# service clickhouse-server status
● clickhouse-server.service - ClickHouse Server
     Loaded: loaded (/lib/systemd/system/clickhouse-server.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-12-15 11:10:10 CET; 3h 37min ago
   Main PID: 816 (clickhouse-serv)
      Tasks: 33 (limit: 4577)
     Memory: 81.3M
     CGroup: /system.slice/clickhouse-server.service
             └─816 /usr/sbin/clickhouse-server --config=/etc/clickhouse-server/config.xml

déc. 15 11:10:10 NTOP systemd[1]: Started ClickHouse Server.
déc. 15 11:10:12 NTOP clickhouse-server[816]: Include not found: clickhouse_remote_servers
déc. 15 11:10:12 NTOP clickhouse-server[816]: Include not found: clickhouse_compression
déc. 15 11:10:13 NTOP clickhouse-server[816]: Logging warning to /var/log/clickhouse-server/clickhouse-server.log
déc. 15 11:10:13 NTOP clickhouse-server[816]: Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
déc. 15 11:10:13 NTOP clickhouse-server[816]: Include not found: networks
déc. 15 11:10:13 NTOP clickhouse-server[816]: Include not found: networks
déc. 15 11:10:15 NTOP clickhouse-server[816]: Include not found: clickhouse_remote_servers
déc. 15 11:10:15 NTOP clickhouse-server[816]: Include not found: clickhouse_compression

vi /etc/ntopng/ntopng.conf : 
-e=
-i=ens192
-w=3000
-F "clickhouse;127.0.0.1@9000;ntopng;default;default"

Then I restarted ntopng and it's ok : 

root@NTOP:~# systemctl status ntopng
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
     Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-12-15 14:48:16 CET; 15s ago
    Process: 21186 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (>
    Process: 21200 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
    Process: 21202 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (code=exited, status=0/SUCC>
    Process: 21204 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /run/ntopng.conf (c>
   Main PID: 21206 (ntopng)
      Tasks: 13 (limit: 4577)
     Memory: 43.6M
     CGroup: /system.slice/ntopng.service
             └─21206 /usr/bin/ntopng /run/ntopng.conf

déc. 15 14:48:17 NTOP ntopng[21206]: 15/Dec/2022 14:48:17 [Ntop.cpp:2586] Registered interface ens192 [id: 4]
déc. 15 14:48:17 NTOP ntopng[21206]: 15/Dec/2022 14:48:17 [main.cpp:352] PID stored in file /var/run/ntopng.pid
déc. 15 14:48:17 NTOP ntopng[21206]: 15/Dec/2022 14:48:17 [Geolocation.cpp:149] Loaded database dbip-asn-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip-a>
déc. 15 14:48:17 NTOP ntopng[21206]: 15/Dec/2022 14:48:17 [Geolocation.cpp:149] Loaded database dbip-city-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip->
déc. 15 14:48:17 NTOP ntopng[21206]: 15/Dec/2022 14:48:17 [Geolocation.cpp:95] Using geolocation provided by DB-IP (https://db-ip.com)
déc. 15 14:48:17 NTOP ntopng[21206]: 15/Dec/2022 14:48:17 [HTTPserver.cpp:1408] Found TLS certificate /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem
déc. 15 14:48:17 NTOP ntopng[21206]: 15/Dec/2022 14:48:17 [HTTPserver.cpp:1683] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
déc. 15 14:48:17 NTOP ntopng[21206]: 15/Dec/2022 14:48:17 [HTTPserver.cpp:1686] HTTP server listening on 3000
déc. 15 14:48:17 NTOP ntopng[21206]: 15/Dec/2022 14:48:17 [Utils.cpp:800] User changed to ntopng
déc. 15 14:48:17 NTOP ntopng[21206]: 15/Dec/2022 14:48:17 [NetworkInterface.cpp:3230] Started flow dump loop on interface ens192 [id: 4]...

Unfortunately, I have this message on the Web interface : 

ntopng is unable to serve requests at this time (possibly starting up or shutting down). Please hold on.

Do you already have this message ?
Do you have a fix for thaht ? Maybe I missed something ?

Thanks for you help,

Regards,

Romain

**Comment by lucaderi** [comment]
The error means that the DB is keeping ntopng busy (no reply?). Can you please check if everything is ok on the DB side?

**Comment by MatteoBiscosi** [comment]
Hi @Danifilth89, please update to the latest ntopng and let me know if the issue persists. In that case please send me the ntopng.conf file via email (`biscosi at ntop.org`)

**Comment by Danifilth89** [comment]
> The error means that the DB is keeping ntopng busy (no reply?). Can you please check if everything is ok on the DB side?

Hi Lucaderi,

Here are my tests on the DB :

root@NTOP:~# clickhouse-client
ClickHouse client version 18.16.1.
Connecting to localhost:9000.
Connected to ClickHouse server version 18.16.1 revision 54412.

NTOP :) show databases

SHOW DATABASES

┌─name────┐
│ default │
│ ntopng  │
│ system  │
└─────────┘

3 rows in set. Elapsed: 0.002 sec.

NTOP :) show tables

SHOW TABLES

Ok.

0 rows in set. Elapsed: 0.020 sec.


What kind of tests can I do ?

Regards,

Romain T.

**Comment by Danifilth89** [comment]
> MatteoBiscosi



> Hi @Danifilth89, please update to the latest ntopng and let me know if the issue persists. In that case please send me the ntopng.conf file via email (`biscosi at ntop.org`)

Hi @MatteoBiscosi 

Thank you for your feedback.
I upgraded my Ntopng few minutes ago and I have the same result.
I'll contact you by email.

Regards,

Romain T.

**Comment by lucaderi** [comment]
As of https://www.ntop.org/guides/ntopng/clickhouse/index.html you need to use clickhouse 22 or newer. Please upgrade clickhouse

**Comment by Danifilth89** [comment]
> As of https://www.ntop.org/guides/ntopng/clickhouse/index.html you need to use clickhouse 22 or newer. Please upgrade clickhouse

Hi @lucaderi 

Thanks for your support.

Clickhouse is now in version 22.2 but I still have the same issue : 

root@NTOP:~# systemctl status clickhouse-server.service
● clickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
     Loaded: loaded (/etc/systemd/system/clickhouse-server.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-12-21 14:15:27 CET; 37s ago
   Main PID: 2085 (clckhouse-watch)
      Tasks: 205 (limit: 4577)
     Memory: 442.7M
     CGroup: /system.slice/clickhouse-server.service
             ├─2085 clickhouse-watchdog        --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid
             └─2112 /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid

déc. 21 14:15:27 NTOP systemd[1]: Started ClickHouse Server (analytic DBMS for big data).
déc. 21 14:15:29 NTOP clickhouse-server[2085]: Processing configuration file '/etc/clickhouse-server/config.xml'.
déc. 21 14:15:29 NTOP clickhouse-server[2085]: Logging trace to /var/log/clickhouse-server/clickhouse-server.log
déc. 21 14:15:29 NTOP clickhouse-server[2085]: Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
déc. 21 14:15:35 NTOP clickhouse-server[2112]: Processing configuration file '/etc/clickhouse-server/config.xml'.
déc. 21 14:15:35 NTOP clickhouse-server[2112]: Saved preprocessed configuration to '/var/lib/clickhouse/preprocessed_configs/config.xml'.
déc. 21 14:15:35 NTOP clickhouse-server[2112]: Processing configuration file '/etc/clickhouse-server/users.xml'.
déc. 21 14:15:35 NTOP clickhouse-server[2112]: Saved preprocessed configuration to '/var/lib/clickhouse/preprocessed_configs/users.xml'.


root@NTOP:~# systemctl status ntopng
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
     Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-12-21 14:15:20 CET; 49s ago
    Process: 2041 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (c>
    Process: 2055 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
    Process: 2057 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (code=exited, status=0/SUCCE>
    Process: 2059 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /run/ntopng.conf (co>
   Main PID: 2061 (ntopng)
      Tasks: 13 (limit: 4577)
     Memory: 43.7M
     CGroup: /system.slice/ntopng.service
             └─2061 /usr/bin/ntopng /run/ntopng.conf

déc. 21 14:15:37 NTOP ntopng[2061]: 21/Dec/2022 14:15:37 [Ntop.cpp:2637] Registered interface ens192 [id: 4]
déc. 21 14:15:37 NTOP ntopng[2061]: 21/Dec/2022 14:15:37 [main.cpp:352] PID stored in file /var/run/ntopng.pid
déc. 21 14:15:37 NTOP ntopng[2061]: 21/Dec/2022 14:15:37 [Geolocation.cpp:149] Loaded database dbip-asn-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip-as>
déc. 21 14:15:37 NTOP ntopng[2061]: 21/Dec/2022 14:15:37 [Geolocation.cpp:149] Loaded database dbip-city-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip-c>
déc. 21 14:15:37 NTOP ntopng[2061]: 21/Dec/2022 14:15:37 [Geolocation.cpp:95] Using geolocation provided by DB-IP (https://db-ip.com/)
déc. 21 14:15:37 NTOP ntopng[2061]: 21/Dec/2022 14:15:37 [HTTPserver.cpp:1406] Found TLS certificate /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem
déc. 21 14:15:37 NTOP ntopng[2061]: 21/Dec/2022 14:15:37 [HTTPserver.cpp:1683] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
déc. 21 14:15:37 NTOP ntopng[2061]: 21/Dec/2022 14:15:37 [HTTPserver.cpp:1686] HTTP server listening on 3000
déc. 21 14:15:37 NTOP ntopng[2061]: 21/Dec/2022 14:15:37 [Utils.cpp:800] User changed to ntopng
déc. 21 14:15:37 NTOP ntopng[2061]: 21/Dec/2022 14:15:37 [NetworkInterface.cpp:3268] Started flow dump loop on interface ens192 [id: 4]...


root@NTOP:~# clickhouse-client
ClickHouse client version 22.2.2.1.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.2.2 revision 54455.

NTOP :) q
Bye.


root@NTOP:~# ntopng --version
Version:        5.5.221220 [Enterprise/Professional build]
GIT rev:        dev:c42fdd60c925d8e2d2bcd02a0797895d8d8bc7e3:20221220
Pro rev:        r5414
Built on:       Ubuntu 20.04.5 LTS

**Comment by Danifilth89** [comment]
Hi,

With @MatteoBiscosi we modified the ntop configuration file like this : 
#-F "clickhouse;127.0.0.1@9000;ntopng;default;default"
-F='clickhouse'

Everything is now OK.
Thanks for you assistance.

Regards,

Romain T
