### ISSUE TITLE
Host Ports Page is Unreadeable

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7041]
![Screen Shot 2022-12-18 at 09 33 41](https://user-images.githubusercontent.com/4493366/208288801-76d16d42-183c-48cb-86e2-98585c7177d8.png)

**Comment by lucaderi** [comment]
Said that it is very complicated to read, I am missing the goal of this page in the current layout. Furthermore, labels are not consistent "Top Server Ports" vs "Contacted Server TCP Ports"

**Comment by MatteoBiscosi** [comment]
Reverted to the hold page
