### ISSUE TITLE
Multi-series Charts are Unreadable in Dark Mode

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7042]
![Screen Shot 2022-12-18 at 09 41 34](https://user-images.githubusercontent.com/4493366/208289044-1ef44dc6-0ae0-4026-a6be-c9aebc3e5e1c.png)

**Comment by uccidibuti** [comment]
It should be fixed:
![immagine](https://user-images.githubusercontent.com/12447209/208838728-c6333dbc-e9c4-4b0f-ba36-3a07d2f02f2f.png)

**Comment by lucaderi** [comment]
Verified as fixed
