### ISSUE TITLE
Top Interface Hosts Disappeared

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7044]
Before the migration to the new graphs, when moving the mouse over the interface chart it was possible to see the top hosts displayed. This feature is now gone and it needs to be restored.

**Comment by uccidibuti** [comment]
Can you add a picture? This pic shows the old interface timeseries and i didn't see any top host displayed on chart mouse over.
![immagine](https://user-images.githubusercontent.com/12447209/208429274-b4adccc3-69d7-413c-b279-4d58874b999f.png)

**Comment by lucaderi** [comment]
Verified as fixed
