### ISSUE TITLE
Fix space in Host Rules

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7047]
OK
![Screen Shot 2022-12-18 at 10 10 23](https://user-images.githubusercontent.com/4493366/208290118-6a4a97a5-316b-4ec3-a755-4b25517c0544.png)

Not OK
![image](https://user-images.githubusercontent.com/4493366/208290129-277bcb9e-dc5f-4040-979b-4e02f9807e1f.png)

**Comment by MatteoBiscosi** [comment]
issue with the padding should be fixed now
![image](https://user-images.githubusercontent.com/49585191/208411317-68017468-a3ec-40bf-9a1c-4973ab840738.png)

**Comment by lucaderi** [comment]
Verified as fixed
