### ISSUE TITLE
Invalid Unit Reported

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7048]
![Screen Shot 2022-12-18 at 10 14 17](https://user-images.githubusercontent.com/4493366/208290230-dd1a5f0c-d53f-4a9c-864b-248fed2e93f3.png)

When selected the score, the unit (GB,....) has to disappear as the score unit is a number

**Comment by MatteoBiscosi** [comment]
The issue should be fixed now.
![image](https://user-images.githubusercontent.com/49585191/208406467-0a7f0b44-cf64-4034-b569-ca991cbff505.png)
![image](https://user-images.githubusercontent.com/49585191/208406379-6abd8f3d-3ede-47b8-ac10-07e7ff69b8fb.png)

**Comment by lucaderi** [comment]
Verified ad fixed
