### ISSUE TITLE
Issue #678 still happening. Not using ES. Running version: 2.5.160822

### ISSUE THREAD

**Issue by nate-byrnes** [ntop/ntopng#705]
I would have re-opened that issue, but it seems I cannot....

**Comment by lucaderi** [comment]
Please describe the problem in details and we'll look at it later this week

**Comment by nate-byrnes** [comment]
ON the dashboard I see traffic (this is my top host)
![dashboard](https://cloud.githubusercontent.com/assets/19349744/17457234/ec8a4e90-5bc0-11e6-81d3-e9ac231fd1dc.png)

On the host specific page, I see there has been traffic for quite a while
![host_top](https://cloud.githubusercontent.com/assets/19349744/17457220/25ada83a-5bc0-11e6-8289-b118e6a1a45d.png)

But, in the traffic history graph, I only see one spike of 26bps, when I have watched this host's traffic on the dashboard staying above 20Mbps for 30 minutes....
![host_traff](https://cloud.githubusercontent.com/assets/19349744/17457235/f1f74c16-5bc0-11e6-9d60-b3977395687f.png)

**Comment by simonemainardi** [comment]
@nate-byrnes I dropped you an email a few days ago. Can you please re-grant me the access to your machine. Thank you,

**Comment by nate-byrnes** [comment]
Sorry, i'm just on my way home from a long weekend in the mountains. I'll get that set up tomorrow.
    Thanks,    Nate

---

Nathanial Byrneswww.elmdc.com(716) 949-7656

-------- Original message --------From: simonemainardi notifications@github.com Date: 8/29/16  10:34 AM  (GMT-05:00) To: ntop/ntopng ntopng@noreply.github.com Cc: nate-byrnes nate@elmdc.com, Mention mention@noreply.github.com Subject: Re: [ntop/ntopng] Issue #678 still happening. Not using ES. Running version: 2.5.160822 (#705) 
@nate-byrnes I dropped you an email a few days ago. Can you please re-grant me the access to your machine. Thank you,

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ntop/ntopng","title":"ntop/ntopng","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ntop/ntopng"}},"updates":{"snippets":[{"icon":"PERSON","message":"@simonemainardi in #705: @nate-byrnes I dropped you an email a few days ago. Can you please re-grant me the access to your machine. Thank you,"}],"action":{"name":"View Issue","url":"https://github.com/ntop/ntopng/issues/705#issuecomment-243142340"}}}

**Comment by simonemainardi** [comment]
a remote session highlighted the filesystem was full. Please make more room and report back.

**Comment by simonemainardi** [comment]
I can confirm that the issue was due to a full FS. It is solved now and statistics are properly recorded.
