### ISSUE TITLE
IP address filtering not working with Alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7050]
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/4493366/208315683-bfd4253b-be8b-43f0-811f-dc5953ad7dd7.png">

Please check if the VLAN tag is the problem

**Comment by cardigliano** [comment]
Unable to reproduce, I need the SQL or access to a box

**Comment by lucaderi** [comment]
leave as is (unable to reproduce)
