### ISSUE TITLE
VLAN names are not mapped in Alert Exclusions Dialog

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7051]
<img width="779" alt="image" src="https://user-images.githubusercontent.com/4493366/208315876-027c40ff-9b00-4261-9fdd-b8da51d050aa.png">

**Comment by MatteoBiscosi** [comment]
Fixed like the following, by adding the vlan formatted name after the client name
![image](https://user-images.githubusercontent.com/49585191/208391636-0f55e1b0-b49e-4711-9fe8-560124072d5f.png)

**Comment by lucaderi** [comment]
Verified as fixed
