### ISSUE TITLE
VLAN tags are not mapped in Check Exclusions

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7052]
Similar to #7051

<img width="1447" alt="image" src="https://user-images.githubusercontent.com/4493366/208315986-5d3510f6-ca72-498a-bb1b-6cee2bdc54b0.png">

**Comment by MatteoBiscosi** [comment]
Added the vlan like for the disable alerts modal.
![image](https://user-images.githubusercontent.com/49585191/208395852-3545a7d2-e5ca-4cc2-90cd-801d5a168bdb.png)

**Comment by lucaderi** [comment]
Verified as fixed
