### ISSUE TITLE
Alert Exclusion randomly works with VLANs

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7053]
<img width="787" alt="image" src="https://user-images.githubusercontent.com/4493366/208316076-a205184c-e511-4e4b-9394-307c30e74522.png">

Adding the above exclusion, many times does not work 

In some cases:
- does not delete affected alerts in the alert page
- the exclusion is not added to the exclusion list

In other cases it works and it is added to the exclusion list. Usually the first attempt fails with no errors, whereas the second attempt works correctly.

**Comment by cardigliano** [comment]
According to my tests it seems that the first attempt actually works behind the hood, but the frontend still shows deleted alerts (which are actually deleted on the backend, but this probably happens after the table refresh). Manually reloading the page shows that alerts are actually deleted.

**Comment by cardigliano** [comment]
@uccidibuti we should make sure that the datatable is reloaded *after* the API request to delete the data returns, and probably add some delay to make sure the change is applied to the DB, with a loading/spinning component to give some feedback to the user.

**Comment by cardigliano** [comment]
It is requested to:
- when running on clickhouse, warn the user with something like "Alerts may still appear for a while after pushing an exclusion rule as alert deletion on the database is asynchronous"
- add a loader of 1 second that should cover in most cases the deletion time, before updating the table

**Comment by lucaderi** [comment]
Verified as fixed
