### ISSUE TITLE
Add title to symbolic IP address and VLANs

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7054]
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/4493366/208316372-917ae21f-bffb-45bc-ad59-c7b6814b8b9e.png">

When IP addresses and VLANs are represented symbolically it is requested to add a title="...." in the HREF that contains the numeric IP or VLAN name. This is useful when troubleshooting large networks

**Comment by MatteoBiscosi** [comment]
Implemented like requested. In this case i decided just to add the ip, because the vlan alias / id is above, the host mac is already there and so the only thing missing is the host ip.
![image](https://user-images.githubusercontent.com/49585191/208385164-488dcc0a-a3db-449e-afe1-6c2aee620311.png)

**Comment by lucaderi** [comment]
Verified as fixed
