### ISSUE TITLE
Move Host Rules to a New Place

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7055]
Host Rules are currently reported under the already crowded network interface menu.

This is to request to move such page under the left sidebar menu under "Hosts"

**Comment by MatteoBiscosi** [comment]
Moved the page like requested
![image](https://user-images.githubusercontent.com/49585191/208415462-a4df248b-7505-4dbb-87a6-763f7f0d9011.png)

**Comment by lucaderi** [comment]
Verified as fixed
