### ISSUE TITLE
Problem activating educational license

### ISSUE THREAD

**Issue by vpanagos** [ntop/ntopng#7056]
**Environment**:
* OS name: Rocky Linux
* OS version: 8.7
* Architecture: amd64
* ntopng version/revision: 5.4.221130

**What happened**:
I contacted ntopng on behalf of our University network department and received an educational license for nprobe and ntopng.
The license for ntopng cannot get activated

**How did you reproduce it?**
I enter in ntopng License Generator the data I received and I always get the message "The orderId you have specified is not valid for the product you have selected (see [for details](https://shop.ntop.org/recover_licenses.html)). Please go back and try again."

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @vpanagos please drop an email at `biscosi at ntop.org`

**Comment by lucaderi** [comment]
@vpanagos

In the activation page you need to select from the drop-down menu below, the product for which you require license activation:
![Screen Shot 2022-12-19 at 16 39 54](https://user-images.githubusercontent.com/4493366/208463533-133aec06-47b4-450b-abc7-7ca89c005b73.png)

**Comment by MatteoBiscosi** [comment]
Verified as fixed
