### ISSUE TITLE
Invalid historical menu show-up

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7057]
With an unprivileged user configured with networks "0.0.0.0/0,::/0" as follows
![Screen Shot 2022-12-19 at 15 50 06](https://user-images.githubusercontent.com/4493366/208452987-1ea8d3c6-ecef-4ab2-9cdf-81479a7098be.png)

the user can see historical data
![Screen Shot 2022-12-19 at 15 52 47](https://user-images.githubusercontent.com/4493366/208453508-91768b0f-c4a4-474c-a643-19d41c660e9b.png)

Instead, if I specify a different network (e.g. 192.168.1.0/24) the historical menu disappears.

**Comment by MatteoBiscosi** [comment]
The issue should now be fixed

**Comment by lucaderi** [comment]
Verified as fixed
