### ISSUE TITLE
User restriction is not working

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7058]
Configuring an unprivileged user as follows:

![Screen Shot 2022-12-19 at 15 55 40](https://user-images.githubusercontent.com/4493366/208454095-3287db4a-3870-441d-9603-2776953f4e90.png)

such user should not be able to see historical records. In this case the Flows->Historical menu is not displayed and this is correct.

Unfortunately the security is bypassed if the user accesses https://xxxx:3000/lua/pro/db_search.lua

![image](https://user-images.githubusercontent.com/4493366/208454464-275d8130-f009-4bdb-a619-deecbcac66c0.png)

As you can see everything (except the top chart above the table) is working and also all the queries in this menu

![Screen Shot 2022-12-19 at 15 58 49](https://user-images.githubusercontent.com/4493366/208454785-0309933d-d1c1-4561-8914-91210f0e2492.png)

are bypassed.

Please also fix/check all the REST API calls that should not work for this user.

**Comment by MatteoBiscosi** [comment]
The issue should be fixed. Pro repo.

**Comment by lucaderi** [comment]
Verified as fixed
