### ISSUE TITLE
Host not active cannot be resumed (moon icon) anymore

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7059]
![Screen Shot 2022-12-20 at 09 38 12](https://user-images.githubusercontent.com/4493366/208621740-ac521e88-7f79-4d05-bdae-a910690e9f14.png)

**Comment by cardigliano** [comment]
This seems to be working for me, it is likely this happens under some circumstances and needs to be reproduced again.

**Comment by lucaderi** [comment]
Ok leave it as is for the time bein
