### ISSUE TITLE
Inconsistent chart/table representation in historical flows

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7060]
![image](https://user-images.githubusercontent.com/4493366/208754851-d7bd4ff9-869e-4e1d-9550-9a315364ead9.png)

This is the SQL query copied from the page:

SELECT PROTOCOL,L7_PROTO,L7_PROTO_MASTER,PACKETS,TOTAL_BYTES,toInt32(FIRST_SEEN) FIRST_SEEN,toInt32(LAST_SEEN) LAST_SEEN,CLIENT_NW_LATENCY_US,SERVER_NW_LATENCY_US,SRC_HOST_POOL_ID,FLOW_ID,VLAN_ID,IP_PROTOCOL_VERSION,IPv4NumToString(IPV4_SRC_ADDR) IPV4_SRC_ADDR_FORMATTED,IPv4NumToString(IPV4_DST_ADDR) IPV4_DST_ADDR_FORMATTED,IPv6NumToString(IPV6_SRC_ADDR) IPV6_SRC_ADDR_FORMATTED,IPv6NumToString(IPV6_DST_ADDR) IPV6_DST_ADDR_FORMATTED,IP_SRC_PORT,IP_DST_PORT,IPv4NumToString(PROBE_IP) PROBE_IP_FORMATTED,SRC_LABEL,DST_LABEL,CLIENT_LOCATION,SERVER_LOCATION,COMMUNITY_ID,ABS(LAST_SEEN - FIRST_SEEN) as TIME_DELTA,(TOTAL_BYTES / (TIME_DELTA + 1)) * 8 as THROUGHPUT,ALERT_JSON FROM flows WHERE ((INTERFACE_ID=0) AND ((IP_PROTOCOL_VERSION = 4) AND( (IPV4_DST_ADDR=IPv4StringToNum('10.141.253.227') OR IPV4_SRC_ADDR=IPv4StringToNum('10.141.253.227')) OR (DST_LABEL=('10.141.253.227') OR SRC_LABEL=('10.141.253.227')) ))) AND (FIRST_SEEN >= 1671563721 AND FIRST_SEEN <= 1671565521 AND LAST_SEEN <= 1671565521)  ORDER BY FIRST_SEEN desc LIMIT 10

**Comment by cardigliano** [comment]
The selected IP filter in the Tagify component is 10.141.253.226 while the SQL query reports 10.141.253.227, which is likely to be a previous query, maybe due to some js failure (and the datatable probably shows the result for the previous query)

**Comment by uccidibuti** [comment]
Unable to reproduce.
