### ISSUE TITLE
Unprivileged user network support in Historical Data

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7062]
Currently, unprivileged users can have restrictions on network list. This is not honoured for historical data (flows and alerts) and it needs to be supported.

**Comment by cardigliano** [comment]
Implemented with 7da1395b874e11a98070bdb8d05cb0db1d4a346e ab9682ed306864ec718ec17b6bad82a4fd727bdd d3bc7bf663f9ff209bbac3b099332587107507ce 2bf833575e8bd4fe1c91695af4b60d092e7238d8 22dcb1588708627d52ee5cf256c24f47b8928b35

**Comment by lucaderi** [comment]
Verified as fixed
