### ISSUE TITLE
Invalid Engaged Time Report in Chart

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7066]
![Screen Shot 2022-12-23 at 06 38 55](https://user-images.githubusercontent.com/4493366/209277992-8c1d8e2e-689d-4ff4-8498-a7e50a0900dc.png)

In the above example, the engaged alerts started at 6:31 for 7 mins, so I expect (only for engaged alerts) to see in the chart an area from 6:31 to 6:38 and not just a single point.

The above bug is creating a side effect. Suppose that you have an engaged alert triggered 1 hour ago, and you open the alert page. You see an empty page that makes you think that there are no engaged alerts. This is wrong as there are engaged alerts that were *first* triggered outside of the selected time range.

![Screen Shot 2022-12-23 at 10 14 38](https://user-images.githubusercontent.com/4493366/209307935-e8e75330-d48c-487e-8372-48401a712db4.png)

**Comment by cardigliano** [comment]
The same applies to Past alerts: the current logic displays alerts by creation/trigger time, it does not handle intervals. This is this way by design and should be reconsidered.

**Comment by cardigliano** [comment]
Changed as requested for engaged alerts. The same should be done for Past alerts for consistency.

**Comment by lucaderi** [comment]
Verified as fixed
