### ISSUE TITLE
Unable add exclude domain.

### ISSUE THREAD

**Issue by takenek** [ntop/ntopng#7069]
Exclude Checks "Susp. DGA Domain". Exclude For:
Any host (disable check)
Client: X.X.X.X
Server: dns.google (8.8.8.8)
Exclude all checks for:
Domain: somethingcom-my.sharepoint.com

When i press domain somethingcom-my.sharepoint.com to exclude i am unable to press yellow button exclude.

**Comment by cardigliano** [comment]
What ntopng license are you running?

**Comment by takenek** [comment]
ntopng Professional v.5.4.221224

**Comment by takenek** [comment]
I just update ntopng to version: ntopng Professional v.5.4.221229 (Debian GNU/Linux 11 (bullseye)) 
and problem still exist buttons is still grey unable to press:
![image](https://user-images.githubusercontent.com/4953735/210129317-d3829291-7568-4bca-8a29-331afb3a6766.png)

**Comment by cardigliano** [comment]
@uccidibuti could you backport the fix to the stable too?

**Comment by uccidibuti** [comment]
it will be available soon in next stable release
