### ISSUE TITLE
IEC Invalid Command Transition Alert Disabled but alerts still emitted in stable

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#7070]
[ntopng Enterprise L v.5.4.221130 (Rocky Linux release 8.5 (Green Obsidian))](https://www.ntop.org/products/traffic-analysis/ntop/)

IEC Invalid Command Transition Alert Disabled but alerts still emitted.

![image](https://user-images.githubusercontent.com/67421019/209583348-848b6b24-d7d7-4650-a3c3-76d895c178d8.png)

![image](https://user-images.githubusercontent.com/67421019/209583411-92b154f8-0fec-4671-8add-a5408e1170d0.png)

**Comment by MatteoBiscosi** [comment]
The issue should be fixed, update to the latest version and let me know

**Comment by atemix** [comment]
@MatteoBiscosi Latest stable build is 2023-01-03, but issue was fixed later?

**Comment by atemix** [comment]
@MatteoBiscosi 
After upgrading our ntopng instances to 5.4.230112, all is ok except 2 of them, where IEC alerts were emitting.
Ntopng faults and restarts after a couple of seconds infinetly.

Jan 12 20:41:56 ntopng systemd[1]: ntopng.service: Main process exited, code=killed, status=11/SEGV
Jan 12 20:41:56 ntopng systemd[1]: ntopng.service: Failed with result 'signal'.
Jan 12 20:42:01 ntopng systemd[1]: ntopng.service: Service RestartSec=5s expired, scheduling restart.
Jan 12 20:42:01 ntopng systemd[1]: ntopng.service: Scheduled restart job, restart counter is at 7.
Jan 12 20:42:01 ntopng systemd[1]: Stopped ntopng high-speed web-based traffic monitoring and analysis tool.
Jan 12 20:42:01 ntopng systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
Jan 12 20:42:01 ntopng systemd[1]: Started ntopng high-speed web-based traffic monitoring and analysis tool.

Conf factory reset or full reset (clearing redis, influxdb, clickhouse, homedir) has no effect.
Ntopng starting only after commenting packet interface in ntopng.conf.
Flow and syslog interfaces are ok.

**Comment by MatteoBiscosi** [comment]
I pushed again a new fix, it should fix both the restart and the IEC invalid transition, please update in a couple of hours and let me know.

**Comment by atemix** [comment]
@MatteoBiscosi fixed, instances with iec alerts started ok, no new iec alerts. Thanks
