### ISSUE TITLE
Ignoring --offline switch in stable

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#7071]
ntopng Enterprise L v.5.4.221130 (Rocky Linux release 8.5 (Green Obsidian))

Configured "--offline=" in ntopng.conf, but after a while Ntopng still trying to connect to sites.

![image](https://user-images.githubusercontent.com/67421019/209583688-bd1975c0-d0e8-46f0-b52a-074186b16586.png)

![image](https://user-images.githubusercontent.com/67421019/209583706-2858aed1-5b03-4c1d-b953-09db3ab81ceb.png)

**Comment by MatteoBiscosi** [comment]
Hi @atemix to run ntopng in offline mode, you have to add the `--offline` to the configuration file (without `=`) other then that, please could you share your ntopng configuration file? Then update ntopng to the latest versione and let me know if with these changes the problem occurs again

**Comment by MatteoBiscosi** [comment]
The issue should now be fixed for both, dev and stable version
