### ISSUE TITLE
Alert Severity Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7074]
![image](https://user-images.githubusercontent.com/4493366/209687096-5f85e59d-00b5-4f10-9d00-ac998147db5f.png)
In the above configuration only errors (red) must appear.

This is what happens instead
![Screen Shot 2022-12-27 at 16 26 32](https://user-images.githubusercontent.com/4493366/209687486-01333955-877c-41a0-90c9-eec827b77ada.png)

**Comment by cardigliano** [comment]
Fixed with 09c2e1f1c00dc04df6e68435a4c4748297ddc58a 039b842ce5335831ff0ef2036ddde953ad1d6f21

**Comment by lucaderi** [comment]
Verified as fixed
