### ISSUE TITLE
Does ntopng support multiple languages ？

### ISSUE THREAD

**Issue by maojianyou** [ntop/ntopng#7079]
**What would you like to add or change?**:

Does ntopng support multiple languages

**Why do you and others need this?**:

**Comment by cardigliano** [comment]
Yes of course, you can switch the language from the top-right user menu.

<img width="798" alt="Screen Shot 2023-01-03 at 09 18 26" src="https://user-images.githubusercontent.com/7548711/210320923-a0d4c07c-c37f-4289-bc7d-7ad8fdf1c79a.png">
