### ISSUE TITLE
NIC Upload (tx) performance extremely slows down when ntopng is disabled

### ISSUE THREAD

**Issue by Q1984** [ntop/ntopng#7083]
Hi All,

I have to disable ntopng on a gateway (debian 11) due to long term maintenance.
Its generally ok, but the upload speed stuck at very low amount (sometimes 0.0!!) when ntopng is disabled. Download speed is fine. After I enabled ntopng upload speed back to normal. What can cause this weird behavior?
NICS are vmxnet3 adapters.

**Comment by cardigliano** [comment]
@Q1984 ntopng is a passive application, receiving a copy of the packets for implementing traffic analysis, thus it should not interfere with your system data plane (it's not inline). This is definitely a strange behavior. More details about your ntopng configuration may help.

**Comment by Q1984** [comment]
Based on a small investigaion I've figured out that ntopng disables interfaces tso/gro when running, and that was my issue, after disabling ntopng the tso was enabled by the kernel driver defaults which kills my upload speed, don't know why probably wmxnet3 drivers in linux is not fully working with hardware offloadings...

**Comment by cardigliano** [comment]
Interesting, hardware offloads usually improve the performance with virtual adapters. However good that you found the reason.
