### ISSUE TITLE
make sankey-host api generic

### ISSUE THREAD

**Issue by uccidibuti** [ntop/ntopng#7087]
The API /lua/pro/rest/v2/get/host/flows/data.lua must return an object of nodes and links:
{
nodes: [ { node_id: string, label: string, ...optional_info: any }, .. ]
links: [ { source_node_id: string, target_node_id: string, label: string, ...optional_info:any}]
}

Differently from current API, protocols must be returned as links.

**Comment by NicoMaio** [comment]
Verified the implementation
