### ISSUE TITLE
Recipient Alert Counter Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7088]
Despite the number of triggered alerts (below you can see the flow alerts but there are additional alerts such as those triggered on hosts)

![Screen Shot 2023-01-09 at 19 12 47](https://user-images.githubusercontent.com/4493366/211378389-5c34eba8-4f69-4cd8-949d-cca2b8652911.png)

the recipient counters do not account the number of triggered alerts

![Screen Shot 2023-01-09 at 19 12 32](https://user-images.githubusercontent.com/4493366/211378654-1f3a2f6d-cac6-4a99-a90b-a362af14e884.png)

**Comment by cardigliano** [comment]
When clickhouse is enabled, flow alerts are a view on historical flows. It is likely this issue is related to that: we should handle this case when displaying counters in the recipient table.
However this does not explain the mismatch with host alerts.

**Comment by MatteoBiscosi** [comment]
Issue fixed and tested on hsol
