### ISSUE TITLE
Telegram Reported alerts contain HTML

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7090]
![IMAGE 2023-01-10 10:28:15](https://user-images.githubusercontent.com/4493366/211513281-4d2cebab-d540-45ec-8d60-638799d3d1df.jpg)

HTML should not be used in alerts

**Comment by MatteoBiscosi** [comment]
The issue should be fixed in the last version

**Comment by lucaderi** [comment]
Verified by @NicoMaio as working
