### ISSUE TITLE
Dropdown menu shouldn't have a scrollbar

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7093]
In host -> Sankey Chart the dropdown must be larger (in x) as the scrollbar should not be displayed
![Screen Shot 2023-01-12 at 09 34 06](https://user-images.githubusercontent.com/4493366/212017448-93c0a2a7-995c-47dc-bc33-0de9775faf07.png)

**Comment by MatteoBiscosi** [comment]
This issue should be fixed with the last update
![image](https://user-images.githubusercontent.com/49585191/215470670-752739a8-beb9-4992-bbd1-78a8cb3a89a5.png)

**Comment by lucaderi** [comment]
![bug](https://user-images.githubusercontent.com/4493366/215748722-f568b1bb-4886-4ee4-8173-6f5997e897b7.png)
Not yet working on safari: make it wider

**Comment by MatteoBiscosi** [comment]
Fixed yesterday
