### ISSUE TITLE
Influx Data Retention not Honoured

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7096]
ntopng is set to use InfluxDB with a retention of 30 days. On Nov 24 retention was set to 60 days but Influx is still using the old one (30 days).

**Comment by MatteoBiscosi** [comment]
From now on, the retention should works correctly, when you update the retention from the gui, the retention on influxdb is correctly updated.
![image](https://user-images.githubusercontent.com/49585191/214813217-a62af0ed-9cd1-498f-8baf-01a5be9c9b3b.png)
![image](https://user-images.githubusercontent.com/49585191/214813428-04fcf89b-6291-4628-8b6f-eb78bc12f6f9.png)

**Comment by lucaderi** [comment]
Seems to work
