### ISSUE TITLE
LuaEngine error crashed ntopng GUI

### ISSUE THREAD

**Issue by sp-heinrichsra** [ntop/ntopng#7097]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04.5 LTS
* Architecture: 5.4.0-136-generic x153-Ubuntu SMP Thu Nov 24 15:56:58 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* ntopng version/revision: ntopng Enterprise XL v.5.5.230112

**What happened**:
After a while (seems to random) the ntopng GUI crashed with the following error:
ntopng[239968]: 12/Jan/2023 15:31:37 [LuaEngine.cpp:1329] WARNING: Script failure [/usr/share/ntopng/scripts/lua/flows_stats.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils_print.lua:174: attempt to index a nil value (field '?')]

Do a "service ntopng restart" whithout success: immediate crashed again:
ntopng[257409]: 12/Jan/2023 16:13:10 [LuaEngine.cpp:1329] WARNING: Script failure [/usr/share/ntopng/scripts/lua/flows_stats.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils_print.lua:174: attempt to index a nil value (field '?')]

Do a reboot of the server -> Crashed again
12/Jan/2023 16:18:39 [LuaEngine.cpp:1329] WARNING: Script failure [/usr/share/ntopng/scripts/lua/flows_stats.lua][/usr/share/ntopng/scripts/lua/modules/lua_utils_print.lua:174: attempt to index a nil value (field '?')]

**How did you reproduce it?**
Most likely by choosing the ZMQ Interface in the dropdown of showing the Flows/Live:
ntopng[1346]: 12/Jan/2023 16:15:46 [ZMQCollectorInterface.cpp:263] Collecting flows on tcp://*:5557c
ntopng[1346]: 12/Jan/2023 16:15:46 [ZMQCollectorInterface.cpp:263] Collecting flows on tcp://*:5556c

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @sp-heinrichsra i pushed a possible fix, however i'm not able to reproduce the issue, so please let me know if this patch fixed the issue or not

**Comment by sp-heinrichsra** [comment]
Hello Matteo,

I will check it further the next days and send you an update on this.
Atm I cannot see an error but I was only on short session at our ntop system.

Thanks
Ralf


Mit freundlichen Grüßen / Kind regards

Ralf Heinrichs
Senior Network Architect
Service Engineering




[cid:qbeyond_Cloud_Solutions_Logo_signatur_4c8cfa21-6e32-44a5-b9e2-91ec21e8af43.png]

Direkt:
T +49 731 920 13 - 240<tel:+4973192013240>
E ***@***.******@***.***>

Zentrale:
T +49 731 92013 - 0<tel:+49731920130>
F +49 731 92013 - 290<tel:+4973192013290>
E ***@***.******@***.***>

Büroanschrift:
Lise-Meitner-Straße 5
89081 Ulm

Firmensitz
q.beyond Cloud Solutions GmbH
Richard-Byrd-Str. 4, 50829 Köln
Geschäftsführung: Thies Rixen, Sönke Eschke, Tatjana Bratina
Registergericht: Amtsgericht Köln, HRB 107825

www.qbeyond-cloud-solutions.de<http://www.qbeyond-cloud-solutions.de>

[cid:banner_rebranding_sp_307d863c-7297-454a-8ddd-bc3944cd9d04.jpg]<https://www.qbeyond-cloud-solutions.de/faq/>
Von: Matteo Biscosi ***@***.***>
Gesendet: Freitag, 13. Januar 2023 17:14
An: ntop/ntopng ***@***.***>
Cc: Ralf Heinrichs ***@***.***>; Mention ***@***.***>
Betreff: Re: [ntop/ntopng] LuaEngine error crashed ntopng GUI (Issue #7097)


Hi @sp-heinrichsra<https://github.com/sp-heinrichsra> i pushed a possible fix, however i'm not able to reproduce the issue, so please let me know if this patch fixed the issue or not

**Comment by sp-heinrichsra** [comment]
After some tests I cannot re-produce the error anylonger.
So this issue seems to fixed from my point of view.
