### ISSUE TITLE
No operating system detection

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#7099]
CentOS 8 Stream
ntopng Enterprise L v.5.4.230112

What happened:
Before 5.4.230112 ntopng detect operating system as Rocky Linux
Now there is nothing: "ntopng Enterprise L v.5.4.230112 ()"
![image](https://user-images.githubusercontent.com/67421019/212170946-e7477c44-a414-4f6d-a04c-0c95794426b3.png)

Is it a bug?

**Comment by lucaderi** [comment]
This has been fixed in the current release
