### ISSUE TITLE
tons of "suspicious activity"

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#710]
since few builds, I have ton of "suspicious activity" permanently whereas it was not the case before
I have 3 ntop servers to manage different networks and they all have the same result :-(
if i'm correct the max is 8193 ? + I did not find the command to extand it
- as I'm using mysql to save data I have now an issue with I/O where I have now 3 MB/s of data recorded on disk. Before it was at 300 KB/s

examples
![alerts](https://cloud.githubusercontent.com/assets/17108017/17930481/bf1a12ac-6a06-11e6-92a9-ce37627a70ac.png)

![alerts2](https://cloud.githubusercontent.com/assets/17108017/17930586/5569e994-6a07-11e6-99cc-bfd435ccb1b8.png)

**Comment by dan2716430** [comment]
I can confirm the problem. 
Even if you delete all the alerts, the list fills back up to 8193 (2^13 + 1).

**Comment by lucaderi** [comment]
@Niko78 We do not have the ability to extend it, but @simonemainardi is working at a full alert reimplementation where we can take this into account. This said, are those alerts correct or not?

**Comment by dan2716430** [comment]
Nope. Can't speak about Nico, but even after I deleted all the data (/var/tmp), the alerts remained.
The same after clicking on purge all alerts: the alerts disappear for 10 seconds then gradually ramp up to 8193.

**Comment by Niko78** [comment]
same here as Dan, alerts seem not correct at all

**Comment by dan2716430** [comment]
@Niko78 Just out of curiosity: do you use the Nagios integration?
I was supposed to start testing this week, but when I saw 8k alerts... I'd better wait. 
Trying to send 8193 SMS messages to 5 people might not be such a good idea...

**Comment by lucaderi** [comment]
@Niko78 Can you explain why they are not correct? If I look at https://cloud.githubusercontent.com/assets/17108017/17930481/bf1a12ac-6a06-11e6-92a9-ce37627a70ac.png I believe they are correct. Please explain why are not so.

@dan2716430 Sending SMSs is not a good idea in 2016. These are flow issues that need to be consolidated in real alerts, and this is what we are doing. Please be patient, of if you want we welcome your code/ideas contribution

**Comment by dan2716430** [comment]
@lucaderi In my limited experience with ntopng, every time you restart the service you get an alert for each known host. And you could click on "Purge all alerts" and all would be well until the next restart.

What's new is that now even if you delete all alerts they immediately come back. No service restart needed.

**Comment by dan2716430** [comment]
@lucaderi "Sending SMSs is not a good idea in 2016". Why?

**Comment by lucaderi** [comment]
Said that you cannot send IMHO an alert per flow issue, I think there are better options such as https://telegram.org/blog/bot-revolution. We have a prototype working, but we need some time to integrate it properly in ntopng. It will happen in the coming months.

**Comment by dan2716430** [comment]
@lucaderi OK, so you don't have a problem with SMS as a delivery method for alerts. Call me old, but I do remember a time when Internet was not always available.
Telegram integration sounds fine. We use a Telegram bot to coordinate field teams.

**Comment by Niko78** [comment]
@Niko78 Can you explain why they are not correct? If I look at https://cloud.githubusercontent.com/assets/17108017/17930481/bf1a12ac-6a06-11e6-92a9-ce37627a70ac.png I believe they are correct. Please explain why are not so.
=> cause it's not because a server is down that there is something suspicious
I would say that all seems to be "suspicious" now, a simple SYN packet has nothing suspicious
a simple ldap/http syn same

I doni't know what's the algorithm used but for me it's clearly not ok
- any idea why now with new builds data recorded in mysql are bigger ? 3MB/s now instead of 300 KB/s before... at this rythm my disk will be full very quickly

**Comment by simonemainardi** [comment]
@Niko78 mysql has nothing to do with alerts. Alerts are not saved to mysql. The fact that now there's a 3Mbps traffic going to mysql does not suffice to assert there is something wrong. Check your network for changes, misbehaving/additional hosts, and look at the recorded flows. Do they look good?

The algorithm is implemented in `FlowStatus Flow::getFlowStatus()` please check that out, share your thoughts, and feel free to improve it.

**Comment by Niko78** [comment]
@simonemainardi 
ok about mysql but I have this datarate on 3 servers just after upgrading ntop that's why I suspect something wrong before it was ok 
no changes in network or/and server
I would like to downgrade, is there an historic of deb files, I would need deb from last week to test

about alerts, ok but as it seems I'm not alone to see something wrong here maybe you should look into it.
thanks

Nico

**Comment by dan2716430** [comment]
Tried this morning with the latest ntopng build and a clean data folder (/var/tmp/ntopng instead of /var/tmp).

ntopng started with 8193 alerts. How?? It has an empty data folder. If it did not see any traffic, what's the meaning of 8193 of these:
Fri Aug 26 09:09:11 2016    Warning  Suspicious Activity    Probing or server down: gw150-136.jcsfiberlink.net > 108.161.188.192 [TCP 79.134.136.150:39023 > 108.161.188.192:443 [proto: 91/SSL][2048/0 pkts][81920/0 bytes][RST]]

Purged all alerts. 
They immediately started coming back. In 2 minutes it was back to 8193 alerts.

**Comment by lucaderi** [comment]
@dan2716430 the above activity is a problem as host 108.... Ha received 2048 TCP RST packets on port 443 sent by host gw-150.... So it looks to me like a DoS attack. BUT what do you mean with "if it did not see any traffic" ? Do you mean that ntopng has not seen these reset packets? Please explain.

**Comment by dan2716430** [comment]
Nope, it's not a DOS attack. 
You have somewhere an amplification bug.
Fri Aug 26 09:09:11 2016    Warning  Suspicious Activity    Probing or server down: 82.213.22.13 > cache.google.com [TCP 82.213.22.13:443 > 79.134.129.197:41116 [proto: 91/SSL][10240/0 pkts][15360000/0 bytes][ACK]]

> > It did not see any traffic. As in it started with an empty data folder.

Do you need access to the server?

**Comment by Niko78** [comment]
same here there is no ddos attack
if you check my screenshots, for some of them there are only few packets (less than 50) and for sure it's not an attack... and even when there are more, nothing indicates it is an attack.. that could be a server in maintenance or something else

**Comment by lucaderi** [comment]
@dan2716430 Yes access would be great. However if you look at ][10240/0 pkts][15360000/0 bytes] I see only one direction of the traffic (10240 in one direction, 0 in the reverse). Is this consistent with what you expect?

**Comment by dan2716430** [comment]
Nope.
I sent you an email for access.

**Comment by Niko78** [comment]
about my problem with more data... it's on my side, I have more flows than before so more data
sorry for the noise about that

**Comment by simonemainardi** [comment]
hi, I've made a fix that should have solved this issue. @Niko78 @dan2716430 a new build is in progress. Please hold on a couple of hours and then reinstall the latest ntopng. Feedback will be appreciated.

**Comment by Niko78** [comment]
@simonemainardi for me alerts disappeared :-)
thanks

**Comment by dan2716430** [comment]
Upgraded to the latest version.

Now when I click on "Purge all alerts" nothing happens...

I can delete the alerts one by one and they don't seem to come back, but I'm not going to click on 8k alerts one by one...

**Comment by simonemainardi** [comment]
I connected to your system and clicked purge all alerts: all alerts have been immediately purged. Now you have 0 alerts. Let me know.

**Comment by dan2716430** [comment]
Weird. That means I am logged in with a user account and did not have the rights to purge all?

Where is the logout button?

![2016-08-29 17_02_04-welcome to ntopng](https://cloud.githubusercontent.com/assets/20684284/18053933/6673e7e2-6e0a-11e6-8e9c-599b9ad454b6.png)

**Comment by simonemainardi** [comment]
![image](https://cloud.githubusercontent.com/assets/3397663/18054720/40b97ddc-6e05-11e6-86b1-a324d185a71e.png)

screenshot taken directly from your host ntopng

**Comment by dan2716430** [comment]
I don't doubt that's what you're seeing. I just wonder why I don't see the same thing.

**Comment by dan2716430** [comment]
Deleted cookies to force re-login and now I have the correct view. 
Maybe the interface crashes when left opened?

Anyway, not relevant for this bug.

I can confirm that I no longer have the permanent 8k alerts.

**Comment by ScottBrenner** [comment]
Was there a resolution on this? Setup ntopng earlier today and already have 8000+ "Probing or server down ..." alerts.

**Comment by lucaderi** [comment]
@ScottBrenner Please report what version you are using and how you configured ntopng

**Comment by emanuele-f** [comment]
@ScottBrenner under the ntopng preferences, do you have "Enable Probing Alerts" enabled?

**Comment by ScottBrenner** [comment]
@emanuele-f Just turned off Enable Probing Alerts, that seems to have fixed it. Thanks!

@lucaderi  I'm using ntopng v.2.4.170626 via the ntopng 0.8.10 package on pfSense 2.3.3.

**Comment by lucaderi** [comment]
@ScottBrenner Moving to v3 will fix the problem. Please do.

**Comment by ASHOKGP** [comment]
@lucaderi how to upgrade from V2 to V3 in pfsense it is not updating automatically we are getting only download option 
![image](https://user-images.githubusercontent.com/1425675/28713278-13b542a0-73ac-11e7-9bc0-77f9d26de7b4.png)

http://www.ntop.org/get-started/download/

Please let us know steps to upgrade this version in pfsense

**Comment by dagelf** [comment]
What's happening with me with 3.7.180827 is if I put network discovery on, then the host running ntop spams itself with probe detections... is there an easy way to exclude a host from being listed?

**Comment by emanuele-f** [comment]
@ASHOKGP please provide information about your OS in a new issue. Updating the software is just like upgrading any other package (e.g. `apt-get update && apt-get install ntopng`).

@dagelf do you mean that you get "suspicous activity for the ntopng host hitself? Currently you can only disable all the ntopng host alerts at once, from the host alert settings
