### ISSUE TITLE
Ignoring --offline switch in stable #7071

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#7100]
Ignoring --offline switch in stable #7071

Upgraded to 5.4.230112
Configured "--offline" in ntopng.conf but ntopng still trying to connect to web.

![image](https://user-images.githubusercontent.com/67421019/212172442-6119598e-4d91-4f03-b4a6-21dec60adee5.png)

**Comment by MatteoBiscosi** [comment]
The issue should be fixed with update that is going to be available in a couple of hours

**Comment by atemix** [comment]
@MatteoBiscosi, its fixed, thx
