### ISSUE TITLE
Unable to disable items in Category Lists

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#7101]
CentOS 8 Stream
ntopng Enterprise L v.5.4.230112

What happened:
Trying to disable items in Category Lists, but nothing happened.
Items still enabled after edit.
But on some instances lists were disabled correctly.

![image](https://user-images.githubusercontent.com/67421019/212245010-f1493890-9bb3-4363-8ef7-ad7367cf9aeb.png)

**Comment by MatteoBiscosi** [comment]
Hi @atemix could you please report if you have some error in your `journalctl -e -u ntopng` ? cause i tried to reproduce it but i could enable and disable the blacklists without problems

**Comment by atemix** [comment]
@MatteoBiscosi, no errors

Jan 12 23:05:47 ntopng[3279]: 12/Jan/2023 23:05:47 [SyslogCollectorInterface.cpp:401] Collecting events on syslog://X.X.X.X:5140
Jan 12 23:05:56 ntopng[3279]: 12/Jan/2023 23:05:56 [SyslogCollectorInterface.cpp:241] Incoming connection from X.X.X.X:55983
Jan 13 19:30:55 ntopng[3279]: radcli: rc_test_config: ntopng: no acctserver specified
Jan 13 19:31:32 ntopng[3279]: radcli: rc_test_config: ntopng: no acctserver specified
Jan 13 19:32:01 ntopng[3279]: radcli: rc_test_config: ntopng: no acctserver specified

**Comment by MatteoBiscosi** [comment]
The issue should be fixed with update that is going to be available in a couple of hours, please let me know

**Comment by atemix** [comment]
@MatteoBiscosi no luck, unable to disable items.
Btw, on instances with disabled categories, they were in red "error" status before, and on problematic instances they are green "enabled".

**Comment by lucaderi** [comment]
Works in dev. Next week we'll release a new stable that will also include this fix
