### ISSUE TITLE
Misleading Chart with Engaged Alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7102]
![Screen Shot 2023-01-13 at 18 09 33](https://user-images.githubusercontent.com/4493366/212378461-5dc66b0e-d3e8-491b-a935-652726d0f96e.png)
The above screenshot seems to be a bug as the chart is red but there are no records in table.

Zooming left instead we see the culprit.
![Screen Shot 2023-01-13 at 18 09 41](https://user-images.githubusercontent.com/4493366/212378677-a251504c-0bdb-40cf-8c2d-51ad8cc99594.png)

This is misleading for a user and a solution needs to be implemented.

**Comment by cardigliano** [comment]
Restoring the check in 863101326623371009d0076593c9b5e550c133fe should've fixed this

**Comment by lucaderi** [comment]
Seems to work now
