### ISSUE TITLE
Cannot dump flows to clickhouse (Unexpected data)

### ISSUE THREAD

**Issue by vobornik** [ntop/ntopng#7103]
**Environment**:
* OS name: Rocky Linux
* OS version: 8
* Architecture: Linux t-dc1-ntopng01 4.18.0-425.3.1.el8.x86_64 # 1 SMP Wed Nov 9 20:13:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* ntopng version/revision:
  * Version:        5.5.230113 [Enterprise/Professional build]
  * GIT rev:        dev:5219b5bfa1b5d294dbd3721dbb58c51f076f4f3e:20230113
  * Pro rev:        r5461
  * Platform:       x86_64
* clickhouse versions: 
  * Connected to ClickHouse server version 22.13.1 revision 54461.
  * ClickHouse client version 22.13.1.2178 (official build)

**What happened**:

After enabling dumping flows to the clickhouse database I cannot see any data in the DB. Log produces errors <code>Code: 632. DB::Exception: Unexpected data '|60252|323' after parsed IPv6 value '::': While executing CSVRowInputFormat</code> on a very first line of every csv file trying to import

**How did you reproduce it?**

<code>cat /var/lib/ntopng/tmp/clickhouse/clickhouse-3-38-50001.1673648290.csv | /usr/bin/clickhouse-client --port 9000 --host "127.0.0.1" --user "default" --password "XXXXX" -d "ntopng" --format_csv_delimiter="|" --format_csv_allow_double_quotes true --query="INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,SRC2DST_PACKETS,DST2SRC_PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR,IPV6_SRC_ADDR,IP_SRC_PORT,IPV4_DST_ADDR,IPV6_DST_ADDR,IP_DST_PORT,L7_PROTO,L7_PROTO_MASTER,L7_CATEGORY,FLOW_RISK,INFO,PROFILE,NTOPNG_INSTANCE_NAME,INTERFACE_ID,STATUS,SRC_COUNTRY_CODE,DST_COUNTRY_CODE,SRC_LABEL,DST_LABEL,SRC_MAC,DST_MAC,COMMUNITY_ID,SRC_ASN,DST_ASN,PROBE_IP,OBSERVATION_POINT_ID,SRC2DST_TCP_FLAGS,DST2SRC_TCP_FLAGS,SCORE,CLIENT_NW_LATENCY_US,SERVER_NW_LATENCY_US,CLIENT_LOCATION,SERVER_LOCATION,SRC_NETWORK_ID,DST_NETWORK_ID,INPUT_SNMP,OUTPUT_SNMP,SRC_HOST_POOL_ID,DST_HOST_POOL_ID,SRC_PROC_NAME,DST_PROC_NAME,SRC_PROC_USER_NAME,DST_PROC_USER_NAME,ALERTS_MAP,SEVERITY,IS_CLI_ATTACKER,IS_CLI_VICTIM,IS_CLI_BLACKLISTED,IS_SRV_ATTACKER,IS_SRV_VICTIM,IS_SRV_BLACKLISTED,IS_ALERT_DELETED,ALERT_JSON) FORMAT CSV"</code>

It produces error on the very first line of the csv file:
<code>Code: 632. DB::Exception: Unexpected data '|60252|323' after parsed IPv6 value '::': While executing CSVRowInputFormat: data for INSERT was parsed from stdin: (in query: INSERT INTO flows (FLOW_ID,IP_PROTOCOL_VERSION,FIRST_SEEN,LAST_SEEN,VLAN_ID,PACKETS,SRC2DST_PACKETS,DST2SRC_PACKETS,TOTAL_BYTES,SRC2DST_BYTES,DST2SRC_BYTES,SRC2DST_DSCP,DST2SRC_DSCP,PROTOCOL,IPV4_SRC_ADDR,IPV6_SRC_ADDR,IP_SRC_PORT,IPV4_DST_ADDR,IPV6_DST_ADDR,IP_DST_PORT,L7_PROTO,L7_PROTO_MASTER,L7_CATEGORY,FLOW_RISK,INFO,PROFILE,NTOPNG_INSTANCE_NAME,INTERFACE_ID,STATUS,SRC_COUNTRY_CODE,DST_COUNTRY_CODE,SRC_LABEL,DST_LABEL,SRC_MAC,DST_MAC,COMMUNITY_ID,SRC_ASN,DST_ASN,PROBE_IP,OBSERVATION_POINT_ID,SRC2DST_TCP_FLAGS,DST2SRC_TCP_FLAGS,SCORE,CLIENT_NW_LATENCY_US,SERVER_NW_LATENCY_US,CLIENT_LOCATION,SERVER_LOCATION,SRC_NETWORK_ID,DST_NETWORK_ID,INPUT_SNMP,OUTPUT_SNMP,SRC_HOST_POOL_ID,DST_HOST_POOL_ID,SRC_PROC_NAME,DST_PROC_NAME,SRC_PROC_USER_NAME,DST_PROC_USER_NAME,ALERTS_MAP,SEVERITY,IS_CLI_ATTACKER,IS_CLI_VICTIM,IS_CLI_BLACKLISTED,IS_SRV_ATTACKER,IS_SRV_VICTIM,IS_SRV_BLACKLISTED,IS_ALERT_DELETED,ALERT_JSON) FORMAT CSV). (UNEXPECTED_DATA_AFTER_PARSED_VALUE)</code>

**Debug Information**:

The first line of the CSV file:
```
2246462|4|1669353335|1669353335|0|14|10|4|1129|840|289|0|0|6|3232294386|::|60252|3232297237|::|10050|248|0|14|1|""||t-dc1-ntopng01|3|0|0|0|"zabbixng1"|"vm_printers4"|0|0|1:72MjLfs+6Nu+SPyyS5U1JBrzkH4=|0|0|182583042|0|0|0|0|0|0|1|1|620|632|151064543|0|0|0|||||00|0|0|0|0|0|0|0|1|"{""proto"": {}}"
```
ntopng is started with parametr <code>-F="clickhouse;127.0.0.1;ntopng;default;XXXXX"</code>

flows are imported via ZMQ interfaces <code>-i "tcp://10.127.0.51:5556" -i "tcp://10.130.0.51:5556"</code> and live flows (on the web) work as expected without any issue, historical is empty

```
t-dc1-ntopng01 :) select * from ntopng.flows;

SELECT *
FROM ntopng.flows

Query id: 4098bee6-5787-41a4-aeb4-e6d97ab95103

Ok.

0 rows in set. Elapsed: 0.007 sec.
```

```
t-dc1-ntopng01 :) show create table ntopng.flows;

SHOW CREATE TABLE ntopng.flows

Query id: 83dc9f5c-68fa-44f5-bc6a-8a595908417a

┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE ntopng.flows
(
    `FLOW_ID` UInt64,
    `IP_PROTOCOL_VERSION` UInt8,
    `FIRST_SEEN` DateTime,
    `LAST_SEEN` DateTime,
    `VLAN_ID` UInt16,
    `PACKETS` UInt32,
    `TOTAL_BYTES` UInt64,
    `SRC2DST_BYTES` UInt64,
    `DST2SRC_BYTES` UInt64,
    `SRC2DST_DSCP` UInt8,
    `DST2SRC_DSCP` UInt8,
    `PROTOCOL` UInt8,
    `IPV4_SRC_ADDR` UInt32,
    `IPV6_SRC_ADDR` IPv6,
    `IP_SRC_PORT` UInt16,
    `IPV4_DST_ADDR` UInt32,
    `IPV6_DST_ADDR` IPv6,
    `IP_DST_PORT` UInt16,
    `L7_PROTO` UInt16,
    `L7_PROTO_MASTER` UInt16,
    `L7_CATEGORY` UInt16,
    `FLOW_RISK` UInt64,
    `INFO` String,
    `PROFILE` String,
    `NTOPNG_INSTANCE_NAME` String,
    `INTERFACE_ID` UInt16,
    `STATUS` UInt8,
    `SRC_COUNTRY_CODE` UInt16,
    `DST_COUNTRY_CODE` UInt16,
    `SRC_LABEL` String,
    `DST_LABEL` String,
    `SRC_MAC` UInt64,
    `DST_MAC` UInt64,
    `COMMUNITY_ID` String,
    `SRC_ASN` UInt32,
    `DST_ASN` UInt32,
    `PROBE_IP` UInt32,
    `OBSERVATION_POINT_ID` UInt16,
    `SRC2DST_TCP_FLAGS` UInt8,
    `DST2SRC_TCP_FLAGS` UInt8,
    `SCORE` UInt16,
    `CLIENT_NW_LATENCY_US` UInt32,
    `SERVER_NW_LATENCY_US` UInt32,
    `CLIENT_LOCATION` UInt8,
    `SERVER_LOCATION` UInt8,
    `SRC_NETWORK_ID` UInt16,
    `DST_NETWORK_ID` UInt16,
    `INPUT_SNMP` UInt32,
    `OUTPUT_SNMP` UInt32,
    `SRC_HOST_POOL_ID` UInt16,
    `DST_HOST_POOL_ID` UInt16,
    `SRC_PROC_NAME` String,
    `DST_PROC_NAME` String,
    `SRC_PROC_USER_NAME` String,
    `DST_PROC_USER_NAME` String,
    `ALERTS_MAP` String,
    `SEVERITY` UInt8,
    `IS_CLI_ATTACKER` UInt8,
    `IS_CLI_VICTIM` UInt8,
    `IS_CLI_BLACKLISTED` UInt8,
    `IS_SRV_ATTACKER` UInt8,
    `IS_SRV_VICTIM` UInt8,
    `IS_SRV_BLACKLISTED` UInt8,
    `ALERT_STATUS` UInt8,
    `USER_LABEL` String,
    `USER_LABEL_TSTAMP` DateTime,
    `ALERT_JSON` String,
    `IS_ALERT_DELETED` UInt8,
    `SRC2DST_PACKETS` UInt32,
    `DST2SRC_PACKETS` UInt32
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(FIRST_SEEN)
ORDER BY (IPV4_SRC_ADDR, IPV4_DST_ADDR, FIRST_SEEN)
SETTINGS index_granularity = 8192 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.004 sec.
```

**Comment by vobornik** [comment]
Hi, managed to make it working - downgraded the clickhouse engine and everything works fine. IMHO either some bug in the clickouse build or some changes in import format ntopng does not follow:

```
[t-dc1-ntopng01 ~]$ clickhouse-client --user "default" --password "XXXXX"
ClickHouse client version 22.12.3.5 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.12.3 revision 54461.
```

**Comment by lucaderi** [comment]
Thank you: in fact it was working for us. We use

deri@dell 201> clickhouse-client --version
ClickHouse client version 22.12.3.5 (official build).
deri@dell 202> clickhouse-server --version
ClickHouse server version 22.12.3.5 (official build).
