### ISSUE TITLE
os-ntopng-enterprise plugin not showing / installing OPNSense

### ISSUE THREAD

**Issue by bdorr1105** [ntop/ntopng#7104]
**Environment**:
* OS name: [OPNSense 22.7.10_2 - FreeBSD 13.1-RELEASE-p5]
* OS version: [13.1]
* Architecture: [amd64]
* ntopng version/revision: [5.5.230113]

**What happened**: 

**How did you reproduce it?** I went to the documentation page for ntop and opnsense located at [NTOP Documentation](https://www.ntop.org/guides/ntopng/third_party_integrations/opnsense.html) and I accessed my OPNSense machine via SSH. I went into the shell and did the following

`pkg add https://packages.ntop.org/FreeBSD/FreeBSD:13:amd64/latest/ntop-1.0.pkg`

It downloaded and installed the package. I went and hit check for updates and says it processed 7 packages. Below is the log output

_

> Processing entries: .......... done
> OPNsense repository update completed. 820 packages processed.
> Updating SunnyValley repository catalogue...
> Fetching meta.conf: . done
> Fetching packagesite.pkg: .. done
> Processing entries: .... done
> SunnyValley repository update completed. 31 packages processed.
> Updating ntop repository catalogue...
> Fetching meta.conf: . done
> Fetching packagesite.pkg: . done
> Processing entries: . done
> ntop repository update completed. 7 packages processed.
> All repositories are up to date.
> Checking integrity... done (0 conflicting)
> Your packages are up to date.
> Checking for upgrades (45 candidates): .......... done
> Processing candidates (45 candidates): . done
> Checking integrity... done (0 conflicting)
> Your packages are up to date.
> ***DONE***

Event though everything looked to install like it should have, there is no available package like in the screenshot on ntop's docs. Please help

⚠ Please remove sensitive/private information from logs and pictures.
-->
What the documentation shows I am supposed to see on top, what I actually see on the bottom
<img width="1026" alt="what I am supposed to see" src="https://user-images.githubusercontent.com/12386911/212438430-e36944d8-bfc4-4b72-83a4-61fa175fad44.png">
![what i see](https://user-images.githubusercontent.com/12386911/212438433-fbb9a632-4050-4aca-a1bd-373b33bd7b1f.png)

**Comment by cardigliano** [comment]
@bdorr1105 could you try running from shell "pkg install os-ntopng-enterprise" ?

**Comment by bdorr1105** [comment]
@cardigliano , I ran the command from shell and still have the same exact issue. os-ntopng-enterprise is not available in the list of plugins

**Comment by cardigliano** [comment]
@bdorr1105 but do you see the ntopng Enterprise service configuration in the sidebar?

**Comment by bdorr1105** [comment]
@cardigliano, yes I did see ntopng Enterprise on the sidebar under services. It appears to be working

**Comment by cardigliano** [comment]
It seems OPNsense changed the way plugin packages are detected and displayed in the GUI, we are working to handle this. Anyway good that the plugin itself is working. Thank you

**Comment by bdorr1105** [comment]
Ok, thanks, how will we become aware the issue is fixed? Will this effect any updates?

**Comment by cardigliano** [comment]
We will release an update as soon as it's fixed, however you can use it already, it's affecting the plugins list only
