### ISSUE TITLE
Error While Displaying Observation Points

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7105]
After https://github.com/ntop/ntopng/commit/98cc2c32e096dd6aa5a985e166b236e6c80d77a0 there is a problem displayign observation points

![Screen Shot 2023-01-14 at 08 07 37](https://user-images.githubusercontent.com/4493366/212460490-11b82f99-26b1-4815-9e5c-80362502b083.png)

reports an empty page and this error on the console

14/Jan/2023 08:06:22 [LuaEngineNtop.cpp:45] ERROR: ntop_select_interface : expected string[@pos 1], got number

You can reproduce this bug at HS (194....)

**Comment by MatteoBiscosi** [comment]
Fixes in the latest release

**Comment by lucaderi** [comment]
Verified as fixed
