### ISSUE TITLE
Inconsistent Chart Labels

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7106]
![image](https://user-images.githubusercontent.com/4493366/212464201-2caa12d4-4d57-4526-87e4-c454fdf24764.png)

Clicking on top talkers (as shown in the above picture) it
- adds the hosts as numeric IPs instead of labels as in the top talkers table: this makes it hard to bind IPs to names. Solution: use labels everywhere
- even if series labels are added, the new series is not depicted as confirmed by the screenshot below
![image](https://user-images.githubusercontent.com/4493366/212464329-7d12d25a-97f0-44a7-a81f-818c977098a6.png)

**Comment by uccidibuti** [comment]
the problem is that sometimes in ts.lua rest API label field missing:
```
    {
      "series": [],
      "schema": "host:traffic",
      "max_points": 180,
      "query": {
        "host": "52.89.106.162",
        "ifid": "2"
        // label: "some name" <-MISSING 
      }
    },
```
