### ISSUE TITLE
Started after anomalous termination

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#7107]
**Environment**:
CentOS 8 Stream
4.18.0-408.el8.x86_64 #1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
amd64
5.4.230113

**What happened**:

Started after anomalous termination ([bug report](https://www.ntop.org/support/need-help-2/need-help/)) ntopng v.5.4.230113 (19201) [OS: ][pid: 3251973][options: --interface 'ens192' --interface 'tcp://127.0.0.1:5556c' --interface 'syslog://XXXXX:5140' --instance-name 'XXXXX' --data-dir '/home/ntopng-datadir' --pcap-dir '/home/n2disk-datadir' --http-port '0' --https-port '443' --max-num-hosts '65536' --max-num-flows '1048576' --local-networks 'XXXXX' --dump-flows 'clickhouse,[hidden]' --ignore-vlans --offline ]

Jan 14 13:00:12 ntopng[2287]: ntopng: json_object.c:514: json_object_object_length: Assertion `json_object_get_type(jso) == json_type_object' failed.
Jan 14 13:00:12 systemd[1]: ntopng.service: Main process exited, code=killed, status=6/ABRT
Jan 14 13:00:12 systemd[1]: ntopng.service: Failed with result 'signal'.
Jan 14 13:00:17 systemd[1]: ntopng.service: Service RestartSec=5s expired, scheduling restart.
Jan 14 13:00:17 systemd[1]: ntopng.service: Scheduled restart job, restart counter is at 1.
Jan 14 13:00:17 systemd[1]: Stopped ntopng high-speed web-based traffic monitoring and analysis tool.
Jan 14 13:00:17 systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
Jan 14 13:00:17 systemd[1]: Started ntopng high-speed web-based traffic monitoring and analysis tool.

**Comment by lucaderi** [comment]
Unable to reproduce on dev. Next week we'll release a new stable: please check it and re-open it if not working for you
