### ISSUE TITLE
Invisible interface alerts

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#7108]
Environment:
CentOS 8 Stream
4.18.0-408.el8.x86_64 https://github.com/ntop/ntopng/pull/1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
amd64
5.4.230113

What happened:
Unknown interface alerts in "all" view not accesible in "interface"

![image](https://user-images.githubusercontent.com/67421019/212470851-0ddcd60d-6e0d-4fc5-bd11-b013200fa3d7.png)

![image](https://user-images.githubusercontent.com/67421019/212470865-57fdef53-9f23-4cc6-aee5-b335d3c667da.png)

**Comment by cardigliano** [comment]
I need a way to reproduce this

**Comment by lucaderi** [comment]
Works for us in the development version that this week will become stable. After release please update and it should work
