### ISSUE TITLE
Flow alerts disabled at all, but still emitted

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#7109]
Environment:
CentOS 8 Stream
4.18.0-408.el8.x86_64 https://github.com/ntop/ntopng/pull/1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
amd64
5.4.230113

What happened:
Flow alerts disabled at all, but still emitted.

![image](https://user-images.githubusercontent.com/67421019/212475646-a147fbe2-dbd4-47e5-bc68-7ee923cfc196.png)

![image](https://user-images.githubusercontent.com/67421019/212475652-1991cf63-d551-45bf-9c57-592f5cfe8ad0.png)

**Comment by cardigliano** [comment]
Fixed, please check it with the next software update.

**Comment by NicoMaio** [comment]
Verified as fixed.
