### ISSUE TITLE
Discrepancy in Traffic Calculation (Interface Chart)

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7110]
![image](https://user-images.githubusercontent.com/4493366/212642337-f904b7f6-9921-4caa-a14e-e0da3d115ce3.png)

**Comment by uccidibuti** [comment]
Now Total is set with the value returned by rest api but there is something wrong:
![immagine](https://user-images.githubusercontent.com/12447209/214507022-dd491d13-4f04-4a32-9944-2b62e0d55ae8.png)

**Comment by lucaderi** [comment]
Discrepancy is still present but it has been mitigated.
