### ISSUE TITLE
Sankey Unable to Fit in page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7113]
![image](https://user-images.githubusercontent.com/4493366/212745973-838f6545-623d-45ef-b95c-125f5af5a174.png)

The Sankey image never shows as a whole in the page but a portion it is always outside the screen and a scrollbar is displayed.

This is to request to fix this problem fitting the chart in the page, and support resize when the window size changes

**Comment by MatteoBiscosi** [comment]
Fixes as requested
