### ISSUE TITLE
Missing Sankey Data 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7115]
This is all flows
![image](https://user-images.githubusercontent.com/4493366/212754184-4550fa15-8395-4c4e-8cca-7c32949861c4.png)

This is outbound (no inbound or local flows)

![image](https://user-images.githubusercontent.com/4493366/212754281-4d283a04-e939-4403-8ae4-3d359032104b.png)

and this is the flow list

![image](https://user-images.githubusercontent.com/4493366/212754327-41ef09b4-d013-4899-b3ac-1bc9bea37e53.png)

Obviously some data is missing from the chart

**Comment by MatteoBiscosi** [comment]
Fixed, pro repo
