### ISSUE TITLE
Duplicated Sankey Data

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7118]
The image below shows an implementation issue in the current sankey
![image](https://user-images.githubusercontent.com/4493366/212755483-7cd23947-2083-4b67-b632-b97d5408551c.png)

The middle line (the one with protocols) should NOT have repeated nodes. For instance, there should be one (1) node for TLS, one for HTTP.... and not several as depicted.

**Comment by MatteoBiscosi** [comment]
Verified as fixed
