### ISSUE TITLE
DNS Large Packet Alert

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#7119]
**Environment**:
ntopng Enterprise L v.5.5.230112 (Ubuntu 20.04.5 LTS) 

**What happened**:
Hello ntop team!
Probably a bug in the gui:
![image](https://user-images.githubusercontent.com/38549755/212842268-dbd036b1-2ff1-4910-8c45-bcad664ebf67.png)

Total size is 404 bytes, alert should only be when 512 or more bytes.
https://www.ntop.org/guides/nDPI/flow_risks.html#ndpi-dns-large-packet

**How did you reproduce it?**

**Debug Information**:

**Comment by NicoMaio** [comment]
Hi @martinscheu ,

I tried to reproduce this possible bug in the gui using this pcap file for [DNS Large Packet](https://github.com/ntop/nDPI/blob/dev/tests/pcap/dns_fragmented.pcap)
and this pcap file for [DNS Record with zero TTL](https://github.com/ntop/nDPI/blob/dev/tests/pcap/telegram.pcap).

In any case, the bug that you found is never comes out, so could you please share with us a pcap file of your scenario?

**Comment by lucaderi** [comment]
Fixed by https://github.com/ntop/ntopng/commit/ccd8890e54e299d9a6b6f2b45ed14aedde4e22e3
