### ISSUE TITLE
Add Exclusion Rule Note

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7125]
This is to request as for Acknowledgements
![Screen Shot 2023-01-19 at 09 46 47](https://user-images.githubusercontent.com/4493366/213396034-7371de49-6436-4275-8270-8523e0678f65.png)

 Add a comment field where a note can be added in the dialogue below.

![Screen Shot 2023-01-19 at 09 46 26](https://user-images.githubusercontent.com/4493366/213396079-f396220f-a08b-49d5-b343-ddf598e5038e.png)

Such comment must be visible from the "Behavioural Check Exclusions" page

**Comment by NicoMaio** [comment]
Verified the implementation.
