### ISSUE TITLE
Missing Reload Icon

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7133]
![Screen Shot 2023-01-21 at 09 41 03](https://user-images.githubusercontent.com/4493366/213859305-41a669f0-fb8e-4260-8230-f213eeae53f3.png)
![Screen Shot 2023-01-21 at 09 40 56](https://user-images.githubusercontent.com/4493366/213859306-0a5e2c0a-f0df-4fbe-8235-90389cc4a80c.png)

**Comment by MatteoBiscosi** [comment]
Added reload button on both pages

**Comment by lucaderi** [comment]
Verified as fixed
