### ISSUE TITLE
Implement CIDR support in "Historical Flows"

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7138]
In "Historical Flows"and "Flow Alerts", it is requested to implement CIDR support (e.g. 192.168.1.0/24) in IP address fields.

**Comment by cardigliano** [comment]
3a36fb9ba3cf6280316c11de645d704a5c65cc36 adds CIDR support for Historical Flows

**Comment by cardigliano** [comment]
@uccidibuti please add a CIDR validator for the 'cidr' data type

<img width="810" alt="Screen Shot 2023-01-25 at 14 37 47" src="https://user-images.githubusercontent.com/7548711/214578192-69b54a15-bb76-401d-9e1c-bf407ed8b45b.png">

**Comment by cardigliano** [comment]
Seems to be working for me, also with vlan (192.168.0.0/24@12)

**Comment by lucaderi** [comment]
Not working. See below
![Screen Shot 2023-01-31 at 12 53 43](https://user-images.githubusercontent.com/4493366/215752973-01c4b67e-48c8-4a2d-8966-c83a5e63c9b7.png)
then click on the host. 
![Screen Shot 2023-01-31 at 12 53 36](https://user-images.githubusercontent.com/4493366/215752980-8bd433fc-f629-413f-a982-d12a9b7d2bcb.png)
This is the SQL

SELECT L7_PROTO,L7_PROTO_MASTER,SCORE,TOTAL_BYTES,toInt32(FIRST_SEEN) FIRST_SEEN,toInt32(LAST_SEEN) LAST_SEEN,STATUS,FLOW_RISK,INFO,INPUT_SNMP,OUTPUT_SNMP,FLOW_ID,VLAN_ID,IP_PROTOCOL_VERSION,IPv4NumToString(IPV4_SRC_ADDR) IPV4_SRC_ADDR_FORMATTED,IPv4NumToString(IPV4_DST_ADDR) IPV4_DST_ADDR_FORMATTED,IPv6NumToString(IPV6_SRC_ADDR) IPV6_SRC_ADDR_FORMATTED,IPv6NumToString(IPV6_DST_ADDR) IPV6_DST_ADDR_FORMATTED,IP_SRC_PORT,IP_DST_PORT,IPv4NumToString(PROBE_IP) PROBE_IP_FORMATTED,SRC_LABEL,DST_LABEL,CLIENT_LOCATION,SERVER_LOCATION,COMMUNITY_ID,NTOPNG_INSTANCE_NAME,ALERT_JSON,ABS(LAST_SEEN - FIRST_SEEN) as TIME_DELTA,(TOTAL_BYTES / (TIME_DELTA + 1)) * 8 as THROUGHPUT FROM flows WHERE ((INTERFACE_ID=2) AND ((IP_PROTOCOL_VERSION = 4) AND( (IPV4_SRC_ADDR=IPv4StringToNum('1.62.203.0/24')) OR (SRC_LABEL=('1.62.203.0/24')) ))) AND (FIRST_SEEN >= 1675164199 AND FIRST_SEEN <= 1675165999 AND LAST_SEEN <= 1675165999)  ORDER BY TOTAL_BYTES asc LIMIT 10

**Comment by cardigliano** [comment]
One of the Network CIDR filters should be used for subnets:
<img width="808" alt="Screen Shot 2023-01-31 at 14 19 59" src="https://user-images.githubusercontent.com/7548711/215771531-83dd1a92-6df9-4fab-9650-d8bb4d8ef918.png">

@uccidibuti it seems the IP field is accepting subnets, please fix the validation to accept IP only

**Comment by cardigliano** [comment]
CIDR are also allowed in IP filters now (autodetected at query time)
