### ISSUE TITLE
Implement Health REST API Calls

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7141]
Currently ntopng health counters are not exported via REST API making ntopng hard to monitor.

This ticket is to request to implement various REST API calls for reporting the same information reported via the Health menu

![bug](https://user-images.githubusercontent.com/4493366/214111618-01a8bf73-1918-41bf-b81c-8d2f47012cee.png)

**Comment by cardigliano** [comment]
Please take a look at scripts/lua/rest/v2/get/system/stats.lua which seems to return similar data

**Comment by mzac** [comment]
Could this be used for a health check in Kubernetes?  Right now I use a get on port 3000 to verify that ntopng is running.

**Comment by NicoMaio** [comment]
> Could this be used for a health check in Kubernetes? Right now I use a get on port 3000 to verify that ntopng is running.

Yep, you can use a get on the /lua/rest/v2/get/system/health/stats.lua endpoint to know if ntpong is up and running.
This endpoint will be available on the next stable release 5.6.

**Comment by cardigliano** [comment]
New REST endpoints available now:

/lua/rest/v2/get/system/health/stats.lua
/lua/rest/v2/get/system/health/interfaces.lua
/lua/rest/v2/get/system/health/redis.lua
/lua/rest/v2/get/system/health/influxdb.lua
/lua/pro/rest/v2/get/system/health/clickhouse.lua

**Comment by lucaderi** [comment]
Verified as implemented
