### ISSUE TITLE
Can't build an image with the latest version of Nprobe in the docker (probably due to missing systemd)

### ISSUE THREAD

**Issue by firengate** [ntop/ntopng#7144]
Finding the cause of the problem leads me to the fact that systemd is missing by default in the Debian image (from which I'm building my image).

![image](https://user-images.githubusercontent.com/25734655/214180290-9c7459f7-f75e-40e9-94e7-1a0ab084e508.png)

Do you not have this problem? Perhaps you can provide your Dockerfile?

**Comment by firengate** [comment]
My Dockerfile:

FROM debian:bullseye

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
        apt-get -y -q install wget lsb-release gnupg libelf1 && \
        wget -q https://packages.ntop.org/apt/bullseye/all/apt-ntop.deb && \
        apt install ./apt-ntop.deb && \
        apt-get clean all

RUN apt-get update && \
        echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections && \
        apt-get -y install nprobe

**Comment by firengate** [comment]
If you install Nprobe by entering the container, the installation goes fine. The problem is with the image build.

**Comment by lucaderi** [comment]
Ok but this is the container you have built. not sure how I can help you with your image build

**Comment by firengate** [comment]
All right, let's go in from the other side.

You definitely have images that you upload to the Docker Hub. You're definitely doing it in some way. Do you install your packages the same way I do or do you have a different way of building the image? 

Last time you gave me a link to a Dockerfile for ntopng and it worked for me.
https://github.com/ntop/ntopng/issues/6987
https://raw.githubusercontent.com/ntop/docker-ntop/master/Dockerfile.ntopng.debian11.dev

Maybe you have the same Dockerfile for nprobe?

**Comment by lucaderi** [comment]
You can find all docker image sources here https://github.com/ntop/docker-ntop

**Comment by firengate** [comment]
> You can find all docker image sources here https://github.com/ntop/docker-ntop

Sorry I didn't notice your repository with dockerfiles, but with your dockerfile with Ubuntu 12 (dev version), the same problem.
![image](https://user-images.githubusercontent.com/25734655/214652128-4387fee9-4439-467b-96f4-713e33435fa4.png)

FROM ubuntu:22.04
MAINTAINER ntop.org

RUN apt-get update && \
    apt-get -y -q install wget lsb-release gnupg libelf1 && \
    wget -q http://apt.ntop.org/22.04/all/apt-ntop.deb && \
    dpkg -i apt-ntop.deb && \
    apt-get clean all

RUN apt-get update && \
    apt-get -y install nprobe

RUN echo '#!/bin/bash\nnprobe "$@" $NTOP_CONFIG' > /run.sh && \
    chmod +x /run.sh

ENTRYPOINT ["/run.sh"]
