### ISSUE TITLE
Make ntopng ElasticSearch cluster aware

### ISSUE THREAD

**Issue by mroe1234** [ntop/ntopng#715]
As per the below documentation, there is a way to improve performance when using elastic search as a backend by making ntopng cluster aware:
https://www.elastic.co/guide/en/elasticsearch/client/index.html
With an installation of significant size ( /16 )  we see the following:
25/Aug/2016 14:19:38 [ElasticSearch.cpp:57] WARNING: [ES] Export queue too long [32768]: expect drops

Here is my config file for reference:

-e=
-w=3000
--data-dir=/var/lib/ntopng
-m=10.0.0.0/16
-F="es;ntopng;ntopng-%Y.%m.%d;http://logstash.local.lan:9200/_bulk"
--dns=1
-i=tcp://127.0.0.1:5556
-x=150000

**Comment by simonemainardi** [comment]
I am not sure ntopng should be aware of the ES cluster. I believe this is something that must be handled by ES itself. Knowing the internals of an ES cluster shouldn't be done by ntopng. Recall that ES properly handles shards and replicas and transparently distributes data and indices across nodes in the cluster. Node failures, additions, etc are handled by ES internally.

The only thing I believe should be added to ntopng is the ability to specify the number of shards and replicas of any index.

However, by default, ES indices (including those created with ntopng) have 5 shards and 1 replica, e.g.:

```
simone@simone-VirtualBox-1:~$ curl 'http://localhost:9200/_cat/indices?v'
health status index             pri rep docs.count docs.deleted store.size pri.store.size 
yellow open   ntopng-2016.05.08   5   1      10336            0      5.4mb          5.4mb 
yellow open   ntopng-2016.06.23   5   1       1880            0      1.2mb          1.2mb 
yellow open   ntopng-2016.07.19   5   1       8008            0      2.3mb          2.3mb
```

so if you add 5 nodes to your ES cluster, then ES will be smart enough to distribute the index across all these nodes, routing each flow to the proper node during the indexing phase. This will boost the performance significantly over a single-node cluster.

**Comment by mroe1234** [comment]
The problem is when ntopng send 3.4 million records per hour to one of 5 hosts that one host drowns while the other 4 are basically idle. Yes the one host will redistribute the best it can but performance suffers greatly. There is a reason elastic search _recommends_ a cluster aware interface.

**Comment by dando-it** [comment]
To improve performance on ES  i suggest to raise the Bulk export values.

Unfortunately they aren't user configurable (feature request ?) so you need to modify the source and recompile: on _**Elasticsearch.cpp**_  in the _ElasticSearch::indexESdata()_ function,  change  _watermark_  ,_postbuf_ and _min_buf_size_ , the default values are conservative.

To get a "cluster aware" ntopng it's better to use an dedicated ES Client node (not a Data node) as a target for export.

With this configuration i write about 15M/hour flow record to an ES 2+1 nodes cluster without any issue.

**Comment by simonemainardi** [comment]
@dando-it would you like to lead the development of this feature?

**Comment by dando-it** [comment]
@simonemainardi  I'm sorry but I have to decline, at the moment I couldn't follow it.
I hope that my suggestion could be helpful for the product improvement.

**Comment by simonemainardi** [comment]
ok anyway thanks for the suggestion. regards.
