### ISSUE TITLE
Protocol Report Glitches 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7150]
Issues
- @0 (as VLAN) must be removed as VLAN 0 does not exist
- at thee bottom of the page there is a lot of space that needs to be removed

![image](https://user-images.githubusercontent.com/4493366/214318777-b79bfe44-78af-4dd9-8fd8-0f462e81361c.png)

**Comment by MatteoBiscosi** [comment]
Fixed pro repo

**Comment by lucaderi** [comment]
Verified as fixed
