### ISSUE TITLE
Inconsistent Data

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7153]
These two screenshots have been taken at the same time: there is a huge difference that cannot be explained

![Screen Shot 2023-01-24 at 21 32 22](https://user-images.githubusercontent.com/4493366/214403110-9896d53b-5062-4913-865f-85d2ab499cd9.png)
![Screen Shot 2023-01-24 at 21 32 15](https://user-images.githubusercontent.com/4493366/214403148-284499b9-58eb-4db9-83d2-2891d7b70f5b.png)

**Comment by lucaderi** [comment]
It looks like sort is bugged
![Screen Shot 2023-01-24 at 21 40 17](https://user-images.githubusercontent.com/4493366/214405755-f11a9cd4-8124-49aa-8ebc-71dd2afa725b.png)

**Comment by lucaderi** [comment]
![a](https://user-images.githubusercontent.com/4493366/214881810-3a01cf5a-fee1-4e66-8771-7821b10ff7fe.png)
Still bugged even after the sort

**Comment by NicoMaio** [comment]
Fixed, pro repo

**Comment by lucaderi** [comment]
Verified as fixed
