### ISSUE TITLE
Nprobe stops sending traffic after 15-20 minutes due to custom traffic disaggregation

### ISSUE THREAD

**Issue by firengate** [ntop/ntopng#7155]
**Environment**:
* OS name: Debian (docker)
* OS version: 11
* Architecture: amd64
* ntopng version/revision: 5.5.230113

**What happened**:
After creating custom traffic disaggregation, after about 20 minutes, ntopng sends a TCP ACK with a window of zero size, thus stopping the nprobe export.

zero win (tcpdump in nprobe container)
![image](https://user-images.githubusercontent.com/25734655/214540113-f1a0f7ef-683b-4c31-82cc-58f075ec9cf1.png)

test example custom traffic disaggregation
![image](https://user-images.githubusercontent.com/25734655/214536238-b3cbeba1-55b1-45ac-a639-4e704047551d.png)

When the problem starts, so does Time Drift begins to grow.
![image](https://user-images.githubusercontent.com/25734655/214536368-8012da93-f282-4961-ad69-6f06c4386dd8.png)

If you remove all custom traffic disaggregation and reboot, the problem disappears.

**How did you reproduce it?**
Create ~4 custom traffic disaggregation.
Drain netflow via nrpobe over ZMQ to ntopng.
Wait for 15-30 minutes.

**Comment by firengate** [comment]
This is what it looks like on the graph.
![image](https://user-images.githubusercontent.com/25734655/214552162-711e5261-ad48-4fd1-9f68-f583d5f775e9.png)

Time Drift will grow indefinitely until all custom traffic disaggregation is removed.
![image](https://user-images.githubusercontent.com/25734655/214552218-fa6ebf99-aec4-4773-aaf4-0c9b50733d11.png)

**Comment by lucaderi** [comment]
We're checking it. From you report it seems the problem is on the ntopng side.

**Comment by cardigliano** [comment]
@remackad we are unable to reproduce this, thus we need more details:

- are you pushing data from 1 nprobe or multiple instances?
- are you running ntopng and nProbe on different machines?
- could you also provide the ntopng and nprobe configuration files?
 
Thank you.

**Comment by firengate** [comment]
> * are you pushing data from 1 nprobe or multiple instances?

From 1 nprobe.

> * are you running ntopng and nProbe on different machines?

Yes, but I've tried it on one machine as well.

ntopng config
-i="tcp://*:1234c"
-X=1500000
-x=250000
--redis=redis
-F="clickhouse;10.0.0.4;ntopng;default;xxxxxxxxxxxxxxxxxxxxxx"
-m="10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16,198.18.0.0/15"
--ndpi-protocols=/var/lib/ntopng/protos.txt
--dns-mode=1
--disable-autologout

nprobe config
--ntopng="zmq://10.0.0.3:1234"
--zmq-probe-mode
--collector-port=2055
-n=none
-i=none
-b=1
--redis="10.200.1.2"
--flow-deduplication=15
--local-networks="10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16,198.18.0.0/15"
--ndpi-custom-protos="/etc/nprobe/ndpi-custom-protos.txt"
--disable-startup-checks
--biflows-export-policy=1
-z="<TCP[:UDP[:O]]>"
-T="%EXPORTER_IPV4_ADDRESS %OBSERVATION_POINT_ID %DURATION_IN %DURATION_OUT %IN_SRC_MAC %OUT_DST_MAC %IPV4_SRC_ADDR %IPV4_DST_ADDR %IPV4_NEXT_HOP %IN_PKTS %IN_BYTES %FIRST_SWITCHED %LAST_SWITCHED %L4_SRC_PORT %L4_DST_PORT %INPUT_SNMP %OUTPUT_SNMP %PROTOCOL_MAP %IP_PROTOCOL_VERSION %PROTOCOL %SRC_TOS %DST_TOS %TCP_FLAGS %OUT_BYTES %OUT_PKTS %SRC_MASK %DST_MASK %ICMP_TYPE %ICMP_IPv4_TYPE %ICMP_IPV4_CODE %SRC_AS %DST_AS %IPV4_SRC_MASK %IPV4_DST_MASK %FRAGMENTS %RETRANSMITTED_IN_PKTS %RETRANSMITTED_OUT_PKTS %OOORDER_IN_PKTS %OOORDER_OUT_PKTS %L7_PROTO %L7_PROTO_NAME %IPV6_SRC_ADDR %IPV6_DST_ADDR %IPV6_SRC_MASK %IPV6_DST_MASK %postNATSourceIPv4Address %postNatDestinationIPv4Address %postNAPTSourceTransportPort %postNAPTDestinationTransportPort %minimumIpTotalLength %maximumIpTotalLength"

**Comment by cardigliano** [comment]
@remackad while we try to reproduce this, one more question: did you see an high CPU load on some core when this was happening?

**Comment by firengate** [comment]
Updated ntopng and nprobe today and tested for a few hours. The problem is no longer there.

I have actually noticed that when the CPU core is overloaded, nprobe's traffic reception stops temporarily, but not for long and then resumes.

I'll think about balancing the load.

Thank you very much for your assistance!

**Comment by cardigliano** [comment]
Thank you for the update, please let us know if the issue occurs again
