### ISSUE TITLE
RRD does not scale well (~140k hosts, ~40k of which are local)

### ISSUE THREAD

**Issue by mroe1234** [ntop/ntopng#716]
For large installations RRD without RRDCached is impossibly slow.  We are currently using an SAN with 24disks in a raid 10 and browsing the data is too slow.  Either RRDCached needs to be added or something like influxDB needs to be investigated.

**Comment by simonemainardi** [comment]
can you please give us an indication of the number of hosts you are monitoring. Also are you keeping l7 statistics?

**Comment by mroe1234** [comment]
~140k hosts, ~40k of which are local.

**Comment by lhxhanson** [comment]
If you dump flows into database, the historical page will be very very slow. Every time you open the historical page, even the the auto update, ntopng will do some query.

**Comment by simonemainardi** [comment]
@lhxhanson what you reported has been addressed in, in the latest dev build, if you browse to the historical page but don't visit the flows page, no query will be performed.

**Comment by lhxhanson** [comment]
@simonemainardi  I am looking forward to the stable version. Thx~

**Comment by lucaderi** [comment]
We are planning to replace RRD in an upcoming version, so we'll take your request into account.

**Comment by simonemainardi** [comment]
Several optimizations have been made to reduce the pressure on the IO. Recent commits demonstrate this.

Moreover, from a UI perspective, the user has now the ability to control which RRD are generated for each interface, local host, and device:

![image](https://user-images.githubusercontent.com/3397663/33486625-15de5e10-d6ab-11e7-9584-883c645d7185.png)

So we believe we can close this issue now as we won't push further on speeding up rrds but will replace RRD with an home-grown timeseries database.
