### ISSUE TITLE
Host Sankey Page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7160]
- Missing dropdown label
- Missing Reload Icon
- Dropdown must be aligned to the right page side

![Screenshot 2023-01-25 at 15 32 25](https://user-images.githubusercontent.com/4493366/214590612-3e8d2e7a-4908-44b4-af18-dbe836d5dd24.png)

**Comment by MatteoBiscosi** [comment]
This issue should be fixed, added the same label like for the live flows
![image](https://user-images.githubusercontent.com/49585191/215470084-545170ab-4c79-44e6-b4aa-b3c5a1c55b86.png)

**Comment by lucaderi** [comment]
Verified as fixed
