### ISSUE TITLE
Minor Glitches in Interface Table Charts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7161]
![image](https://user-images.githubusercontent.com/4493366/214594123-3ec37cf3-5bb6-4f7d-bdbe-7b71d2b0559e.png)

- avoid cutting hostnames when too long. Fix: use a longer shorten value as we have space
- alight measurement to the right

**Comment by MatteoBiscosi** [comment]
Partially fixed

**Comment by lucaderi** [comment]
![bu](https://user-images.githubusercontent.com/4493366/214824917-660be007-a988-40b1-bbaf-0ec7d7995b09.png)
- Labels are still cut
- totals do not match
- sort is wrong

**Comment by lucaderi** [comment]
Hyperlinks not yet working

**Comment by MatteoBiscosi** [comment]
Now the issue should be fixed, hyperlinks seems working and remote hosts hyperlinks are removed (remote hosts don't have timeseries)
![image](https://user-images.githubusercontent.com/49585191/215448737-ffb82ae1-7194-4bbf-b94e-eb97e6df9d89.png)

**Comment by lucaderi** [comment]
Unfortunately the alert is not triggered for hosts that are not in memory (active). This is not the idea as external alerts can be triggered for any host

**Comment by lucaderi** [comment]
Verified as fixed.
