### ISSUE TITLE
Info field for BITTORRENT hash is empty

### ISSUE THREAD

**Issue by colinvv2** [ntop/ntopng#717]
I am capturing with Nprobe via Proxy using IPFIX and do have '%BITTORRENT_HASH' selected for export.

ntopng.conf:
-n=3
-w=3000
-W=0
-g=-1
-S=all
-F=mysql;localhost;ntopng;flows;ntopng;*****
-d=/storage/ntopng
-G=/var/run/ntopng.pid
-i=tcp://127.0.0.1:5556

nprobe-none.conf:
-n=none
-i=none
-t=60
-d=60
-a=0
-e=1
-B=10
-w=128000
-z=0
-S=1:1
-E=0:0
-g=/var/run/nprobe-none.pid
-3=6343
--zmq=tcp://127.0.0.1:5556
--vlanid-as-iface-idx=none
-T=%IN_BYTES %IN_PKTS %PROTOCOL %SRC_TOS %TCP_FLAGS %L4_SRC_PORT %IPV4_SRC_ADDR %INPUT_SNMP %L4_DST_PORT %IPV4_DST_ADDR %OUTPUT_SNMP %LAST_SWITCHED %FIRST_SWITCHED %L7_PROTO %BITTORRENT_HASH
-V=10
--dump-stats=/var/log/nprobe/none-0_flows_stats.txt

**Comment by simonemainardi** [comment]
Hi,

you can't use nprobe in proxy mode if you want to the bittorrent hash. You need to send nprobe the real traffic in order for its engine to properly extract the hash from the flow.

**Comment by colinvv2** [comment]
But if when I try to collect through 'eth0', I only see the flows from the switches that are reporting their flows. I don't actually get the customer traffic.

The switches are sending their flows via UDP port 6343... but I can only get the Proxy to listen there!

nprobe-eth0.conf:
-n=none
-i=eth0
-s=128
-t=60
-d=60
-a=0
-e=1
-B=10
-w=128000
-z=0
-S=1:1
-E=0:0
-g=/var/run/nprobe-eth0.pid
--zmq=tcp://127.0.0.1:5556
--vlanid-as-iface-idx=none
-T=%IN_BYTES %IN_PKTS %PROTOCOL %SRC_TOS %TCP_FLAGS %L4_SRC_PORT %IPV4_SRC_ADDR %INPUT_SNMP %L4_DST_PORT %IPV4_DST_ADDR %OUTPUT_SNMP %LAST_SWITCHED %FIRST_SWITCHED %L7_PROTO %BITTORRENT_HASH
-V=10
--dump-stats=/var/log/nprobe/eth0-0_flows_stats.txt

**Comment by colinvv2** [comment]
So how can I do this using a centralized ntop 'collector' within my network?
http://www.ntop.org/ntopng/monitoring-bittorrent-traffic-with-ntopng/

**Comment by lucaderi** [comment]
In proxy mode not all fields proxied: the bit torrent hash is one of those. Please file an issue request on nprobe where we can implement that

**Comment by colinvv2** [comment]
I have turned off 'proxy' and now have nprobe running as 'file' and sending to ntopng. Archive to MySQL is working for ntopng and I am still able to search previous flows. Will the 'file' nprobe be able to get the hash if I set for ?

nprobe-file.conf:
-n=none
-i=none
-t=60
-d=60
-a=0
-e=1
-B=10
-w=128000
-z=0
-S=1:1
-E=0:0
-g=/var/run/nprobe-file.pid
-3=6343
--zmq=tcp://127.0.0.1:5556
--vlanid-as-iface-idx=none
-T=%IN_BYTES %IN_PKTS %PROTOCOL %SRC_TOS %TCP_FLAGS %L4_SRC_PORT %IPV4_SRC_ADDR %INPUT_SNMP %L4_DST_PORT %IPV4_DST_ADDR %OUTPUT_SNMP %LAST_SWITCHED %FIRST_SWITCHED %L7_PROTO %BITTORRENT_HASH
-V=10
--dump-stats=/var/log/nprobe/file-0_flows_stats.txt

**Comment by lucaderi** [comment]
It looks that even in non-proxy mode there is a problem.

**Comment by simonemainardi** [comment]
I have tested the combination of nProbe and ntopng with bittorrent traffic and I can say that the hash is propagated properly:

![image](https://cloud.githubusercontent.com/assets/3397663/18049408/64faadfa-6de8-11e6-9165-d4f422c4208a.png)

@colinvv2 , bittorrent hash extraction requires deep packet inspection. nProbe, in order to obtain that hash, leverages on the nDPI engine but it _must see_ the real network traffic. IPFIX is just a flow export format that contains aggregated traffic information and not the actual traffic.

So, if you want to see the bittorrent hash, you must send nProbe the traffic that is flowing through the switches (e.g., via a mirror)

**Comment by colinvv2** [comment]
@simonemainardi,
Are you saying that by using the 'sflow' command in the switch, the hash info may not be sent through to the nProbe? We would need to use as a flow transmitter like one of the following:
- an nProbe application in the firewall itself
- an external piece of equipment on a 'mirror' port in the switch
- an intrusive 'bridge' device between the clients and the firewall

**Comment by simonemainardi** [comment]
Correct.

A fourth option could be to use a network tap.

See this for a deeper discussion: http://www.ntop.org/pf_ring/port-mirror-vs-network-tap/

**Comment by colinvv2** [comment]
So just to clarify... only direct access to traffic, via nProbe, can extract the 'hash'?

Any way to get nProbe installed on my old Fedora firewalls... going way back. Cores 6/9/13?

**Comment by simonemainardi** [comment]
@colinvv2 correct. Check if you can leverage on one of the existing packaged distributions at http://packages.ntop.org/

**Comment by lucaderi** [comment]
In order to extract the hash it is necessary to see the whole packet, so a direct packet capture is required
