### ISSUE TITLE
Implement REST API for Injecting Alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7170]
This is to request to implement a new REST API for injecting alerts in ntopng.

Furthermore, the Python API should be extended to support it.

**Comment by cardigliano** [comment]
Doc in 4072283a75d2dd9204cb7d5579774fd3867450c3

**Comment by lucaderi** [comment]
I have run  
$ curl -u admin:admin -H "Content-Type: application/json" -d '{"ifid": 0, "host": "192.168.1.134", "vlan": 0, "score": 100, "info": "Custom alert triggered thrugh the REST API"}' http://localhost:3000/lua/rest/v2/trigger/host/alert.lua
{"rc_str_hr":"Success","rc":0,"rsp":[],"rc_str":"OK"}

but no alert appears in host alerts.

**Comment by cardigliano** [comment]
The API now returns a failure when the check is not enabled

{"rc_str_hr":"Unknown","rc":-2,"rc_str":"NOT_ENABLED","rsp":[]}

**Comment by lucaderi** [comment]
Unfortunately the alert is not triggered for hosts that are not in memory (active). This is not the idea as external alerts can be triggered for any host

**Comment by cardigliano** [comment]
TODO: This check should be able to trigger alerts also for inactive hosts, this requires reworking the check architecture (at least for this check) to be able to push alerts directly to the recipients (including the database)
