### ISSUE TITLE
Chart Visualisation Issues

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7171]
In the image below there are a few bugs
- it is impossible to see the various timeseries. Better to make them stacked or in another way as currently it is unreadable.
- Clicking on the host name a series is added and this is ok. However it is missing an icon (as in alerts) or similar that allows the analyst to jump to the host timeseries view. This needs to be added.
- Finally there is a scale problem as the pi3 chart is very low compared to the other charts

![a](https://user-images.githubusercontent.com/4493366/214894207-125a6aa0-1c5c-4279-99c3-0d96bc369844.png)

**Comment by MatteoBiscosi** [comment]
Added like in the other pages the button in the action column
![image](https://user-images.githubusercontent.com/49585191/215457255-eab45062-83de-4ba6-82f5-de8f9466c6e6.png)
