### ISSUE TITLE
Unable to find timezone: using UTC (official dev docker image)

### ISSUE THREAD

**Issue by firengate** [ntop/ntopng#7172]
The problem exists only on the dev version of the image.
https://hub.docker.com/r/ntop/ntopng.dev

The stable version does not have this problem.

![image](https://user-images.githubusercontent.com/25734655/215019414-862f395f-be9b-4479-85f1-cf2f2d181606.png)

A localtime file exists.
![image](https://user-images.githubusercontent.com/25734655/215019434-f1a1db3a-3047-4fa9-8ea3-b9113113deb9.png)

**Comment by lucaderi** [comment]
Can you report the output of ```ls -l /etc/localtime``` ?

**Comment by firengate** [comment]
> Can you report the output of `ls -l /etc/localtime` ?

root@ntopng:/srv/ntopng# docker exec -it ntopng /bin/bash
root@3bf221385fc3:/# ls -l /etc/localtime
-rw-r--r-- 1 root root 1229 Oct 29 12:12 /etc/localtime

**Comment by lucaderi** [comment]
This is the problem. This file should be a symbolic link

deri@dell 202> ls -l /etc/localtime
0 lrwxrwxrwx 1 root root 31 Dec 15 06:47 /etc/localtime -> /usr/share/zoneinfo/Europe/Rome

if it is a file as the one you have we have no clue what is the timezone to use. Please make it standard

**Comment by firengate** [comment]
I figured it out. The thing is that docker compose, when mounting a localtime file, mounts it as a file, not as a symlink. I had to mount zoneinfo first, then in the run.sh file do from zoneinfo file symlink to localtime.

In fact, the localtime file has the same contents, but this does not work in 5.5 version, but it works in 5.4. This confused me.
