### ISSUE TITLE
ICMP not Supported

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7179]
![Screenshot 2023-01-27 at 19 24 05](https://user-images.githubusercontent.com/4493366/215165049-83e3c63d-c15c-4b20-8a71-6d393174d8e8.png)

**Comment by cardigliano** [comment]
Support for icmp added in https://github.com/ntop/PF_RING/commit/5200398e626cda2020162d96e288d9c29bcb00d7
