### ISSUE TITLE
Access Forbidden - nBox integration is disabled

### ISSUE THREAD

**Issue by colinvv2** [ntop/ntopng#719]
I am intermittently getting these errors in ntopng. I notice that the main menu items are different and some 'Access Forbidden' messages start to appear.
![image](https://cloud.githubusercontent.com/assets/21261036/18052220/022fe972-6dc7-11e6-8a95-ae0e6f18b1c8.png)

**Comment by simonemainardi** [comment]
acess forbidden means that you are trying to perform an administrator operation with a non-admin user. Please, check that.

If you still get the errors, post the exact urls visited when getting the message

**Comment by colinvv2** [comment]
But I am an admin user... and it works properly most of the time. I think it has something to do with never logging in/out and just leaving the browser open all of the time. I do have it set to 'stay loggend in'.

**Comment by colinvv2** [comment]
Since the main menu has changed... I can't even log out! What is the query string URL to log off manually?
![image](https://cloud.githubusercontent.com/assets/21261036/18057573/895d1534-6dde-11e6-8806-25cf05044453.png)

**Comment by simonemainardi** [comment]
delete cookies and it will come back

**Comment by colinvv2** [comment]
Ok. So that worked... and got me back to a regular menu.

I see the logout URL is:
http://127.0.0.1:3000/lua/logout.lua

So is this a problem with the User preferences setting for 'Auto Logout' set to 'Off'?

**Comment by simonemainardi** [comment]
autologout doesn't 'hide' the logoff menu, it's just to prevent ntopng from expiring user sessions.

Anyway, is the 'access forbidden' problem solved now?

**Comment by simonemainardi** [comment]
solution given. closing.
