### ISSUE TITLE
Add AS/Network Timeseries

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7192]
For each AS/network defined add timeseries for
- latency (should be already implemented)
- retransmissions

**Comment by MatteoBiscosi** [comment]
Implemented like requested for both, ASN and Networks
![image](https://user-images.githubusercontent.com/49585191/219343683-9039a828-2c0d-4e95-8153-b346310fdd72.png)
![image](https://user-images.githubusercontent.com/49585191/219343568-dab2e32c-1237-48c2-ab6e-48bea736d655.png)
