### ISSUE TITLE
Host pool limit

### ISSUE THREAD

**Issue by not-known** [ntop/ntopng#7193]
**What would you like to add or change?**:
At the moment there is a hard limit on how many host pools can be created. This limit is 128 pools. I'd like to have (much) more host pools. Is it possible to raise the limit to say 4000 or more?

**Why do you and others need this?**:
I'm using ntopng as an ISP and have many clients using our services. Every client has one or more IP4/6 subnets and what I'd like to have is a flow aggegation per client. This way I have a quick option to view all flows corresponding to a client. This saves me from searching in IPAM, creating custom filters, etc.

**Comment by MatteoBiscosi** [comment]
Your case can be achieve by using the networks options.
Currently we decided to not increase the Host Pool limit
