### ISSUE TITLE
"Suspicious Entropy" alert disabled, but still emitted

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#7200]
Environment:
CentOS 8 Stream
4.18.0-408.el8.x86_64 https://github.com/ntop/ntopng/pull/1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
amd64
5.6.230203

What happened:
"Suspicious Entropy" alert disabled, but still emitted.

![image](https://user-images.githubusercontent.com/67421019/216649630-2212892e-edd5-42ea-9df1-467cb644efa1.png)

![image](https://user-images.githubusercontent.com/67421019/216649731-03d80736-9ea7-4447-8096-94f3c01903a4.png)

**Comment by MatteoBiscosi** [comment]
Hi @atemix could you please reset to factory value the suspicious entropy alert, stop ntopng service and restart it? Then disable the alert again and let me know if new suspicious entropy issues are stil triggered
![image](https://user-images.githubusercontent.com/49585191/216968308-d0ed3fb0-1112-45cf-b2a8-bf500edfd76c.png)

**Comment by MatteoBiscosi** [comment]
Please update to the latest version before trying

**Comment by atemix** [comment]
Hi @MatteoBiscosi 
Its hangs on factory reset for this alert, but after a day alerts and a couple of reboots its stop emitting, so its ok =)

Now, another alert - "Desktop/File Sharing", is emitting, even disabled in conf.

**Comment by MatteoBiscosi** [comment]
Hi @atemix I updated the ntopng stable version, today, and everything should work correctly now, i checked the issue for all the checks and seems working. The only problem is that probably you need to reset the alerts configuration again, please let me know.

**Comment by atemix** [comment]
Hi @MatteoBiscosi After factory reset behavioural checks, configuring alerts and restart ntopng everything seems fine, alerts really disabled. Thx for help
