### ISSUE TITLE
Missing contents of httpdocs/dist in ntopng 5.6 stable

### ISSUE THREAD

**Issue by peterneutron** [ntop/ntopng#7203]
**Environment**:
* OS name: Arch
* OS version: rolling
* Architecture: aarch64
* ntopng version/revision: 5.6 release tarball

**What happened**:
`autogen.sh` doesn't pull in https://github.com/ntop/ntopng-dist and thus results in a broken login page see related issue https://github.com/ntop/ntopng/issues/6805

**Comment by cardigliano** [comment]
We created a 5.6 branch in ntopng-dist and it seems to be working now:
```
ntopng % git branch -a
* 5.6-stable
  dev
 
ntopng % ./autogen.sh 
From https://github.com/ntop/ntopng-dist
 * [new branch]      5.6-stable -> origin/5.6-stable
Submodule path 'httpdocs/dist': checked out '6f667966d947e620c9bf3faf72cbc31a1bbffeec'
From https://github.com/ntop/ntopng-e2e-tests
 * [new branch]      5.6-stable -> origin/5.6-stable
Wait please...

Now run ./configure
```

**Comment by peterneutron** [comment]
Can compile `5.6-stable, 5.4-stable, dev` with git clone but still not possible using any release tarball because of the missing `.git` directory. Running ./autogen.sh then obviously fails with the following.

```
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

Affects any version > `5.2.1`

**Comment by cardigliano** [comment]
Please note dist can be compiled with:

npm install
npm run build

The pre-built folder is mainly used to build packages

**Comment by peterneutron** [comment]
Thanks, working as expected now. The `npm` steps are missing from https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ntopng which I used as a build template for the `aarch64` package.
