### ISSUE TITLE
Problem with Filter on IP

### ISSUE THREAD

**Issue by joonasak** [ntop/ntopng#7204]
**Environment**:
* OS name: Ubuntu
* OS version: 22.04
* Architecture: amd64
* ntopng version/revision: 5.6.230203

**What happened**:
It has problem when try to filter IP.

<img width="631" alt="image" src="https://user-images.githubusercontent.com/85352105/216915385-33fe2248-b758-4313-85e9-abb8d9c869ab.png">

**How did you reproduce it?**
It's not error before upgrade.

**Comment by lucaderi** [comment]
@cardigliano @uccidibuti The dev version seems to be ok

**Comment by MatteoBiscosi** [comment]
Fixed in the last ntopng version
