### ISSUE TITLE
Slow Alert Page Load

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7209]
In the page below

![image](https://user-images.githubusercontent.com/4493366/217069431-ebbe1a8f-2974-4cf4-883b-57aa38866e3b.png)

when loading the data into the table is much slower than the above chart. I believe this is due to name resolution. This problem does not affect for instance the flow page, and thus it should be implemented the same way.

**Comment by MatteoBiscosi** [comment]
The issue seems fixed in the latest versions, please reopen if needed
