### ISSUE TITLE
Enabling HTTPS disables all access to web interface

### ISSUE THREAD

**Issue by pmerkner** [ntop/ntopng#721]
I stepped through the instructions for creating an SSL cert and added the config file entries to enable HTTPS on port 3001 and disable HTTP by using port 0.  This completely disabled the web interface.  I then commented out the HTTP setting and restarted the ntopng service, still no web access on either HTTP or HTTPS.  Commented out the HTTPS setting and restarted the service, access to the web interface via HTTP was restored.  Any suggestions for how to fix this and use HTTPS for the web interface?  

Config specifications:
ntopng version 2.5.160802 - Pro Small Business Edition
CenOS 7.2.1511

**Comment by simonemainardi** [comment]
hi, I've just tested again https on centos7 and everything works as expected.

```
# /usr/local/bin/ntopng -w 0 -W 3001
```

make sure to add the `https://` prefix in the browser url. If the issue still occurs, the add the full ntopng logs. You may have another process that is bound to port 3001.

**Comment by pmerkner** [comment]
Thanks, Simone.  I’ll try it again.  It could be the instructions in the
user manual for the command switches reference using the colon so –w=:0
–W=:3001.  I’ll give it a go without the colon (which I bet fixes the
issue).

_From:_ simonemainardi [mailto:notifications@github.com]
_Sent:_ Wednesday, August 31, 2016 12:06 PM
_To:_ ntop/ntopng ntopng@noreply.github.com
_Cc:_ pmerkner pmerkner@usgs.gov; Author author@noreply.github.com
_Subject:_ Re: [ntop/ntopng] Enabling HTTPS disables all access to web
interface (#721)

hi, I've just tested again https on centos7 and everything works as
expected.

# /usr/local/bin/ntopng -w 0 -W 3001

make sure to add the https:// prefix in the browser url. If the issue still
occurs, the add the full ntopng logs. You may have another process that is
bound to port 3001.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/ntop/ntopng/issues/721#issuecomment-243849940, or mute
the thread

**Comment by simonemainardi** [comment]
as it is explained in the manual and in the help, if you use the `:` ntopng will bind on the local address

**Comment by pmerkner** [comment]
That explains it.  I missed that in the manual!  Thanks again for the help,
Simone.

_From:_ simonemainardi [mailto:notifications@github.com]
_Sent:_ Thursday, September 1, 2016 1:50 AM
_To:_ ntop/ntopng ntopng@noreply.github.com
_Cc:_ pmerkner pmerkner@usgs.gov; Author author@noreply.github.com
_Subject:_ Re: [ntop/ntopng] Enabling HTTPS disables all access to web
interface (#721)

as it is explained in the manual and in the help, if you use the : ntopng
will bind on the local address

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/ntop/ntopng/issues/721#issuecomment-244002809, or mute
the thread

**Comment by simonemainardi** [comment]
thanks for reporting
