### ISSUE TITLE
Missing Alert Badge in Host Flow Page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7210]
In case a host has no active flows a warning message has to be reported

![image](https://user-images.githubusercontent.com/4493366/217088751-c75968f4-b7fc-4a74-9f79-0b4b4a2bfc14.png)

**Comment by NicoMaio** [comment]
The pr: #7211 fixes the issue.

**Comment by MatteoBiscosi** [comment]
Verified as fixed
