### ISSUE TITLE
Search Criteria missing with SQL Flowdump enabled

### ISSUE THREAD

**Issue by faisalusuf** [ntop/ntopng#722]
Hi,
With reference to the blog post on `Exploring Historical Data using ntopng`. I have configured the SQL dump of expired flows. I'm not sure if its working properly also I'm unable to locate the search criteria on WEB-GUI. The configurations are okay in my deployment? Please guide.

`ntopng --pid "/var/run/ntopng.pid\" --community "" --dump-flows "mysql;localhost;ntopng;flows;root;xxx" --local-networks "192.168.0.0/24,10.0.0.0/24"`

`31/Aug/2016 01:00:00 [MySQLDB.cpp:693] ERROR: MySQL error: [][0]
31/Aug/2016 01:00:00 [MySQLDB.cpp:589] Succesfully connected to MySQL [localhost:root] for interface em1
31/Aug/2016 01:00:00 [MySQLDB.cpp:549] Attempting to connect to MySQL for interface em1...
31/Aug/2016 01:00:00 [MySQLDB.cpp:693] ERROR: MySQL error: [][0]
31/Aug/2016 01:00:00 [MySQLDB.cpp:693] ERROR: MySQL error: [][0]
31/Aug/2016 01:00:00 [MySQLDB.cpp:589] Succesfully connected to MySQL [localhost:root] for interface lo
31/Aug/2016 01:00:00 [MySQLDB.cpp:549] Attempting to connect to MySQL for interface lo...
31/Aug/2016 01:00:00 [MySQLDB.cpp:693] ERROR: MySQL error: [][0]
31/Aug/2016 01:00:00 [MySQLDB.cpp:693] ERROR: MySQL error: [][0]
31/Aug/2016 01:00:00 [MySQLDB.cpp:589] Succesfully connected to MySQL [localhost:root] for interface em4
31/Aug/2016 01:00:00 [MySQLDB.cpp:549] Attempting to connect to MySQL for interface em4...
30/Aug/2016 04:53:42 [NetworkInterface.cpp:1061] WARNING: Use: sudo ethtool -K em1 gro off gso off tso off
30/Aug/2016 04:53:42 [NetworkInterface.cpp:1059] WARNING: If you have TSO/GRO enabled, please disable it
30/Aug/2016 04:53:42 [NetworkInterface.cpp:1058] Invalid packet received [len: 2574][MTU: 1518].
30/Aug/2016 04:53:02 [MySQLDB.cpp:589] Succesfully connected to MySQL [localhost:root] for interface lo
30/Aug/2016 04:53:02 [MySQLDB.cpp:589] Succesfully connected to MySQL [localhost:root] for interface em4
30/Aug/2016 04:53:02 [MySQLDB.cpp:549] Attempting to connect to MySQL for interface lo...
30/Aug/2016 04:53:02 [MySQLDB.cpp:589] Succesfully connected to MySQL [localhost:root] for interface em1
30/Aug/2016 04:53:02 [MySQLDB.cpp:549] Attempting to connect to MySQL for interface em4...
30/Aug/2016 04:53:02 [MySQLDB.cpp:549] Attempting to connect to MySQL for interface em1...
30/Aug/2016 04:53:01 [NetworkInterface.cpp:1538] Started packet polling on interface em4 [id: 2]...
30/Aug/2016 04:53:01 [NetworkInterface.cpp:1538] Started packet polling on interface lo [id: 1]...
30/Aug/2016 04:53:01 [NetworkInterface.cpp:1538] Started packet polling on interface em1 [id: 0]...
30/Aug/2016 04:53:01 [Ntop.cpp:531] Adding 192.168.0.23/24 as IPv4 local network for em1
30/Aug/2016 04:53:01 [Ntop.cpp:531] Adding 127.0.0.0/8 as IPv4 local network for lo
30/Aug/2016 04:53:01 [NtopPro.cpp:252] [LICENSE] ntopng is starting without a valid license
30/Aug/2016 04:53:01 [NtopPro.cpp:249] [LICENSE] ntopng systemId: ED427B7E7104A1D2
30/Aug/2016 04:53:01 [RuntimePrefs.cpp:34] Dumping alerts into syslog
30/Aug/2016 04:53:01 [PeriodicActivities.cpp:53] Started periodic activities loop...`

Ref: 
http://www.ntop.org/ntopng/exploring-historical-data-using-ntopng/
http://i1.wp.com/www.ntop.org/wp-content/uploads/2015/10/Screen-Shot-2015-10-11-at-10.44.53.png?w=1164

**Comment by simonemainardi** [comment]
search criteria are available in the 'historical data explorer' which is a pro feature. Remove the flag `--community`.

I can also see some generic mysql error from the logs. Check the mysql database and make sure you can connect to that.

**Comment by faisalusuf** [comment]
Hi simonemainardi,
Thanks for your response. Yes I can see the required tabs. Also I'm able to connect to database locally. Will try to get pro then.

Thanks
