### ISSUE TITLE
Implement peity charts to be put as component in pages

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7220]
![Screenshot 2023-02-08 at 19 02 39](https://user-images.githubusercontent.com/4493366/217615471-876aa1dd-4f5c-42e2-a122-760ab819aa61.png)
![Screen Shot 2023-02-13 at 12 33 12](https://user-images.githubusercontent.com/4493366/218447146-128411f0-af49-4174-aeaf-c8f13b6a3562.png)

**Comment by lucaderi** [comment]
@uccidibuti Missing code reference, example or anything that explains howto use this code

**Comment by MatteoBiscosi** [comment]
Implemented as requested by using Dygraph
