### ISSUE TITLE
Alert Window Too Wide Due to Data Repeated

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7222]
![image](https://user-images.githubusercontent.com/4493366/217640120-522f1566-17b1-4b4e-ab5b-bccf1358ba2c.png)

**Comment by NicoMaio** [comment]
Update description message.

![SuspiciousDGADomain](https://user-images.githubusercontent.com/55502486/218811565-2bb40cb4-d3d1-4168-8c1e-29042f0b402d.png)

**Comment by MatteoBiscosi** [comment]
Verified as fixed
