### ISSUE TITLE
Invalid Unidirectional Alert

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7224]
![image](https://user-images.githubusercontent.com/4493366/217644478-b440225b-b162-4ef7-9305-0d26f294f385.png)

**Comment by cardigliano** [comment]
This Flow Risk was evaluated on L7 Protocol Detection, on the first packet in case of ICMP. The Unidirectional Flow Risk spcifically is now evaluated on Flow End, fixing this issue, while other Risks are still evaluated on L7 Protocol Detection.

**Comment by lucaderi** [comment]
Verified as fixed
