### ISSUE TITLE
Is there any simple way to get all the local host that existing on the ntopng?

### ISSUE THREAD

**Issue by lhxhanson** [ntop/ntopng#723]
My now solution is use script to open the url 
get_hosts_data.lua?mode=local&currentPage=1&perPage=5000&sortColumn=column_ip&sortOrder=desc
If there any other people view the ntopng page in his browser, the hosts page also be 5000/per page, this will cause browser stuck.
So is there any other way to get all the local host that existing on the ntopng? Because after I get that, I can get every local host's json data.

**Comment by simonemainardi** [comment]
use your script to get paginated results. That is, rather than querying for 5k hosts, play with `currentPage` and `perPage` and call the `get_hosts_data` multiple times. Note that you may want to use flag `mode=local` in the url to get only local hosts. For example

```
http://localhost:3000/lua/get_hosts_data.lua?mode=local&currentPage=1&perPage=10&sortColumn=column_thpt&sortOrder=desc
```

**Comment by lhxhanson** [comment]
So if the perPage is only work in the login session not all the user will be more convenient.
