### ISSUE TITLE
Python Ntopg object attempt a connection test on bad url. 

### ISSUE THREAD

**Issue by giacomotontini** [ntop/ntopng#7231]
OS name:  Ubuntu 22.04
ntopng version/revision: 5.7.230203

main.py
```
from ntopng.ntopng import Ntopng
my_ntopng = Ntopng(auth_token={retracted}, url='http://{retracted}')
```

if you look closely how the init function of Ntopng object (ntopng.py) is written, it make a http GET request at `self.url` + `"/lua/self_test.lua"` an check if the response contains  json content.
That API endpoint doesn't exists anymore or it's not functioning properly (already tested even with Postman tools and curl) and returns an html page. 

Furthermore the error that the init function print is missleading and has no correlation to the actual error ("Invalid credentials or URL specified"). Even if the user and password (or token) are correct and the endpoint url is right, the user of that object has no control over the entpoint path that the library is using to test credential ("/lua/self_test.lua")

Disabling lines 55 and 56 of ntong.py
```
 # if(not(response.headers['Content-Type'].startswith('application/json'))):
 #     raise ValueError("Invalid credentials or URL specified")
```
and proceeding using my_ntopng object works and doesn't produce any errors. But obviously, this is a workaround.
I suggest using a GET on '/lua/rest/v2/create/ntopng/session.lua'. This route should be a POST, but if you make it as a GET, is returns a json response only if provided credentials are right.

**Comment by cardigliano** [comment]
@giacomotontini the self_test.lua endpoint (said that we should move it to the rest API) is actually available, it's working for me:

$ curl -u admin:password -H "Content-Type: application/json" -d '{"ifid": "0"}' http://localhost:3000/lua/self_test.lua
{"response":"OK"}

**Comment by cardigliano** [comment]
I moved the test endpoint to lua/rest/v2/connect/test.lua

curl -u admin:password http://localhost:3000/lua/rest/v2/connect/test.lua
{"rsp":[],"rc_str":"OK","rc":0,"rc_str_hr":"Success"}

**Comment by giacomotontini** [comment]
```
curl -u admin:admin -H "Content-Type: application/json" -H "Accept: application/json" -d '{"ifi
d": "0"}' -v http://10.255.3.119:3000/lua/self_test.lua
*   Trying 10.255.3.119:3000...
* Connected to 10.255.3.119 (10.255.3.119) port 3000 (#0)
* Server auth using Basic with user 'admin'
> POST /lua/self_test.lua HTTP/1.1
> Host: 10.255.3.119:3000
> Authorization: Basic ____
> User-Agent: curl/7.81.0
> Content-Type: application/json
> Accept: application/json
> Content-Length: 13
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Server: ntopng 5.4.230113 (x86_64)
< Set-Cookie: session=; path=/; HttpOnly; SameSite=lax
< Location: /lua/http_status_code.lua?message=not_found&referer=10.255.3.119%3A3000%2Flua%2Fself_test.lua&error_message=
* no chunk, no close, no size. Assume close to signal end
<

* Closing connection 0
```
I tried several times, changing few params but still no response in curl (error code 302)
Using postman i receive an html page reporting "You're not supposed to be here!
The requested page cannot be found"

In addition: within python Ntopng.py , the connection test is made using a GET requests with no additional query parameters or request body. 
No interface id, neither HTTP headers.

**Comment by cardigliano** [comment]
I realized you are using stable, I backported the test endpoint, it will be available with the next build

**Comment by giacomotontini** [comment]
Well I think I've found (my) issue.
I was running ntopng as a docker container using ntop/ntopng:latest tag but never pulling the new version.
