### ISSUE TITLE
Empty file in Historical flow download

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#7236]
Environment:
CentOS 8 Stream
4.18.0-408.el8.x86_64 https://github.com/ntop/ntopng/pull/1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
amd64
ntopng Enterprise L v.5.6.230215

What happened:
Historical flow download.
Configured filter "IP1 = x.x.x.x" -> export ok.
Configured filter "IP1 = x.x.x.x IP2 !=y.y.y.y" -> export ok.
Configured filter "IP1 = x.x.x.x IP2 !=y.y.y.y IP3 != z.z.z.z" -> export file is empty.

**Comment by NicoMaio** [comment]
Fixed in pro repo by a8cffb65f14c1315c87c76f8c0ec54cc1a8905c4

**Comment by NicoMaio** [comment]
Hi @atemix,

In the stable version, it should be fixed.
Please update and let me know.

**Comment by atemix** [comment]
Hi @NicoMaio 

Fixed, thanks for help
