### ISSUE TITLE
Local timezone in historical flow download

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#7237]
Environment:
CentOS 8 Stream
4.18.0-408.el8.x86_64 https://github.com/ntop/ntopng/pull/1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
amd64
ntopng Enterprise L v.5.6.230215

What happened:
Historical flow download.
Time filter configured in interface as from 16.02.2023 9:00 to 16.02.2023 19:00.
Exported flows in file are from 16.02.2023 6:00 to 16.02.2023 16:00.
Local timezone +3.

Flows export should strictly honor user timefilter as configured in interface.
Or add notification that in real search and export would be in UTC time?

**Comment by lucaderi** [comment]
FLow time is exported as UTC epoch, please describe exactly the issue you are reporting.

**Comment by atemix** [comment]
My mistake, no issue.
local time in ntopng gui and utc in csv export are the same time time, just misunderstand.
