### ISSUE TITLE
Invalid Search filter in Flows

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7249]
With @ is detected as hostname (and thus no record will be found)
<img width="558" alt="image" src="https://user-images.githubusercontent.com/4493366/220418574-e14ef493-9d66-4f71-b9d6-88836f23b5d2.png">

without as IP that is correct

<img width="468" alt="Screenshot 2023-02-21 at 18 35 46" src="https://user-images.githubusercontent.com/4493366/220418783-c8887a3f-19f3-486e-95d0-4345667efa8d.png">

This is to request to detect @ properly and search as IP + VLAN instead of hostname

**Comment by cardigliano** [comment]
Fixed 
<img width="614" alt="Screen Shot 2023-03-09 at 15 28 57" src="https://user-images.githubusercontent.com/7548711/224055923-81072104-94db-4435-9f4a-df7f75958160.png">

**Comment by lucaderi** [comment]
Verified as fixed
