### ISSUE TITLE
Update doc for proxy (trailing /)

### ISSUE THREAD

**Issue by fastlorenzo** [ntop/ntopng#725]
Today I tried to put ntopng behind an apache reverse proxy and I encountered the following issue : 
I followed the man that says : 

> [...] you must use ntopng with -Z "/ntopng/"

But it was not working. Then I noticed the following line in the logs :

> WARNING: -Z argument (/ntop/) cannot end with '/' (example /ntopng): skipped

Maybe the man example should be updated to remove the trailing / in the example provide.

Kr,
Lorenzo

**Comment by simonemainardi** [comment]
thank you
