### ISSUE TITLE
Historical Flows do not show server alias or IP, but one of the L7 web domains

### ISSUE THREAD

**Issue by aadlung** [ntop/ntopng#7254]
**Environment**:
* OS name: Debian
* OS version: 11.6
* Architecture: x86_64
* ntopng version/revision: ntopng Enterprise M v.5.6.230221

When browsing the *historical flows*, it seems the server hostname is using neither the reverse DNS, the IP or the alias, but just any of the domains the server is providing (webserver).

The server where ntopng runs is a web server providing dozens of domains, but I added an alias to the server and the reverse lookup of the IP also resolves to the alias.

This shows an example in the historical flows. It shows the server using "www.the...." as domain, which is neither the reverse lookup nor the alias. The Info column shows the actual web request domains which have been requested like www.tipo... .

<kbd>
<img width="2244" alt="image" src="https://user-images.githubusercontent.com/8441971/220681888-ec31a69e-da6f-4eaf-8344-a159878fe8b8.png">
</kbd>

When accessing the details, it shows that the web request actually was for a totally different domain www.tipo...

<kbd>
<img width="1524" alt="image" src="https://user-images.githubusercontent.com/8441971/220681916-b955a2fd-da76-476c-8602-c33fe5e84a53.png" border="1">
</kbd>

I would expect that the historical flow explorer shows it the same way than the live flows, having always the alias for the server as "server" column, or at least the IP or the reverse lookup but not anything of the L7 headers.

<kbd>
<img width="2619" alt="image" src="https://user-images.githubusercontent.com/8441971/220684338-ba686a3f-25ae-41b9-8c21-df794ef5ec67.png">
</kbd>

**Comment by NicoMaio** [comment]
Hi @aadlung,
in the stable version, it should be fixed. 
Now, if an alias is set on the client or server it's shown instead of the IP.
Please update and let me know.

**Comment by aadlung** [comment]
Thanks @NicoMaio  I can confirm it's working now, the historical flows page only shows the alias or IP for the flow, not the web domain.
