### ISSUE TITLE
Disable Redis Messages Thunderstorm 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7256]
1677082741.576047 [0 127.0.0.1:53566] "HSTRLEN" "ntopng.prefs.host_pools.details.1" "name"
1677082741.576165 [0 127.0.0.1:53566] "HGET" "ntopng.prefs.host_pools.details.1" "name"
1677082741.576466 [0 127.0.0.1:53566] "SMEMBERS" "ntopng.prefs.host_pools.members.1"
1677082741.576796 [0 127.0.0.1:53566] "HSTRLEN" "ntopng.prefs.host_pools.details.1" "policy"
1677082741.576921 [0 127.0.0.1:53566] "HGET" "ntopng.prefs.host_pools.details.1" "policy"
1677082741.679169 [0 127.0.0.1:53566] "HSTRLEN" "ntopng.prefs.host_pools.details.0" "name"
1677082741.679631 [0 127.0.0.1:53566] "HGET" "ntopng.prefs.host_pools.details.0" "name"
1677082741.680024 [0 127.0.0.1:53566] "SMEMBERS" "ntopng.prefs.host_pools.members.0"
1677082741.680382 [0 127.0.0.1:53566] "HSTRLEN" "ntopng.prefs.host_pools.details.0" "policy"
1677082741.680722 [0 127.0.0.1:53566] "HGET" "ntopng.prefs.host_pools.details.0" "policy"
1677082741.681114 [0 127.0.0.1:53566] "HSTRLEN" "ntopng.prefs.host_pools.details.1" "name"
1677082741.681478 [0 127.0.0.1:53566] "HGET" "ntopng.prefs.host_pools.details.1" "name"
1677082741.681844 [0 127.0.0.1:53566] "SMEMBERS" "ntopng.prefs.host_pools.members.1"
1677082741.682283 [0 127.0.0.1:53566] "HSTRLEN" "ntopng.prefs.host_pools.details.1" "policy"
1677082741.682675 [0 127.0.0.1:53566] "HGET" "ntopng.prefs.host_pools.details.1" "policy"
1677082741.700899 [0 127.0.0.1:53566] "HSTRLEN" "ntopng.prefs.host_pools.details.0" "name"
1677082741.701387 [0 127.0.0.1:53566] "HGET" "ntopng.prefs.host_pools.details.0" "name"

**Comment by MatteoBiscosi** [comment]
The issue seems fixed, please reopen if needed
