### ISSUE TITLE
Alert Flows get purged before the Flow Idle Timeout

### ISSUE THREAD

**Issue by aadlung** [ntop/ntopng#7257]
**Environment**:
OS name: Debian
OS version: 11.6
Architecture: x86_64
ntopng version/revision: ntopng Enterprise M v.5.6.230221

The server is a dedicated rented server at a Hetzner datacenter, running web services.

I have a flow idle timeout of 30 minutes, and Clickhouse active for historical flows. For some reasons, alert flows get purged from memory even after a few seconds (not all of them, some I can still see after 10+ minutes).

Do I miss something why they can get purged? Luca mentioned it could be a router time issue, but why would others stay longer - and the first/last seen time confirms it's just a few seconds ago?

Because I don't look at the alert list all the time, and the longer I have them available the better it is for me so I can look at alert flows even 30 minutes or longer (if I configure the idle flow timeout for many hours)?

<kbd>
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/8441971/220692050-c27ad2fe-aa5d-4bef-99a9-11becddfc0d4.png">
</kbd>

ntopng even confirms that the flow idle timeout is 30 minutes.

<kbd>
<img width="430" alt="image" src="https://user-images.githubusercontent.com/8441971/220690788-96379574-25c8-467d-a73f-5b2a9309effe.png">
</kbd>

<kbd>
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/8441971/220690871-8753e116-d561-4d0e-b726-826910f0847e.png">
</kbd>

**Comment by lucaderi** [comment]
@aadlung This is not a timer issue as you collect packets and not flows. It looks like. bug to investigate.

**Comment by NicoMaio** [comment]
Hi @aadlung,
Could you please share your ntopng and nprobe configurations?
My email address is maio@ntop.org.

**Comment by aadlung** [comment]
Hi @NicoMaio - that's my ntopng.conf, I've just replaced the IPs and credentials with random values.
I don't have any other configuration.
```
# cat ntopng.conf|grep -v "^#"
-G=/var/run/ntopng.pid
-i=enp41s0
-i=tun0
-m=148.1.1.1/32,46.1.1.1/32,192.168.0.0/24,10.0.0.0/24,fe80::fe80:fe80:fe80:fe80/64,2a01:2a01:2a01:2a01::2/64,127.0.0.0/8
-Z=/ntopng
--http-port=:3000
-F="clickhouse;127.0.0.1;ntopng;ntopng;secretpassword"
```

**Comment by NicoMaio** [comment]
In the example flow, it seems the server or the client sent a FIN packet consequentially ntopng purged the flow. 
Could you please share a pcap file of that test case?

**Comment by aadlung** [comment]
I just tried to use the "pcap download" on the host page of one of the hosts which had such an alert directly after it was purged from memory, but unfortunately the pcap downloads do not work - I will have to investigate why I can't export the pcap files.

So you mean if an alert flow gets a FIN (or in my new example I see a RST) it gets purged from memory (as it's not an alert any more) and would be visible in the historical flows only (because in the live flows I can't filter anyway)? Then this would work as designed, it's just annoying then that it is being removed from the alerts list after a FIN or RST and I have to search it again somehow on /lua/alert_stats.lua for example?

Because it looks like in the historical flows I still can find it. And I can even drill down to the flow details as well.

![image](https://user-images.githubusercontent.com/8441971/221604473-6916fe67-92b4-40a6-b923-4ed1ee00f434.png)

![image](https://user-images.githubusercontent.com/8441971/221604885-b85e319b-ef30-4d9c-b850-1f48260391a7.png)

**Comment by NicoMaio** [comment]
Hi @aadlung,
in the stable version, it should be fixed. Please update and let me know.

**Comment by aadlung** [comment]
Looks good for me, at least I did some random samples and even flows with FIN in it did not get the purge message any more.
In general, how long do alert flows stay in the alert flow list `/lua/flows_stats.lua?alert_type_severity=error`? Before this change, they seem to be removed after a FIN or RST, now they stay in alert list until the cache time expires?

**Comment by NicoMaio** [comment]
After the fix, the TCP flows, after a FIN or an RST or a bad Three-Way Handshake, stay in memory until the "Flow Idle Timeout" expires.

**Comment by aadlung** [comment]
Great, thanks a lot
