### ISSUE TITLE
Extract pcap - Interface Missing

### ISSUE THREAD

**Issue by colinvv2** [ntop/ntopng#726]
When I try to 'Extract pcap'... error shows 'Interface Missing'.

![image](https://cloud.githubusercontent.com/assets/21261036/18185615/8c0562a6-706c-11e6-89f6-09e03a66e065.png)

---

ntopng.conf:
-n=3
-w=3000
-W=0
-g=-1
-S=all
-F=mysql;localhost;ntopng;flows;ntopng;*****
-d=/storage/ntopng
-G=/var/run/ntopng.pid
-i=tcp://127.0.0.1:5556

---

nprobe-file.conf:
-n=none
-i=none
-t=60
-d=60
-a=0
-e=1
-B=10
-w=128000
-z=0
-S=1:1
-E=0:0
-g=/var/run/nprobe-file.pid
-3=6343
--zmq=tcp://127.0.0.1:5556
--vlanid-as-iface-idx=none
-T=%IN_BYTES %IN_PKTS %PROTOCOL %SRC_TOS %TCP_FLAGS %L4_SRC_PORT %IPV4_SRC_ADDR %INPUT_SNMP %L4_DST_PORT %IPV4_DST_ADDR %OUTPUT_SNMP %LAST_SWITCHED %FIRST_SWITCHED %L7_PROTO %BITTORRENT_HASH
-V=10
--mysql=localhost:ntopng::ntopng:*****
--dump-stats=/var/log/nprobe/file-0_flows_stats.txt

---

**Comment by simonemainardi** [comment]
you can't extract pcaps out of flows traffic. I guess I should disable that button on the interface when the interface is ZMQ. That feature is meant for user that have ntopng and n2disk on the same box so they can browse recorded data inside ntopng and obtain the pcaps of their searches.
