### ISSUE TITLE
ntopng wont compile on Fedora 36

### ISSUE THREAD

**Issue by pgaltieri** [ntop/ntopng#7262]
**Environment**:
* OS name: [e.g. Ubuntu] Fedora
* OS version: [e.g. 18.04] 36
* Architecture: [e.g. amd64] x86_64
* ntopng version/revision: [e.g. 5.1.211223] latest

**What happened**:
when trying to compile ntopng from source I get:
src/SNMP.cpp: In member function ‘void SNMP::send_snmp_request(char*, u_int, char*, char*, char*, char*, char*, char*, char*, snmp_pdu_primitive, char**, char*, char**, bool)’:
src/SNMP.cpp:477:77: error: ‘usmDESPrivProtocol’ was not declared in this scope; did you mean ‘usmAESPrivProtocol’?
  477 |               snmpSession->session.securityPrivProto = snmp_duplicate_objid(usmDESPrivProtocol, USM_PRIV_PROTO_DES_LEN);
      |                                                                             ^~~~~~~~~~~~~~~~~~
      |                                                                             usmAESPrivProtocol
make: *** [Makefile:130: src/SNMP.o] Error 1

Note that your README.compilation only references Fedora 30, 31 and 32.  

**How did you reproduce it?**
Compile ntopng on Fedora 36 
![ntopng_compile](https://user-images.githubusercontent.com/6402176/220968257-db38978a-03b5-4f39-bd35-d0903a438504.png)

from snm_api.h of the net-snmp 5.9.3

#ifndef NETSNMP_DISABLE_DES
#define SNMP_DEFAULT_PRIV_PROTO     usmDESPrivProtocol
#else
#define SNMP_DEFAULT_PRIV_PROTO     usmAESPrivProtocol
#endif

**Debug Information**:

**Comment by lucaderi** [comment]
Please try the fix and reopen this ticket if not working.

**Comment by pgaltieri** [comment]
The fix works.  Thank you for your quick response.
