### ISSUE TITLE
Fix service map icons

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7269]
![image](https://user-images.githubusercontent.com/4493366/221344900-78b95d7b-be5b-4a03-9170-51a426a6474a.jpeg)

**Comment by MatteoBiscosi** [comment]
The issue should now be fixed
![image](https://user-images.githubusercontent.com/49585191/221827109-d3aacf88-384f-4e01-9e14-61c69d4fb73a.png)

**Comment by martinscheu** [comment]
@MatteoBiscosi 
it is working correctly now. Thank you
