### ISSUE TITLE
Wrong Granularity

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7270]
Fix this problem in both stable and dev

Feb 23 18:45:00 XXXX ntopng[5648]: [export_influxdb_stats.lua:20] [influxdb.lua:1355] ERROR: Could not contact the InfluxDB database: Is InfluxDB running?
Feb 23 18:45:00 XXXX ntopng[5648]: 23/Feb/2023 18:45:00 [export_influxdb_stats.lua:20] [influxdb.lua:1355] ERROR: Could not contact the InfluxDB database: Is InfluxDB running?
Feb 23 18:46:00 XXXX ntopng[5648]: 23/Feb/2023 18:46:00 [LuaEngine.cpp:330] [ERROR] Unknown granularity
Feb 23 18:46:00 XXXX ntopng[5648]:  table
Feb 23 18:46:00 XXXX ntopng[5648]: granularity_id number 1
Feb 23 18:46:00 XXXX ntopng[5648]: granularity_seconds number 60
Feb 23 18:46:00 XXXX ntopng[5648]: i18n_title string show_alerts.minute
Feb 23 18:46:00 XXXX ntopng[5648]: i18n_description string alerts_thresholds_config.every_minute
Feb 23 18:46:00 XXXX ntopng[5648]: 23/Feb/2023 18:46:00 [LuaEngine.cpp:330] stack traceback:
Feb 23 18:46:00 XXXX ntopng[5648]:         /usr/share/ntopng/scripts/lua/modules/alert.lua:161: in function 'alert.set_granularity'
Feb 23 18:46:00 XXXX ntopng[5648]:         ...opng/scripts/callbacks/minute/system/influxdb_checks.lua:29: in main chunk
Feb 23 18:47:01 XXXX ntopng[5648]: 23/Feb/2023 18:47:01 [LuaEngine.cpp:330] [ERROR] Unknown granularity
Feb 23 18:47:01 XXXX ntopng[5648]:  table
Feb 23 18:47:01 XXXX ntopng[5648]: granularity_seconds number 60
Feb 23 18:47:01 XXXX ntopng[5648]: i18n_title string show_alerts.minute
Feb 23 18:47:01 XXXX ntopng[5648]: granularity_id number 1
Feb 23 18:47:01 XXXX ntopng[5648]: i18n_description string alerts_thresholds_config.every_minute
Feb 23 18:47:01 XXXX ntopng[5648]: 23/Feb/2023 18:47:01 [LuaEngine.cpp:330] stack traceback:
Feb 23 18:47:01 XXXX ntopng[5648]:         /usr/share/ntopng/scripts/lua/modules/alert.lua:161: in function 'alert.set_granularity'
Feb 23 18:47:01 XXXX ntopng[5648]:         ...opng/scripts/callbacks/minute/system/influxdb_checks.lua:29: in main chunk
Feb 23 18:48:01 XXXX ntopng[5648]: 23/Feb/2023 18:48:01 [LuaEngine.cpp:330] [ERROR] Unknown granularity
Feb 23 18:48:01 XXXX ntopng[5648]:  table
Feb 23 18:48:01 XXXX ntopng[5648]: i18n_title string show_alerts.minute
Feb 23 18:48:01 XXXX ntopng[5648]: granularity_id number 1
Feb 23 18:48:01 XXXX ntopng[5648]: granularity_seconds number 60
Feb 23 18:48:01 XXXX ntopng[5648]: i18n_description string alerts_thresholds_config.every_minute
Feb 23 18:48:01 XXXX ntopng[5648]: 23/Feb/2023 18:48:01 [LuaEngine.cpp:330] stack traceback:
Feb 23 18:48:01 XXXX ntopng[5648]:         /usr/share/ntopng/scripts/lua/modules/alert.lua:161: in function 'alert.set_granularity'
Feb 23 18:48:01 XXXX ntopng[5648]:         ...opng/scripts/callbacks/minute/system/influxdb_checks.lua:29: in main chunk

**Comment by MatteoBiscosi** [comment]
The issue seems fixed, please reopen if needed
