### ISSUE TITLE
Service map not showing all flows

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#7273]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]
ntopng Enterprise L v.5.7.230225 (Ubuntu 20.04.5 LTS)

**What happened**:
It seems that not all flows are represented in the service map.
E.g. IEC-104
There where 136 live flows, so at least 60 different hosts, but service map is not showing them
<img width="779" alt="Screenshot 2023-02-26 at 23 37 38" src="https://user-images.githubusercontent.com/38549755/221441916-fa83c7b8-afad-4ef5-82aa-052e3d34a9b8.png">

<img width="1630" alt="Screenshot 2023-02-26 at 23 41 54" src="https://user-images.githubusercontent.com/38549755/221441924-7624011b-8f6e-4c80-8e72-5f1702c0fccc.png">

**How did you reproduce it?**

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu is it possible to have a pcap with some of those flows? in order to reproduce the issue in my lab in case drop an email at 'biscosi at ntop.org'

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu please drop a pcap at biscosi at ntop.org and I'll try to reproduce the issue, in our lab, everything seems working correctly.
Please reopen the ticket if needed
