### ISSUE TITLE
Service map host-to-host marking not accessible

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#7274]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]
ntopng Enterprise L v.5.7.230225 (Ubuntu 20.04.5 LTS)

**What happened**:
The ability to mark host to host communication with "Allowed, Unknown or Deny" is not accessible.
(as shown here: https://www.ntop.org/guides/ntopng/_images/advanced_features_service_map_table.png)
<img width="1626" alt="Screenshot 2023-02-26 at 23 49 11" src="https://user-images.githubusercontent.com/38549755/221442196-24ef966a-0889-4cfd-9bba-a5657a4a3545.png">

also, I cant change the view to "Standard View"
![image](https://user-images.githubusercontent.com/38549755/221442223-81956334-1550-47b1-a571-70e8d74129f4.png)

**How did you reproduce it?**

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu please wait a couple of hours and update, the issue should be solved in the new version. It's possible to switch to the standard view and change the status. 
Note that to change the status you have to switch to the standard view, the centrality view is just a summary.
I'm going to update the documentation.

**Comment by martinscheu** [comment]
HI @MatteoBiscosi 
I've just updated to the latest version and when I try to load the Service Table is only loading:
<img width="921" alt="Screenshot 2023-02-28 at 21 37 32" src="https://user-images.githubusercontent.com/38549755/221974622-2295e88c-57ca-4846-8a34-f0255e496ea2.png">

**Comment by MatteoBiscosi** [comment]
Verified as fixed, please reopen if needed
