### ISSUE TITLE
Exclude domain in Enterprise M version not working properly

### ISSUE THREAD

**Issue by takenek** [ntop/ntopng#7276]
Alerts>Explorer
![image](https://user-images.githubusercontent.com/4953735/221521029-952772d3-55bf-4825-b94a-ca6d3836bf7d.png)

But i got in exlclude this domain:
![image](https://user-images.githubusercontent.com/4953735/221521207-89b9847a-278e-4733-b6ba-22309f329bcc.png)

i try many times add domain to exclude but not working:
![image](https://user-images.githubusercontent.com/4953735/221521639-b7455ded-b9f4-4930-a40b-726a9bb4e1be.png)

**Comment by MatteoBiscosi** [comment]
Hi @takenek is it possible to have a small pcap with some of those flows? in order to reproduce the issue in my workspace cause i tried but everything seems working fine on my side. Please drop an email at 'biscosi at ntop.org'

**Comment by takenek** [comment]
@MatteoBiscosi Check Your mailbox i just send You.

**Comment by MatteoBiscosi** [comment]
Hi @takenek thanks, i was able to reproduce the issue, i'll investigate further and update you

**Comment by takenek** [comment]
@MatteoBiscosi  Good too hear i send You little information on e-mail :-)

**Comment by MatteoBiscosi** [comment]
Hi @takenek in the latest dev version (5.7) the issue should be fixed
