### ISSUE TITLE
Ntopng compilation src/Prefs.o' failed on debian 8.5

### ISSUE THREAD

**Issue by edo33** [ntop/ntopng#728]
Hello. 
Ive got problem with compiling ntopng 2.4.0 on my debian 8.5 system. I have tryed git pull && ./configure && make in nDPI dir but it didnt work. 
Operating System: Debian GNU/Linux 8 (jessie)
Kernel: Linux 3.16.0-4-686-pae
Architecture: x86
src/Prefs.cpp: In function ‘void nDPIusage()’:
src/Prefs.cpp:150:81: error: too few arguments to function ‘ndpi_detection_module_struct\* ndpi_init_detection_module(u_int32_t, void\* (_)(size_t), void (_)(void_), ndpi_debug_function_ptr)’
   struct ndpi_detection_module_struct *ndpi_struct = ndpi_init_detection_module();
                                                                                 ^
In file included from /usr/local/include/libndpi-1.7.1/libndpi/ndpi_main.h:33:0,
                 from /ntopng/include/ntop_includes.h:99,
                 from src/Prefs.cpp:22:
/usr/local/include/libndpi-1.7.1/libndpi/ndpi_api.h:129:40: note: declared here
   struct ndpi_detection_module_struct *ndpi_init_detection_module(u_int32_t ticks_per_second,
                                        ^
Makefile:138: recipe for target 'src/Prefs.o' failed
make: *_\* [src/Prefs.o] Error 1

Can you please help? 
Best regards

Matthew

**Comment by simonemainardi** [comment]
you need to use nDPI stable branch 1.8 (https://github.com/ntop/nDPI/tree/1.8-stable)

make sure to uninstall any previous nDPI (you have 1.7.x under /usr/local) and then checkout branch 1.8 in an ntopng sibling directory

**Comment by edo33** [comment]
Thank you very much. Now its ok but another error.
g++ -g -Wall -I/ntopng -I/ntopng/include -I/usr/local/include -D_FILE_OFFSET_BITS=64 -I/usr/include/hiredis  -I/usr/include/hiredis -I/ntopng/third-party/mongoose -I/ntopng/third-party/json-c  -I/usr/local/include/libndpi-1.7.1/libndpi  -I/ntopng/third-party/LuaJIT-2.0.3/src  -I/ntopng/third-party/zeromq-4.1.3/include -I/usr/include/mysql  -I/ntopng -I/ntopng/include -I/usr/local/include -I/ntopng/third-party/http-client-c/src/  -I/usr/include/openssl  -DDATA_DIR='"/usr/local/share"' -I/ntopng/third-party/libgeohash -I/ntopng/third-party/patricia   -c src/GenericHashEntry.cpp -o src/GenericHashEntry.o
In file included from src/GenericHashEntry.cpp:22:0:
/ntopng/include/ntop_includes.h:99:23: fatal error: ndpi_main.h: No such file or directory
 #include "ndpi_main.h"
                       ^
compilation terminated.
Makefile:138: recipe for target 'src/GenericHashEntry.o' failed
make: **\* [src/GenericHashEntry.o] Error 1

**Comment by simonemainardi** [comment]
you are still using `libndpi-1.7.1``

re-run `./autogen.sh && ./configure`  before `make`

**Comment by edo33** [comment]
Thank you very much. . After removing libndpi-1.7.1 from /usr/local/include/  there was still some shared objects in  /usr/local/lib - libndpi-bin.so. Problem was gone when I manualy remove that file. Many thanks for help.

**Comment by simonemainardi** [comment]
thank you
