### ISSUE TITLE
ntopng ignores max-num-flows setting

### ISSUE THREAD

**Issue by notyourcommy** [ntop/ntopng#7280]
* OS name: CentOS Stream 
* OS version: 8
* Architecture: amd64
* ntopng version/revision:     5.7.230228

In ntopng.conf we have -X 700000
Currently Ntopng informs me that "Too many flows for ntopng leading to packet drops and high CPU load. Please tune -X or click the button below to double the current number. After that restart ntopng " while it only has 400k of active flows.
Also button "Double max flow" doesn't work.

**Comment by MatteoBiscosi** [comment]
Hi @notyourcommy the issue should be fixed, the threshold before that alert spawns is now at 80% (if you have more then 80% of the flows you put with the -X option then the alert is going to be triggered).
Also fixed the button not working.
A new version with the fix should be available soon.
Please reopen if needed
