### ISSUE TITLE
Manage Timeseries: only two different charts shown, third chart same as second

### ISSUE THREAD

**Issue by oliwirth** [ntop/ntopng#7283]
Hi guys,
I found the following: 
In the chat, if you choose more than two Interfaces, via Manage `Timeseries` to see in one `Chart per Metric`, it shows 3 Charts but only the info of two. See pic

![grafik](https://user-images.githubusercontent.com/47536446/222218747-e99b230e-ae93-463b-b792-4a15b2fbdce8.png)

Best regards 
OliverW

ntop Version:  5.6.230301 and 5.7.230301
System: Debian bullseye

**Comment by uccidibuti** [comment]
@oliwirth This bug should be fixed. Please update in an hour and let me know..
