### ISSUE TITLE
Warning Script

### ISSUE THREAD

**Issue by tncyysl** [ntop/ntopng#7286]
after fresh install i cant change password...

02/Mar/2023 21:03:10 [LuaEngine.cpp:1254] WARNING: Script failure [/usr/local/Cellar/ntopng/5.2.1_1/share/ntopng/scripts/lua/change_password.lua][.../ntopng/scripts/lua/modules/notifications/recipients.lua:649: attempt to index a nil value (local 'alert_store_db_recipient')]

Mac M2 ARM

ntopng --version
Version:	5.2.230115 [Community build]
GIT rev:	:5.2.230115

**Comment by MatteoBiscosi** [comment]
Hi @tncyysl currently we support only the latest stable and dev version (5.6 and 5.7) please update or we cannot help you

**Comment by tncyysl** [comment]
how can install latest version because i dont see packages URL adress ?

i m looking for arm packages...

**Comment by MatteoBiscosi** [comment]
Hi @tncyysl you can find the binary available here https://packages.ntop.org/

**Comment by tncyysl** [comment]
thanks a lot.

it's worked properly x64 package on arm...

**Comment by MatteoBiscosi** [comment]
Glad to know @tncyysl !
