### ISSUE TITLE
Unable to show the comment in Exclusion List

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7291]
<img width="1119" alt="Screenshot 2023-03-06 at 15 19 54" src="https://user-images.githubusercontent.com/4493366/223136242-4610d5fb-62ac-4bae-a905-11ab6c2fc382.png">

**Comment by NicoMaio** [comment]
Fixed in pro repo by cf207c55d975230d90f9bd051b856ac928c96381

**Comment by lucaderi** [comment]
Verified as fixed
