### ISSUE TITLE
modification of max char length in Client Server columnt - IPv6 address length cut and replaced with … - for better search possibility

### ISSUE THREAD

**Issue by melicherm** [ntop/ntopng#7294]
We suggest the possibility of changing the width of the Client or Server column width to accommodate the length of IPv6 addresses. So they don't get cut and are searchable by browser search function.

![image](https://user-images.githubusercontent.com/25390140/223690566-0debeb17-b3ff-41dc-a75a-c70fae9c868c.png)

**Comment by melicherm** [comment]
The last characters of IPv6 addresses are replaced with the character: …  , which makes them not searchable in the browser.

the character …  is -> horizontal ellipsis (U+2026)

**Comment by MatteoBiscosi** [comment]
Hi @melicherm which page are you talking about? The live flows one?

**Comment by melicherm** [comment]
@MatteoBiscosi - exactly, live flows.

**Comment by lucaderi** [comment]
Verified as fixed
