### ISSUE TITLE
Missing Link for Jumping to SNMP Pages

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7297]
As shown below, there are only links for filtering into the alerts page, but no icons (or similar as for instance in flows) for jumping into the SNMP host/interface. This ticket is to request to add such icons

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/4493366/224006070-0c4c424f-08fa-463e-8fa8-4e961547dc1c.png">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
