### ISSUE TITLE
Full-duplex characteristic of WAN traffic is not reflected in the little 'peity' graph at the bottom

### ISSUE THREAD

**Issue by JuergenWeber** [ntop/ntopng#73]
To my understanding WAN traffic is bidirectional (upstream- and downstream traffic at the same time). This doesn't reflect in the little 'peity' graph at the bottom of each NTOPNG page. In the little graph upstream- and downstream traffic doesn't occur simultaneously. It's either up- or downstream. Here's an example how it could look like: http://www.atotech.com/data/peity.html
![image](https://cloud.githubusercontent.com/assets/13195740/8597661/0c60f390-2657-11e5-8750-1c01e1006f4e.png)

**Comment by lucaderi** [comment]
I have made a fix towards what you need. Please play a bit with the HTML and add the remaining pieces such as Kbps etc so I can then incorporate them in ntopng. Please send me a merge request when you're done.

**Comment by lucaderi** [comment]
Fixed in git
