### ISSUE TITLE
Latest git segfault

### ISSUE THREAD

**Issue by DigiAngel** [ntop/ntopng#730]
Bummer:

```
Sep  6 08:02:51 gateway kernel: [481758.602339] ntopng[31631]: segfault at 141d9e1d0 ip 00007f2b4100037e sp 00007fffa2c0b210 error 4 in libluajit-5.1.so.2.0.3[7f2b40ff7000+6d000]
```

and

```
v.2.5.160826 [Community Edition]
GIT rev:   dev:7ee8f8e560f88828a4dfdba44d8cd0c468d66bb0:20160826
```

I can debug, just lemme know how.

**Comment by simonemainardi** [comment]
you are using aug 26 version. Make sure to either use the latest branch of 2.4 stable if you are building from source.

**Comment by DigiAngel** [comment]
Thank you...however I'm more than happy to continue with the 2.5 branch to report bugs and use new features :)  This isn't really in a business environment, so I can continue to test.

**Comment by simonemainardi** [comment]
Thank you. I'm closing this as it is related to an old version. Please, feel free to re-open in case you experience it in the latest build.
