### ISSUE TITLE
Click Has Secondary Action

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7300]
Clicking on a host label should jump to the host page and not *also* open the table

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/4493366/224046467-8c856914-22ba-41fd-9877-93a0d6eb0893.png">

**Comment by lucaderi** [comment]
You have removed the opening on a new page but the hosts are not formatted as they should be. There are formatting functions in ntopng that you need to use without reinventing the wheel. For instance, I expect to see flags or blacklist icons that I do not see

**Comment by NicoMaio** [comment]
Fixed by fe2351f0e1d2c954bb66dfa6c6b197c16fdeb28d

**Comment by lucaderi** [comment]
Verified as fixed
