### ISSUE TITLE
Missing VLAN support in Flow Analysis

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7301]
Hosts do not support VLANs and thus
- their name does not have @VLAN
- the URL is invalid as the VLAN is missing
- 
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/4493366/224046816-5b9166bb-71c0-4490-b87d-190fe134a6fd.png">

**Comment by NicoMaio** [comment]
There are also issues with the VLAN filter dropdown menu.

**Comment by MatteoBiscosi** [comment]
Issue verified and fixed
