### ISSUE TITLE
Asset Map Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7303]
Note that asset table is also broken

<img width="1570" alt="Screenshot 2023-03-10 at 10 02 17" src="https://user-images.githubusercontent.com/4493366/224272192-8280a8fe-80ba-40c9-b8e8-3bc307001cce.png">

**Comment by lucaderi** [comment]
Clicking on a host shows an empty page

**Comment by MatteoBiscosi** [comment]
The issue should be fixed with this morning update, tested on hs.
