### ISSUE TITLE
VLAN Filtering Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7305]
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/4493366/224279264-d0fcae41-6898-4c93-9f57-dca6c32847eb.png">

**Comment by cardigliano** [comment]
Fixed in 7045004ecd1984d50046ce18967d7b7af3d2dcf7

**Comment by MatteoBiscosi** [comment]
Verified and fixed
