### ISSUE TITLE
Feature Request: interface with sample rate

### ISSUE THREAD

**Issue by blues-git** [ntop/ntopng#731]
I have few devices that I'm monitoring using ntopng.
Traffic is directed using port mirror with sample-rate 1:100. That causes bandwidth problems (100x lower rates).

I would be great to introduce option to specify interface with sample-rate, i.e.: -i eth0@100

**Comment by emanuele-f** [comment]
Implemented as a UI interface setting. Thank you for the suggestion.

**Comment by blues-git** [comment]
Great.
Version 2.5.161028-1751 from debian packages works fine.
Thanks.
