### ISSUE TITLE
Invalid Chart Scrolling

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7310]
Charts implemented in ntopng have animations that make them unsuitable for network monitoring. Scrolling must be smooth and with no animation at all, scrolling left as soon as one point is added.

See [this example](https://app.netdata.cloud/spaces/netdata-demo/rooms/dns-query/overview#d8a4e0c5-7c79-4145-900e-83a9f06fcb6a-overview-chartName=menu_system_submenu_disk&after=-900&before=0&utc=Europe%2FRome&offset=%2B1&timezoneName=Amsterdam%2C%20Berlin%2C%20Bern%2C%20Rome%2C%20Stockholm%2C%20Vienna&modal=&modalTab=&modalParams=&metrics_correlation=false&0543a50f-d94f-4488-a634-b390adbe8d0e-overview-chartName=menu_ad_submenu_database&7ab50836-f05c-4983-a9ea-b5b4ee520f71-overview-chartName=menu_web_log&23dc37c4-2bb4-48e7-b6d4-49f03ed29421-overview-chartName=menu_netdata) and implement it this way also in ntopng

**Comment by lucaderi** [comment]
Animations are still present, and it is not updating timely as it should. Check http://xxxx:3000/lua/if_stats.lua?ifid=2&page=historical&epoch_begin=1678886722&epoch_end=1678888522&timeseries_groups_mode=1_chart_x_metric&timeseries_groups=interface%3B2%3Biface%3Atraffic_rxtx%3Bbytes_rcvd%3Dtrue%3Afalse%3Afalse%3Afalse%7Cbytes_sent%3Dtrue%3Afalse%3Afalse%3Afalse

**Comment by MatteoBiscosi** [comment]
Issue fixed by changing the charts library
