### ISSUE TITLE
Zero vs Unknown in Charts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7312]
A value 0 means that the measurement happened and it reported 0 as value. An Unknown value means that no measurement happened.

The image below is wrong and confusing as unknown values are reported as zero and fix is a major flaw that needs to be fixed.

![image 6](https://user-images.githubusercontent.com/4493366/224635772-dde73ae8-5dc9-4600-b478-6151f6cc6c28.png)

**Comment by uccidibuti** [comment]
This should be a Rest problem that return 0 instead of null.

**Comment by lucaderi** [comment]
Still bugged. Just added a timeseries and seen point in the past
![Screenshot 2023-03-15 at 14 56 50](https://user-images.githubusercontent.com/4493366/225330868-fdcc43b7-c121-44f3-a90d-5417bed4bc05.png)

**Comment by lucaderi** [comment]
The bug seems to be in the backend
![Screenshot 2023-03-15 at 15 32 49](https://user-images.githubusercontent.com/4493366/225341896-97f1336d-c668-485b-bf3f-b046f282b9c4.png)

**Comment by MatteoBiscosi** [comment]
Issue fixed
