### ISSUE TITLE
Wrong server detection: unexpected NTP server found

### ISSUE THREAD

**Issue by HeavenBay** [ntop/ntopng#7313]
Hi Team,

ntopng Enterprise M v.5.6.230310 (Ubuntu 22.04.2 LTS)

We have domain controllers which are also NTP servers. I enabled feature "Unexpected NTP server found", set these servers as NTP servers but nTopng started thinking that ALL clients of these servers are also servers.

<html>
<body>

10:44:46 | 100 | UDP:NTP | Unexpected NTP server found | DOMAIN_CONTROLLER:123    10.2.22.116:123 | Unexpected NTP server found: 10.2.22.116  
-- | -- | -- | -- | -- | -- | 
10:43:20 | 100 | UDP:NTP | Unexpected NTP server found | DOMAIN_CONTROLLER:123    10.0.246.168:123 | Unexpected NTP server found: 10.0.246.168  
10:44:17 | 100 | UDP:NTP | Unexpected NTP server found | DOMAIN_CONTROLLER:123    10.0.246.112:123 | Unexpected NTP server found: 10.0.246.112  
10:44:17 | 100 | UDP:NTP | Unexpected NTP server found | DOMAIN_CONTROLLER:123    10.0.46.78:123 | Unexpected NTP server found: 10.0.46.78  
10:43:54 | 100 | UDP:NTP | Unexpected NTP server found | DOMAIN_CONTROLLER:123    10.0.25.147:123 | Unexpected NTP server found: 10.0.25.147  
10:43:44 | 100 | UDP:NTP | Unexpected NTP server found | DOMAIN_CONTROLLER:123    10.0.25.26:123 | Unexpected NTP server found: 10.0.25.26  
10:44:04 | 100 | UDP:NTP | Unexpected NTP server found | DOMAIN_CONTROLLER:123    10.0.15.37:123 | Unexpected NTP server found: 10.0.15.37  
10:43:30 | 100 | UDP:NTP | Unexpected NTP server found | DOMAIN_CONTROLLER:123    10.0.24.155:123 | Unexpected NTP server found: 10.0.24.155  
10:44:36 | 100 | UDP:NTP | Unexpected NTP server found | DOMAIN_CONTROLLER:123    10.0.25.21:123 | Unexpected NTP server found: 10.0.25.21

**Comment by MatteoBiscosi** [comment]
Hi @HeavenBay what do you mean, sorry but i'm not understanding, do you perhaps have alerts triggered even if the servers are not ntp server?
Could you please send me a screenshot? If you jump to the host page of one of those pages, what have you reported there? are they reported as NTP servers? (e.g. see screenshot below)
![image](https://user-images.githubusercontent.com/49585191/224651662-a7a17350-d37b-4d4e-b5a8-31b5acdcc606.png)

**Comment by HeavenBay** [comment]
Hi @MatteoBiscosi,
Thank you for a quick reply!

I added IPs of my DCs to "Unexpected NTP server" setting in Behavioural Checks and enabled this feature.
![ntp](https://user-images.githubusercontent.com/42742929/224687345-4c64fa35-ebf2-4e32-9144-90b44d978b33.png)

I started receiving alarms about wrong NTP servers. In my network all domain PCs query time by NTP proto only from PDC. However, I saw that nTopng decided that my PDC (domain controller) could be a client of domain PCs :) It mixed up the client and server. I guess it sees 123/UDP on both sides and it no longer cares in which direction the request was, and in which direction the response. You also can see that 192.168.0.31 is also **server** for some "client" in the Internet.
![flow](https://user-images.githubusercontent.com/42742929/224687272-5e2fdeac-7634-42e9-8d55-fc186c9c9aea.png)

So it's impossible to add NTP server cos every client can be a server.

**Comment by lucaderi** [comment]
Are you capturing packets or flows?
Please share your configuration

**Comment by HeavenBay** [comment]
Two VMs: nTopng and nProbe.
Network Device -> netFlow IPFIX -> nProbe -> nTopng

**nTopng: /etc/ntopng/ntopng.conf**
```
-G=/var/run/ntopng.pid
-i=tcp://NPROBE-NODE:5556
-m=10.x.x.x/16,10.x.x.x/16,10.x.x.x/16
-F="clickhouse;127.0.0.1;DATABASE;USERNAME;PASSWORD"
```

**nProbe: /etc/nprobe/nprobe-ntopng.conf**
```
-i=ens192
-n=none
-3=9996
--ntopng=zmq://NPROBE-NODE:5556
-T="@NTOPNG@"
```

**Comment by lucaderi** [comment]
This is the problem: as ntopng receives flows he has no clue who is the client and who is the server and thus the problem. This when both speak on port ntp and connections are longstanding.
@MatteoBiscosi I believe we need to disable the NTP check over flows

**Comment by HeavenBay** [comment]
Eh... We are unable to use TAPs. It's too sad that impossible to read the stream vector. Because it's a nice feature with NTP.
Thank you @MatteoBiscosi, @lucaderi.

**Comment by MatteoBiscosi** [comment]
Hi @HeavenBay like luca told to you, the problem is that the direction is not right.
One thing that you could try is by adding a check exclusion, excluding all the NTP Unexpected Server alert for your ntp server.
However consider the fact that the alert is not going to be triggered even in the case the NTP server is for real a client trying to contact an other host as server using NTP.
![image](https://user-images.githubusercontent.com/49585191/224736770-090f71c5-4761-4d5c-b645-bde981505365.png)
