### ISSUE TITLE
Saving peak throughput to historical flows

### ISSUE THREAD

**Issue by midoelhawy** [ntop/ntopng#7315]
**What would you like to add or change?**:
it's possible to save peak throughput for the single flows Like that :
![Screenshot from 2023-03-13 11-26-41](https://user-images.githubusercontent.com/27738027/224727977-b2edb322-9a82-476e-99e1-bd7ac95b04d6.png)

For example :

```
peakThroughput = [0,2,6,9,8,80,120 ecc..]
```

**Comment by lucaderi** [comment]
We can compute the top throughput but computing what you propose will cost a lost in terms of performance and hard to implement with flows

**Comment by NicoMaio** [comment]
The max throughput value is already present on the live flow details page. It's the Peak value.

**Comment by midoelhawy** [comment]
@NicoMaio how can I fetch it directly from db for historical flows?
