### ISSUE TITLE
Map missing field names

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7316]
When starting ntopng in kafka mode (see https://www.ntop.org/nprobe/howto-use-kafka-instead-of-zmq-for-reliable-flow-collection-and-ipc/) some fields are not mapped with human-friendly labels

<img width="874" alt="Screenshot 2023-03-13 at 15 22 29" src="https://user-images.githubusercontent.com/4493366/224729824-73f136c3-6355-4d97-8261-c786637d0368.png">

**Comment by lucaderi** [comment]
You can reproduce as follows
1.``` nprobe --json-labels --kafka "kafka:9093;flow" -i ethX -T "@NTOPNG@"```
2. ```ntopng -i kafka://192.168.2.38```

Make sure you have defined
```
# grep kafka /etc/hosts
192.168.2.38	kafka
````

**Comment by MatteoBiscosi** [comment]
Implemented as requested
