### ISSUE TITLE
Host Service Labelling is Biased

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7326]
Sometimes ntopng labels a host as "XXX server" but the host has just received the XXX traffic without sending a reply back or has sent a negative reply back. This has to be fixed

![Screenshot 2023-03-15 at 18 05 21](https://user-images.githubusercontent.com/4493366/225386271-05d8d3e8-64cc-49c9-8df3-ba8d883b6108.png)

**Comment by NicoMaio** [comment]
For flows using UDP, the detected l7 protocol processing is made when the server has not responded yet.
