### ISSUE TITLE
Renaming of Observation Points in ntopng not working

### ISSUE THREAD

**Issue by goltob** [ntop/ntopng#7329]
**Environment**:
* OS name:  Ubuntu
* OS version:  20.04
* ntopng version/revision: 5.6.230315

**What happened**:
We fill up ntopng with observation points information by using the -E option on the probes, which will send the flows to ntopng.

1. Afterwards we can see the Observation points in the Observation Points menu, but we are not able to rename them by clicking on the "settings" button.

2. Further more, we are not able to see the observation points drop down field on the right site of the interface field.
I mean we cannot see the dropdown fiels as shown in the following image.

![image](https://user-images.githubusercontent.com/62657418/225851502-53df30d5-d564-42c5-b91c-bba4e32bcd23.png)

**How did you reproduce it?**

**Debug Information**:

**Comment by NicoMaio** [comment]
Hi @goltob,

1. I'm trying to reproduce your problem on the stable version, but I am able to rename the observation points correctly. Could you please share a screenshot of the problem? 

2. We removed the observation point dropdown menu on the flow details page because every flow can have only one observation point.

**Comment by MatteoBiscosi** [comment]
Hi @goltob, to rename the observation point you have to jump to the observation points page, then click on the cog, you should be able to change the alias.
![image](https://user-images.githubusercontent.com/49585191/226930982-a7e6380f-cf19-434b-8c87-b154f1e17c18.png)
![image](https://user-images.githubusercontent.com/49585191/226931056-018727e5-93f0-4f4d-bcbf-1115ae0b0ceb.png)

To enable instead the time series (chart icon) you have to enable the observation points time series from the preference page:
![image](https://user-images.githubusercontent.com/49585191/226931525-f689e4c0-7821-41bb-acce-936c923b3d93.png)

Please reopen the issue if needed

**Comment by goltob** [comment]
@MatteoBiscosi 

Hello, we have still two questions:

1. The host alerts, flow alerts, hosts, devices, ecc. (red circle) are visualized for the whole interface and NOT for the select observation point?

![image](https://user-images.githubusercontent.com/62657418/229046814-b0472bc5-c597-4a08-923a-d0f96b87228d.png)


2. In the meantime we have ntopng version v.5.6.230329, and we are not able to change the observation name. When we click on the save button there are no changes in the name.
![image](https://user-images.githubusercontent.com/62657418/229047702-849de711-2944-47d8-b227-6fee1036e183.png)



![observation02](https://user-images.githubusercontent.com/62657418/229047965-6b11fc84-bb3e-45e5-8633-9338730f1fdb.PNG)
