### ISSUE TITLE
Reopen:There was something strange about MySQL

### ISSUE THREAD

**Issue by lhxhanson** [ntop/ntopng#733]
![qq 20160909153007](https://cloud.githubusercontent.com/assets/5568373/18378927/6905e2da-76a2-11e6-8d18-9577dd3bc382.png)

Are these MySQL ERROR have any relevance to the **Data Retention**？
The version about ntopng is 2.4.160805 - Community Edition

**Comment by simonemainardi** [comment]
please, update to the latest stable (v2.4.160908) and then report back

**Comment by lhxhanson** [comment]
@simonemainardi 
OK, I will try the latest stable version. If this happened again, then open a new issue.

**Comment by lhxhanson** [comment]
I have update to the latest stable version, looks like the strange log is still have.
We have about 4k hosts, and 30 million flows a day. The mysql and ntopng data directory are all on a ssd.
![qq 20160911093042](https://cloud.githubusercontent.com/assets/5568373/18414589/71859930-7802-11e6-89fb-549b3c923c36.png)

**Comment by simonemainardi** [comment]
If we look at the timestamp of the errors, we see that they occur exactly at 0.00 and 8.00.

I guess there is some automatic procedure at 0.00 that could possibly teardown MySQL server and/or it connections (e.g., system updates?). 

Moreover, the next error occur at 8.00, that is, exactly 8 hours after midnight. The 8 hours is also the default timeout of mysql connections (see MySQL configuration options `wait_timeout`  and 
`interactive_timeout`). So very likely, the MySQL server closes the open connection after 8 hours and ntopng immediately tries to set the connection up again. This causes the temporary glitch.  However you shouldn't worry about that.

Anyway, to confirm this hypothesis, can you check if ntopng continues to store flows after these errors? 

PS: The latest dev version also shows you the rate (in flows/sec) at which ntopng exports flows to MySQL and is also tells you if there are any dropped flows during export.

PPS: As a side note, 30M flows per day is pretty much. MySQL will become soon unresponsive, unless you have a sharded/replicated deployment. Make sure to set a reasonable value for the retention days. You may want also to try with the latest MySQL 5.7 that has very good performances.

**Comment by lhxhanson** [comment]
Thanks for reply.
The running ntopng host is the gateway that connect to the Internet, so if there is no big issue, we won't do any change on this host.
Why I think it may caused by Data Retention is that, sort the tables by idx, the oldest record's FIRST_SWITCHED is always about 08:00, just same as the error time in log. And our timezone is UTC+8.

We have a test environment, it has 500+ hosts, and almost no traffic through the test ntopng host(haven't make the ntopng be the gateway, so only some broadcast traffic).
![image](https://cloud.githubusercontent.com/assets/5568373/18459295/f47f95b8-799a-11e6-8af6-8f880316976b.png)
I check the log, it also has the same messages.

**Comment by simonemainardi** [comment]
Since cleanup according to the data retention settings is performed once per day using the unix epoch, it should occurs exactly at UTC+8 on your system so your point is meaningful. 

However, I think I have found the issue. The cleanup performs a DELETE operation on the mysql DB and this kind of query it is not supposed to return any result. In the previous implementation we assumed a no-result return can alwasy be interpreted as an error. Actually, this is not always true as described in the manual: https://dev.mysql.com/doc/refman/5.7/en/null-mysql-store-result.html
I have made a fix for this.

New stable packages are being rebuild. Please wait a couple of hours, update again, and let us know. Thank you.
