### ISSUE TITLE
ntopng - Device/MAC Address Tracking - allow devices are recognized as "denied" status

### ISSUE THREAD

**Issue by goltob** [ntop/ntopng#7330]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04
* ntopng version/revision: 5.6.230315

**What happened**:
We have enabled the alert rule "Unexpected Device Connected/Disconnected" for activating the MAC Address Tracking. When I see the MAC addresses in the "Device Exclusion List" after the learning time,  all mac addresses are in "denied".

As I have read in the documentation (https://www.ntop.org/guides/ntopng/advanced_features/devices_exclusion.html) I understood, that the device found newly should be in  "allowed" .

![image](https://user-images.githubusercontent.com/62657418/225857634-35d20924-a9ef-4433-af32-75245f1fba73.png)

Maybe I have misunderstood something?

**How did you reproduce it?**

**Debug Information**:

**Comment by NicoMaio** [comment]
Hi @goltob,

Thanks for the tip. We updated the documentation. It should be available this evening or tomorrow morning.

**Comment by goltob** [comment]
Hi @NicoMaio , 
I have read the documentation, and now I understand, that every new detected MAC address will be set as DENIED, until it will be handled in the "Allowd Devices List". 
Is this correct?

**Comment by NicoMaio** [comment]
Yes, it is correct.

**Comment by goltob** [comment]
thanks

**Comment by NicoMaio** [comment]
Verified as fixed
