### ISSUE TITLE
ntopng SNMPv3 monitoring of Extreme Switch

### ISSUE THREAD

**Issue by goltob** [ntop/ntopng#7331]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04
* ntopng version/revision: 5.6.230315

**What happened**:
We want to insert Switch Extreme Modell X440G2-48t-10G4  OS: 22.6.1.4-patch1-1 to monitor with snmpv3.

1. We are not able to insert these models of extreme switch to snmpv3 monitoring, we always get an error when clicking the add button. (snmpwalk in version 3 from the ntopng server to these switchers is working) 
For the Extreme switches with OS: 31.6.2.1 we are able to add in snmpv3.

2. For the switch we were able to add to the snmpv3 monitoring, we get no VLAN information.

3. For the switch we were able to add to the snmpv3 monitoring, we are not able to see the "charts" icon like on the following image:

![image](https://user-images.githubusercontent.com/62657418/225866598-82b98da7-251d-456f-8d43-64c4f596b9b1.png)

**How did you reproduce it?**

**Debug Information**:

**Comment by dudumao520** [comment]
Hello, can you use the snmp v2c protocol to add it successfully? During my use here, I found that several devices can be added successfully, but they cannot be polled. Have you ever encountered this situation?

**Comment by goltob** [comment]
No, the hosts I was able to add they will be polled.

**Comment by MatteoBiscosi** [comment]
Hi @goltob regarding the chart icon, to make it appear, the SNMP chart option needs to be enabled
![image](https://user-images.githubusercontent.com/49585191/226320222-5069011e-ae1f-4870-a246-8988caaa1c1e.png)

If the insert fails, there should be some error or warning reported in the journalctl -e -u ntopng , please let me know

**Comment by MatteoBiscosi** [comment]
@dudumao520 what do you mean by never polled? is there some error displayed in the journalctl; if the device is not polled you should have a triangle like this one and if you hover the mouse on it you should have the problem reported there
![image](https://user-images.githubusercontent.com/49585191/226321142-5471d2dd-dd93-40c6-893b-41d287e005bf.png)

**Comment by MatteoBiscosi** [comment]
Hi @goltob when adding the snmp device which error do you get? Is there an error shown in the ntopng log (  journalctl -e -u ntopng  )?

**Comment by goltob** [comment]
Good morning,
We get this error: (I remember that the snmpwalk for version 3 is working)

![image](https://user-images.githubusercontent.com/62657418/229049862-3c7df1ce-7a1b-4f63-8088-8c9da8e72f13.png)

We will see NO error in the journalctl.

If we try with an IP which does not exist, we get an error in the journalctl. 

Is there maybe a config file on ntopng, on which we have wrong permissions, or can we reset the whole snmp configuration from scratch? Maybes there is a misconfiguration happened?
