### ISSUE TITLE
Historical Flows Sorting by Bytes Breaks the Layout

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7335]
<img width="1170" alt="Screenshot 2023-03-21 at 11 53 07" src="https://user-images.githubusercontent.com/4493366/226585464-bebaa5f3-53a1-46d1-927b-3b82eb581026.png">

**Comment by lucaderi** [comment]
This has to be fixed in both stable and dev. Note that similar problems such as "Top Clients" have also sorting problem that need to be fixed

**Comment by cardigliano** [comment]
Fixed in 70fce2d8b62b69e6ab42bba368f2abe1c88cbfcf  a5e8323cf6b2f3fafe14a10b5909f7a17230fc5b  6105458cfa2e8f73578a0a33d2a45c27f2487c67 186a25f5b34f35fbdd57fb465b142038434bd553

**Comment by MatteoBiscosi** [comment]
Issue verified and fixed
