### ISSUE TITLE
Invalid Apply Button (Instead of Edit)

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7336]
<img width="1196" alt="Screenshot 2023-03-21 at 12 00 17" src="https://user-images.githubusercontent.com/4493366/226587244-c3a5b03d-fdf1-4424-a0dc-62c7e5021e11.png">

**Comment by NicoMaio** [comment]
It seems ok on HS.
![image](https://user-images.githubusercontent.com/55502486/226653790-7ad4447c-ca4e-4ca8-9255-255e55474a67.png)
