### ISSUE TITLE
ClickHouse Data Retention not working

### ISSUE THREAD

**Issue by sfedu-admin** [ntop/ntopng#7337]
Hi!
Ubuntu 20.04.6 LTS
Ntopng 5.6.230321
ClickHouse server version 23.2.4 revision 54461
Settings →Runtime Preferences →Data Retention
1 day (two check box).

We have out of free space.

ntop :) SELECT DISTINCT database, table, toUInt32(partition) drop_part FROM system.parts WHERE active AND database='ntopng';

SELECT DISTINCT
database,
table,
toUInt32(partition) AS drop_part
FROM system.parts
WHERE active AND (database = 'ntopng')

Query id: a7eb744c-f4b7-451c-b478-7abaad14253b

┌─database─┬─table────────────┬─drop_part─┐
│ ntopng │ flows │ 20230213 │
│ ntopng │ flows │ 20230214 │
│ ntopng │ flows │ 20230215 │
│ ntopng │ flows │ 20230216 │
│ ntopng │ flows │ 20230217 │
│ ntopng │ flows │ 20230218 │
│ ntopng │ flows │ 20230219 │
│ ntopng │ flows │ 20230220 │
│ ntopng │ flows │ 20230221 │
│ ntopng │ flows │ 20230222 │
│ ntopng │ flows │ 20230223 │
│ ntopng │ flows │ 20230224 │
│ ntopng │ flows │ 20230225 │
│ ntopng │ flows │ 20230226 │
│ ntopng │ flows │ 20230227 │
│ ntopng │ flows │ 20230228 │
│ ntopng │ flows │ 20230301 │
│ ntopng │ flows │ 20230302 │
│ ntopng │ flows │ 20230303 │
│ ntopng │ flows │ 20230304 │
│ ntopng │ flows │ 20230305 │
│ ntopng │ flows │ 20230306 │
│ ntopng │ flows │ 20230307 │
│ ntopng │ flows │ 20230308 │
│ ntopng │ flows │ 20230309 │
│ ntopng │ flows │ 20230310 │
│ ntopng │ flows │ 20230311 │
│ ntopng │ flows │ 20230312 │
│ ntopng │ flows │ 20230313 │
│ ntopng │ flows │ 20230314 │
│ ntopng │ flows │ 20230315 │
│ ntopng │ flows │ 20230316 │
│ ntopng │ flows │ 20230317 │
│ ntopng │ flows │ 20230321 │
│ ntopng │ host_alerts │ 20230213 │
│ ntopng │ host_alerts │ 20230214 │
│ ntopng │ host_alerts │ 20230215 │
│ ntopng │ host_alerts │ 20230216 │
│ ntopng │ host_alerts │ 20230217 │
│ ntopng │ host_alerts │ 20230218 │
│ ntopng │ host_alerts │ 20230219 │
│ ntopng │ host_alerts │ 20230220 │
│ ntopng │ host_alerts │ 20230221 │
│ ntopng │ host_alerts │ 20230222 │
│ ntopng │ host_alerts │ 20230223 │
│ ntopng │ host_alerts │ 20230224 │
│ ntopng │ host_alerts │ 20230225 │
│ ntopng │ host_alerts │ 20230226 │
│ ntopng │ host_alerts │ 20230227 │
│ ntopng │ host_alerts │ 20230228 │
│ ntopng │ host_alerts │ 20230301 │
│ ntopng │ host_alerts │ 20230302 │
│ ntopng │ host_alerts │ 20230303 │
│ ntopng │ host_alerts │ 20230304 │
│ ntopng │ host_alerts │ 20230305 │
│ ntopng │ host_alerts │ 20230306 │
│ ntopng │ host_alerts │ 20230307 │
│ ntopng │ host_alerts │ 20230308 │
│ ntopng │ host_alerts │ 20230309 │
│ ntopng │ host_alerts │ 20230310 │
│ ntopng │ host_alerts │ 20230311 │
│ ntopng │ host_alerts │ 20230312 │
│ ntopng │ host_alerts │ 20230313 │
│ ntopng │ host_alerts │ 20230314 │
│ ntopng │ host_alerts │ 20230315 │
│ ntopng │ host_alerts │ 20230316 │
│ ntopng │ host_alerts │ 20230317 │
│ ntopng │ host_alerts │ 20230321 │
│ ntopng │ interface_alerts │ 20230213 │
│ ntopng │ interface_alerts │ 20230214 │
│ ntopng │ interface_alerts │ 20230215 │
│ ntopng │ interface_alerts │ 20230216 │
│ ntopng │ interface_alerts │ 20230217 │
│ ntopng │ interface_alerts │ 20230218 │
│ ntopng │ interface_alerts │ 20230219 │
│ ntopng │ interface_alerts │ 20230220 │
│ ntopng │ interface_alerts │ 20230221 │
│ ntopng │ interface_alerts │ 20230222 │
│ ntopng │ interface_alerts │ 20230223 │
│ ntopng │ interface_alerts │ 20230224 │
│ ntopng │ interface_alerts │ 20230225 │
│ ntopng │ interface_alerts │ 20230226 │
│ ntopng │ interface_alerts │ 20230227 │
│ ntopng │ interface_alerts │ 20230228 │
│ ntopng │ interface_alerts │ 20230301 │
│ ntopng │ interface_alerts │ 20230302 │
│ ntopng │ interface_alerts │ 20230303 │
│ ntopng │ interface_alerts │ 20230304 │
│ ntopng │ interface_alerts │ 20230305 │
│ ntopng │ interface_alerts │ 20230306 │
│ ntopng │ interface_alerts │ 20230307 │
│ ntopng │ interface_alerts │ 20230308 │
│ ntopng │ interface_alerts │ 20230309 │
│ ntopng │ interface_alerts │ 20230310 │
│ ntopng │ interface_alerts │ 20230311 │
│ ntopng │ interface_alerts │ 20230312 │
│ ntopng │ interface_alerts │ 20230313 │
│ ntopng │ interface_alerts │ 20230314 │
│ ntopng │ interface_alerts │ 20230315 │
│ ntopng │ interface_alerts │ 20230316 │
│ ntopng │ interface_alerts │ 20230317 │
│ ntopng │ system_alerts │ 20230213 │
│ ntopng │ system_alerts │ 20230214 │
│ ntopng │ system_alerts │ 20230215 │
│ ntopng │ system_alerts │ 20230216 │
│ ntopng │ system_alerts │ 20230217 │
│ ntopng │ system_alerts │ 20230218 │
│ ntopng │ system_alerts │ 20230219 │
│ ntopng │ system_alerts │ 20230220 │
│ ntopng │ system_alerts │ 20230221 │
│ ntopng │ system_alerts │ 20230222 │
│ ntopng │ system_alerts │ 20230223 │
│ ntopng │ system_alerts │ 20230224 │
│ ntopng │ system_alerts │ 20230225 │
│ ntopng │ system_alerts │ 20230226 │
│ ntopng │ system_alerts │ 20230227 │
│ ntopng │ system_alerts │ 20230228 │
│ ntopng │ system_alerts │ 20230301 │
│ ntopng │ system_alerts │ 20230302 │
│ ntopng │ system_alerts │ 20230303 │
│ ntopng │ system_alerts │ 20230304 │
│ ntopng │ system_alerts │ 20230305 │
│ ntopng │ system_alerts │ 20230306 │
│ ntopng │ system_alerts │ 20230307 │
│ ntopng │ system_alerts │ 20230308 │
│ ntopng │ system_alerts │ 20230309 │
│ ntopng │ system_alerts │ 20230310 │
│ ntopng │ system_alerts │ 20230311 │
│ ntopng │ system_alerts │ 20230312 │
│ ntopng │ system_alerts │ 20230313 │
│ ntopng │ system_alerts │ 20230314 │
│ ntopng │ system_alerts │ 20230315 │
│ ntopng │ system_alerts │ 20230316 │
│ ntopng │ system_alerts │ 20230317 │
│ ntopng │ system_alerts │ 20230321 │
│ ntopng │ user_alerts │ 20230215 │
│ ntopng │ user_alerts │ 20230216 │
│ ntopng │ user_alerts │ 20230227 │
│ ntopng │ user_alerts │ 20230316 │
│ ntopng │ user_alerts │ 20230317 │
│ ntopng │ user_alerts │ 20230321 │
└──────────┴──────────────────┴───────────┘

141 rows in set. Elapsed: 0.008 sec.

@sfedu-admin

**Comment by MatteoBiscosi** [comment]
Hi @sfedu-admin did you keep ntopng up and running until midnight? the removal of older data is done on a daily script that is executed at midnight

**Comment by sfedu-admin** [comment]
Yep, it's up and running 24/7.

df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             32G     0   32G   0% /dev
tmpfs           6.3G  1.2M  6.3G   1% /run
**/dev/sda2       193G  188G     0 100% /**

**Comment by sfedu-admin** [comment]
How can I force data retention script manually?

**Comment by sfedu-admin** [comment]
Is it safe to manually drop DB parts like this:

`ntop :) ALTER TABLE user_alerts DROP PARTITION '20230215';`

**Comment by MatteoBiscosi** [comment]
Hi, @sfedu-admin yes to drop the partition, you could, however, ntopng should do that.
Could you please share your journalctl -e -u ntopng ? to understand if the logs report some problem.

**Comment by sfedu-admin** [comment]
Looks like it's when we have no space left on disk
```
Mar 22 11:12:07 ntop ntopng[2534]: [ClickHouseImport.cpp:112] WARNING: Code: 108. DB::Exception: No data to insert: (in query: INSERT INTO flows (FLOW_ID,IP_PROTOCOL>
Mar 22 11:12:07 ntop ntopng[2534]: 22/Mar/2023 11:12:07 [ClickHouseImport.cpp:112] WARNING: Code: 108. DB::Exception: No data to insert: (in query: INSERT INTO flows>
Mar 22 11:12:07 ntop ntopng[2534]: [ClickHouseImport.cpp:111] WARNING: Unable to execute 'cat /storage/ntopng/tmp/clickhouse/clickhouse-4-1285-50001.1679463747.csv |>
Mar 22 11:12:07 ntop ntopng[2534]: 22/Mar/2023 11:12:07 [ClickHouseImport.cpp:111] WARNING: Unable to execute 'cat /storage/ntopng/tmp/clickhouse/clickhouse-4-1285-5>
Mar 22 11:12:07 ntop ntopng[2534]: [ClickHouseImport.cpp:112] WARNING: Code: 108. DB::Exception: No data to insert: (in query: INSERT INTO flows (FLOW_ID,IP_PROTOCOL>
Mar 22 11:12:07 ntop ntopng[2534]: 22/Mar/2023 11:12:07 [ClickHouseImport.cpp:112] WARNING: Code: 108. DB::Exception: No data to insert: (in query: INSERT INTO flows>
Mar 22 11:12:07 ntop ntopng[2534]: [ClickHouseImport.cpp:111] WARNING: Unable to execute 'cat /storage/ntopng/tmp/clickhouse/clickhouse-4-1471-50001.1679469866.csv |>
Mar 22 11:12:07 ntop ntopng[2534]: 22/Mar/2023 11:12:07 [ClickHouseImport.cpp:111] WARNING: Unable to execute 'cat /storage/ntopng/tmp/clickhouse/clickhouse-4-1471-5>
Mar 22 11:12:07 ntop ntopng[2534]: [ClickHouseImport.cpp:112] WARNING: Code: 108. DB::Exception: No data to insert: (in query: INSERT INTO flows (FLOW_ID,IP_PROTOCOL>
Mar 22 11:12:07 ntop ntopng[2534]: 22/Mar/2023 11:12:07 [ClickHouseImport.cpp:112] WARNING: Code: 108. DB::Exception: No data to insert: (in query: INSERT INTO flows>
Mar 22 11:12:07 ntop ntopng[2534]: 22/Mar/2023 11:12:07 [ClickHouseImport.cpp:111] WARNING: Unable to execute 'cat /storage/ntopng/tmp/clickhouse/clickhouse-4-1579-5>
Mar 22 11:12:07 ntop ntopng[2534]: [ClickHouseImport.cpp:111] WARNING: Unable to execute 'cat /storage/ntopng/tmp/clickhouse/clickhouse-4-1579-50001.1679472683.csv |>
Mar 22 11:12:07 ntop ntopng[2534]: 22/Mar/2023 11:12:07 [ClickHouseImport.cpp:112] WARNING: Code: 108. DB::Exception: No data to insert: (in query: INSERT INTO flows>
Mar 22 11:12:07 ntop ntopng[2534]: [ClickHouseImport.cpp:112] WARNING: Code: 108. DB::Exception: No data to insert: (in query: INSERT INTO flows (FLOW_ID,IP_PROTOCOL>

```

**Comment by MatteoBiscosi** [comment]
Hi @sfedu-admin then run directly this query in clickhouse-client:

SELECT DISTINCT database, table, toUInt32(partition) drop_part FROM system.parts WHERE active AND database='ntopng' AND drop_part <= 20230320 AND drop_part > 999999

This should drop the data older than 2 days ago, meanwhile, I'm going to investigate the issue.

**Comment by sfedu-admin** [comment]
> SELECT DISTINCT database, table, toUInt32(partition) drop_part FROM system.parts WHERE active AND database='ntopng' AND drop_part <= 20230320 AND drop_part > 999999

It's SELECT not DROP.

**Comment by MatteoBiscosi** [comment]
Hi @sfedu-admin i know, but you need to run that query before dropping the partitions.
To drop the partitions you have to run  

ALTER TABLE ntopng._TABLE_ DROP PARTITION _PARTITION_

and instead of _TABLE_ use the table that the above query returns and the corresponding _PARTITION_
e.g.

ALTER TABLE ntopng.flows DROP PARTITION 20230226

**Comment by MatteoBiscosi** [comment]
Hi @sfedu-admin we pushed a fix, and new builds are running, in 3/4 hours a new build should be available with the fix.

**Comment by sfedu-admin** [comment]
Just got the update
```
# ntopng --version
Version:	5.6.230322 [Enterprise/Professional build]
```
Hope it fixed my ClickHouse data retention issue.

**Comment by sfedu-admin** [comment]
> Just got the update
> 
> ```
> # ntopng --version
> Version:	5.6.230322 [Enterprise/Professional build]
> ```
> 
> Hope it fixed my ClickHouse data retention issue.

Data retention has fixed.
Thank you!
