### ISSUE TITLE
OPNsense plugin - Expose the -m parameter for local networks 

### ISSUE THREAD

**Issue by charris-msft** [ntop/ntopng#7339]
**What would you like to add or change?**:
Need the ability in OPNsense to specify additional local networks.
this is the `-m` parameter in the configuration file

**Why do you and others need this?**:
It is needed to enable data for additional local networks to flow to InfluxDB for reporting perposes.

**Comment by cardigliano** [comment]
@charris-msft I did double check, and the Local Networks configuration is actually present. I guess you are using the builtin plugin for the community built coming with opnsense. Please install ntopng Enterprise plugin (see screenshot)
<img width="1045" alt="Screen Shot 2023-03-22 at 10 53 47" src="https://user-images.githubusercontent.com/7548711/226866595-d17ec58d-8584-4b50-afa1-5e163c895f1c.png">
