### ISSUE TITLE
Traffic Report Local Networks missing

### ISSUE THREAD

**Issue by marcohueb** [ntop/ntopng#7340]
**Environment**:
* OS name: Debian GNU/Linux 11 (bullseye)
* Kernel: Linux 5.10.0-21-amd64
* Architecture: x86_64
* ntopng version/revision: 5.6.230321

**What happened**:
I have configured seven subnets as local networks. The Hosts - Networks view is correct and showing all seven. But Dashboard - Traffic Report only shows three and the graph also seems off (graphs not aggregated)

![hosts_networks](https://user-images.githubusercontent.com/127097894/226956727-2b9e2623-0189-4348-b0c3-c06979cf29fd.png)
![dashboard_traffic_report](https://user-images.githubusercontent.com/127097894/226956741-c2cda275-1b93-4b1f-a352-c323d2a4891d.png)

**Comment by MatteoBiscosi** [comment]
Hi @marcohueb the issue should now be fixed; in the next update (in 3/4 hours) the fix should be available. Please let me know.

**Comment by lucaderi** [comment]
Closing issue, will reopen if the fix didn't work as expected.
