### ISSUE TITLE
Periodicity Maps not available

### ISSUE THREAD

**Issue by srfn8kd** [ntop/ntopng#7345]
**Environment**:
* OS name: CentOS
* OS version: CentOS Stream release 8.6-1
* Architecture: x86_64
* ntopng version/revision: 5.6.230324 [Enterprise/Professional build]
GIT rev:        5.6-stable:9421bc068810e9d325ac00ad6d34c626b0b36b02:20230324
Pro rev:        r5548
Platform:       x86_64
Edition:        Enterprise L (Bundle)
License Type:   Permanent
Maintenance:    Until Wed Dec 13 06:02:15 2023 [263 days left]

**What happened**:  With behavior analysis configured the periodicity map does not show up on the left link list after restart and when clicking on the periodicity icon for a host pool, the linked page says, "You're not supposed to be here!
The requested page cannot be found"

Running a Fiberblaze FPGA running Savona  2.11.6.0 and the latest pf_ring and Cento releases

cat /etc/ntopng/ntopng.conf
-i=zcflow:11@0
-g=18,20,22,24
-y=26,28,30,32
-n=3
-d=/datassd/ntopng/
-x=1000000
-m=redacted
-W=redacted:3001
-F=clickhouse
-v=0
-X=32000000
--ignore-vlans=

**How did you reproduce it?**

**Debug Information**:

**Comment by srfn8kd** [comment]
I can find the periodicity maps when I use the Periodicity link from the top of the Interface details

**Comment by MatteoBiscosi** [comment]
Hi @srfn8kd to jump to the Periodicity Map you have to click on the Maps->Analysis entry and then jump to the periodicity map, from where are you trying to access the map, can you send me a couple of screenshots?
![image](https://user-images.githubusercontent.com/49585191/227878197-2ba5c438-08d8-4142-86c2-92b7e01f1bf2.png)

**Comment by MatteoBiscosi** [comment]
hi @srfn8kd the issue should now be fixed, in 3/4 hours update and let me know if everything is working correctly

**Comment by srfn8kd** [comment]
I tried to update, however there is an issue with your stable packages so the update fails



yum update ntopng
Last metadata expiration check: 1:57:52 ago on Tue 28 Mar 2023 06:58:17 AM PDT.
Dependencies resolved.
==============================================================================================================================================================================================================
 Package                                          Architecture                                Version                                                  Repository                                        Size
==============================================================================================================================================================================================================
Upgrading:
 cento                                            x86_64                                      1.18.230328-783                                          ntop                                             2.5 M
 n2disk                                           x86_64                                      3.6.230328-5286                                          ntop                                             4.4 M
 ndpi                                             x86_64                                      4.6.0-4160                                               ntop                                             700 k
 ndpi-dev                                         x86_64                                      4.6.0-4160                                               ntop                                             531 k
 ntopng                                           x86_64                                      5.6.230328-19916                                         ntop                                             6.4 M
 pfring                                           x86_64                                      8.4.0-8194                                               ntop                                             1.8 M
 pfring-dkms                                      noarch                                      8.4.0.8194-8194                                          ntop-noarch                                       79 k

Transaction Summary
==============================================================================================================================================================================================================
Upgrade  7 Packages

Total download size: 16 M
Is this ok [y/N]: y
Downloading Packages:
[MIRROR] n2disk-3.6.230328-5286.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 4639392 but expected size is: 4639396                                                             
[MIRROR] n2disk-3.6.230328-5286.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 4639392 but expected size is: 4639396                                                             
[MIRROR] ndpi-4.6.0-4160.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: e29da2d5e5d93107df5f16857919220dd59f4044355045e863018a30f84dc397(sha256)  Expected: 76ba33b3c38485d37f92942e79b1c726946e397c69528a955c161d825ac48ac9(sha256) 
[MIRROR] n2disk-3.6.230328-5286.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 4639392 but expected size is: 4639396                                                             
[FAILED] n2disk-3.6.230328-5286.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success

**Comment by srfn8kd** [comment]
Just updated - links available from maps and host pools.  Thank you!
