### ISSUE TITLE
Add RIPEstat link to Host Details page

### ISSUE THREAD

**Issue by lumarel** [ntop/ntopng#7346]
I have been recently using the new RIPEstat launchpad a whole lot more because it consistently delivers a lot of interesting information.

**What would you like to add or change?**:
Add a RIPEstat Lookup button beside the Whois Lookup button in the Host Details page.
Also I noticed that the AS lookup in the list view does not work anymore, and the one on the AS Details page already uses RIPEstat.

**Why do you and others need this?**:
It's a useful source of information for external IPs, AS networks and domains.

I also already played around with a test environment and created a patch for it, I can send a PR for that if wanted.
![image](https://user-images.githubusercontent.com/42647570/227738931-7fdb2335-a996-4ea4-9a58-3cc782897412.png)

**Comment by MatteoBiscosi** [comment]
Hi @lumarel you have have a pr to fix this issue, sure thing, you can open it, this is an open source project so we gladly welcome pr

**Comment by lumarel** [comment]
@MatteoBiscosi Okay thank you!
