### ISSUE TITLE
Alert bypassing exclusion

### ISSUE THREAD

**Issue by jacoporusso-css** [ntop/ntopng#7349]
**Environment**:
* OS name: CentOs Linux
* OS version:7
* Architecture: amd64
* nprobe version/revision: 10.2.230221

**What happened**:
Following #6905 issue, we're observing a similar behavior to the one reported: doing on nprobe an exclusion using protos file, only some alert is actually muted. I'm giving you an example for clarity: traffic to [...].amazontrust.com/[...] was generating both ndpi_error_code_detected and ndpi_http_suspicious_user_agent alerts, so we put host_risk_mask:".amazontrust.com"=0 on the protos file on nprobe. After that we stopped receiving ndpi_error_code_detected, but ndpi_http_suspicious_user_agent ones are still coming.

**Comment by MatteoBiscosi** [comment]
Hi @jacoporusso-css being an nProbe issue i moved the ticket there, thanks for your report
https://github.com/ntop/nProbe/issues/569
