### ISSUE TITLE
How to alarm if a network storm occurs？

### ISSUE THREAD

**Issue by dudumao520** [ntop/ntopng#7352]
Hello everyone,If a loop occurs in the network, resulting in a network storm, which alarm rule can provide an alarm? Which rule is in "Behavioral Checks"?

**Comment by MatteoBiscosi** [comment]
Hi @dudumao520, we currently have the DHCP Storm alert for the whole interface or the flow flood alert for the Network.
Which type of storm alert do you have in mind? If you have some idea and pcap to reproduce the situation, please drop an email at ' biscosi at ntop.org ' and we can add a new check.

**Comment by dudumao520** [comment]
@MatteoBiscosi Hello, thank you for your support and assistance!
①If the switch is not configured with the STP protocol, and there is a loop in the link, there will be a large amount of broadcast traffic in a short period of time. How can I give an early warning in this case?
②"Or how to give an early warning when a device on the network experiences a virus and sends out various kinds of messy data packets?"? TKS
