### ISSUE TITLE
Rework Custom Protocol Rules

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7361]
As of today the protocol rules do not have any check in terms of parameters, values and format. This needs to be modied and validated according to nDPI rule format

<img width="512" alt="Screenshot 2023-03-31 at 11 47 33" src="https://user-images.githubusercontent.com/4493366/229101636-3123b13a-d610-4420-960f-3d17ae088838.png">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
