### ISSUE TITLE
TheHive integration

### ISSUE THREAD

**Issue by lvandre** [ntop/ntopng#7363]
**What would you like to add or change?**:
Add direct integration to send alerts to TheHive

**Why do you and others need this?**:
Since TheHive is a Security Incident Response Platform, seems fitting that ntopng and its ability to send very detailed and rich alerts regarding possible network incidents should be integrated in a platform that is the most used in terms of SIRP around the world.

TheHive can receive alerts using the create alert API. In the maintainers document page [https://docs.strangebee.com/thehive/api-docs/#operation/Create%20Alert](url) there is the necessary information to be added. 
I have tried to use the ntopng ShellScript option but since the alerts are in a specific JSON format that I tried to parse but wasn't able to succeed, due to the message being a json inside a json.

In the maintainers link is all the JSON structure detail but bellow is a general look at what is sent:

> With curl
> Create an alert with observables of type strings using json
> 
> curl http://<thehive_endpoint>/api/v1/alert -H 'Authorization: Bearer <api_key>' -X POST -H 'Content-Type: application/json' --data '
> {
>   "type": "alertType",
>   "source": "test",
>   "sourceRef": "1",
>   "title": "alert title",
>   "description": "alert description",
>   "observables": [
>      { "dataType": "url", "data": "http://example.org" },
>      { "dataType": "mail", "data": "foo@example.org" }
>   ]
> }
> Create an alert with 2 observables, an url and a file, using multipart
> 
> curl http://<thehive_endpoint>/api/v1/alert -H 'Authorization: Bearer <api_key>' -X POST -F _json='
> {
>   "type": "alertType",
>   "source": "test",
>   "sourceRef": "1",
>   "title": "alert title",
>   "description": "alert description",
>   "observables": [
>      { "dataType": "url", "data": "http://example.org" },
>      { "dataType": "file", "attachment": "attachment0" }
>   ]
> }
> ' -F attachment0=@<file>

The observables can be very useful to add IP/MAC/URL address to be able to identify rapidly this information. That is currently easy with srv_ip and cli_ip, but some of the information inside the json: ".." is not very easy to parse.

Thank you and great work with the product!

**Comment by lucaderi** [comment]
@lvandre We have created a small prototype for the integration with TheHive but we would like first chat a bit with you to define the next steps. Are you interested?

**Comment by lvandre** [comment]
Hi @lucaderi yes of course.

**Comment by lucaderi** [comment]
Hi @lvandre Please send me a mail (deri@ntop.org) so we can arrange the chat/call
