### ISSUE TITLE
InfluxDB 1.X driver button grayed !

### ISSUE THREAD

**Issue by carnyx-io** [ntop/ntopng#7366]
Hello

I created a docker compose stack with Redis, InfluxDB 1.8 alpine and Ntopng/ntopng:stable containers.

Everything seems correct except for the "InfluxDB 1.x" button in the Timeseries drivers which is still greyed out. 
When I click on it, the focus stays on RRD

So I can't link ntopNG to influxDB.

To test, I added the "influxdb-client" package inside the ntopng container, but that didn't change anything...

All this is probably stupidity on my part, but I don't see what...

THANKS

**Comment by MatteoBiscosi** [comment]
Hi @carnyx-io could you please share a couple of screenshots? to understand better the issue

**Comment by carnyx-io** [comment]
Hello.

Hello
It seeams to be a problem with my Firefox navigator (actually v111). 

On Edge, i can switch the "timeseries Driver" button from RRD to "InfluxDB"..

I'll try to find another PC workstation to test Firefox again.

best regards
GE

**Comment by MatteoBiscosi** [comment]
Hi @carnyx-io oh that's really strange, please let me know, on my firefox it's working pretty well

**Comment by carnyx-io** [comment]
hello

Yes, it's strange. I've the same problem on another Firefox 111, under another windows version (W2012 server).

But hey, it works with another browser :-)

Thanks for taking the time to research this topic.

![ntop_InfluxDB_firefox](https://user-images.githubusercontent.com/129883450/230435293-90ba2eb2-c923-41e3-888e-e7c4a3f614fc.jpg)
