### ISSUE TITLE
Having payload in the historical flows

### ISSUE THREAD

**Issue by joonasak** [ntop/ntopng#7367]
**What would you like to add or change?**:
I saw in the lives flow there are payload information appear in the bottom of information but I didn't see it inside the historical flows. Matteo Biscosi explained to me that "we decided to currently not to add the payload information in historical flows, because it could be a long string, meaning that a lot more disk is used for each single flow". So I hope it could be existing inside the historical flows in the next release.

**Why do you and others need this?**:
It's a good to keep those information to check in the past.

**Comment by lucaderi** [comment]
We have decided to avoid saving this data as if you want payload info, you better enable ntopng with n2disk and have full payload and not just the first few bytes
