### ISSUE TITLE
99% of the ntopng flows dumped to Elasticsearch are dropped

### ISSUE THREAD

**Issue by msalmi77** [ntop/ntopng#7369]
**Environment**:
* OS name: [Ubuntu]
* OS version: [20.04.5 LTS]
* Architecture: [amd64]
* ntopng version/revision: [5.7.230403 with Enterprise Bundle L license  ]
* nprobe version/revision [10.3.230403]

**What happened**:
99% drops when flows dumped to Elasticsearch.   

**How did you reproduce it?**
Nprobe is configured as a flow collector from two edge routers. Packets are published to one ZMQ. Ntopng is listening on ZMQ and dumping flows to a 3 Master/data nodes Elasticsearch cluster hosted on OKD. 99% of the flows dumped to Elasticsearch are dropped and no errors shown in Elasticsearch with DEBUG mode enabled. No drops detected on the ntopng VM interface from where the packets leave. We have deployed another cluster in the same network as the ntopng VM but we still have the issue. All the components are hosted on Openstack and the backend storage is Cinder (Block storage with SSD disks).

P.S : Please note that we have an old setup of ntopng which is dumping flows to the same Elasticsearch cluster without any issue.  

**Debug Information**:

![image](https://user-images.githubusercontent.com/129944550/230063912-8638a407-7a3f-4a2b-83ba-dac2c9919500.png)

![image](https://user-images.githubusercontent.com/129944550/230061855-fcfcabc1-117d-4c8e-8a97-59f117377345.png)

![image](https://user-images.githubusercontent.com/129944550/230063757-3fccd8a0-dd6d-45b3-848b-cc8bbbe6268a.png)

**Comment by MatteoBiscosi** [comment]
Hi, @msalmi77 try to switch out the frequency of dumps to elastic search in the Preferences. In older versions, the frequency was 5 seconds, however, we changed it and by default, we put 2 minutes because it was too frequent (and it consumed a lot of memory and CPU). Having a lot of flows you probably drop them because you export these data every two minutes by default, try to lower the frequency (e.g to 30 sec)
![image](https://user-images.githubusercontent.com/49585191/230054538-7b47f1f3-3448-4ff5-8dc7-62822dd4c824.png)

**Comment by msalmi77** [comment]
Hi @MatteoBiscosi, we tuned this but unfortunately we are still facing the same issue : 

![image](https://user-images.githubusercontent.com/129944550/230064291-cfc10a25-25ec-464d-8659-78b4fc9279b9.png)

**Comment by lucaderi** [comment]
@msalmi77 The ingress rate is about 32 flows/sec which is pretty low, but I am wondering if the ELK installation is adequate for this rate. Did you check the ingress rate it can sustain? We suggest you to use ClickHouse if possible that is not affected by performance issues

**Comment by msalmi77** [comment]
@lucaderi  Unfortunately, we cannot use ClickHouse because other systems in the company are retrieving data from Elasticsearch.
 
Please note that two old ntopng setups (version 4.1.200427 ) as you can see below, are pushing to the same Elasticsearch cluster in parallel without any issue. The drops are not in Elasticsearch since I am not getting any error in ELK logs with debug mode enabled. I strongly believes that this is a bug in the new ntopng software. 

Can you try to reproduce the issue from your side ?.

![image](https://user-images.githubusercontent.com/129944550/230339876-46cbb626-0466-4f87-b1de-88ec03be9ee6.png)

**Comment by msalmi77** [comment]
Have you been able to reproduce the issue ? Any clue here ?

**Comment by cardigliano** [comment]
@msalmi77 are you available for a joint call to investigate this issue? Please drop us an email to schedule it.

**Comment by lucaderi** [comment]
I have implemented https://github.com/ntop/ntopng/commit/ae6a3d4cf12f3da7454490babd781122178be063 so if you start ntopng with "-v 3" we can analyze Elastic statistics. This change will be included in the next nighty build.

**Comment by msalmi77** [comment]
@cardigliano Sorry we were on a long vacation. Can you share your email address please to coordinate and schedule a call ?

**Comment by msalmi77** [comment]
@lucaderi How can we start ntopng from this repository on a systemd based OS ? I cannot find the binary to do this.

**Comment by msalmi77** [comment]
@lucaderi @cardigliano can any one support please ?

**Comment by cardigliano** [comment]
056dd000a30ad02a47c94bc652e852554cd2efe1 should address this, waiting for a feedback

**Comment by MatteoBiscosi** [comment]
Verified as fixed, please reopen if needed
