### ISSUE TITLE
about ntopng's system id and execute

### ISSUE THREAD

**Issue by theidforgithub** [ntop/ntopng#737]
When I reboot my machine and don't know why the system id
The system id is changed after my machine reboot .
I have checked runtime status it's show that " [LICENSE] ntopng is starting without a valid license".
My last SystemId is 3B0B1FB576056205 but now it is changed to B308B1CFB2092205.
I try to use the shop page to generate a new one and it show I've got one before.

The other problem is I found that my ntopng will stop collecting information during one minute left.
I saw not only hosts in bottom of page will stop change and stuck in  last number but also flows has this problem.

[CollectorInterface.cpp:104] Collecting flows on tcp://127.0.0.1:5556 [ntopng->nprobe]
[NetworkInterface.cpp:1512] Started packet polling on interface tcp://127.0.0.1:5556 [id: 2]...

Sometime the ntopng only get local network's information , and when it could receive my cisco netflow
two cloud icon will stop working . Two cloud icon in the bottom of page only working when I could only get local network information.

Is this problem caused by invalid license ? or I need to change my setting ?

There are some information I could provide ,

1 Gbit PF_RING ZC Intel [Linux]
OrderId:    1465847740

nProbe Standard [Linux/Win]
OrderId:    1465847766

ntopng Pro Small Business Linux/Win (x64)
OrderId:    1465847786

Thanks for your help ! Alvin

**Comment by simonemainardi** [comment]
Alvin,

System ID should not change. Are you running ntopng on top of a VM? Please, check that the hypervisor has not changed the underlying emulated hardware or mac addresses.

Try and add ntopng option `--online-license-check`. If this doesn't work, please contact me privately and I'll send you instructions to withdraw the license and generate a new one (mainardi ntop org). However, we should understand why the systemid is changing or we may end up in having the same issue. Also make sure to use the latest ntopng version.

---

The two clouds that you see at the bottom of the page are local-to-remote and remote-to-local traffic so, if there is no local traffic, both of them will be at zero and this is normal.

**Comment by theidforgithub** [comment]
Simonemainardi ,

Thanks for your help !

Maybe you are right, I've cloned my VM when I need to backup one . I didn't change my NIC even machine's hardware. I don't know will clone (the same mac address) will change the system id or not.
In this case , I believe maybe something is changed invisible ... 

so the ntopng stop collecting the traffic is normal if I have the invalid license ? 

It's seem to work after I add option you provide !! But when I reboot the VM , I need to restart the ntopng
or it will show

Sep 12 23:02:03 Log ntopng[614]: Starting ntopng:ntopng already running. Exiting ... failed!
Sep 12 23:02:03 Log ntopng[614]: failed!
Sep 12 23:02:04 Log systemd[1]: ntopng.service: control process exited, code=exited status=99
Sep 12 23:02:04 Log systemd[1]: Failed to start LSB: Start/stop ntopng web.
Sep 12 23:02:04 Log systemd[1]: Unit ntopng.service entered failed state.
After Uptime: 3 min ,it will stop collecting the traffic ...

## 

 And thanks for explain how the icon works .

Thanks You !! Alvin

**Comment by simonemainardi** [comment]
ntopng doesn't stop collecting traffic without a valid license, it just toggles in non-professional mode.

However, as you are running nprobe and ntopng on the same host, I guess it is the nprobe that stops sending traffic: without a valid license, nprobe stops exporting flows after a while. 
Indeed, the system id change affects both the ntopng and the nprobe.

btw, if ntopng fails to start on boot, please post `systemctl status ntopng` right after the reboot

**Comment by theidforgithub** [comment]
Very fast reply !! 
I think you are right although I solve the ntopng's problem but the nprobe hasn't changed .

sudo systemctl status ntopng
● ntopng.service - LSB: Start/stop ntopng web
   Loaded: loaded (/etc/init.d/ntopng)
   Active: active (running) since Mon 2016-09-12 23:18:48 CST; 8min ago
  Process: 1008 ExecStart=/etc/init.d/ntopng start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/ntopng.service
           └─1024 /usr/bin/ntopng /etc/ntopng/ntopng.conf

Sep 12 23:18:47 Log ntopng[1017]: [NtopPro.cpp:172] ERROR: [LICENSE] Invalid or missing ntopng License [License mismatch error]
Sep 12 23:18:47 Log ntopng[1017]: [NtopPro.cpp:185] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
Sep 12 23:18:47 Log ntopng[1017]: [NtopPro.cpp:187] WARNING: [LICENSE] before returning to community mode
Sep 12 23:18:47 Log ntopng[1017]: [NtopPro.cpp:188] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
Sep 12 23:18:47 Log ntopng[1017]: [NtopPro.cpp:189] WARNING: [LICENSE] or run ntopng in community mode starting
Sep 12 23:18:47 Log ntopng[1017]: [NtopPro.cpp:190] WARNING: [LICENSE] ntopng --community
Sep 12 23:18:48 Log ntopng[1008]: Starting ntopng:.

In ntopng , I could add the --online-license-check in /etc/ntopng/ntopng.conf  but how could I add the option in nprobe ? or I should provide my email to get new license  ?

**Comment by simonemainardi** [comment]
nprobe has the same option `--online-license-check` you can add it to the nprobe configuration file

**Comment by theidforgithub** [comment]
OK , I'll try it . And I need to put both nprobe and ntopng in rc.local or it will not start like above I post ...

**Comment by theidforgithub** [comment]
service nprobe status
● nprobe.service - LSB: Start/stop nprobe
   Loaded: loaded (/etc/init.d/nprobe)
   Active: active (exited) since Tue 2016-09-13 00:14:53 CST; 1min 15s ago
  Process: 613 ExecStart=/etc/init.d/nprobe start (code=exited, status=0/SUCCESS                                                                             )
Is it normal ??

**Comment by simonemainardi** [comment]
it's normal, it just say exited. start it

**Comment by theidforgithub** [comment]
okay I got it !
It's works now. I will keep monitoring it ! 
Thanks for help me !!!
