### ISSUE TITLE
ntopng GUI is hanging with -p

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7370]
The ntopng GUI is spinning when -p file has issues. Example

Unable to open file /Users/deri/Downloads/protos.txt [Permission denied]

<img width="1219" alt="Screenshot 2023-04-05 at 21 28 18" src="https://user-images.githubusercontent.com/4493366/230185690-89a75a94-cdd6-49c9-9d3d-37918d1906a3.png">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
