### ISSUE TITLE
Observation Points renaming

### ISSUE THREAD

**Issue by goltob** [ntop/ntopng#7371]
Hello,

I have added some additional questions/comments on the closed ticket https://github.com/ntop/ntopng/issues/7329 . Have you already seen that or have I to reopen a new ticket?

**Comment by MatteoBiscosi** [comment]
Hi @goltob
1) No those statistics are still per interface, not per observation points.
2) So whenever you change the name and click on "Save settings" no save is applied?
![image](https://user-images.githubusercontent.com/49585191/232726754-ef7d501e-2a6a-4de1-8340-7c588606eae7.png)
Could you right click the page -> Inspect and jump to the console tab and check if some error is reported there when you save the name?
![image](https://user-images.githubusercontent.com/49585191/232727412-c03b78a4-0d1b-457c-8fc0-ddbb7327c17a.png)
At the same time please send me the output of ' journalctl -e -u ntopng ' after saving the observation point alias, to check if some error is displayed there

**Comment by goltob** [comment]
2. That's correct, nothing happens - but it suddenly worked twice during the tests, but I then tested it again more than 10 times - without success again.
I didn't do or click anything differently. I just don't know why it worked once and then not again 20 times...

- no error about "journalctl -e -u ntopng" - no entry is displayed here when you do the renaming
- No errors in the browser console


Additional error: I noticed that selecting the observation point under "Flows -> Live" is not applied correctly or does not work at 
all:

![image](https://user-images.githubusercontent.com/62657418/232803970-741bf77e-9591-4a3e-b3cf-2a67b4e14ddc.png)


- I selected the observation point "21" in the drop-down menu - this can also be seen in the URL
- After loading, the dropdown menu jumps back to observation point "1" or at least shows it
- The "mp-ng01" is ALWAYS specified here as the "Flow Exporter", no matter which observation point I select - but the observation point 21 actually gets the data from "mp-ng11"

o The main instance where NTOPNG is running is apparently always given here and not the real source where the flow comes from

**Comment by goltob** [comment]
@MatteoBiscosi  do you have any news? We have also done some updates of ntopng in the meantime, but the behavior didn't change.

**Comment by lucaderi** [comment]
@goltob What exact ntopng version are you using?

**Comment by goltob** [comment]
@lucaderi  v5.6.230509

**Comment by earendilfr** [comment]
Hello,
I have seen the same issue (renaming of observation point doesn't work through the webUI).
I have try to apply the fix but it's always the same issue.

But, for information, if I do directly the modification with CURL, it's work correctly:

- WebUI => KO
- CLI with the following command => OK
```
curl -L -u <user>:<pwd> -H "Content-Type: application/json" https://ntopng.net.fhvi.ch/lua/rest/v2/set/observation_points/alias.lua -d '{ "alias":"<alias>", "observation_point":"<id>" }'
```
