### ISSUE TITLE
"Old" Pie Charts Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7374]
<img width="1426" alt="Screenshot 2023-04-08 at 11 42 36" src="https://user-images.githubusercontent.com/4493366/230714717-03872ece-33f6-47fe-85c3-c32fb751205e.png">
<img width="1412" alt="Screenshot 2023-04-08 at 11 42 20" src="https://user-images.githubusercontent.com/4493366/230714719-d37685aa-4a38-41b6-976b-a1f5fb9d7186.png">
<img width="1435" alt="Screenshot 2023-04-08 at 11 42 12" src="https://user-images.githubusercontent.com/4493366/230714720-837f99ba-450f-42c3-87bf-e3f225efcee3.png">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
![image](https://user-images.githubusercontent.com/49585191/231392052-a9dcd060-f264-47bc-8d0d-0bf925a96fd4.png)
