### ISSUE TITLE
Missing Search Box in "New" Tables

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7383]
<img width="1480" alt="Screenshot 2023-04-11 at 10 17 13" src="https://user-images.githubusercontent.com/4493366/231099391-e0aec924-aa10-4b7f-8976-dabce503ceb7.png">

Tables have a search box that is not present in "modern" tables and that is compulsory

**Comment by uccidibuti** [comment]
i added a new parameter map_search

**Comment by MatteoBiscosi** [comment]
Verified as fixed
