### ISSUE TITLE
Row Number in Alerts is not Honoured (and Row Value are not Sorted)

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7385]
<img width="481" alt="Screenshot 2023-04-11 at 11 55 54" src="https://user-images.githubusercontent.com/4493366/231125639-5aaf549e-a1a2-49ea-9f31-928240082e99.png">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
![image](https://user-images.githubusercontent.com/49585191/231392432-ebfc3370-30be-48b8-a745-39a9df803e6b.png)
![image](https://user-images.githubusercontent.com/49585191/231392559-ae1e6463-0b4d-4afc-802c-a96f5a9ca845.png)
