### ISSUE TITLE
Bad disk utilization units

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#7387]
Bad disk utilization units (it has been changed recently as it used to be correct):

- Traffic Recording Settings

<img width="819" alt="Screen Shot 2023-04-11 at 18 00 20" src="https://user-images.githubusercontent.com/7548711/231221340-dd29d962-a30b-4725-9856-0aba13f3d8f2.png">

- System Health
<img width="977" alt="Screen Shot 2023-04-11 at 18 01 22" src="https://user-images.githubusercontent.com/7548711/231221579-bacc1e79-e80d-4611-a85a-308a3d5678ca.png">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
![image](https://user-images.githubusercontent.com/49585191/231386495-432b4d98-ada7-4795-988b-67d334a689ca.png)
