### ISSUE TITLE
Develop new rest APi to save columns visibility and columns order in future

### ISSUE THREAD

**Issue by uccidibuti** [ntop/ntopng#7389]
We need to implement a new Rest Api to save and get Columns Visibility for each table.

- The rest to Save user columns config is a HTTP POST
/lua/rest/v2/add/tables/user_columns_config.lua with parameters:
```
 { table_id: string, visible_columns_ids: object[] } 
```
- The rest to Get user columns config is a HTTP GET
/lua/rest/v2/get/tables/user_columns_config.lua that return: 
```
{  visible_columns_ids: object[] }
```

**Comment by NicoMaio** [comment]
The visible_columns_ids must be sent as single string made up of a comma separated list of strings.
