### ISSUE TITLE
broken packages

### ISSUE THREAD

**Issue by brunoaraujocosta** [ntop/ntopng#739]
HI, having errors on install ntopng..

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ntopng : Depends: libhiredis0.10 but it is not installable
          Depends: libmysqlclient18 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by lucaderi** [comment]
Can you please report what platform/OS version are you using and attach the whole installation log?

**Comment by brunoaraujocosta** [comment]
Hi 
Using Ubuntu 16.04. I already add ntopng installed, but for somehow i can't install it again.
error:

The following packages have unmet dependencies:
 ntopng : Depends: libhiredis0.10 but it is not installable
          Depends: libmysqlclient18 but it is not installable
E: Unable to correct problems, you have held broken packages.

I only see apt-get logs with instalations. I can't see the failure on log

Regards

**Comment by lucaderi** [comment]
Again, no logs, no version, are not enough. Please share this info or I cannot help you

**Comment by lucaderi** [comment]
Working for me, will reopen if @brunoaraujocosta is able to reproduce it
