### ISSUE TITLE
Invalid Alert Records Reported

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7394]
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/4493366/231584326-f98bd9a5-3750-4745-af71-0fb2e93b06f3.png">

This issue can be reported logging in to the web GUI. On the ntopng console this error is returned

12/Apr/2023 23:00:15 [SQLiteAlertStore.cpp:161] ERROR: SQL Error: no such column: alerts_map
 SELECT 15 entity_id, (tstamp_end - tstamp) duration, *, hex(alerts_map) alerts_map FROM `system_alerts` WHERE (tstamp >= 1681331413 AND tstamp <= 1681333213) ORDER BY score desc LIMIT 10 OFFSET 0

**Comment by MatteoBiscosi** [comment]
Issue fixed in the latest dev and stable versions
