### ISSUE TITLE
Report Only Available Timeseries

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7395]
The ticket is to check the backend in order to show only those timeseries that exist and not all the timeseries as shown in the example below

<img width="1256" alt="Screenshot 2023-04-12 at 23 07 02" src="https://user-images.githubusercontent.com/4493366/231585306-e927f233-e271-4d7a-a70e-1b18a09e13e0.png">

**Comment by MatteoBiscosi** [comment]
The issue should be fixed, please reopen if needed
