### ISSUE TITLE
GUI authentication log file

### ISSUE THREAD

**Issue by emaklav** [ntop/ntopng#7398]
**What would you like to add or change?**:
Hello! Is it possible to write a log file with successful & unsuccessful authentication with source IP?

**Why do you and others need this?**:
Its a simpilest way to analise attacks from internet and blocking it by Fail2Ban.

**Comment by NicoMaio** [comment]
Proposal:

Upon startup of the HTTP server, a new Trace object should be instantiated which needs to receive a parameter for the log format (either the current format or Apache format) and open the log file.
Additionally, a preference must be defined to determine whether successful authentication attempts should be logged.

Within the HTTPserver, two events must be logged:

- 	In the HTTPserver::traceLogin an event should be logged when authentication is completed and the preference for logging successful attempts is enabled.

- 	In the HTTPserver::authorize_noconn an event should be logged in the case of successful authentication. 

A single log must contain a significant amount of information, such as the IP address of the client, the HTTP request method used, and the HTTP response status code.

The traceEvent method in the Trace class should be divided into two separate methods: one for formatting the log data and another for actually logging the data.

**Comment by lucaderi** [comment]
This is now implemented with the -L <file> option

**Comment by emaklav** [comment]
Ok, so how to use it?
