### ISSUE TITLE
ntopng - not able to open alert window - GUI is hanging

### ISSUE THREAD

**Issue by goltob** [ntop/ntopng#7399]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04
* Architecture: Intel Xeon
* ntopng version/revision: 5.6.230329

**What happened**:
By clicking in ntopng on the ALERT icon, the GUI is hanging.
See picture.

![image](https://user-images.githubusercontent.com/62657418/231966712-70f43b24-ff18-40d7-be61-7e749a3542a6.png)

**How did you reproduce it?**

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @goltob a new build should be available in 3/4 hours, please update and let me know if the issue persists
