### ISSUE TITLE
The Alert Explorer Page must have a Bar and not an Area Chart (as in Historical flows)

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7400]
<img width="1296" alt="Screenshot 2023-04-14 at 09 47 00" src="https://user-images.githubusercontent.com/4493366/231979165-029bcc91-823d-4c4a-b6a8-200e62fdf673.png">

**Comment by MatteoBiscosi** [comment]
This was a backend bug, the issue should be fixed in the latest dev version and currently cherry-picked in the stable version
