### ISSUE TITLE
After host alert disable not able to find the exclution alert in the exclustion list

### ISSUE THREAD

**Issue by goltob** [ntop/ntopng#7402]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04
* Architecture: Intel Xeon
* ntopng version/revision: 5.6.230329

**What happened**:
On the Alerts -> Explorer we select the error on host and DISABLE a alert by selecting "Delete Alerts".
The alert has been removed from the database and this is ok, but I am not able to see these exclustion in the Check exclution list.

**How did you reproduce it?**

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @goltob with the latest ntopng stable version the issue should be fixed

**Comment by MatteoBiscosi** [comment]
Hi @goltob I was able to reproduce the issue fix this issue. It should be fixed in the latest dev and stable versions
