### ISSUE TITLE
Flow Analysis: No Records Reported

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7404]
<img width="1610" alt="Screenshot 2023-04-15 at 09 30 59" src="https://user-images.githubusercontent.com/4493366/232196135-e9cd147e-3e53-40bd-a8e9-6b43b6745124.png">

Sometimes instead
<img width="1602" alt="Screenshot 2023-04-15 at 09 30 41" src="https://user-images.githubusercontent.com/4493366/232196145-3c04e1ed-938e-42e6-aa79-1d0f72fd37c3.png">

**Comment by MatteoBiscosi** [comment]
The issue seems fixed with the latest version
