### ISSUE TITLE
SQL Error: no such column: alerts_map

### ISSUE THREAD

**Issue by plamondon-ln** [ntop/ntopng#7411]
**Environment**:
pfSense 2.6.0-RELEASE (amd64) 
FreeBSD 12.3-STABLE
ntopng amd64 v.5.7.230418 (dev:a79faa5b622d86c57f25cb30ba2067f831c2bb69:20230418) Pro license
**What happened**:
Received a TCP SYN Scan Host alert.
Tried to view with Alertes Explorer => nothing about this alert
Read this message from /var/db/ntopng/ntopng.log:
[SQLiteAlertStore.cpp:161] ERROR: SQL Error: no such column: alerts_map
 SELECT 1 entity_id, (tstamp_end - tstamp) duration, *, hex(alerts_map) alerts_map FROM `host_alerts` WHERE ( alert_status = 0 ) AND (tstamp >= 1681838853 AND tstamp <= 1681840653) AND (sev
erity = 4) ORDER BY score desc LIMIT 10 OFFSET 0

Paste debug information below:
- Copy the service log from "systemctl status ntopng" or "journalctl -u ntopng".
systemctl: Command not found.
journalctl: Command not found.

**Comment by MatteoBiscosi** [comment]
Hi @plamondon-ln can you please share your ntopng configuration file?

**Comment by MatteoBiscosi** [comment]
Hi @plamondon-ln the issue should be fixed; please update to the latest version in a couple of hours and let me know

**Comment by plamondon-ln** [comment]
Hi Matteo, so far so good. Thanks for the fast response.
