### ISSUE TITLE
Wrong = instead of contains DGA filter in Alerts Filter

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7414]
<img width="262" alt="Screenshot 2023-04-20 at 06 51 41" src="https://user-images.githubusercontent.com/4493366/233261557-0bd420da-4223-4967-979c-c0514aa3a5b6.png">
<img width="805" alt="Screenshot 2023-04-20 at 06 51 34" src="https://user-images.githubusercontent.com/4493366/233261562-f53c98f2-c925-46b4-8131-a1f1030b83ce.png">

**Comment by cardigliano** [comment]
This requires:
1. the backend to pass the operator
2. the frontend to handle the passed operator (eq by default)
