### ISSUE TITLE
installation broken on raspberry pi 3

### ISSUE THREAD

**Issue by specterpete** [ntop/ntopng#7415]
After following the [download instructions](https://packages.ntop.org/) for raspian on a raspberry pi 3, 
I got the following lines in /etc/apt/sources.list.d/ntop.list:

```
deb [signed-by=/usr/share/keyrings/ntop-archive-keyring.gpg] https://packages.ntop.org/apt/bullseye_pi/ armhf/
deb [signed-by=/usr/share/keyrings/ntop-archive-keyring.gpg] https://packages.ntop.org/apt/bullseye_pi/ all/
```

when trying to install, the ntopng package was not found. I read in another ticket, that bullseye is for raspberry pi 4 only, and buster must be used on a pi 3. So i fixed the locations:

```
deb [signed-by=/usr/share/keyrings/ntop-archive-keyring.gpg] https://packages.ntop.org/apt/buster_pi/ armhf/
deb [signed-by=/usr/share/keyrings/ntop-archive-keyring.gpg] https://packages.ntop.org/apt/buster_pi/ all/
```

After this , the ackages were found. But now I run into a dependency problem:

```
pi@raspberrypi:/etc/apt/sources.list.d $ sudo apt-get install ntopng nprobe n2n
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nprobe : Depends: libjson-c3 but it is not installable
          Recommends: ntopng-data but it is not going to be installed
 ntopng : Depends: libjson-c3 but it is not installable
          Depends: libsnmp30 but it is not installable
E: Unable to correct problems, you have held broken packages.

```
I am stuck now since these packages are not available in raspian.

**Comment by lucaderi** [comment]
It works or me

deri@pi3 202> apt-cache search libjson-c3
libjson-c3 - JSON manipulation library - shared library
deri@pi3 203> lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
