### ISSUE TITLE
recordsTotal wrong in aggregated_live_flows.lua

### ISSUE THREAD

**Issue by uccidibuti** [ntop/ntopng#7416]
If i ask aggregated_live_flows with a start > of the total records on server, the rest api return recordsTotal: 0 even if there are records. recordsTotal should be represent the total number of records on server independently about start parameter.

**Comment by lucaderi** [comment]
<img width="1631" alt="Screenshot 2023-04-24 at 10 46 45" src="https://user-images.githubusercontent.com/4493366/233946520-d85ff356-e99d-44d8-a021-b4388a2e832a.png">
it looks like the REST is ok but the but seems to be in the GUI

**Comment by lucaderi** [comment]
Fixed
