### ISSUE TITLE
Menu Out of Sync

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7417]
Click on Interface -> graph icon
You obtain a chart for traffic that is wrong

- this is a traffic RX/TX timeseries but the dropdown menu is set to a different metric
- this is a chart of the last 30 min and not of the last 5 mins

<img width="1299" alt="image" src="https://user-images.githubusercontent.com/4493366/233772845-5f160419-d295-4630-b00b-66a1d7cbf809.png">

**Comment by MatteoBiscosi** [comment]
Issue fixed in the latest version
