### ISSUE TITLE
Display process id/name/commandline in Flows table .Display ip location in hosts table

### ISSUE THREAD

**Issue by acodervic** [ntop/ntopng#7418]
How do i display process id/name/commandline in  flows table? Like this :
![image](https://user-images.githubusercontent.com/57204004/233828604-6a281995-6735-4250-9a15-8c636c09f98f.png)

How do i display ip location  in  hosts table?Like this :

![image](https://user-images.githubusercontent.com/57204004/233828627-53fad498-cde3-49b7-8046-9b492aa8c307.png)

Thanks for everyone to help me !

**Comment by lucaderi** [comment]
You need to enable nProbe and export the process name with -T. For location make sure you have installed geolocation
