### ISSUE TITLE
Rework Device/MAC Address Tracking List

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7419]
1. Move the menu from Preferences to Hosts
2. Check that this feature is Enterprise and up
3. Split Excluded Device column in Name + MAC (as in Mac Addresses)
4. Rename the behavioural check that enables to feature to "Device/MAC Address Tracking" or similar but they must have the same name
5. Make sure that for devices with alert enabled, such alert is generated when the device connects and disconnects (change the label name)
6. Add batch action (as "Deleted Devices") to set for all records the Device Status and Disconnection Alert
7. Modify the preferences and set the learning period and preferences (allow/disallow) as in behavioural preferences

**Comment by plamondon-ln** [comment]
Hello,
what do you mean by "Check that this feature is Enterprise and up"
I paid 462 CAN$ for a professionnal license, and this feature won't be available to me?
Please say it isn't so...
Thanks

**Comment by MatteoBiscosi** [comment]
Verified as fixed
