### ISSUE TITLE
Occasionally ntopng does not start upon startup, logs seems ok, does not write pid to specified area

### ISSUE THREAD

**Issue by morphyno** [ntop/ntopng#742]
In the system we are deploying, instead of using ntopng service, we wish to launch ntopng in our own startup service. 

However, ntopng tries to launch, but fails to start.  I have "verbose" turned on but the log doesn't show what is missing.

The log below is actually identical to what I see during successfull startup 
`Sep 14 15:22:12 localhost dev-util: 14/Sep/2016 15:22:12 [Prefs.cpp:581] ntopng will use redis 127.0.0.1:6379@0`
`Sep 14 15:22:12 localhost dev-util: 14/Sep/2016 15:22:12 [Prefs.cpp:796] Logging into /apps/ntopng/ntopng.log`
`Sep 14 15:22:12 localhost dev-util: 14/Sep/2016 15:22:12 [Ntop.cpp:933] Setting local networks to 127.0.0.0/8`
`Sep 14 15:22:12 localhost dev-util: 14/Sep/2016 15:22:12 [AddressTree.cpp:139] Rule 127.0.0.0/8`
`Sep 14 15:22:12 localhost dev-util: 14/Sep/2016 15:22:12 [Redis.cpp:106] Successfully connected to redis 127.0.0.1:6379@0`
`Sep 14 15:22:12 localhost dev-util: 14/Sep/2016 15:22:12 [Ntop.cpp:907] Parent process is exiting (this is normal)`
`Sep 14 15:22:12 localhost systemd: Started dev server daemon.`

When examin /apps/ntopng/ntopng.log, I only see the following:

`[root@localhost ntopng]# cat ntopng.log`
`14/Sep/2016 15:22:12 [Ntop.cpp:933] Setting local networks to 127.0.0.0/8`
`14/Sep/2016 15:22:12 [AddressTree.cpp:139] Rule 127.0.0.0/8`
`14/Sep/2016 15:22:12 [Redis.cpp:106] Successfully connected to redis 127.0.0.1:6379@0`
`14/Sep/2016 15:22:12 [Ntop.cpp:907] Parent process is exiting (this is normal)`
`14/Sep/2016 15:22:12 [main.cpp:130] System has 8 CPU cores`

I suspect there is a timing issue. Is it possible to get more debug information?

**Comment by simonemainardi** [comment]
are you using systemd to control the start/stop of ntopng? can you attach you own 'startup service'?

**Comment by morphyno** [comment]
@simonemainardi, yes I am using systemd.

Below is my service script

[Unit]
Description=xyz server daemon
After=network.target

[Service]
Type=forking
ExecStartPre=/usr/bin/sh -c /opt/xyz/sbin/prep.sh
ExecStart= /opt/xyz/sbin/xyz-util init
ExecStop=/usr/bin/pkill -1 -f blah-daemon.sh
[Install]
WantedBy=multi-user.target

ntopng is actually invoked in "ExecStart", in a bash script that invokes ntop.

When I call "xyz-util init", it lacaunches fine, but when I run "systemctl restart xyz.service", ntopng does not launch

**Comment by morphyno** [comment]
So based on the output of "systemctl statys xyz.service", "xyz-util init" exitted successfully. "xyz-util" calls "ntopng" last, and you can see it seemingly has started (but it didn't)

[root@localhost states]# sudo systemctl status xyzd.service
xyzd.service - xyz server daemon
   Loaded: loaded (/usr/lib/systemd/system/xyzd.service; enabled)
   Active: active (running) since Thu 2016-09-15 15:31:49 EDT; 3min 0s ago
  Process: 30391 ExecStop=/usr/bin/pkill -1 -f blah-serv.sh (code=exited, status=0/SUCCESS)
  Process: 30410 ExecStartPost=/opt/xyz/sbin/xyz-util init (code=exited, status=0/SUCCESS)
  Process: 30408 ExecStart=/usr/bin/sh -c /opt/xyz/sbin/blah-serv.sh > /var/log/xyzd.log 2>&1 & (code=exited, status=0/SUCCESS)
  Process: 30403 ExecStartPre=/usr/bin/sh -c /opt/xyz/sbin/diskprep.sh (code=exited, status=0/SUCCESS)
 Main PID: 30409 (blah-serv.sh)
   CGroup: /system.slice/xyzd.service
           tq30409 /bin/bash /opt/xyz/sbin/blah-serv.sh
           mq30411 /usr/bin/python /opt/xyz/sbin/blah-serv.py

Sep 15 15:31:49 localhost.xyznet sh[30403]: /xyz_capture:        Already mounted
Sep 15 15:31:49 localhost.xyznet xyz-util[30410]: Address 172.60.110.111/16 already exists on enp1s0f0
Sep 15 15:31:49 localhost.xyznet xyz-util[30410]: enp1s0f0 initialized to 172.60.110.111/16: Enabled
Sep 15 15:31:49 localhost.xyznet xyz-util[30410]: starting ntop on interface enp1s0f1
Sep 15 15:31:49 localhost.xyznet xyz-util[30410]: 15/Sep/2016 15:31:49 [Prefs.cpp:581] ntopng will use redis 127....379@0
Sep 15 15:31:49 localhost.xyznet xyz-util[30410]: 15/Sep/2016 15:31:49 [Prefs.cpp:796] Logging into /xyz_apps/n...g.log
Sep 15 15:31:49 localhost.xyznet xyz-util[30410]: 15/Sep/2016 15:31:49 [Ntop.cpp:933] Setting local networks to 1...0.0/8
Sep 15 15:31:49 localhost.xyznet xyz-util[30410]: 15/Sep/2016 15:31:49 [Redis.cpp:106] Successfully connected to ...379@0
Sep 15 15:31:49 localhost.xyznet xyz-util[30410]: 15/Sep/2016 15:31:49 [Ntop.cpp:907] Parent process is exiting (...rmal)
Sep 15 15:31:49 localhost.xyznet systemd[1]: Started xyz server daemon.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by simonemainardi** [comment]
As you can see from here, the proper way to stop ntopng is correctly coded here: `https://github.com/ntop/ntopng/blob/dev/packages/etc/init.d/ntopng#L172`

If you skip our scripts and generate your own, then you should take care of that. Indeed, if proper cleanup isn't make on exit, then ntopng may fail to start.

However, I think your xyz-util is not properly following pattern used with systemd or, more in general, with services. You are using it to do many things (setting up interfaces, checking addresses, starting ntopng, etc), while each service should do only one action. My suggestion is to make separate services. You should leverage on the systemd units and use order directives (e.g., After= Before=) to regulate their start order
