### ISSUE TITLE
Disalligned columns.

### ISSUE THREAD

**Issue by NicoMaio** [ntop/ntopng#7421]
In aggregated live flows page 
![Schermata 2023-04-24 alle 12 08 01](https://user-images.githubusercontent.com/55502486/233966818-cc2d4447-ed0e-4dd0-ac82-82bb5ddfadbd.png)
 total score and metrics columns must be aligned like the live flows page. 
![Schermata 2023-04-24 alle 12 07 22](https://user-images.githubusercontent.com/55502486/233966794-db93407e-baff-4bae-b5cc-1e0c70e63f8d.png)

**Comment by lucaderi** [comment]
Verified as fixed
