### ISSUE TITLE
Invalid Timeseries Label

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7429]
The correct label is (as in hosts) Traffic TX + RX or if just Traffic RX+TX must be summed

<img width="1207" alt="Screenshot 2023-04-28 at 21 18 38" src="https://user-images.githubusercontent.com/4493366/235234616-24bb0cd6-4b1e-4f81-a82f-e20968a19676.png">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
