### ISSUE TITLE
pf_ring ZC config

### ISSUE THREAD

**Issue by GerogeW** [ntop/ntopng#743]
does anyone have some decent documentation on installing pf_ring and setting up ZC?
i've got a box sitting on about 2G of traffic and tons of packet loss on the RX interface.  i've got http://packages.ntop.org/ubuntu/16.04/x64/PF_RING/pfring_6.5.0-800_amd64.deb installed, but it seems like i'm missing setting up the ZC drivers?  i'm following this https://github.com/ntop/PF_RING/blob/dev/doc/PF_RING-UsersGuide.pdf as much as i can, but when i download the .deb file, i don't have to compile anything, so the steps are kind of out of order.
any feedback greatly appreciated.

**Comment by cardigliano** [comment]
Hi
I think this is the guide you are looking for:

https://github.com/ntop/PF_RING/blob/dev/doc/README.apt_rpm_packages

Please also take a look at:

https://github.com/ntop/PF_RING/blob/dev/doc/README.RSS

Alfredo

**Comment by GerogeW** [comment]
when trying to install 
dpkg -i pfring-drivers-zc-dkms_1.3_all.deb, 
i get error 
dpkg: dependency problems prevent configuration of pfring-drivers-zc-dkms:

 pfring-drivers-zc-dkms depends on e1000e-zc-dkms; however:
  Package e1000e-zc-dkms is not installed.
 pfring-drivers-zc-dkms depends on igb-zc-dkms; however:
  Package igb-zc-dkms is not installed.
 pfring-drivers-zc-dkms depends on ixgbe-zc-dkms; however:
  Package ixgbe-zc-dkms is not installed.
 pfring-drivers-zc-dkms depends on i40e-zc-dkms; however:
  Package i40e-zc-dkms is not installed.
 pfring-drivers-zc-dkms depends on fm10k-zc-dkms; however:
  Package fm10k-zc-dkms is not installed.
my network card is ixgbe,  i'm not sure how to troubleshoot?

**Comment by cardigliano** [comment]
Please follow the steps described at http://packages.ntop.org/apt/ (i.e. please use the repository)

**Comment by GerogeW** [comment]
How can i tell if the ZC drivers have been properly loaded now?  it seems i still can't start the pf_ring service

**Comment by cardigliano** [comment]
You can check it with:

# cat /proc/net/pf_ring/dev/eth1/info | grep ZC

Polling Mode:      ZC/NAPI

**Comment by GerogeW** [comment]
cat /proc/net/pf_ring/dev/enp4s0f0/info | grep ZC
returns no info

cat /proc/net/pf_ring/dev/enp4s0f0/info 
returns
Name:              enp4s0f0
Index:             4
Address:           0C:C4:7A:B7:34:BA
Polling Mode:      NAPI
Type:              Ethernet
Family:            Standard NIC

# Bound Sockets:   1

Max # TX Queues:   24

# Used RX Queues:  24

**Comment by cardigliano** [comment]
Did you "apt-get install pfring-drivers-zc-dkms" and configured according to README.apt_rpm_packages? If this is the case, please provide some output/log when starting the pf_ring service.

**Comment by GerogeW** [comment]
actually, that was how i installed ntop, but get an error when trying to install pfring-drivers-zc-dkms, . unable to locate package pfring-drivers-zc-dkms

**Comment by GerogeW** [comment]
what can i do to resolve it?

**Comment by cardigliano** [comment]
Please provide the full log of apt-get install pfring-drivers-zc-dkms (please cleanup the environment if you manually installed some package)

**Comment by GerogeW** [comment]
I've just wiped the server, and am starting over again.  I had manually tried to install several of the failed packages.  
If I'm starting from scratch, where is the best place to start fresh?
It seemed like i had to put different sets of instructions together to get the install to take last time.

**Comment by cardigliano** [comment]
This guide should be enough: https://github.com/ntop/PF_RING/blob/dev/doc/README.apt_rpm_packages

**Comment by GerogeW** [comment]
Ok, making some progress. clean install... i have everything installed successfully.. in nbox, i have ZC selected for ixgbe driver on the correct intefrace, with 16 receive side scaling queues.  still having packet loss and not reflecting correct throughput.  what else do i need to adjust to allow the proper performance?

**Comment by GerogeW** [comment]
I seem to have very little packet loss, less than 2%, until i add my local networks to the config, then i have almost 80% packetloss, what would i need to change

**Comment by GerogeW** [comment]
Actually, never mind.  It is just random.   very high packet loss.

**Comment by simonemainardi** [comment]
please report full configuration used

**Comment by GerogeW** [comment]
so actually, it lost my -x -X config when i rebooted it. not sure.
so the only time i have high packet loss is when i define the local networks.
here is my ntopng.conf
-w=3000
-W=0
-g=-1
-d=/storage/ntopng
-G=/var/run/ntopng.pid
-i=enp4s0f0
-x 512000
-X 512000

**Comment by GerogeW** [comment]
it would appear, when you use the nbox web console, it over writes the ntop.conf file.  
so when i was making changes via the web interface, it kept over writing my conf file, so it was removing my -x -X config.
it would appear as long as i always use the cmd line, it seems ok.
but with -w=3000
-W=0
-g=-1
-d=/storage/ntopng
-G=/var/run/ntopng.pid
-i=enp4s0f0
-x 512000
-X 512000
-m "actual subnets removed"
it seems better but still have 21% packet loss.  what other config file should i check, or use for the ZC config?

**Comment by simonemainardi** [comment]
I am not sure you are opening the card in Zero Copy.

please specify it as `-i zc:enp4s0f0` and optionally, if you use RSS, you can also create independent interfaces on a per-queue basis, e.g., `-i zc:enp4s0f0@0 -i zc:enp4s0f0@1 -i zc:enp4s0f0@2` that you can then combine together with a view.

By the way, also please check #740 and see if it is related

**Comment by GerogeW** [comment]
already using a SSD.  ok, so i've got it setup with
-i zc:enp4s0f0@0
-i zc:enp4s0f0@1
-i zc:enp4s0f0@2
-i zc:enp4s0f0@3
-i zc:enp4s0f0@4
-i zc:enp4s0f0@5
-i zc:enp4s0f0@6
-i zc:enp4s0f0@7
-i zc:enp4s0f0@8
-i zc:enp4s0f0@9
-i zc:enp4s0f0@10
-i zc:enp4s0f0@11
-i zc:enp4s0f0@12
is there a way to consolidate the data?  or see if i still have any packet loss / errors?
also, top local talkers on the zc:enp4s0f0@0: Top Local Talkers, does that include all queues?

**Comment by simonemainardi** [comment]
each -i is a separate queue. @0 doesn't include everything. you can merge interfaces together in a view using an ADDITIONAL view interface such as `-i view:zc:enp4s0f0@7,zc:enp4s0f0@8,zc:enp4s0f0@9`

**Comment by GerogeW** [comment]
when i use
-w=3000
-W=0
-g=-1
-d=/storage/ntopng
-G=/var/run/ntopng.pid
-i zc:enp4s0f0
-x 512000
-X 512000

I don't show any dropped packets, it just shows 0 PKTS, 
the network interfaces realtime traffic doesn't match what is on the port though either.

**Comment by GerogeW** [comment]
![capture](https://cloud.githubusercontent.com/assets/22206504/18593469/c4e76564-7bf8-11e6-8452-f147c9306c4f.PNG)
![capture2](https://cloud.githubusercontent.com/assets/22206504/18593497/e30be628-7bf8-11e6-9189-666eb4b2ef57.PNG)
![capture3](https://cloud.githubusercontent.com/assets/22206504/18593780/38d7ab04-7bfa-11e6-9aee-eb9eba27ad50.png)
The top pictures are when i use 
-i zc:enp4s0f0@0
-i zc:enp4s0f0@1
-i zc:enp4s0f0@2
-i zc:enp4s0f0@3
-i zc:enp4s0f0@4
-i zc:enp4s0f0@5
-i zc:enp4s0f0@6
-i zc:enp4s0f0@7
-i zc:enp4s0f0@8
the bottom picture is when i use config 
-i=enp4s0f0

**Comment by GerogeW** [comment]
My apologies, I thought you were not responding tot his issue when it was marked as closed.  that was why i opened new thread.  I still have issue when use config -i=zc:enp4s0f0
my utilization is not correctly being displayed at the bottom of page.
it only seems correct when using -i=enp4s0f0

**Comment by simonemainardi** [comment]
You said you have loaded PF_RING ZC with 16 RSS queues. So you need to add 16 interfaces to ntopng if you want to capture all the traffic (that is, interfaces `zc:enp4s0f0@0` to `zc:enp4s0f0@15`)

Remember that `-i=zc:enp4s0f0` is equal to `-i=zc:enp4s0f0@0` so you were just capturing from one queue.

As a bottom line: make sure to have as many ntopng interfaces as the actual number of RSS queues. Also, since you are monitoring 3Gbps, i guess 2-4 queues should suffice to avoid packet drops.

**Comment by ghost** [comment]
None of your guide links work anymore.
