### ISSUE TITLE
Device/MAC Address Tracking List - Loading...

### ISSUE THREAD

**Issue by plamondon-ln** [ntop/ntopng#7431]
ntopng amd64 v.5.7.230430 (dev:a73d7d84cf5eb3bbd59a68942d78a3cfa662ebf1:20230430) Professional
on pfsense 2.6.0-RELEASE (amd64)
FreeBSD 12.3-STABLE

Trying bevavioural check; interface, Unexpected Device Connected/Disconnected
I get no list as per the title and loadingg for ever.
Plus, I get this in /var/db/ntopng/ntopng.log:
30/Apr/2023 13:39:41 [HostChecksLoader.cpp:204] Unable to find host check external_host_script

Thank you for your time and efforts.

**Comment by MatteoBiscosi** [comment]
Hi @plamondon-ln the  Unable to find host check external_host_script and the loading for ever are not related, i fixed the issue with the loading for ever, in a couple of hours a new build with the fix should be up

**Comment by plamondon-ln** [comment]
Hi Matteo,
I tested it and unfortunately, still loading for ever.
Plus trying to access the Edit Check Options of the Unexpected Device Connected/Disconnected is greyed out and probably produces the [HostChecksLoader.cpp:204] Unable to find host check external_host_script error, we talked about.
Thank you

**Comment by plamondon-ln** [comment]
Hi Matteo,
This is to let you know that the device tracking list is now loading after software update ntopng v.5.7.230504 (20263) [OS: FreeBSD 12.2. 
Thanks.
