### ISSUE TITLE
radcli: rc_test_config: ntopng: no acctserver specified

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#7432]
Environment:
CentOS 8 Stream
4.18.0-489.el8.x86_64
amd64
[ntopng Enterprise L v.5.6.230428 (Rocky Linux release 8.7)

What happened:
Authentification through radius configured and works.
Ntopng log trashed by this messages:
May 2 07:44:15 ntopng[2114]: radcli: rc_test_config: ntopng: no acctserver specified
May 2 07:44:17 ntopng[2114]: radcli: rc_test_config: ntopng: no acctserver specified
May 2 07:44:22 ntopng[2114]: radcli: rc_test_config: ntopng: no acctserver specified
May 2 07:44:27 ntopng[2114]: radcli: rc_test_config: ntopng: no acctserver specified
May 2 07:44:39 ntopng[2114]: radcli: rc_test_config: ntopng: no acctserver specified
May 2 07:44:39 ntopng[2114]: radcli: rc_test_config: ntopng: no acctserver specified
May 2 07:44:51 ntopng[2114]: radcli: rc_test_config: ntopng: no acctserver specified
May 2 07:44:51 ntopng[2114]: radcli: rc_test_config: ntopng: no acctserver specified

What it is?

**Comment by MatteoBiscosi** [comment]
Hi @atemix can you update to the latest version and let us know if the issue persists?

**Comment by atemix** [comment]
Hi @MatteoBiscosi 
After updating to v.5.6.230531 (Rocky Linux release 8.7) issue still persists:

Jun  9 10:25:06 ntopng ntopng[2151]: radcli: rc_test_config: ntopng: no acctserver specified
Jun  9 10:25:12 ntopng ntopng[2151]: radcli: rc_test_config: ntopng: no acctserver specified
Jun  9 10:25:13 ntopng ntopng[2151]: radcli: rc_test_config: ntopng: no acctserver specified
Jun  9 10:25:14 ntopng ntopng[2151]: radcli: rc_test_config: ntopng: no acctserver specified
Jun  9 10:25:15 ntopng ntopng[2151]: radcli: rc_test_config: ntopng: no acctserver specified
Jun  9 10:25:21 ntopng ntopng[2151]: radcli: rc_test_config: ntopng: no acctserver specified
Jun  9 10:25:33 ntopng ntopng[2151]: radcli: rc_test_config: ntopng: no acctserver specified
Jun  9 10:26:06 ntopng ntopng[2151]: radcli: rc_test_config: ntopng: no acctserver specified
Jun  9 10:26:12 ntopng ntopng[2151]: radcli: rc_test_config: ntopng: no acctserver specified
Jun  9 10:26:13 ntopng ntopng[2151]: radcli: rc_test_config: ntopng: no acctserver specified
Jun  9 10:26:14 ntopng ntopng[2151]: radcli: rc_test_config: ntopng: no acctserver specified
Jun  9 10:26:15 ntopng ntopng[2151]: radcli: rc_test_config: ntopng: no acctserver specified
Jun  9 10:26:21 ntopng ntopng[2151]: radcli: rc_test_config: ntopng: no acctserver specified
Jun  9 10:26:33 ntopng ntopng[2151]: radcli: rc_test_config: ntopng: no acctserver specified
Jun  9 10:27:06 ntopng ntopng[2151]: radcli: rc_test_config: ntopng: no acctserver specified
Jun  9 10:27:12 ntopng ntopng[2151]: radcli: rc_test_config: ntopng: no acctserver specified
Jun  9 10:27:13 ntopng ntopng[2151]: radcli: rc_test_config: ntopng: no acctserver specified
Jun  9 10:27:14 ntopng ntopng[2151]: radcli: rc_test_config: ntopng: no acctserver specified
Jun  9 10:27:15 ntopng ntopng[2151]: radcli: rc_test_config: ntopng: no acctserver specified
Jun  9 10:27:21 ntopng ntopng[2151]: radcli: rc_test_config: ntopng: no acctserver specified
Jun  9 10:27:33 ntopng ntopng[2151]: radcli: rc_test_config: ntopng: no acctserver specified

**Comment by MatteoBiscosi** [comment]
This issue is fixed in the dev version. Unfortunately we cannot backport this fix to the stable version.
It doesn't count much this log, in the radcli there should be configured both the accounting server and authentication server.
