### ISSUE TITLE
ClickHouse Discard Files Grow Forever

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7433]
In case of failure, ClickHouse dump files are stored on disk and grow indefinitely. This needs to be fixed and at most 3 discarded files need to be saved on disk to avoid the disk being filled up.

**Comment by NicoMaio** [comment]
Fixed in pro repo by 75fb7a8896290aa7b2330c28e203a03c8bbc6105

**Comment by lucaderi** [comment]
Looks good
