### ISSUE TITLE
lua scripts got from directory where compiled, not installed

### ISSUE THREAD

**Issue by EAnsy** [ntop/ntopng#744]
May be my mistake... but after _make install_ I've purged _ntopng_ directory and then got something like _"lua script login.lua not found"_ error in web interface. Searching into FS show _login.lua_ file in _/usr/local/share/ntopng/scripts_ but logged in only after _git clone ntopng_ again.
So I've edited both files _login.lua_ to distinct them and proved _ntopng_ using compilation directory one. 
Is it right and how to fix?

**Comment by simonemainardi** [comment]
when building from source you can control all the installation dirs using `./configure`. See `./configure --help`

at runtime you tell ntopng which directories to use with the following options:

```
 [--httpdocs-dir|-1] <path>          | HTTP documents root directory.
                                    | Default: httpdocs
[--scripts-dir|-2] <path>           | Scripts directory.
                                    | Default: scripts
[--callbacks-dir|-3] <path>         | Callbacks directory.
                                    | Default: scripts/callbacks
```
