### ISSUE TITLE
Split Protocols (Guess and not Guess)

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7442]
In
![image](https://user-images.githubusercontent.com/4493366/235991574-428f7fa6-7f8c-496b-acca-89a024dea433.png)

for each application protocol (e.g. TLS) if you have traffic for TLS and TLS (guess) then these do not have to be merged as today, but be split into two protocols.

Note that inside the flow it's written if the flow protocol is guessed or not

**Comment by lucaderi** [comment]
An application protocol is guessed as returned by getConfidence(). In case the confidence is
   case NDPI_CONFIDENCE_DPI_CACHE:
    case NDPI_CONFIDENCE_DPI_PARTIAL_CACHE:
    case NDPI_CONFIDENCE_DPI:
    case NDPI_CONFIDENCE_NBPF:
 
then is it NOT guessed, otherwise is guessed.

**Comment by MatteoBiscosi** [comment]
Implemented as requested
