### ISSUE TITLE
nProbe Standard: Define IPs as "local" to a particular interface?

### ISSUE THREAD

**Issue by kph-ent** [ntop/ntopng#745]
We have several Mikrotik routers (one in each of several spread out geographic locations) sending Netflow (v9) info to a specific port on the server. I've currently got nprobe/ntopng set up with a separate "interface" for each router based on the port that gets the netflow data. So, like;

Router 1 --> server port 2055 == zmq tcp://1.2.3.4:5555
Router 2 --> server port 2056 == zmq tcp://1.2.3.4:5556
Router 3 --> server port 2057 == zmq tcp://1.2.3.4:5557 (etc)

(There are 8-10 locations, spread out over a fairly large area.)

I need to be able to tell nprobe/ntopng which IPs are "local" to each "interface" or router. So far, I've only been able to find out how to make one list of local IPs for all these interfaces together, and since there's some crossover, I think I'm getting duplicate info. Do I need to run separate instances of ntopng/nProbe to do this, or is there a way to configure "local hosts" specifically to each interface? Thanks!

**Comment by simonemainardi** [comment]
hi, ntopng doesn't mix hosts information, don't worry. So it is completely safe to define a local networks list that is the union of the lists of local networks belonging to each interface.

So for example if you have host 192.168.1.3 on interface i1 and i2, you will see it on both interfaces but each interface will keep independent and separated data for the host.
