### ISSUE TITLE
Failed to save historical data

### ISSUE THREAD

**Issue by TwoDogs2** [ntop/ntopng#7450]
system Centos7.8
version 5.6.230504 [Enterprise/Professional build]
'''
[root@ntopng 3]# ls
alerts  rrd  subnetstats  top_talkers
[root@ntopng 3]# pwd
/var/lib/ntopng/3
[root@ntopng 3]#
'''
Failed to enable traffic recording on the web, but there is no corresponding file in the system
the is log
"""
n2disk-ntopng@ens224.service failed.
Unit n2disk-ntopng@ens224.service entered failed state.
n2disk-ntopng@ens224.service: main process exited, code=exited, status=255/n/a
06/May/2023 14:08:45 [n2disk.c:7359] ERROR: Has the pf_ring kernel module been loaded ?
06/May/2023 14:08:45 [n2disk.c:7358] ERROR: Unable to initialize packet reader
06/May/2023 14:08:45 [n2disk.c:1338] Caught termination signal -1...
06/May/2023 14:08:45 [n2disk.c:4552] ERROR: Unable to open PF_RING device ens224: Address family not supported by protocol [snaplen=1536]
06/May/2023 14:08:45 [n2disk.c:4531] Using packet timestamps from pf_ring
06/May/2023 14:08:44 [n2disk.c:7222] Index processing memory is set to 206 MB (x 2 x 4 index files)
06/May/2023 14:08:44 [n2disk.c:7211] Dumping data in 0.1 MB chunks
06/May/2023 14:08:44 [n2disk.c:7179] Dump files max duration is set to 60 sec
06/May/2023 14:08:44 [n2disk.c:7173] Up to 100 files will be written per folder
06/May/2023 14:08:44 [n2disk.c:7155] Storage #0 directory: /var/lib/ntopng/3/pcap
06/May/2023 14:08:44 [n2disk.c:7121] Buffer memory is set to 1 GB (x 4 pcap files)
06/May/2023 14:08:44 [n2disk.c:7098] Dump files max size is set to 256 MB
06/May/2023 14:08:44 [n2disk.c:7051] Storage /var/lib/ntopng/3/pcap limit set to 100.00 GB, total volume size is 147.73 GB
blkid: write error
"""
Is it the reason for the standard version

**Comment by cardigliano** [comment]
@TwoDogs2 do you have pf_ring loaded (pfring-dkms package)? Please provide:
cat /proc/net/pf_ring/info

**Comment by TwoDogs2** [comment]
> @TwoDogs2 do you have pf_ring loaded (pfring-dkms package)? Please provide: cat /proc/net/pf_ring/info

Prompt that there is no such path
```
[root@ntopng ~]# cat /proc/net/pf_ring/info
cat: /proc/net/pf_ring/info: No such file or directory
```

**Comment by cardigliano** [comment]
@TwoDogs2 please install pfring (pfring-dkms) as this is required by n2disk, and also by ntopng for better performance (sorry for late reply)

**Comment by TwoDogs2** [comment]
> @TwoDogs2 please install pfring (pfring-dkms) as this is required by n2disk, and also by ntopng for better performance (sorry for late reply)

Sorry for the late reply, I'll give it a try Thank you very much
