### ISSUE TITLE
Interface Periodic Activity Not Executed

### ISSUE THREAD

**Issue by plamondon-ln** [ntop/ntopng#7454]
As soon as I activate this Behavioural Checks, I get this Engaged Alert that never goes away:
Periodic activity "5second" is queued but has not been executed. No thread available for execution. [Pending since xx:yy:zz]
The only way to clear that is to disable this check and restart Ntopng.

[2.6.0-RELEASE][admin@pfSense.gmhp]/root: /usr/local/bin/ntopng -V
Version:        5.7.230509 [Enterprise/Professional build]
GIT rev:        dev:175462b4d3066406a3afa0e40d2dcb4940cefa12:20230509
Pro rev:        r5715
Built on:       FreeBSD 12.2
System Id:      xxxxxxxxxxxxxxxx
Platform:       amd64
Edition:        Professional
License Type:   Permanent
Maintenance:    Until Sat Mar 30 13:54:22 2024 [325 days left]

**Comment by MatteoBiscosi** [comment]
Hi @plamondon-ln could you check if some errors are reported in the logs? (  journalctl -e -u ntopng  ).
What's the amount of traffic do you have? Number of flows and number of hosts too (they can be found here, screenshot below)
![image](https://github.com/ntop/ntopng/assets/49585191/da18c810-f632-415c-b7b4-e21b2cc578fb)

**Comment by plamondon-ln** [comment]
journalctl -e:
journalctl: Command not found.
![IMG_0806](https://github.com/ntop/ntopng/assets/60553360/680f570b-7bfa-4744-8736-63acd1deedc5)
No significant error message in /var/db/ntopng/ntopng.log
