### ISSUE TITLE
User authentication via RADIUS/PAP no longer works in ntopng

### ISSUE THREAD

**Issue by GrumpyOldNetworkGuy** [ntop/ntopng#7455]
**Environment**:
* OS name: Debian
* OS version: 11.7
* Architecture: amd64
# ntopng -V
Version:	5.7.230510 [Enterprise/Professional build]
GIT rev:	dev:056dd000a30ad02a47c94bc652e852554cd2efe1:20230510
Pro rev:	r5721
Built on:	Debian GNU/Linux 11 (bullseye)
System Id:	<removed>
Platform:	x86_64
Edition:	Enterprise L (Bundle)
License Type:	Permanent

**What happened**:
Since an automatic update of ntopng about two weeks ago, authentication via RADIUS/PAP no longer works. The reason is that CHAP is used instead of PAP:

RADIUS Protocol
    Code: Access-Request (1)
    Packet identifier: 0xd3 (211)
    Length: 88
    Authenticator: 53315c4c1e64bfd5d2152271bb22ce11
    Attribute Value Pairs
        AVP: t=User-Name(1) l=5 val=<removed>
            Type: 1
            Length: 5
            User-Name: tgh
        AVP: t=CHAP-Challenge(60) l=32 val=<removed>
            Type: 60
            Length: 32
            CHAP-Challenge: <removed>
        AVP: t=CHAP-Password(3) l=19 val=<removed>
            Type: 3
            Length: 19
            CHAP-Password: <removed>
                CHAP Ident: 0x23
                CHAP String: <removed>
        AVP: t=NAS-Port(5) l=6 val=0
            Type: 5
            Length: 6
            NAS-Port: 0
        AVP: t=NAS-IP-Address(4) l=6 val=<removed>
            Type: 4
            Length: 6
            NAS-IP-Address: <removed>
![radius-pap](https://github.com/ntop/ntopng/assets/86432254/f96e7c30-5aa7-4b4a-ac9b-3243a6b197e2)

**Comment by MatteoBiscosi** [comment]
Hi @GrumpyOldNetworkGuy i pushed a fix regarding the pap authentication, in a couple of hours a new update should be available, please update and let me know if it fixed the issue

**Comment by GrumpyOldNetworkGuy** [comment]
Hi @MatteoBiscosi You fixed it. Thanks.

**Comment by SteffenC7** [comment]
@MatteoBiscosi We have encountered this exact issue today in v6.7.260807 rev.28884 (Ubuntu 24.04.4 LTS)
We see that the packet capture contains CHAP even though the GUI setting is set to PAP. 
Can you reopen that issue to see what's wrong?
