### ISSUE TITLE
Invalid SNMP Interface Errors Count

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7456]
![Screenshot 2023-05-10 at 17 30 01](https://github.com/ntop/ntopng/assets/4493366/a8036a53-0bca-4885-92f1-b0e24ed6cb99)
![Screenshot 2023-05-10 at 17 29 51](https://github.com/ntop/ntopng/assets/4493366/53994862-dfb0-4bd9-9ecc-26a203fc32f2)

**Comment by NicoMaio** [comment]
Fixed in pro repo by 18a4acd2f54e837bde3fa6366daa06a0e8462645

**Comment by MatteoBiscosi** [comment]
Verified as fixed
