### ISSUE TITLE
nProbe Standard: Hardware requirments/tuning recommendations requested

### ISSUE THREAD

**Issue by kph-ent** [ntop/ntopng#746]
We have about 8-10 routers sending Netflow data for around 2,000-3,000 IPs to a single Centos 7 x86_64 server. We need to maintain historical data for at least 90 days. (I already know I need more disk space.)

Current CPU is  Intel(R) Xeon(R) X3323 @ 2.50GHz (fam:06, model: 17, stepping: 0a) (quad core)
RAM: 8GB

It's kind of barely handling the processing from three routers right now, but it seems to be pretty cpu/memory intensive, and slows the machine down perceptibly, both command line and web ntopng interface.

Suggestions for hardware appreciated. Also, suggestions for tuning ntopng/nprobe would be welcome as well. 

Thanks!

**Comment by lucaderi** [comment]
Hardware is a problem, but the main issue here is the configuration. How did you configure but nProbe and ntopng?

**Comment by lucaderi** [comment]
Closed for inactivity. Will reopen if necessary
