### ISSUE TITLE
Local Network Alerts not showing on table but they get counted on graph

### ISSUE THREAD

**Issue by marui07** [ntop/ntopng#7460]
**Environment**:
* OS name: Alma Linux
* OS version: 8.7
* Architecture: x86_64
* ntopng version/revision: 5.7.230512

**What happened**:
I set up behavioural checks for ingress and egress traffic to get alerted when I exceed certain bandwith. So when I tried to validate it,  the alerts on the alert explorer wouldnt show up on the table but on the chart were a few of them on the engaged tab. So my problem is that there is no detail on the Local Networks alerts because they dont show up on the table. I verified that the alerts that show up on the chart are real by changing ingress and eggress traffic alerts to a value I know it will trip the alerts.

Before changing values:
![Captura de pantalla 2023-05-12 114925](https://github.com/ntop/ntopng/assets/83734131/39850d4e-c803-4b7a-9896-d11d55160d85)

After changing values:
![Captura de pantalla 2023-05-12 115442](https://github.com/ntop/ntopng/assets/83734131/73e03f30-3903-46ab-8bdf-6fed849a0636)

**How did you reproduce it?**

First I was on the latest stable version for RHEL/Centos/Rocky (5.6.XXX), now I upgraded to nightly to test if the problem is still there (it is). I tried on another VM with Ubuntu server 22.04 LTS with the same strategy (enabling behavioural checks that I know they will trip). The I tried on a docker container and the same problem.

**Comment by marui07** [comment]
`May 12 11:53:49 almantop ntopng[324046]: [LuaEngine.cpp:1399] WARNING: Script failure [/usr/share/ntopng/scripts/lua/rest/v2/get/network/alert/list.lua][/usr/share/ntopng/scripts/lua/modules/alert_consts.lua:655: attempt to index a nil value (field '?')] 
May 12 11:53:49 almantop ntopng[324046]:  string stack traceback:
May 12 11:53:49 almantop ntopng[324046]:         /usr/share/ntopng/scripts/lua/modules/alert_consts.lua:652: in function 'alert_consts.alertEngine'
May 12 11:53:49 almantop ntopng[324046]:         ...odules/alert_definitions/other/alert_threshold_cross.lua:62: in function 'alert_threshold_cross.format'
May 12 11:53:49 almantop ntopng[324046]:         /usr/share/ntopng/scripts/lua/modules/alert_utils.lua:447: in function 'alert_utils.formatAlertMessage'
May 12 11:53:49 almantop ntopng[324046]:         .../scripts/lua/modules/alert_store/network_alert_store.lua:146: in function 'network_alert_store.format_record'`

I keep getting this error, I dont know if it related to this problem.

**Comment by cardigliano** [comment]
Fixed

**Comment by marui07** [comment]
> Fixed

Wait, it was already fixed or it's coming on the next update?
