### ISSUE TITLE
fritzdump.sh login failed with fritzOS 7.50

### ISSUE THREAD

**Issue by aberfisch** [ntop/ntopng#7461]
should fritzdump.sh still work with fritzOS 7.50. 
I am getting the following result:
```
Login failed. Did you create & use explicit Fritz!Box users?
```
and yes I created a explicit user for this and password is correct as well. 
any ideas or help is highly appreciated. THanks!

**Comment by lucaderi** [comment]
This is a script we have released as an example and it's not part of our products. We do not use Fritzbox anymore in our company. Feel free to send us patches if you will update the script.
