### ISSUE TITLE
So, what is the deal here? I paid 461.99 CAN$ for this Pro license and I have LOTS OF BUGS

### ISSUE THREAD

**Issue by plamondon-ln** [ntop/ntopng#7463]
I do not know what the target OS/platform is intended for this software but, since paying 462 CAN$ and installing it on my pfSense Version 2.6.0-RELEASE (amd64) on FreeBSD 12.3-STABLE, I only have LOTS of problems. Even though I followed the instructions on https://www.ntop.org/guides/ntopng/third_party_integrations/pfsense.html#pfsenseintegration of the latest ntopng-5.7.230513 for my installation.
The MOST APPALING FACT is that if I wipe everything and install the COMMUNITY version that comes with pfSense packadge manager (5.0.230124 [Community build]), almost EVERYTHING WORKS as intended free of charge!
My question thus becomes: can I get a refund?

**Comment by lucaderi** [comment]
Please contact me deri@ntop.org and we'll address your issues.
