### ISSUE TITLE
Alert Type Filter in Alerts is Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7465]
<img width="1464" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/a10c307f-5c00-45d7-bb1c-0adb02219adc">

**Comment by cardigliano** [comment]
I was able to reproduce this with SQLite as it does not support toUInt128 and other operators supported by ClickHouse only.
I pushed a temporary patch to match the predominant alert type only.
@NicoMaio please see how to implement the alert_map match in SQLite.

**Comment by NicoMaio** [comment]
It's not possible to search an alert_id into the alert_map using SQLite. At the moment, the patch made by Alfredo is the only fix possible.
