### ISSUE TITLE
Invalid interface reported in SNMP rules

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7467]
This device has several interfaces
<img width="1466" alt="Screenshot 2023-05-16 at 12 08 02" src="https://github.com/ntop/ntopng/assets/4493366/60765c8c-e1ef-4fb5-bd01-fa0e0b618ab0">
but none is reported
<img width="826" alt="Screenshot 2023-05-16 at 12 07 42" src="https://github.com/ntop/ntopng/assets/4493366/3279b273-768a-4620-975e-eb82d6c208a7">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
