### ISSUE TITLE
SNMP Rules: Interface Id is missing

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7469]
<img width="453" alt="Screenshot 2023-05-16 at 12 11 10" src="https://github.com/ntop/ntopng/assets/4493366/56a3cc4d-570a-4d8d-acce-5d3f3bb35cfa">

As discussed the formats must be <interface Name/Alias> (<interfaceId>)

**Comment by MatteoBiscosi** [comment]
Verified as fixed
