### ISSUE TITLE
How to bind two or more PF_RING ZC to a given cluster

### ISSUE THREAD

**Issue by rezaeimh7** [ntop/ntopng#747]
Hi.
Is it possible to bind some NICs which opened in ZC Mode, to a given cluster as follow:

![b5bda90c-63b3-11e6-82fd-076a3b9a79e8](https://cloud.githubusercontent.com/assets/15108703/18583189/3b6b5d88-7c1e-11e6-948f-f6f9f62837b5.jpg)

**Comment by rezaeimh7** [comment]
@cardigliano , @lucaderi  can you answer my question?

**Comment by lucaderi** [comment]
Yes it is possible: see https://github.com/ntop/PF_RING/blob/dev/userland/examples_zc/zbalance_ipc.c. Please do not post issues for pfring in ntopng.
