### ISSUE TITLE
Traffic Analysis information in Historical Flows

### ISSUE THREAD

**Issue by imadrafi** [ntop/ntopng#7470]
**What would you like to add or change?**:
Historical Flows are missing detailed Traffic Analysis information. I would like to request that detailed Traffic Analysis is added to Historical Flows as well. 

I present two cases to demonstrate my point. 

1. TCP/NetBIOS Flow
Live Flow shows rich traffic analysis information. Including TCP retransmits, Lost packets and Out-of-order packets, RTT to and from server and client, total Bytes transferred, Average and Peak transfers etc. This is great info. Lost packets, RTT, Retransmits tellms me a lot about the conversation and quality of transfer. 

Historical Flow is limited to: Total Bytes transferred, Server and Client Latency. Thats it. 

2. ICMP Flow
Live Flow shows rich traffic analysis info. Packet inter-arrival time, RTT, bytes transferred to and from client  and server etc. 
Historical flows only show Packet Inter-arrival time. 

**Why do you and others need this?**:
I cannot perform any Network Performance analysis without detailed traffic analysis info.
Detailed traffic analysis info is available with Live Flows. But completely missing in Historical Flows. 
I have no way to compare how my network is behaving over a longer period. I cannot troubleshoot user complains around network. I cannot quantify how config changes to network is impacting my network performance over historical periods.

My users complain about slow zoom calls they experienced yesterday (for example). I go and look at historical flows. I can see flows from their PC. But there is no useful info in there to help me say where is the issue - client side latency, server side latency etc. 

It would be great if detailed Traffic Analysis info is available. 

![Screenshot 2023-05-16 133201](https://github.com/ntop/ntopng/assets/89908241/be0c2e75-4933-44af-a441-885494ecd0ca)
![Screenshot 2023-05-16 130134](https://github.com/ntop/ntopng/assets/89908241/c49762ff-c041-49ad-b754-6a584df338da)
![Screenshot 2023-05-16 130042](https://github.com/ntop/ntopng/assets/89908241/28ccee30-a1a9-4546-b8a7-8704b38cad4b)
![Screenshot 2023-05-16 134038](https://github.com/ntop/ntopng/assets/89908241/57cf0969-bd3d-4383-8eb7-19c1dee8f51f)

**Comment by NicoMaio** [comment]
Hi @imadrafi,

We have added more information on the historical flow page. 
Please update it and let me know if it is sufficient for you.

**Comment by imadrafi** [comment]
Hi Nico, 
My ntop license has expired. Cant update the app.
I will renew the license and verify.

Thanks

**Comment by NicoMaio** [comment]
Hi @imadrafi 
Please open this issue in case you need it after your verification.
