### ISSUE TITLE
SNMP Rules: Missing %

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7475]
<img width="794" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/2db806ea-85f0-4b08-84a3-178693ad5f55">

This is how it is implemented in host traffic rules

<img width="344" alt="Screenshot 2023-05-16 at 12 21 58" src="https://github.com/ntop/ntopng/assets/4493366/4a6fb477-68a2-466e-aa6a-0c6bcbbefb89">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
