### ISSUE TITLE
SNMP Rules: Form Data is not Clean 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7477]
When clicking on + the form should appear as empty. Today it shows the previous data that was added

<img width="1432" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/9b3b2a39-1189-42a7-8f72-439607419205">

**Comment by NicoMaio** [comment]
In the form, only the SNMP interface can be cleaned. The default SNMP device selected is the first on the list. 
Is it ok?

**Comment by NicoMaio** [comment]
Fixed by 269317545e22d698ea01050f2811d60da1b1fe05

**Comment by MatteoBiscosi** [comment]
Verified as fixed
