### ISSUE TITLE
Hide from top talkers filter does not appear to work

### ISSUE THREAD

**Issue by xoengine** [ntop/ntopng#7478]
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
ntopng Enterprise L v.5.6.230515 rev.20382

Hosts added to the "hide from talk talkers" still appear in the top talkers dashboard.

<img width="484" alt="Screenshot 2023-05-16 at 7 11 06 AM" src="https://github.com/ntop/ntopng/assets/25558045/b4ead70c-72d7-4595-99d1-ec6fd95c062e">
<img width="1423" alt="Screenshot 2023-05-16 at 7 10 49 AM" src="https://github.com/ntop/ntopng/assets/25558045/48a94e51-7109-47df-8c4d-08e6b6f795d5">

**Comment by NicoMaio** [comment]
Hi @xoengine,

A new version has been released that fixes this issue. Please update and let me know.

**Comment by MatteoBiscosi** [comment]
Verified as fixed, please reopen if needed
