### ISSUE TITLE
nDPI protos mapping

### ISSUE THREAD

**Issue by aouinizied** [ntop/ntopng#748]
Dear nTop team,

In case we are exporting "L7_PROTO" field from a probe to ntopng.
Is there a way to change L7_PROTO mapping function in ntopng?
Example: The probe exports L7_PROTO=7 for "Bittorrent".
How to configure ntopng to interpret "7" as Bittorrent and not "HTTP".
I checked for protos.txt but it seems usefull only for port based or servername dissection.
We just want to overwrite ndpi protocols table.

Best regards,
Zied

**Comment by kYroL01** [comment]
Hi!
The protocol detection is based on nDPI default number associated to protocols.
Yes, _protos.txt_ is to specify a different name of the application detected, based on _tcp/udp ports_, _hostname_ or _ip range_.
I think you can use a similar option also for nProbe ( _--ndpi-proto-ports <flle>_ ) but this follows the rules of protos.txt.
nDPI is the library for detect the protocol and it's used by ntopng and nProbe; HTTP is assigned to number 7, Bittorrent to 37, and so on.

**Comment by aouinizied** [comment]
Hi! Thanks for the answer. 
Yes, Protos.txt is used to overwrite ndpi protos based on port and servername.
Yes ntopng use nDPI default protocols for L7 identification. nProbe too.
In my case, I implemented a probe that export records to ntopng. the L7 identification engine of my probe is not nDPI and do not cover the set of protocols covered by nDPI.
Lets say that my engine detects a set of prtocols [1 .. 5000] where "7" for example refers to a specific game protocol.
The probe detects this protocol and exports a record where "L7_PROTO"="7".
As ntopng is used as collector, the flow is displayed as "HTTP". Because ntopng relies on ndpi protocols ids.
My question is: where I have to change this to change how ntopng interpret the "L7_PROTO".
For exemple: I will set 7:OnlineGameX
                                    36: TorrentClientY
                                    5000: VerySophisticatedProtocol
Where numeric id is the L7_PROTO and the name is what we will be displayed in ntopng.

Best regards,
Zied

**Comment by lucaderi** [comment]
@aouinizied What you want to do is not supported. You should use in you probe the nDPI protocol numbers. So if you want to send BitTorrent you should not use  ID 7 but 37
#define NDPI_PROTOCOL_HTTP                  7
#define NDPI_PROTOCOL_BITTORRENT            37
