### ISSUE TITLE
Alert Table: Unknown 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7480]
Clicking on Unknown protocol it does not work (with other protocol works)

<img width="137" alt="Screenshot 2023-05-16 at 17 48 32" src="https://github.com/ntop/ntopng/assets/4493366/f31405cf-edf5-4f23-a2cb-6cac6ca080b8">

<img width="807" alt="Screenshot 2023-05-16 at 17 48 16" src="https://github.com/ntop/ntopng/assets/4493366/a82fec54-7ea3-403c-ad0a-66101a5b16e9">

**Comment by uccidibuti** [comment]
It should be a server side problem. We need check.

**Comment by cardigliano** [comment]
@uccidibuti please note this happens only for the Unknown protocol, which is in the list actually, thus looks like a client side issue. Please check.

**Comment by MatteoBiscosi** [comment]
Verified as fixed
