### ISSUE TITLE
Alert Page: CSS cuts the label way too much

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7483]
<img width="322" alt="Screenshot 2023-05-16 at 17 59 41" src="https://github.com/ntop/ntopng/assets/4493366/1de93393-2d50-4d8d-a322-68a260c0bff6">
<img width="268" alt="Screenshot 2023-05-16 at 17 59 34" src="https://github.com/ntop/ntopng/assets/4493366/cec39ab1-909b-47b4-b305-89c688d5a5a3">

**Comment by uccidibuti** [comment]
The rest must remove ntopng-external-link class style from info.desc 'a' tag content
```
<span><button data-to-copy='https://www.githubstatus.com' class='copy-http-url btn btn-light btn-sm border ms-1' style='cursor: pointer;'><i class='fas fa-copy'></i></button>  <a class='ntopng-external-link' href='https://www.githubstatus.com' target='_blank'><i class='fas fa-external-link-alt'></i> www.githubstatus.com</a></span>
```

**Comment by MatteoBiscosi** [comment]
Verified as fixed
