### ISSUE TITLE
SNMP Alerts: Edit won't work

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7485]
Suppose you have this entry

<img width="1088" alt="Screenshot 2023-05-16 at 20 47 03" src="https://github.com/ntop/ntopng/assets/4493366/d459c75c-b7c6-4804-858b-adc08799dd1a">

Click on edit and this is what I get

<img width="813" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/b882e253-4ce2-41df-8f30-4a884030376d">

In red the errored values

**Comment by MatteoBiscosi** [comment]
Verified as fixed
