### ISSUE TITLE
SNMP Alerts: Invalid Metrics Combination

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7487]
Throughput should be enabled only with bytes and not with packets and errors (packet with errors)

For packets and errors you need to support % and absolute number (also in K and M).

<img width="782" alt="Screenshot 2023-05-16 at 20 55 40" src="https://github.com/ntop/ntopng/assets/4493366/a6a95da7-bb1c-430d-b803-145de1d52ada">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
