### ISSUE TITLE
[nEdge] Fix action buttons in Hosts page

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#7489]
Similar to the flows page where action buttons have been fixed with a nowrap, please do the same for the hosts page

<img width="328" alt="Screen Shot 2023-05-17 at 13 50 49" src="https://github.com/ntop/ntopng/assets/7548711/ddac8d1b-a4c6-44fc-a664-5059faaa3e8f">

**Comment by NicoMaio** [comment]
Fixed by faf2d405df9fed8065973263c7be89349aa47a1d

**Comment by MatteoBiscosi** [comment]
Verified as fixed
