### ISSUE TITLE
Poudriere build failed - freebsd 10.3 - ntopng 2.4

### ISSUE THREAD

**Issue by 06chaynes** [ntop/ntopng#749]
I am having an issue when building ntopng with Poudriere and was hoping someone could point me in the right direction. I can build the package manually but Poudriere fails with the following error:

`DDATA_DIR='"/usr/local/share"' -I/wrkdirs/usr/ports/net/ntopng/work/ntopng-2.4/third-party/libgeohash -I/wrkdirs/usr/ports/net/ntopng/work/ntopng-2.4/third-party/patricia  -O2 -pipe -isystem /usr/local/include -fstack-protector -fno-strict-aliasing  -isystem /usr/local/include -c src/Flow.cpp -o src/Flow.o
src/Flow.cpp:349:28: error: no member named 'reply_code' in 'ndpi_flow_struct::<anonymous struct at /usr/local/include/libndpi-1.8.0/libndpi/ndpi_typedefs.h:913:5>'; did you mean 'ret_code'?
          if(ndpiFlow->protos.dns.reply_code == 0) {
                                  ^~~~~~~~~~
                                  ret_code
/usr/local/include/libndpi-1.8.0/libndpi/ndpi_typedefs.h:914:29: note: 'ret_code' declared here
      u_int8_t num_answers, ret_code;
                            ^
1 error generated.
gmake[1]: *** [Makefile:67: src/Flow.o] Error 1
gmake[1]: Leaving directory '/wrkdirs/usr/ports/net/ntopng/work/ntopng-2.4'
*** Error code 1`

**Comment by simonemainardi** [comment]
follow the instructions here if you want to build from source on freebsd: https://github.com/ntop/ntopng/blob/dev/doc/README.FreeBSD

In particular I guess you are using a wrong version of nDPI. check out nDPI sources in the same folder that contains ntopng sources and then business as usual: autogen, configure, make

**Comment by 06chaynes** [comment]
I was using nDPI version 1.8, needed 1.8_1. That fixed the issue, thanks for the help!
