### ISSUE TITLE
Include API REST Documentation in ntopng

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7490]
This is to request to take the [REST API](https://raw.githubusercontent.com/ntop/ntopng/dev/doc/src/api/rest/rest-api-v2.json) and display it in ntopng similar to what https://editor-next.swagger.io/ does

**Comment by MatteoBiscosi** [comment]
Implemented as requested, the entry can be found in the Developer menu 
![image](https://github.com/ntop/ntopng/assets/49585191/d7aa2969-1a64-429e-adab-3cb5ac7a3ca0)
