### ISSUE TITLE
Not able to stop Continous Traffic Recording

### ISSUE THREAD

**Issue by goltob** [ntop/ntopng#7491]
**Environment**:
* OS name: [Ubuntu]
* OS version: [22.04]
* Architecture: [virtual]
* ntopng version/revision: [5.6.230421]

**What happened**:
I have enabled the "Continous Traffic Recording" and afterwards I was not able to disable it.
I am not able to save the change from the UI.

![image](https://github.com/ntop/ntopng/assets/62657418/2f11e797-cbb0-45b8-971a-5432c031ae41)

**How did you reproduce it?**

**Debug Information**:

**Comment by cardigliano** [comment]
@goltob this is working for me, however I analysed the page and it may be due to a glitch in the html code. Could you try toggling off and setting 1 GB as max disk space, then Save Settings?

**Comment by goltob** [comment]
@cardigliano If I set the max value to 1 GB, I can no longer save the change. The "save settings" button stays "light blue", I can't click on it and save.

**Comment by cardigliano** [comment]
@goltob please try with the latest update (apt update && apt upgrade). How much free space do you have on disk?

**Comment by goltob** [comment]
@cardigliano free space on disk 8.7 GB, after update and upgrade it was possible to do the changes. Now I am at version v5.6.230522. 
Thanks a lot

**Comment by cardigliano** [comment]
Great, sorry for the inconvenience
