### ISSUE TITLE
Invalid border in Alerts Page (Safari)

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7496]
![Screenshot 2023-05-24 at 16 12 28](https://github.com/ntop/ntopng/assets/4493366/faaf6d60-a26b-44bc-9c79-b4f901e2f64b)
![Screenshot 2023-05-24 at 16 12 11](https://github.com/ntop/ntopng/assets/4493366/8053cf6e-103e-43bc-8557-934f10a922e2)

**Comment by MatteoBiscosi** [comment]
Verified as fixed
