### ISSUE TITLE
Missing HyperLinks

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7504]
<img width="911" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/dcf1912c-a888-4e25-afa8-efc3051aaa62">
In the port analysis, the Host and Port are not hyperlinked as they should be, thus making it impossible to navigate. Please transform the label in hyperlinks

**Comment by MatteoBiscosi** [comment]
Verified as fixed
