### ISSUE TITLE
ntop crash with a segfault

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#751]
I have 3 servers and all crashes each day with this output log

Sep 17 00:59:01 ntop-racine CRON[29793]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Sep 17 01:00:01 ntop-racine kernel: [1337189.515687] ntopng[21820]: segfault at a0 ip 00007f3509c31ff1 sp 00007f34e2ffc0a0 error 4 in libmysqlclient.so.20.3.2[7f3509bff000+392000]
Sep 17 01:00:01 ntop-racine CRON[30063]: (root) CMD (python /var/ntop/utils/scheduler.py > /dev/null 2>&1)
Sep 17 01:00:02 ntop-racine systemd[1]: ntopng.service: Main process exited, code=killed, status=11/SEGV
Sep 17 01:00:02 ntop-racine root: ntopng stop
Sep 17 01:00:02 ntop-racine ntopng[30066]:  \* Stopping ntopng
Sep 17 01:00:02 ntop-racine ntopng[30066]:    ...done.
Sep 17 01:00:02 ntop-racine systemd[1]: ntopng.service: Unit entered failed state.
Sep 17 01:00:02 ntop-racine systemd[1]: ntopng.service: Failed with result 'signal'.
Sep 17 01:00:07 ntop-racine systemd[1]: ntopng.service: Service hold-off time over, scheduling restart.
Sep 17 01:00:07 ntop-racine systemd[1]: Stopped Start/stop ntopng program.
Sep 17 01:00:07 ntop-racine systemd[1]: Starting Start/stop ntopng program...
Sep 17 01:00:07 ntop-racine root: ntopng start
Sep 17 01:00:07 ntop-racine ntopng[30160]:  \* Starting ntopng
Sep 17 01:00:08 ntop-racine kernel: [1337196.505914] ntopng[30199]: segfault at a0 ip 00007f70b9d43ff1 sp 00007f7092ffc0a0 error 4 in libmysqlclient.so.20.3.2[7f70b9d11000+392000]
Sep 17 01:00:08 ntop-racine ntopng[30160]: /etc/init.d/ntopng : ligne 143 : 30176 Erreur de segmentation  (core dumped) $NTOPNG_BINARY /etc/ntopng/ntopng.conf >> /var/log/ntopng/ntopng.log
Sep 17 01:00:08 ntop-racine ntopng[30160]:    ...done.
Sep 17 01:00:08 ntop-racine root: ntopng stop
Sep 17 01:00:08 ntop-racine ntopng[30215]:  \* Stopping ntopng

I try to catch a core dump.

Nico

**Comment by lucaderi** [comment]
packages are being rebuild. Reopen if necessary

**Comment by colinvv2** [comment]
So if you are preparing a solution for this problem, maybe by rebuilding the packages for a release upgrade, this ticket should remain 'open'? That would help cut down on the duplication of 'like' tickets. Also, please be sure to post when we can expect to see an updated package release.

**Comment by colinvv2** [comment]
I just upgraded to latest stable package release...
Get:1 http://www.nmon.net/apt-stable/14.04/ x64/ ntopng 2.4.160917-1671 [4,174 kB]
Get:2 http://www.nmon.net/apt-stable/14.04/ x64/ nprobe 7.4.160917-5333 [1,136 kB]
Get:3 http://www.nmon.net/apt-stable/14.04/ x64/ n2disk 2.6.160917-4666 [961 kB]
Get:4 http://www.nmon.net/apt-stable/14.04/ x64/ pfring 6.4.1-829 [1,475 kB]
Get:5 http://www.nmon.net/apt-stable/14.04/ all/ ntopng-data 2.4.160917 [21.4 MB]

**Comment by lucaderi** [comment]
You are using outdated packages configuration. Please use http://packages.ntop.org/apt-stable/ for instructions.
I confirm you the bug is fixed in both the dev and stable (https://github.com/ntop/ntopng/commit/98ee891ed1bff3c11be3922a93c03f62619b8d6a)
