### ISSUE TITLE
Invalid Form Validation in Edit Rule

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7511]
![image](https://github.com/ntop/ntopng/assets/4493366/3def8b94-5096-4de8-b5c9-bf8b397f5365)

When editing a traffic rule, the page that opens has some issues
- the edit button is disabled even if we change values (eg. from GB to MB in the example)
- the top label should be Edit and not Add

**Comment by MatteoBiscosi** [comment]
Verified as fixed
