### ISSUE TITLE
SNMP Traffic Rules don't Trigger Alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7512]
I have setup the following rules
<img width="1475" alt="Screenshot 2023-06-01 at 11 48 33" src="https://github.com/ntop/ntopng/assets/4493366/1c908c9a-2b35-44cb-bce2-0c847bf08c2f">

that should trigger alerts for sure. Then I wait a bit and check SNMP alerts and I see no alerts at all

<img width="1464" alt="Screenshot 2023-06-01 at 11 50 16" src="https://github.com/ntop/ntopng/assets/4493366/7aca11ba-e717-4622-a1be-3be1c9bb72a4">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
