### ISSUE TITLE
Invalid Flow Info Behaviour 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7514]
In "Historical Flows" clicking on the Info column

<img width="388" alt="Screenshot 2023-06-02 at 16 59 55" src="https://github.com/ntop/ntopng/assets/4493366/b183ebbd-9097-421e-ae9e-9e339e64dde1">

this error is returned 

<img width="1032" alt="Screenshot 2023-06-02 at 17 00 48" src="https://github.com/ntop/ntopng/assets/4493366/398da982-d771-4079-b2f7-ea1038e531a1">

and this is the URL that was generated (search undefined)

http://dell:3000/lua/pro/db_search.lua?ifid=0&epoch_begin=1685716112&epoch_end=1685717912&query_preset=&count=&undefined=registry.npmjs.org%3Beq

**Comment by MatteoBiscosi** [comment]
Verified as fixed
