### ISSUE TITLE
Unable to enlarge the last column of a table

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7515]
See historical alerts: the last column cannot be enlarged dragging the vertical bar. This behaviour is the same with all tables.

<img width="406" alt="Screenshot 2023-06-02 at 17 03 01" src="https://github.com/ntop/ntopng/assets/4493366/057757c4-06fe-4f11-b450-24eb1f7ba4f7">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
