### ISSUE TITLE
ntopng REST API keeps HTTP sockets open

### ISSUE THREAD

**Issue by angeloalduino** [ntop/ntopng#7517]
**Environment**:
* OS name: OPNsense 23.1.9-amd64 (FreeBSD 13.1-RELEASE-p7)
* OS version: 23.1.9
* Architecture: amd64
* ntopng version/revision: ntopng Community v.5.6.230525 rev.0 (FreeBSD 13.1)

**What happened**:
When using the ntopng [RESTful APIs](https://www.ntop.org/guides/ntopng/api/rest/api_v2.html), the server keeps a socket open for each request for approximately 1 minute, regardless of what HTTP connection headers are used by the client (e.g. `close` instead of `keep-alive`). This can also be seen when using the ntopng web UI, as it is polling in the browser as well. This is generally not an issue if polling at a lower interval (like every 10 seconds), but if polling more frequently the server will start to sporadically fail to respond, possibly due to socket exhaustion.

I've tried changing client code to use `keep-alive` vs `close` and also play with max timeout values, but it doesn't seem to make a difference. To rule out an issue with the host OS in general, testing the same requests against [node_exporter](https://github.com/prometheus/node_exporter) has expected results (the socket is closed immediately upon response completion).

**How did you reproduce it?**
Use `curl` to make any request to the API as seen in the [documentation examples](https://www.ntop.org/guides/ntopng/api/rest/examples_v2.html). After each invocation, check the open sockets on the server to verify that there is one open on the server port which will close after about 1 minute. This was verified in my environment by navigating to `Interfaces > Diagnostics > Netstat > Sockets` and refreshing the `Active internet connections`.

**Debug Information**:
Here is a screenshot showing the active connections when just using the ntopng web UI in the `Flows` section:

<img width="307" alt="ntopng_sockets" src="https://github.com/ntop/ntopng/assets/5280261/84f15bfd-a1d6-4047-bc22-7ece3d3c4551">

This is also what it looks like (but with even more connections) when polling the API with a 1 second interval.

Ideally the server would minimally respect `Connection: close` headers so that sockets are cleaned up after each API request.

Please let me know if there's anything else I should be trying here. Thanks for your consideration!

**Comment by lucaderi** [comment]
This is the typical socket lifecycle as explained
- https://stackoverflow.com/questions/3757289/when-is-tcp-option-so-linger-0-required
- https://www.ibm.com/docs/en/zvse/6.2?topic=SSB27H_6.2.0/fa2ti_call_setsockopt.htm

The socket that you see listed is in TIME_WAIT that is perfectly normal

```deri@freebsd13 351> netstat -na | grep 3000
tcp4       0      0 *.3000                 *.*                    LISTEN     
tcp4       0      0 127.0.0.1.3000         127.0.0.1.38141        TIME_WAIT  
tcp4       0      0 127.0.0.1.3000         127.0.0.1.23442        TIME_WAIT  ```

I could disable linger but this will be a rude shutdown

curl: (56) Recv failure: Connection reset by peer
deri@freebsd13 356> curl http://localhost:3000/lua/login.lua > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5238    0  5238    0     0  41861      0 --:--:-- --:--:-- --:--:-- 41904
curl: (56) Recv failure: Connection reset by peer <====

that is not pleasant. So in essence the behaviour is not harmful and it is perfectly fine, no need to be concerned.
