### ISSUE TITLE
Installation Failure Raspberry Pi4 -- Old Issue Unresolved?

### ISSUE THREAD

**Issue by wxprofessor** [ntop/ntopng#7522]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]

**What happened**:
I noticed a previous bug report on this issue from last year, and have attempted posted fixes to resolve installation failure, however, they were unsuccessful. I have included all relevant information below in an attempt to aid in debugging the issue. Thank you for looking :)

**How did you reproduce it?**

**Debug Information**:

user@raspberrypi:~ $ cat /proc/cpuinfo
processor       : 0
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2835
Revision        : c03114
Serial          : 10000000e9c6e84c
Model           : Raspberry Pi 4 Model B Rev 1.4

user@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

user@raspberrypi:~ $ sudo apt-get update
Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:3 https://packages.ntop.org/apt/bullseye_pi arm64/ InRelease
Hit:4 https://packages.ntop.org/apt/bullseye_pi all/ InRelease
Reading package lists... Done

user@raspberrypi:~ $ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

user@raspberrypi:~ $ wget http://packages.ntop.org/RaspberryPI/apt-ntop.deb
--2023-06-05 18:44:45--  http://packages.ntop.org/RaspberryPI/apt-ntop.deb
Resolving packages.ntop.org (packages.ntop.org)... 167.99.215.164, 2a03:b0c0:2:d                                                           0::d27:3001
Connecting to packages.ntop.org (packages.ntop.org)|167.99.215.164|:80... connec                                                           ted.
HTTP request sent, awaiting response... 302 Found
Location: https://packages.ntop.org/RaspberryPI/apt-ntop.deb [following]
--2023-06-05 18:44:45--  https://packages.ntop.org/RaspberryPI/apt-ntop.deb
Connecting to packages.ntop.org (packages.ntop.org)|167.99.215.164|:443... conne                                                           cted.
HTTP request sent, awaiting response... 200 OK
Length: 3226 (3.2K) [application/vnd.debian.binary-package]
Saving to: ‘apt-ntop.deb’

apt-ntop.deb        100%[===================>]   3.15K  --.-KB/s    in 0s

2023-06-05 18:44:46 (39.4 MB/s) - ‘apt-ntop.deb’ saved [3226/3226]

user@raspberrypi:~ $ sudo dpkg -i apt-ntop.deb
Selecting previously unselected package apt-ntop.
(Reading database ... 116344 files and directories currently installed.)
Preparing to unpack apt-ntop.deb ...
Unpacking apt-ntop (2.9-16) ...
Setting up apt-ntop (2.9-16) ...
Installing ntop GPG key. Please wait...
gpg: keybox '/usr/share/keyrings/ntop-archive-keyring.gpg' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 3D84C955924F7599: public key "Luca Deri <deri@ntop.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1

user@raspberrypi:~ $ sudo apt-get install ntopng nprobe n2n
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package ntopng is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ntopng' has no installation candidate
E: Unable to locate package nprobe

**Comment by lucaderi** [comment]
I see a few problems
1. After installing apt-ntop.deb you need to do "apt-get update" and then "apt-get install ntopng"
2. I believe you are running PiOS 32-bit instead of 64-bit: this is the main problem.

Please install PiOS 64 bit and it will work. Please see https://linuxhint.com/install-64-bit-version-raspberry-pi-os/ for details
