### ISSUE TITLE
Invalid SNMP Error Rule

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7524]
ONLY for Error metric
- use Packets as Threshold (i.e. number of errored packets)
- Remove < (for errors the threshold is greater than and not less than)

<img width="787" alt="Screenshot 2023-06-06 at 19 00 33" src="https://github.com/ntop/ntopng/assets/4493366/03059318-b604-46b0-a6a5-f2c796d11ec5">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
