### ISSUE TITLE
Improve SNMP Alert Error Messages

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7526]
Currently, SNMP alerts are like

SNMP Device Interface Threshold Crossed
Threshold crossed on Device 192.168.2.237, interface 1:7. [ Metric: Bytes (RX/TX) ] [ Measure Unit: Volume ] [ 0 < 1 GB ]

As alerts already have columns for
- Device IP
-  SNMP Interface
- SNMP Device Name

this is to request to reformat the message as follows
- Modify "SNMP Device Interface Threshold Crossed" -> "Threshold Cross"
- Modify "Threshold crossed on Device 192.168.2.237, interface 1:7. [ Metric: Bytes (RX/TX) ] [ Measure Unit: Volume ] [ 0 < 1 GB ]" -> "Metric: Bytes (RX/TX) / Unit: Volume / Value: X GB / Threshold:  < 1 GB"

**Comment by lucaderi** [comment]
Unfortunately, there are a few bugs 
- Clicking on the interface name column, a dialogue page is open. Clicking on the Apply button there is no action happening
<img width="896" alt="Screenshot 2023-06-08 at 22 28 38" src="https://github.com/ntop/ntopng/assets/4493366/bf8aac3c-8476-4d96-8c84-d9d65119bf0d">
- Clicking on the Info button a page is open but with the wrong URL without selecting the interface that caused the issue
<img width="1120" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/3538fde7-6e1c-49f6-bec2-2d18a1d7fd03">

**Comment by NicoMaio** [comment]
Fix the SNMP device rule alerts on the pro repository by f75e6a69fff24b8c137d962ffbedeb4c0056eb48

**Comment by lucaderi** [comment]
<img width="1657" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/ad0537e7-6a10-4540-a1d7-ac22bebfe906">

- Threshold Crossed -> Cross
- Clicking on Info it opens a wrong URL: it should show the Interface that triggered the problem and not the host page

**Comment by NicoMaio** [comment]
Fixed by 02b201ce61403b70a1eed08f656d3ce21abcaa7d

**Comment by lucaderi** [comment]
Verified as fixed
