### ISSUE TITLE
Improve SNMP Charts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7527]
Below are some errors to fix
- invalid colours
- wrong formatting 

<img width="1557" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/9eff49fe-7acd-45ea-bda7-817f9fbe3adf">

**Comment by lucaderi** [comment]
Not yet working

<img width="1204" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/04cc95d8-ef11-4f05-b300-d39bd4305f80">

**Comment by MatteoBiscosi** [comment]
the issue should be fixed, please reopen if any other charts with strange colors is available
![image](https://github.com/ntop/ntopng/assets/49585191/f6313b9a-0ffb-4588-9284-e74d409f605d)

**Comment by tano46** [comment]
Issue is just ther for some menu
![snmp](https://github.com/ntop/ntopng/assets/38938542/c5a1b61b-1c1a-4959-b515-3417d0ecccc6)

**Comment by tano46** [comment]
I report in addition that if I try to add extra charts derived from interfaces list they are correct from color point of view but ther is no complete legend info.

![snmp2](https://github.com/ntop/ntopng/assets/38938542/39aeaa98-2165-4d40-8553-ecba70518d16)
