### ISSUE TITLE
Invalid SNMP Interface Id in Alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7528]
Go to SNMP alerts page and click on an SNMP Interface

![Screenshot 2023-06-07 at 15 39 58](https://github.com/ntop/ntopng/assets/4493366/a09b932b-44ba-40d5-b963-b0110ba47369)

this dialog appears (the interface reported is wrong)

![Screenshot 2023-06-07 at 15 40 04](https://github.com/ntop/ntopng/assets/4493366/64bb5577-ed61-40b4-a28d-0ab49dde5a17)

and clicking on Apply has no effect

**Comment by cardigliano** [comment]
There are 2 issues here:
1. clicking on a snmp interface in the table, does not select the proper snmp interface in the dropdown
2. apply the filter leads to a bad query (fixed in 11ff3db6c815d27709ea8260089f94ff51036fe0)

@uccidibuti please check 1.

**Comment by cardigliano** [comment]
Duplicate of #7523

**Comment by cardigliano** [comment]
Both issues have been fixed

**Comment by lucaderi** [comment]
Verified as fixed
