### ISSUE TITLE
New Bootstrap Tables Color

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7529]
The new bootstrap tables have non-standard colors and need to be fixed

**Comment by lucaderi** [comment]
Not yet working: still all white, no colors.
<img width="1192" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/4110c875-e158-4157-ba5d-b58ba70d4a61">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
