### ISSUE TITLE
graphs layout ?

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#753]
I don't understand how work graphs layout on the main page
sometimes some graphs are reduce vs others (I mean graphs width), is there any reason ? is it dynamic ?

I use firefox
see below
![ntop1](https://cloud.githubusercontent.com/assets/17108017/18609223/35a83e04-7cfd-11e6-89a3-8fb378363154.png)
![ntop2](https://cloud.githubusercontent.com/assets/17108017/18609222/354ad1a6-7cfd-11e6-9bf6-516aa9ef120c.png)

**Comment by simonemainardi** [comment]
that's a FF issue. Use chrome until it's fixed

**Comment by emanuele-f** [comment]
@Niko78 this should be fixed now, check out new release and reopen if necessary, thank you.
