### ISSUE TITLE
Add Category to Alerts Page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7530]
This is to request to add the alert category to alerts page. The category can be extracted from the flow check that issued the alert.

**Comment by cardigliano** [comment]
Implemented in patch set 246e5a51427dcaa7b249d3bfd0ba3ce2329dde27 bb10dceb0e103031b021beb8e594fe62012fc36f 68046aafa8bffa51cf429b31ef98fd770c7ebbd7 fcdfaa04b0d514ac7df30137a7fc44de27b8fb0e 969db1b2f92db6fdb97bddd32340752ccb30aa36 2dfb9c9a215929383125e2551252e3e0c5dbb6be

**Comment by lucaderi** [comment]
Verified as implemented
