### ISSUE TITLE
Rework Alert Definition

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7531]
Modify the alert definition by adding a flag that specifies if the alert should be stored as "already" acknowledged or not.

Update the alerts table replacing past/ack with "eye" (require human intervention) and "all"

**Comment by cardigliano** [comment]
Implemented in patch set 2ac9ed0cfc3dce8c196786d5ab60aaa14f9b4171 4cfb9591c727410194f9de5b351d0da6039f3edb 45d1f106478a40f87cfa5479853ec3e64078c42d 9fa2e96809885d828940c4e5ee0d0ddb762df423 fff80b933e404177e9e2d898f216ee4c37dfefdf

**Comment by lucaderi** [comment]
Implementation ok, but documentation is missing. See #7592
