### ISSUE TITLE
Rework Server Port Analysis

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7532]
Add a new dropdown menu
- Protocol
- Application
- Server Port
![Screenshot 2023-06-07 at 18 56 12](https://github.com/ntop/ntopng/assets/4493366/4f80518e-2fa4-4c5b-835d-5d34ae332c3c)

**Comment by lucaderi** [comment]
still bugged (empty menu)

**Comment by MatteoBiscosi** [comment]
Verified as fixed
