### ISSUE TITLE
Improve Historical Flow Search Capabilities

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7535]
Historical flows contain attributes such as User Agent, HTTP return code, URL... that need to be added to the search field of historical flows

<img width="1305" alt="Screenshot 2023-06-08 at 14 47 15" src="https://github.com/ntop/ntopng/assets/4493366/454ae2e1-96b8-4448-b8dd-496a5a4d7d03">

**Comment by cardigliano** [comment]
This seems to be related to https://github.com/ntop/ntopng/issues/7032

**Comment by lucaderi** [comment]
Verified (for user agent)
