### ISSUE TITLE
Hourly Aggregated Flows: Missing Actions Column

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7543]
This is to request the implementation (as the leftmost column) of the "actions" column that is out of an aggregated row, it displays all the raw records (so not aggregated) that have been merged in such row.

In essence all the DB entries with the same 5 tuple + SNMP Interfaces and exporter IP and ntopng Instance name

**Comment by MatteoBiscosi** [comment]
Verified as fixed
