### ISSUE TITLE
Bulk actions in Alert Explorer are disabled

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#7545]
Bulk actions (e.g. button to delete all alerts) in the alert explorer are not working (disabled)

<img width="633" alt="Screen Shot 2023-06-09 at 11 34 48" src="https://github.com/ntop/ntopng/assets/7548711/993f0db8-baad-442a-82a3-ba935ba6468c">

**Comment by cardigliano** [comment]
- Delete Alerts is working
- Acknowledge is NOT working

**Comment by MatteoBiscosi** [comment]
Verified as fixed, however it requires a couple of seconds
