### ISSUE TITLE
unable to install ntopng on Raspberry Pi 

### ISSUE THREAD

**Issue by admKolodziejczak** [ntop/ntopng#7547]
Hi,
Been trying to install the ntopng on my Raspberry since a couple weeks, hoping this was jsut a bug that is going to be resolved, but seems like ntopng package is gone from the repo :/

patryk@raspberrypi:~ $ sudo apt-get install ntopng nprobe n2n
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package ntopng is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ntopng' has no installation candidate
E: Unable to locate package nprobe
patryk@raspberrypi:~ $

Any ideas?

**Comment by lucaderi** [comment]
I believe you are using a 32 bit rPI OS. Please upgrade to 64 bit and it will work

**Comment by admKolodziejczak** [comment]
Not the case unfortunately. I’m on 64bit version.. (aarch64)
