### ISSUE TITLE
Show name of triggering blacklist in blacklisted flow

### ISSUE THREAD

**Issue by solarexpedition** [ntop/ntopng#7549]
It would be very helpful when the blacklist-name which was triggering the alert is shown in a flow and also in the messages which will be forwarded to a syslog server.

Benefit:
Grepping through all the blacklists with all alerted ip's and domains directly on the ntopng host would no longer be necessary and would save so much time analyzing the alerts. This change would make visible much better which blacklists was triggering the alerts and will help to better identify false-positives and therefore which lists one should activate or not.

**Comment by solarexpedition** [comment]
I have tested it and it looks promising, but in GUI and syslog alarms, the blacklist names are most of the times empty.
![image](https://github.com/ntop/ntopng/assets/92759235/9095bff8-736d-45b8-b5c3-ae41673ea7eb)

I would suggest to replace the "@" sign with "Blacklist:" in the flow details.
This would make it more clear that it was triggered by a blacklist.
![image](https://github.com/ntop/ntopng/assets/92759235/ada6f7cf-5477-4b42-b073-ff78b133eaef)

In syslog messages, sometimes the blacklist-name is missing, sometimes not. I will observe this for a while.
![image](https://github.com/ntop/ntopng/assets/92759235/946cac2f-a8e7-4996-b4b6-2680047d55ac)

**Comment by NicoMaio** [comment]
It seems to be a problem with the engine retrieving the blacklist name.

**Comment by lucaderi** [comment]
Verified as fixed
