### ISSUE TITLE
Invalid Protocol Throughput Calculation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7554]
When selecting a protocol (e.g. HTTP), the highlighted throughput is wrongly computed. It does NOT have to be computed as the sum of the individual flow throughput but as the protocol's throughput (HTTP in this case) as computed using the accumulated byte count in the interface.

<img width="691" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/79cdbf1f-b345-4472-8118-0b2cd17fa173">

**Comment by MatteoBiscosi** [comment]
The issue seems fixed, tested on hsol
![image](https://github.com/ntop/ntopng/assets/49585191/f70c2bc1-e7cf-4363-b9c6-efba37ce324e)
