### ISSUE TITLE
Various Charts Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7556]
Clicking on any chart (small icon)

<img width="723" alt="Screenshot 2023-06-14 at 08 23 43" src="https://github.com/ntop/ntopng/assets/4493366/76c230df-d201-48fe-b9a5-8ccd4f997c32">

produces 

<img width="1313" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/6c6b31d2-97c3-4b48-80b7-4ccfcd3091b9">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
