### ISSUE TITLE
Historical Flows Top X

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7557]
As with Alerts, this is to request the implementation of top Hosts/Server/Client/Protocol

![Screenshot 2023-06-14 at 18 38 45](https://github.com/ntop/ntopng/assets/4493366/c9a26a07-3797-4a67-b098-544dce672ef2)

**Comment by NicoMaio** [comment]
Implemented in the pro repo by 27ebc65e8036550a80cafd12529c0f728df75519

**Comment by MatteoBiscosi** [comment]
Verified as fixed
