### ISSUE TITLE
dropped packets

### ISSUE THREAD

**Issue by GerogeW** [ntop/ntopng#756]
I have about 2.5G of traffic on a 10G interface.  I have ZC enabled i believe.
I have about 13% packet loss.
below is my ntopng.conf

-w=3000
-W=0
-g=-1
-d=/storage/ntopng
-G=/var/run/ntopng.pid
-i=enp4s0f0
-x 512000
-X 512000
-m "local subnets"

Can anyone provide guidance on getting rid of the dropped packets?

**Comment by simonemainardi** [comment]
I am not sure why you are ignoring the replies given to your previous issue: https://github.com/ntop/ntopng/issues/743

We have already explained you how to use PF_RING in ZC mode and how to configure RSS. And indeed, by properly configuring ntopng you confirmed that

> I don't show any dropped packets, it just shows 0 PKTS,
