### ISSUE TITLE
Rework Inactive Hosts Page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7562]
Rework the layout as follows in order to reduce the X size 
- remove the VLAN column and add @VLANID on the host. 
- Add a VLAN drop-down menu to select a specific VLAN
- Move Network as another drop-down menu and remove the column
- Do not add to the table multicast/broadcast addresses 
<img width="542" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/64c15a07-6e1f-493a-acd9-9c7a1edc671b">

**Comment by MatteoBiscosi** [comment]
The issue seems fixed with the multicast/broadcast addresses.
Dropdowns added and VLAN column removed and added to the IP column
![image](https://github.com/ntop/ntopng/assets/49585191/6c927ab8-6fa7-4d8d-92af-6bab4057ce80)

**Comment by lucaderi** [comment]
26/Jun/2023 22:42:54 [LuaEngine.cpp:1397] WARNING: Script failure [/Volumes/T7/deri/network/ntopng/scripts/lua/rest/v2/get/host/inactive_filters.lua][...work/ntopng/scripts/lua/modules/inactive_hosts_utils.lua:300: table index is nil]

This needs to be fixed

**Comment by MatteoBiscosi** [comment]
The issue should now be fixed.
Even the performances should be better

**Comment by lucaderi** [comment]
Verified as fixed. Performance is still very poor
