### ISSUE TITLE
Table must have at least an entry

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7566]
The "new" table has a major flaw

<img width="1388" alt="Screenshot 2023-06-16 at 11 33 55" src="https://github.com/ntop/ntopng/assets/4493366/7e34c2ad-45f4-4d9c-9e1a-36388e6b1c08">

When there are no rows this is how the table looks like. This instead is the correct layout (e.g. SNMP table) with an informative message:

<img width="1392" alt="Screenshot 2023-06-16 at 11 35 35" src="https://github.com/ntop/ntopng/assets/4493366/e3949d7d-c0bc-4a3d-9ff2-efaa2d65a1d0">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
