### ISSUE TITLE
Server Ports Analysis Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7568]
Selecting Server Ports Analysis (you can check on HSol) does not work, protocols listed are incomplete

<img width="440" alt="Screenshot 2023-06-16 at 21 38 38" src="https://github.com/ntop/ntopng/assets/4493366/4b16b6cb-8603-4254-8985-73cfa0eda725">

and some menu entries are empty instead of bein populated

<img width="429" alt="Screenshot 2023-06-16 at 21 39 11" src="https://github.com/ntop/ntopng/assets/4493366/1ee69a33-48f5-4879-90a7-cdee2ae77c2f">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
