### ISSUE TITLE
Fix Preferences Validation (including ClickHouse Settings)

### ISSUE THREAD

**Issue by NicoMaio** [ntop/ntopng#7569]
<img width="1480" alt="image" src="https://github.com/ntop/ntopng/assets/55502486/52d6f88c-0019-4d23-85b9-9ba0658fd5b5">

- When an upper bound or lower bound is not respected, the border of the label must be colored in red. 
- In this case, the save button has to be enabled at all times.

**Comment by cardigliano** [comment]
In my case the same settings report "1" (while minimum should be 10000) and there is even no message.
The same validation issue applies to (and should be fixed for) all the preferences, not just this specifically.

<img width="833" alt="Screen Shot 2023-07-12 at 15 33 28" src="https://github.com/ntop/ntopng/assets/7548711/a18dac30-eecb-4362-80a0-20d7cf50d64e">

**Comment by MatteoBiscosi** [comment]
The issue should partially be fixed. Unfortunatly it cannot be fully fixed until switching this page to vuejs
![image](https://github.com/ntop/ntopng/assets/49585191/bade3dd1-001f-4247-9ee5-6807a7bf2543)
![image](https://github.com/ntop/ntopng/assets/49585191/3b14d083-43a7-46e4-a018-2fbbed8f8154)

**Comment by NicoMaio** [comment]
Verified as fixed.
