### ISSUE TITLE
Unable to customize main top left logo

### ISSUE THREAD

**Issue by edrozenberg** [ntop/ntopng#757]
Based on scripts/lua/inc/menu.lua I created a custom_logo.jpg in the img directory but it is not used in the top left logo position. 

The logo appears to be hardcoded svg code in scripts/lua/modules/lua_utils.lua. I was trying to use a flat simple ntop logo instead of the standard 3d'ish logo which is out of fashion these days :).

**Comment by simonemainardi** [comment]
Please attach the new logo you have designed so we can consider it for inclusion.

Also remember that stripping the logo as well as hiding the copyright notice determines a license infringement. See sections 4 and 5 of the license:

>  You may convey ... copies of the Program's source code as you
> receive it, in any medium, provided that you conspicuously and
> appropriately publish on each copy an appropriate copyright notice

**Comment by edrozenberg** [comment]
Thank you Simone, I’m not interested in any License Infringement.

Here are the logo ideas I was thinking of. I’m not an artist and don’t
know what font you use for your logos. I can also just export
the svg and hard code it into the lua file myself. It would just be
easier if your app allowed a custom logo to be added in a simple
way.

https://cloud.githubusercontent.com/assets/2648417/18696316/ef49c802-7f6c-11e6-96d0-da5ac7c465a7.png

**Comment by simonemainardi** [comment]
Thanks for submitting, however you should use the official font VAG Rounded.

Please, feel free to reopen or create a pull request if you redesign the logos.
