### ISSUE TITLE
Historical Flow Overview is void

### ISSUE THREAD

**Issue by bioteseo** [ntop/ntopng#7571]
**Environment**:
* OS name: Ubuntu
* OS version: 22.04.2 LTS
* Architecture: x86_64
* ntopng version/revision: 5.7.230620
* clickhouse: 23.5.3.24

**What happened**:
Historical Flow Overview is void

**How did you reproduce it?**
Enter the historical flows (flow -> historical).
From the table displayed, choose info by clicking on the actions column (choose any of the rows). The page that opens contains no data.

**Debug Information**:
# journalctl -fe -u ntopng.service
giu 20 07:30:34 eymerich ntopng[750511]: 20/Jun/2023 07:30:34 [MySQLDB.cpp:754] Disconnected from MySQL for interface tcp://*:5556c...
giu 20 07:30:34 eymerich ntopng[750511]: 20/Jun/2023 07:30:34 [MySQLDB.cpp:917] Successfully connected to ClickHouse [default@127.0.0.1:9004][dbname: ntopng] for interface tcp://*:5556c
giu 20 07:30:34 eymerich ntopng[750511]: [MySQLDB.cpp:45] ERROR: SQL query: SELECT DST_PROC_NAME, DST_LABEL, SRC2DST_DSCP, TOTAL_BYTES, IPv6NumToString(IPV6_DST_ADDR) IPV6_DST_ADDR, IS_SRV_ATTACKER, SRC_NETWORK_ID, FLOW_ID, USER_LABEL, L7_PROTO, IP_SRC_PORT, IS_CLI_ATTACKER, PROTOCOL, SRC_PROC_NAME, VLAN_ID, SERVER_NW_LATENCY_US, IPv6NumToString(IPV6_SRC_ADDR) IPV6_SRC_ADDR, toInt32(FIRST_SEEN) FIRST_SEEN, toInt32(LAST_SEEN) LAST_SEEN, OBSERVATION_POINT_ID, SCORE, ALERT_STATUS, L7_PROTO_MASTER, SRC2DST_BYTES, ALERT_JSON, SEVERITY, FLOW_RISK, L7_CATEGORY, DST_PROC_USER_NAME, SRC_LABEL, DST2SRC_BYTES, DST2SRC_DSCP, USER_LABEL_TSTAMP, CLIENT_NW_LATENCY_US, SRC_MAC, INTERFACE_ID, SRC_PROC_USER_NAME, IS_SRV_BLACKLISTED, IS_SRV_VICTIM, IS_CLI_VICTIM, IS_CLI_BLACKLISTED, IP_PROTOCOL_VERSION, IP_DST_PORT, ALERTS_MAP, DST_COUNTRY_CODE, PROFILE, DST_HOST_POOL_ID, SRC_HOST_POOL_ID, PACKETS, OUTPUT_SNMP, INPUT_SNMP, CLIENT_LOCATION, IPv4NumToString(IPV4_SRC_ADDR) IPV4_SRC_ADDR, SERVER_LOCATION, DST_ASN, DST_NETWORK_ID, DST2SRC_TCP_FLAGS, IPv4NumToString(PROBE_IP) PROBE_IP, SRC_COUNTRY_CODE, SRC2DST_TCP_FLAGS, SRC_ASN, DST_MAC, COMMUNITY_ID, STATUS, NUM_FLOWS, NTOPNG_INSTANCE_NAME, INFO, IPv4NumToString(IPV4_DST_ADDR) IPV4_DST_ADDR FROM flows WHERE FLOW_ID = '5681926535' AND NTOPNG_INSTANCE_NAME = 'eymerich' AND FIRST_SEEN = 1687245692
giu 20 07:30:34 eymerich ntopng[750511]: 20/Jun/2023 07:30:34 [MySQLDB.cpp:45] ERROR: SQL query: SELECT DST_PROC_NAME, DST_LABEL, SRC2DST_DSCP, TOTAL_BYTES, IPv6NumToString(IPV6_DST_ADDR) IPV6_DST_ADDR, IS_SRV_ATTACKER, SRC_NETWORK_ID, FLOW_ID, USER_LABEL, L7_PROTO, IP_SRC_PORT, IS_CLI_ATTACKER, PROTOCOL, SRC_PROC_NAME, VLAN_ID, SERVER_NW_LATENCY_US, IPv6NumToString(IPV6_SRC_ADDR) IPV6_SRC_ADDR, toInt32(FIRST_SEEN) FIRST_SEEN, toInt32(LAST_SEEN) LAST_SEEN, OBSERVATION_POINT_ID, SCORE, ALERT_STATUS, L7_PROTO_MASTER, SRC2DST_BYTES, ALERT_JSON, SEVERITY, FLOW_RISK, L7_CATEGORY, DST_PROC_USER_NAME, SRC_LABEL, DST2SRC_BYTES, DST2SRC_DSCP, USER_LABEL_TSTAMP, CLIENT_NW_LATENCY_US, SRC_MAC, INTERFACE_ID, SRC_PROC_USER_NAME, IS_SRV_BLACKLISTED, IS_SRV_VICTIM, IS_CLI_VICTIM, IS_CLI_BLACKLISTED, IP_PROTOCOL_VERSION, IP_DST_PORT, ALERTS_MAP, DST_COUNTRY_CODE, PROFILE, DST_HOST_POOL_ID, SRC_HOST_POOL_ID, PACKETS, OUTPUT_SNMP, INPUT_SNMP, CLIENT_LOCATION, IPv4NumToString(IPV4_SRC_ADDR) IPV4_SRC_ADDR, SERVER_LOCATION, DST_ASN, DST_NETWORK_ID, DST2SRC_TCP_FLAGS, IPv4NumToString(PROBE_IP) PROBE_IP, SRC_COUNTRY_CODE, SRC2DST_TCP_FLAGS, SRC_ASN, DST_MAC, COMMUNITY_ID, STATUS, NUM_FLOWS, NTOPNG_INSTANCE_NAME, INFO, IPv4NumToString(IPV4_DST_ADDR) IPV4_DST_ADDR FROM flows WHERE FLOW_ID = '5681926535' AND NTOPNG_INSTANCE_NAME = 'eymerich' AND FIRST_SEEN = 1687245692
giu 20 07:30:34 eymerich ntopng[750511]: 20/Jun/2023 07:30:34 [MySQLDB.cpp:46] ERROR: SQL error (1): Code: 47. DB::Exception: Missing columns: 'NUM_FLOWS' while processing query: 'SELECT DST_PROC_NAME, DST_LABEL, SRC2DST_DSCP, TOTAL_BYTES, IPv6NumToString(IPV6_DST_ADDR) AS IPV6_DST_ADDR, IS_SRV_ATTACKER, SRC_NETWORK_ID, FLOW_ID, USER_LABEL, L7_PROTO, IP_SRC_PORT, IS_CLI_ATTACKER, PROTOCOL, SRC_PROC_NAME, VLAN_ID, SERVER_NW_LATENCY_US, IPv6NumToString(IPV6_SRC_ADDR) AS IPV6_SRC_ADDR, toInt32(FIRST_SEEN) AS FIRST_SEEN, toInt32(LAST_SEEN) AS LAST_SEEN, OBSERVATION_POINT_ID, SCORE, ALERT_STATUS, L7_PROTO_MAST
giu 20 07:30:34 eymerich ntopng[750511]: [MySQLDB.cpp:46] ERROR: SQL error (1): Code: 47. DB::Exception: Missing columns: 'NUM_FLOWS' while processing query: 'SELECT DST_PROC_NAME, DST_LABEL, SRC2DST_DSCP, TOTAL_BYTES, IPv6NumToString(IPV6_DST_ADDR) AS IPV6_DST_ADDR, IS_SRV_ATTACKER, SRC_NETWORK_ID, FLOW_ID, USER_LABEL, L7_PROTO, IP_SRC_PORT, IS_CLI_ATTACKER, PROTOCOL, SRC_PROC_NAME, VLAN_ID, SERVER_NW_LATENCY_US, IPv6NumToString(IPV6_SRC_ADDR) AS IPV6_SRC_ADDR, toInt32(FIRST_SEEN) AS FIRST_SEEN, toInt32(LAST_SEEN) AS LAST_SEEN, OBSERVATION_POINT_ID, SCORE, ALERT_STATUS, L7_PROTO_MAST

# systemctl status ntopng
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
     Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-06-20 05:30:26 UTC; 2h 11min ago
    Process: 750491 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exited, status=0/SUCCESS)
    Process: 750505 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
    Process: 750507 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (code=exited, status=0/SUCCESS)
    Process: 750509 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /run/ntopng.conf (code=exited, status=0/SUCCESS)
   Main PID: 750511 (ntopng-main)
      Tasks: 27 (limit: 77049)
     Memory: 5.2G
        CPU: 2h 58min 37.194s
     CGroup: /system.slice/ntopng.service
             └─750511 /usr/bin/ntopng /run/ntopng.conf

giu 20 07:19:31 eymerich ntopng[750511]: [MySQLDB.cpp:45] ERROR: SQL query: SELECT PROTOCOL, SRC_HOST_POOL_ID, toInt32(FIRST_SEEN) FIRST_SEEN, SRC_LABEL, L7_CATEGORY, DST2SRC_DSCP, SRC_PROC_NAME, USE>
giu 20 07:19:31 eymerich ntopng[750511]: 20/Jun/2023 07:19:31 [MySQLDB.cpp:45] ERROR: SQL query: SELECT PROTOCOL, SRC_HOST_POOL_ID, toInt32(FIRST_SEEN) FIRST_SEEN, SRC_LABEL, L7_CATEGORY, DST2SRC_DSC>
giu 20 07:19:31 eymerich ntopng[750511]: 20/Jun/2023 07:19:31 [MySQLDB.cpp:46] ERROR: SQL error (1): Code: 47. DB::Exception: Missing columns: 'NUM_FLOWS' while processing query: 'SELECT PROTOCOL, SR>
giu 20 07:19:31 eymerich ntopng[750511]: [MySQLDB.cpp:46] ERROR: SQL error (1): Code: 47. DB::Exception: Missing columns: 'NUM_FLOWS' while processing query: 'SELECT PROTOCOL, SRC_HOST_POOL_ID, toInt>
giu 20 07:30:34 eymerich ntopng[750511]: 20/Jun/2023 07:30:34 [MySQLDB.cpp:754] Disconnected from MySQL for interface tcp://*:5556c...
giu 20 07:30:34 eymerich ntopng[750511]: 20/Jun/2023 07:30:34 [MySQLDB.cpp:917] Successfully connected to ClickHouse [default@127.0.0.1:9004][dbname: ntopng] for interface tcp://*:5556c
giu 20 07:30:34 eymerich ntopng[750511]: [MySQLDB.cpp:45] ERROR: SQL query: SELECT DST_PROC_NAME, DST_LABEL, SRC2DST_DSCP, TOTAL_BYTES, IPv6NumToString(IPV6_DST_ADDR) IPV6_DST_ADDR, IS_SRV_ATTACKER, >
giu 20 07:30:34 eymerich ntopng[750511]: 20/Jun/2023 07:30:34 [MySQLDB.cpp:45] ERROR: SQL query: SELECT DST_PROC_NAME, DST_LABEL, SRC2DST_DSCP, TOTAL_BYTES, IPv6NumToString(IPV6_DST_ADDR) IPV6_DST_AD>
giu 20 07:30:34 eymerich ntopng[750511]: 20/Jun/2023 07:30:34 [MySQLDB.cpp:46] ERROR: SQL error (1): Code: 47. DB::Exception: Missing columns: 'NUM_FLOWS' while processing query: 'SELECT DST_PROC_NAM>

![historical flows table](https://github.com/ntop/ntopng/assets/316396/57982aca-d229-4f69-b616-ae17ea9da433)
![historical flow overview is void](https://github.com/ntop/ntopng/assets/316396/8864b3e5-9e7a-4b7b-bc89-2b666b3842e5)

**Comment by NicoMaio** [comment]
Hi @bioteseo,

We have made the fix and we are starting the builds. Please wait a couple of hours for the new version.

**Comment by bioteseo** [comment]
Problem solved. Thank you so much

**Comment by NicoMaio** [comment]
Verify as fixed.
