### ISSUE TITLE
Flow alerts analyzer - expand timeframe

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#7572]
**What would you like to add or change?**:
In the flow alerts analyzer max timeframe currently is 1 day.

Could it be extended like in alerts:
-last day
-last week
-last month
-last year
-custom

**Why do you and others need this?**:
Analyzing security logs is often done weekly or bi-weekly, but rarely or never daily.

Thanks

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu I updated the selectable timeframe with the same as in the alerts. The only problem is that it is not possible to add the time-picker component, so if you need other predefined timeframe, please let me know.

**Comment by lucaderi** [comment]
Verified as fixed
