### ISSUE TITLE
Alerts Action Info - wrong detail page is opening

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#7573]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [ntopng Enterprise L v.5.7.230620 (Ubuntu 20.04.5 LTS) 

**What happened**:
When pressing the Info text under action, the wrong info page is opened:
<img width="961" alt="Screenshot 2023-06-20 at 18 45 45" src="https://github.com/ntop/ntopng/assets/38549755/f044ab9b-ef3c-49a6-bf96-9283de61cf6d">

(in my case its an error, but the info page opening is warning

**How did you reproduce it?**

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi martin, the issue should be fixed in the latest version, please update and let me know

**Comment by lucaderi** [comment]
Verified as fixed
