### ISSUE TITLE
Historical flow filter bug

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#7574]
* ntopng version/revision: ntopng Enterprise L v.5.7.230620 (Ubuntu 20.04.5 LTS)
**What happened**:
In the historical filter I filter for : 
- Client name
- would like to filter for FTP-Control, but not available
<img width="787" alt="Screenshot 2023-06-20 at 19 00 28" src="https://github.com/ntop/ntopng/assets/38549755/fb0dfbec-7f34-43c2-90cd-f7b2cea968cc">

but filtering after clear text passwords works and there protocol is FTP_Control:

<img width="778" alt="Screenshot 2023-06-20 at 19 00 40" src="https://github.com/ntop/ntopng/assets/38549755/d566becf-f47c-4e31-87cb-77791af74d78">

**How did you reproduce it?**

**Debug Information**:

**Comment by cardigliano** [comment]
@martinscheu please note FTP_CONTROL can be selected in the "Application" filter as it is detected by nDPI, "Protocol" is for L4 only

<img width="810" alt="Screen Shot 2023-06-22 at 14 18 40" src="https://github.com/ntop/ntopng/assets/7548711/a4073a2e-1329-4009-90bb-ad54273ea2d3">

**Comment by martinscheu** [comment]
my bad, thanks for the info @cardigliano
