### ISSUE TITLE
pcap download not working

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#7575]
* ntopng version/revision: ntopng version/revision: ntopng Enterprise L v.5.7.230620 (Ubuntu 20.04.5 LTS)

**What happened**:
PCAP downloading from historical flows is not working:

<img width="261" alt="Screenshot 2023-06-20 at 19 03 07" src="https://github.com/ntop/ntopng/assets/38549755/8102bac8-c5bf-40c2-975d-670678074cb8">

<img width="491" alt="Screenshot 2023-06-20 at 19 06 00" src="https://github.com/ntop/ntopng/assets/38549755/d7c0823f-c932-4f87-b6b2-fb58193799e2">

<img width="1383" alt="Screenshot 2023-06-20 at 19 04 38" src="https://github.com/ntop/ntopng/assets/38549755/15688243-2e81-44a6-a11b-03bd9ddcf1f8">

downloaded pcap is 0 byte

**How did you reproduce it?**

**Debug Information**:

**Comment by cardigliano** [comment]
@martinscheu there is an update available, please check it and let us know

**Comment by martinscheu** [comment]
thanks @cardigliano 
I've updated to [ntopng Enterprise L v.5.7.230627] but it doesnt work for me. 
File is still empty. But I noticed something strange:

<img width="836" alt="Screenshot 2023-06-27 at 23 47 18" src="https://github.com/ntop/ntopng/assets/38549755/90c05524-33ac-470c-9f71-57be4e99ab12">

storage utilization is almost nothing. but when I check the log:
`27/Jun/2023 21:40:05 [n2disk.c:2953] Storage /var/lib/ntopng/3/pcap: 297.34 GB in use
27/Jun/2023 21:40:05 [n2disk.c:664] n2disk1g changed user to ntopng
27/Jun/2023 21:40:05 [n2disk.c:5459] [reader] Packet capture started (packet mode)
27/Jun/2023 21:40:05 [n2disk.c:7672] Starting compression thread #1...
27/Jun/2023 21:40:05 [n2disk.c:7672] Starting compression thread #0...
27/Jun/2023 21:40:05 [n2disk.c:4724] Started PF_RING packet reader thread for device ens192
27/Jun/2023 21:40:05 [n2disk.c:4712] Dumping traffic statistics on /proc/net/pf_ring/stats/2570513-ens192.10
27/Jun/2023 21:40:05 [n2disk.c:4704] Using PF_RING v.8.5.0
27/Jun/2023 21:40:05 [n2disk.c:4626] Using packet timestamps from pf_ring
27/Jun/2023 21:40:00 [n2disk.c:7510] Index processing memory is set to 813.08 MB (x 2 x 4 index files)
27/Jun/2023 21:40:00 [n2disk.c:7470] Dump files max duration is set to 60 sec
27/Jun/2023 21:40:00 [n2disk.c:7464] Up to 100 files will be written per folder
27/Jun/2023 21:40:00 [n2disk.c:7446] Storage #0 directory: /var/lib/ntopng/3/pcap
27/Jun/2023 21:40:00 [n2disk.c:7425] Dumping data in 0.1 MB chunks
27/Jun/2023 21:40:00 [n2disk.c:7398] Buffer memory is set to 4.00 GB (x 4 pcap files)
27/Jun/2023 21:40:00 [n2disk.c:7372] Dump files max size is set to 1024.00 MB
27/Jun/2023 21:40:00 [n2disk.c:7323] Storage /var/lib/ntopng/3/pcap limit set to 300.00 GB, total volume size is 490.05 GB
27/Jun/2023 21:40:00 [n2disk.c:7054] Running on 1 node(s) system with 4 core(s). NUMA affinity set to node 0.
27/Jun/2023 21:40:00 [n2disk.c:7014] Welcome to n2disk1g v.3.7.230627 (r5444) [CPU 5065]
Started n2disk ultra-high-speed traffic recorder with realtime indexing on ens192.
License Ok`

**Comment by cardigliano** [comment]
Update:
- this was related to a pre-existing n2disk configuration and has been addressed re-creating the configuration.
- the second instance instead was not able to start due to the RAM n2disk was allocating, addressed with a manual tuning

**Comment by martinscheu** [comment]
I tried on another system with a ntap interface:

`n2disk-ntopng@ntap:35786:ics-lab.service: Failed with result 'exit-code'.
n2disk-ntopng@ntap:35786:ics-lab.service: Main process exited, code=exited, status=1/FAILURE
29/Jun/2023 20:41:37 [n2disk.c:1310] Caught termination signal -1...
29/Jun/2023 20:41:37 [n2disk.c:7651] ERROR: Unable to initialize packet reader
29/Jun/2023 20:41:37 [n2disk.c:4498] ERROR: Unable to open device ntap:35786:ics-lab: ntap:35786:ics-lab: No such file or directory
ntap:35786:ics-lab: not a valid pfring device name
29/Jun/2023 20:41:37 [n2disk.c:4655] ERROR: Has the pf_ring kernel module been loaded? Falling back to libpcap..
29/Jun/2023 20:41:37 [n2disk.c:4653] ERROR: Unable to open PF_RING device ntap:35786:ics-lab: No such file or directory [snaplen=1536]
ntap:35786:ics-lab: not a valid pfring device name
29/Jun/2023 20:41:37 [n2disk.c:4626] Using packet timestamps from pf_ring
29/Jun/2023 20:41:35 [n2disk.c:7510] Index processing memory is set to 203.98 MB (x 2 x 4 index files)
29/Jun/2023 20:41:35 [n2disk.c:7470] Dump files max duration is set to 60 sec
29/Jun/2023 20:41:35 [n2disk.c:7464] Up to 100 files will be written per folder
29/Jun/2023 20:41:35 [n2disk.c:7446] Storage #0 directory: /mnt/n2disk/11/pcap
29/Jun/2023 20:41:35 [n2disk.c:7425] Dumping data in 0.1 MB chunks
29/Jun/2023 20:41:35 [n2disk.c:7398] Buffer memory is set to 1.00 GB (x 4 pcap files)
29/Jun/2023 20:41:35 [n2disk.c:7372] Dump files max size is set to 256.00 MB
29/Jun/2023 20:41:35 [n2disk.c:7323] Storage /mnt/n2disk/11/pcap limit set to 30.00 GB, total volume size is 294.23 GB
Started n2disk ultra-high-speed traffic recorder with realtime indexing on ntap:35786:ics/lab.
29/Jun/2023 20:41:35 [n2disk.c:7054] Running on 1 node(s) system with 8 core(s). NUMA affinity set to node 0.
29/Jun/2023 20:41:35 [n2disk.c:7014] Welcome to n2disk1g v.3.7.230628 (r5444) [CPU F6]
License Ok
Starting n2disk ultra-high-speed traffic recorder with realtime indexing on ntap:35786:ics/lab...
Stopped n2disk ultra-high-speed traffic recorder with realtime indexing on ntap:35786:ics/lab.
n2disk-ntopng@ntap:35786:ics-lab.service: Failed with result 'exit-code'.
n2disk-ntopng@ntap:35786:ics-lab.service: Main process exited, code=exited, status=1/FAILURE
29/Jun/2023 20:41:34 [n2disk.c:7651] ERROR: Unable to initialize packet reader
29/Jun/2023 20:41:34 [n2disk.c:4498] ERROR: Unable to open device ntap:35786:ics-lab: ntap:35786:ics-lab: No such file or directory
ntap:35786:ics-lab: not a valid pfring device name
29/Jun/2023 20:41:34 [n2disk.c:4655] ERROR: Has the pf_ring kernel module been loaded? Falling back to libpcap..
29/Jun/2023 20:41:34 [n2disk.c:4653] ERROR: Unable to open PF_RING device ntap:35786:ics-lab: No such file or directory [snaplen=1536]
ntap:35786:ics-lab: not a valid pfring device name
`

**Comment by cardigliano** [comment]
@martinscheu n2disk does not natively support ntap interfaces at the moment, you should setup the ntap collecor and configure n2disk to capture from the virtual interface created by the collector (see https://www.ntop.org/guides/ntap/usecases.html#remote-tap-sends-traffic-to-non-ntop-applications)
