### ISSUE TITLE
Alerts explorer add data amount column

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#7576]
**What would you like to add or change?**:
Currently it is not possible to show or filter for amount of data exchanged between client and server:

<img width="2391" alt="Screenshot 2023-06-20 at 19 13 22" src="https://github.com/ntop/ntopng/assets/38549755/4f8aacdc-8c34-4dce-96e2-477b2989012c">

Sometimes no data is actually exchanged, when e.g. the firewall is blocking outbound connections.

In order to filter away items without data transmitted, it would be helpful to show amount of data and have a filter for filtering away items without data transferred.

**Why do you and others need this?**:

**Comment by DGabri** [comment]
Implemented as request in pull request
