### ISSUE TITLE
Rework Inactive Host

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7580]
As the table is already pretty large in width, try to reduce its size by
- remove the description in the device type (leave the icon)

In case you have no VLANs remove the VLAN menu
<img width="178" alt="Screenshot 2023-06-22 at 16 51 58" src="https://github.com/ntop/ntopng/assets/4493366/3ac4c726-5ff9-4a42-853d-b81b793a953f">

Add a new drop-down menu with the
- device types (if other than Unknown)
- Hardware manufacturer

Add the ability to download inactive hosts data as a text file (CVS or JSON)

**Comment by lucaderi** [comment]
Implementation is broken. You can select Manufacturer on Hsol to see

**Comment by MatteoBiscosi** [comment]
The issue should be fixed, tested on HSol
![image](https://github.com/ntop/ntopng/assets/49585191/676a6dc4-3fc8-4e4d-8fe9-fb47c6c589fe)

**Comment by lucaderi** [comment]
Mostly working a few glitches
- the implementation is suboptimal so on large networks it is very very slow.
- <img width="514" alt="Screenshot 2023-07-12 at 22 27 09" src="https://github.com/ntop/ntopng/assets/4493366/022c0d2d-d73d-487c-9cf4-83e7063cc9e6">
You have used Others and not Other, you recycle the colour, so avoid using the same color twice

**Comment by MatteoBiscosi** [comment]
Verified as fixed
![image](https://github.com/ntop/ntopng/assets/49585191/c13822fd-06e6-4f6f-b5b0-a9bb409d3245)
