### ISSUE TITLE
n2disk invalid interface

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#7581]
Environment:
CentOS 8 Stream
4.18.0-489.el8.x86_64
amd64
[ntopng Enterprise L v.5.6.230428 (Rocky Linux release 8.7)

What happened:
Ntopng intrefaces configured as --interface="ens192f0,ens192f1,ens192f2,ens192f3".
Traffic recording not working.

![image](https://github.com/ntop/ntopng/assets/67421019/db0f959b-950a-4866-8595-0df8ab2f4e20)

If n2disk started directly as n2disk1g --interface ens192f0,ens192f1,ens192f2,ens192f3 --dump-directory /tmp/1, dumping works.

![image](https://github.com/ntop/ntopng/assets/67421019/3d3d2f3c-2381-4817-9429-bcb6cff2774c)

**Comment by cardigliano** [comment]
Fixed, a new update will be available later today

**Comment by atemix** [comment]
@cardigliano thx for help, fixed

**Comment by atemix** [comment]
@cardigliano 

Updated to ntopng Enterprise L v.5.6.230623 (Rocky Linux release 8.7).
Traffic recording in ntopng shown started, but there are no pcaps on disk. 
And now we cant disable it - nothing happened on save button, after page refresh it's stll enabled.

![image](https://github.com/ntop/ntopng/assets/67421019/06a40274-8e0a-4fe8-979c-0c2bb2217605)


n2disk directly works as expected.

![image](https://github.com/ntop/ntopng/assets/67421019/dff7507c-bb72-4484-af06-f98622ef1cb8)

**Comment by cardigliano** [comment]
@atemix maybe it is better to schedule a call and check this together, please drop an email to cardigliano at ntop.org

**Comment by atemix** [comment]
@cardigliano after full reset of ntopng, traffic recording works, thx for help
