### ISSUE TITLE
Historical flows page is not fully responsive

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7588]
Reducing the window size from
<img width="1401" alt="Screenshot 2023-06-26 at 17 18 13" src="https://github.com/ntop/ntopng/assets/4493366/73cb8bbd-3767-45d8-8f30-48d2bc7169c0">
to
<img width="768" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/c316785f-d4a4-41e6-ac07-bd3ce48d01cb">

reproduces the problem

**Comment by MatteoBiscosi** [comment]
The issue should now be fixed
![image](https://github.com/ntop/ntopng/assets/49585191/5430b168-4b57-43dc-8b33-6cbc1d085565)

**Comment by lucaderi** [comment]
Verified as fixed
