### ISSUE TITLE
Historical Flows: Implement Data Grouping

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7589]
As shown in the picture
<img width="762" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/b7205ad6-f358-4746-a2ba-2efca377a9b3">
- add a drop-down menu (multi-select)
or
- an icon that opens a dialogue

and that lists the fields on which we can aggregate data (GROUP BY)

**Comment by lucaderi** [comment]
For example, I have 100 servers and 1000 client.
Historically,there are many connections between 1 client and 1 server that is exposing an application (IP/PORT). All these connections for me count as only one pair.

Finally, I expect a report/list of 
server a/ port b ----- client c
server a/ port d------ client e
....
server x/port y-------client z

no matter how many times the connection is made (add a count column when grouping)

**Comment by cardigliano** [comment]
- A new custom query "Server Contacts" has been added to list <server, port, client> contacts
- It is possible to use "Conversations" to list <server, client> contacts

What is still missing is:
- the ability to download raw records
- the ability to list *all* contacts as at the moment there is a dropdown for the limit, 100 is the max

**Comment by cardigliano** [comment]
Update:
- raw records can be downloaded now
- the list of all contacts is paginated now in the GUI
- when downloading raw records the full list is returned

**Comment by cardigliano** [comment]
TODO
- fix alignments
- change render function for numbers (display full numbers with ' thousands separator)
- add count column to Conversations

**Comment by cardigliano** [comment]
Alignment, render functions, AS name, raw data download, all fixed.
Added count column to conversation.
Patch set: 0844c780320b1e419b61642dab2d905bc4e55c8f c05afc9c38859c220d55f01482af25d0a480a971 6546d76028fd6876083b68acff30b4fe29dac6d2 (and pro)

**Comment by lucaderi** [comment]
Verified as fixed
