### ISSUE TITLE
searching historical flows with wildcards in hostname.

### ISSUE THREAD

**Issue by njcwotx** [ntop/ntopng#759]
I am on a virus hunt.  I have a case I need to search a historical flow from 12 days ago.  I have some limited info and I think I could find it if I could narrow down my search.

For example:
I got an email from my isp upstream they detected zeus from
Destination IP: 82.x.x.26
destination port: 80

Naturally, getting any more information is unavailable.

Maybe even queries to the mysql database might help, but a couple of examples might help.  If thats possible.  I am trying to get the source IP which ISP cant provde..

**Comment by njcwotx** [comment]
I got my local DBA to give me a hand.  We got a query started  to see if we can find the flow....Ill post what we did if it works

**Comment by lucaderi** [comment]
You need to use -F, dumps flows on a MySQL then use the historical flow search to extract all you are looking for
