### ISSUE TITLE
Inactive Hosts: Glitches

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7590]
There are a few issues
- Local Hosts is a wrong label that also takes a lot of space. Modify "Inactive" to "Inactive Local Hosts" and remove it
- Two charts are empty

<img width="1769" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/bd0a6582-7264-4f4c-abe8-b2af01e143ef">

**Comment by MatteoBiscosi** [comment]
The issue should be fixed, tested on HSol
![image](https://github.com/ntop/ntopng/assets/49585191/09e180a3-38e6-472d-a916-6dcddb94c189)

**Comment by lucaderi** [comment]
Verified as fixed
