### ISSUE TITLE
Inactive Hosts: Missing Feedback

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7591]
<img width="453" alt="Screenshot 2023-06-26 at 19 46 00" src="https://github.com/ntop/ntopng/assets/4493366/78385101-5bd9-43e5-a084-bf6d604fd71a">

When clicking on "Delete Older Than" the system should
- report if the action took place
- how many hosts have been deleted

**Comment by MatteoBiscosi** [comment]
Added feedback when deleting hosts
![image](https://github.com/ntop/ntopng/assets/49585191/891242c4-6de4-437f-9476-17ad57cff2eb)

**Comment by lucaderi** [comment]
Working but the table should have empty lines but not be empty (after delete all)
<img width="1703" alt="Screenshot 2023-07-10 at 21 49 49" src="https://github.com/ntop/ntopng/assets/4493366/3710da9f-c527-47b1-8d8c-bed4185b6ad2">

**Comment by lucaderi** [comment]
Verified as fixed
