### ISSUE TITLE
Missing Alert Documentation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7592]
As new icons have been added to the alerts page, documentation must be updated. Writing a blog page is also desirable

<img width="334" alt="Screenshot 2023-06-26 at 19 53 13" src="https://github.com/ntop/ntopng/assets/4493366/0e86dfb6-06cf-4ec7-b75c-0777441d6bc0">

**Comment by cardigliano** [comment]
Doc updated

**Comment by lucaderi** [comment]
Verified as fixed
