### ISSUE TITLE
Top X Functions Should Not Appear When Custom Queries are Select

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7594]
<img width="1185" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/fa39b4ec-8278-47b0-8d19-eb4c8c0bb25a">

**Comment by NicoMaio** [comment]
Fixed in pro repo by e7dd33f1127274207502e6c364b36a59969e4203

**Comment by lucaderi** [comment]
Verified as fixed
