### ISSUE TITLE
Download Button is Broken: No Action

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7595]
<img width="1257" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/7800b4fd-d11b-4e10-8ca4-ec01c0910bd1">

**Comment by cardigliano** [comment]
Update:
the link has been restored, it is now possible to download records, however there are still 2 open issues:

- filters are not dynamically added to the link (it keeps using those set on page refresh)
- it does not pass "visible_columns" which contains the list of columns to be added to the CSV (the default list is used by the backend now)

**Comment by uccidibuti** [comment]
@cardigliano i have fixed frontend problems. Now it works in page flows but it doesn't works in aggregated flows page. In this case this exception are returned:
```
Received exception from server (version 22.3.2):
Code: 47. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Missing columns: 'NUM_FLOWS' while processing query: 'SELECT toInt32(FIRST_SEEN) AS FIRST_SEEN, toInt32(LAST_SEEN) AS LAST_SEEN, PROTOCOL, L7_PROTO, L7_PROTO_MASTER, SCORE, NUM_FLOWS, ...
```

**Comment by lucaderi** [comment]
Verified as fixed
