### ISSUE TITLE
Local traffic rules - add actual measurement

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#7596]
**What would you like to add or change?**:
First, nice feature added, thank you!
In order to tune the local traffic rules, it would be helpful to have a column showing the last measured value as information in a column similar as in Active Monitoring, with Chart and last 24h

<img width="982" alt="Screenshot 2023-06-28 at 09 40 03" src="https://github.com/ntop/ntopng/assets/38549755/8eaa542f-0dc5-4df2-af73-5ab33ca04986">

**Why do you and others need this?**:

**Comment by NicoMaio** [comment]
Hi @martinscheu
It's possible to indicate the last measurement only for the local traffic rules with the single target (specific IP or Network Interface). In the case of '*' as the target, the Last Measurement column should be empty. Is it ok?

**Comment by martinscheu** [comment]
Hello @NicoMaio 
Yes, it is ok for me. 
Thanks

**Comment by lucaderi** [comment]
Verified as fixed
