### ISSUE TITLE
Change historical flow columns

### ISSUE THREAD

**Issue by MatteoBiscosi** [ntop/ntopng#7598]
Remove the 'Pkts' from the packets column and add the column containing the flow application information
![image](https://github.com/ntop/ntopng/assets/49585191/fe18ff48-f39d-46ed-9aef-edaa91438038)
![image](https://github.com/ntop/ntopng/assets/49585191/c2f00fb1-04e7-4cea-a80a-3c0dad7b4309)

**Comment by MatteoBiscosi** [comment]
Remove the '...' from the info column

**Comment by lucaderi** [comment]
Verified as fixed
