### ISSUE TITLE
The ability to give flow exporters aliases.

### ISSUE THREAD

**Issue by maherkassem** [ntop/ntopng#7599]
**What would you like to add or change?**:
It would be a great feature to be able to apply aliases to flow exporters instead of IP addresses. For networks with a lot of flow exporters sending to ntopng.

**Why do you and others need this?**:

It will make it a lot easier to navigate the software as well as alleviate the need to memorize a lot of IP's and correlate them to devices.

**Comment by MatteoBiscosi** [comment]
The flow exporter alias is now implemented in all ntopng and should be visualized the alias if set
![image](https://github.com/ntop/ntopng/assets/49585191/4c2d3cd4-c0ea-4f52-b48d-c912f55a0f8b)
