### ISSUE TITLE
Alerts Glitches

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7600]
- Copy button on Info does not work
- Info field should open a dialog as with other fields
- With HTTP the Info URL should not start wth https://....
- If selected engaged "Host Alerts", when jumping to flow alerts there is no button selected (all,engaged, or important)

**Comment by MatteoBiscosi** [comment]
Partially fixed

**Comment by MatteoBiscosi** [comment]
All 4 issues should now be fixed

**Comment by lucaderi** [comment]
Verified as fixed
