### ISSUE TITLE
Invalid Latency Format

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7609]
In historical flows 0 latency means that it has not been computed. So in this case the cell must be empty
<img width="516" alt="Screenshot 2023-06-29 at 17 33 37" src="https://github.com/ntop/ntopng/assets/4493366/2bdd89d4-9911-4a05-b885-26b3607e07c2">

**Comment by cardigliano** [comment]
@uccidibuti did you fix this already?

**Comment by lucaderi** [comment]
Verified as fixed
