### ISSUE TITLE
Sorting of small number of hosts does only sorts within that set

### ISSUE THREAD

**Issue by edrozenberg** [ntop/ntopng#761]
ntop 2.2 running within pfSense firewall (haven't checked yet if issue is still there with 2.4).

Went to Host -> Hosts. Only shows 10 hosts by default even though title of page is All Hosts - should at least indicate 1-10 in the title. Clicked to sort by Traffic and it only sorted those 10 rows - misleading the user into thinking that's all there is to see.

Had to click on 200 (then it shows only 150 for some reason). Don't see a way to truly see all hosts or paginate to the next set (next page).

At least sorting should sort within the entire set, so if I have 10 hosts showing, sorting by traffic should show top 10 traffic hosts from the whole set.

**Comment by simonemainardi** [comment]
@edrozenberg that issue has already been sorted out in 2.4. Please, update.
