### ISSUE TITLE
Invalid Alert Host Filter

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7612]
Clicking on a host with VLAN on the alerts page

<img width="249" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/7320db56-dc55-4c1e-8787-50e244ac9e63">

adds a filter without VLAN (i.e. the filter has only the IP but not the VLAN)

<img width="810" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/8b2bb47e-4b41-4167-9073-85aae3d35d2a">

**Comment by cardigliano** [comment]
Fixed in pro 645056ee8e59c1a4ab7d552e33a3088b8ea5b9b0

**Comment by lucaderi** [comment]
Verified as fixed
