### ISSUE TITLE
Invalid VLAN menu in Flow Analysis

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7614]
<img width="1305" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/3a44a61a-ee79-4ea0-a4a9-84133b5360d4">

In this page
1. VLAN are not mapped to a name. Example: "32" -> "32 [office]"
2. VLAN 0 does not exist. Call it Untagged

**Comment by NicoMaio** [comment]
Fixed by 2972703b9740f4ae9bb542eab51188ac3ffd0afc.

**Comment by lucaderi** [comment]
Verified as fixed
