### ISSUE TITLE
ntopng on OPNsense - DNS Mode settings not saved

### ISSUE THREAD

**Issue by GiladHi** [ntop/ntopng#7621]
Hi,

Using the latest version of OPNsense (23.1.11) with the latest build of ntopng (5.7.230703).

When selecting the DMS Mode is Services -> ntopng Enterprise -> Settings:
Change the settings to 'Decode DNS responses and resolve all numeric IPs' (or anything else), The setting doesn't stick when you press 'Save', and goes back to 'none'.

Please advise.

Regards,
Gilad

**Comment by MatteoBiscosi** [comment]
HI @GiladHi could you share a picture of the setting you are talking about?

**Comment by GiladHi** [comment]
> HI @GiladHi could you share a picture of the setting you are talking about?

Sure: 

![image](https://github.com/ntop/ntopng/assets/34942558/acaa23f8-e761-4f3e-ab2d-0179277c7738)
![image](https://github.com/ntop/ntopng/assets/34942558/b3f74cca-ecb0-4328-a041-6699c7f44dc8)
![image](https://github.com/ntop/ntopng/assets/34942558/874a9024-1b73-446c-949c-80993119102e)

**Comment by cardigliano** [comment]
@GiladHi we are checking this, we have been able to reproduce it and it seems the configuration file is created correctly, however the OPNsense plugin engine does not reload the value in the GUI.

**Comment by cardigliano** [comment]
It seems this is an OPNsense bug with the dropdown component, the same issue can be reproduced with the original OPNsense plugin for the community ntopng available at  https://github.com/opnsense/plugins/tree/master/net/ntopng
We suggest to open an issue on that repository.
Anyway please note that the configuration file is saved correctly with the configured dns setting.
