### ISSUE TITLE
Add VLAN name on SNMP Device Interfaces page.

### ISSUE THREAD

**Issue by NicoMaio** [ntop/ntopng#7626]
To format the VLAN column with the VLAN_ID and VLAN_NAME, considering the presence of an alias on a specific interface of a specific SNMP device, you can use the following structure:

VLAN_ID [VLAN_NAME]

**Comment by NicoMaio** [comment]
Implemented in the pro repo by 2e018f3ba0fd21c72530aaf1d2473e715d2f2d3d

**Comment by lucaderi** [comment]
Broken 
HTTP/1.1 302 Found
Server: ntopng 5.7.230712 (x86_64)
Set-Cookie: session=ae5f2a52b2278643c241cf88c2a5c9b9; HttpOnly; path=/; HttpOnly; SameSite=lax
Location: /lua/http_status_code.lua?message=internal_error&referer=192.168.2.64%3A3000%2Flua%2Fpro%2Fenterprise%2Fsnmp_device_stats.lua%3Fvlan%3D0%26host%3D172.30.2.100%26page%3Dinterfaces%26currentPage%3D1%26perPage%3D10%26sortColumn%3Dcolumn_port_vlan%26sortOrder%3Ddesc&error_message=...%2Fntopng%2Fscripts%2Flua%2Fpro%2Fenterprise%2Fsnmp_device_stats.lua%3A303%3A%20attempt%20to%20index%20a%20nil%20value%20%28local%20%27vlan_names%27%29

.../ntopng/scripts/lua/pro/enterprise/snmp_device_stats.lua:303: attempt to index a nil value (local 'vlan_names')

**Comment by NicoMaio** [comment]
Fixed in the pro repo by 702a4e21762478312fbff3547b4e64ccbcaad8c1

**Comment by NicoMaio** [comment]
Verified as fixed.
