### ISSUE TITLE
Some ZMQ RRDs are overweighted

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7627]
The zmq* RRDs are way too big with respect to the other RRDs. It should indicate that they have not been created properly and this needs to be fixed

-rw------- 1 ntopng ntopng 1057000 Apr 24 18:02 15/rrd/zmq_flow_coll_drops.rrd
-rw------- 1 ntopng ntopng 1057000 Apr 24 18:02 15/rrd/zmq_flow_udp_drops.rrd
-rw------- 1 ntopng ntopng 1057000 Apr 24 18:02 15/rrd/zmq_msg_drops.rrd
-rw------- 1 ntopng ntopng 1057000 Apr 24 18:02 15/rrd/zmq_rcvd_flows.rrd
-rw------- 1 ntopng ntopng 1057000 Apr 24 18:02 15/rrd/zmq_rcvd_msgs.rrd

**Comment by cardigliano** [comment]
zmq timeseries have second granularity, written every second together with iface:traffic etc. Thus it seems it is expected to occupy more space than the other.
