### ISSUE TITLE
Various Flow Exporter Chart Bugs

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7629]
1. the chart is empty
2. all the entries in the table have the same label but I believe they should have the interface name of the exporter
<img width="1254" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/a09ac61b-638a-408c-a584-f2cf07c6f5d3">

**Comment by lucaderi** [comment]
From the drop down metrics menu, it is not possible to see the list of interfaces (thing that you can do going back and clicking on the host). Please fix this too

**Comment by MatteoBiscosi** [comment]
Added entries to the dropdown like requested.
Now it's like snmp.
![image](https://github.com/ntop/ntopng/assets/49585191/8325b418-5cce-4577-a509-3abc629d7f36)

**Comment by lucaderi** [comment]
The bottom table is now empty

![image](https://github.com/ntop/ntopng/assets/4493366/eb7ada87-ebf3-4d0f-bf33-45a7ac08a612)

**Comment by MatteoBiscosi** [comment]
The Top Table was never available in that page, added as an enchantment
![image](https://github.com/ntop/ntopng/assets/49585191/90774d02-5dd7-4a4a-bb7d-72e4c3ab78d0)

**Comment by MatteoBiscosi** [comment]
Added the top flow exporter interfaces table.
This table was not present, on the previous versions, added as a feature
![image](https://github.com/ntop/ntopng/assets/49585191/20e95e23-5b06-41eb-8ee8-35e0cada83d0)

**Comment by MatteoBiscosi** [comment]
Added the top table even on the flow exporter interface charts (like for snmp)

**Comment by lucaderi** [comment]
Verified as fixed
