### ISSUE TITLE
after upgrade configuration get lost

### ISSUE THREAD

**Issue by lucadistefano** [ntop/ntopng#763]
after upgrading to latest ntopng all settings (retentions, profiles) are resetted to default

**Comment by simonemainardi** [comment]
ntopng never (ever) touches the settings during upgrades. Did the upgrade involve other packages in the system? Check the system logs. Maybe some other package cleared/reset the redis database. Please check that and report.

Also did you know that you can protect redis access with a password? We have added this feature to ntopng. This will protect unauthorized `redis-cli` accesses.

**Comment by simonemainardi** [comment]
@lucadistefano did you have a chance to investigate on this?

**Comment by lucadistefano** [comment]
redis is installed as dependency of ntopng. only ntopng uses redis. no
updates on redis was performed. 
This is the second time that the settings will be resetted after an
ntopng upgrade.
There is a log where I can check the access on redis?
Is possible that redis was down when ntopng started again after
upgrade?
There is no way to recover the configuration? A tool for import /
export settings just in case?
Thanks,
Luca##SELECTION_END##

**Comment by simonemainardi** [comment]
I would check the logs of your package manager to possibly see if other packages (e.g., a redis update) could have clreared the redis cache that stores ntopng configuration. Again you can check in the whole ntopng sources we never clear the cache.

That said I agree with you: an export button would be useful.

**Comment by lucadistefano** [comment]
Hi simone,
the problem seems to be in redis  since long time ago (the first
occurrence is in July):
    [76350] 30 Sep 13:56:12 \* Server started, Redis version 2.4.10
    [76350] 30 Sep 13:56:12 # WARNING overcommit_memory is set to 0!
    Background save may fail under low memory condition. To fix this
    issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then
    reboot or run the command 'sysctl vm.overcommit_memory=1' for this
    to take effect.
    [76350] 30 Sep 13:56:12 #     Can't handle RDB format version 6

that means when we changed the settings, the changes was stored in
local but not on redis (persistently). Then, when we upgraded ntopng
the settings get lost because we restarted the process.
thanks,
Luca

**Comment by simonemainardi** [comment]
Luca, thanks for reporting the condition that caused the issue.
