### ISSUE TITLE
Host Live Aggregated Flows is Empty

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7633]
<img width="1186" alt="Screenshot 2023-07-05 at 15 10 40" src="https://github.com/ntop/ntopng/assets/4493366/b4dd7a6c-2868-4fad-a946-3347b4f8a713">

**Comment by MatteoBiscosi** [comment]
The issue should now be fixed
![image](https://github.com/ntop/ntopng/assets/49585191/440a994e-6e4c-496b-b5e0-a89221b1f31e)

**Comment by lucaderi** [comment]
Verified as fixed
