### ISSUE TITLE
SNMP Index instead of IfName Reported

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7635]
<img width="1259" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/058c440d-a987-4958-926f-fac07e21e138">

**Comment by MatteoBiscosi** [comment]
Currently, it's impossible to add a mapping for the interfaces, there is no way to differentiate the interface of a device from an interface with the same id of another device (e.g. iface 1 of eno1 or interface 1 of lo).
No parameter is given to the rest and the sources are not differentiated between interfaces of different devices, they only use the iface id.
Please provide a way of differentiating the interfaces in the front-end
![image](https://github.com/ntop/ntopng/assets/49585191/aaf96392-a50b-4977-aaeb-f9f1dfb0490c)
![image](https://github.com/ntop/ntopng/assets/49585191/3ddd5374-8249-41e1-808f-2e7a0601bb1f)

**Comment by lucaderi** [comment]
Verified as fixed
