### ISSUE TITLE
Menu Wrap lines in Safari, Chrome is OK

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7636]
Chrome
<img width="308" alt="Screenshot 2023-07-05 at 22 37 27" src="https://github.com/ntop/ntopng/assets/4493366/a9fe8322-7295-403d-bee0-21db9093c188">

Safari
<img width="625" alt="Screenshot 2023-07-05 at 22 36 38" src="https://github.com/ntop/ntopng/assets/4493366/d3562598-d032-438b-8443-c2090d24fbc0">

**Comment by cardigliano** [comment]
On my mac:

- Safari
<img width="359" alt="Screenshot 2023-10-20 at 15 54 50" src="https://github.com/ntop/ntopng/assets/7548711/85946794-4394-41ab-8eef-d0c455b41745">

- Chrome
<img width="354" alt="Screenshot 2023-10-20 at 15 55 00" src="https://github.com/ntop/ntopng/assets/7548711/88998622-e359-4206-8f99-203512c60858">

**Comment by NicoMaio** [comment]
In my situation, it's the same as what Alfredo mentioned.

**Comment by MatteoBiscosi** [comment]
Verified as fixed, width: 100% property does not works on safari
