### ISSUE TITLE
Merge client and server flows

### ISSUE THREAD

**Issue by BlueHairMinerBoy** [ntop/ntopng#7637]
**Environment**:
* OS name: [e.g. Ubuntu]: Ubuntu
* OS version: [e.g. 18.04] 22.04.1 LTS 
* Architecture: [e.g. amd64] amd64
* ntopng version/revision: [e.g. 5.1.211223]  v.5.4.230113

**What happened**:
I'm getting duplicate flows - one for the upload and one for the download - is there any way to have these show together? It's showing the "client" as the external IP.

**How did you reproduce it?**

**Debug Information**:

![image](https://github.com/ntop/ntopng/assets/76572698/fc111bf5-591f-4178-b5d5-146340f194b4)

**Comment by MatteoBiscosi** [comment]
Hi @BlueHairMinerBoy which are the duplicated flows? In the screenshot you sent, there are 4 different flows (client/server and client port) and they are different from one to an other.
Other than that if u have the possibility (no license or an updated license) i suggest on moving to our latest version cause if there is some problem we cannot fix in the older versions

**Comment by BlueHairMinerBoy** [comment]
Was using the Docker container with :latest instead of :stable, up to date and the issue is fixed. Thanks

**Comment by MatteoBiscosi** [comment]
Alright, great news!
