### ISSUE TITLE
again flow details not shown in historical data

### ISSUE THREAD

**Issue by lucadistefano** [ntop/ntopng#764]
if you query historical data and navigate through 'info' button on flow, the flow details are shown as raw json

![selection_471](https://cloud.githubusercontent.com/assets/1080723/18825869/aab816fa-83ca-11e6-8991-7ceb11bf1b8f.png)
![selection_470](https://cloud.githubusercontent.com/assets/1080723/18825871/acfc8626-83ca-11e6-96d9-d678bb54980f.png)

**Comment by simonemainardi** [comment]
fixed. packages are being rebuilt. thank you.
