### ISSUE TITLE
Sort in Inactive Hosts is Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7642]
Multiple columns are broken (for instance also the manufacturer)
<img width="357" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/c942a9f1-e58c-4706-b975-27597c31b238">

**Comment by lucaderi** [comment]
Still broken
<img width="328" alt="Screenshot 2023-07-10 at 21 14 12" src="https://github.com/ntop/ntopng/assets/4493366/dfd8ed94-6c66-48ef-a221-8c2e1b769824">
<img width="300" alt="Screenshot 2023-07-10 at 21 14 06" src="https://github.com/ntop/ntopng/assets/4493366/ca1f6ccd-a1b4-4f3e-bae4-70d553247210">

**Comment by MatteoBiscosi** [comment]
The issue seems fixed, tested on HSol
![image](https://github.com/ntop/ntopng/assets/49585191/c41c9697-525a-424a-b7a0-8ec379f5bc5f)
![image](https://github.com/ntop/ntopng/assets/49585191/0c3e200f-621b-4364-badc-091c8c9adb84)

**Comment by lucaderi** [comment]
Still broken

![image](https://github.com/ntop/ntopng/assets/4493366/6ca97e94-8c33-40ea-980e-3121cddfa647)

**Comment by MatteoBiscosi** [comment]
The issue should now be fixed properly for each field, tested on hsol too
![image](https://github.com/ntop/ntopng/assets/49585191/092cedff-8778-4ba8-bf18-4cbb3566b6dd)
![image](https://github.com/ntop/ntopng/assets/49585191/27f9783b-0559-4976-9c12-535afd83312b)

**Comment by lucaderi** [comment]
Verified as fixed
