### ISSUE TITLE
Alerts Download is Broken (nothing happens)

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7644]
<img width="1192" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/5e0a1fe7-7995-4e0d-86a7-fc29c36db226">

**Comment by NicoMaio** [comment]
Partially fixed the alert download button by 4eec378afed78e06966be5037b3b33f16966ffe7. 
It's necessary to set the visible columns param.

**Comment by cardigliano** [comment]
This seems to work now, however it is required to pass the list of visible columns in case the user wants to download selected columns as it was in past.
@uccidibuti please address this

**Comment by lucaderi** [comment]
Almost fixed
- clicking on "Active Monitoring" nothing is downloaded but shown inline
All the rest seems to work

**Comment by lucaderi** [comment]
Verified as fixed
