### ISSUE TITLE
Packages for Debian 12 (Bookworm)

### ISSUE THREAD

**Issue by plegrand1** [ntop/ntopng#7651]
Hello,
I would like to install Ntopng on a machine running Debian 12 (Bookworm).
However, I can't find a link to install ntopng for this debian version on : 
https://packages.ntop.org/apt/
or 
https://packages.ntop.org/apt-stable/.
Are there any new packages for debian bookworm?
Thanks for your help.
Pascal

**Comment by cardigliano** [comment]
@plegrand1 we are working on this, packages for Debian 12 will be available soon

**Comment by plegrand1** [comment]
Great !!
Thanks a lot
Pascal

**Comment by lucaderi** [comment]
Initial packages (still to be fully tested) now available at https://packages.ntop.org/apt/bookworm/

**Comment by aadlung** [comment]
Do you need some testers or will you test deeply anyway? ;)
I've just created a clean Debian 12 install VM for testing...
```
root@ntop-test:~# apt install ntopng
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ntopng : Depends: libldap-2.4-2 but it is not installable
          Depends: libssl1.1 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

or with all packages:

```
root@ntop-test:~# apt-get install pfring-dkms nprobe ntopng n2disk cento
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cento : Depends: libbpf0 but it is not installable
 n2disk : Depends: libbpf0 but it is not installable
 nprobe : Depends: libhiredis0.10 but it is not installable
          Depends: libmysqlclient18 but it is not installable
          Depends: libcurl3 but it is not installable
          Depends: libbpf0 but it is not installable
          Depends: libnl1 but it is not installable
          Depends: libzmq3 but it is not installable
 ntopng : Depends: libldap-2.4-2 but it is not installable
          Depends: libssl1.1 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by cardigliano** [comment]
@aadlung we are still testing the packages and setting up the CI, I will update this issue later today.

**Comment by lucaderi** [comment]
Packages are now available at https://packages.ntop.org/apt/bookworm/

**Comment by plegrand1** [comment]
Bonjour et merci pour cet ajout!!
Juste une question, les paquets ne sont disponibles que pour  "nightly builds packages" et pas pour les "stable builds packages" ?

**Comment by cardigliano** [comment]
English please :-) Packages for Debian 12 are available for nightly builds atm

**Comment by plegrand1** [comment]
Oups, sorry, i forgot to use deepl just before 
Hello and thank you for this addition!
Just a question, the packages are only available for "nightly builds packages" and not for "stable builds packages"?

atm ??   At the moment ???

Thanks again
