### ISSUE TITLE
Al tables must have a sorting criteria

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7655]
By default it should be the number of flows ordered desc
<img width="1490" alt="Screenshot 2023-07-11 at 22 15 22" src="https://github.com/ntop/ntopng/assets/4493366/2364fb52-231f-4b7e-a64f-92e9390fdaac">

**Comment by uccidibuti** [comment]
I Add config in tables configuration. For an example see aggregated_live_flows.json
```
     "default_sort": {
        "column_id": "flows",
        "sort": 2
    },
```
Note: to see default visible sort column you need delete for each table the redis key:
redis-cli KEYS "ntopng.columns_config.*"

**Comment by lucaderi** [comment]
Seems to work
