### ISSUE TITLE
Inactive Hosts Labels are Cut

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7657]
<img width="525" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/bf767a1f-4efe-48c3-a2c9-4cce2a29d86c">

**Comment by MatteoBiscosi** [comment]
The issue should now be fixed, the labels were not cut, in the filters the manufacturer short label was used to reduce the amount of width used, in the table insted the full label was used; now both use the full label

**Comment by lucaderi** [comment]
Verified as fixed
