### ISSUE TITLE
Invalid Number of Records Reported 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7658]
The number of network records is wrong as it is computed without any other filter. In this case the number of entries would have been much smaller and the number of entries different

<img width="520" alt="Screenshot 2023-07-11 at 22 20 22" src="https://github.com/ntop/ntopng/assets/4493366/2eadeaf3-f47c-486c-9111-e3530caebf0d">

**Comment by MatteoBiscosi** [comment]
The issue is now fixed.
Added even loading after selecting a filter to reload the dropdown with the updated values, otherwise to see the "new filters", the dropdown had to be closed and reopened.
![image](https://github.com/ntop/ntopng/assets/49585191/56eb41fa-98ad-46df-8bf1-217119b154ec)

**Comment by lucaderi** [comment]
Verified as fixed
