### ISSUE TITLE
Historic data just stopped accumulating

### ISSUE THREAD

**Issue by nate-byrnes** [ntop/ntopng#766]
In short, ntopng, after running for a period of time, stops recording historical data. I can leave it in its present not recording data state for someone to take a look at it if that is useful, but I'd like to get back to recording data soon.

By historic data I am specifically referring to the chart of bandwidth history for any host that is reached by clicking on this icon: 
![shot-2016-09-27_15-33-15](https://cloud.githubusercontent.com/assets/19349744/18888816/edfd0080-84c7-11e6-9cbf-40b7b9873e84.png)

It seems that every host has stopped recording data which would appear in this chart. If I expand the timeperiod covered, I can see older data, But there appears to be no data from the periods indicated below.

Having reported this issue a few times in the past, I'm hoping I've ruled out all prior causes of this issue in this instance. I have confirmed disk space is not low (22G free, ntopng BTW creates some massive logs...).  I've recently identified a pattern via my monitoring of the ntopng process that indicates the issue was taking place. When I start to observe large fluctuations in what my monitoring system records as the maximum user time any of the threads in the ntopng process,I know that the historic data has stopped being written. If I restart ntopng, the data starts being recorded again. Here is a graph of the measurement in question. The yellow highlighted areas indicate the time period when ntopng **is** saving the historic data. 
![shot-2016-09-27_09-59-49](https://cloud.githubusercontent.com/assets/19349744/18877032/e6dc9a46-8499-11e6-87f3-1b7ecc1b0ff4.png)

**Comment by nate-byrnes** [comment]
I am running ntopng Pro [Small Business Edition] v.2.5.160822. Remote access is available under the same credentials last shared with @simonemainardi 

I'm happy to provide more information. Please just let me know what is needed.

Here is the corresponding free space of the filesystem ntopng is writing to over the same timeperiod illustrated above. 

![shot-2016-09-27_10-10-52](https://cloud.githubusercontent.com/assets/19349744/18877303/d67f820c-849a-11e6-922f-8c4fdfa975f8.png)

**Comment by simonemainardi** [comment]
@nate-byrnes first of all I have checked and  v.2.5.160822 may be affected by performance issues that we have recently solved. So first of all I would kindly suggest you to update to the latest version and repeat the monitoring.

In addition I noticed that you are running ntopng on top of KVM. So I think we should make sure that, during the large fluctuation periods shown, there are no other processes that are jeopardizing the cores thus preventing ntopng from executing smoothly.

**Comment by nate-byrnes** [comment]
OK, I'll upgrade. I am not actually running within kvm.... that's just the name of the server. This box was used for some experiments with kvm some time back, but, when I saw the resource needs of ntopng, I gave the whole server to ntop. Someday I'll probably even get around to renaming the server

**Comment by simonemainardi** [comment]
@nate-byrnes I was wondering if you've had a chance to try the latest version... doest data keep stopping to accumulate?

**Comment by nate-byrnes** [comment]
Hi @simonemainardi, https://github.com/simonemainardi

```
 I upgraded to v.2.5.160929 when you suggested to upgrade (I'm just 
```

using apt-get to upgrade via packages.ntop.org). Since the upgrade I 
have not lost any historical data (uptime 7 days so far). However, the 
initial stoppage of historical data recording didn't take place until 
the system was running for 28-29 days. The subsequent stoppage after 
restarting the service was only a matter of hours after restart. The 
observed pattern of the maximum user time consumed by any of the threads 
has changed since the upgrade. It is not as erratic as when the prior 
release I was using stopped recording. I've attached charts the maximum 
user time and maximum system time consumed by any thread recorded once 
every 5 minutes for the past 30 days. As you can see there has been no 
change in the max system time. Clearly the application is doing 
something differently since the upgrade. It looks like the max system 
time is not showing the same upward trend that it was under the prior 
version 2.5.160822.

```
 Regards,
 Nate
```

**Comment by simonemainardi** [comment]
@nate-byrnes I can't see the attachments with the charts

**Comment by nate-byrnes** [comment]
Sorry, seems like the email reply got stripped of them. Here they are

![screenshot_2016-10-06_09-09-49](https://cloud.githubusercontent.com/assets/19349744/19155905/1e074730-8bae-11e6-8ef8-5aff67d6a505.png)
![screenshot_2016-10-06_09-08-23](https://cloud.githubusercontent.com/assets/19349744/19155912/234159e8-8bae-11e6-814b-faad52f3c56d.png)

**Comment by simonemainardi** [comment]
thanks for enclosing the charts, @nate-byrnes 

Please, feel free to close the issue and re-open if necessary. Thanks for submitting all this great deal of information!

**Comment by nate-byrnes** [comment]
Sure thing. Closing, hopefully for good.
