### ISSUE TITLE
Manufacturer column is empty

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7663]
The manufacturer must be moved to the manufacturer column instead of being listed under the device.

![Screenshot 2023-07-12 at 17 59 43](https://github.com/ntop/ntopng/assets/4493366/5115018b-531a-4b36-8cbe-6ba5687cc4df)

Please unify the column layout according to the mac list page (same column names, and order)

<img width="488" alt="Screenshot 2023-07-12 at 18 05 38" src="https://github.com/ntop/ntopng/assets/4493366/aad13cf3-86c2-4656-8a1d-57c84ad75cae">

**Comment by NicoMaio** [comment]
Fixed in pro repo by 72b77e279a9f1aa7a14d3c074fbc0ff6baacb02d

**Comment by lucaderi** [comment]
Fixed but open new issues in #7709
