### ISSUE TITLE
Invalid Date Reported Under Inactive Mac Addresses

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7665]
<img width="1285" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/21cc9993-cf9e-4b63-9b65-9ef5f3aa13e5">

**Comment by MatteoBiscosi** [comment]
The issue should now be fixed

**Comment by lucaderi** [comment]
Unable to reproduce, closing for now. Next time @MatteoBiscosi please reference the commit that fixed it
