### ISSUE TITLE
Inactive MAC Addresses "Older Than" Not Working

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7666]
It seems that the deletion of inactive MAC addresses is on the first seen and not on the last seen as it should

**Comment by MatteoBiscosi** [comment]
This issue should now be fixed

**Comment by lucaderi** [comment]
Still bugged. All entries have been deleted

<img width="1339" alt="Screenshot 2023-08-03 at 12 34 40" src="https://github.com/ntop/ntopng/assets/4493366/87c90a25-f087-4f41-8367-be610f816367">

**Comment by lucaderi** [comment]
Verified as fixed
