### ISSUE TITLE
crash in going flows tab

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#767]
just upgraded to the latest available build and now flows tab is empty (flows_stats.lua)
=> no result found

it seems ntop crashes in going in this tab

**Comment by Niko78** [comment]
got it

...
28/Sep/2016 07:46:00 [CollectorInterface.cpp:111] Collecting flows on tcp://192.168.6.35:5556
[New Thread 0x7fffbeffd700 (LWP 15974)]
[New Thread 0x7fffbe7fc700 (LWP 15975)]

Thread 8 "ntopng" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd77fe700 (LWP 15963)]
lh_char_hash (k=0x0) at linkhash.c:47
47      linkhash.c: Aucun fichier ou dossier de ce type.
...

**Comment by simonemainardi** [comment]
thanks @emanuele-f
