### ISSUE TITLE
Align space between buttons and vertical alignment

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7670]
![image](https://github.com/ntop/ntopng/assets/4493366/454a8c1a-600f-495a-baf3-73476b8acce4)

**Comment by MatteoBiscosi** [comment]
The issue should be fixed
![image](https://github.com/ntop/ntopng/assets/49585191/297c5020-0b9c-4a64-a4c4-206ef45eac3d)

**Comment by lucaderi** [comment]
<img width="950" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/10f36437-1967-48ce-9689-b7aee18cd93d">
Still bugged

**Comment by MatteoBiscosi** [comment]
![image](https://github.com/ntop/ntopng/assets/49585191/e0a4accb-e436-48b3-ba67-a9dbab3afcb9)
fixed in the latest version

**Comment by MatteoBiscosi** [comment]
Verified as fixed
