### ISSUE TITLE
SNMP: Make sure Interface Names are not Shortened 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7671]
![Screenshot 2023-07-12 at 18 59 24](https://github.com/ntop/ntopng/assets/4493366/120e673b-69a7-4855-a4df-8c17a9bf3103)

**Comment by MatteoBiscosi** [comment]
Ports name and aliases no more cut in half, added a - between the device name and the interface name
![image](https://github.com/ntop/ntopng/assets/49585191/ce0c2d02-3ab1-41c7-a629-9e847af9de98)

**Comment by lucaderi** [comment]
Verified as fixed
