### ISSUE TITLE
Aggregated Flows: Enhance VLAN Support

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7673]
Add a VLAN dropdown menu here for selecting only a specific VLAN (this only in case of tagged traffic)
<img width="1601" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/9e77f5d5-80bb-4b65-aaea-ebc8096dc51b">

**Comment by lucaderi** [comment]
<img width="1362" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/bc96bfc2-dacf-47b0-a220-e20dbda8fa24">
Still broken

**Comment by lucaderi** [comment]
<img width="1297" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/33cd052f-bd49-400a-8969-739553b2ec20">

Still no dropdown menu

**Comment by NicoMaio** [comment]
Fixed by 42866af4a94c4c195cf9b42ee2cba7399e578f07

**Comment by MatteoBiscosi** [comment]
Verified as fixed
![image](https://github.com/ntop/ntopng/assets/49585191/2debe90c-0c5e-4402-82d9-ecd6c32ff70f)
