### ISSUE TITLE
Custom Queries dropdown is missing in the Analysis page

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#7677]
The custom queries dropdown is present in the historical flows page:

<img width="640" alt="Screen Shot 2023-07-14 at 12 07 57" src="https://github.com/ntop/ntopng/assets/7548711/eaab7524-5add-4ab2-85f1-3e0ce89b4e62">

but it is missing in the analysis page (it used to be there also):

<img width="543" alt="Screen Shot 2023-07-14 at 12 09 32" src="https://github.com/ntop/ntopng/assets/7548711/31e81816-6cf8-4730-9829-ab9bee934465">

**Comment by NicoMaio** [comment]
@MatteoBiscosi the location of the dropdown must be the same as the "Flows" page.
