### ISSUE TITLE
Empty Host Score Chart

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7678]
Open a host and click on the score icon

<img width="566" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/91808ebf-36ba-449e-8ea8-0c2dd16b730f">

this is what you get

<img width="1083" alt="Screenshot 2023-07-15 at 00 18 00" src="https://github.com/ntop/ntopng/assets/4493366/5e1c7ef3-5a77-40bd-a5d7-85936dd7d8d9">

**Comment by MatteoBiscosi** [comment]
The issue should now be fixed, tested on hsol
![image](https://github.com/ntop/ntopng/assets/49585191/0b0af8be-d4e0-49c1-8fa7-123e248b5ecc)

**Comment by lucaderi** [comment]
Verified as fixed
