### ISSUE TITLE
Improve Alert Explorer user experience

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#7683]
The Unread / Require Attention tab reports alerts that should be handled/acknowledged by the user. In a quiet situation this presents an empty table that means no alerts, however the feeling is that something is not working as an empty table is associated with "there is no data, something is not working". I suggest reporting instead a "green" message like "All good. There is no alert requiring user actions in the selected time frame."

<img width="1217" alt="Screen Shot 2023-07-18 at 14 43 38" src="https://github.com/ntop/ntopng/assets/7548711/0515c2bf-bd35-483f-b0a5-60043f4b9e5d">

**Comment by MatteoBiscosi** [comment]
Implemented as requested
