### ISSUE TITLE
issue while installing

### ISSUE THREAD

**Issue by sirajkrm** [ntop/ntopng#769]
Hi
when i try to install ntop on CentOS 7 (with french language )
this error appears :
[windeco@localhost NtopFiles]$ cd ntopng/
[windeco@localhost ntopng]$ ./autogen.sh 
Wait please...

Now run ./configure
[windeco@localhost ntopng]$ ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes 
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for nDPI... found in ../nDPI
checking for ../nDPI/src/lib/.libs/libndpi.a... found ../nDPI/src/lib/.libs/libndpi.a
checking for ntopng professional edition... not found
Using PF_RING installed in /usr/local/lib
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking libnetfilter_queue/libnetfilter_queue.h usability... yes
checking libnetfilter_queue/libnetfilter_queue.h presence... yes
checking for libnetfilter_queue/libnetfilter_queue.h... yes
checking for nfq_create_queue in -lnetfilter_queue... yes
checking for nfq_set_verdict2... yes
checking for nl_handle_alloc in -lnl... no
checking for clock_gettime in -lrt... yes
checking for dlopen in -ldl... yes
checking for curl_easy_perform in -lcurl... yes
checking for GeoIP_record_by_ipnum in -lGeoIP... yes
checking GeoIP.h usability... yes
checking GeoIP.h presence... yes
checking for GeoIP.h... yes
checking for GeoIP_lib_version in -lGeoIP... yes
checking for sqlite3_open in -lsqlite3... yes
checking for mariadb_config... no
checking for mysql_config... mysql_config
checking for main in -lwrap... yes
which: no clang++ in (/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/windeco/.local/bin:/home/windeco/bin:/usr/local/mysql/bin)
configure: creating ./config.status
config.status: creating packages/ntopng.spec
config.status: creating packages/ntopng-data.spec
config.status: creating Makefile
config.status: WARNING:  'Makefile.in' seems to ignore the --datarootdir setting
config.status: creating doc/doxygen.conf
config.status: creating include/config.h

You are now ready to compile typing /usr/bin/gmake
[windeco@localhost ntopng]$ make
g++ -g -Wall -I/home/windeco/Bureau/NtopFiles/ntopng -I/home/windeco/Bureau/NtopFiles/ntopng/include -I/usr/local/include -D_FILE_OFFSET_BITS=64 -I/usr/include/hiredis   -I/usr/include/hiredis -I/home/windeco/Bureau/NtopFiles/ntopng/third-party/mongoose -I/home/windeco/Bureau/NtopFiles/ntopng/third-party/json-c  -I../nDPI/src/include -I/home/windeco/Bureau/NtopFiles/ntopng/third-party/LuaJIT-2.0.3/src -I/home/windeco/Bureau/NtopFiles/ntopng/third-party/rrdtool-1.4.8/src/ -I/home/windeco/Bureau/NtopFiles/ntopng/third-party/zeromq-4.1.3/include -I/usr/include/mysql  -I/home/windeco/Bureau/NtopFiles/ntopng -I/home/windeco/Bureau/NtopFiles/ntopng/include -I/usr/local/include -I/home/windeco/Bureau/NtopFiles/ntopng/third-party/http-client-c/src/ @SSL_INC@  -DDATA_DIR='"/usr/local/share"' -I/home/windeco/Bureau/NtopFiles/ntopng/third-party/libgeohash -I/home/windeco/Bureau/NtopFiles/ntopng/third-party/patricia   -c src/GenericHashEntry.cpp -o src/GenericHashEntry.o
g++: erreur: @SSL_INC@: Aucun fichier ou dossier de ce type
make: **\* [src/GenericHashEntry.o] Erreur 1
///////////////////////////
any indea for is very welcome
thnx :)

**Comment by simonemainardi** [comment]
it looks like autoconf failed to substitute @SSL_INC@ with the actual include.  Substitution is clearly done here: https://github.com/ntop/ntopng/blob/dev/configure.seed#L441 so please make sure your sources are up-to-date with the dev branch

**Comment by sirajkrm** [comment]
hi 
thank you your response :)
so i should modify the file configure.seed
copy and paste right ?!

**Comment by sirajkrm** [comment]
ok i updated ntop
here's the result :
...
checking for nfq_create_queue in -lnetfilter_queue... no
checking for nfq_set_verdict2... no
checking for ldap_initialize in -lldap... no
checking for nl_handle_alloc in -lnl... no
checking for clock_gettime in -lrt... no
checking for zlibVersion in -lz... no
checking for dlopen in -ldl... no
checking for curl_easy_perform in -lcurl... no
Please install libcurl(-dev) (http://curl.haxx.se/)

Libcurl is missing
but it's not.. i think
[windeco@localhost ntopng]$ rpm -qa | grep libcurl
libcurl-7.29.0-25.el7.centos.x86_64
libcurl-devel-7.29.0-25.el7.centos.x86_64

what now ?!

**Comment by simonemainardi** [comment]
the problem (that occurs only on Centos7) is due to the `-lpfring` in the `LDFLAGS`:

```
checking for curl_easy_perform in -lcurl... no
Please install libcurl(-dev) (http://curl.haxx.se/)
LDFLAGS:  -L/usr/local/lib -lpfring
```

Indeed, if I manually strip `-lpfring` from the LDFLAGS right before the curl check, then the check completes with success.

I guess `-lpfring` should be added to the `LIBS` and not to the `LDFLAGS` as done here: https://github.com/ntop/ntopng/blob/dev/configure.seed#L211

@lucaderi , who takes care of the builds, will look at this when possible

**Comment by sirajkrm** [comment]
so.. should i modify configure.seed (L211) to fix it or what ?

**Comment by sirajkrm** [comment]
i checked configure.seed
LDFLAGS="${LDFLAGS} -lpfring" 
line does existe

**Comment by simonemainardi** [comment]
it doesn't exists because it's generated at runtime. Remove this line https://github.com/ntop/ntopng/blob/dev/configure.seed#L211 and see. If the linking fails, then wait for the fix or submit a pull request with the fix. thank you

**Comment by sirajkrm** [comment]
it did fix it by removing that line
big thank's ^^
but..
i got this now :
(.text+0x2469): référence indéfinie vers « pfring_set_direction »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_setdirection_linux »:
(.text+0x2478): référence indéfinie vers « pfring_set_direction »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_inject_linux »:
(.text+0x255b): référence indéfinie vers « pfring_send »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_set_appl_name_linux »:
(.text+0x58cd): référence indéfinie vers « pfring_set_application_name »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_set_cluster »:
(.text+0x58ef): référence indéfinie vers « pfring_set_cluster »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_get_pfring_id »:
(.text+0x598d): référence indéfinie vers « pfring_get_ring_id »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_set_master_id »:
(.text+0x59a8): référence indéfinie vers « pfring_set_master_id »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_set_master »:
(.text+0x59bf): référence indéfinie vers « pfring_set_master »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_set_application_name »:
(.text+0x59d8): référence indéfinie vers « pfring_set_application_name »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_set_watermark »:
(.text+0x59f0): référence indéfinie vers « pfring_set_poll_watermark »
collect2: erreur: ld a retourné 1 code d'état d'exécution
make: **\* [ntopng] Erreur 1

**Comment by simonemainardi** [comment]
> If the linking fails, then wait for the fix ...

**Comment by sirajkrm** [comment]
ok
@lucaderi any help is very appreciated
@simonemainardi thank's a lot for help

**Comment by lucaderi** [comment]
@sirajkrm I have added a fix. Please try again

**Comment by simonemainardi** [comment]
I can confirm it is working now thank you @lucaderi

**Comment by ssirag** [comment]
I'm having the "Please install libcurl(-dev) (http://curl.haxx.se/)" issue when running the ./configure script for NtopNG install.

I'm running Ubuntu 16.04 and cloned the https://github.com/ntop/ntopng.git repo twice to fix it.

Versions:
Curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Libcurl3 version 7.47.0-1ubuntu2.2

**Comment by delgadod** [comment]
I also am facing this issue on Ubuntu 16.04 as I try to update ntopng
v.2.4.170513 [Professional Edition]
GIT rev:   2.4-stable:00c19bd312019e97f0a1a499382a931d183ff827:20170513
Pro rev:   r643
System Id: 90DC7C979208AB1B
Built on:  Ubuntu 16.04.2 LTS

curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2k zlib/1.2.8

**Comment by simonemainardi** [comment]
@delgadod please list the exact steps you did and the error you received

**Comment by delgadod** [comment]
@simonemainardi 
This was some time ago, but as I remember I used 
sudo apt-get update 
sudo apt-get upgrade
Then proceeded to uninstall ntopng and clone the github repo for the stable version, encountering the error "Please install libcurl(-dev) (http://curl.haxx.se/)" when running ./configure
I uninstalled the stable version (and dependencies) and then installed the dev version from http://packages.ntop.org/apt/ without issue.

**Comment by simonemainardi** [comment]
ok thanks for reporting.  Issue is fixes in dev, indeed.
