### ISSUE TITLE
Wrong filter using Expand action in alert explorer

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#7691]
When filtering rows in a custom query, the Expand action picks the filters from the wrong row:

In this example:
<img width="755" alt="Screen Shot 2023-07-24 at 11 07 42" src="https://github.com/ntop/ntopng/assets/7548711/e67b780b-18ba-4c4b-ad9f-78d80ebada25">

After filtering by "Periodic Flow":

<img width="574" alt="Screen Shot 2023-07-24 at 11 04 35" src="https://github.com/ntop/ntopng/assets/7548711/3b5797ee-b600-4d94-9a6f-23b9f40b30fb">

The Expand action is adding a "Known Proto on Non Std Port" (that was the first raw before filtering) instead of "Periodic Flow":

<img width="869" alt="Screen Shot 2023-07-24 at 11 04 53" src="https://github.com/ntop/ntopng/assets/7548711/a3e02ea4-428e-44ec-9711-455cdd92a8c0">

**Comment by lucaderi** [comment]
Verified as fixed
