### ISSUE TITLE
Errors when moving to off chart data

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7692]
Go to a chart page [http://devele:3000/lua/if_stats.lua?ifid=1&page=historical&epoch_begin=1690189406&epoch_end=1690189580&timeseries_groups_mode=1_chart_x_metric&timeseries_groups=interface%3B1%3Biface%3Athroughput_bps%3Bbps%3Dtrue%3Afalse%3Afalse%3Afalse]

<img width="1384" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/cd5197bb-5d35-4895-b04c-d3a686856736">

then click on the button highlighted that moves the chart to a period of time where there is no data to display. This is what we get
- broken layout
- no metric name was reported

<img width="1365" alt="Screenshot 2023-07-24 at 11 08 54" src="https://github.com/ntop/ntopng/assets/4493366/626cc934-c059-485c-93fa-63dce649ba77">

**Comment by MatteoBiscosi** [comment]
Issue fixed in the latest dev version
