### ISSUE TITLE
Packages for SLES/OpenSUSE

### ISSUE THREAD

**Issue by deadpoint** [ntop/ntopng#7693]
**What would you like to add or change?**:

I'd like to request the addition of packages for the SLES or openSUSE distributions.

**Why do you and others need this?**:

SLES/openSUSE is one of the leading Linux distributions and it would be great to have current packages of ntopng and related packages available. There are "community" packages available from the openSUSE Build Service, but they are old and outdated, ntopng 5.0 and ndpi 4.0, and it would be ideal to have current versions available, especially for anyone considering purchasing a commercial license.

Thanks!

**Comment by NicoMaio** [comment]
This is not a distribution that we use.
We'll consider it in the future.
