### ISSUE TITLE
Can't generate nprobe license 

### ISSUE THREAD

**Issue by lyycotsz** [ntop/ntopng#770]
I was trying to generate license with the link provided but got the following message: nProbe/Cento License Generator - The orderId you have specified is not valid.

I got orderIds for "nProbe Pro with Plugin Support [Linux/Win]" and "ntopng Pro Small Business Linux/Win (x64)". I generated license for ntopng sometime ago for a testing server and now want to add  nprobe but I couldn't generate license. Is that means the order is invalid or the SystemID or version number I put in causing problem?

Thanks
Yu-king

**Comment by simonemainardi** [comment]
- https://shop.ntop.org/mklicense/ for nProbe/cento licenses
- https://shop.ntop.org/mkntopng/ for ntopng licenses
