### ISSUE TITLE
Historical flows: Filtering does not work for hostnames containing spaces or slashes

### ISSUE THREAD

**Issue by psct** [ntop/ntopng#7700]
If a hostname contains spaces or slashes "Add Filter" displays "invalid name" and applying it anyway does not filter at all. Workaround: select "contains" instead of "=" or "=!".  I am using ntopng Enterprise M v.5.6.230720 (Debian GNU/Linux 11 (bullseye))

**Comment by NicoMaio** [comment]
White spaces hostname validation fixed by 1c3fa662ca0052badb8b1849aad870e72509da85

**Comment by lucaderi** [comment]
<img width="808" alt="Screenshot 2023-10-24 at 18 33 29" src="https://github.com/ntop/ntopng/assets/4493366/b311e3f7-d5ec-4973-bf8e-6400b73a99c0">

Not quite. FIx both client and servers. This said hostnames with spaces are not valid.

**Comment by MatteoBiscosi** [comment]
Verified as fixed
