### ISSUE TITLE
Historical flows: excluding IPv6 flows by addresses also clips IPv4 flows and vice versa

### ISSUE THREAD

**Issue by psct** [ntop/ntopng#7701]
I was trying to take a look at historical data and used filters like "Client IP != fd00::...". This leads to SQL where statements like: "((IP_PROTOCOL_VERSION = 6) AND( (IPV6_SRC_ADDR!=IPv6StringToNum('fd00:...'))". Which discards any IPv4 traffic from the flows view. May be there is a better way to filter for IPv4/v6 but excluding an IPv6 address should not clip IPv4 flows at all? The same happens on excluding IPv4 addresses; IPv6 gets clipped.  I am using ntopng Enterprise M v.5.6.230720 (Debian GNU/Linux 11 (bullseye)).

**Comment by cardigliano** [comment]
@psct this has been fixed, a new update will be available shortly, this is the generated query now:

(IP_PROTOCOL_VERSION != 6) OR (IPV6_SRC_ADDR != IPv6StringToNum('fd00:...'))

**Comment by psct** [comment]
Thank you, works now as I expected with ntopng Enterprise M v.5.6.230728.
