### ISSUE TITLE
Vulnerability Scan: Symbolic hosts are not accepted

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7703]
<img width="820" alt="Screenshot 2023-07-28 at 17 00 45" src="https://github.com/ntop/ntopng/assets/4493366/d154d70c-68d5-4f16-a534-5ea2d63ddb7c">

**Comment by NicoMaio** [comment]
Fixed by a93201e42f61acaeaecb78e3915e31e3d6fcd9ec

**Comment by lucaderi** [comment]
Verified as fixed
