### ISSUE TITLE
ntop - Suricata service and host and flow issue

### ISSUE THREAD

**Issue by Alisher-Nabiev** [ntop/ntopng#7705]
hi,

I would to know if we can delete the Suricata process from our server. also, we receiving lately a lot of hosts and flow limits in our server and the CPU is high any suggestions on how to handle this?

**Comment by lucaderi** [comment]
Suricata uses many resources due to the checks it implements. If not required, you can stop Suricata in order to save resources. You can do this safely.

**Comment by Alisher-Nabiev** [comment]
thanks!
