### ISSUE TITLE
Critical alerts are not delivered when setting is set to the minimum severity: critical

### ISSUE THREAD

**Issue by Ernestas-S** [ntop/ntopng#7708]
**Environment**:
* OS name: [Ubuntu]
* OS version: [22.04.2 LTS]
* Architecture: [amd64]
* ntopng version/revision: Enterprise L v.5.6.230727

**What happened**:
When I want to send syslog notifications with the setting for "minimum severity" chosen as "critical" there are no messages delivered. 

**How did you reproduce it?**
when I set the minimum severity to "Notice", it dispatches notifications marked as "Notice", "Error", and "Critical" to chosen syslog system as expected. Similarly, when I set the minimum severity to "Error", Ntopng sends notifications classified as "Error" and "Critical", which also aligns with expectations.

The issue arises when I set the minimum severity to "Critical". In this instance, I do not receive any notifications in chosen syslog system at all. Also, "Notifications>Recipients“ Usage table displays 0% usage for it.

**Comment by MatteoBiscosi** [comment]
The issue should be fixed with the latest ntopng stable version. Consider that currently in ntopng stable, there is only this alert as critical.
![image](https://github.com/ntop/ntopng/assets/49585191/3bb650ce-a0d0-4ad3-8b1e-9214b92f68bd)
