### ISSUE TITLE
Device/MAC Address Tracking Issues

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7709]
1. the status drop-down menu cannot have an empty value
<img width="837" alt="Screenshot 2023-08-03 at 12 26 55" src="https://github.com/ntop/ntopng/assets/4493366/ae3235a7-cb43-4d26-bf02-22c63becb8ca">

2. changing the status from allowed to deny does not change the "Device Status" column or the disconnection alert. The REST is working but on large networks (due to a suboptimal Redis-based implementation) it takes a while (tenth of second) to refresh making it unusable

3. Add a spinner to show that the REST is still taking place
4. Rework the implementation more efficiently

**Comment by NicoMaio** [comment]
This table was migrated by (#7802)

**Comment by lucaderi** [comment]
Still bugged
<img width="831" alt="Screenshot 2023-10-23 at 23 15 13" src="https://github.com/ntop/ntopng/assets/4493366/0c88221c-a240-4102-85fc-5dec67d4b8d5">

**Comment by lucaderi** [comment]
Verified as fixed
