### ISSUE TITLE
[InterfaceStatsHash.cpp:162] WARNING: Internal error: too many devices 48

### ISSUE THREAD

**Issue by m00tpoint** [ntop/ntopng#771]
Have a licensed copy of nprobe receiving sflow data. Device count yesterday was ~196. Running ntopng community edition. Added ~36 additional exporters. Total interface count is probably ~10K. Now receiving the following error every 5 minutes from ntopng: 

[InterfaceStatsHash.cpp:162] WARNING: Internal error: too many devices 48

The GUI seems to be working fine, wondering what the error means, and whether it will impact flow data exports to MySQL from ntopng. 

Commmands used: 
nprobe -n none --zmq tcp://127.0.0.1:1234 --collector-port 6343 &
ntopng -i tcp://127.0.0.1:1234 -F "mysql;127.0.0.1;ntopng;flows;root;myrootpassword" --community &

[prompt]# ntopng -V
v.2.5.160919 [Enterprise/Professional Edition]
GIT rev:   dev:97e9f98c00eb408d4d2234b035823980e14d170b:20160919
Pro rev:   r696
System Id: <redacted>
Built on:  CentOS Linux release 7.2.1511 (Core)

[prompt]# nprobe -v

Welcome to nProbe v.7.5.160919 (r5407) for x86_64-unknown-linux-gnu
with native PF_RING acceleration.
Copyright 2002-16 ntop.org

Build OS:      CentOS Linux release 7.2.1511 (Core)
SystemID:      68B8BF9E76056206
GIT rev:       dev:358d34569137ca0f834666fbd88a12c8379a3844:20160919
Edition:       nProbe Pro
License:       <redacted> [valid license]
License Type:  Permanent License

**Comment by simonemainardi** [comment]
hi, thanks for reporting. The one you reported is just a warning and does to break ntopng. However it shouldn't have been occurred as you are running in community mode.

Please, consider contacting us for an evaluation of the enterprise version of ntopng. In the enterprise version we are able to collect historical statistics for any exporter you have.

**Comment by m00tpoint** [comment]
Thanks for the quick reply! Is the enterprise version different from the Small Business version that demo's for 10 minutes? My primary use case for the flow data is historical analysis rather than live "top talker" type use, which is most of what I see in the ntopng GUI. I'd like to be able to pull flow data based on device, and pull all flows involving a specific subnet, ideally automated reporting. I'm currently using the data with direct CLI queries in scripts directly against the MySQL database.

**Comment by simonemainardi** [comment]
The enterprise version has an additional menu "Netflow Devices" that you can use to inspect and monitor not only the flows but also the devices that are sending them. This monitoring includes historical timeseries as well.
