### ISSUE TITLE
Add column with number of Host Vulnerabilities

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7711]
<img width="1281" alt="Screenshot 2023-08-03 at 14 52 19" src="https://github.com/ntop/ntopng/assets/4493366/942c4097-73ac-40fa-9edd-24948fc89407">

Please use the bug icon (https://fontawesome.com/v5/search?q=bug&o=r) for the column name if possible)

**Comment by NicoMaio** [comment]
The column won't be sortable for now.

**Comment by lucaderi** [comment]
Verified as fixed
