### ISSUE TITLE
Add Host Hyperlink in Report

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7712]
In Vulnerability report
<img width="541" alt="Screenshot 2023-08-03 at 14 55 32" src="https://github.com/ntop/ntopng/assets/4493366/1cea20ad-c925-49bd-8049-1523c8f7a36d">

1. add the host name (after having resolved to numeric IP) to a hyperlink for jumping to the host details
2. in the host page add a button for adding the host to the list of scanned assets (if not already there)
3. in the host page list the identified CVEs. Clicking on one of them jumps to the latest host report

**Comment by lucaderi** [comment]
<img width="590" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/ee87b893-03e6-4d95-8881-6c175ec07383">
Also change the font type to a title font such as 
<img width="256" alt="Screenshot 2023-08-03 at 18 25 02" src="https://github.com/ntop/ntopng/assets/4493366/20fce96a-439a-4d2d-a3ad-0d4f67e80fd9">

**Comment by NicoMaio** [comment]
2. What about a hyperlink "Add Host to Vulnerability Scan List" sending to the hosts' vulnerability scan page and then clicking on + the host is already set?

**Comment by lucaderi** [comment]
Verified as fixed
