### ISSUE TITLE
Invalid badge color

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7716]
<img width="209" alt="Screenshot 2023-08-03 at 15 42 13" src="https://github.com/ntop/ntopng/assets/4493366/4b062999-10de-426a-95cd-468679bd8ea4">

avoid yellow (warning) as a color. use instead primary, secondary and info for scanning, not yet scanned....

https://getbootstrap.com/docs/4.0/components/badge/

**Comment by NicoMaio** [comment]
What about primary for "Not Scanned" status and info for "In Progress" status?

**Comment by lucaderi** [comment]
Verified as fixed
