### ISSUE TITLE
Invalid Vulnerability Host Edit

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7719]
Suppose  you have two hosts as follows

<img width="609" alt="Screenshot 2023-08-03 at 18 32 10" src="https://github.com/ntop/ntopng/assets/4493366/0f079ccb-cf6b-4185-a4fd-fa8a764c9582">

now edit devele as follows and save the data

<img width="1032" alt="Screenshot 2023-08-03 at 18 32 54" src="https://github.com/ntop/ntopng/assets/4493366/5d0e0157-664b-47df-8f3f-479befdc3d70">

After saving the row have been reordered
<img width="1323" alt="Screenshot 2023-08-03 at 18 34 07" src="https://github.com/ntop/ntopng/assets/4493366/a7958d23-cd80-46fc-8a78-190fed9e09f4">

if I now edit 192.168.2.255 the previous devele setting has been applied to this host and not to devele.

I don't know it the bug is caused by row reordering, but I am sure that you it host  A and you also edit host B

**Comment by NicoMaio** [comment]
It should be fixed now. 
Please test again.

**Comment by lucaderi** [comment]
Verified as fixed
