### ISSUE TITLE
Is there anyway to set ntopng to ignore the 802.1Q vlan tag header?

### ISSUE THREAD

**Issue by njcwotx** [ntop/ntopng#772]
I have a setup where we are using port-mirroring on the switch to feed ntopng.  ntopng is working fine, but my switch has an issue where the vendor will acknowledge the problem, but says its not going to fix.  On the port-miror port, its adding an errant 802.1Q vlan tag header on the outbound direction only.  On the actual port itself, there is no tagging, but on the port-mirror port outbound packets are tagged, but inbound packets are not.  Vendor acknowledges the bug, but says its in the asic and cannot be fixed.

Is there a way to tell ntopng to ignore vlan tags?  the ports themselves are in access mode on the switch and are all the same vlan, but when port-mirroring adds the tag, ntopng splits sending and recieving into 2 separate hosts...

192.168.99.99 for recieve
192.168.99.99@10 for send

its not ntopnng's fault, its flagging correct, but the fault lies totally on my crappy core switch that wont get replaced any time soon!

**Comment by simonemainardi** [comment]
it's easy: forcefully set `vlan_id` at zero here:
- https://github.com/ntop/ntopng/blob/dev/src/NetworkInterface.cpp#L1407
- https://github.com/ntop/ntopng/blob/dev/src/NetworkInterface.cpp#L1493

recompile, and you're done.

**Comment by schoerg** [comment]
Thanks for this.
I have the same crappy switch, Nortel 4524GT-PWR.
