### ISSUE TITLE
Implement Menu Disable/Remove

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7720]
Currently it is not possible to disable an entry hence in this case disabled items appear as enabled but no action is performed clicking on them This needs to be fixed
<img width="268" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/ca4287ec-7ab4-4f80-be6a-edb31b8fcd82">

**Comment by lucaderi** [comment]
Apparently disabling a menu item is possible already
<img width="223" alt="Screenshot 2023-08-03 at 18 43 08" src="https://github.com/ntop/ntopng/assets/4493366/71095abf-1ab0-4eb5-b924-c79287fff03f">

**Comment by lucaderi** [comment]
I believe it's still broken
<img width="1103" alt="Screenshot 2023-08-09 at 09 00 23" src="https://github.com/ntop/ntopng/assets/4493366/9f717666-0efd-4610-8f84-f0c179bfcbdd">

**Comment by NicoMaio** [comment]
Fixed by 869981544bf8e78e29199bbcd5eaf48ce6b0269b and c77b1df2f3d13f46e053013107b698eb2e066951

**Comment by lucaderi** [comment]
Verified as fixed
