### ISSUE TITLE
[Dashboard] Chart component

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#7725]
It is required to implement a chart component for that dashboard that should be compatible with the REST APIs we have today for the interface/hosts historical charts and support the same endpoints. The chart should support also live refresh to be used in the live dashboard.

**Comment by cardigliano** [comment]
Chart component has been implemented and it is working fine.

TODO: it would be nice to have the zoom control disabled.

**Comment by MatteoBiscosi** [comment]
Implemented as requested
