### ISSUE TITLE
Unable to stop continuous recording

### ISSUE THREAD

**Issue by psct** [ntop/ntopng#7728]
I can't stop traffic recording on the "Traffic Recording Settings"-page. The "Save Settings"-button stays light blue after pressing it, if I toggle the "Traffic-Recording"-checkbox. There are some closed bugs on this: #6947 and #7491. I am on ntopng Enterprise M v.5.6.230728 (Debian GNU/Linux 11 (bullseye)

**Comment by cardigliano** [comment]
@psct this may be related to the validation, could you try setting 1GB as max disk space and hit save?

**Comment by psct** [comment]
Ah, yes it is. 

So if value "Max Disk Space" exceeds what's available on storage, the button gets disabled and one may not toggle traffic recording.

"Max Disk Space" was prefilled with the storage available when first enabling traffic recording. May be the setting should distinguish user overrides from max space preload?

**Comment by cardigliano** [comment]
Yes, or at least the validation should ignore the disk space setting when disabling the recording.
