### ISSUE TITLE
TCP Packet analysis function is missing/not displayed

### ISSUE THREAD

**Issue by ossgeek** [ntop/ntopng#773]
Hello all
My ntopng instance (2.4.160917 - Pro Small Business Edition) with a valid license is running fine but I'm missing the TCP Packet analysis functions (Retransmissons/Out of Order/Lost). All other details about flows like Traffic sent/received etc. are present. 

My ntopng runs on "CentOS Linux release 7.2.1511 (Core) ] - 64 bit" and the startup line is: ntopng --http-port "3000" --https-port "0" --core-affinity "-1" --local-networks "10.0.0.0/8,172.26.27.0/24,172.26.28.0/24,172.26.30.0/24" --sticky-hosts "none" --data-dir "/storage/ntopng" --pid "/var/tmp/ntopng.pid" --interface "tcp://127.0.0.1:5556" .  nDPI (Ver. 1.8.0-1.8-stable-467-6450ae2) is started and active too. 

As far as I understand the manual it's not necessary to start or configure a special option to get this "Network Health" informations!?  Every hint to get this network infos showed is welcomed. Thanks a lot.

Regards
Attila

**Comment by simonemainardi** [comment]
Attila,

add those guys to the nProbe template and you should be able to get that information in the flow details page:

```
[NFv9 57599][IPFIX 35632.127] %RETRANSMITTED_IN_BYTES           Number of retransmitted TCP flow bytes (src->dst)
[NFv9 57581][IPFIX 35632.109] %RETRANSMITTED_IN_PKTS            Number of retransmitted TCP flow packets (src->dst)
[NFv9 57600][IPFIX 35632.128] %RETRANSMITTED_OUT_BYTES          Number of retransmitted TCP flow bytes (dst->src)
[NFv9 57582][IPFIX 35632.110] %RETRANSMITTED_OUT_PKTS           Number of retransmitted TCP flow packets (dst->src)
[NFv9 57583][IPFIX 35632.111] %OOORDER_IN_PKTS                  Number of out of order TCP flow packets (dst->src)
[NFv9 57584][IPFIX 35632.112] %OOORDER_OUT_PKTS                 Number of out of order TCP flow packets (src->dst)
```

**Comment by ossgeek** [comment]
Hello Simone
Special thanks for your very quick response. I'll try to add such a template to nProbe and sorry for this RTFM-alike question. It seems that I've overseen this crucial part of the Ntop manual  ;-)

**Comment by simonemainardi** [comment]
you will get TCP OOO/lost/retransmits out-of-the-box if you use ntopng to monitor a network interface. If you use that to collect nProbe data, then you have to add those fields to the template.
