### ISSUE TITLE
Unable to Export Historical Flows

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7741]
In historical flows, clocking on the export flow icon the downloaded file is empty and it contains the following line

Code: 62. DB::Exception: Syntax error: failed at position 1 (')'): ). Unmatched parentheses: ). (SYNTAX_ERROR)

**Comment by NicoMaio** [comment]
Fixed in pro repo by ed748600906d453cde0964b08297ada125269ea7

**Comment by lucaderi** [comment]
Verified as fixed
