### ISSUE TITLE
Invalid Alert Detail Page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7742]
In the flow page, take an alert and click on the info button
<img width="920" alt="Screenshot 2023-08-09 at 09 12 19" src="https://github.com/ntop/ntopng/assets/4493366/51467e5f-d1c4-416d-94a2-797473070e3b">

this is what we get 
<img width="813" alt="Screenshot 2023-08-09 at 09 13 13" src="https://github.com/ntop/ntopng/assets/4493366/cadf09b4-2de0-4949-b709-8c0850b19083">

**Comment by cardigliano** [comment]
@martinscheu please check it

**Comment by lucaderi** [comment]
Verified as fixed
