### ISSUE TITLE
Vulnerability Scan: Add Batch Edit

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7744]
In vulnerability assessment, add the ability (similar to delete all) to change the scan periodicity of all entries. This to avoid clicking on individual hosts. This will be implemented adding a new button next to "Delete All"

In the future, we should selectively edit the host properties (not on all)

**Comment by lucaderi** [comment]
<img width="1520" alt="Screenshot 2023-08-11 at 11 14 35" src="https://github.com/ntop/ntopng/assets/4493366/8e58fe28-d37f-4db6-b8c5-4fe87914f45d">
Broken: batch edit set to daily, the table says daily, edit days disabled

**Comment by NicoMaio** [comment]
Fixed by 6fd7aa5ea7261eac5c223ec4bd23ea77b209a4a1

**Comment by lucaderi** [comment]
Verified as fixed
