### ISSUE TITLE
User login not works

### ISSUE THREAD

**Issue by apcastro** [ntop/ntopng#775]
I just installed ntopng with nbox few days ago, and when i enable user login autentication in nbox for ntopng, it seems bugged: the login button doesn't focus and can't login. 

I look at the default password in the phisical machine where the system is installed with the command redis-cli and its ok.

PS: I have a 1 year license, and i wanna ask about SNMP but i dont know how can i do (in contact section, email).

EDIT: My OS is ubuntu server 16.04

**Comment by ssa5** [comment]
I am having the same issue running on Oracle Linux 7.2. Just ran latest updates as of today, v2.4.160928-1308 and still can not login either. I am able to log into another server running v.2.4.160913. But 2 other servers I have tried that were updated more recently all have the same issue. So something between 913 to 928.

Update: Seems this only affects Google Chrome, but the behavior is not see in IE/Edge and as such I am able to login using that browser. But under Chrome, the 2nd character you type in the password field essentially fades out the login

**Comment by alv91** [comment]
Same:
GIT rev:   2.4-stable:98ee891ed1bff3c11be3922a93c03f62619b8d6a:20161004
Built on:  Debian GNU/Linux 7.10 (wheezy)

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36

**Comment by tomlabaude** [comment]
There's a javacript error on Chrome (macOS & Android) as soon as a 2nd character is entered in password form:

> validator.js:83 Pattern attribute value ^[\w\$\!\/()\=\?^*@_-\u0000-\u00ff]{1,}$ is not a valid regular expression: Uncaught SyntaxError: Invalid regular expression: /^[\w\$\!\/()\=\?^*@_-\u0000-\u00ff]{1,}$/: Invalid escape

validator.js:83 points on el.checkValidity()

Looks like the regex pattern used in various Lua scripts is not accepted:
Ex in ntopng/scripts/lua/login.lua:

```
<input type="password" class="form-control" name="password" placeholder="Password" pattern="^[\w\$\\!\/\(\)=\?\^\*@_\-\u0000-\u00ff]{1,}$" required>
</div>
```

**Comment by simonemainardi** [comment]
Can you guys check if the problem occurs with version 2.5? That version contains a fix which can solve the problem: See https://github.com/ntop/ntopng/issues/700  and https://github.com/ntop/ntopng/commit/55d8658046a41dd308f3179bb0068483683a580d

**Comment by alv91** [comment]
I changed adhoc in scripts/lua/login.lua and now after POST moving to http://example.com:3000/lua/login.lua?referer=/authorize.html but not log in.

**Comment by simonemainardi** [comment]
as you can see commit https://github.com/ntop/ntopng/commit/55d8658046a41dd308f3179bb0068483683a580d involves multiple files. You should try version 2.5

**Comment by apcastro** [comment]
@simonemainardi @tomlabaude @alv91 I test it in IE on Windows and chrome in Ubuntu, and the login works. I change the lines in the files explained in https://github.com/ntop/ntopng/commit/55d8658046a41dd308f3179bb0068483683a580d

Now i have my ntopng working perfectly!!

Lot of thanks guys 😄

**Comment by alv91** [comment]
@simonemainardi The problem was with the already added password in database. Now i can log in, thanks.

**Comment by simonemainardi** [comment]
thanks for reporting guys!
