### ISSUE TITLE
No historic graphs rendering - Community 5.7.230811

### ISSUE THREAD

**Issue by scoob8000** [ntop/ntopng#7758]
**Environment**:
* OS name: [OPNSense]
* OS version: [23.1.11_1]
* Architecture: [amd64]
* ntopng version/revision: [e.g. 5.7.230811]

**What happened**:
Was running Opensense plugin version which was a 5.6.x release.   Removed it and installed the repo to install ntopng enterprise, running with community flag.   Also running with influxdb option.   That is working fine, and I can see measurements getting sent over.

Everything is working as expected, but no historic graphs work.    Seems that the menu for them doesn't finish rendering as none of the drop downs are populated.  ie, last 30 minutes, hour, day, etc.    Date picker also using the wrong date format despite being set in settings.

**How did you reproduce it?**

Try viewing any graph.

**Debug Information**:

![image](https://github.com/ntop/ntopng/assets/20466847/553a90b0-b3cb-4695-9ba4-5ba9199afc5a)
![image](https://github.com/ntop/ntopng/assets/20466847/4cb835cf-c147-4dfe-8ad0-0bd0c71a561c)

**Comment by scoob8000** [comment]
Not sure what I did, but Opnsense "updated" the package to 230812, but now the web ui reports that I'm running 5.6.230808.  But my graphs are working again..

**Comment by scoob8000** [comment]
Update today.   Apparently opnsense had reinstalled it's older version overtop of the enterprise version.   I just did a clean reinstall this morning and am on 5.7.230813 and I'm back to none of the interactive graphs working.

**Comment by cardigliano** [comment]
@scoob8000 could you check your browser inspector to see if there is any javascript error or network request failure? Thank you.

**Comment by scoob8000** [comment]
> @scoob8000 could you check your browser inspector to see if there is any javascript error or network request failure? Thank you.

Ahh.  I see this at the end of the console output in firefox under errors:

Hope this helps.    192.168.0.2:3000 is my instance of ntopng

Source map error: Error: request failed with status 404
Resource URL: http://192.168.0.2:3000/dist/third-party.js?1691927649
Source Map URL: third-party.js.map

Also this right after that, this:
Uncaught (in promise) TypeError: n is null                [timeseries-utils.js:515:16](http://192.168.0.2:3000/http_src/utilities/timeseries-utils.js)

Uncaught (in promise) TypeError: e.metadata is undefined     [timeseries-utils.js:252:22](http://192.168.0.2:3000/http_src/utilities/timeseries-utils.js)


[edit]
If I goto that /dist/third-part.js in my browser, it is there and I see the contents of the .js..

**Comment by admtan** [comment]
I am as well. Here is my environment information and console log.

OS name, OS version and Architecture: see below
```
admtan@IntelRabbit6:~$ uname -a; lsb_release -a
Linux IntelRabbit6 5.15.0-1037-intel-iotg #42-Ubuntu SMP Wed Jul 26 14:01:25 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```
ntopng version/revision: see below
```
admtan@IntelRabbit6:~$ ntopng -V
Version:        5.7.230815 [Enterprise/Professional build]
GIT rev:        dev:6dc7c384075322165a039813cf491690e4a60937:20230815
Pro rev:        r6000
Built on:       Ubuntu 22.04.2 LTS
System Id:      LB74E0F0E9206A1D8--UB74E0F0E3D788A72--OL
Platform:       x86_64
Edition:        Community
License Type:   Time-Limited [Empty license file]
Validity:       Until Wed Aug 16 09:13:25 2023
```
![screenshot0](https://github.com/ntop/ntopng/assets/9016499/ed6cb850-cbe1-44ea-b8e4-943e82f4ec6f)
![screenshot1](https://github.com/ntop/ntopng/assets/9016499/8bb897bf-3b68-421b-9e9f-decb0428aebf)

**Comment by MatteoBiscosi** [comment]
hi @scoob8000 the issue should now be fixed, in a couple of hours a new version with the fix should be available, please update and let me know.

**Comment by scoob8000** [comment]
> hi @scoob8000 the issue should now be fixed, in a couple of hours a new version with the fix should be available, please update and let me know.

Looks like it's fixed for me!    Thank you!

Cheers
