### ISSUE TITLE
Exporting/Collecting/Analyzing Netflow with nProbe and ntopng

### ISSUE THREAD

**Issue by 0xFloS** [ntop/ntopng#7759]
Hi everyone,
I am trying to export and collect Netflow Data with nProbe and ntopng.

### Introduction:

I work on a project to collect/export/analyse Netflow Data in a SmartHome. So there are tons of smart devices communicating with different services in the internet or with each other. So it would be interesting to see who is communicating with who. The idea is to export the Netflow Data from the routers interface (where all the smart devices are "connected") to another machine to collect there the data and maybe also analyze them. I found ntopng and i think it would be very useful for this project. 

### My Testsetup:

First i wanted to test the idea so here is my testsetup.
<img width="521" alt="testumgebung_updated" src="https://github.com/ntop/ntopng/assets/128367008/0c86c97e-4ab2-47c3-87e7-160fc06700b4">
The Client is browsing websites and watching for example YouTube videos. So everything from enp0s8 should be exported to the collector (server).

### Questions:

- Do i need nProbe on the router to export the flow and on the collector (server) also nProbe and ntopng?
- Can i use one license for multiple instances of ntopng/nProbe or do i need multiple instances?
- Can ntopng interprete the Netflow Data? I mean if the client is watching videos on YouTube and i export and collect the Netflow, can i then see in ntopng from the Netflow that the client was watching/browsing YouTube?
- Which commands would be useful? I tried a few different commands.

### Versions:
```
ntopng --version
Version:	5.6.230728 [Enterprise/Professional build]
GIT rev:	5.6-stable:9b297ed11e69dfce7be37be79747078c3b7586f0:20230728
Pro rev:	r5565
Built on:	Ubuntu 22.04.2 LTS
System Id:	L397F26BA00870F20--U397F26BA80151250--OL
Platform:	x86_64
Edition:	Enterprise XL (Bundle)
```
```
nprobe --version
Version:       10.2.230728
Build OS:      Ubuntu 22.04.2 LTS
SystemID:      L397F26BA00870F20--U397F26BA80151250--OL
GIT rev:       10.2-stable:135c05cc1891f5c2ce4b3dbfb3382d48673814b6:20230728
Edition:       nProbe Enterprise S [ntopng Enterprise Bundle License
```
Thank you very much!

**Comment by cardigliano** [comment]
Hi @0xFloS,
- if the router is able of exporting Netflow, you do not need nProbe on the router (you can run it on the server running ntopng to interpret Netflow), yes otherwise. Please also note that Netflow does not carry L7 information, in that case ntopng can *guess* the protocol based on ip, port, etc, if you want to fully leverage on nDPI to identify the application protocol and metadata better to run nProbe on the router.
- A single license can run multiple instances of the software as long as they run on the same box.
- ntopng cannot collect Netflow directly, you need nProbe to act as a "proxy" in you router exports Netflow

**Comment by 0xFloS** [comment]
Hi @cardigliano,

Thank you very much for your explanation. Sorry for the late response, i am still trying to figure out which settings and configurations might give me the best output.

## Router
I am running nProbe on my router with the following command:

`sudo nprobe --zmq "tcp://*:5556" -i enp0s8 -n none -T "@NTOPNG@"`

28/Aug/2023 18:28:20 [plugin.c:178] No plugins found in ./plugins
28/Aug/2023 18:28:20 [plugin.c:186] Loading 23 plugins [.so] from /usr/lib/nprobe/plugins
28/Aug/2023 18:28:20 [nprobe.c:5350] Valid nProbe Enterprise S [ntopng Enterprise Bundle License license found
28/Aug/2023 18:28:20 [nprobe.c:6984] WARNING: IMPORTANT
28/Aug/2023 18:28:20 [nprobe.c:6985] WARNING: IMPORTANT --zmq tcp://x.x.x.x:yyyy is deprecated
28/Aug/2023 18:28:20 [nprobe.c:6986] WARNING: IMPORTANT and it has been replaced with
28/Aug/2023 18:28:20 [nprobe.c:6987] WARNING: IMPORTANT --ntopng zmq://x.x.x.x:yyyy
28/Aug/2023 18:28:20 [nprobe.c:6988] WARNING: IMPORTANT Please update your configuration
28/Aug/2023 18:28:20 [nprobe.c:6989] WARNING: IMPORTANT
28/Aug/2023 18:28:20 [nprobe.c:7690] WARNING: The output interfaceId is set to 0: did you forget to use -Q perhaps ?
28/Aug/2023 18:28:20 [nprobe.c:7693] WARNING: The input interfaceId is set to 0: did you forget to use -u perhaps ?
28/Aug/2023 18:28:20 [nprobe.c:7718] Using ZMQ sourceId 522590979
28/Aug/2023 18:28:20 [nprobe.c:7792] Welcome to nProbe v.10.2.230814 for x86_64-pc-linux-gnu with native PF_RING acceleration
28/Aug/2023 18:28:20 [nprobe.c:7814] Enterprise S [ntopng Enterprise Bundle License Edition running on Ubuntu 22.04.2 LTS
28/Aug/2023 18:28:20 [nprobe.c:7815] Current limits [8 ZMQ exporters][8 collector devices]
28/Aug/2023 18:28:20 [nprobe.c:7826] SystemId: L397F26BA00870F20--U397F26BA80151250--OL
28/Aug/2023 18:28:20 [nprobe.c:7919] Sample rate [packet: 1][flow collection/export: 1/1]
28/Aug/2023 18:28:20 [nprobe.c:9948] Using template @NTOPNG@
28/Aug/2023 18:28:20 [nprobe.c:9950] Using NetFlow Packet Payload Len: 1472
28/Aug/2023 18:28:20 [nprobe.c:9835] @NTOPNG@ expanded to " %IN_SRC_MAC %OUT_DST_MAC %INPUT_SNMP %OUTPUT_SNMP %SRC_VLAN %IPV4_SRC_ADDR %IPV4_DST_ADDR %L4_SRC_PORT %L4_DST_PORT %IPV6_SRC_ADDR %IPV6_DST_ADDR %IP_PROTOCOL_VERSION %PROTOCOL %L7_PROTO %L7_CONFIDENCE %IN_BYTES %IN_PKTS %OUT_BYTES %OUT_PKTS %FIRST_SWITCHED %LAST_SWITCHED %CLIENT_TCP_FLAGS %SERVER_TCP_FLAGS %L7_PROTO_RISK %L7_RISK_SCORE %EXPORTER_IPV4_ADDRESS %DIRECTION %SAMPLING_INTERVAL %TOTAL_FLOWS_EXP %NPROBE_IPV4_ADDRESS %CLIENT_NW_LATENCY_MS %SERVER_NW_LATENCY_MS %APPL_LATENCY_MS %TCP_WIN_MAX_IN %TCP_WIN_MAX_OUT %OOORDER_IN_PKTS %OOORDER_OUT_PKTS %RETRANSMITTED_IN_PKTS %RETRANSMITTED_OUT_PKTS %SRC_FRAGMENTS %DST_FRAGMENTS %L7_INFO %DNS_QUERY %DNS_QUERY_TYPE %DNS_RET_CODE %HTTP_URL %HTTP_SITE %HTTP_METHOD %HTTP_RET_CODE %TLS_SERVER_NAME %BITTORRENT_HASH %SRC_TOS %DST_TOS %HTTP_USER_AGENT %L7_RISK_INFO "
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'DNS_QUERY'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'DNS_QUERY_TYPE'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'DNS_RET_CODE'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'HTTP_URL'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'HTTP_SITE'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'HTTP_METHOD'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'HTTP_RET_CODE'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'HTTP_USER_AGENT'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'DNS_QUERY'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'DNS_QUERY_TYPE'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'DNS_RET_CODE'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'HTTP_URL'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'HTTP_SITE'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'HTTP_METHOD'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'HTTP_RET_CODE'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'HTTP_USER_AGENT'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'NPROBE_IPV6_ADDRESS'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'DNS_QUERY'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'DNS_QUERY_TYPE'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'DNS_RET_CODE'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'HTTP_URL'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'HTTP_SITE'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'HTTP_METHOD'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'HTTP_RET_CODE'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'HTTP_USER_AGENT'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'NPROBE_IPV6_ADDRESS'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'DNS_QUERY'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'DNS_QUERY_TYPE'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'DNS_RET_CODE'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'HTTP_URL'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'HTTP_SITE'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'HTTP_METHOD'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'HTTP_RET_CODE'. Discarded.
28/Aug/2023 18:28:20 [template.c:3506] WARNING: Unable to locate template 'HTTP_USER_AGENT'. Discarded.
28/Aug/2023 18:28:20 [plugin.c:1196] 0 plugin(s) enabled
28/Aug/2023 18:28:20 [nprobe.c:10491] Each flow is 326 bytes long
28/Aug/2023 18:28:20 [nprobe.c:10492] The # flows per packet has been set to 3
28/Aug/2023 18:28:20 [nprobe.c:10495] IP TOS is ignored
28/Aug/2023 18:28:20 [nprobe.c:11293] Flow export type (-T): bidirectional flows
28/Aug/2023 18:28:20 [nprobe.c:11501] Flows ASs will not be computed (no GeoDB files loaded with --as-list)
28/Aug/2023 18:28:20 [nprobe.c:11533] Flows will be exported in NetFlow 9 format
28/Aug/2023 18:28:20 [nprobe.c:11576] Learning the public IP address.. Disable it with --disable-startup-checks
28/Aug/2023 18:28:21 [util.c:6303] Initializing ZMQ as server
28/Aug/2023 18:28:21 [util.c:6382] Successfully created ZMQ endpoint tcp://*:5556 with sourceId: 522590979
28/Aug/2023 18:28:21 [pf_ring.c:435] Initializing PF_RING socket on device enp0s8.. (promisc)
28/Aug/2023 18:28:21 [nprobe.c:8875] Initializing pcap socket on device enp0s8 (promisc)
28/Aug/2023 18:28:21 [nprobe.c:11753] Capturing packets from interface enp0s8 [snaplen: 1600 bytes]
28/Aug/2023 18:28:21 [util.c:5198] nProbe changed user to 'nprobe'
28/Aug/2023 18:28:21 [export.c:479] Using TLV as serialization format
28/Aug/2023 18:28:21 [nprobe.c:12046] nProbe started successfully

## Collector
And on my server (collector) i run ntopng with the parameter specified in /etc/ntopng/ntopng.conf:
`-i=zmq://192.168.2.2:5556`

## Questions
Why do i get the Warnings: Unable to locate template ... ?

### Guess and DPI

So i am using the commands above and then i get in ntopng some flows which i generated with the client (internet surfing)
As you mentioned some are guesses and some are DPI.

<img width="125" alt="Guess_DPI" src="https://github.com/ntop/ntopng/assets/128367008/918ade4f-3441-4ed2-97e7-43d91da581be">

Could you again please explain what the tag "Guess" and what the tag "DPI" is.

### nProbe with ntopng

I also can investigate the flows in see the following information:

<img width="1540" alt="nprobe_ntopng_pic1" src="https://github.com/ntop/ntopng/assets/128367008/f1ec78d4-eda9-4ae2-ba1b-938302885ad8">

but i would like to see some more infomrations like this:

<img width="1551" alt="tcpdump_ntopng" src="https://github.com/ntop/ntopng/assets/128367008/7c142798-16f9-4ab1-9e27-d7ba1b465c1c">

TLS-Version, TLS ALPN, Supported TLS Protocols, ASN number etc.
To get this i used tcpdump and then i uploaded the pcap file to ntopng to analyze it.
Can i also get this information with nProbe and ntopng? I know that i can get this informations if i run ntopng on the router.

Thank you!

**Comment by lucaderi** [comment]
The plugin license issue reported has now been fixed
