### ISSUE TITLE
stuck in installation

### ISSUE THREAD

**Issue by sirajkrm** [ntop/ntopng#776]
hi..
i'm still stuck while installing ntopng 2.5-dev
i'm running CentOS 7 64bit (french lang) on vSphere 5.5
while installing this error appears :

/home/windeco/Bureau/topFiles/ntopng/src/ZCCollectorInterface.cpp:47: référence indéfinie vers « pfring_zc_ipc_attach_queue »
/home/windeco/Bureau/topFiles/ntopng/src/ZCCollectorInterface.cpp:52: référence indéfinie vers « pfring_zc_ipc_attach_buffer_pool »
/home/windeco/Bureau/topFiles/ntopng/src/ZCCollectorInterface.cpp:57: référence indéfinie vers « pfring_zc_get_packet_handle_from_pool »
src/ZCCollectorInterface.o: dans la fonction « ZCCollectorInterface::~ZCCollectorInterface() »:
/home/windeco/Bureau/topFiles/ntopng/src/ZCCollectorInterface.cpp:66: référence indéfinie vers « pfring_zc_sync_queue »
/home/windeco/Bureau/topFiles/ntopng/src/ZCCollectorInterface.cpp:67: référence indéfinie vers « pfring_zc_release_packet_handle_to_pool »
/home/windeco/Bureau/topFiles/ntopng/src/ZCCollectorInterface.cpp:68: référence indéfinie vers « pfring_zc_ipc_detach_queue »
/home/windeco/Bureau/topFiles/ntopng/src/ZCCollectorInterface.cpp:69: référence indéfinie vers « pfring_zc_ipc_detach_buffer_pool »
src/ZCCollectorInterface.o: dans la fonction « ZCCollectorInterface::collect_flows() »:
/home/windeco/Bureau/topFiles/ntopng/src/ZCCollectorInterface.cpp:86: référence indéfinie vers « pfring_zc_recv_pkt »
/home/windeco/Bureau/topFiles/ntopng/src/ZCCollectorInterface.cpp:89: référence indéfinie vers « pfring_zc_pkt_buff_data »
/home/windeco/Bureau/topFiles/ntopng/src/ZCCollectorInterface.cpp:104: référence indéfinie vers « pfring_zc_sync_queue »
src/ZCCollectorInterface.o: dans la fonction « ZCCollectorInterface::shutdown() »:
/home/windeco/Bureau/topFiles/ntopng/src/ZCCollectorInterface.cpp:134: référence indéfinie vers « pfring_zc_queue_breakloop »
src/PF_RINGInterface.o: dans la fonction « PF_RINGInterface::PF_RINGInterface(char const_) »:
/home/windeco/Bureau/topFiles/ntopng/src/PF_RINGInterface.cpp:47: référence indéfinie vers « pfring_open »
/home/windeco/Bureau/topFiles/ntopng/src/PF_RINGInterface.cpp:52: référence indéfinie vers « pfring_version »
/home/windeco/Bureau/topFiles/ntopng/src/PF_RINGInterface.cpp:60: référence indéfinie vers « pfring_set_direction »
/home/windeco/Bureau/topFiles/ntopng/src/PF_RINGInterface.cpp:61: référence indéfinie vers « pfring_set_poll_watermark »
/home/windeco/Bureau/topFiles/ntopng/src/PF_RINGInterface.cpp:62: référence indéfinie vers « pfring_set_application_name »
/home/windeco/Bureau/topFiles/ntopng/src/PF_RINGInterface.cpp:70: référence indéfinie vers « pfring_set_direction »
src/PF_RINGInterface.o: dans la fonction « PF_RINGInterface::~PF_RINGInterface() »:
/home/windeco/Bureau/topFiles/ntopng/src/PF_RINGInterface.cpp:80: référence indéfinie vers « pfring_close »
src/PF_RINGInterface.o: dans la fonction « packetPollLoop »:
/home/windeco/Bureau/topFiles/ntopng/src/PF_RINGInterface.cpp:91: référence indéfinie vers « pfring_enable_ring »
/home/windeco/Bureau/topFiles/ntopng/src/PF_RINGInterface.cpp:96: référence indéfinie vers « pfring_is_pkt_available »
/home/windeco/Bureau/topFiles/ntopng/src/PF_RINGInterface.cpp:100: référence indéfinie vers « pfring_recv »
src/PF_RINGInterface.o: dans la fonction « PF_RINGInterface::shutdown() »:
/home/windeco/Bureau/topFiles/ntopng/src/PF_RINGInterface.cpp:143: référence indéfinie vers « pfring_breakloop »
src/PF_RINGInterface.o: dans la fonction « PF_RINGInterface::getNumDroppedPackets() »:
/home/windeco/Bureau/topFiles/ntopng/src/PF_RINGInterface.cpp:153: référence indéfinie vers « pfring_stats »
src/PF_RINGInterface.o: dans la fonction « PF_RINGInterface::set_packet_filter(char_) »:
/home/windeco/Bureau/topFiles/ntopng/src/PF_RINGInterface.cpp:167: référence indéfinie vers « pfring_set_bpf_filter »
/usr/local/lib/libpcap.a(pcap.o): dans la fonction « pcap_breakloop »:
(.text+0x744): référence indéfinie vers « pfring_breakloop »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_read_packet »:
(.text+0x33c): référence indéfinie vers « pfring_recv »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_stats_linux »:
(.text+0x1103): référence indéfinie vers « pfring_stats »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_cleanup_linux »:
(.text+0x1261): référence indéfinie vers « pfring_close »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_activate_linux »:
(.text+0x2f0a): référence indéfinie vers « pfring_enable_ring »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_activate_linux »:
(.text+0x2f16): référence indéfinie vers « pfring_get_selectable_fd »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_activate_linux »:
(.text+0x3061): référence indéfinie vers « pfring_open »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_activate_linux »:
(.text+0x3093): référence indéfinie vers « pfring_set_socket_mode »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_activate_linux »:
(.text+0x3138): référence indéfinie vers « pfring_set_poll_watermark »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_activate_linux »:
(.text+0x37f8): référence indéfinie vers « pfring_enable_rss_rehash »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_activate_linux »:
(.text+0x3bec): référence indéfinie vers « pfring_set_application_name »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_activate_linux »:
(.text+0x3c25): référence indéfinie vers « pfring_set_cluster »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_activate_linux »:
(.text+0x44c1): référence indéfinie vers « pfring_set_cluster »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_activate_linux »:
(.text+0x4626): référence indéfinie vers « pfring_set_cluster »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_activate_linux »:
(.text+0x47fa): référence indéfinie vers « pfring_set_cluster »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_activate_linux »:
(.text+0x4832): référence indéfinie vers « pfring_set_cluster »
/usr/local/lib/libpcap.a(pcap-linux.o):(.text+0x484f): encore plus de références indéfinies suivent vers « pfring_set_cluster »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_setfilter_linux_common »:
(.text+0x48fc): référence indéfinie vers « pfring_set_bpf_filter »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_setfilter_linux_common »:
(.text+0x4a93): référence indéfinie vers « pfring_get_bound_device_ifindex »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_setdirection_linux »:
(.text+0x2749): référence indéfinie vers « pfring_set_direction »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_setdirection_linux »:
(.text+0x2758): référence indéfinie vers « pfring_set_direction »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_inject_linux »:
(.text+0x283b): référence indéfinie vers « pfring_send »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_set_appl_name_linux »:
(.text+0x5c2d): référence indéfinie vers « pfring_set_application_name »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_set_cluster »:
(.text+0x5c4f): référence indéfinie vers « pfring_set_cluster »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_get_pfring_id »:
(.text+0x5ced): référence indéfinie vers « pfring_get_ring_id »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_set_master_id »:
(.text+0x5d08): référence indéfinie vers « pfring_set_master_id »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_set_master »:
(.text+0x5d1f): référence indéfinie vers « pfring_set_master »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_set_application_name »:
(.text+0x5d38): référence indéfinie vers « pfring_set_application_name »
/usr/local/lib/libpcap.a(pcap-linux.o): dans la fonction « pcap_set_watermark »:
(.text+0x5d50): référence indéfinie vers « pfring_set_poll_watermark »
collect2: erreur: ld a retourné 1 code d'état d'exécution
make: **\* [ntopng] Erreur 1

any idea to fix it is very appreciated
thank's in advance.

**Comment by simonemainardi** [comment]
duplicate of #769
