### ISSUE TITLE
slack.lua:65: attempt to index a nil value

### ISSUE THREAD

**Issue by walteroa2023** [ntop/ntopng#7764]
**Environment**: Docker
* OS name: Alpine
* OS version: 3.18
* Architecture: amd64
* ntopng version/revision: 4.3.201202 (12382)  - Community Edition

**What happened**: error on logs due to slack connection

**How did you reproduce it?**
simply taking look at logs: 
17/Aug/2023 22:37:22 [LuaEngine.cpp:571] WARNING Script failure [/usr/share/ntopng/scripts/callbacks/system/notifications.lua][/var/lib/ntopng/plugins0/alert_endpoints/slack.lua:65: attempt to index a nil value (local 'settings')]
[4.3.201202 (12382)](https://github.com/ntop/ntopng/commit/973e38587b6d1dfeeef8e635dc328bb29f8e6ca9)  - Community Edition

**Comment by lucaderi** [comment]
This is an old version, please move to 5.7

**Comment by walteroa2023** [comment]
Cool. but im getting the image from docker hub, using this image: ntop/ntopng

How can I get updated from current to 5.7 using docker? should I tag stable to get it?
