### ISSUE TITLE
influx DB 1.x driver seems not being installed. 

### ISSUE THREAD

**Issue by walteroa2023** [ntop/ntopng#7765]
**Environment**: Docker image /latest
* OS name: Alpine
* OS version: 3.18
* Architecture: amd64
* ntopng version/revision: 4.3.201202 (12382) - Community Edition

**What happened**:
Cannot enable influxDB. When I look at health status, influx DB 1.x driver seems not being installed. 
I'm running the latest image of ntopng in a docker container... 
Verified. There is no directory influxdb under /etc/   neither influxdb.conf inside the container ...  

**How did you reproduce it?**
Looking at system menu.

**Comment by lucaderi** [comment]
You need to install influx first, then go to preferences and set enabled it
