### ISSUE TITLE
Adding Host to Vulnerability Scan Fails

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7769]
Howto reproduce it
- Go to a local host and open the host details
- Go to the end of the page and click on "Add Host to Vulnerability Scan List"
- The host is added to the list but the table is not refreshed hence the user believes that the action failed

**Comment by lucaderi** [comment]
Still broken

**Comment by NicoMaio** [comment]
Fixed by 459ec1d7265633467a2f8566453778da88ccb203

**Comment by lucaderi** [comment]
Verified as fixed
