### ISSUE TITLE
reload hosts from mysql flow dump on startup

### ISSUE THREAD

**Issue by alext234** [ntop/ntopng#777]
I am running **ntopng** (built from source following the instruction) on my laptop and able to use the **-F** option to dump flows to MySQL database.

Now after running for a while a stop **ntopng** and then run again. Right then I am interested to explore the historical flow of a particular host but it is not on yet the '**All hosts'**. I know this host is already stored in MySQL database but how do I make **ntopng** retrieve this host information?

**Comment by simonemainardi** [comment]
use flag `-S` to make local hosts sticky. That way ntopng will dump/restore local hosts on shutdown/startup.

**Comment by alext234** [comment]
I have segmentation fault with the following syntax. I did not happen before trying the -S option

_sudo ./ntopng -d /media/u/ntopngdata --user u -F "mysql;localhost;ntopng;flows;root;u" -S remote -D all_

**Comment by alext234** [comment]
Anyway, i tried the 2.4-stable branch with -S option and realize this still does not solve the issue (i.e. persistent storage of host information). It seems someone else encountered this issue before:

http://lists.ntop.org/pipermail/ntop/2015-March/018355.html

Is this the intended restriction for community/opensource version?

**Comment by simonemainardi** [comment]
@alext234 correct, the feature comes in in version 2.5. Please follow up in the other issue we are trying to solve the crash.
