### ISSUE TITLE
Invalid Link

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7771]
<img width="834" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/d922e187-a2e8-4ec1-9f8c-d03e403b1766">
clicking on the above link triggers
<img width="1161" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/160ade29-bbca-48aa-835d-5b0606ed286d">

**Comment by NicoMaio** [comment]
Fixed by #7770 disabling link for remote hosts.

**Comment by lucaderi** [comment]
Sorry this is wrong. You need to disable the link on the protocol *also* when there are no timeseries generated for this host (e.g. due to preferences setup)

**Comment by lucaderi** [comment]
Verified as fixed
