### ISSUE TITLE
Add a table to the doc with the alerts available per license

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7773]
On Ubuntu 22.04 LTS with packages ntopng, the vulnerability scan works as expected. Unfortunately, it is not possible to enable the behavioural check that is present on other hosts.

<img width="1602" alt="Screenshot 2023-08-18 at 19 48 42" src="https://github.com/ntop/ntopng/assets/4493366/2ff70fb8-4596-4b57-b1bb-95c3c4083314">

On the above host this is the network configuration
<img width="213" alt="Screenshot 2023-08-18 at 19 50 15" src="https://github.com/ntop/ntopng/assets/4493366/c1e650a3-ed33-4006-84f5-eeb884a576a7">

**Comment by MatteoBiscosi** [comment]
The issue is with the license, this alert was available only with the XL license. Now moved to the L one.

**Comment by lucaderi** [comment]
Verified as fixed
