### ISSUE TITLE
Alerts explorer add total bytes of flow

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#7776]
**What would you like to add or change?**:
Hello ntop team!
When analyzing Alerts with the Alerts Explorer, it would be helpful to have the total amount of bytes flown by the flow of the alert in the overview table.

Thanks
**Why do you and others need this?**:

**Comment by NicoMaio** [comment]
Hi @martinscheu,
It's possible to jump to the filtered historical flows page from the entry of the alert. Is it ok?

**Comment by MatteoBiscosi** [comment]
Added as requested
![image](https://github.com/ntop/ntopng/assets/49585191/85712cb5-d9f6-469b-a1db-392ae15de390)
