### ISSUE TITLE
Snapshots shows nothing with the "Traffic Profile"

### ISSUE THREAD

**Issue by Yoshihiro-jp** [ntop/ntopng#7777]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04.6 LTS (Focal Fossa)
* Architecture:  x86_64
* ntopng version/revision: 5.6.230814

**What happened**:
As attached file the snapshot shows nothing when I put the "Traffic Profile" graphs.

**How did you reproduce it?**
You just add the graph of the "Traffic Profile" then take the snapshot and save it.
When you try to open that you can't see any graphs like attached file.

**Debug Information**:
Attached files.
![000](https://github.com/ntop/ntopng/assets/58843707/231eccaa-e736-467c-9364-b62ef7b6011c)
![001](https://github.com/ntop/ntopng/assets/58843707/1ba4908e-d951-48dc-983f-020924b359f5)
![002](https://github.com/ntop/ntopng/assets/58843707/cd9a1ceb-025d-4d95-9053-17a921eb315e)

**Comment by oronkessel1** [comment]
same issue here since upgrade its not showing anything ....

**Comment by MatteoBiscosi** [comment]
Hi @Yoshihiro-jp, @oronkessel1 I'm totally unable to reproduce the issue, so I need your help, I need the output of 
journalctl -e -u ntopng 
the web console (right click on the page -> inspect -> console)
![image](https://github.com/ntop/ntopng/assets/49585191/37f9bddf-fc02-46b7-8afd-496c297c9ca6)

**Comment by oronkessel1** [comment]
I can’t do it but I can give you access to my top on web and SSH if needed 

I do see this when I do inspect:

![Screenshot 2023-08-23 at 6 58 07 PM](https://github.com/ntop/ntopng/assets/74092942/7fe36d7a-3553-4607-bf1a-50859ffc936e)

￼
Oron Kessel

￼
Dominican Republic | Telephone: +1829.470.1486 | Office: +1.809.571.1033

**Comment by Yoshihiro-jp** [comment]
Dear @MatteoBiscosi ,

Thank you for your reply.
Attached files are why you mentioned.

![errorprofile](https://github.com/ntop/ntopng/assets/58843707/7b06143f-68f1-4803-88e2-f117046d0df7)
[jn1.log](https://github.com/ntop/ntopng/files/12426944/jn1.log)

regards,
Yoshihiro

**Comment by oronkessel1** [comment]
here is my log file:

[ntoperror.log](https://github.com/ntop/ntopng/files/12428239/ntoperror.log)

**Comment by MatteoBiscosi** [comment]
Hi @Yoshihiro-jp sorry but i was unable to reproduce the issue, so I need your help to know if the fix i pushed is correct or not. In a couple of hours a new build should be available, please update and let me know

**Comment by MatteoBiscosi** [comment]
@oronkessel1 yours instead is a different issue, i have to understand which is the source of your fail if you are able to give me ssh and web access that would be great. Please contact me by email (biscosi at ntop.org)

**Comment by Yoshihiro-jp** [comment]
> Hi @Yoshihiro-jp sorry but i was unable to reproduce the issue, so I need your help to know if the fix i pushed is correct or not. In a couple of hours a new build should be available, please update and let me know

Dear @MatteoBiscosi ,

$ sudo ntopng -V
Version:        5.6.230825 [Enterprise/Professional build]
GIT rev:        5.6-stable:ba6e7556697641d97f1e6b557b5cd4b48a4f806b:20230825

As attached file it already has been fixed!!!
Thank you for your work. I really appriciate!

![20230829jtc](https://github.com/ntop/ntopng/assets/58843707/00859abd-0578-4e68-889a-2a57b99cc3ee)
