### ISSUE TITLE
[Alpine Linux] SQLiteAlertStore.cpp:161 ERROR: SQL Error: (null)

### ISSUE THREAD

**Issue by walteroa2023** [ntop/ntopng#7778]
**Environment**: Docker
* OS name: Alpine
* OS version: 3.18
* Architecture: amd64
* ntopng version/revision: ntopng Community v.5.7.230817 rev.21321 (Ubuntu 22.04.2 LTS)
* **updated to latest edge version today**: Community v.5.7.230920

**What happened**:
21/Aug/2023 12:31:02 [SQLiteAlertStore.cpp:161] ERROR: SQL Error: (null)
INSERT INTO flow_alerts (alert_id, alert_status, alert_category, interface_id, tstamp, tstamp_end, severity, ip_version, cli_ip, srv_ip, cli_port, srv_port, vlan_id, is_cli_attacker, is_cli_victim, is_srv_attacker, is_srv_victim, proto, l7_proto, l7_master_proto, l7_cat, cli_name, srv_name, cli_country, srv_country, cli_blacklisted, srv_blacklisted, cli_location, srv_location, cli2srv_bytes, srv2cli_bytes, cli2srv_pkts, srv2cli_pkts, first_seen, community_id, score, flow_risk_bitmap, alerts_map, cli_host_pool_id, srv_host_pool_id, cli_network, srv_network, probe_ip, input_snmp, output_snmp, json, info) VALUES (26, 1, 3, 0, 1692621000, 1692621061, 3, 4, '10.0.0.253', '8.8.8.8', 0, 0, 0, 0, 0, 0, 0, 1, 81, 0, 14, '', '', '', 'US', 0, 0, 1, 0, 167, 0, 1, 0, 1692621000, '1:2A0n/NM4rKy2Ax1nYIqxtyqgArI=', 10, 70368744177664, X'04000000', 0, 0, 1, 65535, '0.0.0.0', 0, 0, '{"ntopng.key":605080548,"hash_entry_id":1489,"alert_generation": "script_key":"ndpi_unidirectional_traffic","subdir":"flow","flow_risk_info":"{\"46\":\"No server to client traffic\"}"},"proto": {"icmp": {"type":3,"code":3},"confidence":1},"traffic_stats": {}}', ''); 

**How did you reproduce it?**
log entries with several error lines

**Debug Information**:
atacched screenshoot from portainer log viewer.
![ERROR SQL Error (null)](https://github.com/ntop/ntopng/assets/142554546/c2e7555b-581b-4ba7-b468-0fdf0b337e31)

**Comment by cardigliano** [comment]
It seems there is some issue with sqlite and we cannot reproduce this atm, unfortunately Alpine is not one of the distributions we officially support, not sure if it depends on that.

**Comment by walteroa2023** [comment]
> It seems there is some issue with sqlite and we cannot reproduce this atm, unfortunately Alpine is not one of the distributions we officially support, not sure if it depends on that.

Thx Alfredo!!!
I'm running other apps with sqlite with no issue. So, seems to be a ntopng fail from the container itself. Is there any way to capture deeper logs to see where is coming from? Please guide me to obtain the verbose logs... waiting your indications...
Cheers, Walter

**Comment by walteroa2023** [comment]
any update on this @cardigliano or anybody else in the team? Logs are getting huge!

**Comment by cardigliano** [comment]
@walteroa2023 we will take a look at this asap, the team is sorting out higher priority issues at the moment (this is Community on an unsupported OS)

**Comment by lucaderi** [comment]
We are unable to reproduce this error with the containers we distribute at packages.ntop.org
