### ISSUE TITLE
"Traffic Profile" stop showing after upgrade... last upgrade didn't help also....

### ISSUE THREAD

**Issue by oronkessel1** [ntop/ntopng#7779]
Environment:
CentOS Linux release 7.9.2009 (Core) [x86_64] - 64 bit

ntopng version/revision: ntopng Enterprise L v.5.6.230814 rev.21295 (CentOS Linux release 7.9.2009 (Core)) |
What happened:

ntop stop showing my custom profiles traffic after latest upgrade

How did you reproduce it?

upgrade

Debug Information:
still not showing the graphs and also in the time dropdown I see only 30 min doesn't show the rest
all was working before the upgrade
I see graphs in the DASHBOARD but not under the interface -> trafficprofiles

**Comment by oronkessel1** [comment]
<img width="1367" alt="Screenshot 2023-08-21 at 10 13 35 PM" src="https://github.com/ntop/ntopng/assets/74092942/20c48cc9-4ead-4301-be5f-fb78138f4a7d">





<img width="978" alt="Screenshot 2023-08-21 at 10 13 13 PM" src="https://github.com/ntop/ntopng/assets/74092942/89a96547-9796-4dbf-9a8b-e6c1b2d07d78">







<img width="1066" alt="Screenshot 2023-08-21 at 10 13 02 PM" src="https://github.com/ntop/ntopng/assets/74092942/968d8f61-24f9-476b-a017-380cf64f2ff8">





<img width="1116" alt="Screenshot 2023-08-21 at 10 12 52 PM" src="https://github.com/ntop/ntopng/assets/74092942/6cc10613-aaf9-42a4-9d44-4212ddabd6ee">

**Comment by MatteoBiscosi** [comment]
Issue fixed, followed by email.
