### ISSUE TITLE
Table Reload Changes Size

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7786]
Reloading the table the column sizes are also modified

**Comment by lucaderi** [comment]
<img width="1286" alt="Screenshot 2023-09-21 at 12 07 04" src="https://github.com/ntop/ntopng/assets/4493366/774da8ea-eeb2-4afe-a623-80abf93161d7">

now I change page (click on home icon) and back. and this is what I get
<img width="1288" alt="Screenshot 2023-09-21 at 12 07 33" src="https://github.com/ntop/ntopng/assets/4493366/0e93c962-fdf3-4987-806b-7cb69719ad82">

**Comment by uccidibuti** [comment]
This wasn't a table problem! The problem was that there were 2 columns with the same column id and then resizing one of them columns broke the table dimension.

**Comment by lucaderi** [comment]
Verified as fixed
