### ISSUE TITLE
ERROR: MySQL error: [Commands out of sync; you can't run this command now][2014]

### ISSUE THREAD

**Issue by dbvan** [ntop/ntopng#779]
I detect some error when dump flow on ntop-ng to mariadb. Please see log bellow:
07/Oct/2016 15:30:01 ERROR: MySQL error: [Commands out of sync; you can't run this command now][2014] 
08/Oct/2016 13:09:37 ERROR: MySQL error: [Commands out of sync; you can't run this command now][2014] 
09/Oct/2016 07:00:00 Attempting to connect to MySQL for interface eth1... 
09/Oct/2016 07:00:00 ERROR: MySQL error:  
09/Oct/2016 07:00:00 ERROR: INSERT INTO `flowsv4` (VLAN_ID,L7_PROTO,IP_SRC_ADDR,L4_SRC_PORT,IP_DST_ADDR,L4_DST_PORT,PROTOCOL,IN_BYTES,OUT_BYTES,PACKETS,FIRST_SWITCHED,LAST_SWITCHED,INFO,JSON,NTOPNG_INSTANCE_NAME,INTERFACE_ID,PROFILE) VALUES ('0','5','1884160454','34131','1884160258','53','17','87','87','2','1475971196','1475971196','149.120.99.116.in-addr.arpa',COMPRESS('{ "8": "112.78.1.198", "12": "112.78.1.2", "7": 34131, "11": 53, "4": 17, "57590": 5, "57591": "DNS", "2": 1, "1": 87, "24": 1, "23": 87, "22": 1475971196, "21": 1475971196, "SRC_IP_COUNTRY": "VN", "SRC_IP_LOCATION": [ 106.133301, 9.916700 ], "DST_IP_COUNTRY": "VN", "DST_IP_LOCATION": [ 106.133301, 9.916700 ], "NTOPNG_INSTANCE_NAME": "ntop", "INTERFACE": "eth1", "DNS_QUERY": "149.120.99.116.in-addr.arpa", "PASS_VERDICT": true }'), 'ntop', '0','')

**Comment by simonemainardi** [comment]
can you please make sure you are using the latest dev version of ntopng? please report back. Also note that mariadb is not officially supported.

**Comment by dbvan** [comment]
@simonemainardi : I'm using ntop version 2.4.160928 - Community Edition on Ubuntu 14.04.5 LTS.

**Comment by simonemainardi** [comment]
you should try with version 2.5.x as we have added some fixes there

**Comment by simonemainardi** [comment]
@BaVanDuong any news?

**Comment by dbvan** [comment]
@simonemainardi : I upgrade ntopng to version 2.5 and it working.

**Comment by simonemainardi** [comment]
thanks for reporting
