### ISSUE TITLE
Top Countries in the drop down list of Historical Flows

### ISSUE THREAD

**Issue by joonasak** [ntop/ntopng#7798]
**What would you like to add or change?**:
I would like to request a Top Countries in the drop down list of Historical Flows. It would be nice to see it in there too.
![telegram-cloud-photo-size-5-6260157182200886517-x](https://github.com/ntop/ntopng/assets/85352105/d39db09d-d2fb-453f-b902-c2ae4dc31db2)

**Why do you and others need this?**:
We can analyze about which countries access our internal server or our website. So we can do statistic and improve performance of our platform to reach more for those countries.

**Comment by cardigliano** [comment]
Top Receiver and Sender Countries are already available in latest dev, and will be available in the next stable release end of summer

<img width="376" alt="Screen Shot 2023-08-28 at 10 37 03" src="https://github.com/ntop/ntopng/assets/7548711/b7164353-6663-401c-a8fd-577c117cc0f1">
