### ISSUE TITLE
Last seen time is not always populated correctly for flows in Historical interface.

### ISSUE THREAD

**Issue by VittGam** [ntop/ntopng#78]
For example, many flows have "01/01/1970 01:00:05 [45 years, 200 days, 7 h, 22 min, 16 sec ago]" as Last Seen, with the time ranging from 01:00:00 and 01:00:something.

**Comment by lucaderi** [comment]
The historical interface will be reworked anyway. let's leave it open for the time being.

**Comment by lucaderi** [comment]
We're rewriting the historical interface. Please follow issue #61
