### ISSUE TITLE
Recently Active Flows No Results Found

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [ntop/ntopng#780]
On the web interface, right bottom says 1000+ flows, but when I click on it, recently active flows page says "No Results Found"

IPFIX from EdgeOS 1.9.0, nprobe and ntopng on the same host

**Comment by simonemainardi** [comment]
hi, please post ntopng and nprobe version and configuration used

**Comment by jkldgoefgkljefogeg** [comment]
- ntopng    2.4.161004-1709
- nprobe    7.4.161004-5333

nprobe
`-i none -n none -3 64001 --zmq tcp://127.0.0.1:2001 -V 10`

ntopng

```
-G=/var/run/ntopng.pid
--daemon
--interface=tcp://127.0.0.1:2001
--http-port=3000
--local-networks="10.25.0.0/24"
--dns-mode=1
--data-dir=/var/tmp/ntopng
--disable-autologout
--community
```

Occasionally flows works. There is always about 1000 flows shown in the bottom right counter.

**Comment by simonemainardi** [comment]
please do a small capture of localhost port 2001 and enclose the pcap. I want to see the traffic that is flowing between the ntopng and nprobe. It is supposed to be plain json with certain fields. Thank you.

If you can't attach the pcap publicly, send it to mainardi at ntop dot org. Thank you.

**Comment by jkldgoefgkljefogeg** [comment]
I looked at the actual IPFIX udp packets and they are correctly formatted. Given other features can list the port number/IP the flow collector is working correctly. It looks like issue with flows_stats.lua. Sometimes I click it like 3 times and it starts working....

**Comment by simonemainardi** [comment]
traffic that flows between the nProbe and the ntopng is not IPFIX and I wanted to see that traffic. However, before continuing the investigation, can you please try and use the dev versions of nProbe and ntopng? They are 7.5.x and 2.5.x respectively.

**Comment by emanuele-f** [comment]
@jkldgoefgkljefogeg any news?

**Comment by lucaderi** [comment]
Closed for inactivity. Will reopen if necessary.
