### ISSUE TITLE
SNMP counter values only increasing 

### ISSUE THREAD

**Issue by oliwirth** [ntop/ntopng#7801]
**Environment**:
* OS name: Debian
* OS version: bullseye
* Architecture: amd64
* ntopng version/revision: 5.7.230830 and 5.6.230829

**What happened**:
Via SNMP a Cisco 9500 is asked from ntop for its statistic values.
On one Interface I get some `In Errors`. If I clear the statistics in the Cisco (clear counters) ntop does not clear the value for `In Errors`.
If new `In Errors` arrive on the Interface it looks like ntop summs it up to the existing value and is not taking the new, actual value.

In shorts words: ntop does not take the value to show bu calculates istself.

**How did you reproduce it?**
If I clear the counters on the router again ntop does not clear its counters.

**Comment by lucaderi** [comment]
Did you check if from SNMP the value is cleared or only from the command line? I believe that the culprit is there

**Comment by oliwirth** [comment]
Hi, I checked from the GUI for SNMP in ntop after doing `clear counters` on the switch.
If you give me the CLI command I learn something....

**Comment by MatteoBiscosi** [comment]
Hi @oliwirth could you share a couple of screenshots? from where do you clear the counters, in which page?

**Comment by oliwirth** [comment]
Hi Matteo, I'm not clearing counters in ntop, I don't know how to do that...
See interface `TwentyFiveGigE1/0/3`:
![grafik](https://github.com/ntop/ntopng/assets/47536446/fb86b166-2275-4b15-839f-1038ff04ae24)
I clear directly in the commandline of the switch:
![grafik](https://github.com/ntop/ntopng/assets/47536446/8662571a-2652-469b-b4d0-f9664c8d59fc)

See I cleared 2 days ago and got new 2,3 mio `input errors` but ntop tells me 4,8 mio...

**Comment by oliwirth** [comment]
So ntop seems not to take the value it gets from the switch, but is adding it on top of the previous value...

**Comment by oliwirth** [comment]
Maybe I get you point:
iso.3.6.1.2.1.2.2.1.14.5 = Counter32: 4815694

I found this article: https://community.cisco.com/t5/routing/capturing-interface-errors-with-snmp/td-p/438891
And it seems `clear counters` does not clear the counters for snmp questioned values!
Is that what Luca was asking for?

**Comment by lucaderi** [comment]
yes that is the culprit: clearing counters is a CLI-only command, but not via SNMP. Closing for now.
