### ISSUE TITLE
Debian 12

### ISSUE THREAD

**Issue by Clashplayer** [ntop/ntopng#7803]
**What would you like to add or change?**:

Currently on the documentation there is only Debian 11 (Bullseye) should add Debian 12 (BookWorm)
Especially since you have applied a change today !

**Why do you and others need this?**:
Because I use debian 12

**Comment by Clashplayer** [comment]
After checking apt-stable does not have debian 12

**Comment by cardigliano** [comment]
@Clashplayer-PROTECT debian 12 is supported by dev packages only at the moment, we will release stable packages on the next stable release (soon)
