### ISSUE TITLE
Missing sort on IP Address

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7805]
<img width="532" alt="Screenshot 2023-09-04 at 08 53 32" src="https://github.com/ntop/ntopng/assets/4493366/891f4d6d-4325-4d47-8131-23e09a0f1540">

**Comment by NicoMaio** [comment]
Fixed by 999cac65f67f93c4d44eba76e012fce3c9729627

**Comment by lucaderi** [comment]
Verified as fixed
