### ISSUE TITLE
Traffict Dashboard is may broken.

### ISSUE THREAD

**Issue by admtan** [ntop/ntopng#7809]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
```
admtan@IntelRabbit6:~$ uname -a; lsb_release -a
Linux IntelRabbit6 5.15.0-1038-intel-iotg #43-Ubuntu SMP Wed Aug 16 21:04:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```
* ntopng version/revision: [e.g. 5.1.211223]
```
admtan@IntelRabbit6:~$ ntopng -V
Version:        5.7.230906 [Enterprise/Professional build]
GIT rev:        dev:cd4367c1c409e567106ba33b584920f008dabc67:20230906
Pro rev:        r6059
Built on:       Ubuntu 22.04.3 LTS
System Id:      <hidden>
Platform:       x86_64
Edition:        Community
License Type:   Time-Limited [Empty license file]
Validity:       Until Wed Sep  6 19:14:12 2023
```
**What happened**:
The Traffic Dashboard is empty displayed.

**How did you reproduce it?**
After the Daily Update, I opened Dashboard as usual.

**Debug Information**:
See screenshots.
![06e6aaac-ea17-4914-b5b3-ada6a1c4f9e1](https://github.com/ntop/ntopng/assets/9016499/fa2e8ece-96b3-4b81-b308-6565cbdb3a33)
![dd434515-8760-44c4-b9c8-adaed1f9cffb](https://github.com/ntop/ntopng/assets/9016499/2d06989b-0eed-4e45-8195-a13e70f9d5f9)

**Comment by AxelF07** [comment]
Hello,
Same issue here with an ntopng installed today on Debian 12 (ESXI 8).
Traffic Dashboard worked fine when ntopng what on professional demo, but once the demo expired, and became community, dashboard was empty.

![image](https://github.com/ntop/ntopng/assets/7081641/ff577050-963b-4658-90ef-313ce3dba189)

**Comment by cardigliano** [comment]
A fix has been pushed, a package update should be available shortly (within 1h from now)

**Comment by admtan** [comment]
![image](https://github.com/ntop/ntopng/assets/9016499/8dd4a7fb-949b-4ecd-9929-38d3204fcaaf)
Fix verified! Thank you your work. New Looks is nice.
