### ISSUE TITLE
bogon IP to ASN mapping

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [ntop/ntopng#781]
RFC1918 address 172.16.0.0/16 is counted in AS14138. And 70%+ of IPv4 address in my case are in AS 0.

**Comment by simonemainardi** [comment]
No mention to AS14138 and/or its association to `172.16.0.0/16` is given in RFC1918 (https://tools.ietf.org/html/rfc1918)

Also I am not sure why the private range `172.16.0.0/16` should be counted with "Orange County Public Schools" autonomous system number AS14138 (https://whois.arin.net/rest/asn/AS14138)

**Comment by jkldgoefgkljefogeg** [comment]
I am saying it should not. But as_stats.lua does list 172.16.0.0/16 as hosts for AS14138.

**Comment by simonemainardi** [comment]
I have just checked that on a 2.5 ntopng (ubuntu 14.4) we have deployed in a datacenter with private network `172.16.0.0/16` configured. Autonomous system associated to that private network is ASN0 as it should be

![image](https://cloud.githubusercontent.com/assets/3397663/19264293/67ff5558-8fa0-11e6-90b5-d875b79d3d6c.png)

![image](https://cloud.githubusercontent.com/assets/3397663/19264362/c24bd5ea-8fa0-11e6-8c2e-dfe71375f749.png)

![image](https://cloud.githubusercontent.com/assets/3397663/19264552/75f55b70-8fa1-11e6-8786-72c549bfb6e3.png)

Therefore, as suggested in #780, I would recommend trying with the dev versions of ntopng and nProbe.

**Comment by emanuele-f** [comment]
@jkldgoefgkljefogeg please update package ntopng-data that contains new mappings

**Comment by simonemainardi** [comment]
issue is now resolved. new `ntopng-data` packages with updated information have been released.
