### ISSUE TITLE
Raspberry Pi builds not being updated

### ISSUE THREAD

**Issue by dpkano** [ntop/ntopng#7813]
**Environment**:
* OS name: [Raspberry OS (Debian)]
* OS version: [bulleye]
* Architecture: [arm64]
* ntopng version/revision: [5.7.230709]

**What happened**:
My ntopng seems to be stuck with 5.7.230709 on a Git rev: dev:b56a0ef5be5adc1dc9fe244a89e0214ae9d96fb0:20230709
I'm following the "Raspberry Raspbian Instructions". Is there any cadence for the raspberry pi (arm64) builds?

**How did you reproduce it?**
Follow the "Raspberry Raspbian Instructions" on a Rpi4 (arm64) and check the version. It won't be the latest dev version.

**Debug Information**:

**Comment by lucaderi** [comment]
We're on it

**Comment by MatteoBiscosi** [comment]
Raspberry builds are updated every weekend (on Sunday night), but we are working on having a daily update like for the other builds.
