### ISSUE TITLE
Permanent license removed after update the OS

### ISSUE THREAD

**Issue by infinitynet2011** [ntop/ntopng#7814]
Hello!

I ran an OS update (software update)  no hardware replacement and my license is gone, Is normal?
I don't want to pay 524.96 Euro (after the discount)  just because I hit "yum update".

Thanks,
Gabe

**Comment by cardigliano** [comment]
@gvoitis please drop an email to cardigliano at ntop.org with your order ID and the output of ntopng -V

**Comment by infinitynet2011** [comment]
Hello!

I just did, thank you.

**Comment by cardigliano** [comment]
@gvoitis sorry I did not receive your email yet, what is your address?

**Comment by infinitynet2011** [comment]
voitis at infinitytelecom.ro

**Comment by cardigliano** [comment]
Maintenance was expired (talking by mail)

**Comment by gvoitis** [comment]
Hello,

As I mentioned in the email.

I bought a "**Enterprise permanent license**" which was removed automatically and replaced with a **community** license, 

What is the point of buying a license if you aren't allowed to keep it after the maintenance expires?

I need help finding the old versions of ntopng to allow me to replace this new version (community license).

Does that make sense to you?



Thanks,
Gabe
