### ISSUE TITLE
Missing Number Formatters

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7816]
1. New dashboard
<img width="418" alt="Screenshot 2023-09-07 at 21 37 58" src="https://github.com/ntop/ntopng/assets/4493366/605839be-1c10-4ee2-981b-744493c43fcc">

2. Periodicity table
<img width="149" alt="Screenshot 2023-09-07 at 22 51 58" src="https://github.com/ntop/ntopng/assets/4493366/a566c171-3665-44ca-8e5b-22c851e55152">

**Comment by cardigliano** [comment]
1. dashboard has been fixed

**Comment by MatteoBiscosi** [comment]
Fixes, pro repo

**Comment by lucaderi** [comment]
Verified as fixed
