### ISSUE TITLE
VS Invalid TCP Port Sort

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7818]
<img width="1010" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/c67d1a0c-f4b1-4f1c-9ec8-5fdcb5ae6c74">

**Comment by NicoMaio** [comment]
Fixed by be833efbd1375cd607a9cb4964db2b83cd40086b

**Comment by lucaderi** [comment]
Verified as fixed
