### ISSUE TITLE
Unable to Show Hosts Alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7822]
There are errors on the console

http://dell:3000/lua/http_status_code.lua?message=internal_error&referer=dell%3A3000%2Flua%2Frest%2Fv2%2Fget%2Fhost%2Falert%2Flist.lua%3Fstart%3D0%26length%3D10%26map_search%3D%26visible_columns%3Dactions%252Ctstamp%252Cscore%252Calert_category%252Cmsg%252Cip%252Cdescription%252Chost_pool_id%252Cnetwork%26page%3Dhost%26epoch_begin%3D1694758104%26epoch_end%3D1694759904%26status%3Dengaged%26i&error_message=table%20index%20is%20nil

<img width="1532" alt="Screenshot 2023-09-15 at 08 40 17" src="https://github.com/ntop/ntopng/assets/4493366/cb868a38-afba-4451-ad2c-ee4427f0e91f">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
