### ISSUE TITLE
Live Flows View may be broken

### ISSUE THREAD

**Issue by admtan** [ntop/ntopng#7824]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]
```
admtan@IntelRabbit6:~$ uname -a; lsb_release -a; ntopng -V
Linux IntelRabbit6 5.15.0-1038-intel-iotg #43-Ubuntu SMP Wed Aug 16 21:04:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
Version:        5.7.230915 [Enterprise/Professional build]
GIT rev:        dev:24e80bc6b95248d799d5eb899a6136bad1231320:20230915
Pro rev:        r6071
Built on:       Ubuntu 22.04.3 LTS
System Id:      <hidden>
Platform:       x86_64
Edition:        Community
License Type:   Time-Limited [Empty license file]
Validity:       Until Fri Sep 15 19:00:51 2023
```

**What happened**:
As shown in the screenshot, nothing is displayed on the Live Flow page.
![702f8aa6-0757-47aa-8690-ada627ec78b2](https://github.com/ntop/ntopng/assets/9016499/5a2fd402-f90b-48de-b4e1-ee3ddfd768bc)

**How did you reproduce it?**
The issue occurred after applying the usual updates and opening the page.

**Debug Information**:
The only information I can provide is the screenshot. Nothing was displayed in the console.
![592b0f50-db05-40ad-8f81-ada467efe07d](https://github.com/ntop/ntopng/assets/9016499/3f249624-83e4-41ab-929a-98b81240a3f6)

**Comment by lucaderi** [comment]
Fixed by https://github.com/ntop/ntopng/commit/a834e3b5cb6f9cb7ec353c3086774c02448fe0f4

New packages are being build and will be available within one hour. THanks for reporting it

**Comment by admtan** [comment]
Thank you for the quick fix! Looking forward to the update.
