### ISSUE TITLE
Installation Failure: In case you see a message as the one below

### ISSUE THREAD

**Issue by nasheayahu** [ntop/ntopng#7826]
**Environment**:
Edition	Windows 11 Pro
Version	22H2
Installed on	‎9/‎8/‎2023
OS build	22621.2283
Experience	Windows Feature Experience Pack 1000.22662.1000.0

* ntopng version/revision: 5.7.230830

**What happened**:
Keep getting
![Screenshot 2023-09-15 073649](https://github.com/ntop/ntopng/assets/5845052/5c2ebd3c-6fa6-4609-b401-9a7f0e734d57)

I have Wireshark installed
![Screenshot 2023-09-15 073805](https://github.com/ntop/ntopng/assets/5845052/dfcff73d-ae66-4635-b087-77ff196f5adb)

and I have all the dependency as well
![Screenshot 2023-09-15 073714](https://github.com/ntop/ntopng/assets/5845052/9757e14a-539a-49a6-a382-df1a493d9ff4)

**How did you reproduce it?**
During installation or executing the program manually

However it will not install
![Screenshot 2023-09-15 080034](https://github.com/ntop/ntopng/assets/5845052/daaafaac-b909-41e9-a9e5-f8c1492b32d2)

because I already have the latest version of MVC++ Red (x64), see above image.  Does this mean I will have to install wpcap along side npcap?

**Debug Information**:
none

**Comment by MatteoBiscosi** [comment]
Hi @nasheayahu the issue should now be fixed. Please follow the instructions here https://www.ntop.org/guides/ntopng/what_is_ntopng.html#installing-on-windows
Basically no, you have to install npcap api compatible mode when installing npcap and the issue should be fixed

**Comment by lucaderi** [comment]
We have also removed the need to install C++ redistributable
