### ISSUE TITLE
Flow Dumps Settings not visible in ntopng  

### ISSUE THREAD

**Issue by SHBIL** [ntop/ntopng#7829]
hello, i am trying to dump flows on clickhouse, i have setup the clickhouse on ntop on same machine, 
i am unable to see flow dumps settings in ntopng, your support is requested in this regard.

**Comment by MatteoBiscosi** [comment]
Hi @k-shehzad could you share your ntopng --version?

**Comment by SHBIL** [comment]
Sir issue is fixed by using -F switch in conf file to integrate Clickhouse DB in , now I am unable to see historical reports graphs,  I am using 5.7 version. With M licence

**Comment by SHBIL** [comment]
I am also facing GUI login issue , ntopng is not accepting password

**Comment by MatteoBiscosi** [comment]
Please, like requested share your ntopng --version and if possible the configuration file too.

**Comment by SHBIL** [comment]
ntopng --version
Version:        5.7.230919 [Enterprise/Professional build]
GIT rev:        dev:bb66f65eb3407281cb13435e8c4732f671934700:20230919
Pro rev:        r6083
Built on:       Ubuntu 20.04.6 LTS
System Id:      L3BFD4B6C5505621F--U3BFD4B6C88713DEA--OL
Platform:       x86_64
Edition:        Enterprise M
License Type:   Permanent

**Comment by SHBIL** [comment]
#         The  configuration  file is similar to the command line, with the exception that an equal
#        sign '=' must be used between key and value. Example:  -i=p1p2  or  --interface=p1p2  For
#        options with no value (e.g. -v) the equal is also necessary. Example: "-v=" must be used.
#
#
#       -G|--pid-path
#        Specifies the path where the PID (process ID) is saved. This option is ignored when
#        ntopng is controlled with systemd (e.g., service ntopng start).
#
-G=/var/run/ntopng.pid
#
#       -e|--daemon
#        This  parameter  causes ntop to become a daemon, i.e. a task which runs in the background
#        without connection to a specific terminal. To use ntop other than as a casual  monitoring
#        tool, you probably will want to use this option. This option is ignored when ntopng is
#        controlled with systemd (e.g., service ntopng start)
#
# -e=
#
#       -i|--interface
#        Specifies  the  network  interface or collector endpoint to be used by ntopng for network
#        monitoring. On Unix you can specify both the interface name  (e.g.  lo)  or  the  numeric
#        interface id as shown by ntopng -h. On Windows you must use the interface number instead.
#        Note that you can specify -i multiple times in order to instruct ntopng to create  multi-
#        ple interfaces.
#
# -i=eth1
# -i=eth2
#
#       -w|--http-port
#        Sets the HTTP port of the embedded web server.
--interface="tcp://127.0.0.1:5556"
-F="clickhouse;127.0.0.1;ntopng;*******;*****"
--local-networks="103.226.216.0.0/23,10.0.0.0/8,103.111.160.0/23"
# -w=3000
#
#       -m|--local-networks
#        ntopng determines the ip addresses and netmasks for each active interface. Any traffic on
#        those  networks  is considered local. This parameter allows the user to define additional
#        networks and subnetworks whose traffic is also considered local in  ntopng  reports.  All
#        other hosts are considered remote. If not specified the default is set to 192.168.1.0/24.
#
#        Commas  separate  multiple  network  values.  Both netmask and CIDR notation may be used,
#        even mixed together, for instance "131.114.21.0/24,10.0.0.0/255.0.0.0".
#
# -m=10.10.123.0/24,10.10.124.0/24
#
#       -n|--dns-mode
#        Sets the DNS address resolution mode: 0 - Decode DNS responses  and  resolve  only  local
#        (-m)  numeric  IPs  1  -  Decode DNS responses and resolve all numeric IPs 2 - Decode DNS
#        responses and don't resolve numeric IPs 3 - Don't decode DNS responses and don't  resolve
#
# -n=1
#
#       -S|--sticky-hosts
#        ntopng  periodically purges idle hosts. With this option you can modify this behaviour by
#        telling ntopng not to purge the hosts specified by -S. This parameter requires  an  argu-
#        ment  that  can  be  "all"  (Keep  all hosts in memory), "local" (Keep only local hosts),
#        "remote" (Keep only remote hosts), "none" (Flush hosts when idle).
#
# -S=
#
#       -d|--data-dir
#        Specifies the data directory (it must be writable by the user that is executing ntopng).
#
# -d=/var/lib/ntopng
#
#       -q|--disable-autologout
#        Disable web interface logout for inactivity.
#
# -q=
#
# Define nDPI custom protocols
#--online-license-check
#--community
--ndpi-protocols=/etc/ntopng/custom_protocols.txt

**Comment by SHBIL** [comment]
traffic graphs are also not being shown in the traffic report....... Pls help

**Comment by MatteoBiscosi** [comment]
Hi @k-shehzad the issue with the traffic report should be fixed in a couple of hours with the new version. Update and let me know

**Comment by SHBIL** [comment]
Hi, MetteoBiscosi, issue is fixed now :) ; thanks for your support in this regard.
