### ISSUE TITLE
Cannot generate historical data

### ISSUE THREAD

**Issue by souzaeric** [ntop/ntopng#783]
Hi, when I search historical data in historical data explorar, I only can generate with 1 hour, if I search any time bigger than 1 hour the result is empty. Do not shows nothing, even not a message with error... 
1 hour they generate OK.

Whats wrong? I start my ntopng like this:

ntopng  -i "tcp://127.0.0.1:5556" -m "192.168.90.0/24" -w 3000 -e -F "mysql;localhost;ntopng;flows;root;"

**Comment by souzaeric** [comment]
Any Ideas?

**Comment by simonemainardi** [comment]
hi,

first, please make sure to use the latest dev version (2.5.x)

then please answer the following:
- how long does it takes ntopng before giving you an empty result?
- make sure your database doesn't have timeout that may be terminating the query too early
- do you see any errors in the ntopng log?
- if you right click on your browser and select inspect element', do you see any errors after reloading the page?

**Comment by souzaeric** [comment]
Hi, answer your questions:
My version is: v.2.5.161011 [Enterprise/Professional Edition]
I have tested and I can generate report up to 17 hours, more than 17 will be empty.

how long does it takes ntopng before giving you an empty result?
Does not show a message with empty result, just it stuck on this page, I already left 10 minutes and nothing, like this picture, 
![image](https://cloud.githubusercontent.com/assets/22778946/19563798/185f00ee-96c0-11e6-847b-d88e8aa6544e.png)

make sure your database doesn't have timeout that may be terminating the query too early:
My timeouts:
 Variable_name              | Value |
+----------------------------+-------+
| connect_timeout            | 240   |
| delayed_insert_timeout     | 300   |
| innodb_lock_wait_timeout   | 50    |
| innodb_rollback_on_timeout | OFF   |
| interactive_timeout        | 28800 |
| net_read_timeout           | 30    |
| net_write_timeout          | 60    |
| slave_net_timeout          | 3600  |
| table_lock_wait_timeout    | 50    |
| wait_timeout               | 28800 |

No, my log doesn't show errors.

When I inspect element on my browser show this error: Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING

**Comment by simonemainardi** [comment]
a search of `net::ERR_INCOMPLETE_CHUNKED_ENCODING` pointed me to this thread: http://stackoverflow.com/questions/29894154/chrome-neterr-incomplete-chunked-encoding-error

can you please check?

Btw, your MySQL timeouts are good.

**Comment by souzaeric** [comment]
Thank you, the error with Chrome is gone. But I am still unable to generate report greater than 17 hours.

**Comment by simonemainardi** [comment]
please explain why the error with chrome is gone so that also other users can benefit

**Comment by souzaeric** [comment]
I go into Chrome's settings and use the "Restore to Default" option, the problem disappeared.

**Comment by simonemainardi** [comment]
thank you.

By looking at your previous screenshot, it looks like the mysql query is still executing so you think you can't get the results while actually ntopng is simply waiting for a mysql response.

I don't know how many flows/sec you export, but it can be that your mysql can't execute the queries of interest in a reasonable time.

Do the following: while you are waiting for the results open a MySQL shell and execute `show processlist`. If the query is executing you should be able to see an ntopng entry

**Comment by souzaeric** [comment]
Hi, I have executed the query on MySQL shell and took very long time. A query with dates between 05 october and 21 october, have duration 13 minutes.

When I generate report on ntopng and execute show processlist, after +- 200 seconds the state of query changes to sleep .
I export an average of 75 flows/sec.

![image](https://cloud.githubusercontent.com/assets/22778946/19608021/f9f9c66e-97ac-11e6-8fe4-707be66db626.png)

**Comment by simonemainardi** [comment]
as you can see the bottleneck is the speed of mysql, not ntopng. You should try to tune mysql (sw or sw + hw) to make sure it is able to provide you replies in a reasonable time in your environment. Remember also that, when you generate a report, ntopng doesn't use mysql so this is why the connections look as sleeping.

**Comment by souzaeric** [comment]
Thank you, I'll try tunne my MySql server.
