### ISSUE TITLE
ntopng plugin for OPNSense - network discovery shows nothing - how to configure interfaces?

### ISSUE THREAD

**Issue by emsofo** [ntop/ntopng#7836]
**Environment**:
* OS name: Proxmox 8.04 running OPNSense 23.7.6 virtualized
* OS version:  FreeBSD 13.2
* Architecture: x86_64
* ntopng version/revision: OPNSense Plugin 1.2_2

**What happened**:

Running latest 23.7.4 as virtualized host under Proxmox (virtio & linux bridges) - all is working fine for some time except the following:

I installed the ntopng plugin and it runs - but I can't seem to perform a network discovery (showing no results) and I can't seem to configure the interfaces from the OPNSesne gui as shown here:  https://docs.opnsense.org/manual/how-tos/ntopng.html

There is no option to select the interfaces ?!?  Under REDIS I enabled all interfaces but that didn't seem to help . . .

Any hints would be welcome!

**How did you reproduce it?**

Install ntopng and redis plugins - start services - go to GUI and try to perform a network discovery

**Comment by MatteoBiscosi** [comment]
Hi @emsofo please follow our instruction for ntopng installation in OPNSense, https://www.ntop.org/guides/ntopng/what_is_ntopng.html#installing-on-opnsense-pfsense the ntopng plugin on their system is no more supported.
In case you have still problems even after installing the official ntopng, please reopen the issue.
