### ISSUE TITLE
Monitoring IPv4 and IPv6 traffic

### ISSUE THREAD

**Issue by marcopirovano** [ntop/ntopng#7837]
**What would you like to add or change?**:
I would like to have a TS that reports both IPv4 and IPv6 traffic.

**Why do you and others need this?**:
Having this TS in InfluxDB, I can have a dashboard in Grafana that show me in real time the type of traffic.

**Comment by lucaderi** [comment]
1. The class EthStats already accounts traffic for IPv4 and IPv6 and other types
2. In NetworkInterface::lua() under the key "eth" the above stats are already exported
3. In scripts/callbacks/second/system/second.lua add a line similar to
            ts_utils.append("iface:traffic", {ifid=ifstats.id, bytes=ifstats.stats.bytes}, when)
anche check that ifstats already export the above values or if something need to be modified
4. Modify scripts/lua/modules/timeseries/schemas/ts_second.lua adding the definition for IPv4/6 traffic
5. Check that the new chart is reported in the interface chart menu

**Comment by lucaderi** [comment]
Verified as fixed
