### ISSUE TITLE
Add traffic profiles to Traffic Rules page

### ISSUE THREAD

**Issue by MarpleA** [ntop/ntopng#7839]
**What would you like to add or change?**:
I would like to see a feature which makes it easy to create an alert based on custom traffic profiles.
I created a custom traffic profile for wireguard traffic. Now I'd like to get an alert whenever such a flow is being detected. It seems like there is no way to create such an alert.

**Why do you and others need this?**:
To easily define new alerts based on nBPF Format.

**Comment by MatteoBiscosi** [comment]
@NicoMaio you could implement easily this alert by adding it to the Traffic Rules page.
Add new entry for the traffic profiles timeseries.
![image](https://github.com/ntop/ntopng/assets/49585191/edbd9491-1709-4954-98ac-7f033c8522ed)

**Comment by MarpleA** [comment]
I tried that but it didn't work for me. Probably I didn't configure it right. 
do you mean that my custom traffic profile should show up under metrics or where do I configure it?

**Comment by MatteoBiscosi** [comment]
Hi @MarpleA , @NicoMaio has to implement it, currently it's not available this feature. I suggested a way to develop it.

**Comment by NicoMaio** [comment]
Implemented in the PRO repo by 78f0f3ba8853b80e19528527526d1f7252dce97a

**Comment by MatteoBiscosi** [comment]
Implemented as requested
