### ISSUE TITLE
Syslog notification seems broken

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#7841]
**Environment**:
[ntopng Enterprise L v.5.7.230922 (Ubuntu 22.04.3 LTS) ](https://www.ntop.org/products/traffic-analysis/ntop/)|

**What happened**:
Configure a Syslog Endpoint for notifications
Set recipient for this Endpoint and severity level to `notice`.
GUI shows messages should have been sent:
![image](https://github.com/ntop/ntopng/assets/38549755/6adfd08d-2ab9-466e-b82a-1c683a67f786)

but checking with tcpdump shows no outgoing UDP traffic to the defined host in Endpoint.
Same behavior when changing to TCP .

**How did you reproduce it?**
Checked on two different hosts

**Debug Information**:

**Comment by cardigliano** [comment]
Fixed in ce0eb043cfb6fd2129801f7761547e89d1f6e9dc. A package update will be available soon.

**Comment by martinscheu** [comment]
thanks @cardigliano. from my side it is working on the hosts it didnt before.

**Comment by cardigliano** [comment]
thank you
