### ISSUE TITLE
Implement a VS Report

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7843]
This is to request to implement an HTML (pure that I can send via email without ntopng access) report with a few sections that contains:

1. First section [column list]
- IP numeric
- IP symbolic
- Scan type
- Number of CVEs
- List of CVEs
- Number of open ports
- list of open ports

2. Second section [column list]
- CVE number
- Port
- List of IP (symbolic if available or numeric if not) that are affected by such CVE

3. Third section [column list]
- Port
- List of IP (symbolic if available or numeric if not) that are affected by such CVE that have such port open

The HTML file must be a pure file, if you use CSS/JS etc they need to be downloaded from the cloud so the user opening the page can render it without any access to ntopng

**Comment by NicoMaio** [comment]
@uccidibuti 
It needs to be fixed: the 'Print' button on the 'Vulnerability Scan Report' report page should display all the data in the PDF.

**Comment by uccidibuti** [comment]
this is the commit that fix the print problems:
https://github.com/ntop/ntopng/commit/8e14e3dc3b96f9ad45e0202aa6f5e0a41b05f725

now we can add in component configuration custom_style and custom_print_style to set different style in view or print mode for each components.

**Comment by lucaderi** [comment]
Verified as fixed beside some tiny print issues
