### ISSUE TITLE
Flow Exporter dropdown not working with Aggregated Interface

### ISSUE THREAD

**Issue by MatteoBiscosi** [ntop/ntopng#7845]
As the screenshot shows, with aggregated interface, if the user has an exporter (can be seen from the last column in the interface), it is not possible to filter out by flow exporters because the dropdown is empty
![image](https://github.com/ntop/ntopng/assets/49585191/4fa8d918-6643-4f18-92c6-46038b2292fe)

**Comment by lucaderi** [comment]
Verified as fixed
