### ISSUE TITLE
VLAN untagged filter not working

### ISSUE THREAD

**Issue by MatteoBiscosi** [ntop/ntopng#7847]
Please see the screenshots below, when filtering per untagged vlan, in case of Client/Server/Dst Port, the filter is not correct, shows 3 entries but the table is empty after filtering
![Screenshot 2023-09-27 112746](https://github.com/ntop/ntopng/assets/49585191/435d4fa6-1ac4-499d-b90c-fde90c9bb18e)
![image](https://github.com/ntop/ntopng/assets/49585191/e9654c93-fd5c-41e9-bfd6-b7f1b4923e78)

**Comment by NicoMaio** [comment]
Fixed by 42866af4a94c4c195cf9b42ee2cba7399e578f07

**Comment by MatteoBiscosi** [comment]
Verified as fixed
