### ISSUE TITLE
Add option to ignore HTTP Proxy with SMTP

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#7849]
If a proxy has been configured via HTTP_PROXY / http_proxy env var, ntopng is trying to use those settings also for SMTP (email endpoint), however it is not always true that the http proxy is also used for smtp. One option to address this is to add a setting in the endpoint configuration to ignore proxy settings, if any.

**Comment by NicoMaio** [comment]
Fixed the checkbox with 88b8d0be400c65e017a84fec90c1636214107a86

**Comment by cardigliano** [comment]
Implemented in ed7ebaa6ac239a9595bce284672f56519bf56c9b 88b8d0be400c65e017a84fec90c1636214107a86
