### ISSUE TITLE
Help connect Nprobe and Ntopng on windows machine via NAT

### ISSUE THREAD

**Issue by avman20** [ntop/ntopng#785]
Hi, 
I have a situation that I want to have ntopng on a public IP and nprobe behind NAT (both on windows server and windows 7)
I follow the instruction here:
http://www.ntop.org/nprobe/advanced-flow-collection-with-ntopng-and-nprobe/

So I choose push mode (note that c is append at the end as instructed in above link: 
**ntopng.exe /i -i "tcp://1234c"**
Then open service manager, start the ntopng service and get "Error 1067: The process termitated unexpectedly"
If I remove the service, add again without tcp parameter, then it works.
**ntopng.exe /i "**

I get stuck at this step.
Thanks

Quote in http://www.ntop.org/nprobe/advanced-flow-collection-with-ntopng-and-nprobe/ :
Push Mode

host X> ntopng -i "tcp://*:1234c" --zmq-encrypt-pwd myencryptionkey
host Y> nprobe -n none --zmq "tcp://X:1234" --zmq-probe-mode --zmq-encrypt-pwd myencryptionkey

**Comment by simonemainardi** [comment]
hi, the interface name doesn't look complete. please add a `*:`:

```
ntopng.exe /i -i "tcp://*:1234c"
```

**Comment by avman20** [comment]
I do this 
ntopng.exe /i -i "tcp://*:1234c" 
and still same error.
"Error 1067: The process termitated unexpectedly"
I also tried on another Windows machine which produces same error.
I think this is a bug.

**Comment by simonemainardi** [comment]
can you please try without encryption? Also try to run the processes in foreground (/c) and report any suspicious message you may get on video.

**Comment by avman20** [comment]
Hi,
I created a video here:
https://youtu.be/yWU4y86MMvM

You can see on the video that Poll Mode , the service can start, Push mode cause error.
Hope you can find the issue.

**Comment by simonemainardi** [comment]
ok thanks for providing this information. Can you please run ntopng in foreground (use `\c` rather than `\i` after uninstalling the service with `\r`) and paste here the full console output?

Also keep in mind that, depending on the configuration used -- push or pull mode -- you need also to change nprobe parameters as well

**Comment by avman20** [comment]
Here is the output:( I ran cmd as Administrator)
ntopng.exe /c -i "tcp://_:1234c" 
Starting ntopg
Running ntopng.
21/Oct/2016 08:06:53 [Prefs.cpp:919] Logging into C:\Users\win7 64\Documents\ntopng.log
21/Oct/2016 08:06:53 [Ntop.cpp:1121] Setting local networks to 127.0.0.0/8
21/Oct/2016 08:06:53 [Redis.cpp:92] Successfully connected to redis 127.0.0.1:6379@0
21/Oct/2016 08:06:53 [NtopPro.cpp:120] [LICENSE] Read license from Redis []
21/Oct/2016 08:06:53 [NtopPro.cpp:172] ERROR: [LICENSE] Invalid or missing ntopng License [Empty license file]
21/Oct/2016 08:06:53 [NtopPro.cpp:185] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
21/Oct/2016 08:06:53 [NtopPro.cpp:187] WARNING: [LICENSE] before returning to community mode
21/Oct/2016 08:06:53 [NtopPro.cpp:188] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
21/Oct/2016 08:06:53 [NtopPro.cpp:189] WARNING: [LICENSE] or run ntopng in community mode starting
21/Oct/2016 08:06:53 [NtopPro.cpp:190] WARNING: [LICENSE] ntopng --community
21/Oct/2016 08:06:53 [CollectorInterface.cpp:59] ERROR: Unable to connect to ZMQ endpoint tcp://_:1234c
21/Oct/2016 08:06:53 [main.cpp:190] ERROR: Unable to create interface tcp://*:1234c
21/Oct/2016 08:06:53 [main.cpp:223] ERROR: Startup error: missing super-user privileges ?

**Comment by simonemainardi** [comment]
I am not sure the latest windows build is compatible with the `c` at the end of the ZMQ endpoint name. I guess you should still use the old flag `--zmq-collector-mode`.

The `c` has been added in July while the latest windows build has been released ad the end of June.

```
commit 9bf27b6940880d193e1a7631fb09a342f1b6ed8f
Author: Luca Deri <deri@ntop.org>
Date:   Sun Jul 3 14:23:29 2016 +0200

    Removed --zmq-collector-mode replaced with a c at the end of the endpoint. Example -i tcp://1.2.3.4:5678c
```

So I would ask @hung1024 to try with `ntopng.exe /c -i "tcp://*:1234" --zmq-collector-mode` and, in the meanwhile, I would encourage @lucaderi to release a new windows build.

**Comment by avman20** [comment]
This appears to work, thanks.

**Comment by simonemainardi** [comment]
thank you for reporting.
