### ISSUE TITLE
Historical Data not loading

### ISSUE THREAD

**Issue by cyablo** [ntop/ntopng#7850]
**Environment**:
* OS name: OPNsense / FreeBSD
* OS version: 23.7.5-amd64 / 13.2-RELEASE-p3
* Architecture: amd64
* ntopng version/revision: v.5.6.230926

**What happened**:

Historical Data tab is not loading in Host's Section:

![hist_data](https://github.com/ntop/ntopng/assets/3456720/baa85e75-ecf0-4482-804a-e01fae715445)

**How did you reproduce it?**

Click Hosts -> Select any Host -> Click on "Historical Data" Tab.

**Debug Information**:

Chrome Debug Console shows follwing Error:

```
timeseries-utils.js:252 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'epoch_begin')
    at timeseries-utils.js:252:42
    at Array.forEach (<anonymous>)
    at Af (timeseries-utils.js:246:17)
    at timeseries-utils.js:142:18
    at Array.forEach (<anonymous>)
    at Nf (timeseries-utils.js:141:18)
    at Object.Sf [as tsArrayToOptionsArray] (timeseries-utils.js:83:10)
    at V (page-stats.vue:391:42)
    at async page-stats.vue:220:27
```

**Comment by jepke** [comment]
Having issues alike here. Some users are unable to get data in Flows -> historical (clickhouse). Some even dont get the historical menu option in Flows.

**Comment by iamtherobin** [comment]
Having the same problem on my opnsense firewall. No historical data and I cannot figure out why. It's just not there.

**Comment by MatteoBiscosi** [comment]
Hi, sorry but missed the issue. Regarding not finding the Historical entry is probably due to the fact that CH is not enabled with ntopng, please check this issue for a possible problem https://github.com/ntop/ntopng/issues/7871

**Comment by MatteoBiscosi** [comment]
Regarding the host timeseries missing, could you check if there is some issue reported in ntopng logs?
Could you please send me the URL?
Could you please send me the REST?
![image](https://github.com/ntop/ntopng/assets/49585191/9601120e-9921-4168-81ef-30498e8dfd64)

**Comment by iamtherobin** [comment]
> Hi, sorry but missed the issue. Regarding not finding the Historical entry is probably due to the fact that CH is not enabled with ntopng, please check this issue for a possible problem #7871

Just FYI OPNsense is FreeBSD 13. So I don't know if that ticket is related.

I am not seeing a ts_multi.lua in my network monitor. Here is a sample URL in my case https://192.168.0.1:4000/lua/if_stats.lua?ifid=3&page=historical&epoch_begin=1697641323&epoch_end=1697643123

Where will I find the relevant logs to check?

**Comment by iamtherobin** [comment]
Just wanted to add ntopng historical graphs are suddenly working again since updating to OPNsense 23.7.6-amd64.

Can anyone else confirm the update fixed it for them or is it just a coincidence?

**Comment by MatteoBiscosi** [comment]
I pushed a couple of fixes in the latest update, glad to know that it seems working. Just to be sure, could you share your ntopng version?

**Comment by iamtherobin** [comment]
ntopng Community v.5.6.231011 (FreeBSD 13.2)

EDIT: Was previously on same version in OP

**Comment by lucaderi** [comment]
The ntopng build you are using is not coming from ntop so we encourage to use the binaries we release as they contain the bug fixes we developed. Please go to https://packages.ntop.org

**Comment by MatteoBiscosi** [comment]
Hi @iamtherobin sorry but totally missed an important thing, on FreeBSD, the only version currently supported is the 5.7.
Please uninstall the default packages available on OPNSense and reinstall ntopng by following this guide
https://www.ntop.org/guides/ntopng/third_party_integrations/opnsense.html#opnsenseintegration
