### ISSUE TITLE
Host Traffic Volume Exceeded Not Triggered

### ISSUE THREAD

**Issue by NicoMaio** [ntop/ntopng#7853]
In Local Traffic Rules, the alert for Host Rules (using *) is not triggered when the threshold is crossed.

**Comment by MatteoBiscosi** [comment]
In my case it's triggered correctly:
![image](https://github.com/ntop/ntopng/assets/49585191/e7535033-7c92-4115-8bce-42ea066b7bfa)
![image](https://github.com/ntop/ntopng/assets/49585191/ce75de37-3136-4ea7-a826-7a0e43b2f937)

**Comment by NicoMaio** [comment]
The issue regarding HSOL.

**Comment by NicoMaio** [comment]
Fixed in pro repo by b876254c9e6ff9dd4cc9bdda43a7507539534117

**Comment by NicoMaio** [comment]
Verified as fixed.
