### ISSUE TITLE
Invalid Host First Seen

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7856]
[630_obfuscated_vpn.pcap.zip](https://github.com/ntop/ntopng/files/12771879/630_obfuscated_vpn.pcap.zip)

<img width="1312" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/7247d2dd-ef94-4f1a-aae2-baa6ea44b39b">

**Comment by NicoMaio** [comment]
I am attempting to print the value of the host["seen.first"] variable in the host_details.lua file, and I am receiving the value 65. 
Wireshark appears to confirm this:
<img width="738" alt="image" src="https://github.com/ntop/ntopng/assets/55502486/0d947dbe-af2f-4c3b-b94c-6156f6bb3fcd">

**Comment by MatteoBiscosi** [comment]
The issue seems releated to the pcap, not to an ntopng issue
