### ISSUE TITLE
Change policy - All tests done from the page "Manage Traffic Filtering Policies"

### ISSUE THREAD

**Issue by atlanteinformatica** [ntop/ntopng#786]
Starting subnet: 192.168.131.0/24
Single host: 192.168.131.36/32, 
Our goal: split the /24 into two /25; inserting 192.168.131.0/25 and 192.168.131.128/25 objects for a simulation of diverse filtering on two groups of hosts. 

Step 1 - Entering single host and subnet in blocking policy.
The single host blocks: Skype, Facebook, Youtube, and Tor. 
The subnet blocks: Facebook. 
Everything ok.

Step 2 - Changing the single host blocks.
Changing the policy by removing Youtube and Facebook. 
We do not know why but the entire subnet was offline.

Step 3 - Inserting and deleting subnet 
Subnet inserted: 192.168.131.128/25
Subnet deleted: 192.168.131.0/24  
The office was offline again. 
Resolution
Deleting 192.168.131.128/25 , re-insertion 192.168.131.0/24  (without blocks) and then clicking on "Set Protocol Policy and Shaper".

During this tests we learned that, whenever an host (or subnet) listed in the drop down menu "Network" is offline, clicking "Set Protocol Policy and Shaper" after selecting it solved the problem.
Every time we modified a Network Object, our network stopped working.

**Comment by emanuele-f** [comment]
@atlanteinformatica, thank you for reporting. The bug has been fixed. Please test next daily rebuild. Reopen the issue if necessary.
