### ISSUE TITLE
VS: Unable to search in Host Name

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7864]
In the VS page, the search box does not search symbolic host names.

**Comment by lucaderi** [comment]
Not working

02/Oct/2023 21:21:06 [LuaEngine.cpp:1396] WARNING: Script failure [/home/deri/ntopng/scripts/lua/rest/v2/get/host/to_scan_list.lua][...eri/ntopng/scripts/lua/rest/v2/get/host/to_scan_list.lua:63: attempt to index a nil value (field '?')]
02/Oct/2023 21:21:07 [LuaEngine.cpp:1396] WARNING: Script failure [/home/deri/ntopng/scripts/lua/rest/v2/get/host/to_scan_list.lua][...eri/ntopng/scripts/lua/rest/v2/get/host/to_scan_list.lua:63: attempt to index a nil value (field '?')]
02/Oct/2023 21:21:08 [LuaEngine.cpp:1396] WARNING: Script failure [/home/deri/ntopng/scripts/lua/rest/v2/get/host/to_scan_list.lua][...eri/ntopng/scripts/lua/rest/v2/get/host/to_scan_list.lua:63: attempt to index a nil value (field '?')]
02/Oct/2023 21:21:18 [LuaEngine.cpp:1396] WARNING: Script failure [/home/deri/ntopng/scripts/lua/rest/v2/get/host/to_scan_list.lua][...eri/ntopng/scripts/lua/rest/v2/get/host/to_scan_list.lua:63: attempt to index a nil value (field '?')]
02/Oct/2023 21:21:28 [LuaEngine.cpp:1396] WARNING: Script failure [/home/deri/ntopng/scripts/lua/rest/v2/get/host/to_scan_list.lua][...eri/ntopng/scripts/lua/rest/v2/get/host/to_scan_list.lua:63: attempt to index a nil value (field '?')]

<img width="1595" alt="Screenshot 2023-10-02 at 21 21 53" src="https://github.com/ntop/ntopng/assets/4493366/162565fc-92cd-4ae1-a644-8ec9105b2d71">

**Comment by lucaderi** [comment]
Verified as fixed

**Comment by HostingGlobal** [comment]
Hello, Good morning ^^

i update ntopng to  5.7.231024-21934 and restart the ntopng

but still can't search hostname.
