### ISSUE TITLE
Time Picker: Invalid Year Update

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7868]
<img width="380" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/218d85ff-c98a-4f45-8628-72429b79e0f2">

Changing the year with arrows up/down does not change the year in the string now the "Apply" button is enabled

**Comment by uccidibuti** [comment]
This is a no sense request. Changing month or year it means only change the displayed menu. If you want select a date you must click on the day that you want select. This is how the js picker library works,  what would happen if I select February 29 of a year and move to a non-leap year?
