### ISSUE TITLE
Missing HTTPS/SSL 

### ISSUE THREAD

**Issue by atlanteinformatica** [ntop/ntopng#787]
Maybe is our mistake but in the search bar does not appear (by writing http) the HTTPS/SSL (we do not see even scrolling through the list).

Web catergory list 
For blocking adult sites (or other types of site in HTTP/HTTPS) is possible to use lists like http://urlblacklist.com (or make it an option)?

**Comment by simonemainardi** [comment]
the search bar is used to search hosts.

if you want to see live SSL flows just select the protocol from the dropdown menu in the flows page

![image](https://cloud.githubusercontent.com/assets/3397663/19349321/ba580756-9152-11e6-98de-eb53da51247e.png)

Historical SSL flows can be searched with the data explorer:

![image](https://cloud.githubusercontent.com/assets/3397663/19349372/fb3223ba-9152-11e6-9988-8c9e2a88b0c6.png)

to block sites you can try ntopng httpbl support. See option

```
[--traffic-filtering|-k] <param>    | Filter traffic using cloud services.
                                    | (default: disabled). Available options:
                                    | httpbl:<api_key>        See README.httpbl
```

**Comment by atlanteinformatica** [comment]
All our issue are for the applications filtering.
It seem that is not possible to block HTTPS/SSL.

**Comment by simonemainardi** [comment]
see this:
![image](https://cloud.githubusercontent.com/assets/3397663/19380832/2ed08c74-91f9-11e6-84ad-1d2df0124d97.png)
