### ISSUE TITLE
FreeBSD 14 Clickhouse Startup Issue on 5.7.231004

### ISSUE THREAD

**Issue by dkggpeters** [ntop/ntopng#7871]
**Environment**:
* FreeBSD 14 (PFSense 23.05)
* Enterprise 5.7.231004

**What happened**:
Upgraded from the previous version dated 9/4/2023 (5.7.230904) and receive the following error related to clickhouse on startup:

04/Oct/2023 19:31:45 [Prefs.cpp:2029] WARNING: -F mysql/-F clickhouse not available: missing MySQL support in ntopng

Config file was unchanged and worked previously

**Comment by dkggpeters** [comment]
Not sure if the kernel mismatch is the issue.  PFSense is 23.05.1

![image](https://github.com/ntop/ntopng/assets/63671969/eaec1c83-d51e-4b24-acab-88fd9aa932bd)

**Comment by dkggpeters** [comment]
Maybe I am reading it wrong, although the problem appears to be have_mysql as not being defined for FreeBSD 14.  In configure.ac.in, mysql is never defined for FreeBSD 14.  Mysql does exist in my /usr/local/bin directory.

[![have_mysql](https://github.com/ntop/ntopng/assets/63671969/0db0193f-c635-486c-85b4-cce452c3e9bf)](url)

**Comment by lucaderi** [comment]
FreeBSD has issues with OpenSSL and MySQL depends on it. Until this problem is solved and FreeBSD 14 officially release, we cannot do much unfortunately

**Comment by dkggpeters** [comment]
Thanks for the response.  I am hoping that the change from OpenSSL from 1
to 3 will resolve the issue.  I believe it is on the PFSense 23.09 roadmap
which should be released soon.

Dave

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by MatteoBiscosi** [comment]
This issue is due to a FreeBSD problem, closing the issue. If after the official release, the issue still persists, please reopen.
