### ISSUE TITLE
ntopng not clearing RAM and GUI slow responsive. 

### ISSUE THREAD

**Issue by Alisher-Nabiev** [ntop/ntopng#7876]
**Environment**:
* OS name: Ubuntu
* OS version: 18.04.6 LTS 
* Architecture: x86_64
* ntopng version/revision: ntopng Enterprise L v.5.5.230112 rev.19181

**What happened**:
The machine collects RAM over time, and after 3-6 days, the service restarts because RAM usage reaches 97% or higher.

When using the GUI interface, it is slow and laggy. Even after server restart, it takes minutes to navigate.

**How did you reproduce it?**
I can share monitoring graphs 

**Debug Information**:

**Comment by Alisher-Nabiev** [comment]
[ntopng log.txt](https://github.com/ntop/ntopng/files/12817915/ntopng.log.txt)
<img width="883" alt="ntopng" src="https://github.com/ntop/ntopng/assets/33841389/0b12e0ea-d853-414f-b6f9-f4546d6f4c2a">

**Comment by MatteoBiscosi** [comment]
Hi @Alisher-Nabiev sorry but we do not support the 5.5 version anymore. If you need help you have to update to the latest 5.7 or 5.6 version. Remember that if you did not renew the license, after updating the license is not going to work.

**Comment by lucaderi** [comment]
These leaks have been fixed in more recent versions. Please update and reopen this ticket if necesary
