### ISSUE TITLE
Update from GUI caused a disservice

### ISSUE THREAD

**Issue by atlanteinformatica** [ntop/ntopng#788]
The Ntopng application was stopped (from GUI you could see the red ball and from CLI there was ntopng process). We do not know if it was an accident, but we had to start/stop a couple of times the service package (from GUI) before reviewing the ntopng process running again. 
Later everything is back to normal.

Is possible to write a notice in the upgrade page that alerts of possible disservice?

**Comment by simonemainardi** [comment]
I am not sure to understand... Can you please rephrase the exact steps you did?

**Comment by atlanteinformatica** [comment]
Sure. 
we updated the appliance using the appropriate function in the gui. This operation has stopped the ntopng service and caused a disservice. We started troubleshooting and we have verified that the ntopng process (Linux process I mean) was not running; to start the service (and the process) we used the appropriate function of the gui, but to have the complete operation it took a couple of start / stop.

**Comment by simonemainardi** [comment]
@ValentinaViscarelli please check this out. Thank you.

**Comment by ValentinaViscarelli** [comment]
@atlanteinformatica 
The GUI suggest you reboot the system after updating the system (image attached). 
Do you have reboot the system?
After rebooting, ntopng should automatically start if you have enabled it in configuration (image attached).
So:
1) Enable ntopng to start at startup.
2) Update the system
3) Reboot
4) Check if ntopng is run

Let me know if it works.

![selection_008](https://cloud.githubusercontent.com/assets/13115771/19399310/3032be40-9251-11e6-9cfc-28ac03594d86.png)

![selection_010](https://cloud.githubusercontent.com/assets/13115771/19399363/725ee1cc-9251-11e6-8cb4-f69aef08f052.png)

**Comment by atlanteinformatica** [comment]
Hi Valentina, thank you for the reply.
The GUI suggest to reboot but do not alert about the disservice. This is different. Seem that the suggestion is telling: sooner or later reboot the appliance.
We suggest you to write something like: Warning, the update will restart the services.

Regards

**Comment by ValentinaViscarelli** [comment]
Just a think... do you have enable automatic startup in ntopng?
I don't think we need to alert because if you have set "automatic startup", ntopng must start. If not there is a bug.

**Comment by atlanteinformatica** [comment]
We know (now) that an update require a reboot.
If you won't put an alert, this issue can't live. So...

**Comment by ValentinaViscarelli** [comment]
In my opinion the alert is not important, but since you say that it is important I added a warning in update page.
![selection_012](https://cloud.githubusercontent.com/assets/13115771/19701107/400ee1b6-9afa-11e6-9856-33315e637ee5.png)

**Comment by atlanteinformatica** [comment]
Hi Valentina,

many thanks for this change. Yes, is important because it can be dangerous for those who can't imagine the possible consequences of pressing that button. 
Regards.

**Comment by atlanteinformatica** [comment]
Hi Valentina,

we can't view this change in our appliance. 
ntopng -V
v.2.5.161117 [Enterprise/Professional Edition]

Regards

**Comment by ValentinaViscarelli** [comment]
Just to clarify....
nbox and ntopng are two different things. You have updated ntopng but not nbox. 
At the moment you cannot update nbox because we have had some problems with ubuntu16 and we removed the nbox package building for ubuntu 16.
We will restore everything asap.
Please try to update in few days.

**Comment by ValentinaViscarelli** [comment]
@atlanteinformatica 
The nbox package for ubuntu 16 is available again.

**Comment by atlanteinformatica** [comment]
Thank you. Now we can see the change.
Unfortunatelly, although the ntopng service was configured to start automatically, it didn't start.
We started manually after reboot. Is it a bug/issue to notice here, or we have to open a new issue?

**Comment by ValentinaViscarelli** [comment]
It is not important open other bug. I will check and I will let you know.

**Comment by simonemainardi** [comment]
it looks like the issue is solved. Thanks @ValentinaViscarelli
