### ISSUE TITLE
SNMP device interface is not showing any graph data and showing data of 01 jan 1970

### ISSUE THREAD

**Issue by SHBIL** [ntop/ntopng#7882]
no data in graph in snmp and showing data of 1 jan 1970. how to fix it

**Environment**:
* OS name: [Ubuntu]
* OS version: [ 20.04]
* Architecture: [amd64]
* ntopng version/revision: [5.6.230]

**What happened**:

**How did you reproduce it?**

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi, please give us more info or we cannot help you give us the output of ntopng --version and a couple of screenshots

**Comment by SHBIL** [comment]
B-S@ntopng:~$ ntopng --version
Version:        5.6.230920 [Enterprise/Professional build]
GIT rev:        5.6-stable:f5d186f3ed840e9898ab15c079ceabd78c50961c:20230920
Pro rev:        r5568
Built on:       Ubuntu 20.04.6 LTS
System Id:      L3BFD4B6C5505621F--U3BFD4B6C88713DEA--OL
Platform:       x86_64
Edition:        Enterprise M
License Type:   Permanent
Maintenance:    Until Sat Sep 14 21:50:21 2024 [332 days left]

**There is no graph data in snmp interface utilization, i.e interface utilization is not being shown in snmp**

**Comment by k-shehzad** [comment]
![Ntop-NG](https://github.com/ntop/ntopng/assets/109748815/217259aa-d094-45ba-aaa2-29231ebba691)

**Comment by SHBIL** [comment]
![Capture](https://github.com/ntop/ntopng/assets/109748815/9c7acfef-906c-4053-af3b-c7d28ba90d1d)

**Comment by lucaderi** [comment]
@k-shehzad Today we will release a new stable that does not seem to be affected by your problem. Please check it out as soon as builds will be available

**Comment by MatteoBiscosi** [comment]
Hi @k-shehzad the issue should be fixed, please update and in case the issue persists reopen the ticket

**Comment by SHBIL** [comment]
@MatteoBiscosi After the update in am seeing below logs while clicking the SNMP link

HTTP/1.1 302 Found Server: ntopng 6.0.231101 (x86_64) Set-Cookie: session=2c6543eb2ff18edf69a0210d2b0dbe91; HttpOnly; path=/; HttpOnly; SameSite=lax Location: /lua/http_status_code.lua?message=internal_error&referer=10.50.3.249%3A3050%2Flua%2Fpro%2Fenterprise%2Fsnmpdevices_stats.lua&error_message=%2Fusr%2Fshare%2Fntopng%2Fpro%2Fscripts%2Flua%2Fmodules%2Fsnmp_config.lua%3A152%3A%20attempt%20to%20index%20a%20nil%20value%20%28field%20%27%3F%27%29 /usr/share/ntopng/pro/scripts/lua/modules/snmp_config.lua:152: attempt to index a nil value (field '?')

**Comment by SHBIL** [comment]
![ntop snmp](https://github.com/ntop/ntopng/assets/109748815/77e945c0-1747-434c-b202-25a288ab9b9e)
