### ISSUE TITLE
SNMP Device CPU and Memory

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#7884]
Sometime the network is slow and if you could have CPU and Memory data available on SNMP device can help you to understand some extra flow behaviour or latency introduced by switch bottleneck

**Comment by lucaderi** [comment]
Please report the device type/model and the SNMP proprietary MIB that needs to be used (CPU/memory are usually on proprietary MIBs)

**Comment by MatteoBiscosi** [comment]
Closing for missed feedback, in case it's needed again, please reopen
