### ISSUE TITLE
The TLS Source found gnar.grammarly.com

### ISSUE THREAD

**Issue by NicoMaio** [ntop/ntopng#7886]
<img width="1393" alt="Screenshot 2023-10-09 alle 15 08 25" src="https://github.com/ntop/ntopng/assets/55502486/17f9c04e-42ce-45eb-9e10-b770ad53329b">

**Comment by NicoMaio** [comment]
Fixed by 2233e386ce37563d68a4c071b1e2b387bcbeece3

**Comment by MatteoBiscosi** [comment]
Verified as fixed
