### ISSUE TITLE
[nEdge] Segfault when triggering a reboot

### ISSUE THREAD

**Issue by maurinxw** [ntop/ntopng#7894]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04
* Architecture: x86_64
* ntopng version/revision: 5.7.231012

**What happened**:

Every time I trigger a machine reboot nothing happens.

**How did you reproduce it?**

I can reproduce it by changing IP address of an interface and applying modifications, or acting to the top-right menu on "reboot". As far as I can see from "journalctl -f", the shutdown procedure starts but nedge crashes in the middle of it, so - instead of triggering a reboot - nedge itself is restarted.

**Debug Information**:

`Oct 12 15:37:02 NXgate nedge[4015301]: 12/Oct/2023 15:37:02 [PeriodicActivities.cpp:98] Terminated periodic activites...`
`Oct 12 15:37:03 NXgate nedge[4015301]: 12/Oct/2023 15:37:03 [main.cpp:478] Terminating...`
`Oct 12 15:37:06 NXgate nedge[4015301]: 12/Oct/2023 15:37:05 [NetworkInterface.cpp:3568] Host alerts dump thread terminated for nf:0`
`Oct 12 15:37:07 NXgate nedge[4015301]: 12/Oct/2023 15:37:06 [NetworkInterface.cpp:3505] Flow alerts dump thread terminated for nf:0`
`Oct 12 15:37:07 NXgate nedge[4015301]: 12/Oct/2023 15:37:06 [Ntop.cpp:3101] Polling shut down [interface: nf:0]`
`Oct 12 15:37:07 NXgate nedge[4015301]: 12/Oct/2023 15:37:07 [Ntop.cpp:3123] Executing shutdown script [shutdown.lua]`
`Oct 12 15:37:07 NXgate nedge[4015301]: 12/Oct/2023 15:37:07 [ThreadedActivity.cpp:298] Running /usr/share/ntopng/scripts/callbacks/system/shutdown.lua (iface=0x556165ae3820)`
`Oct 12 15:37:07 NXgate nedge[4015301]: 12/Oct/2023 15:37:07 [LuaEngineNtop.cpp:6022] ntop_trace_event() called`
`Oct 12 15:37:07 NXgate nedge[4015301]: 12/Oct/2023 15:37:07 [shutdown.lua:42] [checks.lua:1109] Script 'score_behavior' configuration is missing from subdir 'interface'. New user script?`
`Oct 12 15:37:07 NXgate nedge[4015301]: 12/Oct/2023 15:37:07 [LuaEngineNtop.cpp:6022] ntop_trace_event() called`
`Oct 12 15:37:07 NXgate nedge[4015301]: 12/Oct/2023 15:37:07 [shutdown.lua:42] [checks.lua:1109] Script 'traffic_behavior' configuration is missing from subdir 'interface'. New user script?`
`Oct 12 15:37:07 NXgate nedge[4015301]: 12/Oct/2023 15:37:07 [LuaEngineNtop.cpp:6022] ntop_trace_event() called`
`Oct 12 15:37:07 NXgate nedge[4015301]: 12/Oct/2023 15:37:07 [shutdown.lua:42] [checks.lua:1109] Script 'snmp_device_interface_threshold_crossed' configuration is missing from subdir 'snmp_device'. New user script?`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [LuaEngineNtop.cpp:6022] ntop_trace_event() called`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [shutdown.lua:42] [checks.lua:1109] Script 'ndpi_fully_encrypted' configuration is missing from subdir 'flow'. New user script?`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [LuaEngineNtop.cpp:6022] ntop_trace_event() called`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [shutdown.lua:42] [checks.lua:1109] Script 'ndpi_tls_alpn_sni_mismatch' configuration is missing from subdir 'flow'. New user script?`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [LuaEngineNtop.cpp:6022] ntop_trace_event() called`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [shutdown.lua:42] [checks.lua:1103] ERROR: Missing subdir 'active_monitoring' from config`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [shutdown.lua:42] [checks.lua:1103] ERROR: Missing subdir 'active_monitoring' from config`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [HTTPserver.cpp:1951] HTTP server terminated`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [NetfilterInterface.cpp:896] Closing nlif_handle...`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [NetfilterInterface.cpp:903] Closing NF_QUEUE...`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [Utils.cpp:5459] Socket 34 closed`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [NetworkInterface.cpp:3745] Cleanup interface nf:0`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [Utils.cpp:5459] Socket 31 closed`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [Utils.cpp:5459] Socket 32 closed`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [Utils.cpp:5459] Socket 33 closed`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [NetworkInterface.cpp:384] cleanShadownDPI(0x556166796340)`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [NetworkInterface.cpp:384] cleanShadownDPI((nil))`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [Utils.cpp:5459] Socket 7 closed`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [Utils.cpp:5459] Socket 8 closed`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [Utils.cpp:5459] Socket 5 closed`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [Utils.cpp:5459] Socket 6 closed`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [Utils.cpp:5459] Socket 9 closed`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [Utils.cpp:5459] Socket 10 closed`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [Utils.cpp:5459] Socket 3 closed`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [Utils.cpp:5459] Socket 4 closed`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [Utils.cpp:5459] Socket 11 closed`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [Utils.cpp:5459] Socket 12 closed`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [Utils.cpp:5459] Socket 13 closed`
`Oct 12 15:37:08 NXgate nedge[4015301]: 12/Oct/2023 15:37:08 [AddressResolution.cpp:47] Address resolution stats [0 resolved][0 failures]`
`Oct 12 15:37:09 NXgate kernel: ntopng-main[4136456]: segfault at 518 ip 000055f4f1725662 sp 00007ffd89554860 error 4 in nedge[55f4f160c000+206000]`
`Oct 12 15:37:09 NXgate kernel: Code: 01 00 00 ba 01 00 00 00 4c 8d 05 4f 9c 10 00 be 00 01 00 00 48 89 df e8 5c b0 ee ff 3d ff 00 00 00 77 b1 48 8b 05 be 6e 29 00 <48> 8b b8 18 05 00 00 48 85 ff 74 04 48 8b 7f 10 31 c0 49 89 d9 b9`
`Oct 12 15:37:09 NXgate systemd[1]: ntopng.service: Main process exited, code=dumped, status=11/SEGV`
`Oct 12 15:37:09 NXgate systemd[1]: ntopng.service: Failed with result 'core-dump'.`
`Oct 12 15:37:14 NXgate systemd[1]: ntopng.service: Scheduled restart job, restart counter is at 4.`
`Oct 12 15:37:14 NXgate systemd[1]: Stopped nedge high-speed web-based traffic monitoring and analysis tool.`
`Oct 12 15:37:14 NXgate systemd[1]: Starting nedge high-speed web-based traffic monitoring and analysis tool...`
`Oct 12 15:37:14 NXgate systemd[1]: Started nedge high-speed web-based traffic monitoring and analysis tool.`

**Comment by cardigliano** [comment]
This should've been addressed today, please let us know in case you can still reproduce it with the latest update.

**Comment by maurinxw** [comment]
Solved, thanks
