### ISSUE TITLE
[VS] New table doesn't set default sort column

### ISSUE THREAD

**Issue by NicoMaio** [ntop/ntopng#7895]
After specifying the default column to sort in the new table on the JSON file, the component doesn't set the arrow on the column.

**Comment by lucaderi** [comment]
<img width="1535" alt="Screenshot 2023-10-20 at 18 56 51" src="https://github.com/ntop/ntopng/assets/4493366/051b6332-2785-41d9-ba10-4aaf3979ae83">

**Comment by MatteoBiscosi** [comment]
The issue should now be fixed.
However consider that the default sort is applied only the first seen the table is loaded.
![image](https://github.com/ntop/ntopng/assets/49585191/28ecb5c3-6896-4bdb-afd1-f3ab30dc58f4)

**Comment by NicoMaio** [comment]
Verified as fixed.
