### ISSUE TITLE
[nEdge] Captive portal: once authorized the landing page in the browser could not be the expected one

### ISSUE THREAD

**Issue by maurinxw** [ntop/ntopng#7896]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04
* Architecture: x86_64
* ntopng version/revision: 5.7.231012

**What happened**:

Under certain conditions, once the captive portal successfully authenticated us, the browser is redirected to a wrong page.

**How did you reproduce it?**

Example: I try to access corriere.it and it open the captive portal page
http://192.168.40.1:3000/lua/captive_portal.lua?referer=corriere.it%2F

If I have configured "redirection URL" in the captive portal page, browser is redirected to that page (that correctly overrides www.corriere.it)
If I have not configured "redirection URL" browser is not redirected to www.corriere.it but to the login page. If I login again, then the browser will land finally to www.corriere.it

**Debug Information**:

**Comment by cardigliano** [comment]
@maurinxw this has been fixed yesterday, please check latest dev and let us know

**Comment by maurinxw** [comment]
solved, thanks
