### ISSUE TITLE
[nEdge] Informative page for captive portal has a couple of inconsistencies

### ISSUE THREAD

**Issue by maurinxw** [ntop/ntopng#7897]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04
* Architecture: x86_64
* ntopng version/revision: 5.7.231012

**What happened**:

If I set the "informative" flag without entering anything in the "informative page URL" in the captive portal configuration page, we are redirected in a page (there is a small typo - agreee with 3 "e") with a link to a wikipedia page for GDPR that we cannot read before confirmation. Probably the intended page should be reachable for reading before confirmation.

**How did you reproduce it?**

set the "informative" flag without entering anything in the "informative page URL" in the captive portal configuration page.

**Debug Information**:

**Comment by cardigliano** [comment]
Typo has been fixed. As of the wikipedia link, the Wikipedia protocol should be allowed to users not yet assigned. In short this depends on #7898 (allowing the Wikipedia protocol to those allowed by default).
