### ISSUE TITLE
--dump-flows to https instead of http

### ISSUE THREAD

**Issue by TotieBash** [ntop/ntopng#7899]
**Is there a way to configure --dump-flows to Elasticsearch using https?**
**how do I ignore the certificate error like the equivalent of "curl -k" or "curl --insecure"**
**I am getting "ERROR ...... SSL peer certificate or SSH remote key was not OK"**

**Environment**:
* OS name: Centos 7.9
* OS version: Centos 7.9
* Architecture: [e.g. amd64]
* ntopng version/revision: "5.4.221102 on Ubuntu 22.04.1 LTS" using the official docker image]

https://www.ntop.org/guides/ntopng/advanced_features/flows_dump.html#flowdumpelasticsearch

![image](https://github.com/ntop/ntopng/assets/86748904/31c6c219-66ab-4c12-bcd7-3151586317a2)

**Comment by cardigliano** [comment]
Please try adding --insecure to the ntopng configuration file

<img width="695" alt="Screen Shot 2023-10-13 at 10 25 41" src="https://github.com/ntop/ntopng/assets/7548711/9e79be49-dd98-4378-8675-9eb81cd6730a">
