### ISSUE TITLE
Local Traffic Rules: Broken GUI

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7909]
$ redis-cli get "ntopng.prefs.ifid_2.flow_exp_device_threshold_rules"
"[{\"rule_type\":\"Host\",\"threshold\":\"1073741824\",\"target\":\"*\",\"selected_iface\":\"\",\"metric_label\":\"Traffic\",\"metric\":\"host:traffic\",\"frequency\":\"5min\",\"metric_type\":\"volume\",\"id\":\"*_host:traffic__5min\",\"threshold_sign\":\"-1\"}]"

$ redis-cli get "ntopng.prefs.ifid_2.host_threshold_rules"
"[]"

but the GUI shows

<img width="1146" alt="Screenshot 2023-10-14 at 20 44 45" src="https://github.com/ntop/ntopng/assets/4493366/be755a1a-f72d-48b8-a8ea-c5a76b8d8650">

**Comment by NicoMaio** [comment]
Fixed in pro repo by b876254c9e6ff9dd4cc9bdda43a7507539534117

**Comment by lucaderi** [comment]
Verified as fixed
