### ISSUE TITLE
Unable to view historical data

### ISSUE THREAD

**Issue by bcstechdept** [ntop/ntopng#791]
Hello!
    I am using nprobe to capture flow information from a Cisco ASA 5512-X and relay it to ntopng on the same machine.
    My problem is that I am unable to use the Historical Data Explorer, everything returns "no results".  Additionally, the "IPv4 Flows" under the historical tab disappears and both the "Talkers" and "Protocols" tabs return "No Results Found".
    The MySQL Flows Export Statistics looks good and doesn't have any drops.  There is data in the mysql database.

ntopng -V
v.2.5.161020 [Enterprise/Professional Edition]
Built on:  CentOS Linux release 7.2.1511 (Core) 

cat ntopng.conf
-G=/var/run/ntopng.pid
--interface=tcp://127.0.0.1:5556
--http-port=3000
--dns-mode=1
-m=10.0.0.0/8,172.0.0.0/8
-S=local
-x=50000
-X=400000
-F="mysql;127.0.0.1;ntop;flows;ntop;ntopng"

/usr/local/bin/nprobe -v
Welcome to nProbe v.7.5.161020 (r5443) for x86_64-unknown-linux-gnu
with native PF_RING acceleration.
Edition:       nProbe Standard

cat nprobe.conf
--zmq="tcp://127.0.0.1:5556"
-i=eth0
-n=none
--collector-port=6343

ASA 5512-X config:
flow-export destination Inside 172.16.0.108 6343

policy-map global_policy
class class-default
flow-export event-type all destination 172.16.0.108

I have tried exporting to both a Percona sql cluster and to a local MariaDB MySQL server with the same results.

Percona version-
mysqld  Ver 5.6.32-78.1-56 for debian-linux-gnu on x86_64 (Percona XtraDB Cluster (GPL), Release rel78.1, Revision 979409a, WSREP version 25.17, wsrep_25.17)

MariaDB version-
/usr/libexec/mysqld  Ver 5.5.50-MariaDB for Linux on x86_64 (MariaDB Server)

**Comment by bcstechdept** [comment]
I'm not sure what happened but this is working now using the local mysql server after I restarted ntopng after modifying the maximum flows value.  Thanks for taking a look!

**Comment by bcstechdept** [comment]
I stand corrected.  It works for about an hour then stops displaying historical data.

**Comment by simonemainardi** [comment]
navigate to the interface page and see if MySQL flows are dropped when you can't see the results. 
It can be that mysql is not able to ingest flows at the rate ntopng is sending them.

Alternatively, check the footer for the actual number of active flows and hosts. If you see red badges, then very likely your hash tables are full (i.e., you have too many hosts/flows) and ntopng is forced to drop new flows. Dropped flows are not inserted into MySQL. Make sure to increase hash table sizes using `-x` and `-X` so that the actual number are much smaller than the maximum configured numbers.

Also, remember that only mysql is officially supported, no percona or mariadb.

**Comment by bcstechdept** [comment]
Hey simonemainardi,
  Thanks for the reply!  The interface page doesn't show any dropped flows but I think you're right in that the database servers I'm trying to use can't keep up with ntop's speed.  I have -x and -X set to about double what I would expect our actual number of hosts and flows to be from watching during peak hours.  Is there anything else I can do like a buffer/"ZMQ for SQL"?

**Comment by simonemainardi** [comment]
I am still not sure what is happening on your system. You said that you don't see dropped flows in the MySQL export statistics and, at the same time, the historical explorer doesn't show the results. Is it correct? 

If that is the case, then either:
- mysql is executing select queries (check this with `mysql> show processlist`)
- data is sent to mysql but is not yet committed so you can't see that
- there is some error in ntopng (check this my inspecting ntopng logs)

**Comment by bcstechdept** [comment]
Hey simone,
  Yes, that's correct.  Ntop is not reporting any dropped flows but I do not see the data in the historical explorer, no matter how long I wait.  My network frequently bursts from ~8k flows to ~350k, and I think I'm experiencing a MySQL performance issue rather than a problem with ntop itself.

**Comment by simonemainardi** [comment]
if flows are not dropped and not shown in the historical explorer, it means that they don't even reach the ntopng. Do you see data in the dashboard and in the charts?

run nprobe using `--debug` and see if it properly receives flows from the ASA as well.

**Comment by bcstechdept** [comment]
Hi simone,
  Yes, data is populated in the dashboard and all the rrdtool/whisper graphs/data that's stored in redis is all accurate and is retained correctly.  Running with --debug, I can definitely see the flow information from the ASA coming in and it looked like ntop was correctly exporting it, it just looks like my database server can't keep up when my network traffic gets bursty.

**Comment by simonemainardi** [comment]
I see. There was a similar problem in another issue a few days ago. You should tune your mysql and make sure it can handle (e.g., both queries and insertions) the data you send.

**Comment by bcstechdept** [comment]
Thanks for your help, simone.  I will try tweaking some mysql performance settings and see if I can get it going again.

**Comment by simonemainardi** [comment]
We have also improved the ntopng UI to inform the user when a query is taking too long to complete. The user can also choose to abort the query in order to narrow down the search criteria. By means of ajax, we've been able to implement these features while keeping the overall interface responsive. This should improve the user experience. I think it is safe to close this. Please, try the latest version and feel free to give us feedback.

**Comment by Baymax254** [comment]
Hey , I am on ntopng free version, 3.1 using ES i can save data, but how can i display  it using ntopng Lua web interface? using the same template provided in READme.Elasticsearch
