### ISSUE TITLE
No Local Host Traffic Rules for LocalLink IPv6 Addresses

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7911]
<img width="1419" alt="Screenshot 2023-10-16 at 11 38 42" src="https://github.com/ntop/ntopng/assets/4493366/9e588c8c-a53a-4bcc-a033-f1769b0f32b5">

Host alerts for local link or multicast addresses cannot be generated,

**Comment by NicoMaio** [comment]
Fixed in pro repo by 24f8b1e42e33f19edd8f776b13256abbec5bb20d

**Comment by lucaderi** [comment]
Verified as fixed
