### ISSUE TITLE
Wrong Traffic Threshold

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7912]
<img width="1415" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/3bf3aeae-9a66-4bf7-a317-c1243ccebaa2">

Given that a ethernet packet is at least 60 bytes, the way host rules are checked is definitively wrong

**Comment by NicoMaio** [comment]
Fixed in pro repo also by 7562d6f44d12ff1470aa28aee1b5c853f769e1de

**Comment by lucaderi** [comment]
Verified as fixed
