### ISSUE TITLE
Invalid report when selecting a 5 minute interval

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7913]
How to reproduce it
- take one host
- select a 5-minute interval
- the chart is empty, the table below is partially empty

Solution: never display less than two points, or make sure that what you visualize is consistent

<img width="1218" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/7a5488b0-8b7e-46c8-ac97-85a0767ba1b3">

**Comment by lucaderi** [comment]
Please set the minimum period to 10 minutes

<img width="275" alt="Screenshot 2023-10-16 at 16 39 24" src="https://github.com/ntop/ntopng/assets/4493366/4ddd0b8e-95a7-4f6a-877b-b5272935360f">

**Comment by NicoMaio** [comment]
Verified as fixed.
