### ISSUE TITLE
Iface TS step is wrong

### ISSUE THREAD

**Issue by NicoMaio** [ntop/ntopng#7914]
Setting up a threshold rule with the "iface:ndpi" schema (5 minutes frequency) printing the data received from the 'ts_utils.timeseries_query' the step is 60 instead of 300. (epoch_begin and epoch_end instead are correct)

**Comment by MatteoBiscosi** [comment]
The interface l7 timeseries are minute frequency timeseries, not 5 minutes
![image](https://github.com/ntop/ntopng/assets/49585191/79435d4d-f8ca-4e49-a0c0-ab40e6d5d6c5)
![image](https://github.com/ntop/ntopng/assets/49585191/da492d22-a45d-407f-91dc-e0a19698f8a4)
