### ISSUE TITLE
Discrepancy in Timeseries Values and Host Threshold Rules

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7916]
<img width="1442" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/1e5b3864-b08c-47e5-afb0-31b423c0ce41">

RX+TX total is about 12 GBytes according to the chart

Looking at host traffic rules it is 9.3 GB

<img width="1419" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/2cd91b1d-6a40-45f3-89b4-4b3bf3be7885">

Something is wrong.

**Comment by NicoMaio** [comment]
Fixed in pro repo by 3280e6915bb6a5d00169abe280121a4df04574eb

**Comment by lucaderi** [comment]
Verified as fixed
