### ISSUE TITLE
flow_alert_ndpi_malware_host_contacted not triggered

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7921]
Howto reproduce it
- Add 67.215.92.210 in a blacklist (example /var/lib/ntopng/category_lists/Feodo.txt)
- Use the enclosed pcap [1.pcap.zip](https://github.com/ntop/ntopng/files/12965672/1.pcap.zip)
- start ntopng -i 1.pcap

The NDPI_MALWARE_HOST_CONTACTED is reported by nDPI but it does not
- update the flow score
- report the risk in the flow info

**Comment by cardigliano** [comment]
8a97f69c278bbd0d832b41db65e0beb1919ff8f0 should address this

**Comment by NicoMaio** [comment]
Verified as fixed
