### ISSUE TITLE
[VS] Rework Report Page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7925]
On the report page, there are some sections that sometimes should be omitted due to lack of information. For instance, if there are no CVEs (or no CVE scans) the CVE section of the report should be omitted or empty (today is partially filled)

**Comment by NicoMaio** [comment]
Fixed in the pro repo (only on the back-end side not, not in the report frontend side) by fcca0066234b237dd0daaf205c3e2f2a0545c2ed

**Comment by lucaderi** [comment]
Verified as fixed
