### ISSUE TITLE
Implement Host Alias Search

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7931]
If a host has a custom name/alias set
![1697744730359](https://github.com/ntop/ntopng/assets/4493366/ff67f21c-de07-4936-853e-2b713663c16b)

this is not considered in the search box
![1697744744480](https://github.com/ntop/ntopng/assets/4493366/484e506f-c857-43e7-8533-dcae0d924681)

This ticket is to request to implement a search of custom hostnames

**Comment by HostingGlobal** [comment]
Thank you very much for interesting to me.

I want to contribute in any way.

**Comment by cardigliano** [comment]
Host search by alias is working in the latest dev (that will become stable in a few days). Please check it and let me know in case of issues.

**Comment by HostingGlobal** [comment]
I look forward to working it :-)

**Comment by lucaderi** [comment]
Verified as fixed

**Comment by NMSGLOBAL** [comment]
> Verified as fixed

Thank you for your effort

Can i apply it now with

Yum - y update?
