### ISSUE TITLE
Add ntop for raspbian bookworm

### ISSUE THREAD

**Issue by CookieCr2nk** [ntop/ntopng#7938]
**What do you want to add or change?**:

Add ntop for raspbian bookworm. Currently there is only a package for raspbian bullseye https://packages.ntop.org/apt/bullseye_pi/

**Why do you and others need this?**:

For RaspberryPi users who want to stay up to date with the latest debian.

**Comment by lucaderi** [comment]
See https://packages.ntop.org/apt/bookworm_pi/

**Comment by CookieCr2nk** [comment]
Thanks for adding bookworm :)
