### ISSUE TITLE
pfring_zc and ntopng packet loss

### ISSUE THREAD

**Issue by papage** [ntop/ntopng#794]
Hi all,

I have a few problems getting ntopng to work without significant packet loss. 
My setup is:
Centos7 VM 4core/6GB RAM with a passed-through intel 10G 520 adapter.

PFcount seems ok:
/usr/local/bin/pfcount -i zc:ens160

Absolute Stats: [1'494'382 pkts total][0 pkts dropped][0.0% dropped]
[1'494'382 pkts rcvd][1'140'440'217 bytes rcvd][498'086.65 pkt/sec][3'040.92 Mbit/sec]

Actual Stats: [382'705 pkts rcvd][1'000.06 ms][382'680.89 pps][2.33 Gbps]

NTOPNG shows extreme packet loss. 
Dropped Packets 46,507,909 Pkts [ 90.25 % ] 
Actually is proccesses 60-70K pps when I have 400Kpps

Top shows:
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND  
 2771 nobody    20   0 2565496 1.422g   5976 S 204.3 18.6  10:09.36 ntopng  
 1357 redis     20   0  146788   9960   1516 S  30.9  0.1   1:16.68 redis-server    

Is that normal? How can I imporve its perfomance?
I have tried to change RSS=4 and launch ntopng with zc:ens160@0-3 but it did not improve.

Thanx,
sp

Setup details: 
# ethtool -g ens160

Ring parameters for ens160
Pre-set maximums:
RX:             32768
RX Mini:        0
RX Jumbo:       0
TX:             32768
Current hardware settings:
RX:             32768
RX Mini:        0
RX Jumbo:       0
TX:             32768
# cat /proc/net/pf_ring/dev/ens160/info

Name:         ens160
Index:        4
Address:      90:E2:BA:5C:BB:9D
Polling Mode: NAPI/ZC
Type:         Ethernet
Family:       Intel ixgbe 82599
TX Queues:    1
RX Queues:    1
Num RX Slots: 32768
Num TX Slots: 32768
# cat /proc/interrupts | grep ens160

 63:         25      34405          0          0          0          0   PCI-MSI-edge      ens160-TxRx-0
 64:          3          0          0          0          0          0   PCI-MSI-edge      ens160
# cat /etc/pf_ring/zc/ixgbe/ixgbe.conf

RSS=1
# cat /etc/pf_ring/zc/ixgbe/ixgbe.start
# 
# cat /etc/ntopng/ntopng.conf

-G=/var/run/ntopng.pid
--interface=zc:ens160
--local-networks="147.102.0.0/16,147.102.222.0/24,147.102.220.0/24,147.102.247.0/24,2001:648:2000::/48"
--data-dir=/var/ntopng
--dns-mode=1
--disable-autologout
-x 512000
-g -1

**Comment by lucaderi** [comment]
Please open this issue under PF_RING
