### ISSUE TITLE
Vulnerability scan additional subnets

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#7943]
**What would you like to add or change?**:
Dear ntop team

Could you add additional commonly used subnets, like 30, 26, 27, 29 ?

Thank you.

![image](https://github.com/ntop/ntopng/assets/38549755/806cb9a7-4a9f-4894-afc7-35ab2d1f79f4)

**Why do you and others need this?**:

**Comment by MatteoBiscosi** [comment]
This is not user friendly at all, please add a text box, with default value of 24
![image](https://github.com/ntop/ntopng/assets/49585191/2eed6726-34e3-4766-9f7b-7b29237282e7)
![image](https://github.com/ntop/ntopng/assets/49585191/440db9ea-2eb7-4d41-bed3-82fb95d0e51c)

**Comment by lucaderi** [comment]
In all the dialogs a default value should be put. /24 is not a default as requested but a hint

**Comment by NicoMaio** [comment]
By default on VS the CIDR put is /32 when the Host is IPv4 

> In all the dialogs a default value should be put. /24 is not a default as requested but a hint

**Comment by lucaderi** [comment]
Verified as fixed
