### ISSUE TITLE
Actions Must be the First Column on the Left

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7944]
In some pages the Actions menu is the last column on the right, instead of the correct first column on the left. Please fix it and check all pages

<img width="1396" alt="Screenshot 2023-10-24 at 09 45 06" src="https://github.com/ntop/ntopng/assets/4493366/977a7a3d-5d43-4de6-978a-ab352e987587">

**Comment by lucaderi** [comment]
Verified as fixed

**Comment by lucaderi** [comment]
<img width="1696" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/1457919e-ed11-4b15-834c-5a580a8fecec">
This is not yet as it should

**Comment by MatteoBiscosi** [comment]
Moved all the actions column on the left side of the table (first column)
