### ISSUE TITLE
Search Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7945]
<img width="1560" alt="Screenshot 2023-10-24 at 15 43 04" src="https://github.com/ntop/ntopng/assets/4493366/e474c770-36b6-4d62-8581-5496aea76917">

**Comment by NicoMaio** [comment]
Fixed in pro repo by 635200d4506bf51d94851b64d7aef0f1175ca8a9

**Comment by lucaderi** [comment]
Verified as fixed
