### ISSUE TITLE
Unable to add SNMP Rules

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7947]
How to reproduce
- Click on +
- Click on Add
- No rule is added

<img width="1361" alt="Screenshot 2023-10-24 at 16 19 14" src="https://github.com/ntop/ntopng/assets/4493366/53c8410c-3f5f-4759-8c84-6c4f36172400">

**Comment by NicoMaio** [comment]
Fixed by 8f6fbafc79b245bc2f425a83072589b846b14604

**Comment by lucaderi** [comment]
Verified as fixed
