### ISSUE TITLE
Stateful Alerts are Lost with Shutdown 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7949]
How to reproduce it
- Create a SNMP device rule that triggers many alerts (other methods can be used)
- Alerts are produced
<img width="1631" alt="Screenshot 2023-10-24 at 17 53 44" src="https://github.com/ntop/ntopng/assets/4493366/069bbcc3-f96c-42b9-9eb8-5aaba679d21c">
- "Gracefully" shutdown ntopng and restart it
- Upon restart alerts are lost
- 
<img width="1604" alt="Screenshot 2023-10-24 at 17 54 07" src="https://github.com/ntop/ntopng/assets/4493366/d03b5be1-36ca-4582-9f07-bb59526db67a">

**Comment by cardigliano** [comment]
Please also see https://github.com/ntop/ntopng/issues/7679

**Comment by MatteoBiscosi** [comment]
The issue seems fixed now. The ones in the screenshots were engaged alerts previous to ntopng shutdown 
![image](https://github.com/ntop/ntopng/assets/49585191/6a7789a5-e574-4a59-9c17-4232b8ab0055)

**Comment by MatteoBiscosi** [comment]
Issue fixed in the latest stable
