### ISSUE TITLE
periodic ntopng restarts on RPi

### ISSUE THREAD

**Issue by bob3rocks** [ntop/ntopng#795]
When I run ntopng on the command line to stdout, the process will fail after a few minutes with "**_stack smashing detected**_." When I run ntopng as a daemon from init.d, the process fails and restarts itself. This happens every 5 minutes. Log sample:

Oct 24 09:40:01 jessie-rpi systemd[1]: Started ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool.
Oct 24 09:45:00 jessie-rpi sh[28125]: **\* stack smashing detected _**: /usr/sbin/ntopng terminated
Oct 24 09:45:00 jessie-rpi systemd[1]: ntopng.service: main process exited, code=killed, status=6/ABRT
Oct 24 09:45:00 jessie-rpi systemd[1]: Unit ntopng.service entered failed state.
Oct 24 09:45:01 jessie-rpi systemd[1]: ntopng.service holdoff time over, scheduling restart.
Oct 24 09:45:01 jessie-rpi systemd[1]: Stopping ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool...
Oct 24 09:45:01 jessie-rpi systemd[1]: Starting ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool...
Oct 24 09:45:01 jessie-rpi sh[28170]: 24/Oct/2016 09:45:01 [Prefs.cpp:548] Logging into /var/log/ntopng/ntopng.log
Oct 24 09:45:01 jessie-rpi systemd[1]: PID file /var/tmp/ntopng.pid not readable (yet?) after start.
Oct 24 09:45:01 jessie-rpi systemd[1]: Started ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool.
Oct 24 09:50:00 jessie-rpi sh[28170]: *_\* stack smashing detected _**: /usr/sbin/ntopng terminated
Oct 24 09:50:00 jessie-rpi systemd[1]: ntopng.service: main process exited, code=killed, status=6/ABRT
Oct 24 09:50:00 jessie-rpi systemd[1]: Unit ntopng.service entered failed state.
Oct 24 09:50:00 jessie-rpi systemd[1]: ntopng.service holdoff time over, scheduling restart.
Oct 24 09:50:00 jessie-rpi systemd[1]: Stopping ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool...
Oct 24 09:50:00 jessie-rpi systemd[1]: Starting ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool...
Oct 24 09:50:00 jessie-rpi sh[28215]: 24/Oct/2016 09:50:00 [Prefs.cpp:548] Logging into /var/log/ntopng/ntopng.log
Oct 24 09:50:01 jessie-rpi systemd[1]: PID file /var/tmp/ntopng.pid not readable (yet?) after start.
Oct 24 09:50:01 jessie-rpi systemd[1]: Started ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool.
Oct 24 09:55:00 jessie-rpi sh[28215]: *_\* stack smashing detected _**: /usr/sbin/ntopng terminated
Oct 24 09:55:00 jessie-rpi systemd[1]: ntopng.service: main process exited, code=killed, status=6/ABRT
Oct 24 09:55:00 jessie-rpi systemd[1]: Unit ntopng.service entered failed state.
Oct 24 09:55:01 jessie-rpi systemd[1]: ntopng.service holdoff time over, scheduling restart.
Oct 24 09:55:01 jessie-rpi systemd[1]: Stopping ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool...
Oct 24 09:55:01 jessie-rpi systemd[1]: Starting ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool...
Oct 24 09:55:01 jessie-rpi sh[28262]: 24/Oct/2016 09:55:01 [Prefs.cpp:548] Logging into /var/log/ntopng/ntopng.log
Oct 24 09:55:01 jessie-rpi systemd[1]: PID file /var/tmp/ntopng.pid not readable (yet?) after start.
Oct 24 09:55:01 jessie-rpi systemd[1]: Started ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool.
Oct 24 10:00:00 jessie-rpi sh[28262]: *_\* stack smashing detected ***: /usr/sbin/ntopng terminated
Oct 24 10:00:00 jessie-rpi systemd[1]: ntopng.service: main process exited, code=killed, status=6/ABRT
Oct 24 10:00:00 jessie-rpi systemd[1]: Unit ntopng.service entered failed state.
Oct 24 10:00:00 jessie-rpi systemd[1]: ntopng.service holdoff time over, scheduling restart.
Oct 24 10:00:00 jessie-rpi systemd[1]: Stopping ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool...
Oct 24 10:00:00 jessie-rpi systemd[1]: Starting ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool...
Oct 24 10:00:00 jessie-rpi sh[28323]: 24/Oct/2016 10:00:00 [Prefs.cpp:548] Logging into /var/log/ntopng/ntopng.log
Oct 24 10:00:01 jessie-rpi systemd[1]: PID file /var/tmp/ntopng.pid not readable (yet?) after start.
Oct 24 10:00:01 jessie-rpi systemd[1]: Started ntopng - High-Speed Web-based Traffic Analysis and Flow Collection Tool.

---

System is Raspberry Pi 2 running Debian GNU/Linux 8 \n \l

root@jessie-rpi:~# ntopng --version
v.1.2.1 (r1.2.1)

**Comment by bob3rocks** [comment]
Also, I tried to update ntopng, but this is the only package available from apt-get. I also tried compiling from source which fails.

**Comment by emanuele-f** [comment]
Can you specify what arguments you pass from command line?

**Comment by bob3rocks** [comment]
This is what I have in /etc/init.d/ntopng:
ARGS="--daemon --pid $PIDFILE --disable-autologout"

This is what it looks like from ps aux:
/usr/sbin/ntopng --daemon --pid /var/tmp/ntopng.pid -w 3000

**Comment by emanuele-f** [comment]
Thank you. Can you run ntopng from command line and report a stack trace with the error (gdb)?

With a4bd8f1 I've fixed a bug which caused a crash when a usb bluetooth dongle was connected to the system. Do you have any kind of devices connected to RPI? Can you possibly compile and run nDPI and ntopng from github repository? Alternatively you can wait the nightly builds in apt.ntop.org repository.

**Comment by bob3rocks** [comment]
I installed the debugger and this is all I get from gdb ntopng:
Reading symbols from ntopng...(no debugging symbols found)...done.

I tried compiling from the github repository and and compile fails during the last phases of the process. I can try that again and post it in a separate thread if you like.

There is no bluetooth device connected to the RPi. There was a cheapo WIFI dongle plugged in, that was not in use. For fun, I removed the dongle, with no change -- when I run ntopng I still see the stack smashing detected in the logs.

I followed the steps to get the nightly build, and I see that ntopng is already the newest version.

**Comment by emanuele-f** [comment]
Into the gdb environment, you have to run the `start` command, followed by ntop arguments, in order to start debugging the program. After the crash, you can run the `bt` command to get a backtrace, which you should post here.

Nightly builds are built each night, so you will be able to install the new version since tomorrow. Thank you for the feedback.

**Comment by bob3rocks** [comment]
My apologies, I am not that familiar with the gdb environment, and I get no result when using the start command. 

(gdb) start /usr/sbin/ntopng
No symbol table loaded.  Use the "file" command.

Am I right in assuming ntopng has to be compiled for debugging in order for this to work?

**Comment by emanuele-f** [comment]
I guess you are using https://archive.raspbian.org/raspbian/pool/main/n/ntopng/ ntopng from raspbian, which is outdated and not ufficially supported by us. Please, install an officially supported build from our repository. You can follow the instructions reported http://packages.ntop.org/RaspberryPI/. Reopen if necessary.
