### ISSUE TITLE
The --offline switch is still being ignored.

### ISSUE THREAD

**Issue by DaddyBurrito72** [ntop/ntopng#7957]
Hello,

I hope this message finds you well. Thank you for this work with ntopng.

I am trying to understand what's preventing me from leveraging the "--offline" command switch. Even when I am using this, I am still seeing the software making DNS lookups and establishing TLS1.3 sessions with at least one remote site over tcp/443.

I am using the following ntop version that was installed from my gentoo linux portage package management:
Version:        5.6.230624 [Community build]
GIT rev:        :5.6.230624

Steps to reproduce - execute the following from a bash shell:

`ntopng -U ntopng --offline`

...and at the same time, I see the host doing a DNS lookup for DNS type "A" and type "AAAA" records for github.com and then I see the station establishing a tls1.3 session over tcp/443 with the target IP address that we see returned in the RRDATA from the DNS response.

I thought the documentation explained that the --offline switch was expected to prevent this. Here's what I found in the documentation.

1. There's a post on the ntop.org website that invites the use of the switch. This can be read from this hyperlink: [](https://www.ntop.org/faq/to-what-ip-domain-names-ntopng-connects-to/)
And excerpt of this is found here:
##############################################
If you are using ntopng on a site with no Internet access, ntopng might be slow. For this reason we invite you start ntopng with –offline to disable Internet access to the above sites.
##############################################

2. This is also explained in the ntopng user guide under the "Command Line Options" section. The current version of the ntopng user guide (5.7) summarizes that use the --offline CLI switch should avoid contacting remote sites. The link for the documentation is here: [](https://www.ntop.org/guides/ntopng/cli_options/cli_options.html?highlight=offline)
Excerpt:
##############################################
[--offline] Run in offline mode (avoid contacting remote sites, including blacklists)
##############################################

3. The --help command line switch also outputs a line about the use of the --offline command line option:
`[--offline]                         | Run in offline mode (avoid contacting remote sites, including blacklists)`

When I start the tool, it immediately tries to establish a tls session with gitub.com. Why?

I found this in the startup too:

```
28/Oct/2023 09:15:37 [Ntop.cpp:470] Welcome to ntopng x86_64 v.5.6.230624 (:5.6.230624)
28/Oct/2023 09:15:37 [Ntop.cpp:480] Built on Gentoo Linux
[more logging outputs omitted]
28/Oct/2023 09:15:37 [startup.lua:35] Processing startup.lua: please hold on...
28/Oct/2023 09:15:37 [startup.lua:120] [lists_utils.lua:819] Category lists not loaded (offline)
28/Oct/2023 09:15:37 [startup.lua:124] Initializing device polices...
28/Oct/2023 09:15:37 [startup.lua:140] Initializing alerts...
28/Oct/2023 09:15:37 [startup.lua:149] Initializing timeseries...
28/Oct/2023 09:15:37 [startup.lua:212] Fetching latest ntop blog posts...
28/Oct/2023 09:15:37 [startup.lua:216] Completed startup.lua
```

Why is ntopng still trying to communicate with the external site, github.com? If it's thought that this is happening because it's fetching the blog posts, then this feels like there's a bug because the startup.lua has mention of the tool being set up with the "offline" - the output of the Category lists as "(offline)" at the end of the line - but then 4 lines below that it's trying to fetch the blog posts.

Is this a bug?

Thank you again for taking a look at this and thank you much again for this exciting work with ntopng.

**Comment by cardigliano** [comment]
This is on 5.6 stable. ntopng 6.0 will be released today, we need to verify if this still applies.

**Comment by MatteoBiscosi** [comment]
The issue seems fixed, please reopen the ticket if the issue persists with the latest stable version
