### ISSUE TITLE
ntopng key signing down?

### ISSUE THREAD

**Issue by deanfourie1** [ntop/ntopng#7958]
**Environment**:
* bullseye - raspberrypi
* 11
* arm64
* latest

**What happened**:
Do you want to continue? [Y/n] y
Setting up apt-ntop-stable (2.9-25) ...
Installing ntop GPG key [no proxy]. Please wait...
gpg: CRC error; F00B5A - 1E27B7
gpg: read_block: read error: Invalid keyring
gpg: Total number processed: 0
dpkg: error processing package apt-ntop-stable (--configure):

admin@raspberrypi:~ $ sudo apt update
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 http://archive.raspberrypi.org/debian bullseye InRelease
Ign:5 https://packages.ntop.org/apt-stable/bullseye_pi arm64/ InRelease
Ign:6 https://packages.ntop.org/apt-stable/bullseye_pi all/ InRelease
Err:7 https://packages.ntop.org/apt-stable/bullseye_pi arm64/ Release
  404  Not Found [IP: 167.99.215.164 443]
Err:8 https://packages.ntop.org/apt-stable/bullseye_pi all/ Release
  404  Not Found [IP: 167.99.215.164 443]
Reading package lists... Done
E: The repository 'https://packages.ntop.org/apt-stable/bullseye_pi arm64/ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://packages.ntop.org/apt-stable/bullseye_pi all/ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**How did you reproduce it?**
just tried to install the apt-ntop-stable.deb.

**Debug Information**:

**Comment by lucaderi** [comment]
We do not build stable packages for raspberry. Please use dev versions

**Comment by deanfourie1** [comment]
Yea, nah nothing works.

**Comment by deanfourie1** [comment]
Stable or nightly, i'm unable to install due to the GPG key failing.

**Comment by deanfourie1** [comment]
hostnamectl

```
admin@raspberrypi:~ $ hostnamectl
   Static hostname: raspberrypi
         Icon name: computer
        Machine ID: 665f72a560f54b1a976eadb12902ec7f
           Boot ID: 802857d7a49a4cd9816ff3052c3a218a
  Operating System: Debian GNU/Linux 11 (bullseye)
            Kernel: Linux 6.1.21-v8+
      Architecture: arm64
```

Choosing debain nightly packages from https://packages.ntop.org/apt/ and choosing debian 11 bullseye.

```
admin@raspberrypi:~ $ sudo apt install ./apt-ntop.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'apt-ntop' instead of './apt-ntop.deb'
The following packages will be upgraded:
  apt-ntop
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 0 B/2,702 B of archives.
After this operation, 3,072 B disk space will be freed.
Get:1 /home/admin/apt-ntop.deb apt-ntop all 2.9-25 [2,702 B]
Reading changelogs... Done
(Reading database ... 37764 files and directories currently installed.)
Preparing to unpack /home/admin/apt-ntop.deb ...
Unpacking apt-ntop (2.9-25) over (2.9-16) ...
upgrade
Setting up apt-ntop (2.9-25) ...
Installing ntop GPG key [no proxy]. Please wait...
gpg: CRC error; F00B5A - 1E27B7
gpg: read_block: read error: Invalid keyring
gpg: Total number processed: 0
dpkg: error processing package apt-ntop (--configure):
 installed apt-ntop package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 apt-ntop
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Any trying the following.

```
wget https://packages.ntop.org/RaspberryPI/apt-ntop.deb
sudo dpkg -i apt-ntop.deb
```

Returns the following.

```
admin@raspberrypi:~ $ sudo dpkg -i apt-ntop.deb
dpkg: warning: downgrading apt-ntop from 2.9-25 to 2.9-16
(Reading database ... 37764 files and directories currently installed.)
Preparing to unpack apt-ntop.deb ...
Unpacking apt-ntop (2.9-16) over (2.9-25) ...
upgrade
Setting up apt-ntop (2.9-16) ...
Installing ntop GPG key. Please wait...
gpg: CRC error; F00B5A - 1E27B7
gpg: read_block: read error: Invalid keyring
gpg: Total number processed: 0
dpkg: error processing package apt-ntop (--install):
 installed apt-ntop package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 apt-ntop

```

**Comment by deanfourie1** [comment]
there is definitely a issue with your key signing server.

**Comment by deanfourie1** [comment]
@lucaderi 

FYI, your support is shit!

You don't just mark an issue as completed and move on when it's not completed.

Thats crap.
