### ISSUE TITLE
[VS] Notifications not working

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7963]
After a nightly scan ended at about 3 AM
- apparently, an email (yesterday one was sent and delivered, so count is +1) was delivered (two emails sent in total) but not received. Second problem, the time indicates almost 6AM

Something is wrong

<img width="1346" alt="Screenshot 2023-10-31 at 08 54 29" src="https://github.com/ntop/ntopng/assets/4493366/00b573ec-bf84-4dbe-9043-b659298e19c0">
<img width="366" alt="Screenshot 2023-10-31 at 08 54 06" src="https://github.com/ntop/ntopng/assets/4493366/96b8c492-fbc0-4b5a-b4ef-c3270cb5c19b">

**Comment by cardigliano** [comment]
After this fix d0da787cb751481206e684b6d93ad734a1234198 it seems to be working for me, please confirm

**Comment by MatteoBiscosi** [comment]
Verified as fixed
