### ISSUE TITLE
[VS] Load open ports not working

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#7970]
**Environment**:
* OS name: [e.g. Ubuntu] Ubuntu
* OS version: [e.g. 18.04] 22.04 LTS
* Architecture: [e.g. amd64] amd64
* ntopng version/revision: [e.g. 5.1.211223] [ntopng Community v.6.1.231101 (Ubuntu 22.04.3 LTS) ](https://www.ntop.org/products/traffic-analysis/ntop/)|

**What happened**:
When I want to check for open ports on a host not present in my network, I get "unknown host" : 

<img width="631" alt="Screenshot 2023-11-02 at 09 27 32" src="https://github.com/ntop/ntopng/assets/38549755/ab76a9a3-f55e-42cc-8a3c-125f9ff3756e">

**How did you reproduce it?**

**Debug Information**:

**Comment by martinscheu** [comment]
duplicated entry: https://github.com/ntop/ntopng/issues/7968

**Comment by lucaderi** [comment]
We probably need to change the logic. The idea of the button is to load from ntopng the open ports of host 88.xxx in order to limit the scan to it. As such host is probably not active in ntopng, this is the message "Unknown Host".
We'll think about it and see what we can do to make it better

**Comment by martinscheu** [comment]
ok understand, then maybe change the description to "load ports from ntopng" and hide the button for TCP / UDP port scan

**Comment by NicoMaio** [comment]
We decided to remove this button temporarily. (35f66ca1c67ef65d43cd41ec732415b0d3a047f4)

**Comment by NicoMaio** [comment]
The "Load Ports" button will not be added again.
