### ISSUE TITLE
Add Source Interface ID to Flows and Hosts in View Interfaces

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#7973]
When using a view (e.g. -i view:all) interface to aggregate multiple packet or ZMQ interfaces, there is no info about the interface(s) where a specific flow or host has been seen. It is required to add the interface ID of the source interfaces in the flow/host and show them in the flow/host details page. Showing up to 2 interface IDs is enough (and add a note in case of more).

E.g.: 
- Seen on interface: X
- Seen on interface: X, Y
- Seen on interface: X, Y and others

**Comment by MatteoBiscosi** [comment]
Implemented as requested
