### ISSUE TITLE
Edit Recipient for Traffic Report shows alert fields

### ISSUE THREAD

**Issue by mzac** [ntop/ntopng#7978]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04
* Architecture: amd64
* ntopng version/revision: 6.0.231102

**What happened**:
When editing a recipient that was set for 'Report', the fields for 'Alert' are displayed.

![image](https://github.com/ntop/ntopng/assets/10270879/8bca83fe-bd0c-4345-85bd-e6a518d9cde1)

**How did you reproduce it?**
Edit recipient for report.  If you choose Alert and then Traffic Report then the fields dissapear.  This might confuse people.

**Comment by MatteoBiscosi** [comment]
Hi @mzac thanks a lot for your report, I pushed the fix right now, in a couple of hours a new build should be available

**Comment by mzac** [comment]
@MatteoBiscosi It looks good now thanks!

**Comment by MatteoBiscosi** [comment]
Verified as fixed
