### ISSUE TITLE
ntopng service stops every few minutes on NST 24

### ISSUE THREAD

**Issue by fkamal1** [ntop/ntopng#798]
ntopng service stops after random number of minutes every time. Here is the startup line:

Version 2.5.160702 - Community Edition
Platform    x86_64-unknown-linux-gnu [x86_64][NST release 24 (NST24)] - 64 bit
Startup Line    ntopng --interface "enp0s20u9" --interface "eno1" --https-port "3001" --http-port "0" --local-networks "inserted several subnets here" --data-dir "/var/nst/ntopng" --dns-mode "1" --disable-autologout "" --sticky-hosts "none"

This was working fine with NST 22 but recently updated to NST 24. ntopng runs fine while the service is running and no issues when browsing the web interface. After few minutes, sometimes hours, the service crashes. Please let me know what logs or output you need to troubleshoot this.
Thanks you.

**Comment by emanuele-f** [comment]
Can you provide a core dump of the ntopng? Can you test latest version from git?

**Comment by emanuele-f** [comment]
Are you building from source? It is important to update to the latest version in order to give us useful information, thank you

**Comment by lucaderi** [comment]
Closed for inactivity. Will reopen if necessary.
