### ISSUE TITLE
[VS] port scan input mask issues

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#7980]
**Environment**:
* OS name:  Ubuntu
* OS version: 22.04
* Architecture: amd64
* ntopng version/revision: [ntopng Enterprise L v.6.1.231102 (Ubuntu 22.04.3 LTS) ](https://www.ntop.org/products/traffic-analysis/ntop/)|

**What happened**:
Adding a port range e.g. 1-1024 does not work for TCP (it works for a single port)
<img width="795" alt="Screenshot 2023-11-02 at 21 47 43" src="https://github.com/ntop/ntopng/assets/38549755/932ad3d0-fb1e-49b2-b0a0-c82534feaff4">

UDP port scan not working for any input:

<img width="782" alt="Screenshot 2023-11-02 at 21 55 41" src="https://github.com/ntop/ntopng/assets/38549755/583cc9a7-a12d-49b6-af41-c8a39e0522e1">

**How did you reproduce it?**

**Debug Information**:

**Comment by NicoMaio** [comment]
Currently, the VS is working correctly when specifying a port range.

**Comment by MatteoBiscosi** [comment]
Verified as fixed
