### ISSUE TITLE
No  Vulnerability Scan type?

### ISSUE THREAD

**Issue by deanfourie1** [ntop/ntopng#7981]
**Environment**:
* OS name: [e.g. Ubuntu] - **FreeBSD 14.0 [amd64] - 64 bit**
* OS version: [e.g. 18.04] - **FreeBSD 14.0 [amd64] - 64 bit**
* Architecture: [e.g. amd64] - **FreeBSD 14.0 [amd64] - 64 bit**
* ntopng version/revision: [e.g. 5.1.211223]  - **ntopng Community v.6.1.231102 rev.22046 (FreeBSD 14.0)** 

**What happened**:
There is no option for Vulnerability scan in the menu.
When navigating to the Vulnerability scan URL, I dont get the option for any scan types.

![image](https://github.com/ntop/ntopng/assets/71812804/8e1c1a89-b034-46c4-a701-41f4f6cf8029)

**How did you reproduce it?**
Just latest install of ntopng from repo.

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @deanfourie1 yes, we know about this issue with FreeBSD, we are working on it

**Comment by deanfourie1** [comment]
Great thanks

**Comment by n0w33d** [comment]
It is March 2024 and I am still seeing this issue on my OPNsense OS. Any update on progress or how we can fix this ourselves? Manually installing nmap on the host FreeBSD OS does not correct this.

**Comment by NicoMaio** [comment]
Hi @n0w33d,
what's your ntopng version?

**Comment by NicoMaio** [comment]
Hi @deanfourie1,
I'm trying to reproduce this issue, but it's working well. Could you please update to the latest ntopng version and try again?

**Comment by deanfourie1** [comment]
This is what I get when I try to update?

```
New packages to be INSTALLED:
        groff: 1.23.0_3 [FreeBSD]
        hidapi: 0.14.0 [FreeBSD]
        mysql80-client: 8.0.35 [FreeBSD]
        psutils: 1.17_6 [FreeBSD]

Installed packages to be UPGRADED:
        ntopng: 6.1.231102 -> 6.0.d20240307,1 [FreeBSD]

Number of packages to be installed: 4
Number of packages to be upgraded: 1

The process will require 22 MiB more space.
14 MiB to be downloaded.

Proceed with this action? [y/N]:
```

Just confirming this is an update and not a downgrade?

**Comment by n0w33d** [comment]
> Hi @n0w33d, what's your ntopng version?

Hello. My OPNsense is updated to the latest firmware version and the repo that it pulls from is stating I'm running ntop-ng on version 1.3, the actual ntop version is v6

![image](https://github.com/ntop/ntopng/assets/106119998/123e3760-3489-414e-b50e-7f76db7bd919)

**Comment by lucaderi** [comment]
@NicoMaio Please assist

**Comment by n0w33d** [comment]
Additional information and screen shots of my ntop-ng application dashboard.

Host OS: FreeBSD 13.2-RELEASE-p10
Host distribution: OPNsense 24.1.4-amd64
ntop version: ntopng Community v.6.0.240320 rev.0 (FreeBSD 13.2)

![image](https://github.com/ntop/ntopng/assets/106119998/c88f304f-6c3a-426e-9535-3d52ccb247e0)


![image](https://github.com/ntop/ntopng/assets/106119998/070100f4-94e5-4bbc-bcb9-b80784df8c9f)

**Comment by n0w33d** [comment]
I have installed nmap manually and can run vulscan as well within the OS console, but i cannot get the ntop-ng GUI to give me anything no matter if nmap and vulscan are installed or not.

**Comment by deanfourie1** [comment]
FYI, I  no longer even have the option to start a scan and choose a scan type?

I cant get to the screen in the screenshot above? The vulnerability scan option is gone completely.

**Comment by NicoMaio** [comment]
Hi @n0w33d and @deanfourie1,
I tested the vulnerability scan using ntopng Enterprise L v.6.1.240320 rev.23126 on FreeBSD 14.0, and it performed well. Therefore, please utilize the official ntopng versions available for download at: https://packages.ntop.org/FreeBSD/

**Comment by deanfourie1** [comment]
Is this an enterprise feature only?

**Comment by NicoMaio** [comment]
According to the doc (https://www.ntop.org/guides/ntopng/vulnerability_scan/index.html), this feature is also available on the community edition but with some limitations.

**Comment by deanfourie1** [comment]
Thanks,

I am running on FreeBSD alongside pfSense. Installed separately to pfSense via CLI.

Could you guide me through upgrading as I am a little less capable on FreeBSD.

Thanks

**Comment by n0w33d** [comment]
> Thanks,
> 
> I am running on FreeBSD alongside pfSense. Installed separately to pfSense via CLI.
> 
> Could you guide me through upgrading as I am a little less capable on FreeBSD.
> 
> Thanks

pfSense does not have a package manager so you must seek instructions from their forum elsewhere or use OPNsense instead.

**Comment by deanfourie1** [comment]
Version shown below, and still I do not see a Vulnerability Scan option.

I can see all the settings for it though.

![image](https://github.com/ntop/ntopng/assets/71812804/8521a932-2954-4b3d-ae23-a99348e36749)

**Comment by n0w33d** [comment]
I manually install nmap and vulscan, then rebooted. Now I see the Vulnerability Scan module page with options to make scans, but for some reason I see 11 scans running that do not exist. I am unable to remove these erroneous scans. 

![image](https://github.com/ntop/ntopng/assets/106119998/983c425b-17b8-425d-b696-a8a585cf8281)

**Comment by NicoMaio** [comment]
> I manually install nmap and vulscan, then rebooted. Now I see the Vulnerability Scan module page with options to make scans, but for some reason I see 11 scans running that do not exist. I am unable to remove these erroneous scans.
> 
> ![image](https://private-user-images.githubusercontent.com/106119998/320061850-983c425b-17b8-425d-b696-a8a585cf8281.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NDI3NjcsIm5iZiI6MTcxMjc0MjQ2NywicGF0aCI6Ii8xMDYxMTk5OTgvMzIwMDYxODUwLTk4M2M0MjViLTE3YjgtNDI1ZC1iNjk2LWE4YTU4NWNmODI4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwOTQ3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjY5ODk5ZDUyYTlmMTZkMDAzYWFiYzEyMWZmZDEyZTI5NmI0N2ViNjk2YzhlZjNhMGQwOTk4MDhkMDYyZDI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BpmXLe8YmeqJnRGOb2FmiNqpa4nXZVKTPnN9QXuGf2M)

This is strange, try to find out the nmap process on your machine with `ps ax | grep nmap` and in case kill them with the -9 option.

**Comment by deanfourie1** [comment]
> Version shown below, and still I do not see a Vulnerability Scan option.
> 
> I can see all the settings for it though.
> 
> ![image](https://private-user-images.githubusercontent.com/71812804/319968719-8521a932-2954-4b3d-ae23-a99348e36749.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3ODQ1MzQsIm5iZiI6MTcxMjc4NDIzNCwicGF0aCI6Ii83MTgxMjgwNC8zMTk5Njg3MTktODUyMWE5MzItMjk1NC00YjNkLWFlMjMtYTk5MzQ4ZTM2NzQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDIxMjM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NTJkYmI5ZDYwNzdjYWUxZTg4ODVjNTY1OTFiNmJmOGI2ZDdhNDAzYmIwNjlkODU4NWI4Zjg5MDQ4ODkwOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.alvXYzqEyfbJZfRXNO1QUCARYMScX-hCu3MnWDgOa0I)

Still waiting for a fix on this.

**Comment by ayeifry** [comment]
Any update on this issue with ntop-ng and opnsense? not showing "Scan Type" options?

**Comment by n0w33d** [comment]
The latest update labeled "ntopng Community v.6.1.240408 rev.23196 (FreeBSD 13.1)" fixed this issue for me.

**Comment by deanfourie1** [comment]
Again, updated to latest version and still no option to scan.

![image](https://github.com/ntop/ntopng/assets/71812804/ef281523-8e8d-4d38-8f1a-f286e588290c)

**Comment by NicoMaio** [comment]
> Again, updated to latest version and still no option to scan.
> 
> ![image](https://private-user-images.githubusercontent.com/71812804/322733905-ef281523-8e8d-4d38-8f1a-f286e588290c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTQ1NjAsIm5iZiI6MTcxMzUxNDI2MCwicGF0aCI6Ii83MTgxMjgwNC8zMjI3MzM5MDUtZWYyODE1MjMtOGU4ZC00ZDM4LThmMWEtZjI4NmU1ODgyOTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA4MTEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNGY3NzNlMTIyYmJjMjJkN2I2NWIxODQ4OTZhYmQzZWUxZDU3YzBjZDg3MTg4NjMwZDdlMjc0ZWQyNDM5N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zk1kA9v5S93i5KwQsI_TbECKgXw7XqeM8OOIdHgqd10)

This statement is only possible when nmap is not found in the following file system paths:

"/usr/bin/nmap"
"/usr/local/bin/nmap"
"/opt/homebrew/bin/nmap"

or when the nmap scripts are not found in the following file system paths:

"/usr/share/nmap/scripts/"
"/opt/homebrew/share/nmap/scripts/vulscan/"
"/usr/local/share/nmap/scripts/vulscan"

**Comment by n0w33d** [comment]
Manually installing nmap and vulscan, as well as updating ntop-ng likely fixed my issues.

**Comment by deanfourie1** [comment]
> > Again, updated to latest version and still no option to scan.
> > ![image](https://private-user-images.githubusercontent.com/71812804/322733905-ef281523-8e8d-4d38-8f1a-f286e588290c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTQ1NjAsIm5iZiI6MTcxMzUxNDI2MCwicGF0aCI6Ii83MTgxMjgwNC8zMjI3MzM5MDUtZWYyODE1MjMtOGU4ZC00ZDM4LThmMWEtZjI4NmU1ODgyOTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA4MTEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNGY3NzNlMTIyYmJjMjJkN2I2NWIxODQ4OTZhYmQzZWUxZDU3YzBjZDg3MTg4NjMwZDdlMjc0ZWQyNDM5N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zk1kA9v5S93i5KwQsI_TbECKgXw7XqeM8OOIdHgqd10)
> 
> This statement is only possible when nmap is not found in the following file system paths:
> 
> "/usr/bin/nmap" "/usr/local/bin/nmap" "/opt/homebrew/bin/nmap"
> 
> or when the nmap scripts are not found in the following file system paths:
> 
> "/usr/share/nmap/scripts/" "/opt/homebrew/share/nmap/scripts/vulscan/" "/usr/local/share/nmap/scripts/vulscan"

Thank you! Finally this is resolved.

**Comment by NicoMaio** [comment]
Verified as fixed.
