### ISSUE TITLE
Looking for support for our non-profit org

### ISSUE THREAD

**Issue by lupael** [ntop/ntopng#7983]
We have a virtual machine in Microsoft Azure, we need help to install your software in this virtual machine.

**We Want to monitor and secure remote host from Coud VM**. We use Mikrotik router and router has public IP.

**We have the following free license for our non-profit organizations**:
1 x "ntopng Enterprise XL Bundle Linux (x64)"
1 x "nScrub XL [Linux]"
1 x "PF_RING ZC - Intel/Mellanox 10/40/100 Gbit [Linux]":

**Comment by cardigliano** [comment]
@lupael please contact my colleague Maria (I guess she gave you the free licenses) to get a quote for the support time. Thank you.
