### ISSUE TITLE
Manage Configurations page not available

### ISSUE THREAD

**Issue by dimalev01** [ntop/ntopng#7984]
Hello ,

We have next output on Manage Configurations page:

HTTP/1.1 302 Found Server: ntopng 5.3.220620 (x86_64) Set-Cookie: session=37e83e693496913bba61703a5e31bea3; path=/; HttpOnly; SameSite=lax; Secure Location: /lua/http_status_code.lua?message=internal_error&referer=192.168.10.13%2Flua%2Fadmin%2Fmanage_configurations.lua&error_message=%5Bstring%20%22context%3D...%20or%20%7B%7D...%22%5D%3A132%3A%20attempt%20to%20index%20a%20nil%20value%20%28global%20%27info%27%29 [string "context=... or {}..."]:132: attempt to index a nil value (global 'info')

What is the issue here , and hot to fix it?

Br,

Dima Lev.

**Comment by MatteoBiscosi** [comment]
Hi @dimalev01 please update to the latest ntopng version (6.1 or 6.0) or we cannot help you

**Comment by dimalev01** [comment]
Hi @MatteoBiscosi 

Do I need to update all versions step by step till version 6.0 or I can do it directly?

**Comment by MatteoBiscosi** [comment]
You can directly update to the latest version

**Comment by NicoMaio** [comment]
Verified as fixed
