### ISSUE TITLE
Historical Flows

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7990]
At the moment all flows are reported on the page, and what we can do is filter exporters which is cumbersome when switching across exporters.

Enable easy navigation across flow exporters. A possible (but not the only solution) is to add a new drop-down menu
<img width="461" alt="Screenshot 2023-11-07 at 10 34 49" src="https://github.com/ntop/ntopng/assets/4493366/b14bb8ba-07f6-4c8f-9776-261d43e377a3">

but in this case we also have to filter per exporter interface.

**Comment by MatteoBiscosi** [comment]
Implemented as requested

**Comment by lucaderi** [comment]
Verified as fixed
