### ISSUE TITLE
Local traffic Rules: Flow Export Devices

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7991]
<img width="559" alt="Screenshot 2023-11-07 at 10 36 06" src="https://github.com/ntop/ntopng/assets/4493366/4d26a81e-e048-4c8b-9b9b-12e652ba1a40">

Issues
- check what is "no ifId"
- add the ability of setting * as flow exporter and interfaceId
- Rename the metric Percentage in "Volume Percentage"

Only for the flow/exporter tab
- add a new metric called "Utilisation Percentage" that triggers an alert based on the interface throughput (computed via SNMP). This is triggered based on the timeseries described in #7993

**Comment by NicoMaio** [comment]
Fixed also in the pro repo by 8f09a907effb8a8ea096cb68493b086ba118a216

**Comment by MatteoBiscosi** [comment]
Implemented as requested
