### ISSUE TITLE
Various Blacklist Chart Bugs

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7995]
From the blacklist page click on the chart that will bring you to the page below

<img width="1371" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/a7c07181-ece0-46f8-b2d0-405839b5e05c">

Various bugs
- missing blacklist name
- the timeseries (checked with rrdtool) contains the correct time, but this chart is shifted -1 hour. It seems that the reported time is in UTC and not in the local timezone. 
1699377000: 0,0000000000e+00
1699377300: 0,0000000000e+00
1699377600: 0,0000000000e+00
1699377900: 0,0000000000e+00
1699378200: 0,0000000000e+00
1699378500: 3,3222591362e-03
1699378800: 3,3444075305e-03
1699379100: 0,0000000000e+00
1699379400: 3,3222591362e-03
- the total value is wrong
- the blacklist dropdown menu does not list the other blacklists
- the top value is 3 but on the Y axis it is depicted as 3.8 
- on the Y axis the unit (host hits/sec) is missing

**Comment by lucaderi** [comment]
In the latest build the charts are completely broken
<img width="981" alt="Screenshot 2023-11-10 at 09 44 45" src="https://github.com/ntop/ntopng/assets/4493366/f7adb756-14b1-4a1b-a3ff-d4d7d988eb7b">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
