### ISSUE TITLE
Invalid Flow Exporter Mapping

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7999]
When SNMP/DNS is enabled, flow exporter devices are mapped to names

<img width="138" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/8e90a2fb-75d3-4331-811c-465c85cee0e6">

clicking on it will jump to a page with no selected exporter probably because of the name resolution that does not match the name

<img width="794" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/9a620167-0dc1-4c14-a25e-6ecd1a5f2d4e">

**Comment by lucaderi** [comment]
Same bug also with other columns

<img width="409" alt="Screenshot 2023-11-10 at 09 42 34" src="https://github.com/ntop/ntopng/assets/4493366/ef9d3740-1b20-4598-8c88-2446505e9df2">

**Comment by cardigliano** [comment]
Fixed in 3ad079a6b556088ee2878af700e25a4534035c76

**Comment by MatteoBiscosi** [comment]
Verified as fixed
