### ISSUE TITLE
-B filter statement causes error if statement > 512 Bytes

### ISSUE THREAD

**Issue by JuergenWeber** [ntop/ntopng#80]
We're running a NTOPNG box at the border LAN/WAN and we're filtering out all local IP networks. This makes the filter statement looong.
I get the following error if the -B filter statement exceeds 512 Bytes:  [src/PcapInterface.cpp:221] ERROR: Unable to set filter ip && !(ip multicast ........... || dst net 10.187.128.0/24 ||. Filter ignored.
Version: 2.0.150611

**Comment by ariava** [comment]
@JuergenWeber could you please provide a sample filter statement that triggers the issue?

**Comment by lucaderi** [comment]
@JuergenWeber Does tcpdump accepts your filter?

**Comment by JuergenWeber** [comment]
Yes, it does.
Here's the real world example which works in NTOP- - but works in TCPDUMP
-B=ip && !(ip multicast || ether broadcast) && !((src net 10.187.112.0/22 
|| src net 10.187.125.0/24 || src net 10.186.59.0/24 || src net 
10.186.102.0/24 || src net 10.187.127.0/24 || src net 10.187.126.0/24 || 
src net 10.187.128.0/24 || src net 10.161.254.0/24 || src net 
10.161.252.128/25 || src net 10.161.139.0/24) && (dst net 10.187.112.0/22 
|| dst net 10.187.125.0/24 || dst net 10.186.59.0/24 || dst net 
10.186.102.0/24 || dst net 10.187.127.0/24 || dst net 10.187.126.0/24 || 
dst net 10.187.128.0/24))

This doesn't work in NTOP - but works in TCPDUMP
#-B=ip && !(ip multicast || ether broadcast) && !((src net 10.187.112.0/22 
|| src net 10.187.125.0/24 || src net 10.186.59.0/24 || src net 
10.186.102.0/24 || src net 10.187.127.0/24 || src net 10.187.126.0/24 || 
src net 10.187.128.0/24 || src net 10.161.254.0/24 || src net 
10.161.252.128/25 || src net 10.161.139.0/24) && (dst net 10.187.112.0/22 
|| dst net 10.187.125.0/24 || dst net 10.186.59.0/24 || dst net 
10.186.102.0/24 || dst net 10.187.127.0/24 || dst net 10.187.126.0/24 || 
dst net 10.187.128.0/24 || dst net 10.161.254.0/24 || dst net 
10.161.252.128/25 || dst net 10.161.139.0/24))


Regards,

Juergen

**Comment by lucaderi** [comment]
@JuergenWeber On what interface did you set this on ntopng? What is the -i interface you set? Note that BPF filters cannot be set for all interfaces. For instance the loopback interface accepts filters different than the ethernet interface. Please provide the complete log.

**Comment by lucaderi** [comment]
Fixed on https://github.com/ntop/ntopng/commit/ebdcfc4d869db7b3b8fb09786df85eaaa7af2912. Again note that not all interfaces support the same BPF filter.

**Comment by JuergenWeber** [comment]
--interface eth1

**Comment by JuergenWeber** [comment]
-G=/var/tmp/ntopng.pid
# tells ntop the user id to run as
--user ntop5

#save messages into the system log
--use-syslog=daemon

# sets the directory that ntop runs from
--db-file-path /var/lib/ntop

# --data-dir=/var/tmp/ntopng

# the amount and severity of messages that ntop will put out
--trace-level 0

# limit ntop to listening on a specific interface and port
--http-port=3003
#--https-port=3001

# disables "phone home" behaviour
--skip-version-check

### Set the protocol list (name and ports to be monitored)
-p=/etc/ntopng/protos.txt


### Interface(s) that ntop will capture on (default: eth0)
--interface eth1

--no-interface-merge

--dns-mode=1
### Logging messages to syslog (instead of the console):
####  NOTE: To log to a specific facility, use --use-syslog=local3
####  NOTE: The = is REQUIRED and no spaces are permitted.
--use-syslog=local3

### Sets program to run as a daemon
--daemon

-e

#verbose
#-v
--disable-login=1

# 0 - No aggregations (default)
# 1 - Enable aggregations, no timeline dump
# 2 - Enable aggregations, with timeline
--enable-aggregations=2

# enable historical data
-F=db

-m=10.187.112.0/22,10.187.125.0/24,10.186.59.0/24,10.186.102.0/24,10.187.127.0/24,10.187.126.0/24,10.187.128.0/24,10.161.254.0/24,10.161.252.128/25,10.161.139.0/24
-B=ip && !(ip multicast || ether broadcast) && !((src net 10.187.112.0/22 || src net 10.187.125.0/24 || src net 10.186.59.0/24 || src net 10.186.102.0/24 || src net 10.187.127.0/24 || src net 10.187.126.0/24 || src net 10.187.128.0/24 || src net 10.161.254.0/24 || src net 10.161.252.128/25 || src net 10.161.139.0/24) && (dst net 10.187.112.0/22 || dst net 10.187.125.0/24 || dst net 10.186.59.0/24 || dst net 10.186.102.0/24 || dst net 10.187.127.0/24 || dst net 10.187.126.0/24 || dst net 10.187.128.0/24))
#-B=ip && !(ip multicast || ether broadcast) && !((src net 10.187.112.0/22 || src net 10.187.125.0/24 || src net 10.186.59.0/24 || src net 10.186.102.0/24 || src net 10.187.127.0/24 || src net 10.187.126.0/24 || src net 10.187.128.0/24 || src net 10.161.254.0/24 || src net 10.161.252.128/25 || src net 10.161.139.0/24) && (dst net 10.187.112.0/22 || dst net 10.187.125.0/24 || dst net 10.186.59.0/24 || dst net 10.186.102.0/24 || dst net 10.187.127.0/24 || dst net 10.187.126.0/24 || dst net 10.187.128.0/24 || dst net 10.161.254.0/24 || dst net 10.161.252.128/25 || dst net 10.161.139.0/24))
