### ISSUE TITLE
Missing Home Icon

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8001]
Inside the VLAN page, when clicking on a VLAN and then on the wheel icon to set its symbolic name, there is not home icon in the header to jump back to the VLAN list page
<img width="293" alt="Screenshot 2023-11-09 at 09 38 44" src="https://github.com/ntop/ntopng/assets/4493366/abb91c1c-ca17-49f1-bb33-294bd0819134">

**Comment by lucaderi** [comment]
The fix is working but VLAN 0 does not exist: please fix it
<img width="443" alt="Screenshot 2023-11-10 at 09 39 48" src="https://github.com/ntop/ntopng/assets/4493366/c6e50e32-cb24-4210-8001-a37a5477accb">
<img width="322" alt="Screenshot 2023-11-10 at 09 39 40" src="https://github.com/ntop/ntopng/assets/4493366/b1357517-6c76-44bf-a5d6-dd1df8ff3c8d">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
