### ISSUE TITLE
Empty Flow Exporter Timeseries

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8003]
Clicking on the chart
<img width="444" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/fde9c902-247a-43e9-9694-97308cef7064">

The timeseries are empty (although enabled in preferences)
<img width="785" alt="Screenshot 2023-11-09 at 10 00 52" src="https://github.com/ntop/ntopng/assets/4493366/cbca1c73-0005-462e-8f51-c689ae7459d9">

**Comment by lucaderi** [comment]
<img width="827" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/ce78bbe4-d29d-485c-8243-3272b6b64467">
<img width="784" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/3ca75376-bc99-46ac-b198-f3dc4747405f">

Still broken

**Comment by MatteoBiscosi** [comment]
Verified as fixed
