### ISSUE TITLE
Improve CPU load chart

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8007]
The chart below is not easy to read at first glance. Please reorder is as follows
- active first
- iowait
- idle can be omitted as people do not understand it immediately or if you want leave it as last entry

<img width="1193" alt="Screenshot 2023-11-10 at 09 47 39" src="https://github.com/ntop/ntopng/assets/4493366/eb0ffe3b-4d2a-4c4c-a1ab-e482f25bb59d">

**Comment by MatteoBiscosi** [comment]
Implemented as requested
