### ISSUE TITLE
Invalid Flow Exporter Link

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8009]
The link in the picture below, should jump to SNMP as with sFlow and not back to the same page. 

<img width="557" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/957e601f-bcc5-40d0-8168-8bae6202dd42">

**Comment by NicoMaio** [comment]
Fixed in pro repo by 1d342a52991ec1ede826697655eeda0b7b9d0e18

**Comment by MatteoBiscosi** [comment]
Verified as fixed
