### ISSUE TITLE
Report MySQL slow response

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#801]
As of the latest MySQL it is possible to report slow queries for instance with the query below. It would be nice to ntopng alert users when this is the case and likely report slow queries

mysql> select \* from  events_statements_summary_by_digest order by MAX_TIMER_WAIT desc limit 1 \G
**************************\* 1. row ***************************
                SCHEMA_NAME: ntopng
                     DIGEST: 79669e73b0e9bcf17c7ebc9c5ba6b8de
                DIGEST_TEXT: SELECT COUNT ( \* ) AS `TOT_FLOWS` , SUM ( `IN_BYTES` + `OUT_BYTES` ) AS `TOT_BYTES` , SUM ( `PACKETS` ) AS `TOT_PACKETS` FROM `flowsv4` WHERE `FIRST_SWITCHED` <= ? AND `FIRST_SWITCHED` >= ? AND ( `NTOPNG_INSTANCE_NAME` = ? OR `NTOPNG_INSTANCE_NAME` IS NULL ) AND ( `INTERFACE_ID` = ? ) AND `L7_PROTO` = ? AND ( `IP_SRC_ADDR` = `INET_ATON` (?) OR `IP_DST_ADDR` = `INET_ATON` (?) )
                 COUNT_STAR: 37
             SUM_TIMER_WAIT: 2475543000000
             MIN_TIMER_WAIT: 22072000000
             AVG_TIMER_WAIT: 66906567000
             MAX_TIMER_WAIT: 471173000000
              SUM_LOCK_TIME: 10407000000
                 SUM_ERRORS: 0
               SUM_WARNINGS: 0
          SUM_ROWS_AFFECTED: 0
              SUM_ROWS_SENT: 37
          SUM_ROWS_EXAMINED: 817254
SUM_CREATED_TMP_DISK_TABLES: 0
     SUM_CREATED_TMP_TABLES: 0
       SUM_SELECT_FULL_JOIN: 0
 SUM_SELECT_FULL_RANGE_JOIN: 0
           SUM_SELECT_RANGE: 1
     SUM_SELECT_RANGE_CHECK: 0
            SUM_SELECT_SCAN: 34
      SUM_SORT_MERGE_PASSES: 0
             SUM_SORT_RANGE: 0
              SUM_SORT_ROWS: 0
              SUM_SORT_SCAN: 0
          SUM_NO_INDEX_USED: 34
     SUM_NO_GOOD_INDEX_USED: 0
                 FIRST_SEEN: 2016-10-26 16:11:04
                  LAST_SEEN: 2016-10-26 16:43:11
1 row in set (0.00 sec)

**Comment by simonemainardi** [comment]
database queries are now carried out asynchronously. The user is notified every time there's a slow query going on. Slow queries can be aborted as well and the interface is always responsive.

![image](https://cloud.githubusercontent.com/assets/3397663/19860158/03abf802-9f88-11e6-9875-524a80a20a78.png)
