### ISSUE TITLE
Add the ability to Specify the SNMP Interface speed

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8010]
Add the ability (in the wheel) to set a custom speed 

<img width="619" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/124d9c52-feb2-439e-b925-91093ec9d154">

as in interface details

<img width="1016" alt="Screenshot 2023-11-10 at 16 17 26" src="https://github.com/ntop/ntopng/assets/4493366/715b8de5-4ec5-461b-9c61-219a028a3bbc">

Also create a lua function that given (IP address and interfaceId) and returns the interface speed as follows
- if specified, use the custom speed
- if not, use the SNMP speed

**Comment by MatteoBiscosi** [comment]
Implemented as requested
