### ISSUE TITLE
[VS] Filtered ports not shown in overview

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#8012]
**Environment**:
* OS name: [e.g. Ubuntu] Ubuntu 22.04.3 LTS
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64] amd64
* ntopng version/revision: [e.g. 5.1.211223][ntopng Enterprise L v.6.1.231111 () 
**What happened**:
In the overview list filtered ports are not shown:
<img width="528" alt="Screenshot 2023-11-11 at 09 37 38" src="https://github.com/ntop/ntopng/assets/38549755/d9bd5fff-4329-4040-9aea-b2c251bedafc">

Scan result:

<img width="427" alt="Screenshot 2023-11-11 at 09 37 17" src="https://github.com/ntop/ntopng/assets/38549755/aca1a69f-baf3-40a9-96dd-7b3a96b2bcfa">

**How did you reproduce it?**

**Debug Information**:

**Comment by NicoMaio** [comment]
Hi @martinscheu,
To highlight filtered ports, we compare the results with http://localhost:3000/lua/host_details.lua?host=X.X.X.X&page=ports (found under the 'Ports' tab on the host details page). If ntopng, with passive monitoring, shows ports that aren't discovered by the VS, a filter icon will appear on the overview VS page. 
Please check the 'Ports' tab on the host details page for differences in the VS result and let me know.

**Comment by martinscheu** [comment]
Hi @NicoMaio 
Ok thanks. Then I dont understand why in the example above we see in the overview 3 found ports and in the scan report 6?
Because this is miss leading for me, as I think in the overview it would show me all ports found, regardless of filtered or open. This because I check hosts with many open ports first.

**Comment by NicoMaio** [comment]
Currently, the VS result is considering just the ports with the open state because the ports with the filtered state could be false positives.

**Comment by lucaderi** [comment]
Verified as fixed
