### ISSUE TITLE
Acknowledge (All) Alerts Button is Broken

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#8014]
The Acknowledge button used to acknowledge all alerts in the alert explorer table does just nothing when clicking on it. Please restore it.

<img width="535" alt="Screenshot 2023-11-13 at 10 31 57" src="https://github.com/ntop/ntopng/assets/7548711/edd5844e-dda0-4cbf-b980-db9a5dad96a2">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
