### ISSUE TITLE
Discord notifications fail

### ISSUE THREAD

**Issue by jepke** [ntop/ntopng#8016]
**Environment**:
* OS name: [Debian]
* OS version: [Bullseye]
* Architecture: [amd64]
* ntopng version/revision: [6.0.231110 [Enterprise/Professional build]] (likely hapened in 5.6 as well looking back at notification. Upgraded to 6.0 this morning and last notification is from a few weeks ago)

**What happened**:
Discord notifications fail with following error.

**How did you reproduce it?**

Fully deleted discord enpoint and recipient recreated them.

**Debug Information**:
journalctl -u ntopng is spamming the message below
```
13/Nov/2023 15:44:30 [LuaEngine.cpp:610] WARNING: ...scripts/lua/modules/notifications/endpoints//discord.lua:113: field 'formatAlertNotification' is not callable (a nil value)
```

**Comment by cardigliano** [comment]
Fixed in d6d3e0a829e17c6bb04b36fb140ec98db019966f

**Comment by cardigliano** [comment]
A software update will be available in 1h

**Comment by jepke** [comment]
@cardigliano thanks will wait - update - report back 👍

**Comment by jepke** [comment]
Confirmed notifications are flowing towards discord again

**Comment by vuanhson** [comment]
Discord notification is no problem on my side now!

**Comment by cardigliano** [comment]
Great, thank you
