### ISSUE TITLE
cannot access after reboot

### ISSUE THREAD

**Issue by lucadistefano** [ntop/ntopng#802]
we performed a reboot of box where ntopng is hosted
after reboot whe cannot access to frontend :
![image](https://cloud.githubusercontent.com/assets/1080723/19803348/79f35014-9d08-11e6-8235-12a57a92ec18.png)

we did no ntopng version upgrade, so I suppose there should be no schema update
the actual installed version is ntopng-2.5.160926-1584.x86_64

the logs :
redis.log:
....
[97228] 28 Oct 08:41:30 \* Background saving terminated with success
[97228] 28 Oct 08:42:31 \* 10000 changes in 60 seconds. Saving...
[97228] 28 Oct 08:42:31 \* Background saving started by pid 74153
[74153] 28 Oct 08:42:31 \* DB saved on disk
[97228] 28 Oct 08:42:31 \* Background saving terminated with success
[97228] 28 Oct 08:43:01 # Received SIGTERM, scheduling shutdown...
[97228] 28 Oct 08:43:01 # User requested shutdown...
[97228] 28 Oct 08:43:01 \* Saving the final RDB snapshot before exiting.
[97228] 28 Oct 08:43:01 \* DB saved on disk
[97228] 28 Oct 08:43:01 \* Removing the pid file.
[97228] 28 Oct 08:43:01 # Redis is now ready to exit, bye bye...
[4894] 28 Oct 08:46:00 \* Server started, Redis version 2.4.10
[4894] 28 Oct 08:46:00 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
[4894] 28 Oct 08:46:00 \* DB loaded from disk: 0 seconds
[4894] 28 Oct 08:46:00 \* The server is now ready to accept connections on port 6379

ntopng.log
28/Oct/2016 07:00:00 [Lua.cpp:5159] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/hourly.lua][...ng/pro/scripts/lua/modules/top_scripts/top_aggregate.lua:111: attempt to index a nil value]
28/Oct/2016 08:00:00 [Lua.cpp:5159] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/hourly.lua][...ng/pro/scripts/lua/modules/top_scripts/top_aggregate.lua:111: attempt to index a nil value]
28/Oct/2016 08:43:01 [Redis.cpp:61] Redis has disconnected: reconnecting...
28/Oct/2016 08:43:04 [main.cpp:43] Shutting down...
**28/Oct/2016 12:03:17 [Prefs.cpp:789] All HTTP user login disabled**
28/Oct/2016 12:03:17 [Ntop.cpp:1124] Setting local networks to 10.62.4.0/22,10.62.1.0/25
28/Oct/2016 12:03:17 [Redis.cpp:103] Successfully connected to redis 127.0.0.1:6379@0
28/Oct/2016 12:03:17 [NtopPro.cpp:123] [LICENSE] Reading license from /etc/ntopng.license
28/Oct/2016 12:03:17 [MySQLDB.cpp:595] Attempting to connect to MySQL for interface tcp://10.62.5.111:5552...
28/Oct/2016 12:03:17 [MySQLDB.cpp:635] Succesfully connected to MySQL [/data/ntopng/mysql/mysql.sock:ntopng] for interface tcp://10.62.5.111:5552
28/Oct/2016 12:03:18 [Ntop.cpp:1223] Registered interface tcp://10.62.5.111:5552 [id: 0]
28/Oct/2016 12:03:18 [MySQLDB.cpp:595] Attempting to connect to MySQL for interface tcp://10.62.5.111:5553...
28/Oct/2016 12:03:18 [MySQLDB.cpp:635] Succesfully connected to MySQL [/data/ntopng/mysql/mysql.sock:ntopng] for interface tcp://10.62.5.111:5553
28/Oct/2016 12:03:18 [Ntop.cpp:1223] Registered interface tcp://10.62.5.111:5553 [id: 1]
28/Oct/2016 12:03:18 [MySQLDB.cpp:595] Attempting to connect to MySQL for interface view:tcp://10.62.5.111:5552,tcp://10.62.5.111:5553...
28/Oct/2016 12:03:18 [MySQLDB.cpp:635] Succesfully connected to MySQL [/data/ntopng/mysql/mysql.sock:ntopng] for interface view:tcp://10.62.5.111:5552,tcp://10.62.5.111:5553
28/Oct/2016 12:03:18 [Ntop.cpp:1223] Registered interface view:tcp://10.62.5.111:5552,tcp://10.62.5.111:5553 [id: 2]
28/Oct/2016 12:03:18 [main.cpp:246] PID stored in file /var/tmp/ntopng.pid
28/Oct/2016 12:03:18 [HTTPserver.cpp:507] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
28/Oct/2016 12:03:18 [Utils.cpp:354] User changed to nobody
28/Oct/2016 12:03:18 [HTTPserver.cpp:552] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
28/Oct/2016 12:03:18 [HTTPserver.cpp:555] HTTP server listening on port 3001
28/Oct/2016 12:03:18 [MySQLDB.cpp:595] Attempting to connect to MySQL for interface tcp://10.62.5.111:5552...
28/Oct/2016 12:03:18 [MySQLDB.cpp:635] Succesfully connected to MySQL [/data/ntopng/mysql/mysql.sock:ntopng] for interface tcp://10.62.5.111:5552

strange is the message of ntopng < All HTTP user login disabled >
how can I access again to frontend?

thanks
Luca

**Comment by simonemainardi** [comment]
```
28/Oct/2016 12:03:17 [Prefs.cpp:789] All HTTP user login disabled
```

means that you have used option `-l 1` during startup:

```
[--disable-login|-l] <mode>         | Disable user login authentication:
                                    | 0 - Disable login only for localhost
                                    | 1 - Disable login only for all hosts
```

So if this is not the expected behaviour, maybe you think you are using an ntopng while you are actually using another version/instance... please check that out... this could also explain why you are getting a mysql schema update message. In addition, when a schema update takes place, you also get update messages in the command line and those messages are not shown in the output you enclosed.

**Comment by lucadistefano** [comment]
hi,

the problem occurred because mysql started a repair process on flows4 table, therefore ntopng has no access to the table and tries to recreate it and hangs on waiting the repair completion.

thanks Simone for the prompt help!
