### ISSUE TITLE
Retention not working

### ISSUE THREAD

**Issue by seaperse** [ntop/ntopng#8021]
**Environment**:
NAME="Rocky Linux"
VERSION="8.8 (Green Obsidian)"
Architecture: x86-64
ntopng Enterprise L v.6.1.231115 rev.22190 (Rocky Linux release 8.8) 

What happened:
Data retention being not honored and disk is almost full

How did you reproduce it?

Debug Information:

Paste debug information below:
]# systemctl status ntopng
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/usr/lib/systemd/system/ntopng.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2023-11-15 11:24:32 EET; 19min ago
 Main PID: 6840 (ntopng-main)
    Tasks: 36 (limit: 113559)
   Memory: 3.1G
   CGroup: /system.slice/ntopng.service
           └─6840 /usr/bin/ntopng /run/ntopng.conf

Nov 15 11:42:00 ntop.domain.com callbacks/minute/interface/test.lua:1: module 'user_scripts' not found:
Nov 15 11:42:00 ntop.domain.com ntopng[6840]: 15/Nov/2023 11:42:00 [LuaEngine.cpp:649] WARNING: ...share/ntopng/scripts/callbacks/minute/interface/test.lua:1: module 'user_scripts' not found:
Nov 15 11:43:00 ntop.domain.com ntopng[6840]: 15/Nov/2023 11:43:00 [LuaEngine.cpp:442] WARNING: Script failure [script: user_scripts][path: ][cur-path: /usr/local/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?/init.lua;/usr/local/lib/lua/5.4/?.lua;/usr/local/lib/lua/5.4>
Nov 15 11:43:00 ntop.domain.com ntopng[6840]: 15/Nov/2023 11:43:00 [LuaEngine.cpp:442] WARNING: Script failure [script: user_scripts][path: ][cur-path: /usr/local/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?/init.lua;/usr/local/lib/lua/5.4/?.lua;/usr/local/lib/lua/5.4>
Nov 15 11:43:00 ntop.domain.com ntopng[6840]: 15/Nov/2023 11:43:00 [LuaEngine.cpp:649] WARNING: ...share/ntopng/scripts/callbacks/minute/interface/test.lua:1: module 'user_scripts' not found:
Nov 15 11:43:00 ntop.domain.com ntopng[6840]: 15/Nov/2023 11:43:00 [LuaEngine.cpp:649] WARNING: ...share/ntopng/scripts/callbacks/minute/interface/test.lua:1: module 'user_scripts' not found:
Nov 15 11:44:00 ntop.domain.com ntopng[6840]: 15/Nov/2023 11:44:00 [LuaEngine.cpp:442] WARNING: Script failure [script: user_scripts][path: ][cur-path: /usr/local/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?/init.lua;/usr/local/lib/lua/5.4/?.lua;/usr/local/lib/lua/5.4>
Nov 15 11:44:00 ntop.domain.com ntopng[6840]: 15/Nov/2023 11:44:00 [LuaEngine.cpp:442] WARNING: Script failure [script: user_scripts][path: ][cur-path: /usr/local/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?/init.lua;/usr/local/lib/lua/5.4/?.lua;/usr/local/lib/lua/5.4>
Nov 15 11:44:00 ntop.domain.com ntopng[6840]: 15/Nov/2023 11:44:00 [LuaEngine.cpp:649] WARNING: ...share/ntopng/scripts/callbacks/minute/interface/test.lua:1: module 'user_scripts' not found:
Nov 15 11:44:00 ntop.domain.com ntopng[6840]: 15/Nov/2023 11:44:00 [LuaEngine.cpp:649] WARNING: ...share/ntopng/scripts/callbacks/minute/interface/test.lua:1: module 'user_scripts' not found:

- Grab a screenshot from the GUI demonstrating the issue.
- 
![Screenshot 2023-11-15 114557](https://github.com/ntop/ntopng/assets/140824574/7d38c307-6cb0-48d5-9efc-04525c5d8de9)

- Provide a PCAP when this is required to reproduce the issue.

Below it says that the flows are 100 days old, but the retention period is 90 days.
Earlier restarting the ntopng service has helped, but not this time.

ntop.domain.com :) SELECT DISTINCT database, table, partition drop_part FROM system.parts WHERE active AND database='ntopng';

SELECT DISTINCT
    database,
    table,
    partition AS drop_part
FROM system.parts
WHERE active AND (database = 'ntopng')

Query id: 64a4f489-40b5-45d9-9e49-5256f570921e

┌─database─┬─table────────────────────┬─drop_part─┐
│ ntopng   │ active_monitoring_alerts │ 20231106  │
│ ntopng   │ active_monitoring_alerts │ 20231110  │
│ ntopng   │ active_monitoring_alerts │ 20231115  │
│ ntopng   │ alert_severities         │ tuple()   │
│ ntopng   │ flow_risks               │ tuple()   │
│ ntopng   │ flows                    │ 20230808  │
│ ntopng   │ flows                    │ 20230809  │
│ ntopng   │ flows                    │ 20230810  │
│ ntopng   │ flows                    │ 20230811  │
│ ntopng   │ flows                    │ 20230812  │
│ ntopng   │ flows                    │ 20230813  │
│ ntopng   │ flows                    │ 20230814  │
│ ntopng   │ flows                    │ 20230815  │
│ ntopng   │ flows                    │ 20230816  │
│ ntopng   │ flows                    │ 20230817  │
│ ntopng   │ flows                    │ 20230818  │
│ ntopng   │ flows                    │ 20230819  │
│ ntopng   │ flows                    │ 20230820  │
│ ntopng   │ flows                    │ 20230821  │
│ ntopng   │ flows                    │ 20230822  │
│ ntopng   │ flows                    │ 20230823  │
│ ntopng   │ flows                    │ 20230824  │
│ ntopng   │ flows                    │ 20230825  │
│ ntopng   │ flows                    │ 20230826  │
│ ntopng   │ flows                    │ 20230827  │
│ ntopng   │ flows                    │ 20230828  │
│ ntopng   │ flows                    │ 20230829  │
│ ntopng   │ flows                    │ 20230830  │
│ ntopng   │ flows                    │ 20230831  │
│ ntopng   │ flows                    │ 20230901  │
│ ntopng   │ flows                    │ 20230902  │
│ ntopng   │ flows                    │ 20230903  │
│ ntopng   │ flows                    │ 20230904  │
│ ntopng   │ flows                    │ 20230905  │
│ ntopng   │ flows                    │ 20230906  │
│ ntopng   │ flows                    │ 20230907  │
│ ntopng   │ flows                    │ 20230908  │
│ ntopng   │ flows                    │ 20230909  │
│ ntopng   │ flows                    │ 20230910  │
│ ntopng   │ flows                    │ 20230911  │
│ ntopng   │ flows                    │ 20230912  │
│ ntopng   │ flows                    │ 20230913  │
│ ntopng   │ flows                    │ 20230914  │
│ ntopng   │ flows                    │ 20230915  │
│ ntopng   │ flows                    │ 20230916  │
│ ntopng   │ flows                    │ 20230917  │
│ ntopng   │ flows                    │ 20230918  │
│ ntopng   │ flows                    │ 20230919  │
│ ntopng   │ flows                    │ 20230920  │
│ ntopng   │ flows                    │ 20230921  │
│ ntopng   │ flows                    │ 20230922  │
│ ntopng   │ flows                    │ 20230923  │
│ ntopng   │ flows                    │ 20230924  │
│ ntopng   │ flows                    │ 20230925  │
│ ntopng   │ flows                    │ 20230926  │
│ ntopng   │ flows                    │ 20230927  │
│ ntopng   │ flows                    │ 20230928  │
│ ntopng   │ flows                    │ 20230929  │
│ ntopng   │ flows                    │ 20230930  │
│ ntopng   │ flows                    │ 20231001  │
│ ntopng   │ flows                    │ 20231002  │
│ ntopng   │ flows                    │ 20231003  │
│ ntopng   │ flows                    │ 20231004  │
│ ntopng   │ flows                    │ 20231005  │
│ ntopng   │ flows                    │ 20231006  │
│ ntopng   │ flows                    │ 20231007  │
│ ntopng   │ flows                    │ 20231008  │
│ ntopng   │ flows                    │ 20231009  │
│ ntopng   │ flows                    │ 20231010  │
│ ntopng   │ flows                    │ 20231011  │
│ ntopng   │ flows                    │ 20231012  │
│ ntopng   │ flows                    │ 20231013  │
│ ntopng   │ flows                    │ 20231014  │
│ ntopng   │ flows                    │ 20231015  │
│ ntopng   │ flows                    │ 20231016  │
│ ntopng   │ flows                    │ 20231017  │
│ ntopng   │ flows                    │ 20231018  │
│ ntopng   │ flows                    │ 20231019  │
│ ntopng   │ flows                    │ 20231020  │
│ ntopng   │ flows                    │ 20231021  │
│ ntopng   │ flows                    │ 20231022  │
│ ntopng   │ flows                    │ 20231023  │
│ ntopng   │ flows                    │ 20231024  │
│ ntopng   │ flows                    │ 20231025  │
│ ntopng   │ flows                    │ 20231026  │
│ ntopng   │ flows                    │ 20231027  │
│ ntopng   │ flows                    │ 20231028  │
│ ntopng   │ flows                    │ 20231029  │
│ ntopng   │ flows                    │ 20231030  │
│ ntopng   │ flows                    │ 20231031  │
│ ntopng   │ flows                    │ 20231101  │
│ ntopng   │ flows                    │ 20231102  │
│ ntopng   │ flows                    │ 20231103  │
│ ntopng   │ flows                    │ 20231104  │
│ ntopng   │ flows                    │ 20231105  │
│ ntopng   │ flows                    │ 20231106  │
│ ntopng   │ flows                    │ 20231107  │
│ ntopng   │ flows                    │ 20231108  │
│ ntopng   │ flows                    │ 20231109  │
│ ntopng   │ flows                    │ 20231110  │
│ ntopng   │ flows                    │ 20231111  │
│ ntopng   │ flows                    │ 20231112  │
│ ntopng   │ flows                    │ 20231113  │
│ ntopng   │ flows                    │ 20231114  │
│ ntopng   │ flows                    │ 20231115  │
│ ntopng   │ host_alerts              │ 20230808  │
│ ntopng   │ host_alerts              │ 20230809  │
│ ntopng   │ host_alerts              │ 20230810  │
│ ntopng   │ host_alerts              │ 20230811  │
│ ntopng   │ host_alerts              │ 20230812  │
│ ntopng   │ host_alerts              │ 20230813  │
│ ntopng   │ host_alerts              │ 20230814  │
│ ntopng   │ host_alerts              │ 20230815  │
│ ntopng   │ host_alerts              │ 20230816  │
│ ntopng   │ host_alerts              │ 20230817  │
│ ntopng   │ host_alerts              │ 20230818  │
│ ntopng   │ host_alerts              │ 20230819  │
│ ntopng   │ host_alerts              │ 20230820  │
│ ntopng   │ host_alerts              │ 20230821  │
│ ntopng   │ host_alerts              │ 20230822  │
│ ntopng   │ host_alerts              │ 20230823  │
│ ntopng   │ host_alerts              │ 20230824  │
│ ntopng   │ host_alerts              │ 20230825  │
│ ntopng   │ host_alerts              │ 20230826  │
│ ntopng   │ host_alerts              │ 20230827  │
│ ntopng   │ host_alerts              │ 20230828  │
│ ntopng   │ host_alerts              │ 20230829  │
│ ntopng   │ host_alerts              │ 20230830  │
│ ntopng   │ host_alerts              │ 20230831  │
│ ntopng   │ host_alerts              │ 20230901  │
│ ntopng   │ host_alerts              │ 20230902  │
│ ntopng   │ host_alerts              │ 20230903  │
│ ntopng   │ host_alerts              │ 20230904  │
│ ntopng   │ host_alerts              │ 20230905  │
│ ntopng   │ host_alerts              │ 20230906  │
│ ntopng   │ host_alerts              │ 20230907  │
│ ntopng   │ host_alerts              │ 20230908  │
│ ntopng   │ host_alerts              │ 20230909  │
│ ntopng   │ host_alerts              │ 20230910  │
│ ntopng   │ host_alerts              │ 20230911  │
│ ntopng   │ host_alerts              │ 20230912  │
│ ntopng   │ host_alerts              │ 20230913  │
│ ntopng   │ host_alerts              │ 20230914  │
│ ntopng   │ host_alerts              │ 20230915  │
│ ntopng   │ host_alerts              │ 20230916  │
│ ntopng   │ host_alerts              │ 20230917  │
│ ntopng   │ host_alerts              │ 20230918  │
│ ntopng   │ host_alerts              │ 20230919  │
│ ntopng   │ host_alerts              │ 20230920  │
│ ntopng   │ host_alerts              │ 20230921  │
│ ntopng   │ host_alerts              │ 20230922  │
│ ntopng   │ host_alerts              │ 20230923  │
│ ntopng   │ host_alerts              │ 20230924  │
│ ntopng   │ host_alerts              │ 20230925  │
│ ntopng   │ host_alerts              │ 20230926  │
│ ntopng   │ host_alerts              │ 20230927  │
│ ntopng   │ host_alerts              │ 20230928  │
│ ntopng   │ host_alerts              │ 20230929  │
│ ntopng   │ host_alerts              │ 20230930  │
│ ntopng   │ host_alerts              │ 20231001  │
│ ntopng   │ host_alerts              │ 20231002  │
│ ntopng   │ host_alerts              │ 20231003  │
│ ntopng   │ host_alerts              │ 20231004  │
│ ntopng   │ host_alerts              │ 20231005  │
│ ntopng   │ host_alerts              │ 20231006  │
│ ntopng   │ host_alerts              │ 20231007  │
│ ntopng   │ host_alerts              │ 20231008  │
│ ntopng   │ host_alerts              │ 20231009  │
│ ntopng   │ host_alerts              │ 20231010  │
│ ntopng   │ host_alerts              │ 20231011  │
│ ntopng   │ host_alerts              │ 20231012  │
│ ntopng   │ host_alerts              │ 20231013  │
│ ntopng   │ host_alerts              │ 20231014  │
│ ntopng   │ host_alerts              │ 20231015  │
│ ntopng   │ host_alerts              │ 20231016  │
│ ntopng   │ host_alerts              │ 20231017  │
│ ntopng   │ host_alerts              │ 20231018  │
│ ntopng   │ host_alerts              │ 20231019  │
│ ntopng   │ host_alerts              │ 20231020  │
│ ntopng   │ host_alerts              │ 20231021  │
│ ntopng   │ host_alerts              │ 20231022  │
│ ntopng   │ host_alerts              │ 20231023  │
│ ntopng   │ host_alerts              │ 20231024  │
│ ntopng   │ host_alerts              │ 20231025  │
│ ntopng   │ host_alerts              │ 20231026  │
│ ntopng   │ host_alerts              │ 20231027  │
│ ntopng   │ host_alerts              │ 20231028  │
│ ntopng   │ host_alerts              │ 20231029  │
│ ntopng   │ host_alerts              │ 20231030  │
│ ntopng   │ host_alerts              │ 20231031  │
│ ntopng   │ host_alerts              │ 20231101  │
│ ntopng   │ host_alerts              │ 20231102  │
│ ntopng   │ host_alerts              │ 20231103  │
│ ntopng   │ host_alerts              │ 20231104  │
│ ntopng   │ host_alerts              │ 20231105  │
│ ntopng   │ host_alerts              │ 20231106  │
│ ntopng   │ host_alerts              │ 20231107  │
│ ntopng   │ host_alerts              │ 20231108  │
│ ntopng   │ host_alerts              │ 20231109  │
│ ntopng   │ host_alerts              │ 20231110  │
│ ntopng   │ host_alerts              │ 20231111  │
│ ntopng   │ host_alerts              │ 20231112  │
│ ntopng   │ host_alerts              │ 20231113  │
│ ntopng   │ host_alerts              │ 20231114  │
│ ntopng   │ host_alerts              │ 20231115  │
│ ntopng   │ interface_alerts         │ 20230808  │
│ ntopng   │ interface_alerts         │ 20230809  │
│ ntopng   │ interface_alerts         │ 20230810  │
│ ntopng   │ interface_alerts         │ 20230811  │
│ ntopng   │ interface_alerts         │ 20230812  │
│ ntopng   │ interface_alerts         │ 20230813  │
│ ntopng   │ interface_alerts         │ 20230814  │
│ ntopng   │ interface_alerts         │ 20230815  │
│ ntopng   │ interface_alerts         │ 20230816  │
│ ntopng   │ interface_alerts         │ 20230817  │
│ ntopng   │ interface_alerts         │ 20230818  │
│ ntopng   │ interface_alerts         │ 20230819  │
│ ntopng   │ interface_alerts         │ 20230820  │
│ ntopng   │ interface_alerts         │ 20230821  │
│ ntopng   │ interface_alerts         │ 20230822  │
│ ntopng   │ interface_alerts         │ 20230823  │
│ ntopng   │ interface_alerts         │ 20230824  │
│ ntopng   │ interface_alerts         │ 20230825  │
│ ntopng   │ interface_alerts         │ 20230826  │
│ ntopng   │ interface_alerts         │ 20230827  │
│ ntopng   │ interface_alerts         │ 20230828  │
│ ntopng   │ interface_alerts         │ 20230829  │
│ ntopng   │ interface_alerts         │ 20230830  │
│ ntopng   │ interface_alerts         │ 20230831  │
│ ntopng   │ interface_alerts         │ 20230901  │
│ ntopng   │ interface_alerts         │ 20230902  │
│ ntopng   │ interface_alerts         │ 20230903  │
│ ntopng   │ interface_alerts         │ 20230904  │
│ ntopng   │ interface_alerts         │ 20230905  │
│ ntopng   │ interface_alerts         │ 20230906  │
│ ntopng   │ interface_alerts         │ 20230907  │
│ ntopng   │ interface_alerts         │ 20230908  │
│ ntopng   │ interface_alerts         │ 20230909  │
│ ntopng   │ interface_alerts         │ 20230910  │
│ ntopng   │ interface_alerts         │ 20230911  │
│ ntopng   │ interface_alerts         │ 20230912  │
│ ntopng   │ interface_alerts         │ 20230913  │
│ ntopng   │ interface_alerts         │ 20230914  │
│ ntopng   │ interface_alerts         │ 20230915  │
│ ntopng   │ interface_alerts         │ 20230916  │
│ ntopng   │ interface_alerts         │ 20230917  │
│ ntopng   │ interface_alerts         │ 20230918  │
│ ntopng   │ interface_alerts         │ 20230919  │
│ ntopng   │ interface_alerts         │ 20230920  │
│ ntopng   │ interface_alerts         │ 20230921  │
│ ntopng   │ interface_alerts         │ 20230922  │
│ ntopng   │ interface_alerts         │ 20230923  │
│ ntopng   │ interface_alerts         │ 20230924  │
│ ntopng   │ interface_alerts         │ 20230925  │
│ ntopng   │ interface_alerts         │ 20230926  │
│ ntopng   │ interface_alerts         │ 20230927  │
│ ntopng   │ interface_alerts         │ 20230928  │
│ ntopng   │ interface_alerts         │ 20230929  │
│ ntopng   │ interface_alerts         │ 20230930  │
│ ntopng   │ interface_alerts         │ 20231001  │
│ ntopng   │ interface_alerts         │ 20231002  │
│ ntopng   │ interface_alerts         │ 20231003  │
│ ntopng   │ interface_alerts         │ 20231004  │
│ ntopng   │ interface_alerts         │ 20231005  │
│ ntopng   │ interface_alerts         │ 20231006  │
│ ntopng   │ interface_alerts         │ 20231007  │
│ ntopng   │ interface_alerts         │ 20231008  │
│ ntopng   │ interface_alerts         │ 20231009  │
│ ntopng   │ interface_alerts         │ 20231010  │
│ ntopng   │ interface_alerts         │ 20231011  │
│ ntopng   │ interface_alerts         │ 20231012  │
│ ntopng   │ interface_alerts         │ 20231013  │
│ ntopng   │ interface_alerts         │ 20231014  │
│ ntopng   │ interface_alerts         │ 20231015  │
│ ntopng   │ interface_alerts         │ 20231016  │
│ ntopng   │ interface_alerts         │ 20231017  │
│ ntopng   │ interface_alerts         │ 20231018  │
│ ntopng   │ interface_alerts         │ 20231019  │
│ ntopng   │ interface_alerts         │ 20231020  │
│ ntopng   │ interface_alerts         │ 20231021  │
│ ntopng   │ interface_alerts         │ 20231022  │
│ ntopng   │ interface_alerts         │ 20231023  │
│ ntopng   │ interface_alerts         │ 20231024  │
│ ntopng   │ interface_alerts         │ 20231025  │
│ ntopng   │ interface_alerts         │ 20231026  │
│ ntopng   │ interface_alerts         │ 20231027  │
│ ntopng   │ interface_alerts         │ 20231028  │
│ ntopng   │ interface_alerts         │ 20231029  │
│ ntopng   │ interface_alerts         │ 20231030  │
│ ntopng   │ interface_alerts         │ 20231031  │
│ ntopng   │ interface_alerts         │ 20231101  │
│ ntopng   │ interface_alerts         │ 20231102  │
│ ntopng   │ interface_alerts         │ 20231103  │
│ ntopng   │ interface_alerts         │ 20231104  │
│ ntopng   │ interface_alerts         │ 20231105  │
│ ntopng   │ interface_alerts         │ 20231106  │
│ ntopng   │ interface_alerts         │ 20231107  │
│ ntopng   │ interface_alerts         │ 20231108  │
│ ntopng   │ interface_alerts         │ 20231109  │
│ ntopng   │ interface_alerts         │ 20231110  │
│ ntopng   │ interface_alerts         │ 20231111  │
│ ntopng   │ interface_alerts         │ 20231112  │
│ ntopng   │ interface_alerts         │ 20231113  │
│ ntopng   │ interface_alerts         │ 20231114  │
│ ntopng   │ interface_alerts         │ 20231115  │
│ ntopng   │ l4_protocols             │ tuple()   │
│ ntopng   │ l7_categories            │ tuple()   │
│ ntopng   │ l7_protocols             │ tuple()   │
│ ntopng   │ system_alerts            │ 20230808  │
│ ntopng   │ system_alerts            │ 20230809  │
│ ntopng   │ system_alerts            │ 20230810  │
│ ntopng   │ system_alerts            │ 20230811  │
│ ntopng   │ system_alerts            │ 20230812  │
│ ntopng   │ system_alerts            │ 20230813  │
│ ntopng   │ system_alerts            │ 20230814  │
│ ntopng   │ system_alerts            │ 20230815  │
│ ntopng   │ system_alerts            │ 20230816  │
│ ntopng   │ system_alerts            │ 20230817  │
│ ntopng   │ system_alerts            │ 20230818  │
│ ntopng   │ system_alerts            │ 20230819  │
│ ntopng   │ system_alerts            │ 20230820  │
│ ntopng   │ system_alerts            │ 20230821  │
│ ntopng   │ system_alerts            │ 20230822  │
│ ntopng   │ system_alerts            │ 20230823  │
│ ntopng   │ system_alerts            │ 20230824  │
│ ntopng   │ system_alerts            │ 20230825  │
│ ntopng   │ system_alerts            │ 20230826  │
│ ntopng   │ system_alerts            │ 20230827  │
│ ntopng   │ system_alerts            │ 20230828  │
│ ntopng   │ system_alerts            │ 20230829  │
│ ntopng   │ system_alerts            │ 20230830  │
│ ntopng   │ system_alerts            │ 20230831  │
│ ntopng   │ system_alerts            │ 20230901  │
│ ntopng   │ system_alerts            │ 20230902  │
│ ntopng   │ system_alerts            │ 20230903  │
│ ntopng   │ system_alerts            │ 20230904  │
│ ntopng   │ system_alerts            │ 20230905  │
│ ntopng   │ system_alerts            │ 20230906  │
│ ntopng   │ system_alerts            │ 20230907  │
│ ntopng   │ system_alerts            │ 20230908  │
│ ntopng   │ system_alerts            │ 20230909  │
│ ntopng   │ system_alerts            │ 20230910  │
│ ntopng   │ system_alerts            │ 20230911  │
│ ntopng   │ system_alerts            │ 20230912  │
│ ntopng   │ system_alerts            │ 20230913  │
│ ntopng   │ system_alerts            │ 20230914  │
│ ntopng   │ system_alerts            │ 20230915  │
│ ntopng   │ system_alerts            │ 20230916  │
│ ntopng   │ system_alerts            │ 20230917  │
│ ntopng   │ system_alerts            │ 20230918  │
│ ntopng   │ system_alerts            │ 20230919  │
│ ntopng   │ system_alerts            │ 20230920  │
│ ntopng   │ system_alerts            │ 20230921  │
│ ntopng   │ system_alerts            │ 20230922  │
│ ntopng   │ system_alerts            │ 20230923  │
│ ntopng   │ system_alerts            │ 20230924  │
│ ntopng   │ system_alerts            │ 20230925  │
│ ntopng   │ system_alerts            │ 20230926  │
│ ntopng   │ system_alerts            │ 20230927  │
│ ntopng   │ system_alerts            │ 20230928  │
│ ntopng   │ system_alerts            │ 20230929  │
│ ntopng   │ system_alerts            │ 20230930  │
│ ntopng   │ system_alerts            │ 20231001  │
│ ntopng   │ system_alerts            │ 20231002  │
│ ntopng   │ system_alerts            │ 20231003  │
│ ntopng   │ system_alerts            │ 20231004  │
│ ntopng   │ system_alerts            │ 20231005  │
│ ntopng   │ system_alerts            │ 20231006  │
│ ntopng   │ system_alerts            │ 20231007  │
│ ntopng   │ system_alerts            │ 20231008  │
│ ntopng   │ system_alerts            │ 20231009  │
│ ntopng   │ system_alerts            │ 20231010  │
│ ntopng   │ system_alerts            │ 20231011  │
│ ntopng   │ system_alerts            │ 20231012  │
│ ntopng   │ system_alerts            │ 20231013  │
│ ntopng   │ system_alerts            │ 20231014  │
│ ntopng   │ system_alerts            │ 20231015  │
│ ntopng   │ system_alerts            │ 20231016  │
│ ntopng   │ system_alerts            │ 20231017  │
│ ntopng   │ system_alerts            │ 20231018  │
│ ntopng   │ system_alerts            │ 20231019  │
│ ntopng   │ system_alerts            │ 20231020  │
│ ntopng   │ system_alerts            │ 20231021  │
│ ntopng   │ system_alerts            │ 20231022  │
│ ntopng   │ system_alerts            │ 20231023  │
│ ntopng   │ system_alerts            │ 20231024  │
│ ntopng   │ system_alerts            │ 20231025  │
│ ntopng   │ system_alerts            │ 20231026  │
│ ntopng   │ system_alerts            │ 20231027  │
│ ntopng   │ system_alerts            │ 20231028  │
│ ntopng   │ system_alerts            │ 20231029  │
│ ntopng   │ system_alerts            │ 20231030  │
│ ntopng   │ system_alerts            │ 20231031  │
│ ntopng   │ system_alerts            │ 20231101  │
│ ntopng   │ system_alerts            │ 20231102  │
│ ntopng   │ system_alerts            │ 20231103  │
│ ntopng   │ system_alerts            │ 20231104  │
│ ntopng   │ system_alerts            │ 20231105  │
│ ntopng   │ system_alerts            │ 20231106  │
│ ntopng   │ system_alerts            │ 20231107  │
│ ntopng   │ system_alerts            │ 20231108  │
│ ntopng   │ system_alerts            │ 20231109  │
│ ntopng   │ system_alerts            │ 20231110  │
│ ntopng   │ system_alerts            │ 20231111  │
│ ntopng   │ system_alerts            │ 20231112  │
│ ntopng   │ system_alerts            │ 20231113  │
│ ntopng   │ system_alerts            │ 20231114  │
│ ntopng   │ system_alerts            │ 20231115  │
│ ntopng   │ user_alerts              │ 20230901  │
│ ntopng   │ user_alerts              │ 20230906  │
│ ntopng   │ user_alerts              │ 20230907  │
│ ntopng   │ user_alerts              │ 20230915  │
│ ntopng   │ user_alerts              │ 20230920  │
│ ntopng   │ user_alerts              │ 20230921  │
│ ntopng   │ user_alerts              │ 20230922  │
│ ntopng   │ user_alerts              │ 20230923  │
│ ntopng   │ user_alerts              │ 20230924  │
│ ntopng   │ user_alerts              │ 20230925  │
│ ntopng   │ user_alerts              │ 20231002  │
│ ntopng   │ user_alerts              │ 20231005  │
│ ntopng   │ user_alerts              │ 20231006  │
│ ntopng   │ user_alerts              │ 20231009  │
│ ntopng   │ user_alerts              │ 20231010  │
│ ntopng   │ user_alerts              │ 20231013  │
│ ntopng   │ user_alerts              │ 20231023  │
│ ntopng   │ user_alerts              │ 20231027  │
│ ntopng   │ user_alerts              │ 20231031  │
│ ntopng   │ user_alerts              │ 20231101  │
│ ntopng   │ user_alerts              │ 20231106  │
│ ntopng   │ user_alerts              │ 20231110  │
│ ntopng   │ user_alerts              │ 20231115  │
└──────────┴──────────────────────────┴───────────┘

**Comment by MatteoBiscosi** [comment]
Hi @seaperse you are misunderstanding that retention, the one  you took the picture is for timeseries, so practically speaking, the charts.
![image](https://github.com/ntop/ntopng/assets/49585191/fccfe77c-1014-4b5f-a5bb-accadb225d20)
![image](https://github.com/ntop/ntopng/assets/49585191/5b4c068b-c816-4131-9f22-b7ab41e667c6)

The ones instead your are checking on ClickHouse are regarding alerts and flows, and to change that configuration you need to switch to the ClickHouse preferences tab.
![image](https://github.com/ntop/ntopng/assets/49585191/3bbe5eb3-e253-428a-a9bc-f1a11a17968b)

**Comment by seaperse** [comment]
![image](https://github.com/ntop/ntopng/assets/140824574/130f613b-95ec-4719-8d8f-56e46a0b22c0)
Please see the picture
this was and is also 90 and the data doesn't get deleted automatically

**Comment by MatteoBiscosi** [comment]
Alright, i pushed a fix and added a couple of more traces, so in a couple of hours update do the following:
- run: `redis-cli SET "ntopng.debug.retention_query" 1`
- restart ntopng
- send me the output of journalctl -e -u ntopng

**Comment by seaperse** [comment]
[new 50.txt](https://github.com/ntop/ntopng/files/13423275/new.50.txt)

Please see the attached file
About 15hours ago I updated the ntop
now I ran the redis command, restarted the ntopng and pasted the output of journalctl to the file

**Comment by MatteoBiscosi** [comment]
Hi @seaperse I pushed a fix, the issue should now be fixed, please update in a couple of hours and let me know.
You can remove the debug print by running `redis-cli del "ntopng.debug.retention_query"`

**Comment by seaperse** [comment]
Hello

Thanks, your update worked!
The retention is again working as expexted!

**Comment by MatteoBiscosi** [comment]
Glad to know @seaperse and sorry for the trouble
