### ISSUE TITLE
block traffic based fqdn - not working

### ISSUE THREAD

**Issue by dimalev01** [ntop/ntopng#8023]
Hello ,

We have a physical server running ntopng + nprobe in the middle between our network and the internet.
We use policy pools to block traffic based on geolocation and protocols , for example we blocking ICMP and SNMP from the world to our IPv4 addresses.

Now we need to block domains/fqdns  , as we saw in the “traffic polices” in NTOPNG GUI it seems possible so we configured it in “Host Rules” (fqdn that added: test.com Drop) , but it’s not working , Traffic continues to go to test.com instead of being blocked.

![112](https://github.com/ntop/ntopng/assets/149945346/895461c2-8bc8-48b9-a73c-5c02bb9feb0b)

 
 ntopng version: 6.1  (Enterprise L)
nprobe version: 10.5 (nProbe Enterprise L)

As we know it should work ,  is there anything else we need to add or is there another way to do it? Or maybe the 
problem is the version of the ntopng or nprobe?

Br ,

Dima Lev.

**Comment by cardigliano** [comment]
ntopng seems to propagate the policy to nProbe as expected:

{"policy":{"id":3,"default_marker":"pass","markers":{"continents":[],"categories":[],"countries":[],**"hostnames":{"test.com":"drop"}**,"protocols":[]},"name":"Pool 2 rules","flow_risk":{"marker":"drop","bitmap":0},"root":0}}

we need to check on the nProbe side if this is honoured

**Comment by cardigliano** [comment]
Following up at https://github.com/ntop/nProbe/issues/587
