### ISSUE TITLE
[VS] Rename REST API

### ISSUE THREAD

**Issue by NicoMaio** [ntop/ntopng#8024]
Rename the vulnerability scan API following the ntopng standards.

**Comment by NicoMaio** [comment]
- /lua/rest/v2/add/host/to_scan.lua (Add Host to vulnerability scan hosts list) ->  /lua/rest/v2/add/vs/entry.lua 
- /lua/rest/v2/exec/host/schedule_vulnerability_scan.lua -> /lua/rest/v2/exec/vs/schedule.lua 
- /lua/rest/v2/get/host/vulnerability_scan_type_list.lua -> /lua/rest/v2/get/vs/types.lua
- /lua/rest/v2/get/host/to_scan_list.lua -> /lua/rest/v2/get/vs/entries.lua 
- /lua/pro/rest/v2/get/vs/report_list.lua -> /lua/pro/rest/v2/get/vs/reports.lua
- /lua/rest/v2/edit/host/update_va_scan_period.lua -> /lua/rest/v2/edit/vs/periodicities.lua

**Comment by MatteoBiscosi** [comment]
Not needed
