### ISSUE TITLE
Traffic disaggregation not work for all VLAN

### ISSUE THREAD

**Issue by jq-yeraz** [ntop/ntopng#8027]
We use traffic disaggregation based on the VLAN Id. For some VLAN a sub interface is created :

<img width="1523" alt="image" src="https://github.com/ntop/ntopng/assets/62381029/146ddcc3-94f2-425c-b4c4-5183113e4642">

But for some others, no sub interface are created :

<img width="1523" alt="image" src="https://github.com/ntop/ntopng/assets/62381029/b7bacc06-d678-48de-aa4d-824af8627862">

**Comment by cardigliano** [comment]
@jq-yeraz how many vlans are correctly disaggregated and present in the interface-selector (dropdown)?

**Comment by jq-yeraz** [comment]
@cardigliano below a list of current VLAN. Sometimes VLAN in the subinterface are only on the dropdown and sometimes it's the opposite. But a same VLAN is not on the both.

<img width="407" alt="image" src="https://github.com/ntop/ntopng/assets/62381029/ab8d5f05-5421-414a-949d-1178c1f2298b">

**Comment by cardigliano** [comment]
I think you are hitting the max number of supported interfaces (ntopng Ent L supports up to 32). 
How many VLANs do you have in your network?

**Comment by jq-yeraz** [comment]
@cardigliano Alfredo, I bought the XL version... now I have 44 subinterfaces but always some VLAN stay (9 exactly) in the dropdown...

<img width="1728" alt="image" src="https://github.com/ntop/ntopng/assets/62381029/717d8638-068e-46a4-935d-3bbd28f576a9">

Second question, XL version limit to 64 subinterfaces... ok but what is the next if I have more than 64 VLAN ? Why you limit ?

**Comment by cardigliano** [comment]
@jq-yeraz are you available for a call to check this together? Please drop me an email (cardigliano at ntop.org)
