### ISSUE TITLE
Filter flows to unknown L7 protocols

### ISSUE THREAD

**Issue by jq-yeraz** [ntop/ntopng#8028]
I have filtered the flows on the **unknown** value of the L7 Protocol dropdown but on the results, I have many **known** protocol :

<img width="1523" alt="image" src="https://github.com/ntop/ntopng/assets/62381029/352cbfb7-0a6b-468b-9454-e7c3a05244b7">

**Comment by jq-yeraz** [comment]
@MatteoBiscosi how to test ? I have uploaded ntopng to 6.1.231122 but the issue is the same.

**Comment by MatteoBiscosi** [comment]
Hi @jq-yeraz could you please update and let me know? In my installation seems working correctly, if not please share your ntopng configuration
![image](https://github.com/ntop/ntopng/assets/49585191/d5760a9f-9110-46a7-a0dc-fef0130a9988)

**Comment by MatteoBiscosi** [comment]
Verified as fixed with the latest dev version
