### ISSUE TITLE
ntopng crashing with "failed to reclaim memory error' since update

### ISSUE THREAD

**Issue by iamtherobin** [ntop/ntopng#8030]
**Environment**:
* OS name: OPNsense 23.7.8_1 / FreeBSD 13.2-RELEASE-p5
* Architecture: amd64
* ntopng version/revision: ntopng Community v.6.1.231119

**What happened**:
I run an opnsense firewall on an intel N100 mini pc. Everything was fine until a few days ago when I made the update from opnsense 23.7.7 to opnsense 23.7.8. Obviously, a lot of packages were updated. No configurations were changed.

Concerning ntopng, my install log for the opnsense update shows:
os-ntopng-enterprise upgraded: 6.1.231107 -> 6.1.231117
ntopng upgraded: 6.1.231107 -> 6.1.231117

Once the update was complete and my firewall was restarted, I would get a swap error that would crash ntopng along with adguardhome (the second highest memory usage on my firewall) and sometimes a third service (usually unbound). This would cause DNS to break for the whole home until I manually restart the service.

Here is a sample from my general system log:
>2023-11-18T00:17:31-05:00	Notice	kernel	<6>wg1: promiscuous mode disabled	
>2023-11-18T00:17:31-05:00	Notice	kernel	<6>bridge0: promiscuous mode disabled	
>2023-11-18T00:17:31-05:00	Notice	kernel	<6>igc0: promiscuous mode disabled	
>2023-11-18T00:17:31-05:00	Notice	kernel	<3>pid 52546 (AdGuardHome), jid 0, uid 0, was killed: failed to reclaim memory	
>2023-11-18T00:17:28-05:00	Notice	kernel	<3>pid 29374 (ntopng), jid 0, uid 288, was killed: failed to reclaim memory	
>2023-11-18T00:17:26-05:00	Notice	kernel	swp_pager_getswapspace(19): failed	
>2023-11-18T00:17:26-05:00	Notice	kernel	swp_pager_getswapspace(24): failed	
>2023-11-18T00:17:26-05:00	Notice	kernel	swap_pager: out of swap space	
>2023-11-18T00:17:26-05:00	Notice	kernel	swp_pager_getswapspace(13): failed	
>2023-11-18T00:17:26-05:00	Notice	kernel	swap_pager: out of swap space

The rate of occurrence is seemingly random. There is no fixed time frequency or a apparent trigger which causes it. It seems to take 30-60 minutes of running ntopng for it to occur. This only occurs if ntopng is running. If I leave ntopng disabled, this issue never occurs.

I have 16GB of RAM installed with an 8GB swap partition. The ram is never fully never used. It usually uses about 4GB with 6GB peaks. Before this update, I have never seen any swap usage on my opnsense. However, after the crash occurs, there is a small about of swap (about 100MB-200MB).

I have since kept updating ntopng and am currently running latest version as of this post. Issue is still occurring. I tried to disable my swap to see if that would remedy the issue but it is still occurring. Only since I disabled the swap, there is no swap_pager kernel notice. The only notice will be the ntopng failed to reclaim memory. Another observation is, since I disabled swap, ntopng is the only service that crashes.

All I get in the general log since disabling swap:
>2023-11-19T07:30:57-05:00	Notice	kernel	<6>wg1: promiscuous mode disabled	
>2023-11-19T07:30:57-05:00	Notice	kernel	<6>bridge0: promiscuous mode disabled	
>2023-11-19T07:30:57-05:00	Notice	kernel	<6>igc0: promiscuous mode disabled	
>2023-11-19T07:30:54-05:00	Notice	kernel	<3>pid 87442 (ntopng), jid 0, uid 288, was killed: failed to reclaim memory

I am not sure how to go about gathering more information on this issue.

**Comment by cardigliano** [comment]
@iamtherobin thank you for providing exhaustive information, we are currently testing ntopng on OPNsense 23.7.8_1 to see if we are able to reproduce the same, we will let you know in case we need additional information.

**Comment by iamtherobin** [comment]
So I just updated to OPNsense 23.7.9 including os-ntopng-enterprise upgraded: 6.1.231119 -> 6.1.231123 and ntopng upgraded: 6.1.231119 -> 6.1.231123. I decided to test it again and it still crashed. However this time the error was different and it was accompanied by an issue with nut that I never seen before so I included it.

```
2023-11-23T14:33:19-05:00	Notice	upsmon	Communications with UPS CyberpowerUPS established	
2023-11-23T14:33:14-05:00	Error	upsmon	Login on UPS [CyberpowerUPS] failed - got [ERR ACCESS-DENIED]	
2023-11-23T14:33:09-05:00	Notice	upsd	UPS [CyberpowerUPS] data is no longer stale	
2023-11-23T14:33:09-05:00	Notice	upsd	Data for UPS [CyberpowerUPS] is stale - check driver	
2023-11-23T14:33:09-05:00	Notice	upsmon	Communications with UPS CyberpowerUPS lost	
2023-11-23T14:33:09-05:00	Error	upsmon	Poll UPS [CyberpowerUPS] failed - Server disconnected	
2023-11-23T14:33:09-05:00	Notice	kernel	<118>2023-11-23T14:33:09.819146-05:00 OPN100.athome.net lighttpd 84129 - - 192.168.0.100 opn100.athome.net - [23/Nov/2023:14:33:09 -0500] "PRI * HTTP/2.0" 100 - "-" "-"	
2023-11-23T14:33:09-05:00	Notice	kernel	<6>wg1: promiscuous mode disabled	
2023-11-23T14:33:09-05:00	Notice	kernel	<6>bridge0: promiscuous mode disabled	
2023-11-23T14:33:09-05:00	Notice	kernel	<6>igc0: promiscuous mode disabled	
2023-11-23T14:33:09-05:00	Notice	kernel	<3>pid 49615 (ntopng), jid 0, uid 288, was killed: a thread waited too long to allocate a page
```

**Comment by MatteoBiscosi** [comment]
Hi @iamtherobin, does the issue persist?

**Comment by iamtherobin** [comment]
Problem seems to be solved through various updates.
