### ISSUE TITLE
Specifying `--callbacks-dir` breaks `--daemon`.

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#8034]
The command `/usr/bin/ntopng --scripts-dir=/usr/share/ntopng/scripts --install-dir=/usr/share/ntopng --httpdocs-dir=/usr/share/ntopng/httpdocs -w 127.0.0.1:3000 --interface=eth2 --interface=wlan1 --disable-login=1 --user=ntopng --daemon --pid=/var/run/ntopng.pid ` works as expected.

The command `/usr/bin/ntopng   ----callbacks-dir=/usr/share/ntopng/scripts/callbacks  --scripts-dir=/usr/share/ntopng/scripts --install-dir=/usr/share/ntopng --httpdocs-dir=/usr/share/ntopng/httpdocs -w 127.0.0.1:3000 --interface=eth2 --interface=wlan1 --disable-login=1 --user=ntopng --daemon --pid=/var/run/ntopng.pid ` does not daemonize.

**Comment by lucaderi** [comment]
Just test: it works for us

root@dell:/home/deri/ntopng# ./ntopng -i eno1 --callbacks-dir /tmp/ --daemon
05/Jun/2024 18:03:01 [Redis.cpp:166] Successfully connected to redis 127.0.0.1:6379@0
05/Jun/2024 18:03:01 [Redis.cpp:166] Successfully connected to redis 127.0.0.1:6379@0
...
05/Jun/2024 18:03:07 [ThreadedActivity.cpp:269] WARNING: Unable to find script boot.lua
05/Jun/2024 18:03:07 [Ntop.cpp:2604] Parent process is exiting (this is normal)
root@dell:/home/deri/ntopng# !ps
ps auwx|grep ntopng
ntopng     24019  8.7  0.2 345684 71412 ?        Ssl  18:03   0:00 ./ntopng -i eno1 --callbacks-dir /tmp/ --daemon
root       24054  0.0  0.0   9088  2308 pts/4    S+   18:03   0:00 grep --color=auto ntopng
