### ISSUE TITLE
after upgrade PCAP file dont svaed for 14 days

### ISSUE THREAD

**Issue by Alisher-Nabiev** [ntop/ntopng#8035]
**Environment**:
* OS name: Ubuntu 
* OS version: 18.04.6 LTS
* Architecture: x86_64
* ntopng version/revision: ntopng Enterprise L v.5.7.231017

**What happened**:

hi,

after the upgrade, the history PCAP files taken by API is available for 4 days despite Timeseries/Stats Data Retention configuration on the GUI set for 14 days.

**Debug Information**:

<!--
Paste debug information below:
- Copy the service log from "systemctl status ntopng" or "journalctl -u ntopng":
![image](https://github.com/ntop/ntopng/assets/33841389/ef18956f-f573-4180-a51e-954029f6b6a4)

- Grab a screenshot from the GUI demonstrating the issue:
![image](https://github.com/ntop/ntopng/assets/33841389/0ce036d7-af19-48e2-9d23-ec272017374f)

**Comment by cardigliano** [comment]
@Alisher-Nabiev PCAP data retention depends on the configured disk space in the recording settings or n2disk configuration file, this is not affected by the configured retention days

**Comment by Alisher-Nabiev** [comment]
This is my conf file where exactly I can control the retention?

--interface=eth0
--dump-directory=/var/lib/ntopng/0/pcap
--index
--timeline-dir=/var/lib/ntopng/0/timeline
--buffer-len=1024
--max-file-len=256
--max-file-duration=60
--disk-limit=1536000
--snaplen=1536
--writer-cpu-affinity=0
--reader-cpu-affinity=1
--compressor-cpu-affinity=2
--index-on-compressor-threads
-u=ntopng
--capture-direction=0
--index-tunnel-content=1
--daemon
-P=/var/run/n2disk-eth0.pid

#--disk-limit=307200
#1024000
#307200

**Comment by cardigliano** [comment]
This is the option:
--disk-limit=1536000

**Comment by Alisher-Nabiev** [comment]
OK, thanks for the info.

and for what exactly Timeseries/Stats Data Retention configuration are?

**Comment by cardigliano** [comment]
Timeseries keep data for historical charts in ntopng
