### ISSUE TITLE
Redesign Alert Severity on some Alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8037]
The alert below should be set to emergency
<img width="1763" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/87de28e6-901e-4bb0-97be-3e0dfd99794c">
as other alerts that prevent ntopng from working properly (e.g.database down or unreachable)

This is to request to
1. Rework alert severities
2. In case ntop does not define an endpoint/recipient for emergencies, a window should open and remind the user to create it

**Comment by lucaderi** [comment]
Please also consider #8040 during the implementation of this ticket

**Comment by MatteoBiscosi** [comment]
Implemented as requested
