### ISSUE TITLE
ntopng segfault

### ISSUE THREAD

**Issue by ankerstal** [ntop/ntopng#804]
Hi,

I recently instralled ntopng and it seems to segfault.
Oct 30 07:00:06 nf kernel: ntopng[17108]: segfault at 18 ip 000000360b42250e sp 00007fcc4f5fd660 error 4 in librrd.so.4.0.7[360b400000+31000]

**Comment by emanuele-f** [comment]
Please, specify operating system and ntopng version (-v). Are you using updated ntopng and rrd packages?

**Comment by ankerstal** [comment]
v.2.5.161029 [Enterprise/Professional Edition]
GIT rev:   dev:0793d8666abe6d04df57c3fbf1179703f55a816d:20161029
Pro rev:   r702
System Id: 1243712E000007F9
Built on:  CentOS release 6.8 (Final)
rrdtool-1.3.8-7.el6.x86_64

System is running Centos 6.

Thanks.

**Comment by ankerstal** [comment]
Ok, nevermind. It was due to full disk.

Thanks!

**Comment by emanuele-f** [comment]
Glad to hear you solved, thank you.
