### ISSUE TITLE
Create alarm when ntop code is broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8040]
In case of errors such as 
Nov 21 03:37:00 tools ntopng[2836995]: 21/Nov/2023 03:37:00 [vulnerability_scan.lua:37] [vs_utils.lua:1971] ...opng/scripts/lua/modules/vulnerability_scan/vs_utils.lua:1002: attempt to index a nil value (global 'rsp')
Nov 21 03:52:31 tools ntopng[2836995]: 21/Nov/2023 03:52:31 [vulnerability_scan.lua:37] [vs_utils.lua:1971] ...opng/scripts/lua/modules/vulnerability_scan/vs_utils.lua:1002: attempt to index a nil value (global 'rsp')

it is requested to generate an emergency alert. See also #8037

**Comment by MatteoBiscosi** [comment]
Implemented as requested
