### ISSUE TITLE
Add Flow Exporters in Report

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8046]
In the report page (and eventually also the dashboard) add a new drop-down menu (in case of flow collection) in the top menubar

![image](https://github.com/ntop/ntopng/assets/4493366/39d10c04-55ed-41ac-9464-907f7cf52961)

containing a sorted list of exporters. Selecting it will refine the results presented in the report

**Comment by MatteoBiscosi** [comment]
Implemented as requested
