### ISSUE TITLE
[VS] Enhance email report

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8048]
Today the report is

---
Daily Vulnerability Scan successfully completed.

Start time: 23/11/2023 00:00:31.

End time: 23/11/2023 03:47:46.

Scan duration: 03:47:15.

Scanned Hosts: 144.

Found no CVEs; 6 UDP open ports; 52 TCP open ports.

See full report here [Vulnerability Scan Report](https://.....)
----

You need to also specify
- if you have found discrepancies with respect to the previous scan
- what discrrepancies
Example

- 10 new ports open, 4 CVEs fixed
- Host X: has port Y open
- .....

**Comment by NicoMaio** [comment]
Fix email format by 9843d3f0248bc9effc5f2ec28607d5182717f28c

**Comment by lucaderi** [comment]
Verified as fixed. There re some minor bugs that are being identified
