### ISSUE TITLE
SNMP page disappears

### ISSUE THREAD

**Issue by e73kiel** [ntop/ntopng#805]
Hi,

I have just installed ntop to my centOS7 server, everything is just fine but i have a problem on monitoring mycisco sg 300-52 switch. I set it up and get the port information on the host page/SNMP
but at the top of the i get an error 
"Lua.cpp:5134] WARNING: Script failure [/usr/share/ntopng/scripts/lua/host_details.lua][/usr/share/ntopng/pro/scripts/lua/modules/snmp_utils.lua:390: attempt to concatenate a nil value]"

and then the SNMP page disappears.

![screen shot 2016-11-01 at 2 09 53 pm](https://cloud.githubusercontent.com/assets/19939206/19888009/0582a684-a03d-11e6-9ed7-913621cb71f9.png)

Anyone has faced before and can help?

Have a Good Day

**Comment by lucaderi** [comment]
I believe you are using the standard version of ntopng in demo mode and when the demo ends the page disappears

**Comment by e73kiel** [comment]
Hi,
I am using ntopng Pro [Small Business Edition] Demo version,
Whenever i restart the service SNMP page appears again and shows random number of ports and number of the ports changes when i refresh the page. after 3 4 refresh the SNMP page disappears. The error is obvious in the log but i don't know if its something i can fix or not.
After the first post i searched some solutions and found that changing the custom name may cause error 
![screen shot 2016-11-01 at 3 08 39 pm](https://cloud.githubusercontent.com/assets/19939206/19889290/2e835e86-a045-11e6-9a99-68e0f6fab3fd.png)
so i changed it to default, its ip. and i started to get a different kind of error;
Lua.cpp:5134] WARNING: Script failure [/usr/share/ntopng/scripts/lua/host_details.lua][/usr/share/ntopng/pro/scripts/lua/modules/snmp_utils.lua:393: bad argument #1 to 'tonumber' (value expected)]

**Comment by e73kiel** [comment]
Anyone has any idea. If its a bug that can be fixed with license then its ok.

**Comment by lucaderi** [comment]
@e73kiel Can you please use the development version and report if you have problem?

**Comment by emanuele-f** [comment]
@e73kiel do you have any updates?

**Comment by e73kiel** [comment]
@emanuele-f  still the same. i get the error:
HTTP/1.1 500 Internal server error Content-Type: text/html Connection: close   Script "/usr/share/ntopng/scripts/lua/host_details.lua" returned an error:
/usr/share/ntopng/pro/scripts/lua/modules/snmp_utils.lua:388: attempt to concatenate a nil value

after 1 or 2 reload the SNMP section disables. When i restart the service it appears again and reacts randomly. sometimes it manages to scan all snmp ports and sometimes it gives the error code on the n th port which changes every time but whatever the snmp page fails or not, the page dissapears approximately 5 minutes after the reload.

**Comment by e73kiel** [comment]
same error on the log line:
[Lua.cpp:5134] WARNING: Script failure [/usr/share/ntopng/scripts/lua/host_details.lua][/usr/share/ntopng/pro/scripts/lua/modules/snmp_utils.lua:392: bad argument #1 to 'tonumber' (value expected)]

**Comment by emanuele-f** [comment]
@e73kiel the fact that the SNMP page disappears after 5 minutes it's normal, since after 5 minutes you go back to the community version because you are using a demo. In order to troubleshoot the second problem, can you please try the latest development version of ntopng as suggested by @lucaderi and see if you still experience the issue?

**Comment by lucaderi** [comment]
We believe we provided the solution. If not, please reopen the issue and explain the problem more in detail
