### ISSUE TITLE
Setup a REST API handle for Setting Host/Interface/Network... Aliases

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8053]
This is to add (if not available yet) a new REST API call that allows a remote client to set Host/Interface/Network... aliases. This is to enable ntopng users to set aliases for hosts. 

Use case:
- an ISP can set aliases for local hosts/networks, e.g. bind a customer name to a host by calling this REST call

Make sure that the REST calls are available to all ntopng possible aliases (e.g. hosts, interfaces, ...)

**Comment by MatteoBiscosi** [comment]
Some of these API are already available and can be found in the API doc, in the specific case:
- /lua/rest/v2/set/host/alias.lua
- /lua/pro/rest/v2/set/observation_points/alias.lua

Missing:
- MAC Addresses
- Networks
- Interfaces

**Comment by MatteoBiscosi** [comment]
All the REST API are tested and working correctly, can be found in the documentation:
- /lua/rest/v2/set/host/alias.lua
- /lua/pro/rest/v2/set/observation_points/alias.lua
- /lua/rest/v2/set/device/alias.lua
- /lua/rest/v2/set/network/alias.lua
- /lua/rest/v2/set/interface/alias.lua

**Comment by MatteoBiscosi** [comment]
Implemented as requested
