### ISSUE TITLE
unable to validate license

### ISSUE THREAD

**Issue by dvachon2018** [ntop/ntopng#8054]
**Environment**:
* OS name: Armbian
* OS version: 23.8.1 Bullseye with Linux 5.15.93-sunxi64
* Architecture: ARM
* ntopng version/revision: 6.1.231119

**What happened**:
licenses errors in logs after installation of new license

**How did you reproduce it?**
start ntopng and look at logs

**Debug Information**:
root@opi3-ntop:/etc# ll /var/log/ntopng.log
-rw-r----- 1 root adm 3325483 Nov 22 10:03 /var/log/ntopng.log

root@opi3-ntop:/etc# cat /var/log/ntopng.log | grep license

Nov 22 09:54:40 opi3-ntop ntopng[237402]: 22/Nov/2023 09:54:40 [NtopPro.cpp:350] [LICENSE] Reading license from /etc/ntopng.license
Nov 22 09:54:40 opi3-ntop ntopng[237402]: 22/Nov/2023 09:54:40 [NtopPro.cpp:519] [LICENSE] /etc/ntopng.license: unable to validate license [Invalid product]
Nov 22 09:54:40 opi3-ntop ntopng[237402]: 22/Nov/2023 09:54:40 [NtopPro.cpp:343] [LICENSE] No license file found /etc/ntopng.license: reading license from redis
Nov 22 09:54:40 opi3-ntop ntopng[237402]: 22/Nov/2023 09:54:40 [NtopPro.cpp:523] [LICENSE] Unable to validate license [Empty license file]
Nov 22 09:54:40 opi3-ntop ntopng: 22/Nov/2023 09:54:40 [NtopPro.cpp:593] WARNING: [LICENSE] Invalid license [Invalid product]
Nov 22 09:54:40 opi3-ntop ntopng[237402]: 22/Nov/2023 09:54:40 [NtopPro.cpp:593] WARNING: [LICENSE] Invalid license [Invalid product]
Nov 22 09:54:40 opi3-ntop ntopng[237402]: 22/Nov/2023 09:54:40 [NtopPro.cpp:622] WARNING: [LICENSE] You can buy a permanent license at [http://shop.ntop.org](https://can01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fshop.ntop.org%2F&data=05%7C01%7Cdvachon%40CegepGranby.qc.ca%7Ca01ad0541e1e4217bd3808dbec1238b1%7C1de815e43c3e451fad8432bc56901196%7C0%7C0%7C638363335248980864%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=czZK%2BqC1emEe%2BJqXth3b9Z%2BpqLAdZozZBek8KfDzDJY%3D&reserved=0)
Nov 22 09:54:40 opi3-ntop ntopng: 22/Nov/2023 09:54:40 [NtopPro.cpp:622] WARNING: [LICENSE] You can buy a permanent license at [http://shop.ntop.org](https://can01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fshop.ntop.org%2F&data=05%7C01%7Cdvachon%40CegepGranby.qc.ca%7Ca01ad0541e1e4217bd3808dbec1238b1%7C1de815e43c3e451fad8432bc56901196%7C0%7C0%7C638363335248980864%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=czZK%2BqC1emEe%2BJqXth3b9Z%2BpqLAdZozZBek8KfDzDJY%3D&reserved=0)
Nov 22 09:55:52 opi3-ntop ntopng[1233]: 22/Nov/2023 09:55:52 [NtopPro.cpp:350] [LICENSE] Reading license from /etc/ntopng.license
Nov 22 09:55:52 opi3-ntop ntopng[1233]: 22/Nov/2023 09:55:52 [NtopPro.cpp:519] [LICENSE] /etc/ntopng.license: unable to validate license [Invalid product]
Nov 22 09:55:52 opi3-ntop ntopng[1233]: 22/Nov/2023 09:55:52 [NtopPro.cpp:343] [LICENSE] No license file found /etc/ntopng.license: reading license from redis
Nov 22 09:55:52 opi3-ntop ntopng[1233]: 22/Nov/2023 09:55:52 [NtopPro.cpp:523] [LICENSE] Unable to validate license [Empty license file]
Nov 22 09:55:52 opi3-ntop ntopng: 22/Nov/2023 09:55:52 [NtopPro.cpp:593] WARNING: [LICENSE] Invalid license [Invalid product]
Nov 22 09:55:52 opi3-ntop ntopng[1233]: 22/Nov/2023 09:55:52 [NtopPro.cpp:593] WARNING: [LICENSE] Invalid license [Invalid product]
Nov 22 09:55:52 opi3-ntop ntopng: 22/Nov/2023 09:55:52 [NtopPro.cpp:622] WARNING: [LICENSE] You can buy a permanent license at [http://shop.ntop.org](https://can01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fshop.ntop.org%2F&data=05%7C01%7Cdvachon%40CegepGranby.qc.ca%7Ca01ad0541e1e4217bd3808dbec1238b1%7C1de815e43c3e451fad8432bc56901196%7C0%7C0%7C638363335248980864%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=czZK%2BqC1emEe%2BJqXth3b9Z%2BpqLAdZozZBek8KfDzDJY%3D&reserved=0)
Nov 22 09:55:52 opi3-ntop ntopng[1233]: 22/Nov/2023 09:55:52 [NtopPro.cpp:622] WARNING: [LICENSE] You can buy a permanent license at [http://shop.ntop.org](https://can01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fshop.ntop.org%2F&data=05%7C01%7Cdvachon%40CegepGranby.qc.ca%7Ca01ad0541e1e4217bd3808dbec1238b1%7C1de815e43c3e451fad8432bc56901196%7C0%7C0%7C638363335248980864%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=czZK%2BqC1emEe%2BJqXth3b9Z%2BpqLAdZozZBek8KfDzDJY%3D&reserved=0)
root@opi3-ntop:/etc#

**Comment by lucaderi** [comment]
it looks you license is not matching the product.
Can you please report the output of ``ntopng --version`` ?

**Comment by dvachon2018** [comment]
Hello,
dvachon@opi3-ntop:~$ ntopng --version
Version:        6.1.231119 [Enterprise/Professional build]
GIT rev:        dev:a85a63287d12df504ab9328c5a5461a8c20168f1:20231119
Pro rev:        r6164
Built on:       Debian GNU/Linux 11 (bullseye) [Raspberry]
System Id:      LEC533646499602D2--OL
Platform:       aarch64
Edition:        Community
License Type:   Time-Limited [Invalid product]
Validity:       Until Fri Nov 24 05:55:10 2023
dvachon@opi3-ntop:~$

**Comment by dvachon2018** [comment]
![Screenshot_20231124-054625](https://github.com/ntop/ntopng/assets/33327149/63072bb9-1561-40e9-8526-9ccec542bcb4)

**Comment by dvachon2018** [comment]
?

**Comment by lucaderi** [comment]
Your license is for embedded systems (Raspberry or similar) but you are using on an Intel x64. You need to use an embedded system or upgrade the license.

**Comment by dvachon2018** [comment]
no, please look carefully, Platform arch64, on an orange pi 3

![image](https://github.com/ntop/ntopng/assets/33327149/2e57c211-317f-4f4f-9122-e9c9937f4195)

**Comment by dvachon2018** [comment]
?
