### ISSUE TITLE
PCAP files downloaded empty using API

### ISSUE THREAD

**Issue by Alisher-Nabiev** [ntop/ntopng#8057]
Environment:

OS name: Ubuntu
OS version: 18.04.6 LTS
Architecture: x86_64
ntopng version/revision: ntopng Enterprise L v.5.7.231017
What happened:

hi, we are trying to download PCAP files with API:
https://xxxxx/lua/rest/v2/get/pcap/live_extraction.lua?ifid=0&epoch_begin=1701070598&epoch_end=1701070778&bpf_filter=host+xx.xx.xx

and it is always an empty PCAP file we would like to schedule a season with you to see how to resolve the issue please

**Comment by cardigliano** [comment]
@Alisher-Nabiev could you provide the full curl command you are using please?

**Comment by Alisher-Nabiev** [comment]
how can I send you privately?

**Comment by cardigliano** [comment]
sure, drop an email to cardigliano at ntop.org

**Comment by Alisher-Nabiev** [comment]
sended

**Comment by Alisher-Nabiev** [comment]
@cardigliano hi, any news?

**Comment by cardigliano** [comment]
Traffic extraction seems to be working in our lab, using the same API call, both as GET and POST:

curl -u admin:password "http://127.0.0.1:3000/lua/rest/v2/get/pcap/live_extraction.lua?ifid=0&epoch_begin=1701246083&epoch_end=1701246315&bpf_filter=" -o output.pcap

curl -u admin:password -H "Content-Type: application/json" -d '{"ifid": "0", "epoch_begin": 1701246083, "epoch_end": 1701246315, "bpf_filter": "" }' http://localhost:3000/lua/rest/v2/get/pcap/live_extraction.lua -o output.pcap

Did you check the Dump Window in the Traffic Recording Status page, to make sure n2disk was active in the time interval specified in the extraction?

**Comment by Alisher-Nabiev** [comment]
![image](https://github.com/ntop/ntopng/assets/33841389/8577298e-5434-407b-a51f-0aefa02b79ac)

as i can see its on.

i also tried to download pcap files from the GUI and its empty

**Comment by cardigliano** [comment]
Please also provide the Traffic Recording "Status", which is the next Tab

**Comment by Alisher-Nabiev** [comment]
![image](https://github.com/ntop/ntopng/assets/33841389/66b098db-1244-403e-bbb5-e1786a78a5e1)

**Comment by cardigliano** [comment]
Please provide the output of  n2disk1g --version

**Comment by Alisher-Nabiev** [comment]
sent via email

**Comment by cardigliano** [comment]
It seems the dump window is 29/11/2023 10:59:00 - 29/11/2023 11:03:29, are you trying to download pcap traffic using an interval included in this one?

**Comment by Alisher-Nabiev** [comment]
right now i am not trying download anything

**Comment by Alisher-Nabiev** [comment]
any news pls? @cardigliano

**Comment by cardigliano** [comment]
@Alisher-Nabiev I was waiting for a .pcap and .idx file as during the call we realised this was related to tunneled traffic

**Comment by cardigliano** [comment]
This is working using inner host IP as confirmed by mail
