### ISSUE TITLE
Switch Port/Interface Names

### ISSUE THREAD

**Issue by mattdunn4465** [ntop/ntopng#806]
I have a switch, Juniper EX4200, that I would like to monitor two different ports for. I cannot have different collector settings with different interfaces however. Both of those interfaces would use the same collector in ntopng/nprobe. Is there a way to show the switch port name the flow came from? Example

ge-0/0/0.0 is WAN on that switch
ge-0/0/1.0 is WAN2 on that switch

My understanding is i won't see these ports sepereated out in ntopng. I see there is a "-M" flag for ntop but not sure if that make ntopng show this field if that makes sense. Ideas?

**Comment by simonemainardi** [comment]
Hi,

What about adding

[ 10] %INPUT_SNMP                 %ingressInterface             Input
interface SNMP idx
[ 14] %OUTPUT_SNMP                %egressInterface              Output
interface SNMP idx

items to the nprobe export template? You'll be able to see that fields from
any flow details page.

---

The -M parameter is for the legacy ntop and is not relevant for your issue.

---

Also note that in the enterprise edition you will have extra menu entries
for SNMP and sFlow/Netflow devices that will give you additional
information on the switch ports.

Regards,
Simone

**Comment by mattdunn4465** [comment]
I have the enterprise version and when clicking on Sflow it says no active
flows, eventhough all flows are from remote switches

**Comment by simonemainardi** [comment]
@fullmoon4465 can you please report the configurations used both for nprobe and ntopng.

nprobe processes sflow that can potentially come from multiple exporters. Processed sflow messages are then exported to ntopng via zmq (over a counter topic). Information such as deviceIP (the exporter router) and ifIndex (the interface on the router) are transmitted over zmq. When ntopng receives that information it updates some internal states and you'll be able to see that information under Devices->sFlow.

![screen shot 2016-11-11 at 12 54 04](https://cloud.githubusercontent.com/assets/3397663/20214401/4545354c-a80e-11e6-82f4-3398a33222bb.png)

So I think we should make sure that nSflow is actually reaching the nprobe (first) and that the nprobe is actually able to communicate to the ntopng (second).

**Comment by mattdunn4465** [comment]
ntopng.conf

-w=3000
-W=0
-g=-1
-m="192.168.1.0/24, 10.50.0.0/23,10.50.6.0/24, 10.50.13.0/24, 10.50.14.0/24,
10.50.16.0/20, 10.50.32.0/20, 10.50.64.0/20, 10.50.80.0/20, 10.50.96.0/20,
10.50.112.0/21, 10.50.120.0/24"
-d=/storage/ntopng
-G=/var/run/ntopng.pid
-i=tcp://127.0.0.1:5556
-i=tcp://127.0.0.1:5557
-i=tcp://127.0.0.1:62057
-i=tcp://127.0.0.1:62058
-i=tcp://127.0.0.1:62059
--online-license-check

then one of the nprobe.conf

-n=none
-i=none
-t=60
-d=60
-a=0
-e=1
-B=10
-w=128000
-z=0
-g=/var/run/nprobe-vdi-2057-62057.pid
-3=2057
--zmq=tcp://127.0.0.1:62057
--dump-stats=/var/log/nprobe/vdi-2057-62057-0_flows_stats.txt
--online-license-check

The data is getting from my switch to nprobe, then to ntopng as i see data
on other pages then the sflow. But currently i have to get a enterprise
trial again from you which is in another email

**Comment by simonemainardi** [comment]
correct, if you need an extension for the enterprise license contact us privately
