### ISSUE TITLE
Add ClickHouse Secure connection support

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8061]
With ClickHouse you can define secure communications support by using this statement in the clickhouse.conf file

```
root@dell:/# grep tcp_port_secure /etc/clickhouse-server/config.xml
         See also 'tcp_port_secure' for secure connections.
    <!-- <tcp_port_secure>9440</tcp_port_secure> -->
```

In this case, the -F parameter needs to be adapted to support TLS

**Comment by lucaderi** [comment]
Use --secure with clickhouse-client

**Comment by NicoMaio** [comment]
According to the ClickHouse documentation 
https://clickhouse.com/docs/en/guides/sre/ssl-user-auth    
https://clickhouse.com/docs/en/interfaces/cli#configuration_files 

it should be necessary to modify the -F params to receive the clickhouse-client config file path.

**Comment by NicoMaio** [comment]
depends on #8071

**Comment by NicoMaio** [comment]
Verified the implementation
