### ISSUE TITLE
View Interface does not Show all Available Exporters

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8063]
- ntopng -i tcp://127.0.0.1:5555 -i tcp://127.0.0.1:5554  -i view:all
- nprobe -i ethX --zmq tcp://127.0.0.1:5554
- nprobe -i lo --zmq tcp://127.0.0.1:5555

Flow exporters that send flows to port 5556 (just as example) are not visible under the view interface

**Comment by NicoMaio** [comment]
The flow exporters under the 'View' interface are visible. However, in the case of two flow exporters running on the same machine but sending the traffic of two different interfaces (ethX and lo), under the 'View' interface on the 'Flow Exporters List' page, the same flow exporter is duplicated. See  (#8129)
