### ISSUE TITLE
hosts_ports_analysis.lua error "ERR_EMPTY_RESPONSE"

### ISSUE THREAD

**Issue by shisheert** [ntop/ntopng#8064]
**Environment**:
* OS name: Centos 
* OS version: 8
* ntopng version/revision: [ntopng Enterprise M v.6.0.231127 (Rocky Linux release 8.8)|

**What happened**:
Under "Server Ports Analysis" in the dashboard when we click on a port or application it shows no data with an error "ERR_EMPTY_RESPONSE" on all browsers.

Please find the attached snapshot.

**Comment by MatteoBiscosi** [comment]
Verified as fixed, please reopen if need
