### ISSUE TITLE
Add Exporter Menu and Interface Id submenus

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8068]
Similar to #8060

dropdown 1 will contain the exporter IP
once selected you will see two more drop downs
- input and output interface Ids

Use cases
- exporter X: all inIfId and all outIfId
- exporter Y: all incoming traffic on interface K 
- exporter Y: all incoming traffic on interface K egressed on interface U

**Comment by MatteoBiscosi** [comment]
Implemented as requested
