### ISSUE TITLE
Problem with apt-ntop-stable behind authenticated proxy

### ISSUE THREAD

**Issue by gabviv73** [ntop/ntopng#8072]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04
* Architecture: amd64
* ntopng version/revision:  6.0.231116 [Enterprise/Professional build]

**What happened**:
Upgrading to ntop 6 the package can't be fully installed because getting of the gpgp key fails.

The package installation fails with:

```
root@nbox:/etc/nprobe# apt install -f                                                                                                      
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up apt-ntop-stable (2.10-26) ...
Installing ntop GPG key [using proxy http://MyUsername:MyPassword@my.proxy.server:80]. Please wait...
gpg: keyserver receive failed: General error
dpkg: error processing package apt-ntop-stable (--configure):
 installed apt-ntop-stable package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 apt-ntop-stable
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**How did you reproduce it?**
`apt install -f`

The installation script tries to get the key using hkps:// in the --keyserver url.

Manually removing hkps:// from the --keyserver url works:

```
gpg --keyserver-options http-proxy="http://MyUsername:MyPassword@my.proxy.server:80" --no-default-keyring --keyring /usr/share/keyrings/ntop-archive-keyring.gpg --keyserver keyserver.ubuntu.com --recv-keys 
```

Manually installing the key like this does not solve the problem, the post-install script does not check if the key is already installed.

**Comment by lucaderi** [comment]
We have added the check to avoid importing a key that is already present.

If we use --keyring without protocol and port, GPG tries to connect to the remote server port 11371 which is often not open on systems, whereas 443 should be open. If you have problems importing the key, please do it manually but we would lie to avoid changing this behaviour that works for most of our users.
