### ISSUE TITLE
Broken Behaviour Exceptions with View Interfaces

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8073]
Behavioural exceptions with view interfaces do not work as they should be applied to physical interfaces.

Consider making behavioural exceptions global to all interfaces.

**Comment by NicoMaio** [comment]
To reproduce it, add a behavioural check exclusion by selecting Flow Alerts `DNS Invalid Characters` and insert the machine's IP Address where ntopng is running.

Run `dig https://www.repubblica.it`

**Comment by MatteoBiscosi** [comment]
The issue is fixed with the latest ntopng version
![image](https://github.com/ntop/ntopng/assets/49585191/74f29af9-5981-4468-92a3-fce8061169b2)
