### ISSUE TITLE
Windows Glitches

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8074]
On Windows
<img width="316" alt="Screenshot 2023-12-01 at 10 09 02" src="https://github.com/ntop/ntopng/assets/4493366/3614382a-622e-445a-8e71-4bcf0ed353f8">

1. remove CPU/Memory as they are always empty
2. enable Sessings -> Configurations and make sure import/export work

**Comment by NicoMaio** [comment]
Removed charts for Windows with this commit 70a3dc0072d4cff718526629e829dc78ab02285d

With the actual Redis version for Windows is not possible to do the configuration's dump.
