### ISSUE TITLE
Duplicated pulldown menu in the Script PATH

### ISSUE THREAD

**Issue by Yoshihiro-jp** [ntop/ntopng#8077]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04.6 LTS
* Architecture: x86_64
* ntopng version/revision: 6.0.231114 [Enterprise/Professional build]

**What happened**:
Please refer to attached file.
I just put a shell script file in the "/usr/share/ntopng/scripts/shell" but it shows two files.

**How did you reproduce it?**
When you try to set the shell script with the "Add New Endpoint".

**Debug Information**:
Please refer to the attached file.
![shellscript_duplicated](https://github.com/ntop/ntopng/assets/58843707/fc1e7e94-15f1-4a1b-b82d-b67a5366bd3b)

**Comment by DGabri** [comment]
Good evening Yoshihiro, please update ntopng as in ntopng Enterprise XL v.6.1.240529 (Ubuntu 22.04.4 LTS) this error is not reproducing. I created the directory that you provided and only one script appears in the dropdown. Please let me know if there is more that I can do.

![Screenshot 2024-06-10 at 16 58 08](https://github.com/ntop/ntopng/assets/33870399/02729204-4860-4be1-a70f-5a7672141534)

**Comment by Yoshihiro-jp** [comment]
Dear @DGabri ,

The "ntopng Enterprise XL v.6.1.240529" looks like not stable version.
I upgraded it but the version is like below.

$ ntopng -V
Version:        6.0.240608 [Enterprise/Professional build]
GIT rev:        6.0-stable:5069aa4a6259bd0830a33f2ece980612dba5ace9:20240608
Pro rev:        r6175

We provide the stable version to the customer.
So we need the fix for the stable version.

regards,
Yoshihiro

**Comment by DGabri** [comment]
Dear @Yoshihiro-jp,
I checked and fixed the issue. The available endpoints were listed as shell scripts file present inside the folders:
- /scripts/shell -> relative path inside ntopng/
- /usr/share/ntopng/scripts/shell/

Is it possible that you had duplicates files?
Now only files in `/usr/share/ntopng/scripts/shell/` are displayed in the menu.

Thank you for pointing this out
