### ISSUE TITLE
[VS] Improve settings of Hostname To be Used in Notifications

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8083]
In preferences there is an entry to be used as hostname in the web GUI. Please add a reference under VS preference that tells the use that he has to set such preference for setting the URL in VS reports sent via email

<img width="1067" alt="Screenshot 2023-12-02 at 10 27 56" src="https://github.com/ntop/ntopng/assets/4493366/fde8083f-3adc-462e-bc2b-ceb561ce0c2b">

**Comment by NicoMaio** [comment]
Implemented by 2993ff89f393df6db1f9b1661137555533ab4763

**Comment by MatteoBiscosi** [comment]
Verified as fixed
