### ISSUE TITLE
Support alternative sources from Europe

### ISSUE THREAD

**Issue by M-Stenzel** [ntop/ntopng#8084]
**What would you like to add or change?**:
You support VirusTotal and AbuseIP, both U.S. based.
There is [https://www.crowdsec.net/](https://www.crowdsec.net/) , which is a France based solution. 
There is [https://www.apivoid.com/](https://www.apivoid.com/), which is an Italy based solution.

**Why do you and others need this?**:
Support of European IT solutions, to become independent from U. S. solutions.
More freedom of choice.

**Comment by MatteoBiscosi** [comment]
The two lists you suggested are paid services. However we added the possibility to add custom blacklists, so that whatever blacklist is provided, it should work
https://www.ntop.org/guides/ntopng/advanced_features/category_lists.html
