### ISSUE TITLE
Cannot read mark with netfilter to divert traffic 

### ISSUE THREAD

**Issue by IvnSoft** [ntop/ntopng#809]
Hi guys.

I've implemented ntopng in a linux bridge to shape traffic for a couple of internal networks.
Tried the bridging facility and the NFQueue option, but it isn't enough, as i have to implement a big number of different profiles, with specific limits per protocol per client. 

I sorta managed this using tc/qdisc and iptables to divert traffic to the specific qdisc based on ip, port, etc. However, some traffic is not so easy to idenity and thats where ntopng shines.

The documentation says ntopng will mark traffic with the protocol id of the flow. However, i cannot find how to read that mark to add the needed rules to divert traffic. (https://github.com/ntop/ntopng/blob/dev/doc/README.netfilter)

Is it possible to get an example or some tips on how to read such mark ? (will iptables be able to read it ?)

Thanks

**Comment by IvnSoft** [comment]
Is it worth mentioning i bought the license because i was told with it i would be able to do this ???

**Comment by simonemainardi** [comment]
ntopng marks packets using `nf_set_verdict2` or `nf_set_verdict_mark`, depending on what is available. Mark is an int that corresponds to the nDPI protocol id as it is pointed out in the readme you linked.

Once the packet is marked you can use for example iptables mark module to do your actions, e.g., 

`iptables -m mangle -A POSTROUTING -m mark --mark 123 -j DROP`

**Comment by IvnSoft** [comment]
I tried that. (btw, there is an error in your example line)

Ntopng  (ntopng x86_64 v.2.5.161102) is being ran like this : 
ntopng -m 10.3.0.0/16,10.2.0.0/16,10.1.0.0/16,192.168.0.0/16 -i eth0 -i eth1 -i eth2 -i eth3
eth0 and 1 are in a bridge
eth2 and 3 are other bridge
Just to be sure, the test were done with ntopng ran like this : 
ntopng -m 10.3.0.0/16,10.2.0.0/16,10.1.0.0/16,192.168.0.0/16 -i br0 -i br1

I tried the following to check the packets being marked, when using standar IMAP (protocol 0x4 according to the list) in every table i could think of. It wont work. I also put another rule to LOG matching packets with standar connection checking :

iptables -t mangle -A FORWARD -m mark --mark 4 -j LOG --log-prefix "TESTNG "
iptables -t mangle -A FORWARD -p tcp --dport 143 -j LOG --log-prefix "IMAP "

iptables -t mangle -A PREROUTING -m mark --mark 4 -j LOG --log-prefix "TESTNG "
iptables -t mangle -A PREROUTING -p tcp --dport 143 -j LOG --log-prefix "IMAP "

iptables -t mangle -A POSTROUTING -m mark --mark 4 -j LOG --log-prefix "TESTNG "
iptables -t mangle -A POSTROUTING -p tcp --dport 143 -j LOG --log-prefix "IMAP "

iptables -t filter -A FORWARD -m mark --mark 4 -j LOG --log-prefix "TESTNG "
iptables -t filter -A FORWARD -p tcp --dport 143 -j LOG --log-prefix "IMAP "

Any time i make IMAP connections (thunderbird or telnet to input commands directly) i only get the logs from the port matching rule. 
So far, havent been able to get a single match with the mark.

Any ideas?

**Comment by IvnSoft** [comment]
Forgot to mention, the version of ntopng was downloaded from your servers in binary/RPM form.

**Comment by IvnSoft** [comment]
Just to corroborate, also compiled the version from git, and checked that nfq_set_vertict2 was available :   

checking libnetfilter_queue/libnetfilter_queue.h usability... yes
checking libnetfilter_queue/libnetfilter_queue.h presence... yes
checking for libnetfilter_queue/libnetfilter_queue.h... yes
checking for nfq_create_queue in -lnetfilter_queue... yes
checking for nfq_set_verdict2... yes

It also wasnt able to mark (or i wasnt able to get matching marks) from netfilter.

**Comment by IvnSoft** [comment]
Ok, im giving up for today.
I've checked the source code, and cannot find any calls to nfq_set_verdict2 anywhere except the config script and supporting files.

As far as i can tell, packets are not being marked with this call.

**Comment by ValentinaViscarelli** [comment]
@IvnSoft 
your scope is create a bridge and filter/shape the traffic on it. Isn't it?
If so you don't need to manage mark id and iptables.
If you create a linux bridge ntopng isn't able to act in active way on the bridge. 
Ntopng is able to create a bridge for you and it is able to filter and shaping traffic on the bridge.
For example (in this way you create a bridge between eth0 and eth1):
  ntopng -i bridge:eth0,eth1

Please read the user guide (page 61):
https://github.com/ntop/ntopng/blob/dev/doc/UserGuide.pdf

**Comment by IvnSoft** [comment]
The problem with that solution is that the software allow for a limited number of traffic profiles, and limited rules to shape traffic. Right now im running 6 different rules per each navigating host (one for each protocol to watch out) with more than 3000 hosts. And i need to change every single rule via scripting.
Thats why i ruled out the traffic shaping use of ntopng and investigated on the marks.

Now if i make the bridge with ntopng ... will it be able to mark the packets ?

**Comment by ValentinaViscarelli** [comment]
No. The only way to mark the traffic is the using of netfilter queues.
I have added an user case in https://github.com/ntop/ntopng/blob/dev/doc/README.netfilter
It should be fine for you. It tried it and this works for me.

**Comment by IvnSoft** [comment]
Aha.
I will try that way and post my results. 

Thanks

**Comment by IvnSoft** [comment]
I got some luck.
Using NFQUEUE in the PREROUTING/mangle table worked for a couple of hosts. Packets are being marked and correctly identified.
But as soon as i get more traffic going, ntopng says

14/Nov/2016 14:14:49 [NetfilterInterface.cpp:91] ERROR: NF_QUEUE receive error
14/Nov/2016 14:14:49 [NetfilterInterface.cpp:96] Leaving netfilter packet poll loop

And the traffic stops flowing. Restarting ntopng gets me the same 2 lines and no traffic thru.

Im guessing there are some limits on the size/packet number of the queue ? If so, how can i modify it ?

**Comment by ValentinaViscarelli** [comment]
I have added more information to "ERROR: NF_QUEUE receive error" log. 
Please try the tomorrow release and post the new log.
Thanks

**Comment by IvnSoft** [comment]
Ok. 
FYI, i fixed that error with a lot of fine tuning of network parameters. But now im stuck with the default queue length of 1024 in recent kernels (3.16)

 nf_queue: full at 1024 entries, dropping packets(s)

Im still reading how i can change the default (using nfq_set_queue_maxlen perhaps, but looks like a per-app basis).

**Comment by IvnSoft** [comment]
Tried the new ntopng-2.5.161115-1708.x86_64.rpm and pfring-6.5.0-993.x86_64.rpm.
Same issues. 

15/Nov/2016 14:04:25 [Ntop.cpp:1127] Setting local networks to 10.3.0.0/16,10.2.0.0/16,10.1.0.0/16
15/Nov/2016 14:04:25 [Redis.cpp:103] Successfully connected to redis 127.0.0.1:6379@0
15/Nov/2016 14:04:25 [NtopPro.cpp:118] [LICENSE] Read license from Redis [XXXXXX]
15/Nov/2016 14:04:25 [NetfilterInterface.cpp:127] Succesfully connected to NF_QUEUE 0
15/Nov/2016 14:04:25 [NetfilterInterface.cpp:141] WARNING: Disabling user change as otherwise netfilter won't work
15/Nov/2016 14:04:25 [Ntop.cpp:1226] Registered interface nf:0 [id: 7]
15/Nov/2016 14:04:25 [main.cpp:246] PID stored in file /var/run/ntopng.pid
15/Nov/2016 14:04:25 [HTTPserver.cpp:507] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
15/Nov/2016 14:04:25 [HTTPserver.cpp:552] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
15/Nov/2016 14:04:25 [HTTPserver.cpp:555] HTTP server listening on port 3000
15/Nov/2016 14:04:25 [main.cpp:307] Working directory: /var/tmp/ntopng
15/Nov/2016 14:04:25 [main.cpp:309] Scripts/HTML pages directory: /usr/share/ntopng
15/Nov/2016 14:04:25 [Ntop.cpp:270] Welcome to ntopng x86_64 v.2.5.161115 - (C) 1998-2016 ntop.org
15/Nov/2016 14:04:25 [Ntop.cpp:275] Built on CentOS release 6.8 (Final)
15/Nov/2016 14:04:25 [PeriodicActivities.cpp:53] Started periodic activities loop...
15/Nov/2016 14:04:25 [RuntimePrefs.cpp:34] Dumping alerts into syslog
15/Nov/2016 14:04:25 [NtopPro.cpp:262] [LICENSE] ntopng systemId: 8C15C3769205A1D6
15/Nov/2016 14:04:25 [NtopPro.cpp:273] [LICENSE] ntopng license: A111572F25BCDF9A1203566EE4ABF935150739850342E983C4
15/Nov/2016 14:04:25 [NtopPro.cpp:294] [LICENSE] Maintenance is available until Sat Oct  7 14:48:23 2017 [326 days left]
15/Nov/2016 14:04:25 [NetworkInterface.cpp:1578] Started packet polling on interface nf:0 [id: 7]...

Then i sent traffic to NF:0
iptables -t mangle -I PREROUTING 1 -d 10.3.0.0/16 -j NFQUEUE --queue-num 0

and then dmesg flood
[10178161.649367] net_ratelimit: 20243 callbacks suppressed
[10178161.649387] nf_queue: full at 1024 entries, dropping packets(s)
[10178161.649554] nf_queue: full at 1024 entries, dropping packets(s)
[10178161.650734] nf_queue: full at 1024 entries, dropping packets(s)
[10178161.651036] nf_queue: full at 1024 entries, dropping packets(s)
[10178161.651043] nf_queue: full at 1024 entries, dropping packets(s)
[10178161.651047] nf_queue: full at 1024 entries, dropping packets(s)
[10178161.651181] nf_queue: full at 1024 entries, dropping packets(s)
[10178161.651284] nf_queue: full at 1024 entries, dropping packets(s)
[10178161.651724] nf_queue: full at 1024 entries, dropping packets(s)

**Comment by IvnSoft** [comment]
I give up. 
The source code available does not have the queue binding code... As the log says the binding is done in NetfilterInterface.cpp:124 
That file is not available for the recent community version, so i cannot test. It should be simple as adding nfq_set_queue_maxlen(nfQHandle, 65536); before setting mode.

Is there any way to try and compile the pro version to modify that code ?

**Comment by IvnSoft** [comment]
Well, finaly decided to hijack the call to nfq_set_mode and replace it with nfq_set_queue_maxlen and the original nfq_set_mode.
It works, and was able to set the queue len to any number. However, ntopng is not able to keep up with the amount of traffic and latency spikes awfully after a few mins.... So, it will have to go.

The original question from this ticket was answered, so i will close the ticket.
