### ISSUE TITLE
Historical reports no longer working in 6.1.231208

### ISSUE THREAD

**Issue by seaperse** [ntop/ntopng#8091]
![Screenshot 2023-12-08 142938](https://github.com/ntop/ntopng/assets/140824574/a2687412-b228-4376-8b8c-8ae3cdf9fb33)
[flows_export_1702038502.csv](https://github.com/ntop/ntopng/files/13614008/flows_export_1702038502.csv)
![Screenshot 2023-12-08 143144](https://github.com/ntop/ntopng/assets/140824574/d6781490-4316-446a-8e64-a194bbbd4724)

**Environment**:
Rocky Linux release 8.9

**What happened**:
Before in 5.x version the historical report downloads worked fine. 
But today when I needed to download a report, then I am unable to download historical reports anymore.
Please see the attached csv and screenshots, I am using clickhouse for historical reports.
I haven't made any changes to the environment except keeping it up-to-date. with "yum update" and from the ntopng web interface.
Restarting the server or using another browser didn't help.

**Comment by seaperse** [comment]
[flows_export_1702038502.csv](https://github.com/ntop/ntopng/files/13614055/flows_export_1702038502.csv)

**Comment by MatteoBiscosi** [comment]
Hi @seaperse a new build with the fix should be available soon (in a couple of hourse) please update and let me know

**Comment by seaperse** [comment]
Hello

If ntopng Enterprise L v.6.1.231211 rev.22378 is the new build, then the issue persists in this version also.

**Comment by MatteoBiscosi** [comment]
like i said above, please wait for a couple of hours before updating, the builds are still in progress

**Comment by seaperse** [comment]
Hello

They seem to be downloadable now, thank you!
I have a question about the reports. Is it possible to download the report from cli or via api without having to wait for webui to fully load the selected historical flow?

**Comment by cardigliano** [comment]
The csv file is downloaded from the REST API also when using the explorer/GUI, you can check the REST documentation or use the browser inspector to check the API call and use the same from cli or third party applications.
