### ISSUE TITLE
Add top Blacklist Chart

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8092]
Add as indicated in the picture

<img width="1355" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/0238d34f-bea1-45f8-a723-a8ed367fdea9">

<img width="1354" alt="Screenshot 2023-12-10 at 11 22 22" src="https://github.com/ntop/ntopng/assets/4493366/1b3bc4f2-8436-4230-81d5-1ae46031b67f">

the chart of top timeseries (if blacklist counters > 0)

**Comment by MatteoBiscosi** [comment]
Implemented as requested, other than that, exported page to vuejs
![image](https://github.com/ntop/ntopng/assets/49585191/3c61375e-a9c3-4f6e-800a-3bccaad29139)

**Comment by lucaderi** [comment]
Verified as fixed
