### ISSUE TITLE
'TCP Packet Issues' executes the "Endpoint Shell Script" even if there are no alerts.

### ISSUE THREAD

**Issue by Yoshihiro-jp** [ntop/ntopng#8094]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04.6 LTS
* Architecture: x86_64
* ntopng version/revision: 6.0.231127

**What happened**:
I set only on Checks in my ntopng configuration. It is the "Packets Exceeded".
Kindly refer to the attached files.
As you can see the Checks execute the  "Endpoint Shell Script" even if there are no alerts.
Is this a bug or something?

Kindly guide me.

**How did you reproduce it?**
I mentioned above.
![002](https://github.com/ntop/ntopng/assets/58843707/15bcc1b1-b2bf-462c-9398-d6afc621e881)
![004](https://github.com/ntop/ntopng/assets/58843707/c4651c89-0150-416a-ae4e-7b1eb5aa2185)

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @Yoshihiro-jp , I'll check your issue as soon as possible, this is strange, do you have perhaps more than one interface currently analyzing?

**Comment by Yoshihiro-jp** [comment]
Hello, @MatteoBiscosi
Thank you for your answer.

I have changed with only one interface then I did another test  using the "Local Traffic Rules" like attached file.
![local traffic rule](https://github.com/ntop/ntopng/assets/58843707/99c76acc-c575-4403-b996-80fa935c8449)

Using "iperf"(traffic generator) I made 13Mbps from "192.168.63.34" to "192.168.72.254".
My procedure is like below.

16:57:21 Start the iperf with 15Mbps
17:01:44 alert Threshold Crossed
17:01:50 Endpoint Shell Script Executed
17:02:08 Stop the iperf
17:08:53 Endpoint Shell Script Executed ★ This is no needed execution

![problem](https://github.com/ntop/ntopng/assets/58843707/19b2644f-b3e1-4da0-97ce-ac0357dd6fa4)




It looks like that the shell script executed when the alert had been reset.
It should not be executed I think.

What do you think?

regards,
Yoshihiro

**Comment by MatteoBiscosi** [comment]
Hi @Yoshihiro-jp how did you configure the shell script?
In order to simulate your same enviroment and fix the issue.

**Comment by Yoshihiro-jp** [comment]
Hi @MatteoBiscosi ,

Kindly refer to attached files.
![shell script](https://github.com/ntop/ntopng/assets/58843707/e57a7d39-0a67-4469-b039-f646a5d78e3a)
![shell script002](https://github.com/ntop/ntopng/assets/58843707/3d8f83ab-300b-4a7f-901f-ffa450f7cb4b)

And the shell script is below.

root@em05:/usr/share/ntopng/scripts/shell# more shell_script_w.sh
#!/bin/bash
DATE=`date +"%Y%m%d%I%M%S"`
echo $DATE >> /tmp/shell-script_w.log
root@em05:/usr/share/ntopng/scripts/shell#

regards,
Yoshihiro

**Comment by Yoshihiro-jp** [comment]
Dear @MatteoBiscosi ,
Any update information for this case?

regards,
Yoshihiro

**Comment by MatteoBiscosi** [comment]
Verified as fixed
