### ISSUE TITLE
Sort Check Exclusions Alphabetically

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8096]
<img width="802" alt="Screenshot 2023-12-13 at 23 05 38" src="https://github.com/ntop/ntopng/assets/4493366/b7759d64-ce26-4f76-9299-892adc14c9cb">

This for both flow and host exclusions

**Comment by NicoMaio** [comment]
Fixed in pro repo by 4b60ef34c87cb8554733d49c42abdfc97ab36f0e

**Comment by MatteoBiscosi** [comment]
Verified as fixed
