### ISSUE TITLE
[nEdge] Editing a single row in Multicast Forwarding doesn't work

### ISSUE THREAD

**Issue by NicoMaio** [ntop/ntopng#8098]
When clicking on the edit button under the actions dropdown of a single row, the modal doesn't appear.

**Comment by cardigliano** [comment]
Click edit on a rule, then close the modal. Adding a new rule with "+" shows the same edit modal shown before, instead of being empty.

**Comment by NicoMaio** [comment]
Fixed by 4c5191aaef86a3362a51fd545581127050d1aaa8
