### ISSUE TITLE
Incorrect Values for Local Traffic Rules with threshold type Throughput

### ISSUE THREAD

**Issue by NicoMaio** [ntop/ntopng#8099]
The values extracted from TS for the throughput rules are taken from `statistics.value`, which is incorrect. The correct value for the throughput rules must be taken from `statistics.average`.

**Comment by NicoMaio** [comment]
@MatteoBiscosi, with `Flow Exporter Device` rules, the statistics from the TS `flowdev:traffic` and `flowdev_port:traffic` are missing, and they are mandatory for the rules.

**Comment by NicoMaio** [comment]
Fixed in pro repo by 9a12d33d5a1b385df630c1f0413b36c42c146614 and ad36903f81d93a1b2b91c21efa3baa718f9c674e

**Comment by MatteoBiscosi** [comment]
Now the local traffic rules are working as expected.
