### ISSUE TITLE
BGP ASN data not correct

### ISSUE THREAD

**Issue by drolfe** [ntop/ntopng#81]
Ubuntu 14.04.2 LTS 
ntopng x86_64 v.2.0.150531

I see our local ranges from the DC not pick-up the correct ASN, could all ASN resolution be off ?

Below networks show as ISP Elekom [ ASN 44348 ] in MOSCOW
93.158.208.0/20
93.158.200.0/21
The real DATA is Serverius BV [ ASN AS50673 ] in Netherlands

Let me know if you need any more information

**Comment by lucaderi** [comment]
We rely on GeoIP dat files. Please check if they handle this update (so we can download new dat files) or if you need to report them this problem.

**Comment by drolfe** [comment]
Ok I've updated the dat files by hand, lets see if this makes a difference

 root@ntopng:/usr/share/GeoIP# ls -la
total 28220
drwxr-xr-x   2 root root     4096 Jul 12 20:13 .
drwxr-xr-x 109 root root     4096 Jul  9 00:10 ..
-rw-r--r--   1 root root  3916649 Jun 15 06:45 GeoIPASNum.dat
-rw-r--r--   1 root root   769078 Jul  8 11:10 GeoIP.dat
-rw-r--r--   1 root root  3105495 Apr  8  2014 GeoIPv6.dat
-rw-r--r--   1 root root 21086218 Jul  8 12:12 GeoLiteCity.dat

If not I'll report to MaxMind
