### ISSUE TITLE
Cannot upgrade ntopng to Pro version

### ISSUE THREAD

**Issue by ngmacha** [ntop/ntopng#810]
I am new to ntopng, installed and run the free version for some time, and just got yesterday the free pro license as not-to-profit organization (I'm working for UNAIDS). I have generated the license for the SystemID 1982229622-09b1b8a9  with the order ID 1478032923 following the steps below:
 - logged in to ntopng via 127.0.0.1:3000 and went to menu Home -> About;
 - clicked the URL for the System ID, which opened the License Generation page with the System ID already pre-filled; 
 - enterd the OrderID given by you and generated the License;
 - copy/pasted the generated License into the About page and Saved.

However, although after restarting it shows running the Pro [Small Business Edition] v.2.4.270616, there is still a countdown which after about 9 minutes reset the version back to Community Edition.

The license check somehow shows License expired:
C:\Program Files\ntopng>ntopng /c --online-license-check
Starting ntopg
Running ntopng.
02/Nov/2016 16:27:16 [Prefs.cpp:919] Logging into C:\Users\Me\Documents\ntopng.log
02/Nov/2016 16:27:16 [Ntop.cpp:1121] Setting local networks to 127.0.0.0/8
02/Nov/2016 16:27:16 [Redis.cpp:92] Successfully connected to redis 127.0.0.1:6379@0
02/Nov/2016 16:27:16 [NtopPro.cpp:120] [LICENSE] Read license from Redis [2FBA5B5F38A1A823ED93496136C866561509612579F3021622]
02/Nov/2016 16:27:16 [NtopPro.cpp:172] ERROR: [LICENSE] Invalid or missing ntopng License [License expired]
02/Nov/2016 16:27:16 [NtopPro.cpp:185] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
02/Nov/2016 16:27:16 [NtopPro.cpp:187] WARNING: [LICENSE] before returning to community mode
02/Nov/2016 16:27:16 [NtopPro.cpp:188] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
02/Nov/2016 16:27:16 [NtopPro.cpp:189] WARNING: [LICENSE] or run ntopng in community mode starting
02/Nov/2016 16:27:16 [NtopPro.cpp:190] WARNING: [LICENSE] ntopng --community
02/Nov/2016 16:27:16 [PcapInterface.cpp:85] Reading packets from interface NPF_{4C3C8F5C-D348-4329-B745-6947EA34FF70}...

Please kindly advise what must I do to properly upgrade to the Pro version?

**Comment by IvnSoft** [comment]
Just in case, i had a similar problem because i had a file /etc/ntopng.license . removing it made it work.
You are on windows... Not sure if it applies, but if you have such a file, delete it.

**Comment by lucaderi** [comment]
I have invalidated your license. Please deinstall ntopng and install this http://packages.ntop.org/Windows/ntopng-2.4.160627_1-x64.zip then generate a new license.

**Comment by ngmacha** [comment]
Thank you very much guys for quick response!! It's already COB here, so will do tomorrow

Mac Ha - Sent from iPhone

On 3 Nov 2016, at 17:25, Luca Deri <notifications@github.com<mailto:notifications@github.com>> wrote:

I have invalidated your license. Please deinstall ntopng and install this http://packages.ntop.org/Windows/ntopng-2.4.160627_1-x64.zip then generate a new license.

##

**Comment by ngmacha** [comment]
I've removed and reinstalled the version Luca given above - and even without generating the new license, it is now running as Pro for several hours already: 
C:\Users\Me>"C:\Program Files\ntopng\ntopng" /c --online-license-check
Starting ntopg
Running ntopng.
04/Nov/2016 10:07:59 [Prefs.cpp:919] Logging into C:\Users\Me\Documents\ntopng.log
04/Nov/2016 10:07:59 [Ntop.cpp:1121] Setting local networks to 127.0.0.0/8
04/Nov/2016 10:07:59 [Redis.cpp:92] Successfully connected to redis 127.0.0.1:6379@0
04/Nov/2016 10:07:59 [NtopPro.cpp:120] [LICENSE] Read license from Redis [2FBA5B5F38A1A823ED93496136C866561509612579F3021622]
04/Nov/2016 10:08:00 [PcapInterface.cpp:85] Reading packets from interface NPF_{4C3C8F5C-D348-4329-B745-6947EA34FF70}...
04/Nov/2016 10:08:01 [PcapInterface.cpp:90] WARNING: Unable to set packet capture direction
04/Nov/2016 10:08:01 [Ntop.cpp:1267] Registered interface NPF_{4C3C8F5C-D348-4329-B745-6947EA34FF70} [id: 0]
04/Nov/2016 10:08:01 [PcapInterface.cpp:85] Reading packets from interface NPF_{127E2912-8F43-467E-957B-11284442355F}...
04/Nov/2016 10:08:01 [PcapInterface.cpp:90] WARNING: Unable to set packet capture direction
04/Nov/2016 10:08:01 [Ntop.cpp:1267] Registered interface NPF_{127E2912-8F43-467E-957B-11284442355F} [id: 7]
04/Nov/2016 10:08:01 [Ntop.cpp:1279] Registered interface view \Device\NPF_{4C3C8F5C-D348-4329-B745-6947EA34FF70} [id: 0]
04/Nov/2016 10:08:01 [Ntop.cpp:1279] Registered interface view \Device\NPF_{127E2912-8F43-467E-957B-11284442355F} [id: 7]
04/Nov/2016 10:08:03 [HTTPserver.cpp:466] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
04/Nov/2016 10:08:03 [HTTPserver.cpp:509] Web server dirs [C:\Program Files\ntopng\httpdocs][C:\Program Files\ntopng\scripts]
04/Nov/2016 10:08:03 [HTTPserver.cpp:512] HTTP server listening on port 3000
04/Nov/2016 10:08:03 [main.cpp:295] Working directory: C:\Users\Me\Documents
04/Nov/2016 10:08:03 [main.cpp:297] Scripts/HTML pages directory: C:\Program Files\ntopng
04/Nov/2016 10:08:03 [Ntop.cpp:271] Welcome to ntopng x64 v.2.4.160627 - (C) 1998-2016 ntop.org
04/Nov/2016 10:08:03 [Ntop.cpp:276] Built on Windows
04/Nov/2016 10:08:03 [PeriodicActivities.cpp:53] Started periodic activities loop...
04/Nov/2016 10:08:03 [NtopPro.cpp:249] [LICENSE] ntopng systemId: 1982229622-09b1b8a9
04/Nov/2016 10:08:03 [NtopPro.cpp:260] [LICENSE] ntopng license: 2FBA5B5F38A1A823ED93496136C866561509612579F3021622
04/Nov/2016 10:08:03 [NtopPro.cpp:281] [LICENSE] Maintenance is available until Thu Nov 02 11:49:39 2017 [363 days left]
04/Nov/2016 10:08:03 [Ntop.cpp:454] Adding 10.84.62.0/25 as local address for NPF_{4C3C8F5C-D348-4329-B745-6947EA34FF70}
04/Nov/2016 10:08:03 [Ntop.cpp:459] Adding 10.84.62.34/32 as IPv4 interface address for NPF_{4C3C8F5C-D348-4329-B745-6947EA34FF70}
04/Nov/2016 10:08:03 [NetworkInterface.cpp:1536] Started packet polling on interface NPF_{4C3C8F5C-D348-4329-B745-6947EA34FF70} [id: 0]...
04/Nov/2016 10:08:03 [NetworkInterface.cpp:1536] Started packet polling on interface NPF_{127E2912-8F43-467E-957B-11284442355F} [id: 7]...

Does the above show everything is OK? Do I still need to re-generate the license?
Thank you - Mac Ha

**Comment by simonemainardi** [comment]
@ngmacha  the logs enclosed suggest that everything is now ok. Thanks for reporting.
