### ISSUE TITLE
IP Filter doesn't work on SNMP Engaged Alerts Page

### ISSUE THREAD

**Issue by NicoMaio** [ntop/ntopng#8108]
When clicking on the `Device IP` href
<img width="1475" alt="Screenshot 2023-12-15 alle 12 07 21" src="https://github.com/ntop/ntopng/assets/55502486/f3b234ec-441b-4f6a-9a98-fd6166051542">
The filter is broken:
<img width="1473" alt="Screenshot 2023-12-15 alle 12 07 11" src="https://github.com/ntop/ntopng/assets/55502486/69af5b63-0e0d-4323-8a14-f08026004a0e">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
