### ISSUE TITLE
network history

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#811]
I would like to know if it's possible to get a network historic instead of just host history
I managed few networks (ie : 192.168.1.0/24, 192.168.155.0/24, etc....) and I would like to be able to find in history all flows from 192.168.155.0/24 by example
It seems I can do only with host right now ? by example in "client/server host" if I had possibility to enter : "192.168.155.*", that would be great and even better with a cidr writing.

I know I can change "--local-networks" in adding all networks but even in doing that I can see only "new graph traffic" not historical... but I need flows informations (not only graph) 

thanks

nico

**Comment by Niko78** [comment]
in checking mysql request during a host request history, I can see that it is possible, request is like that in changing src and dst (192.168.155.0 <=> 192.168.155.255)

select INET_NTOA(IP_SRC_ADDR) AS IP_SRC_ADDR,INET_NTOA(IP_DST_ADDR) AS  IP_DST_ADDR  ,L4_SRC_PORT,L4_DST_PORT,VLAN_ID,PROTOCOL,FIRST_SWITCHED,LAST_SWITCHED,PACKETS,IN_BYTES  + OUT_BYTES as BYTES,IN_BYTES,OUT_BYTES,idx,L7_PROTO,INFO,PROFILE from  flowsv4 where FIRST_SWITCHED <= 1478170800 and FIRST_SWITCHED >=  1478156400 AND (NTOPNG_INSTANCE_NAME='ntop-ia'OR NTOPNG_INSTANCE_NAME IS  NULL) AND (INTERFACE_ID='4') AND ((IP_SRC_ADDR>=3232275200 AND  IP_SRC_ADDR <= 3232275455) OR   (IP_DST_ADDR>=3232275200 AND IP_DST_ADDR  <= 3232275455)) order by BYTES desc;

so how it is possible in GUI ?

**Comment by simonemainardi** [comment]
Presently, not all the GUI functions support querying networks. You should inspect the code in `scripts/lua/modules/db_utils.lua` and extend these functions to make sure they support ranges of ip. Some of them already have that support but not all of them.

Feel free to provide a pull request. Thank you.

**Comment by Niko78** [comment]
I checked code and I found where the issue could be

64 rsp = expandIpV4Network(host_or_profile)
65 follow = follow .." AND ((IP_SRC_ADDR>="..rsp[1].." AND IP_SRC_ADDR <= "..rsp[2]..")"
66 follow = follow .." OR   (IP_DST_ADDR>="..rsp[1].." AND IP_DST_ADDR <= "..rsp[2].."))"
67 if peer ~= nil and peer ~= "" then
68 rsp = expandIpV4Network(peer)
69 follow = follow .." AND ((IP_SRC_ADDR>="..rsp[1].." AND IP_SRC_ADDR <= "..rsp[2]..")"
70 follow = follow .." OR   (IP_DST_ADDR>="..rsp[1].." AND IP_DST_ADDR <= "..rsp[2].."))"

function "expandIpV4Network()" should have in parameter the complete string researched.
I tried in changing that online and now function works well in putting a network (ie 192.168.155.0/24)

![lua test](https://cloud.githubusercontent.com/assets/17108017/20211785/66da94a8-a800-11e6-9bb4-277b2e142516.PNG)

To eliminate decimal in expandIpV4Network 
return({ addr, math.floor(addr+num_hosts-1) })

I let you change it cause I don't know if there is an impact behind.
thanks

Nico
