### ISSUE TITLE
Various Issues in SNMP Chart

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8111]
[ntopng - SNMP.pdf](https://github.com/ntop/ntopng/files/13691822/ntopng.-.SNMP.pdf)

1. (red) The saved image has a funny name and it is limited to the first few charts
![bug](https://github.com/ntop/ntopng/assets/4493366/da6ad746-c268-4e53-80bd-779f5f95a674)
<img width="920" alt="Screenshot 2023-12-16 at 09 04 05" src="https://github.com/ntop/ntopng/assets/4493366/d0d2942d-8029-4b7c-ba94-4fb706f0aacd">
2. (blue and second red box). SNMP Interface names are not mapped but interfaceIDs are displayed
3. (orange) it is not possible to specify the interface speed (as in the usage chart)
4. (orange) the Usage % must be at the same line of the numerical usage

**Comment by MatteoBiscosi** [comment]
Verified as fixed after various fixes
