### ISSUE TITLE
Implement the ability to Download ntopng Logs on systems OSs

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8114]
This is to request the ability to download the ntopng tracings/logs on systemd-based OSs

**Comment by cardigliano** [comment]
Testing patch set e625e1bfd3faa8863d1259150753e4725b12b713 85f7335e7a25b1a60496c3338abe7b27463686cf

**Comment by cardigliano** [comment]
<img width="315" alt="Screenshot 2023-12-18 at 14 36 51" src="https://github.com/ntop/ntopng/assets/7548711/0d545bf8-d9f1-4b26-a59b-0f3e0dae9c3d">
