### ISSUE TITLE
Implement Fast Polling of SNMP Interfaces in NetFlow/IPFIX Exporters

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8115]
Only for NetFlow/IPFIX Exporters, this is to request the implementation of fast polling (30 sec or 1 min) of interface bytes in/out and their display in the interface charts.

The lua function snmp_utils.getExportersInterfaces() returns the IP addresses and interface IDs to poll

**Comment by lucaderi** [comment]
Backend implemented

**Comment by MatteoBiscosi** [comment]
Frontend implemented in Pro repo

**Comment by lucaderi** [comment]
Verified as fixed
