### ISSUE TITLE
[nEdge] User change from the host page does not work

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#8116]
Change the user from the host page, refresh the page, the old user is still present.

<img width="1271" alt="Screenshot 2023-12-19 at 11 18 14" src="https://github.com/ntop/ntopng/assets/7548711/845ab6c6-90bc-4d8e-aadc-6e922153e55f">

**Comment by MatteoBiscosi** [comment]
Duplicated of #8121
