### ISSUE TITLE
freeradius integration: missing values on columns

### ISSUE THREAD

**Issue by massimoies** [ntop/ntopng#8119]
**What would you like to add or change?**:
Currently radius integration doesn't set some column's values. The most important for us are: FramedIPAddress with ip adress, CallingStationID with mac address.
Optimal solution could be review all fields on radacct.

**Why do you and others need this?**:
It's useful to have more complete integration with freeradius

**Comment by MatteoBiscosi** [comment]
All columns are now correctly populated
