### ISSUE TITLE
dashboard: change user from assign user to another user

### ISSUE THREAD

**Issue by massimoies** [ntop/ntopng#8121]
**What would you like to add or change?**:
After assigning device to a user via API it's not possible to change the user for that device from dashboard.

**Why do you and others need this?**:
To have a functional dashboard

**Comment by MatteoBiscosi** [comment]
It seems that the user group is correctly changed but the change is not instantaneous, but it requires a couple of seconds

**Comment by cardigliano** [comment]
The UI is changing the user pool association and issuing a backend refresh. This takes a bit (1-2 seconds). The UI reads the pool from the backend, thus it is displaying the old pool if re-opening the page during that time.

**Comment by cardigliano** [comment]
This is improved by reducing the pool refresh delay
