### ISSUE TITLE
freeradius integration: radacct missing insertion

### ISSUE THREAD

**Issue by massimoies** [ntop/ntopng#8122]
**What would you like to add or change?**:
If the voucher (username) is present on the table radusergroup, it will not be inserted into the radacct table when /lua/rest/v2/set/pool/members.lua is called.
Example API payload: {"associations": {"7c:d6:61:b2:eb:93" : {"group" : "crewstar", "connectivity" : "pass", "username" : "904945985341", "password" : "904945985341"}}}

**Why do you and others need this?**:
To have more complete freeradius integration

**Comment by MatteoBiscosi** [comment]
Duplicated of #8120

**Comment by MatteoBiscosi** [comment]
Implemented as requested
