### ISSUE TITLE
freeradius integration: fill out radacct.AcctTerminateCause

### ISSUE THREAD

**Issue by massimoies** [ntop/ntopng#8123]
**What would you like to add or change?**:
Add termination cause for the device when /lua/rest/v2/set/pool/members.lua is called with a payload as following:
{"associations": {"7c:d6:61:b2:eb:93" : {"group" : "crewstar", "connectivity" : "reject", "username" : "904945985341", "password" : "904945985341", "reject_cause": "User-Request"}}}

For complete mapping of AcctTerminateCause enum:

AcctTerminateCause_Value_UserRequest:        "User-Request",
AcctTerminateCause_Value_LostCarrier:        "Lost-Carrier",
AcctTerminateCause_Value_LostService:        "Lost-Service",
AcctTerminateCause_Value_IdleTimeout:        "Idle-Timeout",
AcctTerminateCause_Value_SessionTimeout:     "Session-Timeout",
AcctTerminateCause_Value_AdminReset:         "Admin-Reset",
AcctTerminateCause_Value_AdminReboot:        "Admin-Reboot",
AcctTerminateCause_Value_PortError:          "Port-Error",
AcctTerminateCause_Value_NASError:           "NAS-Error",
AcctTerminateCause_Value_NASRequest:         "NAS-Request",
AcctTerminateCause_Value_NASReboot:          "NAS-Reboot",
AcctTerminateCause_Value_PortUnneeded:       "Port-Unneeded",
AcctTerminateCause_Value_PortPreempted:      "Port-Preempted",
AcctTerminateCause_Value_PortSuspended:      "Port-Suspended",
AcctTerminateCause_Value_ServiceUnavailable: "Service-Unavailable",
AcctTerminateCause_Value_Callback:           "Callback",
AcctTerminateCause_Value_UserError:          "User-Error",
AcctTerminateCause_Value_HostRequest:        "Host-Request",

**Why do you and others need this?**:
To have more complete freeradius integration

**Comment by MatteoBiscosi** [comment]
Implemented as requested
