### ISSUE TITLE
freeradius integration: stop octets update about 1GByte

### ISSUE THREAD

**Issue by massimoies** [ntop/ntopng#8124]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. Ubuntu 20.04.6 LTS]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 6.1.231218-22425]

**What happened**:
traffic update on radacct stops around 1GByte (upload+download)

**How did you reproduce it?**
you can connect with username (voucher), assign a group and generate traffic until 1GByte, you will see updating stops with
 SELECT (COALESCE(SUM(AcctInputOctets)+SUM(AcctOutputOctets),0)) FROM radius.radacct WHERE UserName=?; 

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
This is not correct, the accounting continue sending interim updates even after the 1 GB threshold you told, see captured by using tcpdump:
![image](https://github.com/ntop/ntopng/assets/49585191/665be303-8022-4c0d-8bf2-9969b5d3da60)
