### ISSUE TITLE
freeradius integration: acctinputoctets and acctoutputoctets must refer to current session

### ISSUE THREAD

**Issue by massimoies** [ntop/ntopng#8127]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 20.04.6]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 6.1.231218-22425]

**What happened**:
The columns acctinputoctets and acctoutputoctets must refer to current session. Right now, each time that new row is opened under radacct table, the fields acctinputoctets and acctoutputoctets are retained as the summation of all the previous rows with the same username 

**How did you reproduce it?**
You can use a device to connect username, produce traffic and disconnect the device. Repeat the same process for the second time. Now You can see the problem on fields acctinputoctets and acctoutputoctets, the value of acctinputoctets is the same value of first row (instead of being zero), same thing for acctoutputoctets

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Implemented as requested
