### ISSUE TITLE
Freeradius integration: accounting update traffic data

### ISSUE THREAD

**Issue by massimoies** [ntop/ntopng#8128]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 20.04.6]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 6.1.231218-22425]

**What happened**:
The update process of accounting data must set only acctinputoctets and acctoutputoctets columns of radacct table and not other columns. We suppose current process is update all columns because after any manual modification, old values are restored.

**How did you reproduce it?**
You can try to modify a value of FramedIPAddress (for example but could be other column) and the update process will restore old value

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Implemented as requested
