### ISSUE TITLE
The View interface displays duplicated Available Exporters

### ISSUE THREAD

**Issue by NicoMaio** [ntop/ntopng#8129]
- ntopng -i tcp://127.0.0.1:5555 -i tcp://127.0.0.1:5554 -i view:all
- nprobe -i ethX --zmq tcp://127.0.0.1:5554
- nprobe -i lo --zmq tcp://127.0.0.1:5555

The nprobes are running on the same machine, so it is expected that under the 'View' interface, on the 'Flow Exporters List' page, a single Available Flow Exporter with two interfaces is present.

**Comment by lucaderi** [comment]
Verified as fixed but on hsol it is not working yet
