### ISSUE TITLE
The ntopng should have 2 types trigger action.  One is the trigger action and Another is the reset action.

### ISSUE THREAD

**Issue by Yoshihiro-jp** [ntop/ntopng#8130]
**What would you like to add or change?**:
When I talked with @MatteoBiscosi he explained about the trigger action like below.

～snip～
The alert is just sent one time, the check is however executed every 5(depends on settings) minutes. The check is kept in the "engaged state" until the threshold is no more exceeded, when it stops exceeding the threshold the alert is moved in the "relesead state" this was the reason why before 2 shell script were executed, the first one was for the engaged state (the alert is triggered for the first time), the other one was for the released state (the host/interface does not exceed the threshold anymore so the alert is no more present, released). 
if you need with the shell script to trigger something when the alert is seen, you have to use the first alert (with the engaged state), then you can do something else when the alert is no more present (released state). In that case let me know, i'll restore the previous state when 2 shell scripts where triggered. You can capture info from the alert, if you check the STDIN from the shell script, because the alerts info are provided to the shell script by using the STDIN (in json format)
～

So I thought that the ntopng should have 2 types trigger action.  
One is the trigger action and Another is the reset action.

**Why do you and others need this?**:

Like SolarWinds Platform it is much better that the ntopng would have the 2 type trigger actions.
Because users can understand why the action had been executed.

![solar](https://github.com/ntop/ntopng/assets/58843707/94379ed4-582d-471e-8fab-643fd8183943)

**Comment by MatteoBiscosi** [comment]
The issue should be implemented as requested. A new option in the shell script recipient has been added, with the possibility to trigger the shell script on 3 different moments:
- The alert is triggered (when the issue is seen on the network and the alert is triggered)
- The alert is released (when the issue is solved and it is no more seen on the network)
- Alwais (both options above)

![image](https://github.com/ntop/ntopng/assets/49585191/aba91e54-1ceb-4a71-b276-bc4d47996fe1)

**Comment by MatteoBiscosi** [comment]
Implemented as requested

**Comment by Yoshihiro-jp** [comment]
Dear @MatteoBiscosi ,
Is this already implemented in the stable version? Could I test it?
