### ISSUE TITLE
License Page is Empty.

### ISSUE THREAD

**Issue by ferrytimal-hvn** [ntop/ntopng#8131]
**Environment**:
* OS name: [e.g. Ubuntu] FreeBSD 
* OS version: [e.g. 18.04] 14.0
* Architecture: [e.g. amd64] amd64
* ntopng version/revision: [e.g. 5.1.211223} ntopng Community v.5.6.230701

**What happened**:
License page is empty on ntopng

**How did you reproduce it?**
Go to the settings page > Licenses

**Debug Information**:

**Comment by cardigliano** [comment]
@ferrytimal-hvn please move to ntopng 6.0 or 6.1, your version is not supported
