### ISSUE TITLE
Server Port Analysis Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8133]
Table view is broken, chart is ok

<img width="1265" alt="Screenshot 2023-12-23 at 09 50 51" src="https://github.com/ntop/ntopng/assets/4493366/3878918e-c0fc-4275-b4a1-5a72bedb0d70">

**Comment by NicoMaio** [comment]
Fixed a several issue related to this page by 1deb6903cdb6e520bfd11705b5855718dca2909f
and a minor bug by e48ea81c99af180e705f6a5c71b8929d86af8d1d

**Comment by NicoMaio** [comment]
Currently, the two views are generated by querying server hosts with two distinctions:

1. The table page uses `walker_hosts` for its data, while the chart page utilizes `walker_flows`.
2. For the table page, only the local server hosts are considered; whereas, for the chart page, every active flow is analyzed.

Do you have any suggestions, @MatteoBiscosi ?

**Comment by MatteoBiscosi** [comment]
Verified as fixed
