### ISSUE TITLE
Alert notification augmentation - ability to add external query response or trigger custom script

### ISSUE THREAD

**Issue by p27182** [ntop/ntopng#8136]
**What would you like to add or change?**:
When I get a notification like:
`26/12/2023 23:33:37  [Interface: enxa0] [Severity: 🚩 Emergency] [Flow] [Malware Host Contacted] [192.168.2.213 -> 185.193.90.46]
Malware Host Contacted`

It would save me some time to have it automatically do a dns whois/nslookup to see what company it may be publicly affiliated with.  That or allow for alerts to trigger custom scripts that can take content from the alert (like src IP and dst IP) as arguments, and include that in the notification.  That would be really awesome to allow for something like shodan lookup of an ip etc...    

**Why do you and others need this?**:

need is a strong word, but I think that the more ntopng can tell me about something it has deemed suspicious, the more valuable it is.  the more time it can save me by automatically taking the next step when notifying me of some sort of suspcious traffic, the more money it is worth to me.

**Comment by MatteoBiscosi** [comment]
Hi @p27182 what you are asking for can already be implemented.
You can execute shell script when an alert is triggered. So what you can do is the following, create a shell script that get the ntopng alerts, do the dns whois/nslookup and then send those ares to your email or whatever you want
https://www.ntop.org/guides/ntopng/alerts/available_recipients.html
