### ISSUE TITLE
Invalid regex used to filter domain names

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8137]
Dash (-) needs to be supported. Please check if are there other characters that need to be handled.
<img width="826" alt="Screenshot 2023-12-27 at 15 28 23" src="https://github.com/ntop/ntopng/assets/4493366/ca3af7f9-9d0a-45ef-adf1-5e5183fd5598">

**Comment by MatteoBiscosi** [comment]
Regex correctly working now
