### ISSUE TITLE
extended flow search criteria doesn't show 

### ISSUE THREAD

**Issue by s2105** [ntop/ntopng#814]
Hello,

We have installed ntopng 2.4.161004 - Pro Small Business Edition and try to look into extended flow search criteria as discussed here. can you please tell us how to enable it. we tried -F doesn't work 

http://www.ntop.org/wp-content/uploads/2016/10/ntop-Users-Meeting-Sharkfest-2016-[ntopng].pdf

**Comment by simonemainardi** [comment]
what do you mean with it doesn't work?

Please, post the full ntopng command line arguments used and also attach the console output so we can see it there is any error.

thank you

**Comment by simonemainardi** [comment]
@s2105 can you please explain what do you mean with 'it doesn't work'? can you check the ntopng logs to see if there are errors?

**Comment by s2105** [comment]
Hello,

I am trying to put following command 👍 
root@ntopng:~# ntopng -F "mysql;localhost;ntopng;flows;root;5360880;" and
following error is received:

15/Nov/2016 10:57:46 [Ntop.cpp:1121] Setting local networks to 127.0.0.0/8
15/Nov/2016 10:57:46 [Redis.cpp:92] Successfully connected to redis 127.0.0.1:6379@0
15/Nov/2016 10:57:46 [NtopPro.cpp:122] [LICENSE] Reading license from /etc/ntopng.license
15/Nov/2016 10:57:47 [MySQLDB.cpp:549] Attempting to connect to MySQL for interface dummy...
15/Nov/2016 10:57:47 [MySQLDB.cpp:578] ERROR: Failed to connect to MySQL: Access denied for user 'root'@'localhost' (using password: YES) [localhost:root]
15/Nov/2016 10:57:47 [MySQLDB.cpp:549] Attempting to connect to MySQL for interface eth0...
15/Nov/2016 10:57:47 [MySQLDB.cpp:578] ERROR: Failed to connect to MySQL: Access denied for user 'root'@'localhost' (using password: YES) [localhost:root]
15/Nov/2016 10:57:47 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.6.4.1 interface eth0...
15/Nov/2016 10:57:47 [Ntop.cpp:1267] Registered interface eth0 [id: 0]
15/Nov/2016 10:57:47 [MySQLDB.cpp:549] Attempting to connect to MySQL for interface lo...
15/Nov/2016 10:57:47 [MySQLDB.cpp:578] ERROR: Failed to connect to MySQL: Access denied for user 'root'@'localhost' (using password: YES) [localhost:root]

**Comment by emanuele-f** [comment]
Hi @s2105, does the command `mysql -u root -p 5360880 -D ntopng -e "show tables"` execute correctly?

**Comment by simonemainardi** [comment]
remove the last `;` if it is not part of the password and it will work.

**Comment by s2105** [comment]
getting following error.

ubuntu@ntopng:~$ mysql -u root -p 5360880 -D ntopng -e "show tables"
Enter password:
ERROR 1049 (42000): Unknown database '5360880'

**Comment by emanuele-f** [comment]
@s2105 does the tip @simonemainardi gave you work?

**Comment by s2105** [comment]
nope

**Comment by simonemainardi** [comment]
@s2105 as you reported in the error your command is tricking mysql into thinking the database name is your password:

```
ERROR 1049 (42000): Unknown database '5360880'
```

try this `mysql -u root -D ntopng -e "show tables" -p` and insert the password manually to see if your MySQL works OK

**Comment by s2105** [comment]
Here is the output:

root@ntopng:~# mysql -u root -D ntopng -e "show tables" -p
Enter password:
root@ntopng:~#

**Comment by simonemainardi** [comment]
ok that is fine: it means that there are no tables but the database exists.

So re-run  ntopng -F "mysql;localhost;ntopng;flows;root;5360880" and post the output

**Comment by s2105** [comment]
Here is the output:

ubuntu@ntopng:~$ ntopng -F "mysql;localhost;ntopng;flows;root;5360880"
16/Nov/2016 09:26:48 [Ntop.cpp:1121] Setting local networks to 127.0.0.0/8
16/Nov/2016 09:26:48 [Redis.cpp:92] Successfully connected to redis
127.0.0.1:6379@0
16/Nov/2016 09:26:48 [NtopPro.cpp:122] [LICENSE] Reading license from
/etc/ntopng.license
16/Nov/2016 09:26:48 [MySQLDB.cpp:549] Attempting to connect to MySQL for
interface dummy...
16/Nov/2016 09:26:48 [MySQLDB.cpp:589] Succesfully connected to MySQL
[localhost:root] for interface dummy
16/Nov/2016 09:26:48 [main.cpp:223] ERROR: Startup error: missing
super-user privileges ?
ubuntu@ntopng:~$

**Comment by s2105** [comment]
Ok, so looks like I have to start with superuser.

**Comment by s2105** [comment]
Ok, How do you I incorporate command with historic data command.

ntopng -i tcp://127.0.0.1:5556 -d /var/tmp -w 3000 -v >> /dev/null &

**Comment by simonemainardi** [comment]
you should refer to the official users guide that explains how to execute that

**Comment by s2105** [comment]
Ok, Thank you very much for your support.
