### ISSUE TITLE
Alerts Explorer Filters only filtering for one Issue

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#8142]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [ntopng Enterprise L v.6.1.240101 (Ubuntu 22.04.3 LTS) ](https://www.ntop.org/products/traffic-analysis/ntop/)|

**What happened**:
When having multiple issues per alert, filtering only works for what is in the Description.
E.g. in following example the filter and drop down selection only works for 
"HTTP" traffic not allowed for the client according to its NAS application policy
but it is not possible to filter for e.g. Clear-Text Credentials : 
![image](https://github.com/ntop/ntopng/assets/38549755/3127fbe7-c4b3-4cf1-8d49-daef25f5edbf)

<img width="859" alt="Screenshot 2024-01-01 at 12 41 15" src="https://github.com/ntop/ntopng/assets/38549755/1c51a151-dc69-47a9-a478-9b59f1183935">

**How did you reproduce it?**

**Debug Information**:

**Comment by cardigliano** [comment]
I confirm the "Top Alerts" dropdown reports only the alerts set as "Main Issue".
However setting a filter on a "Other Issue" alert works for me, if add a filter manually. Are you saying it is missing a link in the table for adding filters on "other" alerts with a click?

**Comment by martinscheu** [comment]
when I add the filter "clear text credentials" it doesn't give me any results:
<img width="1325" alt="Screenshot 2024-01-02 at 12 11 17" src="https://github.com/ntop/ntopng/assets/38549755/8139a737-212a-42e4-a81d-d2206322756c">
<img width="1286" alt="Screenshot 2024-01-02 at 12 14 01" src="https://github.com/ntop/ntopng/assets/38549755/52ada294-be08-44ae-b3dc-a8e8f4d6297c">

**Comment by martinscheu** [comment]
when I do it with two filters, then the "clear text credentials" is not filtering anything out. So it kind of works half way..
<img width="1096" alt="Screenshot 2024-01-02 at 12 16 46" src="https://github.com/ntop/ntopng/assets/38549755/5d10e9f8-a5af-4ae3-b248-0adb9a504158">

**Comment by cardigliano** [comment]
When you apply multiple filters of the same kind, they are verified as "or", thus the last screenshot looks fine. What seems to be not working is your previous screenshot with no result, if there are alerts with "clear text credentials" in the selected range. I will check again, otherwise I need to verify what's going on on your machine.

**Comment by cardigliano** [comment]
@martinscheu please drop me an email with your availability for a call to check this, I ran several tests but I am not able to reproduce it.

**Comment by cardigliano** [comment]
This applies to SQLite only, works with ClickHouse

**Comment by cardigliano** [comment]
SQLite implementation is missing, we need to check the complexity (and performance) to match the bitmap on SQLite:
https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/alert_store/alert_store.lua#L287

**Comment by NicoMaio** [comment]
SQLite doesn't have native support for bitwise operations on 128-bit integers, and other solutions, such as integrating C++ functions inside the query, shouldn't be considered to avoid a potential decrease in performance. 

So, these types of queries are executed only on ClickHouse as reported in the documentation.
