### ISSUE TITLE
Implement Application Breakdown per Interface of Exporter Devices

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8146]
As of today a collector interfaces keep timeseries of traffic per exporter (only RX and TX)

This is to request to 
- create per interface of each collector time series of application protocols
- depict them as positive/negative timeseries 

Done this it should be possible to select with a drop-down menu the list of devices and with another one the list of interfaces, as display for each interface the top X protocols, or a single one.

**Comment by MatteoBiscosi** [comment]
already available
![image](https://github.com/user-attachments/assets/dde7f3e1-0f6d-434c-9b2f-8ff388a268d1)
