### ISSUE TITLE
[nedge] error on filter host

### ISSUE THREAD

**Issue by tano46** [ntop/ntopng#8147]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04.6 LTS
* Architecture: x86
* nedge version/revision: 6.0.23.1127

**What happened**:
selecting "Local Unicast" option from View -> Hosts -> Filter Hosts, nedge answer with a "Local unicast for User XXX", where XXX is the last user before the Local Unicast entry

![nedge](https://github.com/ntop/ntopng/assets/38938542/cf1c35d2-0e00-4813-af1c-ba23534b956b)
![nedge2](https://github.com/ntop/ntopng/assets/38938542/26b61fcc-c0f3-43ae-8e38-0bf2706a3de4)

**Comment by NicoMaio** [comment]
Fixed by e5a98562e72ad6eeb87c082230fe22ff18f13a98

**Comment by NicoMaio** [comment]
Hi @tano46,
We have released a new stable version with the fix for this issue. Please update and let us know if it is correct now.

**Comment by tano46** [comment]
all seems to be ok now in our testbed, 
thanks :-)

**Comment by NicoMaio** [comment]
Verify as fixed
