### ISSUE TITLE
Mattermost transport not working

### ISSUE THREAD

**Issue by jogalt** [ntop/ntopng#8152]
**Environment**:
* OS name: [Debian]
* OS version: [12]
* Architecture: [Raspberry Pi 4]
* ntopng version/revision: [ntopng Professional (Embedded) v.6.1.240104 (Debian GNU/Linux 12 (bookworm))]

**What happened**:
Attempted to configure Mattermost transport for alerts or reports. 
URL / port / URI is used, per the documentation.
```
https://mattermost.example.com/api/v4/posts
```
I ran a tcpdump for the destination host on my network, from the ntopng server and there's no traffic when I attempt to check the transport.

When I configure a fake discord alert to the same URL:port, I see traffic attempting to leave when I use tcpdump

`tcpdump dst host 10.0.3.136 -vv`
-With the Discord transport (to the same mattermost server)
```
39 packets captured
39 packets received by filter
0 packets dropped by kernel
```
-With the mattermost transport
```
0 packets captured
0 packets received by filter
0 packets dropped by kernel
```
**How did you reproduce it?**
-Configure a mattermost transport and attempt to run a check.
![image](https://github.com/ntop/ntopng/assets/49085678/adc8af62-e3db-42fd-8765-e7483b202fe0)

-Configure recipient
![image](https://github.com/ntop/ntopng/assets/49085678/7029c4b6-2edf-41fb-b62f-17b7372444ab)

**Comment by NicoMaio** [comment]
@martinscheu, could you please help us verify this issue and, if possible, fix it?

**Comment by NicoMaio** [comment]
Hi @jogalt,

Could you please send me your ntopng logs at maio@ntop.org?

**Comment by jogalt** [comment]
@NicoMaio

Logs have been sent.

**Comment by NicoMaio** [comment]
@jogalt 

We released a new version of ntopng with the fix for this issue. Please update and try again.

**Comment by jogalt** [comment]
@NicoMaio 

I'm going to analyze a pcap later. I see traffic now in a dump but everything looks like an SSL error in tcpdump. I'm assuming ntop doesn't have any built-in CA cert store?

**Comment by NicoMaio** [comment]
@jogalt 

Nope, ntopng doesn't have any built-in CA cert store.

**Comment by jogalt** [comment]
After the update and regenerating a new user token for the webhook, everything seems to be working now. Thank you.
