### ISSUE TITLE
journalctl -xe gets flooded with errors from pf_ring

### ISSUE THREAD

**Issue by lhugensc-hwl** [ntop/ntopng#8155]
[ntopng Enterprise XL v.6.0.240104 (Ubuntu 22.04.3 LTS) ]

**What happened**:
journalctl -xe gets flooded with the following errors:
Jan 08 15:13:56 server node[1050]: Error: Command failed: cat /proc/net/pf_ring/stats/2089443-*
Jan 08 15:13:56 server node[1050]: cat: '/proc/net/pf_ring/stats/2089443-*': No such file or directory
Jan 08 15:13:56 server node[1050]:     at ChildProcess.exithandler (child_process.js:308:12)
Jan 08 15:13:56 server node[1050]:     at ChildProcess.emit (events.js:314:20)
Jan 08 15:13:56 server node[1050]:     at maybeClose (internal/child_process.js:1022:16)
Jan 08 15:13:56 server node[1050]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
Jan 08 15:13:56 server node[1050]:   killed: false,
Jan 08 15:13:56 server node[1050]:   code: 1,
Jan 08 15:13:56 server node[1050]:   signal: null,
Jan 08 15:13:56 server node[1050]:   cmd: 'cat /proc/net/pf_ring/stats/2089443-*',
Jan 08 15:13:56 server node[1050]:   stdout: '',
Jan 08 15:13:56 server node[1050]:   stderr: "cat: '/proc/net/pf_ring/stats/2089443-*': No such file or directory\n"
Jan 08 15:13:56 server node[1050]: }
Jan 08 15:13:56 server node[1050]: Failure reading stats for nprobe on nprobe@2057 with PID = 2089443

**How did you reproduce it?**
It is happening all the time.

**Debug Information**:
I tried to configure the path but it still keeps making these errors. How do I resolve it?
It spams about 100.000k lines in about 1.5 hours.

**Comment by cardigliano** [comment]
@lhugensc this does not seem to be related to ntopng, are you running the nboxui perhaps?

**Comment by cardigliano** [comment]
I reduced the verbosity in case the nbox is unable to read stats (e.g. the application is not running). A new build will be available asap. Please open a new issue at https://github.com/ntop/cockpit-ntop if you still experience issues with the new update.
