### ISSUE TITLE
Add Thpt timeseries split for sent and rcvd

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#8156]
Hi,

If possible to have this information as well in the metrics. Or maybe there is already present or can it be calculated?

**Comment by MatteoBiscosi** [comment]
Hi @bogdanbuligadio we already have the Throughput timeseries, is it okay for your needs?
![image](https://github.com/ntop/ntopng/assets/49585191/e1ff7e11-d69b-4283-a6d5-d093cdd50ed4)

**Comment by ghost** [comment]
Hi @MatteoBiscosi I need it in influxdb and I can find it in the measurements that are sent.

**Comment by MatteoBiscosi** [comment]
Timeseries available in rrd are available on influx too.
What we miss is the thpt timeseries per sent and rcvd

**Comment by ghost** [comment]
So there is total thpt? What measurement would that that be?

**Comment by MatteoBiscosi** [comment]
Yes, for the interface, the schema is iface:throughput_bps and you can access that timeserie by using the selected entry shown in the screenshot previously

**Comment by MatteoBiscosi** [comment]
An other timeseries with the throughput is the iface:traffic_rxtx with the thpt divided per sent and rcvd
![image](https://github.com/ntop/ntopng/assets/49585191/50e896c9-1e4e-448d-afec-3e9736a0aa4c)
