### ISSUE TITLE
Unable to add Check Exclusions

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8158]
<img width="1009" alt="Screenshot 2024-01-09 at 10 37 12" src="https://github.com/ntop/ntopng/assets/4493366/b705fce5-f7a3-446a-8863-ac713e2024ef">

**Comment by MatteoBiscosi** [comment]
Issue verified fixed. However it would be good to rework the page, because it is a bit tricky and not user-friendly.
