### ISSUE TITLE
Implement status REST Call

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8159]
Implement a new REST call that allows to fetch from ntopng information about (most of them are part of ntopng GUI)
- license (validity, expire....). See about page
- resources used (memory, etc). See the system page

The result is formatted in JSON.

**Comment by NicoMaio** [comment]
For this new REST, I was thinking about "/lua/rest/v2/get/system/status.lua" as the endpoint
and a JSON Object as a response like this:

`{
   "license_info":{
      "license":"",
      "status":"",
      "maintenance":"",
      "system_id":""
   },
   "resources_used":{
      "system":{
         "CPU_load":"",
         "CPU_states":{
            "active":"",
            "iowait":"",
            "idle":""
         },
         "RAM":{
            "used":"",
            "available":"",
            "total":""
         }
      },
      "ntopng":{
         "RAM_used":""
      }
   }
}`

**Comment by MatteoBiscosi** [comment]
Implemented as requested
