### ISSUE TITLE
Dashboard disappearing

### ISSUE THREAD

**Issue by Dubbeldrank** [ntop/ntopng#816]
I run the stable version of ntopng on ubuntu 16.04. At first login after restarting or rebooting ntopng will open fine, after logging out and in the dashboard is gone and 'Top Flow Talkers' will be displayed full screen. The only way to get the dashboard back is to restart ntopng, but after logging out the same problem appears.
![ntopng_dashboard](https://cloud.githubusercontent.com/assets/23383389/20182420/fffaa316-a761-11e6-9fd0-b696decab7f4.png)

**Comment by simonemainardi** [comment]
I guess you are referring to the professional dashborard. That dashboard is only available for the first 10 minutes.

**Comment by emanuele-f** [comment]
@Dubbeldrank if you need the pro features of ntopng, like the dashboard, historical views and reports, please consider buying the professional version of ntopng. You can find prices at https://shop.ntop.org, contact us if you need any assistance. Thank you.
