### ISSUE TITLE
Implement Exporters Usage Report

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8163]
This is to request a bar graph to list, separately every flow exporter circuit to show how congested each circuit is in terms of the percentage of time being congested. And we can sort the bar graph to show in descending order which site's circuit is most congested to least congested. The axis will be %percentage of time being congested against the site list. The output will be based on the time range for sampling.

<img width="741" alt="PastedGraphic-2" src="https://github.com/ntop/ntopng/assets/4493366/be9fc0cf-2977-4a8c-9414-76d9e70671a8">

**Comment by MatteoBiscosi** [comment]
Implemented as requested
