### ISSUE TITLE
Problem during load the Live Flow dashboard - ntopng crash

### ISSUE THREAD

**Issue by G-Team-Log** [ntop/ntopng#8166]
**Environment**:
* OS name: Ubuntu
* OS version: 22.04.3 LTS
* ntopng Enterprise M v.6.1.240111

**What happened**:
 ntopng crash

**How did you reproduce it?**

Clicking on "Live Flow"

**Debug Information**:
Jan 11 10:39:42 ntopng systemd[1]: ntopng.service: Main process exited, code=killed, status=8/FPE
Jan 11 10:39:42 ntopng systemd[1]: ntopng.service: Failed with result 'signal'.
Jan 11 10:39:42 ntopng systemd[1]: ntopng.service: Consumed 6.946s CPU time.
Jan 11 10:39:47 ntopng systemd[1]: ntopng.service: Scheduled restart job, restart counter is at 1.
Jan 11 10:39:47 ntopng systemd[1]: Stopped ntopng high-speed web-based traffic monitoring and analysis tool.
Jan 11 10:39:47 ntopng systemd[1]: ntopng.service: Consumed 6.946s CPU time.
Jan 11 10:39:47 ntopng systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
Jan 11 10:39:47 ntopng systemd[1]: Started ntopng high-speed web-based traffic monitoring and analysis tool.
Jan 11 10:39:47 ntopng ntopng[19833]: 11/Jan/2024 10:39:47 [Redis.cpp:164] Successfully connected to redis 127.0.0.1:6379@0
Jan 11 10:39:47 ntopng ntopng[19833]: 11/Jan/2024 10:39:47 [Redis.cpp:164] Successfully connected to redis 127.0.0.1:6379@0
Jan 11 10:39:47 ntopng ntopng[19833]: 11/Jan/2024 10:39:47 [NtopPro.cpp:350] [LICENSE] Reading license from /etc/ntopng.license
Jan 11 10:39:47 ntopng ntopng[19833]: 11/Jan/2024 10:39:47 [NtopPro.cpp:513] [LICENSE] /etc/ntopng.license: found valid Enterprise M license
Jan 11 10:39:47 ntopng ntopng[19833]: 11/Jan/2024 10:39:47 [NtopCloud.cpp:26] ERROR: Unable to connect to the ntop cloud
Jan 11 10:39:47 ntopng ntopng[19833]: 11/Jan/2024 10:39:47 [NtopPro.cpp:674] Succefully connected to the ntop cloud
Jan 11 10:39:47 ntopng ntopng[19833]: 11/Jan/2024 10:39:47 [NtopCloud.cpp:26] ERROR: Unable to connect to the ntop cloud
Jan 11 10:39:47 ntopng ntopng[19833]: 11/Jan/2024 10:39:47 [Ntop.cpp:2683] Registered interface 'tcp://*:5559c' [id: 5]
Jan 11 10:39:47 ntopng ntopng[19833]: 11/Jan/2024 10:39:47 [Ntop.cpp:2683] Registered interface 'tcp://*:5558c' [id: 6]
Jan 11 10:39:47 ntopng ntopng[19833]: 11/Jan/2024 10:39:47 [Ntop.cpp:2683] Registered interface 'tcp://*:5560c' [id: 7]
Jan 11 10:39:47 ntopng ntopng[19833]: 11/Jan/2024 10:39:47 [Ntop.cpp:2683] Registered interface 'tcp://*:5555c' [id: 8]
Jan 11 10:39:47 ntopng ntopng[19833]: 11/Jan/2024 10:39:47 [Ntop.cpp:2683] Registered interface 'tcp://*:5556c' [id: 9]
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [Ntop.cpp:2683] Registered interface 'tcp://*:5557c' [id: 10]
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [Ntop.cpp:2683] Registered interface 'tcp://*:5561c' [id: 11]
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [Ntop.cpp:2683] Registered interface 'tcp://*:5562c' [id: 12]
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [Ntop.cpp:2683] Registered interface 'tcp://*:5563c' [id: 13]
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [Ntop.cpp:2683] Registered interface 'tcp://*:5564c' [id: 14]
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [main.cpp:370] PID stored in file /var/run/ntopng.pid
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [Geolocation.cpp:170] Loaded database dbip-asn-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip-asn-lite.mmdb][ip_version: 6]
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [Geolocation.cpp:170] Loaded database dbip-city-lite.mmdb [/usr/share/ntopng/httpdocs/geoip//dbip-city-lite.mmdb][ip_version: 6]
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [Geolocation.cpp:109] Using geolocation provided by DB-IP (https://db-ip.com)
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [HTTPserver.cpp:1642] Found TLS certificate /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [HTTPserver.cpp:1934] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [HTTPserver.cpp:1939] HTTP server listening on 3000
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [HTTPserver.cpp:1946] HTTPS server listening on 443
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [Utils.cpp:860] User changed to ntopng
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3604] Started flow dump loop on interface tcp://*:5559c [id: 5]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [MySQLDB.cpp:944] Successfully connected to ClickHouse [default@127.0.0.1:9004][dbname: <no db>] for interface tcp://*:5559c
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [ClickHouseFlowDB.cpp:74] [ClickHouse] Creating ClickHouse Flow DB
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [ClickHouseFlowDB.cpp:145] [ClickHouse] Database created
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [ClickHouseFlowDB.cpp:43] ClickHouse will dump into /var/lib/ntopng/tmp/clickhouse
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3483] Started flow user script hooks loop on interface 'tcp://*:5559c' [id: 5]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3542] Started host user script hooks loop on interface 'tcp://*:5559c' [id: 5]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3604] Started flow dump loop on interface tcp://*:5558c [id: 6]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [MySQLDB.cpp:944] Successfully connected to ClickHouse [default@127.0.0.1:9004][dbname: <no db>] for interface tcp://*:5558c
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3483] Started flow user script hooks loop on interface 'tcp://*:5558c' [id: 6]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3542] Started host user script hooks loop on interface 'tcp://*:5558c' [id: 6]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3604] Started flow dump loop on interface tcp://*:5560c [id: 7]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [MySQLDB.cpp:944] Successfully connected to ClickHouse [default@127.0.0.1:9004][dbname: <no db>] for interface tcp://*:5560c
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3483] Started flow user script hooks loop on interface 'tcp://*:5560c' [id: 7]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3542] Started host user script hooks loop on interface 'tcp://*:5560c' [id: 7]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3604] Started flow dump loop on interface tcp://*:5555c [id: 8]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [MySQLDB.cpp:944] Successfully connected to ClickHouse [default@127.0.0.1:9004][dbname: <no db>] for interface tcp://*:5555c
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3483] Started flow user script hooks loop on interface 'tcp://*:5555c' [id: 8]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3542] Started host user script hooks loop on interface 'tcp://*:5555c' [id: 8]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3604] Started flow dump loop on interface tcp://*:5556c [id: 9]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [MySQLDB.cpp:944] Successfully connected to ClickHouse [default@127.0.0.1:9004][dbname: <no db>] for interface tcp://*:5556c
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3483] Started flow user script hooks loop on interface 'tcp://*:5556c' [id: 9]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3542] Started host user script hooks loop on interface 'tcp://*:5556c' [id: 9]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3604] Started flow dump loop on interface tcp://*:5557c [id: 10]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [MySQLDB.cpp:944] Successfully connected to ClickHouse [default@127.0.0.1:9004][dbname: <no db>] for interface tcp://*:5557c
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3483] Started flow user script hooks loop on interface 'tcp://*:5557c' [id: 10]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3542] Started host user script hooks loop on interface 'tcp://*:5557c' [id: 10]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3604] Started flow dump loop on interface tcp://*:5561c [id: 11]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [MySQLDB.cpp:944] Successfully connected to ClickHouse [default@127.0.0.1:9004][dbname: <no db>] for interface tcp://*:5561c
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3483] Started flow user script hooks loop on interface 'tcp://*:5561c' [id: 11]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3542] Started host user script hooks loop on interface 'tcp://*:5561c' [id: 11]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3604] Started flow dump loop on interface tcp://*:5562c [id: 12]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [MySQLDB.cpp:944] Successfully connected to ClickHouse [default@127.0.0.1:9004][dbname: <no db>] for interface tcp://*:5562c
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3483] Started flow user script hooks loop on interface 'tcp://*:5562c' [id: 12]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3542] Started host user script hooks loop on interface 'tcp://*:5562c' [id: 12]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3604] Started flow dump loop on interface tcp://*:5563c [id: 13]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [MySQLDB.cpp:944] Successfully connected to ClickHouse [default@127.0.0.1:9004][dbname: <no db>] for interface tcp://*:5563c
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3483] Started flow user script hooks loop on interface 'tcp://*:5563c' [id: 13]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3542] Started host user script hooks loop on interface 'tcp://*:5563c' [id: 13]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3604] Started flow dump loop on interface tcp://*:5564c [id: 14]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [MySQLDB.cpp:944] Successfully connected to ClickHouse [default@127.0.0.1:9004][dbname: <no db>] for interface tcp://*:5564c
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3483] Started flow user script hooks loop on interface 'tcp://*:5564c' [id: 14]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [NetworkInterface.cpp:3542] Started host user script hooks loop on interface 'tcp://*:5564c' [id: 14]...
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [main.cpp:445] Working directory: /var/lib/ntopng
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [main.cpp:447] Scripts/HTML pages directory: /usr/share/ntopng
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [Ntop.cpp:523] Welcome to ntopng x86_64 v.6.1.240111 (dev:f658d8d58f300995022c553e89df86e6b8a06734:20240111)
Jan 11 10:39:48 ntopng ntopng[19833]: 11/Jan/2024 10:39:48 [Ntop.cpp:532] Built on Ubuntu 22.04.3 LTS

-->

**Comment by cardigliano** [comment]
I pushed a fix for this, a new update will be available shortly

**Comment by G-Team-Log** [comment]
Issue solved with the update, thank you very much!
