### ISSUE TITLE
Rework SNMP table

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8168]
<img width="1875" alt="Screenshot 2024-01-12 at 09 23 07" src="https://github.com/ntop/ntopng/assets/4493366/7b7ee0ee-0dc7-45f9-a23b-dcb04d6a8d97">

1. remove column Interface index and put the URL of interface index on interface Name
2. remove the column device type and IP address
3. after the column throughput add a new column with the usage % likely displayed as a the traffic breakdown 
<img width="143" alt="Screenshot 2024-01-12 at 09 27 34" src="https://github.com/ntop/ntopng/assets/4493366/26540a5c-caaf-4f60-a024-cc77cc0bf5ef">

**Comment by NicoMaio** [comment]
Fixed in pro repo by 9ed80ea9de73e38c7786e6a6b562cfaede31e544 and 3563a79b49dfd024857bd18c603bc9a32ce48702

**Comment by MatteoBiscosi** [comment]
Verified as fixed. Other than that, the SNMP page is totally being reworked by using the new VueJS
