### ISSUE TITLE
Configuration for "virtual-nbox" and ntopng

### ISSUE THREAD

**Issue by KUV-VOKL** [ntop/ntopng#817]
Hi,
i using a virtual nbox and ntopng license. - that means the nbox is instaledl on a vmware host in a virtual machine

I want:
- Manage and view the ALL traffic and ALL flows from "Local <-> Remote".
- To see who is eating my bandwidth. (And maybe limit this traffic by a rule)

I have made some configuration wtih NFQUEUE, but i dont know if this correct and get working proberly.

That is my way:
Lokal-Clients <->  Win-DC (192.168.20.1) <->  [ nbox-eth1 (192.168.20.21) < (ntopng)-> nbox-eth2 (192.168.20.22)  ] <-> internet-Router (192.168.20.23) <> Remote-Internet

Sometimes it seems to work, sometimes not. I feel a can not see ALL traffic.

Please help

Thanks a lot
[nbox_configuration_11_11_2016.zip](https://github.com/ntop/ntopng/files/585999/nbox_configuration_11_11_2016.zip)

Klaus

**Comment by ValentinaViscarelli** [comment]
@KUV-VOKL 
An example of NFQUEUE is shown here:
https://github.com/ntop/ntopng/blob/dev/doc/README.netfilter
I tried the use case shown in this document a couple of days ago and it works. Your configuration is different you have just one subnet and in the example there is a NAT.

Step 1) Forget ntopng and NFQUEUE and make sure that you are able to pass the traffic from eth1 to eth2 and viceversa. Don't go to step 2 if this step doesn't work.

Step 2) enable nfqueue rules for iptables and ntopng

**Comment by KUV-VOKL** [comment]
Yes, you are right, i have only one subnet. in witch example there is a NAT ?
I have tried the example, but it seems that does not work. How can i check this ?
What means "Forget ntpnog and nfqueue" ?
Yes, i want to make sure for the traffic from eth1 to eth2, but how ? ipforward ?

**Comment by KUV-VOKL** [comment]
please help me again

**Comment by ValentinaViscarelli** [comment]
@KUV-VOKL 
ntopng configured with nfqueue can work just if you have a forwarding between 2 interfaces that works. So before configuring ntopng and nfqueue make sure that you have configured a forwarding that works (step 1). 
If forwarding doesn't work we cannot help you. The forwarding is made via tools/applications of linux (no ntop applications is need to do this).
After you are sure that you have configured well a forwarding and it works, you take care about ntopng and nfqueue iptables rules (step 2).

**Comment by KUV-VOKL** [comment]
i am not not a linux pro !
i think my forwarding is ok. But:
please give me some hints for configuration of forwarding of my two interfaces, so i can check if my configuarion is working,
thank you for your answers, but please give me more technical help !
Thx

**Comment by KUV-VOKL** [comment]
New update, new problems.
I have version 2.5.161209.
So many alerts on all hosts, so that after 16384 alerts the ntopng crashed.
How can i stop the alerting generally ? - The switch in preferences is grayed out.

The next thing (my main problem) is, i am using netfilter and i only see the remote address when i am using tracert.
On the other site, in ntopng i see obly the traffic from local to remote !
No traffic form remote to local.
What is going on ?

**Comment by simonemainardi** [comment]
The preferences switch is no longer grayed out. Please try and update. If you get a crash please enclose a backtrace / coredump so we can inspect the issue.

**Comment by simonemainardi** [comment]
@KUV-VOKL do you have any updates?

**Comment by KUV-VOKL** [comment]
i made:
apt-get update
apt-get upgrade
reboot

now:
i can swich of allerts, but after i have made the netfilter again for eth1 and eth2, the traffic is stil NOT going through the netfilter like this:

iptables -A FORWARD -i eth1 -j NFQUEUE --queue-num 0
iptables -A FORWARD -i eth2 -j NFQUEUE --queue-num 0

on my win-clients a can perform a 
tracert google.de
but i get this:
  1    <1 ms     *       <1 ms  soma-dc1.soma.local [192.168.20.1]
  2    <1 ms    <1 ms    <1 ms  192.168.20.24
  3     *        *        *     Zeitüberschreitung der Anforderung.
  4     2 ms     1 ms     2 ms  062-146-214-177.rms-online.de [62.146.214.177]
  5     3 ms     2 ms     2 ms  062-146-203-029.rms-online.de [62.146.203.29]
  6     2 ms     2 ms     2 ms  062-146-203-117.rms-online.de [62.146.203.117]
  7     3 ms     3 ms     2 ms  gw.rtr1.colo1.nbg1.content-colo.net [62.146.196.77]
...
In my config 192.168.20.24 is eth0 !!!!!!

nano /etc/network/interfaces shows:
## The loopback interface
auto lo
iface lo inet loopback

## The primary network interface
auto eth0
iface eth0 inet static
 address 192.168.20.24
 netmask 255.255.255.0
 dns-nameservers 192.168.20.1

## Internal
auto eth1
iface eth1 inet static
 address 192.168.20.21
 netmask 255.255.255.0

## External
auto eth2
iface eth2 inet static
 address 192.168.20.22
 netmask 255.255.255.0
 gateway 192.168.20.23
 dns-nameservers 192.168.20.1

 Remember, i have a virtual nbox/ntopng running on vmware/vsphere.

Please help again.

Thanks Klaus

**Comment by lucaderi** [comment]
@KUV-VOKL the nfqueue mechanism is a way to tell the linux kernel to send packets to this special queue where ntopng is listening to. In this configuration all the routing/bridging is implemented by the kernel, and ntopng is inspecting the traffic. So forget ntopng for a second (that is passive) and make sure that the basic networking is ok on your system. I believe that having eth1 and eth2 on the same network isn't a wise choice, for instance. However these are things that have nothing to do with ntopng and this issue.
