### ISSUE TITLE
Invalid Check Exclusion

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8170]
1. Add a host exclusion
<img width="790" alt="Screenshot 2024-01-12 at 15 30 52" src="https://github.com/ntop/ntopng/assets/4493366/7af62d81-af71-428f-87a5-e42129392855">
2. This is the first problem: no category 
<img width="1150" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/1f9dc595-60ed-4227-ae4a-cf334d3eeee3">
3. Now delete the entry: the table is empty
<img width="808" alt="Screenshot 2024-01-12 at 15 35 24" src="https://github.com/ntop/ntopng/assets/4493366/e2cc8f51-be3c-4acf-b82a-2f7113fdbb69">

**Comment by NicoMaio** [comment]
Fix the empty confirm delete dialog in the pro repo by 1ca5917992c171c8a3656925e9f39e23ec349ed9

**Comment by NicoMaio** [comment]
The first issue, 'no category,' is currently correct because, with 'all' alerts, the exclusion does not specify a particular category, leaving the label empty.

**Comment by MatteoBiscosi** [comment]
Verified as fixed
