### ISSUE TITLE
Config option to set network interface for VS

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#8173]
**What would you like to add or change?**:
Now ntopng uses the admin / web GUI network interface for active monitoring / vulnerability scanning.

But when using ntopng for security monitoring, the web GUI and ssh access should not be reachable from the monitored production network.
Further interfaces with mirror port traffic can not be used for active monitoring or vulnerability scanning.

For proper network segmentation and separation of duties it should be possible, to set the active monitoring / vulnerability scanning network interface in the ntopng.conf file, for using a dedicated NIC.

Thank you!

**Why do you and others need this?**:

**Comment by MatteoBiscosi** [comment]
Hi @martinscheu, this feature for the active monitoring part is already implemented and working the one we are missing is the one for vs
![image](https://github.com/ntop/ntopng/assets/49585191/4c3d944d-09c8-427c-a70c-a9da1d94662a)
