### ISSUE TITLE
Only the first twelves private networks are displayed in ntopng

### ISSUE THREAD

**Issue by FedmahnK** [ntop/ntopng#8177]
**Environment**:
* OS name: Debian
* OS version: 11
* Architecture: amd64
* ntopng version/revision: 6.1.240119 / r6292

Hi, I use a list of private networks of my infrastructure. These networks are defined in a separate file, call in ntop configuration via the -m=/path/to/file option.

The file contains a hundred networks, but only 12 are displayed. The config files where not modified with the 5.7 -> 6.1 upgrade.

Regards

**Comment by NicoMaio** [comment]
Hi @FedmahnK 
Have you noticed any errors in ntopng's logs?

**Comment by FedmahnK** [comment]
I activated debug log level for a short period, and the only error I encounter is "No allowed interface found for tcp://127.0.0.1:<my_zmq_tcp>." I am using nprobe which collect sflow data and pass these flow to ntop via local zmq interfaces. 

Don't know why I am seeing theses errors and if it's related to my problem.

**Comment by FedmahnK** [comment]
Ok, I managed to recover almost all my private network by "reordering" the list of network in the file. (for example 172.17.0.0/24 must come before a 172.18.0.0/24. The 5.7 branch didn't have this problem.

Hope it help

**Comment by NicoMaio** [comment]
Could you please send the file containing the list of your private networks to `maio@ntop.org`? 
I want to reproduce it to attempt a fix.

**Comment by NicoMaio** [comment]
When you mention 'but only 12 are displayed,' are you referring to the networks shown on the networks page (https://www.ntop.org/guides/ntopng/web_gui/hosts.html?highlight=networks#networks)? This depends on the current traffic of the hosts in your network. For instance, if you ping a host like 192.168.203.1, the corresponding network, 192.168.203.0/24, should appear on that page.

**Comment by FedmahnK** [comment]
Yes, the networks page only showed a dozen of network. But I am sure that other network are used. When I reordered them in the file, after a ntopng restart, they immediately showed up. From 12 to 100+ networks.

**Comment by FedmahnK** [comment]
I sent another mail with more details and step for reproducing the bug. The order of the network in the file seems to really alter the way of how ntop is parsing it.

**Comment by NicoMaio** [comment]
Hi @FedmahnK,

Could you please send me an email with some traffic in a pcap file so I can try to reproduce this issue?

**Comment by MatteoBiscosi** [comment]
The issue should be fixed with the latest version.
