### ISSUE TITLE
How to remove/uninstall ntopng?

### ISSUE THREAD

**Issue by alexxsun** [ntop/ntopng#818]
Hi guys, this may not be a "good" topic here, but for some reasons, I need to remove ntopng on my Archlinux.
I downloaded it from github, built it and it worked very well.
How can I remove ntopng completely?
The file is in ```\home\myname\programs\ntopng```. Just delete this folder?
How about files in ```/usr/local/share/ntopng/```
Thanks.

**Comment by emanuele-f** [comment]
If you installed it using "make install", then you can run "make uninstall" to remove it. You should also manually remove /var/tmp/ntopng directory and do a redis FLUSHDB on the ntopng database. Moreover, if you used the mysql connection (ntopng option "-F"), then you may need to flush the relevant mysql database too.

Although archlinux is not actually supported by us, you can find an AUR package with a stable ntopng version at https://aur.archlinux.org/packages/ntopng/. Please report there any installation issues. Thank you.

**Comment by kewp** [comment]
Hi I'm on a mac and no idea how to remove this. I don't think I built it manually. Not sure how it was installed (it's not in brew). Any help on doing this manually?

**Comment by kewp** [comment]
Hmm I found a script in my Downloads folder `ntopng-uninstall.sh` that seems to have worked

**Comment by IgorRudy** [comment]
> Hi I'm on a mac and no idea how to remove this. I don't think I built it manually. Not sure how it was installed (it's not in brew). Any help on doing this manually?

Hey there, just had the same issue. 

You can use 

sudo /usr/local/bin/ntopng-uninstall.sh

in your Terminal app. 

as mentioned here:
https://www.ntop.org/guides/ntopng/what_is_ntopng.html#installing-on-macos

Hope i could help

br
