### ISSUE TITLE
Broken Debian package

### ISSUE THREAD

**Issue by takenek** [ntop/ntopng#8180]
I don't saw but Debian remove ntopng package from my system Debian 11 today - we use Enterprise M license if i good remember:
Start-Date: 2024-01-21  07:30:01
Commandline: apt-get dist-upgrade
Upgrade: ntopng-data:amd64 (6.0.240111, 6.0.240117)
Remove: ntopng:amd64 (6.0.240111-22573)
End-Date: 2024-01-21  07:30:15

When i try install back ntopng get error:

root@XXX:~# apt-get install ntopng
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ntopng : Depends: pfring (= 8.6.1-8820) but 8.6.1-8845 is to be installed
E: Unable to correct problems, you have held broken packages.

```
root@XXX:~# apt-cache madison ntopng
    ntopng | 6.0.240117-22602 | https://packages.ntop.org/apt-stable/bullseye x64/ Packages
root@XXX:~# apt-cache madison pfring
    pfring | 8.6.1-8820 | https://packages.ntop.org/apt-stable/bullseye x64/ Packages
```

**Comment by martinfryc** [comment]
I have the same problem on Ubuntu 22.04.

**Comment by takenek** [comment]
> I have the same problem on Ubuntu 22.04.

Do You finded a way to install back? i try install old version but not working :( now completly not working :(

**Comment by martinfryc** [comment]
The fastest way for me was to recover the whole VM from the backup.

**Comment by MatteoBiscosi** [comment]
The issue should now be fixed please do:
apt remove pfring pfring-dkms ntopng
and apt install ntopng
and the issue should be gone

**Comment by takenek** [comment]
```
root@XXX:~# apt-get update
root@XXX:~# apt remove pfring pfring-dkms ntopng
root@XXX:~# apt install ntopng
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pfring : Depends: ndpi (= 4.8.0-4573) but 4.8.0-4608 is to be installed
          Recommends: pfring-dkms (= 8.6.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
root@XXX:~#
```

Need remove ndpi too?

**Comment by martinfryc** [comment]
You have to remove ndpi also. Then it worked for me.

**Comment by takenek** [comment]
Yep saw it there is issue with ndpi too... now it`s working...
Version | ntopng Enterprise M v.6.0.240117 rev.22602 (Debian GNU/Linux 11 (bullseye))
