### ISSUE TITLE
EMail Alerts do not contain the full links to our nTopNG UI

### ISSUE THREAD

**Issue by arosemanhellmann** [ntop/ntopng#8183]
**Environment**:
* OS name: Ubuntu
* OS version: 22.04
* Architecture: Ubuntu 22.04.3 LTS [x86_64] - 64 bit
* ntopng version/revision: ntopng Enterprise XL v.6.0.240104 rev.22539 (Ubuntu 22.04.3 LTS)

**What happened**: we configured some email Alerts that should be send out. - the emails are send out, but the links in those emails do not contain the part of the site itself .  they look like -> 

 /lua/pro/enterprise/snmp_device_details.lua?host=....

**How did you reproduce it?**

- just sent out any email / or retrieve existing alerts - it seems to be the same in all emails

**Debug Information**:

i don't have further info on that. 
-->

**Comment by NicoMaio** [comment]
Hi @arosemanhellmann 
We have released a new stable version of ntopng with the fix for this issue. 
It should be ready in a couple of hours.

**Comment by arosemanhellmann** [comment]
I just updated. The ntopng URL in SNMP Alerts now containes the IP as host .. - but the site is hosted on a CN.domain with SSL. With just the IP we now get an SSL error in the browser as the IP is not part of the SSL Cert. 

Will this also be fixed ? 

Maybe it would be a good option to make this configurable ?

**Comment by NicoMaio** [comment]
Yes, on the 'User Interface' tab under Settings -> Preferences, you can find the preference 'ntopng Host Address.' That should be what you need.

**Comment by arosemanhellmann** [comment]
Hm .. no - i can not find this setting -> 

![image](https://github.com/ntop/ntopng/assets/157366980/53eecc45-c11d-482d-a809-d5b4230831c5)

This here is all in the point you directed me to -> 

![image](https://github.com/ntop/ntopng/assets/157366980/8fab9d41-49a5-451d-bbef-42851db23c72)

**Comment by NicoMaio** [comment]
I just verified, and currently, that preference is not available in the stable version. To use it, you should switch to the development version of ntopng.

**Comment by arosemanhellmann** [comment]
Thx for the update. We want to keep running the stable - do you have an idea how long it will take until this feature arrives in the stable?

**Comment by arosemanhellmann** [comment]
I saw that there is already a new stable i think - is there a place where you show the "change logs"?

**Comment by NicoMaio** [comment]
The latest stable releases are primarily for bug fixes. The next stable version, including new features, is scheduled for release in late spring or early summer.

**Comment by MatteoBiscosi** [comment]
Verified as fixed
