### ISSUE TITLE
SNMP Usage Report Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8184]
<img width="1482" alt="Screenshot 2024-01-22 at 20 21 44" src="https://github.com/ntop/ntopng/assets/4493366/dd339ecd-7d79-494e-b124-4c2c0809d573">

<img width="776" alt="Screenshot 2024-01-22 at 20 24 21" src="https://github.com/ntop/ntopng/assets/4493366/4037c89f-381d-4345-828c-3208de76ac58">

<img width="1570" alt="Screenshot 2024-01-22 at 20 28 41" src="https://github.com/ntop/ntopng/assets/4493366/db535b30-ac18-4a0b-9619-c415bcf8b1c0">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
