### ISSUE TITLE
Filter unique IP addresses when searching historical flows

### ISSUE THREAD

**Issue by Syl4r-v** [ntop/ntopng#8185]
**What would you like to add or change?**:

When searching certain traffic between two networks for example, it would be nice to filter down sources/destination with unique ip addresses. For example if I want to know which addresses poll SNMP from which clients I don't need to see the all the unique flows of every poll, I just want to find out which addresses polled which clients inside timeframe X.

**Why do you and others need this?**:

My use case was that when cleaning up the network and consolidating hosts into fewer subnets I need to check actual traffic between networks so I can create FW rules for the new networks where the hosts will be migrated into.

**Comment by MatteoBiscosi** [comment]
sorry @Syl4r-v i'm not understanding which kind of filter would you like to have, could you please explain better? with a practical example would be perfect

**Comment by Syl4r-v** [comment]
Actually I found out that you already have implemented this kind of feature. Its the "Top client contacts" and "Server contacts" in the historical flows browser. 

The use case for me was to find unique clients that communicate with certain servers. For example if I want to find out which clients have used certain NTP server in the last week. For that, I don't need to see all the flows of every client that have contacted that server, I only need to find out a list of clients that have contacted to server at least once. So a unique list of clients, not list of unique flows.

**Comment by MatteoBiscosi** [comment]
Hi @Syl4r-v ah yes, it's possible with the feature of the Tops in the historical flows, in case you need something different i'd suggest on looking at https://www.ntop.org/guides/ntopng/historical_flows.html#custom-queries it's possible to configure custom queries showing whatever you want from the historical flows
