### ISSUE TITLE
Can't install ntop: 404 on buster_pi arm64 (ipv6)

### ISSUE THREAD

**Issue by softlion** [ntop/ntopng#8190]
**Environment**:
```
uname -a
Linux raspberrypi 5.10.103-v8+ #1529 SMP PREEMPT Tue Mar 8 12:26:46 GMT 2022 aarch64 GNU/Linux
```

**What happened**:
Can't install ntop ?

I followed the instructions. ` dpkg -i apt-ntop.deb` ok.  
But `sudo apt update` failed:

```
sudo apt update

Err:9 https://packages.ntop.org/apt/buster_pi arm64/ Release
  404  Not Found [IP: 2a03:b0c0:2:d0::d27:3001 443]
Hit:10 https://deb.torproject.org/torproject.org buster InRelease
Reading package lists... Done
E: The repository 'https://packages.ntop.org/apt/buster_pi arm64/ Release' does not have a Release file.
```

ping to this IPv6 address is ok.
```
ping6 2a03:b0c0:2:d0::d27:3001
PING 2a03:b0c0:2:d0::d27:3001(2a03:b0c0:2:d0::d27:3001) 56 data bytes
64 bytes from 2a03:b0c0:2:d0::d27:3001: icmp_seq=1 ttl=48 time=360 ms
```

Any clue ?

**Comment by lucaderi** [comment]
64bit packages are available only for bookworm_pi/bullseye_pi (see https://packages.ntop.org)

**Comment by softlion** [comment]
ty I thought I have the latest version.
Updated to Linux raspberrypi 6.1.74-v8+ #1725 SMP PREEMPT Mon Jan 22 13:35:32 GMT 2024 aarch64 GNU/Linux
And it's ok !
