### ISSUE TITLE
Feature request: Alert when a certain VLAN reaches a certain user defined throughput threshold

### ISSUE THREAD

**Issue by Langoor2** [ntop/ntopng#8193]
**What would you like to add or change?**:

I would like to get a way to configure a max througput per vlan and be able to receive an alert when (a certain percentage?) of this gets reached.

**Why do you and others need this?**:

We use ntopng with nprobe to better monitor traffic different VLANS generate and to get insight in the (peak) throughput they do. It would be very useful to be able to set an alert when a vlan reaches (a percentage of) a configurable max througput.

**Comment by MatteoBiscosi** [comment]
This feature can be implemented by using the Rules @NicoMaio

**Comment by NicoMaio** [comment]
Implemented in the pro repo with c972a5cbeee0c81ef3eac174b9a67887db716a32

**Comment by Langoor2** [comment]
We have a pro license so we should have the pro-repo version installed. I just updated to the latest version but I cannot seem to find any way in the UI to configure this?

**Comment by NicoMaio** [comment]
To see the VLAN Rules, it's necessary to enable the VLANs Timeseries in Settings -> Preferences -> Timeseries tab.

**Comment by Langoor2** [comment]
We have this enabled, but I still cannot find the VLAN rules... Am I looking in the wrong places? Running "Professional v.6.0.240207 (Ubuntu 22.04.3 LTS)" at this moment

**Comment by NicoMaio** [comment]
The VLAN rules are currently only available in the development version, not in the stable version.

**Comment by MatteoBiscosi** [comment]
Implemented as requested

**Comment by Langoor2** [comment]
I have vlan timeseries enabled, is this yet in stable? (running [ntopng Professional v.6.0.240703]) I cannot seem to find this option anywhere in the menu
