### ISSUE TITLE
Apply button is disabled

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8194]
<img width="800" alt="Screenshot 2024-01-29 at 10 09 19" src="https://github.com/ntop/ntopng/assets/4493366/cc52cde4-6398-41d7-864e-6fd9a2599473">

You can reproduce it with this custom protocols file

[protos (1).txt](https://github.com/ntop/ntopng/files/14082928/protos.1.txt)

**Comment by lucaderi** [comment]
Apparently, the problem is reproduce with protocol names containing _ or -

**Comment by MatteoBiscosi** [comment]
Verified as fixed
