### ISSUE TITLE
Custom protocol not handled properly

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8195]
When a custom protocol is defined, this is not properly handled even though set as allowed. The result is that false positive alerts are triggered
<img width="948" alt="Screenshot 2024-01-29 at 11 19 53" src="https://github.com/ntop/ntopng/assets/4493366/ed3725e2-4dc7-4b47-af79-25a5f386b7de">
<img width="1456" alt="Screenshot 2024-01-29 at 09 44 22" src="https://github.com/ntop/ntopng/assets/4493366/46c824e7-a91e-4e14-bcd5-5c727fd544bb">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
