### ISSUE TITLE
Interface ID is missing in Hourly flows

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#8197]
The hourly flows table is missing the interface ID now, this makes it impossible to run queries. Please fix it.

Please backport the fix also on the stable branch, including 2532d885db19720ead064cf0c675ad0c97f86caa (pro)

**Comment by NicoMaio** [comment]
Fixed in pro repo by:
6abcac09ff6381249e157899b2fd7f72af848055
c20512bb19564fb3ade6c058caf6805a3131b78f
a8e74d6508d6dc85e3548215aba2e665680244d0

**Comment by MatteoBiscosi** [comment]
Verified as fixed
