### ISSUE TITLE
 Page "/lua/login.lua" was not found

### ISSUE THREAD

**Issue by Drewshg312** [ntop/ntopng#82]
Hi! Successfully installed ntopng from homebrew. Started redis server and started ntopng: `$ sudo ntopng`. When going to `localhost:3000` in browser, getting this:

![untitled](https://cloud.githubusercontent.com/assets/10493450/8636687/1bb803e6-2824-11e5-85f7-86ab23e841ab.jpg)
Could you please point me in right direction. Thank you.

**Comment by lucaderi** [comment]
Have you installed the v2 of ntopng? If so under /usr/local/ntopng do you see the files?

**Comment by Drewshg312** [comment]
Yeah I've already solved the problem:
https://github.com/Homebrew/homebrew/issues/41637#issuecomment-120756355
