### ISSUE TITLE
Unable to get timeseries data

### ISSUE THREAD

**Issue by barsigor** [ntop/ntopng#8202]
**Environment**:
* OS name: Ubuntu
* OS version: 22.04
* Architecture: amd64
* ntopng version/revision: ntopng Professional v.6.0.231219 rev.22435 

I'm trying to get timeseries data from API, with this command:

curl -s --cookie "user=USERNAME; password=PASSWORD" ["http://IP_ADDRESS:3000/lua/rest/get/timeseries/ts.lua?ts_schema=iface:traffic&ts_query=ifid:1&extended=1"](http://IP_ADDRESS:3000/lua/rest/get/timeseries/ts.lua?ts_schema=iface:traffic&ts_query=ifid:1&extended=1)

curl get a valid connection but i don't get any data.

**Comment by MatteoBiscosi** [comment]
Please see https://www.ntop.org/guides/ntopng/api/rest/api_v2.html
The url is wrong and you miss the timestamp (epoch_begin and epoch_end)
![image](https://github.com/ntop/ntopng/assets/49585191/76428498-f0b2-4a1c-a2eb-92b8af8e3d39)

You can check and test the rest api even from ntopng
![image](https://github.com/ntop/ntopng/assets/49585191/c9b8ebfa-73e6-4b9f-9430-aadf8a56b3e6)

**Comment by barsigor** [comment]
Thanks, but i need the timeseries, if i try with the url in documentation:

curl -s -u USER:PASSWORD "
http://172.25.1.29:3000/lua/rest/get/timeseries/ts.lua?ts_schema=iface:traffic&ts_query=ifid:1&extended=1&epoch_begin=1707146891&epoch_end=1707148891
"

i get an empty response.


Il giorno lun 5 feb 2024 alle ore 11:00 Matteo Biscosi <
***@***.***> ha scritto:
