### ISSUE TITLE
Extend Preferences with Message Broker 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8205]
Add a new entry in the preferences named " Message Broker" that implements
- a toggle button MQTT / NATS
- for each entry: username, password, broker list

**Comment by MatteoBiscosi** [comment]
To show the preferences, set the hidden parameter to false:
![image](https://github.com/ntop/ntopng/assets/49585191/8d42b53c-a9d2-459e-a5a6-ca14ce0bce9c)
