### ISSUE TITLE
The "Local traffic Rule" throughput calculation looks like strange

### ISSUE THREAD

**Issue by Yoshihiro-jp** [ntop/ntopng#8206]
**Environment**:
* OS name: [e.g. Ubuntu] Rocky Linux
* OS version: [e.g. 18.04] 9.1 (Blue Onyx)"
* Architecture: [e.g. amd64] x86_64 
* ntopng version/revision: [e.g. 5.1.211223] 
Version:        6.0.240131 [Enterprise/Professional build]
GIT rev:        6.0-stable:fb8dc80cd38151c22278e0466e0a5302aa71a2d0:20240131
Pro rev:        r6160

**What happened**:
The interface throughput should be less than 1Gbps but the "Local traffic Rule" throughput reports more than 2.73Gpbs....

**How did you reproduce it?**
Set the  "Local traffic Rule" throughput on the interface like attached file.
This screen shot is my environment.
![local_traffic_rules001](https://github.com/ntop/ntopng/assets/58843707/19a91017-64d5-4ea3-9db1-c10a2b4f4e9e)

**Debug Information**:
Look at the alert with the attached file.
This screen shot is my customer's environment.
<img width="870" alt="002" src="https://github.com/ntop/ntopng/assets/58843707/f797ee13-c83f-4b06-91aa-e3c8f264a699">

I asked to change the scope of the time series then the maximum throughput  is around 123Mbps(RX) + 9.24Mbps(TX). 
The 2.73Gpbs is not correct I think.

<img width="855" alt="003" src="https://github.com/ntop/ntopng/assets/58843707/71c06c5c-115a-4b4f-9c39-494d4fc72d0c">

**Comment by NicoMaio** [comment]
Fixed by backporting the fixes made for #8099 in the stable branch

**Comment by NicoMaio** [comment]
Hi @Yoshihiro-jp,
The new stable version with the fix for this issue should be ready. 
Please update and let us know if it's alright now.

**Comment by Yoshihiro-jp** [comment]
> Hi @Yoshihiro-jp, The new stable version with the fix for this issue should be ready. Please update and let us know if it's alright now.

Dear @NicoMaio 
Looks like be fixed.
Thank you for your prompt action.

regards,
Yoshihiro
![Uploading fixed.png…]()

**Comment by NicoMaio** [comment]
Verified as fixed.
