### ISSUE TITLE
Add Search in SNMP Interfaces

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8213]
With many interfaces, the search box is compulsory: please add it 

<img width="1362" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/4cfade91-38f9-461b-8f85-7838e0c48702">

Both under a single or on all interfaces. The search is on the column Interface Name

**Comment by NicoMaio** [comment]
Fixed by a2100950119e44a87d02821b064f80960c440ab1 and in the PRO repo by 495493fada50fe76fa2974285cd6873ed72a4cef

**Comment by MatteoBiscosi** [comment]
Missing the search box in the all view

**Comment by lucaderi** [comment]
<img width="1814" alt="Screenshot 2024-05-02 at 19 03 48" src="https://github.com/ntop/ntopng/assets/4493366/506fb631-af7e-47d7-93ab-ae3b03fb38c5">

02/May/2024 19:03:29 [LuaEngine.cpp:1499] WARNING Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/snmp/metric/interfaces.lua][/usr/share/ntopng/pro/scripts/lua/modules/snmp_utils.lua:1193: bad argument #1 to 'lower' (string expected, got nil)]
02/May/2024 19:03:28 [LuaEngine.cpp:1499] WARNING Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/snmp/metric/interfaces.lua][/usr/share/ntopng/pro/scripts/lua/modules/snmp_utils.lua:1193: bad argument #1 to 'lower' (string expected, got nil)]

Reproduce it on hsol

**Comment by NicoMaio** [comment]
Fixed in the PRO repo by b86797fd75108fb05cc2b159ed3c3cf663f518a6

**Comment by MatteoBiscosi** [comment]
Verified as fixed
