### ISSUE TITLE
ntopng files not available for Ubuntu 22.04 arm64

### ISSUE THREAD

**Issue by paulgiordano** [ntop/ntopng#8214]
Looking to install Ubuntu 22.04 arm64, the apt directories are empty.
![image](https://github.com/ntop/ntopng/assets/19802449/44ecd461-470b-4e82-9a8a-924ddb751952)

**Comment by lucaderi** [comment]
For ARM 64 please use the Debian12 packages. We do not build for Ubuntu22 ARM
