### ISSUE TITLE
Disable view links for Enterprise L or higher.

### ISSUE THREAD

**Issue by NicoMaio** [ntop/ntopng#8215]
<img width="1360" alt="sankey" src="https://github.com/ntop/ntopng/assets/55502486/0ca0ef42-dd64-4806-9e5b-3e029de54f1f">

**Comment by NicoMaio** [comment]
Fixed in the pro repo by 53bd4760cfbc9b4a38718e67dcefdfd7d1402ca9

**Comment by MatteoBiscosi** [comment]
Verified as fixed
