### ISSUE TITLE
Host tab to historical appears to have a link issue

### ISSUE THREAD

**Issue by dkggpeters** [ntop/ntopng#8217]
**Environment**:
* OS name: FreeBSD (PFSenese 23.09.1)
* OS version: 14.0
* Architecture: amd64
* ntopng version/revision: 6.1.240207

**What happened**:

In the host screen seleting the Historical option appears to have a lnk issue.

![image](https://github.com/ntop/ntopng/assets/63671969/395e0515-5dd2-49f1-ab72-2c9ce1b62916)

Link for the below

http://10.57.1.1:3000/lua/db_search.lua?ifid=2%3Beq&epoch_begin=1707746211&epoch_end=1707748011&aggregated=false&query_preset=&count=&ip=10.57.1.148%3Beq

![image](https://github.com/ntop/ntopng/assets/63671969/a4129df3-bbdb-43c6-86f4-c09b881056e4)

After deleting the %3Beq above after ifid=2

Link for the below

http://10.57.1.1:3000/lua/db_search.lua?ifid=2&epoch_begin=1707746763&epoch_end=1707748563&aggregated=false&query_preset=&count=&ip=10.57.1.148%3Beq

![image](https://github.com/ntop/ntopng/assets/63671969/8b8f8750-f3b4-4378-bd96-f89b06701b80)

**Comment by MatteoBiscosi** [comment]
Hi @dkggpeters sorry for the late response but i missed this issue.
Update to the latest version and let me know, now the issue should be fixed, there was an issue with the url of the link:
`http://192.168.2.222:3000/lua/db_search.lua?ifid=0&epoch_begin=1709109973&epoch_end=1709111773&aggregated=false&query_preset=&count=&ip=192.168.2.222%3Beq`
In case it does not work, please reopen the ticket
