### ISSUE TITLE
The topology (table view) on the SNMP Device details page is broken

### ISSUE THREAD

**Issue by NicoMaio** [ntop/ntopng#8219]
An empty table error is displayed when clicking on the 'Topology' navbar item in ntopng. 
However, when using the topology icon, data is shown.

**Comment by MatteoBiscosi** [comment]
The issue is fixed, however the calculation of Thpt is probably wrong, cannot be NaN value
![image](https://github.com/ntop/ntopng/assets/49585191/493940a1-1967-44fe-8cca-43f0d4acbfd9)

**Comment by MatteoBiscosi** [comment]
The issue is fixed now, thanks
