### ISSUE TITLE
ntopng is not able to empty NFQUEUE fast enough

### ISSUE THREAD

**Issue by IvnSoft** [ntop/ntopng#822]
Hi guys.

I've been trying to use ntopng to apply shaping to stations based on protocol. I bought a pro license, as i was told that it was able to mark packets and i would be able to classify using that mark.

The problem is, according to the documentation now, is that ntopng only marks packets when using NFQUEUE, which seems to work fine for a couple of hosts. As soon as i get enough traffic (>50mbps) i get different kinds of errors.

At first, i got 
16/Nov/2016 00:01:49 [NetfilterInterface.cpp:91] ERROR: NF_QUEUE receive error: [len: -1][errno: 105]
16/Nov/2016 00:01:49 [NetfilterInterface.cpp:96] Leaving netfilter packet poll loop
and inmediatly ntopng stopped accepting traffic on the queue.
This was sort of fixed with some sysctl optimizations (attached below). 

Then, i started to get dropped packets by the kernel 

> Nov 15 23:59:17 kernel: nf_queue: full at 1024 entries, dropping packets(s). Dropped: 18600
> Nov 15 23:59:17 kernel: nf_queue: full at 1024 entries, dropping packets(s). Dropped: 18601

The pro version creates a queue using nfq_create_queue , and doesnt allow to modify its current maxlen. I hijacked the call to nfq_set_mode in order to call that call and nfq_set_queue_maxlen. This way i was able to modify the max entries to 32768. ( thats the number where the errors stopped).

However, i am back at the first error. After some time (depending on traffic, could be 20 seconds to a minute) ntopng reports the error and stops accepting packets.

> 16/Nov/2016 00:01:49 [NetfilterInterface.cpp:91] ERROR: NF_QUEUE receive error: [len: -1][errno: 105]
> 16/Nov/2016 00:01:49 [NetfilterInterface.cpp:96] Leaving netfilter packet poll loop

 The system is a 4 cpu (xeon e5504) with 16gb ram, with broadcom NetXtreme gigabit cards. eth2 connects stations in a private subnet , and eth1 provides internet connection. 

  Load on the server is negligible (avg load never goes over 0.15). I am using iptables/nat to block navigation to certain stations, and to masquerade/snat.

  Is there something wrong with my setup ? o ntopng is not able to mark so much traffic using nfqueue ? 

Below, logs 

> 16/Nov/2016 00:14:15 [RuntimePrefs.cpp:34] Dumping alerts into syslog
> 16/Nov/2016 00:14:15 [PeriodicActivities.cpp:53] Started periodic activities loop...
> 16/Nov/2016 00:14:15 [Ntop.cpp:275] Built on CentOS release 6.8 (Final)
> 16/Nov/2016 00:14:15 [Ntop.cpp:270] Welcome to ntopng x86_64 v.2.5.161116 - (C) 1998-2016 ntop.org
> 16/Nov/2016 00:14:15 [main.cpp:309] Scripts/HTML pages directory: /usr/share/ntopng
> 16/Nov/2016 00:14:15 [main.cpp:307] Working directory: /var/tmp/ntopng
> 16/Nov/2016 00:14:15 [HTTPserver.cpp:555] HTTP server listening on port 3000
> 16/Nov/2016 00:14:15 [HTTPserver.cpp:552] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
> 16/Nov/2016 00:14:15 [HTTPserver.cpp:507] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
> 16/Nov/2016 00:14:15 [main.cpp:246] PID stored in file /var/run/ntopng.pid
> 16/Nov/2016 00:14:15 [Ntop.cpp:1226] Registered interface nf:0 [id: 9]
> 16/Nov/2016 00:14:15 [NetfilterInterface.cpp:141] WARNING: Disabling user change as otherwise netfilter won't work
> 16/Nov/2016 00:14:15 [NetworkInterface.cpp:1578] Started packet polling on interface nf:0 [id: 9]...
> 16/Nov/2016 00:14:15 [NetfilterInterface.cpp:127] Succesfully connected to NF_QUEUE 0
> 16/Nov/2016 00:14:15 [NetfilterInterface.cpp:96] Leaving netfilter packet poll loop
> 

Traffic during the tests on eth2 was about 80200 kbits/s ( reported by iptraf before and after running ntopng)

This is my hijacking .so

```
    int nfq_set_mode(struct nfq_q_handle *qh,u_int8_t     mode,u_int32_t  range)
    {
      printf("Hijacker: Hijacking nfq_set_mode %d , %d\n", mode,range);
      nfnl_rcvbufsiz(nfq_nfnlh(qh->h), 32768*16384);
      real_nfq_set_mode = dlsym(RTLD_NEXT, "nfq_set_mode");
      if(real_nfq_set_mode(qh, NFQNL_COPY_PACKET, 1000 ) < 0) {
        printf("Hijacker: Cannot set mode %d/%d\n", mode,range);
        return -1;
      }
       u_int32_t qlen = 4096;
      if (nfq_set_queue_maxlen(qh, qlen) < 0)
      {
          printf("Hijacker: Cannot set queue len \n");
          exit(1);
      }
   }
```

The ntopng process was set nice to -20, alerts disabled, dns resolution disabled,  tried cpu affinity (for interrupts and process) and some sysctl changes

```
sysctl net.ipv4.ip_forward=1
sysctl net.ipv4.tcp_synack_retries=2
sysctl net.ipv4.ip_local_port_range="2000 65535"
sysctl net.ipv4.tcp_rfc1337=1
sysctl net.ipv4.tcp_fin_timeout=15
sysctl net.ipv4.tcp_keepalive_time=300
sysctl net.ipv4.tcp_keepalive_probes=5
sysctl net.ipv4.tcp_keepalive_intvl=15
sysctl net.ipv4.tcp_max_tw_buckets=2880000
sysctl net.ipv4.tcp_tw_recycle=1
sysctl net.ipv4.tcp_tw_reuse=1
sysctl net.core.rmem_default=62914560
sysctl net.core.rmem_max=99999999
sysctl net.core.wmem_default=62914560
sysctl net.core.wmem_max=99999999
sysctl net.core.somaxconn=32768
sysctl net.core.netdev_max_backlog=65536
sysctl net.core.optmem_max=25165824
sysctl net.ipv4.tcp_mem="1310720 2621440 5242880"
sysctl net.ipv4.udp_mem="1310720 2621440 5242880"
sysctl net.ipv4.tcp_rmem="873800 167772160 1677721600"
sysctl net.ipv4.udp_rmem_min=163840
sysctl net.ipv4.tcp_wmem="655360 167772160 1677721600"
sysctl net.ipv4.udp_wmem_min=163840

```

Let me know if you need more info , or if it cannot be done.

**Comment by IvnSoft** [comment]
Kept trying on different bridges i have available.
The best i could manage was with the optimizations shown above, and using ~25 nfqueues (ntopng wouldnt let me use more than 30)
The best i could achieve was about 230mbps (at 16.000pps aprox). When the pps went over 16k, latencies went up, and started loosing packets. 
When leaving ntopng just monitoring the network bandwidth reached up to 760mbps (80.000pps).

Im guessing its not feasible to manipulate so many packets within userspace. 

Will using zc drivers make a difference ? (im guessing no, because of the name)

**Comment by ValentinaViscarelli** [comment]
@IvnSoft 
Sorry for delay. I verified "NF_QUEUE receive error" and I included the code you proposed us.
You can find this modify in tomorrow release.
Thanks very much.
About the speed I cannot verify the speed problem you said.
I made these tests with a ftp transfer:
1) just with ip forwarding (without nfqueue and ntopng) I got about 40 MBytes/sec.
2) with nfqueue and ntopng activated and with just one netfilter queue I got about 38 MBytes/sec
So more or less they are the same.
Recently we have made some modifies to the shapers, bridge and netfilter queues.
Please update your system and if you still have the problem please open again the issue.
Thanks.
