### ISSUE TITLE
The Active ICMP Monitoring has selected the wrong network interface

### ISSUE THREAD

**Issue by NicoMaio** [ntop/ntopng#8220]
Performing an ICMP active monitoring on a network interface without IP, the pings are redirected to a network interface with IP, such as the management one.

**Comment by lucaderi** [comment]
Fixed by
- https://github.com/ntop/ntopng/issues/8220
- https://github.com/ntop/ntopng/commit/1f556fece767bc50ce145417dda154a3c70dfee8
