### ISSUE TITLE
Incorrect interface when adding a new active monitoring

### ISSUE THREAD

**Issue by MatteoBiscosi** [ntop/ntopng#8222]
![image](https://github.com/ntop/ntopng/assets/49585191/23aa4db3-7d99-49b4-9205-936e105b6ce2)

**Comment by NicoMaio** [comment]
Fixed by a6862ed0dee1a6f3d5cb07af329e14f33e76753f

**Comment by MatteoBiscosi** [comment]
Verified as fixed, please reopen if needed
