### ISSUE TITLE
Time Picker Takes Local Browser time (instead of remote host) when setting Last XXX

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8223]
<img width="1598" alt="Screenshot 2024-02-16 at 11 45 22" src="https://github.com/ntop/ntopng/assets/4493366/9a934ebc-6ca3-4362-a2bc-674ed1d1412c">

**Comment by MatteoBiscosi** [comment]
If the timezone is set correctly on the server the range-time picker has no issue.
(Timezone set America/New York)
However a restart of ntopng is needed to correctly see the timezone.
![image](https://github.com/ntop/ntopng/assets/49585191/00665b5c-5a64-4716-9618-3aa66c3fc170)
