### ISSUE TITLE
Add Toggle to disable SNMP Polling

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8224]
Similar to Network Discovery
<img width="764" alt="Screenshot 2024-02-16 at 18 36 43" src="https://github.com/ntop/ntopng/assets/4493366/4b394360-96cf-4e40-af15-fec2b9839805">

add in preferences a toggle to disable SNMP monitoring.

If disabled, put a warning on the SNMP page saying that polling is disabled and it can be restored via preferences.

**Comment by NicoMaio** [comment]
Implemented in the PRO repo by 19ee327f14bbc6fb0ad07faf83c2c7e027a2e4bc and 5beb0be6f5a1396a7199dffa5b192a675d3c599f

**Comment by MatteoBiscosi** [comment]
Verified as fixed, please reopen if needed
