### ISSUE TITLE
Occasionaly can't post data to ElasticSearch in case of Netflow rates up to 7 Mbps

### ISSUE THREAD

**Issue by dtrizna** [ntop/ntopng#823]
Hi, community!

I don't believe anyone hasn't met this kind of problem before, so I am asking for your advice.

I am using nProbe Standard and ntopng Pro licences, as base OS serves Centos 7, Netflow traffic rates are average in about 1 Mbps with pikes to 7 Mbps. Although in result ntopng-MySQL solution wasn't usable (it took really long time to explore historical data even with 1h range), so the I've migrated to ElasticSearch solution.

Although here I've met a different kind of limitation. 
Several times in few minutes I've receiving this kind of log messages from NTOP:
16/Nov/2016 09:54:12 [Utils.cpp:856] WARNING: Unable to post data to (http://127.0.0.1:9200/_bulk): Couldn't connect to server
16/Nov/2016 09:53:57 [Utils.cpp:856] WARNING: Unable to post data to (http://127.0.0.1:9200/_bulk): Couldn't connect to server
16/Nov/2016 09:50:56 [Utils.cpp:856] WARNING: Unable to post data to (http://127.0.0.1:9200/_bulk): Couldn't connect to server

Of course the Elasticsearch is up and running. NTOP data itself is posted inside and I can observe it with Kibana. But as I understand some amount of data is lost due to this behavior.

As I think, this is caused by TCP/IP stack limitation, because there's really huge amount of TIME_WAIT connections from NTOP to ElasticSearch:
[root@l-netflow1 ~]# netstat -natp | grep :9200 | wc -l
28236

Those all connections as I told are in TIME_WAIT status:
[root@l-netflow1 ~]# netstat -natp | grep :9200 | awk '{print $6}' | sort | uniq -c
      8 ESTABLISHED
      1 LISTEN
  28180 TIME_WAIT

By default TIME_WAIT timer is 60s. I've tried to reduce it and already set it equal to 2 seconds. The same picture (interval between "Unable to post data.." logs are increased, but some % of data is loosed anyway).

There should be way to push all data through lower amount of connections, but I can't find the necessary configuration point.
I'm still searching, but probably you have any advises?
Any configuration tuning from NTOP or Elasticsearch side?

Thanks!
Regards,
Dmitry

**Comment by simonemainardi** [comment]
Hi,

you should try and set 

```
/proc/sys/net/ipv4/tcp_tw_recycle
/proc/sys/net/ipv4/tcp_tw_reuse
```

To allow fast recycling / reuse of sockets in a TIME_WAIT status. As you have ntopng and ES on the same box is safe to use both.

---

ntopng already batches several flows into a single POST https://github.com/ntop/ntopng/blob/dev/src/ElasticSearch.cpp#L135

---

How many flows/sec do you have on average? I guess you should tune your local ES to increase the insertion speed.

**Comment by dtrizna** [comment]
In the interface graph with selection of "Active Flows" there're numbers in between of 200,000 and 300,000.

But your first suggestion is totally correct - enabling those kernel parameters helped, now number of active sockets are ~300. There's no more previously mentioned log messages from ntopng daemon. I see increase in whole information amount in about 15%, this portion of data was missed before. 

Thank you! 
You should somehow mention about those parameters in your Blog or even User Guide in ES section. :)

P.S. Anyway I'll continue to tune ES, and obligatory will search for insertion speed characteristic.

P.S.S.
ntopng version v.2.4.161108 [Professional Edition]
CentOS Linux release 7.2.1511 (Core)
ElasticSearch:
  "version" : {
    "number" : "5.0.0",
    "build_date" : "2016-10-26T04:37:51.531Z",
    "lucene_version" : "6.2.0"
