### ISSUE TITLE
Inconsistent DPI

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8232]
Guess (yellow) becomes DPi (green) in flow info
<img width="260" alt="Screenshot 2024-02-20 at 17 05 01" src="https://github.com/ntop/ntopng/assets/4493366/f31d57a8-8818-4a19-8325-7dced2a0b7fa">
<img width="875" alt="Screenshot 2024-02-20 at 17 04 56" src="https://github.com/ntop/ntopng/assets/4493366/439d0444-ccb7-4ea4-baa8-5b764b5e89ac">

**Comment by MatteoBiscosi** [comment]
Verified as fixed, please reopen if needed
