### ISSUE TITLE
Inconsistent DPI with nProbe

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8233]
Bugs (when ntopng collects flows sent by nProbe)
1. nDPI becomes Unknown
2. In all cases Unknown cannot be green

<img width="1337" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/b0557e4c-76a7-4540-920f-b8c9be57fb99">

<img width="1356" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/00e289aa-8043-48e6-8278-78ea0e6c80c2">

**Comment by MatteoBiscosi** [comment]
Verified as fixed, please reopen if needed
