### ISSUE TITLE
Remove HostChecksStatus

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8235]
- From Host.h remove HostChecksStatus
- Remove class HostChecksStatus
- Remove checks that are no longer necessary as they have been implemented with local traffic rules 
![Screenshot 2024-02-21 at 17 11 13](https://github.com/ntop/ntopng/assets/4493366/c1bb5352-e8ec-4d75-a233-36632d0a796d)

**Comment by MatteoBiscosi** [comment]
Removed all no more used alerts (implemented with local rules)

**Comment by MatteoBiscosi** [comment]
Implemented as requested
