### ISSUE TITLE
Add JA4C filter in Historical Flows

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8238]
![Screenshot 2024-02-21 at 17 23 58](https://github.com/ntop/ntopng/assets/4493366/52f920ba-bb87-4de4-84c4-64bc658d85e5)

Make sure that in historical flow details the JA4 string (i18n) is mapped

**Comment by NicoMaio** [comment]
Implemented by 24e81d3ef979a5eeb1d0c9b247505ec40e2e34cb 
and in the PRO repo by 22a8fae3c09e925bc3003e7ec349d7a4e3cbc501

**Comment by MatteoBiscosi** [comment]
Implemented as requested
