### ISSUE TITLE
Ntopng chart time axis formatting problems

### ISSUE THREAD

**Issue by pshute** [ntop/ntopng#824]
I'm running 2.5.161113 - Pro Small Business Edition.

Charts are displayed in several places in ntopng's web interface. I find these difficult to interpret beyond a one day date range because of several problems:
- It doesn't display the dates on the time axis.
- The times are relative to the current time, so they aren't whole hours.
- The chart appears to always be divided into the same number of segments, so the interval between segments isn't a whole number of hours.
- A cosmetic issue, but if I scale the display (in Firefox), at some scales some of the divisions disappear.

E.g I'm looking at a 1 week chart now, and the values on the axis are 11:19:00, 21:13:20, 11:06:40, etc. It makes it hard to even tell where each day begins.

Looking at the webpage source, I found this function:
```
function getTickFormat(diff_epoch) {
   var tickFormat;

   if(diff_epoch < 86400) {
      tickFormat = "%H:%M:%S";
   } else if(diff_epoch < 2*86400) {
      tickFormat = "%b %e, %H:%M:%S";
   } else {
      tickFormat = "%b %e";
   }

   return(tickFormat);
}

```
That looks to me like it's supposed to display the date and time if the range is over a day, and just the date if it's over 2 days. But the only use of that function in the page source is:
`var tickFormat = getTickFormat(0);`

Is this variable scale format a feature that was never fully implemented?

**Comment by simonemainardi** [comment]
implemented in 36df7511c4f9b2beacfeb42211048cf8b47fc611
