### ISSUE TITLE
Service Map does not Honour the Specified Policy 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8241]
<img width="1329" alt="Screenshot 2024-02-22 at 13 47 19" src="https://github.com/ntop/ntopng/assets/4493366/efd868f2-7b1b-419e-9de0-1141822eaf98">

The policy post-learning is overwritten also for communications that were already labelled during the learning phase.

**Comment by MatteoBiscosi** [comment]
Issue fixed in the pro repo

**Comment by MatteoBiscosi** [comment]
pro repo: 51130eafb4757c83440145f0ce51f26ca0f6da05

**Comment by MatteoBiscosi** [comment]
Verified as fixed, please reopen if needed
