### ISSUE TITLE
Configuring NTOP flows to Elasticsearch in Docker compose 

### ISSUE THREAD

**Issue by olg33** [ntop/ntopng#8245]
Hi, this is just a question. 

We have a deployment that uses NTOPng and Elasticsearch where we are moving from VMs to Docker containers. 

Basically we'd like to know in which section of the docker compose file should we add the -F commands that forward flows to Elasticsearch:

> -F "es;ntopng;ntopng-%Y.%m.%d;http://localhost:9200/_bulk;"

I would say the flow line should be in the command section:

>   command:-d /var/lib/ntopng -i br0 -r 127.0.0.1:9200@0 -w 0.0.0.0:3000

but I'm not sure what format should we follow or if there's a different section for the -F lines.

Any clue would be appreciated.

**Comment by NicoMaio** [comment]
Hi @olg33,

another solution could be to use Docker volumes and import the 'ntopng.conf' file into the '/etc/ntopng/' directory inside the container.

**Comment by MatteoBiscosi** [comment]
Hi @olg33, like @NicoMaio suggested the right way is to create a configuration file and put an option per line:
e.g.:  ntopng.conf

-F="clickhouse"
-m="192.168.2.2/24"

Otherwise yes you should add the -F to the command option
