### ISSUE TITLE
Unprivileged users are unable to download pcap

### ISSUE THREAD

**Issue by ftalla** [ntop/ntopng#8246]
**Environment**:
* OS name: Ubuntu
* OS version: 22.04
* Architecture: amd64
* ntopng version/revision: 6.1.231212

**What happened**: I created an unprivileged user and granted the account privileges to download live traffic and PCAPs. When I click on Flows>Historical and attempt to download a pcap, I always get a 0 bytes file. Switching to a privileged user for the same flow works.

**How did you reproduce it?**: Same step as above

**Debug Information**:

**Comment by cardigliano** [comment]
Fixed in d8af77713159cac0550035458fdb8ffc56f07668
