### ISSUE TITLE
Local authorization for RADIUS account

### ISSUE THREAD

**Issue by ftalla** [ntop/ntopng#8247]
**What would you like to add or change?**: Allow authorization for RADIUS accounts to be defined locally and use RADIUS only for authentication. This would allow more flexibility in granting privileges and better apply principle of least privileges. 

**Why do you and others need this?**: In larger environment where RADIUS is used for a multitude of tools by a large number of groups, it doesn't make sense that anyone who can authenticate to RADIUS can get access (even limited) to network forensics. It makes sense for strong authentication to use RADIUS, authorization is better defined by each tool owner.

**Comment by cardigliano** [comment]
A new "Toggle RADIUS Authentication of Local Users" toggle is now available under Settings -> Preferences -> User Authentication -> Radius Authentication. This toggle enables remote authentication (Radius) with local authorization and requires that the local user name matches a Radius user name.

<img width="1483" alt="Screenshot 2024-03-12 at 11 22 04" src="https://github.com/ntop/ntopng/assets/7548711/011a18c0-4aac-4561-a18e-7dd5abe756c0">
