### ISSUE TITLE
Enrichment of exported logs

### ISSUE THREAD

**Issue by ftalla** [ntop/ntopng#8248]
**What would you like to add or change?**: Modify exported logs to display actual string value instead of codify value.

**Why do you and others need this?**: Codify values makes it hard to process the logs as it is not obvious what they mean. For example it is impossible for me to know if I should worry about an alert with the following values: 
alert_category: 3
alert_id: 88
entity_id: 4
l7_cat: 5
l7_proto: 91
...

**Comment by MatteoBiscosi** [comment]
This is already available, but depends on where you export and what you mean for exporting

**Comment by lucaderi** [comment]
Closed for inactivity
