### ISSUE TITLE
Mbps in history flow page

### ISSUE THREAD

**Issue by Niklasr69** [ntop/ntopng#8249]
**What would you like to add or change?**:
It would be very beneficial if it were possible to view a Mbps graph on the history flow page. Currently, it is possible to observe the amount of traffic per hour using various filters. It would be helpful to have a similar feature for Mbps, such like an SNMP interface graph style.
**Existing Hour table**
<img width="1831" alt="image" src="https://github.com/ntop/ntopng/assets/26242302/4b3f546a-e725-4576-8d13-c3dbbc4a269d">

**Why do you and others need this?**:

With SNMP interface monitoring or the ntopng flow/history page, it is challenging to obtain a complete picture of which clients or servers are allocating interface bandwidth per second.

**Comment by Niklasr69** [comment]
Hi,
I have tested the new feature and I got some strange results:
The output is 3.2Gbps , but the link has physical BW 1G
Pls could you check the calculation.

**Comment by lucaderi** [comment]
I agree that the implementation is bugged
<img width="1378" alt="Screenshot 2024-04-30 at 11 07 30" src="https://github.com/ntop/ntopng/assets/4493366/1fb6fd36-a7d2-4f55-b2fe-f4db27c60125">

**Comment by Niklasr69** [comment]
Any ETA for fix?

**Comment by MatteoBiscosi** [comment]
This issue should be fixed, in case reopen if needed

**Comment by Niklasr69** [comment]
Hi,
Sorry for the delayed answer.

Yes it's work fine now.
