### ISSUE TITLE
IP filter incompatible with Conversations

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8251]
When set IP filter no result is found even though the selected host produces hits

<img width="394" alt="Screenshot 2024-03-03 at 22 37 57" src="https://github.com/ntop/ntopng/assets/4493366/ead26949-845e-40ba-ae82-d1af14ad39e8">

**Comment by cardigliano** [comment]
This seems to depend on the clickhouse version, on some version it does not allow "SELECT any(SRC_LABEL)" and "WHERE SRC_LABEL=('3.91.203.183')" at the same time. Looking for a workaround..

**Comment by cardigliano** [comment]
Fixed in e60344995fcbc6e69a2c857b43fbbad342195205
