### ISSUE TITLE
Sent and Receive differences between Stable- and Dev-Version with same netflow data as source

### ISSUE THREAD

**Issue by oliwirth** [ntop/ntopng#8252]
### Dev-version last 30min  
![ntop_dev_30min](https://github.com/ntop/ntopng/assets/47536446/f66492a6-43c5-424c-967d-12dc42015f38)
### Stable-version last 30min
![ntop_stable_30min](https://github.com/ntop/ntopng/assets/47536446/4d73a8d8-d9a6-4d7d-a111-22655f1cbf81)
### Dev-version last day
![ntop_dev_day](https://github.com/ntop/ntopng/assets/47536446/043e7496-37e6-460a-aa35-fcb1ee69f94c)
### Stable-version last day
![ntop_stable_day](https://github.com/ntop/ntopng/assets/47536446/c6d34e76-eeb4-4f67-9f7d-5b90a5019b54)
### Dev-version single host
![ntop_dev_citpc013](https://github.com/ntop/ntopng/assets/47536446/4d58908e-55fd-4727-bcc7-90de74815fa4)
### Stable-version single host
![ntop_stable_citpc013](https://github.com/ntop/ntopng/assets/47536446/7018b4ab-cb56-48b1-a7a2-19910ff428b6)

Hi guys,
since a longer time I discover a mismatch of the charts between the stable and the dev-version.
It looks like the stable version is evaluation some of the netflow flow data in a different direction than the dev-version

It is assured that both versions are receiving the same netflow data as input.

Today it is particulary visible.
**I attached 6 pics**
* daily chart of both version
* 30min chart of both versions
* a single host citpc013.gsi.de of both version

**Environment**:
* Stable-version: 6.0.240223  
* Dev-version:  6.1.240301  
* Both running on 8 cpu virtual machines with 16GB memory under debian 11 (bullsye)

**Comment by MatteoBiscosi** [comment]
Hi @oliwirth the dev should be the correct one, we did some changes lately, soon we will release the new stable, when available, please update and in case you see incorrect data reopen the ticket
