### ISSUE TITLE
Increment SYN Flood Alert Score

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8253]
The score value of a SYN flood alert must be 250 (or similar) as it's a severe problem. Currently, it's 50. You can reproduce it as specified in https://www.ntop.org/ntopconf2022/pdf/Giaimo.pdf (slides 6 and 7)

**Comment by lucaderi** [comment]
Unfortunately, no alert is generated
- Reproduce with  nmap --top-ports 1000 --open 192.168.1.1
- 
<img width="1393" alt="Screenshot 2024-04-30 at 11 04 01" src="https://github.com/ntop/ntopng/assets/4493366/4e78950f-24e2-4f3d-aff9-7d8800e5242a">
<img width="1349" alt="Screenshot 2024-04-30 at 11 04 40" src="https://github.com/ntop/ntopng/assets/4493366/1523aa9c-9064-4663-a0d6-394a4240f081">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
