### ISSUE TITLE
Create Preference to Enable TLS/QUIC for host naming

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8258]
In TLS/QUIC there is no way to inspect the response and see if it has been successful. In case of failure, hostnames are bound to IP addresses wrongly.

This is to request to
- create a preference to enable this naming. The default should be no (disabled)
- modify the ntopng code to honour this setting

**Comment by MatteoBiscosi** [comment]
Verified as fixed, please reopen if needed
