### ISSUE TITLE
Behavioural Checks Glitches

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8259]
<img width="352" alt="Screenshot 2024-03-05 at 18 08 39" src="https://github.com/ntop/ntopng/assets/4493366/c0060123-c6c3-4392-9320-ba8d51674fe0">

The Factory Reset button should
- be blue (red is for other destructive actions)
- change the label to "Restore Checks Defaults"

**Comment by MatteoBiscosi** [comment]
Verified as fixed, please reopen if needed
