### ISSUE TITLE
NTOPng crashes  - symbol lookup error: rrd_lastupdate_r

### ISSUE THREAD

**Issue by cliveaustin** [ntop/ntopng#826]
Hi,

I've installed NTOPng (2.5.161116 - Pro Small Business Edition) in a dedicated CentOS 6.8 openVZ container (Proxmox 3.4) via YUM. Nprobe collects netflow data from my Mikrotik router and for the most part NTOPng is working "as described on the box" but....

There's one significant problem that I've been unable to resolve (or even shed much light on). NTOPng will ALWAYS crash if I use its web console to view a specific local host and then click the "graph" icon in the host's menu. This is the error that's reported in the log:

_**/usr/bin/ntopng: symbol lookup error: /usr/bin/ntopng: undefined symbol: rrd_lastupdate_r**_

At that stage, NTOPng has crashed/burned/died and needs to be re-started, so any help/advice/suggestions you may provide will be gratefully received. Thank you.

**Comment by emanuele-f** [comment]
Hi, what version of rrdtool is installed in your system? Please try and post the output of the following command: `ldd ntopng | grep rrd`

Sample output:

```
librrd.so.8 => /usr/lib/librrd.so.8
```

Then `readelf -s /usr/lib/librrd.so.8 (wich is the second part of the output above) | grep rrd_lastupdate`

Sample output:

```
286: 0000000000007b50   702 FUNC    GLOBAL DEFAULT   12 rrd_lastupdate_r
297: 0000000000007e10   610 FUNC    GLOBAL DEFAULT   12 rrd_lastupdate
```

**Comment by IvnSoft** [comment]
You need to install a newer version of rrdtool. 
I used 1.4.7 and that was good enough.

**Comment by cliveaustin** [comment]
Hi emanuele-f,

Here's what I get...

 **ldd /usr/local/bin/ntopng|grep rrd**
        librrd.so.4 => /usr/lib64/librrd.so.4 (0x00007f91a1e78000)

 **readelf -s /usr/lib64/librrd.so.4 | grep rrd_lastupdate**
   188: 0000000000017000   416 FUNC    GLOBAL DEFAULT   11 rrd_lastupdate

It dosen't seem to include rrd_lastupdate_r? ...so perhaps IvnSoft's suggestion (get a more recent rrdtool) might be the way to go?  FWIW I currently have  rrdtool-1.3.8-7.el6.x86_64 installed.

**Comment by simonemainardi** [comment]
@cliveaustin correct, follow @IvnSoft suggestion and update rrdtool

**Comment by lucaderi** [comment]
Fixed. Packages are being rebuilt

**Comment by cliveaustin** [comment]
Confirming this issue is resolved.

I only had to "yum -y update" and reboot to bring in the changes.

Now I can see those lovely graphs again withoug NTOPng crashing... Woohoo!

Thanks Luca!

Best Regards,
Clive Austin

Armadillo interNET
w. www.anet.com.au
e. clive@anet.com.au
m. 04 1217 6673
