### ISSUE TITLE
Implement Flow Reset/Attempt Alert and Host Counter

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8264]
- In each local host, implement a counter of Reset/Attempted flows
- Trigger an alert (low score) for flow reset
<img width="713" alt="Screenshot 2024-03-03 at 22 27 57 2" src="https://github.com/ntop/ntopng/assets/4493366/b28a6dc1-d7b2-48bc-a8b9-33fb4ceda035">

**Comment by lucaderi** [comment]
Issues
- In host_details.lua there is not a reset counter displayed.
- On Hsol you can easily reproduce it
<img width="1364" alt="Screenshot 2024-04-30 at 10 57 03" src="https://github.com/ntop/ntopng/assets/4493366/690cbe9f-04fd-45cb-b759-fccf2bd39e1c">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
