### ISSUE TITLE
Repeated data is present in the flow alert request

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#8265]
When doing a query to this endpoint: lua/rest/v2/get/flow/alert/list.lua?ifid=2&epoch_begin=1709911212&epoch_end=1709913012&format=json

There are many repeated fields inside the "records" key, for example:
1. there is cli_port : {"value": value}, the same for srv_port. These values are redundant inside the "flow" field
2. inside "flow" field there are cli_ip and srv_ip which are again redundant inside each "records" element

**Why do you and others need this?**:
Improve performance when loading the alerts page table and reduce the load on the api, reducing the amount of data transferred

**Comment by cardigliano** [comment]
The flow object has been removed all together when format=json is used
