### ISSUE TITLE
Historical Flows lists do not show up

### ISSUE THREAD

**Issue by akusilvennoinen1** [ntop/ntopng#8266]
**Environment**:
* OS name: Ubuntu
* OS version: 22.04.3 LTS
* Architecture: x86_64
* ntopng version/revision: v.6.0.240207
**What happened**:

When I select a local host and navigate to the Historical view, the flow list does not populate. The HTTP-request to historical_db_search.lua is not successful. The response code is 400 and the response contains the following:

`{"rc":-2,"rc_str":"INVALID_INTERFACE","rc_str_hr":"Invalid interface","rsp":[]}`

Currently, the most recent ntopng version is v.6.0.240307.  The same issue is present with that version.

Clickhouse version: 24.1.3.31

Already reset the browser cache (Firefox).

**How did you reproduce it?**

Just navigate to a local host's Historical view.

**Debug Information**:

```
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
     Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-03-11 10:49:21 EET; 6h ago
   Main PID: 2674 (ntopng-main)
      Tasks: 44 (limit: 19048)
     Memory: 431.1M
        CPU: 55min 11.537s
     CGroup: /system.slice/ntopng.service
             └─2674 /usr/bin/ntopng /run/ntopng.conf
```
![image](https://github.com/ntop/ntopng/assets/73161606/0fda523f-31cb-4ce6-89cc-d08235a10bf2)

![image](https://github.com/ntop/ntopng/assets/73161606/95382aeb-6d15-4988-88d5-6cbc089605d6)

[temp2.txt](https://github.com/ntop/ntopng/files/14560938/temp2.txt)

**Comment by NicoMaio** [comment]
This issue has been resolved in the development branch with the commit c78ba0d93e8868af7f0c4a6f8b5be6c327030468 and was reported in the closed issue (#8217).

@akusilvennoinen1, a new stable version with the fix should be available in a few hours. Please update and let us know if everything is alright.

**Comment by akusilvennoinen1** [comment]
Hi, @NicoMaio : tested the version 6.0.240313 and it was fixed, thank you! 👍

**Comment by dkggpeters** [comment]
I concur that historical flows works now using 6.1.240314 (FreeBSD 14.0) on hosts.

I do notice some drop down selections are really hard to read in dark mode.  ie Time selections Last xxx and some others.

**Comment by dkggpeters** [comment]
I do get the below error on the L7 contacts.  The chart updates but the table does not which I am assuming the below error is.  I do not use IPV6 and only IPV4.

14/Mar/2024 09:15:48 [historical_db_search.lua:44] [clickhouse_utils.lua:1246] WARNING Failure: Code: 47. DB::Exception: Missing columns: 'IPV6_SRC_ADDRc' while processing query: 'SELECT VLAN_ID, IPv4NumToString(IPV4_SRC_ADDR) AS IPV4_SRC_ADDR_FORMATTED, IPv4NumToString(IPV4_DST_ADDR) AS IPV4_DST_ADDR_FORMATTED, IPv6NumToString(IPV6_SRC_ADDR) AS IPV6_SRC_ADDR_FORMATTED, IPv6NumToString(IPV6_DST_ADDR) AS IPV6_DST_ADDR_FORMATTED, any(SRC_LABEL) AS SRC_LABEL, any(DST_LABEL) AS DST_LABEL, PROTOCOL, L7_PROTO, L7_PROTO_MASTER, count() AS count, sum(TOTAL_BYTES) AS total_bytes FROM flows WHERE ((INTERFACE_I
14/Mar/2024 09:15:48 [historical_db_search.lua:44] [clickhouse_utils.lua:1245] WARNING Query: SELECT VLAN_ID,IPv4NumToString(IPV4_SRC_ADDR) IPV4_SRC_ADDR_FORMATTED,IPv4NumToString(IPV4_DST_ADDR) IPV4_DST_ADDR_FORMATTED,IPv6NumToString(IPV6_SRC_ADDR) IPV6_SRC_ADDR_FORMATTED,IPv6NumToString(IPV6_DST_ADDR) IPV6_DST_ADDR_FORMATTED,any(SRC_LABEL) AS SRC_LABEL,any(DST_LABEL) AS DST_LABEL,PROTOCOL,L7_PROTO,L7_PROTO_MASTER,COUNT(*) AS count,SUM(TOTAL_BYTES) AS total_bytes FROM flows WHERE ((INTERFACE_ID=2) AND ((((IP_PROTOCOL_VERSION = 4) AND (flows.IPV4_SRC_ADDR=IPv4StringToNum('10.57.1.155'))) OR (flows.SRC_LABEL=('10.57.1.155'))) )) AND (FIRST_SEEN >= 1710420318 AND FIRST_SEEN <= 1710422118 AND LAST_SEEN <= 1710422118) GROUP BY VLAN_ID,IPV4_SRC_ADDR,IPV4_DST_ADDR,IPV6_SRC_ADDR,IPV6_DST_ADDR,PROTOCOL,L7_PROTO,L7_PROTO_MASTER ORDER BY IPv4NumToString(IPV4_SRC_ADDR) asc, IPv6NumToString(IPV6_SRC_ADDRc) asc LIMIT 10
14/Mar/2024 09:15:48 [MySQLDB.cpp:46] ERROR SQL error (1): Code: 47. DB::Exception: Missing columns: 'IPV6_SRC_ADDRc' while processing query: 'SELECT VLAN_ID, IPv4NumToString(IPV4_SRC_ADDR) AS IPV4_SRC_ADDR_FORMATTED, IPv4NumToString(IPV4_DST_ADDR) AS IPV4_DST_ADDR_FORMATTED, IPv6NumToString(IPV6_SRC_ADDR) AS IPV6_SRC_ADDR_FORMATTED, IPv6NumToString(IPV6_DST_ADDR) AS IPV6_DST_ADDR_FORMATTED, any(SRC_LABEL) AS SRC_LABEL, any(DST_LABEL) AS DST_LABEL, PROTOCOL, L7_PROTO, L7_PROTO_MASTER, count() AS count, sum(TOTAL_BYTES) AS total_bytes FROM flows WHERE ((INTERFACE_I
14/Mar/2024 09:15:48 [MySQLDB.cpp:45] ERROR SQL query: SELECT VLAN_ID,IPv4NumToString(IPV4_SRC_ADDR) IPV4_SRC_ADDR_FORMATTED,IPv4NumToString(IPV4_DST_ADDR) IPV4_DST_ADDR_FORMATTED,IPv6NumToString(IPV6_SRC_ADDR) IPV6_SRC_ADDR_FORMATTED,IPv6NumToString(IPV6_DST_ADDR) IPV6_DST_ADDR_FORMATTED,any(SRC_LABEL) AS SRC_LABEL,any(DST_LABEL) AS DST_LABEL,PROTOCOL,L7_PROTO,L7_PROTO_MASTER,COUNT(*) AS count,SUM(TOTAL_BYTES) AS total_bytes FROM flows WHERE ((INTERFACE_ID=2) AND ((((IP_PROTOCOL_VERSION = 4) AND (flows.IPV4_SRC_ADDR=IPv4StringToNum('10.57.1.155'))) OR (flows.SRC_LABEL=('10.57.1.155'))) )) AND (FIRST_SEEN >= 1710420318 AND FIRST_SEEN <= 1710422118 AND LAST_SEEN <= 1710422118) GROUP BY VLAN_ID,IPV4_SRC_ADDR,IPV4_DST_ADDR,IPV6_SRC_ADDR,IPV6_DST_ADDR,PROTOCOL,L7_PROTO,L7_PROTO_MASTER ORDER BY IPv4NumToString(IPV4_SRC_ADDR) asc, IPv6NumToString(IPV6_SRC_ADDRc) asc LIMIT 10
14/Mar/2024 09:15:48 [MySQLDB.cpp:947] Successfully connected to ClickHouse [default@10.57.1.149:9004][dbname: ntopng] for interface ix0

**Comment by NicoMaio** [comment]
Hi @dkggpeters, could you please open another issue?

**Comment by NicoMaio** [comment]
Verified as fixed.
