### ISSUE TITLE
Timeseries scale issues

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8268]
1. Behaviour Traffic TX is zero (RX is OK)
2. Invalid scales
<img width="445" alt="Screenshot 2024-03-12 at 11 21 05" src="https://github.com/ntop/ntopng/assets/4493366/aaf66d36-f4b2-4083-b576-7c59b67ce56f">
<img width="359" alt="Screenshot 2024-03-12 at 11 20 28" src="https://github.com/ntop/ntopng/assets/4493366/5676ac60-4c48-4986-968a-5ff081f9520f">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
