### ISSUE TITLE
TCP retransmissions detection (feature request)

### ISSUE THREAD

**Issue by papage** [ntop/ntopng#827]
It would be nice to see TCP retransmissions that happen in a network. We could use the data to reroute traffic and adjust our networks accordingly.

So, lf ntopng could monitor flows and log retransmissions that are happening, this info could be exported to ELK and then we would be able to use it.

Just an idea.
 
Cheers,,
Sp

**Comment by simonemainardi** [comment]
ntopng exports that information to ELK provided that it is used in conjunction with nprobe having a template that includes:

```
[NFv9 57599][IPFIX 35632.127] %RETRANSMITTED_IN_BYTES           Number of retransmitted TCP flow bytes (src->dst)
[NFv9 57581][IPFIX 35632.109] %RETRANSMITTED_IN_PKTS            Number of retransmitted TCP flow packets (src->dst)
[NFv9 57600][IPFIX 35632.128] %RETRANSMITTED_OUT_BYTES          Number of retransmitted TCP flow bytes (dst->src)
[NFv9 57582][IPFIX 35632.110] %RETRANSMITTED_OUT_PKTS           Number of retransmitted TCP flow packets (dst->src)
```

regards,
