### ISSUE TITLE
Ntopng leaves valid api tokens after deleting a user

### ISSUE THREAD

**Issue by mschilli** [ntop/ntopng#8271]
**Environment**:
* OS name: FreeBSD
* OS version: 14.0
* Architecture: Intel
* ntopng version/revision: 5.6.231208 rev.0

**What happened**:
When deleting a user from the Web Users admin screen (admin/users.lua), only the last generated API token gets deleted from Redis, any previously generated tokens remain active and can be used to obtain access to API calls.

**How did you reproduce it?**
1) Go to the Web Users page on admin/users.lua and create a new user (e.g. "buguser")
2) Click on "Edit" for this user, and then on "User Authentication Token"
3) Click "Generate Token" (write this one down)
4) Click "Generate Token" AGAIN
5) Go back to the Web Users page and delete the new user "buguser", confirm the popup.
6) Now take the token from 3) and use it in an API call, Ntopng will permanently accept it although the corresponding user is gone

**Debug Information**:
1) Each click on "Generate Token" for a user adds a new token to ntopng.api_tokens in Redis via HTTPserver::create_api_token
2) When deleting a user, Ntop::deleteUser in Ntop.cpp will only delete the *last* created token for the user via getUserAPIToken/redis->hashDel

**Recommendations:**
1) Fix Ntop::deleteUser to delete all valid tokens for the user, not just the last one
2) Maybe rethink the concept of allowing several tokens to be created for a user with no way to list or selectively revoke them

Hope this is helpful!

**Comment by MatteoBiscosi** [comment]
Verified as fixed, please reopen if needed
