### ISSUE TITLE
SNMP Ratio Not Working

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8274]
Go to the flow exporters page, click one exporter, then the following dialog will appear
<img width="361" alt="Screenshot 2024-03-15 at 20 47 49" src="https://github.com/ntop/ntopng/assets/4493366/7c07930f-2192-45bc-9107-1a1abd9aca4b">
Clicking on "Enable Them" has no effect

**Comment by MatteoBiscosi** [comment]
Implemented as requested
