### ISSUE TITLE
Glitches on Historical Flow Interface Filter

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8276]
<img width="793" alt="Screenshot 2024-03-15 at 21 00 47" src="https://github.com/ntop/ntopng/assets/4493366/291966a2-60a3-4f7c-b28e-1e6a824ca65a">
1. Interface names are not completely visible
2. With many devices this display is hard to use. Please rework it.

**Comment by MatteoBiscosi** [comment]
The issue should now be fixed, only on the selected item, the name is cut but in the dropdown the full name is displayed
![image](https://github.com/ntop/ntopng/assets/49585191/8f7aa27c-6213-44b5-9daf-d12b5a4a6741)
