### ISSUE TITLE
Empty Report Tables When Selecting a Flow Exporter

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8278]
<img width="1406" alt="Screenshot 2024-03-15 at 21 07 31" src="https://github.com/ntop/ntopng/assets/4493366/a7eb83c4-db13-4f8f-9c06-a45e44c5d579">

Everything works if no exporter is selected

**Comment by MatteoBiscosi** [comment]
The issue should be fixed, it should still be related to the changes in the dropdown select component

**Comment by MatteoBiscosi** [comment]
Verified as fixed
