### ISSUE TITLE
Historical data in ntopng

### ISSUE THREAD

**Issue by seleznevae** [ntop/ntopng#828]
I am trying to save data in ntopng and load them after restart.
I am starting ntopng as follows:
sudo ntopng  -i tcp://127.0.0.1:5556  -F "mysql;localhost;ntopng_db;flows;root;my_password"

During work I can see that ntopng pushs data to the database. I can see them in MySQL.
But after restart (to restart I use the same command sudo ntopng  -i tcp://127.0.0.1:5556  -F "mysql;localhost;ntopng_db;flows;root;my_password" ) I can't see the saved data in ntopng.
Here is console output when I start ntopng:

18/Nov/2016 12:53:35 [Ntop.cpp:1121] Setting local networks to 127.0.0.0/8
18/Nov/2016 12:53:35 [Redis.cpp:92] Successfully connected to redis 127.0.0.1:6379@0
18/Nov/2016 12:53:35 [NtopPro.cpp:118] [LICENSE] Read license from Redis []
18/Nov/2016 12:53:35 [NtopPro.cpp:182] ERROR: [LICENSE] Invalid or missing ntopng License [Empty license file]
18/Nov/2016 12:53:35 [NtopPro.cpp:195] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
18/Nov/2016 12:53:35 [NtopPro.cpp:197] WARNING: [LICENSE] before returning to community mode
18/Nov/2016 12:53:35 [NtopPro.cpp:198] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
18/Nov/2016 12:53:35 [NtopPro.cpp:199] WARNING: [LICENSE] or run ntopng in community mode starting
18/Nov/2016 12:53:35 [NtopPro.cpp:200] WARNING: [LICENSE] ntopng --community
18/Nov/2016 12:53:35 [MySQLDB.cpp:549] Attempting to connect to MySQL for interface tcp://127.0.0.1:5556...
18/Nov/2016 12:53:35 [MySQLDB.cpp:589] Succesfully connected to MySQL [localhost:root] for interface tcp://127.0.0.1:5556
18/Nov/2016 12:53:35 [Ntop.cpp:1267] Registered interface tcp://127.0.0.1:5556 [id: 0]
18/Nov/2016 12:53:35 [Ntop.cpp:1279] Registered interface view tcp://127.0.0.1:5556 [id: 0]
18/Nov/2016 12:53:35 [main.cpp:255] PID stored in file /var/run/ntopng.pid
18/Nov/2016 12:53:35 [Utils.cpp:341] User changed to nobody
18/Nov/2016 12:53:35 [HTTPserver.cpp:501] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
18/Nov/2016 12:53:35 [HTTPserver.cpp:544] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
18/Nov/2016 12:53:35 [HTTPserver.cpp:547] HTTP server listening on port 3000
18/Nov/2016 12:53:35 [MySQLDB.cpp:549] Attempting to connect to MySQL for interface tcp://127.0.0.1:5556...
18/Nov/2016 12:53:35 [MySQLDB.cpp:589] Succesfully connected to MySQL [localhost:root] for interface tcp://127.0.0.1:5556
18/Nov/2016 12:53:35 [MySQLDB.cpp:311] MySQL schema update. Altering table flowsv4: renaming BYTES to IN_BYTES and adding OUT_BYTES
18/Nov/2016 12:53:35 [MySQLDB.cpp:366] MySQL schema update. Altering table flowsv6: changing PACKETS data type to unsigned int.
18/Nov/2016 12:53:35 [main.cpp:309] Working directory: /var/tmp/ntopng
18/Nov/2016 12:53:35 [main.cpp:311] Scripts/HTML pages directory: /usr/share/ntopng
18/Nov/2016 12:53:35 [Ntop.cpp:271] Welcome to ntopng x86_64 v.2.4.161113 - (C) 1998-2016 ntop.org
18/Nov/2016 12:53:35 [Ntop.cpp:276] Built on Ubuntu 14.04.5 LTS
18/Nov/2016 12:53:35 [PeriodicActivities.cpp:53] Started periodic activities loop...
18/Nov/2016 12:53:35 [RuntimePrefs.cpp:34] Dumping alerts into syslog
18/Nov/2016 12:53:35 [NtopPro.cpp:259] [LICENSE] ntopng systemId: 394AC9CA7A086B1B
18/Nov/2016 12:53:35 [NtopPro.cpp:264] [LICENSE] ntopng is starting in demo mode
18/Nov/2016 12:53:35 [NetworkInterface.cpp:1538] Started packet polling on interface tcp://127.0.0.1:5556 [id: 0]...
18/Nov/2016 12:53:35 [CollectorInterface.cpp:104] Collecting flows on tcp://127.0.0.1:5556 [ntopng->nprobe]
18/Nov/2016 12:53:36 [MySQLDB.cpp:549] Attempting to connect to MySQL for interface tcp://127.0.0.1:5556...
18/Nov/2016 12:53:36 [MySQLDB.cpp:589] Succesfully connected to MySQL [localhost:root] for interface tcp://127.0.0.1:5556

 As I understand (http://www.ntop.org/ntopng/exploring-historical-data-using-ntopng/) in interfaces I should see some special historical interface, but I see only tcp://127.0.0.1:5556 interface:
![1](https://cloud.githubusercontent.com/assets/16498414/20424080/6819f286-ad8d-11e6-937e-d64aeb8a08fb.png)

My ntopng version is v.2.4.161113. Should I use some special keys to see historical interface?

**Comment by emanuele-f** [comment]
Hi, in order to access the historical data, you should click on the _home_ icon at the top of the page, then "Historical Data Exporer". You mysql configuration is ok.

**Comment by seleznevae** [comment]
Thanks.
It seems that I missed it.
Problem is solved. Thanks again.
