### ISSUE TITLE
Clickhouse Query Errors

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8280]
15/Mar/2024 21:05:56 [MySQLDB.cpp:46] ERROR: SQL error (1): Code: 47. DB::Exception: Missing columns: 'hourly_flows.PROBE_IP' while processing query: 'SELECT SRC_ASN AS ASN, IPV4_SRC_ADDR AS IPV4_ADDR, IPV6_SRC_ADDR AS IPV6_ADDR, SRC2DST_BYTES AS BYTES FROM flows WHERE ((INTERFACE_ID = 2) AND (hourly_flows.PROBE_IP = IPv4StringToNum('192.168.2.1'))) AND (SRC_ASN != DST_ASN) AND ((FIRST_SEEN >= 1710531300) AND (FIRST_SEEN <= 1710533100) AND (LAST_SEEN <= 1710533100)) AND (SRC_ASN != 0)', required columns: 'SRC_ASN' 'IPV6_SRC_ADDR' 'FIRST_SEEN' 'INTERFACE_ID' 'hourly
15/Mar/2024 21:05:56 [historical_db_search.lua:44] [clickhouse_utils.lua:1245] WARNING: Query: SELECT ASN, IPv4NumToString(any(IPV4_ADDR)) IPV4_ADDR, IPv6NumToString(any(IPV6_ADDR)) IPV6_ADDR, SUM(BYTES) AS total_bytes FROM (SELECT SRC_ASN AS ASN, IPV4_SRC_ADDR AS IPV4_ADDR, IPV6_SRC_ADDR AS IPV6_ADDR, SRC2DST_BYTES AS BYTES FROM flows WHERE ((INTERFACE_ID=2) AND (hourly_flows.PROBE_IP=IPv4StringToNum('192.168.2.1'))) AND SRC_ASN!=DST_ASN AND (FIRST_SEEN >= 1710531300 AND FIRST_SEEN <= 1710533100 AND LAST_SEEN <= 1710533100) AND SRC_ASN!=0 UNION ALL SELECT DST_ASN AS ASN, IPV4_DST_ADDR AS IPV4_ADDR, IPV6_DST_ADDR AS IPV6_ADDR, DST2SRC_BYTES AS BYTES FROM flows WHERE ((INTERFACE_ID=2) AND (hourly_flows.PROBE_IP=IPv4StringToNum('192.168.2.1'))) AND SRC_ASN!=DST_ASN AND (FIRST_SEEN >= 1710531300 AND FIRST_SEEN <= 1710533100 AND LAST_SEEN <= 1710533100) AND DST_ASN!=0) AS f GROUP BY ASN ORDER BY total_bytes DESC LIMIT 20

**Comment by MatteoBiscosi** [comment]
Fixed, pro repo

**Comment by MatteoBiscosi** [comment]
Verified as fixed
