### ISSUE TITLE
Import Host Pools Member not working on 6.0 stable and 6.1

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#8281]
This has been reproduced from the Button at the bottom of the "Host Pools Members" page

**Comment by cardigliano** [comment]
@NicoMaio did you backport this fix to the stable?

**Comment by NicoMaio** [comment]
> @NicoMaio did you backport this fix to the stable?

Yes, the fix has been successfully backported to the stable version.

**Comment by cardigliano** [comment]
I tried importing a simple CSV but it seems this is not working (no new entry is added to the pool). I would also add a note about the expected format of the CSV file in the dialog (specifying that it expects e.g. one IP per line, in CIDR format, with VLAN, with an example)

**Comment by cardigliano** [comment]
I confirm this is working now

**Comment by cardigliano** [comment]
As suggested I would add a note in the dialog with the expected csv format or an example.

Format: CIDR[@VLAN]
Example: 192.168.1.1/32@5

**Comment by MatteoBiscosi** [comment]
Verified as fixed
