### ISSUE TITLE
ntop dropping packets - nf_queue: full at 4096 entries

### ISSUE THREAD

**Issue by dimalev01** [ntop/ntopng#8284]
Hello ,

We had an issue with ntop nfnetlink_queue that effect on our traffic.
next is the log from syslog file:

Mar 20 11:15:18 ntop kernel: [37007151.640388] nfnetlink_queue: nf_queue: full at 4096 entries, dropping packets(s)
Mar 20 11:15:18 ntop kernel: [37007151.640390] nfnetlink_queue: nf_queue: full at 4096 entries, dropping packets(s)
Mar 20 11:15:18 ntop kernel: [37007151.640391] nfnetlink_queue: nf_queue: full at 4096 entries, dropping packets(s)
Mar 20 11:15:23 ntop kernel: [37007156.644446] net_ratelimit: 1018019 callbacks suppressed

our linux version:

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

How can we check the nf_queue current size + hot to increase it ?

Br , 

Dima Lev.

**Comment by cardigliano** [comment]
Handled by mail time ago
