### ISSUE TITLE
The "Active Monitoring" notification and alerts are wired

### ISSUE THREAD

**Issue by Yoshihiro-jp** [ntop/ntopng#8289]
**Environment**:
* OS name:  Ubuntu
* OS version: 20.04.6
* Architecture: x86_64
* ntopng version/revision: 6.0.240321

**What happened**:
I don't set the "Silence Duplicated Alerts".
There is no alerts in the Explorer when the Active Monitoring provided the notification.

My test procedure was below:
25/03/202419:05: the icmp target node was shutdown 
25/03/2024 19:06: the ntopng's notification(slack) was occured
[25/03/2024 19:06:03]  [Active Monitoring] [Active Monitoring] [192.168.63.33] [Engaged] Host 192.168.63.33  is unreachable.
★Here is the problem I think.
There are no alerts in the "Alerts Explorer" and then after 1 minutes later the notification doesn't happen anymore even if I don't set the "Silence Duplicated Alerts".

25/03/2024 19:10: the icmp target node was restarted
25/03/2024 19:11: the ntopng's notification(slack) was occured
[25/03/2024 19:11:03] [Active Monitoring] [Active Monitoring] [192.168.63.33] [Released] Host 192.168.63.33  is unreachable.
★What I knew
The previous alert showed in the "Alerts Explorer".
★This timing is wired...

I thought that if I don't set the "Silence Duplicated Alerts" I expected that I received the alerts periodically but it was not.
Additionally the Alert Explorer doesn't show any alerts of the Active Monitoring until the target node was online. 
This is also wired behavior.

**How did you reproduce it?**
Kindly read above test procedure.

**Debug Information**:
Kindly read above test procedure.

![silence_alert001](https://github.com/ntop/ntopng/assets/58843707/d020e3f8-94a5-4211-b3f8-1bb9ae36e46b)

**Comment by Yoshihiro-jp** [comment]
Dear ntop Team,

May I ask you guys opinion about this?

regards,
Yoshihiro

**Comment by MatteoBiscosi** [comment]
Hi @Yoshihiro-jp we are working on it, we found an issue that could probably address your issue, but we are still checking

**Comment by Yoshihiro-jp** [comment]
Dear @Matteo thank you for your reply.

I would inform my customer to wait for a while.

 

Regards,

Yoshihiro

**Comment by MatteoBiscosi** [comment]
Hi @Yoshihiro-jp i checked and everything works as expected. By design the engaged alert is just sent to the endpoint when triggered or when released, not all the times the check is performed this is in order to not receive a flood of alerts on the configured endpoint

**Comment by Yoshihiro-jp** [comment]
Dear @MatteoBiscosi , 
Thank you for your reply.

What is for  the "Silence Duplicated Alerts"?

regards,
Yoshihiro

**Comment by MatteoBiscosi** [comment]
The "Silence Duplicated Alerts" is for all the other (non engaged) alerts, for instance you have a VPN connection and the alert "Remote Connection" enabled, having multiple flows this kind of connection, means that all the times you'll receive an alert "Remote Connection". With the "Silence duplicated alerts" you'll receive just one alert of this kind (the first flow that triggers the alert)
