### ISSUE TITLE
Use of GeoLite2-Country

### ISSUE THREAD

**Issue by dennypage** [ntop/ntopng#8294]
The documentation for geolocation (https://github.com/ntop/ntopng/blob/dev/doc/README.geolocation.md) using MaxMind says to ensure that GeoLite2-Country, GeoLite2-City and GeoLite2-ASN are installed. Looking at the code, I see that GeoLite2-City and GeoLite2-ASN are used, but I do not see that GeoLite2-Country is ever used.

Does the documentation need to be updated?

**Comment by lucaderi** [comment]
The city database contains country information so there is no need to use it

**Comment by dennypage** [comment]
So, perhaps the documentation for geolocation should be updated to remove the reference to installing GeoLite2-Country?
