### ISSUE TITLE
Add SNMP Import

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8295]
Add the ability to import SNMP host configuration by uploading a file with the following format

IP address[,version,community]

The IP is mandatory, the other fields are not and default to
- version = 2c
- community if not specified will default to the one configured on preferences or "public"

At the moment SNMPv3 support needs to be evaluated as it's a bit more complex.

After import, the system should report success or failure in case some lines are malformed.

**Comment by NicoMaio** [comment]
It is implemented in the PRO repo by 20e56ee4a59358fad868aa2fce1eb948a260bf44

**Comment by NicoMaio** [comment]
Tested with these files: 
[snmp_devices_2.json](https://github.com/ntop/ntopng/files/14871793/snmp_devices_2.json)
[snmp_devices.json](https://github.com/ntop/ntopng/files/14871794/snmp_devices.json)
[snmp_net_device.json](https://github.com/ntop/ntopng/files/14871795/snmp_net_device.json)
[bad_file.json](https://github.com/ntop/ntopng/files/14871796/bad_file.json)
[bad_file_json_format.json](https://github.com/ntop/ntopng/files/14871799/bad_file_json_format.json)

Tested the case where the maximum number of configurable SNMP devices is reached by modifying the max number in 'snmp_config.max_num_configred_devices' to 1.

**Comment by NicoMaio** [comment]
Add support for CSV file in the PRO repo by 64a2677de728c7925a1723208dc0866b4bd70450


Tested with these files:
[snmp_device_2.csv](https://github.com/ntop/ntopng/files/14947550/snmp_device_2.csv)
[snmp_device_3.csv](https://github.com/ntop/ntopng/files/14947552/snmp_device_3.csv)
[snmp_device_4.csv](https://github.com/ntop/ntopng/files/14947553/snmp_device_4.csv)
[snmp_device.csv](https://github.com/ntop/ntopng/files/14947554/snmp_device.csv)

**Comment by NicoMaio** [comment]
Fixed in the PRO repo with 14f20df34914860877a97d34baeac65e5a075c4a

**Comment by lucaderi** [comment]
<img width="1096" alt="Screenshot 2024-04-30 at 10 45 46" src="https://github.com/ntop/ntopng/assets/4493366/01f89618-7b8b-45ab-87cb-fcc0a457ba98">
[a.csv](https://github.com/ntop/ntopng/files/15160748/a.csv)

Broken

**Comment by lucaderi** [comment]
Note that CSV means comma sepaated value, so | is not the separator but ,

**Comment by NicoMaio** [comment]
> Note that CSV means comma sepaated value, so | is not the separator but ,

Currently, the import is working with a comma-separated values list.

**Comment by MatteoBiscosi** [comment]
In order to not users be confused the import needs to be done in a single place, the configuration page or the SNMP page. Other than that, the format must be the same, for both json and csv file

**Comment by MatteoBiscosi** [comment]
Implemented as requested
