### ISSUE TITLE
Hi @deanfourie1,

### ISSUE THREAD

**Issue by deanfourie1** [ntop/ntopng#8296]
Hi @deanfourie1,
I'm trying to reproduce this issue, but it's working well. Could you please update to the latest ntopng version and try again?

_Originally posted by @NicoMaio in https://github.com/ntop/ntopng/issues/7981#issuecomment-2023342470_

Im on ntopng Community v.6.1.231102 (FreeBSD 14.0) .

Issues still there for me.

Thanks

**Comment by lucaderi** [comment]
please let's continue on the original ticket
