### ISSUE TITLE
Flow Page Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8300]
<img width="1086" alt="Screenshot 2024-04-01 at 09 46 59" src="https://github.com/ntop/ntopng/assets/4493366/e820735f-4169-4b34-ac4f-a9bddda1d1ba">

There are many flows but none is displayed

**Comment by AtzoFatzo** [comment]
Same issue present on my setup:

Version:	6.1.240331 [Enterprise/Professional build]
GIT rev:	dev:35e732b44a6359126577d382602ac2382d508c8c:20240331
Pro rev:	r6450
Built on:	Debian GNU/Linux 12 (bookworm)
Platform:	aarch64
Edition:	Community

Thanks for fixing :)

BR
Matthias

**Comment by MatteoBiscosi** [comment]
Issue fixed yesterday, please update and it should work
