### ISSUE TITLE
Glitches in the flow table

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8303]
1. Duration and last seen sort are wrong (reverted)
<img width="291" alt="Screenshot 2024-04-02 at 10 47 51" src="https://github.com/ntop/ntopng/assets/4493366/885efe20-4b9c-4c0a-ad6c-f881319e01f4">
2. remove the red triangle on the score column or add it where it is missing (e.g. in the flow alerts)
<img width="101" alt="Screenshot 2024-04-02 at 10 48 28" src="https://github.com/ntop/ntopng/assets/4493366/f9679d9d-56e0-426f-8eb6-d8caae597a68">

**Comment by MatteoBiscosi** [comment]
verified as fixed
