### ISSUE TITLE
Update the SNMP documentation

### ISSUE THREAD

**Issue by NicoMaio** [ntop/ntopng#8305]
We need to update the SNMP documentation with the new pages in vue and the batch import.

**Comment by lucaderi** [comment]
<img width="788" alt="Screenshot 2024-04-30 at 10 51 10" src="https://github.com/ntop/ntopng/assets/4493366/ee863f4a-3647-4290-a2c9-e02271c9f07c">

Update the above picture in the documentation and specify that both CSV and JSON are supported

**Comment by lucaderi** [comment]
Unfortunately the text has not been updated as requested. For instance see "SNMP Import File" in https://www.ntop.org/guides/ntopng/snmp/configuration.html#snmp-import-file
Nowhere is mentioned the CSV format

**Comment by NicoMaio** [comment]
Verified the implementation.
