### ISSUE TITLE
Labels cut in lua/pro/db_flow_details.lua

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8315]
<img width="991" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/cee49acf-0fe5-49a7-8008-825f267dbdad">

**Comment by MatteoBiscosi** [comment]
the issue should now be fixed 
![image](https://github.com/ntop/ntopng/assets/49585191/afb192fc-745e-4e78-9aca-3c04b15e074b)

**Comment by lucaderi** [comment]
Verified as fixed
