### ISSUE TITLE
Invalid Flows: both flow hosts are attackers

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8319]
<img width="1166" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/2f497dba-d975-4d70-9b60-9f11523fcfc6">

**Comment by lucaderi** [comment]
Note that Local and Remote icon is missing

**Comment by lucaderi** [comment]
Two issues
- The description field is wrong but Info is ok
<img width="702" alt="Screenshot 2024-04-30 at 09 30 28" src="https://github.com/ntop/ntopng/assets/4493366/d87cdb9d-9dd1-4b23-b019-715a615fd698">
- Clicking on the copy icon on Info the URL starts with https://...  that is wrong as this is a HTTP flow

**Comment by MatteoBiscosi** [comment]
it is not wrong, it is css class to cut the string, if you expand the column everything should work...
The css class / copy button is removed to avoid this issue

**Comment by lucaderi** [comment]
Verified as fixed
