### ISSUE TITLE
pass "--community" flag in /etc/ntopng/ntopng.conf

### ISSUE THREAD

**Issue by morphyno** [ntop/ntopng#832]
It seems we can't pass debug "--community" flags via /etc/ntopng/ntopng.conf. Is this something can be added for future releases?

**Comment by simonemainardi** [comment]
`--community` is not a debug flag, it is used to start ntopng in community mode without the initial 10 minute trial of the professional version.

Try to add it in the configuration file in a new line as:
```
--community=
```

**Comment by simonemainardi** [comment]
@morphyno did you try the solution proposed?

**Comment by simonemainardi** [comment]
Solution given. No feedback received. Apparently the uses confused the role of --community flag.
