### ISSUE TITLE
Missing DNS alert info

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#8325]
When accessing this url: /lua/alert_stats.lua?page=flow&epoch_begin=1712818151&epoch_end=1712819951&status=any&ifid=2&query_preset=&count=&severity=5%3Bgte&alert_id=47%3Beq

Some values of the column info are present and some are not. When clicking on a missing alert's info the content is present on the specific page instead

<img width="1841" alt="Screenshot 2024-04-11 at 09 20 06" src="https://github.com/ntop/ntopng/assets/33870399/101d551e-c360-4ed4-b62b-0361252bcdd3">

**Comment by lucaderi** [comment]
<img width="1272" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/1e50f9d9-3835-4593-a646-a16c5e5d9027">

Still bugged. The URL s only for HTTP, for all other protocols it is not named UR:L. In all cases the info is missing

**Comment by MatteoBiscosi** [comment]
The issue should now be fixed for smtps too. The info shown is provided by nDPI, (like for the other flow risks), in case a more explanatory description is needed, i suggest on changing the nDPI side.
![Screenshot 2024-05-09 113932](https://github.com/ntop/ntopng/assets/49585191/5ffff74d-2f7b-41f7-9f31-94b1856598bb)
