### ISSUE TITLE
historical interface doesn't show up

### ISSUE THREAD

**Issue by seleznevae** [ntop/ntopng#833]
I've built ntopng and nDPI for the latest  commits in dev branch according to the README.compilation.
When I start ntopng:
sudo ./ntopng  -F "mysql;localhost;ntopng_db;flows;root;my_password" 

It connects to the MySQL and inserts data to it. 
However historical interface is not shown
![2](https://cloud.githubusercontent.com/assets/16498414/20522724/43bcee8e-b0cb-11e6-9b3a-e63f67fa07f9.png)

When I used prebuilt ntopng v.2.4.161113  I saw item in the menu to watch historical data.
![3](https://cloud.githubusercontent.com/assets/16498414/20522945/336b39ea-b0cc-11e6-8fc3-8674ad16e261.png)
Does this option enabled when I build ntopng myself or I should use some extra packages.

**Comment by simonemainardi** [comment]
historical data explorer is implemented in the Professional version. Professional version is not available when building from sources thus you can't get it. The only way is to use the binary packages.
