### ISSUE TITLE
Alert Count Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8330]
<img width="1242" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/b4d4e79c-4239-48ed-80c9-d6b40600e9a5">

Either the values are corrected, or better to remove them

**Comment by MatteoBiscosi** [comment]
Alert counters are removed in the latest version, we can re-add them after uniting all the engaged and historical alerts

**Comment by lucaderi** [comment]
Verified as fixed
