### ISSUE TITLE
Add redirection to flows or alerts from a chart

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#8335]
**What would you like to add or change?**:
From hosts page i would like to click on the graph, open a new tab at the given timestamp to see historical info like flows

**Why do you and others need this?**:
Improve speed of analysis 

![Screenshot 2024-04-15 at 21 18 44](https://github.com/ntop/ntopng/assets/33870399/2a997749-1ac1-472c-a866-1c8651021d2c)

**Comment by MatteoBiscosi** [comment]
this feature is already available, i changed the icon to the flows one, but essentially you just need to click the last icon
![image](https://github.com/ntop/ntopng/assets/49585191/d609dbe9-b514-4aa2-a284-040a14d9035b)

**Comment by MatteoBiscosi** [comment]
It is even possible to jump to a specific application/category/host flows by using the action button in the top table
![image](https://github.com/ntop/ntopng/assets/49585191/77583085-99d9-4d33-8cfd-28063b6f1f2c)

**Comment by lucaderi** [comment]
It does not seem to work.
<img width="1166" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/d7a9def0-f111-407c-839e-edbf96424c9b">
the clicking on the icon brings to
<img width="987" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/f4a5e77d-c7a1-45df-9abd-80ea6fc3ac95">

with wrong timestamp

**Comment by MatteoBiscosi** [comment]
The one that needs to be clicked is not the one in the navbar, but the one close to the charts, it's a bit confusing but currently it's impossible to dinamically change the link for the link in the navbar
![Screenshot 2024-05-02 152722](https://github.com/ntop/ntopng/assets/49585191/4a25b7ff-25c9-43d5-8743-40ebca5520d9)

**Comment by MatteoBiscosi** [comment]
What i did is the following, due to the fact that i cannot create a dynamic link there, i disabled all the historical flows link in the navbar, from the timeseries page but kept the one next to the timeframe
![image](https://github.com/ntop/ntopng/assets/49585191/b512204a-ba33-42d8-b7b1-073ce0899844)
when exiting the timeseries the link is back
![image](https://github.com/ntop/ntopng/assets/49585191/6abc3c99-63b0-40a2-841c-0891d3a87863)

**Comment by lucaderi** [comment]
Not too happy but I understand the technical issue
