### ISSUE TITLE
The top SNMP interfaces table must not be present with a single interface

### ISSUE THREAD

**Issue by NicoMaio** [ntop/ntopng#8341]
![image](https://github.com/ntop/ntopng/assets/55502486/f65c0d3c-503d-45f3-856d-1100e8efd184)

**Comment by MatteoBiscosi** [comment]
Verified as fixed
![image](https://github.com/ntop/ntopng/assets/49585191/820d3f2d-f5fc-4a1d-ba94-f9ef75fe56f4)
