### ISSUE TITLE
Option to set default value for max items shown on page

### ISSUE THREAD

**Issue by deanfourie1** [ntop/ntopng#8345]
**What would you like to add or change?**:
The ability to add a "Default" selection for how man entries to show per page. It always defaults to 10.

**Why do you and others need this?**:

Right now, every time there is more then 10 entries shown on the page, I need to manually go and select 100 from the drop down every time.  Would be nice if I could just set the default to display 100 no matter what.

<img width="313" alt="image" src="https://github.com/ntop/ntopng/assets/71812804/baa92976-d096-45f6-ab0d-8710e95cfbad">

**Comment by MatteoBiscosi** [comment]
This issue should currently be fixed at least where it's possible; there is no preference, however if in a page you select a number of rows, that number is kept untile the browser cache is deleted.
E.g.
in the alerts page i select 20 entries
![image](https://github.com/ntop/ntopng/assets/49585191/4fa63e44-c1c6-469d-a60e-4c6e7810be68)
if i jump to the flow page, that number of entries is kept
![image](https://github.com/ntop/ntopng/assets/49585191/5cc9334d-e5d3-476a-9d36-312cab2a0284)
The only issue is that in some tables (the old ones) that value is not kept but currently it cannot be implemented in those tables

**Comment by deanfourie1** [comment]
Damn, I just upgraded pfSense to 24.02 and its upgraded to FreeBSD 15,

Any idea on a possible release for FreeBSD 15? Then i can test 🦖

**Comment by MatteoBiscosi** [comment]
Verified as fixed, regarding FreeBSD 15, we are planning to add the support but still not available yet i'll open a new ticket for that
