### ISSUE TITLE
Vulnerability Scan does not run

### ISSUE THREAD

**Issue by deanfourie1** [ntop/ntopng#8346]
**Environment**:
* OS name: FreeBSD
* OS version: 14
* Architecture: amd64
* ntopng version/revision: v.6.1.240416
* 
**What happened**:
Vulnerability Scan is just stuck at "scanning" and does not change. It appears that the scan does not start?

**How did you reproduce it?**
Just ran a Vulnerability Scan on selected targets.

**Debug Information**:

<img width="1028" alt="image" src="https://github.com/ntop/ntopng/assets/71812804/2321c192-1e10-495a-9473-a1bc2e23aa4e">

**Comment by NicoMaio** [comment]
Currently, when you run a CVE scan for the first time, and if the host has many CVEs detected, ntopng will call a REST API endpoint to retrieve scores for each CVE. Consequently, you'll see no Nmap process on the machine, and the status will remain as 'scanning' until ntopng finishes retrieving that information.

**Comment by NicoMaio** [comment]
This is not a problem. Currently, the CVE scan type is slower due to the retrieval of the CVE score through the REST call.
