### ISSUE TITLE
Traffic/daily report showing incorrect name for autonomous systems

### ISSUE THREAD

**Issue by mzac** [ntop/ntopng#8350]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04
* Architecture: amd64
* ntopng version/revision: 6.0.240417

**What happened**:
When looking at the daily traffic reports, under the Top Receiver AS the name presented next to the AS sometimes incorrect as well as in the Top Sender AS the name is missing

**How did you reproduce it?**
Look at the daily traffic reports or even the current traffic report

**Debug Information**:
In this image, our AS 15318 (McGill University) is displayed as Altima Telecom. Some other reports it is correct but most are not.  It seems there is maybe a variable being overwritten from a previous loop and is keeping an old entry in memory when the report is generated.

![image](https://github.com/ntop/ntopng/assets/10270879/68a6f54c-22aa-4e2a-bc45-56f191c89c63)

![image](https://github.com/ntop/ntopng/assets/10270879/cd89aebd-453c-4b2f-977c-9db8bcf3409e)

**Comment by cardigliano** [comment]
Could you provide us the output of the below curl command? Replace password, ip and ifid as required. You can also send it by mail to cardigliano at ntop.org. Thank you.

curl -u admin:password 'http://127.0.0.1:3000/lua/pro/rest/v2/get/db/historical_db_search.lua?ifid=0&epoch_begin=1713684177&epoch_end=1713770577&query_preset=top_sender_as&length=20&start=0&aggregated=true'

**Comment by cardigliano** [comment]
And the same for receivers

curl -u admin:password 'http://127.0.0.1:3000/lua/pro/rest/v2/get/db/historical_db_search.lua?ifid=0&epoch_begin=1713684177&epoch_end=1713770577&query_preset=top_receiver_as&length=20&start=0&aggregated=true'

**Comment by cardigliano** [comment]
Probably fixed by d55c90f15b030d3acd18d5113d6c22a6cd89a7f9 (pro), to be backported to stable after testing.
