### ISSUE TITLE
Non standard SNMP Device Layout

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8351]
Invalid Layout

<img width="1643" alt="Screenshot 2024-04-23 at 19 36 22" src="https://github.com/ntop/ntopng/assets/4493366/349edc6d-10bb-44df-a160-1c957231bdfc">

Correct Layout
<img width="1319" alt="Screenshot 2024-04-23 at 19 42 56" src="https://github.com/ntop/ntopng/assets/4493366/0bcc13bd-6b12-4bc6-a4d2-a4c45f966f86">

Misplaced + and rows numbers, as well as search position (before/after the icons).

Please check **all** forms and make sure they are consistent

**Comment by MatteoBiscosi** [comment]
Updated layout with the requested changes, only the number of entries is shifted to the right position because it could be misleading having it at the left of the filters
![image](https://github.com/ntop/ntopng/assets/49585191/c8d5d45c-2eaf-4e1b-8dd9-583aaec4433d)

**Comment by lucaderi** [comment]
Verified as fixed (for SNMP)
