### ISSUE TITLE
Menu Entries must be sorted (if possible)

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8361]
- Alerts (many other menus such as Top Clients/Servers have the same problem)
<img width="252" alt="Screenshot 2024-04-26 at 12 20 04" src="https://github.com/ntop/ntopng/assets/4493366/30850035-f14c-4f2e-9746-12db99c1332a">
- Flows (you can sort by occurrence or alphabetically)
<img width="333" alt="Screenshot 2024-04-26 at 12 21 06" src="https://github.com/ntop/ntopng/assets/4493366/d4681b3a-8870-474e-8172-576f12706304">

In general, keep in mind that menu content must be alphabetically sorted

**Comment by lucaderi** [comment]
Partially woking. Ok for flow status, still unsorted on alerts.

**Comment by MatteoBiscosi** [comment]
For alerts, it's sorted by percentage, not by name, being the TOP, in my opinion it's better to keep it as it is
![image](https://github.com/ntop/ntopng/assets/49585191/abac1611-e975-4401-891f-db6557ddc39f)

**Comment by martinscheu** [comment]
+1 for Matteo's comment, Top something is sorted by the respective percentage of each entry

**Comment by MatteoBiscosi** [comment]
Thanks @martinscheu , for now we will keep the alert dropdowns sorted by percentage
