### ISSUE TITLE
Historical Flows: Minor Connection State Not Mapped Properly

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8363]
<img width="474" alt="Screenshot 2024-04-27 at 11 57 02" src="https://github.com/ntop/ntopng/assets/4493366/b0935786-29f7-4fc2-b95c-1fe1a2ffe761">

**Comment by lucaderi** [comment]
Example of properly mapped
<img width="803" alt="Screenshot 2024-04-27 at 11 58 16" src="https://github.com/ntop/ntopng/assets/4493366/8a978442-7ce1-4b6e-b510-19ea73e93d11">

**Comment by NicoMaio** [comment]
OTH should be 'Attempted' instead of 'Established'?

**Comment by lucaderi** [comment]
Verified as fixed
