### ISSUE TITLE
Support for FreeBSD 15?

### ISSUE THREAD

**Issue by deanfourie1** [ntop/ntopng#8366]
Any news on a upcoming release for FreeBSD 15?

Thanks

**Comment by lucaderi** [comment]
it's not yet out right ?
https://www.freebsd.org/releases/

When it will be released we will support it

**Comment by deanfourie1** [comment]
Oh, how strange.

![image](https://github.com/ntop/ntopng/assets/71812804/8428ef65-7fe4-422d-bd04-9e8c47941585)

**Comment by aibix0001** [comment]
> it's not yet out right ? https://www.freebsd.org/releases/
> 
> When it will be released we will support it

So atm. you don't support pfSense+ anymore?
Can that be done (since pfSense is an officially supported platform of yours)?

I hold an Enterprise M License and cannot use it atm because it won't install.
That kinda s*cks.
