### ISSUE TITLE
Informative Alerts Not Show on on ClickHouse

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8367]
How to reproduce
- Trigger and informative alerts (e.g. ping a host that is on a ntop blacklist)
- A flow with score 10 will be created and an alert is triggered
- if you use SQLite the alert will be shown in the GUI. If you repeat the test with Clickhouse it won't
- On ClickHouse flow alerts are saved into the DB as flows, and accessed with a view
You can reproduce this on Hsol

**Comment by MatteoBiscosi** [comment]
The reason why the alert is not seen on Hsol is the following, only alerts from severity error on are delivered to the gui there.
![image](https://github.com/ntop/ntopng/assets/49585191/80e102e2-4549-4f6c-8b8c-6c8a5fdcf9a2)

**Comment by lucaderi** [comment]
Verified as fixed
