### ISSUE TITLE
SMTP flows triggered DNS Invalid Characters

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8368]
<img width="950" alt="Screenshot 2024-04-30 at 09 27 38" src="https://github.com/ntop/ntopng/assets/4493366/eb101447-89ca-4507-8eeb-d34e93fe1853">

**Comment by cardigliano** [comment]
The real issue here is that there are SMTPS flows which triggered a DNS Invalid Characters alert

<img width="739" alt="Screenshot 2024-04-30 at 09 31 23" src="https://github.com/ntop/ntopng/assets/7548711/6c4ea318-c179-4dd9-8ad8-bdd6739a9f48">

**Comment by lucaderi** [comment]
The DNS issue was solved some time ago, and today the issue cannot be reproduced. Closing it for now
