### ISSUE TITLE
List 'Stratosphere Lab' has 0 rules. Please report this to https://github.com/ntop/ntopng

### ISSUE THREAD

**Issue by noxubell** [ntop/ntopng#8371]
**Environment**:
* OS name: Ubuntu
* OS version: 5.15.0-105-generic [Ubuntu 22.04.3 LTS]
* Architecture: [e.g. amd64]
* ntopng version/revision: ntopng Community v.6.0.240417

**What happened**:
List 'Stratosphere Lab' has 0 rules

**How did you reproduce it?**
Restart ntopng service

**Debug Information**:
None

**Comment by MatteoBiscosi** [comment]
Duplicated of #8372 please, follow that issue
