### ISSUE TITLE
'Stratosphere Lab' has 0 rules

### ISSUE THREAD

**Issue by matthansen0** [ntop/ntopng#8372]
**Environment**:
* OS name: [Ubuntu, Docker Compose]
* OS version: [22.04]
* Architecture: [x86_64]
* ntopng version/revision: [Stable Latest // 6.0.240305]

**What happened**: ``List 'Stratosphere Lab' has 0 rules. Please report this to https://github.com/ntop/ntopng``

**How did you reproduce it?**
Attempt to start the container, I've been running this setup for years and today after patches it started failing. 

![image](https://github.com/ntop/ntopng/assets/23407342/b10e0a0c-febd-429a-bfd6-92b01543fe63)

**Comment by NicoMaio** [comment]
Fixed by 4447c9bbf55f681476c10a54cf8b9f0b3604b458

**Comment by noxubell** [comment]
Modified scripts/lua/modules/lists_utils.lua. Ran Stratosphere Lab update, reporting 10,795 entries now.

**Comment by matthansen0** [comment]
> Modified scripts/lua/modules/lists_utils.lua. Ran Stratosphere Lab update, reporting 10,795 entries now.

How can we kick off a new docker build with this change?

**Comment by noxubell** [comment]
Sorry, I'm not running docker. I just modified the script and reran it.

**Comment by MatteoBiscosi** [comment]
Hi @matthansen0 please update and the issue should be fixed, the last build is from 7 hours ago. In case you sill have the issue please reopen the ticket
