### ISSUE TITLE
Missing score in test peers_swap_heuristic_01

### ISSUE THREAD

**Issue by lucaferret** [ntop/ntopng#8373]
**Environment**:
* OS name: Ubuntu
* OS version:  22.04 LTS
* Architecture: amd64
* ntopng version/revision: 6.1.240502 [Enterprise/Professional build]

**What happened**:
After running the following tests v2/peers_swap_heuristic_01, v2/peers_swap_heuristic_02, v2/peers_swap_heuristic_03, the output does not contain any score, unlike the one in result/v2/peers_swap_heuristic_01.out, result/v2/peers_swap_heuristic_02.out, result/v2/peers_swap_heuristic_03.out which contain "score":100

**How did you reproduce it?**
Inside direcory tests/e2e/rest/
>$  ./run.sh -y=v2/peers_swap_heuristic_01

**Debug Information**:

> $ diff conflicts/v2/peers_swap_heuristic_01.out result/v2/peers_swap_heuristic_01.out
> 1c1
1c1
< {"rc":0,"rc_str":"OK","rc_str_hr":"Success","rsp":{"currentPage":1,"data":[{"breakdown":{"cli2srv":51,"srv2cli":49},"bytes":3675,"client":{"ip":"[192.168.1.122](https://192.168.1.122/)","is_blacklisted":false,"is_broadcast_domain":false,"is_dhcp":false,"name":"78:31:C1:BD:5E:24","port":50513},"duration":1,"first_seen":1614443917,"hash_id":"0","key":"255906621","last_seen":1614443917,"protocol":{"l4":"TCP","l7":"SSH"},"server":{"ip":"[78.152.105.248](https://78.152.105.248/)","is_blacklisted":false,"is_broadcast":false,"is_dhcp":false,"name":"B8:27:EB:2B:90:F1","port":22},"thpt":{"bps":0,"pps":0},"vlan":0}],"perPage":10,"sort":[["column_","desc"]],"totalRows":1}}
\---
> {"rc":0,"rc_str":"OK","rc_str_hr":"Success","rsp":{"currentPage":1,"data":[{"breakdown":{"cli2srv":51,"srv2cli":49},"bytes":3675,"client":{"ip":"[192.168.1.122](https://192.168.1.122/)","is_blacklisted":false,"is_broadcast_domain":false,"is_dhcp":false,"name":"78:31:C1:BD:5E:24","port":50513},"duration":1,"first_seen":1614443917,"hash_id":"0","key":"255906621","last_seen":1614443917,"protocol":{"l4":"TCP","l7":"SSH"},"score":"100","server":{"ip":"[0.0.0.0](https://0.0.0.0/)","is_blacklisted":false,"is_broadcast":false,"is_dhcp":false,"name":"B8:27:EB:2B:90:F1","port":22},"thpt":{"bps":0,"pps":0},"vlan":0}],"perPage":10,"sort":[["column_","desc"]],"totalRows":1}}

**Comment by MatteoBiscosi** [comment]
Before running the tests, it is needed to toggle all checks ( see: get_alert_data_01.yaml )

**Comment by MatteoBiscosi** [comment]
Verified as fixed
