### ISSUE TITLE
VoIP Support Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8375]
This is how ntopng used to handle VoIP https://www.ntop.org/nprobe/monitoring-voip-traffic-with-nprobe-and-ntopng/
- SIP Flows
![image](https://github.com/ntop/ntopng/assets/4493366/a9974cab-a097-45d7-85f1-38da8a21ffb3)
- RTP Flows
![image](https://github.com/ntop/ntopng/assets/4493366/2fe997b4-a3c6-4cfb-8036-edd99bea41fd)

Unfortunately today ntopng is broken
- SIP Flows
<img width="848" alt="Screenshot 2024-05-03 at 11 17 27" src="https://github.com/ntop/ntopng/assets/4493366/98bed111-9693-45f7-b90d-931a6c37335c">
- RTP Flows
<img width="1271" alt="Screenshot 2024-05-03 at 11 17 55" src="https://github.com/ntop/ntopng/assets/4493366/23f0f089-ba21-4657-9a83-6a7c579d1c07">

Note also that in the Info column of the flows page, the description is empty and it does not show who is talking with whom.

HowTo reproduce it
- ntopng -i tcp://127.0.0.1:1234
- nprobe -i voitest.pcap --zmq tcp://127.0.0.1:1234 -T "@NTOPNG@ @SIP@ @RTP@" --redis localhost -b 2 --original-speed -t 10 -d 10

**Comment by MatteoBiscosi** [comment]
Verified as fixed in the latest dev version and partially in the stable version too
