### ISSUE TITLE
Bad ClickHouse Limit Aggregated Flows Limit or Default

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#8376]
Default value is 1000, however the minimum allowed value is 10000, this creates issues when modifying other settings and try to save the page.

<img width="1205" alt="Screenshot 2024-05-03 at 15 42 30" src="https://github.com/ntop/ntopng/assets/7548711/bdffa8d2-8af8-43b0-8ab3-798fdfafa6ff">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
![image](https://github.com/ntop/ntopng/assets/49585191/3a4bf9c2-9e72-46fe-8bf8-68da218cb7e7)
