### ISSUE TITLE
Unable to select interface in webinterface

### ISSUE THREAD

**Issue by MadsRC** [ntop/ntopng#838]
After having used ntopng-pro for some time internally, I agreed to help a customer set ntopng up, and eventually buy the pro edition for them.

The setup is a newly installed, fully updated CentOS 7 server (As of yesterday), with the ntopng repository added. It has 2 interfaces, one of which is a PCI device mapped through the VMware host to the virtual machine using DirectIO. A Cisco switch is mirroring/span'in the network uplink port to the mapped through interface. This should be supported by ntopng, as I did the exact same setup 6 months ago at another location.

Unfortunately, I can't select the mapped through interface in the webinterface. I can select, and see some traffic, on other interface fine though.

I've also tried starting ntop-ng with the --user=root and --interface=ens192, with no success, but ntop won't start then, stating the it's unable to create the interface (Although the interface exists and is listed in `ip link`).

Any idea what could be causing this?

Let me know if any output from any commands are needed.

**Comment by emanuele-f** [comment]
Can you post the full startup log of ntopng and your ip link/ifconfig output?

**Comment by MadsRC** [comment]
Sorry for the delay

Journalctl output is:
```
Dec 02 07:44:36 kd-netmonitor systemd[1]: Starting Start/stop ntopng program...
Dec 02 07:44:36 kd-netmonitor ntopng[962]: [NtopPro.cpp:182] ERROR: [LICENSE] Invalid or missing ntopng License [Empty license file]
Dec 02 07:44:36 kd-netmonitor ntopng[962]: [NtopPro.cpp:195] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
Dec 02 07:44:36 kd-netmonitor ntopng[962]: [NtopPro.cpp:197] WARNING: [LICENSE] before returning to community mode
Dec 02 07:44:36 kd-netmonitor ntopng[962]: [NtopPro.cpp:198] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
Dec 02 07:44:36 kd-netmonitor ntopng[962]: [NtopPro.cpp:199] WARNING: [LICENSE] or run ntopng in community mode starting
Dec 02 07:44:36 kd-netmonitor ntopng[962]: [NtopPro.cpp:200] WARNING: [LICENSE] ntopng --community
Dec 02 07:44:38 kd-netmonitor ntopng[905]: Starting ntopng: [  OK  ]
Dec 02 07:44:38 kd-netmonitor systemd[1]: Started Start/stop ntopng program.
Dec 02 08:13:12 kd-netmonitor ntopng[962]: [NetworkInterface.cpp:1059] WARNING: If you have TSO/GRO enabled, please disable it
Dec 02 08:13:12 kd-netmonitor ntopng[962]: [NetworkInterface.cpp:1061] WARNING: Use: sudo ethtool -K ens160 gro off gso off tso off
Dec 02 08:14:00 kd-netmonitor systemd[1]: Stopping Start/stop ntopng program...
Dec 02 08:14:03 kd-netmonitor ntopng[2263]: Stopping ntopng: [  OK  ]
Dec 02 08:14:03 kd-netmonitor systemd[1]: Stopped Start/stop ntopng program.
Dec 02 08:16:45 kd-netmonitor systemd[1]: Starting Start/stop ntopng program...
Dec 02 08:16:45 kd-netmonitor ntopng[2380]: [NtopPro.cpp:182] ERROR: [LICENSE] Invalid or missing ntopng License [Empty license file]
Dec 02 08:16:45 kd-netmonitor ntopng[2380]: [NtopPro.cpp:195] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
Dec 02 08:16:45 kd-netmonitor ntopng[2380]: [NtopPro.cpp:197] WARNING: [LICENSE] before returning to community mode
Dec 02 08:16:45 kd-netmonitor ntopng[2380]: [NtopPro.cpp:198] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
Dec 02 08:16:45 kd-netmonitor ntopng[2380]: [NtopPro.cpp:199] WARNING: [LICENSE] or run ntopng in community mode starting
Dec 02 08:16:45 kd-netmonitor ntopng[2380]: [NtopPro.cpp:200] WARNING: [LICENSE] ntopng --community
Dec 02 08:16:48 kd-netmonitor ntopng[2373]: Starting ntopng: [  OK  ]
Dec 02 08:16:48 kd-netmonitor systemd[1]: Started Start/stop ntopng program.
Dec 02 08:16:51 kd-netmonitor ntopng[2380]: [NetworkInterface.cpp:1059] WARNING: If you have TSO/GRO enabled, please disable it
Dec 02 08:16:51 kd-netmonitor ntopng[2380]: [NetworkInterface.cpp:1061] WARNING: Use: sudo ethtool -K ens160 gro off gso off tso off
Dec 02 08:17:06 kd-netmonitor systemd[1]: Stopping Start/stop ntopng program...
Dec 02 08:17:10 kd-netmonitor ntopng[2454]: Stopping ntopng: [  OK  ]
Dec 02 08:17:10 kd-netmonitor systemd[1]: Starting Start/stop ntopng program...
Dec 02 08:17:10 kd-netmonitor ntopng[2517]: [NtopPro.cpp:182] ERROR: [LICENSE] Invalid or missing ntopng License [Empty license file]
Dec 02 08:17:10 kd-netmonitor ntopng[2517]: [NtopPro.cpp:195] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
Dec 02 08:17:10 kd-netmonitor ntopng[2517]: [NtopPro.cpp:197] WARNING: [LICENSE] before returning to community mode
Dec 02 08:17:10 kd-netmonitor ntopng[2517]: [NtopPro.cpp:198] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
Dec 02 08:17:10 kd-netmonitor ntopng[2517]: [NtopPro.cpp:199] WARNING: [LICENSE] or run ntopng in community mode starting
Dec 02 08:17:10 kd-netmonitor ntopng[2517]: [NtopPro.cpp:200] WARNING: [LICENSE] ntopng --community
Dec 02 08:17:12 kd-netmonitor ntopng[2510]: Starting ntopng: [  OK  ]
Dec 02 08:17:12 kd-netmonitor systemd[1]: Started Start/stop ntopng program.
```

ip link
`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ens160: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT qlen 1000
    link/ether 00:50:56:a2:6d:9e brd ff:ff:ff:ff:ff:ff
3: ens192: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT qlen 1000
    link/ether b8:ca:3a:5b:e4:37 brd ff:ff:ff:ff:ff:ff
4: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT
    link/ether f6:c5:98:af:d2:b5 brd ff:ff:ff:ff:ff:ff
`

Could it be as simple as the interface being down? The downed port has a cable attached, which is also attached to the mirroring port in the switch.

**Comment by emanuele-f** [comment]
Since it's a mirroring port, there is no need for the interface to be up.
Please post a *full* ntopng startup log.

**Comment by MadsRC** [comment]
I found out that it was a driver issue. Apparently the igb driver wasn't installed or loaded. Fixed that, and everything runs smoothly. Never seen Linux actually assigning a interface a name while having driver issues though... But I guess there's first time for everything.

--  
Med venlig hilsen | Best regards
Mads R. Havmand

**Comment by simonemainardi** [comment]
Thanks for reporting .
