### ISSUE TITLE
Implement WeChat Recipient for Delivering Alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8382]
Add the integration of WeChat in ntopng for delivering alerts
- [https://developer.work.weixin.qq.com/document/path/99110
- https://open.work.weixin.qq.com/help2/pc/cat?doc_id=14931&person_id=undefined](https://developer-work-weixin-qq-com.translate.goog/document/path/99110?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp)

**Comment by NicoMaio** [comment]
Verified the implementation.
