### ISSUE TITLE
Export PRE/POST NAT in ClickHouse/Elastic and GUI

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8384]
As of today, ntopng allows users to choose what IP (PRE/POST) NAT are used in the GUI.

Today we keep one or the other and had to choose "Use Post-Nat Destination IPv4 Addresses and Ports" or "Use Post-Nat Source IPv4 Addresses and Ports" to replace those values in ntopng preferences even if nProbe is [sending over](https://www.ntop.org/guides/nprobe/cli_options.html#netflow-v9-ipfix-format-t) all of:

     --- [225][Len 4] %POST_NAT_SRC_IPV4_ADDR     %postNatSourceIPv4Address   Post Nat Source IPv4 Address
     --- [226][Len 4] %POST_NAT_DST_IPV4_ADDR     %postNatDestinationIPv4Address      Post Nat Destination IPv4 Address
     --- [227][Len 2] %POST_NAPT_SRC_TRANSPORT_PORT %postNaptSourceTransportPort      Post Napt Source Transport Port
     --- [228][Len 2] %POST_NAPT_DST_TRANSPORT_PORT %postNaptDestinationTransportPort Post Napt Destination Transport Port .

<img width="1103" alt="Screenshot 2024-05-09 at 11 45 03" src="https://github.com/ntop/ntopng/assets/4493366/b7770dbe-bbb1-4770-b093-66e7c4f28408">

This ticket is to request to store both in ClickHouse and Elastic and perform searches on both PRE/POST fields

**Comment by MatteoBiscosi** [comment]
Info correctly exported and represented
![image](https://github.com/ntop/ntopng/assets/49585191/6bd5b8cc-4280-4bda-84b9-51b5b9992a41)
