### ISSUE TITLE
PfSense Unable to start HTTP server on port 3000: Address already in use

### ISSUE THREAD

**Issue by michciopro** [ntop/ntopng#839]
Hello there! I installed Community Release of PfSphere on VMWare Virtual Box, and I want to use it as virtual router for gathering traffic logs and saving them into MYSQL database. PfSphere has ntopng embedded (v.2.3.160927), I can access it through 3000 port, but when it comes to activating traffic logs via shell using this command:
ntopng -F "mysql;localhost;ntopng;flows;root;"
I'm getting error:
[HTTPserver.cpp:503] ERROR: Unable to start HTTP server (IPv4) on ports 3000: Address already in use.
How to solve this issue?

**Comment by emanuele-f** [comment]
You already have a running instance of ntopng listening on port 3000, you need to terminate that first. You can either prevent the ntopng service from automatically load or specify custom options in /etc/ntopng/ntopng.conf and reload the service. Please read the manual https://github.com/ntop/ntopng/blob/dev/doc/UserGuide.pdf for more details.

**Comment by michciopro** [comment]
Ok I can stop the service from running, and then restart it from my shell, but when I do I can't access the web GUI anymore. I don't have etc/ntopng directory, and I can't find the ntopng.conf file

**Comment by michciopro** [comment]
It's like PfSense is generating ntopng.conf file dynamically and there is no mysql option enabled.

**Comment by emanuele-f** [comment]
Can you post the output of ntopng starting from command line?

This forum post https://forum.pfsense.org/index.php?topic=115748.0 says that, as you suspect, PfSense overwrites ntopng configuration.
Since you cannot reach ntopng anymore after stopping the service and running from cli, I suspect you need to do perform port 3000 forwarding manually, as explained in https://doc.pfsense.org/index.php/How_can_I_forward_ports_with_pfSense

Please note that PfSense support it's still work in progress, see https://github.com/ntop/ntopng/issues/297

**Comment by michciopro** [comment]
02/Dec/2016 09:33:32 [Ntop.cpp:1013] Setting local networks to 127.0.0.0/8
02/Dec/2016 09:33:32 [Redis.cpp:92] Successfully connected to redis 127.0.0.1:6379@0
02/Dec/2016 09:33:32 [MySQLDB.cpp:470] Attempting to connect to MySQL for interface dummy...
02/Dec/2016 09:33:32 [MySQLDB.cpp:510] Succesfully connected to MySQL [localhost:root] for interface dummy
02/Dec/2016 09:33:32 [MySQLDB.cpp:470] Attempting to connect to MySQL for interface le0...
02/Dec/2016 09:33:32 [MySQLDB.cpp:510] Succesfully connected to MySQL [localhost:root] for interface le0
02/Dec/2016 09:33:32 [PcapInterface.cpp:85] Reading packets from interface le0...
02/Dec/2016 09:33:32 [Ntop.cpp:1233] Registered interface le0 [id: 0]
02/Dec/2016 09:33:32 [MySQLDB.cpp:470] Attempting to connect to MySQL for interface le0...
02/Dec/2016 09:33:32 [MySQLDB.cpp:510] Succesfully connected to MySQL [localhost:root] for interface le0
02/Dec/2016 09:33:32 [MySQLDB.cpp:470] Attempting to connect to MySQL for interface le2...
02/Dec/2016 09:33:32 [MySQLDB.cpp:510] Succesfully connected to MySQL [localhost:root] for interface le2
02/Dec/2016 09:33:32 [PcapInterface.cpp:85] Reading packets from interface le2...
02/Dec/2016 09:33:32 [Ntop.cpp:1233] Registered interface le2 [id: 1]
02/Dec/2016 09:33:32 [MySQLDB.cpp:470] Attempting to connect to MySQL for interface le2...
02/Dec/2016 09:33:32 [MySQLDB.cpp:510] Succesfully connected to MySQL [localhost:root] for interface le2
02/Dec/2016 09:33:32 [MySQLDB.cpp:470] Attempting to connect to MySQL for interface lo0...
02/Dec/2016 09:33:32 [MySQLDB.cpp:510] Succesfully connected to MySQL [localhost:root] for interface lo0
02/Dec/2016 09:33:32 [PcapInterface.cpp:85] Reading packets from interface lo0...
02/Dec/2016 09:33:32 [Ntop.cpp:1233] Registered interface lo0 [id: 2]
02/Dec/2016 09:33:32 [MySQLDB.cpp:470] Attempting to connect to MySQL for interface lo0...
02/Dec/2016 09:33:32 [Ntop.cpp:1245] Registered interface view le0 [id: 0]
02/Dec/2016 09:33:32 [Ntop.cpp:1245] Registered interface view le2 [id: 1]
02/Dec/2016 09:33:32 [Ntop.cpp:1245] Registered interface view lo0 [id: 2]
02/Dec/2016 09:33:32 [MySQLDB.cpp:510] Succesfully connected to MySQL [localhost:root] for interface lo0
02/Dec/2016 09:33:32 [main.cpp:255] PID stored in file /var/run/ntopng.pid
02/Dec/2016 09:33:32 [Utils.cpp:338] User changed to nobody
02/Dec/2016 09:33:32 [HTTPserver.cpp:464] HTTPS Disabled: missing SSL certificate /usr/local/share/ntopng/httpdocs/ssl/ntopng-cert.pem
02/Dec/2016 09:33:32 [HTTPserver.cpp:466] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
02/Dec/2016 09:33:32 [HTTPserver.cpp:509] Web server dirs [/usr/local/share/ntopng/httpdocs][/usr/local/share/ntopng/scripts]
02/Dec/2016 09:33:32 [HTTPserver.cpp:512] HTTP server listening on port 3000
02/Dec/2016 09:33:32 [main.cpp:295] Working directory: /var/tmp/ntopng
02/Dec/2016 09:33:32 [main.cpp:297] Scripts/HTML pages directory: /usr/local/share/ntopng
02/Dec/2016 09:33:32 [Ntop.cpp:271] Welcome to ntopng i386 v.2.3.160927 - (C) 1998-2016 ntop.org
02/Dec/2016 09:33:32 [PeriodicActivities.cpp:53] Started periodic activities loop...
02/Dec/2016 09:33:32 [RuntimePrefs.cpp:34] Dumping alerts into syslog
02/Dec/2016 09:33:32 [Ntop.cpp:557] Adding fe80::20c:29ff:feba:b9cf/64 as IPv6 local network for le0
02/Dec/2016 09:33:32 [Ntop.cpp:527] Adding 192.168.250.0/24 as IPv4 local network for le0
02/Dec/2016 09:33:32 [Ntop.cpp:557] Adding fe80::20c:29ff:feba:b9e3/64 as IPv6 local network for le2
02/Dec/2016 09:33:32 [Ntop.cpp:527] Adding 192.168.251.0/24 as IPv4 local network for le2
02/Dec/2016 09:33:32 [Ntop.cpp:527] Adding 127.0.0.0/8 as IPv4 local network for lo0
02/Dec/2016 09:33:32 [Ntop.cpp:557] Adding ::1/128 as IPv6 local network for lo0
02/Dec/2016 09:33:32 [Ntop.cpp:557] Adding fe80::1/64 as IPv6 local network for lo0
02/Dec/2016 09:33:32 [NetworkInterface.cpp:1479] Started packet polling on interface le0 [id: 0]...
02/Dec/2016 09:33:32 [NetworkInterface.cpp:1479] Started packet polling on interface le2 [id: 1]...
02/Dec/2016 09:33:32 [NetworkInterface.cpp:1479] Started packet polling on interface lo0 [id: 2]...
02/Dec/2016 09:33:42 [main.cpp:37] Shutting down...
02/Dec/2016 09:33:42 [PcapInterface.cpp:200] Terminated packet polling for lo0
02/Dec/2016 09:33:42 [PcapInterface.cpp:200] Terminated packet polling for le0
02/Dec/2016 09:33:42 [PcapInterface.cpp:200] Terminated packet polling for le2

It seems like it's working but, I can't see it influencing my webGUI

**Comment by emanuele-f** [comment]
Can't you see the "Historical Data Explorer" in the home menu? Are you accessing the correct port?

![s1](https://cloud.githubusercontent.com/assets/5488003/20879257/2893820a-bad3-11e6-8384-c1d087ccfda7.png)

**Comment by michciopro** [comment]
![niedziala](https://cloud.githubusercontent.com/assets/24267393/20880356/00e2d1de-bad8-11e6-9a1a-6953148cd4c6.png)

**Comment by michciopro** [comment]
It's like I can stop service "ntopng" which started triggered by webGUI, but when I want to restart it from shell I can't access webGUI anymore. To access it again i must turn off service in my webGUI pfSense config, start it again, but it doesnt start with mysql option enabled.

**Comment by simonemainardi** [comment]
@michciopro you should follow up with pfsense support. We don't officially support pfsense yet (there's already another issue pending: https://github.com/ntop/ntopng/issues/297). In addition, version 2.3 is just an old development version as the latest stable version is 2.4.

**Comment by michciopro** [comment]
Hello, I solved my issue. All i did was removing ntopng from pfSense tab "System->Package Manager", and reinstalling it from command line using FreeBSD repositiories, it also upgraded ntopng to newer version, in addition i needed to install redis-server (ntopng uses it to host a session) and mysql packages to store traffic data.

**Comment by emanuele-f** [comment]
Thank you for reporting. Closing the issue

**Comment by fkanyesigye** [comment]
Hi, I am facing an issue with setting up historic data. Below is the output i get when i input this code:
ntopng -F "mysql;localhost;ntopng;flows;root;"

 I'll appreciate if someone here can help how to resolve the error to do with ports binding.

19/Jan/2018 09:54:58 [Ntop.cpp:1361] Setting local networks to 127.0.0.0/8
19/Jan/2018 09:54:58 [Redis.cpp:109] Successfully connected to redis 127.0.0.1:6                                                                                                             379@0
19/Jan/2018 09:54:58 [MySQLDB.cpp:627] Attempting to connect to MySQL for interf                                                                                                             ace dummy...
19/Jan/2018 09:54:58 [MySQLDB.cpp:667] Successfully connected to MySQL [localhos                                                                                                             t:root] for interface dummy
19/Jan/2018 09:54:58 [HostPools.cpp:65] Host Pools Available: 4
19/Jan/2018 09:54:58 [MySQLDB.cpp:614] Disconnected from MySQL for interface <un                                                                                                             known>...
19/Jan/2018 09:54:58 [MySQLDB.cpp:627] Attempting to connect to MySQL for interf                                                                                                             ace re1...
19/Jan/2018 09:54:58 [MySQLDB.cpp:667] Successfully connected to MySQL [localhos                                                                                                             t:root] for interface re1
19/Jan/2018 09:54:58 [HostPools.cpp:65] Host Pools Available: 4
19/Jan/2018 09:54:58 [PcapInterface.cpp:86] Reading packets from interface re1..                                                                                                             .
19/Jan/2018 09:54:58 [Ntop.cpp:1466] Registered interface re1 [id: 0]
19/Jan/2018 09:54:58 [MySQLDB.cpp:627] Attempting to connect to MySQL for interf                                                                                                             ace re0...
19/Jan/2018 09:54:58 [MySQLDB.cpp:667] Successfully connected to MySQL [localhos                                                                                                             t:root] for interface re0
19/Jan/2018 09:54:58 [HostPools.cpp:65] Host Pools Available: 4
19/Jan/2018 09:54:58 [PcapInterface.cpp:86] Reading packets from interface re0..                                                                                                             .
19/Jan/2018 09:54:58 [Ntop.cpp:1466] Registered interface re0 [id: 1]
19/Jan/2018 09:54:58 [MySQLDB.cpp:627] Attempting to connect to MySQL for interf                                                                                                             ace lo0...
19/Jan/2018 09:54:58 [MySQLDB.cpp:667] Successfully connected to MySQL [localhos                                                                                                             t:root] for interface lo0
19/Jan/2018 09:54:58 [HostPools.cpp:65] Host Pools Available: 4
19/Jan/2018 09:54:58 [PcapInterface.cpp:86] Reading packets from interface lo0..                                                                                                             .
19/Jan/2018 09:54:58 [Ntop.cpp:1466] Registered interface lo0 [id: 2]
19/Jan/2018 09:54:58 [main.cpp:250] PID stored in file /var/run/ntopng.pid
19/Jan/2018 09:54:58 [HTTPserver.cpp:760] Please read https://github.com/ntop/nt                                                                                                             opng/blob/dev/doc/README.SSL if you want to enable SSL.
19/Jan/2018 09:54:58 [HTTPserver.cpp:793] HTTP logs will be stored on /var/tmp/n                                                                                                             topng/ntopng_access.log
19/Jan/2018 09:54:58 [mongoose.c:4515] ERROR: set_ports_option: cannot bind to 3                                                                                                             000: Address already in use
19/Jan/2018 09:54:58 [HTTPserver.cpp:806] ERROR: Unable to start HTTP server (IP                                                                                                             v4) on ports 3000

**Comment by simonemainardi** [comment]
Very likely there's another ntopng process running. Please stop any running instance before executing from the command line

**Comment by fkanyesigye** [comment]
Thanks I have done that and ran the query again. it however seems to be running endlessly now, as below. I have waiting for it to end for about 10 minutes now. is this normal? do i give it more time to probably finish?

19/Jan/2018 14:31:35 [Ntop.cpp:1361] Setting local networks to 127.0.0.0/8
19/Jan/2018 14:31:35 [Redis.cpp:109] Successfully connected to redis 127.0.0.1:6                                                                                                             379@0
19/Jan/2018 14:31:35 [MySQLDB.cpp:627] Attempting to connect to MySQL for interf                                                                                                             ace dummy...
19/Jan/2018 14:31:35 [MySQLDB.cpp:667] Successfully connected to MySQL [localhos                                                                                                             t:root] for interface dummy
19/Jan/2018 14:31:35 [HostPools.cpp:65] Host Pools Available: 4
19/Jan/2018 14:31:35 [MySQLDB.cpp:614] Disconnected from MySQL for interface <un                                                                                                             known>...
19/Jan/2018 14:31:35 [MySQLDB.cpp:627] Attempting to connect to MySQL for interf                                                                                                             ace re1...
19/Jan/2018 14:31:35 [MySQLDB.cpp:667] Successfully connected to MySQL [localhos                                                                                                             t:root] for interface re1
19/Jan/2018 14:31:35 [HostPools.cpp:65] Host Pools Available: 4
19/Jan/2018 14:31:35 [PcapInterface.cpp:86] Reading packets from interface re1..                                                                                                             .
19/Jan/2018 14:31:35 [Ntop.cpp:1466] Registered interface re1 [id: 0]
19/Jan/2018 14:31:35 [MySQLDB.cpp:627] Attempting to connect to MySQL for interf                                                                                                             ace re0...
19/Jan/2018 14:31:35 [MySQLDB.cpp:667] Successfully connected to MySQL [localhos                                                                                                             t:root] for interface re0
19/Jan/2018 14:31:35 [HostPools.cpp:65] Host Pools Available: 4
19/Jan/2018 14:31:35 [PcapInterface.cpp:86] Reading packets from interface re0..                                                                                                             .
19/Jan/2018 14:31:35 [Ntop.cpp:1466] Registered interface re0 [id: 1]
19/Jan/2018 14:31:35 [MySQLDB.cpp:627] Attempting to connect to MySQL for interf                                                                                                             ace lo0...
19/Jan/2018 14:31:35 [MySQLDB.cpp:667] Successfully connected to MySQL [localhos                                                                                                             t:root] for interface lo0
19/Jan/2018 14:31:35 [HostPools.cpp:65] Host Pools Available: 4
19/Jan/2018 14:31:35 [PcapInterface.cpp:86] Reading packets from interface lo0..                                                                                                             .
19/Jan/2018 14:31:35 [Ntop.cpp:1466] Registered interface lo0 [id: 2]
19/Jan/2018 14:31:35 [main.cpp:250] PID stored in file /var/run/ntopng.pid
19/Jan/2018 14:31:35 [HTTPserver.cpp:760] Please read https://github.com/ntop/nt                                                                                                             opng/blob/dev/doc/README.SSL if you want to enable SSL.
19/Jan/2018 14:31:35 [HTTPserver.cpp:793] HTTP logs will be stored on /var/tmp/n                                                                                                             topng/ntopng_access.log
19/Jan/2018 14:31:35 [Utils.cpp:371] User changed to nobody
19/Jan/2018 14:31:35 [HTTPserver.cpp:814] Web server dirs [/usr/local/share/ntop                                                                                                             ng/httpdocs][/usr/local/share/ntopng/scripts]
19/Jan/2018 14:31:35 [HTTPserver.cpp:817] HTTP server listening on port(s) 3000
19/Jan/2018 14:31:35 [MySQLDB.cpp:614] Disconnected from MySQL for interface re1                                                                                                             ...
19/Jan/2018 14:31:35 [MySQLDB.cpp:627] Attempting to connect to MySQL for interf                                                                                                             ace re1...
19/Jan/2018 14:31:35 [MySQLDB.cpp:667] Successfully connected to MySQL [localhos                                                                                                             t:root] for interface re1
19/Jan/2018 14:31:37 [MySQLDB.cpp:315] MySQL schema update. Altering table flows                                                                                                             v4: renaming BYTES to IN_BYTES and adding OUT_BYTES
19/Jan/2018 14:31:38 [MySQLDB.cpp:315] MySQL schema update. Altering table flows                                                                                                             v6: renaming BYTES to IN_BYTES and adding OUT_BYTES
19/Jan/2018 14:31:38 [MySQLDB.cpp:343] MySQL schema update. Altering table flows                                                                                                             v4: changing engine from InnoDB to MyISAM.
19/Jan/2018 14:31:38 [MySQLDB.cpp:343] MySQL schema update. Altering table flows                                                                                                             v6: changing engine from InnoDB to MyISAM.
19/Jan/2018 14:31:39 [MySQLDB.cpp:369] MySQL schema update. Altering table flows                                                                                                             v4: changing the number of partitions to 8.
19/Jan/2018 14:31:39 [MySQLDB.cpp:369] MySQL schema update. Altering table flows                                                                                                             v6: changing the number of partitions to 8.
19/Jan/2018 14:31:39 [MySQLDB.cpp:398] MySQL schema update. Altering table flows                                                                                                             v4: changing IN_BYTES data type to unsigned int.
19/Jan/2018 14:31:39 [MySQLDB.cpp:398] MySQL schema update. Altering table flows                                                                                                             v4: changing OUT_BYTES data type to unsigned int.
19/Jan/2018 14:31:39 [MySQLDB.cpp:398] MySQL schema update. Altering table flows                                                                                                             v6: changing IN_BYTES data type to unsigned int.
19/Jan/2018 14:31:39 [MySQLDB.cpp:398] MySQL schema update. Altering table flows                                                                                                             v6: changing OUT_BYTES data type to unsigned int.
19/Jan/2018 14:31:39 [main.cpp:311] Working directory: /var/tmp/ntopng
19/Jan/2018 14:31:39 [main.cpp:313] Scripts/HTML pages directory: /usr/local/sha                                                                                                             re/ntopng
19/Jan/2018 14:31:39 [Ntop.cpp:307] Welcome to ntopng amd64 v.3.0.171218 - (C) 1                                                                                                             998-17 ntop.org
19/Jan/2018 14:31:39 [PeriodicActivities.cpp:56] Started periodic activities loo                                                                                                             p...
19/Jan/2018 14:31:39 [Ntop.cpp:607] Adding fe80::c225:e9ff:fe0e:b988/128 as IPv6                                                                                                              interface address for re0
19/Jan/2018 14:31:39 [Ntop.cpp:616] Adding fe80::c225:e9ff:fe0e:b988/64 as IPv6                                                                                                              local network for re0
19/Jan/2018 14:31:39 [Ntop.cpp:580] Adding 41.242.142.218/32 as IPv4 interface a                                                                                                             ddress for re0
19/Jan/2018 14:31:39 [Ntop.cpp:588] Adding 41.242.142.216/29 as IPv4 local netwo                                                                                                             rk for re0
19/Jan/2018 14:31:39 [Ntop.cpp:607] Adding fe80::725a:fff:fe43:3212/128 as IPv6                                                                                                              interface address for re1
19/Jan/2018 14:31:39 [Ntop.cpp:616] Adding fe80::725a:fff:fe43:3212/64 as IPv6 l                                                                                                             ocal network for re1
19/Jan/2018 14:31:39 [Ntop.cpp:580] Adding 192.168.10.1/32 as IPv4 interface add                                                                                                             ress for re1
19/Jan/2018 14:31:39 [Ntop.cpp:588] Adding 192.168.10.0/24 as IPv4 local network                                                                                                              for re1
19/Jan/2018 14:31:39 [Ntop.cpp:607] Adding ::1/128 as IPv6 interface address for                                                                                                              lo0
19/Jan/2018 14:31:39 [Ntop.cpp:616] Adding ::1/128 as IPv6 local network for lo0
19/Jan/2018 14:31:39 [Ntop.cpp:607] Adding fe80::1/128 as IPv6 interface address                                                                                                              for lo0
19/Jan/2018 14:31:39 [Ntop.cpp:616] Adding fe80::1/64 as IPv6 local network for                                                                                                              lo0
19/Jan/2018 14:31:39 [Ntop.cpp:580] Adding 127.0.0.1/32 as IPv4 interface addres                                                                                                             s for lo0
19/Jan/2018 14:31:39 [Ntop.cpp:588] Adding 127.0.0.0/8 as IPv4 local network for                                                                                                              lo0
19/Jan/2018 14:31:39 [NetworkInterface.cpp:2059] Started packet polling on inter                                                                                                             face re1 [id: 0]...
19/Jan/2018 14:31:39 [NetworkInterface.cpp:2059] Started packet polling on inter                                                                                                             face re0 [id: 1]...
19/Jan/2018 14:31:39 [NetworkInterface.cpp:2059] Started packet polling on inter                                                                                                             face lo0 [id: 2]...
19/Jan/2018 14:31:39 [MySQLDB.cpp:627] Attempting to connect to MySQL for interf                                                                                                             ace re1...
19/Jan/2018 14:31:39 [MySQLDB.cpp:627] Attempting to connect to MySQL for interf                                                                                                             ace lo0...
19/Jan/2018 14:31:39 [MySQLDB.cpp:627] Attempting to connect to MySQL for interf                                                                                                             ace re0...
19/Jan/2018 14:31:39 [MySQLDB.cpp:667] Successfully connected to MySQL [localhos                                                                                                             t:root] for interface re1
19/Jan/2018 14:31:39 [MySQLDB.cpp:667] Successfully connected to MySQL [localhos                                                                                                             t:root] for interface lo0
19/Jan/2018 14:31:39 [MySQLDB.cpp:667] Successfully connected to MySQL [localhos                                                                                                             t:root] for interface re0

**Comment by simonemainardi** [comment]
yes, wait or create a new database. it's running a schema migration after an update. it's a one-time procedure that takes some time.

**Comment by fkanyesigye** [comment]
Thanks. Will wait.

**Comment by fkanyesigye** [comment]
It appears to be stuck at some point, not loading anymore. Would you be able to help further? Thank you
