### ISSUE TITLE
NtopNG Error (Too many Interfaces)

### ISSUE THREAD

**Issue by awptechnologies** [ntop/ntopng#8390]
**Environment**:
* OS name: OPNsense
* OS version:  OPNsense 24.1.6-amd64, FreeBSD 13.2-RELEASE-p11
* Architecture: amd64
* ntopng version/revision:  6.0.d20240307,1

**What happened**:
I keep getting these errors
ERROR: Too many interfaces (8): discarded bge1
ERROR: Hint: reset redis (redis-cli flushall) and then start ntopng again

I have over 8 interfaces and when trying to monitor all of them i get these errors. If i uncheck a few of them and keep only 8 total the errors go away. Is this a bug or does ntopng only allow monitoring of 8 interfaces?

**How did you reproduce it?**
Enable more then 8 interfaces.

**Comment by lucaderi** [comment]
It is a license limitation to avoid people put too much load on ntopng. Enterprise licenses do not have such limitation https://www.ntop.org/products/traffic-analysis/ntop/

**Comment by awptechnologies** [comment]
Is there a way to get the license version in opnsense? I dont see an option in the plugin settings
