### ISSUE TITLE
Add SNMP Interface Toggle

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8392]
In this page

<img width="1192" alt="Screenshot 2024-05-15 at 06 47 53" src="https://github.com/ntop/ntopng/assets/4493366/b80ad4eb-6dfb-48dd-9ade-e2812714d22a">

implement a new toggle (disabled by default) that per interface enables/disables QoS MIB Polling

**Comment by NicoMaio** [comment]
Add toggle in PRO repo by (85236144f4eac9d9280b47857ed3e1e583fdb6f8)

To verify if the toggle is enabled please use `snmp_utils.is_snmp_device_interface_qos_mib_polling_enabled(device_ip, port)` method.

**Comment by MatteoBiscosi** [comment]
The toggle is not properly done, it needs to be added to the device page otherwise in case of a device with multiple qos interfaces it could be a problem to toggle all of them one by one

**Comment by MatteoBiscosi** [comment]
Implemented as requested
![image](https://github.com/ntop/ntopng/assets/49585191/7abfb246-0f38-4a35-80b3-5e077a3902a4)
