### ISSUE TITLE
Remediations not working with nDPI checks

### ISSUE THREAD

**Issue by NicoMaio** [ntop/ntopng#8395]
Currently the link to the remediation not working for nDPI flow risks. 
It's necessary to use a method that recognizes if the alert id is an nDPI flow risk or a ntopng flow risk and returns the correct link to the documentation (for ntopng: https://www.ntop.org/guides/ntopng/remediations/flow_risks.html for nDPI: https://www.ntop.org/guides/nDPI/flow_risks.html).

**Comment by DGabri** [comment]
fixed
