### ISSUE TITLE
Help with install on OPNSense

### ISSUE THREAD

**Issue by deanfourie1** [ntop/ntopng#8397]
**Environment**:
* OS name: FreeBSD
* OS version: 13
* Architecture: amd64
* ntopng version/revision: latest

**What happened**:
Attempting to install on OPNSense from here
https://packages.ntop.org/FreeBSD/

**How did you reproduce it?**
Followed the instructions

**Debug Information**:
Everything seems to run correctly, however doesnt appear to be any listening socket on port 3000?

**Comment by MatteoBiscosi** [comment]
Hi @deanfourie1 please follow these instructions and if it's not working re-open the ticket please https://www.ntop.org/guides/ntopng/what_is_ntopng.html#installing-on-opnsense-pfsense
