### ISSUE TITLE
External - ntop.org down

### ISSUE THREAD

**Issue by HussX** [ntop/ntopng#8399]
**Environment**:
Android, Ubuntu server, Windows 10, tried multiples 

**What happened**:
Ntop.org is down

**How did you reproduce it?**
Tried to visit ntop.org. verified with a couple bounce servers

**Debug Information**:

**Comment by lucaderi** [comment]
What is your IP? it works for us

**Comment by HussX** [comment]
The irony. I'd tried the last two days via cellular, hotel Wi-Fi, and VPN
from another state (various IPs across public Internet) and the site
wouldn't respond whether ntop.org or packages.ntop.org. I just tried from
my phone today and it's responding.  This can be marked closed, now.
