### ISSUE TITLE
ntopng on OS X strange error 500

### ISSUE THREAD

**Issue by Drewshg312** [ntop/ntopng#84]
Hi! I've installed ntopng on mac os x yosemite 10.10.4
I have this in "About ntopng" tab:
![untitled1](https://cloud.githubusercontent.com/assets/10493450/8660995/81828a0c-2969-11e5-91db-0aea737a2905.jpg)

**Comment by lucaderi** [comment]
Can you please check if the code in github fixes the issue?

**Comment by Drewshg312** [comment]
do you mean the master repo? which version is it? There is 2.0v (Stable) in brew...

**Comment by lucaderi** [comment]
The master dev repo. I think we fixed the issue so we can back port the fix

**Comment by Drewshg312** [comment]
In which version was it fixed? I've reported it in Homebrew but they say they don't have the issue...
How do I install it without brew? Is there an instrutction?

**Comment by ariava** [comment]
@Drewshg312 you must clone this git repository and get the dev branch (it's the default branch). Then you can compile it and run it.

**Comment by lucaderi** [comment]
We update homebrew periodically with the new sw release. For the time being please use the development branch on git.

**Comment by Drewshg312** [comment]
With the latest dev version getting this:

    -I/private/tmp/ntopng20150822-24304-1qbxoul/third-party/EWAHBoolArray/headers  -DDATA_DIR='"/usr/local/Cellar/ntopng/HEAD/share"' -I/private/tmp/ntopng20150822-24304-1qbxoul/third-party/libgeohash -I/private/tmp/ntopng20150822-24304-1qbxoul/third-party/patricia   -c src/Flow.cpp -o src/Flow.o
    src/Flow.cpp:96:28: error: assigning to 'u_int16_t' (aka 'unsigned short') from incompatible type 'ndpi_protocol'
          (aka 'ndpi_proto')
        ndpi_detected_protocol = ndpi_guess_undetected_protocol(iface->get_ndpi_struct(),
                               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/Flow.cpp:469:30: error: assigning to 'u_int16_t' (aka 'unsigned short') from incompatible type 'ndpi_protocol'
          (aka 'ndpi_proto')
          ndpi_detected_protocol = ndpi_guess_undetected_protocol(iface->get_ndpi_struct(), protocol,
                                 ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    2 errors generated.
    make: *** [src/Flow.o] Error 1

**Comment by lucaderi** [comment]
Your nDPI is newer than your ntopng code

**Comment by Drewshg312** [comment]
Sorry so what does that mean?

**Comment by lucaderi** [comment]
Use the code of ntopng that's on git

**Comment by Drewshg312** [comment]
Ok

**Comment by Drewshg312** [comment]
Well we are actually using the nDPI and ntopng codes from git… and still getting these errors
