### ISSUE TITLE
Identify Plex as a Custom Proto

### ISSUE THREAD

**Issue by depraved22** [ntop/ntopng#840]
I opened up this issue for nDPI:

https://github.com/ntop/nDPI/issues/309

It was asked to come over here as I'm running:

```
Version	2.4.161130 - Pro Small Business Edition
Built on	Ubuntu 16.04.1 LTS
nDPI	1.8.0-1.8-stable-467-6450ae2
```

Startup line:

`Startup Line	ntopng --interface "p3p1" --http-port "3000" --dns-mode "1" --local-networks "192.168.1.0/24" --data-dir "/var/tmp/ntopng" --disable-autologout "" --ndpi-protocols "/etc/ntopng/custom.protos" --http-prefix "/ntopng" --daemon "" --disable-login "1" --dump-flows "mysql;localhost;ntopng;flows;ntopng;somepassword"`

When I bring up the flows, it shows my custom proto Plex as finds it as SSL instead:

http://imgur.com/a/xk9P8

**Comment by emanuele-f** [comment]
Hi, I've tested your pcap file with ntopng 2.5 and the protocol Plex is correctly identified.

![screenshot at 2016-12-01 10-38-05](https://cloud.githubusercontent.com/assets/5488003/20788910/dab1c25e-b7b2-11e6-82fa-7db2732eb698.png)

Please update to get the latest features and fixes. Thank you.

**Comment by depraved22** [comment]
Does 2.5 exist with the Pro version? I don't see it anywhere to download.

**Comment by emanuele-f** [comment]
Yes of course, please check out http://packages.ntop.org/

**Comment by depraved22** [comment]
Thanks. I was looking in the stable area and not finding it. I installed it and it seems to be picking it up via my limited test. Thanks!
