### ISSUE TITLE
Loading configuration json of 250kB fails

### ISSUE THREAD

**Issue by gabviv73** [ntop/ntopng#8401]
**Environment**:
* OS name: Red Hat Enterprise Linux
* OS version: 8.8
* Architecture: amd64
* ntopng version/revision: Version:	5.4.221019 [Enterprise/Professional build]
GIT rev:	5.4-stable:d7aa929869785a332ab0952c12e891fc82b7582b:20221019
Pro rev:	r5132
Built on:	Rocky Linux release 8.5 (Green Obsidian)
System Id:	LF4EAEB32B208AA8C--UF4EAEB32A7841883--OL
Platform:	x86_64
Edition:	Enterprise L (Bundle)

**What happened**:
Loading an host pool file of 250kB fails with error:

` May 23 19:22:31 host.example.com ntopng[795563]: [LuaEngine.cpp:974] WARNING: Too much data submitted with the form. [data len: 451877][max len: 131072][URI: /lua/rest/v2/import/pool/config.lua]
May 23 19:22:31 host.example.com  ntopng[795563]: 23/May/2024 19:22:31 [LuaEngine.cpp:974] WARNING: Too much data submitted with the form. [data len: 451877][max len: 131072][URI: /lua/rest/v2/import/pool/config.lua]`

**Comment by lucaderi** [comment]
Can you please send me in private (deri@ntop.org) via email, such file for inspection?

**Comment by gabviv73** [comment]
Sent.

**Comment by MatteoBiscosi** [comment]
Issue fixed in the last update (available in a couple of hours) however please read the mail i sent that some errors could arise while importing that file
