### ISSUE TITLE
rrd.lua errors

### ISSUE THREAD

**Issue by b1b3tt3r** [ntop/ntopng#8412]
**Environment**: 28/May/2024 08:17:39 [Ntop.cpp:523] Welcome to ntopng x86_64 v.6.0.240517 (6.0-stable:1e72bf79c9eeceb91faf015aa56d4263ed1e171c:20240517)
28/May/2024 08:17:39 [Ntop.cpp:532] Built on Ubuntu 22.04.4 LTS

**What happened**:
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/6031/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2659/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/5067/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/5932/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/6037/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2068/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2582/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2747/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/5048/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/3056/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/208/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/6032/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2437/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/299/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/3048/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/5182/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2439/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2901/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/323/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/4033/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2904/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2138/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2143/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/5049/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2900/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/4048/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/272/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/6029/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2743/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/220/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2998/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/6042/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/6101/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:01:10 [LuaEngine.cpp:610] WARNING: ...o/scripts/lua/modules/snmp_dev_threshold_check_rules.lua:415: attempt to compare number with string
28/May/2024 13:06:14 [LuaEngine.cpp:610] WARNING: ...o/scripts/lua/modules/snmp_dev_threshold_check_rules.lua:415: attempt to compare number with string
28/May/2024 13:06:36 [LuaEngineNtop.cpp:6137] WARNING: Overwriting already existing RRD [/var/lib/ntopng/2/asnstats/3/6/0/0/7/HTTP_Proxy.rrd]
28/May/2024 13:10:16 [LuaEngine.cpp:610] WARNING: ...o/scripts/lua/modules/snmp_dev_threshold_check_rules.lua:415: attempt to compare number with string
28/May/2024 13:16:31 [LuaEngine.cpp:610] WARNING: ...o/scripts/lua/modules/snmp_dev_threshold_check_rules.lua:415: attempt to compare number with string

**How did you reproduce it?**
It appears after several minutes

**Debug Information**:
28/May/2024 13:01:10 [LuaEngine.cpp:610] WARNING: ...o/scripts/lua/modules/snmp_dev_threshold_check_rules.lua:415: attempt to compare number with string
28/May/2024 13:06:14 [LuaEngine.cpp:610] WARNING: ...o/scripts/lua/modules/snmp_dev_threshold_check_rules.lua:415: attempt to compare number with string
28/May/2024 13:06:36 [LuaEngineNtop.cpp:6137] WARNING: Overwriting already existing RRD [/var/lib/ntopng/2/asnstats/3/6/0/0/7/HTTP_Proxy.rrd]
28/May/2024 13:10:16 [LuaEngine.cpp:610] WARNING: ...o/scripts/lua/modules/snmp_dev_threshold_check_rules.lua:415: attempt to compare number with string
28/May/2024 13:16:31 [LuaEngine.cpp:610] WARNING: ...o/scripts/lua/modules/snmp_dev_threshold_check_rules.lua:415: attempt to compare number with string
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2051/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/5428/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/5964/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2931/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/6037/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/5051/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2576/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2883/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/324/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/224/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/200/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/3048/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/325/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/5048/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/4048/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/322/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2147/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2900/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/6018/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2881/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/303/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/5972/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/6039/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/5929/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/208/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/196/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2911/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/6045/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/296/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/5988/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/6040/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/6042/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/6047/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2069/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2659/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2574/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/260/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
28/May/2024 13:21:42 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2138/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?

**Comment by MatteoBiscosi** [comment]
Hi @b1b3tt3r this issue usually starts when no more disk is available or there was some issue when writing timeseries on RRD file and unfortunately if this is the case we are not able to fix it.
Please remove the timeseries of the 172.25.0.64 snmp device and it should be fixed if the disk space is okay.
To remove those timeseries run 
'sudo rm -r /var/lib/ntopng/-1/snmpstats/172/25/0/64'

**Comment by b1b3tt3r** [comment]
Thank you for researching.
I am not seeing a disk issue regarding space.
Could it be disk latency?

**Comment by MatteoBiscosi** [comment]
yes it could be disk latency but sincerely speaking it's really rare and maybe it's my second time seeing your issue (consider we have a testing machine with solid disk, no ssd, no m2 and it never happened in more than 4 years). Have you tried removing the rrds i told you about? does the issue persist?

**Comment by b1b3tt3r** [comment]
I have done so this morning.
The last errors reported are here:
31/May/2024 06:20:07 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/6026/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
31/May/2024 06:20:07 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2147/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
31/May/2024 06:20:07 [LuaEngine.cpp:610] WARNING: ...o/scripts/lua/modules/snmp_dev_threshold_check_rules.lua:415: attempt to compare number with string
31/May/2024 06:26:20 [LuaEngine.cpp:610] WARNING: ...o/scripts/lua/modules/snmp_dev_threshold_check_rules.lua:415: attempt to compare number with string
31/May/2024 06:30:37 [LuaEngine.cpp:610] WARNING: ...o/scripts/lua/modules/snmp_dev_threshold_check_rules.lua:415: attempt to compare number with string


I am seeing time drift of up to 6 minutes, do you think it could be related?
I will continue to monitor.

**Comment by MatteoBiscosi** [comment]
Hi @b1b3tt3r stop ntopng service and remove all folders and files in /var/lib/ntopng/-1/snmpstats/172/25/0/64 then restart ntopng.
I'll check that attempt to compare failed. Which ntopng --version do you have? have you set up some rules for snmp? in case could you please send me those threshold (i'll try to add them trying to reproduce your issue)?

**Comment by b1b3tt3r** [comment]
LOL.... I missed the second part of the command a deleted the entire directory!
Oh Joy....
Just restarted... Monitoring.

**Comment by b1b3tt3r** [comment]
Sadly, same issue...
31/May/2024 08:36:05 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/3090/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
31/May/2024 08:36:05 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/324/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
31/May/2024 08:36:05 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/224/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
31/May/2024 08:36:05 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/6045/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
31/May/2024 08:36:05 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2998/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
31/May/2024 08:36:05 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/64/2057/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
31/May/2024 08:36:07 [LuaEngine.cpp:610] WARNING: ...o/scripts/lua/modules/snmp_dev_threshold_check_rules.lua:415: attempt to compare number with string

**Comment by b1b3tt3r** [comment]
Interestingly enough the Redis statistics look good.
Clickhouse stats are not visible from the System Gui?

**Comment by MatteoBiscosi** [comment]
yes they are visible from the system interface. that issue is however from rrd (timeseries), i'll think of a way and let you know asap

**Comment by b1b3tt3r** [comment]
The CPU is running 99.5%, I'll add another CPU and see if it helps

**Comment by lucaderi** [comment]
@b1b3tt3r Can you please check if you have only ntopng instance running on the host?

**Comment by b1b3tt3r** [comment]
It is a dedicated VM on an ESX host.

The error has move to another device ip
03/Jun/2024 17:15:12 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/31/2137/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
03/Jun/2024 17:15:12 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/31/2910/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
03/Jun/2024 17:15:12 [LuaEngineNtop.cpp:6458] ERROR: Error 'malloc fetch data area' while calling rrd_fetch_r(/var/lib/ntopng/-1/snmpstats/172/25/0/31/2714/bytes.rrd, AVERAGE): is the RRD corrupted perhaps?
03/Jun/2024 17:15:12 [LuaEngine.cpp:610] WARNING: ...o/scripts/lua/modules/snmp_dev_threshold_check_rules.lua:415: attempt to compare number with string
 
 It also has Fail2ban running.

**Comment by MatteoBiscosi** [comment]
Hi @b1b3tt3r please drop an email at `biscosi at ntop.org` and we'll schedule a support call if you are okay with that.

**Comment by MatteoBiscosi** [comment]
The issue seems fixed with --dont-change-user option added to the config file
