### ISSUE TITLE
Ntopng log spammed with unnecessary ZMQ messages

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#8418]
Ubuntu 22.04.3 LTS
ntopng v.6.0.240531
Clickhouse 24.3.3.102

Hello team!
Ntopng log spammed with unnecessary messages.
Ntopng configured to receive flows from nprobe via ZMQ on the same host.
Other deployments configured the same way doesn't show this messages.

31/May/2024 20:57:55 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":48,"4":6,"5":10000000000,"6":"Full","7":"Up","8":"Down","9":1075730378,"10":14536897,"11":0,"12":1075730674,"13":14536901,"14":0,"15":2}
31/May/2024 20:57:55 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":47,"4":6,"5":10000000000,"6":"Full","7":"Up","8":"Down","9":1075731784,"10":14536916,"11":0,"12":1075731636,"13":14536914,"14":0,"15":2}
31/May/2024 20:57:55 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":46,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:55 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":45,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:55 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":44,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:55 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":43,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":42,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":41,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":40,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":39,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":38,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":37,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":36,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":35,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":34,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":33,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":32,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":31,"4":6,"5":0,"6":"Half","7":"Up","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":30,"4":6,"5":0,"6":"Half","7":"Up","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":29,"4":6,"5":0,"6":"Half","7":"Up","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":28,"4":6,"5":0,"6":"Half","7":"Up","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":27,"4":6,"5":0,"6":"Half","7":"Up","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":26,"4":6,"5":0,"6":"Half","7":"Up","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":25,"4":6,"5":0,"6":"Half","7":"Up","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":24,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":23,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":22,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":21,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":20,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":19,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":18,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}
31/May/2024 20:57:54 [ZMQParserInterface.cpp:2289] {"0":174325523,"1":43839,"2":17,"4":6,"5":0,"6":"Half","7":"Down","8":"Down","9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":2}

**Comment by cardigliano** [comment]
Fixed, an update will be available shortly
