### ISSUE TITLE
Implement Missing Alerts URL

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8421]
Add an alerts icon 
<img width="684" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/2ab4bd45-b222-4060-b807-fdfd03f95850">

Similar to the hosts page

<img width="284" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/a7971d27-3738-4230-8b6d-92dbc393cc46">

that sends the user to the alerts page in the SNMP section with filter set to this device/interface

**Comment by DGabri** [comment]
Implemented
