### ISSUE TITLE
Incomplete SNMP Status Mapping

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8423]
It seems that in the interface list only Up/Down are shown 
<img width="702" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/bd9c6962-2e3a-4cf3-b2e2-2455c04e77ff">
instead of all statuses mapped in snmp_consts.snmp_ifstatus(

**Comment by DGabri** [comment]
This happened at startup, after some time the status appears on all interfaces. When logging the status value it was nil

**Comment by MatteoBiscosi** [comment]
Verified as fixed
