### ISSUE TITLE
No traffic analyze on kafka interface

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#8425]
Ubuntu 22.04.3 LTS
ntopng v.6.0.240531

Hello!
Ntopng doesn't analyze traffic and networks on kafka interface.
Kafka interface is the only one configured.
No traffic breakdown, no networks statistics.
Local / remote hosts correctly displayed in flow page.
Local-networks configured as --local-networks=/etc/ntopng/local-networks.conf
No erros / warnings on startup in log.
It is the same ntopng instance as in #8409.

![ntopng-traffic-1](https://github.com/ntop/ntopng/assets/67421019/4d75ce7b-ed7c-43da-9c58-fa63c68892c6)

![ntopng-traffic-2](https://github.com/ntop/ntopng/assets/67421019/a3ce30d7-6b1a-4e92-91e6-5a2cb587afb9)

**Comment by atemix** [comment]
Local HTTP Servers also empty.

**Comment by lucaderi** [comment]
Can you please paste the nprobe and ntopng configuration files?

**Comment by atemix** [comment]
Hi @lucaderi 

--interface="kafka://127.0.0.1:[XXX]"
--instance-name=XXX
--data-dir=/[XXX]/ntopng
--pcap-dir=/[XXX]/n2disk
--http-port=0
--https-port=443
--max-num-hosts=1048576
--max-num-flows=67108864
--dns-mode=3
--local-networks=/etc/ntopng/local-networks.conf
--dump-flows="clickhouse;XXX;ntopng;XXX;XXX"
--ignore-vlans
--offline


--disable-startup-checks=
--pid-file=/var/run/nprobe-netflow.pid
--collector-port=2055
--kafka="[XXX]:[XXX];flow;option"
--kafka-conf="security.protocol=ssl"
--kafka-conf="ssl.ca.location=/etc/nprobe/[XXX]"
--kafka-conf="ssl.keystore.location=/etc/nprobe/[XXX].jks"
--kafka-conf="ssl.keystore.password=[XXX]"
-T="@NTOPNG@"
-E=0:999
-i=none
-n=none
-a=
--flow-deduplication=15

**Comment by atemix** [comment]
After updating to dev 6.1.240603 nothing change.
Still no traffic breakdown and networks.

**Comment by lucaderi** [comment]
Please see https://www.ntop.org/nprobe/howto-use-kafka-instead-of-zmq-for-reliable-flow-collection-and-ipc/ that shows how to configure ntopng and nProbe when using Kafka. Your nprobe kafka configuration is good for exporting data to a kafka broker with consumers different from ntopng. If you want to use ntopng you need to do something like
- nprobe -i eno1 –ntopng  kafka://192.168.2.225
- ntopng -i kafka://192.168.2.225

**Comment by atemix** [comment]
nprobe reconfigured:

#cat /etc/ntopng/ntopng.conf | grep kafka
--interface="kafka://127.0.0.1:9091"
#cat /etc/nprobe/nprobe-netflow.conf | grep kafka
--ntopng="kafka://127.0.0.1:9091"
#cat /etc/nprobe/nprobe-sflow.conf | grep kafka
--ntopng="kafka://127.0.0.1:9091"
 
No change, ntopng shows No traffic yet.
On ntopng restart on a second appears traffic breakdown pie and exported flow count, but then again No traffic yet.

Nprobe creates 8 topics in kafka, but 4 of them remain empty. Is it normal?
counter, listening-ports, snmp-ifaces, template.
