### ISSUE TITLE
Missing Advertised Interface Speed

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8426]
<img width="987" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/99243858-7aa9-4d98-a2dc-3bdb318313b0">
In this dialog, we see the configured speed but not the advertised (via SNMP) speed.

This is to request to
- display the advertised speed
- add a speed reset button to revert it to the advertised speed

**Comment by DGabri** [comment]
Implemented as requested
