### ISSUE TITLE
nedge Preferences menu errors

### ISSUE THREAD

**Issue by tano46** [ntop/ntopng#8427]
**Environment**:
* OS name: [Ubuntu]
* OS version: [20.04]
* Architecture: [amd64]
* ntopng version/revision: [e.g. 6.1.240521]

**What happened**:
Accessing to Settings -> Preferences  (Expert View)
- Behaviour Analysis menu is empty, only inactive "save" button visible
- Reports Menu to be removed? Functionality not available for nedge
- Vulnerability Scan Menu to be removed? Functionality not available for nedge

**Comment by MatteoBiscosi** [comment]
In the latest ntopng version these issues should already be addressed. Please update and let me know.

**Comment by tano46** [comment]
Reports and Vulnerablity Scan menu correctly eliminated.
Also Behaviour Analysis has been removed, it is correct?

**Comment by MatteoBiscosi** [comment]
Hi @tano46, yes this is correct
