### ISSUE TITLE
Network matrix doesn't loading on ZMQ interface

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#8432]
ntopng v.6.0.240603 (Ubuntu 22.04.4 LTS)

On ZMQ (for nprobe) interface network matrix often doesn't loading, only sometimes it's shown. 
We can't identify a pattern when it's shown.
On span interface always works well.
Local networks defined through  --local-networks=/etc/ntopng/local-networks.conf.

In browser console:
network_stats.lua:746 Uncaught TypeError: Cannot read properties of undefined (reading 'data')
    at Object.click (network_stats.lua:746:55)
    at HTMLDivElement.<anonymous> (third-party.js?1717522204:2:752263)

![image](https://github.com/ntop/ntopng/assets/67421019/53721084-bdc1-4831-8142-47bdfe2990a0)

**Comment by DGabri** [comment]
Hello there, on my side it seems that the network matrix is showing. It does not show if -m is not defined when starting ntopng. Could you please double check the content of the config and check that it is correct?

**Comment by atemix** [comment]
Hi @DGabri 
Network matrix works on span interface, but not on netflow interface in the same ntopng instance.
Local networks configured through --local-networks=/etc/ntopng/local-networks.conf.
If it were errors, matrix didn't working at all.
But local netwotks counters showns correctly on both interfaces.

SPAN

![ntopng-matrix-span](https://github.com/ntop/ntopng/assets/67421019/df0624ef-ceee-4f17-9a0e-ffd986675ee8)

Netflow

![ntopng-matrix-netflow](https://github.com/ntop/ntopng/assets/67421019/51d736e4-ebc6-4bb4-9ae1-eb1b38c02b39)

**Comment by DGabri** [comment]
I see, I will check and let you know, thanks for the additional info

**Comment by DGabri** [comment]
Hi there, we tested and were never able to reproduce this error, could you please provide a browser console screenshot when the error happens and also provide a screenshot of the code that opens if you click on the error in console?
An example of screenshot that you should click on is shown below. You have to click on the link on the right, githubBase etc in the photo,. The ntopng error will of course be different but located on the same position
Thank you

![Screenshot 2024-06-21 at 09 58 20](https://github.com/ntop/ntopng/assets/33870399/1a03b443-b2fa-4259-acd4-9ef193b61cb6)

**Comment by atemix** [comment]
Hi @DGabri 

No errors on page loading:

![image](https://github.com/ntop/ntopng/assets/67421019/0fa04d48-7663-4fdd-b2b8-a530b355d1c6)

After clicking on matrix place:

![image](https://github.com/ntop/ntopng/assets/67421019/0c6dbeca-2353-4a2b-8396-b9f4f377b4ea)
![image](https://github.com/ntop/ntopng/assets/67421019/cd563b52-795b-40db-bdae-a5695eea1429)

**Comment by MatteoBiscosi** [comment]
Hi @atemix please update in a couple of hours and let me know

**Comment by atemix** [comment]
@MatteoBiscosi, no matrix on zmq interface after update, and no any errors in console.

![image](https://github.com/ntop/ntopng/assets/67421019/caf191b5-8317-448d-8cf6-4b0dcbc35f13)

**Comment by lucaderi** [comment]
<img width="1542" alt="Screenshot 2024-08-03 at 21 37 21" src="https://github.com/user-attachments/assets/a39e7c5e-6b2a-4d12-bf27-e649dd38bec7">
Just checked: it works for us
