### ISSUE TITLE
Infrastrucure monitoring on Ubuntu 22.04 not working

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#8434]
ntopng 6.1.240603 (Ubuntu 22.04.4 LTS)
ntopng 6.0.240603 (Rocky Linux release 8.8)

We have remote ntopng deployments on ubuntu and centos, and central deployment on ubuntu.
Infrastructure monitoring works only from remote instance on centos to central on ubuntu.
But it doesn't works from central ubuntu to any remote ntopng, doesn't matter centos or ubuntu it is.
Check hangs on testing authentification.

Infrastucture monitoring on remote centos to central instance configured through https://IP_address, certificates from internal CA with IP in SAN.
openssl s_client -connect [IP]:443 verified from any remore instance to core and vice verse.

![image](https://github.com/ntop/ntopng/assets/67421019/d3b38b44-87f2-4dce-ac8b-6a6c46ce7505)

**Comment by atemix** [comment]
In log:
ntopng[128772]: 05/Jun/2024 23:08:26 [LuaEngine.cpp:1396] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/check/infrastructure/config.lua][/usr/share/ntopng/scripts/lua/modules/dkjson.lua:397: bad argument #1 to 'strfind' (string expected, got nil)]

**Comment by cardigliano** [comment]
@atemix does it mean you are running different versions, stable on Rocky and dev on Ubuntu? IT would be better not to mix versions for different reasons (to avoid possible incompatibility, to help identifying if it depends on the version or the OS, etc.)
Please also clarify what to/from means to make sure we get which direction is not working.
Thank you

**Comment by atemix** [comment]
Hi @cardigliano, no, it's my mistake, central instance was downgraded to stable. All our deployments on 6.0.240603 Ubuntu / Rocky.

![image](https://github.com/ntop/ntopng/assets/67421019/9c3d7c99-9c82-4444-8db2-1cfb5f5119de)

**Comment by cardigliano** [comment]
I ran a few tests in our lab, infrastructure monitoring seems to be actually working on Ubuntu 22.04.4 LTS, tested with both v.6.0.240603 and v.6.1.240528 in all combinations/directions. This is strange.

**Comment by cardigliano** [comment]
I realised HTTPS is used here, it may be related. Checking.

**Comment by atemix** [comment]
We have Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-83-generic x86_64) if it's important.

**Comment by cardigliano** [comment]
@atemix I think I found the root cause, "in Ubuntu 22.04 LTS curl is version 7.81.0, and fails in case of unexpected EOF with OpenSSL 3.0.x" as you can also read at https://stackoverflow.com/questions/72627218/openssl-error-messages-error0a000126ssl-routinesunexpected-eof-while-readin
I pushed a workaround to make it work until a newer curl version is released in Ubuntu 22, a ntopng update will be available later today

**Comment by atemix** [comment]
@cardigliano Would this workaround available in stable branch?

**Comment by cardigliano** [comment]
Already available, try updating

**Comment by atemix** [comment]
@cardigliano AM works in any direction, thx fo help

**Comment by cardigliano** [comment]
Great, thank you.
