### ISSUE TITLE
ASN details on external RIPE website not working

### ISSUE THREAD

**Issue by Paolo5466** [ntop/ntopng#8435]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04.6
* Architecture: amd64
* ntopng version/revision: 6.1.240603

**What happened**:
External Link to ASN Ripe details not working

**How did you reproduce it?**
Clicking on ASN links to open details
![ASN](https://github.com/ntop/ntopng/assets/53659380/f1fcfa68-69da-4bc1-8443-8f80808d0ee2)
![ripe](https://github.com/ntop/ntopng/assets/53659380/e8c3ec0e-4b10-4dad-9f10-2987957aa98f)

**Comment by MatteoBiscosi** [comment]
Verified as fixed
