### ISSUE TITLE
So it seems this is the error i am getting when ntop crashes.

### ISSUE THREAD

**Issue by awptechnologies** [ntop/ntopng#8438]
So it seems this is the error i am getting when ntop crashes.

[LuaEngine.cpp:610] WARNING: attempt to index a boolean value

This is from ntop log and it happens at the exact same time i get this error in opnsense

<6>pid 5254 (ntopng), jid 0, uid 288: exited on signal 11

_Originally posted by @awptechnologies in https://github.com/ntop/ntopng/issues/8391#issuecomment-2148702217_

**Comment by cardigliano** [comment]
Reopened #8391
