### ISSUE TITLE
geoip fail? 2.5.161205 - Community Edition

### ISSUE THREAD

**Issue by valantislevas** [ntop/ntopng#844]
I have the 2.5.161205 - Community Edition version on my debian server installed from git..
i do make geoip it downloads it but in information of ntopng cant see geoip loading with no failure etc.. 
just like doesnt installed/compiled..

**Comment by emanuele-f** [comment]
Can you post the output of ./configure?

**Comment by valantislevas** [comment]
You are now ready to compile typing make
root@srv:~/ntopng# ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for nDPI... found in ../nDPI
checking for ../nDPI/src/lib/.libs/libndpi.a... found ../nDPI/src/lib/.libs/libndpi.a
checking for ntopng professional edition... not found
checking for pcap_open_live in -lpcap... yes
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking libnetfilter_queue/libnetfilter_queue.h usability... no
checking libnetfilter_queue/libnetfilter_queue.h presence... no
checking for libnetfilter_queue/libnetfilter_queue.h... no
checking for nfq_create_queue in -lnetfilter_queue... no
checking for nfq_set_verdict2... no
checking for ldap_initialize in -lldap... yes
checking for nl_handle_alloc in -lnl... no
checking for clock_gettime in -lrt... yes
checking for zlibVersion in -lz... yes
checking for dlopen in -ldl... yes
checking for curl_easy_perform in -lcurl... yes
checking for GeoIP_record_by_ipnum in -lGeoIP... no
checking GeoIP.h usability... no
checking GeoIP.h presence... no
checking for GeoIP.h... no
Build ntop without geolocation - GeoIP (http://www.maxmind.com/)
checking for sqlite3_open in -lsqlite3... yes
checking for mariadb_config... no
checking for mysql_config... mysql_config
checking for main in -lwrap... no
configure: creating ./config.status
config.status: creating packages/ntopng.spec
config.status: creating packages/ntopng-data.spec
config.status: creating Makefile
config.status: WARNING:  'Makefile.in' seems to ignore the --datarootdir setting
config.status: creating doc/doxygen.conf
config.status: creating include/config.h
config.status: include/config.h is unchanged
You are now ready to compile typing make
root@srv:~/ntopng#

now i see that: Build ntop without geolocation - GeoIP (http://www.maxmind.com/)
how i can ./configure with geoip?

**Comment by valantislevas** [comment]
fixed i compile it again after i install libgeoip-dev thanks
