### ISSUE TITLE
The "Active hosts" graph's Y-axis is strange...

### ISSUE THREAD

**Issue by Yoshihiro-jp** [ntop/ntopng#8445]
**Environment**:
* OS name: [e.g. Ubuntu] ubuntu  
* OS version: [e.g. 18.04] Ubuntu 20.04.6 LTS
* Architecture: [e.g. amd64] x86_64
* ntopng version/revision: [e.g. 5.1.211223] 6.0.240608

**What happened**:
Kindly refer to the attached file.
Y-axis is strange. 
The numbers are duplicated with 1K.

**How did you reproduce it?**
Just open the "Active hosts" graph

**Debug Information**:
![active host bug](https://github.com/ntop/ntopng/assets/58843707/2571a96e-dbce-45c2-8341-a16f6b40a89d)

**Comment by MatteoBiscosi** [comment]
Hi @Yoshihiro-jp , it's not duplicated, it's probably 1.3, 1.6, 1.9k however let me fix so that we can see it

**Comment by MatteoBiscosi** [comment]
Verified as fixed
