### ISSUE TITLE
segmentation fault with libssl.so.8

### ISSUE THREAD

**Issue by ALIREZA-Z** [ntop/ntopng#845]
Hello
When i configure ntopng to use ssl (as explain in document)it is terminated with segmentation fault.
FreeBSD 10.3
ntopng 2.4
ndpi 1.8 
curl 7.51.0
and libssl.so.8

and if i change libssl.so to libssl.so.7 it doesn't have a problem and it work correctly.
It seems there is problem in set_ssl_option method of mongoose.c(the problem is raised when i use libssl.so.8)
any idea?

**Comment by emanuele-f** [comment]
Hi, maybe you have compiled ntopng with old libssl headers (version 7) and you try to link against new (version 8)?

**Comment by ALIREZA-Z** [comment]
hi 
I check the build environment and final system and i find that openssl version is the same.
the method that is used in set_ssl_option in mongoose third-party is deprecated.I think this is the problem?!

**Comment by simonemainardi** [comment]
can you please enclose the backtrace of the crash?

**Comment by ALIREZA-Z** [comment]
Using OpenSSL port version 1.0.2_14
ntopng (2.4 release version) compile with openssl port.
curl compile with openssl port.(Set GSSAPI_None for using openssl port)
====================================================
log when i execute the command#ntopng -W 3001
11/Dec/2016 10:30:09 [Ntop.cpp:1121] Setting local networks to 127.0.0.0/8
11/Dec/2016 10:30:09 [Redis.cpp:92] Successfully connected to redis 127.0.0.1:6379@0
[NDPI] ndpi_init_protocol_defaults(missing protoId=226) INTERNAL ERROR: not all protocols have been initialized
[NDPI] ndpi_init_protocol_defaults(missing protoId=226) INTERNAL ERROR: not all protocols have been initialized
11/Dec/2016 10:30:09 [PcapInterface.cpp:85] Reading packets from interface em0...
11/Dec/2016 10:30:09 [Ntop.cpp:1267] Registered interface em0 [id: 0]
[NDPI] ndpi_init_protocol_defaults(missing protoId=226) INTERNAL ERROR: not all protocols have been initialized
11/Dec/2016 10:30:09 [PcapInterface.cpp:85] Reading packets from interface pflog0...
11/Dec/2016 10:30:09 [Ntop.cpp:1267] Registered interface pflog0 [id: 1]
[NDPI] ndpi_init_protocol_defaults(missing protoId=226) INTERNAL ERROR: not all protocols have been initialized
11/Dec/2016 10:30:09 [PcapInterface.cpp:85] Reading packets from interface pfsync0...
11/Dec/2016 10:30:09 [Ntop.cpp:1267] Registered interface pfsync0 [id: 2]
[NDPI] ndpi_init_protocol_defaults(missing protoId=226) INTERNAL ERROR: not all protocols have been initialized
11/Dec/2016 10:30:09 [PcapInterface.cpp:85] Reading packets from interface enc0...
11/Dec/2016 10:30:09 [Ntop.cpp:1267] Registered interface enc0 [id: 3]
[NDPI] ndpi_init_protocol_defaults(missing protoId=226) INTERNAL ERROR: not all protocols have been initialized
11/Dec/2016 10:30:09 [PcapInterface.cpp:85] Reading packets from interface em1...
11/Dec/2016 10:30:09 [Ntop.cpp:1267] Registered interface em1 [id: 4]
[NDPI] ndpi_init_protocol_defaults(missing protoId=226) INTERNAL ERROR: not all protocols have been initialized
11/Dec/2016 10:30:09 [PcapInterface.cpp:85] Reading packets from interface em2...
11/Dec/2016 10:30:09 [Ntop.cpp:1267] Registered interface em2 [id: 5]
[NDPI] ndpi_init_protocol_defaults(missing protoId=226) INTERNAL ERROR: not all protocols have been initialized
11/Dec/2016 10:30:09 [PcapInterface.cpp:85] Reading packets from interface em3...
11/Dec/2016 10:30:09 [Ntop.cpp:1267] Registered interface em3 [id: 6]
[NDPI] ndpi_init_protocol_defaults(missing protoId=226) INTERNAL ERROR: not all protocols have been initialized
11/Dec/2016 10:30:09 [PcapInterface.cpp:85] Reading packets from interface lo0...
11/Dec/2016 10:30:09 [Ntop.cpp:1267] Registered interface lo0 [id: 7]
11/Dec/2016 10:30:09 [Ntop.cpp:1279] Registered interface view em0 [id: 0]
11/Dec/2016 10:30:09 [Ntop.cpp:1279] Registered interface view pflog0 [id: 1]
11/Dec/2016 10:30:09 [Ntop.cpp:1279] Registered interface view pfsync0 [id: 2]
11/Dec/2016 10:30:09 [Ntop.cpp:1279] Registered interface view enc0 [id: 3]
11/Dec/2016 10:30:09 [Ntop.cpp:1279] Registered interface view em1 [id: 4]
11/Dec/2016 10:30:09 [Ntop.cpp:1279] Registered interface view em2 [id: 5]
11/Dec/2016 10:30:09 [Ntop.cpp:1279] Registered interface view em3 [id: 6]
11/Dec/2016 10:30:09 [Ntop.cpp:1279] Registered interface view lo0 [id: 7]
11/Dec/2016 10:30:09 [main.cpp:255] PID stored in file /var/run/ntopng.pid
11/Dec/2016 10:30:09 [Utils.cpp:341] User changed to nobody
Segmentation fault
=====================================================
this is the ldd result:
`ldd /usr/local/bin/ntopng`
libssl.so.8 => /usr/local/lib/libssl.so.8 (0x30161120000)
=====================================================
after i create a link to libssl.so.7 .ntopng works fine and this is the output:
11/Dec/2016 11:11:05 [Ntop.cpp:1121] Setting local networks to 127.0.0.0/8
11/Dec/2016 11:11:05 [Redis.cpp:92] Successfully connected to redis 127.0.0.1:6379@0
[NDPI] ndpi_init_protocol_defaults(missing protoId=226) INTERNAL ERROR: not all protocols have been initialized
[NDPI] ndpi_init_protocol_defaults(missing protoId=226) INTERNAL ERROR: not all protocols have been initialized
11/Dec/2016 11:11:05 [PcapInterface.cpp:85] Reading packets from interface em0...
11/Dec/2016 11:11:05 [Ntop.cpp:1267] Registered interface em0 [id: 0]
[NDPI] ndpi_init_protocol_defaults(missing protoId=226) INTERNAL ERROR: not all protocols have been initialized
11/Dec/2016 11:11:05 [PcapInterface.cpp:85] Reading packets from interface pflog0...
11/Dec/2016 11:11:05 [Ntop.cpp:1267] Registered interface pflog0 [id: 1]
[NDPI] ndpi_init_protocol_defaults(missing protoId=226) INTERNAL ERROR: not all protocols have been initialized
11/Dec/2016 11:11:05 [PcapInterface.cpp:85] Reading packets from interface pfsync0...
11/Dec/2016 11:11:05 [Ntop.cpp:1267] Registered interface pfsync0 [id: 2]
[NDPI] ndpi_init_protocol_defaults(missing protoId=226) INTERNAL ERROR: not all protocols have been initialized
11/Dec/2016 11:11:05 [PcapInterface.cpp:85] Reading packets from interface em1...
11/Dec/2016 11:11:05 [Ntop.cpp:1267] Registered interface em1 [id: 4]
[NDPI] ndpi_init_protocol_defaults(missing protoId=226) INTERNAL ERROR: not all protocols have been initialized
11/Dec/2016 11:11:05 [PcapInterface.cpp:85] Reading packets from interface em2...
11/Dec/2016 11:11:05 [Ntop.cpp:1267] Registered interface em2 [id: 5]
[NDPI] ndpi_init_protocol_defaults(missing protoId=226) INTERNAL ERROR: not all protocols have been initialized
11/Dec/2016 11:11:05 [PcapInterface.cpp:85] Reading packets from interface em3...
11/Dec/2016 11:11:05 [Ntop.cpp:1267] Registered interface em3 [id: 6]
[NDPI] ndpi_init_protocol_defaults(missing protoId=226) INTERNAL ERROR: not all protocols have been initialized
11/Dec/2016 11:11:05 [PcapInterface.cpp:85] Reading packets from interface lo0...
11/Dec/2016 11:11:05 [Ntop.cpp:1267] Registered interface lo0 [id: 7]
11/Dec/2016 11:11:05 [Ntop.cpp:1279] Registered interface view em0 [id: 0]
11/Dec/2016 11:11:05 [Ntop.cpp:1279] Registered interface view pflog0 [id: 1]
11/Dec/2016 11:11:05 [Ntop.cpp:1279] Registered interface view pfsync0 [id: 2]
11/Dec/2016 11:11:05 [Ntop.cpp:1279] Registered interface view em1 [id: 4]
11/Dec/2016 11:11:05 [Ntop.cpp:1279] Registered interface view em2 [id: 5]
11/Dec/2016 11:11:05 [Ntop.cpp:1279] Registered interface view em3 [id: 6]
11/Dec/2016 11:11:05 [Ntop.cpp:1279] Registered interface view lo0 [id: 7]
11/Dec/2016 11:11:05 [main.cpp:255] PID stored in file /var/run/ntopng.pid
11/Dec/2016 11:11:05 [Utils.cpp:341] User changed to nobody
11/Dec/2016 11:11:05 [HTTPserver.cpp:509] Web server dirs [/usr/local/share/ntopng/httpdocs][/usr/local/share/ntopng/scripts]
11/Dec/2016 11:11:05 [HTTPserver.cpp:512] HTTP server listening on port 3000
11/Dec/2016 11:11:05 [HTTPserver.cpp:515] HTTPS server listening on port 3001
11/Dec/2016 11:11:05 [main.cpp:295] Working directory: /var/tmp/ntopng
11/Dec/2016 11:11:05 [main.cpp:297] Scripts/HTML pages directory: /usr/local/share/ntopng
11/Dec/2016 11:11:05 [Ntop.cpp:271] Welcome to ntopng amd64 v.2.5.161210 - (C) 1998-2016 ntop.org
11/Dec/2016 11:11:05 [PeriodicActivities.cpp:53] Started periodic activities loop...
11/Dec/2016 11:11:05 [RuntimePrefs.cpp:34] Dumping alerts into syslog
11/Dec/2016 11:11:05 [Ntop.cpp:561] Adding fe80::1:1/64 as IPv6 local network for em0
11/Dec/2016 11:11:05 [Ntop.cpp:531] Adding 192.168.26.0/24 as IPv4 local network for em0
11/Dec/2016 11:11:05 [Ntop.cpp:561] Adding fe80::210:f3ff:fe38:41ab/64 as IPv6 local network for em1
11/Dec/2016 11:11:05 [Ntop.cpp:561] Adding fe80::210:f3ff:fe38:41ac/64 as IPv6 local network for em2
11/Dec/2016 11:11:05 [Ntop.cpp:561] Adding fe80::210:f3ff:fe38:41ad/64 as IPv6 local network for em3
11/Dec/2016 11:11:05 [Ntop.cpp:531] Adding 127.0.0.0/8 as IPv4 local network for lo0
11/Dec/2016 11:11:05 [Ntop.cpp:561] Adding ::1/128 as IPv6 local network for lo0
11/Dec/2016 11:11:05 [Ntop.cpp:561] Adding fe80::1/64 as IPv6 local network for lo0
11/Dec/2016 11:11:05 [NetworkInterface.cpp:1536] Started packet polling on interface em0 [id: 0]...
11/Dec/2016 11:11:05 [NetworkInterface.cpp:1536] Started packet polling on interface pflog0 [id: 1]...
11/Dec/2016 11:11:05 [NetworkInterface.cpp:1536] Started packet polling on interface pfsync0 [id: 2]...
11/Dec/2016 11:11:05 [NetworkInterface.cpp:1536] Started packet polling on interface em1 [id: 4]...
11/Dec/2016 11:11:05 [NetworkInterface.cpp:1536] Started packet polling on interface em2 [id: 5]...
11/Dec/2016 11:11:05 [NetworkInterface.cpp:1536] Started packet polling on interface em3 [id: 6]...
11/Dec/2016 11:11:05 [NetworkInterface.cpp:1536] Started packet polling on interface lo0 [id: 7]...

**Comment by simonemainardi** [comment]
nDPI sources are not in sync with ntopng sources. For ntopng 2.4 you need to compile with nDPI 1.8-stable

**Comment by ALIREZA-Z** [comment]
hi simonemainardi  
I think emanuele-f  is true because mongoos uses libssl.so.7 despite WITH_OPENSSL_PORT=yes (in FreeBSD we can use openssl as base or port.)

https://wiki.freebsd.org/OpenSSL/PortsLinkingBase

thanks

**Comment by emanuele-f** [comment]
@ali-reza-zareian  do you have any hint what component should honor the WITH_OPENSSL_PORT preference in FreeBSD?

**Comment by ALIREZA-Z** [comment]
Sorry But i dont understand your question!
_what component should honor the WITH_OPENSSL_PORT preference in FreeBSD?_

**Comment by emanuele-f** [comment]
I'm not a FreeBSD user, but I think the problem of choosing to compile against the "base" version or the "port" version of SSL should be handled by the FreeBSD build system, not by ntopng.

For example, "pkgconfig --cflags" should return the correct version of SSL based on WITH_OPENSSL_PORT preference. Can you verify this?

**Comment by ALIREZA-Z** [comment]
Ok,I get it.Its not ntopng problem.

In FreeBSD we should create a make.conf file in /etc/ with this content:
DEFAULT_VERSIONS+=ssl=openssl 
it says to os that make new ports with openssl ports which is compiled on system.we can use base or libressl instead of openssl.but we have some ports like curl or mongoose that have special details in their make file.
for example:
if curl GSSAPI config is enable it is installed with base whether we use openssl port or not.
mongoose use libssl.so.7 whether we have newer version.
In my envirement i use DEFAULT_VERSIONS+=ssl=openssl  and my libssl version is 8 but mongoose needs libssl.so.7.

thanks .

**Comment by emanuele-f** [comment]
Ok, so you must link against libssl 7 because mongoose version ntopng uses requires it. Thank you for your explaination.
