### ISSUE TITLE
add a new preferences section: asset inventory

### ISSUE THREAD

**Issue by lucaferret** [ntop/ntopng#8451]
Create a new Preference section called Assets Inventory.
The first section of this new preference will be Netbox. The required parameters required for activation are the URL of the running instance of Netbox and the Personal Access Token

**Comment by lucaderi** [comment]
The preferences for asset inventor must be available both from C++ and Lua (Ent L only)

**Comment by MatteoBiscosi** [comment]
Implemented as requested
