### ISSUE TITLE
Enhance Cloud Support

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8456]
- [x] add the ability to re-check the cloud and not to quit as soon as there is a minor connectivity issue
- [x] in case of a cloud license, at startup we need to wait until we're connected to the ntop cloud without jumping immediately in demo mode
- [x] demo mode must be disabled in case of a cloud license
- [x] in case of cloud connectivity issues, trigger an ntopng alert similar to crash alert (lost connectivity)  [cloud lib]
- [x] add an alert when connectivity is restored [add callback to cloud lib]
- [x] add versioning in messages and trigger an alert (or similar) in case of old cloud versions [cloud lib]
- [x] Add current node in the alert in case of reconnection

**Comment by cardigliano** [comment]
Code for triggering the alerts in items 4 and 5:

`
if (ntop->getSystemInterface() && ntop->getSystemInterface()->getAlertsQueue())
  ntop->getSystemInterface()->getAlertsQueue()->pushCloudDisconnectionAlert();
  
if (ntop->getSystemInterface() && ntop->getSystemInterface()->getAlertsQueue())
  ntop->getSystemInterface()->getAlertsQueue()->pushCloudReconnectionAlert();
`

**Comment by cardigliano** [comment]
Enclosing screenshot of the alerts:
<img width="1305" alt="Screenshot 2024-07-02 at 11 12 29" src="https://github.com/ntop/ntopng/assets/7548711/ff8d32cd-5299-4cc6-95d8-3a841fb9d052">

**Comment by cardigliano** [comment]
Add current node in case of reconnection

**Comment by cardigliano** [comment]
Added broker host on disconnection and reconnection alerts
<img width="966" alt="Screenshot 2024-07-04 at 18 45 24" src="https://github.com/ntop/ntopng/assets/7548711/b5d47f1d-cad6-4fe1-b669-e8620e62baa0">
