### ISSUE TITLE
The disk-limit of n2disk would be changed automatically when using it with ntopng

### ISSUE THREAD

**Issue by Yoshihiro-jp** [ntop/ntopng#8459]
**Environment**:
* OS name: Ubuntu 
* OS version: 20.04.6 LTS
* Architecture: x86_64
* ntopng version/revision: 6.0.240613

**What happened**:
When I change the "Max Disk Space" in "Traffic Recording Settings" of the ntopng.
The value would not be changed with what I changed...

For example if I set 100GB it would be change 263GB.....

**How did you reproduce it?**
Just change the  "Max Disk Space" in "Traffic Recording Settings" of the ntopng.

**Debug Information**:
![n2diskbug](https://github.com/ntop/ntopng/assets/58843707/37242cb1-7bce-477f-8e5c-3a884e94bf6a)

**Comment by cardigliano** [comment]
Fixed in 1719c39cf, a new update will be available later today
