### ISSUE TITLE
Report the Check Interface in User's Guide

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8463]
In the User's Guide (for instance https://www.ntop.org/guides/ntopng/alerts/host_checks.html) it is not shown what checks apply to what interface type as in the ntopng GUI

<img width="1213" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/55739db3-8624-4a7a-a69a-d382252817d2">

This ticket is to request to update the user's guide reporting to what interface family a specific check applies and report what is the meaning of icons

**Comment by lucaderi** [comment]
Invalid formatting (bold): please fix it

<img width="421" alt="image" src="https://github.com/user-attachments/assets/8cd86a5b-d0ea-4f02-b22b-3489fec15255">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
