### ISSUE TITLE
Network discovery not working. Warning

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#8464]
When executing network discovery a warning appears in console every 5 seconds and discovery jumps between 0% and 10% every 5 seconds.

21/Jun/2024 11:16:19 [LuaEngine.cpp:702] WARNING: /home/data/lavoro/ntopng/scripts/lua/modules/xmlSimple.lua:90: XmlParser: trying to close eventSubURL with service [/home/data/lavoro/ntopng/scripts/callbacks/5second/system/network_discovery.lua]

PAGE: /lua/discover.lua

![Screenshot 2024-06-21 at 11 18 26](https://github.com/ntop/ntopng/assets/33870399/29f7c545-6976-4b9a-93c0-4d9cfe2df560)
![Screenshot 2024-06-21 at 11 19 07](https://github.com/ntop/ntopng/assets/33870399/4eb0ebe5-f242-4638-9f7d-b0b5e0b4e7f9)

**Comment by MatteoBiscosi** [comment]
Verified as fixed
