### ISSUE TITLE
Missing Country Name from Filtered Flows Page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8469]
When filtering for a country (see below) the country name must be shown somewhere in the navbar

http://host:3000/lua/hosts_stats.lua?country=LT&version=&network=&traffic_type=&mode=&pool=&deviceIP=

**Comment by DGabri** [comment]
Implemented as requested. When redirected to hosts_stats page a new dropdown filter appears above the table

**Comment by DGabri** [comment]
Completed
