### ISSUE TITLE
attempt to concatenate a nil value

### ISSUE THREAD

**Issue by flapegue** [ntop/ntopng#847]
in ntopng > ntopng Runtime Status, i have this error

`07/Dec/2016 00:50:47 [Lua.cpp:5997] WARNING: Script failure [/usr/share/ntopng/scripts/lua/flow_stats.lua][/usr/share/ntopng/scripts/lua/flow_stats.lua:455: attempt to concatenate a nil value]`

what is the problem ?

**Comment by emanuele-f** [comment]
Which version of ntopng are you using?

**Comment by flapegue** [comment]
It has been repaired the last two days with last update
Thanks
