### ISSUE TITLE
Raspberry PI 5 latest update

### ISSUE THREAD

**Issue by stonejlhu** [ntop/ntopng#8474]
**Environment**:
* OS name: [e.g. Ubuntu] - Raspbian
* OS version: [e.g. 18.04] - 12.5 
* Architecture: [e.g. amd64] amd64
* ntopng version/revision: [e.g. 5.1.211223] - 6.1.240512

**What happened**:
Installed and was running fine.  Raspbian downloaded update for ntopng-data and then needed a reboot.  Rebooted and ntopng cannot be started anymore.  If I try to reinstall I get : 
sudo apt-get install ntopng nprobe
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nprobe is already the newest version (10.5.240623-8332).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ntopng : Depends: ntopng-data (= 6.1.240623) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Debug Information**:
systemctl status ntopng - 
Unit ntopng.service could not be found.

**Comment by lucaderi** [comment]
Fixed. New packages will be available in < 2h from now. If not working yet after the update, please reopen this ticket.
