### ISSUE TITLE
Invalid Check on NetBox URL

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8476]
<img width="1083" alt="Screenshot 2024-06-25 at 18 11 04" src="https://github.com/ntop/ntopng/assets/4493366/2aafe4a5-4f3a-4060-88c4-cd04a4c4d6f7">

[LINT] validateParameter failed for parameter [netbox_default_site][function]
 string Lucas Site

[LINT] validateParameter failed for parameter [netbox_default_site][function]
 string Lucas

**Comment by DGabri** [comment]
Completed
