### ISSUE TITLE
Space problem

### ISSUE THREAD

**Issue by infinitynet2011** [ntop/ntopng#8481]
Hello,

Please check:

![image](https://github.com/ntop/ntopng/assets/42605037/5400146d-147b-4deb-a89f-4162e4a05f38)

[root@ntopng ~]# df -h
Filesystem Size Used Avail Use% Mounted on
devtmpfs 4.0M 0 4.0M 0% /dev
tmpfs 63G 0 63G 0% /dev/shm
tmpfs 26G 95M 25G 1% /run
/dev/mapper/almalinux-root 70G 70G 223M **100%** /
/dev/sda2 958M 314M 645M 33% /boot
/dev/mapper/almalinux-home 3.5T 26G 3.4T **1%** /home
tmpfs 13G 0 13G 0% /run/user/0
tmpfs 13G 0 13G 0% /run/user/1001
[root@ntopng ~]#

[root@ntopng ~]# hostnamectl
Static hostname: ntopng
Icon name: computer
Operating System: AlmaLinux 9.4 (Seafoam Ocelot)
CPE OS Name: cpe:/o:almalinux:almalinux:9::baseos
Kernel: Linux 5.14.0-427.20.1.el9_4.x86_64
Architecture: x86-64
Hardware Vendor: HP
Hardware Model: ProLiant DL360p Gen8
Firmware Version: P71
[root@ntopng ~]#

I can't use ntopng anymore because there is not enough space.

Thanks,
Gabriel

**Comment by lucaderi** [comment]
Can you please check who's using the disk? I suggest you to do this https://github.com/ntop/ntopng/blob/dev/doc/README.clickhouse.md

**Comment by infinitynet2011** [comment]
Hello Luca,

I have **3TB** free. 

I set the path in ntopng.conf to use my 3TB free partition (please check the print screen in the first post).

I don`t see why and how Clickhouse is relevant to my problem.

I have enough space, but ntopng refuses to use it.

How I can fix this?   


Thank you,
Gabriel

**Comment by lucaderi** [comment]
ntopng saves data under /var/lib/ntopng. Please check if this is the problem (I doubt it), and if so you can change the path to 
[--data-dir|-d] <path>              | Data directory (must be writable).
                                    | Default: /var/lib/ntopng

**Comment by infinitynet2011** [comment]
Hello Luca!

Storage Utilization:    Volume: /home/ntopng (/dev/mapper/almalinux-home)
System (25.18 GB)
Available (3.39 TB)  -  Total: 3.42 TB

All the information I provided in the first post via a print screen.

About ntopng.conf have obliviously -d=/home/ntopng

My only problem is ntopng saving data into the old partition.

df -h
/dev/mapper/almalinux-root 70G 70G 223M 100% /
/dev/mapper/almalinux-home 3.5T 26G 3.4T 1% /home

I can`t use ntopng because of the lack of space.

[root@ntopng ntopng]# pwd
/home/ntopng

[root@ntopng ntopng]# ls -lZa
total 32
drwx------.  6 ntopng ntop system_u:object_r:var_lib_t:s0      96 Jun 23 23:00 -1
drwxrwxrwx. 21 ntopng ntop system_u:object_r:var_lib_t:s0    4096 Jun 29 03:24 .
drwxr-xr-x.  6 root   root system_u:object_r:home_root_t:s0    60 Jun 23 00:01 ..
-rwx------.  1 ntopng ntop system_u:object_r:var_lib_t:s0       0 Jun 20 01:39 .lock
drwx------.  3 ntopng ntop system_u:object_r:var_lib_t:s0      25 Jun 20 01:40 0
drwx------.  6 ntopng ntop system_u:object_r:var_lib_t:s0      89 Jun 20 01:41 1
drwx------.  3 ntopng ntop system_u:object_r:var_lib_t:s0      33 Jun 22 15:07 10
drwx------.  3 ntopng ntop system_u:object_r:var_lib_t:s0      33 Jun 22 15:24 11
drwx------.  3 ntopng ntop system_u:object_r:var_lib_t:s0      25 Jun 24 01:23 12
drwx------.  3 ntopng ntop system_u:object_r:var_lib_t:s0      25 Jun 24 01:23 13
drwx------.  5 ntopng ntop system_u:object_r:var_lib_t:s0      66 Jun 20 01:40 2
drwx------.  6 ntopng ntop system_u:object_r:var_lib_t:s0      89 Jun 20 01:41 3
drwx------.  6 ntopng ntop system_u:object_r:var_lib_t:s0      89 Jun 20 01:41 4
drwx------.  6 ntopng ntop system_u:object_r:var_lib_t:s0      89 Jun 20 01:41 5
drwx------.  3 ntopng ntop system_u:object_r:var_lib_t:s0      25 Jun 20 02:35 6
drwx------.  3 ntopng ntop system_u:object_r:var_lib_t:s0      25 Jun 20 02:35 7
drwx------.  3 ntopng ntop system_u:object_r:var_lib_t:s0      25 Jun 21 04:18 9
drwx------.  2 ntopng ntop system_u:object_r:var_lib_t:s0    4096 Jun 29 03:24 category_lists
drwx------.  2 ntopng ntop system_u:object_r:var_lib_t:s0     180 Jun 27 00:00 configurations
drwx------.  2 ntopng ntop system_u:object_r:var_lib_t:s0   16384 Jun 26 15:38 cve
drwx------. 15 ntopng ntop system_u:object_r:var_lib_t:s0    4096 Jun 20 01:40 scripts
drwx------.  4 ntopng ntop system_u:object_r:var_lib_t:s0      40 Jun 20 02:35 tmp
[root@ntopng ntopng]# 

*SELinux is in permissive mode


Thank you!
Gabriel

**Comment by infinitynet2011** [comment]
Update and resolve!

The problem was from clickhouse, the working directory remained on the old partition.
After I moved to /home/clickhouse, everything was back to normal!

Thanks again!
Gabriel
