### ISSUE TITLE
GeoMap Broken

### ISSUE THREAD

**Issue by djstarfox** [ntop/ntopng#8486]
**Environment**:
* OS name: Debian GNU/Linux 11 
* OS version: (bullseye)
* Architecture:  [aarch64]
* ntopng version/revision:  [ntopng Professional (Embedded) v.6.1.240628

**What happened**: 
GeoMap data is displayed, but the background map is not displayed.  Instead, it is showing HTTP ERROR 401.  See attached screenshot.

**How did you reproduce it?**
Browse to any interface --> maps --> GeoMap

**Debug Information**:
There are no relevant entries in the ntopng.log file.
![Screenshot from 2024-07-02 10-12-58](https://github.com/ntop/ntopng/assets/32071372/4f90da05-d441-488d-a66e-b44903ba59b0)

Note:  This issue did not exist in the prior version of ntopng.

**Comment by DGabri** [comment]
Hello there, thanks for the heads up, the problem is the provider of the map rendering template, I will change this to another style that does not require authentication. The providers changed the usage of the template in openstreetmap without us noticing, thank you!
I will fix this

**Comment by MatteoBiscosi** [comment]
Hi @djstarfox sorry for the trouble, in a couple of hours a new version with the fix should be available

**Comment by lucaderi** [comment]
The map is now empty
<img width="1490" alt="Screenshot 2024-07-08 at 09 28 35" src="https://github.com/ntop/ntopng/assets/4493366/c4e690e3-db53-4a33-9681-6e07db5c79dd">

**Comment by djstarfox** [comment]
@DGabri  In which software release version is this fixed?  I have not seen a release since 28th of June. 
If you'd like me to test, please provide the software patch/script.

**Comment by DGabri** [comment]
This is on the dev branch of this github repository, please git clone, make and run with sudo ./ntopng -i interface name --dont-change-user to test this
