### ISSUE TITLE
Data downfalls every 5 mins in ElasticSearch

### ISSUE THREAD

**Issue by dtrizna** [ntop/ntopng#849]
Hi, ntopng community!

Probably, this is not as much issue, as question related to communication between ntopng and ElasticSearch.

When I observe Netflow information in Kibana, there's behaviour like this:
![image](https://cloud.githubusercontent.com/assets/15322061/21002671/97a181de-bd2f-11e6-9661-2efc36d754c6.png)

Every 5 mins there's downfall in data, that is ~1 min long. 
This is kinda weird, traffic on the network sensor is continuous and Netflow data itself is sent to nprobe without such periods of silence.

For now my troubleshooting lead me to observing localhost traffic between ElasticSearch and ntopng, and it looks like, that in about a minute ntopng doesn't sent data to ES (here's Wireshark IO graph that described packets/s to port 9200 on loopback):
![image](https://cloud.githubusercontent.com/assets/15322061/21005895/5ddd5bfc-bd3f-11e6-9ac4-d55d5916eb41.png)

Is it normal behaviour for ntopng to make such breaks and sent data in portions?

Or it indeed may be related to data loss? 
There's too much data and I can't detect exact flows that may be lost, but I think it still can be real scenario. 
Additionally, I think it even may not be related to ntopng or ES configuration, but linux TCP/IP stack itself? Previously I've manipulations advised within this thread: https://github.com/ntop/ntopng/issues/823

May be someone has any ideas to find out what exactly causing this?

**Comment by simonemainardi** [comment]
there is a dropped elastic search flows counters in the ntopng interface page. Can you please check that? It that counter greater than zero? Does that counter increases periodically?

**Comment by dtrizna** [comment]
I didn't found value called "Dropped [ElasticSearch] flows", but possibly you mention that counter named "Dropped Packets" next to "Received Traffic" value?
It is equal with zero. This is correct place to look?
![image](https://cloud.githubusercontent.com/assets/15322061/21081117/b3afe280-bfc8-11e6-9718-b1023d987789.png)

Paralelly, I've captured raw Netflow data on network interface for ~5 mins.
Within that capture looked for flows, that was received during the silence interval and compared them with Kibana to understand, was something lost or not!?
As a result I indeed didn't found any flow, that was in capture and wasn't in Kibana.

For example speaking about one exact source IP - in capture there was Netflow 10 packets, and in Kibana only 3 records.
But..
Every Netflow flow record says, that flow contains 3-9 packets, while in Kibana every record describes ~20 packets. 
Netflow:
![image](https://cloud.githubusercontent.com/assets/15322061/21081253/354f8b7c-bfcb-11e6-9e84-d408f2d1bc07.png)
Kibana:
![image](https://cloud.githubusercontent.com/assets/15322061/21081255/3c6a142c-bfcb-11e6-8111-1ce6d0b41025.png)

When calculating 4 first Netflow flow packet's, it exactly fits with first Kibana's record packets count (6+3+8+4=21), next 3 flows fits 2nd Kibana record (9+9+5=24) and the same picutre with least (6+5+3=14). 

So I think, that ntopng summarizes Netflow flows and only then sends them to ES.
And that silence minute is due to ntopng behaviour.
Hopefully I didn't confused you even more.
What do you think, can be this a real scenario?

P.S.
Within the Kibana reconrds there's fields called FIRST_SWITCHED and LAST_SWITCHED:
![image](https://cloud.githubusercontent.com/assets/15322061/21081223/9700fc3a-bfca-11e6-8c0a-403c6a9a2ded.png)
![image](https://cloud.githubusercontent.com/assets/15322061/21081230/a2c79434-bfca-11e6-8edc-64b4e7438824.png)
It looks like it describes some interval in seconds (average 90-100), and all Netflow records within that interval are accumulated to that single ES record.

**Comment by dtrizna** [comment]
In fact there indeed was problem with indexation, that appeared like mentioned data downfalls once in five minutes. I think it is worth to tell about solution within this thread.

In the end it looks like, that problem was due to highly loaded JVM heap.
It is possible to see it consumption with any cluster monitoring tool or simply with cat nodes API: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html
F.e. following query displays the percentage of it usage: GET _cat/nodes?v&h=id,hp
If it's higher that 90%, probably my configuration will help.

My ElasticSearch node has total 32 Gigs of RAM, and there is important leave as many as possible free space for buff/cache operations. Knowing that ntopng itself takes 6-10 GB of RAM, I dedicated for ES JVM 10-12 GB with indices.memory.index_buffer_size=30%. 

First mistake was increasing the percentage for buffer size and number of active shards. Many ES roadmaps advice to increase default values of them, but in fact it better even to decrease the number of shards. It is correctly even to dedicate a few tens of gigs for single shard. And with less shards there's no need with high index buffer size (max is 512 MBs for single active shard, due to ES documentation additional increase won't give any real benefit).

I have ~60-70 GB of data per day. During whole operations I found more useful to tell ntop create index every hour (easier to test new changes or reindex already collected data), so there's ~3 GB data per index. Despite even single shard would be Ok, I've dedicated 2 shards per index. As a result the standard 10% is more than Ok.
Speaking about JVM heap size. I set it to 16 GB, because with smaller values there still appears data mediations. Now I have ~8-10 GB for buff/cache operations, that affects as ~10-15% iowait in CPU, but it's not critical and looks like it is enough for indexation such amount of data.

Glad if this would help someone. :)

**Comment by simonemainardi** [comment]
Thanks for reporting your experience. 

As you are on a single node, did you try with just one shard? I am curious to see how the system behaves with just one shard.

**Comment by dtrizna** [comment]
Yeah, I've tried such config also, but for short period of time, and I've seen that total amount of logs decreased for ~10%. But.. For now I think that this wasn't related actually with shard configuration.

While reading related topics in web I've understood - with indices, that size is lower than 30 GB, it's good practice to have 1 shard per index per node. 
So I'm planning to migrate to 1 shard per index. I'll test the performance and will write back here the results.

Although... this still will be too many with hourly indices - 24 shards per day. With default limit of querying 1000 shards (limit, that is undesirable to increase), timelion and Dasboards longer than 20 days are unavailable.

I still don't want to return for daily indices. 
Simone, may there's a way to tell ntopng create an index every 4-6 hours?
