### ISSUE TITLE
remote2local.rrd and local2remote.rrd are missing in /var/tmp/ntopng/1/rrd/localstats/

### ISSUE THREAD

**Issue by JuergenWeber** [ntop/ntopng#85]
What can be the reason that remote2local.rrd and local2remote.rrd are not being created by minute.lua?

**Comment by JuergenWeber** [comment]
After investing some time for investigation it turned out that the following kind of errors prevented the creation of local2remote/remote2local.rrd files. The manual creation of the missing directories solved the problem. One question remains: What is the source of these kind of errors?
 ntopng: [src/Lua.cpp:4477] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:884: creating '/var/tmp/ntopng/1/rrd/10/187/127/71/HP-SAN/iQ.rrd': No such file or directory]

**Comment by JuergenWeber** [comment]
Ok, reason for this was an error in the "/etc/ntopng/protos.txt" file which caused the "graph_utils.lua" to fail at line 884. Maybe it's a good idea to catch such kind of errors to prevent other parts of the ntopng from aborting.

**Comment by lucaderi** [comment]
See https://github.com/ntop/nDPI/commit/73358d5ec2f877ca30ac0b20c12530d1f338ca5b
