### ISSUE TITLE
Dashboard graphs displaying incorrectly

### ISSUE THREAD

**Issue by njcwotx** [ntop/ntopng#850]
I just noticed my dashboard screen shows my traffic at Kbits/s.

On the left side, my top talkers are showing correctly in Mbits but the graphs are reporting in Kbits and appear undifferentiated.  I updated it a couple of weeks ago, Ill check repo to see if there is another update to try
	2.5.161123 - Pro Small Business Edition
![ntopng dashboard issue](https://cloud.githubusercontent.com/assets/22085357/21026073/ab30e872-bd50-11e6-96ca-7acd73b9da31.GIF)

I have 2 installs at different locations and my dashboard at the other site shows correct and colorful.  It is however an older version.
	2.4.160818 - Pro Small Business Edition
![ntopng dashboard no issue](https://cloud.githubusercontent.com/assets/22085357/21026160/0cee7d54-bd51-11e6-9b1a-3373ffa14188.GIF)

**Comment by simonemainardi** [comment]
can you please report the configurations used by both ntopngs? It looks like the first one is not able to properly do DPI on the traffic as it shows everything as unknown.

**Comment by njcwotx** [comment]
A bit confused, are you asking for the confguration file during compiling?

I used RPMs from nmon.net/centos-stable and did not compile them directly.  I can try to dig up something if you can give me some more hints.  Thanks.

**Comment by njcwotx** [comment]
FYI, after my last post, I went in and checked the repository, there was a slightly newer version available for ntopng and pfring.  I had update a couple weeks ago and those were the only two newer packages inside the dependency set, so I ran an update.  the real-time graphs are now working.  I will let it go a few hours and re-check to see if the last-day graphs improve.

**Comment by njcwotx** [comment]
the graphs are working again, doing the update of the packages to the latest version did the trick.  Had a little scare, the moving interface graphs at the bottom of the pages stopped working, but a clearing of the browser cache fixed it.  Thanks.

**Comment by simonemainardi** [comment]
thanks for reporting
