### ISSUE TITLE
Push alerts to the CheckMK Event Console

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#8501]
CheckMK can ingest alerts via an Event Console listening on port 514 for syslog messages, via UDP or TCP.
It is requested to extend the syslog endpoint to support a new "checkmk" type for exported messages.

References to the documentation:
https://docs.checkmk.com/latest/en/ec.html#setup
https://docs.checkmk.com/latest/en/ec.html#eventsimulator

**Comment by lucaferret** [comment]
Implemented with commit #8521
