### ISSUE TITLE
SSH Signature copy to historical flows

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#8505]
**What would you like to add or change?**:
The SSH Signature is an important information when searching for malicious traffic.
It therefore would be helpful, if the information is available in the historical flows.
Thank you

**Why do you and others need this?**:

**Comment by martinscheu** [comment]
The server SSH signature is available under Info. If therefore you could please add the client signature as well?

**Comment by lucaderi** [comment]
the DB schema already contains the requested information
{"proto": {"ssh": {"client_signature":"SSH-2.0-OpenSSH_9.6p1 Ubuntu-3ubuntu13.5","server_signature":""...

so it just needs to be rendered

**Comment by MatteoBiscosi** [comment]
The SSH info is correctly displayed too. Closing the issue, in case it is needed please reopen this issue or open a new one
![image](https://github.com/user-attachments/assets/7c3a5380-0eb8-4283-bdc4-6c51a76cb2d6)
