### ISSUE TITLE
Extend Manage Data Page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8508]
In "Manage Data" (under Setting) page
- modify the tab label Export -> Export Host Data
- modify the tab label Delete -> Purge Host Data. In the page change "Insert Host IP or Mac Address or /24" and "Insert VLAN" with the word "Specify"
- In case asset inventory is enabled, add a new tab named "Purge Assed Inventory Cache" with only one button that requires a REST API that purges the Asset Inventory Cache

**Comment by DGabri** [comment]
REST to be implemented when needed

**Comment by lucaderi** [comment]
Verified as fixed
