### ISSUE TITLE
ntopng unable to reconnect to the database when MySQL is restarted

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#851]
root@pc-deri:/home/deri# tail /tmp/ntopng.log 
09/Dec/2016 15:16:51 [MySQLDB.cpp:595] Attempting to connect to MySQL for interface tcp://0.0.0.0:1234c...
09/Dec/2016 15:16:51 [MySQLDB.cpp:595] Attempting to connect to MySQL for interface eth0...
09/Dec/2016 15:16:51 [MySQLDB.cpp:624] ERROR: Failed to connect to MySQL: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) [localhost:root]
09/Dec/2016 15:16:51 [MySQLDB.cpp:624] ERROR: Failed to connect to MySQL: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) [localhost:root]
09/Dec/2016 15:16:52 [MySQLDB.cpp:595] Attempting to connect to MySQL for interface tcp://192.12.192.104:1234...
09/Dec/2016 15:16:52 [MySQLDB.cpp:624] ERROR: Failed to connect to MySQL: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) [localhost:root]
09/Dec/2016 15:16:52 [MySQLDB.cpp:55] ERROR: MySQL error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) [rc=-2]
09/Dec/2016 15:16:52 [MySQLDB.cpp:56] ERROR: INSERT INTO `flowsv4` (VLAN_ID,L7_PROTO,IP_SRC_ADDR,L4_SRC_PORT,IP_DST_ADDR,L4_DST_PORT,PROTOCOL,IN_BYTES,OUT_BYTES,PACKETS,FIRST_SWITCHED,LAST_SWITCHED,INFO,JSON,NTOPNG_INSTANCE_NAME,INTERFACE_ID,PROFILE) VALUES ......
09/Dec/2016 15:16:52 [MySQLDB.cpp:595] Attempting to connect to MySQL for interface tcp://192.12.192.104:1234...
09/Dec/2016 15:16:52 [MySQLDB.cpp:624] ERROR: Failed to connect to MySQL: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) [localhost:root]

**Comment by simonemainardi** [comment]
can you please try and `telnet 127.0.0.1 3306` to see if you get a connection refused error thanks

**Comment by lucaderi** [comment]
The connection is not refused. If you restart ntopng everything will work again.

**Comment by amirul123akmal** [comment]
@simonemainardi i got Connection refused..what shall i do?

**Comment by simonemainardi** [comment]
report the log please
