### ISSUE TITLE
Implement Probes Page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8510]
<img width="377" alt="Screenshot 2024-07-10 at 06 27 19" src="https://github.com/ntop/ntopng/assets/4493366/bf6ec766-03c8-4c90-aca3-a38c35d230c8">
Under the Flow Exporters menu entry add a new page that reports on a single table the following information related to probes (nProbe and nProbe Cento) that is currently in the interface stats page
<img width="1316" alt="Screenshot 2024-07-10 at 06 30 17" src="https://github.com/ntop/ntopng/assets/4493366/dead893a-4f90-4d5a-98fb-5a806ee2b9b2">

- probe UUID (unique nProbe/Prrobe Cento identifier and NOT unique flow exported identifier)
- IP Address (host IP where the probe is active)
- Charts Icon for accessing probe timeseries
- Number of flow exporters (sFlow and NetFlow) sending flows to the identified nProbe. This must be a hyperlink that clicking on it jumps to the existing IPFIX and sFlow pages displaying stats of the exporters sending data to such nProbe
- Exported ZMQ Messages
- Dropped ZMQ Messages
- Software version
- Software edition
- Maintenance information

Done this the Interface stats page must be reduced as follows
<img width="1240" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/55ac2eef-cbd1-4f77-b1e2-e45bc781dd5d">

**Comment by MatteoBiscosi** [comment]
Implemented as requested
