### ISSUE TITLE
HTTP user agent Info missing in Historical Flow Details

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#8515]
**Environment**:
[ntopng Enterprise XL v.6.1.240710 (Ubuntu 22.04.4 LTS) ]

**What happened**:
The User Agent field in Historical Flow Details is empty:

<img width="1453" alt="Screenshot 2024-07-11 at 00 01 28" src="https://github.com/ntop/ntopng/assets/38549755/116e747d-b0a7-46d8-9c0c-5e30aa0a529d">

Note tha there is a 100 risk score for HTTP Suspicious User-Agent.

**How did you reproduce it?**

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
The issue seems fixed
![image](https://github.com/user-attachments/assets/4c9412b8-96b7-48e7-90c7-656a1e914633)
![image](https://github.com/user-attachments/assets/51752ead-8599-40c9-ba7c-5965566f2035)
