### ISSUE TITLE
Improve Flow Issues

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8519]
<img width="1595" alt="Screenshot 2024-07-15 at 16 33 20" src="https://github.com/user-attachments/assets/0fa8763a-1ced-4e9f-b92f-0c7ec4d8473f">

In flow_details.lua:
1. Add issue family (cybersec/network)
2. Add issue source (nDPi/ntopng)
3. Rework the table adding (if possible) a score issue without putting the score in brackets [...]
4. For ntopng issues, sometimes the label is duplicated. Example DNS Data Exfiltration

**Comment by DGabri** [comment]
Fixed: 

<img width="2421" alt="Screenshot 2024-08-05 at 10 26 28 AM" src="https://github.com/user-attachments/assets/afac7ab5-51e6-405a-b0ec-a0d581f2ec75">
