### ISSUE TITLE
Counter overflow

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#8523]
There is a counter overflow on the Hsol instance.
<img width="811" alt="Screenshot 2024-07-17 at 10 52 16 AM" src="https://github.com/user-attachments/assets/2d902310-a431-43b4-a01e-dfe437243dd4">

**Comment by lucaderi** [comment]
<img width="1392" alt="Screenshot 2024-08-01 at 16 47 36" src="https://github.com/user-attachments/assets/ccb1d371-748c-4343-8610-b5df2fa83b02">

**Comment by cardigliano** [comment]
Tentative fix c2cc635bf137fbce89927b35f85baa31c6069854

**Comment by cardigliano** [comment]
Tentative fix c262a4a38e0639ad3f2926523f01a4f10f622d01

**Comment by MatteoBiscosi** [comment]
the issue seems fixed 
![image](https://github.com/user-attachments/assets/aae29e11-b9fe-41bb-a229-eeb6dba22519)
