### ISSUE TITLE
After update restart ntopng gets stopped and restarted

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#8524]
ntopng gets stopped and restarted seconds after the update successful restart as it can be seen from the alerts attached

<img width="1181" alt="Screenshot 2024-07-17 at 11 01 58 AM" src="https://github.com/user-attachments/assets/4c20e138-4ba5-49d6-ac83-968cedf2f3be">

**Comment by cardigliano** [comment]
Are you still able to reproduce this? It seems it does not happen in my machine

<img width="1113" alt="Screenshot 2024-07-22 at 18 58 14" src="https://github.com/user-attachments/assets/2aa7d5db-7069-40e6-9fb8-6d4ac2483115">

**Comment by DGabri** [comment]
It seems fixed now
