### ISSUE TITLE
Snapshot problem

### ISSUE THREAD

**Issue by xkrizp09** [ntop/ntopng#8526]
**Environment**:
* OS name: Debian
* OS version: 12
* Architecture: amd64
* ntopng version/revision: ntopng Enterprise L v.6.1.240716

After I made filter I wanted to make snapshot from it. Clicked "add snapshot", then windows closes, but when i opened snapshots again, I can't click on "manage snaphots". Am I doing something wrong?

I asked for advice on discord without reply even if I am not alone with this problem...

![image](https://github.com/user-attachments/assets/a267f782-e392-4b52-8fc2-6ed1883bd3c0)

**Comment by cardigliano** [comment]
Fix available with the next nightly build
