### ISSUE TITLE
Remove/MAP Non-TCP/UDP/ICMP redundant information 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8530]
<img width="499" alt="image" src="https://github.com/user-attachments/assets/7733bfcf-8c11-4793-b062-0c74ae05f08a">

**Comment by lucaderi** [comment]
You can use this pcap to reproduce the issue
[sctp.pcap.zip](https://github.com/user-attachments/files/16675799/sctp.pcap.zip)

**Comment by DGabri** [comment]
Verified as fixed

<img width="167" alt="Screenshot 2024-08-23 at 10 09 47 AM" src="https://github.com/user-attachments/assets/245f452b-bf2d-4b0d-bbf4-abf77883dc00">

<img width="341" alt="Screenshot 2024-08-23 at 10 10 12 AM" src="https://github.com/user-attachments/assets/f02cbff4-162b-4b22-aeff-e8768488b75f">
