### ISSUE TITLE
Alert Minor Issues meaning

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#8537]
What are minor issues? 
Eventually if periodicity of the flow can be displayed it would be useful

<img width="1524" alt="Screenshot 2024-07-20 at 4 58 54 PM" src="https://github.com/user-attachments/assets/f66678f4-b2d8-4094-8a3b-efede19ae49a">

**Comment by MatteoBiscosi** [comment]
Displayed as requested now.
![image](https://github.com/user-attachments/assets/d49d7e1b-9c84-46c6-8594-f89f1685425a)
