### ISSUE TITLE
Rename Menu Name

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8538]
<img width="646" alt="Screenshot 2024-07-21 at 07 50 09" src="https://github.com/user-attachments/assets/bcb47f8d-7adc-4c64-af47-b9e426352a8f">

This will become:
Exporters: 192.168.67.247(nProbe) / 192.168.67.247(Exporter)

**Comment by DGabri** [comment]
Completed: 
<img width="605" alt="Screenshot 2024-07-22 at 9 24 32 AM" src="https://github.com/user-attachments/assets/bc1703c1-b919-4d9e-8513-778758685e16">

**Comment by DGabri** [comment]
Fixed
