### ISSUE TITLE
Invalid Exporter Interfaces

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8540]
<img width="977" alt="Screenshot 2024-07-21 at 07 52 54" src="https://github.com/user-attachments/assets/0777b1d4-2edb-4393-a2e9-ed10c84b8e64">

This exporter has only interface 0 with traffic in and out. The page reports two interfaces with unidirectional traffic

Clicking on an interface we have this error

<img width="932" alt="Screenshot 2024-07-21 at 07 53 59" src="https://github.com/user-attachments/assets/46a06def-1f82-4cc1-bf4c-85d9f0780f02">

This issue depends on #8539

**Comment by DGabri** [comment]
Fixed
