### ISSUE TITLE
Missing URL on nProbe IP

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8541]
<img width="1407" alt="Screenshot 2024-07-21 at 07 54 48" src="https://github.com/user-attachments/assets/8fede012-262c-4102-825a-8d24b4424828">

**Comment by DGabri** [comment]
On my side it is like this, maybe dist must be built? @MatteoBiscosi 

<img width="318" alt="Screenshot 2024-07-22 at 9 35 43 AM" src="https://github.com/user-attachments/assets/aadc2a61-cfe0-4815-87df-05ac31356260">
