### ISSUE TITLE
Local traffic Rules Broken: Missing Interface List and *

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8543]
Contrary to Hosts, in the Interface tag
- * (all interfaces) is no accepted
- No interface is listed
<img width="791" alt="Screenshot 2024-07-22 at 09 31 59" src="https://github.com/user-attachments/assets/8cf0599c-a089-443d-a902-ece0913de448">

**Comment by DGabri** [comment]
Fixed
