### ISSUE TITLE
Historical flow analysis charts not displayed for hourly aggregated flows

### ISSUE THREAD

**Issue by philipp-petermann** [ntop/ntopng#8544]
**Environment**:
* OS name: Ubuntu
* OS version: 22.04.4
* Architecture: amd64
* ntopng version/revision: 6.0.240613

**What happened**:

No analysis charts show up for hourly aggregated flows

**How did you reproduce it?**

In the ntop web interface:

- Click "Flows" -> "Historical"
- Toggle "hourly"
- Click "Analysis"

Expected result: Charts show up as they do when "hourly" is not toggled
Actual result: No charts show up, only an empty light grey box (see screen shot)

**Debug Information**:

![image](https://github.com/user-attachments/assets/d370def0-8e91-4d02-899b-524033428f13)

**Comment by cardigliano** [comment]
It seems this can be reproduced on 6.0, while this is working on 6.1.

**Comment by MatteoBiscosi** [comment]
like @cardigliano said, this issue is for the stable version, soon we will release the new 6.2 ntopng stable version with the fix.

**Comment by MatteoBiscosi** [comment]
Verified as fixed, please reopen if needed
