### ISSUE TITLE
Custom alerts queries not showing entries, alerts not showing filter button

### ISSUE THREAD

**Issue by xkrizp09** [ntop/ntopng#8545]
Environment:
OS name: Debian
OS version: 12
Architecture: amd64
ntopng version/revision: ntopng Enterprise L v.6.1.240722

Hello,
I checked your alert guide for ntopng and found out, that there are custom alerts queries, but i my environment there are not showing entries as its shown in guide.
![Snímek obrazovky 2024-07-22 112129](https://github.com/user-attachments/assets/40257ffd-72e9-4d83-b533-0e695f16015e)
In your guide there is screenshot, how it looks like when everything is working correctly, so is this bug?
![image](https://github.com/user-attachments/assets/15818b3a-ddf5-4e37-867f-93e33d728a7c)

I´ve also noticed, that sometimes "plus" button where i can filter alterts is not visible, so I cannot filter alerts.
<img width="902" alt="image" src="https://github.com/user-attachments/assets/3957e4fd-048a-44ea-ab20-defbbfdf896c">

Thank you

**Comment by cardigliano** [comment]
@xkrizp09 I can see the dropdown for selecting queries in your screenshot, now sure I got what is missing. Please note those queries are currently in the Flow and Host alerts only.
As of the + button for adding filters, does it appear just randomly refreshing the page?

**Comment by xkrizp09** [comment]
In all queries (alert type, CLI/SRV, CLI/SRV alert type, CLI/SRV server port, info) I am missing the table under the chart with all the entries. Screenshot with white theme is from your guide.

I have 6 interfaces and the first interface always has a button here for all alert types.
But for the other interfaces, button is always missing in flow and SNMP alerts. In other alerts the button is there. 
![image](https://github.com/user-attachments/assets/43b03d61-ebeb-4b59-905e-73910925ca8a)

**Comment by cardigliano** [comment]
Fixed in 1d6efb9b13c18c36bf5e2935912d90e0fe577585, an update will be available later today

**Comment by xkrizp09** [comment]
its working, thx
