### ISSUE TITLE
Error with "ntopng-utils-manage-updates"

### ISSUE THREAD

**Issue by plegrand1** [ntop/ntopng#8548]
Hello,

**Environment**:
* OS name: Debian
* OS version: 12
* Architecture: amd64
* ntopng version/revision: 6.1.240723-23993

**What happened**:
Since last update, i've got an error message from crontab
 /etc/cron.d/ntopng
`* * * * * root /usr/bin/ntopng-utils-manage-updates -a handle-on-demand-requests`

The error message is the following:
```
/usr/bin/ntopng-utils-manage-updates: ligne 211: erreur de syntaxe près du symbole inattendu « fi » 
/usr/bin/ntopng-utils-manage-updates: ligne 211: `	fi'
```
What could be the workaround because i receive an error mail every minute ?

Thanks for your help
Pascal

**Comment by cardigliano** [comment]
Fixed in 8805eb617a41d83a5e65f31d3c7164872233a5d5 , building new packages, an update will be available in ~1h from now

**Comment by plegrand1** [comment]
Ouch!!!
I am impressed by the speed of the response and the solution provided.
Thanks a lot
I'm not a specialist of bash and i'm not sure about the problem.
Is it because of the empty "else ?

**Comment by cardigliano** [comment]
Yes, bash does not like empty else blocks, this was fixed yesterday but it seems we forgot to push it sorry.

**Comment by plegrand1** [comment]
> Yes, bash does not like empty else blocks, this was fixed yesterday but it seems we forgot to push it sorry.

No problem and thanks again
