### ISSUE TITLE
Modify Exporters Menu

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8551]
- Remove "Flow Exporters" submenu entry from the "Flow Exp."
- Under the "nProbe Instances" menu in the square menu 
<img width="384" alt="image" src="https://github.com/user-attachments/assets/1f3b4d61-da16-4e7e-a6f6-6835e3aa5b7c">
add "Exporters" entry that points to the /lua/pro/enterprise/exporters.lua (former page)
- In the "Exporters" page (see the above bullet) 
<img width="391" alt="image" src="https://github.com/user-attachments/assets/8624c74b-c226-4d8d-8ba8-62b6fd037d07">
in the square add a menu entry that points to /lua/pro/enterprise/nprobe.lua (nProbe Instances)

**Comment by DGabri** [comment]
Completed

1.
<img width="359" alt="Screenshot 2024-07-23 at 3 51 23 PM" src="https://github.com/user-attachments/assets/6dde27b9-6de5-4373-ad8e-de92c1daa446">

2.
<img width="449" alt="Screenshot 2024-07-23 at 3 51 40 PM" src="https://github.com/user-attachments/assets/ce2ac222-f6b8-490c-8fc3-55a3f01a0f26">

3.
<img width="436" alt="Screenshot 2024-07-23 at 3 52 47 PM" src="https://github.com/user-attachments/assets/b1af5e68-f6c0-4b0c-822b-22e648c23b5d">

**Comment by DGabri** [comment]
Fixed
