### ISSUE TITLE
Missing Menu Label

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8553]
This image is OK
<img width="834" alt="Screenshot 2024-07-23 at 15 15 36" src="https://github.com/user-attachments/assets/18cee8f6-5b61-4435-9b86-49a6404804d2">

This is not: Missing "(nProbe)"
<img width="724" alt="Screenshot 2024-07-23 at 15 15 42" src="https://github.com/user-attachments/assets/e95ef7f0-094f-41fd-9608-155d1ba40c8b">

**Comment by DGabri** [comment]
Completed

<img width="594" alt="Screenshot 2024-07-23 at 3 50 38 PM" src="https://github.com/user-attachments/assets/2301230d-c159-4c02-b429-3ac3be48aea3">

**Comment by DGabri** [comment]
Fixed
