### ISSUE TITLE
Implement ASN Exporter Stats

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8557]
For each ASN, implement per direction (-> ASN and ASN ->) stats:
- exporter IP / Interface traffic volume (sent/received)

**Comment by cardigliano** [comment]
Implemented (testing)

**Comment by cardigliano** [comment]
Available in the Historical Flows page as custom queries. "Top Receiver AS Exporter Iface" for data going to the AS, "Top Sender AS Exporter Iface" for data leaving the AS. In bytes is the rx data for the exporter interface, Out bytes is the tx data.

<img width="1586" alt="Screenshot 2024-10-17 at 11 04 05" src="https://github.com/user-attachments/assets/476f2d3e-05d7-434e-a271-27c8bf65f4d4">

**Comment by lucaderi** [comment]
Verified as implemented
