### ISSUE TITLE
Custom applications and adding rule from flow problem

### ISSUE THREAD

**Issue by xkrizp09** [ntop/ntopng#8559]
Environment:
OS name: Debian
OS version: 12
Architecture: amd64
ntopng version/revision: ntopng Enterprise L v.6.1.240724

Hello,
I noticed issues with Custom applications, Custom Categories and adding rule from Flow.

I started ntopng with –ndpi-protocols=/var/lib/ntopng/protos.txt, in protos.txt file there is 

![image](https://github.com/user-attachments/assets/8621ed85-808d-4bf7-9599-33a1e7bb26a5)

Then I restarted ntopng, but there are no new application in Application. When I tried edit existing application by adding new domain  in GUI nothing happed even after restart. 

![image](https://github.com/user-attachments/assets/75cb173c-aa3b-4f92-8a5d-6748f54afa90)

So i Tried to add http from live flow and got this: (I tried to add him to different application than 1kxun):

![image](https://github.com/user-attachments/assets/78acc81b-9a4b-4e26-a122-d60938a7027d)

After that there is this log:

15:43:51 [flow_details.lua:252] [protos_utils.lua:345] ERROR [protos.txt] Could not open '' for write

in my system ntopng has all premisson for protos.txt

**Comment by MatteoBiscosi** [comment]
Hi @xkrizp09 could you please share your protocols file here?
do not edit manually the protocol files, add the protocols from the gui, because some info (like the identifier) are added to the protocol file.
Add new protocols by clicking the + icon 
![image](https://github.com/user-attachments/assets/ec832746-f0e8-491f-80ad-5e7cc6759a7d)
and follow the rules written in the screenshot you sent

**Comment by xkrizp09** [comment]
My proto.txt:
ip:www.ntop.org@ntop
host:"disneyplus.com",host:"cdn.registerdisney.go.com",host:"disney-portal.my.onetrust.com",host:"disneyplus.bn5x.net",host:"disney-plus.net"@DisneyPlus
tcp:9002@Elasticsearch

I can not see + icon in my GUI.

**Comment by MatteoBiscosi** [comment]
the file should be similar to:

biscosi@develv5:~$ cat protos.txt 
ip:0.0.0.0:55666@matteo=1024

Like i said the issue is that it needs some ids and other things used by ntopng.
Could you please send me the output of `journalctl -e -u ntopng` and the ntopng config file?

**Comment by xkrizp09** [comment]
My original file was saved in /var/lib/ntopng/proto.txt and it didn't work, so I created new file in /etc/ntopng/custom_protocols.txt and now its working as you describe. Thank you
