### ISSUE TITLE
Invalid probe type

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8563]
Invalid probe type (Packet) instead of sFlow

nprobe -3 6343 --zmq tcp://127.0.0.1:1234 --zmq-probe-mode
nprobe -3 2055 --zmq tcp://127.0.0.1:1234 --zmq-probe-mode

<img width="1177" alt="Screenshot 2024-07-24 at 17 45 36" src="https://github.com/user-attachments/assets/0c149869-e7be-4bfb-be34-3712a8748369">

TODO
- add in nProbe/cento the flow exporter type
- export additional nprobe configuration info

**Comment by MatteoBiscosi** [comment]
This happens because no packet has been received and cannot be understood which kind of exporter is
