### ISSUE TITLE
Saving wrong timestamp in redis

### ISSUE THREAD

**Issue by mathieufrh** [ntop/ntopng#857]
Hello,

I have a problem regarding redis and the `seen_first` and `seen_last` Host variables.    
The `Host::getJSONObject()` function is regularly called and I add a debug string inside it to print `first_seen` and `last_seen` variables values.    
However it seems that the last time the function is called, when deserializing to redis, the timestamps are both `0`. Here is what I get with my debug string:

```
serial:618 IF:2 MAC:AA:BB:CC:DD:EE:FF IP:192.168.30.219 first.seen=1481643693
serial:618 IF:2 MAC:AA:BB:CC:DD:EE:FF IP:192.168.30.219 last.seen=1481643700
serial:618 IF:2 MAC:AA:BB:CC:DD:EE:FF IP:192.168.30.219 first.seen=1481643693
serial:618 IF:2 MAC:AA:BB:CC:DD:EE:FF IP:192.168.30.219 last.seen=1481643705
serial:618 IF:2 MAC:AA:BB:CC:DD:EE:FF IP:192.168.30.219 first.seen=1481643693
serial:618 IF:2 MAC:AA:BB:CC:DD:EE:FF IP:192.168.30.219 last.seen=1481643710
[...]
Shutting down...
Flushing host contacts for interface eth0
[...]
serial:618 IF:2 MAC:AA:BB:CC:DD:EE:FF IP:192.168.30.219 first.seen=0
serial:618 IF:2 MAC:AA:BB:CC:DD:EE:FF IP:192.168.30.219 last.seen=0
```

As you can see, this example use one single host, in the first part of the output everything is OK but after shutting down ntopng, the Hosts are deserialized to redis and this time there is something wrong, the timestamps are 0.

Here is my configuration:

```
-U=root 
-F=mysql;localhost;ntopng;flows;root;PASSWORD 
-D=local 
-W=4433 
-G=/var/tmp/ntopng.pid 
```

Can someone help ? Because actually, if I restore an host from redis with `first.seen` and `last.seen` equal to `0`, on the host page the table column `Seen since` says "46 years..." which I guess is what separates us from the 1970/01/01.

**Comment by simonemainardi** [comment]
thanks for reporting. We've found the issue. New packages will be available tomorrow. Please flush redis before trying otherwise you will get deserialized zero first and last seen.
