### ISSUE TITLE
TLS/SSH exact version/ciphers stored in alerts or historical flow

### ISSUE THREAD

**Issue by xkrizp09** [ntop/ntopng#8570]
**What would you like to add or change?**:
Can we get information about Obsolete SSH/TLS verions/cipher saved in alerts or historical flows like its shown in live flows? 
In live flow I can see information exact information about version/ciphers, but I can't find this information in alerts or historical flows.

**Why do you and others need this?**:
Alert tells me only that there is TLS version < 1.1. I would like to know exact version, now I have to go to live flows a wait until I see flow again and than check the version.

Live flow:
<img width="420" alt="image" src="https://github.com/user-attachments/assets/575c3ad5-4720-45dd-9c26-d4eabf36b5ef">

Alerts:
<img width="576" alt="image" src="https://github.com/user-attachments/assets/5edacd34-164f-4a2b-a489-21bf13597559">

Historical info:
<img width="590" alt="image" src="https://github.com/user-attachments/assets/8584075e-6002-4ba8-b0fb-c38c7e844cf2">

**Comment by MatteoBiscosi** [comment]
Hi @xkrizp09 this was an bug, where the informations where not correctly displayed. In the dev version this issue should be solved with the new build in a couple of hours. In case it is not working, please reopen the ticket.
![image](https://github.com/user-attachments/assets/c6667fd6-47c9-4889-bc9c-29d9746c29ae)
