### ISSUE TITLE
date and time expressed in different time zones

### ISSUE THREAD

**Issue by ptocadoa** [ntop/ntopng#8571]
Hello 
I am trying to use ntopng in my local timezone with the following compose file.

version: "3.3"

services:
  ntopng:
    container_name: ntopng
    image: ntop/ntopng.dev
    command: --community -d /var/lib/ntopng -i br0 -r 127.0.0.1:6379@0 -w 0.0.0.0:8001
    volumes:
      - /share/dockervolumes/ntopng:/var/lib/ntopng
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    dns: 192.168.1.1
    privileged: true
    restart: always
    environment:
            - TZ=Europe/Andorra

Nevertheless, I see this. I can not figure what timezone I am really using:
  
![image](https://github.com/user-attachments/assets/ddfa58a4-d14b-42bf-a1cd-69faaa5797c2)

**Comment by ptocadoa** [comment]
My version: 
![image](https://github.com/user-attachments/assets/eafaa2b0-4d3e-4dbe-88e7-6f08306e0837)

**Comment by lucaderi** [comment]
UTC+2 is CEST that is the Andorra time. Everything looks good.
