### ISSUE TITLE
Timezone not in-sync

### ISSUE THREAD

**Issue by chengidesk** [ntop/ntopng#8572]
similar to https://github.com/ntop/ntopng/issues/6492
having issue after updating to the latest Opnsense 24.7_9.

**Environment**:
* OS name: [e.g. Ubuntu] FreeBSD 
* OS version: [e.g. 18.04] 14.1 
* Architecture: [e.g. amd64] amd64
* ntopng version/revision: [e.g. 5.1.211223] ntopng Community v.6.0.240722 (FreeBSD 14.1) | 

**What happened**:
Timezone not in sync with browser

**How did you reproduce it?**
Just looking at the dashboard summary and when looking at the summary. 

**Debug Information**:

![image](https://github.com/user-attachments/assets/346f92fc-6f05-49fd-bf40-d70fa9eca0b7)
![image](https://github.com/user-attachments/assets/7bee96cf-8406-488b-bb7b-891d8304cc85)
![image](https://github.com/user-attachments/assets/09618a8d-50b4-489c-9dda-89fa3dfc27bf)

**Comment by chengidesk** [comment]
Magically, today the system back to normal again, not sure if it is a bug or something. I will proceed to close it.
![image](https://github.com/user-attachments/assets/3dcd5ff8-5219-4410-9ddf-9024d9460408)

**Comment by vk2him** [comment]
I have the same issue as reported above on OPNsense 24.7_9 - my local timezone is UTC +10 and ntopng displays in UTC.

It's been like this for a few days, it hasn't reverted to correct local time as @chengidesk saw
