### ISSUE TITLE
Elephant Flow Check Not Triggered

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8573]
Howto reproduce it
1. Enable the "Elephant Flow" check and set threshold to 10 MB for all directions
2. Start ntopng as -B "net 151.0.0.0/8" -i ethX
3. Download wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.10.2.tar.xz

The alert is triggered but it is not reported in the flow score nor in the alert page

**Comment by cardigliano** [comment]
- Elephant Flow Check score has been increased in e4dcc0a5675ae0618bbea8693904c1b1e9fc13c7 to be notified over less relevant alerts
- Notes added in be7b1c9d59ec8246ac1c05690800221813b4b7b3

**Comment by MatteoBiscosi** [comment]
This issue seems fixed
