### ISSUE TITLE
Cannot start ntopng on opnsense due to redis auth

### ISSUE THREAD

**Issue by MrHakisak** [ntop/ntopng#8574]
OS: Opnsense 24.7_9 (bare metal)
ntopng version/revision: os-ntopng-enterprise 6.1.240730

What happened:
trying to start ntopng on opnsense, redis is enabled. it hasn't been working for weeks since an update.
typing "date" into opnsense shell shows correct date+time.
please be clear with instructions, im inexperienced.

Debug Information:
> /usr/local/etc/rc.d/ntopng: WARNING: failed to start ntopng	
> [Redis.cpp:157] ERROR: to specify a redis server other than the default	
> [Redis.cpp:154] ERROR: Please start it and try again or use -r	
> [Redis.cpp:153] ERROR: ntopng requires redis server to be up and running	
> [Redis.cpp:120] ERROR: NOAUTH Authentication required.	
> [Redis.cpp:120] ERROR: NOAUTH Authentication required.	
> [Redis.cpp:120] ERROR: NOAUTH Authentication required.	
> [Redis.cpp:120] ERROR: NOAUTH Authentication required.	
> [Redis.cpp:120] ERROR: NOAUTH Authentication required.	
> [Redis.cpp:120] ERROR: NOAUTH Authentication required.	
> [Redis.cpp:120] ERROR: NOAUTH Authentication required.	
> [Redis.cpp:120] ERROR: NOAUTH Authentication required.	
> [Redis.cpp:120] ERROR: NOAUTH Authentication required.	
> [Redis.cpp:120] ERROR: NOAUTH Authentication required.	
> [Redis.cpp:120] ERROR: NOAUTH Authentication required.	
> [Redis.cpp:120] ERROR: NOAUTH Authentication required.	
> [Redis.cpp:120] ERROR: NOAUTH Authentication required.	
> [Redis.cpp:120] ERROR: NOAUTH Authentication required.	
> [Redis.cpp:120] ERROR: NOAUTH Authentication required.	
> [Redis.cpp:120] ERROR: NOAUTH Authentication required.	
> [Ntop.cpp:3890] WARNING: Unable to find timezone: using UTC

configuration: certificate none, dns mode none, 2 interfaces.
redis config: default. tried disabling "Enable Protected Mode". also reset the db.

**Comment by lucaderi** [comment]
You need to specify the password in the configuration file as follows

```
[--redis|-r] <fmt>                  | Redis connection. <fmt> is specified as
                                    | [h[:port[:pwd]]][@db-id] where db-id
                                    | identifies the database Id (default 0).
                                    | h is the host running Redis (default
                                    | localhost), optionally followed by a
                                    |  ':'-separated port (default 6379).
                                    | The special characters \ and ` are not
                                    | supported by ntopng.
                                    | A password can be specified after
                                    | the port when Redis auth is required.
                                    | By default password auth is disabled.
                                    | Examples:
                                    | -r @2
                                    | -r 129.168.1.3
                                    | -r 129.168.1.3:6379@3
                                    | -r 129.168.1.3:6379:nt0pngPwD@0

```

or remove the authentication and ntopng will start
