### ISSUE TITLE
NTOPNG does not get timezone via DOCKER

### ISSUE THREAD

**Issue by ptocadoa** [ntop/ntopng#8579]
My ntopng compose
![image](https://github.com/user-attachments/assets/3818015d-8689-49c1-b2a0-bb6c54b8352c)

**Comment by ptocadoa** [comment]
what i see is in GMT 
![image](https://github.com/user-attachments/assets/7f774afb-116a-418a-b8bf-3f772339918b)

**Comment by cardigliano** [comment]
This seems to be the same as https://github.com/ntop/ntopng/issues/8571 Please avoid opening multiple tickets for the same issue.

**Comment by ptocadoa** [comment]
Perhaps #8571 issue was not clear and was closed maybe too fast (I was getting different TZ at diferent places)
Today I have forced a redeploy of the docker with the above yaml and NTOPNG does not get the TZ specified.

**Comment by cardigliano** [comment]
An update for the ntopng.dev image should be available on dockerhub, it seems the tzdata package was not installed which affects the timezone. Please check the new image and let us know.

**Comment by ptocadoa** [comment]
Although It seems I am using latest version, it says TZ=UTC
![image](https://github.com/user-attachments/assets/8b5562ae-c19a-43a8-a432-2b039826c065)

If i connect to ntopng command line:
![image](https://github.com/user-attachments/assets/ea577993-ad5b-4ea5-8647-fadb7e3b9453)

**Comment by cardigliano** [comment]
Could you check the time to see if it is correct, regardless of the printed Timezone name?
Please also provide the date output

**Comment by ptocadoa** [comment]
![image](https://github.com/user-attachments/assets/cbcca2a4-7fdd-4818-a119-d7a8e6760f56)
Screenshot taken right now. Please note the local timezone at the taskbar vs the GMT timezone inside the browser.

![image](https://github.com/user-attachments/assets/7d4d4f17-8340-4f0c-9dc1-78675e2a40da)
Please note the date at the host (above) and date inside ntopng docker.

**Comment by cardigliano** [comment]
Could you run apt install tzdata in the container and issue date again?

**Comment by ptocadoa** [comment]
![image](https://github.com/user-attachments/assets/2d82f58c-2deb-4a22-9747-23ce500a5582)
Installed tzdata in the container
Date now reports correctly in bash
At the botton of the ntopng page, the date is local.
The dashboards, filters, graphs are still using epoch time and GMT timezone.

**Comment by cardigliano** [comment]
d31236f7ed4e2f3c1e7b61aa7c4a2b8db5acae30 probably fixes this, please wait for the new docker images (tomorrow)

**Comment by ptocadoa** [comment]
date+time seems to have been corrected:
![image](https://github.com/user-attachments/assets/0c7a185e-6da0-4315-bfb4-a27a1765c419)

but as time goes by:
![image](https://github.com/user-attachments/assets/08ec6cf5-c156-4f28-b95b-66637e3fb292)

graphs do not appear:
![image](https://github.com/user-attachments/assets/b1c2789e-9eaa-4afd-b17b-aa39ab728edc)

I have tried to reset ntop preferences via:
redis-cli keys "ntopng.*" | xargs redis-cli unlink

**Comment by MatteoBiscosi** [comment]
what are you currently using, rrd or influxdb?

**Comment by ptocadoa** [comment]
I am currently using RRD, cleaning redis preferences.
I have just changed to Influx 1.8.10....commenting rsults in a few minutes

Changing to Influx makes unresponsive my ntopng docker.
Access denied to folder/files appear:
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/-1/top_talkers/) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/-1/alerts/) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/0/top_talkers/) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/0/alerts/) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/ts_schemas) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/scripts_data) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks/interface) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks/interface/interface) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/httpdocs) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/alert_endpoints) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks/interface) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks/interface/network) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/http_lint) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/menu_items) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/locales) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks/system) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks/system/active_monitoring) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/check_definitions) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/scripts) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks/system) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks/system/system) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks/system) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks/system/snmp_device) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks/system) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks/system/syslog) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/alert_definitions) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/modules) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks/interface) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks/interface/flow) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks/interface) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/callbacks/interface/host) failed [13/Permission denied]
02/Aug/2024 12:49:46 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/scripts/templates) failed [13/Permission denied]
02/Aug/2024 12:49:49 [Utils.cpp:761] WARNING: mkdir(/var/lib/ntopng/tmp/influxdb/) failed [13/Permission denied]
[admin@NAS164B9C ntopng]#

**Comment by MatteoBiscosi** [comment]
To do that, you need to add the option to the configuration file:
--dont-change-user

**Comment by ptocadoa** [comment]
I have deleted the folder of my docker ntopng and recreated
I had configured influxdb as backend
Restarted the docker and voila, graphs appear using influxdb

**Comment by cardigliano** [comment]
Thank you for reporting, this seems solved
