### ISSUE TITLE
Correct license but nprobe only executes in demo mode

### ISSUE THREAD

**Issue by gabrieldt** [ntop/ntopng#858]
I run nprobe in a virtual box machine and when I have generated the license it ran ok, but after a couple a days it decided do run in demo mode. I have double checked the license it is correct.
Is it because the license is for educational purposes ?

What can I do to solve this problem? If you need more information please let me know.

Best regards.

**Comment by ValentinaViscarelli** [comment]
If you use a virtual machine in order to run nprobe or ntopng, you have to add this parameter in configuration: 

--online-license-check 

Regards

**Comment by Uzzi** [comment]
I've ntop on Fisical server and I've the same problem
Also with --online-license-check in ntopng.conf
nprobe -v tell me I've a  [valid license]  [357 days left]

**Comment by simonemainardi** [comment]
@gabrieldt nprobe (and ntopng) licenses are bound to the hardware. Running on top of a VM may result in hardware changes (e.g., the hypervisor can change the cards MAC addresses). Adding `--online-license-check` should solve the issue.

@Uzzi you added `--online-license-check` to ntopng.conf and you are checking the nprobe license... if you want to check ntopng do `ntopng --check-license`

**Comment by Uzzi** [comment]
Ok.
Now I've ntop licence code in /etc/ntopng.license.
ntopng --check-license ---> License Ok
I see Upgrade to Professional version
Why?

nProbe Pro:
nprobe -v ---> [valid license]

**Comment by emanuele-f** [comment]
@Uzzi can you post the startup log of ntopng?

**Comment by gabrieldt** [comment]
Thanks everyone! 
I have solved the problem by starting nprobe with --online-license-check.

Best regards!

**Comment by Uzzi** [comment]
@emanuele-f ok,thank you I'll do it monday morning

**Comment by Uzzi** [comment]
@emanuele-f 
These are my ntopng.log rows:
`14/Dec/2016 19:04:34 [Ntop.cpp:1121] Setting local networks to 127.0.0.0/8
14/Dec/2016 19:04:34 [Redis.cpp:92] Successfully connected to redis 127.0.0.1:6379@0
14/Dec/2016 19:04:34 [NtopPro.cpp:118] [LICENSE] Read license from Redis []
14/Dec/2016 19:04:34 [NtopPro.cpp:182] ERROR: [LICENSE] Invalid or missing ntopng License [Empty license file]
14/Dec/2016 19:04:34 [NtopPro.cpp:195] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
14/Dec/2016 19:04:34 [NtopPro.cpp:197] WARNING: [LICENSE] before returning to community mode
14/Dec/2016 19:04:34 [NtopPro.cpp:198] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
14/Dec/2016 19:04:34 [NtopPro.cpp:199] WARNING: [LICENSE] or run ntopng in community mode starting
14/Dec/2016 19:04:34 [NtopPro.cpp:200] WARNING: [LICENSE] ntopng --community
`

I've licence code in /etc/ntopng.license

**Comment by simonemainardi** [comment]
@Uzzi it looks like you license file is empty `ERROR: [LICENSE] Invalid or missing ntopng License [Empty license file]`
make sure it contains the license key and is readable by ntopng

**Comment by Uzzi** [comment]
@simonemainardi 
-rw-r--r--  1 root  root      51 dic 14 20:10 ntopng.license

**Comment by simonemainardi** [comment]
@Uzzi  did you place ntopng.license under `etc`? The correct path is `/etc/ntopng.license`

**Comment by Uzzi** [comment]
@simonemainardi 
yes /etc/ntopng.license

**Comment by simonemainardi** [comment]
make sure the file contains just the license string, without heading/trailing spaces or other characters.

**Comment by Uzzi** [comment]
I've Add on WebGui

**Comment by Uzzi** [comment]
Now Works fine. I've purged and reinstalled all

Thank you

**Comment by souzaeric** [comment]
Hi, I've ntop on virtual server and I've the same problem. The systemID changed a few months ago and after this I always run with --online-license-check, but today after I update my ntopng and nprobe, I can't check online.

Before today my version was: v2.5.161121

I always started my nprobe like this: nprobe -3 1237 -i eth0 --zmq tcp://*:5580 -G --online-license-check

And now nprobe doesn't check online and always start like demo mode.

ERROR: Invalid nProbe license (/etc/nprobe.license) [License mismatch error]
12/Jan/2017 11:52:31 [nprobe.c:3496] ERROR: *****************************************************
12/Jan/2017 11:52:31 [nprobe.c:3497] ERROR: **                                                 **
12/Jan/2017 11:52:31 [nprobe.c:3498] ERROR: **  Switching to DEMO MODE (missing valid license) **
12/Jan/2017 11:52:31 [nprobe.c:3499] ERROR: **                                                 **
12/Jan/2017 11:52:31 [nprobe.c:3500] ERROR: **  Purchase your nProbe license at                **
12/Jan/2017 11:52:31 [nprobe.c:3501] ERROR: **       https://shop.ntop.org/                    **
12/Jan/2017 11:52:31 [nprobe.c:3502] ERROR: **                                                 **
12/Jan/2017 11:52:31 [nprobe.c:3503] ERROR: *****************************************************

 ERROR: ***************************************************************
12/Jan/2017 11:52:31 [nprobe.c:7715] ERROR: * NOTE: This is a DEMO version limited to 25000 flows export.  *
12/Jan/2017 11:52:31 [nprobe.c:7716] ERROR: ***************************************************************

**Comment by simonemainardi** [comment]
please, follow the instructions at http://www.ntop.org/support/faq/how-can-i-move-a-license-to-a-new-server/

**Comment by souzaeric** [comment]
I already did this an one year ago.
The website ntop says "Note that we can allow you this operation only once".
So, after this, I only use --online-license-check, but after update this doesn't works anymore.

**Comment by ValentinaViscarelli** [comment]
@souzaeric 
I think your maintenance license has expired. 
Please our license works in this way:
http://www.ntop.org/support/faq/are-licenses-permanent-what-about-maintenance/
Please send me in private (valentina@ntop.org) the purchase  order id and/or the output of this command:
cat /etc/nprobe.license
I will tell you if your license has expired and when.
