### ISSUE TITLE
Invalid traffic direction with Blacklisted Server Contact

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8582]
Some (if not all) "Blacklisted Server Contact" alerts are swapped in the direction

**Comment by Sunny463467** [comment]
Jason

**Comment by MatteoBiscosi** [comment]
The direction seems correct, as you can see from the screenshot below. I'll mark this issue as resolved, in case it is not please reopen the ticket
![image](https://github.com/user-attachments/assets/91710dcd-3f16-44ac-9aa4-7b98dd6d4282)
