### ISSUE TITLE
Implement Mitre Att&ck Dashboard

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8584]
Implement tiny Dashboard Block with Mitre Att&ck Information

**Comment by lucaderi** [comment]
This issue depends on #8592

**Comment by cardigliano** [comment]
Added new "Security Report"

**Comment by lucaderi** [comment]
<img width="1416" alt="Screenshot 2024-08-09 at 19 40 06" src="https://github.com/user-attachments/assets/40f2aee3-dd79-4046-86ff-36b36e2e3c07">

Mostly working but 
- the boxes are duplicated
- Top Mitre on Flows are empty

**Comment by cardigliano** [comment]
Fix in bc26f3f5eb51cb5e0ca2cb913fcb2514b70bec61

**Comment by MatteoBiscosi** [comment]
Implemented as requested
