### ISSUE TITLE
Inconsistent Flow Drops

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8585]
<img width="1388" alt="image" src="https://github.com/user-attachments/assets/f5a0560f-86a2-4275-ab2d-b7ff5138eb7b">
<img width="1354" alt="image" src="https://github.com/user-attachments/assets/dc2bbd06-6cbe-4f20-91dc-87362052a6d5">

**Comment by MatteoBiscosi** [comment]
Changed labels, the two values indicates 2 different kind of drops, the first one from the ntopng side (ntopng drops) the secondo one, is instead from nprobe point of view (nprobe drops)

**Comment by lucaderi** [comment]
Verified as fixed
