### ISSUE TITLE
Add Interface Ids in the Exporters Sankey

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8586]
<img width="1027" alt="Screenshot 2024-08-01 at 19 37 52" src="https://github.com/user-attachments/assets/fc722e4b-d273-4502-ac5c-c3994f47966c">
<img width="1263" alt="Screenshot 2024-08-01 at 19 37 43" src="https://github.com/user-attachments/assets/816c589f-f2ad-4d34-b4e9-2b28d42c7fa8">

**Comment by MatteoBiscosi** [comment]
Already added in the latest version (duplicated ticket)
