### ISSUE TITLE
[nEdge] interface chart timeseries not visible

### ISSUE THREAD

**Issue by tano46** [ntop/ntopng#8588]
**Environment**:
Ubuntu
20.04.6 LTS
amd64
nedge version/revision: [e.g. 6.1.2406105.1.211223]

**What happened**:
Timeseries chart for net interfaces not visible any more

**How did you reproduce it?**
click on Dashboard menu -> Gateways and Users -> <interface name es. enp7s0>
click on chart icon
no data visible
![nedge](https://github.com/user-attachments/assets/91555a1d-f214-4b50-b4e7-ce12cb2d3e9c)

**Comment by MatteoBiscosi** [comment]
Hi @tano46 please update to the latest ntopng version and let me know

**Comment by cardigliano** [comment]
This seems to be working for me, tested with v.6.1.240813

<img width="924" alt="Screenshot 2024-08-13 at 15 57 06" src="https://github.com/user-attachments/assets/da73c6cb-cdc8-4eb7-8846-43b6ecc7df9e">

**Comment by cardigliano** [comment]
Closing, please reopen if reoccurs
