### ISSUE TITLE
Rework nProbe Instances Page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8590]
<img width="1488" alt="Screenshot 2024-08-03 at 21 22 06" src="https://github.com/user-attachments/assets/abd9324e-bd8b-402e-bc77-6a43064cdfdc">

In the nProbe Instances Page
- remove UUID and Public IP or move it as the last columns
- add nProbe version
- Change the label Interface in nProbe Interfaces
- In case of drops 
<img width="1522" alt="image" src="https://github.com/user-attachments/assets/79c8c832-fda4-41ea-9b43-fde9959f24c3">
ass a better label. Example replace "0" with "No Drops" or "X" with "X Flow Dropped"

**Comment by lucaderi** [comment]
<img width="1402" alt="image" src="https://github.com/user-attachments/assets/fa531aaf-c0e5-4b09-9ce3-79f42622f39a">
Not working as expected

**Comment by MatteoBiscosi** [comment]
The issue should now be fixed, it was with packets capturing probes
![image](https://github.com/user-attachments/assets/7852eb6d-6e6c-488b-b176-9206b16e2abe)

**Comment by MatteoBiscosi** [comment]
Issue has been fixed
