### ISSUE TITLE
Hide Asset Inventory Preference

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8591]
This is to request to hide the "Asset Inventory" preference temporarily as well as disable the underneath logic that will be restored past the 6.2 stable release

**Comment by DGabri** [comment]
Disabled and also disabled default value c++ side.

<img width="501" alt="Screenshot 2024-08-05 at 10 26 53 AM" src="https://github.com/user-attachments/assets/e15a29c0-e375-4147-9647-e9a2de799068">
