### ISSUE TITLE
Menu item "Protocols/DNS" fails (no table shown)

### ISSUE THREAD

**Issue by JuergenWeber** [ntop/ntopng#86]
When calling "Protocols/DNS" the following error occured:
ntopng: [src/Lua.cpp:4746] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_hosts_data.lua][/usr/share/ntopng/scripts/lua/get_hosts_data.lua:394: attempt to compare number with nil]

After putting line 394 between a "nil" check everything works:
if(value["active_http_hosts"] ~= nil) then 
     if(value["active_http_hosts"] > 0) then print(" <span class='badge badge-top-right'>".. value["active_http_hosts"] .."</span>") end
end

NTOPNG v.2.0.150611

**Comment by kYroL01** [comment]
fixed in commit 03de4213c3fc866a40dccbe1ed41e66a90c0cf16
