### ISSUE TITLE
alert driven shell script execution not working

### ISSUE THREAD

**Issue by p27182** [ntop/ntopng#8601]
**Environment**:
* OS name: ubuntu 
* OS version: 22.04 server
* Architecture: x86_64
* ntopng version/revision: 6.0.240417 [Enterprise/Professional build]

I'm unable to get the shell script alerts to work:
![image](https://github.com/user-attachments/assets/9c966b13-f11e-4064-bca7-1dfc2974b230)

![image](https://github.com/user-attachments/assets/78b3997b-28fb-447b-8f79-dce12c275368)

![image](https://github.com/user-attachments/assets/3f9f6654-cc09-449d-9a32-539a87ec92f7)

thanks for reading!

systemd status:
------------
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
     Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-08-05 08:07:44 EDT; 21h ago
    Process: 216556 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exited, status=0/SUCCESS)
    Process: 216570 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
    Process: 216572 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (code=exited, status=0/SUCCESS)
    Process: 216574 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /run/ntopng.conf (code=exited, status=0/SUCCESS)
   Main PID: 216576 (ntopng-main)
      Tasks: 85 (limit: 9390)
     Memory: 3.8G
        CPU: 2h 27min 40.415s
     CGroup: /system.slice/ntopng.service
             └─216576 /usr/bin/ntopng /run/ntopng.conf

Aug 06 00:00:31 ntopng ntopng[216576]: 06/Aug/2024 00:00:31 [housekeeping.lua:37] [lists_utils.lua:417] Updating list 'Abuse.ch URLhaus' [https://urlhaus.abuse.ch/downloads/hostfile/]... OK
Aug 06 00:00:31 ntopng ntopng[216576]: 06/Aug/2024 00:00:31 [housekeeping.lua:37] [lists_utils.lua:417] Updating list 'Emerging Threats' [https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt]... OK
Aug 06 00:00:31 ntopng ntopng[216576]: 06/Aug/2024 00:00:31 [housekeeping.lua:37] [lists_utils.lua:417] Updating list 'NoCoin Filter List' [https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt]... OK
Aug 06 00:00:31 ntopng ntopng[216576]: 06/Aug/2024 00:00:31 [housekeeping.lua:37] [lists_utils.lua:417] Updating list 'SSLBL Botnet C2 IP Blacklist' [https://sslbl.abuse.ch/blacklist/sslipblacklist.txt]... OK
Aug 06 00:00:32 ntopng ntopng[216576]: 06/Aug/2024 00:00:32 [housekeeping.lua:37] [lists_utils.lua:417] Updating list 'Stratosphere Lab' [https://mcfp.felk.cvut.cz/publicDatasets/CTU-AIPP-BlackList/Todays-Blacklists/AIP_historical_blacklist_prioritized_by_newest_at>
Aug 06 00:00:33 ntopng ntopng[216576]: 06/Aug/2024 00:00:33 [housekeeping.lua:37] [lists_utils.lua:417] Updating list 'ThreatFox' [https://threatfox.abuse.ch/downloads/hostfile/]... OK
Aug 06 00:00:33 ntopng ntopng[216576]: 06/Aug/2024 00:00:33 [housekeeping.lua:37] [lists_utils.lua:417] Updating list 'dshield 7 days' [https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/dshield_7d.netset]... OK
Aug 06 00:00:35 ntopng ntopng[216576]: 06/Aug/2024 00:00:35 [housekeeping.lua:37] [lists_utils.lua:679] List 'Stratosphere Lab' has 0 rules. Please report this to https://github.com/ntop/ntopng
Aug 06 00:00:35 ntopng ntopng[216576]: 06/Aug/2024 00:00:35 [housekeeping.lua:37] [lists_utils.lua:753] Category Lists (7694 hosts, 1461 IPs, 0 JA3) loaded in 2 sec
Aug 06 00:01:35 ntopng ntopng[216576]: 06/Aug/2024 00:01:35 [fetch_blog_feed.lua:15] [blog_utils.lua:125] Fetching latest ntop blog posts...
------------

last 1000 lines of journalctl -n 1000 -u ntopng (the last known alert happend at Aug 6th 4:59:30AM:
------------
Aug 05 08:07:44 ntopng ntopng[216576]: 05/Aug/2024 08:07:44 [NtopPro.cpp:851] [LICENSE] License Hash:        C0ECE00A2461356C4315B7179BDC1A2517352037646B9E28F0
Aug 05 08:07:44 ntopng ntopng[216576]: 05/Aug/2024 08:07:44 [NtopPro.cpp:864] [LICENSE] Maintenance:        Until Thu Dec 26 04:02:44 2024 [142 days left]
Aug 05 08:07:44 ntopng ntopng[216576]: 05/Aug/2024 08:07:44 [Ntop.cpp:945] Adding 127.0.0.1/32 as IPv4 interface address for lo
Aug 05 08:07:44 ntopng ntopng[216576]: 05/Aug/2024 08:07:44 [Ntop.cpp:956] Adding 127.0.0.0/8 as IPv4 local network for lo
Aug 05 08:07:44 ntopng ntopng[216576]: 05/Aug/2024 08:07:44 [Ntop.cpp:945] Adding 10.0.0.3/32 as IPv4 interface address for ens22
Aug 05 08:07:44 ntopng ntopng[216576]: 05/Aug/2024 08:07:44 [Ntop.cpp:956] Adding 10.0.0.0/24 as IPv4 local network for ens22
Aug 05 08:07:44 ntopng ntopng[216576]: 05/Aug/2024 08:07:44 [Ntop.cpp:981] Adding ::1/128 as IPv6 interface address for lo
Aug 05 08:07:44 ntopng ntopng[216576]: 05/Aug/2024 08:07:44 [Ntop.cpp:993] Adding ::1/128 as IPv6 local network for lo
Aug 05 08:07:44 ntopng ntopng[216576]: 05/Aug/2024 08:07:44 [Ntop.cpp:981] Adding fe80::90a8:XXXX:XXXX:XXXX/128 as IPv6 interface address for ens22
Aug 05 08:07:44 ntopng ntopng[216576]: 05/Aug/2024 08:07:44 [Ntop.cpp:993] Adding fe80::90a8:XXXX:XXXX:XXXX/64 as IPv6 local network for ens22
Aug 05 08:07:44 ntopng ntopng[216576]: 05/Aug/2024 08:07:44 [Ntop.cpp:981] Adding fe80::a2ce:XXXX:XXXX:XXXX/128 as IPv6 interface address for ens[NIC]
Aug 05 08:07:44 ntopng ntopng[216576]: 05/Aug/2024 08:07:44 [Ntop.cpp:993] Adding fe80::a2ce:XXXX:XXXX:XXXX/64 as IPv6 local network for ens[NIC]
Aug 05 08:07:44 ntopng ntopng[216576]: 05/Aug/2024 08:07:44 [PeriodicActivities.cpp:108] Started periodic activities loop...
Aug 05 08:07:44 ntopng ntopng[216576]: 05/Aug/2024 08:07:44 [startup.lua:38] Processing startup.lua: please hold on...
Aug 05 08:07:45 ntopng ntopng[216576]: 05/Aug/2024 08:07:45 [startup.lua:121] [lists_utils.lua:831] Refreshing category lists...
Aug 05 08:07:45 ntopng ntopng[216576]: 05/Aug/2024 08:07:45 [startup.lua:121] [lists_utils.lua:679] List 'Stratosphere Lab' has 0 rules. Please report this to https://github.com/ntop/ntopng
Aug 05 08:07:45 ntopng ntopng[216576]: 05/Aug/2024 08:07:45 [startup.lua:121] [lists_utils.lua:753] Category Lists (7710 hosts, 1448 IPs, 0 JA3) loaded in 0 sec
Aug 05 08:07:45 ntopng ntopng[216576]: 05/Aug/2024 08:07:45 [startup.lua:125] Initializing device polices...
Aug 05 08:07:45 ntopng ntopng[216576]: 05/Aug/2024 08:07:45 [startup.lua:141] Initializing alerts...
Aug 05 08:07:45 ntopng ntopng[216576]: 05/Aug/2024 08:07:45 [startup.lua:150] Initializing timeseries...
Aug 05 08:07:45 ntopng ntopng[216576]: 05/Aug/2024 08:07:45 [startup.lua:242] Completed startup.lua
Aug 05 08:07:45 ntopng ntopng[216576]: 05/Aug/2024 08:07:45 [PeriodicActivities.cpp:167] Found 10 activities
Aug 05 08:07:45 ntopng ntopng[216576]: 05/Aug/2024 08:07:45 [FlowChecksLoader.cpp:290] WARNING: Unable to find flow check 'tcp_issues_generic': skipping it
Aug 05 08:07:45 ntopng ntopng[216576]: 05/Aug/2024 08:07:45 [FlowChecksLoader.cpp:290] WARNING: Unable to find flow check 'tcp_issues_generic': skipping it
Aug 05 08:07:45 ntopng ntopng[216576]: 05/Aug/2024 08:07:45 [FlowChecksLoader.cpp:290] WARNING: Unable to find flow check 'udp_unidirectional': skipping it
Aug 05 08:07:45 ntopng ntopng[216576]: 05/Aug/2024 08:07:45 [FlowChecksLoader.cpp:290] WARNING: Unable to find flow check 'udp_unidirectional': skipping it
Aug 05 08:07:45 ntopng ntopng[216576]: 05/Aug/2024 08:07:45 [NetworkInterface.cpp:3720] Started packet polling on interface ens22 [id: 5]...
Aug 05 08:07:45 ntopng ntopng[216576]: 05/Aug/2024 08:07:45 [NetworkInterface.cpp:3720] Started packet polling on interface lo [id: 6]...
Aug 05 08:07:45 ntopng ntopng[216576]: 05/Aug/2024 08:07:45 [NetworkInterface.cpp:3720] Started packet polling on interface ens[NIC] [id: 7]...
Aug 05 08:07:46 ntopng ntopng[216576]: 05/Aug/2024 08:07:46 [Ntop.cpp:2685] Registered interface ens[NIC] [VLAN Id: 4] [id: 9]
Aug 05 08:07:46 ntopng ntopng[216576]: 05/Aug/2024 08:07:46 [NetworkInterface.cpp:3469] Started flow user script hooks loop on interface ens[NIC] [VLAN Id: 4] [id: 9]...
Aug 05 08:07:46 ntopng ntopng[216576]: 05/Aug/2024 08:07:46 [NetworkInterface.cpp:3720] Started packet polling on interface ens[NIC] [VLAN Id: 4] [id: 9]...
Aug 05 08:07:46 ntopng ntopng[216576]: 05/Aug/2024 08:07:46 [NetworkInterface.cpp:3529] Started host user script hooks loop on interface ens[NIC] [VLAN Id: 4] [id: 9]...
Aug 05 08:07:46 ntopng ntopng[216576]: 05/Aug/2024 08:07:46 [Ntop.cpp:2685] Registered interface ens[NIC] [VLAN Id: 2] [id: 10]
Aug 05 08:07:46 ntopng ntopng[216576]: 05/Aug/2024 08:07:46 [NetworkInterface.cpp:3469] Started flow user script hooks loop on interface ens[NIC] [VLAN Id: 2] [id: 10]...
Aug 05 08:07:46 ntopng ntopng[216576]: 05/Aug/2024 08:07:46 [NetworkInterface.cpp:3720] Started packet polling on interface ens[NIC] [VLAN Id: 2] [id: 10]...
Aug 05 08:07:46 ntopng ntopng[216576]: 05/Aug/2024 08:07:46 [NetworkInterface.cpp:3529] Started host user script hooks loop on interface ens[NIC] [VLAN Id: 2] [id: 10]...
Aug 05 08:07:46 ntopng ntopng[216576]: 05/Aug/2024 08:07:46 [NetworkInterface.cpp:2463] Packets exceeding the expected max size have been received [len: 1520][max len: 1518].
Aug 05 08:07:46 ntopng ntopng[216576]: 05/Aug/2024 08:07:46 [NetworkInterface.cpp:2470] WARNING: If TSO/GRO is enabled, please disable it for best accuracy
Aug 05 08:07:46 ntopng ntopng[216576]: 05/Aug/2024 08:07:46 [NetworkInterface.cpp:2470] WARNING: If TSO/GRO is enabled, please disable it for best accuracy
Aug 05 08:07:46 ntopng ntopng[216576]: 05/Aug/2024 08:07:46 [NetworkInterface.cpp:2475] WARNING: using: sudo ethtool -K ens[NIC] gro off gso off tso off
Aug 05 08:07:46 ntopng ntopng[216576]: 05/Aug/2024 08:07:46 [NetworkInterface.cpp:2475] WARNING: using: sudo ethtool -K ens[NIC] gro off gso off tso off
Aug 05 08:07:49 ntopng ntopng[216576]: 05/Aug/2024 08:07:49 [Ntop.cpp:2685] Registered interface ens[NIC] [VLAN Id: 3] [id: 8]
Aug 05 08:07:49 ntopng ntopng[216576]: 05/Aug/2024 08:07:49 [NetworkInterface.cpp:3720] Started packet polling on interface ens[NIC] [VLAN Id: 3] [id: 8]...
Aug 05 08:07:49 ntopng ntopng[216576]: 05/Aug/2024 08:07:49 [NetworkInterface.cpp:3469] Started flow user script hooks loop on interface ens[NIC] [VLAN Id: 3] [id: 8]...
Aug 05 08:07:49 ntopng ntopng[216576]: 05/Aug/2024 08:07:49 [NetworkInterface.cpp:3529] Started host user script hooks loop on interface ens[NIC] [VLAN Id: 3] [id: 8]...
Aug 05 08:07:50 ntopng ntopng[216576]: 05/Aug/2024 08:07:50 [housekeeping.lua:37] [lists_utils.lua:679] List 'Stratosphere Lab' has 0 rules. Please report this to https://github.com/ntop/ntopng
Aug 05 08:07:50 ntopng ntopng[216576]: 05/Aug/2024 08:07:50 [housekeeping.lua:37] [lists_utils.lua:753] Category Lists (7710 hosts, 1448 IPs, 0 JA3) loaded in 0 sec
Aug 05 08:07:52 ntopng ntopng[216576]: 05/Aug/2024 08:07:52 [Ntop.cpp:2685] Registered interface ens[NIC] [VLAN Id: 5] [id: 12]
Aug 05 08:07:52 ntopng ntopng[216576]: 05/Aug/2024 08:07:52 [NetworkInterface.cpp:3720] Started packet polling on interface ens[NIC] [VLAN Id: 5] [id: 12]...
Aug 05 08:07:52 ntopng ntopng[216576]: 05/Aug/2024 08:07:52 [NetworkInterface.cpp:3469] Started flow user script hooks loop on interface ens[NIC] [VLAN Id: 5] [id: 12]...
Aug 05 08:07:52 ntopng ntopng[216576]: 05/Aug/2024 08:07:52 [NetworkInterface.cpp:3529] Started host user script hooks loop on interface ens[NIC] [VLAN Id: 5] [id: 12]...
Aug 05 08:07:53 ntopng ntopng[216576]: 05/Aug/2024 08:07:53 [Ntop.cpp:2685] Registered interface ens[NIC] [VLAN Id: 6] [id: 11]
Aug 05 08:07:53 ntopng ntopng[216576]: 05/Aug/2024 08:07:53 [NetworkInterface.cpp:3720] Started packet polling on interface ens[NIC] [VLAN Id: 6] [id: 11]...
Aug 05 08:07:53 ntopng ntopng[216576]: 05/Aug/2024 08:07:53 [NetworkInterface.cpp:3529] Started host user script hooks loop on interface ens[NIC] [VLAN Id: 6] [id: 11]...
Aug 05 08:07:53 ntopng ntopng[216576]: 05/Aug/2024 08:07:53 [NetworkInterface.cpp:3469] Started flow user script hooks loop on interface ens[NIC] [VLAN Id: 6] [id: 11]...
Aug 05 08:07:54 ntopng ntopng[216576]: 05/Aug/2024 08:07:54 [housekeeping.lua:37] [lists_utils.lua:679] List 'Stratosphere Lab' has 0 rules. Please report this to https://github.com/ntop/ntopng
Aug 05 08:07:54 ntopng ntopng[216576]: 05/Aug/2024 08:07:54 [housekeeping.lua:37] [lists_utils.lua:753] Category Lists (7710 hosts, 1448 IPs, 0 JA3) loaded in 1 sec
Aug 05 11:10:10 ntopng ntopng[216576]: 05/Aug/2024 11:10:10 [NetworkInterface.cpp:2463] Packets exceeding the expected max size have been received [len: 2032][max len: 1518].
Aug 05 11:10:10 ntopng ntopng[216576]: 05/Aug/2024 11:10:10 [NetworkInterface.cpp:2470] WARNING: If TSO/GRO is enabled, please disable it for best accuracy
Aug 05 11:10:10 ntopng ntopng[216576]: 05/Aug/2024 11:10:10 [NetworkInterface.cpp:2470] WARNING: If TSO/GRO is enabled, please disable it for best accuracy
Aug 05 11:10:10 ntopng ntopng[216576]: 05/Aug/2024 11:10:10 [NetworkInterface.cpp:2475] WARNING: using: sudo ethtool -K ens22 gro off gso off tso off
Aug 05 11:10:10 ntopng ntopng[216576]: 05/Aug/2024 11:10:10 [NetworkInterface.cpp:2475] WARNING: using: sudo ethtool -K ens22 gro off gso off tso off
Aug 06 00:00:31 ntopng ntopng[216576]: 06/Aug/2024 00:00:31 [housekeeping.lua:37] [lists_utils.lua:417] Updating list 'Abuse.ch URLhaus' [https://urlhaus.abuse.ch/downloads/hostfile/]... OK
Aug 06 00:00:31 ntopng ntopng[216576]: 06/Aug/2024 00:00:31 [housekeeping.lua:37] [lists_utils.lua:417] Updating list 'Emerging Threats' [https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt]... OK
Aug 06 00:00:31 ntopng ntopng[216576]: 06/Aug/2024 00:00:31 [housekeeping.lua:37] [lists_utils.lua:417] Updating list 'NoCoin Filter List' [https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt]... OK
Aug 06 00:00:31 ntopng ntopng[216576]: 06/Aug/2024 00:00:31 [housekeeping.lua:37] [lists_utils.lua:417] Updating list 'SSLBL Botnet C2 IP Blacklist' [https://sslbl.abuse.ch/blacklist/sslipblacklist.txt]... OK
Aug 06 00:00:32 ntopng ntopng[216576]: 06/Aug/2024 00:00:32 [housekeeping.lua:37] [lists_utils.lua:417] Updating list 'Stratosphere Lab' [https://mcfp.felk.cvut.cz/publicDatasets/CTU-AIPP-BlackList/Todays-Blacklists/AIP_historical_blacklist_prioritized_by_newest_at>
Aug 06 00:00:33 ntopng ntopng[216576]: 06/Aug/2024 00:00:33 [housekeeping.lua:37] [lists_utils.lua:417] Updating list 'ThreatFox' [https://threatfox.abuse.ch/downloads/hostfile/]... OK
Aug 06 00:00:33 ntopng ntopng[216576]: 06/Aug/2024 00:00:33 [housekeeping.lua:37] [lists_utils.lua:417] Updating list 'dshield 7 days' [https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/dshield_7d.netset]... OK
Aug 06 00:00:35 ntopng ntopng[216576]: 06/Aug/2024 00:00:35 [housekeeping.lua:37] [lists_utils.lua:679] List 'Stratosphere Lab' has 0 rules. Please report this to https://github.com/ntop/ntopng
Aug 06 00:00:35 ntopng ntopng[216576]: 06/Aug/2024 00:00:35 [housekeeping.lua:37] [lists_utils.lua:753] Category Lists (7694 hosts, 1461 IPs, 0 JA3) loaded in 2 sec
Aug 06 00:01:35 ntopng ntopng[216576]: 06/Aug/2024 00:01:35 [fetch_blog_feed.lua:15] [blog_utils.lua:125] Fetching latest ntop blog posts...

------------

**Comment by cardigliano** [comment]
This seems to be working in 6.1. A stable update (6.2) is under testing and will be released this week.

**Comment by MatteoBiscosi** [comment]
The update has been release, please let us know with the latest version if you still have this issue

**Comment by p27182** [comment]
> The update has been release, please let us know with the latest version if you still have this issue

I have updated and it still  doesnt seem to be working, also my discord alerts seemed to have stopped working as well.  I am troubleshooting now.  I also notice that for some reason the pulldown menu for script path seems to list items twice? 
![image](https://github.com/user-attachments/assets/521499ff-7012-4812-a4e1-563bb3335a0d)

also, potentially another unrelated issue with the update to 6.2, but when I run `ntopng --version` I get hundreds of lines of output that include:
```Cannot adopt OID in UCD-SNMP-MIB: laIndex ::= { laEntry 1 }
Cannot adopt OID in UCD-SNMP-MIB: laNames ::= { laEntry 2 }
Cannot adopt OID in UCD-SNMP-MIB: laLoad ::= { laEntry 3 }
Cannot adopt OID in UCD-SNMP-MIB: laConfig ::= { laEntry 4 }
Cannot adopt OID in UCD-SNMP-MIB: laLoadInt ::= { laEntry 5 }
Cannot adopt OID in UCD-SNMP-MIB: laLoadFloat ::= { laEntry 6 }
Cannot adopt OID in UCD-SNMP-MIB: laErrorFlag ::= { laEntry 100 }
Cannot adopt OID in UCD-SNMP-MIB: laErrMessage ::= { laEntry 101 }
Cannot adopt OID in NET-SNMP-AGENT-MIB: nsNotifyRestart ::= { netSnmpNotifications 3 }
Cannot adopt OID in NET-SNMP-AGENT-MIB: nsNotifyShutdown ::= { netSnmpNotifications 2 }
Cannot adopt OID in NET-SNMP-AGENT-MIB: nsNotifyStart ::= { netSnmpNotifications 1 }
```

**Comment by cardigliano** [comment]
We probably need to debug this together as it is working for us. Are you available next week for a call? Please drop un an email (cardigliano at ntop.org).
As of the last issue, we already pushed a fix (see https://github.com/ntop/ntopng/issues/8625)

**Comment by MatteoBiscosi** [comment]
The issue seems fixed, in case it is not please reopen the ticket

**Comment by p27182** [comment]
Sorry for not getting to this, I moved and that whole lab is basically on
hold till its relocated.   I really appreciate your response though!
