### ISSUE TITLE
Trigger an Alert when an Exporter is Unresponsive 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8608]
This is to request the implementation of an alert when a flow exporter is unresponsive (either not sending events or flows)

**Comment by cardigliano** [comment]
Created new no_exporter_activity alert and check definition in b09688beeef08c89d51af1cfa6cffe474b151ae4
this can be triggered in scripts/lua/modules/check_definitions/interface/no_exporter_activity.lua

**Comment by lucaderi** [comment]
Verified as fixed
