### ISSUE TITLE
View Interfaces fail to show data in "Top Applications" underneath the "Traffic RX/TX" graph

### ISSUE THREAD

**Issue by lmartin-spsd** [ntop/ntopng#8610]
**Environment**:
* OS name: Ubuntu
* OS version:  22.04.4 LTS
* Architecture: amd64
* ntopng version/revision: ntopng Enterprise XL v.6.1.240806

**What happened**:
(Image 1) I use view interfaces to combine RSS Queues into one interface for monitoring.
(Image 2) If you go to look at the last 30 minutes in the graph for Traffic Rx/Tx, the "Top Applications" section at the bottom is empty (was not always the case, this seems "recent").
(Image 3) If you check the Apps section of the view interface, it shows Apps related data so I feel like the data is being collected at the very least even if not appropriately displayed in other places.
(Image 4) If you go to view the Traffic Rx/TX graph of one  of the interfaces that the view interface is composed of, it shows the "Top Applications" section correctly.

**How did you reproduce it?**
Run ntopng with view interfaces.

**Debug Information**:

![image](https://github.com/user-attachments/assets/e170efcd-9180-43c1-a043-f6b579c17982)
![image](https://github.com/user-attachments/assets/4687a0ca-dd39-4967-bd93-f705c42fad11)
![image](https://github.com/user-attachments/assets/83ba1063-5127-42d7-a975-455db245a9c8)
![image](https://github.com/user-attachments/assets/fef9728a-1515-48b3-b8da-b7b379c7e3bd)

**Comment by MatteoBiscosi** [comment]
The issue should now be fixed
![image](https://github.com/user-attachments/assets/d08fd99c-4094-4697-9eb9-ff93d723ef3a)

**Comment by lmartin-spsd** [comment]
Confirmed working here. Leaving open in case there are any additional checks needed. If my confirmation was all that was lacking then please close the issue.

**Comment by lucaderi** [comment]
Verified as fixed, closing it for now (you can reopen it if necessary)
