### ISSUE TITLE
JA4 Broken in Flow Details

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8611]
<img width="1142" alt="Screenshot 2024-08-07 at 23 01 49" src="https://github.com/user-attachments/assets/ce65d1bc-0aba-4341-bebb-3e61d7b1714e">

**Comment by MatteoBiscosi** [comment]
Tried with many pcaps but seems working, is it possible to have a pcap with the problematic ja4 ?
![image](https://github.com/user-attachments/assets/5e0b37ac-4f36-454a-a7e2-d0aa2c39cb7d)

**Comment by MatteoBiscosi** [comment]
It seems fixed, in case the issue happens again please reopen the ticket
