### ISSUE TITLE
Update Historical Flows and Add Mitre Att&ck/nDPI Information

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8613]
Wrong
![image](https://github.com/user-attachments/assets/d5a45e08-7f66-44ec-bdc0-2204c3478de1)

Good
<img width="890" alt="Screenshot 2024-08-08 at 10 29 23" src="https://github.com/user-attachments/assets/71e1684b-35e5-44bf-be2c-8cc60c681ca1">

**Comment by cardigliano** [comment]
Implemented in 5398e9d88842c3ae9f752222e50e93995ad36c54

**Comment by lucaderi** [comment]
Implemented in https://github.com/ntop/ntopng/commit/d7873670dd19f072f336c79924db3ce146a92442
