### ISSUE TITLE
Missing Exporter Interfaces in Sankey

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8615]
<img width="1128" alt="Screenshot 2024-08-08 at 10 32 38" src="https://github.com/user-attachments/assets/a4d192de-72ef-4e52-a03c-9af1b02f151e">

**Comment by MatteoBiscosi** [comment]
Added these info as ports
![image](https://github.com/user-attachments/assets/a7fa5976-8b49-41cd-9278-f63523c69d24)

**Comment by MatteoBiscosi** [comment]
Implemented as requested
