### ISSUE TITLE
Invalid Alerts Number Reported

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8619]
Clicking on the link below
<img width="1339" alt="image" src="https://github.com/user-attachments/assets/faca4901-cf34-4713-8aaa-b857c92edb65">

brings to two empty pages.
<img width="1356" alt="Screenshot 2024-08-08 at 18 02 40" src="https://github.com/user-attachments/assets/f3dd25cd-a2f9-4a63-a3bc-0444176f6547">
<img width="1372" alt="Screenshot 2024-08-08 at 18 02 30" src="https://github.com/user-attachments/assets/3794e897-d364-41b5-8781-dad29e3c85fa">

**Comment by cardigliano** [comment]
Fix provided in 1ddc1ab77a2dda06c5d5a50203947c32a2380efd d944725bbb0ae2e2408c0c7f40937ea09c500e01

**Comment by lucaderi** [comment]
Verified as fixed
