### ISSUE TITLE
All Hosts page is always empty

### ISSUE THREAD

**Issue by epodberezkin** [ntop/ntopng#862]
Page /lua/hosts_stats.lua always shows "No Results Found", but there are >7K hosts. All other pages returns correct info (network_stats, top_hosts, host_details etc.)

**Comment by epodberezkin** [comment]
Version	2.5.161219 - Community Edition
Built on	Ubuntu 16.04.1 LTS

**Comment by simonemainardi** [comment]
@podber please update ntopng to its latest dev version and it will work

**Comment by epodberezkin** [comment]
Thanks, it works.
