### ISSUE TITLE
DSCP Selector dropdown no longer renders while viewing active flows

### ISSUE THREAD

**Issue by RobertTheProfessional** [ntop/ntopng#8624]
**Environment**:
* OS name: opnsense
* OS version: FreeBSD 14.1
* Architecture: amd64
* ntopng version/revision: v.6.3.240813

**What happened**:

After upgrading from ntopng 6.0 Community, the DSCP Selector dropdown no longer renders while viewing active flows. Yet, when an integer value for a DSCP tag (CS4==32 or CS5==40) is provided as a query parameter in the URL as such `https://ntopng/lua/flows_stats.lua?flowhosts_type=&...&dscp=32`, the flows are correctly filtered by their DSCP value similar to ntopng 6.0 behavior.

**How did you reproduce it?**

https://github.com/ntop/ntopng/blob/9a35ae52a1976b4df9c8eecd039dfac8ef7371ba/scripts/lua/flows_stats.lua#L190-L192

https://github.com/ntop/ntopng/blob/9a35ae52a1976b4df9c8eecd039dfac8ef7371ba/scripts/lua/flows_stats.lua#L293

https://github.com/ntop/ntopng/blob/9a35ae52a1976b4df9c8eecd039dfac8ef7371ba/scripts/lua/modules/flow_utils.lua#L2474-L2482

**Debug Information**:

<img width="1066" alt="image" src="https://github.com/user-attachments/assets/b5354b15-3db8-4ad1-9e78-0d1fa3737cab">

**Comment by MatteoBiscosi** [comment]
the issue should now be fixed, in a couple of hours update and let me know

**Comment by RobertTheProfessional** [comment]
Just tried out the `flow_filter.lua` patch. My DSCP tags are reported in the dropdown and able to be filtered again.

![image](https://github.com/user-attachments/assets/44890dfa-17bd-408b-9680-6c96ad969e7e)
