### ISSUE TITLE
Timeseries not working

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#8629]
Host alert -> Host page -> Host timeseries.

The timeseries is not showing data in every possible entry, only some dropdown entries work

<img width="1786" alt="Screenshot 2024-08-17 at 9 14 48 AM" src="https://github.com/user-attachments/assets/56384e18-db63-4038-8d29-64c64957f8ee">

<img width="2134" alt="Screenshot 2024-08-17 at 9 14 30 AM" src="https://github.com/user-attachments/assets/87b8a8a3-fecc-4dbc-8284-cc655ca38684">

**Comment by sulaimansuhas** [comment]
@DGabri What drop downs are not working specifically? If there is no data for a particular dropdown then it makes sense to not have any time series data show up right. Looking at my host time series, I see no results for TCP or UDP packets which is weird. I am wondering if there any other more specific drop down selections not working.

**Comment by MatteoBiscosi** [comment]
Verified as fixed
