### ISSUE TITLE
Why is not the Geo map work?

### ISSUE THREAD

**Issue by wayneshow** [ntop/ntopng#863]
I have added my google api key into the field "Google APIs Browser Key" of Preferences, but the page of "geo map"is not working as before! What should I set next?

**Comment by simonemainardi** [comment]
I've just tried to reproduce and it looks like is working:

![image](https://cloud.githubusercontent.com/assets/3397663/21356187/fa4320e0-c6d0-11e6-8612-cec761a1f51f.png)

please be more specific in reporting the issue. What do you get? If you right-click on the browser and select 'inspect element', do you see any errors?

**Comment by wayneshow** [comment]
By clicking F12, I found that because our network can not access Google Maps. Thank you!
