### ISSUE TITLE
Alerts Filter not working

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#8630]
The filter for alerts page is not working.

Steps to reproduce: 
1. Go to host alert page
2. Select last week
3. Select a specific alert type to filter results on
4. Zoom on a specific time window in the histogram chart until no alerts are shown
5. Select last week or another timeframe from the dropdown
6. The filter is selected but results are not filtered

The first image is what can be seen at step 4. The last image is after step 5 and 6

<img width="1857" alt="Screenshot 2024-08-17 at 9 22 39 AM" src="https://github.com/user-attachments/assets/cdf3d3a6-ded6-485e-b234-f76069cdc3f0">

<img width="1099" alt="Screenshot 2024-08-17 at 9 22 48 AM" src="https://github.com/user-attachments/assets/bc15286b-59df-4df2-85ce-62d636b5142c">

**Comment by cardigliano** [comment]
@DGabri could you check wether "Score Threshold Exceeded" is a secondary/additional alert for those records?

**Comment by DGabri** [comment]
This was the case. Closing this ticket

**Comment by cardigliano** [comment]
I suggest to rename the Alert column into Main Alert
