### ISSUE TITLE
Network Discovery not being executed

### ISSUE THREAD

**Issue by fimmezwansch** [ntop/ntopng#8635]
**Environment**:
* OS name: Ubuntu 
* OS version: 22.0.4.4 LTS
* Architecture: amd64
* ntopng version/revision: 6.2.240814 Community Edition
**What happened**: Update from prev. Version to 6.2.240814

Since last update to current version Network Discovery is no longer working. There is a Error message "Network Discovery is Disabled, Please Enable it in Preferences ".
It is enabled in preferences. Disabling an re-enabling has no effect too. 
In all other previous versions Network Discovery was working fine over the years.

**Comment by MatteoBiscosi** [comment]
Could you please share a couple of screenshots to understand the issue? Cause right now i'm unable to reproduce the same behavior

**Comment by fimmezwansch** [comment]
Yes, here are two relevant screen shots, please.

![Screenshot 2024-08-19 175035](https://github.com/user-attachments/assets/e4671d51-3eca-40da-b7c2-3a7797bcb437)
![Screenshot 2024-08-19 175124](https://github.com/user-attachments/assets/220f472f-2418-49f2-bc42-60809ab81182)

**Comment by fimmezwansch** [comment]
Just updated from 6.2.240814 to version 6.2.2408**19**, the same behaviour.

**Comment by fimmezwansch** [comment]
Just updated from 6.2.240819 to version 6.2.240821, still the same behaviour.

**Comment by fimmezwansch** [comment]
Just updated to version 6.2.240822. After Update I saw still "Network Discovery is Disabled...". Network Discovery was still enabled in preferences. My next step was to enable "Active Monitoring". After that Network Discovery did work again. I did not expect, that Active Monitoring has effect to Network Discovery. 
Have settings been accidentally mixed?

**Comment by MatteoBiscosi** [comment]
Settings are now correct, the issue is that the network discovery seems to not be running 
![image](https://github.com/user-attachments/assets/17ca697a-0016-407a-b785-659c5ec1ff80)

**Comment by MatteoBiscosi** [comment]
The issue should now be fixed

**Comment by fimmezwansch** [comment]
Thanks a lot, Matteo, great Job!
Now we have under Preferences -> Active Monitoring two Settings: Active Monitoring and Network Discovery to enable.
Under Preferences -> Network Discovery we have the settings for consecutive discoveries.
Perhaps for some users it would be better if we could find enabling Network Discovery under Preferences -> Network Discovery instead of Preferences -> Active Monitoring.
But however, that's just an idea.

Kind regards
Roland

**Comment by MatteoBiscosi** [comment]
The issue seems fixed, in case it is not please reopen the ticket
