### ISSUE TITLE
Ntopng offline mode and cloud

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#8642]
Ntopng should respect configured --offline mode in internal checks.

19/Aug/2024 09:03:08 [LuaEngine.cpp:1499] WARNING: Script failure [/usr/share/ntopng/scripts/lua/if_stats.lua] Script failure [/usr/share/ntopng/scripts/lua/if_stats.lua][/usr/share/ntopng/scripts/lua/if_stats.lua:711: attempt to call a nil value (field 'isCloud')]

**Comment by cardigliano** [comment]
Fixed, a new update will be available shortly
