### ISSUE TITLE
Flow dropped due to limits to the license

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#8643]
Environment:
Ubuntu 22.04
ntopng 6.2.240814
Enterprise XL license installed.

#8626 
After upgrading to 6.2 ntopng show license error on start:
15/Aug/2024 12:56:58 [ParserInterface.cpp:104] Flow dropped due to limits to the license. Exporters limit: 32 | Exporters Interfaces limit: 2048

![image](https://github.com/user-attachments/assets/a2c39e43-d870-4fea-95f3-e849f77d3168)

We have 30 nprobes, connected to ntopng, license limit 32.

![image](https://github.com/user-attachments/assets/1d79ea56-9acb-4329-bf86-52f67ab374ce)

We have 94 netflow exporters, license limit 2048.

![image](https://github.com/user-attachments/assets/04f6de6f-cd3d-43c6-ac74-679f0ca141f3)

What's wrong?

**Comment by lucaderi** [comment]
You have 94 exporters and your license limit is 32. You need to start multiple ntopng on the same host or use a more capable license for putting everything in the same ntopng.
