### ISSUE TITLE
Add option to disable nprobes / exporters chart

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#8644]
Add option in settings to disable nprobe's chart.
It's impossible to read anything on large networks.

![image](https://github.com/user-attachments/assets/ee43acfc-19fb-4796-8e41-c434a371a847)

**Comment by lucaderi** [comment]
This is a bug that needs to be fixed. Removing the chart is not a solution. Please get in touch with me directly (deri@ntop.org) for solving this issue.

**Comment by MatteoBiscosi** [comment]
The issue should be addressed, in case the issue persists please reopen the ticket
