### ISSUE TITLE
Sorting not working in flow exporters table

### ISSUE THREAD

**Issue by atemix** [ntop/ntopng#8645]
Environment:
Ubuntu 22.04
ntopng 6.2.240814

Sorting not working in flow exporters table.

![image](https://github.com/user-attachments/assets/8c20dccb-12f2-4ee7-bb74-af58d6cae4d6)

**Comment by DGabri** [comment]
@atemix Fixed this on the 6.2-stable branch

**Comment by DGabri** [comment]
Verified as fixed
