### ISSUE TITLE
Invalid Host Filter when Clicking on ASN 0

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8651]
<img width="412" alt="image" src="https://github.com/user-attachments/assets/29d48111-a300-41fe-a2e9-e9fd0cadaf74">

**Comment by MatteoBiscosi** [comment]
the issue should now be fixed
![image](https://github.com/user-attachments/assets/9176e586-4c2e-4e1a-a061-377d2cf2e63e)
![image](https://github.com/user-attachments/assets/d93d3816-a4f0-42ac-9965-74cdd7484fe4)
