### ISSUE TITLE
Extra rows shown when they should not be

### ISSUE THREAD

**Issue by mzac** [ntop/ntopng#8654]
**Environment**:
* OS name: Ubuntu
* OS version: 22.04.4
* Architecture: amd64
* ntopng version/revision: 6.2.240821

**What happened**:
When viewing a table on either flows, aggregated, or any other table that has less data than the selected number of rows, empty rows are shown below the data.

**How did you reproduce it?**
Look at any table that has small data and choose more rows in the upper right

**Debug Information**:
This shows empty rows below the valid data (under STUN)

![image](https://github.com/user-attachments/assets/7b6f35d1-773a-4ef5-9667-68811f8a8228)

**Comment by DGabri** [comment]
Thanks for the heads up, this is a style configuration, you are not missing any data, almost all tables have been ported to the new version which enables to display a predefined number of rows even if data is less than the total number of rows, I will fix this

**Comment by DGabri** [comment]
We discussed with the team and empty rows will be shown to keep UI uniform across pages. Closing ticket
