### ISSUE TITLE
ASN info

### ISSUE THREAD

**Issue by infinitynet2011** [ntop/ntopng#8655]
Hello,

If I look at this print screen, I do not know what ASN is about. 
It would be nice to have that information displayed somewhere.

If I send that printscreen to someone, I must put a note about the ASN ...  

![image](https://github.com/user-attachments/assets/f446e918-1efa-43eb-b58a-e9caa8c13a0d)

Thank you,
Gabriel

**Comment by DGabri** [comment]
Hi, thanks for the feedback, I fixed it putting ASN: number (name). If you click on this you will be redirected to the hosts page filtered by ASN

<img width="1188" alt="Screenshot 2024-08-22 at 3 38 38 PM" src="https://github.com/user-attachments/assets/3404a265-ecc7-44f4-b9f2-31b8f6ead285">

<img width="767" alt="Screenshot 2024-08-22 at 3 59 47 PM" src="https://github.com/user-attachments/assets/57a8998d-fd91-4ee2-9b54-c75d5b8c816a">

**Comment by DGabri** [comment]
@MatteoBiscosi In the timeseries chart, please add which ASN data it is so if multiple timeseries are compared it is possible to distinguish which asn generated traffic

**Comment by infinitynet2011** [comment]
Hello!

![image](https://github.com/user-attachments/assets/76f117b8-12e4-4be1-bb36-4b86d3ff2034)


I dont have the today graph.

Thanks,
Gabriel

**Comment by DGabri** [comment]
Hi, could please check if you have some errors in the console of the browser or in the network tab?
On my side it is showing the table. You are saying that the table under the chart is not rendering? The graph seems normal.

Thanks

**Comment by infinitynet2011** [comment]
Hi DGabri

Now i have after I enable **Interfaces Timeseries** / Traffic /  Toggle the creation of bytes and packets timeseries. 
But was not enabled before.

![image](https://github.com/user-attachments/assets/4f610250-e045-475a-a271-0d70a3f1a17f)


Thanks,

**Comment by infinitynet2011** [comment]
Hello!


Another thing that i think need your attention.

![image](https://github.com/user-attachments/assets/e228faee-e90b-4d63-afa2-0a818cca2eca)


Thank you,
Gabriel

**Comment by DGabri** [comment]
@MatteoBiscosi please check this timeseries problem

**Comment by MatteoBiscosi** [comment]
Hi @infinitynet2011 the issue should now be fixed, it was due to problems with approximation and the large timeframe that timeseries uses.

**Comment by MatteoBiscosi** [comment]
The issue seems fixed, in case it is not please reopen the ticket
