### ISSUE TITLE
sFlow Stats Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8657]
<img width="1378" alt="image" src="https://github.com/user-attachments/assets/d838d237-1c02-45c0-b1be-0b9ca95aa735">
Wrong IP address reported. It should be 192.168.65.82
https://github.com/user-attachments/files/16710983/sflow.pcap.zip

**Comment by MatteoBiscosi** [comment]
Same as #6858 
Now (see the other ticket) the probe is correctly reported (being my local machine ...2.225) and the IP is correct, being report in the pcap as Agent Address:
Specifies an IP address in IPv4 format (x.x.x.x), where x is a decimal number from 0 to 255, or IPv6 format (xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx), where x is a hexadecimal number from 0 to F. The agent address is used to identify the switch in all sFlow datagrams sent to sFlow collectors. It is usually set to an IP address on the switch that is reachable from an sFlow collector.
![image](https://github.com/user-attachments/assets/ea3e7d1e-81f4-42c9-98a5-06f3e18d9e5d)

**Comment by MatteoBiscosi** [comment]
Verified as fixed
