### ISSUE TITLE
sFlow Interface State Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8658]
<img width="1378" alt="image" src="https://github.com/user-attachments/assets/60b9235b-2f76-4ee0-9905-dacc8dfa8f23">

Not all fields are populated even though sFlow reported the data.

As this is a sFlow export, it would be nice to
- read it somewhere
- remove the Flow/SNMP ratio that is meaningful only on NetFlow.IPFIX
- 
Use the pcap in #8657 to reproduce it.

**Comment by MatteoBiscosi** [comment]
The data are now correct, being an sflow counters exporter.
However the nprobe is still seen in the page (that's in my pov the right course).
![image](https://github.com/user-attachments/assets/37caa0a2-996d-4378-b08d-26a2a6820e64)
![image](https://github.com/user-attachments/assets/37b44b35-11b6-45e3-a1b5-a05abb6e0b45)

**Comment by MatteoBiscosi** [comment]
The issue seems fixed, in case it is not please reopen the ticket
