### ISSUE TITLE
BUG "hosts_stats.lua" when sort by column "Traffic"

### ISSUE THREAD

**Issue by itnas-s** [ntop/ntopng#866]
Hi ntop developer
sorry for my poor english

My OS is Ubuntu 14.04 and ntopng is nightly builds 2.5.161222
When select "Hosts" "hosts_status.lua" and sort by "Traffic". It show "No Results Found"

This BUG are happen in "local_hosts_stats.lua" and "hosts_stats.lua". Other menu are no problem I can sort by column "Traffic"

This BUG happen in nightly builds / in stable no problem

Regards

**Comment by simonemainardi** [comment]
thanks for reporting. The issue has been fixed. New packages will be available tomorrow.
