### ISSUE TITLE
Create Flow Exporters Interfaces Page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8661]
Under Flow Exporters page add a new entry called Interfaces
<img width="518" alt="Screenshot 2024-08-22 at 16 37 20" src="https://github.com/user-attachments/assets/99cf5b4b-ade3-4f31-b8e9-72334de6f37e">

On that page you need to display one table (no sankey) containing

nprobe IP | Exporter IP | Interface Id | In Bytes | Out Bytes

**Comment by sulaimansuhas** [comment]
Hey @lucaderi  can you tell me where I can find this page or how I can activate it? I can't seem to find it on my ntopng localhost.

**Comment by MatteoBiscosi** [comment]
Implemented as requested
![image](https://github.com/user-attachments/assets/b3ab5e74-fe9c-4e68-a622-2e74387c7925)
