### ISSUE TITLE
Exporters Sankey Chart Broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8662]
<img width="1693" alt="image" src="https://github.com/user-attachments/assets/5ed5bf16-1ea2-4e16-9207-1d56275946b2">

**Comment by lucaderi** [comment]
![image](https://github.com/user-attachments/assets/ea7655fe-21e6-43b7-b990-2d1fa92f6610)

**Comment by lucaderi** [comment]
<img width="1053" alt="Screenshot 2024-08-29 at 17 02 09" src="https://github.com/user-attachments/assets/426281cf-fef0-4320-b43b-f9786507e263">

Unfortunately, the fix isn't working. You can reproduce with
- ntopng -i tcp://127.0.0.1:1234
- nprobe -3 2068 --zmq tcp://127.0.0.1:1234 -t 10 -s 10 -d 10 --zmq-simulate-exporters 64

Send to nprobe a few flows and the bug will show up

**Comment by Westy-87** [comment]
This appears to be working correctly after update this morning.

ntopng Enterprise L v.6.2.240904 rev.24422 (Ubuntu 20.04.6 LTS)

**Comment by MatteoBiscosi** [comment]
Hi @Westy-87 thanks for your report
