### ISSUE TITLE
Empty client.ip and server.ip

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8664]
After ntopng was upgraded to 6.2, exporting to elasticsearch no longer displays client.ip and server.ip, always 0.0.0.0

**Comment by sulaimansuhas** [comment]
@MatteoBiscosi Do you mind if I also have a look at this?

**Comment by sulaimansuhas** [comment]
We can mark this as closed?

**Comment by MatteoBiscosi** [comment]
The issue seems fixed, in case it is not please reopen the ticket
