### ISSUE TITLE
ERR_CONNECTION_REFUSED - This site can’t be reached

### ISSUE THREAD

**Issue by infinitynet2011** [ntop/ntopng#8665]
[root@ntopng]# **sudo systemctl status ntopng**
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
     Loaded: loaded (/usr/lib/systemd/system/ntopng.service; enabled; preset: disabled)
     Active: active (running) since Fri 2024-08-23 01:20:34 EEST; 2min 36s ago
    Process: 8453 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exited, status=0/SUCCESS)
    Process: 8467 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
    Process: 8469 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (code=exited, status=0/SUCCESS)
    Process: 8471 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /run/ntopng.conf (code=exited, status=0/SUCCESS)
   Main PID: 8474 (ntopng)
      Tasks: 2 (limit: 48978)
     Memory: 23.4M
        CPU: 2min 35.542s
     CGroup: /system.slice/ntopng.service
             └─8474 /usr/bin/ntopng /run/ntopng.conf

Aug 23 01:20:34 ntopng systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
Aug 23 01:20:34 ntopng systemd[1]: Started ntopng high-speed web-based traffic monitoring and analysis tool.
Aug 23 01:20:34 ntopng ntopng[8474]: 23/Aug/2024 01:20:34 [Redis.cpp:166] Successfully connected to redis 127.0.0.1:6379@0
Aug 23 01:20:34 ntopng ntopng[8474]: 23/Aug/2024 01:20:34 [Redis.cpp:166] Successfully connected to redis 127.0.0.1:6379@0
Aug 23 01:20:34 ntopng ntopng[8474]: 23/Aug/2024 01:20:34 [NtopCloud.cpp:131] Successfully connected to ntop cloud
Aug 23 01:20:35 ntopng ntopng[8474]: 23/Aug/2024 01:20:35 [NtopCloud.cpp:145] Successfully registered with the cloud
Aug 23 01:20:35 ntopng ntopng[8474]: 23/Aug/2024 01:20:35 [NtopCloud.cpp:146] Unique id ntop/4606798171/L68C03416B2076B27--U68C034166376FC9F--OL/ntopng/8474
Aug 23 01:20:35 ntopng ntopng[8474]: 23/Aug/2024 01:20:35 [NtopPro.cpp:348] [LICENSE] Reading license from /etc/ntopng.license
Aug 23 01:20:35 ntopng ntopng[8474]: 23/Aug/2024 01:20:35 [NtopPro.cpp:506] [LICENSE] /etc/ntopng.license: found valid Enterprise M license
[root@ntopng]# 

[root@ntopng]# **sudo /usr/bin/ntopng --http-port=3000 --https-port=443 --verbose=5**
23/Aug/2024 01:05:36 [Ntop.cpp:3673] Added Local Network 127.0.0.0/8
23/Aug/2024 01:05:36 [Ntop.cpp:3704] Added network 127.0.0.0/8
23/Aug/2024 01:05:36 [Ntop.cpp:3673] Added Local Network fe80::/10
23/Aug/2024 01:05:36 [Ntop.cpp:3704] Added network fe80::/10
23/Aug/2024 01:05:36 [Redis.cpp:166] Successfully connected to redis 127.0.0.1:6379@0
23/Aug/2024 01:05:36 [Redis.cpp:166] Successfully connected to redis 127.0.0.1:6379@0
23/Aug/2024 01:05:37 [NtopCloud.cpp:131] Successfully connected to ntop cloud
23/Aug/2024 01:05:37 [NtopCloud.cpp:145] Successfully registered with the cloud
23/Aug/2024 01:05:37 [NtopCloud.cpp:146] Unique id ntop/4606798171/L68C03416B2076B27--U68C034166376FC9F--OL/ntopng/7451
23/Aug/2024 01:05:37 [NtopPro.cpp:348] [LICENSE] Reading license from /etc/ntopng.license
23/Aug/2024 01:05:37 [NtopPro.cpp:506] [LICENSE] /etc/ntopng.license: found valid Enterprise M license
23/Aug/2024 01:05:37 [NetworkInterface.cpp:445] Successfully loaded /usr/share/ndpi/public_suffix_list.dat
23/Aug/2024 01:05:37 [ntoppro_defines.h:105] Max profiles number: 128
23/Aug/2024 01:05:37 [ntoppro_defines.h:74] Max host pools number: 128
23/Aug/2024 01:05:37 [HostPools.cpp:79] Host Pools Available: 128
23/Aug/2024 01:05:37 [ntoppro_defines.h:147] Max nw interfaces number: 16
23/Aug/2024 01:05:37 [Ntop.cpp:520] Interfaces Available: 16
23/Aug/2024 01:05:37 [LuaEngine.cpp:687] Running /usr/share/ntopng/scripts/callbacks/system/boot.lua
*   Trying 140.82.121.4:443...
* Connected to github.com (140.82.121.4) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=github.com
*  start date: Mar  7 00:00:00 2024 GMT
*  expire date: Mar  7 23:59:59 2025 GMT
*  subjectAltName: host "github.com" matched cert's "github.com"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo ECC Domain Validation Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x174c0e0)
> GET / HTTP/2
Host: github.com
user-agent: ntopng 6.3.240822/x86_64/Rocky Linux release 9.3
accept: */*

* old SSL session ID is stale, removing
< HTTP/2 200 
< server: GitHub.com
< date: Thu, 22 Aug 2024 22:05:35 GMT
< content-type: text/html; charset=utf-8
< vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Language, Accept-Encoding, Accept, X-Requested-With
< content-language: en-US
< etag: W/"d2ce7d2dad4672116d48c92fd47bf46c"
< cache-control: max-age=0, private, must-revalidate
< strict-transport-security: max-age=31536000; includeSubdomains; preload
< x-frame-options: deny
< x-content-type-options: nosniff
< x-xss-protection: 0
< referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
< content-security-policy: default-src 'none'; base-uri 'self'; child-src github.com/assets-cdn/worker/ github.com/webpack/ github.com/assets/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com www.githubstatus.com collector.github.com raw.githubusercontent.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com *.rel.tunnels.api.visualstudio.com wss://*.rel.tunnels.api.visualstudio.com api.githubcopilot.com objects-origin.githubusercontent.com copilot-proxy.githubusercontent.com/v1/engines/github-completion/completions proxy.enterprise.githubcopilot.com/v1/engines/github-completion/completions *.actions.githubusercontent.com wss://*.actions.githubusercontent.com productionresultssa0.blob.core.windows.net/ productionresultssa1.blob.core.windows.net/ productionresultssa2.blob.core.windows.net/ productionresultssa3.blob.core.windows.net/ productionresultssa4.blob.core.windows.net/ productionresultssa5.blob.core.windows.net/ productionresultssa6.blob.core.windows.net/ productionresultssa7.blob.core.windows.net/ productionresultssa8.blob.core.windows.net/ productionresultssa9.blob.core.windows.net/ productionresultssa10.blob.core.windows.net/ productionresultssa11.blob.core.windows.net/ productionresultssa12.blob.core.windows.net/ productionresultssa13.blob.core.windows.net/ productionresultssa14.blob.core.windows.net/ productionresultssa15.blob.core.windows.net/ productionresultssa16.blob.core.windows.net/ productionresultssa17.blob.core.windows.net/ productionresultssa18.blob.core.windows.net/ productionresultssa19.blob.core.windows.net/ github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com wss://alive.github.com github.githubassets.com edge.fullstory.com rs.fullstory.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com copilot-workspace.githubnext.com objects-origin.githubusercontent.com; frame-ancestors 'none'; frame-src viewscreen.githubusercontent.com notebooks.githubusercontent.com www.youtube-nocookie.com; img-src 'self' data: blob: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com avatars.githubusercontent.com github-cloud.s3.amazonaws.com objects.githubusercontent.com secured-user-images.githubusercontent.com/ user-images.githubusercontent.com/ private-user-images.githubusercontent.com opengraph.githubassets.com github-production-user-asset-6210df.s3.amazonaws.com customer-stories-feed.github.com spotlights-feed.github.com objects-origin.githubusercontent.com *.githubusercontent.com; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/ secured-user-images.githubusercontent.com/ private-user-images.githubusercontent.com github-production-user-asset-6210df.s3.amazonaws.com gist.github.com github.githubassets.com; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; upgrade-insecure-requests; worker-src github.com/assets-cdn/worker/ github.com/webpack/ github.com/assets/ gist.github.com/assets-cdn/worker/
< set-cookie: _gh_sess=sKNu6fhb8aw%2BG20agckUULoci4vxMlr3yv%2FFeHxbt0vc8XxmvcN8WM3scDNWgdI2%2FLfxF7JDWHZwTXJf5WLENqN7XwyfbVN8LW5Tff67DGtcVXMWUROm4EaehW5mT1vDGmeaMbd3T8X8Tzv%2B7gEDz3BSO0lqvQnLym8j0f4PhgQAES2BvUTd3e0mIs098piWto%2BdpORLvzZbkefG%2FLQgbOI%2FIAc%2BdolX6KRdvOVAUo8MXqJ9yAwe4mcY%2BUeucEbQGCfLRfn%2FGKhJRoOYa7p%2BYg%3D%3D--p1jCMQqoPF6iqyls--8hX4702ZR7d70yvgd665hA%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax
< set-cookie: _octo=GH1.1.1221060599.1724364337; Path=/; Domain=github.com; Expires=Fri, 22 Aug 2025 22:05:37 GMT; Secure; SameSite=Lax
< set-cookie: logged_in=no; Path=/; Domain=github.com; Expires=Fri, 22 Aug 2025 22:05:37 GMT; HttpOnly; Secure; SameSite=Lax
< accept-ranges: bytes
< x-github-request-id: 8150:A41DE:DE5C33:E2F1E1:66C7B631
< 
* Connection #0 to host github.com left intact
23/Aug/2024 01:05:37 [Utils.cpp:1614] [NAMELOOKUP_TIME 0.03][CONNECT_TIME 0.07][APPCONNECT_TIME 0.14][PRETRANSFER_TIME 0.14][REDIRECT_TIME 0.00][STARTTRANSFER_TIME 0.17][TOTAL_TIME 0.31]
23/Aug/2024 01:05:37 [ntoppro_defines.h:89] Max host pool members number: 4294967295

[root@ntopng]# **sudo ss -tuln | grep ':8080\|:8443'**
[root@ntopng]# 
[root@ntopng]# **sudo lsof -i :3000**
[root@ntopng]# **sudo lsof -i :443**
[root@ntopng]# 

[root@ntopng]# **sestatus**
SELinux status:                 disabled

[root@ntopng]# **hostnamectl** 
 Static hostname: ntopng
       Icon name: computer-vm
         Chassis: vm 🖴
      Machine ID: 82d7500240064ad***
         Boot ID: 50bdb9ad1f22483b***
  Virtualization: vmware
Operating System: AlmaLinux 9.4 (Seafoam Ocelot)      
     CPE OS Name: cpe:/o:almalinux:almalinux:9::baseos
          Kernel: Linux 5.14.0-427.31.1.el9_4.x86_64
    Architecture: x86-64
 Hardware Vendor: VMware, Inc.
  Hardware Model: VMware20,1
Firmware Version: VMW201.00V*

[root@ntopng]# **ntopng --version**
Cannot bind for clientaddr: Address already in use
Version:        6.3.240822 [Enterprise/Professional build]
GIT rev:        dev:c84f982a5b8d9c5e0dfb4ab96b6acef7df27900a:20240822
Pro rev:        r6776
Built on:       Rocky Linux release 9.3
System Id:      L68C03416B2076B27--U68C034166376FC9F--OL
Platform:       x86_64
Edition:        Enterprise M
License Type:   Permanent
Maintenance:    Until Wed Jun 18 03:13:08 2025 [299 days left]
License:        osGDVB4nhgUUaBlUjaQ6le0P8q9iNFKnx7kxUVxZbiyewSXFzHSyBvxAAh/rYSNP79gZs
                uD3cGH2Z3oDzMtCXZaCzHZDW2ZPSTQSstjNBDOfKvPcO0zwzv4Wu5bJr3eHYPE/KpoOqe
                BMvch1rgvYirtvEOoAa7JCzmfvHoXKn+GZwIzbqzMTg***
License Hash:   A1BB1655D0AC4243B2C640E3***
[root@ntopng]# 

Thank you,
Gabriel

**Comment by infinitynet2011** [comment]
[root@ntopng]# **dnf update -y**
Last metadata expiration check: 0:48:14 ago on Fri Aug 23 03:45:55 2024.
Error: 
 Problem: cannot install both ntop-license-1.0-494.x86_64 from ntop and ntop-license-1.0-492.x86_64 from @System
  - package nprobe-10.7.240822-8434.x86_64 from @System requires ntop-license = 1.0-492, but none of the providers can be installed
  - cannot install the best update candidate for package ntop-license-1.0-492.x86_64
  - cannot install the best update candidate for package nprobe-10.7.240822-8434.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)


Thanks,
Gabriel

**Comment by infinitynet2011** [comment]
After the last update, all is ok.


[root@ntopng]# **dnf update -y**
Last metadata expiration check: 1:18:56 ago on Fri Aug 23 07:19:07 2024.
Dependencies resolved.

 Package                                        Architecture                          Version                                                      Repository                                  Size

Upgrading:
 ca-certificates                                noarch                                2024.2.69_v8.0.303-91.4.el9_4                                baseos                                     911 k
 cento                                          x86_64                                2.1.240823-961                                               ntop                                       1.3 M
 n2disk                                         x86_64                                3.7.240823-5525                                              ntop                                       1.4 M
 nprobe                                         x86_64                                10.7.240823-8436                                             ntop                                       3.9 M
 ntop-license                                   x86_64                                1.0-494                                                      ntop                                        22 k
 ntopng                                         x86_64                                6.3.240823-24306                                             ntop                                       9.5 M
 ntopng-data                                    noarch                                6.3.240823-24306                                             ntop-noarch                                 49 M
 
 
 Thanks,
 Gabriel

**Comment by MatteoBiscosi** [comment]
Hi gabriel, in case the issue come back, please reopen the ticket (or open a new one)
