### ISSUE TITLE
[ts_utils_core.lua:230] ERROR Schema not found

### ISSUE THREAD

**Issue by infinitynet2011** [ntop/ntopng#8666]
Hello,
	
23/Aug/2024 08:44:00 [timeseries.lua:54] [ts_utils_core.lua:230] ERROR Schema not found: process:resident_memory
23/Aug/2024 08:44:00 [timeseries.lua:44] [ts_utils_core.lua:230] ERROR Schema not found: process:num_alerts
23/Aug/2024 08:43:00 [timeseries.lua:54] [ts_utils_core.lua:230] ERROR Schema not found: process:resident_memory
23/Aug/2024 08:43:00 [timeseries.lua:44] [ts_utils_core.lua:230] ERROR Schema not found: process:num_alerts
23/Aug/2024 08:42:00 [timeseries.lua:54] [ts_utils_core.lua:230] ERROR Schema not found: process:resident_memory
23/Aug/2024 08:42:00 [timeseries.lua:44] [ts_utils_core.lua:230] ERROR Schema not found: process:num_alerts
23/Aug/2024 08:41:00 [timeseries.lua:54] [ts_utils_core.lua:230] ERROR Schema not found: process:resident_memory
23/Aug/2024 08:41:00 [timeseries.lua:44] [ts_utils_core.lua:230] ERROR Schema not found: process:num_alerts
23/Aug/2024 08:40:00 [timeseries.lua:54] [ts_utils_core.lua:230] ERROR Schema not found: process:resident_memory
23/Aug/2024 08:40:00 [timeseries.lua:44] [ts_utils_core.lua:230] ERROR Schema not found: process:num_alerts
23/Aug/2024 08:39:00 [timeseries.lua:54] [ts_utils_core.lua:230] ERROR Schema not found: process:resident_memory
23/Aug/2024 08:39:00 [timeseries.lua:44] [ts_utils_core.lua:230] ERROR Schema not found: process:num_alerts
23/Aug/2024 08:38:16 [NtopPro.cpp:506] [LICENSE] /etc/ntopng.license: found valid Enterprise M license
23/Aug/2024 08:38:16 [NtopPro.cpp:348] [LICENSE] Reading license from /etc/ntopng.license
23/Aug/2024 08:38:16 [NtopCloud.cpp:146] Unique id ntop/4606798171/L68C03416B2076B27--U68C034166376FC9F--OL/ntopng/28022
23/Aug/2024 08:38:16 [NtopCloud.cpp:145] Successfully registered with the cloud
23/Aug/2024 08:38:16 [NtopCloud.cpp:131] Successfully connected to ntop cloud
23/Aug/2024 04:30:35 [NtopPro.cpp:506] [LICENSE] /etc/ntopng.license: found valid Enterprise M license
23/Aug/2024 04:30:35 [NtopPro.cpp:348] [LICENSE] Reading license from /etc/ntopng.license
23/Aug/2024 04:30:35 [NtopCloud.cpp:146] Unique id ntop/4606798171/L68C03416B2076B27--U68C034166376FC9F--OL/ntopng/16861
23/Aug/2024 04:30:35 [NtopCloud.cpp:145] Successfully registered with the cloud
23/Aug/2024 04:30:35 [NtopCloud.cpp:131] Successfully connected to ntop cloud
23/Aug/2024 01:28:43 [ntoppro_defines.h:89] Max host pool members number: 4294967295
23/Aug/2024 01:28:43 [Utils.cpp:1614] [NAMELOOKUP_TIME 0.03][CONNECT_TIME 0.06][APPCONNECT_TIME 0.14][PRETRANSFER_TIME 0.14][REDIRECT_TIME 0.00][STARTTRANSFER_TIME 0.17][TOTAL_TIME 0.30]
23/Aug/2024 01:28:42 [LuaEngine.cpp:687] Running /usr/share/ntopng/scripts/callbacks/system/boot.lua
23/Aug/2024 01:28:42 [Ntop.cpp:520] Interfaces Available: 16
23/Aug/2024 01:28:42 [ntoppro_defines.h:147] Max nw interfaces number: 16
23/Aug/2024 01:28:42 [HostPools.cpp:79] Host Pools Available: 128
23/Aug/2024 01:28:42 [ntoppro_defines.h:74] Max host pools number: 128
23/Aug/2024 01:28:42 [ntoppro_defines.h:105] Max profiles number: 128
23/Aug/2024 01:28:42 [NetworkInterface.cpp:445] Successfully loaded /usr/share/ndpi/public_suffix_list.dat
23/Aug/2024 01:28:42 [NtopPro.cpp:506] [LICENSE] /etc/ntopng.license: found valid Enterprise M license

Thanks,
Gabriel

**Comment by MatteoBiscosi** [comment]
Hi @infinitynet2011 please share your ntopng.conf and your ntopng --version.
Are you exporting to influxdb or are you using rrd?

**Comment by infinitynet2011** [comment]
Hello Matteo.

I dont see that error anymore since the last update.


Thanks,
Gabriel

**Comment by MatteoBiscosi** [comment]
Ok good, please reopen the ticket if the issue appears again
