### ISSUE TITLE
elasticsearch missing mac

### ISSUE THREAD

**Issue by xiamaohan** [ntop/ntopng#8667]
We want to know is it normal that when we set “-i view:all” in ntopng config, elasticsearch is missing data of server.mac and client.mac.
But with the following configs, the mac data are existed in elasticsearch.
-i=enp3s0f0@0
-i=enp3s0f0@1
-i=enp3s0f0@2
-i=enp3s0f0@3
-i=enp3s0f0@4
-i=enp3s0f0@5
-i=enp3s0f0@6
-i=enp3s0f0@7

**Comment by MatteoBiscosi** [comment]
Hi @xiamaohan which info are you exporting to elastic, flows or alerts?

**Comment by xiamaohan** [comment]
> Hi @xiamaohan which info are you exporting to elastic, flows or alerts?

Hi, flows

**Comment by MatteoBiscosi** [comment]
In that case it's normal, because there is no concept of MAC Address on all the interfaces except for the view:all one (that in reality has no real flow, it's just a view).
So if you want to export flows to elastic and have MACs i'd suggest on removing the view:all option
