### ISSUE TITLE
HTTP prefix not handled correctly on some links

### ISSUE THREAD

**Issue by mcodato** [ntop/ntopng#8676]
**Environment**:
* OS name: RHEL 8.10
* Architecture: x86_64
* ntopng version/revision: 6.2.240820

**What happened**:
We found a couple of links/requests that are not generated correctly with the HTTP prefix.

Given the HTTP prefix `/neteye/ntopng/ntopng`

1. On `Flows -> Historical` the `Analyse Records (Live)` and `Download Records` buttons have a double slash between the domain and the HTTP prefix
![image](https://github.com/user-attachments/assets/6f1b864c-5150-43a9-b4b9-958ae4c5e6fa)
![image](https://github.com/user-attachments/assets/c4310529-ec1e-43bd-8d93-85be95dd5f9b)

All other links are generated correctly for example
![image](https://github.com/user-attachments/assets/f5e4b36e-2b66-4a24-86b7-0c1b5e8da7b4)

2. On `Developer -> Rest API` and error is shown due to the request to `misc/rest-api-v2.json` that is generated without the http-prefix
![image](https://github.com/user-attachments/assets/f0137d08-8e1a-4279-a6d4-a05be5fe9375)

**How did you reproduce it?**
Configure an HTTP prefix for example
`-Z=/neteye/ntopng/ntopng` 
and check the pages previously mentioned

**Comment by MatteoBiscosi** [comment]
The issue should be fixed, in an hour or so a new update should be available, please let me know.

**Comment by mcodato** [comment]
I confirm that the issue has been fixed, thank you

**Comment by NotArandomGUY** [comment]
I found a few more links that didn't handle http prefix correctly
https://github.com/ntop/ntopng/blob/084e295af84794ecea818512c44a266c50a6af9c/scripts/lua/monitor/active_monitoring_monitor.lua#L71
https://github.com/ntop/ntopng/blob/084e295af84794ecea818512c44a266c50a6af9c/scripts/lua/ntopng_logout.lua#L17
https://github.com/ntop/ntopng/blob/084e295af84794ecea818512c44a266c50a6af9c/scripts/lua/change_password.lua#L31

## Fixes
Here's my attempt at fixing it, hope this helps
### Location 1: https://github.com/ntop/ntopng/blob/084e295af84794ecea818512c44a266c50a6af9c/scripts/lua/modules/ui_utils.lua#L74
### Changes 1:
```diff
-    return "<a href='".. title_link .."'>".. title .. "</a>&nbsp;/&nbsp;<span>"..subpage.."</span>"
+    return "<a href='".. ntop.getHttpPrefix() .. title_link .."'>".. title .. "</a>&nbsp;/&nbsp;<span>"..subpage.."</span>"
```
### Location 2:
https://github.com/ntop/ntopng/blob/084e295af84794ecea818512c44a266c50a6af9c/scripts/lua/ntopng_logout.lua#L17
### Changes 2:
```diff
-  <meta http-equiv="refresh" content="1; URL=/">
+  <meta http-equiv="refresh" content="1; URL=]] print(ntop.getHttpPrefix()) [[/">
```
### Location 3:
https://github.com/ntop/ntopng/blob/084e295af84794ecea818512c44a266c50a6af9c/scripts/lua/change_password.lua#L31
### Changes 3:
```diff
-     print(ntop.httpRedirect(_GET["referrer"] or "/"))
+     print(ntop.httpRedirect(_GET["referrer"] or (ntop.getHttpPrefix() .. "/")))
```

**Comment by NotArandomGUY** [comment]
Found 2 more links that didn't handle http prefix correctly

https://github.com/ntop/ntopng/blob/084e295af84794ecea818512c44a266c50a6af9c/scripts/lua/host_details.lua#L150

https://github.com/ntop/ntopng/blob/084e295af84794ecea818512c44a266c50a6af9c/scripts/lua/host_details.lua#L155

**Comment by MatteoBiscosi** [comment]
Thanks a lot for your report
