### ISSUE TITLE
top local/remote KO

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#868]
since few builds in the main page top local/remote hosts are not OK
something changed in "--local-networks" setting ?

ie 
--local-networks="161.48.0.0/19,100.64.0.0/16,100.65.0.0/16,100.66.0.0/16,100.77.0.0/16,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"

and result is
![capture](https://cloud.githubusercontent.com/assets/17108017/21435951/9210f904-c87c-11e6-81b7-093ef962a182.PNG)

even when it is public IP it is mixed with top-remote... so mixed with local here

NIcolas

**Comment by Niko78** [comment]
just upgraded this morning
still not fixed

**Comment by Alestor** [comment]
Same here:
--local-networks "192.168.0.0/16,172.16.0.0/12,10.0.0.0/8"


25/Dec/2016 18:07:43 [AddressTree.cpp:134] [AddressTree] 192.168.0.0/16
25/Dec/2016 18:07:43 [Ntop.cpp:561] Local Networks
25/Dec/2016 18:07:43 [Ntop.cpp:559] Local Interface Addresses (System Host)

**Comment by lucaderi** [comment]
You need to explain more in detail how to reproduce. The above log seems ok

**Comment by Alestor** [comment]
Hi,

well startup parameter are in /etc/ntopng/ntopng.conf including the -m switch for local network. If more then one network is specified (-m "network1/mask,network2/mask,network3/mask") only network1/mask is recognized as local. ntopng is started via systemd (ExecStart=/etc/init.d/ntopng start)
