### ISSUE TITLE
Question: When can we get an official arm64 release published?

### ISSUE THREAD

**Issue by djstarfox** [ntop/ntopng#8680]
When can we get an official arm64 release published?  It's been 2+ months since the last binary published at https://packages.ntop.org/

**Comment by lucaderi** [comment]
We are undecided if necessary. Why the raspberry build is not enough for you?

**Comment by djstarfox** [comment]
Because there have been a number of key bug fixes between the last official release 2024-06-28 and the latest build in development branch.

**Comment by dpkano** [comment]
The last version of the raspberry pi build is also 2024-06-28. Will the raspberry pi builds be updated again?

**Comment by lucaderi** [comment]
Pi builds are daily as you can see https://packages.ntop.org/apt/bookworm_pi/arm64/
