### ISSUE TITLE
Disconnection After Inactivity

### ISSUE THREAD

**Issue by shabi61** [ntop/ntopng#8684]
Description: Nedge disconnects users after 5 minutes of inactivity, which creates issues. Users who lock their devices do not receive notifications and are subsequently disconnected, requiring them to re-enter their codes.

Version: v.6.3.240828 with RADIUS integrated

**Comment by lucaderi** [comment]
@shabi61 What do you want us to do exactly?

**Comment by MatteoBiscosi** [comment]
![image](https://github.com/user-attachments/assets/ff5cc618-e116-455e-9a3c-cae57e6bb523)

**Comment by lucaderi** [comment]
@shabi61 Can you please check if this code is working and if not please report howto reproduce the defect?

**Comment by shabi61** [comment]
Despite the updates on October 1st and 8th, it appears that the issue still persists. After closely monitoring the system's behavior over the past few days, we observed that approximately 30 minutes after Nedge starts, the number of users shown in the "Members" section of the Nedge dashboard consistently falls below the number of users in RADIUS.

This may indicate that some users who initially joined a group in Nedge and RADIUS using a voucher lose their group association in Nedge after a period of inactivity. However, no disconnect request is being sent from the user's side, suggesting that they are being removed due to system behavior, not user-initiated actions.

**Comment by MatteoBiscosi** [comment]
The issue has been reported as fixed
