### ISSUE TITLE
User session with updatetime > stoptime

### ISSUE THREAD

**Issue by shabi61** [ntop/ntopng#8685]
Description: The issue where a user session’s updatetime exceeds stoptime has resurfaced in a different form after being previously closed.
When a voucher is disconnected, the session’s updatetime continues to update, even though the disconnection reason is listed as “User request” . Upon reconnection, a new entry is correctly created in the database, but the previously closed entry is modified. Specifically, the stoptime, updatetime, consumed traffic, and disconnection reason change to “Lost service” .
On Nedge, the user appears to be in the correct group (captivepass) after disconnection.

Version: v.6.3.240828 with RADIUS integrated

**Comment by MatteoBiscosi** [comment]
The problem is due to the fact that between a Radius accounting start and an other (in case of disconnection) no Radius accounting stop is called.
