### ISSUE TITLE
Rework NTP/DNS/DHCP/SMTP Configuration Page

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8686]
The list of allowed NTP/DNS/DHCP/SMTP servers is specified inside behavioural checks. They need to be migrated to a new page named "Network Configuration" which is similar to 

![image](https://github.com/user-attachments/assets/a3eaa95d-9ba3-4fb9-836f-630f24a4cc54)

and that contains the save information specified inside the former checks page.

Inside the above  "NTP/DNS/DHCP/SMTP Unexpected Server" checks, the existing textbox
<img width="793" alt="Screenshot 2024-08-30 at 16 34 16" src="https://github.com/user-attachments/assets/a7f7208e-9383-45ff-b1a9-6047a7a5c510">

has to be removed. At the bottom of the check add a new string saying "You can specify the list of PROTOCOL servers at XXX" where XXX is the URL of this new page.

Currently, the checks values (for all checks) are specified in a single "ntopng.prefs.checks.configset_v1" redis key. For the above NTP/DNS/DHCP/SMTP servers, the new configuration page will save them individually in redis key whose name is ntopng.prefs.XXX_ip_list. Example ntopng.prefs.XXX_ip_list for DHCP.

This requires to
- write a short Lua script executed at boot, that migrates the old keys to the new keys
- check the NTP/DNS/DHCP/SMTP behavioural check to make sure that the C++ check logic is not broken

**Comment by MatteoBiscosi** [comment]
This feature is implemented and working, the only missing thing is implement the gateway support, that is followed by ticket #8687
