### ISSUE TITLE
Labels Broken in Some Checks

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8689]
Some labels are broken in checks (e.g. DHCP).

Both stable and dev must be fixed.

<img width="799" alt="Screenshot 2024-09-01 at 15 43 08" src="https://github.com/user-attachments/assets/6ff6dc9d-31d1-4f7a-a6c9-fc2b6ad0b60b">

**Comment by MatteoBiscosi** [comment]
Fixed for both, stable and dev

**Comment by MatteoBiscosi** [comment]
The issue seems fixed, in case it is not please reopen the ticket
