### ISSUE TITLE
NetworkInterface.cpp build error on last code pull

### ISSUE THREAD

**Issue by leveryd** [ntop/ntopng#869]
ndpi version is 1.8.0-stable
ntopng version is ntopng-2.4-stable.
i  do what  "ntopng-2.4-stable/doc/README.compilation"  mentions,then occurs a error.
`g++ -g -Wall -I/tmp/ntopng -I/tmp/ntopng/include -I/usr/local/include  -I/usr/include/hiredis -I/tmp/ntopng/third-party/mongoose -I/usr/local/include/json-c   -I/usr/local/include/libndpi-1.8.0/libndpi   -I/tmp/ntopng/third-party/LuaJIT-2.0.3/src   -I/tmp/ntopng/third-party/zeromq-4.1.3/include -I/usr/include/mysql  -I/tmp/ntopng -I/tmp/ntopng/include -I/usr/local/include -I/tmp/ntopng/third-party/http-client-c/src/  -DDATA_DIR='"/usr/local/share"' -I/tmp/ntopng/third-party/libgeohash -I/tmp/ntopng/third-party/patricia   -c src/NetworkInterface.cpp -o src/NetworkInterface.o
src/NetworkInterface.cpp: In constructor 'NetworkInterface::NetworkInterface(const char*)':
src/NetworkInterface.cpp:118:49: error: cannot convert 'ndpi_port_range*' to 'ndpi_protocol_category_t' for argument '7' to 'void ndpi_set_proto_defaults(ndpi_detection_module_struct*, ndpi_protocol_breed_t, u_int16_t, u_int16_t*, u_int16_t*, char*, ndpi_protocol_category_t, ndpi_port_range*, ndpi_port_range*)'
make: *** [src/NetworkInterface.o] Error 1`

**Comment by leveryd** [comment]
i do all those on ubuntu 12.04 LTS.
and the kernel information is:
Linux sec 3.8.0-29-generic #42~precise1-Ubuntu SMP Wed Aug 14 16:19:23 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by emanuele-f** [comment]
Please double check that there isn't another nDPI version installed somewhere else in the system. Ideally, you should put the nDPI folder at the same level of ntopng, so in /tmp in your case. We also provide prebuilt stable packages for ubuntu 12, please take a look at http://packages.ntop.org/apt-stable/

**Comment by ALIREZA-Z** [comment]
Your branches are not sync together.It seems you use ntopng with dev branch and ndpi with 1.8-stable

**Comment by simonemainardi** [comment]
solution found and given. Cause was a non-aligned nDPI and ntopng sources.
