### ISSUE TITLE
storage space is running out because of the suricata eve.json file

### ISSUE THREAD

**Issue by Alisher-Nabiev** [ntop/ntopng#8691]
Environment:

OS name: Ubuntu
OS version: 18.04.6 LTS
Architecture: x86_64
ntopng version/revision: ntopng Enterprise L v.5.7.231017
What happened:
my storage space is running out because of the suricata eve.json file

![image](https://github.com/user-attachments/assets/c28f3b6e-123b-4737-b5a3-ecfb82d23959)

can I delete this file? How can I keep this file small?

**Comment by cardigliano** [comment]
The eve.json file is produced by Suricata, ntopng does not need that file. Please change the Suricata configuration.
