### ISSUE TITLE
decompression buffer too short

### ISSUE THREAD

**Issue by xkrizp09** [ntop/ntopng#8694]
Environment:
OS name: Debian
OS version: 12
Architecture: amd64
ntopng version/revision: ntopng Enterprise L v.6.3.240902

Hi,
after yesterday update I am getting this error. How can I fix it? Thank you

03/Sep/2024 10:55:10 [ZMQCollectorInterface.cpp:493] ERROR Internal error: decompression buffer too short
03/Sep/2024 10:55:10 [ZMQCollectorInterface.cpp:489] ERROR [topic: template][version: 4] Uncompress error -5 [compressed len: 1715][max decompress len: 540]

**Comment by lucaderi** [comment]
Did you update nProbe that sends flows to ntopng? Please report "nprobe --version"

**Comment by xkrizp09** [comment]
I did, all probes version 10.7.240902-8451

**Comment by lucaderi** [comment]
Please share the nprobe configuration file. I have pushed a new change that should address your issue. The new build will be available in about 1h from now. Please update and report.

**Comment by xkrizp09** [comment]
There is no error after nprobe update. Thank you.
