### ISSUE TITLE
Alerts Explorer for Local Hosts

### ISSUE THREAD

**Issue by infinitynet2011** [ntop/ntopng#8695]
Hello!

Would it be possible to have a filter for **Local** and **Remote** Hosts?

I am more interested in getting alerts for **Local** Hosts.

![image](https://github.com/user-attachments/assets/6ec31b95-6c33-48df-b881-d9cc4b26660b)

Thank you,
Gabriel

**Comment by MatteoBiscosi** [comment]
To be able to filter hosts, use the host location filter:
![image](https://github.com/user-attachments/assets/8f3bcfd5-7931-49a0-93c8-8eb647a2f20f)

**Comment by infinitynet2011** [comment]
Perfect!,

But I can't find them, can you please show me where it is?


Thanks,
Gabriel

**Comment by infinitynet2011** [comment]
Found it!

![image](https://github.com/user-attachments/assets/3133239b-0139-40ce-bba7-77012f5b84e8)


Thanks,
Gabriel

**Comment by infinitynet2011** [comment]
Hello,

My idea was not to be **bothered** by remote Hosts not just to have a filter to hide Remote Hosts.

![image](https://github.com/user-attachments/assets/86ba57d4-3de3-4735-8234-c719eeacb486)

Can I do something about alerts that i am not interested?




Thanks,
Gabriel

**Comment by MatteoBiscosi** [comment]
Hi Gabriel, no, right now no, you have to add that filter to remove the remote hosts for instance but they are still saved on the db

**Comment by infinitynet2011** [comment]
Hi Matteo,

Yes, but it is a problem. Each time that page goes, I must put the filters again. 
Could I keep a filter to be **permanent**?


Thank you,
Gabriel
