### ISSUE TITLE
Remove nProbe Menu Entry 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8701]
This entry (shown on non-view interfaces) is no longer necessary and it can be safely removed from stable/dev

<img width="946" alt="Screenshot 2024-09-05 at 18 32 18" src="https://github.com/user-attachments/assets/4eefc202-72c2-4a1b-823c-e3705db8d7ce">

**Comment by MatteoBiscosi** [comment]
The issue seems fixed, in case it is not please reopen the ticket
