### ISSUE TITLE
List 'Feodo' has 0 rules

### ISSUE THREAD

**Issue by joee** [ntop/ntopng#8704]
**Environment**:
* OS name: NixOS
* OS version: 23.05
* Architecture: x86_64
* ntopng version/revision: 5.6.231230

**What happened**:

This warning was displayed in `journalctl`:

Sep 05 00:00:42 HOSTNAME ntopng[PID]: [housekeeping.lua:37] [lists_utils.lua:673] WARNING: List 'Feodo' has 0 rules. Please report this to https://github.com/ntop/ntopng

**How did you reproduce it?**

It seems to happen every few days on its own.

**Debug Information**:

● ntopng.service - Ntopng Network Monitor
     Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; preset: enabled)
     Active: active (running) since Wed 2024-06-19 13:18:00 GMT; 2 months 17 days ago
       Docs: man:ntopng(8)
   Main PID: 1157 (ntopng-main)
         IP: 1.1G in, 1.5M out
         IO: 861.4G read, 13.2T written
      Tasks: 50 (limit: 18909)
     Memory: 14.2G
        CPU: 1w 8h 42min 42.482s
     CGroup: /system.slice/ntopng.service
             └─1157 /nix/store/0nbij0zb9wh9vw1qnfva86llzn7n5raz-ntopng-5.6/bin/ntopng /nix/store/rr3m9pw1p8z4qpjszzzi4a0lxly2x2bs-ntopng.conf

Sep 05 00:00:42 HOSTNAME ntopng[1157]: 05/Sep/2024 00:00:42 [housekeeping.lua:37] [lists_utils.lua:411] Updating list 'Feodo' [https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt]... OK
Sep 05 00:00:42 HOSTNAME ntopng[1157]: 05/Sep/2024 00:00:42 [housekeeping.lua:37] [lists_utils.lua:411] Updating list 'Feodo Tracker Botnet C2 IP Blocklist' [https://feodotracker.abuse.ch/downloads/ipblocklist.txt]... OK
Sep 05 00:00:42 HOSTNAME ntopng[1157]: 05/Sep/2024 00:00:42 [housekeeping.lua:37] [lists_utils.lua:411] Updating list 'NoCoin Filter List' [https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt]... OK
Sep 05 00:00:42 HOSTNAME ntopng[1157]: 05/Sep/2024 00:00:42 [housekeeping.lua:37] [lists_utils.lua:411] Updating list 'SSLBL Botnet C2 IP Blacklist' [https://sslbl.abuse.ch/blacklist/sslipblacklist.txt]... OK
Sep 05 00:00:42 HOSTNAME ntopng[1157]: 05/Sep/2024 00:00:42 [housekeeping.lua:37] [lists_utils.lua:411] Updating list 'ThreatFox' [https://threatfox.abuse.ch/downloads/hostfile/]... OK
Sep 05 00:00:42 HOSTNAME ntopng[1157]: 05/Sep/2024 00:00:42 [housekeeping.lua:37] [lists_utils.lua:411] Updating list 'URLhaus' [https://urlhaus.abuse.ch/downloads/hostfile/]... OK
Sep 05 00:00:42 HOSTNAME ntopng[1157]: 05/Sep/2024 00:00:42 [housekeeping.lua:37] [lists_utils.lua:411] Updating list 'dshield 7 days' [https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/dshield_7d.netset]... OK
Sep 05 00:00:42 HOSTNAME ntopng[1157]: [housekeeping.lua:37] [lists_utils.lua:673] WARNING: List 'Feodo' has 0 rules. Please report this to https://github.com/ntop/ntopng
Sep 05 00:00:42 HOSTNAME ntopng[1157]: 05/Sep/2024 00:00:42 [housekeeping.lua:37] [lists_utils.lua:673] WARNING: List 'Feodo' has 0 rules. Please report this to https://github.com/ntop/ntopng
Sep 05 00:00:43 HOSTNAME ntopng[1157]: 05/Sep/2024 00:00:43 [housekeeping.lua:37] [lists_utils.lua:747] Category Lists (8451 hosts, 1461 IPs, 0 JA3) loaded in 1 sec

**Comment by MatteoBiscosi** [comment]
Hi @joee sorry but we do support only the most recent versions of ntopng (6.2 for stable and 6.3 for dev) so we can help you, only if you update

**Comment by joee** [comment]
No problem.  Just sharing because it said: Please report this to https://github.com/ntop/ntopng
