### ISSUE TITLE
Bad formatting in the Analysis pages

### ISSUE THREAD

**Issue by mzac** [ntop/ntopng#8707]
* OS name: Ubuntu
* OS version: 22.04.4 LTS
* Architecture: amd64
* ntopng version/revision: 6.2.240906

**What happened**:
When viewing Analysis on live flows, some of the buttons in the left column are not displayed properly

**How did you reproduce it?**
By looking at the Analysis page

**Debug Information**:

![image](https://github.com/user-attachments/assets/1da702f8-613f-4407-8d79-41372ee81d30)

![image](https://github.com/user-attachments/assets/1cf6a14f-5513-4ddb-96f8-97890bf908fe)

**Comment by DGabri** [comment]
@MatteoBiscosi this is what I found, could you please check cpp side? 

`src/Flow.cpp:   info_field = std::string("<i class='fa fa-lg fa-video'></i> Video");`

**Comment by MatteoBiscosi** [comment]
The issue should now be fixed both for Stable and Dev version

**Comment by mzac** [comment]
@MatteoBiscosi  Thanks it looks better now!

**Comment by MatteoBiscosi** [comment]
The issue seems fixed, in case it is not please reopen the ticket
