### ISSUE TITLE
Add Packet Analysis to Historical (replay) flows.

### ISSUE THREAD

**Issue by wahezu** [ntop/ntopng#8708]
**What would you like to add or change?**:

Add Packet Analysis to Historical (replay) flows similar to what is shown with LIVE flows. Screenshot attached.

**Why do you and others need this?**:

Ability to troubleshoot packet loss, retransmissions, jitter, etc for historical flows.

![ntopng-packetanalysis](https://github.com/user-attachments/assets/e31e7b90-34b5-4b6c-84b6-99b1dc8d6621)

Thanks.

**Comment by lucaderi** [comment]
This is what you can use to troubleshoot retransmissions....
https://www.ntop.org/guides/ntopng/using_with_other_tools/n2disk.html
