### ISSUE TITLE
How to exclude protocols from monitoring or how to aggregate protocol monitoring

### ISSUE THREAD

**Issue by Falcosc** [ntop/ntopng#871]
I would like to monitor my internet traffic. Unfortunately I share the same network interface for local network traffic and internet traffic.
I don’t need to exact. It would be enough to exclude SMB from monitoring than I would be able to use the “Traffic” time series.
If this is not possible It would also be also sufficient if there is a way to combine 2 protocol timeseries into one node without losing the possibility to display each of them separate.
I did already try the nDPI configuration but I can’t assign same port to multiple Names.
Is there any feature which could help to achieve an exclude or an aggregation or would this be an feature request?

Kind Regards
Falco

**Comment by simonemainardi** [comment]
if you can identify the (hosts and) ports Samba uses, then it would suffice to start ntopng with a BPF filter that excludes traffic matching those (hosts and) ports. For example

`./ntopng --packet-filter "not host 127.0.0.1 and not port 138 and not port 139"`

Keep in mind that all the traffic matching the specified criteria will be excluded so if there are other applications that use the same ports they will be excluded as well.

**Comment by Falcosc** [comment]
Thank you for your answer.
I thought the packet filter option was for dropping packages because you have features for shaping and blacklisting as well. Maybe it would improve the user guide to make more clear which options are for monitoring flows and which for adjusting flows.

**Comment by simonemainardi** [comment]
@Falcosc thanks for the feedback.
