### ISSUE TITLE
Please allow specifying location of logs + log level

### ISSUE THREAD

**Issue by 2tefan** [ntop/ntopng#8715]
Hi, currently `ntopng` uses `rsyslog` to write logs to `/var/log/ntopng.log` by default on an Ubuntu install:

https://github.com/ntop/ntopng/blob/d4cb75abfd51a53413d3dd954561cdb79463d183/packages/etc/rsyslog.d/20-ntopng.conf#L1-L3

When I change this file and then do an update, this file is overwritten by ntopng. So maybe you could add at least a comment to this file, that it's automatically overwritten? Or maybe leave it, if it was modified :)

**What would you like to add or change?**:
It would be nice, to be able to specify the location of logs as well as the severity, that is logged into this file. Maybe users should be able to specify this via an argument at startup?

You could use this as a template:
```
if $programname == 'ntopng' and $syslogseverity <= 6 then /var/log/ntopng/ntopng.log
& ~
```

**Why do you and others need this?**:
We want to have ntopng logs in a different location and also not all logs from all severities, as ntopng produces quite a lot of logs with this configuration.

**Comment by lucaderi** [comment]
Please provide a pull request with the changes you would like to see implemented and we'll look at them
