### ISSUE TITLE
 Invalid lua VM state returned by reload_servers_configuration()

### ISSUE THREAD

**Issue by infinitynet2011** [ntop/ntopng#8716]
Hello,

After the latest update:

[root@ntopng ~]# sudo systemctl status ntopng
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
     Loaded: loaded (/usr/lib/systemd/system/ntopng.service; enabled; preset: disabled)
     Active: active (running) since Wed 2024-09-11 00:10:09 EEST; 9min ago
    Process: 1970447 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exited, status=0/SUCCESS)
    Process: 1970461 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
    Process: 1970463 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (code=exited, status=0/SUCCESS)
    Process: 1970465 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /run/ntopng.conf (code=exited, status=0/SUCCESS)
   Main PID: 1970468 (ntopng-main)
      Tasks: 46 (limit: 152197)
     Memory: 2.0G
        CPU: 4min 47.187s
     CGroup: /system.slice/ntopng.service
             └─1970468 /usr/bin/ntopng /run/ntopng.conf

Sep 11 00:10:10 ntopng ntopng[1970468]: 11/Sep/2024 00:10:10 [NtopCloud.cpp:131] Successfully connected to ntop cloud
Sep 11 00:10:10 ntopng ntopng[1970468]: 11/Sep/2024 00:10:10 [NtopCloud.cpp:145] Successfully registered with the cloud
Sep 11 00:10:10 ntopng ntopng[1970468]: 11/Sep/2024 00:10:10 [NtopCloud.cpp:146] Unique id ntop/4606798171/L68C03416B2076B27--U68C034166376FC9F--OL/ntopng/1970468
Sep 11 00:10:10 ntopng ntopng[1970468]: 11/Sep/2024 00:10:10 [NtopPro.cpp:348] [LICENSE] Reading license from /etc/ntopng.license
Sep 11 00:10:10 ntopng ntopng[1970468]: 11/Sep/2024 00:10:10 [NtopPro.cpp:506] [LICENSE] /etc/ntopng.license: found valid Enterprise M license
**Sep 11 00:10:17 ntopng ntopng[1970468]: 11/Sep/2024 00:10:17 [LuaEngine.cpp:255] ERROR: [INTERNAL ERROR] Invalid lua VM state returned by reload_servers_configuration()
Sep 11 00:10:17 ntopng ntopng[1970468]: 11/Sep/2024 00:10:17 [LuaEngine.cpp:255] ERROR: [INTERNAL ERROR] Invalid lua VM state returned by reload_servers_configuration()
Sep 11 00:10:17 ntopng ntopng[1970468]: 11/Sep/2024 00:10:17 [LuaEngine.cpp:257] ERROR: [INTERNAL ERROR] Please report it here https://github.com/ntop/ntopng/issues
Sep 11 00:10:17 ntopng ntopng[1970468]: 11/Sep/2024 00:10:17 [LuaEngine.cpp:257] ERROR: [INTERNAL ERROR] Please report it here https://github.com/ntop/ntopng/issues**
Sep 11 00:19:03 ntopng sudo[1971506]:   ntopng : PWD=/ ; USER=root ; COMMAND=/usr/bin/ntopctl n2disk-ntopng stats

[root@ntopng ~]# ntopng --version
Version:        6.3.240910 [Enterprise/Professional build]
GIT rev:        dev:d4cb75abfd51a53413d3dd954561cdb79463d183:20240910
Pro rev:        r6802
Built on:       Rocky Linux release 9.3
System Id:      L68C03416B2076B27--U68C034166376FC9F--OL
Platform:       x86_64
Edition:        Enterprise M
License Type:   Permanent

Thank you,
Gabriel

**Comment by MatteoBiscosi** [comment]
Hi @infinitynet2011 please update to the latest version and let me know, the issue should already have been fixed with yesterday's build

**Comment by infinitynet2011** [comment]
Yes, it's fixed. Thank you.
