### ISSUE TITLE
Syslog alert notifications do not work when severity is set to critical or emergency

### ISSUE THREAD

**Issue by Ernestas-S** [ntop/ntopng#8719]
**Environment**:
* OS name: Ubuntu
* OS version: 22.04.2
* Architecture: amd64
* ntopng version/revision: ntopng Enterprise L v.5.6.230727

**What happened**:
Hi, the following version of ntopng: [ntopng Enterprise L v.5.6.230727 (Ubuntu 22.04.2 LTS)](https://www.ntop.org/products/traffic-analysis/ntop/), does not send any syslog alert notifications when severity is set to critical or emergency. It only works when severity is set to error, warning, notice.

**How did you reproduce it?**
I just checked by selecting each severity and I noticed that some of severity levels do not send any "packets" in uses list of Notifications/Endpoints list. And I also do not receive anything on the endpoint server.

**Debug Information**:
No error, just that no information is coming out when different severity level is selected

**Comment by MatteoBiscosi** [comment]
Hi @Ernestas-S sorry but we can help you if you update to the latest dev or stable version of ntopng (6.2 or 6.3) so please update and let me know if the issue persists

**Comment by MatteoBiscosi** [comment]
If the issue persists after the update please reopen the ticket
