### ISSUE TITLE
Continuous ICMP monitoring not working

### ISSUE THREAD

**Issue by Westy-87** [ntop/ntopng#8721]
**Environment**:
* OS name: Ubuntu
* OS version: 20.04.6 LTS
* Architecture: x86_64 
* ntopng version/revision: 6.2.240909 [Enterprise/Professional build]

**What happened**:
After update to 6.2 builds, 'Continuous ICMP' active monitoring no longer works. No measurements will be taken/shown and threshold will be shown as red. Exclamation mark next to the URL.

Normal ICMP monitor works still.

**How did you reproduce it?**

I have deleted/recreated the active monitoring. Performed another minor ntopng update as well.

When adding a new Continuous ICMP monitor, the interface will be shown as 'Default Interface'. However when you create it, it will show after the URL, in square brackets, the interface you were under in ntopng at the time. For instance, I have System and three virtual interfaces. If I create the monitor while in System view, it will show the interface as System. If I create it in my first virtual interface view, it will show the interface as 127.0.0.1:{port}. Editing the monitor and reselecting default inerface will get rid of the interface shown in the main view but won't fix the over all problem.

**Debug Information**:

<!--
Paste debug information below:
:~$ sudo systemctl status ntopng
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
     Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2024-09-10 08:39:11 AEST; 3 days ago
   Main PID: 3895817 (ntopng-main)
      Tasks: 64 (limit: 38385)
     Memory: 2.6G
     CGroup: /system.slice/ntopng.service
             └─3895817 /usr/bin/ntopng /run/ntopng.conf

Sep 13 04:16:22 auqlddcntop1ai ntopng[3895817]: 13/Sep/2024 04:16:22 [snmp_polling.lua:36] [snmp_poll.lua:464] ERROR: ...share/ntopng/pro/scripts/lua/modules/snmp_dev_bridge.lua:277: invalid>
Sep 13 04:16:22 auqlddcntop1ai ntopng[3895817]: 13/Sep/2024 04:16:22 [snmp_polling.lua:36] [snmp_poll.lua:464] ERROR: ...share/ntopng/pro/scripts/lua/modules/snmp_dev_bridge.lua:277: invalid>
Sep 13 13:56:05 auqlddcntop1ai ntopng[3895817]: [LINT] validateParameter failed for parameter [ifname][function]
Sep 13 13:56:05 auqlddcntop1ai ntopng[3895817]:  string Default Interface
Sep 13 13:56:05 auqlddcntop1ai ntopng[3895817]: [LINT] validateParameter failed for parameter [ifname][function]
Sep 13 13:56:05 auqlddcntop1ai ntopng[3895817]:  string Default Interface
Sep 13 13:56:05 auqlddcntop1ai ntopng[3895817]: [LINT] validateParameter failed for parameter [ifname][function]
Sep 13 13:56:05 auqlddcntop1ai ntopng[3895817]:  string Default Interface
Sep 13 13:56:05 auqlddcntop1ai ntopng[3895817]: [LINT] validateParameter failed for parameter [ifname][function]
Sep 13 13:56:05 auqlddcntop1ai ntopng[3895817]:  string Default Interface

- Grab a screenshot from the GUI demonstrating the issue.

![image](https://github.com/user-attachments/assets/4b8b9aaa-b0c7-40b0-ae55-bdb92ab29a64)

**Comment by MatteoBiscosi** [comment]
Could you please share your ntopng configuration file? I'll try to reproduce with your config

**Comment by Westy-87** [comment]
[ntopng.conf.txt](https://github.com/user-attachments/files/17051324/ntopng.conf.txt)

**Comment by MatteoBiscosi** [comment]
Hi @Westy-87 the issue should now be fixed. Tomorrow please update and let me know. The problem was related to the interfaces you are currently using (ZMQ interfaces) but now it should works with those too

**Comment by MatteoBiscosi** [comment]
The issue seems fixed, in case it is not please reopen the ticket

**Comment by Westy-87** [comment]
Sorry for the delay, I can confirm it's working now. Thanks
