### ISSUE TITLE
Flow > Historical not working at all, issue with influxdb ?

### ISSUE THREAD

**Issue by Spleenftw** [ntop/ntopng#8722]
**Environment**:
* OS name: Red Hat Enterprise Linux release 8.10 (Ootpa)
* OS version:  8.10
* Architecture: amd64
* ntopng version/revision:  6.2.240909 [Enterprise/Professional build]

**What happened**:

When i'm clicking on the Flows > Historical button, nothing shows up.

**How did you reproduce it?**

Simply clicking on flows > historical

**Debug Information**:

```
Sep 17 11:42:47 protop02 ntopng[281743]: 17/Sep/2024 11:42:47 [LuaEngine.cpp:1499] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/ts.lua][...ng/scripts/lua/pro/modules/flow_db/db_search_manager.lua:563: attempt to call a nil value (field 'formatWhere')]                   

Sep 17 11:42:48 protop02 ntopng[281743]: 17/Sep/2024 11:42:48 [LuaEngine.cpp:1499] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/historical_db_search.lua][...ng/scripts/lua/pro/modules/flow_db/db_search_manager.lua:94: attempt to call a nil value (field 'formatSelect')] 
```

![image](https://github.com/user-attachments/assets/75c5b9e5-94ac-4ceb-8b33-1a604bd1f58a)

**Comment by Spleenftw** [comment]
the issue is still there in the 6.3.240919, 6.3.240922 and 6.3.240924.

**Comment by MatteoBiscosi** [comment]
Hi @Spleenftw influxdb and clickhouse are used for different purposes, for this reason they should coexist without problems. Could you please share your ntopng configuration file?

**Comment by Spleenftw** [comment]
> Hi @Spleenftw influxdb and clickhouse are used for different purposes, for this reason they should coexist without problems. Could you please share your ntopng configuration file?

clickhouse-server & clickhouse-client were indeed missing.
I had to add "-F clickhouse" in the ntopng.conf file.

Regards,
