### ISSUE TITLE
Historical Flows Error

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8723]
ntopng Enterprise L v.6.2.240917 rev.24453

Historical Flows under ntopng -> Error

18/Sep/2024 15:06:55 [LuaEngine.cpp:1499] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/ts.lua][...ng/scripts/lua/pro/modules/flow_db/db_search_manager.lua:563: attempt to call a nil value (field 'formatWhere')]
18/Sep/2024 15:06:56 [LuaEngine.cpp:1499] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/historical_db_search.lua][...ng/scripts/lua/pro/modules/flow_db/db_search_manager.lua:94: attempt to call a nil value (field 'formatSelect')]

**Comment by kristoferus75** [comment]
i have now upgraded to version

ntopng Enterprise L v.6.2.240918 rev.24457

but same error :-(

**Comment by MatteoBiscosi** [comment]
Hi @kristoferus75 could you please share your configuration file?

**Comment by kristoferus75** [comment]
Hi !

**My Config**

ntopng.conf

```
-i=eno1
-i=tcp://127.0.0.1:5556
--local-networks="192.168.88.0/24"
```
nprobe.conf

```
-i none
-n none
--collector-port=2055
--zmq "tcp://*:5556"
```

**Comment by MatteoBiscosi** [comment]
Hi @kristoferus75 the issue is that you did not add the -F option to the configuration file to be able to access the Historical Flows.
If you want to access them, please follow this guide:
https://www.ntop.org/guides/ntopng/clickhouse/index.html

**Comment by MatteoBiscosi** [comment]
There was an issue with the Historical entry that appeared even if ClickHouse was not enabled.

**Comment by kristoferus75** [comment]
Hi Matteo ! It works now Thanks !

**Comment by MatteoBiscosi** [comment]
hi @kristoferus75 glad to know! thanks a lot for the feedback!
