### ISSUE TITLE
alert explorer SNMP delete uses wrong API call

### ISSUE THREAD

**Issue by dukrat** [ntop/ntopng#8724]
**Environment**:
* OS name: Oracle Linux
* OS version: 9.4
* Architecture: amd64
* ntopng version/revision: ntopng Enterprise XL v.6.2.240918 rev.24457 (Rocky Linux release 9.3)

**What happened**:
SNMP alerts are not deleted in alerts explorer by use of the actions or red trash buttonQ

**How did you reproduce it?**
Try to delete SNMP alerts from explorer

**Debug Information**:
JS appears to be determining the API call to make based on the page argument to alert_stats.lua. For SNMP it uses /lua/rest/v2/delete/snmp_device/alerts.lua. However, the API indicates that for SNMP the correct call is /lua/pro/rest/v2/delete/snmp/device/alerts.lua. I believe this is also true for acknowledgements.

Code to fix appears to be https://github.com/ntop/ntopng/blob/6bc1faa02dc175cee749bf792776920a637f1c45/http_src/vue/modal-delete-alert.vue#L40 and https://github.com/ntop/ntopng/blob/6bc1faa02dc175cee749bf792776920a637f1c45/http_src/vue/modal-acknowledge-alert.vue#L48 and https://github.com/ntop/ntopng/blob/6bc1faa02dc175cee749bf792776920a637f1c45/http_src/vue/modal-acknowledge-alerts.vue#L67 and https://github.com/ntop/ntopng/blob/6bc1faa02dc175cee749bf792776920a637f1c45/http_src/vue/modal-delete-alerts.vue#L84

**Comment by MatteoBiscosi** [comment]
Hi @dukrat thanks for reporting, the issue should be fixed in the next update, in a couple of hours update and let me know.

**Comment by dukrat** [comment]
Indeed. Thanks for the fix.
