### ISSUE TITLE
Critical Flow to push.services.mozilla.com

### ISSUE THREAD

**Issue by takenek** [ntop/ntopng#8725]
Hey,
Why ntopng block all the time connection to push.services.mozilla.com ?
20/09/2024 08:03:35  [Interface: eth1] [Severity: ❗ Critical] [Flow] [Blacklisted Server Contact] [XXX:4381 -> 34.107.243.93:443]
Blacklisted Server [ Blacklist: "IPsum Threat Intelligence Feed" ]

We use: ntopng Enterprise M v.6.2.240909 rev.24443 (Debian GNU/Linux 12 (bookworm)) 
Best Regards
TaKeN

**Comment by lucaderi** [comment]
This flow is blocked as listed in "IPsum Threat Intelligence Feed" . if you believe this is a problem, please disable such feed.

**Comment by takenek** [comment]
Could you please investigate further? I believe this is a false positive. Completely disabling the IPsum Threat Intelligence Feed would not be a good solution.

**Comment by lucaderi** [comment]
It is not under our responsibility as I have said. Contact  IPsum Threat Intelligence Feed as they are providing the information

**Comment by takenek** [comment]
Ohhh... i buy product from You not from "IPsum Threat Intelligence Feed" but ok... nice support!

Thanks.
