### ISSUE TITLE
Export SNMP Polled Data

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8726]
On the page below, during troubleshooting,
<img width="734" alt="Screenshot 2024-09-20 at 08 54 39" src="https://github.com/user-attachments/assets/87c112b2-636e-4a41-acfb-646925377759">
it is required to export not just the SNMP configuration but also polled data.

It is up to the implementor to export config+data in the above existing page (i.e. only change the backend) or add a new entry (SNMP + data) for implementing it

**Comment by MatteoBiscosi** [comment]
This issue seems fixed, please reopen in case any problem is found
