### ISSUE TITLE
Request to disable disconnection due to inactivity

### ISSUE THREAD

**Issue by shabi61** [ntop/ntopng#8728]
Would it be possible to disable the disconnection functionality of a MAC address (IP) in case of inactivity? Despite setting the MAC address cache to 1 day, it seems that users connected with a code are being disconnected after only 10 minutes.

**Comment by lucaderi** [comment]
This is a duplicate of https://github.com/ntop/ntopng/issues/8684 implemented more than 3 weeks ago
