### ISSUE TITLE
NTOPNG License issue.

### ISSUE THREAD

**Issue by haseebjinnah** [ntop/ntopng#8729]
**Environment**:
* OS name: [e.g. Ubuntu]
* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [e.g. 5.1.211223]

**What happened**:

Hey hope you are well we just entered a license key now and registered as per given link with our systemId and license key once we entered its registered and status shows valid license but after that counter starts and again status not valid and its unlicensed so please let us know its a bit delay to deploy because we arrange server physical hardware and now its all set to run NTOPNG kindly help me we are waiting.
Platform :  Ubuntu 24.04 LTS [x86_64] - 64 bit

**How did you reproduce it?**

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
Hi @haseebjinnah sorry but i didn't understand the issue, you purchased/renew the license and when putting the license in ntopng it shows that is not valid? Could you please share a couple of screenshots (remember to remove the license from key from the screenshots)

**Comment by haseebjinnah** [comment]
[ntopng - License.pdf](https://github.com/user-attachments/files/17108399/ntopng.-.License.pdf)

Hi @MatteoBiscosi the above issue is attached we are from university non-profit research organization ntop gives a ntopng enterprise XL 64bit license key
[ntopng - License.pdf](https://github.com/user-attachments/files/17108491/ntopng.-.License.pdf)
 once we enter a license key its shows valid license but after 3 minutes its not valid as above attached file shows so kindly resolve it as soon as we are facing issue not using properly NTOPNG.

**Comment by MatteoBiscosi** [comment]
Hi @haseebjinnah could you please check if you have correctly configured the ntopng license file?
cat /etc/ntopng.license
In case the file is not present then you need to put your license there.
e.g.
echo "LICENSE" > /etc/ntopng.license
https://www.ntop.org/guides/ntopng/adding_a_license/index.html
Then restart ntopng and you should have the license, to check that you can run ntopng --version from the terminal and you should see your license and the expiration time

**Comment by haseebjinnah** [comment]
Hello @MatteoBiscosi yes we checked its now accepted and licensed now key its working fine thank you so much.

**Comment by MatteoBiscosi** [comment]
Okay, thanks a lot for reporting @haseebjinnah
