### ISSUE TITLE
Wrong timestamp when using dynamic vlan interfaces

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#873]
All flows have timestamp as of 01/01/1970 01:00:00, when using dynamic vlan interfaces.
This also applies to hosts first / last seen, in a short period of time I have 100k+ flows on a home network.
Date on the host that runs ntopng is correct.
Version	2.5.161225 - Community/Embedded Edition
Built on	Raspbian GNU/Linux 8.0 (jessie)

![2016-12-27 01_25_35-welcome to ntopng - chromium](https://cloud.githubusercontent.com/assets/7170155/21487783/e55f7f68-cbd3-11e6-92de-65511d32df22.png)
![2016-12-27 01_27_18-welcome to ntopng - chromium](https://cloud.githubusercontent.com/assets/7170155/21487782/e55ebe52-cbd3-11e6-8c8f-2cbe58df0f60.png)
![2016-12-27 01_27_53-welcome to ntopng - chromium](https://cloud.githubusercontent.com/assets/7170155/21487784/e5610a9a-cbd3-11e6-92a8-b1663c647a91.png)

**Comment by ghost** [comment]
Hi, any updates on this? Can you reproduce it or is there a problem with my installation?

**Comment by emanuele-f** [comment]
I can reproduce with pcap file provided in #906. Possibly it is related to the same issue.
