### ISSUE TITLE
Inconsistent/Non-existent historical data

### ISSUE THREAD

**Issue by dpkano** [ntop/ntopng#8733]
**Environment**:
* OS name: Debian GNU/Linux (Raspberry PI OS)
* OS version: 12 (bookworm)
* Architecture: aarch64 (Raspberry Pi 4 Model B Rev 1.5)
* ntopng version/revision: 6.3.240929 [Enterprise/Professional build]
* ntopng edition: Professional Embedded
* nprobe version/revision: 10.7.240928
* nprobe edition: nProbe Embedded

ntopng.conf:
```
-G=/var/run/ntopng.pid
-i=tcp://127.0.0.1:5556
--local-networks=10.0.0.0/8
```

nprobe.conf
```
-i=none
-n=none
-3=2055
-T="@NTOPNG@"
--ntopng=zmq://127.0.0.1:5556
```
Setup (https://www.ntop.org/ntopng/how-to-analyse-mikrotik-traffic-using-ntopng/):
![image](https://github.com/user-attachments/assets/088b8b4c-90d2-4418-a6b6-ac9e3962d05b)

**What happened**:
The historical data for hosts rarely displays data. For most of my hosts, when I click the chart icon in the hosts page, nothing is displayed. For a very  few hosts (e.g. my local DNS server), it shows inconsistent data like the chart below:
![image](https://github.com/user-attachments/assets/c288cabf-2b27-4f0d-9df3-ee9a17608103)

**How did you reproduce it?**
- Go to: [ntopng host]:3000/lua/host_details.lua?host=[any host]
- Click the historical data icon:
   ![image](https://github.com/user-attachments/assets/4a456a44-e972-4e4d-a648-916ee87be87d)
- This is what's displayed for the majority of my hosts:
   ![image](https://github.com/user-attachments/assets/81499c64-d0ed-407f-b75f-15fe2834f06b)

**Debug Information**:

"systemctl status ntopng"
![image](https://github.com/user-attachments/assets/7763e967-341d-4930-b18f-e67ca6ab4c56)

**Comment by dpkano** [comment]
Extra info: I've disabled nprobe and started sending mirrored traffic to ntopng's interface. Nothing changed in the historical data. I still can't see anything. There are no errors in the ntopng logs. Are there any tips where I can start debugging this?

**Comment by MatteoBiscosi** [comment]
Hi @dpkano could you please send a screenshot of an host details that has that issue?
![image](https://github.com/user-attachments/assets/bec3659b-4448-45a4-99b8-0bee4e17a7c7)

**Comment by dpkano** [comment]
Yep, here it they are:
<img width="1847" alt="image" src="https://github.com/user-attachments/assets/556a68c9-6797-4257-80cf-c73ad88d7a38">

The MAC one:
<img width="908" alt="image" src="https://github.com/user-attachments/assets/8a0b5b95-af62-4402-b3ed-c2a3e2d76707">

And the empty historical chart:
<img width="910" alt="image" src="https://github.com/user-attachments/assets/3728ce5a-26bc-4cc5-803a-1113c516006f">

**Comment by MatteoBiscosi** [comment]
Hi, probably the reason is because you did not enable the One Way Traffic Timeseries option from the settings (see below).
By default is disabled because in case of ddos attacks or scans it could lead to a huge amount of timeseries created and possibly to full the disk of the machine, so keep in mind this point. In case you are not intersted in this possibility just simpli enable the preference just like in the screenshot.
![image](https://github.com/user-attachments/assets/845cd3f1-417d-42c5-97b3-ac17c2f94091)

**Comment by dpkano** [comment]
yes. This seems to be the case. Now I can see traffic for many (if not all) of the hosts that had never displayed traffic before. But why? It's not clear from that screen that enabling it would allow traffic to be recorded for all hosts.

Thanks!
