### ISSUE TITLE
NTOPNG db sits in ramdisk on pfsense

### ISSUE THREAD

**Issue by HotNoob** [ntop/ntopng#8735]
**Environment**:
* OS name: PFSENSE
* OS version: 2.7.2-RELEASE
* Architecture: amd64
* ntopng version/revision: ntopng Community v.5.6.240304 rev.0 (FreeBSD 14.0) 

**What happened**:
by default, ntopng puts it's db files in /var/db/ntopng
when ramdisk is enabled in pfsense, the files are now sitting on the ramdisk and it can be quickly filled up. 

**How did you reproduce it?**

ntopng on pfsense \w ramdisk enabled. 

**Debug Information**:
```
/var/db: du -sh * | sort -hr | head
317M    ntopng
 12M    rrd
8.1M    pkg
748K    captiveportaldn.rules
560K    cpelements
```

i think ntopng is using redis ( .rdb ) which loads to the memory, so i think this shouldn't be in ramdisk. 
changing the default location from:
`/var/db/ntopng`
to:
`/var/db/pkg/ntopng`

should do the trick.

**Comment by lucaderi** [comment]
We will add this to the user's guide, thank you. Unfortunately, this is all we can do, as the redis package is not under our control.
