### ISSUE TITLE
WARNING: [LICENSE]

### ISSUE THREAD

**Issue by nzqadri** [ntop/ntopng#8739]
can you please help me to resolve this warning it was working fine for me but i have upgraded now facing this issue 

**Environment**:
Version:	6.3.241001 [Enterprise/Professional build]
GIT rev:	dev:6fa13808f5c61df22eecb9302d81ee2a8878b13b:20241001
Pro rev:	r6823
Built on:	Ubuntu 20.04.6 LTS
System Id:	L1C9D15EB7607AB1F--U1C9D15EB760FF1BC--OL
Platform:	x86_64
Edition:	Community
License Type:	Time-Limited [Empty license file]
Validity:	Until Wed Oct  2 15:39:30 2024

**What happened**:
Oct  2 15:19:12 ntopng[192122]: 02/Oct/2024 15:19:12 [NtopPro.cpp:696] WARNING: [LICENSE] Invalid license [Empty license file]
Oct  2 15:19:12 ntopng[192122]: 02/Oct/2024 15:19:12 [NtopPro.cpp:725] WARNING: [LICENSE] ntopng will now run in Enterprise XL edition for 10 minutes
Oct  2 15:19:12 ntopng[192122]: 02/Oct/2024 15:19:12 [NtopPro.cpp:731] WARNING: [LICENSE] before returning to community mode
Oct  2 15:19:12 ntopng[192122]: 02/Oct/2024 15:19:12 [NtopPro.cpp:733] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
Oct  2 15:19:12 ntopng[192122]: 02/Oct/2024 15:19:12 [NtopPro.cpp:737] WARNING: [LICENSE] or run ntopng in community mode starting
Oct  2 15:19:12 ntopng[192122]: 02/Oct/2024 15:19:12 [NtopPro.cpp:739] WARNING: [LICENSE] ntopng --community
Oct  2 15:19:12 kernel: device ens4 entered promiscuous mode

**How did you reproduce it?**

**Debug Information**:
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
     Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2024-10-02 15:19:11 UTC; 22min ago
   Main PID: 192122 (ntopng-main)
      Tasks: 49 (limit: 4680)
     Memory: 218.1M
     CGroup: /system.slice/ntopng.service
             └─192122 /usr/bin/ntopng /run/ntopng.conf

Oct 02 15:19:18 ntopng[192122]: 02/Oct/2024 15:19:18 [startup.lua:207] Initializing timeseries...
Oct 02 15:19:18 ntopng[192122]: 02/Oct/2024 15:19:18 [startup.lua:316] Completed startup.lua
Oct 02 15:19:18 ntopng[192122]: 02/Oct/2024 15:19:18 [NetworkInterface.cpp:3812] Started packet polling on interface 'lo' [id: 1]...
Oct 02 15:19:18 ntopng[192122]: 02/Oct/2024 15:19:18 [NetworkInterface.cpp:3812] Started packet polling on interface 'ens4' [id: 2]...
Oct 02 15:19:18 ntopng[192122]: 02/Oct/2024 15:19:18 [NetworkInterface.cpp:3812] Started packet polling on interface 'docker0' [id: 3]...
Oct 02 15:19:19  ntopng[192122]: 02/Oct/2024 15:19:19 [NetworkInterface.cpp:2510] Packets exceeding the expected max size have been received [ens4][len: 2373][max len: 1478].
Oct 02 15:19:19  ntopng[192122]: 02/Oct/2024 15:19:19 [NetworkInterface.cpp:2516] WARNING: If TSO/GRO is enabled, please disable it for best accuracy
Oct 02 15:19:19  ntopng[192122]: 02/Oct/2024 15:19:19 [NetworkInterface.cpp:2516] WARNING: If TSO/GRO is enabled, please disable it for best accuracy
Oct 02 15:19:19  ntopng[192122]: 02/Oct/2024 15:19:19 [NetworkInterface.cpp:2520] WARNING: using: sudo ethtool -K ens4 gro off gso off tso off
Oct 02 15:19:19 ntopng[192122]: 02/Oct/2024 15:19:19 [NetworkInterface.cpp:2520] WARNING: using: sudo ethtool -K ens4 gro off gso off tso off

**Comment by MatteoBiscosi** [comment]
Hi @nzqadri which warning, about the license? In that case you have to check the /etc/ntopng.license file if it's empty, in case you have to add the license in that file and restart ntopng.
You can follow this guide to recover the license: https://www.ntop.org/faq/how-to-recover-issued-licenses/

**Comment by nzqadri** [comment]
Basically I was using 18.04 and upgrade to 20.04 OS using free version which
automatically licensed somehow but here it's not working.

**Comment by lucaderi** [comment]
The warning is ok. If you do not like it, please use the --community CLi flag
