### ISSUE TITLE
Refresh Redis::_set code

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8742]
The following method
int Redis::_set(bool use_nx, const char *key, const char *value, u_int expire_secs)

needs to be refreshed as follows
- remove use_nx support as SETNX is obsolete
- for non zero expire_secs, avoid calling redis twice and use the EX parameter of the SET

See https://redis.io/docs/latest/commands/set/

**Comment by MatteoBiscosi** [comment]
Following the documentation, the SETNX has been moved to the NX parameter of the SET command, unfortunatly some code cleaning cannot be done due to the hiredis library (for example having just one command that adds options in case NX or EX is set)
