### ISSUE TITLE
Input/Output Value Resets to 0 After Device Stays Connected Without Wi-Fi Interaction

### ISSUE THREAD

**Issue by shabi61** [ntop/ntopng#8743]
Description:
As per our investigation, the issue can be reproduced consistently. After the device remains connected for a certain period without interaction with the Wi-Fi, the input/output value resets to 0.

Please find the following details:

PCAP file: Attached in email
Example of input/output values reset to 0: Attached in email
Steps to reproduce:

Connect the device to the Wi-Fi.
Leave the device connected but without any interaction with the Wi-Fi for an extended period.
Observe the traffic and input/output values; the input/output eventually resets to 0.

<img width="1440" alt="Screenshot 2024-10-04 at 15 15 24" src="https://github.com/user-attachments/assets/07c10f0d-458a-4f3a-94ee-5445864f329f">

**Comment by MatteoBiscosi** [comment]
The issue seems fixed, in case it is not, reopen the ticket
