### ISSUE TITLE
Search Box Partially Working

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8745]
On FreeBSD the search box does not work with anything

<img width="1248" alt="Screenshot 2024-10-04 at 17 31 00" src="https://github.com/user-attachments/assets/5a943ffb-b5ee-4244-a2b8-38c34d1f01a7">

On other platforms it works for MACs but not for strings (example shellypro)

**Comment by MatteoBiscosi** [comment]
![image](https://github.com/user-attachments/assets/bd51f0f4-d9db-44d0-9ae7-ca3f2aff5438)

**Comment by MatteoBiscosi** [comment]
This issue seems fixed, please reopen in case any problem is found
