### ISSUE TITLE
Empty Pool Charts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8748]
When creating a host pool, the charts or the pool is properly populated, but those of the hosts belonging to the pool are empty

**Comment by lucaderi** [comment]
This warning should also be fixed
[LINT] validateParameter failed for parameter [pool][function]
 string host

**Comment by MatteoBiscosi** [comment]
The problem is not present, the hosts not showing timeseries are remote hosts, which is correct, not being available timeseries for remote hosts in ntopng
