### ISSUE TITLE
Empty Top Visited Sites with View Interfaces

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8749]
<img width="1377" alt="Screenshot 2024-10-09 at 09 36 15" src="https://github.com/user-attachments/assets/0a527d81-7313-4273-91bd-2d0c77181d49">

**Comment by MatteoBiscosi** [comment]
Verified as fixed
![image](https://github.com/user-attachments/assets/4b4ce069-f2c2-4cbf-a94e-c8870d74bdc2)
