### ISSUE TITLE
Empty Alerts Flow view

### ISSUE THREAD

**Issue by PaoGRodrigues** [ntop/ntopng#8754]
**Environment**:
* OS name: Raspbian
* Architecture: arm64
* ntopng version/revision: 6.3.241007

**What happened**:
I coundn't see alerts in Alert page, Flow section. 
I configured a check **Blacklisted Country** with US to probe that there are alerts.

I coundn't see alerts in Flow section, but when I selected a flow, I found the security check!

**How did you reproduce it?**
The new version has the bug.

_Alerts > Explore > Flow alerts (empty)_
<img width="1366" alt="Captura de pantalla 2024-10-09 a la(s) 12 56 25 p  m" src="https://github.com/user-attachments/assets/13c7ecf2-b90e-4af2-b2d2-a2ca178d12cb">

_Flow with the detection inside_
<img width="1364" alt="Captura de pantalla 2024-10-09 a la(s) 12 56 40 p  m" src="https://github.com/user-attachments/assets/7fa45a55-e7b9-4dbb-86f1-3095044a4e13">

**Comment by MatteoBiscosi** [comment]
Hi @PaoGRodrigues i moved the blacklisted country in the Important tab (the one you are checking).
However the alerts should still be available; please click on the Red Icon (screenshot below) and you should be able to see all the alerts not just the important ones
![image](https://github.com/user-attachments/assets/020a7d98-9d0c-4143-9183-4eb5b901e8d9)

**Comment by MatteoBiscosi** [comment]
This issue seems fixed, please reopen in case any problem is found
