### ISSUE TITLE
Notifications to Mattermost cause errors

### ISSUE THREAD

**Issue by horned1** [ntop/ntopng#8756]
**Environment**:
* OS name: Alma
* OS version: 9.4
* Architecture: amd64
* ntopng version/revision: ntopng-6.2.240902-24395

**What happened**:
Enabling notifications to Mattermost gives the following error in the logs every time a notification is sent. Notification reaches Mattermost and looks OK though. except of course that the errors themselves are posted to mattermost..

Before the notifications were setup I did not see these errors. 

**How did you reproduce it?**
Seen in the logs every time a notification is sent

**Debug Information**:
( /var/log/ntopng.log)
[LuaEngine.cpp:702] WARNING: ...ipts/lua/modules/notifications/endpoints//mattermost.lua:76: attempt to index a boolean value (local 'post_rc') [/usr/share/ntopng/scripts/callbacks/5second/system/notifications.lua]

( systemctl status ntopng )

[LuaEngine.cpp:702] WARNING: ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:101: attempt to index a nil value (local 'schema') [/usr/share/ntopng/scripts/callbacks/5second/system/upload_timeseries.lua]
[LuaEngine.cpp:702] WARNING: ...ipts/lua/modules/notifications/endpoints//mattermost.lua:76: attempt to index a boolean value (local 'post_rc') [/usr/share/ntopng/scripts/callbacks/5second/system/notifications.lua]

**Comment by MatteoBiscosi** [comment]
The issue should be fixed

**Comment by horned1** [comment]
Thank you, errors are gone after your changes
