### ISSUE TITLE
Flows information Miss in Elastic Index

### ISSUE THREAD

**Issue by nikopuf** [ntop/ntopng#8761]
**ntopng -i ens192 -F "es;ntopng;ntopng-%Y.%m.%d;http://120.120.1.202:9200/_bulk;" --http-port 4000 --ignore-vlans** this is how i run ntop to push data in elastic but when i go in my elastic index i didnt fine ja3 ja3s information in index,

what is the recommend version of elastic search i am using 7.16.3?

OS: ubuntu 18.04

**Comment by MatteoBiscosi** [comment]
Ja3/ja4 info are not exported to the elastic flows, only basic info about flows are exported to the elastic
