### ISSUE TITLE
Filters of historical flow dosen't work

### ISSUE THREAD

**Issue by Achronium** [ntop/ntopng#8764]
**Environment**:
* OS name:Rocky Linux
* OS version:8.10
* Architecture:x86_64
* ntopng version/revision:6.3.241022

**What happened**:
Filter button don't appear in historical flow
Date interface doesn't work in historical flow
unable to select object in listed flow to add filter
Only ntop historical flow web interface seems impacted
Date of when it started is unsure : Less than a week

**How did you reproduce it?**
open web interface of historical flow in ntop

**Debug Information**:
--started ntopng without v="6"  in my ntopng.conf--
sudo[47394]: pam_unix(sudo:auth): conversation failed
sudo[47394]: pam_unix(sudo:auth): auth could not identify password for [ntopng]
sudo[47394]:   ntopng : user NOT in sudoers ; PWD=/ ; USER=root ; COMMAND=/usr/bin/ntopctl n2disk-ntopng stats
Oct 22 16:12:03 bigflo.univ-rennes1.fr ntopng[42283]: 22/Oct/2024 16:12:03 [LuaEngine.cpp:1499] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/filter/consts.lua][/usr/share/ntopng/scripts/lua/modules/tag_utils.lua:1369: bad argument #1 to 'for iterator' (table expected, got number)]
--started ntopng as  -v="6" in my ntopng.conf--
sudo[50873]: pam_unix(sudo:auth): conversation failed
sudo[50873]: pam_unix(sudo:auth): auth could not identify password for [ntopng]
sudo[50873]:   ntopng : user NOT in sudoers ; PWD=/ ; USER=root ; COMMAND=/usr/bin/ntopctl n2disk-ntopng stats
systemd-journald[1197]: Suppressed 246035 messages from ntopng.service
ntopng[49364]: 22/Oct/2024 16:28:01 [LuaEngine.cpp:472] [ntop_lua_require] Searching /usr/share/ntopng/scripts/lua/modules/alert_definitions/flow/alert_ndpi_tls_uncommon_alpn.lua
ntopng[49364]: 22/Oct/2024 16:28:01 [LuaEngine.cpp:472] [ntop_lua_require] Searching /usr/share/ntopng/scripts/lua/pro/modules/rest_utils.lua
ntopng[49364]: 22/Oct/2024 16:28:01 [ZMQParserInterface.cpp:2228] Not handled ZMQ field 35632.527
--going on for a long time--
- ![capture](https://github.com/user-attachments/assets/7a77fe97-8650-4386-8fe3-8e0937535f26)

**Comment by MatteoBiscosi** [comment]
Hi @Achronium the issue should be fixed, a new build should be available in an hour or so, please when available update and let me know

**Comment by Achronium** [comment]
Hello,
Thanks for your reponse but, i can't test/reproduce it anymore,
Searching for a solution, i endened up turning to stable (6.2.241022) version and it solved my problems at the same time you posted the fixe
hope my precedent post still helped to something
