### ISSUE TITLE
SNMPv3 unhandled SNMP response in case of bad credentials

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#8766]
As a workaround, the device has been imported via JSON, and there are SNMP timeouts (not sure if related). 
Logs:
 
[SNMP.cpp:230] WARNING: Unhandled pdu command 168
[SNMP.cpp:230] WARNING: Unhandled pdu command 168

**Comment by lucaderi** [comment]
This can be reproduced with
snmpwalk -v 3 -u authUser -l authPriv -a MD5 -A wrongpassword -x DES -X privpassword localhost

**Comment by MatteoBiscosi** [comment]
This issue seems fixed, please reopen in case any problem is found
