### ISSUE TITLE
ntop/ntopng.dev docker container not working 

### ISSUE THREAD

**Issue by mmaxwellhorn** [ntop/ntopng#8768]
**Environment**:
* OS name: Docker ntop/ntopng.dev
* OS version: latest
* Architecture: x64
* ntopng version/revision: 

**What happened**:

When running the latest version of ntop/ntopng.dev the ntopng container fails to run properly.  

**How did you reproduce it?**

Using the latest container for ntop/ntopng.dev

**Debug Information**:

**Comment by MatteoBiscosi** [comment]
could you provide more info? what do you mean with "fails to run properly"? you are not able to start ntopng? it crashes?

**Comment by cardigliano** [comment]
Latest image seems to be working for me
