### ISSUE TITLE
Historical Flow Filter Does not Appear (Errors out)

### ISSUE THREAD

**Issue by dkggpeters** [ntop/ntopng#8769]
**Environment**:
* OS name: Ubuntu
* OS version: 22.04
* Architecture: amd64
* ntopng version/revision: 6.3.241022 Enterprise L

**What happened**:
Within Historical Flows the filter open does not appear and the below error is generated.  

**Debug Information**:
![image](https://github.com/user-attachments/assets/7296269a-3639-433e-b39d-01d329208c2f)

**Comment by MatteoBiscosi** [comment]
Please update to the latest ntopng version, the issue should be fixed

**Comment by dkggpeters** [comment]
Fixed.  Thank you.
