### ISSUE TITLE
Incomplete ClickhouseDB Table Definition

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8776]
ClickHouse DB schema is incomplete and it works only because ALTER TABLE add missing columns
https://github.com/ntop/ntopng/blob/dev/httpdocs/misc/db_schema_clickhouse.sql

**Comment by cardigliano** [comment]
Fixed in fb30f7592fa23d9333db7459d53e05f6fbb82f2c

**Comment by lucaderi** [comment]
Verified as fixed
