### ISSUE TITLE
Enhance Flow Exporters

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8777]
In the flow exporters probe page lua/pro/enterprise/nprobe.lua, it would be nice to see how many interfaces are being monitored per nprobe instance as well as in the exporters page, how many interfaces per exporter, like in the images attached. The graphic above the table on those pages seems to indicate number of interfaces for each exporter but it's so squished together that it's not that usable. It would be nice to have it in the table to be able to sort by.

![image](https://github.com/user-attachments/assets/455df46a-e714-41a2-8eb2-7d1ebd135a88)
![image](https://github.com/user-attachments/assets/3b7047ee-d04b-4eb6-a9c9-e616a5b5f7c6)

**Comment by Westy-87** [comment]
Hi there, I updated this morning but don't see any interface numbers. These are the available columns:
Exporters page: 
![image](https://github.com/user-attachments/assets/0a476496-dd8d-40ba-b72c-6f988257392b)
Probes page:
![image](https://github.com/user-attachments/assets/cb78120c-54e4-4fc2-be85-0ab34d3f66f2)
![image](https://github.com/user-attachments/assets/0fa41918-4ecc-4eba-828e-e70fa8f7b401)

**Comment by MatteoBiscosi** [comment]
Hi @Westy-87 which ntopng are you currently running? this enchantment is currently available only for the dev version (6.3)

**Comment by Westy-87** [comment]
Ah sorry I am not running dev version. I am off for the next three weeks too.

**Comment by lucaderi** [comment]
Verified as fixed

**Comment by Westy-87** [comment]
@lucaderi has this made it to stable release yet?

**Comment by Westy-87** [comment]
I still don't see anything indicating how many interfaces per probe or exporter in latest stable release?
