### ISSUE TITLE
local networks not parsed correctly from config

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#878]
"Commas separate multiple network values.  Both netmask and CIDR notation may be used, even mixed together, for instance "131.114.21.0/24,10.0.0.0/255.0.0.0"

1. Networks after the first comma are not parsed at all, hosts are marked as remote in overview.
2. netmasks / cidr notation don't match, see screenshots attached.

![2016-12-28 14_01_09-welcome to ntopng - chromium](https://cloud.githubusercontent.com/assets/7170155/21522818/263503ba-cd09-11e6-81cd-cfc7c953f5b1.png)
![2016-12-28 14_16_17-welcome to ntopng - chromium](https://cloud.githubusercontent.com/assets/7170155/21522822/2d2c8e22-cd09-11e6-8ec1-29113ab180c4.png)

**Comment by simonemainardi** [comment]
presently /CIDR notation is not supported, only the number of bits. Would you be able to help us to add that support? The function you should extend is ` Utils::ptree_add_rule`

**Comment by filemoon** [comment]
I'd like to confirm local network are broken.

config:
-G=/var/log/ntopng.pid
-d=/var/lib/ntopng
-i=tcp://127.0.0.1:5556
-m="10.0.1.0/24,10.0.2.0/24,10.0.0.0/24"
-n=1
-X=100000
-x=16000
version: 
![screen shot 2017-01-03 at 10 55 35](https://cloud.githubusercontent.com/assets/14888287/21605780/313fd9bc-d1a3-11e6-93e6-dd73f26379e0.jpg)

log:
![screen shot 2017-01-03 at 10 54 55](https://cloud.githubusercontent.com/assets/14888287/21605765/1e84102c-d1a3-11e6-912a-1b3a9f15ecab.jpg)

issue:
![screen shot 2017-01-03 at 10 56 19](https://cloud.githubusercontent.com/assets/14888287/21605818/6876e948-d1a3-11e6-9ca4-083a9728769d.jpg)

**Comment by simonemainardi** [comment]
@filemoon fix has been introduced on Dec 27 (https://github.com/ntop/ntopng/commit/476e43d677f860010c7895c402e62458336a6529) please update to the latest dev version and report. thank you

**Comment by filemoon** [comment]
Hi.


Thank you for update.

I have latest version from repository.
I will wait until arm repository is updated.

**Comment by simonemainardi** [comment]
@filemoon the new arm build is cooked. Please try that out and let us know.

**Comment by ghost** [comment]
just wanted to confirm that the issue has been fixed in the current release, thanks

**Comment by filemoon** [comment]
Issue sorted - thank you.

**Comment by simonemainardi** [comment]
thanks for reporting @olliff @filemoon
