### ISSUE TITLE
Host Metrics Timeseries do not populate for Hosts with a Host Name

### ISSUE THREAD

**Issue by dkggpeters** [ntop/ntopng#8787]
**Environment**:
* OS name: Ubuntu
* OS version: 22.04
* Architecture: amd64
* ntopng version/revision: Enterprise L 6.3.241028

The hosts history graphs do not populate for hosts that have Host Names that can resolved via DNS.  Hosts with no Host Names populate the graphs properly

**Computer with host name**
![image](https://github.com/user-attachments/assets/7491e9e3-a8d4-420b-9f70-9d520ee4a546)
![image](https://github.com/user-attachments/assets/55d50b83-2e9a-4f88-99d9-894ca3dfd9f8)

**Device with no hostname**

![image](https://github.com/user-attachments/assets/0162a048-3d87-4afe-b183-a2c2f0fc2cba)

This is consistent with all devices.  For devices with Host Names, I have to go through the Mac Address for the device to get the graphs.  I do have the LAN interface setup for Local Broadcast Domain Hosts Identifier as MAC Address

![image](https://github.com/user-attachments/assets/a374e6f9-6256-4898-9448-a590c36be93f)

**Comment by MatteoBiscosi** [comment]
Hi @dkggpeters in a couple of hours a new build with the fix should be available, please update and let me know

**Comment by dkggpeters** [comment]
Fixed.  Thank you.
