### ISSUE TITLE
Repo broken?

### ISSUE THREAD

**Issue by bbabich** [ntop/ntopng#879]
Hi there,

It looks like something is up with your repo:

# apt-get update 
....
W: Failed to fetch http://packages.ntop.org/apt/jessie/all/Packages  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.

--

# cat /etc/apt/sources.list.d/ntop.list
deb http://packages.ntop.org/apt/jessie/ x64/
deb http://packages.ntop.org/apt/jessie/ all/

---

Perhaps:
https://blog.packagecloud.io/eng/2016/03/21/apt-hash-sum-mismatch/

Cheers.

**Comment by cardigliano** [comment]
Hi
it seems it is working for me, did you follow the steps described at http://packages.ntop.org/apt/ <http://packages.ntop.org/apt/> ?

Best Regards
Alfredo

**Comment by bbabich** [comment]
Looks like it magically started working again :)
