### ISSUE TITLE
Issues after deploy on container 

### ISSUE THREAD

**Issue by tuanama00** [ntop/ntopng#8792]
**Environment**:
* OS name: Ubuntu
* OS version: 24.04
* Architecture: amd64
* ntopng version/revision: 6.2.24

**What happened**:
After deploy in container using this command:
set container name ntopng arguments '--community -i eth0 -i eth1 -i eth2 -i wg0 -i vti1 -i vti0 -d /var/lib/ntopng -r 127.0.0.1:6379@0 -w 172.10.20.3:3001'

I get this error:
01/Nov/2024 23:39:28 [main.cpp:269] Unable to open interface eth1 [97]: PF_RING not loaded. Falling back to pcap.
01/Nov/2024 23:39:28 [PcapInterface.cpp:127] Reading packets from eth1 [ifId: 0]
01/Nov/2024 23:39:28 [Ntop.cpp:2839] Registered interface 'eth1' [id: 0]
01/Nov/2024 23:39:28 [NetworkInterface.cpp:3841] Cleanup interface eth0
01/Nov/2024 23:39:30 [main.cpp:269] Unable to open interface eth0 [97]: PF_RING not loaded. Falling back to pcap.
01/Nov/2024 23:39:30 [PcapInterface.cpp:127] Reading packets from eth0 [ifId: 1]
01/Nov/2024 23:39:30 [Ntop.cpp:2839] Registered interface 'eth0' [id: 1]
01/Nov/2024 23:39:31 [NetworkInterface.cpp:3841] Cleanup interface eth2
01/Nov/2024 23:39:31 [main.cpp:269] Unable to open interface eth2 [97]: PF_RING not loaded. Falling back to pcap.
01/Nov/2024 23:39:31 [PcapInterface.cpp:127] Reading packets from eth2 [ifId: 2]
01/Nov/2024 23:39:31 [Ntop.cpp:2839] Registered interface 'eth2' [id: 2]
01/Nov/2024 23:39:31 [NetworkInterface.cpp:144] ERROR: Failure initializing Network Discovery
01/Nov/2024 23:39:31 [NetworkInterface.cpp:3841] Cleanup interface vti0
01/Nov/2024 23:39:31 [main.cpp:269] Unable to open interface vti0 [97]: PF_RING not loaded. Falling back to pcap.
01/Nov/2024 23:39:31 [NetworkInterface.cpp:144] ERROR: Failure initializing Network Discovery
01/Nov/2024 23:39:31 [PcapInterface.cpp:127] Reading packets from vti0 [ifId: 4]
01/Nov/2024 23:39:31 [Ntop.cpp:2839] Registered interface 'vti0' [id: 4]
01/Nov/2024 23:39:31 [NetworkInterface.cpp:144] ERROR: Failure initializing Network Discovery
01/Nov/2024 23:39:31 [NetworkInterface.cpp:3841] Cleanup interface wg0
01/Nov/2024 23:39:31 [main.cpp:269] Unable to open interface wg0 [97]: PF_RING not loaded. Falling back to pcap.
01/Nov/2024 23:39:31 [NetworkInterface.cpp:144] ERROR: Failure initializing Network Discovery
01/Nov/2024 23:39:31 [PcapInterface.cpp:127] Reading packets from wg0 [ifId: 5]
01/Nov/2024 23:39:31 [Ntop.cpp:2839] Registered interface 'wg0' [id: 5]
01/Nov/2024 23:39:31 [NetworkInterface.cpp:144] ERROR: Failure initializing Network Discovery
01/Nov/2024 23:39:31 [NetworkInterface.cpp:3841] Cleanup interface vti1
01/Nov/2024 23:39:31 [main.cpp:269] Unable to open interface vti1 [97]: PF_RING not loaded. Falling back to pcap.
01/Nov/2024 23:39:31 [NetworkInterface.cpp:144] ERROR: Failure initializing Network Discovery
01/Nov/2024 23:39:31 [PcapInterface.cpp:127] Reading packets from vti1 [ifId: 6]
01/Nov/2024 23:39:31 [Ntop.cpp:2839] Registered interface 'vti1' [id: 6]

**How did you reproduce it?**

Using podman container 

**Debug Information**:

**Comment by lucaderi** [comment]
These warning/errors are perfectly fine
- you have not loaded PF_RING in the container hence the issues
- network discovery cannot be enabled on some interfaces inside a container
