### ISSUE TITLE
Move inactive host information from redis to a sql lite database

### ISSUE THREAD

**Issue by YellowMan02** [ntop/ntopng#8794]
**What would you like to add or change?**:
Inactive host/mac information is now stored on the redis server, and this causes high overhead every time it is necessary to retrieve information from multiple hosts/macs.

It would be useful to store this type of information in a database table to reduce this overhead. Redis can still be used to enqueue this information so that the database can be updated periodically.

**Comment by MatteoBiscosi** [comment]
This feature has been implemented as requested
