### ISSUE TITLE
ntopng 6.2 as Docker container on Synology NAS not working

### ISSUE THREAD

**Issue by G-3-3-R-T** [ntop/ntopng#8798]
**Environment**:
Synology DS1815+ with DSM 7.1.1
Docker version 20.10.3-1308
Interface: bond0
* ntopng version/revision: ntopng x86_64 v.6.2.241025 (6.2-stable:7ac2e318cdc24b70124c9fb1c32e0d7bfd1ee41b:20241025)

**What happened**:
In the past it has worked and I recenly noticed that it does not work anymore.

If I look in the logs I see that ntop always aborts with this message:
```
05/Nov/2024 21:04:58 [startup.lua:253] Completed startup.lua

Fatal glibc error: cannot get entropy for arc4random

/run.sh: line 3:    17 Aborted                 (core dumped) ntopng "$@" $NTOP_CONFIG
```

**How did you reproduce it?**

This is the Docker compose I use:
```
version: '3.9'
services: 
 ntopng:
    hostname: ntopng
    image: ntop/ntopng:stable
    container_name: ntopng
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    volumes:
      - /volume1/docker/ntopng:/var/lib/ntopng:rw
    network_mode: host
    command: --community
```

**Debug Information**:
```
05/Nov/2024 21:04:58 [startup.lua:253] Completed startup.lua

Fatal glibc error: cannot get entropy for arc4random

/run.sh: line 3:    17 Aborted                 (core dumped) ntopng "$@" $NTOP_CONFIG
```

**Comment by cardigliano** [comment]
The latest ntop/ntopng:stable image seems to be working fine for me. I guess it is related to the host OS (I am running on Ubuntu 22.04)

$ sudo docker run -it -v $(pwd)/ntopng.license:/etc/ntopng.license:ro --net=host ntop/ntopng:stable --version
Starting redis-server: redis-server.
Version:	6.2.241025 [Enterprise/Professional build]
GIT rev:	6.2-stable:7ac2e318cdc24b70124c9fb1c32e0d7bfd1ee41b:20241025
Pro rev:	r6784
Built on:	Ubuntu 24.04.1 LTS

**Comment by lucaderi** [comment]
@G-3-3-R-T If crashing we can provide you with a debug build if you can specify the exact OS distribution you are using

**Comment by G-3-3-R-T** [comment]
> @G-3-3-R-T If crashing we can provide you with a debug build if you can specify the exact OS distribution you are using

uname -a
`Linux DiskStation 3.10.108 #42962 SMP Fri Mar 24 00:28:41 CST 2023 x86_64 GNU/Linux synology_avoton_1515+`

cat /proc/version
`Linux version 3.10.108 (root@build7) (gcc version 8.5.0 (GCC) ) #42962 SMP Fri Mar 24 00:28:41 CST 2023`

**Comment by volandir** [comment]
I'm getting same exact error on DS916+:
```
Fatal glibc error: cannot get entropy for arc4random
/run.sh: line 3:    18 Aborted                 (core dumped) ntopng "$@" $NTOP_CONFIG
```
running on:
`Linux ds916 3.10.108 #72806 SMP Thu Sep 5 13:39:20 CST 2024 x86_64 GNU/Linux synology_braswell_916+`

I was wondering if you found any solution?

**Comment by G-3-3-R-T** [comment]
The problem occurs when using an older Linux kernel.

We need at least Kernel 3.17 to make ntopng to work.

Unfortunately the DS1517+ has an Avoton CPU and the DS916+ has a Braswell CPU, these models are build on Kernel 3.10.x even when you update tot the latest DSM 7.2.2

Look over here: 
[Synology Linux Kernel in each platform](https://github.com/007revad/Synology_Information_Wiki/blob/main/pages/Linux-Kernel-in-each-platform-arch.md)
