### ISSUE TITLE
Duplicated remediation links

### ISSUE THREAD

**Issue by cardigliano** [ntop/ntopng#8799]
In the below screenshot from the historical flow details page there are 3 icons/links to the remediations page in the doc, all pointing to the same page.

<img width="1201" alt="Screenshot 2024-11-06 at 09 02 07" src="https://github.com/user-attachments/assets/271d2af5-ad20-405f-9b9f-4875b05914ae">

**Comment by MatteoBiscosi** [comment]
The issue should be fixed, please in case there is some issue, reopen the ticket
