### ISSUE TITLE
Error in DPI for http ???

### ISSUE THREAD

**Issue by JuergenWeber** [ntop/ntopng#88]
I find very strange "hosts" when launching "http_servers_stats.lua": The server 10.187.127.45=brlnap69 runs Microsoft SCCM (1.6.0-dev-66-12f89ff):

![image](https://cloud.githubusercontent.com/assets/13195740/8742405/422a9fd0-2c65-11e5-8884-89402a3fb80d.png)

**Comment by lucaderi** [comment]
Please provide a pcap file of the traffic of such host to see what happens

**Comment by lucaderi** [comment]
@JuergenWeber Once you have a pcap please file an issue on nDPI (no ntopng)
