### ISSUE TITLE
Elephant flow alert is not working

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#8806]
As you can see, having set 1GB L2R and R2L threshold elephant flow is not detected if i tranasfer 2.97GB of data. This is not detected both on the live and historical flows alerts

<img width="2423" alt="Screenshot 2024-11-07 at 9 00 11 PM" src="https://github.com/user-attachments/assets/445f8fab-0a61-498b-b52f-c311a27e27ab">

<img width="1366" alt="Screenshot 2024-11-07 at 8 59 05 PM" src="https://github.com/user-attachments/assets/ba99b262-c35e-427d-9647-65201f2e3148">

**Comment by YellowMan02** [comment]
Alert works fine.
This issue describes when the flow is removed before the periodic check is performed. The alert is visible in the Alert section as expected.
