### ISSUE TITLE
An API to reload nedge remotely

### ISSUE THREAD

**Issue by iesreza** [ntop/ntopng#8808]
**What would you like to add or change?**:
Adding an API to remotely restart or reload Nedge would be highly beneficial. Since Nedge already has the internal capability to restart and reload configurations upon changes, exposing this as an API would allow third-party applications to initiate a restart after modifying configurations, streamlining integration and enhancing operational flexibility.

**Why do you and others need this?**:
Third parties occasionally need to modify Nedge configurations, especially in networks with multiple Nedge instances that require synchronized configurations. In such cases, after applying new configurations, the ability to remotely restart Nedge would ensure that the new settings are applied across all instances, simplifying configuration management and maintaining consistency in the network.

**Comment by MatteoBiscosi** [comment]
Hi @iesreza , like requested, the REST API has been added:
lua/rest/v2/get/ntopng/restart.lua
No parameters needed, this rest however can be run only by Admin users

**Comment by iesreza** [comment]
Hi @MatteoBiscosi. upon calling `lua/rest/v2/get/ntopng/restart.lua` i see following in logs:
```
06/Dec/2024 15:07:51 [LuaEngine.cpp:1499] WARNING: Script failure [/usr/share/ntopng/scripts/lua/rest/v2/get/ntopng/restart.lua][.../share/ntopng/scripts/lua/rest/v2/get/ntopng/restart.lua:10: attempt to call a nil value (global 'isAdministratorOrPrintErr')]
```
Also it is called by admin.

**Comment by MatteoBiscosi** [comment]
Hi @iesreza sorry for the trouble, i missed an import, it should work now
