### ISSUE TITLE
Timeseries for blacklists is not working

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#8817]
I have alerts regarding blacklisted client and server contact made by an IP from IPsum Threat Intelligence Feed but in the timeseries I do not see any hit.

<img width="1417" alt="Screenshot " src="https://github.com/user-attachments/assets/352e58d0-8e97-4f6f-9bde-2435768bfc10">

**Comment by MatteoBiscosi** [comment]
The blacklists timeseries works, the only problem is that it's an hits per second metric, so if you do not have enough blacklisted flows, you are not going to see nothing due to the low hit rate
![image](https://github.com/user-attachments/assets/f1a302b8-8e0d-4d79-a20b-c9524b503a9c)

**Comment by lucaderi** [comment]
Healthy networks have very few blacklist hits, hence you need to multiply the hits so that they are non-zero. Possible workarounds include hits/min

**Comment by MatteoBiscosi** [comment]
The issue should now be solved, moved the timeseries from counter to gauge, there is no possibility to include hits/min or whatsoever, the only solution i found was changing the timeseries type
![image](https://github.com/user-attachments/assets/06e02ba6-4b52-468e-abea-dde4b81a1514)

**Comment by DGabri** [comment]
Verified as fixed
