### ISSUE TITLE
Periodic Flow Improvement

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#8818]
**What would you like to add or change?**:

I would like to add in the DB and on the live flows or historical flows what is the periodicity of a flow when the alert: "Periodic Flow is triggered"

**Why do you and others need this?**:
To see very quickly what the periodicity is.

For example if I have a periodic flow i would like to know if the periodicity is 5 min, 1 minute etc. Add it to the info columns

**Comment by lucaderi** [comment]
![image](https://github.com/user-attachments/assets/b80171fe-dd4a-41a1-8f6a-334e4c0f9d4c)

**Comment by DGabri** [comment]
Completed
