### ISSUE TITLE
100.64.0.0/10 => rfc6598

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#882]
in ntop, 100.64.0.0/10 is considered as subnet block as other while it is not
even more 100.66.0.0/16 appears with ASN TOT Public Company Limited in ntop
![10066](https://cloud.githubusercontent.com/assets/17108017/21549735/9595b006-cdf4-11e6-80ad-6612cafa42db.PNG)

100.64/10 is Shared Address Space (rfc6598 : https://tools.ietf.org/html/rfc6598) so should appear like this in ntop

Nicolas

**Comment by simonemainardi** [comment]
IP in that range are properly categorized in the latest build, that is, no AS is assigned:

![image](https://cloud.githubusercontent.com/assets/3397663/21550915/c5578356-cdfd-11e6-9eba-704efc34f587.png)

please try to update to the latest version and do:
- `make geoip` if you are building from sources
- update package ntopng-data if you are working with packaged versions

**Comment by Niko78** [comment]
just updated (and with ntopng-data 2.5.170103)
it still appears as TOT on my side

**Comment by simonemainardi** [comment]
updated `ntopng-data` package contents yesterday. Please try again

**Comment by Niko78** [comment]
I can confirm, now it's fixed
thx

**Comment by simonemainardi** [comment]
thanks for reporting
