### ISSUE TITLE
Add option to specify Local Hosts based on ASN

### ISSUE THREAD

**Issue by MatteoBiscosi** [ntop/ntopng#8822]
In same cases, it is better to be able to mark the Hosts as local based on the Autonomous System and not based on the local network option (-m option).
It is requested to check if this possibility is already available and in case not, add the possibility to specify a list of comma separated ASN as an option (for the configuration file) and whenever an Host is created, check, if it's local, not just by checking the Local Networks but the ASN too.

**Comment by YellowMan02** [comment]
TODO list:
- parse autonomous system list as already done for local networks
- store AS ids in a set

The next step will be to decide how to check this information when creating a host
