### ISSUE TITLE
No Data Showing

### ISSUE THREAD

**Issue by vegeta-x2** [ntop/ntopng#883]
Hi, I am testing out ntopng and I have installed i ton centos 6.8 I have everything that needs to be installed I am pointing my pfsense firewall sflow to this server.  I see netflow data reaching this box once I enable logging on nprobe but when I loggin to ntopng no data on netflow, host, network, AS, etc is being shown has anyone run into this issue before and maybe let me me know if I am missing something I added some configs below. thx for help

probe --zmq "tcp://127.0.0.1:3001" -i none -n none -b 1 --collector-port 2055

--------------------------------------------------------------
-G=/var/run/ntopng.pid

--local-networks="192.168.0.0/16,10.0.0.0/8"

-i="tcp://127.0.0.1:3001"

-F "mysql;localhost;ntopng;flows;root;"

------------------------------------------------------
nprobe --version

Welcome to nProbe v.7.5.161220 (r5542) for x86_64-unknown-linux-gnu
with native PF_RING acceleration.
Copyright 2002-16 ntop.org

Build OS:      CentOS release 6.8 (Final)
SystemID:      3B02429B05B1B8A9
GIT rev:       dev:e55257511206d9773021e5d0d0f4296929a3aa92:20161220
---------------------------------------------------------
ntopng --version
v.2.5.161227 [Community Edition]
GIT rev:   dev:f09e58b19126902af48ba7d75ad1343df6607418:20161227

---------------------------------------------------------
9/Dec/2016 14:00:55 [nprobe.c:2912] Average traffic: [0.00 pps][All Traffic 0 b/sec][IP Traffic 0 b/sec][ratio -nan]
29/Dec/2016 14:00:55 [nprobe.c:2920] Current traffic: [0.00 pps][0 b/sec]
29/Dec/2016 14:00:55 [nprobe.c:2926] Current flow export rate: [0.0 flows/sec]
29/Dec/2016 14:00:55 [nprobe.c:2929] Flow drops: [export queue too long=0][too many flows=0][ELK queue flow drops=0]
29/Dec/2016 14:00:55 [nprobe.c:2934] Export Queue: 0/512000 [0.0 %]
29/Dec/2016 14:00:55 [nprobe.c:2939] Flow Buckets: [active=0][allocated=0][toBeExported=0]
29/Dec/2016 14:00:55 [cache.c:1224] Redis Cache [0 total/0.0 get/sec][0 total/0.0 set/sec]
29/Dec/2016 14:00:55 [nprobe.c:2957] Collector Threads: [263083 pkts@0]
29/Dec/2016 14:00:55 [nprobe.c:2778] Processed packets: 0 (max bucket search: 0)
29/Dec/2016 14:00:55 [nprobe.c:2761] Fragment queue length: 0
29/Dec/2016 14:00:55 [nprobe.c:2787] Flow export stats: [0 bytes/0 pkts][0 flows/0 pkts sent]
29/Dec/2016 14:00:55 [nprobe.c:2794] Flow collection: [collected pkts: 263083][processed flows: 3877620]
29/Dec/2016 14:00:55 [nprobe.c:2797] Flow drop stats:   [0 bytes/0 pkts][0 flows]
29/Dec/2016 14:00:55 [nprobe.c:2802] Total flow stats:  [0 bytes/0 pkts][0 flows/0 pkts sent]
29/Dec/2016 14:01:25 [nprobe.c:2911] ---------------------------------
29/Dec/2016 14:01:25 [nprobe.c:2912] Average traffic: [0.00 pps][All Traffic 0 b/sec][IP Traffic 0 b/sec][ratio -nan]
29/Dec/2016 14:01:25 [nprobe.c:2920] Current traffic: [0.00 pps][0 b/sec]
29/Dec/2016 14:01:25 [nprobe.c:2926] Current flow export rate: [26.1 flows/sec]
29/Dec/2016 14:01:25 [nprobe.c:2929] Flow drops: [export queue too long=0][too many flows=0][ELK queue flow drops=0]
29/Dec/2016 14:01:25 [nprobe.c:2934] Export Queue: 0/512000 [0.0 %]
29/Dec/2016 14:01:25 [nprobe.c:2939] Flow Buckets: [active=0][allocated=0][toBeExported=0]
29/Dec/2016 14:01:25 [cache.c:1224] Redis Cache [0 total/0.0 get/sec][0 total/0.0 set/sec]
29/Dec/2016 14:01:25 [nprobe.c:2957] Collector Threads: [263153 pkts@0] 
29/Dec/2016 14:01:25 [nprobe.c:2778] Processed packets: 0 (max bucket search: 1)
29/Dec/2016 14:01:25 [nprobe.c:2761] Fragment queue length: 0
29/Dec/2016 14:01:25 [nprobe.c:2787] Flow export stats: [0 bytes/0 pkts][0 flows/0 pkts sent]
29/Dec/2016 14:01:25 [nprobe.c:2794] Flow collection: [collected pkts: 263153][processed flows: 3878522]
29/Dec/2016 14:01:25 [nprobe.c:2797] Flow drop stats:   [0 bytes/0 pkts][0 flows]
29/Dec/2016 14:01:25 [nprobe.c:2802] Total flow stats:  [0 bytes/0 pkts][0 flows/0 pkts sent]

![2016-12-29_14-16-24](https://cloud.githubusercontent.com/assets/24831034/21552764/d73ee5b8-cdd1-11e6-9327-cf4b6a0bddc6.png)

![2016-12-29_14-16-05](https://cloud.githubusercontent.com/assets/24831034/21552789/fffbdf60-cdd1-11e6-81ed-49fc5af23309.png)

**Comment by simonemainardi** [comment]
@vegeta-x2 it seems that flows can't reach the ntopng.

I noticed that you used local `127.0.0.1` for both ntopng and nprobe. Are they running on the same box? Try to set the nProbe as `probe --zmq "tcp://*:3001" -i none -n none -b 1 --collector-port 2055`

If it still doesn't work, please post the ntopng logs and try to capture with tcpdump the traffic on port 3000 to see if the flows are travelling from the nprobe to the ntopng

**Comment by emanuele-f** [comment]
@vegeta-x2 do you have any updates?

**Comment by vegeta-x2** [comment]
Hi, I am was able to resolve my issue by update ntopng, nprobe, and all dependencies by doing a yum update.  Looks like before in interfaces before the yum update i would only get tcp://127.0.0.1:3001 and now with update a new interface showed up tcp://127.0.0.1:3001 [ifIdx: 0] I choose this interface and I am starting to see netflow

**Comment by emanuele-f** [comment]
Perfect, thank you. I'm closing the issue.
