### ISSUE TITLE
Problem with my ntopng enterprise educational lisence

### ISSUE THREAD

**Issue by malongoe** [ntop/ntopng#8835]
**Environment**:
* OS name: PfSense 
* OS version: FreeBSD 14.04
* Architecture: amd64
* ntopng version/revision: 6.3.241120

**What happened**:

We successfully generated and applied the license; however, due to an unforeseen hardware issue, we opted to use an alternative device. Although the license file was saved, we are encountering an issue where it is being flagged as invalid. Previously, the license was generated and associated with ntop version 6.3.241119. However, upon upgrading to ntop version 6.3.241120, the license no longer appears to work. Could you kindly confirm whether the license is bound to a specific ntop version during the key generation process? We would appreciate your guidance on how to resolve this issue.

**How did you reproduce it?**
![Screenshot 2024-11-22 152619](https://github.com/user-attachments/assets/304e18f0-60b5-4c63-941b-d0f8da8f653d)

**Debug Information**: 

22/Nov/2024 15:20:31 [Redis.cpp:172] Successfully connected to redis 127.0.0.1@0
22/Nov/2024 15:20:31 [Redis.cpp:172] Successfully connected to redis 127.0.0.1@0
22/Nov/2024 15:20:31 [NtopPro.cpp:379] [LICENSE] Reading license from /usr/local/etc/ntopng.license
22/Nov/2024 15:20:31 [NtopPro.cpp:542] [LICENSE] /usr/local/etc/ntopng.license: unable to validate license [Invalid
22/Nov/2024 15:20:31 [NtopPro.cpp:372] [LICENSE] No license file found /usr/local/etc/ntopng.license: reading licens
22/Nov/2024 15:20:31 [NtopPro.cpp:546] [LICENSE] Unable to validate license [Empty license file]
22/Nov/2024 15:20:31 [NtopPro.cpp:697] WARNING: [LICENSE] Invalid license [Invalid encrypted license]
22/Nov/2024 15:20:31 [NtopPro.cpp:726] WARNING: [LICENSE] ntopng will now run in Enterprise XL edition for 10 minute
22/Nov/2024 15:20:31 [NtopPro.cpp:732] WARNING: [LICENSE] before returning to community mode
22/Nov/2024 15:20:31 [NtopPro.cpp:734] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
22/Nov/2024 15:20:31 [NtopPro.cpp:738] WARNING: [LICENSE] or run ntopng in community mode starting
22/Nov/2024 15:20:31 [NtopPro.cpp:740] WARNING: [LICENSE] ntopng --community
22/Nov/2024 15:20:32 [NetworkInterface.cpp:3859] Cleanup interface dummy
22/Nov/2024 15:20:32 [Ntop.cpp:2668] Parent process is exiting (this is normal)

**Comment by malongoe** [comment]
How does ntpng license generation works? Is it binded with version of ntopng?

**Comment by dkggpeters** [comment]
It is bound to hardware which is your issue.  Email them and they will reset.  Happened to me once.

**Comment by malongoe** [comment]
Thank you for the response @dkggpeters. Let me get in touch the the tech team

**Comment by lucaderi** [comment]
You need first to revoke the license and then create the new one https://www.ntop.org/faq/how-can-i-transfer-a-license-to-a-new-server/

**Comment by malongoe** [comment]
Thank you @lucaderi. The link wass useful and managed to deploy the license
