### ISSUE TITLE
Detection of unexpected connection

### ISSUE THREAD

**Issue by ftalla** [ntop/ntopng#8838]
**What would you like to add or change?**:
Add the ability to maintain a list of IP for which an alert is triggered if they initiate connections. 

**Why do you and others need this?**:
They are devices that are connected directly to the internet and are meant to only respond to request from the internet. Typical example is a VPN gateway. If they initiate a connection, that most likely mean they have been compromised. The feature will help us detect such behavior

**Comment by lucaderi** [comment]
See also https://github.com/ntop/ntopng/issues/8812

**Comment by lucaderi** [comment]
Hi @ftalla I believe your request is the same as #8812 where your VPN server has to be defined in list B. What do you think?

**Comment by ftalla** [comment]
Hi @lucaderi,
Thank you for looking into my request.
I concur this could be the same request as #8812. I imagine if I put my server which has a public address in B and nothing in C I would get an alert anytime my server initiates a connection?
Would this be a text file with A,B and C on a single line? Just curious

Thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lucaderi** [comment]
Will be handled in https://github.com/ntop/ntopng/issues/8812
