### ISSUE TITLE
HTTP prefix not handled correctly on some more links

### ISSUE THREAD

**Issue by NotArandomGUY** [ntop/ntopng#8844]
**Environment**:
* OS name: Ubuntu
* OS version: 24.04
* Architecture: x86_64
* ntopng version/revision: 6.2.241111

**What happened**:
See #8676 

**How did you reproduce it?**
See #8676

**Comment by MatteoBiscosi** [comment]
Thanks a lot for your report! Already pushed a fix, in the next build it should be available; If perhaps you find other problems please report
