### ISSUE TITLE
ntopng makes additional 40% cpu load on opnsense-business dec2770

### ISSUE THREAD

**Issue by Ginther-GLAB** [ntop/ntopng#8845]
**Environment**:
* OS name: [opnsense business]
* OS version: [24.10.1]
* Architecture: [amd64]
* ntopng version/revision: [1.3]

**What happened**:
since i updated opnsense business to 24.10 the cpu of the ntopng process consumes continuously 40%.
It is a hardware appliance dec2770.

**How did you reproduce it?**
to reproducte the issue when i stop the ntopng service the cpu load disappears.

![image](https://github.com/user-attachments/assets/b338509b-ee19-4354-a3ed-2a8699033158)

Does anybody have suggestions or may a solution

**Comment by MatteoBiscosi** [comment]
Could you please report your ntopng version?

**Comment by Ginther-GLAB** [comment]
yes, it is version 1.3 from the OPNsense repository

**Comment by MatteoBiscosi** [comment]
Unfortunatly we cannot help you if you use the ntopng from the OPNsense repo, we can help you only if you install our repo
https://www.ntop.org/guides/ntopng/third_party_integrations/opnsense.html#opnsenseintegration
