### ISSUE TITLE
Missing known protocol on non std port

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#8849]
Please add which is the know protocol being used on non standard port such as: `Found HTTP on port 1234`. Also persist in db for historical alerts/flows

<img width="1485" alt="Screenshot 2024-12-01 at 7 45 57 PM" src="https://github.com/user-attachments/assets/a231bd73-c950-4b38-8f1d-e12b9e22adb5">

**Comment by YellowMan02** [comment]
already fixed
