### ISSUE TITLE
Missing TLS certificate information

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#8850]
Please add which is the duration of the TLS certificate. If I am not mistaken, this information should be present in live flows alert and is not persisted in the alert db. 

<img width="1521" alt="Screenshot 2024-12-01 at 7 47 58 PM" src="https://github.com/user-attachments/assets/6dd4381f-97a3-4d7f-a50e-c82549930b6b">

**Comment by YellowMan02** [comment]
alredy fixed
