### ISSUE TITLE
Sort historical alerts by decreasing score

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#8851]
Please sort alerts by decreasing score and remove the remediations icon in the description, just leave it in the info/remediation column. This is lua/pro/db_flow_details.lua. In live flows this is sorted

<img width="1524" alt="Screenshot 2024-12-01 at 7 48 51 PM" src="https://github.com/user-attachments/assets/03a8f7d7-6ba0-4114-9308-dd5c20af470f">

**Comment by DGabri** [comment]
Still not working and remediation link is present in the description
<img width="1336" alt="Screenshot 2024-12-11 at 7 24 47 AM" src="https://github.com/user-attachments/assets/ae663996-e33c-4914-a267-acedc8b0f350">

**Comment by MatteoBiscosi** [comment]
The issue should now be fixed
![image](https://github.com/user-attachments/assets/3d0e48dd-ce1a-489d-b06f-aaa9db1f2f48)

**Comment by DGabri** [comment]
Verified as fixed
