### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8858]
03/Dec/2024 15:54:45 [LuaEngine.cpp:1499] WARNING Script failure [/usr/share/ntopng/scripts/lua/pro/rest/v2/get/db/historical_db_search.lua][...ng/scripts/lua/pro/modules/flow_db/db_search_manager.lua:99: attempt to call a nil value (field 'formatSelect')]

**Comment by cardigliano** [comment]
Fixed. A trace has been added to catch cases like this (trying to use the db with CH not enabled).
