### ISSUE TITLE
ntopng Report: No display

### ISSUE THREAD

**Issue by jumezurike** [ntop/ntopng#8859]
![ntopgnissues](https://github.com/user-attachments/assets/8b531659-3d1b-4758-b002-c95e717c79a9)

**Environment**:
* OS name: Ubuntu
* OS version: 22.04.4 LTS
* Architecture: x86_64 - 64 bit (jemalloc)
* ntopng version/revision: 

ntopng Enterprise XL v.6.3.241029 rev.24649 

**What happened**:

We included the clickhouse lines on ntopng conf file
We use to get report before we upgraded to this.
-F="clickhouse-cloud;ndk5w2mfzw.us-east-1.aws.clickhouse.cloud@9440,3306s;ntopng;mysql4ndk5ww,mysql4ndk5w2mfzw;yRS76d_EQ"

**How did you reproduce it?**

If you put -F= 

**Debug Information**:

**Comment by cardigliano** [comment]
@jumezurike please show (e.g. with a screenshot) what is the exact issue. Please update to the latest version before.

**Comment by jumezurike** [comment]
![ntopgnissues](https://github.com/user-attachments/assets/a6de5e03-1671-4c85-9e16-0366933f6ccc)
Sorry you did not get this earlier.

**Comment by jumezurike** [comment]
nprobe + ZMQ version? I am not sure where this was used but we can go over the setup if anyone of you wants to assist on that.

**Comment by lucaderi** [comment]
It looks like the GUI is unable to query clickhouse cloud as I see data is received in ntopng from ZMQ. Can you please check if with a local clickhouse you are able to extract data correctly?

**Comment by jumezurike** [comment]
My clickhouse free trial is done.Can I pull the report without clickhouse.In fact I prefer that for this. Thanks.

Josiah J. UmezurikeIT Consultant | E1T1, Incwww.each1teach1.us
Cell:(763)568-4836
----------------------------------------------------------------------This email is privileged and confidential and is intended for the recipient. If you have received this email and are not the intended recipient please disregard it. If you have intercepted this communication without our authorization, consent or knowledge, you are in violation of both State and Federal Laws which govern private communication and will be prosecuted to the fullest extent of the law. 

    On Wednesday, December 11, 2024 at 06:35:54 AM EST, Luca Deri ***@***.***> wrote:  
 
 


It looks like the GUI is unable to query clickhouse cloud as I see data is received in ntopng from ZMQ. Can you please check if with a local clickhouse you are able to extract data correctly?

**Comment by cardigliano** [comment]
Report's data comes from the database on ClickHouse..
