### ISSUE TITLE
Total score calculation broken

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#8868]
Flow alert calculation is broken.
1. in the alerts table this flow was of total score 30 with main alert: "Blacklisted Server Contact" which has score 200. 
2. Opening the details of this alert, the score calculation is broken

http://HSOL:3000/lua/alert_stats.lua?page=flow&epoch_begin=1733896640&epoch_end=1733898440&status=historical&ifid=11&query_preset=&count=&severity=3%3Blte

<img width="884" alt="Screenshot 2024-12-11 at 7 31 16 AM" src="https://github.com/user-attachments/assets/b0f406c2-96dd-4af0-a613-ad9848195b27">

http://HSOL:3000/lua/pro/db_flow_details.lua?page=flow&status=historical&row_id=92670282070&tstamp=1733898218
<img width="1329" alt="Screenshot 2024-12-11 at 7 29 12 AM" src="https://github.com/user-attachments/assets/235613d7-8f39-4e84-8dd2-0eb20c661ef3">

**Comment by cardigliano** [comment]
@DGabri what is the exact ntopng version and database (CH or SQLite)?

**Comment by DGabri** [comment]
This is using clickhouse on the hosting solutions machine

**Comment by MatteoBiscosi** [comment]
Hi @DGabri The issue should now be fixed, however unfortunately it is only applyable to the new triggered alerts, the old ones are going to keep this problem

**Comment by DGabri** [comment]
Verified as fixed
