### ISSUE TITLE
downloading empty PCAP file

### ISSUE THREAD

**Issue by Alisher-Nabiev** [ntop/ntopng#8869]
Environment:

OS name: Ubuntu
OS version: 18.04.6 LTS
Architecture: x86_64
ntopng version/revision: ntopng Enterprise L v.5.7.231017

**What happened**:
trying to download PCAP and its empy  file.

**How did you reproduce it?**
send a full URL via support, on alisher@monogoto.io email

**Debug Information**:

**Comment by Alisher-Nabiev** [comment]
![image](https://github.com/user-attachments/assets/17bf1d10-2f13-4ac9-a9c8-161e5acddf15)

[ntopng.txt](https://github.com/user-attachments/files/18091383/ntopng.txt)

**Comment by lucaderi** [comment]
Please move to a more recent version

**Comment by Alisher-Nabiev** [comment]
@lucaderi 
Hit:1 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu bionic-backports InRelease
Ign:4 https://apt.datadoghq.com stable InRelease
Hit:5 https://apt.datadoghq.com stable Release
Hit:6 https://artifacts.elastic.co/packages/7.x/apt stable InRelease
Hit:7 http://ppa.launchpad.net/oisf/suricata-stable/ubuntu bionic InRelease
Ign:8 https://packages.ntop.org/apt/18.04 x64/ InRelease
Ign:9 https://packages.ntop.org/apt/18.04 all/ InRelease
Err:10 https://packages.ntop.org/apt/18.04 x64/ Release
  404  Not Found [IP: 167.99.215.164 443]
Err:11 https://packages.ntop.org/apt/18.04 all/ Release
  404  Not Found [IP: 167.99.215.164 443]
Hit:12 http://security.ubuntu.com/ubuntu bionic-security InRelease
Ign:14 https://repo.clickhouse.com/deb/stable main/ InRelease
Hit:15 https://repo.clickhouse.com/deb/stable main/ Release
Reading package lists... Done
E: The repository 'https://packages.ntop.org/apt/18.04 x64/ Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://packages.ntop.org/apt/18.04 all/ Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by Alisher-Nabiev** [comment]
can i also bump my OS version?

**Comment by Alisher-Nabiev** [comment]
@lucaderi 
Environment:
OS name: Ubuntu
OS version: 18.04.6 LTS
Architecture: x86_64
ntopng version/revision: ntopng Enterprise L v.6.1.231204

i did the update but still same issue

![Capture](https://github.com/user-attachments/assets/89ead4de-add3-4550-b381-d9d07ac9c95b)
