### ISSUE TITLE
@lucaderi

### ISSUE THREAD

**Issue by Alisher-Nabiev** [ntop/ntopng#8870]
@lucaderi 
Environment:
OS name: Ubuntu
OS version: 18.04.6 LTS
Architecture: x86_64
ntopng version/revision: ntopng Enterprise L v.6.1.231204

i did the update but still same issue

![Capture](https://github.com/user-attachments/assets/89ead4de-add3-4550-b381-d9d07ac9c95b)

_Originally posted by @Alisher-Nabiev in https://github.com/ntop/ntopng/issues/8869#issuecomment-2535188478_

**Comment by lucaderi** [comment]
Your version is one year old. Please use a package from https://packages.ntop.org
