### ISSUE TITLE
repo upgrade and empty pcap files

### ISSUE THREAD

**Issue by Alisher-Nabiev** [ntop/ntopng#8874]
**Environment**:
* OS name:  Ubuntu
* OS version: 24.04.1 LTS
* Architecture: amd64
* ntopng version/revision: ntopng Enterprise L v.6.3.241215

**What happened**:
I encountered some issues with my old OS version 18.04 ntopng version/revision: ntopng Enterprise L v.5.7.231017 while trying to download a PCAP file via the UI.

I contacted via GitHub, and @lucaderi  suggested me to upgrade the version.

I update my operating system regularly, ensuring the DPI is installed and running correctly.

when I upgrade to 24.04 and tried to install the repo from here : https://packages.ntop.org/apt-stable/

I face some issues.

couldn't install ntopng at all I got this error:
root@ip-100----4:/home/ubuntu# systemctl status ntopng
Unit ntopng.service could not be found.

and this:
root@ip-100------:/home/ubuntu# apt-get install pfring-dkms ntopng n2disk cento
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
pfring-dkms is already the newest version (8.8.0.9574).
n2disk is already the newest version (3.6.241209-5312).
cento is already the newest version (2.0.241209-962).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ntopng : Depends: ntopng-data (= 5.2.1+dfsg1-1ubuntu4) but 6.2.241209 is to be installed
E: Unable to correct problems, you have held broken packages.

after this I update the repo to 22.04 and install ntop again:

currently, I am running:
OS name: Ubuntu
OS version: Ubuntu 24.04.1 LTS
Architecture: x86_64
ntopng version/revision: ntopng Enterprise L v.6.3.241215

I would like to understand why this issue occurred. 

also the initial issue with pcap files are not solved at all.

worth mentioning that if I narrow the search to 3 hours from 24h I am able to download the pcap file.

now when I am trying to down load 24h pcap I got this error in UI:

"No recorded data in the specified time frame. Traffic recorder needs some time to write recent data and deletes old data according to the configured data retention."

**Comment by lucaderi** [comment]
So you upgrade from ubuntu 18 to 24. In this case you need to
1. uninstall all packages as described here https://www.ntop.org/faq/how-can-i-uninstall-all-the-ntop-packages/
2. reinstall packages from https://packages.ntop.org

**Comment by Alisher-Nabiev** [comment]
and this will keep all my configuration on the services like, ntopng, n2disk etc' ?

**Comment by cardigliano** [comment]
Could you try removing ntopng and reinstalling it? It seems you have a community version as it is requiring ntopng-data 5.2.1+dfsg1-1ubuntu4, rather than 6.2.241209 from our repository at https://packages.ntop.org/apt-stable/24.04/all/

**Comment by cardigliano** [comment]
Yes, configuration is not removed (unless you purge the package)
