### ISSUE TITLE
ntopng 6.3.241218 errors

### ISSUE THREAD

**Issue by plegrand1** [ntop/ntopng#8879]
Hello, 
since a few days, i've been unable to access the following url
http://xxx.xxx.xxx.xxx:3000/lua/vlan_stats.lua
On the web page, i've got the following error
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

And these messages in the log file (/var/log/ntopng.log)
```
2024-12-18T10:00:06.160861+01:00 sonde ntopng: 18/Dec/2024 10:00:06 [LuaEngine.cpp:1499] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_vlans_data.lua][/usr/share/ntopng/scripts/lua/get_vlans_data.lua:67: attempt to index a nil value (local 'vlans_stats')]
```

I'm using this ntopng version:
ntopng --version
Version:        6.3.241218 [Enterprise/Professional build]
GIT rev:        dev:fd98333e2cf8912dcd43f38b4b96b483d3e0971e:20241218
Pro rev:        r6924
Built on:       Debian GNU/Linux 12 (bookworm)
System Id:      L78BFBCE1B206AB13--U78BFBCE1A6FB7A83--OL
Platform:       x86_64
Edition:        Community
License Type:   Time-Limited [Empty license file]
Validity:       Until Wed Dec 18 10:12:46 2024

Debian GNU/Linux 12 (bookworm)

could someone help me solve this problem?
Thanks
Pascal

**Comment by plegrand1** [comment]
I solve my problem.
Dont know why but on the home page was displayed:
![image](https://github.com/user-attachments/assets/e15c7d12-8f84-4733-b8b3-84111a80af84)

I changed for:
![image](https://github.com/user-attachments/assets/481833bf-0acb-4f15-84ef-55d957b7744e)

Now it works fine

**Comment by MatteoBiscosi** [comment]
Hi @plegrand1 i will push a fix to prevent that error from being displayed, but yes, if that error happens it mean that you have no vlans on the interface you are checking

**Comment by plegrand1** [comment]
thank you for your prompt reply !!
