### ISSUE TITLE
No compatible pkg with pfSense 2.7.2 / FreeBSD 14

### ISSUE THREAD

**Issue by GSzabados** [ntop/ntopng#8890]
**Environment**:
* OS name: pfSense / FreeBSD 14
* OS version: 2.7.2
* Architecture: x64
* ntopng version/revision: latest

**What happened**:

The provided pkg at https://packages.ntop.org/FreeBSD/FreeBSD:14:amd64/latest/ntop-1.0.pkg is not compatible with pfSense 2.7.2. During installation it tries to remove essential pfSense packages.  

**How did you reproduce it?**

pkg add https://packages.ntop.org/FreeBSD/FreeBSD:14:amd64/latest/ntop-1.0.pkg 

pkg install ntopng

**Debug Information**:

```
[2.7.2-RELEASE][root@pfSense.localdomain]/root: pkg install ntopng
Updating ntop repository catalogue...
ntop repository is up to date.
Updating pfSense-core repository catalogue...
Fetching meta.conf:   0%
Fetching packagesite.pkg:   0%
pfSense-core repository is up to date.
Updating pfSense repository catalogue...
Fetching meta.conf:   0%
Fetching packagesite.pkg:   0%
pfSense repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The following 5 package(s) will be affected (of 0 checked):

Installed packages to be REMOVED:
        pfSense: 2.7.2
        php82-pfSense-module: 0.95
        strongswan: 5.9.11_3
        unbound: 1.19.1

New packages to be INSTALLED:
        ntopng: 6.3.241228 [ntop]

Number of packages to be removed: 4
Number of packages to be installed: 1

The process will require 71 MiB more space.

Proceed with this action? [y/N]: N

```

**Comment by GSzabados** [comment]
I pulled the trigger too early on this one. So here is the solution.

Install original package from pfSense, then in  command line remove the ntopng.

`pkg remove -f ntopng`     (5.6.d20230920)

then 

install the latest one (6.3.something):

```
pkg add https://packages.ntop.org/FreeBSD/FreeBSD:14:amd64/latest/ntop-1.0.pkg

pkg install nprobe ntopng
```

Then resolve libsodium:

`pkg add --force https://pkg.freebsd.org/FreeBSD:14:amd64/latest/All/libsodium-1.0.19.pkg`

And start ntopng from the pfSense UI as  "DIAGNOSTICS -> ntopng settings" 

The only issues which I cannot resolve yet, is why a PPPOE connection has only one direction traffic, why not RX and TX. And why Geo Map is not showing any locations like it was showing with 5.6.....

**Comment by cardigliano** [comment]
@GSzabados thank you for reporting, we will update the docs to fix common errors. As of the other issues, please open individual tickets. Thank you.
