### ISSUE TITLE
NTOPNG generates duplicate variable in CONF file when using advanced configuration lines on pfsense+

### ISSUE THREAD

**Issue by BenjaminGC** [ntop/ntopng#8891]
**Environment**:
* OS name: pfSense+
* OS version: 24.11-RELEASE (FreeBSD 15.0-CURRENT)
* Architecture: amd64
* ntopng version/revision: 5.6.0_1

**What happened**:
 When adding different ports under the advanced configuration like these:
--http-port=3000
--https-port=3001
It fails to start the service because now in the config file it has the following:
    # This file is automatically generated -- do not edit
    --daemon=
    --pid=/var/run/ntopng.pid
    --data-dir=/var/db/ntopng/
    --no-promisc=
    --http-port=0
    --https-port=0.0.0.0:3000,[::]:3000
    --interface=lagg0.100
    --interface=lagg0.110
    --interface=lagg0.120
    --interface=lagg0.130
    --interface=lagg0.140
    --interface=lagg0.150
    --interface=lagg0.160
    --interface=tun_wg0
    --dns-mode=0
    # Custom configuration options:
    --http-port=3000
    --https-port=3001
This means I need to remove the 2 lines it automatically generated (http-port and https-port) and manually start the service via the pfsense WebUI.

**How did you reproduce it?**
You just need to create a small change via the WebUI of pfsense+ in the NTOPNG settings page and then you will find yourself the need for manually having to change the ntopng.conf file and manually having to start the service from the pfsense+ WebUI

**Debug Information**:
N/A

**Comment by cardigliano** [comment]
@BenjaminGC please note the pfsense+ WebUI is not under our control as we are not the authors nor the maintainers, please contact pfsense. Thank you.
