### ISSUE TITLE
Generate a report depending of the network equipment that sends the data

### ISSUE THREAD

**Issue by jbeney** [ntop/ntopng#890]
Hello,

We have a customer with a pro license that has NETFLOW activated on different equipments sending their data to the same NTOP instance.
They would like to generate different reports (report A for router A, report B for router B) and avoid to have all info in the same report. 
Is there a way to 'tag' the data in order that NTOP can generate a report depending of the network equipment that sends it ?

Thanks

**Comment by simonemainardi** [comment]
you should create dynamic interfaces on the basis of the Probe IP Address or Ingress Fow Interface:

![image](https://cloud.githubusercontent.com/assets/3397663/21594960/000ccd3e-d129-11e6-80f7-814051617801.png)

this will keep the traffic separated and you will be able to generate reports for every equipment

**Comment by franckfischer** [comment]
Hello Simone, 
To follow up on Jonathan's query, we currently have router A sending flows to an nprobe instance running in proxy mode.
Flows are then forwarded by nprobe to an ntopng instance.

We'd now like to add a second device (router B) to that setup and be able to separate reports from router A and router B in ntopng.

I got from your last reply we should create different interfaces for each router.

However : 
1) should we create a different nProbe instance for each router, each exporting to the appropriate ntopng instance ? Or is it possible to collect all flows in one nProbe instance, and have it export data to the appropriate dynamic interface in ntopng ?
2) We were not able to find where to create Dynamic Interfaces in ntopng GUI. Could you please specify this ?

I'm sorry, we were not able to find that information from the user's guide.

Thanks for your help
