### ISSUE TITLE
Misleading MySQL Upgrade Message

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#891]
Sometimes MySQL needs to perform some tasks that are misinterpreted by ntopng. This is bad as the information returned is misleading, and it needs to be fixed.

Example
mysql> show processlist;
+----+------+-----------+--------+---------+------+----------------------+------------------------------------------------------------------------------------------------------+
| Id | User | Host      | db     | Command | Time | State                | Info                                                                                                 |
+----+------+-----------+--------+---------+------+----------------------+------------------------------------------------------------------------------------------------------+
|  4 | root | localhost | NULL   | Sleep   |   45 |                      | NULL                                                                                                 |
|  6 | root | localhost | NULL   | Sleep   |   45 |                      | NULL                                                                                                 |
|  7 | root | localhost | NULL   | Sleep   |   45 |                      | NULL                                                                                                 |
|  8 | root | localhost | NULL   | Sleep   |   45 |                      | NULL                                                                                                 |
|  9 | root | localhost | ntopng | Query   |   45 | Repair with keycache | CREATE TABLE IF NOT EXISTS `flowsv6` (`idx` int(11) NOT NULL AUTO_INCREMENT,`VLAN_ID` smallint(5) un |
| 12 | root | localhost | NULL   | Query   |    0 | starting             | show processlist                                                                                     |
+----+------+-----------+--------+---------+------+----------------------+------------------------------------------------------------------------------------------------------+
6 rows in set (0.00 sec)

is reported as

<img width="496" alt="screen shot 2017-01-02 at 21 56 30" src="https://cloud.githubusercontent.com/assets/4493366/21596098/995bd414-d136-11e6-978b-3c7456dd0656.png">

**Comment by simonemainardi** [comment]
changed the message and added the operations currently performed on the database

![image](https://cloud.githubusercontent.com/assets/3397663/21772611/4ab1ade2-d68c-11e6-89e2-5bd46951c42b.png)
