### ISSUE TITLE
Invalid information entered in data pane

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#892]
In the host report pane, it is possible to write date by hand. This needs to be fixed as users can enter invalid information. The field must be set read-only.

<img width="907" alt="screen shot 2017-01-02 at 21 59 27" src="https://cloud.githubusercontent.com/assets/4493366/21596114/ce6c33f6-d136-11e6-9e9e-7c0577562e09.png">

**Comment by emanuele-f** [comment]
This should is fixed in the private branch part of #905
