### ISSUE TITLE
Invalid MAC address number reported in GUI

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#893]
ntopng reports an invalid number of MAC addresses. The footer page reports 5 devices, the device list reports only 3 devices. This information is inconsistent and misleading.

<img width="1209" alt="screen shot 2017-01-02 at 22 10 05" src="https://cloud.githubusercontent.com/assets/4493366/21596207/515b40ee-d138-11e6-971d-876d93805b54.png">

[mac.pcap.zip](https://github.com/ntop/ntopng/files/681384/mac.pcap.zip)

**Comment by simonemainardi** [comment]
fixed in https://github.com/ntop/ntopng/pull/902
