### ISSUE TITLE
Disable bridging when bridged interfaces have an IP address

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#894]
ntopng in bridge mode (no netfilter) must refuse to start when bridged network interfaces have an IP address configured.

**Comment by simonemainardi** [comment]
Implemented

```
03/Jan/2017 11:17:24 [PacketBridge.cpp:61] ERROR: Unable to start the bridge as enp5s0f2 has an address assigned [192.168.2.228].
03/Jan/2017 11:17:24 [PacketBridge.cpp:64] ERROR: Delete any address assigned to enp5s0f2 and restart ntopng. Run:
03/Jan/2017 11:17:24 [PacketBridge.cpp:67] ERROR: ip addr flush dev enp5s0f2
```

I suggest @ValentinaViscarelli  to disable network configuration for interfaces used as bridge in the nBox:

![image](https://cloud.githubusercontent.com/assets/3397663/21605030/c96ab100-d1a6-11e6-92a4-9d6104c8f475.png)
