### ISSUE TITLE
Disable DHCP for bridged interfaces

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#895]
When ntopng is used in bridge mode, it must avoid transmitting Bootstrap/DHCP packets whose source MAC address (and client MAC address inside the Bootstrap/DHCP packet) is one of the bridged interfaces.

**Comment by ValentinaViscarelli** [comment]
@lucaderi 
Currently ntopng used in bridge mode avoids to transmit packets (between bridged interfaces) whose source or destination mac address is one of the bridged interfaces. Can you say that issue #895 is resolved from this condition?

**Comment by lucaderi** [comment]
We're mostly ready: the only missing piece is to do this check for Bootstrap/DHCP packet also for client Mac address that unless DHCP relay is used it should be identical to the MAC of the packet. Done this you can close this issue.
![screen shot 2017-01-07 at 18 25 39](https://cloud.githubusercontent.com/assets/4493366/21743650/bbbf4eea-d506-11e6-9648-5c316416e1f2.png)

**Comment by ValentinaViscarelli** [comment]
Fixed.
