### ISSUE TITLE
No "custom host name" in nightly builds 2.5.170103

### ISSUE THREAD

**Issue by itnas-s** [ntop/ntopng#896]
Hi
and sorry for my poor english
No "custom host name" in nightly builds 2.5.170103

I think the "custom host name" is very usefull, on some device it no host name such as android phone

**Comment by emanuele-f** [comment]
Hi, I'm not able to reproduce this. Do you see any errors in the ntopng log? What OS are you using?

**Comment by itnas-s** [comment]
my OS is Ubuntu 14.04
![image](https://cloud.githubusercontent.com/assets/24326638/21603037/bf9d689a-d1cc-11e6-994a-439d32d2f817.png)

in previous version I can custom host name

**Comment by itnas-s** [comment]
OK I Close this issue
solved by remove ntopng and reinstall (apt ubuntu)

Thank you
