### ISSUE TITLE
Bandwidth Ntopng I don't understand !

### ISSUE THREAD

**Issue by iPhosphoR** [ntop/ntopng#897]
Hi !
I used Ntopng since 1 month ago, i'm a newbie and I still do not understand where to find the bandwidth of each machine, what I do not understand is that when I download a file of 1 GBytes with a download speed of 1.25 MBytes/s ntopng tells me 365 Kbit/s.
Help me !

![ntopng](https://cloud.githubusercontent.com/assets/24895578/21610719/f76c6440-d1c9-11e6-8120-41c814bf8441.png)

**Comment by emanuele-f** [comment]
You can find host information such as istantaneous bandwidth in the hosts page, the one in your screenshot. Moreover, from the host page, cliking the chart icon in the navigation bar will bring you to the graphs page, where you can see the throughput during time, which is probably what you want.

Please note that, in the simple setup, in order to monitor your network you need traffic to pass through your pc running ntopng. Otherwise, you will only see your local ntopng-running pc traffic.

**Comment by iPhosphoR** [comment]
No, what I mean is that I mean is that I have connection is capping at about 2 MB / s whereas ntopng tells me that I am at 350 KB / s downloading about what I think Should not be:

Here I see that I have a connection of 2 MB / s
![ping](https://cloud.githubusercontent.com/assets/24895578/21636824/69072ce4-d264-11e6-91b5-63432f8cda53.png)
![convert](https://cloud.githubusercontent.com/assets/24895578/21636830/6e2af642-d264-11e6-9268-1f13945753ba.png)

Here I see that I download 100 MB and that the traffic is only 8 MB.
I also see that my connection is 310 KB / s while I use the whole band is this normal?
![ntopng 2](https://cloud.githubusercontent.com/assets/24895578/21636841/75f0d5ae-d264-11e6-9498-e4c22d38fc1f.png)

Thank you for your help.

**Comment by emanuele-f** [comment]
How is your ntopng-running machine connected to the rest of your network? In order to monitor your entire network your need to setup a bridge or mirror the traffic.

**Comment by iPhosphoR** [comment]
Yes I did a mirroring on the switch affect

**Comment by emanuele-f** [comment]
Do you see dropped flows into the interface view? If not, please double check your mirroring configuration in the switch. Do you have VLANs?

**Comment by iPhosphoR** [comment]
I checked, the mirror is correct. This may be due to the configuration of the 2 network cards?

**Comment by simonemainardi** [comment]
Don't use the speedtest to do the comparisons. The speedtest does speed estimations using multiple factors and so it is not necessarily accurate.

However, I argue that the switch isn't mirroring you all the traffic. I assume you have 2 network cards connected to your pc, one that does the actual traffic (A) and another one that receives mirrored traffic from the switch (B). Check mirror configuration and make sure A's traffic is mirrored through B.

**Comment by iPhosphoR** [comment]
I check this now!

**Comment by simonemainardi** [comment]
ok let us know

**Comment by iPhosphoR** [comment]
There is no worry I keep you informed

**Comment by iPhosphoR** [comment]
I think this would come from the installation of ntopng and its packages as well as the configuration of files and network cards ... Would you mind to advise me a good tutorial or at best offer me one?

**Comment by iPhosphoR** [comment]
I find some things weird, I feel that my local and eth0 are taking part of the bandwidth so I do not have the full bandwidth, am I wrong?
![eth](https://cloud.githubusercontent.com/assets/24895578/21772678/7eb0dd0c-d68c-11e6-923a-8469b5247d52.png)

**Comment by simonemainardi** [comment]
@iPhosphoR no, each interface is separated and bandwidth is not shared among different interfaces. Please post the current configuration you are using and we'll try to help.

**Comment by iPhosphoR** [comment]
I can send you the tutorial page that I followed

**Comment by simonemainardi** [comment]
ok but also send the configuration file used or visit page runtime status and attach the contents

![image](https://cloud.githubusercontent.com/assets/3397663/21773685/4717b380-d690-11e6-84fa-85703860afa8.png)

**Comment by iPhosphoR** [comment]
I send you that tomorrow at the first hour

**Comment by iPhosphoR** [comment]
Runtime Status : 
![ntopng pid](https://cloud.githubusercontent.com/assets/24895578/21798572/7ecdb1a0-d715-11e6-990a-ccc0074a625e.png)

Ntopng.conf : 
![capture d ecran de 2017-01-10 09 12 56](https://cloud.githubusercontent.com/assets/24895578/21798595/9d0c36e6-d715-11e6-99e3-840d94510874.png)

Tutorial page : 
![tuto](https://cloud.githubusercontent.com/assets/24895578/21798621/c7ce25ec-d715-11e6-972d-9ce036bd1db8.png)

**Comment by lucaderi** [comment]
Are you sure you are observing on your ethernet interfaces all the traffic flowing on your network?

**Comment by iPhosphoR** [comment]
I'm sure, but I think I will reinstall ntopng because I think I've done anything ... Would you have a good tutorial to advise me or better still offer me please?

**Comment by simonemainardi** [comment]
@iPhosphoR the official user guide is a good starting point https://raw.githubusercontent.com/ntop/ntopng/dev/doc/UserGuide.pdf

However, from the logs you've enclosed, I don't see any particular issue. 

If you want to explore the traffic that goes to the internet, you should first determine which is the interface that carries that traffic (one of eth0, eth1 or eth2), and then you have to select it using the ntopng dropdown menu "Interfaces".

**Comment by iPhosphoR** [comment]
I know that I can choose one of the interfaces but the problem is that I have a bandwidth that rises up to about 2 MB/s but the ntopng interface tells me that when I download a 1GB file and ben my bandwidth does not exceed 340Kbit, the worst is that they are bits and not Bytes ...

**Comment by iPhosphoR** [comment]
After reinstalling always the same problem ... Would you have an option or a file that could limit the bandwidth that receives ntopng?

**Comment by emanuele-f** [comment]
If you don't see any dropped packets on ntopng than ntopng should be working fine.
As the suggestions above, you probably can't see all your network traffic from your interface you are monitoring. This could be related to an invalid mirroring configuration and/or network configuration but this is something you should take care of.
As a check, you could try to run programs like wireshark and see if you actually receive all the data from the mirror port.

**Comment by iPhosphoR** [comment]
I go to check my mirroring.

**Comment by iPhosphoR** [comment]
I have a worry ... 
-My modem is connected to a router NetGear which is also connected to the switch. At the base I did the mirroring on the switch. Should I possibly do this on the NetGear router?

-Should the SSH server be enabled?

-Can this come from a firmware missing a network card?

-The installation of debian can influence the use of ntopng?

-This my configuration of fil /etc/network/interfaces:

# Primary
auto eth0
allow-hotplug eth0
iface eth0 inet dhcp

# Sonde Interface
auto eth1
iface eth1 inet manual
                      up ifconfig eth1 promisc up
                      down ifconfig eth1 promisc down

**Comment by emanuele-f** [comment]
I'm sorry but I cannot provide technical assistance on your specific network configuration here. I think we provided enough information to troubleshoot where any problems could be. Contact us privately for more specific support. Thank you.
