### ISSUE TITLE
Bridging interface check

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#900]
When starting ntopng in bridge mode (-i bridge:X,Y) it is compulsory to avoid starting it if at least one interface is part of a bridge. This does not apply for ZC interfaces.

**Comment by ValentinaViscarelli** [comment]
Fixed.

**Comment by simonemainardi** [comment]
we should also check whether the interface itself is not a bridge. In that case, a folder `bridge` exists under `/sys/class/net/dev_name`. :

```
simone@devel:~$ ip link show develv5
18: develv5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 00:e0:ed:1a:34:58 brd ff:ff:ff:ff:ff:ff
simone@devel:~$ less /sys/class/net/develv5/br
brforward  bridge/    brif/      broadcast
```

**Comment by ValentinaViscarelli** [comment]
I already added this case. Have you tried to test it? 
I don't understand what I'm missing.

**Comment by simonemainardi** [comment]
@ValentinaViscarelli I've inspected the sources and found the following checks ` sprintf(folder, "/sys/class/net/%s/brport/", dev1);`

Those checks properly determine if the interface belongs to a bridge but not if the interface is a bridge itself. Isn't it?

**Comment by ValentinaViscarelli** [comment]
@simonemainardi 
It doesn't seem this is part of request of the issue.
Anyway I will add this check.

**Comment by ValentinaViscarelli** [comment]
Implemented.
