### ISSUE TITLE
License mismatch error

### ISSUE THREAD

**Issue by Consuelnetwork** [ntop/ntopng#903]
Hello

We have a problem with our Nprobe server.

We had a lot of issue with our servers monday, and we had to migrate some virtual machines.
When our Nprobe server was rebooted, it now show us this message at start :
ERROR: Invalid nProbe license (/etc/nprobe.license) [License mismatch error]

Our order ID is : 1461928301 

I can provide System ID and license file actually used if necesserary.

Thanks for your help

**Comment by simonemainardi** [comment]
Please, follow the instructions at: http://www.ntop.org/support/faq/how-can-i-move-a-license-to-a-new-server/
