### ISSUE TITLE
Bandwith Manager input fields

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#904]
It is not possible to save when setting an input field
![image](https://cloud.githubusercontent.com/assets/3397663/21676178/ffc71862-d334-11e6-993a-1ce7b5a0ddfa.png)

However, if you stop typing for a second and then delete/add extra digits, then the save button becomes enabled

**Comment by emanuele-f** [comment]
If 10000 it's the current shaper max_rate value, backed by redis, then it is expected save button to be disabled.
If the redis value is an empty value, that is a bug, since empty fields max rate fields should not be allowed (fixed in #905)
