### ISSUE TITLE
remote host name showing name of local gateway

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#906]
all remote hosts have the name of the local gateway instead of the DNS PTR record. In this case it should be video-edge-c2b67c.fra02.hls.ttvnw.net. ntopng is started with -n=1. Version 2.5.170105
![2017-01-06 01_58_52-welcome to ntopng - chromium](https://cloud.githubusercontent.com/assets/7170155/21703700/43b527ce-d3b4-11e6-9776-157fa9d7cfdc.png)
![2017-01-06 01_59_28-welcome to ntopng - chromium](https://cloud.githubusercontent.com/assets/7170155/21703702/46d4165e-d3b4-11e6-8601-c39cda5e3b3f.png)

**Comment by simonemainardi** [comment]
@olliff what is your ntopng version?

Can you attach a pcap so we can try and reproduce?

**Comment by ghost** [comment]
I'm using ntopng v. 2.5.170105.
I'm capturing traffic on a mirror port, pcap file that contains dns requests attached.

[http://pub.syscontrol.net/dump.pcap](http://pub.syscontrol.net/dump.pcap)

**Comment by ghost** [comment]
I wanted to add that host names are displayed correctly in the 'Talkers' Overview of a host

**Comment by emanuele-f** [comment]
Do you have incoming DHCP traffic from remote hosts? Can you try to reproduce the error disabling dynamic vlan interfaces?

**Comment by ghost** [comment]
No, DHCP traffic originates only from local subnets (192.168.2.0/24, 192.168.11.0/28, 192.168.22.0/28, 172.20.164.0/24, 192.168.60-64.0/24), incoming dhcp traffic from remote hosts is blocked at firewall level. After discovering issue #873, I disabled dynamic vlan feature. The screenshots above were taken after.
I also found out that links to local and remote hosts are swapped sometimes in flow overview, don't know if this is related.
![2017-01-11 19_50_42-welcome to ntopng - chromium](https://cloud.githubusercontent.com/assets/7170155/21862165/4eb662fe-d838-11e6-970f-85326d54bc92.png)
![2017-01-11 19_51_03-welcome to ntopng - chromium](https://cloud.githubusercontent.com/assets/7170155/21862166/4eb6ae12-d838-11e6-9b2b-4eba992dd24d.png)

**Comment by ghost** [comment]
Clearing the redis cache solved the problem for me. I still don't know why the database got messed up. Issue #873 has also been fixed by today's patch, which is great. Looking forward for a new arm release. I really appreciate your help.
