### ISSUE TITLE
PPP supported?

### ISSUE THREAD

**Issue by chasgames** [ntop/ntopng#907]
Hi

Is there a way to search in ntop by PPP username (radius), instead of IP address?

Thanks

**Comment by simonemainardi** [comment]
In order to dissect radius traffic you should combine ntopng with nProbe. The nProbe radius plugin allows you to extract the following information:

```
Plugin Radius Protocol templates:
[NFv9 57712][IPFIX 35632.240] %RADIUS_REQ_MSG_TYPE              RADIUS Request Msg Type
[NFv9 57713][IPFIX 35632.241] %RADIUS_RSP_MSG_TYPE              RADIUS Response Msg Type
[NFv9 57714][IPFIX 35632.242] %RADIUS_USER_NAME                 RADIUS User Name (Access Only)
[NFv9 57715][IPFIX 35632.243] %RADIUS_CALLING_STATION_ID        RADIUS Calling Station Id
[NFv9 57716][IPFIX 35632.244] %RADIUS_CALLED_STATION_ID         RADIUS Called Station Id
[NFv9 57717][IPFIX 35632.245] %RADIUS_NAS_IP_ADDR               RADIUS NAS IP Address
[NFv9 57718][IPFIX 35632.246] %RADIUS_NAS_IDENTIFIER            RADIUS NAS Identifier
[NFv9 57719][IPFIX 35632.247] %RADIUS_USER_IMSI                 RADIUS User IMSI (Extension)
[NFv9 57720][IPFIX 35632.248] %RADIUS_USER_IMEI                 RADIUS User MSISDN (Extension)
[NFv9 57721][IPFIX 35632.249] %RADIUS_FRAMED_IP_ADDR            RADIUS Framed IP
[NFv9 57722][IPFIX 35632.250] %RADIUS_ACCT_SESSION_ID           RADIUS Accounting Session Name
[NFv9 57723][IPFIX 35632.251] %RADIUS_ACCT_STATUS_TYPE          RADIUS Accounting Status Type
[NFv9 57724][IPFIX 35632.252] %RADIUS_ACCT_IN_OCTETS            RADIUS Accounting Input Octets
[NFv9 57725][IPFIX 35632.253] %RADIUS_ACCT_OUT_OCTETS           RADIUS Accounting Output Octets
[NFv9 57726][IPFIX 35632.254] %RADIUS_ACCT_IN_PKTS              RADIUS Accounting Input Packets
[NFv9 57727][IPFIX 35632.255] %RADIUS_ACCT_OUT_PKTS             RADIUS Accounting Output Packets
```

Once you have this nProbe plugin enabled, you can use ntopng to collect the data and store the fields above (including the username) in a database. You will then be able to search the database for the users of interest.

**Comment by chasgames** [comment]
Awesome thanks very much

**Comment by kraker07** [comment]
> In order to dissect radius traffic you should combine ntopng with nProbe. The nProbe radius plugin allows you to extract the following information:
> 
> ```
> Plugin Radius Protocol templates:
> [NFv9 57712][IPFIX 35632.240] %RADIUS_REQ_MSG_TYPE              RADIUS Request Msg Type
> [NFv9 57713][IPFIX 35632.241] %RADIUS_RSP_MSG_TYPE              RADIUS Response Msg Type
> [NFv9 57714][IPFIX 35632.242] %RADIUS_USER_NAME                 RADIUS User Name (Access Only)
> [NFv9 57715][IPFIX 35632.243] %RADIUS_CALLING_STATION_ID        RADIUS Calling Station Id
> [NFv9 57716][IPFIX 35632.244] %RADIUS_CALLED_STATION_ID         RADIUS Called Station Id
> [NFv9 57717][IPFIX 35632.245] %RADIUS_NAS_IP_ADDR               RADIUS NAS IP Address
> [NFv9 57718][IPFIX 35632.246] %RADIUS_NAS_IDENTIFIER            RADIUS NAS Identifier
> [NFv9 57719][IPFIX 35632.247] %RADIUS_USER_IMSI                 RADIUS User IMSI (Extension)
> [NFv9 57720][IPFIX 35632.248] %RADIUS_USER_IMEI                 RADIUS User MSISDN (Extension)
> [NFv9 57721][IPFIX 35632.249] %RADIUS_FRAMED_IP_ADDR            RADIUS Framed IP
> [NFv9 57722][IPFIX 35632.250] %RADIUS_ACCT_SESSION_ID           RADIUS Accounting Session Name
> [NFv9 57723][IPFIX 35632.251] %RADIUS_ACCT_STATUS_TYPE          RADIUS Accounting Status Type
> [NFv9 57724][IPFIX 35632.252] %RADIUS_ACCT_IN_OCTETS            RADIUS Accounting Input Octets
> [NFv9 57725][IPFIX 35632.253] %RADIUS_ACCT_OUT_OCTETS           RADIUS Accounting Output Octets
> [NFv9 57726][IPFIX 35632.254] %RADIUS_ACCT_IN_PKTS              RADIUS Accounting Input Packets
> [NFv9 57727][IPFIX 35632.255] %RADIUS_ACCT_OUT_PKTS             RADIUS Accounting Output Packets
> ```
> 
> Once you have this nProbe plugin enabled, you can use ntopng to collect the data and store the fields above (including the username) in a database. You will then be able to search the database for the users of interest.



> In order to dissect radius traffic you should combine ntopng with nProbe. The nProbe radius plugin allows you to extract the following information:
> 
> ```
> Plugin Radius Protocol templates:
> [NFv9 57712][IPFIX 35632.240] %RADIUS_REQ_MSG_TYPE              RADIUS Request Msg Type
> [NFv9 57713][IPFIX 35632.241] %RADIUS_RSP_MSG_TYPE              RADIUS Response Msg Type
> [NFv9 57714][IPFIX 35632.242] %RADIUS_USER_NAME                 RADIUS User Name (Access Only)
> [NFv9 57715][IPFIX 35632.243] %RADIUS_CALLING_STATION_ID        RADIUS Calling Station Id
> [NFv9 57716][IPFIX 35632.244] %RADIUS_CALLED_STATION_ID         RADIUS Called Station Id
> [NFv9 57717][IPFIX 35632.245] %RADIUS_NAS_IP_ADDR               RADIUS NAS IP Address
> [NFv9 57718][IPFIX 35632.246] %RADIUS_NAS_IDENTIFIER            RADIUS NAS Identifier
> [NFv9 57719][IPFIX 35632.247] %RADIUS_USER_IMSI                 RADIUS User IMSI (Extension)
> [NFv9 57720][IPFIX 35632.248] %RADIUS_USER_IMEI                 RADIUS User MSISDN (Extension)
> [NFv9 57721][IPFIX 35632.249] %RADIUS_FRAMED_IP_ADDR            RADIUS Framed IP
> [NFv9 57722][IPFIX 35632.250] %RADIUS_ACCT_SESSION_ID           RADIUS Accounting Session Name
> [NFv9 57723][IPFIX 35632.251] %RADIUS_ACCT_STATUS_TYPE          RADIUS Accounting Status Type
> [NFv9 57724][IPFIX 35632.252] %RADIUS_ACCT_IN_OCTETS            RADIUS Accounting Input Octets
> [NFv9 57725][IPFIX 35632.253] %RADIUS_ACCT_OUT_OCTETS           RADIUS Accounting Output Octets
> [NFv9 57726][IPFIX 35632.254] %RADIUS_ACCT_IN_PKTS              RADIUS Accounting Input Packets
> [NFv9 57727][IPFIX 35632.255] %RADIUS_ACCT_OUT_PKTS             RADIUS Accounting Output Packets
> ```
> 
> Once you have this nProbe plugin enabled, you can use ntopng to collect the data and store the fields above (including the username) in a database. You will then be able to search the database for the users of interest.

Hi;

How is come from  router ? Can we do something on router?If I get radius plugin for ppp , is it combining data on dump file automaticly?
