### ISSUE TITLE
ntopng package does not perform restart after upgrade

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#908]
On Ubuntu (on CentOS this bug https://github.com/ntop/PF_RING/issues/170 must be fixed first to verify the problem) when the ntopng package is upgraded while ntopng is running, the upgrade is performed properly but ntopng is not restarted after the upgrade (i.e. the application is stopped but not restarted when the upgrade ends). The same issue is observed to other packages (e.g. nprobe). This must be fixed so that when the upgrade is completed, the ntopng service is restarted.

**Comment by emanuele-f** [comment]
Is this fixed with fa0f3f4?

**Comment by ValentinaViscarelli** [comment]
Fixed. I also reported the modify for nprobe, cento and n2disk.
