### ISSUE TITLE
Error compiling Ntopng

### ISSUE THREAD

**Issue by jerric12** [ntop/ntopng#91]
Hi,
I wanted to install ntopng 2 + nDpi 1.6 and i have an error when compiling ntopng.
My system is a Debian Jessie.
Can you help me please
Thanks a lot (Sorry for my englih i'm french ;-))
The error is 
----------------------------------------------------------------------------------------
In file included from /opt/ntopng/include/ntop_includes.h:153:0,
                 from src/HTTPBL.cpp:22:
/opt/ntopng/include/NetworkInterface.h:90:18: error: 'NUM_BREEDS' was not declared in this scope
     breeds_bytes[NUM_BREEDS];
                  ^
/opt/ntopng/include/NetworkInterface.h: In member function 'char* NetworkInterface::get_ndpi_proto_breed_name(u_int)':
/opt/ntopng/include/NetworkInterface.h:190:19: error: 'ndpi_get_proto_breed' was not declared in this scope
                 id))); };
                   ^
/opt/ntopng/include/NetworkInterface.h:190:20: error: 'ndpi_get_proto_breed_name' was not declared in this scope
                 id))); };
                    ^
In file included from /opt/ntopng/include/ntop_includes.h:180:0,
                 from src/HTTPBL.cpp:22:
/opt/ntopng/include/Host.h: At global scope:
/opt/ntopng/include/Host.h:154:23: error: 'ndpi_protocol' has not been declared
   bool doDropProtocol(ndpi_protocol l7_proto);
                       ^
In file included from /opt/ntopng/include/ntop_includes.h:181:0,
                 from src/HTTPBL.cpp:22:
/opt/ntopng/include/Flow.h:43:3: error: 'ndpi_protocol' does not name a type
   ndpi_protocol ndpi_detected_protocol;
   ^
/opt/ntopng/include/Flow.h:159:28: error: 'ndpi_protocol' has not been declared
   void setDetectedProtocol(ndpi_protocol proto_id);
                            ^
/opt/ntopng/include/Flow.h:179:10: error: 'ndpi_protocol' does not name a type
   inline ndpi_protocol get_detected_protocol()    { return(ndpi_detected_protocol);          };
          ^
/opt/ntopng/include/Flow.h:183:10: error: 'ndpi_protocol_breed_t' does not name a type
   inline ndpi_protocol_breed_t get_protocol_breed() { return(ndpi_get_proto_breed(iface->get_ndpi_struct(), ndpi_detected_protocol.protocol)); };
          ^
In file included from /opt/ntopng/include/ntop_includes.h:181:0,
                 from src/HTTPBL.cpp:22:
/opt/ntopng/include/Flow.h: In member function 'char* Flow::get_protocol_breed_name()':
/opt/ntopng/include/Flow.h:186:18: error: 'ndpi_detected_protocol' was not declared in this scope
                  ndpi_detected_protocol.protocol))); };
                  ^
/opt/ntopng/include/Flow.h:186:49: error: 'ndpi_get_proto_breed' was not declared in this scope
                  ndpi_detected_protocol.protocol))); };
                                                 ^
/opt/ntopng/include/Flow.h:186:50: error: 'ndpi_get_proto_breed_name' was not declared in this scope
                  ndpi_detected_protocol.protocol))); };
                                                  ^
Makefile:131: recipe for target 'src/HTTPBL.o' failed
make: *** [src/HTTPBL.o] Error 1

**Comment by lucaderi** [comment]
You are using an old nDPI. Please get both ntopng and nDPI from github

**Comment by jerric12** [comment]
Thanks a lot. I'v installed 2 versions of ndpi, with apt-get and github.
