### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by freebooterish** [ntop/ntopng#910]
./autogen.sh
./configure
make 
......... 
src/Lua.cpp: In function 'int ntop_get_ndpi_protocols(lua_State*)':
src/Lua.cpp:2427:27: error: 'NDPI_PROTOCOL_NUM_CATEGORIES' was not declared in this scope
     if(category_filter >= NDPI_PROTOCOL_NUM_CATEGORIES)
                           ^
src/Lua.cpp: In function 'int ntop_get_ndpi_categories(lua_State*)':
src/Lua.cpp:2444:21: error: 'NDPI_PROTOCOL_NUM_CATEGORIES' was not declared in this scope
   for (int i=0; i < NDPI_PROTOCOL_NUM_CATEGORIES; i++) {
                     ^
Makefile:138: recipe for target 'src/Lua.o' failed
make: *** [src/Lua.o] Error 1

**Comment by simonemainardi** [comment]
@freebooterish update nDPI to the latest version and it will work
