### ISSUE TITLE
Preferences layout broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#915]
It looks like the layout of the preferences is now broken after the recent changes made
<img width="958" alt="screen shot 2017-01-09 at 17 49 00" src="https://cloud.githubusercontent.com/assets/4493366/21790984/9b6da8d2-d694-11e6-8833-f08dd45bc800.png">
<img width="822" alt="screen shot 2017-01-09 at 17 48 33" src="https://cloud.githubusercontent.com/assets/4493366/21790985/9b707c88-d694-11e6-9d8f-a467183a900a.png">

**Comment by emanuele-f** [comment]
Fix contained into #918
