### ISSUE TITLE
Preferences log level broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#916]
Changing the log level, modifies the icon of the search button instead of the preference one. The bug is documented below.
<img width="359" alt="screen shot 2017-01-09 at 18 02 19" src="https://cloud.githubusercontent.com/assets/4493366/21791229/469bfa32-d696-11e6-938d-fecd2e4d4896.png">

<img width="275" alt="screen shot 2017-01-09 at 18 03 33" src="https://cloud.githubusercontent.com/assets/4493366/21791230/469c0ac2-d696-11e6-9904-fa687dcbe21b.png">

For consistency it would be nice to replace the pop-down with buttons similar to those used for units (sec, min...).

**Comment by emanuele-f** [comment]
Fix contained into #918. Pop-down has been replaced with coloured toggle buttons.
