### ISSUE TITLE
Traffic from remote nProbe drops off from NTOPNG.

### ISSUE THREAD

**Issue by ipbowker** [ntop/ntopng#917]
When I first start ntopng, I see traffic from my remote nProbe server.  After anything between 3 - 36 hours, the interface view and other views of the nProbe traffic show no traffic.

Restarting ntopng, brings it back to life again until next failure.

nprobe-eth2.conf
-i=eth2
--zmq=tcp://10.97.10.25:2055
-G
-n=none

ntopng.conf
-G=/var/run/ntopng.pid
--daemon
--http-port=10.100.10.25:3000
#What are our sources
# --interface=tcp://10.100.10.25:2055
--interface=eth2
--interface=tcp://10.97.10.25:2055
--local-networks="xx.yy.92.0/27,xx.yy.92.32/27,146.80.128.0/19,146.80.160.0/19"
#Maximum number of expected active hosts and flows.
--max-num-hosts=30000
--max-num-flows=70000

#Only resolve what you've sniffed from DNS packets.
--dns-mode=2

**Comment by lucaderi** [comment]
Can you please check if the problem is on the probe or on the collector side? i.e. are flows still being exported or not?

I assume you are using the latest development packages and that you have a valid nProbe license otherwise this problem is due to the end of the demo-mode

**Comment by ipbowker** [comment]
No, I'm running the latest stable builds updated via yum.

I never have to restart the probe, only ntopng to resolve the issue.  TCPDump on the NTOPNG server shows no flows from the probe until I restart the NTOPNG service.  

Even under fault conditions traffic is still observed from the local collector interface eth2.

**Comment by emanuele-f** [comment]
Can you post a full log of ntopng in the meanwhile the problem appears?

**Comment by ipbowker** [comment]
Which logs?
/var/log/ntopng/ntopng.log
/var/tmp/ntopng/ntopng.log

**Comment by emanuele-f** [comment]
It depends on your configuration. You can find out which one is the correct one executing `tail -f [logfile]` and then restarting the ntopng service. The correct one will scroll the terminal while ntopng is restarting. 

You should post the part of the log from start of ntopng to stop while you are reproducing the error.

**Comment by emanuele-f** [comment]
@ipbowker any updates on the log? Did you managed to solve the issue?

**Comment by ipbowker** [comment]
Sorry, I've been out of office for a while.  It doesn't appear to have stopped again since though?
I've had one NTOPNG outage but that was due to excess disk consumption by RRD files.

**Comment by emanuele-f** [comment]
Your /19 networks can eat a lot of disk space in RRD files. Please check out your "On-Disk Timeseries" settings to reduce per-host space. This could be the original source of the issue.

**Comment by emanuele-f** [comment]
Please reopen if necessary.
