### ISSUE TITLE
Preference Tab

### ISSUE THREAD

**Issue by epodberezkin** [ntop/ntopng#919]
After update Preference Tab contains "Change Password" and "Export Data" only. Direct link (f.e.
/lua/admin/prefs.lua?subpage_active=data_purge) shows  "Access forbidden".

License	GNU GPLv3
Version	2.5.170110 - Community Edition
Built on	Ubuntu 16.04.1 LTS

**Comment by emanuele-f** [comment]
The preferences page access is restricted to Administrator ntopng users only, since it allows you to modify sensitive settings.

Please reopen if necessary.
