### ISSUE TITLE
Flow.cpp build error on last code pull

### ISSUE THREAD

**Issue by pcmerc** [ntop/ntopng#92]
pulled latest nDPI, compiled & installed
pulled latest ntopng, compile fails with errors:

Previous build, built with no errors.

src/Flow.cpp: In constructor ‘Flow::Flow(NetworkInterface*, u_int16_t, u_int8_t, u_int8_t*, IpAddress*, u_int16_t, u_int8_t*, IpAddress*, u_int16_t, time_t, time_t)’:
src/Flow.cpp:97:32: error: cannot convert ‘ndpi_protocol {aka ndpi_proto}’ to ‘u_int16_t {aka short unsigned int}’ in assignment
src/Flow.cpp: In member function ‘void Flow::guessProtocol()’:
src/Flow.cpp:473:29: error: cannot convert ‘ndpi_protocol {aka ndpi_proto}’ to ‘u_int16_t {aka short unsigned int}’ in assignment
make: *** [src/Flow.o] Error 1

**Comment by ariava** [comment]
@pcmerc I currently don't see any compile-time error with dev branches of ntopng and nDPI. Did you get the dev branch of both repos? You need to have both stable branches or both dev branches.

**Comment by lucaderi** [comment]
You are still using an old nDPI with a new ntopng code. Check again

**Comment by pcmerc** [comment]
Thanks guys

4 drwxr-sr-x  3 root staff  4096 Jun 30 17:53 libndpi-1.6.1
 4 drwxr-sr-x  3 root staff  4096 Jul 23 01:04 libndpi-1.7.0

Yup it appears 2 dif versions
