### ISSUE TITLE
filtering hosts in vlan tab should respect selected vlan

### ISSUE THREAD

**Issue by ghost** [ntop/ntopng#921]
currently when filtering hosts in vlan tab, the filter is applied to all hosts, rather than the previously selected vlan

it's not a big issue as you can manually go to http://server/lua/hosts_stats.lua?vlan=164&mode=local, to filter local hosts on a vlan, but it would be a nice enhancement

**Comment by emanuele-f** [comment]
Fixed in #922. Thank you for reporting.
