### ISSUE TITLE
Ntopng dropped packets !

### ISSUE THREAD

**Issue by iPhosphoR** [ntop/ntopng#927]
Hi,

My eth1 drop packets and so I think that does not allow to display the correct figure of the bandwidth ... Why ???

![drop](https://cloud.githubusercontent.com/assets/24895578/21980603/32f4d848-dbe4-11e6-9202-3dd02e13db1d.png)

And I have many alerts!

![alerts](https://cloud.githubusercontent.com/assets/24895578/21980591/2b29b476-dbe4-11e6-975b-29d63de3f18f.png)

**Comment by simonemainardi** [comment]
packets dropped are shown under the Interface "home" button.

The "lost" you highlighted are packets LOST with TCP.

show the full text of alerts not only the first part

**Comment by iPhosphoR** [comment]
![alert](https://cloud.githubusercontent.com/assets/24895578/21981620/9e78e2cc-dbe8-11e6-87f7-31466188517c.png)

And Why ~4,000 packets out of order ?

**Comment by simonemainardi** [comment]
- alerts shown are mono-directional flows, that is, flows that have carried traffic in just one of the two possible directions (.e.g, client to server or server to client). You should investigate why those flows occur as they are suspicious. Maybe there are applications that periodically poll a remote server without answer, for example. You should investigate that on your own.

- Typically, packets out of order depends on the network. For example, different IP packets can take different routes and thus can be delivered to the host in an arbitrary order (even if this is rather seldom).
