### ISSUE TITLE
FR: graphs on main page linked with username/allowed networks

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#928]
on my ntop, I have few networks in configuration : public + private
I created a user for my colleagues just to show them networks they managed... that works well

My problem is that on main page, all graphs represent all data/traffic and not only data from networks they managed, so it's a bit confused, I have to explain them do not use them

So I would like to get graphs only from networks I allowed in user preference for a specific user, maybe just an option.

thanks

nico

PS : not only graphs on main page cause all other should follow user and its rights (allowed networks)

**Comment by simonemainardi** [comment]
Dashboard top local hosts and top remote destinations are properly filtered according to the authorizations of the current web user. No unauthorized host is ever shown.

Regarding the top application protocols and realtime traffic, they refer to the whole interface as is it clearly stated in the titles. Reducing the volumes of traffic shown will therefore cause inconsistencies in the charts.

Also when you navigate hosts / network pages, hosts counters reflect the right values by taking into account only the authorized hosts.
