### ISSUE TITLE
Remote Host Throughput Showing 0 bps but Traffic is Collecting Correct Data

### ISSUE THREAD

**Issue by mmaxwell3n1** [ntop/ntopng#93]
Under Host > Host, any remote locations are not showing Throughput but are showing correct Traffic data.  All remote locations show 0 bps  This feature worked fine with the same configuration before.

ntopng V 2.0.150609 
Ubuntu 14.04 LTS
Free License

**Comment by ariava** [comment]
@mmaxwell3n1 could you please update to the latest nightly? Recently @lucaderi fixed a bug that could trigger this issue.

**Comment by mmaxwell3n1** [comment]
I just updated to the nightly build.  I am on version Community v.2.0.150723.  I am still getting no Remote traffic.  Please see attached image.

Thank you for helping.

![welcome to ntopng](https://cloud.githubusercontent.com/assets/13470200/8860698/075f60a8-314b-11e5-8958-b72a32ec9517.jpg)
