### ISSUE TITLE
License Issue, Ntop can not get the license from Radis server.

### ISSUE THREAD

**Issue by BroadbandCommunicationsNorth** [ntop/ntopng#931]
OS: CentOS 7.3.1611, 16 GB, 4 CPU
License has been put in /etc/nprobe.license.
Nprobe gets this license, but Ntop does not not get the license from Radis server.

Nprobe software information:

[root@nprobe ntopng]# nprobe -v
Welcome to nProbe v.7.4.161220 (r5334) for x86_64-unknown-linux-gnu
with native PF_RING acceleration.
Copyright 2002-16 ntop.org

Build OS:      CentOS Linux release 7.3.1611 (Core)
SystemID:      9XXXXXXXXXXXXXXXXXX9
GIT rev:       7.4-stable:1c6a46955c431c129cce7dd522ce35b3e83fe4ee:20161220
Edition:       nProbe Pro
License:       9XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX9 [valid license]
License Type:  Permanent License
Maintenance:   Until Fri Jan 12 14:59:44 2018 [364 days left]

nProbe is subject to the terms and conditions defined in
the LICENSE and EULA files that are part of this package.

nProbe also contains third party code:
Radix tree code - (C) The Regents of the University of Michigan
                      ("The Regents") and Merit Network, Inc.
sFlow collector - (C) InMon Inc.

Nprobe log:

12/Jan/2017 15:12:49 [nprobe.c:3407] Valid nProbe Pro license found
12/Jan/2017 15:12:49 [plugin.c:168] No plugins found in ./plugins
12/Jan/2017 15:12:49 [plugin.c:176] Loading 24 plugins [.so] from /usr/local/lib/nprobe/plugins
12/Jan/2017 15:12:49 [plugin.c:778] Unable to enable plugin DHCP Protocol [/etc/nprobe.license.dhcp]: License Ok
12/Jan/2017 15:12:49 [plugin.c:778] Unable to enable plugin Diameter Protocol [/etc/nprobe.license.diameter]: License Ok
12/Jan/2017 15:12:49 [plugin.c:778] Unable to enable plugin DNS/LLMNR Protocol [/etc/nprobe.license.dns]: License Ok
12/Jan/2017 15:12:49 [plugin.c:778] Unable to enable plugin Export Plugin [/etc/nprobe.license.export]: License Ok
12/Jan/2017 15:12:49 [plugin.c:778] Unable to enable plugin FTP Protocol [/etc/nprobe.license.ftp]: License Ok
12/Jan/2017 15:12:49 [plugin.c:778] Unable to enable plugin GTPv0 Signaling Protocol [/etc/nprobe.license.gtpv0]: License Ok
12/Jan/2017 15:12:49 [plugin.c:778] Unable to enable plugin GTPv1 Signaling Protocol [/etc/nprobe.license.gtpv1]: License Ok
12/Jan/2017 15:12:49 [plugin.c:778] Unable to enable plugin GTPv2 Signaling Protocol [/etc/nprobe.license.gtpv2]: License Ok
12/Jan/2017 15:12:49 [plugin.c:778] Unable to enable plugin HTTP Protocol [/etc/nprobe.license.http]: License Ok
12/Jan/2017 15:12:49 [plugin.c:778] Unable to enable plugin IMAP Protocol [/etc/nprobe.license.email]: License Ok
12/Jan/2017 15:12:49 [plugin.c:778] Unable to enable plugin Netflow-Lite Plugin [/etc/nprobe.license.nflite]: License Ok
12/Jan/2017 15:12:49 [plugin.c:778] Unable to enable plugin Oracle Protocol [/etc/nprobe.license.oracle]: License Ok
12/Jan/2017 15:12:49 [plugin.c:778] Unable to enable plugin POP3 Protocol [/etc/nprobe.license.email]: License Ok
12/Jan/2017 15:12:49 [plugin.c:778] Unable to enable plugin System process information [/etc/nprobe.license.process]: License Ok
12/Jan/2017 15:12:49 [plugin.c:778] Unable to enable plugin Radius Protocol [/etc/nprobe.license.radius]: License Ok
12/Jan/2017 15:12:49 [plugin.c:778] Unable to enable plugin RTP Plugin [/etc/nprobe.license.voip]: License Ok
12/Jan/2017 15:12:49 [plugin.c:778] Unable to enable plugin S1AP Protocol [/etc/nprobe.license.S1AP]: License Ok
12/Jan/2017 15:12:49 [plugin.c:778] Unable to enable plugin SIP Plugin [/etc/nprobe.license.voip]: License Ok
12/Jan/2017 15:12:49 [plugin.c:778] Unable to enable plugin SMTP Protocol [/etc/nprobe.license.email]: License Ok
12/Jan/2017 15:12:49 [nprobe.c:4872] WARNING: The output interfaceId is set to 0: did you forget to use -Q perhaps ?
12/Jan/2017 15:12:49 [nprobe.c:4875] WARNING: The input interfaceId is set to 0: did you forget to use -u perhaps ?
12/Jan/2017 15:12:49 [nprobe.c:4975] Welcome to nProbe Pro v.7.4.161220 ($Revision: 5334 $) for x86_64-unknown-linux-gnu with native PF_RING acceleration
12/Jan/2017 15:12:49 [nprobe.c:4985] Running on CentOS Linux release 7.3.1611 (Core)
12/Jan/2017 15:12:49 [nprobe.c:4996] [LICENSE] nProbe SystemId: 9XXXXXXXXXXXXXXXXXX9
12/Jan/2017 15:12:49 [nprobe.c:7308] Welcome to nProbe v.7.4.161220 for x86_64-unknown-linux-gnu
12/Jan/2017 15:12:49 [plugin.c:1045] 0 plugin(s) enabled

Ntopng log:

12/Jan/2017 15:14:24 [Prefs.cpp:686] ntopng will use redis localhost:6379@0
12/Jan/2017 15:14:24 [Ntop.cpp:1121] Setting local networks to 127.0.0.0/8
12/Jan/2017 15:14:24 [Redis.cpp:92] Successfully connected to redis localhost:6379@0
12/Jan/2017 15:14:24 [NtopPro.cpp:118] [LICENSE] Read license from Redis [ 9XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX9]
12/Jan/2017 15:14:24 [NtopPro.cpp:182] ERROR: [LICENSE] Invalid or missing ntopng License [License format error]
12/Jan/2017 15:14:24 [NtopPro.cpp:195] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
12/Jan/2017 15:14:24 [NtopPro.cpp:197] WARNING: [LICENSE] before returning to community mode
12/Jan/2017 15:14:24 [NtopPro.cpp:198] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
12/Jan/2017 15:14:24 [NtopPro.cpp:199] WARNING: [LICENSE] or run ntopng in community mode starting
12/Jan/2017 15:14:24 [NtopPro.cpp:200] WARNING: [LICENSE] ntopng --community
12/Jan/2017 15:14:24 [MySQLDB.cpp:549] Attempting to connect to MySQL for interface tcp://127.0.0.1:1234...
12/Jan/2017 15:14:24 [MySQLDB.cpp:589] Succesfully connected to MySQL [localhost:nprobe] for interface tcp://127.0.0.1:1234
12/Jan/2017 15:14:24 [Ntop.cpp:1267] Registered interface tcp://127.0.0.1:1234 [id: 5]
12/Jan/2017 15:14:24 [Ntop.cpp:1279] Registered interface view tcp://127.0.0.1:1234 [id: 5]
12/Jan/2017 15:14:24 [main.cpp:255] PID stored in file /var/run/ntopng.pid
12/Jan/2017 15:14:24 [Utils.cpp:341] User changed to nobody
12/Jan/2017 15:14:24 [HTTPserver.cpp:501] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
12/Jan/2017 15:14:24 [HTTPserver.cpp:544] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
12/Jan/2017 15:14:24 [HTTPserver.cpp:547] HTTP server listening on port 8080
12/Jan/2017 15:14:24 [MySQLDB.cpp:549] Attempting to connect to MySQL for interface tcp://127.0.0.1:1234...
12/Jan/2017 15:14:24 [MySQLDB.cpp:589] Succesfully connected to MySQL [localhost:nprobe] for interface tcp://127.0.0.1:1234
12/Jan/2017 15:14:24 [main.cpp:309] Working directory: /opt/storage/ntopng
12/Jan/2017 15:14:24 [main.cpp:311] Scripts/HTML pages directory: /usr/share/ntopng
12/Jan/2017 15:14:24 [Ntop.cpp:271] Welcome to ntopng x86_64 v.2.4.161220 - (C) 1998-2016 ntop.org
12/Jan/2017 15:14:24 [Ntop.cpp:276] Built on CentOS Linux release 7.3.1611 (Core).
12/Jan/2017 15:14:24 [PeriodicActivities.cpp:53] Started periodic activities loop...
12/Jan/2017 15:14:24 [RuntimePrefs.cpp:34] Dumping alerts into syslog
12/Jan/2017 15:14:24 [NtopPro.cpp:259] [LICENSE] ntopng systemId: 9XXXXXXXXXXXXXXXXXX9
12/Jan/2017 15:14:24 [NtopPro.cpp:264] [LICENSE] ntopng is starting in demo mode
12/Jan/2017 15:14:24 [NetworkInterface.cpp:1538] Started packet polling on interface tcp://127.0.0.1:1234 [id: 5]...
12/Jan/2017 15:14:25 [MySQLDB.cpp:549] Attempting to connect to MySQL for interface tcp://127.0.0.1:1234...
12/Jan/2017 15:14:25 [MySQLDB.cpp:589] Succesfully connected to MySQL [localhost:nprobe] for interface tcp://127.0.0.1:1234
12/Jan/2017 15:14:25 [CollectorInterface.cpp:104] Collecting flows on tcp://127.0.0.1:1234 [ntopng->nprobe]

**Comment by emanuele-f** [comment]
You cannot use nprobe licence on ntopng, it is a separate licence

**Comment by lucaderi** [comment]
Taking this request offline
