### ISSUE TITLE
Elasticsearch identifies improper fields 

### ISSUE THREAD

**Issue by maggiedeblock** [ntop/ntopng#934]
Good morning, 

I'm having an issue with the ntopng index in elasticsearch and some visualizations / plugins viewing the wrong information. When using some 3rd party plugins (like sunburst) or Elastic Graph with Kibana and the ntopng index, it sometimes has trouble with the IP address data. In the Sunburst plugin for example, it pulls the "key"  field which appears to be some arbitrary number instead of the "key as string" field which in the response output, is the proper IP address. Also, the elastic graph claims the field is not an IP address and as such won't let me visualize the data. It doesn't give a reason but it may be seeing the "key"  instead of the string. Most other plugins and visualizations have no issues with these strings. Would this be an issue of the plugins themselves or something I need to change in ntopng's elasticsearch output?

**Comment by simonemainardi** [comment]
We store IPv4 addresses with type "ip" in elastic search and not as plain strings. This is the ES template definition: https://github.com/ntop/ntopng/blob/dev/httpdocs/misc/ntopng_template_elk.json#L22

I guess that somehow the "arbitrary number"  you are referring to is the 4-byte integer representation of the IP address.

Anyway, please give us detailed examples and we'll try to help even if I honestly think the issues are more on the side of the plugins.

**Comment by maggiedeblock** [comment]
Thank you for the response. I'm also attacking it from the plugin perspective and if I get anywhere I'll post the fix here and close it, just in case someone wanders by. Anyways, here is an example of the request / response while utilizing the Sunburst plugin from Juan Carniglia's github. I've also attached a screenshot of the resulting Sunburst as well as the pop-up table displaying the correct information. 


**Request:**

```
{
  "size": 0,
  "query": {
    "filtered": {
      "query": {
        "query_string": {
          "analyze_wildcard": true,
          "query": "*"
        }
      },
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gte": 1484391657358,
                  "lte": 1484478057358,
                  "format": "epoch_millis"
                }
              }
            }
          ],
          "must_not": []
        }
      }
    }
  },
  "aggs": {
    "2": {
      "terms": {
        "field": "IPV4_DST_ADDR",
        "size": 5,
        "order": {
          "_count": "desc"
        }
      }
    }
  }
}
```

**Response:**

```
{
  "took": 4,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 16576,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "2": {
      "doc_count_error_upper_bound": 78,
      "sum_other_doc_count": 7296,
      "buckets": [
        {
          "key": 3232236306,
          "key_as_string": "192.168.3.18",
          "doc_count": 3569
        },
        {
          "key": 4026531834,
          "key_as_string": "239.255.255.250",
          "doc_count": 2264
        },
        {
          "key": 3232236543,
          "key_as_string": "192.168.3.255",
          "doc_count": 2101
        },
        {
          "key": 3232236289,
          "key_as_string": "192.168.3.1",
          "doc_count": 542
        },
        {
          "key": 3232236380,
          "key_as_string": "192.168.3.92",
          "doc_count": 278
        }
      ]
    }
  }
}
```

![0b09ab0e-dbff-11e6-9835-0f930e8afb42](https://cloud.githubusercontent.com/assets/25132251/22062982/cebddedc-ddbf-11e6-924b-568bd8dbd23b.png)
![285b6f4e-dbff-11e6-9e80-197522202188](https://cloud.githubusercontent.com/assets/25132251/22062983/cec0f7ca-ddbf-11e6-9d92-89bfd0371ff3.png)

**Comment by simonemainardi** [comment]
there's nothing strange in the JSON response shown, "key" is the integer representation and "key_as_string" is the dotted-string representation of the same Ipv4 address.

**Comment by simonemainardi** [comment]
@maggiedeblock do you have any news?

**Comment by simonemainardi** [comment]
Explanation given. No feedback. Closing.
