### ISSUE TITLE
Local networks defined grouped under the wrong network prefixes.

### ISSUE THREAD

**Issue by Marlow925** [ntop/ntopng#938]
ntopng  v.2.5.170119

output of /etc/ntopng/ntopng.conf 
-G=/var/run/ntopng.pid
-m=10.129.0.0/16,fddf:bf7:10:1::/64,fe00::/4,64:ff9b::/96
-i=tcp://XXX.XXX.XXX.XXX:1234

Screenshot of Networks -> https://c1.staticflickr.com/1/578/32036269260_81a85592bb_b.jpg
Clicking into 10.129.0.0/16 -> https://c1.staticflickr.com/1/440/32263379162_7a38b6e3a2_b.jpg

It looks like ALL local nets are grouped into the one network listed in the list of local networks.

/M

**Comment by edhil** [comment]
+1 Same issue here

**Comment by emanuele-f** [comment]
I can reproduce easily:
- ntopng -m 192.168.1.130/32,192.168.1.0/24
- ping 192.168.1.130
- ping 192.168.1.1
- but all local traffic/hosts goes into 192.168.1.130/32 network
