### ISSUE TITLE
Is there any possible to change data retention time?

### ISSUE THREAD

**Issue by lhxhanson** [ntop/ntopng#939]
Hi all,
[https://github.com/ntop/ntopng/issues/733](url)
In the issue 733, you said "Since cleanup according to the data retention settings is performed once per day using the unix epoch, it should occurs exactly at UTC+8 on your system so your point is meaningful."

So when the database starting data retention, it will locked and the record can not write in for while. But our timezone is UTC+8, the start time is 8:00 am. Is there any possible to change the data retention time to 0:00 not just depends on unix epoch?

Thx~

**Comment by simonemainardi** [comment]
daily activities are already coded to execute at midnight local time (https://github.com/ntop/ntopng/blob/dev/src/PeriodicActivities.cpp#L218)

Please update to the latest dev version.

**Comment by lhxhanson** [comment]
Does the stable version has this feature now?

**Comment by simonemainardi** [comment]
yes: https://github.com/ntop/ntopng/blob/2.4-stable/src/PeriodicActivities.cpp#L191

**Comment by lhxhanson** [comment]
@simonemainardi 
Hi simone

Several days ago, I updated ntopng to stable version: x86_64 v.2.4.170202, and it looks like the data retention still start at 8:00.

Hers is the ntopng log:
![image](https://cloud.githubusercontent.com/assets/5568373/22675030/35876166-ed1e-11e6-839c-dc6a925dfc39.png)

and this is my `date -R` result:

![qq 20170207101522](https://cloud.githubusercontent.com/assets/5568373/22675059/5ba21184-ed1e-11e6-8e40-d6a5e3b7f436.png)

**Comment by simonemainardi** [comment]
The screenshot enclosed only shows MySQL reconnections at 8.00, that is, exactly 8 hours after the latest connections (by default, mysql connection timeout is 8 h). This is normal.

You should verify, using mysql `show processlist` , if the system is actually doing the cleanup `DELETE` queries at 8am

**Comment by lhxhanson** [comment]
Oh, I forget the Mysql timeout.
OK, this issue can really close.
Thx~

**Comment by lhxhanson** [comment]
@simonemainardi 
Several days ago, we use dev instead of stable version. But we got some strange log:
![image](https://cloud.githubusercontent.com/assets/5568373/23685681/538986c0-03e0-11e7-9e32-f1456e00437f.png)

After these log came out, I use a simple script to run `SHOW FULL PROCESSLIST` to get the MySQL state every 1s. And it looks like the data retention still start at 8:00 not 0:00:
![image](https://cloud.githubusercontent.com/assets/5568373/23685658/3933aa62-03e0-11e7-9acc-8d48b2783b8d.png)
