### ISSUE TITLE
LDAP is not sending authentication requests on login - CenOS 7.

### ISSUE THREAD

**Issue by BroadbandCommunicationsNorth** [ntop/ntopng#940]
I am sorry, but previous case is closed, but we have the same issue.
https://github.com/ntop/ntopng/issues/784

We have the same issue with 2.4.161220 - Pro Small Business Edition, CentOS Linux release 7.3.1611 (Core).
According tcpdump, Ntop does not send any traffic to Active Directory Ldap server, which is set up in ldap://10.10.10.1:389. Tried to include verbose mode for Ntopng, nothing appeared in the log.

**Comment by simonemainardi** [comment]
@BroadbandCommunicationsNorth dev version of ntopng contains the fix. Please update

**Comment by BroadbandCommunicationsNorth** [comment]
v.2.5.170123 version, from nightly builds  http://packages.ntop.org/centos/ repository works with Active directory LDAP, ports 389/3268.

**Comment by simonemainardi** [comment]
correct, this is the fix: https://github.com/ntop/ntopng/commit/aa8789db7f282e5106a9dd53a9cdec791b782277
