### ISSUE TITLE
Menu.lua script generates forms switch_interface_forms with the same ID

### ISSUE THREAD

**Issue by bluedogs** [ntop/ntopng#941]
Menu.lua has a loop that generates the drop interface menu. If you only have two interfaces you will not notice that each form generated has the same id so only the first form created gets submitted. 

On my local copy I here is what the fixed code looks like.
```lua
 if(v == ifname) then
      print("<a href=\""..ntop.getHttpPrefix().."/lua/if_stats.lua?id="..k.."\">")
   else
      print[[<form id="switch_interface_form_]] print(tostring(k)) print[[" method="post" action="]] print(ntop.getHttpPrefix()) print[[/lua/if_stats.lua?id=]] print(tostring(k)) print[[">]]
      print[[<input name="switch_interface" type="hidden" value="1" />]]
      print[[<input name="csrf" type="hidden" value="]] print(ntop.getRandomCSRFValue()) print[[" />]]
      print[[</form>]]
      print[[<a href="javascript:void(0);" onclick="$('#switch_interface_form_]]  print(tostring(k))  print[[').submit();">]]
   end
```

I have added __]] print(tostring(k)) print[[__ to the form id field and the onclick call.

I apologize that I do not have this git repository cloned to issue a pull request.

Also I am using the small business license as well.

**Comment by emanuele-f** [comment]
Fixed with 92b40eb2d03fefd7160c32b2b22334a528dc2dfb. Thank you!
