### ISSUE TITLE
Access to ntopng WebGUI - strange redirect

### ISSUE THREAD

**Issue by Alestor** [ntop/ntopng#942]
Hi, 

I justed updated ntopng today and can't access the webgui after logut. The Webserver is redirecting me to a IP Address which isn't available on my network:

http://192.168.1.131:3000/lua/login.lua?referer=172.16.x.x:3000/

I usal do access ntopng's webgui by using a DNS Name. 172.16.x.x is the real IP Address of the Server.

Does somebody have an idea whats going on?

Edit:

 ntopng -V
v.2.5.170121 [Enterprise/Professional Edition]
GIT rev:   dev:bfa78e73f27ad3efd22eff0010d6672412c79ad4:20170121

**Comment by Alestor** [comment]
Please check commit:

https://github.com/ntop/ntopng/commit/bfa78e73f27ad3efd22eff0010d6672412c79ad4#diff-eb0e40210459e3d89a487bef836ab604

**Comment by lucaderi** [comment]
Fixed by https://github.com/ntop/ntopng/commit/5a308e35aaa2e2b726be681686dc60b3cb7e3bf6
