### ISSUE TITLE
nprobe hanging when stopping

### ISSUE THREAD

**Issue by mAineAc-** [ntop/ntopng#943]
Every time I try to update nprobe I get this:

Adding the nprobe startup script
Synchronizing state for nprobe.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d nprobe defaults
Executing /usr/sbin/update-rc.d nprobe enable
(Re)Starting nprobe...
Stopping nProbe none
 
And then it just hangs there indefinitely until I stop the nprobe process. Once I kill the process it continues on teh install but I have an error in apt and it tries to rerun this process for every update even when it does not include nprobe.

**Comment by mAineAc-** [comment]
This is happening on two unrelated systems for me right now. One is 
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux
the other is 
Linux 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ValentinaViscarelli** [comment]
@mAineAc- 
I'm not able to reproduce the problem. Anyway i have made a fix. 
Please update to tomorrow release and give it a try.
Thanks

**Comment by mAineAc-** [comment]
@ValentinaViscarelli 
This did not appear to fix the issue. I have gone so far as to purge nprobe and find all of the related files that were not removed, delete them nad try to re-install with the same issue. It always hangs on nProbe (re)start. Is there something in my settings that could cause that? I have a pretty straight forward set up. nothing fancy.

nprobe.conf has this:

--zmq="tcp://*:5556"
--collector-port=2055
-n=none
-i=none

nprobe.start is empty

**Comment by ValentinaViscarelli** [comment]
@mAineAc- 
could you please report here the output of this command?

cat /etc/init.d/nprobe

Thanks

**Comment by mAineAc-** [comment]
Debian device:

[sudo] password for rhall:
#! /bin/bash
#
# (C) 2003-16 - ntop.org
#
# chkconfig: 2345 80 30
#
### BEGIN INIT INFO
# Provides:          nprobe
# Required-Start:    $local_fs $remote_fs $network $syslog $pf_ring
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop nprobe
### END INIT INFO

#Needed to skip systemctl redirect in ubuntu 16
_SYSTEMCTL_SKIP_REDIRECT=yes

start_nprobe_instance() {
    INTERFACE_NAME=$1
    ID=$2

    CONFIG_FILE=/tmp/nprobe-${INTERFACE_NAME}@${ID}.conf
    EXP_IF=""
    IP_EXP_IF=""
    if [ -f "/var/ntop/utils/exporting.conf" ]; then
      EXP_IF=$(cat '/var/ntop/utils/exporting.conf' | grep 'exporting_interface='|cut -d '=' -f 2)
      if [ "${EXP_IF}" != "" ]; then
        IP_EXP_IF=$(ifconfig $EXP_IF | grep 'inet addr:'| cut -d: -f2 | awk '{ print $1}')
      fi
    fi

    sed -e "s/\#ID/$ID/" /etc/nprobe/nprobe-${INTERFACE_NAME}.conf > ${CONFIG_FILE}

    if [ "${IP_EXP_IF}" != "" ]; then
      sed -i -e "s/\#EXPIF/$IP_EXP_IF/" ${CONFIG_FILE}
    else
      sed -i "/\#EXPIF/d" ${CONFIG_FILE}
    fi
    # computing core ID in case of --cpu-affinity=#ID+<offset>
    CORE_OFFSET=$(cat /etc/nprobe/nprobe-${INTERFACE_NAME}.conf | grep "\--cpu-affinity=#ID\+" | cut -d '+' -f 2)
    if [ "$CORE_OFFSET" ] && [ $CORE_OFFSET -gt 0 ]; then
        grep -v "\--cpu-affinity=" ${CONFIG_FILE} >${CONFIG_FILE}.tmp
        mv ${CONFIG_FILE}.tmp ${CONFIG_FILE}
        CORE=$(expr $CORE_OFFSET + $ID)
        echo "--cpu-affinity=$CORE" >> ${CONFIG_FILE}
    fi

    PID_FILE=$(cat ${CONFIG_FILE} | grep '\-g='|cut -d '=' -f 2)
    if [ -f "${PID_FILE}" ]; then
        PID=$(cat ${PID_FILE})
        if [ $PID -gt 0 ]; then
            IS_EXISTING=$(ps auxw | grep -w $PID | grep nprobe | wc -l)
            if [ $IS_EXISTING -gt 0 ]; then
                echo "nProbe $INTERFACE_NAME@$ID is already running [pid $PID]: not started"
                return 0
            fi
        fi
    fi
    touch /var/log/nprobe/${INTERFACE_NAME}-${ID}_flows_stats.txt
    chmod 777 /var/log/nprobe/${INTERFACE_NAME}-${ID}_flows_stats.txt
    /usr/local/bin/nprobe ${CONFIG_FILE} >> /var/log/nprobe/nprobe-${INTERFACE_NAME}@${ID}.log 2>&1 &
    if [ "${PID_FILE}" != "" ]; then
        ESC=0
        while [ ! -f "${PID_FILE}" ]
        do
            if [ $ESC -eq 5 ]; then
              break
            fi
            ESC=$((ESC+1))
            sleep 1
        done
    fi
}

start_nprobe_eth() {
    INTERFACE_NAME=$1
    FORCE=$2

    if [ -f /etc/nprobe/nprobe-${INTERFACE_NAME}.start ] || [ $FORCE -eq 1 ]; then
        echo "Starting nProbe $INTERFACE_NAME"
        ############# Needed to migrate from .cluster files to .group files #############
        if [ -f /etc/nprobe/nprobe-${INTERFACE_NAME}.cluster ]; then
            NUM=$(cat /etc/nprobe/nprobe-${INTERFACE_NAME}.cluster)
            NUM_STRING=""
            for ID in `seq 0 $[$NUM-1]`
            do
                NUM_STRING="$NUM_STRING""$ID "
            done
            echo ${NUM_STRING} > /etc/nprobe/nprobe-${INTERFACE_NAME}.group
            rm /etc/nprobe/nprobe-${INTERFACE_NAME}.cluster
        fi
        #################################################################################
        if [ -f /etc/nprobe/nprobe-${INTERFACE_NAME}.group ]; then
            NUM_ARRAY=$(cat /etc/nprobe/nprobe-${INTERFACE_NAME}.group)
        else
            NUM=$(cat /etc/nprobe/nprobe-${INTERFACE_NAME}.conf | grep '@#ID' | wc -l)
            if [ ! -z $NUM ] && [ $NUM -gt 0 ]; then
                # We are starting nprobe on a multi-queue interface
                NUM=$(cat /proc/net/pf_ring/dev/${INTERFACE_NAME}/info | grep 'RX Queues' | awk '{print $NF}')
            else
                NUM=1
            fi
            NUM_ARRAY=""
            for ID in `seq 0 $[$NUM-1]`
            do
                NUM_ARRAY="$NUM_ARRAY""$ID "
            done
        fi
        for ID in $NUM_ARRAY
        do
            start_nprobe_instance ${INTERFACE_NAME} ${ID}
        done
    else
        echo "nProbe $INTERFACE_NAME not started: missing /etc/nprobe/nprobe-${INTERFACE_NAME}.start"
    fi
    return 1
}


stop_nprobe_eth() {
    INTERFACE_NAME=$1
    echo "Stopping nProbe $INTERFACE_NAME"

    ARRAY_PID=()

    if [ -f /etc/nprobe/nprobe-${INTERFACE_NAME}.conf ]; then
        if [ -f /etc/nprobe/nprobe-${INTERFACE_NAME}.group ]; then
            NUM_ARRAY=$(cat /etc/nprobe/nprobe-${INTERFACE_NAME}.group)
        else
            NUM=$(cat /etc/nprobe/nprobe-${INTERFACE_NAME}.conf | grep '@#ID' | wc -l)
            if [ ! -z $NUM ] && [ $NUM -gt 0 ]; then
                # We are starting nprobe on a multi-queue interface
                NUM=$(cat /proc/net/pf_ring/dev/${INTERFACE_NAME}/info | grep 'RX Queues' | awk '{print $NF}')
            else
                NUM=1
            fi
            NUM_ARRAY=""
            for ID in `seq 0 $[$NUM-1]`
            do
                NUM_ARRAY="$NUM_ARRAY""$ID "
            done
        fi

        for ID in $NUM_ARRAY
        do
            if [ ! -f /tmp/nprobe-${INTERFACE_NAME}@${ID}.conf ]; then
                continue
            fi

            PID_FILE=$(cat /tmp/nprobe-${INTERFACE_NAME}@${ID}.conf | grep -E '^\-g=|^\-\-pid\-file='|cut -d '=' -f 2)
            if [ -f $PID_FILE ]; then
                PID=$(cat $PID_FILE)
                if [ $PID -gt 0 ]; then
                    ARRAY_PID+=($PID)
                    kill -15 $PID > /dev/null
                    if [ -f $PID_FILE ]; then
                        /bin/rm $PID_FILE
                    fi
                else
                    echo "Unable to stop nProbe $INTERFACE_NAME: invalid pid [$PID][$PID_FILE]"
                fi
        #else
        #    echo "Unable to stop nProbe $INTERFACE_NAME: missing pid $PID_FILE"
            fi
        done
        for PID_ELEM in $ARRAY_PID
        do
            EXIT_VAR=0
            IS_EXISTING=$(ps auxw | grep -w $PID_ELEM | grep nprobe | wc -l)
            while [ $IS_EXISTING -gt 0 ]
            do
                sleep 1
                IS_EXISTING=$(ps auxw | grep -w $PID_ELEM | grep nprobe | wc -l)
                EXIT_VAR=$((EXIT_VAR+1))
                if [ $EXIT_VAR -gt 5 ]; then
                  echo "Unable to stop nProbe $INTERFACE_NAME"
                  break
                fi
            done
        done
    else
        echo "nProbe $INTERFACE_NAME can't be stopped: missing /etc/nprobe/nprobe-${INTERFACE_NAME}.conf"
    fi

    return 0
}

generate_config_file() {
    IF_SELECTED=$1

    echo "Generating configuration file /etc/nprobe/nprobe-$IF_SELECTED.conf"
    echo "-n=none" > /etc/nprobe/nprobe-$IF_SELECTED.conf
    echo "-i=$IF_SELECTED" >> /etc/nprobe/nprobe-$IF_SELECTED.conf
    echo "-s=128" >> /etc/nprobe/nprobe-$IF_SELECTED.conf
    echo "-t=60" >> /etc/nprobe/nprobe-$IF_SELECTED.conf
    echo "-d=60" >> /etc/nprobe/nprobe-$IF_SELECTED.conf
    echo "-a=0" >> /etc/nprobe/nprobe-$IF_SELECTED.conf
    echo "-e=1" >> /etc/nprobe/nprobe-$IF_SELECTED.conf
    echo "-B=10" >> /etc/nprobe/nprobe-$IF_SELECTED.conf
    echo "-w=128000" >> /etc/nprobe/nprobe-$IF_SELECTED.conf
    echo "-z=0" >> /etc/nprobe/nprobe-$IF_SELECTED.conf
    echo "-S=1:1" >> /etc/nprobe/nprobe-$IF_SELECTED.conf
    echo "-E=0:0" >> /etc/nprobe/nprobe-$IF_SELECTED.conf
    echo "-g=/var/run/nprobe-$IF_SELECTED.pid" >> /etc/nprobe/nprobe-$IF_SELECTED.conf
    echo "--vlanid-as-iface-idx=none" >> /etc/nprobe/nprobe-$IF_SELECTED.conf
    echo "-V=5" >> /etc/nprobe/nprobe-$IF_SELECTED.conf
    echo "--dump-stats=/var/log/nprobe/$IF_SELECTED-0_flows_stats.txt" >> /etc/nprobe/nprobe-$IF_SELECTED.conf
    #touch /etc/nprobe/nprobe-$IF_SELECTED.start
    echo "/etc/nprobe/nprobe-$IF_SELECTED.conf created successful"
}

start_nprobe() {
    INTERFACE_NAME=$1
    FORCE=$2

    if [ ! -d "/etc/nprobe" ]; then
        echo "Configuration directory /etc/nprobe does not exist: quitting..."
        return 0
    fi

    if [ ! -d "/var/log/nprobe" ]; then
        mkdir -p /var/log/nprobe
    fi

    NUM_CONF="$(find /etc/nprobe/ -name "nprobe-*.conf"|wc -l)"
    if [ "$NUM_CONF" -eq 0 ]; then
        if [ -z $INTERFACE_NAME ]; then
            echo "Missing nprobe configuration"
            MGMT_IP=`hostname -I`
            IF_SELECTED=`ip addr show|grep $MGMT_IP | awk -F" "  '{ print  $NF }'`
            if [ -z $IF_SELECTED ]; then
                ARRAY_IF=`cat /proc/net/dev | grep : | grep -v lo | cut -d : -f 1`
                IF_SELECTED=""
                for IF in $ARRAY_IF ; do
                    if [ -z $IF_SELECTED ]; then
                        IF_SELECTED=$IF
                        fi
                done
                    fi

                    if [ -z $IF_SELECTED ]; then
              # Last resort
                        IF_SELECTED="lo"
                        fi

                        generate_config_file "$IF_SELECTED"
                    fi
                fi

                NUM_TO_START="$(find /etc/nprobe/ -name "*.start"|wc -l)"
                if [ "$NUM_TO_START" -eq 0 ] && [ $FORCE -eq 0 ]; then
        # No instances to start
                    return 0
                fi

                if [ -z $INTERFACE_NAME ]; then
                    NETDEVICES="$(/bin/ls /etc/nprobe | /bin/grep .start | /bin/sed -e 's/-/%/' | /usr/bin/cut -d '%' -f 2 | /bin/sed -e 's/\(.*\)\.start/\1/')"
                else
                    NETDEVICES=$INTERFACE_NAME
                fi

                for E in $NETDEVICES ; do
                    start_nprobe_eth $E $FORCE
                done
}


stop_nprobe() {
    INTERFACE_NAME=$1

    if [ ! -d "/etc/nprobe" ]; then
        echo "Configuration directory /etc/nprobe does not exist: quitting..."
        return 0
    fi

    if [ -z $INTERFACE_NAME ]; then
        NUM_TO_START="$(find /etc/nprobe/ -name "*.start"|wc -l)"
        if [ "$NUM_TO_START" -eq 0 ]; then
            # No instances to start
            return 0
        fi
        NETDEVICES="$(/bin/ls /etc/nprobe | /bin/grep .start | /bin/sed -e 's/-/%/' | /usr/bin/cut -d '%' -f 2 | /bin/sed -e 's/\(.*\)\.start/\1/')"
    else
        NETDEVICES=$INTERFACE_NAME
    fi

    for E in $NETDEVICES ; do
        stop_nprobe_eth $E
    done
}

check_nprobe_status() {
    INTERFACE_NAME=$1

    if [ -z $INTERFACE_NAME ]; then
        NETDEVICES="$(/bin/ls /etc/nprobe | /bin/grep .start | /usr/bin/cut -d '-' -f 2 | /usr/bin/cut -d '.' -f 1)"
    else
        NETDEVICES=$INTERFACE_NAME
    fi

    local NUM_CONFIGED_INSTANCES=0
    local NUM_RUNNING_INSTANCES=0
    local RUNNING_INSTANCES=()
    local NOT_RUNNING_INSTANCES=()

    for E in $NETDEVICES ; do
        if [ -f /etc/nprobe/nprobe-${E}.start ] ; then
            NUM_CONFIGED_INSTANCES=$((NUM_CONFIGED_INSTANCES+1))

            PID_FILE=$(cat /etc/nprobe/nprobe-${E}.conf | grep '\-g='|cut -d '=' -f 2)
            if [ -f $PID_FILE ]; then
                PID=$(cat "${PID_FILE}")
                if [ $PID -gt 0 ]; then
                    IS_EXISTING=$(ps auxw | grep -v grep| grep $PID|wc -l)
                    if [ $IS_EXISTING -gt 0 ]; then
                        NUM_RUNNING_INSTANCES=$((NUM_RUNNING_INSTANCES+1));
                        RUNNING_INSTANCES+=($E);
                    else   # pid file found not not running
                        NOT_RUNNING_INSTANCES+=($E);
                    fi
                fi
            else #no pid
                NOT_RUNNING_INSTANCES+=($E);
            fi
        fi
    done
    if [ $NUM_RUNNING_INSTANCES -eq $NUM_CONFIGED_INSTANCES  ]; then
        echo "UP"
    else
        local MSG="The following instances are not running: "
        for INSTANCE in ${NOT_RUNNING_INSTANCES[@]}; do
            MSG+="$INSTANCE "
        done
        echo "$MSG"
    fi
}

get_status() {
    EXIT_CODE=0
    nprobe_result=$(check_nprobe_status $1);

    if [[ $nprobe_result == UP* ]]; then
        echo "nprobe running"
    else
        echo "$nprobe_result"
        EXIT_CODE=3
    fi

    exit "$EXIT_CODE"
}

########

PARAM_INTERFACE_NAME=$2

logger "nprobe $1 $2"

case "$1" in
    start)
        start_nprobe "$PARAM_INTERFACE_NAME" 0;
        ;;

    force-start | forcestart)
        if [ -z $PARAM_INTERFACE_NAME ]; then
            echo "ERROR: no interface name specified"
            exit 1
        fi

        if [ ! -f /etc/nprobe/nprobe-$PARAM_INTERFACE_NAME.conf ]; then
            echo "ERROR: No configuration file found for $PARAM_INTERFACE_NAME"
            exit 1
        fi
        start_nprobe "$PARAM_INTERFACE_NAME" 1;
        ;;

    stop)
        stop_nprobe "$PARAM_INTERFACE_NAME";
        ;;

    reload | force-reload | restart)
        stop_nprobe "$PARAM_INTERFACE_NAME";
        start_nprobe "$PARAM_INTERFACE_NAME" 0;
        ;;

    status)
        get_status "$PARAM_INTERFACE_NAME";
        ;;

    *)
        echo "Usage: /etc/init.d/nprobe {start|force-start|stop|restart|status} [interface(s)]"
        exit 1
esac

exit 0

**Comment by mAineAc-** [comment]
[debian.txt](https://github.com/ntop/ntopng/files/736114/debian.txt)
[ubuntu.txt](https://github.com/ntop/ntopng/files/736117/ubuntu.txt)

These are the two files. One from the Ubuntu system and the one from the Debian system. both are doing the same thing even this morning.

**Comment by mAineAc-** [comment]
oh yeah, in my hurry the name of the files are actually nprobe-none.conf and nprobe-none.start

**Comment by ValentinaViscarelli** [comment]
@mAineAc- 
I'm not able to reproduce the problem.
Any chance to connect to your machine?
If so, please contact me in private (valentina@ntop.org)
Thanks

**Comment by simonemainardi** [comment]
@ValentinaViscarelli @mAineAc- any news?

**Comment by ValentinaViscarelli** [comment]
I'm not able to reproduce the problem. In order to understand the problem I need to connect to the machine where the problem has been verified.
@mAineAc- 
If  this is possible, please contact me in private (valentina@ntop.org).
Thanks.

**Comment by achurak** [comment]
Just FYI, I had exactly the same issue on my raspberry pi - it would just stuck on this forever:

```
pi@raspi:~$ sudo dpkg --configure -a
Setting up nprobe (7.5.170212-5642) ...
Rebuilding ld cache...
Adding the nprobe startup script
Synchronizing state for nprobe.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d nprobe defaults
Executing /usr/sbin/update-rc.d nprobe enable
(Re)Starting nprobe...
Stopping nProbe none
```
I was poking around and found out that the nprobe's init.d script is trying to figure out the pid by looking into the /tmp/nprobe-none@0.conf:
`PID_FILE=$(cat /tmp/nprobe-${INTERFACE_NAME}@${ID}.conf | grep -E '^\-g=|^\-\-pid\-file='|cut -d '=' -f 2)`
which in my case doesn't contain a path to pid file (ntopng.conf does, but not nprobe.conf according to all the guides I've seen):
```
pi@raspi:~$ more /etc/nprobe/nprobe-none.conf 
--zmq="tcp://*:5556"
--collector-port=2055
-n=none
-i=none
```
The original init.d script checks whether the file exists using the following expression:
`if [ -f $PID_FILE ]; then`
which seems to be always returning true, even in case of the pid_file variable being null. Now bear in mind that I've never done any shell scripting before, but in several examples I was able to google the variable in the if -f test had quotes around it: `if [ -f "$PID_FILE" ]; then`. So I added the quotes into my init.d script and now it gives me the error like it's supposed to: Unable to stop nProbe none: missing pid. No idea how bad it is and how to fix it, but at least it's better than completely breaking the apt-get tool by having to kill it every time it tries to update ntopng/nprobe.

**Comment by ValentinaViscarelli** [comment]
Please try to add this row to your configuration file:

-g=/var/run/nprobe-none.pid

**Comment by achurak** [comment]
Looks like it worked. There are no updates available at the moment, but I ran the "/etc/init.d/nprobe stop" command and it went through with no errors and no freezing. Strangely I didn't see this option required anywhere in the startup guide. Granted I didn't invest too much time into this, so I'll just blame myself :) Thanks for your help!
