### ISSUE TITLE
Ntopng/Nprobe can not create PID file on CentOS 7

### ISSUE THREAD

**Issue by BroadbandCommunicationsNorth** [ntop/ntopng#947]
In case of starting NProbe or Ntopng under "nobody" user, daemons can not create PID files in /run. RPM packet does not have configuration files for it /usr/lib/tmpfiles.d/nprobe.conf /usr/lib/tmpfiles.d/ntopng.conf.

**Comment by BroadbandCommunicationsNorth** [comment]
I am sorry, operating system is CentOS Linux release 7.3.1611 (Core).

**Comment by lucaderi** [comment]
The PID file is created immediately before dropping privileges, thus if you start it as root (before dropping privileges) it should work. Unless you specify the PID path in nprobe.conf (or on the command line) the PID file is not created. I think you should add it to the config file and it will work.

**Comment by BroadbandCommunicationsNorth** [comment]
It works, for sure. 

In CentOS /var/run is a symbolic link for /run, which is temp file system

lrwxrwxrwx.  1 root root     6 Jul 23  2015 run -> ../run

[root@nprobe ~]# mount | grep run
tmpfs on /run type tmpfs (rw,nosuid,nodev,seclabel,mode=755)

At the same time usually every daemon in CentOS puts their PID files in their folder in /var/run with proper rights, they could be root . For instance, mariadb.

[root@nprobe ~]# ls -la /var/run/mariadb/
total 4
drwxr-xr-x.  2 mysql mysql  60 Jan 25 13:14 .
drwxr-xr-x. 28 root  root  740 Jan 25 15:53 ..
-rw-rw----.  1 mysql mysql   5 Jan 25 13:14 mariadb.pid

So, we have to create a config files for every daemon for creating their folders in tempfs , otherwise they will just gone. MariaDB again:

[root@nprobe ~]# rpm -qf /usr/lib/tmpfiles.d/mariadb.conf
mariadb-server-5.5.52-1.el7.x86_64

[root@nprobe ~]# cat /usr/lib/tmpfiles.d/mariadb.conf

d /var/run/mariadb 0755 mysql mysql -

For nprobe and ntopng I have created the same config files, but usually they are in RPM inside. Otherwise, I just did not have them.  

[root@nprobe ~]# cat /usr/lib/tmpfiles.d/nprobe.conf

d /var/run/nprobe 0755 nobody nobody -

[root@nprobe ~]# cat /usr/lib/tmpfiles.d/ntopng.conf

d /var/run/ntopng 0755 nobody nobody -

it is not necessary, in this case it is root, and we can just use /var/run/nprobe.pid

**Comment by BroadbandCommunicationsNorth** [comment]
Just for addition after today update: 
nprobe-7.5.170201-5628.x86_64
ntopng-2.5.170201-2208.x86_64
ntopng-data-2.5.170201-2208.noarch


Nprobe creates PID file with nobody's credentials, so we just need conf file. 
[root@nprobe nprobe]# ls -la /var/run/nprobe/nprobe.pid
-rw-r--r--. 1 nobody nobody 6 Feb  1 10:46 /var/run/nprobe/nprobe.pid

Ntopng still creates PID file under the root.
[root@nprobe run]# ls -la /var/run/ntopng/ntopng.pid
-rw-r--r--. 1 root root 6 Feb  1 10:51 /var/run/ntopng/ntopng.pid
