### ISSUE TITLE
Nprobe does not change user from root to nobody

### ISSUE THREAD

**Issue by BroadbandCommunicationsNorth** [ntop/ntopng#949]
Nprobe does not change user from root to nobody, in case --collector-port 2055.  

[root@nprobe ~]# ps axu |  grep nprobe
root      4328  1.6  0.0 476436 15200 pts/4    Sl+  15:35   0:02 nprobe --zmq tcp://127.0.0.1:1234 -i none -n none --collector-port 2055 --pid-file /var/run/nprobe/nprobe.pid

[root@nprobe nprobe]# nprobe --zmq tcp://127.0.0.1:1234 -i none -n none --collector-port 2055 --pid-file /var/run/nprobe/nprobe.pid
24/Jan/2017 15:35:28 [plugin.c:176] No plugins found in ./plugins
24/Jan/2017 15:35:28 [plugin.c:184] Loading 24 plugins [.so] from /usr/local/lib/nprobe/plugins
24/Jan/2017 15:35:28 [plugin.c:806] Unable to enable plugin DHCP Protocol [/etc/nprobe.license.dhcp]: Missing license file
24/Jan/2017 15:35:28 [plugin.c:806] Unable to enable plugin Diameter Protocol [/etc/nprobe.license.diameter]: Missing license file
24/Jan/2017 15:35:28 [plugin.c:806] Unable to enable plugin DNS/LLMNR Protocol [/etc/nprobe.license.dns]: Missing license file
24/Jan/2017 15:35:28 [plugin.c:806] Unable to enable plugin Export Plugin [/etc/nprobe.license.export]: Missing license file
24/Jan/2017 15:35:28 [plugin.c:806] Unable to enable plugin FTP Protocol [/etc/nprobe.license.ftp]: Missing license file
24/Jan/2017 15:35:28 [plugin.c:806] Unable to enable plugin GTPv0 Signaling Protocol [/etc/nprobe.license.gtpv0]: Missing license file
24/Jan/2017 15:35:28 [plugin.c:806] Unable to enable plugin GTPv1 Signaling Protocol [/etc/nprobe.license.gtpv1]: Missing license file
24/Jan/2017 15:35:28 [plugin.c:806] Unable to enable plugin GTPv2 Signaling Protocol [/etc/nprobe.license.gtpv2]: Missing license file
24/Jan/2017 15:35:28 [plugin.c:806] Unable to enable plugin HTTP Protocol [/etc/nprobe.license.http]: Missing license file
24/Jan/2017 15:35:28 [plugin.c:806] Unable to enable plugin IMAP Protocol [/etc/nprobe.license.email]: Missing license file
24/Jan/2017 15:35:28 [plugin.c:806] Unable to enable plugin Netflow-Lite Plugin [/etc/nprobe.license.nflite]: Missing license file
24/Jan/2017 15:35:28 [plugin.c:806] Unable to enable plugin Oracle Protocol [/etc/nprobe.license.oracle]: Missing license file
24/Jan/2017 15:35:28 [plugin.c:806] Unable to enable plugin POP3 Protocol [/etc/nprobe.license.email]: Missing license file
24/Jan/2017 15:35:28 [plugin.c:806] Unable to enable plugin System process information [/etc/nprobe.license.process]: Missing license file
24/Jan/2017 15:35:28 [plugin.c:806] Unable to enable plugin Radius Protocol [/etc/nprobe.license.radius]: Missing license file
24/Jan/2017 15:35:28 [plugin.c:806] Unable to enable plugin RTP Plugin [/etc/nprobe.license.voip]: Missing license file
24/Jan/2017 15:35:28 [plugin.c:806] Unable to enable plugin S1AP Protocol [/etc/nprobe.license.S1AP]: Missing license file
24/Jan/2017 15:35:28 [plugin.c:806] Unable to enable plugin SIP Plugin [/etc/nprobe.license.voip]: Missing license file
24/Jan/2017 15:35:28 [plugin.c:806] Unable to enable plugin SMTP Protocol [/etc/nprobe.license.email]: Missing license file
24/Jan/2017 15:35:28 [nprobe.c:3510] Valid nProbe Pro license found
24/Jan/2017 15:35:28 [nprobe.c:5271] WARNING: The output interfaceId is set to 0: did you forget to use -Q perhaps ?
24/Jan/2017 15:35:28 [nprobe.c:5274] WARNING: The input interfaceId is set to 0: did you forget to use -u perhaps ?
24/Jan/2017 15:35:28 [nprobe.c:5374] Welcome to nProbe Pro v.7.5.170123 ($Revision: 5612 $) for x86_64-unknown-linux-gnu with native PF_RING acceleration
24/Jan/2017 15:35:28 [nprobe.c:5384] Running on CentOS Linux release 7.3.1611 (Core)
24/Jan/2017 15:35:28 [nprobe.c:5395] [LICENSE] nProbe SystemId: XXXXXXXXXXXXXXX
24/Jan/2017 15:35:28 [nprobe.c:5509] Sample rate [packet: 1][flow: 1]
24/Jan/2017 15:35:28 [nprobe.c:7751] Welcome to nProbe v.7.5.170123 for x86_64-unknown-linux-gnu
24/Jan/2017 15:35:28 [plugin.c:1078] 0 plugin(s) enabled
24/Jan/2017 15:35:28 [nprobe.c:7278] Non IPv4/v6 traffic is discarded according to the template
24/Jan/2017 15:35:28 [util.c:430] GeoIP: loaded AS config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNum.dat
24/Jan/2017 15:35:28 [util.c:441] GeoIP: loaded AS IPv6 config file /usr/share/ntopng/httpdocs/geoip/GeoIPASNumv6.dat
24/Jan/2017 15:35:28 [nprobe.c:7927] IPv6 traffic will NOT be exported/accounted by this probe
24/Jan/2017 15:35:28 [nprobe.c:7928] due to configuration options (e.g. use NetFlow v9)
24/Jan/2017 15:35:28 [nprobe.c:7929] Please use -V to set the version to other than NetFlow V5
24/Jan/2017 15:35:28 [nprobe.c:8077] Not capturing packet from interface (collector mode)
24/Jan/2017 15:35:28 [util.c:4043] Initializing ZMQ as server
24/Jan/2017 15:35:28 [util.c:4086] Succesfully created ZMQ endpoint tcp://127.0.0.1:1234
24/Jan/2017 15:35:28 [collect.c:143] Flow collector listening on port 2055 (IPv4/v6)
24/Jan/2017 15:35:28 [nprobe.c:8303] nProbe started successfully

Maintenance:   Until Fri Jan 12 14:59:44 2018 [352 days left]

**Comment by lucaderi** [comment]
Fixed. Overnight a new package will include the fix
