### ISSUE TITLE
Alerts in Hosts

### ISSUE THREAD

**Issue by edo33** [ntop/ntopng#950]
Hi. Ive got debian 8 running on server and ntopng v.2.5.170124. Everytime I try to open alerts in host it give me this error:
![chyba](https://cloud.githubusercontent.com/assets/10207340/22271822/e2917c4e-e296-11e6-807d-c936c8560417.jpg)

**Comment by emanuele-f** [comment]
Hi, I cannot reproduce the issue in my installation. Can you post your alerts database file so that we can inspect it? Please follow these instructions:

1. find your interface name: Select the interface from the "Interfaces". Take note of the "Id" cell.
2. post here the file located at */var/tmp/ntopng/[Id]/alerts/alerts_v3.db*

**Comment by edo33** [comment]
Hi. Thanks for fast reaction. Yesterday I was upgrading ntopng from v2.4 to v2.5. In the path /var/tmp/ntopng/1/ Ive got only 2 folders - rrd and top_talkers. I was looking for the alerts_v3.db but db is only in the path /disk/temp/ntopng/1/alerts/... and the last date and time which was db created is date before the upgrade.

**Comment by emanuele-f** [comment]
You should remove old alerts database since it is not compatible with new 2.5 format

**Comment by edo33** [comment]
Ive removed the old database and after restart ntopng creates new but error is still present. When I was looking into the tables - they are empty.... And every client show 0 alerts.
![bez nazvu](https://cloud.githubusercontent.com/assets/10207340/22321998/3ae55dea-e399-11e6-9fc8-54ee33599cfa.jpg)
[alerts_v3.zip](https://github.com/ntop/ntopng/files/731655/alerts_v3.zip)

**Comment by emanuele-f** [comment]
I've managed to reproduce your issue: it appears when alerts are disabled. I've fixed it in commit 096db1085d46e3c9d712325acaf0a4266c2ce223 .
Please enable alerts from the preferences page. Thank you.
