### ISSUE TITLE
SSL don't work in nightly build

### ISSUE THREAD

**Issue by DelltaPeak** [ntop/ntopng#96]
ntopng can't find on start the SSL certificate, works with stable build.
[src/HTTPserver.cpp:449] HTTPS Disabled: missing SSL certificate /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem

Using v.2.0.150729

**Comment by lucaderi** [comment]
We have made some changes and in packages SSL works for me. Please update to the latest version and if not working please specify the platform you are using

**Comment by DelltaPeak** [comment]
Doesn't work with latest nightly build (but in stable).
We are using: Centos 6.6, ntopng v.2.0.150805, wildcard ssl with a key, crt and ca bundle.

They key, crt and ca bundle is inserted in /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem

Logmessage: 
05/Aug/2015 10:17:25 [src/HTTPserver.cpp:449] HTTPS Disabled: missing SSL certificate /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem
05/Aug/2015 10:17:25 [src/HTTPserver.cpp:451] Please read https://svn.ntop.org/svn/ntop/trunk/ntopng/README.SSL if you want to enable SSL.
