### ISSUE TITLE
Ability to export data to an intermediate broker rather than directly to ElasticSearch

### ISSUE THREAD

**Issue by almico** [ntop/ntopng#961]
Being able to save data to ElasticSearch is a useful feature to have something running quickly.
It would be great, though, to be able to "decorate" the data generated by ntopng.
For example:
- Put IPV4_SRC_ADDR and IPV6_SRC_ADDR into a single IP_SRC_ADDR field
- Add custom fields
- Geolocalize IPv6
- Add a field with the textual representation of L4 protocol name
- ...

My suggestion is to send json records to REDIS or anything like that.

**Comment by simonemainardi** [comment]
hi, 

why you don't use ES as the 'intermediate broker'. You can query it and crunch/augment/aggregate/decorate data as you wish. Once you've done you can decide to drop the old indices and keep only the aggregated data.

In particular:

> Put IPV4_SRC_ADDR and IPV6_SRC_ADDR into a single IP_SRC_ADDR field

you can do this with a query to ES

> Add custom fields

if you use ntopng with nProbe you get all the custom fields specified in option -T inside ES

**Comment by almico** [comment]
Thank you for the suggestion.
Ignoring the imposed overhead, polling ES to get records would be the only option and even creating a procedure that won't miss records and won't create duplicates on live data would be a pain...
Dropping the index is something that makes me think you didn't consider applying my suggestion to live data, though...

**Comment by simonemainardi** [comment]
The degree of flexibility requested for data decoration is something that should not be done inside ntopng. Indeed, it's role is to provide accurate network data not custom decorations.

We believe that deep data decoration and augmentation is something that must be done after ntopng in the data pipeline. Dedicated software already exists for this kind of operations, see for example Logstash https://www.elastic.co/products/logstash  and the pretty well known combination of ES+Logstash+Kibana also known as ELK.

**Comment by almico** [comment]
May be I was not clear enough when I presented the problem ("data decoration") and proposed a solution ("redis or anything similar").
I totally agree that decoration should be done outside ntopng and I push that forward, stating that even saving to a database should be done outside ntopng.
Having ntopng save to a file or to any intermediate broker (I suggested Redis because I think ntopng already uses it) should be the way to go.
If you try just for a minute to use logstash to decorate data already saved to Elasticsearch, I think you will have quite some hard time.

**Comment by simonemainardi** [comment]
> If you try just for a minute to use logstash to decorate data already saved to Elasticsearch, I think you will have quite some hard time.

I know people that use it and apart from spending some time for confguration, it works well

> I totally agree that decoration should be done outside ntopng and I push that forward, stating that even saving to a database should be done outside ntopng.

well 

> Having ntopng save to a file or to any intermediate broker (I suggested Redis because I think ntopng already uses it) should be the way to go.

Have a look at nprobe. With it you can export to plain text files
