### ISSUE TITLE
Remote and local talkers mixed up

### ISSUE THREAD

**Issue by filemoon** [ntop/ntopng#962]
ntopng Pro [Small Business Edition]/Embedded v.2.5.170130 (ARM)

Config same as always:

-G=/var/log/ntopng.pid
-d=/var/lib/ntopng
-i=tcp://127.0.0.1:5556
-m="10.0.1.0/24,10.0.2.0/24,10.0.0.0/24"
-n=1
-X=100000
-x=16000

As result remote/local sections are all mixed up.

![screen shot 2017-02-02 at 19 37 06](https://cloud.githubusercontent.com/assets/14888287/22565358/b810ffc2-e97f-11e6-9fb1-769801b1b066.jpg)

**Comment by emanuele-f** [comment]
Can you experience this with latest version? If you go into the *Hosts* page and apply the filter to show local/remote hosts only, are they mixed up in that page?

**Comment by filemoon** [comment]
hi.

This is the last ARM version form your repository.
Yes - they are same (when I'm applying filters - local and remote are present for both filters mixed up).

**Comment by simonemainardi** [comment]
The issue has already been sorted. @lucaderi can you please trigger a new ARM build as the latest doesn't include the fix. Thank you.

**Comment by emanuele-f** [comment]
@filemoon please install the latest ARM package since it contains the fix (tested on a raspberry). Reopen if necessary.
