### ISSUE TITLE
Missing data and some errors

### ISSUE THREAD

**Issue by Alestor** [ntop/ntopng#963]
Hi,

ntopng isn't saving some data anymore:

- Top Application Traffic Last Day View (data missing)
- Per local Host traffic statistics
- Per Interface Application Traffic

Maybe some more but thats all I found at the moment.

Starting ntopng is logging some warnings:
[HostPools.cpp:266] WARNING: JSON Parse error [unexpected end of data] key: ntopng.prefs.2.host_pools.dump:

Every 5 minutes I also get a warning like

[Lua.cpp:5837] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/host_pools_utils.lua:198: attempt to call global 'isCaptivePortalActive' (a nil value)]

v.2.5.170202 [Enterprise/Professional Edition]
GIT rev:   dev:ad12492b10d54c530c4c58c0bdd333b688c07559:20170202
Pro rev:   r930
System Id: 390956AE7A056206
Built on:  Debian GNU/Linux 8.2 (jessie)

**Comment by emanuele-f** [comment]
Hi, the first error may be caused by an incorrect shutdown but it's not a problem.
The second one is probably the cause of the data saving issue. I've made a fix af90324. Please try the tomorrow version.

**Comment by Alestor** [comment]
Thanks, your fix works fine so far.

Another Question: What feature does the Enterprise Version include and how may I get a license. can't find this in the shop.

**Comment by emanuele-f** [comment]
Hi, currently we only provide Enterprise licences on request. Please contact us privately for more information since github is not the right place for this. Thank you.
