### ISSUE TITLE
ntopng service not using correct mysql.sock

### ISSUE THREAD

**Issue by njcwotx** [ntop/ntopng#968]
My mysql install uses another path.  the my.cnf file [client] directive and [mysqld] directive is using the correct path to mysql.sock, I can access it from command line, but when I start ntop the path is still the default.  mysql answers up from an external client too using correct username and password.  the issue I see is the '/var/lib/mysql/mysql.sock' is the wrong path and needs to be '/storage/mysql/mysql.sock'

Feb 06 14:48:13 server.name.com systemd[1]: Starting Start/stop ntopng program...
Feb 06 14:48:13 server.name.com ntopng[4043]: [MySQLDB.cpp:610] ERROR: Failed to connect to MySQL: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2) [localhost:root]
Feb 06 14:48:13 server.name.com ntopng[4043]: [MySQLDB.cpp:610] ERROR: Failed to connect to MySQL: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2) [localhost:root]
Feb 06 14:48:13 server.name.com ntopng[4043]: [MySQLDB.cpp:79] ERROR: Unable to connect: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
Feb 06 14:48:13 server.name.com ntopng[4043]: [main.cpp:280] ERROR: Unable to create database schema, quitting.

I could be missing another config somewhere else, I was able to use mysql -u root -p and create the ntopng database.

**Comment by njcwotx** [comment]
I am able to telnet to localhost:3306

**Comment by simonemainardi** [comment]
just tested with a non-standard sock file and it works.  See this:

```
Simones-MacBook-Pro:ntopng simone$ sudo   ./ntopng  -i en0  -i en4 "100.64.0.0/10" -F"mysql;/opt/local/var/run/mysql56/mysqld.sock;ntopng;flows;root;xxx" --enable-flow-activity
07/Feb/2017 15:21:54 [Prefs.cpp:1023] Flow activity detection enabled
07/Feb/2017 15:21:54 [Ntop.cpp:1286] Setting local networks to 127.0.0.0/8
07/Feb/2017 15:21:54 [Redis.cpp:109] Successfully connected to redis 127.0.0.1:6379@0
07/Feb/2017 15:21:54 [MySQLDB.cpp:581] Attempting to connect to MySQL for interface en0...
07/Feb/2017 15:21:54 [MySQLDB.cpp:621] Succesfully connected to MySQL [/opt/local/var/run/mysql56/mysqld.sock:root] for interface en0
07/Feb/2017 15:21:54 [PcapInterface.cpp:86] Reading packets from interface en0...
07/Feb/2017 15:21:54 [Ntop.cpp:1391] Registered interface en0 [id: 0]
07/Feb/2017 15:21:54 [BatchedMySQLDB.cpp:61] Executing queryLoop()
07/Feb/2017 15:21:54 [MySQLDB.cpp:581] Attempting to connect to MySQL for interface en4...
07/Feb/2017 15:21:54 [MySQLDB.cpp:621] Succesfully connected to MySQL [/opt/local/var/run/mysql56/mysqld.sock:root] for interface en4
07/Feb/2017 15:21:54 [PcapInterface.cpp:86] Reading packets from interface en4...
```

make sure to replace, inside the -F configuration string, the host with the abs path of the socket file as shown above.
