### ISSUE TITLE
no license for pro version

### ISSUE THREAD

**Issue by DelltaPeak** [ntop/ntopng#97]
Within the latest nightly build we can't use our pro license.
Deployed in:
/etc/ntopng.license
/etc/ntopng/ntopng.license

There is no way to activate our license in ntopng webinterface.

**Comment by lucaderi** [comment]
I have just checked and it works for me. What platform are you using?

**Comment by DelltaPeak** [comment]
Latest CentOS 6. On stable or older nightly builds (older than 4 days) i put the license by a link into the ntopng httpd without using a license file in /etc. This link disappeared with the latest nightly build.

**Comment by lucaderi** [comment]
If you have /etc/ntopng.license the license we assume is there and this is the place where you have the license. If such file does not exist it works as before. So I believe you have the license in such file and that is why you do not see a form in the about box.

**Comment by DelltaPeak** [comment]
Without /etc/ntopng.license there is no link, ntopng starts direct in community mode without 10 minutes pro mode.
But i inserted the license:
ls /etc/ntopng.license
/etc/ntopng.license

There is nothing about a license in our ntopng.log

**Comment by lucaderi** [comment]
I am not sure I understand. Please remove /etc/ntopng.license and the old "set license" box in the About menu should re-appear

**Comment by DelltaPeak** [comment]
Already tested (now again) but no box there:
![ntopng](https://cloud.githubusercontent.com/assets/13550377/8960616/16f2d5de-3611-11e5-871f-6d00cfe695c9.png)

**Comment by lucaderi** [comment]
I have just checked the package and after the latest fixes is ok. The license can go in /etc/ntopng.license or through the web GUI in redis.

**Comment by brconflict** [comment]
Still broken for me. Same issue. I also tried removing the ntopng.license file. 

License	GNU GPLv3
Version	2.0.150910 - Community Edition
Platform	Debian jessie/sid (x86_64) - 64 bit

**Comment by lucaderi** [comment]
@brconflict See this
[root@centos6 deri]# ntopng --version
v.2.0.150912 [Professional Edition]
GIT rev:   dev:fe6becaa18fc1c98214a6c00bcfa2f82af7019b7:20150912
Pro rev:   r450
System Id: 12DC4E4000000789

Can you please check this on your PC and report?

**Comment by lucaderi** [comment]
Works for me

**Comment by RobertLukan** [comment]
Hi,

I have same issue as DeltaPeak. 

~$ ntopng --version
v.2.0.151001 [Community Edition]
GIT rev:   dev:e97bc6c4251e934515c014c2561e7c7b60f47931:20151001
~$

**Comment by lucaderi** [comment]
What platform are you using? Please make sure you are using the binary packages available at http://packages.ntop.org

**Comment by RobertLukan** [comment]
It works now. I have used git directly, which doesnt support pro features. Thanks

**Comment by dheerajmpai** [comment]
Why do you want to use the Nightly version. Why not use the stable one?
