### ISSUE TITLE
Getting JSON output from .pcap files with the CLI

### ISSUE THREAD

**Issue by delgadod** [ntop/ntopng#973]
Hello,

I am trying to process a large number of .pcap files with ntopng and get the JSON flow information.

I know it is possible to do so from the web GUI, but wanted to know if there was a way to do so from the CLI to make automating the process easier?

Apologies if this is trivial.

**Comment by simonemainardi** [comment]
sure, 

you can get the JSON (paginated) list of flows with

```
http://localhost:3000/lua/get_flows_data.lua?currentPage=1&perPage=10&sortColumn=column_&sortOrder=desc
```

Then you can use the flow key received as part of the JSON reply above to get additional detailed flow information

```
http://localhost:3000/lua/flow_stats.lua?ifid=1&flow_key=2565068408
```
