### ISSUE TITLE
Hosts pool parsing error

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#978]
It looks there is a parsing error in host pools

11/Feb/2017 11:19:09 [HostPools.cpp:266] WARNING: JSON Parse error [unexpected end of data] key: ntopng.prefs.0.host_pools.dump: 
11/Feb/2017 11:19:09 [HostPools.cpp:266] WARNING: JSON Parse error [unexpected end of data] key: ntopng.prefs.0.host_pools.dump: 
11/Feb/2017 11:19:09 [HostPools.cpp:266] WARNING: JSON Parse error [unexpected end of data] key: ntopng.prefs.0.host_pools.dump: 
11/Feb/2017 11:19:09 [HostPools.cpp:266] WARNING: JSON Parse error [unexpected end of data] key: ntopng.prefs.0.host_pools.dump: 

===

1486808430.618843 [0 127.0.0.1:60139] "SMEMBERS" "ntopng.prefs.0.host_pools.pool_ids"
1486808430.619043 [0 127.0.0.1:60139] "SMEMBERS" "ntopng.prefs.0.host_pools.members.1"
1486808430.619230 [0 127.0.0.1:60139] "SMEMBERS" "ntopng.prefs.0.host_pools.members.2"
1486808430.619731 [0 127.0.0.1:60139] "SMEMBERS" "ntopng.prefs.0.host_pools.members.3"
1486808430.619989 [0 127.0.0.1:60139] "SMEMBERS" "ntopng.prefs.0.host_pools.members.4"
1486808430.620342 [0 127.0.0.1:60139] "HGET" "ntopng.prefs.0.host_pools.dump" "1"
1486808430.620891 [0 127.0.0.1:60139] "LPUSH" "ntopng.trace" "11/Feb/2017 11:20:30 [HostPools.cpp:266] WARNING: JSON Parse error [unexpected end of data] key: ntopng.prefs.0.host_pools.dump: "
1486808430.622629 [0 127.0.0.1:60139] "HGET" "ntopng.prefs.0.host_pools.dump" "2"
1486808430.622828 [0 127.0.0.1:60139] "LPUSH" "ntopng.trace" "11/Feb/2017 11:20:30 [HostPools.cpp:266] WARNING: JSON Parse error [unexpected end of data] key: ntopng.prefs.0.host_pools.dump: "
1486808430.623290 [0 127.0.0.1:60139] "HGET" "ntopng.prefs.0.host_pools.dump" "3"
1486808430.623410 [0 127.0.0.1:60139] "LPUSH" "ntopng.trace" "11/Feb/2017 11:20:30 [HostPools.cpp:266] WARNING: JSON Parse error [unexpected end of data] key: ntopng.prefs.0.host_pools.dump: "
1486808430.623707 [0 127.0.0.1:60139] "HGET" "ntopng.prefs.0.host_pools.dump" "4"
1486808430.623840 [0 127.0.0.1:60139] "LPUSH" "ntopng.trace" "11/Feb/2017 11:20:30 [HostPools.cpp:266] WARNING: JSON Parse error [unexpected end of data] key: ntopng.prefs.0.host_pools.dump: "
1486808430.711622 [0 127.0.0.1:60139] "SADD" "ntopng.prefs.0.host_pools.pool_ids" "0"
1486808430.711776 [0 127.0.0.1:60139] "HSET" "ntopng.prefs.0.host_pools.details.0" "name" "Not Assigned"
===

$ redis-cli "HGET" "ntopng.prefs.0.host_pools.dump" "1"
(nil)
$ redis-cli "HGET" "ntopng.prefs.0.host_pools.dump" "2"
(nil)
$ redis-cli "HGET" "ntopng.prefs.0.host_pools.dump" "2"
$ redis-cli "SMEMBERS" "ntopng.prefs.0.host_pools.members.1"
(empty list or set)
$ redis-cli "SMEMBERS" "ntopng.prefs.0.host_pools.members.2"
1) "c4:2c:03:06:49:fe"
$ redis-cli "SMEMBERS" "ntopng.prefs.0.host_pools.members.3"
(empty list or set)
$ redis-cli "SMEMBERS" "ntopng.prefs.0.host_pools.members.4"

**Comment by simonemainardi** [comment]
@emanuele-f please check, this error occurs during ntopng startup and is related to the serialization of host pool counters

**Comment by emanuele-f** [comment]
It should be fixed with ee480c36193ae68c64f15a7ee6bdf682f8839ab6
