### ISSUE TITLE
Protocol version check can trigger alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#979]
With https://github.com/ntop/ntopng/commit/34c5bce183a472c92f63b2eb3804c87a52eb30ec is now possible to report SSH client/server version

![screen shot 2017-02-11 at 11 23 50](https://cloud.githubusercontent.com/assets/4493366/22853087/ad8035a4-f04c-11e6-8ba2-9c04f8d63947.png)

It would be nice to specify (under preferences, on a file or similar) for local hosts, the minimum protocol version we consider safe and trigger alerts if some of local hosts are running old protocol versions. This way we can implement a minimal yet effective control over old software versions that can lead to security issues.

Soon this feature, currently available for SSH, should/will be implemented for other protocols such as HTTP (both server and browser version taken from the user-agent string) or OS version (e.g. NetBIOS protocol)

**Comment by simonemainardi** [comment]
Added as task in https://github.com/ntop/ntopng/issues/1808
