### ISSUE TITLE
Check empty http parameters

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#983]
As highlighted in https://github.com/ntop/ntopng/commit/01f47e04fd7c8d54399c9e465f823f0017069f8f, preventing "empty-string" HTTP parameters from being passed to lua, could break some pages.

It should be checked whether this is true and possibly implement a solution

**Comment by emanuele-f** [comment]
Moreover, after the change, another issue appears when selecting an expired host: 
`ntopng/scripts/lua/host_details.lua:89: attempt to index global 'host' (a nil value)`
