### ISSUE TITLE
Realtime traffic

### ISSUE THREAD

**Issue by james-shumba** [ntop/ntopng#984]
How can I reset the data to show me realtime data only from a specific period, currently its showing cumulative host data for a long period, am I able to specify what period for a a host the data should show like the last 1 hour, last 1 week, last week, or at least just show exactly what hosts are pushing too much traffic at this particular moment.

am using windows version, version 2.4.160627 - Pro Small Business Edition

**Comment by emanuele-f** [comment]
Hi, you can review host traffic for a specific time period by selecting the host of interest, then, from the host page, click the [graph](http://fontawesome.io/icon/area-chart/) icon. From that page you can specify the time interval to view in the graph (1h, 12h, 1d, 1M and so on).

You can see the hosts which are generating most of the traffic at this particular moment directly from the dashboard. You can also open the "hosts" page and click on the *Throughput* column to sort active hosts by throughput.

**Comment by james-shumba** [comment]
Hi,

I dont have the graph icon, see attached
![captureccc](https://cloud.githubusercontent.com/assets/23502107/22969953/fb6d953e-f378-11e6-8024-ac105068b9f4.JPG)

**Comment by emanuele-f** [comment]
Graphs are only available for *local* hosts. You can configure your local networks with the *-m* option.

**Comment by emanuele-f** [comment]
Please reopen if necessary

**Comment by james-shumba** [comment]
Thanks



Sent from my Samsung Galaxy smartphone.


-------- Original message --------
