### ISSUE TITLE
Engaged and Past alerts page displays No Results Found

### ISSUE THREAD

**Issue by lawrencecare2** [ntop/ntopng#987]
My Alerts page displays No Results Found for engaged and past alerts, but flow alerts are working. Also, I am able to see the number of accumulated alerts count in the purging confirm button.

ntopng v.2.5.170216

CentOS Linux release 7.3.1611 (Core)

**Comment by emanuele-f** [comment]
This should be fixed with 4a5f0cf8a36343f941dc88b854630ae1f01e50c1. A new package will be available tomorrow. Please, reopen if necessary.
