### ISSUE TITLE
Historical interface not working on RHEL 7

### ISSUE THREAD

**Issue by eloybrea** [ntop/ntopng#99]
I've setup nprobe and ntopng with the newest stable version
from the repository. When I am on the historical interface, I try to load the data by date and then it just
displays: "Well Done! Data loading process started successfully"

I don't see any loading process or animation.

OS: Redhat 7 (latest patches)
Nprobe version: v.7.1.150531
Ntopng version: v.2.0.150531

root@HOSTNAME:/var/tmp/ntopng# find . -name *.sqlite | du -sh
25G	.

# cat /etc/ntopng/ntopng.conf 
-i tcp://127.0.0.1:5556 
-m 10.22.0.0/16,10.21.0.0/16,10.20.0.0/16,10.23.0.0/16,10.0.0.0/16,192.168.0.0/16
--dump-flows db
-A=2 
-C=
-D=all
-E=all
-S=all 
-p /etc/ntopng/custome.protos
-G=/var/tmp/ntopng.pid

# cat /etc/nprobe/nprobe-ens192.conf
-g=/var/run/nprobe.pid
-i ens224
-n none 
--collector-port 6343 
--zmq tcp://127.0.0.1:5556

**Comment by lucaderi** [comment]
Please use the development version that has some fixes, however we'll dismiss the historical interface as in the current incarnation.

**Comment by lucaderi** [comment]
We're rewriting the historical interface. Please follow #61.
