### ISSUE TITLE
ntopng stop after 5 minutes

### ISSUE THREAD

**Issue by laterano** [ntop/ntopng#990]
Hello,
after reinstalling the correct license for Ntopng the service is stopped exactly after 5 minutes of use, reading between the logs was released this statement:

22/Feb/2017 16:25:04 [MySQLDB.cpp:582] Attempting to connect to MySQL for interface zc:em2...
22/Feb/2017 16:25:04 [MySQLDB.cpp:622] Succesfully connected to MySQL [localhost:userntop] for interface zc:em2
#########################################################################
Demo time elapsed: please get a valid license
#########################################################################
22/Feb/2017 16:30:04 [main.cpp:43] Shutting down...
22/Feb/2017 16:30:04 [MySQLDB.cpp:569] Disconnected from MySQL for interface zc:em2...
22/Feb/2017 16:30:06 [ProtoStats.cpp:35] [IPv4]  973.58 MB/1.02 M Packets
22/Feb/2017 16:30:06 [ProtoStats.cpp:35] [IPv6]  66.06 KB/411.00 Packets
22/Feb/2017 16:30:06 [ProtoStats.cpp:35] [ARP]   71.22 KB/1.21 K Packets
22/Feb/2017 16:30:06 [ProtoStats.cpp:35] [MPLS]  0 B/0.00 Packets
22/Feb/2017 16:30:06 [ProtoStats.cpp:35] [Other] 2.24 KB/5.00 Packets
22/Feb/2017 16:30:06 [PF_RINGInterface.cpp:126] Terminated packet polling for zc:em2
22/Feb/2017 16:30:06 [Ntop.cpp:1423] Interface zc:em2 [running: 0]
22/Feb/2017 16:30:06 [main.cpp:54] Deleted PID /var/run/ntopng.pid [rc: -1]
22/Feb/2017 16:30:06 [HTTPserver.cpp:786] HTTP server terminated
22/Feb/2017 16:30:06 [NetworkInterface.cpp:509] Flushing host contacts for interface zc:em2
22/Feb/2017 16:30:06 [NetworkInterface.cpp:1854] Cleanup interface zc:em2
22/Feb/2017 16:30:06 [MySQLDB.cpp:569] Disconnected from MySQL for interface <unknown>...
22/Feb/2017 16:30:06 [AddressResolution.cpp:44] Address resolution stats [79 resolved][45 failures]

This happens to every manual restart of the service ntopng, i do not understand what is the license to which it relates.

Fabio

**Comment by emanuele-f** [comment]
You are using zero copy pfring (see interface "zc:em2"), which requires a separate license.

**Comment by laterano** [comment]
the license is present, I see below ntop-licenses-configuration-ZC

**Comment by emanuele-f** [comment]
Where is located the license file?

**Comment by laterano** [comment]
in etc/pf_ring/mac address

**Comment by emanuele-f** [comment]
Please contact us privately http://www.ntop.org/support/need-help-2/contact-us/ for licence issues.
