### ISSUE TITLE
Problem to install on fresh RedHat 7.3 due to dependencies problems

### ISSUE THREAD

**Issue by PandaWawawa** [ntop/ntopng#991]
Hi everyone,

I have trouble trying to install ntopng on fresh Redhat 7.3

I follow the instructions on http://packages.ntop.org/centos/
But it seems that there is some problem  with mysql, numactl and rrdtools denpendencies which are not packaged 

I've managed to install numactl, MariaDB-common and rrdtools which are needed,
But when I retry to install it leads to several messages like : 
"Http://packages.ntop.org/centos/7Server/x86_64/Packages/cento-1.3.170222-180.x86_64.rpm: [Errno -1] The package does not match the expected download."

Any clue about this ?

**Comment by emanuele-f** [comment]
Hi, can you try to install the latest version of the packages located at http://packages.ntop.org/rpm7/ ?

**Comment by PandaWawawa** [comment]
Hi ! 

Yup that solved my problem, installing manually by these rpm
Thank you :)

(Maybe some modification should be done on the centos repo)

**Comment by emanuele-f** [comment]
Maybe there is a problem with your installation. I suggest you to clean and retry to install ntopng following the instructions on http://packages.ntop.org/centos/ for CentOS 7. You should be able to pull mysql and other dependencies automatically from the package manager.

**Comment by emanuele-f** [comment]
Closing. Please reopen if necessary
