### ISSUE TITLE
which folder location to put License number in Centos 7  

### ISSUE THREAD

**Issue by Dhardeki** [ntop/ntopng#993]
Hi Everyone, I'm newbie in Centos 7, I would like to activate the license from the Community license into the professional once, and I have got the license number and I have followed the instruction but it still says the license still Community License. Can you please to give me the instruction ?
Thank you for you all support.
Cheers

**Comment by emanuele-f** [comment]
Hi, license can either be entered via the ntopng web ui, in the about page, or manually by writing it to the file `/etc/ntopng.license`.
Please read http://www.ntop.org/support/faq/my-license-does-not-work-what-can-i-do/ for more details

**Comment by Dhardeki** [comment]
Hi Emanuele,

thank you for your response, I had tried both of them, also I tried the step in in that link to check the license and it looks ok, but in the GUI it says the version is "Community Edition”

Cheers,
Deki

**Comment by emanuele-f** [comment]
Please post the startup log of ntopng, it will contain hints to find out where the problem is

**Comment by emanuele-f** [comment]
@Dhardeki did you managed to solve the problem?

**Comment by Dhardeki** [comment]
Dear Emanuele,

Thank you for your support, I still have the same problem.
Where I can’t activate the license, it still says Community License, I tried follow the instruction but not worked.
Is there something wrong from my side ?

Cheers,
Deki

**Comment by emanuele-f** [comment]
@Dhardeki please post the startup log of ntopng so that we can inspect it

**Comment by Dhardeki** [comment]
Hi Emanuele,

I did it, also I tried restart the server, but unfortunately the problem still persist.

Cheers,
Deki

**Comment by emanuele-f** [comment]
I cannot see the startup log of ntopng in your previous messages, maybe it's related to the fact that you are using standard email to reply in github. Please contact us directly www.ntop.org/support/need-help-2/contact-us/ Thank you

**Comment by simonemainardi** [comment]
@Dhardeki try to add --online-license-check to the ntopng options

**Comment by Dhardeki** [comment]
Dear Simone,

Sorry for delay response since we are in difference zone.
Could you please send me the instruction how to do that.
Thank you and we appreciate it.

Cheers,
Deki

**Comment by simonemainardi** [comment]
@Dhardeki please put the license string generated under file /etc/ntopng.license
also make sure you are not executing ntopng with option --community

**Comment by Dhardeki** [comment]
Dear Simone,

I tried for both, online and manual, I send you the screenshot.
Is there something I missed?

Cheers,
Deki

**Comment by simonemainardi** [comment]
@Dhardeki screenshot is not visible, please try to post it through the github web page.

Also I would like to see:
- full ntopng startup command
- full console output
