### ISSUE TITLE
ntopng issues

### ISSUE THREAD

**Issue by izzie88** [ntop/ntopng#995]
Hi Luca,
I am having the issues below with ntopng, Please help

Feb 24 09:36:06 NTOP-DPI ntopng[21347]: [CollectorInterface.cpp:59] ERROR: Unable to connect to ZMQ endpoint tcp://*:5556c
Feb 24 09:36:06 NTOP-DPI ntopng[21347]: [main.cpp:190] ERROR: Unable to create interface tcp://*:5556c
Feb 24 09:36:06 NTOP-DPI ntopng[21347]: [main.cpp:223] ERROR: Startup error: missing super-user privileges ?

**Comment by emanuele-f** [comment]
Hi, can you post here your ntopng command line options / your ntopng configuration file?

**Comment by lucaderi** [comment]
@izzie88 You have an errore in your command line. tcp://:5556c is wrong. User for instance tcp://127.0.0.1:5556c
