### ISSUE TITLE
ntopng Pro can't access traffice_report page

### ISSUE THREAD

**Issue by IT-MPIC** [ntop/ntopng#996]
With a ntopng Pro license I can't access the traffic report overview page ("This feature is only available in the ntop enterprise version"). But I can't get an enterprise version at the moment.
How can I access to this page now?

Thanks
Torsten Helmer @MPIC

**Comment by emanuele-f** [comment]
Indeed you need the Enterprise version, which is in trial state for now. Please contact us privately to get more information.
