### ISSUE TITLE
License Problem

### ISSUE THREAD

**Issue by FlorianJedlicka** [ntop/ntopng#997]
I got my license for the ntopng version, and put it into the Gui of it. However, it still says in the bottom, to be the community version.
I´ve tried the online license command, and it showed "started packed pooling" and after that it said " SQL Error: Database is locked". 
The SystemID is the same, as we´ve used it to get the license.

**Comment by emanuele-f** [comment]
If you try to disable both alerts (add -H option) and mysql dump (remove -F option), do you get pro mode? Can you post the full startup log?

**Comment by FlorianJedlicka** [comment]
What alerts do you mean?

**Comment by emanuele-f** [comment]
Alerts are not available in stable version. What exact ntopnt version do you have (use -v option or get it from the web ui)? On stable version, just remove the -F option.

**Comment by FlorianJedlicka** [comment]
I have the 2.4.170109 - Community Edition

**Comment by emanuele-f** [comment]
So please post the full ntopng log.

**Comment by FlorianJedlicka** [comment]
I´ve just logged off. I only have access to it on friday, so I can´t post it until next week

**Comment by FlorianJedlicka** [comment]
So back at it again. What can I do? Should I post the configuration?

**Comment by emanuele-f** [comment]
Yes, we need configuration and full log. Maybe it's better if you contact us privately http://www.ntop.org/support/need-help-2/contact-us/

**Comment by simonemainardi** [comment]
@FlorianJedlicka please provide information as suggested by @emanuele-f

**Comment by FlorianJedlicka** [comment]
Only on friday, but I think that this will solve the problem

**Comment by simonemainardi** [comment]
yes. In case you will still experience difficulties in installing the license, then please re-open issue with the requested information.
